### ISSUE TITLE
Migrating from Mage1 -> Mage2 can be optimized

### ISSUE THREAD

**Issue by SchumacherFM** [magento/magento2#1000]
I have written SQL database migration tool (not yet open source) which runs pretty well.

The tools does a bunch of fixes and writes all executed SQL scripts into `core_resource` tables column `version`. Column `data_version` is null.

After my migration tools has finished the setup scripts in the modules `data` folder needs to be run to apply some Magento2 stuff to your Magento1 database. I call the script:
```
root/setup $ php index.php update
```

Due to existing data from Magento1 the data updates will fail. I have to disable the data update for modules:

```
            'log' => '1.6.0.0',
            'checkout' => '2.0.0',
            'directory' => '2.0.0',
            'sales' => '2.0.0',
            'reports' => '2.0.0',
            'review' => '2.0.0',
            'tax' => '2.0.0',
```

and also commented out in files:

- Customer/data/customer_setup/data-install-2.0.0.php Lines 12 - 130
- Catalog/data/catalog_setup/data-install-2.0.0.php Lines 12-44, 94-127 (maybe some more?)
- CatalogInventory/data/cataloginventory_setup/data-install-2.0.0.php Lines 10-14

to be able to run the `index.php update` tool.

I suggest the following: Either for all inserted data use MySQL `INSERT IGNORE` to silently fail on existing entries OR separate the logic in the data install script between adding data and migrating data (then it is easier to pick the correct install/update script).

AFAIK: there is also a migration script missing in the `dev/tools/Magento/Tools/Migration` folder which converts the e.g. `backend_model` to the new class names in the EAV tables.

**Comment by TexanHogman** [comment]
@SchumacherFM to satisfy several requirements we are taking a different approach to support migration to M2.

The existing feature of update scripts, requires the site to be in maintenance mode and because some operations could take a significant amount time doing conversions we were not comfortable relying on this for our M2 data migration needs. 

In M2 we are supporting migration using a new tool and workflow that allows extremely fast data migration using mostly native sql commands.  The process will be to setup a fresh Magento 2 instance and run the tool to pull data from the M1 database.  This allows validation in a staging environment and also a final (very quick) catchup phase therefore minimizing the downtime for the site.  The solution uses a mapping file between source and target versions of Magento.  The core team will provide this mapping files for several versions of CE and EE and the community can pitch in too to provide support for other versions.

Additionally, as you have seen we have collapsed all M1 update scripts for M2 this allows us to start fresh with M2 but of course limits the update scripts support versions.  Since the incremental upgrade did not solve performance requirements (site downtime) we decided to start fresh for M2.

We understand this is an important merchant/si first experience with M2 and therefore we are ensuring this is fast, extensible and predictable.
