### ISSUE TITLE
Customizable Options Cannot Be Moved from Page to Page

### ISSUE THREAD

**Issue by Ecksters** [magento/magento2#10027]
### Preconditions

1. Magento 2.1.6
2. PHP7

### Steps to reproduce

1. Open any product
2. Create 2 or more pages of customizable options
3. Create a new product and try to move it to the first page

### Expected result

1. There should be a simple way to alphabetically sort customizable options, or at a minimum I should be able to move them from page to page.

### Actual result

1. You have to manually swap options page by page until you get where you want

**Comment by TomashKhamlai** [comment]
Thank you for your submission. The issue that you reported was reproduced. I am very surprised that this feature is not available for your needs. I am sorry but this submission will be classified as a feature improvement because you need more features in existing functionality. 

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

Use these links to submit feature improvements in next Magento releases. Your ideas are valuable for us.

**Comment by Ecksters** [comment]
https://community.magento.com/t5/Magento-2-Feature-Requests-and/2-1-RC-Custom-options-not-draggable-from-page-to-page/idi-p/46334

Apparently has already been requested.

**Comment by veloraven** [comment]
This issue appears to be duplicate of #4715.
Internal ticket MAGETWO-53590 exists for it.
