### ISSUE TITLE
Bundled products with "User Defined" field unchecked cannot be back ordered when they should be.

### ISSUE THREAD

**Issue by wjhuebner** [magento/magento2#10061]
### Preconditions

1. M2 EE 2.1.7 (may also work on CE version as well. Have not tested)
2. PHP 7

### Steps to reproduce

1. Create 2 simple products that can be back ordered with a quantity of 0. Products should be set to In Stock and work just like any other back ordered product.
2. Create a bundled product that contains the 2 newly made products and is set to In Stock.
3. For each of the simple product settings in the bundled product, make sure that "User Defined" field is unchecked. See below for config setting:
![m2-bundled-product-user-defined](https://user-images.githubusercontent.com/7671672/27560334-67ad5e10-5a89-11e7-81a9-5c1894ccfe9d.png)
4. Navigate to the bundled product on the frontend and confirm it is out of stock.

### Expected result

1. Bundled product on the frontend should be in stock and purchasable since those products should be back ordered. The back order setting can be sent on either the product level or global level for testing.

### Actual result

1. The bundled product appears out of stock instead of being purchasable. This only happens if the "User Defined" field for simple products is unchecked, so bundled product works as expected if "User Defined" is checked.
2. Site was reindexed and caches were flushed, but the same result still happens.
![m2-bundled-product-frontend](https://user-images.githubusercontent.com/7671672/27560501-feb1802a-5a89-11e7-9c99-e7e1af7e7bfc.png)

**Comment by veloraven** [comment]
@wjhuebner thank you for your report.
EE issues should be reported to the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
However if this issue reproduces on CE as well we can leave it here.
But could you please tell me if you have reported the same issue to Support? In order to avoid duplicates.

**Comment by joshuaswarren** [comment]
Yes, this issue reproduces on CE as well. It was reported to EE support
where it was apparently classified basically as “works as intended”,
although it doesn’t - I think support may have misunderstood the
combination of inventory settings and bundled products.

**Comment by joshuaswarren** [comment]
@veloraven - I see you've added the needs update label. I wanted to make sure you saw my reply and understand that:

1) This is an issue that impacts both CE and EE sites.

2) This issue has been reported to Magento's Enterprise support, who has actually stated it's a "feature request" and not a bug (which seems a bit odd to me - it seems to be like when a merchant configures a product in such a way to be purchasable even when the quantity is 0 or negative, that product should be purchasable at all times). I've asked for the person who opened the ticket to share the ticket number so that we can pass it along here. 

3) There's a full bug report, including a process on how to replicate this issue on a stock installation of CE or EE with Magento's provided sample data. Hopefully this will allow the bug to be quickly reproduced and confirmed. 

Thanks for your attention on this bug that's currently blocking a Magento 2.1 site launch. Let us know if there's anything else you need in order to move forward with investigating and resolving this issue in both CE and EE. 

-Josh

**Comment by joshuaswarren** [comment]
As far as the ticket number you requested, it was filed with EE support via ticket # 03209255 on June 21st.

**Comment by misha-kotov** [comment]
Thanks for reporting this - internal issue is MAGETWO-70489.

**Comment by magento-engcom-team** [comment]
@wjhuebner, thank you for your report.
We've created internal ticket(s) MAGETWO-70489, MAGETWO-83325 to track progress on the issue.

**Comment by ghost** [comment]
I am experiencing the same issue. Was previously using 2.1.9 and bundles worked fine. I do not track inventory in Magento on the simple products that make up the bundle or the bundle itself. After upgrading to 2.2.1 bundle items all display as out of stock and cannot be ordered.

As a work around for now I set the quantities of all the simple products to be a positive number and stock is set to not decrease when orders are made. This allows the bundle items to show in stock and be available for purchase.

**Comment by magento-engcom-team** [comment]
Hi @wjhuebner. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.2-develop` branch(es).
Related commit(s):
 - [6b4b959e4c5c8e800bb3ab9fa23b18a54394b935](https://github.com/magento/magento2/commit/6b4b959e4c5c8e800bb3ab9fa23b18a54394b935)
 - [a345343183720613f5ef6b0b63cc78c55b37140f](https://github.com/magento/magento2/commit/a345343183720613f5ef6b0b63cc78c55b37140f)
 - [1575a5ba0cf8c114fe6b04579e7c92549d3c87b2](https://github.com/magento/magento2/commit/1575a5ba0cf8c114fe6b04579e7c92549d3c87b2)
 - [952a8a90b853ea999edee7259d7fca8435f1c7bb](https://github.com/magento/magento2/commit/952a8a90b853ea999edee7259d7fca8435f1c7bb)
 - [96e1222f5fc8b697bad57876b047e6118e1fe636](https://github.com/magento/magento2/commit/96e1222f5fc8b697bad57876b047e6118e1fe636)
 - [994d8e5a14c1fed4fa3845c3cb60bdac9e6f6322](https://github.com/magento/magento2/commit/994d8e5a14c1fed4fa3845c3cb60bdac9e6f6322)

The fix will be available with the upcoming `2.2.10` release.

**Comment by magento-engcom-team** [comment]
Hi @wjhuebner. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-83325` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
