### ISSUE TITLE
sales_order_item.qty_backordered  should not be NULL

### ISSUE THREAD

**Issue by grizwako** [magento/magento2#10079]
### Preconditions
1. Ubuntu x64 17.04, MySQL 5.7.18-0ubuntu0.17.04.1, PHP 7.0.18, MySQL 5.6.23
2. Magento 2.1.7
3. Products, categories created by hand

### Steps to reproduce
1. Enable backorders in store configuration (for example Enable Backorders and notify customers)
2. Set some product to have low quantity (for example 2)
3. Order "more than stock" qty (for example 3 if product has 2 items in stock)
3.1  Can be done via frontend or admin order creation.
4. Observe order in admin
5. Observe order in database

### Expected result
1. Order should have qty_backordered equal to difference between qty_ordered and how many items were in stock. 

### Actual result
1. sales_order_item.qty_backordered = NULL

If this is solved in upcoming Magento 2.2 can you just point us in right places in codebase and explain why it does not work as it should?

Thanks!

EDIT1:
Closest I could find was issue #10057 , but from quick reading, it seems like issue in 2.1.5 was caused by something about how forms were handled.

EDIT2: Same bug manifests with MySQL 5.6.23

**Comment by grizwako** [comment]
Ok, so after some debug sessions...
Seems like issue is that \Magento\Quote\Model\Quote\Item\ToOrderItem::convert()  accepts quote item without "backorders" data field. And afterwards it proceeds to

`        $orderItemData = $this->objectCopyService->getDataFromFieldset(
            'quote_convert_item',
            'to_order_item',
            $item
        );
`

Funny thing is that backorders field is "properly" set when rendering quote  (display admin order create interface). It uses: \Magento\CatalogInventory\Model\StockStateProvider::checkQuoteItemQty()


Honestly, I do not know best way to fix this, for now I am going to work around it by using StockStateProvider::checkQuoteItemQty or applying same logic if using full method turns out to be bad idea.

**Comment by grizwako** [comment]
Anyway, decided to just hook up backorders qty before
`\Magento\Quote\Model\Quote\Item\ToOrderItem::convert`

There is just one confusing part for quote item option quantity validator initializer.
https://github.com/magento/magento2/blob/c3508715ce41c343fb9349def3ddff8347e8faa5/app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator/Initializer/Option.php#L93

Is that $optionValue always one for composite products? Child item qty gets multiplied on next line with $optionValue and I am not sure if it can be something not equal to 1?

**Comment by AlexWorking** [comment]
Hello @grizwako. We could reproduce Your issue only when creating order via Admin. Anyway, based on Your issue, there has been created an internal ticket MAGETWO-70413. You'll be informed after the problem is resolved. Thanks for applying.

**Comment by rbncha** [comment]
What it solved. Do we get a patch ?

**Comment by grizwako** [comment]
Hi @AlexWorking !

Thanks for feedback!

When you say issue was reproduced only in Admin, do you mean you could not reproduce it on storefront in **both** **development** and **production** modes?

**Comment by grizwako** [comment]
Hi, it actually turns out that production and development mode seems to not be relevant.
Looks like issue happens only when product's qty is **exactly zero**.

Weird thing we noticed is that
\Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList->getQty()

 In later parts of the code, the number returned from here gets multiplied by one (0*1) which screws later conditions...

**Comment by AlexWorking** [comment]
Hi @grizwako. There is the step to reproduce: "3.1 Can be done via frontend or admin order creation." I meant if You create an order via frontend You won't face this issue. The mode I used was production.

**Comment by grizwako** [comment]
Hi, @AlexWorking !

Ok, not sure why you can not reproduce it. We are already quite familiar with that part of the code and I do not see any setting other than backorders being enabled which would obviously cause it to behave differently.
Both teammate and I are reproducing it reliably as long as backorders are enabled and **product's stock is exactly 0**. We reproduced it in production mode few times and then fell back to development mode.
IMHO, stuff like this is critical business logic and development vs production mode should have no impact at all whether this bug will manifest or not.

I am not sure what is the focus for core team currently, but in the long run, it would probably be worthwhile to refactor some code and maybe even describe why it is there, and what relies on it.
It would be nice if code like backorders handling could be easily understood by average backend Magento website developer, ideally seeing a rough big picture in under 15 minutes. An hour max. Honestly with one hour spent, I would expect to have a really good understanding how that code works, narrowing down possible root causes of a bug and have some ideas about how to fix ones that seem most likely.


Sorry, went a bit off topic...
Anyway, good luck and we are hoping for an official fix soon.

Thanks!

**Comment by AlexWorking** [comment]
Hello, @grizwako. It's really interesting, because I tested it twice or thrice before creating a ticket. So, when I have a bit of free time, I'll try to reproduce the issue again and will do it making sure that stock is exactly equal to 0 and also will try it in different modes. And I'll let You know the results. But anyway if there is, as You say, no any setting other than backorders being enabled which would obviously cause it to behave differently, the bug fix shall have right effect for both ends.

**Comment by grizwako** [comment]
Hi, everyone!

Any updates on this?

**Comment by magento-engcom-team** [comment]
@grizwako, thank you for your report.
We've created internal ticket(s) MAGETWO-80464 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @devamitbera. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by devamitbera** [comment]
#MM19IN

**Comment by ritesh-san** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@ritesh-san thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ritesh-san** [comment]
I have created this PR #22689. Please check.

**Comment by ritesh-san** [comment]
@magento-engcom-team I have fixed this issue. Creating the PR #22689.

**Comment by seansan** [comment]
For sake of completeness, cross posted

Whats the status on this? Has this seriously been an open issue since 2019? And is the original issue from 2017? https://github.com/magento/magento2/issues/10079

Or: maybe is the whole backorder_qty field no longer used due to MSI and reservations? 

I can confirm on m2.3.5 
- there is no field backorder_qty in the quote_item table
- it does exist in order_item table, but it is NOT populated

Downside is that the order and the order item DO NOT KNOW they are a backordered item or order and hence it does not show in the order view or in the order grid view.

I think M2 nees to re-think backorders - there are more bugs/features listed related to backorders.

**Comment by grizwako** [comment]
Hey @seansan , I am not working with Magento anymore.

Anyway, for shops that used this functionality fix was not too hard, I don't remember exactly what was needed, but most of the fix was standard "configuration overhead", and a very little real logic.

Run code with debugger a couple of times to get familiar with the flow and you will see the issue clearly (at least it was like that when I last did the workaround few ago, I don't think much has changed since then).

**Comment by seansan** [comment]
See https://github.com/magento/inventory/pull/2452 would this also fix the issue by OP?

**Comment by MyroslavDobra** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @grizwako,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.kindly refer the screenshots.

<img width="1437" alt="Screenshot 2024-09-11 at 16 21 42" src="https://github.com/user-attachments/assets/4d7b52bc-60cd-481a-8cce-2e01300e4bda">


qty_backordered having values.

Hence we are closing this issue.

Thanks.
