### ISSUE TITLE
Magento don't create product redirect if URL key on store view level was changed.

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#10073]
### Preconditions
1. Magento 2.1.6 with Sample data

### Steps to reproduce
1. Create store view with code "second" for Main Website
2. Create new product with name "A" for Main Website (URL Key "a"). Here are product URLs from core_url_rewrite table:
https://drive.google.com/file/d/0B__P_POF2b9aTHU0M21zVnJ2ZG8/view?usp=drivesdk
3. Switch to "Default Store View" (store_id = 1 for me) and change URL Key to "b" then save product:
https://drive.google.com/file/d/0B__P_POF2b9adHpDT1ZSUDRRRzg/view?usp=drivesdk

### Expected result
1. 301 redirect for "Default Store View" (ID#1) in core_url_rewrites table

### Actual result
1. 301 redirect missing
https://drive.google.com/file/d/0B__P_POF2b9ael9MaWdZU0xGYVk/view?usp=drivesdk

### But
If you change URL Key on "All Store View" level - 301 redirect will be created for "Second Store View" store, which haven't personal URL Key value.
https://drive.google.com/file/d/0B__P_POF2b9abTBJOWZlMEtuMVE/view?usp=drivesdk
Issue occurs if change URL Key on the Store View level.

**Comment by Stas94** [comment]
@sergei-sss Thanks for reporting this issue. We've created internal ticket MAGETWO-70447 to address this issue.

**Comment by magento-engcom-team** [comment]
@sergei-sss, thank you for your report.
We've created internal ticket(s) MAGETWO-80451 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @sergei-sss. Thank you for your report. 
The issue has been fixed in magento/magento2#13567 by @adrien-louis-r in 2.2-develop branch
Related commit(s):
 - [1ef4dcc110062612e9971d7f8fb788bef213df3f](https://github.com/magento/magento2/commit/1ef4dcc110062612e9971d7f8fb788bef213df3f)
 - [864f371aed88884fb73082deb0c856819c43a41f](https://github.com/magento/magento2/commit/864f371aed88884fb73082deb0c856819c43a41f)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @sergei-sss. Thank you for your report. 
The issue has been fixed in magento/magento2#14252 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [03e0a0b007c7d1f8a7f82d685a5e99aa1cd9e7c3](https://github.com/magento/magento2/commit/03e0a0b007c7d1f8a7f82d685a5e99aa1cd9e7c3)
 - [1322d8be3e64695effbfb525a22c3aed02587b1e](https://github.com/magento/magento2/commit/1322d8be3e64695effbfb525a22c3aed02587b1e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by peterjaap** [comment]
@magento-engcom-team that is not the fix, that is just an integration test. Could you refer us to the actual commit that *fixes* it?
