### ISSUE TITLE
Issue Creating Order In the ADMIN Order Items Missing

### ISSUE THREAD

**Issue by almuete** [magento/magento2#10078]
### Preconditions

1. Magento2 CE 2.1.7

### Steps to reproduce

Issue 1:
1. Started sale in Safari In the admin just create order and select any customer
2. Added product in without a problem
3. Went to change delivery address for customer
4. This removed the product from top of page and set price to $0
5. When page refreshed, product reappears at the top, old address back in
6. When attempted to change address again same issue
7. Play around changing the shipping address and shipping method.

Issue 2:
1. Went into Chrome to try again
2. Went into customer first and changed default address to one intended for use
3. Added product in fine
4. Selected shipping option
5. Product stayed at top but price went to $0 & states no payment method required
6. Play around changing the shipping address and shipping method.

### Expected result

1. Expected result Admin Create Order will work without any issue.
![screen shot 2017-06-28 at 2 29 02 pm](https://user-images.githubusercontent.com/2081976/27620683-88ac4c08-5c0e-11e7-90f0-bfbb24ee0a01.png)

### Actual result

1. [Screenshot, logs]
![screen shot 2017-06-28 at 2 28 56 pm](https://user-images.githubusercontent.com/2081976/27620688-91b46826-5c0e-11e7-8e5d-ee21e5bab017.png)

**Comment by vityakopin** [comment]
Thanks for the feedback. Unfortunately, I could not reproduce the issue as you described it. After changing shipping or billing address or shipping methods in both browsers the product added to order is still shown in Items Ordered section. Can you confirm that issue is reproduced on clean install of Magento without any extensions?

**Comment by almuete** [comment]
Hi Vityakopin,

Nope is not fresh install basically we implemented some 3rd party extensions, custom extensions and other core minor extends. Do you have any advice?

**Comment by korostii** [comment]
The typical advice is usually "please double-check whether you can reproduce the issue on a fresh installation of 2.1.7 CE". 
The background is that the GitHub Issues are intended for tracking the bugs of Magento CE itself only and not the ones caused by 3rd-party code.

**Comment by magento-engcom-team** [comment]
@almuete, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by vincentwinkel** [comment]
Hello,

I have the same problem on Magento 2.0.14.

When I update the delivery address from the select, in some cases, the "items" section is returned empty from the HTTP loadBlock response, I guess it's because the form data contain the field `customer_id` = `false`.

It seems working properly when `customer_id` = `<id>`.

But I don't find anything interesting in `vendor/magento/module-sales/Controller/Adminhtml/Order/Create.php`

**Comment by mrodmincheg** [comment]
Had the same problem. In my case it was apostrophe symbol in customer address. It was interpreted like close apostrophe in DOM in data-order-config attribute.

**Comment by rachit-m** [comment]
This happens when apostrophe is present in the address.
Make 
data-order-config='<?php /* @escapeNotVerified */ echo $block->getOrderDataJson() ?>'
as
data-order-config="<?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getOrderDataJson()) ?>"
