### ISSUE TITLE
Module names sorting issue?

### ISSUE THREAD

**Issue by magekey** [magento/magento2#10112]
Not sure it could be an issue but I found some problem during develop my module.

### Preconditions

1. Release 2.1.7 with Sample Data
2. Ubuntu 16.04, php-fpm 5.6.30, MySql Percona Server 5.6

I did some tests with modules sorting function in \Magento\Framework\Module\ModuleList\Loader.
Here is results of print_r function.

**TEST 1** - No custom modules.

_**Result:**_

> Magento_Checkout - line 558 (Line in browser)
> Magento_Tax - line 618

---

**TEST 2** - added module MageKey_Module - no sequences
```
<module name="MageKey_Module" setup_version="2.1.0"/>
```

_**Result:**_

> MageKey_Module - line 3
> Magento_Checkout - line 568
> Magento_Tax - line 628 

looks correct

---

**TEST 3** - added sequence

```
<module name="MageKey_Module" setup_version="2.1.0">
    <sequence>
        <module name="Magento_Checkout"/>
    </sequence>
</module>
```
_**Result:**_

> Magento_Tax - line 511
> Magento_Checkout - line 571
> MageKey_Module - line 1073

now Magento_Checkout has high priority which is not good.

---
Not sure it can be an issue but I added only Checkout sequence, not sure why Tax has low priority now. As result I got an issue on Checkout cart page.

### Expected result
On Checkout Cart page on summary sidebar to render Grand Total (grand-total) we are using component **Magento_Tax/js/view/checkout/cart/totals/grand-total**. Order Total shows correct info.

### Actual result
When module has been added now we have checkout component **Magento_Checkout/js/view/summary/grand-total**. And Order Total collected without Taxes.

Not sure maybe I missed something.

**Comment by korostii** [comment]
I will duplicate here some considerations which I've also mentioned on #10649.

Magento_Tax module depends on code from Magento_Checkout module and will crash without it.

A couple examples:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Tax/etc/frontend/di.xml#L17
https://github.com/magento/magento2/blob/develop/app/code/Magento/Tax/view/frontend/web/js/view/checkout/cart/totals/tax.js#L12

This should be fixed by adding an making that dependency explicit instead (via adding `Magento_Checkout` into the `Magento_Tax`'s `<sequence>`). 

This seem to be done on 2.2.0 branch already;
https://github.com/magento/magento2/blob/2.2.0-preview/app/code/Magento/Tax/etc/module.xml#L12
But not yet backported to 2.1:
https://github.com/magento/magento2/blob/2.1.10-preview/app/code/Magento/Tax/etc/module.xml
