### ISSUE TITLE
New Orders not being saved to order grid

### ISSUE THREAD

**Issue by martinmarsian** [magento/magento2#10128]
### Preconditions

1.  This is Magento 2.1.7 with SSL being active
2. PHP 5.6 latest FPM
3. MySQL 5.6
4. Internal Payment module "Check/Money Order" being used.

### Steps to reproduce

1. Visit site as guest
2. Put item in cart, go to checkout
3. Fill out any necessary customer information
4. Choose internal payment method "Check/Money order"
5. Place Order

### Expected result

1. E-Mails to customer should be sent, containing all necessary informations about the order
2. Order should be saved to grid with customer name
3. Dashboard should show order with customer name

### Actual result

1. Email with order no. is being sent to customer, but **the email contains no information about ordered items**, only billing and shipping address (Standard Magento email-template being used)
**2. Orders are not saved to order grid**
3. **Dashboard shows orders as "Guest"**, order can be opened from dashboard and it seems to be complete with informations about items being ordered
4. Debug logs are being written, exception logs not.

5. system.logs are included as well 

### Additional Info
I tried to pin this down. I installed a complete and fresh installation of Magento 2.1.7 from magento.com. Even with this version I have this problem.
I can also exclude that this is a template problem. The behaviour also exists if Magento Luma theme is being used.

**Comment by Andrii-Deineha** [comment]
@joergmaertin  Hi,  Internal ticket was created MAGETWO-70503 for problem with Customer name. Unfortunately, I could not reproduce another issues as you described ites.   Screenshots of Email letter with and order grid would be helpful, too . If you have this problems please create singly issue for ones issues .  Thank.

**Comment by martinmarsian** [comment]
@Andrii-Deineha I updated screenshots. At the moment I try to find out what is going on.
1. I have a clean install of Magento 2.1.4 with demo data. The problem is not existent
2. When I try the same with Magento 2.1.4 and a database after migration, the problem is existent. The only extensions installed are de_DE Language pack and WebShopAppls Matrixrate.

**Comment by martinmarsian** [comment]
@Andrii-Deineha I removed any third party extension and language pack from the running magento 2.1.4 and used migrated data. Problem is existent.

**Comment by martinmarsian** [comment]
@Andrii-Deineha I don't think the issues are single independent issues, they seem to be connected.

**Comment by Andrii-Deineha** [comment]
@joergmaertin Please create new issue  with order after database migration. If you use database migration from M1, give a link to the appropriate repository. Thank.

**Comment by martinmarsian** [comment]
@Andrii-Deineha I will do so after I really tested this. I will create a new fresh magento 2.1.7 instance and do a fresh datamigration as well again. I will do that over the weekend, so don't a fast response.

**Comment by martinmarsian** [comment]
@Andrii-Deineha I don't know what you mean with "Appropriate repository". Anyway I need to open a new issue, as testing showed same error: orders are not shown in order grid.

**Comment by magento-engcom-team** [comment]
@joergmaertin, thank you for your report.
We've created internal ticket(s) MAGETWO-70503 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by okorshenko** [comment]
Hi @joergmaertin. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1325 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - e84cb3eb79f63f3cac85f5b68b90b82530786d86
 - 742819bdd72880190a992a0f9412af4c0ba417ae
 - cc2b11f47825471e93523db287b4a013da6629d5
 - ae8b1870640227d69e921a5a358fe2addefb5018
 - 35b3c02ca62fa40990fd957c36cd21b7e4f127cd
 - eae893662678539fa602434d92d798ec8a3b3a4c
 - 90e49230db9a94b2b5831c5618b960de35ebc4e0
 - b098dbc4e53efae137286bf056f1e46a2971d52c
 - e8e4cdd29db74ccd13f3078f93c59fb53c4a96d3
 - 058e5e55680e4ca8eb64311f782994fac10a1f74
 - 9368d5da237eb6e158990f2cff8be954242821fe
 - bf19409195b7b93322073026455405ed8820e6af
 - a15ec3421d3d2371429f9c804b91ecd3b6aaf763
 - 9e4ce76a9ad07713d2170420fcd8d237ec776fcb
 - 099568124736c9575bf7498641a0842877260346
 - 6772a2d6658c4677334df0b67159d3a47b6d2155
 - b0d6bfc6599390f31ef3b564fb3e2848037faeef
 - b03735716895f21bee4bc5b5be7d5c7f5a27ba33
 - 8de595178d6dca294d649fde0359a055f07fca69

The fix will be available with the upcoming 2.3.0 release.
