### ISSUE TITLE
Please add your expectations for @deprecated annotations

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#10133]
Hello,

I try to create own code based on the `\Magento\Checkout\Controller\Cart\Add` class. I see that this class uses `\Magento\Checkout\Model\Cart` class that has `@deprecated` annotation. I could use other class in my code but I don't know your expectations - which other class does Magento team use instead of deprecated `\Magento\Checkout\Model\Cart`?

It would be more pleasantly if `@deprecated` annotations will have comments that point to expected replacements. Something like: 

    /**
     * Shopping cart model
     * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
     * @deprecated use \Magento\Quote\Model\Quote
     */
    class Cart extends DataObject implements CartInterface {...}

I know, there are a lot of deprecated classes/methods in the code (> 500) and Magento team cannot comment all of them at once. However, the source code is a primary documentation for developers and all developers read the sources. Your plans (expectations) will be more understandable for us if you will write it just a little wider in the sources.

Thanks.

**Comment by magento-engcom-team** [comment]
Hi @flancer64 thank you for pointing on this. We already have this as a part of our commitment in [Backward compatible development](http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/) We still have some tech debt, but we are working to minimize it. 
Feel free to submit pull request to address the most painful issues for you. Thank you

**Comment by magento-engcom-team** [comment]
Hi @flancer64. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1359 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 1db3f8f6a336026d4a4493c8ba8d3e165ade66d8
 - 412d2287ee5a1a9620fb2a256bab562bdd10fe49
 - 02620b09456d77408ccbbd6a6b61a7b7ebcf73fa
 - 57c5d8a819e403905bd4d5419564d184712bc142
 - 94a3f0346ea086626d8b11c08fd397b11a570caa
 - 0d557dc99c15c6638e1c894ce46cb681a74b8912
 - 48baf590f86590c44bba81a9d5303902aed9d8d7
 - dc3bb78962c4522eb5df8a1a8f40c3bbe2b623fc
 - 0ab45334ef4d44e55c9f84f9c6e4b6a9e08e9237
 - 00f64b077ce00e55216e6ea9fb39071dc74b51a1
 - 440a1b5f9e6309fa87790a5f5b7d1b8fd7ffa53d
 - 4ed8f5b65d5d1779522653102120917c5f9578be
 - 656eeb5587eb1baebaffdc8ba68f1028afda8910
 - fd2f731f7efc4a2cec9e03f8de88bf39c0988829
 - 2c1a23faa60805bd63ff62216309d57a052612d1
 - f7ff71a92bcf56679b82c22549244e1adb9f4ed2
 - ac9bcfa15b1b0b98f9cb3851f4d9b56e18ede89b
 - 55debe0c2b514e37271ed6edf20b95fec6cc41c9
 - 349508628dc1c4334e13b3541227505e26c93c64
 - d678f1568b6e2d30c6d651dd3da02e0f3512353e
 - bf8ee3089f005e267f0b14cf81b14e9a3ee26986
 - 335c91c07dde6f90309f11cf0efcbd9127630955
 - c5a823f95161f7c13fb0947abb445fdc9e9a620a
 - 696a5a575513bb87c47ffc15a571034b0b91d7ae

The fix will be available with the upcoming 2.3.0 release.
