### ISSUE TITLE
The "More Information" tab can't display when show "category_ids" in front end

### ISSUE THREAD

**Issue by trangunghoa** [magento/magento2#10135]
### Preconditions
1. Magento Enterprise 2.1.4
2. PHP 5.6.30
3. Nginx 

### Steps to reproduce
1.  Go to Store >> Atributes >> Product 
2. Edit "category_ids" Attribute
3. Choose Storefront Properties 
4. Choose Yes in the Visible on Catalog Pages on Storefront

### Expected result

1. It's should show all categories with name and link

### Actual result

1. Can't show any attributes.
2. the support_report.log show the error:
`[2017-07-04 06:51:21] report.CRITICAL: Notice: Array to string conversion in /var/www/m2/magentoee/src/vendor/magento/module-catalog/Block/Product/View/Attributes.php on line 83 [] []`
![category_ids](https://user-images.githubusercontent.com/909219/27818521-2a98450c-60c0-11e7-9e79-586fb898c12f.png)
![tabs](https://user-images.githubusercontent.com/909219/27818551-484db1ea-60c0-11e7-9238-7910f55bb0b8.png)

**Comment by veloraven** [comment]
@trangunghoa thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
