### ISSUE TITLE
New data in admin grids do not show up with asynchronous indexing enabled

### ISSUE THREAD

**Issue by redelschaap** [magento/magento2#10158]
When asynchronous indexing is enabled in Stores > Configuration > Advanced > Developer, new data in admin grids do not show up. For example, when a new invoice is created for an order and the order view page refreshes, the new created invoice is not visible.

### Preconditions
1. Tested on Magento 2.1.5
2. Installation uses PHP 7.0.17 on nginx and MySQL 5.7.18

### Steps to reproduce
1. Enable Asynchronous indexing in the configuration
2. Open an existing order
3. Create a new invoice
4. Return to the order view page and open de invoices tab

### Expected result

1. The new invoice should be visible

### Actual result

1. The new invoice is not visible and gets only visible after a very long time (did not log the time) or after disabling Asynchronous indexing.

**Comment by Andrii-Deineha** [comment]
@redelschaap  Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-71031.

**Comment by magento-engcom-team** [comment]
@redelschaap, thank you for your report.
We've created internal ticket(s) MAGETWO-71031 to track progress on the issue.

**Comment by Ctucker9233** [comment]
@magento-engcom-team I want to add that disabling asynchronous indexing solves the problem but seems to have the negative effect of not writing information to the system.log file.

**Comment by spinxdigital** [comment]
Hi @magento-engcom-team 

Any update on fixing this issue?

**Comment by sadon** [comment]
Please check what cron is setup correctly

**Comment by redelschaap** [comment]
I don't have a development environment anymore that I can use to test this. Anyone?

**Comment by sadon** [comment]
try run manually 

```
su <magento_owner>
cd <magneto_dir>
php ./bin/magento cron:run
php ./update/cron.php
php ./bin/magento setup:cron:run
```
and check results

**Comment by redelschaap** [comment]
I know, but I have no environment where I can test the asynchronous indexing.

**Comment by MikeParkin** [comment]
Spent some time trying to re-create this issue without success. 

I enabled asynchronous admin grids, placed a couple of test orders and they have appeared. I then created invoices for the orders and they also appeared.

I tested disabling the cron job and placed the same tests, these did not appear (as expected). Re-enabling the cron then creates the new records.  

I've tested this on the 2.3-develop branch, and cannot see anything wrong. Going to close this issue off as I think it's likely the issue was the cron was not running. If this is not the case can we have some additional information added to this ticket to re-open it?
