### ISSUE TITLE
MCE 2.1.7 / Paypal Express :( -> "We can't place the order" 

### ISSUE THREAD

**Issue by gewaechshaus** [magento/magento2#10175]
### Preconditions
1. MCE 2.1.7
2. OS 7.0.20-2~ubuntu16.04.1+deb.sury.org+1
3. MySQL 10.0.2 (MariaDB)
4. PHP Version 7.0.20 (as php-fpm) (I know it's officialy not supported yet but it does contain important fixes), OPCache enabled
5. Haproxy->Varnish->Nginx->php-fpm
6. Redis as Cache/Session storage
7. Running in production mode

### Steps to reproduce
1. Clean browser cache and cookies or start private session
2. Go to the frontend and place an item into the cart, **click the paypal express button in CHECKOUT after filling the data incl. email address**  **Important: Do checkout as guest (does also work in guest mode with a customer who got an account under the same email address)**
3. Fill in the needed data and return from paypal to your site
4. In our case, the paypal customer has another email address than the one the customer did provide in the store frontend checkout field. If you click the PPE button from within the minicart, this email does get stored correctly. As we used the checkout payment method, it results in what is written under actual result underneath.

### Expected result
1. Order should be placed(skip review step enabled)

### Actual result
1. Order doesn't get placed and the message "We can't place the order" appears

### Analyse
We did analyse the logs first as we got some fixes applied related to other paypal issues I will link seperatly. In this case the email doesn't get included in the request, instead the related value stays null. This throws out the following exception "Bitte geben Sie Ihre Kunden E-Mail Adresse an". **Actualy we're using Mageplaza OSC, but we did test this also with the original checkout and got the same result.** This also seems to be an issue which persists since longer as our customers are frequently reporting this. As always, this is complicated cause there were bugs before that generated the same error messages in frontend. See my list at the end of this posting.

https://pastebin.com/2WxPpCtP

### Log
[2017-07-07 07:29:30] main.DEBUG: array (
  'url' => 'https://api.paypal.com/nvp',
  'SetExpressCheckout' => 
  array (
    'PAYMENTACTION' => 'Authorization',
    'AMT' => '48.31',
    'CURRENCYCODE' => 'EUR',
    'RETURNURL' => 'https://www.xxxxxxxxx.com/paypal/express/return/',
    'CANCELURL' => 'https://www.xxxxxxxxx.com/paypal/express/cancel/',
    'INVNUM' => '000002014',
    'SOLUTIONTYPE' => 'Mark',
    'GIROPAYCANCELURL' => 'https://www.xxxxxxxxx.com/paypal/express/cancel/',
    'GIROPAYSUCCESSURL' => 'https://www.xxxxxxxxx.com/checkout/onepage/success/',
    'BANKTXNPENDINGURL' => 'https://www.xxxxxxxxx.com/checkout/onepage/success/',
    'PAGESTYLE' => 'XXX',
    'SHIPPINGAMT' => '2.90',
    'ITEMAMT' => '37.78',
    'TAXAMT' => '7.63',
    'BUSINESS' => NULL,
    'NOTETEXT' => NULL,
    **'EMAIL' => NULL,**
    'FIRSTNAME' => 'Jan',
    'LASTNAME' => 'de Tester',
    'MIDDLENAME' => NULL,
    'SALUTATION' => 'Herr',
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'DE',
    'STATE' => 'NDS',
    'CITY' => 'Solingen',
    'STREET' => 'Querstr. 59',
    'ZIP' => '42699',
    'PHONENUM' => NULL,
    'SHIPTOCOUNTRYCODE' => 'DE',
    'SHIPTOSTATE' => 'NDS',
    'SHIPTOCITY' => 'Solingen',
    'SHIPTOSTREET' => 'Querstr. 59',
    'SHIPTOZIP' => '42699',
    'SHIPTOPHONENUM' => NULL,
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => 'Herr Jan de Tester',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'SetExpressCheckout',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
  ),
  'response' => 
  array (
    'TOKEN' => 'EC-XXX',
    'TIMESTAMP' => '2017-07-07T07:29:30Z',
    'CORRELATIONID' => 'XXX',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '35915193',
  ),
) {"is_exception":false} []

### Other Issues related to paypal issue "We can't place the order"
https://github.com/magento/magento2/issues/9455
https://github.com/magento/magento2/issues/6929
https://github.com/magento/magento2/issues/7955

**Comment by s00071609** [comment]
This **Cannot Place Order** with exception log below. This is a bug that was present in magento 2.0 and its still there in magento 2.1.7. There are multiple threads with several people reporting this error but for some reason this error has never been fixed.

Although this is a payment related error that should have received top priority, it was not fixed in so many releases since first reported. here is the log:

main.CRITICAL: Exception: Wrong order ID: "INV2-HCZX-TDHA-EA8F-3TZQ". in /home/couponc1/public_html/vendor/magento/module-paypal/Model/Ipn.php:140
Stack trace:
#0 /home/couponc1/public_html/vendor/magento/module-paypal/Model/Ipn.php(106): Magento\Paypal\Model\Ipn->_getOrder()
#1 /home/couponc1/public_html/vendor/magento/module-paypal/Model/Ipn.php(87): Magento\Paypal\Model\Ipn->_getConfig()
#2 /home/couponc1/public_html/vendor/magento/module-paypal/Controller/Ipn/Index.php(56): Magento\Paypal\Model\Ipn->processIpnRequest()
#3 /home/couponc1/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Paypal\Controller\Ipn\Index->execute()
#4 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callParent('dispatch', Array)
#6 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'contextPlugin')
#7 /home/couponc1/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'customer-app-ac...')
#10 /home/couponc1/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'storeCheck')
#13 /home/couponc1/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'weee-app-action...')
#16 /home/couponc1/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'tax-app-action-...')
#19 /home/couponc1/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Paypal\Controller\Ipn\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /home/couponc1/public_html/var/generation/Magento/Paypal/Controller/Ipn/Index/Interceptor.php(26): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /home/couponc1/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Paypal\Controller\Ipn\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#26 /home/couponc1/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#29 /home/couponc1/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#32 /home/couponc1/public_html/app/code/Litespeed/Litemage/Model/App/FrontController/LitemagePlugin.php(71): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Litespeed\Litemage\Model\App\FrontController\LitemagePlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#35 /home/couponc1/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#38 /home/couponc1/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /home/couponc1/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#41 /home/couponc1/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /home/couponc1/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#43 /home/couponc1/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by s00071609** [comment]
Not sure if anyone has had this issue with magento - It says cannot place order, but it places the order but magento does not create new order and transaction appears in PayPal.

If the customer had previous order, the transaction then ends up linking to the old order with - with status "Suspected Fraud". No matter how many orders that same customer places, it will end up in the same old order and new order will not be created.

The comment section inside the order page will show log of which paypal transactions were flagged as suspected fraud.
I guess all of these issues are linked and goes back to this "cannot place order" thing that has not been resolved since more than a year.

Note - there is no foreign currency involved.
If anyone else is having suspected fraud and cannot place order issue with magento, please do share it here

**Comment by gewaechshaus** [comment]
@s00071609 - it's a different scenario, resulting in the same error message. You have to differ as there are 4-5 issues I currently know. 

Take a look at this module, it will help to demistify PPE a bit
https://github.com/piotrkwiecinski/magento2-paypal-cant-place-order

**Comment by s00071609** [comment]
@gewaechshaus - Does this module fix the cannot place error with PayPal? - i think it results due to many different things you said scenario. 
Anything related to receiving payment should have the top most priority among different bugs but this error is still there.

**Comment by gewaechshaus** [comment]
@s00071609 - yes and no... It extends the  _handleCallErrors() method and handles false error messages on successfull transactions (as seen [here](https://github.com/magento/magento2/issues/9455)) and enables a more robust logging. 

https://github.com/piotrkwiecinski/magento2-paypal-cant-place-order/blob/master/Model/Api/Nvp.php#L12

There's a M2 core commit here
https://github.com/magento/magento2/commit/f954a9150aef87d58ccc4f400815f6337234f09a

**Comment by s00071609** [comment]
@gewaechshaus Its sickening to see errors in one place where you never want any error ie Payment/Orders. I know there are plenty of issues reported and there are many sources of errors like this- does this module help with this error at all:

[2017-07-12 23:11:31] main.CRITICAL: Exception: Wrong order ID: "INV2-HCZX-TDHA-EA8F-3TZQ". in /home/couponc1/public_html/vendor/magento/module-paypal/Model/Ipn.php:140
Stack trace:
#0 /home/couponc1/public_html/vendor/magento/module-paypal/Model/Ipn.php(106): Magento\Paypal\Model\Ipn->_getOrder()
#1 /home/couponc1/public_html/vendor/magento/module-paypal/Model/Ipn.php(87): Magento\Paypal\Model\Ipn->_getConfig()
#2 /home/couponc1/public_html/vendor/magento/module-paypal/Controller/Ipn/Index.php(56): Magento\Paypal\Model\Ipn->processIpnRequest()
#3 /home/couponc1/public_html/vendor/magento/framework/App/Action/Action.php(102): Magento\Paypal\Controller\Ipn\Index->execute()
#4 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callParent('dispatch', Array)
#6 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'contextPlugin')
#7 /home/couponc1/public_html/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#8 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#9 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'customer-app-ac...')
#10 /home/couponc1/public_html/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'storeCheck')
#13 /home/couponc1/public_html/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#15 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'weee-app-action...')
#16 /home/couponc1/public_html/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Paypal\\...', 'dispatch', Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Array, 'tax-app-action-...')
#19 /home/couponc1/public_html/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\Paypal\Controller\Ipn\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Paypal\Controller\Ipn\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /home/couponc1/public_html/var/generation/Magento/Paypal/Controller/Ipn/Index/Interceptor.php(26): Magento\Paypal\Controller\Ipn\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /home/couponc1/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Paypal\Controller\Ipn\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#25 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#26 /home/couponc1/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#29 /home/couponc1/public_html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#32 /home/couponc1/public_html/app/code/Litespeed/Litemage/Model/App/FrontController/LitemagePlugin.php(71): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Litespeed\Litemage\Model\App\FrontController\LitemagePlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#35 /home/couponc1/public_html/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /home/couponc1/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#37 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#38 /home/couponc1/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(68): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /home/couponc1/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /home/couponc1/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#41 /home/couponc1/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /home/couponc1/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#43 /home/couponc1/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#44 {main} [] []

**Comment by s00071609** [comment]
@gewaechshaus Installed it via composer but it gave permission error although permission looked fine. Only homepage worked and rest of the pages simply blank, page.html had 500 server error after i installed this.

I installed via composer
Removed all cache, static content etc,
Ran compile and deployed static content.

Any info on this would be great.

**Comment by gewaechshaus** [comment]
@s00071609 - please take a look a the modules PR's and try our fix
https://github.com/piotrkwiecinski/magento2-paypal-cant-place-order/pull/1

And BTW - please put your logmessages in pastebins, there's to much pollution the way you did it. You don't respect others who are stumbling upon this and wan't to read the related information in the possible shortest time.

**Comment by s00071609** [comment]
@gewaechshaus the fix suggested gives file system error. Its causing more issues than solving. I guess i am ding something wrong

**Comment by s00071609** [comment]
Did new release magento 2.1.8 include fix for WE CANNOT PLACE ORDER? This is an awful error probably one of the most crucial. People end of paying twice and some cannot pay. I cant see this bug fix included in 2.1.8, if true this will be another sad thing.

**Comment by gewaechshaus** [comment]
@s00071609 - I think this stuff is fixed in 2.2.0 - you should take a look at the RCs. It's a hard knock life to deal with PP/M since Magento 1 rounding issues and bunches of other paypal bugs :) I can hardly remember a release which didn't had any issues with PPE :) :) 

I didn't took a look at 2.1.8...

**Comment by gewaechshaus** [comment]
@s00071609 - according to the RN this is fixed (take a look under payment):
http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.8CE.html

**Comment by s00071609** [comment]
Well, that seems to be another thing that causes CANNOT PLACE ORDER . As you know there are many threads reporting this same issue coming from different sources - wrong invoice, wrong order id, item not in stock etc. I guess RN lists one of the fixes. As noted above, there has not been a release that is free from this issue. You can live with other issues but not with payment integration, its surprising that this issue has been widely reported yet no fixes in last releases. It confuses customers, leads to double payment, and many issues, it also causes stock discrepancy I think.

**Comment by s00071609** [comment]
Installed it yesterday and i already see the error Wrong Order ID in the log. This error causes cannot place orders. I dont think this issue gone and doesnt look like magento team is even considering it.

 main.CRITICAL: Exception: Wrong order ID: "INV2-HQSJ-BTKX-76SH-KBJ4". in /home/xxxxxxxx/public_html/vendor/magento/module-paypal/Model/Ipn.php:140

**Comment by orlangur** [comment]
> main.CRITICAL: Exception: Wrong order ID: "INV2-HQSJ-BTKX-76SH-KBJ4". in /home/xxxxxxxx/public_html/vendor/magento/module-paypal/Model/Ipn.php:140

You actually have order with such `increment_id` in your system?

**Comment by magento-engcom-team** [comment]
@gewaechshaus, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by ghost** [comment]
We are still facing same issue in Magento ver 2.1.9. Log says 

**main.CRITICAL: Exception: Wrong order ID:**

We have upgraded our Magento from earlier 2.x version to latest one.

**Comment by mattdillon100** [comment]
We have upgraded to 2.1.10 but no luck!
Is there any fix for this yet?? Our client is currently losing orders due to this bug.

**Comment by tanghia** [comment]
same issue.

First time, this issue occurs with our customer, we think that it's a customer account's problem, and that customer doesn't checkout again!

Second time, we still think that it's a customer account's problem.

Third time, a customer places another order after he completes a new order with express checkout. But, the system throws "can't place order". We don't know how many customers we lost (if they don't report error)!

Our website is in a marketing campaign (with cart price rules). It was updated from Magento 2.0.6 -> 2.1.0 -> 2.1.7 -> 2.1.9. 

Please fix this issue!

**Comment by tanghia** [comment]
We have just checked log file and this is content:

[2017-11-15 09:50:21] main.CRITICAL: Exception message: Please check the billing address information. Please enter the street. Please enter the city. Please enter the phone number. Please enter the zip/postal code.

**Comment by NiteshKuyate** [comment]
We are also facing same issue, anyone found solution for this?

**Comment by pulkitjalan** [comment]
We are also having the same issue on 2.1.10, is there a fix for it?
Our clients are loosing orders because of it...

**Comment by tanghia** [comment]
Magento 2.1.x gets this issue, I have to update my website to 2.2.X to resolve it !!!

**Comment by yosefkurniawan** [comment]
any workaround for Magento 2.1.x?
i'm still geeting the same issue on Magento 2.1.8 (upgraded from 2.1.3)

**Comment by riyajalijunakiya** [comment]
Downgrade php to 7.0 from 7.1 its solve issue for me.
