### ISSUE TITLE
New Orders are not in Order grid after data migration from M 1.7.0.2 to M 2.1.7

### ISSUE THREAD

**Issue by martinmarsian** [magento/magento2#10185]
### Preconditions

1. PHP 5.6 latest FPM
2. MySQL 5.6.19
3. Running Magento CE 1.7.0.2, database replicated, no problems here.
4. Fresh Magento CE 2.1.7 with Luma Theme
5. Datamigration Tool 2.1.7
6. vendor/magento/data-migration-tool/etc/ce-to-ce/1.7.0.2/config.xml Datamigration

### Steps to reproduce

1. Migrate Data from 1.7.0.2 to Magento 2.1.7
2. Place order as guest in Magento 2.1.7
3. Choose internal Payment method "Check/Money order" or "Bank transfer"
4. Finish order

### Expected result

1. The customer should get an email about the order
2. The order should be visible in order grid
3. The order should be visible in dashboard

### Actual result

1. The Customer gets an email with correct content of order and order no. that is in line with the order no. in general
**2. But the order is not visible in order grid, it seems not being saved here**
3. The order is visible with entry "Guest" in Dashboard. Magento 1.7.0.2 saved the name of the customer here even as guest. 

The issue has been first reported in #4431 which was closed. Again reported in #10128, on request the issue has been specified here.

I have included logs in #10128. I'd like to include my datamigration config files here to review. Maybe there is something important missing in my files, which also need to be migrated.

**Comment by ihor-sviziev** [comment]
Hi @joergmaertin,
For data migration tool we have separate repository, so you should ask it there:
https://github.com/magento/data-migration-tool

Did you ran reindex from cli after migration? Reindex of grids in m2 is async and it runs during cron execution. Did you configured cron jobs?

**Comment by martinmarsian** [comment]
@ihor-sviziev I indeed ran reindex from CLI and also now from cron. The result is the same: nothing in order grid.

**Comment by magento-engcom-team** [comment]
Hi @joergmaertin
Please report migration related issues to the migration tool repository: https://github.com/magento/data-migration-tool
Thank you

**Comment by ihor-sviziev** [comment]
I got the same issue after upgrading from M1 to M 2.1.9. Issue is not actually related to data migration tool, but it caused by incorrect sorting by order id field in order grid. It sort as string, but not as a number. Issue appeared because in M1 we had 9 symbols for order number, while in M2 it use 10. I didn't found any related issues, except this one. And this issue is already closed because it looked as data migration issue, but it isn't.

Workaround sort by Purchase Date field:
![capture 2017-10-05 at 9 21 13](https://user-images.githubusercontent.com/1873745/31807641-0751ffe0-b578-11e7-9b0f-516843e7b2ac.png)

**Comment by okorshenko** [comment]
Hi @ihor-sviziev 
The column ID renders the data from DB column `increment_id` (varchar(50)). So it is `string` by design. Also we have a feature that allows you to change order id generation pattern (see the table `select * from sales_sequence_profile;`). You can add suffix, prefix, step and etc. This is a requirement dictated by law in some countries. 
If you would like to change pattern for Order ID generation you can customize it via DI for the class `\Magento\SalesSequence\Model\Sequence`. By default we are using `%s%'.09d%s` but it is customizable. 
So I would say that from the Magento prospective this is not a bug. This is expected system behavior. Order ID (increment_id) is a string by default. If you will add prefix/suffix you can not sort the orders by ID as `int` value.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83084

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83155

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83154
