### ISSUE TITLE
Magento 2 import products with images using CSV Issue

### ISSUE THREAD

**Issue by mayankzalavadia** [magento/magento2#10209]
I'm trying to import a CSV file with new products that contain local images but I am receiving the error:
### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. Create simple product with image.
2. Export this product to CSV.
3. Try to import product with an image using csv.

### Expected result

Product Import Successful.

### Actual result

Got following error : 
Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s):

**Comment by kbrakband** [comment]
I have the same problem while I do have images in the **pub/media/import** folder and in the csv the images are written like this: 123456.jpg (without the path)

**Comment by magento-engcom-team** [comment]
Description updated.

**Comment by magento-engcom-team** [comment]
@mayankzalavadia, thank you for your report.
We've created internal ticket(s) MAGETWO-75633 to track progress on the issue.

**Comment by Jens-S** [comment]
I would like to work on this ticket.

**Comment by okorshenko** [comment]
Hi @Jens-S 
I've sent you an invitation to join Magento Team on public GitHub. Could you please accept the invitation?

**Comment by Jens-S** [comment]
Sorry, but I want to pass this ticket back.

**Comment by Jens-S** [comment]
Sorry, but I want to pass this ticket back.

**Comment by mayankzalavadia** [comment]
Hello @okorshenko 

I also would like to give my contribution on Magento. So, can you please send me an invitation to join Magento Team on public GitHub.

**Comment by okorshenko** [comment]
@mayankzalavadia invitation sent. Would like to work on this issue?

**Comment by mayankzalavadia** [comment]
Yes I Would like to work on this issue.

**Comment by KarlDeux** [comment]
Cannot reproduce it on 2.2 dev.
Are you filling Images File Directory field from the admin/import tool?
If so, try not to fill it and use the CSV file exported as-is.

PS: if you still encounter issues i'd like to take care of this ticket.

**Comment by PieterCappelle** [comment]
Can confirm. Can’t reproduce in 2.2 and 2.3.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#83

**Comment by Lanot** [comment]
Hello Community!

I was able to reproduce the same error `Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s):` when tried to import products with images. The images were located  and really existed on 3rd party website, not in local foder. 

The issue was related to HTTP Header, which my images returned when code asked for HTTP status per each image url.

The code expects status `200 OK`, but in my case it was `301 Moved Permanently` and that assumed as "Image Missing". 

Hints:
Magento\Framework\Filesystem\Driver\Http::isExists()

if (strpos($status, '200 OK') === false) {
  $result = false;
} else {
  $result = true;
}

In our case we have done customization with following enhancement:
if (strpos($status, '200 OK') === false && strpos($status, '301 Moved Permanently') === false) {
  $result = false;
} else {
  $result = true;
}

Kind Regards,
Tolik

**Comment by valuead** [comment]
Same error 2.2.5 
in my pub/media/import i have the file with 777 permission both on the folder and the file.
in my csv I have only file name.
![err](https://user-images.githubusercontent.com/9205462/45655633-25fd0600-ba96-11e8-83be-a96a8b1a01b6.PNG)

**Comment by gsa83** [comment]
Note : When a magento is behind a Proxy for example, this code is causing issue because get_header is not properly implemented
here Magento\Framework\Filesystem\Driver\Http.php : isExists mail have the possibility to pass a $context variable to be able to pass for example a proxy to the get_header, which allow context to handle this problem
note : the context is passed on the function of the class....
Today the only solution is to override this class, which is bad solution
