### ISSUE TITLE
Duplicate content when a page is added to a hierarchy

### ISSUE THREAD

**Issue by chefbuitenhuis** [magento/magento2#10241]
### Preconditions
1. Magento 2.1.7 EE
2. PHP 7.0.18

### Steps to reproduce
1. Create a CMS page with the URL `bar`
2. Add the newly created page to a hierarchy, for example to the `foo` hierachy

### Expected result
1. The CMS page should be accessible only through the hierarchy and not separately.

### Actual result
1. The newly created page will be available as `example.com/bar` and `example.com/foo/bar`, resulting in duplicate content.
2. The generated sitemap.xml only contains the CMS page (`example.com/bar`), and not the hierarchy version  (`example.com/foo/bar`)

**Comment by korostii** [comment]
Please note that Enterprise issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
That way, your issue should probably get acknowledged and solved faster. 
GitHub is intended for the Community Edition issue reports.

**Comment by veloraven** [comment]
@chefbuitenhuis thank you for your report.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
As pages hierarchy is present in EE only we can not treat this problem as an issue in GitHub. As GitHub is intended for Community edition reports only.

**Comment by evs-xsarus** [comment]
I've fixed this by adding a custom router which needs to be run after the urlrewrite but before the cmspages router. In it, I perform a getList on \Magento\VersionsCms\Api\HierarchyNodeRepositoryInterface with a searchCriteria where I filter on page_id. A redirect is performed if the request_url from the node differs from the request->getOriginalPath.
