### ISSUE TITLE
Magento 2 Loading custom option dropdown issue

### ISSUE THREAD

**Issue by NagarajuKasa** [magento/magento2#10291]
## Preconditions
1. Magento 2.1

## Steps to reproduce
1. Log in to admin
2. Go to Catalog -> Products and start to create new product
3. Add Customizable Options with next steps:
    * Select Drop-down Option Type.
    * Click the 'Add value' button to add an empty row, leave it empty.
    * Select a different Option Type (doesn't matter which).
    * Select 'Drop-down' Option Type again.

## Expected Result
The option Drop-down is selected and values are possible to edit

## Actual Result
The option Drop-down is selected and a infinite loader is presented

## Description
Hi,
We are facing the issue with default magento2.17
#issue:
While selecting the OptionType select fields for second time its loadind continuosly.

Please find the steps in the screenshot:
https://prnt.sc/fwkrc5

Thanks

**Comment by SanderJP** [comment]
I can reproduce this on a clean 2.1.7 installation with these steps:

1. Create or edit a Simple product.
2. Add Custom option.
3. Select 'Drop-down' Option Type.
4. Click the 'Add value' button to add an empty row, leave it empty.
5. Select a different Option Type (doesn't matter which).
6. Select 'Drop-down' Option Type again.

Result is a infinite loader and no javascript error message.

**Comment by RomanKrut** [comment]
@NagarajuKasa Hi, thanks for your feedback. The internal ticket was created MAGETWO-70954 to address this issue.

**Comment by NagarajuKasa** [comment]
thanks for reply i hope you will fix in the coming version.... thanks

**Comment by NagarajuKasa** [comment]
is there any update on this ticket?

**Comment by magento-engcom-team** [comment]
@NagarajuKasa, thank you for your report.
We've created internal ticket(s) MAGETWO-70954 to track progress on the issue.

**Comment by briscoda** [comment]
I would like to work on this one, can you assign it to me?  #squashtoberfest

**Comment by okorshenko** [comment]
@briscoda  please accept the invite

**Comment by briscoda** [comment]
The problem here can be traced back to this file:

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows.js#L610

In cases where there are option values added for the "Select" option types, the javascript will try to keep track of those options if they are not deleted by clicking on the trash can icon. 

When the user toggles back to the select option, it then tries to do some logical not operation that seems to fail because the previous options don't seem to get properly deleted from the recordData.

I cannot think of a case in my testing where you would ever want the spinner to show up for these custom options. 

The solution might be to either make sure that the "recordData" gets updated correctly so that records don't linger, or to remove the spinner functionality from this altogether. I tried looking back through commit history to see what the reason was for adding in spinner functionality there, but couldn't really tell from looking at it.

One thing that I think will happen if you make the recordData remove those entries, will be that one existing products with custom options, you could potentially lose any custom options that were set.


@okorshenko Who would be the right person to advise on a potential solution?

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82943

**Comment by okorshenko** [comment]
the issue has been fixed and delivered to 2.2-develop branch. WIll be available with 2.2.2 release

**Comment by magento-engcom-team** [comment]
Hi @NagarajuKasa. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1285 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - ad6c0af7dddbe2855a336acd3fd55994851e6d26
 - 6d3d70a72f08cba36c3aef6b59eea8db40eb4071
 - 6b0c02c5fd00d7a4237c4e1fae40dc265e3e43c3
 - c8abb139f8006826989fe4231dabc21fd4a02fd0
 - c6a9b5f7b13554958b547f387637c4288eb60b0b
 - c867b81af936e01a3d8ba8baa7128de06a5b7cd5
 - 88a3ad00d3ca97da847531c86bf64055dc1d790b
 - d87e316a2d6ee55debe2e712359adba8cb70fdb2
 - c76b04c9acde117c1021270500c8ded6954f6f05
 - 5ae21099aaa19699525c798f9ac0ef10db47b311
 - 931133abf574f1db96450f11f5980ef359d32967
 - 4c927a0585f11921c5e422b7e4a15b787e6338bd
 - 060a8f9f2b08ed97b31667eb76cace1dc0e642be
 - 4da2a7d2657b0da67f8be43bffc85f04b5b7144e
 - 008ef5583892d73c04628f003a2ce3d97fe0ed72
 - d3642e88d26a9240a1a4d648d37d984a785672a9
 - d37ce089d56c230f5896d5d7e922bd928b3726e6
 - b22b232563359f9cbcbf09709e63a87be7e81446
 - 6c02a2d3a272e872d549881d91ed6d5235a33f77
 - f2ec2ea175469636acec0bf9f65f0601854f89a2

The fix will be available with the upcoming patch release.

**Comment by NagarajuKasa** [comment]
Thank you so much for updating.
Great job.
