### ISSUE TITLE
Phoenix/Moneybookers

### ISSUE THREAD

**Issue by riconeitzel** [magento/magento2#103]
Hey Guys,

is there a reason for keeping that Community Module in Magento2 as a prebundled extension?

Best,
 Rico

**Comment by magento-engcom-team** [comment]
Hi @riconeitzel. Thank you for your report. 
The issue has been fixed in magento-engcom/import-export-improvements#117 by @pogster in 2.3-develop branch
Related commit(s):
 - [a765ec76e6590039f0441beb26afa356a5b84c6d](https://github.com/magento/magento2/commit/a765ec76e6590039f0441beb26afa356a5b84c6d)
 - [d45e4f8d376e200e176446765670b5d2d84cd8a5](https://github.com/magento/magento2/commit/d45e4f8d376e200e176446765670b5d2d84cd8a5)

The fix will be available with the upcoming 2.3.0 release.

**Comment by riconeitzel** [comment]
hey @magento-engcom-team, I'm sure this message is … uhm … wrong :D
