### ISSUE TITLE
Please delete, thank you.

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#10309]
Please delete.

Thank you.

**Comment by korostii** [comment]
And hello to you, too.
You do know that this is not a help desk, right? If you're in a need of some timely customer support, you've come to the wrong place.

The error in question might be caused by a legitimate reason, and is not necessarily symptomatic of a bug. It might be caused by conflicting requirements, lost configs or other server issues. However, the information you provide is not enough to identify the exact cause. 
If you are looking for some help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.

**Comment by GlobalOutsourcing** [comment]
Thank you, I will ask someone to resolve this I guess.

And allow the time allocated to this so they can look into other CE Magento 2 issues.
