### ISSUE TITLE
Changed Values in Database - but changes are not showing in backend

### ISSUE THREAD

**Issue by MoschenBayern** [magento/magento2#10312]
### Preconditions
1. Magento 2.1.7 on PHP 7.0.21
2. MySQL 10.0.30-0+deb8u2

### Steps to reproduce

1. In database table catalog_product_flat_1 we changes the values for "news_from_date" and "news_to_date" with the following sql-command:

Update 'catalog_product_flat_1'
Set 'news_from_date' = 'new date xxx'

2. No sql-errors 
3. Data in database are changed

### Expected result

1. In Backend it should be the new value for "news from date" and "news to date" at products

### Actual result

1. Nothing is changed. The old values are still there and are not changed to the new values we changed in database

Why is it not working? Do we need to change the value on other table?
Cache and index were rebuilt after database changes, but no changes in backend.

Can you pls help us

**Comment by korostii** [comment]
Yeah, it's a bad idea to edit the `flat` tables directly since they are just used as indices.
Generally, editing Magneto's EAV values via raw SQL is a bad idea, it's too easy to perform destructive changes if you miss some join or where clause.
I'd highly recommend to do the whatever changes you intend to do via some Magento-style PHP code. Or at least read up on how EAV works in Magento first.

**Comment by magento-engcom-team** [comment]
Hi @MoschenBayern
Flat tables are not used to display product information in the backend. Modifying the values directly in database is not intended.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion regarding this question. The GitHub issue tracker is intended for Magento Core technical issues only
