### ISSUE TITLE
Can't search for products with ampersand

### ISSUE THREAD

**Issue by cosmomathieu** [magento/magento2#10355]
We have an item called "Ro & De Black Faux Leather Panel Top." When searching for Ro & De it is finding no results even though it exists. If I search for "Ro" it finds nothing. I have to search for at least "Ro & De Black Faux." Cannot search for this item by brand because it cannot find results.

### Preconditions

1. Magento 2.4-develop
### Steps to reproduce

1. Go to storefront and search for "Ro & De" then search for "Ro & De Black Faux Leather"

### Expected result

1. Product Ro & De Black Faux Leather  should show

### Actual result

1. No result is found

**Comment by cosmomathieu** [comment]
Nothing, really?

**Comment by korostii** [comment]
Yes, really. Things move rather slow around here.
There's more than 2000 open issues in here and processing them takes quite a lot of time.
There are older bugs which have been here for months. Some of the 2.1 bugs even managed to pass the one-year mark recently, so you shouldn't be surprised, really. 

If the issue is blocking an urgent project for you something like that, you might have better chances trying to fix it yourself. 
(And if you do manage to do that, PRs are welcome here, it is an open source project, after all.)

**Comment by orlangur** [comment]
@korostii how is your comment useful? Why you spend your time on writing such comments instead of something useful? (like, raise topic regarding processes/release strategy/bug triage and so on in appropriate place)

@cosmointeractive to me this issue looks pretty similar to https://github.com/magento/magento2/issues/10176#issuecomment-313623626, try to tune full-text search engine or other suggested solutions.

**Comment by korostii** [comment]
@orlangur 
Well, hello. Long time no see.

> how is your comment useful?

For one, it explains that the issue probably wasn't simply overlooked as a unique case, but rather that the waiting time on this repository is quite high, on average.
I find that keeping people well informed about progress (or rather, absence or progress), future plans (or absence of such) lowers down the anxiety and helps to adjust their expectation. 
Feeling ignored is not a good feeling, you know.

Like, for example, if you look at mine older comments or @andidhouse's comments, you'll see that a lot of people expect the Magento, Inc. to put some effort into issue management, including but not limited to:
1. Providing clear timespans for Long-Time Support, similar to what PHP did, for example: http://php.net/supported-versions.php
Having clear release, end-of-life dates and guaranteed support periods helps merchants and module developers plan their projects and other endeavors in a more predictable manner. 
Like, for, example, you probably wouldn't waste resources starting a new project based on 2.1 if you knew 2.2 is scheduled to get released in a month and 2.1 will only receive security fixes after that.
2. Active bugfixing, at least for the current latest stable branch (2.1 at the moment). Active as in "major acknowledged issues fixed in order of weeks (and not months)".
3. Active support, as in "reported issues get a meaningful response in order of days (and not weeks)".
4. Clear and publicly explained rules, as in "there is no customer support provided for CE users, yet EE users are entitled to priority treatment" etc.

The idea is that Magento is open-core and thus its commercial product (such as Magento EE and Magento B2B) will also benefit from code quality and bugfixes delivered to the core in scope of supporting CE. Thus it is presumed to be beneficial for Magento, Inc. to take user input into account and put some effort into improving the product core (and not just creating more EE and B2B modules), as well. 

Thus some people expect to be appreciated and not to ignored when voluntarily submitting issues and suggested improvements. 

Having those expectations met with 22 days of silence might be soul-crushing, and even a response that doesn't provide an immediate solution might turn out to be useful, don't you agree?

**Comment by cosmomathieu** [comment]
@korostii Thanks your comment was most useful. 

@orlangur It was helpful to know that things move slow around these parts. Thanks.

**Comment by magento-engcom-team** [comment]
@cosmointeractive, thank you for your report.
We've created internal ticket(s) MAGETWO-80183 to track progress on the issue.

**Comment by orlangur** [comment]
@maghamed you may be interested in reviewing this (similar to previous one https://github.com/magento/magento2/issues/10355#issuecomment-323312355).

**Comment by manuelson** [comment]
@okorshenko can you assign to me?

**Comment by okorshenko** [comment]
Sure. Please accept the invitation on the GitHub

**Comment by manuelson** [comment]
@okorshenko done!

**Comment by adamsimonini** [comment]
@cosmomathieu it might have something to do with the ampersand. I am currently have troubles with it myself. Try removing &, and replacing it with something else that isn't a single character.

**Comment by Ravii0** [comment]
We have the same issue on 2.2.5

**Comment by cosmomathieu** [comment]
@adamsimonini I would have loved to try your suggestion, however, I no longer work on that project. Will try that in my next Magento site.

Thanks!

**Comment by alvarogrillet** [comment]
Same happens to me but with - or / if its on the product name. No results, but if i search for part of that name without the - the product appears in the search result. Version 2.2.1

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ravi-chandra3197** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197, here is your [Magento instance](https://i-10355-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-10355-2-3-develop.instances.magento-community.engineering/admin](https://i-10355-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Tajveez** [comment]
Hi, @magento-engcom-team I'm facing a similar issue, with numbers and quotations marks i.e. ' 18" X 6" ' and also with special characters like '®'. Is there any immediate fix for this?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30058` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
