### ISSUE TITLE
Customer entity the field is_active is not working

### ISSUE THREAD

**Issue by mpont91** [magento/magento2#10362]
I'm trying to lock some customers for they not being able to login neither place orders, etc. There is a field named `is_active` on the table `customer_entity`, but seems it does nothing.

### Preconditions

1. Magento 2.1.7
2. PHP 7.0.18
3. MySQL 5.7.18

### Steps to reproduce

1. Create a new customer
2. Set `is_active=0` on the table `customer_entity` in the ddbb manually for this customer
3. Login with the customer's credentials.

### Expected result

1. It should deny the login, showing some error like this account is blocked or simply credentials are wrong.

### Actual result

1. It logged in successfully

**Comment by magento-engcom-team** [comment]
@slayerbleast, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by crissanclick** [comment]
I'm working on this feature at #MM17ES

**Comment by GianniPDF** [comment]
I have made some progress to this issue, forgot to mention it, please assign the issue to me please #MM17ES. I have talked to @crissanclick

**Comment by magento-engcom-team** [comment]
Hi @slayerbleast. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/36
