### ISSUE TITLE
Re Index

### ISSUE THREAD

**Issue by huzanspenta** [magento/magento2#10361]
Hi,
Can someone please help me with reindex issue. How can I reindex  items?

**Comment by ghost** [comment]
http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-index.html

**Comment by huzanspenta** [comment]
Thanks @lclghst 
However I'm struggling with this. Is there a code that I can add in Cron jobs?

**Comment by ghost** [comment]
What are you struggling with?

Please try and elaborate on what your problem is and what you are trying to do.

**Comment by huzanspenta** [comment]
Everything.

My website is on bluehost and I'm unable to go through the full process. Could you help me out?

**Comment by orlangur** [comment]
GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

It is better to use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

The documentation explains how to configure cron to run reindexing: http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-cron.html

**Comment by choukalos** [comment]
Did you setup Cron?

Most shared hosts do not let you run frequent background processing activity.  Magento Cron kicks off every minute and there's a variety of activities that happen - which include cron.

In addition as your effective sku count increases (aka # sku X # store views X #customer groups) in Magento 2.0.x & 2.1.x you'll need to have more memory allocated to PHP & update mysql config to allocate more memory to tmp_table_size.  In the upcoming Magento 2.2.0 this isn't needed (out of the box will work with default MySQL config & only needs 256M of PHP ram for indexing processes; you can allocate more which can improve performance for higher effective sku count stores).
