### ISSUE TITLE
in my magento 2 website shipping page not showing

### ISSUE THREAD

**Issue by abhi1292** [magento/magento2#10375]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment]
Could you please care to add any more details than that?

The you're experiencing might be caused by a legitimate reason (for example, if it's the CMS page you're talking about - it could have status "Disabled") and is not necessarily symptomatic of a bug. In any case, the information you provide is not enough to identify the exact cause. 

If you are looking for some help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
Please keep in mind that this is not a help desk: the GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.
