### ISSUE TITLE
Disable logging per module

### ISSUE THREAD

**Issue by mzeis** [magento/magento2#1039]
Some extensions log useless stuff that pollutes the logs.

The problem could be avoided if Magento as well as the extension vendors would pay more attention to the log levels already provided and use them accordingly (e.g. differentiate between debug output and real information / notices / warnings / errors).

As it may not be possible to force using the correct log levels it would be nice to have an option in the System Configuration to disable logging. One of many possible ways to solve this in the UI would be to have a multi-select listing all modules in the installation.

**Comment by antonkril** [comment]
Calls to log don't provide module for which this call happens, so we will not be able to distinguish from which module the log entry comes

**Comment by mzeis** [comment]
That's true.

@schmengler suggested that debug_backtrace() could be investigated. See https://github.com/firegento/firegento-logger/issues/62. I admit that this may not be reliable. However if the log entity was to be redesigned this could be taken into account (e.g. if the log functionality was refactored to be implemented via traits, a different service contract / DI implementation, ...).

**Comment by antonkril** [comment]
Theoretically it's possible to inject different log instances to classed of different modules, but that would impact performance of ObjectManager (module checks would become required on each instance creation) and might become overkill. Filtering log results seems much cheaper solution.

**Comment by alankent** [comment]
Is the logger global? Or could each module have a separate logger instance initialized with the module name (via DI.xml file)? That is, it is not "magic" in object manager - it's just a different constructor argument if a class wants to log something.

Alternative approach is to have "switches" where "good" code should check if a switch is set before calling the log function. This avoids creating strings that are not actually written, but tends to make the code ugly.

    if (switch.isOn("catalog")) warn("blah blah ".$x." Blah blah blah");

The concatenation is only done if the flag is on, rather than computing the string only to have it discarded later.

**Comment by mzeis** [comment]
For reference: @jayelkaake built an M1 extension analysing debug_backtrace: https://github.com/jayelkaake/logmanager

My personal preference would be to have a more enhanced logging functionality like https://github.com/firegento/firegento-logger.

The key features for me:
* let me decide where the log should go (File, Database, syslog, ...)
* let me decide what should be logged where (e.g. we have a log for all messages in the DB, one for warnings/errors only in the file)
* let met black/whitelist the messages to be logged

I do understand the performance implication mentioned by @antonkril.

I thought about it again and it might be enough to:

* have the key features mentioned above in the core
* giving direction in the documentation when and how to use the different log levels
* make it mandatory to define a log level when writing to the blog.

Could you consider the last point? If people had to define the log level themselves (i.e. you are not defaulting to a certain log level) that may help. 

Making it possible to disable logging on a module level could then be left to the community if still necessary, either by providing an extension like Jay did or by encouraging the extension developer to improve the logging in their respective extensions.

**Comment by orlangur** [comment]
Starting from [0.42.0-beta2](https://github.com/magento/magento2/blob/develop/CHANGELOG.md#0420-beta2) M2 uses [PSR-3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md) compatible [Monolog](https://github.com/Seldaek/monolog) library, de-facto logging standard in PHP world, instead of old logger inherited from M1. In order to achieve logging parity, like `system.log`, `exception.log` and `debug.log` separation, only a tiny configuration of Monolog was needed: https://github.com/magento/magento2/tree/develop/lib/internal/Magento/Framework/Logger/Handler

So, currently logging in M2 is used in most recognizable and standardized way. Among three options to change logging behavior:
- add features to core
- configure Monolog
- replace logger implementation [via DI](https://github.com/magento/magento2/blob/develop/app/etc/di.xml#L9)

I personally would prefer second one and consider third as acceptable for rare cases.

At the first glance it looks like key features you described are supported by [Monolog](https://github.com/Seldaek/monolog) out of the box:
> Every Logger instance has a channel (name) and a stack of handlers. Whenever you add a record to the logger, it traverses the handler stack. Each handler decides whether it fully handled the record, and if so, the propagation of the record ends there.

> This allows for flexible logging setups, for example having a StreamHandler at the bottom of the stack that will log anything to disk, and on top of that add a MailHandler that will send emails only when an error message is logged. Handlers also have a $bubble property which defines whether they block the record or not if they handled it. In this example, setting the MailHandler's $bubble argument to false means that records handled by the MailHandler will not propagate to the StreamHandler anymore.

> You can create many Loggers, each defining a channel (e.g.: db, request, router, ..) and each of them combining various handlers, which can be shared or not. The channel is reflected in the logs and allows you to easily see or filter records.

Custom logging logic, like `debug_backtrace` analysis for extensions which do not follow [PSR-3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md), could be easily implemented but does not seem to be suitable for core.

> - giving direction in the documentation when and how to use the different log levels
> - make it mandatory to define a log level when writing to the log.

It's exactly what [PSR-3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md) is intended for. Log level is [already mandatory](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php).

**Comment by mzeis** [comment]
Thank you for the explanation - that's very helpful. I'll close the issue then and wait how things work out in practice.

**Comment by wsakaren** [comment]
Hi, know this is closed but just wanted to add that we ship our own logger with every extension.  This is open source, and will support any extension - https://github.com/webshopapps/wsalogger

We wrote this a number of years back, and are planning to update for Magento2 to key into the features there. The advantage of this logger is that you can set it to display not just in the system log but also in the admin panel. We did think about having a separate log per extension but decided against this approach as its better sometimes to run them in one log so you can see the sequence of events as they interact with each other.  

We showed this logger to Yoav and the architects back in 2010 but there was a total lack of understanding of the value of the tool in my mind.

I'm sure what we are doing could be extended (the open source one isn't our latest codebase btw) but it supports various log levels, emailing logs, and this in admin view, all of which I think are important features. I'm very much a fan of log4j and hope to see something similar in Magento.  We also have support for showing logs in the cart.

The frustration we find is that because other providers aren't also logging we can't see their interactions, if we could get everyone to use a common format my feeling is this would empower not just extn providers, but the merchant and web design agencies themselves.

There are other loggers out there, I know the Mage Hackathon team did one which I think some people have adopted. We did this before that, if there was a common one we would use it because we would rather concentrate on shipping than sysadmin tools.

The ability to give merchants tools to be able to self-diagnose should not be underestimated, and at present this is severely lacking.

**Comment by piotrekkaminski** [comment]
Hey Keren. Given the integration with Monolog that can send out logs to things like Loggly I would assume we will recommend all extensions providers to use common logger. Can you tell me from customer experience would asking customer to add another handler for monolog would be possible? I would assume no. How about having customer send you the log file? Do you think only web interface in admin is a solution? I would rather use a 3rd party centralized service like Loggly instead but need more input.

**Comment by piotrekkaminski** [comment]
@mzeis your question is very relevant. It would be great to be able to filter out logs by module.  @orlangur is it possible to automatically add current module name to all logs or this would have to be explicitly added to all log messages? This is actually pretty important to be able to analyze logs

**Comment by wsakaren** [comment]
Merchants are not going to use loggly.  For our particular area they want it in the admin panel, or they want better verification when entering data. For instance when packing boxes they want to be able to switch on logging to view this. They will not want to go to Loggly, it will scare the hell out of them.

The reality we find is that merchants are involved at this level, and even a lot of the web devs do not have a clue about stuff. Make it simple.

Customers send us log files today, but they find it hard to do sometimes. We have screencasts that walk them thro the process. We have many many customers that either do not have access to their file system, or have no clue how to use it.

**Comment by orlangur** [comment]
@piotrekkaminski,
> is it possible to automatically add current module name to all logs or this would have to be explicitly added to all log messages? This is actually pretty important to be able to analyze logs

It is possible with `debug_backtrace` hack or if each module will have separate logger instance, as [suggested](https://github.com/magento/magento2/issues/1039#issuecomment-74118633) by @antonkril.

Is it not enough to have all messages in one log with ability to [filter](https://github.com/magento/magento2/issues/1039#issuecomment-74071598) some of them? We can do it pretty accurate even with current log message format: just collect all possible log messages from all extensions (like we do for translations) and then for each message in UI specify which extension could add the message to log.

**Comment by Landkeks** [comment]
@wsakaren I haven't checked how exactly M2 uses Monolog, but in theory, this should be really easy to do. Just add a custom [Handler](https://github.com/Seldaek/monolog#handlers) to the Monolog instance, which sends the logs to the admin panel, and you're done. Monolog can do everything you mentioned.

**Comment by devdesco-ceo** [comment]
How to completely disable debugging and writing anything to debug.log unless lets say I exclusively enable debug output from lets say FedEx Shipping extension?

Or may be change debug / syslog reporting level?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Disable-logging-per-module/idi-p/45814).
