### ISSUE TITLE
Parallel REST API requests

### ISSUE THREAD

**Issue by klakovsky** [magento/magento2#10396]
### Preconditions

1. Magento CE 2.1.7 fresh instants without sample data.
2. Two simple products
3. One order for 2 different items each 1 qty.

### Steps to reproduce

1. Sent 4 parallel requests:
/rest/V1/order/:orderId/invoice
/rest/V1/order/:orderId/invoice
/rest/V1/order/:orderId/ship
/rest/V1/order/:orderId/ship

### Expected result

1.  Order have status "Complete", both items with:

> Ordered | 1
> Invoiced | 1
> Shipped | 1

### Actual result

1. Case by case, wrong order status and item Ordered/Invoiced/Shipped qty.

/V1/order/:orderId/invoice
/V1/order/:orderId/ship
/V1/order/:orderId/refund
did not support parallel requests

**Comment by sshymko** [comment]
We're experiencing the issue on 2.1.4.
The code behind the API calls hasn't changed in 2.2, so it should suffer the same issue.

Insufficient isolation between concurrent order update transactions is the root cause of the issue.
For instance, method `\Magento\Sales\Model\InvoiceOrder::execute()` and alike retrieve an order via `$this->orderRepository->get($orderId)` by a plain `SELECT` query **outside of a transaction**.
Instead, `SELECT...FOR UPDATE` query needs to be used **inside the transaction**. That will lock the order record for exclusive modification by the first API call and make all other API call wait until the first transaction completes. Then, all of them will read the updated version of the order record.

**Comment by sshymko** [comment]
@antonkril @akaplya 
Magento ORM does not protect from data integrity issues on concurrent requests to modify the same entity. For instance, repositories do not support loading with an intent to modify the entity. Basically, repositories have only a `get()` method, but nothing like `getForUpdate()` that would lock down the record via `SELECT...FOR UPDATE` for exclusive modification instead of a plain `SELECT`.

**Comment by magento-engcom-team** [comment]
@klakovskiy, thank you for your report.
We've created internal ticket(s) MAGETWO-82162 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@klakovsky, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
