### ISSUE TITLE
Zend_Db_Adapter_Exception

### ISSUE THREAD

**Issue by abdul4343** [magento/magento2#10391]
getting an exception
![error](https://user-images.githubusercontent.com/19662387/28821563-89df8dd0-76d3-11e7-899d-7b58335d9dae.png)

**Comment by korostii** [comment]
The error in question might be caused by a legitimate reason is is not necessarily symptomatic of a bug. It is likely to be caused by unsuitable environment which you happen to be using, however the information you provide is not enough to identify the exact cause. 

Thus if you are, in fact, reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed (if any), preconditions, exact steps to follow, screenshots and stack trace from browser console and even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 

If you are looking for some help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.

**Comment by orlangur** [comment]
I expected env to be Ubuntu even before I saw it on a screenshot :)

Please try to investigate/google env problem prior to bug report. This seems to be a known issue: https://stackoverflow.com/questions/42926075/pdoexception-sqlstatehy000-2002-php-network-getaddresses-getaddrinfo-faile
