### ISSUE TITLE
Wysywig editor shows broken image icons

### ISSUE THREAD

**Issue by deadlyw1re** [magento/magento2#10417]
### Preconditions

1. Magento 2.1.7
2. PHP 7.0

### Steps to reproduce

1. Add image in Wysywig editor

### Expected result

1. Image is shown in editor

### Actual result

1. Broken image icon
2. Url is `<img src="http://domain/path-to-magento/adminurl/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvcGRmL3BkZi5wbmcifX0,/key/e44fd2b2430f15239de43de5a10cb958615b525bb7bca920ab2865c99ff7de7d/" data-mce-src="http://domain/path-to-magento/adminurl/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvcGRmL3BkZi5wbmcifX0,/key/e44fd2b2430f15239de43de5a10cb958615b525bb7bca920ab2865c99ff7de7d/">`

**Comment by hostep** [comment]
If this occurs on the product or category wysiwyg fields, then it is probably a duplicate of https://github.com/magento/magento2/issues/6138, and this bug will be fixed in Magento 2.1.8: https://github.com/magento/magento2/commit/ba6612462c260da7cc534b6365623993a6fe4311

**Comment by deadlyw1re** [comment]
@hostep This occures in the wysiwyg editor itself, on the frontend the images are visible.

**Comment by hostep** [comment]
@deadlyw1re: Yes, but which wysiwyg editor? The one in the CMS pages/blocks shouldn't have this bug, only the wysiwyg editor on the product and categories edit forms if I remember correctly.

**Comment by deadlyw1re** [comment]
@hostep This bug occures on CMS pages/blocks and products/categories

**Comment by PieterCappelle** [comment]
@hostep I think the bug is back in 2.1.9. We are having the same problem in CMS Pages / Blocks. When you insert image in 2.1.8, we get ```<p><img src="{{media url="wysiwyg/Hond.jpg"}}" width="1024" height="683" /></p>``` when we insert image in 2.1.9 ```<p><img src="http://local.magento/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvVmVsZC5qcGcifX0%2C/key/d3f89696a93152f6d352e5d5cb391180a27c8a7924d9fe3b583d3e9f03d00753/" width="959" height="1024" /></p>```

**Comment by hostep** [comment]
@PieterCappelle: that's weird, I can't really see anything at first sight in the [diff between 2.1.8 and 2.1.9](https://github.com/magento/magento2/compare/2.1.8...2.1.9) which can cause this bug to re-appear.

Can you reproduce it on a clean 2.1.9 installation?

**Comment by PieterCappelle** [comment]
@hostep Tomorrow at MM17BE? Will show you my case.

**Comment by hostep** [comment]
Confirmed, tried it on a clean 2.1.8: no problem
Then on a clean 2.1.9: and the problem you describe appears. God damned, I hoped we were finally rid of this bug, but it came back :(

(See you tomorrow at MM17BE :))

**Comment by PieterCappelle** [comment]
You should join the Slack channel of Magento. Let's fix this in the contribution day :-)

**Comment by okorshenko** [comment]
Just for info: https://github.com/magento/magento2/compare/2.1.8...2.1.9#diff-92c32b12996a53a237ff51fa0d39d829R113

**Comment by magento-engcom-team** [comment]
@deadlyw1re, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80230

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81305

**Comment by LSERRE** [comment]
I have the same issue on 2.2.0.

**Comment by WalterSmulders** [comment]
I experienced the same issue today and it kept me busy for a half day, but I found that at least my problem was not related to the Magento code.

One of the external extensions had a extra empty line at the beginning of the registration.php. This extra empty line was added at the beginning of the response. Which in turn made the browser not recognising the image and thus not showing it since it doesn't start with the required bytes.

I could find the registration.php that was responsible for this error by debugging trough `app/etc/NonComposerComponentRegistration.php` simply put a `echo $file;` after `include $file;` if you see that the text (filenames) start on a new line you know it is the file that starts on that line.

**Comment by okorshenko** [comment]
Hi @deadlyw1re. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1380 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - [e9238bcb04f75a5ef0d801ef7a4c372832d83aad](https://github.com/magento/magento2/commit/e9238bcb04f75a5ef0d801ef7a4c372832d83aad)
 - [c46acb7f26afb967c2e727d9557d00a03418a599](https://github.com/magento/magento2/commit/c46acb7f26afb967c2e727d9557d00a03418a599)
 - [3d5cc519f30a8664aadca0b1378ff62138fd1bf9](https://github.com/magento/magento2/commit/3d5cc519f30a8664aadca0b1378ff62138fd1bf9)
 - [fcd3e7af7984ed9887a8213c51ff3cc29546fd93](https://github.com/magento/magento2/commit/fcd3e7af7984ed9887a8213c51ff3cc29546fd93)
 - [a37313a401cd143fbfb6642108f602a16d96d211](https://github.com/magento/magento2/commit/a37313a401cd143fbfb6642108f602a16d96d211)
 - [4e00485ed12b762e38bbf5e38cce97981a43dedf](https://github.com/magento/magento2/commit/4e00485ed12b762e38bbf5e38cce97981a43dedf)
 - [d73cca2aee6113f66e8098512343d4e440afe65e](https://github.com/magento/magento2/commit/d73cca2aee6113f66e8098512343d4e440afe65e)
 - [0d8938cfd7f6c85146e1ad3176947eb6f8a945ae](https://github.com/magento/magento2/commit/0d8938cfd7f6c85146e1ad3176947eb6f8a945ae)
 - [d544ca2a6d99132e66e8b416ab73cc712de149f9](https://github.com/magento/magento2/commit/d544ca2a6d99132e66e8b416ab73cc712de149f9)
 - [e075ca794af8189260359434488029b2768fc29d](https://github.com/magento/magento2/commit/e075ca794af8189260359434488029b2768fc29d)
 - [a6c2bc2b471586eb44d9b4fc2341517bb64cad15](https://github.com/magento/magento2/commit/a6c2bc2b471586eb44d9b4fc2341517bb64cad15)
 - [960d58cfc3ef200654f1c19a5eca8cb905da686c](https://github.com/magento/magento2/commit/960d58cfc3ef200654f1c19a5eca8cb905da686c)
 - [dbdb772c0260347267701f5f54196fec1c0e5109](https://github.com/magento/magento2/commit/dbdb772c0260347267701f5f54196fec1c0e5109)
 - [bac46ce7f62207e27fdb401e4e72040c2bed32db](https://github.com/magento/magento2/commit/bac46ce7f62207e27fdb401e4e72040c2bed32db)
 - [1503f3a49de2d20ed3729823a4410cbfba3fd92a](https://github.com/magento/magento2/commit/1503f3a49de2d20ed3729823a4410cbfba3fd92a)
 - [17662c6eb0948da16b97a93ad0c231947eba933d](https://github.com/magento/magento2/commit/17662c6eb0948da16b97a93ad0c231947eba933d)
 - [2a72e5cc81c7b28aa04c5c64a63a8493043d6384](https://github.com/magento/magento2/commit/2a72e5cc81c7b28aa04c5c64a63a8493043d6384)
 - [ddaf5c6df7e2b294085ef6133820a6a1b6b12762](https://github.com/magento/magento2/commit/ddaf5c6df7e2b294085ef6133820a6a1b6b12762)
 - [7bf80fdc06c32325040dada5082b78975b910e1b](https://github.com/magento/magento2/commit/7bf80fdc06c32325040dada5082b78975b910e1b)
 - [efb8bf6a94a99130fe013f4ef9c3c0c39777b7b1](https://github.com/magento/magento2/commit/efb8bf6a94a99130fe013f4ef9c3c0c39777b7b1)
 - [321263009819a694221ce8a06902cf7a4ba3ff00](https://github.com/magento/magento2/commit/321263009819a694221ce8a06902cf7a4ba3ff00)
 - [ac9c10b96940ed5393581135146c8ea29eddd143](https://github.com/magento/magento2/commit/ac9c10b96940ed5393581135146c8ea29eddd143)
 - [2c6c9c06b1a69a20f4b7bfcd27e1eebf8e26ad2b](https://github.com/magento/magento2/commit/2c6c9c06b1a69a20f4b7bfcd27e1eebf8e26ad2b)
 - [73522bf72d57e503281077abb20b4000375eb57d](https://github.com/magento/magento2/commit/73522bf72d57e503281077abb20b4000375eb57d)
 - [818cf61d28821cc2a5435c60b6308adcb5a3ea26](https://github.com/magento/magento2/commit/818cf61d28821cc2a5435c60b6308adcb5a3ea26)
 - [61d0d9608493f65a0c0eafe264e1575eaa84b7be](https://github.com/magento/magento2/commit/61d0d9608493f65a0c0eafe264e1575eaa84b7be)
 - [85e0956b08923ca721e3577edd684aec02a93b6b](https://github.com/magento/magento2/commit/85e0956b08923ca721e3577edd684aec02a93b6b)
 - [1698afc93aed22284efa2bf9d943b2108b5af3ab](https://github.com/magento/magento2/commit/1698afc93aed22284efa2bf9d943b2108b5af3ab)
 - [ce7faf6203e39aefdf177e2a6a4168cbb5223993](https://github.com/magento/magento2/commit/ce7faf6203e39aefdf177e2a6a4168cbb5223993)
 - [70051020df3e9053272cc6926680895b9898a35b](https://github.com/magento/magento2/commit/70051020df3e9053272cc6926680895b9898a35b)
 - [bd07bcc9e681810ac35fd59b3ef74970e55dca37](https://github.com/magento/magento2/commit/bd07bcc9e681810ac35fd59b3ef74970e55dca37)
 - [16930193a78f00b50f9fa16012d96c5c1d481f19](https://github.com/magento/magento2/commit/16930193a78f00b50f9fa16012d96c5c1d481f19)
 - [ba7da597361305e6a91c04fe39d63162408af3b3](https://github.com/magento/magento2/commit/ba7da597361305e6a91c04fe39d63162408af3b3)
 - [d9e8b87af003d550f39e9d34cf19f94088660a38](https://github.com/magento/magento2/commit/d9e8b87af003d550f39e9d34cf19f94088660a38)
 - [0bb740b82dcf7324dad4b1650f13838b51950368](https://github.com/magento/magento2/commit/0bb740b82dcf7324dad4b1650f13838b51950368)
 - [c51f94c3a115468ea4808478e67c88c13dca1445](https://github.com/magento/magento2/commit/c51f94c3a115468ea4808478e67c88c13dca1445)
 - [9f3f3e05d91951f56b469cf47576e3c2eb72a9b5](https://github.com/magento/magento2/commit/9f3f3e05d91951f56b469cf47576e3c2eb72a9b5)

The fix will be available with the upcoming 2.3.0 release.

**Comment by Vishrootways** [comment]
How to solve this error in Magento 2.1.8 version? Please help us if anyone know.
