### ISSUE TITLE
Customizable Options is not showing on frontend

### ISSUE THREAD

**Issue by piavgh** [magento/magento2#10469]
### Preconditions

1. Magento version 2.1.7
2. XAMPP 7.0.21 Windows 10

### Steps to reproduce

1. Setup a new Magento installation
2. Create a new product
3. Add some custom options to product: http://prntscr.com/g6606f

### Expected result

1. Custom options should appear in product info page so that customer can choose, and then they can add to cart: http://prntscr.com/g660mx
2. After adding to cart, custom options should be displayed below product name: http://prntscr.com/g6611z

### Actual result

1. At frontend, the place which custom options should be appeared is now nothing
http://prntscr.com/g660mx
http://prntscr.com/g6611z

I'm not sure if this is a problem on Windows only. Because about 2 months ago, I installed Magento 2.1.7 on my Macbook and everything is ok, I can see custom options appeared at frontend.

**Comment by piavgh** [comment]
Hi guys,
I managed to solve this problem by change from in stock to out of stock and then change back to in stock again. Now custom options are displayed well.
I don't know what's the reason but now the issue seems to be fixed so I will close this.
Thanks

**Comment by deadlyw1re** [comment]
Having same issue, after resaving product they show again

**Comment by LexKoomen** [comment]
Any fixes yet? I'm having the same problem.

**Comment by pniel-cohen** [comment]
Having the same issue & resaving the product seems to solve that. 
Any idea what's the cause? How to prevent that? How to fix that for all products without resaving them all?

**Comment by barryvdh** [comment]
We're still having this same issue. Is there a fix for this yet?

**Comment by TomashKhamlai** [comment]
It looks like it has been fixed at least in the latest release.
XAMPP 7.0.21 Windows 10 is not supported as a platform. Mac OS, Windows and even Linux systems that do not belong to x86-64 architecture are also not supported. Please check the documentation [Magento 2.2.x technology stack requirements](https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html)

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.
