### ISSUE TITLE
The price has been multiplied by the exchange rate twice

### ISSUE THREAD

**Issue by whitepepper355** [magento/magento2#10490]
### Preconditions
1.Magento2.1.7
2.PHP7
3.My site Base Currency is US$
4.I set a product price 168US$.
5.US$ JPYen rate is 109.9620.

### Steps to reproduce

1. show the product detail page
2. change currency JP Yen
3. The price is 2,031,396.20Yen It's too high!
4. Select color, the price is 18,473.62Yen. This is collect.

### Expected result

1. the price is 18,473.62Yen

### Actual result

1. The price is 2,031,396.20Yen
[https://tokyo-products.com/flash-eva01-pcb-art-iphone7-case.html](url)

Thank you in advice.

**Comment by denchev** [comment]
This is known issue which is fixed in 2.2 branch but unfortunately not in 2.1 (even the recent 2.1.8). You can see the fix commit here:
https://github.com/magento/magento2/commit/1527713f82aa535692d23b3f5c432b80b13f89ae

Basically you need to remove the currency convert wrapper. You can write a preference for this file and replace your defected one with one from 2.2 branch. Of course it sounds simpler than it actually will be :)

**Comment by whitepepper355** [comment]
Thank You so much!
