### ISSUE TITLE
Fatal error: Call getTranslateInline of null when generating some sitemap with errors

### ISSUE THREAD

**Issue by Koc** [magento/magento2#10502]
### Preconditions

1.  Mage 2.1.8
2. PHP 7.0.21

### Steps to reproduce

1. create some sitemap with error
2. 
3. 

### Expected result

1. error sended to email

### Actual result

1. fatal error: try call getTranslateInline of null

see
https://github.com/magento/magento2/blob/develop/app/code/Magento/Sitemap/Model/Observer.php#L125

`_translateModel` field not even defined in this class.

**Comment by Andrii-Deineha** [comment]
Hi @Koc , thanks for reporting this issue. Internal ticket was created MAGETWO-71992.

**Comment by marinagociu** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
The issue has neeb fixed and delivered to 2.2-develop branch

**Comment by magento-engcom-team** [comment]
Hi @Koc. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1358 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 2e90684d1f906a63c37e2dea4710aee59c0c0a58
 - f99b75906ab0d370005692499faebba810aa3984
 - 49a3076876a44798397495c6f376699eb3214528
 - b754973b0c24a5d4482ba6b027f8d673a64dae80
 - ed833c492e51f78ee2523c0b2eb5fee37c91166d
 - d8b73d3bb4b8ff66faa308e761b9ade25d0bf9f7
 - 60e83eac5925e1ec01cbc11b8eb1acc5305a7a23
 - dc69e175dc95befc3e1c0eb1b9d51c23a0e1e0e9
 - 6b9c188627aa4d9614c5ffe1a0436d75e17bb796
 - 3b58efc8e8cf3f856f7f0edbe84bd2ceb5f167b2
 - 8b40859ed856295dfd4240638c26d7b17807402a
 - 11922a14040b4869da87445fa627533256164595
 - 0bd39d42c785cac7ee0b49434cb957baa04f6c7f
 - 8bbb8bbb675f10f9632e76ff27a8199a7a3aa4ee
 - f8307d9d169debab91b1440d131dc166eb2e2640
 - 768c769b2772743e8599840aa8dc523597d0b6e5
 - 16a10291b25f826d066f155257a3922ee3f01682
 - 17a26cbcf93a3d95815a21b92dc9bc04ec116e58
 - 8f1d8e78df9cd8f648ea30d399f81816ad1d6d01
 - 5d084ce7979f07e7b1d6ac9980be13fdd2a378cd
 - d248f4e39a1fca56c5ea429dca5af190e28c56cb

The fix will be available with the upcoming 2.3.0 release.
