### ISSUE TITLE
Redis backed sessions expire in 60 seconds when cookie lifetime is set to 0

### ISSUE THREAD

**Issue by ekuusela** [magento/magento2#10529]
Setting cookie lifetime to 0 should keep the session open until browser is closed. However, the cookie lifetime value is used as a parameter to the redis's EXPIRE function (after making sure it falls within the configured min/max values, where 60 seconds is the default minimum). Instead, cookie lifetime of zero should be a special case.

Some relevant code:
- getLifetime() function at magento2/lib/internal/Magento/Framework/Session/SaveHandler/Redis/Config.php
- getLifetime() function at magento2/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php.

### Preconditions
1. Magento 2.1.8 with redis configured as session storage
2. Set cookie lifetime to 0 in Stores -> Configuration -> General -> Web

### Steps to reproduce
1. Navigate to some page in the store frontend and monitor redis for "expire" commands
2. Observe that they are set to expire in 60 seconds, causing users to log out and visitor carts to get emptied in the same timeframe

### Expected result
1. Redis backed sessions should last until the browser closed (or some reasonable timeframe).

### Actual result
1. Redis backed sessions expire in 60 seconds.

**Comment by tkotosz** [comment]
@ekuusela if I remember correctly there is a "min_lifetime" config in the env.php for the redis session config. Most likely it is configured to be 60 in your case.

**Comment by tkotosz** [comment]
Ye just checked it here: http://devdocs.magento.com/guides/v2.0/config-guide/redis/redis-session.html
`'min_lifetime' => '60',` - prob this need to be changed :thinking:

**Comment by rg-srini** [comment]
@tkotosz : Could you please confirm that this min_lifetime is equivalent to PHP's session timeout. [session.gc-maxlifetime] (http://php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime)

If we set this to 15 minutes (900 seconds) and session.gc-maxlifetime is 24 minutes, then in 15 minutes of idle time, the session will be destroyed?

Regards,
Srini

**Comment by JacobBrownAustin** [comment]
I've created an internal ticket to track this issue:  MAGETWO-72236

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@keharper, can you help us by providing information about https://github.com/magento-obsessive-owls/devdocs_internal/pull/1?
The merge was probably made somewhere between 20/Sep/18 25/Sep/18.

**Comment by keharper** [comment]
The information described in the PR linked above has been published on devdocs. It looks like I didn't close the PR because it was opened under an obsolete workflow. Closing.

**Comment by sdzhepa** [comment]
Hello @ekuusela 

Internal ticket `MAGETWO-72236` was fixed.
As the fix DevDocs related to redis session were updated.
Was added information block that explains behavior for cookie lifetime and Redis session. Please see next pages for more details:
- https://devdocs.magento.com/guides/v2.0/config-guide/redis/redis-session.html
- https://devdocs.magento.com/guides/v2.1/config-guide/redis/redis-session.html
- https://devdocs.magento.com/guides/v2.2/config-guide/redis/redis-session.html
- https://devdocs.magento.com/guides/v2.3/config-guide/redis/redis-session.html


This ticket can be closed.
Please, feel free to reopen or create a new one if issue still exists or was not fully fixed

Thank you for feedback and collaboration
