### ISSUE TITLE
Apply discount does nothing "Request does not match any route" (On every coupon)

### ISSUE THREAD

**Issue by EthicalErik** [magento/magento2#10534]
### Preconditions
1. Magento 2.1.8
2. PHP 7.0.21

### Steps to reproduce
1. Add a random product to the cart
2. Go to the checkout
3.  Fill something in at the coupon field
4. Press apply discount

### Expected result
1.  A display that the coupon does not exist

### Actual result
1. `Nothing happens from the user end.
2. The chrome console gives a Empty_response error: https://cl.ly/2Q2h3u0r2y0R
3. When xml logging it turned on it shows it fails loading: https://cl.ly/1K0X352Q1602
4. Going to the request itself it shows it does not match any route: https://cl.ly/0r0G3f3n0W3s

Apache does not have any logs from this.
The same thing happends even when there is a valid coupon code named test.

### Special Notes
1. It is not mod security as we do not have that currently on our apache build.

2. I have seen other issues regarding the same message however all these had something to with characters like ' , " #. It seems that I get this message everytime even if I just 1 or one letter like a.

**Comment by EthicalErik** [comment]
*** Update

It seems that the cart coupon function is working fine.
On inspection the cart makes another request then the checkout does.

Cart coupon (The coupon works with this request)
https://cl.ly/0g3c3O1f2g2t

Checkout coupon (That doesn't work)
https://cl.ly/1H11441L042o

Is there a way to change the checkout coupon function to the same way as in the cart? That would solve the problem for me.

**Comment by magento-engcom-team** [comment]
@erik921 thank you for your bug report.
We've created internal ticket MAGETWO-75485 to track progress on the issue.

**Comment by EthicalErik** [comment]
This seems to be a apache configuration issue of some sort.
We changed to nginx and it all worked fine.

**Comment by RomaKis** [comment]
The problem is next:
1. When we enter invalid coupon code it sends put request and Magento takes it on Magento/Quote/Model/GuestCart/GuestCouponManagement::set($cartId, $couponCode).
2. Magento tries to  apply coupon code and throws exception "Coupon code is not valid" in Magento/Quote/Model/CouponManagement::set($cartId, $couponCode) .
3. The exception is caught  in Magento/Webapi/Controller/Rest::dispatch(\RequestInterface $request).
4. As exception type is NoSuchEntityException so the http code become 404 in Magento/Framework/Webapi/ErrorProcessor::maskException(\Exception $exception).
5. Magento/Framework/Webapi/Rest/Response::_renderMessages() check for errors and put exception http code to response http code. So now the response http code is 404 that's why we have error in console. Ajax on fail process exception message, so there isn't any problem for customer and he see the erro message as expected.

As a conclusion I don't know is it normal Magento behavior or it is bug. If it is a bug it need a deep analysis how the system should work.

**Comment by bytepattern** [comment]
I am in same problem when I try to add valid coupon code from checkout page. Return message: Request does not match any route. Any solution please

**Comment by fauzie** [comment]
@RomaKis i have same problem here.
Mine fix this issue by changing `to_date` value on coupon below year 2038. And it's okay now.
It is not a bug, see : https://en.wikipedia.org/wiki/Year_2038_problem

For magento team, please do not use date picker above 19 January 2038, because it causing error on php date.

**Comment by ywsw** [comment]
can someone please provide a solution to this issue? We are using Magento 2.2.5 and Apache 2.4. The discount codes do not work on the checkout page but they do work on the shopping cart page. The checkout page uses PUT which does not work and the shopping cart uses POST which does work. Can someone please provide a solution to get the discount codes working on the checkout?

It is _not_ related to mod_security as we do not even have that installed on the server.

SOLUTION: (in my case) I was using POUND as a reverse proxy so I can use Varnish for HTTPS and by default POUND blocks PUT and DELETE requests. By adding in the command "xHTTP 1" between the ListenHTTPS in the POUND config, PUT and DELETE requests are now allowed. Issue solved. I hope this can be of help to someone (@Toike)

**Comment by Toike** [comment]
I've got the same problem with Magento 2 version 2.2.5, promotion code working in shopping cart, but not on the payment page.

**Comment by rahulidea** [comment]
Same problem with Magento 2.2.3. Coupon working fine on cart page but not working on the checkout page. Same mirror copy is working on another webhost

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment]
The message ```The coupon code isn't valid. Verify the code and try again.``` appears when you submit something invalid in the input on the 2.3-develop. Looks like problem has been fixed.

**Comment by shansari25** [comment]
same issue with us - We have a discount code and it works in the view cart page but doesn't work in the checkout/#payment. In fact no action is taken when we click on Apply discount. Does anybody know the solution for this.

When we add a product to the cart and click on CHECKOUT which takes to a page colorcherry.com/checkout/#payment and there is Apply Discount button and textbox to enter a code and when we enter the code and Apply Discount, nothing happens, the discount code doesn't get applied. But when we VIEW CART instead of CHECKOUT then it takes to a different page and the discount code does work here. But normally customers are not going to click on VIEW CART rather they will just go to CHECKOUT page, apply the discount and progress for payment. So its a big flaw in the process. Can someone help @magento-engcom-team @ywsw @Sonal824 @stefanguapa @erik921 @magento-engcom-team @RomaKis @bytepattern @fauzie

**Comment by FadedOut** [comment]
Hello,

I realize this is a SUPER old git report but I just wish to help anyone coming across this on any Magento version even from years ago (because it's still relevant).

I believe it actually has to do with ModSecurity. If you look into the logs for ModSec, you'll most likely see something like the following:
```
Request:	PUT /rest/default/V1/carts/mine/coupons/coupon-code
Action Description:	Access denied with code 403 (phase 2).
Justification:	Operator GE matched 5 at TX:anomaly_score.
```
I wouldn't recommend altering the ModSec rules to accomodate for this, what I'm going to do is simply hide the field (using css: display:none;) on the checkout page.

Suggestion:
```
#checkoutSteps .checkout-payment-method .payment-option-title {display: none;}
```

My view here is two parts: 
1) The way Magento does the discount code by (it's basically AJAX - no page reload) it is using a PUT command and can be flagged for security purposes. 
2) I wouldn't modify ModSec because I believe this is for sanitation reasons, if you allow codes to be entered there (thus anything), you may be opening up security risks - though I'm not completely sure. I wouldn't want to test that theory (I'm not a hacker) so for me, the best option I believe will be to simply hide that discount/coupon field on the checkout page. It's pretty visible on the cart page so ultimately in the end your site will stay secure and not have errors happening (resulting in extra support emails). 
3) The solution for Magento might be to force a page-reload like it does with the cart (doing away with the PUT command). Then anyone with ModSec enabled won't have to hide the coupon code box on checkout or deal with the "Request does not match any route" error (or in worse case end up modifying their ModSec rules).

I believe this is primarily a problem with store owners/webmasters with ModSecurity enabled.

Hope this helps anyone still running into this problem.

**Comment by davideleonelli99** [comment]
Hi everyone, I have the same issue on Magento 2.4.5-p4.
Did anyone find a patch for this?

Thank you.
