### ISSUE TITLE
PayPal Express - Changed Billing Address Doesn't Take

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#10541]
### Preconditions
1. Magento 2.1.7
2. PHP 7 / Linux
3. PayPal Express as checkout method, 

### Steps to reproduce
If customer doesn't have PayPal account:
1. Add item to cart and checkout. Fill out shipping address, choose PayPal checkout,
2. Choose credit card / debit card option in PayPal popup.
3. Specify different addresses for both Shipping Address and Billing Address

If customer has a PayPal account:
1. Add item to cart and checkout. Fill out shipping address, proceed to payment method, uncheck same billing/shipping address. Specify unique billing address. 
2. Choose PayPal option to initiate popup, login as PayPal user.

### Expected result
If customer doesn't have PayPal account:
Process order with unique shipping address and unique billing address.
If customer has a PayPal account:
Process order with unique shipping address and unique billing address.

### Actual result
Sales order always ends up with billing address being the same as shipping address. It seems to 'throwout' the user-specified billing address both if not a PayPal user (and user specifies it in PayPal popup) or if PayPal user, specifies unique billing address (on storefront). 

It seems like others might have reported this but I wanted to be more specific and specify both situations for both PayPal users and non-PayPal users who checkout as guest.  We didn't seem to have this issue on our Magento 1.9 store.

**Comment by YevSent** [comment]
Hi, @heyepic. Please, clarify some points:

> uncheck same billing/shipping address

Did you change `Display Billing Address On` option to `Payment Page` (by default it `Payment Method`) in `Checkout` settings? You can't choose another billing address for PayPal Express Checkout if billing address displayed by `Payment Method` and it will be always the same as shipping address even if you choose another address on PayPal side.

I've checked described flow in different variations: Express Checkout with In-Context and without, checkout from mini-cart and payment step, displaying billing address on payment method and payment page. The billing address is always different (I chose it on Magento and PayPal side).
The only exception if `Display Billing Address On` -> `Payment Method` (default value) and the checkout from payment step, the billing address will the same as shipping but this is expected behavior and the changes on PayPal side do not override it.

**Comment by heyepic** [comment]
It seems like just flipping to Payment Page was the fix - we tried a few things in succession with this and things were breaking. Thanks for the quick solution.

**Comment by silversil** [comment]
I have noticed same issue, but it isn't fixed just selecting "Payment Page". :(

**Comment by cproach** [comment]
Has there been any progress made with this bug?
