### ISSUE TITLE
Adress Book - Default billing address overrides default shipping address.

### ISSUE THREAD

**Issue by johnny-longneck** [magento/magento2#10556]
### Preconditions

1. Magento 2.1.8
2. Php 7

### Steps to reproduce
1. Create Account
2. Go to Address Book
3. Enter address and save
4. Edit default billing address and save

### Expected result
1. Default billing address gets saved
2. Default shipping address will remain the same

### Actual result

1. Shipping address gets overridden, too - and vice versa

A customer wrote us this after trying to change the address for 20 minutes he ordered via email then.

![shippingbillingdisaster](https://user-images.githubusercontent.com/25068173/29370711-87346a54-82a6-11e7-921e-2f4871202d5e.png)

**Comment by orlangur** [comment]
On step 4 did you uncheck the "Use as my default shipping address" checkbox?

**Comment by Joker2099** [comment]
Same issue here on M 2.1.4. A customer just called in to order over the phone because he couldn't change the billing address without changing the shipping address. 

@orlangur Page doesn't have a checkbox at all. It's a possibility that because it's missing it's being checked automatically and therefore, addresses override themselves.

I will dig into it today. Please post a solution if you have one.
Thank you

**Comment by orlangur** [comment]
Just checked on http://magento2-demo.nexcess.net/customer/address/edit/id/1531/ (not sure which version it runs), "Use as my default shipping address" checkbox is in place.

Do you use some custom theme with these templates overridden? Try switching to Luma for the functionality check.

**Comment by Joker2099** [comment]
@orlangur Try changing the address and see what happens. I checked the code in edit.phtml and the reason checkbox doesn't show up is because the address is already "Set as default" there is a condition 

`<?php if ($block->isDefaultBilling()): ?><div class="message info"><?php /* @escapeNotVerified */ echo __("It's a default billing address.") ?></div><?php elseif ($block->canSetAsDefaultBilling()): ?>`

So the checkbox is out of the question. And the theme I use is based on Magento/Blank with my own changes.

**Comment by Joker2099** [comment]
The only way I found it to be working "properly" is to actually have multiple addresses added to your account. Only then you will be able to switch billing & shipping to whichever address you want it to be. 

But when you try to "Change Billing Address" or "Change Shipping Address" it saves both addresses with the same info. You can definitely see it yourself at that M2 Nexcess demo.

**Comment by johnny-longneck** [comment]
I can confirm this. 

You could say it works but it is definitly not what a user expects.

**Comment by orlangur** [comment]
It clearly states "It's a default billing address." and "It's a default shipping address." when you edit it, so definitely not a bug, but a severe usability issue as to me.

Billing/shipping note should be more visible, not in the very bottom of the page, and there should be more natural way to edit billing address without touching shipping address than going to a different page and press "Add New Address".

**Comment by Joker2099** [comment]
I agree that it's not an actual bug since nothing is really broken, at the same time something has to be done about it. It confuses customers I am sure.

The simplest workaround is to put a message on the Address Book page that gives some direction.

**Comment by magento-engcom-team** [comment]
@johnny-longneck  Thank you for your submission.
The issue you described is standard functionality behavior. Only after you add second address and save it as "default billing address" or "default shipping address" - then you will be able to edit them separately.
If you want to make Feature Requests and Improvements, please submit them to the new Magento 2 Feature Requests and Improvements forum [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96))

**Comment by korostii** [comment]
> Billing/shipping note should be more visible, not in the very bottom of the page, and there should be more natural way to edit billing address without touching shipping address than going to a different page and press "Add New Address".

Well, if you show Default Billing Address and default shipping address separately with different "Change address" links on the same page, user naturally thinks they are different entities and can be edited naturally.
So the system should follow that expeced behavior or state explicitly if it's doing otherwise.
 
How about a small hint "The changes will be applied to both your default shipping address" with clickable text saying "No, keep my shipping address unshanged" at the bottom of the page? (This button should naturally place a hidden input via JS)
In that case, submitting the form would save the address as a new one and everyone will be happy.

There you go @magento-engcom-team , it's possible to fix this one. 
Please reopen the issue. 
If you don't plan to fix it touyrselves, that's fine: just add an `up for grabs` label. **But please, keep this valid issue open**.

**Comment by magento-engcom-team** [comment]
@johnny-longneck, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hi @johnny-longneck. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/24

**Comment by alexgubarev** [comment]
@magento give me 2.4-develop instance

**Comment by YekaMX** [comment]
Hi,
I'm not a developer, but i'm interested in change that behavior, can anyone try this?

https://www.youtube.com/watch?v=8_jthVC0a7s&ab_channel=RoelVandePaar

Thank you!

**Comment by Franciscof-Serfe** [comment]
Hi everyone!
I have already added this feature to this pull request: https://github.com/magento/magento2/pull/38677. 

Regards, 
Fran
