### ISSUE TITLE
Merging / Bundling JS Files Production Mode breaks Regular Expressions

### ISSUE THREAD

**Issue by ulftietze** [magento/magento2#10562]
### Preconditions

1. Magento 2.1.X (explict tested with 2.1.2, also shouldn't work with all other versions)
2. PHP 7.0.X
3. Production Mode
4. Enabled JS Bundling (Configuration > Advanced > Developer > JavaScript Settings)

### Steps to reproduce

1. Create a custom JS File which should do some Regular Expressions (e.g. Input Fields in Checkout)
2. Inside if Validation e.g. do a /^([a-zA-ZßäöüÄÖÜ\s.]{3,})+$/
3. Run php bin/magento setup:static-content:deploy

### Expected result

1. Regex should pass the following string: "Übergrößenträger"

### Actual result

1. Can't validate this string, because REGEX Validation is modified to: 
/^([a-zA-Z\u00c3\u009f\u00c3\u00a4\u00c3\u00b6\u00c3\u00bc\u00c3\u0084\u00c3\u0096\u00c3\u009c\\s.]{3,})+$/
2. This is after the json_encode of this string. Before Magento do this, here is the string that Magento creates: /^([a-zA-ZÃÃ¤Ã¶Ã¼ÃÃÃ\s.]{3,})+$/

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71647

**Comment by magento-engcom-team** [comment]
@ulftietze, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @ulftietze The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
