### ISSUE TITLE
swift and magento

### ISSUE THREAD

**Issue by J-Arji** [magento/magento2#10592]
hi
how can work agento with swift 3 for receive access token ?
thank

**Comment by denchev** [comment]
@J-Arji You have to be more specific which Swift you are talking about. 

- Swift - Apple's programming language
- Swift - The PHP micro framework
- Swift - The PHP mailing software

And then ... I don't think this is the place to get the answer for it. Maybe Stack overflow?

**Comment by orlangur** [comment]
@denchev is absolutely right.

GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

It is better to use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
