### ISSUE TITLE
Magento 2.2 RC Installation Fails -  Class Magento\Indexer\Model\ResourceModel\FrontendResource does not exist  

### ISSUE THREAD

**Issue by careys7** [magento/magento2#10602]
### Preconditions

1. CE 2.2.0-preview
2. EE 2.2.0-release-candidate
3. B2B 1.0.0-release-candidate
4. PHP Version 7.0.22

### Steps to reproduce

1. Install Magento via CLI, using the Git build process described in devdocs

### Expected result

1. Installation completes

### Actual result

1. The following error occurs:

```
[Progress: 424 / 817]
Module 'Magento_Catalog':
Installing data... 
                                                                             
  [ReflectionException]                                                      
  Class Magento\Indexer\Model\ResourceModel\FrontendResource does not exist  
                                                                             

                                                                             
  [ReflectionException]                                                      
  Class Magento\Indexer\Model\ResourceModel\FrontendResource does not exist  
```

**Comment by misha-kotov** [comment]
Thanks for reporting - internal issue is MAGETWO-71778. We'll be taking a look. If you've identified any work-arounds, let us know.

**Comment by careys7** [comment]
Thanks @misha-kotov - not aware of any workarounds (I wasn't able to find the class)

**Comment by tjwiebell** [comment]
@careys7 
I've run through installation given the preconditions, and was unable to reproduce the error you mentioned. I have a few suggestions though, because I'm not sure the branch combination you're using is a supported one, and might be one of two simple fixes I can think of.

Branch _magento/magento2/2.2.0-preview_ is a mirror of our internal _2.2-develop_ branch that gets nightly updates, and should be combined with other internal _2.2-develop_ branches for installation. Branches like _\*/\*-release-candidate_ are snapshots of these internal branches, and receive scheduled updates once a week. If you can confirm what repos you have access to, I can confirm what branches you should can use for testing RCs.

A second simple fix that I've run into several times jumping between different versions, is clearing the generated directories. I could only find this suggestion buried in an upgrade article in devdocs, but contains good suggestions that apply to git based re-installs as well. See Step 5 of this article:

http://devdocs.magento.com/guides/v2.2/comp-mgr/cli/cli-upgrade.html#ui-id-6

Let me know if either of these suggestions help, and we'll gather additional information if necessary.

**Comment by misha-kotov** [comment]
@careys7 were you able to get past this issue?

**Comment by careys7** [comment]
hi @tjwiebell / @misha-kotov thanks for your replies - sorry for the delay have been out of office. 

I have access through our partner account to the Enterprise repositories, and installed based on the branches listed here: http://devdocs.magento.com/guides/v2.2/release-notes/release-candidate/install.html#install-with-github. It should have been a fresh install as we are generating docker images for testing the RCs.

I haven't been able to reproduce any more, and think I'll go with the suggestion of composer for RC testing in the future now that's available. Thanks!
