### ISSUE TITLE
Color attribute swatches are not visible if sorting is enabled

### ISSUE THREAD

**Issue by akashkarev** [magento/magento2#10628]
Color attribute swatches are not rendered correctly for the search result page if sorting for color attribute is enabled.

### Preconditions
1. Magento EE 2.1.& with sample data is installed.
2. *Used for Sorting in Product Listing* option is enabled for the color attribute
3. *Used in Product Listing*  option is enabled for the color attribute
4. Make sure eav cache is enabled

### Steps to reproduce

1. Flush eav cache
php bin/magento cache:flush eav
2. Run reindex for attributes
php bin/magento indexer:reindex catalog_product_attribute
3. Make search by "red" keyword.
### Expected result

1. List of results is shown
2. Color attribute is presented for configurable attributes

### Actual result

1. List of results is shown
2. Color options are missing

**Comment by magento-engcom-team** [comment]
@akashkarev thank you for your bug report.
We've created internal ticket MAGETWO-75407 to track progress on the issue

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-engcom-team** [comment]
Hi @akashkarev. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1289 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - b41594122f532f6a89165a70906a5b257562c0df
 - 7369261d82e0e5ad926eaf4ccb2a8def79c4fcbb
 - dce1c66301cdddfee2dc2887f584c333d0b438b2
 - 95ed67ee4adbbd7f3f0107a52da4b9238cf44803
 - 05fcdd1a52c674ea09a34960cea71e73488fbc99
 - 8b1a2972b3f0ddd4713d00055b8d60f737a72ce4
 - 90addb731c3b253d3da4dc564ddf94ac3525bd0f
 - d5c9eef075cd5f4d9781ec7f3151a14e087d061d
 - 6ec62717c16ed96d45e670d7f867b724f0449aaa
 - f0af87edad79b295b4be87f6f92502bacfbc2764
 - 2497062749bf41c80aaebb9b6cd21eb48656f58c
 - 1f7347f47cca48238f9deabd48a0a280bc0c309f
 - 0d151c41539ba7c4d20ede20d614bb4be257903c
 - 07982fdea19074788654c6e825874cb8188ab627
 - 617da6ca08607890779ce71530a2871438c88351
 - 39ed21f83071ebffd71963e9097ecb59fd906702
 - 9aa036dec42211867f68f714a746b71395c43bb2
 - fda37ef0af75e6b28d4a0da1781b19c7a7894a97
 - 47b109180b6b5e499ba8d82e6c67888fca21ffe8
 - ef6badace5c6b046047a6e5f617020f9d4410a82
 - 809ec050986fa3ddfeec4a715ce5ace1e41a4427

The fix will be available with the upcoming patch release.
