### ISSUE TITLE
Adding BEM class in XML via attribute tag causes class to be rewritten

### ISSUE THREAD

**Issue by Zaylril** [magento/magento2#10645]
### Preconditions
1. Magento 2.2, PHP 7.1

### Steps to reproduce
1. Go to default.xml
2. Add attribute tag with a class to the body element i.e. `<attribute name="class" value="background-color--white"/>`
3. Clear cache and reload page

### Expected result
1. Class should be rendered as it is added in the XML i.e. `background-color--white`

### Actual result
1. Classes with `--` in them are replaced with a single `-` so result appears as `background-color-white`

**Comment by daniloargentiero** [comment]
Hi Zaylrill,
I found a solution. Tomorrow I'll send the pull request to Magento and then I'll post the solution here.

Please hold on!

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71933

**Comment by miguelbalparda** [comment]
This should be fixed by #10655

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98747` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Zaylril. Thank you for your report. 
The issue has been fixed in magento/magento2#21804 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [ab7aee90f55ccd02738ff98a69e6e29b083faed8](https://github.com/magento/magento2/commit/ab7aee90f55ccd02738ff98a69e6e29b083faed8)
 - [743c034291d62a4329350d637832ad0ef7b8439b](https://github.com/magento/magento2/commit/743c034291d62a4329350d637832ad0ef7b8439b)

The fix will be available with the upcoming 2.2.9 release.
