### ISSUE TITLE
Meta keywords not working

### ISSUE THREAD

**Issue by choefron** [magento/magento2#10641]
Magento 2.1

If I configure meta keywords in search engine optimization.
meta keywords must be searched on search engine.
But simply It didn't work and I couldn't find what's wrong with that.

### Expected result

1. Configured meta keyword: 라면, ramyeon, ramen
    After that if I type 라면, ramyeon, ramen on store search engine configured product must be shown.
    But it didn't.

**Comment by orlangur** [comment]
Magento catalog search should not be mixed up with external search engines (like Google, Yandex, etc). Meta keywords are for the latter ones.

Technically you can make meta keywords searchable on your site by setting `Use in Search = Yes` on `Stores > Attributes > Product > Edit Attribute > Storefront Properties` but by default it should be set to `No` due to outlined reasons.

**Comment by choefron** [comment]
@orlangur 
Now It is searched on our store search engine.
Thank you.

I've got 2 more questions as below.

1. does meta keyword support international language?
-When I type English meta keywords it searched on our website but when I type Korean keywords don't work.

-Does meta keyword support international language in different language store?
(ex:English store-Korean meta keywords, Korean store-Chinese meta keywords)

2. International Language product name isn't searched properly.
-When I search English name product(ex:"Beaumont Summit Kit") most letter of product name can be searched on search engine(ex: bea, sum, kit, beaumont, summit,...).

-But when I search Korean name product(ex:"톰포드 블랙 수트") It only can search by keyword "톰포드".
Search engine can't find product by keyword "블랙" and "수트" even in Korean store view, it weird.
I guess Magento is optimized in English, so it can't sorting other languages keywords properly.

I wish I could find answer.

**Comment by orlangur** [comment]
GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

[Magento Stack Exchange](https://magento.stackexchange.com) shall be used for questions.

**Comment by gilles6** [comment]
If meta keywords should no be used for Magento catalog search, where should we set Magento catalog search keywords ?

**Comment by orlangur** [comment]
@gvigner please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

As I mentioned, you can make builtin attributes searchable or add custom attributes and make them searchable.

**Comment by gilles6** [comment]
It doesn't work and has been reported here:
https://github.com/magento/magento2/issues/12319
