### ISSUE TITLE
Some questions about meta keyword and search engine.

### ISSUE THREAD

**Issue by choefron** [magento/magento2#10652]
I've got some questions about keyword and search engine as below.

1. **does meta keyword support international language?**
-When I type English meta keywords it searched on our website but when I type Korean meta keywords It doesn't work.
Does meta keyword support international language in different language store?
(ex:English store-Korean meta keywords, Korean store-Chinese meta keywords)

2. **International Language product name isn't searched properly.**
-When I search English name product(ex:"Beaumont Summit Kit") most letter of product name can be searched on search engine(ex: "bea" "sum" "kit" "beaumont" "summit", ...).
But when I search Korean name product(ex:"톰포드 블랙 수트") It only can search by keyword "톰포드".
Search engine can't find product by keyword "블랙" and "수트" even in Korean store view, it weird.
Is there another way to search more specifically in Korean language?

I wish I could find answer.

**Comment by orlangur** [comment]
GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

[Magento Stack Exchange](https://magento.stackexchange.com) shall be used for questions.

Magento is using MySQL full-text search (or Elasticsearch in case of EE) under the hood. I believe the most efficient approach here would be to track down the issue to this level just to understand whether a problem is on Magento side or it is a limitation/misconfiguration of engine used.
