### ISSUE TITLE
Child categories included in menu when parent category is set not to "Include in Menu" 

### ISSUE THREAD

**Issue by toddwolaver** [magento/magento2#10664]
### Description
When a subcategory is enabled and set to "Include in Menu" **AND** the parent category is disabled or set not to "Include in Menu" the subcategory is included as a top level menu item.

### Preconditions
1. Installed 2.2.0-RC21 via composer metapackage
2. Installed sample data

### Steps to reproduce
1. Add new top level category and turn off "Include in Menu". (Note, issue is the same if the parent category is disabled)
2. Add new sub category to the category added in step # 1. "Include in Menu" should be enabled by default.

### Expected result
1. Only top level categories that are enabled and set to "Include in Menu" will be rendered in the menu. 
2. Sub categories will only be included in the menu if **both** of the following are true:
    1. Category is enabled and set to include in menu
    2. Parent category is enabled and set to include in menu

### Actual result
1. The sub category added in step # 2 will be rendered as a top level category

Please note, it appears this issue was added via the following commit:
https://github.com/magento/magento2/commit/026a599577b45097f237d3acaf24bae347bd8e11#diff-b1fa678d0cae299f35fb1633bb9dcf5c

![2017-08-25_1407](https://user-images.githubusercontent.com/7132399/29728857-56e87340-899f-11e7-8056-f303a2841a86.png)

**Comment by misha-kotov** [comment]
Thanks for reporting - internal issue is MAGETWO-72112

**Comment by okorshenko** [comment]
@toddwolaver thank you for the report. The issue already fixed in 2.2.0

**Comment by jove4015** [comment]
@okorshenko - I just upgraded to version 2.2.5, which seems to be latest version of 2.2 available.  However, the bug as described is still there.  In what exact version of 2.2 is this supposed to be fixed already?

**Comment by RDXSportsCom** [comment]
Having same issue on Magento 2.2.2 Enterprise Edition.

**Comment by Mohamed-Elwan** [comment]
I'm adding `2.2.5` Enterprise to the issued versions too

**Comment by rizwan-i-khan** [comment]
Still exists in Magento 2.3.2 CE.

**Comment by ashishsjagnani** [comment]
@okorshenko This issue is still there in Magento 2.3.x. Anyone have solution for this ?

**Comment by BezV8** [comment]
Encountered this issue on 2.3.3 just now.

**Comment by engcom-Hotel** [comment]
Hello @BezV8 
I am not able to reproduce this issue on the Magento 2.3.3 & 2.4-develop.

**Testing scenario:**
1. Add new top level category and turn off "Include in Menu". (Note, issue is the same if the parent category is disabled)
![image](https://user-images.githubusercontent.com/51681618/72720716-41dd5400-3b83-11ea-8c8e-f881c6e32441.png)
2. Add new sub category to the category added in step # 1. "Include in Menu" should be enabled by default.
3. Check top menu in the frontend.

**Result:**
There is no disabled category in top menu as expected:
![image](https://user-images.githubusercontent.com/51681618/72720876-8d8ffd80-3b83-11ea-8b2e-f78f079a564c.png)

So i have close this issue as not reproducible.

Could you verify my steps?

**Comment by BezV8** [comment]
@magento give me 2.3-develop instance

**Comment by BezV8** [comment]
@engcom-Hotel I have just tried the same methodology as you on a 2.3.3 site we are developing and the subcategory does show on the menu even when the parent is set to not show.

I have yet to test on a completely vanilla instance.

![Screenshot_2020-01-20 Home page](https://user-images.githubusercontent.com/33320744/72740207-22ebbb80-3b9d-11ea-8805-9137744d5d1b.png)
![Screenshot_2020-01-20 Test (ID 5) Categories Inventory Catalog Magento Admin](https://user-images.githubusercontent.com/33320744/72740208-23845200-3b9d-11ea-89f1-aa1577696842.png)

**Comment by engcom-Hotel** [comment]
@BezV8 i tried again with enabled top category and a child category is not visible:
![image](https://user-images.githubusercontent.com/51681618/72792279-6c8de200-3c41-11ea-9d5b-1cb002420c36.png)
![image](https://user-images.githubusercontent.com/51681618/72792302-73b4f000-3c41-11ea-9110-52887aa238e0.png)

**Comment by engcom-Hotel** [comment]
@BezV8 i think it is related to your custom theme(some category display layouts is broken). Please try to find different of your theme layouts and Luma theme. Hope it helps.
So now i have to finally close this issue as not reproducible.

Thanks for collaboration!

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your request. I'm working on Magento 2.3.3-develop instance for you

**Comment by BezV8** [comment]
@engcom-Hotel I managed to track the issue down to a custom extension, removing that fixed it.

**Comment by vandijkstef** [comment]
I was able to reproduce this issue, or at least very similar, on CE-2.3.4 using the Magento blank theme and the demo data set. Basically I set 'tops' & 'bottoms' under the 'women' section to hide from menu, and it starts displaying all the children of those items. Note; Im taking out a 'middle' category, not a top-level one. Also disabled a module that *might* influence the top-menu, but no changes in behaviour seen. There are other modules running, but nothing that is, or should, directly change how the menu appears. Maybe this is intended behaviour but then it should be clear from the parent category that the children might 'leak through'.

Only solution for me right now is to manually disable all the children of the child-element, but that seems redundant and not-intentional behaviour. This way categories can show without their parent in the menu, possibly losing 'context' of said items. Would've expected the child-child items to not show as well.

Default demo data (same for 'women'):  
![Schermafbeelding 2021-02-26 om 14 24 14](https://user-images.githubusercontent.com/5433241/109306614-b3380d80-783f-11eb-96da-77a6a117fe94.png)

Disabling of 'women/tops':  
![Schermafbeelding 2021-02-26 om 14 33 56](https://user-images.githubusercontent.com/5433241/109306650-bfbc6600-783f-11eb-9042-79672ab3a12c.png)

Rendered output:  
![Schermafbeelding 2021-02-26 om 14 24 17](https://user-images.githubusercontent.com/5433241/109306688-ccd95500-783f-11eb-8262-46fd192634ff.png)

Expected:  
No children on 'women'

**Comment by ejaz-alam** [comment]
@magento give me 2.4.6-develop instance

**Comment by ejaz-alam** [comment]
@magento give me 2.4-develop instance

**Comment by ejaz-alam** [comment]
@magento give me 2.4 instance
