### ISSUE TITLE
Cannot instantiate abstract class Magento\Eav\Model\Entity\Attribute\Source\AbstractSource in var/www/html/XXXXXX/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php on line 73

### ISSUE THREAD

**Issue by dndanoff** [magento/magento2#10685]
Hello,
I am experiencing very strange exception that is persistent. The exception happens every time  I try to log in. The strange thing is that none of my colleagues has this error. It happens even after I reset all my code changes from our git repo. Also I did a setup:upgrade and cleaned all caches but exception is still there.
Do you have suggestions how I can fix it?

### Preconditions
1.Magentoto 2.1.7
2. PHP Version 7.0.7
3.Apache/2.4.7 (Ubuntu)

### Steps to reproduce
1.Log in in magento site as customer.
### Expected result
1. I am able to log in with my valid credentials

### Actual result
1. I see the exception in the title

**Comment by mzeis** [comment]
Hi,

thank your for reporting this!

As you stated that none of your colleagues could reproduce this error:

* Could you make sure that this really is a core code problem and not caused by a modification of your project?
* Do you get the same error if you use a database of one of your colleagues (and the same commit from your git repo as your colleagues)?
* Do you experience the same error with Magento 2.1.8?
* How exactly has Magento been set up in your project (Github clone, Composer, ...)? Which deploy mode are you using?

**Comment by wizziLalev** [comment]
Hi @dndanoff ,
Do you try to clean everything from var/di folder? I've experienced the same error few times already and this was the thing that return everything back on track?

**Comment by dndanoff** [comment]
Hi all,

the issue was connected to an old DB dump. I do not know what exactly was wrong in my local DB but after getting dump from latest dev environment everything worked.
So for anyone who experience such issue first clean your caches, execute setup:upgrade and if it is persistant you can try with fresh db import.
