### ISSUE TITLE
How to magento upgrade 1.9 to 2.1.7 ?

### ISSUE THREAD

**Issue by sweetycoderkube** [magento/magento2#10681]
How to magento upgrade 1.9 to 2.1.7 ?

**Comment by voleye** [comment]
@sweetycoderkube you need migration instead of upgrade, you can find guide at http://devdocs.magento.com/guides/v2.0/howdoi/migrate/migrate.html

**Comment by orlangur** [comment]
GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

[Magento Stack Exchange](https://magento.stackexchange.com) shall be used for questions.

**Comment by sweetycoderkube** [comment]
After upgrade 1.9 to 2.1.7. And when we click on edit/new product display below error.

The configuration parameter "componentType" is a required for "" component.

Can you please help me how to solve this error?

Thank in advance

**Comment by korostii** [comment]
Hi @sweetycoderkube,

Migration issues are supposed to be reported to a different repository: 
https://github.com/magento/data-migration-tool

Good luck & have a nice day!
