### ISSUE TITLE
Cannot remove configurable product from the cart on the cart page

### ISSUE THREAD

**Issue by Rich8881** [magento/magento2#10696]
Unable to remove configurable products from the cart on the cart overview page, you can however remove from the mini cart dropdown

### Preconditions
Magento 2.1.2 
Linux, Apache

### Steps to reproduce

1. Add configurable to the cart from the product page
2. Visited Cart Page

### Expected result
The product should be removable from the cart
1. 

### Actual result
The option to remove and gift section do not appear

**Comment by nmalevanec** [comment]
@Rich8881
 Unfortunately, I could not reproduce the issue as you described it. Please add more details to your description of the steps you followed when identifying this issue. Screenshots or logs would be helpful, too.

**Comment by magento-engcom-team** [comment]
@Rich8881 thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by sandervall** [comment]
The issue is still present in Magento 2.2.0.
I have 2 configurable products in my cart and 1 virtual product.
The "View and edit cart" page displays action buttons only for the virtual product.
I added a log line to \Magento\Framework\View\Element\AbstractBlock.php to the method getChildBlock before it returns $layout->getBlock($name); and the log output is:

No layout for 'checkout.cart.item.renderers_schedule_block7' with alias 'configurable '

The result is that the action buttons in <div class="actions-toolbar"> portion in vendor/magento/module-checkout/view/frontend/templates/cart/item/default.phtml will not get any content.

Screenshot is attached.
![no_actions](https://user-images.githubusercontent.com/34515754/33948535-c2dc277c-e02f-11e7-8d0b-46b89c4f70f4.jpg)
