### ISSUE TITLE
Use short echo tags in phtml templates

### ISSUE THREAD

**Issue by colinmollenhour** [magento/magento2#107]
PHP 5.4 has made the short echo tag <?= always available regardless of the short_open_tag setting so this feature is now 100% future proof and using it in templates reduces quite a bit of unnecessary typing/characters. The feature has been in PHP forever, only before 5.4 it could be disabled in php.ini.

Proposal example before:

    <dt><?php echo $this->getFoo() ?></dt><dd><?php echo $this->getBar() ?></dd>

Proposed change to:

    <dt><?= $this->getFoo() ?></dt><dd><?= $this->getBar() ?></dd>

I'd be happy to tackle this by writing a script which can do the replacement with a regex. I think it won't be hard using a lookahead to make sure the replacement is only done when there is one statement between the open and close tags (detected by semicolons).

Note, I am *not* proposing changing *all* tags to short tags, just the ones that contain a single echo statement on one line.

If you approve I will start on the script. Actually I would probably use DAMit which would make it easy for everyone to convert their code if they so desired:
http://code.google.com/p/dam-tools/source/browse/trunk/DAMit.pl

EDIT:
For users of PHP versions prior to 5.4 it should be possible to force short_open_tag to "on" via .htaccess.

    php_value short_open_tag 1

**Comment by mariuszgomse** [comment]
Hello,

Sorry that I dig out this "issue" again, but I'm curious is there any decision about it ? 

In the actual repository I can find some phtmls with `<?=`:
* app/code/Magento/Catalog/view/adminhtml/templates/product/edit/tabs.phtml
* app/code/Magento/Customer/view/adminhtml/templates/tab/addresses.phtml
* app/code/Magento/Downloadable/view/adminhtml/templates/product/edit/downloadable.phtml
* app/code/Magento/Msrp/view/base/templates/product/price/msrp.phtml
* app/code/Magento/Weee/view/adminhtml/templates/renderer/tax.phtml

As I can see most of them are used for data-mage-init. In the actual [Magento 2 Release Notes](http://devdocs.magento.com/guides/v1.0/release-notes/release-notes.html) there is information that _Magento 2 supports PHP 5.5 and 5.6_ so `<?=` is safe :)

For me `<?=` looks great, but `<?php echo` is also good :) Just wanted to know is there some **final decision** ?

**Comment by alankent** [comment]
Final word - we follow PSR-1 and it allows both so this can be re-closed. Not planning to change anything.

**Comment by maksek** [comment]
As motioned by @alankent we are supporting PSR standards. PSR-1 says "Files MUST use only <?php and <?= tags." So both are valid.
Closing the topic, if more discussion required please comment on this topic.

**Comment by davidalger** [comment]
@alankent if I take the time to update all the template files to use the short-echo tags and submit a PR, would it be something the team would consider accepting?

**Comment by sshymko** [comment]
To whoever is going to review this request:

Keep in mind that this is a CE repository. A pull request would include changes to CE files only. Somebody from the Magento team will have to work on EE files in order to complete the short tags support.

**Comment by alankent** [comment]
I think more of a question for @maksek (the Engineering team). I worry more about big picture architecture.

Good question though. Is there a reason you prefer the short form? How many other people agree? If you get a bunch of people saying "its a good thing" with not many saying "its a bad thing" it makes decisions easier. Some changes are really "for the community". It does not affect us. If such a change makes the community happy, its good.

I will however also say that it may be easier to accept (due to merge conflicts) by providing a script to make the change, rather than a mega commit doing the change (and colliding with everyone else's work). But I will leave to Max.

I will also say as we get closer to GA the internal pressure will go up, like any project. The benefits of the work need to be clearer as every engineer looking at this sort of thing is not working on something else. We still need to code review any change request, which takes real time for a mega change like this. So personally I think it would need to be pretty compelling community vote that this is important to do.

**Comment by erikhansen** [comment]
@alankent I would love to see all template code refactored to the short-echo tag syntax. In addition to saving keystrokes, it would also make it easier to scan a template and see which php tags output content vs everything else. In a quick search of the M2 codebase, I found ~21 usages of the `<?=` tag. So it seems that some developers are taking advantage of the __option__ to use the short-hand syntax, but I would love to see this documented as a standard, so that the codebase is consistent.

As an aside, it seems that the [Magento 2 coding standards](http://devdocs.magento.com/guides/v1.0/coding-standards/bk-coding-standards.html) should be more opinionated about things like this, removing underscores from protected/private methods/properties, etc.

**Comment by davidalger** [comment]
A quick review of the comment thread here reveals a dozen in support of short-echo tags and less than half that in opposition, at least a couple of the opposers being due to PHP 5.4 not being a requirement at the time (2-3 years ago).

@sshymko Good point. I could take care of that and make a PR on the EE repo too if that made a difference though. ;)

@alankent I'm curious to hear @maksek's thoughts on this. Personally I think it's a huge amount of benefit due to less syntax clutter in templates, leading to better readability and overall cleanliness.

I could provide a script to make the change. I used a few perl commands to replace everything, ran the lint checker on all the changed files to verify it didn't bust syntax and then pushed up e50d17d5b4 so I could run the test suite on travis and be sure it didn't totally screw them up. Now that it's run and I can see the result is the same as current results on the develop mainline, I feel comfortable posting the script.

Look forward to hearing others input here. I'd be happy to let your team use the script directly, happy to make the PR on the internal CE/EE repos so it'll get both without requiring effort to effect the change, or happy to just do it here and let you take the EE change internally via the script. Let's just say I'll be happy to see the change allowed/effected regardless of whether it's through a PR I submit or not. ;)

Here's what I ran to make the changes for my testing purposes…

```bash
#!/usr/bin/env bash

# using *html vs *.phtml because one .html file has a use of <?php echo in it
# the first expression converts all the single-line to a uniformly formatted
# short-echo tag format, the second updates the few existing short-echo tags
# to use the same padding applied in the first, and the third expression just
# replaces the opening tag on the few multi-line cases (where I did a visual
# check to ensure it wasn't touching things it shouldn't)

find . -type f -name '*html' -print0 | xargs -0 perl -pi -w -e 's#<\?php\s*echo\s*(.*?);?\s*\?>#<?= $1 ?>#g';
find . -type f -name '*html' -print0 | xargs -0 perl -pi -w -e 's#<\?=\s*([^\?]*?);?\s*\?>#<?= $1 ?>#g';
find . -type f -name '*html' -print0 | xargs -0 perl -pi -w -e 's#<\?php\s*echo\s*#<?= #g';

# there are actually a handful of cases in non-template files, get those too
find app/code/ -type f -name '*.php' -print0 | xargs -0 perl -pi -w -e 's#<\?php\s*echo\s*#<?= #g';

# verify we did not break syntax of phtml and php files
find . -name '*.phtml' -print0 | xargs -0 -n1 php -l | grep -v "No syntax errors";
find app/code/ -name '*.php' -print0 | xargs -0 -n1 php -l | grep -v "No syntax errors";

# revert changes made to 2 unit test files before comitting
git status -s | grep 'Test/Unit' | awk '{print $2}' | xargs git checkout
git commit -am 'Resolves #107: Replace all usages of <?php echo with <?= tags and unify padding on existing tags';
```

**Comment by jonathanhodges** [comment]
@alankent I also think moving to a consistent and shorter syntax, since PHP 5.4 is already a requirement, is a good idea.  Also to the point @erikhansen was making, I believe that providing more coding standards (specific to the Magento architecture) could help reduce poor quality modules.

**Comment by alankent** [comment]
Understood. We are following PSR standards - there are occasional debates how much further we should go over PSR, where in this case PSR allows both forms. Max I think is travelling at present - he will probably jump on this thread soon.

**Comment by davidalger** [comment]
@maksek Do you have any input on this?

**Comment by maksek** [comment]
@davidalger Sorry for long time without feedback.

Lets see how it evolves. 
PHP parses file with starting tag `<?php`, and it allows to use short tags `<?` as short to `<?php` and `<?=` as short to `<?php echo`. 
Starting PHP 5.4 short tag `<?=` is always available regardless of the `short_open_tag` ini setting. At the same time, PHP discourage to use short tag `<?` because it is available only with `short_open_tag` enabled.  Also PSR-1 does not allow to use short tag `<?`. 
Analyzing short tag usage versus full tag usage we see there are some restrictions on using short tags, but no restriction to use full tag. 
With this logic - I would keep full tag as main one, but do not restrict to use short one.
