### ISSUE TITLE
Magento 2 local storage access denied in IE-11

### ISSUE THREAD

**Issue by ganeshgnath1989** [magento/magento2#10711]
### Preconditions

1. Not able to  store any local storage value in IE 11
2. mini cart and other functionalities not working.

### Steps to reproduce

1. Load  an M2  sample site in IE 11
2. And look in the console it will say access is denied.
PFA 
![m2 access denied in ie2](https://user-images.githubusercontent.com/16254790/29869501-c3eed916-8da0-11e7-9aa1-256419f58954.png)

 **execCb: function (name, callback, args, exports) {
return callback.apply(exports, args);
},
line no 1649** 

>

**Comment by orlangur** [comment]
Looks like the problem is in your system configuration rather than a Magento bug: https://stackoverflow.com/questions/13102116/access-denied-for-localstorage-in-ie10

Some other modern sites, like Twitter, may not work as well.

Please clarify expected result how you see it. Probably, some fallback mechanism like https://mathiasbynens.be/notes/localstorage-pattern#comment-13 could be implemented in case of `localStorage` unavailability but it will cause `/customer/section/load/` calls on every page thus I doubt it's worth implementing.

**Comment by ganeshgnath1989** [comment]
Thank you  @orlangur for the reply  
I also  try the below-given urls of the themes luma and  porto also occur the same issue
http://magento2-demo.nexcess.net/
http://newsmartwave.net/magento2/porto/demo5_en
**So can we conclude the issue related to the IE 11** .
And we can't replicate the issue in "Microsoft edge".

**Comment by orlangur** [comment]
You can read a couple of links I posted. As far as I understood the problem is not "solvable" as usual bug on Magento side at all. Looks like something is wrong with a particular IE11 instance (thus I believe you will not observe such behavior on every IE11). It could be related to some rights, policies, even anti-virus software.

Please try to fix this IE11 configuration first to allow `localStorage`.

**Comment by ganeshgnath1989** [comment]
Thank You @orlangur
