### ISSUE TITLE
Magento 2 is not showing Popular Search Terms

### ISSUE THREAD

**Issue by addison74** [magento/magento2#10743]
I am using Magento 2.1.8 with sample pack. 

I did a lot of searches for "radiant" word. Now for this word:

- Number of results = 5
- Number of uses = 11
- Display in Suggested Terms = Yes

Let's visit Popular Search Terms section in Frontend (path is search/term/popular/). Magento 2 is not showing any word, it is a empty content page. Normally the word "radiant" should be listed.

**Comment by TomashKhamlai** [comment]
Thank you for your report. It looks like reproducible, but I am not sure.
Please use the issue reporting [guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the steps required to reproduce, the actual result, and the expected result.

On the Admin sidebar, tap Marketing. Then under SEO & Search, choose Search Terms.
Please, add the screenshot of this page. I could not found in documentation the minimum amount of search attempts that is needed for the expected result. I am ready to mark it as 'bug report' assuming that this functionality adds search terms from the first search attempt.

These links may help you.
http://docs.magento.com/m2/ce/user_guide/marketing/search-terms-add.html
http://docs.magento.com/m2/ce/user_guide/marketing/search-terms-popular.html

**Comment by addison74** [comment]
Here is the screenshot you asked for:

![search_terms](https://user-images.githubusercontent.com/8360474/30051923-80dcf4d8-922c-11e7-8423-c462f2489c7d.jpg)

Radiant word produces 5 results. The number of uses should qualify this word for appearing in Popular Search Terms page. Checking it in Magento 1, the same results produce the expected feature. As you may see Suggested Terms is set to yes.

Popular Search Terms page must be checked with Varnish and without for getting the right behavior after it is fixed.

**Comment by v0gler** [comment]
It's a bug in Magento 2.1.x
You can fix this issue with editing two files.
Magento/Search/Block/Term.php:
from
`94. $temp[$term->getName()] = $term;`
to
`94. $temp[$term->getData('query_text')] = $term;`

from
`95. $termKeys[] = $term->getName();`
to
`95. $termKeys[] = $term->getData('query_text');`
from
`127. $url->setQueryParam('q', $obj->getName());`
to
`127. $url->setQueryParam('q', $obj->getData('query_text'));`

Magento/Search/view/frontend/templates/term.phtml:
from
`16. escapeHtml($_term->getName()) ?>`
to
`16. escapeHtml($_term->getData('query_text')) ?>`

See also:
https://magento.stackexchange.com/questions/131693/display-the-blank-page-on-the-search-terms-page/131727


Edit: 
It seems to be fixed in dev branch: 

https://github.com/magento/magento2/commit/5b59f5c45e1f1fbeb60f10cd1dd540804b6cbe19#diff-0b8cbdbf8448cb42caa6c872bc220b35

**Comment by magento-engcom-team** [comment]
Hi @SirElectro 
It would be very helpful if you can submit pull request with the fix! Looks like you already have a solution 👍

**Comment by magento-engcom-team** [comment]
@ADDISON74, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by okorshenko** [comment]
Hi @ADDISON74 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.
