### ISSUE TITLE
Attribute repository resets sourceModel for new attributes

### ISSUE THREAD

**Issue by adi3009** [magento/magento2#10814]
When creating a new product attribute through code, product attribute repository save method resets source model to null or something else. Therefore a new attribute is created with an empty option (in case of select or multiselect input type). This happens only for new attributes not when updating exiting attributes. 

### Expected Result
It is expected that when some data is set on a model, repository should not change or reset it.

### Preconditions
Magento Version 2.1.7 CE and EE

[Product Attribute Repository](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product/Attribute/Repository.php#L163)

[Example Code](https://github.com/adi3009/attribute_repository_save)

### Steps to reproduce

- Copy Example/Catalog module into app/code directory.
- Install module 
    
      ./bin/magento module:enable "Example_Catalog"
      ./bin/magento setup:upgrade
      ./bin/magento setup:di:compile
      
- Run command to create an example product attribute
    
      ./bin/magento example:catalog:create_attribute
      
### Actual Result
- In magento admin panel you should see attribute `example_attribute_code` of input type `select` having just an empty option.

- Run the command again and you should see the attribute has options from source model.

**Comment by orlangur** [comment]
```
$attribute->setSourceModel(
                $this->productHelper->getAttributeSourceModelByInputType($attribute->getFrontendInput())
            );
```
looks perfectly valid to me as you cannot have different source models for the same `frontend_input`. Just use another `frontend_input` and map source model properly.

**Comment by adi3009** [comment]
@orlangur I've updated the example code. I think the repository should only set source model if not set already.

**Comment by orlangur** [comment]
Again:
- is Magento using different source models for the same frontend input internally?
- what is the problem in mapping your source model with frontend input properly?

**Comment by adi3009** [comment]
Yes
- Magento uses different source models for several product attributes, e.g. product status (frontend_input is select) etc.
- The problem is in [save method of repository](https://github.com/magento/magento2/blob/5973d671fae91b0cde83b43777fff34848880d82/app/code/Magento/Catalog/Model/Product/Attribute/Repository.php#L107) where it sets a source model without checking if a source model already set on attribute model data, it does this only for new attributes not when saving existing attribute.

**Comment by orlangur** [comment]
Ok, thanks for the detailed explanation, it looks like `\Magento\Catalog\Helper\Product::getAttributeInputTypes` is just a partial implementation currently.

So, you just need a regular new select/multiselect but with custom source model.

Not sure it should be treated as bug report or a feature request, so, leaving without such label for now.

**Comment by magento-engcom-team** [comment]
@adi3009 thank you for your bug report.
We've created internal ticket MAGETWO-75299 to track progress on the issue

**Comment by okorshenko** [comment]
Hi @adi3009 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by adi3009** [comment]
Hi @okorshenko, @orlangur  

Is this fixed and released, I can replicate the issue in 2.2.4

**Comment by adi3009** [comment]
can also replicate in 2.2.5

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-tomash Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97417`, `MAGETWO-97418` were created
