### ISSUE TITLE
New customers not shown on backend. Seems indexer customer_grid not re-indexing.

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#10829]
### Preconditions

1. v2.1.8
2. PHP 7.0.20

### Steps to reproduce

1. Create an account on frontend or webapi
2. Check backend customer list

### Expected result

1. Newly created customer(s) shown on customer_grid.

### Actual result

1. Customer grid not been updated. If i run bin/magento indexer:reindex customer_grid, customers comes to grid. I think it is related about scheduled customer_grid indexing. There is nothing in logs/reports.

**Comment by magento-engcom-team** [comment]
Hi @rbostan 
What indexer mode do you use for customers: `UPDATE ON SAVE` or `UPDATE BY SCHEDULE`?

**Comment by orlangur** [comment]
@rbostan please make sure cron is running background tasks properly: http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-cron.html#config-cli-cron-bkg

**Comment by cizgidekiadam** [comment]
@orlangur All crons set scheduled and all other scheduled indexes working fine. It seems to be just related about customer_grid indexer.

**Comment by magento-engcom-team** [comment]
@rbostan , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.

**Comment by cizgidekiadam** [comment]
Thanks form information.
But, we are not planning to upgrade 2.2.0 in near future.

How can we fix this for 2.1.8 ?

**Comment by jarnorai** [comment]
Seems that you have removed the is scheduled check in 2.2 and that solves the issue when saving customer from the admin. (https://github.com/magento/magento2/commit/8c465937d22043039c317e03a07a4bf760124724#diff-b825af2e6d0add2867a20213c97c9635) That does not still add the similar database trigger based support for customer grid indexing that is there for other entities. The indexing is then basically update on save and not scheduled. There still exists that customer_dummy indexer in mview.xml that does nothing and that seems to be there in all dev branches.

**Comment by avra911** [comment]
This also affects catalogrule_product index, not only customer grid

**Comment by anemitoff** [comment]
Is the takeaway that the the customer_grid index (and potentially catalogrule_product too, according to avra911) should never be "update on schedule"?  The "fix" seems like a hack and I don't really understand the why the rows wouldn't be properly indexed when the scheduled update was run?  Can anyone explain why the "fix" is "correct" rather than a hack?

**Comment by tek-moe** [comment]
I've been fighting with this issue since upgrading from 2.1.2 -> 2.1.9. Cron is running successfully with no error and is showing success on the cron_schedule table. 

I guess I have to upgrade to 2.2, which is always an issue due to plugin compatibility and other random bugs that appear when updating Magento 2.2

**Comment by steros** [comment]
It's still an issue in 2.1.11 and it is not only with customer grid but also several other indexers.

**Comment by Prasad2706** [comment]
Same issue with version magento 2.3.0

**Comment by ajay-gehlod** [comment]
@Prasad2706  - Did you find any solution for that I'm too facing the same issue. 

I tried to rename the existing customer grid table and run reindex manually. It syncs properly all customers to customer_grid but when cron run the reindexing it again start causing the same issue.

**Comment by Jimgitsit** [comment]
I am experiencing this issue as wee on 2.1.16. Other indexers seem to be working fine and if I reindex the customer_grid index manually it works fine and customer show up. It's as if the customer grid isn't invalidating and therefore is not getting reindex.

Some observations:
The cron_schedule tables shows that indexer_reindex_all_invalid is running successfully however, there seem to always be 3 of them in pending status all the time. Those 3 will finish successfully and another 3 will start.
It takes about 3 mins to reindex our customer_grid.
I have the cron schedule for the index group set to run every 1 min so I wonder if it's a timing issue.

We can not upgrade to 2.2 or 2.3 due to incompatible extensions but it sounds like it's not really fix in those versions anyway.
