### ISSUE TITLE
signing in after selecting checkout button, will not end up to checkout page!

### ISSUE THREAD

**Issue by MMaKenZi** [magento/magento2#10834]
If you open a magento store, add a product to cart, and try to checkout, and guest checkout be disabled, the login window will appear on screen, 
but if you login to your account, you will be returned to homepage

while the correct page is checkout 
because user clicked the checkout button before signing in

### Preconditions
1. Magento 2.1.8
2. PHP 7.0.22

### Steps to reproduce
1. disable guest checkout
2. open magento store
3. add product to your cart and select checkout button
4. fill the login window details
5. and you should select checkout button once again after signing in

### Expected result
after signing in, user should redirected to checkout page, as he want this before signing in

### Actual result
will be returned to homepage

**Comment by pboisvert** [comment]
@tkacheva Olena--can you consider this for backlog? I think it may make sense as a default as login at checkout is likely driven by desire to use stored address/payment info or possibly get a discount tied to customer account, but should do some research to confirm if it should configurable (to current or continue checkout).

**Comment by magento-engcom-team** [comment]
@MMaKenZi, thank you for your report.
We've created internal ticket(s) MAGETWO-80516 to track progress on the issue.

**Comment by MIstvan93** [comment]
I'm working on it #SQUАSHTOBERFEST

**Comment by MIstvan93** [comment]
I've found that in this situation there's a configuration that can be done from stores> settings > configuration >customers > customer configuration > login options > redirect customer to account dashboard after logging in needs to be set to no like this.

[http://prntscr.com/gxo0bn](http://prntscr.com/gxo0bn)

**Comment by maksek** [comment]
@MIstvan93, what do you think if the "No" value will be the default one after installation?

**Comment by MIstvan93** [comment]
@maksek I think it would be a good idea, but that's just me, but also there should be a condition made for this for in case it's set to yes, but if it's a checkout redirect login, the customer should be sent to checkout.

**Comment by maksek** [comment]
@MIstvan93  -  create PR with changing default value, and we will process it :)

**Comment by okorshenko** [comment]
Hi @MIstvan93 could you please accept the invite to join magento2 repository on the GitHub?

**Comment by okorshenko** [comment]
Hi @MIstvan93 could you please accept the invite to join magento2 repository on the GitHub?

**Comment by okorshenko** [comment]
Hi @bohemiorulo please accept the invite to join magento2 repository on the GitHub?

**Comment by bohemiorulo** [comment]
yes, I already accept it, thanks

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by okorshenko** [comment]
Hi @MMaKenZi. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1353 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 299109f1265fa15eeb3067e22c2638ff5907205e
 - 57318bf03bf6fe7f84b2956ffb5ecc1332bf41b3
 - 41cd961a217d30c4b7b051a775902c4fb40b84ea
 - 076b90398852478d93d1444f936ac483b4640a82
 - 435a6c200cd548b8765e5bc73b0458039a58645d
 - 5d174b873f8ba369d6504fb9d7ef30296816e2b1
 - a47b10dce854a2d21ead6b362b86ca3ddf595386
 - ab48cb176830ddab69fd1617cae96d76094ab167
 - 46be4c7ea59f6cfb9884f2bc5875245b1960edc6
 - eafc6f0a473547542c3ef80352dcd2be7128da87
 - 63b9e909f1173a51374d4cdfc68249baa66f0007
 - 2edfe9a30bb64f0a7e102bb335a89658b627bfad
 - ef5ddffb43a735627d09535b62fac2a41804a96a
 - 4ada797ece84c2f5eb55499e8bc3f75e0c7ef245
 - c5d9a019b0d51a51b452fd99b527e3b894874be2
 - 72e9e0732b98ea5b8f47bddc781dc47c688c3c58
 - 215180de0a3f6c4a16e02205732bfe8670293ad2
 - 685d50625b68dbb960988a6bfbbfc14455a6cb9e

The fix will be available with the upcoming 2.3.0 release.
