### ISSUE TITLE
Problem with uninstall sample data in magento 2.1.3

### ISSUE THREAD

**Issue by mataheri** [magento/magento2#10832]
I tried to remove sample data by this command:

`bin/magento sampledata:remove`

But I received These errors in terminal:
`Removal failed, reverting ./composer.json to its original content.

    `[Composer\Downloader\TransportException]`

    `The 'https://repo.magento.com/packages.json' URL required authentication. You must be using the interactive console to authenticate`

**Comment by orlangur** [comment]
See http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-sample-data-composer.html#authentication-error. Error message is quite clear by itself.

GitHub is intended for bug reports and other issues observed in vanilla Magento 2 Community Edition. Issues should conform to [issue template](https://github.com/magento/magento2/blob/develop/ISSUE_TEMPLATE.md) so that anyone can reproduce problem and not guessing anything.

[Magento Stack Exchange](https://magento.stackexchange.com) shall be used for questions.
