### ISSUE TITLE
Google Analytics Affiliation Property Set Breaks Analytics and Adword Reports

### ISSUE THREAD

**Issue by benhath** [magento/magento2#10857]
### Preconditions

Magento 2.1
Core analytics module.

### Steps to reproduce
Enable google analytics, enable e-commerce tracking in analytics and submit a transaction.

### Expected result
Transaction appears in google analytics and can be filtered by source/medium. The source should not show as an affiliation.

### Actual result
The affiliation property in Google Analytics purchase tracking code is set to the store name.
This causes all conversions/transactions to be recorded as an internal affiliation.
This overwrites the source/medium data for each transaction.
Making it impossible to determine where the sale has originated from (Facebook, CPC, direct, organic etc).
When the analytics account is linked with adwords, no conversions are passed through as affiliations are ignored. 

### How to fix
The affiliation field is not required by google docs. By removing this property the conversions are tracked correctly.

`$result[] = sprintf(
                "ga('ec:setAction', 'purchase', {
                    'id': '%s',
                    'affiliation': '%s',
                    'revenue': '%s',
                    'tax': '%s',
                    'shipping': '%s'
                });",
                $order->getIncrementId(),
                $this->escapeJsQuote($this->_storeManager->getStore()->getFrontendName()),
                $order->getBaseGrandTotal(),
                $order->getBaseTaxAmount(),
                $order->getBaseShippingAmount()
            );
`

**Comment by orlangur** [comment]
> How to fix

It's better to propose a PR instead.

**Comment by benhath** [comment]
I don't know how to do this.

**Comment by orlangur** [comment]
Ok, no problem, somebody familiar with Magento code from Community or Core Team may take care of it.

Just FYI, for simple changes it can be done even via Web UI if there is no `git` and other tools installed locally.

First some "grep": https://github.com/magento/magento2/search?utf8=✓&q=affiliation&type=

Then
https://github.com/magento/magento2/blob/develop/app/code/Magento/GoogleAnalytics/Block/Ga.php#L143
https://github.com/magento/magento2/blob/develop/app/code/Magento/GoogleAnalytics/Block/Ga.php#L247
could be changed and PR proposed.

**Comment by magento-engcom-team** [comment]
@benhath, thank you for your report.
We've created internal ticket(s) MAGETWO-81815 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@benhath, thank you for your report.
We've created internal ticket(s) MAGETWO-81815 to track progress on the issue.

**Comment by engcom-Charlie** [comment]
Hello @benhath 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
