### ISSUE TITLE
Shipping address get deselected after knockout-js init with only 1 shipping address on checkout

### ISSUE THREAD

**Issue by MathijsDelva** [magento/magento2#10865]
### Preconditions
Magento 2.1.5

### Steps to reproduce
1. Make sure you only have 1 shipping address linked to your account
2. Go to checkout after adding a product to basket.

### Expected result
The (sole) shipping address will be selected

### Actual result
The (sole) shipping address gets selected on load, but only to deselect after knockout-js init (after a mere second). After this automatic deselect, you can select the shipping address again and continue your flow and everything works.

**Comment by mattgreenfield** [comment]
I'm having this same issue. It also happens when I have more than one address, one gets selected and then unselected.
It appears that the `isSelected` selected function runs on every address twice. Once running correctly and the second time always returning false. Something to do with it looking for a new address? as `shippingAddress.getKey()` always returns `new-customer-address` on the second time around.
See https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/web/js/view/shipping-address/address-renderer/default.js#L28

**Comment by mattgreenfield** [comment]
I think this issue is kind of related as fixing one would make the other less of an issue - https://github.com/magento/magento2/issues/6488

**Comment by magento-engcom-team** [comment]
@MathijsDelva, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by chrishister01** [comment]
@MathijsDelva @mattgreenfield 

I know this issue has been closed for quite a while now, but I am actually experiencing a very similar issue. Just like you reported, each time I attempt to checkout, I can briefly see the selected shipping address (for less than a second), then immediately, nothing is selected. If I select something manually, it works, but on refresh, the same thing happens.

Were you guys ever able to resolve this? I could really use some help as I've been dealing with this issue for over a week now and, for obvious reasons, my boss is pretty upset. I feel like I've looked everywhere (Magento forums, Youtube videos, threads like these, Magento's stack overflow, etc.) but can't seem to find any answers. I don't mean to dig up old news, but I really need help. Please help if you can!!

Thanks!!

**Comment by mattgreenfield** [comment]
Sorry Chris, I've long left the Magento world.
Could there be a last ditch hack running some JS after page load to
re-select it?

**Comment by chrishister01** [comment]
Yes, that could be an option. I was hoping someone got to the bottom of this but after all my research, my hopes weren't high. Would you happen to have any further documentation regarding that specific side of the Magento system? Unfortunately everywhere I've looked has been either outdated or unrelated.

Any help at this point would be much appreciated!!

Thanks!

**Comment by jorgehs91** [comment]
Same problem here @chrishister01 .

Any hint of how can we bypass this problem?

**Comment by chrishister01** [comment]
It turned out we were running into a bug within the system. After applying a later patch, everything started working as expected. I can't recall which part of the system needed this patch, but it had something to do with the checkout functionality.
--
Chris HisterSenior Web Developer, Austin TX773.620.0387 

    On Thursday, March 7, 2019, 9:06:09 AM CST, Jorge Henrique <notifications@github.com> wrote:  
 
 
Same problem here @chrishister01 .

Any hint of how can we bypass this problem?
