### ISSUE TITLE
Unable to programmatically import tier prices in 2.2.  Worked in 2.1.8

### ISSUE THREAD

**Issue by cannycookie** [magento/magento2#10884]
### Preconditions

1. Magento 2.2.0RC23
2. PHP 7.0.21

### Steps to reproduce

1. Loop through a list of SKU's and tier prices in a shell script
2. run: 
`$this->tierPriceManagement->add($product->getSku(), 'all', $row['price'], $row['min_qty']);`

### Expected result

1. Tier price should be created

### Actual result

1.  [Exception]
  Warning: Invalid argument supplied for foreach() in /http/vendor/magento/module-catalog/Model/Product/TierPriceManagement.php on line 103

In this file, line 103 is expecting an array of Tier prices but is receiving null when a product has no tier prices.

`foreach ($tierPrices as &$item) {`

Workaround created to check for null:-

` if($tierPrices){`
`           foreach ($tierPrices as &$item) {`

**Comment by orlangur** [comment]
`\Magento\Catalog\Model\Product\TierPriceManagement` is not marked with `@api`and corresponding interface https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Api/ProductTierPriceManagementInterface.php#L11 is deprecated.

Do you observe any issues using an appropriate https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Api/ScopedProductTierPriceManagementInterface.php#L25 interface?

**Comment by cannycookie** [comment]
Ah I'm not using the API files, so instead of injecting:- `Magento\Catalog\Model\Product\TierPriceManagement`

I should be using:-
`Magento\Catalog\Api\ProductTierPriceManagementInterface`

Can try that, but just to let you know that this function was working previously.  I think this function:-
` $tierPrices = $product->getData('tier_price');` is returning null rather than an empty array.

**Comment by orlangur** [comment]
Yeah, I understand that the fix could be something like

```
$tierPrices = $product->getData('tier_price') ?: [];
```

However, you shouldn't use deprecated functionality in the first place.

> Ah I'm not using the API files, so instead of injecting: `Magento\Catalog\Model\Product\TierPriceManagement`

You should not rely on a particular implementation whenever possible, just use interfaces.

Please upgrade your custom script using a proper https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Api/ScopedProductTierPriceManagementInterface.php#L25 interface and let us know if you meet any bugs.

> Can try that, but just to let you know that this function was working previously. I think this function:-
`$tierPrices = $product->getData('tier_price');` is returning null rather than an empty array.

That's exactly why one shouldn't rely on details of internal implementation. There is no guarantee `$product->getData('tier_price')` behavior will be retained in future versions while everything will work fine if you rely on `@api` marked interfaces/classes only.

**Comment by cannycookie** [comment]
OK Thanks.  Still trying to find my way in Mage2 understanding as best I can.

**Comment by arnoutvreugdenhil** [comment]
ScopedTierPriceManagement runs exactly the same code from TierPriceManagement with exactly the same problem, but not for all products, strangely enough. 
Seen in Magento 2.3.1.

`Warning: Invalid argument supplied for foreach() in vendor/magento/module-catalog/Model/Product/TierPriceManagement.php on line 186`
