### ISSUE TITLE
Downloadable products downloadproblem

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#10909]
### Preconditions

1. M2 2.1.9
2. PHP 7.0.22

### Steps to reproduce

1. Login as client to the downloadable products
2. select the downloadlink
3. the downloadlink starts as stream in browser with right click you could download it

### Expected result

1. the download should permanently be downloaded no streaming

### Actual result

1. [Screenshot, logs]

**Comment by oleg-onufer** [comment]
Hi @Olek89.
Thanks for reporting this issue.
Internal ticket MAGETWO-75431 was created.

**Comment by Zifius** [comment]
This is controlled by an option in Configuration -> Catalog -> Catalog -> Downloadable Product Options, Use Content-Disposition which is set to "inline" by default. Perhaps it should be changed to "attachment"

**Comment by oleg-onufer** [comment]
Hi @Zifius.
Yes you're right!
This problem is solved in:
Configuration -> Catalog -> Catalog -> Downloadable Product Options, Use Content-Disposition set to "attachment".

**Comment by magento-engcom-team** [comment]
@Olek89, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by KarlDeux** [comment]
Shouldn't this be closed / archived?

**Comment by Olek89** [comment]
Yes thanx can be closed.

**Comment by ishakhsuvarov** [comment]
Closing per comments above.
Thank you for collaboration!
