### ISSUE TITLE
composer update does not update htdocs/lib folder

### ISSUE THREAD

**Issue by steros** [magento/magento2#10972]
### Preconditions
1. have Magento 2.1.5 (or below 2.1.9 I suppose installed)
2. change composer.json to require 2.1.9

### Steps to reproduce
1. delete the vendor folder 
2. leave all other folders as is
3. run composer update

### Expected result
1. Magento is updated to 2.1.9 

### Actual result
1. Magento is updated to 2.1.9
2. almost everything runs fine
3. except in backend I get a 404 error about moment-timezone-with-data.js

The problem is that the lib folder in htdocs was not updated properly or at all.
I replaced the lib folder entirely with the lib folder from the zip download from the website.
Now the 404 error is gone.

I'm not sure this is a Magento problem at all or local setup or composer problem though.

**Comment by orlangur** [comment]
Did you perform all the necessary steps from http://devdocs.magento.com/guides/v2.1/comp-mgr/cli/cli-upgrade.html#upgrade-cli-upgr? Static files should have been updated on step 6.

Looks like the new file https://github.com/magento/magento2/commits/2.1/lib/web/moment-timezone-with-data.js wasn't materialized to `pub/static` in your case.

**Comment by steros** [comment]
Yes of course and the problem was that in the end it wasn't materialized. But that was due to the fact that `lib` wasn't updated properly so the file wasn't in the source place in the first place.
So it couldn't be copied to `pub/static` then.

**Comment by hostep** [comment]
@steros: can you reproduce the issue without the following step?
> 1. delete the vendor folder

If you leave the `vendor` directory in place, and then perform the update, it might work correctly.

It feels like it has something to do with https://github.com/magento/magento-composer-installer, which is being used to copy files from inside the vendor directory, to outside the vendor directory using the `extra` => `map` config of the `composer.json` files of the modules, see the file: `vendor/magento/magento2-base/composer.json` (I can't seem to find this file in github), it contains:
```json
    ...
    "extra": {
        "map": [
            [
                "lib/web/moment-timezone-with-data.js",
                "lib/web/moment-timezone-with-data.js"
            ]
        ]
    }
    ....
```

I have the suspicion that if you remove the `vendor` directory, it might fail to copy these files, but I might be wrong.

**Comment by steros** [comment]
I see. Unfortunately not deleting vendor isn't possible.
I'm running a Ubuntu Vagrant on MacOSX with NFS. Apple changed some rights stuff and thus often deleting files fails. I did not manage to fix the rights issues, if it is even possible.
I can't update magento via composer without deleting the folder :/

**Comment by orlangur** [comment]
Something like https://github.com/paliarush/magento2-vagrant-for-developers/issues/140#issuecomment-313196408 could do the trick, at least for me it worked with similar problem. For myself after suffering with vagrant/docker I switched to https://github.com/weprovide/valet-plus and never regret it.

@hostep, thanks for pointing out the crux, I read the report as "remove `vendor` folder contents", like it occur usually. Closing as `vendor` folder removal is not a valid scenario, problems with MacOS should be solved on appropriate level, some `rsync` could be involved in the worst case.

**Comment by BrocksiNet** [comment]
After that problem that the file is missing under pub/static i had a javascript error occuring in the backend:`Uncaught TypeError: utils.convertToMomentFormat is not a function`

This is happening because the file under _src/pub/static/adminhtml/Magento/backend/en_US/mage/utils/misc.js_ was not updated or the same like _src/vendor/magento/magento2-base/lib/web/mage/utils/misc.js_ (more less all the files under mage/utils where not updated during composer update, more things were broken in the backend).

I just leave this comment here for others to help.

**Comment by steros** [comment]
Yeah you need to update all folders except vendor manually.

**Comment by Ambertvu** [comment]
To be honest, as webbuilder, i'd excpect composer to update everything that is needed. Including the JS files.

I currently have the same issue as @bjoern-flagbit mentioned on his last (oct 4) post. 

There is a misc.js file in vendor/magento/magento2-base/lib/web/mage/utils/misc.js

I've compared this file with one from a full zip, and there seems to be a file difference.

I replaced the misc.js file with the one from the zip, and the back-end is working again.

So Composer does not update these files it seems.

**Comment by orlangur** [comment]
@Rann1 files are materialized dynamically, https://github.com/magento/magento2/tree/2.2-develop/pub/static is empty as well.

**Comment by Ambertvu** [comment]
@orlangur as to be expected. Think I typed it a bit wrong in my post, I've edited it a bit to make it more clear.

As an average user I'd expect composer to update all the files, it does so with many plugins aswell but not with those folders/files ?

**Comment by orlangur** [comment]
@Rann1 it is not a responsibility of Composer to update `pub/static`. In proper Magento setup, with appropriate directory/files permissions, contents of `pub/static` are updated automatically.

**Comment by hostep** [comment]
@orlangur: @Rann1 isn't talking about `pub/static` (well not in his _edited_ post at least).

@Rann1: can you try to find a simple way to reproduce this problem? First install a certain version of Magento using composer, then upgrade it to a newer version and see if certain files in `lib/` aren't getting updated to the correct version?
Note that composer should copy certain files from `vendor/magento/magento2-base/lib/` to `lib/` using the composer plugin I mentioned above.

The fact that multiple people start reporting issues like this has me worried a bit, since this should always work perfect during upgrades and if there is in fact a bug in here, then it should get a very high priority to be fixed. The bug might get triggered if you remove your `vendor/` directory before performing an update, but you should try to avoid that (you can remove `vendor/` before running `composer install`, but not before `composer update` please).

**Comment by orlangur** [comment]
@hostep hm, true :) Generally contents of zip and specific path in `vendor/magento/magento2-base/...` should not differ.

`composer clear-cache` and `rm -rf vendor/*` + `composer install` should help if somehow packages were corrupted on your env.

**Comment by alxgnz** [comment]
Make sure misc.js is the same in the lib vendor and pub folders are the same. If you have minify js enabled in store config, it could be affecting these files
