### ISSUE TITLE
Magento 2.2-rc3.0 and problem with including path for lib/internal directory. 

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#10985]
### Preconditions
1. Magento 2.2-rc3.0

### Steps to reproduce
1. Upload any library  to the lib/internal directory,  in our case - GeoIP and MaxMind libraries.
2. Use the same libraries as you are can currently using in magento 2.1.x:
```
use GeoIp2\Database\Reader as GeoIP2Reader;
...
$reader = new GeoIP2Reader($dbPath, ['en']);
```

### Expected result
1. $reader is the object of the Reader class

### Actual result
1. Error: GeoIp2\Database\Reader class not found

It seems that for magento 2.2 in Magento\Framework\Autoload\Populator::populateMappings()
the following adding include path for lib/internal was removed. 
We use the lib/internal directory for libraries in our “ready-to-paste” package version, and now we are confused.
Is it bug? Or we currently need to add libraries to the new “generated” directory (it seems improbable).

**Comment by orlangur** [comment]
This is intentional change in https://github.com/magento/magento2/commit/0b659d2613eeb53360c73108f7d71b808d4bbf28#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L220.

The best way to solve is to install all libraries using Composer and do not rely on `include_path` just like Magento does. If it is not possible, you can simply restore this config in your custom `composer.json`.
