### ISSUE TITLE
Magento CE 2.1.9 SVG Logo Upload

### ISSUE THREAD

**Issue by ramindas** [magento/magento2#10999]
Cannot upload .SVG image as Magento 2.1.9 Logo

Did a fresh installation of Magento CE 2.1.9 tried to upload .SVG file as logo image and it says "Attention - We don't recognize or support this file extension type"   
Magento 2.1.9 PHP 7.0.23 MySQL 5.6.37

Content > Configuration > Edit > Header > Logo Iamge

 Expected result
Need to upload .SVG as logo image

Actual result
![image](https://user-images.githubusercontent.com/22808209/30741759-c698d048-9fb3-11e7-932a-ddd03210ef2d.png)

![image](https://user-images.githubusercontent.com/22808209/30741777-e2499ba6-9fb3-11e7-85fb-b92e143b14a9.png)

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

Here is an example of such customization: https://magento.stackexchange.com/a/186976/40869

**Comment by ramindas** [comment]
Hi,

Added to the XML but is is not working. CE 2.1.8 allowing to upload and extension was there.



Thanks

**Comment by ramindas** [comment]
<----<item name="svg" xsi:type="number">1</item>---->>>

**Comment by orlangur** [comment]
You are right, `svg` was intentionally removed due to security reasons: https://magento.com/security/patches/magento-2016-and-219-security-update `APPSEC-1673: Stored xss using svg images in Favicon`.

You can get the idea how to enable it back in your custom module by searching "svg" in https://github.com/magento/magento2/compare/2.1.8...2.1.9.

Still, such question falls out this GitHub which is intended for bug reports.

**Comment by ramindas** [comment]
Hi,

Thanks for your reply I'm talking about Logo image cannot upload .SVG sa a logo too..

Thanks & Regards,

**Comment by orlangur** [comment]
From changeset it looks like `svg` was completely disallowed as same vector attack could be possible with logo and any other image.

**Comment by ramindas** [comment]
Thanks for your Reply
