### ISSUE TITLE
92 usages of expectException() with ignored $message parameter

### ISSUE THREAD

**Issue by schmengler** [magento/magento2#11059]
It seems like during the transition to PHPUnit 6, `setExpectedException($class, $message)`  has been bulk replaced by `expectExcpeption($class, $message)`

But the new `expectException()` method only takes one parameter, namely the exception class. To check the message as well, a second method is needed: `expectExceptionMessage()`

### Preconditions
1. Magento 2.2

### Steps to reproduce
1. Change an exception message that should be covered by a test

### Expected result

1. The test should fail

### Actual result

3. The test passes

**Comment by magento-engcom-team** [comment]
@schmengler, thank you for your report.
We've created internal ticket(s) MAGETWO-80128 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @schmengler 
thank you for report and fix

**Comment by magento-engcom-team** [comment]
Hi @schmengler. Thank you for your report. 
The issue has been fixed in magento/magento2#14621 by @mastiuhin-olexandr in 2.3-develop branch
Related commit(s):
 - [948e5fad1b36c92ab78e2762efbc1781fcf7f66a](https://github.com/magento/magento2/commit/948e5fad1b36c92ab78e2762efbc1781fcf7f66a)
 - [c5573606d5441e6cd0f576926dd0d755583ebcac](https://github.com/magento/magento2/commit/c5573606d5441e6cd0f576926dd0d755583ebcac)
 - [353c04cbdc91cf539d851fff8b9b0d5d76d6bf65](https://github.com/magento/magento2/commit/353c04cbdc91cf539d851fff8b9b0d5d76d6bf65)
 - [5d6600efb1454d2cfc6fd75f5cab87f08525b854](https://github.com/magento/magento2/commit/5d6600efb1454d2cfc6fd75f5cab87f08525b854)
 - [0d912e66f1fdf40c68e7946c580c3579616fedcd](https://github.com/magento/magento2/commit/0d912e66f1fdf40c68e7946c580c3579616fedcd)
 - [a205337984b91e6a7940b832a40a4e5f623a8c67](https://github.com/magento/magento2/commit/a205337984b91e6a7940b832a40a4e5f623a8c67)
 - [87b3b588b6189d72899cbc93bb0a90d162f96e64](https://github.com/magento/magento2/commit/87b3b588b6189d72899cbc93bb0a90d162f96e64)
 - [4955faeae560bc6d8a3d888910b71997587029f6](https://github.com/magento/magento2/commit/4955faeae560bc6d8a3d888910b71997587029f6)
 - [28cddb9a48ec1fbfae493778eee021a225ef8c87](https://github.com/magento/magento2/commit/28cddb9a48ec1fbfae493778eee021a225ef8c87)
 - [7893cd65d13735360b938175dced0418eb254769](https://github.com/magento/magento2/commit/7893cd65d13735360b938175dced0418eb254769)

The fix will be available with the upcoming 2.3.0 release.
