### ISSUE TITLE
Segmentation fault after successful clone

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#11106]
### Preconditions

1. Apache/2.4.27 (Win32) OpenSSL/1.0.2l
2. MySQL 5.0.12-dev - 20150407
3. PHP 7.1.8
4. XAMPP for Windows 7.1.8
5. Git Bash for Windows (Git Portable 2.12.2)
6. Windows 10 Pro 64-bit (latest build)

### Steps to reproduce

1. `git clone git@github.com:magento/magento2.git`
2. `git status`

### Expected result

1. It should return the git status.

### Actual result

1. It returned "Segmentation fault" error.
2. It dumps an index.lock file in `.git` directory, which prevents `git pull`.

**Comment by orlangur** [comment]
This is clearly not Magento issue. Magento does not change `git` installation in any way as far as I know.

Just remove `index.lock` and try one more time. It is safe operation. If it does not work, try upgrading `git` or googling for solution for your particular environment.

Note that installing under Windows is not a good idea at all since it is not supported (see http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html). There are known issues related to XML and directory separators.
