### ISSUE TITLE
Magento 2.2 Upgrade  PHP Version Issue 

### ISSUE THREAD

**Issue by vishalpatel14** [magento/magento2#11108]
### Preconditions

1. Magento 2.2
2. Php 7.0.10
3. Appache 2.4.23
4. Wampserver 3.0.6
5. MySQL 5.7.14

### Steps to reproduce

1. composer require magento/product-community-edition 2.2 --no-update
2. composer update

### Expected result

1.  Upgrade Process should continue.

### Actual result

1. 
![version](https://user-images.githubusercontent.com/16519746/30951070-8e3dc9bc-a43e-11e7-83ff-52cdcb5b5502.jpg)

**Comment by FinBoWa** [comment]
@vishalpatel14 not a magento issue but your environments. 

The cli PHP under windows is 5.6  but Wampserver is running php 7 .. Run composer update with 
`--ignore-platform-reqs` or run composer with the right php in the cli also.

**Comment by vishalpatel14** [comment]
@FinBoWa 

Thank you for the quick support. Issue was my CLI version and its resolved now. You can close the ticket,

**Comment by vishalpatel14** [comment]
After completion of update still its showing same version 2.1.9 not the 2.2.0. Please have a look.

**Comment by magento-engcom-team** [comment]
@vishalpatel14 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
Your problem seems to be related to the platform you are using.

**Comment by vishalpatel14** [comment]
After Solving my environment problem this new error have came. Please have a look.

![error](https://user-images.githubusercontent.com/16519746/30955810-9a29d07c-a452-11e7-9946-4bd58c1f334c.jpg)
