### ISSUE TITLE
Magento 2.2.0 Publication possible issue

### ISSUE THREAD

**Issue by therool** [magento/magento2#11111]
This has nothing to do with code vise but is there any specific reason why the version for the ["magento/framework" package was set from "100.2.0-dev" to "101.0.0" instead of "100.2.0"](https://github.com/magento/magento2/commit/07465f8ce879ff0bd0ba72a662c9e2473e49afe4#commitcomment-24620019)?

This kinda breaks some of third party extensions which added support to magento 2.2.0 by adding and expecting that the "magento/framework" package for magento 2.2.0 would be version "100.2.0" as now I will have to somehow manually update these packages or wait for them to do it.

Also is this expected for ["magento/framework" package for magento 2.3 version](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/composer.json#L5)?

**Comment by orlangur** [comment]
Please check http://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/dependencies.html.

> This kinda breaks some of third party extensions

No, it allows to NOT break third-party extensions. They needs to be thoroughly tested and only after that constraint may be expanded to indicate both `100.x` and `101.x` versions are supported. 

> Also is this expected for "magento/framework" package for magento 2.3 version?

Nope, there is no chance `101.x` will be changed to `100.3.x` some day and this is controlled automatically. Should be fixed with first publication of `2.3rc` I believe, until then there is no need to use Composer anyway.
