### ISSUE TITLE
Wishlist Add grouped product Error

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#11209]
**Preconditions**
Magento version 2.1.8,2.1.9 and 2.2.0.

**Steps to reproduce**

1. Add grouped product from the product list with the qty of 3. For ex. added product A to the wishlist.
2. After adding the product, once again add the same product A to the wishlist with the qty of 4.

**Expected result:**
The qty of product A should be updated to 7.

**Actual result:**
But it has been added as two separate products. product with qty 3, product with qty 4. in the wishlist items.

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We've created internal ticket(s) MAGETWO-80833 to track progress on the issue.

**Comment by sasilinux** [comment]
Still the issue is not resolved. But my previous ticket was closed. https://github.com/magento/magento2/issues/9612.

Without solving the issue, then how it was closed?

**Comment by tdgroot** [comment]
I would like to pickup this issue! For which branch should I create the PR?

**Comment by mrodespin** [comment]
I have been debugging this issue, @tdgroot if you could not fix it I can do it.

**Comment by maksek** [comment]
@tdgroot 2.2-develop first, and if successful, would be nice to forward port to 2.3-develop.

**Comment by tdgroot** [comment]
@magento-engcom-team Can this issue be unassigned?

**Comment by Krishnan369** [comment]
"I am working on this at #dmcdindia19”

**Comment by VladimirZaets** [comment]
Hi @sasilinux. Thank you for your report. 
The issue has been fixed in magento/magento2#26258 by @MaxRomanov4669 in 2.4-develop branch
Related commit(s):
 - [9a4ccb7b6129060b00faf26dbdb3a9a6aa6c4284](https://github.com/magento/magento2/commit/9a4ccb7b6129060b00faf26dbdb3a9a6aa6c4284)
 - [ec8a756f8ac32e058c48eaa848e9c5c3593e2acc](https://github.com/magento/magento2/commit/ec8a756f8ac32e058c48eaa848e9c5c3593e2acc)
 - [6d7b457abb3faae9acece068d4be21d1b69a06c8](https://github.com/magento/magento2/commit/6d7b457abb3faae9acece068d4be21d1b69a06c8)

The fix will be available with the upcoming 2.4.0 release.
