### ISSUE TITLE
Store View switcher not working on front-end and it throws an error

### ISSUE THREAD

**Issue by latypatil** [magento/magento2#11211]
If we select any store then site will go to that store and again we select another store then it throws an error because the url is wrong.

### Preconditions

1. Magento ver. 2.2.0
2. PHP 7.0.24, mysql Ver 14.14

### Steps to reproduce

1. Create different store view from admin panel and all will appear on front-end 
2. Select any store view (No error)
3. Again select another store view(error will be there)

### Expected result

1. It should show all store views without any error
Ex. http://10.16.16.141/magento2.2/?___store=aus ==>this is for one of store view
      http://10.16.16.141/magento2.2/?___store=usa ==> This should be for different store view
                                                        OR
Base url should be the same for any store ,only store will get switch!

### Actual result

1. [Screenshot, logs]
![error](https://user-images.githubusercontent.com/31685324/31170868-603dda3e-a91b-11e7-8193-022b93f6cda7.png)
 
After changing the store view second time it redirect to below url  :
http://10.16.16.141/magento2.2/?___store=aus?___store=usa

(URL is only for reference , it will not work)

**Comment by magento-engcom-team** [comment]
@latypatil, thank you for your report.
We've created internal ticket(s) MAGETWO-80840 to track progress on the issue.

**Comment by latypatil** [comment]
The issue is in /vendor/magento/module-store/Block/Switcher.php  with function getTargetStorePostData ()   where $store->getCurrentUrl(false) , Current url has been passed there and It should be $this->getUrl('stores/store/switch').

**Comment by duckchip** [comment]
this issue is a result of merge in issue [https://github.com/magento/magento2/issues/8509] which fixes cookie redirect problems with multidomains

**Comment by thiagolima-bm** [comment]
Hey @okorshenko PR #11337

**Comment by TomashKhamlai** [comment]
@latypatil, I think that this issue is similar to issue #10908? Do you have logs in var/logs/exception.log?

**Comment by okorshenko** [comment]
the issue has been fixed and delivered to 2.2-develop branch. WIll be available with 2.2.2 release

**Comment by davidroberto** [comment]
@latypatil, i had the same problem and was able to fix it with this small fix.

I know it's not perfect and that i should overwrite the core module in a custom plugin, but anyway i'll not need this fix anymore when i'll update the code with the new release containing the official fix.

In /vendor/magento/module-store/block/switcher.php, in getTargetStorePostData method, replace 

`        return $this->_postDataHelper->getPostData(
            $store->getCurrentUrl(false),
            $data
        );`

by:

`	$currentUrl = strtok($store->getCurrentUrl(false), '?');
        return $this->_postDataHelper->getPostData(
	        $currentUrl,
            $data
        );`

**Comment by magento-engcom-team** [comment]
Hi @latypatil. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1285 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - ad6c0af7dddbe2855a336acd3fd55994851e6d26
 - 6d3d70a72f08cba36c3aef6b59eea8db40eb4071
 - 6b0c02c5fd00d7a4237c4e1fae40dc265e3e43c3
 - c8abb139f8006826989fe4231dabc21fd4a02fd0
 - c6a9b5f7b13554958b547f387637c4288eb60b0b
 - c867b81af936e01a3d8ba8baa7128de06a5b7cd5
 - 88a3ad00d3ca97da847531c86bf64055dc1d790b
 - d87e316a2d6ee55debe2e712359adba8cb70fdb2
 - c76b04c9acde117c1021270500c8ded6954f6f05
 - 5ae21099aaa19699525c798f9ac0ef10db47b311
 - 931133abf574f1db96450f11f5980ef359d32967
 - 4c927a0585f11921c5e422b7e4a15b787e6338bd
 - 060a8f9f2b08ed97b31667eb76cace1dc0e642be
 - 4da2a7d2657b0da67f8be43bffc85f04b5b7144e
 - 008ef5583892d73c04628f003a2ce3d97fe0ed72
 - d3642e88d26a9240a1a4d648d37d984a785672a9
 - d37ce089d56c230f5896d5d7e922bd928b3726e6
 - b22b232563359f9cbcbf09709e63a87be7e81446
 - 6c02a2d3a272e872d549881d91ed6d5235a33f77
 - f2ec2ea175469636acec0bf9f65f0601854f89a2

The fix will be available with the upcoming patch release.
