### ISSUE TITLE
Magento fails after upgrading from 2.1.7 to 2.2.0

### ISSUE THREAD

**Issue by laurci** [magento/magento2#11224]
### Preconditions
Before:
1. PHP 5.3
2. Magento 2.1.7
After:
1. PHP 7.1.10

### Steps to reproduce
1. replace magento version 2.1.7 to 2.2.0 in the composer.json file 
2. run composer update
3. run bin/magento setup:upgrade
4. run bin/magento setup:static-content:deploy -f
5. run bin/magento setup:di:compile

### Expected result
1. To run the bin/magento --version and to see that the upgrade was a success
2. The store to still function 

### Actual result
1. The store crashes (not including the admin)
2. The CLI states that it's indeed the version 2.2.0
SCREENSHOT:
![image](https://user-images.githubusercontent.com/5719762/31182795-87aec86e-a92d-11e7-858d-d9b46fcf1da0.png)
LOGS:
{"0":"Notice: Undefined index: src in \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Page\/Config\/Generator\/Head.php on line 125","1":"#0 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Page\/Config\/Generator\/Head.php(125): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Undefined index...', '\/home\/deals17\/p...', 125, Array)\n#1 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Page\/Config\/Generator\/Head.php(103): Magento\\Framework\\View\\Page\\Config\\Generator\\Head->processAssets(Object(Magento\\Framework\\View\\Page\\Config\\Structure))\n#2 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php(80): Magento\\Framework\\View\\Page\\Config\\Generator\\Head->process(Object(Magento\\Framework\\View\\Layout\\Reader\\Context), Object(Magento\\Framework\\View\\Layout\\Generator\\Context))\n#3 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Layout.php(344): Magento\\Framework\\View\\Layout\\GeneratorPool->process(Object(Magento\\Framework\\View\\Layout\\Reader\\Context), Object(Magento\\Framework\\View\\Layout\\Generator\\Context))\n#4 \/home\/deals17\/public_html\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(89): Magento\\Framework\\View\\Layout->generateElements()\n#5 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Layout\/Builder.php(129): Magento\\Framework\\View\\Layout\\Interceptor->generateElements()\n#6 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Page\/Builder.php(55): Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks()\n#7 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Layout\/Builder.php(65): Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks()\n#8 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Layout.php(254): Magento\\Framework\\View\\Layout\\Builder->build()\n#9 \/home\/deals17\/public_html\/vendor\/magento\/framework\/View\/Layout.php(875): Magento\\Framework\\View\\Layout->build()\n#10 \/home\/deals17\/public_html\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(414): Magento\\Framework\\View\\Layout->getBlock('page_content_he...')\n#11 \/home\/deals17\/public_html\/vendor\/magento\/module-cms\/Helper\/Page.php(171): Magento\\Framework\\View\\Layout\\Interceptor->getBlock('page_content_he...')\n#12 \/home\/deals17\/public_html\/vendor\/magento\/module-cms\/Controller\/Index\/Index.php(43): Magento\\Cms\\Helper\\Page->prepareResultPage(Object(Magento\\Cms\\Controller\\Index\\Index\\Interceptor), 'home')\n#13 \/home\/deals17\/public_html\/generated\/code\/Magento\/Cms\/Controller\/Index\/Index\/Interceptor.php(24): Magento\\Cms\\Controller\\Index\\Index->execute(NULL)\n#14 \/home\/deals17\/public_html\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->execute()\n#15 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#16 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->___callParent('dispatch', Array)\n#17 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#18 \/home\/deals17\/public_html\/generated\/code\/Magento\/Cms\/Controller\/Index\/Index\/Interceptor.php(39): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->___callPlugins('dispatch', Array, Array)\n#19 \/home\/deals17\/public_html\/vendor\/magento\/framework\/App\/FrontController.php(55): Magento\\Cms\\Controller\\Index\\Index\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#20 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#22 \/home\/deals17\/public_html\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#23 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#24 \/home\/deals17\/public_html\/app\/code\/TemplateMonster\/LayoutSwitcher\/Model\/App\/Action\/ContextPlugin.php(40): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): TemplateMonster\\LayoutSwitcher\\Model\\App\\Action\\ContextPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#26 \/home\/deals17\/public_html\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(69): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#27 \/home\/deals17\/public_html\/app\/code\/TemplateMonster\/SiteMaintenance\/Model\/PageCache\/App\/FrontController\/BuiltinPlugin.php(30): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#28 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): TemplateMonster\\SiteMaintenance\\Model\\PageCache\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#29 \/home\/deals17\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#30 \/home\/deals17\/public_html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#31 \/home\/deals17\/public_html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#32 \/home\/deals17\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#33 \/home\/deals17\/public_html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#34 {main}","url":"\/","script_name":"\/index.php"}

**Comment by andidhouse** [comment]
Upgrading from 2.1.7 to 2.2.0 is a complete disaster here. 
Once again not tested by the magento team - in no way! 

Every update costs us thousands of dollars... in a long term we will cancel magento as one of our preferred systems.

**Comment by andidhouse** [comment]
We expected to be 2.2 to have fixed major and minor bugs - instead you implement new functions and do not care about over 1000 reported bugs... this speaks for itself.

**Comment by jzahedieh** [comment]
@andidhouse it's a major upgrade so it would be expected to face some issues.

**Comment by andidhouse** [comment]
@jzahedieh no - we work with about 3 major systems here - and magento is the only one which has major problems with any updates.
I can not confirm your reply on shopware, oxid or even larger systems at all.

**Comment by laurci** [comment]
@andidhouse It's the first time i'm using Magento because i heard from friends that is "the best e-commerce platform around"... But man.. I must say that my experience 'till now was a complete disaster! I need a fix to this! And i kinda' need it fast! (tomorrow a client shows up to check progress and his store is not working anymore) If anyone can help me... i would be very glad!

**Comment by andidhouse** [comment]
@IAmTheVex i am not shure you get any help here. 
Did you try to reset the rights completely for all folders and files after update. 
I would suggest to present the 2.1.7 system you are using. We also tried the update from 2.1.7 and there are far more then 10 major issues we are facing - there is no way to use this on productive in any way at the moment.

**Comment by laurci** [comment]
@andidhouse i have drwxr-xr-x on everything... tho' now that i think.. public_html is a symlink to /var/www

**Comment by andidhouse** [comment]
Not shure if this is ok - try this (adapt it for your system):

chown -R :www-data . && find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento && chmod -R 777 var && chmod -R 777 app/etc && chmod -R 777 pub

**Comment by andidhouse** [comment]
run it in the magento2 root folder of course

**Comment by andidhouse** [comment]
maybe also clear this folders as well and compile and deploy again:

rm -rf /var/www/html/magento2/pub/static/*
rm -rf /var/www/html/magento2/var/view_preprocessed/*
rm -rf /var/www/html/magento2/var/di/*
rm -rf /var/www/html/magento2/var/cache/*
rm -rf /var/www/html/magento2/var/page_cache/*

**Comment by laurci** [comment]
already tried removing those :( and i followed the steps you provided only got me with an error "unknown group www-data"... is kinda' logic as i don't have that group :))

**Comment by andidhouse** [comment]
sry i could not help. i suggest to present an older version to your client. The problem with magento is that every new version is full of bugs - since the beginning. so never ever try to update for a live or important system.

**Comment by brandontamm** [comment]
if you tried to upgrade to 2.2, there are significant differences in codes, commands, deployment, caching, indexing, etc ... just check bin/magento and you'll see all sorts of commands are now missing.

**Comment by brandontamm** [comment]
also you can't just switch the version in composer file. there are many changes to composer file alone... ;)

**Comment by brandontamm** [comment]
I'd suggest you switch back to 2.1.7 and work in a development and staging environment until you get comfortable with how PHP development works..

**Comment by laurci** [comment]
If this is how PHP developement works, then it sucks! I dont think that an update should destroy the old stores built with old APIs! This is horrible!

**Comment by laurci** [comment]
Something more... 2.1.7 to 2.2 is not.. in theory....  a "major" update

**Comment by brandontamm** [comment]
You can’t blame “destruction” of an old store on a software update. The human destroyed the store by not isolating new code in a dev environment and fully testing with the testing framework prior to releasing to production. Maybe I stated that wrong..roll back the update until you understand how core version control and deployment workflows.. can’t blame the gun for the human that pulled the trigger in Vegas and can’t blame the code for the human that failed to use it correctly.

Brandon Tamm

**Comment by JerVoo** [comment]
@IAmTheVex actually, 2.1.7 to 2.2.0 is in fact a major update, just not in the Magento version itself. The framework has been upgrade from version 100.x.x to version 101.0.0, making this in fact a major upgrade.

On the other hand, there's a documentation about Magento's versioning strategy available, which clearly states this should be treate as a major update. See http://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/

The 2.1.x to 2.2.x update is a breaking update. I agree that this should have been communicated better, but it's truly a breaking upgrade.

**Comment by brandontamm** [comment]
And clearly you didn’t read the release notes even so how would you know what to test 😂

It is a major update - you should also brush up on your hit versioning knowledge as well.

Brandon Tamm

**Comment by andidhouse** [comment]
It is not relevant if this is a major or minor upate.

For us as a company it is just relevant how much time and stress an update is causing.
And this one, again - causes massive problems meaning massive financial effort on our side.
Everyone has to decide if this is worth it in a future perspective - we saw no clean update so far from the magento2 team. 

All in all we just updated an orocommerce system - not a single issue.

There is no new magento2 project for us as far as on every update massive effort must be taken to fix the system.

**Comment by JerVoo** [comment]
@andidhouse I must say, this is the first update since 2.1.6 I've seen that is causing issues. Updating from 2.1.6 to 2.1.7 to 2.1.8 to 2.1.9 I have had no issues. It was a simple as running a composer update, cleaning the caches and the generated files (var/cache, var/page_cache, var/generation, var/di, pub/static/frontend, pub/static/adminhtml, pub/static/_cache and pub/static/_requirejs), running setup:upgrade and redeploying static files. It took about 15 minutes, but that was about it.

Every update may or may not cause issues with anything has been built around the software, which is the case in Magento. Since the Framework has had a major update, there is a huge possibility that things may break when running the update. You should just update the code accordingly and you're ready to get back into production. This should not be more than a day's worth of work.

Magento is a very complex system and has been a very complex system every since it first came out. Therefore it's impossible to create version iterations without any breaking changes.

**Comment by brandontamm** [comment]
I agree that:
- There should have been better communication in release notes
- This is a major upgrade and will require major effort

But sometimes life on the other side of the hurdle is pretty great, right? I mean, you chose Magento because of the features and in order to keep up with technological enhancements of Magento's competitors (just like yours) you have to keep up and better yourselves right?

The point is, that Magento is attempting to secure the B2B in addition to B2C clients. As a B2B AND B2C customer, this release is groundbreaking.

Can we all just say thank you and get back to work - which is what we are all being PAID for, correct?

PS - If you're not getting paid, please reevaluate your business strategy. If you're releasing broken code to production, please reevaluate git versioning and deployment and development workflow.

**Comment by andidhouse** [comment]
@JerVoo we can not confirm smooth updates here with extensions installed. 
Maybe on a clean system it is easier but the plus of magento and magento2 where and are the extensions that are available - and you can ask companies like amasty, aheadworks or name all the other big ones... updates of magento cause problems on the row with every update.

In my mind to put 90% functions in magento2 instead of 100% would be a far better solution - and put the 10% time in bugfixing. Instead magento introduces new functions but does not fix the bugs?

In my opinion this is a bad management  - in development you first have to make shure your system is as bug free as possible before you implement new functions. But you can see this clearly here at github as well. Bugs keep rising and rising - also with every release. 

M2 is not an option any more for new projects - we just live with it on some systems at the moment.

**Comment by brandontamm** [comment]
So you're truly referencing that the extensions are breaking code? Which 9 times out of 10 is the case. 

First, you shouldn't be upgrading Magento until your extension developers have released and verified the code compatible with each new release.

Second, you should be updating the code and reintroducing each extension and full unit testing in each case.

Third, you should be developing your own code for minor functionality but you chose to pay someone else to do it, so now you're kinda at the mercy of them.

I haven't heard one positive thing on this thread, and it started from an inexperienced developer releasing what he thought was a number change into a production system...

I can say that I haven't had a major issue with an upgrade since 1.12 and I follow the practices that I preach. Magento provides full documentation, testing, and a testing/development/deployment framework. It is truly one of the most polished softwares that I have used to date.

Sounds like WooCommerce would be a better fit for some developers here..

**Comment by andidhouse** [comment]
@brandontamm - i have no idea what your comment should solve here?

In fact you see that M2 has major problems right? 
Or why in your opinion are close to 2.000 open bugreports here and hundreds of closed ones but not fixed?

Every software has bugs - that is true. But nothing comes close to the M2 release since day one and i am not talking about small bugs which do not influence the sales at an ecommerce system. We are talking about major bugs and heavy ones that block customers from buying.

To your point with the extensions:
I am not shure you have a close contact to any extension developer company? Otherwise you would maybe understand what i mean. Magestore just canceled the development of their normal extensions at all (they are doing a ERP right now instead for m2) - so guess why they are doing this?

Other extensions companies are also close to shut the doors for m2 developments... too much problems, too much effort on each update, too less users at the moment.
 
Extensions are often a problem when updating - 100% agree with you! But if official magento bugs keeps extension away from working properly like they should this is a massive problem not only for magento but for the developers and users - and here we are again at the bugs which are not solved for close to 1.5 years now.

And i think you are also 100% right that many users and companies are not happy with m2 - and therefore change for other system like orocommerce, shopify plus and some smaller ones - maybe also to woo. But think about why this is happening....

For me it is the end of the discussion here as this platform should not be used for discussions like this in our mind.

**Comment by laurci** [comment]
@brandontamm we have a very good development workflow.. no need to reevaluate that! the problem here is that we are a company that develops and deploys software for others! every minute spent on doing anything else than coding means lost time, so lost money! the fact that i had to tell my client that the job is not done today, even if this should have been, caused a lost of trust... also, the community here is the worst man! You are hitting on me for having a bug.... We are some of the best software developers in my country... thank you very much for the support! I hate magento and php... going back to nodejs

PS: Thanks @andidhouse for your support!

**Comment by orlangur** [comment]
@IAmTheVex 
> we have a very good development workflow.. 
> If this is how PHP developement works, then it sucks!

Well, I don't know why root cause of this problem is not clear after 20+ hours since it was reported.

To investigate what exactly is going on you just need to set conditional breakpoint in `\Magento\Framework\View\Page\Config\Generator\Head::processAssets` with condition `!isset($data['src'])`. Hope you have developers familiar with xdebug?

On the first glance it looks like some of your assets lack `src` attribute. I.e. normally declaration looks like

```
<head>
        <css src="Vendor_Module::css/style.css"/>
        <script src="Vendor_Module::js/tinybox.js"/>
    </head>
```

but it could be 

```
<head>
        <css/>
        <script src="Vendor_Module::js/tinybox.js"/>
    </head>
```

**Comment by orlangur** [comment]
@andidhouse, I feel like I'm banging my head against the wall but anyway...

> Upgrading from 2.1.7 to 2.2.0 is a complete disaster here.
Once again not tested by the magento team - in no way!

It is tested. Magento cannot test third-party extensions or customizations done for particular stores.

> Every update costs us thousands of dollars...

It depends on quality of extensions you use and on quality of customizations performed by your team mostly. Fragile code produces broken updates while in vanilla Magento it may work seamlessly. Are your customizations 100% covered with automated unit/integration tests?

> We expected to be 2.2 to have fixed major and minor bugs - instead you implement new functions and do not care about over 1000 reported bugs... this speaks for itself.

That is obviously not true. You may notice issue drop from 2300+ to ~1600 and still decreases.

> We also tried the update from 2.1.7 and there are far more then 10 major issues we are facing - there is no way to use this on productive in any way at the moment.

Please report exact issues you face with _separately_.

> For us as a company it is just relevant how much time and stress an update is causing.
And this one, again - causes massive problems meaning massive financial effort on our side.

I really doubt ALL problems were caused by changes in core code. Probably it would be worth investing into better developers producing less fragile code or into some education for existing developers.

> we can not confirm smooth updates here with extensions installed.
> and you can ask companies like amasty, aheadworks or name all the other big ones... updates of magento cause problems on the row with every update.

This is the question to quality of third-party extensions. All vendors must set composer constraints correctly so that any extension will not run on 2.2 until it is tested and updated if necessary by vendor.

> In my opinion this is a bad management - in development you first have to make shure your system is as bug free as possible before you implement new functions. But you can see this clearly here at github as well. Bugs keep rising and rising - also with every release.

Not true. Amount of bugs is obviously decreasing. I do agree that Magento 2.2 is still not bugfree but this is something EVERY Magento Community member may improve, by either issue reporting or even fixes provided as pull requests.

> - i have no idea what your comment should solve here?

It's the best summarization I have read for a long time 😉 

> and hundreds of closed ones but not fixed?

Please provide concrete examples of issues not fixed in `2.2.x` but closed. There is always a chance of accidental closing, I'll reopen such issues with a big pleasure for you.

> Magestore just canceled the development of their normal extensions at all (they are doing a ERP right now instead for m2) - so guess why they are doing this?

Change of priorities? Change of business strategy? Do you have an exact quote maybe which refers to inability to develop extensions in existing circumstances.

> and here we are again at the bugs which are not solved for close to 1.5 years now.

Again, please refer to concrete issues, I'll maybe even take a look into them in spare time.

Thanks for your time! I always have good time reading your comments, they are always quite expressive unlike the official press releases.

@IAmTheVex
>  I need a fix to this! And i kinda' need it fast! (tomorrow a client shows up to check progress and his store is not working anymore)

Are you saying that tried to do a major upgrade on a production system? It is not correct even for minor `2.1.x` upgrades. Please adjust your processes with http://devdocs.magento.com/guides/v2.1/config-guide/prod/prod_deploy.html, with versions 2.2+ there are even better processes elaborated http://devdocs.magento.com/guides/v2.2/config-guide/deployment/

> If this is how PHP developement works, then it sucks! I dont think that an update should destroy the old stores built with old APIs! This is horrible!
> Something more... 2.1.7 to 2.2 is not.. in theory.... a "major" update

Please check http://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/dependencies.html. As to me, current backward compatibility policy is even too strict and slows down development for those who use modern practices like automated testing, CICD loop and such. Hope it will be changed in the future.

@brandontamm,
> - There should have been better communication in release notes

What exactly is missing?

**Comment by andidhouse** [comment]
@orlangur this is exactly what the magento team is doing for close to 1.5 years - you state all is perfect and nothing is a problem and the software works fine without any major problems.

I think this is really the problem - instead of self reflecting that the m2 system was put out way to early as a stable version with 2.0.0 on the market (in fact 2.0.0 is far away from stable) you guys always keep on saying M2 is great and there are some "small issues". 

--> 1.600 Issues --> at least 1500 too much (by the way an ecommerce system with 2.3K bugreuports - never seen that in any way)

--> I really doubt ALL problems were caused by changes in core code --> Nope! not one core code change at all!

--> Please provide concrete examples of issues not fixed in 2.2.x --> Just take a look at the ongoing "indexing problems" --> This seems to be also a problem in 2.2.0 - Just one out of many!


--> In my opinion this is a bad management - in development you first have to make shure your system is as bug free as possible before you implement new functions. But you can see this clearly here at github as well. Bugs keep rising and rising - also with every release.
Not true. Amount of bugs is obviously decreasing. I do agree that Magento 2.2 is still not bugfree but this is something EVERY Magento Community member may improve, by either issue reporting or even fixes provided as pull requests. 
-----> Do you really consider over 2K Bugreports and for shure over 200 major bugs for your system to be a good coding and good management? Wow - ok i accept that this is your opinion but for us this is way too much and about 10+ times the size of bugs of other enterprise systems.



Finally:
--> and here we are again at the bugs which are not solved for close to 1.5 years now.
Again, please refer to concrete issues, I'll maybe even take a look into them in spare time. --> Shure just one out of many again --> 

https://github.com/magento/magento2/issues/6609
Reported over 1 year ago - not fixed till 2.1.7 - no information in the report if this is fixed in 2.2.0 - no timeline at all when this will be fixed.


I think we should stop discussing here really - this is not the platform for this right?

**Comment by brandontamm** [comment]
@orlangur - Nothing is missing except for the clarity. For instance, highlights could include something so people stop and think before doing something silly like upgrading production directly ;) Adding some verbiage like below examples to http://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html  would be helpful to avoid these scenarios:
- Please view backwards compatibility and deprecation notices here
- Development and deployment workflows will be affected with this release
- Commands that used to work will no longer work so please adjust previous scripting
- Framework Updates have been completed.

Just trying to help :)

**Comment by okorshenko** [comment]
Hi All, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion.  The GitHub issue tracker is intended for Magento Core technical issues only, but not for general discussion of eCommerce market.

**Comment by orlangur** [comment]
Stopping as well.

> --> I really doubt ALL problems were caused by changes in core code --> Nope! not one core code change at all!

I didn't mean that core code was changed improperly during customization, just that upgrade issues are usually caused by core customizations in extensions or `/app/code` (sometimes developer has to rely on core internals if there is no suitable `@api` marked extension code, breakage of such logic is expectable and needs to be monitored during upgrades as core implementation may change). Here is a recent example of such situation: https://github.com/magento/magento2/issues/10900#issuecomment-329821276

**Comment by okorshenko** [comment]
Hi @IAmTheVex 
Unfortunately, we can not reproduce the issue on our side. All Upgrade Tests successfully passed + we retested the upgrade process one more time manually.  On clean Magento installation upgrade works well.
As I see from the log you have installed `TemplateMonster_SiteMaintenance` and `TemplateMonster_LayoutSwitcher`. We can not test upgrade process with 3rd party extensions that you may have. 2.2.0 was a minor release and major change in several components. Please, review your installed extensions and make sure that all dependencies are configured properly. If you extensions do declare real dependencies, you may have an upgrade issue.

Here is a screenshot on some upgrade tests that we executed (this is just small part of all upgrade tests)
Here 2.x.x is a 2.2.0.
So as you see CLI Upgrade from CE 2.1.7 to CE 2.2.0 and from CE 2.1.7 to EE 2.2.0 passed
![upgradetests](https://user-images.githubusercontent.com/7325075/31250078-42ea98ae-a9df-11e7-8eb2-054ddb94ab4c.png)
