### ISSUE TITLE
Order date discrepancy on printing order 

### ISSUE THREAD

**Issue by kimVinqueur** [magento/magento2#11257]
### Preconditions

1. Magento 2.1.5 CE
2. PHP 7.0.18 and MySQL 14.14

### Steps to reproduce

1. Print Invoice
2. var_dump($order->getCreatedAt()) in function **insertOrder** (vendor/magento-sales/Model/Order/Pdf/AbstractPdf)

### Expected result

2017-10-04 17:40:40 (Timezone : America/New-York)

### Actual result

**Screenshot Admin :** 
![screen shot 2017-10-04 at 6 14 20 pm](https://user-images.githubusercontent.com/8004607/31237387-d4330730-a9c4-11e7-8cbc-e140012abc9d.png)

**Screenshot (var_dump($order->getCreatedAt())) :** 
![screen shot 2017-10-04 at 6 14 46 pm](https://user-images.githubusercontent.com/8004607/31237386-d431d2de-a9c4-11e7-8371-91d7dbb63703.png)

**Comment by magento-engcom-team** [comment]
@kimVinqueur, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
