### ISSUE TITLE
Call to a member function addCrumb()

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#11275]
I have encounter a small issue on new installation of Magento 2.1.7 regards to breadcrumbs.

step to recreate the issue is simple once install is susccesfull:

1- create custom Theme
2- create default.xml
3- add `<referenceBlock name="breadcrumbs" remove="true" />`
4- navigate to your Magento installation root url .../sales/guest/form/

5- error: 500 

Log:
`PHP Fatal error:  Call to a member function addCrumb() on boolean in /Library/WebServer/Documents/dev/vendor/magento/module-sales/Helper/Guest.php on line 205`

Comment or removing 

> /*($breadcrumbs->addCrumb(
            'home',
            [
                'label' => __('Home'),
                'title' => __('Go to Home Page'),
                'link' => $this->_storeManager->getStore()->getBaseUrl()
            ]
        );
        $breadcrumbs->addCrumb(
            'cms_page',
            ['label' => __('Order Information'), 'title' => __('Order Information')]
        );*/

Will display the the page correctly.

Thank's
Juliano

**Comment by magento-engcom-team** [comment]
Hi @lano-vargas 
thank you for the report. Would like submit a pull request with the fix? By this, you can participate in [#SQUASHTOBERFEST](https://github.com/magento/magento2/wiki/%23SQUASHTOBERFEST-2017)

**Comment by magento-engcom-team** [comment]
The fix looks simple

**Comment by lano-vargas** [comment]
@magento-engcom-team I can't promise but will try and work on it this weekend.

> I'm working on it #SQUASHTOBERFEST.

Thanks.

**Comment by lano-vargas** [comment]
@magento-engcom-team the "continuous-integration/travis-ci/pr" has errored with 

> "The job exceeded the maximum time limit for jobs, and has been terminated."

ref: https://travis-ci.org/magento/magento2/jobs/285215690

Please advice what to do next.
Thanks.

**Comment by lano-vargas** [comment]
@okorshenko Could you please restart build/trigger as mentioned here:https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit
Appreciate.

**Comment by orlangur** [comment]
@lano-vargas restarted, main CI source of truth is Bamboo runned internally, I'll let you know if there will be some issues revealed.

**Comment by lano-vargas** [comment]
@magento-engcom-team errored for the same reason as https://github.com/magento/magento2/issues/11275#issuecomment-335275722

**Comment by adrian-martinez-interactiv4** [comment]
@magento-engcom-team This issue should be closed, solved in PR https://github.com/magento/magento2/pull/11382

**Comment by okorshenko** [comment]
the issue has been fixed and delivered to 2.2.2 branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81647

**Comment by magento-engcom-team** [comment]
Hi @lano-vargas. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1283 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 074285735cd6d33fd530302390ab8101e73d7e34
 - fde512eacfce36508bcec2b1c08ef381d0af3f92
 - e7d90de918be70731e2021dee757d1e7af374ab8
 - 6d4f36db79a9bee553b4acfe8c0820b5c046e6af
 - 2e83a36fbf3201bdaf6612dcfce08125687f0e28
 - 23b4aa11f5a4a0b6bfe76cd1e812d36d88ed4d83
 - b50bfa811876af007426b734019fd149def63bba
 - 04cd60da14a87727768165942c23fc1403016e41
 - 75d5a0522e8a18c2f403ea284d62e445e3d6ddc2
 - 5e02b15fcbe310cd13e385d0ae7a3e6017b56497
 - aad5ba6236ca8557072f62db524b23d68eae5de3
 - 3e321401374a7f2292bd3b2c4540db2c0af34216
 - 7898946b7ec40999b2007ee377d6b6312a3778b3
 - a173e1cd160b1d7cd24a855420317fdd7bfd9624
 - 41d0075104cb628ec1806130b6449929e8585997
 - dda19b2f6eff23e0904673fe7719c3fd935aed02
 - cba48cdfedc500b652deee50e3a3dc95e366eca3
 - 0c62caaf80c9659530d0c3dd0741108d1b0dadb0
 - 736f783b1b2fd361fb8328fd7c5cf9e7c3c172e2
 - 7569b7002878019a115aa2ea587d476a282fcd17

The fix will be available with the upcoming patch release.
