### ISSUE TITLE
Issue on UI of admin panel and not able to run compilation

### ISSUE THREAD

**Issue by kytan91** [magento/magento2#11289]
Magento 2.1.9 version
![2017-10-07_23-47-31](https://user-images.githubusercontent.com/30074078/31309559-a0a1f352-abba-11e7-8eef-a59cf17e6e48.jpg)
![2017-10-07_23-48-40](https://user-images.githubusercontent.com/30074078/31309560-a25e85ca-abba-11e7-8f0e-cae701514395.jpg)
![2017-10-07_23-54-46](https://user-images.githubusercontent.com/30074078/31309582-ee59ac2a-abba-11e7-9a5a-1780580884c7.jpg)

Does anyone know how to solve this issues? 
when use this php bin/magento setup:di:compile in putty and happened somethings like this
and the backend show like pictures
it happened after restore back to 3 days ago.. suppose not get this kind of results. Please help

**Comment by JerVoo** [comment]
The error actually describes the problem pretty clear. A file is missing from the file system. Try to get the files back to the filesystem with composer and it will work.

The fact that backend isn't showing is due to missing static content files, which can easily be fixed by running `php bin/magento setup:static-content:deploy` followed by `php bin/magento cache:flush`.

**Comment by magento-engcom-team** [comment]
@kytan91 The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
