### ISSUE TITLE
Cart not clearing when session expires

### ISSUE THREAD

**Issue by stevenlavine** [magento/magento2#11314]
### Preconditions

1. Magento 2.4
2. PHP 7.x
3. MySQL 5.7
4. Apache 2.4
5. "Persistent Shopping Cart" is enabled

### Steps to reproduce

1. Add product to basket
2. Login - choose "remember me"
3. Leave the browser open
4. Refresh the page after some time

### Expected result

1. The customer should remain logged in
2. Or - if the session has expired, the minicart should have not any content

### Actual result

1. Customer is logged out
2. Minicart still has content
3. Going to the Cart page results in a empty shopping cart notice

**Comment by magento-engcom-team** [comment]
@stevenlavine, thank you for your report.
We've created internal ticket(s) MAGETWO-72402 to track progress on the issue.

**Comment by apotdar** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by lexwet** [comment]
Similar issue.

**Preconditions:**
- Magento: 2.2
- PHP: 7.0.24
- Mode: developer

**Steps to reproduce:**
- Add product to the cart
- Go to checkout 
- Double refresh the page
On the checkout page double/fast refresh (chrome/win double CTRL + R _or_ F5 key ) 

**Result:**
- User redirected to shopping cart page.
- Minicart still has content
- On the cart page showing "You have no items in your shopping cart".

**Comment by apotdar** [comment]
Hi @okorshenko,

Can you please assign this issue to me?

Thank you :)

**Comment by christophe29222** [comment]
Similar issue: But the bug occur after 60 minute (cookie lifetime). And if i set cookie lifetime to 86000, sessions times aren't increased. the cart is empty for guest at the next session (60 min inactivity).

Preconditions:

Magento: 2.2 or 2.1.9
PHP: 7.0.24

Steps to reproduce:

close browser and wait 60 minutes
start browser

Result:

The welcome message is here and the cart is full but user is not connected

i have fresh install of:
Version | Plesk Onyx v17.5.3_build1705170317.16 os_CentOS 7
OS | CentOS Linux 7.4.1708 (Core)
magento 2.1.9 or 2.2.0

Have you also the problem of empty cart for guest? Thanks

**Comment by apotdar** [comment]
Thanks for the update @Christophe29222.  I had issues with my vm instance.  Created a new vm and working on this issue.

**Comment by josh-nh** [comment]
Following as I am having the exact same issue as @lexwet. 

Preconditions:

Magento: 2.2 (we were on 2.1.7 before upgrading and the issue was not present then)
PHP 7.0.24
Varnish: 4 (using VCL generated for Varnish 4 in Admin panel)
OS: Same issue on Apache and Nginx
gc.maxlifetime: 86400
cookie expiration: 86400
Sessions: Using REDIS to store session data (config below)

Steps to reproduce:

1. Open new browser (preferable icognito but any instance works in any browser)
2. Add a product to your shopping cart
3. Proceed to cart
4. Proceed to checkout
5. Refresh checkout
6. Notice you are redirected to the shopping cart page with an empty cart. 

NOTE: This happens even without waiting any length of time between the steps above. 

One thing we have also see when this issue appears is that when viewing chrome's developer tools under application > cookies, is that there are 2 PHPSESSID's being set. One for our stores domain as: 

- .www.example.com and one for

- www.example.com (without the leading .)

For us this second PHPSESSID gets created when you go to the cart page. At that point the two values are the same, however when you navigate to the checkout page the first time, one of those values changes. then when you refresh the page and are redirected back to the shopping cart (emptied), both values are the same again. 

The issue appears to go away when we disable varnish, however that is just not possible for us as it will kill site speed. 

REDIS Config for Session:

'session' => 
  array (
    'save' => 'redis',
    'redis' => 
    array (
      'host' => 'redis',
      'port' => '6379',
      'password' => '',
      'timeout' => '2.5',
      'persistent_identifier' => '',
      'database' => '0',
      'compression_threshold' => '2048',
      'compression_library' => 'gzip',
      'log_level' => '1',
      'max_concurrency' => '6',
      'break_after_frontend' => '5',
      'break_after_adminhtml' => '30',
      'first_lifetime' => '600',
      'bot_first_lifetime' => '60',
      'bot_lifetime' => '7200',
      'disable_locking' => '0',
      'min_lifetime' => '86400',
      'max_lifetime' => '2592000',

**Comment by aeu** [comment]
I can reproduce this exactly the same way as @lexwet above.  Add to cart, go to checkout, hit refresh twice, and you will be redirected to an empty cart page with contents in the minicart.

I am running 2.1.11, Centos 7, PHP7, MariaDB.  I can get this to happen using both Redis and "files" for session storage, even with FPC and blocks HTML caching disabled.
![screen shot 2018-01-25 at 9 56 10 pm](https://user-images.githubusercontent.com/2225377/35423785-9fd0e528-021d-11e8-85f3-090253b06b69.png)



EDIT:  This does not happen with Magento 2 Enterprise, I tried this on a bunch of known M2 Enterprise sites and could not reproduce it.

**Comment by ghost** [comment]
Hi Guys, I was able to reproduce this in **Magento 2.2.2** but now I'm on **v2.2.3** and I'm not able to reproduce this, I've:

**PHP 7
Varnish: 4 
OS: Nginx
Sessions: Redis** 

Anyone knows if this issue was already fixed in **Magento 2.2.3** because I'm seeing that this was reproduced in _v2.3_ also.

Please if anyone knows please let me know.

Thanks

**Comment by ghost** [comment]
I was able to reproduce this again but with a bit more elaborated procedure.
After add a different shipping address and reload the page the checkout page was empty displaying the same image that @aeu user shared in previous comment.

So, this is still an issue, is there any Magento developer reviewing this? 

Thanks

**Comment by maksymcherevko** [comment]
Hi,

Magento CLI version 2.2.4
Issue still present.

**Comment by andy-rush-beerhawk** [comment]
This session issue is occurring for us also:
PHP: 7.1
No varnish
Redis: 4.0.8
Magento: ee 2.2.3

Steps to reproduce:

1. in an incognito window, log in as a customer
2. add an item to the cart
3. add an item to the wishlist
4. let the session time out
5. reload and navigate to /wishlist

The cart and wishlist both have the products added as was when logged in.

**Comment by engcom-Echo** [comment]
Hello All

I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Preconditions:**
"Persistent Shopping Cart" is enabled

**Steps to reproduce:**

1. Add product to basket
2. Login - choose "remember me"
3. Leave the browser open
4. Refresh the page after some time

**Result**
The customer is remain logged in
Or - if the session has expired, the minicart has no any content
![Screenshot_30](https://user-images.githubusercontent.com/51681435/71366607-28101780-25ab-11ea-8b41-dcb74889b876.png)
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
