### ISSUE TITLE
Feature: extra arguments for setup:config:set

### ISSUE THREAD

**Issue by tdgroot** [magento/magento2#11318]
### Preconditions
1. Imported Magento 2.2 environment

### Steps to reproduce

1. Import database from production backup
2. Download/copy/sync `app/etc/config.php` from production
3. Set deployment config to your environment using `bin/magento setup:config:set`
4. Run `bin/magento setup:upgrade`
4. Go to your webserver and it'll tell you that the environment is not installed yet.

### Expected result

1. It would be great if one could tell the `setup:config:set` command that the environment is installed.
2. The environment works after these steps

### Actual result

1. The `install` configuration is missing in `app/etc/env.php`
2. I can't use the environment, except by adding the `install` configuration to `app/etc/env.php`

I would really like the following arguments to be added to the `setup:config:set` command:
- `--install Set install date`
- `--mage-mode Set mage mode`

If you agree, I'd gladly make a Pull Request to make this happen!

**Comment by orlangur** [comment]
Why not just run  `bin/magento setup:install`?

**Comment by hostep** [comment]
@tdgroot: in your second step, if you also download the `app/etc/env.php` file to your local environment, it will probably work? We do it exactly the same in our workflow for Magento 2.1 and it works perfectly fine like that, I haven't had the chance yet to test the same workflow on 2.2 though.

**Comment by tdgroot** [comment]
@orlangur I feel like running `bin/magento setup:install` is a workaround for the problem. It has a lot of overhead, because generally speaking, it installs a database first, and it would create a `app/etc/config.php` file which differs from the production `app/etc/config.php`. 

@hostep Thank you, I haven't really thought about that. It would also tackle the problem of getting the crypt key to the environment. I didn't think about this, because we version the `app/etc/config.php` file, so downloading a config file from production is not part of our 'environment setup script' yet. Your method would work great in combination with `bin/magento setup:config:set`!

Although @hostep had a great suggestion, I still think it would be great if these arguments would be added to the `bin/magento setup:config:set command.

I kind of hoped for input like this, so thank you @orlangur @hostep!

**Comment by hostep** [comment]
Yes, that's exactly what we do when setting up a local environment.

Just informational and completely off topic, here is what we do when starting a new project in Magento 2.1 (this will most likely change in 2.2 because of various reasons):

- setup a new directory
- run `composer create-project ...` (*not* installing Magento just yet though)
- configure some files for the staging environment
- commit all in git
- do a first deploy to the staging environment (which triggers a `setup:install` on the staging)
- then setup a bunch of configurations on the staging (part automatic, part manual)
- only then start setting up the local environment by:
- getting the 2 config files `config.php` and `env.php` from the staging (we don't version `config.php` at this time)
- strip out potential Redis & Varnish configuration settings from the `env.php` file
- run `setup:config:set` to configure the database connection for our local environment
- getting a database dump from staging and import in local
- overwrite some configurations in the database (like the base_url's and again strip out potential Varnish settings)
- set the local environment to developer mode
- reindex, flush caches
- optionally get media files from the staging to local

(I probably forgot some steps, but these are the basics I think)

I hope this is helpful to someone :)

**Comment by orlangur** [comment]
> generally speaking, it installs a database first, and it would create a `app/etc/config.php` file which differs from the production `app/etc/config.php`

It can use existing database. What exactly can differ in `app/etc/config.php` generated?

> running `bin/magento setup:install` is a workaround

I didn't get familiar with new 2.2 pipeline workflow yet but it seems normal to me that every installation start from, well, install command :) If it is not suitable for some cases, like if it didn't allow to use existing database which is not true in fact, I believe it would be better to fix it than set some raw configuration directly.

**Comment by magento-engcom-team** [comment]
Hi @tdgroot. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/19
