### ISSUE TITLE
Method "getChildren" sort ordering

### ISSUE THREAD

**Issue by EliasKotlyar** [magento/magento2#11310]
### Preconditions
Bug can be reproduced in every Magento Version. M1 has it, M2 has it. Even M2.2 has it.

### Steps to reproduce
Create a Code which will call the following Class:
M1: Mage_Catalog_Model_Resource_Category_Flat
M2:  Magento\Catalog\Model\ResourceModel\Category\Flat 

With the following Method:
getChildren()

### Expected result
You will get a list of Ids of the children categories.
This list is sorted by the "position" attribute.

### Actual result
You will get a list of Ids of the Children Categories.
This list is sorted by entity-id attribute.

I dont see any special case where you would need the sorting by the entity_id. More usual you will need them sorted in the same order as in the Backend(by the position attribute).

Greetings,
Elias

**Comment by magento-engcom-team** [comment]
@EliasKotlyar, thank you for your report.
We've created internal ticket(s) MAGETWO-81314 to track progress on the issue.

**Comment by denisristic** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by denisristic** [comment]
@ishakhsuvarov this ticket is resolved :)

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-81456

**Comment by okorshenko** [comment]
Hi @EliasKotlyar the issue has been fixed in 2.2-develop branch and will be available in 2.2.2 release soon

**Comment by magento-engcom-team** [comment]
Hi @EliasKotlyar. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1283 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 074285735cd6d33fd530302390ab8101e73d7e34
 - fde512eacfce36508bcec2b1c08ef381d0af3f92
 - e7d90de918be70731e2021dee757d1e7af374ab8
 - 6d4f36db79a9bee553b4acfe8c0820b5c046e6af
 - 2e83a36fbf3201bdaf6612dcfce08125687f0e28
 - 23b4aa11f5a4a0b6bfe76cd1e812d36d88ed4d83
 - b50bfa811876af007426b734019fd149def63bba
 - 04cd60da14a87727768165942c23fc1403016e41
 - 75d5a0522e8a18c2f403ea284d62e445e3d6ddc2
 - 5e02b15fcbe310cd13e385d0ae7a3e6017b56497
 - aad5ba6236ca8557072f62db524b23d68eae5de3
 - 3e321401374a7f2292bd3b2c4540db2c0af34216
 - 7898946b7ec40999b2007ee377d6b6312a3778b3
 - a173e1cd160b1d7cd24a855420317fdd7bfd9624
 - 41d0075104cb628ec1806130b6449929e8585997
 - dda19b2f6eff23e0904673fe7719c3fd935aed02
 - cba48cdfedc500b652deee50e3a3dc95e366eca3
 - 0c62caaf80c9659530d0c3dd0741108d1b0dadb0
 - 736f783b1b2fd361fb8328fd7c5cf9e7c3c172e2
 - 7569b7002878019a115aa2ea587d476a282fcd17

The fix will be available with the upcoming patch release.
