### ISSUE TITLE
Infinite redirects in magento

### ISSUE THREAD

**Issue by scholtz** [magento/magento2#11355]
### Preconditions
1. Magento 2.2, Magento 2.3-dev
2. Any version of PHP
3. Webserver that supports Strict-Transport-Security or buggy extension

### Steps to reproduce
1. Install magento using only http
2. Set up HTTPS on webserver
3. Test webserver address
4. Go to magento administration

### Expected result
1. Magento login screen is displayed

### Actual result
1. Infinite redirect loop

Strict-Transport-Security is a default option in nginx in ubuntu. When user install magento, and later decides to switch https, he gets infinite redirect loop. Repeating redirects can be easily avoided even for developers to be notified when they develop extensions..

**Comment by orlangur** [comment]
As already explained in https://github.com/magento/magento2/issues/11350#issuecomment-335533670, such behavior is expectable and caused by incorrect server configuration. Just like a mistake in `nginx.conf` by itself may lead to infinite redirects not even involving backend application.

> When user install magento, and later decides to switch https, he gets error and no way to fix it

User should notice server misconfiguration and either switch https off to change Base URL via Admin UI or specify new Base URL via `bin/magento setup:install`.

Please stop spamming, you can add any additional information in initial issue. Also, if you see how to improve existing system behavior, you can propose a pull request.
