### ISSUE TITLE
Full Tax Summary display wrong numbers.

### ISSUE THREAD

**Issue by heyqule** [magento/magento2#11358]
The full tax summary is displaying total tax, instead of showing individual tax value.

### Preconditions
1. Magento 2.1.8 and 2.2.0
2.  PHP 7.0.22
3. MYSQL 5.6.35

### Steps to reproduce
1.   Set Display Full Tax Summary to Yes
2.   Set up 2 tax rule to apply 2 taxes.
3.   Create an order with 2 taxes.  I create an order for BC Canada with GST 5% and PST 7%.
4.  Go to order page and expand total tax summary

### Expected result
1. GST and PST should have a different value.
	

### Actual Result
1. GST and PST have a totaled value.
	
### The Current Fix:

Magento 1 appearently used to has this issue as well.  I ported the M1 fix to M2. The change worked.    

See the following gist for detail in line 88.
https://gist.github.com/heyqule/7c830137715544ff95baba50a5ed3d80

**Comment by magento-engcom-team** [comment]
@heyqule, thank you for your report.
We've created internal ticket(s) MAGETWO-81574 to track progress on the issue.

**Comment by adrian-martinez-interactiv4** [comment]
@heyqule taken gist proposed solution for PR :D

**Comment by heyqule** [comment]
@adrian-martinez-interactiv4 Thanks for setting up the PR.

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @heyqule. Thank you for your report. 
The issue has been fixed in magento/magento2#20682 by @niravkrish in 2.3-develop branch
Related commit(s):
 - [2258f50be930dddee4eb3e575e3826a2edbdd817](https://github.com/magento/magento2/commit/2258f50be930dddee4eb3e575e3826a2edbdd817)
 - [938eaf39d5406f8327d7cb445b0a16686aa7d063](https://github.com/magento/magento2/commit/938eaf39d5406f8327d7cb445b0a16686aa7d063)
 - [d6b100028f3c17a220015c44dde309c83557c4fa](https://github.com/magento/magento2/commit/d6b100028f3c17a220015c44dde309c83557c4fa)
 - [8e4c9ad3ce91dad42d5d22a60438d97fdf7d0380](https://github.com/magento/magento2/commit/8e4c9ad3ce91dad42d5d22a60438d97fdf7d0380)
 - [11b9b442109f13db51e9da589f42c57f42793c0d](https://github.com/magento/magento2/commit/11b9b442109f13db51e9da589f42c57f42793c0d)
 - [47a53b5039027850902d14d34edcff8b1d6ad686](https://github.com/magento/magento2/commit/47a53b5039027850902d14d34edcff8b1d6ad686)
 - [1c6138cf67cda426d6472560d3347eff62dac69e](https://github.com/magento/magento2/commit/1c6138cf67cda426d6472560d3347eff62dac69e)
 - [e5f5ecebd5a896bdcbf180434448c0fbfeffcb57](https://github.com/magento/magento2/commit/e5f5ecebd5a896bdcbf180434448c0fbfeffcb57)

The fix will be available with the upcoming 2.3.2 release.
