### ISSUE TITLE
app:config:dump locks every configuration setting no alternative to dump specific setting only

### ISSUE THREAD

**Issue by gulshan-streammarket** [magento/magento2#11396]
While using pipeline deployment app:config:dump locks every configuration setting and if merchant want to update any email he must have to run app:config:set command which is not possible. There should be some alternative to dump only specific setting that is required to prepare static content on build system.

### Preconditions

1. Magento 2.2
2. Pipeline deployment

### Steps to reproduce

1. Run app:config:dump
2. 
3. 

### Expected result

1. Email/Payment settings(update/enable/disable) must be editable in admin.

### Actual result

1. Settings locked and there is no alternative of app:config:dump 

I am not sure whether it is a bug or feature request. But it is not possible piepline deployment with locked confiuratiion. I found Magento-cloud have an alternative command. Am i missing something that i need be aware of.

**Comment by magento-engcom-team** [comment]
@gulshan-streammarket Thank you for your submission. We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues. Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by jalogut** [comment]
This PR will fixes this issue:

* https://github.com/magento/magento2/pull/12410

Until the PR gets merged, see here a temporal solution to avoid dumping all config settings:

* https://magento.stackexchange.com/questions/196912/appconfigdump-locks-everything-in-configuration#answer-202826

**Comment by magento-engcom-team** [comment]
Hi @gulshan-streammarket. Thank you for your report. 
The issue has been fixed in magento/magento2#12410 by @jalogut in 2.2-develop branch
Related commit(s):
 - [3202e941adcde6cc3aadd4494cc680210c47aa64](https://github.com/magento/magento2/commit/3202e941adcde6cc3aadd4494cc680210c47aa64)
 - [0812ba807e605343d397768199d67a0ecd811482](https://github.com/magento/magento2/commit/0812ba807e605343d397768199d67a0ecd811482)
 - [6751504cd9f8f2dc7290d802132bffab98a7d745](https://github.com/magento/magento2/commit/6751504cd9f8f2dc7290d802132bffab98a7d745)

The fix will be available with the upcoming 2.2.5 release.

**Comment by VladimirZaets** [comment]
Hi @gulshan-streammarket. Thank you for your report. 
The issue has been fixed in magento/magento2#14807 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [2631805b26189a589ab7ee9046c3f507838641e5](https://github.com/magento/magento2/commit/2631805b26189a589ab7ee9046c3f507838641e5)
 - [8bfbc774462c92111c2d0dc1a0d92630eab7579e](https://github.com/magento/magento2/commit/8bfbc774462c92111c2d0dc1a0d92630eab7579e)
 - [d3c53f847b05502c39c3ada06671627c9bfa82ef](https://github.com/magento/magento2/commit/d3c53f847b05502c39c3ada06671627c9bfa82ef)
 - [0cbf318c2b82e1a54162b75f293003754874ac30](https://github.com/magento/magento2/commit/0cbf318c2b82e1a54162b75f293003754874ac30)

The fix will be available with the upcoming 2.3.0 release.
