### ISSUE TITLE
Product Attributes Not Updating on Frontend

### ISSUE THREAD

**Issue by rbur0425** [magento/magento2#11403]
### Preconditions

1. Magento 2.2 CE 
2. PHP 7.0.23
3. MySQL 5.7

### Steps to reproduce

1. Add a custom product attribute and assign values
2. Select Text Swatch for Catalog Input Type for Store Owner
3. Save and view on frontend
4. Go back to product attribute and select Dropdown for Catalog Input Type for Store Owner
5. The changes are not applied, the text swatch still shows even though product attribute says dropdown. 

### Expected result

1. Add a custom product attribute and assign values
2. Select Text Swatch for Catalog Input Type for Store Owner
3. Save and view on frontend
4. Go back to product attribute and select Dropdown for Catalog Input Type for Store Owner
5. The changes are applied, the text swatch is no longer visible and it is a dropdown menu.

### Actual result

1. Add a custom product attribute and assign values
2. Select Text Swatch for Catalog Input Type for Store Owner
3. Save and view on frontend
4. Go back to product attribute and select Dropdown for Catalog Input Type for Store Owner
5. The changes are not applied, the text swatch still shows even though product attribute says dropdown. 

The dropdown is not showing and it is staying as a text swatch.

**Comment by magento-engcom-team** [comment]
@rbur0425, thank you for your report.
We've created internal ticket(s) MAGETWO-82245 to track progress on the issue.

**Comment by eugene-shab** [comment]
#mageconf

**Comment by eugene-shab** [comment]
Closed because duplicate #12695

**Comment by sidolov** [comment]
Hi @rbur0425. Thank you for your report. 
The issue has been fixed in magento/magento2#12771 by @eugene-shab in 2.2-develop branch
Related commit(s):
 - [39b1ef3a5b5a4741a0c664135b13944c4e7c7b61](https://github.com/magento/magento2/commit/39b1ef3a5b5a4741a0c664135b13944c4e7c7b61)
 - [94539b755992f120927a4760c06c624a0ced07c7](https://github.com/magento/magento2/commit/94539b755992f120927a4760c06c624a0ced07c7)
 - [3d76096a752ff234843890d7a072cd1d64e8c1c2](https://github.com/magento/magento2/commit/3d76096a752ff234843890d7a072cd1d64e8c1c2)
 - [0b079e05ab2e12c004fb1e81bda57817e5f0f14f](https://github.com/magento/magento2/commit/0b079e05ab2e12c004fb1e81bda57817e5f0f14f)
 - [71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79](https://github.com/magento/magento2/commit/71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79)
 - [47b2f4841ae27fa7bde0124e8860493e79c62a92](https://github.com/magento/magento2/commit/47b2f4841ae27fa7bde0124e8860493e79c62a92)
 - [707f1cd34f0f4c905b07658849984d0eb825d6d7](https://github.com/magento/magento2/commit/707f1cd34f0f4c905b07658849984d0eb825d6d7)
 - [9153fe221d7ce9e65a3b082ab9d79c26245f1e0b](https://github.com/magento/magento2/commit/9153fe221d7ce9e65a3b082ab9d79c26245f1e0b)
 - [1bd4acfee8a58b035eef561aaebe94f97990a4a2](https://github.com/magento/magento2/commit/1bd4acfee8a58b035eef561aaebe94f97990a4a2)
 - [f4990277bf9f20227402f4b76e57499873b170ad](https://github.com/magento/magento2/commit/f4990277bf9f20227402f4b76e57499873b170ad)
 - [3fa9ed2485a97972133ddb1f7d7e775f784fe6e4](https://github.com/magento/magento2/commit/3fa9ed2485a97972133ddb1f7d7e775f784fe6e4)
 - [8fa792a1444670e60fe6052c77e7b35684549906](https://github.com/magento/magento2/commit/8fa792a1444670e60fe6052c77e7b35684549906)
 - [7cd7adecf598dd6f9fe6ecd4369208869442387d](https://github.com/magento/magento2/commit/7cd7adecf598dd6f9fe6ecd4369208869442387d)
 - [54ad76c1f48eafbfe16a4e8e3c7669145a190627](https://github.com/magento/magento2/commit/54ad76c1f48eafbfe16a4e8e3c7669145a190627)
 - [bd126512cfe4f139a10ada9136495c1a617df158](https://github.com/magento/magento2/commit/bd126512cfe4f139a10ada9136495c1a617df158)
 - [cb6975c3f57739946cb65acebaf62300def1fa99](https://github.com/magento/magento2/commit/cb6975c3f57739946cb65acebaf62300def1fa99)

The fix will be available with the upcoming 2.2.6 release.

**Comment by ishakhsuvarov** [comment]
Hi @rbur0425. Thank you for your report. 
The issue has been fixed in magento/magento2#17750 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [0f28b61565c3108281ef24c5f846ba2034e9ba9c](https://github.com/magento/magento2/commit/0f28b61565c3108281ef24c5f846ba2034e9ba9c)
 - [d159921f79c68e9aec489192c223ce5535ff47d9](https://github.com/magento/magento2/commit/d159921f79c68e9aec489192c223ce5535ff47d9)

The fix will be available with the upcoming 2.3.0 release.
