### ISSUE TITLE
Setup page is available after installation completed

### ISSUE THREAD

**Issue by alihalabyah** [magento/magento2#1141]
I can access the setup page `/setup/#/landing` even after the installation was completed!

**Comment by maksek** [comment]
HI @alihalabyah, setup will be available after installation, if you will not add .htaccess deny all, or remove setup folder.
It is expected behavior. What is your desired expectation?

**Comment by alihalabyah** [comment]
@maksek Since keeping it might be risky, it should be removed, blocked automatically by the installation process.

**Comment by vrann** [comment]
@alihalabyah, your observation is correct and as @maksek said the only way right now to close access to that is to remove the path or configure web server.

But currently we are working on the feature which will redirect you to admin login screen as long as you are navigating to setup. You would need to be authenticated as an admin in order to view the page.

The feature will be released shortly.

**Comment by piotrekkaminski** [comment]
@vrann - can you give me link to the story you mentioned? redirect to login page is NOT CORRECT as it exposes your login path, if it is custom.

**Comment by vrann** [comment]
MAGETWO-34695

**Comment by vrann** [comment]
@piotrekkaminski good catch, we will avoid doing redirect. Admin need to be logged in before navigating the /setup or it will get 401 status code.

**Comment by alihalabyah** [comment]
@vrann Thank you!
@piotrekkaminski Good point!

**Comment by tanya-soroka** [comment]
Setup page is not available after installation right now. The @vrann suggestion has been implemented. 

Closed. Feel free to reopen if you see an issue with this.
