### ISSUE TITLE
Cart Price Rule Label is not working

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#11428]
### Preconditions

1. Magento 2.2.0
2. Create Cart Price Rule

### Steps to reproduce

1. While creating the cart price rule, I have given the Label value as "Buy 2 and Get 1 Free".
2.  In front end, Checkout page, It will show only the label as "Discount" not the given name has been reflected.

### Expected result

1. I need the exact label value that was given in the Admin end while creating the cart price rule

### Actual result

1. Label value has been shown as "Discount".

**Comment by magento-engcom-team** [comment]
@sasilinux, thank you for your report.
We've created internal ticket(s) MAGETWO-74692 to track progress on the issue.

**Comment by mrodespin** [comment]
I am going to fix this issue

**Comment by okorshenko** [comment]
Hi @sasilinux 
Thank you for the report. But this is expected system behavior. Please check user guide http://docs.magento.com/m2/ce/user_guide/marketing/price-rules-cart.html?Highlight=shopping%20cart%20rules

1. Coupon label is optional and we can not rely on it on the storefront.
2. User is applying the code so it is reasonable to show what was applied but not the alternative text (coupon label)
3. Coupon label will be rendered in the backend. Store owner does not care about the coupon code but he is interested what exact rule has been applied. 

@mrodespin thank you for the proposed fix and pull requests. Our fault that we confirmed the issue during initial verification. Unfortunately, we should reject your pull request.

@sasilinux if you are looking for this feature, I would recommend to make it configurable from the admin panel so that store owner can decide what should be rendered during the checkout. So feel free submit a pull request with this feature.

**Comment by pmoreno1980** [comment]
This is not the behavior that had Magento 1. This bug is when i create a shopping cart rule without coupon, that is an automatic discount, of course the customer should read the label.

**Again, we didn't have this issue on Magento 1**

**Comment by pmoreno1980** [comment]
@okobchenko here we have 2 situations for this issue (Cart Price Rule Label is not working):

1) Shopping Cart Rules **with Coupon Code** and this is the solution for that [https://github.com/magento/magento2/issues/6244](#6244) 

2) Shopping Cart Rules **without Coupon Code**, i mean automatic discount, we don't have solution for this yet, this #11438 doesn't work.

this is a very important problem that is not solved in Magento 2. **we didn't have this issue on Magento 1**

thanks for you help

**Comment by magento-team** [comment]
Hi @sasilinux. Thank you for your report. 
The issue has been fixed in magento/magento2#13141 by @ihor-sviziev in 2.2-develop branch
Related commit(s):
 - 976182b27212fb22bdb12c0a2da3e6a3e7231368
 - 3fc1f40d84b319e254284054c8a4dfe4aacf1a18
 - 0f36e0eac721070312fede445aa13d3b838e35d4

The fix will be available with the upcoming patch release.

**Comment by magento-team** [comment]
Hi @sasilinux. Thank you for your report. 
The issue has been fixed in magento/magento2#13223 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - 1721ff185412d7aa04f45bb68717b2083b5b7769
 - 90d508bc112b341d0eeeed6db0ab18ee8b9b64d0
 - 968d7af6a4b5c3845c136c85d58fe80d5a1cd601

The fix will be available with the upcoming patch release.
