### ISSUE TITLE
Certain upgrade scripts created with Pestle cause setup:di:compile to fatal error

### ISSUE THREAD

**Issue by jantzenw** [magento/magento2#11442]
## Preconditions
1. Magento 2.2.0 EE
2. [Pestle 1.4.2](https://github.com/astorm/pestle)

## Steps to reproduce
1. Use pestle to create an upgrade script containing something similar to the following structure:
<pre>

$eavSetup = <b>$this->eavSetupFactory</b>->create(['setup' => $setup]);

$eavSetup->addAttribute(
    \Magento\Catalog\Model\Product::ENTITY,
    'test',
    [
        ...
        'source' => \Magento\Eav\Model\Entity\Attribute\Source\Boolean::<b>class</b>, <----
        'global' => \<b>Magento</b>\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
        ...
    ]
);
</pre>
2. Run `setup:di:compile`. 

## Expected result
DI is compiled.

## Actual result
```
[Exception]
Notice: Undefined property: Magento\Setup\Module\Di\Code\Reader\ClassesScanner::$eavSetupFactory 
in ... upgrade_scripts/data/0.0.5.php
```

## Analysis
At the end of one line, there is the word `'class'`. In the following line, there is the word `'Magento'`. This triggers the following events:

1. `\Magento\Setup\Module\Di\Code\Reader\FileClassScanner::extract` thinks the file contains `class Magento`, 
2. Causing `\Magento\Setup\Module\Di\Code\Reader\ClassesScanner::includeClasses` to try to include the file, 
3. Causing the file to be included with `$this` being `\Magento\Setup\Module\Di\Code\Reader\ClassesScanner`, 
4. Causing `$this->eavSetupFactory` to fatal error. 

So Pestle upgrade scripts containing the following properties will fail:
1. Contain the word "class" that is parsed as its own token.
2. Contain another token that can be parsed as a class name.
3. Call a property or function on `$this` that `Magento\Setup\Module\Di\Code\Reader\ClassesScanner` does not contain.

I have reported this to Pestle as well. I understand that it is not Magento's responsibility to modify the code compiler to support Pestle.

**Comment by orlangur** [comment]
> it is not Magento's responsibility to modify the code compiler to support Pestle.

I don't see any mistakes in Pestle's code snippet you provided actually.

Thanks for detailed analysis, I don't see how `\Magento\Setup\Module\Di\Code\Reader\FileClassScanner::extract` may pick not the first class name occurrence though.

**Comment by piotrekkaminski** [comment]
Please refer to discussion about this issue here https://github.com/astorm/pestle/issues/311

**Comment by baublet** [comment]
This was closed for seemingly no apparent reason. I'm searching through the Mage2 contribution guidelines to see if the magento-engcome-team self-assignment indicates that this bug is being looked at internally, or if the labels "G1 Passed" and "G2 Passed" mean anything about the resolution of this bug. But I can't seem to find anything.

Can anyone (e.g., @maksek) shed some light on the status of this issue? It's still affecting our code comp and that of various third-party plugins. We can fix our own code comp issues affected by this bug, but we can't really do much easily about code comp bugs in our third-party plugins.
  
BTW, this affects **all code compilation**, not just code generated by Pestle. The code compiler should not be reading lines `::class` as a signal that the current file is a class definition file...
