### ISSUE TITLE
Delete additional address will not work if no default address is set

### ISSUE THREAD

**Issue by gnuzealot** [magento/magento2#11496]
### Preconditions

1. PHP 7.0.24
2. Percona 5.6.33-79.0
3. Magento 2.2

### Steps to reproduce
1.  Create a new customer account
2.  Add an address without making it a default for shipping or billing
3.  Delete option will show for the address, but will not function. href for link is just "#"

### Expected result
1. The address should be deleted

### Actual result
1. The delete link does not have any action at all

**Comment by gnuzealot** [comment]
Was able to narrow this down to a problem with my installation, please close.

**Comment by magento-engcom-team** [comment]
@gnuzealot, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
