### ISSUE TITLE
Psr logger debug method does not work by the default in developer mode

### ISSUE THREAD

**Issue by eralaz** [magento/magento2#11509]
Psr logger debug method does not work by the default when you just install &  switch to the developer mode.
To make that works store config switcher should be turned on (see attached img, by the default, it's turned off).

### Preconditions

1. Install Magento 2.2.0
2. Switch to developer mode.

### Steps to reproduce

1. Install Magento 2.2.0
2. Switch to developer mode.
3. Use Psr logger debug method.
4. File var/debug.log is not created.
5. Until you turn on "log to file" boolean switcher in store configuration advanced developer debug section.

### Expected result

1. In developer mode Psr logger debug method should write logs to var/debug.log without addition switches in store config.

### Actual result

1.  Happens opposite to expected result. It needs addition store configuring to make psr logger debug log to debug.log file being in developer mode.
<img width="1402" alt="screen shot 2017-10-17 at 09 05 06" src="https://user-images.githubusercontent.com/4068905/31651076-d9d3616e-b322-11e7-8e64-2ef1b1d7cbc3.png">

**Comment by magento-engcom-team** [comment]
@LaryShadow, thank you for your report.
We've created internal ticket(s) MAGETWO-82036 to track progress on the issue.

**Comment by orlangur** [comment]
Do you mean changing default value of `Log to File` from No to Yes? It may be undesired as log file may be quite huge and it is not used by every Magento user working in developer mode. Just like not every user needs `Enabled Template Path Hints for Storefront` by default.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @LaryShadow. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1351 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 70dd5a3fa17e1ee1cdfaf7f0defd9276989ebbd0
 - 54bc3a1dca861e11e46e12f5a15578e0cb7ceb6d
 - 3debd3f87e27e23949b81cb2d7e881b5a269608c
 - 72c496566bf0d2ff1ced0401514faa5cbaccc0f8
 - e60ecdfeabe8b8839cf52fd5ba7fefcbb0b9bdc3
 - 8703b3da3dbe28f71c1daeaba08bbe44887f0733
 - bd88ed8cc4e1f98b791bd7ca8bed45c29b276ee1
 - 1c70b18a339fddf8a51a476a5a251aabef951350
 - 5fd7481d2cf8b298369837508a16a23ab4f49850
 - 7c615065b36cdafa95d752a891c09dd4ab1a4dfa
 - 2653b8ae55625637a6836d305451e292f881bd6a
 - 917a03f89f98454cb2ecde524dc8557d7fdcc135
 - eca73d0abd1ca6e110c364ef380adab86ab3cc1a
 - 26f3109842ce89096a49b9c122af0bae6b672ba2
 - c223484a75e38fdcece09d4586342528f06c6383
 - 3b90ad71d791ba9cf8e81cc204fd306f41473a18
 - ad317c25039de70c1a976e1139c57730899eb114
 - 53e721ccc06f1ade05132690715575bd7d47d6b7
 - 6114120c0a921b342871448dfb6c47bf34a65cdc
 - 63b483925c18304a32441f66b0db8a9c70995c73

The fix will be available with the upcoming 2.3.0 release.
