### ISSUE TITLE
How to configure the SMTP?

### ISSUE THREAD

**Issue by JesusTinoco** [magento/magento2#1153]
I've been looking for the SMTP configuration but I didn't found, do you know where it is?

**Comment by grepdirect** [comment]
Stores > configuration > System > Mail Sending Settings

**Comment by JesusTinoco** [comment]
Thaks grepdirect, and do you know which file or which  table in the db I have to populate to do that manually without go to the admin panel?

**Comment by alihalabyah** [comment]
@JesusTinoco I think it's the `core_config_data`

**Comment by JesusTinoco** [comment]
But I would like to send emails from an external SMTP server, do you know how? Thanks @alihalabyah

**Comment by grepdirect** [comment]
No in Magento2 in core_config_data there's not email settings. 

Inviato da iPhone

**Comment by adzminz** [comment]
@JesusTinoco Are you running the store on unix server? If so, my suggestion is to install ssmtp and config your external smtp server in /etc/ssmtp/ssmtp.conf. It works without any settings on admin page.

**Comment by JesusTinoco** [comment]
Thaks @adzminz I'm running the store con unix server, but I would like that the smtp work on windows server as well.

**Comment by vpelipenko** [comment]
@JesusTinoco, do you still have questions here? Can we close this issue?

**Comment by JesusTinoco** [comment]
Basically I would like to know if it is possible use an external SMTP in magento2. For example how configure Magento 2 to send emails using gmail.

**Comment by kirmorozov** [comment]
Nothing to do inhere.
Please setup ssmtp to make any outgoing email go through any smtp..

**Comment by boscowitch** [comment]
To summarize for anyone else coming, Magento unlike other frameworks like laravel ect.  has no PHP SMTP support build into the framework, one has to install  ssmtp or  setup sendmail on the underlaying linux system in order to use a dedicated external smtp server/saas/account  like mailtrap ect.  ... it is not possible to simply put all the smtp config per shop into the magento configuration file ...

However alternatively there might be extensions out there that add this kind of feature....
