### ISSUE TITLE
Uncaught TypeError: methodList is not a function

### ISSUE THREAD

**Issue by stevenlavine** [magento/magento2#11536]
### Preconditions

1. Magento 2.1.9
2. MySQL 5.7
3. PHP 7.x
4. Apache 2.4

### Steps to reproduce

1. Add products to basket
2. Go to checkout
3. 

### Expected result

1. Shipping step should load

### Actual result

1. Loading spinner remains on the page

Developer Tools console reports:

Uncaught TypeError: methodList is not a function
    at Object.setPaymentMethods (payment-service.js:50)
    at payment.js:37
    at Object.execCb (require.js:1650)
    at Object.context.execCb (resolver.js:131)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132
    at require.js:1156
    at each (require.js:57)
    at Module.emit (require.js:1155)

**Comment by magento-engcom-team** [comment]
@stevenlavine, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by juergengp** [comment]
Hello,
i experienced that error many times on 2.1.9
it seems that different you are using a special combination of custom modules, that error occurs - especially in the payment section.  i'm using skrill for payment and get something like " reqire is not a fuintion" there is somewhere a ")" missing. this happens if a module is called in a special place of source-code. i got rid of that error doing an uninstall and reinstall of that module.  unfortunately i cant tell you what makes the difference after reinstall ... maybe the modules is called not at the same line of source afterwards- means it'S initialized maybe "later" or earlier.

**Comment by juergengp** [comment]
it seems that all occurs because many of the developers don'tknow what they are doing :-)
furthermore magento is a kind of huge application and nobody has an idea what happens inside of that application. thats a result of being specialied to a part of a system. only having experiency in producing wheels doesnt make a person to a mechanic of cars

**Comment by juergengp** [comment]
this is a problem in the IT sector in general .. everybody is specialized .. like some "unix specialists" havent got an idea of ip addressing :-)

**Comment by juergengp** [comment]
i forgot to mention:  if you are using a custom theme, search there first :-)
