### ISSUE TITLE
mini cart error

### ISSUE THREAD

**Issue by alen9788** [magento/magento2#11559]
1. Magento CE 2.2
2. 

### Steps to reproduce

After the item is added to the cart

### Actual result

1. [Screenshot, logs]

![cart](https://user-images.githubusercontent.com/20162144/31773544-aa70efbe-b515-11e7-95c2-a8775bb16d28.jpg)

The "Proceed to Checkout" link is gone.

**Comment by infortis** [comment]
It looks like you don't have proper version of the theme. Or the files of the theme are overridden by your extensions or by your custom modifications. 

The code of the mini cart dropdown has changed a bit in Magento 2.2.0 so the issue like this can happen if you are using theme files which don't reflect those changes.

**Comment by magento-engcom-team** [comment]
Hello @alen9788. Please, let us know if Your issue concerns what **infortis** mentioned about.

**Comment by alen9788** [comment]
It was solved after update the theme.

**Comment by magento-engcom-team** [comment]
@alen9788, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
