### ISSUE TITLE
Compiling with the compact strategy fails to copy images to a child theme

### ISSUE THREAD

**Issue by Silarn** [magento/magento2#11568]
We have a custom theme overriding Luma.

All the CSS/JS/HTML compilation seems to work fine, however when using the compact strategy on production mode I've noticed that image files are not being copied to the active child theme directory - even image files specific to the theme (under customtheme/web/images/).

When the server tries to load the images, it looks for them under pub/static/<version>/frontend/customtheme/language_CODE/images - but they are not there.

### Preconditions
1. Use custom images in a custom child theme
2. Set the application to production mode
3. Magento 2.2

### Steps to reproduce
1. Use the compact deployment strategy: magento setup:static-content:deploy -s compact

### Expected result
1. All CSS, JS, HTML, and images should be populated correctly into the pub/static areas.

### Actual result
1. CSS, JS, and HTML works as expected, but image files are not copied.

**Comment by magento-engcom-team** [comment]
@Silarn, thank you for your report.
We've created internal ticket(s) MAGETWO-82380 to track progress on the issue.

**Comment by Silarn** [comment]
Thanks.

**Comment by Silarn** [comment]
Is there any progress on a fix for this? I admit I haven't tried it for a couple versions.

**Comment by agorbulin** [comment]
It's reproduced on 2.2.5
Any progress with the issue?
Could you provide version in which it will be fixed or some patch maybe?

**Comment by magento-engcom-team** [comment]
Hi @Silarn. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-82380` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by hostep** [comment]
Hmm, I just ran into this problem on a Magento 2.3.1 store. Let me re-open this and I'll try to find exact steps to reproduce a bit later on.

**Comment by hostep** [comment]
Ok, exact steps to reproduce on a vanilla 2.3-develop instance:
1. Have a frontend theme, you only need these files:
```
app/design/frontend/Custom/
└── theme
    ├── registration.php
    ├── theme.xml
    └── web
        └── images
            └── test.png

3 directories, 3 files
```
2. Clear your static content files: `rm -R var/view_preprocessed/* pub/static/*`
3. Now first run using the default strategy `quick`: `bin/magento setup:static-content:deploy -f --theme Custom/theme en_US`
4. Notice that the file `pub/static/frontend/Custom/theme/en_US/images/test.png` exists
=> **good**
5. Clear your static content files again: `rm -R var/view_preprocessed/* pub/static/*`
6. Now run using the strategy `compact`:  `bin/magento setup:static-content:deploy -f --theme Custom/theme --strategy=compact en_US`
7. Notice that the directory `pub/static/frontend/Custom/theme/en_US/images` doesn't exist
=> **not good**

Tagging @DrewML because he'll be interested to see yet another SCD bug ;)

*Update*: It looks like the image gets put in the directory `pub/static/frontend/Custom/theme/default/images/test.png` and is being referenced in the file `pub/static/frontend/Custom/theme/en_US/map.json`. The idea is probably to have javascript resolve the correct path?
But we need these images in php code, not in javascript in this case, and php has no knowledge of this 'default' locale I'm guessing?

**Comment by hostep** [comment]
Sorry, I'm mistaken. We took over some shop which has code which references images like this in php code:
```php
<?php $someDynamicValue = 'test'; ?>
<img src="<?= $this->getViewFileUrl('images') . '/' . $someDynamicValue . '.png';?>"/>
```

That is wrong, it should have been:
```php
<?php $someDynamicValue = 'test'; ?>
<img src="<?= $this->getViewFileUrl('images' . '/' . $someDynamicValue . '.png');?>"/>
```

Using this new code, PHP is able to resolve the correct image file from that `default` locale which gets generated by the `compact` strategy.

So everything does work as expected.

Sorry for the noise! (But hopefully my comments are helpful for people running against a similar problem)
