### ISSUE TITLE
EE vs CE

### ISSUE THREAD

**Issue by gondo** [magento/magento2#116]
in the future, would you accept/ignore pull requests adding EE functionality into CE version?
f.e.: store credit is currently EE functionality, what if i would commit code to support this in CE?

**Comment by magento-engcom-team** [comment]
Hi @gondo. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#119 by @naydav in 2.3-develop branch
Related commit(s):
 - [4a4bbe2fc0947a8ff17906b4de0204ad5143aa21](https://github.com/magento/magento2/commit/4a4bbe2fc0947a8ff17906b4de0204ad5143aa21)

The fix will be available with the upcoming 2.3.0 release.
