### ISSUE TITLE
Price filter working wrong when applying a catalog price rule (discount 20%)

### ISSUE THREAD

**Issue by divivu** [magento/magento2#11639]
### Preconditions

1. Create a catalog price rule, discount 20% for certain product category
2. Configurable product with some child products with price and special price.

### Steps to reproduce

1. Create a catalog price rule, discount 20% for certain product category
2. Assign price for one child product is 100$, special price is 90$
3. Go to category page which that product belongs to
4. Click to filter by price, select prices from 90-100$
5. The product even present regardless of product's price is 80$
### Expected result

1. The price filter has to working right match with presented product price

### Actual result

1. [Screenshot, logs]
5. The product even present regardless of product's price is 80$
![price-filter-3](https://user-images.githubusercontent.com/13075342/31880125-ce7f2488-b809-11e7-9e1e-7663bbef6bc7.png)

**Comment by Tristan-N** [comment]
I have the same issue. Magento 2.2, php 7.1.10 (production) and php 7.1.18 (local) and both mySQL version 5.7.19 Same also occurs when selecting filters on the top of the category page as you can see on the screenshot.

Configurable Product with catalog price rule. Filtering of products is executed before calculating catalog price rules instead of after calculation. 

![filter_issue](https://user-images.githubusercontent.com/19165453/32175783-3a0e6552-bd86-11e7-924b-2c96e09f2466.png)

**Comment by Tristan-N** [comment]
Are there any updates regarding this issue?

**Comment by divivu** [comment]
Hi Tristan-N, this issue will be fixed on 2.3.x releases. You can check commits that related on magento 2 repo. Now I am not focus on this issue anymore.

**Comment by michel334** [comment]
how can we find the code fix for this issue? Is there an internal Magento ticket number we can track?

**Comment by piszczek** [comment]
Is there any progress on that?

**Comment by dhorytskyi** [comment]
Was fixed in
#https://github.com/magento/magento2/commit/56859b0c84cc41d03617800c930b937a12711e2f

**Comment by divivu** [comment]
Thanks dhorytskyi

**Comment by CrowlaraZ** [comment]
Can you let us know which files this has been fixed?

**Comment by CrowlaraZ** [comment]
@dhorytskyi Hello! Can u help me please? which files i edit? 
I am using 2.1.7, I cant upgrade to other version.
Thanks in advance!

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @divivu The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
