### ISSUE TITLE
Captcha not showing on custom theme after upgrade to v 2.2

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#11653]
Preconditions

Previous version 2.1.7
PHP version 7.1.9

Upgrade to version 2.2.0

Steps to reproduce

1. Use Custom theme.
2. Goto Forgot Password page on frontend 

Expected result

1. Forgot Password page should appear
2. Screen should show input box to place email address and for captcha
3. Image of captcha should also appear.
4. Attempts to change password after entering details required on screen should be successful

Actual result

Captcha field is not appearing on forgot password page in v2.2
Attempts to reset password shows error message 'Incorrect CAPTCHA'

**Comment by orlangur** [comment]
Well, you need to check how CAPTCHA code in core theme currently looks like in 2.2 and change custom theme accordingly.

**Comment by magento-engcom-team** [comment]
@msawyers, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by msawyers** [comment]
ok, will check on this.
