### ISSUE TITLE
Wrong return type for getAttributeText($attributeCode)

### ISSUE THREAD

**Issue by diazwatson** [magento/magento2#11691]
When I pass the a multi-select attribute code to `getAttributeText($attributeCode)` I get an `array` instead of an `string`.

https://github.com/magento/magento2/blob/4d2609343a950e9ee6b50cc4444469d50d82b139/app/code/Magento/Catalog/Model/Product.php#L1717

Actually I don't see anything wrong with it but the return tag should be updated accordingly. 

### Preconditions

1. Magento CE 2.1.9 /2.2 with sample data.

### Steps to reproduce

I guess the easiest way to reproduce it is by:
1. Creating a multi-select attribute for a product and add few values.
2. Add the attribute you just created to the attribute set Default
3. Edit a product using that attribute set and select all attribute values.
4. Then you could use (for example) 

`magento/module-catalog/view/frontend/templates/product/view/form.phtml` 

to output the attribute values:
```php
print_r($product->getAttributeText('your-attribute-code-here'))
```

### Expected result

I would expect the return to be a `string` type as the return type says.

### Actual result
But the result is instead an `array` of attribute values.

![screen shot 2017-10-24 at 14 40 05](https://user-images.githubusercontent.com/1080386/31946304-6417f5be-b8c9-11e7-941b-4b08fd099aa8.png)

**Comment by magento-engcom-team** [comment]
@diazwatson, thank you for your report.
We've created internal ticket(s) MAGETWO-83251 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @diazwatson thank you for your report. The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @diazwatson. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1358 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 2e90684d1f906a63c37e2dea4710aee59c0c0a58
 - f99b75906ab0d370005692499faebba810aa3984
 - 49a3076876a44798397495c6f376699eb3214528
 - b754973b0c24a5d4482ba6b027f8d673a64dae80
 - ed833c492e51f78ee2523c0b2eb5fee37c91166d
 - d8b73d3bb4b8ff66faa308e761b9ade25d0bf9f7
 - 60e83eac5925e1ec01cbc11b8eb1acc5305a7a23
 - dc69e175dc95befc3e1c0eb1b9d51c23a0e1e0e9
 - 6b9c188627aa4d9614c5ffe1a0436d75e17bb796
 - 3b58efc8e8cf3f856f7f0edbe84bd2ceb5f167b2
 - 8b40859ed856295dfd4240638c26d7b17807402a
 - 11922a14040b4869da87445fa627533256164595
 - 0bd39d42c785cac7ee0b49434cb957baa04f6c7f
 - 8bbb8bbb675f10f9632e76ff27a8199a7a3aa4ee
 - f8307d9d169debab91b1440d131dc166eb2e2640
 - 768c769b2772743e8599840aa8dc523597d0b6e5
 - 16a10291b25f826d066f155257a3922ee3f01682
 - 17a26cbcf93a3d95815a21b92dc9bc04ec116e58
 - 8f1d8e78df9cd8f648ea30d399f81816ad1d6d01
 - 5d084ce7979f07e7b1d6ac9980be13fdd2a378cd
 - d248f4e39a1fca56c5ea429dca5af190e28c56cb

The fix will be available with the upcoming 2.3.0 release.

**Comment by diazwatson** [comment]
Nice, thanks

**Comment by mihaikalif** [comment]
Was this fixed? I have magento 2.3.3 and I still replicate this when printing an attribute multiselect:
My code below
<<<<<
$att_network_technology = $_product->getAttributeText('mobile_network_technology');
<td class="col data"><?php if( $att_network_technology != '' ) { print_r ($att_network_technology); } else { echo '<span class="no-attribute-value">N/A</span>'; } ?></td>

>>>>>>>

**Comment by mihaikalif** [comment]
<td class="col data"><?php if( $att_network_technology != '' ) { print_r ($att_network_technology); } else { echo '<span class="no-attribute-value">N/A</span>'; } ?></td>

**Comment by mihaikalif** [comment]
![1](https://user-images.githubusercontent.com/61434922/79041379-11dca480-7bf8-11ea-987f-8e81d7059ae0.PNG)
