### ISSUE TITLE
"Something Went Wrong" error for limited access admin user

### ISSUE THREAD

**Issue by expgabe** [magento/magento2#11700]
### Preconditions

1. Magento 2.2
2. CentOS Cpanel 66.0 with Engintron Nginx for cpanel,  Apache 2.4.28,  MySQL 10.2.9-MariaDB , PHP 7.0

### Steps to reproduce

1.  Login as an admin user with limited access 
2.  Something went wrong error pops up after every page load
3.  Server Logs and Magento Logs don't record any errors

### Expected result

1. Logs should point to the error. 

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@expgabe, thank you for your report.
We've created internal ticket(s) MAGETWO-82713 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by georgios-2317** [comment]
Are you sure this is fixed and done?!
Just tried the changes from https://github.com/magento/magento2/commit/4904b3d0f0e73d9a7452407c5162c2d55b04b049 and the error persists.

**Comment by magento-team** [comment]
Hi @expgabe. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1286 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by george-vlahakis** [comment]
404 at https://github.com/magento-engcom/magento2ce/pull/1286

**Comment by okorshenko** [comment]
Hi @georgios-2317 
this is a private repository with limited access that's why you got 404

**Comment by philsmcc** [comment]
It is usually just this..
Say you only want to give someone access to add products...

Enable "Catalog", and under system, you can also enable "notifications" under "System".

The error usually comes from the message that tells you that one of your cache types is invalidated but is is being blocked because the user does not have access to receive system messages and notifications, so it throws an error.  You may also need to give access to some of your theme's and modules properties that produce notifications or if it is related to adding products or whatever task you want to assign to that role.
