### ISSUE TITLE
Wrong price amount on product page

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#11717]
### Preconditions
1. Install Magento2.2.0 via composer
2. Deploy sampledata
3. Configure store view language as ja_JP
(To activate IDR, KRW, VND, and EUR is better for test)

### Steps to reproduce
1. Access to product page.
2. Check price part.

### Expected result
1. Price should be shown as $00.00 or ￥00. (00 means real product price)

### Actual result
<img width="561" alt="jpy" src="https://user-images.githubusercontent.com/124136/31990614-91bd7e98-b9b0-11e7-9c71-547f9d20a3a0.png">
<img width="520" alt="usd" src="https://user-images.githubusercontent.com/124136/31990615-9243fcb6-b9b0-11e7-89a4-06004b9b0c3b.png">

**Comment by magento-engcom-team** [comment]
@HirokazuNishi, thank you for your report.
We've created internal ticket(s) MAGETWO-82730 to track progress on the issue.

**Comment by sidolov** [comment]
Hi @HirokazuNishi. Thank you for your report. 
The issue has been fixed in magento/magento2#15540 by @HirokazuNishi in 2.3-develop branch
Related commit(s):
 - [cf05a84f73a36b2fabd08d630e077b6e3ea922f5](https://github.com/magento/magento2/commit/cf05a84f73a36b2fabd08d630e077b6e3ea922f5)
 - [67a203869a0cff6495bf4953659f0a720cc0641d](https://github.com/magento/magento2/commit/67a203869a0cff6495bf4953659f0a720cc0641d)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @HirokazuNishi. Thank you for your report. 
The issue has been fixed in magento/magento2#15909 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [ea16687f3c6897d8b1cab96c9737d59903107c5d](https://github.com/magento/magento2/commit/ea16687f3c6897d8b1cab96c9737d59903107c5d)
 - [8a4d96645182c443477415f03ca609c30d1cc908](https://github.com/magento/magento2/commit/8a4d96645182c443477415f03ca609c30d1cc908)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @HirokazuNishi. Thank you for your report. 
The issue has been fixed in magento/magento2#16588 by @vkublytskyi in 2.3-develop branch
Related commit(s):
 - [e2c4acae5974c91e16a437e027b06affa4a97822](https://github.com/magento/magento2/commit/e2c4acae5974c91e16a437e027b06affa4a97822)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @HirokazuNishi. Thank you for your report. 
The issue has been fixed in magento/magento2#16590 by @vkublytskyi in 2.2-develop branch
Related commit(s):
 - [e1db595425a207779a04ca83f36a60549f517ec5](https://github.com/magento/magento2/commit/e1db595425a207779a04ca83f36a60549f517ec5)

The fix will be available with the upcoming 2.2.6 release.
