### ISSUE TITLE
Admin data table headers are not showing correctly 

### ISSUE THREAD

**Issue by antoniszachos** [magento/magento2#11736]
Admin data table headers are not showing horizontally but vertically

Magento 2.0.7.
PHP 7.0.23

![magento-error](https://user-images.githubusercontent.com/31135329/32009509-020708b6-b9b8-11e7-9148-5cc6a58c99fb.jpg)

I removed all static content, run setup:static-content:deploy, indexer:reindex, cache:clean cache:flush but the problem persists.

Thanks in advance!

**Comment by orlangur** [comment]
> Magento 2.0.7.

This version is quite old, upgrade to `2.1.x` or at least to latest `2.0.x` could help.

**Comment by antoniszachos** [comment]
Last time I tried to upgrade to latest version, the process couldn't finish due to some data-entry and file naming errors and the whole installation was corrupted and stopped working...  Anyway, i will give it one more shot... Thanks

**Comment by orlangur** [comment]
Good luck!

> the process couldn't finish due to some data-entry and file naming errors and the whole installation was corrupted and stopped working...

Yeah, sometimes this process is not seamless, various issues could be observed due to environment setup / customization bugs / core bugs. But this cannot be postponed forever at least for the sake of security upgrades, like https://magento.com/security/patches/magento-2016-and-219-security-update.

It is never a good idea to upgrade a live store without a try on some staging environment but hope you already take this into account.

**Comment by antoniszachos** [comment]
I know... Thankfully the shop in not live yet... 

Thank you for your info.
