### ISSUE TITLE
Sending emails from Admin in Multi-Store Environment defaults to Primary Store

### ISSUE THREAD

**Issue by lee586** [magento/magento2#11740]
### Preconditions

1. Tried on versions 2.18-2.2
2. Cent OS 7, PHP 7.1.10

### Steps to reproduce

1. Create two stores: ABC.com (primary) and XYZ.com
2. Have customer place order on XYZ.com
3. Go into admin, click on order from XYZ.com, and resend order confirmation email

### Expected result

1.  Should send email using FROM EMAIL and FROM NAME of store XYZ.com

### Actual result

1.  Magneto sends correct email content, but FROM EMAIL and FROM NAME are both from the primary store ABC.com instead of the store the customer used, XYZ.com.  Creates confusion for customer as the FROM information is not the store from which they placed the order.  Happens on any email resent from admin--confirmation, shipping, credit, etc.

**Comment by magento-engcom-team** [comment]
Hello @lee586. Tanks for reporting. Please clarify You mean two stores on the same website or two stores on two different websites.

**Comment by lee586** [comment]
Sorry for not clarifying.  Two different websites.

**Comment by magento-engcom-team** [comment]
@lee586, thank you for your report.
We've created internal ticket(s) MAGETWO-82906 to track progress on the issue.

**Comment by EugenOrosan** [comment]
Any fixes for this ? This is a big issue because customers receive emails from the default sender instead of order website sender.

**Comment by ArroganceEmu** [comment]
The problem is the same if both shops are under the same website.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by okorshenko** [comment]
Hi @lee586. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1325 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - e84cb3eb79f63f3cac85f5b68b90b82530786d86
 - 742819bdd72880190a992a0f9412af4c0ba417ae
 - cc2b11f47825471e93523db287b4a013da6629d5
 - ae8b1870640227d69e921a5a358fe2addefb5018
 - 35b3c02ca62fa40990fd957c36cd21b7e4f127cd
 - eae893662678539fa602434d92d798ec8a3b3a4c
 - 90e49230db9a94b2b5831c5618b960de35ebc4e0
 - b098dbc4e53efae137286bf056f1e46a2971d52c
 - e8e4cdd29db74ccd13f3078f93c59fb53c4a96d3
 - 058e5e55680e4ca8eb64311f782994fac10a1f74
 - 9368d5da237eb6e158990f2cff8be954242821fe
 - bf19409195b7b93322073026455405ed8820e6af
 - a15ec3421d3d2371429f9c804b91ecd3b6aaf763
 - 9e4ce76a9ad07713d2170420fcd8d237ec776fcb
 - 099568124736c9575bf7498641a0842877260346
 - 6772a2d6658c4677334df0b67159d3a47b6d2155
 - b0d6bfc6599390f31ef3b564fb3e2848037faeef
 - b03735716895f21bee4bc5b5be7d5c7f5a27ba33
 - 8de595178d6dca294d649fde0359a055f07fca69

The fix will be available with the upcoming 2.3.0 release.

**Comment by Hajo-Magre** [comment]
Hi, the link above is private or broken and gives a 404. The list of related commits is large and does seem to adress a lot of other issues, that I am not experiencing. Of course they could be heavily related.

I am on 2.2.3 right now. The fix for this is in 2.3.0. Is there a rough ETA for it's arrival? How many minor versions will we have in between?

In others words: my customers are receiving 'wrong'  email, that is: not from the shop they ordered from. This is a serious issue at this time.

Has anyone figured out a temporarily fix or workaround for this issue? 

(Besides: this issue received the label "fixed in 2.2.x" but I can confirm that is NOT the case in 2.2.3.)

== UPDATE:
found a temporarily fix, I think:
1. Magento has 5 emailadresses to configure in General > Stores Emailadresses. I've set one of them to an emailadress of my second store, but I set that value at **top** level i.e. "default config", NOT at the store view or website level. I chose to use "Custom Email 2" for this purpose.
2. Went to Sales > Sales emails and configured each email instance to use "Custom Email 2" as email sender, but **only** in the scope of my second store or website.
Result: Magento can read the emailadress and from name from a top level (default config) instead of the store view, where it al goes wrong.
I think this fixed it for now. Will report back here if anything else pops up.

**Comment by zack6849** [comment]
Is there not going to be a backport to 2.1 for this fix?

**Comment by ritschi72** [comment]
Still got that problem in 2.2.4 ...

**Comment by diedburn** [comment]
This broke the normal confirmation email https://github.com/magento/magento2/issues/14952

**Comment by gwharton** [comment]
This also broke sending multiple emails at the same time from admin backend. The first email succeeds, but all remaining emails fail with an exception saying can't set from address twice. Presumably because the $message object is now static, each time this function is called it is trying to add from address again.

**Comment by gwharton** [comment]
https://github.com/magento/magento2/issues/16203

**Comment by daveyx** [comment]
updated from 2.2.3 to 2.2.4 and now i have also this issue
(i have only one store)

**Comment by juandosil** [comment]
Same issue here with Magento 2.2.4 with only one store

**Comment by cleardarren** [comment]
same issue with 2.2.5 multistore

**Comment by gwharton** [comment]
Note. If you dont use the amazom payments module, disable or uninstall it to get this working again. This update triggered a bug in that module.

**Comment by juandosil** [comment]
Just disable it bin/magento module:disable Amazon_Core Amazon_Login Amazon_Payment and it´s working fine again.
Thank so much

**Comment by magento-engcom-team** [comment]
Hi @lee586. Thank you for your report. 
The issue has been fixed in magento/magento2#18471 by @gwharton in 2.3-develop branch
Related commit(s):
 - [ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3](https://github.com/magento/magento2/commit/ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3)
 - [e16ff74e4f5f24a4a2530b6aced6ef50032515e0](https://github.com/magento/magento2/commit/e16ff74e4f5f24a4a2530b6aced6ef50032515e0)
 - [621d2cfeaf8e0a15e592cdc001c856385b3cbd83](https://github.com/magento/magento2/commit/621d2cfeaf8e0a15e592cdc001c856385b3cbd83)
 - [b6f9e48289119117df230b6578ac9ff3d69e4996](https://github.com/magento/magento2/commit/b6f9e48289119117df230b6578ac9ff3d69e4996)
 - [0dc85785e522e2be8c72dfeaee7e9f5054195034](https://github.com/magento/magento2/commit/0dc85785e522e2be8c72dfeaee7e9f5054195034)
 - [122019c953037df74ef97245a42b274eae2e6639](https://github.com/magento/magento2/commit/122019c953037df74ef97245a42b274eae2e6639)
 - [193c6c2f6facf7276c1c8858d29ea3b847062ef5](https://github.com/magento/magento2/commit/193c6c2f6facf7276c1c8858d29ea3b847062ef5)
 - [bd0aa57cc837918335015d051f08cf380dc186d0](https://github.com/magento/magento2/commit/bd0aa57cc837918335015d051f08cf380dc186d0)
 - [523b0464966f81f1f01aa13073092bfddf363219](https://github.com/magento/magento2/commit/523b0464966f81f1f01aa13073092bfddf363219)
 - [424929fe9aee1005601cc2c9c7ad0090741be723](https://github.com/magento/magento2/commit/424929fe9aee1005601cc2c9c7ad0090741be723)
 - [c32ca7a0d58cbc57276349b26eb5ecd38451fd2d](https://github.com/magento/magento2/commit/c32ca7a0d58cbc57276349b26eb5ecd38451fd2d)
 - [e39ce7a3f2a7e6ee134cff9a097b7321756c32cf](https://github.com/magento/magento2/commit/e39ce7a3f2a7e6ee134cff9a097b7321756c32cf)
 - [99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31](https://github.com/magento/magento2/commit/99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31)
 - [f171c9d6ab035439ffb6374ec14dd8d51123dcd2](https://github.com/magento/magento2/commit/f171c9d6ab035439ffb6374ec14dd8d51123dcd2)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @lee586. Thank you for your report. 
The issue has been fixed in magento/magento2#18472 by @gwharton in 2.2-develop branch
Related commit(s):
 - [82a635b3a4eb0fd0e2f030d82495ab717ee11db5](https://github.com/magento/magento2/commit/82a635b3a4eb0fd0e2f030d82495ab717ee11db5)
 - [16afc0962463261e4464456b9bdaad4e8f3be924](https://github.com/magento/magento2/commit/16afc0962463261e4464456b9bdaad4e8f3be924)
 - [47c5f72c9196dc77b50db3c36ec99719a69a18a0](https://github.com/magento/magento2/commit/47c5f72c9196dc77b50db3c36ec99719a69a18a0)
 - [8d7a4513ddf4b759a6c6a0d2ace04aa714a396df](https://github.com/magento/magento2/commit/8d7a4513ddf4b759a6c6a0d2ace04aa714a396df)
 - [a7cd527a6896c3a2f204e2771b92496ef4089f4e](https://github.com/magento/magento2/commit/a7cd527a6896c3a2f204e2771b92496ef4089f4e)
 - [491d7f133591c64346cb54c2392d0ef212333b1a](https://github.com/magento/magento2/commit/491d7f133591c64346cb54c2392d0ef212333b1a)
 - [490e5d22074224ec1965a391abfffc379c31d0ee](https://github.com/magento/magento2/commit/490e5d22074224ec1965a391abfffc379c31d0ee)
 - [b19b3ed195b870f16a00c673e435b5b9b8184227](https://github.com/magento/magento2/commit/b19b3ed195b870f16a00c673e435b5b9b8184227)
 - [9f34fd631a55ded6d8a458d219edfc23c1bc5f9b](https://github.com/magento/magento2/commit/9f34fd631a55ded6d8a458d219edfc23c1bc5f9b)
 - [66478ec59d6cbf77d538f2ea112f32997e491bf8](https://github.com/magento/magento2/commit/66478ec59d6cbf77d538f2ea112f32997e491bf8)
 - [cc34f00113e1e644e92002f82d34c4bf36aa0e26](https://github.com/magento/magento2/commit/cc34f00113e1e644e92002f82d34c4bf36aa0e26)
 - [fb572d887f0ce156c8f3ac149de7b8f06835623d](https://github.com/magento/magento2/commit/fb572d887f0ce156c8f3ac149de7b8f06835623d)
 - [59a4e57a0c36671ff84e8398f413253610a512ac](https://github.com/magento/magento2/commit/59a4e57a0c36671ff84e8398f413253610a512ac)
 - [a8bcb8bb8442a649bf1e62400ca6f147023e53c6](https://github.com/magento/magento2/commit/a8bcb8bb8442a649bf1e62400ca6f147023e53c6)
 - [573cf7a9fee7c2d8ca9c1c25fe909c93ccf06c49](https://github.com/magento/magento2/commit/573cf7a9fee7c2d8ca9c1c25fe909c93ccf06c49)
 - [ef635bf6b8ecf67c729deb38df05c81b9e5b5359](https://github.com/magento/magento2/commit/ef635bf6b8ecf67c729deb38df05c81b9e5b5359)
 - [daa8996bbda2e7ca938a7e3a3e8afc40502cd98f](https://github.com/magento/magento2/commit/daa8996bbda2e7ca938a7e3a3e8afc40502cd98f)

The fix will be available with the upcoming 2.2.9 release.

**Comment by Rickertje** [comment]
@magento-engcom-team Are you sure this has found its way into 231 ?

**Comment by okorshenko** [comment]
Hi @Rickertje 
Could you please clarify your question? Are you still able to reproduce the issue on latest 2.3-develop?

**Comment by Rickertje** [comment]
I'm responding to this comment
![afbeelding](https://user-images.githubusercontent.com/27420995/59284028-d8e84200-8c6b-11e9-9704-9f66b0b769eb.png)
I was expecting to see this fixed in 231 but Im still experiecing the orginal problem in 231.
Have not checked 23develop since I'm not a developer

**Comment by okorshenko** [comment]
Sure, we will double check this issue.

**Comment by soleksii** [comment]
Hi @Rickertje ! Thank you for your collaboration!

I'm not able to reproduce the issue on latest 2.3-develop and 2.3.1 release.

**Steps to reproduce:**

1. Create two websites: magento23.loc (primary) and magento23second.loc
2. Have customer place order on magento23second.loc
3. Go into admin, click on order from magento23second.loc, and resend order confirmation email

**Actual Result:**
Magneto sends correct email content, FROM EMAIL and FROM NAME are both from the second store 
magento23second.loc

![screen](https://user-images.githubusercontent.com/44244273/59335841-097cba00-8d06-11e9-84e4-fe0fd100c8f5.png)

Could you please provide more details how to reproduce the issue?

Thanks!

**Comment by Rickertje** [comment]
Hi @stoleksiy . I can reproduce this but only on my own 231 install which was upgraded from 227 recently. So its not a fresh install. Could be that some custome code is interfering. I dont know and I'm not in the position to thorougly investigate this right now. For now you can close the issue again. Thank you very much for taking the time to check this for me. Regards. Rick

**Comment by okorshenko** [comment]
Closing the issue based on comment above

**Comment by angelflo** [comment]
still got the pb with magento 2.2.10 ? can someone explain me clearly what to do to fix this ?
