### ISSUE TITLE
Can't add customizable options to product

### ISSUE THREAD

**Issue by mikelevy300** [magento/magento2#11792]
### Preconditions

1. PHP 7.0.16
2. MySQL 5.7
3. Apache 2.4
4. Magento 2.1.9 (I was able to recreate this w/ both the sample data and the data from my store)

### Steps to reproduce

1. Go into the admin panel and navigate to Stores->Attribute Set
2. Edit the default attribute set, add a new group named 'Options', add a few attributes to the new group, and save the group
3. Navigate toe Products->Catalog and choose any product with the default attribute set to edit
4. Expand the Customizable Options section and click the 'Add Option' button

### Expected result

1. A new customizable option form should appear

### Actual result

1. Nothing happens on the page
2. A 'Uncaught TypeError: Cannot read property 'apply' of undefined' error is thrown in the console

The full stack trace for the console error is:

Uncaught TypeError: Cannot read property 'apply' of undefined
    at registry.js:54
    at Registry._resolveRequest (registry.js:413)
    at Registry._addRequest (registry.js:380)
    at Registry.get (registry.js:224)
    at async (registry.js:53)
    at UiClass.applyAction (button.js:72)
    at Array.forEach (<anonymous>)
    at UiClass.action (button.js:50)
    at HTMLButtonElement.<anonymous> (knockout.js:3863)
    at HTMLButtonElement.dispatch (jquery.js:5226)

I traced it out and what is happening is there are two UIClass objects on the page with the same 'ns'=>'product_form' and 'index'=>'options' properties.  This is occurring because the 'Options' attribute group we just created was given the attribute group code 'options' and that attribute group code appears to be the value that's used for the 'index' key in the resulting UIClass object.  If we go back and delete the 'Options' group out of the attribute set, the button goes back to working like it should.  I also tested out just renaming the group; however, it appears that the attribute group code is only set when the group is created.  So changing the name later won't update the attribute group code.

**Comment by magento-engcom-team** [comment]
@mikelevy300, thank you for your report.
We've created internal ticket(s) MAGETWO-82893 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to the 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @mikelevy300. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1359 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 1db3f8f6a336026d4a4493c8ba8d3e165ade66d8
 - 412d2287ee5a1a9620fb2a256bab562bdd10fe49
 - 02620b09456d77408ccbbd6a6b61a7b7ebcf73fa
 - 57c5d8a819e403905bd4d5419564d184712bc142
 - 94a3f0346ea086626d8b11c08fd397b11a570caa
 - 0d557dc99c15c6638e1c894ce46cb681a74b8912
 - 48baf590f86590c44bba81a9d5303902aed9d8d7
 - dc3bb78962c4522eb5df8a1a8f40c3bbe2b623fc
 - 0ab45334ef4d44e55c9f84f9c6e4b6a9e08e9237
 - 00f64b077ce00e55216e6ea9fb39071dc74b51a1
 - 440a1b5f9e6309fa87790a5f5b7d1b8fd7ffa53d
 - 4ed8f5b65d5d1779522653102120917c5f9578be
 - 656eeb5587eb1baebaffdc8ba68f1028afda8910
 - fd2f731f7efc4a2cec9e03f8de88bf39c0988829
 - 2c1a23faa60805bd63ff62216309d57a052612d1
 - f7ff71a92bcf56679b82c22549244e1adb9f4ed2
 - ac9bcfa15b1b0b98f9cb3851f4d9b56e18ede89b
 - 55debe0c2b514e37271ed6edf20b95fec6cc41c9
 - 349508628dc1c4334e13b3541227505e26c93c64
 - d678f1568b6e2d30c6d651dd3da02e0f3512353e
 - bf8ee3089f005e267f0b14cf81b14e9a3ee26986
 - 335c91c07dde6f90309f11cf0efcbd9127630955
 - c5a823f95161f7c13fb0947abb445fdc9e9a620a
 - 696a5a575513bb87c47ffc15a571034b0b91d7ae

The fix will be available with the upcoming 2.3.0 release.
