### ISSUE TITLE
Magento2.2.0 home page product grid issues

### ISSUE THREAD

**Issue by losetemp** [magento/magento2#11796]
Magento 2.2.0 with sample data
![20171027154814](https://user-images.githubusercontent.com/11692688/32093346-8573cfbe-bb2e-11e7-869c-518bc69106f8.png)
![20171027154736](https://user-images.githubusercontent.com/11692688/32093347-85b750ae-bb2e-11e7-84b0-e2e06c34e326.png)
![20171027154659](https://user-images.githubusercontent.com/11692688/32093348-85f531e4-bb2e-11e7-821b-996b77988b85.png)

**Comment by magento-engcom-team** [comment]
@losetemp, thank you for your report.
We've created internal ticket(s) MAGETWO-82879 to track progress on the issue.

**Comment by victor-martinez87** [comment]
Can I get this ticket please? #mmes

**Comment by victor-martinez87** [comment]
I've been having a look into this ticket, and I can't see this grid problem on Luma Template. As far as I know your screenshots looks like you are using "2-columns-right" template" and the layered navigation or static blocks are not showing there, witch in this case, could be a catalog reindex problem.

Solution:
- if you are trying to avoid this white space, change your template to 1-column
-if you are trying to show the filters there (Layered navigation) try a full reindex using the shell  cmd-> "php bin/magento indexer:reindex" on your root of Magento.


<img width="975" alt="screen shot 2017-11-05 at 12 26 26" src="https://user-images.githubusercontent.com/24246899/32414371-4eb90874-c225-11e7-836f-d144d2df1c20.png">

**Comment by losetemp** [comment]
Hello, thanks for your help, but this issue is in home page with widgets, you can install the magento 2.2.0 with sample data and you will find the columns wrong in some mobile test.

**Comment by magento-team** [comment]
Hi @losetemp. Thank you for your report. 
The issue has been fixed in magento/magento2#13081 by @punitv in 2.2-develop branch
Related commit(s):
 - 828352628c82ec94f24e11b9a0fc861d60cccf96
 - 1a407e6246ab3b5e7b2333b46364412df50f5bf7
 - c0d59a8e52bdb85b56bfa045875b48c55061e7ae
 - 6181457b10f4f442795f0ca134575378bec95e78
 - 15064d91e790dbb9ef230d4b4d05f1ae741214e3

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @losetemp. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1361 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 716f9afd694b6d7e5423bd2dbdabeeb45797886b
 - 595527a919eafd309f8b2a1d1339b312f6546f7b
 - 8c05a29b711ca03ecb866fc384122b3e46c08ccd
 - 63958cdc14bf3b44ad5fd95aafc626d8e25ca3e3
 - 78c2c2159b6c5aacc27e4fc918a1ed56a9df9b5f
 - 7f2dc2965a2d46e935770a7acdef8f260bd5fdc6
 - aee74586a9d28c1f47fd2ba3bae5e5871b779be9
 - 92f85860ce9725e34922a523e5137e656322c394
 - bf178ca5c3c10a50e3eba6e64fdf905e75d0b4c5
 - ecafa804c26054499b42c6820f0996035eb39dbc
 - a15208e96c06248d740ee65d154eda30226c848a
 - 76716b84a92f009253039cd06b9e47367384655f
 - 490785fffd885f85a7292c9144783cf2576b6b66
 - 6fe62802f5a529cd113697df79021bdb1dda9f53
 - 33e40ece8246363429be614440622600394a4516
 - 7b1bec8edb2eedea399eb78f891f1d6873cb1955
 - dbe5fc792279802f83d7110285c15fb2eede8d95
 - 22c6937f6db6a2ed17188f24097e0f9a194dc295
 - ca7da3fd58edca05b70a2af1768743ffc0294b72
 - b55a5d1a497279f72735e577ba60327dba178b6e
 - 65b745f7a94b2ba699a68f2825a63c9d78615f1c
 - b0a5a52df60a765748f15a7e0391f6b50535de21
 - 97dd9ad59c7d6bf9d4cf673a8e22708c480b1967
 - aa28366cc7378a972497e186fa8fb955684f74aa
 - 0fc86d89ab491fe7fc246d025662658844cd15a4
 - f11994acc1e220eb620d3baa63da8427d53e5797
 - 04445d07887870ba47dd2e97006c94d656f85942

The fix will be available with the upcoming 2.3.0 release.
