### ISSUE TITLE
Create order (on Customer edit page) - not working from admin environment

### ISSUE THREAD

**Issue by psbhanu** [magento/magento2#11832]
**Getting Fatal error while trying to access create order page from Customer edit screen.** 

`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Wishlist\Interceptor::getItemPrice() must be an instance of Magento\Catalog\Model\Product, instance of Magento\Wishlist\Model\Item given, called in /home/psbhanu/public_html/subdomains/ishop/vendor/magento/module-sales/view/adminhtml/templates/order/create/sidebar/items.phtml on line 73 and defined in /home/psbhanu/public_html/subdomains/ishop/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Sidebar/Wishlist/Interceptor.php:280 Stack trace: #0 /home/psbhanu/public_html/subdomains/ishop/vendor/magento/module-sales/view/adminhtml/templates/order/create/sidebar/items.phtml(73): Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Wishlist\Interceptor->getItemPrice(Object(Magento\Wishlist\Model\Item)) #1 /home/psbhanu/public_html/subdomains/ishop/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/psbhanu/p...') #2 /home/psbhanu/public_html/subdomains/ishop/vendor/magento/framework/View/Element/ in /home/psbhanu/public_html/subdomains/ishop/generated/code/Magento/Sales/Block/Adminhtml/Order/Create/Sidebar/Wishlist/Interceptor.php on line 280`

### Preconditions
1. Magento version 2.2.0
2. PhP version 7.1.9
3. Apache version 2.4
4. MySQL version 5.6.36

### Steps to reproduce
1. Login to Admin Panel
2. Navigate to Customers -> All Customer
3. Edit any customer
4. Use top Action - Create Order 

### Expected result
1. It should display Create Order screen correctly.

### Actual result
The Create Order page displaying above FATAL error and due to the same, page (and css/js etc) has not loading completly.
1. Screen Print - [megento_admin_customer_create_order_fatal_error.png](http://images.psbhanu.com/megento_admin_customer_create_order_fatal_error.png)

**Comment by magento-engcom-team** [comment]
Hello @psbhanu. Thanks for reporting. Can You reproduce Your issue on a fresh Magento 2.2.0 instance?

**Comment by magento-engcom-team** [comment]
Sorry for needlessly disturbing You @psbhanu. We've just managed to reproduce Your issue. Soon our internal ticket will have been created.

**Comment by magento-engcom-team** [comment]
@psbhanu, thank you for your report.
We've created internal ticket(s) MAGETWO-82981 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by fwolfst** [comment]
Gosh we have this too. The workaround (delete wishlist of customer) is expensive. Thanks @RomaKis  for the PR, we will look into patching our installation. @okorshenko Do you know about plans to transparentize the release schedules? Or specifically for 2.2.2 ?

**Comment by okorshenko** [comment]
Hi @fwolfst most likely the fix will be a part of 2.2.2 release

**Comment by fwolfst** [comment]
@okorshenko Thanks for the reply! Any guess whether 2.2.2 will be there before christmas?

**Comment by fwolfst** [comment]
@okorshenko Okay, got update and confirm fix.

**Comment by magento-engcom-team** [comment]
Hi @psbhanu. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1289 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - b41594122f532f6a89165a70906a5b257562c0df
 - 7369261d82e0e5ad926eaf4ccb2a8def79c4fcbb
 - dce1c66301cdddfee2dc2887f584c333d0b438b2
 - 95ed67ee4adbbd7f3f0107a52da4b9238cf44803
 - 05fcdd1a52c674ea09a34960cea71e73488fbc99
 - 8b1a2972b3f0ddd4713d00055b8d60f737a72ce4
 - 90addb731c3b253d3da4dc564ddf94ac3525bd0f
 - d5c9eef075cd5f4d9781ec7f3151a14e087d061d
 - 6ec62717c16ed96d45e670d7f867b724f0449aaa
 - f0af87edad79b295b4be87f6f92502bacfbc2764
 - 2497062749bf41c80aaebb9b6cd21eb48656f58c
 - 1f7347f47cca48238f9deabd48a0a280bc0c309f
 - 0d151c41539ba7c4d20ede20d614bb4be257903c
 - 07982fdea19074788654c6e825874cb8188ab627
 - 617da6ca08607890779ce71530a2871438c88351
 - 39ed21f83071ebffd71963e9097ecb59fd906702
 - 9aa036dec42211867f68f714a746b71395c43bb2
 - fda37ef0af75e6b28d4a0da1781b19c7a7894a97
 - 47b109180b6b5e499ba8d82e6c67888fca21ffe8
 - ef6badace5c6b046047a6e5f617020f9d4410a82
 - 809ec050986fa3ddfeec4a715ce5ace1e41a4427

The fix will be available with the upcoming patch release.
