### ISSUE TITLE
"Add Products" button has been duplicated after the customer group was changed

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#11868]
### Preconditions

1. Magneto 2.2.0 and previous versions

### Steps to reproduce

1. Login to admin panel
2. Go to: Sales - Orders - Create New Order
3. Select existing customer or create new
4. Change customer group

### Expected result

1. Button "Add products" ("Add Products", "Add Products By SKU" on EE) should not duplicated.

### Actual result

1. Button "Add products" ("Add Products", "Add Products By SKU" on EE) has been duplicated.
2. https://goo.gl/NZPTDJ

**Comment by magento-engcom-team** [comment]
@OleksiyOleksiyovych, thank you for your report.
We've created internal ticket(s) MAGETWO-82975 to track progress on the issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-83174

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release

**Comment by magento-engcom-team** [comment]
Hi @OleksiyOleksiyovych. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1285 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - ad6c0af7dddbe2855a336acd3fd55994851e6d26
 - 6d3d70a72f08cba36c3aef6b59eea8db40eb4071
 - 6b0c02c5fd00d7a4237c4e1fae40dc265e3e43c3
 - c8abb139f8006826989fe4231dabc21fd4a02fd0
 - c6a9b5f7b13554958b547f387637c4288eb60b0b
 - c867b81af936e01a3d8ba8baa7128de06a5b7cd5
 - 88a3ad00d3ca97da847531c86bf64055dc1d790b
 - d87e316a2d6ee55debe2e712359adba8cb70fdb2
 - c76b04c9acde117c1021270500c8ded6954f6f05
 - 5ae21099aaa19699525c798f9ac0ef10db47b311
 - 931133abf574f1db96450f11f5980ef359d32967
 - 4c927a0585f11921c5e422b7e4a15b787e6338bd
 - 060a8f9f2b08ed97b31667eb76cace1dc0e642be
 - 4da2a7d2657b0da67f8be43bffc85f04b5b7144e
 - 008ef5583892d73c04628f003a2ce3d97fe0ed72
 - d3642e88d26a9240a1a4d648d37d984a785672a9
 - d37ce089d56c230f5896d5d7e922bd928b3726e6
 - b22b232563359f9cbcbf09709e63a87be7e81446
 - 6c02a2d3a272e872d549881d91ed6d5235a33f77
 - f2ec2ea175469636acec0bf9f65f0601854f89a2

The fix will be available with the upcoming patch release.
