### ISSUE TITLE
Magento 2.2.x Grid Not Working.

### ISSUE THREAD

**Issue by sbwcws** [magento/magento2#11881]
Install Magento2.2.0 
PHP 7.01

For some reason Order, Customer, Products Grid are not working they do have a waiting circle move but after a second I see no display and its just white page.

I've over 20K Orders, 40K Customers and only 1K Products.

**Comment by sbwcws** [comment]
Please see screen shot. I've over 20K Orders, 40K Customers and only 1K Products.


<img width="1431" alt="sbpic 4" src="https://user-images.githubusercontent.com/7937555/32212607-010315ce-bdee-11e7-8f67-c44d590027c1.png">
<img width="1432" alt="sbpic 3" src="https://user-images.githubusercontent.com/7937555/32212608-010ff118-bdee-11e7-924f-697ff142a5c3.png">

**Comment by magento-engcom-team** [comment]
Hello @sbwcws, thank you for your report! Are there any additional settings that you have on your Magento? Or just the big about of data?

**Comment by sbwcws** [comment]
Able to solve it after re index and disabling Google page speed it's not a bug I apologize

**Comment by magento-engcom-team** [comment]
@sbwcws, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
