### ISSUE TITLE
M2.2 Autogenerated code doesn't work with the self PHP7 return type

### ISSUE THREAD

**Issue by bgorski** [magento/magento2#11905]
It looks like the autogenerated code doesn't work when methods in the class for which it's created have a `self` PHP7 return type (not the phpdoc `@return`). In Magento 2.2 there's one class which methods are marked as returning `self` - `\Magento\Indexer\Model\Indexer\DependencyDecorator`. 

### Preconditions
1.  Magento 2.2 (either Community Edition or Commerce, doesn't matter)

### Steps to reproduce

1.  Create a simple module with a plugin for `\Magento\Indexer\Model\Indexer\DependencyDecorator` (which will force Magento to create an Interceptor class for the DependencyDecorator class)
2. Run `bin/magento setup:upgrade`

### Expected result
1. `bin/magento setup:upgrade` ends with no errors

### Actual result
1. `bin/magento setup:upgrade` ends with the following fatal error: `Fatal error: '\self' is an invalid class name in [path to M2]/generated/code/Magento/Indexer/Model/Indexer/DependencyDecorator/Interceptor.php on line 137`

I saw the issue appear for an Interceptor class, but I guess it will appear for any autogenerated code that copies code from its parent class - so proxies as well.

**Comment by orlangur** [comment]
Will it work for `$this` return type?

**Comment by bgorski** [comment]
In my initial post I forgot to clarify that I mean the PHP7 return type just after function head, not the phpdoc's `@return` - sorry!. Just edited my previous message to clarify that.
It will work for phpdoc's `@return $this` as it will not translate it to a class name in the autogenerated code to a PHP7 return type.

**Comment by magento-engcom-team** [comment]
@bgorski, thank you for your report.
We've created internal ticket(s) MAGETWO-84148 to track progress on the issue.

**Comment by ihor-sviziev** [comment]
Hi @engcom-backlog-nazar,
Looks like this issue should be fixed by https://github.com/magento/magento2/pull/19398 in 2.2-develop, as it's backport - it should be also fixed in 2.3-develop.
Could you check if this issue wasn't fixed?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @bgorski Hi @ihor-sviziev yes described steps not reproducing on 2.2-develop and 2.3-develop branch. Can we close this issue as this was fixed in ->https://github.com/magento/magento2/pull/19398 ?

**Comment by ihor-sviziev** [comment]
Hi @engcom-backlog-nazar,
Thank you for checking. I'm closing this issue
