### ISSUE TITLE
Advanced Price not showing in a Configurable Product in Magento 2.2

### ISSUE THREAD

**Issue by mnuhell** [magento/magento2#11900]
### Preconditions

1. Magento 2.2
2. PHP 7.0

### Steps to reproduce

1. Configurable product not have advanced price Options

### Expected result

1. I read that in the Magento 2.2 version the option advanced price would be added in configurable product?

### Actual result

1. the option does not appear in the configurable product

In the documentation [http://docs.magento.com/m2/ce/user_guide/catalog/product-create-configurable.html](url)
Step 4: Complete the Basic Settings
An image appears showing the advanced price in what is supposedly the configurable product.

Thanks.

**Comment by magento-engcom-team** [comment]
@mnuhell, thank you for your report.
You can add Advanced Price for Configurations afte generete a products, not for parent Configurable product

**Comment by magento-engcom-team** [comment]
@mnuhell, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by mnuhell** [comment]
Ok, I thought it was already implemented. 

thanks so much
