### ISSUE TITLE
setup:di:compile's generated cache files inaccessible by the web-server user

### ISSUE THREAD

**Issue by JanisE** [magento/magento2#11930]
### Preconditions
1. OS: Linux Mint 18.2 (based on Ubuntu Xenial).
2. Magento CE 2.2.0 with sample data is installed by Composer.
3. Permissions and ownership set up as instructed on http://devdocs.magento.com/guides/v2.1/install-gde/prereq/file-system-perms.html#perms-private for two-user system (users "magento_user" and "www-data").

### Steps to reproduce
1. Run `bin/magento setup:di:compile` as Magento file system owner ("magento_user").
2. Open the web site.

### Expected result
1. Web site opens.

### Actual result
1. `var/cache/*` folders lose their set-gid bits.
2. `var/cache/mage-tags/*` folders are created with "magento_user"'s primary group and 660 permissions.
3. The web user ("www-data") fails opening the site because it cannot access this content:
```
1 exception(s):
Exception #0 (Exception): Warning: file_put_contents(/var/www/m2training/public/var/cache//mage-tags/mage---762_COMPILED_CONFIG): failed to open stream: Permission denied in /var/www/m2training/public/vendor/colinmollenhour/cache-backend-file/File.php on line 663
```

The problem was reported also in this StackExchange question: https://magento.stackexchange.com/q/193727/60128

**Comment by magento-engcom-team** [comment]
@JanisE, thank you for your report.
We've created internal ticket(s) MAGETWO-83148 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @JanisE. Thank you for your report. 
The issue has been fixed in magento/magento2#14361 by @xtremeperf in 2.2-develop branch
Related commit(s):
 - [9baa83fca8a97fe4c0e02557246bdd6069a50b27](https://github.com/magento/magento2/commit/9baa83fca8a97fe4c0e02557246bdd6069a50b27)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @JanisE. Thank you for your report. 
The issue has been fixed in magento/magento2#14416 by @xtremeperf in 2.3-develop branch
Related commit(s):
 - [87ad6ebbfcf4ed1585a1f4c26603cc2676e72f26](https://github.com/magento/magento2/commit/87ad6ebbfcf4ed1585a1f4c26603cc2676e72f26)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @JanisE. Thank you for your report. 
The issue has been fixed in magento/magento2#14417 by @xtremeperf in 2.1-develop branch
Related commit(s):
 - [e57745874027ba0779c6614d6739b4f0a89f3d2b](https://github.com/magento/magento2/commit/e57745874027ba0779c6614d6739b4f0a89f3d2b)

The fix will be available with the upcoming 2.1.14 release.

**Comment by keharper** [comment]
@JanisE does the documentation need to be updated as a result of this fix?

https://devdocs.magento.com/guides/v2.1/install-gde/prereq/file-system-perms.html#perms-private

**Comment by JanisE** [comment]
@keharper , no, not as a result of this fix.

Although I'm probably not going to check if it actually fixed the problem for me, at least not any time soon.
