### ISSUE TITLE
required attribute set id filter on attribute group repository getList

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#11936]
### Preconditions

1. Magento 2.1 or 2.2 (probably reproducible on earlier versions)

### Steps to reproduce

1. Try calling `Magento\Eav\Model\Attribute\GroupRepository::getList` with a `\Magento\Framework\Api\SearchCriteriaInterface` parameter that does not contain a filter for `attribute_set_id`

### Expected result

1. I Should get as response the list of attribute groups based on my search criteria

### Actual result

1. I get a `Magento\Framework\Exception\NoSuchEntityException` with the message `No such entity with %fieldName = %fieldValue`.

### Additional info:
Full description and code can be found here https://magento.stackexchange.com/q/195740/146  

The exception happens because the `getList` method of the GroupRepository requires a filter on `attribute_set_id`: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Eav/Model/Attribute/GroupRepository.php#L120-L128  
I don't really see the need for this. The repository should let me retrieve the groups as I want to. 

If I'm wrong, please explain the reason, if I'm right, just tell me and I'll come back with a PR.

**Comment by orlangur** [comment]
It reminded me https://github.com/magento/magento2/issues/7847 a bit :)

You can see from `getList` and `save` methods of `GroupRepository` implementation that it is not intended to work without attribute set. Just because attribute group is a sub-entity of attribute set and if you want to manipulate attribute groups directly without relation to attribute sets, you would break encapsulation (it's like managing attribute values of multiple products without relation to products).

So until new persistence layer is implemented https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/EntityManager/EntityManager.php#L24 is your best option. You can also implement your custom `GroupRepository` removing all the attribute set checks but there is nothing to "fix" in core.

**Comment by tzyganu** [comment]
@orlangur  I see where this is going but I don't really agree with your reasoning.  
Having a 1 to many relation and managing the entities involved in the relation does not necessarily mean I'm breaking encapsulation.  
Why isn't the same logic applied to the ProductRepository? I mean, Attribute Set is the parent entity for the products. Why isn't there a mandatory filter on attribute_set_id for the product repository getList method?  
Why isn't there a mandatory filter on order_id for InvoiceRepository or better yet, a mandatory filter on the Invoice/ItemRepository::getList() for invoice_id.  
I'm sure that "if you want to manipulate invoice items directly without relation invoices you would break encapsulation" (quote adapted from your reply),

I suggest reconsidering or asking for a second opinion.

**Comment by maghamed** [comment]
Hey @orlangur and @tzyganu , it's a pretty interesting question you raised here.

Here is what I think about this:

1. API **must** be self-descriptive.  A client of the API **should not** look at the implementation details to understand how does API work. It's enough to see Interface declaration to get a clue how to use API.  Current interface of the [AttributeGroupRepositoryInterface](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Eav/Api/AttributeGroupRepositoryInterface.php) does not imply any limitations on its usage. One can't see that all the manipulation with Attribute Groups should be done in the **scope** of the specified attribute set.
2. Attribute Group from Magento point of view is not a sub-entity of Attribute Set. Attribute Group exists in the scope of the Attribute set. Which is different to what you @orlangur described. For example, Magento Products also exist in the scope of some Website, but they don't belong to the Website Aggregate Root (in DDD terms). Magento interfaces proof my words because Magento provides independent Repositories (aka ways for manipulation) for both AttributeSet and AttributeGroup. If Magento considered that AttributeGroup is a sub-entity of Attribute Set - it would not provide an ability to manipulate Attribute Group independently out of Attribute Set.
3. If some entity supposed to be manipulated only in pre-defined scope - it should be clearly represented in its contract. For example, that's how we do that for MSI 
[GetProductQuantityInStockInterface::execute(string $sku, int $stockId)](https://github.com/magento-engcom/msi/blob/develop/app/code/Magento/InventoryApi/Api/GetProductQuantityInStockInterface.php#L24) where `$stockId` is a required argument which defines a *scope* for current operation.
4. Also, you can't consider retrieving of all Attribute Groups which are assigned to different Attribute Sets as a violation of encapsulation because you still can get the same result with several `getList` calls applied to a different attributeset_id filter. 

Based on all the above, I consider that proposal of @tzyganu makes sense, thus I reopened the issue.

**Comment by orlangur** [comment]
Started to reply on that issue that day with intention to reopen, maybe will find that comment in some other tab.

`ProductRepository` or `InvoiceRepository` are irrelevant as invoices and products have perfect sense be themselves.

On the other hand `AttributeGroup` has no sense in core without `AttributeSet`. Just like, as far as I know, we don't have a repository to manipulate categories to products relations separately.

> Attribute Group from Magento point of view is not a sub-entity of Attribute Set. Attribute Group exists in the scope of the Attribute set.

@maghamed, please provide an example in core where attribute groups are manipulated directly.

As I mentioned previously, existing implementation of `GroupRepository` cannot be changed as existing third party code may rely on such validations, another repository could be created for direct manipulations, but I don't see how it would be useful in core. Using resource models for such direct manipulations is the best option until we have a new persistence layer.

**Comment by tzyganu** [comment]
@orlangur You don't need an example from the core. The service contracts don't serve only the core. It should serve my needs also. 
And here is what I need.  
I have one requirement that all attribute groups called "This is my Group" should be renamed to "This is NOT my group" (names are fictional).  
I can let the admin do that for all 54 attribute sets manually, but this will only solve it for the live env. 
But the groups are generated via an install script so I thought about making it in the proper magento way and have an upgrade script for it in which I retrieve all the attribute groups with a certain name, change them and save them.  
Guess how I'm doing it right now....
I get all the attribute sets, then loop through the results, pass the attribute set id as a filter to the group repository and make 54 queries when I could make 1 to retrieve the data I need.  

I know I could use the `updateAttributeGroup` method from the EavSetup class, but that one takes a `setId` parameter also.

Does this make sense?

Also the GroupRepository can be changed in this case... all other third party implementations that depend on it will still work. Having a filter on attribute set it will still remain  valid filter. The signature is not changed.

**Comment by orlangur** [comment]
That's absolutely clear from the SO question.

> Please don't suggest calling `getList` for each attribute set (I have a lot of them so a foreach is not a nice solution). 

As far as I understand main concern here is performance and "lack of joins" is a common problem for current service layer. If we start changing implementations that way, not considering usefulness for core, than every real-world application would request "I need to do it in only one query!!!".

I don't see why resource models are bad for the case described.

**Comment by tzyganu** [comment]
@orlangur resource models and collections would work, but I'm trying to build my code the proper magento  way. If there is a repository I use it.

**Comment by orlangur** [comment]
> If there is a repository I use it.

And now there is no ready-to-use repository. Does it mean that in every such situation repositories functionality should be expanded?

**Comment by tzyganu** [comment]
@orlangur I don't know about every repository, but in this case I think I should. it's an easy fix and the impact should not be big.

**Comment by maghamed** [comment]
>As I mentioned previously, existing implementation of GroupRepository cannot be changed as existing third party code may rely on such validations

Current changes proposed by @tzyganu are **backward compatible** and could be done in the scope of existing Attribute Group Repository implementation.
There could not be a situation where we would break existing code.
All that we do is changing required filter parameter (attributeSetId) and making it optional.
Thus, currently, all the existing code pass sttributeSetId into the Search Criteria filter - and that would be supported after the changes proposed along with providing the new possibility of extracting AttributeGroups assigned to different attribute sets.

>another repository could be created for direct manipulations

we don't recommend to introduce new APIs for replicating the functionality we already have in the code. Because that would duplicate extension/customization points for Extension developers

Based on the above, @tzyganu feel free to create Pull Request with proposed changes and we would process it.

@orlangur if there are other open questions I propose to discuss them in Slack and not to overwhelm this thread.

**Comment by orlangur** [comment]
@maghamed are you referring to `getList` implementation only or `save` or any other method with attribute set-related logic shall be changed too?

**Comment by maghamed** [comment]
About getList only. Regarding save - it's okay to prevent saving an AttributeGroup when attribute set id is not set, considering it as a required attribute.

**Comment by magento-engcom-team** [comment]
@tzyganu, thank you for your report.
We've created internal ticket(s) MAGETWO-84043 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento/magento2#12105 by @tzyganu in 2.2-develop branch
Related commit(s):
 - 433c3cd97c327b6130fa34ad2aad15659facafe3
 - 7be92a872300f949d349e442c3d8e1045609d8b1

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1298 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 54301a8ea63134b961d6b7b9891c31bc2798f8dc
 - 402b719168fc8b17ebc099c12b85f629cf90303b
 - 3837f2780b32112b7f70a9d3074158ee2336b1b7
 - 031e23e93ffaa258a39dfed5c5edb0e873ab0aa8
 - aa267f462f7eb964226a9c89d20c04b718406337
 - 934818dbee0bd36ec5eae7b3b7230c4d8a70b481
 - 6bed7d475bff5e98e27b8fdcaa998438bc31ed05
 - 72b2794043afd0012f9a8d5f6fc04df07acad3af
 - 4e64c415e26845826b527c17008eda00d3808591
 - d3feb280ed621c5ffe2dc3a2b7ac30abb25d9c22
 - 7aeccea46d2336a1322811a9d60d52432108c8e3
 - b857c022ae1cdb7975cf5c3d79cd679843c72a3b
 - a75bf2391dfc6e7c8a1283490f5de7551de42bbe
 - ab2e5798e529633f770c3970a0df999c11764e06
 - d904690443d43322c5dd2c58d075944eae867316
 - a821c7a3c17eb06983f421c47a7cc0fe99983a38
 - 68ac4c0bd6cae6b5b62e683c23f49293ee41d797
 - 93fe4d14faba635cc7c668b2d931e7595567cda9
 - f43fd4b98c55e1f498d060aeb245e4c969bdcb13
 - 2c52a8fd15cff7af7245573e2f26be6d601acb08

The fix will be available with the upcoming 2.3.0 release.
