### ISSUE TITLE
About I/O Usage in magento2.2

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#11948]
### Preconditions

1. in magento2.2
2. php7,1

### Steps to reproduce

1.  when I'm using an administrator,my server I/O Usage is very high,and then can't open the page.need to restart the server

### Expected result

1. How to solve this issue?

### Actual result

1.  I/O Usage so high

**Comment by victor-martinez87** [comment]
I do recommend to install "htop" on the server and check what process it's consuming all the performance.

Maybe it's a cron, maybe it's something else

**Comment by onepack** [comment]
We had the exact same issue. Maybe my feedback can help.
We had:
PHP 7.0
Magento 2.2

I decided to upgrade to the latest magento 2.2.1 version in the hope this was a bug in the release and the upgrade would make things right.
What I found out during the upgrade process is that all caching seemed enabled in the backend the var/cache directory was empty! There was no file or directory. Weird is caching is enabled!
This explained the high I/O load and from time to time high CPU peaks.

After the upgrade to 2.2.1 and also the PHP upgrade to 7.1 I noticed that in the magento backend the caching had the status disabled (red) and I could not enable it from there.
I enabled it now from cli and since these steps the high I/O usage is gone and the cpu load is much lower.

I'm still monitoring the vps now but all seems better now.

**Comment by andy17612** [comment]
@onepack @victor-martinez-interactiv4 
i will try to upgrade to the latest magento 2.2.1 version , hope can better.
update to you when i upgraded,thank you

**Comment by onepack** [comment]
We have result now from today's ugrade and it didn't help a bit. At first it was super fast but after one hour it crashed again we are three crashes further now with a frustrated client. Will search further and let you know.

**Comment by onepack** [comment]
Ok, fixed. Please go and check your database cron_schedule table.
It might be that this one is full. (over 100 pages). In our case 9000+ pages of jobs pending!!
Truncate and it will fill-up itself again and check that the crons are successfully processed.
This was the issue with us and the server is now fine again.
We are now looking for the reason but I think it was something from the past as all jobs get cleared now like they should.

**Comment by andy17612** [comment]
@onepack 
I don't know why i in admin > setup upgradd >Update application is running ->will be show error upgrade. Did't suggest anything wrong?

Update application is not running

Error in Update! 
Please refer to documentation Doc link to perform manual rollback.

To attempt automatic rollback, please click the "Rollback" button.

[Module 'Magento_******':
Running schema recurring...Source class "\SignifydAvsDefault" for "SignifydAvsDefaultMapper" generation does not exist.

[2017-11-10 11:19:32 UTC] Job "setup:upgrade {"command":"setup:upgrade"}" has been successfully completed
[2017-11-10 11:19:32 UTC] Job "setup:static:regenerate []" has started

[2017-11-10 11:19:32 UTC] Cleaning generated files...
[2017-11-10 11:19:32 UTC] Clearing cache...
[2017-11-10 11:20:12 UTC] Cleaning static view files
[2017-11-10 11:20:12 UTC] Job "setup:static:regenerate []" has been successfully completed
[2017-11-10 11:20:12 UTC] Job "setup:maintenance:disable []" has started
Disabled maintenance mode

[2017-11-10 11:20:12 UTC] Job "setup:maintenance:disable []" has been successfully completed]([url](url))

**Comment by magento-engcom-team** [comment]
Hi @rigu12 
If your server I/O Usage is very high, you can change Index mode to "Update by schedule".

**Comment by magento-engcom-team** [comment]
@rigu12, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
