### ISSUE TITLE
Unable to explicitly set In Stock/Out of Stock for qty = 0

### ISSUE THREAD

**Issue by J-Fricke** [magento/magento2#11942]
v2.1.9
When editing a product with a qty set to 0 setting `Stock Status` to:
* 'In Stock' with Managed Inventory on 
or 
* 'Out of Stock' with Managed Inventory setting disabled

Always defaults back to the opposite value.

Expecting the input value selected to actually save as selected.

We have need of some products going out of stock while others simply become Available as drop ship orders when inventory levels are 0. Seems like the user should be able to select an option or the box should be disabled for user input.

**Comment by magento-engcom-team** [comment]
Hello @J-Fricke. Have You tried to use Advanced Inventory functionality (under the quantity field on the product page in admin). It doesn't change the logic in the whole (e.g. the product with qty=0 is always In Stock when Inventory is on and always out of stock when Inventory is off), but You can turn Inventory on/off separately for each product. Please let us know if this possibility would meet Your needs. Thank You.

**Comment by magento-engcom-team** [comment]
@J-Fricke, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
Also You may reopen the issue if You are not satisfied with all proposed above.

**Comment by J-Fricke** [comment]
@magento-engcom-team 
Thanks for the input. I found out that our issue was this product had `No Backorders` set in Advanced Inventory and was why we could not change the status manually.
