### ISSUE TITLE
Layer navigation showing  wrong product count 

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#11946]
Preconditions

Magento version 2.1.9
Enable out of stock display yes from backend

Getting errors -
Layer navigation count wrong due to Magento count only in-stock product.
https://github.com/magento/magento2/blob/2.1.9/app/code/Magento/CatalogSearch/Model/Adapter/Mysql/Aggregation/DataProvider.php#L115

Actual result:
count calculation based on backend stock setting.

**Comment by sunilit42** [comment]
It is also same for magento 2.2 version.

**Comment by magento-engcom-team** [comment]
@sunilit42, thank you for your report.
We've created internal ticket(s) MAGETWO-81624 to track progress on the issue.

**Comment by j-plou** [comment]
@sunilit42 Can't reproduce it in 2.2. Could you attach any screenshot or more details/steps on how to reproduce it?

**Comment by sunilit42** [comment]
Hello,
 Case 1) Go to Backend set Out of stock display No (Make sure some product out of stock)
Go to any category , check count of layer navigation of attribute

 Case 2) Go to Backend set Out of stock display Yes
Go to any category , check count of layer navigation of attribute, it will show same

It does not count out of stock product count into layer nav.

Check below file 

https://github.com/magento/magento2/blob/2.2.0/app/code/Magento/CatalogSearch/Model/Adapter/Mysql/Aggregation/DataProvider.php#L117

**Comment by versdivers** [comment]
Still an issue 9/12/2017 magento 2,2,1

**Comment by ishakhsuvarov** [comment]
Hi @sunilit42 @versdivers 
We are closing this issue now as the fix has been delivered with the commit 3839c0f and should be released with 2.2.4
Thank you.

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1297 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 21cfb6ab689b52d27dfe6816b27542f03ffbd73b
 - d173193c9612135a44d4f0490eef5995cb82c89f
 - b5a4ee42e65fec38b4d088335f44fbfd7e93c64c
 - f6570bd5d8e6b0767ce39f37d0355a5b61620638
 - b32bdc9a34247f33af0d7f2ed80868c55b1e5aae
 - 3c6d9bef7435b10fbf9570332ce27f6ceae9a7ac
 - d4c7ca0d4aeac15b8961e0e8a582fe716a088972
 - 07fa73aa7e698bc212ebeb65efbe558e49ac054a
 - 60426c6cd24c2f7d1881a27459a2a46628a81b3f
 - 14f85e9cd1f6c3349a5ce35c49c14e5772687d86
 - 72b399100b50ec9efaf437e800cd057631e4d9aa
 - 5483dc7045ea37787e3119770b2c737d9992bd06
 - f442a76b9f9225217004654154a57e585b8802e5
 - af9f7cbad96e82f56e093a9bfd70edf4e2296fde
 - 8b4ad902efc299e035ff9a93e58ae96513a686c1
 - 9354bb98941bff3a1675d893a27695ddd3ffe692
 - 9c9ed9153084a0c6acb16a6cea6932c117b2d26e
 - 4a422f65ce1d0a559cf1b4d1c477b32d11f54b6b
 - b6473f6924ca933702d5936628b4e51612ac8c90
 - 0c12a7aa9a5307263426a8b2bb93a97692cdd685

The fix will be available with the upcoming patch release.

**Comment by saiwingwu** [comment]
When could this fix be backported to 2.1.14?

**Comment by Wadekone** [comment]
@magento-engcom-team 
1. magento-engcom/magento2ce#1297 takes to 404. Any working link?
2. Any backport for Commerce edition?
