### ISSUE TITLE
Customer with empty "Date of Birth" cannot be saved

### ISSUE THREAD

**Issue by JanisE** [magento/magento2#11989]
Customer with empty "Date of Birth" cannot be saved even when it is not marked (or checked on the JS side) as mandatory.

### Preconditions
1. OS: Linux Mint 18.2 (based on Ubuntu Xenial).
2. Magento CE 2.2.0 with sample data is installed by Composer.

### Steps to reproduce
1. Sign up as a new user entering whatever name, e-mail, password.
2. In Admin go to Stores -> Customers -> All customers and click "Edit" for the created customer.
3. Go to "Account Information" and change "Group" from "General" to "Reseller".
4. Click "Save Customer".

### Expected result
1. Either the customer gets saved
2. Or
2.1. Account Information -> "Date of Birth" field is marked as mandatory;
2.2. "This is a required field." appears beneath "Date of Birth" if it is empty when saving.

### Actual result
1. The page reloads with an error message "Something went wrong while saving the customer.".
2. An error message gets logged in the "system.log" starting with `main.CRITICAL: Exception message: Warning: A non-numeric value encountered in /var/www/m2training/public/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php on line 94`

Locale info:
```
$ locale
LANG=lv_LV.UTF-8
LANGUAGE=lv_LV
LC_CTYPE="lv_LV.UTF-8"
LC_NUMERIC=lv_LV.UTF-8
LC_TIME=lv_LV.UTF-8
LC_COLLATE="lv_LV.UTF-8"
LC_MONETARY=lv_LV.UTF-8
LC_MESSAGES="lv_LV.UTF-8"
LC_PAPER=lv_LV.UTF-8
LC_NAME=lv_LV.UTF-8
LC_ADDRESS=lv_LV.UTF-8
LC_TELEPHONE=lv_LV.UTF-8
LC_MEASUREMENT=lv_LV.UTF-8
LC_IDENTIFICATION=lv_LV.UTF-8
LC_ALL=
```

**Comment by magento-engcom-team** [comment]
@JanisE, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by Blatant** [comment]
We have been able to recreate this issue using latest Magento ver. 2.2.1 (this mornings release) and Php 7.1.11. We can confirm it does not occur on PHP 7.1.8.

In our case the symtoms are slightly different as an empty DOB is allowed, however saving the customer with a blank DOB in the admin panel results in the above error message `main.CRITICAL: Exception message: Warning: A non-numeric value encountered in /var/www/m2training/public/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php on line 94`.

The issue is that somewhere along the save pattern the `PhpMath->Sub` method is called with 2 blank parameters (I guess there's a missing "if empty don't do any date logic" statement missing somewhere. The code changes the first parameter `$op1` to zero (0) but leaves the second one blank, then tries to subtract them resulting in the exception on the `$result = $op1 - $op2;` line. 

Excerpt magento/zendframework1/library/Zend/Locale/MathPhpMath.php Lines 80 -> 101

```
    public static function Sub($op1, $op2, $scale = null)
    {
        if ($scale === null) {
            $scale     = Zend_Locale_Math_PhpMath::$defaultScale;
            $precision = Zend_Locale_Math_PhpMath::$defaultPrecision;
        } else {
            $precision = pow(10, -$scale);
        }

        if (empty($op1)) {
            $op1 = 0;
        }
        $op1  = self::normalize($op1);
        $op2  = self::normalize($op2);
        $result = $op1 - $op2;
        if (is_infinite($result)  or  (abs($result + $op2 - $op1) > $precision)) {
            #require_once 'Zend/Locale/Math/Exception.php';
            throw new Zend_Locale_Math_Exception("subtraction overflow: $op1 - $op2 != $result", $op1, $op2, $result);
        }

        return self::round(self::normalize($result), $scale);
    }
```

**Comment by JanisE** [comment]
Re-created the issue at #12146.

**Comment by aishwaryasunarc** [comment]
I got same issue with magento 2.2.2 version. I fill all fields except date of birth and tried to save customer but my customer was not saved successfully it shows main.CRITICAL: Exception message: Warning: A non-numeric value encountered in /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php on line 94 error.
