### ISSUE TITLE
Old price excluding TAX is incorrectly replaced by JavaScript

### ISSUE THREAD

**Issue by VesnaS** [magento/magento2#11998]
### Preconditions

1. Tested on Magento versions 2.4-develop
2. PHP 7.2

### Steps to reproduce

1. In Admin, set Stores -> Configuration -> SALES -> Tax -> Price Display Settings -> Display Product Prices In Catalog to "Including and Excluding Tax"
2. Configure tax class and set it for the product
3. Set special price for the product
4. In vendor/magento/module-catalog/view/base/templates/product/price/final_price.phtml, set "skip_adjustments" to FALSE for "old-price"

### Expected result

1. On product detail view page in frontend, old price and new price are displayed with and without TAX 

### Actual result

1. New price and old price excluding TAX are the same. This happens because JavaScript in vendor/magento/module-catalog/view/base/web/js/price-box.js replaces prices incorrectly.

![old_price_bug_report](https://user-images.githubusercontent.com/33281361/32377643-a74d8f38-c0a8-11e7-8b82-b108828e507c.png)

**Comment by magento-engcom-team** [comment]
@VesnaS, thank you for your report.
We've created internal ticket(s) MAGETWO-83250 to track progress on the issue.

**Comment by joachimVT** [comment]
I can confirm this having the same issue on version 2.2.2

![schermafbeelding 2017-12-18 om 14 50 08](https://user-images.githubusercontent.com/1216688/34109136-f2a8de42-e402-11e7-80de-a2f5d70be900.png)

**Comment by MaximilianSchwarz** [comment]
I have the same issue in Magento 2.2.2. Is there any new information about this bug?

**Comment by HashDefineElectronics** [comment]
Hi All,

## My Issue
When the store is configure to allow both Include and Exclude tax to be display on the product page then the following happens to me.

On products with ***special price*** enabled, The
 special price value for excluding tax will be set to Old price excluding tax.
This is because the Excluding tax html element for Special price and Old price using the same price type. This means that price-box.js is unable to differentiate between prices when it loads.

![tax price issue](https://user-images.githubusercontent.com/13482395/40586846-a0f157f6-61bf-11e8-9a27-1379750e67a0.jpg)

Ideally, which ever code set the data-price-type for each of these element should also make sure that it take into account that when both tax types are displayed.

# The quick solution
My quick fix is to override the ***data-price-type*** value before price-box.js store the price options.

## Steps

- First copy **MAGE_ROOT**/app/code/Magento/Catalog/view/base/web/js/price-box.js to your theme or module. (ie **MAGE_ROOT**/app/design/frontend/VENDOR/YOUR_THEME/Magento_Catalog/web/js/my-price-box.js
- update the requirejs-config.js from your module: (**MAGE_ROOT*/app/design/frontend/VENDOR/YOUR_THEME/Magento_Catalog/requirejs-config.js)
```
var config = {
    map: {
        '*': {
               priceBox:'Magento_Catalog/js/my-price-box',
        }
   }
};
```
- Insert the following code into function ***_setDefaultsFromDataSet*** after line 191 in marv-price-box.js.
```
label = $(element).data('label')
if(type && label) {
    type += label;
}
```
It should look like this:
```

        /**
         * setDefaultsFromDataSet
         */
        _setDefaultsFromDataSet: function _setDefaultsFromDataSet() {
            var box = this.element,
                priceHolders = $('[data-price-type]', box),
                prices = this.options.prices;

            this.options.productId = box.data('productId');

            if (_.isEmpty(prices)) {
                priceHolders.each(function (index, element) {
                    var type = $(element).data('priceType'),
                        label = $(element).data('label'),
                        amount = parseFloat($(element).data('priceAmount'));

                    $(element).data('priceType', type + label)

                    if(type && label) {
                       type += label;
                    }

                    if (type && !_.isNaN(amount)) {
                        prices[type] = {
                            amount: amount
                        };
                    }
                });
            }
        },
```

**Comment by malikt** [comment]
Any solution to this issue?

**Comment by malikt** [comment]
i was able to do a quick fix for it, but it will be a good to have a better and permanent solution by the team.

**Comment by DanielRuf** [comment]
> i was able to do a quick fix for it

Can you show it for us?

**Comment by duckchip** [comment]
@magento-engcom-team Any news on this issue?

**Comment by melaniajitaru** [comment]
Hi,

This error also appears in Magento 2.3.3. Do you have any news on how to fix it? @magento-engcom-team 

Thanks.

**Comment by engcom-Alfa** [comment]
Reproduced on the fresh 2.4-develop instance

**Manual testing scenario:**

1. In Admin, set Stores -> Configuration -> SALES -> Tax -> Price Display Settings -> Display Product Prices In Catalog to "Including and Excluding Tax"
2. Configure tax class and set it for the product
3. Set special price for the product
4. In vendor/magento/module-catalog/view/base/templates/product/price/final_price.phtml, set "skip_adjustments" to FALSE for "old-price"

**Actual Result:**
New price and old price excluding TAX are the same.
![screen2](https://user-images.githubusercontent.com/51679138/71476471-f5a22c80-27ed-11ea-80f0-0ef12956a5bf.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30089` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @VesnaS. Thank you for your report. 
The issue has been fixed in magento/magento2#27832 by @Krielkip in 2.4-develop branch
Related commit(s):
 - [65c06eb13208f9f4fe851ae136e61fe5a06642e4](https://github.com/magento/magento2/commit/65c06eb13208f9f4fe851ae136e61fe5a06642e4)
 - [7f4b2766b8b068ca03595d0548e84ed94c47773b](https://github.com/magento/magento2/commit/7f4b2766b8b068ca03595d0548e84ed94c47773b)
 - [21ad13f6880fa6be86b18a993d38dbb18752916b](https://github.com/magento/magento2/commit/21ad13f6880fa6be86b18a993d38dbb18752916b)
 - [8f1020af9f5cca737bb24696769f7eb81958556a](https://github.com/magento/magento2/commit/8f1020af9f5cca737bb24696769f7eb81958556a)
 - [cfb762d664a2da0933ee1a6fc46deb684fc6eecd](https://github.com/magento/magento2/commit/cfb762d664a2da0933ee1a6fc46deb684fc6eecd)
 - [c6a43f3920d29c046ca7a097e520f30f72f14ac7](https://github.com/magento/magento2/commit/c6a43f3920d29c046ca7a097e520f30f72f14ac7)
 - [84124f74b55a88b09947f1fc561a4ad30ecdd07b](https://github.com/magento/magento2/commit/84124f74b55a88b09947f1fc561a4ad30ecdd07b)
 - [43b4f648a1efd0a24c668b2f80f34f7d60b6f649](https://github.com/magento/magento2/commit/43b4f648a1efd0a24c668b2f80f34f7d60b6f649)
 - [9fd54363ced22b9d627f0768cf1820d125468e80](https://github.com/magento/magento2/commit/9fd54363ced22b9d627f0768cf1820d125468e80)

The fix will be available with the upcoming 2.4.2 release.

**Comment by LeanderFS** [comment]
Reopening as the exact same issue also seems to be happening for tier prices. 

2 different cases where this bug occurs:
---
1. Set price display type to "Excluding tax"
2. Create a simple product and add a tier price (For example: 50 pieces for x amount)
3. Go to the product page and change the quantity selection box to 50
4. The price doesn't update as `updateProductTierPrice` in `price-box.js` expects `finalPrice` to be present in the `this.options.prices` object and only `basePrice` is available. (Throws JS error)

1. Set price display type to "Including and Excluding tax"
2. Same as the above step 2
3. Same as the above step 3
4. Only the price including tax updates to reflect the tier price, the excluding price will stay on the regular value.

**Comment by LeanderFS** [comment]
@magento give me 2.4.3 instance

**Comment by LeanderFS** [comment]
Reproduced on a fresh 2.4.3 instance.

**Comment by LeanderFS** [comment]
@magento I am working on this

**Comment by LeanderFS** [comment]
@magento add to contributors team

**Comment by Krielkip** [comment]
@LeanderFS nice found 👍  (I haven't used tier prices for this use case)

**Comment by engcom-Lima** [comment]
Hi @VesnaS,

Thank you for reporting the issue.

I have tried this issue on the fresh installation Magento 2.4-dev but I am not able to reproduce it.
Steps followed to reproduce the issue:

1. In Admin, set Stores -> Configuration -> SALES -> Tax -> Price Display Settings -> Display Product Prices In Catalog to "Including and Excluding Tax"
2. Configure tax class and set it for the product
3. Set special price for the product
4. In vendor/magento/module-catalog/view/base/templates/product/price/final_price.phtml, set "skip_adjustments" to FALSE for "old-price"

**Output:** On product detail view page in frontend, old price and new price are displayed with and without TAX
![Screenshot from 2022-02-02 19-03-39](https://user-images.githubusercontent.com/60198022/152164251-81a0d4ba-ca8f-4a80-9918-f70d6879cb50.png)

Kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps if the issue is still reproducible.
Thank you.

**Comment by Krielkip** [comment]
> 22 days ago

Hi @engcom-Lima ,
You need to follow the actions told by @LeanderFS .
See reply:
https://github.com/magento/magento2/issues/11998#issuecomment-1015392569

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @VesnaS 

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
Followed above [comment](https://github.com/magento/magento2/issues/11998#issuecomment-1015392569)

Kindly refer this [video,](https://shared-assets.adobe.com/link/8ef24e7d-0e44-4210-6fe3-954ce07c8dd6)If I am missing anything steps please provide information.
Please try to check in latest 2.4 develop branch with Php 8.1.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @VesnaS,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
