### ISSUE TITLE
Default trigger coupon via URL

### ISSUE THREAD

**Issue by seansan** [magento/magento2#120]
Hi - can we enable trigger coupon via URL in Magento 2?

http://www.drewgillson.com/blog/how-to-apply-magento-coupon-codes-automatically/

**Comment by rasikatlinksture** [comment]
I found a very good extension that supports discount link and link click report also. It is working very well in almost all magento versions. You can find it here: http://codecanyon.net/item/discount-coupon-code-link-extension-for-magento/12744606?ref=themezaa

**Comment by sidolov** [comment]
Hi @seansan. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#126 by @VitaliyBoyko in 2.3-develop branch
Related commit(s):
 - [e1f53d45065a6fa292e2213b72a2742f81197a0b](https://github.com/magento/magento2/commit/e1f53d45065a6fa292e2213b72a2742f81197a0b)
 - [5229cd6eed7b5e08174268245f23158513feabd9](https://github.com/magento/magento2/commit/5229cd6eed7b5e08174268245f23158513feabd9)
 - [af4b258a78a4772d4256b7c6e5912ddf326d93de](https://github.com/magento/magento2/commit/af4b258a78a4772d4256b7c6e5912ddf326d93de)
 - [3b64955757358d8c1d5f81859870bd1d84d2ac7b](https://github.com/magento/magento2/commit/3b64955757358d8c1d5f81859870bd1d84d2ac7b)
 - [b5a2a983c5b8441b8733f2d36055a4fb4f79a1f3](https://github.com/magento/magento2/commit/b5a2a983c5b8441b8733f2d36055a4fb4f79a1f3)
 - [e85a6e54ee15d8ea808d434b05eb9c666cdd772a](https://github.com/magento/magento2/commit/e85a6e54ee15d8ea808d434b05eb9c666cdd772a)
 - [8f3c6e920b7bdb953c31013c843017a4d25e3ed6](https://github.com/magento/magento2/commit/8f3c6e920b7bdb953c31013c843017a4d25e3ed6)

The fix will be available with the upcoming 2.3.0 release.

**Comment by duffner** [comment]
@magento-admin & @magento-engcom-team Was this added into the 2.3 release?
