### ISSUE TITLE
Can't save emoji in custom product options

### ISSUE THREAD

**Issue by archonkulis** [magento/magento2#12058]
### Preconditions

1. Magento version 2.1.6 ( it doesn't matter actually )
2. PHP 7.0
3) Mysql 5.6

### Steps to reproduce

1. Add some custom options to product ( text )
2. Go to product in front-end, input some emoji in that text field, e.g. "123 😍"
3. Add to cart

### Expected result

1. Either cart would render fine or show an error that specific emoji insertion is not supported

### Actual result

1. The cart is empty -> https://prnt.sc/h6v033

### My observations

The issues seem to be because Magento uses utf8_general_ci collation for the tables and also connection. If I try to manually insert "123 😍" in the utf8_general_ci table in the database, it doesn't allow it and shows following error:

`[HY000][1366] Incorrect string value: '\xF0\x9F\x98\x8D' for column 'value' at row 1`

Everything would be good if Magento wouldn't serialize ( or json_encode in the newest version ) the custom_options. ( well, not good anyway, but at least the cart would render fine, just the options would be truncated )

For example, when Magento inserts the "123 😍" in the quote_item_option.vale table, it becomes:

`a:5:{i:0;s:8:"123 `

As you can see, the string is corrupted at the end ( it truncates the string at the place where the emoji is )

I think that even if you do not plan to switch from utf8_general_ci to some other encoding which could solve this problem, you should still try to either show an error message in the front-end for the user or at least silently remove that emoji so that at least the cart would render fine.

Let me know what you think.

Thanks.

**Comment by magento-engcom-team** [comment]
@archonkulis, thank you for your report.
We've created internal ticket(s) MAGETWO-83334 to track progress on the issue.

**Comment by KarlDeux** [comment]
Got this! (think so)

**Comment by KarlDeux** [comment]
Fixed on #12253

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @archonkulis. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1296 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - aefd089d3b29023d4ec09036f5ae836a97fe549b
 - 0c799d2defa8341b7eb23bd5c92717b5f64138e7
 - 0a282955d6ec5b8e8f8fc6cf94d1a813adebb285
 - d0d8d03982dde84fb119636492d3272b54bd59e0
 - 1623007dc26f1953b10893304f3d9b7efa8db805
 - 64f63b3cf56fe03ae78a0154133d27f05749be4a
 - eceb5eb5d31608ef96403dbd7857e8178acb5dc6
 - e1db353d9fd9ed508846160a3cdb16228c09b60a
 - 7b12d50d92e1503f959219a5c8f05ecbef1cc423
 - 60285c4011fa4ccabe6548ace2b6aefc0cc65c8f
 - 2d910df07653f1a3fac8fbf3688b57ce5e3869e7
 - 57c355a802a3e2ff21b7cf7312c203ab735cd2bd
 - 4f9f40e54207c31a2c5e8460c85a042ad39cfa66
 - ebd663b8dde32c49d9f147bd2bbe3b438a2f415e
 - bdb62bb6c6c8326b31c83fc4c6343ee4017b84e6
 - 76f6eed85e282be7df18766868f03a5e1aa4109c
 - cd5c72ee83a89fe3c6632ddf9b6aeabf512503fc
 - b03566074756b7264155e10e2d68845d5000df29
 - 6217c009f7565b72fe8bd24ca2e862131f3d8dee
 - e07d040a33324bae14961ccc629604738854684b
 - 47ea3188264a42f735d12c6c6ebe208135eefb69

The fix will be available with the upcoming patch release.
