### ISSUE TITLE
Database Rollback not working with magento 2.1.9?

### ISSUE THREAD

**Issue by whereowareadmin** [magento/magento2#12064]
I created one test DB backup "test backup" when trying to rollback with SSH it only looks for somecode_db.sql file instead this backup contains the name in its file. is it magento2.1.9 bug?

### Preconditions

1.  centos 7.4 
2.  apache 2.4 / mysql 5.7/ php 7.0.2

### Steps to reproduce

1.  create a database backup from admin
2.  check from ssh if the database is in the list?
3.  run command in ssh to roll back the database.

### Expected result

1. it should roll back the database.

### Actual result

1. [Screenshot, logs]
https://i.imgur.com/n4FJjPC.png

**Comment by magento-engcom-team** [comment]
@whereowareadmin, thank you for your report.
We've created internal ticket(s) MAGETWO-83355 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to the 2.2-develop branch. Will be available with upcoming patch release

**Comment by whereowareadmin** [comment]
Thanks, I am not sure if this is the right place to ask. but should I download Magento from composure or GitHub branch, to make my Magento setup open for ongoing bug fixes?

can I set the pull request for each bug you solve? please bear with me as I am new to Magento2 and not sure how does it work with GitHub

**Comment by magento-engcom-team** [comment]
Hi @whereowareadmin. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1361 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 716f9afd694b6d7e5423bd2dbdabeeb45797886b
 - 595527a919eafd309f8b2a1d1339b312f6546f7b
 - 8c05a29b711ca03ecb866fc384122b3e46c08ccd
 - 63958cdc14bf3b44ad5fd95aafc626d8e25ca3e3
 - 78c2c2159b6c5aacc27e4fc918a1ed56a9df9b5f
 - 7f2dc2965a2d46e935770a7acdef8f260bd5fdc6
 - aee74586a9d28c1f47fd2ba3bae5e5871b779be9
 - 92f85860ce9725e34922a523e5137e656322c394
 - bf178ca5c3c10a50e3eba6e64fdf905e75d0b4c5
 - ecafa804c26054499b42c6820f0996035eb39dbc
 - a15208e96c06248d740ee65d154eda30226c848a
 - 76716b84a92f009253039cd06b9e47367384655f
 - 490785fffd885f85a7292c9144783cf2576b6b66
 - 6fe62802f5a529cd113697df79021bdb1dda9f53
 - 33e40ece8246363429be614440622600394a4516
 - 7b1bec8edb2eedea399eb78f891f1d6873cb1955
 - dbe5fc792279802f83d7110285c15fb2eede8d95
 - 22c6937f6db6a2ed17188f24097e0f9a194dc295
 - ca7da3fd58edca05b70a2af1768743ffc0294b72
 - b55a5d1a497279f72735e577ba60327dba178b6e
 - 65b745f7a94b2ba699a68f2825a63c9d78615f1c
 - b0a5a52df60a765748f15a7e0391f6b50535de21
 - 97dd9ad59c7d6bf9d4cf673a8e22708c480b1967
 - aa28366cc7378a972497e186fa8fb955684f74aa
 - 0fc86d89ab491fe7fc246d025662658844cd15a4
 - f11994acc1e220eb620d3baa63da8427d53e5797
 - 04445d07887870ba47dd2e97006c94d656f85942

The fix will be available with the upcoming 2.3.0 release.
