### ISSUE TITLE
Unable to insert widget with text value which contains }} string

### ISSUE THREAD

**Issue by ghost** [magento/magento2#12087]
### Preconditions

1. Magento 2.4-develop

### Steps to reproduce

1. Go to admin **Content -> Pages**
1. Click **Add New Page**
1. Set **Page Title** to `Page Title`
1. Expand **Content** section
1. In the content field, click **Insert Widget** button
1. Choose any widget which has at least one text input, e.g. **Catalog Products List**
1. Set widget title: `Title}}`
1. Click **Insert Widget**
1. Click **Save Page**
1. Go in frontend to see the page: \<base-url\>/page-title 

### Expected result

1. No errors

### Actual result

1. Widget content is incorrectly parsed
![image](https://user-images.githubusercontent.com/20726882/32505760-ab8e9088-c3eb-11e7-8cb0-6516f5535e75.png)

**Comment by magento-engcom-team** [comment]
@marcel-moldovan-vm, thank you for your report.
We've created internal ticket(s) MAGETWO-83438 to track progress on the issue.

**Comment by drpayyne** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @drpayyne, here is your [Magento instance](https://i-12087-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-12087-2-3-develop.instances.magento-community.engineering/admin](https://i-12087-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by theCapypara** [comment]
I tried solving this issue by extending the regex in Magento\Framework\Filter\Template, however after some tests and thinking about it, I don't think this is actually solvable using regex. So to solve this, the directive parsing logic would propably need to be changed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30096` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ghost. Thank you for your report. 
The issue has been fixed in magento/magento2#29006 by @engcom-Kilo in 2.4-develop branch
Related commit(s):
 - [7f0f260d3110a055ca1f8fa4886e766dd303b6c1](https://github.com/magento/magento2/commit/7f0f260d3110a055ca1f8fa4886e766dd303b6c1)
 - [2a48abee8a17331fdea9d3ba4738e5394d73a13b](https://github.com/magento/magento2/commit/2a48abee8a17331fdea9d3ba4738e5394d73a13b)
 - [e0eb4b0e3000b027b0197cf5603cc5fb8f6b8198](https://github.com/magento/magento2/commit/e0eb4b0e3000b027b0197cf5603cc5fb8f6b8198)
 - [cb0b3d407dc1ac5c42e202a515a2aee97574b57d](https://github.com/magento/magento2/commit/cb0b3d407dc1ac5c42e202a515a2aee97574b57d)
 - [1f84319d6905dc9cc862fd0cb1244489b44f5052](https://github.com/magento/magento2/commit/1f84319d6905dc9cc862fd0cb1244489b44f5052)
 - [f55eeb49d1e83b268f0c45bdce73eb2d0689b88f](https://github.com/magento/magento2/commit/f55eeb49d1e83b268f0c45bdce73eb2d0689b88f)
 - [ae3d3df4752dfcac5256ddb5014ce02b19e8a529](https://github.com/magento/magento2/commit/ae3d3df4752dfcac5256ddb5014ce02b19e8a529)
 - [a2346f4697a76f1d9905dc9968a79b57a9909e2b](https://github.com/magento/magento2/commit/a2346f4697a76f1d9905dc9968a79b57a9909e2b)
 - [74325ef39fd1c1e4e957747dc2d29ca3e73f4cf8](https://github.com/magento/magento2/commit/74325ef39fd1c1e4e957747dc2d29ca3e73f4cf8)
 - [0ac2e5d691f5bccbdb2fba896bb1c22ff6a0fa80](https://github.com/magento/magento2/commit/0ac2e5d691f5bccbdb2fba896bb1c22ff6a0fa80)
 - [edd340130b92015e3ecd6e03e93ca75111610afe](https://github.com/magento/magento2/commit/edd340130b92015e3ecd6e03e93ca75111610afe)
 - [ace8a6fd54d920b01533668f7f0b2942ec4b3def](https://github.com/magento/magento2/commit/ace8a6fd54d920b01533668f7f0b2942ec4b3def)
 - [01b7906cd3e339c0467f6cc9af6d681c7627482b](https://github.com/magento/magento2/commit/01b7906cd3e339c0467f6cc9af6d681c7627482b)

The fix will be available with the upcoming 2.4.2 release.
