### ISSUE TITLE
Customer with empty "Date of Birth" cannot be saved

### ISSUE THREAD

**Issue by JanisE** [magento/magento2#12146]
Customer with empty "Date of Birth" cannot be saved even when it is not marked (or checked on the JS side) as mandatory.

I didn't know how to re-open issue #11989 so I'm creating a new one. Now, I'm installing the latest Magento version (2.2.1), which has the same problem. The PHP version might be important (as pointed out by @Blatant at https://github.com/magento/magento2/issues/11989#issuecomment-342798206), it's 7.1.11, although I got the error with 7.1.7, too, previously.

I've also prepared an automated way of setting up the environment and installing Magento by Docker: https://github.com/JanisE/magento_test_1 Use it, please, if you cannot reproduce the bug in your test environments.

### Preconditions
1. OS: Linux Mint 18.2 (based on Ubuntu Xenial).
2. PHP 7.1.11
3. Magento CE 2.2.1 without sample data is installed by Composer.

### Steps to reproduce
1. Sign up as a new user entering whatever name, e-mail, password.
2. In Admin go to Stores -> Customers -> All customers and click "Edit" for the created customer.
3. Go to "Account Information" and change "Group" from "General" to "Reseller".
4. Click "Save Customer".

### Expected result
1. Either the customer gets saved
2. Or
2.1. Account Information -> "Date of Birth" field is marked as mandatory;
2.2. "This is a required field." appears beneath "Date of Birth" if it is empty when saving.

### Actual result
1. The page reloads with an error message "Something went wrong while saving the customer.".
2. An error message gets logged in the "system.log" starting with `main.CRITICAL: Exception message: Warning: A non-numeric value encountered in/var/www/html/magento/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php on line 94`

**Comment by okorshenko** [comment]
The issue has been fixed in 2.2-develop branch

**Comment by spectravp** [comment]
When updating Magento via composer to version 2.2.3, it installs magento/framework (101.0.3) which does NOT contain the fix for this issue. Have tried completely removing all composer installed components and reinstalling, same result. 

If I download the latest tarball from https://magento.com/tech-resources/download the above fixes are not present. 

Has this change not been merged into a release?

**Comment by magento-engcom-team** [comment]
Hi @JanisE. Thank you for your report. 
The issue has been fixed in magento/magento2#14666 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [4801d7486e16f200beede7a9afddb0d23cc1ec51](https://github.com/magento/magento2/commit/4801d7486e16f200beede7a9afddb0d23cc1ec51)

The fix will be available with the upcoming 2.3.0 release.

**Comment by developer-vtnetzwelt** [comment]
I am also facing the same issue on version - 2.2.3. On php-7.0.30 its working fine and on php-7.1.20 its giving same issue - "Warning: A non-numeric value encountered in /home/www-data/staging.risch-shoes.com/vendor/magento/zendframework1/library/Zend/Locale/Math/PhpMath.php on line 94"
