### ISSUE TITLE
BUG: in magento 2.2.1 $_product->getCollection()->load(); gives only 1 result although there are alot of products

### ISSUE THREAD

**Issue by petnutz** [magento/magento2#12157]
BUG: in magento 2.2.1 $_product->getCollection()->load(); gives only 1 result although there are alot of products

**Comment by magento-engcom-team** [comment]
@petnutz Thanks for reporting this issue. Please provide more detailed preconditions and steps to reproduce.

**Comment by magento-engcom-team** [comment]
@petnutz, thank you for your report.
Code `$_product->getCollection()->load()` should return a Collection subclass entity. You can get all its produts by calling getItems method, like `$_product->getCollection()->load()->getItems()`

**Comment by magento-engcom-team** [comment]
@petnutz, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
