### ISSUE TITLE
Magento 2.1 Multiple Image Uploader vs Magento 2.2 Multiple Image Uploader

### ISSUE THREAD

**Issue by darabaig** [magento/magento2#12168]
**Preconditions**
Magento 2.1.x 
Magento 2.2.x
Magento Multiple Image Uploader
![new events events magento admin](https://user-images.githubusercontent.com/3623336/32658128-69fa2a50-c63a-11e7-898d-53db648ae21b.png)

In magneto 2.2 the multiple product image up-loader block has been moved from layout to UI component form. To make it compatible with magento-2.2 I made the required changes in my custom module and it worked for me. But, when I reinstalled the module on (magneto 2.1.8), it does not recognize the block and settings nodes. Is it not backward compatible? What if we wish to run the same module on both Magento 2.2 and 2.1 ? Are there any module settings where we can change the format for different versions? How can we place a check or condition because in both version the block is placed at two different locations.

 **Steps to reproduce**

1. Create a custom module with multiple image uploder on magento 2.1.8 
2. Install the same module on magento 2.2 -the multiple image uploader will not be visible in the Ui  Form . Now to fix it move the block form layout xml to Ui form in a similar fashion as it has been done in magento 2.2 core files. It will work fine.
3. Next , if we re-install the working module from magento 2.2 on to a freshly installed magento2.1.8 you will get the following errors.

**Expected result**

Able to use multiple product image uploader in a custom module  in both version of magento i.e . Magento 2.1 && Magento 2.2

**Actual result**
The requested component ("settings") is not found. Before using, you must add the implementation.
The requested component ("block") is not found. Before using, you must add the implementation.

**Comment by orlangur** [comment]
I don't think there is something to "fix" here from core perspective.

Sometimes it is possible to make module compatible with many Magento version at the same time, sometimes it is not worth efforts.

Please check http://devdocs.magento.com/guides/v2.0/extension-dev-guide/versioning/dependencies.html and specify constraints of your module properly so that you get a compatible module version for both 2.1 and 2.2.

**Comment by magento-engcom-team** [comment]
@darabaig, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
