### ISSUE TITLE
Magento2: Not able to create promotion rule

### ISSUE THREAD

**Issue by sakjha10** [magento/magento2#12176]
HI,

I am getting an issue when trying to create promotion rule. This error occurs sometimes and the error disappears if run Magento upgrade command.  But it comes again sometime.

### Preconditions
Magento Version : 2.2

### Steps to reproduce
When trying to create promotion rule

### Expected result

1. Able to create promotion rule

### Actual result
Invalid method Magento\Eav\Model\Entity\Attribute::isAllowedForRuleCondition
Please check screenshot also.
https://s.nimbus.everhelper.me/share/1235713/exxaywvla6rk8oqndtxt

Looking forward to the solution.

Regards,
Sanjeev
www.tilkor.com

**Comment by magento-engcom-team** [comment]
@sakjha10, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.1.10, 2.2.1

**Comment by MichalZabrocki** [comment]
I have this issue when Mgt_DeveloperToolbar is enabled

**Comment by sakjha10** [comment]
Is Mgt_DeveloperToolbar of Magento or third party module?

**Comment by MichalZabrocki** [comment]
This is third party module.

**Comment by sakjha10** [comment]
Ok. In my case, there are more than 25 extensions. And the issue comes sometime, not frequently.

**Comment by andkirby** [comment]
I'd confirm this issue. Just there is some difference: we are still facing this issue in shopping cart and on some other pages on front store.
 
We decided to make temp fix by replacing code 
in file `vendor/magento/module-rule/Model/Condition/Product/AbstractProduct.php`
in method `Magento\Rule\Model\Condition\Product\AbstractProduct::loadAttributeOptions()`:
```
if (!$attribute->isAllowedForRuleCondition() || !$attribute->getDataUsingMethod($this->_isUsedForRuleProperty))
```
with 
```
if (!$attribute->getDataUsingMethod($this->_isUsedForRuleProperty) ||!$attribute->isAllowedForRuleCondition())
```

**Comment by andkirby** [comment]
@magento-engcom-team, is there any opportunity to reopen this issue? There is really the simple fix for this.

**Comment by arronmoss** [comment]
We experienced a very severe case related to this issue. At the promo pages in Admin reported this error, a full reindex happened and every product had every promo rule applied causing 15,000 products to be reduced by up to 90% as all rules applied sequentially to all products.

**Comment by Sil-B** [comment]
@arronmoss we have exactly the same issue. Did you find a fix?

**Comment by arronmoss** [comment]
@Sil-B no sorry, and no sign of steps to replicate so it's a very worrying situation to when this might reappear.

**Comment by Sil-B** [comment]
@arronmoss oke thanks. We've had this problem twice in one week. It appears out of the blue and was not caused by a setup:upgrade. 

After deleting the promorule and a reindex everything works fine again.

**Comment by parnus01** [comment]
this issue come to me same and it disappear after magento flush cache. who has some solution?

**Comment by Jakhotiya** [comment]
The database is migrated database from Magento m 1.9 to 2.2.4.
Current version of Magento we are using : 2.2.4

I'm facing the same issue. It appears out of the blue on checkout page and admin promo rules edit page.  I'm having a hard time replicating it. As soon as I clear the eav cache the issue goes away.
here's the screenshot of the trace.
![is-allowed-method-call](https://user-images.githubusercontent.com/9327315/40268438-bd4b14cc-5b8a-11e8-9047-69acbfddf71a.png)

I traced the issue to product attribute **status**. That's when 
the 
```
    public function loadAttributeOptions()
    {
        $productAttributes = $this->_productResource->loadAllAttributes()->getAttributesByCode();

        $attributes = [];
        foreach ($productAttributes as $attribute) {
            /* @var $attribute \Magento\Catalog\Model\ResourceModel\Eav\Attribute */
            if (!$attribute->isAllowedForRuleCondition() || !$attribute->getDataUsingMethod(
                $this->_isUsedForRuleProperty
            )
            ) {
                continue;
            }
            $attributes[$attribute->getAttributeCode()] = $attribute->getFrontendLabel();
        }

        $this->_addSpecialAttributes($attributes);

        asort($attributes);
        $this->setAttributeOption($attributes);

        return $this;
    }
```

Loop in the method fails. Looks like for attribute status, sometimes `$attribute` is not an instance of class `Magento\Catalog\Model\ResourceModel\Eav\Attribute`. That results in isAllowedForRuleCondition() to fail.

The reason this is hard to trace is cache clearing fixes the issue.

I hope somebody finds it helpful for debugging further

**Comment by andkirby** [comment]
@Jakhotiya , try to use my solution: https://github.com/magento/magento2/issues/12176#issuecomment-356279098. We have it in our projects - it doesn't disturb us anymore.

**Comment by Jakhotiya** [comment]
Thanks @andkirby I am aware of this fix but this issue looks more serious. I traced it to attribute cache being saved incorrectly sometimes? That makes me wonder about possible repercussions of this issue. As of now, we do have that temporary fix in place on live site, but we keep trying to replicate issue on staging site.

**Comment by gwharton** [comment]
I also get this on a reasonably regular basis when m2epro is downloading orders. My last debug showed the exact same problem, and a refresh of the cache fixed the attribute type.

**Comment by jobingeorgek** [comment]
@andkirby I have applied your fix to resolve the issue for now and its bypassing the loop without throwing the fatal error. Thanks!
@Jakhotiya As you mentioned the issue is that some attributes objects in loop are not in 'ResourceModel/Eav/Attribute'. I just added some code to log the attribute code and type of the object coming in loop and found that issue is for attributes Status and Visibility.
2018-05-26T12:50:33+00:00 INFO (6): ********LOOP STARTS**********
2018-05-26T12:50:33+00:00 INFO (6): entity_id :  
2018-05-26T12:50:33+00:00 INFO (6): attribute_set_id :  
.
.
.
2018-05-26T12:50:33+00:00 INFO (6): small_image :  
2018-05-26T12:50:33+00:00 INFO (6): small_image_label :  
2018-05-26T12:50:33+00:00 INFO (6): special_from_date :  
2018-05-26T12:50:33+00:00 INFO (6): special_price :  
2018-05-26T12:50:33+00:00 INFO (6): special_to_date :  
2018-05-26T12:50:33+00:00 INFO (6): status : Magento\Eav\Model\Entity\Attribute\AbstractAttribute
2018-05-26T12:50:33+00:00 INFO (6): style_name :  
2018-05-26T12:50:33+00:00 INFO (6): swatch_image :  
2018-05-26T12:50:33+00:00 INFO (6): sw_featured :  
2018-05-26T12:50:33+00:00 INFO (6): tax_class_id :  
2018-05-26T12:50:33+00:00 INFO (6): thumbnail :  
2018-05-26T12:50:33+00:00 INFO (6): thumbnail_label :  
2018-05-26T12:50:33+00:00 INFO (6): tier_price :  
2018-05-26T12:50:33+00:00 INFO (6): type :  
2018-05-26T12:50:33+00:00 INFO (6): updated_at :  
2018-05-26T12:50:33+00:00 INFO (6): url_key :  
2018-05-26T12:50:33+00:00 INFO (6): url_path :  
2018-05-26T12:50:33+00:00 INFO (6): visibility : Magento\Eav\Model\Entity\Attribute\AbstractAttribute
2018-05-26T12:50:33+00:00 INFO (6): weight :  
2018-05-26T12:50:33+00:00 INFO (6): weight_type : 
2018-05-26T12:50:33+00:00 INFO (6): ********LOOP ENDS**********

Further investigating on the issue.

**Comment by gwharton** [comment]
As someone hinted it is a problem with the cached version of the eav attribute and not the attribute itself, I have disabled the EAV cache and for now I have not seem this problem again.

**Comment by andkirby** [comment]
@gwharton , that's a good note. Thanks!

**Comment by rafaelstz** [comment]
Just refreshing before to access the Promo Page works too.

**Comment by mcyrulik** [comment]
We've noticed that this seems to happen more often for us with the following scenario:

1. Flush magento cache (all of them)
2. Load catalog pages, search for products, etc. on the Front End (DO NOT go into magento admin) also place an order with promo rule.
3. After the front end has populated the EAV cache, go into the admin and go to cart price rules. 

If we do it the other way around - clear cache, go into admin cart price rules.. it seems to work. 

Is it possible that the front end is populating the cache differently than the admin is, and that's a discrepency?

**Comment by ghost** [comment]
We were not able to reproduce this issue.

**Comment by domeglic** [comment]
I am able to reproduce the bug with the following steps:
- Magento 2.2.3+ with sample data
- Enable Product flat, reindex
- Add a product to cart
- Have a custom controller that uses ProductRepositoryInterface->getList 
- Clean the caches and open that page first
- Go to cart page and trigger a cart rule (sample shop has a over 200€ subtotal rule)

Then the error message appears. The error appears because `visibility` is cached with `attribute_model` set to the default `Magento\Eav\Model\Entity\Attribute` which doesn't have that method. 
The expected type should be `Magento\Catalog\Model\ResourceModel\Eav\Attribute`.

A quick workaround that worked for me is setting `attribute_model` of `visibility` to  `Magento\Catalog\Model\ResourceModel\Eav\Attribute` in the `eav_attribute` table although I don't know if that is a good idea.

**Comment by Vlad-Mecu** [comment]
Only working solution for both so far is for me is setting attribute_model of visibility and status to Magento\Catalog\Model\ResourceModel\Eav\Attribute in the eav_attribute table. 

Those attributes generates another error. 
"status" and "visibility" attributes type is Magento\Eav\Model\Entity\Attribute, expected to be Magento\Catalog\Model\ResourceModel\Attribute

It errors on some pages, it may be on more because of this:

1 exception(s):

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\Eav\Model\Entity\Attribute::isAllowedForRuleCondition



Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\Eav\Model\Entity\Attribute::isAllowedForRuleCondition

<pre>#1 Magento\SalesRule\Model\Rule\Condition\Product->loadAttributeOptions() called at [generated/code/Magento/AdvancedSalesRule/Model/Rule/Condition/Product/Interceptor.php:76]......


1 exception(s):

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\Eav\Model\Entity\Attribute::isScopeGlobal



Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\Eav\Model\Entity\Attribute::isScopeGlobal

<pre>#1 Magento\Catalog\Model\ResourceModel\Collection\AbstractCollection->_joinAttributeToSelect() called at [vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:1425]...

**Comment by wdttilburg** [comment]
This is still a bug in magento 2.2.10 (tig/postnl-magento2 and onestepcheckout/iosc is installed). Magento has set the wrong attribute model in the attribute cache when i followed these steps

1. clear cache with bin/magento c:c
2. open home page
3. goto empty category
4. goto category with products
5. goto to product
6. add product to cart
7. goto cart
8. goto checkout
9. change storeview to different language
10. wrong attribute model for status and visibility is saved in cache.

this is my diff to fix this:

```
diff --git a/vendor/magento/module-eav/Model/Entity/AbstractEntity.php b/vendor/magento/module-eav/Model/Entity/AbstractEntity.php
index b6100e9..ebab15f 100644
--- a/vendor/magento/module-eav/Model/Entity/AbstractEntity.php
+++ b/vendor/magento/module-eav/Model/Entity/AbstractEntity.php
@@ -448,6 +448,9 @@ abstract class AbstractEntity extends AbstractResource implements EntityInterfac
         if (!$attribute->getAttributeCode()) {
             $attribute->setAttributeCode($attributeCode);
         }
+        if (!$attribute->getAttributeModel()) {
+            $attribute->setAttributeModel($this->getEntityType()->getAttributeModel());
+        }
         if (!$attribute->getAttributeModel()) {
             $attribute->setAttributeModel($this->_getDefaultAttributeModel());
         }
```
