### ISSUE TITLE
Catalog not filtered by admin search bar

### ISSUE THREAD

**Issue by gianiaco** [magento/magento2#12193]
### Preconditions

1. magento 2.2.1
2. php 7.0.2
3. mariadb 10

### Steps to reproduce

1.  Log into backend with admin credentials
2. Click on the search in the top-right corner
3. Type something about name of products ("telephone" for example)
4. Click on ""telephone" in Products" to search the word inside catalog

### Expected result

1. Catalog filtered in base of word typed in the search bar

### Actual result

1. Catalog not filtered
![is1](https://user-images.githubusercontent.com/33554340/32691029-965d79d6-c701-11e7-8f5c-8cd885e29bd1.jpg)

**Comment by hannassy** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@hannassy thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ishakhsuvarov** [comment]
Closing, as it duplicates https://github.com/magento/magento2/issues/7861

**Comment by magento-engcom-team** [comment]
Hi @gianiaco. Thank you for your report. 
The issue has been fixed in magento/magento2#12735 by @hannassy in 2.2-develop branch
Related commit(s):
 - [0666b27c6f3aed663992beb166ef97f5523c2355](https://github.com/magento/magento2/commit/0666b27c6f3aed663992beb166ef97f5523c2355)
 - [f5d93c3e04ebf7ee8fd2537c7415ae3b11ba07a9](https://github.com/magento/magento2/commit/f5d93c3e04ebf7ee8fd2537c7415ae3b11ba07a9)
 - [790ac311344350c33af6f6a697a8d5f8bfe478d8](https://github.com/magento/magento2/commit/790ac311344350c33af6f6a697a8d5f8bfe478d8)

The fix will be available with the upcoming 2.2.5 release.
