### ISSUE TITLE
Tracking link returns 404 page in admin panel

### ISSUE THREAD

**Issue by catstantin** [magento/magento2#12206]
### Preconditions

Magento ver. 2.1.9

### Steps to reproduce
1. Configure Custom URL for admin panel in Admin > Stores > Configuration > Advanced 
![admin](https://user-images.githubusercontent.com/9476187/32723655-f73df96c-c876-11e7-90a9-766156b73bfe.png)
>
2. Make order
3. Login to admin panel
4. Add shipment to order
5. Click on "Track Order" link on order page in admin panel

### Expected result
1. Url should be generated for store where order was placed

### Actual result
1. Url generated for admin URL, as result - we have 404 page

**Comment by magento-engcom-team** [comment]
@catstantin, thank you for your report.
We've created internal ticket(s) MAGETWO-83474 to track progress on the issue.

**Comment by ihor-sviziev** [comment]
@p-bystritsky FYI I have fix for this issue, in progress of preparing PR for it

**Comment by p-bystritsky** [comment]
@ihor-sviziev I'll reassign issue to you.

**Comment by ihor-sviziev** [comment]
@okorshenko @p-bystritsky FYI we fixed this issue for own project with  https://github.com/magento/magento2/commit/9f7171a485e6e591d61f1c4353e9b203824a7c89 but I'm not sure that it's really good solution. 
It looks like issue it located in getUrl method for $store object, not sure it will be easy fix and not to brake websites. What do you think about this change?

**Comment by ihor-sviziev** [comment]
Ok, I tried that fix, it didn't worked well.
I'm working on it at #mageconf

**Comment by okorshenko** [comment]
Hi @catstantin. Thank you for your report. 
The issue has been fixed in magento/magento2#12732 by @ihor-sviziev in 2.2-develop branch
Related commits:
 - ecf27becd6bc99842527153f45e0e7fc91c95624
 - 5e4bf42b29de485cf19b119e32e52effe5ce1820

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @catstantin. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1297 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 21cfb6ab689b52d27dfe6816b27542f03ffbd73b
 - d173193c9612135a44d4f0490eef5995cb82c89f
 - b5a4ee42e65fec38b4d088335f44fbfd7e93c64c
 - f6570bd5d8e6b0767ce39f37d0355a5b61620638
 - b32bdc9a34247f33af0d7f2ed80868c55b1e5aae
 - 3c6d9bef7435b10fbf9570332ce27f6ceae9a7ac
 - d4c7ca0d4aeac15b8961e0e8a582fe716a088972
 - 07fa73aa7e698bc212ebeb65efbe558e49ac054a
 - 60426c6cd24c2f7d1881a27459a2a46628a81b3f
 - 14f85e9cd1f6c3349a5ce35c49c14e5772687d86
 - 72b399100b50ec9efaf437e800cd057631e4d9aa
 - 5483dc7045ea37787e3119770b2c737d9992bd06
 - f442a76b9f9225217004654154a57e585b8802e5
 - af9f7cbad96e82f56e093a9bfd70edf4e2296fde
 - 8b4ad902efc299e035ff9a93e58ae96513a686c1
 - 9354bb98941bff3a1675d893a27695ddd3ffe692
 - 9c9ed9153084a0c6acb16a6cea6932c117b2d26e
 - 4a422f65ce1d0a559cf1b4d1c477b32d11f54b6b
 - b6473f6924ca933702d5936628b4e51612ac8c90
 - 0c12a7aa9a5307263426a8b2bb93a97692cdd685

The fix will be available with the upcoming patch release.
