### ISSUE TITLE
Stock inventory reindex bug

### ISSUE THREAD

**Issue by Nix-id** [magento/magento2#12205]
Incorrect cleaning previous index's

### Preconditions

Magento 2.2.0

### Steps to reproduce

in Magento\CatalogInventory\Model\ResourceModel\Indexer\Stock\DefaultStock 
https://github.com/magento/magento2/blob/44d2562728d6fb70f32d13ea053c84ddb3def535/app/code/Magento/CatalogInventory/Model/ResourceModel/Indexer/Stock/DefaultStock.php#L289

### Expected result

Method deleteOldRecords should be called before all _updateIndexTable calls.

### Actual result

Method deleteOldRecords is called after one of _updateIndexTable calls.

also can you change 'private' method and vars in this class to 'protected'? for redeclare thiss class as 'extended' for use with 'di.xml'

**Comment by magento-engcom-team** [comment]
@Nix-id, thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@Nix-id, thank you for your report.
We've created internal ticket(s) MAGETWO-84414 to track progress on the issue.

**Comment by Nix-id** [comment]
Sorry for incorrect format.
but thanks for you work.

**Comment by p-bystritsky** [comment]
> also can you change 'private' method and vars in this class to 'protected'? for redeclare thiss class as 'extended' for use with 'di.xml'

@Nix-id, please create new ticket for this feature request.

**Comment by magento-engcom-team** [comment]
Hi @Nix-id. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1134 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - [20d7afbe75fed9b8f45e3231848aae40b1c06a3a](https://github.com/magento/magento2/commit/20d7afbe75fed9b8f45e3231848aae40b1c06a3a)
 - [8c44db2c9aa437a5f5b9356fbc36e2ea9134394f](https://github.com/magento/magento2/commit/8c44db2c9aa437a5f5b9356fbc36e2ea9134394f)

The fix will be available with the upcoming 2.2.5 release.

**Comment by avstudnitz** [comment]
This fix not being in Magento 2.3.2 has just cost us several days of work. Will it be in 2.3.3 @magento-engcom-team?

**Comment by avstudnitz** [comment]
This bug has cost us a lot of time and money after upgrading from 2.2.8 to 2.3.2.
@magento-engcom-team This fix is not included in Magento 2.3.x. Could you migrate it and make sure it will be in 2.3.3?

**Comment by hostep** [comment]
@avstudnitz: thanks for your comment! I created a new PR to get this change included in 2.3-develop: https://github.com/magento/magento2/pull/25306, let's hope it makes it in 2.3.4 now ...

**Comment by VladimirZaets** [comment]
Hi @Nix-id. Thank you for your report. 
The issue has been fixed in magento/magento2#25306 by @hostep in 2.3-develop branch
Related commit(s):
 - [c6d166be701d9afe0b341ca35727af8a20db80f8](https://github.com/magento/magento2/commit/c6d166be701d9afe0b341ca35727af8a20db80f8)

The fix will be available with the upcoming 2.3.5 release.

**Comment by wigman** [comment]
Awesome that this patch was removed in 2.3.4 again 👍 

https://github.com/magento/magento2/commit/9c4c3a05c7c14de1c1fd3d28f56bd409cd9f2a39#diff-9cf0a1093ac8c2558ce19f00934420d6L287

Hat tip to @SeruyV. You've costed a lot of people a lot of money.

so:
- added in 2.2.8
- removed in 2.3.2
- added in 2.3.3
- removed in 2.3.4
- added in 2.3.5

Let's hope this is the end of the journey, yes?

**Comment by kingletas** [comment]
@wigman Yes please. I don't think this bug needs any extra stamps.
