### ISSUE TITLE
Substitution payment method - Incorrect message

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#12209]
### Preconditions

1. Magento 2.1.9 (same should be in 2.2-develop and 2.3-develop)
2. DB migrated from M1, payment method wasn't migrated, so it's not available

### Steps to reproduce
1. Go to Admin panel and look at existing order
2. View "Payment & Shipping Method" section

### Expected result
 We should have message "<payment_method_name> is not available. You still can process offline actions." OR we should have message "Payment method is not available. You still can process offline actions.

### Actual result
We have message "is not available. You still can process offline actions."
![image](https://user-images.githubusercontent.com/1873745/32724672-ec6ce332-c87a-11e7-8593-cd34a7bfb1a5.png)

### Tech note
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Payment/view/adminhtml/templates/info/substitution.phtml#L13
1. payment method title isn't printed
2. There is no check if title is not empty

**Comment by magento-engcom-team** [comment]
@ihor-sviziev, thank you for your report.
We've created internal ticket(s) MAGETWO-83822 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#12731 by @zamoroka in 2.2-develop branch
Related commit(s):
 - 30b8293b6ba86d0aba94fbb0e1a41fac154a1716

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1325 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - e84cb3eb79f63f3cac85f5b68b90b82530786d86
 - 742819bdd72880190a992a0f9412af4c0ba417ae
 - cc2b11f47825471e93523db287b4a013da6629d5
 - ae8b1870640227d69e921a5a358fe2addefb5018
 - 35b3c02ca62fa40990fd957c36cd21b7e4f127cd
 - eae893662678539fa602434d92d798ec8a3b3a4c
 - 90e49230db9a94b2b5831c5618b960de35ebc4e0
 - b098dbc4e53efae137286bf056f1e46a2971d52c
 - e8e4cdd29db74ccd13f3078f93c59fb53c4a96d3
 - 058e5e55680e4ca8eb64311f782994fac10a1f74
 - 9368d5da237eb6e158990f2cff8be954242821fe
 - bf19409195b7b93322073026455405ed8820e6af
 - a15ec3421d3d2371429f9c804b91ecd3b6aaf763
 - 9e4ce76a9ad07713d2170420fcd8d237ec776fcb
 - 099568124736c9575bf7498641a0842877260346
 - 6772a2d6658c4677334df0b67159d3a47b6d2155
 - b0d6bfc6599390f31ef3b564fb3e2848037faeef
 - b03735716895f21bee4bc5b5be7d5c7f5a27ba33
 - 8de595178d6dca294d649fde0359a055f07fca69

The fix will be available with the upcoming 2.3.0 release.
