### ISSUE TITLE
Topmenu links stop working after resizing the browser window

### ISSUE THREAD

**Issue by linden2015** [magento/magento2#12213]
The topmenu links that have subcategories stop working as expected when the browser window is reduced to small and enlarged to original size again.

### Preconditions
1. Magento Commerce 2.2.1 OR Magento Commerce 2.1.9.
2. Browser: Google Chrome Version 62.0.3202.89 (Official Build) (64-bit)

### Steps to reproduce
1. Enable production mode
2. Open the homepage on a screen resolution of 1920x1080 or beyond.
3. Resize the browser window to as small as possible in the horizontal direction.
4. Resize the browser window again to the original resolution.

### Expected result
1. The topmenu items that have subcategories can be clicked with the mouse pointer causing a redirection to a new page.

### Actual result
1. The topmenu items that have subcategories do not respond to a mouse click. No redirection. No javascript errors in the console.

**Comment by linden2015** [comment]
@magento-engcom-team , can you tell me what will be done with this issue?

* Will it be fixed in 2.1.?
* Will it be fixed in 2.2.?

**Comment by laconica-sergey** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @linden2015 The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
