### ISSUE TITLE
Invalid input datetime format of value in MAGENTO 2.2.1

### ISSUE THREAD

**Issue by vitormicillo** [magento/magento2#12215]
### Preconditions

1. Magento 2.2.1
2. PHP 7.1.8

### Steps to reproduce

1. Change your Dashboard Language to non en
2. Update any product
3. Set any date to define as a new product, it can be the current date
4. Save

### Actual result

![screenshot from 2017-11-13 15-45-26](https://user-images.githubusercontent.com/1921806/32731280-ae9ba872-c889-11e7-9648-7edd8b9621a4.png)

**Comment by raumatbel** [comment]
Hi @vitormicillo, thanks for bug report, I close this issue because it is a known issue tracked as [10580](https://github.com/magento/magento2/issues/10580)

**Comment by magento-engcom-team** [comment]
@vitormicillo, thank you for your report.
We've created internal ticket(s) MAGETWO-83902 to track progress on the issue.

**Comment by bahramdavoodi** [comment]
Hi, i hope this help to you now.
[Module Fix Date](https://github.com/Magonex/module-datetime)

**Comment by MaiconUnzer** [comment]
The module fix date by bahramdavodi worked

**Comment by katiakweb** [comment]
Thank you bahramdavodi, this fixed the issue in Magento 2.2

**Comment by officestarmb** [comment]
I have Magento 2.2.1 in my case the solution that worked it was very simple: In product go to Advanced Pricing and delete the date from/to is empty in my case.......this worked for me! I hope help you!:)

**Comment by clockover** [comment]
Same issue Magento 2.2.3.
Pass the admin itnerface in English solve the issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-12215-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-12215-2-3-0.instances.magento-community.engineering/admin](https://i-12215-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@vitormicillo, thank you for reporting the issue. We are closing this as fixed at least on 2.3.0

**Comment by raisandeep1989** [comment]
Invalid input datetime format of value in MAGENTO 2.3 with product Schedule Design Update.
product update is working fine but when update the Schedule Design Update  it got this error.
   
I am using AU_EN locale to store and tried with US_EN also but it did not worked.
https://prnt.sc/p13qiz

Why is it is happen with magento 2.3?? any suggestion are welcomed

**Comment by chapagain** [comment]
A temporary quick fix can be the following:

- Click your user name on the top right in your admin panel.
- Click on the `Account Settings` submenu.
- Try to change `Interface Locale` to a different one (I changed from English US to English UK)
- Save
- Now, go to `Catalog > Products` and try to save any product with a change in `Set Product as New From` date.

You should be able to save the product successfully.

_Ref: https://magento.stackexchange.com/a/219936/1883_
