### ISSUE TITLE
"Uncaught TypeError: Event.observe is not a function" In Version 0.74.0-beta6

### ISSUE THREAD

**Issue by anshumanravi** [magento/magento2#1221]
Hi, I am getting this Js error(Related to Prototype?)  at Admin , As a result Submit and other functions not working for me. Frontend working properly though with no error so far.

Env :
 Mac OSX 10.10 
 Apache+PHP  , Chrome Version 42.0.2311.90 (64-bit)

**Comment by anshumanravi** [comment]
Self closing it. running deploy fixed it.

```php
php dev/tools/Magento/Tools/View/deploy.php
```

**Comment by VladimirZaets** [comment]
Hi @risingravi. Thank you for your report. 
The issue has been fixed in magento/magento2#15685 by @phoenix128 in 2.3-develop branch
Related commit(s):
 - [7259c4bc329c3b9b9541d3113bb46f3ba2f131d3](https://github.com/magento/magento2/commit/7259c4bc329c3b9b9541d3113bb46f3ba2f131d3)

The fix will be available with the upcoming 2.3.0 release.
