### ISSUE TITLE
Layered navigation counts only IN STOCK products

### ISSUE THREAD

**Issue by maqlec** [magento/magento2#12223]
### Preconditions

1. Magento 2.1.10 or 2.2

### Steps to reproduce

1. Set category with 3 products, 2 in stock and 1 out of stock with the same attribute on layered navigation
2. Turn on "Display Out of Stock Products" in admin panel

### Expected result

1. On layered navigation is count of 3 products and on list are 3 products

### Actual result

1. On list are 3 products (2 in stock, 1 out of stock) and on layered navigation are 2 (in stock only).

I don't know, maybe this should work like this but in 2.1.7 worked well. It is broke since MAGETWO-57475 was merged.

**Comment by magento-engcom-team** [comment]
@maqlec, thanks for reporting.
Please specify what attributes are used for layered navigation in Your case.

**Comment by maqlec** [comment]
It could be any attribute, I found the place where this condition is hardcoded
https://github.com/magento/magento2/commit/b043944085b94d3689b396246753d19a02bf453f#diff-c04b442549dd53e9620aa23f581ff1b5R115 
I could fix this but I don't know purpose why sombody did that :)

**Comment by magento-engcom-team** [comment]
Hello @maqlec. Still we would like You to specify the following information about the attribute You've used: what it is set to in Storefront Properties -> Use in Layered Navigation - Filterable (with results) or Filterable (no results) because it directly concerns the situation. Till now we've been able to get Your actual result only with Filterable (with results) selected. But that is a normal behavior for an attribute. With selected Filterable (no results) it will have done just like You have expected.

**Comment by maqlec** [comment]
Ok, so It's not dependant on Use in Layered Navigation option.
My attribute is a dropdown with 3 value options. Filterable (with results or no results) causes the same behavior. There is one difference with no results is showed attribute with 0 count number.
Maybe in the picture it will be better shown
![test](https://user-images.githubusercontent.com/13941930/32859117-d229c01a-ca4d-11e7-9f05-1a975939a2cd.png)

**Comment by magento-engcom-team** [comment]
@maqlec, thank you for your report.
We've created internal ticket(s) MAGETWO-83983 to track progress on the issue.

**Comment by p-bystritsky** [comment]
Duplicatates https://github.com/magento/magento2/issues/11946
