### ISSUE TITLE
Fourth URI segment is lost during redirection

### ISSUE THREAD

**Issue by berkanduzgun** [magento/magento2#12242]
### Preconditions
1. Magento CE 2.2-develop (d4e666fbb2528de8d2e97dcb642107edf0c64f88)
2. Also exists on 2.1.9 EE

### Steps to reproduce
1. Store uses secure URL. Base URL is https://example.com/.
2. Create a category tree with following structure. (You do not have to create to reproduce)
Root Category
- Test 1
- - Test 2
- - - Test 3
- - - - Test 4
2. Make a request to **http**://example.com/test-1/test-2/test-3/test-4.html

### Expected result
1. Magento should redirect to https://example.com/test-1/test-2/test-3/test-4.html

### Actual result
1. Magento redirects to https://example.com/test-1/test-2/test-3/. The last URI segment is lost.

**Comment by magento-engcom-team** [comment]
@berkanduzgun, thank you for your report.
We've created internal ticket(s) MAGETWO-83917 to track progress on the issue.

**Comment by shilpag25** [comment]
@magento-engcom-team give me 2.3-develop

**Comment by shilpag25** [comment]
I am working on this issue at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@shilpag25 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by shilpag25** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shilpag25. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shilpag25, here is your [Magento instance](https://i-12242-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-12242-2-3-develop.instances.magento-community.engineering/admin](https://i-12242-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shilpag25** [comment]
Hello @berkanduzgun ,

I have tried to reproduce the issue on above mentioned instance( https://i-12242-2-3-develop.instances.magento-community.engineering/) and found that this issue is not reproducible.

Steps followed for reproducing an issue:
1. Followed the same category structure as mentioned above.
2. Make request with url **http://i-12242-2-3-develop.instances.magento-community.engineering/test-1/test-2/test-3/test-4.html**
3. The last url part is not getting truncated and url redirect to https://i-12242-2-3-develop.instances.magento-community.engineering/test-1/test-2/test-3/test-4.html 
This is an expected result, hence I am closing this issue.
