### ISSUE TITLE
Limited access admin user can't export products on first request after login in magento 2.1.x 

### ISSUE THREAD

**Issue by rushtohk** [magento/magento2#12269]
**Steps to reproduce**

1. Create new admin user role having following role resources  'a. Products  > Inventory > Catalog b. My Account c. Stores > Attributes > Product d. Stores > Attributes > Update Attributes e. System > Data Transnfer > Import f. System > Data Transnfer > Export' 
2. Add new admin user to above mentioned role.
3. Export Products from new limited acess admin user created.

**Expected result**

export_products.csv should be downloaded.

**Actual result**

Redirects to 'product > catalog' page

**Comment by rushtohk** [comment]
@magento-engcom-team Is this issue being reviewed ?

**Comment by rushtohk** [comment]
Got the solution. The new limited access admin user must have  'System > Other Settings > Notifications > Show Toolbar' to get the expected result.

**Comment by magento-engcom-team** [comment]
@rushtohk , Thanks for the report. Should we close the ticket now?

**Comment by rushtohk** [comment]
Yes.

**Comment by magento-engcom-team** [comment]
@rushtohk, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
