### ISSUE TITLE
Order confirmation email contains non functioning links 

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#12261]
On the bottom of the Order Confirmation email (and all other emails sent to the customer) there are two links "About Us" and "Customer Service" which do not work - view screenshot

### Preconditions
1.  Magento 2.2.1
2.  PHP 7.1

### Steps to reproduce
1.  Place an order and receive a confirmation email

### Expected result
1.  Links should work when clicked

### Actual result
1.  Links do not work

![magento](https://user-images.githubusercontent.com/10808588/32822201-79b0faec-ca2b-11e7-9bfd-d2d822dcb247.jpg)

**Comment by renttek** [comment]
what are the URLs, that the links are pointing to? (Domain is not needed, but path)

**Comment by magento-engcom-team** [comment]
@bondimedical3, thank you for your report.
We've created internal ticket(s) MAGETWO-83912 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @bondimedical3 thank you for your report. The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release

**Comment by magento-engcom-team** [comment]
Hi @bondimedical3. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1358 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 2e90684d1f906a63c37e2dea4710aee59c0c0a58
 - f99b75906ab0d370005692499faebba810aa3984
 - 49a3076876a44798397495c6f376699eb3214528
 - b754973b0c24a5d4482ba6b027f8d673a64dae80
 - ed833c492e51f78ee2523c0b2eb5fee37c91166d
 - d8b73d3bb4b8ff66faa308e761b9ade25d0bf9f7
 - 60e83eac5925e1ec01cbc11b8eb1acc5305a7a23
 - dc69e175dc95befc3e1c0eb1b9d51c23a0e1e0e9
 - 6b9c188627aa4d9614c5ffe1a0436d75e17bb796
 - 3b58efc8e8cf3f856f7f0edbe84bd2ceb5f167b2
 - 8b40859ed856295dfd4240638c26d7b17807402a
 - 11922a14040b4869da87445fa627533256164595
 - 0bd39d42c785cac7ee0b49434cb957baa04f6c7f
 - 8bbb8bbb675f10f9632e76ff27a8199a7a3aa4ee
 - f8307d9d169debab91b1440d131dc166eb2e2640
 - 768c769b2772743e8599840aa8dc523597d0b6e5
 - 16a10291b25f826d066f155257a3922ee3f01682
 - 17a26cbcf93a3d95815a21b92dc9bc04ec116e58
 - 8f1d8e78df9cd8f648ea30d399f81816ad1d6d01
 - 5d084ce7979f07e7b1d6ac9980be13fdd2a378cd
 - d248f4e39a1fca56c5ea429dca5af190e28c56cb

The fix will be available with the upcoming 2.3.0 release.
