### ISSUE TITLE
Add shipping address in orderInterface

### ISSUE THREAD

**Issue by VictorSnow** [magento/magento2#12263]
### Preconditions

1. Magento 2.2.1
2. ......

### Steps to reproduce

1. call rest api on /V1/orders/:orderId  method: get
2. 

### Expected result

1. return shipping address as well as the billing address

### Actual result

1. no shippping address is returned

**Comment by magento-engcom-team** [comment]
@VictorSnow , We cannot reproduce this issue. Here is our result:

![shipping address](https://user-images.githubusercontent.com/31669971/32824506-eb96b634-c9e9-11e7-82bb-8577d0dd7a0d.png)

**Comment by VictorSnow** [comment]
the interface returns billing_address as order field
and shipping_address may need to be the same
````
            [billing_address] => Array
                (
                    [address_type] => 
                    [city] =>
                    [country_id] =>
                    [customer_id] => 
                    [email] => 
                    [entity_id] => 
                    [firstname] => 
                    [lastname] => 
                    [parent_id] =>
                    [postcode] => 
                    [region] => 
                    [region_code] => 
                    [region_id] => 
                    [street] => Array
                        (
                            [0] =>
                        )

                    [telephone] => 
                )
````

**Comment by magento-engcom-team** [comment]
@VictorSnow ,  thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@VictorSnow, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
