### ISSUE TITLE
Bug: Adding Custom Attribute - The value of Admin scope can't be empty

### ISSUE THREAD

**Issue by webscot** [magento/magento2#12294]
### Preconditions

1. v2.2.1
2. php7

### Steps to reproduce

1. Add customer Product Attribute
2. Choose Dropdown
3. Under Manage Attributes, click "Add Option" and then "Delete" empty boxes
4. Attempt to save. Error produced, "The value of Admin scope can't be empty."

### Expected result

1. Attribute should save rather than trying to collect data that can no longer be entered.

### Actual result

1. [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@webscot, thank you for your report.
We've created internal ticket(s) MAGETWO-83964 to track progress on the issue.

**Comment by virtual97** [comment]
#mageconf

**Comment by magento-team** [comment]
Hi @webscot. Thank you for your report. 
The issue has been fixed in magento/magento2#12755 by @virtual97 in 2.2-develop branch
Related commit(s):
 - 2ccb374aaf4a646594eb01e72fee7748871fadcc
 - 288d0d47e4998e1b8981063b562e87f783f08f42
 - e78ea61cc080a38bb7985f04b5bf33ab0547cf73

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @webscot. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1299 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 99e3a76b47267c930d4268b7bbf65500d1913f24
 - 4cfc07e28a8edb388011168e5fd0726dc6c71119
 - ea616e0a217e74707305f1038e6ca207d4bdaba6
 - be55217eae883abd02d44211fa0a88bb0a1d803c
 - 41c52fb989d961ad6ac48eea23163deb61dd9adc
 - 7f42a672ee864f2fc186d0259eb0de2e3d9634f6
 - 1090c8b54733b409a17553bfeb3ec292d449e5ce
 - c80b5ca54d2890407cf329bd24312ebf858929d2
 - 8077af7d42d069523f4addc21741567579e6e74f
 - 38e34a8747651b69a85575d7416d88a3ae49a34d
 - c13ad8595cf555b683223688325fe888fc112bec
 - 9e7bf93ec5b0e90952cac07391d2bde1a72d81ef
 - 10a6288175601ba26075996f3c39880b6e17eb76
 - abf31d2afaa543cddca00b197434ba3f28ac199b
 - 898a470a8b8b6cc6048a403be03594b8fd1b6b98
 - c99c3a7ae67ab16ab2407641a9b2c796f63ce3ef
 - 4537e784c70a3e07470ff7424684348c802839c8
 - 0bad56f0c371d5edc3cfc80dbae1e11400516546
 - fd2418ed8d062181ebc2e10bc298aba95d6d7a5e
 - 946e9e1b508e7788abf12e5c50098cdd9f6447ec

The fix will be available with the upcoming patch release.
