### ISSUE TITLE
SKU values are not trimmed with the space.

### ISSUE THREAD

**Issue by ShaileshChauhan92** [magento/magento2#12300]
### Preconditions

1.  SKU accepts the value with space at end at starting of the value. They are not validated while importing products by CSV.

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. SKU should be trimmed while importing into the database.

### Actual result

1. [Screenshot, logs]
Two duplicates SKU are created with same name.

**Comment by magento-engcom-team** [comment]
@ShaileshChauhan92, thank you for your report.
We've created internal ticket(s) MAGETWO-84007 to track progress on the issue.

**Comment by p-bystritsky** [comment]
### Preconditions


1.  Magento 2

### Steps to reproduce

1. Create a product with sku 'test', save it.
2. Create a product with sku '&nbsp;&nbsp;&nbsp;test&nbsp;&nbsp;&nbsp; ', save it.

### Expected result

1. Product is saved with sku '&nbsp;&nbsp;&nbsp;test&nbsp;&nbsp;&nbsp; '.

### Actual result

1. Product is saved with sku 'test-1'.


Problem is caused by sku uniqueness check. It trims whitespaces before executing the database request. 
https://github.com/magento/magento2/blob/7d00d28efee1fec773e3a715fc6c6f5906d53d79/app/code/Magento/Eav/Model/Entity/AbstractEntity.php#L906-L909

**Comment by dimaperedriy** [comment]
#mageconf

**Comment by dimaperedriy** [comment]
Steps from original bug message can`t reproduce on magento 2.2-develop branch.

**Comment by PieterCappelle** [comment]
I think this correct behaviour and I can’t reproduce in 2.2 or 2.3.

**Comment by ishakhsuvarov** [comment]
@ShaileshChauhan92 Closing per multiple comments abount the issue not being reproducible.
Please clarify the steps and reopen if you still experiencing problems.

**Comment by sidolov** [comment]
Hi @ShaileshChauhan92. Thank you for your report. 
The issue has been fixed in magento/magento2#18019 by @bartoszkubicki in 2.3-develop branch
Related commit(s):
 - [6c168dd9ced1f3eb141b01dc8091319b474811a6](https://github.com/magento/magento2/commit/6c168dd9ced1f3eb141b01dc8091319b474811a6)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @ShaileshChauhan92. Thank you for your report. 
The issue has been fixed in magento/magento2#18862 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [109a27eb8bd2e5b8f37fcb84ef4c0d19490a5e16](https://github.com/magento/magento2/commit/109a27eb8bd2e5b8f37fcb84ef4c0d19490a5e16)

The fix will be available with the upcoming 2.2.8 release.
