### ISSUE TITLE
Magento 2.1.3 - Invoice and shipment PDF doesn't support Arabic

### ISSUE THREAD

**Issue by Avinashsain** [magento/magento2#12323]
### Preconditions

1. Magento CE 2.1.3

### Steps to reproduce

1. In the admin, go to Sales > Orders
2. Select one 'completed' order and select the action 'Print Invoices' (any of the Print... actions actually)

### Expected result

1. Be able to read  Arabic words & texts

### Actual result

1. [invoice_Arabic.pdf](https://github.com/magento/magento2/files/1482013/invoice_Arabic.pdf)

**Comment by magento-engcom-team** [comment]
@Avinashsain, thank you for your report.
We've created internal ticket(s) MAGETWO-84083 to track progress on the issue.

**Comment by Avinashsain** [comment]
Hi Team,

Any update on this?

Thanks

**Comment by sukhwinder-singh-dev** [comment]
Hi, I am looking into this issue.
Please assign me #MM18IN

**Comment by magento-engcom-team** [comment]
@ss-wtw thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by rossmc** [comment]
@ss-wtw & @magento-engcom-team ,

I submitted a PR for this yesterday. PR #13016.

Ross

**Comment by magento-engcom-team** [comment]
Hi @Avinashsain. Thank you for your report. 
The issue has been fixed in magento/magento2#13016 by @rossmc in 2.2-develop branch
Related commit(s):
 - [e44c91fbc0da0b36575b4eaef25bbc7b6fba112b](https://github.com/magento/magento2/commit/e44c91fbc0da0b36575b4eaef25bbc7b6fba112b)
 - [b38976b5341781fe72dcf41f421cd61abab453cf](https://github.com/magento/magento2/commit/b38976b5341781fe72dcf41f421cd61abab453cf)
 - [a5b685e77b0f39d72805495db6ccdac3eada35e0](https://github.com/magento/magento2/commit/a5b685e77b0f39d72805495db6ccdac3eada35e0)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @Avinashsain. Thank you for your report. 
The issue has been fixed in magento/magento2#14711 by @rossmc in 2.1-develop branch
Related commit(s):
 - [6165e36c8d77640b0c3cab875afba978967266da](https://github.com/magento/magento2/commit/6165e36c8d77640b0c3cab875afba978967266da)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @Avinashsain. Thank you for your report. 
The issue has been fixed in magento/magento2#14710 by @rossmc in 2.3-develop branch
Related commit(s):
 - [abd7be087cebeae8109f8d998d24361cedb2d554](https://github.com/magento/magento2/commit/abd7be087cebeae8109f8d998d24361cedb2d554)

The fix will be available with the upcoming 2.3.0 release.
