### ISSUE TITLE
Newsletter subscribe button title wrapped

### ISSUE THREAD

**Issue by gilles6** [magento/magento2#12320]
### Preconditions

1. Magento 2.2.1
2. PHP 7.1

### Steps to reproduce

Set the **newsletter subscribe button**'s title with at least two Chinese characters (either by changing it with your browser's Developer Tool or by switching the CMS language to Chinese), for instance "订阅".

### Expected result

The two characters of the Chinese word "订阅" should be written in the same line.
<img width="377" alt="screen shot 2017-11-17 at 16 37 12" src="https://user-images.githubusercontent.com/612946/32938025-c41604de-cbb5-11e7-8d87-cf20944b5c7d.png">

### Actual result

The Chinese word "订阅" is wrapped in two lines.
<img width="363" alt="screen shot 2017-11-17 at 16 36 56" src="https://user-images.githubusercontent.com/612946/32938002-b3bd697e-cbb5-11e7-889b-c83d8ff8ac44.png">

I fixed the issue temporarily by adding the following CSS in the file `web/css/source/_extend.less` of my custom theme. 
```
button.action.subscribe.primary {
  white-space: nowrap;
}
```

**Comment by magento-engcom-team** [comment]
@gvigner, thank you for your report.
We've created internal ticket(s) MAGETWO-84056 to track progress on the issue.

**Comment by dasharath-wagento** [comment]
dasharath-wagento:“#mm18in”

**Comment by magento-engcom-team** [comment]
@dasharath-wagento thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by monaemipro** [comment]
Please assign me this issue #MM18IN

**Comment by magento-engcom-team** [comment]
@monaemipro thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-team** [comment]
Hi @gvigner. Thank you for your report. 
The issue has been fixed in magento/magento2#13041 by @monaemipro in 2.2-develop branch
Related commit(s):
 - d9536c881f164cd032bc3ffe6413569dd2ea222d

The fix will be available with the upcoming patch release.

**Comment by magento-team** [comment]
Hi @gvigner. Thank you for your report. 
The issue has been fixed in magento/magento2#13029 by @dasharath-wagento in 2.2-develop branch
Related commit(s):
 - f83956bbd221446407f94d20c4e868347952e66a
 - 294c09eb3cc0e16cb1eb711b35e05ced7aae8232

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @gvigner. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1302 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 176b9f09d657cea1ba04d69d273641a1d47841b3
 - ab504376148b77c73447c8abbb5ae42a66071a10
 - 6a527a87bc6e46fce9ed45b2561b45c44a7a7e85
 - a0cb9e274b6a4cca5f410224babb6625546ce45b
 - 6e6c7d2987182cb48042db28f72a8c08de615d8d
 - 1d45a064e783f109cd413989672073c9ccac8bdb
 - 1fdee0001742c5fd1b5980aaa1f3ed81ab545cc3
 - 727f9b306bb8ea889dc580fe8056f8080fd62680
 - f842883a7a0b680f2cda361f7f9628bd739c1c38
 - 547426435ddbb263d30baee68fd5cd29a7dc1267
 - ba1d05a023f3e989d49ea8e29546433fe62090b0
 - 6fb29ac2a4f92dde2947f2a07225a6c55899c946
 - be2840d4f2d930ce97a5c1d005ebd5d071f782a7
 - 17da65c817295631c34d4902e62798d88e010ecb
 - ded8aa9710c5527d3eb8b679b8fb58ba1a222faa
 - 818cccdd55a4009fe7617e9c535b4c858967b273

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
Hi @gvigner. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1380 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - [e9238bcb04f75a5ef0d801ef7a4c372832d83aad](https://github.com/magento/magento2/commit/e9238bcb04f75a5ef0d801ef7a4c372832d83aad)
 - [c46acb7f26afb967c2e727d9557d00a03418a599](https://github.com/magento/magento2/commit/c46acb7f26afb967c2e727d9557d00a03418a599)
 - [3d5cc519f30a8664aadca0b1378ff62138fd1bf9](https://github.com/magento/magento2/commit/3d5cc519f30a8664aadca0b1378ff62138fd1bf9)
 - [fcd3e7af7984ed9887a8213c51ff3cc29546fd93](https://github.com/magento/magento2/commit/fcd3e7af7984ed9887a8213c51ff3cc29546fd93)
 - [a37313a401cd143fbfb6642108f602a16d96d211](https://github.com/magento/magento2/commit/a37313a401cd143fbfb6642108f602a16d96d211)
 - [4e00485ed12b762e38bbf5e38cce97981a43dedf](https://github.com/magento/magento2/commit/4e00485ed12b762e38bbf5e38cce97981a43dedf)
 - [d73cca2aee6113f66e8098512343d4e440afe65e](https://github.com/magento/magento2/commit/d73cca2aee6113f66e8098512343d4e440afe65e)
 - [0d8938cfd7f6c85146e1ad3176947eb6f8a945ae](https://github.com/magento/magento2/commit/0d8938cfd7f6c85146e1ad3176947eb6f8a945ae)
 - [d544ca2a6d99132e66e8b416ab73cc712de149f9](https://github.com/magento/magento2/commit/d544ca2a6d99132e66e8b416ab73cc712de149f9)
 - [e075ca794af8189260359434488029b2768fc29d](https://github.com/magento/magento2/commit/e075ca794af8189260359434488029b2768fc29d)
 - [a6c2bc2b471586eb44d9b4fc2341517bb64cad15](https://github.com/magento/magento2/commit/a6c2bc2b471586eb44d9b4fc2341517bb64cad15)
 - [960d58cfc3ef200654f1c19a5eca8cb905da686c](https://github.com/magento/magento2/commit/960d58cfc3ef200654f1c19a5eca8cb905da686c)
 - [dbdb772c0260347267701f5f54196fec1c0e5109](https://github.com/magento/magento2/commit/dbdb772c0260347267701f5f54196fec1c0e5109)
 - [bac46ce7f62207e27fdb401e4e72040c2bed32db](https://github.com/magento/magento2/commit/bac46ce7f62207e27fdb401e4e72040c2bed32db)
 - [1503f3a49de2d20ed3729823a4410cbfba3fd92a](https://github.com/magento/magento2/commit/1503f3a49de2d20ed3729823a4410cbfba3fd92a)
 - [17662c6eb0948da16b97a93ad0c231947eba933d](https://github.com/magento/magento2/commit/17662c6eb0948da16b97a93ad0c231947eba933d)
 - [2a72e5cc81c7b28aa04c5c64a63a8493043d6384](https://github.com/magento/magento2/commit/2a72e5cc81c7b28aa04c5c64a63a8493043d6384)
 - [ddaf5c6df7e2b294085ef6133820a6a1b6b12762](https://github.com/magento/magento2/commit/ddaf5c6df7e2b294085ef6133820a6a1b6b12762)
 - [7bf80fdc06c32325040dada5082b78975b910e1b](https://github.com/magento/magento2/commit/7bf80fdc06c32325040dada5082b78975b910e1b)
 - [efb8bf6a94a99130fe013f4ef9c3c0c39777b7b1](https://github.com/magento/magento2/commit/efb8bf6a94a99130fe013f4ef9c3c0c39777b7b1)
 - [321263009819a694221ce8a06902cf7a4ba3ff00](https://github.com/magento/magento2/commit/321263009819a694221ce8a06902cf7a4ba3ff00)
 - [ac9c10b96940ed5393581135146c8ea29eddd143](https://github.com/magento/magento2/commit/ac9c10b96940ed5393581135146c8ea29eddd143)
 - [2c6c9c06b1a69a20f4b7bfcd27e1eebf8e26ad2b](https://github.com/magento/magento2/commit/2c6c9c06b1a69a20f4b7bfcd27e1eebf8e26ad2b)
 - [73522bf72d57e503281077abb20b4000375eb57d](https://github.com/magento/magento2/commit/73522bf72d57e503281077abb20b4000375eb57d)
 - [818cf61d28821cc2a5435c60b6308adcb5a3ea26](https://github.com/magento/magento2/commit/818cf61d28821cc2a5435c60b6308adcb5a3ea26)
 - [61d0d9608493f65a0c0eafe264e1575eaa84b7be](https://github.com/magento/magento2/commit/61d0d9608493f65a0c0eafe264e1575eaa84b7be)
 - [85e0956b08923ca721e3577edd684aec02a93b6b](https://github.com/magento/magento2/commit/85e0956b08923ca721e3577edd684aec02a93b6b)
 - [1698afc93aed22284efa2bf9d943b2108b5af3ab](https://github.com/magento/magento2/commit/1698afc93aed22284efa2bf9d943b2108b5af3ab)
 - [ce7faf6203e39aefdf177e2a6a4168cbb5223993](https://github.com/magento/magento2/commit/ce7faf6203e39aefdf177e2a6a4168cbb5223993)
 - [70051020df3e9053272cc6926680895b9898a35b](https://github.com/magento/magento2/commit/70051020df3e9053272cc6926680895b9898a35b)
 - [bd07bcc9e681810ac35fd59b3ef74970e55dca37](https://github.com/magento/magento2/commit/bd07bcc9e681810ac35fd59b3ef74970e55dca37)
 - [16930193a78f00b50f9fa16012d96c5c1d481f19](https://github.com/magento/magento2/commit/16930193a78f00b50f9fa16012d96c5c1d481f19)
 - [ba7da597361305e6a91c04fe39d63162408af3b3](https://github.com/magento/magento2/commit/ba7da597361305e6a91c04fe39d63162408af3b3)
 - [d9e8b87af003d550f39e9d34cf19f94088660a38](https://github.com/magento/magento2/commit/d9e8b87af003d550f39e9d34cf19f94088660a38)
 - [0bb740b82dcf7324dad4b1650f13838b51950368](https://github.com/magento/magento2/commit/0bb740b82dcf7324dad4b1650f13838b51950368)
 - [c51f94c3a115468ea4808478e67c88c13dca1445](https://github.com/magento/magento2/commit/c51f94c3a115468ea4808478e67c88c13dca1445)
 - [9f3f3e05d91951f56b469cf47576e3c2eb72a9b5](https://github.com/magento/magento2/commit/9f3f3e05d91951f56b469cf47576e3c2eb72a9b5)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @gvigner. Thank you for your report. 
The issue has been fixed in magento/magento2#17022 by @dasharath-wagento in 2.1-develop branch
Related commit(s):
 - [aad8cb7a6af97642b02e5772606cbc490bf67cf3](https://github.com/magento/magento2/commit/aad8cb7a6af97642b02e5772606cbc490bf67cf3)

The fix will be available with the upcoming 2.1.15 release.
