### ISSUE TITLE
'Uncaught Error' After Customer Signs Out

### ISSUE THREAD

**Issue by pioneerathletics** [magento/magento2#12336]
### Preconditions

1. Magento 2.1.10 or 2.1.9 CE
2. PHP 7.0.24
3. Apache/2.4.23 CentOS
4. Redis enabled
5. Production Mode
6. All Caches enabled

### Steps to reproduce

1. Sign in as a customer
2. Add item to shopping cart
3. Select the view and edit cart link in the mini-basket dropdown
4. Remove the item from the cart
5. Sign out as the customer and return to the homepage

### Expected result

1.  No errors should be present

### Actual result

1. `Uncaught Error: [object Object]
    at Object.<anonymous> (pub/static/frontend/.../.../.../Magento_Customer/js/customer-data.min.js:1)
    at fire (jquery.min.js:212)
    at Object.fireWith [as rejectWith] (jquery.min.js:218)
    at done (jquery.min.js:628)
    at XMLHttpRequest.callback (jquery.min.js:655)`

![screen-shot-2017-11-15-at-10 12 48-am](https://user-images.githubusercontent.com/19981272/32964376-0a56788a-cba1-11e7-86ff-d199dbef6fdd.jpg)

**Comment by sanjay-wagento** [comment]
Review in 2.2-develop branch and cannot reproduce an issue.
OS: Ubuntu 16.04
Magento Branch: 2.2-develop (Install without sample data)

**Comment by bharat-singh-dev** [comment]
Hi I am looking in to the issue. Please assign me this #MM18IN

**Comment by magento-engcom-team** [comment]
@bharatsingh67 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @pioneerathletics The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
