### ISSUE TITLE
Remove Copyright date from all files

### ISSUE THREAD

**Issue by navarr** [magento/magento2#1234]
Please remove the Copyright date from all files, i.e. this text:

 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

Should have the "Copyright © 2015 Magento" replaced with one of:

* "Copyright © Magento"
* tongue-in-cheek "Copyright © date('Y') Magento"

**Why?**

One of the most annoying things about Magento 1 is the huge diffs created for the first release of a new year - every. single. file. has changed.

Please don't do that to us again.

**Comment by orlangur** [comment]
Hi, as far as I understand 2015 is not going to be updated ever as it is "the year of the first publication of the work" (see a9e5897bf6c3607f1d994c6d03c2c4b8b8954985).

Otherwise it would be placed in separate file like here:
https://github.com/zendframework/zf2/blob/master/LICENSE.txt#L1
https://github.com/symfony/symfony/blob/2.7/LICENSE#L1

**Comment by navarr** [comment]
If that's true, that's all I want :+1:

**Comment by orlangur** [comment]
Unfortunately, somebody came up with https://github.com/magento/magento2/commit/2d368d0134597257ef5697a4bcbb7f69f2aebed8. Hope it's the last such massive change.

**Comment by Detzler** [comment]
Unfortunately, somebody came up with 934e277c. Hope it's the last such massive change.

looooool
