### ISSUE TITLE
Order Status resets to default Status after Partial Refund

### ISSUE THREAD

**Issue by DigitalStartupUK** [magento/magento2#12386]
### Preconditions
1. Magento 2.2.0

### Steps to reproduce
1. Create new Status: "Picking"
2. Assign new State to Processing: "processing[Picking]"
3. Create order and Invoice
4. Update Status from Processing to Picking
5. Refund part of order whilst in Picking Status (e.g. lower quantity, refund delivery, remove a line)

### Expected result
1. Order Status remains the same "Picking"

### Actual result
1. Order Status resets to Processing

Note: A custom Order Status is required during order preparation in the warehouse. When a partial refund takes place and reset the status, it results in orders being picked and dispatched twice.

**Comment by magento-engcom-team** [comment]
@DigitalStartupUK, thank you for your report.
We've created internal ticket(s) MAGETWO-84313 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @DigitalStartupUK. Thank you for your report. 
The issue has been fixed in magento/magento2#20378 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [2eccce2ff17c7c061761273406ea828126756170](https://github.com/magento/magento2/commit/2eccce2ff17c7c061761273406ea828126756170)
 - [12498b5ed23c035338e1da342fb4aa80dfbae201](https://github.com/magento/magento2/commit/12498b5ed23c035338e1da342fb4aa80dfbae201)
 - [2a343dd8e60d7cc9ba8fa037dd8dbd2f51ab6d46](https://github.com/magento/magento2/commit/2a343dd8e60d7cc9ba8fa037dd8dbd2f51ab6d46)

The fix will be available with the upcoming 2.3.2 release.
