### ISSUE TITLE
Custom Magento CLI command has incorrect current store id.

### ISSUE THREAD

**Issue by Cinawork** [magento/magento2#12395]
### Preconditions
1. Magento 2.2.0
2. PHP 7.0.25
3. MariaDB 10.1.29

### Steps to reproduce
1. Create Magento CLI module
2. Retrieve random ProductInterface
3. Set product name to something new
4. Save product

### Expected result
1.  Product saves to all store views (store view 0)

### Actual result
1. Product saves to store view 1

**Comment by kozie** [comment]
I have the exact same problem with pretty much the same preconditions. +1

We had to set the store explicitly with the storeInterface to have the expected result where i didn't had to do this when i first created a CLI Command a few versions back (I presume M2 v2.1).

**Comment by magento-engcom-team** [comment]
@Cinawork, thank you for your report.
We've created internal ticket(s) MAGETWO-84308 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @Cinawork. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#967 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - [a2ae375499a807f06a677d2e7c5a7ed7e130b0b8](https://github.com/magento/magento2/commit/a2ae375499a807f06a677d2e7c5a7ed7e130b0b8)
 - [64a516128431f85b7ae623461117b5c9308fea05](https://github.com/magento/magento2/commit/64a516128431f85b7ae623461117b5c9308fea05)

The fix will be available with the upcoming 2.2.5 release.
