### ISSUE TITLE
Minimum advertised prices not working for configurable products

### ISSUE THREAD

**Issue by sl02** [magento/magento2#12426]
### Preconditions
1. Magento 2.2.1

### Steps to reproduce
1. Enable MAP in Stores>>Sales>>Sales>>Minimum Advertised Prices. Leave other options as 'Use system value'.
2. Create a configurable product.
3. Created linked virtual products, set a value for MSRP > Price and select 'Use config' for Display Actual Price.

### Expected result
1. Price on frontend is hidden and only shown 'on gesture' (which is default system value).

### Actual result
1. Price is shown on frontend as if Minimum Advertised Prices were disabled.
![map](https://user-images.githubusercontent.com/22160597/33194165-f38aa342-d09b-11e7-91fa-f5138a0180e8.png)

### Additional info
MAP works exactly as expected for simple products.

**Comment by magento-engcom-team** [comment]
@sl02, thank you for your report.
We've created internal ticket(s) MAGETWO-84461 to track progress on the issue.

**Comment by KarlDeux** [comment]
This is sexy, i'll take a look into this.

**Comment by KarlDeux** [comment]
Hi!

So I am working on this and there are many questions that needs to be clarify by someone from @magento-engcom-team .

I made some changes in order to show correctly the price message for configurable products in the category/view layout as can be seen here:

<img width="1017" alt="captura de pantalla 2018-03-14 a las 10 26 51" src="https://user-images.githubusercontent.com/5971780/37393836-9197a170-2772-11e8-9344-df80ea2b98f6.png">
<img width="455" alt="captura de pantalla 2018-03-14 a las 10 27 20" src="https://user-images.githubusercontent.com/5971780/37393835-917b025e-2772-11e8-90e3-2d3820633312.png">

The issue comes with the grouped products as they won't show the message properly.

Also, there are some constrains into the product/view page:

<img width="1173" alt="captura de pantalla 2018-03-14 a las 10 31 05" src="https://user-images.githubusercontent.com/5971780/37393968-efe370f6-2772-11e8-87a6-2ab553e7876b.png">
<img width="1155" alt="captura de pantalla 2018-03-14 a las 10 31 18" src="https://user-images.githubusercontent.com/5971780/37393969-f003aa7e-2772-11e8-9fa1-e8667dff6754.png">

The thing is that it will only show the price for the cheapest combination but it won't update with the chosen one from the dropdown.

Shall we update the app/code/Magento/Catalog/Block/Product/View.php `$config` with MSRP price in case MAP is enabled and MSRP > Price and modify JS behavior to update the popup block with this data? 

Let me know if you would like me to fix grouped product too and how shall I proceed with the product view thing.

Best,
Carlos.

**Comment by joemstar** [comment]
Has anyone found a resolution to this? I am experiencing the same problem.

**Comment by alfonso-eusebio** [comment]
Hi,

I'm struggling in this area as well.
As far as I can see, at least in some places, Magento uses the configurable/parent product's MSRP value, and not the child products'. However, you can't configure an MSRP for the parent product once it has associated products (children).

If in M2 configurable product pricing should be managed at the child product level, then all the internal logic should support that approach. Why is the code using the parent's MSRP when it's not even supposed to be there?

Am I completely mistaken here?

**Comment by Ctucker9233** [comment]
@alfonso-eusebio I've noticed the same as well. I think you have it right.

**Comment by mslabko** [comment]
@KarlDeux do you have a PR with a fix for configurable products?

**Comment by KnK123** [comment]
Hi Team,

We have been facing the same issue in the Magento version 2.3.5-p2 enterprise edition. Could you please let us know is there any patch for this? please share us if you have.

Nagaraju
