### ISSUE TITLE
'Requested store is not found' when trying to create a store view in the back end

### ISSUE THREAD

**Issue by Eminee** [magento/magento2#12421]
### Preconditions

1. PHP 7.1.8
2. Magento 2.2.1 installed via metapackage/composer

### Steps to reproduce

1. Log into back end
2. Go to Stores >All Stores > Create Store View
3. Select an existing store, and add a name and code for new store view
4. Click 'Save Store View'

### Expected result

1. A new store view is created and shown in the list of stores

### Actual result

1. I get an error which says 'Requested store is not found'
![image](https://user-images.githubusercontent.com/603253/33184079-c3fcee88-d072-11e7-8b18-70428dcfbea3.png)

### Additional Info
I've noticed a previous issue that is somewhat similar here: https://github.com/magento/magento2/issues/10908 which says that bug will be fixed in 2.2.2 but I'm not sure this is the same bug? 
Do we know when 2.2.2 is scheduled for launch? 

Many thanks.

**Comment by hostep** [comment]
Heh, funny, I noticed the same problem yesterday: https://github.com/magento/magento2/issues/12405

But you can't reproduce it on a clean installation, you need "something" changed to a clean installation, the question is, what that "something" is and why it causes this problem...

#10908 is not the same problem, that's something totally different.

**Comment by magento-engcom-team** [comment]
@Eminee thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a new clean installation

**Comment by hostep** [comment]
@magento-engcom-team: you should be able to reproduce using the steps mentioned in https://github.com/magento/magento2/issues/12405

**Comment by magento-engcom-team** [comment]
@Eminee, thank you for your report.
We've created internal ticket(s) MAGETWO-84636 to track progress on the issue.

**Comment by Ylmzef** [comment]
I have same issue when i save one of my website design configuration (Content -> Design -> Configuration)

**Comment by Arcturpartner** [comment]
I have same issue when i save some of my websites in design configuration (Content -> Design -> Configuration). With some websites I don't have an issue when saving!

**Comment by magento-engcom-team** [comment]
Hi @Eminee. Thank you for your report. 
The issue has been fixed in magento/magento2#13943 by @hostep in 2.2-develop branch
Related commit(s):
 - [5b6df42840edf7d27455fa6fe8dec221cf8af747](https://github.com/magento/magento2/commit/5b6df42840edf7d27455fa6fe8dec221cf8af747)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @Eminee. Thank you for your report. 
The issue has been fixed in magento/magento2#14043 by @hostep in 2.3-develop branch
Related commit(s):
 - [7a2d71561fbde5ea849fbeccaf2847fcddd6adc6](https://github.com/magento/magento2/commit/7a2d71561fbde5ea849fbeccaf2847fcddd6adc6)

The fix will be available with the upcoming 2.3.0 release.
