### ISSUE TITLE
Magento CE 1.9.x issues or improvements or features finding their way to Magento 2

### ISSUE THREAD

**Issue by seansan** [magento/magento2#1243]
Hi, a question regarding bug issue process. .

I see many issues or improvements or features that also (could) apply to Magento 2. Often they are logic issues where process logic could be improved. 

As we are human individuals: I could imagine that the Magento CE 1.9.x can easily discard some of these issues as not being relevant. Also many issues have no status. No idea what is happening with them. But they could be of strong importance for the improvement of Magento 2. 

How do these issues find their way to Magento 2? And would one appreciate logging them here too - maybe as a reminder to check or verify? (albeit that there will be a reference to Mage 1.x instead of Mage2)

http://www.magentocommerce.com/bug-tracking/list

**Comment by maksek** [comment]
Hi @seansan, we are continually checking existing or recently fixed issues in Magento 1, and validating them across Magento 2. If there are similar issues - we are fixing it.
If you have found issues in current code base, and able to reproduce it - feel free to report it here, in github. If there are similar ticket in our backlog - we will let you know and post in comments related MAGETWO ticket number. As soon as it will be fixed in fix available in codebase we will notify creator and close issue in github.

**Comment by seansan** [comment]
OK - I think the most important is that you also check "checking existing
issues" - regarding my comment that something may not be fixed (anymore) in
Magento 1.x - and will not show up in any change / update list- rather the
bug will exist only as a report in the bug report system

Is there already a nightly build of Mage2 available where one can test
situations to validate this?

On Thu, May 7, 2015 at 11:47 AM, Max Yekaterynenko <notifications@github.com

**Comment by maksek** [comment]
No, at the moment we don't have build, but we are considering to provide it around or after Merchant Beta release.

**Comment by piotrekkaminski** [comment]
The public bug tracker is tied to our internal system but with limited resources we are rather slowly reviewing the issues there. If you have a major issue and can reproduce it on Magento 2 - please report in github to expedite fixing.
