### ISSUE TITLE
Remove /home from the sitemap.xml

### ISSUE THREAD

**Issue by wd7080** [magento/magento2#12446]
### Preconditions

Magento ver. 2.2.1

### Steps to reproduce

1. Visit your site sitemap at https://domain.com/sitemap.xml

### Expected result

1. You will see your sitemap.
2. You will see your homepage listed as https://domain.com/home 

### Actual result

1. I want to remove /home from the sitemap.xml (I want the URL in the sitemap to be "https://domain.com" instead of "https://domain.com/home").

I tried: https://github.com/VincentMarmiesse/magento2-remove-home-from-sitemap but it does not work on this version. I don't want to achieve this via the .htaccess. I want that to be adjusted in the XML.

**Comment by magento-engcom-team** [comment]
@wd7080 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.
After install this module run setup:upgrade, setup:di:compile, clear cache and add permissions if needed.

**Comment by wd7080** [comment]
@magento-engcom-team  To reproduce this you need to fill the default CMS home page title as "Home Page". In the URL Key under Search Engine Optimization type "home". (this is the mistake because by doing this, we created a URL rewrite rule. I don't remember if it was already there).  This adds /home to the URL and makes the URL for the homepage looks like https://domain.com/home. This URL does not redirect back to the homepage. Alternatively, the homepage will appear on two links as follows:
https://domain.com/home AND https://domain.com

Go to Content -> Pages and you will see URL key for the home page set as "Home". See the image below: 
![home](https://user-images.githubusercontent.com/33989344/33275737-2a9cbb3a-d359-11e7-9f78-f4e2c56ff516.png)

I checked the rewrite rules under Marketing ->URL Rewrites and I found this rule there (also, refer to the image below:
Request path: home 
Target path: cms/page/view/page_id/2
![url](https://user-images.githubusercontent.com/33989344/33275867-72ca5750-d359-11e7-9929-61e96d98a99e.png)
How can we correct this on the sitemap.xml and make the home page appears as the domain name only without /home? Shall I delete this rewrite rule? Again, I don't want to achieve this via the .htaccess.

**Comment by magento-engcom-team** [comment]
@wd7080, thank you for your response.
We've created internal ticket(s) MAGETWO-84604 to track progress on the issue.

**Comment by osrecio** [comment]
I'm working on it

**Comment by wd7080** [comment]
@osrecio Thanks for working on the ticket! I would like to know if adding /home to the main website name affects Google search engine because, for example, I cannot find my website on google when I look for the domain name only, although the domain name is a .com domain name, alternatively, I get .net.au domain name when I look up for my domain name, but this is not the case with Bing search engine. I suspect this has to do with this ticket and I am currently testing this by adding a new sitemap I created rather than using Magento 2 sitemap. I should update you soon on this.

**Comment by osrecio** [comment]
@wd7080 I added a PR to exclude default pages inside `Store->Configuration->General->Web`.

**Comment by wd7080** [comment]
@osrecio  Thanks! in which update version do you expect this to be released?

**Comment by magento-team** [comment]
Hi @wd7080. Thank you for your report. 
The issue has been fixed in magento/magento2#12649 by @osrecio in 2.2-develop branch
Related commit(s):
 - 6ea1c43040a0364ee2483837256077511dc1301a

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @wd7080. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1361 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 716f9afd694b6d7e5423bd2dbdabeeb45797886b
 - 595527a919eafd309f8b2a1d1339b312f6546f7b
 - 8c05a29b711ca03ecb866fc384122b3e46c08ccd
 - 63958cdc14bf3b44ad5fd95aafc626d8e25ca3e3
 - 78c2c2159b6c5aacc27e4fc918a1ed56a9df9b5f
 - 7f2dc2965a2d46e935770a7acdef8f260bd5fdc6
 - aee74586a9d28c1f47fd2ba3bae5e5871b779be9
 - 92f85860ce9725e34922a523e5137e656322c394
 - bf178ca5c3c10a50e3eba6e64fdf905e75d0b4c5
 - ecafa804c26054499b42c6820f0996035eb39dbc
 - a15208e96c06248d740ee65d154eda30226c848a
 - 76716b84a92f009253039cd06b9e47367384655f
 - 490785fffd885f85a7292c9144783cf2576b6b66
 - 6fe62802f5a529cd113697df79021bdb1dda9f53
 - 33e40ece8246363429be614440622600394a4516
 - 7b1bec8edb2eedea399eb78f891f1d6873cb1955
 - dbe5fc792279802f83d7110285c15fb2eede8d95
 - 22c6937f6db6a2ed17188f24097e0f9a194dc295
 - ca7da3fd58edca05b70a2af1768743ffc0294b72
 - b55a5d1a497279f72735e577ba60327dba178b6e
 - 65b745f7a94b2ba699a68f2825a63c9d78615f1c
 - b0a5a52df60a765748f15a7e0391f6b50535de21
 - 97dd9ad59c7d6bf9d4cf673a8e22708c480b1967
 - aa28366cc7378a972497e186fa8fb955684f74aa
 - 0fc86d89ab491fe7fc246d025662658844cd15a4
 - f11994acc1e220eb620d3baa63da8427d53e5797
 - 04445d07887870ba47dd2e97006c94d656f85942

The fix will be available with the upcoming 2.3.0 release.

**Comment by rav-redchamps** [comment]
If anybody needs it before 2.3 release, it is available in below free extension

https://redchamps.com/seo-and-sitemap-patch-magento-2-extension.html

OR

there is a paid extension which can exclude any URL from sitemap

https://redchamps.com/xml-sitemap-exclude-url-magento-2-extension.html

**Comment by duffner** [comment]
@osrecio and @magento-engcom-team , 

I'm not sure if this is the direct cause, but I'm using 2.2.4 and the homepage is entirely missing from the sitemap.xml in previous versions it's included as `/home` now I can't find it in the sitemap at all. 

Is this expected behavior and related to this ticket, or should I create a new one?

**Comment by bilalusean** [comment]
@duffner same issue homepage missing from the sitemap.xml, I have tested this in Magento 2.2.5 Vanilla setup.
if you found any solution, please let me know.

**Comment by duffner** [comment]
@bilalusean, I did find a workaround, however I can’t remember what exactly. I seem to remember it being not using the default /home as the CMS homepage in the admin.    I’ll try and check this later but wanted to help you as much as I could first.

**Comment by magulin** [comment]
I have the same problem on Magento 2.3.1, "https://domain.com/" is missing from sitemap.xml
@duffner Do you remember what workaround you found?
