### ISSUE TITLE
Allow 'contains' as a search criteria condition type

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#12458]
As an API consumer, I don't want to have to think about formatting 'like' conditions for my search criteria, and would like to be able to use a 'contains' search criteria condition type.

### Preconditions
1. Magento 2.2.1

### Steps to reproduce
1. Install Magento 2.2.1
2. Install sample data using `bin/magento sampledata:deploy`
3. Deactivate WebApi security settings in Admin > Store > Configuration > Services > Magento WebAPI
4. Send request to `http://[magento host]/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=red&searchCriteria[filter_groups][0][filters][0][condition_type]=contains`

### Expected result

1. Response xml contains products with 'red' in their sku.

### Actual result

1. No products returned.

**Comment by magento-engcom-team** [comment]
@nbennett25, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hi @nbennett25. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento-engcom/community-features/issues/12
