### ISSUE TITLE
I can't disable full screen gallery on mobile on magento 2.2.1

### ISSUE THREAD

**Issue by joebordo** [magento/magento2#12490]
I applied the code below to disable full screen gallery in magento 2.2.1

    `<var name="breakpoints">
            <var name="mobile">
                <var name="conditions">
                    <var name="max-width">767px</var>
                </var>
                <var name="options">
                   <var name="options">
                     <var name="allowfullscreen">false</var>
                     <var name="arrows">false</var> 
                     <var name="nav">thumbs</var> 
                    </var>
                </var>
            </var>
        </var>`

The code does not work. The full screen gallery is still not disabled on mobile. (under 767 px)
### Preconditions
magento 2.2.1
php 7.1
### Steps to reproduce
Add the code above, it should disable the full screen gallery under 767 px.
 <var name="allowfullscreen">false</var>  (this code does nothing)
### Expected result
It does nothing.

### Actual result
Nothing happens, the gallery is still enabled in mobile (under 767 px)

**Comment by magento-engcom-team** [comment]
@joebordo, thank you for your report.
We've created internal ticket(s) MAGETWO-84793 to track progress on the issue.

**Comment by joebordo** [comment]
Okey the problem is that it passes breakpoint value as a string.

It renders the breakpoints like this:

```[ "breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"dots","allowfullscreen":"false"}}}}    }]```


But it should be like this 

 ```"breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"dots","allowfullscreen":false}}}}    }```

false should not be a string.

As a temporary solution you can replace the php echo block for the breakpoints in

module-catalog/view/frontend/templates/product/view/gallery.phtml

with the above code directly. Until this is fixed.

**Comment by okorshenko** [comment]
Hi @joebordo 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by ikevinkk** [comment]
Hi @okorshenko 

Firstly wish you a Happy Christmas and a Happy New Year in 2018! 

I'm a newcomer that i may have a same problem as yours :

The problem is when go on any Android or IOS device, go to a product page, open the image gallery of the item. Try to click the upper right hand X and the gallery does NOT close. You have to hit the back button on the browser to get out of it but when you do that, it takes you back to the product grid page. It has been tested on iphone 5s, and iPhone 6s and iPhone 7. (i had pasted a screenshot of it is appearing on iphone 7)

Thanks a million to help me out of this problem. 

![problem screenshot](https://user-images.githubusercontent.com/34853612/34351029-2552e812-ea55-11e7-807d-e2dac5a1e581.jpg)

**Comment by Chad-Mathews** [comment]
@joebordo is right that it passes breakpoint value as a string. Another workout around I found without having to override gallery.phtml is to just set the var value to an empty string so it returns false.
`<var name="allowfullscreen"></var>`

**Comment by BB-000** [comment]
Still having this problem in 2.2.2..  ):

**Comment by sashas777** [comment]
@okorshenko 
I can confirm the issue exist at Magento 2.2.2.
module-catalog/view/frontend/templates/product/view/gallery.phtml
 breakpoints return:
``"breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"thumbs","arrows":"false","allowfullscreen":"false","thumbwidth":"64","thumbheight":"64","navtype":"slides"}}}} ``

Where "false" should be false in order to work.
