### ISSUE TITLE
Packages file at repo.magento.com is corrupt

### ISSUE THREAD

**Issue by moleman** [magento/magento2#12547]
### Steps to reproduce

1. composer require "module"

### Expected result

1. Should add module

### Actual result

1. Composer fails with:
`[ErrorException]
  Array to string conversion`

Found out that the package index file contains: `"name": ["magento\/ece-tools", "magento\/ece-tools"],` which is not correct.

**Comment by lbajsarowicz** [comment]
It is caused by Spanish translation module.
<img width="1075" alt="zrzut ekranu 2017-12-05 o 11 54 19" src="https://user-images.githubusercontent.com/1639941/33603851-3d35c302-d9b4-11e7-93c1-93faedd8993b.png">

![zrzut ekranu 2017-12-05 o 11 26 39](https://user-images.githubusercontent.com/1639941/33603856-42a3dc02-d9b4-11e7-82f0-46b8d8ecbafe.png)

**Comment by chonny** [comment]
same issue here plus 
<img width="1071" alt="screen shot 2017-12-05 at 13 58 19" src="https://user-images.githubusercontent.com/491965/33605948-642c7220-d9c4-11e7-9a8a-c2c7d6716af2.png"> upgrading to 2.2.0

**Comment by lbajsarowicz** [comment]
Now it works.
I recommend Magento2 core to use CI at least basic level.

**Comment by chonny** [comment]
Still presented here

**Comment by chonny** [comment]
Now it works :)
