### ISSUE TITLE
Google Crawl Error after running command lines

### ISSUE THREAD

**Issue by wd7080** [magento/magento2#12543]
### Preconditions

1.  Magento 2 Ver 2.2.1

### Steps to reproduce

1. Connect to your web server using SSH
2. Enter your credentials.
3. Run the following command: `php bin/magento module:disable Magento_Reviews` to disable reviews.

### Expected result

1. Reviews expected to be disabled.

### Actual result

1. Reviews were not disabled and the command line # 3 in steps to reproduce ended in error.
2. I tried to deploy the static content and I run the following command: `php bin/magento setup:static-content:deploy`
3. The command line in step # 2 above didn't run and gave me a message saying that Magento 2 is automatically deployed when needed, so I used manual deployment: `setup:static-content:deploy -f`
4. Now, I get crawl error on google saying:
"pub/static/frontend/Magento/luma/en_US/?resource=frontend/Magento/luma/en_US"
I only got this error after running these commands. The site is never indexed by Google. Please tell me how to fix this?

**Comment by magento-engcom-team** [comment]
@wd7080 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

In console we have message, because this module is dependent and linked to the rest of the modules
Unable to change status of modules because of the following constraints:
Cannot disable Magento_Review because modules depend on it:
Magento_Store: Magento_Store->Magento_Catalog->Magento_Customer->Magento_Review
Magento_AdvancedPricingImportExport: Magento_AdvancedPricingImportExport->Magento_Customer->Magento_Review
Magento_Directory: Magento_Directory->Magento_Backend->Magento_Customer->Magento_Review
Magento_Theme: Magento_Theme->Magento_Customer->Magento_Review
Magento_Backend: Magento_Backend->Magento_Customer->Magento_Review
Magento_Backup: Magento_Backup->Magento_Backend->Magento_Customer->Magento_Review
Magento_Eav: Magento_Eav->Magento_Backend->Magento_Customer->Magento_Review
Magento_Customer: Magento_Customer->Magento_Review
Magento_BundleImportExport: Magento_BundleImportExport->Magento_CatalogImportExport->Magento_Customer->Magento_Review
Magento_CacheInvalidate: Magento_CacheInvalidate->Magento_PageCache->Magento_Backend->Magento_Customer->Magento_Review
Magento_AdminNotification: Magento_AdminNotification->Magento_Backend->Magento_Customer->Magento_Review
Magento_Indexer: Magento_Indexer->Magento_Backend->Magento_Customer->Magento_Review
Magento_CatalogImportExport: Magento_CatalogImportExport->Magento_Customer->Magento_Review
Magento_Cms: Magento_Cms->Magento_Theme->Magento_Customer->Magento_Review
Magento_Rule: Magento_Rule->Magento_Backend->Magento_Customer->Magento_Review
Magento_Catalog: Magento_Catalog->Magento_Customer->Magento_Review
Magento_Search: Magento_Search->Magento_Reports->Magento_Review
Magento_CatalogUrlRewrite: Magento_CatalogUrlRewrite->Magento_Backend->Magento_Customer->Magento_Review
Magento_Widget: Magento_Widget->Magento_Theme->Magento_Customer->Magento_Review
Magento_Quote: Magento_Quote->Magento_Customer->Magento_Review
Magento_Payment: Magento_Payment->Magento_Quote->Magento_Customer->Magento_Review
Magento_CmsUrlRewrite: Magento_CmsUrlRewrite->Magento_Cms->Magento_Theme->Magento_Customer->Magento_Review
Magento_Config: Magento_Config->Magento_Backend->Magento_Customer->Magento_Review
Magento_ConfigurableImportExport: Magento_ConfigurableImportExport->Magento_CatalogImportExport->Magento_Customer->Magento_Review
Magento_Msrp: Magento_Msrp->Magento_Catalog->Magento_Customer->Magento_Review
Magento_CatalogInventory: Magento_CatalogInventory->Magento_Customer->Magento_Review
Magento_Contact: Magento_Contact->Magento_Customer->Magento_Review
Magento_Cookie: Magento_Cookie->Magento_Store->Magento_Catalog->Magento_Customer->Magento_Review
Magento_Cron: Magento_Cron->Magento_Store->Magento_Catalog->Magento_Customer->Magento_Review
Magento_CurrencySymbol: Magento_CurrencySymbol->Magento_Backend->Magento_Customer->Magento_Review
Magento_Bundle: Magento_Bundle->Magento_Customer->Magento_Review
Magento_CustomerImportExport: Magento_CustomerImportExport->Magento_Customer->Magento_Review
Magento_Deploy: Magento_Deploy->Magento_Config->Magento_Backend->Magento_Customer->Magento_Review
Magento_Developer: Magento_Developer->Magento_Config->Magento_Backend->Magento_Customer->Magento_Review
Magento_Dhl: Magento_Dhl->Magento_Backend->Magento_Customer->Magento_Review
Magento_Authorization: Magento_Authorization->Magento_Backend->Magento_Customer->Magento_Review
Magento_Downloadable: Magento_Downloadable->Magento_Customer->Magento_Review
Magento_ImportExport: Magento_ImportExport->Magento_Backend->Magento_Customer->Magento_Review
Magento_Sales: Magento_Sales->Magento_Customer->Magento_Review
Magento_Email: Magento_Email->Magento_Theme->Magento_Customer->Magento_Review
Magento_User: Magento_User->Magento_Backend->Magento_Customer->Magento_Review
Magento_Fedex: Magento_Fedex->Magento_Catalog->Magento_Customer->Magento_Review
Magento_GiftMessage: Magento_GiftMessage->Magento_Customer->Magento_Review
Magento_Checkout: Magento_Checkout->Magento_Customer->Magento_Review
Magento_GoogleAnalytics: Magento_GoogleAnalytics->Magento_Sales->Magento_Customer->Magento_Review
Magento_Ui: Magento_Ui->Magento_Backend->Magento_Customer->Magento_Review
Magento_Security: Magento_Security->Magento_Backend->Magento_Customer->Magento_Review
Magento_GroupedImportExport: Magento_GroupedImportExport->Magento_CatalogImportExport->Magento_Customer->Magento_Review
Magento_GroupedProduct: Magento_GroupedProduct->Magento_Customer->Magento_Review
Magento_DownloadableImportExport: Magento_DownloadableImportExport->Magento_CatalogImportExport->Magento_Customer->Magento_Review
Magento_CatalogRule: Magento_CatalogRule->Magento_Customer->Magento_Review
Magento_InstantPurchase: Magento_InstantPurchase->Magento_Customer->Magento_Review
Magento_Integration: Magento_Integration->Magento_Customer->Magento_Review
Magento_LayeredNavigation: Magento_LayeredNavigation->Magento_Catalog->Magento_Customer->Magento_Review
Magento_Marketplace: Magento_Marketplace->Magento_Backend->Magento_Customer->Magento_Review
Magento_MediaStorage: Magento_MediaStorage->Magento_Backend->Magento_Customer->Magento_Review
Magento_ConfigurableProduct: Magento_ConfigurableProduct->Magento_Customer->Magento_Review
Magento_Multishipping: Magento_Multishipping->Magento_Customer->Magento_Review
Magento_NewRelicReporting: Magento_NewRelicReporting->Magento_Customer->Magento_Review
Magento_Newsletter: Magento_Newsletter->Magento_Customer->Magento_Review
Magento_OfflinePayments: Magento_OfflinePayments->Magento_Checkout->Magento_Customer->Magento_Review
Magento_SalesRule: Magento_SalesRule->Magento_Customer->Magento_Review
Magento_PageCache: Magento_PageCache->Magento_Backend->Magento_Customer->Magento_Review
Magento_Captcha: Magento_Captcha->Magento_Customer->Magento_Review
Magento_Vault: Magento_Vault->Magento_Customer->Magento_Review
Magento_Persistent: Magento_Persistent->Magento_Customer->Magento_Review
Magento_ProductAlert: Magento_ProductAlert->Magento_Customer->Magento_Review
Magento_ProductVideo: Magento_ProductVideo->Magento_Backend->Magento_Customer->Magento_Review
Magento_CheckoutAgreements: Magento_CheckoutAgreements->Magento_Backend->Magento_Customer->Magento_Review
Magento_Reports: Magento_Reports->Magento_Review
Magento_Robots: Magento_Robots->Magento_Store->Magento_Catalog->Magento_Customer->Magento_Review
Magento_Rss: Magento_Rss->Magento_Customer->Magento_Review
Magento_CatalogRuleConfigurable: Magento_CatalogRuleConfigurable->Magento_Catalog->Magento_Customer->Magento_Review
Magento_Authorizenet: Magento_Authorizenet->Magento_Backend->Magento_Customer->Magento_Review
Magento_SalesInventory: Magento_SalesInventory->Magento_Catalog->Magento_Customer->Magento_Review
Magento_OfflineShipping: Magento_OfflineShipping->Magento_Backend->Magento_Customer->Magento_Review
Magento_ConfigurableProductSales: Magento_ConfigurableProductSales->Magento_Catalog->Magento_Customer->Magento_Review
Magento_UrlRewrite: Magento_UrlRewrite->Magento_Backend->Magento_Customer->Magento_Review
Magento_CatalogSearch: Magento_CatalogSearch->Magento_Customer->Magento_Review
Magento_Webapi: Magento_Webapi->Magento_Backend->Magento_Customer->Magento_Review
Magento_SendFriend: Magento_SendFriend->Magento_Customer->Magento_Review
Magento_Shipping: Magento_Shipping->Magento_Customer->Magento_Review
Magento_Sitemap: Magento_Sitemap->Magento_Backend->Magento_Customer->Magento_Review
Magento_Paypal: Magento_Paypal->Magento_Customer->Magento_Review
Magento_Swatches: Magento_Swatches->Magento_Customer->Magento_Review
Magento_Tax: Magento_Tax->Magento_Customer->Magento_Review
Magento_TaxImportExport: Magento_TaxImportExport->Magento_Backend->Magento_Customer->Magento_Review
Magento_GoogleAdwords: Magento_GoogleAdwords->Magento_Sales->Magento_Customer->Magento_Review
Magento_Translation: Magento_Translation->Magento_Backend->Magento_Customer->Magento_Review
Magento_GoogleOptimizer: Magento_GoogleOptimizer->Magento_Backend->Magento_Customer->Magento_Review
Magento_Ups: Magento_Ups->Magento_Backend->Magento_Customer->Magento_Review
Magento_EncryptionKey: Magento_EncryptionKey->Magento_Backend->Magento_Customer->Magento_Review
Magento_Usps: Magento_Usps->Magento_Catalog->Magento_Customer->Magento_Review
Magento_Variable: Magento_Variable->Magento_Backend->Magento_Customer->Magento_Review
Magento_Braintree: Magento_Braintree->Magento_Customer->Magento_Review
Magento_GraphQl: Magento_GraphQl->Magento_Catalog->Magento_Customer->Magento_Review
Magento_WebapiSecurity: Magento_WebapiSecurity->Magento_Webapi->Magento_Backend->Magento_Customer->Magento_Review
Magento_Weee: Magento_Weee->Magento_Customer->Magento_Review
Magento_CatalogWidget: Magento_CatalogWidget->Magento_Customer->Magento_Review
Magento_Wishlist: Magento_Wishlist->Magento_Customer->Magento_Review

**Comment by wd7080** [comment]
Hello, I think the above message is the same message I got when I run that command. My question, is your testing site crawled by google? If yes, you need to check the error log in google webmaster (Google Search Console) after 24 hours. You will find the same error there. You will not reproduce the same error without crawling your site by Google.

**Comment by wd7080** [comment]
Hello
I forgot to mention this, I have also run the following commands through the System CRON Management (which was wrong):
php /bin/magento setup:cron:run
php /bin/magento setup:static-content:deploy
This also caused that error on google...

**Comment by magento-engcom-team** [comment]
@wd7080 , thanks for you update.
For disable module see devdocs:
http://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-subcommands-enable.html

**Comment by magento-engcom-team** [comment]
@wd7080, thank you for your report.
For Google Error We've created internal ticket(s) MAGETWO-85295 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Bravo** [comment]
Hello @wd7080. Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
