### ISSUE TITLE
 Payment method option is not showing under shopping cart rules condition tab

### ISSUE THREAD

**Issue by AbdurBhadarka** [magento/magento2#12549]
I go admin end under left menu:
Marketing > Promotions > Cart Price Rules and create a new Rule: Conditions.

**Comment by magento-engcom-team** [comment]
Hello @AbdurBhadarka. Thanks for reporting. Please specify which version of Magento and wich operating system You use.

**Comment by magento-engcom-team** [comment]
@AbdurBhadarka, thank you for your report.
We've created internal ticket(s) MAGETWO-81449 to track progress on the issue.

**Comment by MohamedQabbani** [comment]
ANY UPDATE?

**Comment by riorubiarjo703** [comment]
ANY UPDATE? (2)

**Comment by magento-engcom-team** [comment]
Hi @AbdurBhadarka. Thank you for your report. 
The issue has been fixed in magento/magento2#20042 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [76ca463a96e3e215cae08a1acacef8eea24cdf44](https://github.com/magento/magento2/commit/76ca463a96e3e215cae08a1acacef8eea24cdf44)

The fix will be available with the upcoming 2.3.1 release.
