### ISSUE TITLE
Magento 2.2 tier price missing in advanced pricing

### ISSUE THREAD

**Issue by ajaymakwana** [magento/magento2#12557]
### Preconditions

1. Magento 2.2.0

### Steps to reproduce

1. Admin -> Catalog -> Products -> Edit Product -> Advanced Pricing

### Expected result

1. Admin can add Tier price. There is only Customer Group Price.

### Actual result

1.
![tierprice](https://user-images.githubusercontent.com/1335843/33655202-6f73f3d6-da98-11e7-8704-f07902ed485a.png)

**Comment by magento-engcom-team** [comment]
@ajaymakwana ,thanks for your report.
Starting with version  2.2.0  Tier price is renaming for Customer group price.

**Comment by magento-engcom-team** [comment]
@ajaymakwana, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
