### ISSUE TITLE
Back-End issue for multi-store website: when editing Order shipping/billing address - allowed countries are selected from wrong Store View  

### ISSUE THREAD

**Issue by svejegres** [magento/magento2#12560]
### Preconditions

1. Magento 2.1.10 CE & 2.3.x
2. PHP 7.0.22
3. MySQL 5.6

### Steps to reproduce

1. Create multi-stores
2. Configure different 'Allow Countries' settings for different stores (Configuration > General > Country Options)
3. Go to Admin > Sales > Orders > Go to any order view page
4. Press "Edit" near Shipping Address: you will see the different values for Country dropdown.

### Expected result

1. Address Country drop-down in Admin should take values from 'Allow Countries' setting configured for the Website Store View where that order was made (e.g.: for German store with id = 7)

### Actual result

1. But it's picking the 'Allow Countries' from first store View (with id=1). 
2. If before steps 3 and 4 from "Steps to reproduce" go to Admin > Sales > Create New Order and when creating it select some different Store View (e.g.: Italian, with id = 10) then actual result after "Steps to reproduce" will show allowed countries for that selected Store View (with id = 10, if continue on example).

----

Similar issue was already mentioned here: https://github.com/magento/magento2/issues/7036
And fixed [here](https://github.com/magento/magento2/commit/863c05a9b2bf6f98934e66aebb81ebd3bf1cca05#diff-a44538b2bdaf2bbd38d71c40fde8c07f).

**Comment by magento-engcom-team** [comment]
@svejegres, thank you for your report.
We've created internal ticket(s) MAGETWO-85220 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @svejegres 
We are closing this issue report now since the fix for the issue is delivered to `2.2-develop` (should be released with 2.2.4).
You may check https://github.com/magento/magento2/commit/506d5004e472f3937d4d67fefce62c9e2ce9c403 for now to get more details on the fix.

Thank you for collaboration.

**Comment by DrewRobertson** [comment]
I'm still getting this problem on 2.3 CE, PHP 7.3

**Comment by g-anedda** [comment]
Had this on 2.1, still have this in 2.3.1.

**Comment by oleksii-lisovyi** [comment]
The issue is not fixed and still is reproducible on Magento 2.3.2.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19722` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @svejegres. Thank you for your report. 
The issue has been fixed in magento/magento2#24345 by @oleksii-lisovyi in 2.3-develop branch
Related commit(s):
 - [d617c3ca6541d1528bf26c26738b909d55424def](https://github.com/magento/magento2/commit/d617c3ca6541d1528bf26c26738b909d55424def)
 - [883d9f52e1b360b5c3c3b9b9f0a7f512531dfe83](https://github.com/magento/magento2/commit/883d9f52e1b360b5c3c3b9b9f0a7f512531dfe83)

The fix will be available with the upcoming 2.3.4 release.
