### ISSUE TITLE
Configurable product price shows 0 when all the simple products are out of stock.

### ISSUE THREAD

**Issue by l1mosh** [magento/magento2#12578]
### Preconditions

1. Magento 2 (ver. 2.1.7)
2. Configurable product price on frontend.

### Steps to reproduce

1. Create configurable product with some simple products options. 
2. Set all the simple product to be out of stock.
3. Then you will see the configurable product price will be 0.

### Expected result

1. Price shown accounting to the out of stock simple.

### Actual result

1. Price is showing as 0.

**Comment by mysil2** [comment]
This is marked as "Fixed in 2.3.x". Anybody know which pull request fixed this in 2.3.x? I'm looking for a temporary fix for my 2.1.x store.

**Comment by p-zamoroka** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@p-zamoroka thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by AndrewMun** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@AndrewMun thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Zamoroka** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@Zamoroka thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by kis28viktor** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@kis28viktor thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mslabko** [comment]
@kis28viktor, please accept invitation and assign issue to yourself

**Comment by dryadav** [comment]
I would like to solve this issue #MM18IN

**Comment by magento-engcom-team** [comment]
@dryadav thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by dryadav** [comment]
@magento-engcom-team  The issue has been fixed in updated version.

**Comment by dr0per435** [comment]
Could someone tell me which pull request fixed this bug?

**Comment by mysil2** [comment]
@albertomario It should be https://github.com/magento/magento2/pull/12936

**Comment by 0franco** [comment]
Any news? Same issue M. Commerce ver. 2.2.2

**Comment by amelojunior** [comment]
Same issue here!

The configurable products stock availability status doesn't change when all associated Simple products go out of stock AND  product price shows 0 in frontend.

v2.2.4

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-12578-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-12578-2-3-0.instances.magento-community.engineering/admin](https://i-12578-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@l1mosh, thank you for reporting this issue. This issue is fixed now or at least we cannot reproduce it on the latest release version. If all simple products are out of stock than configurable disappear from the catalog.

**Comment by vetshopdeveloper** [comment]
@engcom-backlog-andrii  again how can you close this issue? users have reported this in the 2.2 branch.

Do the labels reproduced in 2.2 and 2.1 not mean anything?
