### ISSUE TITLE
REST webapi with "mixed[]" return type does not work anymore

### ISSUE THREAD

**Issue by yaroslav-zenin** [magento/magento2#12597]
Sometimes webapi used to retrieve complex agreggation and for that I've used "mixed" return type to retrieve any structure I need. In magento 2.1.6 was working fine. After migrating to 2.2.1 stop working.
It was done by https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/Reflection/TypeCaster.php#L49
commit hash: 6ba399cdaea5babb373a35e88131a8cbd041b0de
cast @joni-jones 

I tried to fix that in REST via 
```php
   /**
     * @return \stdClass[]
     */
```
and it is working in REST but does not in SOAP, because in SOAP continue working with
```php
   /**
     * @return mixed[]
     */
```

### Preconditions

1. Magento 2.2.1 
2. PHP 7.0
### Steps to reproduce

1. create dummy webapi interface for REST
```php
interface RowsetPageableInterface 
{
    /**
     * @return mixed[]
     */
    function getRowset();

    /**
     * @param array $rowset
     * @return RowsetPageableInterface
     */
    function setRowset(array $rowset);
}

// implement interface
class RowsetPageable implements RowsetPageableInterface
{
    private $rowset = [];

    /**
     * @return array
     */
    public function getRowset()
    {
        return $this->rowset;
    }

    /**
     * @param array $rowset
     * @return $this
     */
    public function setRowset(array $rowset)
    {
        $this->rowset = $rowset;
        return $this;
    }
}

// create some API service and use that object as response
return $this->rowsetPageableFactory->create()->setRowset([
['id' => 1],
['id' => 3],
]);
```

### Expected result

```json
{
    "rowset": [
        {"id": 1},
        {"id": 3}
    ]
}
```

### Actual result

```json
{
    "rowset": [
        "{\"id\":1}",
        "{\"id\":3}"
    ]
}
```

**Comment by YevSent** [comment]
Hi, @yaroslav-zenin, this is expected behavior for the current implementation, because previous didn't process correctly embedded data if the return type specified as an array. The previous behavior caught errors for WEB API https://github.com/magento/magento2/issues/8947.

What is the meaning of `mixed[]` - seems like your interface doesn't have structure. How should WEB API know how to process such interface if there no specific type?

**Comment by yaroslav-zenin** [comment]
@joni-jones 

> this is expected behavior for the current implementation, because previous didn't process correctly embedded data if the return type specified as an array.

if it is cause new issues it is not expected behavior
on SOAP @return mixed[] worked as expected, so, we should have possibility to use similar on REST

> What is the meaning of mixed[] - seems like your interface doesn't have structure. How should WEB API know how to process such interface if there no specific type?

yes, I do not have structure, because it can be very complex structure with nested arrays. SOAP works good with mixed[] annotation and before 2.2.0 magento REST was also fine

BTW, I tried to comment
```php
//        if (is_array($value) && !interface_exists($type) && !class_exists($type)) {
//            return $this->serializer->serialize($value);
//        }
```
it does not #8947 reproduced for me
I understand that commit 6ba399c fix bug but it should not break existing functionality

**Comment by YevSent** [comment]
> @return mixed[]

Such annotation in the interface shows code smell in the API design ([Technical Guidelines 1.2](http://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html#1-basic-programming-principles)) and Magento doesn't have `@api` interfaces with `mixed[]` return type and has a small amount of `@api` interfaces with `mixed` return type. The `mixed` it's only pseudo-type and in general doesn't represent any real scalar or compound type.

> it does not #8947 reproduced for me

I can be reproduced if some method has the return tag like `string[]|int[]|etc` but the method returns an array of arrays.

Anyway, I will check the specified case and will update this ticket.

**Comment by YevSent** [comment]
@yaroslav-zenin, I've checked described case and there is some summary.

For example, an interface for order payment has `getAdditionalInformation()` method with `string[]` return type. This method can contain nested arrays:
```php
[
    'entity' =>
    [
        ['attribute' => 'id'],
        ['attribute' => 'title'],
    ]
]
```
In 2.1.x, such code caused PHP notice: `"Notice: Array to string conversion in lib/internal/Magento/Framework/Reflection/TypeCaster.php on line 58"`.

Starting at 2.2.0, it will return this array as json represented string:
```json
"additional_information":
{
    "entity": "[{'attribute':'id'},{'attribute':'title'}]"
}
```
If this method would have `mixed[]` it would return in 2.1.x:
```json
"additional_information": {
    "entity": [{
        "id": 1
    }, {
        "id": 2
    }]
}
```
But, as I previously said, Magento doesn't have `@api` interfaces with `mixed[]` return type and only legacy `@api` interfaces with `mixed` annotation, because this is pseudo-type, and, according to Magento tech vision, interface methods should return scalar types, arrays, and objects. That's why it's expected behavior and not a bug.

But, if you want, to change such behavior you can always add plugin for `\Magento\Framework\Reflection\TypeCaster::castValueToType`, for example simple fix:
```php
...
if ((is_array($value) && $type !== 'mixed') && !interface_exists($type) && !class_exists($type)) {
    return $this->serializer->serialize($value);
}
...
```

**Comment by juniorkid** [comment]
Hello, I have same problem with magento2.2. So I use your solution but it can't fix this problem. How can I do for solve this problem ?

**Comment by PivitParkour94** [comment]
So to be clear, we can't have any sort of api methods like `getData` for a custom model we create in a module, and return something like `mixed[]`? And this isn't considered a breaking change? It was definitely working previously and suddenly all the saving methods for our custom module is broken. Is having a method like `getData` not supposed to exist on the interface?

This seems like a really big change, because now we have to refactor a bunch of modules that were working fine previously...
