### ISSUE TITLE
Couldn't select all items on Review grid

### ISSUE THREAD

**Issue by paul-at-straker** [magento/magento2#12594]
I couldn't select all items on review grid.
### Preconditions

1. Magento 2.2.1
2. PHP 7.1.12

### Steps to reproduce

1. login Magento admin
2. from main menu, select `MARKETING -> User Content -> Reviews`
3. select `Select All` under `Actions` checkbox

### Expected result

1. it should show <code>346 records found (<b>346</b> selected)</code>

### Actual result

1. it should show <code>346 records found (<b>20</b> selected)</code>

**Comment by magento-engcom-team** [comment]
@paul-at-straker, thank you for your report.
We've created internal ticket(s) MAGETWO-85227 to track progress on the issue.

**Comment by osrecio** [comment]
The problem is due to: [MassAction/Extended.php](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Backend/Block/Widget/Grid/Massaction/Extended.php#L285).  When try to get: `getColumValues` from [Review\Product\Collection](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Review/Model/ResourceModel/Review/Product/Collection.php#L520) the [collection is loaded](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L746) and only get the first 20 Product Reviews.

In this moment I don't know what is the best way to solve this issue. I will continue investigating.

Thanks for the catch @paul-at-straker

**Comment by paul-at-straker** [comment]
As far as know `getGridIdsJson()` in the version of 2.1.x uses [getAllIds](https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/Backend/Block/Widget/Grid/Massaction/Extended.php#L275) instead of `getColumValues()`. I have tried to replace the entire `getGridIdsJson()` with the code copied from version `2.1.x`, it works. Although I haven't looked at it deeply, it might be helpful.

**Comment by osrecio** [comment]
Yes, This changes was made to allow get Id's not only for primary key: https://github.com/magento/magento2/issues/9610.

**Comment by osrecio** [comment]
Same happens in Grid Notification.

Ivestigating possibilities to fix #9610

**Comment by sheenu3091** [comment]
I am working in at #dmcdindia

**Comment by magento-engcom-team** [comment]
@sheenu3091 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by jspoe** [comment]
I would suggest to change this into an ui-component with a proper data-provider instead of the old Grid-block method, to make it future proof and generic with the other grids.
This should fix this bug too.

**Comment by jspoe** [comment]
@magento-engcom-team @okorshenko Do you agree with this approach? If that is the case, I will continue to work on this solution.

**Comment by VladimirZaets** [comment]
Hi @jspoe. I agree that this issue should be fixed only in the ui-component grid, no sense to fix it in the old grids. 
The correct fix for this issue is replacing the old grid with ui-component grid.
@jspoe As I see the ui-component grid works correctly (screenshots are attached. We can select items per page or all items in all pages), so I don't fully understand the solution in the ui-component grid you said, could you please provide more information?
<img width="258" alt="screen shot 2018-08-15 at 17 57 51" src="https://user-images.githubusercontent.com/8035672/44157597-807ffc80-a0bb-11e8-939e-e58a6fa3d240.png">
<img width="412" alt="screen shot 2018-08-15 at 17 58 07" src="https://user-images.githubusercontent.com/8035672/44157598-81189300-a0bb-11e8-81b4-ca742aeb764a.png">

**Comment by jspoe** [comment]
@VladimirZaets The scenario where this can be reproduced (Marketing -> User Content -> Reviews) is an old grid. This should be transformed from an old grid into an UiComponent instead of just fix the selection bug of the grid.

Before I spent a couple of hours in transforming the old grid into an UiComponent and removing all the references and files of the old grid. It would be a waste of time if this change was already made in another issue or by another team. Therefor I just wanted to have the confirmation to make this whole change instead of only fix the selection bug. :)

**Comment by raisaev** [comment]
Transforming the Reviews grid to the version based on UiComponent is definitely a good thing.

But the issue can be reproduced on ANY of grids that still use the old approach. Yes, perhaps this is really the last of the grids that do not use UiComponent in Magento Core but there can be a lot in other extensions written for M2.

A good solution is to do both:
- fix the selection bug for all old grids
- transform Reviews grid to the UiComponent approach

**Comment by jspoe** [comment]
Agreed, I'll work on the bugfix first then and make a pull request for the UiComponent afterwards.

**Comment by jspoe** [comment]
Debugged this right down to the problem, with the given information of [#9610
](https://github.com/magento/magento2/issues/9610)

The problem is the fact that the change to getColumnValues() did not take in account that a collection already could be loaded with a given limit. In the case of the toolbar of the review grid. The collection gets loaded and the default methods to reset it are not possible, because of an afterLoad in Model/ResourceModel/Review.php that joins the store table onto it. That will result in a correlation error because the afterLoad method will be called twice.

Solution in this case might be to have a cloned version of an (yet) unloaded collection in Magento/Backend/Block/Widget/Grid/Extended.php. But that is not a solid solution either, because you'll have a second collection in your object and thus maks the object heavier than it should be. I also thought of the getSelectCountSql() that is available in most collections and in the AbstractDb class, but that might also result in some unwanted constructions because you could miss the column that you want to use.

**Comment by slavvka** [comment]
@jspoe Could you give me more details about `correlation error`. As far as I can see `_addStoreData()` will overwrite `stores` data in case we call `clear()` to reset a collection.

**Comment by jspoe** [comment]
@slavvka You are correct, it will overwrite it, that is not the problem. The problem is that getColumnValues() will call $this->getItems(), which will call load().
In that cycle, _beforeLoad() and _afterLoad() are called and as far as I can see, the _beforeLoad will already give the correlation error, because it will call _applyStoresFilterToSelect() that joins the store column onto the select, that was already added by the _addStoreData() function.

**Comment by slavvka** [comment]
@jspoe Now I can see. The issue is not in `_addStoreData()` it is in `_applyStoresFilterToSelect()`. I do agree that a generic solution is much better (e.g. that you used in your PR #18060). But it requires making a breaking change which is forbidden for both 2.2.x and 2.3.x patch releases. I cannot see generic solution right now. Could you look at checking if store joins were applied to fix it just for Review Grid?

**Comment by slavvka** [comment]
@jspoe You could refer to the solution in `\Magento\Store\Model\ResourceModel\Website\Collection::joinGroupAndStore`

**Comment by jspoe** [comment]
@slavvka Certainly, will check for alternative asap.

**Comment by kirtinariya1** [comment]
Still not working in latest released Magento 2.3.1 

Any updated on this ?

**Comment by dkyosev9** [comment]
Magento 2.3.1 - When "Select All" rows from the grid, then the grid filter doesn't read all rows but only those on the first grid page.
The expected result is to get all rows not only those on first page.
This is shame that such a simple thing is an issue in a few Magento releases and not fixed yet.
Please, fix it as this is very important for the admin area. Literally an admin can't select all rows and do mass actions to all selected rows.
It worked perfectly well on Magento 2.2.2.
