### ISSUE TITLE
reorder redirecting to cart page

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1260]
i registered an account & placed an order.now if i click in reorder link in my account->my orders section->grid.
first its showing like this.
"Shopping Cart

You have no items in your shopping cart.

Click here to continue shopping."
then its showing cart page properly.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-37251

**Comment by sivaschenko** [comment]
@sivajik34 Are you still able to reproduce this issue?

**Comment by okorshenko** [comment]
@sivajik34 , Please, let us know if you still have an issue

**Comment by seo99ita** [comment]
I have the same problem.
I arrived here because Magento 2 sends 15 times the same email.
I noticed the cron_schedule table that generated the same job many times at the same time.
![schermata 2018-03-08 alle 22 08 00](https://user-images.githubusercontent.com/35658761/37176700-6ef7e6ec-231d-11e8-9353-bc1b1c76d855.png)
