### ISSUE TITLE
Web Setup Wizard issue 401 error 

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#12608]
Strange issue, Need Solving by Magento team. 

**Preconditions**

Magento 2.2.1

**Steps to reproduce**

1. Changed the base URL & Base Link URL to HTTPS Web Setup Wizard Gives 401 error.

2. When changed the Url back to HTTP  Web Setup wizard loads without any issues.

**Expected result**

Web Setup wizard should load properly without any issues even upon changing the base URL & Base Link URL to HTTPS

**Actual result**

![websetup](https://user-images.githubusercontent.com/13229022/33796194-f789a894-dd43-11e7-8a60-417736c53269.png)

**Comment by magento-engcom-team** [comment]
@terrybakshi, thank you for your report.
We've created internal ticket(s) MAGETWO-85591 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @terrybakshi thank you for you report, this issue has already fixed in 2.2.6 release 
![selection_300](https://user-images.githubusercontent.com/40756439/51904611-bf82df80-23c7-11e9-8502-fa4ff30f1d9b.png)

**Comment by horst-creationell** [comment]
Web Setup Wizard is missing in 2.27 again!?
![image](https://user-images.githubusercontent.com/43030949/52482281-21ee9380-2bb1-11e9-9eb6-2ff57f0adc15.png)
Could you please check behaviour too?
Thanks
