### ISSUE TITLE
Referer is not added to login url in checkout config

### ISSUE THREAD

**Issue by quisse** [magento/magento2#12627]
When disabling the `Redirect Customer to Account Dashboard after Logging in` setting, the login url should include an referer. This works but not in the `window.checkout` object.
### Preconditions

1. Magento 2.1.10
2. PHP 7.0.25

### Steps to reproduce

1. Enable `Redirect Customer to Account Dashboard after Logging in` in the Magento backend.
2. Retrieve the login url from the `window.checkout` object (key is customerLoginUrl)

### Expected result

1. The `window.checkout.customerLoginUrl` contains an url which includes the referer in base64 encoding. For example: `https://myshop.com/customer/account/login/referer/aHR0cHM6Ly9teXNob3AuY29tL2NoZWNrb3V0`

### Actual result

1. The login url without referer. For example: `https://myshop.com/customer/account/login`

**Comment by magento-engcom-team** [comment]
@quisse, thank you for your report.
We've created internal ticket(s) MAGETWO-85542 to track progress on the issue.

**Comment by okorshenko** [comment]
Hi @quisse. Thank you for your report. 
The issue has been fixed in magento/magento2#12630 by @quisse in 2.2-develop branch
Related commits:
 - 6f7219f4d2a6cb43cb3b7e8805a096d6df63ca44
 - 2602e7ec18fd2f0bed5fefeee91a52b0fbde160e
 - 115ba8ef9d739ee131fccf5baff6d3a8b9d4b192
 - 97f77e64e7db6c04958632906ae9519590918414
 - bb3932cfdb8985fe8c1e752ab99414bdffc47ebf
 - 8986107dfe5dadb582fc11113287cc933b06cf9e
 - 5c87fb020fb2317eeaef1dc76132b3bd272b05ec
 - 4350858fe93f76ecebcb560ba746004f66570192

The fix will be available with the upcoming patch release.
