### ISSUE TITLE
Tax rounding row order

### ISSUE THREAD

**Issue by versdivers** [magento/magento2#12643]
### Preconditions
1.  magento 2.2.1
2. php 7.0.2

### Steps to reproduce
1.  create 4 products with same price €2.27
2.  add them to an order with 21% tax and 4 qty each
3.  process the order

### Expected result
1.  since `2.27 * 4 * 1.21 = 10.9868` -> all rows should have €10.99 as a result

### Actual result
1. the price is somehow different for one 1 row (see screenshot)
![image](https://user-images.githubusercontent.com/18028151/33860566-c6a56e60-ded9-11e7-9173-2c2c00747348.png)

This propable because somewhere (not sure why) it calculates all the prices and corrects itself in 1 or more prices before it rounds to have the total 'right'. 

Most booking softwares round this/row so creating an API becomes difficult

**Comment by magento-engcom-team** [comment]
Hello @versdivers. Thanks for reporting. You must have been used the default setting for Tax Calculation Method Based On that is Total (Stores->Configuration->Sales->Tax->Calculation Settings). And this calculating option works correctly, because 16 (4*4) units each with the price of 2.27 compound an amount of 36.32 which then according to option's name (Total) is added with 21% and finally becomes equal to 43.95. If each position in the order (4 units) were displayed as 10.99 one after counting them together would obtain an amount of 43.96 that is not correct. But there are two more options for tax calculation: Unit Price and Row Total. Each option begins rounding at different stages of order calculation. (As for Your very case each of the three possible options give different display results in the order. For example Row Total option leads to 10.99 to be displayed for each position but the total is already not 43.95 but 43.96). So You may chose which option suites You the best.

**Comment by magento-engcom-team** [comment]
@versdivers, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
