### ISSUE TITLE
Zero Subtotal Checkout New Order Status Always Pending

### ISSUE THREAD

**Issue by BernardRobbins** [magento/magento2#12642]
Steps to reproduce
Enable Zero Subtotal Checkout.
Change New Order Status to anything that is not pending.
Create $0 priced product per group.
Setup $0 priced shipping for $0 subtotal.
Checkout with $0 priced product and $0 shipping.

Expected result:
Order will be the same as New Order Status.

Actual result:
New orders will always be pending. 

Magento ver. 2.1.10
PHP 7.0.22 & PHP 7.0.25
mysql  5.6.36-82.0 & 5.6.35

**Comment by magento-engcom-team** [comment]
@BernardRobbins , thank you for your report.
If you changing Automatically Invoice All Items to Yes, status of order is changing.
See attachment
![free_conf_0891280977](https://user-images.githubusercontent.com/31669971/33874399-52fc7302-df27-11e7-9df2-52c948f33404.png)

**Comment by BernardRobbins** [comment]
Thank you. That will work for us. It's not intuitive that auto invoicing is required.

**Comment by magento-engcom-team** [comment]
@BernardRobbins, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
