### ISSUE TITLE
Multiselect Attribute is not saved for a product in the admin panel when it has a related product using another attribute set

### ISSUE THREAD

**Issue by bmisyura** [magento/magento2#12699]
### Preconditions

1. Install Magento from 2.2.-develop branch

### Steps to reproduce

1. Create 2 attribute sets from the Default one.
2. Create a multi-select attribute and assign it to set #1.
3. Create a product 1 with attribute set #2.
4. Create a product 2 with attribute set #1 and set a product 1 as it's related product.
5. Save product 2 without populating the multi-select.
6. Edit the product 2, populate multi-select and click save.
7. Notice the selected option is not saved

### Expected result

Multiselect Attribute should be saved for a product in the admin panel when it has a related product using another attribute set.

### Actual result

Multiselect Attribute is not saved for a product in the admin panel when it has a related product using another attribute set

**Comment by andrii-dymov** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@awarche thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by andrii-dymov** [comment]
The issue is in Eav AbstractEntity which stores linked product's attribute codes after we load linked products.
These codes do not include our multiselect attribute, therefore it's skipped in beforeSave method, it's array value is not converted to a string literal and UpdateHandler silently skips it.
Already fixed in 2.1 branch, working on backport.

**Comment by ishakhsuvarov** [comment]
Closing, as the issue seems to be fixed in `2.2-develop` with the PR #12767
Thanks.

**Comment by magento-engcom-team** [comment]
Hi @bmisyura. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1362 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 4705e23479eae053947c52ee5be6969a79a82079
 - 6d355e033e513cefc390f26417eb2321756b1dce
 - 77f34cf7e3e12f567aa8fdd6918bcf9cd1ffda2f
 - 748ab4db199379ce2154ffb63b9801a8c0d13bb4
 - 90f9d95056b1cd7fe0be036ec72c236bc03738fc
 - 44ca24fdc0d3367515893cf9a8fc1bffcc070140
 - f0b7f2b1708218a8d894178fc9a4f045dfdbdedd
 - c3e1d93db404b63dc38050f9089d2b6a72094085
 - 4810755a4751e3a389e2a39dcbaf55ab72c2149c
 - 4709a222e58918876e2f5b9d28b8f0e5e120d52f
 - a2b9fab4b10421c327b1f323bf222750ac371fb9
 - ac7df33cecf744cf9899067dc62453bc7a15ca50
 - 245238dcbb72b10fad84596399b12b9814295641
 - 2c153c3c428308c1cbc1969bd2eb271913d6551d
 - 48a72fa0d214418a79a5d77d25ead1eb75cbc1c1
 - 625f685c183e0c0a7993ca38c025a079e0e29b47
 - afa4516615808a427be8a160e9cd6ae80c321b27

The fix will be available with the upcoming 2.3.0 release.
