### ISSUE TITLE
Unable to change attribute type from swatch to dropdown 

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12695]
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Product attribute is created (Stores > Attributes > Product):
- Catalog Input Type for Store Owner = **Visual Swatch**
- Scope = Global
3. Created product attribute is added to Default attribute set (Stores > Attributes > Attribute Set)

### Steps to reproduce
1. Create new configurable product based attribute from precondition
2. Check this product on frontend - options displays as visual swatches 
3. Go to attribute and change "Catalog Input Type for Store Owner" = **Dropdown**
4. Clear Cache
5. Check product page on frontend

### Expected result
Options still displays as visual swatches

### Actual result
Options is shown as dropdown

**Comment by eugene-shab** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@eugene-shab thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by eugene-shab** [comment]
Maybe similar to #11703

**Comment by eugene-shab** [comment]
Maybe similar to #12695

**Comment by samaybhavsar** [comment]
Is there any workaround ?

**Comment by ktan88** [comment]
Hello Samay.
There was another thread, where somebody gave a hint.
Truncate the table eav_attribute_option_swatch and flush the cache.
For me this worked.

**Comment by Axeldekker** [comment]
I have the same problem, but I only have it for the options for manufacturer and color. If I truncate the eav_attribute_option_swatch settings I will lose all the data that still works. What is the work around?

**Comment by axovel** [comment]
Any update on this ?

**Comment by eugene-shab** [comment]
This issue related to the - https://github.com/magento/magento2/pull/12771
Waiting for merge.

**Comment by sidolov** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento/magento2#12771 by @eugene-shab in 2.2-develop branch
Related commit(s):
 - [39b1ef3a5b5a4741a0c664135b13944c4e7c7b61](https://github.com/magento/magento2/commit/39b1ef3a5b5a4741a0c664135b13944c4e7c7b61)
 - [94539b755992f120927a4760c06c624a0ced07c7](https://github.com/magento/magento2/commit/94539b755992f120927a4760c06c624a0ced07c7)
 - [3d76096a752ff234843890d7a072cd1d64e8c1c2](https://github.com/magento/magento2/commit/3d76096a752ff234843890d7a072cd1d64e8c1c2)
 - [0b079e05ab2e12c004fb1e81bda57817e5f0f14f](https://github.com/magento/magento2/commit/0b079e05ab2e12c004fb1e81bda57817e5f0f14f)
 - [71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79](https://github.com/magento/magento2/commit/71d30b7c521fd5143a4cfd3252fa5c7c2c4fdd79)
 - [47b2f4841ae27fa7bde0124e8860493e79c62a92](https://github.com/magento/magento2/commit/47b2f4841ae27fa7bde0124e8860493e79c62a92)
 - [707f1cd34f0f4c905b07658849984d0eb825d6d7](https://github.com/magento/magento2/commit/707f1cd34f0f4c905b07658849984d0eb825d6d7)
 - [9153fe221d7ce9e65a3b082ab9d79c26245f1e0b](https://github.com/magento/magento2/commit/9153fe221d7ce9e65a3b082ab9d79c26245f1e0b)
 - [1bd4acfee8a58b035eef561aaebe94f97990a4a2](https://github.com/magento/magento2/commit/1bd4acfee8a58b035eef561aaebe94f97990a4a2)
 - [f4990277bf9f20227402f4b76e57499873b170ad](https://github.com/magento/magento2/commit/f4990277bf9f20227402f4b76e57499873b170ad)
 - [3fa9ed2485a97972133ddb1f7d7e775f784fe6e4](https://github.com/magento/magento2/commit/3fa9ed2485a97972133ddb1f7d7e775f784fe6e4)
 - [8fa792a1444670e60fe6052c77e7b35684549906](https://github.com/magento/magento2/commit/8fa792a1444670e60fe6052c77e7b35684549906)
 - [7cd7adecf598dd6f9fe6ecd4369208869442387d](https://github.com/magento/magento2/commit/7cd7adecf598dd6f9fe6ecd4369208869442387d)
 - [54ad76c1f48eafbfe16a4e8e3c7669145a190627](https://github.com/magento/magento2/commit/54ad76c1f48eafbfe16a4e8e3c7669145a190627)
 - [bd126512cfe4f139a10ada9136495c1a617df158](https://github.com/magento/magento2/commit/bd126512cfe4f139a10ada9136495c1a617df158)
 - [cb6975c3f57739946cb65acebaf62300def1fa99](https://github.com/magento/magento2/commit/cb6975c3f57739946cb65acebaf62300def1fa99)

The fix will be available with the upcoming 2.2.6 release.

**Comment by arielmorry** [comment]
I had the same issue on 2.2.5.

I changed my custom Visual Swatches Attributes to Drop Down > flush cache > changed it again to Visual Swatches.

Now I see Visual Swatches instead of Drop Down.

**Comment by ishakhsuvarov** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento/magento2#17750 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [0f28b61565c3108281ef24c5f846ba2034e9ba9c](https://github.com/magento/magento2/commit/0f28b61565c3108281ef24c5f846ba2034e9ba9c)
 - [d159921f79c68e9aec489192c223ce5535ff47d9](https://github.com/magento/magento2/commit/d159921f79c68e9aec489192c223ce5535ff47d9)

The fix will be available with the upcoming 2.3.0 release.
