### ISSUE TITLE
Integrity constraint violation error after reordering product with custom options

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12705]
### Preconditions
1. Magento with Sample Data is installed from 2.2-develop branch

### Steps to reproduce
1. Go to Admin > Products > Catalog
2. Click **Add product** button
3. Fill in information for the item
- Product name = testprod
- Sku = testprod
- Add product to any category
- At the *Configurations* section click **Edit Configurations** button
-- Select color and size from the list and click **Next**
-- Select Colors Black and Blue from the Color Section, and Size S, M, L from the Size section and click **Next**
	-- At the next screen enter the following configuration:
	--- Images: Skip image uploading at this time
	--- Price: Apply single price to all SKUs = 100 
	--- Quantity: Apply single quantity to each Skus = 10
- At the _Customizable Options_ click on **Add Option** button
	-- Option 1
	--- Option title: opt1
	--- Option type: radio button
	--- Required: leave it empty
	--- Title: option 1
	--- Price 10.00
	--- Price type: fixed
	--- Sku: 22
	-- Option 2
	--- Option title: opt2
	--- Option type: radio button
	--- Title: option 2
	--- Price 15.00
	--- Price type: fixed
	--- Sku: 21
- Click **Save** to save the item.
4. Go to the Storefront and find the item testprod
5. Add the first item to the cart by choosing the following configuration:
	- Color: Black
	- Size: S
	- Opt1: option1 + $10.00
	- Opt2: None
	- Qty: 1
6. Add the second item to the cart by choosing the following configuration:
	Color: Black
	Size: S
	Opt1: None
	Opt2: option2 + $15.00
	Qty: 1
7. Go to Admin and find your recent order in Sales > Orders
6. Click on the view link and once the order loads click **Reorder** button

### Expected result
New order page is opened 

### Actual result
Unable to reorder, error is thrown and logged in var/report 

Log from var/report:
 [a:4:{i:0;s:386:"SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dbname`.`quote_item_option`, CONSTRAINT `QUOTE_ITEM_OPTION_ITEM_ID_QUOTE_ITEM_ITEM_ID` FOREIGN KEY (`item_id`) REFERENCES `quote_item` (`item_id`) ON DELETE CASCADE), query was: INSERT INTO `quote_item_option` (`product_id`, `code`, `value`) VALUES (?, ?, ?)";i:1;s:13245:"#0 /pathToMagentoFolder/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)

**Comment by demtaric** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@demtaric thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by vinayshah** [comment]
Hello I am looking for this issue #mm18in

**Comment by magento-engcom-team** [comment]
@vinayshah thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-team** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento/magento2#13036 by @vinayshah in 2.2-develop branch
Related commit(s):
 - 843bc6229ba141cd1f326eeb90013c342c2d2983
 - f89e04d8252a672fef58d5d7eea9331ed8a5222f
 - df96b51224f928cde3919cf6a69ca8c4236afc86

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1359 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 1db3f8f6a336026d4a4493c8ba8d3e165ade66d8
 - 412d2287ee5a1a9620fb2a256bab562bdd10fe49
 - 02620b09456d77408ccbbd6a6b61a7b7ebcf73fa
 - 57c5d8a819e403905bd4d5419564d184712bc142
 - 94a3f0346ea086626d8b11c08fd397b11a570caa
 - 0d557dc99c15c6638e1c894ce46cb681a74b8912
 - 48baf590f86590c44bba81a9d5303902aed9d8d7
 - dc3bb78962c4522eb5df8a1a8f40c3bbe2b623fc
 - 0ab45334ef4d44e55c9f84f9c6e4b6a9e08e9237
 - 00f64b077ce00e55216e6ea9fb39071dc74b51a1
 - 440a1b5f9e6309fa87790a5f5b7d1b8fd7ffa53d
 - 4ed8f5b65d5d1779522653102120917c5f9578be
 - 656eeb5587eb1baebaffdc8ba68f1028afda8910
 - fd2f731f7efc4a2cec9e03f8de88bf39c0988829
 - 2c1a23faa60805bd63ff62216309d57a052612d1
 - f7ff71a92bcf56679b82c22549244e1adb9f4ed2
 - ac9bcfa15b1b0b98f9cb3851f4d9b56e18ede89b
 - 55debe0c2b514e37271ed6edf20b95fec6cc41c9
 - 349508628dc1c4334e13b3541227505e26c93c64
 - d678f1568b6e2d30c6d651dd3da02e0f3512353e
 - bf8ee3089f005e267f0b14cf81b14e9a3ee26986
 - 335c91c07dde6f90309f11cf0efcbd9127630955
 - c5a823f95161f7c13fb0947abb445fdc9e9a620a
 - 696a5a575513bb87c47ffc15a571034b0b91d7ae

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento/magento2#13394 by @vinayshah in 2.3-develop branch
Related commit(s):
 - [b5b4530d41260ce59d291e660dfbd9f79d57a213](https://github.com/magento/magento2/commit/b5b4530d41260ce59d291e660dfbd9f79d57a213)

The fix will be available with the upcoming 2.3.0 release.
