### ISSUE TITLE
back button not working in edit order status

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1270]
stores->order status.->create or edit any order status->back button not working in edit order status.
and reset button also.

**Comment by vpelipenko** [comment]
Do you get this issue for all placed orders?

**Comment by sivaschenko** [comment]
@sivajik34, I cannot reproduce this issue, could you please provide a bit more details to help me?

**Comment by sivajik34** [comment]
its not in orders.please go to stores->order status->edit any order status

**Comment by sivaschenko** [comment]
I see, but I still need more details. What browser are you using, do you have any messages in console?

**Comment by sivajik34** [comment]
mozilla.ubutu 14.04

**Comment by vpelipenko** [comment]
hm.. still do not success with reproducing this issue locally. @sivajik34, could you provide more details if is possible? Does this issue happen on all your magento instances? Did you try to do new installation?

**Comment by sivajik34** [comment]
ver. 0.74.0-beta8
![status](https://cloud.githubusercontent.com/assets/7636894/7615075/8fb2f782-f9b8-11e4-93d4-da78e7ef7e8a.png)

**Comment by sivajik34** [comment]
after deleting pub/static/_requirejs/adminhtml
its working fine

**Comment by magento-engcom-team** [comment]
Hi @sivajik34. Thank you for your report. 
The issue has been fixed in magento/magento2#27976 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [ac3aa709a6fbb9b7f3aa603fdf296e7cc7b35b07](https://github.com/magento/magento2/commit/ac3aa709a6fbb9b7f3aa603fdf296e7cc7b35b07)

The fix will be available with the upcoming 2.4.0 release.
