### ISSUE TITLE
Default Welcome message is broken on storefront with enabled translate-inline

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12711]
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Several products are created

### Steps to reproduce
1. Add product to cart on Storefront
2. Login to admin area
3. Set **Enabled for Storefront** option to **Yes** (Stores > Configuration > Advanced > Developer > Translate Inline) and save configuration
4. Refresh magento cache
5. Go to storefront as guest

### Expected result
Default welcome msg! is not broken

### Actual result
Default welcome msg!  is broken, see screenshot for details
<img width="1552" alt="defaultwelcomemsg" src="https://user-images.githubusercontent.com/9049705/33996342-945c28c4-e0e9-11e7-963d-deb4384726a5.png">

**Comment by KostiantynZhydkovskyi** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@KonstantinZhidkovskiy thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by pareshpansuriya** [comment]
I am looking for this issue #mm18in.

**Comment by magento-engcom-team** [comment]
@paresh1 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento/magento2#13038 by @pareshpansuriya in 2.2-develop branch
Related commit(s):
 - [6144c4f0b6d37908ca58e7fe065091299da7d7dc](https://github.com/magento/magento2/commit/6144c4f0b6d37908ca58e7fe065091299da7d7dc)
 - [7e913f177b1962d887a56af2e98dd8e2ef6748aa](https://github.com/magento/magento2/commit/7e913f177b1962d887a56af2e98dd8e2ef6748aa)
 - [cbc704d71f7a6b31b20c603dade2e8c52438acce](https://github.com/magento/magento2/commit/cbc704d71f7a6b31b20c603dade2e8c52438acce)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento/magento2#14177 by @dimonovp in 2.3-develop branch
Related commit(s):
 - [4147b53d52cbefa60028d693722facbf87f9c128](https://github.com/magento/magento2/commit/4147b53d52cbefa60028d693722facbf87f9c128)
 - [06104496d566917f5649208f0157245abea4a804](https://github.com/magento/magento2/commit/06104496d566917f5649208f0157245abea4a804)
 - [5367c47ee473d165af95b0c732ff016f78aeeb65](https://github.com/magento/magento2/commit/5367c47ee473d165af95b0c732ff016f78aeeb65)

The fix will be available with the upcoming 2.3.0 release.
