### ISSUE TITLE
Welcome message is shown with customer's first and last names after confirming account

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12719]
### Preconditions
1. Magento is installed from 2.2-develop branch
2. Set **Require Emails Confirmation = Yes** at Stores > Configuration > Customers > Customer Configuration

### Steps to reproduce
1. Go to Storefront as a guest
2. Start creating new customer
3. Fill in all the required fields
4. Click **Create an Account**
5. Open confirmation email and click the **Confirm Your Account** button

### Expected result
Website loads with customer logged in, welcome message contains customer's first and last names

### Actual result
Website loads with customer logged in, welcome message does not contain customer's first and last names

**Comment by xpoback** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@xpoback thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by okorshenko** [comment]
Hi @alena-marchenko. Thank you for your report. The issue has been fixed in magento/magento2#12738 by @xpoback in 2.2-develop branch
Related commits:
 - 1. 6b9c39cadfe86a62a5b0c4b13470431f0409c651
The fix will be available with upcoming patch release.

**Comment by okorshenko** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento/magento2#12738 by @xpoback in 2.2-develop branch
Related commits:
 - 6b9c39cadfe86a62a5b0c4b13470431f0409c651

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
Hi @alena-marchenko. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1298 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 54301a8ea63134b961d6b7b9891c31bc2798f8dc
 - 402b719168fc8b17ebc099c12b85f629cf90303b
 - 3837f2780b32112b7f70a9d3074158ee2336b1b7
 - 031e23e93ffaa258a39dfed5c5edb0e873ab0aa8
 - aa267f462f7eb964226a9c89d20c04b718406337
 - 934818dbee0bd36ec5eae7b3b7230c4d8a70b481
 - 6bed7d475bff5e98e27b8fdcaa998438bc31ed05
 - 72b2794043afd0012f9a8d5f6fc04df07acad3af
 - 4e64c415e26845826b527c17008eda00d3808591
 - d3feb280ed621c5ffe2dc3a2b7ac30abb25d9c22
 - 7aeccea46d2336a1322811a9d60d52432108c8e3
 - b857c022ae1cdb7975cf5c3d79cd679843c72a3b
 - a75bf2391dfc6e7c8a1283490f5de7551de42bbe
 - ab2e5798e529633f770c3970a0df999c11764e06
 - d904690443d43322c5dd2c58d075944eae867316
 - a821c7a3c17eb06983f421c47a7cc0fe99983a38
 - 68ac4c0bd6cae6b5b62e683c23f49293ee41d797
 - 93fe4d14faba635cc7c668b2d931e7595567cda9
 - f43fd4b98c55e1f498d060aeb245e4c969bdcb13
 - 2c52a8fd15cff7af7245573e2f26be6d601acb08

The fix will be available with the upcoming 2.3.0 release.
