### ISSUE TITLE
Latest Google Chrome Browser issue with duplicate #email

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#12712]
Magento 2.1.7
Latest Google Chrome Version { Version 63.0.3239.84 (Official Build) (64-bit) } detects duplicate ids and console.log an ERROR

Navigate to Magento default contact page the form#contact-form contain #email and the login at header form#login-form also  contain #email that gives the error: attached screenshot.
<img width="1282" alt="screen shot 2017-12-14 at 14 57 36" src="https://user-images.githubusercontent.com/3495481/33998750-6974054a-e0e0-11e7-820a-9b16683e5981.png">

Thanks.

**Comment by magento-engcom-team** [comment]
@lano-vargas, thank you for your report.
We've created internal ticket(s) MAGETWO-85675 to track progress on the issue.

**Comment by magento-team** [comment]
Hi @lano-vargas. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1036 by @serhii-balko in 2.2-develop branch
Related commit(s):
 - 781ec89aaca6e6ee2853e98065416614f2edffce

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @lano-vargas. Thank you for your report. 
The issue has been fixed in magento/magento2#14867 by @julienanquetil in 2.3-develop branch
Related commit(s):
 - [b7c0f1b6c2ddc8b2a50a1550a4a6265f8a1916e2](https://github.com/magento/magento2/commit/b7c0f1b6c2ddc8b2a50a1550a4a6265f8a1916e2)

The fix will be available with the upcoming 2.3.0 release.
