### ISSUE TITLE
Fixed amount discount for whole cart applying an extra cent to the discount amount

### ISSUE THREAD

**Issue by alena-marchenko** [magento/magento2#12721]
### Preconditions
1. Magento is installed from 2.2-develop branch

### Steps to reproduce
1. Log in to Admin
2. Go to Marketing > Promotions > Cart Price Rule
3. Create Cart Price Rule with the following data:
- Coupon couponName, all websites, all customer groups
- Conditions: 
-- Subtotal  equals or greater than  45
- Actions: 
-- Apply Fixed amount discount for whole cart
-- Disocunt amount = 15, 
-- Free shipping = No, 
-- Apply to shipping amount No
4. Go to Products > Inventory > Catalog
5. Create product with Price = 0
6. Create products with Prices = 22; 14; 43; 9.50 (special price = 7.50)
7. Go to Stores -> Configuration -> Sales -> Tax -> Calculation Settings:
- Tax Calculation Method Based On = Row Total
- Catalog Prices, Shipping Prices, Apply Discount on Prices = Excluding Tax
- Apply Customer Tax = After Discount
8. Reindex and clear the cache as needed
9. Add all created products to cart on frontend (product with 0 price must be added into the end of cart products list)
10. Go to shopping cart > apply couponName

### Expected result
Discount with the sample products that have a price of $0.00 in the cart should equal 15.00

### Actual result
Discount with the sample products that have a price of $0.00 in the cart equals 15.01

**Comment by barbarich-p** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@barbarich-p thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by tippaluru** [comment]
Hi,

Wondering if there is a patch/fix for this issue in the community edition (2.2.2).

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash, here is your [Magento instance](https://i-12721-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-12721-2-3-0.instances.magento-community.engineering/admin](https://i-12721-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
I'm closing as this was already fixed on 2.3-develop branch.
