### ISSUE TITLE
2.2 Importing Group Products No Longer Works

### ISSUE THREAD

**Issue by mzenner1** [magento/magento2#12793]
As of 2.2, group products no longer import properly.  Using the sample data given on the system->import page, it will import the group product (the product type is correct), but no longer associate the simple products to the grouped product.  This was confirmed working in 2.1.7, but looks to be broken in 2.2.1 and 2.2.2.

**Comment by magento-engcom-team** [comment]
@mzenner1, thank you for your report.
We've created internal ticket(s) MAGETWO-85900 to track progress on the issue.

**Comment by PieterCappelle** [comment]
Hi @mzenner1 , I've created PR to fix this issue. Currently only for 2.3-develop branch. If accepted I'll create backport to 2.2-develop branch.

Issue has been created because of new functionality in 2.2 & 2.3 for duplicate SKU's. Every SKU is lowercased. In this function it was forgotten to change SKU to lowercase.

@dmanners Could you add import/export label to this issue. Thanks!

**Comment by sasilinux** [comment]
@mzenner1 - Have you ever got a chance to solve this issue. If you found any solution, please let me know. Thanks

**Comment by PieterCappelle** [comment]
@sasilinux I fixed in that PR. Just need to fix unit test but is easy. Will fix it.

**Comment by mzeis** [comment]
@PieterCappelle @dmanners FYI I added the Import/Export label.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#76

**Comment by magento-team** [comment]
Hi @mzenner1. Thank you for your report. 
The issue has been fixed in magento/magento2#12853 by @PieterCappelle in 2.3-develop branch
Related commit(s):
 - 01013fa674409a0f62cc66ee2f041b76211915cb
 - b566ca72a5c3f5cf817ad9c6d0bc346bf2014556

The fix will be available with the upcoming patch release.

**Comment by zuber11** [comment]
Hey all,

define simple product's SKU in small latter rather than capital. This will fix all the issues,
