### ISSUE TITLE
CartTotalRepository cannot handle extension attributes in quote addresses in 2.2.2

### ISSUE THREAD

**Issue by marius-bica** [magento/magento2#12819]
This issue is exactly the same as this one: https://github.com/magento/magento2/issues/9646, which had been opened at the time for magento `2.1.3` to `2.1.6` and fixed for `2.1.8`

The issue is still present in `2.2.2`

From what I tested, commit [aa535e](https://github.com/ekuusela/magento2/commit/aa535ea5d4bf78915bddd4387a9d3c4b39943eea) solves this issue and it's present in `2.1.8` (as stated in the original issue) but it's not ported to the `2.2` branch. As soon as it gets ported, everything will work as expected.

Sorry if this is not the proper way to resurrect the problem, seems like an easy fix though since the code is already there.

**Comment by sedax90** [comment]
Commit aa535e solves the problem in 2.2.2, why is not commited yet?

**Comment by magento-engcom-team** [comment]
@marius-bica, thank you for your report.
We've created internal ticket(s) MAGETWO-86420 to track progress on the issue.

**Comment by ishakhsuvarov** [comment]
Hi @marius-bica. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1186 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - 69cad441761423287c3caa1a05d8ecfe9d1c0c32
 - dc641384de526677dd1bebe349acaa16e7c17475

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @marius-bica. Thank you for your report. 
The issue has been fixed in magento/magento2#17620 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [370dc8492dc2b00d21e74dccf24e0abd6cca6d97](https://github.com/magento/magento2/commit/370dc8492dc2b00d21e74dccf24e0abd6cca6d97)

The fix will be available with the upcoming 2.3.0 release.
