### ISSUE TITLE
Coupon code with canceled order

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#12817]
### Preconditions

1. Magento 2.2.0
2. mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22

### Steps to reproduce

1. Add new coupon, [For example](http://joxi.ru/MAj3plec4lPVar) to reproduce this bug easily.
2. Do an order and apply this coupon code.
3. Go to admin area and cancel this order.

### Expected result

1. Coupon should be available again after all those steps.

### Actual result

1. I can't use coupon again. It says _Coupon code is not valid_.

**Comment by magento-engcom-team** [comment]
@AleksLi, thank you for your report.
We've created internal ticket(s) MAGETWO-85852 to track progress on the issue.

**Comment by AleksLi** [comment]
That's great,
Thanks. I Will track it.

**Comment by PieterCappelle** [comment]
Any update on this issue? Having the same problem with one of our customers.

**Comment by AleksLi** [comment]
No, I don't have any new notifications

**Comment by okorshenko** [comment]
Hi @AleksLi. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1095 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - cda78359e5bffd720381b022be99a72a13856a34
 - a7f6412e025285e5f18704264a077b9b5191903b
 - 86555549c24d3f0bc3152c870652242b051dc41f
 - bce7fc78e45b39d6be3c84f5998d3d8d18c0dee6
 - 29e59577f20b46474282fa6868f9d9774281a848
 - 7c98cc2152b8e6679dcb7454bd728b64eb2ec545
 - 24cb1ac31d765bd0b9f8cdb62a11b85b389b52e4
 - e1b33d4d501ffa100d82276e0f581e6f5ce7abbe
 - 025c6b815b5b8ce852202b5a3bc587b929158287
 - 6a21e850476ac6eb9776f1652a3018e504d30b01
 - 940cc642801f75ef5dc16fb4246b95225ec8f947

The fix will be available with the upcoming 2.2.4 release.

**Comment by AleksLi** [comment]
@okorshenko thank you for fixing that.

**Comment by magento-engcom-team** [comment]
Hi @AleksLi. Thank you for your report. 
The issue has been fixed in magento/magento2#20579 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [757856f3c6b6feccb8205950ece8fdedb7cc54a9](https://github.com/magento/magento2/commit/757856f3c6b6feccb8205950ece8fdedb7cc54a9)
 - [378f03c8edb1fab63d708ee60f8971cd379d3677](https://github.com/magento/magento2/commit/378f03c8edb1fab63d708ee60f8971cd379d3677)
 - [f02b0fa43b92f3f9be0e48c23c597b4e6e270f8f](https://github.com/magento/magento2/commit/f02b0fa43b92f3f9be0e48c23c597b4e6e270f8f)
 - [53abf958dcfef65f581790af9a827b7c87901ec1](https://github.com/magento/magento2/commit/53abf958dcfef65f581790af9a827b7c87901ec1)
 - [8f41977f66114c75ef84f5364ec36b55dbd5c094](https://github.com/magento/magento2/commit/8f41977f66114c75ef84f5364ec36b55dbd5c094)
 - [6f3362f3fd7236ad374b2492cc96cc1eef9c1a44](https://github.com/magento/magento2/commit/6f3362f3fd7236ad374b2492cc96cc1eef9c1a44)

The fix will be available with the upcoming 2.3.3 release.

**Comment by willemyouweagency** [comment]
Hi @magento-engcom-team , I have the following Magento version:

`"magento/product-enterprise-edition": "2.4.2-p1"`

The commits where the fix was applied (see comment above) do not seem to be applied to this version. Any idea why this is the case and how to solve this?
