### ISSUE TITLE
Magento rounding issue

### ISSUE THREAD

**Issue by ashishgavshinde** [magento/magento2#12823]
### Preconditions

1. Magento Version 2.x
2. 

### Steps to reproduce

1. Set Tax calculation settings > Catalog Prices as Excluding Tax
2. Set product price excluding tax like $34.77
3. Set Tax as 10.00% for USA and any state
4. Product Price on catalog is $35.25 then add product to cart and updates its qty to 2 
5. Getting subtotal as $76.49 instead of $76.50

### Expected result

1.  We have to get Cart Subtotal should be $76.50 instead of $76.49 etc

### Actual result

1. We are getting Cart subtotal $76.49 etc as per https://gyazo.com/ef476f658778ef03a175f566ea6b5950

**Comment by magento-engcom-team** [comment]
@ashishgavshinde, thank you for your report.
Please tell us what is your "Tax Calculation Method Based On" is set to. In order to get the result, you expect you need to have it set to "Unit Price".

**Comment by magento-engcom-team** [comment]
@ashishgavshinde, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
