### ISSUE TITLE
Payment method charge (feature request)

### ISSUE THREAD

**Issue by m-spyratos** [magento/magento2#12854]
I would like to request the ability to add additional charges depending on the payment method that a user has chosen.

For example: 

- [ ] Bank Deposit: Free
- [ ] Cash on Delivery: + $3.00

Paid solutions already exist for this, like [Extra Charge of Payment Method](https://shop.emiprotechnologies.com/extra-charge-of-payment-method-for-magento-2.html) from Emipro, but I believe that this should be part of the core functionality of Magento.

**Comment by davidverholen** [comment]
@magento-engcom-team If I would be willing to provide a PR for this, how is this handled from here? I think it first has to be decided if it should be included and at least some acceptance criteria to be defined? Is this even the right place or should the conversation be moved to the forums? Just asking because some time ago I already created a module doing this for cash on delivery.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Payment-method-charge-feature-request/idi-p/84517).
