### ISSUE TITLE
Invalid Document  Element 'resource': The attribute 'title' is required but missing.

### ISSUE THREAD

**Issue by ashvinim0003** [magento/magento2#12868]
### Preconditions

1.Installed Magento ver. 2.1.8 from git
2. Installed some extensions
3.Uploaded sample products

### Steps to reproduce

1.Open SSH 
2.Trying to upgrade  from ver. 2.1.8 to 2.2.2
3. php bin/magento cache:flush
4. php bin/magento cache:flush
5. php bin/magento setup:upgrade

### Expected result

1. No Error 

### Actual result

1. [Screenshot, logs]
1.Error showing
![screenshot from 21](https://user-images.githubusercontent.com/5154042/34321929-2cee0e10-e840-11e7-8f9b-51be9b6a625f.png)
2. Frontend errors
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please update your modules: Run "composer install" from the Magento root directory.
The following modules are outdated:
Magento_Customer db data version: defined in codebase - 2.0.12, currently installed - 2.0.9

Exception #0 (Magento\Framework\Exception\LocalizedException): Please update your modules: Run "composer install" from the Magento root directory.
The following modules are outdated:
Magento_Customer db data version: defined in codebase - 2.0.12, currently installed - 2.0.9
#0 /home/babybonb/public_html/babybonbon.com.au/beta-site/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Magento\Framework\App\Request\Http))
#1 /beta-site/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#2 /beta-site/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#3 /beta-site/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#4 /beta-site/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#5 /beta-site/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#6 /beta-site/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#7 /beta-site/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#8 /beta-site/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#9 {main}

**Comment by orlangur** [comment]
Hi @ashvinimarwal, please check https://magento.stackexchange.com/a/195091/40869 and use GitHub for bug reports only. Generally such kind of error indicates invalid XML files in your code and they just needs to be fixed to correlate with XSD.

If solution didn't work for your, please ping us back and issue will be reopened for further investigation.

**Comment by toledoroy** [comment]
I'm getting a similar error after running updating M2.3.5-p1 to N2.4.0 via Composer Update 

The error happens when trying to logging to the admin
(BTW, if the only error message had also included the XML filename everyone's life would have been so much easier)



1 exception(s):
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 13

Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 13

<pre>#1 Magento\Framework\Acl\Builder\Proxy->getAcl() called at [vendor/magento/module-backend/Model/Auth/Session.php:229]
#2 Magento\Backend\Model\Auth\Session->processLogin() called at [generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php:102]
#3 Magento\Backend\Model\Auth\Session\Interceptor->processLogin() called at [vendor/magento/module-backend/Model/Auth.php:165]
...

**Comment by huykon** [comment]
@toledoroy I tried your guide but still show error. Do you have any idea?
