### ISSUE TITLE
Can't remove State is required for all countries

### ISSUE THREAD

**Issue by mazur-vlad** [magento/magento2#12894]
### Preconditions

1. Magento version 2.1.9
2. PHP 7.0.25

### Steps to reproduce

1. Login to admin page
2. Navigate to Stores > Configuration > General
3. In the fieldset "State is Required for" disable all options.
4. Click to save

### Expected result

1. Nothing set in "State is Required for"

### Actual result

1. Previos options selected

**Comment by magento-engcom-team** [comment]
@mazur-vlad, thank you for your report.
We've created internal ticket(s) MAGETWO-86053 to track progress on the issue.

**Comment by vasilii-b** [comment]
Hi @magento-engcom-team, @mazur-vlad !

I investigated this issue and found fix for it. Please have a look at the PR.

Thanks!

**Comment by miguelbalparda** [comment]
Will take a look, thanks @vasilii-b!

**Comment by magento-team** [comment]
Hi @mazur-vlad. Thank you for your report. 
The issue has been fixed in magento/magento2#12917 by @vasilii-b in 2.2-develop branch
Related commit(s):
 - 4f9156625eeddfa7770d03724c93a8e04ff2531b

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @mazur-vlad. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1299 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 99e3a76b47267c930d4268b7bbf65500d1913f24
 - 4cfc07e28a8edb388011168e5fd0726dc6c71119
 - ea616e0a217e74707305f1038e6ca207d4bdaba6
 - be55217eae883abd02d44211fa0a88bb0a1d803c
 - 41c52fb989d961ad6ac48eea23163deb61dd9adc
 - 7f42a672ee864f2fc186d0259eb0de2e3d9634f6
 - 1090c8b54733b409a17553bfeb3ec292d449e5ce
 - c80b5ca54d2890407cf329bd24312ebf858929d2
 - 8077af7d42d069523f4addc21741567579e6e74f
 - 38e34a8747651b69a85575d7416d88a3ae49a34d
 - c13ad8595cf555b683223688325fe888fc112bec
 - 9e7bf93ec5b0e90952cac07391d2bde1a72d81ef
 - 10a6288175601ba26075996f3c39880b6e17eb76
 - abf31d2afaa543cddca00b197434ba3f28ac199b
 - 898a470a8b8b6cc6048a403be03594b8fd1b6b98
 - c99c3a7ae67ab16ab2407641a9b2c796f63ce3ef
 - 4537e784c70a3e07470ff7424684348c802839c8
 - 0bad56f0c371d5edc3cfc80dbae1e11400516546
 - fd2418ed8d062181ebc2e10bc298aba95d6d7a5e
 - 946e9e1b508e7788abf12e5c50098cdd9f6447ec

The fix will be available with the upcoming patch release.
