### ISSUE TITLE
Braintree "Place Order" button is disabled after failed validation

### ISSUE THREAD

**Issue by ifekaj** [magento/magento2#12900]
### Preconditions

1. Magento 2.2.2
2. PHP 7.0.25

### Steps to reproduce

1. Add product to cart and proceed to checkout
2. Fill all customer data and select shipping method. Proceed to payment
3. Select Braintree credit card payment method
4. Input credit card number (dummy)
5. Omit expiry date or cvv
6. Click "Place order" button
7. Error "Payment Credit Card (Braintree) can't be initialized" briefly appears
8. Input expiry date or cvv
9. "Place order" button is disabled/not responsive

### Expected result

1. "Place order" button can be clicked and order placed

### Actual result

1. "Place order" becomes unresponsive/disabled

Please note that if I input correct expiry date and cvv, order goes through correctly.

**Comment by magento-team** [comment]
Hi @ifekaj. Thank you for your report. 
The issue has been fixed in magento/magento2#12902 by @joni-jones in 2.2-develop branch
Related commit(s):
 - 0c5cb6ada1c46b7e68ee4cbd282c5369d63cbab7

The fix will be available with the upcoming patch release.

**Comment by franckgarnier21** [comment]
I have the same issue when T&C checkbox is enabled. I think you need to do the same fix an agreement-validator.js

I should have inject Magento_Braintree/js/view/payment/method-renderer/cc-form in the agreement-validator.js and call ccform().isPlaceOrderActionAllowed(true); at the end of the validate function.

It is a hot fix, I let you find the correct fix.

Thanks,

**Comment by magento-engcom-team** [comment]
Hi @ifekaj. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1299 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 99e3a76b47267c930d4268b7bbf65500d1913f24
 - 4cfc07e28a8edb388011168e5fd0726dc6c71119
 - ea616e0a217e74707305f1038e6ca207d4bdaba6
 - be55217eae883abd02d44211fa0a88bb0a1d803c
 - 41c52fb989d961ad6ac48eea23163deb61dd9adc
 - 7f42a672ee864f2fc186d0259eb0de2e3d9634f6
 - 1090c8b54733b409a17553bfeb3ec292d449e5ce
 - c80b5ca54d2890407cf329bd24312ebf858929d2
 - 8077af7d42d069523f4addc21741567579e6e74f
 - 38e34a8747651b69a85575d7416d88a3ae49a34d
 - c13ad8595cf555b683223688325fe888fc112bec
 - 9e7bf93ec5b0e90952cac07391d2bde1a72d81ef
 - 10a6288175601ba26075996f3c39880b6e17eb76
 - abf31d2afaa543cddca00b197434ba3f28ac199b
 - 898a470a8b8b6cc6048a403be03594b8fd1b6b98
 - c99c3a7ae67ab16ab2407641a9b2c796f63ce3ef
 - 4537e784c70a3e07470ff7424684348c802839c8
 - 0bad56f0c371d5edc3cfc80dbae1e11400516546
 - fd2418ed8d062181ebc2e10bc298aba95d6d7a5e
 - 946e9e1b508e7788abf12e5c50098cdd9f6447ec

The fix will be available with the upcoming patch release.

**Comment by aniruddhadeshpande** [comment]
@franckgarnier21 ,

Are you able to fix this issue? I'm getting same problem on Magento 2.2.  BrainTree  and TC checkbox enabled.

**Comment by deepakgairola25** [comment]
There is another error in verion 2.3 with disabling Place order button
**Steps to reproduce**

1. Add product to cart and proceed to checkout
2. leave email address field blank
3. Select Braintree credit card payment method
4. Input credit card number (dummy)
5. input expiry date and cvv
6. make sure that email id field is blank
7. fill customer data (name and address field)
8. Click update button
9. Click "Place order" button
10. Error for email address "This is a required field."
11. put email address
12. "Place order" button is disabled/not responsive
