### ISSUE TITLE
Unable to cancel/close a 100% discounted order

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#12910]
If a buyer uses a coupon code (in term of a gift card or whatever kind of shop owners logic) which gives 100% discount (grand total == 0), the order is not closable in a general matter.

### Preconditions
1. Magento 2.*

### Steps to reproduce
1. Create a cart rule which gives 100% discount
2. Create an order with applied coupon code
3. Create an invoice in the backend
4. Open the order in the backend

### Expected result
1. Should have a possibility to close/cancel an order and/or create a creditmemo.

### Actual result
1. Order persists in the processing status
2. No buttons to cancel or close
3. No possibility to create a creditmemo which closes the order automatically

**Comment by magento-engcom-team** [comment]
@Detzler, thank you for your report.
We've created internal ticket(s) MAGETWO-86160 to track progress on the issue.

**Comment by p-bystritsky** [comment]
@Detzler, I don't think this is a bug. You can not cancel any invoiced order.

**Comment by Detzler** [comment]
Maybe it's not a technical bug, which raises an exception internally. It's more a bug in the business logic. It's ok if we call it a feature request.

What happens if one can't create a creditmemo for an invoiced order:

If one has an invoiced order, the tax which has been calculated needs to be payed to the tax office (at least in Germany). If the buyer asks for an order cancellation, the shop owner needs to create a creditmemo, so that the tax office will not charge the shop owner.

The creditmemo gives also the possibility to inform the buyer about the cancellation.

**Comment by Detzler** [comment]
so whats the next procedure?

**Comment by magento-engcom-team** [comment]
Hi @lisovyievhenii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @Detzler thank you for your report, you cannot cancel invoiced order, only do the credit memo, wich is available
**No possibility to create a creditmemo which closes the order automatically** 
![DeepinScreenshot_select-area_20190405100841](https://user-images.githubusercontent.com/40756439/55610086-df999b00-578a-11e9-9dc3-a1e47f2d5a81.png)

**Comment by Detzler** [comment]
> only do the credit memo, wich is available

@engcom-backlog-nazar, which order status do you see after creating a credit memo with a full refund?

**Comment by ghost** [comment]
@Detzler after create the "credit memo", you cannot   do anything  with order. https://github.com/magento/magento2/issues/18509#issuecomment-442742113

**Comment by Detzler** [comment]
@engcom-backlog-nazar, at the time I created this github issue (2017-12), magento worked like this:

- create an order
- create a full invoice
- create a full credit memo
- the orders status is not complete nor closed. It had order status "in processing", which is incorrect to me. The order should be in status "closed", "complete" or even a new one "refunded", but not in "processing".

Now it's year 2019. I didn't check if this bug still persists. Are you able to reproduce it on the supported magento versions?

**Comment by ghost** [comment]
@Detzler in 2.3-develop branch status closed.
![DeepinScreenshot_select-area_20190405104648](https://user-images.githubusercontent.com/40756439/55612112-2a69e180-5790-11e9-8f51-9ae60ee4a4dc.png)
