### ISSUE TITLE
Checkout - Payment - Wrong promo code cancelled

### ISSUE THREAD

**Issue by popovdenis** [magento/magento2#12923]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Apply promo code successfully
2. Enter another code
3. Click on "Cancel promo code"

### Expected result

1. Error message that promo code doesn't exist should be displayed.

### Actual result

1. Promo code removed

**Comment by magento-engcom-team** [comment]
@popovdenis, thank you for your report.
We've created internal ticket(s) MAGETWO-86224 to track progress on the issue.

**Comment by ravi-chandra3197** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197, here is your [Magento instance](https://i-12923-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-12923-2-3-develop.instances.magento-community.engineering/admin](https://i-12923-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ravi-chandra3197** [comment]
Hello @magento-engcom-team, @popovdenis, 
Using the above step I have can't reproduce the issue in 2.3-develop,
If we apply one Coupon then coupon_code text box disabled,
so we can't add another coupon code like this image 

![issues-12923](https://user-images.githubusercontent.com/43946827/51831914-517fdf00-2319-11e9-8fc2-931f377f28d5.png)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @popovdenis thank you for you report, this issue already fixed in 2.3-develop and 2.2-develop branch, and available on 2.2.7 and 2.3.0 release.
