### ISSUE TITLE
Major Date Formatting Cockup

### ISSUE THREAD

**Issue by 4DallasC** [magento/magento2#12938]
When Mangento converts dates from the standard MySQL database format (YYYY-MM-DD) to the display format (MM/DD/YYYY) and the dates are at the end of the year, it add 1 year to the date. This gets progressively worse each year, ie 2017-12-31, 2018-12-30 & 2018-12-31, etc/

### Preconditions

None

### Steps to reproduce

$input = '2018-12-31';
$date = new \DateTime($input, new \DateTimeZone('Australia/Sydney'));
$formatted = $this->localeDate->formatDateTime($date, null, null, null, $date->getTimezone(),'M/d/Y');
        \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->debug("Input ".$input." and formatted ".$formatted);

### Expected result

1. should output "Input 2018-12-31 and formatted 31/12/2018"

### Actual result

1. should output "Input 2018-12-31 and formatted 31/12/2019"

P.S. I don't care if you think this bug report is formatted incorrectly or for some reason you can't reproduce this issue in your environment.

**Comment by wagento-bhavin** [comment]
wagento-bhavin:“#mm18in”

**Comment by magento-engcom-team** [comment]
@wagento-bhavin thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by wagento-bhavin** [comment]
I've reviewed the core magento code this issue occrued from the file
 
lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php line number 289.
This line calls the function format, to convert the date in required pattern.

I've checked the [http://php.net/manual/en/intldateformatter.format.php](url) and put below code in standalone php file and ran it in browser.
`<?php
$input = date('2018-12-31');
$date = new \DateTime($input, new \DateTimeZone('Australia/Sydney'));
$fmt = datefmt_create(
        'en_US',
        IntlDateFormatter::SHORT,
        IntlDateFormatter::SHORT,
    'Australia/Sydney',
        null,
    'MM/dd/yyyy'
);`
In above core Php file if we passed 'M/d/Y' pattern, it will also give the result 12/31/2019 instead of 12/31/2018.

Please use the date format pattern to 'MM/dd/yyyy' in above Magento's code, it will give the expected result.

**Comment by 4DallasC** [comment]
Hello @wagento-bhavin 

The date format is coming from:-
<pre>
    public function __construct(\Magento\Backend\Block\Template\Context $context, array $data = [])
    {
        $format = $context->getLocaleDate()->getDateFormatWithLongYear();
    }
</pre>

Can you please re-advise.

**Comment by wagento-bhavin** [comment]
Could you please let me know from which file you found this code. I search through the M2 source directory for above funciton. However I couldn't found that code in that.
getDateFormatWithLongYear() only exist in lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php, but it was not being called on running the code to format date.

Please provide me file path in which above constructor code exists.

**Comment by 4DallasC** [comment]
OMG if only you put as much effort into resolving these bugs as you do denying them, I'm sure Magento would work a lot better for all of us.
<pre>
  $field = $fieldset->addField('date', 'date', [
            'name'         => 'date',
            'label'        => __('Report Date'),
            'input_format' => 'yyyy-MM-dd',
            'date_format'  => $this->_localeDate->getDateFormatWithLongYear(),
            'value'        => $data['date'],//should always be set by the controller
            'onchange'     => "jQuery('#continue').val(1);jQuery('#edit_form').validate().cancelSubmit = true;jQuery('#edit_form').submit();"
  ]);
</pre>

Is your solution to remove this function from the M2 API?

**Comment by gwharton** [comment]
related to #10663 possibly?

**Comment by 4DallasC** [comment]
Hello gwharton,

No, the date format has nothing to do with the timezone. Currently the 
function will format 'Y' as the year 2018, but on the last days of the 
year it will convert 2018 to 2019.

This needs to be fixed, or the formatting of 'Y' needs to be removed.


Regards
Dallas Clarke

MBA'13 (IT Mgmt) UTS
BSc'03 (CS) & LLB'03 UNSW
Managing Director
Ekky Software Pty Ltd

Homepage: http://www.ekkysoftware.com
Mobile: 0424 990 497
Email: Dallas@ekkySoftware.com

Notice: The information contained in this email is confidential. If you 
are not the intended recipient, you may not disclose or use the 
information in this email in any way.

**Comment by magento-engcom-team** [comment]
@4DallasC, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by niravkrish** [comment]
Hello,

I have check this issue.

This is Core PHP issue in IntlDateFormatter function for date formating.

You can use other format for expected result like as below.
```
<?php 

$input = '2018-12-31';

$localeDate = $obj->getLocaleDate();

$zone = new \DateTimeZone('Australia/Sydney');

$date = new \DateTime($input, $zone);

$formatted = $localeDate->formatDateTime($date, IntlDateFormatter::FULL, IntlDateFormatter::FULL, null, $date->getTimezone(),'M/d/y');  // change format to M/d/y instead of M/d/Y

echo "Input ".$input." and formatted ".$formatted;

?>

```
Result : 
Input 2018-12-31 and formatted 31/12/2018

Thanks 
Nirav Patel

**Comment by engcom-Delta** [comment]
@niravkrish thanks for investigation. 
Closed as non-issue
