### ISSUE TITLE
Every time creating as separate customer in braintree

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#12942]
I created a customer in the front end.Now i have placed an order with credit card.
In braintree account its creating a customer.
Now with same magento cutomer i placed one more order with different credit card.
In braintree account its creating as separate new customer with same details. 

### Preconditions

1. magento 2.2.2
2. 

### Steps to reproduce

1. create a customer in the front end & place an order with credit card.
2. it will create a customer in braintree account.
3. again place an order with same customer.
4.then it will create separate customer in braintree

### Expected result

1. it should update existing customer.

### Actual result

1. it's creating as separate customer each time

**Comment by YevSent** [comment]
@sivajik34, this is expected behavior and not an issue. This is how Braintree Vault implemented in Magento. All Braintree customer accounts will be related to the same credit card.
![screenshot from 2018-01-02 16-04-11](https://user-images.githubusercontent.com/2736528/34486086-a9fd4662-efd6-11e7-86ab-847ab3768bc1.png)
![screenshot from 2018-01-02 16-04-26](https://user-images.githubusercontent.com/2736528/34486088-abc14278-efd6-11e7-98d9-caba203323a9.png)

Two different transactions for the same Magento customer (also have different customer ID) have different payment tokens (Vault tokens) but relate to the same card.
