### ISSUE TITLE
Drop down values are not showing in catalog product grid magento2

### ISSUE THREAD

**Issue by ramusadwika** [magento/magento2#13006]
Drop down values are not showing in catalog product grid magento2 after applying filter and sorting on respected attribute.

### Preconditions

1. Check a select attribute is available for products like manufacturer/brand
2. verify that that attribute properties (Add to Column Options > Yes and Use in Filter Options > Yes)
3. Select that attribute in column list of product grid

### Steps to reproduce

1. Navigate to admin catalog product grid
2. apply sorting on manufacturer/brand column
3. apply filter on manufacturer/brand using  filtlers
4. then manufacturer column shows empty.
5. We have response data in console it is returning option text instead of value.
6. Apply filter and sorting on drop attribute to reproduce easily.

### Expected result

1. It should show manufacturer names

### Actual result

1. It showing empty
![product grid](https://user-images.githubusercontent.com/30239543/34599709-cd79bee6-f219-11e7-99a3-b9c97a53a114.png)

**Comment by magento-engcom-team** [comment]
@ramusadwika, thank you for your report.
We've created internal ticket(s) MAGETWO-86415 to track progress on the issue.

**Comment by rohit-wagento** [comment]
rohit-wagento: “#mm18in”

**Comment by magento-engcom-team** [comment]
@rohit-wagento thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by rohit-wagento** [comment]
I have created the product and set the dropdown options on manufacturer And
In Catalog >> Products grid, It shows option name in manufacturer column in grid
and also shows on filter, Please find attached screenshot
![manufacturer](https://user-images.githubusercontent.com/22287262/34646961-760a2c3a-f39b-11e7-9fee-5fa7a4a9c7e5.png)

**Comment by ramusadwika** [comment]
Hi Rohit,

@rohit-wagento @dmanners 
Please do sorting on manufacturer field.
The values are disappearing after applying filter and sorting on manufacturer field.

**Comment by rohit-wagento** [comment]
Hi @ramusadwika
you can temporary resolve this by following way,
- When you filter any column and sorting it, the column values gone blank, then try at that time sort other column and you will get the values of blank column, and then you can sort column which you want and you can sort the columns and not got blank columns issue,
- For Example: 
you are filtering manufacturer column and sorting it you will get blank columns,
then just sort other columns like sku or any other you can see all values come from
manufacturer column, and then you can sort manufacturer column with manufacturer names,
and will not get blank values.

I am checking for it , that why it is happening and will update soon

**Comment by ramusadwika** [comment]
Thank you @rohit-wagento

**Comment by ramusadwika** [comment]
Hi @rohit-wagento ,

Have you checked this issue.

**Comment by rohit-wagento** [comment]
HI @ramusadwika ,
I have found the code, which is causing the issue,
I am checking on it to fix it

**Comment by ramusadwika** [comment]
Hi @rohit-wagento ,

Have you checked this issue.

**Comment by ramusadwika** [comment]
Hi @rohit-wagento ,

Any update on this issue.

**Comment by magento-engcom-team** [comment]
Hi @ramusadwika. Thank you for your report. 
The issue has been fixed in magento/magento2#13861 by @hiren-wagento in 2.2-develop branch
Related commit(s):
 - [db80cc237fdbf383f20da21bc129b7216063e1d5](https://github.com/magento/magento2/commit/db80cc237fdbf383f20da21bc129b7216063e1d5)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @ramusadwika. Thank you for your report. 
The issue has been fixed in magento/magento2#14174 by @dimonovp in 2.3-develop branch
Related commit(s):
 - [80887ac7db5a9c8c825debfe0a006ca7da4dca18](https://github.com/magento/magento2/commit/80887ac7db5a9c8c825debfe0a006ca7da4dca18)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @ramusadwika. Thank you for your report. 
The issue has been fixed in magento/magento2#17088 by @mageprince in 2.1-develop branch
Related commit(s):
 - [c1f13137a55999e8df6c6666f437264a22bd5afc](https://github.com/magento/magento2/commit/c1f13137a55999e8df6c6666f437264a22bd5afc)

The fix will be available with the upcoming 2.1.15 release.
