### ISSUE TITLE
Update pelago/emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [magento/magento2#13021]
Emogrifier 2.0.0 has been released, fixing a lot of bugs. If the new PHP >= 5.5 requirement is not a problem, the dependency should be updated to ^2.0.0.

**Comment by orlangur** [comment]
`"pelago/emogrifier": "1.2.0",` is currently used, upgrade could be probably not so easy due to breaking changes.

GitHub is intended for bug reports, please use [Community Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) for other suggestions like improvements or feature requests.

If you can test updated version, pull request would be welcomed.

> Emogrifier 2.0.0 has been released, fixing a lot of bugs

However, concrete manual testing scenarios for Magento should be provided so that issues affecting Magento could be verified.
