### ISSUE TITLE
After upgrade magento 2.1.0 to 2.2.1 product export not working

### ISSUE THREAD

**Issue by pradeepnew** [magento/magento2#13054]
After upgrade magento 2.1.0 to 2.2.1 product export redirect to dashboard.

### Preconditions
1. magento ver 2.2.1
2. php 7

### Steps to reproduce

1. Click on System > Export
2. then choose entity type Product and then scroll and click on continue.

### Expected result
1. Download csv  with products.

### Actual result
1. Its redirect to dashboard.

**Comment by nikolaybaychenko** [comment]
I experience the same issue with 2.2.2.

**Comment by hellotaran** [comment]
You may be having config value in core_config_data table for modules output restrictions. This functionality was deprecated in 2.2.0 and the config menu system -> advanced -> advanced was removed.

However the logic for processing existing settings was preserved. It should be removed in future releases of Magento. This is an issue with Core Magento

Since those options are deprecated and can be safely deleted. Below are the steps for the same:

1) Remove deprecated "modules_disable_output" values from core_config_data table:

DELETE FROM core_config_data WHERE path LIKE "advanced/modules_disable_output/%";

2) Clean config cache:

php bin/magento cache:clean config

Note: Please try this in your dev or staging environment before deploying to your production environment.

**Comment by zeljkoprsa** [comment]
Same issue with 2.2.2 only "advanced/modules_disable_output/" not found in the core_config_data table. @hellotaran Is there any other reason for this error?

**Comment by hellotaran** [comment]
@zeljkoprsa I believe you have used "advanced/modules_disable_output/%" to find any value exist in core_config_data table. Note: the % sign in the end of search string.

Other than above solution I do not have other recommendation for you.

**Comment by ghost** [comment]
@pradeepnew  thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
