### ISSUE TITLE
Changing admin Sales Orders filter after check one order will check it all

### ISSUE THREAD

**Issue by bordeo** [magento/magento2#13088]
On Admin Sales -> Orders filtering with one result and selecting one row/order result on selecting all orders.

### Preconditions
1. Magento 2.1.10 and 2.2.0
2. Log in as Admin
3. Orders must be more than 2 to test

### Steps to reproduce
1. Go to Sales > Orders
2. Filter the list using "Search by keyword" obtaining one row as result
3. Click on order checkbox to select the only one order. See "Select all checkbox" shown a tick.
4. Remove or change filter "Search by keyword" obtaining other or more orders.

### Expected result
1. After removing or changing the filter "Search by keyword" only previous ticked order must be checked.

### Actual result
1. After remove or change filter "Search by keyword" all orders are checked.

**Comment by magento-engcom-team** [comment]
@bordeo, thank you for your report.
We've created internal ticket(s) MAGETWO-86557 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-13088-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-13088-2-3-0.instances.magento-community.engineering/admin](https://i-13088-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by harshaldandade** [comment]
Please don't trouble me by sending this email



On Dec 26, 2018 15:05, "Magento Community Engineering" <
notifications@github.com> wrote:

Hi @engcom-backlog-andrii <https://github.com/engcom-backlog-andrii>. Thank
you for your request. I'm working on Magento 2.3.0 instance for you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/magento/magento2/issues/13088#issuecomment-449938820>,
or mute the thread

**Comment by ghost** [comment]
@harshaldandade you can always mute the thread from email by link or unsubscribe from this page by button
![image](https://user-images.githubusercontent.com/41946904/50442505-227be500-08f7-11e9-94ff-87a3c6da47f0.png)

**Comment by ghost** [comment]
@bordeo, thank you for contributing

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97336`, `MAGETWO-97337` were created

**Comment by magento-engcom-team** [comment]
@bordeo, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
