### ISSUE TITLE
Missing method setIsAnchor() in \Magento\Catalog\Api\Data\CategoryInterface

### ISSUE THREAD

**Issue by tdgroot** [magento/magento2#13087]
This might be an issue or it could have been designed this way. I just stumbled upon the fact that this method is missing.

### Preconditions

1. Magento 2.2.2

### Steps to reproduce

No steps, it's a missing piece in the code.

### Expected result

1. Method `\Magento\Catalog\Api\Data\CategoryInterface::setIsAnchor(bool)` exists.
2. Method `\Magento\Catalog\Api\Data\CategoryInterface::getIsAnchor()` exists.

### Actual result

1. Method `\Magento\Catalog\Api\Data\CategoryInterface::setIsAnchor(bool)` doesn't exist.
2. Method `\Magento\Catalog\Api\Data\CategoryInterface::getIsAnchor()` doesn't exist.

**Comment by magento-engcom-team** [comment]
@tdgroot, thank you for your report.
We've created internal ticket(s) MAGETWO-86559 to track progress on the issue.

**Comment by okorshenko** [comment]
http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#introduction-of-a-method-to-a-class-or-interface

**Comment by magento-engcom-team** [comment]
Hi @vshatylo. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sdzhepa** [comment]
Closed.
Such changes are contradicting the Magento Backward Compatible guide.

For more details see: https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/index.html#introduction-of-a-method-to-a-class-or-interface
