### ISSUE TITLE
Something went wrong while saving this configuration: Warning: array_replace_recursive(): recursion detected

### ISSUE THREAD

**Issue by zaheerbadi** [magento/magento2#13116]
### Preconditions

1.  Magento 2.2.2
2. Apache 2.4.18
3. My SQL 5.7.11
4. Wamp 3.0.4

### Steps to reproduce

1. installed fresh magento
2. try to save any configuration
3. it invalidate FPC everytime you save configuration

### Expected result

1. save configuration without any error
2. it should not invalidate FPC everytime we save configuration

### Actual result

1. https://www.screencast.com/t/8ttHroiA
2.https://www.screencast.com/t/sg8ybkAyf

it produce every time when install magento with sample data or without sample data.
it also occur in command line interface too

**Comment by zaheerbadi** [comment]
Without resolve this error we can't able to move forward as we are not able run `php bin/magento setup:upgrade` command .

**Comment by zaheerbadi** [comment]
@magento-engcom-team any progress on this please guide us on this if possible?

**Comment by magento-engcom-team** [comment]
Hi @zaheerbadi 
We can not help you in your issue.
We don't support your OS (i mean Windows).
See: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@zaheerbadi, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
