### ISSUE TITLE
Swatch Attribute is not getting save while deleting a swatch row with empty admin scope text

### ISSUE THREAD

**Issue by mak0605** [magento/magento2#13117]
### Preconditions

1. Magento 2.2

### Steps to reproduce

1. Install Magento v 2.2
2. Login to admin and  Goto Store- >Attribute->Product
3. Find a attribute like color
4. Open color attribute and make it to Visual Swatch type
5. In Manage Swatches section add color swatches
6. Now Click on Add Swatch button, a row will appear just remove it without filling anything into it.
7. Click on save, you will get following error:
**The value of Admin scope can't be empty.**

### Expected result

1.  Attribute should be save with out any error if i want to remove any option
2. It should not validate for deleted swatch row while saving

### Actual result

1. When i add a new row and delete it without filling data into it its getting display none, but its getting validate while submitting form for save. 
See in attached screenshot
![screen shot 2018-01-11 at 13 31 42](https://user-images.githubusercontent.com/34734884/34814524-febef282-f6d3-11e7-909e-8e971276369f.png)

**Comment by magento-engcom-team** [comment]
@mak0605, thank you for your report.
We've created internal ticket(s) MAGETWO-86644 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @mak0605. Thank you for your report. 
The issue has been fixed in magento/magento2#13717 by @enriquei4 in 2.2-develop branch
Related commit(s):
 - [0fc6be3a18fa8bdfe2a1bb19a2ce883fa18ac27d](https://github.com/magento/magento2/commit/0fc6be3a18fa8bdfe2a1bb19a2ce883fa18ac27d)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @mak0605. Thank you for your report. 
The issue has been fixed in magento/magento2#13220 by @enriquei4 in 2.3-develop branch
Related commit(s):
 - [15477afc1b7a66a8fd81776dc7c0d5e3a7193991](https://github.com/magento/magento2/commit/15477afc1b7a66a8fd81776dc7c0d5e3a7193991)
 - [2eeb633245caf20a6afa5e96b7f224bac7111414](https://github.com/magento/magento2/commit/2eeb633245caf20a6afa5e96b7f224bac7111414)
 - [3bab7142a508abedc3105e53bceda4856785d0ae](https://github.com/magento/magento2/commit/3bab7142a508abedc3105e53bceda4856785d0ae)
 - [ae01fba1ea5097d9e15f3ed8553ce66a34b08a8e](https://github.com/magento/magento2/commit/ae01fba1ea5097d9e15f3ed8553ce66a34b08a8e)
 - [a9abfa804f96dfdfa51d82298ce8e0a77534fe90](https://github.com/magento/magento2/commit/a9abfa804f96dfdfa51d82298ce8e0a77534fe90)
 - [980522ad182817b10e4550ad308c7f84476329b2](https://github.com/magento/magento2/commit/980522ad182817b10e4550ad308c7f84476329b2)
 - [d42b6bebca5d2c54bb88e4bcf46b94a0ee579129](https://github.com/magento/magento2/commit/d42b6bebca5d2c54bb88e4bcf46b94a0ee579129)

The fix will be available with the upcoming 2.3.0 release.
