### ISSUE TITLE
Magento 2.2 Order Product Reporting - Not Summarizing and Filtering Properly within the Grid

### ISSUE THREAD

**Issue by aCicchelli** [magento/magento2#13147]
Looking at the Ordered Products Report  (Reports->Products->Ordered) report, it doesn't to be summarizing within the grid at  all. It's also not 'sorting' the tables in any particular order.

It'll show many duplicates making a little unusable for us and some our our clients.
See attached. I've tried different views, filters, etc doesn't seem to matter.

![summarizing](https://user-images.githubusercontent.com/35355487/34856821-57eadc2c-f715-11e7-9ed9-a392fe1c2171.PNG)

**Comment by magento-engcom-team** [comment]
@aCicchelli, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@aCicchelli The issue seems to be fixed in upcoming 2.3.0.
We will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @aCicchelli ,The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by coatesjonathan** [comment]
Hi - what commit was this? I would like to patch this in my current 2.2.5 version as we're currently not willing to upgrade.

**Comment by Ctucker9233** [comment]
@engcom-backlog-nazar can we get the commits please?
