### ISSUE TITLE
Prices of Bundle products on customer's wishlist are wrong

### ISSUE THREAD

**Issue by densen45** [magento/magento2#13181]
### Preconditions

We tested this on two environments: 
1. Ubuntu 17.04, Apache2, PHP 7.0
2. Ubuntu 17.10, Nginx, PHP 7.0

And we were able to reproduce this issue on the following two Magento 2 versions:
1. M 2.1.10
2. M 2.2.2

### Steps to reproduce

1. Create a Bundle product in the backend with at least one option with "Radio" and "User defined quantity" (also experienced the issue for "Checkbox")
2. Access the Bundle in a browser
3. Change the quantity of the option
4. Notice and remember the calculated price
5. Add the Bundle to the wishlist
6. Compare the price that was displayed on the Bundle product view page to the price from the wishlist  

### Expected result

The Bundle's price is the same.

### Actual result

The Bundle's price differs. 

Actually, the price is calculated based on the default values for the selections that were configured in the backend and not on the customer's defined quantities.

Hovering over the "Details" the correct quantities for the selections are shown.

**Comment by magento-engcom-team** [comment]
@densen45, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mahesh-rajawat** [comment]
@densen45 this issue has been fixed with the PRs #19437 and #19260 . You can check the updated code or wait for the upcoming releases. 
Thanks
