### ISSUE TITLE
Unable to remove ProductWebsiteLink via API for the calling website

### ISSUE THREAD

**Issue by danbuchal** [magento/magento2#13191]
### Preconditions
Magento 2.2.2

### Steps to reproduce
1. Create a product and associate it with more than 1 website.
2. Use REST call to remove website: (DELETE /V1/products/:sku/websites/:websiteId)
    NOTE: The domain used should be that of the website we are attempting to remove from the product

### Expected result
The website id should be removed from the associated websites

### Actual result
If the websiteId is the same as the domain used to make the API call, the call returns "true", but the product website link is not removed

### Believed Root Cause
In the deleteByID method of the Product Website Link Repository the Product Repository save method is called:
https://github.com/magento/magento2/blob/0e445495f1471738fb5f3b09e119a47ef4b78fd2/app/code/Magento/Catalog/Model/ProductWebsiteLinkRepository.php#L71

which calls the initializeProductData method:
https://github.com/magento/magento2/blob/0e445495f1471738fb5f3b09e119a47ef4b78fd2/app/code/Magento/Catalog/Model/ProductRepository.php#L586

which calls the assignProductToWebsites method:
https://github.com/magento/magento2/blob/0e445495f1471738fb5f3b09e119a47ef4b78fd2/app/code/Magento/Catalog/Model/ProductRepository.php#L343

which re-adds the current store's website:
https://github.com/magento/magento2/blob/0e445495f1471738fb5f3b09e119a47ef4b78fd2/app/code/Magento/Catalog/Model/ProductRepository.php#L357-L362

**Comment by magento-engcom-team** [comment]
@danbuchal, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by AleksLi** [comment]
@danbuchal I investigated the issue very precisely. And I tried to reproduce it on Magento 2.3 version and I couldn't. 
I think the logic has been changed since January 15, 2018. 
Here is what I found now in ProductRepository:
<img width="915" alt="magento 2 from magento github public projects magento2source - public app code magento catalog model productrepository 2019-02-18 20-49-23" src="https://user-images.githubusercontent.com/10618641/52973616-ea58c600-33be-11e9-9047-ed56aeb118e7.png">

So, I can say for sure that the bug is not reproducable now @magento-engcom-team . 
I guess @magento-engcom-team can close it now.

**Comment by magento-engcom-team** [comment]
Hi @AleksLi. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @danbuchal thank you for you report, this issue has already been fixed by this commit 95d17ee6a5ec5375dd2ef7934d1b4f501ba29080
