### ISSUE TITLE
`quoteAddressToFormAddressData` mutates the argument

### ISSUE THREAD

**Issue by vaaralav** [magento/magento2#13216]
### Preconditions

1. Magento >=2.1.9 (at least)

### Steps to reproduce

1. Require `'Magento_Checkout/js/model/address-converter'` inside any JavaScript module.
2. Call `quoteAddressToFormAddressData` method with some `address`.

### Expected result

1. `address.street` should remain as an array. Eg. `['Sesame Street']`

### Actual result

1. `address.street` becomes an object. Eg. `{0: 'Sesame Street'}`

**Comment by magento-engcom-team** [comment]
@vaaralav, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @vaaralav. Thank you for your report. 
The issue has been fixed in magento/magento2#14250 by @mastiuhin-olexandr in 2.3-develop branch
Related commit(s):
 - [c71e7acb4e13e3b2848a77353345de1b03fe0d5e](https://github.com/magento/magento2/commit/c71e7acb4e13e3b2848a77353345de1b03fe0d5e)

The fix will be available with the upcoming 2.3.0 release.
