### ISSUE TITLE
CLI Backup doesn't work properly when directory is a symlink

### ISSUE THREAD

**Issue by Igloczek** [magento/magento2#13218]
### Preconditions
1. Symlinked `pub/media` directory 

### Steps to reproduce
1.  `bin/magento setup:backup --media`

### Expected result
1. Fully functional backup file

### Actual result
1. Backup size is 4KB and contains just a symlink

@matthiasherold hint - it might be a `magento/framework/Backup/Filesystem/Helper.php:110`

**Comment by PascalBrouwers** [comment]
Related issue: https://github.com/magento/magento2/issues/6470

**Comment by magento-engcom-team** [comment]
@Igloczek, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ivanko-dev** [comment]
@magento I am working on it

**Comment by magento-engcom-team** [comment]
Hi @Igloczek. Thank you for your report. 
The issue has been fixed in magento/magento2#24755 by @ivan-koliadynskyy in 2.3-develop branch
Related commit(s):
 - [b27a5767a5ac6e53b434d2590b5daeeaef2a0cfd](https://github.com/magento/magento2/commit/b27a5767a5ac6e53b434d2590b5daeeaef2a0cfd)
 - [7a9f956c311af2834f6b263d3e5fb14bde1d7a5a](https://github.com/magento/magento2/commit/7a9f956c311af2834f6b263d3e5fb14bde1d7a5a)

The fix will be available with the upcoming 2.3.4 release.
