### ISSUE TITLE
Peristent cart cookie is not generated for guests and thus persistent cart isn't working

### ISSUE THREAD

**Issue by TimQSO** [magento/magento2#13229]
When we want to use the Persistent Shopping Cart functionality it does not seem to work for guest users. For guest users the persistent shopping cart cookie isn't created and thus when the session expires the shopping cart is gone.

**Preconditions**

1. Magento 2.4
2. PHP 7.3 | Ubuntu 18.04 LTS | Nginx 1.14.0 or Apache 2.4.29
3. MySQL 5.7.28

**Steps to reproduce**
1. Enable Persistent Shopping Cart in the Backend and set every option to YES 
2. Refresh cache where needed
3. Go to the Frontend (as a guest / not logged in) and put something in your shopping cart
4. Verify that the persistent_shopping_cart cookie isn't created (while it should)
5. Remove the PHPSESSID cookie to clear your session

**Expected result**
1. After removing the PHPSESSID cookie the shopping cart should stay intact 

**Actual result**
1. After removing the PHPSESSID cookie the shopping cart is empty again
2. No sign of the persistent_shopping_cart cookie that should kick in to preserve the cart

**Comment by magento-engcom-team** [comment]
@GuiltyNL, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by PascalBrouwers** [comment]
@irenelagno could you have a look at this please? :)

**Comment by r3v4ek** [comment]
@magento-engcom-team Hi. We have the same problem in our store. Any updates from your side?

**Comment by TimQSO** [comment]
Any updates on this one?

**Comment by TimQSO** [comment]
It is a pity it takes so long for this ticket. :(

**Comment by katmoon** [comment]
Persistent shopping cart cookie is created only for a registered user. The cookie contains non-sensitive information and will be used when the user logs off or the session cookie expires.

**Comment by TimQSO** [comment]
Well it doesn't make sense to make this option available for registered users only. It should also work for guest users with an expiring session cookie.

**Comment by imontaine** [comment]
Just so you guys know, Shopify keeps guest carts for 2 weeks. Sellers using Magento stores are at a severe disadvantage by not passing some sort of guest persistence.

**Comment by erfanimani** [comment]
@emosquito you could always enable the session lifetime to 2 weeks

**Comment by clockworkgeek** [comment]
M2 works the same as M1 in this regard.  Guest quotes are never purged so they build up in the database, even if they contain no items.  Previously I wrote [an (M1 only) extension](https://marketplace.magento.com/clockworkgeek-clockworkgeek-guestcookies.html) to take advantage of this by generating a token to match each guest quote and saving it in a cookie.  This is a more scalable approach than long session times and is what Persistence is doing for registered customers.  The `persistent_session` table even allows a null customer ID so it wouldn't be that hard to extend it to guests.

Unlike the existing 'remember me' feature on login page, guests are not opting in so implementation must comply with EU cookie law, and since quotes can contain address information GDPR law too.  I think the requested behaviour is a huge value add and I fully support it.

**Comment by imontaine** [comment]
The solution that @clockworkgeek gives is a great solution, I would love to see that officially supported in M2.

@erfanimani enabling the session lifetime is not a great solution in general because the session lifetime also affects logged in customers. Keeping customers logged in for 2 weeks could be a security risk for an ecommerce website (Which is why persistent mode exists).

**Comment by TimQSO** [comment]
This ticket is now almost a year old. :(

**Comment by SAN1TAR1UM** [comment]
Any update on this? Anyone built an M2 extension?

**Comment by swaibar** [comment]
Any update on this?

**Comment by tig-daanvandenbergh** [comment]
Hi guys,

I built an extension for M2, inspired by @clockworkgeek's M1 extension. I must say I haven't tested it in a while, but I don't see a reason why it wouldn't work in M2.3.3.

You can download it here: https://github.com/tig-nl/persistentshoppingcart-magento2

**Comment by swaibar** [comment]
@tig-daanvandenbergh thank you!  As it happens I found this after my comment and before yours.  I did have some issues... But then I'm having issues getting this to work for logged in users too... so I didn't want to raise issues with your module when I figured I've got other problems.

**Comment by macguydvd** [comment]
@tig-daanvandenbergh thanks for the extension. I have loaded it in my M2.3.3 instance, but I am not seeing the TIG section under Stores > Configuration. There are no new sections and I do have the customer persistent cart enabled. Thanks!

> Hi guys,
> 
> I built an extension for M2, inspired by @clockworkgeek's M1 extension. I must say I haven't tested it in a while, but I don't see a reason why it wouldn't work in M2.3.3.
> 
> You can download it here: https://github.com/tig-nl/persistentshoppingcart-magento2

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30119` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MadonnaRagu** [comment]
Has this been fixed or not?

**Comment by sdzhepa** [comment]
The Issue was moved by bot to the Done column by mistake.
Issue is not fixed yet so feel free to take it in progress and propose your solution

**Comment by bluedarter2** [comment]
Has this been fixed in magento 2.4?

**Comment by GuiltyNL** [comment]
More than three years have passed. This is never going to be fixed. 😎

**Comment by janisverins** [comment]
Still praying for this to be implemented.

**Comment by mserbanoiu** [comment]
Any news here?
