### ISSUE TITLE
Can't close full screen gallery on iOS devices

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#13226]
It's not possible to close the full screen image gallery on iOS devices. Maybe other devices are affected.
I found some other issues or comment regarding this topic, but they've been closed by mistake.
https://github.com/magento/magento2/issues/12185
https://github.com/magento/magento2/issues/12490#issuecomment-353934666
https://magento.stackexchange.com/questions/207194/magento-2-product-gallery-doesnt-close-on-iphone

### Preconditions

1. Magento 2.2-develop
2. PHP 7.0.22
3. MySQL 5.6.35

### Steps to reproduce
1. Start Apple Simulator (https://developer.apple.com/library/content/documentation/IDEs/Conceptual/iOS_Simulator_Guide/Introduction/Introduction.html)
2. Run Safari and open any product detail page
3. Tap on the image to open the product image in fullscreen mode
4. Tap on the close button in the upper right corner

### Expected result
1. Gallery should be closed
2. Product detail page should be visible again

### Actual result
1. Gallery doesn't disappear

**Comment by magento-engcom-team** [comment]
@torhoehn, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by pavelshulgabi** [comment]
I'm working on #cd-balance

**Comment by pavelshulgabi** [comment]
The reported issue was extensively tested on vanilla Magento versions 2.2.4, 2.2.5 and 2.2-develop (2.2.6).
As per investigation, the issue is resolved. The fix was to explicitly trigger required DOM event for mobile devices:
[https://github.com/magento/magento2/blob/2.2.4/lib/web/fotorama/fotorama.js#L1221](https://github.com/magento/magento2/blob/2.2.4/lib/web/fotorama/fotorama.js#L1221)

The verification was conducted on a real device, for more information please refer to the screen capture video below:
[https://drive.google.com/open?id=1S5qGgfbG3fw4SB1jvqGzn-Zpe1-4g1EL](https://drive.google.com/open?id=1S5qGgfbG3fw4SB1jvqGzn-Zpe1-4g1EL)

In case if anyone is still encountering the issue described in this thread feel free to reopen the it.

**Comment by ghost** [comment]
I'm not sure how to reopen the issue, but it is still there in production mode when opting to minify js files. It seems like the fix was not put into the minified version of the script.

**Comment by torhoehn** [comment]
@shilpambb Minified version of fotorama was removed in https://github.com/magento/magento2/pull/22082.

**Comment by ghost** [comment]
@torhoehn thanks for the update. Looks like it didn't make it into 2.2.9. I guess it will make it into the next release for 2.2.
