### ISSUE TITLE
set default vlaues in checkout in magento 2

### ISSUE THREAD

**Issue by aathil-ali** [magento/magento2#13236]
### Preconditions

1. I need set default vlaues in checkout in magento 2

**Comment by magento-engcom-team** [comment]
@aliaathil Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by magento-engcom-team** [comment]
@aliaathil, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@aliaathil Closing this one, because of https://github.com/magento/magento2/issues/13237
