### ISSUE TITLE
Default State or Province is not pre-selected in the Estimate Shipping and Tax

### ISSUE THREAD

**Issue by harrywutech** [magento/magento2#13231]
### Preconditions

1. Magento CE 2.1.9 with sample data is installed.

### Steps to reproduce

1. Go to Admin -> Stores -> Sales -> Tax ->Default Tax Destination Calculation
2. Set Default Country to Canada and set Default State to British Columbia

### Expected result

1. The default state or province should pre-selected as British Columbia 
 
![shopping cart](https://user-images.githubusercontent.com/3589130/35014731-a6b2aa60-fac6-11e7-92f5-0381c52a29ff.jpg)

### Actual result

1. The state or Province is not selected unlike the country
![shopping cart 1](https://user-images.githubusercontent.com/3589130/35014759-c02f4692-fac6-11e7-9aca-a36f23df75c0.jpg)

**Comment by magento-engcom-team** [comment]
@hanxiangwu, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by harrywutech** [comment]
Thank you, when this issue will be fixed? and if it is a easy fix, then how could we fix it by ourselves?

**Comment by magento-engcom-team** [comment]
Hi @hanxiangwu. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1258 by @serhii-balko in 2.2-develop branch
Related commit(s):
 - [0cabe58e64e89f8b1284a3ffb71593ad04d6e525](https://github.com/magento/magento2/commit/0cabe58e64e89f8b1284a3ffb71593ad04d6e525)
 - [0ad6208ddd87c9d27681418294e42c9c8af0e637](https://github.com/magento/magento2/commit/0ad6208ddd87c9d27681418294e42c9c8af0e637)
 - [e26c22f4bbf18b46516f1032b04044bc69eae092](https://github.com/magento/magento2/commit/e26c22f4bbf18b46516f1032b04044bc69eae092)
 - [7b0a489ea25cbb2f03dce60e51c25b572157745e](https://github.com/magento/magento2/commit/7b0a489ea25cbb2f03dce60e51c25b572157745e)
 - [35fb31999e4196155c00b4f0e9f5d925299dc571](https://github.com/magento/magento2/commit/35fb31999e4196155c00b4f0e9f5d925299dc571)
 - [5837d364eaf8a95af75b4e3c312c9c42dcfea232](https://github.com/magento/magento2/commit/5837d364eaf8a95af75b4e3c312c9c42dcfea232)
 - [4d5006659611afb02c12f364df48aa079f9f5e90](https://github.com/magento/magento2/commit/4d5006659611afb02c12f364df48aa079f9f5e90)
 - [04e573afa8c3a169cdb0e6413de5283294fb257a](https://github.com/magento/magento2/commit/04e573afa8c3a169cdb0e6413de5283294fb257a)

The fix will be available with the upcoming 2.2.5 release.
