### ISSUE TITLE
Unable to update tracking number, carrrier code and title using magento rest api 

### ISSUE THREAD

**Issue by amardeepthadisetty** [magento/magento2#13248]
My magento version is 2.2.2. I am using the following code: 
`"entity": { "orderId": 4883, "items": [ { "extension_attributes": {}, "order_item_id": "7141", "qty": "1" } ], "notify": true, "append_comment": true, "comment": { "extension_attributes": {}, "comment": "Item(s) has been shipped", "is_visible_on_front": 0 }, "tracks": [ { "extension_attributes": {}, "track_number": "028806881473805", "title": "Federal Express", "carrier_code": "fedex" } ], "packages": [ { "extension_attributes": {} } ], "arguments": { "extension_attributes": {} } } }`

URL is: 'https://'.$_SERVER['HTTP_HOST'].'/index.php/rest/V1/order/'.$entity_id.'/ship/';

In my case, before running the above script the order status at magento admin site is under 'processing'.
After running the script , that particular order status is changing to complete. However, the tracking number, carrier code and title, comment are not being updated in the admin. If i again run the script, after updating the status to complete, I am getting an error like: "You can't create a shipment without products" and some other error. So, i think, it works only the first time.
The order status is changing to complete in my case, however, I am unable to update the tracking info. I am attaching a screen shot:
![complete1](https://user-images.githubusercontent.com/13029965/35082544-76c50430-fc40-11e7-9c4c-80f5d4fba269.JPG)
![complete2](https://user-images.githubusercontent.com/13029965/35082546-76ee3558-fc40-11e7-9f2c-c1abbc983c48.JPG)

**Comment by magento-engcom-team** [comment]
@amacgregor  thank you for your report
Please try using the following code and tell us your result.

{
  "items": [
    {
      "qty": 2,
      "order_item_id": 3
    }
  ],
  "notify": true,
  "comment": {
    "extension_attributes": {},
    "comment": "Item(s) has been shipped",
    "is_visible_on_front": 0
  },
  "tracks": [
    {
      "extension_attributes": {},
      "track_number": "028806881473805",
      "title": "Federal Express",
      "carrier_code": "fedex"
    }
  ]
}

>  I am getting an error like: "You can't create a shipment without products" and some other error.

Yes, it works only the first time, because after full shipment has been created for the specified in request *order_item_id* (which isn't an order id) no more shipment can be created for the same *order_item_id*

**Comment by amardeepthadisetty** [comment]
Thank you for the response. I am waiting for a new order, i will try this n update you the status.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amardeepthadisetty** [comment]
Thank you @amacgregor . It worked!!
This is the one I am using:
`$tracking_str = [ "items"=> [ [ "order_item_id"=>$orderItemId, "qty"=> $qty_invoiced ] ], "notify" => true, "appendComment" => true, "comment" => [ "extension_attributes" => [], "comment" => "Item(s) has been shipped", "is_visible_on_front" => 0 ], "tracks" => [ [ "extension_attributes" => [], "track_number" => $TrackingNumber, "title" => $ShipTitle, "carrier_code" => $carrierCode ] ] ]`

Finally, tracking number, carrier code and title are being updated. Thanks for everything!!!

**Comment by magento-engcom-team** [comment]
@amardeepthadisetty, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
