### ISSUE TITLE
Fetching customer entity through API will not return 'is_subscribed' extension attribute

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#13252]
In the Magento_Newsletter module an extension attribute 'is_subscribed' is defined for the \Magento\Customer\Api\Data\CustomerInterface. However when fetching the customer through api, the extension attribute is not present in the data.

### Preconditions
1. PHP7 
2. CE 2.2.2 (also tested EE 2.2.2)

### Steps to reproduce
1. Create a new customer through the frontend registration and make sure to check the subscribe to newsletter checkbox 
2. Fetch the newly created customer through the api call '../rest/nl/V1/customers/{newCustomerId}'

### Expected result
1. Extension attributes are present in the data containing a value for 'is_subscribed'

### Actual result
1. The extension attributes are missing from the customer data

I did some basic digging into the core and noticed there is no actual place in the Magento_Newsletter module that sets the extension attribute 'is_subscribed' after the customer is fetched.

I compared this with the Magento_GiftMessage module where in the Magento\GiftMessage\Model\Plugin folder there are several classes which contain logic to add extension attributes to the orders when fetching and saving.

Seems like somebody dropped the ball when programming the Magento_Newsletter module.
#magentomagic

**Comment by magento-engcom-team** [comment]
@koenner01, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by koenner01** [comment]
We have received a patch for this through the cloud support (but they asked us not to make it public as it is probably not final). This commit https://github.com/magento/magento2/commit/f9dd1b1f579ed5e58d39ffe341e60f085bd24fe0#diff-8b13fe3225a8e5f17fa52fa6c5b74eda contains a fix (but it's not the same as we received through cloud)

**Comment by AGPDev** [comment]
nice, one year and nothing

**Comment by yaroslav-zenin** [comment]
why it is still not  merged?

**Comment by rimsey1** [comment]
bump, agree what is stopping this feature being merged?

**Comment by magento-engcom-team** [comment]
Hi @koenner01. Thank you for your report. 
The issue has been fixed in magento/magento2#25311 by @enriquei4 in 2.4-develop branch
Related commit(s):
 - [b2d553ad7d7726703aac51e6fb02f04e8c7ca1d7](https://github.com/magento/magento2/commit/b2d553ad7d7726703aac51e6fb02f04e8c7ca1d7)
 - [8f5bfad585426b22a1fed43fe139bf615b8e2d57](https://github.com/magento/magento2/commit/8f5bfad585426b22a1fed43fe139bf615b8e2d57)
 - [8b33f6925f8aebfe04bef9121ff642c88233efa0](https://github.com/magento/magento2/commit/8b33f6925f8aebfe04bef9121ff642c88233efa0)
 - [d867655780f0803b6864d087732387aec878c8f0](https://github.com/magento/magento2/commit/d867655780f0803b6864d087732387aec878c8f0)
 - [c9f9d71a26e8ad79190ae00dc7902856472c55c4](https://github.com/magento/magento2/commit/c9f9d71a26e8ad79190ae00dc7902856472c55c4)
 - [50207521b8fbbaa52c3ac99dbb4f854d2ebc6093](https://github.com/magento/magento2/commit/50207521b8fbbaa52c3ac99dbb4f854d2ebc6093)

The fix will be available with the upcoming 2.4.0 release.
