### ISSUE TITLE
Unable to create new customer using CustomerRepositoryInterface

### ISSUE THREAD

**Issue by cphl91** [magento/magento2#13264]
### Preconditions

1. Magento CE 2.2.2
2. PHP 7.0.22

### Steps to reproduce

1. Using `Magento\Customer\Api\Data\CustomerInterfaceFactory`
and `Magento\Customer\Api\CustomerRepositoryInterface;`
2. Executing the following code:
```
$customer = $this->customerFactory->create();
$customer->setId($id)
    ->setGroupId($groupId)
    ->setStoreId($storeId)
    ->setFirstname('New')
    ->setLastname('Customer')
    ->setWebsiteId($websiteID)
    ->setEmail('new.customer@something.com')
$this->customerRepository->save($customer);
```
With unused customer id and email.

### Expected result

1. Customer should be created with the provided values.

### Actual result

1. During execution of the save command the following error message is thrown:
```
[Magento\Framework\Exception\NoSuchEntityException]  
  No such entity with customerId = 17
```
The reason for this is the call to 
`$prevCustomerData = $this->getById($customer->getId());`
in the following file
`Magento/Customer/Model/ResourceModel/CustomerRepository.php`
at the beginning of the `save` function.

**Comment by magento-engcom-team** [comment]
@cphl91, thank you for your report.
This seems to be correct Magento behavior. In order to create new customer, he should have no id specified(as it's autoincrement). Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by willtran** [comment]
We are working on this #MLAU18 @zolat

**Comment by ishakhsuvarov** [comment]
Hi @cphl91
Closing this ticket now, as Customer entity does not have a predefined ID, therefore setting ID would not allow to create entity.
