### ISSUE TITLE
Topmenu 'last' class not being set if the a parent is inactive

### ISSUE THREAD

**Issue by arnoudhgz** [magento/magento2#13266]
When one or more parents in the top menu are inactive the 'last' class is not being set on the last item.

### Preconditions
1. Magento 2.2

### Steps to reproduce
1. Do a clean install of Magento 2.2 with sample data
2. Set a level 1 category (e.g. Gear or Gift Cards) inactive
3. Inspect the menu and see there is no class 'last' on the last active topmenu item

### Expected result
1. The last menu item should have the class **last**

### Actual result
1. The last menu item does not have the class **last**

#### Tech hints
- class `Magento\Theme\Block\Html\Topmenu`
- method `_getHtml`
- this part is not always being triggered correctly: `$child->setIsLast($counter == $childrenCount);`

**Comment by magento-engcom-team** [comment]
@arnoudhgz, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by arnoudhgz** [comment]
@magento-engcom-team I recreated the bugfix PR for Magento 2.3

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your report. 
The issue has been fixed in magento/magento2#22071 by @arnoudhgz in 2.3-develop branch
Related commit(s):
 - [151a48e148445c9d633739098b7bc7872ed62e9e](https://github.com/magento/magento2/commit/151a48e148445c9d633739098b7bc7872ed62e9e)
 - [967328dc6e968fb5f1d2a7c10cb9190a0c9ee66f](https://github.com/magento/magento2/commit/967328dc6e968fb5f1d2a7c10cb9190a0c9ee66f)
 - [3d3273c90080fda732be8d2c25dababe36bd73e5](https://github.com/magento/magento2/commit/3d3273c90080fda732be8d2c25dababe36bd73e5)
 - [2a7f5b5f39d21310f569b69749966c71ec025b71](https://github.com/magento/magento2/commit/2a7f5b5f39d21310f569b69749966c71ec025b71)

The fix will be available with the upcoming 2.3.3 release.
