### ISSUE TITLE
In the magenta (all versions) there is no option to choose Serbian-Latin

### ISSUE THREAD

**Issue by danijelkusic** [magento/magento2#13263]
### Preconditions

Magento 2.2.2 (but valid for all versions)
PHP 7.1.13
SQL 5.5.32
System Linux

### Steps to Reproduce
1. Serbian language has two letters Cyrillic and Latin. All versions of Magenta (so far) have taken Cyrillic as default (when selecting Configuration/General/Locale->Sebian), and that's fine, but Latin is also needed to be in options.
This is also true for "Interface Locale"!

### Expected result

1. Required Serbian language Latin

### Actual result

 There is only Serbian Cyrillic
It would be nice of someone to help me. How can I do this?

**Comment by magento-engcom-team** [comment]
@danijelkusic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @danijelkusic. Thank you for your report. 
The issue has been fixed in magento/magento2#22293 by @Bartlomiejsz in 2.3-develop branch
Related commit(s):
 - [a4f6b3c753c5df332be3545a26519581463d89f9](https://github.com/magento/magento2/commit/a4f6b3c753c5df332be3545a26519581463d89f9)
 - [1e6a2991f9ab3feef3baf2e0afdd70894ac9e7e9](https://github.com/magento/magento2/commit/1e6a2991f9ab3feef3baf2e0afdd70894ac9e7e9)
 - [29411feaac256670b5787d61217983fbdd974a88](https://github.com/magento/magento2/commit/29411feaac256670b5787d61217983fbdd974a88)

The fix will be available with the upcoming 2.3.4 release.
