### ISSUE TITLE
Wrong return type in Salesrule Module RuleInterface.php

### ISSUE THREAD

**Issue by Alviaz** [magento/magento2#13278]
### Preconditions

1.  Magento CE 2.2.2

### Steps to reproduce

1. creating a salesrule object via RuleInterfaceFactory and using its setIsActive() method before another setter method with method chaining.

### Expected result

1. Return typehint of setIsActive() of Magento\SalesRule\Api\Data\RuleInterface is RuleInterface type ($this).

### Actual result

1. Return typehint of setIsActive() of Magento\SalesRule\Api\Data\RuleInterface is bool type.

**Comment by magento-engcom-team** [comment]
@Alviaz, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by amit24029898** [comment]
I am working it #dcmcdindia

**Comment by amittiwari024** [comment]
I am working it #dmcdindia

**Comment by magento-engcom-team** [comment]
@amittiwari024 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by amittiwari024** [comment]
it is fixed https://github.com/amittiwari024/magento2/commit/5c91f4b139003d6571f6fc2d4fd688213e0422f0

**Comment by magento-engcom-team** [comment]
Hi @sanjay-wagento. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sanjay-wagento** [comment]
I am working on this issue at #MM19IN
