### ISSUE TITLE
Category name with special characters brakes in url rewrites category tree

### ISSUE THREAD

**Issue by galanis-a** [magento/magento2#13296]
### Preconditions
1. Magento 2.2.0
2. PHP 7.0
3. MySQL 5.6.35
4. Windows Docker

### Steps to reproduce
1. Create a category with quotes (") in its name. ex Test "Category"
2. Try to create a url rewrite (Go to Admin>>Marketing>>URL Rewrites>>Add URL Rewrite)
3. Select For Category in the dropdown

### Expected result
1. The full category tree should load and be able to select the category you want to create URL Rewrite for.

### Actual result
1. The category tree doesn't load at all
![image-2018-01-16-17-46-06-555](https://user-images.githubusercontent.com/6358839/35193208-16c7e948-fea8-11e7-88f8-8e356df5456f.png)
2. In the browser console throws this error
![url-rewrite-error](https://user-images.githubusercontent.com/6358839/35193309-51cc8db8-fea9-11e7-95e2-ac354427148d.png)

This is due to the category tree json not escaped in the Magento/UrlRewrite/view/adminhtml/templates/categories.phtml.
I overrided the file and changes it to this

`<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\UrlRewrite\Block\Catalog\Category\Tree $block */
?>
<fieldset class="admin__fieldset" data-ui-id="category-selector">
    <legend class="admin__legend"><span><?= $block->escapeHtml(__('Select Category')) ?></span></legend>
    <div class="content content-category-tree">
        <input type="hidden" name="categories" id="product_categories" value="" />
        <?php if ($block->getRoot()): ?>
            <div data-mage-init='<?php /* @noEscape */ echo htmlspecialchars(json_encode([
                'categoryTree' => [
                    'data' => $block->getTreeArray(),
                    'url' => $block->escapeUrl($block->getLoadTreeUrl()),
                ],
            ]),ENT_QUOTES, 'UTF-8'); ?>' class="jstree-default"></div>
        <?php endif; ?>
    </div>
</fieldset>`

it works but the special characters in category names are now shown escaped.
Ex. double quotes are #&quot and this is a problem.

I didn't test for pruducts or CMS pages.

**Comment by magento-engcom-team** [comment]
@galanis-a, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @galanis-a. Thank you for your report. 
The issue has been fixed in magento/magento2#13402 by @vinayshah in 2.3-develop branch
Related commit(s):
 - [bd5834cd1e0e6000f5b6560d389673aa97a24cb2](https://github.com/magento/magento2/commit/bd5834cd1e0e6000f5b6560d389673aa97a24cb2)
 - [46feb0b9de7e17eccc809153067d046e889243f4](https://github.com/magento/magento2/commit/46feb0b9de7e17eccc809153067d046e889243f4)
 - [aa31ff83f857fa50b12f3afd37ee666ff7afc74f](https://github.com/magento/magento2/commit/aa31ff83f857fa50b12f3afd37ee666ff7afc74f)
 - [c136ce8951c5c8a39a2b367e3165e34bd2cdc2be](https://github.com/magento/magento2/commit/c136ce8951c5c8a39a2b367e3165e34bd2cdc2be)
 - [9b67a3eca86f38291aa7730255c09cb8f1cb66ea](https://github.com/magento/magento2/commit/9b67a3eca86f38291aa7730255c09cb8f1cb66ea)
 - [6e1ac10efabe8ecd7b5f9640969a80bf0903753d](https://github.com/magento/magento2/commit/6e1ac10efabe8ecd7b5f9640969a80bf0903753d)
 - [9a73e4c07d78de302b18a7f9f0a1628a8d5eb999](https://github.com/magento/magento2/commit/9a73e4c07d78de302b18a7f9f0a1628a8d5eb999)
 - [f6c4efd871f68d3d6410c1b11311006f28822e54](https://github.com/magento/magento2/commit/f6c4efd871f68d3d6410c1b11311006f28822e54)
 - [b8b000b3a675fab24091664256219c2f2b5a18bd](https://github.com/magento/magento2/commit/b8b000b3a675fab24091664256219c2f2b5a18bd)
 - [33144f9965d34a1e23d653f23f22810d84fd22f0](https://github.com/magento/magento2/commit/33144f9965d34a1e23d653f23f22810d84fd22f0)
 - [47b544092c4543966e4f176d7f8f16ea5b22826a](https://github.com/magento/magento2/commit/47b544092c4543966e4f176d7f8f16ea5b22826a)
 - [2ef98ac7ca9966d9c896fb8ddf30e920325003e2](https://github.com/magento/magento2/commit/2ef98ac7ca9966d9c896fb8ddf30e920325003e2)
 - [3ce79eb8ea7098a22071e091b5d98d6478007236](https://github.com/magento/magento2/commit/3ce79eb8ea7098a22071e091b5d98d6478007236)
 - [8b8d5ce8ea825db1aba642d246875168f484406e](https://github.com/magento/magento2/commit/8b8d5ce8ea825db1aba642d246875168f484406e)
 - [2c97259e1780f42658cb475c0ea2c22d3619ae76](https://github.com/magento/magento2/commit/2c97259e1780f42658cb475c0ea2c22d3619ae76)
 - [de3b966fae57ae03e4f0eee02ad4673c250de0ec](https://github.com/magento/magento2/commit/de3b966fae57ae03e4f0eee02ad4673c250de0ec)
 - [597d5486c5cb5dab00bf12e08595161854d002b5](https://github.com/magento/magento2/commit/597d5486c5cb5dab00bf12e08595161854d002b5)
 - [30989e1c98bfc0302dfc5e230aba4a9e32dd22fc](https://github.com/magento/magento2/commit/30989e1c98bfc0302dfc5e230aba4a9e32dd22fc)
 - [b9d2e5385e85af7f0e204b18e12715e44b190863](https://github.com/magento/magento2/commit/b9d2e5385e85af7f0e204b18e12715e44b190863)
 - [b52787a4ef7481c58a2f47d8e9895e70ac9874bf](https://github.com/magento/magento2/commit/b52787a4ef7481c58a2f47d8e9895e70ac9874bf)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @galanis-a. Thank you for your report. 
The issue has been fixed in magento/magento2#13397 by @vinayshah in 2.2-develop branch
Related commit(s):
 - [20396d562f46ccc8914e764295ff99b40864bead](https://github.com/magento/magento2/commit/20396d562f46ccc8914e764295ff99b40864bead)
 - [a22b6fd60c5ff3d99ee7d48acd0d54bd13af19bb](https://github.com/magento/magento2/commit/a22b6fd60c5ff3d99ee7d48acd0d54bd13af19bb)
 - [ff4f6cf7646bb8364ab236ab54ddf5f26bf28a84](https://github.com/magento/magento2/commit/ff4f6cf7646bb8364ab236ab54ddf5f26bf28a84)
 - [934a0a31b0ede4965239d1a3bba536a3224d89d8](https://github.com/magento/magento2/commit/934a0a31b0ede4965239d1a3bba536a3224d89d8)
 - [1bd6356ebd3250f28aa9cb6550cd955c29b82e56](https://github.com/magento/magento2/commit/1bd6356ebd3250f28aa9cb6550cd955c29b82e56)
 - [4bdba3601ac51c50a0484460fdbb69c17524cce8](https://github.com/magento/magento2/commit/4bdba3601ac51c50a0484460fdbb69c17524cce8)
 - [e764e6880bdb8686980520e62a303170bc16daa3](https://github.com/magento/magento2/commit/e764e6880bdb8686980520e62a303170bc16daa3)
 - [ac21097579ca5dd35963dfea274caf2fe47a1fac](https://github.com/magento/magento2/commit/ac21097579ca5dd35963dfea274caf2fe47a1fac)
 - [b9821e99aecf8ce8bfe5c3619c35f4c06d4865f8](https://github.com/magento/magento2/commit/b9821e99aecf8ce8bfe5c3619c35f4c06d4865f8)
 - [6fec23255d82de0e909de1645f7b7fec030ef0a2](https://github.com/magento/magento2/commit/6fec23255d82de0e909de1645f7b7fec030ef0a2)
 - [c33d27f18acceb2a144f4bbc9495708999346777](https://github.com/magento/magento2/commit/c33d27f18acceb2a144f4bbc9495708999346777)
 - [fc510c4409502a6c7912316756652b3261354e98](https://github.com/magento/magento2/commit/fc510c4409502a6c7912316756652b3261354e98)
 - [f300c39f9e406d822b1e8806eaf9d7128cce11fb](https://github.com/magento/magento2/commit/f300c39f9e406d822b1e8806eaf9d7128cce11fb)
 - [b74734381108eb414e0b69296b0b5ea200f1b78b](https://github.com/magento/magento2/commit/b74734381108eb414e0b69296b0b5ea200f1b78b)
 - [851cc3af44fbbe47ae87db92d761640c30e15f7c](https://github.com/magento/magento2/commit/851cc3af44fbbe47ae87db92d761640c30e15f7c)
 - [af0f2e9ff1ad824cab180078f2cf4ca7ee6e16f2](https://github.com/magento/magento2/commit/af0f2e9ff1ad824cab180078f2cf4ca7ee6e16f2)
 - [05dfa6ee46221bbc3f6d26f047b21a8388cd8c62](https://github.com/magento/magento2/commit/05dfa6ee46221bbc3f6d26f047b21a8388cd8c62)

The fix will be available with the upcoming 2.2.5 release.
