### ISSUE TITLE
All SampleData should be installed last in bin/magento setup:install

### ISSUE THREAD

**Issue by AntonEvers** [magento/magento2#13292]
### Preconditions

1. Magento 2.1-develop
2. Magento 2.2-develop
3. Magento 2.3-develop

### Steps to reproduce

1. Create a module that saves a custom customer attribute on the event customer_address_save_before
2. Your module dependency is on 'Magento_Customer'

In my case the code is:
```php
<?php

namespace Example\Customer\Observer;

use Magento\Framework\Event\ObserverInterface;

/**
 * Class SyncNeeded
 * @package Example\Customer\Observer
 */
class SyncNeeded implements ObserverInterface
{
    /**
     * @var \Magento\Customer\Model\CustomerFactory
     */
    private $customerFactory;

    /**
     * @var \Magento\Customer\Model\ResourceModel\CustomerFactory
     */
    private $customerResourceFactory;

    /**
     * SyncNeeded constructor.
     * @param \Magento\Customer\Model\CustomerFactory $customerFactory
     * @param \Magento\Customer\Model\ResourceModel\CustomerFactory $customerResourceFactory
     */
    public function __construct(
        \Magento\Customer\Model\CustomerFactory $customerFactory,
        \Magento\Customer\Model\ResourceModel\CustomerFactory $customerResourceFactory
    ) {
        $this->customerFactory = $customerFactory;
        $this->customerResourceFactory = $customerResourceFactory;
    }

    /**
     * @param \Magento\Framework\Event\Observer $observer
     * @throws \Exception
     */
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        /** @var \Magento\Customer\Model\Address $address */
        $address = $observer->getEvent()->getCustomerAddress();
        /** @var \Magento\Customer\Model\Backend\Customer $customer */
        $customerId = $address->getCustomer()->getId();

        /** @var \Magento\Customer\Model\Customer $customer */
        $customer = $this->customerFactory->create();
        $customerData = $customer->getDataModel();
        $customerData->setId($customerId);
        $customerData->setCustomAttribute('sync_needed', 1);
        $customer->updateData($customerData);
        /** @var \Magento\Customer\Model\ResourceModel\Customer $customerResource */
        $customerResource = $this->customerResourceFactory->create();
        $customerResource->saveAttribute($customer, 'sync_needed');
    }
}
?>
```

### Expected result

1. `bin:magento setup:install` runs without errors

### Actual result

1. `bin:magento setup:install` cannot install Magento_CustomerSampleData because it installs before Example_Customer.
2. The Example_Customer code is already in place and will be executed, the Example_Customer attributes have not yet been installed, so the observer crashes on a non existing attribute.

Sample data installation performs operations that normally happen after Magento has been installed completely. They are representations of real life situations such as customer saves and order creations. These actions should therefore depend on the installation of all regular modules.

**Comment by orlangur** [comment]
Quoting from https://github.com/magento/magento2-sample-data:

> Installing sample data is optional.
Technically, sample data is a set of regular Magento modules, which can be deployed and installed together with the Magento instance, or later in the scope of upgrade.

Note that sample data modules are not even a part of core. They are not guaranteed to work on customized Magento installations.

So, instead of `Magento_CustomerSampleData` you may need a similar module with requirement to both `Magento_Customer` and `Example_Customer`. Other option is to simply install sample data after all bunsiness logic-related modules are installed.

I don't see what to fix here from core perspective, behavior seems correct and quite predictable to me.

**Comment by AntonEvers** [comment]
Sure, installing sample data after the initial installation is an option when you use sample data during development or manual deployment. 

As a plugin developer I'd like to have a demo shop where I can display my plugins. automatic deployment of a git branch that includes all of my plugins and the sample data in the `composer.json` file makes sure that when I update the demo shop, my prospect customers have something to play with. For instance products they can 'buy'. So it is quite practical for non-core development that this sample data is available and gets installed properly no matter what (really breaking custom code aside).

I get that the sample data is not guaranteed to work with customized Magento installations. But this little change makes it lots more likely to work with them than the current setup. Installing a third module that solely fixes a dependency seems less than ideal to me.

For the sake of demo shops, would you be open to this functionality if I am able to do it in a less magical fashion?

**Comment by orlangur** [comment]
Sometimes in order to adopt default sample data you may need something more than just changing order of module installation.

For described scenario I believe it would be best to have your own sample data metapackage and some additional small modules like `Example_CustomerSampleData` if you need some modifications on top of official sample data.

> For the sake of demo shops, would you be open to this functionality if I am able to do it in a less magical fashion?

Please describe proposed implementation approach first and then it can be evaluated. My main concern is that we already have a clear way to define dependencies between modules and I would like to avoid unnecessary entities introduction (Occam's razor).

Just like I don't like unnecessary (as to me) distinction between modules/lang pack/m2 theme composer packages, your suggestion looks like introduction of another type of module with separate rules.

**Comment by AntonEvers** [comment]
You're right. Instead of writing code to fix this, it might be better to write a devdocs entry in order to point others to a working solution with the current code.

Any programming solution will result in dependencies between normal modules and sample data modules not being followed strictly anymore or becoming impossible altogether.

**Comment by jeff-matthews** [comment]
Hi @ajpevers! Please don't hesitate to open an issue or pull request in the [devdocs](https://github.com/magento/devdocs) repo if you have suggestions for improving the content on http://devdocs.magento.com.
