### ISSUE TITLE
Lifetime update syntax error

### ISSUE THREAD

**Issue by navalnichnik** [magento/magento2#13309]
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/Cache/Backend/Database.php#L436

Should be (question sign is missing):

` ['id=?' => $id, 'expire_time = 0 OR expire_time>?' => time()]`

**Comment by magento-engcom-team** [comment]
Please use our issue reporting template to describe this issue. The template specifies the version and configuration information we need to assess your issue. See the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) for more information.

**Comment by navalnichnik** [comment]
@magento-engcom-team 
Really? Don't you see a syntax error?
It's valid for any available version of Magento 2.

**Comment by magento-engcom-team** [comment]
@navalnichnik, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ssp58bleuciel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @navalnichnik. Thank you for your report. 
The issue has been fixed in magento/magento2#19634 by @ssp58bleuciel in 2.3-develop branch
Related commit(s):
 - [146f74a5fb82f1bcb82a20beda67306cdb45c246](https://github.com/magento/magento2/commit/146f74a5fb82f1bcb82a20beda67306cdb45c246)
 - [70056f54311ac889ead8aa8c0d83d82827659647](https://github.com/magento/magento2/commit/70056f54311ac889ead8aa8c0d83d82827659647)

The fix will be available with the upcoming 2.3.1 release.

**Comment by cscd98** [comment]
@navalnichnik What does this fix exactly?

**Comment by magento-engcom-team** [comment]
Hi @navalnichnik. Thank you for your report. 
The issue has been fixed in magento/magento2#21078 by @ssp58bleuciel in 2.2-develop branch
Related commit(s):
 - [4cb01ef1823358aa9444f348e51e4c65c5bb95b6](https://github.com/magento/magento2/commit/4cb01ef1823358aa9444f348e51e4c65c5bb95b6)
 - [5ecc6b2c9f3e205fc41f86b8feecc77a8521fb0f](https://github.com/magento/magento2/commit/5ecc6b2c9f3e205fc41f86b8feecc77a8521fb0f)

The fix will be available with the upcoming 2.2.9 release.
