### ISSUE TITLE
Mobile "Payment Methods" step looks bad on mobile

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#13315]
### Preconditions
1. Magento 2.2.2, or from 2.2.4-develop branch
2. Create some products that you could buy

### Steps to reproduce
1. Go to frontend, add some product to shopping cart on mobile (or in iphone emulation mode on chrome)
2. Go to Checkout, fill "shipping" step, click "Next" button
3. See "Payment Methods" block

### Expected result
1. "Payment Method" title should looks good, there should be space before it
![capture 2018-01-01 at 16 10 15](https://user-images.githubusercontent.com/1873745/35224757-c096c28c-ff8e-11e7-9528-647df6c08f1b.png)

### Actual result
1. "Payment Method" title looks not so good, there is no space before it
![capture 2018-01-01 at 16 08 42](https://user-images.githubusercontent.com/1873745/35224724-abc594d2-ff8e-11e7-9a68-d987958388f7.png)

**Comment by magento-engcom-team** [comment]
@ihor-sviziev, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#13777 by @Frodigo in 2.2-develop branch
Related commit(s):
 - [db7d29973e3d03f513ee9f5517567c902e99e8c5](https://github.com/magento/magento2/commit/db7d29973e3d03f513ee9f5517567c902e99e8c5)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#13979 by @Frodigo in 2.3-develop branch
Related commit(s):
 - [b27ec8cdbd37bfbb1b67c5a944b6d961ca12ae59](https://github.com/magento/magento2/commit/b27ec8cdbd37bfbb1b67c5a944b6d961ca12ae59)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#13980 by @Frodigo in 2.1-develop branch
Related commit(s):
 - [17a707a15532897920beee2e9f074dd1e103ef55](https://github.com/magento/magento2/commit/17a707a15532897920beee2e9f074dd1e103ef55)

The fix will be available with the upcoming 2.1.14 release.
