### ISSUE TITLE
Magento 2 Tier Pricing Not Working As Expected on Product Page.

### ISSUE THREAD

**Issue by 666triv** [magento/magento2#13314]
### Preconditions

1. Magento 2.2

### Steps to reproduce

1. I have added a set number of tiered pricing for product "A" which it's base price is £50 and set 5 tiers as below:

 - Buy 5 at £45 (All Groups "General, Guest & wholesale)
 - Buy 10 at £40 (All Groups)
 - Buy 15 at £35 (All Groups)
 - Buy 20 at £30 (All Groups)
 - Buy 25 at £25 (All Groups)

I have set a specific wholesale price tier for:

 - Buy 15 at £20 (Wholesale Only)

But on my frontend the tier pricing for a wholesale customer looks like this:

 - Buy 5 at £45 (All Groups) <---- This is working as expected.
 - Buy 10 at £40 (All Groups) <---- This is working as expected.
 - Buy 15 at £20 (Wholesale) <---- This is working as expected.
 - Buy 20 at £30 (All Groups) <---- Should be hidden.
 -  Buy 25 at £25 (All Groups) <---- Should be hidden.

The basket works in the way you would expect any qty over 15 pieces the price stays at £20 but the product page does not update.

### Expected result

1.  The tier price higher than what the customer would receive should be hidden as it's not relevant to that specific customer group. Rather than showing all available, as it was hidden in Magento 1 so has the programming/logic for this changed.

### Actual result

1. The higher tier price values which include the customer group browsing a product an still see the tier prices for higher quantities even when the discount is grater.

**Comment by magento-engcom-team** [comment]
@666triv, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ssp58bleuciel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Delta** [comment]
Hi @666triv ,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached screenshots.


<img width="1440" alt="Screenshot 2024-05-23 at 6 13 29 PM" src="https://github.com/magento/magento2/assets/51681379/5730010e-7e23-4ce3-a7de-c638c9b1fb17">

<img width="1435" alt="Screenshot 2024-05-23 at 6 16 06 PM" src="https://github.com/magento/magento2/assets/51681379/a25d5b9b-7e97-484e-977c-3bdfa9067fef">

<img width="1440" alt="Screenshot 2024-05-23 at 6 16 32 PM" src="https://github.com/magento/magento2/assets/51681379/2abdba37-a70e-4532-97c9-c9254c8be8fc">

<img width="1440" alt="Screenshot 2024-05-23 at 6 22 20 PM" src="https://github.com/magento/magento2/assets/51681379/db78fd2b-3683-4798-9865-94ecc1451ff6">

<img width="1404" alt="Screenshot 2024-05-23 at 6 32 34 PM" src="https://github.com/magento/magento2/assets/51681379/9d8d2a18-9758-4fd9-83c7-00497483c76b">

Hence closing this.
