### ISSUE TITLE
2 .htaccess files?

### ISSUE THREAD

**Issue by steverobbins** [magento/magento2#1331]
I'm curious as to why [`.htaccess`](https://github.com/magento/magento2/blob/develop/.htaccess) and [`pub/.htaccess`](https://github.com/magento/magento2/blob/develop/pub/.htaccess) both exist.

They seem to be mostly the same (I notice there are two memory limits, `256M` and `768M`.  Which is correct?).  Perhaps `.htaccess` is a remnant of Magento1?  Can it be removed?

Same goes for `.htaccess.sample`.  It's used in Magento1 for the `Enterprise_Staging` module, but it doesn't appear to be being used here.

**Comment by alankent** [comment]
The pub directory I think handles image rendering / resizing for media. See static.php. The htaccess file checks to see if file already produced, else calls static.php file.

(Maybe - a little knowledge can be a dangerous thing!)

**Comment by steverobbins** [comment]
I believe a separate [`pub/status/.htaccess`](https://github.com/magento/magento2/blob/develop/pub/static/.htaccess#L17) is used for `static.php` operations.

**Comment by buskamuza** [comment]
@steverobbins , yes, `pub/static/.htaccess` is used for handling static view files.
`index.php` and `.htaccess` that exist in both root and `pub` folders are to cover two use cases:
1. simple installation, when document root = Magento code base root
2. more secure installation, when document root = `pub`

**Comment by steverobbins** [comment]
@buskamuza In that case

* Should the contents of both `.htaccess` files be the same?
  * If so, which memory limit is the correct one?
* Should the contents of both `index.php` files be the same (other than `require __DIR__ . '/app/bootstrap.php';` vs `require __DIR__ . '/../app/bootstrap.php';`)?
* Should `.htaccess.sample` be removed?

**Comment by buskamuza** [comment]
1. `.htaccess`. @steverobbins , yes, they should be identical, except the things you've mentioned + "Deny access  to cron.php" in the `pub/.htaccess`
I'd say that the one in the root should be more accurate now, as this is more common scenario for using Magento on current, development, stage.
2. `index.php`. Logically - yes, they should be the same. But because of different root folder, `pub/index.php` has additional configuration for URLs
```
$params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS] = [
    DirectoryList::PUB => [DirectoryList::URL_PATH => ''],
    DirectoryList::MEDIA => [DirectoryList::URL_PATH => 'media'],
    DirectoryList::STATIC_VIEW => [DirectoryList::URL_PATH => 'static'],
    DirectoryList::UPLOAD => [DirectoryList::URL_PATH => 'media/upload'],
];
```
`<root>/index.php` uses default values, which would be like `pub/media` instead of `media`, etc. If it will be calculated based on `BP` instead of hard-coded, the contents can be the same, except the bootstrap part. Not sure that it will be more efficient. Maybe having a static test to verify the content would be better, as these files should not change often.
3. `.htaccess.sample`. Theoretically, it may help to restore original values in case you modified something in the original `.htaccess` and don't have the code under version control. I'm not sure that this is the case that we should care now, but I'd leave it to our architects. @alankent , do you know anything about why we still keep this file?

**Comment by alankent** [comment]
Sorry, I don't know this level of detail on .htaccess files

**Comment by hostep** [comment]
Just noticed some other problems with the .htaccess file in the `pub` subdirectory which apply If you serve Magento from the `pub` directory (which is recommended in the [docs](http://devdocs.magento.com/guides/v2.0/howdoi/deploy/deploy-to-prod.html#checklist-prod) btw)

The .htaccess file in the `pub` subdirectory is missing these two lines:

```
Header set X-Content-Type-Options "nosniff"
Header set X-XSS-Protection "1; mode=block"
```

And this line may be removed as I believe it is added through the PHP code:

```
Header set X-Frame-Options SAMEORIGIN
```

Also these lines may be removed, seems like a leftover from Magento 1:

```
###########################################
## Deny access to release notes to prevent disclosure of the installed Magento version

    <Files RELEASE_NOTES.txt>
        order allow,deny
        deny from all
    </Files>
```

So like @buskamuza says the file should be identical from the one in the root directory with the exception of denying access to the cron.php file.

(completely off topic: is the memory_limit of 768M really necessary? It seems way to much in my opinion)

**Comment by steverobbins** [comment]
@hostep The recommendation for M1 is 512MB.  If M2 needs "more umf" that might be understandable.

I think the the non-pub `.htaccess` and `index.php` should be removed entirely.  Publish a separate document on how to host the site in the Magento document root (for shared hosts, etc), where you copy these files over.

That way only one of each file needs to be maintained in this repo, people won't accidentally do a non-pub install, but those who need this configuration are still supported.

**Comment by hostep** [comment]
In practice we run almost all our M1 shops on 128M, some exceptions need more, but most of them work perfectly fine with 128M :)
So that's why I think the 768M is very high, the only thing I can think of why it would need such a high amount of memory is because of the LESS compilation through php (which should only be needed on develop environments).

Anyways, back on topic: I totally agree with recommending serving M2 from the `pub` directory, but I don't think the Magento guys want that since they have mentioned this in other threads unfortunately.

**Comment by maksek** [comment]
Closing the topic, for further discussion please create topic in forum.
