### ISSUE TITLE
Menu ui-state-active not removed from previous opened menu item

### ISSUE THREAD

**Issue by arnoudhgz** [magento/magento2#13327]
The `ui-state-active` clas is not removed from the previous opened main menu item when you open a new main menu item.

### Preconditions
1. Clean Magento 2.2 installation with sample data
2. You are in mobile view

### Steps to reproduce
1. In your browser switch to mobile view so you have the mobile menu
2. Open the menu
3. Expand the menu item **Women**
4. Now expand the menu item **Men**
5. You will see that the `ui-state-active` class is still also on **Women**

### Expected result
1. The previous opened main menu item should not have the class `ui-state-active`

### Actual result
1. The previous opened main menu item has the class `ui-state-active` (see screenshot)

![image](https://user-images.githubusercontent.com/10864061/35275749-0a6cf608-0041-11e8-80c1-d84cf3bb45fc.png)

**Comment by magento-engcom-team** [comment]
@arnoudhgz, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your report. 
The issue has been fixed in magento/magento2#13341 by @arnoudhgz in 2.2-develop branch
Related commit(s):
 - 5714ffd97f8b8f21c46e047d74a02bd75742002b
 - 5773225311c87d3717a11401bfd030a9ecba8533

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
Hi @arnoudhgz. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1380 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - [e9238bcb04f75a5ef0d801ef7a4c372832d83aad](https://github.com/magento/magento2/commit/e9238bcb04f75a5ef0d801ef7a4c372832d83aad)
 - [c46acb7f26afb967c2e727d9557d00a03418a599](https://github.com/magento/magento2/commit/c46acb7f26afb967c2e727d9557d00a03418a599)
 - [3d5cc519f30a8664aadca0b1378ff62138fd1bf9](https://github.com/magento/magento2/commit/3d5cc519f30a8664aadca0b1378ff62138fd1bf9)
 - [fcd3e7af7984ed9887a8213c51ff3cc29546fd93](https://github.com/magento/magento2/commit/fcd3e7af7984ed9887a8213c51ff3cc29546fd93)
 - [a37313a401cd143fbfb6642108f602a16d96d211](https://github.com/magento/magento2/commit/a37313a401cd143fbfb6642108f602a16d96d211)
 - [4e00485ed12b762e38bbf5e38cce97981a43dedf](https://github.com/magento/magento2/commit/4e00485ed12b762e38bbf5e38cce97981a43dedf)
 - [d73cca2aee6113f66e8098512343d4e440afe65e](https://github.com/magento/magento2/commit/d73cca2aee6113f66e8098512343d4e440afe65e)
 - [0d8938cfd7f6c85146e1ad3176947eb6f8a945ae](https://github.com/magento/magento2/commit/0d8938cfd7f6c85146e1ad3176947eb6f8a945ae)
 - [d544ca2a6d99132e66e8b416ab73cc712de149f9](https://github.com/magento/magento2/commit/d544ca2a6d99132e66e8b416ab73cc712de149f9)
 - [e075ca794af8189260359434488029b2768fc29d](https://github.com/magento/magento2/commit/e075ca794af8189260359434488029b2768fc29d)
 - [a6c2bc2b471586eb44d9b4fc2341517bb64cad15](https://github.com/magento/magento2/commit/a6c2bc2b471586eb44d9b4fc2341517bb64cad15)
 - [960d58cfc3ef200654f1c19a5eca8cb905da686c](https://github.com/magento/magento2/commit/960d58cfc3ef200654f1c19a5eca8cb905da686c)
 - [dbdb772c0260347267701f5f54196fec1c0e5109](https://github.com/magento/magento2/commit/dbdb772c0260347267701f5f54196fec1c0e5109)
 - [bac46ce7f62207e27fdb401e4e72040c2bed32db](https://github.com/magento/magento2/commit/bac46ce7f62207e27fdb401e4e72040c2bed32db)
 - [1503f3a49de2d20ed3729823a4410cbfba3fd92a](https://github.com/magento/magento2/commit/1503f3a49de2d20ed3729823a4410cbfba3fd92a)
 - [17662c6eb0948da16b97a93ad0c231947eba933d](https://github.com/magento/magento2/commit/17662c6eb0948da16b97a93ad0c231947eba933d)
 - [2a72e5cc81c7b28aa04c5c64a63a8493043d6384](https://github.com/magento/magento2/commit/2a72e5cc81c7b28aa04c5c64a63a8493043d6384)
 - [ddaf5c6df7e2b294085ef6133820a6a1b6b12762](https://github.com/magento/magento2/commit/ddaf5c6df7e2b294085ef6133820a6a1b6b12762)
 - [7bf80fdc06c32325040dada5082b78975b910e1b](https://github.com/magento/magento2/commit/7bf80fdc06c32325040dada5082b78975b910e1b)
 - [efb8bf6a94a99130fe013f4ef9c3c0c39777b7b1](https://github.com/magento/magento2/commit/efb8bf6a94a99130fe013f4ef9c3c0c39777b7b1)
 - [321263009819a694221ce8a06902cf7a4ba3ff00](https://github.com/magento/magento2/commit/321263009819a694221ce8a06902cf7a4ba3ff00)
 - [ac9c10b96940ed5393581135146c8ea29eddd143](https://github.com/magento/magento2/commit/ac9c10b96940ed5393581135146c8ea29eddd143)
 - [2c6c9c06b1a69a20f4b7bfcd27e1eebf8e26ad2b](https://github.com/magento/magento2/commit/2c6c9c06b1a69a20f4b7bfcd27e1eebf8e26ad2b)
 - [73522bf72d57e503281077abb20b4000375eb57d](https://github.com/magento/magento2/commit/73522bf72d57e503281077abb20b4000375eb57d)
 - [818cf61d28821cc2a5435c60b6308adcb5a3ea26](https://github.com/magento/magento2/commit/818cf61d28821cc2a5435c60b6308adcb5a3ea26)
 - [61d0d9608493f65a0c0eafe264e1575eaa84b7be](https://github.com/magento/magento2/commit/61d0d9608493f65a0c0eafe264e1575eaa84b7be)
 - [85e0956b08923ca721e3577edd684aec02a93b6b](https://github.com/magento/magento2/commit/85e0956b08923ca721e3577edd684aec02a93b6b)
 - [1698afc93aed22284efa2bf9d943b2108b5af3ab](https://github.com/magento/magento2/commit/1698afc93aed22284efa2bf9d943b2108b5af3ab)
 - [ce7faf6203e39aefdf177e2a6a4168cbb5223993](https://github.com/magento/magento2/commit/ce7faf6203e39aefdf177e2a6a4168cbb5223993)
 - [70051020df3e9053272cc6926680895b9898a35b](https://github.com/magento/magento2/commit/70051020df3e9053272cc6926680895b9898a35b)
 - [bd07bcc9e681810ac35fd59b3ef74970e55dca37](https://github.com/magento/magento2/commit/bd07bcc9e681810ac35fd59b3ef74970e55dca37)
 - [16930193a78f00b50f9fa16012d96c5c1d481f19](https://github.com/magento/magento2/commit/16930193a78f00b50f9fa16012d96c5c1d481f19)
 - [ba7da597361305e6a91c04fe39d63162408af3b3](https://github.com/magento/magento2/commit/ba7da597361305e6a91c04fe39d63162408af3b3)
 - [d9e8b87af003d550f39e9d34cf19f94088660a38](https://github.com/magento/magento2/commit/d9e8b87af003d550f39e9d34cf19f94088660a38)
 - [0bb740b82dcf7324dad4b1650f13838b51950368](https://github.com/magento/magento2/commit/0bb740b82dcf7324dad4b1650f13838b51950368)
 - [c51f94c3a115468ea4808478e67c88c13dca1445](https://github.com/magento/magento2/commit/c51f94c3a115468ea4808478e67c88c13dca1445)
 - [9f3f3e05d91951f56b469cf47576e3c2eb72a9b5](https://github.com/magento/magento2/commit/9f3f3e05d91951f56b469cf47576e3c2eb72a9b5)

The fix will be available with the upcoming 2.3.0 release.
