### ISSUE TITLE
Products grid in admin does not display default values?

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#13338]
Hello,
I don't know if it's the expected behavior, but the products grid in admin does not seem to display the default values.

### Preconditions

- Magento 2.2.2
- PHP 7.0.25
- Maria DB 10.2.9

### Steps to reproduce

1. Create the following stores configuration:
- Website EU
    - Store EU
        - Store view FR
        - Store view EN
- Website US
    - Store US
        - Store view EN

2. Create a product with this names:
- Default configuration: My product
- Store view FR from website EU : My product EU FR
- Store view EN from website EU : My product EU EN
- Store view EN from website US : My product US EN

### Expected result

On the products grid, my product's name is "My product" when I have no filter selected.

### Actual result

On the products grid, my product's name is "My product EU FR" when I have no filter selected.

**Comment by magento-engcom-team** [comment]
@VincentMarmiesse, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by julian-van-drielen** [comment]
I'm working on this. #distributed-cd

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @VincentMarmiesse. Thank you for your report. 
The issue has been fixed in magento/magento2#21363 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [a0be69b48ad0ac15834c31787d8a4fbc9c4b0ab1](https://github.com/magento/magento2/commit/a0be69b48ad0ac15834c31787d8a4fbc9c4b0ab1)
 - [9e657ad9a2696e15a346d636a245c9a2184e9019](https://github.com/magento/magento2/commit/9e657ad9a2696e15a346d636a245c9a2184e9019)
 - [5d2ffad7b23d1c7d6fe46d9288217ee5a1df4e5e](https://github.com/magento/magento2/commit/5d2ffad7b23d1c7d6fe46d9288217ee5a1df4e5e)
 - [edc66baf9d24944b9d3ee39125e0ff89e804b81b](https://github.com/magento/magento2/commit/edc66baf9d24944b9d3ee39125e0ff89e804b81b)
 - [14dbb4f3470780daa74644dc1450ec6e99cdcaf2](https://github.com/magento/magento2/commit/14dbb4f3470780daa74644dc1450ec6e99cdcaf2)

The fix will be available with the upcoming 2.3.2 release.
