### ISSUE TITLE
Fatal error when using GiftCardAccountRepositoryInterface

### ISSUE THREAD

**Issue by bydrei** [magento/magento2#13330]
When you DI `\Magento\GiftCardAccount\Api\GiftCardAccountRepositoryInterface` into a constructor to use the supposed repository is used upon you it fails.

### Preconditions

1. Magento 2.1.9
2. PHP 7.0.27
3. MySQL Ver 14.14 Distrib 5.7.21

### Steps to reproduce

1. Create a new custom module
2. Inject` \Magento\GiftCardAccount\Api\GiftCardAccountRepositoryInterface` into a class constructor.
3. Call getList with a search criteria

### Expected result

1. You should receive data accordingly. 

### Actual result

1. `Fatal error: Cannot instantiate interface Magento\\GiftCardAccount\\Api\\Data\\GiftCardAccountSearchResultInterface`

**Comment by magento-engcom-team** [comment]
@ferrazzuk , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@ferrazzuk, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
