### ISSUE TITLE
REST API unable to make requests with slash (/) in SKU again

### ISSUE THREAD

**Issue by manhao-chen** [magento/magento2#13343]
as reported with https://github.com/magento/magento2/issues/8615

### Preconditions
1. Tested in CE 2.2.2

### Steps to reproduce
Fresh install
Create product (of any type) with SKU containing /, e.g. "ELEVATOR_HEADS-5/0 1oz-Orange"

searching for the product with 
GET : /rest/v1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=ELEVATOR_HEADS-5%2F0%201oz-Orange
returns results as expected

but when getting the stockItems with the following
GET : /rest/V1/stockItems/ELEVATOR_HEADS-5%2F0+1oz-Orange
result 404 status - BUT the actual data is returned?

when trying to update the stockItem 
PUT : /rest/V1/products/ELEVATOR_HEADS-5%2F0+1oz-Orange/stockItems/100
result : 404 status - message=Request does not match any route.

### Expected result
expect 
/rest/V1/stockItems/[sku containing / to also work]
/rest/V1/products/[sku containing / to also work]/stockItems/[stockItemID]

both to work in the same manner as sku without '/'

### Actual result
GET : /rest/V1/stockItems/ELEVATOR_HEADS-5%2F0+1oz-Orange
result 404 status - BUT the actual data is returned?

PUT : /rest/V1/products/ELEVATOR_HEADS-5%2F0+1oz-Orange/stockItems/100
result : 404 status - message=Request does not match any route.

**Comment by magento-engcom-team** [comment]
@manhao-chen, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Arhimenrius** [comment]
To be honest, the problem is not with code but with server config. Servers by default block possibility to send even encoded slash as part of url (but not in case of param).

Solution for Apache might be **AllowEncodedSlashes**
In case of Nginx, **proxy_pass**

**Comment by ksiamro** [comment]
@Arhimenrius 
Solution with AllowEncodedSlashes works great.

Thanks ;)

**Comment by irajneeshgupta** [comment]
@magento-engcom-team @engcom-backlog-nazar I think its not a issue. Can you please review and close?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @manhao-chen Hi @irajneeshgupta the issue was retested, and we can confirm that this is non issue.

**Comment by xfolder** [comment]
Hi. I've same issue with DELETE CURL. Encoding the sku returns the payload but the product is not deleted.

Magento 2.3
