### ISSUE TITLE
How to load third-party javascript library in Magento2?

### ISSUE THREAD

**Issue by hackin88** [magento/magento2#1334]
======
en_US
======

1)

How to load third-party javascript library in Magento2?

I would charge the following library in Mageno2

https://github.com/rstacruz/nprogress

How do I?

2)

2)

in

/app/code/<VendorName>/<ModuleName>/view/frontend/layout/default.xml

I have

<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">
    <head>
        <link src="<VendorName>_<ModuleName>::js/web/nprogress/nprogress.js"/>
    </head>
</page>

Where is loaded this file

But it returned in firebug error

Error: Mismatched anonymous define() module: function () {
  var NProgress = {};
  ...
}
http://requirejs.org/docs/errors.html#mismatch	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

I think that way I'm doing something wrong

======
pt_BR
======

1)

Como carregar biblioteca de javascript de terceiros no Magento2 ?

Gostaria de carregar a seguinte biblioteca no Mageno2

https://github.com/rstacruz/nprogress

Como faço ?

2)

Em

/app/code/<VendorName>/<ModuleName>/view/frontend/layout/default.xml

Tenho

<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../lib/internal/Magento/Framework/View/Layout/etc/page_configuration.xsd">
    <head>
        <link src="<VendorName>_<ModuleName>::js/web/nprogress/nprogress.js"/>
    </head>
</page>

Onde é carregado esse arquivo

Mas é retornado no firebug o erro

Error: Mismatched anonymous define() module: function () {
  var NProgress = {};
  ...
}
http://requirejs.org/docs/errors.html#mismatch	

var e = new Error(msg + '\nhttp://requirejs.org/docs/errors.html#' + id);

Creio que dessa forma estou fazendo algo errado

**Comment by guz-anton** [comment]
> 1) How to load third-party javascript library in Magento2?

Current version Magento2 (v.0.74.0) works with external (same as internal) JavaScript files as with AMD modules through RequireJS. You can load external file (e. g. nprogress) via:
 - `require` or `define` call
 - [`deps`-key](http://requirejs.org/docs/api.html#config-deps) in `requirejs-config.js` file
 - or declare inline on the page via:
````html
<script type="text/x-magento-init">
{
  "*": {
    "nprogress": {}
  }
}
</script>
````
E.g.:
[Customer/ ... /customer.phtml](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/view/frontend/templates/account/customer.phtml#L28)
[Catalog/ ... /options.phtml](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/templates/product/view/options.phtml#L14)

> 2) in `layout/default.xml` I have `requirejs.org/docs/errors.html#mismatch`

Because `nprogress,js` itself is an [UMD module](https://github.com/umdjs/umd). When it appear on the page he tries _to be an AMD_ and executes via RequireJS. RequireJS forbids and explain you why: [http://requirejs.org/docs/errors.html#mismatch](http://requirejs.org/docs/errors.html#mismatch).

**Comment by vpelipenko** [comment]
@hackin88, did you find suggestions provided by @guz-anton useful?

**Comment by hackin88** [comment]
Hello

I could load the javascript informing the jQuery dependence

Thank you

**Comment by kapil-infobeans** [comment]
Hi @hackin88 ,

You can add jQuery or other dependency like below code, using shim configuration in **requirejs-config.js** file, and then you can initialize it on your element using below syntax.

```
var config = {
   "map": {
       "*": {
           'nprogress' : 'Your_Module/js/nprogress'
        }
   },
   shim: {
    'nprogress': {
        deps: ['jquery']
    }
   }
};
```

Use on html element using below syntax.

```
<div data-mage-init='{"nprogress":{}}'></div>

```
I hope it helps.
