### ISSUE TITLE
Magento 2.2 Encoding Issue -> Google Analytics

### ISSUE THREAD

**Issue by danielpfarmer** [magento/magento2#13350]
With the Magento 2.2 update we are now seeing incorrect data in Google Analytics. 

### Steps to reproduce
1. Complete a sale on Magento 2.2
2. View Sale in Google Analytics
3. Observe the Product Titles are incorrect

### Expected result
1. The product titles are transferred from Magento correctly

### Actual result
1. The product titles are incorrect

![image](https://user-images.githubusercontent.com/29124855/35334513-96381162-010a-11e8-932e-8d0212dffaf7.png)

### Potential Fix 
This has been introduced in Magento 2.2 with changes to the Magento\Framework\Escaper

In the file Magento\GoogleAnalytics\Block\Ga

Replace all instances of 

`escapeJs`

with

`escapeJsQuote`

After making this change the data coming into GA is now correct for our store.

**Comment by ihor-sviziev** [comment]
@danielpfarmer if you have fix for this issue - could you create Pull Request with the fix?

**Comment by thangtd** [comment]
#MALU18

**Comment by danielpfarmer** [comment]
I believe this is part of a bigger encoding issue with Magento 2.2. I'm not sure what the motivations were to changing this in this release, but it is also effecting the opengraph data:

![image](https://user-images.githubusercontent.com/29124855/36539443-c1d62e8c-17ce-11e8-9628-26a5fb77cebf.png)

**Comment by ArjenMiedema** [comment]
Keep in mind that if you change it back you do encode quotes. In Magento 2.1 it was an issue that when you entered a name containing double quotes, you got a JavaScript error for the staticImpressions (Google Tag Manager).

**Comment by magento-engcom-team** [comment]
Hi @danielpfarmer. Thank you for your report. 
The issue has been fixed in magento/magento2#13844 by @julienanquetil in 2.2-develop branch
Related commit(s):
 - [5843e815a57a514226ec5d2104afb4b2d4fea726](https://github.com/magento/magento2/commit/5843e815a57a514226ec5d2104afb4b2d4fea726)
 - [0d5197f8619b34dce648e554b7c317faeb56ca15](https://github.com/magento/magento2/commit/0d5197f8619b34dce648e554b7c317faeb56ca15)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @danielpfarmer. Thank you for your report. 
The issue has been fixed in magento/magento2#13907 by @julienanquetil in 2.3-develop branch
Related commit(s):
 - [c09c8d5c164a6ed2fb05c591d0a060f5a68e56cf](https://github.com/magento/magento2/commit/c09c8d5c164a6ed2fb05c591d0a060f5a68e56cf)

The fix will be available with the upcoming 2.3.0 release.
