### ISSUE TITLE
[Improvement] Add HTML attributes to containers

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#13354]
Hello,

This is not an issue but an improvement. It would be nice to add HTML attributes to `containers` to layout files.

For example, if I want to create the following HTML output with a container:

```
<header class="header" id="header" data-sticky data-isheader="true">

</header>
```

I can specify tag, id and class but not the other attributes.

What do you think about it?

**Comment by VincentMarmiesse** [comment]
PR #13355 created, I'm open to discussion!

**Comment by magento-engcom-team** [comment]
@VincentMarmiesse, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hi @VincentMarmiesse. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/85
