### ISSUE TITLE
Widget Sort Orders.

### ISSUE THREAD

**Issue by JamesAnelay** [magento/magento2#1335]
There is a bug/issue with widget sort orders which means if you have widget widget updates for the 'default' handle and another a specific handle e.g cms pages it is impossible to have your cms_page update block show above the default handles update block.

This is because DB layout updates are pulled in per handle sorted and then the next handle is pulled in this means you can only sort widget updates on a per handle basis.

A fix would be to pull the updates from the database using all current handles using IN($handlesArray) in the select statment. e.g for Magento1 https://github.com/JamesAnelay/WidgetSortOrders

**Comment by MaxSavich** [comment]
Hello James!

If you want to have this fix ASAP feel free to submit the pull request.

Thanks,

**Comment by dimasch** [comment]
Hey guys!
It's bug, because sort order for wigdets is not apply after change.

**Comment by pboisvert** [comment]
Olena--can you have the team evaluate the suggestion?

**Comment by tkacheva** [comment]
we will look in the scope of MAGETWO-54474

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Widget-Sort-Orders/idi-p/46576).

**Comment by JamesAnelay** [comment]
The way your handling issues here is total B.S.

**Comment by slavvka** [comment]
Hi @JamesAnelay. Thank you for your report. 
The issue has been fixed in magento/magento2#28219 by @Nazar65 in 2.4.0-develop branch
Related commit(s):
 - [660eb755b8dcabac7e3ad093386923fa470f41de](https://github.com/magento/magento2/commit/660eb755b8dcabac7e3ad093386923fa470f41de)
 - [f434c972eea54f916a9b44e3051b94e094a46253](https://github.com/magento/magento2/commit/f434c972eea54f916a9b44e3051b94e094a46253)
 - [f9059636275a08071390023940aa749b7e970c31](https://github.com/magento/magento2/commit/f9059636275a08071390023940aa749b7e970c31)
 - [bd6853f82acb26bd573d9cc3968b412deb4225ed](https://github.com/magento/magento2/commit/bd6853f82acb26bd573d9cc3968b412deb4225ed)
 - [d811f9aa8ef477736c0f21d54ba805d69b07d757](https://github.com/magento/magento2/commit/d811f9aa8ef477736c0f21d54ba805d69b07d757)
 - [b4fe70c4f25894fa908e64c53e62ced2066896b1](https://github.com/magento/magento2/commit/b4fe70c4f25894fa908e64c53e62ced2066896b1)
 - [e8e654fccbeee3cf766e55bb65870f25a21007aa](https://github.com/magento/magento2/commit/e8e654fccbeee3cf766e55bb65870f25a21007aa)
 - [65b11c3cfac463a1c16cd051d8bc77614526bd23](https://github.com/magento/magento2/commit/65b11c3cfac463a1c16cd051d8bc77614526bd23)
 - [eab0af933f60ccfea09ac4f138325bd73f31bc36](https://github.com/magento/magento2/commit/eab0af933f60ccfea09ac4f138325bd73f31bc36)
 - [817ec4f9da7ae08cf5ae1e3baa70173d5c8bc5f7](https://github.com/magento/magento2/commit/817ec4f9da7ae08cf5ae1e3baa70173d5c8bc5f7)
 - [597a58e5dcd164968412c8d655654579c216a278](https://github.com/magento/magento2/commit/597a58e5dcd164968412c8d655654579c216a278)
 - [93f2144d821be8a3723836c7a50ebeda4f3145ac](https://github.com/magento/magento2/commit/93f2144d821be8a3723836c7a50ebeda4f3145ac)
 - [5e365a0f8d888cf17f96d1724a4013c99785460c](https://github.com/magento/magento2/commit/5e365a0f8d888cf17f96d1724a4013c99785460c)
 - [234086000be2efad27ffd8327ac23fbec81ba420](https://github.com/magento/magento2/commit/234086000be2efad27ffd8327ac23fbec81ba420)

The fix will be available with the upcoming 2.4.0 release.

**Comment by JamesAnelay** [comment]
Thanks for taking the time to update us here @slavvka :)

**Comment by Nazar65** [comment]
Actually this is wrong issue number, the same number but in adobe-stock repository :)

**Comment by ihor-sviziev** [comment]
Closing this issue again, as it was moved to the forums
