### ISSUE TITLE
Product's 'is in stock' method erroneous

### ISSUE THREAD

**Issue by mustdobetter** [magento/magento2#13362]
### Preconditions

Magento 2.1.*, 2.2.*

### Steps to reproduce

Call the isInStock()  method on a product model.

### Expected result

Magento should return a value that is indicative of whether the product is actually in stock i.e. whether it has a positive stock level - dependent on the configuration defined in the admin.

### Actual result

Magento is seemingly returning boolean true if the product is enabled, using the product's status flag. This is clearly not sufficient when attempting to determine whether the product is in stock or not - stock is not taken into account at all here. At best its highly confusing and misleading, at worst it's just plan wrong.

**Comment by magento-engcom-team** [comment]
@mustdobetter , Thank you for your report. This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this. Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@mustdobetter, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
