### ISSUE TITLE
MiniCart error in console. Blank product section in dialog box

### ISSUE THREAD

**Issue by slunnon12** [magento/magento2#13389]
### Preconditions

1. PHP 7.0.27 
2. MySql 5.7.21
3. CentOs 6.9
4. Apache 2.2
5. Magento 2.1.11

### Steps to reproduce

1. Add Any product to cart (I am using a custom theme and have created Magento_Checkout directory in theme folder) 
2. Product seems to have been added to cart i.e. Green success message appears informing the user.
3. 

### Expected result

1. The product is added to cart and information is shown in the minicart including little picture, product title, price. Also, a  grand total is also shown.

### Actual result

1. ![minicart-error](https://user-images.githubusercontent.com/7900386/35442357-e3331ac6-029e-11e8-8020-683fc1b1b8b0.JPG)
2. ![minicart-error console log](https://user-images.githubusercontent.com/7900386/35442413-1ed9b102-029f-11e8-8d08-9816942ee722.JPG)

Any help would be appreciated.

**Comment by magento-engcom-team** [comment]
@slunnon12 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation and default theme(luma or blank).

**Comment by slunnon12** [comment]
Would it help if I gave you access to the site? Its a development site and would need adding to local hosts file

**Comment by magento-engcom-team** [comment]
@slunnon12 , seems this issue is not reproduced on clean installiation and default themes, if it is true and you need help please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by slunnon12** [comment]
Ok thank you.

**Comment by magento-engcom-team** [comment]
@slunnon12, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
