### ISSUE TITLE
Incorrect work of Magento\Sales\Cron\CleanExpiredQuotes::setExpireQuotesAdditionalFilterFields()

### ISSUE THREAD

**Issue by mazur-vlad** [magento/magento2#13381]
### Preconditions

1. Magento version 2.1.7
2. PHP 7.0.26

### Steps to reproduce

1. Write before plugin for \Magento\Sales\Cron\CleanExpiredQuotes
3. Write another before plugin from another module for \Magento\Sales\Cron\CleanExpiredQuotes
3. In both plugins call setExpireQuotesAdditionalFilterFields and set different arrays

### Expected result

1. Both rules will be included

### Actual result

1. Works only one rule

**Comment by magento-engcom-team** [comment]
@mazur-vlad, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @mazur-vlad thank you for your report, in both plugins this method calls as expected. this is non issue
