### ISSUE TITLE
Maybe just a wish because in Germany / is a valid punctuation mark

### ISSUE THREAD

**Issue by ulicodex** [magento/magento2#13384]
### Preconditions
1. Magento 2.1.10

### Steps to reproduce
1. Export data with a Category like "Ladestecker /-dosen" which is valid punctuation in Germany.
2. Try to parse this somehow

### Expected result
1. No problems should occur

### Actual result
1. Magento exports category paths with / so that "Ladestecker /-dosen" will get two categories.

**Comment by ulicodex** [comment]
Commas as delimiter is as well a bad choice for every language where there are commas allowed. Without core hacking, every product export from Magento backend is useless crap.

**Comment by magento-engcom-team** [comment]
@ulicodex, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @ulicodex The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
