### ISSUE TITLE
Magento Framework?

### ISSUE THREAD

**Issue by sakiss** [magento/magento2#1340]
I would love to be engaged with magento 2 modules/extensions and generally with development.

I cannot find a lot of resources so my question is if Magento 2 is built over an existing framework or if i can use a framework of my choice?
I can see Zend and Symfony are bundled but i have no idea how these can be used. Any guidance would be great

**Comment by choukalos** [comment]
Hi @sakiss,

We view Magento as it's own framework.  As such we use various libraries to help us accelerate development.  In generally we have Magento specific framework interfaces that abstract away a direct reference to those libraries.  So think instead of Magento as it's own framework.  To help, please understand that we're really an enterprise java app that just happens to be written in PHP ( so there's a couple design patterns we use; also why we're all XML happy ).  With that in mind go check out our developer hub, and some of the Magento 2 deep dive presentations from this year's Imagine.  I think that'll help get you started.  I also recommend you take our Magento 2 training course ( paid ) as a way to accelerate your learning curve.

We'd love to hear your feedback on ways we can make it easier to learn about and start becoming productive on Magento 2.  Also any ways we can improve your ability to easily create the crazy customizations that Magento is famous for.

Resources:
http://magento.com/developers/magento2
http://imagine2015.magento.com/agenda - Day 1 Magento 2 deep dive session videos
http://devdocs.magento.com
http://magento.com/training/about

-Chuck

**Comment by Mackovey** [comment]
>> To help, please understand that we're really an enterprise java app that just happens to be written in PHP.

Did The First Magento Team before starting develop Magento use Java EE and none-MySql database?

**Comment by choukalos** [comment]
Yes the original Magento development team had Java experience and was familiar with other databases at that time.  When Magento launched in 2007 it was conceived as an easy to distribute enterprise e-commerce platform.  The platform was architected as an enterprise platform and uses several common design patterns along with extensive use of XML for easy configuration.  PHP was chosen because it was very easy to deploy at the time ( just unzip into your web server's root and then install ).  

I'm hoping one of the old timers (cough - @piotrekkaminski or Ben Marks or Roy ) write a tell all book; I think it would be a fun read.
