### ISSUE TITLE
No such entity error when saving product in single-store mode if website_id <> 1

### ISSUE THREAD

**Issue by kyegil** [magento/magento2#13405]
After upgrading to Magento 2.2.1 I'm no longer able to save products while the website is in single store mode. The website has previously had multiple store views.
I've been able to replicate the issue on a clean install of Magento 2.2.2
The problem is likely related to the fact that website_id != 1

### Preconditions
* Magento version 2.2.1 or 2.2.2
* PHP version 7.0.22
* Mysql version 5.6.35
* Apache/2.2.32 (Unix)

### Steps to reproduce
1. Install a clean version of Magento version 2.2.2
2. Add a new website, store and store view, and make this the default
3. Delete the preinstalled website, store and store view
4. Add a new product and save it
5. Change the configurations to single-store mode
6. Open the product and save it again

### Expected result
1. The product should save successfully

### Actual result
1. The save action fails, with the message 'No such entity.'

![image](https://user-images.githubusercontent.com/26584237/35488541-bd209eb8-0482-11e8-94ec-9d38eea3781a.png)
![image](https://user-images.githubusercontent.com/26584237/35488616-41cbdf2e-0483-11e8-80e5-472658102ba1.png)

**Comment by magento-engcom-team** [comment]
@kyegil, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ComputerNorth** [comment]
I had the same problem. When I disabled the single-store mode, I could save successfully.

**Comment by Techiescot** [comment]
This is the same error as I have ... But the single store mode makes no difference to me.

**Comment by kyegil** [comment]
While waiting for a bug fix I solved this issue by making the following change to the core Product model (in the hope that this will be fixed by next time I update Magento):

In the Magento\Catalog\Model\Product::getStoreIds() method
(approx line 792 of vendor/magento/module-catalog/Model/Product.php):

Find
`                foreach ($websiteIds as $websiteId) {
`
Replace with
`                foreach ($websiteIds as $websiteId => $selected) {
`

**Comment by sidolov** [comment]
Hi @kyegil. Thank you for your report. 
The issue has been fixed in magento/magento2#18001 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [baf17113eb4366bae2ca0df5b74b5d13c9ad06a9](https://github.com/magento/magento2/commit/baf17113eb4366bae2ca0df5b74b5d13c9ad06a9)
 - [23f3c5bb948101e4c82e354d42b344933474a307](https://github.com/magento/magento2/commit/23f3c5bb948101e4c82e354d42b344933474a307)
 - [03ea646c2eb481f4b74c98992e263de23843d11c](https://github.com/magento/magento2/commit/03ea646c2eb481f4b74c98992e263de23843d11c)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @kyegil. Thank you for your report. 
The issue has been fixed in magento/magento2#18210 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [765f88f0359dbd689a2b662f3c5a76f91a839e52](https://github.com/magento/magento2/commit/765f88f0359dbd689a2b662f3c5a76f91a839e52)
 - [558d5279f200d4e9753aae715f2d7f4f44a0d5c4](https://github.com/magento/magento2/commit/558d5279f200d4e9753aae715f2d7f4f44a0d5c4)
 - [deebbc08e59a7eec5b6c5b3a013291330a194126](https://github.com/magento/magento2/commit/deebbc08e59a7eec5b6c5b3a013291330a194126)
 - [ae2917c58c836a80da13659f50d251de83efadd2](https://github.com/magento/magento2/commit/ae2917c58c836a80da13659f50d251de83efadd2)
 - [e068783fef14108cafe169f1639f7e3875875bc4](https://github.com/magento/magento2/commit/e068783fef14108cafe169f1639f7e3875875bc4)
 - [7cd36de951ca85bdeab03df32aea0d36e066c49e](https://github.com/magento/magento2/commit/7cd36de951ca85bdeab03df32aea0d36e066c49e)
 - [0e7f7792950225d26bda094fa9e667e9a3833a83](https://github.com/magento/magento2/commit/0e7f7792950225d26bda094fa9e667e9a3833a83)
 - [1133391adc707f493b4d230788b14bc70673b36c](https://github.com/magento/magento2/commit/1133391adc707f493b4d230788b14bc70673b36c)

The fix will be available with the upcoming 2.3.1 release.
