### ISSUE TITLE
Date range filter in admin ui grid displaying "Invalid date" after reload

### ISSUE THREAD

**Issue by perryholden** [magento/magento2#13428]
### Preconditions
1. Magento 2.2.1
2. PHP 7.0.26
3. MySQL 5.6.38-83.0

### Steps to reproduce
1. Create a new sales order, if there are no sales orders already
2. Go to the orders admin grid
3. Filter the grid by "Order Date"
4. After the grid has been filtered by the date range, reload/refresh the page

### Expected result
1. Date range is properly displayed in the "Active filters" area

### Actual result
1. Date range is displayed improperly, including an "Invalid date" message

<hr>

![Admin Grid](https://files.classyllama.com/7432c533/Image_2018-01-30_12-37-01.png)

### Additional note

1. This happens on any admin grid that uses a date range for filtering, not only the sales order grid

**Comment by magento-engcom-team** [comment]
@dewayneholden, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by vadimulyanov** [comment]
Code with wrong date formating is started here:
vendor/magento/module-ui/view/base/web/js/form/element/date.js:120

```
dateFormat = this.shiftedValue() ? this.outputDateFormat : this.inputDateFormat;

shiftedValue = moment(value, dateFormat);
```
The code not checks the format of input value.
Date value may be come from js layout with format `m/d/y` (for example, from filter js layout - 04/10/2018), but in `this.inputDateFormat` may be set by other checking format, for example `YYYY-MM-DD`, which breaks the value after moment method.

Code needs have some additional checking of input value format, something like this, for example, my fast fix:
```
dateFormat = (
    this.shiftedValue()
    || (new RegExp( "(" + this.outputDateFormat.replace(/[dmy]+/gi, '[\\d]+') + ")" ).test(value)) // value may be already in output format
) ? this.outputDateFormat : this.inputDateFormat;
```
or some simple other

**Comment by afavata** [comment]
any news on this

**Comment by vishal-7037** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@vishal-7037 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by pareshpansuriya** [comment]
#mm19in

**Comment by magento-engcom-team** [comment]
Hi @pareshpansuriya. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by nntoan** [comment]
Any updates?

**Comment by geet07** [comment]
I am working on this, but how can I self-assign this issue. @magento-engcom-team

**Comment by nntoan** [comment]
@geet07 Try to use a hashtag to get the invitation from the GitHub bot. E.g `#mm19in` then you can self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @pwaszkis. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by geet07** [comment]
#mm19in

**Comment by sashas777** [comment]
@geet07 
any luck wit hthe issue?
