### ISSUE TITLE
Customer login not working in chrome & Edge browser but proper working in Firefox browser in Magento 2.2.2

### ISSUE THREAD

**Issue by RahulBhut21** [magento/magento2#13423]
Customer/Client not login in chrome & Edge browser but proper working in firefox browser
Admin login work in Both Browser Properly Chrome & Firefox But admin login page does not load in Edge Browser
**Preconditions**
1.Magento 2.2.2 without sample data is installed. 
2.WAMP on Windows OS.
3.PHP 7.1.9, MySQL 5.7.
4.Already User is created using firefox browser.
5.No error in Consol as well as Networking Tab.

**Steps to reproduce**
1.Start WAMP Server.
2.Type URL "localhost/Magento".
3.Click on "Sign In" Link place at right side of home page
4. Redirect to Sign In Page.Enter User Email ID and Password (1st Time)
5. Not Login Replay "* filed is required".
6. 2nd Time login same Replay. Reload Sign In Page
7.Now come captcha as 3rd input filed. Enter login detail  with valid captcha code
8.But not login. And "Incorrect CAPTCHA" message dispaly.
9.Same process continues running

**Expected result**
1. Customer should log in and display name on right side

**Actual result**
1.Not Login And stay on Login page
![image](https://user-images.githubusercontent.com/31387311/35559481-d69f7dd8-05d0-11e8-9e42-c0733625a53c.png)

**Comment by miguelbalparda** [comment]
There are high chances this is caused by the domain you are using (localhost). Can you change it to something [valid](https://tools.ietf.org/html/rfc1035) and report back? localtest.com should do the trick for testing.

**Comment by magento-engcom-team** [comment]
Hello @RahulBhut21. Thanks for reporting. In addition to what miguelbalparda said You also ought to know that Windows OS is not the one Magento 2 supports (though Magento 1 did it). You can see it in documentation: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html. So if You can reproduce this issue on Linux, please report it again.

**Comment by magento-engcom-team** [comment]
@RahulBhut21, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by RahulBhut21** [comment]
@miguelbalparda how I can update url in magento (client url and admin url)

**Comment by miguelbalparda** [comment]
You should be able to do that from the admin or from the [CLI](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-store.html).

**Comment by orlangur** [comment]
Hi @RahulBhut21,

> Admin login work in Both Browser Properly Chrome & Firefox But admin login page does not load in Edge Browser

This issue is not related to Magento but to the way browsers following (or not) specifications on how cookies should be handled for `localhost` domain: https://stackoverflow.com/a/1188145

Always use appropriate domain aliases and as mentioned by other participants, WAMP is not a right choice for Magento dev environment even if it works in some cases.
