### ISSUE TITLE
[2.1.11] Add to cart, try to checkout, cart is empty but mini-cart has items.

### ISSUE THREAD

**Issue by aeu** [magento/magento2#13427]
### Issue
We have been getting reports from users saying that they added product to cart, tried to checkout, but when they go to the cart, the cart was empty, but the mini-cart still showed products.

We have been getting customer complaints about this issue in every release of Magento 2 we have used since October, up to and including our current implementation which is 2.1.11.

This has obviously been a nightmare to debug, but we have figured out how to reproduce it 100%, in Luma.

### Preconditions
Dedicated server,
Magento 2.1.11.
CentOS 7.3.
PHP 7.
MariaDB.
Double Redis (session and cache).
Images on a CDN.

### Steps to reproduce

1. Add product to cart
2. Click on cart
3. Click on checkout button multiple times **before the checkout page has loaded**.  At least two clicks are necessary.
4. You will now be on a cart page page that says your cart is empty but your minicart will still have content.

### Actual result
The user will be directed to a cart page saying there are no items in the cart, but the mini-cart will still have contents.

### Expected result
The cart should have items in it.

### Misc
I believe that this is probably related to the "Hit refresh multiple times fast in checkout and your cart will be empty" bug **edit** which can be referenced here - https://github.com/magento/magento2/issues/12362

### Fix
We added some client-side code to disable the "checkout" button after it was clicked, which solves this issue.  This obviously does not resolve the fundamental problem (double refresh on checkout page clears cart) but it should be done anyway if for no other reason than to reduce server load.  We can create a pull request for this if needed.

![screen shot 2018-01-25 at 9 56 10 pm](https://user-images.githubusercontent.com/2225377/35577216-fc505bb4-05ae-11e8-97e8-ef1e7b432aa2.png)

**Comment by magento-engcom-team** [comment]
@aeu, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by wenpingguo** [comment]
I can reproduce this in Magento 2.2 too.
see video record https://monosnap.com/file/3nG4CTflRD4qD6QusZAeskxRKzybEj

**Comment by elioermini** [comment]
We are having the same issues on 2.1.11 Commerce with Redis for session storage.

**Comment by ashleyemma** [comment]
I am using Magento 2.2.2 and have this issue also, is there any update on this?

**Comment by bilabong** [comment]
Try to disable the FPC cache i have the same issue i think the checkout page has been cached when it was empty

**Comment by allisonlawrencels** [comment]
What is the status on this issue? We see it also and it is a huge issue for an ecommerce platform.

**Comment by elioermini** [comment]
@bilabong @allisonlawrencels I've been told today by the support team that is fixed in 2.2.2 we haven't tested that yet please try on a staging environment.

**Comment by elioermini** [comment]
We are on 2.1.12 with composer so we temporarily (till we will find an official fix for 2.1.x) replaced \Magento\Framework\Session\SessionManager of Magento 2.1.10 https://github.com/magento/magento2/blob/2.1.10/lib/internal/Magento/Framework/Session/SessionManager.php which hasn't such issues by placing it one folder Lib/Framework/Session of our module.
We did the override in the main composer.json of the project inside the "autoload" node:

```
"psr-4": {
      "Magento\\Framework\\Session\\": "vendor/yourvendor/yourmodule/Lib/Framework/Session"
    }
```

```
"exclude-from-classmap": [
      "vendor/magento/framework/Session/SessionManager.php"
    ],

```

That is solving for now. 

Otherwise a simpler fix without composer can be by placing the same SessionManager of 2.1.10 in your own lib/internal/Magento/Session folder

**Comment by allisonlawrencels** [comment]
@elioermini For what it's worth, I did not have luck with reverting the core code. I believe it is related to using PHP 7 - the fix I eventually was successful with is here: https://github.com/magento/magento2/issues/12362#issuecomment-346301084

Looking at the 2.2.3-develop branch, it seems that the Magento team is trying out the reverting solution as well, but I don't think that is going to be the solution here.

As someone pointed out in the linked thread, it would be nice to know specifically what risk Magento is trying to mitigate with the regenerate_session_id() call when going to checkout, as it is tempting to just remove that line altogether.

**Comment by aeu** [comment]
@allisonlawrencels Thanks for linking that other issue, that was a very interesting read.  We are experiencing the exact same thing described in that thread - if you go to checkout, hit refresh a few times quickly and then the cart is empty.

I'll take a look at the solution that acetronaut posted and see if we can get that working here, we are currently on 2.1.12.

**Comment by elioermini** [comment]
@allisonlawrencels exactly see my comment in #12362 we found out as well after a while the same fix you referenced but I forgot to amend it here. It is also solving this issue #4301 the only change in addition to #12362#issuecomment-373318974 I added in `start()` is `$this->renewCookie($sid);` after `$this->validator->validate($this);`

**Comment by ishakhsuvarov** [comment]
@aeu This issue duplicates https://github.com/magento/magento2/issues/12362
Closing. Please continue further tracking and discussion in mentioned ticket.
Thank you.

**Comment by magento-engcom-team** [comment]
Hi @aeu. Thank you for your report. 
The issue has been fixed in magento/magento2#14428 by @adrian-martinez-interactiv4 in 2.2-develop branch
Related commit(s):
 - [dc687c6730ad87189e86867a30e5349388a10777](https://github.com/magento/magento2/commit/dc687c6730ad87189e86867a30e5349388a10777)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @aeu. Thank you for your report. 
The issue has been fixed in magento/magento2#14429 by @adrian-martinez-interactiv4 in 2.3-develop branch
Related commit(s):
 - [f82a17507acfa821e2bea543a99f072e1de1252f](https://github.com/magento/magento2/commit/f82a17507acfa821e2bea543a99f072e1de1252f)
 - [4d23b8b3c64e4e0276c0f562ceba36f2c5688e4d](https://github.com/magento/magento2/commit/4d23b8b3c64e4e0276c0f562ceba36f2c5688e4d)

The fix will be available with the upcoming 2.3.0 release.

**Comment by aeu** [comment]
I see that this is fixed in 2.3.x and 2.2.x, is there any chance of a fix in the next 2.1.x update as well?

**Comment by nmallepally** [comment]
same issue on 2.1.12, cart is empty.
only happens on simple products for me on quick reload, is there any quick fix to this issue for 2.1.12 version ?

**Comment by nmallepally** [comment]
same issue on 2.1.12, cart is empty.
It happens when people clicked twice on the checkout button and the cart is empty but mini cart has items.

**Comment by apedicdev** [comment]
I'm on 2.2.6 and I can still replicate the issue.

**Comment by anthonynewman** [comment]
Replicated on 2.2.4
