### ISSUE TITLE
maintenance.enable is different from php bin/magento maintenance:enable

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#13444]
Hello,

According to [the documentation](http://devdocs.magento.com/guides/v2.2/comp-mgr/trouble/cman/maint-mode.html), we should create a `maintenance.html` to customize the maintenance page.
Then we have to `touch maintenance.enable` in root directory to enable maintenance.

Everything works but when I launch the `php bin/magento maintenance:enable` command, I don't have the same behavior because a `.maintenance.flag` file is created in `var` folder.

Also, `php bin/magento maintenance:allow-ips` does not work with the `maintenance.enable` file method because we have to allow IP from web server directly.

### Preconditions
1. Magento 2.2.2

### Steps to reproduce
1. Create a `maintenance.html` file in Magento root directory
2. Update the web server configuration as described in [the documentation](http://devdocs.magento.com/guides/v2.2/comp-mgr/trouble/cman/maint-mode.html)
3. Launch command `php bin/magento maintenance:enable`

### Expected result
1. You should be redirected to `maintenance.html`

### Actual result
1. Default Magento maintenance screen is displayed

**Comment by magento-engcom-team** [comment]
@username, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only. 
You don't have to use CLI commands if you have created maintenance.html and have configured Apache according to the documentation. There are different methods to set your Magento website in maintenance mode.
We recommend you to choose either methods "Apache method" or "Magento CLI method". If you chose "Apache method", enable maintenance mode using the command "touch maintenance.enable" otherwise "rm maintenance.enable" (deletes the file).  In case you chose "Magento CLI method" pub/errors/default/503.phtml will be used to show the page with a message about maintenance.

**Comment by magento-engcom-team** [comment]
@VincentMarmiesse, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
