### ISSUE TITLE
Product Table in Backend loads forever

### ISSUE THREAD

**Issue by thomas-villagers** [magento/magento2#13459]
### Preconditions

1. ver. 2.2.2
2. 

### Steps to reproduce

1. make a full backup of a store with sample data
2. reinstall backup 
3. 

### Expected result

1. when opening catalog / products in backend, the product listing should be showing

### Actual result

1. Magento hangs forever:
[Screenshot, logs]
![bildschirmfoto von 2018-02-01 13-35-34](https://user-images.githubusercontent.com/1818737/35678755-d0064670-0754-11e8-8a7f-34c5fe04bc5e.png)

The frontend is OK, all products are available. 

Any idea how to debug this? 
Thank you!

**Comment by thomas-villagers** [comment]
![bildschirmfoto von 2018-02-01 14-31-14](https://user-images.githubusercontent.com/1818737/35681075-96a86df6-075c-11e8-99a6-54b093c44ed3.png)

So this might be a apache2 related problem ... my version is

Server version: Apache/2.4.18 (Ubuntu)

In sites-enabled/000-default.conf I have:

`<Directory "/var/www/html">
  Options Indexes FollowSymLinks MultiViews
  AllowOverride All
  Require all granted
</Directory>
`

hm ...

**Comment by thomas-villagers** [comment]
OK, I think I fixed it ... had to reinstall magento.

**Comment by magento-engcom-team** [comment]
@thomas-villagers, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
