### ISSUE TITLE
Fix recursive dependencies?

### ISSUE THREAD

**Issue by tobi-pb** [magento/magento2#1345]
Hello Magento-Team,

I would like to Mirror all external libs so I never got a problem when some external server is gone.

So I decided to use Satis:

```
{
   "require" : {
    "magento/product-community-edition" : ">=0.74.0-beta12"
   },
   "require-dependencies": true,
   "archive": {
        "directory": "dist",
    "skip-dev": true
    },
   "name": "Magento2 Clone",
   "description": "informaton.",
   "repositories": [
      { "type": "composer", "url": "https://packages.magento.com" },
      { "type": "composer", "url": "http://packagist.org/" }
   ]
}
```

Running `./satis/bin/satis build external.json ../htdocs/packages/external` just clones magento2/product-community-edition instead off all magento2 stuff.

Problem is that magento/product-community-edition exists in packagist.org and in packages.magento.com with different dependencies. Would be great if you could rename one package :)

To look closer:
https://packagist.org/packages/magento/product-community-edition depends on magento/product-community-edition (itself?). Dependecies of magento/product-community-edition changes when I add packages.magento.com as repository. 

Thanks a lot,

Tobi

**Comment by buskamuza** [comment]
@tobi-pb , thanks for reporting. We have an internal ticket to clean up packagist.org from outdated packages MAGETWO-37853, so it should solve your issue when will be done.

**Comment by alankent** [comment]
Side question - just after your opinion (and anyone else listening). How serious is the problem you are trying to solve?  Do you think Magento should be adding a copy of all 3rd party libraries we depend on to our repo as well?  Feels "wrong", but I understand the dependence on availability. Should we mirror those libraries for reliability?

My gut feeling is no, because you don't need to run composer every day when on projects. Or do people run composer more frequently that I expect to get new versions of local modules etc?

**Comment by Vinai** [comment]
Since the recent github outages I see it is becoming common practice to use [toran proxy](https://toranproxy.com/) for mirroring required composer packages.
Personally I think using toran (or another proxy) is a better solution then Magento copying all requirements into the repository, which would not only put the burden of keeping them in sync on the product team, but also remove a lot of the flexibility composer offers.

**Comment by tobi-pb** [comment]
Hi @alankent,

I don't how serious it is but is feels bad when my deployment strategy depends on magentos hosting strategy :)

@Vinai Easiest way to mirror all depending packages is using satis. just add your main requirement, activate archive function and satis does the job :)

When magento solves double naming problem my example above should mirror all depending packages from packagist and packages.magento.com automatticly. 

Greetings,

Tobi

**Comment by ghost** [comment]
This is a non issue. Please remove this bug. If someone wants to mirror it let them mirror it and maintain it. Why is this on github? It doesnt help improving this codebase at all.

**Comment by choukalos** [comment]
Assigning Piotr to evaluate from a dev experience perspective.

**Comment by magento-engcom-team** [comment]
magento/product-community-edition is a deprecated repository and we are not supporting packagist any more. Closing this issue as not relevant
