### ISSUE TITLE
Not able to add any Reviews/Ratings

### ISSUE THREAD

**Issue by Tonzr** [magento/magento2#13473]
### Preconditions
Magento CE ver. 2.2.2

### Steps to reproduce
Good question. When I installed my Magento it was in ver 2.1.7 and then i could disable the review option from the dashboard and since I've updated up to ver. 2.2.2 but now i would like to add ratings so I went to the terminal to see module:status and it seems to be enabled but it is not working.

When i go to stores->attributes->rating the page is empty and when i open just some random product and go to Product Reviews i get "Attention Something went wrong" and get an error in the consol 
`/mui/index/render/key/c711c99c7ee1cc7aae396d2d0b920ba71adf452e3c645923ad35e20fa7c6b317/?namespace=review_listing&isAjax=true 500 ()`

### Expected result
Being able to add reviews/ratings

### Actual result
Not being able to add any reviews/ratings

**Comment by magento-engcom-team** [comment]
@Tonzr, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Tonzr** [comment]
Is there an "hot-fix" available for this problem? Would appreciate it if i could use this module again.

**Comment by jeroenschipper** [comment]
Hi @Tonzr,

I can reproduce this issue when i'm disabling module output in the way the [devdocs](https://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html) describe it on a clean magento2.2 installation. I think the best solution is to check your core_config_data table and to remove the row where the path contains "modules_disable_output" and "Magento_Review". Deleting the row will enable the module again when the cache is cleaned/flushed.

FYI: This was in developer mode. Not sure if you need to deploy when in production mode.

**Comment by dasharath-wagento** [comment]
I am working on this at #dmcdindia19

**Comment by engcom-Delta** [comment]
Hi @Tonzr 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
