### ISSUE TITLE
Custom source model cannot add own values to flat tables

### ISSUE THREAD

**Issue by botwebdev** [magento/magento2#13477]
I have a table with with multiple columns, 2 of which I wish to use for attribute values and labels so I have created my own Source Model which works fine.

I also want the value and label to be included in the  product flat tables so added implementations of getFlatColumns() and getFlatUpdateSelect().  The columns and the attribute value are added but the labels (in an <attribute>_value fields) are all NULL.

Magento\Catalog\Model\Indexer\Product\Flat\TableBuilder calls getFlatUpdateSelect() but then discards the result and recalculates the required select from the eav_attribute_option_value table. (lines 317 and below))

This means that there is no longer a way for custom source models to add additional columns to the flat tables and populate them with data.

### Preconditions
1. Magento 2.2.1 & 2.3

### Steps to reproduce
1. Add table with at least an id and label column 
2. Add a custom source model to provide attribute options
3. Implement getFlatColumns() and getFlatUpdateSelect() to create flat columns (attr and attr_value) and values
4. Add attribute to product, choose a value, save

### Expected result
1. atrr and attr_value columns should be added to product flat tables
2. values for attr and attr_value should be populated for this new product

### Actual result
1. Columns are added as expected
2. attr value is populated but attr_value is not

**Comment by magento-engcom-team** [comment]
Duplicate of #13751

**Comment by Swahjak** [comment]
@magento-engcom-team This is not a duplicate of #13751. It's about the `_value` fields not being populated due to `getFlatUpdateSelect` being completely ignored by the indexer. The only option to add a custom attribute is by using `eav_attribute_option_value` a custom backend is not possible. `Magento\Catalog\Model\Indexer\Product\Flat\Table\BuilderInterfaceFactory\TableBuilder::306` and beyond do not give any logic for implementing custom value retrieval.

This issue should be reopened.

**Comment by the-midi** [comment]
I can replicate this issue in 2.3.1 and can confirm it is not a duplicate of #13751 - therefore I am re-opening this issue.

I have created a brand attribute and have added brand and brand_value to the flat table columns. The brand column is being populated with the correct brand_id from the source, however the brand_value is incorrect as it is using the label found in eav_attribute_option_value for option_id = brand_id which is incorrect as the attribute_id for the option does not match.

We cannot use the `getFlatUpdateSelect` in the `Magento\Catalog\Model\Indexer\Product\Flat\Table\BuilderInterfaceFactory\TableBuilder` as it throws mysql error. This originates from `\Magento\Eav\Model\ResourceModel\Entity\Attribute\Option::getFlatUpdateSelect` which uses columns (`entity_id` and `entity_type_id`) that do not exist on the `catalog_product_entity_int` table.

Only current workaround is to ignore the brand_value as it is wrong and load the correct label when needed.

**Comment by ghost** [comment]
Hi @michaelwylde this issue has already fixed in 2.3-develop branch by this commit https://github.com/magento/magento2/commit/ae7179f7bee1b99597aee46da79f581a8a45a018 and will be available on 2.3.2 release.

**Comment by Swahjak** [comment]
@engcom-backlog-nazar I don't see how https://github.com/magento/magento2/commit/ae7179f7bee1b99597aee46da79f581a8a45a018 fixes the issue of not being able to use a custom source table. It's still selecting from `eav_attribute_option_value`.

**Comment by the-midi** [comment]
@engcom-backlog-nazar As mentioned by @Swahjak there is still the hardcoded tablename for eav_attribute_option_value which is the issue.

The actual select `$attribute->getFlatUpdateSelect($storeId) instanceof \Magento\Framework\DB\Select` is ignored and instead the code does its own link to the `eav_attribute_option_value` rather then using the select which we can change to use other tables for custom sources.

**Comment by engcom-Charlie** [comment]
Hello @botwebdev 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch 2.2-develop was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.
See Accepted pull requests and ported code for more details

If you still faced this issue on 2.3 please create a new Issue with all required details according to Issue reporting guidelines

Thanks for your report!

**Comment by Swahjak** [comment]
@engcom-Charlie @engcom-backlog-nazar  why close the issue? As stated in the comments this issue has not been resolved and if it is please give us a reference to the relevant commit. This issue is (as far as I'm aware of) still present in 2.3 so closing it because this was reported on 2.2 is short sighted.

The description seems pretty clear to me. At this point it seems that randomly closing issues without any reference or based on bad reasoning is how most issues end in this repo.

**Comment by Swahjak** [comment]
@michaelwylde since you seem to be able to re-open issues (and have re-opened this issue multiple times) would you be so kind te reopen this issue again. As you can see in https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Model/Indexer/Product/Flat/TableBuilder.php the method `getFlatUpdateSelect` still isn't doing anything to manipulate the actual query. Nothing has changed, no real attempt has been made to reproduce this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19796` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Swahjak** [comment]
FYI this commit made it even worse https://github.com/magento/magento2/commit/3e44f8c891d4398db8f94ecf421b39bdb953eed7#diff-56587e255646121ddf3a8b375569b579

**Comment by Swahjak** [comment]
@dhorytskyi not to bash, but you seem to have done some work that touches this issue.

**Comment by Swahjak** [comment]
:clap:  next level issue solving, just close the issue because it hasn't been fixed within a x period.

Since nobody has marked this as fixed I'm going to assume it hasn't been fixed.

**Comment by Swahjak** [comment]
Still not stale

**Comment by magento-engcom-team** [comment]
Hi @botwebdev. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24037` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by Swahjak** [comment]
@magento-engcom-team commit's or it didn't happen https://github.com/magento/magento2/search?q=MC-24037&type=commits

**Comment by Swahjak** [comment]
@magento-engcom-team on as side note; Why is stale bot still closing issues when I clearly responded to this not being stale?

**Comment by ahofstetter** [comment]
Still not fixed in 2.4.3 :/
