### ISSUE TITLE
Unable to activate logs after switching from production mode to developer 

### ISSUE THREAD

**Issue by VincentMarmiesse** [magento/magento2#13480]
Hello,

I can't enable logs in config (Stores > Configuration > Advanced > Developer > Debug > Log to file) because the select field is disabled.

![capture d ecran de 2018-02-02 20-14-36](https://user-images.githubusercontent.com/1949412/35750569-b8106b20-0855-11e8-970c-0cf4e36a001e.png)

### Preconditions
1. Magento 2.2.2
2. PHP 7.0.25

### Steps to reproduce
1. Switch to production mode
2. Switch to developer mode
3. Go to Stores > Configuration > Advanced > Developer > Debug

### Expected result
1. I should be able to enable Log to file

### Actual result
1. Log to file select field is disabled

**Comment by magento-engcom-team** [comment]
@VincentMarmiesse, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by VincentMarmiesse** [comment]
Hello,

Any news on this issue?

Thanks!

**Comment by jayankaghosh** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@jayankaghosh thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @VincentMarmiesse. Thank you for your report. 
The issue has been fixed in magento/magento2#15335 by @jayankaghosh in 2.2-develop branch
Related commit(s):
 - [540917e54db5490f411beb6cbbe8715502de5b1a](https://github.com/magento/magento2/commit/540917e54db5490f411beb6cbbe8715502de5b1a)
 - [c6aabf8f6b88b9b54a5022eb2163718af270b7a8](https://github.com/magento/magento2/commit/c6aabf8f6b88b9b54a5022eb2163718af270b7a8)

The fix will be available with the upcoming 2.2.7 release.

**Comment by magento-engcom-team** [comment]
Hi @VincentMarmiesse. Thank you for your report. 
The issue has been fixed in magento/magento2#17477 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [ad610f674d5d37e781556686408c8bbaeb28c956](https://github.com/magento/magento2/commit/ad610f674d5d37e781556686408c8bbaeb28c956)
 - [e967eb984065348ad3df0db39d1fe287e9927d2b](https://github.com/magento/magento2/commit/e967eb984065348ad3df0db39d1fe287e9927d2b)

The fix will be available with the upcoming 2.3.0 release.
