### ISSUE TITLE
Install Quits on install on Magento_Catalog

### ISSUE THREAD

**Issue by Zaylril** [magento/magento2#1350]
Hey,

Whilst installing Magento 2 using the magento setup:install command it gets to installing the Magento_Catalog then on running this SQL command:

INSERT INTO `session` (`session_expires`, `session_data`, `session_id`) VALUES ('1433773767', 'X3Nlc3Npb25fdmFsaWRhdG9yX2RhdGF8YTo0OntzOjExOiJyZW1vdGVfYWRkciI7czowOiIiO3M6ODoiaHR0cF92aWEiO3M6MDoiIjtzOjIwOiJodHRwX3hfZm9yd2FyZGVkX2ZvciI7czowOiIiO3M6MTU6Imh0dHBfdXNlcl9hZ2VudCI7czowOiIiO31hZG1pbnxhOjA6e31kZWZhdWx0fGE6MDp7fWN1c3RvbWVyX2Jhc2V8YTowOnt9', 'hkksug9ed17flgp3m7kf5e95s1')

It quits out and gives me the error:

 [Exception]
  Warning: Error while sending QUERY packet. PID=25773 in /vagrant/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line
  228

Any ideas?

Thanks

**Comment by mazhalai** [comment]
@Zaylril can you please check your mySQL logs? I could be a mySQL configuration issue, specifically setting for `max_allowed_packet`

**Comment by Zaylril** [comment]
Just to give a bit more information I'm running a VM on my windows machine and this error occurs when running the install command within the VM itself which is a CentOS machine. When I tailed the mysql log it logs the insert into the "session" table as above and then just says "Quit" and displays the error I put above.

I've also increased the max_allowed_packet to 500M and increased the timeout from 10 to 100 but I still get the same errors. It always quits in exactly the same place.

Anything else I can try?

**Comment by mazhalai** [comment]
Can you please tell us what is your version of Magento, MySQL and PHP?

**Comment by jamescowie** [comment]
Magento version:  0.74.0-beta12
MySQL version: 5.6.24-log
PHP version: 5.6.9

**Comment by Zaylril** [comment]
Ok,

This has now been solved by increasing the wait_timeout, connect_timeout and also  delayed_insert_timeout

Thanks

**Comment by VladimirZaets** [comment]
Hi @Zaylril. Thank you for your report. 
The issue has been fixed in magento/magento2#15982 by @slackerzz in 2.3-develop branch
Related commit(s):
 - [9e5757df2e1ebfc75e93c9d793473662ec0e761e](https://github.com/magento/magento2/commit/9e5757df2e1ebfc75e93c9d793473662ec0e761e)
 - [1555b967b865b6a31f21b68461a8516254627d6f](https://github.com/magento/magento2/commit/1555b967b865b6a31f21b68461a8516254627d6f)
 - [039e71c5ced19acad3ab4b287c75188d7b1f837e](https://github.com/magento/magento2/commit/039e71c5ced19acad3ab4b287c75188d7b1f837e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by slackerzz** [comment]
Hi @VladimirZaets, how could i have fixed this issue by fixing a test?
