### ISSUE TITLE
[2.2.2] Trailing slash on navigation links causes store-view-specific CMS pages to switch to default store view

### ISSUE THREAD

**Issue by blizam** [magento/magento2#13507]
Magento 2.2.2

Nothing custom in my .htaccess file

1 Web Site (one domain), 1 Store, 2 Store Views with locale set; en_US and fr_FR

Add Store Code to Urls is set to No

Home page is comprised of 2 CMS Pages each assigned to a different Store View; Store View 1 is the Default

2 CMS Pages with the same URL Key (article-1); 1 page set to Store View 1 and 1 page set to Store View 2

On the frontend (domain.com) when you visit the site the default store view, Store View 1 (english), is loaded. Use the Store View Switcher to switch to Store View 2 (french) and it switcher works correctly. You can even visit domain.com and domain.com/ respectively and the correct store view is maintained.

You can then navigate to domain.com/article-1 and the correct storeview there will be maintained; however if navigate to domain.com/article-1/ (with a trailing slash) then the site will revert to Store View 1 (english). You can try this anywhere from home page, another CMS page, or the /article-1 page itself... simply navigating to a either article-1 or article-2 with a trailing slash will change the store view.

The same is not true if a CMS page is assigned to BOTH store views... then it maintains the store view regardless of whether the navigating link has a trailing slash or not.

**Comment by magento-engcom-team** [comment]
@blizam, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sanjay-wagento** [comment]
I am working on this at #dmcdindia

**Comment by sanjay-wagento** [comment]
@magento-engcom-team @blizam, I reviewed the issue and found that actual issue is not related to trailing slash.
If you want to make it working like http://hostnamae/article-1/ then you require to make changes from Admin >> Store >> Configuration >> GENERAL >> Web >> Search Engine Optimization >> Use Web Server Rewrites >> Yes

Reason is when you open site with index.php then it create store cookie with index.php path and after that, if you try to access any cms page without index.php then Magento by default take index.php in path because of your server and Magento settings.

**Comment by magento-engcom-team** [comment]
@sanjay-wagento Thank you for in-depth research on this.
@blizam We are closing this ticket now, please refer to the comment above. If you still experience the issue – please reopen.
Thanks
