### ISSUE TITLE
Magento ignore store-level url_key of child category in URL rewrite process for global scope

### ISSUE THREAD

**Issue by sergei-sss** [magento/magento2#13513]
### Preconditions
1. Magento 2.2.2 CE with sample data, php 5.0.20.

### Steps to reproduce
1. Create additional store view for Main Website,  name: "Second Store View", code: "second"
2. bin/magento indexer:reindex
3. For category "Bags" on the "second" store view(!) modify URL Key to bags-second
https://drive.google.com/a/mgworx.com/file/d/1b79K8y4HdAn2WbgdV4KJt8mIlalj1jAK/view?usp=drivesdk
4. For parent category "Gear" modify on the All Store Views(!) scope URL Key to gear-global
https://drive.google.com/a/mgworx.com/file/d/1v8HFA8uO4aT6oquchbSSuiQaHJMJz3yz/view?usp=drivesdk

### Expected result
1. For second store view result ULR must corresponding:
http://magento.local/gear-global/bags-second.html

### Actual result
Result rewrite is:
1. http://magento.local/gear-global/bags.html

After step 3 URL was http://magento.local/gear/bags-second.html

After step 4 rewrite from http://magento.local/gear/bags-second.html to 
http://magento.local/gear-global/bags.html
https://drive.google.com/a/mgworx.com/file/d/1rP_ctymA2jfo4SKu0BKqPlmR_5ZZRcVs/view?usp=drivesdk

URL Key attribute of "Bags" category on the second store wasn't change - "bags-second".
https://drive.google.com/a/mgworx.com/file/d/17m92TtdLn1FaEPBeJ_lFj93EU7Hydrhy/view?usp=drivesdk

Product rewrites also were incorrect generated, example for second store level:
gear/bags-second/push-it-messenger-bag.html -> gear-global/bags/push-it-messenger-bag.html

### Possible reasons

You don't load real store view(!) URL key for children categories for the url_path generation process.
Instead of this you simply load category child collection for store_id=0 and set each possible store_id to child category model - but it does not influence on the URL Key:

https://github.com/magento/magento2/blob/79463a5629c6fb742ab6bd63583e89b7c0dfeba4/app/code/Magento/CatalogUrlRewrite/Observer/CategoryUrlPathAutogeneratorObserver.php#L91

**Comment by magento-engcom-team** [comment]
@sergei-sss, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @sergei-sss The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
