### ISSUE TITLE
Magento 2.1.7: Admin user with custom role

### ISSUE THREAD

**Issue by vishalmangoitsolutions** [magento/magento2#13512]
### Preconditions
1.  Magento 2.1.7

### Steps to reproduce
1. Create admin user and role with Custom Resource Access
2. Select all checkboxes. Screenshot: https://drive.google.com/file/d/1OQyqsMPV9uwtlTTnp2YGPtanQN5IwyFR/view?usp=drivesdk
3. Login with newly created admin user.
4. Some section will not show, Like: 
    a) Integration, Screenshot: https://drive.google.com/file/d/1OQyqsMPV9uwtlTTnp2YGPtanQN5IwyFR/view?usp=drivesdk
    b) Web, Currency Setup etc. Screenshot: https://drive.google.com/file/d/1k13yHSNR_x6DfEZv64c4Odv6Gz1pwPHi/view?usp=drivesdk

### Expected result

1. It should show all sections in admin as I checked all checkboxes.

### Actual result

1. Not showing some section and submenus.

**Comment by magento-engcom-team** [comment]
@vishalmangoitsolutions, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by vishalmangoitsolutions** [comment]
@magento-engcom-team I have fixed the issue on my end. please find attached zip for updated files.
Note: These are magento 2.1.7 files.
[app.zip](https://github.com/magento/magento2/files/1722615/app.zip)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @vishalmangoitsolutions The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
