### ISSUE TITLE
Upgrade 2.1.8 to 2.2.2 admin blank page

### ISSUE THREAD

**Issue by sambalay** [magento/magento2#13521]
### Preconditions

1. Magento 2.1.8

### Steps to reproduce

1. After upgrade admin is showing the blank page

### Expected result

1. should show admin login page

### Actual result

1. Blank page
also see this error 
main.CRITICAL: Unable to Connect to tcp://1.2.3.4(public IP):80. Error #110: Connection timed out {"exception":"[object] (Zend_Http_Client_Adapter_Exception(code: 0): Unable to Connect to tcp://1.2.3.4(public IP):80. Error #110: Connection timed out at /var/www/vhosts/dev.domain.com/httpdocs/vendor/magento/zendframework1/library/Zend/Http/Client/Adapter/Socket.php:235)"} []

**Comment by sambalay** [comment]
Also seeing this error too

main.CRITICAL: Dotmailer connector API endpoint cannot be empty. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Dotmailer connector API endpoint cannot be empty. at /var/www/vhosts/dev.domain.com/httpdocs/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/Client.php:118)"} []

**Comment by orlangur** [comment]
Hi @sambalay, looks like there is an issue with third-party extension

> /vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/Client.php:118)

Respective vendor should be contacted in such case, GitHub is intended for bug reports in Magento core modules.

**Comment by simon-letch** [comment]
Hey @sambalay, we are aware of the issue and you can track it's progress here: https://github.com/dotmailer/dotmailer-magento2-extension/issues/495

We have a fix for it which will be released in the next few days. It's caused by one of our cron jobs which is not checking if a dotmailer account has been connected before attempting to do work. It's highly unlikely to be the cause of your blank admin page.
