### ISSUE TITLE
Layered navigation does't work with "show out of stock" option

### ISSUE THREAD

**Issue by RomaKis** [magento/magento2#13541]
### Preconditions
Magento 2 on develop branch.
1. Create product attribute new_attribute type dropdown with two options "first", "second", scope: global and visible in layered navigation(with results). Add it to default attribute set.
2. Create three products Simple1(in stock), Simple2(out of stock) and Simple3(in stock) and add it two category "Test":
- Simple 1 set new_attribute - "first";
- Simple 2 set new_attribute - "first";
- Simple 3 set new_attribute - "second".

### Steps to reproduce
1. Go to frontend to category "Test". You should see in Layered navigation new_attribute with options:
- "first(1)";
- "second(1)";
2. Press on each option and be sure that you really see only one product on each.
3. Go to Magento configuration -> Catalog -> Inventory -> Stock Option -> Display Out of Stock Products -> Yes. Save. Clean cache.
4. Go to frontend to category "Test". You should see in Layered navigation new_attribute with options:
### Expected result
- "first(2)";
- "second(1)";
### Actual result
- "first(1)";
- "second(1)";

5. Press on each option. At "first" you will see two products and in "second" you will see one.

How to fix:
`app/code/Magento/CatalogSearch/Model/Adapter/Mysql/Aggregation/DataProvider.php` - method `getDataSet` doesn't  check `cataloginventory/options/show_out_of_stock`, it only add `->where('stock_index.stock_status = ?', Stock::STOCK_IN_STOCK);`
Need to add check:
```
/**
     * @return bool
     */
    private function isAddStockFilter()
    {
        $isShowOutOfStock = $this->scopeConfig->isSetFlag(
            'cataloginventory/options/show_out_of_stock',
            ScopeInterface::SCOPE_STORE
        );

        return false === $isShowOutOfStock;
    }
```

**Comment by magento-engcom-team** [comment]
@RomaKis, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by eh6design** [comment]
Would this be why I have out of stock items showing in my layered navigation even though I have Magento configuration -> Catalog -> Inventory -> Stock Option -> Display Out of Stock Products set to No?

If so, can you confirm exactly where I add the above code?

**Comment by eugene-shab** [comment]
I cannot reproduce it on 2.2.4 version

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
I cannot reproduce it on 2.3-develop
