### ISSUE TITLE
reindext reqired

### ISSUE THREAD

**Issue by lidiawang** [magento/magento2#13590]
### Preconditions

1. 
2. [ma==Magento2.2.2](url
![image](https://user-images.githubusercontent.com/35614931/36039794-8f8f8fa0-0d91-11e8-89cc-ab20e1ad3d9e.png)
)

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by orlangur** [comment]
This is normal if you didn't setup cron. Please provide more details according to template.

**Comment by RahulBhut21** [comment]
Goto your installation directory, open command line and run this command in command line
" php bin/magento indexer:reindex "

**Comment by magento-engcom-team** [comment]
@lidiawang, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
