### ISSUE TITLE
loadCache for Block Magento\Theme\Block\Html\Footer dont work

### ISSUE THREAD

**Issue by larsroettig** [magento/magento2#13595]
### Preconditions
1.  Install 2.2-develop CE or EE

### Steps to reproduce
1.  Disable Full page caching in Backend
2. Reload the Category Page 

### Expected result
**\Magento\Framework\View\Element\AbstractBlock::_loadCache**
  ` $cacheData = $this->_cache->load($cacheKey);` return a result for the second Page reload

### Actual result
**\Magento\Framework\View\Element\AbstractBlock::_loadCache**
  ` $cacheData = $this->_cache->load($cacheKey);` return false

See:
![footer](https://user-images.githubusercontent.com/5289370/36061349-47433210-0e59-11e8-90ed-52d11fd4c808.png)

**Comment by magento-engcom-team** [comment]
@larsroettig, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by zolat** [comment]
We are working on it #MLAU18 @willtran

**Comment by okorshenko** [comment]
Hi @larsroettig. Thank you for your report. 
The issue has been fixed in magento/magento2#13762 by @zolat in 2.2-develop branch
Related commit(s):
 - [a9d7a7ad691680216e3318e162ab4da8b5b6d88b](https://github.com/magento/magento2/commit/a9d7a7ad691680216e3318e162ab4da8b5b6d88b)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your report. 
The issue has been fixed in magento/magento2#13785 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [53c732150e2bddb3211e07f2624378278cf0db80](https://github.com/magento/magento2/commit/53c732150e2bddb3211e07f2624378278cf0db80)
 - [24078453b209bf36374840d79e82824eb37ad160](https://github.com/magento/magento2/commit/24078453b209bf36374840d79e82824eb37ad160)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @larsroettig. Thank you for your report. 
The issue has been fixed in magento/magento2#17092 by @mageprince in 2.1-develop branch
Related commit(s):
 - [58698b55dc33ced5794f226e32ef90fa9d8bd69b](https://github.com/magento/magento2/commit/58698b55dc33ced5794f226e32ef90fa9d8bd69b)

The fix will be available with the upcoming 2.1.15 release.
