### ISSUE TITLE
Totals sort order is not respected in customer account order view

### ISSUE THREAD

**Issue by schmengler** [magento/magento2#13631]
### Preconditions
1. Magento 2.2

### Steps to reproduce
1. Configure a non-default sort order for total (e.g. discount before shipping)
2. Place an order with multiple totals (e.g. with discount and with shipping)

### Expected result

1. Configured sort order is respected (as in checkout)

### Actual result
1. It's always shipping, then discount, then additional totals

Apparently, Magento implements a NothingSort algorithm:

https://github.com/magento/magento2/blob/2bbf7e92c114f65e99a0be74713bf4251f143e5b/app/code/Magento/Sales/Block/Order/Totals.php#L282-L297

**Comment by schmengler** [comment]
Oh, and `applySortOrder()` is never called, so trying to fix that method doesn't help

**Comment by magento-engcom-team** [comment]
@schmengler, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by schmengler** [comment]
@magento-engcom-team Please note that I implemented the missing `applySortOrder` in PR #13641, you should be able to build upon this

**Comment by magento-engcom-team** [comment]
Hi @schmengler. Thank you for your report. 
The issue has been fixed in magento/magento2#14231 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [a7ff3051f39868c3ac72ab40483cceb53e2359be](https://github.com/magento/magento2/commit/a7ff3051f39868c3ac72ab40483cceb53e2359be)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @schmengler The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
