### ISSUE TITLE
Admin Sales->Archive | Masactions "Remove to Archive" instead "Return to Order Management"

### ISSUE THREAD

**Issue by sadon** [magento/magento2#13645]
### Preconditions

1. Magento 2.2.2 EE

### Steps to reproduce

1. Go to Admin
2. View Orders in Sales->Archive
3. Check on dropdown Masaction 
4. The last option named "Remove to Archive" 

### Expected result

1. Option must be named "Return to Order Management" or similar
It return orders to ordinary Order Management

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/2854508/36192108-44ac6be6-1171-11e8-8f58-875127c5d20f.png)

**Comment by magento-engcom-team** [comment]
Hello @sadon. The functionality You are talking about here belongs only to EE versions. So please refer directly to Magento support with this issue. Thank You.

**Comment by magento-engcom-team** [comment]
@sadon, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
