### ISSUE TITLE
Pdf data formatting issue

### ISSUE THREAD

**Issue by priti-rathee** [magento/magento2#13651]
### Preconditions

1. Magento 2.2.2
2. 7.0.24

### Steps to reproduce

1. I stall fresh magento instance
2. Place an order
2. Generate invoice from admin panel

### Expected result

1. Product price, subtotal,tax values should be as it is in the order details.

### Actual result

1. First digits of the price values are getting cut
2.Currency symbol is not coming proper.(my currency is indian rupee
![22](https://user-images.githubusercontent.com/33680940/36200045-7cc52a24-11a1-11e8-995c-490c18a05d35.png)
![screenshot from 2018-02-14 16-07-28](https://user-images.githubusercontent.com/33680940/36200067-84d49fb0-11a1-11e8-8ca6-1b35f5bce289.png)

)
 [Screenshot, logs]

**Comment by magento-engcom-team** [comment]
@priti-rathee, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @priti-rathee thank you for you report, the issue was tested and we can confirm that is already fixed in 2.3-develop branch and available on 2.3.1 release. thanks for collaboration.
