### ISSUE TITLE
Can we add image in magento2 using URL via rest API.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#13657]
### Preconditions
1. Magento all versions
2. 

### Steps to reproduce
1. use magento 2 media api to add image in Magento2.
2. pass data with base64 image.
3. everything working

Question: 
Can we import images using Image URLs instead of passing base64data.

Thanks

**Comment by magento-engcom-team** [comment]
Hello @ankursachdeva11.  The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Thank You.

**Comment by magento-engcom-team** [comment]
@ankursachdeva11, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
