### ISSUE TITLE
Issue in product title with special chars in mini cart

### ISSUE THREAD

**Issue by Sunil-Nethues** [magento/magento2#13652]
### Preconditions

1. Magento 2.2.2 version
2. Php version 7, Linux
3. default Luma theme

### Steps to reproduce

1. create a product titled Fusion Backpack &trade;
2. go to front end the product title comes up correctly as Fusion Backpack ™ then add it to cart
3. in the mini cart it shows it as Fusion Backpack &trade; and not converting &trade; to ™

### Expected result

1. Mini cart should also show the correct product title after converting the html equivalent to characters

### Actual result

1. ![errr](https://user-images.githubusercontent.com/36194094/36201242-599a5dae-11a5-11e8-997a-323f9932f4e0.png)

**Comment by magento-engcom-team** [comment]
@Sunil-Nethues , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation without any extensions if you have.

![product_name_01281280980](https://user-images.githubusercontent.com/31669971/36202444-7fa4449c-118c-11e8-9adc-4964ed623bdc.png)

**Comment by Sunil-Nethues** [comment]
Hello @magento-engcom-team , i have a fresh installation of v 2.2.2

The site can be seen at http://magento6.newsoftdemo.info/m22.2.2/fusion-backpack.html

**Comment by magento-engcom-team** [comment]
@Sunil-Nethues , thanks for you update. We cannot reproduce this issue with sample data too. 

![backpack](https://user-images.githubusercontent.com/31669971/36254100-6be65ed8-1252-11e8-9e80-379abc233e7e.png)

**Comment by ananth-iyer** [comment]
@Sunil-Nethues 
Please let us know how you installed Magento 2.2.2
Using zip file or composer install

I've also reproduced the issue but didn't find the issue with sample data on fresh composer install.

**Comment by Sunil-Nethues** [comment]
@Ananth747 i have installed the magento2.2.2 using composer. then installed sample data using composer as well. After that i went to admin and changed the product name from Fusion Backpack to Fusion Backpack &trade and then tried to add it in cart. where i saw the issue.

**Comment by magento-engcom-team** [comment]
@Sunil-Nethues, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by mrkhoa99** [comment]
@Sunil-Nethues this is because Magento just shows the product name as a plain text, not a HTML. But, I ask myself it makes sense if allowing HTML in the product name?

**Comment by magento-engcom-team** [comment]
Hi @Sunil-Nethues. Thank you for your report. 
The issue has been fixed in magento/magento2#13802 by @afirlejczyk in 2.3-develop branch
Related commit(s):
 - [764f0862f46204f649367728333f40f39509bd7c](https://github.com/magento/magento2/commit/764f0862f46204f649367728333f40f39509bd7c)

The fix will be available with the upcoming 2.3.0 release.

**Comment by saravananvelu** [comment]
The same issue I could get reproduced in cart summary section of checkout page. To fix that need to update 
**vendor\magento\module-checkout\view\frontend\web\template\summary\item\details.html**

Use:
`<strong class="product-item-name" data-bind="html: $parent.name"></strong>`

instead

`<strong class="product-item-name" data-bind="text: $parent.name"></strong>`

**Comment by magento-engcom-team** [comment]
Hi @Sunil-Nethues. Thank you for your report. 
The issue has been fixed in magento/magento2#14665 by @ampulos in 2.1-develop branch
Related commit(s):
 - [ac083d49e4e1541851685fef4147b329c5e53f17](https://github.com/magento/magento2/commit/ac083d49e4e1541851685fef4147b329c5e53f17)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @Sunil-Nethues. Thank you for your report. 
The issue has been fixed in magento/magento2#14681 by @ihor-sviziev in 2.2-develop branch
Related commit(s):
 - [8a30ffd9ed56f80bb54cbfb597e5452e21e2463c](https://github.com/magento/magento2/commit/8a30ffd9ed56f80bb54cbfb597e5452e21e2463c)

The fix will be available with the upcoming 2.2.5 release.

**Comment by geoffbeaumont** [comment]
It looks to me like the fix only works for products with links? The knockout.js type on the non-link product title also needs changing to html.

**Comment by InternetMedicineMan** [comment]
I'm running 2.2.7 and this problem has always occurred for us. It was never fixed in 2.2.5

**Comment by ihor-sviziev** [comment]
Hi @InternetMedicineMan,
Could you report separate issues for that?
Thank you!

**Comment by j-lloyd-slc** [comment]
For anyone having this issue in later versions, make sure that you don't have an extension that is re-introducing the problem. E.g. Aitoc PreOrders v2.2.0 re-introduced the issue via its own version of 

`view/frontend/web/template/minicart/item/default.html`
