### ISSUE TITLE
magento 2 admin - Changing default product view per page from 20 to 1000

### ISSUE THREAD

**Issue by Asifjalil99** [magento/magento2#13664]
want to change current products / catalog view / Configurable Products from by default 20 view per page to 1000 views per page changes i have done in both files gird.phtml and extended.phtml but not working need your help its urgent, changes below i have done but not working . 
Thanks
 
```
<option value="520"<?php if ($block->getCollection()->getPageSize() == 520): ?>
                            selected="selected"<?php endif; ?>>520
                        </option>
                        <option value="550"<?php if ($block->getCollection()->getPageSize() == 550): ?>
                            selected="selected"<?php endif; ?>>550
                        </option>
                        <option value="700"<?php if ($block->getCollection()->getPageSize() == 700): ?>
                            selected="selected"<?php endif; ?>>700
                        </option>
                        <option value="800"<?php if ($block->getCollection()->getPageSize() == 800): ?>
                            selected="selected"<?php endif; ?>>800
                        </option>
                        <option value="1000"<?php if ($block->getCollection()->getPageSize() == 1000): ?>
                            selected="selected"<?php endif; ?>>1000
                        </option>
```

**Comment by Asifjalil99** [comment]
any one please i need help magento Team can you please help me it very urgent please

**Comment by magento-engcom-team** [comment]
Hello @Asifjalil99. At GitHub issue tracker according to our workflow we need at first to reproduce Your issue. Then if reproduced to add it to our backlog. Then when its turn comes to get processed our developers will start to work on it. It seems Your issue is more appropriate for the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) than this forum. Please refer there or to some other programming forums if You need an urgent help. Thank You.

**Comment by magento-engcom-team** [comment]
@Asifjalil99, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
Hello @Asifjalil99. At GitHub issue tracker according to our workflow we have to try to reproduce Your issue at first. Then if reproduced, we add it to our backlog. Then when its turn comes to get processed our developers will start working on it. It seems Your issue is more appropriate for the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) than this forum. So please refer there or to some other programmers forum if You need an urgent help. Thank You.

**Comment by Asifjalil99** [comment]
i have posted in [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) lets see what happen forum lets see whats happen but i need to fix i before 8hours so need very urgent help
