### ISSUE TITLE
Magento 2.2.2 run super slow on MAMP

### ISSUE THREAD

**Issue by duytran21** [magento/magento2#13667]
### Preconditions

I'm setting up Magento on Macbook Air localhost using MAMP but It runs really slow. I searched and did some setup as: turn on Varnish cache, minify CSS ... but the speed still slow. Here is my configurations: 
1. Magento Version 2.2.2
2. MAMP Server: 
- php7.0.22 already set up memory_limit to 2G
- Webserver Apache
- MySQL version 5.6.35
3. Macbook Air 13" 2015 and I tried to set up on Macbook Pro 15" 2012 but nothing changed.
4. Ram 8Gb, CPU: i5 1.6GHz, 128Gb SSD.

### Steps to reproduce

1. Turn on Varnish Cache
2. Turn on Minify CSS and JS
3. Setup Php ini memory_limit to 2G

### Expected result

1. Do you know how to boost up the speed?

Thank you so much

**Comment by magento-engcom-team** [comment]
@duytran21, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@duytran21 thank you for your report,
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
