### ISSUE TITLE
Magento 2 config options not showing

### ISSUE THREAD

**Issue by danncoba** [magento/magento2#13677]
Magento 2 admin > Stores > Configuration isn't displaying the actual input fields only the tabls on the left. After selecting one of the configuration options not shows up in main content, no input fields, save button nothing.

This is a regular magento 2 with my 3 extension that were custom built. The extensions configuration worked normally.

Only change that i've done is that i've enabled redis-cache for sessions, page_cache for frontend and admin after which i can't see the system configurations at all.

Regards

**Comment by magento-engcom-team** [comment]
@danncoba , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@danncoba, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
