### ISSUE TITLE
Cannot create catagory's name with thai langauge

### ISSUE THREAD

**Issue by juniorkidza1994** [magento/magento2#13689]
### Preconditions
1. Magento 2.2.2
2. PHP 7.1.11

### Steps to reproduce
1. Create new sub category
2. Use thai language in name field 

### Expected result
1. get new category with thai name language Or have a meaningful message that we need to fix url key manually

### Actual result

1. get error in picture
![screen shot 2561-02-16 at 3 28 43 pm](https://user-images.githubusercontent.com/8817242/36299125-2abe2724-132e-11e8-9b4a-122f4b5390c1.png)
And message not clear at all

**Comment by magento-engcom-team** [comment]
@juniorkid, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by otokoalan** [comment]
I'm working on it. 
#MLAU18

**Comment by ghost** [comment]
Still reproducing at 2.3-develop branch.
![DeepinScreenshot_select-area_20190405104325](https://user-images.githubusercontent.com/40756439/55611935-a7e12200-578f-11e9-8d23-c9e64b175cbc.png)

**Comment by abhi-ranosys** [comment]
I am working on this at #dmcdindia19

**Comment by pradeep-wagento** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30158` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @juniorkid. Thank you for your report. 
The issue has been fixed in magento/magento2#27412 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [577a27ee25312b6eed02aa528fc96505b886ab28](https://github.com/magento/magento2/commit/577a27ee25312b6eed02aa528fc96505b886ab28)
 - [76890694ccdcd6c8063cabab83c9004dc0ff2026](https://github.com/magento/magento2/commit/76890694ccdcd6c8063cabab83c9004dc0ff2026)

The fix will be available with the upcoming 2.4.0 release.
