### ISSUE TITLE
In payment step of checkout I cannot unselect #billing-save-in-address-book checkbox in non-first payment method

### ISSUE THREAD

**Issue by ghost** [magento/magento2#13692]
### Preconditions

1. Magento version 2.2.0
2. At least 2 payments methods enabled

### Steps to reproduce

1. Log in to your client account.
2. Add product to cart.
3. Go to checkout and click next button to be able to choose payment methods.
4. Open payment method other than the first one.
5. Uncheck _My billing and shipping address are the same_ checkbox
6. Choose _New address_ on the billing address dropdown
7. Fill address
8. Click on label _Save in address book_

### Expected result

1. The checkbox is unchecked.

### Actual result

1. The checkbox stays checked regardless click on label

That happens because in every payment method tab _Save in address book_ checkbox has the same id: **#billing-save-in-address-book** If there are multiple checkboxes with the same id all labels are associated with the first one.
![zrzut ekranu 2018-02-16 o 10 30 26](https://user-images.githubusercontent.com/12411219/36301816-701fd75e-1306-11e8-9186-5d2a0042ef19.png)

**Comment by magento-engcom-team** [comment]
@NeosKnowledgeBasePluswerk, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@NeosKnowledgeBasePluswerk, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by rakesh-gangani** [comment]
#DMCDINDIA

**Comment by magento-engcom-team** [comment]
@rsquarem thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @NeosKnowledgeBasePluswerk. Thank you for your report. 
The issue has been fixed in magento/magento2#15344 by @rakesh-gangani in 2.2-develop branch
Related commit(s):
 - [97a1eceb4b11cce4cc754bb06b6f95cc8a3ec7ae](https://github.com/magento/magento2/commit/97a1eceb4b11cce4cc754bb06b6f95cc8a3ec7ae)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @NeosKnowledgeBasePluswerk. Thank you for your report. 
The issue has been fixed in magento/magento2#16811 by @mage2pratik in 2.1-develop branch
Related commit(s):
 - [0f3ec2516effd4ea76db76a5d6677d0e09057bad](https://github.com/magento/magento2/commit/0f3ec2516effd4ea76db76a5d6677d0e09057bad)

The fix will be available with the upcoming 2.1.15 release.

**Comment by sidolov** [comment]
Hi @NeosKnowledgeBasePluswerk. Thank you for your report. 
The issue has been fixed in magento/magento2#16993 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [a659f4b9321a4036a9e45130b7695387066f967d](https://github.com/magento/magento2/commit/a659f4b9321a4036a9e45130b7695387066f967d)

The fix will be available with the upcoming 2.3.0 release.
