### ISSUE TITLE
Custom WebAPI doesn't return Array as  JSON

### ISSUE THREAD

**Issue by cedricve** [magento/magento2#13694]
Hello all,

I'm trying to create a custom webapi module, it works great however if I want to return a JSON response I get an empty array[] instead. However If I wrap the return value in another array I see the values. What's going wrong (this is really weird).

### Steps to reproduce

1.  Create a custom API
2.  Return Array from method

### Expected result

1. 
    {
        "id": 100,
        "permalink": "lol",
        "mac": "e5b28b82657a528fb778d0671dd0538f49a4ea3b0cdd7f17c7d4fb3907a595ac"
    }

### Actual result

1.
[
    {
        "id": 100,
        "permalink": "lol",
        "mac": "e5b28b82657a528fb778d0671dd0538f49a4ea3b0cdd7f17c7d4fb3907a595ac"
    }
]

**Comment by magento-engcom-team** [comment]
@cedricve, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@cedricve thank you for your report,
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
