### ISSUE TITLE
Console Error: Call to a member function getId() on null in .../vendor/magento/module-new-relic-reporting/Model/Observer/ReportSystemCacheFlushToNewRelic.php:58

### ISSUE THREAD

**Issue by IgorSIT** [magento/magento2#13693]
### Preconditions

1. Magento ver. 2.1.10
2. PHP 5.6

### Steps to reproduce

1.  Field Enable New Relic Integration set to "Yes" in Admin Magento 2 (Stores -> Configuration -> General -> New Relic Reporting)
2.  To run bin/magento cache:clean command in the console

### Expected result

1. bin/magento cache:clean command is executed in console when field Enable New Relic Integration set to "Yes" in Admin Magento 2

### Actual result

1. PHP Fatal error: Uncaught Error: Call to a member function getId() on null in .../vendor/magento/module-new-relic-reporting/Model/Observer/ReportSystemCacheFlushToNewRelic.php:58

When running  bin/magento cache:clean command in the console I have such a error:

PHP Fatal error: Uncaught Error: Call to a member function getId() on null in .../vendor/magento/module-new-relic-reporting/Model/Observer/ReportSystemCacheFlushToNewRelic.php:58

This error occurs if in field Enable New Relic Integration set to "Yes" in Admin Magento 2 (Stores -> Configuration -> General -> New Relic Reporting) because in the ReportSystemCacheFlushToNewRelic.php file in row 58 is returns logged backend user, but the bin/magento cache:clean command is executed in console and variable $user will be always NULL.

$user = $this->backendAuthSession->getUser(); 
if ($user->getId ()) { 
... 
}

**Comment by magento-engcom-team** [comment]
@IgorSIT thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by IgorSIT** [comment]
I go to Admin Magento 2 to Stores -> Configuration -> General -> New Relic Reporting.
Field "Enable New Relic Integration" setting to "Yes".
Clicking button "Save Config".
Saving is complete and display message "You saved the configuration."

I go to console and run bin/magento cache:clean command and I have such error:

PHP Fatal error: Uncaught Error: Call to a member function getId() on null in .../vendor/magento/module-new-relic-reporting/Model/Observer/ReportSystemCacheFlushToNewRelic.php:58
...

**Comment by hostep** [comment]
Hi @IgorSIT 

This should not happen in a default clean Magento installation, since that piece of code is only executed in the `adminhtml` area. Because the event is defined in the [`etc/adminhtml/events.xml` file](https://github.com/magento/magento2/blob/2.1.10/app/code/Magento/NewRelicReporting/etc/adminhtml/events.xml#L11).

But I have a good guess as to why this problem happens in your case. It's because when executing whatever command using the cli, it executes **all** constructors of all registered commands over all default Magento and 3rd party modules. And if one of those constructors changes the area to `adminhtml` you'll run into this problem.
You can very easily reproduce this problem on a clean Magento by for example editing the file `vendor/magento/module-catalog/Console/Command/ImagesResizeCommand.php` and add this line to the constructor of that class:
```php
$this->appState->setAreaCode('adminhtml');
```

So now it's up to you to find which custom module triggers this, so search through all your custom modules and try to find an instance where `setAreaCode` is being used in the constructor. Disabling that line should fix your issue. And please report such problems to the vendor of the module, because I've seen this mistake being made *a lot* in 3rd party modules. Developers should try to avoid executing logic in the constructor of a class, only assign member variables.

**Comment by IgorSIT** [comment]
Hi, @hostep 
Ok. 
Thanks for answer.
