### ISSUE TITLE
Make magento/product-community-edition available on GitHub

### ISSUE THREAD

**Issue by kassner** [magento/magento2#13749]
Currently is not possible to see the differences between versions for `magento/product-community-edition` composer virtual package (and enterprise as well). For a custom project, requiring `magento/product-community-edition` directly is not viable because unwanted packages are added by it, so instead we copy the `require` section into our own `composer.json` and remove what we need. But this quite an extensive task to get them every time a new version is released, since several modules have their versions bumped.

### Preconditions

None

### Steps to reproduce

None

### Expected result

1. Have `magento/product-community-edition`'s `composer.json` definition available on GitHub, with all applicable tags, so we can diff the `composer.json` between all the released versions;
2. Bonus: have `magento/product-community-edition` available on Packagist.org;
3. Bonus: have `magento/product-enterprise-edition` available on GitHub (and/or Packagist.org) if applicable/allowed;

### Actual result

`magento/product-community-edition` definition is not available anywhere public.

**Comment by magento-engcom-team** [comment]
@kassner, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by cedricziel** [comment]
Same problem, my motivation is slightly differrent: I want to apply patches through composer or at least be able to require a dev-branch.

**Comment by hostep** [comment]
@okorshenko, @maksek: any chance of this happening?

It would allow the community to send in PR's to this repo. Like to move a couple of non required and buggy modules (temando, shopialfb & dotmailer) from the `require` section to the `suggest` section in the `composer.json` file.

Also: any chance of giving access to the meta project `magento/project-community-edition` which is being used when calling `composer create-project magento/project-community-edition`, so we can remove the alpha requirement of `composer/composer` from there?

And while talking about `temando/module-shipping-m2` & `shopialfb/facebook-module`, maybe make these available as well? Since I can't find these on github anywhere, only `dotmailer/dotmailer-magento2-extension` is available. It would also allow the community to send in fixes for those modules (if they really have to stay part of the default Magento installation)

Thanks!

**Comment by magento-engcom-team** [comment]
Hi @kassner. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/62
