### ISSUE TITLE
Wysiwyg > Image Uploader >Max width/height

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#13747]
Not able to upload images bigger than 1920px width or 1200px height. There is no way to configure the max size in the backend, except of changing the values programmatically. There are some community entries about it:
https://magento.stackexchange.com/questions/144013/default-uploading-image-size-in-magento-2

### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Get an image of size of 3000x700
https://dummyimage.com/3000x700
2. Open a CMS page
3. Use the wysiwyg to upload an image

### Expected result

1. The image size remains lossless

### Actual result

1. The image gets resized to 1920x448

We need to remove this functionality or give a possibility to configure the values through the backend.

Further, can someone clarify some questions please:

1. Wtf is this limitation for?
2. Why is there no possibility to configure that values?
3. Why does the system dictates how big my images should be?

**Comment by magento-engcom-team** [comment]
@Detzler, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by lgrassini** [comment]
This is also happening with the product images. 
Any estimated resolution time for this?

**Comment by nadeefit6** [comment]
Do we really need to change this behavior?
Could you please reply. Then i will be able to attend.

**Comment by amitsiliguri** [comment]
This feature is good. It prevents the site from slowing down. High-resolution big images are bad for the website performance, speed and UX. 1920x448 size is enough for a website banner.

**Comment by Detzler** [comment]
I understand that some non-developer admins can upload horrible big images, but please dont tell us that the size of 1920x448 is enough. 

At least, lets keep the current resize values as default, but lets make a possibility to override that values by configuration. Changing the values programmatically engrosses much time a.k.a. money.

**Comment by eduard13** [comment]
I'm working on this one.

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#15942 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [933e4964b2d67bb1865325902c8245db453b060f](https://github.com/magento/magento2/commit/933e4964b2d67bb1865325902c8245db453b060f)
 - [a579bff44bbf87cf623efe36d70b52f610978415](https://github.com/magento/magento2/commit/a579bff44bbf87cf623efe36d70b52f610978415)
 - [4ecce145d51e1d226fd57d49b0c9f0e5b0fa5402](https://github.com/magento/magento2/commit/4ecce145d51e1d226fd57d49b0c9f0e5b0fa5402)
 - [c51b1d455175406c91dcb009ee19f1aa1b92e981](https://github.com/magento/magento2/commit/c51b1d455175406c91dcb009ee19f1aa1b92e981)
 - [1d5e56b8ac039d0607d1849a3d8471b06d3e450c](https://github.com/magento/magento2/commit/1d5e56b8ac039d0607d1849a3d8471b06d3e450c)
 - [f7b4a66bb4122e1251a2272c7172ea34b38296ef](https://github.com/magento/magento2/commit/f7b4a66bb4122e1251a2272c7172ea34b38296ef)
 - [e1591e49061ff13aed39c713448e53d31d463c52](https://github.com/magento/magento2/commit/e1591e49061ff13aed39c713448e53d31d463c52)
 - [0c8221b8dbb26f854d7f85bf44f06964eeeb3d59](https://github.com/magento/magento2/commit/0c8221b8dbb26f854d7f85bf44f06964eeeb3d59)
 - [2491b51fc9c3ad87cb3c387363acb0b3dc278b05](https://github.com/magento/magento2/commit/2491b51fc9c3ad87cb3c387363acb0b3dc278b05)
 - [7b4b32f50bf62f6e0f20779b4d2a068aca1f6782](https://github.com/magento/magento2/commit/7b4b32f50bf62f6e0f20779b4d2a068aca1f6782)
 - [0f630172f4a6086b2ffd3d1f56951fd909813d0f](https://github.com/magento/magento2/commit/0f630172f4a6086b2ffd3d1f56951fd909813d0f)
 - [128724fdbc2d53dd974204fe51d7aba814feffe0](https://github.com/magento/magento2/commit/128724fdbc2d53dd974204fe51d7aba814feffe0)
 - [30822efedf3b02f74cb648fff78d7fc4973c7cbf](https://github.com/magento/magento2/commit/30822efedf3b02f74cb648fff78d7fc4973c7cbf)
 - [2e6923620b359ad6a00958ab8f08ed600c0c361a](https://github.com/magento/magento2/commit/2e6923620b359ad6a00958ab8f08ed600c0c361a)
 - [614570fa3a70a6cfdcc0746cbde915ba980ae514](https://github.com/magento/magento2/commit/614570fa3a70a6cfdcc0746cbde915ba980ae514)
 - [507d18335294ec85a9c7ea76dcab29957a02b44d](https://github.com/magento/magento2/commit/507d18335294ec85a9c7ea76dcab29957a02b44d)

The fix will be available with the upcoming 2.2.7 release.

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#17826 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [88e26f2b958d6835f877d0feea8759418326a7f5](https://github.com/magento/magento2/commit/88e26f2b958d6835f877d0feea8759418326a7f5)
 - [44102727d7671b999daef0059de5a859a9d81d2f](https://github.com/magento/magento2/commit/44102727d7671b999daef0059de5a859a9d81d2f)

The fix will be available with the upcoming 2.3.0 release.
