### ISSUE TITLE
Expired backend password - Attention: Something went wrong

### ISSUE THREAD

**Issue by janssensjelle** [magento/magento2#13768]
### Preconditions
1. Clean Magento 2.2 install, either Open Source, Commerce or Commerce + B2B
2. PHP 7.1.11

### Steps to reproduce
1. Create any backend user. 
2. Wait/set the password as expired
3. Log in
4. You will get an error popup with Attention: Something went wrong. Also it will show _A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later._
5. After change password, the error messages are gone.

### Expected result
1. Error popup saying your password has expired. No Technical error message. 

### Actual result
You will get an error popup with Attention: Something went wrong. Also it will show _A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later._

[https://imgur.com/a/XyQg1](https://imgur.com/a/XyQg1)

**Comment by magento-engcom-team** [comment]
@janssensjelle, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @janssensjelle. Thank you for your report. 
The issue has been fixed in magento/magento2#13787 by @nuzil in 2.2-develop branch
Related commit(s):
 - [96a8b5817fb0fdbea8701ba1f0e5a7ca404a82e2](https://github.com/magento/magento2/commit/96a8b5817fb0fdbea8701ba1f0e5a7ca404a82e2)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @janssensjelle. Thank you for your report. 
The issue has been fixed in magento/magento2#14199 by @dimonovp in 2.3-develop branch
Related commit(s):
 - [4df41e14b62ddb1cc117ed7eaf7548d74f4ca35d](https://github.com/magento/magento2/commit/4df41e14b62ddb1cc117ed7eaf7548d74f4ca35d)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @janssensjelle. Thank you for your report. 
The issue has been fixed in magento/magento2#17091 by @mageprince in 2.1-develop branch
Related commit(s):
 - [90a8bed94c857708d99154f22abd930b2ea522cb](https://github.com/magento/magento2/commit/90a8bed94c857708d99154f22abd930b2ea522cb)

The fix will be available with the upcoming 2.1.15 release.
