### ISSUE TITLE
Order Email Sender

### ISSUE THREAD

**Issue by pawcioma** [magento/magento2#13769]
Probably I found wrong logical in "\Magento\Sales\Model\Order\Email\Sender::checkAndSend" because you catch Exception and then you return true. In database will be information about  send_email and email_sent as true, but email can not be sent.

Original code:
`protected function checkAndSend(Order $order)
    {
        $this->identityContainer->setStore($order->getStore());
        if (!$this->identityContainer->isEnabled()) {
            return false;
        }
        $this->prepareTemplate($order);

        /** @var SenderBuilder $sender */
        $sender = $this->getSender();

        try {
            $sender->send();
            $sender->sendCopyTo();
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage());
        }

        return true;
}`

For my opinion should be:
`protected function checkAndSend(Order $order)
    {
        $this->identityContainer->setStore($order->getStore());

        if (!$this->identityContainer->isEnabled()) {
            return false;
        }

        $this->prepareTemplate($order);

        /** @var SenderBuilder $sender */
        $sender = $this->getSender();

        try {
            $sender->send();
            $sender->sendCopyTo();
        } catch (\Exception $e) {
            $this->logger->error($e->getMessage());

            return false;
        }

        return true;
    }`

**Comment by magento-engcom-team** [comment]
@pawcioma, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by pawcioma** [comment]
If you want I can take care of it.

**Comment by ArjenMiedema** [comment]
@pawcioma you can assign yourself to this issue and create a pull request so it can be reviewed and merged.

**Comment by pawcioma** [comment]
Ok . I will prepare "pull request", but how can I assign to the issue?

**Comment by ArjenMiedema** [comment]
Just did it for you. Good luck fixing the issue!

**Comment by magento-engcom-team** [comment]
Hi @pawcioma. Thank you for your report. 
The issue has been fixed in magento/magento2#13878 by @pawcioma in 2.2-develop branch
Related commit(s):
 - [1c7e3a144fce8ac5168e51fd559404e1e0122bd4](https://github.com/magento/magento2/commit/1c7e3a144fce8ac5168e51fd559404e1e0122bd4)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @pawcioma. Thank you for your report. 
The issue has been fixed in magento/magento2#14051 by @pawcioma in 2.3-develop branch
Related commit(s):
 - [8d3205926eeafe0b6973cee3af76b8f2ffca7dfa](https://github.com/magento/magento2/commit/8d3205926eeafe0b6973cee3af76b8f2ffca7dfa)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @pawcioma. Thank you for your report. 
The issue has been fixed in magento/magento2#17087 by @mageprince in 2.1-develop branch
Related commit(s):
 - [add1e1459b38ef7f10df4e3b474d1716a739126a](https://github.com/magento/magento2/commit/add1e1459b38ef7f10df4e3b474d1716a739126a)

The fix will be available with the upcoming 2.1.15 release.
