### ISSUE TITLE
Remove deprecated Brazilian currencies in the setup process

### ISSUE THREAD

**Issue by r-martins** [magento/magento2#13760]
### Preconditions
When installing Magento we have to choose a currency for your store.
There are some Brazilian currencies that are deprecated and that does not exist in Brazil for more than a decade and might be disabled/removed/hidden from the list.

### Steps to reproduce
1. Start a new Magento 2.2.4-dev (branch 2.2-develop) setup on /setup
2. Agree to terms on step 1
3. Proceed to the installation until step 4 (Customize your store)
4. See the Store Default Currency with 6 deprecated Brazilian currencies

### Expected result
1. See only Brazilian Real (BRL) option listed as Brazilian currencies.

### Actual result
We see many unused, deprecated currencies for Brazil above the only valid option.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/191149/36455542-ab353b44-16f4-11e8-9f18-c31d831191e0.png">

### Other sources of information
In order to confirm that Brazilian Real is the only valid currency available in Brazil you can:
1. [Google for it](https://www.google.com.au/search?q=brazilian+current+currencies)
2. Check on [Brazilian Central Bank reference](http://www.bcb.gov.br/pre/museu/moedas/real.asp?idpai=MOREAL94)
3. Check on [Wikipedia about Real](https://en.wikipedia.org/wiki/Brazilian_real)
4. Check on [Wikipedia](https://en.wikipedia.org/wiki/Brazilian_currency) that the other currencies are old and deprecated since 1994.

**Comment by r-martins** [comment]
I'm working on it #MLAU18

**Comment by magento-engcom-team** [comment]
@r-martins, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ihor-sviziev** [comment]
Hi @r-martins. Thank you for your report.
The issue has been fixed in https://github.com/magento/magento2/pull/13770 by @r-martins in 2.2-develop branch

Related commit(s):
- b1a5bc197e3177f42025757f6fc6146c25f03a43

**Comment by r-martins** [comment]
My pleasure, @ihor-sviziev

**Comment by magento-engcom-team** [comment]
Hi @r-martins. Thank you for your report. 
The issue has been fixed in magento/magento2#13782 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [3293254f23aa47a2b5bb8e54901ae9f296031727](https://github.com/magento/magento2/commit/3293254f23aa47a2b5bb8e54901ae9f296031727)
 - [a92a3b2e50738e89b0ea423f6f1d0f16b0ad7fff](https://github.com/magento/magento2/commit/a92a3b2e50738e89b0ea423f6f1d0f16b0ad7fff)
 - [ef94d4436a24bf42909beceddcdd4e857ca51dd8](https://github.com/magento/magento2/commit/ef94d4436a24bf42909beceddcdd4e857ca51dd8)

The fix will be available with the upcoming 2.3.0 release.
