### ISSUE TITLE
Show / Hide Editor dont show because fail to load js.

### ISSUE THREAD

**Issue by goben2489** [magento/magento2#13772]
### Preconditions
1. Magento 2.1.5
2. PHP 5.6
3. Live use https for frotend and backend

### Steps to reproduce
1. Go to Block or Page Content
2. Click Show / Hide Editor

### Expected result
1. Editor showing or hide

### Actual result
1. Editor not show and in console showing
Failed to load: pub/static/.../en_US/tiny_mce/plugins/media/editor_plugin_src.js

![h16](https://user-images.githubusercontent.com/14970253/36474471-2e41db84-172a-11e8-8cd8-48bfdf3c2249.jpg)

At local this work perfectly, but on Live is have bug.

**Comment by magento-engcom-team** [comment]
@goben2489, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@goben2489, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
