### ISSUE TITLE
Braintree Paypal Method No Order Confirmation Email Sent

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#13778]
1. 2.2.2 

### Steps to reproduce
1. Only payment method used is built in braintree module.  When customer pays via credit card, email confirmation is sent. When customer pays via paypal via the braintree paypal method, no order confirmation is sent.

**Comment by magento-engcom-team** [comment]
@snoroozi , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
Hi @snoroozi. Thank you for your report. 
The issue has been fixed in magento/magento2#13898 by @pmclain in 2.2-develop branch
Related commit(s):
 - [975137b58353bcef780e34e679fe8b115f98fe34](https://github.com/magento/magento2/commit/975137b58353bcef780e34e679fe8b115f98fe34)
 - [aec7af9c3b0ebf733d9c94fc3f34696e4cd87769](https://github.com/magento/magento2/commit/aec7af9c3b0ebf733d9c94fc3f34696e4cd87769)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @snoroozi. Thank you for your report. 
The issue has been fixed in magento/magento2#14225 by @dimonovp in 2.3-develop branch
Related commit(s):
 - [413b8981388d8a356db0f02ec096c91c388ae44e](https://github.com/magento/magento2/commit/413b8981388d8a356db0f02ec096c91c388ae44e)
 - [2b64618e4cc35ab27d142f4f84a17d99cc3b17dd](https://github.com/magento/magento2/commit/2b64618e4cc35ab27d142f4f84a17d99cc3b17dd)

The fix will be available with the upcoming 2.3.0 release.
