### ISSUE TITLE
Enable RMA option is not found on Product detail page

### ISSUE THREAD

**Issue by deepthit57** [magento/magento2#13771]
Install Magento Enterprise 2.2.0 version with sample data

1.Go to Sales>Sales>RMA setting and set Enable RMA on Product Level to Yes
2.Go to Products, Choose a product and click on Edit
3.check for option Enable RMA in product detail page

Expected:
Enable RMA option appears in product detail page
Actual:
Enable RMA option is not present 
![product detail page](https://user-images.githubusercontent.com/20681023/36473095-95a4f236-1719-11e8-98b6-2034daa2fc59.png)
in product detail page

**Comment by magento-engcom-team** [comment]
@deepthit57 , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@deepthit57, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
