### ISSUE TITLE
JQMIGRATE: jQuery.browser is deprecated

### ISSUE THREAD

**Issue by iprabhakar** [magento/magento2#13799]
Hi, I am using my custom theme with Magento2.1.11. On checkout page is not complete loading getting this error in console.
JQMIGRATE: jQuery.browser is deprecated
migrateWarn @ jquery-migrate.js:41
get @ jquery-migrate.js:58
(anonymous) @ jquery.ba-hashchange.min.js:9
(anonymous) @ jquery.ba-hashchange.min.js:9
(anonymous) @ jquery.ba-hashchange.min.js:9
jquery-migrate.js:43 console.trace
migrateWarn @ jquery-migrate.js:43
get @ jquery-migrate.js:58
(anonymous) @ jquery.ba-hashchange.min.js:9
(anonymous) @ jquery.ba-hashchange.min.js:9
(anonymous) @ jquery.ba-hashchange.min.js:9

Please, help me out, wasted whole day.

**Comment by magento-engcom-team** [comment]
Hello @iprabhakar. The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment]
@iprabhakar, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
