### ISSUE TITLE
Invoice grid shows wrong subtotal for partial items invoice. It shows order's subtotal instead if invoiced item's subtotal

### ISSUE THREAD

**Issue by ankurvr** [magento/magento2#13804]
### Preconditions

1. Magento Version : (2.1.6 | 2.2.0 | 2.2.2) (community-edition), 2.2.2 (enterprise-edition)
2. PHP : 7.0.24
3. MySQL : 5.7.19
4. Platform : MacOS High Sierra v10.13.3 (17B1003)

### Steps to reproduce

1. Place order with multiple taxable items
2. Generate separate invoice for each items. (In short generate multiple invoices for same order with different items)
3. Do check value of **Subtotal** column value in Invoice grid.

### Expected result

1. In Invoice grid it should show **Subtotal** of invoiced items only, not order's subtotal

### Actual result

1. In Invoice grid it shows order's **Subtotal** instead of invoiced item's **Subtotal**
<img width="989" alt="screen shot 2018-02-23 at 10 45 51 am" src="https://user-images.githubusercontent.com/3338156/36579119-6d2c6e6e-1887-11e8-9279-6ec4ffd5eee1.png">
<img width="990" alt="screen shot 2018-02-23 at 10 46 32 am" src="https://user-images.githubusercontent.com/3338156/36579120-6d52a14c-1887-11e8-9ac4-fdfddee4af58.png">
<img width="983" alt="screen shot 2018-02-23 at 10 46 50 am" src="https://user-images.githubusercontent.com/3338156/36579121-6d796426-1887-11e8-858d-270ed8e1f1d4.png">

**Comment by magento-engcom-team** [comment]
@ankurvr, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ankurvr** [comment]
I have already created pull request for this bug fix. So i suggest to not putting this in backlog. And put it in Merging queue.

**Comment by magento-engcom-team** [comment]
Hi @ankurvr. Thank you for your report. 
The issue has been fixed in magento/magento2#13855 by @ankurvr in 2.2-develop branch
Related commit(s):
 - [579b07479e314a2272db61e514843df138bc5a68](https://github.com/magento/magento2/commit/579b07479e314a2272db61e514843df138bc5a68)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @ankurvr. Thank you for your report. 
The issue has been fixed in magento/magento2#14209 by @AlexWorking in 2.3-develop branch
Related commit(s):
 - [0bfc3e17f9baef90c4639b25956ca6947838312e](https://github.com/magento/magento2/commit/0bfc3e17f9baef90c4639b25956ca6947838312e)

The fix will be available with the upcoming 2.3.0 release.
