### ISSUE TITLE
banner slider not working showing one after the another

### ISSUE THREAD

**Issue by akshaykamble27** [magento/magento2#13805]
i had purchased couture fashion theme and try to create banner slider with their sample code  but my banner slider not working. Image is coming one after the other

this is link of sample code
:http://www.confluence.izysync.com/display/DOC/2.+Couture+Fashion+User+Guides

1. php-7.0.2
2. magento 2.1.9
3. Mysql-5.7x
4.Ubuntu

**Comment by magento-engcom-team** [comment]
@akshaykamble27, thank you for your report.
We can't help you with third-party extensions or code. The GitHub issue tracker is intended for technical issues only. Please refer to the creator of **your theme** or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by magento-engcom-team** [comment]
@akshaykamble27, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
