### ISSUE TITLE
Special Price Not Showing on Category List Page

### ISSUE THREAD

**Issue by webspeaks** [magento/magento2#13803]
### Preconditions

1. Installed Magento 2.2.2
2. Migrated magento 1 site (1.9.3) to Magento 2.2.2. Everything goes well.
3. Set special price for few products.
4, Theme is default Magento Luma (no changes)

### Steps to reproduce

1. Set special price for any product. Thats it.

### Expected result

1. We should see special price and regular price (striked out) on the products page and category listing page

### Actual result

1. Special price appears only on the product page,
2. On Category page it still shows the regular price. Please see below screenshot:

![image](https://user-images.githubusercontent.com/1465109/36578058-f883ff10-1880-11e8-83aa-bc43e75215eb.png)

![image](https://user-images.githubusercontent.com/1465109/36578005-c2c80100-1880-11e8-97ba-e56cd6d90fec.png)

I tried to debug the issue and here are my findings:
In `Magento\Catalog\Pricing\Render\FinalPriceBox` the function `hasSpecialPrice()` returns false on the category page but it returns true on the product page. I am still not sure why it is happening.
Any clues here?

**Comment by magento-engcom-team** [comment]
Hi @webspeaks. For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by magento-engcom-team** [comment]
@webspeaks, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by webspeaks** [comment]
This is not a migration issue. Even if I create new product and add special price, it does not show in category page. How can it be migration related issue?

**Comment by magento-engcom-team** [comment]
You see @webspeaks, even if it is not a Migration Tool issue, anyway it will be reviewed and processed by our specialists when they see it on that repository. Besides this kind of issue is most likely caused by migration. If You try to reproduce it on a clear, freshly downloaded and installed instance of Magento 2.2.2 (not migrated from Magento 1.x.x) You won't get it done.

**Comment by vmasciotta** [comment]
Hi all, I'm experiencing the same "non-issue".
@webspeaks did You solve the problem?

Thanks

**Comment by ncaballerobol** [comment]
Having same issue on 2.3.1

**Comment by ArjenvanEck** [comment]
Having this issue, how did you solve it?

**Comment by rstylenl** [comment]
I know this is an old issue, but i had with a recent migration from Magento 1.9.4.0 to Magento 2.4.4.

To fix this issue: 
1. Log in to the Backend
2. Goto Stores -> (under Attributes) click on product
3. Search for Special Price Attribute. And click on it to edit it.
4. on the lefthand side click on: Storefront Properties
5. Set Used in Product Listing to Yes.
6. Reindex

After these changes it worked started to work again. Hopefully this helps someone out coming across the same issue.

@ArjenvanEck @webspeaks 
![specprice-](https://user-images.githubusercontent.com/6038697/185377425-2e049498-d100-4097-ae2a-4aedffbee1fe.PNG)
