### ISSUE TITLE
Google Analytics character encoding issue ( \u0020 )

### ISSUE THREAD

**Issue by bigbywolf-uk** [magento/magento2#13827]
### Preconditions
1. Magento 2.2.2.
2. PHP 7.0

### Steps to reproduce
1. Set locale to en_GB
2. Enable Google Analytics tracking on backend
3. Purchase products on the frontend
4. Login to Google Analytics
5. Go to Conversions ->E-Commerce -> Overview

### Expected result
1. Product names showing up correctly

### Actual result
1. Spaces in product names get replaced by their HTML value: \u0020
https://goo.gl/5EjjZx

Fix found in this error report:
https://github.com/magento/magento2/issues/13350

Edit: /vendor/magento/module-google-analytics/Block/Ga.php
and replace every **escapeJs** with **escapeJsQuote**

Result:
https://goo.gl/mb1YU3

**Comment by ihor-sviziev** [comment]
Hi, this issue originally was reported in https://github.com/magento/magento2/issues/13350. I'm closing this issue as duplicate.

**Comment by magento-engcom-team** [comment]
Hi @Munszu. Thank you for your report. 
The issue has been fixed in magento/magento2#13844 by @julienanquetil in 2.2-develop branch
Related commit(s):
 - [5843e815a57a514226ec5d2104afb4b2d4fea726](https://github.com/magento/magento2/commit/5843e815a57a514226ec5d2104afb4b2d4fea726)
 - [0d5197f8619b34dce648e554b7c317faeb56ca15](https://github.com/magento/magento2/commit/0d5197f8619b34dce648e554b7c317faeb56ca15)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @Munszu. Thank you for your report. 
The issue has been fixed in magento/magento2#13907 by @julienanquetil in 2.3-develop branch
Related commit(s):
 - [c09c8d5c164a6ed2fb05c591d0a060f5a68e56cf](https://github.com/magento/magento2/commit/c09c8d5c164a6ed2fb05c591d0a060f5a68e56cf)

The fix will be available with the upcoming 2.3.0 release.
