### ISSUE TITLE
PHP memory issue "Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to alloc ate 4096 bytes)"

### ISSUE THREAD

**Issue by aakash1213** [magento/magento2#13846]
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to alloc ate 4096 bytes) in \vendor\zendframework\zend-stdlib \src\PriorityQueue.php on line 281

I am using Magento 2.2.2 version and Migrated old Magento 1.9.2 site to Magento 2.2.2. 
While migration faced some issues but I have resolved it. Now I am trying to add new extension with the store and to get it installed and enable it I am running the Magento commands but not it is giving me this error in the terminal.

### Steps to reproduce
1. After Data migration I am facing this issue.
2. I am trying to use Magestore Banner slider extension with Magento 2.2.2
3. Errors are genrated while running the commands in the terminal.

### Expected result
trying to run following commands
```
php bin\magento cache:clean
php bin\magento cache:flush
php bin\magento setup:upgrade
php bin\magento indexer:reindex	
```

Expected result : Run the commands install and enable the extension.

### Actual result
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 4096 bytes) in \vendor\zendframework\zend-stdlib\src\PriorityQueue.php on line 281

I have set `memory_limit= 8G` but still it is showing memory allocation issue.
All possible caches cleaned, folders under var/ removed, but getting same result.
Have already searched so any reference links and tried the solutions given to still getting same errors.

**Comment by magento-engcom-team** [comment]
Hi @aakash1213. For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by magento-engcom-team** [comment]
@aakash1213, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by muckee** [comment]
@magento-engcom-team please re-open this issue. I experience it with a fresh install of magento 2.2.5, without migration.

**Comment by DanielRuf** [comment]
@JoshuaFlood please make sure to increase the memory_limit of PHP.

**Comment by muckee** [comment]
@DanielRuf I have set the memory limit in my server's php.ini to 2048M. I have also set it in Magento's .htaccess and .ini files. Actually, since updating all of the entries from 768 to 2048 I can't execute any magento commands at all. I receive an error saying memory is exhausted at 2M... So it is obviously being overridden somewhere. I've checked the relevant folders' memory limit and all are displaying as expected. Will try with a fresh install next week. Not at home until then so can only test with existing install.

**Comment by DanielRuf** [comment]
Did you restart the server after this?

**Comment by muckee** [comment]
@DanielRuf yes I have tried that and I still can't execute any commands. Even something like `magento module:status` throws an 'out of memory' error.

**Comment by DanielRuf** [comment]
Try adding the memory_limit parameter to `php bin/magento ...`

**Comment by muckee** [comment]
Thanks! I'll just stick with it. I'm already aware that this is an option, it just seems ludicrous to me that Magento would even suggest things like adding the `bin/magento` command as an environment variable or suggesting their dysfunctional 'two-user' setup. Ideally, I'd just like to find a solution which allows me to run magento commands in their standard format, or at least see some explanation within the official documentation of common issues relating to permissions or PHP settings, because right now the best support seems to be from community members taking stabs in the dark. Hopefully Adobe will have a positive influence.

**Comment by DanielRuf** [comment]
> like adding the bin/magento command as an environment variable or suggesting their dysfunctional 'two-user' setup.

I do not fully understand. You just have to provide the PHP CLI options for the memory_limit parameter to increase it during the steps.

**Comment by DanielRuf** [comment]
In general your PHP CLI version has different settings than the version running your website.

**Comment by DanielRuf** [comment]
Did you try `php -d memory_limit=-1 bin/magento setup:upgrade`?

**Comment by ingedicson** [comment]
Yes DanielRuf, that work for me!
Thanks!

I executed commands like:

/opt/plesk/php/7.2/bin/php -d memory_limit=-1 bin/magento setup:upgrade
/opt/plesk/php/7.2/bin/php -d memory_limit=-1 bin/magento setup:di:compile
/opt/plesk/php/7.2/bin/php -d memory_limit=-1 bin/magento setup:static-content:deploy -f es_ES
/opt/plesk/php/7.2/bin/php -d memory_limit=-1 bin/magento indexer:reindex
/opt/plesk/php/7.2/bin/php -d memory_limit=-1 bin/magento cache:clean
/opt/plesk/php/7.2/bin/php -d memory_limit=-1 bin/magento cache:flush

Thanks
