### ISSUE TITLE
Magento 2.2.2 - Minicart does not display Trademark symbol while Prod Detail Page does

### ISSUE THREAD

**Issue by Vikram0811** [magento/magento2#13847]
I have products where it is important to have symbols like `™` and `®`, as these are necessary to be with product name. When I tried to import such products, it throws exception `General system exception` happened on Check Data.

After removing same symbols, file is being validated successfully. I tried using HTML equivalent instead for example - Testing Product &trade; in CSV

- `™ : &trade;`

- `® : &reg;`

It renders those characters correctly on product detail page like Testing Product ™ , but on minicart it shows text like Testing Product &trade; Also it shows the same when I edit any product in admin.

How do I resolve this to make it appear consistent throughout the store?

**Comment by magento-engcom-team** [comment]
@Vikram0811, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
