### ISSUE TITLE
Credit doesn't recognize amount after comma

### ISSUE THREAD

**Issue by gerben86** [magento/magento2#13851]
When I enter an amount with decimals (like 2,50) in the field "Adjustment Refund" while making a Credit Memo the amount on the real credit memo is without decimals (2,00). So the Credit Memo isn't in line with the real credit amount.

### Preconditions
1. Magento 2.1.10

### Steps to reproduce
1. Create a Credit Memo for an order
2. Enter an amount with decimals (by example 1,23) in the field Adjustment Refund
3. Create an offline payment (finish credit memo)

### Expected result
1. The credit memo should show the amount of 1,23 in the field "Adjustment Refund" on the Credit Memo overview

### Actual result
1. The credit memo should show the amount of 1,00 in the field "Adjustment Refund" on the Credit Memo overview

I'm using a comma as decimal seperator, because my local language is dutch.

**Comment by magento-engcom-team** [comment]
@gerben86, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by vijay-wagento** [comment]
This is working fine in magento 2.2. Verified at #dmcdindia

**Comment by magento-engcom-team** [comment]
@vijay-wagento thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
@gerben86 Could you please verify that it works as expected for you now?

**Comment by gerben86** [comment]
@magento-engcom-team , Unfortunally the issue still exist (Magento 2.2.4) See printscreens.
Adding adjustment amounts:
![step1](https://user-images.githubusercontent.com/17478858/40575512-80fed7ae-60e6-11e8-8655-bc2f00e79e8a.JPG)
Decimals are gone after clicking on "Update Totals":
![step2](https://user-images.githubusercontent.com/17478858/40575503-6306a772-60e6-11e8-81a3-bbfdc58d0c5d.JPG)

**Comment by GovindaSharma** [comment]
#MM19IN

**Comment by magento-engcom-team** [comment]
Hi @tonytrinh218. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by tonytrinh218** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tonytrinh218. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tonytrinh218, here is your [Magento instance](https://i-13851-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-13851-2-3-develop.instances.magento-community.engineering/admin](https://i-13851-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30172` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sedero** [comment]
The problem is the trim function on Magento/module-sales/Model/Order/Creditmemo.php

setAdjustmentPositive / setAdjustmentNegative

$amount = trim($amount);

**Comment by magento-engcom-team** [comment]
Hi @gerben86. Thank you for your report. 
The issue has been fixed in magento/magento2#27343 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [4046760db00a93d147b3b40609c1c0b6cdda8ca0](https://github.com/magento/magento2/commit/4046760db00a93d147b3b40609c1c0b6cdda8ca0)

The fix will be available with the upcoming 2.4.0 release.
