### ISSUE TITLE
Add Mod_version to system requirements

### ISSUE THREAD

**Issue by amenk** [magento/magento2#13850]
http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

should state the requirement for "mod_version"

See also #12777

**Comment by chickenland** [comment]
Think this probably needs to be reported over at https://github.com/magento/devdocs/issues ?

**Comment by magento-engcom-team** [comment]
Hello @amenk. Please reopen this issue in the correct repository mentioned above. Thanks for reporting.

**Comment by magento-engcom-team** [comment]
@amenk, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
