### ISSUE TITLE
after data migration admin page not working

### ISSUE THREAD

**Issue by akshaykamble27** [magento/magento2#13854]
I have installed Magento 2 was working fine until after Data Migration.
I install data migration tool via composer then migrate data from m1 to m2 .
Then After customer page working properly but admin page is not working.
I suspect that the front end is working but that I need to get to admin panel to change the theme.

This is where the problem arises.
gives a 404 error page not found error. 
I have attached Screenshot for above erro
![magentoerror](https://user-images.githubusercontent.com/36723685/36715257-75419a34-1bbb-11e8-84f2-0583425a02af.png)

1 .Php 7.0.2 
2. Magento 2.1.9
3. Mysql 5.7x

**Comment by magento-engcom-team** [comment]
Hi @akshaykamble27. For migration related issues please use the correct repository: https://github.com/magento/data-migration-tool

Thank you.

**Comment by magento-engcom-team** [comment]
@akshaykamble27, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
