### ISSUE TITLE
Back button goes to the top of the grid instead of scrolling down to where you left off

### ISSUE THREAD

**Issue by robbertstevens** [magento/magento2#13868]
### Steps to reproduce

1. Go from a grid to an entity
2. Go back, either via back button or browser back button
3. You come back at the top of the grid.

### Expected result

1. Scroll to the location in the grid you left before you go to the entity

### Actual result

1. You come back to the  top of the grid

**Comment by nshiff** [comment]
@robbertstevens Hello. In order to ensure issues are addressed as effectively as possible, the Magento team requires that issues conform to a common format and provide some basic information. Your post has been automatically tagged as "G1 Failed," which means you left out some of the required information. Please review the guidelines and update your post: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

Thanks for reporting, and happy hacking.

**Comment by magento-engcom-team** [comment]
Hi @robbertstevens. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/64
