### ISSUE TITLE
Sorting on country_of_manufacture product attribute not working

### ISSUE THREAD

**Issue by hiren2615** [magento/magento2#13864]
Magento provide built-in product attribute with code **country_of_manufacture**. In admin product grid sorting on this attribute is not working.

### Preconditions
Magento Version : CE 2.2.2
PHP version     : PHP 7.0.18-1+deb.sury.org~xenial+1
MySQL version   : mysql Ver 14.14 Distrib 5.7.20

### Steps to reproduce
1. Navigate to admin catalog product grid
2. Using "Columns" selection add **Country of Manufacture** column in grid
3. Now click on this **Country of Manufacture** column to apply sorting in grid
4. Now you can see that sorting is not working in any order for this column

### Expected result
Sort by **Country of Manufacture** should be working fine.

### Actual result
Sort by country_of_manufacture product attribute not working. See below screen.
![actual](https://user-images.githubusercontent.com/23444023/36729098-fa6ccd0a-1be8-11e8-92a9-785104f03830.png)

**Comment by magento-engcom-team** [comment]
@hiren-wagento, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by milindfulcrum** [comment]
Any solution or temporary fix  for this issue, we also facing same issue while sorting with websites

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
