### ISSUE TITLE
When creating configurable products I cannot add simple products directly

### ISSUE THREAD

**Issue by robbertstevens** [magento/magento2#13882]
### Preconditions

1. Have a configurable product with no simples attached
2. Magento ver. 2.1.10

### Steps to reproduce

1. Have a configurable product
2. Click on Edit configurations
3. Go to step 4
4. no way to add simples.

### Expected result

1. abbility to add simple products instead of fake product first
2. then remove fake product and and simples

### Actual result

1. No button to add simple product directly
![image](https://user-images.githubusercontent.com/726557/36781557-77dca142-1c76-11e8-9a1a-791c5e4b8243.png)

**Comment by magento-engcom-team** [comment]
@robbertstevens, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
Anyway, Your issue will be reviewed and considered by our developers as a feature request.

**Comment by magento-engcom-team** [comment]
Hi @robbertstevens. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/65
