### ISSUE TITLE
Postal code (zip code) for Canada should allow postal codes without space

### ISSUE THREAD

**Issue by sl02** [magento/magento2#13899]
This is practically a copy-paste of issue #11898, which was for Netherlands. 

### Issue

Zip code validation warning on adresses from Canada.
Current validation is A1B 2C3
This should also allow postal code without space A1B2C3

### Preconditions

Tested only on 2.2.

### Steps to reproduce

Go to cart or checkout, select Canada and insert postal code A1B2C3

### Expected result

No warning

### Actual result

Zipcode gives warning

Additional info:
Like in issue #11898, even though having the space is the official format, having no space is still widely accepted and common. Should definitely not trigger an error.

**Comment by magento-engcom-team** [comment]
@sl02, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by tadeobarranco** [comment]
#MageTitansMX

**Comment by magento-engcom-team** [comment]
@tadeobarranco thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @sl02. Thank you for your report. 
The issue has been fixed in magento/magento2#13930 by @tadeobarranco in 2.2-develop branch
Related commit(s):
 - [c6d128f6c12ad81dade448723ebe4a17bc06c3be](https://github.com/magento/magento2/commit/c6d128f6c12ad81dade448723ebe4a17bc06c3be)
 - [7c5ddeedb0d6c48a7db85e6b8163bd99f6632a0f](https://github.com/magento/magento2/commit/7c5ddeedb0d6c48a7db85e6b8163bd99f6632a0f)
 - [fa8b88491e28853e0d9cd6b5849bda233a41f1bf](https://github.com/magento/magento2/commit/fa8b88491e28853e0d9cd6b5849bda233a41f1bf)
 - [8fae90bfa98424f794ed53f128ce6e26ad639b5c](https://github.com/magento/magento2/commit/8fae90bfa98424f794ed53f128ce6e26ad639b5c)

The fix will be available with the upcoming 2.2.4 release.

**Comment by magento-engcom-team** [comment]
Hi @sl02. Thank you for your report. 
The issue has been fixed in magento/magento2#14215 by @AlexWorking in 2.3-develop branch
Related commit(s):
 - [c87b10465a4b051a5c6cf54668ed143417c6a0b9](https://github.com/magento/magento2/commit/c87b10465a4b051a5c6cf54668ed143417c6a0b9)
 - [ac377279fb55dc1f8301239bb381ed9b8dd68573](https://github.com/magento/magento2/commit/ac377279fb55dc1f8301239bb381ed9b8dd68573)
 - [bda63c768690b1a6d90a63e9b63dcaebf5247581](https://github.com/magento/magento2/commit/bda63c768690b1a6d90a63e9b63dcaebf5247581)
 - [cb04f93530361abc63cab78253b426044f79d8a7](https://github.com/magento/magento2/commit/cb04f93530361abc63cab78253b426044f79d8a7)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @sl02. Thank you for your report. 
The issue has been fixed in magento/magento2#16031 by @hitesh-wagento in 2.1-develop branch
Related commit(s):
 - [bc26a3a132fba7aae4be6095411b212b03c9c93d](https://github.com/magento/magento2/commit/bc26a3a132fba7aae4be6095411b212b03c9c93d)
 - [8f03ac9aee1cad032cbc45f128fa9d86aa0e918b](https://github.com/magento/magento2/commit/8f03ac9aee1cad032cbc45f128fa9d86aa0e918b)
 - [2587e0f5f11405aedc431d71542db2ae85af9522](https://github.com/magento/magento2/commit/2587e0f5f11405aedc431d71542db2ae85af9522)
 - [e7db1306f8785684649a06c49a229ddb0f57f641](https://github.com/magento/magento2/commit/e7db1306f8785684649a06c49a229ddb0f57f641)

The fix will be available with the upcoming 2.1.15 release.
