### ISSUE TITLE
Cart subtotal is calculated incorrectly for certain prices

### ISSUE THREAD

**Issue by al1357** [magento/magento2#13903]
Subtotal in cart is calculated incorrectly for certain prices. For other prices it is correct though. In my case it was rounded down.

### Preconditions
1. Tested on Magento CE 2.1.10 and 2.2.3
2. PHP 7.0.20 (cgi-fcgi)

### Steps to reproduce
1. Set product price to **5.36**, apply **10%** tax. Product price with tax is **5.9**
2. Configuration - "Sales" > "Tax" > "Shopping Cart Display Settings"; 3 x Including Tax & 3 x yes
3. Configuration - "Sales" > "Tax" > "Tax Calculation Method Based On" > "Calculation settings" set to Totals. **(setting it to Unit Price solves the problem.)**
3. Add 3 products to cart.

### Expected result
1. Subtotal should be 17.70

### Actual result
1. Subtotal is 17.69

In case of 300 products the difference is: 1770(correct) vs 1768.80

![shopping_cart](https://user-images.githubusercontent.com/7080278/36836227-1801ce32-1d39-11e8-8541-5225495d67a6.png)

**Comment by magento-engcom-team** [comment]
Hello @al1357. Thanks for reporting. We need the product price to have no more than 2 decimal digits after decimal separator. Though in most cases after different calculations of taxes, discounts, etc.  which affect the price,  the price itself in fact changes its value to some that has more than 2 decimal digits. For example in Your case a price of 5.36 taxed by 10% in fact  is equal not to 5.9 but to 5.896. And changes in price bring changes in total of the order or other document. Again for Your case order subtotal and total are precisely equal to 17.688 that is neither 17.69 nor 17.70 at all. So a question comes up where to  round down the numbers in order to get two decimals after decimal separator. Naturally there are only three possible options: 1) to round down the price right after it has been taxed; 2) to round down the order item's total; 3) to round down the last sum, e.g. the whole order's total (in Your case its the same as item's total as Your order contains only one item). And Magento gives all of those possibilities. You just pick up what suites You the best in "Sales" > "Tax" > "Tax Calculation Method Based On" >: Unit Price, Row Total or Total respectively. 
Lets take an example. So lets widen a bit Your case and create two more products with the same price 5.36 and add them to cart together with the first one. Assume free shipping. Now what we would have without rounding. So each product's price with Tax then would be equal 5.896 (5.36 +10%). Each row total (each product's total) - 17.688 (5.896 * 3) and, in the end, the order's total - 53.064 (17.688 * 3). Now depending on where You fulfill the rounding the order total will accept one of the three different values: 53.10, 53.07 or 53.06. Please see the picture below illustrating that.

![roundings](https://user-images.githubusercontent.com/31669971/36888182-0439c70a-1dfd-11e8-96f1-fe4d26a196d7.png)

So that's how everithing should be explained.

**Comment by magento-engcom-team** [comment]
@al1357, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
