### ISSUE TITLE
Missing health check call

### ISSUE THREAD

**Issue by fvschie** [magento/magento2#13924]
### Preconditions
Any Magento 2 version with properly configured REST API credentials

### Steps to reproduce
1. 

### Expected result
I expect an API to have an option to verify the status of the connection and credentials.

### Actual result
I have to use a somewhat expensive call to monitor the health of the connection. This is sub-optimal.

Please add an API call to all versions of Magento2 that requires authentication and returns either no-content or a status (maintenance mode or some such) if available.

**Comment by magento-engcom-team** [comment]
@fvschie, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment]
@fvschie Thank you for reporting

Unfortunately we are closing this ticket now, as Github issue tracker is intended only for core Magento technical issues. Please refer to the [Community Forums](https://community.magento.com/) to submit a feature request or use [magento/community-features](https://github.com/magento/community-features/issues) repository to describe your idea.

Also, consider submitting a Pull Request with the suggested improvement.

Thank you for collaboration!
