### ISSUE TITLE
Sidebar shortcut to admin dashboard (Magento logo on top left) has no link in web setup wizard

### ISSUE THREAD

**Issue by doctormess** [magento/magento2#13948]
### Preconditions

1. Magento 2.2.3
2. Ubuntu 16.04

### Steps to reproduce

1. Admin dashboard>System>Web Setup Wizard
2. Click Magento logo on top left
3. No effect
4. No way to get back to admin dashboard

### Expected result

1. Click Magento logo on top left>admin dashboard

### Actual result

1. No effect as logo has no link like the other sidebars do

**Comment by magento-engcom-team** [comment]
@doctormess, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by osrecio** [comment]
I can't reproducte it, with 2.2-develop. I clicked in `Web Setup Wizard` but redirect me to Dashboard.

**Comment by doctormess** [comment]
![magento logo issue](https://user-images.githubusercontent.com/7372629/37869759-8f03a766-3022-11e8-8ca3-cbddc32f3049.png)

**Comment by osrecio** [comment]
@magento-engcom-team give me 2.2.0 instance.

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento 2.2.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [Magento instance](https://i-13948-2-2-0.engcom.dev.magento.com).
Admin access: [https://i-13948-2-2-0.engcom.dev.magento.com/admin](https://i-13948-2-2-0.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by osrecio** [comment]
I reproduced the problem... but to be honest I don't know what is the best solution. The setup part is written with Angular and not is my area of expertise.

**Comment by arnoudhgz** [comment]
@magento-engcom-team give me 2.2.5 instance.

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz, here is your [Magento instance](https://i-13948-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-13948-2-2-5.engcom.dev.magento.com/admin](https://i-13948-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @doctormess. Thank you for your report. 
The issue has been fixed in magento/magento2#17543 by @arnoudhgz in 2.2-develop branch
Related commit(s):
 - [d10de87796e51c2f21edbc0f73aea25d455e3a40](https://github.com/magento/magento2/commit/d10de87796e51c2f21edbc0f73aea25d455e3a40)

The fix will be available with the upcoming 2.2.7 release.

**Comment by magento-engcom-team** [comment]
Hi @doctormess. Thank you for your report. 
The issue has been fixed in magento/magento2#17610 by @arnoudhgz in 2.3-develop branch
Related commit(s):
 - [43bbdb5730adbe56d161e38e236035c4af0a2c2f](https://github.com/magento/magento2/commit/43bbdb5730adbe56d161e38e236035c4af0a2c2f)

The fix will be available with the upcoming 2.3.0 release.
