### ISSUE TITLE
Magento 2 Stores \ Configuration sub menu does no work

### ISSUE THREAD

**Issue by ghost** [magento/magento2#13946]
When Entering the Stores \ Configuration menu, the sub menu  with the options:
GENERAL
CATALOG
CUSTOMERS
SALES
SERVICES
ADVANCED

Does no work. When clicking either on the text or the arrow to open the sub menu, nothing happens.

### Preconditions

1.  Windows 10, xampp apache + MySQL
2. Magento 2

### Expected result
1. I guess the sub menu should respond

### Actual result
1. Nothing happens.

**Comment by magento-engcom-team** [comment]
Hello @supergula. Thanks for reporting. Unfortunately Magento 2 does not support Windows OS (Magento 1 did it), see the documentation: http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html. Please reopen the issue if You are able to reproduce it using the supported operating system.

**Comment by magento-engcom-team** [comment]
@supergula, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
