### ISSUE TITLE
Stores -> Terms and Conditions - No Store View shown

### ISSUE THREAD

**Issue by raymond62** [magento/magento2#13944]
1. Magento ver. 2.2.2

### Steps to reproduce
1. Go to "Stores -> Terms and Conditions" and create new Condition
2. Do this for different Store Views
3. No Store View in Column "Store View"

### Expected result
1. Store View should be shown in Column "Store View"

### Actual result
1. See Screenshot below

![04-03-2018 16-44-20](https://user-images.githubusercontent.com/29265078/36947429-c238d014-1fcb-11e8-9310-711a8285e161.jpg)

**Comment by magento-engcom-team** [comment]
@raymond62, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by tdgroot** [comment]
@neeta-wagento are you picking up this issue?

**Comment by magento-engcom-team** [comment]
Hi @raymond62. Thank you for your report. 
The issue has been fixed in magento/magento2#14546 by @afirlejczyk in 2.2-develop branch
Related commit(s):
 - [49432af840e272ddfba4da271c29d88dd6242607](https://github.com/magento/magento2/commit/49432af840e272ddfba4da271c29d88dd6242607)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @raymond62. Thank you for your report. 
The issue has been fixed in magento/magento2#14868 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [9000f7498a691ca1c7ca7d239ad97ce84ac41537](https://github.com/magento/magento2/commit/9000f7498a691ca1c7ca7d239ad97ce84ac41537)

The fix will be available with the upcoming 2.3.0 release.
