### ISSUE TITLE
mini cart not  showing items

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1395]
![mini cart](https://cloud.githubusercontent.com/assets/7636894/8267992/044a796a-1793-11e5-943a-1946aa8b3609.png)

i added couple of products to cart with out login.

**Comment by vpelipenko** [comment]
@sivajik34, could you help us with reproducing this issue? Do you see any JS errors? Can you see empty mini shopping cart when you add only specific products? Or it doesn't work correctly for all product types?

**Comment by Zaylril** [comment]
I also have this issue. The problem is that the knockout JS is not rendering the template it seems. There are no JS errors (other that the jquery cookie error which as been around for a while)

Even on a clean install of M2 the template just doesn't render. Even without adding anything to the bag. It should just say "You have no items in your shopping cart." but as above in the screenshot it's blank.

I've also attached an example showing that i have an item in my cart but clicking on the shopping cart doesn't render the minicart as it should nor does it update the icon with a "1" to indicate i have one item in my bag.

![screen shot 2015-06-23 at 09 29 37](https://cloud.githubusercontent.com/assets/245699/8301995/ddc758fe-198a-11e5-8d3a-97b52a4ad9c3.png)

**Comment by kassner** [comment]
@Zaylril just a shot in the water here: can you check if "use SID in Frontend" is set to zero (No) on Stores > Config > General > Web? Also, fill the cookie domain and cookie path options in the same config page. I remember having this issue a while ago, but I haven't seen it since I've changed a bunch of configs, although I have no idea if this is somehow related.

**Comment by vpelipenko** [comment]
Also It will be good if somebody provides screenshot of Firebug Net tab.

**Comment by Zaylril** [comment]
@kassner I've tried those things (It was initially set to Yes for use SID in Frontend, and i changed it to no). I've also set the cookie path and cookie domain and still have the same issue.

@vpelipenko What do you need to see in the network tab? I'll send you a screenshot of it via chrome dev tools. However, everything loads correctly, including the minicart.js file. However this never seems to actually run (adding console logs in some of those functions never appear).

**Comment by orlangur** [comment]
The most interesting part in Network Tab is whether https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/web/template/minicart/content.html template is loaded successfully.

**Comment by Zaylril** [comment]
Ok, so looking at a working version and non working version here, you can see that collection.html and content.html are both loaded on the working version (these are the only html files loaded in the network tab). However they are **not** loaded on my current install. Both versions load minicart.js successfully.

**Comment by Zaylril** [comment]
Ok, it seems that the issue was indeed related to cookies. As i mentioned in my original message no JS errors apart from the jquery-cookie.js error. Well it turns out this seems to have been the problem. I changed the file as suggested in #1363 (which is related to this ticket)

Changing the file app/code/Magento/Customer/view/frontend/web/js/customer-data.js on line 11 from "jquery-cookie" to "jquery.cookie" fixes the issue as the cookies now work correctly and the knockoutJS templates now load correctly.

So this is now resolved.

**Comment by vpelipenko** [comment]
Fix for https://github.com/magento/magento2/issues/1363 is already available in 0.74.0-beta15 version. Could you also verify this issue on the latest code?

**Comment by Zaylril** [comment]
Yep seems to be working correctly now in 0.74.0-beta15. Thanks!

**Comment by sivajik34** [comment]
thank you.its working fine
