### ISSUE TITLE
Url rewrites are generated w/ category path included even with setting turned off

### ISSUE THREAD

**Issue by paul-blundell** [magento/magento2#13974]
### Preconditions
Magento 2.2.2

### Steps to reproduce
1. Set "Use Categories Path for Product URLs" to No
2. Add a new product and select a category

### Expected result
The url_rewrite table should only have the product url in the request path without any categories for each store view.

### Actual result
I am seeing an entry in the url_rewrite table for the product path without categories but there is also an entry with categories included.

A somewhat odd case but this prevents you from having products in a category that have the exact same url key as a child category.

**Comment by AirmanAJK** [comment]
I've noticed this as well. I believe it was intentional as a user could change the config at any time to include those paths or not. If they didn't already exist, updating the config would require potentially many thousands of URL rewrite rules to be created at once in the update request, some of which could conflict with existing rules (as you pointed out).

I do agree that it adds unnecessary clutter for users who never will use category paths for products, but there are some edge cases here that prevent an easy fix.

**Comment by paul-blundell** [comment]
That makes perfect sense. Its just a little odd trying to explain to a client that a category and product url key cannot be the same (in the same parent category), so they must manually edit the url key on one of them. Granted I would say this is more of an edge case than what you described, so I shall close this issue and work around it. Thanks.
