### ISSUE TITLE
Country values missing in admin customer grid for multi-store configuration

### ISSUE THREAD

**Issue by jalogut** [magento/magento2#13971]
Country values missing in "All Customers" admin grid, if multi-store with `Account Sharing Options = per Website`

![Customer Grid Screenshot](https://user-images.githubusercontent.com/6410900/37042812-78a3a86c-215f-11e8-88b2-493270b73b5d.png)

### Preconditions

1. Any Magento version between 2.1.10 to 2.2.3 

### Steps to reproduce

* Vide demo: [customer_grid_country_bug.mov](https://www.dropbox.com/s/7fzx04hwg9ochti/customer_grid_country_bug.mov?dl=0)

1. Create 2 Websites
2. `System > Config > General > Country Options > Allow Countries`
     * Set different allowed countries for each website
3. `System > Config > Customer Configuration > Share Customer Accounts > Per Website`
4. Create a couple of user for each websites. Create also an address for each customer. S

et this address as `default billing`
5. execute `bin/magento indexer:reindex customer_grid && bin/magento c:f`
6. Check customer grid: `Customer > All Customers` 

### Expected result

1. All customers have values on the country column

### Actual result
1. Only some customers have values in country column

### Source of the bug

See my next comment where I explain the 2 reason why this bug is happening

**Comment by jalogut** [comment]
# Bug reason

I figured out the source of the problem. Implementing a proper solution seems a bit more complex.

## Problems:

1. Country source loads only allowed countries for current store. In the admin that is `store_id = 1`  

    `\Magento\Customer\Model\ResourceModel\Address\Attribute\Source\Country`
    
    ```
    public function getAllOptions()
    {
        if (!$this->_options) {
            $this->_options = $this->_createCountriesCollection()->loadByStore(
                $this->getStoreResolver()->getCurrentStoreId()
            )->toOptionArray();
         }
     return $this->_options;
    }
    ```

2. Countries are retrieved from cache. This cache can also be set from frontend store, when a user logs in. If that happens, the countries displayed are the ones allowed where the customer logged in before the cache was set.

    `\Magento\Customer\Model\Metadata\CachedMetadata`
    ```
    public function getAllAttributesMetadata()
    {
        $attributes = $this->attributeMetadataCache->load($this->entityType, 'all');
        if ($attributes !== false) {
            return $attributes;
        }
        $attributes = $this->metadata->getAllAttributesMetadata();
        $this->attributeMetadataCache->save($this->entityType, $attributes, 'all');
        return $attributes;
    }
    ```
## Solution
* First Load all countries for the customer grid and not the ones for the current store.
* Second, do not use same cache for storing the list of `allowed_countries` in frontend and backend.

**Comment by magento-engcom-team** [comment]
@jalogut, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jalogut** [comment]
# Workaround

As workaround, we are using a plugin on the admin grid

`etc/adminhtml/di.xml`
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
   <type name="Magento\Customer\Ui\Component\Listing\AttributeRepository">
       <plugin name="staempfli_corefixes_customer_grid_country" type="Staempfli\CoreFixes\Plugin\Magento\Customer\Ui\Component\Listing\AttributeRepositoryPlugin"/>
   </type>
</config>
```

`\Staempfli\CoreFixes\Plugin\Magento\Customer\Ui\Component\Listing\AttributeRepositoryPlugin`
```
namespace Staempfli\CoreFixes\Plugin\Magento\Customer\Ui\Component\Listing;

use Magento\Customer\Api\Data\AttributeMetadataInterface;
use Magento\Customer\Ui\Component\Listing\AttributeRepository;
use Magento\Directory\Model\ResourceModel\Country\Collection as CountryCollection;
use Magento\Directory\Model\ResourceModel\Country\CollectionFactory as CountryCollectionFactory;

/**
 * Class AttributeRepositoryPlugin
 */
class AttributeRepositoryPlugin
{
    const BILLING_ADDRESS_COUNTRY_ATTRIBUTE = AttributeRepository::BILLING_ADDRESS_PREFIX . 'country_id';

    /**
     * @var CountryCollectionFactory
     */
    private $countryCollectionFactory;

    /**
     * AttributeRepositoryPlugin constructor.
     *
     * @param CountryCollectionFactory $countryCollectionFactory
     */
    public function __construct(CountryCollectionFactory $countryCollectionFactory)
    {
        $this->countryCollectionFactory = $countryCollectionFactory;
    }

    /**
     * @param AttributeRepository $subject
     * @param $result
     * @return array
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function afterGetList(AttributeRepository $subject, $result)
    {
        return $this->getResultWithFixedCountryAttribute($result);
    }

     /**
     * @param array $result
     * @return array
     */
    private function getResultWithFixedCountryAttribute(array $result): array
    {
        $countryAttribute = $result[self::BILLING_ADDRESS_COUNTRY_ATTRIBUTE] ?? null;
        if ($countryAttribute) {
            $countryAttribute[AttributeMetadataInterface::OPTIONS] = $this->getAllCountryOptions();
            $result[self::BILLING_ADDRESS_COUNTRY_ATTRIBUTE] = $countryAttribute;
            return $result;
        }
        return $result;
    }

    /**
     * @return array
     */
    private function getAllCountryOptions(): array
    {
        /** @var CountryCollection $countryCollection */
        $countryCollection = $this->countryCollectionFactory->create();
        return $countryCollection->toOptionArray();
    }

}
```

**Comment by ananth-iyer** [comment]
I'm working on it #dmcdindia

**Comment by sadeeshmca** [comment]
I'm working on it

**Comment by adjogic** [comment]
I'm working on #cd-balance

**Comment by magento-engcom-team** [comment]
@adjogic thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by adjogic** [comment]
I was working on this issue but didn't finish.
The issue is not limited to the grid but is on the filter as well.

I think this should be changed in a way that there is a different source for select on filter and then take the same approach for grid. I was trying to update UI Component for customer listing but had some issues with it.

### Problems
There is another thing to think about here, what countries do we load:
- if we load all countries in the filter it will make it inconvenient when trying to filter
- if we load allowed countries from all store views and some of the countries were removed we wouldn't be able to search for them/see it in the grid

**Comment by magento-engcom-team** [comment]
Hi @jeroenschipper. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Bravo** [comment]
Hello @jalogut 
This issue is not reproducible on Magento 2.4-develop, so we have to close it.
If you are still experiencing the same behavior on Magento 2.4, please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. 
Thank you for collaboration

**Comment by ananth-iyer** [comment]
@jurvi can you share a screen video gif?
