### ISSUE TITLE
Mini search field looses focus after its JavaScript is initialized

### ISSUE THREAD

**Issue by krzksz** [magento/magento2#13988]
### Preconditions

1. Any Magento 2.x.x installation, e.g. http://magento2-demo.nexcess.net/

### Steps to reproduce

1. Open Magento 2 shop.
2. Focus mini search field before JavaScript manages to load and optionally start writing some query there.

### Expected result

1. The focus is maintained when the component is initialized.

### Actual result

1. After mini search component's JavaScript loads and initializes, search input loses focus and user has to focus it again.

As far as I understand this part of the code is responsible for above behavior: https://github.com/magento/magento2/blob/36bfa583f12ccf79c754920d6b6288e67fcc9961/app/code/Magento/Search/view/frontend/web/form-mini.js#L101
I suspect it was added to correctly toggle active classes attached to `focus` event by forcing the user to reselect input field. I'm creating PR which will make code check current active element and triggers `setActiveState` method if it is our component's input.

**Comment by magento-engcom-team** [comment]
@krzksz, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your report. 
The issue has been fixed in magento/magento2#13989 by @krzksz in 2.2-develop branch
Related commit(s):
 - [9eb3c6f5a00b12cde1b397bab983305acf568688](https://github.com/magento/magento2/commit/9eb3c6f5a00b12cde1b397bab983305acf568688)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your report. 
The issue has been fixed in magento/magento2#14180 by @mastiuhin-olexandr in 2.3-develop branch
Related commit(s):
 - [2f624a4852d0b0323b4ea88615859b3726f46da4](https://github.com/magento/magento2/commit/2f624a4852d0b0323b4ea88615859b3726f46da4)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @krzksz. Thank you for your report. 
The issue has been fixed in magento/magento2#17086 by @mageprince in 2.1-develop branch
Related commit(s):
 - [90f884f8bb5cdf803042ee65dbd9986cc6d094d1](https://github.com/magento/magento2/commit/90f884f8bb5cdf803042ee65dbd9986cc6d094d1)

The fix will be available with the upcoming 2.1.15 release.
