### ISSUE TITLE
Incorrect phpdoc should be Shipment\Item not Invoice\Item

### ISSUE THREAD

**Issue by ThisIsRuddy** [magento/magento2#13992]
Phpdoc references the return object as `Magento\Sales\Model\Order\Invoice\Item` but it should be `Magento\Sales\Model\Order\Shipment\Item`.

Causes incorrect type warnings in IDEs.

https://github.com/magento/magento2/blob/96b819215bc5cb3225c4f183a0090de0f280c907/app/code/Magento/Sales/Model/Order/Shipment/Item.php#L149

**Comment by magento-engcom-team** [comment]
@ThisIsRuddy, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ThisIsRuddy. Thank you for your report. 
The issue has been fixed in magento/magento2#14304 by @cream-julian in 2.3-develop branch
Related commit(s):
 - [79c1b4f79f6f95eea0ee079d601974fc410693bd](https://github.com/magento/magento2/commit/79c1b4f79f6f95eea0ee079d601974fc410693bd)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @ThisIsRuddy. Thank you for your report. 
The issue has been fixed in magento/magento2#14303 by @cream-julian in 2.2-develop branch
Related commit(s):
 - [564ab99f2b42aca948654adfd112bfdca8610757](https://github.com/magento/magento2/commit/564ab99f2b42aca948654adfd112bfdca8610757)

The fix will be available with the upcoming 2.2.5 release.

**Comment by ishakhsuvarov** [comment]
Hi @ThisIsRuddy. Thank you for your report. 
The issue has been fixed in magento/magento2#15619 by @dmytro-ch in 2.1-develop branch
Related commit(s):
 - [ab64a2c39358c6f37d27206a16272cc176a33abe](https://github.com/magento/magento2/commit/ab64a2c39358c6f37d27206a16272cc176a33abe)

The fix will be available with the upcoming 2.1.15 release.
