### ISSUE TITLE
modual not install

### ISSUE THREAD

**Issue by Drashtii** [magento/magento2#14003]
i m not install new modual in config.php file
please suggest proper document to solved this

**Comment by orlangur** [comment]
Hi @Drashtii, GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

Looks like you are looking for a way to enable module so that it appears in `config.php`, please check http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-enable.html#instgde-cli-subcommands-enable-disable on this.
