### ISSUE TITLE
"Use in Layered Navigation: Filterable (no results)" not working for `Price` attribute.

### ISSUE THREAD

**Issue by yogeshsuhagiya** [magento/magento2#14007]
Hello,

I'm trying to set **Filterable (no results)** for price attribute but it's not working.
There is below note for **Use in Layered Navigation** setting of product attribute at the backend.
**Can be used only with catalog input type Dropdown, Multiple Select and Price.**
So I hope it should work for Price attribute too.

### Preconditions
1. Magento 2.2.3
2. PHP 7.1.15
3. Apache/2.4.18 (Ubuntu)

### Steps to reproduce
1. Goto: Stores > Attributes > Product
2. Search price attribute and edit it.
3. In "Storefront Properties" tab, and set **Use in Layered Navigation** to **Filterable (no results)**
4. Go to category view page.
5. Apply any other filter like color, size etc except price.

### Expected result
1. All price range links will appear for all values, whether the number of results is zero or greater.

### Actual result
1. Appear only those price range links where the number of results is greater than zero. Other links are removed from layered navigation.

Without applying any filter: https://www.screencast.com/t/PWgwUqEQsWVI
After applying the filter: https://www.screencast.com/t/qj6H5Jq0

Thank you.

**Comment by magento-engcom-team** [comment]
@Yogeshks, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ashokramji** [comment]
I am working on this at #dmcdindia

**Comment by lewis-dan** [comment]
Hi,
I am working on this Issue.
Thanks,
Dan

**Comment by lewis-dan** [comment]
I am working on this at #dmcdindia”

**Comment by magento-engcom-team** [comment]
@lewis-dan thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by lewis-dan** [comment]
Hi, 
Just need to use the other attribute with "Filterable (No Results)" for both Search and Catalog pages.
Check the following screen shots - 
![image](https://user-images.githubusercontent.com/34798405/40268157-9eae7166-5b36-11e8-91fb-c223edd40f3e.png)

Only if there is no Results, then Price Attribute wont visible on Left Hand Layered Navigation.

![image](https://user-images.githubusercontent.com/34798405/40268164-d418970a-5b36-11e8-80cb-fd1142c6003b.png)

**Comment by ashokramji** [comment]
Hi Dan,
How to fix it....??
Please explain it.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks 
Could you please check the comment above?
Thanks

**Comment by yogeshsuhagiya** [comment]
Hello @magento-engcom-team ,
I agree with @lewis-dan that `Filterable (No Results)` working for other custom attributes but it's not working for `price` attribute for which I had opened this issue.

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vpodorozh** [comment]
Hello @Yogeshks - about your expected result from this issue: `All price range links will appear for all values, whether the number of results is zero or greater.` - I do think that it is not valid expectation.
**Reason**: the user does not need filters that will return the empty set of products.

However, this comment from magento back office could confuse: `Can be used only with catalog input type Yes/No, Dropdown, Multiple Select and Price.`
I'll just edit this comment and put a remark about `Price` attribute.

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your report. 
The issue has been fixed in magento/magento2#19044 by @vpodorozh in 2.2-develop branch
Related commit(s):
 - [52bfffc2d2f43891b27af2d6144c0b64be572f79](https://github.com/magento/magento2/commit/52bfffc2d2f43891b27af2d6144c0b64be572f79)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @Yogeshks. Thank you for your report. 
The issue has been fixed in magento/magento2#19037 by @vpodorozh in 2.3-develop branch
Related commit(s):
 - [e18df69004ef25f53ed927e953cc5fce0191bf84](https://github.com/magento/magento2/commit/e18df69004ef25f53ed927e953cc5fce0191bf84)

The fix will be available with the upcoming 2.3.1 release.
