### ISSUE TITLE
Why Report Bugs link not open in new tab?

### ISSUE THREAD

**Issue by webshouters** [magento/magento2#14010]
Why Report Bugs link not open in new tab?

It should be open in new tab(target="_blank").

![new-tab-link](https://user-images.githubusercontent.com/15726230/37154403-e639427c-2305-11e8-9a00-535f572d5e83.png)

**Comment by orlangur** [comment]
> It should be open in new tab(target="_blank").

No.

It is generally considered a good practice to let user decide whether a link should be opened in a new tab. So, pressing Ctrl+Click link is opened in new tab, pressing Shift+Click link is opened in new window and user is not forced to open a new tab or window.

**Comment by daniloargentiero** [comment]
Hi @orlangur,
This is useful because in this way you don't loose your currently opened admin page.

**Comment by orlangur** [comment]
@DaniloEmpire there is a Back button in browser to not lose an opened admin page.

Default behavior is opening the link in the same tab so such behavior is quite expectable for user.

**Comment by daniloargentiero** [comment]
@orlangur "Back button" in browser don't always keeps form's data.

A scenario for example:
1) Create a new product
2) Compile the form (it takes at least 5/10 minutes)
3) Click on "Report an Issue" (because you encounter an issue in that specific scenario)
4) Click on browser's "Back button" 
5) Result: an empty form. You have to refill form to replicate the scenario. This is boring and can leads developers to abandon the idea to send an issue.

In this case, Default behavior is not a good choice.

**Comment by orlangur** [comment]
> Click on "Report an Issue" 

User is aware that to open issue in new tab or window you need to press Ctrl/Shift + Click.

> Click on browser's "Back button"

In most cases you will see nonempty form (some data could be missed in tabs loaded via AJAX). Also, some modern browsers ask if user really wants to leave page as form data entered may be lost. A generic cross-browser mechanism could be implemented on Magento side to avoid data loss (show confirmation dialog when there is some unsaved form data).

Placing target=blank in random places is not a right way to improve user experience in 2k18.

**Comment by magento-engcom-team** [comment]
Hi @webshouters. Thank you for your report. 
The issue has been fixed in magento/magento2#14016 by @DaniloEmpire in 2.3-develop branch
Related commit(s):
 - [79e87b414972ff6c01bce1747bec4700455a23f8](https://github.com/magento/magento2/commit/79e87b414972ff6c01bce1747bec4700455a23f8)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @webshouters. Thank you for your report. 
The issue has been fixed in magento/magento2#14121 by @sidolov in 2.2-develop branch
Related commit(s):
 - [8cfffc1d479f88a09bdf84678e9b81531b275d7d](https://github.com/magento/magento2/commit/8cfffc1d479f88a09bdf84678e9b81531b275d7d)

The fix will be available with the upcoming 2.2.5 release.
