### ISSUE TITLE
Cart Sales Rule with negated condition over special_price does not work for configurable products

### ISSUE THREAD

**Issue by Filipe-Bicho** [magento/magento2#14020]
### Preconditions
1. magento 2.2.3
2. php 7.1.10
3. mariadb 10.1.24

### Steps to reproduce
0. Setup vanilla 2.2.3 with demodata (or use a similar existing store)
1. Enable the `special_price` for promo rule conditions: 
   1. Stores > Attributes > Product
   2. Search for and edit `special_price`
   3. Storefront Properties: Use for Promo Rule Conditions: Yes
   4. Save
2. create new cart sales rule:
   1. Marketing > Cart Price Rules
   2.  Add New Rule:
       1. Rule name = "Special Price Test"
       2. Website: select all
       3. Customer Groups: select all
       4. Coupon: "Specific Coupon"
       5. Coupon Code: "special"
       6. Actions: Discount Amount: "10"
       7. Actions: Apply the rule only to cart items matching the following conditions: "if **ALL** of these conditions are **FALSE**": "Special Price **greater than 0.01**"
       8. Leave all other fields to their defaults and save
3. In the front end, add a the child product of a configurable product to the cart, such that the child product has a special price set. This product should be the only one in the cart.
4. "View and Edit Cart" > "Apply Discount Code": `special`

### Expected result
1. the coupon is not accepted with the message `The coupon code "special" is not valid.`
2. no discount is applied

### Actual result
1. the coupon is accepted with the message `You used coupon code "special".`
2. a discount is applied

The intention with the above mentioned sales rule is to exclude already discounted products from further discounting via a coupon code.

**Comment by ktruehl** [comment]
The problem manifests itself in the rule validation mechanism. For configurable products both the associated and the parent product is handed to the `validate()` method in `Magento\Rule\Model\Condition\Product\AbstractProduct`. But for special prices the `special_price` attribute is not defined. So in `validate()` in `Magento\Rule\Model\Condition\AbstractCondition` the call `$model->getData($this->getAttribute())` will always return null for the parent product and thus validate to `false`. Thus price rule conditions using the `special_price` attribute will always validate to `false` for configurable products.

We have created a quickfix for this issue: [bugfix-GH11178-configurable_product_sales_rule_special_price_validation.2018-02-06.diff.zip](https://github.com/magento/magento2/files/1796196/bugfix-GH11178-configurable_product_sales_rule_special_price_validation.2018-02-06.diff.zip). It is only that, i.e. a quickfix. A more comprehensive fix would be to check `Magento\Rule\Model\Condition\Product\AbstractProduct::validate()` whether an attribute is defined at all for a specific product, and if not, to validate to `true`.

**Comment by magento-engcom-team** [comment]
@Filipe-Bicho, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sunilit42** [comment]
I am working on this at #dmcdindia

**Comment by novikor** [comment]
#kiev-cd

**Comment by VladimirZaets** [comment]
Hi @Filipe-Bicho. Thank you for your report. 
The issue has been fixed in magento/magento2#16342 by @novikor in 2.2-develop branch
Related commit(s):
 - [90b6803aab559cd0c345ab42d19bb712e4df8011](https://github.com/magento/magento2/commit/90b6803aab559cd0c345ab42d19bb712e4df8011)
 - [2717cb1729b6f1b61040f3eb1582eb1d60622893](https://github.com/magento/magento2/commit/2717cb1729b6f1b61040f3eb1582eb1d60622893)
 - [d2a0de83c0f73dd850925b4a70ab2e5cf233d74b](https://github.com/magento/magento2/commit/d2a0de83c0f73dd850925b4a70ab2e5cf233d74b)
 - [fae98c01e29ea9ca47eca00cf2081ede1f729ccb](https://github.com/magento/magento2/commit/fae98c01e29ea9ca47eca00cf2081ede1f729ccb)
 - [9a35b459f1b31b2b8d40c6597bd90ac9c5c865fe](https://github.com/magento/magento2/commit/9a35b459f1b31b2b8d40c6597bd90ac9c5c865fe)
 - [887ee4aa918340a5933c9923c334cef6b97d44eb](https://github.com/magento/magento2/commit/887ee4aa918340a5933c9923c334cef6b97d44eb)
 - [0c9aa81d514717a4761c716260130e87fb08980e](https://github.com/magento/magento2/commit/0c9aa81d514717a4761c716260130e87fb08980e)
 - [4e683378f6cf29f8117328ff512fbc749267e487](https://github.com/magento/magento2/commit/4e683378f6cf29f8117328ff512fbc749267e487)
 - [5b95b223b6bb3aa6ee292364486837a51e74ce31](https://github.com/magento/magento2/commit/5b95b223b6bb3aa6ee292364486837a51e74ce31)
 - [618f408b2af3ff6c541cdc90d110de0a5827a66a](https://github.com/magento/magento2/commit/618f408b2af3ff6c541cdc90d110de0a5827a66a)
 - [7c8482bccf6d6d55d89b743dc74f00278c9b8f95](https://github.com/magento/magento2/commit/7c8482bccf6d6d55d89b743dc74f00278c9b8f95)
 - [e7130bf7826f72c0ff73dae1240f2dc1a1ad7e05](https://github.com/magento/magento2/commit/e7130bf7826f72c0ff73dae1240f2dc1a1ad7e05)
 - [5a7e78af8c6838b8c141e6e1b861a37ac00b4b96](https://github.com/magento/magento2/commit/5a7e78af8c6838b8c141e6e1b861a37ac00b4b96)
 - [8d417ac4192cdddb191686c5de8b18e5cda99032](https://github.com/magento/magento2/commit/8d417ac4192cdddb191686c5de8b18e5cda99032)
 - [90ff989212c73ee31b75c06d1f9c14efae4715aa](https://github.com/magento/magento2/commit/90ff989212c73ee31b75c06d1f9c14efae4715aa)
 - [c52e0e856f5edb657867d65fcf88702eef00ca37](https://github.com/magento/magento2/commit/c52e0e856f5edb657867d65fcf88702eef00ca37)
 - [5c3154b665f1843ab8de50396a9fe739b021cea6](https://github.com/magento/magento2/commit/5c3154b665f1843ab8de50396a9fe739b021cea6)
 - [51adb9d86f671b4789f31338f83d48c000cb8053](https://github.com/magento/magento2/commit/51adb9d86f671b4789f31338f83d48c000cb8053)

The fix will be available with the upcoming 2.2.8 release.
