### ISSUE TITLE
Magento REST API, wrong condition for product list category filter

### ISSUE THREAD

**Issue by kamilszewczyk** [magento/magento2#14035]
### Preconditions

1. Magento 2.2.1

### Steps to reproduce

1. Access https://{magento_url}/rest/default/V1/products?store_id=1&searchCriteria[filter_groups][0][filters][0][field]=status&searchCriteria[filter_groups][0][filters][0][value]=1&searchCriteria[filter_groups][1][filters][0][field]=category_id&searchCriteria[filter_groups][1][filters][0][value]={csv_category_list}&searchCriteria[filter_groups][1][filters][0][condition_type]=in
Where {csv_category_list} is a comma separated list of category ids as per IN condition from http://devdocs.magento.com/guides/v2.2/rest/performing-searches.html

### Expected result

1. A list of enabled products assigned to any of the listed categories should be returned

### Actual result

1. A list of products assigned to first listed category is returned

After digging up, I found that 2.2.0 introduced SearchCriteria Unified Processing (internat ticket MAGETWO-56012), adding `Magento\Catalog\Model\Api\SearchCriteria\CollectionProcessor\FilterProcessor\ProductCategoryFilter` which is calling addCategoriesFilter method for a Product Collection.
Problem is that the value passed to the method is casted in array `$categoryFilter = [$conditionType => [$filter->getValue()]];` (notice the array around `$filter->getValue()`).

This further in processing is being passed to `Magento\Framework\DB\Adapter\Pdo\Mysql::prepareSqlCondition()` which for IN conditionType tries to explode a passed parameter into array, but only if the parameter is passed as string.

I manage to fix the issue by adding simple beforePlugin that explodes the value before it's passed to the `addCategoriesFilter` method.

**Comment by magento-engcom-team** [comment]
@kamilszewczyk, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ihor-sviziev** [comment]
@kamilszewczyk could you please create PR for fixing this issue?

**Comment by kamilszewczyk** [comment]
@ihor-sviziev - I'm planning to actually, creating proper PR requires more time that I had when created a simple plugin serving its purpose. Hopefully will get to it throughout the weekend

**Comment by magento-engcom-team** [comment]
Hi @kamilszewczyk. Thank you for your report. 
The issue has been fixed in magento/magento2#14048 by @kamilszewczyk in 2.2-develop branch
Related commit(s):
 - [3e776eeee5826f7619803398e6fd558f435b83b4](https://github.com/magento/magento2/commit/3e776eeee5826f7619803398e6fd558f435b83b4)
 - [e18055829508c858328069bda72a7e56e3f0604a](https://github.com/magento/magento2/commit/e18055829508c858328069bda72a7e56e3f0604a)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @kamilszewczyk. Thank you for your report. 
The issue has been fixed in magento/magento2#16742 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [9fb7323cd3952d9a92bc42bb1a180fe2df0775cd](https://github.com/magento/magento2/commit/9fb7323cd3952d9a92bc42bb1a180fe2df0775cd)
 - [69c9a63b1b1e79475546a1095daee0935ca31b7d](https://github.com/magento/magento2/commit/69c9a63b1b1e79475546a1095daee0935ca31b7d)
 - [11284467c033bccd5a685897b07c3d4237b2432f](https://github.com/magento/magento2/commit/11284467c033bccd5a685897b07c3d4237b2432f)

The fix will be available with the upcoming 2.3.0 release.
