### ISSUE TITLE
Coupon API not working for guest user

### ISSUE THREAD

**Issue by gnanasekaranl** [magento/magento2#14056]
Followed below steps,
1. Create cart for guest user URL: http://devsite.com/magento2.2/rest/all/V1/guest-carts

   Content-Type: application/json
   Method: POST
   Authorization Bearer Key: yfna0bkjnj3j8jcr42rk7a1f3391yy0c

   Request Parameters: NIL

   Response :
adf748e2e78b4cd4d7d3795a127bed97  (Generates Cart ID in response)
create coupon in backend and also by API
Apply this coupon to cartId
URL: http://devsite.com/magento2.2/rest/all/V1/guest-carts/adf748e2e78b4cd4d7d3795a127bed97/coupons/782OYX2VOEINUF08

   Content-Type: application/json
   Method: PUT
   Authorization Bearer Key: yfna0bkjnj3j8jcr42rk7a1f3391yy0c

   Request Parameters: NIL

   Response :
{
 "message": "Coupon code is not valid"
}
For check I have applied this coupon in front-end of website as a guest user its work. In API only its not working

**Comment by magento-engcom-team** [comment]
@gnanasekaranl, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
Coupon code also does not work for logged-in customer through webapi, on frontend it works fine.

magento-engcom-team any  updates?

**Comment by mgarciaebo** [comment]
I'm working on this #distributed-cd

**Comment by matkeupon** [comment]
So many critical erros on this thing...
How many years until this will strat to become useable ??

**Comment by mgarciaebo** [comment]
@matkeupon I have already found the problem and a possible solution. I will send a fix to the dev team (I'm an external contributor), so keep in touch because this could be solved soon. Regards!

**Comment by marcin-dykas** [comment]
#WroCD

**Comment by magento-engcom-team** [comment]
@Hypo386 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by VladimirZaets** [comment]
Hi @gnanasekaranl. Thank you for your report. 
The issue has been fixed in magento/magento2#15320 by @Hypo386 in 2.2-develop branch
Related commit(s):
 - [6ad9c03bead4c56831f08c1af13f7cd3a53b163a](https://github.com/magento/magento2/commit/6ad9c03bead4c56831f08c1af13f7cd3a53b163a)
 - [8b7bb58d4bd90d426d8166e304801ab04e06fa18](https://github.com/magento/magento2/commit/8b7bb58d4bd90d426d8166e304801ab04e06fa18)

The fix will be available with the upcoming 2.2.6 release.

**Comment by gnanasekaranl** [comment]
@VladimirZaets That's great.

**Comment by pascalckunz** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pascalckunz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pascalckunz, here is your [Magento instance](https://i-14056-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-14056-2-3-develop.engcom.dev.magento.com/admin](https://i-14056-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
Hi @gnanasekaranl. Thank you for your report. 
The issue has been fixed in magento/magento2#16562 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [1acd06f76508ecf46f87a477aff691e504549fb6](https://github.com/magento/magento2/commit/1acd06f76508ecf46f87a477aff691e504549fb6)
 - [2651be335ea19d68cdf0989694a35c70e44de45f](https://github.com/magento/magento2/commit/2651be335ea19d68cdf0989694a35c70e44de45f)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @gnanasekaranl. Thank you for your report. 
The issue has been fixed in magento/magento2#16782 by @gelanivishal in 2.1-develop branch
Related commit(s):
 - [03b7b5ec2b03cf6e48628d44083a385006bbf61d](https://github.com/magento/magento2/commit/03b7b5ec2b03cf6e48628d44083a385006bbf61d)
 - [bc749b0b7045ea1e275940f80cc164a53755988f](https://github.com/magento/magento2/commit/bc749b0b7045ea1e275940f80cc164a53755988f)

The fix will be available with the upcoming 2.1.16 release.
