### ISSUE TITLE
Import related products issue

### ISSUE THREAD

**Issue by estellehuang** [magento/magento2#14050]
I imported four related products for a product. The related products are showing in the frontend.But only two related products are showing in the backend. I have run index and cleared cache. But the issue is still exist.

**Comment by magento-engcom-team** [comment]
@estellehuang , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment]
@estellehuang, thank you for your report.
We've acknowledged the issue and added to our backlog. If You want to have Your issue resolved You may add to Your CSV file the related_position column with position numbers, that correspond to related products You want to export. They should be separated by coma.

**Comment by chrisgan** [comment]
@magento-engcom-team 

This is also a problem for upsell_skus and crossell_skus
The fix of adding a 'related_position' does fix the issue. Along with a upsell_position, and crosssell_position columns as required.

The problem comes if you are migrating data from M1. Mostly I saw the positions are either '0' or theres no value at all. So in these cases you have then create a position value for these.

Ideally M2 should assign a position value based on the order of the skus, unless a relevant _position column is included.

**Comment by roychandrasekhar** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@roychandrasekhar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by roychandrasekhar** [comment]
Can't reproduce during import in admin.

**Comment by magento-engcom-team** [comment]
@chrisgan If you think the issue is caused by migration we suggest reporting to https://github.com/magento/data-migration-tool

@roychandrasekhar Thank you for your research. Closing this ticket now.

**Comment by sidolov** [comment]
Hi @estellehuang. Thank you for your report. 
The issue has been fixed in magento/magento2#17885 by @hostep in 2.2-develop branch
Related commit(s):
 - [a3f1c384e77ea1e693b18462e82091cf72965269](https://github.com/magento/magento2/commit/a3f1c384e77ea1e693b18462e82091cf72965269)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @estellehuang. Thank you for your report. 
The issue has been fixed in magento/magento2#18207 by @hostep in 2.3-develop branch
Related commit(s):
 - [74e1ea92cb57d739d3552fa9b86c51a8d5d8cfe9](https://github.com/magento/magento2/commit/74e1ea92cb57d739d3552fa9b86c51a8d5d8cfe9)
 - [d5b6231a241ade0acf154f8e88de88714b8e5cff](https://github.com/magento/magento2/commit/d5b6231a241ade0acf154f8e88de88714b8e5cff)

The fix will be available with the upcoming 2.3.1 release.
