### ISSUE TITLE
Change zip code validation pattern for Japan

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#14072]
### Preconditions

1. magento 2.3.x
2. magento 2.2.x
3. magento 2.1.x
4. magento 2.0.x

### Steps to reproduce

1. Add one more item into cart
2. Proceed checkout step
3. Choose "Japan" for country
4. Set zip code like "123" or "123-4567"
5. If you set other pattern, you may get validation error message.

### Expected result

1. "1234567" or "123-4567" only can pass the validation. Since 1998, Japanese postoffice only uses 7 digits for zipcode.

### Actual result

1. 123 is not a valid pattern, but actually recognized as a valid pattern. 7 digits of number should be allowed instead of existing pattern_2.

**Comment by magento-engcom-team** [comment]
@HirokazuNishi , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by osrecio** [comment]
Working on it #distributed-cd

**Comment by magento-engcom-team** [comment]
@osrecio thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @HirokazuNishi. Thank you for your report. 
The issue has been fixed in magento/magento2#14300 by @osrecio in 2.3-develop branch
Related commit(s):
 - [79474caf9536ff1bea791af430b3eb039ffd2ef5](https://github.com/magento/magento2/commit/79474caf9536ff1bea791af430b3eb039ffd2ef5)
 - [1e735aa63fd468fd00898f30b219bf2a03bce960](https://github.com/magento/magento2/commit/1e735aa63fd468fd00898f30b219bf2a03bce960)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @HirokazuNishi. Thank you for your report. 
The issue has been fixed in magento/magento2#14299 by @osrecio in 2.2-develop branch
Related commit(s):
 - [6b6ce0a4166c5fe9bd140cfb0ca344ef3ee9aa97](https://github.com/magento/magento2/commit/6b6ce0a4166c5fe9bd140cfb0ca344ef3ee9aa97)
 - [af6bbfd4776304b222df8938ce8e55aee0b30736](https://github.com/magento/magento2/commit/af6bbfd4776304b222df8938ce8e55aee0b30736)

The fix will be available with the upcoming 2.2.5 release.
