### ISSUE TITLE
Malaysian (Malaysia) missing from locale list

### ISSUE THREAD

**Issue by superdav42** [magento/magento2#14089]
### Preconditions
1. Magento 2.2.3
2. PHP 7.1.11 
3. intl extension 1.1.0
4. ICU version 57.1

### Steps to reproduce
1. Go to Store Configuration page
2. Change locale to Malaysian (Malaysia)
3. It's not there!

### Expected result

1. Malaysian (Malaysia) is on the list of locales

### Actual result

1. It's not

Magento\Framework\Locale\Config has the code `ms_Latn_MY` for Malaysian (Malaysia) but \ResourceBundle::getLocales() returns `ms_MY` in Magento\Framework\Locale\TranslatedLists::_getOptionLocales() probably Config should be updated to support either code.

**Comment by orlangur** [comment]
@superdav42 you can try fix similar to https://github.com/magento/magento2/commit/ecaa2c01e1d4c57b86a95404b61046db6ae2d580 on your side and prepare a pull request if it works.

**Comment by magento-engcom-team** [comment]
@superdav42, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by osrecio** [comment]
Working on it #distributed-cd

**Comment by magento-engcom-team** [comment]
Hi @superdav42. Thank you for your report. 
The issue has been fixed in magento/magento2#14305 by @osrecio in 2.3-develop branch
Related commit(s):
 - [7081c47a7c197006dfd48a68e929d6b6e2d8e68d](https://github.com/magento/magento2/commit/7081c47a7c197006dfd48a68e929d6b6e2d8e68d)
 - [7df2162fabdda481b618ee6b7cdab9c20fb5004e](https://github.com/magento/magento2/commit/7df2162fabdda481b618ee6b7cdab9c20fb5004e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @superdav42. Thank you for your report. 
The issue has been fixed in magento/magento2#14306 by @osrecio in 2.2-develop branch
Related commit(s):
 - [1cd6d1b02abc62d0d8ceb055796d39bab6dda3a3](https://github.com/magento/magento2/commit/1cd6d1b02abc62d0d8ceb055796d39bab6dda3a3)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @superdav42. Thank you for your report. 
The issue has been fixed in magento/magento2#15927 by @dmytro-ch in 2.1-develop branch
Related commit(s):
 - [0658873f52db5e34049952eac2efdf009d3d8698](https://github.com/magento/magento2/commit/0658873f52db5e34049952eac2efdf009d3d8698)

The fix will be available with the upcoming 2.1.15 release.
