### ISSUE TITLE
Outdated package after upgrade  sjparkinson/static-review is abandoned

### ISSUE THREAD

**Issue by woshka** [magento/magento2#14138]
outdated package after upgrade

Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.

### Preconditions

1. magento 2.12
2. 

### Steps to reproduce

1. upgrade using composer
2. 
3. 

### Expected result

1. no warning

### Actual result

1. [Screenshot, logs]

**Comment by ishakhsuvarov** [comment]
Hi @woshka
Thank you for reporting.

There is a Pull Request which is going to fix it in `2.2.x` soon: https://github.com/magento/magento2/pull/14091

**Comment by magento-engcom-team** [comment]
Hi @woshka. Thank you for your report. 
The issue has been fixed in magento/magento2#14091 by @orlangur in 2.2-develop branch
Related commit(s):
 - [9cd24a119e477564b4f8135305ddbf78a489b827](https://github.com/magento/magento2/commit/9cd24a119e477564b4f8135305ddbf78a489b827)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @woshka. Thank you for your report. 
The issue has been fixed in magento/magento2#14368 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [485353020369fcd8812827d57047163e79da8819](https://github.com/magento/magento2/commit/485353020369fcd8812827d57047163e79da8819)
 - [632f89d6424f47db631b2cfb781e1ed6fd0c3216](https://github.com/magento/magento2/commit/632f89d6424f47db631b2cfb781e1ed6fd0c3216)

The fix will be available with the upcoming 2.3.0 release.
