### ISSUE TITLE
Why Magento2.x admin always go to Dashboard after session expire or logout instead or previous page?

### ISSUE THREAD

**Issue by iamckdev** [magento/magento2#14132]
Hi Team,

### Preconditions

1. Magento 2.2.3
2. Default theme default sample data

### Steps to reproduce

I am facing some critical redirection issue in magento 2 admin area.

This is working fine in magento 1.9.

I have checked in both Magento 1 or Magento 2.

There is no issue in Magento 1.9.x.

**A scenario for example:**

Suppose i am login in Magento 2 admin and open three tabs.

Tab 1. Products
Tab 2. Orders
Tab 3. Cache Management

**Step-1.** When i logout from cache management page then i was going to login page.

**Step-2.** Now i am refreshing first and second tabs then i was going to login page.

**Step-3.** After i am logged from second tab(Orders) then i was going to Dashboard area instead of Orders page.

**Step-4.** Now refresh first tab(Products) then i was going to Dashboard area instead of Products page.

Means, I was lost my previous state, Where We left off.

This issue fixed in Magento 1, you can check this case.

### Expected result

After login should redirect to previous state from where we left off instead of dashboard.

### Actual result
This always redirect to dashboard and lost previous state(page).

**Comment by paragpadsumbiya** [comment]
@chandrakeshkumar Yes its default behaviour of Magento 2. Whenever you login in Admin panel you always redirect toDashboard .When you refresh second page it also redirect to dashboard because it regenartes session and form key which you redirect to Admin . Yes i am agree with you that is should redirect to previous state from where we left off .

**Comment by paragpadsumbiya** [comment]
@chandrakeshkumar You need to follow guidelines to report issue here .
Please use the issue reporting guidelines to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:

Preconditions: Magento version
Steps to reproduce
Expected result
Actual result

Otherwise they will never check your issue .

**Comment by iamck07** [comment]
@paragpadsumbiya Thanks for your response, I have updated issue.. 

You can check same scenario with Magento 1.9.x, it's working fine(redirect to previous state from where you left off). Why it's not working with Magento 2. 

Please fix this.. Admin loss time to reopen again pages where this was left off.

**Comment by paragpadsumbiya** [comment]
@chandrakeshkumar Yes you are right .Now as your issue pass guidelines .Magneto team will consider this issue and raise ticket and will solve in next verison .
@orlangur What do you think ?

@magento-engcom-team can you please check this and update this as this is very critical issue .

**Comment by magento-engcom-team** [comment]
@chandrakeshkumar 
Thank you for your report. This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this. Otherwise you may submit Pull Request with the suggested changes.

**Comment by iamck07** [comment]
@magento-engcom-team 

This is not correct behavior you can check this issue in Magento 1.9.x. Why it's working fine in Magento 19.x, and not in Magento2. Please share this issue with your core development team for review..

**Comment by iamck07** [comment]
@sidolov, @orlangur and **UX** team What do you think? Please review this issue step by step. I am working on 3-5 projects in a one day.

I facing redirection issue every time when session expired or log out any tabs. Then all tabs automatically go to dashboard after login. and I need to open all tabs again. this is too much time taken the job.

Everything working fine in Magento 1.9.x version.

This is not correct behavior from the user's point of view.

Thanks
