### ISSUE TITLE
Allow to disable module via installer using enable_modules = all

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#14143]
When installing via the installer you can use the options `disable_modules` and `enable_modules`
How it works now is that you need to list all modules in the `enable_modules` list if you want to be able to disable a module for install.

### Preconditions
1. Magento 2.4

### Steps to reproduce
1. Use a cli command to install magento with option enable_modules = all and disable_module
```
bin/magento setup:install --base-url=http://magento.local/ \
--db-host=localhost --db-name=magento --db-user=root --db-password=root \
--admin-firstname=admin --admin-lastname=admin --admin-email=me@example.com \
--admin-user=admin --admin-password=example@password1 --language=en_US \
--use-rewrites=1 --backend-frontname admin \
--enable-modules='all' --disable-modules='Magento_Sitemap'
```

### Expected result
1. Install should not able modules listed in disable_modules. Eg. Magento_Sitemap

### Actual result
1. Install ignores disable_modules when option enable_modules = all is used.

**Comment by magento-engcom-team** [comment]
@PascalBrouwers, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by alexmorco** [comment]
I was also having an issue with my Magento 2 store, I was installing Magento on AWS, I couldn't figure out the issue and tried Cloudways managed platform, https://www.cloudways.com/en/magento-managed-cloud-hosting.php, I have installed through their platform that gone successfully without going technical or fixing files.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @adityayadav-cedcoss. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by realadityayadav** [comment]
#MM19IN

**Comment by orlangur** [comment]
@PascalBrouwers how does it work currently if you omit `--enable-modules='all'` ?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30151` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
