### ISSUE TITLE
Invalid scope or scope id

### ISSUE THREAD

**Issue by gawpo50** [magento/magento2#14167]
### Preconditions

1. Unable to load and save new logo image....get this error on save........Invalid scope or scope id
2. Magento version 2.2.0 thru 2.2.3

### Steps to reproduce

1. Login to backend
2. Click on Content->Configuration
3. Select store
4. Click upload logo image button
5. Choose logo image
6. Click Save button
7. Get error.....Invalid scope or scope id

### Expected result

1. I expect it to save and upload the new logo image

### Actual result

1. ![magento-error](https://user-images.githubusercontent.com/37498213/37566373-1c3a591a-2b08-11e8-86f8-188aef2b09b5.jpg)

1. Don't point me at GitHub or StackOverflow......no answers there

**Comment by gawpo50** [comment]
Have done several fresh re-installs of Magento 2.2.3 and get the same error each time when trying to upload a new store logo. So the problem is repeatable.

**Comment by nfourteen** [comment]
@gawpo50 I don't have a fresh install, so I couldn't test this. If you look at the URL, it should contain `edit/scope/stores/scope_id/1/` or the like. The `Magento\Theme\Controller\Adminhtml\Design\Config\Save` controller gets the scope parameter from the URL and then tries to load the `$desingConfigData` with that id. Before the data is loaded, there's a check to ensure there's a valid scope (this is where the error is coming from). 

I believe this is  correct for throwing the error in that there is no theme set in your case and therefore no theme to add the logo to within the design configuration. The error also may be occurring because the **Website** name has been changed (thus changing the scope) and the default theme configuration of the application can't be retrieved. Try explicitly setting a theme and see if the problem persists.

**Comment by gawpo50** [comment]
1. Website name has not changed
2. Have done several fresh installs of Magento
3. Using the default Luma theme on all store views
4. Still getting the same error

I don't have a clue what to do now

**Comment by nfourteen** [comment]
@gawpo50 I ran a `whois` on your site and saw you're using GoDaddy. This seems to be an issue on their end as per the following reported issues: [#14025](https://github.com/magento/magento2/issues/14025), [#13875](https://github.com/magento/magento2/issues/13875)

From what I see in your screenshot above, there are no URL params present. These have to be set in the URL, otherwise you'll keep getting the error. For this functionality to work correctly, a URL would look like:

https://domain.com/admin/theme/design_config/edit/scope/stores/scope_id/1/key/bunch-of-random-characters/

The **scope/stores/scope_id/1** part has to be in the request URL. I would contact GoDaddy as it looks like their cloud hosting configuration is re-writing the URL somehow, removing or hashing those parameters, and causing the error with application.

Edit: That part wouldn't be in the URL for the screenshot you have above. Can you click on Edit and take a screenshot there please?

**Comment by gawpo50** [comment]
I checked what you said above and this is the url I get from the store view....

https://domain_name/aaaaa/theme/design_config/edit/scope/stores/scope_id/1/key/3a83edab67a4557fea688f321f6b44b603460932a29c18719149535376ec4a12/

Have had Godaddy check their end extensively....they cannot find anything wrong there.

This is effecting any image file I try to upload form logo to product images.

I've run out of ideas to try.

**Comment by gawpo50** [comment]
![store-code](https://user-images.githubusercontent.com/37498213/37574907-034335a0-2b74-11e8-9393-12815b08333c.jpg)

Screenshot as you requested

**Comment by nfourteen** [comment]
Can you get a hold of the PHP error logs and see if anything is reported there? Also, if you have PhpMyAdmin, find the `core_config_data` table and run a search on `design/theme/theme_id` and see what rows are returned. Or, if you have access to the **SQL** tab, you can run `SELECT * from core_config_data WHERE path = 'design/theme/theme_id';`. Directions here: [http://support.hostgator.com/articles/specialized-help/technical/phpmyadmin/how-to-run-sql-queries-in-phpmyadmin](http://support.hostgator.com/articles/specialized-help/technical/phpmyadmin/how-to-run-sql-queries-in-phpmyadmin)

**Comment by gawpo50** [comment]
This is a screenshot of what got returned from the SQL Query:


![php-admin](https://user-images.githubusercontent.com/37498213/37576333-d43273c2-2b7b-11e8-93a8-12cc2f9c3222.jpg)

**Comment by nfourteen** [comment]
So with that I'm at a loss. The scope should be resolved and valid. The last thing would be the PHP error log. I have one last idea to check there. Search for `\Magento\Framework\App\ScopeResolverInterface` in them.

**Comment by gawpo50** [comment]
I have found a way around the scope id error. Not ideal but it works. I have to other problems which are:

1. Category images not being uploaded and saved...gives the error -> A technical problem with the server generated an error.

2. Paypal not working....gives error -> Payment gateway is unreachable.
Have installed the proper credentials from my paypal account, enabled solution. When I do a test purchase...I get the above error.

The rest of the site seems to be working as it should.

Any ideas / help would be appreciated, thanks.

**Comment by magento-engcom-team** [comment]
Hello @gawpo50. Thanks for reporting. As for the new issues You've just mentioned, please create a new ticket for each. As for the original issue if it's still actual for You, unfortunately we are not able to reproduce it. Here is a video about how we were trying to do that.
[Logo.zip](https://github.com/magento/magento2/files/1836728/Logo.zip)
Tell us if we have missed something essential. And please try to reproduce the issue using a webserver on a local machine on a clear fresh instance of Magento. Thank You.

**Comment by nfourteen** [comment]
@gawpo50 I'm not sure about the category images and Paypal issues—I feel these are probably GoDaddy related. I just updated a site on Nexcess hosting and tried a fresh install of 2.2.2 on my local computer. I didn't run into any of these issues.

**Comment by gawpo50** [comment]
I'm beginning to think the same also...that it is a Godaddy issue. Getting them to admit it though...will be pretty hard.

**Comment by ArjenMiedema** [comment]
Did you try this on a different server as well (i.e. your local installation or a server from another hosting provider) to see if you could reproduce it there? Just did a check on my local machine, which is a Mac OSX using Valet+ with PHP 7.0.27, and I could upload any image there using a supported file type.

**Comment by gawpo50** [comment]
The problem was the server host I was using....went to a different hosting package and all works now.

**Comment by magento-engcom-team** [comment]
So @gawpo50 we are closing this issue as it was caused not by Magento itself.
