### ISSUE TITLE
Remove use of setTimeout eval

### ISSUE THREAD

**Issue by jonathanKingston** [magento/magento2#14172]
### Preconditions
1. Using 2.3-devel

### Steps to reproduce

Call sites like:
- app/code/Magento/Integration/Controller/Adminhtml/Integration/LoginSuccessCallback.php
  - Should be replaced for `function () {...}`
- app/code/Magento/Ui/view/base/web/js/lib/view/utils/raf.js
  - Should throw if the callback isn't a function

This bug should audit if throwing causes issues in callsites that accept a string argument passed into `setTimeout` and also check if other call sites exist.

### Expected result
1. No strings passed to setTimeout

### Actual result
Magento uses strings in evaluation of setTimeout, this could escalate into being a security issue and will restrict the use of strict Content Security Policies.

**Comment by jonathanKingston** [comment]
Optionally this commit could also include adding `'use strict'` to all JS files and removing `arguments.callee`. Both `arguments.callee` and string eval prevent the use of strict mode.

**Comment by magento-engcom-team** [comment]
@jonathanKingston, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @jonathanKingston. Thank you for your report. 
The issue has been fixed in magento/magento2#14173 by @jonathanKingston in 2.3-develop branch
Related commit(s):
 - [e501f679ffb622160ff8b8c20ac60334ff93c89a](https://github.com/magento/magento2/commit/e501f679ffb622160ff8b8c20ac60334ff93c89a)
 - [0684b13d66bcbf47f46fcc439ae6dbdcf7efc0a8](https://github.com/magento/magento2/commit/0684b13d66bcbf47f46fcc439ae6dbdcf7efc0a8)

The fix will be available with the upcoming 2.3.0 release.
