### ISSUE TITLE
How to get products by category id in magento 2.2.1 ?

### ISSUE THREAD

**Issue by DKoctopus** [magento/magento2#14193]
Hello, I am working in Magento 2.2.1, I am trying to get product-collection of a category by its category id. Every time when i use to call using this example...

https://magento.stackexchange.com/questions/125086/get-product-collection-by-category-id-on-phtml-file-magento2

I always get an error.

**Comment by magento-engcom-team** [comment]
@DKoctopus , 
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by magento-engcom-team** [comment]
@DKoctopus, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
