### ISSUE TITLE
Transparent background becomes black for thumbnails of PNG into Wysiwyg editor...

### ISSUE THREAD

**Issue by jb-dg** [magento/magento2#14248]
Hi, 

![capture](https://user-images.githubusercontent.com/36449657/37770089-87144606-2dd3-11e8-982e-c9823ddcecbe.PNG)

A transparent background becomes black for thumbnails of PNG into Wysiwyg editor...
Issue solved ever since talk about it ? 
Thank's !

Config: Magento 2.2.1 & PHP 7.0

**Comment by magento-engcom-team** [comment]
@jb-dg , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by eduard13** [comment]
I'm working on this one.

**Comment by magento-engcom-team** [comment]
Hi @jb-dg. Thank you for your report. 
The issue has been fixed in magento/magento2#16733 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [453aa847a25b54bd83e596563b00e58afdcbfe3e](https://github.com/magento/magento2/commit/453aa847a25b54bd83e596563b00e58afdcbfe3e)
 - [8ad6bd61bc9ecbcefae5b65a29d3295227985df2](https://github.com/magento/magento2/commit/8ad6bd61bc9ecbcefae5b65a29d3295227985df2)
 - [31b1d0cb52689d91b1d0083cbc8a1aab78cd919a](https://github.com/magento/magento2/commit/31b1d0cb52689d91b1d0083cbc8a1aab78cd919a)
 - [fcb41339c3c624c958f20022c376cdf767c8e65b](https://github.com/magento/magento2/commit/fcb41339c3c624c958f20022c376cdf767c8e65b)
 - [48607aa5dcb308a27994f35aaf330e631d9a0c8b](https://github.com/magento/magento2/commit/48607aa5dcb308a27994f35aaf330e631d9a0c8b)
 - [b10a9f9262c1451dd3a29483ef44172e8a883a32](https://github.com/magento/magento2/commit/b10a9f9262c1451dd3a29483ef44172e8a883a32)
 - [c37fbef620f111f1e73e89cf4960fce18e1558e4](https://github.com/magento/magento2/commit/c37fbef620f111f1e73e89cf4960fce18e1558e4)
 - [de55247522cc2220b54b9c5889bdf007532a7175](https://github.com/magento/magento2/commit/de55247522cc2220b54b9c5889bdf007532a7175)
 - [ce18fd28f016b404d3e04fa613c33055389dbd0e](https://github.com/magento/magento2/commit/ce18fd28f016b404d3e04fa613c33055389dbd0e)
 - [4e0348db3f9211cbd25be1bf83979a648c41f30b](https://github.com/magento/magento2/commit/4e0348db3f9211cbd25be1bf83979a648c41f30b)
 - [bc697d97dd32dddb56a6b60eacf2463bdf052609](https://github.com/magento/magento2/commit/bc697d97dd32dddb56a6b60eacf2463bdf052609)
 - [bfeba59b3ea0bbd09193b8b5ff551ff661d22254](https://github.com/magento/magento2/commit/bfeba59b3ea0bbd09193b8b5ff551ff661d22254)
 - [4f4a8a1d5327cff9b897fd429b0dd5279029196a](https://github.com/magento/magento2/commit/4f4a8a1d5327cff9b897fd429b0dd5279029196a)

The fix will be available with the upcoming 2.2.7 release.

**Comment by sidolov** [comment]
Hi @jb-dg. Thank you for your report. 
The issue has been fixed in magento/magento2#17855 by @eduard13 in 2.1-develop branch
Related commit(s):
 - [99eb5213ac544f919bc2e3acb49ba1834c9b7ac2](https://github.com/magento/magento2/commit/99eb5213ac544f919bc2e3acb49ba1834c9b7ac2)

The fix will be available with the upcoming 2.1.16 release.

**Comment by magento-engcom-team** [comment]
Hi @jb-dg. Thank you for your report. 
The issue has been fixed in magento/magento2#17857 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [ead882db36d57ce1bffb31e441481bec2d93d14d](https://github.com/magento/magento2/commit/ead882db36d57ce1bffb31e441481bec2d93d14d)

The fix will be available with the upcoming 2.3.0 release.

**Comment by alrururu** [comment]
same issue with .gif images when images are imported or added via product editor
![2019-10-01 19_13_30-CompatWindow](https://user-images.githubusercontent.com/56052517/66007164-546e3900-e47f-11e9-868e-ff0da28f99bb.png)
