### ISSUE TITLE
Magento\Email\Model\Template::getProcessedTemplate() with 1 too many params

### ISSUE THREAD

**Issue by fooman** [magento/magento2#1424]
The getProcessedTemplate() method is called here https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/Template.php#L649

    $text = $this->getProcessedTemplate($this->_getVars(), true);

vs the actual method in the same class:

    public function getProcessedTemplate(array $variables = [])

I believe this might be a copy & paste issue since the Newsletter module has this

    public function getProcessedTemplate(array $variables = [], $usePreprocess = false)

The extra param carries through to here https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Block/Adminhtml/Template/Preview.php#L73 as well.

**Comment by rganin** [comment]
Overloaded param is never used and does not cause any issue, created a ticket MAGETWO-39428

**Comment by vpelipenko** [comment]
@fooman, internal ticket is created, but your pull request is always welcome.

**Comment by arkadiych** [comment]
@fooman, The class with excessive parameters mentioned here:
> The getProcessedTemplate() method is called here 
> https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/Template.php#L649
> ```
> $text = $this->getProcessedTemplate($this->_getVars(), true);
> ```

has already been refactored and the parameters list has been fixed in https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/Template.php#L375 
in commit https://github.com/magento/magento2/commit/42af021fc56a255e5264612050a4560966a73d9f .
There are no other usages of this method with multiple parameters.

**Comment by mazhalai** [comment]
@fooman since the code has been refactored, closing this as wont fix.
