### ISSUE TITLE
/vendor/magento/module-configurable-product/Model/Product/Type/VariationMatrix.php on line 43

### ISSUE THREAD

**Issue by forwells** [magento/magento2#14240]
magento2 
/vendor/magento/module-configurable-product/Model/Product/Type/VariationMatrix.php on line 43
### Preconditions

1. magento 2.2.2

the configurable products edit error
### Steps to reproduce

1. add a configrable products
2. save 
3. do some attributes options
### Expected result

1. it works normally
### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/32950945/37746610-055dd34c-2db6-11e8-9864-f71881496ec9.png)

but it tell me a offset error~
magento tell me "Notice: Undefined offset: 0 in /var/www/magento2/vendor/magento/module-configurable-product/Model/Product/Type/VariationMatrix.php on line 43"

**Comment by magento-engcom-team** [comment]
@dearmatta , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by forwells** [comment]
Somehow this problem has arisen, but so far, it has not found that problem again.

**Comment by elfeffe** [comment]
I have created a pull request for this. I was having the same problem.
https://github.com/magento/magento2/pull/24659

**Comment by magento-engcom-team** [comment]
Hi @Low-config. Thank you for your report. 
The issue has been fixed in magento/magento2#24659 by @elfeffe in 2.3-develop branch
Related commit(s):
 - [bff262dc6a13da40fadb86d6afc68e4002349bdd](https://github.com/magento/magento2/commit/bff262dc6a13da40fadb86d6afc68e4002349bdd)
 - [d16dd4cacae81fac4ead4629e32ad85c829c31c0](https://github.com/magento/magento2/commit/d16dd4cacae81fac4ead4629e32ad85c829c31c0)
 - [44377673d3c7591fd2461bf421d91f9a3a66ae49](https://github.com/magento/magento2/commit/44377673d3c7591fd2461bf421d91f9a3a66ae49)

The fix will be available with the upcoming 2.3.4 release.

**Comment by katesuykovskaya** [comment]
@magento-engcom-team the condition to reproduce is - when creating configurable product you need to choose an attribute, that is not present in attribute set, that future simple products will be created

**Comment by magento-seis10** [comment]
This is still an issue for 2.3.5-p2

**Comment by usuyukiso** [comment]
reproduced for M2.4.3 and 2.4.4-p1

**Comment by duckchip** [comment]
Reproduced on 2.3.7-p4 @magento-engcom-team this ticket should be reopened
