### ISSUE TITLE
incorrect db user

### ISSUE THREAD

**Issue by woakley** [magento/magento2#14264]
Magento 2.2.3

Copied working site to a new account
changed DB detail in env.php
cleared var folder
recompile
redeploy

add image to product

### Expected result
image is added

### Actual result
SQLSTATE[42000]: Syntax error or access violation: 1142 TRIGGER command denied to user 'OLDUSER'@'localhost' for table 'catalog_product_entity_media_gallery', query was: INSERT INTO `catalog_product_entity_media_gallery` (`attribute_id`, `value`, `media_type`) VALUES (?, ?, ?)

Magento is trying to use the DB details from the old account even though I have cleared everything I can think of that might have contained these old details.

Everything else seems to work just as expected frontend and backend

**Comment by woakley** [comment]
So what do I do to get G1 passed?

**Comment by dmanners** [comment]
Hi @woakley you can use https://github.com/magento/magento2/wiki/Magento-Issue-Gates#gate-1---automatic-verification to see what needs to be in an issue report to get a G1 Pass. My guess is that as the issue is not using the complete issue template there are some parts that the system cannot pick up automatically.

**Comment by s-hoffman** [comment]
Hi, I ran into this issue yesterday and determined the root cause.
Please see #14401 Trigger Removal on Mview Subscription Change

**Comment by woakley** [comment]
Thanks both, really helpful :)

**Comment by magento-engcom-team** [comment]
@woakley Closing this ticket then, as #14401 has more details.
Thanks.
