### ISSUE TITLE
Image zoom pinch on the product page doesn't work in iOS/Safari

### ISSUE THREAD

**Issue by chernenm-zz** [magento/magento2#14261]
### Preconditions
2.2.0, 2.2.2, 2.2.5

### Steps to reproduce
1. Open Safari browser
2. Open a product page with images. (E.g.: sample-data product *Circe Hooded Ice Fleece*)
3. Click on product image
4. Try to pinch an image in the opened popup

### Expected result
Only image should be zoomed. Try the same test case in Chrome browser and you will see how it should work.

### Actual result
Whole page is zoomed

*Original ticket*:
MAGETWO-89033

**Comment by ishakhsuvarov** [comment]
Closing. Should be reopened in the scope of https://github.com/magento/up-for-grabs

**Comment by magento-engcom-team** [comment]
@chernenm, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
