### ISSUE TITLE
Quick search fires error

### ISSUE THREAD

**Issue by jonathanKingston** [magento/magento2#14274]
## Preconditions
1. Magento 2.3-develop branch

### Steps to reproduce
1. Type a term into the quick Ajax search field (`#search`) that doesn't exist in the database
2. Press Home keyboard key

### Expected result
1. No error

### Actual result
1. TypeError: this._getFirstVisibleElement(...).addClass is not a function

**Comment by magento-engcom-team** [comment]
@jonathanKingston, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by drashmk** [comment]
I’m working on it #distributed-cd

**Comment by magento-engcom-team** [comment]
@drashmk thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @jonathanKingston. Thank you for your report. 
The issue has been fixed in magento/magento2#14301 by @drashmk in 2.3-develop branch
Related commit(s):
 - [bd47df7d9fc167a24c9e0c8613d6a4b05dd9cc74](https://github.com/magento/magento2/commit/bd47df7d9fc167a24c9e0c8613d6a4b05dd9cc74)
 - [98be34bd3e5308c31a3ef51980bc2dc0c89549eb](https://github.com/magento/magento2/commit/98be34bd3e5308c31a3ef51980bc2dc0c89549eb)
 - [a5252dec47b32ffd95c46d9270c3dbe56f356d73](https://github.com/magento/magento2/commit/a5252dec47b32ffd95c46d9270c3dbe56f356d73)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @jonathanKingston. Thank you for your report. 
The issue has been fixed in magento/magento2#14839 by @julienanquetil in 2.2-develop branch
Related commit(s):
 - [0d7f6fe3e2a8056b55f803295090bf6d5b926e4a](https://github.com/magento/magento2/commit/0d7f6fe3e2a8056b55f803295090bf6d5b926e4a)
 - [fbf980b5945863850be2e51e3b3b9db1fa85bc74](https://github.com/magento/magento2/commit/fbf980b5945863850be2e51e3b3b9db1fa85bc74)
 - [8ae41761fd0ccc7a3c120bb43e001b62f74bce5f](https://github.com/magento/magento2/commit/8ae41761fd0ccc7a3c120bb43e001b62f74bce5f)

The fix will be available with the upcoming 2.2.5 release.
