### ISSUE TITLE
Exclude items from Cart Price Rule which have already Catalog Price Rule

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#14281]
### Preconditions

1. Magento 2.1.7, PHP 7.X, MySQL 5
2. Nginx

### Steps to reproduce

1. Set **Catalog Price Rule** for some **SKU's** belongs to the Category **X**
2. Set **Cart Price Rule** for the Category **X** and add a coupon code **Test** to this
3. Now add two items to the cart, one have Catalog Price Rule applied and another without it.
4. Go to the cart and apply the coupon code Test

### Expected result

1. Coupon code is only applied to the item don't have Catalog Price Rule 

### Actual result

1. Coupon is applied to both the products

**Comment by tkacheva** [comment]
@RishabhRkRai do you use _Discard subsequent rules_ for catalog rule? 

http://docs.magento.com/m2/ce/user_guide/marketing/price-rules-catalog.html

**Comment by rishabhrkrai** [comment]
@tkacheva I do that. I want to exclude the Catalog rules products form Cart Price rule.

**Comment by magento-engcom-team** [comment]
Hello @RishabhRkRai. Thanks for reporting. You see the Cart Price Rules and Catalog Price Rules are mutually independent. And it's quite logical, otherwise there would be no reason to create different Rule types - it would be enough just to have a Price Rule in the whole and everything else could be managed by the condition options it would offer. So if You have a Cart Price Rule for category X it will affect all the products that belong to that category no matter whether there already are any Catalog Price Rules for them or no. There are plenty of variations how to build marketing rules using different conditions in Magento, so You need to form Your rules in some other way.

**Comment by magento-engcom-team** [comment]
@RishabhRkRai we are closing this issue as it is an expected behavior for Magento. Thank You.
