### ISSUE TITLE
Possible to press the "Previous" button while in the first step of the installation

### ISSUE THREAD

**Issue by ArjenMiedema** [magento/magento2#14307]
### Preconditions
1.  PHP 7.0.27
2. Magento 2.2-develop

### Steps to reproduce
1. Clone the Magento 2 repository from Github on your local environment
2. Open your browser to start the installation process
3. Click the "Agree and Install Magento" button
4. When in the first step of the installation process, click the "Previous" button

### Expected result
1. It's impossible to go to the previous step when you're on the first step 

### Actual result
1. You can press the "Previous" button when on the first step of the installation process, which brings you to the final step of the checkout

**Comment by magento-engcom-team** [comment]
@ArjenMiedema thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ArjenMiedema. Thank you for your report. 
The issue has been fixed in magento/magento2#14309 by @ArjenMiedema in 2.2-develop branch
Related commit(s):
 - [9668ae7022f007eb987b0e92105582655645f3e0](https://github.com/magento/magento2/commit/9668ae7022f007eb987b0e92105582655645f3e0)
 - [1bf7685c2d9b8559402f8a0bc06e753c3e5ce828](https://github.com/magento/magento2/commit/1bf7685c2d9b8559402f8a0bc06e753c3e5ce828)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @ArjenMiedema. Thank you for your report. 
The issue has been fixed in magento/magento2#14460 by @mastiuhin-olexandr in 2.3-develop branch
Related commit(s):
 - [14f522799bca20f889862fb8093957dba138b49b](https://github.com/magento/magento2/commit/14f522799bca20f889862fb8093957dba138b49b)
 - [1214c4f82885674781e3366789e9717481360ee2](https://github.com/magento/magento2/commit/1214c4f82885674781e3366789e9717481360ee2)

The fix will be available with the upcoming 2.3.0 release.
