### ISSUE TITLE
backend change language  invalid 

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1431]
backend change language  invalid bug

**Comment by vpelipenko** [comment]
Hi, @LifeAsBook. What is wrong there? Could you give more details?

**Comment by LifeAsBook** [comment]
![20150701234527](https://cloud.githubusercontent.com/assets/10986726/8458749/540d282e-204b-11e5-818c-74aaa228e406.png)
change Interface Locale invalid

**Comment by mazhalai** [comment]
@LifeAsBook What version of Magento are you using? Can you please show steps to reproduce this issue?

**Comment by LifeAsBook** [comment]
version 0.74.0-beta15 
step:
  admin->Account Setting->Interface Locale   to change language invalid

**Comment by xcomSteveJohnson** [comment]
Hi, I'm not the expert so someone else might be able to elaborate.

As shipped, Magento provides some language packages: https://github.com/magento/magento2/tree/develop/app/i18n/magento

Chinese is not one of them, which is why the UI doesn't change to Chinese as you noted. However, you can try Deutsch and you'll notice it works. (Not all UI elements are translated, however.)

A Magento *language package* is a set of translations; you can find more info here: http://bit.ly/1Gk7O0X

We also provide the ability for you to create your own language package: http://bit.ly/1AMEbEc

Let us know if you need more information.

**Comment by LifeAsBook** [comment]
Thank you, I understand

**Comment by joanhe** [comment]
@LifeAsBook Do you have any more questions regarding this issue? If not, could you please close it? Thanks.

**Comment by LifeAsBook** [comment]
@joanhe ok, are you chinese girl?
