### ISSUE TITLE
zxcvbn.js included in merged.js

### ISSUE THREAD

**Issue by cannycookie** [magento/magento2#14357]
zxcvbn.js is not included in our theme, but when js bundling and merging is enabled this 850Kb file is added to the merged script.

### Preconditions
1. Magento 2.2.1
2. Custom Theme

### Steps to reproduce
1. Enable a custom theme with no reference to password-strength-indicator or zxcvbn.js
2. create override for  magento-customer/view/frontend/requirejs-config.js and remove 
``
passwordStrengthIndicator: 'Magento_Customer/js/password-strength-indicator',
zxcvbn: 'Magento_Customer/js/zxcvbn',
``
2. Enable JS Bundling and merging
3. Enable production mode

### Expected result
1.  zxcvbn.js should not be included

### Actual result
1.  Search minified script and find 122 instances of fuck

**Comment by ghost** [comment]
@cannycookie, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by DanielRuf** [comment]
Afaik this is part of login and others things which use it for calculating the password strength.

You should be able to remove the js file according to the docs.

**Comment by bery** [comment]
I did some testing and I was not able to remove the file as it is merged via require js config. When merging is disabled, all works fine, yet when merging is enabled, the library is included on all pages.

**Comment by DanielRuf** [comment]
Mh, maybe because it is not bound to a specific selector?
https://github.com/magento/magento2/blob/19eeeb99f350c05ab416344f5e997ffb64822e09/app/code/Magento/Customer/view/frontend/requirejs-config.js

At least it is excluded in the default themes:
https://github.com/magento/magento2/blob/c896f2c07c4bf61481aad75bab2467832594b546/app/design/frontend/Magento/blank/etc/view.xml

Did you test it with a fresh Magento test instance?

I guess you need the exclude in the view.xml file to remove it and prevent that it is bundled.

**Comment by DanielRuf** [comment]
You have to explicitely exclude it from bundling (which is done with all files which are loaded with requireJS):

https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/js-bundling.html

See https://github.com/magento/magento2/blob/c896f2c07c4bf61481aad75bab2467832594b546/app/design/frontend/Magento/blank/etc/view.xml for reference.

**Comment by RaphaelBronsveld** [comment]
Hi,

It seems that excluding via the view.xml file only works for directories. We copied the exclude node from the Blank theme to our custom theme, but the libraries are still in the bundled+merged+minified js.

For example:
- "jquery.min.js"
- "moment-timezone-with-data.js"
- "moment.js"
- "Magento_Customer/js/zxcvbn.js"

Are still in the bundled javascript. 

This is on Magento 2.2.5.

Anyone else experiencing this?

**Comment by gwharton** [comment]
Adding this to the exclude list in view.xml gets rid of moment-timezone-with-data.min.js

`<item type="file">Lib::moment-timezone-with-data.js</item>`

and adding

`<item type="file">Magento_Customer::js/zxcvbn.min.js</item>`

gets rid of zxcvbn (note including the .min.

**Comment by RaphaelBronsveld** [comment]
> Adding this to the exclude list in view.xml gets rid of moment-timezone-with-data.min.js
> 
> `<item type="file">Lib::moment-timezone-with-data.js</item>`
> 
> and adding
> 
> `<item type="file">Magento_Customer::js/zxcvbn.min.js</item>`
> 
> gets rid of zxcvbn (note including the .min.

Based on the https://devdocs.magento.com/guides/v2.2/performance-best-practices/configuration.html#bundling-tips documentation, I disabled merging. Only minify + bundling is enabled.

The zxcvbn (with min) worked for me. The timezone data without did not. I included .min in the exclude and it worked.

Same with `<item type="file">Lib::jquery/jquery-ui-1.9.2.js</item>`, this doesn't work for me, but `<item type="file">Lib::jquery/jquery-ui-1.9.2.min.js</item>` does. 

So I assumed, adding .min. will fix this for several js files, but..

Blank luma theme adds this: `<item type="file">Lib::jquery/jquery.min.js</item>`. And this is still included in one of the bundles?

**Comment by adifucan** [comment]
Hi @cannycookie!
I created a custom theme for Magento 2.3.-develop. This theme extends luma theme. It has its custom theme requirejs-config without passwordStrengthIndicator & zxcvbn. I enabled JS merging and bundling and switched to production mode. 
And I could not find zxcvbn library in bundles and in merge file either. zxcvbn library is requested separately/asynchronously when I register custom, edit customer's password or reset customer's password.
It's because zxcvbn library is excluded from bundles in app/design/frontend/Magento/luma/etc/view.xml in exclude node.
So, may be this bug is already fixed in 2.3-develop. Or maybe your custom theme does not extend blank or luma themes and you do not specify zxcvbn library in exclude node in your app/design/frontend/Vendor/theme-name/etc/view.xml file. exclude node in view.xml defines the list of resources that should not be bundled.

**Comment by adifucan** [comment]
Please, reopen this issue with more details if it still occurs.

**Comment by magento-engcom-team** [comment]
Hi @cannycookie. Thank you for your report. 
The issue has been fixed in magento/magento2#24506 by @hostep in 2.3-develop branch
Related commit(s):
 - [41ef34feca73eea48f3dd1744bce529d36909c91](https://github.com/magento/magento2/commit/41ef34feca73eea48f3dd1744bce529d36909c91)
 - [cbe25f4960b59feed344eebee25e3dbe2f3efaaa](https://github.com/magento/magento2/commit/cbe25f4960b59feed344eebee25e3dbe2f3efaaa)

The fix will be available with the upcoming 2.3.4 release.
