### ISSUE TITLE
Impossible to Filter Collection by `null` Attribute Value

### ISSUE THREAD

**Issue by maxbucknell** [magento/magento2#14355]
When loading an EAV collection, such as a product collection, it is impossible to filter a collection by specifying that the value of the attribute is `null`. This is because the collection generates an `INNER JOIN`, when it should be generating at least a `LEFT JOIN`.

I found this issue when researching magento/magento2/14312

### Preconditions

This was found on `2.3-develop`, and I haven't checked, but my suspicion is that it will fail on all versions of Magento 2.

### Steps to reproduce

I have written a failing unit test for this: https://github.com/maxbucknell/magento2/commit/b2e290472a9f76e62ac40cc73867e71591aa1c25

### Expected result

This query should find the product with the special price of `null`.

### Actual result

Because of the `INNER JOIN`, `$productCount` is `0`.

**Comment by magento-engcom-team** [comment]
Hi @maxbucknell. Thank you for your report. 
The issue has been fixed in magento/magento2#14356 by @maxbucknell in 2.3-develop branch
Related commit(s):
 - [7a3ea4ef23584d3dfdd1f414dad69858c3c46ac9](https://github.com/magento/magento2/commit/7a3ea4ef23584d3dfdd1f414dad69858c3c46ac9)
 - [4589cb0ad644290e5e8d968b275bc5e2357bb349](https://github.com/magento/magento2/commit/4589cb0ad644290e5e8d968b275bc5e2357bb349)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment]
The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by skeutmeier** [comment]
is this bug reintroduced?

I just tried to get some orders in 2.4.6-p5
` ->addFieldToFilter('email_sent', ['eq' => NULL])`
returns 0 orders (incorrect), but 
`->addFieldToFilter('email_sent', array('null' => true))`
returns the correct orders.
