### ISSUE TITLE
Images Not Replaced via CSV Import

### ISSUE THREAD

**Issue by itsabe** [magento/magento2#14398]
### Preconditions
1. Magento 2.2.2
2. CSV file with columns [sku], [additional_images] and one row of values
3. Current images of sku is A, B, C, D.
4. My CSV file contains images A, B, E, F, G

### Steps to reproduce
1. Create CSV file
2. First column is sku with one existing sku in catalog.
3. Second column is additional_images with comma separated values of relative path.
4. Import file into Magento with Add/Update Import Behavior.

### Expected result
1. Images of the sku should be A, B, E, F, G. (The images I have in my CSV file).

### Actual result
1. Images of the sku are A, A, B, C, D, E, F, G. All the images got appended to the product.

I know there is a Import Behavior of Replace but that recreates the whole item. Is there a way to do so without recreating the item?

**Comment by ghost** [comment]
@itsabe, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by erfanimani** [comment]
Hi @agorbulin , was there any update on this?

**Comment by erfanimani** [comment]
Product imports should be idempotent and declarative. Importing the same CSV twice should not result in unwanted side-effect, as clearly is the case now.

I do want to add that to do this properly is quite a big job and requires Magento to keep track of file metadata such as a hash of uploaded images. Then it can compare the hash with a hash of the newly uploaded file and determine whether it should delete the previous one and upload the new one, or just leave things as-is. Simply blasting away all images on import does not scale.

**Comment by agorbulin** [comment]
Hi @erfanimani 
unfortunately, but I'm not investigation this issue.

**Comment by pemann** [comment]
What if there were a selection between replacing all product images with the ones from csv, or adding new images but not deleting old ones? It could be easy as one more column to csv or one more checkbox to the import form.

**Comment by erfanimani** [comment]
@pemann I'm just thinking, there are four situations:

1. Filename changed, image changed
2. Filename changed, image is still the same
3. Filename is the same, image changed
4. Filename is the same, image is still the same

I was thinking about things like filename comparisons and hash comparisons, but I think the only option is a hash check and ignore things like filename changes because it would be too hard. There's a big downfall though, and I'm not sure if it's acceptable. 

I propose the following: During the import we load the existing product and it's images. We create an array with md5 hashes. Then we create an array with md5 hashes of the images specified in the import CSV. We do a comparison, and we know which ones to leave alone and which ones to delete. One downfall of this approach is that you could rename an existing image and do another upload, but the filename in Magento will not change because the hashes have been kept the same.

I'll experiment with this at work tomorrow and maybe suggest this in a PR.

Your approach is not really ideal either @pemann because on a high volume production site you wouldn't want to blast away all images. Or maybe sites that have high volume are advised to use a third party importer... Also it would mean that if you run imports regularly, the filenames of all images would keep changing forever, and any images URLs externally referenced would stop working.

**Comment by erfanimani** [comment]
Added PR here: https://github.com/magento/magento2/pull/21146

**Comment by jg-development** [comment]
@agorbulin 
Is there any updates on this issue?

**Comment by agorbulin** [comment]
Hello.
I do not check the issue. Is it still actual?

**Comment by template-provider** [comment]
Yes, this is still an issue

**Comment by atIOCrON** [comment]
Has there been any update on this?

**Comment by engcom-Oscar** [comment]
Hi @itsabe , I have rechecked this issue on the latest 2.4-develop Magento instance. How I see, it is expected behavior when you select Products Import - Add/Update - new images are added to your product, but old ones remains there as well. It also confirmed here in documentation: https://docs.magento.com/user-guide/system/data-import.html.  If your have more details of the problem, please update ticket description, otherwise this ticket is not valid and need to be closed.

**Comment by HenKun** [comment]
@engcom-Oscar Where exactly is stated that product images add up instead of being replaced? Type "Add/Update" means "Add or (if present) update products". Not "Combine old and new attribute values". At least as far as my logic goes. Furthermore there is another ticket concerning the same issue: https://github.com/magento/magento2/issues/21885 and already a PR, but just nothing happens with this issue. I think it would be a step backwards if the (quite old) ticket is closed and everything must be started from the beginning.

**Comment by magento-engcom-team** [comment]
Hi @itsabe. Thank you for your report. 
The issue has been fixed in magento/magento2#26713 by @PieterCappelle in 2.4-develop branch
Related commit(s):
 - [912b3f7737259d5977ce3fa64781a3280c712bfe](https://github.com/magento/magento2/commit/912b3f7737259d5977ce3fa64781a3280c712bfe)
 - [ffdb34112974d74aa2d72b5fd441641e85234ad3](https://github.com/magento/magento2/commit/ffdb34112974d74aa2d72b5fd441641e85234ad3)
 - [eb8607c5ab62f10e519e20810da60a2755c34d58](https://github.com/magento/magento2/commit/eb8607c5ab62f10e519e20810da60a2755c34d58)
 - [e4812b842f300af4f45dd9d6ed3a6faaa2143a38](https://github.com/magento/magento2/commit/e4812b842f300af4f45dd9d6ed3a6faaa2143a38)
 - [d03b223d33cc511b482f83c2666469c2e9c19e3f](https://github.com/magento/magento2/commit/d03b223d33cc511b482f83c2666469c2e9c19e3f)
 - [d4931f79648bfd1677a861257697d5f8a57cecd6](https://github.com/magento/magento2/commit/d4931f79648bfd1677a861257697d5f8a57cecd6)
 - [f16a12f6bad4a60c50223ab6aab7bc924fc5e437](https://github.com/magento/magento2/commit/f16a12f6bad4a60c50223ab6aab7bc924fc5e437)
 - [819fc7cfef122559826edbfd17ce397527461ae1](https://github.com/magento/magento2/commit/819fc7cfef122559826edbfd17ce397527461ae1)
 - [f16811c29421f34c9ae1b07d080b7ec0107c9757](https://github.com/magento/magento2/commit/f16811c29421f34c9ae1b07d080b7ec0107c9757)
 - [bca6bf6db9f3eeca2f10c753c34a23b568307bdf](https://github.com/magento/magento2/commit/bca6bf6db9f3eeca2f10c753c34a23b568307bdf)
 - [3da6f23f4fb20553580431bdcdbb35afb4551d7f](https://github.com/magento/magento2/commit/3da6f23f4fb20553580431bdcdbb35afb4551d7f)
 - [9b505ee45d9d40dd9b030f8ef88e64204a1b56d4](https://github.com/magento/magento2/commit/9b505ee45d9d40dd9b030f8ef88e64204a1b56d4)

The fix will be available with the upcoming 2.4.2 release.

**Comment by mfickers** [comment]
This fix only prevents duplicate images, but does not help with removing images that are no longer present in the import file:

1. Product in Magento has images A, B, C
2. Row in import file has images A, D, E

**Before fix**
After import, product has images A, A, B, C, D, E

**After fix**
After import, product has images A, B, C, D, E

There are still two images attached to the product that were not present in the import file. This was part of the original bug description and is still occurring on version 2.4.3
