### ISSUE TITLE
Place Order button disabled after Terms and Condition validation failed with BrainTree Payment Gateway

### ISSUE THREAD

**Issue by aniruddhadeshpande** [magento/magento2#14451]
### Preconditions

1. Magento 2.2.2 CE
2. PHP 7.0.22

### Steps to reproduce

1. Enable BrainTree payment gateway.
2. Add item to cart. Login to customer account.
3. Add credit card details in Payment form.
4. Click on Place Order button without check in terms and condition box.
5. Check in Terms and Condition checkbox.

### Expected result

1. Place Order button should be enabled after selecting checkbox.

### Actual result

1. Place Order button still disabled.

Please let me know quick fix.
![checkout 3](https://user-images.githubusercontent.com/2982610/38101121-0efe9746-339d-11e8-8ffa-d8ee46159b8e.png)

**Comment by magento-engcom-team** [comment]
@aniruddhadeshpande , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

![braintree](https://user-images.githubusercontent.com/31669971/38138262-9738bca0-3432-11e8-84b9-399919ae9c65.png)

**Comment by aniruddhadeshpande** [comment]
@magento-engcom-team , Please enable Terms and Condition from admin panel. This issue is with Terms and Condition checkbox failed validation.

**Comment by aniruddhadeshpande** [comment]
Below suggestion from this ticket - https://github.com/magento/magento2/issues/12900 could be useful? I have tried this solution but it was not helpful.
![braintree place order button is disabled after failed validation issue 12900 magento magento2 1](https://user-images.githubusercontent.com/2982610/38139625-ee84f8a0-344d-11e8-8b8b-9ec78b0aa6a1.png)

**Comment by ghost** [comment]
HI @aniruddhadeshpande , thank you for your report. I cannot reproduce, see attachments

**Comment by ghost** [comment]
![frame-47d](https://user-images.githubusercontent.com/40756439/43400631-e1e10b60-9416-11e8-85ce-b37ab831e87e.gif)

**Comment by killpond** [comment]
@engcom-backlog-nazar You are not replicating correctly.

1. Click "Place Order" before touching the T&C checkbox
2. Get alerted about T&C's not being checked
3. Check T&C's
4. "Place Order" button remains disabled

This ticket mentions this was fixed in 2.2.x, but we can still replicate it on 2.2.3?
https://github.com/magento/magento2/issues/12900

**Comment by ghost** [comment]
Hi @aniruddhadeshpande thank you for you report. the fix for issue has already on 2.2-develop branch and 2.3-develop branch

**Comment by granthony** [comment]
@engcom-backlog-nazar I am able to replicate this issue on a Magento 2.2.6 install.  Can you please advise what commits were made to resolve it?

**Comment by pkisdar** [comment]
> Hi @aniruddhadeshpande thank you for you report. the fix for issue has already on 2.2-develop branch and 2.3-develop branch

I can confirm it's still a problem in 2.2.6.

**Comment by huykon** [comment]
don't see any param attribute for magento 2 api of it?

**Comment by aholovan** [comment]
Hello @engcom-backlog-nazar, 
It's pretty weird that ticket was closed because looks like it's still an issue even with 2.3.1 version. I've got the same behavior of the checkout button doing the same steps as described. 
Sugested fix that in #12900 doesn't work when payment form defined correctly!
Please, take a look once more and recheck taking in account 4, 5 stepts carefully. 
By my opinion, agreement's checkbox should have click function that will trigger some validation functionality that responsible for the ability of checkout.
