### ISSUE TITLE
Unable to add more then 1 product to cart with persistent module disabled

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#14486]
### Preconditions
1. Magento version 2.2.2
2. Have all caching functions enabled (especially FPC cache)
3. In the config.php disable the Magento_Persistent module, set it to 0.

### Steps to reproduce
1. Go to a category page and a product detail page. Add the product to the cart. 
2. Go back to another product detail page and add that product to the cart as well.
3. Only the last product added to the cart is in the cart, the first product has been removed from the cart. 

### Expected result
1. Both products should be in the cart 

### Actual result
1. Only the last added product is in the cart. 
2. Another session_id is created, the previous session_id is not in your cookies anymore

**Comment by ghost** [comment]
@dverkadee, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Renu05** [comment]
@magento-engcom-team give me 2.3-develop

**Comment by Renu05** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Renu05. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Renu05, here is your [Magento instance](https://i-14486-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14486-2-3-develop.instances.magento-community.engineering/admin](https://i-14486-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Renu05** [comment]
Hi @dverkade,

I have tried to reproduce the issue in the above instance [Magento instance]( https://i-14486-2-3-develop.instances.magento-community.engineering/admin) and found that this issue is not reproducible.

**I have followed the steps to reproduce the issue:**

1. Created a new category and two new products.
2. Assigned the product to the category.
3. Product 1 is added in cart. The product is visible in cart.
4. Now added second product in the cart. The mini cart is updated and now cart contains two products.

Note: Persistence Cart feature is disabled. I have tried to reproduce on local as well by making the Magento_Persistent as 0 but no luck.

**As this issue is not reproducible in 2.3-develop hence closing this ticket.**

**Comment by Renu05** [comment]
Hi @dverkade,

I have tried to reproduce the issue in the above instance [Magento instance]( https://i-14486-2-3-develop.instances.magento-community.engineering/admin) and found that this issue is not reproducible.

**I have followed the steps to reproduce the issue:**

1. Created a new category and two new products.
2. Assigned the product to the category.
3. Product 1 is added in cart. The product is visible in cart.
4. Now added second product in the cart. The mini cart is updated and now cart contains two products.
5. Have all caching functions enabled (especially FPC cache).

Note: Persistence Cart feature is disabled. I have tried to reproduce on local as well by making the Magento_Persistent as 0 but no luck.

**As this issue is not reproducible in 2.3-develop hence closing this ticket.**

**Comment by dverkade** [comment]
This issue has been verified by Magento, so reopening this so that it can be fixed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dverkade
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dverkade
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by kirtinariya1** [comment]
@magento-engcom-team Please provide Magento 2.3.1 CE test instance.

**Comment by kirtinariya1** [comment]
Can't reproduce the issue.

**Comment by dverkade** [comment]
@kirtinariya1 no need to reproduce this issue, because it's already verified by Magento. The ticket als has the label "Ready for work" and it can be expected to have someone supply a PR for this.

**Comment by engcom-Bravo** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-14486-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14486-2-3-develop.instances.magento-community.engineering/admin](https://i-14486-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-14486-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-14486-2-2-develop.instances.magento-community.engineering/admin](https://i-14486-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18021`, `MC-18022` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @dverkade. 

Thank you for your report and collaboration!

The issue was fixed by Magento team.
