### ISSUE TITLE
Discount Label Text missing for Translation(s)

### ISSUE THREAD

**Issue by raymond62** [magento/magento2#14494]
### Preconditions
**1)** Discount Labels are not shown correctly in all cases, per example not for nl_NL.
**2)** This is happening in all browser, mobile and pc. Installated version Magento 2.3. PHP 7.0, Sql 5.6
**3)** Additional to Issue/Solution https://github.com/magento/magento2/pull/13223

### Steps to reproduce
**1)**  I have an en_GB, a de_DE and a nl_NL Store. Following the Order Process in en_GB and de_DE is working fine, no issues, Labels are Translated as expected. 
**2)** The nl_NL Stores only show "%s" untranslated.

![grafik](https://user-images.githubusercontent.com/29265078/38167114-43ee5312-3530-11e8-91bd-652a80a2b53d.png)

**3)** flush, clean, rm all static files, del cookies don't change anything

### Expected result
1. A translation should appear set in the Label Field in the BackOffice 

![grafik](https://user-images.githubusercontent.com/29265078/38167236-45671222-3532-11e8-97c6-57a246e85b2c.png)

### Actual result
**1)** The nl_NL Stores only show "%s" untranslated.
**2)** When i change the language to de_DE or en_GB, instead of the relevant translation, the discount label text appears in nl_NL, 

![grafik](https://user-images.githubusercontent.com/29265078/38167160-09472fe4-3531-11e8-88f8-2f7681c85c0c.png)

**3)** Going back to nl_NL Store the "%s" is back again.

**Comment by ghost** [comment]
Hi @raymond62 i cannot reproduce by yours scenarios steps can you provide more information ?

**Comment by raymond62** [comment]
What kind of information? 

Please try to setup the 3 language labels as discribed above. I cannot imagine you get different results as i do. 

As i show in the picture in "reproduce 2" there is shown only the placeholder s% instead of the third translation label (nl_NL nederlands). When you change to another shop view (p.e. en_GB english), the translation is shown in dutch (nl_NL nederlands),  as shown in the picture "actual results 2". Changing back to shop view dutch (nl_NL nederlands) the placeholder s% appears again instead of the dutch translation from label 3.

Hope this helps you.

**Comment by raymond62** [comment]
Maybee another issue i posted is related to this one. see https://github.com/magento/magento2/issues/14849

**Comment by ghost** [comment]
Hi @raymond62 , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @raymond62. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-94698` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @raymond62. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-94699` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
