### ISSUE TITLE
Duplicated attributes in sidebar when installing with sample data

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1449]
Seeing duplicated attributes in the sidebar of the Yoga Collection category in Magento ver. 0.74.0-beta16

![screen shot 2015-07-07 at 9 21 07 am](https://cloud.githubusercontent.com/assets/437029/8546985/ac8be520-2489-11e5-8976-d7dd356106a0.png)

**Comment by tkacheva** [comment]
Thank you for highlighting this issue - we will address it upcoming releases. Seeing such feedback proves that magento sample data is being used :-)

**Comment by tkacheva** [comment]
MAGETWO-38658

**Comment by piotrekkaminski** [comment]
This change was implemented and should be already on github or available soon.

**Comment by magento-engcom-team** [comment]
Hi @markoshust. Thank you for your report. 
The issue has been fixed in magento/magento2#29576 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [a74d422b30b2142d4b2195aa86d58acf0c506bfe](https://github.com/magento/magento2/commit/a74d422b30b2142d4b2195aa86d58acf0c506bfe)
 - [9b8c81c657102c5b7e2fee8fc91ae926c82e2c67](https://github.com/magento/magento2/commit/9b8c81c657102c5b7e2fee8fc91ae926c82e2c67)
 - [5c7c95955dc4afe349d284f60d9534b127ae9508](https://github.com/magento/magento2/commit/5c7c95955dc4afe349d284f60d9534b127ae9508)
 - [4ef4c6c52d889213e536575d732c9ab00b6806d3](https://github.com/magento/magento2/commit/4ef4c6c52d889213e536575d732c9ab00b6806d3)
 - [4a7fbd733c59ce798d8fbdbad790da19baaa5a61](https://github.com/magento/magento2/commit/4a7fbd733c59ce798d8fbdbad790da19baaa5a61)
 - [5e072905804d2a66283cbd63151eb598e209ab09](https://github.com/magento/magento2/commit/5e072905804d2a66283cbd63151eb598e209ab09)
 - [0830d38e4b44d145cca9425bdfdefb7509a3df99](https://github.com/magento/magento2/commit/0830d38e4b44d145cca9425bdfdefb7509a3df99)
 - [c29e740bad55570fe30f1c8e86848988dbf20544](https://github.com/magento/magento2/commit/c29e740bad55570fe30f1c8e86848988dbf20544)
 - [bed58c5ccca7b11d2495d44ce6cebdc03c49439b](https://github.com/magento/magento2/commit/bed58c5ccca7b11d2495d44ce6cebdc03c49439b)
 - [58fbad4730f1dd552ee90b0008bc99cef77d644b](https://github.com/magento/magento2/commit/58fbad4730f1dd552ee90b0008bc99cef77d644b)
 - [9a740371e1bfdde8c5dc79460de6e6e4a29dc27f](https://github.com/magento/magento2/commit/9a740371e1bfdde8c5dc79460de6e6e4a29dc27f)
 - [583b0134ff6244438e55064bcd9b2980a18d2bc9](https://github.com/magento/magento2/commit/583b0134ff6244438e55064bcd9b2980a18d2bc9)

The fix will be available with the upcoming 2.4.1 release.
