### ISSUE TITLE
PDF invoices in /var folder

### ISSUE THREAD

**Issue by erichagz** [magento/magento2#14517]
### Preconditions

1. AWS EC2 C4-Large, Ubuntu 16.04.4 LTS, PHP 7.0.28-0ubuntu0.16.04.1
2. Magento 2.2.2
3. Also using AWS Redis for page caching. Following directions on https://devdocs.magento.com/guides/v2.2/config-guide/redis/redis-pg-cache.html

### Steps to reproduce

1. Create invoice
2. Print invoice

### Expected result

1. PDF Generation (maybe in cache) happens properly for client and user
2. PDF maybe should not be created at all? 

### Actual result

1. Creates PDF copy in the /var folder

-rw-rw-r-- 1 www-data www-data  2013893 Apr  2 21:07 invoice2018-04-02_21-07-00.pdf
-rw-rw-r-- 1 www-data www-data  2014019 Apr  3 12:41 invoice2018-04-03_12-41-06.pdf
-rw-rw-r-- 1 www-data www-data  1558155 Apr  3 12:52 invoice2018-04-03_12-52-36.pdf
-rw-rw-r-- 1 www-data www-data  2015663 Apr  3 13:26 invoice2018-04-03_13-26-28.pdf
-rw-rw-r-- 1 www-data www-data  1558369 Apr  3 13:43 invoice2018-04-03_13-43-12.pdf
-rw-rw-r-- 1 www-data www-data  2014032 Apr  3 13:45 invoice2018-04-03_13-45-22.pdf
-rw-rw-r-- 1 www-data www-data  2014195 Apr  3 14:04 invoice2018-04-03_14-04-53.pdf
-rw-rw-r-- 1 www-data www-data  2014212 Apr  3 14:08 invoice2018-04-03_14-08-05.pdf
-rw-rw-r-- 1 www-data www-data  2015663 Apr  3 14:13 invoice2018-04-03_14-13-27.pdf
-rw-rw-r-- 1 www-data www-data  2013876 Apr  3 14:18 invoice2018-04-03_14-18-26.pdf
-rw-rw-r-- 1 www-data www-data  2016614 Apr  3 14:53 invoice2018-04-03_14-53-14.pdf
-rw-rw-r-- 1 www-data www-data  2014914 Apr  3 14:54 invoice2018-04-03_14-54-15.pdf
-rw-rw-r-- 1 www-data www-data  2013543 Apr  3 15:08 invoice2018-04-03_15-08-33.pdf
-rw-rw-r-- 1 www-data www-data  2017829 Apr  3 15:48 invoice2018-04-03_15-48-19.pdf
-rw-rw-r-- 1 www-data www-data  1558155 Apr  3 15:58 invoice2018-04-03_15-58-48.pdf
-rw-rw-r-- 1 www-data www-data  2014961 Apr  3 16:12 invoice2018-04-03_16-12-38.pdf
-rw-rw-r-- 1 www-data www-data  2013969 Apr  3 16:23 invoice2018-04-03_16-23-52.pdf
-rw-rw-r-- 1 www-data www-data  2014070 Apr  3 16:59 invoice2018-04-03_16-59-58.pdf
-rw-rw-r-- 1 www-data www-data  2013838 Apr  3 17:03 invoice2018-04-03_17-03-43.pdf
-rw-rw-r-- 1 www-data www-data  2014539 Apr  3 17:05 invoice2018-04-03_17-05-38.pdf
-rw-rw-r-- 1 www-data www-data  2013866 Apr  3 17:17 invoice2018-04-03_17-17-57.pdf
-rw-rw-r-- 1 www-data www-data  2014325 Apr  3 17:34 invoice2018-04-03_17-34-30.pdf
-rw-rw-r-- 1 www-data www-data  2013543 Apr  3 17:35 invoice2018-04-03_17-35-59.pdf
drwxrwsr-x 2 www-data www-data     4096 Mar 28 17:14 log
-rw-rw-r-- 1 www-data www-data  2007347 Nov 15 17:17 packingslip2017-11-15_17-17-43.pdf
drwxrwsr-x 2 www-data www-data     4096 Jan 16 20:20 page_cache
drwxrwsr-x 3 www-data www-data  1228800 Apr  3 17:08 report
-rw-rw-r-- 1 www-data www-data      216 Apr  3 17:36 resource_config.json
drwxrwsr-x 3 www-data www-data     4096 Feb 13 21:38 tmp
drwxrwsr-x 3 www-data www-data     4096 Mar 30 09:28 view_preprocessed

**Comment by ghost** [comment]
Duplicate of #3535

**Comment by magento-engcom-team** [comment]
Hi @erichagz. Thank you for your report. 
The issue has been fixed in magento/magento2#16401 by @rogyar in 2.2-develop branch
Related commit(s):
 - [4989d8b358bcaccac21ee5aa985e2359d8abb9ca](https://github.com/magento/magento2/commit/4989d8b358bcaccac21ee5aa985e2359d8abb9ca)
 - [9366da978649cd3549f1732521d45f4963f74d5e](https://github.com/magento/magento2/commit/9366da978649cd3549f1732521d45f4963f74d5e)
 - [70fed741d14a72c11ae7f62c7164b9fd066c532e](https://github.com/magento/magento2/commit/70fed741d14a72c11ae7f62c7164b9fd066c532e)
 - [31df140d545a5a4cecf3b7c410069d0ae169a328](https://github.com/magento/magento2/commit/31df140d545a5a4cecf3b7c410069d0ae169a328)
 - [25d49eb011d2aa7cd232b0139f05ad09cc1fb731](https://github.com/magento/magento2/commit/25d49eb011d2aa7cd232b0139f05ad09cc1fb731)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @erichagz. Thank you for your report. 
The issue has been fixed in magento/magento2#17280 by @tiagosampaio in 2.3-develop branch
Related commit(s):
 - [b358932812325776ca46824aaf15f8795d990984](https://github.com/magento/magento2/commit/b358932812325776ca46824aaf15f8795d990984)
 - [d3a7b9729405842e680fd5fafb09285de09ce30b](https://github.com/magento/magento2/commit/d3a7b9729405842e680fd5fafb09285de09ce30b)
 - [5f1e0bf52be0c106de165f304f9d6a582903e0ae](https://github.com/magento/magento2/commit/5f1e0bf52be0c106de165f304f9d6a582903e0ae)
 - [99c5631783417a829523f647d00ed2a5838fad6e](https://github.com/magento/magento2/commit/99c5631783417a829523f647d00ed2a5838fad6e)
 - [ec713fcbb0f33f668540e2c9c625097679b68b2e](https://github.com/magento/magento2/commit/ec713fcbb0f33f668540e2c9c625097679b68b2e)

The fix will be available with the upcoming 2.3.0 release.
