### ISSUE TITLE
Script error while uploading category image in Magento 2.1.9 using IE11

### ISSUE THREAD

**Issue by ameshca** [magento/magento2#14533]
### Preconditions

1. Magento 2.1.9
2. MariaDB 10.1.32 
3. PHP 7.0.29
4. IE11 browser

_Or_

1. Magento 2.1.9
2. Mysql 5.6.24
3. PHP 5.6.8
4. IE11 browser

### Steps to reproduce

1. Go to IE11 browser
2. Take the backend
3. Go to Admin -> Products -> Categories
4. Go to Content section
5. Upload a category image

### Expected result

1. When we browse the image the image thumbnail should be shown below the browse button

### Actual result

1. Showing script error in console
2. Loader shows infinite time

This issue exist in IE browser, chrome and firefox have no problem. The script error generated in the console is 
`SCRIPT438: Object doesn't support property or method 'set'`  
and the corresponding file is 
`Magento_Ui/js/form/element/file-uploader.js`

Another point is we have tested the same scenario in a lower magento version ie Magento 2.1.2.
Here no issue occured and successfully browsed and uploaded the image for category. So we have compared the file file-uploader.js in both versions and saw some difference also which causing the error. The code part where the error throwing is in the function "onBeforeFileUpload" at line 300 is
`postData.data.set('param_name', this.paramName);`

**Comment by ameshca** [comment]
Any solution for this?

**Comment by munna2468** [comment]
Hi Amesh,

The issue you have specified is of magento's issue (in magento 2.1.9).

Thers is a solution for this , since the console says that "_SCRIPT438: Object doesn't support property or method 'set'_ " so you can use "append" method instead of 'set' method. so the final code be like
`postData.data.append('param_name', this.paramName);` 

Its works fine for me . Before changing don't forget to override the core file.

Thank you

**Comment by ameshca** [comment]
@munna2468 Great work, thanks for the fix ;).
