### ISSUE TITLE
Zero Price with Decimal Qty When Price is Less Than 0.05

### ISSUE THREAD

**Issue by C0D31GN1T3R** [magento/magento2#14567]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Create a product or set a products price to 0.49 or anything less than 0.50.
2. Enable decimal qty.
3. Set minimum qty allowed in basket to 0.01
4. Add 0.01 of product to basket.

### Expected result

1. 0.01 of product is added to basket, the price is rounded up 2 decimal places.  So if price is calculated as < 0.005 it will be rounded to 0.01

### Actual result

1. 0.01 of product is added to basket rounded down 2 decimal places.  So if price is < 0.005 the item total is 0.00.

This feature is being used for selling goods that are priced per 10, 100, 1000.  Customers can buy as many as they like but the price is expressed per 10, 100, 1000.  Decimal qty's make this possible as the price entered in admin is for the full qty i.e 10, 100, 1000, but by entering a decimal qty the price can be recalculated for any qty.  Except when the price is less than 0.005 as it is rounded down rather than up.  In a real world example the vast majority of items wouldn't have this issue as they would be higher value but this does affect a handful of low value products.

**Comment by ghost** [comment]
Hi @C0D31GN1T3R  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Bravo** [comment]
Hello @C0D31GN1T3R. Unfortunately we acknowledged this issue by mistake. Rounding 0.0049 to 0.01 instead of 0.00 (when You need to round to the second decimal place) would be against Math convention on the rules of rounding. When one wants to round a number to some N place (not necessarily a place after the decimal point) one considers **only** N + 1 place. If the digit occupying that place is less than 5, (i.e equal to 0, 1, 2, 3 or 4) the digit in position N will remain unchanged. Otherwise (i.e equal to 5, 6, 7, 8 or 9) the digit will be incremented by 1. It comes out to be curious that if You are going to round 0.0049 to third decimal place You'll obtain 0.005. if You want to round 0.005 (that is originally 0.005, but not a result of previous rounding) to the second decimal position You'll obtain 0.01. But if You want to round 0.0049 right to the second decimal position (though at the intermediate stage it undergoes through 0.005) You'll get 0. You may try it out with any of the calculating tables:
![rounding](https://user-images.githubusercontent.com/51680745/65495697-da0e4980-debf-11e9-8e5d-ed21301fa093.gif)
I think You would agree we can not go against generally accepted Math convention as it necessarily will lead to enormous unexpected outcomes. So to consider rounding rules when setting up prices and to correct them appropriately (if necessary) seems to be the only way to cope with such situations as Yours one is.

**Comment by engcom-Bravo** [comment]
@C0D31GN1T3R the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
