### ISSUE TITLE
Specify the table when adding field to filter for the collection Eav/Model/ResourceModel/Entity/Attribute/Option/Collection.php

### ISSUE THREAD

**Issue by PierreLeMaguer** [magento/magento2#14572]
Hi!
About the collection vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute/Option/Collection.php, the method setAttribbuteFilter call the method addFieldToFilter without specify the table.
So, when we join some tables with a column 'attribute_id' (example: 'catalog_product_entity_int'), we have the error 'ambiguous column name'.

### Preconditions
Magento EE 2.1.12

### Steps to reproduce

1. Create a class with a property Magento\Eav\Model\ResourceModel\Entity\Attribute\Option\CollectionFactory
2. Create a collection with it and join tables like 'catalog_product_entity_int'
3. Get items of the collection.

### Expected result

1. Have the items

### Actual result

1.error 'ambiguous column name'

a solution would be on the method setAttributeFilter of the class vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute/Option/Collection.php : replace 'return $this->addFieldToFilter('attribute_id', $setId);' by 'return $this->addFieldToFilter('main_table.attribute_id', $setId);'

**Comment by orlangur** [comment]
@PierreLeMaguer true! `setIdFilter` already uses similar prefix.

Feel free to propose such doubtless observations directly as a pull request. Could you create one now please? It is possible even via GitHub UI without necessity to clone repository locally.

**Comment by magento-engcom-team** [comment]
Hi @PierreLeMaguer. Thank you for your report. 
The issue has been fixed in magento/magento2#14596 by @PierreLeMaguer in 2.1-develop branch
Related commit(s):
 - [f02dae8a27c0639ccdfd403622966cd6f7b78634](https://github.com/magento/magento2/commit/f02dae8a27c0639ccdfd403622966cd6f7b78634)

The fix will be available with the upcoming 2.1.14 release.

**Comment by magento-engcom-team** [comment]
Hi @PierreLeMaguer. Thank you for your report. 
The issue has been fixed in magento/magento2#14599 by @PierreLeMaguer in 2.2-develop branch
Related commit(s):
 - [215c7834df8bf156ea307504a28874d1b96fc6ac](https://github.com/magento/magento2/commit/215c7834df8bf156ea307504a28874d1b96fc6ac)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @PierreLeMaguer. Thank you for your report. 
The issue has been fixed in magento/magento2#14676 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [a712d3e69c3c7d968d827fbcf5faa366e6db9e9d](https://github.com/magento/magento2/commit/a712d3e69c3c7d968d827fbcf5faa366e6db9e9d)

The fix will be available with the upcoming 2.3.0 release.
