### ISSUE TITLE
Sub-admin role related issue in order view page in magento 2 admin

### ISSUE THREAD

**Issue by amalkarmick** [magento/magento2#14633]
I have created one sub admin user from Magento admin. This user can only view orders, add a comment and operate on shipping. I gave some permissions for sub admin user. Please check the below image:
![roles - permissions - system - magento admin 4-11-2018 1-35-43 pm](https://user-images.githubusercontent.com/25522301/38604477-1b625784-3d8e-11e8-90b1-9055c40dc14b.png)

So as you can see I have disabled Invoice and Credit memo role of this sub-admin.
But when I logged in as sub admin and go to order view page. I saw some error messages pop-up. Check below image:
![screenshot-2018-4-11 000000013-1](https://user-images.githubusercontent.com/25522301/38605147-24b29004-3d90-11e8-8602-0ada89a8fd5a.png)

### Preconditions

1. Magento ver. 2.1.8

### Steps to reproduce

1. In M2 admin, create new sub admin user and then create role for that user with order operation and shipping operation.
2. Next Log in as sub admin user and go to view order page
3. You can see some error messages pop-up

### Expected result

1.Must show Order information tab, shipping tab and comment history tab

### Actual result

1. 
![screenshot-2018-4-11 000000013-1](https://user-images.githubusercontent.com/25522301/38605174-33f86494-3d90-11e8-9851-41a5d698b85d.png)
2.
![screenshot-2018-4-11 000000013-2](https://user-images.githubusercontent.com/25522301/38605187-3ce3a884-3d90-11e8-88df-fd2816b87570.png)

**Comment by ghost** [comment]
@amalkarmick, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by GovindaSharma** [comment]
#MM14633

**Comment by GovindaSharma** [comment]
#MM19IN

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38521` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
