### ISSUE TITLE
Size Filter is visible on the Storefront only when ‘Filterable (no results)’ setting is applied.

### ISSUE THREAD

**Issue by AmastyLtd-zz** [magento/magento2#14640]
### Preconditions

1. Magento 2.2.3

### Steps to reproduce

1. Go to any Category Page (e.g. Men > Tops > Jackets);
2. Note that Size Filter don’t display in the column;
3. Navigate to the Admin > Stores > Product > Size > Storefront Properties tab;
4. In ‘Use in Layered Navigation’ drop-down select ‘Filterable (no results)’;
5. Go back to the Category Page.
### Expected result

Size Filter is visible when ‘Filterable (with results)’ is applied.

### Actual result

Size Filter is visible.

**Comment by brendanbell** [comment]
Hi,

I agree with the above. I just did a new install and the above issue persists as detailed.

Magento 2.2.3
Ubtuntu 16.04
PHP 7.0.28-0ubuntu0.16.04.1
nginx version: nginx/1.10.3 (Ubuntu)

**Comment by ghost** [comment]
@AmastyLtd, thank you for the report. This is expected behavior - when 
"Filterable (no results)" is enabled, Layered navigation includes filters for all available attribute values and their product counts, including those with zero (0) product matches.
Please see [Magento documentation](https://docs.magento.com/m2/ee/user_guide/catalog/navigation-layered-filterable-attributes.html).
