### ISSUE TITLE
Updating Customer through rest/all/V1/customers/:id resets group_id if group_id not passed in payload

### ISSUE THREAD

**Issue by abancroft0** [magento/magento2#14663]
### Preconditions

1. Magento Version 2.2.3 using rest API
2. Passing a JSON payload with minimum required data (email, first/last name, website_id, id)

### Steps to reproduce

1. Update any customer who's group_id isn't the first group_id in the source list
2. Pass the customer payload with email, firstname, lastname, website_id, id

### Expected result

1. I expect that only the data passed in the payload would be modified
2. Example: {"customer":{"email":"test@gmail.com","firstname":"magento","lastname":"user","website_id":1,"id":77486}} should leave the customer's full data structure unchanged.

### Actual result

1. If the above customer had a group_id of 5, and our full group_id consisted of [1,2,3,4,5], the customer's group_id after passing the above payload would be set to 1:

Before: 
![image](https://user-images.githubusercontent.com/31518676/38679172-ace6204c-3e28-11e8-8109-2bf663acb663.png)

PUT: 
![image](https://user-images.githubusercontent.com/31518676/38679196-c7e2d476-3e28-11e8-826a-b0381a17c865.png)

Results:
![image](https://user-images.githubusercontent.com/31518676/38679222-da11b1f8-3e28-11e8-8d1a-725d1b760927.png)

**Comment by bydrei** [comment]
@magento-engcom-team was able to replicate this. Ok if I self assign?

**Comment by magento-engcom-team** [comment]
Hi @ferrazzuk 
Sure, feel free to assign it to yourself if you feel like trying and fixing this

Thanks!

**Comment by bydrei** [comment]
@magento-engcom-team pull request created.

**Comment by magento-engcom-team** [comment]
Hi @abancroft0. Thank you for your report. 
The issue has been fixed in magento/magento2#14757 by @ferrazzuk in 2.1-develop branch
Related commit(s):
 - [51f2f076a8fddbeb7b29914a1994236c29bdc369](https://github.com/magento/magento2/commit/51f2f076a8fddbeb7b29914a1994236c29bdc369)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @jignesh-baldha. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by KishorkumarKar** [comment]
@magento-engcom-team I have fixed this issue. Creating the PR #22700.
