### ISSUE TITLE
Css class "empty" is always present on minicart dropdown 

### ISSUE THREAD

**Issue by denistrator** [magento/magento2#14669]
### Preconditions

1.  Magento 2.2.3 or older

### Steps to reproduce

1. Add product to cart
2. Open dev tools and find `.block-minicart` element 

### Expected result

1. `.block-minicart` element doesn't have `empty` class

### Actual result

1. `.block-minicart` element has `empty` class
![screenshot_149](https://user-images.githubusercontent.com/21016905/38692973-2b228404-3e8e-11e8-90ba-b7e07af381b0.png)

**Comment by magento-engcom-team** [comment]
Hi @denistrator. Thank you for your report. 
The issue has been fixed in magento/magento2#14715 by @Karlasa in 2.2-develop branch
Related commit(s):
 - [888d8283f69b50873b508c0fa38836938e93bc33](https://github.com/magento/magento2/commit/888d8283f69b50873b508c0fa38836938e93bc33)

The fix will be available with the upcoming 2.2.5 release.
