### ISSUE TITLE
Attribute value saving issue

### ISSUE THREAD

**Issue by orozcodiaz** [magento/magento2#14691]
### Preconditions

1. Magento 2.2.2 and 2.2.3
2. PHP 7.0.28
3. mysql Ver 14.14 Distrib 5.6.32-78.1

### Steps to reproduce

1. Add new value with single quote to dropdown attribute and save it `(e.g. Men's)`
2. Add the same value `(Men's)` with single quote and save it
3. Try to edit something else on the page and try to save attribute

### Expected result
Prevent saving same values

### Actual result
Same values are successfully saved and it prevents to update attribute data. 
It's ok if you have 5-20 values but what if you will have hundreds? 

Check this video:

![hx5zo9s3rl](https://user-images.githubusercontent.com/24477165/38743857-2776b1b0-3f0e-11e8-88b4-8563fd06a4a1.gif)

P.S.: `magento/module-catalog/view/adminhtml/web/catalog/product/attribute/unique-validate.js` should be fixed

**Comment by viral-wagento** [comment]
@oroskodias 
@magento-engcom-team 

Hello,
I have checked in Magento latest branch 2.2-develop, and it seems that issue is not being reproduced in this version. 
I can add attribute option "Men's" , "Women's"  and it is saved properly by first time, without any other characters as you have shown in video.
Please check attached screenshot for your reference.

![myattribute product attributes attributes stores magento admin](https://user-images.githubusercontent.com/39254899/40535700-7a8cd5c0-6027-11e8-9d6b-28c0a3c6536a.png)

**Comment by ghost** [comment]
@oroskodias, thank you for your report.
This issue is already fixed in Magento 2.2.
