### ISSUE TITLE
'validate-grouped-qty' validation is meaningless

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#14692]
https://github.com/magento/magento2/blob/a2f6a0827221e0e9ccd1f1bc49375611dcc5fb17/lib/web/mage/validation/validation.js#L22

Seems that this 'validate-grouped-qty' validation haven't sense because validation should be done on the child elements.

And seems that current implementation is buggy. Seems that sense of this validation is check that sum of qty for all products is more then one. But what sense in it?

Grouped Product can contains simple products with "Qty Uses Decimals" = Yes and "Minimum Qty Allowed in Shopping Cart" less than 1 (for example 0.05). As result sum of qty would be 0 (because of 
using parseInt()).

Seems that 'validate-grouped-qty' should be deleted at all or rewritten to just call subproduct's validators.

**Comment by likemusic** [comment]
https://github.com/magento/magento2/pull/14693 - pull-request with replaced parseInt() to parseFloat().

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
The issue has been fixed in magento/magento2#14752 by @likemusic in 2.2-develop branch
Related commit(s):
 - [67e7994ffea34333a02500e0aa7f64a873722d2a](https://github.com/magento/magento2/commit/67e7994ffea34333a02500e0aa7f64a873722d2a)
 - [de6203588c935481fd0375e2859c435a001fb25a](https://github.com/magento/magento2/commit/de6203588c935481fd0375e2859c435a001fb25a)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
The issue has been fixed in magento/magento2#14814 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [c3a1415719f266390593b5a3ee5f35e504c8128e](https://github.com/magento/magento2/commit/c3a1415719f266390593b5a3ee5f35e504c8128e)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
The issue has been fixed in magento/magento2#15407 by @rogyar in 2.1-develop branch
Related commit(s):
 - [e8087c5569b32d193801f63fa2c9fd02f10c6a29](https://github.com/magento/magento2/commit/e8087c5569b32d193801f63fa2c9fd02f10c6a29)

The fix will be available with the upcoming 2.1.15 release.
