### ISSUE TITLE
Shipping issue on PayPal Express

### ISSUE THREAD

**Issue by raymond62** [magento/magento2#14712]
Shipping Information is not shown in Summary on PayPal Express Review Page if the Price is 0.00

### Preconditions
1. Magento 2.2.3., PHP 7.0, MySql 5.6

### Steps to reproduce
1. Make a Payment using PayPal Express
2. On the Review Page use a 0.00 Value for a Shipping Method
3. Summary only shows "Delivery & Handling" but not the Method

### Expected result
1. The Shipping Method should be shown in the Summary.
2. This is only shown when the Price is not set to 0.00 Value, eg. 0.01

### Actual result
![grafik](https://user-images.githubusercontent.com/29265078/38778639-000fb210-40bd-11e8-88fb-cc5eae6201f2.png)

This IS shown
![grafik](https://user-images.githubusercontent.com/29265078/38778644-13efcef0-40bd-11e8-98e7-0be3e03c85e0.png)

This SHOULD be shown as 0.00 Price value
![grafik](https://user-images.githubusercontent.com/29265078/38778993-538b2b2c-40c2-11e8-8a31-2b48ac02dff1.png)

**Comment by ghost** [comment]
Hi @raymond62, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ssp58bleuciel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @raymond62. Thank you for your report. 
The issue has been fixed in magento/magento2#19788 by @ssp58bleuciel in 2.3-develop branch
Related commit(s):
 - [0e8ffeb450abcc1b08fe7db532dd3ff1e3346746](https://github.com/magento/magento2/commit/0e8ffeb450abcc1b08fe7db532dd3ff1e3346746)
 - [a39039097b5abb807b2b552a606de19256865dfb](https://github.com/magento/magento2/commit/a39039097b5abb807b2b552a606de19256865dfb)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @raymond62. Thank you for your report. 
The issue has been fixed in magento/magento2#19655 by @ssp58bleuciel in 2.2-develop branch
Related commit(s):
 - [8a059e655b4e09ca506638bc5bc59aca9badbf08](https://github.com/magento/magento2/commit/8a059e655b4e09ca506638bc5bc59aca9badbf08)
 - [8bdcca96f53b0e47a7270af1e399144446ea7290](https://github.com/magento/magento2/commit/8bdcca96f53b0e47a7270af1e399144446ea7290)
 - [c3d5010efe9b2ce61220ef9fec3a98c3952276fc](https://github.com/magento/magento2/commit/c3d5010efe9b2ce61220ef9fec3a98c3952276fc)

The fix will be available with the upcoming 2.2.8 release.
