### ISSUE TITLE
Issue in Partial Credit Memo including total tax.

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#14713]
### Preconditions

1. Magento 2.2.2 CE

### Steps to reproduce

1. Create an order using two items contain the tax on it. Support one item(order_item_id:100) having tax $10 and other item(order item id:101) having tax $11. Total tax is $21.
2. Create invoice.
3. try to refund using /V1/invoice/:invoiceId/refund API with this payload.
{
	"items": [
		{
			"order_item_id": "101",
			"qty": "1"
		}
		]
	
}

Then refund will contain total $21 tax. Which is not correct.
If we make request using this payload:
{
	"items": [
		{
			"order_item_id": "100",
			"qty": "0"
		},
		{
			"order_item_id": "101",
			"qty": "1"
		}
		]
	
}
then it will refund $11 tax amount.

### Expected result

1. It should refund $11 tax, not the total tax if we provide only single item and qty in refund payload.

### Actual result

1. It is refunding total tax if we want to refund partially with having only one item in refund payload.
Example screenshots of other order:

Ordered items:
![image](https://user-images.githubusercontent.com/6079017/38795683-a27a5992-4176-11e8-82d9-abce597f76bd.png)

and refund contain total tax of order:
![image](https://user-images.githubusercontent.com/6079017/38795709-bb0b8418-4176-11e8-94d7-52790fcc49e0.png)

**Comment by ankursachdeva11** [comment]
Hi @magento-engcom-team 

Any update on this?

Thanks

**Comment by ghost** [comment]
Hi @ankursachdeva11 thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Bravo** [comment]
Hello @ankursachdeva11 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
