### ISSUE TITLE
html ID store.menu confuses css

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#14721]
Magento produces a container with an ID of "store.menu". This confuses CSS since "#store.menu" relates to an element with the ID "store" AND a class "menu".

I just learned that you can actually escape dots in CSS with a backslash (#store\.menu) to access that element.

While this does work I would suggest to rename this ID to something else (store-menu, store_menu etc.). 

Was this intended anyway?

**Comment by xtremeperf** [comment]
@DocOlson ,

Yeah, it is intentional... I found the following rule published online in the Magento coding standards...

**_"Visual representation must rely only on HTML class attributes, CSS pseudo-classes and pseudo-elements, HTML tags, and form element’s type attribute and form elements state attributes"_**...  [**devdocs**](http://devdocs.magento.com/guides/v2.2/coding-standards/code-standard-demarcation.html#visual-representation-must-rely-only-on-html-class-attributes-css-pseudo-classes-and-pseudo-elements-html-tags-and-form-elements-type-attribute-and-form-elements-state-attributes-example-disabled-checked) 

In the `store.menu` example you gave, the ID is actually being used for ARIA Controls.

**Comment by OvalMedia** [comment]
Ok, thanks for clarifying.
