### ISSUE TITLE
Newsletter subscription confirmation message does not display after clicking link in email

### ISSUE THREAD

**Issue by tohann** [magento/magento2#14747]
### Preconditions

1. Magento 2.2.x

### Steps to reproduce

1. Visit the store homepage.
2. Enter a valid email address in the newsletter subscription box, press submit.
3. In the subscription confirmation email, click on the link to confirm the subscription.

### Expected result

1. Magento processes the subscription confirmation.
2. Magento redirects the user to the homepage with a success message stating the subscription was successful.

### Actual result

1. Magento processes the subscription confirmation.
2. Magento redirects the user to the homepage, but there is no success message stating the subscription was successful.
3. Furthermore, if you enter a search term and press submit on the search form, the newsletter confirmation message will appear on the search results page.

**Comment by magento-engcom-team** [comment]
Hi @tohann. Thank you for your report. 
The issue has been fixed in magento/magento2#15247 by @KaushikChavda in 2.2-develop branch
Related commit(s):
 - [6eb96c6f020a7bb90d3ec7a2b6555d771b93fa3d](https://github.com/magento/magento2/commit/6eb96c6f020a7bb90d3ec7a2b6555d771b93fa3d)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @tohann. Thank you for your report. 
The issue has been fixed in magento/magento2#15861 by @rahul-kachhadiya in 2.3-develop branch
Related commit(s):
 - [75516bf8ee74cbf115b1c2519cd412dc3cd63e20](https://github.com/magento/magento2/commit/75516bf8ee74cbf115b1c2519cd412dc3cd63e20)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @tohann. Thank you for your report. 
The issue has been fixed in magento/magento2#15860 by @rahul-kachhadiya in 2.1-develop branch
Related commit(s):
 - [1839f97c1852d19477b92baf868ce22dcf0da041](https://github.com/magento/magento2/commit/1839f97c1852d19477b92baf868ce22dcf0da041)

The fix will be available with the upcoming 2.1.15 release.
