### ISSUE TITLE
SSL Error!

### ISSUE THREAD

**Issue by mrRonyTran** [magento/magento2#1477]
Hi magento2 developers,
After I enable SSL in backend:
![mage_2_2](https://cloud.githubusercontent.com/assets/3252322/8644418/14463268-2969-11e5-9b97-c474d2fc03f6.png)
![mage_2_1](https://cloud.githubusercontent.com/assets/3252322/8644419/145125d8-2969-11e5-8126-cbf75efb9213.png)

I got errors below:
![mage_2_4](https://cloud.githubusercontent.com/assets/3252322/8644429/229d04b8-2969-11e5-9382-47fc7129dd2f.png)
![mage_2_3](https://cloud.githubusercontent.com/assets/3252322/8644430/22a612ce-2969-11e5-83dc-500319f91273.png)

Please help me,
Thanks

**Comment by buskamuza** [comment]
Hi @mrRonyTran , currently browsers are working more and more on security and often disallow mixed content, which means either having HTTP links on HTTPS pages or vise versa.
In your example Base URL is HTTP and Base Secure URL is HTTPS, which leads to some requests from an HTTP page being made to HTTPS sources. Some browsers block it as insecure.
I'd suggest for better security set HTTPS as Base URL as well and so, have all pages under HTTPS. Would it work for you?

**Comment by mrRonyTran** [comment]
Hi @buskamuza If I change to HTTP or HTTPS, it work OK.
In this case, I just want to use https in a few pages (example: Login, checkout, ...). The rest, I want to use http.
With Magento 1.x, it is OK.
You have any solutions for magento 2?

**Comment by MaxSavich** [comment]
Hello @mrRonyTran,

I had configured the URLs (HTTPS for secure and HTTP for unsecure one) and I wasn't able to reproduce the issue.

Can you try to set up  one more time with fresh Magento installation?
Also, please provide more details: 
What platform and web server do you use, web browser version, how the SSL certificate has been generated, anything that might clarify the situation.

Thanks,

**Comment by MaxSavich** [comment]
Internal ticket MAGETWO-40181

**Comment by dsikkema** [comment]
@mrRonyTran can you please share your Magento version?

**Comment by dsikkema** [comment]
@mrRonyTran additionally, please share your browser and browser version. Thanks!

**Comment by mrRonyTran** [comment]
Hi @dsikkema My magento version is 0.74.0-beta10 and firefox version is 39.0. I am upgrading to latest version of magento2, and then I will check it again. Thanks!

**Comment by MaxSavich** [comment]
Hello @mrRonyTran 

As @buskamuza has mentioned in another thread: 
"... unfortunately, there were schema changes in beta11 that do not allow upgrade from earlier versions. You may re-install the application, if you want to upgrade to the newer version. See details at http://devdocs.magento.com/guides/v1.0/install-gde/install/install-cli-uninstall.html#instgde-install-magento-updatebeta11
If you want to use latest version 1.0.0-beta in future, better to install it now, as it also has backwards incompatible changes and you won't be able to upgrade to this or newer version.

You can use ./bin/magento setup:uninstall for easy uninstall.
...
"
Please try to download the recent version and just install it instead of upgrade to it from the older version.

Thanks,

**Comment by mrRonyTran** [comment]
Hi @MaxSavich thanks for your answer.
After I reinstall latest version 1.0.0-beta, I got some error bellow:
![mage_2_5](https://cloud.githubusercontent.com/assets/3252322/8740128/330e0744-2c6f-11e5-906b-71be13b1ee68.png)
Test on magento2 1.0.0-beta and firefox 39.0
![mage_2_6](https://cloud.githubusercontent.com/assets/3252322/8740134/54a4c1a4-2c6f-11e5-9f21-ee670d046f1c.png)
![mage_2_7](https://cloud.githubusercontent.com/assets/3252322/8740137/5a5291f8-2c6f-11e5-92ee-8f3d2351fc84.png)
![mage_2_8](https://cloud.githubusercontent.com/assets/3252322/8740138/603b7d96-2c6f-11e5-882b-3f1c9a4c8a47.png)

However, if the HTTPS page I visit includes HTTP content, it will be blocked.
![mage_2_9](https://cloud.githubusercontent.com/assets/3252322/8740221/fe4b7306-2c6f-11e5-8eb6-110dfaf7be97.png)

**Comment by MaxSavich** [comment]
Hello @mrRonyTran !

Thank you for your patience :)

We already have the internal ticket about mini shopping cart: MAGETWO-40319

As for the Same-origin policy violation and JavaScript error - I'll create the tickets.

Thank you!

**Comment by MaxSavich** [comment]
@mrRonyTran I was unable to reproduce neither the JavaScript error nor styles.css problem.

If you didn't cleaned up the var/cache and pub folder (just did a git pull in the directory that contained the old Magento version and the generated files for it) - that might be the cause of the problem. The ideal case is to make the git clone to the empty folder in order to make sure that only the necessary files are there and flush the database (delete all tables) and then proceed with the installation. 

Or we can do it next way:

1) Open console/terminal window and navigate to your magento root directory
2) Uninstall Magento. *Your database will be flushed!* Execute: php -f bin/magento setup:uninstall
3) Make sure that 'var' directory contains .htaccess file only
4) Check the structure of 'pub' directory (below) no additional files should be there:
5) Install Magento using Web installer or console installer: 
php -f bin/magento setup:install --base-url="http://dev.magento2.local" --db-name="devmagento2local" --admin-user="admin" --admin-password="admin" --admin-email="null@null.com" --admin-firstname="admin" --admin-lastname="admin" --backend-frontname="admin"
6) Re check the errors you had previously.
7) Let me know if everything is OK or not :)

The structure of 'pub' directory: 
³   .htaccess
³   cron.php
³   get.php
³   index.php
³   static.php
³   tree.txt
³   
----errors
³   ³   .htaccess
³   ³   404.php
³   ³   503.php
³   ³   design.xml
³   ³   local.xml.sample
³   ³   noCache.php
³   ³   processor.php
³   ³   processorFactory.php
³   ³   report.php
³   ³   
³   ----default
³       ³   404.phtml
³       ³   503.phtml
³       ³   nocache.phtml
³       ³   page.phtml
³       ³   report.phtml
³       ³   
³       ----css
³       ³       styles.css
³       ³       
³       ----images
³               favicon.ico
³               i_msg-error.gif
³               i_msg-note.gif
³               i_msg-success.gif
³               logo.gif
³               
----media
³   ³   .htaccess
³   ³   
³   ----customer
³   ³       .htaccess
³   ³       
³   ----downloadable
³   ³       .htaccess
³   ³       
³   ----import
³   ³       .htaccess
³   ³       
³   ----theme_customization
³           .htaccess
³           
----opt
³   ----magento
³       ----var
³               resource_config.json
³               
----static
        .htaccess

**Comment by daim2k5** [comment]
@mrRonyTran do you still have this issue?
