### ISSUE TITLE
Cart Price Rule not Working as Expected

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#14784]
Cart Price Rule not working, Created a Rule which depends on Product Attribute.

### Preconditions

1. Magento CE 2.2.3 CE, Apache/2.4.23 , PHP version: 7.0.9, OS : Windows Server : Xampp

### Steps to reproduce

1. Create a Product Attribute with Named Brands.
2. Assign it to a Product.
3. Create Cart Price Rule for all websites and stores with All types of customer groups allow.
4. Create new Action with Fixed amount Discount 10
5. Action is If Product attribute isn't "Nike" Than apply discount.
6. Add 2 products to Cart, One Contains Nike Brand and another Not Nike.

![image](https://user-images.githubusercontent.com/36662131/39048624-c875a686-44bb-11e8-9bf3-4b560463b005.png)

![image](https://user-images.githubusercontent.com/36662131/39049540-7d2d15f2-44bf-11e8-8359-ae0d6d7888bc.png)

### Expected result
1.  Discount should only be apply to non-Nike Product.

### Actual result

1. Discount applied successfully with Message "You used coupon code "H20".

**Comment by VZeroCool** [comment]
I can also able reproduce this issue in 2.1 CE as well.

**Comment by ghost** [comment]
@VZeroCool, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by VZeroCool** [comment]
@engcom-backlog-pb @engcom-backlog-nazar What's status of this is this resolved or not ?

**Comment by bruce-gemberling** [comment]
On Magento 2.3 I have my Cart Price rule set up to give a 5% discount on any product in a specific attribute set. However, when a product of the attribute set that I chose to give a discount on is added to my cart the coupon works correctly. When I add other products of other attribute sets (not allowed by coupon) the 5% is calculated on the combined subtotal of all cart products instead of only on only on the product in my chosen attribute set. I have even changed up my coupon to make it only apply to one SKU but the discount still applies to the who subtotal incorrectly.

**Comment by Puru2016** [comment]
I am also facing cart rule (action) issue, I have mention my issue here in details:-
https://magento.stackexchange.com/questions/299864/magento2-cart-rule-not-working-properly

Please update here if any one find any solution or idea to fix this.

**Comment by dpavic** [comment]
Hello, 
I wanted to work on this, but it looks like it is fixed. 
On Magento 2.4.1 i was not able to reproduce this. 
I have created Product attribute with name "Brands", and assign it to "Wayfarer Messenger Bag" product 
I got Expected result: 
Discount was only applied on the products that are without "Nike" attribute. 
When in cart only product that contains "Nike" attribute, coupon was not applied

![Screenshot 2020-12-17 at 16 43 13](https://user-images.githubusercontent.com/5398633/102510213-aa7ccb80-4087-11eb-893d-c67d460bdc0a.png)

![Screenshot 2020-12-17 at 16 42 19](https://user-images.githubusercontent.com/5398633/102510293-c3857c80-4087-11eb-8c7f-9d7648f577e3.png)

![image](https://user-images.githubusercontent.com/5398633/102510705-355dc600-4088-11eb-9d61-5db006564342.png)

![image](https://user-images.githubusercontent.com/5398633/102510757-47d7ff80-4088-11eb-8512-908f5f74b3fe.png)

**Comment by dazimax** [comment]
This might be helpful.

On M2 2.3.5 there is a validation filter before apply the cart rules on the frontend cart. It will make sure that your added cart rule is correctly indexed and added to `magento_salesrule_filter` table. Otherwise, it won't automatically apply to the cart on the frontend.

So make sure to reindex `magento indexer:reindex salesrule_rule` after you have added a new cart rule on the admin side. Then it should be correctly applied if all the rule conditions are valid.

Line 171 - vendor/magento/module-sales-rule/Model/Validator.php

`protected function _getRules(Address $address = null)
    {
        $addressId = $this->getAddressId($address);
        $key = $this->getWebsiteId() . '_'
            . $this->getCustomerGroupId() . '_'
            . $this->getCouponCode() . '_'
            . $addressId;
        if (!isset($this->_rules[$key])) {
            $this->_rules[$key] = $this->_collectionFactory->create()
                ->setValidationFilter(
                    $this->getWebsiteId(),
                    $this->getCustomerGroupId(),
                    $this->getCouponCode(),
                    null,
                    $address
                )
                ->addFieldToFilter('is_active', 1)
                ->load();
        }
        return $this->_rules[$key];
    }`

Cheers!

**Comment by engcom-Bravo** [comment]
Hi @VZeroCool,

Thanks for your reporting and collaboration.

We have verified the issue in latest 2.4-develop instance and the issue is no more reproducible hence we are closing this issue.

Please feel free to reopen the issue if you are still facing any issue.

Thanks.
