### ISSUE TITLE
Impossible to change configurable product attributes position on PDP

### ISSUE THREAD

**Issue by rocketweb** [magento/magento2#14788]
Configurable Product Attributes on product details page are not sorted according to configurable product attribute option position.
It's impossible to change configurable product attributes position. 

### Preconditions

Magento 2.2-develop

### Steps to reproduce

1. Create attributes used for creating configurable product:
First attribute:  'size' with sort_order 100
Second attribute: 'color' with sort_order 200
2. Create configurable product based on this attributes.
3. Now on PDP page would be shown size attribute at the top, color attribute at the bottom under size. 
4. Try to change attributes position. It's required to show color first, size second. 
Via upgrade script try to change attributes position: 
$eavSetup->updateAttribute(Product::ENTITY, 'color','position', 10, 200);
$eavSetup->updateAttribute(Product::ENTITY, 'size','position', 11, 210);

### Expected result

Configurable Product Attributes on product details page should be sorted according to configurable product attribute option position.

### Actual result

Configurable Product Attributes on product details page  sorted by attribute id.

**Comment by ghost** [comment]
@rocketweb, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by AleksLi** [comment]
@rocketweb  I found the reason for that behavior. I've investigated the issue and found that you were changed the wrong arguments.
`$eavSetup->updateAttribute(Product::ENTITY, 'color','position', 10, 200);`
The position you were trying to change is the position of the attribute in [category layer navigation](https://monosnap.com/file/oDfblxX2DK6UNqryKJJt3MQ4B0MZnA) 

The real one you are looking for is [this one](http://joxi.ru/52a5RYetElXRE2). Then go to the [step 2](https://monosnap.com/file/Sgtm3GWJdpJ0H6YpN1VvxUmdrTLHwV). Those changes will be written to `catalog_product_super_attribute` table and affect the position on Product Page.

**@magento-engcom-team  I guess we can close this one.**

**Comment by AleksLi** [comment]
@rocketweb Reach out to me if something is still unclear. 
CC::@magento-engcom-team

**Comment by magento-engcom-team** [comment]
Hi @AleksLi. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
