### ISSUE TITLE
Custom Payment Method doesn't uncheck 'My billing and shipping address are the same'

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#14819]
In Magento 2.2.2, 2.2.3 there is no way to get the Magento behavior on _My billing and shipping address are the same_ checkbox when a new custom Offline Payment Method is used.
### Preconditions

1. Magento 2.2.3 EE (on Magento 2.2.2 CE as well) 
2. PHP 7.1

### Steps to reproduce

1. Create an offline payment method
2. Add a product to cart
3. Go to Checkout
4. Fill in the shipping address
5. Go to Payment Step
6. We have our new payment method, and one more - Checkmo
7. Select Checkmo
8. Under Selected Payment Method -  _My billing and shipping address are the same_ is checked and below we have the billing address = shipping address
![4d0833cc22](https://user-images.githubusercontent.com/15868188/39127239-1890c85a-470d-11e8-9387-3c302485a71e.jpg)
9. Go back to shipping step and change some fields
10. Come back on the Payment Step

### Expected result

1.  _My billing and shipping address are the same_ it should be unchecked
![20e4fedd4b](https://user-images.githubusercontent.com/15868188/39127868-ee3e3e46-470e-11e8-8029-c1097c00855b.jpg)

### Actual result

1. _My billing and shipping address are the same_ is checked, but the address information below doesn't reflect the last changes.
![a67191078b](https://user-images.githubusercontent.com/15868188/39128057-6af2e3ce-470f-11e8-8865-f237e1547f43.jpg)

Also noticed that if the Custom Payment Method is marked as Unavailable, then everything works as needed

Thanks.

**Comment by ghost** [comment]
HI @eduard13  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by eduard13** [comment]
I'm going to work on it.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#17593 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [8739f8ef2ebedbf0b1e7c61cb607864f81507556](https://github.com/magento/magento2/commit/8739f8ef2ebedbf0b1e7c61cb607864f81507556)

The fix will be available with the upcoming 2.2.7 release.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#17628 by @jignesh-baldha in 2.3-develop branch
Related commit(s):
 - [c5b5efd8c27d1812c8de0e6cc1a788cf2fe6e6db](https://github.com/magento/magento2/commit/c5b5efd8c27d1812c8de0e6cc1a788cf2fe6e6db)

The fix will be available with the upcoming 2.3.0 release.

**Comment by miteshdhaduk** [comment]
@jignesh-baldha Thank you for fixing this. It is working properly in Magento 2.2.
