### ISSUE TITLE
Missing css files `styles-l.css` and `styles-m.css` 

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#1482]
Hello,

Try to debugging the code.

Getting below error:
main.CRITICAL: CSS compilation from LESS variable @baseDir is undefined in file var/view_preprocessed/less/frontend/Magento/blank/en_US/css/source/lib/variables/_typography.less in _typography.less on line 16, column 20

**Comment by dfediuk** [comment]
May be my fix can help you? https://github.com/magento/magento2/issues/1467#issuecomment-121040535

**Comment by sunilit42** [comment]
Hey,

#1467 issue same. I checked the solution but still same error.
Here error is different  @baseDir  is undefined.

**Comment by godban** [comment]
Hello @sunilit42 

Strange error, because <code>@baseDir</code> is one of first defined variables in lib https://github.com/magento/magento2/blob/develop/lib/web/css/source/lib/_variables.less#L10 and it should be reachable.
We can't reproduce it in current public version.

Can suggest to try compile styles locally via node.js http://devdocs.magento.com/guides/v1.0/frontend-dev-guide/css-topics/css_debug.html

**Comment by buskamuza** [comment]
@sunilit42 , do you have all resources loaded successfully? Any errors in the browser or not-loaded resources?

**Comment by sunilit42** [comment]
css file not 404 page.

still same error @baseDir not defined

**Comment by vpelipenko** [comment]
@sunilit42, did you try suggestion provided in https://github.com/magento/magento2/issues/1482#issuecomment-121295443 by @godban? We still can't to reproduce this issue locally and need more information about your environment. Do you use the latest 1.0.0-beta version?
