### ISSUE TITLE
User logout changes currency format

### ISSUE THREAD

**Issue by markshust** [magento/magento2#14825]
If a user is logged in, changes the currency format, then logs out, the currency format is switched back to the base/default currency instead of being retained to the visitor's last selection.

### Preconditions
1. Magento version 2.2.3

### Steps to reproduce
1. Admin > Stores > Configuration > General > Currency Setup > Set allowed currencies to Euro and US Dollar. Set Base Currency and Default Display Currency to US Dollar.
2. Clear caches
3. On frontend, login to a customer account
4. Change currency format from USD to EUR
5. Logout

**Variant 2**

1. a On frontend, login to a customer account
2. a Change currency format from USD to EUR
3. a Logout
4. a Change currency format to USD.
5. a Login to user account.

### Expected result
1. Currency format of EUR should be retained

1. a The currency format of the user's last session (database value: quote.quote_currency of EUR) is applied.
2. a The currency format is switched to EUR.

### Actual result
1. Currency format is switched to USD

1. a The currency format of the user's last session (database value: quote.quote_currency of EUR) is not applied on user login.
2. a The currency format of the user's last session (database value: quote.quote_currency of EUR) is overridden by the current session's currency format (USD).

**Comment by ghost** [comment]
Hi @markoshust thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by CarlosBarrosoRamirez** [comment]
I get this one.

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by dimasalamatov** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14825-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14825-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14825-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Sharkozp** [comment]
@magento I am working on it

**Comment by Sharkozp** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Sharkozp. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sharkozp, here is your [Magento instance](https://i-14825-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14825-2-3-develop.instances.magento-community.engineering/admin](https://i-14825-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Sharkozp** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Sharkozp. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by Sharkozp** [comment]
@markshust there is no column _quote.quote_currency_ in Magento 2.3.x. I think it was renamed into _quote.quote_currency_code_ and description of this column is **Quote Currency Code**. Looks like it is responsible for storing Currency code for quote and not for Session

**Comment by Sharkozp** [comment]
@markshust Currency code is storing in Session. During logout process session is destroying and loads default code in this case USD. I think everything working properly and not needed more changes.

**Comment by markshust** [comment]
@Sharkozp i know it is "working as expected", but the workflow is super awkward, and i think it should be changed. i would expect the currency to use my last toggled/selected value, not to switch back and forth by itself.
