### ISSUE TITLE
In Sales Emails no translation using order.getStatusLabel() 

### ISSUE THREAD

**Issue by raymond62** [magento/magento2#14849]
Sending sales emails the label for order status is not translated. 

### Preconditions
1. Magento 2.2.3., PHP 7.0, MySql 5.6

### Steps to reproduce
1. edit order status of any status and creat language labels (image 1)
2. send an email using the sales area in your backoffice (image 2)
3. see the status label in the email (image 3)

### Expected result
1. The status label in the email should get the respective order status label language

### Actual result
1.  edit order status
![grafik](https://user-images.githubusercontent.com/29265078/39242189-76b2e15c-4889-11e8-9dca-9965e9742e9d.png)

2. send an email using the sales area
![grafik](https://user-images.githubusercontent.com/29265078/39242271-ccd2f3ec-4889-11e8-84d6-c05a876cdf6d.png)

3. status label in the email. This should be German in this case
![grafik](https://user-images.githubusercontent.com/29265078/39242341-019fb9d4-488a-11e8-9a6f-11668d329204.png)

I've read this issue, but guess this is not the same
https://github.com/magento/magento2/issues/9014

**Comment by Userr017** [comment]
I have same problem with magento 2.2.5. What is the correctly fix for this without problems?

**Comment by magento-engcom-team** [comment]
Hi @raymond62. Thank you for your report. 
The issue has been fixed in magento/magento2#14914 by @phoenix128 in 2.2-develop branch
Related commit(s):
 - [03e7de4dedd9336dabb90a267acb49b9a044c3f8](https://github.com/magento/magento2/commit/03e7de4dedd9336dabb90a267acb49b9a044c3f8)
 - [5d2b5be882918e36aa328b735c8bd00599b3b5c8](https://github.com/magento/magento2/commit/5d2b5be882918e36aa328b735c8bd00599b3b5c8)
 - [1c9ce8467d3297703e1d899314728df8b387e716](https://github.com/magento/magento2/commit/1c9ce8467d3297703e1d899314728df8b387e716)
 - [18ca5f033382e5ba547faa8700eaabe0e4ce3822](https://github.com/magento/magento2/commit/18ca5f033382e5ba547faa8700eaabe0e4ce3822)
 - [bd80b1ad6b9d68b9b1fb8a2855ac796ad87cd498](https://github.com/magento/magento2/commit/bd80b1ad6b9d68b9b1fb8a2855ac796ad87cd498)
 - [2e634e43bda15e01140c46989f2ecea807aa9f9a](https://github.com/magento/magento2/commit/2e634e43bda15e01140c46989f2ecea807aa9f9a)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @raymond62. Thank you for your report. 
The issue has been fixed in magento/magento2#19182 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [bbf124759cf3d27dd4bfee4a9c4e3a3969bc59ff](https://github.com/magento/magento2/commit/bbf124759cf3d27dd4bfee4a9c4e3a3969bc59ff)
 - [3998176c0995dbb912977719039fdac956c8a43c](https://github.com/magento/magento2/commit/3998176c0995dbb912977719039fdac956c8a43c)
 - [2bc10a2484462d6554dbc07655b68e56ca4f72f2](https://github.com/magento/magento2/commit/2bc10a2484462d6554dbc07655b68e56ca4f72f2)
 - [149d9e12a12e8da0bc3066e6e97e72f66adf497c](https://github.com/magento/magento2/commit/149d9e12a12e8da0bc3066e6e97e72f66adf497c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by aqdennis** [comment]
Are you sure it's fixed, because I'm still having this in version 2.3.2 ??

**Comment by Djohn12** [comment]
Hi,

I just came accross the issue in Magento 2.3.5-p2

The template /vendor/magento/module-sales/view/frontend/email/order_update.html is still displaying order_status using

$order_data.frontend_status_label

That variable is set in /vendor/magento/module-sales/Model/Order/Email/Sender/OrderCommentSender.php and is not getting the proper storeId. Thus the value cannot be properly translated.

'order_data' => [ 'customer_name' => $order->getCustomerName(), 'frontend_status_label' => $order->getFrontendStatusLabel() ]

The use of $order.getFrontendStatusLabel() inside the template is working fine.

Do you plan on updating the template to implement the method getFrontendStatusLabel() so every status can be translated accordingly ?
