### ISSUE TITLE
Sitemap generation cron job flushes entire cache

### ISSUE THREAD

**Issue by scottsb** [magento/magento2#14857]
### Preconditions
Magento 2.1.12
Magento 2.2.3 (suspected based on looking relevant code, but not confirmed)

### Steps to reproduce and actual result
Look at debug.log output at midnight (configured sitemap cron schedule) in store timezone for this output:

`main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":[],"mode":"all"},"is_exception":false} []`

This indicates the entire cache was flushed.

### Expected result
Only FPC is flushed.

### Discussion
The class `\Magento\Sitemap\Model\Sitemap` sets `$_cacheTag = true`, which `AbstractModel::afterSave()` and `cleanModelCache()` understand to mean it should flush the entire cache.

This was introduced by the core team's fix for MAGETWO-47607 (#2802). (Note that this is not  the commit that #2802 was officially closed for; it seems that two different fixes for the same issue were merged.) See commits 6edb0da (2.2.x) and 3cd22e2 (backport to 2.1.x).

**Comment by ghost** [comment]
Hi @scottsb , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by larsroettig** [comment]
Hi @scottsb,
my colleague David fixed the bug today.

best regards,

Lars

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @scottsb. Thank you for your report. 
The issue has been fixed in magento/magento2#20818 by @david-fuehr in 2.3-develop branch
Related commit(s):
 - [b9190b3e0dc8118043d10d3c652243fc439ac20c](https://github.com/magento/magento2/commit/b9190b3e0dc8118043d10d3c652243fc439ac20c)
 - [ebc266b5e0f229c644a4329f7463696020b6a681](https://github.com/magento/magento2/commit/ebc266b5e0f229c644a4329f7463696020b6a681)
 - [28a9720406a0d0f22e0b35c6d4e99efb456df9c9](https://github.com/magento/magento2/commit/28a9720406a0d0f22e0b35c6d4e99efb456df9c9)

The fix will be available with the upcoming 2.3.2 release.
