### ISSUE TITLE
Adding an * to do a customer search.

### ISSUE THREAD

**Issue by taylored2** [magento/magento2#14855]
When doing a search in the Customer area of Magento 2. I added an * in the search. When adding the * Magento stays locked and the following message pops up "Something went wrong with processing the default view and we have restored the filter to its original state." .   

![screenshot 96](https://user-images.githubusercontent.com/35534987/39272368-b488d426-48a9-11e8-8e69-a0356caca2ee.png)

Preconditions
1.  We are at Megento 2.2.1CE

Steps to reproduce
1. Login to Magento
2. In the Dashboard - Select Customers
3. Select All Customers
4. In the search add an *
5. Click Search

Expected Result
1. Any Customer with an * should be found

 Actual result

1. Get an error message
2. "Something went wrong with processing the default view and we have restored the filter to its original state."

**Comment by magento-engcom-team** [comment]
Hi @taylored2. Thank you for your report. 
The issue has been fixed in magento/magento2#14905 by @phoenix128 in 2.2-develop branch
Related commit(s):
 - [187ab1f0b5b4bffa5ad5fb69c0c6daac0c5f2498](https://github.com/magento/magento2/commit/187ab1f0b5b4bffa5ad5fb69c0c6daac0c5f2498)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @taylored2. Thank you for your report. 
The issue has been fixed in magento/magento2#15077 by @adrian-martinez-interactiv4 in 2.3-develop branch
Related commit(s):
 - [01b546fe244246dbe033217918e4d0e6c294b2d2](https://github.com/magento/magento2/commit/01b546fe244246dbe033217918e4d0e6c294b2d2)

The fix will be available with the upcoming 2.3.0 release.
