### ISSUE TITLE
Refactoring: Code duplication EmailSender / ShipmentSender and so on

### ISSUE THREAD

**Issue by amenk** [magento/magento2#14885]
These classes do pretty much the same:
`/app/code/Magento/Sales/Model/Order/Shipment/Sender/EmailSender.php`

`/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php`

Should be refactored into one.
What is the reason we have two? Which one should be preferred?

### Preconditions
Magento 2.4-develop

### Steps to reproduce
1. Observe two classes.

`app/code/Magento/Sales/Model/Order/Shipment/Sender/EmailSender.php`
and
`app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php`

### Expected result
Should have different behaviors, or refactored into one.

### Actual result
Two classes almost the same.

**Comment by engcom-backlog-nickolas** [comment]
Hello @amenk, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by korostii** [comment]
Ran into this, as well.
FYI it seems that for some reason the `../Shipment/Sender/EmailSender.php` gets invoked when a shipment is created via API (so, both classes are used by Magento). 
This can be a rather nasty surprise if you attempt to modify the corresponding behaviour using a di.xml plugin as you'll need to declare two plugins at once.

**Comment by rvoronovmeticulosity** [comment]
https://github.com/magento/magento2/commit/0b4d732c8b07343e200251bbbed3730836588116
@dvoskoboinikov for what reasons the https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Shipment/Sender/EmailSender.php was added considering that we already had https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php

**Comment by sivaschenko** [comment]
Hi @rvoronovmeticulosity https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Shipment/Sender/EmailSender.php was introduced to work with data interfaces instead of the concrete model. So I believe https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php can be marked as deprecated and client code refactored to use the new service.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30135` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vigneshbalasubramani** [comment]
#mm20in

**Comment by magento-engcom-team** [comment]
@vigneshbalasubramani thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your report. 
The issue has been fixed in magento/magento2#26714 by @drpayyne in 2.4-develop branch
Related commit(s):
 - [4e1bfdeda9d7da91509a3f738e881ad92614a577](https://github.com/magento/magento2/commit/4e1bfdeda9d7da91509a3f738e881ad92614a577)
 - [2f591a8805a03ca0479724a695baeb67586a2e59](https://github.com/magento/magento2/commit/2f591a8805a03ca0479724a695baeb67586a2e59)
 - [5967ed459c507ca6f62829a52623ed4167e45409](https://github.com/magento/magento2/commit/5967ed459c507ca6f62829a52623ed4167e45409)
 - [997a0de132e38cc4bf4e0d94a9f65dbbc5b30bc5](https://github.com/magento/magento2/commit/997a0de132e38cc4bf4e0d94a9f65dbbc5b30bc5)

The fix will be available with the upcoming 2.4.0 release.
