### ISSUE TITLE
product_types.xml doesn't allow numbers in modelInstance

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#14882]
### Preconditions
1.  Magento  v2.2.2

### Steps to reproduce
1. Have a module with numbers in vendor name
2. Create `product_types.xml` and define a new type

### Expected result
1.  No XSD validation errors

### Actual result
1. XSD validation error that modelName does not validate.

[product_types_base.xsd](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/etc/product_types_base.xsd) does not allow numbers in the `modelName` type. 
Furthermore, searching for the pattern `[a-zA-Z_\\]` finds more files where this might be a problem.

Similar to https://github.com/magento/magento2/issues/4470.

**Comment by ghost** [comment]
@domeglic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @lisovyievhenii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your report. 
The issue has been fixed in magento/magento2#20617 by @lisovyievhenii in 2.3-develop branch
Related commit(s):
 - [eb0653c69918a8381f6f22b9bc4eb316feba6a36](https://github.com/magento/magento2/commit/eb0653c69918a8381f6f22b9bc4eb316feba6a36)
 - [9948dfeae767d48375058758919f13a1def1153b](https://github.com/magento/magento2/commit/9948dfeae767d48375058758919f13a1def1153b)
 - [37465249c5d9505f5de5494b199158cbbb14ecdc](https://github.com/magento/magento2/commit/37465249c5d9505f5de5494b199158cbbb14ecdc)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your report. 
The issue has been fixed in magento/magento2#21598 by @lisovyievhenii in 2.2-develop branch
Related commit(s):
 - [9688409fa3c1ec27575bda44dec9539615d0495a](https://github.com/magento/magento2/commit/9688409fa3c1ec27575bda44dec9539615d0495a)
 - [6bc7575f15364210c091a9a6002fb83988f6c54d](https://github.com/magento/magento2/commit/6bc7575f15364210c091a9a6002fb83988f6c54d)
 - [1c45357d60ef44975e12bad55fa7f2ef9107cad9](https://github.com/magento/magento2/commit/1c45357d60ef44975e12bad55fa7f2ef9107cad9)
 - [ab8d312286fa448f408727ea6fff9e790424cb34](https://github.com/magento/magento2/commit/ab8d312286fa448f408727ea6fff9e790424cb34)

The fix will be available with the upcoming 2.2.9 release.
