### ISSUE TITLE
Change Password warning message appear two times

### ISSUE THREAD

**Issue by cnviradiya** [magento/magento2#14895]
### Preconditions

1.  Magento Version 2.2.0
2. Php version 7.1.8, MySQL  version 5.0.12

### Steps to reproduce

1. Once I login to admin panel It will ask for the change password
2. Now, I am doing change password same as the previous one
3. It will show the multiple time warning message for the change password `It's time to change your password.`

### Expected result

1. Warning message will be one time appear `It's time to change your password.`

### Actual result

1. ![change_password_warning_message_twice_28_04_2018](https://user-images.githubusercontent.com/9442993/39395827-40479868-4b01-11e8-9e80-23aa70438bb6.png)
2. ![change_password_warning_message_twice_28_04_2018](https://user-images.githubusercontent.com/9442993/39395865-b870d6d8-4b01-11e8-9480-2047752a47b7.png)

[Screenshot, logs]

I'm using windows 10Pro Operating System.

**Comment by VladimirZaets** [comment]
Hi @cnviradiya. Thank you for your report. 
The issue has been fixed in magento/magento2#14897 by @phoenix128 in 2.3-develop branch
Related commit(s):
 - [0abb68250cd1b8ed94bcda557b1ec4b2849e2969](https://github.com/magento/magento2/commit/0abb68250cd1b8ed94bcda557b1ec4b2849e2969)
 - [8d8706efe5330a62217603bfea8ee511ae138bd5](https://github.com/magento/magento2/commit/8d8706efe5330a62217603bfea8ee511ae138bd5)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @cnviradiya. Thank you for your report. 
The issue has been fixed in magento/magento2#15774 by @sanjay-wagento in 2.2-develop branch
Related commit(s):
 - [b2cc966da3a6bcc925035e12a950e636847326f8](https://github.com/magento/magento2/commit/b2cc966da3a6bcc925035e12a950e636847326f8)
 - [cfe58e16b5159f97fbf8b1246a6e5d75caaaf9e0](https://github.com/magento/magento2/commit/cfe58e16b5159f97fbf8b1246a6e5d75caaaf9e0)

The fix will be available with the upcoming 2.2.6 release.
