### ISSUE TITLE
bookmark views become uneditable after deleting the first bookmark view.

### ISSUE THREAD

**Issue by Jakhotiya** [magento/magento2#14913]
For product listing grid, I created multiple bookmark views like in following screenshot. When **I delete the first view I created ** all other views become uneditable except the last view. 

![screen shot 2018-04-30 at 2 59 47 pm](https://user-images.githubusercontent.com/9327315/39421823-75e0c5ac-4c88-11e8-83fc-6371d49bb626.png)

![screen shot 2018-04-30 at 3 00 14 pm](https://user-images.githubusercontent.com/9327315/39421839-8742291c-4c88-11e8-847c-ef04a25c7088.png)

The highlighted view in screeshot has become uneditable. If I don't delete the first view then they all remain editable. 

### Preconditions
1. Magento 2.2.3 or 2.2-develop branch **Updated(09/25/2019):** Still actual on `2.3-develop`
2. Chrome 65 (That's what I have)

### Steps to reproduce
1.  Login to admin and go to Catalog->Products. You should see product grid
2. Change the sorting order of columns and save this new view. In similar way by adding filters or adding new columns create multiple bookmark views. I created atleast 8 of them.
3. Now refresh the page. Switch back to default view in bookmarks.
4. **Delete the first bookmark you created**
5. Try editing any other bookmark except last one.

### Expected result
1. All the bookmarks should be editable 

### Actual result
1. Only last one is editable.

**Comment by ghost** [comment]
Hi @Jakhotiya thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ssp58bleuciel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by VladimirZaets** [comment]
Hi @Jakhotiya. Thank you for your report. 
The issue has been fixed in magento/magento2#26263 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [fe984387fc73f559599f27798642e5c22b55ae62](https://github.com/magento/magento2/commit/fe984387fc73f559599f27798642e5c22b55ae62)

The fix will be available with the upcoming 2.4.0 release.
