### ISSUE TITLE
Invalid Template with Custom Theme Applied by User Agent

### ISSUE THREAD

**Issue by C0D31GN1T3R** [magento/magento2#14932]
### Preconditions

Magento 2.2.2

### Steps to reproduce

1.  Register a new theme with no parent.
2.  Create `Magento_Theme` dir and either add a new block in `footer` container with a template that doesn't exist in the core files, or edit the template of an existing block giving it a new template that doesn't exist in the core files.

For example:

    <referenceContainer name="footer">
        <block class="Magento\Framework\View\Element\Template" name="some.block" template="Magento_Theme::some-template-that-exists-in-my-custom-theme-but-not-in-core.phtml" />
    </referenceContainer>
3.  In chrome for example under network change user agent to whatever is required to enable the theme and visit any product view page.

### Expected result

1. When user agent matches what is required to enable custom theme, everything works as normal but with custom theme applied.

### Actual result

1. Invalid Template Error is produced relating to the block which uses a template that is not available in the core files.

For some reason when a theme is a applied based on user agent, it is not applied to certain sections.  The `footer` is one, another is when trying to override `review.phtml` from `Magento_Reviews` dir.  In the case of the `footer` because I was using templates that didn't exist in the base module I get the invalid template error because Magento is not applying my theme but looking for my templates in the base module.  In the case of `Magento_Reviews` `reviews.phtml` there are no errors as the file exists in the base module but the override has no effect as my theme is not applied.  

This seems to be selective as custom templates in the `header` section work fine on the product view page.  I've only noticed the `footer` and `reviews.phtml` issue but there could be others.

**Comment by drew7721** [comment]
I seem to have a similar issue. Any fix for this? @C0D31GN1T3R

**Comment by C0D31GN1T3R** [comment]
Sorry no I was only using user agent based theme switching to quickly test various themes on the frontend.  I just stopped using it, it didn't cause me a major headache so I didn't bother digging through the code.

**Comment by ghost** [comment]
Duplicate of #16074

**Comment by magento-engcom-team** [comment]
Hi @C0D31GN1T3R. Thank you for your report. 
The issue has been fixed in magento/magento2#19124 by @drew7721 in 2.3-develop branch
Related commit(s):
 - [1becee9bb4114318c89f54b45c10b6b60cdc9cee](https://github.com/magento/magento2/commit/1becee9bb4114318c89f54b45c10b6b60cdc9cee)
 - [b8940db9514c672c9e191bbb33172884a524a993](https://github.com/magento/magento2/commit/b8940db9514c672c9e191bbb33172884a524a993)
 - [fd26b94dc1950845a135879937ce7ce0d8f8b8b4](https://github.com/magento/magento2/commit/fd26b94dc1950845a135879937ce7ce0d8f8b8b4)
 - [47e42a969d443715bf483f9e90eabfd2a141c930](https://github.com/magento/magento2/commit/47e42a969d443715bf483f9e90eabfd2a141c930)
 - [4b6100d1e991fc56f7ff9f8e0f0be0db7192328e](https://github.com/magento/magento2/commit/4b6100d1e991fc56f7ff9f8e0f0be0db7192328e)
 - [b8442a15bb1fed7843166bdd4437c009ef03a82f](https://github.com/magento/magento2/commit/b8442a15bb1fed7843166bdd4437c009ef03a82f)

The fix will be available with the upcoming 2.3.1 release.
