### ISSUE TITLE
Unnecessary recalculation of product list pricing causes huge slowdowns

### ISSUE THREAD

**Issue by paales** [magento/magento2#14941]
### Preconditions

1. 2.2.2
2. PHP 7.0, MySQL 5.6

### Steps to reproduce

1. Create a catalog where prices are including tax + prices are shown including tax.
2. Go to a category page and show 100 products per page.

### Expected result

1. System does price calculation very efficiently

### Actual result

1. It recalculates the tax while it shouldn't be doing that.

![schermafbeelding 2018-05-02 om 14 24 14-1](https://user-images.githubusercontent.com/1244416/39533827-5b4441f2-4e30-11e8-8c78-28be69cce60b.png)

If we can disable the recalculation of tax we get the following result:
![slack-imgs](https://user-images.githubusercontent.com/1244416/39533865-73615c2a-4e30-11e8-95cc-288abcdc09bc.png)

Please note that this is _with_ xdebug enabled, so overal performance is bad over here, but the percentual difference is present with xdebug disabled.

The problem seems to lie in the following method:
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Tax/Model/Config.php#L847-L849

The highlighted line should be `false`. If we fix that line the calculation time for the price template goes from 4.3 seconds to 1.6 seconds. This means a 2.7 seconds performance improvement.

In the last chart you can still see room for improvement as the `final_price.phtml` tempalte still takes 31% of total page load time, while I would expect this to be a lot less. So investigating further still.

**Comment by magento-engcom-team** [comment]
Hi @paales. Thank you for your report. 
The issue has been fixed in magento/magento2#15089 by @JeroenVanLeusden in 2.2-develop branch
Related commit(s):
 - [c5536d3721989b97ec0bc02ec174d898067d4dcb](https://github.com/magento/magento2/commit/c5536d3721989b97ec0bc02ec174d898067d4dcb)

The fix will be available with the upcoming 2.2.5 release.

**Comment by ishakhsuvarov** [comment]
Hi @paales. Thank you for your report. 
The issue has been fixed in magento/magento2#15445 by @JeroenVanLeusden in 2.1-develop branch
Related commit(s):
 - [3d05e6b5361d28877ac97e7dfd264b8b5ccf6482](https://github.com/magento/magento2/commit/3d05e6b5361d28877ac97e7dfd264b8b5ccf6482)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @paales. Thank you for your report. 
The issue has been fixed in magento/magento2#15200 by @JeroenVanLeusden in 2.3-develop branch
Related commit(s):
 - [08cf8b878a9919b95b44ef69b04830532d487c24](https://github.com/magento/magento2/commit/08cf8b878a9919b95b44ef69b04830532d487c24)

The fix will be available with the upcoming 2.3.0 release.
