### ISSUE TITLE
Store Email Addresses are not used anymore

### ISSUE THREAD

**Issue by chequille** [magento/magento2#14945]
Updated to 2.2.4
In 2.2.3, emails sent to the customer (f.e. order acknowledgment) used the defined email address and sendername given in "Store Email Addresses".
This is not the case now, no sendername and no email address in the mail to the customer.

What the hell is going on here?
Somebody a solution for this?

BR
Chequille

**Comment by gwharton** [comment]
Duplicate of #14952

**Comment by magento-engcom-team** [comment]
Hi @chequille. Thank you for your report. 
The issue has been fixed in magento/magento2#18471 by @gwharton in 2.3-develop branch
Related commit(s):
 - [ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3](https://github.com/magento/magento2/commit/ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3)
 - [e16ff74e4f5f24a4a2530b6aced6ef50032515e0](https://github.com/magento/magento2/commit/e16ff74e4f5f24a4a2530b6aced6ef50032515e0)
 - [621d2cfeaf8e0a15e592cdc001c856385b3cbd83](https://github.com/magento/magento2/commit/621d2cfeaf8e0a15e592cdc001c856385b3cbd83)
 - [b6f9e48289119117df230b6578ac9ff3d69e4996](https://github.com/magento/magento2/commit/b6f9e48289119117df230b6578ac9ff3d69e4996)
 - [0dc85785e522e2be8c72dfeaee7e9f5054195034](https://github.com/magento/magento2/commit/0dc85785e522e2be8c72dfeaee7e9f5054195034)
 - [122019c953037df74ef97245a42b274eae2e6639](https://github.com/magento/magento2/commit/122019c953037df74ef97245a42b274eae2e6639)
 - [193c6c2f6facf7276c1c8858d29ea3b847062ef5](https://github.com/magento/magento2/commit/193c6c2f6facf7276c1c8858d29ea3b847062ef5)
 - [bd0aa57cc837918335015d051f08cf380dc186d0](https://github.com/magento/magento2/commit/bd0aa57cc837918335015d051f08cf380dc186d0)
 - [523b0464966f81f1f01aa13073092bfddf363219](https://github.com/magento/magento2/commit/523b0464966f81f1f01aa13073092bfddf363219)
 - [424929fe9aee1005601cc2c9c7ad0090741be723](https://github.com/magento/magento2/commit/424929fe9aee1005601cc2c9c7ad0090741be723)
 - [c32ca7a0d58cbc57276349b26eb5ecd38451fd2d](https://github.com/magento/magento2/commit/c32ca7a0d58cbc57276349b26eb5ecd38451fd2d)
 - [e39ce7a3f2a7e6ee134cff9a097b7321756c32cf](https://github.com/magento/magento2/commit/e39ce7a3f2a7e6ee134cff9a097b7321756c32cf)
 - [99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31](https://github.com/magento/magento2/commit/99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31)
 - [f171c9d6ab035439ffb6374ec14dd8d51123dcd2](https://github.com/magento/magento2/commit/f171c9d6ab035439ffb6374ec14dd8d51123dcd2)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @chequille. Thank you for your report. 
The issue has been fixed in magento/magento2#18472 by @gwharton in 2.2-develop branch
Related commit(s):
 - [82a635b3a4eb0fd0e2f030d82495ab717ee11db5](https://github.com/magento/magento2/commit/82a635b3a4eb0fd0e2f030d82495ab717ee11db5)
 - [16afc0962463261e4464456b9bdaad4e8f3be924](https://github.com/magento/magento2/commit/16afc0962463261e4464456b9bdaad4e8f3be924)
 - [47c5f72c9196dc77b50db3c36ec99719a69a18a0](https://github.com/magento/magento2/commit/47c5f72c9196dc77b50db3c36ec99719a69a18a0)
 - [8d7a4513ddf4b759a6c6a0d2ace04aa714a396df](https://github.com/magento/magento2/commit/8d7a4513ddf4b759a6c6a0d2ace04aa714a396df)
 - [a7cd527a6896c3a2f204e2771b92496ef4089f4e](https://github.com/magento/magento2/commit/a7cd527a6896c3a2f204e2771b92496ef4089f4e)
 - [491d7f133591c64346cb54c2392d0ef212333b1a](https://github.com/magento/magento2/commit/491d7f133591c64346cb54c2392d0ef212333b1a)
 - [490e5d22074224ec1965a391abfffc379c31d0ee](https://github.com/magento/magento2/commit/490e5d22074224ec1965a391abfffc379c31d0ee)
 - [b19b3ed195b870f16a00c673e435b5b9b8184227](https://github.com/magento/magento2/commit/b19b3ed195b870f16a00c673e435b5b9b8184227)
 - [9f34fd631a55ded6d8a458d219edfc23c1bc5f9b](https://github.com/magento/magento2/commit/9f34fd631a55ded6d8a458d219edfc23c1bc5f9b)
 - [66478ec59d6cbf77d538f2ea112f32997e491bf8](https://github.com/magento/magento2/commit/66478ec59d6cbf77d538f2ea112f32997e491bf8)
 - [cc34f00113e1e644e92002f82d34c4bf36aa0e26](https://github.com/magento/magento2/commit/cc34f00113e1e644e92002f82d34c4bf36aa0e26)
 - [fb572d887f0ce156c8f3ac149de7b8f06835623d](https://github.com/magento/magento2/commit/fb572d887f0ce156c8f3ac149de7b8f06835623d)
 - [59a4e57a0c36671ff84e8398f413253610a512ac](https://github.com/magento/magento2/commit/59a4e57a0c36671ff84e8398f413253610a512ac)
 - [a8bcb8bb8442a649bf1e62400ca6f147023e53c6](https://github.com/magento/magento2/commit/a8bcb8bb8442a649bf1e62400ca6f147023e53c6)
 - [573cf7a9fee7c2d8ca9c1c25fe909c93ccf06c49](https://github.com/magento/magento2/commit/573cf7a9fee7c2d8ca9c1c25fe909c93ccf06c49)
 - [ef635bf6b8ecf67c729deb38df05c81b9e5b5359](https://github.com/magento/magento2/commit/ef635bf6b8ecf67c729deb38df05c81b9e5b5359)
 - [daa8996bbda2e7ca938a7e3a3e8afc40502cd98f](https://github.com/magento/magento2/commit/daa8996bbda2e7ca938a7e3a3e8afc40502cd98f)

The fix will be available with the upcoming 2.2.9 release.
