### ISSUE TITLE
sale_sequence_* records are not removed on store view deletion

### ISSUE THREAD

**Issue by tim-bezhashvyly** [magento/magento2#14958]
`sale_sequence_meta` and `sales_sequence_profile` records are not removed upon store deletion.

### Preconditions
1. Magento 2.2

### Steps to reproduce
1. Delete existing store view

### Expected result
1. `sale_sequence_meta` and `sales_sequence_profile` contain no records referencing to removed store

### Actual result
1. `sale_sequence_meta` and `sales_sequence_profile` do contain records referencing to removed store

**Comment by ghost** [comment]
@tim-bezhashvyly, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @LlZARD, @Bartlomiejsz. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-93931` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @LlZARD. Thank you for your report. 
The issue has been fixed in magento/magento2#22296 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [8529467d79abb67a63db2a0128f6723ec1c06af9](https://github.com/magento/magento2/commit/8529467d79abb67a63db2a0128f6723ec1c06af9)
 - [4c4ae5350087e8e441d1513d45e1e372b15d2ec3](https://github.com/magento/magento2/commit/4c4ae5350087e8e441d1513d45e1e372b15d2ec3)
 - [774d40f3dd91ec3cf0054646054efe546d49e069](https://github.com/magento/magento2/commit/774d40f3dd91ec3cf0054646054efe546d49e069)
 - [8dab9d767415da4faabc84a25ade4908ff84df45](https://github.com/magento/magento2/commit/8dab9d767415da4faabc84a25ade4908ff84df45)
 - [4385c2f5624746a5d88a37edd71b9919ce10ba44](https://github.com/magento/magento2/commit/4385c2f5624746a5d88a37edd71b9919ce10ba44)
 - [78bfbc86b622c9d92332e46e40f4bc4728c3432e](https://github.com/magento/magento2/commit/78bfbc86b622c9d92332e46e40f4bc4728c3432e)
 - [3ff5c067af467c2ee3e36fcaf0cbc478e1022ee8](https://github.com/magento/magento2/commit/3ff5c067af467c2ee3e36fcaf0cbc478e1022ee8)
 - [85b07306e2d3c6764464e382746bc012f5610645](https://github.com/magento/magento2/commit/85b07306e2d3c6764464e382746bc012f5610645)
 - [309a25ffd61565ab73f688bfff3da72ef877fd25](https://github.com/magento/magento2/commit/309a25ffd61565ab73f688bfff3da72ef877fd25)
 - [c83a28376898d1bde669bcbae2d3302697b08f95](https://github.com/magento/magento2/commit/c83a28376898d1bde669bcbae2d3302697b08f95)
 - [328bc51d3838dcd713fe5e4d6b81cade75528708](https://github.com/magento/magento2/commit/328bc51d3838dcd713fe5e4d6b81cade75528708)
 - [7c078cf8158580bf704c6fb79e0bcd8e26ffe5d7](https://github.com/magento/magento2/commit/7c078cf8158580bf704c6fb79e0bcd8e26ffe5d7)
 - [76b2085cc7b82dc957728183d5dec800ec18be4a](https://github.com/magento/magento2/commit/76b2085cc7b82dc957728183d5dec800ec18be4a)
 - [11f013c30d876f3c182b4d901e0530d79e01bcff](https://github.com/magento/magento2/commit/11f013c30d876f3c182b4d901e0530d79e01bcff)
 - [68d1bed1d13ef3c68bc3da0bb578389db56e795c](https://github.com/magento/magento2/commit/68d1bed1d13ef3c68bc3da0bb578389db56e795c)
 - [48f213d39301c8b3c49523f38107e15e8bcc7d72](https://github.com/magento/magento2/commit/48f213d39301c8b3c49523f38107e15e8bcc7d72)
 - [6458cc851791e1c3e38ffa3d5410fa111278e156](https://github.com/magento/magento2/commit/6458cc851791e1c3e38ffa3d5410fa111278e156)
 - [94b6a170a0016e1416f493514d82027436a35395](https://github.com/magento/magento2/commit/94b6a170a0016e1416f493514d82027436a35395)
 - [f894321ca02705f8131579a224a1c416669a5a1c](https://github.com/magento/magento2/commit/f894321ca02705f8131579a224a1c416669a5a1c)

The fix will be available with the upcoming 2.4.0 release.
