### ISSUE TITLE
Disabling product does not remove it from the flat index

### ISSUE THREAD

**Issue by ktruehl** [magento/magento2#14966]
### Preconditions
1. Magento 2.2.3
2. PHP 7.1
3. Apache

### Steps to reproduce
1. Install Magento 2.2.3 together with the sample data set.
2. Make sure cron is run every minute (`bin/magento cron:run`).
3. Make sure the config setting `Use Flat Catalog Product` is set to `Yes`.
4. Make sure the flat index is up-to-date: `bin/magento index:reindex catalog_product_flat`.
5. Choose an enabled product in the Magento admin backend. Say its ID is `X`.
6. Make sure that there exists an entry in table `catalog_product_flat_1` with `entity_id = X`. If not, you've done something wrong.
7. Now, in the Magento admin backend, disable the product.
8. Wait a few minutes.
9. Check whether the table `catalog_product_flat_1` still contains an entry with `entity_id = X`.

### Expected result
1. The table `catalog_product_flat_1` should contain no entry with `entity_id = X`.

### Actual result
1. The table `catalog_product_flat_1` contains an entry with `entity_id = X`.

**Comment by VladimirZaets** [comment]
Hi @ktruehl. Thank you for your report. 
The issue has been fixed in magento/magento2#15019 by @lewisvoncken in 2.2-develop branch
Related commit(s):
 - [0d350810fd112c53f802fb36d78cd034e404197f](https://github.com/magento/magento2/commit/0d350810fd112c53f802fb36d78cd034e404197f)
 - [c6196d7121569c1f82615ca6dcb9626d9285e972](https://github.com/magento/magento2/commit/c6196d7121569c1f82615ca6dcb9626d9285e972)
 - [2d6fb6253dff51c91bd6107ddc4bb7e74bf7e618](https://github.com/magento/magento2/commit/2d6fb6253dff51c91bd6107ddc4bb7e74bf7e618)
 - [38bd9d381bc14ecc337a6707d96a767da7148f98](https://github.com/magento/magento2/commit/38bd9d381bc14ecc337a6707d96a767da7148f98)
 - [219024c2e3d9b2355fdfb4a8c811cfd172cebba5](https://github.com/magento/magento2/commit/219024c2e3d9b2355fdfb4a8c811cfd172cebba5)

The fix will be available with the upcoming 2.2.6 release.

**Comment by ishakhsuvarov** [comment]
Hi @ktruehl. Thank you for your report. 
The issue has been fixed in magento/magento2#16791 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [68b6e67383b1e31a335b4b5331357ba7e5ad54a1](https://github.com/magento/magento2/commit/68b6e67383b1e31a335b4b5331357ba7e5ad54a1)
 - [673a935ed7dd66769c871df2607431a582ad2e91](https://github.com/magento/magento2/commit/673a935ed7dd66769c871df2607431a582ad2e91)
 - [80fbc9ed8672d5257213e6d7499e5d9180e11f24](https://github.com/magento/magento2/commit/80fbc9ed8672d5257213e6d7499e5d9180e11f24)
 - [13595a3514f7353baed467e24369519e810f88ee](https://github.com/magento/magento2/commit/13595a3514f7353baed467e24369519e810f88ee)
 - [8c838817d6f74c9ede284e14c0f97899d0d9eccc](https://github.com/magento/magento2/commit/8c838817d6f74c9ede284e14c0f97899d0d9eccc)
 - [92c1b10be0b8638b8f1a5165edb005894b8148e7](https://github.com/magento/magento2/commit/92c1b10be0b8638b8f1a5165edb005894b8148e7)
 - [eadb6b7dbd4d4fa70a831d5facbf9f1da1e03e68](https://github.com/magento/magento2/commit/eadb6b7dbd4d4fa70a831d5facbf9f1da1e03e68)

The fix will be available with the upcoming 2.3.0 release.
