### ISSUE TITLE
All Grid Back Links are appearing as "Back to register or connect an account" in 2.2.4

### ISSUE THREAD

**Issue by kmyprojects** [magento/magento2#14978]
### Preconditions

1. Magento 2.2.4
2. PHP 7.0.29, mysql 14.14

### Steps to reproduce

1. Login to admin
2. Go to Catalog -> Products and select any product to edit.
3. or Go to Sales -> Orders and go inside any order.

### Expected result

1.  Just **Back** instead of Back to register or connect an account

### Actual result

1. ![screen-shot-2018-05-03-at-22 32 35](https://user-images.githubusercontent.com/2907889/39604032-6ff5fc60-4f22-11e8-85e6-b52bdab569f2.png)

**Comment by gelanivishal** [comment]
### Issue:
I have checked and found that there is an issue in amazon payment library. This issue is fixed but that branch is not merged with master branch.

> Amazon pay login library: https://github.com/amzn/amazon-payments-magento-2-plugin
> Translation issue is fixed in **pre_2.0.0_2018-02-21** branch: https://github.com/amzn/amazon-payments-magento-2-plugin/tree/pre_2.0.0_2018-02-21
> - Translation file en_GB: https://raw.githubusercontent.com/amzn/amazon-payments-magento-2-plugin/pre_2.0.0_2018-02-21/src/Core/i18n/en_GB.csv
> - Translation file en_US: https://raw.githubusercontent.com/amzn/amazon-payments-magento-2-plugin/pre_2.0.0_2018-02-21/src/Core/i18n/en_US.csv

This issue will be fixed after amazon will merge -> remove this line.
Translation issue is fixed in **pre_2.0.0_2018-02-21** branch but not merged in master branch yet

### Solution:
I have checked and found that there is an issue If we change `"Back","Back to register or connect an account"` to `"Back","Back"` in below file then it will work
- vendor/amzn/amazon-pay-and-login-magento-2-module/src/Core/i18n/en_GB.csv:79
- vendor/amzn/amazon-pay-and-login-magento-2-module/src/Core/i18n/en_US.csv:79

**Comment by bap14** [comment]
See my comment on #15024 about a more proper solution: https://github.com/magento/magento2/issues/15024#issuecomment-387160063

**Comment by erikhansen** [comment]
Closing this as a duplicate of #15024
