### ISSUE TITLE
Improper Handling of Pagination SEO

### ISSUE THREAD

**Issue by winterk80** [magento/magento2#14971]
### Preconditions
Magento 2.1.x or 2.2.x

### Steps to reproduce
Go to a category with 3 or more pages
Goto page 2
When you click back to page 1 OR click previous button it appends ?p=1 to the url

### Expected result
?p=1 should not be appended to the url. This creates a duplicate page. Even though the url is canonical this degrades SEO page authority because you have created a duplicate page in Google and Bing's eyes by appending the ?p=1 to the url Should be the original page url without ?p=1 appended
https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html
https://support.google.com/webmasters/answer/1663744?hl=en
https://moz.com/blog/seo-guide-to-google-webmaster-recommendations-for-pagination

### Actual result
Magento appends a ?p=1 to the page one url and the previous button, creating a duplicate content problem. 
This also creates a problem with rel="next" rel="prev" when you try to implement because magento is creating the duplicate page with ?p=1 for page one.

**Comment by yumicom** [comment]
I also need to correct this issue

**Comment by ghost** [comment]
@winterk80, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by winterk80** [comment]
Hello,
It's been 4 months, when will there be a solution?

**Comment by benathomeofchampions** [comment]
#mmuk2019 Assign to me

**Comment by magento-engcom-team** [comment]
@benathomeofchampions thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Nekoozu** [comment]
#mm19pl

**Comment by magento-engcom-team** [comment]
@Nekoozu thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by VladimirZaets** [comment]
Hi @winterk80. Thank you for your report. 
The issue has been fixed in magento/magento2#25337 by @chickenland in 2.4-develop branch
Related commit(s):
 - [c57d98c67343794530cd9e9d7405c095bc31fad8](https://github.com/magento/magento2/commit/c57d98c67343794530cd9e9d7405c095bc31fad8)
 - [3f4642ed3529467baafad828dd415749f0395176](https://github.com/magento/magento2/commit/3f4642ed3529467baafad828dd415749f0395176)
 - [2860283bd1797bab573925501964712e0c177ed8](https://github.com/magento/magento2/commit/2860283bd1797bab573925501964712e0c177ed8)
 - [94e86852f725424a6c8f61cb76ff591b8061a631](https://github.com/magento/magento2/commit/94e86852f725424a6c8f61cb76ff591b8061a631)
 - [9c4991a5828b34c98e753ecc62dda592a6ff54fc](https://github.com/magento/magento2/commit/9c4991a5828b34c98e753ecc62dda592a6ff54fc)

The fix will be available with the upcoming 2.4.0 release.
