### ISSUE TITLE
Braintree - for partial capturing  the second transaction has no parent id set

### ISSUE THREAD

**Issue by fmitu** [magento/magento2#14984]
### Preconditions
1. use Magento 2.2.3 or 2.2.4 (It's reproducing in both versions)

### Steps to reproduce
1. Configure Braintree sandbox with different merchant ID and different currencies. E.g:  merchant_USA where you set the $ currency, merchant_UK where you set the £ currency, merchant_FR where you set the € currency. Set merchant_UK as default.
2.  Configure multiple stores in Magento. E.g: Store USA where you set the $ currency, Store UK where you set the £ currency, Store FR where you set the € currency
3. Configure Braintree built-in payment method, **set Payment Action to "Authorize"**. For each store set the merchant_id. E.g: for USA store set merchant_USA, for UK store set merchant_UK, for FR store set merchant_FR
4.  Place an order with 2 products on USA store.
5.  Use partial capturing: Create the invoice with "Capture online" action **for first product**. In this moment you will have a transaction with Parent Transaction Id set in Magento and you will see the transaction in Braintree as Submitted For Settlement.
6. Use partial capturing: Create the invoice with "Capture online" action **for second product**.  In this moment you will have a transaction **without** Parent Transaction Id set in Magento and you will see the transaction in Braintree as Submitted For Settlement **with wrong currency.**

### Expected result
1. The both transactions should have set same Parent Transaction Id, and in Braintree you should see the both transactions with same currency (as it is in Magento).

### Actual result

1. The second transaction has no Parent Transaction Id set and the second transaction in Braintree has the default currency (in this case £), instead of $.

**Comment by YevSent** [comment]
Hi, @fmitu, at first few clarifications.
1. Braintree payment configuration (as most payment configurations) website dependable, you can configure it only per website, not per store.
2. Braintree uses `Base Currency` to perform transactions, not the `Default Display Currency`.
> Base currency is used for all online payment transactions. The base currency scope is defined by the catalog price scope ("Catalog" > "Price" > "Catalog Price Scope").

3. By default, the currency scope is `Global`. Even if you have multiple stores the `Base Currency` will be the same for all websites and stores. To change the scope - `Stores` -> `Configuration` -> `Catalog` -> `Price` -> `Catalog Price Scope`.
4. Braintree Gateway doesn't provide partial capture out of the box, this feature based on Vault implementation. There is no parent id for the second transaction because it's a completely new `sale` transaction (authorization + capture), you can check it in your Braintree account. That's why empty parent id for the transaction is expected behavior.
5. During the capture operation, Magento doesn't send the currency to Braintree.

Please, check your configuration and attach `payment.log` debug file with related requests.

**Comment by fmitu** [comment]
Hi 

Thank you for investigating.

1. Yes sorry, it's a website configuration
3. I've already set Stores -> Configuration -> Catalog -> Price -> Catalog Price Scope -> Website
4. I just don't understand "_this feature based on Vault implementation_". What does this mean exactly? Are there some configurations in Braintree sandbox - Vault that need to be done? Or there are some implementation in Magento (into module-braintree/Gateway ) that needs to be developed in order to be able to use the partial capturing?

**Comment by YevSent** [comment]
Hi, @fmitu.
3. Braintree SDK doesn't provide a possibility to perform partial capture operations. But we implemented partial capture (you don't need to implement any additional customizations, it already works in Magento) via Magento Vault module. Braintree integration uses Magento Vault and Braintree Vault - https://developers.braintreepayments.com/guides/payment-methods/php, https://articles.braintreepayments.com/control-panel/vault/overview.

Again, the current Braintree integration supports partial capturing and doesn't require additional configuration.

**Comment by fmitu** [comment]
Hi,

Thank you again.
It's clear now.

**Comment by magento-engcom-team** [comment]
Hi @fmitu 
Closing this ticket now, looks like issue is solved.
