### ISSUE TITLE
can not update index in index management

### ISSUE THREAD

**Issue by zhaoxiong123** [magento/magento2#1498]
can not update index in index management

i not found the action button or view

**Comment by vpelipenko** [comment]
@zhaoxiong123, after reworking indexer infrastructure in Magento this action is not available from admin, because it is not needed, but there is ability to do reindex using Magento CLI:

`
Usage:  bin/magento indexer:<option>
`

**Comment by vpelipenko** [comment]
More information you can find here: http://devdocs.magento.com/guides/v1.0/architecture/index-cache/indexing.html

**Comment by xcomSteveJohnson** [comment]
See also: http://devdocs.magento.com/guides/v1.0/config-guide/cli/config-cli-subcommands-index.html

**Comment by orlangur** [comment]
Maybe message should be added in Index Management UI pointing out that things have been changed since Magento 1? It's not the first bug report regarding this.

**Comment by vpelipenko** [comment]
@orlangur, good point. Need to ask PO.

**Comment by tapansoda** [comment]
I just downloaded Magento 2 and looking at a way to reindex. I found that there is no UI solution to re-index. It would help user's by notifying them that unlike magento 1.x, magento 2 does not support UI to reindex. Also I do not understand why re-indexing has been removed from UI and only console is the option. Any advantages ? Web site owners are not techie to play around with console to reindex website, they will always have to rely on someone. 

I am not sure if I am completely right, kindly provide your feedback.

**Comment by xcomSteveJohnson** [comment]
http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-index.html

**Comment by tapansoda** [comment]
Hey Steve, I am quite aware about this link and have gone through it. Non techie will face problems as they do not have a web interface to re-index. I am not sure if you have understood my concern of point.

**Comment by sumanparihar** [comment]
bin/magento indexer:reindex catalogsearch_fulltext is not working. It's display "segment fault" error. After status change from "reindex-require" to "Processing". it's not completed. How to reindex again and where index related file Store

Thanks
Suman

**Comment by maksymcherevko** [comment]
I have the same problem as @sumanparihar, with Custome Grid and Catalog Search. Tried to change the status in the database (table: mr_indexer_state), then activate this process again. Process start, but the result is the same.

![screenshot_40](https://cloud.githubusercontent.com/assets/16465396/12481880/d6471a8a-c054-11e5-938b-e0a4d46e1c58.png)

**Comment by kevando** [comment]
I am here looking for a clear answer on why reindex is not an option from the admin? 

The links provided have lots of great information, but it's not clear whether or not we should have the reindex action available in the admin ui.

**Comment by ClaudiuCreanga** [comment]
I can't believe the index option was removed from admin.

1) Store owners are very often non technical people who never saw a command line in their lives so they will not be able to reindex. 
2) Is the new system infallible and never a manual reindex is required? I doubt it! What I imagine would happen is us getting a couple of tickets every week just to reindex for them.
3) This basically makes it impossible to have a mangeto store on a shared hosting. You don't get ssh access on most of shared hosting packages so many would run composer commands locally and then move files via ftp. But what about reindexing?

"because it is not needed, but there is ability to do reindex using Magento CLI"
either it is not needed and you should remove it entirely and from cli or it is needed and then it should be in both places. If it is not needed why is it in cli?

**Comment by kandy** [comment]
On production site should not be cases when indexer must be run manually, but I believe that possibility of manually mark index as invalid should be present in UI.

**Comment by kevando** [comment]
Yeah I mean I'm happy to fork the repo and develop this for magento2 but I just cant imagine it's not there by design.

**Comment by kandy** [comment]
How the administrator can know that he needs to invalidate the cache?
