### ISSUE TITLE
Uncaught TypeError: url.replace is not a function in checkout

### ISSUE THREAD

**Issue by iuwqyir** [magento/magento2#14992]
### Preconditions
1. Any Magento 2 version. I tested on versions 2.1.12 and 2.2.3

### Steps to reproduce
1. Create a form on checkout page that has a field with the name 'action' and submit it.
(Can be executed from the console)

### Expected result
1. Form is submitted

### Actual result
1. I get the following error

![error](https://user-images.githubusercontent.com/16590638/39623799-79c4e490-4f9f-11e8-9062-6c5b5afbe1fa.PNG)

2. Form is not submitted

### Possible solution
The reason is in the javascript code, located
1) For Magento 2.1 versions: [here](https://github.com/magento/magento2/blob/2.1/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L365)
2) For Magento 2.2 versions [here](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L397) and [here](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/view/frontend/web/js/storage-manager.js#L23).

The reason is because of the code `event.target.action` which returns the form field with the name 'action' instead of the value of attribute 'action'.

The correct way to ask for the element's 'action' attribute would be 
`event.target.getAttribute('action')` 
or using jquery
`$(event.target).attr('action')`

**Comment by engcom-backlog-nickolas** [comment]
Hello @iuwqyir, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Usuario001** [comment]
#mm18mx

**Comment by magento-engcom-team** [comment]
@Usuario001 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Usuario001** [comment]
@magento-engcom-team give me 2.1.12  instance

**Comment by magento-engcom-team** [comment]
Hi @Usuario001. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by Usuario001** [comment]
@magento-engcom-team give me 2.1.12  instance

**Comment by magento-engcom-team** [comment]
Hi @Usuario001. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by Usuario001** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Usuario001. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usuario001, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14992-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14992-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14992-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @Usuario001. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Usuario001** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usuario001. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usuario001, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14992-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14992-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14992-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by eduard13** [comment]
Hi @iuwqyir , could you provide the way how you add the form to checkout page? I wasn't able to reproduce after adding a new form on shipping step.
![xnip2019-02-20_12-50-03](https://user-images.githubusercontent.com/15868188/53086615-1c2c7280-350e-11e9-8fc8-86a98a7f0b0f.jpg)
So could you please provide more details regarding this issue?
Feel free to reopen the issue once you have some additional info.

Thank you.

**Comment by iuwqyir** [comment]
@eduard13 If you just append a form to the checkout page using `$('body').append()` and then try to submit. 
This was part of a custom online payment method. When the customer clicks 'Place Order' then the form with payment data is generated and submitted to the 3rd party payment gateway.
Here's a small example that you can enter into the console on the checkout page:
```
var form = "
    <form name='test_form' id='test-data-form'  action='/' method='post'>
        <input type='text' name='action' value='test' hidden />
        <input type='submit' value='Submit' hidden />
    </form>";

jQuery('body').append(form);
jQuery('#test-data-form').submit();
```
