### ISSUE TITLE
magento2\lib\internal\Magento\Framework\Webapi\Rest\Request.php line:144

### ISSUE THREAD

**Issue by zhaoxiong123** [magento/magento2#1501]
match problem 

![image](https://cloud.githubusercontent.com/assets/3273395/8719382/f0c6378a-2bdd-11e5-827c-df847f335335.png)

**Comment by zhaoxiong123** [comment]
can not match the charset!

**Comment by vpelipenko** [comment]
@zhaoxiong123, could you give us more details? How did you get a problem?

**Comment by zhaoxiong123** [comment]
I use curl to access the webapi , when i get access token , the return info is 'UTF-8 is the only supported charset'  

but my header is  "Content-Type:application/json; charset=utf-8 ;"

in the file lib\internal\Magento\Framework\Webapi\Rest\Request.php line:144

the $matches[2] is  "utf-8; boundary=------------------------ac2921cd80a6eb03"

so the Regular Expressions have a problem

**Comment by magento-engcom-team** [comment]
Hi @zhaoxiong123. Thank you for your report. 
The issue has been fixed in magento/magento2#28932 by @gabrieldagama in 2.4-develop branch
Related commit(s):
 - [be428f7a4255de6b8ba5ae4668bf27be8ca0a38b](https://github.com/magento/magento2/commit/be428f7a4255de6b8ba5ae4668bf27be8ca0a38b)
 - [984dab1cf1c475ed2b60d12e98358fc69ede9dc0](https://github.com/magento/magento2/commit/984dab1cf1c475ed2b60d12e98358fc69ede9dc0)
 - [5531f50ff1ba3ad3812ddef4c886c8bae6b5b8cd](https://github.com/magento/magento2/commit/5531f50ff1ba3ad3812ddef4c886c8bae6b5b8cd)
 - [1574740ad1c71f1b74212bfd1449881212f25fc3](https://github.com/magento/magento2/commit/1574740ad1c71f1b74212bfd1449881212f25fc3)
 - [607aed6ff371c7aba0e78f41974196458b112937](https://github.com/magento/magento2/commit/607aed6ff371c7aba0e78f41974196458b112937)
 - [22c2be9dbccfea3fbc4ebae5a0f47626f7d41f6c](https://github.com/magento/magento2/commit/22c2be9dbccfea3fbc4ebae5a0f47626f7d41f6c)
 - [58158aafc3614d5d918fcd3382b35702eaeefaa3](https://github.com/magento/magento2/commit/58158aafc3614d5d918fcd3382b35702eaeefaa3)
 - [1467c6ef93b6dab35210429090657d840a8ed4bf](https://github.com/magento/magento2/commit/1467c6ef93b6dab35210429090657d840a8ed4bf)
 - [273607c41173302aadfea916569e404c1abe73ba](https://github.com/magento/magento2/commit/273607c41173302aadfea916569e404c1abe73ba)
 - [8660c73416c732b9772eb0b4aedb293ab088015d](https://github.com/magento/magento2/commit/8660c73416c732b9772eb0b4aedb293ab088015d)
 - [a8c3f67a063244dacd8f289bfb7295c6149294d7](https://github.com/magento/magento2/commit/a8c3f67a063244dacd8f289bfb7295c6149294d7)
 - [96e67524c5637c2a634b80375948fb42b26d1a87](https://github.com/magento/magento2/commit/96e67524c5637c2a634b80375948fb42b26d1a87)
 - [c77d81209df9023ba925157728e7edb133e44c81](https://github.com/magento/magento2/commit/c77d81209df9023ba925157728e7edb133e44c81)
 - [03b3ef5183f2e383b070004400ab9790d3c0eb04](https://github.com/magento/magento2/commit/03b3ef5183f2e383b070004400ab9790d3c0eb04)
 - [b4b16fff64ee2bdc4d57b1e9b9ac9f6d738d7698](https://github.com/magento/magento2/commit/b4b16fff64ee2bdc4d57b1e9b9ac9f6d738d7698)
 - [8af0f46e1404a30f155b37ab19ba045048532f42](https://github.com/magento/magento2/commit/8af0f46e1404a30f155b37ab19ba045048532f42)

The fix will be available with the upcoming 2.4.1 release.
