### ISSUE TITLE
Export will redirect to dashboard instead of download file on first time

### ISSUE THREAD

**Issue by hongc-cc** [magento/magento2#15030]
### Preconditions
1. Magneto v2.1.7

### Steps to reproduce
1. Create an account with Backend access but not full admin permission
2. Go to sales > orders > export

### Expected result
1. Browser downloaded the exported file 

### Actual result
1. Redirected to dashboard with no files download

### Remarks
1. This can be reference to the previously closed issue #14122 
2. I can provide our staging site for you to demonstrate the case.

**Comment by bijennaorem11** [comment]
For solving this issue you need to give the permission for Notifications to the particulars role.

**Comment by engcom-backlog-nickolas** [comment]
Hello @chanwhab, thank you for your report. I cannot reproduce this issue. Could you please provide more  detailed steps to reproduce?

**Comment by jqjk** [comment]
I am facing this issue in the same way.
As pointed out by @bijennaorem11, this issue will happen for users who do not have notification permission.
I think this is a bug.

**Comment by engcom-backlog-nickolas** [comment]
Hello @chanwhab, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-15030-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-15030-2-3-0.instances.magento-community.engineering/admin](https://i-15030-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@chanwhab permissions on notification do not cause the problem anymore. Thank you for reporting this issue.
