### ISSUE TITLE
Product Details Page breadcrumbs cause syntax error on products containing quotes

### ISSUE THREAD

**Issue by brian-labelle** [magento/magento2#15037]
### Preconditions

1. Magento version: 2.2.4

### Steps to reproduce

1. Add a product with `"` in the title, e.g. `My Product - 19" x 16" Header`
2. Navigate to Product Details Page
3. Observe the Syntax Error in the browser console

### Expected result

1. Template file should escape `"` in product name

### Actual result

1. Syntax Error occurs in console upon JSON Parse `SyntaxError: Unexpected token x in JSON`

**Comment by brian-labelle** [comment]
[Magento_Catalog `view/frontend/templates/product/breadcrumbs.phtml`:](https://github.com/magento/magento2/blob/ffac6ee07e49a71fe965804476e64a78d93d7b29/app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml)

```
<div class="breadcrumbs" data-mage-init='{
    "breadcrumbs": {
        "categoryUrlSuffix": "<?= $block->escapeHtml($viewModel->getCategoryUrlSuffix()); ?>",
        "useCategoryPathInUrl": <?= (int)$viewModel->isCategoryUsedInProductUrl(); ?>,
        "product": "<?= $block->escapeHtml($viewModel->getProductName()); ?>"
    }
}'>
</div>
```
To fix the issue, the product name value must go through `$block->escapeJs() `

**Comment by kanduvisla** [comment]
I have the same issue here (also 2.2.4). I'll quick fix it for now (thanks @brian-labelle), but this definitely needs to be fixed.

**Comment by Bobstar040** [comment]
We have the same issue, is there any fix for this already?

**Comment by kanduvisla** [comment]
@Bobstar040 : my best guess would be to implement the fix as described by @brian-labelle at the moment. I hope that this will be fixed in M2.2.5+ / M2.3, but probably @magento-engcom-team could shed more light on this.

**Comment by POLYPERFORMANCE** [comment]
Same issue here too with hundreds of products that contain quotes. I'll implement @brian-labelle 's fix. 
Nice detailed fix: https://magento.stackexchange.com/q/224587/52084

**Comment by chiragp-wagento** [comment]
@magento-engcom-team unable to re-produce the issue in 2.2-develop branch, magento version 2.2.6-dev.
![breadcrumb](https://user-images.githubusercontent.com/19569330/40265823-573e9b54-5b5d-11e8-99f6-62311a778a47.png) #dmcdindia

**Comment by jignesh-baldha** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
Hi @brian-labelle. Thank you for your report. 
The issue has been fixed in magento/magento2#15347 by @jignesh-baldha in 2.2-develop branch
Related commit(s):
 - [6fcfb88a1077602d632c2e8e4037f8cdd147a86b](https://github.com/magento/magento2/commit/6fcfb88a1077602d632c2e8e4037f8cdd147a86b)
 - [bfb39b5bfe24ca0b00de0bf0348db4fb3b5ef3d2](https://github.com/magento/magento2/commit/bfb39b5bfe24ca0b00de0bf0348db4fb3b5ef3d2)
 - [8e93b0da2930502e46b933cc57cd6eb98aba7f8a](https://github.com/magento/magento2/commit/8e93b0da2930502e46b933cc57cd6eb98aba7f8a)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @brian-labelle. Thank you for your report. 
The issue has been fixed in magento/magento2#16148 by @jignesh-baldha in 2.3-develop branch
Related commit(s):
 - [e9fa7b69611152dae7e4c13838ba9701178c5602](https://github.com/magento/magento2/commit/e9fa7b69611152dae7e4c13838ba9701178c5602)
 - [388b58700be8b4ff3f9c2457f0766cae57ced289](https://github.com/magento/magento2/commit/388b58700be8b4ff3f9c2457f0766cae57ced289)

The fix will be available with the upcoming 2.3.0 release.

**Comment by dyron** [comment]
Again not in Magento 2.2.5:
https://github.com/magento/magento2/blob/2.2.5/app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml#L14

**Comment by benhtn** [comment]
Since @magento-engcom-team  have not implemented this in 2.5.5...  For anyone else who needs it, to implement the fix described by @brian-labelle in a theme.
`cp app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml app/design/frontend/<vendor>/<theme>/Magento_Catalog/templates/product/`
then edit 
`        "product": "<?= $block->escapeHtml($viewModel->getProductName()); ?>"`
to
`        "product": "<?= $block->escapeJs($viewModel->getProductName()); ?>"`
then clear your cache.

**Comment by Quent6457** [comment]
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="breadcrumbs" data-mage-init='{
    "breadcrumbs": {
        "categoryUrlSuffix": "<?= $block->escapeHtml($viewModel->getCategoryUrlSuffix()); ?>",
        "useCategoryPathInUrl": <?= (int)$viewModel->isCategoryUsedInProductUrl(); ?>,
        "product": "<?= htmlspecialchars($block->escapeHtml($viewModel->getProductName())); ?>"
    }
}'>
</div>

**Comment by Quent6457** [comment]
`<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="breadcrumbs" data-mage-init='{
    "breadcrumbs": {
        "categoryUrlSuffix": "<?= $block->escapeHtml($viewModel->getCategoryUrlSuffix()); ?>",
        "useCategoryPathInUrl": <?= (int)$viewModel->isCategoryUsedInProductUrl(); ?>,
        "product": "<?= htmlspecialchars($block->escapeHtml($viewModel->getProductName())); ?>"
    }
}'>
</div>`

**Comment by Quent6457** [comment]
[https://magento.stackexchange.com/questions/224587/issue-with-magento-2-2-4-quotation-mark-in-product-name-break-product-pages](url)

**Comment by divyabhagat** [comment]
You have to overwrite the file  app/design/frontend/Vendor/Theme/Magento_Catalog/templates/product/breadcrumbs.phtml and replace the code by this

**Comment by divyabhagat** [comment]
$viewModel = $block->getData('viewModel');
?>
<div class="breadcrumbs" data-mage-init='{
    "breadcrumbs": {
        "categoryUrlSuffix": "<?= $block->escapeHtml($viewModel->getCategoryUrlSuffix()); ?>",
        "useCategoryPathInUrl": <?= (int)$viewModel->isCategoryUsedInProductUrl(); ?>,
        "product": "<?= $block->escapeHtml($block->escapeJsQuote($viewModel->getProductName(), '"')); ?>"
    }
}'>
</div>

**Comment by divyabhagat** [comment]
You have to overwrite the file  app/design/frontend/Vendor/Theme/Magento_Catalog/templates/product/breadcrumbs.phtml
then edit
"product": "<?= $block->escapeHtml($viewModel->getProductName()); ?>"
to
"product":  "product": "<?= $block->escapeHtml($block->escapeJsQuote($viewModel->getProductName(), '"')); ?>"
then clear your cache.
