### ISSUE TITLE
Add NOINDEX, FOLLOW to 404 CMS page using XML

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#15068]
On Magento ver. 2.2.3  404 CMS pages have the robots META tag `INDEX,FOLLOW`.

Is it possible to change the robots META tag using XML in the 'Layout Update XML' field? 

@cmdepi

**Comment by orbitrod** [comment]
I posted a question on StackExchange with no answer so far https://magento.stackexchange.com/questions/224676/magento-2-add-noindex-follow-to-404-cms-page-using-xml

**Comment by cmdepi** [comment]
Hi Roderick! How are you? You can modify this value to your theme on Admin -> Design -> Configuration -> _(Select scope: Website, Store or Store View)_ -> Search Engine Robots -> Default Robots

**Comment by orbitrod** [comment]
@cmdepi This is a global setting across all pages on the site.  I just want to update 404 pages with `NOINDEX, FOLLOW`.

**Comment by cmdepi** [comment]
Hi Roderick! How are you? I apologize because I had to go to a meeting and I could not read your post. I read your post so I understand your problem now. I am outside and I can not test the solution, but I think this magento fix could solve your problem to add the respective robot meta tag to your CMS 404 Page: https://github.com/magento/magento2/issues/4454

**Comment by orbitrod** [comment]
Thanks @cmdepi, https://github.com/magento/magento2/issues/4454 Fixed the problem
