### ISSUE TITLE
.lib-layout-width mixin not available?

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15060]
It seems `.lib-layout-width()` can not be used (anymore) but I still see some definitions of it in core themes.

Is it safe to remove it from the core code?

### Preconditions

1. Magento CE 2.2.4

### Steps to reproduce

1. try to use .lib-layout-width() in a less file

### Expected result

1. mixin should work

### Actual result

1. mixin does not exist / work

**Comment by engcom-backlog-nickolas** [comment]
Hello @DanielRuf, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by hitesh-wagento** [comment]
Hi @DanielRuf,

Where have you find `.lib-layout-width()`. Can you please more explain.

Thanks.

**Comment by DanielRuf** [comment]
> I still see some definitions of it in core themes.

Bare/Luma

**Comment by hitesh-wagento** [comment]
Hi @DanielRuf 

I can see `.lib-layout-width()` in only one file like below code.
`lib/web/css/source/lib/_layout.less`

//  Page Width mixin
.lib-layout-width(
    @_layout__min-width: @layout__min-width,
    @_layout__max-width: @layout__max-width,
    @_layout__indent: @layout-indent__width
) when not (@responsive = true) {
    ._lib-layout-width(@_layout__min-width, @_layout__max-width);
    .lib-css(padding-left, @layout-indent__width);
    .lib-css(padding-right, @layout-indent__width);
    margin: 0 auto;
}

What changes do you want ? can you please explain me in briefly.

**Comment by DanielRuf** [comment]
> Is it safe to remove it from the core code?

**Comment by hitesh-wagento** [comment]
I think we can't remove this code because it's used in backend css `app/design/adminhtml/Magento/backend/web/mui/styles/_vars.less`

`@layout__min-width: 960px;`

**Comment by DanielRuf** [comment]
> @layout__min-width: 960px;

This is just a variable. The mixin itself is not used anywhere. Please recheck. A variable does not call a mixin.

**Comment by hitesh-wagento** [comment]
> @layout__min-width: 960px;

This variable called in lib/web/css/source/lib/_layout.less

    .lib-layout-width(
    @_layout__min-width: @layout__min-width,
    @_layout__max-width: @layout__max-width,
    @_layout__indent: @layout-indent__width
    )

**Comment by DanielRuf** [comment]
That doesn't matter. It is about the removal / cleanup of the mixin `.lib-layout-width()`.

**Comment by hitesh-wagento** [comment]
So do you want I will remove `@layout__min-width: 960px;` from `app/design/adminhtml/Magento/backend/web/mui/styles/_vars.less` and from `lib/web/css/source/lib/_layout.less` below code ?

    .lib-layout-width(
    @_layout__min-width: @layout__min-width,
    @_layout__max-width: @layout__max-width,
    @_layout__indent: @layout-indent__width
    )

**Comment by magento-engcom-team** [comment]
Hi @Mayur1510. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by xandithurow** [comment]
@magento I am working on it

**Comment by thurow** [comment]
following what @sidolov commented on my pull request, i'm closing this issue because:
"I have reviewed PR once again and I'm not sure that we can safely remove mixins from the lib. Someone in his own theme implementation was able to use removed mixins and the theme will be broken after such changes. Probably we should leave such styles even they are not used in Magento itself. Also, we have a section in our Backward Compatible Development Guide connected to the css/less files."
