### ISSUE TITLE
Captcha not working on page load [2.2.4]

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#15062]
### Preconditions
1. Magento 2.2.4 upgrade from 2.2.3
2. PHP 7.0.28
3. Blank theme

### Steps to reproduce
1. Enable captcha for all forms

### Expected result
1. Go to "Forgot your password" for example (its not working for any forms).
2. Enter your email and captcha
3. Submit

### Actual result
1. After form submission you will get Incorrect CAPTCHA

![screenshot_27](https://user-images.githubusercontent.com/4161312/39757889-7eb3368c-52ce-11e8-9312-77c46d4dfeae.png)

But, if you reload the captcha code (not page), and try again, its working.

Instance is clear of any 3rd party modules that might affect captcha functionality.

**Comment by kerlama** [comment]
Can anyone else reproduce this ?

**Comment by BenGlassAtlas** [comment]
Yes I can replicate on 2.2.1, once you click on reload captcha it works.

**Comment by Sil-B** [comment]
Same issue on 2.2.4.

**Comment by kerlama** [comment]
I can confirm that this is not working on 2.2.5 too.

**Comment by BenGlassAtlas** [comment]
Any update on this please @magento-engcom-team?

**Comment by ghost** [comment]
HI @kerlama  thank you for you report. the fix for this issue has already been in 2.3-develop branch

**Comment by hostep** [comment]
@engcom-backlog-nazar: if you post a message like that, it would also be very much appreciated if you could specify the commit where it was fixed, so people can try to backport it to 2.2, just saying :)

**Comment by BenGlassAtlas** [comment]
Agreed, I'm unable to find this fix.

**Comment by ghost** [comment]
@hostep try reproduce this on 2.3-develop branch, i cannot reproduce, but where the fix for this issue or commit, i can't find

**Comment by BenGlassAtlas** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48, here is your [Magento instance](https://i-15062-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-15062-2-3-develop.engcom.dev.magento.com/admin](https://i-15062-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment]
The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
