### ISSUE TITLE
StockRegistryInterface :: getLowStockItems() returns StockStatusCollection instead of StockItemCollection

### ISSUE THREAD

**Issue by jesse-dev** [magento/magento2#15085]
### Preconditions
1. Magento 2.2.4
2. This is a typo/mistake in the API, so the environment doesn't matter

### Steps to reproduce
1. call REST API : /V1/stockItems/lowStock/
2. observe the response is  \Magento\CatalogInventory\Api\Data\StockStatusCollectionInterface

### Expected result
1. return \Magento\CatalogInventory\Api\Data\StockItemCollectionInterface
2. The implementation in Magento\CatalogInventory\Model\StockRegistry :: getLowStockItems() returns \Magento\CatalogInventory\Api\Data\StockItemCollectionInterface , so this is clearly a typo/mistake.

### Actual result
1. returns \Magento\CatalogInventory\Api\Data\StockStatusCollectionInterface
2. The implementation in Magento\CatalogInventory\Model\StockRegistry :: getLowStockItems() returns \Magento\CatalogInventory\Api\Data\StockItemCollectionInterface , so this is clearly a typo/mistake.

### The Fix
1. the return docblock for getLowStockItems() in \Magento\CatalogInventory\Api\StockRegistryInterface just needs to be updated to return \Magento\CatalogInventory\Api\Data\StockItemCollectionInterface instead of \Magento\CatalogInventory\Api\Data\StockStatusCollectionInterface

**Comment by engcom-backlog-nickolas** [comment]
Hello @jesse-dev, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @jesse-dev. Thank you for your report. 
The issue has been fixed in magento/magento2#17562 by @vasilii-b in 2.3-develop branch
Related commit(s):
 - [897e7df9441d121af626cace56cbc2a53e35c38d](https://github.com/magento/magento2/commit/897e7df9441d121af626cace56cbc2a53e35c38d)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @jesse-dev. Thank you for your report. 
The issue has been fixed in magento/magento2#18427 by @lewisvoncken in 2.2-develop branch
Related commit(s):
 - [adfb130b1bc7074daaeaed466f07a283e2eee8ca](https://github.com/magento/magento2/commit/adfb130b1bc7074daaeaed466f07a283e2eee8ca)

The fix will be available with the upcoming 2.2.8 release.
