### ISSUE TITLE
Web Setup Wizard Fatal Error

### ISSUE THREAD

**Issue by dschmidthawk** [magento/magento2#15116]
### Preconditions

1.  Running Magento 2.2.4 on Siteground Shared Linux hosting
2. Database server
  Server: Localhost via UNIX socket
  Server type: Percona Server
  Server version: 5.6.36-82.1-log - Percona Server (GPL), Release 82.1, Revision 1a00d79
  Protocol version: 10
  Server charset: UTF-8 Unicode (utf8)
3. Web server
  cpsrvd 11.66.0.23
  Database client version: libmysql - 5.1.73
  PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
  PHP version: 5.6.30

### Steps to reproduce

1.  Update site via cli from 2.2.3 to 2.2.4.  Front end is fine.
2. Login into backend
3. Click System>Web Setup Wizard
4. Displays error message on page

### Expected result

1. Web Setup Wizard should open

### Actual result

1. Error Message at https://theplasticmart.com/setup/:

Fatal error: Uncaught Exception: Warning: ini_set(): Cannot find save handler 'db' in /home/dshtest0/public_html/vendor/magento/framework/Session/SessionManager.php on line 570 in /home/dshtest0/public_html/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'ini_set(): Cann...', '/home/dshtest0/...', 570, Array) #1 /home/dshtest0/public_html/vendor/magento/framework/Session/SessionManager.php(570): ini_set('session.save_ha...', 'db') #2 /home/dshtest0/public_html/vendor/magento/framework/Session/SessionManager.php(184): Magento\Framework\Session\SessionManager->initIniOptions() #3 /home/dshtest0/public_html/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(37): Magento\Framework\Session\SessionManager->start() #4 /home/dshtest0/public_html/vendor/magento/framework/Session/SessionManager.php(130): Magento\Backend\Model\Auth\Session\Interceptor->start() #5 /home/dshtest0/public_html/vendor/magento/module-backend/Model/Auth/Sess in /home/dshtest0/public_html/vendor/magento/framework/App/ErrorHandler.php on line 61

I've done the following: reindexed, redeployed static content, made sure permissions are correct, flushed cache.

**Comment by ZartSkummer** [comment]
I am facing the exact same problem!

**Comment by inkobject** [comment]
Ditto.

Same exact behavior on Siteground Cloud.

Quick observations:

URL at failure was https://z9t.tech/223a/setup/index.php#/updater-success.
Front end and Back end appear to be working and admin reports Magento ver. 2.2.4

Still gonna go through and check everything I can think of, but I am not a Mag 2 dev. So I probably wont know if something really broke until I need it.

Update:

Rather than upgrade via CLI as above, I upgraded via Wizard. 
As above, in Admin, when I navigate to Stores->Tools-> Web Setup Wizard, I get the error as indicated in the post.
So my Web Setup Wizard is hosed.

**Comment by Paulsky** [comment]
I had the same error and problem. I changed the 'db' value to 'Files' in env.php, which is in my situation also a better choice (https://magento.stackexchange.com/questions/93495/what-should-i-choose-session-save-files-or-db-while-magento-install).

**Comment by inkobject** [comment]
Paulsky, thank you for your input. I followed your suggestion. To add to your fix, Magento dev docs also indicates that one may specify the sessions path: [https://devdocs.magento.com/guides/v2.0/config-guide/sessions.html](https://devdocs.magento.com/guides/v2.0/config-guide/sessions.html) . I did that since I dont know where the php.ini will save the sessions.

I made the changes in /app/etc/env.php and the Web Setup Wizard is back to normal and I can see the saved sessions where I specified. 

You're a rockstar, Paulsky!

**Comment by PieroBonforte** [comment]
Same situation.
I found this solution

http://phpcodez.com/configure-memcached-magento-2/

Hope this helps!
for me worked

**Comment by ritschi72** [comment]
If I try to open Web Setup Wizard via admin panel in Magento 2.2.4, it shows a blank page, without any error message or someting. Does somebody face that problem?

**Comment by inkobject** [comment]
I have not seen this. I have been unable to move to 2.2.4 because a possible extension conflict.

**Comment by ghost** [comment]
Hi @dschmidthawk I cannot reproduce you scenario steps, see attachments, we are closing this issue . If you'd like to update it, please reopen the issue.
![selection_042](https://user-images.githubusercontent.com/40756439/43315530-e9998852-919e-11e8-9683-9cbfd956b42a.png)

**Comment by GregorVoelkl** [comment]
Exactly the same issue to me after upgrading to 2.2.4 via command line.

**Comment by mischabraam** [comment]
Magento 2.2.6 with command `bin/magento setup:upgrade` gives the same error. Please fix.
