### ISSUE TITLE
Magento 2.2.4 - Condition Category Chooser Crashes Page if Store has Several Nested Categories

### ISSUE THREAD

**Issue by rjtulloh** [magento/magento2#15121]
### Preconditions
1. Magento CE 2.2.4 PHP 7.1.17 and PHP 7.0.30
2. Create a set of categories such that a category with no subcategories is followed by two categories that do have one subcategory. Issue can also be observed in environment with sample data freshly deployed.

### Steps to reproduce
1. Create a new Cart Price Rule from Marketing -> Cart Price Rules.
2. Scroll to "Actions" section and open it.
3. Under "Apply the rule only to cart items matching the following conditions (leave blank for all items)." section, add a new condition
4. For the condition attribute, select "Category."
5. Click on the ellipses, then open the Category Chooser.

### Expected result
1. List of categories should appear to select from.

### Actual result
1. No categories appear and the page becomes unresponsive and eventually crashes.

**Comment by stkristobal** [comment]
I get the same. @rjtulloh are you also getting limits to attribute filters? Ours stops after 'Category':
[sceenshot](https://i.stack.imgur.com/L5hcZ.png)

**Comment by hostep** [comment]
@rjtulloh & @stkristobal: it looks like there is a new PR which fixes this issue: https://github.com/magento/magento2/pull/15265

**Comment by stkristobal** [comment]
@hostep worked for me - thanks for the heads up!

**Comment by jonshipman** [comment]
Just a note, with my build I needed to apply the fix to buildHashChildren in the next method.

Here is my alternative fix
https://github.com/magento/magento2/pull/15330/commits/6e57b657f2f05ad54927c116b941086f61c11a4e

**Comment by magento-engcom-team** [comment]
Hi @rjtulloh. Thank you for your report. 
The issue has been fixed in magento/magento2#15265 by @keithbentrup in 2.2-develop branch
Related commit(s):
 - [b7179ad97c0a406e41245d9d092a17df529a1768](https://github.com/magento/magento2/commit/b7179ad97c0a406e41245d9d092a17df529a1768)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @rjtulloh. Thank you for your report. 
The issue has been fixed in magento/magento2#17816 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [3c499dbb45fc86dcb25052f4bc01d78afe6b173d](https://github.com/magento/magento2/commit/3c499dbb45fc86dcb25052f4bc01d78afe6b173d)

The fix will be available with the upcoming 2.3.0 release.

**Comment by Vladekarpa** [comment]
Hi is this problem fixed for older version of magento, i have 2.1 and i have the same problem.
