### ISSUE TITLE
prioritize often upvoted open issues

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15141]
I guess we should link to them in the readme or otherwise and try to prioritize a few of them.

https://github.com/magento/magento2/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+

**Comment by hostep** [comment]
Magento already uses that and blogged about this some time ago: https://community.magento.com/t5/Magento-DevBlog/GitHub-Issue-Priority/ba-p/60088

But unfortunately a lot of people are unaware of this and should upvote more instead of replying with "happens to me too".

I also think this needs to be made more clear, adding this to the readme would probably help (a little bit).

**Comment by DanielRuf** [comment]
At least a link like the one that I posted could be helpful for new and current contributors to see which issues need some more attention.

Personally I did not know about this specific devblog entry.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf 
Thanks for the input. We are already working on it. 
We are closing this ticket now, as it is slightly out of scope for M2 github issue tracker.
