### ISSUE TITLE
Selecting "Create Shipment" from "Invoice" screen yields "Cannot create empty shipment" and locks up Order Status

### ISSUE THREAD

**Issue by grichards** [magento/magento2#15147]
### Preconditions
Magento CE 2.2.2
Authorize.net Direct Post - Authorize Only

### Steps to Reproduce

Order Comes In
View Order
Invoice Order
Check box "Create Shipment"
Leave drop-down at "Capture Online"
Click "Submit Invoice"

### Expected Result
Payment Captured
Invoice Created
Shipment Created
Order Status Updated to "Completed"

### Actual Result
Payment Captured
Invoice Not Created
Shipment Not Created
Error message received on Invoice page: "We cannot create an empty shipment".
Order Status remains: "Processing"

Further attempts to invoice / ship fail... because now attempts to save invoice with "Capture Online" result in "Transaction has already been captured."

Indeed, checking in Authorize.net shows the transactions was captured... so it seems if this is truly a validation error related to creating the shipment... that at least the Invoice should have been created and the Order Status should have been advanced.

**Comment by fromero98** [comment]
Upping this, as I'm getting a very similar error (my order does not lock up, but I can't create shipment and invoice at the same time).

**Comment by ghost** [comment]
Hi @grichards the fix for this issue has already been available in 2.3-develop branch

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @grichards The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by nthink** [comment]
We are still experiencing this issue in Magento 2.3.1, using the new Authorize.Net module with all the same Preconditions, Steps to Reproduce, Expected and Actual Results as above.

**Comment by navabrind** [comment]
This issues persists in Magento 2.3.2 as well..  Our client usign Quickpay.net payment gateway.. (Similar to authorize.net)
