### ISSUE TITLE
PayPal PayFlow Pro: "Comment 1" field set incorrectly

### ISSUE THREAD

**Issue by dccampbell** [magento/magento2#15163]
### Description

PayPal PayFlow provides the optional `COMMENT1` field for passing along any custom information desired to be saved with the transaction in PayPal ([documentation here](https://developer.paypal.com/docs/classic/payflow/integration-guide/?mark=comment1#core-credit-card-parameters)). 

Magento 2 attempts to use this field to store the order ID. However, the use of `setComment1()` to add this value to the request creates the key `comment_1` rather than `comment1`. As such, PayPal ignores it and so the field appears empty when viewing PayPal transactions.

### Preconditions
- Magento version >= 2.3.3*
- PayPal Payflow Pro payment method is enabled and working

*Confirmed in these versions, but also affects all previous M2 releases assuming that the parsing of setData magic method names wasn't changed at some point.

### Steps to reproduce
- Complete any order using PayPal Payflow Pro as the payment method.

### Expected result
- When viewing the transaction for the order in PayPal, the "Comment 1" field contains the order ID.

### Actual result
- The "Comment 1" field is missing/empty on the transaction.

### Proposed Resolution
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Paypal/Model/Payflowpro.php#L885

Change the `->setComment1($orderIncrementId);` line to `->setData('comment1', $orderIncrementId);`

That's assuming that a numeral being treated like a capital letter here when converting camelCase set method names to snake_case data keys is not itself a bigger issue. If not, I'm happy to submit a pull request for the above change if desired.

**Comment by engcom-backlog-nickolas** [comment]
Hello @dccampbell, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @adityayadav-cedcoss. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by realadityayadav** [comment]
#MM19IN

**Comment by sdzhepa** [comment]
Hello @dccampbell 

Thank you for contribution and collaboration!

As I can see from PR #20899 discussion
- https://github.com/magento/magento2/pull/20899#issuecomment-468653869 " looks like the issue was already fixed 0d7f677"
- and confirmation from the author  https://github.com/magento/magento2/pull/20899#issuecomment-468697187

So this issue can be closed
