### ISSUE TITLE
Custom less contained within media queries is not compiled

### ISSUE THREAD

**Issue by muckee** [magento/magento2#15206]
Developing a custom theme, I have created a file `new_products.phtml` which inherits styles from `new_products.less`, both stored within the `Magento_Theme` folder of my custom theme.
When writing styles in plain LESS or CSS, everything works fine, though this means, of course, that the default media queries will override any styles that I apply. However, when I attempt to include either the `.media-width` mixin, or use an `@media` query, the styles are not rendered.

### Preconditions
1. Magento 2.2.3
2. Ubuntu 16.04 Server VM using VirtualBox with icewm window manager
3. Apache 2.4
4. MySQL 14.14
5. PHP 7.0
6. Custom theme, inheriting from `Magento/blank`

### Steps to reproduce
<b>1. Create the file `vendor/theme/Magento_Theme/templates/html/new_products.phtml` as follows:</b>

```
<div class="new-products-banner-container">
    <div class="new-products-banner">
        <h1 class="new-products-banner-title">NEW RELEASES</h1>
    </div>
</div>
<?php echo $this->getLayout()
            ->createBlock("Magento\Catalog\Block\Product\Widget\NewWidget")
            ->setProductsCount("10")
            ->setTemplate("product/widget/new/content/new_grid.phtml")
            ->toHtml();
?>
```

<b>2. Create the file `vendor/theme/Magento_Theme/web/css/new_products.less` as follows:</b>

```
//
//  Common
//  _____________________________________________

& when (@media-common = true) {
    .new-products-banner-container {
        width: 100%;
        height: 53px;
        z-index: 1;
    }
    .new-products-banner {
        width: 100%;
        max-width: 1280px;
        height: 100%;
        margin: 0 auto;
    }
    .new-products-banner-title {
      margin-bottom: 0;
    }
    .block-title {
      display: none;
    }
    .block-new-products {
      margin-top: 10px;
    }
}

//
//  Mobile
//  _____________________________________________

.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
    .new-products-banner-container {
        width: 100%;
        height: 53px;
        z-index: 1;
    }
    .new-products-banner {
        width: 100%;
        max-width: 1280px;
        height: 100%;
        margin: 0 auto;
    }
    .new-products-banner-title {
      margin-bottom: 0;
      line-height: 2;
    }
    .block-title {
      display: none;
    }
    .block-new-products {
      margin-top: 10px;
    }
}

//
//  Desktop
//  _____________________________________________

.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {
    .new-products-banner-container {
        width: 100%;
        height: 53px;
        z-index: 1;
    }
    .new-products-banner {
        width: 100%;
        max-width: 1280px;
        height: 100%;
        margin: 0 auto;
    }
    .new-products-banner-title {
      margin-bottom: 0;
      line-height: 1.25;
    }
    .block-title {
      display: none;
    }
    .block-new-products {
      margin-top: 10px;
    }
}
```

3. Run `setup:upgrade` and `cache:flush`

### Expected result
1. Styles should render on the frontend.

### Actual result
1. The default styles, inherited from `Magento/blank` are rendered, excluding the custom styles from the CSS entirely.

###Note:

I am aware that styles needn't be repeated for mobile/desktop views when they are included in the common view, however even these measures do not ensure that the CSS is rendered.

This issue has been raised as a question on the Magento [Stack Exchange](https://magento.stackexchange.com/questions/225942/magento-2-2-how-to-apply-breakpoints-in-custom-less-files).

**Comment by muckee** [comment]
I will add that I have created a workaround, answered in the aforementioned [stack exchange question](https://magento.stackexchange.com/q/225942/60221). However, this is not proper usage of the magento framework and so I cannot close the issue, though maybe my answer will aid in troubleshooting this more quickly.

**Comment by muckee** [comment]
@engcom-backlog-nickolas As far as I can tell, this is still an issue for 2.2.5.

I need to do a bit of testing once I've got more time but, as far as I remember, everything works as expected when styles are written within a _module.less file, but the breakpoints fail wherever a custom file is included as per magento's documentation.

**Comment by engcom-backlog-nickolas** [comment]
Hello @JoshuaFlood, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magudelo62** [comment]
Hello @JoshuaFlood, 

The real problem is that "vendor/theme/Magento_Theme/web/css/new_products.less" file isn't load and compiled. The good way to import less files as Magento documentations recomend is: In `_extend.less` file #register the `_new_products.less` by adding the following code: `@import '_new_products.less';`

Look here the Magento documentation https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_approach.html#structured_extend

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @JoshuaFlood According to @magudelo62 comment https://github.com/magento/magento2/issues/15206#issuecomment-427777209, we are closing this as this is non issue.
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.html
