### ISSUE TITLE
"Confirmation request" email is sent on customer's newsletter unsubscription

### ISSUE THREAD

**Issue by densen45** [magento/magento2#15218]
### Preconditions

1. PHP 7.0 + 7.1
2. Magento 2.2.4

### Steps to reproduce

1. Activate "Need to Confirm" for the newsletter subscription
2. Create a new customer
3. Subscribe to the newsleter
4. Confirm the newsletter subscription (email --> link)
5. Login as the previous created customer
5. Unsubscribe from the newsletter from the customer area

### Expected result

1. The customer is being unsubscribed from the newsletter
2. Only the "unsubscription confirmation" email will be sent

### Actual result

1. The customer is being unsubscribed from the newsletter
2. The "unsubscription confirmation" email is sent
3. Also the "confirmation request" email is sent although the customer wants to unsubscribe from the newsletter.

This is really odd. The customers are being confused by these "confirmation request" emails. It seems like you don't want them to unsubscribe. The worst thing is that when customers click on the link (because they did not read carefully and assumed they have to confirm the unsubscription) they are being subscribed to the newsletter again.

**Comment by dasharath-wagento** [comment]
I'm working on it #dmcdindia

**Comment by vkublytskyi** [comment]
Reassigned to @nuzil as he provided PR #15464 with a possible fix

**Comment by VladimirZaets** [comment]
Hi @densen45. Thank you for your report. 
The issue has been fixed in magento/magento2#15464 by @nuzil in 2.2-develop branch
Related commit(s):
 - [d790198da9b7a4fc665f17140b17c88598ec08fe](https://github.com/magento/magento2/commit/d790198da9b7a4fc665f17140b17c88598ec08fe)
 - [1f664218cf038d927ef9873de8b1ea6105931c2e](https://github.com/magento/magento2/commit/1f664218cf038d927ef9873de8b1ea6105931c2e)
 - [f80eb037161eb506ddd431955b4614d434cbb1dd](https://github.com/magento/magento2/commit/f80eb037161eb506ddd431955b4614d434cbb1dd)
 - [3227832d1467f77fd11133161a904e67def4f771](https://github.com/magento/magento2/commit/3227832d1467f77fd11133161a904e67def4f771)
 - [69eb20f0e714d07bb2031b7811f0ea7ecc6a74ec](https://github.com/magento/magento2/commit/69eb20f0e714d07bb2031b7811f0ea7ecc6a74ec)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @densen45. Thank you for your report. 
The issue has been fixed in magento/magento2#16995 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [ffa036de7266d1982655d521315ef3f5d2851425](https://github.com/magento/magento2/commit/ffa036de7266d1982655d521315ef3f5d2851425)
 - [a36f791ec3ac99d2706c08f969fed608c0b63e0f](https://github.com/magento/magento2/commit/a36f791ec3ac99d2706c08f969fed608c0b63e0f)
 - [1b504cdec56c63060042d4ae08d1cac743c0e1ff](https://github.com/magento/magento2/commit/1b504cdec56c63060042d4ae08d1cac743c0e1ff)
 - [ac4a2fa7216b5aa9bd5de282b06c5a50a737490d](https://github.com/magento/magento2/commit/ac4a2fa7216b5aa9bd5de282b06c5a50a737490d)
 - [3533e68e1617d8c5ab8381674a6840d5f821bb55](https://github.com/magento/magento2/commit/3533e68e1617d8c5ab8381674a6840d5f821bb55)

The fix will be available with the upcoming 2.3.0 release.
