### ISSUE TITLE
Advanced pricing pagination issue

### ISSUE THREAD

**Issue by dryadav** [magento/magento2#15210]
There is a product which has more than 25 tier price (customer group price) in Advanced Pricing section.

Magento creates the pagination automatically if there are more than 20 customer group price row.

If I click on a next/previous button of pagination, it works properly and navigates the pricing page. But if I enter any page number in the input field and press enter button, it keeps on loading.

You can check the video using attached link.

### Preconditions
I checked this issue in following Magento versions
1.  Magento 2.2.2
2. Magento 2.2.3
3. Magento 2.2.4

### Steps to reproduce

1.  Select any product and add more than 25 customer group prices.
2.  Enter any page number to navigate the customer group price page.
3.  Press enter.

### Expected result
1.  It should navigate to the entered page number.

### Actual result

1. It keeps on loading the page. You can check a video here.  

[http://nimb.ws/5eGZPB](http://nimb.ws/5eGZPB)

**Comment by magento-engcom-team** [comment]
Hi @dryadav. Thank you for your report. 
The issue has been fixed in magento/magento2#15360 by @saravananvelu in 2.3-develop branch
Related commit(s):
 - [cad44a3db14797f7fd2978e1c2a252e785fc0ec1](https://github.com/magento/magento2/commit/cad44a3db14797f7fd2978e1c2a252e785fc0ec1)
 - [560aa38603ac0cd7762ff7d791c598f734eb5435](https://github.com/magento/magento2/commit/560aa38603ac0cd7762ff7d791c598f734eb5435)
 - [8a8ed6613cebd8bddd1f1d9504af47d8ac18cc55](https://github.com/magento/magento2/commit/8a8ed6613cebd8bddd1f1d9504af47d8ac18cc55)
 - [ba6bf77e781dd633134a293a1521d13938cabf07](https://github.com/magento/magento2/commit/ba6bf77e781dd633134a293a1521d13938cabf07)
 - [6de6006220c91be431e68710b481e50393ed2578](https://github.com/magento/magento2/commit/6de6006220c91be431e68710b481e50393ed2578)
 - [ec3eb1ae80716712b1fca54a7becc62a4686815b](https://github.com/magento/magento2/commit/ec3eb1ae80716712b1fca54a7becc62a4686815b)
 - [75960ce8d73e7d924d9f9bf820e4c82a2b0ff543](https://github.com/magento/magento2/commit/75960ce8d73e7d924d9f9bf820e4c82a2b0ff543)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @dryadav. Thank you for your report. 
The issue has been fixed in magento/magento2#15614 by @dmytro-ch in 2.2-develop branch
Related commit(s):
 - [896ca96988ed8b79e2cc732415655fdbada14463](https://github.com/magento/magento2/commit/896ca96988ed8b79e2cc732415655fdbada14463)

The fix will be available with the upcoming 2.2.6 release.
