### ISSUE TITLE
Alignment & overlapping Issue on every Home page & category page of Hot Seller section

### ISSUE THREAD

**Issue by cnviradiya** [magento/magento2#15213]
### Preconditions

1. Magento Version is 2.2.0
2. Php Version is 7.1.8
3. MySQL version is 4.7.0
4. Operating System Window 10Pro
5. Screen Resolution is 1920 x 1080

### Steps to reproduce

1. On Home page there are issue worth alignment for after the second row of product listing (Hot seller section)
2. On Category Page there are section name Hot seller that section also same issue

### Expected result

1. It would be in same alignment either same as second row or first row but alignment will be same

### Actual result

1. ![hotsellersection_design_issue_15_05_2018](https://user-images.githubusercontent.com/9442993/40042498-4264a852-583f-11e8-823f-1796d98109ac.png)
2. ![listing_alignment_design_issue_15_05_2018](https://user-images.githubusercontent.com/9442993/40042510-4a348ce6-583f-11e8-8cc7-2f12c0b77cbd.png)
3. ![product_hover_overlap_design_issue_15_05_2018](https://user-images.githubusercontent.com/9442993/40042516-506253e6-583f-11e8-9b9a-33aa20fb19ec.png)

**Comment by magento-engcom-team** [comment]
Hi @cnviradiya. Thank you for your report. 
The issue has been fixed in magento/magento2#15896 by @chirag-wagento in 2.3-develop branch
Related commit(s):
 - [a8515408a1879dc2e1c0e39615f9a431746584e8](https://github.com/magento/magento2/commit/a8515408a1879dc2e1c0e39615f9a431746584e8)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @cnviradiya. Thank you for your report. 
The issue has been fixed in magento/magento2#15893 by @chirag-wagento in 2.2-develop branch
Related commit(s):
 - [51d099186543380523af374286c0c890bbbbd284](https://github.com/magento/magento2/commit/51d099186543380523af374286c0c890bbbbd284)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @cnviradiya. Thank you for your report. 
The issue has been fixed in magento/magento2#16287 by @chirag-wagento in 2.1-develop branch
Related commit(s):
 - [c601b844777251ce08f402c1cc0d6ebf67f14428](https://github.com/magento/magento2/commit/c601b844777251ce08f402c1cc0d6ebf67f14428)

The fix will be available with the upcoming 2.1.15 release.
