### ISSUE TITLE
Bundle item selections pagination

### ISSUE THREAD

**Issue by msieprawski** [magento/magento2#15219]
### Preconditions
Magento 2.2.0 CE
PHP 7.024

### Steps to reproduce
1. Login to admin interface
2. Create bundle product
3. Create at least 31 simple products
4. Edit previously created bundle product
5. Create one bundle items option and add at least 31 products under it
6. Make sure that your bundle option has pagination (see image below)
![image](https://user-images.githubusercontent.com/6512866/40056613-3e36a4d0-584c-11e8-8881-33b9e028bb2a.png)
7. Now go to second page and try to drag n drop first item on second page to first page

### Expected result
1. The problem is that I can't change the order of products under bundle option if I've got more than one page as I can't hold product row and move it to first page
2. It should change the page when dragging over page controls or something...

### Actual result
1. I can change order of products only within current page

For now I've create plugin for `Magento\Bundle\Ui\DataProvider\Product\Form\Modifier\BundlePanel` in order to create dumb workaround:
`$meta['bundle-items']['children']['bundle_options']['children']['record']['children']['product_bundle_container']['children']['bundle_selections']['arguments']['data']['config']['pageSize'] = 9999;`

**Comment by ghost** [comment]
@msieprawski, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by cmcantrell** [comment]
Has there been any progress on this issue?  I have the same problem with Bundled Products.  The amount of Products have exceeded 20.  

I have tried experimenting with the pageSize variable mentioned by @msieprawski in vendor/magento/module-grouped-product/Ui/DataProvider/Product/Form/Modifier/Grouped.php.  I can log output from $meta["grouped"]["children"]["grouped_products_modal"]["children"]["grouped_product_listing"]["arguments"]["data"]["config"] and see my variable, but don't see any results on the front end.  

I really just need to be able to increase the size of the bundled products from 20 to a designated number.  How can this be achieved?


**UPDATE:**  For anyone looking to simply update the page size on Grouped Product listings, I was just manipulating the wrong data.  Instead of:
$meta["grouped"]["children"]["grouped_products_modal"]["children"]["grouped_product_listing"]["arguments"]["data"]["config"]

set your pageSize variable on:
$meta["grouped"]["children"]["associated"]["arguments"]["data"]["config"]["pageSize"]

**Comment by igi8819** [comment]
any update on this?
why you guys not working on a sulution?
