### ISSUE TITLE
2.2.4: navigation dropdown caret icon missing (jQuery UI)

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15220]
### Preconditions

1. create a demo store with Luma with the sample data

### Steps to reproduce

1. create store with sample data
2. hover over one of the navigation catories
3. inspect the parent navigation point

### Expected result

1. there should be a caret icon

### Actual result

1. there is no caret icon as the jQuery UI classes do not exist (anymore) and were never replaced

![bildschirmfoto 2018-05-15 um 14 40 09](https://user-images.githubusercontent.com/827205/40057221-ef91d5d2-584d-11e8-9084-b1f62bc413be.png)
<img width="559" alt="bildschirmfoto 2018-05-15 um 14 39 58" src="https://user-images.githubusercontent.com/827205/40057222-efc20950-584d-11e8-8d9c-6eab01dd1cc6.png">

`ui-menu-icon ui-icon ui-icon-carat-1-e`

**Comment by tejash-wagento** [comment]
I am working on this

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16082 by @tejash-wagento in 2.2-develop branch
Related commit(s):
 - [3e4421c6beab94a1b30af1e9ab4c6123b76c253b](https://github.com/magento/magento2/commit/3e4421c6beab94a1b30af1e9ab4c6123b76c253b)

The fix will be available with the upcoming 2.2.6 release.
