### ISSUE TITLE
2.2.4 Using Redis when going to System Web Setup Wizard will be Fatal error

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#15239]
### Preconditions

1. PHP71
2. Centos 7
3. Magento 2.2.4

### Steps to reproduce

1. Using Redis
2. Going to System Web Setup Wizard will be Fatal error

### Expected result

1.  Who can help me, please, thank you!
2. when using 2.2.3 is working

### Actual result

1. Using Redis when going to System Web Setup Wizard will be Fatal error
I tried in `app/etc/env.php` edit `'save' => 'redis',` to `'save' => 'files',` will be working. but why?

> Fatal error: Uncaught Exception: Warning: ini_set(): Cannot find save handler 'redis' in public_html/vendor/magento/framework/Session/SessionManager.php on line 570 in public_html/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'ini_set(): Cann...', '...', 570, Array) #1 public_html/vendor/magento/framework/Session/SessionManager.php(570): ini_set('session.save_ha...', 'redis') #2 public_html/vendor/magento/framework/Session/SessionManager.php(184): Magento\Framework\Session\SessionManager->initIniOptions() #3 public_html/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(37): Magento\Framework\Session\SessionManager->start() #4 public_html/vendor/magento/framework/Session/SessionManager.php(130): Magento\Backend\Model\Auth\Session\Interceptor->start() #5 public_html/vendor/magento/module-backend/Model/Aut in public_html/vendor/magento/framework/App/ErrorHandler.php on line 61

**Comment by engcom-backlog-nickolas** [comment]
Hello @rigu12, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @andy17612 The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by dunagan5887** [comment]
@engcom-backlog-nazar We are on 2.2.6 Commerce Edition and have already spent months developing a solution; as such it's a bit late for us to move to 2.3 given our upcoming deployment is very soon. Would you be able to provide a patch file that we could apply to our codebase to resolve this issue?

**Comment by KSATE** [comment]
> @engcom-backlog-nazar We are on 2.2.6 Commerce Edition and have already spent months developing a solution; as such it's a bit late for us to move to 2.3 given our upcoming deployment is very soon. Would you be able to provide a patch file that we could apply to our codebase to resolve this issue?

hi @dunagan5887 : did you try to switch the deploy mode to "developer" and re-execute "setup:upgrade" ?
