### ISSUE TITLE
Advanced Reporting > Unable to disable without providing Industry value

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#15259]
### Preconditions

1. Magento 2.2.3
2. PHP7.1

### Steps to reproduce

1. Goto Backend > Stores > Configuration > General > Advanced Reporting
2. Save config (while Industry is not provided)

### Expected result

1. One should be able to save without providing the Industry value 

### Actual result

1. Can't save. A message appears: "Please select a vertical."

After selecting an Industry (vertical) the config gets saved. The field shouldn't be a required field, when trying to disable.

<img width="961" alt="bildschirmfoto 2018-05-16 um 15 29 11" src="https://user-images.githubusercontent.com/1556434/40119804-e6401aae-591d-11e8-8208-6ed150d0fe13.png">

**Comment by sunilit42** [comment]
I am working on this at #dmcdindia

**Comment by okorshenko** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#15366 by @sunilit42 in 2.2-develop branch
Related commit(s):
 - [274fee981c33ee22b296f99e1ca6cc009d7abaa2](https://github.com/magento/magento2/commit/274fee981c33ee22b296f99e1ca6cc009d7abaa2)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#18782 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [6862c04ece31c29d41be7ac65005e9bdf7c24490](https://github.com/magento/magento2/commit/6862c04ece31c29d41be7ac65005e9bdf7c24490)

The fix will be available with the upcoming 2.3.1 release.
