### ISSUE TITLE
Cannot set billing address when paying with Braintree vaulted credit card

### ISSUE THREAD

**Issue by scottsb** [magento/magento2#15270]
### Preconditions
* Magento 2.1.12 or Magento 2.2.0
* Braintree Vault enabled as payment method
* Stores -> Configuration -> Checkout -> Checkout Options -> Display Billing Address On setting is set to "Payment Method"

### Steps to reproduce
1. Place an order with address "A" as billing & shipping. Use Braintree credit card as payment method and choose to save for later (i.e., add it to vault).
2. Place a new order with address "B" as shipping. Select saved Braintree credit card.

### Expected result
I could see several reasonable behaviors:
* Interface to select a billing address is presented
* Address "A" is used automatically as billing address since it was used when credit card was vaulted
* Combination of these (ideal): interface to select a billing address is presented, defaulted to the address "A" used when the payment method was vaulted

### Actual result
Address "B" (shipping address from second order) is used as billing address on new order. No interface to view or change the billing address is presented.

**Comment by scottsb** [comment]
This seems to be a pretty glaring issue that I'm surprised hasn't been reported already, so please let me know if this is an intentional design decision for some reason.

**Comment by YevSent** [comment]
@scottsb, this is not an issue. This is how the checkout flow is designed.
When a registered customer chooses a shipping address, this address also will be set as billing: `rest/default/V1/carts/mine/shipping-information`.
Not a payment method recognizes which address should be used as billing, it already set in a quote.

Anyway, you can change the billing address on the payment step. There are two options in Magento: billing address per each payment or for all payment methods. To change this option, you need to configure `Stores` -> `Configuration` -> `Checkout` -> `Checkout Options` -> `Display Billing Address On`. By default this option set to `Payment Method`.

**Comment by scottsb** [comment]
@joni-jonesI don't quite understand what you're saying here:

> Not a payment method recognizes which address should be used as billing, it already set in a quote.

**Comment by scottsb** [comment]
@joni-jones: I should have put as a precondition that the "Display Billing Address On" option is set to "Payment Method." I know that you can change it to "Payment Page" to force the billing address to always display in its own section in checkout, but that shouldn't be necessary.

I'm not quite sure what you mean by this:

> Not a payment method recognizes which address should be used as billing, it already set in a quote.

The point of the "Payment Method" option in the setting you mentioned is to allow the payment method to determine whether a billing address is needed or not. So in this case the payment method does "recognize" which address should be used for billing. And when entering a new card with Braintree the payment method front-end code correctly provides an interface to select the billing address. The problem is that when paying with a saved card, this interface is not provided. This means that if AVS checks are enforced, the saved card may be rejected because the billing address won't be (and can't be) correct if it ought to be different than the shipping address.

**Comment by YevSent** [comment]
> The point of the "Payment Method" option in the setting you mentioned is to allow the payment method to determine whether a billing address is needed or not.

Yes, it's true. But

> So in this case the payment method does "recognize" which address should be used for billing.

Actually, not. The payment method uses a billing address from the quote and in the most cases (if we are not talking about specific cases, like the billing address provided by a payment gateway) even doesn't "know" where and by "who" this address was set. That what I meant talking about addresses recognizing.

> The problem is that when paying with a saved card, this interface is not provided. This means that if AVS checks are enforced, the saved card may be rejected because the billing address won't be (and can't be) correct if it ought to be different than the shipping address.

That's why we added extra configuration as `Display Billing Address On`.

**Comment by scottsb** [comment]
@joni-jones, I think we're not on the same page still. You write:

> If we are not talking about specific cases...

But I am talking about a specific case: I'm talking about Braintree vaulted credit card payments. And, contrary to your last comment, the payment method *does* know about where the billing address is set, or at least whether it is set within the UI context of the payment method (when the site is configured to show the billing address on the payment step).

See here where the Braintree template includes the billing address component:
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Braintree/view/frontend/web/template/payment/form.html#L22

Whether there is in fact anything in that requested region comes down to this conditional:
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Checkout/Block/Checkout/LayoutProcessor.php#L257

Which as you can see, is checking the XML configuration located (in the case of Braintree) here:
https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Braintree/view/frontend/layout/checkout_index_index.xml#L33

I have not thoroughly investigated (yet at least), but I suspect the problem is that the above XML line only applies to the method name `"braintree"`, but in the case of a vaulted credit card payment the method name is `"braintree_cc_vault"`.

As to this point:

> That's why we added extra configuration as Display Billing Address On.

That just doesn't make sense to me. That setting is clearly talking only about *where* the billing address should be collected. I should be able to use either setting depending on how I want the checkout flow to work and still be able to collect billing addresses when relevant.

**Comment by misha-kotov** [comment]
From the business use case perspective, this scenario looks valid to me. 

A simple example is "I registered on a site, bought myself an item (with my billing/shipping address), and saved the card. I come back and want to buy an item to be shipped to my parents' house using the saved card". In this case I need to provide a different shipping address and keep the original billing address, otherwise my card could get rejected. The scenario itself seems common. 

Quick check on Amazon confirms this is very accessible operation: 
![image](https://user-images.githubusercontent.com/18131925/40558044-bb6f3ed0-6017-11e8-9c96-eacdf3f814a4.png)

The question is - should this be possible with "Display Billing Address On = Payment Method" setting in Magento? I would say yes, since there could be various layout/design/customization reasons for a merchant to use this setting, not to mention it could be costly for them to switch. I agree the impact of the setting should be in design only and not in functionality. 

So I would leave this as an open issue for now. @scottsb if you arrive at a solution before we do, feel free to submit a PR for it.

**Comment by graemel** [comment]
Sorry, I'm still thoroughly confused by this. Why is the default behaviour to not use the previous billing address.

Surely the normal use case for a saved card is, customer places an order with billing address X. Next time they place an order, they might ship somewhere different, but why would their billing address have changed? I mean, they might have moved house, but surely that's the exception rather than the rule.

In particular with Braintree, the previous billing address is actually associated with the vault entry so the billing address in Braintree for the vault item and the billing address on the order are different.

**Comment by engcom-Alfa** [comment]
Hi @scottsb, thank you for your report.

Unfortunately, we are not able to reproduce this issue on a fresh 2.4-develop instance.

**Manual testing scenario:**
1. Create a customer;
2. Place an order with address "A" as billing & shipping. Use Braintree credit card as a payment method and choose to save for later (i.e., add it to the vault).
![screen1](https://user-images.githubusercontent.com/51679138/72720529-d8f5dc00-3b82-11ea-88da-3def042be3a4.png)
3. Place a new order with address "B" as shipping. Select saved Braintree credit card.

**Actual Result:**
:heavy_check_mark:  Interface to select a billing address is presented
:heavy_check_mark: Address "A" is used automatically as billing address since it was used when a credit card was vaulted
![payment](https://user-images.githubusercontent.com/51679138/72721249-43f3e280-3b84-11ea-8c6a-966e188ea13a.gif)

@scottsb Could you take a look?

Thanks!

**Comment by djacques4gorilla** [comment]
@engcom-Alfa If this issue was resolved in the 2.4 development branch, that's good, but if so would it be possible to point out which commit/PR fixed it in order to backport the fix and create a patch for existing 2.2 and 2.3 stores, and hopefully build it into 2.3.5 too? Thanks!

**Comment by djacques4gorilla** [comment]
Actually, looks like it was MAGETWO-91624 (https://github.com/magento/magento2/commit/06c69e361b283911fb2c2db4da04f81226749a9e), which was built into 2.3.0. This issue is marked as having been reproduced on 2.3.x, so perhaps we need to re-validate if this is really true. If we can't reproduce on 2.3, then the commit above is most likely the fix needed.

**Comment by tcmax76** [comment]
We're on Magento 2.3.4, and the functionality shown in @engcom-Alfa 's gif above is definitely not happening on our checkout with vaulted cards. We had to turn off vaulted cards for this reason.

**Comment by tcmax76** [comment]
Check my previous post. I just realized after looking at the commit referenced by @djacques4gorilla above, that our gene commerce braintree extension wasn't adding this code to the checkout_index_index.xml file:

`<item name="braintree_cc_vault" xsi:type="array">
                                                                            <item name="isBillingAddressRequired" xsi:type="boolean">true</item>
                                                                        </item>`

**Comment by djacques4gorilla** [comment]
@tcmax76 When you say "our Gene Commerce Braintree extension", do you mean you are responsible for maintaining it, or only that your Magento store is using it? I believe we also had the issue due to the Gene Commerce extension, so it would need to be fixed, but Magento won't be the ones to do it.

**Comment by engcom-Alfa** [comment]
@scottsb We double-checked the issue again and had the same result as in [comment](https://github.com/magento/magento2/issues/15270#issuecomment-576221239). The issue isn't reproducible on fresh 2.4-develop.
So, we have to close it.
Please, feel free to comment, reopen or create new ticket according to the[ Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` brunch. Thank you for collaboration.

**Comment by rohitkumawat17** [comment]
how can we solve this issue in Magento 2.2.11. Any solution?
