### ISSUE TITLE
misleading data-container in product list

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15319]
### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. inspect the product list and see `data-container="product-grid"`

### Expected result

1. `data-container="product-list"`

### Actual result

1. `data-container="product-grid"`

**Comment by sunilit42** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#15350 by @sunilit42 in 2.2-develop branch
Related commit(s):
 - [8c144a26281aeb9c773b98b8c8bbd7ffecc0658b](https://github.com/magento/magento2/commit/8c144a26281aeb9c773b98b8c8bbd7ffecc0658b)
 - [9e0db3089f61d29cd3df436d38c9f3af589d81be](https://github.com/magento/magento2/commit/9e0db3089f61d29cd3df436d38c9f3af589d81be)
 - [03465eb87e2956e42bd7ea998708436d1274d936](https://github.com/magento/magento2/commit/03465eb87e2956e42bd7ea998708436d1274d936)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#15816 by @viral-wagento in 2.1-develop branch
Related commit(s):
 - [1a94fd8262530171e947d58e5750900120826fe6](https://github.com/magento/magento2/commit/1a94fd8262530171e947d58e5750900120826fe6)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#17751 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [cba6c39197568d8255541b9871e53582d72f1b60](https://github.com/magento/magento2/commit/cba6c39197568d8255541b9871e53582d72f1b60)

The fix will be available with the upcoming 2.3.0 release.
