### ISSUE TITLE
Purchased Order Form button should visible properly

### ISSUE THREAD

**Issue by neeta-wagento** [magento/magento2#15334]
### Preconditions

1. Enable Purchase Order Payment Method from Admin 

### Steps to reproduce

1. - Add Product in Cart
2. - Go to Checkout 

### Expected result

1. 
![screenshot-2018-5-19 checkout](https://user-images.githubusercontent.com/33098216/40265965-e357a4bc-5b5f-11e8-9b9a-f9c905fc00c3.png)

### Actual result

1. 
![screenshot-2018-5-19 checkout 1](https://user-images.githubusercontent.com/33098216/40265973-051ca958-5b60-11e8-814b-eeaef60764bc.png)

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#15331 by @neeta-wagento in 2.2-develop branch
Related commit(s):
 - [0605a27dfa4b05f7176dfb4815458c4bb57219f5](https://github.com/magento/magento2/commit/0605a27dfa4b05f7176dfb4815458c4bb57219f5)
 - [eae0ac6b02eec639f6060bf1e39709344252d94f](https://github.com/magento/magento2/commit/eae0ac6b02eec639f6060bf1e39709344252d94f)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#15372 by @vgelani in 2.2-develop branch
Related commit(s):
 - [35b2cdf075d5fa1d4117cfb11749eff71c292380](https://github.com/magento/magento2/commit/35b2cdf075d5fa1d4117cfb11749eff71c292380)
 - [be8c6cb58acb79863a67b5d5d0b076e0dc61b822](https://github.com/magento/magento2/commit/be8c6cb58acb79863a67b5d5d0b076e0dc61b822)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#15577 by @osrecio in 2.3-develop branch
Related commit(s):
 - [751c3e609e4529d96c64c0c06c6e84efcdec5f92](https://github.com/magento/magento2/commit/751c3e609e4529d96c64c0c06c6e84efcdec5f92)
 - [fb0f192c767f3f8e30a7c861108768d35fbc8b24](https://github.com/magento/magento2/commit/fb0f192c767f3f8e30a7c861108768d35fbc8b24)

The fix will be available with the upcoming 2.3.0 release.
