### ISSUE TITLE
Multiple Payment Methods Enabled is giving error in console "Found 3 Elements with non - unique Id"

### ISSUE THREAD

**Issue by neeta-wagento** [magento/magento2#15348]
When enabling more then one payment methods from admin , It is giving error in the console "Found elements with non-unique id billing-address-form "

### Preconditions

1. In any magento versions

### Steps to reproduce

1. Login to Admin Panel > Sales> Payment Methods
2. Enable more then one of Magento payment methods for checkout
3. Add a product into the cart, press F12 to check the console log in the browser

### Expected result

1. It should not show any error in the console

### Actual result

1. [Screenshot, logs] 
![screenshot from 2018-05-19 14-10-36](https://user-images.githubusercontent.com/33098216/40266849-f22005c4-5b6f-11e8-94cd-c0894b6a3c42.png)

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#15349 by @neeta-wagento in 2.2-develop branch
Related commit(s):
 - [20d8e6afbe15b37949f22ed35ec20f547fba5861](https://github.com/magento/magento2/commit/20d8e6afbe15b37949f22ed35ec20f547fba5861)
 - [3c8f6f433445e6f339ff15178a7c133dbaeff95a](https://github.com/magento/magento2/commit/3c8f6f433445e6f339ff15178a7c133dbaeff95a)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @neeta-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#15834 by @viral-wagento in 2.1-develop branch
Related commit(s):
 - [b63d2c51aaba7d55f8e288c55892221182a7c455](https://github.com/magento/magento2/commit/b63d2c51aaba7d55f8e288c55892221182a7c455)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#15732 by @vijay-wagento in 2.3-develop branch
Related commit(s):
 - [5822e4422213a4bacfccce41df3c8e87ccc7da1a](https://github.com/magento/magento2/commit/5822e4422213a4bacfccce41df3c8e87ccc7da1a)
 - [4847b463a6e1305636f99455de45f296840ee979](https://github.com/magento/magento2/commit/4847b463a6e1305636f99455de45f296840ee979)

The fix will be available with the upcoming 2.3.0 release.
