### ISSUE TITLE
Template syntax in block file

### ISSUE THREAD

**Issue by gelanivishal** [magento/magento2#15345]
### Preconditions

1. Magento 2.2.4
2. PHP 7.1.15
3. MySQL 14.14
4. Ubuntu

### Steps to reproduce

Not followed correct syntax to set template in following block file
app/code/Magento/Theme/Block/Html/Breadcrumbs.php

### Expected result

`protected $_template = 'Magento_Theme::html/breadcrumbs.phtml';`

### Actual result

`protected $_template = 'html/breadcrumbs.phtml';`

**Comment by magento-engcom-team** [comment]
Hi @vgelani. Thank you for your report. 
The issue has been fixed in magento/magento2#15339 by @NamrataChangani in 2.2-develop branch
Related commit(s):
 - [efd58e34af13c0497652e10ae2151dc9e6e55802](https://github.com/magento/magento2/commit/efd58e34af13c0497652e10ae2151dc9e6e55802)
 - [86b98956b30950f9e00817e6cea12849de888a94](https://github.com/magento/magento2/commit/86b98956b30950f9e00817e6cea12849de888a94)
 - [c1ce795be9bfd0834e6e53a5edf303666595cce1](https://github.com/magento/magento2/commit/c1ce795be9bfd0834e6e53a5edf303666595cce1)
 - [5118361850fcffe0d94a52e3f524ea4e920e9cfa](https://github.com/magento/magento2/commit/5118361850fcffe0d94a52e3f524ea4e920e9cfa)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @gelanivishal. Thank you for your report. 
The issue has been fixed in magento/magento2#16805 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [98cc7522594a0cfb33c5ce5d017948e551c4462c](https://github.com/magento/magento2/commit/98cc7522594a0cfb33c5ce5d017948e551c4462c)
 - [4499034ae38aeed1d547971d57da0365aa89ce71](https://github.com/magento/magento2/commit/4499034ae38aeed1d547971d57da0365aa89ce71)
 - [b405dfaddc12ff42f90425de1f45530cced78327](https://github.com/magento/magento2/commit/b405dfaddc12ff42f90425de1f45530cced78327)

The fix will be available with the upcoming 2.3.0 release.
