### ISSUE TITLE
Reformat the javascript code as per magento standards.

### ISSUE THREAD

**Issue by sanganinamrata** [magento/magento2#15352]
1. Magento 2.2.4
2. PHP 7.1.15
3. MySQL 14.14
4. Ubuntu

 Use javascript inside *.phtml file it's legacy code that we try to refactor according to Magento way.
For that we have <script type="text/x-magento-init" /> tag, where we declare path to JS file and pass parameters if they are needed.

### Preconditions

N/A

### Steps to reproduce

N/A

### Expected result

JS Script code should be removed from template file and treated as a separate component

### Actual result

Affected file: `app/code/Magento/Tax/view/adminhtml/templates/class/page/edit.phtml`
JS script is added directly to template file.(Wrong coding format)

**Comment by magento-engcom-team** [comment]
Hi @NamrataChangani. Thank you for your report. 
The issue has been fixed in magento/magento2#15343 by @vgelani in 2.2-develop branch
Related commit(s):
 - [00bfbd0e8f556fa0e916fc4757c767741093c2ab](https://github.com/magento/magento2/commit/00bfbd0e8f556fa0e916fc4757c767741093c2ab)
 - [cdc5b2ffbc4540f86a0054cc41d650b9a3cf2ec8](https://github.com/magento/magento2/commit/cdc5b2ffbc4540f86a0054cc41d650b9a3cf2ec8)
 - [f8d5312c4903ebcf34059a5531723df55ffff3d0](https://github.com/magento/magento2/commit/f8d5312c4903ebcf34059a5531723df55ffff3d0)
 - [2ecf8c67bdd81dcd15874b73d72cb4ef9b14ecfd](https://github.com/magento/magento2/commit/2ecf8c67bdd81dcd15874b73d72cb4ef9b14ecfd)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @NamrataChangani. Thank you for your report. 
The issue has been fixed in magento/magento2#15560 by @vgelani in 2.3-develop branch
Related commit(s):
 - [467ebb2b234def50f0ca2f95ad372953bfa60071](https://github.com/magento/magento2/commit/467ebb2b234def50f0ca2f95ad372953bfa60071)
 - [4ec581c858b79cc40862c8f746e3efb3658af67b](https://github.com/magento/magento2/commit/4ec581c858b79cc40862c8f746e3efb3658af67b)
 - [4078907739178bb2339b0f343fb3567acbb7ea8e](https://github.com/magento/magento2/commit/4078907739178bb2339b0f343fb3567acbb7ea8e)
 - [60ed6801a43698cb88edb30cc262b7f9d38f49ee](https://github.com/magento/magento2/commit/60ed6801a43698cb88edb30cc262b7f9d38f49ee)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @NamrataChangani. Thank you for your report. 
The issue has been fixed in magento/magento2#16270 by @vgelani in 2.1-develop branch
Related commit(s):
 - [67a9e13ae7472a66cafb84b5614cfd511aee2b8c](https://github.com/magento/magento2/commit/67a9e13ae7472a66cafb84b5614cfd511aee2b8c)

The fix will be available with the upcoming 2.1.15 release.
