### ISSUE TITLE
Refactore javascript for module URL rewrite

### ISSUE THREAD

**Issue by gelanivishal** [magento/magento2#15356]
Use javascript inside *.phtml file it's legacy code that we try to refactor according to Magento way.
For that we have [<script type="text/x-magento-init" />](https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js_init.html) tag, where we declare path to JS file and pass parameters if they are needed

### Preconditions

1. Magento 2.2.4
2. PHP 7.1.15
3. MySQL 14.14
4. Ubuntu

### Steps to reproduce

1. Go to Marketing > URL rewrites > Edit 
2. Remove request path text box value

### Expected result

JS Script code should be removed from template file and treated as a separate component

### Actual result

JS script is added directly to template file.(Wrong coding format)

**Comment by sidolov** [comment]
Hi @vgelani. Thank you for your report. 
The issue has been fixed in magento/magento2#15422 by @patelnimesh1988 in 2.2-develop branch
Related commit(s):
 - [28642a6b17ba9c6d64061ea90f7d39348a5ed767](https://github.com/magento/magento2/commit/28642a6b17ba9c6d64061ea90f7d39348a5ed767)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @vgelani. Thank you for your report. 
The issue has been fixed in magento/magento2#15747 by @vijay-wagento in 2.3-develop branch
Related commit(s):
 - [6711694e180078c714f9216ac0b83cef74ac0a6f](https://github.com/magento/magento2/commit/6711694e180078c714f9216ac0b83cef74ac0a6f)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @vgelani. Thank you for your report. 
The issue has been fixed in magento/magento2#16992 by @chirag-wagento in 2.1-develop branch
Related commit(s):
 - [846347dd6660c9174842fdb7fb199986eb7bf7c5](https://github.com/magento/magento2/commit/846347dd6660c9174842fdb7fb199986eb7bf7c5)

The fix will be available with the upcoming 2.1.15 release.
