### ISSUE TITLE
Function is unnecessarily called multiple time

### ISSUE THREAD

**Issue by saurabh-parekh** [magento/magento2#15355]
### Preconditions

1. Magento 2.2.4
2. PHP 7.1.15
3. MySQL 14.14
4. Ubuntu

### Steps to reproduce

Function is unnecessarily called multiple time.
app/code/Magento/CurrencySymbol/view/adminhtml/templates/grid.phtml

### Expected result

`<?php $block->getCurrencySymbolsData();?>`  should be used only single time.

### Actual result

`<?php $block->getCurrencySymbolsData();?>` is used multiple times in the same file.

**Comment by magento-engcom-team** [comment]
Hi @saurabh-aureate. Thank you for your report. 
The issue has been fixed in magento/magento2#15346 by @saurabh-aureate in 2.2-develop branch
Related commit(s):
 - [933927953ddb5871b3eef96aab36064b55d97d82](https://github.com/magento/magento2/commit/933927953ddb5871b3eef96aab36064b55d97d82)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @saurabh-aureate. Thank you for your report. 
The issue has been fixed in magento/magento2#15763 by @vgelani in 2.3-develop branch
Related commit(s):
 - [bcdd8f2a6fdc722828b3c0d3ac72fd19df1ae226](https://github.com/magento/magento2/commit/bcdd8f2a6fdc722828b3c0d3ac72fd19df1ae226)

The fix will be available with the upcoming 2.3.0 release.

**Comment by VladimirZaets** [comment]
Hi @saurabh-aureate. Thank you for your report. 
The issue has been fixed in magento/magento2#16761 by @gelanivishal in 2.1-develop branch
Related commit(s):
 - [7a6217c5a6bc59f9b318c0de1d73ef3c8c3eccca](https://github.com/magento/magento2/commit/7a6217c5a6bc59f9b318c0de1d73ef3c8c3eccca)

The fix will be available with the upcoming 2.1.15 release.
