### ISSUE TITLE
Refactor javascript code of button split widget call js component

### ISSUE THREAD

**Issue by amittiwari024** [magento/magento2#15354]
Refactor javascript code of button split widgete

### Preconditions
1. Need to refactor template file and need to call js component which is already created
magento2\app\code\Magento\Ui\view\base\web\js\grid\controls\button\split.js
 

### Steps to reproduce

1. N/A

### Expected result

1.N/A 

### Actual result

1.N/A

**Comment by amittiwari024** [comment]
Issue is fixed: #15351

**Comment by magento-engcom-team** [comment]
Hi @amittiwari024. Thank you for your report. 
The issue has been fixed in magento/magento2#15351 by @amittiwari024 in 2.2-develop branch
Related commit(s):
 - [37851f48002c80ee8456e38b9be96b2990999f0f](https://github.com/magento/magento2/commit/37851f48002c80ee8456e38b9be96b2990999f0f)

The fix will be available with the upcoming 2.2.5 release.

**Comment by sidolov** [comment]
Hi @amittiwari024. Thank you for your report. 
The issue has been fixed in magento/magento2#15731 by @vijay-wagento in 2.3-develop branch
Related commit(s):
 - [eaa585d36791c5ddb7073f0c7332f9c06f238bba](https://github.com/magento/magento2/commit/eaa585d36791c5ddb7073f0c7332f9c06f238bba)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @amittiwari024. Thank you for your report. 
The issue has been fixed in magento/magento2#15736 by @vijay-wagento in 2.1-develop branch
Related commit(s):
 - [02453f67e75170f9ff7fe7c5725731a99320534f](https://github.com/magento/magento2/commit/02453f67e75170f9ff7fe7c5725731a99320534f)

The fix will be available with the upcoming 2.1.15 release.
