### ISSUE TITLE
Comments are not translated for Signifyd module.

### ISSUE THREAD

**Issue by yogeshsuhagiya** [magento/magento2#15361]
### Preconditions
1. PHP 7.0.30
2. Magento 2.2.x

### Steps to reproduce
1. Goto STORE > Configuration > [SALES](url) > Fraud Proratection
2. Add translations into `en_US.csv` for comments for under the input/select fields 
3. Flush cache and check comments 

### Expected result
1. All comments should be translated

### Actual result
1. Comments under input/select fields are not translated

**Comment by sidolov** [comment]
Hi @Yogeshks. Thank you for your report. 
The issue has been fixed in magento/magento2#15364 by @Yogeshks in 2.2-develop branch
Related commit(s):
 - [f295906c3c9951b19a5ed3aee66aabe0d9e05a92](https://github.com/magento/magento2/commit/f295906c3c9951b19a5ed3aee66aabe0d9e05a92)

The fix will be available with the upcoming 2.2.5 release.
