### ISSUE TITLE
Admin menu not showing of my custom module

### ISSUE THREAD

**Issue by Hiteshbb** [magento/magento2#1537]
Hi,

Custom module admin menu not showing. and database table not creating.

**Comment by mazhalai** [comment]
@Hiteshbb Thank you for reporting the issue, but could you please provide more details. Have you followed the steps provided [here](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/create_module.html)

**Comment by magento-engcom-team** [comment]
Hi @Hiteshbb. Thank you for your report. 
The issue has been fixed in magento/magento2#17424 by @phoenix128 in 2.3-develop branch
Related commit(s):
 - [f281a053938504331a277e83a7a1152dc5143636](https://github.com/magento/magento2/commit/f281a053938504331a277e83a7a1152dc5143636)
 - [a0379a4bb36486ac26aaabaff969923b01a665f0](https://github.com/magento/magento2/commit/a0379a4bb36486ac26aaabaff969923b01a665f0)
 - [368969a3ef4ffa0bce3941b133e5fd882f0bcaa7](https://github.com/magento/magento2/commit/368969a3ef4ffa0bce3941b133e5fd882f0bcaa7)
 - [1530c69c642797ae87c68292559422b1fede627e](https://github.com/magento/magento2/commit/1530c69c642797ae87c68292559422b1fede627e)
 - [3d0cb544198b74e1294ebc5bee1f995dcde101b1](https://github.com/magento/magento2/commit/3d0cb544198b74e1294ebc5bee1f995dcde101b1)
 - [2232338efacc5288dcc3c0dcaa6e00f204e93762](https://github.com/magento/magento2/commit/2232338efacc5288dcc3c0dcaa6e00f204e93762)
 - [e858f36eb99de3d78129cc1916c4c2b6d64caaca](https://github.com/magento/magento2/commit/e858f36eb99de3d78129cc1916c4c2b6d64caaca)
 - [13353c84e3476a2be67521028a1b1c63a9f79cd1](https://github.com/magento/magento2/commit/13353c84e3476a2be67521028a1b1c63a9f79cd1)
 - [25a5e5be1aac07521317ab891cfcb7eaf407fa37](https://github.com/magento/magento2/commit/25a5e5be1aac07521317ab891cfcb7eaf407fa37)
 - [229a29aff8bd66d5ad18090a7478608c7d0ab753](https://github.com/magento/magento2/commit/229a29aff8bd66d5ad18090a7478608c7d0ab753)

The fix will be available with the upcoming 2.3.1 release.
