### ISSUE TITLE
Multistore Full Page Cache Issue

### ISSUE THREAD

**Issue by ankurAuriga** [magento/magento2#15376]
If a Url is opened on a non-default store, same url do not returned from cache in different browser or even in Incognito mode.

### Preconditions
1. Magento 2.2.3
2. PHP 7.0
3. MySql 5.7
4. Redis for FPC

### Steps to reproduce
1. Created 2 different store, Store A, Store B (Default store)
2. Enabled full page cache with In-Built Mode.(Using Redis)
3. Open home page on Store A.
4. Open same home page on Store A in different browser or in incognito mode.

### Expected result
Home page on Store A, should be rendered from FPC in different browser as it was cached in other browser

### Actual result
Page do not return from FPC causing multiple keys in redis.

**Comment by ankurAuriga** [comment]
@magento-engcom-team  - Any update on this?

**Comment by TimQSO** [comment]
I think we have the same issue here. All pages are cached, but I get frequent misses while trying to open a cached page in different browser and / or incognito.

**Comment by ghost** [comment]
@ankurAuriga, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by medspec** [comment]
@magento-engcom-team  is there a workaround possible?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @ankurAuriga The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by JungleHi** [comment]
@engcom-backlog-nazar
@engcom-backlog-pb 
This issue still exists in the latest Magento releases, both 2.3 and 2.2.7.

Anyone can share a workaround? Need it badly.

**Comment by JungleHi** [comment]
@magento-engcom-team 
This issue is reproducible on 2.3.

I also checked the release notice, #15376 is not in the fixed issue list.

**Comment by ankurAuriga** [comment]
@engcom-backlog-nazar @magento-engcom-team -- This issue is still reproducible in Magento 2.3

**Comment by ghost** [comment]
@ankurAuriga i'm will recheck

**Comment by ankurAuriga** [comment]
@engcom-backlog-nazar - Did you validate this. In 2.3, now it is not working even for the default store.

**Comment by JungleHi** [comment]
@ankurAuriga Just tested. The issue is fixed in Magento 2.3.1
