### ISSUE TITLE
Can't make additiona street fields required in my account section

### ISSUE THREAD

**Issue by nadeefit6** [magento/magento2#15418]
Additional street fields in my account section cannot be made required because of following reason.
field name is not generating correctly and it is not unique.

### Preconditions
1.  Magento ver. 2.2.3
2.  Sample data installed

### Steps to reproduce

1./Magento_CustomerCustomAttributes/templates/customer/address/edit.phtml
2. add class required for <div class="field additional">
3. Save changes
4. Login 
5. Edit Address
6. Check the Additional address fields

### Expected result
1.  Additional Address fields are required

### Actual result
1. Additional address fileds are still not required.

**Comment by nadeefit6** [comment]
Can I pick this issue?

**Comment by hostep** [comment]
@nadeefit6: I think this is a duplicate of https://github.com/magento/magento2/issues/12202
Can you confirm? If yes, it might be best to close this and keep the discussion going in https://github.com/magento/magento2/issues/12202

And feel free to work on resolving this problem. Would be great if this could get solved, since we (and a bunch of other people) also run into this problem.

Thanks!

**Comment by nadeefit6** [comment]
yes its an duplicate of  #12202.
Will close the issue and continue in the  #12202
