### ISSUE TITLE
Payment method title from wrong store in invoice and order

### ISSUE THREAD

**Issue by etcik1** [magento/magento2#15420]
### Preconditions
1. Magento 2.2
2. Having two websites with two store views (e.g website1 with stores store1 and store2 and website2 with stores store3 and store4)
3. Payment method configured with different title for each store view.

### Steps to reproduce

1. Order products in store4
2. Use configured payment method
3. Open order in Admin

### Expected result
1. Payment method title should be store4-payment-titel

### Actual result

1. Payment method title is store1-payment-titel

Our websites use different currencies and stores are in different languages (so are payment method titles)

**Comment by rommelfreddy** [comment]
the issue is reproducable. (v2.2.4 - clean install).
but the more important issue is that when you update the order (create a invoice/credit/shipment, or simply change the status) the "instructions" of the method will be replaced with the configuration values of the DEFAULT STORE, on each save request on the product.

e.g:
**Paymentmethod configuration:**
StoreView UK:
- method title: Banktransfer
- instructions: Please transfer the money to the following bank account......
StoreView DE:
- method title: Banküberweisung
- instructions: Bitte überweisen Sie das Geld auf folgendes Bankkonto......

**Conditions:**
- StoreView UK is the default StoreView.
- The order is placed in StoreView DE

Go to the admin and create a invoice or something else which triggers the save action on the order entity.
After saving the entity in the payment information block the instructions will be the values of the StoreView UK, not StoreView DE.
The values of UK will be also saved to the database.

I have already found a solution for this issue. i will create a commit for it. (also for the display issue of @etcik1 )

**Comment by ghost** [comment]
@Fredwak, please create a separate issue.

**Comment by ghost** [comment]
@etcik1, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ketan-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vasilii-b** [comment]
Hi @magento-engcom-team, @ketan-krish.
I see there is no answer from @ketan-krish  for a while regarding a fix for the issue.

@magento-engcom-team I'm going to take it to provide the fix.
Thank you!

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vasilii-b** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b, here is your [Magento instance](https://i-15420-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-15420-2-2-develop.instances.magento-community.engineering/admin](https://i-15420-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vasilii-b** [comment]
Hi @magento-engcom-team,
I wasn't able to reproduce reported issue on `2.3-develop` neither on `2.2-develop`. Closing this one for now.
If someone have some more explanatory preconditions and steps to reproduce, please feel free to jump in.
Thank you!

**Comment by francescorm** [comment]
I have the same problem on  Magento versione 2.3.4. can you check or give us the solution?

**Comment by plastikschnitzer** [comment]
I can confirm the issue still exists in Magento 2.3.5-p1.

Any solution?

**Comment by Vale18** [comment]
Hello,
is there any solution yet? I searched for the problem for a whole day and didn't find anything helpful yet.
