### ISSUE TITLE
Bundle Products price range is showing expired special price from bundle options

### ISSUE THREAD

**Issue by harleen-mann** [magento/magento2#15457]
### Preconditions
1. 2.2.1
2. bundle product showing expired special price

### Steps to reproduce
1. edit bundle option and set special price dates:
![screen shot 2018-05-23 at 11 06 19](https://user-images.githubusercontent.com/25430163/40418099-5a2edf9e-5e79-11e8-9003-0982a294f056.png)
2. reindex and clear cache
3. view product

### Expected result
1. no special price should be shown for bundle product price range.

### Actual result
1. It is showing special price , when the special price for simple product has already been expired.
but the price in customization and summary box is right:

![screen shot 2018-05-23 at 11 08 18](https://user-images.githubusercontent.com/25430163/40418210-9ef1e16c-5e79-11e8-9f63-91e4e97e81ba.png)

**Comment by magento-engcom-team** [comment]
Hi @harleen-mann. Thank you for your report. 
The issue has been fixed in magento/magento2#15768 by @sanjay-wagento in 2.3-develop branch
Related commit(s):
 - [e13f1f0771998031adbc1e4c3d03f36dfb5984d5](https://github.com/magento/magento2/commit/e13f1f0771998031adbc1e4c3d03f36dfb5984d5)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @harleen-mann. Thank you for your report. 
The issue has been fixed in magento/magento2#15535 by @phoenix128 in 2.2-develop branch
Related commit(s):
 - [ca6e479731182a28509082685af7849e78400781](https://github.com/magento/magento2/commit/ca6e479731182a28509082685af7849e78400781)

The fix will be available with the upcoming 2.2.7 release.
