### ISSUE TITLE
Cart does not load when Configuration product option is deleted and that option is in the cart

### ISSUE THREAD

**Issue by jonshipman** [magento/magento2#15467]
The issue is that $this->getChildProduct() is null when trying to access getThumbnail().

Affected classes/methods:
Magento\ConfigurableProduct\CustomerData\ConfigurableItem::getProductForThumbnail()
Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable::getProductForThumbnail()

**Comment by magento-engcom-team** [comment]
Hi @jonshipman. Thank you for your report. 
The issue has been fixed in magento/magento2#15468 by @jonshipman in 2.2-develop branch
Related commit(s):
 - [1e364956495b6fbd30ddcdeebcae3208fef52de9](https://github.com/magento/magento2/commit/1e364956495b6fbd30ddcdeebcae3208fef52de9)
 - [caa818ec68e7cf4f9e95ed2851bd20a654f29c12](https://github.com/magento/magento2/commit/caa818ec68e7cf4f9e95ed2851bd20a654f29c12)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @jonshipman. Thank you for your report. 
The issue has been fixed in magento/magento2#16812 by @mage2pratik in 2.1-develop branch
Related commit(s):
 - [d6e8ce940235903b2296c5fbb7ee70c39b57e544](https://github.com/magento/magento2/commit/d6e8ce940235903b2296c5fbb7ee70c39b57e544)
 - [66dc4d8b9a053b6746cd0920266c087751b145f5](https://github.com/magento/magento2/commit/66dc4d8b9a053b6746cd0920266c087751b145f5)

The fix will be available with the upcoming 2.1.15 release.
