### ISSUE TITLE
Order confirmation sending takes a long time - Magento 2.2.4

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#15476]
After magento 2.2.4 updates, order confirmation sending takes a long time when customer use email service outlook.com and hotmail.com, sometimes it don't send Order confirmation message. I tested use this but it doesn't work -> Store > Configration > Sales > Sales Emails > General Settings > Asynchronous sending > Enable. Also tested send manually order confirmation -> Sales > Order > Send Email

### Preconditions

1. Magento 2.2.4
2. Mysql 5.6.30

### Steps to reproduce

1. Customer order complete
2. Order confirmation email message

### Expected result

1.  It send order confirmation email message automatically after order is complete.

### Actual result

1.  Order confirmation sending takes a long time. Sometimes it don't send order confirmation message.

**Comment by gwharton** [comment]
If you want emails to go out straight away, make sure you set Store > Configration > Sales > Sales Emails > General Settings > Asynchronous sending to OFF.

Asynchronous sending queues up outbound emails and fires them off at a later time using cron. Non asynchronous sending fires them off straight away.

Is this the issue?

You could also be running into the #14952 issue, because alot of people are reporting that since 2.2.4, the emails do not have any from address set. Perhaps outlook and hotmail are ditching the emails due to an incorrectly formatted from address?

**Comment by Userr017** [comment]
Issue is: After magento 2.2.4 updates, order confirmation sending takes a long time when customer use email service outlook.com and hotmail.com, sometimes it don't send Order confirmation message...?

**Comment by ghost** [comment]
@Userr017, thank you for your report. When "Asynchronous sending" is enabled, Sales emails are sent at predetermined, regular intervals.
Please see [Magento Documentation](https://docs.magento.com/m2/ce/user_guide/configuration/sales/sales-emails.html)
