### ISSUE TITLE
M2.2.4 missing meta title tag and doesn't show product name if meta title is empty

### ISSUE THREAD

**Issue by hirale** [magento/magento2#15501]
### Preconditions

1. Magento 2.2.4
2. PHP 7.1

### Steps to reproduce

1. fresh install via composer
2. install sample data

### Expected result

1. should show product name as brower title and should have meta title tag in html source

### Actual result

1. [Screenshot, logs]
![snipaste20180524_181222](https://user-images.githubusercontent.com/22028058/40498232-bf049cf0-5f7e-11e8-8990-c9ed032e1b4f.png)
![snipaste20180524_181212](https://user-images.githubusercontent.com/22028058/40498240-c12b5c8a-5f7e-11e8-8631-43de4efd1d77.png)
![snipaste20180524_175409](https://user-images.githubusercontent.com/22028058/40497242-0924aec2-5f7c-11e8-9ee1-42400bd21842.png)

1. If only exist Product name, in frontend will display nothing.
2. If meta title exists, in frontend <title> tag will get value of it. but missing <meta name="meta_title"> tag.

**Comment by akosglue** [comment]
@Naturegreen have you got a fix for it?

**Comment by ghost** [comment]
Hi Guys, same issue here, do you have an update on this? thanks!

**Comment by ghost** [comment]
Hey guys, it's possible to apply an override of this? I saw that there're multiple protected and private methods and that's not usual when we made overrides, plugins cannot be used for this purpose (only public methods can be modified with Magento 2 plugins) can anyone share an alternative method to apply this until a new Magento version comes out?

thanks.

**Comment by xuanserfe** [comment]
Hi There,
I've applied the fix proposed in the commit #15532 and is not working with the following configuration:
`dev/front_end_developmennt_workflow/type -> client_side_compilation`
I don't have a fix for this by now, but please review this.
Regards

**Comment by sidolov** [comment]
Hi @Naturegreen. Thank you for your report. 
The issue has been fixed in magento/magento2#15532 by @phoenix128 in 2.2-develop branch
Related commit(s):
 - [0a38b845508577e38d79280288a4fc716f2d1108](https://github.com/magento/magento2/commit/0a38b845508577e38d79280288a4fc716f2d1108)
 - [85ac3be16708f9b7084481e522d29320e4a315e3](https://github.com/magento/magento2/commit/85ac3be16708f9b7084481e522d29320e4a315e3)
 - [432cf007f79937437620f18ace00010b1a61a4ef](https://github.com/magento/magento2/commit/432cf007f79937437620f18ace00010b1a61a4ef)
 - [1413d65946c2e3e076a0605d2e5c739e0b339d83](https://github.com/magento/magento2/commit/1413d65946c2e3e076a0605d2e5c739e0b339d83)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @Naturegreen. Thank you for your report. 
The issue has been fixed in magento/magento2#17771 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [fba597ed6cd8031855844da6b3faa1f311d1341f](https://github.com/magento/magento2/commit/fba597ed6cd8031855844da6b3faa1f311d1341f)
 - [79b0b41780a8b8562302b97a23bcfea24f25ff9b](https://github.com/magento/magento2/commit/79b0b41780a8b8562302b97a23bcfea24f25ff9b)
 - [795c18e6744ab252c038a67f59aa46d8704554a5](https://github.com/magento/magento2/commit/795c18e6744ab252c038a67f59aa46d8704554a5)

The fix will be available with the upcoming 2.3.0 release.
