### ISSUE TITLE
First PDF download / export after login

### ISSUE THREAD

**Issue by magento2dev** [magento/magento2#15510]
### Preconditions

1. Magento 2.2.3

### Steps to reproduce

1. Log in with an admin user who does not have the permissions Other Settings -> Notifications -> *
2. Right after login try to download any PDF or export data

### Expected result

1. Download of generated file

### Actual result

1. Redirect to Admin Dashboard

If you are trying a second time to download PDF or export it will work. The issue is based on isFirstPageAfterLogin(), when user does not have the Notifications permission, it's never set to false.

**Comment by VladimirZaets** [comment]
Hi @anthony-jullien. Thank you for your report. 
The issue has been fixed in magento/magento2#15539 by @phoenix128 in 2.2-develop branch
Related commit(s):
 - [59e03c1a3d91f8f6c5c81ead729f1ae2e102224d](https://github.com/magento/magento2/commit/59e03c1a3d91f8f6c5c81ead729f1ae2e102224d)

The fix will be available with the upcoming 2.2.6 release.

**Comment by VladimirZaets** [comment]
Hi @anthony-jullien. Thank you for your report. 
The issue has been fixed in magento/magento2#15767 by @sanjay-wagento in 2.1-develop branch
Related commit(s):
 - [8e43c07da042bff3a60a03205711b67500b25fdc](https://github.com/magento/magento2/commit/8e43c07da042bff3a60a03205711b67500b25fdc)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @anthony-jullien. Thank you for your report. 
The issue has been fixed in magento/magento2#15766 by @sanjay-wagento in 2.3-develop branch
Related commit(s):
 - [d58ab5fc8d290e162daadf4006b958b0f1de972f](https://github.com/magento/magento2/commit/d58ab5fc8d290e162daadf4006b958b0f1de972f)

The fix will be available with the upcoming 2.3.0 release.
