### ISSUE TITLE
Magento 2.2.4 not install on php7.2.1

### ISSUE THREAD

**Issue by gzchauhan** [magento/magento2#15528]
### Preconditions

1. Magento 2.2.4 not support on php7.2.1

### Steps to reproduce

1. MAMP php7.2.1 and try to install new magento 2.2.4
2. ![screen shot 2018-05-26 at 10 16 35 am](https://user-images.githubusercontent.com/1052373/40572610-009f0bdc-60ce-11e8-9d0a-7c70a012b266.png)

### Expected result

1. It should support php7.2.1

### Actual result

1. ![screen shot 2018-05-26 at 10 16 35 am](https://user-images.githubusercontent.com/1052373/40572612-0f3b3e40-60ce-11e8-8c01-c279d2860345.png)

**Comment by vkublytskyi** [comment]
Magento 2.2.4 does not support PHP 7.2 and it's hardly possible that it support will be added in Magento 2.2.x release line because it requires too big changes in a code and massive update of third party libraries that will make update process very complicated. We are trying to keep upgrades between patch versions simple and safe to enable possibility easily upgrade to the actual version.

The first Magento version with PHP 7.2 support will be 2.3.0. For Magento 2.2 recommended PHP version is 7.1.
