### ISSUE TITLE
Products shown as 'out of stock' after upgrading from 2.1.9 to 2.2.4

### ISSUE THREAD

**Issue by middlegrey** [magento/magento2#15557]
### Preconditions
1. Magento 2.1.9
2. Using multiple websites, stores and languages
3. Apache 2.4.33 with PHP 7.0.30 and MySQL 5.7.22

### Steps to reproduce
1. Import Bundle Product.

### Expected result
1. Bundle Product visible on frontend.

### Actual result
1. Bundle Product absent on frontend - catalog_product_relation table data not filled.

**Comment by magento-engcom-team** [comment]
Hi @middlegrey Thank you for reporting
Unfortunately this description is not complete. Please provide more information so the issue is reproducible.

Thanks

**Comment by middlegrey** [comment]
What additional information would you like?

**Comment by magento-engcom-team** [comment]
@middlegrey It's unclear from the report what kind of products are those, how were they created, which are show and which are not, etc.

To acknowledge the issue on our side we first have to make sure it's reproducible.

**Comment by middlegrey** [comment]
We're using bundle products with customizable options that were created by importing a CSV.

So far I haven't been able to discover why some items are shown as in stock and others are not.

**Comment by middlegrey** [comment]
The issue relates to https://github.com/magento/magento2/issues/12330

The following temporary solution suggested by @domeglic seems to fix the problem

- INSERT IGNORE INTO catalog_product_relation SELECT parent_product_id,product_id FROM catalog_product_bundle_selection
- Reindex stock and price indexes

**Comment by ghost** [comment]
@middlegrey, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @middlegrey The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by middlegrey** [comment]
Thank you!
