### ISSUE TITLE
Getting wrong frontend-controller, when using storecodes in urls

### ISSUE THREAD

**Issue by EliasKotlyar** [magento/magento2#15565]
### Preconditions
1. PHP 7.0
2. Magento 2.2.4

### Steps to reproduce
1. Create a Store with 2 StoreViews like "de" and "en". "de" is the default storeview
2. Set 'Stores' > 'Configuration' > 'General' > 'Web' > 'Add Store Code to Urls' to 'Yes'
3. Set "web/default/front" from Store "en" to somehing different like "catalog/product/view/id/productid"
4. Go to "domain.com/en"

### Expected result
I will see the product page

### Actual result
I see the default CMS-Page

### More information
Not reproducable in 2.2.2,  2.2.3
Reproducable on 2.2.4.

**Comment by magento-engcom-team** [comment]
Hi @EliasKotlyar. Thank you for your report. 
The issue has been fixed in magento/magento2#15566 by @EliasKotlyar in 2.2-develop branch
Related commit(s):
 - [1cbb265dbe72c2b86aaf185494b9fbda86eba8a9](https://github.com/magento/magento2/commit/1cbb265dbe72c2b86aaf185494b9fbda86eba8a9)
 - [4d886b2d2418712a4d9e463c5463a82943b79953](https://github.com/magento/magento2/commit/4d886b2d2418712a4d9e463c5463a82943b79953)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @EliasKotlyar. Thank you for your report. 
The issue has been fixed in magento/magento2#15759 by @vgelani in 2.3-develop branch
Related commit(s):
 - [61856f5e6d5ed69c810183c95ad15b571f308a4d](https://github.com/magento/magento2/commit/61856f5e6d5ed69c810183c95ad15b571f308a4d)
 - [4c77dff976361e70fc190c40b1fa5515cd136ce2](https://github.com/magento/magento2/commit/4c77dff976361e70fc190c40b1fa5515cd136ce2)

The fix will be available with the upcoming 2.3.0 release.
