### ISSUE TITLE
Products order in Categories are same for all stores.

### ISSUE THREAD

**Issue by etcik1** [magento/magento2#15568]
### Preconditions
1. Magento 2.2 **Updated(09/25/2019):** Still actual on `2.3-develop`
2. Having two websites with two store views (e.g website1 with stores store1 and store2 and website2 with stores store3 and store4)
3. Different websites use same categories.

### Steps to reproduce

1. In Admin go to Catalog -> Categories
2. Choose some category
3. Change storefront from default to some specific one
4. Expand tab Products in category
5. Reshuffle products
6. Save category

### Expected result
1. Changes are saved for selected storefront (or at least store)

### Actual result

1. Changes are saved for all storefronts (all stores)

**Comment by ghost** [comment]
@etcik1, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by vivekkumarcedcoss** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vivekkumarcedcoss. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vivekkumarcedcoss, here is your [Magento instance](https://i-15568-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-15568-2-2-develop.instances.magento-community.engineering/admin](https://i-15568-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by serbynskyi** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hi @etcik1,

Thanks for your reporting and collaboration.

Verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="988" alt="Screenshot 2024-05-13 at 12 28 01" src="https://github.com/magento/magento2/assets/51680745/10cbe57d-3bd5-4bfb-82a8-61c20ffbbf58">


<img width="1121" alt="Screenshot 2024-05-13 at 12 28 13" src="https://github.com/magento/magento2/assets/51680745/051544e8-4542-4053-a1cc-ca7f9978faa1">


Hence we are closing this issue.

Thanks
