### ISSUE TITLE
[2.2.4] Gallery product image variable changes have no effect or changes crashes the layout

### ISSUE THREAD

**Issue by densen45** [magento/magento2#15571]
### Preconditions

1. Ubuntu 17.10
2. PHP 7.1
3. Magento 2.2.4

### Steps to reproduce

1. Create a product with one or more images
2. Create custom theme and open etc/view.xml (or open file from blank or luma themes -- doesn't matter)
3. Change the size of the product image (set width and height for product_page_image_medium, product_page_main_image and product_page_main_image_default e.g. to 350; default is 700 in blank theme and 700*560 in luma theme)
4. Apply the fix related to #15009, 8ef039ec281a7fc6af014b42fc69a9d77e4bf277 (otherwise the gallery and the entire JavaScript crashes)
5. Go to the products view page on frontend
6. Wait for the gallery

### Expected result (as it was in Magento 2.2.3)

1. The size of the image is 350*350
2. The height of the fotorama__stage is 350px + a padding

### Actual result (as it is in Magento 2.2.4)

1. The size of the image is still 700*700 resp. 700*560
2. The height of the fotorama__stage doesn't changed either

### Further steps to reproduce
1. Change width and height of product_page_image_medium_no_frame

### Further actual results
1. The size of the image changed
2. The size of the fotorama__stage still isn't changed (the result is a lot of white space)

### Further notes
* This issue is probably related to #15009.

**Comment by engcom-backlog-nickolas** [comment]
Hello @densen45, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @densen45 The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by leoquijano** [comment]
Hi @magento-engcom-team and @engcom-backlog-nazar, do you have the specific commits that were used to fix this in 2.3? 

2.3 is a big release and we're monitoring some issues so we can have a backport to 2.2. Having explicit commits allows us to implement the change ourselves for LTS projects.

If there are commits in 2.2 those would also be useful.
