### ISSUE TITLE
Order payment method is not updated for free payment method while placing order from Admin Panel

### ISSUE THREAD

**Issue by oleksii-lisovyi** [magento/magento2#15579]
### Preconditions

1. Magento 2.2.3.
2. Enabled Check Money (or some other) payment method for test.

### Steps to reproduce

1. Go to Admin Panel -> Sales -> Orders.
2. Click on "Create New Order" button.
3. Do all the necessary steps to go on the Order Create page.
4. Add some product.
5. Click on "Custom Price" checkbox near the product.
6. Change custom price on 0.
7. Click on "Update Items and Quantities" button.
8. Open Developer Tools -> Console.
9. Tap `order.paymentMethod`.

### Expected result

1. "free" payment method is returned.

### Actual result

1. "checkmo" payment method is returned.

This issue making impossible using of `order` object to check current order payment method is such case. This information is useful while developing custom payment method(s).

I found, that method `AdminOrder.setPaymentMethod()` (file magento2/vendor/magento/module-sales/view/adminhtml/web/order/create/scripts.js) is updating order payment method only in case if there is a payment form for a method:
`if ($('payment_form_'+method)){`
`// ... do something`
`this.paymentMethod = method;`
`// ... do something else`
`}`
but there is no such form for the payment method "free", so this condition is never passed for the payment method.

Would be great to get some workaround.
Thanks in advance.

**Comment by oleksii-lisovyi** [comment]
Hi guys. Any updates on it?

**Comment by ghost** [comment]
Hi @oleksii-lisovyi i have no payment method after update items, can you provide more information about this ?

**Comment by oleksii-lisovyi** [comment]
@engcom-backlog-nazar, in order to get No Payment Information required label you need to use "Custom Price" check mark with 0 value:
![image](https://user-images.githubusercontent.com/3918875/42520077-1405231e-846e-11e8-93fe-428170794228.png)
 and some free shipment method to have grand total = 0.

**Comment by ghost** [comment]
@oleksii-lisovyi  ok im reproduced it on 2.2-develop branch

**Comment by ghost** [comment]
@oleksii-lisovyi  this issue has already been fixed on 2.3-develop branch
thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @oleksii-lisovyi The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
