### ISSUE TITLE
Images in XML sitemap are always linked to base store in multistore

### ISSUE THREAD

**Issue by dvershinin** [magento/magento2#15588]
### Preconditions

1.  Magento 2.2.3
2. PHP 7.0.30
3. MySQL: 5.6.37-82.2 Percona Server

### Steps to reproduce

1.  Have a multistore Magento setup
2. Configure each store to use their own domain 
3. Generate Magento XML sitemap

### Expected result

1. All images should be linked to corresponding store domain

### Actual result

1. All pages are linked to proper store but all *images* linked to `base` store

![screenshot 2018-05-29 23 44 54](https://user-images.githubusercontent.com/250071/40684635-875c715e-639a-11e8-8499-273b9a62c8ef.png)

**Comment by VladimirZaets** [comment]
Hi @dvershinin. Thank you for your report. 
The issue has been fixed in magento/magento2#15689 by @StevenGuapaBV in 2.2-develop branch
Related commit(s):
 - [7b8fe3d68a946c62fd55af525b44f1ef9256ab16](https://github.com/magento/magento2/commit/7b8fe3d68a946c62fd55af525b44f1ef9256ab16)
 - [498047cb31c5e34955e49aa684a7e910c4e7d941](https://github.com/magento/magento2/commit/498047cb31c5e34955e49aa684a7e910c4e7d941)
 - [63ed86492f2bdf5b2410836a71724106f9d137f0](https://github.com/magento/magento2/commit/63ed86492f2bdf5b2410836a71724106f9d137f0)
 - [83ad777b941eff746883a25ad674f97609b5e9c6](https://github.com/magento/magento2/commit/83ad777b941eff746883a25ad674f97609b5e9c6)
 - [6a490a8af822080cca3f35db15ae9ec9f5365205](https://github.com/magento/magento2/commit/6a490a8af822080cca3f35db15ae9ec9f5365205)
 - [f1dd4e838e7eaa12e5b06c78e1ed465a326b05ed](https://github.com/magento/magento2/commit/f1dd4e838e7eaa12e5b06c78e1ed465a326b05ed)
 - [b7f8d28c83c82268f56b6ccff3082cc9b54d1310](https://github.com/magento/magento2/commit/b7f8d28c83c82268f56b6ccff3082cc9b54d1310)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @dvershinin. Thank you for your report. 
The issue has been fixed in magento/magento2#16813 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [04d4bb07328e4b145d80e0c008cbd131a1ed300f](https://github.com/magento/magento2/commit/04d4bb07328e4b145d80e0c008cbd131a1ed300f)
 - [d845518d5a2cb0053b62420e975921ab66ac09ae](https://github.com/magento/magento2/commit/d845518d5a2cb0053b62420e975921ab66ac09ae)
 - [547f6fde3bb7243af64052ba4611013dcbb75084](https://github.com/magento/magento2/commit/547f6fde3bb7243af64052ba4611013dcbb75084)
 - [f422401e6d55633dd90af9a52be4c841330daeb2](https://github.com/magento/magento2/commit/f422401e6d55633dd90af9a52be4c841330daeb2)
 - [e11be0019d836d3b465a6c4583334a7353997c5f](https://github.com/magento/magento2/commit/e11be0019d836d3b465a6c4583334a7353997c5f)
 - [25010d4e159579641f13d326b795cf6bc88e8897](https://github.com/magento/magento2/commit/25010d4e159579641f13d326b795cf6bc88e8897)
 - [65ccd39057ff1ebcc7d697ca0723b206e3e108c1](https://github.com/magento/magento2/commit/65ccd39057ff1ebcc7d697ca0723b206e3e108c1)

The fix will be available with the upcoming 2.3.0 release.
