### ISSUE TITLE
Typo in tests / setCateroryIds([])

### ISSUE THREAD

**Issue by kmddevdani** [magento/magento2#15590]
Good morning,

I am not sure if this is an issue. Browsing through the source code, we found occurences of the word "Caterory" in tests, which seemed as if it would be a typo. Please have a look - and just close it, if we are wrong. ;) Thank you!!!

 

### Preconditions

1. Access to github magento/magento2 repository

### Steps to reproduce

1. Browse to https://github.com/magento/magento2/search?q=setcateroryids&unscoped_q=setcateroryids

### Expected result

1. I would expect to see no function calls for "setCateroryIds"

### Actual result

1. I see several occurrences of "setCateroryIds":
<img width="1017" alt="screen shot 2018-05-30 at 2 13 39 pm" src="https://user-images.githubusercontent.com/25165183/40695095-b6408144-6413-11e8-921f-185d15b048c0.png">

**Comment by magento-engcom-team** [comment]
Hi @kmddevdani. Thank you for your report. 
The issue has been fixed in magento/magento2#15621 by @neeta-wagento in 2.2-develop branch
Related commit(s):
 - [1d47b28cbaf42b7cc024ad4c04b32080e61fe0e1](https://github.com/magento/magento2/commit/1d47b28cbaf42b7cc024ad4c04b32080e61fe0e1)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @kmddevdani. Thank you for your report. 
The issue has been fixed in magento/magento2#15814 by @viral-wagento in 2.1-develop branch
Related commit(s):
 - [ea51428e6aa13b5216621f1a66ac7c498b4966f6](https://github.com/magento/magento2/commit/ea51428e6aa13b5216621f1a66ac7c498b4966f6)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @kmddevdani. Thank you for your report. 
The issue has been fixed in magento/magento2#16926 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [77c5e85e329bd5e80270436c1335809e00808114](https://github.com/magento/magento2/commit/77c5e85e329bd5e80270436c1335809e00808114)

The fix will be available with the upcoming 2.3.0 release.
