### ISSUE TITLE
customer name shouldn't display after rebooting the system

### ISSUE THREAD

**Issue by deva96** [magento/magento2#15596]
### Preconditions

1. Welcome message shouldn't contain user name after restarting the system
2. Even after closing the tab without logging out before restarting the sysem

### Steps to reproduce

1. login as a user
2. close the tab without logged out
3. restart the system
4. open brower and open magento local
5. see the welcome message

### Expected result

1. Welcome! - Sign In - Create an account

### Actual result

1.  Welcome!User name! - Sign in - Create an account

**Comment by AirmanAJK** [comment]
This is happening because that information is stored in local storage in the browser, and clearing/invalidating server sessions won't actually give the client any signal to "flush" local storage.

Especially since Magento's local storage refreshing works based on post requests to different "sections". Any solution would have to somehow detect an invalidated session, and then only clear out the necessary parts of local storage (since even guests have info in local storage like directory-data).

**Comment by ghost** [comment]
@deva96, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by krisdante** [comment]
I do not consider this as a bug. It is rather functioning as desired. 
After restarting your system you still log in to the same account of Yours. So the browser local settings are yours. If you want to wipe out everything about you on browser/system restart - then enable such option in the browser (clear storage and history on exit)  

There is no single documentation nor spec where it says that it "shouldn't", so I interpret this issue as subjective opinion. 

IMO this issue shall be closed.
