### ISSUE TITLE
Styling <select> by changing less variables in Luma theme doesn't work as expected

### ISSUE THREAD

**Issue by denistrator** [magento/magento2#15608]
### Preconditions
1. FE theme inherited from Luma

### Steps to reproduce
1. In Custom/theme/web/css/source/_theme.less set less variables:
@select__background: rgba(255, 255, 255, 0.15);
@select__border: 2px dashed blue;
@select__height: 50px;
@select__padding: 15px 40px 15px 15px;
@select__background-clip: border-box;
2. Compile less

### Expected result
Have "select" elements with the styles you set in _theme.less

### Actual result
"select" elements have different styles

### What causes the issue
[web/css/source/_forms.less](https://github.com/magento/magento2/blob/2.2/app/design/frontend/Magento/luma/web/css/source/_forms.less#L91) overrides some "select" styles defined with "@select__" variables
![screenshot_287](https://user-images.githubusercontent.com/21016905/40738320-ef9e2a6c-644b-11e8-95d0-a397a475b89b.png)

### Solution
Remove styles for background, border, height, padding-right from [web/css/source/_forms.less](https://github.com/magento/magento2/blob/2.2/app/design/frontend/Magento/luma/web/css/source/_forms.less#L91) and set these styles in _theme.less

**Comment by hitesh-wagento** [comment]
I am working on this

**Comment by DanielRuf** [comment]
Shouldn't be this in _extend.less?

**Comment by hitesh-wagento** [comment]
@DanielRuf No it's not working in **_extend.less**. We should move change from **web/css/source/_forms.less** to **web/css/source/_theme.less**

![image](https://user-images.githubusercontent.com/23443991/40898495-6724cf8c-67df-11e8-9eb7-85c840b62913.png)

**Comment by sidolov** [comment]
Hi @denistrator. Thank you for your report. 
The issue has been fixed in magento/magento2#15794 by @hitesh-wagento in 2.3-develop branch
Related commit(s):
 - [9fa64255f77609f8b845f3d0b9f503e19a3a6828](https://github.com/magento/magento2/commit/9fa64255f77609f8b845f3d0b9f503e19a3a6828)

The fix will be available with the upcoming 2.3.0 release.

**Comment by denistrator** [comment]
Hi @sidolov. Can you also have a look at #14999, please? It's a very small issue I opened (it has a PR #15000)

**Comment by VladimirZaets** [comment]
Hi @denistrator. Thank you for your report. 
The issue has been fixed in magento/magento2#15734 by @hitesh-wagento in 2.2-develop branch
Related commit(s):
 - [67778cdfc12fd10bdaf299b20ae858c28dc43d0d](https://github.com/magento/magento2/commit/67778cdfc12fd10bdaf299b20ae858c28dc43d0d)

The fix will be available with the upcoming 2.2.6 release.

**Comment by VladimirZaets** [comment]
Hi @denistrator. Thank you for your report. 
The issue has been fixed in magento/magento2#15796 by @hitesh-wagento in 2.1-develop branch
Related commit(s):
 - [d3184acb44f6622481fa18581f62b31fb5115b68](https://github.com/magento/magento2/commit/d3184acb44f6622481fa18581f62b31fb5115b68)

The fix will be available with the upcoming 2.1.15 release.
