### ISSUE TITLE
Known Issues for Magento 2.2.4 

### ISSUE THREAD

**Issue by jfrontain** [magento/magento2#15603]
This issue collects post-release Known Issues for Open Source and Commerce 2.2.4. We will close this issue after thoroughly investigating and documenting these issues. 

@hostep, this issue tracks the two issues you identified in Slack: https://github.com/magento/magento2/issues/15245  https://github.com/magento/magento2/issues/15205
 
Issue 1: (We don't recommend upgrading to Magento 2.2.4 if you use multiple websites on your store. 
Short explanation: if you have multiple websites, the configuration values set to the non-default website are getting ignored and are taken from the default website
So in my opinion, this will cause a lot of Magento shops to not function properly anymore if they use multiple websites and upgrade to 2.2.4.)
 
 
Issue 2: 2.2.4: Wrong home page loaded in multi store setup  · Issue #15245 · magento/magento2
Preconditions Magento 2.2.4 Stores > Configuration > General > Web > Url Options > Add Store Code to Urls: Yes Add two websites with each a store view, for example: a. An internatio...
GitHub
Upgraded to Magento 2.2.4 from Magento 2.1.9 - Locale and Store Configuration issues 'Store View' Locale not being used on frontend, 'Default Config' Locale being used instead   · Issue #15205 · magento/magento2
Magento multi-store installations aren&#39;t using the store view specific values from the Store Configuration if they have been set to be different to the global &#39;Default Configuration&#39;. P...

**Comment by hostep** [comment]
So next to the two mentioned above, here are some other new bugs introduced in 2.2.4 which I've seen popup in the past few weeks:

Magento issues:
- Wrong from sender in outgoing transaction emails: https://github.com/magento/magento2/issues/14952
- Can't change storeview design configuration: https://github.com/magento/magento2/issues/14968 (already fixed and scheduled for 2.2.5)
- Module Manager not working: https://github.com/magento/magento2/issues/15192 (already fixed and scheduled for 2.2.5)
- Shopping Cart Price Rule with condition on categories can crash the browser: https://github.com/magento/magento2/issues/15121 (already fixed and scheduled for 2.2.5)

Some issues introduced by those Amazon modules bundled by default now in Magento 2.2.4:
- Adding products to shopping cart sometimes adds more products then you expect: https://github.com/magento/magento2/issues/15052
- All 'Back' buttons in admin are now labeled incorrectly: https://github.com/magento/magento2/issues/15024 (isn't really Amazon's fault, but it triggered a translation bug in Magento)

An issue introduced by the Vertex module bundled by default now in Magento 2.2.4:
- People searching for the configuration section 'Tax Classes' no longer are able to find it, because that Vertex module renames it to 'Vertex Tax Classes' which is really bad, since those fields are from Magento and not from Vertex, so this is creating confusion: https://github.com/magento/magento2/issues/15463

An issue introduced by the Klarna module bundled by default now in Magento 2.2.4:
- When minifying javascript is enabled, it will break the tinymce editor in the admin, wasn't reported in a new issue, but at the end of an old one, but it is definitely a new bug: https://github.com/magento/magento2/issues/11577#issuecomment-391313584


If other people have more bugs they have verified which were introduced in Magento 2.2.4 and are sure they aren't caused by customizations, feel free to link to them over here as well.

**Comment by jfrontain** [comment]
We've added the following Known Issue description to the 2.2.4 Open Source and Commerce release notes. Code fix is in process. Thanks. Closing this issue. 

"Customers have reported the following behavior after upgrading to Magento 2.2.4 in deployments that span multiple websites:

Magento multi-store installations do not use the store view-specific values from the store configuration settings if these settings have different values than the global default configuration settings. Instead, Magento uses the default configuration for all store views. GitHub-15205, GitHub-15245

We do not recommend upgrading to Magento 2.2.4 if you deploy across multiple websites. Note that this problem is not triggered if you have only a single website with multiple stores or store views. "

**Comment by robolmos** [comment]
> Wrong from sender in outgoing transaction emails: #14952

Why wasn't that line included in the 2.2.4 known issues update?

Also, I don't see a "Known Issues for Magento 2.2.5" collector, and AFAICT the release notes don't mention a fix or that it's still a known/open issue.

Thanks
