### ISSUE TITLE
Product order in category changed after update to Magento 2.2.4

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#15627]
### Preconditions
1. Magento 2.2.4
2. PHP 7.1
3. This issue is introduced by the following PR: #11429

### Steps to reproduce
1. Have a category in Magento with several products in it, all have the position in the category set to the value 0 
2. The default sort order should be set to position
3. In Magento 2.2.3 the newest product in the database (the one with the highest entity_id) was shown first. With Magento 2.2.4 this behaviour changed. The oldest product is shown first, the newest last.

### Expected result
1. Product sort order should be the same between Magento 2.2.3 and Magento 2.2.4. This change is not documented, so can be qualified as a bug, because it was not the intended behaviour.
2. Newest product should be shown first, oldest last.  

### Actual result
1. Product sort order changed. The oldest product is shown first, the newest last. 

### Cause

In PR #11429 the following code was added: 
`->addAttributeToSort('entity_id', $this->getCurrentDirection());`

The Order by for the SQL query for retrieving the products has changed from: 
```
ORDER BY `cat_index_position` ASC, `cat_index`.`position` ASC, `e`.`entity_id` DESC
```
To
```
ORDER BY `cat_index_position` asc, `cat_index`.`position` asc, `e`.`entity_id` asc, `e`.`entity_id` DESC, `cat_index_position` asc, `cat_index`.`position` asc, `e`.`entity_id` asc
```
So as can be seen a `e`.`entity_id` asc is inserted in the order by before the default `e`.`entity_id` DESC is in the order by clause changing this behaviour.

**Comment by sidolov** [comment]
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#15629 by @dverkade in 2.2-develop branch
Related commit(s):
 - [8981225996e92af97671c67727be35af42591e94](https://github.com/magento/magento2/commit/8981225996e92af97671c67727be35af42591e94)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#16343 by @dverkade in 2.3-develop branch
Related commit(s):
 - [7d2636538ecdcc314312689062f799103d86e22a](https://github.com/magento/magento2/commit/7d2636538ecdcc314312689062f799103d86e22a)

The fix will be available with the upcoming 2.3.0 release.

**Comment by engcom-Alfa** [comment]
@magento give me 2.2.3 instance

**Comment by engcom-Alfa** [comment]
@magento give me 2.2.3 instance
