### ISSUE TITLE
REST API create order POST /V1/orders

### ISSUE THREAD

**Issue by bibiseb** [magento/magento2#15652]
### Preconditions

1. Magento 2.2.4
2. PHP 7.0.18

### Steps to reproduce

POST http://magento2.test/index.php/rest/V1/orders

`{
	"entity": {
		"base_grand_total" : 100,
		"customer_email" : "user@domain.tld",
		"grand_total" : 100,
		"items" : [
			{
				"sku" : "TESTSEB"
			}
		]
	}
}`

### Expected result

An order should have been created

### Actual result

I received this json:

`{
    "messages": {
        "error": [
            {
                "code": 500,
                "message": "Server internal error. See details in report api/487380499411"
            }
        ]
    }
}`

And in the report file I get this error:

> Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Paypal\\Model\\Adminhtml\\Express\\Interceptor::isOrderAuthorizationAllowed() must be an instance of Magento\\Sales\\Model\\Order\\Payment, null given, called in \/home\/forge\/magento2.test\/public\/vendor\/magento\/module-paypal\/Plugin\/OrderCanInvoice.php on line 41 and defined in \/home\/forge\/magento2.infinity-mobile.io\/public\/generated\/code\/Magento\/Paypal\/Model\/Adminhtml\/Express\/Interceptor.php:33
> Stack trace:
> #0 \/home\/forge\/magento2.test\/public\/vendor\/magento\/module-paypal\/Plugin\/OrderCanInvoice.php(41): Magento\\Paypal\\Model\\Adminhtml\\Express\\Interceptor->isOrderAuthorizationAllowed(NULL)
> #1 \/home\/forge\/magento2.test\/public\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Magento\\Paypal\\Plugin\\OrderCanInvoice->afterCanInvoice(Object(Magento\\Sales\\Model\\Order\\Interceptor), false)
> #2 \/home\/forge\/magento2.test\/public\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Sales\\Model\\Order\\Interce' in '\/home\/forge\/magento2.test\/public\/generated\/code\/Magento\/Paypal\/Model\/Adminhtml\/Express\/Interceptor.php' on line 33

**Comment by ghost** [comment]
Hi @bibiseb thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @bibiseb. Thank you for your report. 
The issue has been fixed in magento/magento2#15683 by @michielgerritsen in 2.2-develop branch
Related commit(s):
 - [f1554d42e7824ea9149d20142a0178f7a7d31f90](https://github.com/magento/magento2/commit/f1554d42e7824ea9149d20142a0178f7a7d31f90)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @bibiseb. Thank you for your report. 
The issue has been fixed in magento/magento2#18521 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [14b3eaf131298ab8e70bdd529789c91821fbe4a2](https://github.com/magento/magento2/commit/14b3eaf131298ab8e70bdd529789c91821fbe4a2)
 - [3eb6c3e70e65fdadc92f30d4faba77751863580c](https://github.com/magento/magento2/commit/3eb6c3e70e65fdadc92f30d4faba77751863580c)

The fix will be available with the upcoming 2.3.1 release.
