### ISSUE TITLE
Wrong order amount on dashboard on Last orders listing when having more than one website with different currencies

### ISSUE THREAD

**Issue by ankurvr** [magento/magento2#15660]
On Dashboard Last order's table shows wrong table for specific store view dashboard when you have multiple websites and both have different currencies.
Actual Problem is mentioned in 8th point of Steps to Reproduce.

### Preconditions

1. Magneto CE (2.2.3, 2.2.4)
2. PHP Ver 7.0.24
3. MySQL Ver (5.7, 8.0.11)
4. Platform : MacOS High Sierra Ver 10.13.4

### Steps to reproduce

1. Create 2 Websites with 1 store in each
2. Set Default website/store base currency as INR (Indian Rupee)
3. Set another website/store base currency as USD (US Dollar)
4. Place Order from both websites with with their default currencies.
5. Now go to Dashboard and set **Store View** as _All Store Views_
6. See **Last Orders** table and check order's total amounts and all mounts will be in INR (USD orders will be converted to INR with exchange rate
7. Now change **Store View** to USD currency website's store which have orders
8. See **Last Orders** table and check order's total amounts. You will find those amounts converted to again into INR to USD. But at this point orders are already in USD so no need to convert amounts.

### Expected result

1. All Store View Dashboard
<img width="1084" alt="screen shot 2018-06-01 at 4 54 03 pm" src="https://user-images.githubusercontent.com/3338156/40838784-3c6d9fae-65bd-11e8-93c6-04fdc8c23fb4.png">

2. Second Store View Dashboard which have USD currency
<img width="1085" alt="screen shot 2018-06-01 at 5 01 03 pm" src="https://user-images.githubusercontent.com/3338156/40838845-80a5b486-65bd-11e8-9edf-82d08a49706a.png">

### Actual result

1. All Store View Dashboard
<img width="1084" alt="screen shot 2018-06-01 at 4 54 03 pm" src="https://user-images.githubusercontent.com/3338156/40838696-017cf836-65bd-11e8-9e83-b9401075778b.png">

2. Second Store View Dashboard which have USD currency
<img width="1086" alt="screen shot 2018-06-01 at 4 54 29 pm" src="https://user-images.githubusercontent.com/3338156/40838700-03924928-65bd-11e8-8e21-8c85a2d7e758.png">

**Comment by magento-engcom-team** [comment]
Hi @ankurvr. Thank you for your report. 
The issue has been fixed in magento/magento2#15682 by @ankurvr in 2.3-develop branch
Related commit(s):
 - [f5f3c761a42579a4b0b6b2cafc45c17e4e17248f](https://github.com/magento/magento2/commit/f5f3c761a42579a4b0b6b2cafc45c17e4e17248f)
 - [d696233736f0883e5c54f0ba81f635f8e2da8603](https://github.com/magento/magento2/commit/d696233736f0883e5c54f0ba81f635f8e2da8603)
 - [424324e78a7c0c2ab980e4ccaea9eb48ede99f31](https://github.com/magento/magento2/commit/424324e78a7c0c2ab980e4ccaea9eb48ede99f31)
 - [eca36b2809a25e42d2f070caca533b163e48bad0](https://github.com/magento/magento2/commit/eca36b2809a25e42d2f070caca533b163e48bad0)
 - [98265ab15fdfc120f2939dc81cf0d6756d71d8e3](https://github.com/magento/magento2/commit/98265ab15fdfc120f2939dc81cf0d6756d71d8e3)
 - [ac220b7845735567a75108593cf19456a5b21cb7](https://github.com/magento/magento2/commit/ac220b7845735567a75108593cf19456a5b21cb7)
 - [12041e1ec05bd78cbfa220d4f98dbf50e1889d6f](https://github.com/magento/magento2/commit/12041e1ec05bd78cbfa220d4f98dbf50e1889d6f)

The fix will be available with the upcoming 2.3.0 release.

**Comment by VladimirZaets** [comment]
Hi @ankurvr. Thank you for your report. 
The issue has been fixed in magento/magento2#15661 by @ankurvr in 2.2-develop branch
Related commit(s):
 - [56bcffbaad34a6ccf66808bfb4247e015aff26a5](https://github.com/magento/magento2/commit/56bcffbaad34a6ccf66808bfb4247e015aff26a5)
 - [1c1e277c19d96ed10449484998e3c0ad0c7b4c7a](https://github.com/magento/magento2/commit/1c1e277c19d96ed10449484998e3c0ad0c7b4c7a)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @ankurvr. Thank you for your report. 
The issue has been fixed in magento/magento2#15677 by @ankurvr in 2.1-develop branch
Related commit(s):
 - [5a379fcc42abbb92c6211e32e1c8f045f37f5ad5](https://github.com/magento/magento2/commit/5a379fcc42abbb92c6211e32e1c8f045f37f5ad5)
 - [0deea0ebd6bc57ea27b888dc3de517241c05349b](https://github.com/magento/magento2/commit/0deea0ebd6bc57ea27b888dc3de517241c05349b)
 - [6b0f8d0ea944de84dae8cbe6e62b983c9e1980f2](https://github.com/magento/magento2/commit/6b0f8d0ea944de84dae8cbe6e62b983c9e1980f2)
 - [25948530b20e95d43a9c816b9068aaa20fd1bfe9](https://github.com/magento/magento2/commit/25948530b20e95d43a9c816b9068aaa20fd1bfe9)

The fix will be available with the upcoming 2.1.15 release.
