### ISSUE TITLE
Incorrect return type getList() in CustomerRepository

### ISSUE THREAD

**Issue by springimport** [magento/magento2#15775]
### Preconditions
Magento 2.2.3.
Get customers using CustomerRepository.

### Steps to reproduce
1. CustomerRepository->[getList()](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Model/ResourceModel/CustomerRepository.php#L342).

### [Expected result](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Api/CustomerRepositoryInterface.php#L58)
1. $searchCriteria is \Magento\Customer\Api\Data\CustomerSearchResultsInterface.

### Actual result
1. $searchCriteria is \Magento\Framework\Api\SearchResults.
-----
Example for OrderRepository (behavior is correct).
```OrderRepository->getList() returns \Magento\Sales\Model\ResourceModel\Order\Collection.```
Collection implements OrderSearchResultInterface.

**Comment by ghost** [comment]
@springimport, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by p-bystritsky** [comment]
Created PRs for 2.2 and 2.3.

**Comment by skylineop** [comment]
@magento I'm working on it

**Comment by magento-engcom-team** [comment]
Hi @springimport. Thank you for your report. 
The issue has been fixed in magento/magento2#20181 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [36ad18af62f3d434b3a08eb6358217ff43cd1bce](https://github.com/magento/magento2/commit/36ad18af62f3d434b3a08eb6358217ff43cd1bce)

The fix will be available with the upcoming 2.3.4 release.
