### ISSUE TITLE
Admin startup page issue. 

### ISSUE THREAD

**Issue by shater1990** [magento/magento2#15815]
### Preconditions

1. Magento 2.2.4 version.
2. Google cloud server with bitnami

### Steps to reproduce

1. I installed Infortis theme .
2. Login Admin page(It is good).
3. After login admin page, enter the admin url directly in the my web browser again, I had 404 page not found.

### Expected result

1. [Screenshots, logs or description]
![unnamed qq screenshot20180605152637](https://user-images.githubusercontent.com/36569777/40958607-e0b4357c-68d4-11e8-8ed2-2486207e1f4e.png)

### Actual result

1. [Screenshots, logs or description]
![unnamed qq screenshot20180605152332](https://user-images.githubusercontent.com/36569777/40958498-758409ee-68d4-11e8-8170-651e83e0da24.png)

**Comment by hirale** [comment]
Requested url is missing form key.

**Comment by ghost** [comment]
Hi @shater1990  in settings you need to Add Secret Key to URLs -> no

**Comment by konarshankar07** [comment]
Hello @shater1990 ,
The admin url is going to 404 because the theme you are using have an extension name Infortis_Dataporter. In this extension, the route name is used same as magento that's why this bug is generating. You can fix this by rename the route name from "adminhtml" to "ultimoadminhtml" and don't forgot to rename the layout files  from "adminhtml_cfgporter_index_export.xml" to "ultimoadminhtml_cfgporter_index_export"  and "adminhtml_cfgporter_index_import.xml"  to "ultimoadminhtml_cfgporter_index_import.xml"

Thanks,
Shankar
