### ISSUE TITLE
Magento 2.2.x - Product save not working correctly after changed attributes by API code

### ISSUE THREAD

**Issue by vutrankien** [magento/magento2#15819]
Hello Magento Team

I have meeting the problem with magento 2.2.4 when change attribute of product via API, after changed attributes of product via API code, if admin change any attributes of product in backend, frontend will not show data changed

### Preconditions

1. Magento 2.2.4
2. PHP Version 7.1.16 + MySQL 5.6.39

### Steps to reproduce

1. Update product already in magento store via API :
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('\Magento\Catalog\Api\ProductRepositoryInterface')->getById(18);
$product->setName('test 44 55 66 77');
$objectManager->create('\Magento\Catalog\Api\ProductRepositoryInterface')->save($product);
```
2. After ran code change attributes of product by API like above, if admin change name or any attributes of product in backed, product detail will not show data changed at frontend

### Expected result

After changed attributes of product by admin, product detail need show data changed correct on frontend

### Actual result

After changed attributes of product by admin, product detail will show data changed not correct on frontend

Thank you for your help.

**Comment by hostep** [comment]
Hi @vutrankien: do you have multiple storeviews? If yes: can you check the storeview values of that particular attribute and see if that value is incorrectly set to the admin value?

**Comment by vutrankien** [comment]
hi @hostep : Thanks for your suggest but  i'm using one storeview only, not multiple storeviews

**Comment by hostep** [comment]
Ah yes, it will probably happen as well with a single storeview. Can you check the value of the attribute on the storeview level? I have the feeling it will have the original admin value, and the checkbox "use default values" will be unchecked.

**Comment by vutrankien** [comment]
First, product save working good, but after change product attribute by api, product save not working normally, see my example below :
![image](https://user-images.githubusercontent.com/14917460/41073679-a7c041b0-6a2e-11e8-80c0-d622bf67b953.png)
Name not change :
![image](https://user-images.githubusercontent.com/14917460/41073727-d453ba4a-6a2e-11e8-91a3-d7fc1ce09691.png)

**Comment by hostep** [comment]
Ok, can you click on the dropdown 'All Store Views' and switch to the lowest level, and take a look if the Product name wasn't overwritten on that level. If it wasn't, then try to reindex (`bin/magento indexer:reindex`) and flush the caches, maybe that helps.

**Comment by vutrankien** [comment]
I think you can try install magento 2.2.4 on localhost and check by yourself

**Comment by proman77** [comment]
Magento 2.2.4
@vutrankien I've got the same issue - can't edit position of attribute in layered navigation block after changed attributes by API.

**Comment by vutrankien** [comment]
@proman77 yes, i think after changed attributes by API, then can't edit by interface

**Comment by proman77** [comment]
@vutrankien,
what's next? Have you seen the source code for the fix?

@hostep, could you push the issue up? Thanks.

**Comment by hostep** [comment]
Hi guys

I still haven't received answers to my questions, and I still don't see exacts steps to reproduce, so I think you'll have to provide some more info so it makes it more clear what the actual issue is here.

Other then that, @proman77, your issue sounds a bit like this one: https://github.com/magento/magento2/issues/13156, but I'm not sure if it is exactly that one?

Also, I'm no employee of Magento, so I can't determine priorities for fixing issues, sorry! :)

**Comment by proman77** [comment]
@hostep @magento-engcom-team 
Steps to reproduce:
1. Import products through REST API
2. Can't save any changes of attribute
PS  #13156 has same result - can't save any changes but values  of attribute look good.

**Comment by hostep** [comment]
@proman77 : so your issue is the same as #13156, right? Can you take a look at the `eav_attribute` table find your attribute and look at the `source_model`, it will probably be incorrectly set to `Magento\Eav\Model\Entity\Attribute\Source\Table`, can you then try to set it to `NULL` and re-evaluate if your bug still happens? (please execute this on a local or staging environment, not on production).
If yes, then maybe you should continue this discussion in #13156 as I think the original problem of @vutrankien is not related. So we shouldn't discuss 2 separate problems in the same thread. Thanks!

**Comment by vutrankien** [comment]
@proman77 now, i don't have solution for fix this problem
@hostep it is related because this is related with product attributes, if you are function developer you will understand
