### ISSUE TITLE
$_view is listed as @deprecated in Magento\Framework\App\Action

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1583]
This code in Magento\Framework\App\Action

    /**
     * @deprecated
     * @var \Magento\Framework\App\ViewInterface
     */
    protected $_view;

Is the deprecated docblock element supposed to be there? If so, what is the alternative? The core code uses this in a lot of places, for example to load the layout: `$this->_view->loadLayout();`

**Comment by kandy** [comment]
Yes, _view property is deprecated but refactoring still in progress.
Alternative is  \Magento\Framework\View\Result\Page, see for example : 
https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Controller/Adminhtml/Product/Grid.php

**Comment by Zatara7** [comment]
@kandy Do happen to have a better example? I've looked at \Magento\Customer\Account\Login and the one you gave but still cannot get it right. What I'm trying to do is make this work with \Magento\Framework\App\Action\Action but the interceptor keeps passing the wrong arguments to my class when instantiating it.

class Index extends \Magento\Framework\App\Action\Action {

	/** @var \Magento\Framework\View\Result\PageFactory  */
	protected $resultPageFactory;

	public function __construct(
		\Magento\Framework\App\Action\Context $context,
		\Magento\Framework\View\Result\Page $resultPageFactory
	) {
		$this->resultPageFactory = $resultPageFactory;
		parent::__construct($context);
	}


	public function execute() {
		$resultPage = $this->resultPageFactory->create();
		$resultPage->initLayout();
		$resultPage->getLayout()->initMessages();
		//$resultPage->renderResult();
		return $resultPage;


The error:
Recoverable Error: Argument 2 passed to Magento\Hello\Controller\Index\Index::__construct() must be an instance of Magento\Framework\View\Result\Page, none given, called in /var/www/html/magento2ce/var/generation/Magento/Hello/Controller/Index/index/Interceptor.php on line 14

**Comment by Zatara7** [comment]
I got it now if it benefits anyone:

class Index extends \Magento\Framework\App\Action\Action {

	/** @var \Magento\Framework\View\Result\PageFactory  */
	//protected $resultPageFactory;

	public function __construct(
		\Magento\Framework\App\Action\Context $context
	) {
		//$this->resultPageFactory = $resultPageFactory;
		parent::__construct($context);
	}


	public function execute() {
		$resultPageFactory = new \Magento\Framework\View\Result\PageFactory($this->_objectManager);
		$resultPage = $resultPageFactory->create();
		$resultPage->initLayout();
		$resultPage->getLayout()->initMessages();
		return $resultPage;
	}
}


I'm not sure if this is the best way to do it.

**Comment by piotrekkaminski** [comment]
@kandy do you know if this was refactored?

**Comment by alankent** [comment]
@Zatara7 I may be missing something, but is there a reason you don't accept the PageFactory in the constructor and save that to the property, as commented out?  Your previous code sample I think had an error in that the constructor used type 'Page' instead of 'PageFactory', which would have caused "strange things" to happen. The DI framework would give you a Page (not a PageFactory), which you then attempted to call "create()" on.  I am not sure if that was a simple typo mistake or on purpose.

**Comment by Zatara7** [comment]
Sorry @alankent I was only learning when I wrote that code. Please disregard it I'm sure it's full of mistakes. I thought by posting it, I may be able to help the original poster.

**Comment by antonkril** [comment]
@markoshust can we close this issue?

**Comment by markoshust** [comment]
@antonkril @alankent can you confirm this is the "correct" way of implementing this update?

```php
class Index extends \Magento\Framework\App\Action\Action {
    /** @var \Magento\Framework\View\Result\PageFactory  */
    protected $resultPageFactory;

    public function __construct(\Magento\Framework\App\Action\Context $context) {
        $this->resultPageFactory = $resultPageFactory;
    }

    public function execute() {
        $resultPageFactory = new \Magento\Framework\View\Result\PageFactory($this->_objectManager);
        $resultPage = $resultPageFactory->create();
        $resultPage->initLayout();
        return $resultPage;
    }
}
```

**Comment by antonkril** [comment]
Not exactly. Generic factory should be used in controllers and, `loadLayout` call is not required, you can just return result. 

```php
namespace My\Namespace;

use Magento\Framework\Controller\ResultFactory;

class Index extends \Magento\Framework\App\Action\Action 
{
    /** @var \Magento\Framework\Controller\ResultFactory  */
    protected $resultFactory;

    public function __construct(
        \Magento\Framework\App\Action\Context $context,
        ResultFactory $resultFactory
    )  {
        parent::__construct($context);
        $this->resultFactory = $resultFactory;
    }

    /**
     * {@inheritdoc}
     */
    public function execute()
    {
        return $this->resultFactory->create(ResultFactory::TYPE_PAGE);
    }
}
```

Also we plan to modify actions slightly so that extending from `\Magento\Framework\App\Action\Action` will not be required and will be discouraged. Action will only have to implement `\Magento\Framework\App\ActionInterface`.

**Comment by markoshust** [comment]
Great, thanks

**Comment by pantaoran** [comment]
@antonkril is there an example of a controller NOT extending `\Magento\Framework\App\Action\Action` and instead implementing `\Magento\Framework\App\ActionInterface`? I think that I would lose a lot of functionality for which I rely on that parent...

**Comment by pantaoran** [comment]
Actually I just noticed that the deprecated flag which started this issue was removed 3 months ago.

So what is now the recommended way to build controllers?

@markoshust FYI

**Comment by markshust** [comment]
@pantaoran i have to think that a lot of code uses the old format, and they didn't have time to refactor everything before the 2.0.0 ga, and didn't want to release with 'deprecated' code. i'm guessing the recommended way to build controllers is still the last post by @antonkril

**Comment by antonkril** [comment]
@pantaoran, @markoshust, since `ViewInterface` is not marked as @api, we do not recommend to use it anyway, so @deprecated was removed. 

So for now, the recommended way is the one I provided.

As for `ActionInterface`, - it's an excellent question. On GA version, if you just implement it, you will lose all behavior from `\Magento\Framework\App\Action\Action` and other "super-abstracts".

But we are working on this and in one of the next M2 releases you will be able to just implement 'ActionInterface' in your Actions, and get all framework-provided behavior. We want to allow third-party developers to not inherit from our classes.

**Comment by Mabonito** [comment]
> Yes, **$_view** property is deprecated but refactoring still in progress. Alternative is \Magento\Framework\View\Result\Page, see for example : https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Controller/Adminhtml/Product/Grid.php

Hi Kandy, the link that you share on the above send to a 404 page, is there an alternative for this link.
Thank you
