### ISSUE TITLE
No button-primary__font-weight

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15832]
### Preconditions
Magento 2.2.4

### Steps to reproduce

There is no `@button-primary__font-weight` for setting the font weight of the primary buttons.
(under lib/web/css/source/lib/variables/_buttons.less)

### Expected result
Possibility to change only primary button font-weight without changing regular button font-weight with less variables 

### Actual result
Primary button don't have specific variable and falling back to variable @button__font-weight

**Comment by Karlasa** [comment]
@DanielRuf  Primary button also don't have font-size and font-family variable and falling back to regular button settings. Not sure if it should be added? If yes, It's "good first issue" :)

**Comment by sidolov** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16012 by @Karlasa in 2.2-develop branch
Related commit(s):
 - [ab643ce7eba6b44ffdcd7a8050344b777ecf10b6](https://github.com/magento/magento2/commit/ab643ce7eba6b44ffdcd7a8050344b777ecf10b6)
 - [dd007e3ec6f1e660b14a60e112d914d537cac09f](https://github.com/magento/magento2/commit/dd007e3ec6f1e660b14a60e112d914d537cac09f)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16037 by @chirag-wagento in 2.1-develop branch
Related commit(s):
 - [324ee503d0fa0ec042e220c92384143efbf110d2](https://github.com/magento/magento2/commit/324ee503d0fa0ec042e220c92384143efbf110d2)
 - [41b4775b2d953cba7b7065a1c0d6ec3a088099c2](https://github.com/magento/magento2/commit/41b4775b2d953cba7b7065a1c0d6ec3a088099c2)

The fix will be available with the upcoming 2.1.15 release.

**Comment by VladimirZaets** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16036 by @chirag-wagento in 2.3-develop branch
Related commit(s):
 - [d7e77e617e54d586a162ef0d63d74eba33d0efdb](https://github.com/magento/magento2/commit/d7e77e617e54d586a162ef0d63d74eba33d0efdb)
 - [c4de267a7bf32adf50d188531689de9cf75f0f11](https://github.com/magento/magento2/commit/c4de267a7bf32adf50d188531689de9cf75f0f11)

The fix will be available with the upcoming 2.3.0 release.
