### ISSUE TITLE
no navigation-level0-item__hover__color

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#15848]
We have `@navigation-level0-item__active__color` but no `@navigation-level0-item__hover__color`

Keep in mind that we also have hover on some devices and screens (resized browser window).

**Comment by engcom-backlog-nickolas** [comment]
Hello @DanielRuf, thank you for your report. 
GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.

**Comment by DanielRuf** [comment]
This is an actual bugreport. There is a missing variable.

**Comment by DanielRuf** [comment]
I can also provide a PR then if no other developer wants to contribute to solve this easy issue.

**Comment by engcom-backlog-nickolas** [comment]
@DanielRuf, thank you for your feedback. You are right, my bad.

**Comment by hitesh-wagento** [comment]
I am working on this PR

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16732 by @hitesh-wagento in 2.2-develop branch
Related commit(s):
 - [1fbc2db2ada04f8f2951acdb9591231d82a3f711](https://github.com/magento/magento2/commit/1fbc2db2ada04f8f2951acdb9591231d82a3f711)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16797 by @hitesh-wagento in 2.1-develop branch
Related commit(s):
 - [faa98158a42b2a5841e789be0f09b430f3b6e9bb](https://github.com/magento/magento2/commit/faa98158a42b2a5841e789be0f09b430f3b6e9bb)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16796 by @hitesh-wagento in 2.3-develop branch
Related commit(s):
 - [85caf639895f5fa1dd71dda08b791e8cbfaee7e4](https://github.com/magento/magento2/commit/85caf639895f5fa1dd71dda08b791e8cbfaee7e4)

The fix will be available with the upcoming 2.3.0 release.
