### ISSUE TITLE
Running setup:install with --cleanup-database flag is no longer possible when your app/etc/env.php exists

### ISSUE THREAD

**Issue by hostep** [magento/magento2#15864]
This was accidentally discovered while trying to replicate another bug.

So, I was trying to install the current version of the `2.2-develop` branch with the `bin/magento setup:install` command, and it fails.
After bisecting, I found the commit which introduced the problem and that is: 914389161fee5091bfe6ea3069755295c7243ecf
Since that commit dates from March 2018, I feel like someone should at least have noticed this, yet, we are 3 months down the line and it still happens, so this has worried me little bit ...

/cc @slopukhov

### Preconditions
1. PHP 7.0.30

### Steps to reproduce

1. Clone this repo and checkout the `2.2-develop` branch, I'm using commit 10f84fdd222f085fcb007631976b113775b02143
2. Run `composer install`
3. Run `./bin/magento setup:install     --admin-firstname=Ad     --admin-lastname=Min     --admin-email=someone@example.com     --admin-user=admin     --admin-password=admin123     --base-url=https://example.com/     --base-url-secure=https://example.com/     --backend-frontname=admin     --db-host=localhost     --db-name=magento2-github     --db-user=root     --db-password=*secret*     --language=en_US     --currency=EUR     --timezone=Europe/Brussels     --use-rewrites=1     --use-secure=1     --use-secure-admin=1     --admin-use-security-key=1     --session-save=files     --cleanup-database`

### Expected result
Installation goes fine without errors

### Actual result
```
Starting Magento installation:
File permissions check...
[Progress: 1 / 486]
Required extensions check...
[Progress: 2 / 486]
Enabling Maintenance Mode...
[Progress: 3 / 486]
Installing deployment configuration...
[Progress: 4 / 486]
Cleaning up database...
Cleaning up database `magento2-github`
[Progress: 5 / 486]
Installing database schema:


  [Zend_Db_Statement_Exception]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2-github.store_website' doesn't exist, query was: SELECT `store_website`.* FROM `store_website`



  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2-github.store_website' doesn't exist
```

### Additional information
1. (added 11 Jan 2019)  Additional steps to reproduce were provided in the comments below, please see more details by this link https://github.com/magento/magento2/issues/15864#issuecomment-441100421

**Comment by hostep** [comment]
Dug in a little bit more, it's this one line change in the `installSchema` method which causes the problem:
https://github.com/magento/magento2/commit/914389161fee5091bfe6ea3069755295c7243ecf#diff-d3d5031b8198ff87cfbc51bed3736806L772

But I'll leave it over to the magento devs to further investigate, it's probably pretty complex.

I'm wondering why Travis keeps running like everything is ok though ...

**Comment by slopukhov** [comment]
Hi, @hostep 
Looks like problem in the '--cleanup-database' with existing /app/etc/env.php file.
Please try to delete this file before reinstall.

**Comment by hostep** [comment]
@slopukhov: Ah yes indeed, you are correct, removing the `env.php` file solves the problem.

Hmm, I'm not sure if we should ignore this and not consider it as a new bug, since it worked without removing the `env.php` file before 9143891

What do you think?

If this isn't considered a bug, we should probably add something about this to the documentation, so other people running against this can quickly find a solution.

**Comment by slopukhov** [comment]
Hi, @hostep 
Yes, looks like this is bug (with DB connection in the install script with '--cleanup-database' option with existing /app/etc/env.php) and removing /app/etc/env.php file just idea to quick fix.

**Comment by slopukhov** [comment]
Created internal issue MAGETWO-92580. 
But, if you have a solution, it would be great if you can prepare PR with fix for it.

**Comment by ghost** [comment]
@hostep, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by TomashKhamlai** [comment]
The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by leoquijano** [comment]
Thanks @TomashKhamlai.

Questions:
- Is this going to be fixed in a 2.2 release?
- Which commits fix this in the 2.3 branch?

**Comment by hostep** [comment]
@leoquijano: It looks like it works on `2.3-develop` branch indeed, but that's because this bug never existed on the `2.3-develop` branch.

The line I indicated in an earlier post:
`$setup = $this->setupFactory->create($this->context->getResources());` got changed to `$setup = $this->setupFactory->create();` in https://github.com/magento/magento2/commit/914389161fee5091bfe6ea3069755295c7243ecf#diff-d3d5031b8198ff87cfbc51bed3736806L772 which caused the problem

But this change was never done to the `2.3-develop` branch according to the blame view:
https://github.com/magento/magento2/blame/e43fd32810812cb1d8f0de0b1fdf16618d257aad/setup/src/Magento/Setup/Model/Installer.php#L1118 (last change to that line was 3 years ago).

@TomashKhamlai: I'm re-opening if you don't mind, since this bug is not fixed in 2.2 and was not fixed on 2.3, because the bug never existed on the `2.3-develop` branch.

**Comment by leoquijano** [comment]
Thanks for the explanation, @hostep.

**Comment by ghost** [comment]
Hi @hostep , i'm trying reproduce this bug on 2.2-develop but unsuccessful, but i found new trouble, when i have a module which have a console command, and you injected in this command, class like this ->
`use Magento\Catalog\Model\ProductRepository;` so i have a error like in your issue when i try to install magento with this module.

**Comment by hostep** [comment]
@engcom-backlog-nazar: this is very easily reproducible on the latest 2.2-develop branch:

1. Clone magento2's repo, use the 2.2-develop branch (I'm using commit 13de5a75d03)
2. Run `composer install`
3. Run `./bin/magento setup:install --admin-firstname=Ad --admin-lastname=Min --admin-email=someone@example.com --admin-user=admin --admin-password=admin123 --base-url=https://example.com/ --base-url-secure=https://example.com/ --backend-frontname=admin --db-host=localhost --db-name=magento2-github --db-user=root --db-password=*secret* --language=en_US --currency=EUR --timezone=Europe/Brussels --use-rewrites=1 --use-secure=1 --use-secure-admin=1 --admin-use-security-key=1 --session-save=files --cleanup-database` => **this works**
4. Repeat nr 3 => **this fails**
5. Remove the file `app/etc/env.php`
6. Repeat nr 3 => **this works again**
7. Repeat nr 3 => **this fails again**

It works the first time you run `setup:install` because no `app/etc/env.php` file exists yet. It fails the second time you run it because that file got generated by the first run.

Should I update my openingspost with this extra information about the `app/etc/env.php` file? (even though it is mentioned in the title and was [brought to my attention](https://github.com/magento/magento2/issues/15864#issuecomment-395048553) by @slopukhov)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @hostep. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-92580` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by mmenozzi** [comment]
@magento-engcom-team I experienced/reproduced this issue many times with Magento 2.2. The steps described by @hostep are very clear. Please try again.

**Comment by hostep** [comment]
@mmenozzi: I just tested again to verify their claims, and issue can be closed.

I'm noticing that it is broken in Magento 2.2.7, but fixed in 2.2.8 and also fixed on the `2.2-develop` branch. So all is good!

**Comment by maaarghk** [comment]
for me, still occurs on 2.3.3 if cache_types/full_page = 1

**Comment by hostep** [comment]
@maaarghk: I can't reproduce it with [these steps](https://github.com/magento/magento2/issues/15864#issuecomment-441100421) on a vanilla 2.3.3 installation, and yes full_page cache is enabled.

Are you sure this isn't caused by some customisation in your case?
If you can reproduce on a vanilla installation, please provide exact steps to reproduce and open a new issue, thanks!

**Comment by maaarghk** [comment]
I was on a vanilla install of 2.3.3. 

Following above steps, between steps 2 and 3, and between steps 6 and 7 empty all tables from the database.

Rather than removing the file I tried removing just install date, crypt key, lock, backend frontname, repeating no 3 continued to fail. Strangely setting cache_types/full_page = 0 then running no 3 again worked.

#23577 might be more relevant?


Actually looking back at notes I already filled DB connection details in env.php and didn't provide them in setup:install command.
