### ISSUE TITLE
Backend language change doesn't work on Magento 2.2.3

### ISSUE THREAD

**Issue by simonfunk** [magento/magento2#15886]
### Preconditions
1. Magento 2.2.3
2. PHP 7.1

### Steps to reproduce
1. Login to Backend area
2. Go to Account Settings (Over menu on top right)
3. Change language to any other than english

### Expected result
1. Backend should display in set language

### Actual result
1. Backend still showing in english

### Additional
We already executed follwing command with no success:
```
bin/magento setup:static-content:deploy --area adminhtml -f
bin/magento cache:flush
bin/magento cache:clean
```

**Comment by hostep** [comment]
Hi @simonfunk

Did you install a language pack? As far as I'm aware, Magento only comes bundled with an English language pack, so if you want other languages, you first need to install a language pack for the language you want to use.

**Comment by simonfunk** [comment]
Yes of course. The language pack is installed

**Comment by hostep** [comment]
Thanks for the update!

So here are the steps I took to try to reproduce the issue and I wasn't able to reproduce it:
- Setup a clean Magento 2.2.3 installation
- Installed a French language pack using composer: `composer require imaginaerum/magento2-language-fr-fr`
- Ran `bin/magento setup:upgrade`
- Put the store in production mode: `bin/magento deploy:mode:set production`
- Visited the backend, clicked on Account Settings
- Noticed only English is available, which is expected, since the default static content deploy which is triggered by production mode only generates a theme for the configured languages
- Explicitly ran static content deploy for backend theme in French: `bin/magento setup:static-content:deploy --theme Magento/backend fr_FR`
- Visited Account Settings again
- Noticed I now have the option to pick English or French, picked French and saved
- Backend is available in French

Does this help?

**Comment by simonfunk** [comment]
Hi again @hostep

That fixed it for some reason. I'm not sure whether it was because we were running in developer mode before or whether it was due to explicity deploying static content while naming the theme, location and language. Shouldn't it deploy all languages if none are named? And developer mode alone shouldn't be an issue either in my opinion since we were using -f flag when deploying static content.

Thanks for your help.

**Comment by hostep** [comment]
Hi @simonfunk 

Static content deploy only deploys the languages it knows your project uses.

Magento looks at all the configured Locale settings (Stores > Configuration > General > General > Locale Options > Locale; default value & website specific values & storeview specific values), and it will also use locale's if they are defined in `app/etc/config.php` or `app/etc/env.php` somewhere.

But if the specific locale you need isn't defined anywhere, it's best to explicitly add it to the `static:content:deploy` command as last parameter.

As far as developer mode goes, you should **never** need to run `static:content:deploy`, that is only for production environments. In developer mode everything is generated automagically by refreshing your page. (make sure to remove all files & directories in `var/view_preprocessed/` and `pub/static/frontend/` or `pub/static/adminhtml/`, but **don't** remove the `.htaccess` files in there, and just refresh the page, everything will be regenerated)

If you are into frontend development, this might not always be the easiest way to go, and you might need to look at [compiling less files with grunt](https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-topics/css_debug.html), but it has been too long since I did any significant frontend work to be sure if you actually need to use grunt on can always rely on the automagic generation of css files.

Let's close this issue, as it's not an actual bug in Magento.
