### ISSUE TITLE
Unable to save customer attribute. Missing attribute set id when save customer.

### ISSUE THREAD

**Issue by hungpvdev** [magento/magento2#15898]
### Preconditions
Happen in Magento 2.2.x, tested in 2.2.0 & 2.2.4. 
2.1.x still works but still  have issue. After hours debug to magento core i found the problem. 

### Steps to reproduce
1. Create custom attribute with setup script. 
```
$eavSetup->addAttribute(
                \Magento\Customer\Model\Customer::ENTITY,
                'saved_tokens',
                [
                    'type'         => 'text',
                    'input'        => 'hidden',
                    'label'        => '',
                    'required'     => 0,
                    'user_defined' => 0,
                    'visible'      => 0,
                    'backend'      => '$path\Token\Backend',
                ]
            );
```
Backend file response for encrypt & decrypt  value.

2. Update custom attribute value
This attribute was use for saving customer 's payment token, there are a lot of code for this so i won't post full code. Just simple set data to customer model in some controller.

```
$customer->setSavedTokens('some string');
$customer->save();
```

### Expected result
Customer attribute should be saved.

### Actual result
Customer attribute is not saved. 

After hours digging in magento core. The main problem of this issue is customer entity does not have attribute set id value.
Please take a look at \Magento\Eav\Model\Entity\AbstractEntity::_collectSaveData
Line 1331, we have this:
```
if (!$attribute->isInSet($newObject->getAttributeSetId()) && !in_array($k, $staticFields)) {
                $this->_aggregateDeleteData($delete, $attribute, $newObject);
                continue;
            }
```
If attribute is not in same set with object & not in staticFields array. It will be deleted. 
Be cause of my attribute is custom attribute, !in_array($k, $staticFields) is true.
So we we will see isInSet function:
 ```
public function isInSet($setId)
    {
        if (!$this->hasAttributeSetInfo()) {
            return true;
        }

        if (is_array($setId) && count(array_intersect($setId, array_keys($this->getAttributeSetInfo())))) {
            return true;
        }

        if (!is_array($setId) && array_key_exists($setId, $this->getAttributeSetInfo())) {
            return true;
        }

        return false;
    }
```

**In 2.1**, !$this->hasAttributeSetInfo() is true. Well, it's bug as i know. Because attribute does have attribute set info. It belong to customer attribute set, which have attribute set id hard value = 1. Related issue [#4677](https://github.com/magento/magento2/issues/4677)

Lucky for us, we have return true inside if condition. It make my attribute value is not deleted. After that, everything work as expected. Attribute value is saved. 

**In 2.2**, $this->hasAttributeSetInfo() is not null anymore. It seem this bug is fixed.
![image](https://user-images.githubusercontent.com/37575785/41036646-f21524e8-69ba-11e8-91dc-cdb3cf0104aa.png)
Continue, we have $setId is null, so isInSet return false, it make my attribute value is deleted. Then  customer value are saved, except my attribute. 

Notes: 
$setId is null in both Magento 2.1 & 2.2. I'm consider this is bug. Because currently, customer entity does have attribute set id = 1. We can see const for that in \Magento\Customer\Api\CustomerMetadataInterface::ATTRIBUTE_SET_ID_CUSTOMER. 

Workaround for this issue is pretty simple. Before save customer, we set attribute set id = const above.

**Comment by duckchip** [comment]
@hungpvdev Can you explain on which class you triggered this beforeSave method? 
Thx.

**Comment by ghost** [comment]
Hi @hungpvdev thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by hungpvdev** [comment]
@duckchip You just need to set attribute set value for customer model before run save()

For example:
// Set customer model attribute set id
$customer->setAttributeSetId(\Magento\Customer\Api\CustomerMetadataInterface::ATTRIBUTE_SET_ID_CUSTOMER);

// Set some value to customer model
$customer->setSavedTokens('some string');
$customer->save();

**Comment by Thundar** [comment]
Duplicates issue https://github.com/magento/magento2/issues/12479

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment]
#MM19IIN
