### ISSUE TITLE
Click for price in home page can`t work

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento2#15922]
### Preconditions

1. Magento2.2.4
2. php7.0.20
3. Mariadb10.1.24

### Steps to reproduce

1. Background merchandise edit product such as sample data (SKU:24-WB04) Added Manufacturer's Suggested Retail Price, which is higher than the price of the product.
2. Add Catalog Product List widget to home page.

### Expected result

1. Click for price should click.

### Actual result

1. 
![20180607154407](https://user-images.githubusercontent.com/4518013/41085451-ada37170-6a69-11e8-9416-ad78d3b14f28.png)

**Comment by engcom-backlog-nickolas** [comment]
Hello @michaeldyl520, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @michaeldyl520. Thank you for your report. 
The issue has been fixed in magento/magento2#19663 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [f0738591c91ef676b7924f0988c7664fdacdf8d1](https://github.com/magento/magento2/commit/f0738591c91ef676b7924f0988c7664fdacdf8d1)
 - [d116aeca06e7671cea95b818f1d7927a2d2b7bd6](https://github.com/magento/magento2/commit/d116aeca06e7671cea95b818f1d7927a2d2b7bd6)
 - [37b2eb69383f966d38a80d3ba044040339de3b3b](https://github.com/magento/magento2/commit/37b2eb69383f966d38a80d3ba044040339de3b3b)
 - [68636ec6c41eadf000048e124344ed2c6d0cc08a](https://github.com/magento/magento2/commit/68636ec6c41eadf000048e124344ed2c6d0cc08a)

The fix will be available with the upcoming 2.3.1 release.
