### ISSUE TITLE
Wrong end of month at Reports for Europe/Berlin time zone if month contains 31 day

### ISSUE THREAD

**Issue by Stepa4man** [magento/magento2#15940]
### Preconditions
1. Set Timezone "Central European Standard Time (Europe/Berlin)" at the STORE->CONFIGURATION->GENERAL->General->Local options-> Timezone and save configuration
2. Create orders at 31-st day of a month which has this date (May will be used for example)

### Steps to reproduce
1. Go to the Reports adminhtml menu "Products">"Ordered" grid 
2. Select "From" -  01.05.2018
3. Select "To" -  31.05.2018
3. Select "Show by"  - Month
4. Hit refresh

### Expected result
1. Orders that were created at 31.05.2018 are in the grid

### Actual result
1. Orders that were created at 31.05.2018 are NOT in the grid

Comment:
MAGE_ROOT/vendor/magento/module-reports/Model/ResourceModel/Report/Collection.php:218
$interval['end'] filled with 30.05.2018 instead of 31.05.2018

My solution:
Replace: $dateStart->format('Y-m-' . date('t', $dateStart->getTimestamp()) . ' 23:59:59')
with:
$dateStart->format('Y-m-' . cal_days_in_month(CAL_GREGORIAN, $dateStart->format('m'), $dateStart->format('Y')) . ' 23:59:59')

System:
Ububntu16.04/MySQL5.7/PHP7.0

**Comment by the-midi** [comment]
If PHP is compiled without calendar support the proposed solution will not work. Another solution would be to replace it with:
$dateStart->format('Y-m-' . date('t', \DateTime::createFromFormat('d-m-Y g:i:s', $dateStart->format('d-m-Y 00:00:00'))->getTimestamp()) . ' 23:59:59')

This will essentially remove the timezone element when getting the UTC timestamp allowing the correct month to be used.

I have created a PR for this: https://github.com/magento/magento2/pull/16492

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your report. 
The issue has been fixed in magento/magento2#16492 by @michaelwylde in 2.3-develop branch
Related commit(s):
 - [2482579d2dc137c52b5902fbd20fc088acfb7fc7](https://github.com/magento/magento2/commit/2482579d2dc137c52b5902fbd20fc088acfb7fc7)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @Stepa4man. Thank you for your report. 
The issue has been fixed in magento/magento2#16585 by @mageprince in 2.1-develop branch
Related commit(s):
 - [efbe4ded5fab22146996ead87d64b3327f628f8a](https://github.com/magento/magento2/commit/efbe4ded5fab22146996ead87d64b3327f628f8a)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your report. 
The issue has been fixed in magento/magento2#16584 by @mageprince in 2.2-develop branch
Related commit(s):
 - [e233d6ce88b08644839d4401d86317a1798d2d90](https://github.com/magento/magento2/commit/e233d6ce88b08644839d4401d86317a1798d2d90)

The fix will be available with the upcoming 2.2.6 release.
