### ISSUE TITLE
Imported Configurable Products Don't Retain Type Without Children/Configurations

### ISSUE THREAD

**Issue by CNanninga** [magento/magento2#15963]
If a product is imported with the "configurable" type but without defining configurations in the import file, it is successfully created as a Configurable.  If this product is edited and saved, without adding any configurations, the product type is permanently changed to Simple.

### Preconditions

1. Magento 2.2.3
2. PHP 7.1.7
3. MySQL 5.6

### Steps to reproduce

1. Create a product import file with minimal required fields, defining at least one product in the file with the "configurable" type.  Do not include configuration information in the import.
2. Import the file in the admin.
3. Navigate to Products -> Catalog and observe that the imported configurable product is successfully set as Configurable.
4. Edit the configurable product, change any details, but do not add any configurations in the Configurations tab.
5. Save

### Expected result

One or the other of the following results should happen:

1. An error should result and prevent the product from being saved, and the user should be clearly informed that configurations must be created/assigned.
2. OR the product should maintain its status as a Configurable product after being saved.

### Actual result

The product is successfully saved, and the type is switched to Simple.

### Additional Information

This behavior actually matches what occurs if you create a product manually in the admin, selecting "Configurable Product" but don't actually assign any configurations before saving.  The product ends up as a Simple.  The major difference is that in the case of an import, the product first gets created with the Configurable type explicitly set, so the type is changing.  This makes it very easy for a merchant to unexpectedly lose the type if they are incrementally building their product data and haven't gotten to the point of adding configurations.

Even in the case of manually creating a product in the admin, the experience actually isn't ideal.  The experience should really adhere to one of the following:

1. If a product type must be immutable once set and a product must have configurations to be set as Configurable, enforce this.
    1. If the customer chose "Configurable Product" when creating (or if the type is already Configurable such as from an import), throw an explicit error if it's saved without configurations.
    2. If the customer is editing a Simple product, do not include the Configurations tab, since any attempt to add such configurations will fail.
2. Allow product type to be immutable once set, but allow a Configurable product to be created without configurations initially and edited to add configurations later.
3. Allow product type to be mutable by making the Configurations tab actually function (and change type to Configurable) if it is used when editing a Simple product.

**Comment by engcom-backlog-nickolas** [comment]
Hello @CNanninga, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @krnshah. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by orlangur** [comment]
Hi @CNanninga,

> If a product is imported with the "configurable" type but without defining configurations in the import file, it is successfully created as a Configurable

I'm not sure this is correct behavior, should be consistent with manual product creation.

> Actual result
> The product is successfully saved, and the type is switched to Simple.

This is intended system behavior, there is nothing to fix here.

> This makes it very easy for a merchant to unexpectedly lose the type if they are incrementally building their product data and haven't gotten to the point of adding configurations.

I don't really get this. Product will become configurable when it gains some configurations, what data may be lost?

> If the customer is editing a Simple product, do not include the Configurations tab, since any attempt to add such configurations will fail

Adding configurations should work in this scenario.

> Allow product type to be mutable by making the Configurations tab actually function (and change type to Configurable) if it is used when editing a Simple product

Please report such scenario as separate issue. This should actually work. To me it looks like current ticket can be closed as `won't fix`.

**Comment by chernenm-zz** [comment]
Hello @CNanninga,

Thank you for detailed investigation on this issue. 
The issue you are describing is by design system behavior. The product is considered as a configurable one only when there are configuration options associated with it. When there are no any configuration options associated with a product then it is in fact a simple product. 
I do not think it makes much sense to enforce admin user to either provide configuration options or manually update product type to a simple one. But we might need to add some clarity under the Configuration section that the product type is changed to "Configurable" when there are any configuration options added.

**Comment by sivaschenko** [comment]
Closing this issue as not a bug according to https://github.com/magento/magento2/issues/15963#issuecomment-455622746
