### ISSUE TITLE
Backport MAGETWO-84480 to 2.1.x

### ISSUE THREAD

**Issue by subbu1993** [magento/magento2#15965]
The `Magento\Catalog\Model\Product\Image::_getNeedMemoryForFile` calls ends up taking a lot of time (around 50 seconds) to process when getting the image information

I see MAGETWO-84480 entirely removes the method in 2.2. Can this fix be backported into 2.1.x ?

### Preconditions
1. Magento version 2.1.12
2. Php 7.0
3. Mysql Ver 14.14 Distrib 5.6.37-82.2

### Steps to reproduce
1. Load product list page (category)

### Expected result
1. Product list page loads in a reasonable amount of time

### Actual result
![image](https://user-images.githubusercontent.com/13652158/41175996-e72f09cc-6b2c-11e8-8ae2-139feeb9c30d.png)

**Comment by ihor-sviziev** [comment]
@subbu1993 feel free to create backport PR in 2.1-develop branch

**Comment by engcom-backlog-nickolas** [comment]
Hello @subbu1993, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Closed as not reproducible on 2.3-develop
