### ISSUE TITLE
Magento 2 admin login Captcha error "Captcha is not defined"

### ISSUE THREAD

**Issue by kirtinariya1** [magento/magento2#16008]
**Preconditions**
Magento 2.2.3

**Description:
![screenshot-captcha-error-from 2018-06-11](https://user-images.githubusercontent.com/28681937/41228294-821247a0-6d95-11e8-99dc-a5737520ced3.png)
**
We are facing issue in admin login Captcha is not working.
we are checking in Magento version 2.2.3 

**Steps to reproduce**

Step 1)Login to admin.
Step 2)Go to Store > Configuration > ADVANCED > Developer > JavaScript Settings:
        set Merge JavaScript Files: Yes
            Enable JavaScript Bundling: Yes
            Minify JavaScript Files: Yes

        Go to CSS Settings:
            Merge CSS Files: Yes
            Minify CSS Files: Yes

Step 3)click to save config.

Step 4)set production mode.
        Use command: php bin/magento deploy:mode:set production

Step 5)Run admin url. For Example http://127.0.0.1/magentosample223/admin

Step 6) Enter wrong password and face captch screen.

Step 7)It will gives error. Now captch show in admin login form then click to captch button. 
        Error: Uncaught ReferenceError: Captcha is not defined

        Note: On page load gives error please check to use inspect element in browser console.
![screenshot-captcha-error-from 2018-06-11](https://user-images.githubusercontent.com/28681937/41228189-1bce6096-6d95-11e8-90d0-c24b3913dc85.png)

**Expected result:**
    Click on captch button captcha should be a regenerate.

**Actual result:**
    Click on captch button captcha will not regenerate.

Please see attachment of screen "Screenshot-Captcha-Error-from 2018-06-11.png"

Thank you.

**Comment by naumanmansuri** [comment]
Facing Same issue

**Comment by attheCube** [comment]
Me too (but in developer mode)

**Comment by ericpronk84** [comment]
Same issue here (production mode)

**Comment by ghost** [comment]
HI @kirtinariya1 thank you for your report, this issue has already ben fixed in 2.2-dev branch

**Comment by magento-engcom-team** [comment]
Hi @webkul-ratnesh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>
- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by webkul-ratnesh** [comment]
Still able to replicate in 2.2.6 in production mode with js merge

**Comment by ghost** [comment]
Hi @webkul-ratnesh did you reproduce this on 2.2-develop branch ?

**Comment by webkul-ratnesh** [comment]
I did in fresh 2.2.6 CE edition.

**Comment by webkul-ratnesh** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16008-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16008-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16008-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by webkul-ratnesh** [comment]
@engcom-backlog-nazar Issue only occur in production mode, and i have not option to enable production mode in you test instance.

**Comment by ghost** [comment]
@webkul-ratnesh ok, i'm try to check this in my local environment on 2.2dev branch.

**Comment by ghost** [comment]
@webkul-ratnesh I'm not able to reproduce this on 2.2-dev branch, have correctly signed in admin dashboard
![captcha](https://user-images.githubusercontent.com/40756439/47844817-0dd61180-ddcc-11e8-9db7-30ac68dfccfb.gif)

**Comment by ghost** [comment]
@webkul-ratnesh can we close this issue ? as this is already fixed.

**Comment by webkul-ratnesh** [comment]
@engcom-backlog-nazar The issue not that we can not login using captcha, the issue is that we can not regenerate new captcha as it is showing error in console, give me few time i will try once in 2.2-dev if i will succeed i will close this issue by myself.

**Comment by ghost** [comment]
@webkul-ratnesh ok

**Comment by webkul-ratnesh** [comment]
@engcom-backlog-nazar
Issue is confirmed on 2.2-dev branch.
Steps to reproduce:
Step 1 : Merge and minify js from admin end.
Step 2 :  Set Magento on production mode.
Step 3 : Logout from Magento admin and try many time with wrong credentials to login.
Step 4 : Eventually Magento will challenge user authentication with Captcha.
There in terminal you can see error.
Check screenshot for reference.

![screenshot_1](https://user-images.githubusercontent.com/2466603/47893310-7089e480-de82-11e8-9c49-9bc30efda2f9.png)

**Comment by ghost** [comment]
@webkul-ratnesh Did you test it on fresh install ? because i'm have different result.
![captcha2](https://user-images.githubusercontent.com/40756439/48014461-680a0600-e12f-11e8-9ce1-cab63451e3b6.gif)

**Comment by gfxguru** [comment]
Same issues, 2.2.6 this is not fixed.

**Comment by ghost** [comment]
@webkul-ratnesh I'm have error incorrect Captcha but not have en error in console.
![selection_194](https://user-images.githubusercontent.com/40756439/48125542-a0bcf300-e287-11e8-99b5-6325cf83de04.png)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@kirtinariya1, it looks like captcha regenerates without any error in console on the latest release. We are closing this issue as fixed. Thank you for reporting

**Comment by dyuk1987** [comment]
I'm still getting this issue on Magento 2.2.7.
Any ideas about how to apply a quick fix to 2.2.7? Or what are the related commits to this issue?
