### ISSUE TITLE
empty div.fields in .fieldset-fullname

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#16017]
### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Go to the registration page
2. check the generated HTML code

### Expected result

1. there is an empty .fields in .fieldset-fullname

### Actual result

1. There should not be any empty .fields in .fieldset-fullname

**Comment by ghost** [comment]
HI @DanielRuf  thank you for your report
We've acknowledged the issue and added to our backlog.

**Comment by rodrigowebjump** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-16017-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16017-2-3-develop.engcom.dev.magento.com/admin](https://i-16017-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rodrigowebjump** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-16017-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16017-2-2-4.engcom.dev.magento.com/admin](https://i-16017-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rodrigowebjump** [comment]
Hi @DanielRuf,
I'm not able to reproduce the issue that you describe. There is no empty .fields in .fieldset-fullname.

If you enable prefix, suffix or middle name in Stores->Configuration->Customer->Customer Configuration->Name and Address Options, the HTML tags that you mention are included to wrap the "name fields". This is an expected behavior.

If you like to update please reopen the issue.

**Comment by DanielRuf** [comment]
So why were the "reproduced" labels added then?

**Comment by DanielRuf** [comment]
Also see the linked commit https://github.com/StevenGuapaBV/magento2/commit/c05587fc1432bd8c41e301ee4ba573b87edb818e and the PR https://github.com/magento/magento2/issues/18396

**Comment by ghost** [comment]
Hi @DanielRuf  Hi @rodrigowebjump  Seems like this is is an expected behavior. I'm also not able to reproduce, if i enable prefix or middle name in configurations, The referenced pr, its just removed the div block, that have a closed on line 137.
It was a mistake to label as reproduce, because this is expected behavior.
Look at attachments and you will see what happened with form if we just remove the "fields" block
![selection_156](https://user-images.githubusercontent.com/40756439/46727778-f5218280-cc89-11e8-9a66-fbde9ab88a40.png)
![selection_157](https://user-images.githubusercontent.com/40756439/46727883-2b5f0200-cc8a-11e8-907e-c044393c23dc.png)

**Comment by DanielRuf** [comment]
> if i enable prefix or middle name in configurations,

We do not have this enabled in our case.

**Comment by ghost** [comment]
@DanielRuf Without config options
![selection_160](https://user-images.githubusercontent.com/40756439/46728974-be00a080-cc8c-11e8-99d7-c4036f6d8650.png)

**Comment by DanielRuf** [comment]
Ok so this seems to be fixed now (by the linked PRs, I guess).

**Comment by ghost** [comment]
@DanielRuf But if this  will be merged this produce the bug. But i'm also cant find empty fields.

**Comment by rodrigowebjump** [comment]
Hi @DanielRuf I will close the issue for now. If you like to comment please reopen the issue.
Thanks

**Comment by DanielRuf** [comment]
I already did so ;-)
