### ISSUE TITLE
inline-block issue in name form

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#16047]
<img width="115" alt="bildschirmfoto 2018-06-12 um 09 53 20" src="https://user-images.githubusercontent.com/827205/41277115-8b480792-6e26-11e8-9b5c-ed17a25d2e02.png">

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16048 by @DanielRuf in 2.2-develop branch
Related commit(s):
 - [587584cf200ff99e560e2dfd66b5f5dd12273c59](https://github.com/magento/magento2/commit/587584cf200ff99e560e2dfd66b5f5dd12273c59)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#16097 by @DanielRuf in 2.3-develop branch
Related commit(s):
 - [204b4ac07b8eabd7b46f52492bc3094ce5420d17](https://github.com/magento/magento2/commit/204b4ac07b8eabd7b46f52492bc3094ce5420d17)

The fix will be available with the upcoming 2.3.0 release.
