### ISSUE TITLE
Authorize.net 

### ISSUE THREAD

**Issue by milenavasic** [magento/magento2#16050]
### Preconditions

   1. Install Magento 2.2.4 CE
   2. Luma Theme
   3. Sample Data installed

### Steps to reproduce

1. Enable Authorize.net Direct Post payment method
2. Add product to cart
3. Checkout using Credit Card 
4. Place an order

### Expected result

1. Order items should have set original price.

### Actual result

1. Order items have original price $0.0

### Debuging result
This problem appears only if you use Authorize.net Direct Post and create order from fronted.
If you try to create order from admin panel and use this payment method, original price will be correct.

**Comment by Jakhotiya** [comment]
@milenavasic Are you using any promotion rules or can you check in the backend in catalog rules or catalog sales rule? I can't reproduce this issue on my end with steps you provided.

**Comment by milenavasic** [comment]
@Jakhotiya Yes, I have a few rules (those which are created with sample date). I removed them all and the problem still exist.
![image](https://user-images.githubusercontent.com/6206166/41295047-d33db24e-6e59-11e8-9253-9b561d61fa9d.png)

**Comment by ghost** [comment]
Hi @milenavasic  thank you for your report
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @pmclain. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @milenavasic. Thank you for your report. 
The issue has been fixed in magento/magento2#18768 by @pmclain in 2.3-develop branch
Related commit(s):
 - [7bc9c31cdba8a4c4aca2c7fe3276688124b9b75a](https://github.com/magento/magento2/commit/7bc9c31cdba8a4c4aca2c7fe3276688124b9b75a)
 - [389a16b3b2c6cf308c130b09cd08ab75c54dd88c](https://github.com/magento/magento2/commit/389a16b3b2c6cf308c130b09cd08ab75c54dd88c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by Ctucker9233** [comment]
@magento-engcom-team is there a backport for 2.2?
