### ISSUE TITLE
Filters bookmarks saved bad date format

### ISSUE THREAD

**Issue by lucasgonzalez** [magento/magento2#16062]
### Preconditions

1. Magento ver. 2.2.3

### Steps to reproduce

1. Go to the admin site
2. Go to the sales page (or any grid with filters with date and the bookmark saved)
3. Search for a date for example "06/11/2018" using the date picker.
4. Refresh the page and the date will be transform into "11/20/2006"
5. With other dates it could also said: "Invalid Date"

### Expected result

![image](https://user-images.githubusercontent.com/3260408/41290418-3298d96c-6e23-11e8-958f-e4908105683b.png)

### Actual result

![image](https://user-images.githubusercontent.com/3260408/41290444-416c03b0-6e23-11e8-9055-c2ec8c08100d.png)

![image](https://user-images.githubusercontent.com/3260408/41290603-c85cbf36-6e23-11e8-89fd-6f36e2a07b85.png)

**Comment by crtl** [comment]
Same issue on 2.1.11.
Steps:
1. Filter by date from/to (on Order Page)
2. Visit another admin page
3. Go back to order page, one of the dates or both are now Invalid Date.

The problem is the filter stays active. Applying the filter in some conditions can lead to an infinite loader.
Then I have to hide the loader in dev tools to be able to reset the filters.

**Comment by ghost** [comment]
hi @lucasgonzalez  your issue is dublicate with https://github.com/magento/magento2/issues/16507
