### ISSUE TITLE
Configurable product price is not displayed if all children are out of stock and even if Display Out of Stock Products is set to "yes"

### ISSUE THREAD

**Issue by alexber88** [magento/magento2#16069]
### Preconditions

1. Magento CE 2.2.2 with Sample Data
2. PHP 7.0

### Steps to reproduce

1. Create configurable product with view simples
2. Make configurable and all simple products out of stock
3. Set Display Out of Stock Products to "yes"
### Expected result

1. Price for configurable product should be displayed

### Actual result

1. Price is not displayed at all

Seems like in \Magento\ConfigurableProduct\Model\ResourceModel\Product\StockStatusBaseSelectProcessor::process() there is incorrect condition.
It should be:
`if (!$this->stockConfig->isShowOutOfStock()) {`

**Comment by engcom-backlog-nickolas** [comment]
Hello @alexber88, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by indraraka** [comment]
I am working on this #mm18id

**Comment by magento-engcom-team** [comment]
@indraraka thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ktpl-prakash** [comment]
#prakashpatel07

**Comment by akashkarev** [comment]
Looks like the problem is caused by vendor/magento/module-configurable-product/Plugin/Model/ResourceModel/Attribute/InStockOptionSelectBuilder.php

Especially by the condition below
`$select->joinInner(
            ['stock' => $this->stockStatusResource->getMainTable()],
            'stock.product_id = entity.entity_id',
            []
        )->where(
            'stock.stock_status = ?',
            \Magento\CatalogInventory\Model\Stock\Status::STATUS_IN_STOCK
        );`

It should depend on the setting cataloginventory/options/show_out_of_stock

**Comment by josh-carter** [comment]
Possibly related to https://github.com/magento/magento2/pull/12936 & https://github.com/magento/magento2/issues/10454

**Comment by zhartaunik** [comment]
You are looking at wrong places. Final price in index table equals zero. Need to fix indexation process.

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vpodorozh** [comment]
> You are looking at wrong places. Final price in index table equals zero. Need to fix indexation process.

No @zhartaunik - it is not an indexation problem. Current behaviour was added as a side effect of this issue "MAGETWO-72582: Configurable product displays the price of "out of stock" configuration".
I'm working on fix now, the general idea is to allow "out of stock" items to be used for price determination of configurable product ONLY in case all child products are "out of stock".

**Comment by vpodorozh** [comment]
Okay, seems to be fixed now. Waiting for pull request approval.
https://github.com/magento/magento2/issues/18739

**Comment by sdzhepa** [comment]
Hello @alexber88 

This issue was investigated by internal Magento team in the scop of related Jira ticket.
The described flow was additionally discussed with Product Managers/Owners and was confirmed it is not a bug but expected behavior, this requirement covered by internal test case.

Unfortunately, I have to close this issue as well because such changes will not be approved.

To help at least somehow I would recommend having a look at [this topic on the Magento Community Forum](https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Out-of-stock-with-price/td-p/90731). Possibly it has a custom solution for this issue

**Comment by mattyl** [comment]
This cant be right - as it is duplicate of  https://github.com/magento/magento2/issues/23196
My owners expect that out of stock options are visible but grey out and not accesible - this is pretty standard eCommerce experience adn has been available in previous versions of magento

**Comment by nordcomputer** [comment]
I just created a small module to show the price of out-of-stock items based on [this answer](https://magento.stackexchange.com/a/298250/84488) at stackexchange.  Feel free to fork:
https://github.com/nordcomputer/magento2-showoutofstockprice

Composer install should work, if you add the repo to your dependencies. Be aware, that I set the required php version to "^7.1" - you may need to reconfigure that in the cmposer.json file, if you use another version.

**Comment by vitormcsi** [comment]
> I just created a small module to show the price of out-of-stock items based on [this answer](https://magento.stackexchange.com/a/298250/84488) at stackexchange. Feel free to fork:
> https://github.com/nordcomputer/magento2-showoutofstockprice
> 
> Composer install should work, if you add the repo to your dependencies. Be aware, that I set the required php version to "^7.1" - you may need to reconfigure that in the cmposer.json file, if you use another version.

Thanks for this, but in list page not show, you can fix this? Thanks.

**Comment by nordcomputer** [comment]
> > I just created a small module to show the price of out-of-stock items based on [this answer](https://magento.stackexchange.com/a/298250/84488) at stackexchange. Feel free to fork:
> > https://github.com/nordcomputer/magento2-showoutofstockprice
> > Composer install should work, if you add the repo to your dependencies. Be aware, that I set the required php version to "^7.1" - you may need to reconfigure that in the cmposer.json file, if you use another version.
> 
> Thanks for this, but in list page not show, you can fix this? Thanks.
Could you open an issue directly in the extension and explain a bit more?
What magento version are you using, did you configure the system configuration (show out of stock products) to yes (not the extension configuration)?

Normally, the extension shows prices also on the category and search result pages.

**Comment by vitormcsi** [comment]
Sorry @nordcomputer, I reindex and fix all, Many Thanks.
