### ISSUE TITLE
Need information about translating issue (Magento Swatches Js)

### ISSUE THREAD

**Issue by Amadeco** [magento/magento2#16079]
### Preconditions
1.  Magento 2.2.4
2. PHP 7.1.17-1 & MySQL 5.7.22

### Steps to reproduce
1. You need a Configurable Product with a Swatch Product Attribute in Attribute Set
2. Swatch attribute have color or image attached to each swatch attribute value
3. This Parent Product have more than three children configured with the Swatch Attribute
4. In configuration, you need to have in Catalog > Storefront > Swatches per Product defined to 2
5. In configuration, you need to have in Catalog > Storefront > Show Swatches in Product List defined to Yes

### Expected result
<img width="383" alt="capture d ecran 2018-06-12 a 23 09 21" src="https://user-images.githubusercontent.com/2975845/41317719-5fff6862-6e96-11e8-9ba0-ace7fbf33024.png">
**String can be translated through i18n string in dictonary.csv**

### Actual result
<img width="383" alt="capture d ecran 2018-06-12 a 23 09 21" src="https://user-images.githubusercontent.com/2975845/41317520-b850c584-6e95-11e8-87eb-0b4cbf34f12b.png">
**String is not translated**

------------------------------------

I would like to have some information about this line : 
https://github.com/magento/magento2/blob/38d7977f88e04f4f03464b0eb5c0ae002c839fc4/app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js#L503

Indeed, I do not see any process to translate this string apart to pass a new value to options moreButtonText.

However, you pass the mage/translate to the define module, so a simple : 
`html += '<a href="#" class="' + moreClass + '">' + $t(moreText) + '</a>';`
would be enough.

Could you provide me some information about this line, or we need to create a pull request about it.

Thank you,

Ilan PARMENTIER

**Comment by magento-engcom-team** [comment]
Hi @mageho. Thank you for your report. 
The issue has been fixed in magento/magento2#16190 by @Karlasa in 2.2-develop branch
Related commit(s):
 - [d468dba73f952522f3c6f9bca074c1a591562ca0](https://github.com/magento/magento2/commit/d468dba73f952522f3c6f9bca074c1a591562ca0)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @mageho. Thank you for your report. 
The issue has been fixed in magento/magento2#16229 by @Karlasa in 2.1-develop branch
Related commit(s):
 - [d09dbe43f20e8a1ef8b943a6d4db181d780860df](https://github.com/magento/magento2/commit/d09dbe43f20e8a1ef8b943a6d4db181d780860df)
 - [f5230328a387adb4c5c4bf454802b7cd3f12ea0f](https://github.com/magento/magento2/commit/f5230328a387adb4c5c4bf454802b7cd3f12ea0f)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @mageho. Thank you for your report. 
The issue has been fixed in magento/magento2#16228 by @Karlasa in 2.3-develop branch
Related commit(s):
 - [abcded5aee17b30b3eb5b5da98c67e9bba79858f](https://github.com/magento/magento2/commit/abcded5aee17b30b3eb5b5da98c67e9bba79858f)
 - [988ef8956d03341280f3599ffb3bb5049cd4af56](https://github.com/magento/magento2/commit/988ef8956d03341280f3599ffb3bb5049cd4af56)

The fix will be available with the upcoming 2.3.0 release.

**Comment by menphis89** [comment]
Hi, I looked carefully if it was all correct in my magento as you describe in the following interventions and it is! Except that it doesn't translate this thing troubles me, the More button I can't translate it in any way...
i have magento:
    Magento 2.3.0
    PHP 7.1
    MySQL 5.7

in the file: /vendor/magento/module-swatches/view/frontend/web/js/swatch-renderer.js
moreButtonText: $t('More'), 
then this is correct 

the config Swatches is correct like point 4 & 5 
In configuration, you need to have in Catalog > Storefront > Swatches per Product defined to 2
In configuration, you need to have in Catalog > Storefront > Show Swatches in Product List defined to Yes

i try whit inline translation, not have option for translate, 

same not translate whit i18n ind
/app/i18n/magento2translation/it_IT
"More","Altro"

I could kindly clarify and where am I wrong?
thanks

**Comment by Karlasa** [comment]
@menphis89 
I have M2.3-dev branch 
created new conf product
created new it_IT language pack 
added phrase into app/i18n/Test/it_IT/it_IT.csv file 
run setup:upgrade 
changed store language into Italy and cleaned cache
works as expected.
<img width="594" alt="Screen Shot 2019-05-22 at 00 45 32" src="https://user-images.githubusercontent.com/5417554/58132802-ee4cec00-7c2a-11e9-8c3e-cbba146b29e3.png">
