### ISSUE TITLE
User agent exception not setting the correct templates for product pages.

### ISSUE THREAD

**Issue by drew7721** [magento/magento2#16074]
### Preconditions
1. Magento 2.2.4
2. PHP 7.1.17
3. Redis 3.2.11
4. Mysql Ver 14.14 Distrib 5.6.39-83.1

### Steps to reproduce
1. Create a parent theme  ex: `parent` (extending or not the blank theme)
2. Create a child theme of `parent` for the desktop version ex: `desktop`
3. Create another child theme of `parent` for mobile devices ex: `mobile`
4. In all themes, create the `Magento_Theme/templates/html/footer.phtml` file with different content.
5. In the Admin section `Content -> Design -> Configuration` edit the _Global Scope_ and set the `desktop` theme as default. Click **Add New User Agent Rule** button and add an exception for `/(iPhone|iPod|iPad|Android)/i` to use the `mobile` theme.
6. In a browser visit the site with "Responsive Design Mode" enabled and change the user agent to one one of the above. **Note** that the categories pages, listings and CMS pages are working fine.
7. Visit a product page. **Note** that the `desktop` footer is loading regardless of the user agent.

### Expected result
What I find strange is that some templates are loading fine. For instance the header.phtml header will load proper one form the `mobile` theme based on the user agent but not the `footer.phtml` or the `absolute_footer.phtml`. 

### Actual result
1. The `footer.phtml` and `absolute_footer.phtml` templates are loading from the `desktop` theme instead of the `mobile` theme regardless of the user agent.

###Notes
For me, this has broken after upgrading to 2.2.4, on 2.1.10 it was working fine and it was loading the proper templates based on the user agent.

**Comment by drew7721** [comment]
Note that this issue seems similar and related to :
- #7503 
- #7710
- #8333
- #14932 
I've tried applying the patch in #8333 but it does not fix the issue.

**Comment by mbernabeu** [comment]
Hi @ drew7721 I have the same problem.

Did you find a solution to the problem?

**Comment by drew7721** [comment]
Nope, for the moment I'm not using the user agent exception anymore. I just set the mobile theme on one language and the desktop one on another language. That way I still get to test both versions without this issue breaking the page.

I don't know when this issue will be addressed. If I do find a solution I will post the update.

**Comment by ghost** [comment]
@drew772, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by angelomaragna** [comment]
From my investigation, it looks like at the moment the theme is changed, the "custom_design_from" and "custom_design_to" are not updated, so the "POST" content, provides invalid dates.

Once the \Magento\Catalog\Helper\Product\View.php initialise the product layout, it fetches the "design settings".
It calls \Magento\Catalog\Model\Design::getDesignSettings() and then \Magento\Catalog\Model\Design::_extractSettings() that is indeed checks against those fields, invalidating the theme because not in the correct date interval.

I guess the solution has to be found in the JS, which is where I am going to look now.

Hope it helps.

Kind regards,
Angelo Maragna

**Comment by AlekosDordas** [comment]
> From my investigation, it looks like at the moment the theme is changed, the "custom_design_from" and "custom_design_to" are not updated, so the "POST" content, provides invalid dates.
> 
> Once the \Magento\Catalog\Helper\Product\View.php initialise the product layout, it fetches the "design settings".
> It calls \Magento\Catalog\Model\Design::getDesignSettings() and then \Magento\Catalog\Model\Design::_extractSettings() that is indeed checks against those fields, invalidating the theme because not in the correct date interval.
> 
> I guess the solution has to be found in the JS, which is where I am going to look now.
> 
> Hope it helps.
> 
> Kind regards,
> Angelo Maragna

Did you continue your investigation? Any news on the issue?

**Workaround** _(until it gets solved)_
I have noticed that the layout updates are working, it only ignores the block template files. So you can (as ugly as it may be) put the user-agent-specific template files in the parent theme (eg. templates/product/view/**mobile**/addtocart.phtml) and use these files in the layout updates of the child user-agent-specific theme. (ie. at your _Vendor_/_child-theme-name_/Magento_Catalog/layout/catalog_product_view.xml)

**Comment by drew7721** [comment]
Ok, this will sound crazy but the issue comes from the block `product_viewed_counter`.

If we remove that block from the catalog_product_view.xml layout it will not have this issue.

A deeper look and we see that the issue comes from the **Ui** module. Not surprised... 🤣 

The guilty class/method is `Magento\Catalog\Ui\DataProvider\Product\Listing\Collector\Image`->`emulateImageCreating`. Still not sure why this emulates image creation (???) and sets the global design theme to the default theme disregarding the current user agent or any design exceptions set previously.

To recap, all blocks on the product page rendered after the counter.phtml template will be using the default theme.

Temp workarounds:
1. remove the counter block if you don't care and have other analytics in place.
2. in the `_beforeToHtml` method of your first block using the wrong theme, change the theme. This requires a bit more work. 

        protected function _beforeToHtml()
        {
            /** @var \Magento\Framework\View\DesignExceptions $designExceptions  */
            $designExceptions = $this->designExceptions; //inject this in the block.
            $theme = $this->designExceptions->getThemeByRequest($this->_request);
            $this->_design->setDesignTheme($theme);
            return parent::_beforeToHtml();
        }

3. comment/remove *line 139 `$this->design->setDefaultDesignTheme();`* in the class `Magento\Catalog\Ui\DataProvider\Product\Listing\Collector\Image`

**Comment by magento-engcom-team** [comment]
Hi @drew7721. Thank you for your report. 
The issue has been fixed in magento/magento2#19124 by @drew7721 in 2.3-develop branch
Related commit(s):
 - [1becee9bb4114318c89f54b45c10b6b60cdc9cee](https://github.com/magento/magento2/commit/1becee9bb4114318c89f54b45c10b6b60cdc9cee)
 - [b8940db9514c672c9e191bbb33172884a524a993](https://github.com/magento/magento2/commit/b8940db9514c672c9e191bbb33172884a524a993)
 - [fd26b94dc1950845a135879937ce7ce0d8f8b8b4](https://github.com/magento/magento2/commit/fd26b94dc1950845a135879937ce7ce0d8f8b8b4)
 - [47e42a969d443715bf483f9e90eabfd2a141c930](https://github.com/magento/magento2/commit/47e42a969d443715bf483f9e90eabfd2a141c930)
 - [4b6100d1e991fc56f7ff9f8e0f0be0db7192328e](https://github.com/magento/magento2/commit/4b6100d1e991fc56f7ff9f8e0f0be0db7192328e)
 - [b8442a15bb1fed7843166bdd4437c009ef03a82f](https://github.com/magento/magento2/commit/b8442a15bb1fed7843166bdd4437c009ef03a82f)

The fix will be available with the upcoming 2.3.1 release.
