### ISSUE TITLE
Wide images in product detail page are misaligned vertically (Fotorama miscalculation)

### ISSUE THREAD

**Issue by leoquijano** [magento/magento2#16073]
Hi,

When using wide images in the product detail page gallery, a vertical margin is introduced by Fotorama, making the image look vertically misaligned with the product name, and with the thumbnails area (if they are configured vertically).

Details below.

### Preconditions

I'm using Magento v2.2.4 installed via Composer, MySQL 5.7.222 on an Ubuntu 16.04.4 LTS, Apache 2.4.18 and PHP v7.1.17. The issue is visible in Firefox 60.0.2 for Ubuntu and it should be visible in Chrome 67.0.3396.62 as well.

### Steps to reproduce

1. Set up a brand new Magento 2.2.4 setup.
2. Add a simple product with several wide test images. I used this one by Kārlis Dambrāns from Flickr and produced one gray-scale and one red-tinted copy so the gallery thumbnails show up.

    https://flic.kr/p/h42mJn

3. Configure the image size in the theme's ```view.xml```'s ```media/images``` for ```Magento_Catalog``` section. For the example image above, the configuration is this:

    ```xml
    <image id="product_page_image_medium" type="image">
      <width>5472</width>
      <height>3648</height>
    </image>
    <image id="product_page_image_medium_no_frame" type="image">
      <width>5472</width>
      <height>3648</height>
      <frame>false</frame>
    </image>
    ```

    My real use case actually requires this setting not to be used (images can have different aspect ratios), but I think this makes it more simple to reproduce.

4. Set thumbnails direction to ```vertical``` in the same ```view.xml``` file:

    ```xml
    <vars module="Magento_Catalog">
        <!-- ... -->
        <var name="gallery">
            <!-- ... -->
            <var name="navdir">vertical</var> <!-- Sliding direction of thumbnails (horizontal/vertical) -->
            <!-- ... -->
        </var>
        <!-- ... -->
    </vars>
    ```

5. Flush cache and visit the product page.

### Expected result

The product image should be aligned vertically with the product name:

![expected result - vertical thumbnails](https://user-images.githubusercontent.com/7789514/41305110-271d4ec2-6e2f-11e8-94dc-cd6349fe3f37.png)

### Actual result

The product image is misaligned:

![actual result - vertical thumbnails](https://user-images.githubusercontent.com/7789514/41305329-d6629eaa-6e2f-11e8-8744-46538d8e48c2.png)

### Commentary

1. This is related to the fact that the image is very wide. However, it can happen with narrower images if we're using a theme that provides less space to the product gallery (for example, if we're using products with tall images, and we shorten the gallery space to 50% of the page or so, we can also run into this issue).

2. I used explicit image sizes in ```view.xml```, but this is more problematic when using images that can have different sizes in a Bootstrap layout or similar in a custom theme. In that case, the media gallery could be set up as 50% width and the images themselves can have different aspect ratios.

3. This might happen too when using horizontal thumbnails if the product image size is not fixed (a must when working with images that can have different aspect ratios or with responsive-aware image sourcing).

4. I've tracked this down to Fotorama making the ```fotorama__stage``` object too wide when setting its width. Since it's being told to keep the aspect ratio, that also makes the height too tall, and since the image is centered vertically, that will add extra margin at the top and the bottom:

    ![fotorama dimensions](https://user-images.githubusercontent.com/7789514/41305573-9a2296ec-6e30-11e8-96e5-02b98f6c47b3.png)

A CSS-only workaround is available [here](https://thiscodemightwork.wordpress.com/2017/07/20/how-to-position-fotorama-in-magento-2-and-avoid-white-space-around-the-image/) and it kinda works by forcing the positioning via CSS, but it doesn't work very well with the magnifier, when enabled.

I think that a proper JS fix probably requires changes to ```lib/web/fotorama/fotorama.js```. I identified two:

In function ```that.resize```, add an adjustment to the width that subtracts the thumbnail width from the stage width (third line below):
```javascript
if (measureIsValid(width)) {
  // ..
  width = measures.W = measures.w = $wrap.width();
  measures.nw = o_nav && numberFromWhatever(opts.navwidth, width) || width;
  width = (opts.navdir === 'vertical' ? width - opts.thumbheight : width);
  // ..
}
```

And in function ```setStagePosition```, replace ```$arrNext.css('right', padding)``` with ```$arrNext.css('right', '')```:
```javascript
if (opts.navdir == 'vertical') {
    var padding = opts.thumbwidth + opts.thumbmargin;

    $stage.css('left', padding);
    $arrNext.css('right', '');
    $fullscreenIcon.css('right', '');
    $wrap.css('width', $wrap.css('width') + padding);
    $stageShaft.css('max-width', $wrap.width() - padding);
} // ...
```

This is probably not an exhaustive fix. I'm fixing my use case, and I'm not using fullscreen, but it can help sort it out.

**EDIT**: updated the example above to fix the fullscreenIcon positioning too.

**Comment by leoquijano** [comment]
Changing the right position of ```fullScreenIcon``` in the ```setStagePosition``` function mentioned above (when using vertical thumbnails), seems to also fix the full screen icon positioning if that feature is enabled:

```javascript
$fullscreenIcon.css('right', '');
```

**Comment by ghost** [comment]
@leoquijano, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by zapateroremendon** [comment]
Hi guys, any news about this? I am facing same issue using M2.2.9 CE. 
Regards,

**Comment by engcom-Charlie** [comment]
Hello @leoquijano 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by ilker-capli** [comment]
Hi Everyonee,

I guess that I have same issue on 2.3.4 Cloud Version.
When using vertical nav on Fotorama, I think that calculating width and height of Stage are wrong.

**Comment by ioweb-gr** [comment]
I also have the same issue on 2.4.3-p1  please reopen @engcom-Charlie 

![image](https://user-images.githubusercontent.com/20220341/150823348-bbea0611-0565-4689-86b5-02760f3823b9.png)

**Comment by MakoWish** [comment]
I am also facing this same issue on 2.4.3.
