### ISSUE TITLE
URLs in sitemap not correct when generated using cron

### ISSUE THREAD

**Issue by mcyrulik** [magento/magento2#16098]
### Preconditions

1.  Magento 2.2.4
2. Apache 2.4
3. document root set to /pub

### Steps to reproduce

1. Add a sitemap with a path of /pub
2. Allow cron to generate the sitemap

### Expected result

1. sitemap.xml urls to sitemap should be https://site.com/pub/sitemap-1-1.xml
2. placeholder image paths should be https://site.com/media/catalog/product/placeholder/default/image.jpg

### Actual result

1. Sitemap.xml urls look like: https://site.com/Documents/WebProjects/www/pub/sitemap1-1.xml
2 placeholder images appear as https://site.com/pub/static/version1528919727/crontab/_view/en_US/Magento_Catalog/images/product/placeholder/.jpg 

If I generate the sitemap through the Magento2 admin, the urls appear as they should.

**Comment by sergey-nechaev** [comment]
1. Same for the 2.2.1
2. Probably related - https://github.com/magento/magento2/issues/9440

**Comment by ghost** [comment]
Hi @mcyrulik I cannot reproduce by yours scenarios steps, see attachments
![selection_035](https://user-images.githubusercontent.com/40756439/43138793-b739d756-8f58-11e8-9921-1f3b5a154a86.png)

**Comment by hostep** [comment]
@engcom-backlog-nazar : this is certainly still reproducible on Magento 2.2.5, I've just tested this again on a clean installation.

Make sure you are generating the sitemap.xml file using the cron system of Magento, by configuring Stores > Configuration > Catalog > XML Sitemap > Generation Settings:
- Enabled => Yes
- Start Time => 1 or 2 minutes from your current time

Then execute `bin/magento cron:run` a couple of times, until the sitemap.xml file gets generated, and then look at the result, you'll see `pub` in those url's.


But this is actually a duplicate of https://github.com/magento/magento2/issues/5321 & https://github.com/magento/magento2/issues/9111


@mcyrulik : as a temporary fix, you can set these configurations, which will work around the problem:
- General > Web > Base URLs > Base URL for User Media Files to `{{unsecure_base_url}}media/`
- General > Web > Base URLs (Secure) > Base URL for User Media Files to `{{secure_base_url}}media/`

But then also be aware of a new bug introduced in 2.2.1: https://github.com/magento/magento2/issues/15972

@engcom-backlog-nazar : would be great if Magento would give this a little bit of a higher priority, since this has been an issue for more then 2 years now ...

**Comment by ghost** [comment]
@mcyrulik closing as duplicate of https://github.com/magento/magento2/issues/5321.
