### ISSUE TITLE
Modules sort order in config.php is being inconsistent when no changes being made

### ISSUE THREAD

**Issue by comdiler** [magento/magento2#16116]
### Preconditions
1. Install any Magento 2.*

### Steps to reproduce
1. Run php bin/magento setup:upgrade
2. Run cp app/etc/config.php app/etc/config.php_t1
3. Run php bin/magento setup:upgrade again
4. Run cp app/etc/config.php app/etc/config.php_t2
5. Run diff app/etc/config.php_t1 app/etc/config.php_t2

### Expected result
1. Files should be the same, because of no changes being made

### Actual result
1. Files are different

**Comment by engcom-backlog-nickolas** [comment]
Hello @comdiler, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by adamzero1** [comment]
We had a similar issue, where the ordering of modules changing was causing us problems, this is the solution we came up with: https://github.com/zero1limited/magento2-PreserveModuleOrderingInProductionMode

**Comment by magento-engcom-team** [comment]
Hi @comdiler. Thank you for your report. 
The issue has been fixed in magento/magento2#21020 by @ajardin in 2.3-develop branch
Related commit(s):
 - [7b9c6058e8462165dd975ab9d005f671d29a5492](https://github.com/magento/magento2/commit/7b9c6058e8462165dd975ab9d005f671d29a5492)
 - [78916b3f987d47febbdf443b8839baca780e9c02](https://github.com/magento/magento2/commit/78916b3f987d47febbdf443b8839baca780e9c02)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @comdiler. Thank you for your report. 
The issue has been fixed in magento/magento2#21423 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [abc3e7c17b11cfc99edc06495a5da47c0c82d9f0](https://github.com/magento/magento2/commit/abc3e7c17b11cfc99edc06495a5da47c0c82d9f0)
 - [4b2c1b47998775c114b443ae3dae78d532727598](https://github.com/magento/magento2/commit/4b2c1b47998775c114b443ae3dae78d532727598)
 - [730987f7405376c7d9cf8964ef61f74a09c2c019](https://github.com/magento/magento2/commit/730987f7405376c7d9cf8964ef61f74a09c2c019)

The fix will be available with the upcoming 2.2.9 release.
