### ISSUE TITLE
Sales Emails Async Sending issue

### ISSUE THREAD

**Issue by mihaifaget** [magento/magento2#16165]
Working on a clean magento 2.2.4.

## Preconditions

Magento Version 2.2.4
## Steps to reproduce

Enable Async sending from Stores->Configuration->Sales->Sales Emails->Asynchronous sending. Create 2(or more) orders. Run cron(twice if you don't already have sales_send_order_emails scheduled)
## Expected result

An order email should be sent for each order in the queue.
## Actual result

Only 1 email is sent for the first order in queue and marks all other orders as sent (email_sent in sales_order table)

**Comment by gwharton** [comment]
I suspect that it might be this commit that broke this in 2.2.4 by @RomaKis, although further checks should be made to be sure.

https://github.com/magento/magento2/commit/f2bfdd941c0c8c6c7c745156d1ce206e38c76820

There were changes made to the email senders to fix issue #11740.

An unintended consequence of this commit is that if multiple emails are sent under the same process, i.e a cron process sending two or more emails at the same time, then the first email will succeed and the send on the remaining emails will fail with an exception.

The exception is triggered here

https://github.com/magento/magento2/blob/cc85cbe1a1220225905440b4b71e144df2540d58/lib/internal/Magento/Framework/Mail/Template/TransportBuilderByStore.php#L50

After this change, new in 2.2.4, the message object is now static, and not cleared after each email is sent. The exception is triggered as the from header is being set on a message object that still has the from header set from the 1st email.

I have several modules that provide massActions to send emails out, e.g resend order email, resend invoice email. These also fail in the same way on 2.2.4 and just send out the first email, if multiple emails are triggered. Reverting the above commit, fixes the issue for me.

If you don't need the fix from #11740 then you can workaround this issue by reverting the above commit.

**Comment by gwharton** [comment]
PR #16461 is awaiting review and will fix this issue.

**Comment by ghost** [comment]
@mihaifaget, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by gwharton** [comment]
Fixed in 2.2-develop
https://github.com/magento/magento2/commit/9a7c9e553b1c9814907105388bffc2e8a91353a5#diff-dfb3ee5a7f863458afea75f5524cd2e5

**Comment by magento-engcom-team** [comment]
Hi @mihaifaget. Thank you for your report. 
The issue has been fixed in magento/magento2#18471 by @gwharton in 2.3-develop branch
Related commit(s):
 - [ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3](https://github.com/magento/magento2/commit/ad50297e7bf4ea39db62f0969579a1ca8eb5f1a3)
 - [e16ff74e4f5f24a4a2530b6aced6ef50032515e0](https://github.com/magento/magento2/commit/e16ff74e4f5f24a4a2530b6aced6ef50032515e0)
 - [621d2cfeaf8e0a15e592cdc001c856385b3cbd83](https://github.com/magento/magento2/commit/621d2cfeaf8e0a15e592cdc001c856385b3cbd83)
 - [b6f9e48289119117df230b6578ac9ff3d69e4996](https://github.com/magento/magento2/commit/b6f9e48289119117df230b6578ac9ff3d69e4996)
 - [0dc85785e522e2be8c72dfeaee7e9f5054195034](https://github.com/magento/magento2/commit/0dc85785e522e2be8c72dfeaee7e9f5054195034)
 - [122019c953037df74ef97245a42b274eae2e6639](https://github.com/magento/magento2/commit/122019c953037df74ef97245a42b274eae2e6639)
 - [193c6c2f6facf7276c1c8858d29ea3b847062ef5](https://github.com/magento/magento2/commit/193c6c2f6facf7276c1c8858d29ea3b847062ef5)
 - [bd0aa57cc837918335015d051f08cf380dc186d0](https://github.com/magento/magento2/commit/bd0aa57cc837918335015d051f08cf380dc186d0)
 - [523b0464966f81f1f01aa13073092bfddf363219](https://github.com/magento/magento2/commit/523b0464966f81f1f01aa13073092bfddf363219)
 - [424929fe9aee1005601cc2c9c7ad0090741be723](https://github.com/magento/magento2/commit/424929fe9aee1005601cc2c9c7ad0090741be723)
 - [c32ca7a0d58cbc57276349b26eb5ecd38451fd2d](https://github.com/magento/magento2/commit/c32ca7a0d58cbc57276349b26eb5ecd38451fd2d)
 - [e39ce7a3f2a7e6ee134cff9a097b7321756c32cf](https://github.com/magento/magento2/commit/e39ce7a3f2a7e6ee134cff9a097b7321756c32cf)
 - [99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31](https://github.com/magento/magento2/commit/99621b32f8c7d3d12f83db7e67f5f1c1ef3e7f31)
 - [f171c9d6ab035439ffb6374ec14dd8d51123dcd2](https://github.com/magento/magento2/commit/f171c9d6ab035439ffb6374ec14dd8d51123dcd2)

The fix will be available with the upcoming 2.3.1 release.
