### ISSUE TITLE
Assigning websites when creating products is not possible

### ISSUE THREAD

**Issue by dwaynebartels** [magento/magento2#16161]
We would like to be able to assign websites when creating a product.
This is not possible in Magento C.E. 2.2.4 and older. 

### Preconditions

1.  Magento ver. 2.2.4
2.  Postman 6.0.10

### Steps to reproduce

1. Create a second website in Magento.

2. Create a product and set extension_attributes, website_ids to 2
![afbeelding](https://user-images.githubusercontent.com/7535994/41466250-bffbf412-70a1-11e8-8229-f082b8079752.png)
3. Create another product in website 1
![afbeelding](https://user-images.githubusercontent.com/7535994/41466369-458d2af6-70a2-11e8-9414-dbbfc454faa9.png)

NOTE: it's doesnt matter if we used storeview all or not. In this case it has the same behavior. I just expected as in #11324 that we should use storeview all when assigning websites. 

### Expected result

1. Create the product in websites with the id's that are given. not to all websites.

### Actual result

1. Product was created in all websites.

**Comment by bansavage** [comment]
I am facing this same issue in _2.1.7_

The known current work around is, after global product creation, to unassign it from websites via command `DELETE /V1/products/{sku}/websites/{websiteId} ` and then reassign the product to websites using
`PUT /V1/products/{sku}/websites body { "productWebsiteLink": { "sku": "string", "website_id": 0 } }`

**Comment by dwaynebartels** [comment]
Hi Bansavage, 

I read your method as follow.       
I create a product. Seeing its assigned to ALL websites. Then I unassign all websites and then assign them to websites I want.     
I tested your method in 2.1.7 and found out that your work around can be more efficient to just unassign the websites that you do not want since its already assigned to all websites.      

Furthermore, because the POST response has no website information (in 2.1.7), I have to retrieve all websites (store/websites) every time I create a product in 2.1.7. 
This is super inefficient.       
Imagine having 4 websites and you only want to assign your product to website 2. a total of 5 calls to proper create your product. 1 to create it, 1 to get all websites and 3 to unassign it from website 1,3 and 4.      🤡

**Comment by dwaynebartels** [comment]
This work around doesn't work in all versions of C.E. Magento2.      
For people reading in to this. I've tested the unassign workaround in 2.2.2, 2.2.4 and 2.1.7. This method works for 2.2.4 and 2.1.7. But unassinging the default website is impossible in 2.2.2.       

also 2.2.4 has the website information in the resonse (extension attributes) so you do not have to make the extra call to get the websites. :wink:

**Comment by engcom-backlog-nickolas** [comment]
@dwaynebartels. thank you for your report. This issue already has been fixed in 2.3-develop.
We've acknowledged the issue and added to our backlog.

**Comment by lewisvoncken** [comment]
@dwaynebartels maybe you can use the following module in the meantime:

https://github.com/experius/Magento-2-Module-Experius-Product-WebsiteIds-Api

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @dwaynebartels The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
