### ISSUE TITLE
Admin tabs order not working properly

### ISSUE THREAD

**Issue by tiagosampaio** [magento/magento2#16174]
When you add 2 or more tabs to admin area, like order view page, by using the method `addTabAfter` and the second new tab is placed after the first new tab the sort order does not work as expected.
### Preconditions

1. Magento 2.2.4
2. PHP 7.1.13
3. MySQL 5.6

### Steps to reproduce

Example:

I created a module which make changes for the `sales_order_view` handle in admin area and in my file `Vendor/Module/view/adminhtml/layout/sales_order_view.xml` I add two new tabs using the method `addTabAfter`:

1. `skyhub_order_data_source`: is placed after the tab `order_history`.
2. `skyhub_invoice_key`: is placed after the `skyhub_order_data_source`.

When accessing the page in admin area the following sequence is rendered:

1. `skyhub_order_data_source`
2. `skyhub_invoice_key`
3. `order_info`
4. `invoices` and all the rest.

It only works if I set the `skyhub_invoice_key` tab to be placed after `order_history`.

### Expected result

<img width="306" alt="screen shot 2018-06-15 at 17 56 35" src="https://user-images.githubusercontent.com/1485260/41489198-7c8ab85c-70c5-11e8-9426-1e16e6d6259b.png">

### Actual result

<img width="308" alt="screen shot 2018-06-15 at 17 54 24" src="https://user-images.githubusercontent.com/1485260/41489142-3c7e16d2-70c5-11e8-9667-73832805f3a8.png">

**Comment by Aranjan21** [comment]
I installed magento2 using this code on virtual box but my url is not opening . I have given correct permission to file as well still its not loading

**Comment by tiagosampaio** [comment]
@Aranjan21 what Magento version are you using for this test?

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your report. 
The issue has been fixed in magento/magento2#16412 by @tiagosampaio in 2.3-develop branch
Related commit(s):
 - [e04b7ca8077fcbd269ad2e2f3515af12f7beaba9](https://github.com/magento/magento2/commit/e04b7ca8077fcbd269ad2e2f3515af12f7beaba9)
 - [447667fccfdcbba86dbbd0e5d58d33bc9d8fc1e7](https://github.com/magento/magento2/commit/447667fccfdcbba86dbbd0e5d58d33bc9d8fc1e7)
 - [0dd4268c9c2a4398d54cf9c71cd5272ffe2f9e73](https://github.com/magento/magento2/commit/0dd4268c9c2a4398d54cf9c71cd5272ffe2f9e73)
 - [9301ccbf4d2c018304bbaad846ca39a8d939373c](https://github.com/magento/magento2/commit/9301ccbf4d2c018304bbaad846ca39a8d939373c)
 - [c2b5c7a586672a2633b746758a7adb124a2e1947](https://github.com/magento/magento2/commit/c2b5c7a586672a2633b746758a7adb124a2e1947)
 - [024384adfb612151477e60af6b2ed2815cc08496](https://github.com/magento/magento2/commit/024384adfb612151477e60af6b2ed2815cc08496)
 - [d35b094fb9152de81a76af474ba62358be854da3](https://github.com/magento/magento2/commit/d35b094fb9152de81a76af474ba62358be854da3)
 - [63cc8e630df033191fd9447e997f7f38b7504be1](https://github.com/magento/magento2/commit/63cc8e630df033191fd9447e997f7f38b7504be1)
 - [fe307c701c47c553825c278df3d6e2fa5530b1a4](https://github.com/magento/magento2/commit/fe307c701c47c553825c278df3d6e2fa5530b1a4)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your report. 
The issue has been fixed in magento/magento2#16175 by @tiagosampaio in 2.2-develop branch
Related commit(s):
 - [e0b26a7bb49871a701cb85062227297575243451](https://github.com/magento/magento2/commit/e0b26a7bb49871a701cb85062227297575243451)
 - [23d616d1913fcc40b8cf7e21c3f9cbbe933f83f6](https://github.com/magento/magento2/commit/23d616d1913fcc40b8cf7e21c3f9cbbe933f83f6)
 - [5f2cf41ae48e907431267fdffe240765514c05d8](https://github.com/magento/magento2/commit/5f2cf41ae48e907431267fdffe240765514c05d8)
 - [3252237dc976a74903910904a8608764746e5d23](https://github.com/magento/magento2/commit/3252237dc976a74903910904a8608764746e5d23)
 - [d136ac1757ee7fba67726979f80fc25e1aec2b6d](https://github.com/magento/magento2/commit/d136ac1757ee7fba67726979f80fc25e1aec2b6d)
 - [633a751e1ea734a6371ec26d6969592f57706ce1](https://github.com/magento/magento2/commit/633a751e1ea734a6371ec26d6969592f57706ce1)
 - [f5efeeef428382567d0f375e19b580cfcd118e25](https://github.com/magento/magento2/commit/f5efeeef428382567d0f375e19b580cfcd118e25)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @tiagosampaio. Thank you for your report. 
The issue has been fixed in magento/magento2#16920 by @mage2pratik in 2.1-develop branch
Related commit(s):
 - [fb93d25e62be47bdc9270ef97fbf75f6a307c933](https://github.com/magento/magento2/commit/fb93d25e62be47bdc9270ef97fbf75f6a307c933)
 - [ff940759095d965932720dadbf628fa11fc36728](https://github.com/magento/magento2/commit/ff940759095d965932720dadbf628fa11fc36728)
 - [9c7687a3d74225a5ab1f63669b48fb62e51d59cc](https://github.com/magento/magento2/commit/9c7687a3d74225a5ab1f63669b48fb62e51d59cc)
 - [1aec473133d1ec2558914aafacde91e6f29ace3c](https://github.com/magento/magento2/commit/1aec473133d1ec2558914aafacde91e6f29ace3c)
 - [4ac09bf0ff225fb89f64b54501d67a01b2bf6a07](https://github.com/magento/magento2/commit/4ac09bf0ff225fb89f64b54501d67a01b2bf6a07)
 - [787ab8bd602b562940f59fe88856763bb07192c5](https://github.com/magento/magento2/commit/787ab8bd602b562940f59fe88856763bb07192c5)
 - [6ca22c56753aaee394aa7f6f2a52344711dd0dd1](https://github.com/magento/magento2/commit/6ca22c56753aaee394aa7f6f2a52344711dd0dd1)

The fix will be available with the upcoming 2.1.15 release.
