### ISSUE TITLE
Argument 1 passed to Magento\Sales\Model\Order\Payment must be an instance of Magento\Framework\DataObject, none given

### ISSUE THREAD

**Issue by Jakhotiya** [magento/magento2#16184]
https://github.com/magento/magento2/blob/cc85cbe1a1220225905440b4b71e144df2540d58/app/code/Magento/Authorizenet/Model/Directpost.php#L820

### Preconditions
Magento2 2.2 dev branch

### Steps to reproduce
1. Setup authorizenet
2. Setup a plugin that uses declineOrder method of the Directpost model
2. Checkout with authorizenet

### Expected result
Order is declined

### Actual result
Uncaught TypeError: Argument 1 passed to Magento\Sales\Model\Order\Payment\Interceptor::void() must be an instance of Magento\Framework\DataObject, none given.

Some points to note are 
1. void method is not part of the interface \Magento\Sales\Api\Data\OrderPaymentInterface 
2. void method is not called with any arguments in declineOrder method of Directpost Model

**Comment by xpoback** [comment]
@Jakhotiya other methods like capture(), authorize(), refund() are not in the interface as well, so this is either deliberate or just not done yet. The actual problem should now be fixed in the PR above.

**Comment by Jakhotiya** [comment]
Thanks @xpoback . But I'm wondering why you passed response object to void method? More importantly how  did you figure out that you have to pass response received by payment gateway.

**Comment by VladimirZaets** [comment]
Hi @Jakhotiya. Thank you for your report. 
The issue has been fixed in magento/magento2#16194 by @xpoback in 2.2-develop branch
Related commit(s):
 - [a7839e29562e7bb3a3afd57caa8bc9f7cd9b9144](https://github.com/magento/magento2/commit/a7839e29562e7bb3a3afd57caa8bc9f7cd9b9144)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @Jakhotiya. Thank you for your report. 
The issue has been fixed in magento/magento2#16801 by @gelanivishal in 2.1-develop branch
Related commit(s):
 - [25a71d51afa648ae7940dcd0b5d633fedaa9953d](https://github.com/magento/magento2/commit/25a71d51afa648ae7940dcd0b5d633fedaa9953d)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @Jakhotiya. Thank you for your report. 
The issue has been fixed in magento/magento2#16603 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [a1f5fa5ea447e6190d2dcfabedd12cc677f263dd](https://github.com/magento/magento2/commit/a1f5fa5ea447e6190d2dcfabedd12cc677f263dd)

The fix will be available with the upcoming 2.3.0 release.
