### ISSUE TITLE
Category image remain after deleted

### ISSUE THREAD

**Issue by vincent2090311** [magento/magento2#16198]
### Preconditions

1. Magento 2.2.4 with sample data
2. nginx 1.8, mysql 5.7, php 7.0

### Steps to reproduce

1. Go to Admin > Catalog > Categories 
2. Upload image via field Category Image under Content section > Save
3. Click on trash icon to remove image > Save

### Expected result

1. Image disappeared in category management + Image under pub\media\catalog\category should be removed

### Actual result

1. Image disappeared in category management + Image under pub\media\catalog\category still remain

**Comment by orlangur** [comment]
@vincent2090311 looks like a duplicate of https://github.com/magento/magento2/issues/13289, isn't it?

**Comment by vincent2090311** [comment]
@orlangur 
#13289 is talking about file in tmp folder. Im talking about images under pub\media\catalog\category (that mean category already saved, image already moved from tmp to pub\media\catalog\category). The issue is when you delete category or remove category image, the image still exist under pub\media\catalog\category

**Comment by ghost** [comment]
Hi @vincent2090311 this issue has been fixed in 2.3.x version
thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by p-bystritsky** [comment]
PR created.

**Comment by ghost** [comment]
Hi @vincent2090311 The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by magento-engcom-team** [comment]
Hi @vincent2090311. Thank you for your report. 
The issue has been fixed in magento/magento2#20178 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - [3b4581c25627735acb63aedec5d0acd234d8c98b](https://github.com/magento/magento2/commit/3b4581c25627735acb63aedec5d0acd234d8c98b)
 - [979e55290165d75d8675ba6bf5ab0923e3470539](https://github.com/magento/magento2/commit/979e55290165d75d8675ba6bf5ab0923e3470539)

The fix will be available with the upcoming 2.2.8 release.
