### ISSUE TITLE
quantity_and_stock_status display result is wrong in product listing(Grid).

### ISSUE THREAD

**Issue by karangar** [magento/magento2#16209]
### Preconditions
I have added product attribute(quantity_and_stock_status) column in catalog product admin grid for the filtering the "In Stock" and "Out of Stock" products list.

1.Magento 2.2.4

### Steps to reproduce

1. Go to Magento 2 admin => Stores => Attributes => Product => Search attribute code "quantity_and_stock_status".
2. Change "Advanced Attribute Properties" settings Scope => "Store view/Global", "Add to Column Options" to "Yes" and set "Use in Filter Options" to "Yes".
3. Now product attribute Quantity(quantity_and_stock_status) will be visible in to the catalog product settings Columns section and checked it to yes.
4. Make Product "Out of Stock" and Save it Flush/Refresh the Cache And also re-indexing it. 
5. Check quantity_and_stock_status display result in product Grid and edit this product and check stock status. 

### Expected result

1. quantity_and_stock_status display result "Out of stock" if product is Stock status "Out of stock" in product Grid.

### Actual result

1. Check product grid Screen shot.
![screenshot-192 168 10 217-2018 06 18-15-48-30](https://user-images.githubusercontent.com/34768419/41532621-661193d2-7315-11e8-92d2-02f7163e9d0a.png)
2. check same product edit page into product is out stock
![screenshot-192 168 10 217-2018 06 18-15-50-12](https://user-images.githubusercontent.com/34768419/41532640-7671a5be-7315-11e8-9599-162cdd9bc23f.png)

**Comment by karangar** [comment]
This issue is already generated in https://github.com/magento/magento2/issues/15201

**Comment by karangar** [comment]
Any update ?

**Comment by ghost** [comment]
Hello @karangar, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sylvainraye** [comment]
I confirm the issue. We have the same by a merchant. Investigation in progress on our side for a fix

**Comment by sylvainraye** [comment]
Here is a statement of my first analyzes regarding "quantity_and_stock_status" attribute:

1) the attribute is not supposed to be used in grid, however that's the only way to have the column "Quantity" (in fact "Stock") and view "In Stock"/"Out of Stock" in grid view
2) the attribute is in fact used internally to set an array of "is_in_stock" and "qty" to be used in product edit form. That's why it's not supposed to be used in grid. Why ? No clue at the moment
3) in Standard in can't be used as a filter because the value "1" is always saved in the database because that's the default value when the attribute is missing while saving a product due to an observer which remove it before save event `\Magento\CatalogInventory\Observer\ProcessInventoryDataObserver`
4) The only way to fix that easily looks like to change the logic of the observer "\Magento\CatalogInventory\Observer\ProcessInventoryDataObserver" and set a 0 or 1 value to the attribute if the product is in stock

I give a try to see if it's working

**Comment by vteofilo** [comment]
This worked for me:

As I have a specific function to update inventory that extends \Magento\CatalogInventory\Model\StockRegistry, I called inside it, but if you use Magento itself you should create a plugin to be called after you have run the function **Magento\CatalogInventory\Model\StockRegistry::updateStockItemBySku()**. At each inventory update, this function updates the **is_in_stock** status of the parent product by adding the items of the child products:

`








    public function syncProductStock(int $productId)
    {
        $product = $this->productFactory->create();
        $product->load($productId);

        $productParent= $this->productFactory->create();
        $productParent->load(
            $this->objectManager->get(\Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable::class)
                ->getParentIdsByChild($productId)
        );

        $childrenIds = array_values(
            $this->objectManager->get(\Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable::class)
                ->getChildrenIds($productParent->getId())[0]
        );
        $sumQuantity = 0;
        foreach ($childrenIds as $childrenId) {
            $productChildren = $this->productFactory->create();
            $productChildren->load($childrenId);
            $sumQuantity += $this->objectManager->get(\Magento\CatalogInventory\Model\StockRegistry::class)
                ->getStockItem($childrenId)->getQty();
        }

        $isInStock = $sumQuantity > 0 ? 1 : 0;
        $product->addAttributeUpdate('quantity_and_stock_status', $this->getStockItem($productId)->getIsInStock(), $product->getStoreId());
        $productParent->addAttributeUpdate('quantity_and_stock_status', $isInStock, $product->getStoreId());

        $parentStockItem = $this->getStockItem($productParent->getId());
        $parentStockItem->setIsInStock($isInStock);
        $this->stockItemRepository->save($parentStockItem);
    }`

Hope this helps! Thank you!

**Comment by krotus** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
@krotus thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @krotus. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Bravo** [comment]
HI @karangar,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.


<img width="1107" alt="Screenshot 2024-05-06 at 12 11 13" src="https://github.com/magento/magento2/assets/51680745/915905d9-2604-4a67-bc0f-e8425381a469">



<img width="1342" alt="Screenshot 2024-05-06 at 12 11 46" src="https://github.com/magento/magento2/assets/51680745/66bcc190-7ed4-44f1-acd2-a559e55baac5">



Hence We are closing this issue.

Thanks.
