### ISSUE TITLE
Integration test ProcessCronQueueObserverTest.php succeeds regardless of magento config fixture

### ISSUE THREAD

**Issue by evktalo** [magento/magento2#16243]
### Preconditions

1. Magento 2.2.3 installation
2. Integration test database set up

### Steps to reproduce

1. Remove config fixture from ProcessCronQueueObserverTest::testDispatchScheduled
2. In dev/tests/integration run
``../../../vendor/bin/phpunit testsuite/Magento/Cron/Observer/ProcessCronQueueObserverTest.php``

### Expected result

1. testDispatchScheduled fails 

### Actual result

1. testDispatchScheduled passes

### Additional notes

https://github.com/magento/magento2/blob/a328a6b4a3fb2a0a7a6a0fc8c219e68a88b03227/dev/tests/integration/testsuite/Magento/Cron/Observer/ProcessCronQueueObserverTest.php#L30

The integration tests succeeds regardless if the config fixture is there or not.

It seems like the fixture should be removed, if it has no effect on the result of the test.

On the other hand the test should perhaps filter the collection by the job code of the configured cron like below:

``$collection->addFieldToFilter('job_code', 'catalog_product_alert');``

When this is added to the test, it fails, so I'm not quite sure if that is correct.

**Comment by kkrieger85** [comment]
Hi @evktalo please pay attention to [Issue reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and [Issue Template](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#issue-template)

**Comment by VladimirZaets** [comment]
Hi @evktalo. Thank you for your report. 
The issue has been fixed in magento/magento2#16253 by @evktalo in 2.3-develop branch
Related commit(s):
 - [5021532070bc6ac6502c5687b48914d536262686](https://github.com/magento/magento2/commit/5021532070bc6ac6502c5687b48914d536262686)

The fix will be available with the upcoming 2.3.0 release.

**Comment by ghost** [comment]
@evktalo, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @evktalo. Thank you for your report. 
The issue has been fixed in magento/magento2#17192 by @gelanivishal in 2.1-develop branch
Related commit(s):
 - [1ed15d2b78df252a37d643bd59ea1a8bd61a3fff](https://github.com/magento/magento2/commit/1ed15d2b78df252a37d643bd59ea1a8bd61a3fff)

The fix will be available with the upcoming 2.1.15 release.

**Comment by sidolov** [comment]
Hi @evktalo. Thank you for your report. 
The issue has been fixed in magento/magento2#17191 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [ce5ac6e0c578900a2e9f92997a635d72c9643919](https://github.com/magento/magento2/commit/ce5ac6e0c578900a2e9f92997a635d72c9643919)

The fix will be available with the upcoming 2.2.7 release.
