### ISSUE TITLE
Inline ( database ) translations not populating js-translations.json with translations

### ISSUE THREAD

**Issue by archonkulis** [magento/magento2#16284]
### Preconditions
1. Magento 2.2.4

### Steps to reproduce

1. Add new store with e.g. spanish language
2. Create some inline translations in the checkout with developer mode for the spanish store
3. bin/magento s:s:d --theme="Your/theme" es_ES

### Expected result

1. `pub/static/frontend/Your/theme/es_ES/js-translation.json` should be filled with translations

### Actual result

1. `pub/static/frontend/Your/theme/es_ES/js-translation.json` is empty or contains only translations from csv files

### My observations

In short - When you translate inline on different store, it adds the `store_id` correctly to `translation` table ( in my case the store id was 6 ). However, later, when you do `bin/magento s:s:d --theme="Your/theme" es_ES` then it tries to find the translation for locale in different store id, in my case it was 1.

When you run `bin/magento s:s:d --theme="Your/theme" es_ES` then it tries to find the values in the database with in-correct store id and that's why it can't find the translations.

In the function `vendor/magento/module-translation/Model/ResourceModel/Translate.php::getTranslationArray(....)`

The following:

`        if ($storeId === null) {
            $storeId = $this->getStoreId();
        }`

Returns the store id as 1. But, in database the store_id saved to locale = 'es_ES' is 6.

So, either it should find correct store id when running `bin/magento s:s:d` or it should fill the store id correctly when creating inline translations.

And no, this is not a duplicate as I couldn't find similar errors ( the ones I found wasn't related to inline translations ).

**Comment by ghost** [comment]
Hello @archonkulis, thank you for your report.
This issue is already fixed in Magento 2.3.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @archonkulis The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
