### ISSUE TITLE
Problems While Creating Product Attribute With InstallData

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16285]
### Preconditions

1. PHP version: 7.1.16 ,Apache/2.4.23
2. Magento CE Fresh 2.2.4

### Steps to reproduce

1.  Preapare InstallData for Product Attribute.
```
$eavSetup->addAttribute(
    \Magento\Catalog\Model\Product::ENTITY,
    'brands',
    [
        'type' => 'text',
        'backend' => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
        'frontend' => '',
        'label' => 'Brands',
        'input' => 'select',
        'group' => 'General',
        'class' => 'brands',
        'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
        'visible' => true,
        'required' => false,
        'user_defined' => true,
        'default' => '1',
        'searchable' => false,
        'filterable' => false,
        'comparable' => false,
        'visible_on_front' => false,
        'is_used_for_promo_rules' => true,
        'used_in_product_listing' => true,
        'unique' => false,
    ]
);
```

### Expected result

1.  After Execute `setup:upgrade` module registered both attribute created but only `used_in_product_listing` set to true for both.  `is_used_for_promo_rules` is not set. 

### Actual result

1. `is_used_for_promo_rules` and `used_in_product_listing` both needs to be set True.

**Comment by engcom-backlog-nickolas** [comment]
Hello @TBSMage, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
Hello Any update on this ? I'm having same problems with M2.2.5. Any workaround ?

**Comment by Wohlie** [comment]
Hi, I think this issue is invalid and does not exist.

`$eavSetup->addAttribute` performes a mapping from the given array keys to the db field names (compare [implementation #1](https://github.com/magento/magento2/blob/35b736dbc57b2aa4a95efa48a17e8e20ac9f663f/app/code/Magento/Eav/Setup/EavSetup.php#L825), [implementation #2](https://github.com/magento/magento2/blob/35b736dbc57b2aa4a95efa48a17e8e20ac9f663f/app/code/Magento/Catalog/Model/ResourceModel/Setup/PropertyMapper.php#L44))

For `addAttribute` you need to use `used_for_promo_rules` and not `is_used_for_promo_rules`.

If you use `$eavSetup->updateAttribute` you must provide the db field names like `is_used_for_promo_rules`. In my opinion you should always use `addAttribute` even for updating existing attributes because magento take care of already existing attributes (compare [implementation](https://github.com/magento/magento2/blob/35b736dbc57b2aa4a95efa48a17e8e20ac9f663f/app/code/Magento/Eav/Setup/EavSetup.php#L832)).

**Comment by magento-engcom-team** [comment]
@ghost, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
