### ISSUE TITLE
JS files located outside the web/js directory

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#16302]
### Summary

Some JS files are direct children of `web` rather than `web/js`. This does not follow instructions from the [dev docs](https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/custom_js.html) thus is confusing.

> Place the custom component source file in one of the following locations:
>  Your theme JS files: /web/js or /_/web/js
> Your module view JS files: <module_dir>/view/frontend/web/js

There are more instances of this:

- `vendor/magento/module-payment/view/frontend/web/transparent.js`
- `vendor/magento/module-payment/view/frontend/web/cc-type.js`
- `vendor/magento/module-search/view/frontend/web/form-mini.js`
- `vendor/magento/module-sales/view/frontend/web/gift-message.js`

There are more but I'm pushed for time at the minute.

### Preconditions
1. Magento 2.2 - This is irrelevant as it appears in all versions

### Steps to reproduce
1. Go to https://github.com/magento/magento2/tree/2.2-develop/app/code/Magento/Captcha/view/frontend/web and look where `captcha.js` and `onepage.js` is located.

### Expected result
1. JS files to be inside `web/js` as per the dev docs.

### Actual result
1. JS files are direct children of `web`, this is inconsistent with the dev docs.

This is confusing as the dev docs instructs developers to use certain locations yet the core does not follow this, either the files should be relocated to be inside `web/js` or the dev docs should be updated. Unless there is a valid reason why the files are outside `web/js`?

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting with 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by hitesh-wagento** [comment]
@magento-engcom-team give me {Magento 2.2.0} instance

**Comment by ghost** [comment]
@BenSpace48, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by hitesh-wagento** [comment]
Hi @BenSpace48

Do you need below files in `web/js` folder and `captcha.js` and `onepage.js` ?

- `vendor/magento/module-payment/view/frontend/web/transparent.js`
- `vendor/magento/module-payment/view/frontend/web/cc-type.js`
- `vendor/magento/module-search/view/frontend/web/form-mini.js`
- `vendor/magento/module-sales/view/frontend/web/gift-message.js`

**Comment by BenGlassAtlas** [comment]
Hi @hitesh-wagento 

Yeah for consistency with the dev docs and other files, and general best practices. 

I think there are more files than the ones I've listed, they were just the first few I discovered whilst looking into it.

**Comment by hitesh-wagento** [comment]
Ok Thanks @BenSpace48 

I am working on this PR

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48. Thank you for your report. 
The issue has been fixed in magento/magento2#16582 by @hitesh-wagento in 2.2-develop branch
Related commit(s):
 - [8653ba1fbe29acc37505b85adce1463d70e9cdf1](https://github.com/magento/magento2/commit/8653ba1fbe29acc37505b85adce1463d70e9cdf1)
 - [e0b09fdc6db266015b3296fe8a272db7c3ba7d3e](https://github.com/magento/magento2/commit/e0b09fdc6db266015b3296fe8a272db7c3ba7d3e)
 - [45306b4dd8c7b4ac3ca407aae88a2213a40c8822](https://github.com/magento/magento2/commit/45306b4dd8c7b4ac3ca407aae88a2213a40c8822)
 - [9b719bed71f8477dbb22e2e559c391d8a8fee3cb](https://github.com/magento/magento2/commit/9b719bed71f8477dbb22e2e559c391d8a8fee3cb)
 - [c74f9e210a554f9462d8bfaa9e34b46e5542b337](https://github.com/magento/magento2/commit/c74f9e210a554f9462d8bfaa9e34b46e5542b337)
 - [6ad9ea419bd09ffc5b17bd4342f432958ba395ff](https://github.com/magento/magento2/commit/6ad9ea419bd09ffc5b17bd4342f432958ba395ff)
 - [e2558dc6c0729c6f99cb0688048048a1a3483baf](https://github.com/magento/magento2/commit/e2558dc6c0729c6f99cb0688048048a1a3483baf)
 - [230145092ca1b385148fee7867ef927780674c50](https://github.com/magento/magento2/commit/230145092ca1b385148fee7867ef927780674c50)

The fix will be available with the upcoming 2.2.7 release.

**Comment by BenSpace48** [comment]
@magento-engcom-team give me 2.1.7 instance

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by BenGlassAtlas** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48, here is your [Magento instance](https://i-16302-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16302-2-2-5.engcom.dev.magento.com/admin](https://i-16302-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ishakhsuvarov** [comment]
Hi @BenSpace48. Thank you for your report. 
The issue has been fixed in magento/magento2#16708 by @hitesh-wagento in 2.3-develop branch
Related commit(s):
 - [0ce439b1ecc2906dd840f37989c7c8ccf84dc6bf](https://github.com/magento/magento2/commit/0ce439b1ecc2906dd840f37989c7c8ccf84dc6bf)
 - [83a2966916faf1a5007870269fb2402cfa449da3](https://github.com/magento/magento2/commit/83a2966916faf1a5007870269fb2402cfa449da3)
 - [d41ef751c09c86f803c417b0fd4dbbe80da4a01e](https://github.com/magento/magento2/commit/d41ef751c09c86f803c417b0fd4dbbe80da4a01e)
 - [1fddf26e69f083918fdc7951ef08ab530285d4d7](https://github.com/magento/magento2/commit/1fddf26e69f083918fdc7951ef08ab530285d4d7)
 - [6783664fccd8e1866d70461dd189dbd320f1fbc8](https://github.com/magento/magento2/commit/6783664fccd8e1866d70461dd189dbd320f1fbc8)

The fix will be available with the upcoming 2.3.0 release.

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48. Thank you for your report. 
The issue has been fixed in magento/magento2#19583 by @rbayet in 2.3-develop branch
Related commit(s):
 - [f38f09f879a7495772e5a3b2fc2445731ae2cb5b](https://github.com/magento/magento2/commit/f38f09f879a7495772e5a3b2fc2445731ae2cb5b)

The fix will be available with the upcoming 2.3.1 release.
