### ISSUE TITLE
Not possible to override styles.css

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#16314]
### Preconditions

LAMP
Magento 2.2.4

### Steps to reproduce

Install Magento, add custom CSS.

### Expected result

Override contact form CSS.

### Actual result

I can not override styles.css sheet because my custom CSS loads first.

This makes me unable to customize the contact form CSS for example because styles.css loads last and overrides my custom CSS.

```
app/design/frontend/Vendor/theme/Magento_Theme/layout/default_head_blocks.xml

<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
  <head>
    <css src="css/custom-m.css" />
    <css src="css/custom-l.css" media="screen and (min-width: 768px)" />
  </head>
</page>
```
Please advice.

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Zyles do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Zyles thank you for your report.
You need to ovveride .less files style. web/css/source/_forms.less in this case i override the contact form.

**Comment by Zyles** [comment]
Ok I also solved it with `!important` spam in my CSS files.
