### ISSUE TITLE
Product save with onthefly index ignores website assignments

### ISSUE THREAD

**Issue by mvenghaus** [magento/magento2#16315]
### Preconditions

1. Magento 2.2.4
2. PHP 7.1

### Steps to reproduce

1. create multiple stores
2. enable "onthefly" index mode & flat tables
3. remove all website assignments from a product
4. save the product

### Expected result

1. product should not show in any flat table

### Actual result

1. product is found in all flat tables

**Comment by magento-engcom-team** [comment]
Hi @mvenghaus. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mvenghaus do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@mvenghaus, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @mvenghaus. Thank you for your report. 
The issue has been fixed in magento/magento2#27365 by @tna274 in 2.4-develop branch
Related commit(s):
 - [fe026486e1c7d64c31ddc6f017c4f7df20b48e56](https://github.com/magento/magento2/commit/fe026486e1c7d64c31ddc6f017c4f7df20b48e56)
 - [f2a562c9516e5f20662c9bf7ff7b6f7ec72f9cb2](https://github.com/magento/magento2/commit/f2a562c9516e5f20662c9bf7ff7b6f7ec72f9cb2)
 - [34c1818adcc67b063a54887a658b6df4994cf5a0](https://github.com/magento/magento2/commit/34c1818adcc67b063a54887a658b6df4994cf5a0)
 - [52ea21d431b316bdae7b1fc5ba714ff9a1b7c754](https://github.com/magento/magento2/commit/52ea21d431b316bdae7b1fc5ba714ff9a1b7c754)
 - [d0f356e9fce5b876fe7708f1c5a0b2dd6c017728](https://github.com/magento/magento2/commit/d0f356e9fce5b876fe7708f1c5a0b2dd6c017728)
 - [b04a21c70aa57f58b350dbad250da77e4269b0b4](https://github.com/magento/magento2/commit/b04a21c70aa57f58b350dbad250da77e4269b0b4)

The fix will be available with the upcoming 2.4.0 release.
