### ISSUE TITLE
Improvement: REST-API - Add List of Order Status Node

### ISSUE THREAD

**Issue by DanielKarr87** [magento/magento2#16324]
According to: [https://magento.stackexchange.com/questions/150492/magento-2-how-to-get-all-order-status](url) there isn't a possibility to get all Order Status that were available inside the Shop.

For ERP Systems which would change the status from "open" to "complete" or a custom status it is necessary to know how the internal name of the status is setup inside the Shop to update an order from status A to status B.

**For example:**

- Inside Shop A there is a custom status **"parts supplied"**, the _internal status_name_ of this custom status is set to **"custom_partssupplied"**. 
- The Order was **read** with Status **"open"**. 
- After work is done in the ERP-System, this custom status "parts supplied" should be applied to this Order
- Over REST-API there is a possibility to update "status" with a string -> namely the _internal status_name_ in this example **"custom_partssupplied"**

**Problem now is:**
- How to get the List of all status over REST-API without changing anything to the shop (changing php files)?

Most ERP-Systems using a proprietary connector, tool, php-toolbox to do this job, but that is against nature of an api: _use the api, don't work around the api._

**A Node to get all status from shop is needed to get this task done, but this Node is missing.**

**Comment by magento-engcom-team** [comment]
Hi @DanielKarr87. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@DanielKarr87 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @DanielKarr87. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/74
