### ISSUE TITLE
How to do bulk update of PRICE in shopify REST API

### ISSUE THREAD

**Issue by ashishdiff** [magento/magento2#16328]
Update of single product  price can be update with VARIANT ID.
I had used this URL for single product update-
urlData="https://"+apikey+":"+password+"@"+storename+".myshopify.com/admin/variants/"+{{variantId}}+".json".
How can i do bulk update of PRICE using REST API.
Provide us the procedure to do BULK update of PRICE using  shopify REST API.

**Comment by magento-engcom-team** [comment]
Hi @ashishdiff. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ashishdiff do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@ashishdiff Magento 2 can definitely do it BUT first you should migrate from Shopify to Magento :)

**Comment by ishakhsuvarov** [comment]
@ashishdiff Closing ticket now, as issue doesn't seem to be related to Magento
