### ISSUE TITLE
Version with disabled cookie layer gets cached on Varnish for all users

### ISSUE THREAD

**Issue by krisdante** [magento/magento2#16336]
If the first request to the server will be from somebody who already accepted the layer then varnish will cache the page variant without cookie layer. Subsequent visits from new users will not show the cookie layer for that page.

### Preconditions

1. Magento 2.2.4
2. Varnish Server
3. Cookie Restriction Mode enabled.

### Steps to reproduce

1.  Open Magento page that will be cached by Varnish
2. Accept Cookie layer
3. Clear Magento cache
4. Reload the page
5. At this point, Magento will cache version without cookie layer on Varnish
6. Open Magento in Incognito mode
7. No Cookie layer

### Expected result

1. There is always a cookie layer shown for users who did not accept cookies layer

### Actual result

1. When version for a user that already accepted Cookie layer will be the first one who generates cache on Varnish - all other users have this cookie layer hidden.

**Comment by magento-engcom-team** [comment]
Hi @krisdante. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@krisdante do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@krisdante, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![1](https://user-images.githubusercontent.com/40756187/43263000-ae6facd4-90ea-11e8-9725-f0b47e948f32.gif)
