### ISSUE TITLE
Unable to create a customer account from the backend after Website Restriction is enabled. Bug in EE 2.2.4

### ISSUE THREAD

**Issue by nacho2706** [magento/magento2#16346]
After enable the Website Restriction module I am unable to create a customer account from the backend. This functionality is working properly in the frontend but I guess as an Administrator user I should be able to create customer accounts.

### Preconditions
1. Magento Commerce 2.2.4
2. PHP 7.1.13

### Steps to reproduce

1. Go to Stores -> Configuration -> B2B Features
2. Set "Enable Company" to "Yes"
3. Go to Stores -> Configuration -> General -> Website Restrictions
4. Set "Access Restriction" to "Yes"
5. Set "Restriction Mode" to "Private Sales: Login Only"
6.  Go to Customers -> All Customers
7. Click on "Add New Customer"
7. Fill in the required fields like "Group", "First Name", "Last Name" and "Email"
8. Click on "Save Customer"

In the WebsiteRestriction module there's a "beforeCreateAccount" plugin which doesn't allow to create a new customer even from the backend. (File: vendor/magento/module-website-restriction/Plugin/Model/AccountManagement.php)

### Expected result

1. Customer should be created properly

### Actual result

1. Magento is throwing an exception: "Can not register new customer due to restrictions are enabled."

**Comment by magento-engcom-team** [comment]
Hi @nacho2706. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nacho2706 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nacho2706** [comment]
Yes, I do. I was able to reproduce it on vanilla Magento instance. 
Let me know if you need anything else.

**Comment by orlangur** [comment]
@nacho2706,

> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.
