### ISSUE TITLE
Translations stop working from CE 2.2.3 -> 2.2.4

### ISSUE THREAD

**Issue by bobemoe** [magento/magento2#16358]
### Preconditions
Linux dev 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

nginx version: nginx/1.12.2

PHP 7.0.30-1-dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-1-dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

mysql  Ver 15.1 Distrib 10.0.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

We have 4 store views with 4 translation (da_DK.csv  de_DE.csv  en_GB.csv  nn_NO.csv) files placed in:
vendor/mageplaza/magento-2-COUNTRY-language-pack/xx_YY.csv
app/design/frontend/MY_VENDOR/MY_PACKAGE/i18n/xx_YY.csv

### Steps to reproduce
1. Take a 2.2.3 site with multiple store views with working translation packs.
2. Composer upgrade to 2.2.4
3. magento setup:upgrade && magento deploy:mode:set production

### Expected result
Switching store view uses translations from language packs and my custom theme to translate the text in the usual places.  (e.g. Cookie message, currency switcher, field validation)

### Actual result
No matter which store view is loaded, all translatable text remains in English.

NOTE: Product and CMS content is translated, but this is because its not a translatable string associated to a lang code, its is content associated with a store view, which is still working as normal.

**Comment by magento-engcom-team** [comment]
Hi @bobemoe. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@bobemoe do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by bobemoe** [comment]
Unable to reproduce on vanilla install. I will check my extensions/configuration and reopen if it turns out to be core.

**Comment by hostep** [comment]
@bobemoe: if you are using multiple websites, you might run against a new bug in 2.2.4 indeed, it was already reported before in https://github.com/magento/magento2/issues/15205, so let's leave this one closed.

**Comment by bobemoe** [comment]
@hostep, thanks for the thought, but I'm not using multiple websites so I'm not sure its the same bug.  

However, I can confirm the original issue is now fixed in 2.2.5.
