### ISSUE TITLE
Layered Navigation Url not rewrite on home page

### ISSUE THREAD

**Issue by minhluan259** [magento/magento2#16362]
### Preconditions

1. Magento 2.4-develop
2.  PHP 7.3

Have 2 simple products assigned to a category (Id = 3 in my case);
### Steps to reproduce

1.  Go to STORES > Configuration > General > Web > Default Pages and set **Default Web URL** to `catalog/category/view/id/3`
2. Reindex data, flush cache;
3. Go to frontend -> Homepage;

### Expected result

Category showing on home page.
Layered Navigation Url should be
`http://local.test/consumer-electric.html?manufacturer=15`

### Actual result

Category showing on home page.
Layered Navigation Url not rewrite
`http://local.test/catalog/category/view/id/3/?manufacturer=15`

**Comment by magento-engcom-team** [comment]
Hi @minhluan259. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@minhluan259 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @minhluan259 thank you for your report.
we've acknowledged the issue and added to our backlog.

**Comment by ihor-sviziev** [comment]
Hi @minhluan259 @pusachev ,
Could you describe use-case when you need to setup category as homepage? It really looks very-very strange.

Thank you!

**Comment by pusachev** [comment]
Hi @ihor-sviziev I get this ticket on contribution day in Kyiv and think that this ticket was processed and approved. Please let me know when I can continue working on this ticket. 

Best Regards,
Pavel.

**Comment by ihor-sviziev** [comment]
Hi @pusachev,
I do understand that this is an issue, but not all issues need to fix, so if there any use case that could cause this issue - ok, lets fix it, if no - lets not fix it at all and make code more clear and simpler.

Example: In theory we could make homepage - contact us page, but no one will do that, there is no real use case for it

**Comment by pusachev** [comment]
Hi @ihor-sviziev .

Ok not a problem. If this not clear use case maybe make sense change "Default Web URL" from  text -> select with data provider that provide only available pages that admin can selected for default homepage. If needed I can create PR for this. 

Best Regards,
Pavel

**Comment by ihor-sviziev** [comment]
@pusachev  I would keep existing functionality as is because it still have some room for customization without need to develop anything

@engcom-Golf are you agree?

**Comment by engcom-Golf** [comment]
@ihor-sviziev yes i agree with you, probably you can create a cms page with widget in it, and add products from category what you want, and then add this page as default. @pusachev @minhluan259  can you describe a valid case when you need category as home page ?

**Comment by pusachev** [comment]
Hi @engcom-Golf, Thank's for reply. 

For my side. Use case:

As an admin I want to set default page as category named "Best Sellers".
As customer I go to website and see homepage as category "Best Sellers" with all category functionality like layered navigation etc. I can filter products using layered navigation. When the category page reloads I can see url rewrite instead of standard url if we have url rewrite for this category turned on.  

Please check with your this with you business analysts. On how much this question is important. As to my opinion it is.

I’ll also remind you that I took this ticket on Magento Contribution Day in Kiev. This ticket was pre-processed and valid. And also I discussed about my PR with @joni-jones.

Please make sure that you set up actual issue to work on as no one wants to waste time and do job  that will not be used in future.

Best Regards,
Pavel

**Comment by pusachev** [comment]
@engcom-backlog-nazar Please assist. 

Thanks

**Comment by ihor-sviziev** [comment]
> @engcom-backlog-nazar Please assist.
> 
> Thanks

Actually @engcom-backlog-nazar  is old account of @engcom-Golf , so this actually one person 😉
That's actually why I asked @engcom-Golf

**Comment by ihor-sviziev** [comment]
Hi @engcom-Golf @VladimirZaets,
If I remember - you were saying that expected behavior should discussed with PO in order to decide if it's real issue or not.

Is there any updates?

**Comment by ihor-sviziev** [comment]
@lenaorobei @slavvka could you add an update, what's the current status?

**Comment by ihor-sviziev** [comment]
Moved PR to "to approve" column in order to get approval from PO:
https://github.com/magento/magento2/pull/24751#issuecomment-590932346

**Comment by misha-kotov** [comment]
Spoke with a few fellow product folks and reached an agreement that we should support the use of the home page as a category page. We can proceed with a fix for this issue.

**Comment by ihor-sviziev** [comment]
@misha-kotov thank you!

**Comment by CarmineDamore78** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CarmineDamore78, here is your [Magento instance](https://i-16362-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-16362-2-4-develop.instances.magento-community.engineering/admin_2db9](https://i-16362-2-4-develop.instances.magento-community.engineering/admin_2db9)
Login: `cfac29e3` Password: `408568091abc`
Instance will be terminated in up to 3 hours.

**Comment by CarmineDamore78** [comment]
Hi @magento-engcom-team 
I'm sorry but I'm not allowed to reindex the instance and I'm not enable to continue the test on me 2.4-develop. I have to stop my test

**Comment by ihor-sviziev** [comment]
> Hi @magento-engcom-team
> I'm sorry but I'm not allowed to reindex the instance and I'm not enable to continue the test on me 2.4-develop. I have to stop my test

Here you can do reindex https://i-16362-2-4-develop.instances.magento-community.engineering/pub/testing/

**Comment by CarmineDamore78** [comment]
Thanks @ihor-sviziev

**Comment by CarmineDamore78** [comment]
Hi @magento-engcom-team 
I confirm the issue on me2.4-develop

**Comment by ihor-sviziev** [comment]
> Hi @magento-engcom-team
> I confirm the issue on me2.4-develop

Thank you! Just added label

**Comment by Bartlomiejsz** [comment]
@magento I am working on this

**Comment by Bartlomiejsz** [comment]
Hi @ihor-sviziev, got a question. I got fix for that issue, but I'm wondering, if some category page is being used as homepage, should that in result generate urls in layered navigation as `http://local.test/consumer-electric.html?manufacturer=15`, or rather as `http://local.test/?manufacturer=15` to stay on homepage after using filters. Second one makes more sense to me, but it's different approach than mentioned in this ticket, and both ways are possible.
What do you think?

**Comment by ihor-sviziev** [comment]
> Hi @ihor-sviziev, got a question. I got fix for that issue, but I'm wondering, if some category page is being used as homepage, should that in result generate urls in layered navigation as `http://local.test/consumer-electric.html?manufacturer=15`, or rather as `http://local.test/?manufacturer=15` to stay on homepage after using filters? Second one makes more sense to me, but it's different approach than mentioned in this ticket, and both ways are possible.
> What do you think?

As for me both options are correct. As for me `http://local.test/consumer-electric.html?manufacturer=15` is better option because we'll have only one page url with applied filters instead of `http://local.test/consumer-electric.html?manufacturer=15` and `http://local.test/?manufacturer=15`. But personally I don't for `http://local.test/?manufacturer=15`, for instance if it's easier.

**Comment by Bartlomiejsz** [comment]
@ihor-sviziev thank you, I'll go with second option then. I looked into this PR and I don't think such complex solution is needed. I found fix with only few lines. I will create some MFTF tests and create PR then, so you could review :)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37423` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment]
Hi @minhluan259 ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots

**Steps to reproduce**
1.. Go to STORES > Configuration > General > Web > Default Pages and set Default Web URL to catalog/category/view/id/3
![image](https://github.com/user-attachments/assets/afc2262d-f801-4892-89dc-98d86271ff3a)
2. Reindex data, flush cache;
3. Go to frontend -> Homepage;
![image](https://github.com/user-attachments/assets/f81d347c-cf8a-4556-b869-a99d03d11f6d)
Observe URL is loading category page without displaying the id in URL. Frontend URL is displaying as expected.

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.
Thanks.

**Comment by Bartlomiejsz** [comment]
Hi @engcom-Delta, did you check if layered navigation works correctly on your instance? The issue was not related to homepage itself, but to url generated from layered navigation filters

![image](https://github.com/user-attachments/assets/45c67e19-7e39-4b6a-823e-869d92b4f316)
