### ISSUE TITLE
Error message: Please check the shipping address information. Invalid value of "95" provided for the regionId field.

### ISSUE THREAD

**Issue by matin73** [magento/magento2#16368]
### Preconditions

1. Magento 2.2.3 and upgrade to Magento 2.2.4
2. PHP 7.0.30
3. MySQL libmysql - mysqlnd 5.0.12-dev and also 10.0.32-MariaDB-0+deb8u1

### Steps to reproduce
1. Install Magento 2.2.3 and install Firegento 2 via composer. then upgrade to Magento 2.2.4
2. Set configuration for "Province/Region" to "not necessary"; Allowed countries Austria and Germany; Default country Austria (also shipping origin and so on - it is austrian shop); Payment methods "Bank Transfer Method" and "Cash on Delivery"
3. Buy any product and go to checkout. Change country to Germany and select payment "Bank Transfer Method" or "Cash on Delivery".

### Expected result
1. Checkout should work

### Actual result
1. Checkout error message "Error message: Please check the shipping address information. Invalid value of "95" provided for the regionId field."

Value "95" is written by Firegento Extension to table "core_config_data" and row "path" -> tax/defaults/region and "value" 95.

Magento writes error message in "vendor/magento/module-customer/Model/Address/AbstractAddress.php" liine 652ff
$errors[] = __( 'Invalid value of "%value" provided for the %fieldName field.', [ 'fieldName' => 'regionId', 'value' => htmlspecialchars($regionId) ] );

region id is set by function " public function getRegionId()" on line 400ff

I do not knwo why magento is fetching value of "tax/defaults/region" and throwing error. Maybe it is concerning this bug magento/magento2#14052. This value in table is not for shipping - it is only for TAX

**Comment by magento-engcom-team** [comment]
Hi @matin73. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@matin73 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by matin73** [comment]
@matin73 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
•	[x ] yes
•	[ ] no

**Comment by matin73** [comment]
The following code was added in vendor/magento/module-customer/Model/Address/AbstractAddress.php in Magento 2.2.4 in and causes issue - if I rename path value from tax/defaults/region to tax/defaults/rxegion it works. so magento is somehow fetching value because of name "region" in the path value ...:
`$countryId = $this->getCountryId();
        if (!\Zend_Validate::is($countryId, 'NotEmpty')) {
            $errors[] = __('%fieldName is a required field.', ['fieldName' => 'countryId']);
        } else {
            //Checking if such country exists.
            if (!in_array($countryId, $this->_directoryData->getCountryCollection()->getAllIds(), true)) {
                $errors[] = __(
                    'Invalid value of "%value" provided for the %fieldName field.',
                    [
                        'fieldName' => 'countryId',
                        'value' => htmlspecialchars($countryId)
                    ]
                );
            } else {
                //If country is valid then validating selected region ID.
                $countryModel = $this->getCountryModel();
                $regionCollection = $countryModel->getRegionCollection();
                $region = $this->getRegion();
                $regionId = (string)$this->getRegionId();
                $allowedRegions = $regionCollection->getAllIds();
                $isRegionRequired = $this->_directoryData->isRegionRequired($countryId);
                if ($isRegionRequired && empty($allowedRegions) && !\Zend_Validate::is($region, 'NotEmpty')) {
                    //If region is required for country and country doesn't provide regions list
                    //region must be provided.
                    $errors[] = __('%fieldName is a required field.', ['fieldName' => 'region']);
                } elseif ($allowedRegions && !\Zend_Validate::is($regionId, 'NotEmpty') && $isRegionRequired) {
                    //If country actually has regions and requires you to
                    //select one then it must be selected.
                    $errors[] = __('%fieldName is a required field.', ['fieldName' => 'regionId']);
                } elseif ($regionId && !in_array($regionId, $allowedRegions, true)) {
                    //If a region is selected then checking if it exists.
                    $errors[] = __(
                        'Invalid value of "%value" provided for the %fieldName field.',
                        [
                            'fieldName' => 'regionId',
                            'value' => htmlspecialchars($regionId)
                        ]
                    );
                }
            }
        }`

**Comment by ghost** [comment]
Hi @matin73  thank you for your report.
Maybe the problem in Firegento, looks like the "id" for  regionId field  was wrong value, however we've acknowledged the issue and added to our backlog.

**Comment by matin73** [comment]
@engcom-backlog-nazar thanks for reply. Sure, value was set in database by Firegento Magesetup2. But why is Magento checking "TAX-region" value for shipping address. So this must be a bug in latest Magento, because in 2.2.3 it works well.

**Comment by greenleafmedia** [comment]
I too am getting this for region '95' after upgrading from 2.2.0 to 2.2.5 .  When you go into the admin the State is no select in the address book and the numbers of the States are 1 - 65.

I am not using Firegento.

**Comment by greenleafmedia** [comment]
@martin73 - Is the record you are having issues with related to the state of Wisconsin in any way?

Here's what I'm seeing.  Record 95 in `directory_country_region` has a code of "WI".  This is the same as record 64 for Wisconsin.  I wonder if there was a bug at some point where it was looking things up just by `code`, pulled the wrong one and stored 95 instead of 64.  Perhaps it has been updated to look at the `country_id` as well.

@engcom-backlog-nazar - I'm not sure where the repo for `magento/module-directory` lives to verify.  Do you think something like I describe above may have occurred?  The fix may be something as simple as updating `region_id` to 64 in `sales_order_address` via SQL.  I'm just not sure where all `region_id` is stored.

**Comment by matin73** [comment]
@greenleafmedia - the issue is because of entry in table "core_config_data" and row "path" -> tax/defaults/**region** . Magento is somehow checking if there is any entry with "region" in table. I think there is an sql query with "AND path LIKE '%region%'" or something like this. If I rename value tax/defaults/region to tax/defaults/rxegion  error is not shown. So it must be the word "region" in value

**Comment by MaximilianSchwarz** [comment]
I have the same issue in mamgento 2.2.5. I get the message:
Error message: Please check the shipping address information. Invalid value of "GB" provided for the regionId field.

**Comment by Radosav** [comment]
I have the same issue as @MaximilianSchwarz on 2.2.7
After a bit of debugging I see that in
vendor/magento/module-customer/Model/Address/AbstractAddress.php:627
`if (!in_array($countryId, $countryCollection->getAllIds(), true)) {`

the countryCollection is returning the configuration  from from store ID 1 even though the order was made on Store ID 3.

**Comment by floorz** [comment]
Having this same issue/error on Magento Cloud (Commerce) v2.2.4. The way I was able to reproduce the problem was by doing the following:

1. Use fresh account with no addresses associated
2. Add an item to cart
3. Proceed to checkout
4. On Shipping step, fill out new shipping address form using a country that has regions available (country has regions available if region shows up as select box)
5. Click Next to go to Payment step (Clicking Next parses new address form and sends to rest api to save)
6. Return back to the Shipping step to edit the shipping address
7. Change the shipping address to use a country which does not have regions (region will show up as text field instead of select box)
8. Click Next to go to Payment step
9. Attempt to place order
10. Should receive the "Please check the shipping address information. Invalid value of "X" provided for the regionId field" (X = region_id of original shipping address saved)

**Perspective From MySQL**
In the quote_address table, I noticed that upon executing the process above, the region_id never gets cleared when it's no longer relevant for the changed shipping address

**Perspective From Javascript**
In `vendor/magento/module-checkout/view/frontend/web/js/model/new-customer-address.js` on line 31:

    regionId: regionId || addressData.regionId,

Should be:

    regionId: regionId || addressData.regionId || null,

**Explanation of Change**
In the case that the new shipping address has changed in such a way that region_id isn't used, the first `regionId || addressData.regionId` will resolve to `undefined`. The absence of a value will not update/clear the region_id in the quote_address table as expected.

Adding `|| null` at the end of the line will insure that SOMETHING is passed through to clear out region_id in the table.

**Comment by magento-engcom-team** [comment]
Hi @matin73. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-93620` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @matin73. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-93621` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by DmitryPirvu** [comment]
Hey @magento-engcom-team I am able to reproduce this issue on Magento 2.4.6-p3. Please reopen the ticket.

**Comment by arslandev123** [comment]
Please reopen this ticket its reporducd in our website having a Magento version 2.4.7-p3, when order was placed via API.
"Generic error: Please check the shipping address information. %1"
