### ISSUE TITLE
Cannot Return from One Page Checkout  URGENT

### ISSUE THREAD

**Issue by Dave4777** [magento/magento2#16369]
I presumed that activating a one page checkout meant the feature was built into Magento 2.2.2 
Now that I realize you need to purchase a $200 module to make this happen and currently cannot afford to do this, (SHOULD BE A WARNING !) All purchases I attempt to make are coming up "Cannot add to the shopping cart right now" 

I am freaking out, I have turned feature back to NO for one page checkout, cleared the cache and refreshed everything including my browsers !! What must I do to fix this ?? Screenshot below !
https://www.dropbox.com/s/4q3kxoxa87oq2xe/Screenshot%202018-06-24%2011.58.48.png?dl=0

**Comment by magento-engcom-team** [comment]
Hi @Dave4777. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Dave4777 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Dave4777** [comment]
YES it happens to anyone

**Comment by mhauri** [comment]
Hi @Dave4777 can you try the solution mentioned here: https://github.com/magento/magento2/issues/10821#issuecomment-345449411

`include_path = ".:/var/www/...url.../web/vendor/magento/zendframework1/library"`

**Comment by orlangur** [comment]
@Dave4777,

> YES it happens to anyone

Are you sure you can reproduce this issue on a vanilla Magento 2 installation?

**Comment by ghost** [comment]
Hello, @Dave4777. Unfortunately, we are closing your issue due to malformed report. If you'd like to update it, please reopen the issue and use the [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
