### ISSUE TITLE
Currency caching issue on Luma homepage Magento 2.2.4

### ISSUE THREAD

**Issue by esw-michael** [magento/magento2#16374]
**Summary of the issue**
Currency selection does not work correctly on Luma homepage due to caching issues. If caching is disabled the issue does not exist. The issue also does not exist on product page.

**Preconditions**
Magento Open Source 2.2.4

**Steps to reproduce**
1. Install Magento with Luma store
2. Set base currency as EUR
3. Stores>Configuration>CurrencySetup>Add "Allowed Currencies":  Danish Krone, Euro and Swedish Krona
4. Save config
5. Stores>Currency Rates>Add rate: 7.6958 for DKK and 10.5913 for SEK
6. Save Currency Rates
7. Load homepage
8. Change currency to DKK in Magento currency selector header bar, prices update to DKK on homepage
9. Change currency to SEK in Magento currency selector header bar, prices DO NOT update to SEK and stays on DKK which is incorrect

Turning off caching or changing currency on product page corrects behavior.

**Expected result**
Product prices on homepage should change currency with the selector as it does on the product pages

**Actual result**
Currency selector updates to SEK but product prices on homepage stays as DKK.

**Comment by magento-engcom-team** [comment]
Hi @esw-michael. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@esw-michael do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by esw-michael** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @esw-michael. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @esw-michael, here is your [Magento instance](https://i-16374-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16374-2-2-4.engcom.dev.magento.com/admin](https://i-16374-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by esw-michael** [comment]
I can confirm I was able to reproduce the issue on vanilla Magento instance.

I created a simple product and added to homepage (Content>Pages>Homepage>edit>Content>Insert Widget>Widget Type>Catalog Products List)

After this I followed my original steps to reproduce error:

![image](https://user-images.githubusercontent.com/40562272/41851803-02501bfe-7881-11e8-9768-df467b574de9.png)

**Comment by ghost** [comment]
Hi @esw-michael thank you for your report.
This issue is already fixed in Magento 2.3.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @esw-michael The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
