### ISSUE TITLE
Store scope Widget cannot be added

### ISSUE THREAD

**Issue by etcik1** [magento/magento2#16377]
### Preconditions
1. Magento 2.2
2. Having two websites with two store views (e.g website1 with stores store1 and store2 and website2 with stores store3 and store4)
3. Different websites use same categories.

### Steps to reproduce

1. In Admin go to Catalog -> Categories
2. Choose some category (LEVEL 1)
3. Change storefront from default to some specific one
4. Add menu widget (static block)

### Expected result
1. Menu widget is saved and shown in front end.

### Actual result

1. Menu widget is not shown in front end :

a. If default widget is added, default widget is used
b. if default widget exists, store level widget cannot be removed in admin (menu widget-> reset)

**Comment by magento-engcom-team** [comment]
Hi @etcik1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@etcik1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @etcik1 if you click to Display Settings tab on category edit page and chose  Display Mode to "static block and products", Menu widget is shown in front end.

**Comment by etcik1** [comment]
Hi @engcom-backlog-nazar !

Tested Your solution. Here are results:

Our case: 

1. Two store views in two different languages (English and Arabic)
2a. Widget is added in "All store views" 
2b.Widget is not added in "All store views" 
3. Different widget is added in Arabica store view

2a. 
All store views : display mode : Static block and products
English store view : display mode : Products only
Arabic store view : display mode : Static block and products
FE:
English store shows block
Arabic store not showing block

2b.
Arabic store view : display mode : Static block and products
FE:
English: not showing block
Arabic: not showing block

In both cases Arabic store did not show marketing content (static CMS block)

**Case when it works:**

Widget is added in "All store views" 

FE:
English store shows block
Arabic store shows block

(!) NB! 
English store view : display mode : Products only
Arabic store view : display mode : Static block and products

**Comment by ghost** [comment]
@etcik1 you must add "All Store" view as default or set  store view where you want to display the widget, then on display mode you need choose what to show, for me that works. Did you enable the url options to store view code ? store -> configuration -> general -> web-> url options -> Add Store Code to Urls  
then enter to web browser your code to store view english or arabic  and check the result.

**Comment by etcik1** [comment]
@engcom-backlog-nazar 

Provided screencast: 

https://monosnap.com/file/f9bFiedEVlnt98P6z8QqAkCBPziH1f
