### ISSUE TITLE
Wrong placeholder for password field in the checkout page

### ISSUE THREAD

**Issue by mohitka** [magento/magento2#16378]
### Preconditions
1. **Magento version:** 2.2.3 and 2.2.4
2. **Edition:** Community Edition (Open Source Edition)

### Steps to reproduce
1. Add a product to cart and go to checkout page.
2. Enter any registered email so that the password field appears. 
3. The password field shows the placeholder **Optional**, but when we click on Login button without filling password, it shows the validation error.

### Expected result
1. Since the password is a required field, the placeholder for the password field should not be **Optional**.

### Actual result
1. The password field in the checkout page is currently seeming conflicting in nature. It is showing Optional in a placeholder, but after validation, it is showing validation error **This is a required field.**

![validation-password](https://user-images.githubusercontent.com/40565507/41847166-ac4a6046-7896-11e8-87a5-b4306ee3c504.png)

**Comment by magento-engcom-team** [comment]
Hi @mohitka. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mohitka do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hitesh-wagento** [comment]
Hi @mohitka 

Do you need to change placeholder text **Optional** to **Password** ?

**Comment by mohitka** [comment]
No @hitesh-wagento I was just working on a project and found this issue. I thought it should be reported for the sake of the good experience of Magento.

I hope the issue would be checked and fixed in the future releases of Magento.

**Comment by hitesh-wagento** [comment]
Hi @mohitka

Yes, I will fix this issue and fixed in next release.

The issue is placeholder text **Optional** is wrong, Right ?

**Comment by mohitka** [comment]
Yes @hitesh-wagento

**Comment by hitesh-wagento** [comment]
I am working on this

**Comment by mohitka** [comment]
Okay, thanks. So, should I expect the changes in the next release of Magento?

**Comment by hitesh-wagento** [comment]
Yes, sure

**Comment by magento-engcom-team** [comment]
Hi @mohitka. Thank you for your report. 
The issue has been fixed in magento/magento2#16379 by @hitesh-wagento in 2.2-develop branch
Related commit(s):
 - [4f976e703be9390cf4080050d309dd0510ab11a4](https://github.com/magento/magento2/commit/4f976e703be9390cf4080050d309dd0510ab11a4)
 - [55d1c1573eaa63c4d307e498289da0c812e6ab27](https://github.com/magento/magento2/commit/55d1c1573eaa63c4d307e498289da0c812e6ab27)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @mohitka. Thank you for your report. 
The issue has been fixed in magento/magento2#16521 by @hitesh-wagento in 2.3-develop branch
Related commit(s):
 - [386438dcec0f260fb7135332bbb6eb5f03190d6c](https://github.com/magento/magento2/commit/386438dcec0f260fb7135332bbb6eb5f03190d6c)

The fix will be available with the upcoming 2.3.0 release.

**Comment by mohitka** [comment]
Thanks, @hitesh-wagento for fixing and @magento-engcom-team for the update.

**Comment by VladimirZaets** [comment]
Hi @mohitka. Thank you for your report. 
The issue has been fixed in magento/magento2#16526 by @hitesh-wagento in 2.1-develop branch
Related commit(s):
 - [86ed9df6955ea67631674be285f3e1abde5646ec](https://github.com/magento/magento2/commit/86ed9df6955ea67631674be285f3e1abde5646ec)
 - [b5902e9aa40e6e2d3efaed0124f73770c9e9fb81](https://github.com/magento/magento2/commit/b5902e9aa40e6e2d3efaed0124f73770c9e9fb81)

The fix will be available with the upcoming 2.1.15 release.
