### ISSUE TITLE
Force to show billing address form

### ISSUE THREAD

**Issue by vaso123** [magento/magento2#16380]
### Preconditions
1.  Magento 2.2.x

### Steps to reproduce
1. Add a js file to the checkout page
2. Add subscription on billingaddress
3. Try to rewrite the isAddressDetailsVisible to return false

### Expected result
1. Next page the billing address should shown.

### Actual result
1. The billing-address.js is always overwrite this isAddressDetailsVisible to true, no conditions for this.canUseShippingAddress()

**Comment by magento-engcom-team** [comment]
Hi @vaso123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vaso123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @vaso123, thank you for your report.
We've acknowledged the issue and added to our backlog.
