### ISSUE TITLE
Checkout Onepage from Mac not work?

### ISSUE THREAD

**Issue by samuel20miglia** [magento/magento2#16385]
Json error on onepage checkout if i try to by from mobile device and safari

### Preconditions
1. php
2. v.2.1.4

### Steps to reproduce
1. put anything in cart
2. go to checkout
3. try from mac the loading still in page with an error unterminated string

### Expected result
1. finish the checkout

### Actual result
1. error unterminated string error checkout

**Comment by magento-engcom-team** [comment]
Hi @samuel20miglia. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@samuel20miglia do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by samuel20miglia** [comment]
@magento-engcom-team give me 2.1.4 instance

**Comment by magento-engcom-team** [comment]
Hi @samuel20miglia. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by samuel20miglia** [comment]
ok

**Comment by Leandry** [comment]
Can not reproduce the issue
![2018-06-30_14-35-43](https://user-images.githubusercontent.com/9416636/42124903-824f85fa-7c74-11e8-81dd-5cf49fcfdbb6.png)
