### ISSUE TITLE
Magento2 404 Error Admin 

### ISSUE THREAD

**Issue by chappish** [magento/magento2#16384]
Hi there, 

I just manually installed Magento2 CE on Ubuntu server 18.04 with LAMP via composer, the install went ok and all checks were on green however the link given after installation to access the magento admin page is giving error 404.
    
To resolve this a few people say it should work by changing from the config:

sudo nano /etc/apache2/apache2.conf

From: 

<Directory /var/www/>
     Options Indexes FollowSymLinks
     AllowOverride None
     Require all granted
</Directory>

To

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

but is still not working, another tutorials also say to change the file pub/.htaccess to magento root folder which im guessing it would be located default on:  /var/www/html/magento

However I'm new to Ubuntu commands and I'm unable to  find any suggestions of hwo to do this, would it work with this?

sudo mv /var/www/html/magento/pub/.htaccess /var/www/html/magento

If, I tried it and is not working, any suggestions?? or anyone here who have fixed this issue before??.

I need to mention that when completing the install through composer it was installed on /var/www/html/magento-community-edition/ folder and I moved it up and took out the file "magento-community edition and as a result all the installlation files went to /var/www/html/ so I don't know if that made up the error, how do I fix it?

Thank you for your assistance.

**Comment by magento-engcom-team** [comment]
Hi @chappish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@chappish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mhauri** [comment]
Hi @chappish maybe have a look here: https://devdocs.magento.com/guides/v2.2/install-gde/prereq/apache.html

But as a wild guess your `<Directory /var/www/>` directive should be `<Directory /var/www/html/magento/pub>` make sure you have the original .htaccess file in your pub directory.

**Comment by orlangur** [comment]
Hi @chappish,

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
