### ISSUE TITLE
After "Save & Dublicate" Article Image Thumbs not changing 

### ISSUE THREAD

**Issue by flipflap** [magento/magento2#16394]
### Preconditions

1. Magento 2.1.11

### Steps to reproduce

1. Open a Config Article and click "Save & Dublicate"
2. Upload new images
3. Check first image as "Buse, Small and Thumbnail"

### Expected result

1. New image should be shown in product overview and in Magento backend

### Actual result

1. In Catalog view link still goes to old image same as the original article and shows the old image
2. Thumb in Magento Backend still shows the image of the original article
3. Product detail page shows all new image correct

**Comment by magento-engcom-team** [comment]
Hi @flipflap. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@flipflap do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by flipflap** [comment]
Sorry, I am not able to get vanilla Magento instance to work at all.

**Comment by ghost** [comment]
@magento-engcom-team , I would like to work on this issue. #mmei18

**Comment by flipflap** [comment]
I found the solution. You can close this.

I changed the image on "All store view" and it didn't  change them in my sub store views with languages. What is missing for product images is the "Use default value" function as other attribute have. Often people use stores for languages and mostly the images don't contain words so they can be same for all languages.
