### ISSUE TITLE
404 on Admin after Data Migration

### ISSUE THREAD

**Issue by Pesely** [magento/magento2#16398]
I have migrate my magento to a new server. 
http://www.pesemall.com

The front end works fine, but i am not able to find my admin panel:
http://www.pesemall.com/admin

vale of web/secure/use_in_adminhtml is 0
and
this is some lines from my local.xml:
`            <adminhtml>
                <args>
                    <frontName><![CDATA[admin]]></frontName>
                </args>
            </adminhtml>`

Could anyone help to fix my problem?

**Comment by magento-engcom-team** [comment]
Hi @Pesely. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Pesely do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mhauri** [comment]
Hi @Pesely 

GitHub is intended for bug reports only, please use [Magento Stack Exchange](https://magento.stackexchange.com/) for questions. 

Thank you
