### ISSUE TITLE
REST API get cart totals performing additional calculation

### ISSUE THREAD

**Issue by nevinsm** [magento/magento2#16407]
### Preconditions
1. PHP 7.1.15, MySQL 5.7.20
2. Magento 2.2.4

### Steps to reproduce
1. Add a product to the cart
2. Make an ajax request to the endpoint returned by vendor/magento/module-checkout/view/frontend/web/js/model/resource-url-manager.js getUrlForCartTotals(quote), where quote is the object returned by vendor/magento/module-checkout/view/frontend/web/js/model/quote.js

### Expected result
1. The REST API returns a grand_total that matches the result of calling getTotals() on the appropriate quote address.

### Actual result
1. The REST API returns a grand_total that has had the tax subtracted from it.

The problematic code is located in vendor/magento/module-quote/Model/Cart/CartTotalRepository.php lines 114 - 117 where the grand_total is manipulated after the totals collection happens at the address model level. If this is intentional, why is the responsibility for the calculation outside of the address totals collection architecture? If it is not intentional I would be happy to submit a PR removing lines 114, 115, and 117.

Best,
Nevin

**Comment by magento-engcom-team** [comment]
Hi @nevinsm. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nevinsm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
Looks like in https://github.com/magento/magento2/commit/2c9dd450490840841b237656522a7cd1364723f3 this logic became applied to not just ExclTax GrandTotal. @irenelagno thoughts?

**Comment by ghost** [comment]
Hi @nevinsm , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by francescosalvi** [comment]
still there on 2.4

**Comment by willwright** [comment]
This should be escalated it causes a somewhat serious edge case bug when Gift Cards are considered.
If a customer enters a Gift Card and the resulting `quote.GrandTotal` < `quote.TaxAmount` then the GrantTotal is set to 0 and this causes the Payment Interface to update to "No Payment Required" when in fact there is still an outstanding balance.
