### ISSUE TITLE
product attribute property text area is not supporting {{media url =""}} image path

### ISSUE THREAD

**Issue by kkert** [magento/magento2#16418]
Image not showing at fronted side when we uploaded it through media url in text area property

Its only supported the static image path.

I want that its have to support the media url same as description of product

Can this is possible?? 

### Preconditions

1. magento version 2.2.2

### Steps to reproduce

1. go to admin and create one product attribute with "text area" type, set "Enable WYSIWYG" and "Visible on Catalog Pages on Storefront" to "Yes".
2. set that attribute on product create time fields
3. after that create one product and go to that filed of attribute 
4. add an image in to it
5. normally we see that magento do this  <img src="{{"media url="}}">for image adding in content but its only supported on product description and short description not on that custom attribute text area for content.

### Expected result

1. [Screenshots, logs or description]
image has to shown on fronted

### Actual result

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/40622047/41955929-988b422c-79ff-11e8-96b9-0016ab6fcf9b.png)
![image](https://user-images.githubusercontent.com/40622047/41956019-e1e0eaf8-79ff-11e8-9f7d-585007c1c3bb.png)
![image](https://user-images.githubusercontent.com/40622047/41956080-0b4eea7a-7a00-11e8-9481-96101ef24986.png)

**Comment by magento-engcom-team** [comment]
Hi @kkert. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@kkert do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by kkert** [comment]
i have updated my previous comment

**Comment by kkert** [comment]
one more issue i am having

whats the process if the customer want to save its credit cards and payment
methods on his/her fronted account details

**Comment by kkert** [comment]
for magento 2

**Comment by ghost** [comment]
@kkert, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![screenshot_front](https://user-images.githubusercontent.com/40756187/42215677-e6ec66ae-7ec7-11e8-9894-e0d86276f50b.png)
![screenshot_adm](https://user-images.githubusercontent.com/40756187/42215678-e7223284-7ec7-11e8-80c3-785e56b8956b.png)

**Comment by kkert** [comment]
Thanks for replay but there is problem in fronted it was not display the images so please let me help how to fix that. please check the screenshot for custom attribute issue so you can understand what is a problem.


![image](https://user-images.githubusercontent.com/40622047/42217150-bc3677dc-7ee1-11e8-9b2d-82d114313882.png)
![image](https://user-images.githubusercontent.com/40622047/42217173-d2030eea-7ee1-11e8-97a3-2a237d60c22d.png)
![image](https://user-images.githubusercontent.com/40622047/42217259-1668da88-7ee2-11e8-912d-731d5a5c25aa.png)
![image](https://user-images.githubusercontent.com/40622047/42217271-20369c76-7ee2-11e8-92af-586166a7e6b5.png)
![image](https://user-images.githubusercontent.com/40622047/42217304-3c0354ee-7ee2-11e8-9bea-40f6ab233b93.png)

**Comment by ghost** [comment]
@kkert, a problem may be caused by custom modules or incorrect server configuration. Anyway, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by kkert** [comment]
This is not an custom module its an custom attribute (extra field) from magento 2 default fuctionality so please look in to it
