### ISSUE TITLE
Wrong email format sales order

### ISSUE THREAD

**Issue by loibv5989** [magento/magento2#16415]
**Preconditions**
Magento version 2.2.4

**Steps to reproduce**
I updated version 2.1.1 to 2.2.4. I have an error with the email sales order.
Email config sales in my admin is sales@croftonline.co.uk, When the customer sends the order, the server sends the email they receive the email with the ip address and host name as the attachment. (I only get errors with sales order emails).

**Expected result**
send email correct format

**Actual result**

![cr](https://user-images.githubusercontent.com/30828860/41948501-48f08442-79e7-11e8-8891-a448a0547782.png)
![cr2](https://user-images.githubusercontent.com/30828860/41948504-4c505464-79e7-11e8-9eda-69d27a80110e.png)

**Comment by magento-engcom-team** [comment]
Hi @dv-denda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dv-denda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by loibv5989** [comment]
I have fixed it

**Comment by DanielRuf** [comment]
> I have fixed it

Please let us know how you fixed it.

**Comment by loibv5989** [comment]
@versdivers has fixed it on: https://github.com/magento/magento2/pull/16356/commits/6e2fc05e12fa04ece313d4055a78c380ea63c8e3

**Comment by versdivers** [comment]
@dv-denda thats not the whole solution. 
https://github.com/magento/magento2/pull/16356#issuecomment-400204654
this is :D
