### ISSUE TITLE
Why some keys set only when $storeId == Store::DEFAULT_STORE_ID ?

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#16423]
https://github.com/magento/magento2/blob/e758b7f79a9f08f37d58cbb5b93257044a92db9a/app/code/Magento/CatalogImportExport/Model/Export/Product.php#L1182

Why some keys set only when $storeId == Store::DEFAULT_STORE_ID ?
Is it possible to run exports not for default store id without 3rd-patry extensions?

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@likemusic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@likemusic, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
