### ISSUE TITLE
Product display according to position not working for sub categories

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#16424]
### Preconditions

1. PHP Version 7.1.17
2. Mysql: Server version: 10.0.32-MariaDB-0
3. Magento 2.2.3

### Steps to reproduce

1. Add a category name suppose Garments under default category and sub category Like Tops, Shirts etc under Garments category.
2.  Add some products like "Shirt style top 1",  "Shirt style top 2",  "Shirt style top 3"and many other. Assign these three product in both Top and shirt sub category. And In category edit for Shirt Assign Position 1 for "Shirt style top 3", Position 2 for "Shirt style top 1" and Position 3 for "Shirt style top 2"

3. Like wise in category edit of Top assign Position 1 for "Shirt style top 2", Position 2 for "Shirt style top 3" and Position 3 for "Shirt style top 1".

4.After that run indexer reindex command .

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]
![position_in_backend](https://user-images.githubusercontent.com/24405051/41972151-981dda8c-7a2e-11e8-8653-482ea3a31003.png)
![position_in_frontend](https://user-images.githubusercontent.com/24405051/41972160-9ed50832-7a2e-11e8-9b24-a67badba90b0.png)

Pisition ! is set for 20 Bunte rosen in admin but it is coming in 3rd position.

Comment:
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @BabliDey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@BabliDey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hello @BabliDey, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @somat211. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by somat211** [comment]
Hi,
I have tried to reproduce this issue in Magento 2.3.x. I was unable to reproduce this issue.
Here I have shared screenshot for this.

![admin_configuration](https://user-images.githubusercontent.com/16957514/49684257-6ac59580-faf7-11e8-80b8-f286702338f4.png)

![product_list](https://user-images.githubusercontent.com/16957514/49684261-75802a80-faf7-11e8-8332-93ed90306a9a.png)
Thank You

**Comment by magento-engcom-team** [comment]
Hi @BabliDey, @somat211. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-93602` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @BabliDey. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-19969` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
