### ISSUE TITLE
magento2 module update 

### ISSUE THREAD

**Issue by lani2013** [magento/magento2#16426]
magento2 version 2.1.13
php version  7.0.27 

Hello Guys, 
module version its inside composer.json but the question is how can check to last update for my module and how can update it if need it? thanks

**Comment by magento-engcom-team** [comment]
Hi @lani2013. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lani2013 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mhauri** [comment]
Hi @lani2013 

GitHub is intended for bug reports only, please use [Magento Stack Exchange](https://magento.stackexchange.com/) for questions like yours. 

Thank you and have a nice day.
