### ISSUE TITLE
Product description missing in all product

### ISSUE THREAD

**Issue by justinwong617** [magento/magento2#16420]
- Summary of the issue,
   I just found that all the description on all product are missing.

### Preconditions
1. Magento ver. 2.2.2
2. 

### Steps to reproduce
1. Create new product/ Edit product.
2. Type description and short description.
3. Save product.
4. Open Product page on storefront.

### Expected result
1. Product description should shows under product photo.

### Actual result

1.  Even then product description tab is opened, review form is visible in front of description.

![screen shot 2018-06-27 at 5 26 29 pm](https://user-images.githubusercontent.com/40592860/41959089-60e655f2-7a2f-11e8-8f15-87972f5f9422.png)

![screen shot 2018-06-27 at 5 30 45 pm](https://user-images.githubusercontent.com/40592860/41959294-e33b7bea-7a2f-11e8-8b17-42fd8bbc2a54.png)

**Comment by ghost** [comment]
@justinwong617, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sanganinamrata** [comment]
@justinwong617 , Hello

I just checked this issue in **Magento version 2.2.3** And its working. Check this product: https://www.screencast.com/t/CFeDPeo8D

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by dimasalamatov** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16420-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16420-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16420-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dimasalamatov** [comment]
Checked 2.2-develop and 2.3-develop versions. Issue not reproduces anymore.

**Comment by shilpag25** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shilpag25. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shilpag25, here is your [Magento instance](https://i-16420-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-16420-2-3-develop.instances.magento-community.engineering/admin](https://i-16420-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shilpag25** [comment]
Hello @justinwong617 ,
I have tried to reproduce the issue but this issue is not reproducible on above instance (https://i-16420-2-3-develop.instances.magento-community.engineering). Hence closing the ticket

Please find attached screenshot for reference.
![product_description](https://user-images.githubusercontent.com/11830438/57177177-3d4eff00-6e7f-11e9-8e18-a181f29aebf0.png).
