### ISSUE TITLE
Module Manager grid is not working Magento 2.2.5

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#16439]
### Preconditions

1. PHP version: 7.1.16, Magento CE 2.2.5
2. Apache : 2.4.23

### Steps to reproduce

1.  Setup Magento CE 2.2.5
2.  Login to Admin Navigate to System > Tools > Web Setup Wizard 
3.  Than Go to Module Manager

### Expected result

1. It should open and let me display all modules that are currently installed.

### Actual result

1.  URL encounters 404 http://some_Ip/mage2.2.5/setup/index.php/moduleGrid/modules
![system](https://user-images.githubusercontent.com/36662131/42015823-87c48684-7ac6-11e8-8b05-98d8bd247344.png)

### Workaround

`setup\src\Magento\Setup\Model\Grid\Module.php`

`private function addGeneralInfo(array $items)`

-  `$item['moduleName'] = $item['moduleName'] ?: $this->packageInfo->getModuleName($item['name']);`

    To

+  `$item['moduleName'] = $item['moduleName'] ?? $this->packageInfo->getModuleName($item['name']);`

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@VZeroCool do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by VZeroCool** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-16439-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16439-2-2-5.engcom.dev.magento.com/admin](https://i-16439-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VZeroCool** [comment]
@magento-engcom-team, Encounters new problem Can't able to navigate to 
System > Tools > Web Setup Wizard

Its showing me Blank Page on vanilla Instance.
![error](https://user-images.githubusercontent.com/36662131/42016200-468949e6-7ac8-11e8-8dfb-51acb10df190.png)

**Comment by VZeroCool** [comment]
@magento-engcom-team, I would like to work on this issue.  #mm18in

**Comment by johnny-longneck** [comment]
Just a question: Javascript error angular.js? Is this normal or is knockout being replaced by angular? (which i would totally like)

**Comment by VZeroCool** [comment]
@johnny-longneck  Its angular.js error I think..

**Comment by hostep** [comment]
@VZeroCool : this was already [reported for Magento 2.2.4](https://github.com/magento/magento2/issues/15192) and was already fixed in https://github.com/magento/magento2/pull/15211, it was badly communicated and was not fixed in 2.2.5, but should be fixed in 2.2.6

**Comment by ghost** [comment]
I can confirm that the same fix if applied into Magento 2.2.5 it will work. Thanks to all community member about that.

**Comment by matt-mainstreetdesign** [comment]
Have this issue on 2.3.3, cant find a solution
