### ISSUE TITLE
Bundle Product Options not showing in Customer Account - Items Ordered 

### ISSUE THREAD

**Issue by robertkent** [magento/magento2#16434]
When ordering a bundle product (for instance the sample data provides the Yoga Kit) - the bundle options are not shown on the items ordered tab of the my account section.

Environment: Magento v2.2.2 with Sample Data (can't see a fix in other newer release notes)

### Steps to reproduce
1. Install Magento v2.2.2 with sample data
2. Create an account then purchase the Yoga Kit (Bundle Product) on its own
3. Visit the My Orders section in My Account
4. View the Items Ordered tab

### Expected result
Parent product with the options underneath (as is shown on the invoice tab)

### Actual result
Only parent product is listed

### Preconditions
1. PHP 7.0 and PHP 7.1 tested
2. MySQL 5.6 / 5.7
3. Magento 2.2.2 via create-project
4. Sample Data installed (but also broken on live website with real products)

### What I've debugged so far
Looking through the files, I can see that the $parentItem->getChildrenItems() within the renderer template for bundle returns empty.

Looking deeper into the problem, the magento-sales\Model\Order\Item.php does in fact call addChildItem() which should append to the $this->_children property array.

getChildrenItems() should simply pull this array - it looks like between this class being constructed (with child items) and called, this property is being cleared.

![screen shot 2018-06-27 at 17 29 49](https://user-images.githubusercontent.com/1905523/41987492-2d503a12-7a31-11e8-8511-4d292759d576.png)
![screen shot 2018-06-27 at 17 29 54](https://user-images.githubusercontent.com/1905523/41987493-2d776d76-7a31-11e8-89a0-02e436b6f33d.png)

**Comment by magento-engcom-team** [comment]
Hi @robertkent. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@robertkent do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hello @robertkent , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by slavvka** [comment]
Hi @robertkent. Thank you for your report. 
The issue has been fixed in magento/magento2#17889 by @rogyar in 2.2-develop branch
Related commit(s):
 - [f74460631c7feabb72c7ca3dec76a7bb92a17a41](https://github.com/magento/magento2/commit/f74460631c7feabb72c7ca3dec76a7bb92a17a41)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @robertkent. Thank you for your report. 
The issue has been fixed in magento/magento2#19318 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [7e78060c166672fbbd069875812856856d6815f8](https://github.com/magento/magento2/commit/7e78060c166672fbbd069875812856856d6815f8)

The fix will be available with the upcoming 2.3.1 release.

**Comment by fernandusfero** [comment]
Removed 

> Magento/Sales/Block/Order/Items.php
> $this->itemCollection->filterByParent(null);

I can see bundle options in my orders now, But I am facing a issue with pagination, If a bundle products option goes with a in-completion to the 2nd page  its renders as a simple product and not as bundle option.
But for print view i can get the outcome even its is rendered as in-completion .
