### ISSUE TITLE
magento 2.2.2 text swatch switches product image even if attribute feature is disabled

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#16446]
### Preconditions
magento 2.2.2 with one website and two store views
php 7.0 on ubuntu 16.04 with nginx

### Steps to reproduce
- change attribute size to text swatch with Update Product Preview Image set to NO
- create configurable product with some variations for size
- add image to configurable product
- add image to associated simple products

### Expected result
When I load the frontend product page, the image shown is the configurable image.
When I click on a size/variation (since the Update Product Preview Image set to NO in attribute size) I still expect to see the configurable image 

### Actual result
When I load the frontend product page, the image shown is the configurable image. That is correct.
When I click on a size/variation, the image is changed to the simple product image. This is wrong. 

### Other Notes
If I remove the image from the associated simple product, then go to the frontend product page and click on the size, the image shown is still the configurable image. However, the image is still being reloaded everytime I click on a size/variation, making the page glitch for a moment. This should be avoided.

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LouNik1984** [comment]
@magento-engcom-team give me 2.2.2 instance

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your request. I'm working on Magento 2.2.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984, here is your [Magento instance](https://i-16446-2-2-2.engcom.dev.magento.com).
Admin access: [https://i-16446-2-2-2.engcom.dev.magento.com/admin](https://i-16446-2-2-2.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by LouNik1984** [comment]
I confirm I can reproduce the issue on the vanilla Magento instance you provided me. 

### What I did on the vanilla instance
- I created a new category to have a link to the product on the frontend
- I created an attribute called size with attribute code size, type = text swatch and option "Update Product Preview Image" se to NO
- I edited the Default attribute set to add the new size attribute
- I created a configurable product with 3 size variations (small, medium, large)
- I added an image to all the products, both the configurable and the associated simple products

### Result
If you go to the frontend product page https://i-16446-2-2-2.engcom.dev.magento.com/test-product.html and click on the different configurations/text swatches, you can see that the image is loaded every time you click on a variation even if the attribute size is set to "Update Product Preview Image" = NO

**Comment by ghost** [comment]
Hello @LouNik1984, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
The issue has been fixed in magento/magento2#19184 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [dfaee8e70d76f47e39396922d7a05287150945cb](https://github.com/magento/magento2/commit/dfaee8e70d76f47e39396922d7a05287150945cb)
 - [6ce20262a90e0f9045691f3207d9acaa2b7b3f40](https://github.com/magento/magento2/commit/6ce20262a90e0f9045691f3207d9acaa2b7b3f40)
 - [01e8ff1c99557f267ca5ecc5eb450218bba6fc0b](https://github.com/magento/magento2/commit/01e8ff1c99557f267ca5ecc5eb450218bba6fc0b)
 - [73ef11915ffa0ed8f8d38b785d59d3ad8ace9218](https://github.com/magento/magento2/commit/73ef11915ffa0ed8f8d38b785d59d3ad8ace9218)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
The issue has been fixed in magento/magento2#22510 by @ravi-chandra3197 in 2.2-develop branch
Related commit(s):
 - [4e190effd9445fec7abca90fcda9431e577f0650](https://github.com/magento/magento2/commit/4e190effd9445fec7abca90fcda9431e577f0650)
 - [c5674e53bb77c4529e42733848acde768c338ca7](https://github.com/magento/magento2/commit/c5674e53bb77c4529e42733848acde768c338ca7)

The fix will be available with the upcoming 2.2.10 release.
