### ISSUE TITLE
Error while upgrade Magento 2.2.3 to 2.2.5 - The session id is too long or contains illegal characters

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#16448]
We are getting errors after upgrade magento 2.2.3 to 2.2.5.
on frontend we are getting following errors.

1 exception(s):
Exception #0 (Exception): Warning: SessionHandler::read(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /var/www/html/magento225/vendor/magento/framework/Session/SaveHandler/Native.php on line 22

Exception #0 (Exception): Warning: SessionHandler::read(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in /var/www/html/magento225/vendor/magento/framework/Session/SaveHandler/Native.php on line 22
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'SessionHandler:...', '/var/www/html/o...', 22, Array)
#1 /var/www/html/magento225/vendor/magento/framework/Session/SaveHandler/Native.php(22): SessionHandler->read('38u9ut26n3l82f4...')
#2 /var/www/html/magento225/vendor/magento/framework/Session/SaveHandler.php(93): Magento\Framework\Session\SaveHandler\Native->read('38u9ut26n3l82f4...')

**Comment by magento-engcom-team** [comment]
Hi @aasim110. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@aasim110 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by aasim110** [comment]
Issue fixed after clearing browser cache :)
