### ISSUE TITLE
Customer Attribute set as visible & required per scope is not displayed as required in form

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#16442]
### Preconditions
1. PHP 7.1 & Magento 2.2.3

### Steps to reproduce
1. Add new Customer attribute, set `visible` to 0, `required` to 0
2. In one of the scopes - set `visible` to 1, and required to 1.
   ![screenshot from 2018-06-28 10-54-53](https://user-images.githubusercontent.com/1639941/42024140-cbadd0a8-7ac1-11e8-8688-a62c94badbd3.png)

3. Go to Customer edit form

### Expected result
1. Field related with custom attribute should be shown and required

### Actual result
1. Field is just visible, but it's not marked as required.
    ![screenshot from 2018-06-28 10-53-23](https://user-images.githubusercontent.com/1639941/42024147-d1a23292-7ac1-11e8-828d-7bdd94817fc2.png)

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lbajsarowicz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@lbajsarowicz , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
