### ISSUE TITLE
magento2.2.5 products not showing in parent category

### ISSUE THREAD

**Issue by vipashavivi** [magento/magento2#16449]
### Preconditions

1. Magento version 2.2.5
2. Mozilla Firefox

### Steps to reproduce

1. Select Category "Anchor" to "Yes"
![image](https://user-images.githubusercontent.com/40662711/42031822-4618790a-7af5-11e8-9b8f-4c42d030a167.png)
2. Run re-index command
![image](https://user-images.githubusercontent.com/40662711/42031922-8a18cb50-7af5-11e8-89ac-9b8bed86832b.png)

3. Open category on front-end

### Expected result

1. Products will be shown from child categories

### Actual result

1. No product is showing on front-end
![image](https://user-images.githubusercontent.com/40662711/42032099-16903ed8-7af6-11e8-9eab-5c734af418d4.png)

**Comment by magento-engcom-team** [comment]
Hi @vipashavivi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vipashavivi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by vipashavivi** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @vipashavivi. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @vipashavivi, here is your [Magento instance](https://i-16449-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16449-2-2-5.engcom.dev.magento.com/admin](https://i-16449-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by allisonlawrencels** [comment]
We are encountering the same issue. Please provide fix ASAP as we have to accept this error in order to apply the security fixes in 2.2.5.

Alternatively, please provide a security patch for 2.2.3.

**Comment by vegangirlthatcodes** [comment]
I'm also encountering this issue. 2.2.4 was working fine.
In my case no products show up in any category.

**Comment by allisonlawrencels** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @allisonlawrencels. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @allisonlawrencels, here is your [Magento instance](https://i-16449-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16449-2-2-5.engcom.dev.magento.com/admin](https://i-16449-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by allisonlawrencels** [comment]
I cannot reproduce one the 2.2.5 instance, however it is the Open Source version, not Commerce. It looks like this is a Commerce issue, @vipashavivi can you confirm you also use Commerce?

**Comment by allisonlawrencels** [comment]
We found out that our issue was caused by the Mirasvit ElasticSearch module still referencing non-storeview scoped index tables.

**Comment by vipashavivi** [comment]
Hi @allisonlawrencels How to fixed this issue with Mirasvit.? Can you help me to fix?

**Comment by ghost** [comment]
@vipashavivi, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
