### ISSUE TITLE
How to migrate to another shopping cart?

### ISSUE THREAD

**Issue by panel123** [magento/magento2#16447]
I’m using Magento 1 now, and I’ve been thinking of moving to Magento 2, cause the business grows really well. What is the best way to do it?

**Comment by magento-engcom-team** [comment]
Hi @panel123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@panel123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@panel123 you can use https://github.com/magento/data-migration-tool.

Note that GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by saadattravele** [comment]
Moving to a new platform should be done with much planning.
The short version
Map your current website pages
Duplicate the pages to the new platform
Launch new website
Use redirects to map old pages full addresses to new pages
Keep track of new/old website in Google Search Console
I could guide so much in this area that I hope it works
For more information on the [iran incoming tour operator](http://www.saadattravel.com), you can contact us

**Comment by panel123** [comment]
Thanks for your follow-ups and tips
The problem was solved
