### ISSUE TITLE
 Language and currency Switcher  are not working on Magento 2.2.5 in Mac safari and Chrome  Explorer

### ISSUE THREAD

**Issue by realGomez** [magento/magento2#16454]
### Preconditions

1. Magento2 ce 2.2.5
2. php 7.0.1
3.Mac safari 11.1 and Chrom67.0.3396.87  Explorer
### Steps to reproduce

1. I had a Magento 2.2.5 with a website that has one store and two store's views (en and tc)
2. On Stores -> Configuration -> Web , I set "Add Store code to URLs" to "YES" OR "No"(I test)
3. in default store view(en), I  change the language to Chinese, It works first time, Then I change the language to en， It works too；When I change the language to Chinese again, It doesn't work any more；Even if I refresh the page still does not work；
The issue seems to be related to caching, I  clear the cache and switch languages, It works again;

### Expected result

 Language and currency Switcher can switch at any time;

### Actual result

 Language and currency Switcher are not working at the second time;

ps: I test in phone7 safari and window Chrome, IE 9; It works any time;
The issue occurs in Mac Safari and Chrome Explorer;

**Comment by magento-engcom-team** [comment]
Hi @realGomez. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@realGomez do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by realGomez** [comment]
It works after we add the setting; store -> configuration -> web -> default cookie setting;

**Comment by genyuk** [comment]
The issue is still not resolved and got even worse in 2.2.5 preventing our store to change language on Product and Category pages. Basically it switches to the homepage instead of the Product or Category page. 
for example: 
http://prod.sportsvirtuoso.com/en/squash
try to switch to "Fr" language.
expected result:
switches to http://prod.sportsvirtuoso.com/fr/squash
real results:
switches to http://prod.sportsvirtuoso.com/fr/
It was working on 2.2.4 

On another installation It also switches to the homepage after you switch language twice (on fresh Magento 2.2.5 install with just two test categories) and with "Default cookies settings" set.
Here is an example:
http://goodolddisc.com/video-games.html (try to change language twice and you will end up on the homepage). 
It is long story with "Language switcher" and it is getting worse with every release.

Please fix it or let us know what settings can affect such behavior?

**Comment by genyuk** [comment]
Please open this issue again

**Comment by ghost** [comment]
Duplicate of #14674
