### ISSUE TITLE
Unable to place order with coupon code and grandtotal zero

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#16451]
### Preconditions

1. Magento 2.2.3
2. 10.0.32-MariaDB-0

### Steps to reproduce

1. Added a coupon code of flat discount of 25 euro
2. Enabled Zero Subtotal Checkout form store > configuration > sales > payment methods
3. Added product to cart of 18 euro applied the coupon code as a whole the total amount to be 
   paid is zero including shipping. 
4. Added shipping details and in next step the No payment method is coming. 
5. But when clicking on Place Order showing error message The requested payment method is not available

### Expected result

1. [Screenshots, logs or description]
![payment_setting](https://user-images.githubusercontent.com/24405051/42037175-5ce845c4-7b05-11e8-927f-bb6a093bb5b1.png)
![payment_setting](https://user-images.githubusercontent.com/24405051/42037183-621e8a30-7b05-11e8-97cb-12c0cca32266.png)

@magento-engcom-team give me 2.2.3 instance
### Actual result 

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @BabliDey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@BabliDey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by BabliDey** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @BabliDey. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @BabliDey, here is your [Magento instance](https://i-16451-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-16451-2-2-3.engcom.dev.magento.com/admin](https://i-16451-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by BabliDey** [comment]
Tried the process but it is working here. Even the process working fine in my old version of magento 2.1.8. 
But after upgrading to version 2.2.3 it is not working

**Comment by BabliDey** [comment]
Hello need help to solve this problem

**Comment by Leandry** [comment]
Could not reproduce on 2.1.8 and after upgrading it to 2.2.3.
![2018-06-30_11-59-22](https://user-images.githubusercontent.com/9416636/42123805-d5193e20-7c60-11e8-864e-31b4e8999dea.png)
![2018-06-30_12-23-44](https://user-images.githubusercontent.com/9416636/42123836-695f2c52-7c61-11e8-857f-e0c79406a2e8.png)

 @BabliDey Could you check the issue on clean instance?

**Comment by BabliDey** [comment]
Hello @Leandry 

![payment_page](https://user-images.githubusercontent.com/24405051/42228077-ac0c745a-7f00-11e8-9bcd-db5cb284f161.png)
![payment_process](https://user-images.githubusercontent.com/24405051/42228092-b6c368ae-7f00-11e8-8565-c50aabf28f85.png)

This is what i am getting there is one error in console log 
/V1/guest-carts/805fc9f9ca0925cf34f7ebc5be9f2f5c/payment-information 400 (Bad Request)

But no details about in exception log or debug log

**Comment by sicaizhang** [comment]
I have the same issue after applying rewards(same as coupon), on Magento 2.23
<img width="1264" alt="order total 0" src="https://user-images.githubusercontent.com/52158821/68175513-75650500-ffbc-11e9-8db1-42ed176931ee.png">
