### ISSUE TITLE
Upgrade from 2.2.4 -> 2.2.5 - Integrity constraint violation

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#16450]
### Preconditions
1. Magento 2.2.4 -> 2.2.5
2. PHP 7.1.8

### Steps to reproduce
1. bin/magento setup:upgrade

### Expected result
1. No errors

### Actual result
1. 
```
Integrity constraint violation: 1062 Duplicate entry '11-General' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: INSERT INTO `eav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`, `attribute_group_code`) VALUES (?, ?, ?, ?, ?)
```

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Leandry** [comment]
Could not reproduce the issue. I used clean install 2.2.4 and upgraded it to 2.2.5.
Actual result: No errors.
![2018-06-30_12-50-16](https://user-images.githubusercontent.com/9416636/42124011-61749448-7c64-11e8-9ed7-c2cab1e590f7.png)
![2018-06-30_12-49-50](https://user-images.githubusercontent.com/9416636/42124014-6a159336-7c64-11e8-83a3-732eb7dc2f35.png)
![2018-06-30_12-50-50](https://user-images.githubusercontent.com/9416636/42124015-6c7be346-7c64-11e8-905d-bf364897d75f.png)

**Comment by senders** [comment]
I have the same problem. Upgrading existing store from 2.24 to 2.2.5.


Error while executing setup:upgrade;

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9-general' for key 'SISCAT_CTGR_PRD_ATTR_SET_ID_ATTR_GROUP_CODE', query was: INSERT INTO `siseav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`, `attribute_group_code`) VALUES (?, ?, ?, ?, ?)

**Comment by msawyers** [comment]
I am having the same issue:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-General' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: INSERT INTO `eav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`, `attribute_group_code`) VALUES (?, ?, ?, ?, ?)

**Comment by senders** [comment]
Hello,
perhaps somebody has the same problem. I was getting to work by disabling the system extension Temando_Shipping before upgrading to 2.2.5 (not Vertex_Tax as I mentioned before) ;
php bin/magento module:disable Temando_Shipping
php bin/magento setup:upgrade
Then start the normal composer update. And setup:upgrade will work.

So maybe there is something wrong with Temando_Shipping extension with existing data in some case.

**Comment by sebfie** [comment]
Same issue here with a website with already many data
