### ISSUE TITLE
After login from backed user, Go to invoice grid and export csv (At first time in invoice grid) , we get redirect to dashboard page but at second time, csv export successfully

### ISSUE THREAD

**Issue by jitendra-cedcoss** [magento/magento2#16456]
**Description**

* After login from backed user, Go to invoice grid and export csv (At first time in invoice grid) , we get redirect to dashboard page but at second time, csv export successfully.

**Preconditions:**

* This issue is available in a Magento 2.1.x, Magento 2.2.x version.

**Note :** Make sure Notification Resource disable for current login User

**Steps to reproduce:**

* Create a new role (for example role name is 'sales person') and go to Role Resource tab.

* Select 'Resource Access' as 'Custom' and allow all resouces except 'Notification' (See image - role acl.png).

* Create a new User (ex- username : test-user , password: test@123 ) and assing above role (ex: 'sales person') to this user.

* Login this user (ex: test-user) from backed login panel.

* Go to Sales and then invoice grid

* Export csv from invoice grid (After login at first time)

**Expected result:**

* Csv export successfully.

**Actual result:**

* Csv does not export and redirect to Dashboard page. When again back to invoice grid (At second time) and export csv, it is successfully exported.

* Also getting below js error in console (see image: console log.png).

**Images** 
![console log](https://user-images.githubusercontent.com/25526075/42077334-2e6a7384-7b96-11e8-88cf-30044e1bb201.png)
![role acl](https://user-images.githubusercontent.com/25526075/42077335-2ea76988-7b96-11e8-8769-3e4bddcc0128.png)

**Comment by magento-engcom-team** [comment]
Hi @jitendra-cedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@jitendra-cedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jitendra-cedcoss** [comment]
@jitendra-cedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

**yes**

**Comment by ghost** [comment]
#mm18in I would like to work on this issues.

**Comment by ghost** [comment]
@jitendra-cedcoss, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jitendra-cedcoss** [comment]
@engcom-backlog-pb  Any update?

**Comment by Manwanigaurav** [comment]
I am working on this at #dmcdindia19”

**Comment by magento-engcom-team** [comment]
@Manwanigaurav thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Manwanigaurav** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Manwanigaurav. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Manwanigaurav, here is your [Magento instance](https://i-16456-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-16456-2-2-develop.instances.magento-community.engineering/admin](https://i-16456-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @jitendra-cedcoss.

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
