### ISSUE TITLE
Order Emails comes from server email id

### ISSUE THREAD

**Issue by vipinpatole** [magento/magento2#16460]
### Preconditions
	Magento version: 2.2.5
	Php version: 7.0
	Mysql: 5.6.39 - MySQL Community Server (GPL)
### Steps to reproduce
1.	When customer place order he receives email from the15891@server101.hostingcosmos.com
2.	However, I have set email to be sent from customercare@thebookstrunk.com
3.	Below are my email settings with the same setting i was able to produce expected results in magento 2.2.3 
        
![image](https://user-images.githubusercontent.com/39498856/42080998-eda7d8b2-7ba1-11e8-99d0-07a84a18291e.png)

### Expected result
1.	After placing order customer should get email from customercare@thebookstrunk.com
 
![image](https://user-images.githubusercontent.com/39498856/42081014-f94f03f2-7ba1-11e8-8bae-9a2e9a9edf3e.png)

### Actual result
1.	After placing order customer receive email  from the15891@server101.hostingcosmos.com
 
![image](https://user-images.githubusercontent.com/39498856/42081026-fe6c9d2c-7ba1-11e8-92a7-176b8464872d.png)

**Comment by magento-engcom-team** [comment]
Hi @vipinpatole. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vipinpatole do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by vipinpatole** [comment]
@magento-engcom-team  
     i dont have vanilla magento instance, how can i get this?

**Comment by vipinpatole** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by gwharton** [comment]
Duplicate of #14952
