### ISSUE TITLE
Flush cache and flush static content buttons not showing after upgrade to 2.2.4

### ISSUE THREAD

**Issue by nishantbkw** [magento/magento2#16463]
### Upgrade Magento Version 2.2.2 to 2.2.4 

1. From Admin Go to System -> Cache Management It should show Flush Cache and Clean Cache 
Buttons but there is nothing

### Steps to reproduce

1. Upgrade Magento Version 2.2.2 to 2.2.4 
2. from admin go to System -> Cache Management 
3. No Flush Cache Button showing 

### Expected result

It should show flush cache and flush cache storage buttons but not showing 

### Actual result

1.  
![index](https://user-images.githubusercontent.com/11628633/42098847-a7326126-7bd9-11e8-9c8a-1cac777a3a04.png)

**Comment by magento-engcom-team** [comment]
Hi @nishantbkw. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nishantbkw do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
So far we could not reproduce it in our clean 2.2.4 instances.

Did you run the upgrade commands and clear the cache using the CLI?

**Comment by nishantbkw** [comment]
@DanielRuf  Yes Ran Upgrade and Clear cache multiple times but not worked

**Comment by Leandry** [comment]
Hello @nishantbkw 
I could not reproduce the issue in clean Magento installation. The problem was not reproduced on 2.2.2 and after upgrade to 2.2.4.
![2018-06-30_13-55-48](https://user-images.githubusercontent.com/9416636/42124590-24844312-7c6e-11e8-8c19-da210bf41810.png)
![2018-06-30_13-59-31](https://user-images.githubusercontent.com/9416636/42124591-26373110-7c6e-11e8-8b99-7fd1a2c859e0.png)
