### ISSUE TITLE
After Merging Js in admin site issue

### ISSUE THREAD

**Issue by vasudevsundar** [magento/magento2#16473]
### Preconditions

1. Install Magento 2.2.4

### Steps to reproduce

1. Open Admin Panel and Click a cms page, in that content tab is there, Show Editor is not editing
2. Check in console getting error as " Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled. "
3. After Merging js in both mode.

### Expected result

1. Need to show editor. Need to Clear console issue.

### Actual result

1. Not able to show editor.

**Comment by magento-engcom-team** [comment]
Hi @vasudevsundar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vasudevsundar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dev-jq** [comment]
Disabling the Klarna module seems to have resolved the issue for me
```
bin/magento module:disable Klarna_Kp Klarna_Ordermanagement Klarna_Core
bin/magento deploy:mode:set production
```
Solutions from:
https://github.com/magento/magento2/issues/11577
https://github.com/magento/magento2/issues/15638

**Comment by ghost** [comment]
@vasudevsundar, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. It seems like the problem is caused by custom modules.  Please try to reproduce this issue on a clean installation. If the issue is reproducible, please reopen this ticket.

**Comment by vasudevsundar** [comment]
@jq91 ,

Issue Solved as per your comments, i followed. 
Thanks You @jq91

**Comment by LSERRE** [comment]
It seems issue was fixed in Klarna module. Just run composer update.
