### ISSUE TITLE
Column not found: 1054 Unknown column 'at_visibility_default.value'

### ISSUE THREAD

**Issue by sandervall** [magento/magento2#16471]
### Preconditions

1. Magento 2.2.5 Community
2. PHP 7.2
3. Enable developer mode(bin/magento deploy:mode:set developer).
4. Rename magento_root_dir/pub/errors/local.xml.sample to magento_root_dir/pub/errors/local.xml

### Steps to reproduce

1. Navigate to admin area Catalog > Products.
2. Create simple product SKU = 'simple', price = '3', quantity = '100', visibility = 'Catalog, Search'. Categories = 'cat1'(subcategory of default category).
3. Create Products List widget with criteria "Visibility  is  Catalog, Search".
4. Add widget to Main CMS page.
5. Navigate to storefront home page.
 

### Expected result

1. The widget should display only products with visibility Catalog, Search

### Actual result

1. Error
![widget](https://user-images.githubusercontent.com/34515754/42126453-cd08e47a-7c91-11e8-82d7-8d80bb491f7a.jpg)
2. Generated SQL in plain text for debugging
SELECT DISTINCT  COUNT(DISTINCT e.entity_id) FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(`e`.`entity_id`, 0) IN (SELECT `catalog_category_product`.`product_id` FROM `catalog_category_product` WHERE (category_id IN ('3')))) AND(IFNULL(`e`.`entity_id`, `at_visibility_default`.`value`) IN ('5', '6', '20', '21', '22', '23', '26', '33', '34', '35', '36', '37', '56', '57', '59', '60', '62', '63', '64', '65', '87', '109', '117', '136', '143', '150', '151', '152', '153', '155', '156', '157', '158', '159', '185')) ))

**Comment by magento-engcom-team** [comment]
Hi @sandervall. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sandervall do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @sandervall, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by code-explorer1234** [comment]
This is a quick fix that worked for me: https://github.com/magento/magento2/issues/13881

**Comment by bonsoni** [comment]
We are having the similar issue

**Comment by engcom-Bravo** [comment]
Hi @sandervall,

Thanks for your reporting and collaboration.

we have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="923" alt="Screenshot 2024-10-25 at 11 56 19" src="https://github.com/user-attachments/assets/daab9934-6bd1-4eea-870d-8d91e16f3021">



![Home-page-10-25-2024_11_55_AM](https://github.com/user-attachments/assets/7d8e0882-04b1-4096-80a3-3bdaccdbbc66)


Widget displaying products with visibility Catalog, Search

Hence we are closing this issue.


Thanks.
