### ISSUE TITLE
Gift card with open amount disabled, no amounts provided has uncaught exception

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#16486]
### Preconditions
1. Magento 2.2.4
2. PHP 7.1

### Steps to reproduce
1. Create product with type of Gift Card
2. Set "Open amount" to false
3. Do not provide any amount to the amount options

### Expected result
1. Redirect back to the category page and / or just error message that the product is not saleable.

### Actual result
1. Exception thrown to the user and not caught in the application:
```
1 exception(s):
Exception #0 (Exception): Warning: max(): Array must contain at least one element in /var/www/x/src/vendor/magento/module-gift-card/Ui/DataProvider/Product/Collector/Price.php on line 79
```

After debugging \Magento\GiftCard\Ui\DataProvider\Product\Collector\Price method collect() I found out that there are products that have allow_open_amount value set to 0 and no amounts provided.

As a result this part of the code:
```
            if ($product->getAllowOpenAmount()) {
                $max = $product->getOpenAmountMax();
                $min = $product->getOpenAmountMin();
            } else {
                $max = max($amounts);
                $min = min($amounts);
            }
```
causes passing an empty array to max method, which causes an error.

@magento-engcom-team If you provide what is the expected behavior (redirect with error / just error and display page / whatever), I believe that's easy issue to fix.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lbajsarowicz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@lbajsarowicz, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
