### ISSUE TITLE
Product does not added to wishlist after login in Magento version 2.2.x

### ISSUE THREAD

**Issue by sanganinamrata** [magento/magento2#16498]
### Preconditions

1. Add product to wishlist as a guest user.
2. As per Magento's default behavior, It'll ask you to log in first prior to adding that item to your wishlist.

**Reflacted Magento version: 2.2.x** 
**Working properly upto Magento version 2.1.x**

### Steps to reproduce

1. As mentioned in above step

### Expected result

1. After login, the product should be successfully added to cart.

### Actual result

1. The product does not get added to cart after successful login. The issue is with added **formkey validation** to the controller responsible for add to wishlist. (Product data is been sent by session, Where formkey is not been somehow.)

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sanganinamrata do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@sanganinamrata, thank you for your report. Unfortunately, I'm not able to reproduce this issue.
Magento 2.2.5
![peek 2018-07-03 16-19](https://user-images.githubusercontent.com/40755810/42222308-7d7dbfc2-7edd-11e8-835f-05d23475783a.gif)
Can you please provide more details or steps to reproduce?

**Comment by sanganinamrata** [comment]
@engcom-backlog-nickolas ,

I am facing this issue in **Magento version 2.2.2** specifically.

**Comment by engcom-backlog-nickolas** [comment]
@sanganinamrata, thank you for feedback. Confirm, such bug exists in 2.2.2 version. Unfortunately we can not fix it there, as 2.2.2 already has been released. 
Still, you may try to upgrade your magento version to the latest 2.2.x, where it's been fixed.

**Comment by sanganinamrata** [comment]
@engcom-backlog-nickolas - Ok, I'll upgrade my Magento version to have a fix.

Thanks :)
