### ISSUE TITLE
User role issue with customer group

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16499]
While creating a user role for the “customer group”, issue with “customer group” menu for user role(ACL file).
The “customer group” menu is displayed under "customers" menu on the admin side, whereas it is displayed under store > other setting menu while assigning user role. 

### Preconditions

1.Magento Version 2.2.2 with sample data 
2.PHP 7.0 

### Steps to reproduce

1.System > Permission > User Roles 
2. Create a role, give  Resource Access to "Dashboard" and "Customer Groups"
3. Then create a user with the above-specified user role
4. Log in with the user(with the above-specified role) and you will notice that the system and customer menu both are visible at the same time.
5. But customer group is displayed under customer while system menu is blank. 

### Expected result

"Customer group" menu should be displayed under "customers" while Store menu should not be displayed.
1. [Screenshots, logs or description]

### Actual result

Customer group is displaying under customer while Store menu is blank.
1. [Screenshots, logs or description]
![user role issue with customer group 1](https://user-images.githubusercontent.com/2203580/42214174-617a1d2a-7ed8-11e8-90b5-444b617554be.png)
![user role issue with customer group 2](https://user-images.githubusercontent.com/2203580/42214181-6615c258-7ed8-11e8-8712-93ad15c9bdf3.png)

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@emiprotech, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
@engcom-backlog-pb 
I have a solution for this issue , Can you assign me this issue ?

**Comment by ghost** [comment]
@emiprotech, of course. Feel free to create pull-request.

**Comment by sidolov** [comment]
Hi @emiprotech. Thank you for your report. 
The issue has been fixed in magento/magento2#17629 by @jignesh-baldha in 2.1-develop branch
Related commit(s):
 - [0ffcfab6105c468cf461225ee07e088b525b80c7](https://github.com/magento/magento2/commit/0ffcfab6105c468cf461225ee07e088b525b80c7)

The fix will be available with the upcoming 2.1.16 release.

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
The issue has been fixed in magento/magento2#17574 by @jignesh-baldha in 2.3-develop branch
Related commit(s):
 - [0d7dc6cb6c4fb25839b73fcbf861a09a646379b3](https://github.com/magento/magento2/commit/0d7dc6cb6c4fb25839b73fcbf861a09a646379b3)

The fix will be available with the upcoming 2.3.0 release.

**Comment by TomashKhamlai** [comment]
The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by Ctucker9233** [comment]
@TomashKhamlai Where's the PR for 2.2?

**Comment by TomashKhamlai** [comment]
@Ctucker9233, maybe this one #17515
