### ISSUE TITLE
Magento 2.2.5 : Admin user is not able to login with customer group user role

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16501]
While creating a user role for the “customer group”, issue with “customer group” menu for user role(ACL file).

### Preconditions

1. Magento Version 2.2.5 with sample data 
2. PHP 7.0

### Steps to reproduce

1. System > Permission > User Roles 
2. Create a role under "Roles Resources" for the “customer group” access (Role only for customer group).
3. Then create a user with the above-specified user role.
4. Log in with the new user(with the above-specified role) and you will notice that you will not able to log in with that user.

### Expected result

1. New Admin user should be login 
### Actual result

1. Admin not able to log in, getting an error "This Page isn't working"
![admin user is not able to login with customer group user role](https://user-images.githubusercontent.com/2203580/42215352-c31a4b38-7edb-11e8-92fa-7a6bfc564c34.png)

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@emiprotech, thank you for your report and pull request. Can you please specify steps, you've done to achieve actual result? Because I'm not able to reproduce this issue. I've tested it on 2.2.5 with sample data.
Here is my results:
![role](https://user-images.githubusercontent.com/40755810/42217693-d74af600-7ece-11e8-892f-be940a67e5f2.png)
![login](https://user-images.githubusercontent.com/40755810/42217801-46ca26f4-7ecf-11e8-86b4-12d7b5f398a6.png)

**Comment by ghost** [comment]
Ok let me give you more specification.
1. Create new user then set its user resources.
2. Select only customer groups from resources and save role.
3. Now  login in another browser with new admin user(which you have created) credential you will not able to login successfully.
![user_role](https://user-images.githubusercontent.com/2203580/42220172-dbbd40cc-7eeb-11e8-96d5-d4e88e22cd21.png)

**Comment by engcom-backlog-nickolas** [comment]
@emiprotech , thank you for your feedback.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
I have found this solution for that issue and I have submitted pull request. :)

**Comment by engcom-backlog-nickolas** [comment]
@emiprotech, great, thanks! May I assign you to this issue?

**Comment by ghost** [comment]
yes please.

**Comment by ghost** [comment]
I am facing the same issue but Provided commit doesn't work for me ! Any other workaround ?

**Comment by nimitaemipro** [comment]
@TBSMage what you have changed in your file ?
you should have to change in ACL file.

**Comment by ghost** [comment]
@nimitaemipro I modified `acl.xml` for customer.

`<acl>
        <resources>
            <resource id="Magento_Backend::admin">
                <resource id="Magento_Customer::customer" title="Customers" translate="title" sortOrder="40">
                    <resource id="Magento_Customer::manage" title="All Customers" translate="title" sortOrder="10" />
                    <resource id="Magento_Customer::online" title="Now Online" translate="title" sortOrder="20" />
					<resource id="Magento_Customer::group" title="Customer Groups" translate="title" sortOrder="30" />
                </resource>
                <resource id="Magento_Backend::stores">
                    <resource id="Magento_Backend::stores_settings">
                        <resource id="Magento_Config::config">
                            <resource id="Magento_Customer::config_customer" title="Customers Section" translate="title" sortOrder="50" />
                        </resource>
                    </resource>
				</resource>
            </resource>
        </resources>
    </acl>`

**Comment by engcom-Bravo** [comment]
Hello @emiprotech 
We have rechecked this issue on Magento 2.4-develop and can't reproduce 
We've created a user role with the **Customer Groups** Role Resource only 
![customer group](https://user-images.githubusercontent.com/51680745/71727531-38de4a00-2e43-11ea-9c6b-6ad2ede9ef25.png)

And we are able to Login to Magento Admin with a user with such Role assigned 
![customer_group](https://user-images.githubusercontent.com/51680745/71727619-89ee3e00-2e43-11ea-80f5-d6299d45957c.png)
We've even tried to log in from another Browser and in Incognito mode

So, we have to close it.
If you are still experiencing this issue on Magento 2.4, please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.
