### ISSUE TITLE
Magento 2.2.4 Invalid Date in Order Grid

### ISSUE THREAD

**Issue by crtl** [magento/magento2#16507]
### Preconditions

1.  Magento 2.2.4
2. Interface Locale en_US

### Steps to reproduce

1. Go to Sales > Orders 
2. Select Filters and filter by `Order Date` `from` and `to`
3. Apply filters
4. Visit another admin page
5. Go back to Orders
6. The active date filter now shows incorrect or even "Invalid Date" values.
7. Applying the filters crashes the grind and in some cases the loader stays forever (even after relog)

### Expected result
1. Filter should be applied correctly and date should not change to invalid date

### Actual result
1. Date to is an invalid date after revisit

### Aside
The same with Invoice grid (I have not tested more.)

**Comment by magento-engcom-team** [comment]
Hi @crtl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@crtl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@crtl, thank you for your report.
This issue is already fixed in Magento 2.3.

**Comment by neeta-wagento** [comment]
@engcom-backlog-pb : As its resolved in 2.3 Can you provide patch files for 2.1.9 ?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @crtl The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by dyuk1987** [comment]
May I know what are the related commits for the fix(es) for this issue?
