### ISSUE TITLE
Magneto 2.1.9 Image Upload issue in swatches, which uploading in safari web browser

### ISSUE THREAD

**Issue by Mahenderpinakisoft** [magento/magento2#16506]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Actual result

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @Mahenderpinakisoft. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Mahenderpinakisoft do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hello, @Mahenderpinakisoft. Unfortunately, we are closing your issue due to malformed report. If you'd like to update it, please reopen the issue and use the reporting guidelines
