### ISSUE TITLE
Magento 2.2.5 google-analytics.js

### ISSUE THREAD

**Issue by elibyy** [magento/magento2#16514]
### Preconditions

1. magento 2.2.5

### Steps to reproduce

1.Install magento using `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <installation directory name>
` or download it from [here](https://magento.com/tech-resources/download)
2. see that the file vendor/magento/module-google-analytics/view/frontend/web/js/google-analytics.js is not matching the latest version within the 2.5.0 tag.

The missing commit is [this](https://github.com/magento/magento2/commit/24a5abd95a177d9e21f5c2791931e6d104be42aa#diff-c72aa7d76640b3117fdef842add697bc).

Thanks

**Comment by magento-engcom-team** [comment]
Hi @elibyy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@elibyy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by elibyy** [comment]
@magento-engcom-team I confirm I've provided any information needed

**Comment by orlangur** [comment]
https://github.com/magento/magento2/pull/15765 clearly states that it will be available with 2.2.6, thus it is not supposed to be a part of 2.2.5.
