### ISSUE TITLE
Catalog Price Rule not working for magento2 rest api

### ISSUE THREAD

**Issue by hiteshagrawal84** [magento/magento2#16511]
### Preconditions

1.  Magento 2.2.5 with Sample Data
2.  php 7.0+

### Steps to reproduce

1.  Create a Catalog Rule
2.  Run the cron and indexing
3.  Check /V1/products/{sku} rest api

### Expected result

1. Catalog rule applied price should come in special_price 

### Actual result

1.  It is not coming.

**Comment by magento-engcom-team** [comment]
Hi @hiteshagrawal84. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@hiteshagrawal84 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@hiteshagrawal84, thank you for your report. rest/V1/products/{sku} it's admin endpoint, and catalog price rules apply on storefront on the fly. If you take a look at product on product edit page in admin area, there will be no special price to.

**Comment by hiteshagrawal84** [comment]
Yes but it should work in api , as api will use in 3rd party application like android app or other applications , so price should come perfectly whatever it is displaying in storefront.

**Comment by magento-engcom-team** [comment]
Hi @hiteshagrawal84. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/75

**Comment by erankitsrivastava** [comment]
> @hiteshagrawal84, thank you for your report. rest/V1/products/{sku} it's admin endpoint, and catalog price rules apply on storefront on the fly. If you take a look at product on product edit page in admin area, there will be no special price to.

the same thing also doesn't work in the catalog search API rest/V1/products, and it is meant for the customer's end?
