### ISSUE TITLE
Breadcrumb and product image not showing while using Quataion mark(") in product name

### ISSUE THREAD

**Issue by rohitkundale** [magento/magento2#16522]
### Preconditions

1. Magento version 2.2.5
2. Any compatible web browser

### Steps to reproduce

1. Log in to Admin Panel
2. Navigate to "Catalog" -> "Products" -> "Open Any Product"
3. Add Quataion mark(**"**) symbol in product name.
4. Click on *Save*
![2018_07_04_admin-view](https://user-images.githubusercontent.com/10629382/42262363-b5df5dc0-7f88-11e8-9b25-3ec7cc5ed626.png)

### Expected result

1. Go to front end of the store.
2. Open updated product from admin. There should be breadcrumb on the page.
![with-breadcrumb](https://user-images.githubusercontent.com/10629382/42262513-22e1e758-7f89-11e8-80eb-b7163fff9ae6.png)

### Actual result

1. There is nothing, no breadcrumb on product page. and i can see js error in console.
![screenshot from 2018 07 04 12 54 05](https://user-images.githubusercontent.com/10629382/42262615-708c2d1a-7f89-11e8-8a24-ed8df9e979e8.png)

**Comment by magento-engcom-team** [comment]
Hi @rohitkundale. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@rohitkundale do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@rohitkundale, thank you for your report. This issue already fixed in 2.3-develop, 2.2-develop and will be available in next release of 2.2.x(2.2.6)

**Comment by mohsinahmed22** [comment]
Still facing this issue on 2.2.6

**Comment by DanielRuf** [comment]
There is no "fixed in 2.2.x" label. Afaik it will be in .7 or .8.

**Comment by akellberg-zz** [comment]
Also having this issue in 2.2.6

This is bug makes Magento unusable for anyone experiencing it. If my customers can't see my product images, everyone will leave.
I see  its marked "Fixed in 2.3.x", but what do you suggest in meantime? Can you provide a work-around for 2.2.6, or do you suggest we just wait for 2.3.x to be released?
