### ISSUE TITLE
Product rest api is not returning results in magento 2.2.5

### ISSUE THREAD

**Issue by Gurdit** [magento/magento2#16536]
### Preconditions

1. Magento 2.2.5
2. php 7.0.30

### Steps to reproduce

1. Hit Product rest api for 200k products with pageSize = 0 to return full 200k items.
2. Consumer Key : **[redacted]**
3. Consumer Secret : **[redacted]**
4. Access Token : **[redacted]**
5. Access Token Secret : **[redacted]**

 `$requestUrl='**[redacted]**/rest/V1/products?searchCriteria=0&searchCriteria[filter_groups][0][filters][0][field]=visibility&searchCriteria[filter_groups][0][filters][0][value]=4&searchCriteria[filter_groups][0][filters][0][condition_type]=eq'

			$ch = curl_init($requestUrl);
			curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
			curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-Type: application/json","Authorization: Bearer  **[redacted]**"));
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			$result = curl_exec($ch);
			$result = json_decode($result,true);
                        echo 'Items Count =>  '.count($result['items']);
`

### Expected result

1. [Return the items requested on the api]

### Actual result

1. [Blank page with no errors and no result]

**Comment by magento-engcom-team** [comment]
Hi @Gurdit. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Gurdit do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Gurdit** [comment]
yes @magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @Gurdit. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Gurdit, here is your [Magento instance](https://i-16536-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16536-2-2-5.engcom.dev.magento.com/admin](https://i-16536-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Gurdit** [comment]
@magento-engcom-team I cannot import 200k+ products on provided Vanilla instance and test it with product rest api, so I'm unable to reproduce the issue on your test server.

**Comment by orlangur** [comment]
`pageSize = 0 ` why it should return all products?

**Comment by Gurdit** [comment]
`/rest/V1/products?searchCriteria=0 helps to remove pagination and retrieve all the products stored in magento on a single instance`
`
    [search_criteria] => Array
        (
            [filter_groups] => Array
                (
                )

        )

    [total_count] => 2046`

**Comment by orlangur** [comment]
@Gurdit, ok, it's `searchCriteria = 0`, not `pageSize = 0`.

**Comment by magento-engcom-team** [comment]
@Gurdit Please avoid posting links to any of your live websites, specifically with the API keys in the same post.

**Comment by engcom-backlog-nickolas** [comment]
Hello @Gurdit, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Gurdit** [comment]
Hello @engcom-backlog-nickolas , Thank you for the acknowledgement .

**Comment by AfreenScarlet** [comment]
#dmcdindia1

**Comment by Vbak** [comment]
If someone has a similar problem for me the problem was the json_encode.
vendor/magento/zendframework1/library/Zend/Json.php

function encode line 154: $encodedResult = json_encode($valueToEncode);
I added the json_last_error and I saw that it was giving me an error with utf-8 encoding. That error wasn't showing anywhere until I managed to debug the REST API session.

I hope it will help someone.
