### ISSUE TITLE
There is no ability to control order of mixins applying

### ISSUE THREAD

**Issue by DenyVeyten** [magento/magento2#16535]
https://github.com/magento/magento2/blob/a021f0f5a9bbe8769496528b7d07450a553832c2/lib/web/mage/requirejs/mixins.js#L126

The Object.keys() method returns an array of a given object's property names, in the same order as we get with a normal loop ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)).

A for...in loop iterates over the properties of an object in an arbitrary order [(source)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

For now we can load or not load mixins with

`"mixin_name": true|false`

and have no ability to control mixins applying order or create mixin for mixin.

**Comment by magento-engcom-team** [comment]
Hi @DenyVeyten. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@DenyVeyten do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DenyVeyten** [comment]
One of solution (not very well) is to set some type of `sortOrder` as integer for mixins like

`"mixin_name": 25|false`

**Comment by orlangur** [comment]
This is intended behavior. Similar to observers, if order of mixin calls matters, they are written the wrong way.

**Comment by DenyVeyten** [comment]
@orlangur thanks for reply, seems like it's very true, just mixins can be used for rewriting some methods of component, so this is just wrong usage of mixins when two mixins rewrite one method of original component? Or they must be written in the way where calls order really don't matter even when rewritting occurs?

**Comment by magento-engcom-team** [comment]
@DenyVeyten please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by orlangur** [comment]
@DenyVeyten,

> Or they must be written in the way where calls order really don't matter even when rewritting occurs?

This way. When mixin completely changes / kills method behavior this is a misuse of mixin.

**Comment by DenyVeyten** [comment]
@orlangur thanks a lot for advice!
