### ISSUE TITLE
Wrong currency in a multi-view / multi-currency store

### ISSUE THREAD

**Issue by herod2k** [magento/magento2#16539]
### Preconditions
1. Magento 2.2.5 (vanilla) with sample products 
2. Php 7.1.19
3. Apache 2.4.33
4. Operating system: Fedora 28

### Steps to reproduce
1. Install Magento 2.2.5 with sample products 
2. During the installation configure Magento with dollars as default currency
![image](https://user-images.githubusercontent.com/3713164/42285619-144b7d02-7fa8-11e8-8f67-28e5a44744ce.png)
3. Once installed create an additional view for an additional language (Italian for instance)
![image](https://user-images.githubusercontent.com/3713164/42285747-5dfba6ca-7fa8-11e8-9973-619d763dbc50.png)
4. Rename the default view in English
![image](https://user-images.githubusercontent.com/3713164/42285782-7567d8f6-7fa8-11e8-89e9-1a8e5cb3ff86.png)
![image](https://user-images.githubusercontent.com/3713164/42285843-ab02b1de-7fa8-11e8-9365-226c172cf693.png)
5. Assign a different currency for each view
Pounds for the English view 
![image](https://user-images.githubusercontent.com/3713164/42285865-b8f865c2-7fa8-11e8-98a9-b5a62a6caca8.png)
Euro for the Italian view
![image](https://user-images.githubusercontent.com/3713164/42285942-007bb9a8-7fa9-11e8-8b73-2657f4cff79c.png)
6. Flush the cache
7. Open the front-end website
8. Open a product with using the English view 
 
### Expected result
I should see the product using the British pound currency 

### Actual result
![image](https://user-images.githubusercontent.com/3713164/42286033-6040cc20-7fa9-11e8-9d5e-f7b6edb7f06c.png)
Magento get the default currency, configured during the setup instead the value configured in the admin panel.

### Additional info
The Italian version works perfectly
![image](https://user-images.githubusercontent.com/3713164/42286112-a59a3e5a-7fa9-11e8-874b-85ff0027e13c.png)
I can see the product in Euros, as you can see on the screenshot.

I have also tried with multi-store configuration, instead of a multi-view configuration, but Magento still get the default currency.

**Comment by magento-engcom-team** [comment]
Hi @herod2k. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@herod2k do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by herod2k** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @herod2k. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @herod2k, here is your [Magento instance](https://i-16539-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16539-2-2-5.engcom.dev.magento.com/admin](https://i-16539-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-backlog-nickolas** [comment]
Hello @herod2k, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by herod2k** [comment]
I think I have found the bug.

Magento doesn't fill the record for the default store currency
![image](https://user-images.githubusercontent.com/3713164/42316561-145cc5ae-8042-11e8-8873-7ee93952b3a8.png)

During the conversion, Magento doesn't find the value inside the DB and it returns false for the Currency and it picks the default currency.

**Comment by federicosoich** [comment]
#mm18ar

**Comment by magento-engcom-team** [comment]
@federicosoich thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by federicosoich** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @federicosoich. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @federicosoich, here is your [Magento instance](https://i-16539-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16539-2-2-5.engcom.dev.magento.com/admin](https://i-16539-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @andrewbess. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by andrewbess** [comment]
Hello @herod2k 
It hasn't reproduced on Magento (all versions).
You are not filled currency rates in steps to reproduce.
Please clarify, are you filled it?
Thank you in advance.

**Comment by andrewbess** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @andrewbess. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, here is your [Magento instance](http://34.228.235.121/i-16539-2-3-develop/).
Admin access: [http://34.228.235.121/i-16539-2-3-develop//admin](http://34.228.235.121/i-16539-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @herod2k. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-93383` was closed as `non-reproducible` in `2.2-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @herod2k. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-93384` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
