### ISSUE TITLE
After Unhold Order , Order status empty 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16533]
Preconditions
Magento CE 2.2.3
PHP 7.0.30-1+0~20180505045735.18+stretch~1.gbpcfecb9 

### Steps to reproduce
From order, view click on **Hold** button so order status is **Hold** , Now Click on "Unhold" button/
Then after order status is empty https://prnt.sc/k2g1ak.

### Expected result
Order status must be pending
### Actual result

Order status empty https://prnt.sc/k2g1ak

**Comment by magento-engcom-team** [comment]
Hi @navinbhudiya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@navinbhudiya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@navinbhudiya, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![peek 2018-07-04 16-04](https://user-images.githubusercontent.com/40756187/42278694-5c52a516-7fa4-11e8-8df6-cc4485ac776f.gif)
