### ISSUE TITLE
Magento 2.2.x setup get in a loop using /pub

### ISSUE THREAD

**Issue by herod2k** [magento/magento2#16538]
### Preconditions
1. Magento 2.2.5 (but I have also tried it in Magento 2.2.4 and 2.2.0) 
2. Php 7.1.19
3. Apache 2.4.33
3. Operating system: Fedora 28

### Steps to reproduce
1. Download last version of Magento 2.2 from (https://magento.com/tech-resources/download)
2. Decompress it in your public_html folder (we get the error also installing Magento trough Composer)
3. Configure your virtualhost like that:
```
<VirtualHost *:80>
    ServerAdmin webmaster@domain.test
    DocumentRoot "/home/user/public_html/domain/pub"
    ServerName domain.test
    ErrorLog logs/domain.test-error_log
    CustomLog logs/domain.test-access_log common

    <Directory "/home/user/public_html/domain/pub">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
    </Directory>
</VirtualHost>
```
4.  add `127.0.0.1 domain.test` to your /etc/hosts
5. open the url http://domain.test

### Expected result
We should see the installation Magento page:
![image](https://user-images.githubusercontent.com/3713164/42282092-595f02fc-7f9d-11e8-9924-3762b99c5787.png)

### Actual result
We get a loop error.
![image](https://user-images.githubusercontent.com/3713164/42282319-014ee4e6-7f9e-11e8-9188-ec5f58e1bfe6.png)

Also from cli:
```
$ wget domain.test
--2018-07-04 15:09:21--  http://domain.test/
Resolving domain.test (domain.test)... 127.0.0.1
Connecting to domain.test (domain.test)|127.0.0.1|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:21--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:21--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:21--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:22--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:23--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:23--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:23--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:23--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:23--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:23--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
--2018-07-04 15:09:23--  http://domain.test/setup/
Reusing existing connection to domain.test:80.
HTTP request sent, awaiting response... 302 Found
Location: /setup/ [following]
20 redirections exceeded.
```

### Workaround
1. Configure the virtualhost pointing the website to the root folder /home/user/public_html/domain/
2. Install Magento
3. Once installed change the folder to /home/user/public_html/domain/pub

**Comment by magento-engcom-team** [comment]
Hi @herod2k. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@herod2k do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by herod2k** [comment]
@magento-engcom-team it is an installation/configuration bug, I can't reproduce it on a vanilla Magento instance

**Comment by ghost** [comment]
@herod2k, thank you for your report. 
This is not a bug.  Please refer to the [Magento Dev Docs](https://devdocs.magento.com/guides/v2.2/install-gde/tutorials/change-docroot-to-pub.html).

**Comment by herod2k** [comment]
Hello,

I've checked again following your devdocs, I made a new installation, using **test.test** as domain.
This is my virtualhost configuration:
```
<VirtualHost *:80>
        ServerName test.test
        ServerAdmin webmaster@localhost
        DocumentRoot /home/herod/public_html/test/pub
        ErrorLog logs/test-error.log
        CustomLog logs/test-access.log combined

        <Directory "/home/herod/public_html">
                AllowOverride all
        </Directory>
</VirtualHost>
```

It is very similar to what you suggest in your documentation:
![image](https://user-images.githubusercontent.com/3713164/42369899-3247d88a-8103-11e8-88d6-4144a00ad127.png)
The main differences are:
1. I'm using a ServerName
2. My document root is inside a public_html user folder
3. I don't have the ${APACHE_LOG_DIR}

Using the suggested configuration with the **/pub** as root folder I get the same error:
![image](https://user-images.githubusercontent.com/3713164/42370019-8f5c9e2a-8103-11e8-8d9d-2cd565685ba3.png)
(too many redirect on /setup/)

If I remove the **/pub** at the end of the DocumentRoot the setup works.

In your documentation you suggest to use **/pub** as DocumentRoot folder and it doesn't work (for the installation) so I think that it is a bug.

I have also noticed that if you lunch the setup without the /pub at the end of the DocumentRoot and after you edit the virtualhost and re-add the /pub at the end, reload apache and reload the setup. It works. But it works only if you lunch it for the first time without /pub inside the DocumentRoot.

Regards,
H2K

**Comment by PascalBrouwers** [comment]
@magento-engcom-team this is a bug when serving the site from the /pub directory. Magento cannot be installed via the browser that way.
Symlinking the setup folder in /pub fixed it but I wonder if this is the correct way to do it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @herod2k  hi @PascalBrouwers  this is not a bug, according to devdocs -> 

Before you begin
To complete this tutorial, you’ll need access **to a working Magento installation** running on a LAMP stack:

https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html

**Comment by herod2k** [comment]
Hi @engcom-backlog-nazar ,

we are not changing the docroot to pub, if you install it and you change the docroot to pub, it works, there is no problem there.

The problem is: if you install it directly using /pub it doesn't work, you get a loop error. It should be allowed to install from /pub, why we should install and change the docroot? It doesn't make very much sense.

**Comment by ghost** [comment]
@herod2k Yes, that what i'm talking about, to use pub as root directory, dev docs says :that you have already installed magento. 
`To complete this tutorial, you’ll need access to a working Magento installation`

**Comment by herod2k** [comment]
@engcom-backlog-nazar sorry but the devdocs it is not clear.

The devdocs: https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html says:
> If you installed Magento in Apache’s default docroot /var/www/html, the Magento file system is vulnerable because it’s accessible from a browser. This topic describes how to change the Apache docroot on an existing Magento instance to serve files from the Magento pub/ directory, which is more secure.
> 
> Serving files from the pub/ directory prevents site visitors from accessing the Web Setup Wizard and other sensitive areas of the Magento file system from a browser.

If I read this, I understand that: if you have "already" installed Magento with the docroot to /var/www/html please change it because it is not secure. Plus the sentence "If you installed Magento in Apache’s default docroot" gives me the idea that I have other install options.

It should more clear that "this is the only way to get Magento working on /pub". If this is not a bug, it is a least a documentation problem.

**Comment by ghost** [comment]
@herod2k  Yes, this is issue of the documentation that does not always accurately describe a particular process, you can report here -> https://github.com/magento/devdocs/issues, Or create a PR to solve this problem.
