### ISSUE TITLE
using soap, product is created but description field is empty

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#16541]
### Preconditions
Magento 2.2.2 with one website, one store and two storeviews on ubuntu/nginx/php7

### Steps to reproduce
- call soap service and pass the data of the product you want to create: 
$newproductdata = array(
	'sku' => 'prodotto7',
	'name' => 'Prodotto7',
	'attributeSetId' => 4,
	'visibility' => 4,
	'typeId' => 'simple',
	'price' => '50',
	'status' => 1,
	'weight' => '1',
	'custom_attributes' => [
		['attribute_code' => 'description', 'value' => 'Test Description' ],
		['attribute_code' => 'short_description', 'value' => 'Test Short Description' ],
	],
);
$soapClient = new SoapClient("$baseurl=catalogProductRepositoryV1", $options);
$response = $soapClient->catalogProductRepositoryV1save(array('product' => $newproductdata));

### Expected result
product is created with description and short description

### Actual result
product is created but description, short description and all other parameters set in custom_attributes (eg category ids) are not present

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LouNik1984** [comment]
@magento-engcom-team give me 2.2.2 instance

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your request. I'm working on Magento 2.2.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984, here is your [Magento instance](https://i-16541-2-2-2.engcom.dev.magento.com).
Admin access: [https://i-16541-2-2-2.engcom.dev.magento.com/admin](https://i-16541-2-2-2.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by LouNik1984** [comment]
Hi, I confirm I can reproduce the issue on your vanilla instance. 

### Steps to reproduce
- run the script to add a new product via soap api
$newproductdata = array(
	'sku' => 'prodotto1',
	'name' => 'Prodotto1',
	'attributeSetId' => 4,
	'visibility' => 4,
	'typeId' => 'simple',
	'price' => '50',
	'status' => 1,
	'weight' => 1,
	'custom_attributes' => [
		['attribute_code' => 'description', 'value' => 'Test Description' ],
		['attribute_code' => 'short_description', 'value' => 'Test Short Description' ],
	],
);
$soapClient = new SoapClient("$baseurl=catalogProductRepositoryV1", $options);
$response = $soapClient->catalogProductRepositoryV1save(array('product' => $newproductdata));
- logged in magento backend to check the newly created product

### Expected result
Product should have all the attributes mentioned in the array

### Actual Result
Product is created but the attributes mentioned in the "custom_attributes" key of the array are missing

**Comment by engcom-backlog-nickolas** [comment]
Hello @LouNik1984, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by AfreenScarlet** [comment]
#dmcdindia1

**Comment by KotsVladimir** [comment]
@magento I'm working on it
