### ISSUE TITLE
Old categories are not removed from product when using setCategoryIds

### ISSUE THREAD

**Issue by aligent-lturner** [magento/magento2#16548]
### Summary
When saving a product after calling `setCategoryIds($categoryIds)` function, any existing categories are maintained, regardless of whether they are present in the `$categoryIds` array or not.

Existing 3rd-party code relies on the setCategoryIds function as a means of assigning products to categories - this method worked in 2.1, and is expected to still work in 2.2

### Preconditions
1. Magento 2.2.3
2. PHP 7.0
3. MySQL ver 14.14 Distrib 5.6.39

### Steps to reproduce
1. Create 5 categories named Category 1 - Category 5 and note IDs
2. Create a product, and assign to categories 1, 2 and 3.
3. Run the `saveCategories` function from the following code snippet, using the product id, and replacing the `<category id>` placeholders with the actual ids for categories 3, 4 and 5.
```
class CategorySetter
{
    private $_productFactory;

    public function __construct(\Magento\Catalog\Api\Data\ProductInterfaceFactory $productFactory)
    {
        $this->_productFactory = $productFactory;
    }

    public function saveCategories($productId)
    {
        $product = $this->_productFactory->create();
        $product->getResource()->load($product, $productId);
        $categoryIds = array(<category id>, <category id>, <category id>);
        $product->setCategoryIds($categoryIds);
        $product->getResource()->save($product);
    }
}
```

### Expected result
1. Product is added to categories 4 and 5
2. Product is removed from categories 1 and 2

### Actual result

1. Product is added to categories 4 and 5 (the categories it previously did not belong to)
2. Product remains in categories 1 and 2, despite 1 and 2 not being contained in the `$categoryIds` array.

The function `_saveCategories()` in `\Magento\Catalog\Model\ResourceModel\Product` has been deprecated, which is why this method no longer works, but I would expect that instead, any categories set via `setCategoryIds` should be saved in an alternative manner (e.g. using `\Magento\Catalog\Api\Data\CategoryLinkInterface`). There is no indication (as far as I can tell) in documentation that the `setCategoryIds` method of saving would no longer work in 2.2

**Comment by magento-engcom-team** [comment]
Hi @aligent-lturner. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@aligent-lturner do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by aligent-lturner** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @aligent-lturner. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @aligent-lturner, here is your [Magento instance](https://i-16548-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-16548-2-2-3.engcom.dev.magento.com/admin](https://i-16548-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by aligent-lturner** [comment]
Cannot reproduce in vanilla instance, as reproduction requires PHP code to be run, calling a specific function on the \Magento\Catalog\Model\Product class.

**Comment by engcom-backlog-nickolas** [comment]
Hello @aligent-lturner, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
Provided code snippet is incorrect. `setCategoryIds` is not a part of `\Magento\Catalog\Api\Data\ProductInterface`.

> but I would expect that instead, any categories set via setCategoryIds should be saved in an alternative manner (e.g. using \Magento\Catalog\Api\Data\CategoryLinkInterface)

Such expectation is wrong. It would mean that any deprecated code needs to be refactored to use the new code. Things work exactly an opposite way: you must use code marked with `@api` instead of relying on internal class implementation.
