### ISSUE TITLE
Modal WYSIWYG Image Content Slashes Lost

### ISSUE THREAD

**Issue by PivitParkour94** [magento/magento2#16552]
When rendering WYSIWYG image markup in a modal widget, the media url slashes are being escaped. 

### Preconditions

1. Magento 2.2.5 Community Edition
2. MySQL Ver 15.1 Distrib 10.2.15-MariaDB

### Steps to reproduce

1. Create CMS block with media url
The one I tested with is
```
<p>This is a super cool test</p>
<p><img src="{{media url="wysiwyg/test.png"}}" alt="" /></p>
<h1 data-test="&quot;this/is/my/attribute">Slashes are breaking</h1>
<p>Do you prefer cats/dogs or Fish?</p>
```
2. Make sure the test image exists at `wysiwyg/test.png`
3. Render the CMS page somewhere
4. Create Modal for the div the CMS page is rendered in
```
// example/render/cms.js
define([
    'jquery',
    'mage/template',
    'Magento_Ui/js/modal/modal',
    'mage/translate'
], function ($, mageTemplate, Modal, $t) {
    'use strict';

    var cmsRenderedPopup = $("#cmsRendered");
    cmsRenderedPopup.modal({
        title: this.title,
        innerScroll: true,
        modalClass: 'cms-render',
        buttons: [{
            text: $t('Ok'),
            class: '',
            click: function() {
                this.closeModal();
            }
        }]
    }).trigger('openModal');
});
```

### Expected result

1. Open the modal and the content is rendered as is on viewing the block normally

### Actual result

1. Open the modal and the media url has been rendered as `<img src="{{media url=" wysiwyg=""  test.png"}}"="" alt="">`
2. Full output
```
<p>This is a super cool test</p>
<p><img src="{{media url=" wysiwyg="" test.png"}}"="" alt=""></p>
<h1 data-test=""this/is/my/attribute">Slashes are breaking</h1>
<p>Do you prefer cats/dogs or Fish?</p>
```

#### Note
Originally I thought all slashes were being removed, however all the other slashes are being rendered as expected, so it must be something to do with the modal template rendering

**Comment by magento-engcom-team** [comment]
Hi @PivitParkour94. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@PivitParkour94 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by PivitParkour94** [comment]
Realised I was getting the content of the block, using $block->getContent() rather than rendering the $block. That would do it. I'll close this off.
