### ISSUE TITLE
"Shipping address is not set" exception in Multishipping Checkout.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/magento2#16555]
### Preconditions

1. Magento 2.
2. Multishipping Checkout enabled (by default)
3. Simple Product.
4. Customer.

### Steps to reproduce

1. Log In as Customer.
2. Add Product to Cart.
3. Proceed to Checkout.
4. Fill Shipping Address data, click Next (do not place Order)
5. Return to the Storefront.
6. Go to the Shopping Cart.
7. Click Check Out with Multiple Addresses.

### Expected result

1. Correct Multishipping Checkout workflow.

### Actual result

1. Exception #0 (Magento\Framework\Exception\StateException): Shipping address is not set
2. Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[23000]: Integrity constraint violation when trying to access Shopping Cart.

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@p-bystritsky do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
We've acknowledged the issue and added to our backlog.

**Comment by dmytro-ch** [comment]
I will handle this issue.

**Comment by rogyar** [comment]
I'm able to reproduce this issue on the `2.2-develop` branch.

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your report. 
The issue has been fixed in magento/magento2#16753 by @dmytro-ch in 2.2-develop branch
Related commit(s):
 - [def9a8220117de04bc50628d3e9abfcc06d8cffc](https://github.com/magento/magento2/commit/def9a8220117de04bc50628d3e9abfcc06d8cffc)
 - [4268a7579a9c4de63a21578cd6735bb61535310e](https://github.com/magento/magento2/commit/4268a7579a9c4de63a21578cd6735bb61535310e)
 - [9a47c0ed6df879f4492d77b41b0f3383c788fd40](https://github.com/magento/magento2/commit/9a47c0ed6df879f4492d77b41b0f3383c788fd40)
 - [6f88af5ffe9d4bd633d70aa5ca84d2f15b6a52f5](https://github.com/magento/magento2/commit/6f88af5ffe9d4bd633d70aa5ca84d2f15b6a52f5)
 - [cc440783ee5313daeda1aa9a72619b33a2a6f66c](https://github.com/magento/magento2/commit/cc440783ee5313daeda1aa9a72619b33a2a6f66c)
 - [75c3a2ef0e0bae69ff3a17a48786e392c86fd83f](https://github.com/magento/magento2/commit/75c3a2ef0e0bae69ff3a17a48786e392c86fd83f)

The fix will be available with the upcoming 2.2.7 release.

**Comment by sidolov** [comment]
Hi @p-bystritsky. Thank you for your report. 
The issue has been fixed in magento/magento2#16783 by @dmytro-ch in 2.1-develop branch
Related commit(s):
 - [1e730753da331d3b5a3181211fa47c9ab5accb55](https://github.com/magento/magento2/commit/1e730753da331d3b5a3181211fa47c9ab5accb55)
 - [197f1eba3931819d2a098c5748498c120aaffa06](https://github.com/magento/magento2/commit/197f1eba3931819d2a098c5748498c120aaffa06)
 - [80065d87d71870a453da731094d46bfa3a285ba0](https://github.com/magento/magento2/commit/80065d87d71870a453da731094d46bfa3a285ba0)

The fix will be available with the upcoming 2.1.16 release.

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your report. 
The issue has been fixed in magento/magento2#16784 by @dmytro-ch in 2.3-develop branch
Related commit(s):
 - [ab1324ecc1d5e2990acfd4f14c7b77765d343a9e](https://github.com/magento/magento2/commit/ab1324ecc1d5e2990acfd4f14c7b77765d343a9e)
 - [7187c2e318e41e0e5bf0c93f663e17d543ee5380](https://github.com/magento/magento2/commit/7187c2e318e41e0e5bf0c93f663e17d543ee5380)
 - [9868428966220ddc23fe04f3af985eab2d66ff59](https://github.com/magento/magento2/commit/9868428966220ddc23fe04f3af985eab2d66ff59)
 - [2c546c4d67d1b8434405874f80c02eb898c3dced](https://github.com/magento/magento2/commit/2c546c4d67d1b8434405874f80c02eb898c3dced)

The fix will be available with the upcoming 2.3.0 release.
