### ISSUE TITLE
System requirement issue with Magento Version 2.2.5

### ISSUE THREAD

**Issue by tejasklevu** [magento/magento2#16561]
I am trying to install the Magento 2.2.5 with PHP version 7.0.7 and it is not installed. 

### Steps to reproduce
1. Download the Magento 2.2.5 using composer or manually.
2. Try to install it at the PHP version 7.0.7

### Expected result
Getting the error as our PHP version is 7.0.7. The required PHP version is ~7.0.13|~7.1.0.

### Actual result
It should be installed according to the below guide of system requirements.
https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html
If not, please update the guide.

**Comment by magento-engcom-team** [comment]
Hi @tejasklevu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@tejasklevu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@tejasklevu, thank you for your report.
You are right, this article of Dev Docs is outdated. Actual Magento 2.2 supports 7.0.13 and 7.1.0 or higher PHP versions. Please create an issue on https://github.com/magento/devdocs/issues.
