### ISSUE TITLE
Catalog price rules not working Magento 2.2.4

### ISSUE THREAD

**Issue by DennisxCore** [magento/magento2#16574]
**Preconditions**
Magento v2.2.4
PHP 7.0.30 running on Plesk Server

**Steps to reproduce**
![reproduce1](https://user-images.githubusercontent.com/39742004/42361846-a771b2c4-80f0-11e8-959b-7eb9ff685b1c.JPG)
![reproduce2](https://user-images.githubusercontent.com/39742004/42361847-a78c7276-80f0-11e8-87ea-7b6e5e08b0d0.JPG)

My User is "Wholesale".

**Expected result**
Normally it should do -20% on every product.. because its a reseller.

**Actual result**
![reproduce3](https://user-images.githubusercontent.com/39742004/42361863-c2e44c74-80f0-11e8-8a64-6aed25da6422.JPG)

Maybe someone can please help me? I dont find the reason why it dont work...

Best regards,
Dennis

**Comment by magento-engcom-team** [comment]
Hi @DennisxCore. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@DennisxCore do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DennisxCore** [comment]
yes

**Comment by ghost** [comment]
@DennisxCore, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by arnoudhgz** [comment]
@DennisxCore did you do a complete reindex with `bin/magento indexer:reindex`? Did you clean the appropriate caches?

**Comment by DennisxCore** [comment]
Yes I tried everything. I cleared the cache in Magento 2, and I reindex all via the "bin/magento indexer:reindex" command.

**Comment by arnoudhgz** [comment]
@DennisxCore  I had something similar in the past, what did the trick for me back then was setting the from date (`Bis` is your case) in the near future. And having the cron do the index updates on schedule.

**Comment by DennisxCore** [comment]
@arnoudhgz you mean the from (von) date or to (bis) date? Here are my full settings now.

![fireshot capture 016 - 20 fur handler _ katalogpreisregel __ - https___www koemo de_admin_1ifq04_](https://user-images.githubusercontent.com/39742004/42519570-9bafc83c-8464-11e8-88a1-aae9580bd78c.png)

**Comment by arnoudhgz** [comment]
@DennisxCore sorry, no my case was with the Scheduled Update. Can't help you out here :(

**Comment by DennisxCore** [comment]
Now everything working. I dont know why, I think because I setting from and to date. Thank you for your help @arnoudhgz !
