### ISSUE TITLE
Amzone email issue magento2.2.4

### ISSUE THREAD

**Issue by wclshashank** [magento/magento2#16575]
I am getting the issue through Amazon Pay. The issue is: After making an order getting mail from server name. Actually, need to get from admin configuration.
While I'll disable Amazon module issue resolved.
using php bin/magento module:disable Amazon_Core Amazon_Login  Amazon_Payment Aheadworks_Blog 
And after this email sender is according to configuration.
Can anyone help on thisn?

Thanks,
shashank

**Comment by magento-engcom-team** [comment]
Hi @wclshashank. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@wclshashank do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

Amazon Pay module resides here: https://github.com/amzn/amazon-payments-magento-2-plugin
