### ISSUE TITLE
Segmentation fault installing Magento 2.2

### ISSUE THREAD

**Issue by cbichis** [magento/magento2#16589]
Hi,

Trying to install Magento 2.2.5 CE on PHP 7.0.30, 5.6.39 on FreeBSD 11.2 is failing at:

[Progress: 248 / 466]
Module 'Magento_Catalog':
Installing data... Segmentation fault

The CLI command is

sudo -u myserveruser ./magento setup:install --admin-email email@domain.com --admin-firstname=Magento --admin-lastname=User --admin-user myuser --admin-password mypass --base-url https://domain.com --backend-frontname myadmin --db-name mydb --db-user myuser --db-password mypassword --use-secure 1 --language=ro_RO 
--currency=RON --timezone=Europe/Bucharest --cleanup-database --use-rewrites=1

With web based install the same problem, install is getting stuck at 53% on the same Installing data part...

**Comment by magento-engcom-team** [comment]
Hi @cbichis. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@cbichis do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@cbichis there is nothing Magento can fix here with such bug report. You need to investigate further on your side. Did you try to obtain actual PHP stack trace? Did increasing memory limit help? Does it work on your server in case of using locale/currency en_US?

**Comment by ghost** [comment]
@cbichis, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by chrcoluk** [comment]
Some clarification please as to what is meant by vanilla and the best place to report this bug, pointing to generic support forums indexes isnt really helpful.

Also some clarification what a Magento Core technical issue is please.

Regards

Chris
