### ISSUE TITLE
How to disable saveParametersInSession in admin grid when I used ui Component?

### ISSUE THREAD

**Issue by radhagobinda** [magento/magento2#16591]
### Preconditions

1. Magento version: 2.1.4
2. PHP version: 5.6

### Steps to reproduce

Actually this is not a bug that I want to fixed it. This is kind of information that I want to know from this community. 
I want to disabled saveParametersInSession in admin grid when I used Ui Component. I cannot find any elements that I could disabled this option. If any one knows that, Please share with us.

### Expected result

Actually when I filtered in a grid in admin panel that is saved in session by default, then after page load this search is appeared again. But I want to show full data after page load. I know how to disable saveParametersInSession in grid but when this grid use UI Component then the problem is occurred.

Please let me know if any one know that. 

### Actual result

![customers customers magento admin](https://user-images.githubusercontent.com/19976130/42375467-425fb6f8-8139-11e8-8368-b8961f3f605a.png)

**Comment by magento-engcom-team** [comment]
Hi @radhagobinda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@radhagobinda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@radhagobinda, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
