### ISSUE TITLE
Magento\SalesRule\Rule should implement RuleInterface

### ISSUE THREAD

**Issue by herman-aka-wouter** [magento/magento2#16598]
Unable to use RuleRepository to save sales Rule.

### Preconditions

1. Create a `Magento\SalesRule\Rule` using `RuleFactory`
2. 

### Steps to reproduce

1. Try to save `Rule` using `RuleRepository`
2. 
3. 

### Expected result

1. Rule should be saved

### Actual result

1. Expected instance of `RuleInterface` given `Rule`

**Comment by magento-engcom-team** [comment]
Hi @wouter-toppershops. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@wouter-toppershops do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ishakhsuvarov** [comment]
Hi @wouter-toppershops 
`\Magento\SalesRule\Model\Data\Rule` seems to be the preference for the `RuleInterface`.  `RuleInterfaceFactory` seems to be the one to do the job

**Comment by herman-aka-wouter** [comment]
Hi @ishakhsuvarov,
If I use `\Magento\SalesRule\Model\Data\Rule` the `setCouponCode` method is missing: `Call to undefined method Magento\SalesRule\Model\Data\Rule::setCouponCode()`

the `setCouponCode()` function is available in the `Rule` but not in the `RuleInterface` 


 i looked into the default save method of magento of saving sales rules
`Magento\SalesRule\Controller\Adminhtml\Promo\Quote\Save` 

in that code you using the `Rule` model directly and call the `save()` function in `AbstractModel`  
but i dont want to use the `Rule` model directly for saving because its deprecated.

**Comment by Swahjak** [comment]
So `AbstractModel::save()` is deprecated, `RuleRepository::save()` doesn't accept a `Model\Rule` how are we supposed to save a `Model\Rule`?

On a side note: Is `RuleInterfaceFactory` a thing? A interface can not be constructed? Magento 2 keeps amazing me...

**Comment by ishakhsuvarov** [comment]
@wouter-toppershops 
`\Magento\SalesRule\Api\Data\CouponInterface` seems to have links to the `RuleId`. It makes sense to check if it works other way round, creating a rule, and then a coupon for that rule.

**Comment by orlangur** [comment]
@wouter-toppershops,

> If I use \Magento\SalesRule\Model\Data\Rule the setCouponCode method is missing: Call to undefined method Magento\SalesRule\Model\Data\Rule::setCouponCode()

You cannot use repositories to save something not included in data interfaces => you cannot just pass legacy models into repositories. Coupon is separate entity and needs to be persisted accordingly instead of mixing altogether in one model class.

**Comment by Swahjak** [comment]
@orlangur 
> you cannot just pass legacy models into repositories.

I get what your saying here, but 'just legacy' models seems out of place. Looking at other models in Magento 2 suggest no such thing as 'legacy' models. `Magento\Catalog\Model\Product` extends `ProductInterface`, `Magento\Cms\Model\Page` implements `PageInterface`. Based on these core models I would say that saving a model trough the repository is exactly what we should be doing. That still leaves the question:

> So `AbstractModel::save()` is deprecated, `RuleRepository::save()` doesn't accept a `Model\Rule` how are we supposed to save a `Model\Rule`?

**Comment by orlangur** [comment]
@Swahjak product and CMS are legacy models as well and workability only guaranteed within ProductInterface/PageInterface. Check https://github.com/magento/magento2/issues/16598#issuecomment-403068907 for a way to go.

**Comment by Swahjak** [comment]
@orlangur I think we have a different definition of legacy. If I'm correct you are talking about the fact that 'setCoupon' is not part of the Interface 'contract', which I get. But what I do not understand is how to work with Repositories in combination with models if the model does not extend an interface. Are you trying to say that all future models will be in `Model\Data`?

**Comment by orlangur** [comment]
@Swahjak in order to set coupon data you should find a proper contract-interface first and then use it. There is no need to think about underlying model at all.

If at some point legacy model will be replaced with a more lightweight one, your code following contracts won't break you may even not notice the difference.

**Comment by Swahjak** [comment]
@orlangur that's the part that I do get. I understand why we use interfaces. 

What I do not understand is why there are 2 models. One which is the 'regular' Magento 2 model (`Model\Rule`) and why there is a secondary 'data' model `Model\Data\Rule`. And why only the second can be saved without using deprecated functions. Both models have the exact same purpose; persistence. From that perspective not implementing `RuleInterface` with `Model\Rule` is still a bug (to me).

The confusion is about why the default Magento model is unusable since I can not save it using the recommended method: repositories. On one hand Magento 2 is going in the direction of using Repositories, but interfaces are not implemented across the board.

**Comment by orlangur** [comment]
> From that perspective not implementing `RuleInterface` with `Model\Rule` is still a bug (to me).

No, and you shouldn't even think about underlying implementation. In some cases interface was added to existing legacy models, in some cases new data models were introduced (I saw such approach in `Customer` module).

> Both models have the exact same purpose; persistence.

This is completely wrong. None of these models is supposed to persist itself. Persistence is responsibility of resource models, repositories, sometimes entity manager (see https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/EntityManager/EntityManager.php#L15).

**Comment by Swahjak** [comment]
> No, and you shouldn't even think about underlying implementation.

I don't want to, but then
> In some cases interface was added to existing legacy models, in some cases new data models were introduced (I saw such approach in Customer module).

I have to. In some cases I have to use a Model, in some cases I have to use a Data Model. Sometimes you can save Models with a repository, sometimes you can't. Exactly my point. 

> This is completely wrong. None of these models is supposed to persist itself.

Fair enough, I should have been more precise here. My point is that both models hold data destined for persistence.

**Comment by orlangur** [comment]
@Swahjak you DON'T have to use an underlying model directly. Please check https://github.com/magento/magento2/issues/16598#issuecomment-403058402 on this.

Such factory always produces instance persistable via repository.

**Comment by drazulay** [comment]
> > From that perspective not implementing `RuleInterface` with `Model\Rule` is still a bug (to me).
> 
> No, and you shouldn't even think about underlying implementation. In some cases interface was added to existing legacy models, in some cases new data models were introduced (I saw such approach in `Customer` module).
> 
> > Both models have the exact same purpose; persistence.
> 
> This is completely wrong. None of these models is supposed to persist itself. Persistence is responsibility of resource models, repositories, sometimes entity manager (see https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/EntityManager/EntityManager.php#L15).

I have to say.. I get why Magento is moving towards a separation between DTOs and models, but the implementation and documentation is nothing short of horrible. It took me way, way too long figure out how to save new conditions to sales rules. Disappointed in the documentation, first and foremost.
