### ISSUE TITLE
I would just like to decide the default direction of the products in the categories

### ISSUE THREAD

**Issue by eTonki** [magento/magento2#16610]
Good morning,
I know that the problem has already been posed in the past,
but the problems were closed without ever giving a definitive solution.
I would just like to decide the default direction of the products in the categories.
Officially how can you do it in Magento?

### Preconditions
Magento 2.1.x
PHP 7.0.18
MySQL 5.7.18

### Steps to reproduce
Upgrade from 2.1.x to 2.2.x

### Expected result
No errors!

### Actual result
in the child theme, in this folder
...app/design/frontend/Smartwave/porton_child/Magento_Catalog/layout
I have always used this code to choose the sorting direction:

```
...
<referenceContainer name="content">
    <block class="Magento\Catalog\Block\Category\View" name="category_desc_main_column" template="category/desc_main_column.phtml" ifconfig="porto_settings/category/category_description" before="category.products"/>
    <referenceBlock class="Magento\Catalog\Block\Product\ListProduct" name="category.products.list" as="product_list">
        <action method="setDefaultDirection">
            <argument name="dir" xsi:type="string">desc</argument>
        </action>
    </referenceBlock>
</referenceContainer>
...
```
since version 2.2.x does not work, I get this error:

```
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Theme layout update file '/home/usetonki/public_html/shop/app/design/frontend/Smartwave/porton_child/Magento_Catalog/layout/catalog_category_view.xml' is not valid.
Opening and ending tag mismatch: referenceContainer line 12 and referenceBlock
 Line: 21
Opening and ending tag mismatch: body line 8 and referenceContainer
 Line: 22
Opening and ending tag mismatch: page line 7 and body
 Line: 27
Extra content at the end of the document
 Line: 28
```

can not you use it anymore?

how can the sorting be decided now?

**Comment by magento-engcom-team** [comment]
Hi @eTonki. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@eTonki do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

Probably not including referenceBlock into referenceContainer can help.
