### ISSUE TITLE
Magento Di Issue with Plugin in Rest Api

### ISSUE THREAD

**Issue by ilyasmuyiwa** [magento/magento2#16614]
### Preconditions

1. PHP 7.1
2. Version MySQL 5.6
3. Magento EE v2.1.6

### Steps to reproduce

1. Add New Extension Attributes
```
<extension_attributes for="Magento\Quote\Api\Data\CartItemInterface">
    <attribute code="is_in_stock" type="integer" />
</extension_attributes>
```
2.  Create Plugin 
```
<config` xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Quote\Api\CartItemRepositoryInterface">
        <plugin name="stock" type="Vendor\ModuleName\Plugin\StockMessage" disabled="false" sortOrder="70"/>
    </type>
</config>
```

3. Use Plugin
 ```
public function aroundGetList(CartItemRepositoryInterface $subject, \Closure $proceed, $cartId)
    {
        $cartItems = $proceed($cartId);
        foreach ($cartItems as $item) {
            $extensionAttributes = $item->getExtensionAttributes();
            if ($extensionAttributes === null) {
                $extensionAttributes = $this->cartItemExtensionFactory->create();
            }
            $sku = $item->getSku();
            $stock = $this->stockRegistry->getStockItemBySku($sku)->getIsInStock();
            if ($stock) {
                $message = 1;
            } else {
                $message = 0;
            }
            $extensionAttributes->setIsInStock($message);
            $item->setExtensionAttributes($extensionAttributes);
        }

        return $cartItems;
    }

```

### Expected result
1. The expected result response in rest/V1/carts/mine/items is
{
"item_id": 1111111,
"sku": "22222222",
"qty": 2,
"name": "AAAAAAAA",
"price": 1111,
"product_type": "configurable",
"quote_id": "111",
"product_option": {
"extension_attributes": {
"configurable_item_options": [
{
"option_id": "90",
"option_value": 13
},
{
"option_id": "20",
"option_value": 93
}
]
}
},
"extension_attributes": {
"is_in_stock": 1
}
}

### Actual result

1. The Actual result is
{
"item_id": 1111111,
"sku": "22222222",
"qty": 2,
"name": "AAAAAAAA",
"price": 1111,
"product_type": "configurable",
"quote_id": "111",
"extension_attributes": {
"is_in_stock": 1
}
}
Magento removes this 
"product_option": {
"extension_attributes": {
"configurable_item_options": [
{
"option_id": "90",
"option_value": 42
},
{
"option_id": "270",
"option_value": 1180
}

I noticed when i delete the di folder, it works as expected. I tried both production and developer mode, same result. It seems when magento is generating the di, there are some issue/conflict

**Comment by magento-engcom-team** [comment]
Hi @ilyasmuyiwa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ilyasmuyiwa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@ilyasmuyiwa , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
![peek 2018-07-09 12-24](https://user-images.githubusercontent.com/40756187/42442466-657737f6-8373-11e8-9c8b-40d597d59333.gif)
