### ISSUE TITLE
 magento 2 Export Product Name  Not found exported csv for multi language Product Name  

### ISSUE THREAD

**Issue by matinict** [magento/magento2#16622]
magento 2 Export Product Name  Not found exported csv for multi language Product Name  

### Preconditions

1. multi language
2. Different language For Same Product Name  

### Steps to reproduce

1. Export Product CSV From Admin
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @matinict. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@matinict do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @matinict, thank you for your report. Could you please specify magento version you are using? And what do you mean by "Different language For Same Product Name"? Does your product have different names on different store views?

**Comment by matinict** [comment]
Magento ver. 2.2.3
Store View:  ENG, ARABIC
Different language For Same Product Name:YES
Does your  different names on different store views:YES
There is no store view Select for export/import!!
When 
![import_export _ data](https://user-images.githubusercontent.com/4470372/42562618-04c8cc88-851e-11e8-8cac-4d5fde8f5ea1.png)

**Comment by engcom-backlog-nickolas** [comment]
@matinict, thank you for feedback. Indeed there is no possibility to choose store before export or import, but you will have separate rows in export file for different stores.
![export](https://user-images.githubusercontent.com/40755810/42568399-a890556a-8515-11e8-9d3b-f2d6712c514d.png)
Issue, you described exists in 2.2.3, but has been already fixed in 2.2.5 - which is current release version.

**Comment by matinict** [comment]
Dear Thanks for updates faster & more frequently keep magento fittest.
