### ISSUE TITLE
Lowest and Highest price should be display for Product in api same as it is showing on storefront

### ISSUE THREAD

**Issue by hiteshagrawal84** [magento/magento2#16639]
### Preconditions

1.  Magento 2.2.5 with Sample Data

### Steps to reproduce

1.  Hit the any products api for configurable and bundle products

### Expected result

1. Lowest and highest price should be display for configurable and bundle product

### Actual result

1.  0 price is coming in api.

**Comment by magento-engcom-team** [comment]
Hi @hiteshagrawal84. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@hiteshagrawal84 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hiteshagrawal84** [comment]
Yes

**Comment by engcom-backlog-nickolas** [comment]
Hello @hiteshagrawal84, thank you for your report. If you mean for instance rest/V1/product/{product_sku} - it's admin endpoint. So, information provided by API is the same as from admin area UI and has no min and max prices as frontend has. You may try to calculate this prices from API response data the same way, as it;s done on storefront.

**Comment by hiteshagrawal84** [comment]
@engcom-backlog-nickolas  It should come in api instead of separate calculation as this api can be used in 3rd party application like android app.

**Comment by orlangur** [comment]
@hiteshagrawal84, but, with current API this logic is placed on client side.

GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
