### ISSUE TITLE
Update memory limit

### ISSUE THREAD

**Issue by springimport** [magento/magento2#16651]
### Preconditions
1. Increase PHP Memory limit.

### Steps to reproduce
1. Using [Required PHP settings](https://devdocs.magento.com/guides/v2.2/install-gde/prereq/php-settings.html) page set `memory_limit=2G` in `php.ini`.
2. `phpinfo();` in magento domain.

### Expected result
memory_limit | 2G
-- | --

### Actual result
memory_limit | 756M
-- | --

Problem with `756M` in [nginx.conf.sample](https://github.com/magento/magento2/blob/2.2-develop/nginx.conf.sample#L171). Same result with [.htaccess](https://github.com/magento/magento2/blob/2.2-develop/.htaccess#L39).

**Comment by magento-engcom-team** [comment]
Hi @springimport. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@springimport do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ronak2ram** [comment]
Hello @springimport 

Set memory_limit
`memory_limit=2048M`

After restart apache.

**Comment by orlangur** [comment]
@springimport, everything is correct

> Our detailed recommendations are:
> Compiling code or deploying static assets, 756M
> Installing and updating Magento components from Magento Marketplace, 2G
> Testing, 2G
