### ISSUE TITLE
Spinning Loading Wheels appear over Catalog Section in CMS

### ISSUE THREAD

**Issue by adityagaurin2018** [magento/magento2#16652]
I have installed a Magento 2.2.4 Version without any Sample Data over the server. I have given a custom path of admin instead of generic admin one.

It was installed over the server successfully and CMS login very well.

But now after login when I browse to Catalog section, it keep showing the spinning wheels over the pages and won't allowed to do anything.

### Steps to reproduce
1. Install Magento 2.2.4 without any Sample Data
2. Enter some different path (url) for CMS access
3. After installation login to CMS
4. Click on "Catalog" -> "Products"

### Expected result
It allowed to Manage the products over website.

### Actual result
![spinning-wheel-screen](https://user-images.githubusercontent.com/41010556/42456185-c702a74c-83b1-11e8-8454-412d466a4d0d.png)

Following are the errors which i finding over Developer Console of Browser
![console-error](https://user-images.githubusercontent.com/41010556/42456195-cd94c932-83b1-11e8-809b-ee90d53c20e3.png)

Please advise what I do next to resolve this issue?

Thanks

**Comment by magento-engcom-team** [comment]
Hi @adityagaurin2018. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@adityagaurin2018 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by adityagaurin2018** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @adityagaurin2018. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @adityagaurin2018, here is your [Magento instance](https://i-16652-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16652-2-2-4.engcom.dev.magento.com/admin](https://i-16652-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by adityagaurin2018** [comment]
Hi,
It is not replicating over the above instance!

But it is happening over my installed version, and I have not touched any file and just install to follow the given instructions.

Does to having custom url of CMS instead of "admin" can cause this issue?

What do I next?

Thanks

**Comment by xtremeperf** [comment]
@adityagaurin2018 , can you install and try again using the latest release (2.2.5)?  A major bug was fixed between 2.2.4 and 2.2.5 that would have fixed this type of issue.  Please report back your findings.

Thanks

**Comment by xtremeperf** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @xtremeperf. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @xtremeperf, here is your [Magento instance](https://i-16652-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16652-2-2-4.engcom.dev.magento.com/admin](https://i-16652-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by arnoudhgz** [comment]
The error message shows that it is trying to parse a text/html file. Probably that is a 404 page not found. Did you do all the default `bin/magento` calls, like `setup:upgrade`, `setup:di:compile`, `setup:static-content:deploy`?

**Comment by adityagaurin2018** [comment]
Thanks for all your contribution.

This issue related with Issue number #13610
https://github.com/magento/magento2/issues/13610
