### ISSUE TITLE
config:show output

### ISSUE THREAD

**Issue by jbownds** [magento/magento2#16654]
### Preconditions
1. Magento cloud build
2. php 7.1.13
3. mariadb 10.0.35
4. Magento CLI version 2.2.3

### Steps to reproduce

1. SSH to magento-cloud enviornment
2. Change directory to Bin
3. Run ./magento config:show

### Expected result
1.) A list of the configuration values in the following format:
web@4rlomlxl3j6y4a2hrpu2goapcq:~/bin$ ./magento config:show
web/unsecure/base_url - http://development2-avfnyoi-33idfz6fzbmmy.us-3.magentosite.cloud/
web/secure/base_url - https://development2-avfnyoi-33idfz6fzbmmy.us-3.magentosite.cloud/
web/secure/use_in_adminhtml - 1
general/locale/code - en_US
general/locale/timezone - America/Los_Angeles
general/region/display_all - 1
general/region/state_required - AT,BR,CA,CH,EE,ES,FI,HR,LT,LV,RO,US
currency/options/base - USD
currency/options/default - USD

### Actual result

1. A truncated list of the values and error as follows:
carriers/tablerate/condition_name - package_value
connector_automation/review_settings/allow_non_subscribers - 1
connector_configuration/abandoned_carts/allow_non_subscribers - 1
wishlist/general/multiple_enabled - 1
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Config\Model\Config\Structure\Element\Group::hasBackendModel() in /app/vendor/magento/module-config/Console/Command/ConfigShow/ValueProcessor.php:100

**Comment by magento-engcom-team** [comment]
Hi @jbownds. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@jbownds do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jbownds** [comment]
A native build of cloud from github, locally leverages CLI 2.2.5, which doesn't seem to have this command. I don't have a cloud sandbox that I can reproduce this in- The current build I'm using leverages Magento CLI version 2.2.3, so this is likely the problem.

**Comment by engcom-backlog-nickolas** [comment]
@jbownds, thank you for your report. I wasn't able to reproduce this issue locally on Magento CE version.
Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
