### ISSUE TITLE
Magento install cannot continue

### ISSUE THREAD

**Issue by nmklong** [magento/magento2#16673]
I'm trying to install magento2 through the web. I got stuck on this page and clicking next doesn't do anything

![screen shot 2018-07-09 at 15 50 05](https://user-images.githubusercontent.com/1017308/42479917-ea0b75ec-838f-11e8-85dc-d26ccaa38959.png)

I open the inspector and seeing this URL is returning 500
/setup/index.php/modules
![screen shot 2018-07-09 at 15 53 43](https://user-images.githubusercontent.com/1017308/42480003-4b10f8c6-8390-11e8-894b-3782caa8b881.png)

I checked both apache and php error logs but not seeing any other detailed errors thrown. Any help what's up with the error or how to see some better messages of the 500 exception?

**Comment by magento-engcom-team** [comment]
Hi @nmklong. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nmklong do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nmklong** [comment]
@magento-engcom-team yes

**Comment by ghost** [comment]
@nmklong, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
