### ISSUE TITLE
magento 2 flush cache not working

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#16672]
Hi
My issue is I have two duplicate website one for dev purpose and one is my live site.

When I change for example the theme color and flush the cache, Working perfect, color is changing.

But when I do the same thing on my Live site nothing change.

I tried to do all those command.

    php70 bin/magento setup:upgrade;
    rm -rf generated/*;
    rm -rf pub/static/*;
    rm -rf var/cache/*;
    rm -rf var/page_cache/*;
    rm -rf var/composer_home/*;
    rm -rf var/view_preprocessed/*;
    rm -rf var/cron/*;
    
    php70 bin/magento setup:di:compile;
    
    php70 bin/magento setup:static-content:deploy;
    
    redis-cli flushall; /usr/bin/php70 /opt/magemojo/bin/n98-magerun2.phar  cache:flush; 
    php70 bin/magento indexer:reindex;
    php70  bin/magento cache:clean;
    php70 bin/magento cache:flush;

Any idea?

**Comment by magento-engcom-team** [comment]
Hi @testmagento2. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@testmagento2 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@testmagento2, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
