### ISSUE TITLE
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Mail\Template\FactoryInterface

### ISSUE THREAD

**Issue by opnpnt** [magento/magento2#16679]
I 've been getting the below listed exception. And also during reindexing from command cli same exception occurs.  

### Preconditions

1.  Magento 2.2.4
2.  PHP 7.0.29
3. MySQL 5.7 

### Steps to reproduce
1. Call http://gerard-paris.com
2. 
3. 

### Expected result
Frontpage should appear

### Actual result
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Mail\Template\FactoryInterface in /html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111 Stack trace: #0 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array) #1 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...') #2 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...') #3 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...') #4 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo.. in /html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111

-----

And also reindexing has the same 

 php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00

Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Mail\Template\FactoryInterface in /html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
Stack trace:
#0 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#1 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#2 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#3 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#4 /html/magento2/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo.. in /html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111

**Comment by magento-engcom-team** [comment]
Hi @opnpnt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@opnpnt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by opnpnt** [comment]
solved. The email module was deactivated.
