### ISSUE TITLE
Default tax region/state appears in customer & order data

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#16684]
When a default region is set for tax calculation, then this region value gets saved in the customer, quote & order data, which is not a correct behaviour from my pov.

![bildschirmfoto 2018-07-10 um 12 18 08](https://user-images.githubusercontent.com/1556434/42504759-05eb564e-843d-11e8-80e2-873fc3e4812d.png)

My case was: I have disabled the region-field in the checkout shipping form, but still, the region appeared in the order confirmation mail.

![bildschirmfoto 2018-07-10 um 12 26 56](https://user-images.githubusercontent.com/1556434/42504774-0d10aaa0-843d-11e8-8f26-d3b0d638dc99.png)

### Preconditions

1. Magento 2.2.3
2. PHP7.1

### Steps to reproduce

1. Set a default tax region in Stores > Configuration > Sales > Tax
2. Complete an order

### Expected result

1. No region should be set in the customer and order data

### Actual result

1. The region value (from default tax value) is set 

![bildschirmfoto 2018-07-10 um 12 26 56](https://user-images.githubusercontent.com/1556434/42504774-0d10aaa0-843d-11e8-8f26-d3b0d638dc99.png)

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Detzler do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Detzler** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Detzler, here is your [Magento instance](https://i-16684-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-16684-2-2-3.engcom.dev.magento.com/admin](https://i-16684-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Detzler** [comment]
@magento-engcom-team, I could reproduce the issue. What now?

![bildschirmfoto 2018-07-10 um 14 36 44](https://user-images.githubusercontent.com/1556434/42510282-b1244dc0-844e-11e8-80c8-a409b2bb70dc.png)

**Comment by Detzler** [comment]
Beside this issue, I'd like to give feedback to the Magento Contributor Assistant:
Very nice tool. I was able to setup the instance easily. The problem is that the instance is empty. Some dummy data like products, etc. would be nice.

**Comment by ishakhsuvarov** [comment]
@Detzler Thanks for the feedback. We are looking to implement something like that in the future

**Comment by ghost** [comment]
@Detzler, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce.
![1](https://user-images.githubusercontent.com/40756187/42564027-57ce5daa-8508-11e8-8658-ab441603b5d4.gif)

**Comment by Detzler** [comment]
@engcom-backlog-pb thanks for the video.. Didn't you place the order? After that, you will see the state in the backend order view and also in the order confirmation mail

**Comment by ghost** [comment]
@Detzler, thank you for clarification.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @ssp58bleuciel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#18857 by @ssp58bleuciel in 2.2-develop branch
Related commit(s):
 - [5a84c5a483386fdcf297126ecba90db1e1b13f89](https://github.com/magento/magento2/commit/5a84c5a483386fdcf297126ecba90db1e1b13f89)
 - [e4b430a89a1d4e5ed92dccbed8c0c93aef7f82f4](https://github.com/magento/magento2/commit/e4b430a89a1d4e5ed92dccbed8c0c93aef7f82f4)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#19387 by @ssp58bleuciel in 2.3-develop branch
Related commit(s):
 - [350b56cd23ebbecebdaf27c30193a48a732b33a4](https://github.com/magento/magento2/commit/350b56cd23ebbecebdaf27c30193a48a732b33a4)
 - [2854a1e5cc5e705633c04b16e6865e89e5250b77](https://github.com/magento/magento2/commit/2854a1e5cc5e705633c04b16e6865e89e5250b77)
 - [01d4bd63a370769b68892bd6c7b632d16e318fca](https://github.com/magento/magento2/commit/01d4bd63a370769b68892bd6c7b632d16e318fca)
 - [5638333d288daa1512f479ae60734deb81b4ee6c](https://github.com/magento/magento2/commit/5638333d288daa1512f479ae60734deb81b4ee6c)
 - [60005f272f482a5aedc3d30931d821f1711280bd](https://github.com/magento/magento2/commit/60005f272f482a5aedc3d30931d821f1711280bd)

The fix will be available with the upcoming 2.3.1 release.
