### ISSUE TITLE
Product textarea attribute using WYSIWYG - directive URL not replaced by actual URL

### ISSUE THREAD

**Issue by adampmoss** [magento/magento2#16682]
This was resolved for CMS pages with images uploaded using the WYSIWYG here: https://github.com/magento/magento2/issues/12741

This same issue exists for textarea product attributes, the directive URL is used rather than the actual product URL.

### Preconditions
1. Checked on Magento version 2.2.3

### Steps to reproduce

1. Create a textarea attribute for a product with "Enable WYSIWYG" set to Yes.
2. Add this attribute to an attribute set and create a product with this set
3. Use WYSIWYG to add an image to the product

![dormeo_silver_memory_foam_mattress___products___inventory___catalog___magento_admin-2](https://user-images.githubusercontent.com/4948435/42504644-502b4f60-8434-11e8-8128-5ff41bebbd4f.png)

You will already be able to see the directive URL is used in the HTML:

![dormeo_silver_memory_foam_mattress___products___inventory___catalog___magento_admin-3](https://user-images.githubusercontent.com/4948435/42504843-e3cd82c4-8434-11e8-8a1b-5958a84bee4a.png)

4. Save product
5. Make sure you echo this attribute out in a PHTML file on the product page
6. Visit product page on frontend

### Expected result
The image works and the URL has been formatted correctly:

![enable_cookies_and_wysiwygattribute_php_-_dormeo_-____sites_dormeo_](https://user-images.githubusercontent.com/4948435/42505002-5d02fe3a-8435-11e8-8140-cb9d3140663f.png)

### Actual result
The URL is still using the directive URL and hasn't been corrected:

![dormeo_silver_memory_foam_mattress](https://user-images.githubusercontent.com/4948435/42504917-1bb295c6-8435-11e8-92ae-6fa8eaf4fe56.png)

**Comment by magento-engcom-team** [comment]
Hi @adampmoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@adampmoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by adampmoss** [comment]
I wasn't able to reproduce this on vanilla 2.2.2 so I'll close this for now.
