### ISSUE TITLE
REST API wildcard encoding issue since 2.2.4

### ISSUE THREAD

**Issue by paul-blundell** [magento/magento2#16686]
I started seeing the following issue after upgrading to 2.2.5, after reverting back I found the issue was introduced in 2.2.4.

### Preconditions
1. Magento 2.2.4
2. PHP 7.0
3. MySQL 5.7
4. Allow Anonymous Guest Access = Yes

### Steps to reproduce
1. Call the following rest API endpoint: `/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=name&searchCriteria[filter_groups][0][filters][0][value]=%25name%25&searchCriteria[filter_groups][0][filters][0][condition_type]=like` 
with "Accept: text/xml" header.
2. Change the name value to %25**ad**name%25 - or anything where the name begins with one of the values from this list: https://www.w3schools.com/tags/ref_urlencode.asp

### Expected result
You should receive some response, even if there are no matching products.

### Actual result
The following error is returned:

`string is not in UTF-8 in /var/www/[path to magento]/vendor/magento/framework/Webapi/Rest/Response/Renderer/Xml.php on line 64`

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@paul-blundell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by paul-blundell** [comment]
@magento-engcom-team yes

**Comment by paul-blundell** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell, here is your [Magento instance](https://i-16686-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16686-2-2-4.engcom.dev.magento.com/admin](https://i-16686-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by paul-blundell** [comment]
@magento-engcom-team Confirmed I was able to reproduce the issue. Except on this instance it returned: `Server internal error. See details in report api/1255602520740`

**Comment by engcom-backlog-nickolas** [comment]
Hello @paul-blundell, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by paul-blundell** [comment]
After some digging, the issue is caused in the file `/vendor/magento/module-webapi/Model/UrlDecoder.php` and the use of `rawurldecode`

**Comment by dwaynebartels** [comment]
I am curious to what the fix is going to be. Please clarify because we are running in to the same issue. 

#### The problem
Company has thousands of products. Some have spaces between the characters in the itemcode/sku. 
We create the product using the POST /products/ endpoint. It takes spaces, no problem. We want to get the product to do logic on our system and we have a problem because Magento 2.2.4 uses raw decoding. %20 (raw) instead of %2B (simple).

#### Preconditions
1. Magento 2.2.4
2. We use library System.Net from .Net Framework 4.5.2 for simple URL encoding 

We use WebUtility.UrlEncode(string) for encoding. 
[documentation WebUtility.UrlEncode Method (String)](https://msdn.microsoft.com/nl-nl/library/system.net.webutility.urlencode(v=vs.110).aspx)

#### Reproduce
1. Create a product with a SKU ("some product") that has a space in between. 
2. Get the product using simple url encoding 
GET /index.php/rest/V1/products/some%2Bproduct/options

#### Result
```
{
    "message": "Gevraagde product bestaat niet" 
}
```
Does not exists ;)

#### Expected result.
Get the product. 

#### The QuickFix
Use raw encoding. %20 for spaces     
GET /index.php/rest/V1/products/some%20product/options

This gets you the product.

For our purposes we could use HttpUtility.UrlPathEncode(). 
[documentation HttpUtility.UrlPathEncode Method (String)](https://msdn.microsoft.com/en-us/library/system.web.httputility.urlpathencode(v=vs.110).aspx)]

This does it RAW but should be avoided because it's used for compatibility purposes and this bug is fixed in 2.3.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @paul-blundell The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by bcerban** [comment]
Hi, any chance you will backport this fix to 2.2.x versions?

**Comment by yaroslav-zenin** [comment]
Found that issue was caused by commit https://github.com/magento/magento2/commit/377668493512c25d6ba94c2fdff1a9f6a35e3530#diff-25b137703a62acb5686fb2e5ab17ec5a

**Comment by bhupendravgroup** [comment]
I am still getting this isssue in 2.3 Enterprise

**Comment by VitaliyOlikh** [comment]
where can I find a solution to this problem?
