### ISSUE TITLE
Performance issues as catalog:images:resize cannot utilize multi-core CPU

### ISSUE THREAD

**Issue by sheldmandu** [magento/magento2#16706]
### Preconditions

1. Magento 2 installed (version doesn't matter) on an 8-core server
2. Catalog with 500 products with 4 high-res images each with size of 3888x2592 pixels
3. Image cache deleted

### Steps to reproduce

1. Run catalog:images:resize on command-line

### Expected result

1. It should be made possible to split processing between multiple CPU cores through use of parameters (e.g. based on modulo division of product id for example)

### Actual result

1. The process takes hours to complete on a 8-core server
2. Using htop or top you can see that only a single CPU core is being utilized at 100%
3. catalog:images:resize does not accept any parameters that allows to distribute load

It is understandable that php can only utilize a single core as it's not multi-threaded by default, but there are various solutions to either simulate multi-threading and utilize multiple cores or at least allow this to be done manually (pthreads, forking, etc).  For example modulo division of the product_id would enable multiple processes to be kicked off that would each handle a load.  For example if you wanted to utize 2 cores you could have one process handle products with ids ending 0-4 and another handle 5-9 running at the same time.  So if the catalog:images:resize command was able to take an option parameter with how many cores to utilize or even with what products to process it would really help.

**Comment by magento-engcom-team** [comment]
Hi @sheldmandu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sheldmandu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @sheldmandu, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
