### ISSUE TITLE
User Agent Rules table headers do match content of rows.

### ISSUE THREAD

**Issue by JRhyne** [magento/magento2#16703]
### Preconditions
1. Magento 2.2.4
2. PHP 7.1
3. MariaDB 10.1.33

### Steps to reproduce
1. Get to the page where you can edit a design configuration (change the theme)
2. Click on 'Add New User Agent Rule' under User Agent Rules

### Expected result
1. The headers of the user agent rules table should align with the content of the table's rows.

### Actual result
1. The headers of the user agent rules table are not in order.
![screen shot 2018-07-10 at 4 33 17 pm](https://user-images.githubusercontent.com/1634300/42538142-0e53c1d6-8465-11e8-9da8-53d566e1c4e9.png)

**Comment by magento-engcom-team** [comment]
Hi @JRhyne. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JRhyne do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by JRhyne** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @JRhyne. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @JRhyne, here is your [Magento instance](https://i-16703-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16703-2-2-4.engcom.dev.magento.com/admin](https://i-16703-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by JRhyne** [comment]
@magento-engcom-team I have confirmed this issue on the fresh instance.

**Comment by engcom-backlog-nickolas** [comment]
Hello @JRhyne, thank you for your report and pull request.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @JRhyne. Thank you for your report. 
The issue has been fixed in magento/magento2#16704 by @JRhyne in 2.2-develop branch
Related commit(s):
 - [1b53299b238f4a83e0f54801182fde7134bbb5c1](https://github.com/magento/magento2/commit/1b53299b238f4a83e0f54801182fde7134bbb5c1)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @JRhyne. Thank you for your report. 
The issue has been fixed in magento/magento2#16792 by @JRhyne in 2.3-develop branch
Related commit(s):
 - [0430946c8073a05b7c9562cb07294f709ac326a4](https://github.com/magento/magento2/commit/0430946c8073a05b7c9562cb07294f709ac326a4)

The fix will be available with the upcoming 2.3.0 release.
