### ISSUE TITLE
Unable to Recover Password - Reset password token expired

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16710]
### Preconditions
1. Magento 2.2.5
2. PHP 7.0.30

### Steps to reproduce
1. Upgraded magento store from 2.1.9 to 2.2.5 
2. Go to Sign in > Forgot Your Password?
3. Add email and captcha
4. Open the email and click on "Set a New Password"

### Expected result
1. See the reset password form (resetforgottenpassword.phtml)

### Actual result
1. The user is redirected to the Forgot you password form with the Reset password token expired error

### Notes
1. This functionality was working perfectly before the update
2. I've already tested this in a clean installation and this error doesn't happen.
3. I've updated another copy of the store to 2.2.5 and this also happens
4. The first time I tried to recover my password  I also got an email to confirm my newsletter subscription

**Comment by magento-engcom-team** [comment]
Hi @vegangirlthatcodes. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vegangirlthatcodes do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
I've already tested in a clean installation and was unable to reproduce. Only on an Upgrade.

@magento-engcom-team give me 2.2.5 instance so I can try on your environment.

**Comment by magento-engcom-team** [comment]
Hi @vegangirlthatcodes. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @vegangirlthatcodes, here is your [Magento instance](https://i-16710-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16710-2-2-5.engcom.dev.magento.com/admin](https://i-16710-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I was unable to reproduce on your instance.
How can I evaluate if this is related to upgrading from 2.1.9 to 2.2.5?

**Comment by ghost** [comment]
@vegangirlthatcodes, thank you for your report. Seems like your problem is caused by custom modules. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
If you'd like to update it, please reopen the issue.

**Comment by ghost** [comment]
Leaving an update because it may help someone else.

My problem was an error on the customer_account_createpassword.xml file on my theme.

Even in developer mode, instead of throwing an error, the customer was only redirected to the the Forgot you password form with the Reset password token expired error.
