### ISSUE TITLE
Error when putting a product into cart

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#16719]
### Preconditions

1. PHP 7.1 fcgi
2. Magento 2.2.4
3. Production mode

### Steps to reproduce

1. Put a product to cart
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. Frontend error message: the product could not put into cart
2. Error in exception.log: [2018-07-11 12:58:17] main.CRITICAL: Notice: tempnam(): file created in the system's temporary directory in /www/vendor/magento/zendframework1/library/Zend/Cache/Backend.php on line 203 {"exception":"[object] (Exception(code: 0): Notice: tempnam(): file created in the system's temporary directory in /www/vendor/magento/zendframework1/library/Zend/Cache/Backend.php on line 203 at /www/vendor/magento/framework/App/ErrorHandler.php:61)"} []

There is no problem on my local development machine.

**Comment by magento-engcom-team** [comment]
Hi @OvalMedia. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@OvalMedia do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@OvalMedia, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by OvalMedia** [comment]
Yeah, that's easy...
