### ISSUE TITLE
Config backend models are not populated with fieldset data

### ISSUE THREAD

**Issue by mam08ixo** [magento/magento2#16712]
In config backend models, it was possible to access all configured values from the current group. This is especially important for performing sanity checks/validation of _config value combinations_. A recent commit (faint suspicion: 4af80a2) broke that. All config values that are processed _after_ the current field can no longer be accessed via `\Magento\Framework\App\Config\Value::getFieldsetDataValue`.

### Preconditions

1. Magento 2.2.6-dev

### Steps to reproduce

1. Log in to admin panel
2. Navigate to `Stores → Configuration → Catalog → Catalog → Search Engine Optimization` (in fact, every config field with backend model is affected but this one illustrates the problem quite well).
3. Enter some values in this group's config fields
4. Save Config
5. In `\Magento\Config\Model\Config::_processGroup` monitor the data passed into `$backendModel->addData($data)`

### Expected result

1. All config values of the current group are passed to the backend model:

![expected](https://user-images.githubusercontent.com/1771622/42564937-64c1a14e-8502-11e8-8505-46175d609e24.png)

### Actual result

1. Only the config values up to the current field are passed to the backend model:

![actual](https://user-images.githubusercontent.com/1771622/42564992-884a45b2-8502-11e8-8bc6-82829f1c600d.png)

**Comment by magento-engcom-team** [comment]
Hi @mam08ixo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mam08ixo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @mam08ixo, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @mam08ixo 
We are closing this ticket now, as this issue is already fixed with the following commits in 2.2-develop: 86b5bc0461ac2f69ba37902f4ef150dba88ce864 74151715c86449c1d45162904e2d40d304f030b8
Fix is expected to be delivered with patch 2.2.6
