### ISSUE TITLE
False memory limit error in update.log

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#16714]
### Preconditions

1. PHP 7.1 fcgi
2. Magento 2.2.4

### Steps to reproduce

1. setup cron
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

Repeated entries in update.log:

> [2018-07-11 10:23:01] setup-cron.ERROR: Your current PHP memory limit is 2048M. Magento 2 requires it to be set to 756M or more. As a user with root privileges, edit your php.ini file to increase memory_limit. (The command php --ini tells you where it is located.) After that, restart your web server and try again.

It admits the limit is set to 2048M but complains it should be 756M or MORE.

**Comment by magento-engcom-team** [comment]
Hi @OvalMedia. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@OvalMedia do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by OvalMedia** [comment]
The error goes away once I set the memory limit to exactly 756M.

**Comment by orlangur** [comment]
@OvalMedia please try to debug work of `\Magento\Framework\Convert\DataSize::convertSizeToBytes` on your environment further. At first glance it looks okay.

**Comment by ghost** [comment]
@OvalMedia, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
