### ISSUE TITLE
Blocks (Content/Blocks) don't appear

### ISSUE THREAD

**Issue by TryPicks** [magento/magento2#16723]
### Preconditions

1. Magento 2.2.5
2. FreeGo Theme (Solwin)

### Steps to reproduce

1. Admin page
2. Content
3. Blocks

### Expected result

1. All blocks appear like footer_links ...

### Actual result

1. No blocks appear (We couldn't find any records.)

**Comment by magento-engcom-team** [comment]
Hi @TryPicks. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@TryPicks do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
> FreeGo Theme (Solwin)

I guess this is the issue here or where the issue occurs if all caches and the deployment task were executed.

**Comment by TryPicks** [comment]
@DanielRuf Yeah... maybe... and how can I fix it? The footer links are in default, I need to change Urls and add some more info, like Contact information and more...

**Comment by engcom-backlog-nickolas** [comment]
Hello @TryPicks, thank you for report. As The GitHub issue tracker is intended for Magento Core technical issues only, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
