### ISSUE TITLE
Magento 2.2.5 Front Store User Creation Not working in Google Chrome

### ISSUE THREAD

**Issue by ashan-r** [magento/magento2#16729]
Magento 2.2.5 New Customer Account Creation Not Working on Google Chrome. Works fine with Mozilla Firefox.

### Preconditions

1.  MySQL Version 7.0
2.  Magento Version 2.2.5
3.  Browser Version 67.0.3396.99 (Official Build) (64-bit)

### Steps to reproduce

1. Go to Create New Account
2. Fill the New User Account Information
3. Click the Create an Account Button

### Expected result

1. Newly Created User redirected to User Account Area

### Actual result

1. Empty Create New Customer Account Form.

**Comment by magento-engcom-team** [comment]
Hi @ashanrajapaksha. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ashanrajapaksha do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @ashanrajapaksha, thank you for your report. Unfortunately I'm not able to reproduce this issue.
![peek 2018-07-12 09-25](https://user-images.githubusercontent.com/40755810/42615992-36a2a8cc-85b5-11e8-86d8-cea41ae7c7b7.gif)
Could you please add more details?

**Comment by ashan-r** [comment]
Hi!


I'm using version 2.2.5


I have installed it as a fresh install yesterday on localhost xampp with php version 7.0 . Everything works fine with Mozilla Firefox. But new customer account signup in Google Chrome browser doesn't works. I use chrome version 67.


FYI  - Customer Signup works fine in Hosted Environment with google chrome.

Thank you.
________________________________

**Comment by engcom-backlog-nickolas** [comment]
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by andorep** [comment]
This anyone solve this problem?
I have the same issue in Chrome

**Comment by harrigo** [comment]
Yeah ive just had this issue on 2 fresh Magento instances spun up using "@magento-engcom-team give me 2.2.4 instance". Also happened with 2.2.5. Happens on latest chrome however not firefox. This does not happen on my live site thankfully however thought I would just reiterate that there is an issue...

**Comment by magento-engcom-team** [comment]
Hi @harrigo. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @harrigo, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16729-2-2-4/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16729-2-2-4//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-16729-2-2-4//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by harrigo** [comment]
I can confirm that it happens for me on that one too although I didn't mean to trigger that. 

Chrome Version 69.0.3497.100 (Official Build) (64-bit)
