### ISSUE TITLE
Facebook Social Integration fails to activate.

### ISSUE THREAD

**Issue by DigiBlooD** [magento/magento2#16722]
When i try to activate the Facebook Social integration the popup fails with en error message.

### Preconditions
1. Magento v2.2.5
2. PHP v7.1.19
	- bcmath
	- dba
	- dom 
	- enchant
	- fileinfo
	- gd
	- imagick
	- imap
	- intl
	- json
	- ldap
	- mbstring
	- mcrypt
	- mysqli
	- mysqlnd
	- oauth
	- odbc
	- opcache
	- pdo
	- pdo_odbc
	- pdo_pgsql
	- pdo_sqlite
	- pgsql
	- phar
	- posix
	- pspell
	- snmp
	- soap
	- sockets
	- sysvmsg
	- sysvsem
	- sysvshm
	- timezonedb
	- wddx
	- xmlreader
	- xmlrpc
	- xmlwriter
	- xsl
	- zip
3. MySQL v10.1.31-MariaDB-cll-lve
4. Apache v2.4.33
5. Perl v5.16.3
6. Kernel v3.10.0-714.10.2.lve1.5.12.el7.x86_64

### Steps to reproduce
1. Log in to the Magento Admin page 
2. Click on "Marketing"
3. Click "Connect to Facebook"
4. Click on "Activate" on the Magento Social line
5. Click on "Allow" on the API page
6. Magento Social popup shows error and in the background you can click "OK" witch states "Please setup or sign in into your 3rd party account to complete setup of this integration."
7. When Magento Social popup with the error is closed and press "OK" on the Magento Social page with the "Please setup or sign in into your 3rd party account to complete setup of this integration." text status on Magento Social is still "inactive" even after a refresh.

Followed the https://docs.magento.com/m2/ee/user_guide/marketing/social-connect-to-facebook.html 
guide on how to activate. Have also tried the troubleshooting on that same page.

Have also checked https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html and feel that all versions should be in order.

### Expected result
1. 
![social-facebook-successful-activation](https://user-images.githubusercontent.com/41118712/42579655-15cd0386-8529-11e8-98c1-0b504fc27772.png)

### Actual result
1.
![magento social error popup](https://user-images.githubusercontent.com/41118712/42579673-1e1be3cc-8529-11e8-8704-d796684195cc.png)

**Comment by magento-engcom-team** [comment]
Hi @DigiBlooD. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@DigiBlooD do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DigiBlooD** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @DigiBlooD. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @DigiBlooD, here is your [Magento instance](https://i-16722-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16722-2-2-5.engcom.dev.magento.com/admin](https://i-16722-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DigiBlooD** [comment]
"Marketing" -> "Social" -> "Connect to Facebook" not available on the vanilla Magento instance generated therefore not able to test or confirm.

**Comment by bal0gtibi** [comment]
Hi,
Did you manage to solve this? I'm having the same issue:
- Magento CE 2.2.3
- Apache 2.4
- Mysql 5,7
- PHP 7.0

Thanks.

**Comment by DigiBlooD** [comment]
Hi Bal0gtibi

No sorry I haven't. I have pretty much exceeded on things to try, clean test site does the same thing located on the same server host. I had the same issue with 2.2.4 also, upgrading to 2.2.5 didn't help anything. Nether up or downgrading PHP versions.

Host is using cpanel, not sure if that could be a issue. Your host also running cpanel?

**Comment by bal0gtibi** [comment]
Hi DigiBlooD,
No, mine is a vps I'm renting for production, and there is a virtualized one with almost the same config at my home PC, where I can try a few things out. It seems to me that the error is either on FB side or something with the FB app itself. It would be good to have some developer attention on this, I've seen that some folks want this module to be removed by default in newer installations.. Of course it's easier than fixing it :)

**Comment by DigiBlooD** [comment]
I read somewhere else that one could try to delete the consumer key and secret so it regenerates since the keys dont work manually ether but I haven't had the time to test that yet.

Keep me update if you find a solution! I'll do the same.

**Comment by bal0gtibi** [comment]
Hey,
It seems I've sorted it out finally. I have a varnish with nginx reverse proxy (for https) before my magento backend, and I've set my unsecure base url to https too, in order to avoid redirect loops... this seemed to be a mistake.

Here is what I did so far to fix it:
- upgraded php from 7.0 to 7.1
- picked out varnish from the picture completely
- set back the unsecure url to http
- deleted the relevant lines from integration and oauth_consumer tables
- magento setup:upgrade, recompile, redeploy ...
- and the integration can be enabled after all these things

I'm not sure if varnish and php have anything to with it..

Let me know how it works on your side.

ps.: in this case the integration will be activated with your http url not your https one, I don't know how much difference this makes for oauth requests, unfortunately I don't have much experience with it.

**Comment by DigiBlooD** [comment]
Hi

Fixed on the test store.
I cleaned  oaut_consumer for the keys, then it removed the facebook integration from integration itself from the db. Ran ./bin/magneto setup:upgrade… and it poped back up under the activation page. Reactivated it and now its working. :)

Just as extra info i tried disabling and enabling it again this weekend but that didn't work.
Disable the module
1. ./bin/magento module:disable --clear-static-content Shopial_Facebook
2. ./bin/magento setup:recompile

and reenabling it
1. ./bin/magento module:enable --clear-static-content Shopial_Facebook
2. ./bin/magento setup:recompile


Guess manually deleting the tokens/key from the db is the best way to go for now.

**Comment by NiteshKuyate** [comment]
@DigiBlooD In which table ' oaut_consumer' entry exists.

**Comment by DigiBlooD** [comment]
@NiteshKuyate its the Consumer Key and Consumer Secret that are found for it there.

I got it working on my test stor witch is running on the same server as the live shop so the preconditions are the same. Small difference is that the test one is http and the live one is https. There is no https proxy's here.

I have tried setting the base url's to http on the live shop but that did not solve anything. I have tried disabling and enabling the integration and that does not help ether.

Disable
./bin/magento module:disable -c Shopial_Facebook
./bin/magento setup:upgrade

Enable
./bin/magento module:enable -c Shopial_Facebook
./bin/magento setup:upgrade

So I am pretty much stuck again..

**Comment by DigiBlooD** [comment]
Fixed, at least a temp fix for now.

Base Urls:
Base URL and Base Link Url set to http://www.domain.com

Flushed Magento Cache, that did not fix it.

Base Urls:
Base URL and Base Link Url set to http://www.domain.com

Base Urls (Secure):
Use Secure URLs in Admin: No

Flushed Magento Cache and activate for Facebook Social works afterwards.

I have put everything back to the settings I had now to secure since I dont want to be connecting to the admin page without it being secure. Gona do some more testing later today and see if it breaks.

**Comment by DigiBlooD** [comment]
Two new issues related to this

The product it has fetched has prices set to 0,- 

The products listed on Facebook if clicked they go to https://domain.com/product-name.html and not https://domain.com/product-name witch gives a 404 error.

It looks like it does not take consideration to the settings in System -> Configuration -> Catalog --> Product URL Suffix and Category URL Suffix.

**Comment by DigiBlooD** [comment]
Products missing prices is Configurable Products. It manages to fetch the price from Simple Products.

**Comment by NiteshKuyate** [comment]
@DigiBlooD Thanks for the update.

**Comment by NiteshKuyate** [comment]
@DigiBlooD 
I have also tried your steps on our test server, but no luck.
Did you figure out any solution for it?

**Comment by DigiBlooD** [comment]
@NiteshKuyate No sorry imo this is a code issue so the devs will have to take a look at it..

**Comment by bal0gtibi** [comment]
Hello Magento Devs,
Any news about fixing the activation / price of child products / html in url issues? It's a nice feature to have in magento, but it's kind of worthless in its current state..

**Comment by stephenbori** [comment]
Is there any update on this issue as I am experiencing the exact same issues as in this video https://www.youtube.com/watch?v=4M957wZLbpM&feature=youtu.be

my setup is as follows 

- Varnish for Basic page caching only (home, catalog)
- Redis 
- Nginx Reverse proxy caching 
- Magento 2.2.4 
- Dedicated Server

**Comment by Anju2006** [comment]
Trying to integrate Magento ver 2.2.2  with Facebook. Ends up here . What could be the issue? 
![screenshot 2018-09-11 21 39 01](https://user-images.githubusercontent.com/43180698/45372958-d6d55200-b60b-11e8-8675-c8ef1a2e3555.png)
![screenshot 2018-09-11 21 39 50](https://user-images.githubusercontent.com/43180698/45372959-d6d55200-b60b-11e8-8804-7cd4ebff4819.png)

**Comment by hostep** [comment]
I've seen signs that the Shopial Facebook integration is more or less dead.
- Marketplace url no longer works: https://marketplace.magento.com/shopialfb-facebook-module.html
- https certificate is no longer valid: https://www.shopial.com/
- In the accidentally leaked upcoming version of Magento 2.2.6 yesterday, the module was completely removed

So I would just start looking for some other way to integrate with Facebook if I were you...

**Comment by Anju2006** [comment]
Looks like it.

**Comment by Anju2006** [comment]
> I've seen signs that the Shopial Facebook integration is more or less dead.
> 
> * Marketplace url no longer works: https://marketplace.magento.com/shopialfb-facebook-module.html
> * https certificate is no longer valid: https://www.shopial.com/
> * In the accidentally leaked upcoming version of Magento 2.2.6 yesterday, the module was completely removed
> 
> So I would just start looking for some other way to integrate with Facebook if I were you...

Looks like it :/

**Comment by stephenbori** [comment]
@Anju2006  - Thanks for the heads up on this, especially the removal on 2.2.6. I will look for another solution

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by marcelo-monteiro** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro, here is your [Magento instance](https://i-16722-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16722-2-2-5.engcom.dev.magento.com/admin](https://i-16722-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by marcelo-monteiro** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro, here is your [Magento instance](https://i-16722-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16722-2-2-4.engcom.dev.magento.com/admin](https://i-16722-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by marcelo-monteiro** [comment]
@DigiBlooD , unfortunately this is a vendor issue, please contact them at:
http://www.shopial.com/support/

Also as @Anju2006 told, this module will not be bundled anymore in the next Magento version. Thanks!

**Comment by marcelo-monteiro** [comment]
Hi @DigiBlooD , unfortunately this is a vendor issue, please contact them at:
http://www.shopial.com/support/

Also as @Anju2006 told, this module will not be bundled anymore in the next Magento version, the package is available to check.
