### ISSUE TITLE
Importing Customers with custom attributes fails

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#16737]
### Preconditions

1. Magento2.2.3

### Steps to reproduce

1.  Create a custom customer attribute like [here](https://www.mageplaza.com/magento-2-module-development/magento-2-add-customer-attribute-programmatically.html)
2. Export the customer Main file from System > Export , don't exclude any attributes
3. alter the customer main file 
4. Import the customer Main file from System > Import

### Expected result
The customer data including custom attributes gets imported correctly
1. [Screenshots, logs or description]

### Actual result
1. Spinner keeps hanging on the import. 

Following error is shown in the last admin/import/start/key/ request 

Call to a member function getBackendModel() on null in vendor/magento/module-customer-import-export/Model/Import/Customer.php on line <i>413
![screen shot 2018-07-12 at 11 55 50](https://user-images.githubusercontent.com/9752966/42627276-d48dc1e0-85cc-11e8-8b05-cb33c12c7558.png)

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@duckchip do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @duckchip , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by webspeaks** [comment]
I added a custom attribute with code 'country_id' to the customer entity. When I import the country_id using csv, it gives me below error:

![image](https://user-images.githubusercontent.com/1465109/45998835-aa1c4280-c0c1-11e8-839e-32e2c5d9fd35.png)

**Comment by UsenkoArt** [comment]
Hi.
Recently I was faced with this problem.
I found solution for me.
I try to explain.
I check this on magento 2.2.1, 2.2.3, 2.2.6.
It isn't quite a bug.

When I debug module - customer import export. I get next result.
At first Import proccess running through method _prepareDataForUpdate in 
vendor/magento/module-customer-import-export/Model/Import/Customer.php
Magento call the method getAttribute on line 412.
https://i.imgur.com/borZWqv.png
After that we appear in class 
vendor/magento/module-customer/Model/Customer.php(method - getAttribute line - 538).
https://i.imgur.com/HUUco7E.png
Where magento call method getAttributes() - line 540.
In this method magento load all necessary attributes and call method - getSortedAttributes() line 527.
https://i.imgur.com/X3kfvKa.png
If we look at this method. 
Class - vendor/magento/module-eav/Model/Entity/AbstractEntity.php - line 523.
https://i.imgur.com/4m5Ky7Z.png
We can see that magento get all attributes and default attribute set for customer entity.
After that magento check is this attribute in the set?
If attribute doesn't exist in attribute set magento delete this attribute from import process.
And returned sorted set of attributes.
We again come back to method getAttrbute from vendor/magento/module-customer-import-export/Model/Import/Customer.php - line 541.
We can see check if our attribute exist in sorted array "attributes" -> return this attribute.
Otherwise -> return null.
And in the end we return to class 
vendor/magento/module-customer-import-export/Model/Import/Customer.php - line 413.
And we have in result that variable $attribute is null. And magento try to call backend model from null as result we can see exception.

So, I want to say when you create custom attribute in migration. You should write migration like describe in mageplaza guide. But also you should add this code in the end of script.
https://i.imgur.com/aTocvFb.png

So you should add your custom attribute to default attribute set or your custom attribute set.
Also it is correct if attrbute isn't static!

Thanks, sorry for my English.

**Comment by karangar** [comment]
I am facing same Problem in magneto 2.2.8

**Comment by karangar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @karangar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @karangar, here is your [Magento instance](https://i-16737-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-16737-2-2-develop.instances.magento-community.engineering/admin](https://i-16737-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @duckchip 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
