### ISSUE TITLE
Session closed prematurely due to pagecache after creating order

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#16738]
### Preconditions

1.  Magento 2.2.5, redis, varnish 4
2. Have this Paypal plus module installed https://github.com/i-ways/magento2-paypal-plus

### Steps to reproduce

1. Create an order using paypal plus

### Expected result

1. After payment, land on checkout success

### Actual result

1. Land on empty cart after being redirected from success page

This started happening after updating from 2.2.3 to 2.2.5.

After paying in paypal, user is redirected to a controller in Magento that creates the order and redirects to success page.
What happens is that during a call to `\Magento\Quote\Model\QuoteManagement::placeOrder` the [session is closed](https://github.com/magento/magento2/blob/2.2.5/app/code/Magento/PageCache/Model/Layout/DepersonalizePlugin.php#L56) before the [last successful order](https://github.com/magento/magento2/blob/2.2.5/app/code/Magento/Quote/Model/QuoteManagement.php#L372) is saved to the session object so it never gets saved.
Once the page is redirected to success page the validation will fail since there is no last successful order in session and redirects to cart.

[This observer](https://github.com/magento/magento2/blob/2.2.5/app/code/Magento/PageCache/Model/Layout/DepersonalizePlugin.php#L56) gets triggered because while an order is created the email is also generated which uses layouts but the "cachable=false" gets ignored. The request is therefor categorized as cachable.

I realize this will be hard to reproduce without installing this extension, but I am convinced there is a bug. Having `\Magento\Quote\Model\QuoteManagement::placeOrder` inside a controller that is called using GET instead of POST should have the same problem.

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@domeglic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

> Having \Magento\Quote\Model\QuoteManagement::placeOrder inside a controller that is called using GET instead of POST should have the same problem.

Well, calling such method in GET violates CQRS and leads to expected problems.
