### ISSUE TITLE
Magento 2.2.3 | Cant Find "Search Synonyms" Under Admin->Marketing->SEO  & Serch

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#16730]
in my admin panel, i cant find the "Search Synonyms" in "Admin->Marketing->SEO  & Serch"

i even changed the search engine to "mysql", but still not showing up

any ideas on how to enable it?
![screenshot_2018-07-12 search terms seo search marketing magento admin](https://user-images.githubusercontent.com/3238761/42615457-a69e2134-85aa-11e8-9276-4c023813eefe.png)

**Comment by magento-engcom-team** [comment]
Hi @salehawal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@salehawal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by salehawal** [comment]
| Summary of the issue
i cant find the "Search Synonyms" in "Admin->Marketing->SEO & Serch"

| Information on your environment
Centos Server | php 7 | mysql 5 | magento 2.2.3 upgraded from 2.2.2

| Steps to reproduce
i dont know (:

| Expected and actual results
to be able to show "Search Synonyms" under  "Admin->Marketing->SEO & Serch"

Note: i saw some tutorials on youtube like this one: "https://www.youtube.com/watch?v=bE3Gx1P3SvQ"
but i have no idea why it is showing on his screen but not on mine?

**Comment by engcom-backlog-pb** [comment]
@salehawal, thank you for your report.  "Search Synonyms" functionality relates to Magento Commerce. This GitHub tracker is intended for Magento Open Source only.

**Comment by ghost** [comment]
@salehawal, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by salehawal** [comment]
it is included in the CE Edittion ..  check here : https://docs.magento.com/m2/ce/user_guide/marketing/search-synonyms.html?Highlight=Search%20Synonyms
