### ISSUE TITLE
Magento 2.2.3 Product page leads to 404 on another store url (multistore website)

### ISSUE THREAD

**Issue by jakc3** [magento/magento2#16749]
I have two website setup with different domains that share the same products.

The issue is:

Product domain1.com/product1 -> works fine (default store)
Same product on domain2.com/product1 -> returns 404 (2nd store, different domain, same URL)
Same product on domain2.com/category/product1 -> works
Same product on domain2.com/product1NewUrl -> works

So, if there is a category path in the URL the product page works on the second domain but for example on homepage where the product is linked without category path and goes directly to /product1 it returns 404 error.

If the URL of the product is changed to something different on second website (domain2.com) then it works even without category path. As soon as you change it back to the way it was it returns 404 page.

The problem is present on Magento CE 2.2.3, apache, PHP 7.1

What should happen:

Product that you assign to another store should work and not redirect to 404.

**Comment by magento-engcom-team** [comment]
Hi @jakc3. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@jakc3 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jakc3** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @jakc3. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jakc3, here is your [Magento instance](https://i-16749-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-16749-2-2-3.engcom.dev.magento.com/admin](https://i-16749-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jakc3** [comment]
@magento-engcom-team I cannot create a multi domain environment on your instance to test it.

I should also note that the root category on the 2nd domain is different from the default website.

**Comment by jakc3** [comment]
The issue was linked to Amasty module for Rich Snippets.
