### ISSUE TITLE
Changing country in shipping page does not update payment method in payment &review page

### ISSUE THREAD

**Issue by fabianaromagnoli** [magento/magento2#16750]
### Preconditions
1. Magento 2.2.5
2. PHP 7.1

### Steps to reproduce
1. Enable Bank Transfer payment method, only for one country. I enabled Italy.
2. Add a product to cart
3. Go to checkout page
4. Edit a shipping address and set Italy as country
5. Click the Next Button: you'll see both Bank Transfer and Check/Money Order (the latter is enabled by default for all countries)
6. Go back to the Shipping page
7. Change the country of the shipping address, and select any other country, for example Canada
8. Click the Next button

### Expected result
Only the payment method Check/Money Order should be visible

### Actual result
Both Bank Transfer and Check/Money Order are present.
If I choose Bank Transfer, that should not be visible at all, the checkbox "My billing and shipping address are the same" is checked, but the billing address is the old one (the Italian one).
If I place the order now, it is successful, but it has two differente addresses: the Italian one for billing, the Canadian one for shipping.
If I uncheck the "My billing and shipping address are the same" checkbox and check it again, the billing address is updated. If I place the order now I get the error "The requested Payment Method is not available"

**Comment by magento-engcom-team** [comment]
Hi @fabianaromagnoli. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@fabianaromagnoli do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @fabianaromagnoli, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @pmclain. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by gixid192** [comment]
The issue has been fixed in latest Magento versions (Magento 2.3.6 and 2.4.2)

**Comment by GurramSravya** [comment]
@magento-engcom-team give me {2.2.5} instance

**Comment by GurramSravya** [comment]
@magento I am working on this

**Comment by GurramSravya** [comment]
@magento add to contributors team

**Comment by GurramSravya** [comment]
@magento I am working on this

**Comment by GurramSravya** [comment]
@magento give me 2.2.5 instance

**Comment by GurramSravya** [comment]
Hi @fabianaromagnoli .
The issue is not reproducible in my local (version 2.4). It is fixed. 
I am able to see the bank transfer payment method only for the selected country rather than all the countries, which is the correct and reason for not reproducible.

**Comment by engcom-Bravo** [comment]
Hi @fabianaromagnoli,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

Please feel free to reopen the issue if you are still facing any issue.

Thanks.
