### ISSUE TITLE
Add product attribute content area collides with footer section 

### ISSUE THREAD

**Issue by sibi4586** [magento/magento2#16751]
Hi,

I took my Magento 2.2.3 admin-panel for adding new product attributes with an drop-down options. That attribute has more than 20 options and I added one by one suddenly I can see that the content area colliding with footer div.

It shows design broken

I did not knew why it happened?

https://imgur.com/a/V4Fh18G

I hope this report will helps you and fix this in asap 

Thanks

**Comment by magento-engcom-team** [comment]
Hi @sibi4586. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sibi4586 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @sibi4586, thanks you for your report. Unfortunately I couldn't reproduce this issue.
![peek 2018-07-13 11-23](https://user-images.githubusercontent.com/40755810/42680999-32da89be-868f-11e8-97ff-91e016d62b41.gif)
Could you please add more details?

**Comment by sibi4586** [comment]
Hi Team,

Sorry for the delay


Still I am getting this issue.


I am using

Browser => Chrome browser - Version 67.0.3396.99 (Official Build) (64-bit)

Magento version => Mage 2.2.3



Reproduce scenario : I logged into adminpanel and Store -> Attributes ->
Product

Clicked Add New Attribute button from right top side. Then I can see *Advanced
Attribute Properties *tab content collides with footer area.


Please refer attached screenshot too


PFA

Thanks

**Comment by sibi4586** [comment]
Hi Team,

I also tested this scenario in Firefox browser. But I can also not getting
that error.

I hope the issue may be because of the two tab content are displaying on
load action. In firefox we need to click the tab head to open the second tab


I hope this will help you to track the issue

Thanks again

**Comment by engcom-backlog-nickolas** [comment]
@sibi4586, thanks for feedback. Using chrome Version 67.0.3396.99 (Official Build) (64-bit) with Magento 2.2.3 still not able to reproduce this issue.
![peek 2018-07-19 17-53](https://user-images.githubusercontent.com/40755810/42950321-69f51df0-8b7c-11e8-9779-361d09aff62b.gif)

**Comment by engcom-backlog-nickolas** [comment]
@sibi4586, As I wasn't able to reproduce this issue by following the steps you provided, I'm closing it for now. If you'd like to update it, please reopen the issue.
