### ISSUE TITLE
Issue installing extension: stalls on "Update is already in progress"

### ISSUE THREAD

**Issue by North15** [magento/magento2#16754]
Hello, 

### Preconditions
Magento 2.1.7
PHP 7

### **Summary of the Issue**
I am trying to install MailChimp on Magento 2.1.7 and when it gets to the Component Install phase it stalls after:   `./composer.json has been updated` and continues to print `Update is already in progress`

Here is a picture of the console log that Magento has up:
![info1](https://user-images.githubusercontent.com/34386437/42646425-e60c3f30-85ce-11e8-80fa-9f3df092e53f.JPG)

I have looked around at several solutions and have tried the following:
   1. Checked permissions for the /var files 
   2. Removed the `.update_in_progress.flag` and the `.maintenance.flag`

### Information on the Environment
Using Magento 2.1.7

### Steps to Reproduce
Try to install mailchimp 1.0.29 with install wizard in Magento 2.1.7

### Expected Result
I expect Mailchimp to be installed

### Actual Result
It doesn't get installed

When I remove the two files mentioned above, I get:
 `Success
Your store is no longer in maintenance mode.
You installed: mailchimp/mc-magento2`

But when I go back into the admin panel mailchimp isn't on the sidebar, and if I check the install wizard it has not been installed.

Any guidance on the next steps to take to get this resolved would be greatly appreciated.

**Comment by magento-engcom-team** [comment]
Hi @North15. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@North15 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions their respective vendors should be contacted instead.

You may also try installing module via CLI to figure out if there is any core bug which prevents installation.
