### ISSUE TITLE
Rating Star issue on Product detail Page. 

### ISSUE THREAD

**Issue by Sathishkumar8731** [magento/magento2#16764]
### Preconditions
1.  Magento 2.2.4
2.  MYSQL 5.6
3. PHP 7.1.X

### Steps to reproduce

1.  Go to the Product detail page and select "Review"  tab
2.  Now, enter the information such as "Nick name, Summary and Review" and press "Submit Review" button without select any star rating
3.  **Issue**:  Its throws an error Message " Please select one of each of the ratings above". But, by default **First Star rating is selected**.

### Expected result

1. It should not select any star rating while throwing error message as  " Please select one of each of the ratings above".

### Actual result

1. First star rating is showing. Please refer the attached screenshot. 
![review issue on magento 2](https://user-images.githubusercontent.com/37400095/42674935-5679e216-868f-11e8-927b-2398ae9849d4.png)

**Comment by magento-engcom-team** [comment]
Hi @Sathishkumar8731. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Sathishkumar8731 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Sathishkumar8731** [comment]
Please find the solution for the above issue

1) Go to the File path:  vendor/magento/module-review/view/frontend/templates/form.phtml

2)  Search the below code 

`<?php $iterator = 1; foreach ($options as $_option): ?>`

replace with 

`<?php $iterator = 0; foreach ($options as $_option): ?>`

**Comment by engcom-backlog-nickolas** [comment]
Hello @Sathishkumar8731, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Karlasa** [comment]
@Sathishkumar8731  it's not solution, it only miscalculates ratings now :) 
with this fix you can't select 5 stars and if you give 2 stars system will read it as 3. 

I think the Issue is with field validation js. Because as a default after submit it will auto focus into first incorrect field. In this case its first rating star.

**Comment by Sathishkumar8731** [comment]
@Karlasa  

Thank you. I too noticed the issues and I am working on it. If you found solution please share it here.

**Comment by Karlasa** [comment]
@Sathishkumar8731  that PR should fix the issue.

**Comment by VladimirZaets** [comment]
Hi @Sathishkumar8731. Thank you for your report. 
The issue has been fixed in magento/magento2#16766 by @Karlasa in 2.2-develop branch
Related commit(s):
 - [dd6b78a225f452b98521fb8ca7c86ed418e7cebd](https://github.com/magento/magento2/commit/dd6b78a225f452b98521fb8ca7c86ed418e7cebd)

The fix will be available with the upcoming 2.2.6 release.

**Comment by sidolov** [comment]
Hi @Sathishkumar8731. Thank you for your report. 
The issue has been fixed in magento/magento2#16839 by @Karlasa in 2.1-develop branch
Related commit(s):
 - [8e4cda67b30cf2f4c276703e6d12a6034fb47d44](https://github.com/magento/magento2/commit/8e4cda67b30cf2f4c276703e6d12a6034fb47d44)

The fix will be available with the upcoming 2.1.15 release.

**Comment by magento-engcom-team** [comment]
Hi @Sathishkumar8731. Thank you for your report. 
The issue has been fixed in magento/magento2#16808 by @Karlasa in 2.3-develop branch
Related commit(s):
 - [1dd2017ffae83cbebadf78f02f7bc1eb9c860302](https://github.com/magento/magento2/commit/1dd2017ffae83cbebadf78f02f7bc1eb9c860302)

The fix will be available with the upcoming 2.3.0 release.
