### ISSUE TITLE
List of custom product options should be provided by some service.

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#16763]
https://github.com/magento/magento2/blob/b4c23c4c09bfad7c419f48b5ccce239f45974f67/app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Price/DefaultPrice.php#L629

If new custom product options added by extension indexer ignore this.  Method DefaultPrice::_applyCustomOption() has too big body, therefore his overloading require to many copy-paste.

Custom options types has many other dependences with other magento modules, therefore its not trivial to add new one. Introducing some Custom Option Service can help to make it match easy.

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@likemusic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@likemusic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
