### ISSUE TITLE
Inconsistent visibility for getProductForThumbnail not allowing plugin method reusability

### ISSUE THREAD

**Issue by radub** [magento/magento2#16774]
### Preconditions
- Magento 2.2.5
- Apache 2.4.18
- PHP 7.0.22-0ubuntu0.16.04.1 (fpm-fcgi)
 Copyright (c) 1997-2017 The PHP Group
 Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
     with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
     with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
- mysql  Ver 15.1 Distrib 10.3.7-MariaDB, for debian-linux-gnu (x86_64) using readline 5.

### Steps to reproduce
I wrote a before plugin for method getProductForThumbnail in order to do add custom logic before getProductForThumbnail is executed. I've also added the following di.xml configuration:

```
    <type name="Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable">
        <plugin name="MyNamespace\Plugin\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable_1"
                type="MyNamespace\Plugin\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable" />
    </type>

    <type name="Magento\ConfigurableProduct\CustomerData\ConfigurableItem">
        <plugin name="MyNamespace\Plugin\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable_2"
                type="MyNamespace\Plugin\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable" />
    </type>
```
_just to point it out, the name attribute for the plugin xml configuration is unique for each reference_

### Expected result

The beforeGetProductForThumbnail plugin should execute in both cases:
```
/* case 1 */
\Magento\ConfigurableProduct\Block\Cart\Item\Renderer\Configurable::getProductForThumbnail
/* case 2 */
\Magento\ConfigurableProduct\CustomerData\ConfigurableItem::getProductForThumbnail
```

### Actual result

The plugin only executes for case 1). The reason it is not executing for 2) as well is because the method has the visibility set to **protected**. According top the documentation interceptors apply only to public methods (https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html). The same scenario applies for grouped products:
```
\Magento\GroupedProduct\Block\Cart\Item\Renderer\Grouped::getProductForThumbnail
\Magento\GroupedProduct\CustomerData\GroupedItem::getProductForThumbnail
```

**Comment by magento-engcom-team** [comment]
Hi @radub. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@radub do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by radub** [comment]
yes

**Comment by orlangur** [comment]
@radub you are not supposed to write plugins for classes not marked with `@api`, please intercept `\Magento\Checkout\CustomerData\ItemInterface::getItemData` method instead of protected one, `\Magento\Checkout\Block\Cart\Item\Renderer::getProductForThumbnail` is fine for interception.

**Comment by radub** [comment]
Learned something new today! Maybe this should also be in the documentation.

Thanks! :)

**Comment by orlangur** [comment]
@radub I'm pretty sure it's described somewhere about versioning or backward compatibility policy. If not, try to find the most suitable article and modify it by yourself or report an issue refferring to it in devdocs repo. Thanks for collaboration!
