### ISSUE TITLE
Method getGroupId() from \Magento\Customer\Model\Customer returns string back, but it should return int

### ISSUE THREAD

**Issue by SlawomirBoczek** [magento/magento2#16772]
### Preconditions

1. "magento/product-community-edition": "2.2.4",
2. My PHP version is 7.1, but this is not revelant for this issue

### Steps to reproduce

```
public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Customer\Model\Session $customerSession,
        \Magento\Cms\Api\BlockRepositoryInterface $blockRepository
    ) {
        parent::__construct($context);

        $this->customerSession = $customerSession;
        $this->blockRepository = $blockRepository;
    }

    /**
     * @return int
     */
    protected function getCurrentCustomerGroupId()
    {
        $isLoggedIn = $this->customerSession->isLoggedIn();
        if (!$isLoggedIn) {
            return GroupManagement::NOT_LOGGED_IN_ID;
        }

        $customer = $this->customerSession->getCustomer();
        $groupId = $customer->getGroupId();

        return $groupId;
    }
```

### Expected result

Function should return int, because it has defined "@return int" PhpDoc, so I expect result to be int.
When I do:
`$customer->getGroupId() === 5`
It will be always "false" cause we compare string with int.

### Actual result

So, when I do:
`var_dump($customer->getGroupId())`

This is what I become:
`string(1) "5"`

**Comment by magento-engcom-team** [comment]
Hi @SlawomirBoczek. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@SlawomirBoczek do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by SlawomirBoczek** [comment]
Yes, I was able to reproduce the issue on vanilla Magento instance. If you would read my issue content then you would understand what kind of problem it is. It is problem with Core Magento function returning wrong type and I didn't make any modifications to the Core.

@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @SlawomirBoczek. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @SlawomirBoczek, here is your [Magento instance](https://i-16772-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-16772-2-2-4.engcom.dev.magento.com/admin](https://i-16772-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by SlawomirBoczek** [comment]
I don't have time to do additional tests on your instances... I already wasted 1 hour debugging this and posting this issue.

I just wanted to help, if you don't want to improve your product, then just ignore this issue...

**Comment by orlangur** [comment]
> It will be always "false" cause we compare string with int.

Please don't use strict comparisons where `declare(strict_types)` is absent. Numeric string are marked as `int` in PHPDocs all over the code and it is not going to change.
