### ISSUE TITLE
Is Vertex required for taxing orders?

### ISSUE THREAD

**Issue by JosiahCarberry** [magento/magento2#16781]
I am working through configuring a first installation of Magento 2.2.5 and have come to managing the taxes. The online documentation makes no clear distinction between the steps to create and manage taxes and the use of Vertex, as if the "correct" or maybe even the only way to set up taxes is via Vertex. 
So, my question is whether this is just the tendency of the Magento docs to advertise third party services and Vertex is not needed, or do I really need Vertex to set up VAT on my store?

**Comment by magento-engcom-team** [comment]
Hi @JosiahCarberry. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JosiahCarberry do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by navarr** [comment]
@JosiahCarberry Hi!

Vertex is not necessary to setup taxes - and does not yet support VAT.
