### ISSUE TITLE
Permanent Redirect for old URL missing via API or no documentation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16789]
### Preconditions
1. Magento 2.2.5
2. PHP 7.0.30

### Steps to reproduce
1. **POST** a request for a product via REST API: **V1/products/**
{"product":{"sku": "703","custom_attributes":[{"attribute_code":"url_key","value":"new-url"}, {"attribute_code":"url_key_create_redirect","value":1}, {"attribute_code":"save_rewrites_history","value":1}]}}
 

### Expected result
1. Product URL changes to domain/new-url
3. Accessing the old url redirects to the new url

### Actual result
1. Product URL changes to domain/new-url
3. Accessing the old url returns a 404 error page

I've been reading the Swagger documentation back can't find any information on creating 301 via REST when the product URL is changed.

**Comment by magento-engcom-team** [comment]
Hi @vegangirlthatcodes. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vegangirlthatcodes do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @vegangirlthatcodes, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
Any update on this issue? We have to manually create the redirects since this is causing a lot of SEO problems.

Thank you!

**Comment by lewisvoncken** [comment]
@vegangirlthatcodes 
You can use the following temporary solution:

create a Product Attribute **save_rewrites_history** and fill it through the api with the value 1 as a custom attribute and then it will create a new redirect.

```
            $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
            $eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'save_rewrites_history',
            [
                'type' => 'int',
                'backend' => '',
                'frontend' => '',
                'label' => 'save_rewrites_history',
                'input' => 'boolean',
                'class' => '',
                'source' => '',
                'global' => 1,
                'visible' => true,
                'required' => true,
                'user_defined' => true,
                'default' => null,
                'searchable' => false,
                'filterable' => false,
                'comparable' => false,
                'visible_on_front' => false,
                'used_in_product_listing' => false,
                'unique' => false,
                'apply_to' => '',
                'system' => 1,
                'group' => 'General',
                'option' => array('values' => array(""))
            ]
        );
```

**Comment by lewisvoncken** [comment]
#SQUASHTOBERFEST

**Comment by lewisvoncken** [comment]
@vegangirlthatcodes and @magento-engcom-team

The PR has been created.

**Comment by sdzhepa** [comment]
Hello @vegangirlthatcodes @lewisvoncken 

Thank you for contribution and collaboration!

The corresponding internal ticket `MAGETWO-93424` was fixed, delivered and closed by Magento team

Please see details in the next commits:
- 33b0a51
- fe93034
- fc510d3
