### ISSUE TITLE
Problem JS Checkout - Method Title

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16794]
Magento version 2.2.5
PHP 7.0.3

**Problem**

good afternoon,
Can someone help me with the error below in the ckeckout page?

<img src="http://dmxcargo.com/erro.jpg">

tks

**Comment by magento-engcom-team** [comment]
Hi @douglaspduarte. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@douglaspduarte do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by lbajsarowicz** [comment]
Not a Magento bug. Remember that `data-bind` is for binding element attributes to the knockout expressions, not to translate elements.

For general issues use https://community.magento.com/t5/Magento-2-x-PWA-Theming-Layout/bd-p/magento-2-theming instead of Github

**Comment by ghost** [comment]
@douglaspduarte, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
