### ISSUE TITLE
GraphQL - Category query - children field returning empty [CategoryTree]

### ISSUE THREAD

**Issue by erikkubica** [magento/magento2#16790]
### Preconditions

1. Magento 2.3-dev
2. MYSQL 5.6
3. PHP 7.1.X
4. Ubuntu 16

### Summary of the issue
"children" field of "category" query is not populated in GraphQL result.

### Steps to reproduce
1. Get the latest zip of magento 2.3-dev from github
2. Install magento using standard next next finish process
3. Add a product
4. Add one or more subcategories into default category
5. Check if categories and products are working correctly on the front-end
6. Create a GraphQL Query

```
query ($categoryId: Int!) {
  menu: category(id: $categoryId) {
    id
    name
    children_count
    children {
      name
    }
  }
}
```

### Expected result
```
{
  "data": {
    "menu": {
      "id": 2,
      "name": "Default Category",
      "children_count": "2",
      "children": [populated array of category names]
    }
  }
}
```

### Actual result
```
{
  "data": {
    "menu": {
      "id": 2,
      "name": "Default Category",
      "children_count": "2",
      "children": []
    }
  }
}
```

### Maybe issue
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogGraphQl/Model/Category/Hydrator.php

$categoryData['children'] = []; 

I am not expert, but I think here should be some thing else then empty array.

If anyone knows where the issue is, or how I can fetch list of categories using GraphQL in M2.3 let me know please.

Thank You for you hard work, 2.3 looks really amazing

**Comment by magento-engcom-team** [comment]
Hi @erikkubica. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@erikkubica do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by erikkubica** [comment]
@magento-engcom-team 

- Version is 2.3-develop https://github.com/magento/magento2/tree/2.3-develop
- It's clean vanilla magento instance, no third party modules or themes (http://m23sandbox.netlime.eu)
- I confirm that here: http://m23sandbox.netlime.eu/graphql the issue can be reproduced with the following query

```
query ($categoryId: Int!) {
  menu: category(id: $categoryId) {
    id
    name
    children_count
    children {
      name
    }
  }
}
```

and with following query variables

```
{
  "categoryId": 2
}
```

**Comment by ishakhsuvarov** [comment]
Hi @erikkubica 
Thank you for reporting. It makes sense to report this issue directly to https://github.com/magento/graphql-ce repository, where all of QraphQL action is happening.

Please close this ticket of you decide to file a ticket in that project.

Thank you

**Comment by erikkubica** [comment]
@magento-engcom-team thank you, i have submitted the issue into the repository you suggested. I am closing this ticket.

**Comment by ishakhsuvarov** [comment]
@erikkubica Thank you for collaboration
