### ISSUE TITLE
results won't show up

### ISSUE THREAD

**Issue by Lorraine1903** [magento/magento2#16804]
Hello,

Whenever I research an order with the order number reference. I get 1 result but it won't show up in the list section. (please see picture attached)

I'm using Google Chrome on a Macbook pro.

I tried to empty the cache and cookies but nothing has worked.

Please help

thank yoy
![magento bug](https://user-images.githubusercontent.com/41230636/42723095-6d26cc7a-874f-11e8-8701-d766dcaefa65.png)

**Comment by magento-engcom-team** [comment]
Hi @Lorraine1903. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Lorraine1903 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Lorraine1903** [comment]
I don't understand anything

**Comment by lbajsarowicz** [comment]
Are you sure that your cron is working (or make sure that indexes are up to date).

What is more - try to put order reference in filters, not as a keyword?

**Comment by Lorraine1903** [comment]
What is a cron ??

-- 
Bien cordialement, Best regards
*Lorraine KANZONGO ABES*
*Service Client France*
Téléphone : (+33) 09 75 18 28 75 <+33%209%2075%2018%2028%2075>
Email: lorraine@evematelas.fr


*eve Sleep France*

https://www.evematelas.fr



2018-07-14 15:21 GMT+01:00 Lukasz Bajsarowicz <notifications@github.com>:

**Comment by Lorraine1903** [comment]
I applied the ID in filters, not working either

**Comment by ghost** [comment]
@Lorraine1903, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
