### ISSUE TITLE
Images and Videos tab not working

### ISSUE THREAD

**Issue by cralls** [magento/magento2#16807]
Summary: 
When I click to expand Image & Videos when editing a product does not show images after migration from 1.9.2.2 to 2.2.3. Console error shows: Uncaught TypeError: Cannot use 'in' operator to search for 'length' in [{

The images show on the product grid and in the frontend just fine. I cannot even upload an image to a new product so something in the migration has not allowed magento to pull the images into the uploader and instead of an array I get that string [{

Console shows the following when I expand Images and Videos:
![image](https://user-images.githubusercontent.com/8516753/42725579-138bf76e-8743-11e8-8bf9-ecda81a7ff44.png)

Environment: 
- PHP 7.0.30
- Apache 2.4.33
- mysql  Ver 15.1 Distrib 10.2.16-MariaDB
-  Magento 2.2.3

Steps to reproduce:
It has to be specific to my environment but what I've done is migrated from 1.9.2.2 to 2.2.3 and the problem exists.

**Comment by magento-engcom-team** [comment]
Hi @cralls. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@cralls do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by cralls** [comment]
Any suggestions on this? It's a major issue. I have all extensions disabled and I can't even add a new product and add images to it. I get the same error. It's like javascript can't get a json object of images for the gallery.

**Comment by engcom-backlog-nickolas** [comment]
Hello @victortodoran, thank you for report. As I cannot reproduce this issue on clean magento 2.2.3 installation, please report this issue in https://github.com/magento/data-migration-tool repository.

**Comment by toddhainsworth** [comment]
@magento-engcom-team I'm now able to re-create this in a 2.4 instance (note; not migrated from a previous version) with 2 custom media image attributes created via the admin. Same message as @cralls above.
