### ISSUE TITLE
Duplicate argument overwrites option language DeployStaticContentCommand

### ISSUE THREAD

**Issue by Swahjak** [magento/magento2#16806]
### Preconditions

1. Magento 2.3-alpha
2. Not installed: no env.php present, no database available, build environment

### Steps to reproduce

1. run `bin/magento setup:static-content:deploy -t Magento/blank -l nl_NL -f
2. 
3. 

### Expected result

1. Static content for locale `nl_NL` is deployed for theme `Magento/blank`

### Actual result

1. Static content for locale `all` is deployed (defaults to `en_US` on a installation without database available)

```php
// class Magento\Setup\Console\Command\DeployStaticContentCommand
// line 122
$options[Options::LANGUAGE] = $input->getArgument(Options::LANGUAGES_ARGUMENT) ?: ['all'];
```
This will always overwrite the option
```php
// class Magento\Deploy\Console\DeployStaticOptions
// line 198-204
 new InputOption(
      self::LANGUAGE,
      '-l',
      InputOption::VALUE_IS_ARRAY | InputOption::VALUE_OPTIONAL,
     'Generate files only for the specified languages.',
    ['all']
 )
```

**Comment by magento-engcom-team** [comment]
Hi @Swahjak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Swahjak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Swahjak** [comment]
@magento-engcom-team give me 2.3.0-alpha instance

**Comment by magento-engcom-team** [comment]
Hi @Swahjak. Thank you for your request. I'm working on Magento 2.3.0-alpha instance for you

**Comment by ghost** [comment]
@Swahjak, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@keharper, please check after holidays
[deploy_without_db](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-static-view.html#deploy_without_db). It looks like people can do more than described in DevDocs even without this fix but I am not sure that all release lines allow to do these actions.

Merge of this bugfix is a good reason to add missing lines to the documentation. Example of deploying static content for the Magento without db and config and a little remark about situation when it is useful would be more than enough.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
