### ISSUE TITLE
magento showing wrong thumbnail on product page

### ISSUE THREAD

**Issue by hzubyrss** [magento/magento2#16822]
I recently update magento to latest version of M1 but after upgrade on product view thumb nail showing wrong name not same as it i checked in admin product manager any help ? on category page and in other all blocks show fine ! 

Thanks in advance

**Comment by magento-engcom-team** [comment]
Hi @hzubyrss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@hzubyrss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mhauri** [comment]
Hi @hzubyrss this issue section is for issues with Magento 2 only.

Please ask your question on [Magento StackExchange](https://magento.stackexchange.com/) or in the [Magento Forum](https://community.magento.com/t5/Magento-1-x-Technical-Issues/bd-p/Technical).
