### ISSUE TITLE
Failed - Network error Magento2 export

### ISSUE THREAD

**Issue by ewallteam** [magento/magento2#16859]
### Preconditions

1. Magento 2.2.4 
2. PHP 7.1
3. Ubuntu 16.04

### Steps to reproduce

1. Goto System-> Export
2. Select Entity Type as Customers Main FIle
3. Select Export File Format as CSV
4. Click on Continue button

### Expected result

1. Export file should be downloaded with the customer data

### Actual result

1. File started to download and showing the file size while the download is in progress
2. After the download completes, its showing Failed - Network error(https://prnt.sc/k71f6j)
3. No files are downloaded to my local Downloads folder however the exported file is available under /var/www/html/var folder on the server

Guess its purely the server side issue since the export is working fine for the same magento 2 copy on our local server and this issue is happening only with the live server.

**Comment by magento-engcom-team** [comment]
Hi @ewallteam. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ewallteam do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@ewallteam, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by sarvy-p** [comment]
@ewallteam 
I am facing the same issue. Could please kindly provide some information about how you fix that issue.
Any server setting or any change in Magento?

Thanks in advance

**Comment by razvan-f** [comment]
Having same problem. Magento 2.3.2, PHP 7.2, Siteground hosting.

**Comment by wbfiretoss** [comment]
Facing the same issue not sure why this issue is closed.
