### ISSUE TITLE
Default billing and shipping information is lost when updating new default billing and shipping addresses

### ISSUE THREAD

**Issue by dwaynebartels** [magento/magento2#16854]
When the id's default billing and shipping are set on customer, you cannot add new addresses that are default billing or shipping using the API (PUT /V1/customers/{customerId})

### Preconditions
1. Magento CE 2.2.3 and above.      
ENTERPRISE also has these problems. I suspect earlier versions then 2.2.3.

### Steps to reproduce
Make sure customer's default billing and shipping id's aren't set.
1. Update customer with new address (no id's)  and set default billing and shipping `true`
Result: If default and billing id's arent set, it will accept new addresses as default billing and shipping. On Customer level default billing and shipping id's are SET.
2. Update customer with new address (no id's) using API (PUT /V1/customers/{customerId}) and set default billing and shipping `true`
Result: New addresses are added but the default billing and shipping information is lost. 

When you repeat the process, default billing and shipping are set again after each time information is lost. 

### Expected result

1. We want default billing and shipping to be set without overwriting the exisiting id. 
It has always worked this way and because or customers administration (ERP) is leading. 
We want to be able to work without id's.

### Actual result

1. Default billing and shipping information is lost.

**Comment by magento-engcom-team** [comment]
Hi @dwaynebartels. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dwaynebartels do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dwaynebartels** [comment]
@magento-engcom-team 
yes

**Comment by engcom-backlog-nickolas** [comment]
Hello @dwaynebartels, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dwaynebartels** [comment]
We've introduced a workaround in our code by overwriting the default billing and shipping address when available. In the case of new adresses the boolean value default billing or shipping is sufficient. 

This way we can support older and newer versions of Magento.

**Comment by dwaynebartels** [comment]
Reopened issue because the bug still remains that you cant add new addresses that are default billing and or shipping. You have to override the existing address. We would like to have full control through API.

**Comment by magento-engcom-team** [comment]
Hi @cedmudit. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
