### ISSUE TITLE
Stock Management

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#16868]
Magento 2 All the version Same issue, admin is not getting any emails in regards to the low stock of the products, even after setting it up in settings to notify for low stock.
### Preconditions
Magento 2.2.3
This hasn't been happening since Magento 2 was launched
PHP 7.1.12
MySQL 5.0.12
### Steps to reproduce
Login to Admin Panel
Store Configuration -> Catalog -> Inventory
Product Stock Option
Notify for Quantity Below is set to 5
Save Config
No Email is been Sent to admin when the quantity of any product goes below 5
### Expected result
Admin should receive an email if the quantity of any product goes below 5
### Actual result
No Email is been Sent to admin when the quantity of any product goes below 5

**Comment by magento-engcom-team** [comment]
Hi @terrybakshi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@terrybakshi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@terrybakshi, thank you for your report.
Please provide more detailed steps to reproduce or try to reproduce this issue.

**Comment by terrybakshi** [comment]
**Preconditions**
Magento 2.2.3
This hasn't been happening since Magento 2 was launched
PHP 7.1.12
MySQL 5.0.12
**Steps to reproduce**
Login to Admin Panel
Store Configuration  -> Catalog -> Inventory
**Product Stock Option**
Notify for Quantity Below is set to 5
Save Config 
No Email is been Sent to admin when the quantity of any product goes below 5
**Expected result**
Admin should receive an email if the quantity of any product goes below 5
**Actual result**
No Email is been Sent to admin when the quantity of any product goes below 5

**Comment by ghost** [comment]
@terrybakshi, thank you for your report.
There is no low-stock notification by email in Magento 2. You can be notified by RSS or by accessing Reports -> Products -> Low Stock in admin menu.

**Comment by terrybakshi** [comment]
Such a big platform and this basic feature is not present, its a real shame

**Comment by paginasweb** [comment]
I hope this issue is been fixed in future releases
