### ISSUE TITLE
Order mail sender empty

### ISSUE THREAD

**Issue by herod2k** [magento/magento2#16865]
### Preconditions
1. Magento 2.2.5 (vanilla) with sample products
2. Php 7.1.19
3. Apache 2.4.33
4. Operating system: Fedora 28

### Steps to reproduce
1. Install Magento 2.2.5 with sample products
2. Configure the store with more than a view
![image](https://user-images.githubusercontent.com/3713164/42772081-30e12c6e-8921-11e8-8470-c48bf5ab7160.png)
3. Configure each view a different currency and a different currency
4. Enable free shipping
5. Set the shop emails inside the admin panel 
6. Create a shop user
7. Chose a product and make an order.

### Expected result
I should receive the order email with the correct sender.
Something like this:
![image](https://user-images.githubusercontent.com/3713164/42772766-588819f6-8923-11e8-984d-74d15cf99a11.png)

### Actual result
![image](https://user-images.githubusercontent.com/3713164/42772380-2298a2f8-8922-11e8-91c8-e3a55b7b9359.png)

If you use a software like SSMTP
![image](https://user-images.githubusercontent.com/3713164/42772418-48fcab56-8922-11e8-96f0-20b0b93d77fe.png)
You can receive the email from Apache (because the sender is empty).

### Additional information
I've tried only with a multiple views store but I don't think that is related to that, you should be able to replicate the error also with a single view store.

I've investigated a little bit the problem and it seems to be related to the class:
Magento\Sales\Model\Order\Email\SenderBuilder

The method **configureEmailTemplate**
```
protected function configureEmailTemplate()
    {
        $this->transportBuilder->setTemplateIdentifier($this->templateContainer->getTemplateId());
        $this->transportBuilder->setTemplateOptions($this->templateContainer->getTemplateOptions());
        $this->transportBuilder->setTemplateVars($this->templateContainer->getTemplateVars());
        $this->transportBuilderByStore->setFromByStore(
            $this->identityContainer->getEmailIdentity(),
            $this->identityContainer->getStore()->getId()
        );
    }
```

Specially the step: $this->transportBuilderByStore->setFromByStore(...), it seems that it doesn't set the From.

**Comment by magento-engcom-team** [comment]
Hi @herod2k. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@herod2k do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@herod2k, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue.
