### ISSUE TITLE
% symbol in editor, throws URI error prompt

### ISSUE THREAD

**Issue by phpology** [magento/magento2#16862]
Hi guys,

Magento ver. 2.0.16

We have noticed that if a content item has a percentage (%) symbol in the copy of the description content, we get a javascript prompt error within the WYSIWYG editor:

**error: error in [unknown object].fireEvent(): event name: tinymceSaveContent error message: URI malformed.**

If our content has images/links inserted using the Magento variables, this all breaks. 

![image](https://user-images.githubusercontent.com/243916/42767678-82e21bd8-8915-11e8-9bb1-90ada51223c1.png)

**Comment by magento-engcom-team** [comment]
Hi @phpology. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@phpology do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @phpology, thank you for your report. Unfortunately magento 2.0.x no longer supported https://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.18CE.html. 
To maintain the performance and security of your site, we advise you to upgrade to the latest version of Magento Open Source.
