### ISSUE TITLE
Headings of the Curstomer Account page are shown at the end of the page

### ISSUE THREAD

**Issue by richardreen** [magento/magento2#16860]
In Magento 2.2.5 the headings of the customer account page are not visible at the top of the page but at the end.
See screenshot for more. This is a new install of Magento 2.2.5.

![screenshot_20180713_171625](https://user-images.githubusercontent.com/18627705/42761426-c6e3f318-890d-11e8-9be5-263e905beb55.png)

Error is caused by wrong name of destination in vendor//magento/theme-frontend-luma/Magento_Customer/layout/customer_account.xml

Error in following line:
 ...move element="page.main.title" destination="content.top" before="-"/...

When corrected in:
...move element="page.main.title" destination="columns.top" before="-"/"....

The headings are on the correct place again.

**Comment by magento-engcom-team** [comment]
Hi @richardreen. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@richardreen do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by richardreen** [comment]
Magento version 2.2.5

**Comment by engcom-backlog-nickolas** [comment]
Hello @richardreen, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by chirag-wagento** [comment]
Hello @engcom-backlog-nickolas  I think this PR and   #16786 this PR are same.

Thanks

**Comment by engcom-backlog-nickolas** [comment]
@chirag-wagento, you are right. Thanks for pointed it out. 
@richardreen, I'm closing this issue as duplicate of #16786. If you'd like to update it, please feel free to reopen this issue.
