### ISSUE TITLE
Mini cart  not getting updated if product disabled from backed. 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16878]
In my Magento project, if the product is in the cart and I disabled that product from backend after adding it to the cart. Then that product should not display to the cart or should show a message that "Product is out of stock"
     
### Preconditions
- PHP 7.0.30
- magento 2.1.10

### Steps to reproduce

1. make user login on the website
2. add the product to cart
3. Disabled product from backend
4. Refresh site & check cart.

### Expected result
Product absent in minicart.

### Actual result
Product still present in minicar.

**Comment by magento-engcom-team** [comment]
Hi @gaurid-iprogrammer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@gaurid-iprogrammer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @gaurid-iprogrammer, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by binnykumar** [comment]
Hello Folks,

Is there any workaround for this issue in 2.1.5 version ? I am facing this issue for multiple customers for a brand and upgrade can not be done immediately.

**Comment by magento-engcom-team** [comment]
Hi @gaurid-iprogrammer 
We are closing the ticket now, as issue has been fixed in 2.2.x. Please reopen if you think the issue persists.
