### ISSUE TITLE
Issues adding block to sidebar in sales_order_create_index.xml

### ISSUE THREAD

**Issue by joshuabromero** [magento/magento2#16884]
When adding a custom block to the sidebar in a sales_order_create_index.xml file the block is not rendered on the first page load. However, on every subsequent page load thereafter the block renders fine.

**Preconditions**

PHP 7.0.30
MariaDB 10.3.8
Apache 2.4.33
Magento 2.2.5

**Steps to reproduce**

1. Create a new module
2. Add a custom layout (view/adminhtml/layout/sales_order_create_index.xml) and custom template
3. 

**Expected result**

1. Admin sidebar should display the custom block on first page load.

**Actual result**

1. Admin sidebar doesn't display the custom block until second page load.

**Comment by magento-engcom-team** [comment]
Hi @oddyssey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@oddyssey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @oddyssey, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by PanagiotisPapoutsis** [comment]
Same issue here.
I have extended the sales_order_create_index.xml layout file like this

`<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance dc" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
	<referenceBlock name="shipping_method">
	    <block class="Vendor\Module\Block\Adminhtml\CarrierShipping" template="Vendor_Module::order/carrier-shipping.phtml" name="shipping_method_custom">
	    </block>
	</referenceBlock>
</page>`

I then created a simple phtml and placed it in the above path. My template renders only after I reload the page.

**Preconditions**
PHP 7.0.30
Nginx 1.13.8
Magento 2.2.3

As a workaround I overrode the template file of one of the existing blocks of this layout(sales_order_create_index) and then I added the function below in the PHP Block file of this existing block.
`protected function _prepareLayout()
    {
        parent::_prepareLayout();
        $this->setTemplate('Vendor_Module::order/create/shipping/method/form.phtml');
        return $this;
    }`

**Comment by magento-engcom-team** [comment]
Hi @AleksLi. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by AleksLi** [comment]
@magedevjosh Hi. I was investigating this issue. I can reproduce it easily. You are right.
But.. I found the similar blocks that are visible with the first page loading. 
Please look at any block added here `sales_order_create_load_block_sidebar.xml`. 
Let's take wishlist for example. You can find `sales_order_create_load_block_sidebar_wishlist.xml` which is describing the behavior on the first loading. 

Generally, you should add your custom block to the both `sales_order_create_load_block_sidebar.xml` and create your own `sales_order_create_load_block_sidebar_...YOURNAME...xml`.
