### ISSUE TITLE
Magento 2.2.5 Backend redirect loop after change default storview url

### ISSUE THREAD

**Issue by Webroju** [magento/magento2#16886]
Create in Magento 2.2.5 two websites and assign each website a store and a storeview.
For all is now "domain.tld"  the url.
Now I changed for the first storeview (at storeview level) the domain to another domain like "domain2.tld". Save, update, compile over cli, then I can't access the backend, because of a redirect loop.
The expected result is, that I can access over the "domain.tld" the backend and only the first storeview ist accessable over the "domain2.tld".

### Preconditions

1.  Magento 2.2.5.
2. PHP 7.1.3
3. NGINX 
4. MySQL 5.6.30

### Steps to reproduce

1.  Create a second website, and assign a store and a storeview to this
2. Change at Stores > Configuration > Web  to the the scope "Default Store View"
3. at "Base URL" and "Base Link URL" uncheck  "use website" for each field so that you can change the value to another url,  (but the default value remains )
3. Save

### Expected result

1. Access to the backend over the default url 
2. Access to the second storeview over the default URL

### Actual result

1. Redirect loop so that nothing is shown and the backend is not accessable
2. Access to the second storeview redirect to the fist storeview URL

**Comment by magento-engcom-team** [comment]
Hi @Webroju. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Webroju do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Webroju** [comment]
@magento-engcom-team give me {2.2.5} instance

**Comment by ghost** [comment]
@Webroju, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by igor-imaginemage** [comment]
I am able to reproduce the same issue in a vanilla Magento instance. Trying to fix the issue and contribute.
