### ISSUE TITLE
Magento Store view URL with slash instead of underscore

### ISSUE THREAD

**Issue by vinoth44** [magento/magento2#16908]
We have different stores for 6 countries with 2 languages for each English and Arabic. So totally we have 12 store view. Everything works fine, but the URL of store http://example.com/COUNTRY_LANGUAGE to changed to http://example.com/COUNTRY/LANGUAGE. I am not sure how to achieve this, I know it is adding store in the URL after domain name. But I cannot setup store with slash(/). 

### Preconditions

1. Magento EE 2.1.2
2. PHP 7.0.2 Mysql 5.6

### Expected result

1. http://example.com/kw/en/
2. http://example.com/kw/ar/
3 http://example.com/sa/en/
4 http://example.com/sa/ar/

### Actual result

1. http://example.com/kw_en/
2. http://example.com/kw_ar/
3. http://example.com/sa_en/
4. http://example.com/sa_ar/

**Comment by magento-engcom-team** [comment]
Hi @vinoth44. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vinoth44 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@vinoth44, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by vinoth44** [comment]
@engcom-backlog-nickolas  I have already posted in stack exchange there is no response so I have posted here consider that is could be potential issue / change request.
