### ISSUE TITLE
Not redirecting depending on the storeview code

### ISSUE THREAD

**Issue by radulff** [magento/magento2#16907]
We have different store views: Spanish (es_es), French (fr_fr) and English (en). And we have a RMA extension where you can create them. Once you create a RMA you redirect to the same RMA page; we assume it works for the english storeview because of the code of the storeview is "en", not like the spanish and the french ones which have respectively (es_es) and (fr_fr) which redirect to the homepage. 

**This is the condition that redirects:**
```
if ($result[0] == self::HTTP_CODE_OK) {
                                $this->sendEmailSuccessCreateRma($result[1]);
                                $this->messageManager->addSuccessMessage(__('RMA was created successfully'));
                                $this->_redirect('sap/rma/index');
                            } else {
                                $this->messageManager->addErrorMessage($result[1]);
                            }
```
**And this statement in the phtml:**
```
<div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action primary" data-role="rma-submit">
                            <span><?= __('Submit Request') ?></span>
                        </button>
                    </div>
                </div>
```

We have tried doing another class class like:

`\Magento\Store\Model\StoreManagerInterface $storeManager`

with this code:
```
$url = $this->_storeManager->getStore()->getUrl('sap/rma/index');
$this->_redirect($url);
```
But it leaves us a blank page and we can't see anything wrong in the logs.

**Comment by magento-engcom-team** [comment]
Hi @rvilama97. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@rvilama97 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@rvilama97, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
