### ISSUE TITLE
magento2.2.5, found bug for attribute with multiple select

### ISSUE THREAD

**Issue by waymanxie** [magento/magento2#16906]
### Preconditions

1. new installation of magento2.2.5 by bitnami package

### Steps to reproduce

1. create 3 store views for 3 languages, like Default, JP, ENG
2. create an attribute "Application" with multiple select 
3. add 2 options, fill in the textbox for admin in ENG, then do the translations
![image](https://user-images.githubusercontent.com/41362735/42870374-46073590-8aaa-11e8-802e-cb1e65b5325a.png)
4. save attribute.
5. use this attribute to create a new product

### Expected result

1. at the admin product page, the attribute "Application" should display in English  

### Actual result

1. it display in JP
![image](https://user-images.githubusercontent.com/41362735/42870493-97c29816-8aaa-11e8-903e-c15099d20102.png)

**Comment by magento-engcom-team** [comment]
Hi @waymanxie. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@waymanxie do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by waymanxie** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @waymanxie. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @waymanxie, here is your [Magento instance](https://i-16906-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16906-2-2-5.engcom.dev.magento.com/admin](https://i-16906-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@waymanxie, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
![1](https://user-images.githubusercontent.com/40756187/42878373-81b72a2e-8a95-11e8-8cce-addab7238a1b.gif)

**Comment by waymanxie** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @waymanxie. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @waymanxie, here is your [Magento instance](https://i-16906-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16906-2-2-5.engcom.dev.magento.com/admin](https://i-16906-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by waymanxie** [comment]
yes，i can't reproduce this issue on the new instance. but on my VM instance, this still happen even if i create a new attribute. 

i'll check this out by my side, and will report here if i find anything. thanks for the support.

**Comment by ghost** [comment]
@waymanxie, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
