### ISSUE TITLE
Incorrect displaying Product Image Watermarks on Magento 2.2.5

### ISSUE THREAD

**Issue by dzima-chyzhou** [magento/magento2#16929]
### Summary
Background of Product Image Watermarks is displayed incorrect if it is transparent.

### Preconditions
1. Magento 2.2.5 CE with sample data
2. PHP 7.0.30

### Steps to reproduce
1. Login to Admin Panel
2. Create a simple product with any configuration and upload any product image (the image that I uploaded below)
![mb01-blue-0](https://user-images.githubusercontent.com/40271588/42928337-b21a3f6c-8b3f-11e8-9e4b-d92567ef00bf.jpg)
3. Go to Content -> Design -> Configuration 
4. Click on the edit action on the Global Magento Luma theme
5. Go to the Product Image Watermarks section
6. Upload any PNG image with a transparent background for example in the small category (the image that I uploaded below)
![58480ecccef1014c0b5e492c](https://user-images.githubusercontent.com/40271588/42926131-2478ff0a-8b39-11e8-99e6-ecc56f478ba3.png)
7. Set Image Opacity to 10
8. Set Image Size to 40x50
9. Set Image Position Tile 
10. Save Configuration
11. Go to the product view on store front and look at the result

### Expected result
1. Product Image Watermarks are displayed over a product image
2. Image Watermarks size is 40x50
3. Image Watermarks position is tile
4. Image Watermarks opasity is 10
5. Background of Image Watermarks is transparent as it is transparent on an uploaded image

### Actual result
1. Product Image Watermarks are displayed over a product image
2. Image Watermarks size is 40x50
3. Image Watermarks position is tile
4. Image Watermarks opacity is 10
5. Background of Image Watermarks **IS NOT** transparent.
![screenshot from 2018-07-19 10-35-21](https://user-images.githubusercontent.com/40271588/42928436-f2c9d400-8b3f-11e8-8269-07f9218b0cf8.png)

**Comment by magento-engcom-team** [comment]
Hi @chizhov13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@chizhov13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dzima-chyzhou** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @chizhov13. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @chizhov13, here is your [Magento instance](https://i-16929-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16929-2-2-5.engcom.dev.magento.com/admin](https://i-16929-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dzima-chyzhou** [comment]
@magento-engcom-team yes. I am able to reproduse this issue. Just go to the product view on the store front and look at the result.

**Comment by engcom-backlog-nickolas** [comment]
Hello @chizhov13, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ronak2ram** [comment]
Hello @chizhov13
Can you please check solution #17013

**Comment by dzima-chyzhou** [comment]
Hello @ronak2ram thank you for your response.

I checked your solution on Magento 2.2.5, everything is okey. But then I have tried to reproduce this bug on Magento 2.1.14 and it still does not work properly.

I see that this issue is opened for 2.2.x and 2.3.x. but also need to fix it on Magento 2.1.x

**Comment by salehawal** [comment]
@ronak2ram thanks it is working now on magento 2.2.4

**Comment by magento-engcom-team** [comment]
Hi @chizhov13. Thank you for your report. 
The issue has been fixed in magento/magento2#17013 by @ronak2ram in 2.2-develop branch
Related commit(s):
 - [3259f5afae915ced2e4cb74a7ea595d9a1959b5f](https://github.com/magento/magento2/commit/3259f5afae915ced2e4cb74a7ea595d9a1959b5f)
 - [ae24b01152cbd8744957a7f59080030d7882affe](https://github.com/magento/magento2/commit/ae24b01152cbd8744957a7f59080030d7882affe)

The fix will be available with the upcoming 2.2.7 release.

**Comment by magento-engcom-team** [comment]
Hi @chizhov13. Thank you for your report. 
The issue has been fixed in magento/magento2#17623 by @ronak2ram in 2.3-develop branch
Related commit(s):
 - [686406a87fdf04c4924ca2e50d5fb85ba61360cd](https://github.com/magento/magento2/commit/686406a87fdf04c4924ca2e50d5fb85ba61360cd)

The fix will be available with the upcoming 2.3.0 release.
