### ISSUE TITLE
2.2.5 Swagger: With JS minification enabled, the swagger-ui-bundle.js becomes corrupted

### ISSUE THREAD

**Issue by Silarn** [magento/magento2#16927]
### Preconditions
1. Magento 2.2.5
2. PHP 7.1

### Steps to reproduce
1. Enable JS minification
2. Deploy a fresh copy of the static content
3. Visit the Swagger page

### Expected result
The swagger page loads and is usable

### Actual result
The swagger page fails because the swagger-ui-bundle.js throws an error
![image](https://user-images.githubusercontent.com/826174/42913851-d2da9496-8abc-11e8-94b0-6b58bf1ccd8a.png)

The JS works fine when minification is disabled and the files redeployed.

**Comment by magento-engcom-team** [comment]
Hi @Silarn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Silarn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Silarn** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @Silarn. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Silarn, here is your [Magento instance](https://i-16927-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16927-2-2-5.engcom.dev.magento.com/admin](https://i-16927-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Silarn** [comment]
I am able to reproduce on your vanilla instance. Simply enable JS minification and load the Swagger page.

**Comment by engcom-backlog-nickolas** [comment]
Hello @Silarn, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by hostep** [comment]
Confirmed.

Seems to be introduced by https://github.com/magento/magento2/commit/477252628beb7cd9a9d20f19405f5d10c48e3cb9

Since the files `swagger-ui-bundle.js` & `swagger-ui-standalone-preset.js` are already minified and the js minifier used by Magento seems to have problems with trying to minify already minified files, those files should probably be marked as to not be minified?

/cc @VladimirZaets: would that be the correct solution here?

~~I already tried updating the `swagger-ui-bundle.js` file from [`3.10.0`](https://raw.githubusercontent.com/swagger-api/swagger-ui/v3.10.0/dist/swagger-ui-bundle.js) to the latest [`3.17.6`](https://raw.githubusercontent.com/swagger-api/swagger-ui/v3.17.6/dist/swagger-ui-bundle.js), just as a test, but that doesn't solve the problem.~~

**Comment by hostep** [comment]
Update: I goofed up testing, and upgrading `swagger-ui-bundle.js` to version [`3.17.6`](https://raw.githubusercontent.com/swagger-api/swagger-ui/v3.17.6/dist/swagger-ui-bundle.js) actually does fix the problem.

Another way of fixing the problem would be to copy those files with filenames `swagger-ui-bundle.min.js` and `swagger-ui-standalone-preset.min.js`, so Magento avoids minifying these files since they already exist. But not sure if this is the most clean solution here?

**Comment by sidolov** [comment]
Hi @Silarn. Thank you for your report. 
The issue has been fixed in magento/magento2#17627 by @hostep in 2.3-develop branch
Related commit(s):
 - [6aeec4710d0decd5161bb3855e83540df81e6a14](https://github.com/magento/magento2/commit/6aeec4710d0decd5161bb3855e83540df81e6a14)

The fix will be available with the upcoming 2.3.0 release.

**Comment by Silarn** [comment]
Great. Thanks for the fix. Would renaming the files work on current releases as a temporary workaround?

**Comment by hostep** [comment]
@Silarn: in the current release, I just copy them and keep the ones without '.min', these then are used when minification is disabled, and when minification is enabled it will use the new ones with '.min' in the filename.
Or just [patch](https://support.magento.com/hc/en-us/articles/360005484154) your installation, by renaming them and changing the `swagger_index_index.xml` file as well.

**Comment by leoquijano** [comment]
Hi @magento-engcom-team, any chance this fix will be ported to the 2.2 line?

**Comment by hostep** [comment]
@leoquijano: this fix will be included in Magento 2.2.7, see: https://github.com/magento/magento2/pull/17626#issuecomment-416313986

**Comment by leoquijano** [comment]
Alright. Thank you @hostep.
