### ISSUE TITLE
Magento 2.0.17 - Mixed Content issue URL 

### ISSUE THREAD

**Issue by shaikhmasud147** [magento/magento2#16931]
**Summary**
Mix Content Issue URL 

**Preconditions**
Magento 2.0.17 CE with sample data
PHP 7.0.30

**Steps to reproduce**
Some product page link not active HTTPS. When I checked under inspect element thier display mix content url issue. 

![screenshot_2018-07-19_14-35-39](https://user-images.githubusercontent.com/21688214/42933167-b9d58ee2-8b61-11e8-8f54-9a296eba138a.png)

**Expected result**
All Magento front end link redirect and display HTTP to HTTPS

**Actual result**
Some link display HTTPS but is not active

**Comment by magento-engcom-team** [comment]
Hi @shaikhmasud147. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@shaikhmasud147 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @shaikhmasud147, thank you for your report. Unfortunately magento 2.0.x no longer supported https://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.18CE.html.
To maintain the performance and security of your site, we advise you to upgrade to the latest version of Magento Open Source.

**Comment by shaikhmasud147** [comment]
Hi @engcom-backlog-nickolas 
Ok, I will upgrade. Thank you very much.
