### ISSUE TITLE
Sales order emails not sending

### ISSUE THREAD

**Issue by shahanasnkv** [magento/magento2#16938]
### Preconditions
1. Magento 2.2.5
2. Ngnix
3. Php 7

### Steps to reproduce
1. Click send email button from admin panel order details
2. Place order

### Expected result
1. Email should send to customer

### Actual result
1. No Email sending

### Temporary solution which i found
Changing content of Magento\Sales\Model\Order\Email\ SenderBuilder
to below

protected function configureEmailTemplate()
{
    $this->transportBuilder->setTemplateIdentifier($this->templateContainer->getTemplateId());
    $this->transportBuilder->setTemplateOptions($this->templateContainer->getTemplateOptions());
    $this->transportBuilder->setTemplateVars($this->templateContainer->getTemplateVars());
   /* $this->transportBuilderByStore->setFromByStore(
        $this->identityContainer->getEmailIdentity(),
        $this->identityContainer->getStore()->getId()
    );*/
    $this->transportBuilder->setFrom(
        $this->identityContainer->getEmailIdentity()
    );
}

**Comment by magento-engcom-team** [comment]
Hi @shahanasnkv. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@shahanasnkv do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@shahanasnkv, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by gwharton** [comment]
See PR #16461

**Comment by ihor-sviziev** [comment]
It looks like duplicate of https://github.com/magento/magento2/issues/14952

**Comment by loibv5989** [comment]
I have the same problem with version 2.2.5, I tried with #16461 but it does not work, does anyone have a different view
