### ISSUE TITLE
On PDP - Fatal error: Uncaught Error: Cannot instantiate abstract class 

### ISSUE THREAD

**Issue by sajidpatel** [magento/magento2#16930]
### Issue
class Magento\Catalog\Block\Product\View\AbstractView causes errors on magento-cloud

https://github.com/mobilefunuk/magic42-packt/blob/integration/shared/app/design/frontend/Packt/default/Magento_Catalog/layout/catalog_product_view.xml

lines 13 and 20

I am getting the following error on cloud:
Fatal error: Uncaught Error: Cannot instantiate abstract class Magento\Catalog\Block\Product\View\AbstractView in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111 Stack trace: #0 /app/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Catalog...', Array) #1 /app/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Catalog...', Array) #2 /app/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Catalog...', Array) #3 /app/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('Magento\\Catalog...', Array) #4 /app/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\\Catalog...', Array) #5 /app/vendor/magento/frame in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111

### Steps to reproduce

Currently integration is as below:

              <block name="product.info.meta"
                     class="Magento\Catalog\Block\Product\View\AbstractView"
                     template="Magento_Catalog::product/view/meta.phtml">
                  <block name="product.info.meta.authors"
                         class="Packt\Authors\Block\Product\View\Author" />
              </block>

              <block name="product.info.stats"
                     class="Magento\Catalog\Block\Product\View\AbstractView"
                     template="Magento_Catalog::product/view/stats.phtml"
                     after="product.info.meta"/>

shared/app/design/frontend/Packt/default/Magento_Catalog/layout/catalog_product_view.xml

You may need to find another non-abstract class

### How I got it to work

I changed it to:

              <block name="product.info.meta"
                     class="Magento\Catalog\Block\Product\View\Author"
                     template="Magento_Catalog::product/view/meta.phtml">
                  <block name="product.info.meta.authors"
                         class="Packt\Authors\Block\Product\View\Author" />
              </block>

              <block name="product.info.stats"
                     class="Magento\Catalog\Block\Product\View\Author"
                     template="Magento_Catalog::product/view/stats.phtml"
                     after="product.info.meta"/>

shared/app/design/frontend/Packt/default/Magento_Catalog/layout/catalog_product_view.xml
### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @sajidpackt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sajidpackt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
