### ISSUE TITLE
Magento 2.0.17 - Customer Name Not Display After Login

### ISSUE THREAD

**Issue by shaikhmasud147** [magento/magento2#16934]
**Summary**
Customer Name Not Display After Login

**Preconditions**
Magento 2.0.17 CE with sample data
PHP 7.0.30

**Steps to reproduce**
Customer Name Not Display After Login. I have checked under inspect element **Customer-Data.js** issue viewed.

![screenshot_2018-07-19_15-06-42](https://user-images.githubusercontent.com/21688214/42934785-a73d7dae-8b65-11e8-905d-a27de6dc6ab6.png)

**Expected result**
Display Customer name after login.

**Actual result**
Customer Name Not Display After Login.

**Comment by magento-engcom-team** [comment]
Hi @shaikhmasud147. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@shaikhmasud147 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @shaikhmasud147, thank you for your report. Unfortunately magento 2.0.x no longer supported https://devdocs.magento.com/guides/v2.0/release-notes/ReleaseNotes2.0.18CE.html.
To maintain the performance and security of your site, we advise you to upgrade to the latest version of Magento Open Source.

**Comment by shaikhmasud147** [comment]
Hi @engcom-backlog-nickolas
Ok, You mean should upgrade Magento 2 then the issue will resolve?

**Comment by engcom-backlog-nickolas** [comment]
@shaikhmasud147 yes
