### ISSUE TITLE
 After product disabled from backed memory exhausted issue is coming 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16933]
After product disabled from the backend, memory exhausted issue is coming.
This issue is coming for only those user whos cart has the product which later disabled.

**Preconditions**

-  PHP 7.0.30
-  Magento 2.1.10

**Steps to reproduce**
1. login to the site
2. add products to cart
3. now disable any one product from the backend (a product which is in the cart)
4. then try to add another product in the cart 
     
**Expected results**
1. The product should get added to cart without any issue

 **Actual result**
1. After debugging getting following error
Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vlcc-personal-care/vendor/magento/framework/Model/AbstractModel.php on line 354

**Comment by magento-engcom-team** [comment]
Hi @gaurid-iprogrammer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@gaurid-iprogrammer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @gaurid-iprogrammer, thank you for your report. I cannot reproduce this issue.
![peek 2018-07-19 14-03](https://user-images.githubusercontent.com/40755810/42938693-d3a86926-8b5b-11e8-993a-acd6adc11db1.gif)
Could you please provide more details?

**Comment by jignesh-baldha** [comment]
@gaurid-iprogrammer I can't reproduce this issue.

**Comment by ghost** [comment]
1. login to the website
2. Add products to the cart
3. Disable any product which is in the cart of the user
4. now try to check out or try to add another product to the cart.
It is returning 500 error on my browser

I hope you understand

**Comment by engcom-backlog-nickolas** [comment]
@gaurid-iprogrammer, we were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by primisuimotori** [comment]
any solution ?
