### ISSUE TITLE
Wrong using @var comments

### ISSUE THREAD

**Issue by springimport** [magento/magento2#16944]
### Preconditions
1. Check `@var` comments in magento 2 (except zend framework).

### Steps to reproduce
1. Search files by `@var $` and `@var \`.

### Expected result
```php
/** @var \Magento\Store\Model\Store $adminStore */
```

### Actual result
```php
/** @var $agreement \Magento\CheckoutAgreements\Model\Agreement */
```

I think magento should use only `phpdoc` for variable comments instead of `phpdoc/vardoc`.

- [phpdoc and vardoc](https://stackoverflow.com/questions/1798477/variable-type-hinting-in-netbeans-php) on StackOverflow.
- [@var](http://docs.phpdoc.org/references/phpdoc/tags/var.html) on phpDocumentor.

**Comment by magento-engcom-team** [comment]
Hi @springimport. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@springimport do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @springimport, thank you for your report. In Magento both phpdoc and vardoc are valid.
https://devdocs.magento.com/guides/v2.2/coding-standards/docblock-standard-general.html#var
