### ISSUE TITLE
Magento 2.2.5 - Table catalogsearch_fulltext_scope1_tmp not being automatically generated

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#16949]
Summary
The exception log becomes bloated with "main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'catalogsearch_fulltext_scope1_tmp' doesn't exist". It appears as if the indexer is not automatically generating this table. I can manually add the table, but it disappears after one indexing cycle.

Environment
Magento 2.2.5 and possibly earlier versions
PHP 7.0
Custom extensions are installed but are up to date with magento version

### Steps to reproduce

1. Upgrade from Magento 2.2.4 to 2.2.5
2. Check that cron jobs are set up and running
3. Check exceptions log

### Expected result

1. On indexing cycle, no errors should occur.

### Actual result

1. On indexing cycle, error "main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'catalogsearch_fulltext_scope1_tmp' doesn't exist" appears.

**Comment by magento-engcom-team** [comment]
Hi @Ctucker9233. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Ctucker9233 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rimpal18** [comment]
> Summary
> The exception log becomes bloated with "main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'catalogsearch_fulltext_scope1_tmp' doesn't exist". It appears as if the indexer is not automatically generating this table. I can manually add the table, but it disappears after one indexing cycle.
> 
> Environment
> Magento 2.2.5 and possibly earlier versions
> PHP 7.0
> Custom extensions are installed but are up to date with magento version
> 
> ### Steps to reproduce
> 1. Upgrade from Magento 2.2.4 to 2.2.5
> 2. Check that cron jobs are set up and running
> 3. Check exceptions log
> 
> ### Expected result
> 1. On indexing cycle, no errors should occur.
> 
> ### Actual result
> 1. On indexing cycle, error "main.CRITICAL: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'catalogsearch_fulltext_scope1_tmp' doesn't exist" appears.

Did anyone get solution for it?
