### ISSUE TITLE
Unable to view orders, receive "An error occurred on the server. Please try to place the order again. "

### ISSUE THREAD

**Issue by jfuntas** [magento/magento2#16954]
I have been looking at similar posts with these issues but have run out of things to try.  Getting ready to hire someone to help work through these issues but thought I would check with this community first. Hoping someone can get me pointed in the right direction.
 
There are two issues:
1) Trying to view Orders but we receive the error below. 
"Order View
Information Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving."

2) Checkout issues with all payment methods. Only Cash / Money order is enabled. 
"An error occurred on the server. Please try to place the order again."

Some other things I have tried:
The browser's console reports this error upon checkout.
"jquery.js:10254 POST https://specialtyz.com/cart/rest/lt_spare_1/V1/guest-carts/ab2935c8e25f97ee6dcfa915c292f07d/payment-information 400 (Bad Request)"

One suggestion was to run the upgrade but I receive the error below. (php bin/magento setup:upgrade)
"Running data recurring...Unique constraint violation found"

The exception log is showing a missing table, so I added manually in myphpadmin but the error still occurs in that log file.
CREATE TABLE `specialtyz_cart.sequence_order_1` (
`sequence_value` int(10) unsigned NOT NULL AUTO_INCREMENT,
PRIMARY KEY (`sequence_value`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

Also used Cart Migration version 4.0.1 by LitExtension and imported all items, Manufacturers, Orders, etc. 

Magento 2.2.5
ea-php71
CentOS

Thank you for any suggestions.

[exception.log](https://github.com/magento/magento2/files/2212759/exception.log)
[debug.log](https://github.com/magento/magento2/files/2212761/debug.log)

**Comment by magento-engcom-team** [comment]
Hi @jfuntas. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@jfuntas do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
