### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by ghost** [magento/magento2#16960]
I'm  trying to install extension and  before submitting this issue I have tried a lot of things but nothing worked for me. 

I have purchased paid extension and I'm having problem while installing it
Following is the error, I have changed the permission for path as well.

Check Cron Scripts
Cron script readiness check failed. Hide detail

Error from Setup Application Cron Script:
SQLSTATE[HY000] [2002] Connection refused

Error from Updater Application Cron Script:

Found non-writable path(s):
/opt/bitnami/apps/magento/htdocs/bin/magento

**Comment by magento-engcom-team** [comment]
Hi @Gurdeep0007. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Gurdeep0007 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
I'm not sure about vanilla Magento instance. I'm having own my live server

**Comment by lbajsarowicz** [comment]
For general issues it's better to use https://community.magento.com/t5/Magento-2-x-Technical-Issues/bd-p/magento-2-technical-issues

**Comment by nuzil** [comment]
@Gurdeep0007 please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
