### ISSUE TITLE
Inconsistent official guide on changing order of elements in mini shopping cart

### ISSUE THREAD

**Issue by alan-ngai** [magento/magento2#16963]
- Summary of the issue,
I followed the guide to change the order of elements in mini shopping cart. [This page](https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/templates/template-sample.html)
It mentioned the template is on <Magento_Checkout_module_dir>/view/frontend/web/template/minicart/content.html , 
it does not work, even I have cleaned caches.
However, I found there was inconsistent in the official guide on [this page](https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-inherit.html#theme-inherit-templates), this page mentioned the template is on <Magento_Checkout_module_dir>/view/frontend/templates/cart/minicart.phtml,

what is the appropriate way to change the order of elements in mini shopping cart?

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @alan-ngai. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@alan-ngai do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by lbajsarowicz** [comment]
Maybe it's better place to go: https://github.com/magento/devdocs/issues

Also @alan-ngai you can update the documentation on your own and create PR

**Comment by engcom-backlog-nickolas** [comment]
Hello @alan-ngai, thank you for report. The GitHub issue tracker is intended for Magento Core technical issues only. As mentioned in previous comment, please move your issue here: https://github.com/magento/devdocs/issues
