### ISSUE TITLE
Stores configuration is not opened

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#16979]
### Preconditions

1. Magento 2.3-develop
2. PHP 7.1.20
3. MySQL 5.7.22

### Steps to reproduce

1. Login into Magento Admin
2. Open Stores -> Settings -> Configuration

### Expected result

1. Configuration should be opened

### Actual result

1. User is logged out and message "Visible section not found." is shown.

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@torhoehn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by torhoehn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [Magento instance](https://i-16979-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16979-2-3-develop.engcom.dev.magento.com/admin](https://i-16979-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-backlog-nickolas** [comment]
Hello @torhoehn, thank you for your report. I wasn't able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![peek 2018-07-23 10-26](https://user-images.githubusercontent.com/40755810/43062750-80bbe058-8e62-11e8-96e5-fb75e12a8a03.gif)
