### ISSUE TITLE
StoreResolver does not read store param from url

### ISSUE THREAD

**Issue by shochdoerfer** [magento/magento2#16976]
The `\Magento\Store\Model\StoreResolver` determins the active store from either the defined cookie or the passed request parameter but does not take the store code from the url into account (/rest/my_store_code/V1/...).

### Preconditions

1. Tested with Magento 2.2.5 - other versions might also be affected

### Steps to reproduce
1. Pass the store code in the url to Magento
2. Call `\Magento\Store\Model\StoreResolver::getCurrentStoreId()`

### Expected result

1. The method call returns the default store code as the resolver did not find the cookie in question or the url parameter.

### Actual result

1. The method call should return the id of the store defined in the url.

**Comment by magento-engcom-team** [comment]
Hi @shochdoerfer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@shochdoerfer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @shochdoerfer, thank you for your report. GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.

**Comment by shochdoerfer** [comment]
I'd rather see this a bug report, but I'll play along nicely, here's there "feature request": https://github.com/magento/community-features/issues/77

**Comment by engcom-backlog-nickolas** [comment]
@shochdoerfer, thank you.
