### ISSUE TITLE
General error: 1114 The table 'catalog_product_entity_datetime' is full

### ISSUE THREAD

**Issue by SCush** [magento/magento2#16970]
I am in the process of updating prices on a magento site by replacing complex data through the import/export feature in the backend of Magento. This have uploaded successfully but some products require me to go to manage products and manually change the price there or add a special price. When I try to apply a new price I am met with the following error. 

SQLSTATE[HY000]: General error: 1114 The table 'catalog_product_entity_datetime' is full, query was: INSERT INTO `catalog_product_entity_datetime` (`entity_type_id`,`attribute_id`,`store_id`,`entity_id`,`value`) VALUES (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)

I have little experience with Magento or websites in general so any help would be greatly appreciated.

Steps to reproduce:
-Catalog > Manage Products > open any product > Prices tab
-Write new price
-Save
-Error appears and price isn't updated

**Comment by magento-engcom-team** [comment]
Hi @SCush. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@SCush do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions. Also, googling observed error is usually helpful.

@SCush, it seems that https://stackoverflow.com/a/730600 is what you are looking for.
