### ISSUE TITLE
Less variables defined in theme "_extend.less" can't be overridden in "_theme.less"

### ISSUE THREAD

**Issue by denistrator** [magento/magento2#16989]
### Summary
Less variables defined in theme `<Module>/_extend.less` can't be overridden in `_theme.less`

### Steps to reproduce
1.  Create new theme
2.  Add `Magento_Theme/web/css/source/_extend.less`  with this content:
```
@test: red;

& when (@media-common = true) {
    body {
        background-color: @test;
    }
}
```
3. Try to override `@test` in `web/css/source/_theme.less`:
```@test: green;```

### Expected result
`body` has `green` background

### Actual result
`body` has `red` background

### Solution
In `web\css\styles-m.less` and `web\css\styles-l.less` move `@import 'source/_theme.less';` below  `//@magento_import 'source/_extend.less';`

**Comment by magento-engcom-team** [comment]
Hi @denistrator. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@denistrator do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@denistrator could you propose a PR maybe? This is the best way to propose and discuss some changes, there is even no need to report an issue in advance.

**Comment by denistrator** [comment]
@orlangur ok, I'll make a PR with changes from my "solution". The thing is that it's a bug from my point of view and I'm not sure Magento devs think the same way as I do

**Comment by orlangur** [comment]
@denistrator your proposal looks perfectly valid to me, I believe @VladimirZaets is the right person to review your PR.

**Comment by engcom-backlog-nickolas** [comment]
Hello @denistrator, thank you for your report. According to this comment https://github.com/magento/magento2/issues/11098#issuecomment-334392989 described behaviour is correct one.

**Comment by denistrator** [comment]
@vkublytskyi Hi. Is it expected behavior to not be able to override **all** less variables in `_theme.less`?

For example: I want to style my custom component in <Magento_Module> and I don't want to change default styles (styles in `_module.less`). So I create `_extend.less` with styles for my "custom component" and some less variables to control its styles. Now I want to change these variables in child theme but I can't.

I think this case of behavior can be considered as a bug

**Comment by vkublytskyi** [comment]
@denistrator Hi. Yes, it is expected behavior. As described at [DevDocs](https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/css-guide/css_quick_guide_approach.html):
> Extending a theme using _extend.less is the simplest option when you are happy with everything the parent theme has, but want to add more styles.

What probably is missed in DevDocs is that `_extend.less` always have precedence over `_theme.less`. This what needed to be learn and use to achieve desired look and feel. It is how Magento behave. Changing it may break all existing themes. I don't see any serious reason to make such critical backward incompatible change.

**Comment by yuriitaran** [comment]
@vkublytskyi It is how Magento behave? The approach Magento documentation suggests and default Magento behavior are contradict to generally accepted CSS code writing standards. This is very illogical. It results in a bunch of code bad smells. And, instead of recognizing the obvious mistake made in the design of the system, you prefer to say that black is white. "It is how Magento behave".
