### ISSUE TITLE
M2 docs says nothing about where to declare custom less mixins

### ISSUE THREAD

**Issue by denistrator** [magento/magento2#16990]
There is info in [M2 docs](devdocs.magento.com) how to declare custom variables or how to override existing less variables.
For example: custom less variables can be define in theme in `web/css/source/_variables.less`
But where custom less mixing must be declared?

**Comment by magento-engcom-team** [comment]
Hi @denistrator. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@denistrator do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
Issues related to documentation must be reported in [corresponding repo](https://github.com/magento/devdocs).

**Comment by denistrator** [comment]
@orlangur I didn't know about this repo. Thank you
