### ISSUE TITLE
Magento 2 Extension Fund

### ISSUE THREAD

**Issue by kalenjordan** [magento/magento2#1700]
Wanted to post this thread in order to further hash out this idea that we tweeted about earlier today:
https://twitter.com/kalenjordan/status/633711262334078976

So, how much of an incentive would be needed?  I haven't thought this through too much, but $10k feels like a nice round number that might work.  I'd be curious to hear what other extension vendors might say.

Personally, I've been waiting for demand from merchants before I was planning to focus on this - but in an ideal world the extensions would begin to be ready even before merchants are in the ecosystem and beginning to demand things.  It seems like most platform companies eventually develop some kind of fund for exactly this reason.

Then again, maybe no incentive at all is necessary, as many extension vendors may already be incentivized more than enough by the potential for a first mover advantage.

**Comment by kalenjordan** [comment]
Another idea that @dipola had which I thought was awesome would be a free membership to the partner program along with a featured spot in connect in exchange for building an M2 extension.  

That might be worth even more than $10k and it would allow you to strongly incentivize extension developers without even having to inject cash.

**Comment by dipola** [comment]
Cash is king, but in our case, we are all in with Magento, and as part of that commitment, waiving partnership fees or getting a discount for our booth at the next Imagine would mean even more than cash.

**Comment by dfediuk** [comment]
There are two dozens Magento 2 extensions already.
A good list from Firebear Studio: http://firebearstudio.com/blog/the-best-magento-2-extensions.html
My own Magento 2 extension: https://mage2.pro/t/46

**Comment by choukalos** [comment]
Tagging Forum and sharing with our marketing org via email.

**Comment by kalenjordan** [comment]
Thanks @choukalos !

**Comment by krlecarp** [comment]
My 2 cents.  What about having the community fund it through
crowdfunding "spend $10/$50/xx now get $50/$100/xxx later" credit on
the new connect.  Managing and distributing the funds fairly could be
tricky, but if Magento backed and promoted concept it would reduce their
out of pocket for the suggested compensation and it would push M2 exposure,
new connect exposure, and push extension development forward.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by slavvka** [comment]
Hi @kalenjordan. Thank you for your report. 
The issue has been fixed in magento/magento2#29392 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [ebcdce406ee95ad7f6e9fe796846f99999aa2090](https://github.com/magento/magento2/commit/ebcdce406ee95ad7f6e9fe796846f99999aa2090)
 - [2534e462572b68d2f17317247c4caebed72de1bd](https://github.com/magento/magento2/commit/2534e462572b68d2f17317247c4caebed72de1bd)
 - [6c0934415fb249f60649d828089ba1140caba124](https://github.com/magento/magento2/commit/6c0934415fb249f60649d828089ba1140caba124)
 - [6344ad2a0d938c2a0dd964a21ca9a9222dd4a881](https://github.com/magento/magento2/commit/6344ad2a0d938c2a0dd964a21ca9a9222dd4a881)
 - [38562360f5a393ba84ed30c3a2e7140a3ab01e71](https://github.com/magento/magento2/commit/38562360f5a393ba84ed30c3a2e7140a3ab01e71)

The fix will be available with the upcoming 2.4.1 release.
