### ISSUE TITLE
PHP mem error after updating from 2.1.x to 2.2.x

### ISSUE THREAD

**Issue by wedob13** [magento/magento2#17021]
Hello all,
i am trying to update a magento 2.1.x to 2.2.x , 

Unfortunately after i finish the update trying to run any kind of command i get 
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted

The problem is not php confs because whatever the mem size is it seems like a leak, it eats everything.
I tried running upgrade,cache clean, deploy everything gets a php fatal error.

I tried 3 things
Upgrading from 2.1.8 to 2.2.5 
Upgrading from 2.1.8 to 2.2.3 
Upgrading from 2.1.8 to 2.1.9 to 2.2.0 

The problems appears when i pass from 2.1.x to 2.2.x that means when i updated to 2.1.9 from 2.1.8 it was fine, but when i passed onto 2.2.0 i got the error again.

I dont have any more ideas on how to proceed. 

Any thoughts? Thank you!

ps. i get no logged errors or whatsoever

**Comment by magento-engcom-team** [comment]
Hi @wedob13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@wedob13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@wedob13 , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
