### ISSUE TITLE
Admin wrong product category count 

### ISSUE THREAD

**Issue by magento2dev** [magento/magento2#17025]
### Preconditions

1. Use Magento ver. 2.2.3

### Steps to reproduce

1. Go on admin category manage page

### Expected result

1. The number after the category name should reflect the number of product in this category

### Actual result

1. Wrong product number (category has 4 products and it displays 7)

**Comment by magento-engcom-team** [comment]
Hi @anthony-jullien. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@anthony-jullien do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @anthony-jullien, thank you for your report. I cannot reproduce this issue
![peek 2018-07-23 16-42](https://user-images.githubusercontent.com/40755810/43079887-01c031b6-8e97-11e8-9929-70042d5724d2.gif)

Could you please add more details?

**Comment by magento2dev** [comment]
Thanks for your quick reply.
As you can see on screen attached, there is a difference between category count and products in category. I cleared all indexes and caches, I have the issue on two differents installation.

Thanks !

![bug-magento](https://user-images.githubusercontent.com/8010295/43080039-08ff8a10-8e8f-11e8-84f1-e57cfa89c278.png)

**Comment by engcom-backlog-nickolas** [comment]
@anthony-jullien, thanks for feedback. Unfortunately I still not able to reproduce this issue.

![peek 2018-07-23 17-01](https://user-images.githubusercontent.com/40755810/43081014-b5301e3a-8e99-11e8-84e2-bd9344b542de.gif)

**Comment by magento2dev** [comment]
Ok... where Magento gets this value (database table), I will check why the count is wrong ?

Thanks !

**Comment by engcom-backlog-nickolas** [comment]
@anthony-jullien, "catalog_category_ product", but there is no count. There are products assigned to specific category. Base on accounts from this table count is build.

Currently I'm closing this issue, as I wasn't able to reproduce it on clean installation.
If you'd like to update it, please reopen the issue.

Best regards!
