### ISSUE TITLE
Custom widget: included on cms page - vs. layout update // difference? (issue: CMS - no output)

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#17024]
### Preconditions

1. Magento 2.2.5
2. PHP 7.1

### Steps to reproduce

1. Created Custom Widget according to e.g.: https://www.cloudways.com/blog/magento-2-custom-widget/
2. Create new CMS page (Empty Layout)
3. insert widget {{}}

### Expected result

1. See widget output according to widget.phtml

### Actual result

1. no output, no error, nothing.

BUT: if I place the same widget via layout update, by creating a new widget for the main content on any page, the custom module works as expected and I get everything displayed like templated via widget.phtml file.

Where is the difference between using the widget as new widget from widget section or placing it on a content page using the editor? Is this using different templates? I can provide the full source if necessary.

Thank you in advance!

**Comment by magento-engcom-team** [comment]
Hi @lfritsche. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lfritsche do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by lfritsche** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @lfritsche. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @lfritsche, here is your [Magento instance](https://i-17024-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17024-2-2-5.engcom.dev.magento.com/admin](https://i-17024-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-backlog-nickolas** [comment]
Hello @lfritsche, thank you for report. I cannot reproduce this issue.
![peek 2018-07-24 14-29](https://user-images.githubusercontent.com/40755810/43135339-bfd454fa-8f4d-11e8-8891-3a491e2b7836.gif)

If you'd like to update it, please reopen the issue.
