### ISSUE TITLE
when multiple productInterface implement which to use 

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1703]
thank you!

**Comment by vpelipenko** [comment]
@LifeAsBook, what is the issue?

**Comment by LifeAsBook** [comment]
It‘s the question and i see

**Comment by magento-engcom-team** [comment]
Hi @LifeAsBook. Thank you for your report. 
The issue has been fixed in magento/magento2#29400 by @yolouiese in 2.4-develop branch
Related commit(s):
 - [b2b45e679b94cdf526f8a74834246e73c5de185e](https://github.com/magento/magento2/commit/b2b45e679b94cdf526f8a74834246e73c5de185e)
 - [c716884e24b80b8fc48688f5eded7c1910b1835d](https://github.com/magento/magento2/commit/c716884e24b80b8fc48688f5eded7c1910b1835d)
 - [9a2f265aa811710fe05f21907ea8addbc569cd7c](https://github.com/magento/magento2/commit/9a2f265aa811710fe05f21907ea8addbc569cd7c)
 - [8d9d0a5ec0d16701c9fd391ce7c302d747e3d165](https://github.com/magento/magento2/commit/8d9d0a5ec0d16701c9fd391ce7c302d747e3d165)
 - [512942e4a0eb2b356f54b9cd90b8f8a56d1e95dd](https://github.com/magento/magento2/commit/512942e4a0eb2b356f54b9cd90b8f8a56d1e95dd)
 - [7e34bc97092166109f2fbadda8d187a86ca7105e](https://github.com/magento/magento2/commit/7e34bc97092166109f2fbadda8d187a86ca7105e)
 - [0f9189efd2f6b7341c90225d577966f875dbbd83](https://github.com/magento/magento2/commit/0f9189efd2f6b7341c90225d577966f875dbbd83)
 - [c4055cc0e19039506761283e4f93b45775d266c6](https://github.com/magento/magento2/commit/c4055cc0e19039506761283e4f93b45775d266c6)
 - [3b350fd86cfa89a147a736d96e7c59ab2ac40b68](https://github.com/magento/magento2/commit/3b350fd86cfa89a147a736d96e7c59ab2ac40b68)
 - [bf77de0754678b1ed42d7eace0e7af9fb0876102](https://github.com/magento/magento2/commit/bf77de0754678b1ed42d7eace0e7af9fb0876102)
 - [5f1d43a80d6dadbe5b2442c873de94f582f1ea7f](https://github.com/magento/magento2/commit/5f1d43a80d6dadbe5b2442c873de94f582f1ea7f)

The fix will be available with the upcoming 2.4.1 release.
