### ISSUE TITLE
Layered Navigation no longer visible when using Static block only

### ISSUE THREAD

**Issue by DigitalStartupUK** [magento/magento2#17038]
### Preconditions

1. Magento 2.2.5
2. Sample data installed

### Steps to reproduce

1. Set `Display Mode` to `Static block only` on parent directory (Men)
2. Set `Anchor` to `Yes`
3. Remove `<referenceContainer name="catalog.leftnav" remove="true"/>` from `Layout Update XML`

### Expected result

1. Layered Navigation (Shopping Options) should be visible

![2 2 2](https://user-images.githubusercontent.com/24552648/43089878-bd8715d0-8e9d-11e8-801c-51164229ac0d.png)

### Actual result

1. Layered Navigation (Shopping Options) not visible

![2 2 5](https://user-images.githubusercontent.com/24552648/43089885-c1026660-8e9d-11e8-9c75-99b968509a36.png)

Note, that the Layered Navigation in a Parent Category always took into account the child categories. This was the case for M1 through to M2.2.2. I'm not sure which version this issue was introduced, but it's definitely present in 2.2.5. I've only used Luma with Sample Data for the purpose of this issue. However, it can easily be reproduced with your own categories in another theme.

**Comment by magento-engcom-team** [comment]
Hi @DigitalStartupUK. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@DigitalStartupUK do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DigitalStartupUK** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @DigitalStartupUK. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @DigitalStartupUK, here is your [Magento instance](https://i-17038-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17038-2-2-5.engcom.dev.magento.com/admin](https://i-17038-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Karlasa** [comment]
@DigitalStartupUK  it works as expected. If it´s configured to show static block only then after clicking on filter ( even if it would show) it still should show only static block because its configured that way. It was showing on older versions because of bug see more at https://github.com/magento/magento2/issues/7765

**Comment by DigitalStartupUK** [comment]
@Karlasa I considered this a feature carried over from M1. Allowing a Static Block to be displayed in the Main Content area whilst still allowing customers to narrow down their products (in the children categories) via the filter from the sidebar.

I guess to reverse this, I'd just need to override the files in the aforementioned commit? I'll have to look into this in the morning.

**Comment by ghost** [comment]
@DigitalStartupUK, thank you for your report.
This is not a bug, as your "Expected result" was previously considered as a bug.
