### ISSUE TITLE
Toolbar and Pagination not showing on Catalog Search Page and Brand Wise Search Page  Magento 2

### ISSUE THREAD

**Issue by shaikhmasud147** [magento/magento2#17031]
Summary
Toolbar and Pagination not showing on Catalog Search Page and Brand Wise Search Page  Magento 2

Preconditions
Magento 2.0.17 CE with sample data
PHP 7.0.30

Steps to reproduce
When I search any item under catalog search Tool Bar not showing and Brand wise product search pagination not showing.

But both functionality is working on my local server.

![american fyre designs](https://user-images.githubusercontent.com/21688214/43083615-8d0d1b4a-8eb4-11e8-891c-bb9f158c49fd.png)
![american fyre designs 2](https://user-images.githubusercontent.com/21688214/43083616-8d46906e-8eb4-11e8-84de-230db0e5b080.png)

Expected Result
Toolbar and Pagination display any search product under catalog page.

Actual Result
Toolbar and Pagination not showing.

**Comment by magento-engcom-team** [comment]
Hi @shaikhmasud147. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@shaikhmasud147 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@shaikhmasud147, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by shaikhmasud147** [comment]
Ok, Thanks!
