### ISSUE TITLE
Magento 2 | cannot load any grid in Backend 

### ISSUE THREAD

**Issue by yasminelsayed** [magento/magento2#17065]
Suddenly I got issue in loading grid content in backend ( pages / blocks / products ). i need help I cannot access or make any update here 
![image](https://user-images.githubusercontent.com/20180767/43137862-5d0423aa-8f4d-11e8-91e5-6bd1467e58d3.png)

**Comment by magento-engcom-team** [comment]
Hi @yasminelsayed. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@yasminelsayed do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@yasminelsayed, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only. Your issue is caused by some custom modules.
