### ISSUE TITLE
WHILE DOING POST DATA RESPONSE BACK AS Content-Type header is empty

### ISSUE THREAD

**Issue by NSDEEPAKRSHETTY** [magento/magento2#17064]
I am netsuite technical developer, we have integrated netsuite with magento 1.9 server
whenever the data of inventory products are posted in JSON type . Even though we included content-type as application/json then also magento 1.9 srver gives response error of message as Content-Type header is empty 
### Actual result
![post1](https://user-images.githubusercontent.com/41626070/43134452-bd921152-8f5f-11e8-947f-fd9a347ef338.png)
![post2](https://user-images.githubusercontent.com/41626070/43134461-c3586db6-8f5f-11e8-8821-f872bdf6c29c.png)
![post3](https://user-images.githubusercontent.com/41626070/43134468-c79fbe56-8f5f-11e8-845e-47094904e349.png)

**Comment by magento-engcom-team** [comment]
Hi @NSDEEPAKSHETTY. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@NSDEEPAKSHETTY do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@NSDEEPAKSHETTY, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for **Magento 2** technical issues only.
