### ISSUE TITLE
[L300:C4] Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by 201rep** [magento/magento2#17075]
Running "less:theme" (less) task
>> pub/static/frontend/Magento/theme/en_US/css/source/lib/_utilities.less: [L300:C4] Cannot read property 'substring' of undefined
Warning: Error compiling pub/static/frontend/Magento/theme/en_US/css/styles-m.less Use --force to continue.

Aborted due to warnings.

Execution Time (2018-07-24 17:35:39 UTC+3)
loading tasks               403ms  ▇▇▇▇▇▇▇▇▇▇▇ 7%
loading grunt-contrib-less  126ms  ▇▇▇▇ 2%
less:theme                5.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 91%
Total 6s

### Preconditions

1.  Magento ver. 2.2.5
2.  php with Zend OPcache v7.0.30-1+ubuntu16.04.1+deb.sury.org+1,
3.  mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
4.  node v8.9.4

### Steps to reproduce

1. Downloaded Magento
2. Installed Magento
3. Started work with Magento
3. Started task - grunt less:theme 
2. Get an error

### Expected result
Task is working.

**Comment by magento-engcom-team** [comment]
Hi @201rep. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@201rep do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by 201rep** [comment]
no

**Comment by ghost** [comment]
@201rep, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by 201rep** [comment]
@engcom-backlog-pb thank you for your report.
I'm not able to understand why the dachshund does not work out of the box.

**Comment by ghost** [comment]
@201rep, seems like your issue is caused by some custom code. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
