### ISSUE TITLE
DB issue after upgrade to 2.2.5

### ISSUE THREAD

**Issue by terrybakshi** [magento/magento2#17074]
### Preconditions

1. Magento 2.2.5
2. PHP 7.1
3. MySql 5.6

### Steps to reproduce

1. Upgraded magento 2.2.3 to magento 2.2.5
2. went to sales order and go an error 
3. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'toydeals_mg221.sales_order_grid' doesn't exist, query was: SELECT COUNT(*) FROM `sales_order_grid` AS `main_table`

### Expected result

1. Orders should open

### Actual result

![screenshot 58](https://user-images.githubusercontent.com/13229022/43148879-8725344c-8fa9-11e8-8a06-6f15785cb326.png)

**Comment by magento-engcom-team** [comment]
Hi @terrybakshi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@terrybakshi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-17074-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17074-2-2-3.engcom.dev.magento.com/admin](https://i-17074-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@terrybakshi, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![1](https://user-images.githubusercontent.com/40756187/43191583-1a90465e-9004-11e8-99a3-0583c9e838e4.gif)

**Comment by DanielRuf** [comment]
> @DanielRuf, thank you for your report.

It was not me, it was @terrybakshi.

**Comment by ghost** [comment]
@DanielRuf, of course, sorry.
