### ISSUE TITLE
Product page not reachable after status update

### ISSUE THREAD

**Issue by magento2dev** [magento/magento2#17082]
### Preconditions

1. Use Magento ver. 2.2.3 (tested on a fresh install)

### Steps to reproduce

1. Go on admin product edit page
2. Disable product
3. Load frontend product page (returns a normal 404)
4. Go back on admin product edit page
3. Enable product

### Expected result

1. The product should be reachable again after being enable again

### Actual result

1. The product page stills be a 404

**Comment by magento-engcom-team** [comment]
Hi @anthony-jullien. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@anthony-jullien do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@anthony-jullien, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![1](https://user-images.githubusercontent.com/40756187/43188331-8874e2a4-8ffc-11e8-8fb3-dd9f51aac8f7.gif)
