### ISSUE TITLE
Dashboard (seller and buyer)

### ISSUE THREAD

**Issue by sithibodeau** [magento/magento2#17081]
We have three types of users on our :
Seller (no buyer dashboard)
Seller and Buyer (dual dashboard)
Buyer (no seller dashboard)

When a seller is logged in and the configurations are set to "seperate dashboard" the seller still has access to the buyer dashboard. 

how do we control what they see? do we have to submit or create three views of the storefront? buyer, seller and a hybrid?

**Comment by magento-engcom-team** [comment]
Hi @sithibodeau. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sithibodeau do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sithibodeau** [comment]
no

**Comment by ghost** [comment]
@sithibodeau, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
