### ISSUE TITLE
Improve Manual Mode indexing

### ISSUE THREAD

**Issue by colinmollenhour** [magento/magento2#171]
One of my dreams is for Magento to be able to:
1. Perform the heavy lifting of indexes in the background in near-real-time by using a separate daemon of sorts that uses a pub/sub method (e.g. Redis) to wake up the indexer instantly.
2. Clear the related cache tags only after the reindexing is complete. (otherwise the cache may be rewarmed before the reindexing is complete).
3. Not have potential issues with process statuses. Currently I think it would be possible for the status to end up as "pending" even though new events were added while some events were being processed. That is, the status should not be changed to "pending" if new events were added in the meantime (e.g.: prevent update if updated_at time changed)

**Comment by magento-engcom-team** [comment]
Hi @colinmollenhour. Thank you for your report. 
The issue has been fixed in magento/magento2#27597 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [ca0e3a1b655fa0356e69d65bd163196562c72f14](https://github.com/magento/magento2/commit/ca0e3a1b655fa0356e69d65bd163196562c72f14)
 - [1e226ffa0e382c73560eea23223d0c6a8e4d6f72](https://github.com/magento/magento2/commit/1e226ffa0e382c73560eea23223d0c6a8e4d6f72)

The fix will be available with the upcoming 2.4.0 release.
