### ISSUE TITLE
"Multiple Select"  product attributes do not render HTML tags on the storefront view

### ISSUE THREAD

**Issue by kedarjoyner** [magento/magento2#17100]
### Preconditions

1. Fresh install of Magento version 2.2.3 
2. PHP version 7.1.1
3. MySQL version 5.6.35

### Steps to reproduce

1. Navigate to Stores > Product under the `Attributes` header.

2. Set `Catalog Input Type for Store Owner` to `Multiple Select`. Make sure product attribute values include html tags. You must add at least two attribute values. Example below:
<img width="997" alt="screen shot 2018-07-24 at 1 57 22 pm" src="https://user-images.githubusercontent.com/12139428/43160041-a4a744fc-8f49-11e8-9473-0836ead7bd7d.png">

3. Navigate to `Storefront Properties`. The following two properties must be set to `Yes`. 
<img width="849" alt="screen shot 2018-07-24 at 2 01 06 pm" src="https://user-images.githubusercontent.com/12139428/43160190-1b23c81c-8f4a-11e8-894e-9e56f08f1154.png">

4. Navigate to Stores > Attribute Set under the `Attributes` header.

5. Select "Default"

6. Add your newly created Product Attribute under `Product Details`. You can see my attribute of `support` under this group below: 
<img width="1243" alt="screen shot 2018-07-24 at 2 03 37 pm" src="https://user-images.githubusercontent.com/12139428/43160420-b8117174-8f4a-11e8-941f-1e49c13089fd.png">

7. Navigate to Catalog > Products and create a new product

8. Select both of your product attributes: 
<img width="682" alt="screen shot 2018-07-24 at 2 09 43 pm" src="https://user-images.githubusercontent.com/12139428/43160609-411610a6-8f4b-11e8-9a57-abfe0c0c3f5d.png">

9. Navigate to the product page within your browser. Your product attributes will be viewable under the `More Information` tab: 
<img width="1335" alt="screen shot 2018-07-24 at 2 10 35 pm" src="https://user-images.githubusercontent.com/12139428/43160669-6e79ea68-8f4b-11e8-9a38-6ea8bc20dc33.png">

### Expected result

1. The expected output would be rendered html tags. If a product attribute value is wrapped in an <a> tag, the editor would expect to see that element as a link.
2. The editor expects to see this because they have selected `Yes` under the `Allow HTML tags in the storefront` within the created Product Attribute (see above screenshot for reference)

### Actual result

1. Html tags are rendered as plain text
<img width="1335" alt="screen shot 2018-07-24 at 2 10 35 pm" src="https://user-images.githubusercontent.com/12139428/43160811-db4b8d40-8f4b-11e8-8967-04b29ad23dac.png">

**Comment by magento-engcom-team** [comment]
Hi @kedarjoyner. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@kedarjoyner do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Karlasa** [comment]
Seems like duplicate of https://github.com/magento/magento2/issues/15393 
fix for it in PR #15687

**Comment by kedarjoyner** [comment]
@Karlasa You are correct - sorry. I tried searching keywords for this particular issue, but no related results appeared. I will recommend to the creator of #15393 to make the title more specific so others can more easily find it.

**Comment by ghost** [comment]
@kedarjoyner, closing as duplicate of #15393.
