### ISSUE TITLE
Catalog prices always showing excluding tax.

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#17113]
Magento 2.2.5 is displaying product prices in the catalog as excluding tax regardless of what is set in the tax configuration settings. I have attached a screenshot of the Display Product Prices in Catalog setting set to 'Including and Excluding Tax' to better demonstrate this issue.

### Preconditions

1. Magento 2.2.5
2. Blank Theme

### Steps to reproduce

1. Set Tax -> Calculation Settings -> Catalog Prices to 'Including Tax'
2. Set Tax -> Price Display Setting -> Display Product Prices in Catalog to 'Including Tax'
3. Set Tax -> Shopping Cart Display Settings -> Display Prices to 'Including Tax'

### Expected result

1. Load Product Page and check price.
2. Load Cart Page and check price.
3. Both prices should match the price for the product entered in the backend.

### Actual result

1. Product Price on the cart page is shown including Tax.
2. Product Price on the product page is shown excluding tax, regardless of configuration setting.

**Product Page:**
![screenshot_2018-07-25 cavesson bridle](https://user-images.githubusercontent.com/33320744/43191132-73a604ac-8ff2-11e8-9c3d-74f493cdbf88.png)

**Cart Page:**
![screenshot_2018-07-25 shopping cart](https://user-images.githubusercontent.com/33320744/43191149-7b8b8a5c-8ff2-11e8-98e8-dda1e0fa275d.png)

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@BezV8 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by BezV8** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @BezV8, here is your [Magento instance](https://i-17113-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17113-2-2-5.engcom.dev.magento.com/admin](https://i-17113-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by BezV8** [comment]
@magento-engcom-team Issue confirmed on vanilla Magento instance.

**Comment by hostep** [comment]
@BezV8: just quickly ran through the configuration of this test instance (I didn't change anything), but I noticed that Stores > Configuration > Sales > Tax > Default Tax Destination Calculation > Default Country is still set to USA instead of UK (which you set up in various other places as the default country). It's possible that by changing that setting to UK your issue gets resolved. Any chance you could give that a try?

**Comment by BezV8** [comment]
@hostep Good catch! That seems to have sorted it on the test instance, though the Price on the Cart seems to be displaying incorrectly now. I have checked on my actual site and Default Tax Destination Calculation was still set to US. I really should have checked that, but it looks like the setting was reverted when I had to roll back a git commit.

I am closing this issue now as it was user error on my part. Thanks for spotting that so quickly.
