### ISSUE TITLE
Issue : Upgrade Magento 2.1.9 to 2.2.5 : Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "{PRODUCTID}" already exists.

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#17119]
### Preconditions
We are getting issues on category page after upgrade magento 2.1.9 to 2.2.5

1. Magento 2.2.5 (before upgrade it was 2.1.9)
    1.1 Magento Developer mode Enabled
2. PHP 7.0
3. Multi website with 2 stores

### Steps to reproduce

1. upgrade 2.1.9 to 2.2.5
2. Run setup upgrade command
3. Run Deploy command

### Expected result

1. Category page should working fine.

### Actual result

1. Category page showing blank page when production mode enable.
2. When we enabled Developer mode following errors are showing on category page.
```

1 exception(s):
Exception #0 (Exception): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "17171" already exists.

Exception #0 (Exception): Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "17171" already exists.
```

**Comment by magento-engcom-team** [comment]
Hi @aasim110. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@aasim110 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by aasim110** [comment]
@magento-engcom-team  I don't know how to reproduce the issue on vanilla Magento instance.

**Comment by engcom-backlog-nickolas** [comment]
Hello @aasim110. thank you for your report. Unfortunately I cannot reproduce this issue.
![peek 2018-07-26 14-32](https://user-images.githubusercontent.com/40755810/43260306-b602ee60-90e1-11e8-836b-9f27b4568c6b.gif)


If you'd like to update it, please reopen the issue.

**Comment by aasim110** [comment]
@magento-engcom-team @engcom-backlog-nickolas Issue happens in parent category only, in sub categories seems working fine. 

Also we have deleted 8 stores before upgrade as we had 10 stores before, so currently there are two stores only
