### ISSUE TITLE
Ui Bookmark field created_at and updated_at fields always shows '0000-00-00 00:00:00'

### ISSUE THREAD

**Issue by kunj1988** [magento/magento2#17120]
### Preconditions

1. Magento 2.2.1
2. Magento 2.2.4
3. Magento 2.2.5

### Steps to reproduce

1. check `ui_bookmark` table you will see `created_at` and `updated_at` fields value is '0000-00-00 00:00:00' for all grids. 

### Expected result

1.There would time `timestamp [CURRENT_TIMESTAMP]` or magento should save date time while add or update data. 

### Actual result

1. Magento 2.2.4 `ui_bookmark` Table ![magento2 2 4_ui_bookmark](https://user-images.githubusercontent.com/13017040/43198637-011e03ae-902d-11e8-9d7b-1a0eb2d45c43.png)
2. Magento 2.2.4 `ui_bookmark` Table ![magento2 2 5_ui_bookmark png](https://user-images.githubusercontent.com/13017040/43198752-5c6998ae-902d-11e8-83a5-0a2cc29fe7ae.png)
3. Magento 2.2.4 `ui_bookmark` Table ![magento2 2 1_ui_bookmark](https://user-images.githubusercontent.com/13017040/43198833-967c6116-902d-11e8-8513-bd9167f328ee.png)

**Comment by magento-engcom-team** [comment]
Hi @kunj1988. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@kunj1988 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@kunj1988, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by orlangur** [comment]
Duplicate of https://github.com/magento/magento2/issues/18557
