### ISSUE TITLE
 PHP Fatal error:  Uncaught Error: Call to a member function getExtOrderId() on null 

### ISSUE THREAD

**Issue by vinothinik2010** [magento/magento2#17131]
We migrated a data from Magento1 (version 1.8.0.0) to Magento2 (version 2.2.5). After moving to server, We couldn't able to open the order view in admin side. It shows the error like " Order View
 Information Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving. " ( Please refer the attached screen shot). But it is working fine in local. 

server catching the message in error.log is "  *7793 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getExtOrderId() on null in /var/www/html/vendor/temando/module-shipping-m2/view/adminhtml/templates/sales/order/view/info.phtml:134"

Instead of this info.phtml file , moved info.phtml from magento 2.2.4 version , it is working in both server and local. 

In Magento 2.2.5, $extOrderId  is getting like  $extOrderId = $orderDetailsViewModel->getExtOrderId($order); 

In Magento 2.2.4, $extOrderId  is getting like $extOrderId = $block->getExtOrderId()

### Preconditions

1. PHP 7.1.18
2. nginx 
3. Magento 2.2.5

### Steps to reproduce

Admin -> Sales -> orders -> click 'view' from any one of the order from order grid

### Expected result

![screenshot from 2018-07-25 20-10-35](https://user-images.githubusercontent.com/25581010/43207960-e19e0ec4-9046-11e8-8faf-345121a1cee5.png)

### Actual result

![screenshot from 2018-07-25 20-01-20](https://user-images.githubusercontent.com/25581010/43207903-bccd28d2-9046-11e8-9bec-a27d68da7633.png)

**Comment by magento-engcom-team** [comment]
Hi @vinothinik2010. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vinothinik2010 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by artiglobal** [comment]
How to fix ?  Uncaught Error: Call to a member function getExtOrderId() on null

**Comment by markalston** [comment]
I was getting the same error.  Disabling the bundled extension Temando_Shipping fixed the issue for me.

`
 ./bin/magento module:disable Temando_Shipping
`

**Comment by rogyar** [comment]
```
 Uncaught Error: Call to a member function getExtOrderId() on null in /var/www/html/vendor/temando/module-shipping-m2/view/adminhtml/templates/sales/order/view/info.phtml:134"
```
According to the trace above, the issue is related to the Temando_Shipping module. Contact the extension vendor support in order to resolve this issue.

**Comment by okorshenko** [comment]
Hi @vinothinik2010 
Thank you for your report. Unfortunately, we can't resolve this issue in magento2 repository. The issue you mentioned is caused by vendor extension. Please contact vendor support team for the assistance:
https://developer.temando.com/soap/index.html or email them tsupport@temando.com

Thank you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.
