### ISSUE TITLE
Fotorama not working

### ISSUE THREAD

**Issue by tartreau** [magento/magento2#17132]
Hi, my product image is not showing on its page (but on catalog it's working).

The image is indeed on the page (I can see it from the dev tools),but not on frontend directly.

 the only I found to make this work is by adding a width 100% to all children

 

See in less :
 

```
.product{
  &.media{
    div{
      width:100%;
    }
  }
}
```

@magento-engcom-team give me {2.2.4} instance

**Comment by magento-engcom-team** [comment]
Hi @tartreau. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@tartreau do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@tartreau, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
