### ISSUE TITLE
'$_FILES array is empty' in IE11 with uicomponent file field in admin

### ISSUE THREAD

**Issue by magiumcommerce** [magento/magento2#17166]
### Summary

Using field with a "file" input type in a custom admin page ui component form results in a '$_FILES array is empty'  error in Internet Explorer 11. This works fine in Chrome (latest version on both linux and windows)

### Preconditions
1. Magento 2.2.4
2. PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
3. nginx/1.10.3 (Ubuntu)
4. IE11 (11.165.17134.0)

### Steps to reproduce
1. Create custom module that adds a page to the admin section
2. For the custom page, add a ui component form that uses the field  component with a formElement type of "file" as per the following snippet:

```
<fieldset name="csv_file">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="label" xsi:type="string" translate="true"/>
            </item>
        </argument>
        <field name="import">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="label" xsi:type="string" translate="true">CSV File</item>
                    <item name="formElement" xsi:type="string">file</item>
                </item>
            </argument>
        </field>
    </fieldset>

```
3. Navigate to the custom page in admin, choose a CSV file and submit the form

### Expected result
1. $_FILES array on page post is populated with the details of the file that was chosen in the form

### Actual result
1. $_FILES array is empty

Note: we used \Magento\Framework\File\Uploader and it throws the '$_FILES array is empty' exception in IE11, but not Chrome.

**Comment by magento-engcom-team** [comment]
Hi @magiumcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@magiumcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @magiumcommerce thank you for you report, did you try to this fieldset ->  
```
<fieldset name="Import">
    <argument name="data" xsi:type="array">
    <item name="config" xsi:type="array">
        <item name="collapsible" xsi:type="boolean">false</item>
        <item name="label" xsi:type="string" translate="true">Import</item>
    </item>
    </argument>
    <field name="import">
    <argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="label" xsi:type="string">Import</item>
            <item name="visible" xsi:type="boolean">true</item>
            <item name="formElement" xsi:type="string">fileUploader</item>
            <item name="uploaderConfig" xsi:type="array">
                <item name="url" xsi:type="url" path="path/to/controller"/>
            </item>
        </item>
    </argument>
    </field>
</fieldset>
```

**Comment by ghost** [comment]
@magiumcommerce Unfortunately, I'm not able to reproduce this issue. 
Also, it's not the best practice to use FileUploader component  in Magento 2. Please refer to ->
https://devdocs.magento.com/guides/v2.1/ui_comp_guide/components/ui-fileuploader.html 
If you'd like to update this issue, feel free to reopen it.
