### ISSUE TITLE
Export subscriber to CSV

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#17171]
Hello,

i get the following error, if i want to export the subscriber in Magento 2.2.5.
Afert i clicking of all 5700 subscripers to export, i get the error of the System 

Forbidden
You do not have permission to access this document.

In the error_logs of the system is these written:

[Thu Jul 26 17:26:30.693942 2018] [core:error] [pid 31391] (36)File name too long: [client XXXXX:59618] AH00127: Cannot map GET /admin/newsletter/subscriber/exportXml/key/15be55a152156821dd57cd6752ca44a7eabd423f8f91fbd9cba59941d897d461/limit/200/internal_subscriber/6053,6052,6051,6050,6049,6048,6047,6046,6045,6044,6,....

[Thu Jul 26 17:17:14.483610 2018] [core:error] [pid 30201] (36)File name too long: [client XXXXX:48388] AH00127: Cannot map GET /admin/newsletter/subscriber/exportCsv/key/7b2047a9dae0ab43629c649b3fa696fd2942fbd2aa1321372e63b22828efbbb3/limit/200/internal_subscriber/6053,6052,6051,6050,6049,6048,6047,.......

Where is the problem?

kind regards
Olek

**Comment by magento-engcom-team** [comment]
Hi @Olek89. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Olek89 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Olek89** [comment]
Hello, i dont now, if it is on the vanilla magento version.
the issue is coming up after upgrading to 2.2.5.
I think it could also a server problem, but i dont now.

**Comment by ghost** [comment]
@Olek89, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by abcpremium** [comment]
Same for me, also the URL is too long if I select more than 400 Subscribers (URL length exceeds 2000)

**Comment by onlinebizsoft** [comment]
This is a real bug because the it adds all IDs to the URL and the URL length exceeds the limit
