### ISSUE TITLE
Existing updates grid is not showing

### ISSUE THREAD

**Issue by abbasalibutt** [magento/magento2#17180]
Hello,

I am using Magento Enterprise 2.2.2

Steps:
In admin panel Catalog -> Categories -> Select any Category -> Schedule New Updates -> Assign to Existing Update

### Expected result
1. It should show the already existed all other updates in the grid

### Actual result
Showing nothing. 

Note: I have disabled all 3rd party and custom modules but still showing nothing.

**Comment by magento-engcom-team** [comment]
Hi @abbasalibutt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@abbasalibutt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@abbasalibutt, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
