### ISSUE TITLE
ObjectManager Exception in Magento\Backend\Block\Media\Uploader

### ISSUE THREAD

**Issue by robin-homberg** [magento/magento2#17185]
### Preconditions
1. Magento Version 2.3.0-alpha56 or 2.3-develop on commit f01227c554448797077e4f752315204e594b91f2
2. PHPUnit Version 7.2.7
3. Unit-Test for some class that extends `Magento\Backend\Block\Media\Uploader`
( https://github.com/Flagbit/Magento2-Flysystem/blob/develop/Test/Unit/Block/Adminhtml/Filesystem/Content/UploaderTest.php )

### Steps to reproduce
1. Run the unit tests
2. See the results

### Expected result
1. It is exepcted that there wo'nt be an exception inside a core class. While the tests worked correct on different Magento 2.2.x versions.

### Actual result
1. An Exception inside a core class is thrown:
```
RuntimeException : ObjectManager isn't initialized
 /home/robin_homberg/PhpstormProjects/magento2-testsystem/src/vendor/magento/framework/App/ObjectManager.php:35
 /home/robin_homberg/PhpstormProjects/magento2-testsystem/src/vendor/magento/module-backend/Block/Media/Uploader.php:51
 /home/robin_homberg/PhpstormProjects/magento2-testsystem/src/app/code/Flagbit/Flysystem/Block/Adminhtml/Filesystem/Content/Uploader.php:25
 /home/robin_homberg/PhpstormProjects/magento2-testsystem/src/app/code/Flagbit/Flysystem/Test/Unit/Block/Adminhtml/Filesystem/Content/UploaderTest.php:141
```

**Comment by magento-engcom-team** [comment]
Hi @robin-homberg. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@robin-homberg do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @robin-homberg, thank you for your report. Unfortunately, I'm not able to reproduce this issue.
![peek 2018-07-27 14-50](https://user-images.githubusercontent.com/40755810/43319214-8b3b5b06-91ac-11e8-8ad0-4303856b64a3.gif)

Also, it's not the best practice to use inheritance in Magento 2. Please refer to https://devdocs.magento.com/guides/v2.3/ext-best-practices/extension-coding/common-programming-bp.html#composition-over-inheritance

If you'd like to update this issue, feel free to reopen it.
