### ISSUE TITLE
Grid filter does not work with value `0`

### ISSUE THREAD

**Issue by evolbug** [magento/magento2#17187]
### Preconditions

1. Magento 2.1.8/2.1.10/2.2.0

### Steps to reproduce

1. Go to any grid in admin panel
2. Insert `0` in any filter
3. Apply filter

### Expected result

1. Grid is filtered with value `0`

### Actual result

1. All items are returned with no filtering

**Comment by magento-engcom-team** [comment]
Hi @evolbug. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@evolbug do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by evolbug** [comment]
@magento-engcom-team give me 2.2.0 instance

**Comment by magento-engcom-team** [comment]
Hi @evolbug. Thank you for your request. I'm working on Magento 2.2.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @evolbug, here is your [Magento instance](https://i-17187-2-2-0.engcom.dev.magento.com).
Admin access: [https://i-17187-2-2-0.engcom.dev.magento.com/admin](https://i-17187-2-2-0.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by evolbug** [comment]
@magento-engcom-team confirmed

**Comment by ghost** [comment]
@evolbug, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jignesh-baldha** [comment]
@evolbug I've fixed this issue and created PR.

**Comment by evolbug** [comment]
Fixed in #17305
