### ISSUE TITLE
REST API Category translation

### ISSUE THREAD

**Issue by magento2dev** [magento/magento2#17186]
### Additional information

test case steps description : https://github.com/magento/magento2/issues/17186#issuecomment-528501666

### Preconditions

1. Magento 2.2.3 & 2.3.x

### Steps to reproduce

1. Send REST PUT request to translate category name in specific store view : {{BaseURL}}rest/{{codeStoreView}}/V1/categories/{id}

`{
	"saveOptions": true,
	"category": {
		"id": 3,
		"name": "New Category Name Translated"
	}
}`

### Expected result

1. It should only update the category name field and create only one row in database for the specific store view

### Actual result

1. The request uncheck Enable Category, Include in Menu, Category Image, etc... attributes and create multiple rows in database for the specific store view

**Comment by magento-engcom-team** [comment]
Hi @anthony-jullien. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@anthony-jullien do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@anthony-jullien, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento2dev** [comment]
Thanks, do you have an official ticket to follow this important issue ? and do you know when a patch will be developed because we have the same issue on products.

Thanks !

**Comment by ghost** [comment]
@anthony-jullien currently, we are not creating internal tickets, as we want to involve our community members in developing of Magento 2. Anyone can assign an issue on this tracker and submit pull-request with a proper fix.

**Comment by magento2dev** [comment]
I don't understand a lot of people have this issue (#9186) and nobody is finding a solution for this major issue, you can't create an internal ticket for helping the community ?

**Comment by hostep** [comment]
**Update: ignore this post, this isn't fixing the reported issue**

Hi @anthony-jullien: we've recently received a patch from the Magento Cloud support with a fix for this issue. Unfortunately I haven't found the time yet to test it and I can't post the patch here, since it contains code used in certain modules of the Magento Enterprise Edition.

But, I can see that Magento already committed parts of the patch we received here on github, it just hasn't been released yet in a release.
Here are the commits I can find which seem to reflect the same changes as I can find in the patch they send us:

- MAGETWO-87589: [Magento Cloud] - Issue with polluted database when updating product attributes through API: https://github.com/magento/magento2/commit/0383b227f3910378da1e79aa57d84b8e6708ca1d
- MAGETWO-73638: Product "Use Default Value" checkbox for an attributes are unchecked for the new website scope: https://github.com/magento/magento2/commit/a00199395d111e1effd80561bf54e50ed4d845d8 & https://github.com/magento/magento2/commit/c30b2953d16f64a144cef66a8d10c4edccfac74f
- MAGETWO-90768: 'Use Default Value' checkboxes in Design section of a category are not checked by default: https://github.com/magento/magento2/commit/6949623c730c8ee6b76af33947c98435bf358e57

Maybe you can first test on a new installation cloned from github from the latest `2.2-develop` branch and see if the issue has been resolved. And if that is the case, then try to create a patch with the above commits, and attempt to get it working that way on your current version. Hopefully I didn't miss any commits in my list above...

Hope this helps!

**Comment by magento2dev** [comment]
Hi @hostep,

Thanks a lot for your reply !
Sadly these tickets refers to the product issue, I'm trying to solve the same issue on the category edit page. It would be great if you could post the patch here after removing the Magento Enterprise Edition part.

Thanks for your help !

**Comment by hostep** [comment]
**Update: ignore this post, this isn't fixing the reported issue**

Indeed, it's for products, but some of the code also applies to categories, so who knows ...

Anyway, here is the patch we got, stripped out the changes from the RMA module (EE only), was created for Magento 2.2.2, and I've not tested it yet, hope this helps.

[MDVA-8506_EE_2.2.2_v2_COMPOSER.txt](https://github.com/magento/magento2/files/2238887/MDVA-8506_EE_2.2.2_v2_COMPOSER.txt)

**Comment by magento2dev** [comment]
Thanks a lot @hostep for your responsiveness, I tried this afternoon the fourth commit you mentioned above and sadly none of them is fixing this issue, it does not fixing the issue concerning the product store duplication (when you set a product available in a new website all use default value checkboxes are unchecked at store level).

I just tried your patch but it's the same as a001993, it does not solve the issue. I don't understand why Magento (@magento-engcom-team) does not provide any fix, it's a major issue, we lost all the advantages of the Magento store view.

Thanks for your help !

**Comment by hostep** [comment]
Hi @anthony-jullien: I did a little testing on the latest `2.2-develop` branch this time and indeed, the API part is not fixed, even not for products.
The only thing which seems to be fixed by the above commits, is the fact that the `Use Default Value` checkboxes stay checked and don't cause extra rows being inserted in the database when saving a category/product on a storeview level when you leave all accordions closed in the backend of Magento.
So these ones are probably fixed in 2.2-develop: https://github.com/magento/magento2/issues/13665 & https://github.com/magento/magento2/issues/9486, but the issue you reported (same as https://github.com/magento/magento2/issues/9186) is not fixed.

Great, I explicitly asked the Cloud support if the API part was fixed by that patch, since by just reading the code, I couldn't see much changed in the code related to the API and they kept confirming it was fixed. But yeah, I should have actually tried testing myself earlier. I wonder why we (=our client) wants to keep paying for the enterprise support when they act like that...

**Comment by magento2dev** [comment]
Thanks for your help ! @hostep 
Yes the patch solve the product issue but I don't think we have this one on Magento 2.2.3. I report my issue because they keep closing this issue even if it's not fixed (like #9186)...

Exactly I don't understand why they keep saying it's fixed as it's definitely not... I totally agree it's becoming very difficult to use to community edition. I'm working with a lot of Magento developers and many are thinking to migrate to another CMS, there are too many bugs in Magento 2.2 (more than one year after it's released) and @magento-engcom-team don't even take the time to fix the major issues...

**Comment by kolonuk** [comment]
@kolonuk - monitoring

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by frostblogNet** [comment]
This issue is gone with magento 2.3.2. The issue can be closed. @magento-engcom-team

**Comment by hostep** [comment]
@frostblogNet: I can still reproduce this on Magento 2.3.2

Steps:
1. Setup vanilla 2.3.2
2. Create a single category with name 'Category' (in my case it had ID 3)
3. Create an integration with permissions to update categories, activate it and store the authorization key: `abcd` (as an example)
4. Execute:
```
$ curl -k -X PUT "https://example.com/rest/default/V1/categories/3" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer abcd" -d "{ \"category\": { \"id\": 3, \"name\": \"New Cat Name\" }}"
```

(*Update short after first test*: just in case it mattered, I tested this again with that `"saveOptions": true,` flag in the data, and the bug still occurs (no idea what that flag is doing btw, can't find documentation around it))

Expected:
- To only see the category name updated on the store view level
- To only find one new row in the database on the store view level

Actual:
- Finding multiple new rows in the database on the store view level
- Seeing a whole bunch of unchecked `Use Default Value` checkboxes on the store view level:

<img width="1113" alt="Screenshot 2019-09-05 at 19 54 20" src="https://user-images.githubusercontent.com/85479/64366716-15cb9700-d017-11e9-8ea2-ecf25e75d66c.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19908` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento2dev @hostep 

The related/duplicate issue has been fixed and delivered https://github.com/magento/magento2/issues/30047#issuecomment-715498108

It seems we can close this issue as already fixed, but i would like to ask you for confirmation

**Comment by hostep** [comment]
@sdzhepa: sorry for delay but I no longer have personal interest in this bug or its fix. Maybe somebody else can confirm if it's fixed or not?

**Comment by sdzhepa** [comment]
The issue has been fixed in https://github.com/magento/magento2/issues/17186#issuecomment-715499238
