### ISSUE TITLE
Incorrect message: Unable to send the cookie. Maximum number of cookies would be exceeded

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#17195]
Previously this issue was reported in https://github.com/magento/magento2/issues/7931 and https://github.com/magento/magento2/issues/16568, but no one was able to reproduce it.

### Preconditions
1. Magento 2.2.5 installed via composer

### Steps to reproduce
1. Open desktop browser Firefox
2. Navigate to `about:config`
3. Find "dom.storage.enabled" option and change to "false"
4. Navigate to Magento 2.2.5 (frontend), open developer tools >> Storage >> Cookies and look at list (there are 33 cookies)
![image](https://user-images.githubusercontent.com/1873745/43312909-53c414e8-9197-11e8-8e6d-40c4ae917401.png)
5. Duplicate tab (open the same page in another page) - you will have  **43 cookies**.
![image](https://user-images.githubusercontent.com/1873745/43312930-5f54235c-9197-11e8-84e5-771de2b5de7c.png)
6. Try to duplicate tab again - you will have **52 cookies**.
![image](https://user-images.githubusercontent.com/1873745/43312951-6496a2f4-9197-11e8-8302-3d68fdec40fc.png)

### Expected result
1. Cookies list should not grow such fast

### Actual result
1. We can take more then 50 cookies that leads to exception that described in https://github.com/magento/magento2/issues/7931 and https://github.com/magento/magento2/issues/16568

### Tech note
I investigated issue described in https://github.com/magento/magento2/issues/16568 and found that we have 2 different polyfill implementaions for localStorage and sessionStorage:

1. Added to page html (https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Theme/view/frontend/templates/js/polyfill.phtml)
2. As part of jquery.storageapi library  - https://github.com/magento/magento2/blob/2.2-develop/lib/web/jquery/jquery.storageapi.min.js

These implementation are fully different. 1st one works good, but 2nd one adds strange behavior - adds separate cookie with `ls_` prefix in name for each item that should be stored in localstorage and `ss_<some_id>_` for session storage. As result - when customer goes through website - it will add new and new cookies (because of this strange `ss_<some_id>_` prefix).

Sometimess, we're having 2nd implementation used instead of 1st one.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ihor-sviziev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ghost** [comment]
@ihor-sviziev, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by convenient** [comment]
If a customer ends up with 50 or more cookies for whatever reason then they're basically locked out until they clear their browser cookies correct?

If the above is correct then I'm toying with the idea whether it would it be sensible to automatically wipe all the customers cookies when this error occurs and the exception is thrown

- Either way the customer won't get browsing until they clear their cookies
- Doing so automatically will annoy the customer by logging them out, but not so bad as never being able to reliably browse the site again.
- Even in this day and age many customers do not know how to clear their cookies, so this lowers the barrier of recovery and makes these errors a little less catastrophic.
- I believe the 2.2 series has improved new relic logging of reports so this would still be caught and tracked, easily identified when instances of "i was randomly logged out" are reported.

Obviously we should focus on fixing the core magento bug, but I've just seen this error caused by some rogue GTM code creating cookies in a loop and was wondering on how to make this error a little less cataclysmic. 

Just a thought ¯\\_(ツ)_/¯

**Comment by ihor-sviziev** [comment]
Hi @convenient,
I investigated this issue deeper and found that in https://github.com/magento/magento2/commit/1598c0fa816be99cef010721792755fc7506eced#diff-69abf748a729353f99cd623615fecd9dR206 throwing an exception was changed to logging, but message was not updated. Magento CAN set more than 50 cookies, but just writing quite big list of messages "Unable to send the cookie. Maximum number of cookies would be exceeded" in logs, that is confusing people.

I think proper fix will be just updating logged message

**Comment by convenient** [comment]
Interesting. Should magento be allowing that many cookies to be set? It's getting very close to the max limit for some browsers which could result in undefined behaviour.

<img width="644" alt="cookie-support-browsers" src="https://user-images.githubusercontent.com/600190/45280812-c5862b80-b4cd-11e8-8070-7c4ea91406ab.png">

**Comment by ihor-sviziev** [comment]
@convenient i checked, m1 websites works good even with 80+ cookies in IE and another browsers, so it's not a big deal

**Comment by JosephMaxwell** [comment]
We are running into this on a customer's website. Has anyone come up with a decent interim solution?

**Comment by adamj88** [comment]
@JosephMaxwell there's a constant here you can increase with a patch in the interim: https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php#L32

**Comment by ihor-sviziev** [comment]
Hi,

I investigated this issue more deeper. Previously magento was throwing an exception with message "Unable to send the cookie. Maximum number of cookies would be exceeded.", but after https://github.com/magento/magento2/commit/369c963513775cccdd7d7b720d9c5ea5475653ff#diff-69abf748a729353f99cd623615fecd9dR210 - it's just logging of such situation, but cookies are actually sending and no real issue there. This commit was included in Magento 2.2.0, also applied in 2.3.0

It seems like situation much less critical than I thought, just incorrect message is logged here.

So no need to change any constants, you can just ignore such messages, it will not affect production anyhow.

**Comment by giangnv95** [comment]
I got the same problem on magento 2.3.2, Is there any fix from Magento or contributors ?

**Comment by ihor-sviziev** [comment]
As I said above - it’s absolutely not critical issue, it could be ignored.
What’s wrong there - message

**Comment by giangnv95** [comment]
@ihor-sviziev Thanks for reply, cause it's just a warning mess, I also think I can ignore it :)
I just asking again to make sure I don't miss anything valuable :+1:

**Comment by ahmadalkaid** [comment]
Dears,
The issue still there, even when we are in the production mode. I had to override the file to fix it. I am using:
**Magento 2.3
PHP 7.1.33**
So could anyone help here?

Thanks,
- Kaid

**Comment by FerihumF** [comment]
Same issue on 2.2.7.

**Comment by n2diving-dgx** [comment]
Same issue on 2.3.4

**Comment by ihor-sviziev** [comment]
Seems like this issue should reproduce much less as it not creating cookies for translations anymore.
Related changes: 
on frontend https://github.com/magento/magento2/commit/71c781df5536a2ec79c9cf42ade0c262396767a3
on backend  https://github.com/magento/magento2/pull/27364.

**Comment by slavvka** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#27364 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [72567f6b7388a4e762da3ad9c3d96733b8f01e62](https://github.com/magento/magento2/commit/72567f6b7388a4e762da3ad9c3d96733b8f01e62)

The fix will be available with the upcoming 2.4.1 release.
