### ISSUE TITLE
Product listing (inventory) - table not showing

### ISSUE THREAD

**Issue by SLv99** [magento/magento2#1721]
Hi,

This is the second time I came across this issue (two different installations). The catalog table with products is not loaded. It does not show the spinner or something. No errors thrown and also the network inspector / console does not show any issues. The page itself does load fine, including the Add Product button. I can also search for products, I can access individual products via this search. That page works fine.

Is this a known issue? I could not find a similar issue online.

**Comment by ardhitama** [comment]
Hi,

Maybe the same thing happened to me.
Though it prints :

Notice: Undefined index: websites in \magento2\app\code\Magento\Catalog\Ui\Component\Listing\Columns\Websites.php on line 57

I still trying for local fix.

**Comment by SLv99** [comment]
It happend to me again with another installation. It was triggered by putting my store into single store mode. After reversing this the products started to show up again in the inventory.

**Comment by ardhitama** [comment]
Happened on me in that single store mode too

**Comment by piotrekkaminski** [comment]
@SLv99 @ardhitama can you check on latest version? we could not reproduce it.

**Comment by adragus-inviqa** [comment]
In our case, it was the "cataloginventory_stock_item" table having duplicate product IDs because "Manage stock" was set per-website.

When the product list is fetched [here](https://github.com/magento/magento2/blob/f78935dcfb659eaae8a162cc8f863bba2767ad76/app/code/Magento/Catalog/Ui/DataProvider/Product/ProductDataProvider.php#L68), the collection load throws `exception 'Exception' with message 'Item (Magento\Catalog\Model\Product\Interceptor) with the same id "1" already exist' in /vagrant/lib/internal/Magento/Framework/Data/Collection.php:406`,
as it doesn't permit duplicates.

That exception is discarded on merchant beta7 - so that's why you didn't see anything -, but [it's logged in GA](https://github.com/magento/magento2/blob/f78935dcfb659eaae8a162cc8f863bba2767ad76/app/code/Magento/Ui/TemplateEngine/Xhtml/Result.php#L107) (but logs to `system.log` from what I gather, instead of the more appropriate `exception.log` - so it should actually be `->critical($e)`, not `->critical($e->getMessage())`).

So go to your product mentioned in the exception, go to your website scope and set "Manage Stock" to "No". That should leave you with just one row per product in the "cataloginventory_stock_item".
Problem is that.. it doesn't work. Not on beta7 anyway. We had to sql-delete the row.

Though I know M2 has per-website stock in WIP.

Hope this helps someone on earlier versions.

cc @SLv99 @ardhitama
