### ISSUE TITLE
Unble to place order as Guest user.

### ISSUE THREAD

**Issue by mtkumar82** [magento/magento2#17226]
Hi,

I have magento 2.2.4 installed and everything seems working , But Guest checkout not working. Its always giving error "Please Enter customer Email id", While I added it there for guest checkout.  Below is my website url.

http://lourelz.com/

Try to add any product in cart from home page. Then it will move the user to checkout page , Enter email which not exist there and try to checkout as quest. It will always return error, While for login user its working fine. Please look into the issue and help me to resolve this.

Kind Regards,

**Comment by magento-engcom-team** [comment]
Hi @mtkumar82. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mtkumar82 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @mtkumar82 

Unfortunately we can not provide any help with your website. Please provide steps to reproduce the issue on a clean vanilla instance and reopen the ticket.

Thank you.
