### ISSUE TITLE
One or more of the Cache Types are invalidated: Configuration. 

### ISSUE THREAD

**Issue by nwgirl** [magento/magento2#17245]
### 
Every time I log into my Magento 2 site I get this message:

One or more of the Cache Types are invalidated: Configuration. Please go to Cache Management and refresh cache types.

How do I fix this so that it takes care of the cache automatically???

**Comment by magento-engcom-team** [comment]
Hi @nwgirl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nwgirl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@nwgirl please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by hustler203** [comment]
having this issue in Magento  2.4.2  installed on Centos  7  rpm fresh install
