### ISSUE TITLE
2.2.5: A technical problem with the server created an error. 

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#17258]
### Preconditions

1. Upgrade from 2.2.3 > 2.2.5
2. PHP 7

### Steps to reproduce

1. Go to Catalog > Products
2. After results load, "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." appears.

### Expected result

1. No error.

### Actual result

1. Red banner of "A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later." appears on top of Catalog > Products page. I don't see any errors.

If I inspect the page, I see a 500 error as follows:
`Failed to load resource: the server responded with a status of 500 () - /mui/bookmark/save/key/95c6cd211462befaa62b44dff41355169fbbd23b0c33e45666aac9cba1a1f212/?isAjax=true`

**Comment by magento-engcom-team** [comment]
Hi @heyepic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@heyepic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @heyepic 
More details on the catalog and exception log would be helpful in this case. 
Have you tried this with a set of vanila instances?

**Comment by heyepic** [comment]
All my exception log has is an error for some frontend file for my theme (which my theme developer doesn't know how to solve). There is no other errors:
`[2018-07-29 17:51:12] main.CRITICAL: Unable to get content for 'frontend/Mgs/orson/en_US/js/bootstrap.min.js' {"exception":"[object] (Magento\\Framework\\View\\Asset\\File\\NotFoundException(code: 0): Unable to get content for 'frontend/Mgs/orson/en_US/js/bootstrap.min.js' at /vendor/magento/framework/View/Asset/File.php:186)"} []`

**Comment by heyepic** [comment]
Just wanted to post the solution in my case - Mod Security was banning this as it thought SQL injection was occurring in the ajax call. I whitelisted the ID from the httpd log and no more error. :)
