### ISSUE TITLE
Magento 2.2.5 - Product Details Page Images/Tabs Broken

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#17252]
### Preconditions

1. Magento 2.2.5
2. PHP 7 / Linux

### Steps to reproduce

1. Normal upgrade procedure, I happened to do 2.2.3 > 2.2.5
2. Go to frontend of site and view product.

### Expected result

Product images should load. Tabs should work properly.

### Actual result

Image loading gif just shows, images do not load. No product options on configurable products load, dropdown remains empty. I removed all cache, pub/static. Compiled & re-deployed static content. Problem still remains. Worked fine on 2.2.3 prior to upgrade to 2.2.5.

Example page: https://shop.precisionturbo.net/upgrade-2-3l-ecoboost-focus-rs-turbocharger

**Comment by magento-engcom-team** [comment]
Hi @heyepic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@heyepic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by heyepic** [comment]
Found the issue - gallery.phtml in custom theme causing json error.
