### ISSUE TITLE
Adding backend fields via AbstractModifier not sending them to POST

### ISSUE THREAD

**Issue by vo1** [magento/magento2#17255]
### Preconditions

Magento 2.x, unrelated to serverside software

### Steps to reproduce
Defining custom panel via AbstractModifier for editing extension attributes in backend ends in all defined fields not being sent to POST on save action. "Use default" checkbox, however picks up form relation properly.
```
 'delivery_days' => [
                'arguments' => [
                    'data' => [
                        'config' => [
                            'dataType' => Number::NAME,
                            'formElement' => Input::NAME,
                            'componentType' => Field::NAME,
                            'dataScope' => 'product[stock_data][extension_attributes][delivery][days]',
                            'label' => __('Normal'),
                            'default' => 1,
                            'validation' => ['validate-number'],
                            'sortOrder' => 10,
                            'service' => [
                                'template' => 'ui/form/element/helper/service',
                            ]
                        ],
                    ],
                ],
            ],
```
### Expected result
When field is defined, magento should pickup its form as it done in "Use default" checkbox defined in ui/form/element/helper/service by adding 'data-form-part': $data.ns, in data-bind configuration for fields.

### Actual result
POST data misses every defined field except for its "Use default" checkboxes.

### Possible fix
Add 'data-form-part': $data.ns, to https://github.com/magento/magento2/tree/2.2-develop/app/code/Magento/Ui/view/base/web/templates/form/element/ templates so javascript will push form id to data-form-part attribute
```
<input class="admin__control-text" type="text"
    data-bind="
        event: {change: userChanges},
        value: value,
        hasFocus: focused,
        valueUpdate: valueUpdate,
        attr: {
            name: inputName,
            'data-form-part': $data.ns,
            placeholder: placeholder,
            'aria-describedby': noticeId,
            id: uid,
            disabled: disabled,
            maxlength: 255
    }"/>
```

**Comment by magento-engcom-team** [comment]
Hi @vo1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@vo1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by vo1** [comment]
@magento-engcom-team give me {$VERSION} instance

**Comment by vo1** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @vo1. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @vo1, here is your [Magento instance](https://i-17255-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17255-2-2-5.engcom.dev.magento.com/admin](https://i-17255-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @vo1  thank you for your report.
We've acknowledged the issue and added to our backlog.
