### ISSUE TITLE
Checkout page - No text next to the checkboxes

### ISSUE THREAD

**Issue by byDunkman** [magento/magento2#17257]
### Preconditions
1.  Magento 2.0
2. PHP 7.0

### Steps to reproduce
Actually I am using a template. Might it be that the problem is caused by the template?

### Expected result
1. There is text next to the two checkboxes.
2. The button should be translated.

### Actual result
![screenshot_1](https://user-images.githubusercontent.com/19638643/43367549-06350e8a-934f-11e8-9d07-1506d188649f.png)

1. RED: There is no text next to the two checkboxes. Is this just a bug or do I habe to set it?
2. BLUE: Where can I translate the message of the button? I have not found a way yet.

**Comment by magento-engcom-team** [comment]
Hi @byDunkman. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@byDunkman do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Looks like this issue is caused by the existing customization on your system

@byDunkman  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
