### ISSUE TITLE
Can't update the Scripts and Style Sheets field in Head HTML

### ISSUE THREAD

**Issue by antokom** [magento/magento2#17269]
Hello,
I'm trying to add the Google Tag Manager script in Content -> Design -> Configuration -> Store View -> Head Html -> Scripts and Style Sheets but when i try to save the code, the field doesn't update.

### Preconditions
1. Magento 2.2

### Steps to reproduce
1. Go to Content -> Design -> Configuration -> Store View -> Head Html
2. Add the script in Scripts and Style Sheets field
3. Save

### Expected result
1. The field is updated

### Actual result
1. The field doesn't updated

**Comment by magento-engcom-team** [comment]
Hi @antokom. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@antokom do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by antokom** [comment]
@magento-engcom-team give me 2.2.0 instance

**Comment by magento-engcom-team** [comment]
Hi @antokom. Thank you for your request. I'm working on Magento 2.2.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @antokom, here is your [Magento instance](https://i-17269-2-2-0.engcom.dev.magento.com).
Admin access: [https://i-17269-2-2-0.engcom.dev.magento.com/admin](https://i-17269-2-2-0.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by antokom** [comment]
Dear @magento-engcom-team, in the vanilla Magento instance seems it successfully works.

**Comment by ghost** [comment]
@antokom, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
