### ISSUE TITLE
Magento2: Impossible approve discount code in checkout

### ISSUE THREAD

**Issue by Sylvesterx1** [magento/magento2#17264]
### Preconditions

1. Magento 2.2.5

### Steps to reproduce

1. Creating a discount code
2. After go to checkout, should try adding the discount code.

### Expected result

In basket I can approve discount code and work perfect: 
![image](https://user-images.githubusercontent.com/35328055/43369662-210c9b24-9372-11e8-9f5d-f6fb4970a8ea.png)

but in second step in checkout impossible. After accept discount no result: enter image description here
![image](https://user-images.githubusercontent.com/35328055/43369666-32171296-9372-11e8-99a1-6a6905ca8ecc.png)

here is log from the JS console.
![image](https://user-images.githubusercontent.com/35328055/43369669-486cbee2-9372-11e8-8a0a-5cb9d5492d4e.png)
I tried to change to the basic Luma template and the same problem occurs.

**Comment by magento-engcom-team** [comment]
Hi @Sylvesterx1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Sylvesterx1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Sylvesterx1, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![1](https://user-images.githubusercontent.com/40756187/43385270-f0731eee-93e8-11e8-8747-59813e64d994.gif)
