### ISSUE TITLE
Convert CMS pages into a EAV model

### ISSUE THREAD

**Issue by woutersamaey** [magento/magento2#17270]
We should convert the CMS pages into an EAV model, so fields like title, URL key and content can be overridden / translated on a per store basis. Doing so, also makes it possible to link multi-language content using "hreflang" and module developers can have more options to expand on CMS pages.

Why CMS pages are not EAV, is simply beyond me.

I'm willing to put in work for this (along with others), but only if this work will be appreciated (and chances are background compatibility is going to break for this one). I'm expecting mostly issues with setup scripts as the DB table structure would change.

How to go about this?

**Comment by magento-engcom-team** [comment]
Hi @woutersamaey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@woutersamaey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.
