### ISSUE TITLE
Magento 2.2.5: Console log - Refused to apply style/execute script because its MIME type ('text/html') is not a supported MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by muckee** [magento/magento2#17271]
### Preconditions
1. Ubuntu 18.04 LTS installed on a digitalocean droplet.
2. Apache 2.4 w/ mod_rewrite enabled
3. MySQL 5.7
4. PHP 7.1 using ppa:ondrej/php w/ OpCache enabled
5. Redis Server

### Steps to reproduce
1. Download Magento Community Edition 2.2.5 via Composer
2. Apply pre-installation permissions.
3. Install via command line (problem encountered with fresh install and connecting to existing database).
4. Apply post-installation development permissions.
5. Run `setup:upgrade`, `indexer:reindex` and `cache:flush`.
6. Visit frontend or admin page.

### Expected result
1. Default 'Luma' theme or admin login page should be visible.

### Actual result
1. Styles and javascript are not rendered, with lots of 404 errors and invalid MIME type errors displayed in the console.

### Notes
This is well documented throughout the net, though unfortunately I have not been able to find any similar issues on github itself.
It should be noted that an awful lot of questions relating to this issue have been posted on stackexchange and elsewhere very recently, so I assume that the problem has something to do with the 2.2.4 or 2.2.5 update, or at least has been made more prominent by whichever update.

## EDIT
According to [this stackexchange question](https://magento.stackexchange.com/questions/218947/mime-type-error-js-css), the issue also appears when removing the .htaccess file from pub/static.

I have found the problem after manually generating static files. For some reason, they would not generate even with the `-f` parameter, though when I added `-vvv` to make the command verbose, it worked perfectly and generated all the files. They still aren't being picked up on the frontend though. Not sure if it's anything to do with my apache setup, but magento is located as follows: `[website_root]/magento`, with a symlink from `[website_root]/magento/pub` to `[website_root]/html`, where the latter is the directory root defined in my `vhost.conf` file.
For some reason, magento is trying to link static files at `[website_root]/html/pub/path/to/file`, where they should be linked at `[website_root]/html/pub/static/path/to/file`. I have verified this by attempting to access the URLs directly, prepending the extension with `static/`.

I have restarted apache2, following some tweaks I had to make to my apache2.conf file, altered the `base_static_url` entries in the `core_config_data` table and executed `setup:upgrade`, `indexer:reindex` and `cache:flush`, but magento is still trying to pick up the files from the incorrect directory, without `static/` included in the extension.

Am I missing some kind of symlink magic? My setup was working perfectly up until `2.2.4`.

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JoshuaFlood do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by muckee** [comment]
@magento-engcom-team give me {$2.2.5} instance

**Comment by JoshuaFlood** [comment]
@magento-engcom-team please let me know if I have misunderstood what you meant about commenting the instance. Thanks.

**Comment by muckee** [comment]
@magento-engcom-team Please see my updates to the original issue.

**Comment by ghost** [comment]
@JoshuaFlood, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only. It's obvious your problem is caused by incorrect configuration.
Also, if you want to get test instance from bot, do not use curly brackets around version number.
