### ISSUE TITLE
Cart sidebar currency format wrong in Magento 2.2.3 / jp_JP / GBP

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#17276]
### Environment
* Ubuntu 16.04.3
* Nginx 1.10.3
* MySQL  5.6.35
* PHP 7.0.30
* Magento 2.2.3

### Steps to reproduce
1. Set locale to jp_JP
1. Set currency to GBP
1. Add item to cart
1. Go to /checkout/cart

### Expected result
* AJAX cart sidebar should show the GBP price for the only cart item, formatted according to JP locale.

### Actual result
* Thousands separator is correct, but price is three orders of magnitude (1000x) too small.
![github_1](https://user-images.githubusercontent.com/8377620/43409319-82b01c62-941b-11e8-9b53-f77cf513cabf.png)
* This is just a JS formatting error. The actual value of the order is correct in payment gateway and admin.

**Comment by magento-engcom-team** [comment]
Hi @JacobDrummond. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JacobDrummond do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Duplicate of #12527
