### ISSUE TITLE
Can't edit product or create new attribute set after migration

### ISSUE THREAD

**Issue by allblued** [magento/magento2#17277]
Can't edit product or create new attribute set after migration
I used data-migration-tool to migrate my store from 1.9.2.2 to 2.1.14, but after the migration, I find I can't open "edit" page of any existing product. The following error message show up:

========================================================

 

There has been an error processing your request.

The configuration parameter "formElement" is a required for "" field.

Error log record number: 1495859023951

(Yes, there is nothing in the second quote mark)

========================================================

Also, I tried to add new product, with new attribute set, but when I configured it and click "save", it shows:

========================================================

 

Attribute with the same code already exists.

========================================================

Anyone knows how to solve it?

**Comment by magento-engcom-team** [comment]
Hi @allblued. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@allblued do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
Thanks for bug report! However, problems with data migration from `1.x` must be reported in https://github.com/magento/data-migration-tool repository.
