### ISSUE TITLE
Single store mode - non responsive changes to category attributes

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#17278]
### Preconditions

1. PHP 7
2. Magento 2.2.1
3. Migrated from Magento 1.9.1 - with one store view

### Steps to reproduce

1. Unselect the check box 'Use Default Value' for category field 'Include in Menu' on store view mode
2. Disable 'Include in Menu' option on store view mode
2. Enable Single Store Mode
3. Enable 'Include in Menu' option

### Expected result

1.  Category is included in menu 

### Actual result

1. Category is not included in menu.
2. You have to disable single store mode, tick the 'use default' check box, then enable single store mode again. Then this will work

This is a bit of pain for us as from migration from 1.9.1 we have a lot of category attributes that have 'use default' box unticked. So we will have to go through and tick all these category attribute boxes in order for us to use single store mode.

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nadroj467 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nadroj467** [comment]
@magento-engcom-team give me {2.2.1} instance

**Comment by ghost** [comment]
@nadroj467, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
