### ISSUE TITLE
Vat is not saved on storefront -2.2.5

### ISSUE THREAD

**Issue by melissakokel** [magento/magento2#17283]
Magento version CE 2.2.5 , vat adress field is not saved on the edit address or checkout address. 
The attribrutes are existing on the database 
Admin show on storefront is set to true. 
Can you please let me know what should I do to fix it?

### Preconditions

1. Magento 2
2. "Stores" > "Settings" > "Configuration" > "Customers" > "Customer Configuration" > "Create New Account Options" > "Show VAT Number on Storefront" set to "Yes".
3. Product created and visible on storefront.

### Steps to reproduce

1. Register Customer from Storefront.
2. Place an Order as Customer, set "VAT Number" while on Checkout.
3. Open Customers Grid on admin.

### Expected result

1. Tax VAT Number is filled in Customers Grid.

### Actual result

1. Tax VAT Number column is blank in  Customers Grid.

**Comment by magento-engcom-team** [comment]
Hi @melissakokel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@melissakokel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@melissakokel, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by melissakokel** [comment]
Yes I do confirm that I was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

**Comment by sskulkarni** [comment]
@melissakokel ,
Actually is VAT is a field of "Address" entity not of "Customer".

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment]
#MM19IN

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment]
@melissakokel , @sskulkarni is right
Actually is VAT is a field of "Address" entity not of "Customer". so for customer you need add vat number while editing the customer
