### ISSUE TITLE
Exception thrown by cron job staging_synchronize_entities_period

### ISSUE THREAD

**Issue by nguyetnguyen** [magento/magento2#17281]
### Preconditions
1. Magento EE 2.2.5
2. Php 7.0.28, Xampp, Windows and also on Linux

### Steps to reproduce
Re-run conjob php bin/magento cron:run

### Expected result

1. No error thrown

### Actual result

Exception logs
```
[2018-07-10 02:35:05] report.CRITICAL: Repository should return instance of %s
{"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Repository should return instance of %s at /var/www/repo/src/vendor/magento/module-staging/Model/SynchronizeEntityPeriod.php:186)"}
```

Debugging shows problem in detail like this:
`Repository should return instance of Magento\SalesRule\Api\Data\RuleInterface Magento\SalesRule\Model\Rule\Interceptor Magento\SalesRule\Api\Data\RuleInterface {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Repository should return instance of Magento\\SalesRule\\Api\\Data\\RuleInterface Magento\\SalesRule\\Model\\Rule\\Interceptor Magento\\SalesRule\\Api\\Data\\RuleInterface at /var/www/monash-dev2.balancenet.com.au/repo/src/vendor/magento/module-staging/Model/SynchronizeEntityPeriod.php:186)"}`

Seems
`$entity = $retriever->getEntity($entityId);`
$entity is Magento\\SalesRule\\Model\\Rule\\Interceptor while Magento\SalesRule\Api\Data\RuleInterface  is expected

**Comment by magento-engcom-team** [comment]
Hi @nguyetnguyen. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nguyetnguyen do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@nguyetnguyen, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by tereshvti** [comment]
I'm having exactly the same issue at 2.2.5 version. Why is it closed?

**Comment by tereshvti** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @tereshvti. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @tereshvti, here is your [Magento instance](https://i-17281-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17281-2-2-5.engcom.dev.magento.com/admin](https://i-17281-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tereshvti** [comment]
@magento-engcom-team This instance is not EE. And am I supposed to verify cron job issue. It is more then obvious that class instance doesn't match.

**Comment by ghost** [comment]
@tereshvti, this issue tracker is intended for Magento CE issues only.
