### ISSUE TITLE
Installed magento swagger not run. 

### ISSUE THREAD

**Issue by mimrank** [magento/magento2#17288]
Hi,
i try to get swagger document of Magento ver. 2.1.6, but its how this error. 

`500 : {"message":"Class \"array\" does not exist. Please note that namespace must be specified.","trace":"#0 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/module-webapi\/Model\/Config\/ClassReflector.php(103): Magento\\Framework\\Reflection\\TypeProcessor->register('array')\n#1 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/module-webapi\/Model\/Config\/ClassReflector.php(72): Magento\\Webapi\\Model\\Config\\ClassReflector->extractMethodData(Object(Zend\\Code\\Reflection\\MethodReflection))\n#2 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/module-webapi\/Model\/ServiceMetadata.php(120): Magento\\Webapi\\Model\\Config\\ClassReflector->reflectClassMethods('Technify\\\\Dsn\\\\Ap...', Array)\n#3 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/module-webapi\/Model\/ServiceMetadata.php(148): Magento\\Webapi\\Model\\ServiceMetadata->initServicesMetadata()\n#4 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/module-webapi\/Model\/AbstractSchemaGenerator.php(75): Magento\\Webapi\\Model\\ServiceMetadata->getServicesConfig()\n#5 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/module-webapi\/Controller\/Rest.php(278): Magento\\Webapi\\Model\\AbstractSchemaGenerator->getListOfServices()\n#6 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/module-webapi\/Controller\/Rest.php(214): Magento\\Webapi\\Controller\\Rest->processSchemaRequest()\n#7 \/home\/rangrasiya123\/public_html\/beta67556\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(24): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/home\/rangrasiya123\/public_html\/beta67556\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#10 \/home\/rangrasiya123\/public_html\/beta67556\/index.php(58): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#11 {main}"} https://rangrasiya.com.pk/beta67556/rest/default/schema?services=all`

[image](https://user-images.githubusercontent.com/10322671/43451900-7541d3a4-94cf-11e8-8f6a-0bfe8040e774.png)

**Comment by magento-engcom-team** [comment]
Hi @mimrank. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mimrank do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@mimrank, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
