### ISSUE TITLE
Product attributes update in all store views is not working

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#17284]
**Preconditions**
1.	Magento CE 2.2.5
2.	PHP 7.1
**Steps to reproduce**
1.	Create product using default Magento REST API /rest/V1/products with the string {"product":{"id":"","sku":"DTD-1","name":"DTD Descrption","price":45,"typeId":"simple","weight":"0.25","attribute_set_id":4}}
2.	Product created in Magento and provided attributes set for Default store view as well as All store views
3.	Now update the created product by changing product’s description by using same REST API /rest/V1/products with the following string {"product":{"id":"2057","sku":"DTD-1","name":"DTD","price":45,"typeId":"simple","weight":"0.25","attribute_set_id":4}} [“id” is created product’s id]
4.	Check if the product description updated in All store views
**Expected result**
1.	The description should be updated in All store views as well as Default store view
**Actual result**
1.	The description is updating in Default store view only, not updating in All store views
**Note:**
We are facing same issue with product which is created programmatically.

**Comment by magento-engcom-team** [comment]
Hi @i95devdivya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@i95devdivya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by i95devdivya** [comment]
**To help us process this issue please make sure that you provided the following information:**
We provided the following details in the initial comment only.
  Summary of the issue
  Information on your environment
  Steps to reproduce
  Expected and actual results

**@magento-engcom-team give me {$VERSION} instance**
We are using Magento CE 2.2.5 version.

**@i95devdivya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?**
Yes. We are able to replicate in vanilla Magento instance, steps mentioned in the initial comment only.

**Comment by ghost** [comment]
@i95devdivya, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @vaibhavahalpara. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Bravo** [comment]
Hi @i95devdivya,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1036" alt="Screenshot 2024-10-22 at 10 00 57" src="https://github.com/user-attachments/assets/8c86aa88-b0d7-4531-86d2-d92eb755cd81">



<img width="1036" alt="Screenshot 2024-10-22 at 10 01 02" src="https://github.com/user-attachments/assets/b4119232-6909-4e67-a6d6-758f83dec3bd">


<img width="1036" alt="Screenshot 2024-10-22 at 10 01 09" src="https://github.com/user-attachments/assets/42f3b0fd-115c-4e25-b341-f30c8a3ce928">



<img width="1036" alt="Screenshot 2024-10-22 at 10 01 16" src="https://github.com/user-attachments/assets/c3c4e4b7-769d-4679-af8e-7de473d4e3b6">


product description updated in All store views


Hence we are closing this issue.

Thanks.
