### ISSUE TITLE
Magento 2.2.5: Year-to-date dropdown in Stores>Configuration>General>Reports>Dashboard

### ISSUE THREAD

**Issue by muckee** [magento/magento2#17289]
### Preconditions
1. LAMP stack
2. Redis installed
3. Magento 2.2.5 installed

### Steps to reproduce
1. Go to `Stores > Configuration > General > Reports`
2. Click on the 'Month' dropdown of the `Year-to-date starts` section.

### Expected result
1. Numerical list appears of numbers 01 to 12.

### Actual result
1. Numerical list appears of following numbers: [01,03,03,05,05,07,07,09,09,10,10,11,11,12,12]

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JoshuaFlood do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@JoshuaFlood, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your report. 
The issue has been fixed in magento/magento2#17383 by @teddysie in 2.2-develop branch
Related commit(s):
 - [2c64c16e352c9b52b70432dd4ac631a56ed5e2d4](https://github.com/magento/magento2/commit/2c64c16e352c9b52b70432dd4ac631a56ed5e2d4)
 - [5e847c4d43507eb46ff7f0746ffb6cf7c29b024d](https://github.com/magento/magento2/commit/5e847c4d43507eb46ff7f0746ffb6cf7c29b024d)

The fix will be available with the upcoming 2.2.7 release.

**Comment by sidolov** [comment]
Hi @JoshuaFlood. Thank you for your report. 
The issue has been fixed in magento/magento2#17496 by @ronak2ram in 2.1-develop branch
Related commit(s):
 - [80b41cf73f2b5cd46ef9bdc28874e0334344e0c6](https://github.com/magento/magento2/commit/80b41cf73f2b5cd46ef9bdc28874e0334344e0c6)
 - [a19df73c6ea89c6806d9413fee65882ba8e824c6](https://github.com/magento/magento2/commit/a19df73c6ea89c6806d9413fee65882ba8e824c6)

The fix will be available with the upcoming 2.1.16 release.

**Comment by sidolov** [comment]
Hi @JoshuaFlood. Thank you for your report. 
The issue has been fixed in magento/magento2#17495 by @ronak2ram in 2.3-develop branch
Related commit(s):
 - [cea62ecf191f706b6cdef82973ac794989bb80de](https://github.com/magento/magento2/commit/cea62ecf191f706b6cdef82973ac794989bb80de)
 - [1c70659dc409ba6a369a23542dd2a9fe2be7b683](https://github.com/magento/magento2/commit/1c70659dc409ba6a369a23542dd2a9fe2be7b683)

The fix will be available with the upcoming 2.3.0 release.
