### ISSUE TITLE
2.2.4 to 2.2.5 - SQL error for featured products widget

### ISSUE THREAD

**Issue by nedge2k** [magento/magento2#17286]
### Summary
After upgrade to 2.2.5 from 2.2.4, pages that contain a widget displaying featured products fail to load with an SQL error.

### Preconditions

1. PHP7
2. M2.2.5

### Steps to reproduce

1. Upgrade from 2.2.4 to 2.2.5
2. Have "featured products" in catalog
3. Have a widget on homepage with "featured products"

### Expected result

1. After upgrade (and cache:clean|flush, reindex, static-deploy etc. etc.), pages will load with no issues.

### Actual result

1. Pages containing featured products widget fail to load with SQL error:

> main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_featured_default.value' in 'where clause', query was: SELECT DISTINCT  COUNT(DISTINCT e.entity_id) FROM `mg_catalog_product_entity` AS `e` INNER JOIN `mg_catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2' INNER JOIN `mg_catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(`e`.`entity_id`, `at_featured_default`.`value`) IN ('131', '146', '151', '164', '270', '336', '344', '345', '379', '385')) ))

### Temporary fix
1. Delete widget

### Additional info
1. Not tried on a vanilla install

**Comment by magento-engcom-team** [comment]
Hi @nedge2k. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@nedge2k do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@nedge2k, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more info about your "featured products" widget.

**Comment by nedge2k** [comment]
Hi, so it's a Catalog Products List widget, set to display only on CMS homepage, with the condition of Featured = yes. Deleting or removing the layout options for the widget prevent the error but even if you delete it entirely and then make a new one exactly the same, the error returns.

Seems i'm not entirely alone with the issue either: https://magento.stackexchange.com/questions/232862/upgrade-2-2-4-to-2-2-5-sql-query-error

**Comment by ghost** [comment]
@nedge2k, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![default](https://user-images.githubusercontent.com/40756187/43519345-bc99fb0a-9597-11e8-96b6-057a60cf099f.png)

**Comment by kevinlab51** [comment]
@magento-engcom-team  Some additional information to add to the comment of the issue owner:
You have to have a featured attribute with the scope store view.
When you have the featured attribute scope to global it is working.

Please have a look into this magento.

**Comment by nedge2k** [comment]
> @magento-engcom-team Some additional information to add to the comment of the issue owner:
> You have to have a featured attribute with the scope store view.
> When you have the featured attribute scope to global it is working.
> 
> Please have a look into this magento.

Changing attribute scope to global fixed it. Thanks Kevin!
