### ISSUE TITLE
Edit Address or Reorder in Multi-Store not possible if not Default Website

### ISSUE THREAD

**Issue by jwundrak** [magento/magento2#17299]
### Setup
1. some linux (tested arch, centos and various debian based distros)
2. php 7.0-7.2 latest version

### Preconditions
1. Using Magento 2.1, 2,2 and 2.3 with develop-branch including sample-data
2. create a new website/store/store-view
3. set for default - store view in website scope: allowed country = US, default country = US
4. set for new website: allowed country = UK and default_country = UK 
5. create a order in the new store view

### Steps to reproduce
1. goto order in edit order of the created order
2. edit address

### Actual result
1.  Country should preselected (customer e.g. selected uk. This is a possible option, but not preselected)
2. Region is only a text input, not a select
3. if you want to reorder, validation failed, cause of country or region

### Expected result
1. save or do a reorder

### Additional notice

I'm debugged a lot and the main problem is, that the adminhtml is initialized in default scope. `\Magento\Directory\Helper\Data::getRegionJson` renders in the address edit call only the default website.
Also there is this comit: https://github.com/magento/magento2/commit/41db211ad868cae7b594b909f875007f7aef1285
It allowes the correct website-countries, but the preselection is not correct.

I will write a workaround, but i think the main problem is, that there is no emulation mode for something in the back office  (or i not recognice them)

Some comment: The commit, i referenced, was backported through di-preference and plugin and also native, but this does nothing

**Comment by magento-engcom-team** [comment]
Hi @jwundrak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@jwundrak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @jwundrak thank you for you report.   Can you please provide a short video about actual result ?

**Comment by jwundrak** [comment]
@engcom-backlog-nazar [Here is an example](https://drive.google.com/open?id=1pylLVhxn-QcWhsnRtnsJP7WlW7DPiEUf) on Magento 2.2.5 with a second website, there only Germany is the default country and the only allowed country.

**Comment by ghost** [comment]
@jwundrak i'm not able to reproduce this on 2.2-dev and 2.3-dev branch see attachments

![frame-03a](https://user-images.githubusercontent.com/40756439/43519569-9f938160-9598-11e8-80eb-dfc8b651e5a3.gif)

**Comment by jwundrak** [comment]
@engcom-backlog-nazar I rerun the same steps as in the video and in 2.2-dev it works. 

I found the commit: c23480acc89026c890e2ab6ad809cb7a0d30f9b6

Sorry for reporting this already fixed bug!
