### ISSUE TITLE
Search REST API returns wrong total_count

### ISSUE THREAD

**Issue by mohamed-karam** [magento/magento2#17295]
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Make a request to endpoint `GET /V1/search ` and provide `searchCriteria[pageSize]`.
2. Repeat the previous point with `searchCiteria[currentPage]` = 2

### Expected result

1. You will get a response with number of items equals `searchCriteria[pageSize]` in the first time
2. You will get a response with number of items <= `searchCriteria[pageSize]` in the second time
2. The `total_count` is the same on both requests

### Actual result
The value of `total_count` equals `searchCriteria[pageSize]` not the total count of the search result items.

**Comment by magento-engcom-team** [comment]
Hi @mohamed-karam. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@mohamed-karam do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @mohamed-karam I'm not able to reproduce this issue by following the steps you provided. 
![frame-03f](https://user-images.githubusercontent.com/40756439/43508778-8594f0ce-9579-11e8-9d06-f293176c9cdd.gif)

**Comment by ghost** [comment]
@mohamed-karam  you need to use together, like this-> `&searchCriteria[current_page]=1&searchCriteria[page_size]=2`

**Comment by mohamed-karam** [comment]
I think I need to elaborate more.
This is the request I send
`{{url}}/rest/V1/search?searchCriteria[pageSize]=10&searchCriteria[currentPage]=1&searchCriteria[requestName]=quick_search_container&searchCriteria[filterGroups][0][filters][0][field]=search_term&searchCriteria[filterGroups][0][filters][0][conditionType]=like&searchCriteria[filterGroups][0][filters][0][value]={search_query}`

If this search query for example has 15 items, the `total_count` will equal 10 not the real value of the total count of all items which should be 15.

**Comment by ghost** [comment]
@mohamed-karam in your case currentPage=1 pageSize=10, so if you have a 100 result items it be a ->
1 page have -> 10 item, second page have 10 items so you have 10 pages, total count always 10 items on page.

**Comment by mohamed-karam** [comment]
That isn't what happens with other endpoints that have searchCriteria. For example if you call this endpoint
`{{url}}/rest/V1/products?searchCriteria[pageSize]=10&searchCriteria[currentPage]=1&searchCriteria[filterGroups][0][filters][0][field]=category_id&searchCriteria[filterGroups][0][filters][0][value]=75&searchCriteria[filterGroups][0][filters][0][conditionType]=eq`
The total_count value will be the count of all items that matches the searchCriteria not just 10.

**Comment by ghost** [comment]
@mohamed-karam , thank you for your report .
We've acknowledged the issue and added to our backlog.

**Comment by abdulmalik422** [comment]
@engcom-backlog-andrii Please Update? I Will also face this issue.

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ronak2ram** [comment]
@magento-engcom-team give me 2.3-develop instance
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, here is your [Magento instance](https://i-17295-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-17295-2-3-develop.instances.magento-community.engineering/admin](https://i-17295-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ronak2ram** [comment]
Hello @magento-engcom-team 
I can't find this issue in 2.3-develop instance.

![screenshot from 2019-01-12 12-21-22](https://user-images.githubusercontent.com/11473750/51070511-7f51fc00-1668-11e9-8ac9-0cd6529e04fd.png)
![screenshot from 2019-01-12 12-20-52](https://user-images.githubusercontent.com/11473750/51070512-7fea9280-1668-11e9-88d4-d8fbbec25dc6.png)

**Comment by abdulmalik422** [comment]
Dear Ronak Patel : Please Changed url and check on rest/V1/search.

**Comment by ronak2ram** [comment]
@abdulmalik422 You right there is an issue. Let me try to find a solution

**Comment by magento-engcom-team** [comment]
Hi @mohamed-karam. Thank you for your report. 
The issue has been fixed in magento/magento2#21713 by @ronak2ram in 2.3-develop branch
Related commit(s):
 - [7c55811a43ae0a9d80cc3c6544c42088bfe0d790](https://github.com/magento/magento2/commit/7c55811a43ae0a9d80cc3c6544c42088bfe0d790)
 - [a546e142fa738eeb09e09499bd577e40749cc57c](https://github.com/magento/magento2/commit/a546e142fa738eeb09e09499bd577e40749cc57c)
 - [9dc26ccc47495eb33809cbdf180c848373251d9f](https://github.com/magento/magento2/commit/9dc26ccc47495eb33809cbdf180c848373251d9f)

The fix will be available with the upcoming 2.3.2 release.
