### ISSUE TITLE
We can't add this item to your shopping cart right now.

### ISSUE THREAD

**Issue by loibv5989** [magento/magento2#17298]
### Preconditions

1. Magento 2.2.5
2. Php 7.0.x,7.1.x, Percona Mysql 5.7, nginx

### Steps to reproduce
I have a mutiple store setup and I get an error when adding to cart.

### Expected result

1.  
![image](https://user-images.githubusercontent.com/30828860/43481200-820a8a76-952f-11e8-9472-e194dfa41c97.png)
exception.log:
[2018-07-31 18:52:18] main.CRITICAL: ampromo_items is unknown type {"exception": "[object] (InvalidArgumentException /) / [/ code]

I tried it with #12129 but it did not work. All help is appreciated

**Comment by magento-engcom-team** [comment]
Hi @dv-denda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dv-denda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @dv-denda thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by joostvanveen** [comment]
I encountered exactly the same issue.

In our case it happened in the following circumstances:

1. Data migration from M1 to M2
1. M1 store had Amasty Auto Add Promo Items extension
1. M2 store did **not** have the Amasty Auto Add Promo Items extension
1. Amasty Auto Add Promo Items promotion rules had also been imported, hence the 'ampromo_items'

Solution:
Delete all promotion rules in the new store.

**Comment by loibv5989** [comment]
Thank you so much @joostvanveen

**Comment by rk610** [comment]
After migrate m1 to m2 version 2.3.0 error bellow url in add to cart please help me 

![error add cart](https://user-images.githubusercontent.com/55425682/65012802-5213c700-d936-11e9-945f-d3b2050e84cf.png)
