### ISSUE TITLE
Unknown error : Element 'script': The attribute 'src' is required but missing.

### ISSUE THREAD

**Issue by sibi4586** [magento/magento2#17304]
Hi 

I am a newbie Magento2 developer and tried to develop shipping restriction country. So I created custom module which consists install data setup for creating custom product attribute. After that I had done the setup:upgrade and di:compile then static deploy too.

After that the error triggered 

Now showing this error only not showing any php error to fix the issue

This is really unknown. I deleted the attribute and module. But still have the same error

Install data script shows below

namespace Informatics\Restrictproduct\Setup;

use Magento\Eav\Setup\EavSetup;
use Magento\Eav\Setup\EavSetupFactory;
use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class InstallData implements InstallDataInterface
{
	private $eavSetupFactory;

	public function __construct(EavSetupFactory $eavSetupFactory)
	{
		$this->eavSetupFactory = $eavSetupFactory;
	}
	
	public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
	{
		$eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
		$eavSetup->addAttribute(
			\Magento\Catalog\Model\Product::ENTITY,
			'shipping_restriction',
			[
                                'group' => 'General'
				'type' => 'varchar',
				'backend' => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
				'frontend' => '',
				'label' => 'Disallow shipping to',
				'input' => 'multiselect',
				'class' => '',
				'source' => 'Informatics\Restrictproduct\Model\Attribute\Source\Country',
				'sort_order' => 50,
				'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
				'visible' => true,
				'required' => false,
				'user_defined' => false,
				'default' => '',
				'searchable' => false,
				'filterable' => false,
				'comparable' => false,
				'visible_on_front' => true,
				'used_in_product_listing' => true,
				'unique' => false,
				'apply_to' => 'simple,configurable,bundle,grouped'
			]
		);
	}
}

I would be happy if you give quick update

Thanks

**Comment by magento-engcom-team** [comment]
Hi @sibi4586. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sibi4586 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@sibi4586, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by sibi4586** [comment]
My website URL => https://informaticstec.com/cleopatrawebv2/


So you can test
