### ISSUE TITLE
Missing "use default" checkbox for product images when overriding on store view level

### ISSUE THREAD

**Issue by woutersamaey** [magento/magento2#17303]
### Preconditions
1. Tested in Magento 2.2.4
2. Have a product with images on it

### Steps to reproduce
1. Edit a product
2. Switch to a certain store view scope
3. Edit the primary image for the product
4. There is no "Use default" checkbox, to use the product images as entered on the global scope

### Expected result
1. Allow us to reset product images to the parent or global scope, just like any other attribute

### Actual result
1. Screenshot: 
![image](https://user-images.githubusercontent.com/71019/43506897-e529a5f6-956b-11e8-96dc-e8b9b74c7766.png)

**Comment by magento-engcom-team** [comment]
Hi @woutersamaey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@woutersamaey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @woutersamaey. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/82
