### ISSUE TITLE
Unused variable collection, doubled instance

### ISSUE THREAD

**Issue by alexbelkin** [magento/magento2#17308]
Hello, I'm newbie at Magento, and looking for examples of code in core. I found that collection variable in that method is unused, and searchResult class is instantiated instead of returning collection with items. I checked it in my code, and can't find what are the benefits of using searchResults here instead of collection, items are the same.

https://github.com/magento/magento2/blob/50f974b0c8f3ada8d7a2c9b0f9924976dacd2088/app/code/Magento/Cms/Model/BlockRepository.php#L150-L163

**Comment by magento-engcom-team** [comment]
Hi @alexbelkin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@alexbelkin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
