### ISSUE TITLE
[2.2.5] Admin panel unresponsive in Chrome due to .js errors

### ISSUE THREAD

**Issue by aeu** [magento/magento2#17309]
### Preconditions
1. Magento 2.2.5
2. PHP 7.1.19 
3. CentOS centos-release-7-5.1804.el7.centos.2.x86_64
4. Chrome Version 67.0.3396.99

### Steps to reproduce
1. Install using Web wizard.  (I used https for storefront and admin but this may not be necessary)
2. After installation, using Chrome navigate to admin, then go to Stores->Configuration

### Expected result
1. Admin should work

### Actual result
1. Admin panel hangs.  Console shows 404 errors followed by security errors saying "refused to execute script from ... because it's MIME type {'text/html'} is not executable and strict MIME type checking is enabled.  404 errors were for colpick.js and jquery.fancybox.pack.js 

### Solution
These errors were caused because Dotdigitalgroup Email which is included in the 2.2.5 baseline has references to, but does not appear to include, the files colpick.js and jquery.fancybox.pack.js.  Once this module is disabled, then the admin starts working again.

php /var/www/html/bin/magento module:disable Dotdigitalgroup_Email

**Comment by magento-engcom-team** [comment]
Hi @aeu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@aeu do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by aeu** [comment]
Screenshot of console (forgot this earlier)
![screen shot 2018-08-01 at 8 12 18 am](https://user-images.githubusercontent.com/2225377/43526934-569a1dae-9573-11e8-85c8-7169825dad11.png)

**Comment by ghost** [comment]
@aeu , thank you for your report.We were not able to reproduce this issue by following the steps you provided.Please provide more detailed steps to reproduce or try to reproduce this issue ona clean installation or latest release.

**Comment by aeu** [comment]
> Please provide more detailed steps to reproduce or try to reproduce this issue ona clean installation or latest release.

Hi @engcom-backlog-andrii 

The release I used was the current was Magento 2.2.5 (Magento-CE-2.2.5-2018-06-26-09-20-19.tar.gz from your site).  

I'm not sure what further information I can provide regarding steps to reproduce, I did literally nothing other than run the web installer, and then click the button to go to the admin panel.  

What did you try on your end?  Did you verify that the Dotdigitalgroup_Email module, which is the cause of the error, was enabled in your installation?

**Comment by magento-engcom-team** [comment]
Hi @denisflosi1. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by denisflosi1** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @denisflosi1. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @denisflosi1, here is your [Magento instance](https://i-17309-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-17309-2-3-develop.engcom.dev.magento.com/admin](https://i-17309-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by denisflosi1** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @denisflosi1. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @denisflosi1, here is your [Magento instance](https://i-17309-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17309-2-2-5.engcom.dev.magento.com/admin](https://i-17309-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by denisflosi1** [comment]
Hello @aeu.

This issue isn't reproducible on the latest version, please try to upgrade your version for the latest one (2.3.x).

**Comment by hostep** [comment]
@denisflosi1: as @aeu said in his post, it is most likely caused by the Dotdigitalgroup_Email module.
This module is included **by default** in Magento 2 when installing it with composer.
This module is **not** included when you ask the @magento-engcom-team for a test instance, this makes asking for a test instance not a correct way of trying to reproduce this bug. (normally there should be a menu 'Marketing Automation' underneath the 'Reports' main menu in the adminhtml when this module is installed, so that's how I was able to verify that it wasn't installed).

@ Magento: I understand you guys don't want to take responsibility for **fixing** bugs in those core bundled extensions, but you should at least take responsability in **acknowledging** them and reporting them to those third party vendors if you are going to keep including those modules **by default** in a Magento 2 installation.

/cc @okorshenko 

Just my 2 cents :)

**Comment by okorshenko** [comment]
Hi @hostep 
You are right. We have contact person for every bundled extension and we are forwarding these reports to them via our internal system.

**Comment by hostep** [comment]
Thanks @okorshenko!

Is there some way Magento can force those vendors to also put their code online on Github or Bitbucket or ..., so we can link from issues in the magento2 repo to their repo?
That way it will be much easier for people to see what the status of a bug is in these CBE's and will make it more user friendly to start reporting bugs to those vendors.

**Comment by denisflosi1** [comment]
@magento-engcom-team give me 2.3.5-p1 instance

**Comment by denisflosi1** [comment]
@magento-engcom-team give me 2.3.5-p1 instance
