### ISSUE TITLE
cart().subtotal_excl_tax and cart().subtotal_incl_tax are the same

### ISSUE THREAD

**Issue by andrejavidovic** [magento/magento2#17306]
cart().subtotal_excl_tax and cart().subtotal_incl_tax are the same
i got the some price, how can I get the subtotal with including tax
<div class="amount price-container">
    
        
            <span class="price-wrapper" data-bind="html: cart().subtotal_excl_tax" style="color: blue;"></span>
            <span class="price-wrapper" data-bind="html: cart().subtotal_incl_tax"></span>
        

        
            <span class="price-wrapper" data-bind="html: cart().subtotal_incl_tax"></span>
        

        
            <span class="price-wrapper price-including-tax"
                  data-bind="attr: { 'data-label': $t('Incl. Tax') }, html: cart().subtotal_incl_tax">
            </span>

            <span class="price-wrapper price-excluding-tax"
                  data-bind="attr: { 'data-label': $t('Excl. Tax') }, html: cart().subtotal_incl_tax">
            </span>
        
    
    
        
            
        
    
</div>
Can you help me please.

**Comment by magento-engcom-team** [comment]
Hi @andrejavidovic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@andrejavidovic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@andrejavidovic, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
