### ISSUE TITLE
watermark png alpha background turns black on "jpg" products images

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#17301]
### Summary of the issue,
water mark alpha background turn black on jpg products images
![screenshot from 2018-07-31 23-10-17](https://user-images.githubusercontent.com/3238761/43489724-42d4f3a2-951e-11e8-8274-9416152cb3cd.png)

### Preconditions
magento 2.2.4 php 7

### Steps to reproduce
create a water marke and put opacity from 1 to 99

### Expected result
on jpg products images, watermark should have white background instead of black 

### Actual result
jpg images show water mark overlay with boxed black background

**Comment by magento-engcom-team** [comment]
Hi @salehawal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@salehawal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by salehawal** [comment]
i updated the issue text .. change the fail label please

**Comment by ghost** [comment]
Duplicate of #16929
