### ISSUE TITLE
Google reCAPTCHA : Sometimes reCAPTCHA doesn't display

### ISSUE THREAD

**Issue by onlinejitu** [magento/magento2#17319]
### Preconditions

1. Magento 2.2.5
2. Google reCAPTCHA extension should be installed and configured to show on frontend 'Customer Login' form
3. Magento's default Luma theme should be activated

### Steps to reproduce

1. I have installed 'Google reCAPTCHA' in Magento 2.2.5, and configured it and then enabled it for frontend forms as well as for admin login.
2. I am using Magento's default Luma theme
3. Now I have opened 'Customer Login' page on frontend, this time it displayed Google reCAPTCHA
4. Then, I have filled my email address and password (without choose reCAPTCHA) and then clicked on 'Sign In' button
5. Now you would get a form without reCAPTCHA

### Expected result

1. It should display login form again with error message 'Incorrect reCAPTCHA' and there should also be reCAPTCHA button to choose captcha images

### Actual result

1) If we submit form without choosing reCaptcha then it shows error message like 'Incorrect reCAPTCHA' that is fine, but the reCaptcha doesn't show in that screen (i.e. after submitting form without choosing reCaptcha)
2) Sometimes, it doesn't show reCaptcha when form load for first time

![image](https://user-images.githubusercontent.com/36662828/43571784-758e4a30-965b-11e8-9634-1be575cd19fa.png)

**Comment by magento-engcom-team** [comment]
Hi @onlinejitu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@onlinejitu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@onlinejitu , please refer to the [Community Forums](https://community.magento.com/)or the [Magento Stack Exchange](https://magento.stackexchange.com/) site foradvice or general discussion about this issue. The GitHub issue tracker isintended for Magento Core technical issues only.

**Comment by onlinejitu** [comment]
Hello @engcom-backlog-andrii 

Thanks for this information, I will post it thos Community Forum or on Magento Stack Exchange

**Comment by michelecanal** [comment]
Hi, 
now, in magento 2.3, google recaptcha is integrated.
So, can you investigate the problem, please?
The description is: [https://github.com/magento/magespecialist_ReCaptcha/issues/21](https://github.com/magento/magespecialist_ReCaptcha/issues/21)
Thanks

**Comment by DanielRuf** [comment]
The invisible mode of reCaptcha is possibly used so this is normal then.

**Comment by michelecanal** [comment]
Hi @DanielRuf,
but when the recaptcha is not displayed and you fill the form, the result is "incorrect reCAPTCHA"

**Comment by michelecanal** [comment]
Hi,
I think I found a solution.
I'm using google recaptcha so I disabled the magento_captcha module. This is the cause of problem: can be?
Now I enabled it I seem work fine

bye

**Comment by DanielRuf** [comment]
@michelecanal is it a different issue compared to this one here (see the initial comment)? If so please create a new issue with all relevant details so we can reproduce and test it.

**Comment by michelecanal** [comment]
@DanielRuf Sorry: [https://github.com/magento/magento2/issues/19618](https://github.com/magento/magento2/issues/19618)
