### ISSUE TITLE
Region is always required when creating a new order in the Admin area

### ISSUE THREAD

**Issue by kevinboerland** [magento/magento2#17311]
### Preconditions

1.  Magento 2.2.5
2.  PHP 7.0.31
3.  MariaDB 10.1.29
4.  Apache 2.4.29
5.  Ubuntu 18.04

### Steps to reproduce

1. Have a clean Magento 2.2.5 install (composer create-project)
2. In the Admin area go to Sales -> Orders
3. Click "Create New Order"
4. Click "Create New Customer"
5. State/Province is mandatory as the selected country is United States
6. Change country to "The Netherlands" (Where state/province isn't mandatory)
7. State/Provice is still required

### Expected result

1. Region should only be required for countries that are selected in the "State is Required for" configuration option under Stories -> Configuration -> General -> General -> State Options.

### Actual result

1. Region is always mandatory when creating a new address from the "Create New Order" form.
2. This functionality works properly when creating a new address under Customers, adding a new Customer. ect.

The problem is most likely in this class:
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Block/Adminhtml/Edit/Renderer/Region.php#L51

* Line 51: always a required and _required CSS class
* Line 53: always a setRequired(true)
* Line 63: always a required-entry CSS class

If the above is true then this bug applies to all versions from 2.0 to 2.3

**Comment by magento-engcom-team** [comment]
Hi @kevinboerland. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@kevinboerland do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by WebWeave** [comment]
We are having this issue for a while already, its reproduceable on vanilla Magento 2.2.5.

**Comment by engcom-backlog-nickolas** [comment]
Hello @kevinboerland, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ma03lish** [comment]
We are having this issue aswell, it should honor the settings

**Comment by magento-engcom-team** [comment]
Hi @ankur-cedcoss. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by verma-ankur** [comment]
I am working on it #MM19IN

**Comment by madbounce** [comment]
Hey, I checked current issue on branch 2.3-develop and this issue not reproduced.
