### ISSUE TITLE
Magento 2 Checkout Page is Blank

### ISSUE THREAD

**Issue by lombokindustries** [magento/magento2#17317]
Magento 2 Checkout Page is Blank after installing Payment custom module. But when I remove it, the checkout page still blank. I need that payment custom module for development. 
The first test, it works until final order, but next, it doesn't..

Magento CE 2.2.5

module ref:https://www.classyllama.com/blog/how-to-create-payment-method-magento-2

**Comment by magento-engcom-team** [comment]
Hi @lombokindustries. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lombokindustries do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@lombokindustries, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
