### ISSUE TITLE
form_key cookie contain leading dot

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#17323]
### Preconditions

1. Fresh Magento 2.2.5 with sample data 
2. Multiple websites with different domain

### Steps to reproduce

1. Change the configuration to set the cookie for specific domain
2. Login in the backend with valid details
3. Store > Configuration > General
4. Change the website view to save the configuration for only website wise
5. Web Default Cookie Settings > Cookie Domain set your website domain (i.e magento.loc)
6. Set the cookie path to /
7. Save the configuration
8. clear cacher and clear browser cookies(for the current domain) and restart the browser

### Expected result

1. All Magento cookie should set the only domain without any leading dot but in the form_key cookie I can see it is adding a leading dot (and I don't want to set the cookie for subdomain as well)

<img width="1216" alt="screen shot 2018-07-30 at 13 59 40" src="https://user-images.githubusercontent.com/17308601/43575085-2d07779c-9646-11e8-9e82-d358da97e45d.png">

### Actual result

1. All the cookie as valid domain expect form_key cookie(which is adding leading dot)

**Comment by magento-engcom-team** [comment]
Hi @keyurshah070. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@keyurshah070 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@keyurshah070, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by SavchenkoVladimir** [comment]
#khcd2018

**Comment by magento-engcom-team** [comment]
@SavchenkoVladimir thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by mateuszkoscielniak** [comment]
Starting investigation #mm18pl

**Comment by magento-engcom-team** [comment]
@mateuszkoscielniak thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by kvydiuk** [comment]
#mageconf

**Comment by hammockvienna** [comment]
It would be great if someone could fix that. In my opinion that bug would mean that its not possible to use domains like news.com you always have to have a www.news.com
Thats currently a showstopper for us, but i cant fix that :-(
Issue is there also in Magento 2.3.2.

**Comment by prog7707** [comment]
still having this issue on magento version 2.2.8
I have a domain https://xyz.com/admin and subdomain https://test.xyz.com/admin
When i login to admin of these two domains, while i am working i get routed back to login page without loggin out, then i login again and i get notified other oppened session is expired.
can you please fix this are show how to fix it in v2.2.8

**Comment by krisdante** [comment]
As per modern RFC https://tools.ietf.org/html/rfc6265#section-4.1.2.3 trailing dot in the domain is ignored. Whenever the domain for the cookie is defined - it is visible also to subdomains.

Magento\Framework\Stdlib\Cookie\PhpCookieManager always adds a domain, either from settings or from a shop. There is no such option to not include it. 
We could assume that not setting domain for cookies is not sending Domain= parameter (which will lead to set cookie only for the current domain, without subdomains) - but this is a big breaking change. It would have to be release noted because I think most of the current users expect to have those cookies set also for subdomains. 

Alternatively, we could introduce a new switch in settings to do not send domain.

**Comment by krisdante** [comment]
I fixed that. The approach is described in pull request

**Comment by stkrelax** [comment]
the main problem even with your fix @krisdante is that the method 
clearSubDomainSessionCookie() will delete your own cookies, because 
            if ($this->sessionConfig->getCookieDomain() !== $host) {
will be true and delete ...

**Comment by kyleLPG** [comment]
This is most definitely still an issue

**Comment by kanevbg** [comment]
Magento 2.3.7-p2 sometimes generates (eg, after login) two cookies for form_key. PHPSESSID and privateData had a dot prefix and form_key had dot prefix too.

**Comment by mihaifaget1** [comment]
This is most definitely still an issue
