### ISSUE TITLE
Customer Can't Login Using Chrome - OK w/ Firefox Magento 2.2.4

### ISSUE THREAD

**Issue by freshweb** [magento/magento2#17322]
Using Chrome (67.0.3396.99 (64-bit) Mac) Customer login not working  - page just returns with empty fields.
Using Firefox (61.0.1 (64-bit)) login works as expected.
Using Safari ( 11.1.2) login works as expected.

### Preconditions

1. Magento CE 2.2.4
2. PHP 7.0.31
3. CentOS Linux 7.5.1804 (Core)‬
4. Proper domain name - co.uk
5. Magento setting - dev status
6. Cookie settings:
a) Cookie Lifetime: 86400
b) Cookie Path: /
c) Cookie domain: .name.co.uk
d) Use HTTP Only: Yes
e) Cookie Restriction Mode: Yes

### Steps to reproduce

1. Set up Magento CE 2.2.4 
2. Add customer data
3. Attempt Customer Login using Chrome

### Expected result

1. Expect customer to be redirected to customer dashboard
2. If I enter an incorrect password, I get the standard message ("YOU DID NOT SIGN IN CORRECTLY OR YOUR ACCOUNT IS TEMPORARILY DISABLED.") & the email field is still populated.

### Actual result

1. Login page refreshes with blank email/password fields.
2. There are no errors reported in console
3. In the system.log I'm seeing reports like this:
[2018-08-02 09:11:47] main.INFO: Broken reference: the 'sidebar.additional.top' tries to reorder itself towards '', but their parents are different: 'div.sidebar.additional' and '' respectively. [] []
However, nothing relating to login, etc.

**Comment by magento-engcom-team** [comment]
Hi @freshweb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@freshweb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@freshweb, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by freshweb** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @freshweb. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @freshweb, here is your [Magento instance](https://i-17322-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-17322-2-2-4.engcom.dev.magento.com/admin](https://i-17322-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by freshweb** [comment]
Works as expect on Luna template - looks like this is a custom template issue.
