### ISSUE TITLE
When using a template for \Magento\Framework\View\Element\Messages $interpretationStrategy is inaccessible

### ISSUE THREAD

**Issue by paulvandermeijs** [magento/magento2#17324]
### Preconditions

1. Magento 2.2.0

### Steps to reproduce

1. Create a template
```phtml
<div class="messages">
    <?php foreach ($block->getMessageTypes() as $type) : ?>
        <?php foreach ($block->getMessagesByType($type) as $message) : ?>
            <div class="alert-box <?= $type ?>"<?= $block->getUiId("message", $type) ?>>
                <?= $block->interpretationStrategy->interpret($message) ?>
            </div>
        <?php endforeach ?>
    <?php endforeach ?>
</div>
```
2. Update layout checkout_cart_index.xml to use this template in the cart for block checkout.cart.validationmessages
3. Generate an error (e.g. when an item is out of stock)

### Expected result

1. Messages are being displayed according to the template

### Actual result

1. An error is shown because `$interpretationStrategy` is private to `\Magento\Framework\View\Element\Messages`

**Comment by magento-engcom-team** [comment]
Hi @paulvandermeijs. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@paulvandermeijs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@paulvandermeijs why you think `<?= $block->interpretationStrategy->interpret($message) ?>` is a valid code? Do we have such syntax somewhere in templates instead of just calling block method?

**Comment by ghost** [comment]
@paulvandermeijs, thank you for your report.
This is not a bug. If you want to create a feature request, you can do it [here](https://github.com/magento/community-features/issues).

**Comment by paulvandermeijs** [comment]
@orlangur `$block->interpretationStrategy->interpret($message)` comes from the standard markup which is hardcoded into the class.

https://github.com/magento/magento2/blob/5a04525cba48627836cb5a554b7f23d17cbaba57/lib/internal/Magento/Framework/View/Element/Messages.php#L270-L293

It makes no sense that there is an option to use a template if you lose this functionality or are required to introduce a lot of business logic into the view to handle these messages. There should at least be an interface to access `$interpretationStrategy->interpret()` to maintain basic functionality when using a template.
