### ISSUE TITLE
Please reopen issue #14236

### ISSUE THREAD

**Issue by sebastian-enz** [magento/magento2#17326]
It does not seem anyone of engcom has noticed there is a huge bug in email functionality here: https://github.com/magento/magento2/issues/14236

The issue was closed a while ago and since then it seems like engcom didn't take a look at it anymore even though many people have since mentioned @magento-engcom-team and requested it to be reopened.

This is a valid issue that should be fixed. There are lots of stores affected by this issue.

Thank you and feel free to close/delete this issue then.

**Comment by magento-engcom-team** [comment]
Hi @ikk0. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ikk0 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by neddy236** [comment]
@magento-engcom-team issue is reproduced in magento 2.3.3(php73) and magento 2.3.2(php7.2) please reopen the issue
