### ISSUE TITLE
Grand total in the new Credit memo view is not updated when amounts are changed

### ISSUE THREAD

**Issue by orbitrod** [magento/magento2#17341]
This issue was originally reported here https://github.com/magento/magento2/issues/2386 but was labeled as a "Feature Requests and Improvements" and closed out.  However I believe this is incorrect.  This appears to be a bug in the Magento UI.  Because there is no obvious ability to refresh the grand total once the amount(s) in the `Refund Shipping`, `Adjustment Refund`, and/or `Adjustment Fee` fields have been changed.

### Preconditions

1.  Magento Version 2.2.3
2. Chrome Version 66.0.3359.181 (Official Build) (64-bit)

### Steps to reproduce

1. Issue credit memo against invoice.
2. Change the amount next to `Refund Shipping`, and/or `Adjustment Refund`, and/or `Adjustment Fee`.

### Expected result

1. Grand total should update automatically

### Actual result

1. Grand total does not update automatically and there is no button or feature that allows you to update the grand total.

### Workaround
1. Enter the desired amount(s) in the `Refund Shipping`, `Adjustment Refund`, and/or `Adjustment Fee`  fields.
2. Change the `Qty to Refund` qty for an item to another value.
3. Click `Update Qty's`
4. The grand total will now update with a new amount
5. Change the `Qty to Refund` qty for the item that was changed in step 2, back to the original value.
6. Click `Update Qty's`
7. The grand total should now reflect the correct total amount that you want to refund.

**Comment by magento-engcom-team** [comment]
Hi @orbitrod. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@orbitrod do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orbitrod** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @orbitrod. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @orbitrod, here is your [Magento instance](https://i-17341-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17341-2-2-3.engcom.dev.magento.com/admin](https://i-17341-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orbitrod** [comment]
Yes I was able to reproduce the issue on a vanilla Magento instance.

**Comment by ghost** [comment]
@orbitrod ,  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by khodu** [comment]
I have tried to reproduce this issue in 2.2.5 but issue is fixed in 2.2.5

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @orbitrod,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

Now we are having button with **update totals** so we can the amounts.

<img width="716" alt="Screenshot 2024-05-02 at 09 13 27" src="https://github.com/magento/magento2/assets/51680745/eb569087-3fcc-4550-b31c-5bb0130664c1">



Hence We are closing this issue.

Thanks.
