### ISSUE TITLE
Authorized.net "Sorry, but something went wrong. Please contact the seller." - only happens when using Android

### ISSUE THREAD

**Issue by yewtham** [magento/magento2#17345]
after hitting the place order button at final checkout page on the default chrome browser in an Android Phone - error  "Sorry, but something went wrong. Please contact the seller."  But transaction does go through on Authorize. net and order number generates. 

### Preconditions
Magento 2.2.5
PHP 7.0
MySQL 5.6
Any Android 6.0 - chrome browser

Expected result

Should see success landing page after pay.

Actual result

After clicking "placer order" with authorized.net i get that error everytime. So far i have used desktop windows, MAC, iphone, ipad with no errors. Only android phones give this problem.
 
[payment (1).log](https://github.com/magento/magento2/files/2255422/payment.1.log)
[exception (1).log](https://github.com/magento/magento2/files/2255423/exception.1.log)

Do anyone have a clue on how to fix it?

**Comment by magento-engcom-team** [comment]
Hi @yewtham. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@yewtham do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by yewtham** [comment]
give me 2.2.5 instance

**Comment by ghost** [comment]
@yewtham, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. Your problem is caused by third-party modules. This GitHub issue tracker is intended for Magento Core technical issues only.
