### ISSUE TITLE
Thousands (no hyperbole!) catalogrule_ tables

### ISSUE THREAD

**Issue by svlauer** [magento/magento2#17354]
I just noticed that my magento 2.2.4 database (data migrated with data-migration-tool from 1.9) contains a whopping 4642 tables.

The unexpected 4000+ tables all have names starting with "catalogrule_" (eg. "
"catalogrule_group_website0ab22656", "catalogrule_group_website0afe2ee1" ... "catalogrule_product1faca6cd", "catalogrule_product1f136f8a" ... there probably is one table per product?

All the tables are empty.

1. Is this normal? (This cannot be normal.)
2. Can I safely delete these tables?
3. How can I prevent these tables from being created in the future?

So far, there haven't be any problems with the operation of the site (which is still being set-up and not live).

**Comment by magento-engcom-team** [comment]
Hi @svlauer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@svlauer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by svlauer** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @svlauer. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @svlauer, here is your [Magento instance](https://i-17354-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-17354-2-2-4.engcom.dev.magento.com/admin](https://i-17354-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by svlauer** [comment]
It is impossible for me to verify whether this issue can be reproduced, since the test instance does not give me access to the database tables. 

The frontend and and backend of my installation work well (as does the test instance), the problem is with the creation of thousands of tables in the database.

**Comment by ghost** [comment]
@svlauer , thank you for your report. For migration issue please use this repository
https://github.com/magento/data-migration-tool
