### ISSUE TITLE
Fresh Magento 2.1.14, Readiness Check fail with conflicting component dependencies

### ISSUE THREAD

**Issue by allblued** [magento/magento2#17356]
[Summary of the issue]

My Magento is 2.1.14, fresh new. I am trying to install my first extension (Stripe payment extension), and this error occur.

===========================================
Check Component Dependency
We found conflicting component dependencies. Hide detail

For additional assistance, see component dependency help .

===========================================

As it doesn't show any useful information, I just want to know if anyone can help find the problem?

[Information of your environment]
=================
My php version is 5.6.37
Cron scripts are:

/usr/bin/php -c /etc/php5/fpm/php.ini /home/kuohua/www/online-store/bin/magento cron:run > home/kuohua/www/online-store/var/log/magento.cron.log
/usr/bin/php -c /etc/php5/fpm/php.ini /home/kuohua/www/online-store/update/cron.php > /home/kuohua/www/online-store/var/log/update.cron.log
/usr/bin/php -c /etc/php5/fpm/php.ini /home/kuohua/www/online-store/bin/magento setup:cron:run > /home/kuohua/www/online-store/var/log/setup.cron.log

[Steps to reproduce]
Just install a new magento 2.1.14, and try to install stripe payment extension.
https://marketplace.magento.com/stripeofficial-stripe-payments.html

[Expected and actual result]
I just want to successfully install the extension I need.

**Comment by magento-engcom-team** [comment]
Hi @allblued. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@allblued do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@allblued, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
