### ISSUE TITLE
misleading documentation

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#17351]
### Issue
Official documentation leads people to install a version of php which is not compatible with magento. Documentation should be changed to avoid this. 

### Preconditions
Proceed to install magento on a server with ubuntu, php 7.0 and nginx by following official documentation (see pages https://devdocs.magento.com/guides/v2.2/install-gde/prereq/nginx.html and https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html)

### Steps to reproduce
- Go to magento official guide at page https://devdocs.magento.com/guides/v2.2/install-gde/prereq/nginx.html to install magento 2.2 with nginx and php-fpm
- follow instructions, so install nginx with apt-get -y install nginx and then php-fpm with apt-get -y install php7.0-fpm php7.0-cli
- Run php -v in command line

### Expected result
I should see the latest stable version of php7.0 or at least one of the php 7.0 version compatible with magento

### Actual result
I see php 7.0.3 which, according to official documentation (https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html) is not compatible with magento.

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LouNik1984** [comment]
There's no need of a vanilla instance as it is an issue with the documentation, not magento per se

**Comment by ghost** [comment]
@LouNik1984, thank you for your report.
Please create an issue [here](https://github.com/magento/devdocs/issues).
