### ISSUE TITLE
?resource = frontend/Magento/luma/pt_BR/Magento_Ui/templates/form/element/helper/tooltip.html

### ISSUE THREAD

**Issue by dvcm** [magento/magento2#17355]
### Preconditions

1. Magento 2.2.5 
2. php version 5.6.30
3. Mysql version 5.6.32-78.1

### Steps to reproduce

1. When i go to checkout https://ilubrasileiro.com.br/onepage/, this page not loading this script 

2. Why does the script add this /?resource=

https://ilubrasileiro.com.br/pub/static/frontend/Magento/luma/pt_BR/Magento_Ui/templates/form/element/helper/tooltip.html/?resource=frontend/Magento/luma/pt_BR/Magento_Ui/templates/form/element/helper/tooltip.html

3. This script is there on the server.
public_html/pub/static/frontend/Magento/luma/pt_BR/Magento_Ui/templates/form/element/helper

![screen shot 2018-08-03 at 10 44 44](https://user-images.githubusercontent.com/2445325/43646103-52ad1816-970a-11e8-95d3-f9b21760e58c.png)

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

![screen shot 2018-08-03 at 10 38 14](https://user-images.githubusercontent.com/2445325/43645928-bf2e61c6-9709-11e8-9942-bf704df5642b.png)

**Comment by magento-engcom-team** [comment]
Hi @dvcm. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dvcm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dvcm** [comment]
To help us process this issue please make sure that you provided the following information:
  Summary of the issue
I am having problems in freight calculation, the installed script is not returning.
I do not understand why magento places this path /? Resource = frontend /

![screen shot 2018-08-03 at 11 59 11](https://user-images.githubusercontent.com/2445325/43651218-2afa2c42-9718-11e8-93eb-68e83466f0d0.png)
![screen shot 2018-08-03 at 11 59 26](https://user-images.githubusercontent.com/2445325/43651226-2f10a8b0-9718-11e8-897e-14ab1fc9a2db.png)
![screen shot 2018-08-03 at 11 59 35](https://user-images.githubusercontent.com/2445325/43651231-325bc022-9718-11e8-8810-dc0984364fce.png)


Is that correct? How do I get this path? or script is on the server.

I'm having problems with the folder
public_html / pub / static / frontend / Magento / luma / en_US / Magento_Tax / template / checkout / cart / totals /


Do the files become a folder and the script does not working.

![screen shot 2018-08-03 at 11 58 41](https://user-images.githubusercontent.com/2445325/43650996-9817646c-9717-11e8-928b-b1fce05d791b.png)
![screen shot 2018-08-03 at 12 04 40](https://user-images.githubusercontent.com/2445325/43651075-c23454d0-9717-11e8-8f85-249978c57e48.png)


  Information on your environment

would it be this
Magento 2.2.5
php version 5.6.30
Mysql version 5.6.32-78.1

Steps to Reproduce

enter the address ilubrasileiro.com.br
buy a product
test with zip code
From here the script does not calculate the freight ..

Expected and actual results

Calculate the freight and finalize the purchase, both by paypal and own onestepchekout.

Please make sure that the problem is playable on the instance of Magento Vanilla by following the steps to play. To deploy the Vanilla Magento instance in our environment, please add a comment to the problem:

@ magento-engcom-team gives me an instance {$ 2.2.5}

where {$ VERSION} are version tags (from 2.2.0+) or develop branching (2.2-develop +).
For more details, please review the Magento Contributor Assistant documentation.

@dvcm do you confirm that you were able to reproduce the problem on the instance of the Magento van by following the steps to reproduce?
Yes

**Comment by ghost** [comment]
@dvcm , thank you for your report. PHP 5.6.30 is not supported on Magento 2.2.x please check this Magento 2.2.x technology stack requirements
https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html
