### ISSUE TITLE
Issue a Partial Credit Memo for only a Bundle Item order Completes Order

### ISSUE THREAD

**Issue by arronmoss** [magento/magento2#17367]
### Preconditions

1. Fresh install of Magento 2.2.5
2. PHP 7.1

### Steps to reproduce

1. Configuration of some bundle products in Admin
2. Place an order for only a bundle
3. partial Ship
4. Attempt to credit the item but zero all products and attempt only to to a partial refund in the 'Adjustment Refund'. This is connected to another bug where entering zero for all bundle items causes the bundle to disappear, however if you manage to work around this for example by leaving a quantity on a bundle item of zero price, you get a partial credit memo BUT a Complete order.

### Expected result
1. A partial credit should result in a Processing Order

### Actual result
![image](https://user-images.githubusercontent.com/2673943/43683769-a3feef9c-988a-11e8-8748-08c44ffe194b.png)

After credit memo placed the order is Complete, this is NOT desired functionality as the order cannot be shipped.
![image](https://user-images.githubusercontent.com/2673943/43683777-cb826260-988a-11e8-9402-61a097d83a2b.png)

**Comment by magento-engcom-team** [comment]
Hi @arronmoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@arronmoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @arronmoss, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @arronmoss The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
