### ISSUE TITLE
Magento 2 Export Button CSV and XML Catalog Product Problem

### ISSUE THREAD

**Issue by ravikiranpullela** [magento/magento2#17386]
Summary of the issue:
I am adding an export button in product_listing.xml file to get an export functionality in Product->Catalog in admin side.
I am adding like exportButton name="export_button" in product_listing.xml
But getting error like:
 a:4:{i:0;s:51:"A joined field with this alias is already declared.";i:1;s:7545:"#0 D:\xampp\htdocs\dilmah\var\generation\Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor.php(947): Magento\Eav\Model\Entity\Collection\AbstractCollection->joinField('qty', 'cataloginventor...', 'qty', 'product_id=enti...', '{{table}}.stock...', 'left')
#1 D:\xampp\htdocs\dilmah\vendor\magento\module-catalog-inventory\Ui\DataProvider\Product\AddQuantityFieldToCollection.php(27): Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor->joinField('qty', 'cataloginventor...', 'qty', 'product_id=enti...', '{{table}}.stock...', 'left')

### Preconditions

1. magento - 2.1.13 enterprise edition
2.PHP - 7.0.21
3.mysql - 5.6.33

### Steps to reproduce

1. First goto any vanilla magento installed and goto vendor->magento->module_catalog->view->adminhtml->ui_component->product_listing.xml
2. In that file add the <exportButton name="export_button"/> below the line <columnsControls name="columns_controls"/> in that file.
3. Now you can see export button in product->catalog in admin side.
4.when we select any product and click on export,we are getting error.

### Expected result

1. when we click on export button in product->catalog,it should save all the products in csv format.

### Actual result

1.When we click on export butoon in product->catalog, it is throwing error.

a:4:{i:0;s:51:"A joined field with this alias is already declared.";i:1;s:7545:"#0 D:\xampp\htdocs\dilmah\var\generation\Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor.php(947): Magento\Eav\Model\Entity\Collection\AbstractCollection->joinField('qty', 'cataloginventor...', 'qty', 'product_id=enti...', '{{table}}.stock...', 'left')
#1 D:\xampp\htdocs\dilmah\vendor\magento\module-catalog-inventory\Ui\DataProvider\Product\AddQuantityFieldToCollection.php(27): Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor->joinField('qty', 'cataloginventor...', 'qty', 'product_id=enti...', '{{table}}.stock...', 'left')

![image](https://user-images.githubusercontent.com/40379308/43713702-25e8d2bc-9998-11e8-91ff-470fdc299504.png)

**Comment by magento-engcom-team** [comment]
Hi @ravikiranpullela. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ravikiranpullela do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ravikiranpullela** [comment]
yes you can reproduce in vanilla magento instance

**Comment by ghost** [comment]
@ravikiranpullela, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
