### ISSUE TITLE
CSV product export ignores stock filter

### ISSUE THREAD

**Issue by Floddy** [magento/magento2#17388]
### Preconditions
1. Magento 2.2.2
2. Product catalog with 'in stock' / 'out of stock' products

### Steps to reproduce
1. Go to system/data transfer/export
2. Chose entity type: products
3. In the 'quantity_and_stock_status' column, choose 'out of stock' / 'in stock', set checkbox.

### Expected result
The exported CSV excludes products that are out of stock / in stock.

### Actual result
The exported CSV contains all products, regardless of stock status.

**Comment by magento-engcom-team** [comment]
Hi @Floddy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Floddy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Floddy, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by pavelshulgabi** [comment]
I'm working on #cd-balance

**Comment by pavelshulgabi** [comment]
The issue reported was extensively investigated using 2.2-develop (2.2.6), successfully reproduced.
In terms of user expectation, the behaviour is weird but it aligns with the source code.

The import/export functionality is delivered via Magento_ImportExport module which consists of all basic models with common logic and attribute filtering. 
Magento also has entity specific modules for all major entity types. 
As part of this architecture, the product module has product_type-specific models. Each entity model has **_disabledAttrs** field which should consist of attribute codes which are ignored during import/export processes (most likely it was added to address some legacy issues at early days of Magento 2 development as commit dated 11/11/2015):
<img width="898" alt="screen shot 2018-08-11 at 14 31 54" src="https://user-images.githubusercontent.com/31196887/43988256-deec4d68-9d74-11e8-94b4-a6c584dc1ae3.png">

Config/bundle product models don't have any attributes in the list on the contrary to a simple product which has quantity attribute code in there:
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/CatalogImportExport/Model/Export/Product/Type/Simple.php#L40
<img width="554" alt="screen shot 2018-08-11 at 14 30 44" src="https://user-images.githubusercontent.com/31196887/43988254-d86362f6-9d74-11e8-8a8e-8eaab8d91458.png">

It means that during every import/export attempt this attribute will be ignored no matter customer added any specific filtering condition or not.

My advice would be to improve error messages/notes on the export page as well as a tooltip in UI to make sure everyone is aware of intentions and outcomes without any confusion.

**Comment by vteofilo** [comment]
This worked for me:

As I have a specific function to update inventory that extends \Magento\CatalogInventory\Model\StockRegistry, I called inside it, but if you use Magento itself you should create a plugin to be called after you have run the function **Magento\CatalogInventory\Model\StockRegistry::updateStockItemBySku()**. At each inventory update, this function updates the **is_in_stock** status of the parent product by adding the items of the child products:

`








    public function syncProductStock(int $productId)
    {
        $product = $this->productFactory->create();
        $product->load($productId);

        $productParent= $this->productFactory->create();
        $productParent->load(
            $this->objectManager->get(\Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable::class)
                ->getParentIdsByChild($productId)
        );

        $childrenIds = array_values(
            $this->objectManager->get(\Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable::class)
                ->getChildrenIds($productParent->getId())[0]
        );
        $sumQuantity = 0;
        foreach ($childrenIds as $childrenId) {
            $productChildren = $this->productFactory->create();
            $productChildren->load($childrenId);
            $sumQuantity += $this->objectManager->get(\Magento\CatalogInventory\Model\StockRegistry::class)
                ->getStockItem($childrenId)->getQty();
        }

        $isInStock = $sumQuantity > 0 ? 1 : 0;
        $product->addAttributeUpdate('quantity_and_stock_status', $this->getStockItem($productId)->getIsInStock(), $product->getStoreId());
        $productParent->addAttributeUpdate('quantity_and_stock_status', $isInStock, $product->getStoreId());

        $parentStockItem = $this->getStockItem($productParent->getId());
        $parentStockItem->setIsInStock($isInStock);
        $this->stockItemRepository->save($parentStockItem);
    }`

Hope this helps! Thank you!

**Comment by luanwebjump** [comment]
In my analysis, the problem occurs because when you save the product, this attribute does not change, but the is_in_stock column in the cataloginventory_stock_item table.
The export filter does not look at this table, but the catalog_product_entity_int attribute table, because the quantity_and_stock_status attribute. So we can understand that the problem is in the product save action .
@magento-engcom-team

**Comment by santhoshp** [comment]
I am working on it #MM19IN

**Comment by magento-engcom-team** [comment]
Hi @santhoshp. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by santhoshp** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @santhoshp. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @santhoshp, here is your [Magento instance](https://i-17388-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-17388-2-3-develop.instances.magento-community.engineering/admin](https://i-17388-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kkdg** [comment]
#mlau

**Comment by magento-engcom-team** [comment]
Hi @kkdg. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by kkdg** [comment]
@pavelshulga is correct in regards to the solution, this issue happens due to intention of core developers to disable the attribute for whatever reason I don't know, the only solution would be removing gaps between backend and frontend of product export feature by making a consensus of core developers. Who else now needs to be in charge of solving this? or if you want to revive the stock filter for product export, I will create PR by commenting the disabled attribute.
