### ISSUE TITLE
Where the relevant information about the template <!--ko-->

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1738]

**Comment by guz-anton** [comment]
> `<!-- ko -->`

is a part of Knockout templates syntax. Mostly such code used in [_Ui Components_](http://devdocs.magento.com/guides/v2.0/ui-library/ui-library-component.html)  in client-side templates. You could find in Magento box several `.html` files with it.

This funny comments used as alternative for node binding: `<div data-bind="..." />`, where presence of real DOM node not so suitable.

`<!-- ko <some_binding>: <object_of_options>, <another_binding>: <another_options> -->`
`<!-- /ko -->`

Syntax consist with little auxiliary part, `<some_binding>` name and `<object_of_options>` in JSON format.

List of Magento bindings could be found on [Magento2 Github](https://github.com/magento/magento2/tree/develop/app/code/Magento/Ui/view/base/web/js/lib/ko/bind).

More about Knockout templates and bindings: http://knockoutjs.com/documentation/binding-syntax.html

**Comment by LifeAsBook** [comment]
thank you！ i have found

**Comment by magento-engcom-team** [comment]
Hi @LifeAsBook. Thank you for your report. 
The issue has been fixed in magento/magento2#29433 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [36335422453af4abf58859acba7224cabe0f5e43](https://github.com/magento/magento2/commit/36335422453af4abf58859acba7224cabe0f5e43)
 - [651bd690cb0687565cc2a1e99a57d99be5e8f14c](https://github.com/magento/magento2/commit/651bd690cb0687565cc2a1e99a57d99be5e8f14c)
 - [8b592ee2005c4c324672b0b3f1f69307384c43c5](https://github.com/magento/magento2/commit/8b592ee2005c4c324672b0b3f1f69307384c43c5)
 - [3fc230358a246780d2595b6b2606b7b355af0665](https://github.com/magento/magento2/commit/3fc230358a246780d2595b6b2606b7b355af0665)
 - [e76cb954bd71db1d9d8f9ca5d229b139d9958424](https://github.com/magento/magento2/commit/e76cb954bd71db1d9d8f9ca5d229b139d9958424)
 - [1fe9c2268eafa22d1318d459297de3041a9425ca](https://github.com/magento/magento2/commit/1fe9c2268eafa22d1318d459297de3041a9425ca)
 - [de6d2a7ad9ecc1d58fbfd72aafbe8843934c123f](https://github.com/magento/magento2/commit/de6d2a7ad9ecc1d58fbfd72aafbe8843934c123f)

The fix will be available with the upcoming 2.4.1 release.
