### ISSUE TITLE
I get --> Deprecated Functionality: The each() function is deprecated. when run any magento command via ssh

### ISSUE THREAD

**Issue by enviengine** [magento/magento2#17397]
I get this Error when I run this code --> php bin/magento module:status
via ssh

Deprecated Functionality: The each() function is deprecated. This message will be suppressed on further calls in ../vendor/colinmollenhour/cache-backend-file/File.php on line 81

How to fixed it.

Magento version : Magento 2.2.5

@magento-engcom-team give me 2.2.5 instance
Best Regards.
Thank.

**Comment by magento-engcom-team** [comment]
Hi @enviengine. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@enviengine do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by simonworkhouse** [comment]
@enviengine This sounds like a PHP version issue and I believe that 2.2.5 requires 7.1 and it sounds like you might be running that command on 7.2. Confirm by running "php --version".

Your webserver may be configured to use 7.1 but the command line might be a different version. Locate the binary for the correct version and use that instead. I don't know where it would be on your system but it would be something like "/usr/bin/php7.1 bin/magento module:status"

**Comment by ghost** [comment]
@enviengine , thank you for your report.We were not able to reproduce this issue by following the steps you provided.Please provide more detailed steps to reproduce or try to reproduce this issue ona clean installation or latest release.

**Comment by enviengine** [comment]
@simonworkhouse  Thank you very much.  My server use PHP version is 7.2.8

`php --version

PHP 7.2.8 (cli) (built: Jul 18 2018 01:28:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies`

**Comment by orlangur** [comment]
@enviengine Magento `2.2.x` should not be used with PHP 7.2: https://github.com/magento/magento2/blob/2.2-develop/composer.json#L11

@simonworkhouse thanks for a quick investigation!
