### ISSUE TITLE
Featured Products on Catalog Product List Widget: Unknown column 'at_inchoo_featured_product_default.value' in 'where clause'

### ISSUE THREAD

**Issue by joinso** [magento/magento2#17390]
When you add a widget of "Catalog Product List" on some page, using "Featured Product" as a condition, the page show this error:

2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_inchoo_featured_product_default.value' in 'where clause', query was: SELECT DISTINCT  COUNT(DISTINCT e.entity_id) FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store2` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='2' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='143'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '2' AND price_index.customer_group_id = 0
 INNER JOIN `cataloginventory_stock_item` AS `at_stock_item` ON (at_stock_item.`product_id`=e.entity_id) AND (is_in_stock=1) WHERE (((IFNULL(`e`.`entity_id`, `at_inchoo_featured_product_default`.`value`) IN ('3567', '3756', '2063', '3348', '3351', '3389', '3535', '3669', '3766', '3802', '3978', '4009', '2580', '2604', '2605', '2606', '3064', '3456', '4037', '4040', '2789', '2905', '2907', '3065', '3274', '3464', '3700', '3785', '3807', '4065', '3511', '3531', '3326', '3422', '3650', '3651', '3659', '3663', '3886', '3887', '3891', '3917', '4008', '4001', '2210', '2977', '2978', '3193', '3393', '3394', '3596', '3634', '3691', '3696', '3786', '4000', '4017')) ))
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_inchoo_featured_product_default.value' in 'where clause'

### Preconditions

1. Magento version: 2.2.5
2. PHP version: 7.0.30
3. MySQL version: 5.6.34

### Steps to reproduce

1. Just add a "Catalog Product List" widget in a CMS page, and add the condition of "Featured Product".

### Expected result

1. A list of product filtered by featured_product.

### Actual result
An exception is thrown ...: unknow column...

Regards,
Jordi
JOINSO

**Comment by magento-engcom-team** [comment]
Hi @joinso. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@joinso do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@joinso, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by joinso** [comment]
Is this not an issue?
This is related to feature of Magento...

Regards,
Jordi
JOINSO
