### ISSUE TITLE
shipping information API validation 

### ISSUE THREAD

**Issue by kandarp26** [magento/magento2#17403]
### Preconditions

1. Magento 2.2.2 

### Steps to reproduce

1. Generate cart using POST rest/V1/guest-carts
2. Add product to cart POST rest/V1/guest-carts/[cart-id]/items
**REQUEST** 
`
{
  "cartItem": {
    "sku": "[sku]",
    "qty": 1,
    "quote_id": "[cart-id]"
  }
}
`
3. Make a request to endpoint POST rest/V1/guest-carts/[:cart-id]/shipping-information 
**REQUEST** 
```
{
  "addressInformation":{
    "shippingAddress":{
        "country_id":"IN",
        "region":"XYZ",
        "region_id":0,
          "street":["test"],
        "telephone":"99040503256",
          "postcode":"1234",
        "city":"",
        "firstname":"Kandarp",
        "lastname":"Patel",
        "middlename":"Test"
    },
    
    "shipping_method_code":"flatrate",
    "shipping_carrier_code":"flatrate"
  }
}

````

### Expected result

1. API should not allow the save shipping address as city is blank. 

### Actual result

1. API allow to save save shipping address.

**Comment by magento-engcom-team** [comment]
Hi @kandarp26. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@kandarp26 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@kandarp26 ,  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by KishorkumarKar** [comment]
I am working on this issue #mm19in

**Comment by magento-engcom-team** [comment]
@KishorkumarKar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @KishorkumarKar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Bravarg** [comment]
Address validation was removed by resolving internal ticket MAGETWO-48531 in commit https://github.com/magento/magento2/commit/68457cfc63af38bfa47da35c7473a5b4153f67e0
I think @sidolov can advice with it.
CC: @ishakhsuvarov 

At this moment, only country_id is required field setting shipping address and getting payment methods in response.
