### ISSUE TITLE
Magento 2.2.4 condition type "like" with integer values

### ISSUE THREAD

**Issue by airammateos** [magento/magento2#17411]
**Summary of the issue**
I'm starting to use Magento 2.2.4 API following the instructions defined [here](https://devdocs.magento.com/guides/v2.2/rest/performing-searches.html). Exactly I'm trying to build a logic OR statement to get products by sku or name.
If I search for sku with integer values, no data is returned despite the existence of the sku.

**Information on your environment**
Magento 2.2.4

**Steps to reproduce**
Make a request to endpoint GET `/V1/products?fields=items[sku,name]&searchCriteria[filterGroups][0][filters][0][field]=sku&searchCriteria[filterGroups][0][filters][0][value]=%250001%25&searchCriteria[filterGroups][0][filters][0][condition_type]=like`

**Expected and actual results**
The expected result is an object with the product 0001, but no product is returned.

It's something wrong in my searchCriteria query?

I hope I've indicated all the information you need.
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @airammateos. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@airammateos do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@airammateos, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
