### ISSUE TITLE
Product image zoom (magnifier) is broken in Safari

### ISSUE THREAD

**Issue by dannynimmo** [magento/magento2#17416]
### Preconditions

1. Magento 2.2.3
2. PHP 7.1
3. Theme which enables the magnifier in `etc/view.xml` (Luma does not)
4. Safari browser v11.1.2
5. Remote environment (issue does not exist on local environments)

### Steps to reproduce

1. Browse to product detail page with a large image
2. Click the image to open the fullscreen gallery
3. Click on the "zoom in" button

### Expected result

Image is zoomed in larger, user can see more detail

### Actual result

Image does not zoom in

**Comment by magento-engcom-team** [comment]
Hi @dannynimmo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dannynimmo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @dannynimmo. Thank you for your report. 
The issue has been fixed in magento/magento2#17426 by @dannynimmo in 2.3-develop branch
Related commit(s):
 - [5994832f6c1e5cbfc228390c846f7b6ec7beca21](https://github.com/magento/magento2/commit/5994832f6c1e5cbfc228390c846f7b6ec7beca21)

The fix will be available with the upcoming 2.3.0 release.

**Comment by pavelshulgabi** [comment]
@dannynimmo 

Can you please advise on how were you testing the issue (any custom theme magnifier specific customisations)? I was trying to reproduce the problem reported using 2.2-develop (2.2.6) using Luma theme with enabled magnifier (Safari 11.1.2).

**Comment by magento-engcom-team** [comment]
Hi @dannynimmo. Thank you for your report. 
The issue has been fixed in magento/magento2#17491 by @dannynimmo in 2.2-develop branch
Related commit(s):
 - [0f591515b5efbe71665b32220d74384a1efd667e](https://github.com/magento/magento2/commit/0f591515b5efbe71665b32220d74384a1efd667e)

The fix will be available with the upcoming 2.2.7 release.
