### ISSUE TITLE
Sales Order Create Load Block populates wrong reference container

### ISSUE THREAD

**Issue by Orstio** [magento/magento2#17417]
In vendor/magento/module-sales/view/adminhtml/layout/sales_order_create_index.xml, the "data" block:

<block class="Magento\Sales\Block\Adminhtml\Order\Create\Data" template="Magento_Sales::order/create/data.phtml" name="data">

Is directly beneath the "order_create_form" block.

In vendor/magento/module-sales/view/adminhtml/layout/sales_order_create_index.xml, the same block is under the "content" container instead.

The placement of the data block needs to be consistently inside the form in order for the form and page load to work correctly in all instances.

### Preconditions
Preconditions are a bit strange for this one, because in Magento core itself, this issue is probably not noticed.  But, when you create a quote in a third party extension and then try to convert that quote to an order, it becomes apparent.

### Steps to reproduce
Create a quote, either directly in the database or through other third party means, and then attempt to convert the quote to order in the Magento admin panel.

### Expected result
1. Because the quote should already have a store/website assigned, you should be taken directly to the sales order create/edit page, and instead you are faced with the website selection page.  
### Actual result

1. After selecting a website, the sidebar on the sales order create page is duplicated due to the bug in the XML.

**Comment by magento-engcom-team** [comment]
Hi @Orstio. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Orstio do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Orstio** [comment]
As I said, it is probably not reproducable on a vanilla installation.  That does not mean that there is no bug, just that it is not noticable in the vanilla workflow.

What I am reporting is an inconsistency in the two XML files, sales_order_create_index.xml and sales_order_create_load_block.xml.  Any developer looking at this will immediately see the error.

This needs to be fixed for ease of third party development.

All I had to do to fix was change line 11 of the sales_order_create_load_block_data.xml to:

`<referenceContainer name="order_create_form">`

So that it matched the sales_order_create_index.xml and it fixed everything.

**Comment by ghost** [comment]
@Orstio , Thank you for your report. Please refer to the [Community Forums](https://community.magento.com/)or the [Magento Stack Exchange](https://magento.stackexchange.com/) site foradvice or general discussion about this issue. The GitHub issue tracker isintended for Magento Core technical issues only.
