### ISSUE TITLE
Middle Mouse Button Scrolling

### ISSUE THREAD

**Issue by tuushay** [magento/magento2#17429]
### Preconditions

1. Magento 2.2.5 with sample data installed.

### Steps to reproduce

1. When you open up the Men -> Tops category page on front-end, you can't scroll by clicking and dragging the middle mouse button (autoscrolling option for firefox).
2. When you remove the layered navigation from the page, scrolling works again.
Code used for removing layered navigation : 
`<referenceContainer name="catalog.leftnav" remove="true"/>`

### Expected result

1. Middle mouse button scrolling should work for all pages.
2. I have checked most of the available demo online and they have the same problem.

### Actual result

1. It works on some pages and doesn't on others.

**Comment by magento-engcom-team** [comment]
Hi @tuushay. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@tuushay do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@tuushay, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by fyrik** [comment]
#lviv-meetup

**Comment by magento-engcom-team** [comment]
@fyrik thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by bluemwhitew** [comment]
#mm18hr

**Comment by magento-engcom-team** [comment]
@bluemwhitew thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @andrewbess. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by andrewbess** [comment]
Hello @tuushay 
I cannot reproduce this bug on Magento 2.2 using Linux Ubuntu and Firefox 63.0.
Please specify your operating system.

**Comment by TomashKhamlai** [comment]
According to this document https://devdocs.magento.com/guides/v2.2/mtf/mtf_quickstart/mtf_quickstart_environment.html
Firefox 45.0 ESR is still supported browser.

![not_fixed](https://user-images.githubusercontent.com/11827230/48494602-e4d76700-e836-11e8-9285-b28a29480105.gif)

**Comment by TomashKhamlai** [comment]
@sidolov, please check.

**Comment by magento-engcom-team** [comment]
@tuushay, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Comment by 1ci** [comment]
I'm having this issue on Magento 2.3.4

Middle click scroll works on the pages that are linked in the footer (Search Terms, Contact Us, Orders and Returns) **and on a product page**.

But it **doesn't** work on the home page and catalog (product listing)

I'm using:
- Varnish 6.2.2
- Redis 5.0.7
- Elasticsearch 6.8.6
- RabbitMQ 3.8.2
- MariaDB 10.2.31
- nginx 1.16.1
- php 7.2.11
