### ISSUE TITLE
Wrong tax is displayed in checkout for Virtual products

### ISSUE THREAD

**Issue by navarr** [magento/magento2#17425]
Under certain scenarios the tax displayed in checkout for a virtual product does not match the address selected by the billing method

### Preconditions

1. Magento 2.2.6-dev installed
-- **Updated(09/19/2019):** Still actual on `2.3-develop`
-- **Updated(02/15/2021):** Modified for similar issue on `2.4-develop`
2. Default Tax rates configured (typical of a clean installation)
3. Addition of a Tax Rule that enables those rates
![virtual-product-setup](https://user-images.githubusercontent.com/145128/43797782-9110a9a2-9a56-11e8-8307-eccf6f102768.png)
4. A virtual product created with price point $10

### Steps to reproduce

1. Create a customer account
2. Create a default billing & shipping address in New York, such as:
123 Main St
Flushing, NY 11354
3. Save
3. Browse to category to add Virtual product to cart
4. Proceed to checkout
5. Note sales tax of $0.84
6. Click "Edit" under the billing address
7. Click "Update"
6. Press back till you are no longer in checkout
7. Go to customer account page
8. Edit Address, set it to an address in California such as:
1 Main St
San Jose, CA 95131
9. Save
10. Click Mini-cart and click "Proceed to Checkout"

[Video Recreation](https://youtu.be/gG4GPfX8cDg)

### Expected result

1. Sales tax of $0.83 (calculated off California address)

### Actual result

1. Sales tax of $0.84 (calculated off New York address)

### Notice

* Clicking a payment method in the checkout will show the California address as the selected address, despite showing the New York tax)
* After observing the results, if you go back to the cart and click "Update Cart" and then proceed to checkout, the correct sales tax will be displayed

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@navarr do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by navarr** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @navarr, here is your [Magento instance](https://i-17425-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17425-2-2-develop.engcom.dev.magento.com/admin](https://i-17425-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@navarr , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by navarr** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by navarr** [comment]
I've updated the issue with slightly different recreation steps for 2.4; as the original issue was fixed

**Comment by navarr** [comment]
There hasn't been a non-patch release since the last time I confirmed this issue.  I don't believe it's qualified to be stale yet

**Comment by Den4ik** [comment]
@magento I'm working on it

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @navarr,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Hence We are closing this issue.


**Steps to reproduce**

- Create a customer account
- Create a default billing & shipping address in New York, such as:
- 123 Main St
- Flushing, NY 11354
- Save
- Browse to category to add Virtual product to cart
- Proceed to checkout
- Note sales tax of $0.84
- Click "Edit" under the billing address
- Click "Update"
- Press back till you are no longer in checkout
- Go to customer account page
- Edit Address, set it to an address in California such as:
- 1 Main St
- San Jose, CA 95131
- Save
- Click Mini-cart and click "Proceed to Checkout"


<img width="1428" alt="Screenshot 2024-05-03 at 12 15 20" src="https://github.com/magento/magento2/assets/51680745/d26aa8d1-0a68-4c0e-ae74-32af3b511ce8">

**Comment by navarr** [comment]
@engcom-Bravo doesn't that screenshot show that you recreated the issue? If the tax rates are still the same, it's showing new York tax for a California address
