### ISSUE TITLE
Not update installment price on product configuration change (Product Page)

### ISSUE THREAD

**Issue by patrickcavalheiro** [magento/magento2#17427]
I created a template to display the installment price of the product, on the product page. I need to update this price when the user clicks the configurable product option.

I created a preference for "Magento\ConfigurableProduct\Block\Product\View\Type\Configurable" to create a new price_type_code but debugging the product page does not pass through the getJsonConfig method.

I also created a preference for "Magento\Catalog\Block\Product\View\Options" and debugging the product page also does not go through _getPriceConfiguration.

Where should I enter the values for each configurable product option?

Magento ver. 2.2.3 + PHP Version 7.0.28 + Mysql5.6

Thanks

**Comment by magento-engcom-team** [comment]
Hi @patrickcavalheiro. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@patrickcavalheiro do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@patrickcavalheiro , please refer to the [Community Forums](https://community.magento.com/)or the [Magento Stack Exchange](https://magento.stackexchange.com/) site foradvice or general discussion about this issue. The GitHub issue tracker isintended for Magento Core technical issues only.
