### ISSUE TITLE
Database fields corrupt default values

### ISSUE THREAD

**Issue by Michal-sk** [magento/magento2#1742]
When creating a fresh installation, than try to export / dump the database and import the dump in another database. It is not possible because a lot of tables give back the following error ```
TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause``` explanaition: http://stackoverflow.com/a/267675

In magento we have a pretty amount of tables with this issue, i think i saw around 25

**Comment by Michal-sk** [comment]
Mmm, i have a to old mysql version i think... Sorry for this issue.

**Comment by magento-engcom-team** [comment]
Hi @Michal-sk. Thank you for your report. 
The issue has been fixed in magento/magento2#29493 by @jmonteros422 in 2.4-develop branch
Related commit(s):
 - [faf1de2fffd71704f1c63c5390c634387f579690](https://github.com/magento/magento2/commit/faf1de2fffd71704f1c63c5390c634387f579690)

The fix will be available with the upcoming 2.4.1 release.
