### ISSUE TITLE
feature request: make _calcHeight and _isOverflowed of minicart sidebar.js optional

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#17433]
### Preconditions

1. add more than 6 items to the cart
2. open the minicart
3. all current Magento versions (2.2.4+, 2.3, 2.1.x)

### Steps to reproduce

1. open the minicart
2. the 
3. 

### Expected result

1. an option to disable both methods to prevent the calculated height / scroll

### Actual result

1. I can not disable these options without overwriting sidebar.js

I think it also makes sense to optionally support some maxHeight value instead of maxItems value as some items have many lines of text in the name in some shops (long product names which include product attributes) so 65 items for example could also take much height. When we make both optionally we can use CSS values however we want to.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@DanielRuf do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @DanielRuf, thank you for your report. Could you please add more clear steps to reproduce, expected and actual results? Also, please specify magento version.

**Comment by DanielRuf** [comment]
> add more than 6 items to the cart
> open the minicart

**Comment by DanielRuf** [comment]
It is a feature request. The information is all there, I added some more.

**Comment by engcom-backlog-nickolas** [comment]
@DanielRuf, thanks for reply. Please use https://github.com/magento/community-features for suggestions like improvements or feature requests.

**Comment by DanielRuf** [comment]
This issue was meant for me as contributor and possible future maintainer to create a PR. I will reopen it for me.

**Comment by ishakhsuvarov** [comment]
@DanielRuf You might as well create a PR and link the issue from another repository ;)

**Comment by DanielRuf** [comment]
> @DanielRuf You might as well create a PR and link the issue from another repository ;)

That's my plan, to link my future PR to this issue here.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for the report. We are moving your feature request to the special project. You can track this issue here: https://github.com/magento/community-features/issues/83
