### ISSUE TITLE
Order getCreatedAtFormatted has bad params

### ISSUE THREAD

**Issue by patoch14** [magento/magento2#17442]
### Preconditions

1. Magento CE 2.2.5

### Steps to reproduce

1. On any order, call getCreatedAtFormatted($format)
2. Set string format as expected (short|medium|long|full)

### Expected result

1. It should return order's createAt formated

### Actual result

1. PHP Fatal error:  Uncaught TypeError: IntlDateFormatter::__construct() expects parameter 2 to be integer, string given in  vendor/magento/framework/Stdlib/DateTime/Timezone.php:322

There is no conversion between format (string) in order model, and dateType/timeType (integer) in TimezoneInterface.

**Comment by magento-engcom-team** [comment]
Hi @patoch14. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@patoch14 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @patoch14, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by yogeshsuhagiya** [comment]
Hi @patoch14,
Do not pass the string value to `getCreatedAtFormatted` method like `short`, `medium`, `long` and `full`  because it takes integer value like 0,1,2,3.

Use constant of PHP's `IntlDateFormatter` class to pass value.
For example,
`$order->getCreatedAtFormatted(\IntlDateFormatter::SHORT);`

http://php.net/manual/en/class.intldateformatter.php

**IntlDateFormatter::FULL (integer)**
- Completely specified style (Tuesday, April 12, 1952 AD or 3:30:42pm PST)

**IntlDateFormatter::LONG (integer)**
- Long style (January 12, 1952 or 3:30:32pm)

**IntlDateFormatter::MEDIUM (integer)**
- Medium style (Jan 12, 1952)

**IntlDateFormatter::SHORT (integer)**
- Most abbreviated style, only essential data (12/13/52 or 3:30pm)

**Comment by magento-engcom-team** [comment]
Hi @patoch14. Thank you for your report. 
The issue has been fixed in magento/magento2#19537 by @jaimin-ktpl in 2.3-develop branch
Related commit(s):
 - [4a1d103ae910f8277deca275cf4cbe60adffa315](https://github.com/magento/magento2/commit/4a1d103ae910f8277deca275cf4cbe60adffa315)

The fix will be available with the upcoming 2.3.1 release.
