### ISSUE TITLE
Configurable Product Pricing Updating Incorrectly

### ISSUE THREAD

**Issue by ryan-copeland** [magento/magento2#17447]
### Summary

When configuring a configurable product that has 2 configurable attributes the from price does not update when the first attribute is configured.

### Preconditions
1. Magento Commerce 2.2.5 / Magento Open Source 2.2.5
2. Create a configurable product that is configurable by 2 attributes e.g. colour and size. Let's say for this instance that the product is available in the colours Red, Yellow and Blue. Red come in Small and Medium size, Yellow come in Medium and Large size and Blue only comes in Large. The colour attribute should be configured before the size attribute. Ensure that the prices set for each size are different (small: £10, medium: £20, large: £30).  

### Steps to reproduce
1. Navigate to the configurable product page.
2. Select the colour Red. The price will say "From £10".
3. Select the colour Yellow. The price will say "From £10". 
4. Select the colour Blue. The price will say "From £30".

### Expected result
1. Navigate to the configurable product page.
2. Select the colour Red. The price will say "From £10".
3. Select the colour Yellow. The price should say "From £20".
4. Select the colour Blue. The price will say "From £30".

### Actual result
1. Navigate to the configurable product page.
2. Select the colour Red. The price will say "From £10" because the cheapest product for Red is a small which is £10.
3. Select the colour Yellow. The price will say "From £10". This is incorrect as prices for this colour start from £20 as there is no small variant for this colour.
4. Select the colour Blue. The price will say "From £30". This is correct but only because the size has a single option.

### Investigation

In the file vendor/magento/module-configurable-product/view/frontend/web/js/configurable.js I found the following on line 468:

`if (config && config.allowedProducts.length === 1 && !hasProductPrice) {
                    priceValue = this._calculatePrice(config);
                    hasProductPrice = true;
                }`

It seems that the price on the page is only being updated if there is a single product in the allowedProducts array. 

What I think should happen is that it gets the lowest price from all the products in the allowedProducts array and updates the price on the product page accordingly.

Hopefully that all makes sense and let me know if you need any more information around this.

**Comment by magento-engcom-team** [comment]
Hi @ryan-copeland. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ryan-copeland do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ryan-copeland** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ryan-copeland. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ryan-copeland, here is your [Magento instance](https://i-17447-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17447-2-2-5.engcom.dev.magento.com/admin](https://i-17447-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ryan-copeland** [comment]
Yes, this is on a vanilla Magento.

**Comment by ghost** [comment]
@ryan-copeland , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @janakbhimani. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @janakbhimani. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by janakbhimani** [comment]
Hi @engcom-backlog-andrii,

I need your suggestion regarding this issue, my query is without selecting the configurable product available attribute combination price will not update, I mean if you select only one attribute (size or color) the "As low as" price remain as it is, 

When we select the combination of available attributes at that time "As low as" price will updated, so what exactly need to fix in this issue.

**Comment by magento-engcom-team** [comment]
Hi @janakbhimani. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by asifashi1** [comment]
Hi everyone I have added a configured product in Magento 2.3.1 and facing pricing issue. When I look product from the front end price showing look like this.
Attribute product: Flavours
1. Blueberry 1 Donut
2. Blueberry pack of 21 +AED20 (This second attribute title showing first and 2nd attribute price difference)

Please help me how can I resolve this.
You can also visit the sample page: https://capitalbays.com/alasature-protein-doughnuts-2.html
