### ISSUE TITLE
wishlist product already remove from account page still display in wishlist on product page when FPC is on 

### ISSUE THREAD

**Issue by Rutvee123** [magento/magento2#17459]
### Summary of the issue
when product remove from wishlist on the my wishlist page still displayed on wishlist on product detail page when FPC is on

### Information on your environment
php version: 7.0.29
mysql:mysqlnd 5.0.12
magento 2.2.3

### Steps to reproduce:
any product add to wishlist:
go to my wishlist page
remove product from the wishlist
now go to this product detail page
product still display with red symbol

### Expected result:
Product should be removed from the wishlist

### Actual result
product stayed in wishlist

**Comment by magento-engcom-team** [comment]
Hi @Rutvee123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Rutvee123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Rutvee123** [comment]
I have set with code format and yes is  reproducible on vanila  2.2.3

**Comment by ghost** [comment]
@Rutvee123, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Step "product still display with red symbol" clearly marks you are using some custom code. If you'd like to update this issue, please reopen it.

**Comment by Rutvee123** [comment]
Please check in this demo 
http://demo-acm2.bird.eu/
is still remain also in demo version and vanila too

**Comment by ghost** [comment]
@Rutvee123, can't reproduce your issue on demo store. Please record a video.
