### ISSUE TITLE
Maximum execution time of 300 seconds exceeded while upgrade from 2.2.2 to 2.2.5

### ISSUE THREAD

**Issue by ttmuangkeo** [magento/magento2#17455]
I am upgrading a website from Magento 2.2 to 2.5 and running into an error. I read through a lot of threads and forums but nothing is working. This includes adding

max_execution_time 60000, set_time_limit(0) in my php.ini

I am using Cloudways and they said any PHP directives defined in a .htaccess will not be used. To use PHP-FPM Settings.
### Preconditions

1. Magento 2.2.2
2. PHP 7.0
3. SQL 5.7
4. Cloudways server

<img width="427" alt="screen shot 2018-08-06 at 4 01 38 pm" src="https://user-images.githubusercontent.com/25596789/43868763-0e74ad9e-9b24-11e8-9c6e-081c5d84d697.png">

### Steps to reproduce

1. composer require magento/product-community-edition 2.2.5 --no-update
2. composer update
3. rm -rf var/di/* var/generation/* var/cache/* var/log/* var/page_cache/* var/session/* var/view_preprocessed/* pub/static/*
4. php bin/magento setup:upgrade

### Expected result

1. upgrade runs and Magento version should 2.2.5

### Actual result

I get an error saying:
The maximum execution time of 300 seconds exceeded in /file path to error/. **File path changes every time I run setup:upgrade**

![screen shot 2018-08-07 at 4 53 28 pm](https://user-images.githubusercontent.com/25596789/43868769-1da17bb2-9b24-11e8-97a0-461556e99622.png)

**Comment by magento-engcom-team** [comment]
Hi @ttmuangkeo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@ttmuangkeo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ttmuangkeo** [comment]
@magento-engcom-team give me 2.2.2 instance

**Comment by magento-engcom-team** [comment]
Hi @ttmuangkeo. Thank you for your request. I'm working on Magento 2.2.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ttmuangkeo, here is your [Magento instance](https://i-17455-2-2-2.engcom.dev.magento.com).
Admin access: [https://i-17455-2-2-2.engcom.dev.magento.com/admin](https://i-17455-2-2-2.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ttmuangkeo** [comment]
@magento-engcom-team yes

**Comment by orlangur** [comment]
@ttmuangkeo,
> The maximum execution time of 300 seconds exceeded

You need to change PHP settings properly in `php.ini` corresponding to PHP CLI, Magento cannot do anything about such misconfiguration.

GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.
