### ISSUE TITLE
2 Checkout doesn't work with terms and conditions

### ISSUE THREAD

**Issue by adolfobushi** [magento/magento2#17453]
The payment method 2checkout doesn't work when terms and conditions is enabled.

### Preconditions

   Magento 2.2.5 
   PHP 7.0 or 7.1
   2 checkout Express enabled in-checkout payment methods
   Checkout Agreements created and required

### Steps to reproduce
 Attempt to check out with 2checkout  with the agreements box checked

### Expected result
 Proceed to 2checkout checkout as normal

### Actual result
1. [Screenshots, logs or description]
 A  validation error is returned whether or not the agreement box is checked.

**Comment by magento-engcom-team** [comment]
Hi @adolfobushi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@adolfobushi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@adolfobushi, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
