### ISSUE TITLE
CMS module does not implement extension attributes

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#17458]
Currently the entities provided by the CMS module do not allow the use of extension attributes. Is there a reason for this? Or is it on the roadmap to add this functionality?

### Preconditions

1. Magento 2.x

### Steps to reproduce

1. Try to add an extension attribute to `Magento\Cms\Model\Page`.

### Expected result

1. Extension attributes should be added / registered to the model.

### Actual result

1. They're not

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@kanduvisla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@kanduvisla, thank you for your report.
We've acknowledged the issue and added to our backlog.
