### ISSUE TITLE
Customer non-default addresses' post codes do not change on leading zero

### ISSUE THREAD

**Issue by Orstio** [magento/magento2#17452]
### Preconditions

1. Magento 2.2.4
2. Create a customer with at least 3 addresses.  The non-default address should have a post code that is only 4 numbers.

### Steps to reproduce

1. Edit the customer addresses in the admin panel, and add a leading zero to the post code of the address that is not a default billing or shipping address.
2. Save the customer.
3. Look at the address to confirm the post code did not change.

### Expected result

1. Post code should change to whatever was entered.

### Actual result

1. Post code does not change.

I tested and this works the opposite way as well:  If the post code has a leading zero and you remove it and save, it retains the leading zero.  So, it seems to be equating 01111 = 1111 and ignoring it, regardless of which side of the equation it's on.  You can also change it to an entirely different value (e.g. 22222) and that works as expected.  The issue is just changing it from a leading zero or to a leading zero, and only on non-default addresses.

**Comment by magento-engcom-team** [comment]
Hi @Orstio. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Orstio do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Orstio** [comment]
Yes, this is on a vanilla Magento.

**Comment by engcom-backlog-nickolas** [comment]
Hello @Orstio, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by gelanivishal** [comment]
@Orstio I didn't replicate this issue while placing order and save a new address on address book, Please check screenshot.
Please try again and If possible then please create a video.

![2018-08-11_16-01-17](https://user-images.githubusercontent.com/12389799/43990902-ddf342f8-9d7f-11e8-8228-8facbce93178.jpg)
![2018-08-11_16-00-43](https://user-images.githubusercontent.com/12389799/43990903-dea91aa6-9d7f-11e8-893d-3e69e1b6fc57.jpg)


Thank you.

**Comment by Orstio** [comment]
Oh, I see, you did it on the frontend, and I didn't specify it's in the admin panel.

**Comment by magento-engcom-team** [comment]
@Orstio, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
