### ISSUE TITLE
Magento 2 : Product Price on website does not change

### ISSUE THREAD

**Issue by bhavikapatelgm** [magento/magento2#17461]
### Preconditions

1. Magento version 2.2.4 

### Steps to reproduce

1. Add 1 configurable product 
2. While adding the product add 2 new configurable attributes  (Model , Thickness both of type Textual Swatch) 
3. Add 3 simple products for this configurable product 
4. Each product has 3 Swatches color, Thickness and model. 
5. Price of product different for three different model whereas color and thickness is same across all three prodcuts

### Expected result

1. On product detail page it should  change the prices of the product when clicking on model only 

### Actual result

1. On product detail page it changes prices of product when Model + Color + Thickness is clicked, else it keeps showing 1 price for all

**Comment by magento-engcom-team** [comment]
Hi @bhavikapatelgm. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@bhavikapatelgm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@bhavikapatelgm, thank you for your report.
Please provide more clear steps to reproduce, expected and actual results, or record a video.

**Comment by bhavikapatelgm** [comment]
http://techrack.graymatrix.com/index.php/ipad-pro-supreme-glass-screen-protector.html

Above is the link of my development website.

Hhere : ipad pro 9.7 prie is 1999, ipad 10.5 is 2199 and ipad 12.9 is 2399.

Unless i select color (Crystal), model and thickness it wont change the 
price.

**Comment by ghost** [comment]
@bhavikapatelgm, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by routbiplab** [comment]
Since you have made that product using 3 different attributes and hence all are mandatory so you need to select at least one value from each of the attribute which will make a product.

**Comment by kurtdeserter** [comment]
@routbiplab I understand @bhavikapatelgm
Think about the following: You have T-shirts in white and black and each color in S,M,L.
White costs $1 in every size
Black costs $2 in every size

If you open product page you see $1. If you choose black it would be necessary that the price changes to $2.

If the sizes have different prices too, than it would perfect to see a "from price" when choosing black or a price range .

Black S $2
Back M $2.5
Black L $3

Color black "from $2" or "from $2 to $3"

I had it in magento 1.9 but I am not able to do it in 2.2

**Comment by magento-engcom-team** [comment]
Hi @m-a-x-i-m. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
