### ISSUE TITLE
Authenticating a customer via REST API does not update the last logged in data

### ISSUE THREAD

**Issue by paul-blundell** [magento/magento2#17488]
### Preconditions
1. Magento 2.2.5
2. PHP 7.0
3. MySQL 5.7

### Steps to reproduce
1. Create a new customer account
2. Login with that customer using the default Magento frontend
3. View the customer in the Magento admin area, and note that the Last Logged In value has been updated
4. Request a customer token via this API endpoint: `/rest/V1/integration/customer/token`

### Expected result
Requesting the customer token should also update the last logged in value.

### Actual result
Last logged In value does not get updated.

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@paul-blundell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by paul-blundell** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell, here is your [Magento instance](https://i-17488-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17488-2-2-5.engcom.dev.magento.com/admin](https://i-17488-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by paul-blundell** [comment]
@magento-engcom-team Yes I was able to reproduce the issue.

**Comment by ghost** [comment]
@paul-blundell , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your report. 
The issue has been fixed in magento/magento2#17978 by @prakashpatel07 in 2.2-develop branch
Related commit(s):
 - [d73e84f2cf860ea62fae20a9c6714d5f4dcafca0](https://github.com/magento/magento2/commit/d73e84f2cf860ea62fae20a9c6714d5f4dcafca0)
 - [9a4f260d33ea4603e34b112a4d72d934700de3de](https://github.com/magento/magento2/commit/9a4f260d33ea4603e34b112a4d72d934700de3de)
 - [55047c71ec782b86026450628c594ba414744c9c](https://github.com/magento/magento2/commit/55047c71ec782b86026450628c594ba414744c9c)
 - [da2c92027aaf3e9ac00d161af88ba6874037ffe9](https://github.com/magento/magento2/commit/da2c92027aaf3e9ac00d161af88ba6874037ffe9)
 - [e8636ef98ec3b747c0773f30bd7adac6153d6bf7](https://github.com/magento/magento2/commit/e8636ef98ec3b747c0773f30bd7adac6153d6bf7)
 - [141b0e4be95ab843a7659759e79b36654930a004](https://github.com/magento/magento2/commit/141b0e4be95ab843a7659759e79b36654930a004)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your report. 
The issue has been fixed in magento/magento2#18973 by @prakashpatel07 in 2.3-develop branch
Related commit(s):
 - [97d5e9bd3ad830edbcb392790b282698e092c032](https://github.com/magento/magento2/commit/97d5e9bd3ad830edbcb392790b282698e092c032)
 - [b8882988a5850232efbf2c3b996d6d9aebfa2903](https://github.com/magento/magento2/commit/b8882988a5850232efbf2c3b996d6d9aebfa2903)
 - [876f50a7e1f782942a19d18822941907c3805308](https://github.com/magento/magento2/commit/876f50a7e1f782942a19d18822941907c3805308)
 - [80da4ea87544caa583ab1c90ed251ea946a8be51](https://github.com/magento/magento2/commit/80da4ea87544caa583ab1c90ed251ea946a8be51)
 - [a40eb487b7d3f57d6241620ff2f49d9b4196f383](https://github.com/magento/magento2/commit/a40eb487b7d3f57d6241620ff2f49d9b4196f383)

The fix will be available with the upcoming 2.3.1 release.
