### ISSUE TITLE
Magento 2.2.5: Categories aren't displayed in top menu when adding a custom theme to a fresh installation. esi:include

### ISSUE THREAD

**Issue by muckee** [magento/magento2#17480]
### Preconditions

1. Ubuntu 18.04 LTS
2. Nginx 1.14
3. MariaDB Ver 15.1 Distrib 10.1.34
4. PHP 7.1.20 w/ Zend OPCache v7.1.20
5. Redis
### Steps to reproduce
1. Magento 2.2.5 installed via composer, running in developer mode
2. Magento setup command issued via command line using existing database from functioning server.
3. Custom theme files added manually from functioning server using rsync.
4. Permissions were maintained during sync, due to stickybit, so everything belongs to www-data.
5. All magento commands have been prefixed with `sudo -u www-data php ...` since initial setup to ensure continuity.
6. Various forums report that creating a new root directory with sub-directories and assigning the new root category to the store in question works for them, but I've tested this and it fails.

### Expected result
1. New theme installed properly.

### Actual result
1. The top menu doesn't appear and the area within the HTML where the category buttons should be rendered is replaced with this:

```<div class="section-item-content nav-sections-item-content" id="store.menu" data-role="content" role="tabpanel" aria-hidden="false"><esi:include src="http://[my_website_url]/page_cache/block/esi/blocks/%5B%22catalog.topnav%22%5D/handles/WyJkZWZhdWx0IiwiY21zX2luZGV4X2luZGV4IiwiY21zX3BhZ2VfdmlldyJd/"></esi:include></div>```

If I follow the link then I can see the buttons rendered as plain HTML, but they aren't loading on the page.

### NOTES

I've checked  to ensure that styles and scripts are not minified, reset permissions as per two-user development setup mentioned in the devdocs and issued `setup:upgrade`, `indexer:reindex` and `cache:flush` commands, with no luck.

As a last ditch attempt at resolving what I thought was a problem with old cached files, I cleared all the relevant directories (retaining .htaccess files), then issued `setup:static-content:deploy en_GB -f` in hopes that this would properly load all of the files for my deployment, but the same problem occured.

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@JoshuaFlood do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by muckee** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @JoshuaFlood, here is your [Magento instance](https://i-17480-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17480-2-2-5.engcom.dev.magento.com/admin](https://i-17480-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by muckee** [comment]
@magento-engcom-team is there any way I can add themes to this or alter the database? If I can't emulate the process of migrating a database then I'm not going to be able to replicate it, though I don't see that this should matter too much because migrating databases is a feature which Magento is supposed to possess.

**Comment by muckee** [comment]
Never mind. I had simply forgotten to switch the previous config from using varnish cache to default, because I have not yet installed varnish on the server.
