### ISSUE TITLE
Adding a valid product by SKU in lowercase in admin order throws an error exception

### ISSUE THREAD

**Issue by SebastianKlett** [magento/magento2#17486]
Summary:
When creating a new order in Admin and adding a product by SKU, entering a valid product SKU in lowercase throws an exception error.
### Preconditions

1. Magento 2.2.5
2. PHP 7.1
3. mySQL 5.6

### Steps to reproduce

1. Admin
2. Sales
3. Orders
4. Create New Order
5. Select Customer (store view level)
6. Select associated store view 
7. Add product by SKU
8. Enter a valid SKU (must match with lowercase)
9. Error exception is thrown

### Expected result

1. Product SKU is added to order

### Actual result

1. Error exception is thrown

**Comment by magento-engcom-team** [comment]
Hi @SebastianKlett. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@SebastianKlett do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@SebastianKlett, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by SebastianKlett** [comment]
This is in the Magento backend and also an issue in the Magento Open Source version.

**Comment by ghost** [comment]
@SebastianKlett, you cannot have this issue on Magento Open Source version because it does not support adding Product to Order by SKU.

**Comment by nntoan** [comment]
@SebastianKlett @engcom-backlog-pb This issue fixed in 2.3-develop, internal ticket logged as MAGETWO-91807.

https://github.com/magento/magento2/commit/45da02260c989f088b4645307e4af42d9b944b00

**Comment by Ctucker9233** [comment]
@engcom-backlog-pb Is there a backport of this fix for 2.2? If not, I'll take it.
