### ISSUE TITLE
Valid PHP class names containing number not accepted in indexer.xsd and mview.xsd schemas

### ISSUE THREAD

**Issue by mlindholm** [magento/magento2#17494]
### Preconditions
1. Magento 2.2.4
2. PHP 7.1
3. MySQL 5.6

### Steps to reproduce
1. Create indexer class with number on the class name. Example _Vendor\ModuleB2B\Model\Indexer_
2. Create table _moduleb2b_index_ table.
3. Create indexer configuration for the indexer class.
4. Create mview configuration for indexer class and table.

### Expected result
1. indexer.xml should be accepted as valid configuration as the class name is valid php class name.
2. mview.xml should be accepted as valid configuration as the class and table names are valid.

### Actual result
1. According to indexer.xsd the class name is not valid because it contains number.
2. According to mview.xsd the class name and the table name are not valid because they contain number.

**Comment by magento-engcom-team** [comment]
Hi @Tuuhea. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Tuuhea do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Duplicate of #9985
