### ISSUE TITLE
Critical checkout issue with configurable product (Cannot read property 'checkoutUrl' of undefined)

### ISSUE THREAD

**Issue by biotech** [magento/magento2#1749]
Issue happens on recent beta with sample data and can be easily reproduced on Nexcess beta http://magento2-demo.nexcess.net/ same as on our own beta http://magento2demo.firebearstudio.com/ 

Steps to reproduce 

1. Clean all cookies for domain , refresh page 
2. Select options and add to cart configurable product http://magento2-demo.nexcess.net/breathe-easy-tank.html 
3. Go to cart page http://magento2-demo.nexcess.net/checkout/cart/ 
4. Refresh cart page
5. Try Go To Checkout button - not works and error on JS console - Uncaught TypeError: Cannot read property 'checkoutUrl' of undefined - proceed-to-checkout.js:22.  Direct checkout URL works fine in same time. 
<img width="1913" alt="screenshot 2015-08-26 13 10 22" src="https://cloud.githubusercontent.com/assets/2007450/9491984/d9cc15a0-4bf3-11e5-9d22-44b28cc38a3f.png">

Some time this steps is not enough for reproduce the issue. Then if you are able go to checkout - from checkout page click on store logo for back to home page -> cart again.

**Comment by adzminz** [comment]
I think it's the same issue as #1508. Please try retest with the latest development branch.

**Comment by okorshenko** [comment]
@biotech , Please, let us know if you still have an issue with latest changes in develop branch

**Comment by biotech** [comment]
@okobchenko fixed now , thanks

**Comment by magento-engcom-team** [comment]
Hi @biotech. Thank you for your report. 
The issue has been fixed in magento/magento2#29490 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [c410eae85cb8ba2a150fd83b581cc24f23a0e61e](https://github.com/magento/magento2/commit/c410eae85cb8ba2a150fd83b581cc24f23a0e61e)
 - [a1de7214949210220abe3a3428ba78778ac9d2ab](https://github.com/magento/magento2/commit/a1de7214949210220abe3a3428ba78778ac9d2ab)
 - [84ee18b2c95d6476604eb17302d3040afc5b014c](https://github.com/magento/magento2/commit/84ee18b2c95d6476604eb17302d3040afc5b014c)

The fix will be available with the upcoming 2.4.1 release.
