### ISSUE TITLE
cronjob fails with .gitignore-errors

### ISSUE THREAD

**Issue by thomas-villagers** [magento/magento2#17490]
### Preconditions

1. Magento 2.2.3 
2. 

### Steps to reproduce

1. setup cron jobs
2. 
3. 

### Expected result

cronjobs should work

### Actual result

var/log/update.log:

[2018-08-10 11:17:02] update-cron.ERROR: Cron readiness check failure! Found non-writable paths:        /var/www/html/magento/dev/tests/api-functional/.gitignore       /var/www/html/magento/dev/tests/functional/.gitignore   /var/www/html/magento/dev/tests/integration/.gitignore  /var/www/html/magento/dev/tests/js/JsTestDriver/.gitignore      /var/www/html/magento/dev/tests/static/.gitignore       /var/www/html/magento/dev/tests/unit/.gitignore 

But there ARE NO .gitignore files in those folders! E.g., 

/var/www/html/magento/dev/tests/api-functional$ ls -la
insgesamt 28
drwxrwsr-x 6 magento www-data 4096 Jan 25  2018 .
drwxrwsr-x 8 magento www-data 4096 Nov  2  2017 ..
drwxrwsr-x 2 magento www-data 4096 Jan 25  2018 config
drwxrwsr-x 3 magento www-data 4096 Jan 25  2018 _files
drwxrwsr-x 3 magento www-data 4096 Jan 25  2018 framework
-rw-rw-r-- 1 magento www-data 2924 Jan 25  2018 phpunit.xml.dist
drwxrwsr-x 3 magento www-data 4096 Jan 25  2018 testsuite

"magento" is the filesystem owner. Why do I get those errors? 

Any help on this issue would be greatly appreciated! 

- thomas 

I don't want to complain (...), but in other systems like weecommerce upgrading or installing of extensions just work. In Magento: no way! The backend updater doesn't even show the cause of an error, it just hangs forever. :-(

**Comment by magento-engcom-team** [comment]
Hi @thomas-villagers. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@thomas-villagers do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@thomas-villagers, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by thomas-villagers** [comment]
hm, ok, thanks for closing this issue ... and thank you for the information where I should look for a solution (which did not help, by the way). I was able to fix it myself: I just CREATED a bunch of empty .gitignore-files (touch .gitignore) in those folders. 
Don't get mad at me, but I'm still convinced this is some sort of bug -- why does cron complain about non writable files that do not exist? Upgrading/installing of extensions is still a big hassle in Magento, there are just so many places it can break. 

- thomas
