### ISSUE TITLE
Response/Redirect referring to wrong interface layer?

### ISSUE THREAD

**Issue by scottw-finao** [magento/magento2#17508]
This is a little thing, but I was trying to trace code and was having some difficulty as a result of the phpdoc in the file:

vendor/magento/module-store/App/Response/Redirect.php
lines 187-199
``` 
    /**
     * Set redirect into response
     *
     * @param \Magento\Framework\App\ResponseInterface $response
     * @param string $path
     * @param array $arguments
     * @return void
     */
    public function redirect(\Magento\Framework\App\ResponseInterface $response, $path, $arguments = [])
    {
        $arguments = $this->updatePathParams($arguments);
        $response->setRedirect($this->_urlBuilder->getUrl($path, $arguments));
    }
```
What caused the problem is that 'setRedirect()' is not specified in \Magento\Framework\App\ResponseInterface but is instead not available until the next level of inheritance (for example: Magento\Framework\App\Response\HttpInterface)

I'm not sure if this was done on purpose due to multiple 'children' of ResponseInterface potentially implementing that function or simply missed in a refactoring at some point, but it seemed a tad confusing when reading the code. (not to mention breaks IDE trace functionality)
I didn't find any other inheritances of ResponseInterface with a setRedirect function and trying to imagine other protocols (other than http) that might be incorporated in Magento, I can't think of any.

So I'm assuming line 190 should read:
`
     * @param \Magento\Framework\App\Response\HttpInterface $response
`

### Preconditions
Magento 2.2.4

### Steps to reproduce
1. Observe Magento/Store/App/Response/Redirect::redirect()
https://github.com/magento/magento2/blob/840d5b217905f4cfebfccd77099d3e980f076eb0/app/code/Magento/Store/App/Response/Redirect.php#L185-L189

### Expected result
Magento/Store/App/Response/Redirect::redirect() should use param $response with type, which has 'setRedirect()' method implemented. Ex :\Magento\Framework\App\Response\HttpInterface.

### Actual result
\Magento\Framework\App\ResponseInterface $response has no method 'setRedirect()'.

**Comment by magento-engcom-team** [comment]
Hi @scottw-finao. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@scottw-finao do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @scottw-finao, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jasonevans1** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
@scottw-finao, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
