### ISSUE TITLE
Install magento 2 on sever

### ISSUE THREAD

**Issue by tungmpo** [magento/magento2#1750]
Hi,
Anyone can guide me how to install magento 2  on live sever ? 

Thank a lots

Regards
Tony

**Comment by mrkhoa99** [comment]
Hi,

I think that Installing Magento 2 on live server is not difficult. If you had experience of working on live site, you should care about PHP version, configuration of web server: Apache, Nginx, permission. If not, please see this video: https://www.youtube.com/watch?v=ohnhRCUs_J0

**Comment by xcomSteveJohnson** [comment]
Have you looked at the install guide? Currently we have no specific instructions for making Magento live but we're working on it.

http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html

**Comment by choukalos** [comment]
@tungmpo did the devdocs link help you out?

**Comment by tungmpo** [comment]
Hi, 
I have looked  guide document and install successfully on localhost but   i can't install on live server 
Do I install composer on live server?  
Pls help me
Thank you!

**Comment by xcomSteveJohnson** [comment]
Yes you do install composer on your live server.

Please let us know if this helps.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by magento-engcom-team** [comment]
Hi @tungmpo. Thank you for your report. 
The issue has been fixed in magento/magento2#29492 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [8420c37f27ee754de24f2d455f0658c086fd42e8](https://github.com/magento/magento2/commit/8420c37f27ee754de24f2d455f0658c086fd42e8)
 - [19728410e48cf44f28529ad43e71ef22a6e7ef02](https://github.com/magento/magento2/commit/19728410e48cf44f28529ad43e71ef22a6e7ef02)
 - [78980b311ed8f73784becb0769b183c7abd58ff1](https://github.com/magento/magento2/commit/78980b311ed8f73784becb0769b183c7abd58ff1)
 - [12c6bbb57ae5126d724cd4a2181162d2aa6d5543](https://github.com/magento/magento2/commit/12c6bbb57ae5126d724cd4a2181162d2aa6d5543)
 - [94bda9e6d9cbd28309f6f1ff7a0a67c9b1d7f892](https://github.com/magento/magento2/commit/94bda9e6d9cbd28309f6f1ff7a0a67c9b1d7f892)

The fix will be available with the upcoming 2.4.1 release.
