### ISSUE TITLE
Add Australian regions

### ISSUE THREAD

**Issue by maximbaibakov** [magento/magento2#17514]
**Summary of the issue**
Magento does have some country regions by default and they are showing in dropdown when you select a country. 
However, if your country does not have regions defined, then you will see just a text field.

In particularly, Australian regions are missed. 

### Preconditions
1. Magento 2.2.5

### Steps to reproduce
1. Add product to cart
2. Go to checkout
3. Select Australia as shipping / billing country  

### Expected result
1. See dropdown with Australian regions

### Actual result
1. See a text field to enter free text region

**Comment by magento-engcom-team** [comment]
Hi @maximbaibakov. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@maximbaibakov do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @maximbaibakov. Thank you for your report. 
The issue has been fixed in magento/magento2#17516 by @maximbaibakov in 2.2-develop branch
Related commit(s):
 - [1b8b0127522bfd41d93514be4741a88e1901d084](https://github.com/magento/magento2/commit/1b8b0127522bfd41d93514be4741a88e1901d084)
 - [b1fcec41c1284fa203a3d0c366a76ada22f1cbec](https://github.com/magento/magento2/commit/b1fcec41c1284fa203a3d0c366a76ada22f1cbec)
 - [020ca367e590f5ac49df197f6002b66af5048544](https://github.com/magento/magento2/commit/020ca367e590f5ac49df197f6002b66af5048544)
 - [ebb517b4e4886eb176158bac0412557c5b2b4764](https://github.com/magento/magento2/commit/ebb517b4e4886eb176158bac0412557c5b2b4764)

The fix will be available with the upcoming 2.2.8 release.
