### ISSUE TITLE
Dispatch event once catalog price rule indexer finishes.

### ISSUE THREAD

**Issue by joshirohit100** [magento/magento2#17522]
For the catalog price rule indexer, there should be a way for the user/dev to hook into when indexing is done.

Right now  **\Magento\CatalogRule\Model\Indexer\IndexBuilder::saveRuleProductPrices()** is the place when catalog price rule indexing is complete and price is updated in DB.

There are few scenarios where info required once indexing is done. 
**Example** - send the product price info to the third party once indexing is done.

In this case, I see that the only way to do that is by just overriding the **IndexBuilder** class.

So I think there should be a way to hook into the system and I think the event system is good fit here

**Comment by magento-engcom-team** [comment]
Hi @joshirohit100. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@joshirohit100 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @joshirohit100, thank you for your report. You can create plugin for CatalogRule\Model\Indexer\RuleProductPricesPersistor::execute() which called in  \Magento\CatalogRule\Model\Indexer\IndexBuilder::saveRuleProductPrices(). https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
