### ISSUE TITLE
Unable to send the cookie. Maximum number of cookies would be exceeded

### ISSUE THREAD

**Issue by maximbaibakov** [magento/magento2#17523]
### Preconditions
1. Magento 2.2.5 

### Steps to reproduce
1. Open desktop browser Firefox
2. Navigate to about:config
3. Find "dom.storage.enabled" option and change to "false"
4. Navigate to Magento 2.2.5 (frontend), open developer tools >> Storage >> Cookies and look at list (there are 33 cookies)
5. Duplicate tab (open the same page in another page) - you will have 43 cookies.
6. Try to duplicate tab again - you will have 52 cookies.

### Expected result
1. Cookies list should not grow such fast (it is based on that ticket #17195)
2. Large number of cookies should be supported

### Actual result
1. We can take more then 50 cookies that leads to exception that described in #7931 and #16568

As per http://browsercookielimits.squawky.net/ there is higher limit supported by most popular browser is 180.
RFC suggest to have at least minimum cookies of 50 supported by browser
     * RFC 2109 - Page 15
     * http://www.ietf.org/rfc/rfc6265.txt

But RFC is not an application limitation, the application should not limit number of cookies based on RFC.

I might be wrong of course...

**Comment by magento-engcom-team** [comment]
Hi @maximbaibakov. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@maximbaibakov do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by orlangur** [comment]
50 cookies limit is totally fine and RFC-compliant. The real issue which needs to be fixed is https://github.com/magento/magento2/issues/17195.
