### ISSUE TITLE
Attributes from previous attribute set remain "attached" to the product after attribute set is changed.

### ISSUE THREAD

**Issue by csimby** [magento/magento2#17531]
1. Magento 2.2.5
2. PHP 7.2

### Steps to reproduce
1. Set up a few attribute sets with some dropdown attributes for layered navigation with Values requierd set to YES.
2. Create a simple product with an attribute set, other then default.
3. After the product is saved change the attribute set to default. Save the changes.
4. Checking the front-end you will notice that the filters are still present, showing the number of products. Applying a filter will result showing only the product(s) which had that attribute before.
5. Try change the attribute set to a 3rd set. As you change the attribute set, because there are attributes with required values a default values is inserted. Save the changes.
6. Change back to default and save the product.
7. Check the front-end again, you will notice that all the attributes are shown in the filters, although the product should no longer have them. The attributes are not displayed in the product detail table.

Note:
Tried reindexing, it didn't help.

### Expected result
1. Changing the attribute set for a product should clear the "attached" attributes.

### Actual result
1. Changing the attribute set adds new attributes to the product but with old attributes are still "attached" resulting in wrong information on the front end.

**Comment by magento-engcom-team** [comment]
Hi @csimby. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@csimby do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by csimby** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @csimby. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @csimby, here is your [Magento instance](https://i-17531-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17531-2-2-5.engcom.dev.magento.com/admin](https://i-17531-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by csimby** [comment]
I can confirm, that the issue can be reproduced on vanilla Magento instance .

**Comment by ghost** [comment]
@csimby , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
@csimby, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Comment by LEDSAVE** [comment]
Hi @csimby 

Did you eventually resolve this? I'm having the same issue....

Thanks

**Comment by csimby** [comment]
Hi @LEDSAVE 

I didn't didn't do anything, I just warned all my clients on M2 to be aware of this issue. I am not sure if it was fixed in later releases of Magento.

**Comment by CompactCodeEU** [comment]
I can confirm this is still the case in 2.3.1
