### ISSUE TITLE
Order status incorrect

### ISSUE THREAD

**Issue by scoops87** [magento/magento2#17536]
<!---
**Summary**
     -  A guest customer paid through sagepay successfully, but when we checked in backend it shows order status as Cancelled. We use Ebizmarts Sage Pay Suite 1.2.2.  The customer hasn't contacted us for any issues. 
     - **Information on your environment**
Magento  2.2.3, 
     **- Steps to reproduce**
We tried with a test order to make payment and see what would happen, but when we have tried everything works normally- payment comes in fine, order status shows as normal - Processing.

Our site utilises a theme, but maintains normal checkout without extensions added for the checkout such as osc. On a separate note, unrelated we had a customer contact us that after redirected to our order success page on the magento site they saw a message "payment was received successfully but order was not created". Note: We checked their order in backend admin panel, and all was fine. Other customers came before this customer and after but their orders were normal. Only that this issue above today has shown up regarding order status cancelled. 

   
Our server company did a kernel update before this, but not sure whether to go back to the previous kernel.

**Comment by magento-engcom-team** [comment]
Hi @scoops87. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@scoops87 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
