### ISSUE TITLE
No delete button to delete an attribute set 

### ISSUE THREAD

**Issue by wgohier** [magento/magento2#17544]
### Preconditions
1. Magento 2.2.5 CE
2. PHP 7.1.9
3. MySQL : MariaDB  10.0.32-MariaDB-0+deb8u1 - (Debian)
4. Data migration from 1.9.3.6 to 2.2.5 using data-migration plugin

### Steps to reproduce
1. Go in administration 
2. Edit an existing attribute set (it does happen for only one attribute set, otherwise everything is OK)
3. No delete button display (if i try to sneak using an delete url handmade, i got a message  "We can't delete this set right now.")

### Expected result
1. Looking for a delete button like all other attribute sets
![accessoires attribute sets attributes stores magento admin](https://user-images.githubusercontent.com/635710/43996337-1bcdeccc-9dc1-11e8-8256-41beee39923d.png)

### Actual result
1. No delete button on "Bag" attribute set (and only this one !!!)
![bag attribute sets attributes stores magento admin](https://user-images.githubusercontent.com/635710/43996329-fc0bbb4e-9dc0-11e8-8ecc-29b720720953.png)

**Comment by magento-engcom-team** [comment]
Hi @wgohier. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@wgohier do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by wgohier** [comment]
OK I found it. 
It was due to the attribute set (55) was defined as default attribute_set  in eav_entity_type 

select default_attribute_set_id from `eav_entity_type` where `eav_entity_type`.`entity_type_code` = 'catalog_product'
