### ISSUE TITLE
unstalling somethig from github and afterwards removing gives huge problems

### ISSUE THREAD

**Issue by Cristalline** [magento/magento2#17541]
I was in search for a banner slider and found : emizentech/magento2-banner-slider.
After installing I saw this was far from ideal.
So I did install this item.

Afterwards when I now want to install something else i do get this error:
Command "update" failed: Loading composer repositories with package information
Failed to clone the git@github.com:emizentech/magento2-banner-slider.git repository, try running in interactive mode so that you can enter your GitHub credentials

[RuntimeException]
Failed to execute git clone --mirror 'git@github.com:emizentech/magento2-banner-slider.git' '/home/qualityb/public_html/var/composer_home/cache/vcs/git-github.com-emizentech-magento2-banner-slider.git/'

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

I have been seeking how to remove this gethub reprosorie but nothing to find.

everyone that will do the above will get the same

How to solve?

    Please also have a look at our guidelines article before adding a new issue https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
-->

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @Cristalline. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Cristalline do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @Cristalline, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
