### ISSUE TITLE
 Search Synonyms [Cannot edit the row after you add long text to the ' Synonyms' field]

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#17545]
### Preconditions

1. You can not edit the Synonyms group if you add more that 400 chars

### Steps to reproduce

1. Add new Synonyms Group
2. Add more that 400 chars in the Synonyms field
3. Click on save.
4. Go back to the Grid.
5. click on the "select" in Action column.
6. No menu will appear

### Expected result

1. When you click on "select" in the action column you have to see a menu

### Actual result

1. No menu appear when you click on the "select"in the action column.
2. Actually the menu appear but you need to scroll to the maximum right of the browser
![image](https://user-images.githubusercontent.com/2926032/43996854-048038c6-9d9a-11e8-9079-3627690e611d.png)

**Comment by magento-engcom-team** [comment]
Hi @zexperto. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@zexperto do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by zexperto** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @zexperto. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @zexperto, here is your [Magento instance](https://i-17545-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17545-2-2-5.engcom.dev.magento.com/admin](https://i-17545-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by zexperto** [comment]
Hi @magento-engcom-team, Yes i confirm that i could reproduce the issue on the vanilla Magento instance

![image](https://user-images.githubusercontent.com/2926032/44005648-a2582568-9e44-11e8-926f-c834129053a7.png)

**Comment by ghost** [comment]
@zexperto , thank you for your report.The fix for this issue is already available in the develop branch. See screenshot

![synonym_group](https://user-images.githubusercontent.com/41946904/44030476-99343114-9f09-11e8-881e-e0110b49f0d2.png)

**Comment by zexperto** [comment]
That's perfect , Thank you
