### ISSUE TITLE
In Bundle product order “item status” doesn't show

### ISSUE THREAD

**Issue by brekz** [magento/magento2#17546]
Anybody know, why in Bundle Product order, simple products doesn't has "item status" information/status? It's quite essential to know if this product is ordered, or backordered.

Here is screenshot: https://www.dropbox.com/s/t4hbfkwqd72ebbt/Screenshot%202018-08-12%2010.01.40.png?dl=0

**Comment by magento-engcom-team** [comment]
Hi @brekz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@brekz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @brekz, thank you for your report. This issue not reproducible on 2.2-develop nor 2.3-develop.
If you'd like to update it, please reopen the issue.
![bundle](https://user-images.githubusercontent.com/40755810/44026204-f01cfa10-9efa-11e8-8b09-5d6a49e6fbe5.png)

**Comment by brekz** [comment]
Hey,

Thanks for your answer @engcom-backlog-nickolas ! 

I found issue, why it doesn't show near all products - I was selected "Dynamic Prices" = "No" & it was as one product - I guess why it doesn't show.

But the problem still persist - in all products showing "Ordered" (https://www.dropbox.com/s/m0iwnywza0h3i6b/Screenshot%202018-08-25%2015.32.06.png?dl=0), meanwhile some products are 0 qty. and need to show "Backordered" in that line (if you'll buy separate 0qty./in stock product - in order information will show "Backordered" info).

How to resolve this?
