### ISSUE TITLE
Embedded translation strategy breaks JS files

### ISSUE THREAD

**Issue by ghost** [magento/magento2#17568]
After selecting "Embedded (Translation on Admin side)" as translation strategy and set magento mode in production, customer face an issue of java-script errors on Front side & Admin side.  

### Preconditions

1. Magento Version 2.2.* with sample data
2. PHP 7.0

### Steps to reproduce

1. Stores >> Configuration >> Advanced >> Developer Under “JavaScript Settings” Enable “Translation Strategy”.
2. Set magento mode  in production.

### Expected result

Translated strings in JS in the provided locale, instead to be translated strings like return
$.mage.__("Maximum length of this field must be equal or less than %1 symbols.") .replace('%1', this.attrLength);

1. [Screenshots, logs or description]

### Actual result

Front side & Admin side  > In console javascript error displayed  
1. [Screenshots, logs or description]
**Admin side**
![embedded translation strategy breaks js files_1](https://user-images.githubusercontent.com/2203580/44025110-cf795918-9f0c-11e8-90df-54a7c7ca9a84.png)
**Front side**
![embedded translation strategy breaks js files_2](https://user-images.githubusercontent.com/2203580/44025571-25ba72ca-9f0e-11e8-8a1a-47d1acdc14e4.png)

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@emiprotech, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mahsn** [comment]
I am working on this at #webjump

**Comment by mahsn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17568-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17568-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17568-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @emiprotech 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
