### ISSUE TITLE
Catalog price is not being updated after changes of customer group from admin

### ISSUE THREAD

**Issue by ghost** [magento/magento2#17565]
If I am logged in the front area and my <br/>

    customer group is :-  [general]

After that, I create a new customer group [vendor] and create new catalog price rule for vendor type customer and assign 10% discount to vendor group customer.<br/>

Now if I change my customer group from admin <br/> ` general to vendor ` then I am unable to find 10% discount on product price.

I did this action to find the effect:- flush/indexer/clear but there was not any update.

Note :- I got updated price if I re-log in with the customer.

### Preconditions

1. Magento 2
2. Product created.
3. Customer with "General" group registered.
4. Catalog Price Rule for "Wholesale" customer group created and applied.

### Steps to reproduce

1. Login as Customer.
2. Open Product page - make sure Catalog Price Rule is not applied.
3. Change Customer's group to "Wholesale".
4. Open Product page once again.

### Expected result

1.   Catalog Price Rule is applied.

### Actual result

1.   Catalog Price Rule is not applied.

**Comment by magento-engcom-team** [comment]
Hi @manishg0. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@manishg0 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@manishg0, thank you for your report.
We've acknowledged the issue and added to our backlog.
