### ISSUE TITLE
Currency symbol cannot be changed back to default value from admin panel in Single-store mode

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#17567]
### Preconditions
Set "Enable Single-Store Mode" to Yes" in Stores -> Configuration -> General -> Single-Store Mode fieldset

### Steps to reproduce
1. Login to Admin Panel
2. Go to Stores -> Currency Symbols 
3. Change any currency symbol value
4. Save Currency Symbols
5. Change currency symbol back to the default value (or check "Use Standard" checkbox)
6. Save Currency Symbols

### Expected result
Currency Symbol is set back to the default value

### Actual result
A success message is shown, but currency symbol is not changed back to the default value

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@sivaschenko do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@sivaschenko, thank you for your report.
You just need to flush cache.

**Comment by sivaschenko** [comment]
@engcom-backlog-pb there is no cache involved in the admin panel. The issue is still actual and should be reopened.

**Comment by mcspronko** [comment]
@engcom-backlog-pb I wonder, who stands behind the answer about the cache.

**Comment by sivaschenko** [comment]
Thank you! @miguelbalparda

**Comment by ghost** [comment]
@sivaschenko, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.
![1](https://user-images.githubusercontent.com/40756187/44038304-2f70b48a-9f1f-11e8-92f1-c772bc2af8b2.gif)

**Comment by sivaschenko** [comment]
@engcom-backlog-pb Sorry, I missed one important precondition: this is **single-store mode** issue. Title and description updated accordingly.

**Comment by sivaschenko** [comment]
Here is a screen recording of what acvtually happens:
![save-currency-symbol](https://user-images.githubusercontent.com/2028541/44040216-a04ad530-9f12-11e8-9755-aaf07cc7917a.gif)

**Comment by ghost** [comment]
@sivaschenko, thank you for an update.
We've acknowledged the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @sivaschenko. Thank you for your report. 
The issue has been fixed in magento/magento2#17966 by @magently in 2.2-develop branch
Related commit(s):
 - [f1649dc56965a569c8a0edecb7187f788142fd17](https://github.com/magento/magento2/commit/f1649dc56965a569c8a0edecb7187f788142fd17)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @sivaschenko. Thank you for your report. 
The issue has been fixed in magento/magento2#18204 by @mage2pratik in 2.3-develop branch
Related commit(s):
 - [47413207211e76618b2c85ecf73371dc2f02a84a](https://github.com/magento/magento2/commit/47413207211e76618b2c85ecf73371dc2f02a84a)

The fix will be available with the upcoming 2.3.1 release.
