### ISSUE TITLE
Mini cart is not refreshing when user switch the store from one store to another

### ISSUE THREAD

**Issue by 2base** [magento/magento2#17566]
### Preconditions

1. Magento2 version 2.1.1
2. I have added a product from Store A and mini cart showing the correct number of items, then I have switched to Store B mini cart is empty. But when I go to https://www.valleyspice.com/checkout/cart and refresh this page, the mini cart is not empty

### Steps to reproduce

1. Add a product from Store A
2. Check the mini cart
3. Switch the store from store A to Store B 
4. Check the mini cart, it is empty
5. Now got to https://www.valleyspice.com/checkout/cart  this url and refresh the page, check the mini cart, cart is showing correctly
6. Switch the store from store B to Store A
7. Check the mini cart, we can see empty mini cart

### Expected result

1. When user switch the store then the mini cart should show the items

### Actual result

1. Mini cart is empty after switching the store

**Comment by magento-engcom-team** [comment]
Hi @2base. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@2base do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@2base , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by 2base** [comment]
Hi,

You can check this url https://www.valleyspice.com/
Add a product from this store
Check the mini cart
Switch the store from Farmspice store to Wholesale store
Check the mini cart, it is empty

**Comment by ghost** [comment]
@2base, please try to reproduce this issue on a clean Magento installation. Your problem may be caused by custom modules or themes.
