### ISSUE TITLE
Magento 2 inline edit date issues in admin grid with Ui Component 

### ISSUE THREAD

**Issue by Rutvee123** [magento/magento2#17564]
In magento2 Inline Edit date issues while i edit the record it display current date instead of database date

### Preconditions

Magento version 2.2.3
php 7.0.29
mysqli mysqlnd 5.0.12

### Steps to reproduce

1. So please make any date filed 
<column name="date" class="Magento\Ui\Component\Listing\Columns\Date"> <argument name="data" xsi:type="array"> <item name="config" xsi:type="array"> <item name="filter" xsi:type="string">dateRange</item> <item name="component" xsi:type="string">Magento_Ui/js/grid/columns/date</item> <item name="editor" xsi:type="string">date</item> <item name="dataType" xsi:type="string">date</item> <item name="label" xsi:type="string" translate="true">Date</item> <item name="dateFormat" xsi:type="string" translate="true">MMM dd, YYYY</item> </item> </argument> </column>
2. Open edited Grid,

### Expected result
When make row inline editable an existing record, the date field should show the date from the record

### Actual result

When make row inline editable an existing record, the date field show current date 
![1](https://user-images.githubusercontent.com/40756187/44210955-7bc95000-a170-11e8-8fa9-d5e8dbcada56.gif)

**Comment by magento-engcom-team** [comment]
Hi @Rutvee123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Rutvee123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Rutvee123, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by Rutvee123** [comment]
In Magento2.2.4 none any admin grid inline editable date filed exit .

So please make any date filed 👍 
`     <column name="date" class="Magento\Ui\Component\Listing\Columns\Date">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="filter" xsi:type="string">dateRange</item>
                    <item name="component" xsi:type="string">Magento_Ui/js/grid/columns/date</item>
                    <item name="editor" xsi:type="string">date</item>
                    <item name="dataType" xsi:type="string">date</item>
                    <item name="label" xsi:type="string" translate="true">Date</item> 
                    <item name="dateFormat" xsi:type="string" translate="true">MMM dd, YYYY</item>
                </item>
            </argument>
        </column>`

what i facing issue is given in below screen shot
please check
Grid display record with right date:
![actual date](https://user-images.githubusercontent.com/37202663/44022867-84ad83e2-9f06-11e8-9d34-a563b182fdb0.png)
when inline edit date it display current date instead of actual date
![currentdate issue](https://user-images.githubusercontent.com/37202663/44022900-9996c87c-9f06-11e8-9453-6dc07211ec56.png)

**Comment by Rutvee123** [comment]
Have any update?

**Comment by ghost** [comment]
@Rutvee123, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by Rutvee123** [comment]
Have any update?

**Comment by magento-engcom-team** [comment]
Hi @satyaprakashpatel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by satyaprakashpatel** [comment]
I am working on it #MM19IN

**Comment by magento-engcom-team** [comment]
Hi @Rutvee123. Thank you for your report. 
The issue has been fixed in magento/magento2#20902 by @satyaprakashpatel in 2.3-develop branch
Related commit(s):
 - [e34db300648121696ba3b6ba426c06a0065ade2c](https://github.com/magento/magento2/commit/e34db300648121696ba3b6ba426c06a0065ade2c)
 - [119fe1e3af48ebb4c8566434dc7d710dec450119](https://github.com/magento/magento2/commit/119fe1e3af48ebb4c8566434dc7d710dec450119)
 - [9b46c95d503d0b8927b8f39697f936dd3baf6d3d](https://github.com/magento/magento2/commit/9b46c95d503d0b8927b8f39697f936dd3baf6d3d)
 - [385aa601f8977816d6c27cad9eb16398d649e10e](https://github.com/magento/magento2/commit/385aa601f8977816d6c27cad9eb16398d649e10e)

The fix will be available with the upcoming 2.3.2 release.
