### ISSUE TITLE
Typo in vendor/magento/module-catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php

### ISSUE THREAD

**Issue by ghost** [magento/magento2#17579]
Typo in file vendor/magento/module-catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php
setMegiaGallery should be setMediaGallery on line 122

### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Observe vendor/magento/module-catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php

### Expected result

1. setMediaGallery method called in line 122

### Actual result

1. setMe**g**iaGallery method called in line 122

**Comment by magento-engcom-team** [comment]
Hi @adamkingfisher. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@adamkingfisher do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@adamkingfisher, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ghost** [comment]
My apologies, could of swear I put Magento 2.2.4! Updated above.

**Comment by sidolov** [comment]
Hi @adamkingfisher. Thank you for your report. 
The issue has been fixed in magento/magento2#17659 by @Spaggel in 2.3-develop branch
Related commit(s):
 - [3a942809cf3f73114b5236e4f78bf2adf71411ca](https://github.com/magento/magento2/commit/3a942809cf3f73114b5236e4f78bf2adf71411ca)

The fix will be available with the upcoming 2.3.0 release.
