### ISSUE TITLE
Cannot create preference for \Magento\Rule\Model\Condition\AbstractCondition

### ISSUE THREAD

**Issue by crtl** [magento/magento2#17576]
### Preconditions
1. Magento 2.2.4

### Steps to reproduce
1. in the di.xml create a preference for \Magento\Rule\Model\Condition\AbstractCondition
2. Run setup:di:compile

### Expected result
1. Preferenced class should be used

### Actual result
1. \Magento\Rule\Model\Condition\AbstractCondition is used instead.

**Comment by magento-engcom-team** [comment]
Hi @crtl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@crtl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@crt, thank you for your report.
You can determine preferences only for Interfaces. Please refer to [Magento 2 documentation](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/build/di-xml-file.html#abstraction-implementation-mappings).

**Comment by crtl** [comment]
Ive replaced it with a plugin but it still doesnt work.


vendor/module/etc/di.xml
<type name="Magento\CatalogRule\Model\Rule\Condition\Product">
        <plugin
                name="Vendor_Module_Plugin_CatalogRule_ProductCondition"
                type="Vendor\Module\Plugin\CatalogRule\ProductCondition" />
    </type>
