### ISSUE TITLE
Exporting product data generates a CSV that doesn't pass the import check process

### ISSUE THREAD

**Issue by simonworkhouse** [magento/magento2#17584]
From an clean install with sample data deployed, if you export product data via "System/Data Transfer/Export" then immdediately try to import it using "System/Data Transfer/Import" it fails to pass the initial data validation checks.
The error received is:
1. Options for downloadable products not found in row(s): 46, 47, 48, 49, 50, 51

### Preconditions

1. Magento 2.2.5
2. PHP 7.1.20
3. MySQL 5.7.23

### Steps to reproduce

1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition {install dir}
2. cd {install dir}
3. ./bin/magento setup:install --backend-frontname=? --db-host=? --db-name=? --db-user=? --db-password=? --base-url=? --admin-user=? --admin-password=? --admin-email=? --admin-firstname=? --admin-lastname=?
4. ./bin/magento sampledata:deploy
5. ./bin/magento setup:upgrade
6. Visit the admin panel run an export and then an import of that exported data.

#### Export settings
- Entity Type: Products
- Export File Format: CSV (default)
- Fields Enclosure: Not checked (default)
- No entity attributes excluded (default)

#### Import settings
- Entity Type: Products
- Import Behavior: Add/Update
- Stop on Error (default)
- Allowed Errors Count: 10 (default)
- Field separator: , (default)
- Multiple value separator: , (default)
- Fields Enclosure: Not checked (default)

### Expected result

Import to be successful

### Actual result

Import fails with the error:
1. Options for downloadable products not found in row(s): 46, 47, 48, 49, 50, 51

**Comment by magento-engcom-team** [comment]
Hi @simonworkhouse. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@simonworkhouse do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @simonworkhouse, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ravi-chandra3197** [comment]
Hello @simonworkhouse 
I have reproduced the issue  
 this issue occurs when you do not include in import file mandatory fields for the creation of downloadable products, namely links/files and names of downloadable items. So required columns are:

downloadable_samples
downloadable_links

For more details about  Magento 2 downloadable product import and export  also check
 [https://firebearstudio.com/blog/the-complete-guide-to-magento-2-downloadable-products-and-how-to-import-them.html](https://firebearstudio.com/blog/the-complete-guide-to-magento-2-downloadable-products-and-how-to-import-them.html)

**Comment by magento-engcom-team** [comment]
@simonworkhouse, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Comment by simonworkhouse** [comment]
@magento-engcom-team Please re-open this issue, it is still a problem.
