### ISSUE TITLE
Category name translated twice

### ISSUE THREAD

**Issue by RomanMichak** [magento/magento2#17591]
Category title which has translations for every store, translated one more time from I18n files on category view page. So in situation when we have similar words in different language it could be translated twice. 
Example:
en_US | nn_NO
------- | --------
Moped | Scooter
Scooter | Sparkesykkel

So category "Moped" on store nn_NO displayed as "Sparkesykkel" on category view page. Because it alredy tranlsated in admin as "Scooter" and then tranlsated one more time via I18n files to "Sparkesykkel". It shouldn't search for translation if used already translated value from admin.

### Preconditions
Magento 2.4-develop
PHP 7.1.18
MySQL 5.7.22

### Steps to reproduce
1. Create 2 stores with locale en_US and nn_NO
2. Create categories: "Moped", "Scooter"
3. Set tranlations for nn_NO store in admin as "Moped" => "Scooter",  "Scooter" => "Sparkesykkel"
4. Add nn_NO tranlations to I18n files as "Moped" => "Scooter",  "Scooter" => "Sparkesykkel"
5. Open "Moped" category view page on nn_NO store

### Expected result
1. To see properly translated category name, which is "Scooter".

### Actual result
1. Category name translated twice, and you see "Sparkesykkel"
![image](https://user-images.githubusercontent.com/51680850/109277542-2598f580-7820-11eb-8acb-6af39198e815.png)

**Comment by magento-engcom-team** [comment]
Hi @RomanMichak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@RomanMichak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ghost** [comment]
@RomanMichak, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dmytro-ch** [comment]
I will handle this issue. Thank you!

**Comment by Johan-Trp** [comment]
We face the same issue. We have a Dutch storeview and an English one. We have two categories where this problem shows up. One called Bestsellers and one called Sale. In Dutch, we also want to call them that. But Magento won't let us, because the translation file kicks in, and it auto-translates these two to "Meest verkochte producten" which is a horribly long category name and Sale becomes "Verkoop" which is a literal translation which doesn't actually give the context of the Sale period. 

Even if we switch to the Dutch storeview in Admin > Catalog > Categories, select this Category, then untick the default name and then re-save our intended title of said category, the translation still happens. 

It would make sense to me that if left on Default, the translation kicks in. If Default is unticked and we deliberately set the name for these categories, the translation file ignores this. That could be one solution to this problem.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41071` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by frank-bokdam** [comment]
You can enable / disable title translations in theme configuration:

`Content -> Design -> Configuration -> Header -> Translate title (yes/no)`

**Comment by vityakopin** [comment]
Looks like a duplicate of #7065

**Comment by zakdma** [comment]
@RomanMichak I'm closing this issue since it can be fixed using configuration
`Content -> Design -> Configuration -> Header -> Translate title => NO`
If you have any objections please describe it and reopen this issue. Thank you!

**Comment by magento-engcom-team** [comment]
Hi @RomanMichak. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41071` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
