### ISSUE TITLE
custom_options Import doesn't correctly handle '=' and multi-value separators in fields

### ISSUE THREAD

**Issue by arcanumbridge** [magento/magento2#17597]
The import function in System -> Import doesn't correctly handle custom_options with the multi-value separator field in a value as well as the '='.  A simplistic patch attached.  Also attached sample data.

eg. name=EN = #10 Envelope

Expected:
EN = #10 Envelope

Actual:
EN

eg. option_title=10,000

Expected:
10,000

Actual:
10

Tested on version 2.2.3, the code hasn't changed based on what I saw in 2.3.
[importexport-improvements.patch.txt](https://github.com/magento/magento2/files/2287195/importexport-improvements.patch.txt)
[catalog_product_20180814_update-prices-partial.csv.txt](https://github.com/magento/magento2/files/2287210/catalog_product_20180814_update-prices-partial.csv.txt)

### Preconditions

Magento 2

### Steps to reproduce

1. Create a Product with options containing '=' in Title.
2. Export products.
3. Import product CSV, created in Step 2, selecting 'Add/Update' Import Behavior.
4. Observe Product options.

### Expected result

1. Options are the same as before export.

### Actual result

1. Options are modified - '=' and all text after it is absent.

**Comment by magento-engcom-team** [comment]
Hi @arcanumbridge. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@arcanumbridge do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@arcanumbridge , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by DenisSaltanahmedov** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov, here is your [Magento instance](https://i-17597-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-17597-2-2-develop.instances.magento-community.engineering/admin](https://i-17597-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
