### ISSUE TITLE
user can change the form_key cookie value

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#17618]
### Preconditions

1. Fresh Magento 2.2.5 with sample data 

### Steps to reproduce

1. Go to frontend
2. Add some product into the cart
3. Now go to shopping cart page
4. On cart page open chrome developer toolbar(or firebug) so you can inspect the element(I am using the chrome so it is based on this)
5. On the Application tab of chrome, developer toolbar open the cookies section
6. On the form_key cookie change the value with some random value(i.e ABCDEFSFD)
7. Refresh the page and open inspector with application tab
8. see the form_key cookie value it is the same as which you edited

### Expected result

1. Magento should validate the form_key cookie value with session form_key

### Actual result

1. Magento accepts the user-generated form_key value and I think which is not good.

The interesting thing is If you change the form_key value on the cart page it accept your cookie value and you can place an order. And one more thing Magento validate the form_key value [when you add the product into the cart](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Checkout/Controller/Cart/Add.php#L82) otherwise there is no validation for this.

**Comment by magento-engcom-team** [comment]
Hi @keyurshah070. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@keyurshah070 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@keyurshah070, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by keyurshah070** [comment]
Any update on this?

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by satyaprakashpatel** [comment]
#MM19IN @magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @satyaprakashpatel. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @satyaprakashpatel, here is your [Magento instance](https://i-17618-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-17618-2-2-develop.instances.magento-community.engineering/admin](https://i-17618-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by valdislav** [comment]
It is nature of this key, one way or another the key which passing in request validates with a key related to customer cookie (customer either have a sessionId or form_key in a cookie). So because there is no way to set cookie restricted to site domain in customer browser who is attacked I do not think it is a bug.

**Comment by sdzhepa** [comment]
Hello @keyurshah070 

Thank you for contribution and collaboration!


According to the comment from CORE team above https://github.com/magento/magento2/issues/17618#issuecomment-465251953

Closed as not a bug
