### ISSUE TITLE
Translations done within a theme that's enabled through a category Design change aren't used

### ISSUE THREAD

**Issue by chefbuitenhuis** [magento/magento2#17625]
When having an additional theme, which is activated for a certain category, and with certain translations, they are not picked up by Magento. Magento seems to only collect the translation files for the active main theme, which results in the inability to use different translations within the additional theme.

(Jesse Buitenhuis)
### Preconditions

1. Magento 2.2.x
2. PHP 7.x

### Steps to reproduce

1. Enable Magento_Blank for the website
2. Create a category and set Magento_Luma as it's theme
3. Add a translation to the /i18n/ directory of Magento_Luma
4. Flush caches
5. The translation is now not applied.

### Expected result

1. The translation within the i18n file has been applied.

### Actual result

1. The translation isn't applied.

**Comment by magento-engcom-team** [comment]
Hi @chefbuitenhuis. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@chefbuitenhuis do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@chefbuitenhuis, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @chefbuitenhuis. Thank you for your report. 
The issue has been fixed in magento/magento2#18998 by @cezary-zeglen in 2.3-develop branch
Related commit(s):
 - [210c4e15364e3a5303515c94906c0eccf9782871](https://github.com/magento/magento2/commit/210c4e15364e3a5303515c94906c0eccf9782871)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @chefbuitenhuis. Thank you for your report. 
The issue has been fixed in magento/magento2#17854 by @cezary-zeglen in 2.2-develop branch
Related commit(s):
 - [f6eb7fb7f7d35dce7df81fd4fdf1b8dbee54b3db](https://github.com/magento/magento2/commit/f6eb7fb7f7d35dce7df81fd4fdf1b8dbee54b3db)

The fix will be available with the upcoming 2.2.8 release.
