### ISSUE TITLE
Shipment doesn't show on orders

### ISSUE THREAD

**Issue by szreka** [magento/magento2#17621]
### Preconditions

1. Magento EE 2.2.2

### Steps to reproduce

1. Checkout with Braintree used as Payment (using Check / Money order will work as expected.)
2. Create a shipment in the admin
3. Shipment successfully created

### Expected result

Shipment will show up in the Sales > Shipment grid and also on the Order edit page Shipment tab.

### Actual result

It only shows up in the Sales > Shipment grid

**Comment by magento-engcom-team** [comment]
Hi @szreka. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@szreka do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@szreka , thank you for your report.We were not able to reproduce this issue by following the steps you provided.Please provide more detailed steps to reproduce or try to reproduce this issue ona clean installation or latest release.

![shipments](https://user-images.githubusercontent.com/41946904/44149090-6bda6f1c-a0a3-11e8-88ef-2c1272925aec.png)

![shipment1](https://user-images.githubusercontent.com/41946904/44149096-76be9e44-a0a3-11e8-96fc-6a5164da7064.png)

**Comment by szreka** [comment]
@engcom-backlog-andrii  I couldn't recreate this issue on a clean install. I reported it because this issue appears on more projects, but it might be caused by a custom module. Thank you for your reply.

**Comment by szreka** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @szreka. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @szreka, here is your [Magento instance](https://i-17621-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-17621-2-3-3.instances.magento-community.engineering/admin_2b05](https://i-17621-2-3-3.instances.magento-community.engineering/admin_2b05)
Login: `90b8b88d` Password: `e0bec981be9d`
Instance will be terminated in up to 3 hours.
