### ISSUE TITLE
Bundle Special Prices not correctly rounded

### ISSUE THREAD

**Issue by Stassy** [magento/magento2#17638]
When adding a Special Price to a bundle like 78,9473% (4 decimals), it's saved ok in the database.
If you load the same bundle and save again, it's changed to 78.95% (2 decimals)

### Preconditions
1. Magento 2.2.5 (able to reproduce everytime)

### Steps to reproduce
1. Create one product with price 760€
2. Create a bundle with this product
3. Set a special price to this bundle to 78.9473% 
    (I want price of this bundle to be 600€. So 600€ / 760€ = 0,7894736842)
4. Save bundle only ONCE !!!!! (DO NOT RELOAD IT, DO NOT SAVE A SECOND TIME)
5. Check in DB : SELECT * FROM catalog_product_entity_decimal WHERE attribute_id = 78;
    value is 78.9473
6. Open bundle again and go to Advanced pricing --> Value is 78.95%
7. Don't touch anything and Save bundle
8. Check in DB : SELECT * FROM catalog_product_entity_decimal WHERE attribute_id = 78;
    value is 78.95
9. As a final result in the shop, bundle price is 600,01€

### Expected result
1. In Step 6, expected value should be the one in database : 78,9473%  (not rounded)

### Actual result
1. In Step 6, value is rounded to 2 decimals at 78.95%

### EXTRA INFO
Maybe a link with this issue from PierreLeMaguer : https://github.com/magento/magento2/issues/15311

Thanks

**Comment by magento-engcom-team** [comment]
Hi @Stassy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Stassy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Stassy** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @Stassy. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stassy, here is your [Magento instance](https://i-17638-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17638-2-2-5.engcom.dev.magento.com/admin](https://i-17638-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Stassy** [comment]
@magento-engcom-team I confirm I can reproduce it on Vanilla

**Comment by ghost** [comment]
@Stassy , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @Stassy. Thank you for your report. 
The issue has been fixed in magento/magento2#17971 by @magently in 2.2-develop branch
Related commit(s):
 - [c63d1e636629a0035e23f54cdaa8b0f087f3802b](https://github.com/magento/magento2/commit/c63d1e636629a0035e23f54cdaa8b0f087f3802b)
 - [36570de1c7c7045d4a6a89e3b589412da0ff6bb6](https://github.com/magento/magento2/commit/36570de1c7c7045d4a6a89e3b589412da0ff6bb6)
 - [194429936730a6350d1f2cde0e09bcaf6f963a35](https://github.com/magento/magento2/commit/194429936730a6350d1f2cde0e09bcaf6f963a35)

The fix will be available with the upcoming 2.2.8 release.
