### ISSUE TITLE
error when printing order packing slip

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#1764]
Trying to print packing slip of one of the demo orders from sample data. Receiving this error:

`Notice: Undefined property: Magento\Sales\Controller\Adminhtml\Order\Pdfshipments\Interceptor::$_fileFactory in /var/www/html/app/code/Magento/Sales/Controller/Adminhtml/Order/Pdfshipments.php on line 42`

![screen shot 2015-08-31 at 1 01 48 am](https://cloud.githubusercontent.com/assets/437029/9572315/e490c2f2-4f7b-11e5-996d-69d03ba58762.png)

**Comment by markoshust** [comment]
Same error when printing credit memo pdf

**Comment by okorshenko** [comment]
@markoshust , thank you for reporting. Internal ticket: MAGETWO-43230

**Comment by piotrekkaminski** [comment]
We cannot reproduce it @markoshust. Can you provide steps how to reproduce?

**Comment by markoshust** [comment]
This appears to be fixed now in develop

**Comment by magento-engcom-team** [comment]
Hi @markoshust. Thank you for your report. 
The issue has been fixed in magento/magento2#29636 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [d1abc9dd10c47da048a0ceafca37c9b45102fe36](https://github.com/magento/magento2/commit/d1abc9dd10c47da048a0ceafca37c9b45102fe36)
 - [070749dacea796fae19cd935e3318498cd06bb7a](https://github.com/magento/magento2/commit/070749dacea796fae19cd935e3318498cd06bb7a)

The fix will be available with the upcoming 2.4.2 release.
