### ISSUE TITLE
Sales Rule shipping discount incorrect applying 

### ISSUE THREAD

**Issue by philip-teslenko** [magento/magento2#17640]
### Preconditions
1. Magento ver. 2.2.5

### Steps to reproduce
1. Create new Sales Rule 
2. Add discount rules and conditions
3. Switch "Apply to shipping amount" checkbox to "Yes"
4. Save Sales Rule

### Expected result

1. Discount conditions are applied only to shipping cost

### Actual result

1. Discount is applied simultaneously to quote subtotal and to shipping cost

**Comment by magento-engcom-team** [comment]
Hi @philip-teslenko. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@philip-teslenko do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @philip-teslenko, thank you for your report. Described behaviour is correct one. Apply to Shipping Amount = Yes means discount will be applied also to shipping cost, Even if you take a look at comment below button, it doesn't say discount will be applied only to shipping cost.
![apply_to_shipping](https://user-images.githubusercontent.com/40755810/44208571-5f75e500-a169-11e8-9040-f9c76b015eb2.png)

**Comment by k4emic** [comment]
@engcom-backlog-nickolas What is the use case for this setting to work on both totals, compared to only applying to the shipping amount? Merchants have very little control of how the discount is applied here, when it's applied to both totals.
