### ISSUE TITLE
Magento 2.2.4 Free Shipping Enable “Show Method” do not show

### ISSUE THREAD

**Issue by jvhost** [magento/magento2#17656]
Preconditions

Magento 2.2.4 / Php 7.0.20-1 / Mysql 5.6.30

Steps to reproduce
1.Enable ”Free shipping” Method
2.Set "Minimum Order Amount" price which is bigger than the price in my shopping cart.
3.Enable "Show Method if Not Applicable".

Expected result
The "Free Shipping Method" will show with not applicable notice.

Actual result
The "Free Shipping Method" never show

Issue 16312 was never resolved even though it was closed.

**Comment by magento-engcom-team** [comment]
Hi @jvhost. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@jvhost do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@jvhost, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jvhost** [comment]
Hi folks, thanks for the acknowledgement and adding to the backlog, In the mean-time, is there someplace I could start looking to try and debug it myself?  My client needs some sort of free shipping.  Thanks!

**Comment by saravananvelu** [comment]
@jaiminparikh Did you fixed the issue?

**Comment by jaiminparikh** [comment]
@saravananvelu Still I am working on this.

**Comment by saravananvelu** [comment]
@jaiminparikh  I have fixed this issue, if it is ok for you, I will commit.

**Comment by jaiminparikh** [comment]
@saravananvelu sure you can commit it. Thanks for the update.

**Comment by jvhost** [comment]
Hi folks .. just wondering if there's a link to the commit so I can test the changes for my customer .. thanks!

**Comment by nadim2jcommerce** [comment]
Hi @saravananvelu  and @jaiminparikh
Have you fixed issue? Shall I pick?
Thanks!

**Comment by jvhost** [comment]
Hi @saravananvelu - the fix that you applied and worked on doesn't work for this issue.  It doesn't even reach the file you updated.  @jaiminparikh did you have any success?

**Comment by jvhost** [comment]
Hi folks ... now I feel like the amateur .. someone helped me discover, this was my own fault.  For some reason in the shipping configuration I had disabled it for the one store I was testing - that would explain it.  Thanks for your patience folks!
