### ISSUE TITLE
magento 2.2.4 gives error 500 

### ISSUE THREAD

**Issue by soly2014** [magento/magento2#17675]
i just installed magento 2.2.4 on my ubuntu 16.04 with apache 2.4.18 
Preconditions

Magento 2.2.4
PHP 7.0.
ubuntu 16.04
apache 2.4.18  

Steps to reproduce

Go to admin and load web setup wizard to upgrade magento 2.2

Expected result

Website should load without any errors

Actual result
![magento-error](https://user-images.githubusercontent.com/7080614/44291845-67c14380-a281-11e8-82a1-aa2d7ec944e5.png)

**Comment by magento-engcom-team** [comment]
Hi @soly2014. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@soly2014 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ArjenMiedema** [comment]
Did you check your Apache error logs? That's where the HTTP errors (like 500 errors) are saved when they occur. It's really useful if you could post the error you get there.

**Comment by soly2014** [comment]
@ArjenMiedema  Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

**Comment by soly2014** [comment]
@ArdjanShero  still stuck

**Comment by ArjenMiedema** [comment]
What does the backtrace say?

**Comment by engcom-backlog-nickolas** [comment]
@soly2014, thank you for your report. I'm not able to reproduce this issue. Could you please add more details?

**Comment by soly2014** [comment]
the error was occurred because of my project folder name wasn't like to my route name

**Comment by ArjenMiedema** [comment]
So we can close this issue?

**Comment by engcom-backlog-nickolas** [comment]
@soly2014, thank you for feedback. I'm closing this issue for now. If you'd like to update it, please reopen the issue.
