### ISSUE TITLE
Is it possible to create attributes sets and their options pragmatically but not during the install

### ISSUE THREAD

**Issue by achadee** [magento/magento2#17698]
Hi,

We are developing a REST API that extends magento 2's functionality. One thing we need this API to do is to create attributes "on the fly" based on the custom JSON product payload sent.

Ive seen a lot of forum posts showing how to add attributes using the InstallData but none on how to add attributes by calling a function or model

Im also asking for our magento developer - I roughly know how to read PHP and have a basic understanding of magento, so try to keep it simple so I can answer any questions you might have :)

Thanks in advance!

**Comment by magento-engcom-team** [comment]
Hi @achadee. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@achadee do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@achadee, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
