### ISSUE TITLE
Language  Switcher are not working on Magento 2.2.5

### ISSUE THREAD

**Issue by Yuibaritone** [magento/magento2#17696]
### Preconditions
1. Magento 2.2.3
2. PHP 7.1.17

### Steps to reproduce

1. I create a new Store views set and assign this to Main Website [Store]
2. I switch to another language (en->th) and (th->en)

https://www.picz.in.th/image/BL8CYE

### Expected result

1. Expecting to be can  Language Switch are working

### Actual result

1. Language  Switcher are not working

**Comment by magento-engcom-team** [comment]
Hi @Yuibaritone. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Yuibaritone do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Yuibaritone, thank you for your report.
This is not a bug. Language switching in Magento 2 works in another way. Please 
refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
