### ISSUE TITLE
Creating a segment with multiple store views errors 500/logs out

### ISSUE THREAD

**Issue by anthonydangbi** [magento/magento2#17692]
When creating a new segment and assigning it to multiple websites, it links to 500 error page. 

Follow steps to replicate:

1. Admin > Create a NEW segment
2. Assign to >1 Website (Select AU and NZ)
3. Save
Current result: 500 Error
Expected result: Segment is created and saved

Note: 3252309 Customer records found

### Preconditions

Magento 2.2.5
PHP 7.1
mySQL 5.6

### Steps to reproduce

1. Admin > Create a NEW segment
2. Assign to >1 Website (Select AU and NZ)
3. Save
4. Error 500
5. Refresh
6. Admin is logged out

### Expected result
Segment is created and saves

### Actual result

Current result: 500 Error, refresh, admin is logged out

**Comment by magento-engcom-team** [comment]
Hi @anthonydangbi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@anthonydangbi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
@anthonydangbi, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
