### ISSUE TITLE
[2.2.*] Admin Grid column ordering/positioning not working

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#17691]
### Preconditions
1. Magento 2.2.*

### Steps to reproduce
1. In sales order grid enable all columns
2. Move a column
3. Refresh page
4. Check moved column is in correct position
5. Repeat process until it fails (usually within 4 or five column moves)

### Expected result
1. Column positions should be correct following page refresh

### Actual result
1. Column positions are not always correct after page refresh
2. Using browser debug tools, an erroneous AJAX call is made during the page refresh which incorrectly alters the column positions.

Please see PR #17512 for additional background info/debug and analyis on this issue.

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment]
I can reproduce the issue on vanilla installs of all versions of Magento 2.2

**Comment by ghost** [comment]
@gwharton ,  thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by pavelshulgabi** [comment]
I'm working on #cd-balance

**Comment by gwharton** [comment]
Still not working in 2.3-develop

Here is a video of vanilla 2.3-develop.

I have opened up the developer tools and filtered on the ajax call to update the column positions in the database ui_bookmark table.

Note, when I first open the page, no ajax call is made as the page loads.

I then drag "Grand Total (Purchased)" to the beginning of the table.

An ajax call is made which saves the new column positions to the database. I don't show it in the video, but trust me, the contents of that ajax call is correct according to the new column positions and the new column positions are reflected in the database.

I then refresh the page. Notice how an ajax call is made during the page reload. The column positions in the refreshed page are incorrect. I inspect the contents of the ajax call, and the ajax call is storing the incorrect column positions to the database, which are then reflected in the reloaded page. In the reloaded page the columns "ID" and "Grand Total (Base)" have swapped.

As far as I know, this ajax call should NOT be made on page refresh.

Looking at the timings, it looks like the browser is making the decision on page load, that the column positions are wrong, and then it updates the database.

https://www.youtube.com/watch?v=B8rf4dj6LuI

**Comment by gwharton** [comment]
Confirm still broken in 2.2.8...... yawn!

**Comment by gwharton** [comment]
Dont seem to have this issue in 2.3.2 anymore. Closing.

**Comment by realadityayadav** [comment]
@gwharton is there a fix for older versions or a changelog corresponding to this particular fix?

**Comment by gwharton** [comment]
Nope. I'm not sure a fix was ever identified. I closed the issue because it was open for a long time with no interest in anyone fixing it. A check of 2.3 seemed to show it working well, however since then I see it is still broken in 2.3-develop as i've had columns move unexpectedly since updating to 2.3.

Are you able to reproduce it 100% of the time, if so can you write up a detailed report for me, as It always seemed a bit random as to when it happened for me, and those sort of bugs never get picked up.
