### ISSUE TITLE
CustomerAddressId will not set for new billing adress 

### ISSUE THREAD

**Issue by larsroettig** [magento/magento2#17705]
### Preconditions
1.  Magento 2.2.x or 2.3.x

### Steps to reproduce
1. Create a new Customer Account
2. Add one Product to Cart
3. Create a New Shipment Adress
![checkout1](https://user-images.githubusercontent.com/5289370/44344325-bd1f6f80-a490-11e8-97f9-57395787a6e0.png)
4. Use Shipment Adress as Order Adress
![checkout2](https://user-images.githubusercontent.com/5289370/44344355-d32d3000-a490-11e8-8fa2-55ccc36bcd29.png)

### Expected result

1. In `sales_order_address` is for the `customer_address_id ` the correct id saved

### Actual result

1. In `sales_order_address` is the `customer_address_id ` currently null
![sales_order_address](https://user-images.githubusercontent.com/5289370/44344435-0079de00-a491-11e8-829c-3854a25c1169.png)

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@larsroettig do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by larsroettig** [comment]
*Info:*

- Problem is in \Magento\Quote\Model\QuoteManagement::_prepareCustomerQuote 
there will be setCustomerAddressId not set for the `$billing `

**Comment by Spaggel** [comment]
@larsroettig I've added:
```
if(!$billing->getCustomerAddressId() && $shippingAddress) {
    $billing->setCustomerAddressId($shippingAddress->getId());
}
```


to `_prepareCustomerQuote()` after
```
if ($shipping && !$shipping->getCustomerId() && !$hasDefaultBilling) {
    $shipping->setIsDefaultBilling(true);
}
```

to fix the problem (on a local environment). Should I open a PR for it to discuss it further?

**Comment by larsroettig** [comment]
@Spaggel - Feel free to open a PR for this bug but i think you must also extend the \Magento\Quote\Test\Unit\Model\QuoteManagementTest for better qualtiy.

best regards,

Lars

--- 
Maintainer at Magento Community Engineering Team

**Comment by ghost** [comment]
@larsroettig, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by cristhianss** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cristhianss. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cristhianss, here is your [Magento instance](https://i-17705-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-17705-2-3-develop.instances.magento-community.engineering/admin](https://i-17705-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by naydav** [comment]
Hello,

It does not look like a bug. More like legacy code. The completeness of the `customer_address_id` field in `sales_order_address` should not affect the any logic (main links are `quote_address_id` and `parent_id`).
@larsroettig, can you describe a real functional case?

I would not like to introduce performance degradation when placing an order.

**Comment by navarr** [comment]
We found this issue when researching a related problem where customer_address_id was not set and was expected.

In our case, it was on the shipping address.  Our customer keeps all addresses and customer record masters in an ERP.  When processing new orders, the ERP looks for the customer_address_id to match on.

**Comment by VladimirZaets** [comment]
Firstly investigate the usage of the `customer_address_id` field and deprecate it. 
If we use it, we need to refactor and avoid usage of this field
