### ISSUE TITLE
can't designate products which belong to category list _only_ in Cart/Catalog Price Rules

### ISSUE THREAD

**Issue by EustaceCS** [magento/magento2#17706]
### Preconditions
1. Pure Magento 2.2.5 CE with sample data

### Steps to reproduce
1. Remove/inactivate Catalog Price Rules which could be present currently
2. Create a new active Catalog Price Rule with
- Rule Name: any
- Websites: all
- Customer Groups: all
- Conditions:
- - If ALL  of these conditions are FALSE :
- - - Category  is not one of  3
- Actions
- - Apply: as percentage of original
- - Discount Amount: 50.0000
3. Save and apply
4. Reindex all
5. Check SKU 24-MB01 's product page at Frontend

### Expected result
1. Catalog Price Rule don't afffect this product

Because:

Product 24-MB01 have Categories 3 (Gear), 4 (Bags) assigned
This condition config looks for products for which 'category is not one of 3' is False

Checking 'Category  is not one of  3' condition part:
category - 'is not one of 3'?
3 (Gear) - false - failed to pass
4 (Bags) - true - passed

Checking 'If ALL  of these conditions are FALSE :' part:
category - 'is not one of 3'? - 'is not 'is not one of 3''?
4 (Bags) - true - false - failed to pass

### Actual result
1. Catalog Price Rule has been applied, product price reduced by 50%

This 'issue' can be deemed as a feature code-wise despite being rather illogical.
Causes difficulities with designating discounts for products which do pelong to particular category list _only_ if there are too many categories to products from which discounts should _not_ be applied by any means.
Designating such products even via mass update by specific custom product attribute is tedious.

**Comment by magento-engcom-team** [comment]
Hi @EustaceCS. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@EustaceCS do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by EustaceCS** [comment]
I hereby acknowledge that all tests which led to assembling of issue #17706 were performed on pure Magento 2.2.5 CE with Magento's very own Sample Data _and_ that relevant Summary, Information, Steps and ER/AR needed to justify this issue as a bug (preliminarily, as a difficulity which can be improved, at least) are all included.

Thank you.

**Comment by ghost** [comment]
@EustaceCS, thank you for your report.
We've acknowledged the issue and added to our backlog.
