### ISSUE TITLE
Regarding a New Shop

### ISSUE THREAD

**Issue by aneeshjajodia** [magento/magento2#1771]
Hello

I've been using WooCommerce for my previous shop till now and now that we have grown, am looking onto using Magento as my shop for my main website and have a crowdfunding module linked to Magento in some sort.

What I wanted to ask is, should I start with Magento 1.9.2 or whatever is the latest one, or should I go with Magento 2 Beta?

I would be glad if someone could help me out on the same.

Cheers.

**Comment by pronto2000** [comment]
After trying out latest git development branch of M2 all I can say is that it's nowhere near production level right now. At this point I would start with 1.9.2 and upgrade once M2 is stable enough. M1 is not going anywhere for at least three years so it's probably the safest route.

**Comment by aneeshjajodia** [comment]
@pronto2000, So upgrading at a later stage wouldn't be a problem, will it?

**Comment by pronto2000** [comment]
Well, it's going to be somewhat complicated, but building a store right now on half-baked product is worse. Unless you're willing to wait ... Magento 2 GA version should be available by the end of the year.

**Comment by choukalos** [comment]
@aneeshjajodia Magento 2 will GA by the end of the year.  If it makes sense for your business to wait - then waiting is a valid option for you to consider.  If you do choose to wait I'd encourage you to contact the developers of the extensions you believe you'll need as not all developers will have Magento 2 versions available at GA.

If you're looking to move to Magento now - then I'd suggest Magento 1.9.2 (I'm assuming you're < $5M/annual revenue; otherwise I'd recommend 1.14.2 - visual merchandizer, FPC, partial reindexing).  Based on preliminary feedback from our Merchant beta I'm hearing it's a bit more ( ranges from 20-30% ) to migrate to Magento 2 then a upgrading to a new version of Magento in the 1.x branch.  We plan on doing Magento 2 releases every quarter and have some exciting merchant features lined up for next year.

**Comment by TRMMarketing** [comment]
@aneeshjajodia I would never recommend developing a production store on a beta platform. Building your store on Magento 1.9+ you are positioning yourself on an e-commerce platform which will work for a good long time to come. There is no requirement to upgrade to Magento 2 and there is a wealth of developers knowledgeable in the 1.x platform and with years of use the 1.x platform is about as stable as you are going to get (This is true for both Magento CE and EE). Personally I doubt I will be recommending any 1.x clients upgrade to Magento 2.x until at least mid-2016 if not later. The reason is there is bound to be bugs and patches in the first few months after release.

**Comment by pronto2000** [comment]
Well ... if you plan to launch you store next year, it might sounds like a good idea to start working on current beta and update it as you go (maybe even report a bug or ten while working on it). No good! Right now several key functions are totally unusable -- for example configurable products -- and until they get fixed there's no reason to get frustrated.

**Comment by tanya-soroka** [comment]
@pronto2000 , could you please explain/ provide more infroamiton about the the issue which you have faced with configurable product? 
Thanks

**Comment by pronto2000** [comment]
Uh, I've been off the grid for a couple of days.

I'll try to describe things I have issues with. Sure some of them maybe there because of my M1 mindset or because of questionable UX choices, but I think those should be addressed soones or later.

1. At first glance simple product and configurable product are basically the same thing. There's one big difference: configurable product doesn't allow you to choose attribute set. As a long time M1 user I cannot see why it's so -- it was there to limit the number of attributes I had assigned to this particular set and thus made creating configurable product much easier. Also it allowed to limit the number use was able to associate with this particular configurable product.

2. There's no logical way to create configurable product from already existing simple products. ure I was able to create associated elements and later replace them with simple products, but it was both inconvenient and confusing.

3. There's no obvious way to add simple products to configurable products.

There were other issues I had as well, but I'm not near my development machine and thus writing those items off the top of my head.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
