### ISSUE TITLE
duplicate event in Delete operation transaction "entity_manager_delete_before"

### ISSUE THREAD

**Issue by zebimax** [magento/magento2#17715]
### Preconditions

1. Magento 2 code

### Steps to reproduce

1. Observe \Magento\Framework\EntityManager\Operation\Delete::execute

### Expected result

1. 'entity_manager_delete_before' event dispatched once.

### Actual result

1. 'entity_manager_delete_before' event dispatched twice.

https://github.com/magento/magento2/blob/764b00c40d9ad6dd7c8b53f3ecf04a9b4fab2b2e/lib/internal/Magento/Framework/EntityManager/Operation/Delete.php#L121

**Comment by magento-engcom-team** [comment]
Hi @zebimax. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@zebimax do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@zebimax, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @zebimax. Thank you for your report. 
The issue has been fixed in magento/magento2#17718 by @p-bystritsky in 2.2-develop branch
Related commit(s):
 - [bbd9ba7267f11618dfce31222b5449cc4e592d64](https://github.com/magento/magento2/commit/bbd9ba7267f11618dfce31222b5449cc4e592d64)

The fix will be available with the upcoming 2.2.7 release.

**Comment by sidolov** [comment]
Hi @zebimax. Thank you for your report. 
The issue has been fixed in magento/magento2#17720 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [05f8e78913cd9922708a35b830f10ad0f2cd713c](https://github.com/magento/magento2/commit/05f8e78913cd9922708a35b830f10ad0f2cd713c)

The fix will be available with the upcoming 2.3.0 release.
