### ISSUE TITLE
Search Query Length Issue

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#17711]
### Preconditions

1. Magento 2.2.5
2. PHP 7.0
3. MySQL 5.6

### Steps to reproduce

1. Login to Magento  Admin
2. Navigate to **Store > Configuration > Catalog and choose Catalog**. Expand the Catalog Search section and Set Minimal Query Length to 5.
3. Clean Cache.
4. Now trying to search  for the **pen**, an the search have found the search result.

### Expected result

1. It needs to display a warning message that ****Minimum Search query length is 5** **

### Actual result

1. Displays some products on search landing page, while search drop-down had no result.

**Comment by magento-engcom-team** [comment]
Hi @RishabhRkRai. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@RishabhRkRai do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@RishabhRkRai , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by OlgaBurtyka** [comment]
![minimum](https://user-images.githubusercontent.com/4771407/45253028-dec19780-b368-11e8-8b52-2bc997077295.png)

**Comment by colombinis** [comment]
#mm18ar

**Comment by magento-engcom-team** [comment]
@colombinis thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by colombinis** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @colombinis. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @colombinis, here is your [Magento instance](https://i-17711-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17711-2-2-5.engcom.dev.magento.com/admin](https://i-17711-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-17711-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-17711-2-2-5.instances.magento-community.engineering/admin](https://i-17711-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ansari-krish** [comment]
@magento-engcom-team give me 2.3-develop instant

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-17711-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-17711-2-3-develop.instances.magento-community.engineering/admin](https://i-17711-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Closing as fixed in 2.3.0
