### ISSUE TITLE
`catalog_product_entity_media_gallery` not cleared when related products deleted.

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#17727]
### Preconditions
1. Magento 2.2.5CE with sample data. 

### Steps to reproduce
1. Go to Products page and delete all products.
2. Look at `catalog_product_entity_media_gallery` table.

### Expected result

1. Table `catalog_product_entity_media_gallery` is empty.

### Actual result

1. It's still has 3.422 rows.  There is no row was deleted.

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@likemusic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@likemusic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by VincentMarmiesse** [comment]
Hi,
Any news on this issue? 

This is still happening on 2.3.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41009` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @likemusic. Thank you for your report. 
The issue has been fixed in magento/magento2#32273 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [b2c47af0897c8253149462f2f1f9e1937be4c6ac](https://github.com/magento/magento2/commit/b2c47af0897c8253149462f2f1f9e1937be4c6ac)
 - [b40d857ba375a657406cd66e2920f1831c36b4f1](https://github.com/magento/magento2/commit/b40d857ba375a657406cd66e2920f1831c36b4f1)
 - [98237f151916288ff58dee24f61fccff91ba159f](https://github.com/magento/magento2/commit/98237f151916288ff58dee24f61fccff91ba159f)

The fix will be available with the upcoming 2.4.3 release.
