### ISSUE TITLE
Repeated Error Message

### ISSUE THREAD

**Issue by Bluesilverlight** [magento/magento2#17736]
Hello

1) I keep getting error messages such as the following in the Admin Area of m Magento2.2.5 with Webkul Marketplace extension and Agorae Theme.

"There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: 802764218454"

2) Also for example, I have added Categories and Root / Sub Categories, but they do not refresh and upload to the website. 

3) When on the home page of the website www.africahasart.com, and I click top right hand of page on 'Create an Account' it switches from Agorae Theme to Luna Theme.

Can someone please advise as to what the issues are?

Thanks

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. [Screenshots, logs or description]

### Actual result

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @Bluesilverlight. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Bluesilverlight do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Bluesilverlight, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
