### ISSUE TITLE
Magento 2.2.4 - Cart Price Rule not working for some products

### ISSUE THREAD

**Issue by ghost** [magento/magento2#17730]
We are using Magento 2.2.4
We have added cart rule without a coupon code.

In Actions, we have selected one of the SKU.

Apply Rule: Buy X get Y (Fixed Price)

### Expected result
All the mentioned SKU should be applicable for the cart rule

### Actual result
For some products, it working and for some SKUs, it is not working

Please note we have configurable products also.

**Comment by magento-engcom-team** [comment]
Hi @AlectoMysticCode. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@AlectoMysticCode do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi,

Thanks for the help.

For anyone visiting this issue in future, please check it there is some 3rd Party extensions, who is putting checks on the cart rules that need to be applied or not. In my case, it was Amasty Rules Pro.

Hope this helps.
