### ISSUE TITLE
Magento 2.2.4 - Advance Pricing not saving

### ISSUE THREAD

**Issue by ghost** [magento/magento2#17731]
**Preconditions**
We are using Magento 2.2.4 and when we add Advanced pricing for the products

**Steps to reproduce**
1. Create simple product with all required fields and save
2. Open Advanced Pricing and add different price for Qty eg:
Website 1 => 1 Qty => $10 
Website 1 => 2 Qty => $18
Website 1 => 3 Qty => $25
3. Save and go to storefront and change Qty 1, 2, and 3 for this product

### Expected result
Product should save properly and preserve the Advance Pricing Rule.
Meaning for all customer groups if the customer buys 1 unit he will be charged $10, if 2 Units , $18 and so on.

### Actual result
Product saved successfully, but all the Qty reverts back to 1 Qty and dont work with Qty 2 or 3.

**Comment by magento-engcom-team** [comment]
Hi @AlectoMysticCode. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@AlectoMysticCode do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@AlectoMysticCode, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by cedmudit** [comment]
@AlectoMysticCode 
The advanced pricing concept I think you had taken wrongly, as the concept is if the customer will buy more products price will be reduced based on rules. Here the rules applicable based on each quantity, so if you enter rule like:
Website 1 -> All Groups -> 1Qty -> $10 Price
Website 1 -> All Groups -> 2Qty -> $9 Price
Website 1 -> All Groups -> 3Qty -> $8 Price

It will work.

Where As you applied rules 
Website 1 => 1 Qty => $10
Website 1 => 2 Qty => $18
Website 1 => 3 Qty => $25
which is voilating condition of reducing price when quantity increased.

Yes of course if you want something reverse where prices increases for each new quantity then there is the issue.

**Comment by ghost** [comment]
@cedmudit 
Actually my bad, for providing you with the wrong example. It is as intended as you showed above.

Actually, I can't reveal the client data, so came up with an example, which unfortunately I messed up.

But the issue still exists. The Quantity reset to 1 on product save and there is no error in any logs also.

Even if we make a single entry of Website 1 -> All Groups -> 2Qty -> $9 Price. The price is saved successfully but for some reason, the quantity resets to 1.

Please feel free to ask more questions.

Thanks in advance.

**Comment by cedmudit** [comment]
@magento-engcom-team give me magento 2.2.4 instance

**Comment by ghost** [comment]
@cedmudit , thanks for you works for this issue. But product advanced pricing on backend and frontend on Magento store cannot be different

**Comment by cedmudit** [comment]
@engcom-backlog-andrii : Yes true that's I mentioned previously also if Magento is saving prices like 
Website 1 => 1 Qty => $10
Website 1 => 2 Qty => $18
Website 1 => 3 Qty => $25

then it should work on frontend also in the same manner, and while adding the product in the cart it should increase the price, or we can apply validation at admin side to not save prices like above.
