### ISSUE TITLE
Invalid Form Key. Please refresh the page. when trying to save a category

### ISSUE THREAD

**Issue by nuwaus** [magento/magento2#17748]
### Preconditions

1. Magento 2.2.5
2. PHP Version 7.1.20

### Steps to reproduce

1. Open a category by going through Catalog > Categories > Select a category in the tree
2. Make some changes (not required)
3. Hit save button to save the changes

### Expected result

1. Saving the category without any issue

### Actual result

1. Invalid Form Key. Please refresh the page. (no any long in error logs related)
![screen shot 2018-08-22 at 7 58 10 pm](https://user-images.githubusercontent.com/209750/44469796-e46b6d80-a645-11e8-98e6-59f04d9c7677.png)

**Comment by magento-engcom-team** [comment]
Hi @nuwaus. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nuwaus do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@nuwaus, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
