### ISSUE TITLE
Virtual-only quotes use default shipping address for estimation instead of default billing address

### ISSUE THREAD

**Issue by navarr** [magento/magento2#17744]
When you have a cart containing only virtual products and are a signed-in customer with different default shipping and billing addresses, the default shipping address information will be populated in the cart estimation field instead of the default billing address information - providing an incorrect estimation of tax charges.

### Preconditions

1. Magento 2.2.6-dev installed
2. Default tax rates configured (typical of a clean installation)
3. Addition of a Tax Rule that enables those rates
![](https://user-images.githubusercontent.com/145128/43797782-9110a9a2-9a56-11e8-8307-eccf6f102768.png)
4. A virtual product created with price point $10

### Steps to reproduce

1. Create a customer account
2. Create a default billing address of New York, such as:  
123 Main St  
Flushing, NY 11354
3. Save
4. Create a default shipping address in an area without tax rates, such as:  
2301 Renaissance Blvd
King of Prussia, PA 19406
5. Save
6. Browse to category to add Virtual product to cart
7. View cart page

### Expected result

1. Estimate shipping and tax pre-filled with US / New York / 11354, tax estimated as $0.84

### Actual result

1. Estimate shipping and tax pre-filled with US / Pennsylvania / 19406, no displayed tax

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@navarr do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by navarr** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @navarr, here is your [Magento instance](https://i-17744-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17744-2-2-develop.engcom.dev.magento.com/admin](https://i-17744-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@navarr, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @navarr. Thank you for your report. 
The issue has been fixed in magento/magento2#18095 by @LucasCalazans in 2.3-develop branch
Related commit(s):
 - [a44eb5dd5fd2a95f79b617a480b9221704495887](https://github.com/magento/magento2/commit/a44eb5dd5fd2a95f79b617a480b9221704495887)
 - [0890139741aa73a06f81223e0793c0994e171f4d](https://github.com/magento/magento2/commit/0890139741aa73a06f81223e0793c0994e171f4d)
 - [5372c7df5e16601f2cce687e15ff25ecdd0b82ce](https://github.com/magento/magento2/commit/5372c7df5e16601f2cce687e15ff25ecdd0b82ce)
 - [b871ea91610bd14c57ee99aa520ed7350c65b584](https://github.com/magento/magento2/commit/b871ea91610bd14c57ee99aa520ed7350c65b584)
 - [ec5d9b7f171e76c0285c6e683a4b2da5902c2f78](https://github.com/magento/magento2/commit/ec5d9b7f171e76c0285c6e683a4b2da5902c2f78)
 - [a86262018635cbedbec7d474119bbdb7f2f85638](https://github.com/magento/magento2/commit/a86262018635cbedbec7d474119bbdb7f2f85638)
 - [f3bad34fe9156f1fe2d2e2d4a4a7d8a244107085](https://github.com/magento/magento2/commit/f3bad34fe9156f1fe2d2e2d4a4a7d8a244107085)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your report. 
The issue has been fixed in magento/magento2#18863 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [b57ae0188bdf5522a2d56693d386e54348c368e5](https://github.com/magento/magento2/commit/b57ae0188bdf5522a2d56693d386e54348c368e5)
 - [f7a8160bb2d759644de61012cb5b3bdb0b8e2770](https://github.com/magento/magento2/commit/f7a8160bb2d759644de61012cb5b3bdb0b8e2770)
 - [f3f9cff9a1a707db0b022748662888c559e44d4a](https://github.com/magento/magento2/commit/f3f9cff9a1a707db0b022748662888c559e44d4a)
 - [3836bd2743d1f68a3443e11c1a0746a69902849c](https://github.com/magento/magento2/commit/3836bd2743d1f68a3443e11c1a0746a69902849c)
 - [d88d1332ec96d548e4da6b187f3909172ecc4ec1](https://github.com/magento/magento2/commit/d88d1332ec96d548e4da6b187f3909172ecc4ec1)
 - [7116fedf8e8e218529c8ce0f8332193f447656db](https://github.com/magento/magento2/commit/7116fedf8e8e218529c8ce0f8332193f447656db)

The fix will be available with the upcoming 2.2.8 release.
