### ISSUE TITLE
Item (Magento\Review\Model\Review\Interceptor) with the same ID "5" already exists.

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [magento/magento2#17745]
### Preconditions

1. Magento 2 version - 2.1.7
2. PHP Version 7.0.30-0
3. SQL - 5.0.12

### Steps to reproduce

1. On product detail page override theme here Magento_Catalog->layout->catalog_product_view.xml,here i paste this code
  `<referenceContainer name="product.info.additional">
        <block class="Magento\Review\Block\Product\View\ListView"  name="custom.product.section.info" template="Magento_Review::product/view/list.phtml"/> 
    </referenceContainer>
`
### Expected result

1.Show Customer Reviews

### Actual result

1. 
1 exception(s):
Exception #0 (Exception): Item (Magento\Review\Model\Review\Interceptor) with the same ID "5" already exists.
Send you screenshot also
![screencapture-52-48-167-177-amazing-grass-the-trio-barley-wheat-alfalfa-240-g-html-2018-08-22-18_45_20](https://user-images.githubusercontent.com/27199724/44465632-c3058400-a63b-11e8-8401-5129e5782042.png)

**Comment by magento-engcom-team** [comment]
Hi @sumeetmobiwebtech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sumeetmobiwebtech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sumeetmobiwebtech** [comment]
@magento-engcom-team 
no

**Comment by ghost** [comment]
@sumeetmobiwebtech, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
