### ISSUE TITLE
Wrong image type is loaded when clicking a swatch image on the category page

### ISSUE THREAD

**Issue by captainfromspace** [magento/magento2#17746]
The default image shown for a product on the category page is either the `category_page_grid` image or the `category_page_list` image. When a user clicks on the a color swatch the image that gets loaded via ajax i `product_page_image_medium_no_frame`. That's the same image used on the product page.

First of all it's just a wast of bandwidth to load larger images than necessary, the `category_page_grid` is  240x300 by default, the loaded image is 564x700. If we take the green `Mona Pullover Hoodlie` product as an example, there we have a 23kb size difference between the default `category_page_grid` and the loaded `product_page_image_medium_no_frame`.

Secondly this becomes an issue if we want to resize the loaded swatch image. If we resize it to be smaller on the category page, the change will kick in on the product page as well. Or if we resize the product page image, then we'll might get an ever larger size (kb) difference on the category page.

So I would like to suggest that the black magic handling the swatches returns the same image type as the default. On a category page it returns the `category_page_grid` or the `category_page_list` image type, depending on view mode. Or that a new image type is added, let's call it `category_page_grid_swatch`.

### Preconditions

1. Magento version: 2.2.5
2. Theme: Luma
3. Sample data

### Steps to reproduce

1. Open your browser Developer Tools -> Network.
2. Go to `Women > Tops > Hoodies & Sweatshirts`
3. Click any of the color swatches to reload the product image

### Expected result
1. The same image type/size should be loaded

### Actual result
1. A different image type with bigger size is loaded, in this case the image type getting loaded is `product_page_image_medium_no_frame` when the original image type is the `category_page_grid`

**Comment by magento-engcom-team** [comment]
Hi @captainfromspace. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@captainfromspace do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by captainfromspace** [comment]
Confirmed @magento-engcom-team

**Comment by captainfromspace** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @captainfromspace. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @captainfromspace, here is your [Magento instance](https://i-17746-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17746-2-2-5.engcom.dev.magento.com/admin](https://i-17746-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@captainfromspace, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by somat211** [comment]
Hello Team,
I am working on this.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @captainfromspace The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by goranhorvathr** [comment]
Hello. Where was this issue fixed? This is still existing in 2.2 as an issue and proposed solution here is not a solution. There needs to be two separate callings one for grid one for list like category_page_grid_swatch and category_page_list_swatch so we can have freedom in resizing swatches images without hacking our way out of it and not affecting the PDP page.
