### ISSUE TITLE
Misleading error in Add Product Attribute screen

### ISSUE THREAD

**Issue by milossh** [magento/magento2#17754]
### Preconditions
1. Magento 2.2.5

### Steps to reproduce
1.  Navigate to Store->Attributes->Product
2.  Add new attribute
3.  Set Attribute Code to Foo_Bar
4. Click Save

### Expected result
1. An error message saying that capital letters are not allowed in Attribute Code field

### Actual result
1. Following error message: 

> Please use only letters (a-z), numbers (0-9) or underscore (_) in this field, and the first character should be a letter.

**Comment by magento-engcom-team** [comment]
Hi @milossh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@milossh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by milossh** [comment]
Yes.

**Comment by ghost** [comment]
@milossh , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by slavvka** [comment]
Hi @milossh. Thank you for your report. 
The issue has been fixed in magento/magento2#17800 by @aman3103 in 2.3-develop branch
Related commit(s):
 - [9aa4cfa46f723e9d584d9bf014489f63af92d4dc](https://github.com/magento/magento2/commit/9aa4cfa46f723e9d584d9bf014489f63af92d4dc)
 - [18e509c94f26406c3c73e1b16529d46de1ecbb78](https://github.com/magento/magento2/commit/18e509c94f26406c3c73e1b16529d46de1ecbb78)
 - [9a15e1f99ec742b96572285a6dd4dfb118c11d94](https://github.com/magento/magento2/commit/9a15e1f99ec742b96572285a6dd4dfb118c11d94)
 - [6a0485ffdcd0af8bcff9b01fee06bde60c427858](https://github.com/magento/magento2/commit/6a0485ffdcd0af8bcff9b01fee06bde60c427858)
 - [b6a899f0a0ef8fd45d94051f6267b6f95cda4fb3](https://github.com/magento/magento2/commit/b6a899f0a0ef8fd45d94051f6267b6f95cda4fb3)

The fix will be available with the upcoming 2.3.1 release.

**Comment by milossh** [comment]
@slavvka  Should I close this issue, then?

**Comment by TomashKhamlai** [comment]
@milossh, nope. Not yet. Thank you for contributing.

**Comment by ghost** [comment]
Hi @milossh , thank you for you report, this issue has already fixed in 2.3-develop branch, and will be available on 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @milossh. Thank you for your report. 
The issue has been fixed in magento/magento2#17806 by @saravananvelu in 2.3-develop branch
Related commit(s):
 - [90b1c761e87f958cde0fda4710086234547d354e](https://github.com/magento/magento2/commit/90b1c761e87f958cde0fda4710086234547d354e)
 - [22c185efdf7c72f5967f0537b00af17df9d753d6](https://github.com/magento/magento2/commit/22c185efdf7c72f5967f0537b00af17df9d753d6)

The fix will be available with the upcoming 2.3.1 release.
