### ISSUE TITLE
M2.1.5, Checkout Shipping Address Popup Validation Error 'Please enter less or equal than {0} symbols' on empty 2nd address line when adding new address

### ISSUE THREAD

**Issue by kaushik-kumar-roy** [magento/magento2#17758]
### "Please enter less or equal than 255 symbols."

**Preconditions**
- Magento 2.1.5
- PHP Version 7.0.30 
- MySQL Ver 14.14 Distrib 5.7.23, for Linux (x86_64)

**Steps to reproduce**
- Add product to cart and go to checkout page.
- Add new shipping address and place order.
- Again come back to checkout page with a new product in cart.
- Click "+ New Address" button.

**Expected result**
- Nothing except input fields are filled with values from default address.

**Actual result**
- Additional input fields of Street address is having a validation message as "Please enter less or equal than 255 symbols."

![add_new_shipping address error](https://user-images.githubusercontent.com/18119362/44511963-b8e49380-a6d6-11e8-97ca-5876e3ff4825.png)

**Comment by magento-engcom-team** [comment]
Hi @Kaushik-Roy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Kaushik-Roy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Kaushik-Roy I'm not able to reproduce following steps you described.
 we are closing this issue, If you'd like to update it, please reopen the issue.
![selection_061](https://user-images.githubusercontent.com/40756439/44516732-83d44300-a6ce-11e8-9fd2-cbc47e29830a.png)

**Comment by kaushik-kumar-roy** [comment]
Found and Implemented a trick to it :-
[https://magento.stackexchange.com/questions/239657/magento-2-please-enter-less-or-equal-than-255-symbols-valiadtion-error-in-chec/239738#239738](url)
