### ISSUE TITLE
Multiselect product attribute doesn't work with product list widget

### ISSUE THREAD

**Issue by vincent2090311** [magento/magento2#17752]
Add product list widget to cms page/block with multi-select attribute filter doesn't work. Magento return wrong result due SQL query mismatch. The result is missing some products

### Preconditions

1. Magento CE 2.2.5
2. Default Luma theme
3. Sample data
4. Nginx 1.14
5. Mysql 5.7
6. PHP 7.0

### Steps to reproduce

1. go to any cms page and add new widget like this (activity is product multiselect attribute)
![capture 2018-08-22 at 22 51 14](https://user-images.githubusercontent.com/8340835/44475034-3c15d300-a65e-11e8-9e7a-37da084ddfb6.png)
2. Go to cms page you just added widget and here is result
![capture 2018-08-22 at 22 54 45](https://user-images.githubusercontent.com/8340835/44475132-78493380-a65e-11e8-9211-36b69193f7a7.png)

### Expected result

1. [Screenshots, logs or description]

![capture 2018-08-22 at 22 57 32](https://user-images.githubusercontent.com/8340835/44475284-ccecae80-a65e-11e8-9651-2bbdff887d0e.png)

### Actual result

1. [Screenshots, logs or description]

![capture 2018-08-22 at 22 56 41](https://user-images.githubusercontent.com/8340835/44475225-acbcef80-a65e-11e8-9a65-7ebd66d77414.png)

Note: I enabled product flat data and already reindexed before test

- As my investigation, the problem is this condition
`WHERE (((IFNULL(`e`.`activity`, 0) IN ('11')) ))`
if we use like this (without quote around 11) it should work
`WHERE (((IFNULL(`e`.`activity`, 0) IN (11)) ))`

**Comment by magento-engcom-team** [comment]
Hi @vincent2090311. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vincent2090311 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @vincent2090311 , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17752-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17752-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17752-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by eduard13** [comment]
@vincent2090311 thank you for reporting the issue, but unfortunately I wasn't able to reproduce it on 2.3 instance. 
<details><summary>Products</summary>

![426a55488a](https://user-images.githubusercontent.com/15868188/47253586-b0ea6b00-d45d-11e8-84ed-8f52fb4e55cc.jpg)
</details>
<details><summary>Home CMS Page</summary>

![a14b5ab3ea](https://user-images.githubusercontent.com/15868188/47253606-eee78f00-d45d-11e8-9831-8b51724c87a8.jpg)
</details>
<details><summary>Frontend Result</summary>

![6950a9c575](https://user-images.githubusercontent.com/15868188/47253622-20605a80-d45e-11e8-847e-4fc9ba3cc49b.jpg)
</details>
</br>
Please feel free to reopen the issue, if it's still reproducible for you and you can provide some additional info.</br>
Thank you.
