### ISSUE TITLE
magento 2.2.4 | file permission problem

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#17757]
- issue
RuntimeException : Cant Create Directory

- environment
Centos 6
php 7.1
magento 2.2.4

- steps to reproduce
php bin/magento setup:di:compile

- expectation and actual result
it should work fine, but it gives permission problems, and i always have to login as root and change all public_html folder ownership again to cpanel user then run chmod on ( pub, generated and var ) folders

this is issue came to exists after upgrading from magento 2.2.3 to magento 2.2.4

**Comment by magento-engcom-team** [comment]
Hi @salehawal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@salehawal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by salehawal** [comment]
why failed, what is not clear?

**Comment by ghost** [comment]
@salehawal, when you click "new issue", a template is provided. Your issue structure should be based on this template.

**Comment by ghost** [comment]
Also, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
