### ISSUE TITLE
M2.2.5 : CustomerRepository::getList() does not load custom attribute if the name is "company"

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#17759]
I have custom EAV attributes named "company" for customers, but this is not loaded if I use the `CustomerRepository::getList()`-method. Other custom attributes seem to be loaded properly.

### Preconditions

1. Magento 2.2.5

### Steps to reproduce

1. Create customer EAV attribute named "company" (varchar)
2. Populate it with some data
3. Load it with `CustomerRepository::get() / getById()`
4. Load it with `CustomerRepository::getList()`

### Expected result

In both the situations, `$customer->getCustomAttribute('company')->getValue()` should return the value defined for this attribute.

### Actual result

The `get()` / `getById()`-method loads the proper value, `getList()` returns `NULL`.

### Possible cause

My best guess is that it has something to do with the fact that `getList()` joins the customer address that also has a `company`-column:

    $collection->joinAttribute('billing_postcode', 'customer_address/postcode', 'default_billing', null, 'left')
        ->joinAttribute('billing_city', 'customer_address/city', 'default_billing', null, 'left')
        ->joinAttribute('billing_telephone', 'customer_address/telephone', 'default_billing', null, 'left')
        ->joinAttribute('billing_region', 'customer_address/region', 'default_billing', null, 'left')
        ->joinAttribute('billing_country_id', 'customer_address/country_id', 'default_billing', null, 'left')
        ->joinAttribute('company', 'customer_address/company', 'default_billing', null, 'left');

### Possible solution

I can think of 2 solutions:

- Throw an exception that `company` (or whatever other joined attributed) is a reserved keyword.
- Allow the customer model to override the address attributes (order of loading)

### Workaround

I currently have to do the following workaround (in my situation, my search criteria always returns 1 customer):

    $customers = $customerSearchResult->getItems();
    return $this->customerRepository->getById($customers[0]->getId());

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kanduvisla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@kanduvisla, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by irving0mar** [comment]
#mm18mx

**Comment by magento-engcom-team** [comment]
@irving0mar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @irving0mar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by nik4152** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@nik4152 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @nik4152. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sidolov** [comment]
Hi @kanduvisla. Thank you for your report. 
The issue has been fixed in magento/magento2#19620 by @Militree in 2.3-develop branch
Related commit(s):
 - [d600179622e691be0c24af7dac5b89d24649f3c3](https://github.com/magento/magento2/commit/d600179622e691be0c24af7dac5b89d24649f3c3)
 - [b99af3894130e6d2c90b600d25f6cca4b0a0acd6](https://github.com/magento/magento2/commit/b99af3894130e6d2c90b600d25f6cca4b0a0acd6)
 - [e29c5dda7b4b58384e91752d3e40c578ee0eda7b](https://github.com/magento/magento2/commit/e29c5dda7b4b58384e91752d3e40c578ee0eda7b)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
The issue has been fixed in magento/magento2#20284 by @GovindaSharma in 2.2-develop branch
Related commit(s):
 - [0600244d2c4b9931b72da41ff0cf729d96e031eb](https://github.com/magento/magento2/commit/0600244d2c4b9931b72da41ff0cf729d96e031eb)
 - [a59c0b4e91e61ee242aceba30c16a639f27e2708](https://github.com/magento/magento2/commit/a59c0b4e91e61ee242aceba30c16a639f27e2708)

The fix will be available with the upcoming 2.2.8 release.
