### ISSUE TITLE
Error installing Magento2

### ISSUE THREAD

**Issue by harish-sfdc** [magento/magento2#17763]
I'm trying to install Magento 2.2.5 with sample data. when I hit Install now button in the sixth step, It throwed me many errors in the console. I'm providing you sample Error logs in the console.

[ERROR] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-links_purchased_separately' for key 'EAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE' in C:\xampp\htdocs\Magento2\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php:228 
Stack trace: #0 C:\xampp\htdocs\Magento2\vendor\magento\zendframework1\library\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array)
 #1 C:\xampp\htdocs\Magento2\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array) 
 #2 C:\xampp\htdocs\Magento2\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) 
 #3 C:\xampp\htdocs\Magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
 #4 C:\xampp\htdocs\Magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ea...', Array) 
 #5 C:\xampp\htdocs\Magento2\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(533): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ea...', Array) 
 #6 C:\xampp\htdocs\Magento2\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(596): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `ea...', Array) 
 #7 C:\xampp\htdocs\Magento2\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `ea...', Array)
 #8 C:\xampp\htdocs\Magento2\vendor\magento\module-eav\Setup\EavSetup.php(1466): Zend_Db_Adapter_Abstract->insert('eav_attribute', Array) 
 #9 C:\xampp\htdocs\Magento2\vendor\magento\module-eav\Setup\EavSetup.php(823): Magento\Eav\Setup\EavSetup->_insertAttribute(Array) 
 #10 C:\xampp\htdocs\Magento2\vendor\magento\module-downloadable\Setup\InstallData.php(52): Magento\Eav\Setup\EavSetup->addAttribute('4', 'links_purchased...', Array) 

please guide me to solve this issue

**Comment by magento-engcom-team** [comment]
Hi @harish-sfdc. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@harish-sfdc do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @harish-sfdc thank you for your report.
Please use the issue reporting guidelines to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:

- [ ]  Preconditions: Magento version
- [ ]   Steps to reproduce
- [ ]   Expected result
- [ ]   Actual result

**Comment by harish-sfdc** [comment]
@magento-engcom-team give me {$VERSION} instance

**Comment by harish-sfdc** [comment]
Magento version 2.2.5 (with sample data).
Steps to reproduce
1. Download the 2.2.5 and corresponding XAMPP version.
2. extract the zip folder and place the folder in the XAMPP files
3.. follow the 6 steps process of installation. Hit install now button and after 66% the installation throwed various errors.
![magento](https://user-images.githubusercontent.com/31885025/44521624-53ea6700-a6f1-11e8-88c6-5d957e322a56.PNG)
