### ISSUE TITLE
Edit order page has the same billing and shipping address even when original order has different addresses for Guest 

### ISSUE THREAD

**Issue by HanakJakub** [magento/magento2#17764]
When you edit an order which has different shipping and billing address, new order contains only billing address and shipping address is set as same as billing address. 
### Preconditions

1. Magento CE 2.2.5
2. PHP 7.0.30
3. MariaDB 10.1.34

### Steps to reproduce

1. Create an order with different shipping and billing addresses for **Guest account**
2. Open that order in admin and click Edit to open edit order page
3. Order will have shipping and billing addresses same and Same As Billing Address checkbox is checked
![4100451993 orders operations sales magento admin](https://user-images.githubusercontent.com/17723998/44519973-e3325300-a6ce-11e8-9cbb-00f23d4da9ea.png)

### Expected result

1. New order should have billing address and shipping address set same as original order
![edit order orders operations sales magento admin 1](https://user-images.githubusercontent.com/17723998/44520109-41f7cc80-a6cf-11e8-88be-179b795c6c1f.png)

### Actual result

1. New order got billing address and shipping address the same and checkbox Same As Billing Address is checked
![edit order orders operations sales magento admin](https://user-images.githubusercontent.com/17723998/44520100-3c9a8200-a6cf-11e8-9aa6-c6d3fe982e4c.png)

 ### Possible issue
I found that method `_isSameAsBilling` in file magento/module-quote/Model/Quote/Address.php on line 416 is returning 1 even when the addresses are different.

**Comment by magento-engcom-team** [comment]
Hi @HanakJakub. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@HanakJakub do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@HanakJakub , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue ona clean installation or latest release.

![adress](https://user-images.githubusercontent.com/41946904/44522383-06fd9500-a6df-11e8-9d69-961f21a54543.png)

**Comment by HanakJakub** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @HanakJakub. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @HanakJakub, here is your [Magento instance](https://i-17764-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17764-2-2-develop.engcom.dev.magento.com/admin](https://i-17764-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by HanakJakub** [comment]
@engcom-backlog-andrii Same issue on your 2.2-develop instance. Your screenshot is from created order, but issue is when you are on edit order page as on my screenshots. 
For example some user will order an item and he will tell after place order that he wants to change shipping address and add item. So you will go and hit Edit order button and you will have correct billing address but shipping address form is selected as Same as billing address and you cannot edit shipping address.

**Comment by ghost** [comment]
@HanakJakub , thank for you update.
We were not able to reproduce this issue by following the steps you provided on edit order page too. Admin can change shipping or billing address.
See screenshots

![customer_adress_storefront](https://user-images.githubusercontent.com/41946904/45139742-77191a00-b1b9-11e8-843e-6a6ee9ed8510.png)

![order_create](https://user-images.githubusercontent.com/41946904/45139754-7da79180-b1b9-11e8-8238-c11e28aa959f.png)

![edit_order_admin](https://user-images.githubusercontent.com/41946904/45139760-8304dc00-b1b9-11e8-9e81-1c435c1b8375.png)

Please provide more detailed steps to reproduce, thank you.

**Comment by HanakJakub** [comment]
@engcom-backlog-andrii thanks for reply.
It looks like it is working for logged in user. Try create order as guest and follow the steps again.

**Comment by ghost** [comment]
@HanakJakub, thank you for your fast update.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by venkateshwaranpdckap** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@venkateshwaranpdckap thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Alfa** [comment]
Hi @HanakJakub. Thank you for your reporting.

We are not able to reproduce this issue on the fresh 2.4-develop instance. Everything works correctly.

**Manual testing scenario:**

1. Create an order with different shipping and billing addresses for Guest account;
2. Open that order in admin and click Edit to open edit order page;

**Actual Result:**
The new order has billing address and shipping address set the same as the original order
![screen](https://user-images.githubusercontent.com/51679138/71720646-16403700-2e2b-11ea-89d5-2a26905583bd.png)
So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
