### ISSUE TITLE
Observer reset all previously added event data

### ISSUE THREAD

**Issue by Bodyanuk** [magento/magento2#17766]
### Preconditions

1. Magento 2.2.3

### Steps to reproduce

1. Create Observer on event `salesrule_rule_condition_combine`
2. Try to add your own `condition`

### Expected result

1. New Rule Condition added

### Actual result

1. Added just 'Customer Segment' condition

The issue happen because `\Magento\CustomerSegment\Observer\AddSegmentsToSalesRuleCombineObserver::execute` method ignore previously added conditions. You can just add you own condition to condition array and after that  SET.
Like:
```php
$conditions = (array) $additional->getConditions();
$conditions = array_merge_recursive($conditions, [
        $this->getQtyCondition()
]);
$additional->setConditions($conditions);
```

**Comment by magento-engcom-team** [comment]
Hi @Bodyanuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Bodyanuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Bodyanuk, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
