### ISSUE TITLE
magent (2.2.5) installation fails

### ISSUE THREAD

**Issue by harish-sfdc** [magento/magento2#17767]
Magento version 2.2.5 (Zip with sample data).

Download the 2.2.5 and corresponding XAMPP version.
extracted the zip folder and place the folder in the XAMPP files
followed the 6 steps process of installation. finally Hit install now button and after 66% the installation throwed various errors.

![magento](https://user-images.githubusercontent.com/31885025/44522410-0f13ff80-a6f4-11e8-9e74-9e76c9f23528.PNG)

**Comment by magento-engcom-team** [comment]
Hi @harish-sfdc. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@harish-sfdc do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by harish-sfdc** [comment]
@magento-engcom-team give me {$} instance

**Comment by ghost** [comment]
Hi @harish-sfdc We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
Please refer to the Community Forums or the Magento Stack Exchange site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by harish-sfdc** [comment]
Hi team,

I want to set up magento2 in my laptop. can you please me tell how to do it.


thanks in advance

**Comment by ghost** [comment]
@harish-sfdc, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
