### ISSUE TITLE
Table rate fail when using ZIP+4 shipping address

### ISSUE THREAD

**Issue by maximecarey** [magento/magento2#17770]
### Summary
When a customer enters an American customer enters a ZIP+4 inside the ZIP code field, the table rate shipping method fails to return a quote.

### Preconditions

1. Linux
2. Magento 2.2.5
3. PHP 7.1.20

### Steps to reproduce

1. Create a Product with weight >= 1.
2. Enable the Table shipping rate 
3. Import the rate CSV file:
`Country,Region/State,Zip/Postal Code,Weight (and above),Shipping Price`
`USA,*,12345,1,2`
4. Create a customer on the frontend with a zip code in the format ZIP+4 (ex: 12345-1234).
5. Add Product to your cart
6. Go to checkout

### Expected result

1. The table rate shipping method should ignore the extension and  appear with a 2$ shipping fee.

### Actual result

1. The table rate shipping is not present.

**Comment by magento-engcom-team** [comment]
Hi @werfu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@werfu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by maximecarey** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @werfu. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @werfu, here is your [Magento instance](https://i-17770-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17770-2-2-5.engcom.dev.magento.com/admin](https://i-17770-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@werfu, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @werfu. Thank you for your report. 
The issue has been fixed in magento/magento2#18166 by @magently in 2.2-develop branch
Related commit(s):
 - [6e4a4b2d85e25c58e72914a7904a5dc9aa7e43f5](https://github.com/magento/magento2/commit/6e4a4b2d85e25c58e72914a7904a5dc9aa7e43f5)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @werfu. Thank you for your report. 
The issue has been fixed in magento/magento2#18499 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [fe3fd54c10a2e198684e418d743e50cd03fc99b8](https://github.com/magento/magento2/commit/fe3fd54c10a2e198684e418d743e50cd03fc99b8)

The fix will be available with the upcoming 2.3.1 release.
