### ISSUE TITLE
Catalog search results randomised on refresh

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#17787]
Similar to issue #9020, but present on Magento 2.2.x. Search term results are not sorted in the same sequence between page refreshes. This is most often apparent when a user clicks on the product, then hits the back button to return to the search results.

### Preconditions

1. Magento 2.2
2. Large number of products with similar keywords.

### Steps to reproduce

1. Search for a generic keyword that matches many products (e.g. Red).
2. Note product sort order.
3. Indexer reindex && cache flush
4. Refresh page.

### Expected result

1. Products are displayed in same order between page refreshes.

### Actual result

1. All products with the same relevance are randomized each item page refreshes.
2. Products are still sorted according to relevance, but equal relevance products are not kept in a consistent order.

![default](https://user-images.githubusercontent.com/40756187/44649597-06ba0e00-a9ed-11e8-9cfb-4536c8ffc190.png)

![default](https://user-images.githubusercontent.com/40756187/44649563-f43fd480-a9ec-11e8-8d38-11350cc5e4ca.png)

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BezV8 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by BezV8** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @BezV8, here is your [Magento instance](https://i-17787-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17787-2-2-3.engcom.dev.magento.com/admin](https://i-17787-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by BezV8** [comment]
@magento-engcom-team Can not reproduce issue as unable to reindex vanilla instance.

**Comment by ghost** [comment]
@BezV8, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by eduard13** [comment]
I wasn't able to reproduce this issue. Feel free to open if you have any additional info.

**Comment by mslabko** [comment]
The issue is acknowledged and should be fixed in further releases
Internal: MAGETWO-94583

**Comment by engcom-Charlie** [comment]
I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**

1. Search for a generic keyword that matches many products (e.g. Red).
![image](https://user-images.githubusercontent.com/51680850/64234815-bf1f6980-ceff-11e9-8c6b-aa7b240fc23e.png)

2. Note product sort order.
3. Indexer reindex && cache flush
4. Refresh page.

**Actual result:**
Products are displayed in same order between page refreshes.
![image](https://user-images.githubusercontent.com/51680850/64234935-ff7ee780-ceff-11e9-8ed6-1bd0b45dabc7.png)

So it fixed now.
