### ISSUE TITLE
Next Page button triggered when filtering Customer grid

### ISSUE THREAD

**Issue by lucasjor-summa** [magento/magento2#17789]
### Preconditions

1. Magento 2.2.2
2. 20+ customers created in order to have many pages in Customer grid

### Steps to reproduce

1. Go to "Sales -> Orders"
2. "Create new order"
3. Customer grid is displayed
4. Focus on any column filter (i.e. text box in email column)
5. Press ENTER to trigger the filter

### Expected result

1. Filter's AJAX call is triggered
2. Results don't change because the filter input was empty
3. Grid is still showing the same page.

### Actual result

1. Filter's AJAX call is triggered
2. Next Page AJAX call is triggered at the same time (see screenshots)
3. Results don't change because the filter input was empty
4. Grid is showing the next page now
![screenshot from 2018-08-24 10 23 48](https://user-images.githubusercontent.com/7723883/44586977-e89fa400-a787-11e8-915f-82bca50163b2.png)
![screenshot from 2018-08-24 10 23 28](https://user-images.githubusercontent.com/7723883/44586979-e89fa400-a787-11e8-8881-ac75d44a17ba.png)

**Comment by magento-engcom-team** [comment]
Hi @lucasjor-summa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lucasjor-summa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by lucasjor-summa** [comment]
I confirm that I was able to reproduce the issue on vanilla Magento 2.2.2 CE

**Comment by ghost** [comment]
@lucasjor-summa , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @lucasjor-summa. Thank you for your report. 
The issue has been fixed in magento/magento2#17870 by @ronak2ram in 2.2-develop branch
Related commit(s):
 - [964d4ef8763df82c7e47860acda7ab855d819b35](https://github.com/magento/magento2/commit/964d4ef8763df82c7e47860acda7ab855d819b35)
 - [4150ad1ffd1061e342167fea15cabb3a51178c81](https://github.com/magento/magento2/commit/4150ad1ffd1061e342167fea15cabb3a51178c81)
 - [6fb0594ab4160c0ea47d58c45757dfde10861d6e](https://github.com/magento/magento2/commit/6fb0594ab4160c0ea47d58c45757dfde10861d6e)

The fix will be available with the upcoming 2.2.7 release.

**Comment by ishakhsuvarov** [comment]
Hi @lucasjor-summa. Thank you for your report. 
The issue has been fixed in magento/magento2#17874 by @ronak2ram in 2.3-develop branch
Related commit(s):
 - [92c1aa48165ffe73ca4b8c0257f77dcf5b573c6f](https://github.com/magento/magento2/commit/92c1aa48165ffe73ca4b8c0257f77dcf5b573c6f)
 - [a2993a5f9444147c2275549decf9ef0ecc52b336](https://github.com/magento/magento2/commit/a2993a5f9444147c2275549decf9ef0ecc52b336)
 - [c580a464eb576b818491d3f36635b731a4623eef](https://github.com/magento/magento2/commit/c580a464eb576b818491d3f36635b731a4623eef)

The fix will be available with the upcoming 2.3.0 release.
