### ISSUE TITLE
Security issue - spam-Attack shuts down Magento

### ISSUE THREAD

**Issue by matin73** [magento/magento2#17788]
### Preconditions

1. Install Magento2
2. "Wait for attack"

### Steps to reproduce

1. Massiv spam attack from China and Hongkong with thousands of different IP addresses call customer/create/account ...
2. Server error after some minutes 

### Expected result

1. Block spamers

### Actual result

1. No blocking

In last week we had big problems with Magento 2.1 and 2.2. There is a massiv spam attack form asia (China and Hongkong mostly) with thousands of different IP adresses at same time calling Magento customer create account url and fill database with spams. Also server is gone because of too many requests same time.

There should be a security update to avoid this.
Martin

**Comment by magento-engcom-team** [comment]
Hi @matin73. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@matin73 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by matin73** [comment]
@matin73 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

 x   yes
    no

**Comment by ishakhsuvarov** [comment]
Hi @matin73 
Please refer to the https://magento.com/security resource if you believe that you have found a security issue. There is a different reporting process for this kind of issues.

Thank you
