### ISSUE TITLE
Question for the Purge Experts!

### ISSUE THREAD

**Issue by N1ghtfl0w** [magento/magento2#17797]
Im looking for a person that can help us find and fix the problem with our caching! Cause nobody can seem to find it.

Setup:
Magento 2.2.4 Multi-Store 
(running on Apache server)
Varnish 5.2.1 (in combination with Hitch to handle ssl)
Redis 4.0.11

Problem:
When saving a product not only the related categories/products gets invalid but the whole varnish gets invalid? We have over 10.000 products and if we edit one of them the whole site needs to be warmed up again... 

We checked the varnish logs and found out that magento is sending 2 purge requests: 
the first one only for the product.
the second one for the product and all related categories.

![first-purge](https://user-images.githubusercontent.com/42296457/44597968-c894d280-a7d1-11e8-8e42-49e49df8db6b.jpg)
![second-purge](https://user-images.githubusercontent.com/42296457/44597969-c894d280-a7d1-11e8-9d82-c2968424642c.jpg)

If i'm correct Varnish bans every page that has one of the Tags in the header. So if we take a look at the second request it shows cat_c_1 that's the root category and cat_c_2 is our website. Could this be the reason why every page is invalid cause every page is related to cat_c_2?

if so can we remove the categories from the purge request?

**Comment by magento-engcom-team** [comment]
Hi @N1ghtfl0w. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@N1ghtfl0w do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by torhoehn** [comment]
In [#17600](https://github.com/magento/magento2/issues/17600#issuecomment-413451495) you have been referred to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](https://magento.stackexchange.com/). So I'm closing this issue.

**Comment by N1ghtfl0w** [comment]
@torhoehn i asked the same question in #17600 but didn't get an answer yet. Also the are purges being send with the core code? That's why im asking here ;). 

I also posted this question on the Community Forums and Stack Exchange.

**Comment by jesperbrejning** [comment]
Hi N1ghtfl0w, 

I think we see the same issue as you.

 - have you found a solution?
