### ISSUE TITLE
Seems that `catalog_product_entity_media_gallery` contains unused `disabled` field.

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#17796]
Seems that DB table `catalog_product_entity_media_gallery` contains legacy unused column: `disabled`.

In [processNewImage()](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/Product/Gallery/CreateHandler.php#L273) `disabled` field not set.

This field used in [createBatchBaseSelect()](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Gallery.php#L222) but seems that it doesn't make sense, because there is no way to change `disabled` field by admin panel (field 'disabled' changed in `catalog_product_entity_media_gallery_value` when its disabled from admin panel ("Hide from Product Page" in image detail modal)). 

### Preconditions
1. Magento v2.2.5 CE

### Steps to Reproduce
-

### Expected result

1. Table `catalog_product_entity_media_gallery` without`disabled` field.

### Actual result

1. Table `catalog_product_entity_media_gallery` with `disabled` field.

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@likemusic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@likemusic, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-17796-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-17796-2-3-develop.engcom.dev.magento.com/admin](https://i-17796-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VadymKalin** [comment]
#squashtoberfest

**Comment by magento-engcom-team** [comment]
@VadymKalin thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sanjaybharti** [comment]
#MM19IN

**Comment by magento-engcom-team** [comment]
@sanjaybharti thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @sanjaybharti. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sanjaybharti** [comment]
Verified that the issue is reproduced on 2.3-develop branch
