### ISSUE TITLE
PayPal via Braintree: Partial Invoice & Payment Capture Not Working as Expected after first is created. 

### ISSUE THREAD

**Issue by duffner** [magento/magento2#17798]
### Preconditions

1. Magento 2.2.5 (Vanilla) 
2. PayPal Express Enabled via Braintree (Out-of-box) (Screen-shot attached) 
3. PayPal is set to "Authorize Only" not "Capture"

### Steps to reproduce

1. Place Order Via PayPal Express (PayPal Button) for 2 products at $25.00 each 
2. Order total is $50.00 
3. Authorization is successfully captured for $50.00
3. Create Partial Invoice for 1 of the 2 items.
4. Invoice is successfully created for $25.00 and Payment is Captured in PayPal
5. Create Invoice for the second item separately 

### Expected result

1. Capture for the remaining authorization occurs 
2. Payment capture is recorded in PayPal
3.  The second Invoice is created in Magento for $25.00
4. $50.00 has been captured by PayPal and is recoded in their dashboard

### Actual result

1. Capture for the remaining payment does not occur
2. Payment capture does not exist within PayPal 
3.  There is a second invoice created for $25.00 
4. Magento records the payment receipt as successful but it is not 

After a quick code review, it appears that PayPal is enabled for Partial Invoices, however, a request to capture the remaining part of the authorization does not take place.  This issue cost my customer thousands of dollars as authorizations occurred in Magento and recorded as successful, but the remaining payment was never captured. 

After a lengthy discussion with PayPal/Braintree support, they found this to be a bug of Magento as PayPal allows for mutliple captures against a single authorization.  Additionally the payment method is configured in Magento to allow for this behavior but it does not work as expected.   

Attached below are the current settings of PayPal via Braintree and records from Magento for an example order.  Has this been solved?  

![braintree_settings_paypal](https://user-images.githubusercontent.com/7387019/44620776-d729cb00-a85f-11e8-87a0-39e45178db22.png)

<img width="1028" alt="magentoinvoices" src="https://user-images.githubusercontent.com/7387019/44620777-df820600-a85f-11e8-9263-2ee3d9815c15.png">

<img width="664" alt="recordinmagento" src="https://user-images.githubusercontent.com/7387019/44620778-e446ba00-a85f-11e8-9d74-8071f859c7d3.png">

<img width="1136" alt="paypaldashboard" src="https://user-images.githubusercontent.com/7387019/44620781-e872d780-a85f-11e8-9fb9-7cc94ac337f6.png">

**Comment by magento-engcom-team** [comment]
Hi @duffner. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@duffner do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @duffner, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by RostislavS** [comment]
Hi @duffner , Your concern is clear and you're right that Paypal has such functionality as multiple charges of the same transaction. But, Braintree doesn't have such functionality. Braintree allows to charge an authorized transaction only one, right after that rest of transaction amount is released. Therefore, it is impossible to implement the requested feature in Magento until Braintree has such feature in their API. 
I decided to check what happens if I try to send a request for the second charge as in your example. Braintree returned error message "Cannot submit for settlement unless status is authorized."
Here is documenation which is saying the same https://developers.braintreepayments.com/guides/transactions/php#settlement

**Comment by duffner** [comment]
@RostislavS, I see your reference to the docs and I'd be inclined to agree. However, if this is not supported behavior, shouldn't Magento at minimum pass the "Cannot submit for settlement unless status is authorized" error message onto the user.  Most merchants don't give direct access to their merchant accounts, and with this Customer Service members could be doing this for months before it's noticed.

**Comment by ghost** [comment]
@RostislavS why has this issue been closed when it was acknowledged and replicated in 2.3?

Whilst Braintree may not provide the services required to do a partial invoice, until that point, Magento should be fix so this error does not occur.

**Comment by ghost** [comment]
@RostislavS looks like Braintree nows supports partial settlements

https://developers.braintreepayments.com/reference/request/transaction/submit-for-partial-settlement/php
