### ISSUE TITLE
Magento 2 in Localhost Xammp PHP 7.1 is very slow how to make it fast for development.

### ISSUE THREAD

**Issue by mano1617** [magento/magento2#17811]
### Title 
Magento 2 is very slow in localhost , how to make it faster for development purpose.

### Preconditions
1.  My System configuration is 4gb Ram Windows 7
2.  I use Xampp with PHP 7.1.20
3. Apache/2.4.34 (Win32) OpenSSL/1.0.2o PHP/7.1.20
   Database client version: libmysql - mysqlnd 5.0.12-dev - 

### Steps to reproduce
 After installing Magento2 in localhost i made following changes to make development site work faster, please find the below changes which i did

  1. Enabled Varnish cache from admin panel 
     Store-> Configuration-> System -> Full page cache -> change “Caching Application” to Varnish 
     cache.
  2. Set Developer mode on from env.php and using command prompt.
  3. Disabled cache from admin login screen.
  
After making any changes suppose i override a theme css or core modules each time its taking very long time like 108 seconds to run a deploy command. 

And after running all the needed CLI commands i have to wait for so long time to see the changes.

### Actual and Expected result
Please let me know what i can do to make it work best in localhost.

### Additional information
Give some tips which would be a best option for working environment.

Thanks in advance

**Comment by magento-engcom-team** [comment]
Hi @mano1617. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mano1617 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@mano1617 , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
See please this official information about Operating systems

https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html
