### ISSUE TITLE
Can't use plugin for Magento\Customer\Model\AccountManagement::isEmailAvailable()

### ISSUE THREAD

**Issue by mage2dev** [magento/magento2#1781]
Plugin afterIsEmailAvailable() doesn't load when isEmailAvailable() is called through rest api from the checkout page ( /index.php/rest/default/V1/customers/isEmailAvailable ). 
To reproduce create an after plugin for isEmailAvailable() and type email address on checkout. Original method isEmailAvailable() will be called through api, but plugin won't.

**Comment by mage2dev** [comment]
It doesn't work if di.xml is located in etc/frontend, but it works if I move it to etc.

**Comment by okorshenko** [comment]
@mage2dev, thank you for reporting. 
There is no issue in described use case. You can declare a plugin in specific area (such as frontend, backend, webapi_rest, webapi_soap) or for all areas simultaneously using global area (ModuleName/etc/di.xml file). This behavior was implemented by design. More details you can find [here](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/plugins.html)

**Comment by mage2dev** [comment]
Thanks.
