### ISSUE TITLE
Creating customizable option for specific store view applies to all store views...

### ISSUE THREAD

**Issue by gitfredrik** [magento/magento2#17818]
I´m trying to create a customizable option for only one store view but I can´t seem to do that. However I try the option is applied to all store views.

### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Have several store views.
2. Go to any product and change the scope to a specific store view
3. Create a customizable option. Save.

### Expected result

1. The customizable option should be created for the specific store view only and not visible if scope is set to "All store views" or any other store view.

### Actual result

1. Customizable option is created for all store views and also visible in frontend for all of them

**Comment by magento-engcom-team** [comment]
Hi @gitfredrik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gitfredrik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sskulkarni** [comment]
Hello @magento-engcom-team 
I Can also reproduce this issue.
I am working on it.
Thanks

**Comment by ghost** [comment]
@gitfredrik , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by gitfredrik** [comment]
This is my first report and I see all these labels. Do they men that this is an issue that will be fixed in a future update? We have a client that would really benefit from being able to set customizable option in only one store view. It´s a country where they have to charge an extra fee on some specific products but they don´t need to in other countries. That´s why we need it only in one store view.
Thanks

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by abramchukm** [comment]
Actually this is not an issue this is feature request. Customizable option can not be created for specific store view.
