### ISSUE TITLE
category/product page and products graphQL query throws fatal error

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#17810]
### Preconditions
1. magento 2.3 develop 9d6399ea35637ddf21ee35441805d91364a34fe5
2. php 7.1
3. mysql 5.7

### Steps to reproduce
1. open category or product page or graphQL endpoint for product data
2. observe fatal error

### Expected result
1. Category/Product page should be visible and functional
2. products() GraphQL query should work

### Actual result
1. pages throws fatal error

```
Fatal error: Uncaught Error: Cannot instantiate interface Magento\Framework\Search\Request\IndexScopeResolverInterface in /var/www/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:50 Stack trace: #0 /var/www/public/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...') #1 /var/www/public/vendor/magento/magento2ce/app/code/Magento/CatalogSearch/Model/Search/FilterMapper/ExclusionStrategy.php(90): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...') #2 /var/www/public/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(116): Magento\CatalogSearch\Model\Search\FilterMapper\ExclusionStrategy->__construct(Object(Magento\Framework\App\ResourceConnection\Interceptor), Object(Magento\Store\Model\StoreManager), Object(Magento\CatalogSearch\Model\Adapter\Mysql\Filter\AliasResolver), NULL, NULL, Object(Magento\Catalog\Model\Indexer\Product\Price\PriceTableRes in /var/www/public/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
```

**Comment by magento-engcom-team** [comment]
Hi @kandrejevs. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kandrejevs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@kandrejevs, thank you for your report.
Please update title, steps to reproduce and expected results. Currently, they are inconsistent and not obvious.

**Comment by raivisdejus** [comment]
Seems that this can be solved by adding 
`<preference for="Magento\Framework\Search\Request\IndexScopeResolverInterface" type="Magento\Framework\Indexer\ScopeResolver\IndexScopeResolver"/>`
to `di.xml`

**Comment by kandrejevs** [comment]
can be closed, it was bug due specific docker setup

**Comment by mysil2** [comment]
@kandrejevs what was your solution in fixing this in your docker setup? I also got this error and resolved it as per @raivisdejus answer. I'm also using a docker setup, but can't find out why this is happening. 

Edit: Started happening when I upgraded from 2.2.5 to 2.2.6

**Comment by raivisdejus** [comment]
@mysil2 our setup had the usual magento dirs like /bin, /lib or /setup in the repo root. When updating among versions the same folders get changed in the /vendor/magento/, but not in our repo root, so our solution was to copy the content from /vendor/magetno/magento2ce/lib to /lib in repo root.

The setup stragneness is related to the fact that we are working on bleeding edge 2.3, but if your setup also has /lib or other system folders in the root, check if content is the same as in vendor
