### ISSUE TITLE
Unable to add bundle product in configurable product

### ISSUE THREAD

**Issue by shafalibhatia** [magento/magento2#17827]
Unable to add bundle product in configurable product
    
### Preconditions
1. Magento 2

### Steps to reproduce
1. Create a bundle product and add multiple simple products in it 
2. Create a configurable product and try to add products manually

### Expected result
1. Bundled product should be added to configurable product.

### Actual result
1.  Bundled products are shown in available attributes and after selecting it disappeared 
     from configured product

**Comment by magento-engcom-team** [comment]
Hi @shafalibhatia. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@shafalibhatia do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@shafalibhatia, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Bundled products are not shown in available products in "Select Associated Product" menu. If you'd like to update it, please reopen the issue.

**Comment by shafalibhatia** [comment]
Steps
1.Create a configurable product and use some attribute Color(red,blue). After product creation, two virtual products are created and one attribute named as color is added in attribute set.
2.Create a bundle product and both virtual product in it and select color as red in attribute value of bundled product.
3. Go to configurable product created in first step and try to associate a different product for red color. Then available products shows bundle product as well . Select bundle product and save it.
Actual output: Bundle product is removed from configurable product.

Is their a way to add bundle product into configurable product??

**Comment by ghost** [comment]
@shafalibhatia, thank you for clarification. Seems like your issue is caused by some custom code, as you cannot set any 'color' attribute value for bundle product in clean Magento 2.  Please try to reproduce this issue on a clean installation of the latest Magento 2 release.

**Comment by shafalibhatia** [comment]
Ok..Is their a way to add bundle products in configurable products?

**Comment by ghost** [comment]
@shafalibhatia, I think no. We have two 'groups' of product types - 'simple' (simple, virtual, downloadable) and 'complex' (configurable, grouped, bundle). You can assign any 'simple' type product to 'complex', but not 'complex' to 'complex'.
Anyway, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
