### ISSUE TITLE
Web setup wizard not visable, Magento 2.2.5

### ISSUE THREAD

**Issue by bluesound** [magento/magento2#17821]
I have recently updated from 2.2.4 to 2.2.5. And I wuld like to use the web setup wizard to install a modulem however when I access the menu I get a white screen. So the url goes to  /setup/index.php, but the page does not show up, so at the moment I can not update nor install any module via the usual way. Any idea what could be causing this? It worked in 2.2.4...

**Comment by magento-engcom-team** [comment]
Hi @bluesound. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bluesound do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@bluesound , thank you for your report.
Also, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
