### ISSUE TITLE
Magento 2.3.x incomplete ConfigurableProduct setup dependencies

### ISSUE THREAD

**Issue by Swahjak** [magento/magento2#17836]
Magento\ConfigurableProduct\Setup\Patch\Data\InstallInitialConfigurableAttributes should have a dependency on (at least) Magento\Msrp\Setup\Patch\Data\InitializeMsrpAttributes.

### Preconditions

1. Magento 2.3.0-alpha62

### Steps to reproduce

1. None

### Expected result
1. 
```php
class InstallInitialConfigurableAttributes implements DataPatchInterface, PatchVersionInterface
{
//...
    /**
     * {@inheritdoc}
     */
    public static function getDependencies()
    {
        return [
           Magento\Msrp\Setup\Patch\Data\InitializeMsrpAttributes::class
       ];
    }
//...
}
```

### Actual result

1.
```php
class InstallInitialConfigurableAttributes implements DataPatchInterface, PatchVersionInterface
{
//...
    /**
     * {@inheritdoc}
     */
    public static function getDependencies()
    {
        return [];
    }
//...
}
```

**Comment by magento-engcom-team** [comment]
Hi @Swahjak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Swahjak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment]
Hello @Swahjak, thank you for your report and pull request.
We've acknowledged the issue and added to our backlog.

**Comment by Swahjak** [comment]
Since nobody has commented this has been fixed I'm going to assume it's still open.

**Comment by Swahjak** [comment]
Still not stale
