### ISSUE TITLE
Child theme does not inherit translations from parent theme

### ISSUE THREAD

**Issue by rossmc** [magento/magento2#17833]
**Summary of the issue**
Theme inheritance does not work as expected with [translation dictionaries][1].  The child theme does not use any translations defined in it's parent theme's `en_US.csv` translation dictionary.

**Preconditions**
I'm working on a Magento ver 2.2.5 installation with two websites & two corresponding theme's.  Each with their own [translation dictionary][1], and one theme inheriting from the other.

**Steps to reproduce**
1. Set up a magento instance with two websites and with two theme's, one inheriting from luma and the other inheriting from the other theme you created.  See theme structure below.
2. Add a the translation string `"Create New Customer Account","Create New Account"` to the parent theme's `en_US.csv` translation dictionary.
3. Go to the _/customer/account/create/_ URL for the website with the child theme applied.

**Expected result**
The page title should be _Create New Account_

**Actual result**
The page title is still _Create New Customer Account_

- If go to the _/customer/account/create/_ URL for the website with the parent theme applied, the page title should is _Create New Account_.  So the child theme is not picking up translations from the parent theme.
- If you add the translation string `"Create New Customer Account","Create New Account"` to the Child theme's `en_US.csv` translation dictionary you can see the translation string applied corectly on the website with the child theme applied.

Is this a bug with Magento or am I doing something wrong?

Is the [translation dictionary][1] documentation incorrect and this is actually the correct behaviour?

----------

**Theme Structure**

    app/design/frontend/Ross
    │
    ├── parent
    │   ├── composer.json
    │   ├── i18n
    │   │   └── en_US.csv
    │   ├── registration.php
    │   └── theme.xml
    │   
    └──  child
        ├── composer.json
        ├── i18n
        │   └── en_US.csv
        ├── registration.php
        └── theme.xml

**Parent's theme.xml**

    <theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
        <title>Ross Parent</title>
        <parent>Magento/luma</parent>
    </theme>

**Child's theme.xml**

    <theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
        <title>Ross Child</title>
        <parent>Ross/parent</parent>
    </theme>

  [1]: https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/translations/theme_dictionary.html

**Comment by magento-engcom-team** [comment]
Hi @rossmc. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rossmc do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ghost** [comment]
@rossmc, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by SavchenkoVladimir** [comment]
#khcd2018

**Comment by magento-engcom-team** [comment]
@SavchenkoVladimir thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vpodorozh** [comment]
#mageconf

**Comment by vpodorozh** [comment]
This commit `cf313ba` was made with incorrect author git config - that is why Anton Evers was added as an author. I've removed this branch and will re-create my commit with correct author config.

**Comment by sidolov** [comment]
Hi @rossmc. Thank you for your report. 
The issue has been fixed in magento/magento2#19018 by @vpodorozh in 2.3-develop branch
Related commit(s):
 - [388fb45eb6ff24b3fe9fc1452bf75db5507ae87c](https://github.com/magento/magento2/commit/388fb45eb6ff24b3fe9fc1452bf75db5507ae87c)
 - [6a35e24869be3384e9f7d86bf6faed132d5b2bf6](https://github.com/magento/magento2/commit/6a35e24869be3384e9f7d86bf6faed132d5b2bf6)
 - [21f52259c1f435a0fcb31ceb6f8a664fc2b7bf6c](https://github.com/magento/magento2/commit/21f52259c1f435a0fcb31ceb6f8a664fc2b7bf6c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @rossmc. Thank you for your report. 
The issue has been fixed in magento/magento2#19144 by @vpodorozh in 2.3-develop branch
Related commit(s):
 - [57fcc1b24c4c582a96930ff7465e5f74417f2bcc](https://github.com/magento/magento2/commit/57fcc1b24c4c582a96930ff7465e5f74417f2bcc)
 - [fe73cf00549475b0ffc5a470e10ba4f1f3893b78](https://github.com/magento/magento2/commit/fe73cf00549475b0ffc5a470e10ba4f1f3893b78)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @rossmc. Thank you for your report. 
The issue has been fixed in magento/magento2#19023 by @vpodorozh in 2.2-develop branch
Related commit(s):
 - [caa2fe87bcf4d2f452d65119ba8c89672ed60ba6](https://github.com/magento/magento2/commit/caa2fe87bcf4d2f452d65119ba8c89672ed60ba6)
 - [24330d629eca6494445b533126dbc0796605fe4d](https://github.com/magento/magento2/commit/24330d629eca6494445b533126dbc0796605fe4d)
 - [10d9cc9d1a20d9051d7ef95ded7d14cea0585a0d](https://github.com/magento/magento2/commit/10d9cc9d1a20d9051d7ef95ded7d14cea0585a0d)
 - [a3db8d3f789859a096fed08cf1bf2a57987f4bc0](https://github.com/magento/magento2/commit/a3db8d3f789859a096fed08cf1bf2a57987f4bc0)
 - [26ea51e007a9908188f5379a7beab5179888ceff](https://github.com/magento/magento2/commit/26ea51e007a9908188f5379a7beab5179888ceff)
 - [e8a07c95592a7d993890255d0da1312efb5dab78](https://github.com/magento/magento2/commit/e8a07c95592a7d993890255d0da1312efb5dab78)

The fix will be available with the upcoming 2.2.8 release.
