### ISSUE TITLE
Wrong State Title, Displaying Status Label Rather than State

### ISSUE THREAD

**Issue by sskulkarni** [magento/magento2#17847]
### Preconditions

1. Magento 2.2.5 Installed

### Steps to reproduce

1. In Backend - Navigate to Stores > Settings > Order Status

### Expected result

1.It Should display Label of State

### Actual result

1. It is displaying Label of Status.
![order status settings stores magento admin](https://user-images.githubusercontent.com/6185521/44771753-9f859080-ab89-11e8-9a0f-4b104ede3d30.png)

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sskulkarni do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by sskulkarni** [comment]
Yes, confirmed the issue on vanilla 2.2.5 instance already.

**Comment by ghost** [comment]
@sskulkarni, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dmytro-ch** [comment]
I will handle this issue. Thank you.

**Comment by sskulkarni** [comment]
I have already resolved this.
Thanks @dmytro-ch

**Comment by marciowebjump** [comment]
I will handle this in 2.3

**Comment by slavvka** [comment]
Hi @sskulkarni. Thank you for your report. 
The issue has been fixed in magento/magento2#26569 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [e3c203ad5fb0693c55cd3abc383ef6baa43e8b10](https://github.com/magento/magento2/commit/e3c203ad5fb0693c55cd3abc383ef6baa43e8b10)
 - [4e94687ae0c753d9d8d936b9917a8bd65aad001a](https://github.com/magento/magento2/commit/4e94687ae0c753d9d8d936b9917a8bd65aad001a)
 - [1000bcd1bfe1380c613b0486e1557e1acec18958](https://github.com/magento/magento2/commit/1000bcd1bfe1380c613b0486e1557e1acec18958)
 - [ad184d23efcea17cd1d5fe84849b38ed9f1b6636](https://github.com/magento/magento2/commit/ad184d23efcea17cd1d5fe84849b38ed9f1b6636)
 - [6e2d0c841cb716fefd831fe1667acd2013e00c28](https://github.com/magento/magento2/commit/6e2d0c841cb716fefd831fe1667acd2013e00c28)
 - [5474b5f90a853378ac673f296047da09a0e510d5](https://github.com/magento/magento2/commit/5474b5f90a853378ac673f296047da09a0e510d5)

The fix will be available with the upcoming 2.4.0 release.
