### ISSUE TITLE
Time Format is 12H although it should be 24H

### ISSUE THREAD

**Issue by IIxauII** [magento/magento2#17849]
### Preconditions
1.  Magento: 2.2.5
2.  PHP: 7.1.20
3. MySQL: 5.7.23

### Steps to reproduce
1. login to Magento2 admin panel
2. set user locale of currently logged in account to German 
3. set time format under Catalog / Catalog / Date & Time Custom Options / Time Format to 24h

### Expected result
1. under "orders" the time format of the incoming orders should be in 24h format and not 12h(am / pm)

### Actual result
1. under "orders" the time format is 12h(am / pm). Example → Aug 29, 2018 11:02:56 AM

**Comment by magento-engcom-team** [comment]
Hi @IIxauII. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@IIxauII do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by IIxauII** [comment]
Yes, I confirm the issue on vanilla magento 2.2.5

**Comment by ghost** [comment]
@IIxauII, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sskulkarni** [comment]
@IIxauII , Actually It looks like "Date & Time Custom Options" only applies on product custom option.
It should be some configuration for Date-Time in other places.
Its should be considered as "Feature Request."
Thanks

**Comment by ivanbastos** [comment]
I agree with @sskulkarni 

As you can see in your own description you are changing a configuration for catalog. It won't change the format of orders...

The configuration you are seen @IIxauII is used to configure a product..

See more information at https://docs.magento.com/m1/ce/user_guide/catalog/attribute-date-time-options.html

**Comment by benmarks** [comment]
@magento-engcom-team this seems like a **Feature Request**.

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by hiren0241** [comment]
@IIxauII Hi, I have debug this stuff and I didn't found any defect. Will you please tell me which Timezone you have set at back-end for this particular issue?

Please do have a look at my settings. 
1. Admin Account setting --> German Locale ![git1](https://user-images.githubusercontent.com/43466338/49567719-86446b00-f954-11e8-8639-fed20679de54.png)

2. Store configuration settings: Please select European standard time as --> Europe/Berlin from drop-down. 
![git2](https://user-images.githubusercontent.com/43466338/49567947-5d70a580-f955-11e8-9b66-2ce37caff5c6.png)

3. Please do have a look at below image for: 24h format time display at order grid
![git3](https://user-images.githubusercontent.com/43466338/49568070-d5d76680-f955-11e8-8fe2-b709433507a8.png)

Please do have a look at above mentioned points and let me know if you have any issue.

If it satisfy your requirement, then we will close this issue. This is just setting stuff. Please verify settings once.
