### ISSUE TITLE
Deprecate or document `mixins` feature for declarative JS Components

### ISSUE THREAD

**Issue by DrewML** [magento/magento2#17842]
Magento 2 uses the term `mixins` to define 2 different concepts.

## RequireJS Mixins
[Docs](https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js_mixins.html)

A new AMD module + config can be used to intercept the return value of another AMD module:
```ts
// web/js/foobar-mixin.js
define(function() {
   return function(target: Object) {
      // return any value here. The returned value will be
      // what a consumer of `web/js/foobar.js` receives
   };
});

// in requirejs-config.js
config: {
   mixins: {
     'foobar.js': {
        'foobar-mixin.js': true
     }
   }
}
```

## Declarative JS Component Instantiation
[Docs](https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js_init.html)

When declaring a `mage-init` component setup, you can pass a `mixins` key ([example](https://github.com/magento/magento2/blob/07ef8c12bec98846a93a1943448ea50e974fbeee/app/code/Magento/Catalog/view/frontend/templates/product/view/gallery.phtml#L43)). Instead of intercepting an AMD module, though, it intercepts the configuration for a JS component. The API contract is:

```ts
// js-component-mixins.js
define(function() {
   return function (config: Object, selector: string) {
      // Can modify config or init other JS components
      // Then return the config needed for the JS component being intercepted
   };
});
```

## Problem

These 2 separate features share the same name (`mixins`), but have different APIs. One is a mixin for RequireJS modules, one is a mixin for JS Component configuration and instantiation.

The naming collision and the lack of documentation for JS Component mixins is confusing.

## Solutions

1. Document the `mixins` feature of declarative JS Components, and treat it as a supported first-class API

2. Deprecate `mixins` in declarative JS Components.

## Usage

In core, it appears we only use this feature to instantiate the `magnifier/magnify` code for `mage/gallery/gallery`. It would be good to know if this feature has been used at all by the Magento community and 3rd parties.

**Comment by magento-engcom-team** [comment]
Hi @DrewML. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DrewML do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Igloczek** [comment]
This is the first time I see the second meaning of `mixins`, so from my perspective would be better to deprecate, rather than documenting it.

**Comment by DrewML** [comment]
Moved: https://github.com/magento/architecture/pull/23
