### ISSUE TITLE
Order State dropdown in Assign Order Status to State incorrect

### ISSUE THREAD

**Issue by sheldmandu** [magento/magento2#17844]
### Preconditions
1. Magento 2.2.3 installed (Same issue on 2.2.5)

### Steps to reproduce
1.  Navigate in menu to Stores > Settings > Order Status
2. Click "Assign Status to State" link

### Expected result
1. "Order State" dropdown shows the STATES (new, pending_payment, processing, payment_review, etc)

### Actual result
1. Default STATUSES associated with the states are shown instead of states.

The above issues causes extreme confusion when you actually change the default statuses.  For example we added a "Confirming Payment" status and assigned as the default status to the "processing" state.  Now instead of Order State showing "processing" as the state it shows "Confirming Payment" and obviously there is no state called "Confirming Payment" as that's a status, not a state.

**Comment by magento-engcom-team** [comment]
Hi @sheldmandu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sheldmandu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sheldmandu** [comment]
Further to the bug report. It appears that the Order State dropdown currently shows the Status with the lowest ID that is associated with the state.  To reproduce firstly add a new status "Confirming Payment" and assign to the "processing" state as the Default Status.  Make sure you do not have any orders in the "Processing" state.  Then unassign the "Processing" status from the "processing" state.  Then go into Assign Status to State and observe that Order State dropdown now shows "Suspected Fraud" as the 4th option.  The Order State dropdown should just show states or at least status with default status in square brackets same as on Order Status screen, but certainly not the Status with the lowest ID that's associated with the state.

**Comment by sheldmandu** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @sheldmandu. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sheldmandu, here is your [Magento instance](https://i-17844-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17844-2-2-5.engcom.dev.magento.com/admin](https://i-17844-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sheldmandu** [comment]
I've confirmed the issue exists on fresh dev instance provided.  Best way to observe the issue is after associating the new status as the default status for the processing state is to "Unassign" the Processing status from the processing state.  After that you will observe "Suspected Fraud" showing in the "Order State" dropdown when in Assign Order Status to State.

**Comment by sskulkarni** [comment]
@engcom-backlog-nickolas  
Actually Fundamental problem is with "State Label".
We don't have any "State Title."
Even In Order status Grid It should be displayed State Label rather than Status Label.
Should we create State Label From State Code By Removing "-" and creating White Space?
OR Crate New Field of "State Label"?

![order status settings stores magento admin](https://user-images.githubusercontent.com/6185521/44771400-7ca6ac80-ab88-11e8-91e1-6e6929f4dd0b.png)

**Comment by engcom-backlog-nickolas** [comment]
Hello @sheldmandu, thank you for your report and @sskulkarni for additional details.
We've acknowledged the issue and added to our backlog.

**Comment by sheldmandu** [comment]
@sskulkarni Its not quite clear what you're proposing and as states are harcoded as constants with a lot of logic around them I'm not sure exactly how adding user-friendly title to them would be best handled. Probably with some sort of an array lookup and a translation.  Although it would be nice to have a user-friendly titles for states, the more fundamental issue to address that the state is not displayed in the dropdown.  If the dropdown just displayed the state code that would be more than sufficient.

**Comment by dajve** [comment]
#mmuk2019

**Comment by magento-engcom-team** [comment]
@dajve thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
@sheldmandu, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
