### ISSUE TITLE
Default Status for State Not Working

### ISSUE THREAD

**Issue by sheldmandu** [magento/magento2#17845]
### Preconditions
1. Vanilla Magento 2.2.5 installed
2. Single test product created (to allow an order to be placed)

### Steps to reproduce
1. In Backend - Navigate to Stores > Settings > Order Status
2. Create new status called "CUSTOM New"
3. Assign "CUSTOM New" status to the "new" state (5th down with label "Pending" - The fact that states dropdown shows Statuses instead of states is a separate issue I already logged).  Make sure "Use Order Status As Default" is ticked.
4. In Frontend - Create order

### Expected result
1. CUSTOM New should be the Status of the newly created order as it's the Default Status for the "new" state.

### Actual result
1. Order status is "Pending" instead of "CUSTOM New".  That is the Default Status for the state is not being used to correctly assign the default status for the order as it should.

I have also reproduce the same issue with Braintree Payment Method.  This is how we actually initially discovered the issue in Magento 2.2.3 as we wanted all orders to go into a "Confirming Payment" status before manually being processed to Processing once the payment has been confirmed.  However when the order would be created it would have status of Processing instead of Confirming Payment as would be expected given that Confirming Payment was set as Default for the "processing" state.

**Comment by magento-engcom-team** [comment]
Hi @sheldmandu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sheldmandu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sheldmandu** [comment]
Yes, confirmed the issue on vanilla 2.2.5 instance.

**Comment by engcom-backlog-nickolas** [comment]
Hello @sheldmandu, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by dmytro-ch** [comment]
Hello @sheldmandu,

the default order status can be also configured per Payment Method. Each payment method should have its own predefined "New Order Status" value.
Please make sure you assign the newly created status to the payment method used for testing.
It can be done in ``Stores -> Configuration -> Sales tab -> Payment Methods -> select the payment method -> set the "New Order Status" config value``.

Thank you.

**Comment by sheldmandu** [comment]
@dmytro-ch Neither Braintree nor PayPal Express Checkout have the New Order Status config option available so that's not really a solution.

**Comment by mkor** [comment]
Heya, don't know how far ahead you managed to get in resolving this issue, but considering that If I assign a new status to a state (but leave DEFAULT unchecked), the dropdown will display THAT state's label, it seems to me that the generated query is missing a **LIMIT 1** addendum.

Magento 2.2.5

**Comment by magento-engcom-team** [comment]
@sheldmandu, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
