### ISSUE TITLE
Attributes using for sort order in product collection are added several times

### ISSUE THREAD

**Issue by mpasquin** [magento/magento2#17841]
### Preconditions

1. Magento Enterprise 2.2.5
2. php 7.0 and 7.1

### Steps to reproduce

1. Enable flat category and flat product in back-office (optional)
2. Display or log product collection query from a category
3. See that same attributes are added several times in order by clause

### Expected result

![sort_added_several_times_to_product_collection](https://user-images.githubusercontent.com/4748332/44732840-8081f280-aae6-11e8-8bcc-9b037e53a540.png)

This screenshot has been made with flat category and flat product disabled. When flat category and flat product are enable, it is worst. 

### Actual result

1. Attributes used in sort by clause must be added just one time

**Comment by magento-engcom-team** [comment]
Hi @mpasquin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mpasquin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mpasquin** [comment]
@magento-engcom-team give me {2.2.5} instance

**Comment by ghost** [comment]
Hi @mpasquin the fix for this issue has already in 2.2-develop branch

**Comment by mpasquin** [comment]
Hi @engcom-backlog-nazar 

Thank you. Can you please provide me the commit number so I can patch Magento?

**Comment by ghost** [comment]
@mpasquin No i can't find the commit, you can update to next 2.2.7 release
