### ISSUE TITLE
Layered Navigation Filters Pre-Select Configurable Product Options

### ISSUE THREAD

**Issue by chasteIT** [magento/magento2#1784]
Problem: Customers use layered navigation to filter to their desired product, but if the user selects a configurable products from the category, they must select the same options again to configure the product before getting the associated simple product.

Solution: Use the options selected in the layered navigation filters to pre-select configurable product options.

Example: A category of Shoes (configurable product) has layered navigation filters for Size, Color, etc. In the category, a user selects filter attributes for Size10 and ColorRed to find the products with Red, Size 10 shoes. As Magento is now, the user clicks on their desired shoe to go to the configurable product page and must then select the attributes again to configure their product. We could skip this step by using the Size10 and ColorRed filtered attributes to pre-select those same attributes on the configurable product page.

This improvement could go hand-in-hand with the issue: [Set Configurable Product Default Configuration #1783](https://github.com/magento/magento2/issues/1783).

**Comment by choukalos** [comment]
I've added this request to our backlog ( https://jira.corp.x.com/browse/MAGETWO-42534 ).  

As an ask can someone in the community provide insight on algorithms we can use to parse a quick search query and accurately identify values that product attributes would be set to?

**Comment by tzyganu** [comment]
@choukalos This should not be very hard.  
There is already a way to have one configuration selected when a configurable product is opened if the link looks like this:

`/product.html#{attr1_id}={value1}&{attr2_id}={value2}`  
So basically the problem reduces to changing the links of the configurable products in the current displayed page (not all the collection...just what is shown in the page) that have as configurable attributes what is selected from the filters.

[I did this for Magento 1 some time ago](https://github.com/tzyganu/direct-link).  
I'm not particularly proud of my code because I tried to do it via observers and some thing may look ugly. With the Magento 2 interception system this should be easier.  
Maybe at least you can get a part of idea from what I've done.  

(and if you find something wrong with my extension, please open an issue :smile: )

**Comment by webspeaks** [comment]
Hi, any update on this? Has this feature been implemented?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Layered-Navigation-Filters-Pre-Select-Configurable-Product/idi-p/47244).

**Comment by lucscu** [comment]
@magento-engcom-team Is this feature added to 2.3? When 2.3 will be released?
