### ISSUE TITLE
Status can not be changed based on storeview level

### ISSUE THREAD

**Issue by abhaykhatariya** [magento/magento2#17868]
Status can not be change for specific store view level
If you change for one storeview it will change the value for all existing store view

### Preconditions
1. Magento 2.2.5
2. Multiple storeviews

### Steps to reproduce
1. Add more then one store view
2. Go to Magento backend Catalog --> Product and edit one product 
3. Select store view from left top section
4. Change Product status and it will change for both store view.

### Expected result
1. It should be set for specific store view
2. for example status value as follow
Default         Enable
Store view 1 Disable -  change this store view
Store view 2 Enable
### Actual result
Default         Enable
Store view 1 Disable -  change this store view
Store view 2 Disable  - change automatically. It should be enable as we have change for store view 1 only.

**Comment by magento-engcom-team** [comment]
Hi @abhaykhatariya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abhaykhatariya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by abhaykhatariya** [comment]
@magento-admin @magento-devops 
Please take a look this issue as scope should be store view.
Right now it set as website level & global level

**Comment by abhaykhatariya** [comment]
Please find below solution for this. I have done change using script but it should be default store view selected 
Currently, scope selected is website

![status](https://user-images.githubusercontent.com/23476956/44847088-f49bd200-ac6f-11e8-9c83-9ae77d40be12.png)

**Comment by ghost** [comment]
@abhaykhatariya, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by anant-svc** [comment]
@abhaykhatariya @engcom-backlog-pb Instead of changing status attribute you can make use of VISIBILITY that's on STORE VIEW level already.

**Comment by ananth-iyer** [comment]
@abhaykhatariya @engcom-backlog-pb Instead of changing status attribute you can make use of VISIBILITY that's on STORE VIEW level already.

**Comment by abhaykhatariya** [comment]
@Ananth747 @magento-engcom-team 
There is also that way but here problem is when you change any value of status for specific store view it is changing for all existing store view.
Magento allow to change status based on store view but attribute scope is website.
Either magento have to set scope as store view or dont allow to change status for specific store view.

Let me know if its not clear to you

**Comment by kolczu** [comment]
#mm18pl

**Comment by magento-engcom-team** [comment]
@kolczu thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ilnytskyi** [comment]
#mm18pl

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by marcelo-monteiro** [comment]
@abhaykhatariya , the issue you are talking about in your last comment, is this one? #17818

**Comment by abhaykhatariya** [comment]
@marcelo-monteiro  Hello marcelo It's different.

**Comment by magento-engcom-team** [comment]
@okorshenko Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95049`, `MAGETWO-95050` were created

**Comment by marcelo-monteiro** [comment]
@abhaykhatariya, got it. Thanks!

**Comment by abhaykhatariya** [comment]
@magento-admin @magento-engcom-team 
Hello Team, I want to provide solution for this issues also other issue which i found. Please suggest how can i commit those changes ?

**Comment by ishakhsuvarov** [comment]
Hi @abhaykhatariya 
You may submit a Pull Request to this repository with the fix. Please take a look at the "[Contributing](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html)" section of the Magento Developer Documentation to learn more. Feel free to reach out me or anyone on the team via Community Engineering [slack workspace](http://tinyurl.com/engcom-signup) if you need any help.

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Dharmeshvaja91** [comment]
Hi @abhaykhatariya
Actually this is not an issue
magento provide this option "Enable Product"' on website level not on storeview level because,
The purpose of the Store View is usually used in order to store alternative values for such informative content as product's titles, their descriptions, features etc.
This feature is also necessary for all those who wish to have different store themes and original designs.
No specific product options,price,quantity are allowed to change for every store view.
No specific payment methods are allowed for every store view
If you want to understand the differance between storeview and websiteview 
follow this steps:
1 ) Select store view from left top section change the store
2 ) Change Product Name and again chnage the store. the product name from store1 will change but product name from store2 remain same. 
hope this information helpfull to you.
Thanks.

**Comment by hardik-krish** [comment]
Hi @abhaykhatariya @magento-engcom-team @magento-admin  

I reviewed and tested this as per provided steps. Actually this is not an issue this is feature request.

**Comment by magento-engcom-team** [comment]
Hi @routbiplab. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by routbiplab** [comment]
Hello @abhaykhatariya,

The scope for product status is website and global.

**Comment by vidyasagarmukkavili-gw** [comment]
There is a use case for this feature. 

If a configurable product has simple products whose visibility is supposed to be not visible individually and then the options on the configurable would still keep on showing unless those linked simple products are disabled with status attribute. This issue should be reopened.
