### ISSUE TITLE
Customer DOB format should be changed from admin

### ISSUE THREAD

**Issue by sskulkarni** [magento/magento2#17862]
### Description

Now Customer DOB format can not be changed from admin
![customer_dob](https://user-images.githubusercontent.com/6185521/44833682-7b3eb800-ac4c-11e8-92f0-00a856b2a829.png)

### Expected behavior
Customer's DOB format should change from Admin
### Benefits
Various types of customer can take advantage.

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sskulkarni do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sskulkarni** [comment]
Yes, Can be reproduce in vanila instance.

**Comment by ghost** [comment]
@sskulkarni , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by rogyar** [comment]
Hi @sskulkarni. Could you provide more information about the issue? The customer's DOB is editable from admin panel on 2.2 and 2.3 mainline branches.

![image](https://user-images.githubusercontent.com/2148959/44953436-b5e76100-ae95-11e8-8cd3-045e8c9b5794.png)

**Comment by magento-engcom-team** [comment]
@engcom-backlog-pb Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-94986`, `MAGETWO-94987` were created

**Comment by ghost** [comment]
@rogyar 


> Now Customer DOB `format` can not be changed from admin

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by saphaljha** [comment]
Hello @magento-engcom-team ,

As I have gone through with this issue, I have found that you will get this functionality in "**Commerce Editions**" (Enterprise).

I would like you to check it on "**Magento Opensource**" once else close this issue.

Otherwise it will be feature request for "**Magento Opensource**".

**Comment by magento-engcom-team** [comment]
@sskulkarni, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.
