### ISSUE TITLE
Customer Name Prefix shows white space when extra separator is addes.

### ISSUE THREAD

**Issue by sskulkarni** [magento/magento2#17861]
White space option is added when extra separator is added.

### Preconditions

1. php7.1
2. Magento 2.2.5

### Steps to reproduce

1.In admin menu Store->Configuration
Select "Customer Configuration" under confifuration.
Add "Mr;Ms;Mrs;" in "Prefix Dropdown Options"
![prefix1](https://user-images.githubusercontent.com/6185521/44832451-855eb780-ac48-11e8-90cd-c2dfca54e27c.png)

### Expected result

1. It should avoid the white space option, if extra separator is added.

### Actual result

1.It is displaying extra white space option, and In case of it is required, It throws validation.
![prefix2](https://user-images.githubusercontent.com/6185521/44832568-ca82e980-ac48-11e8-92e4-f61f0b8e7f4b.png)

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sskulkarni do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sskulkarni** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni, here is your [Magento instance](https://i-17861-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17861-2-2-5.engcom.dev.magento.com/admin](https://i-17861-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sskulkarni** [comment]
@magento-engcom-team 
Reproduced in above instance.

**Comment by engcom-backlog-nickolas** [comment]
Hello @sskulkarni, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by osrecio** [comment]
What is exactly the problem? If you decide select the empty dropdown the validation shout out : "This is a required field." I think is a expected result

Thanks!

**Comment by sskulkarni** [comment]
No, Actually Required field is not a problem.
Problem is that is we add "Mr;Ms;Mrs;" in admin.
The front end should reflect 3 dropdowns 
1. Mr 
2. Ms
3. Mrs
 But now It shows
 
1: Mr 
2: Ms
3: Mrs
4: 

It should not consider the empty field and should be avoided by code.
Thanks.

**Comment by osrecio** [comment]
but if you select the 4th option you get an error validation
<img width="427" alt="screen shot 2018-08-30 at 10 47 17" src="https://user-images.githubusercontent.com/1510831/44840779-1b431400-ac42-11e8-9d7b-38c26e0d3539.png">

**Comment by sskulkarni** [comment]
Yes, that's fine, But my concern is 4th position should not display.
Only 3 dropdowns should.
Because It leads to confusion.
Thanks

**Comment by osrecio** [comment]
Ok that's ok. 
Maybe someone from Magento will can help us to determine if is an issue.

**Comment by osrecio** [comment]
@engcom-backlog-nickolas Can you help to decide if is issue or not?

**Comment by ronak2ram** [comment]
Hello @sskulkarni 
Semicolon (;) separated values means put Semicolon (;) for separate two value.
You have to put like **Mr;Ms;Mrs**
Not need last Semicolon (;)

I think this not an issue.

**Comment by nainesh2jcommerce** [comment]
I am currently working with Magento version 2.1.9 and facing same issue.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment]
#MM19IN

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your report. 
The issue has been fixed in magento/magento2#20896 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [8ff4aa55e320cb9facba7149ca71bca3b5ecebea](https://github.com/magento/magento2/commit/8ff4aa55e320cb9facba7149ca71bca3b5ecebea)
 - [fa72ee7f925963020ec5f5af558abff09fa4795b](https://github.com/magento/magento2/commit/fa72ee7f925963020ec5f5af558abff09fa4795b)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your report. 
The issue has been fixed in magento/magento2#21245 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [77c780d5ae54a8ec982648d6104cff6da50e35a6](https://github.com/magento/magento2/commit/77c780d5ae54a8ec982648d6104cff6da50e35a6)
 - [5eeecac645d53a3c543247a1d6e6c26752ee5012](https://github.com/magento/magento2/commit/5eeecac645d53a3c543247a1d6e6c26752ee5012)
 - [69cf6cebcd8ad8d51dc3d88fe89b6f3375bf311c](https://github.com/magento/magento2/commit/69cf6cebcd8ad8d51dc3d88fe89b6f3375bf311c)

The fix will be available with the upcoming 2.2.9 release.
