### ISSUE TITLE
import new products via csv: products are created with empty value when strings are too long

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#17865]
### Preconditions
magento 2.2.5 on ubuntu 16.04 with apache and php 7.1.2. Magento is a fresh install, no custom theme nor any custom module is installed. Magento has been installed by downloaded the source via composer and then run the wizard from browser.

### Steps to reproduce
1. prepare a correct csv to create new products via backend. Use short values (less then 71 characters) for name/sku for a few records, then use a longer strings ((more then 71 characters) for name/sku for other records.
2. go to system > import:
-- entity type = products
-- import behaviour = add/update, skip error entries
-- allow errors count = I tried with several numbers from 10 (default) to 500 but issue persists
-- field separator = ; (semicolon)
-- multiple value separator = , (comma, default)
-- field enclosure = unchecked (default)
3. Select the csv to import and run check data

### Expected result
- when strings are too long, I expect to see an error after I run check data. I also expect that import get blocked until all error are fixed so no products gets created until the check data allows you to proceed with the import.

### Actual result
Actual results consists in two issues: 
1. Check data returns no error, so I'm able to proceed with the import. The import fails saying that there's been a system error. But I shouldn't be able to proceed since my csv contains values (the strings too long) that causes my import to fail.
2.  If I go to my product list, I can see that all the products with too long strings have been created but all the values exept sku are empty (see screenshots). Since the import has failed, no product should have been created. 

SCREENSHOTS: 

1. check data returns no error: 
![checkdata](https://user-images.githubusercontent.com/6501073/44840242-f00bf500-ac40-11e8-9f52-3c00f06a309e.JPG)

2. import fails because of the strings that are too long
![error](https://user-images.githubusercontent.com/6501073/44840279-0023d480-ac41-11e8-9e6b-73fea00b178f.JPG)

3. my product list shows the products with empty values
![lista](https://user-images.githubusercontent.com/6501073/44840323-10d44a80-ac41-11e8-9d2c-b82cf916c7e5.JPG)

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LouNik1984** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984, here is your [Magento instance](https://i-17865-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17865-2-2-5.engcom.dev.magento.com/admin](https://i-17865-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by LouNik1984** [comment]
I can confirm that I can reproduce the issue on the vanilla instance you gave me. I don't know the exact character limit so I used one of the record that I tried to import in my magento instance. In the vanilla instance, you can see a bunch of products correctly imported while the last one to be imported (id = 17) is the one with the too long string and you can see that values are empty. 

I'll attach the csv file I have used to import the product which causes the issue. Because I cannot upload csv files, I transformed it in a txt but of course for magento I have used the csv version.

[simple-products-import.txt](https://github.com/magento/magento2/files/2335408/simple-products-import.txt)

**Comment by ghost** [comment]
@LouNik1984, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by adityarshah** [comment]
I would like to work on this issue and hence starting work on this.

**Comment by gloriadg20** [comment]
#mm18mx

**Comment by magento-engcom-team** [comment]
@gloriadg20 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by gloriadg20** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gloriadg20. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gloriadg20, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17865-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17865-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-17865-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
Hi @LouNik1984. Thank you for your report. 
The issue has been fixed in magento/magento2#18639 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [499cdd7ed72a0f323fdda61399fe75b1c6e75a25](https://github.com/magento/magento2/commit/499cdd7ed72a0f323fdda61399fe75b1c6e75a25)
 - [a9bc411deaecd93be411a3bc8c8da003b2e31298](https://github.com/magento/magento2/commit/a9bc411deaecd93be411a3bc8c8da003b2e31298)
 - [b65b49f1bae762988574a9d23f3892f3f65cc913](https://github.com/magento/magento2/commit/b65b49f1bae762988574a9d23f3892f3f65cc913)
 - [57902258f066e4802f026f64e12f48663475b0b3](https://github.com/magento/magento2/commit/57902258f066e4802f026f64e12f48663475b0b3)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
The issue has been fixed in magento/magento2#18591 by @ravi-chandra3197 in 2.2-develop branch
Related commit(s):
 - [e59dee011c199ec0f0fad819ca6be981db4778f1](https://github.com/magento/magento2/commit/e59dee011c199ec0f0fad819ca6be981db4778f1)
 - [a10f0749d9be91695cf3f3558f60744a23d9e12c](https://github.com/magento/magento2/commit/a10f0749d9be91695cf3f3558f60744a23d9e12c)
 - [ad68105413c6375dbb48884b434a40bb17f72b25](https://github.com/magento/magento2/commit/ad68105413c6375dbb48884b434a40bb17f72b25)

The fix will be available with the upcoming 2.2.8 release.
