### ISSUE TITLE
In customer account locked message contact email fetched from default scope config

### ISSUE THREAD

**Issue by kvydiuk** [magento/magento2#17869]
### Preconditions

1. Magento 2.1.8 CE
2. Ubunut 16.04, MariaDB, PHP7.0.1, Nginx

### Steps to reproduce

1. Multiple websites/stores installation
2. Adjust configuration *Stores -> Configuration -> General -> Contacts -> Email Options -> Send Emails To*, set "1-test@email.com" value to default store view and "2-test@email.com" value to particular store view
3. Go to login page. Try to login with correct login email and incorrect password several times until message:
"The account is locked. Please wait and try again or contact ..." will appear

### Expected result

1. Message "The account is locked. Please wait and try again or contact *someemail*" contains "2-test@email.com"

### Actual result

1. Message "The account is locked. Please wait and try again or contact *someemail*" contains "1-test@email.com"

**Comment by magento-engcom-team** [comment]
Hi @breg-13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@breg-13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ghost** [comment]
@breg-13, thank you for your report.
This issue is already fixed in the latest Magento 2 versions.
