### ISSUE TITLE
Magento 2.2.5 IE Browser into Qty not display in edit cart  product.

### ISSUE THREAD

**Issue by karangar** [magento/magento2#17878]
### Preconditions

1. Magento 2.2.5 (sample data)
2. PHP 7.0
3. IE Browser version 11.0.9600.18537 || 11.0.9600.17843 || 11.0.9600.17843

### Steps to reproduce

1. Add to cart Configurable or Simple  Product
2. Press Cart -> Edit Product 

### Expected result

1.Google Chrome Browser result 
![config_update_cart_chrome](https://user-images.githubusercontent.com/34768419/44905753-ab5f8700-ad30-11e8-998d-ce5fa50fa451.png)

### Actual result

1.IE Browser result  
![config_update_cart_ie](https://user-images.githubusercontent.com/34768419/44906021-76076900-ad31-11e8-963a-e6a92d608b7d.png)

**Comment by magento-engcom-team** [comment]
Hi @karangar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@karangar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@karangar, please add browser version into the Preconditions section.

**Comment by karangar** [comment]
I have updated it.
IE Browser version 11.0.9600.18537 || 11.0.9600.17843 || 11.0.9600.17843

**Comment by ghost** [comment]
@karangar, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by niravkrish** [comment]
Hello @karangar,
**This issue is resolved in 2.2.6.**
