### ISSUE TITLE
Magento 2.2.4 - Paypal Express Checkout - Customer not notified (Email) on Order Paid

### ISSUE THREAD

**Issue by ghost** [magento/magento2#17875]
### Preconditions
1. Magento 2.2.4
2. Payment Method: Paypal Express Checkout
3. Setting:
                     >> Payment Action: Sale
                     >> API uses Proxy: No
                     >> Enable SSL Verification: Yes
                     >> Transfer Cart Line Items: Yes
                     >> Transfer Shipping Options: No
                      >> All Sales Emails are enable

### Steps to reproduce
1. Customer Makes a successful purchase using Paypal Express Checkout.
2. Order Status changes to Order Paid.
3. But (The order confirmation email was sent) and Comments show "Customer Not Notified"

### Expected result
On Order Paid customer should receive an order confirmation email.

### Actual result
No order confirmation email.

I know, it may be related to even some configuration. So please help to solve this issue and explain the reason.

Thanks.

**Comment by magento-engcom-team** [comment]
Hi @AlectoMysticCode. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@AlectoMysticCode do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @AlectoMysticCode  We were not able to reproduce this issue by following the steps you provided.
Also magento sends mails use function of php mail() did you check configuration smtp server  ?

**Comment by ghost** [comment]
Hi, Thanks for looking into this.

Yes, all the emails are working fine, when we click on send mail in the order page, it is sending email to the customer.

The only time it is not sending email is when any customer use Paypal express checkout and successfully pay and order status is changed to Order Paid, but the customer is not notified about the order. The email works for other payments. Is there any specific setting to send mail for Paypal Express Checkout.

**Comment by ghost** [comment]
@AlectoMysticCode 
The issue has been fixed in magento/magento2#13898 by @pmclain in 2.2-develop branch
Related commit(s):

https://github.com/magento/magento2/commit/975137b58353bcef780e34e679fe8b115f98fe34
https://github.com/magento/magento2/commit/aec7af9c3b0ebf733d9c94fc3f34696e4cd87769
The fix  available in 2.2.5 release.

**Comment by ghost** [comment]
@engcom-backlog-nazar 

I have already applied the patch a long time but still, no luck and patch is still not fixing the issue.

At can please explain some debugging step to debug this issue.

Thanks.

**Comment by ghost** [comment]
@AlectoMysticCode Did you try to update to 2.2.5 ?

**Comment by ghost** [comment]
@engcom-backlog-nazar  No, but did apply all the patches available for 2.2.5

**Comment by ghost** [comment]
@AlectoMysticCode I've  tested on clear 2.2.5 instance, order confirmation sends, so maybe  problem in  your code.

**Comment by ghost** [comment]
@engcom-backlog-nazar Okay, thanks for your help, will debug more and get back with more data to debug. Thanks.
