### ISSUE TITLE
Can't log into Magento Admin, "Invalid Captcha" error appears

### ISSUE THREAD

**Issue by coatesjonathan** [magento/magento2#17881]
### Summary

I cannot login to Magento admin, I just get this response every time, when I initially entered my login details, there was no captcha there, it appears after I try to login.

<img width="884" alt="screen shot 2018-08-31 at 14 58 54" src="https://user-images.githubusercontent.com/19817306/44916756-6b97a000-ad2e-11e8-9207-5104f768a352.png">

Then once I've tried again, using the captcha, I get this error:

<img width="524" alt="screen shot 2018-08-31 at 15 01 02" src="https://user-images.githubusercontent.com/19817306/44916883-b31e2c00-ad2e-11e8-8400-d9725c5a5e96.png">

Any help would be appreciated?

**Comment by magento-engcom-team** [comment]
Hi @coatesjonathan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@coatesjonathan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@coatesjonathan, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
