### ISSUE TITLE
Product name change within creating new order in admin

### ISSUE THREAD

**Issue by tcurilla** [magento/magento2#17880]
### Preconditions

1. Magento v2.2.5

### Steps to reproduce

1. Fresh install magento
2. Create multistore
3. create product with different name for each store
4. create customer for second store
5. create new order and select customer
6. add product to order -> you will see right name ins Items Ordered
7. click on "Update Items and Quantities" button

### Expected result

1. Same name of the product in Items Ordered

### Actual result

1. Name was change to name in default store

Name of products will change after place order also.

**Comment by magento-engcom-team** [comment]
Hi @tcurilla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tcurilla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tcurilla** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @tcurilla. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @tcurilla, here is your [Magento instance](https://i-17880-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17880-2-2-5.engcom.dev.magento.com/admin](https://i-17880-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tcurilla** [comment]
@magento-engcom-team I confirm that issue was reproduce on vanilla Magento instance with following steps

**Comment by ghost** [comment]
Hi @tcurilla Thank you for you report, the fix for this issue already available in 2.2-develop branch

**Comment by Ctucker9233** [comment]
@engcom-backlog-nazar What version of 2.2 contains fix? If none, what are the related commits?
