### ISSUE TITLE
Something went wrong while saving this configuration: Area is already set

### ISSUE THREAD

**Issue by Ashok5000** [magento/magento2#17893]
### Preconditions

1.
2.

### Steps to reproduce

1.
2.

### Expected result

1. [Screenshots, logs or description]
2.

### Actual result

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
Hi @Ashok5000. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Ashok5000 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Ashok5000** [comment]
"Something went wrong while saving this configuration: Area is already set"
I am getting this when I going to change the store view.
I can't change any of my theme icon or store name above error will pop up.

**Comment by hostep** [comment]
This is a duplicate of https://github.com/magento/magento2/issues/14968
Closing this one. Please read that other thread, it has some pointers to patches which will resolve this issue. 
Issue will also be fixed in Magento 2.2.6
