### ISSUE TITLE
Merchant beta release date?

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1789]
Hello, there are some news for the date of the "merchant beta" release?

**Comment by choukalos** [comment]
Hi @CRYX2 we've already released merchant beta (for CE) on July 15th ( Tag https://github.com/magento/magento2/releases/tag/1.0.0-beta ).  Our enterprise code was released to a small group of merchants/partners to gather feedback at the same time.  

GA is planned for Q4 of this year ( master branch has many changes since merchant beta was released ).

If you've had a chance to work with Magento 2 please send us your feedback.

Thanks!

**Comment by CRYX2** [comment]
Thanks for your response. There are some date plans on the next master release?

**Comment by choukalos** [comment]
We haven't given a specific public date because we want to make sure we're addressing the communities and our beta merchant's feedback. We plan on releasing Magento 2.0 GA this quarter.

**Comment by gabrieldagama** [comment]
Hi @CRYX2. Thank you for your report. 
The issue has been fixed in magento/magento2#29861 by @Nazar65 in 2.4-develop branch
Related commit(s):
 - [04a9f44e2e000d180a2d02bef81768df660812e6](https://github.com/magento/magento2/commit/04a9f44e2e000d180a2d02bef81768df660812e6)
 - [47b5eeac08bd15b6be6f59e47643030f8726ab66](https://github.com/magento/magento2/commit/47b5eeac08bd15b6be6f59e47643030f8726ab66)

The fix will be available with the upcoming 2.4.2 release.
