### ISSUE TITLE
Duplicated extre fees on PayPal Express

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#17898]
### Preconditions

1. Magento 2.1.7 / 2.2.5 (tested on both)
2. Working PayPal Express account

### Steps to reproduce

1. Create a new module which adds a new row to quote totals
```
<section name="quote">
        <group name="totals">
            <item name="rush_handling" instance="Qsolutions\AdvanceCheckout\Model\Total\Quote\Handling" sort_order="150"/>
        </group>
    </section>
```
2. Increase order total with custom value, lets say 10
```
[...]
public function collect(
        \Magento\Quote\Model\Quote $quote,
        \Magento\Quote\Api\Data\ShippingAssignmentInterface $shippingAssignment,
        \Magento\Quote\Model\Quote\Address\Total $total
    )
    {
        $items = $shippingAssignment->getItems();
        if (!count($items)) {
            return $this;
        }
        parent::collect($quote, $shippingAssignment, $total);

        $rushHandling = 10.00;

        $total->setGrandTotal($total->getGrandTotal() + $rushHandling);
        $total->setBaseGrandTotal($total->getBaseGrandTotal() + $rushHandling);

        $this->_checkoutSession->setIsCalculated(true);

        return $this;
    }
[...]
```

### Expected result

1. User can checkout! (from checkout process and cart page)
2. Extra amount added to entire order, visible both backend and frontend
3. PayPal Express has no issues with order processing

### Actual result
1. Cannot checkout!
2. When trying to checkout (paypal express debug on) I see in the logs that final order amount has +20.00 value the final request to paypal (should be + 10.00)
3. PayPal error: _PayPal gateway has rejected request. The totals of the cart item amounts do not match order amounts (#10413: Transaction refused because of an invalid argument. See additional error messages for details)._

I've seen in the logs (by debugging) that PayPal calls collectTotals method twice during checkout. Other native payment extensions don't to that - they only call collectTotals method once.

**Comment by magento-engcom-team** [comment]
Hi @qsolutions-pl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@qsolutions-pl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @qsolutions-pl , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ChristianAlba** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
@ChristianAlba thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @ChristianAlba. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by jakwinkler** [comment]
Is anyone working on this?

**Comment by arshad-codilar** [comment]
#mm19in

**Comment by magento-engcom-team** [comment]
@arshad-codilar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @arshad-codilar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by jakwinkler** [comment]
#snowdog-oss

**Comment by magento-engcom-team** [comment]
@qsolutions-pl thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @bgorski. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by bgorski** [comment]
An update on the issue: 
We found out that the issue is that PayPal Nvp API is not collecting custom totals as separate totals, but still adds them to the grand total amount when making a request. A result of that is when the grand total is compared with all the separate parts of it (items amount, shipping and tax, which are the only amounts sent in the request), it doesn't match and returns and error.

Technical details:
the issue is in \Magento\Paypal\Model\Api\Nvp::call(). The $request variable collecting all the request data has only AMT (grand total), SHIPPINGAMT (shipping amount), ITEMAMT (items subtotal) and TAXAMT (tax). It lacks fields that would collect custom quote totals. The issue is, it doesn't seem possible to add separate fields for separate totals. The only possible way would be to include a HANDLINGAMT field in the request, which would have to collect all custom totals.
For testing purposes we tried adding a custom total with a fixed $99 value and then hardcoding the same value as HANDLINGAMT in \Magento\Paypal\Model\Api\Nvp::call(): 
$request['HANDLINGAMT'] = "99.00";
After that the response for such a modified request was a Success.

**Comment by jakwinkler** [comment]
Ok, so to sum it up. DUplicated fees were caluclated only in my case, but the problem is related to PayPal API and how Magento prepares XML file.

When you add a custom fee / position in Magento that is added to quote, that variable needs to be added to PayPal Soap / Rest request as a custom parameter. 

As @bgorski has described above, all custom fees added to order should be passed to HANDLINGAMT field in PayPal XML request so the calculation is right. 

I think this is much more complex and Magento Core Team should take a look at this.
