### ISSUE TITLE
Magento API GetOrder doesn't return correct sale items

### ISSUE THREAD

**Issue by MaximKitsenko** [magento/magento2#17894]
### Preconditions

1. Magento 1.9.3.3. I know this repository is for magento 2.x version. I've already tried to report a bug at magento.com, but report-a-bug form doesn't work. Some guy has already told about it:  https://community.magento.com/t5/Can-Magento-do/How-can-I-contact-the-Magento-Team-to-report-a-bug/m-p/98488
2. Please either reply on my bur report, either fix your web page for v 1.x bug reports.

### Steps to reproduce

1. There is a sale with 3 configurable sale items: https://yadi.sk/i/IQcrXaAM3aoVUN
2. I'm trying to call 'salesOrderInfo' via soap v2

### Expected result

1. I'm waiting to receive an order with 3 items like, like items on a screenshot above.
2.

### Actual result

1. But i receive a sale with 8 items:

sku | product_type | QtyCanceled | QtyInvoiced | QtyOrdered | QtyRefunded | QtyShipped
-- | -- | -- | -- | -- | -- | --
43475255575 | configurable | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 1,0000
43475255575 | simple | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 0,0000
43475432334 | configurable | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 1,0000
43475432334 | simple | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 0,0000
43475861714 | configurable | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 1,0000
43475861714 | simple | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 0,0000
43475432334 | simple | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 0,0000
43475861714 | simple | 0,0000 | 1,0000 | 1,0000 | 1,0000 | 0,0000

2.

**Comment by magento-engcom-team** [comment]
Hi @MaximKitsenko. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MaximKitsenko do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @MaximKitsenko  Unfortunately we not support magento 1.* versions,  also -> https://magento.com/blog/magento-news/ongoing-magento-1-support
