### ISSUE TITLE
Magento 2.2.5 - No shipping methods available after any edit during reorder

### ISSUE THREAD

**Issue by minglethepringle** [magento/magento2#17892]
### Preconditions

1. Magento 2.2.5
2. PHP >= 7.0

### Steps to reproduce

1. Have any shipping method enabled. I chose flat rate.
2. Place an order.
3. Go to Sales -> Orders -> select order -> Reorder -> Change anything in the order (product qty, price, shipping details) -> Click "Get shipping methods and rates"

### Expected result

1. It should give me some shipping methods. In my case, flat rate should show up.

### Actual result

![image](https://user-images.githubusercontent.com/16504328/44959143-1c7d7680-aeb8-11e8-8a6a-8685f7878dd3.png)

Does not display any shipping methods. On the top of the page, it says:
![image](https://user-images.githubusercontent.com/16504328/44959149-2ef7b000-aeb8-11e8-80f5-2882f8747b66.png)

**Comment by magento-engcom-team** [comment]
Hi @minglethepringle. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@minglethepringle do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by minglethepringle** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @minglethepringle. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @minglethepringle, here is your [Magento instance](https://i-17892-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17892-2-2-5.engcom.dev.magento.com/admin](https://i-17892-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by minglethepringle** [comment]
@magento-engcom-team no

was not able to reproduce issue on vanilla Magento instance v2.2.5.

**Comment by ghost** [comment]
@minglethepringle, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
