### ISSUE TITLE
Add isActive implementation to StoreInterface 

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#17896]
### Description

Since there's no way to to verify whether a store is active or not through the interface, we have to create a store object using the factory, which increases the load. It would be sweet if this function is implemented in the Magento\Store\Api\Data\StoreInterface 

### Expected behavior

call the storeInteface to verify whether it's active or not instead of using the Factory. 

### Benefits

- makes it easier to verify whether a store is active or not.

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@duckchip do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@duckchip, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Charlie** [comment]
Hello @duckchip 

We are closing this issue as not relevant because now in 2.4-develop we can `call the storeInteface to verify whether it's active or not instead of using the Factory` as expected:
![image](https://user-images.githubusercontent.com/51680850/71616814-d0803600-2bc0-11ea-9a68-194a9da252d6.png)
![image](https://user-images.githubusercontent.com/51680850/71616840-ef7ec800-2bc0-11ea-832f-868bcd6d4f45.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest Magento 2.4-develop branch. 

Thank you for collaboration

**Comment by hostep** [comment]
Just FYI, this was already part of [Magento 2.3.0](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Store/Api/Data/StoreInterface.php#L78) by https://github.com/magento/magento2/pull/10923
