### ISSUE TITLE
[REST API] Add item to cart is incorrect after order is placed

### ISSUE THREAD

**Issue by masodu** [magento/magento2#17895]
### Preconditions
This bug is reproducible with magento-2.3.0-alpha62 release and patched with the master code from the repo: `https://github.com/adobe/commerce-cif-magento-extension`.

### Steps to reproduce

All this steps are executing using the REST API endpoints. 
1. Create a customer cart (customer is logged in based on a customer token) 
2. Set the billing address, shipping address and set the cart payment method
3. Post an order for the customer cart
4. Create a new customer cart as the customer does not have any active cart anymore
5. Add an item to the new cart 
6. Add a second item to the new cart

### Expected result

Step `5` from the `Steps to reproduce` should correctly set the prices for the new added item. 

### Actual result

Step `5` from the `Steps to reproduce` sets the cart and item prices to `null`. All the other fields of the cart are correct. 

### Note
This is not reproducible using luma demo site and one possible root cause for this is the different handling of cart operation between demo site and REST API:
- `UI:\Magento\Checkout\Controller\Cart\Add::execute`
- `REST:\Magento\Quote\Model\Quote\Item\Repository::save`

After Step `6` from `Steps to reproduce` the prices are correctly set at cart level, even for the item created at step `5`.

**Comment by magento-engcom-team** [comment]
Hi @masodu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@masodu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by masodu** [comment]
@mkotov please triage this issue.

**Comment by ghost** [comment]
Hi @masodu , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by masodu** [comment]
If it helps pls find bellow the full list of REST calls I am doing. After `step 10` bellow the cart prices are null. 
1. Customer login: /rest/V1/integration/customer/token
2. Customer login: /rest/V1/customers/me
3. Create cart: rest/V1/carts/mine
4. Add item to cart: rest/V1/carts/mine/items
5. Set billing address: /rest/V1/carts/mine/billing-address
6. Set shipping info: /rest/V1/carts/mine/shipping-information
7. Set payment method: /rest/V1/carts/mine/selected-payment-method
8. Post the order: /rest/V1/carts/mine/order
9. Recreate a cart: /rest/V1/carts/mine
10. Add item to the new cart: rest/V1/carts/mine/items

**Comment by magento-engcom-team** [comment]
Hi @prakashpatel07. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sdzhepa** [comment]
Should be re-verified and confirmed on the latest `2.4-develop`

**Comment by engcom-Alfa** [comment]
Hi @masodu. Thank you for your report!
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Looks like the issue has already been fixed.

**Manual testing scenario:** can be useful: [devdocs](https://devdocs.magento.com/guides/v2.4/rest/tutorials/orders/order-create-quote.html)

1. Create a customer cart (customer is logged in based on a customer token)
2. Set the billing address, shipping address and set the cart payment method
3. Post an order for the customer cart
4. Create a new customer cart as the customer does not have any active cart anymore
5. Add an item to the new cart

**Actual Result:** :heavy_check_mark: Price is correctly set for a newly added item

![Screenshot from 2021-02-10 13-05-03](https://user-images.githubusercontent.com/51679138/107502872-eae95900-6ba1-11eb-8603-5d119c5942cb.png)
and all subsequent items are added to the cart correctly.

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.
