### ISSUE TITLE
Magento 2.2.5 Product swatches does not shows correct value for related store view

### ISSUE THREAD

**Issue by magicaner** [magento/magento2#17890]
### Preconditions

1. Magento 2.2.5 (sample data)
2. PHP >= 7.0

### Steps to reproduce

1. Install fresh magento with default simple data
2. Edit swatch values for `size` attribute. 
3. Change value for default store to `XS D`. And for admin store set `XS A`  
![image](https://user-images.githubusercontent.com/1652800/44958591-050bb100-aeeb-11e8-8a29-4de6e405c021.png)
4. Run bin/magento index:reindex to reindex all indexes
5. Run bin/magento cache:clean block_html full_page

### Expected result

1. open product page which has `size` attribute. For example SKU= MH01
2. the value of attribute should be `XS D`

### Actual result

1. open product page which has `size` attribute. For example SKU= MH01
2. the value of attribute should be `XS A`
![image](https://user-images.githubusercontent.com/1652800/44958648-e2c66300-aeeb-11e8-961a-4d055d0f21fb.png)

**Comment by magento-engcom-team** [comment]
Hi @magicaner. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magicaner do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@magicaner, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @magicaner. Thank you for your report. 
The issue has been fixed in magento/magento2#17891 by @magicaner in 2.2-develop branch
Related commit(s):
 - [4164200d702df5abb48970d7bea976a0f6d9e02e](https://github.com/magento/magento2/commit/4164200d702df5abb48970d7bea976a0f6d9e02e)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @magicaner. Thank you for your report. 
The issue has been fixed in magento/magento2#18988 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [f359bbcd3d734f5296f88c7078c1a2b6c3b00017](https://github.com/magento/magento2/commit/f359bbcd3d734f5296f88c7078c1a2b6c3b00017)

The fix will be available with the upcoming 2.3.1 release.
