### ISSUE TITLE
configurable product price is not shown for out-of-stock subproducts, even if it is configured to

### ISSUE THREAD

**Issue by brosenberger** [magento/magento2#17897]
### Preconditions

1. magento2 2.2.3
2. enable option in stores -> configuration -> catalog -> inventory -> stock options -> display out of stock products

### Steps to reproduce
1. create a configurable product, all simple products are out of stock
2. go to detail page of the configurable product

### Expected result
1. the lowest price of the configurable product is shown as it is with in stock products

### Actual result
1. no price at all is shown

I think the problem lies within https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/StockStatusBaseSelectProcessor.php#L48 where the addition of the sql check for stock status should be within the else part of this condition, e.g. 
```php
public function process(Select $select) 
{
  if (**!**$this->stockConfig->isShowOutOfStock()) {
```

**Comment by magento-engcom-team** [comment]
Hi @brosenberger. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@brosenberger do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by brosenberger** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @brosenberger. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @brosenberger, here is your [Magento instance](https://i-17897-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17897-2-2-3.engcom.dev.magento.com/admin](https://i-17897-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by brosenberger** [comment]
@magento-engcom-team it can be reproduced, see product https://i-17897-2-2-3.engcom.dev.magento.com/myconfigurable.html where no price is shown.

**Comment by ghost** [comment]
Duplicate of #16069
