### ISSUE TITLE
How to open popup clicking on custom mass action in sales order grid

### ISSUE THREAD

**Issue by Tsalkapone** [magento/magento2#17907]
### Summary

I am new to Magento 2. I have managed to create a new mass action in sales order grid in admin view. What I need now is to show a popup when clicking on my custom mass action. This popup is needed to configure the selected items before proceeding to some other action.

Any workaround would be appreciated!

**Comment by magento-engcom-team** [comment]
Hi @Tsalkapone. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Tsalkapone do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@Tsalkapone  please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
