### ISSUE TITLE
Getting [Composer\Downloader\TransportException]  exception while we listing our extension in Magento 2 Marketplace

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#17906]
We tried to list our Magento 2 extension for Magento version 2.2.x in Magento Marketplace. But after listing it is failed due to the following error.
Environment: Operating System - Centos 7, PHP Version - 5.6.36, Magento Platform - 2.1.14 CE
[Composer\Downloader\TransportException] 
The "http://packagist.org/p/provider-2018-04%24daec9e583a397acffeb0b6bd85529c0849fec7565b0983c6c4e5feae12687fcd.json" file could not be downloaded (HTTP/1.1 404 Not Found) 

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] []...

[Pipeline] }
[Pipeline] // stage
[Pipeline] sh
[DockerOperationsPHP56Magento21CE] Running shell script
+ echo Failure
Failure

Environment: Operating System - Centos 7, PHP Version - 7.0.30, Magento Platform - 2.2.5 CE Varnish, Sampla Data
Updating dependencies (including require-dev)

[Composer\Downloader\TransportException] 
The "http://packagist.org/p/provider-latest%24b3734e5353b8f3db102eb5a022c28326fdf2fada0bc7fb168d108c4dec0cc83e.json" file could not be downloaded (HTTP/1.1 404 Not Found) 

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] []...

[Pipeline] }
[Pipeline] // stage
[Pipeline] sh
[DockerOperationsPHP70Magento22CEVarnish] Running shell script
+ echo Failure
Failure

Can anyone help on this?

**Comment by magento-engcom-team** [comment]
Hi @i95devdivya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@i95devdivya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@i95devdivya , the GitHub issue tracker is intended for Magento Core technical issues only.
