### ISSUE TITLE
Magento 2 Admin Content/Pages

### ISSUE THREAD

**Issue by lansy1** [magento/magento2#17903]
### Preconditions

1. version 2.2.3
2.

### Steps to reproduce

1.Very simple, I login to admin and go to Content on left bar and go to under Elements / Pages. Will not load. If I go to Widgets, it will load. Blocks used to load until I put the asterisk in the search bar and hit enter. Now it does the exact same thing as the Pages page.
2.

### Expected result Pages list should load. Please look at pictures carefully. I need to remove the search filter somehow.

1. [Screenshots, logs or description]
2.https://prnt.sc/ko4012
![image](https://user-images.githubusercontent.com/42954246/45008496-ecb59800-afb7-11e8-98f6-93e9d1c7f22c.png)

### Actual result
Error message is
1. [Screenshots, logs or description]
2.Error message: Something went wrong with processing the default view and we have restored the filter to it's original state.

**Comment by magento-engcom-team** [comment]
Hi @lansy1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lansy1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@lansy1, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only, and your problem is obviously caused by some custom code.
