### ISSUE TITLE
Magento2 Report export empty row

### ISSUE THREAD

**Issue by penglongyun** [magento/magento2#17913]
### Preconditions

1.Admimhtml reports module,when 'filter' params contains "report_period",and values 'day',must value 
  "day","month" or "year" not error. this param must in the last.
2. then when Refresh,the url will show param 'filter' and value ,the value is urlencode. ok, the value is end by "==", but when export, the url will be encode again, so the report action will not correctly resolve the param "report_period",ERROR SHOW.

3.the template file : Magento_Backend\templates\widget\grid\export.phtml .I monified bellow:
![image](https://user-images.githubusercontent.com/3479975/45027561-54311d80-b074-11e8-9498-4892eb392ece.png)

![image](https://user-images.githubusercontent.com/3479975/45027444-fac8ee80-b073-11e8-82af-b00f069dee11.png)

**diffrent between with:**

![image](https://user-images.githubusercontent.com/3479975/45027300-9e65cf00-b073-11e8-9ac7-3b413c25181a.png)

### Steps to reproduce

1.Magento2 Version:2.2.2
2.click adminhtml menu [REPORTS]->[PRODUCTS]->[Ordered]
2.input special date range  and show by.click [Refresh], will show correct data row,but when click[Export],empty row in CSV file.

### Expected result

1. [Screenshots, logs or description]
2.CSV file show the same rows with Grid.

### Actual result

1. [Screenshots, logs or description]
2. CSV file empty row.

**Comment by magento-engcom-team** [comment]
Hi @penglongyun. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@penglongyun do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @penglongyun thank you for you report, the fix for this issue already available in 2.2develop branch
