### ISSUE TITLE
Unable to import product while it shows success message 

### ISSUE THREAD

**Issue by devenkuswa** [magento/magento2#17914]
**Preconditions**
Magento CE 2.2.5
PHP 7.09
MYSQL 5.7

Import simple product with basic details but description contain some mathematically special character like φ, ─ and other same kind of symbols. When I am importing  it validate file and shows success message. But no product appeared for that sku.

**Steps to reproduce**
Create a simple product csv and add some special characters eg. φ, ─ in the description column and import it.

**Expected result**
It should show error or warning if product did not import due to special characters or handle these characters to import.

**Actual result**
 It validate file and shows success message. But no product inserted for that sku.

**Comment by magento-engcom-team** [comment]
Hi @devenkuswa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@devenkuswa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@devenkuswa, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![1](https://user-images.githubusercontent.com/40756187/45029068-1de1a700-b050-11e8-81d8-c519493fdbaf.gif)
