### ISSUE TITLE
The ui-component field validation error not opening accordion tab that owns the field (field does not get focused)

### ISSUE THREAD

**Issue by allanpaiste** [magento/magento2#17926]
The issue of event not triggering properly on every call causes issues with Form Validation 'error' events where certain errors don't get properly highlighted when error message is not set properly or does not change. In case rest of the UI state around the error has been changed, the element that caused the actual error, no longer gets highlighted correctly. 

In most typical cases this can be encountered when either:

1. When editing entities where some previously optional field was changed to be required.
2. Editing entities that were created by a integration.
3. ... or basically any way you could end up with having entities where required value was reset/blanked in the backend.

The steps provided might feel a bit illogical and odd, but serve still to illustrate the issue; similar, 
more serious situations with non-visible errors have been encountered on specific projects with 3rd party modules (mostly relates to integrations and data imports that deliver data where some required fields end up being empty when editing forms in admin).  

### Preconditions

1. use any Magento version from range of 2.1.0 - 2.2.5
2. use official sample data
3. environment doe not matter. Issue in any browser, nothing that relates to BE.

### Steps to reproduce

1. navigate to <base-url>/admin and log in
2. [admin] Navigate to Content >> Pages
3. [admin] edit any page
4. [admin] open "Page in Websites" accordion
5. [admin] un-select all stores (hold down CMD on Mac and CTRL on Windows and RMB the items)
6. [admin] close the accordion
7. [admin] use "Save and Continue" or "Save" to save the page

### Expected result

1. Saving fails and invalid field is revealed and focused.

### Actual result

1. Saving fails and user is left wondering what went wrong or why the Save button does not work 

### Extra details

These particular steps will have the accordion group already decorated, but --- in case ... 

a) attribute has been made to be required after the entity has been created; or ... 
b) entity created by integration after the attribute was made required and integration not properly synced 

.... the accordion will NOT have any visual hints on what exactly failed.

### Related files

1. [js/form/element/abstract.js](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/web/js/form/element/abstract.js#L100) -- owner of ko-observed 'error' property
2. [js/form/components/fieldset.js](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/web/js/form/components/fieldset.js#L82) -- owner of the onError observer, registers it against abstractElement when it's nested as a child; the onError observer (even if it would trigger), does not guarantee 'opened' state to be set to true.
3. [js/lib/core/events.js](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/web/js/lib/core/events.js#L42) -- has logic split to deal differently with ko-observed properties that kill the bubbling in case object that receives the subscription has observable property with event same name. 

There is no way for an event handler to be registered for an object that has a observable property with same name - leading for the events (although perceived from [declaration point of view as behaving in uniform manner](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/web/js/form/components/fieldset.js#L79)) to be - in reality - treated differently.

I would propose the event observer registration to be re-worked as the behaviour of the application can unintentionally changed based on what properties some objects have declared as observable (a'la: some event that used to trigger on every occurrence of the event suddenly only trigger when field value changes, without bubbling).

**Comment by magento-engcom-team** [comment]
Hi @allanpaiste. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@allanpaiste do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ghost** [comment]
@allanpaiste, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by ilnytskyi** [comment]
#mm18pl

**Comment by magento-engcom-team** [comment]
Hi @andrewbess. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @allanpaiste. Thank you for your report. 
The issue has been fixed in magento/magento2#19812 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [a06ae361ca5e88fa1a1726941438f9cf0e66589c](https://github.com/magento/magento2/commit/a06ae361ca5e88fa1a1726941438f9cf0e66589c)
 - [6e9ad7879ef0c2cb2324dae982c8d89ec1ec8ba5](https://github.com/magento/magento2/commit/6e9ad7879ef0c2cb2324dae982c8d89ec1ec8ba5)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @allanpaiste. Thank you for your report. 
The issue has been fixed in magento/magento2#20510 by @mageprince in 2.2-develop branch
Related commit(s):
 - [4a13ccf26db5844f9d9a6993514a0fc34ce1da7a](https://github.com/magento/magento2/commit/4a13ccf26db5844f9d9a6993514a0fc34ce1da7a)

The fix will be available with the upcoming 2.2.9 release.
