### ISSUE TITLE
The value of Admin scope can't be empty. When updating existing product attributes

### ISSUE THREAD

**Issue by dannychim** [magento/magento2#17927]
### Preconditions

1. Running on Magento 2.2.5

### Steps to reproduce

1. Edit existing product attributes
2. Add a new swatch 
3. Error returned "The value of Admin scope can't be empty."
4.Even when adding a new product attribute **Text Swatch** same error is showing.

### Expected result

1. Successfully saved

### Actual result

1. Trying to add new product attributes "Twin" in row 6. Even filling all stores value with twin, error returned still.
<img width="1354" alt="screen shot 2018-09-05 at 10 28 07 am" src="https://user-images.githubusercontent.com/42988169/45067587-7a979d00-b0f6-11e8-9ddf-6de75bb15ad2.png">

### What i did before submitting this
1. Flushed, reindex, regenerate mangeto static files
2. Check php , max_input_vars=10000

**Comment by magento-engcom-team** [comment]
Hi @dannychim. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dannychim do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
