### ISSUE TITLE
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'container', attribute 'htmlTag': [facet 'enumeration'] The value '' is not an element of the set {'aside', 'dd', 'div', 'dl', 'fieldset', 'main', 'nav', 'header', 'footer', 'ol', 'p', 'section', 'table', 'tfoot', 'ul'}. Line: 1049

### ISSUE THREAD

**Issue by neetu-mittal** [magento/magento2#17923]
http://dev.petceutics.com.au/newsletter/manage/
![capture](https://user-images.githubusercontent.com/8451427/45052248-ea306c80-b0a3-11e8-80f9-d6bf5db6cedf.PNG)

**Comment by magento-engcom-team** [comment]
Hi @neetu-goyal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@neetu-goyal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by neetu-mittal** [comment]
Magento ver. 2.2.5

**Comment by ghost** [comment]
@neetu-goyal , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
