### ISSUE TITLE
Custom session unset after upgrade to 2.2.5 from 2.2.4

### ISSUE THREAD

**Issue by developer-vtnetzwelt** [magento/magento2#17931]
### Summary
I have set some session values and that I am using after sending an email. Up to version 2.2.4 it was working fine, but as I upgrade Magento to 2.2.5 then I am not getting session values after sending email.

As I tried to debug the issue. In my email's footer I applied a cms static block using code-

`{{block class="Magento\\Cms\\Block\\Block" area='frontend' block_id="email_footer"}}`

For testing - In the static block, I write only "Hello".

If I am calling static block using above code then my custom session going to unset. If I am removing this line of code then all working fine, and I am getting all custom session values.

Didn't understand what the issue, because all was working fine up to 2.2.4.

Please let me know if there is fix or have any other method to call static block in email template HTML file.

**Comment by magento-engcom-team** [comment]
Hi @developer-vtnetzwelt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@developer-vtnetzwelt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by developer-vtnetzwelt** [comment]
@magento-engcom-team give me {2.2.5} instance

**Comment by ghost** [comment]
Hi @developer-vtnetzwelt Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

**Comment by ghost** [comment]
@developer-vtnetzwelt You need to -> "give me 2.2.5 instance"

**Comment by orlangur** [comment]
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.
