### ISSUE TITLE
Non existing product in quote

### ISSUE THREAD

**Issue by webspeaks** [magento/magento2#17939]
### Preconditions

1. Magento 2.2.5
2. PHP 7.1

### Steps to reproduce

1. Login and Add a product X to cart
2. Delete the product X from Magento using admin panel
3. Login again and go to cart page

### Expected result

1. You should see the cart page with no item in cart

### Actual result

1. You see white screen with no errors

### Analysis
The Magento Quote module calls a function `removeItemsWithAbsentProducts()` in `vendor\magento\module-quote\Model\ResourceModel\Quote\Item\Collection.php` after quote is loaded. This function tries to remove the non existing products from cart. But this function fails at line # 320:

```
319: $quoteItem = $this->getItemByColumnValue('product_id', $productIdToExclude);
320: $this->removeItemByKey($quoteItem->getId());
```

Since `$quoteItem` is null on line # 319, the code at line # 320 fails.
Please let me know if my observation is correct.

Thanks

**Comment by magento-engcom-team** [comment]
Hi @webspeaks. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@webspeaks do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @webspeaks I'm not able to reproduce following steps your described, i'm have an empty shopping cart.

**Comment by webspeaks** [comment]
@engcom-backlog-nazar Did you try to add new products to cart before after deleting the existing product  from database?

**Comment by ghost** [comment]
@webspeaks yes how you can add product to cart if it deleted ? seems problem related to your custom code or another module. Can you reproduce this on vanilla instance ?

**Comment by webspeaks** [comment]
@engcom-backlog-nazar 
1. Add product X  to cart
2. Remove product X from database
3. Add product Y to cart
4. Go to cart page

You should see the error. However I will also try to replicate it on Vanilla magento instance.

**Comment by ghost** [comment]
@webspeaks  I'm still not able to reproduce
![cart](https://user-images.githubusercontent.com/40756439/45155534-00dddd00-b1e4-11e8-8661-e376e7f0287b.gif)

**Comment by ghost** [comment]
@webspeaks  Can you still  reproduce this issue?

**Comment by webspeaks** [comment]
@engcom-backlog-nazar Sorry I forgot to tell you that I am on Magento Commerce Cloud 2.2.5. So it might be an issue in cloud version.

**Comment by ghost** [comment]
@webspeaks You have CE version or EE ?

**Comment by fooman** [comment]
@engcom-backlog-nazar Commerce would be EE

**Comment by ghost** [comment]
@webspeaks , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
