### ISSUE TITLE
Configurable product & hidden, required custom option: price not added to product price on page load.

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#17935]
### Summary

This is more UX issue but it causing some problems on production site. 
You need create a configurable product to replicate the issue, or use any of configurable products from sample data. Add a custom option to confiurable product but make sure that option is **hidden** , **required** and it adds **+10$ to the price.**

When a customer visits product page, the price they see is a simple product price, before any action is performend on product page. After customer selects all configurable product dropdowns / swatches they do see the price increasing +10... but they have no clue where this custom price is comming from. That is very confusing and UX thing that can be improved.

### Examples
I've tested this on clear installation of Magento, and a customized theme. It works the same on both installations. 
Magento CE, 2.1.7 - tested
Magento CE 2.2.5 - tested

### Proposed solution
If:
- custom option is required & hidden, price of that custom option should be added to product price visible on configurable product page before chosing any options.

I will temporary solve this by a plugin which sets product final price.

**Comment by magento-engcom-team** [comment]
Hi @qsolutions-pl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@qsolutions-pl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@qsolutions-pl, thank you for your report.
Please clarify, how can I add a ***hidden*** option to the product?

**Comment by jakwinkler** [comment]
My bad, what I refer to is a checkbox field, that is both **required** and **invisible**

**Comment by jakwinkler** [comment]
Ok, we can close the issue, Client send me "clean" magento files... with modified CORE :/ 
(2.1.7 base code, modified core)
(2.2.5 - upgrade in progress, also modified core)
Sorry to trouble you guys, will get back with more serious issues ;-)
