### ISSUE TITLE
Onepage Checkout getSerializedCheckoutConfig fails silently if json_encode fails

### ISSUE THREAD

**Issue by zack6849** [magento/magento2#17934]
### Preconditions

1. Magento 2.2.x, 2.3.x, 2.4-develop

### Steps to reproduce

1. Have secure data that won't decrypt properly with the crypt key in `env.php`
2. Visit the checkout page
3. Change crypt key in `env.php`
4. Try to go to the payment step

### Expected result

1. An error message of some sort telling me that something went wrong

### Actual result

1. Javascript Syntax error that breaks the page, which is totally acceptable, but there is no logging to indicate why
![image_2019_12_31T08_36_31_265Z](https://user-images.githubusercontent.com/51680850/71615462-2f8e7c80-2bba-11ea-8dbc-0390f8a65292.png)

2. json_encode returns false, which will  mean that the onepage checkout renders the following js

```
    <script>
        window.checkoutConfig = ;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
```

I suggest some error handling to happpen in \\Magento\\Checkout\\Block\\Onepage.php::getSerializedCheckoutConfig(), similar to the following:

```
    public function getSerializedCheckoutConfig()
    {
        $value = $this->getCheckoutConfig();
        $serialized = json_encode($this->getCheckoutConfig(), JSON_HEX_TAG);
        if(!$serialized){
            $this->_logger->critical("Failed to JSON encode checkout configuration data! " . json_last_error_msg());
        }
        return $serialized;
    }
```

So that at least an administrator can look in the log files and figure out that something is wrong, in my case that outputs the following in my `system.log`:

```
2018-09-05 13:46:30] report.CRITICAL: Failed to JSON encode checkout configuration data! Malformed UTF-8 characters, possibly incorrectly encoded [] []
```

**Comment by magento-engcom-team** [comment]
Hi @zack6849. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@zack6849 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by zack6849** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @zack6849. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @zack6849, here is your [Magento instance](https://i-17934-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-17934-2-2-3.engcom.dev.magento.com/admin](https://i-17934-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by zack6849** [comment]
As I don't have direct db access to that instance, nor file access, I can't reproduce, I will mark yes to keep the bot from tagging the issue as invalid. 

EDIT: Not sure if i'm supposed to be able to check that box to move the workflow forward or not, but i'm unable to on google chrome and firefox, so I guess i'll just wait?

**Comment by ghost** [comment]
@zack6849, thank you for your report.
Please clarify the 1st step.

**Comment by zack6849** [comment]
You need to have something that is a secured value stored in the magento checkout window.checkoutConfig, for example payment information, that is encrypted, but you have the wrong crypt key

For example, change your crypt key to something different and then try the onepage checkout with a payment prodvider configured (eg: authorize.net or something) and see what happens

**Comment by ghost** [comment]
@zack6849, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @shrikant2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30145` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by frilogg** [comment]
I have the same trouble causing Klarna Checkout not to load.

**Comment by zack6849** [comment]
I see this got marked as done, is there a commit for this that fixed it?
