### ISSUE TITLE
Bank Transer Payment Instuctions switch back to default

### ISSUE THREAD

**Issue by rstylenl** [magento/magento2#17933]
### Summary (*)
The default Magento 2 Bank Transfer Payment has an issue when you have multiple stores.
If you create an order and select Bank Transfer Payment as payment method. Then go look at the just created order the title doesn't reflect the one we have setup in the store configuration. (Says: Bank Transfer Payment instead of "Überweisung (per Bank)"

The instructions are fine. But if you click Ship, Invoice the instuction gets reset to the default value that is in the system->configuration.

### Preconditions (*)

1. Magento 2.2.x, 2.3.x, 2.4-develop
2. PHP 7.1, 7.2

### Steps to reproduce (*)

1. Create second store & store view.
2. Enable Bank Transfer Payment.
![image](https://user-images.githubusercontent.com/51680850/71616462-0cb29700-2bbf-11ea-9b9f-a25d08918d8f.png)

3. Change title & instructions of Bank Transfer Payment for second store.
![image](https://user-images.githubusercontent.com/51680850/71616477-1936ef80-2bbf-11ea-9e2a-9c6b475c4a41.png)

4. Create a new order with Bank Transfer Payment from second store.
5. Go to the Order information in the backend. 
![1](https://user-images.githubusercontent.com/51680850/71616498-2eac1980-2bbf-11ea-9be9-344e3cd1e64d.png)
6. Check email
![2](https://user-images.githubusercontent.com/51680850/71616518-4388ad00-2bbf-11ea-91c7-6d429eac103f.png)

7. Then click invoice or ship.
8. Check order info again in the backend & email

### Expected result (*)

1. Payment information should be collected from the store the orde was placed in.

### Actual result (*)

1. Payment information show the default information from Store configuration. (in backend and in emails for Invoice/Shipment):
**Admin:**
![3](https://user-images.githubusercontent.com/51680850/71616539-631fd580-2bbf-11ea-8978-d8fb1497370b.png)
**Email:**
![4](https://user-images.githubusercontent.com/51680850/71616542-687d2000-2bbf-11ea-9dfe-2c789e7c2b97.png)

**Comment by magento-engcom-team** [comment]
Hi @rstylenl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rstylenl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @rstylenl , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by rstylenl** [comment]
Small update - Even when you cancel the order the payment information will revert to the default config info.

**Comment by rstylenl** [comment]
@engcom-backlog-nazar @prakashpatel07 

I have just tested this on a Vanilla Magento 2.2.3 installation and the payment information was as expected so it did not change it back to the default store. In the email that is send to the 'client' the Payment information Title is reset to the default store, but the Instructions are from the store the client order at. See screenshots below (i removed my personal info).

After placing the order (Backend):
![order-placed](https://user-images.githubusercontent.com/6038697/47850841-f2bccf00-ddd6-11e8-94d3-5edd7285f0a7.png)

Info in Email after order is created:
![order-placed-email](https://user-images.githubusercontent.com/6038697/47850971-74acf800-ddd7-11e8-89e2-6526f59e6a87.png)


After creating the invoice: (Backend)
![after-invoice-order](https://user-images.githubusercontent.com/6038697/47850840-f2bccf00-ddd6-11e8-96a0-be699607bbbb.png)

Info in Email after creating invoice:
![invoice-email](https://user-images.githubusercontent.com/6038697/47850973-7676bb80-ddd7-11e8-99aa-9ab76e54d75b.png)

In the invoice email the title of the payment method is reset to the Default store. 
Store title is set to: Virement bancaire like you see in the backend.
Payment instructions however are correct.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30147` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rstylenl. Thank you for your report. 
The issue has been fixed in magento/magento2#26765 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [7c4be6a770ff543a6906b3d6f77b31d1988addf1](https://github.com/magento/magento2/commit/7c4be6a770ff543a6906b3d6f77b31d1988addf1)

The fix will be available with the upcoming 2.4.0 release.
