### ISSUE TITLE
Magento 2.2 Placeholder translation issue on Registration page.

### ISSUE THREAD

**Issue by mohit724** [magento/magento2#17932]
### Preconditions

Magento Version: 2.2.0
Php version: 7.0.3

### Steps to reproduce

1. Created two stores with different languages. One for English and One for Arabic. 
2. Now we have added translation's in theme for strings and all working fine except the Placeholder's on registration page. Like "Firstname , lastname , password , confirm password , email". Label's are translating but placeholder aren't.

### Expected result
Placeholder for input field's should be translated in arabic language according to store.

### Actual result
Placeholder's not translating according to store on registration page always showing in english.

![translation-issue](https://user-images.githubusercontent.com/43002651/45094144-13024180-b138-11e8-8a79-594a037a1223.png)

**Comment by magento-engcom-team** [comment]
Hi @mohit724. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mohit724 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@mohit724, thank you for your report.
Please try to reproduce this issue on a clean Magento 2 installation and reopen the issue if you succeed.
