### ISSUE TITLE
2.2.5 - View Order -Exception occured during order load

### ISSUE THREAD

**Issue by IIxauII** [magento/magento2#17937]
### Preconditions
1. Magento Version: 2.2.5
2. PHP Version: 7.1.20
3. Nginx Version: 1.14.0

### Steps to reproduce
1. "Sales" → "Orders" 
2. click "view" on Magento2 order with different billing address then shipping address

### Expected result
1. Overview of clicked order

### Actual result
1. Order page reloads → Error Message appears: "Exception occurred during order load"
2. Exception.log shows following error message:

`[2018-09-05 15:02:57] main.CRITICAL: Notice: Undefined offset: 1 in /var/www/html/magento/vendor/magento/module-sales/Model/Order.php on line 1205 {"exception":"[object] (Exception(code: 0): Notice: Undefined offset: 1 in /var/www/html/magento/vendor/magento/module-sales/Model/Order.php on line 1205 at /var/www/html/magento/vendor/magento/framework/App/ErrorHandler.php:61)"} []
`

**Comment by magento-engcom-team** [comment]
Hi @IIxauII. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@IIxauII do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @IIxauII  I'm not able to reproduce following steps your described ,  If you'd like to update it, please reopen the issue.
