### ISSUE TITLE
Wrong price shown on configurable item and added to product total

### ISSUE THREAD

**Issue by bobemoe** [magento/magento2#17944]
### Preconditions
PHP 7.0.30-1-dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-1-dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

nginx version: nginx/1.12.2

Linux dev 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux

mysql  Ver 15.1 Distrib 10.0.36-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Clean magento 2.2.5CE install using composer.
By default all prices are shown exc tax.  Also the admin is set to have prices entered exc tax.
Stores->Tax Rules->Add tax rule for uk @ 20%
Stores->Config->Sales->Tax->Default tax destination: uk
Stores->Config->Sales->Tax->Shoping cart display settings->Display Prices: inc and exc tax
Add test product, price £100, taxable items, 10 in stock, add customizable items, add dropdown, two values "A" fixed price £0 and "B" fixed price £10 
Clear the cache

### Steps to reproduce
Visit the test product on frontend. its price is displayed without tax at £100
Click the configuration dropdown and see that the item "B" is shown including tax at £12. 
Select the "B" item, and see the total is now £112.
Click add to cart
View the minicart menu, totals say £132.00 inc tax and £110.00 exc tax

### Expected result
The "B" item should be shown at £10, and when selected the product total should be £110.
This would then match the prices shown in the mincart dropdown.

### Actual result
The "B" item is shown at £12, and when selected the product total is £112.
This means an exc tax value (100) has been added to an inc tax value (12)
This does not match the prices shown in the minicart

**Comment by magento-engcom-team** [comment]
Hi @bobemoe. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bobemoe do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by bobemoe** [comment]
@magento-engcom-team I've reproduced this on a vanilla install on our dev env, do I need to also do this on yours too?

**Comment by ghost** [comment]
Hi @bobemoe  On this step  ->Click the configuration dropdown and see that the item "B" is shown including tax at £12.
I'm have item "B" Excluding tax. Can you verify it on vanilla instance ?

**Comment by bobemoe** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @bobemoe. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @bobemoe, here is your [Magento instance](https://i-17944-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17944-2-2-5.engcom.dev.magento.com/admin](https://i-17944-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bobemoe** [comment]
Confirmed the issue on your vanilla instance.
Here you can see B is at $12 where it should be $10
https://i-17944-2-2-5.engcom.dev.magento.com/test.html

The only additional step I missed out from my steps to reproduce was clearing the cache when prompted after changing config. I have updated this now.

**Comment by bobemoe** [comment]
Also, I have just noticed, on initial page display but while still loading it says $10, but it changes, while looking at the dropdown to $12 just before the page finished loading. Must be updated with JS or something?

**Comment by bobemoe** [comment]
Additionally the workaround we have found is to set this back to default values: (note: it was changed in my preconditions)

Stores->Config->Sales->Tax->Shoping cart display settings->Display Prices

Or to set all the other display settings to inc and exc tax.

**Comment by ghost** [comment]
@bobemoe the fix for this issue has already available in 2.2-develop branch.

**Comment by bobemoe** [comment]
OK cool.  Got link to the related issue?
