### ISSUE TITLE
"Name Prefix" can not be stored, if it is required and stored earlier without prefix

### ISSUE THREAD

**Issue by sskulkarni** [magento/magento2#17949]
"Name Prefix" can not be stored, if it is required and stored earlier without prefix

### Preconditions

1.php 7.0
2.Magento 2.2.5, 2.2.6-dev

### Steps to reproduce

1.Go to "Stores" > "Configuration" > "Customers" > "Customer Configuration" > "Name and Address Options" and set "Show Prefix" to "No" First.
2.Store any address in account.
3. Remove any prefix if stored in Customer or Address.
4.Now Set "Show Prefix" to "Required"
5. Now go to /customer/account/edit page in frontend.
Fill all details with "Prefix".and save.

### Expected result

1. It should save customer.

### Actual result

1. It is showing error : "Name Prefix" is a required value."
2.
![name_prefix](https://user-images.githubusercontent.com/6185521/45139072-3bd41680-b1cc-11e8-8eb0-6d365ac7a63f.png)

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sskulkarni do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sskulkarni** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni, here is your [Magento instance](https://i-17949-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17949-2-2-5.engcom.dev.magento.com/admin](https://i-17949-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sskulkarni** [comment]
Yes, Can be Reproduced in vanila instance.

**Comment by ghost** [comment]
@sskulkarni, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by jaiminparikh** [comment]
@sskulkarni and @engcom-backlog-pb I have checked for this issue and found while customer saves Account Information, Magento saves customer data and also customer address. Here there is no need to save customer address but as per customer model /app/code/Magento/Customer/Model/ResourceModel/CustomerRepository.php its saves all customer data and address.

**Comment by engcom-Charlie** [comment]
Hello @sskulkarni 

We are not able to reproduce this issue on the latest Magento 2.4-develop.

**Testing scenario:**

1. Go to "Stores" > "Configuration" > "Customers" > "Customer Configuration" > "Name and Address Options" and set "Show Prefix" to "No" First.
2. Store any address in account.
3. Remove any prefix if stored in Customer or Address.
4. Now Set "Show Prefix" to "Required"
5. Now go to /customer/account/edit page in frontend.
6. Fill all details with "Prefix".and save.

**Result:**
Address was saved as expected.
![image](https://user-images.githubusercontent.com/51680850/71584527-99a41480-2b1b-11ea-89b0-dfa5f7384496.png)

So i have to close this issue as not relevant.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest Magento 2.4-develop branch. 

Thank you for collaboration.
