### ISSUE TITLE
Error when you double-click the remove cart items button.

### ISSUE THREAD

**Issue by betooliveirame** [magento/magento2#17947]
### Preconditions

1.version 2.2.5 enterprise edition
2.Theme Luma
3. PHP 7.1

### Steps to reproduce

1.Add any product to the cart
2.Go to the cart and double-click  the remove cart items button
3. Get error: **Fatal error: Uncaught Error: Call to a member function getQty() on boolean in /src/vendor/magento/module-google-tag-manager/Model/Plugin/Quote/SetGoogleAnalyticsOnCartRemove.php on line 47**

### Expected result

1. Remove item from cart without get error.

### Actual result

1. Remove item from cart getting error

**Comment by magento-engcom-team** [comment]
Hi @betooliveira79. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@betooliveira79 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by betooliveirame** [comment]
Sorry this is for enterprise.

**Comment by trandinh2409** [comment]
Hi, @betooliveira79,
How's fix this error?

**Comment by srilathakln** [comment]
We are also getting the same error for Magento Enterprise 2.2.5. any update on this issue?

**Comment by betooliveirame** [comment]
@trandinh2409 and @srilathakln there's a patch from magento MDVA-8623_EE_2.2.0_v1. You can get it with magento team.
