### ISSUE TITLE
New Automate Dev Environment for mangento 2 

### ISSUE THREAD

**Issue by HARoonMIND** [magento/magento2#17959]
### Description

If I want to change any module , 
what I need to just write dev  command with module name ,then mangeto copy the whole module and shift to development folder while the web live work that module ,
then Magneto give me the dev link where whole website so similer but the module come from dev folder  as well as database  ,where I can see change and no need to run cache ,upgrade or static deploy command when I successful complete my task I run command module name success

**Comment by magento-engcom-team** [comment]
Hi @HARoonMIND. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@HARoonMIND do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @HARoonMIND , please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by HARoonMIND** [comment]
Hi @engcom-backlog-nazar  it is for Magento Core technical  Feature request  , I am intended to submit that idea .It not under general discussion about this issue.
@magento-engcom-team  I am willing to contribute into Magneto structure  , Please refer my idea as a feature request

**Comment by ghost** [comment]
@HARoonMIND Then please open new issue with this template ->
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

**Comment by HARoonMIND** [comment]
Alright thanks , I will work on it and then I will update it issue properly
