### ISSUE TITLE
Missing Customer Register Mag 2.2.5

### ISSUE THREAD

**Issue by lombokindustries** [magento/magento2#17950]
Customer Register's missing after upgrading from 2.1.10 to 2.2.5.

**Comment by magento-engcom-team** [comment]
Hi @lombokindustries. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lombokindustries do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-andrii** [comment]
@lombokindustries ,  we were not able to reproduce this issue. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

I  have taken the following steps:

1. Install Magento 2.1.10.
2. Have made an upgrade to version 2.2.5.
Actual Result: User registration works well, no problems or errors detected.

**Comment by magento-engcom-team** [comment]
Hi @lombokindustries 

Unfortunately we can not provide any help for the reports not containing all required information. Please update the report and reopen if the issue persists.
