### ISSUE TITLE
Minimum Order Amount for Free Shipping doesn't work.

### ISSUE THREAD

**Issue by davidduong90** [magento/magento2#17962]
### Preconditions
1. Magento 2.2.5 with sample data

### Steps to reproduce
1. STORES > Settings > Configuration > Sales > Shipping Methods > Free Shipping > Enabled > select Yes > Minimum Order Amount > enter 69 > Save Config

### Expected result

1. Free Shipping must don't show when Subtotal less 69.

### Actual result
Free Shipping still show when Subtotal is less 69(57).
http://prntscr.com/krkehg
http://prntscr.com/krkecv
http://prntscr.com/krkeqc

**Comment by magento-engcom-team** [comment]
Hi @davidduong90. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@davidduong90 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@davidduong90, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by davidduong90** [comment]
Ok, Hope hear fix it soon. Good job.

**Comment by jaimin-ktpl** [comment]
Hello @davidduong90,

I have checked for the suggested issue. The results you are getting is not related to any bug in the code.

Magento sample data comes with some of the 'Cart price rules' created by default.
There is one rule with Magento sample data which allows free shipping for total above $50.
Go to
Admin panel > Marketing > Cart Price Rules
Open rule '**Spend $50 or more - shipping is free!**'
This is the rule responsible for adding free shipping for your quote.

Please check if you have this rule disabled or not. If enabled, disable the rule if you do not want free shipping over $50 and your configuration settings for 'Minimum Order Amount' should work as expected.

**Comment by davidduong90** [comment]
Great. Thanks you.
