### ISSUE TITLE
Customer Registration is not working on Front end and Backend after Data Migration from Magento 1.9.3.7 to Magento 2.2.5

### ISSUE THREAD

**Issue by Usman1493** [magento/magento2#17963]
### Summary

I have a fresh installation of `Magento 2.2.5` with Template Monster theme and I have migrated the data from `Magento 1.9.3.7` to `Magento 2.2.5` using data migration tool. Now when I try to create an account by entering all the fields and click the create button, It reloads the same registration page showing an error message that " `"" is a required Field`". I have checked the `app/design/frontend/THEME_VENDOR/THEME/Magento_Customer/templates/form/register.phtm`l file and it contains the form key

`<?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>`

So, its not a form key problem I have deleted all the cookies too, but still no luck.

I have traced the post request after clicking the create customer button in the network tab and the post request goes to CreatePost.php in `/vendor/magento/module-customer/Controller/Account/CreatePost.php` and the request status is 302 found.

The request goes till `vendor/magento/module-customer/Model/AccountManagement.php `and in createAccountWithPasswordHash function it goes in catch block of Localized Exception and prints " "" is a required field" on clicking the create account button. Same is the case with backend.

### Examples

![screenshot from 2018-09-07 11-38-36](https://user-images.githubusercontent.com/30326249/45202837-a7cd8200-b293-11e8-8a23-d5c724f5b436.png)

Any one with the solution for this?

**Comment by magento-engcom-team** [comment]
Hi @Usman1493. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Usman1493 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Usman1493, problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.
