### ISSUE TITLE
Using a " in product title causes jquery error

### ISSUE THREAD

**Issue by MartinAarts** [magento/magento2#17967]
Preconditions:
Magento 2.2.5

Steps to reproduce:
Use a " in a product title

Expected result:
" being displayed.

Actual result:
Page javascript not loaded correctly, because " is not being escaped.

![schermafbeelding 2018-09-07 om 14 34 55](https://user-images.githubusercontent.com/22233203/45219465-50d3a700-b2ab-11e8-9c00-3512dcd8b535.png)

**Comment by magento-engcom-team** [comment]
Hi @MartinAarts. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MartinAarts do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by MartinAarts** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @MartinAarts. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @MartinAarts, here is your [Magento instance](https://i-17967-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17967-2-2-5.engcom.dev.magento.com/admin](https://i-17967-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by MartinAarts** [comment]
I'm able to reproduce the issue in the given instance. See attached screenshots. Now visible at this url:
https://i-17967-2-2-5.engcom.dev.magento.com/test-product.html

For example, image keeps loading, JS gives error.
![schermafbeelding 2018-09-07 om 14 41 19](https://user-images.githubusercontent.com/22233203/45219765-4ebe1800-b2ac-11e8-8f77-eeaa770372a9.png)
![schermafbeelding 2018-09-07 om 14 41 13](https://user-images.githubusercontent.com/22233203/45219766-4ebe1800-b2ac-11e8-99b9-cef07f5fa32a.png)

**Comment by hostep** [comment]
This is a known problem and is already fixed on the `2.2-develop` branch.
Let's close it as a duplicate of https://github.com/magento/magento2/issues/15631 & https://github.com/magento/magento2/issues/15037 & https://github.com/magento/magento2/issues/15491 & probably some others.

**Comment by DanielRuf** [comment]
> Preconditions:
> Magento 2.2.5

**Comment by DanielRuf** [comment]
> This is a known problem and is already fixed on the 2.2-develop branch.

I see no fix there.
