### ISSUE TITLE
Backend Order creation Authorizenet: If invalid credit card number is entered the loader keeps spinning forever without any error message

### ISSUE THREAD

**Issue by Jakhotiya** [magento/magento2#17964]
### Preconditions

1. Magento 2.2-develop branch
2. Enable Authorizenet payment gateway

### Steps to reproduce

1. Go to Admin-> Sales -> Order->Create new Order
2. Add items to card and choose shipping method
3. Select Authorizenet Credit Card as payment method. 
4. Input an invalid credit card number, like just enter 10 digits credit card number
5. Hit submit Order, loader shows up and keeps spinning forever

### Expected result

1. If entered Credit card number is incorrect, it should propmt user to enter correct card number. The loader should stop.

### Actual result

1. The loader keeps spinning forever. There are no javascript errors in console, or logs.
![screen shot 2018-09-07 at 12 30 12 pm](https://user-images.githubusercontent.com/9327315/45203432-d77f8880-b299-11e8-965c-664aa0722a01.png)

**Comment by magento-engcom-team** [comment]
Hi @Jakhotiya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Jakhotiya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by Jakhotiya** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Jakhotiya. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jakhotiya, here is your [Magento instance](https://i-17964-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17964-2-2-develop.engcom.dev.magento.com/admin](https://i-17964-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jakhotiya** [comment]
@magento-engcom-team Yes I was able to reproduce the issue.
![screen shot 2018-09-07 at 12 41 23 pm](https://user-images.githubusercontent.com/9327315/45203974-7eb0ef80-b29b-11e8-97b0-6d5fa2629c3d.png)

**Comment by ghost** [comment]
Hi @Jakhotiya  , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by passtet** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @passtet. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @passtet, here is your [Magento instance](https://i-17964-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17964-2-2-develop.engcom.dev.magento.com/admin](https://i-17964-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jakhotiya** [comment]
Hi @passtet, are you working on this issue, if not I'll start working on it. Let me know.

**Comment by ghost** [comment]
Related pr https://github.com/magento/magento2/pull/17986

**Comment by engcom-Charlie** [comment]
Hello @Jakhotiya 

We are not able to reproduce this issue on the latest Magento 2.4-develop.
We cannot test with Authorize.Net Direct Post because it is deprecated payment method 
(has been replaced by just Authorize.Net) see more [here](https://docs.magento.com/m2/ce/user_guide/payment/authorize-net-direct-post.html).

**Testing scenario:**
1. Configure Authorize.net payment method
2. Go to Admin-> Sales -> Order->Create new Order
3. Add items to card and choose shipping method
4. Select Authorize.net Credit Card as payment method.
5. Input an invalid credit card number, like just enter 10 digits credit card number
6. Hit submit Order

**Result:**
If entered Credit card number is incorrect, you can enter correct card number
![image](https://user-images.githubusercontent.com/51680850/71578008-02c95f00-2aff-11ea-98b3-d560cb1a9451.png)

So i have to close this issue as not relevant.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest Magento 2.4-develop branch. 

Thank you for collaboration.
