### ISSUE TITLE
Adding product to bundled product option fails

### ISSUE THREAD

**Issue by bamboekeizer** [magento/magento2#17972]
### Preconditions
Magento 2.2.5
1. Simple product exists
2. Bundled product exists with no options (products)

### Steps to reproduce
1. Add an option to the bundled product
2. Add products to option

### Expected result

1. add product windows opens and retrieved products are displayed to select them for the bundle option

### Actual result

1. The add products window opens, no products are retrieved, and error message is shown
2. Error messsage A technical problem with the server created an error ...
3. Host failure log file shows
[F[lsapi:error] [pid 450214:tid 139795005236992] Backend fatal error: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\\Framework\\View\\Element\\UiComponentFactory::argumentsResolver() must be of the type array, null given, called in /home/u56354823456/domains/bliepbliep.nl/public_html/m2test/vendor/magento/framework/View/Element/UiComponentFactory.php on line 206 and defined in /home/u56354823456/domains/bliepbliep.nl/public_html/m2test/vendor/magento/framework/View/Element/UiComponentFactory.php:172\nStack trace:\n#0 /home/u56354823456/domains/bliepbliep.nl/public_html/m2test/vendor/magento/framework/View/Element/UiComponentFactory.php(206): Magento\\Framework\\View\\Element\\UiComponentFactory->argumentsResolver('bundle_product_...', NULL)\n#1 /home/u56354823456/domains/bliepbliep.nl/public_html/m2test/vendor/magento/module-ui/Controller/Adminhtml/Index/Render.php(69): Magento\\Framework\\View\\Element\\UiComponentFactory->create('bundle_product_...')\n#2 /home/u56354823456/domains/bliepbliep.nl/public_html/m2test/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/I in /home/u56354823456/domains/bliepbliep.nl/public_html/m2test/vendor/magento/framework/View/Element/UiComponentFactory.php on line 172\n, referer: https://m2test.bliepbliep.nl/electric/catalog/product/edit/id/23/set/4/key/13b8aaf3c35edb514598358d3b4108102743be9261561eb1e0bda6fea6bc126e/type/bundle/store/0/back/edit/

**Comment by magento-engcom-team** [comment]
Hi @bamboekeizer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bamboekeizer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by bamboekeizer** [comment]
I cannot reproduce on the vanilla Magento instance.
I started magento 2 on an earlier release and had a few products. After upgrade to version 2.2.5 I started to add a bundled product and this failure occurred.

**Comment by bamboekeizer** [comment]
I installed a fresh 2.2.5 install and the problem cannot be reproduced, so it works properly on the vanilla version.
I used the fresh 2.2.5 install and used my existing database. Then the problem reproduced.

**Comment by ghost** [comment]
Hi @bamboekeizer GitHub is intended for bug reports, please use Magento Stack Exchange for questions on how particular customization can be implemented. 
The problem not related to magento, I'm not able to reproduce this with migrated 2.2.3 to 2.2.5 versions
