### ISSUE TITLE
Cart gets automatically emptied on none cached paged

### ISSUE THREAD

**Issue by matin73** [magento/magento2#17973]
### Preconditions

1. Magento 2.2.x, 2.3.x, 2.4-develop
2. PHP 7.0, 7.2

### Steps to reproduce

1. Install fresh Magento 
2. Disable `Magento_Persistent` module 

3. Go to shop and add first product to cart -> works correct. Then go to next product (important: product page/category page must not be in page cache). Now cart ist automatically emptied - no product in cart. Same behaviour if you have several products in cart (only possible if you have product pages in cache) and go to product search. So, search results are not in cache - cart gets emptied.

### Expected result

1. All products should be in cart and cart should not get emptied

### Actual result

1. Cart is automatically emptied on non cached product pages

--------------------------------------------------------
If you turn off caching at all (shure, not recommended - but for testing) you can add any product to cart ... After enabling all modules listed above cart is working correct. So I think there is some bug with 1one or more module listed above

**Comment by magento-engcom-team** [comment]
Hi @matin73. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@matin73 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by matin73** [comment]
@matin73 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

 x  yes
    no

**Comment by ghost** [comment]
Hi @matin73  , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by chernenm** [comment]
Hello everyone,

We have investigated the root cause of the issue and came to conclusion that actual result is a by design behavior. If custom attribute is set as a required one than it must be configured to be shown on storefront and to be shown in all the forms.
If merchant wants a custom attribute to be required only on some certain forms, then an extension attribute should be used instead. Extension attributes are used to extend functionality of custom attributes.
Please find more details here https://devdocs.magento.com/guides/v2.0/extension-dev-guide/attributes.html

**Comment by Jakhotiya** [comment]
Hi @chernenm Can you please clarify your last comment and it's relevance in this issue? What do you mean by "shown in all the forms"? What forms are we talking about here? And when you say "actual result is a by design behavior" are you saying this issue does not need a fix ie. this is not an issue?

**Comment by Jakhotiya** [comment]
@magento-engcom-team give me {2.2.5} instance

**Comment by Jakhotiya** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @Jakhotiya. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jakhotiya, here is your [Magento instance](https://i-17973-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17973-2-2-5.engcom.dev.magento.com/admin](https://i-17973-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jakhotiya** [comment]
Hi @matin73 I was not able to reproduce this issue on clean test instance of magento 2.2.5 given by @magento-engcom-team 
One thing I could not do is disable those modules that you listed in steps. On my end I'll try to get that version setup but can you send us some screenshots. Or you can enable all modules and then try to reproduce the issue. That way we can be sure, disabling a module isn't causing the problem. It would be big help.

**Comment by ghost** [comment]
@Jakhotiya Try disable following modules, then add to cart product, and refresh page, cart will be empty

**Comment by Jakhotiya** [comment]
@engcom-backlog-nazar Is there a way to disable modules on instance given by @magento-engcom-team

**Comment by ghost** [comment]
@Jakhotiya no seems there no able to do this, you can only reproduce on your own local instance.

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
I'm running into this on 2.3.3. I'm in the process of looking into it, and I just wanted to post what I have found so far. The issue happens when the module Magento_Persistent is disabled. I think the issue is that the checkout session gets cleared in \Magento\Checkout\Model\Layout\DepersonalizePlugin. When Magento_Persistent is enabled, the checkout session is still cleared, but it seems to be restored later.

That's all I have for now. Will continue digging into this one.

**Comment by ghost** [comment]
Actually, I'm not going to dig into this one...I'm just going to enable the Magento_Persistent module.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30125` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by erikhansen** [comment]
@magento-engcom-team [The 2.3.3 release notes](https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-open-source.html#cache) say that:

> Full-page cache no longer clears out the checkout session data on uncached pages when the <code class="highlighter-rouge">Magento_Persistent</code> module is disabled. <a href="https://github.com/magento/magento2/issues/21614">GitHub-21614</a>

If this indeed the case, can you provide a link to the commit that fixed this issue and then close this issue?
