### ISSUE TITLE
Sitemap grid display incorrect base URL in the grid if using multiple stores

### ISSUE THREAD

**Issue by nntoan** [magento/magento2#17999]
### Preconditions

1. Magento 2.2.5 (should be reproducible in any version of 2.1 or 2.3)
2. PHP 7.1

### Steps to reproduce

1. Setup multiple websites/stores with different base URL. For e.g
 - `www.example-nz.localhost` for New Zealand website
 - `www.example-au.localhost` for Australia website
 - `www.example-uk.localhost` for United Kingdom website
 - `www.example-us.localhost` for United States website
 - `www.admin.example-nz.localhost` for default config base url
2. Go to Marketing > SEO & Search > Site Map

### Expected result

![screenshot from 2018-09-10 15-27-06](https://user-images.githubusercontent.com/3891429/45277935-fede8b80-b50d-11e8-9468-86f19974ca2f.png)

### Actual result

![screenshot from 2018-09-10 15-18-00](https://user-images.githubusercontent.com/3891429/45277727-f5085880-b50c-11e8-9887-56c8f2e48955.png)

**Comment by magento-engcom-team** [comment]
Hi @nntoan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nntoan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ghost** [comment]
Hi @nntoan , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by nntoan** [comment]
@engcom-backlog-nazar @p-bystritsky I also opened a PR for it.

**Comment by magento-engcom-team** [comment]
Hi @nntoan. Thank you for your report. 
The issue has been fixed in magento/magento2#18000 by @nntoan in 2.2-develop branch
Related commit(s):
 - [1172aae5018f4d9cf0414c30073af78c6c432459](https://github.com/magento/magento2/commit/1172aae5018f4d9cf0414c30073af78c6c432459)

The fix will be available with the upcoming 2.2.8 release.

**Comment by slavvka** [comment]
Hi @nntoan. Thank you for your report. 
The issue has been fixed in magento/magento2#18228 by @nntoan in 2.3-develop branch
Related commit(s):
 - [5144320c210c7afadda5eb6a316cf9a5f54ad139](https://github.com/magento/magento2/commit/5144320c210c7afadda5eb6a316cf9a5f54ad139)

The fix will be available with the upcoming 2.3.1 release.
