### ISSUE TITLE
Can't re-order from the admin area when the order contains configurable products

### ISSUE THREAD

**Issue by jamesryanbell** [magento/magento2#18006]
### Preconditions

1. 2.2.2
2. Admin area

### Steps to reproduce

1. Within the admin area choose an order that contains configurable items
2. Press reorder

### Expected result

1. A new order should be created containing the items of the selected order

### Actual result

1. Message(s) appear at the top of the page stating "Product "XXXX" not found. This product is no longer available.

**Comment by magento-engcom-team** [comment]
Hi @jamesryanbell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jamesryanbell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by adarshkhatri** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri, here is your [Magento instance](https://i-18006-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-18006-2-2-4.engcom.dev.magento.com/admin](https://i-18006-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by adarshkhatri** [comment]
I am having same issue on my Magento ver. 2.2.4 EE. It's fresh install with sample data in it.

**Summary of the issue**
Can't re-order from the admin area when the order contains configurable products

**Preconditions**

1. 2.2.4 EE
2. Admin area

**Steps to reproduce**
Within the admin area choose an order that contains configurable items
Press reorder

**Expected result**
It should take me to the order creation area (admin), and filled all the items from the selected order

**Actual result**
Message(s) appear at the top of the page stating "Product "XXXX" not found. This product is no longer available.

**I have tested in vanilla and it works, no error thrown.** What option do I have there?

**Comment by ghost** [comment]
Hi @jamesryanbell i'm not able to reproduce following steps your described. did you check if that product exist?

**Comment by jamesryanbell** [comment]
Hi, yes we have checked the products do exists. We have done a number of test orders and this occurs for each configurable product. When I do the reorder from the user front end in my account area the re-ordering works correctly.

These products were all added via the standard product importing if that helps at all.

Thanks,
James

**Comment by ghost** [comment]
@jamesryanbell  this problem related to you import csv file, can you provide more information about this ?

**Comment by jamesryanbell** [comment]
Hi @magento-engcom-team we have formatted our CSV in the Magento format. It sounds like @adarshkhatri was able to reproduce this error on the latest version based on his post above so it sounds like a wider issue.

Thanks,
James

**Comment by ghost** [comment]
@jamesryanbell  @adarshkhatri  used enterprise version .
![reorder](https://user-images.githubusercontent.com/40756439/45346641-6a7a3480-b5b2-11e8-873b-2191537b6439.gif)

**Comment by jamesryanbell** [comment]
Apologises I should have stated, we also using the Enterprise Edition. Would you like a screen share similar to yours of the issue I'm seeing?

**Comment by ghost** [comment]
@jamesryanbell , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by davidandersson1** [comment]
Hello,

We are using magento open source 2.4.3-p1 and faced same issue on admin reorder time, means existing order contains configurable product and after press on reorder button on admin area we faced below error 

"Product "{sku}" not found. This product is no longer available."

Please let me know if Is there any solution for this issue!

Thanks,
David Andersson

**Comment by PhanQuocPhu** [comment]
Facing this issue too.
It might because of the attribute value.
We are using Magento EE 2.4.4-p4, customer placed an order which contain an config product "sku=123" on 11th oct, config attr "size = 8 lbs" and child product sku = 123xx for that size value.
Our client change from "size = 8 lbs" to "size = 10 lbs" on 12 oct, but using the same child product for the new size value, which mean "sku = 123xx".
When magento check the availabily of the product, it will filter base on the product item information in the order, which mean attr size = 8 lbs, sku = 123xx" of the config product "sku=123" which doesn't available anymore, and return an error
The problem here is the error message don't contain enough information, it make me think it was because of the stock at first.
