### ISSUE TITLE
Product status is not updating properly in admin's product listing page when there are unused storeview data.

### ISSUE THREAD

**Issue by heyqule** [magento/magento2#18008]
Product status is not updated properly in product grid.  This is caused by product status value in a disabled storeview.  

This may be also be the cause of https://github.com/magento/magento2/issues/8795

### Preconditions
1. Magento 2.1.4

### Steps to reproduce
1. Create an enanbled product.
2. Enable it for multiple storeviews (e.g Store A and Store B), copy data from default.
3. Make sure store view values are not using default value.
4. Disable Store B in the product edit page's "Product In Websites" section
5. Disable the product in default view and Store A storeview.

### Expected result
1. The disabled product should show disabled in admin's product listing page

### Actual result
1. The disabled product still show enabled in admin's product listing page

### The cause and temporary workaround
When I check the database,  the enable status of Store B is set to YES.  The admin's product listing page is still taking that value into consideration.   I was able to fix it by forcibly disabled the product in the deselected storeview.   I think the copied data should be removed when you deselect a storeview in "Product In Websites".

This is the SQL I run to fix the issue:
UPDATE catalog_product_entity_int set value = 2 where attribute_id = 97 and store_id IN (affected, store, ids)

**Comment by magento-engcom-team** [comment]
Hi @heyqule. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@heyqule do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by heyqule** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @heyqule. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @heyqule, here is your [Magento instance](https://i-18008-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18008-2-2-5.engcom.dev.magento.com/admin](https://i-18008-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by heyqule** [comment]
"Do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?"

The original issue seems fixed in 2.2.5.  However, I found another bug.  The enabled value looks like depend on the storeview of default website. 

I played around with the product status value of default scope, Default Store, Store A and Store B.    If I set status to disable in "Default Store" and enabled in default scope, Store A and B,  the product will show disabled in admin's product list page.  Vise versa, If I set status to enable in "Default Store" and disabled in default scope, Store A and B,  the product will show enabled in admin's product list page.

**Comment by ghost** [comment]
Hi @heyqule this issue has already fixed in 2.2.5 release, The product grid list show products with default store view.

**Comment by dqblanco** [comment]
Thank you @engcom-backlog-nazar. Can you help me?. Where code was changed?. 
 I have the same version code in local and production, but the problem continua in production.  Anythink idea?

**Comment by ghost** [comment]
Hi @heyqule I'm can't find commit for this issue, but on 2.2-develop branch this works perfectly

**Comment by magento2dev** [comment]
Hi @dqblanco,
Did you finally find the updated code to fix this issue ?

Thanks !
