### ISSUE TITLE
Category field value changes for "all" stores not working using JSON API

### ISSUE THREAD

**Issue by kolonuk** [magento/magento2#18005]
### Preconditions

1. Magento 2.2.5, fresh install.

### Steps to reproduce

1. Fresh install, generated API keys.
2. Create store1.
3. Create store2.
4. Call API category endpoint to create new category, POST https://{{url}}/index.php/rest/all/V1/categories/.
5. Call API category endpoint to change category name PUT.

### Expected result

1. Category name changed in "default", "store1" and "store2" store views,

### Actual result

1. Category name changed in only store1 and store2.  "default" store untouched.

To change the default store, I need to pass either "?storeid=0" in the url, or specifically change the endpoint URL to include the "default" store view.  Adding "?storeid=0" using the "all" store URL reference delivers same effect as Actual result (ie no difference)

I am working with the principal that categories are the same across all stores, and it's just the products offered for each store that are different - ie for products I call the store specific URL, and for things like categories, attributes, etc. I do calls with the "all" store id.

In the short term, I have made a rule that the default store is not to be used, and another store which acts as the default is created and used.

This seems so fundamental, but I really can't find this referenced anywhere else, so apologies if this is already answered in some way somewhere else.

**Comment by magento-engcom-team** [comment]
Hi @kolonuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kolonuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment]
This sounds like a duplicate of https://github.com/magento/magento2/issues/17186 ?

**Comment by ghost** [comment]
Hi @kolonuk close this issue as duplicate to https://github.com/magento/magento2/issues/17186
