### ISSUE TITLE
Authorize.net Directpost Production Integration with Magento 2.2.5 haveing issue

### ISSUE THREAD

**Issue by elamurugan** [magento/magento2#18010]
Checked multiple tickets here and in stackexchange - none of that works for me though the same system works ok with sandbox account, using production account not working. Changed transaction key and hash key multiple times between test mode enable/disable and currently below setting also not working.

**Preconditions**

- Magento 2.2.5
- PHP7
- Authorize.net production account with public accessible https enabled magento single store website 

**Steps to reproduce**

- Use Authorize.net Directpost Gateway with Production Access + Test Mode > Yes and authroize.net Account test Mode Yes
- Input Test credit card details

**Expected result**
Successful Test orders on magento side and authorize.net transactions list

**Actual result**
When using test credit card numbers such as 370000000000002 American Express Test Card getting response in log file like

> main.CRITICAL: Please enter a transaction ID to authorize this payment. 

My configuration looks like this

![image](https://user-images.githubusercontent.com/168342/45340768-f3b74a00-b565-11e8-913e-e02b9587fc2d.png)

![image](https://user-images.githubusercontent.com/168342/45340783-003ba280-b566-11e8-9d79-9a52b67266c0.png)

In transaction.dll request is as following 

`x_version: 3.1
x_delim_data: FALSE
x_relay_response: TRUE
x_test_request: TRUE
x_login: 7yX75Ls5
x_method: CC
x_relay_url: https://domain.com/authorizenet/directpost_payment/response
x_type: AUTH_ONLY
x_fp_sequence: 139
x_invoice_num: 000000180
x_amount: 30.92
x_currency_code: USD
x_tax: 0.00
x_freight: 20.00
x_first_name: Elamurugan
x_last_name: N
x_company: test
x_address: test
x_city: Troy
x_state: Michigan
x_zip: 48083
x_country: US
x_phone: test
x_fax: 
x_cust_id: 
x_customer_ip: 98.250.230.105
x_customer_tax_id: 
x_email: test@test.com
x_email_customer: 0
x_merchant_email: 
x_ship_to_first_name: Elamurugan
x_ship_to_last_name: N
x_ship_to_company: test
x_ship_to_address: Street test
x_ship_to_city: Troy
x_ship_to_state: Michigan
x_ship_to_zip: 48083
x_ship_to_country: US
x_po_num: 
x_fp_timestamp: 1536645256
x_fp_hash: test
controller_action_name: directpost_payment
is_secure: 1
x_card_code: 2123
x_exp_date: 05/22
x_card_num: 370000000000002`

Response for transaction.dll contains

> <script>window.location="https://domain.com/authorizenet/directpost_payment/redirect/x_invoice_num/000000179/success/0/error_msg/Please%20enter%20a%20transaction%20ID%20to%20authorize%20this%20payment./controller_action_name/directpost_payment/is_secure/1/";</script>

![image](https://user-images.githubusercontent.com/168342/45340738-c8345f80-b565-11e8-86a0-26adad8582ef.png)

I also made sure there is no website level separate config added, Not sure whats missing in my configuration.

**Comment by magento-engcom-team** [comment]
Hi @elamurugan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@elamurugan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @elamurugan I'm not able to reproduce following steps you described, please try reproduce this on vanilla instance.

**Comment by ghost** [comment]
Hi @elamurugan @ankurverma5540 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided.
If you like to update this, please reopen issue
