### ISSUE TITLE
Unable to save a customer for the second website in the backend with an allowed country in the address, which is not allowed for the first website

### ISSUE THREAD

**Issue by svenleemaier** [magento/magento2#18014]
### Preconditions

1. Magento 2.2.5
2. PHP 7.0.16
3. MySQL 5.7.18
4. Just updated from 2.1.7 to 2.2.5

### Steps to reproduce

1. Create 2 Websites with 1 Store and 1 Store view each
2. Configure the first Website with 1 allowed country (eg. DE for Germany)
3. Configure the second Website with other allowed countries (eg. FR for France)
4. Use the `Share Customer Accounts`: `Per Website` in the `Account Sharing Options` in the `Customer Configuration`
5. Add a new customer in the backend with the second website associated and add a address with the allowed country for the second website (in this case "France")
6. Try to "Save Customer"

### Expected result

1. Customer should saved with your inserted data.

### Actual result

1. Customer wasn't saved.
2. There is no save message nor an error message.
3. You will stay in the form without any information.

Creating a customer from the frontend is working correctly, but if you want to edit such a customer from the second website with an address with an allowed country for the second website, that is not allowed in the first website, you will get the behaviour described before. 
With such a frontend created customer you can try to edit this customer in the customer grid in the backend (this quick edit in the customer grid) - if you try to save this customer you will get an error message:

`` [Customer ID: 1] Invalid value of "FR" provided for the countryId field. ``

This seems to be the same error as when you try to add a customer or if you edit such a customer in the backend edit form, but there will be no error message ...

The problem is located in the `Magento/Customer/Model/Address/AbstractAddress.php` (https://github.com/magento/magento2/blob/2.2.5/app/code/Magento/Customer/Model/Address/AbstractAddress.php#L626) while getting the country collection - it is called without any store parameter. So it will get the allowed country list from the default store from the default website (in our case from the first website's store view: DE).

A solution could be to get the country collection with a store parameter from the customer:
- before:
`if (!in_array($countryId, $this->_directoryData->getCountryCollection()->getAllIds(), true)) {`
- changed to:
`if (!in_array($countryId, $this->_directoryData->getCountryCollection($this->getCustomer()->getStoreId())->getAllIds(), true)) {`

**Comment by magento-engcom-team** [comment]
Hi @svenleemaier. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@svenleemaier do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @svenleemaier this is duplicate for https://github.com/magento/magento2/issues/18013

**Comment by svenleemaier** [comment]
Hi @engcom-backlog-nazar,
yes I have seen the duplicated bug report directly after I have commited mine - as I started to write this bug report the duplicate #18013 wasn't there - I'm such a lucky one ;-)

Greetings,
Lee
