### ISSUE TITLE
Unable to edit customer via admin panel for various websites.

### ISSUE THREAD

**Issue by LordHansolo** [magento/magento2#18013]
### Preconditions

1. Magento 2.2.5

### Steps to reproduce

1. Create multi website multi store
2. Restrict available countries for every website Stores->Settings->Configuration->General->General->Allow Countries. Make sure for every website are available different countries.
3. Create customer for every website with billing address and shipping address appropriate for website that he is assigned.
4. Try edit customer via admin panel.

### Expected result

1. Customer can be edited via admin panel for every website and every store.

### Actual result

1. Customer can be edited only for default website.
2. Error message appear "[Customer ID: 13247] Invalid value of "PL" provided for the countryId field."

### Additional Information

Magento 2 get allowed countries for default store instead customer store during address validation during customer edit via admin panel.
class "Magento\Customer\Model\Address\AbstractAddress" method "validate" code line 626 code fragment "$this->_directoryData->getCountryCollection()" For method "getCountryCollection" should be passed store specified for customer.

**Comment by magento-engcom-team** [comment]
Hi @LordHansolo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LordHansolo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @LordHansolo The fix for this issue already available on 2.2-develop branch. but i'm able to find commit or PR of this fix.

**Comment by fritzmg** [comment]
We are experiencing this exact problem in a Magento `2.2.5` installation. However, judging by the labels and state of this ticket I am unsure whether it's supposed to be fixed there.

**Comment by fritzmg** [comment]
Ah, seems to have been fixed in Magento `2.2.6`: https://github.com/magento/magento2/commit/c23480acc89026c890e2ab6ad809cb7a0d30f9b6#diff-928482533445351591487945e14cca3bR626
