### ISSUE TITLE
magento extension not working 

### ISSUE THREAD

**Issue by prashant-techindustan** [magento/magento2#18016]
I have installed an multistore extension (https://landofcoder.com/magento-2-currency-auto-switcher.html)
but it is not working in the frontend , the stores and currency are not switching automatically , I have to change them manually then they are working.

I have run these commands ::
uploaded unzip folders in magento respective subfolders
sudo php bin/magento setup:upgrade
sudo php bin/magento setup:di:compile
sudo php bin/magento setup:static-content:deploy
sudo php bin/magento cache:flush
sudo php bin/magento indexer:reindex

I have also done all the configrations and enabled the extension also.

after running these commands the design of the site gets disturb and all the CSS abd JS files are not loaded OR not found , so first issue is how to run the css and js files and another issue is that if they run then stores and currencies are not auto switched .

What may be the issue ?

**Comment by magento-engcom-team** [comment]
Hi @prashant-techindustan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@prashant-techindustan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @prashant-techindustan, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
