### ISSUE TITLE
Issue on Adding Custom Grid in Custom Form Tabs in Admin

### ISSUE THREAD

**Issue by ankurverma5540** [magento/magento2#18021]
I am trying to add custom grid on custom tabs in admin. This is my file that is under Tab folder that is causing issue.
namespace Vendor\Warranty\Block\Adminhtml\Warrantydetails\Edit\Tab;
use Magento\Backend\Block\Widget\Tab\TabInterface;

class Warrantyrule extends \Magento\Backend\Block\Widget\Grid\Container implements TabInterface
{
    protected function _construct()
    {
        $this->_controller = 'adminhtml_warrantydetails';
        $this->_headerText = __('Warranty Rules');

        if ($this->_model->getId()) {
            $this->_addButtonLabel = __('Add New Rule');
            $this->addButton(
                'add_new',
                [
                    'label' => $this->getAddButtonLabel(),
                    'onclick' => 'setLocation(\'' . $this->getCreateUrl() . '\')',
                    'class' => 'add primary'
                ],
                0,
                0,
                $this->getNameInLayout()
            );
        }

        $this->removeButton('add');
    }
}
But this causes an issue. The Page is blank and in system.log there is and error

`Class Magento\Backend\Block\Adminhtml\Warrantydetails\Grid does not exist`
I think the issue is because of 
`$this->_controller = 'adminhtml_warrantydetails';`

**Comment by magento-engcom-team** [comment]
Hi @ankurverma5540. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ankurverma5540 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @ankurverma5540 I'm not able to reproduce following steps your describes. which version of magento you used ?

**Comment by ghost** [comment]
@ankurverma5540 , thank you for your report.
We were not able to reproduce this issue by following the steps you provided. It's obvious your problem is caused by custom code.
If you like to update this, please reopen issue
