### ISSUE TITLE
User role issue with cache management menu 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18029]
After creating the user role with cache management,Amazon log menu items are also display with that. 
### Preconditions

1.Magento Version 2.2.5 with sample data
2.PHP 7.0

### Steps to reproduce

1.System > Permission > User Roles
2.Create a role under "Roles Resources" for the “cache Management” access (Role only for Cache Management).
3.Then create a user with the above-specified user role.
4.Log in with the new user(with the above-specified role) and you will notice “Client & IPN” menus of Amazon Logs are displayed with cache management menu 

### Expected result

Only cache management menu will display under system menu 

### Actual result

Under system menu cache management menu and “Client & IPN” menus of Amazon Logs are display with that

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @emiprotechthe fix for this issue has already available in 2.2-develop branch
2.2.5
![selection_083](https://user-images.githubusercontent.com/40756439/45432468-9aa8fc80-b6b2-11e8-89bd-97c7cdb76d4b.png)
2.2-develop
![selection_082](https://user-images.githubusercontent.com/40756439/45432481-a09edd80-b6b2-11e8-9114-b55c0f4f6e2f.png)

**Comment by andy17612** [comment]
hi @engcom-backlog-nazar 
can you share the link? thank you!^^"
