### ISSUE TITLE
Magento Luma Default Footer Not Showing

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#18022]
Magento Version: Magento community 2.2.5

Issue Summary - 
Magento Luma default theme footer is no longer visible on our website.

Possible Cause -
1. In Admin->Content->Design->Configuration, html code was added to footer section for Magento Luma theme from admin panel.

Once, that code was removed the original footer did not restore. 

Please advise how we can get original footer back.

Thanks
Aditya

**Comment by magento-engcom-team** [comment]
Hi @adityag186. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@adityag186 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by adityag186** [comment]
Summary of the issue
 Magento Luma default theme footer is no longer visible on our website.
Information on your environment
Version : Community edition 2.2.5
Steps to reproduce
1. add Custom html code to Admin->Content->Design->Configuration, html code was added to footer section for Magento Luma theme from admin panel.
2. Remove the custom html code
Expected and actual results
Expected
Magento 2 Luma theme original footer should be restored.
Actual
Magento 2 Luma theme footer not restored. No footer on website now.

**Comment by DanielRuf** [comment]
Did you clear all caches?

**Comment by adityag186** [comment]
Hi,

Yes, I cleared all caches. Also, purged everything from cloudfare cdn and supercacher on cpanel. 

Would adding code in miscellaneous html in tab have any affect in standard luma footer? Because, for us the standard footer just disappeared. We have not made any changes to any other code anywhere.

**Comment by ghost** [comment]
Hi @adityag186  I'm not able to reproduce following steps your described, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
