### ISSUE TITLE
Di compile displays success message , if compilation throws an error

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18026]
Install an extension with the compallation issue and then fire “php bin/magento setup:di:compile” command. The process shows an error but at the end of process it shows the success message. 
### Preconditions

1. Magento Version 2.1.14 with sample data
2. PHP 7.0

### Steps to reproduce

1. Install an extension with compilation issue 
2. Login with root user in terminal and switch to Magento root directory 
3. Then fire “php bin/magento setup:di:compile” command 

### Expected result

When Compilation generates an error at that  time success message(Generated code and dependency injection configuration successfully) will not be displayed. 

### Actual result

When Compilation generates an error at that  time success message(Generated code and dependency injection configuration successfully)is also displayed.

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @emiprotech What did you mean -> Install an extension with compilation issue, because i'm have only error message, In my case i write wrong path to plugin in di.xml

**Comment by ghost** [comment]
@engcom-backlog-nazar ,
I meant that if di:compile has an error in any case at that time only errors lines would be displayed in terminal but now in this version if di: compile is not success then error lines and end of the line success message is displayed. where 'Generated code and dependency injection configuration successfully' is the success message of the di: compile. but it is also visible when di:compile has an error.

**Comment by ghost** [comment]
@emiprotech I'm not able to reproduce following steps your described
![selection_075](https://user-images.githubusercontent.com/40756439/45421903-3cbaeb80-b697-11e8-9655-1ba192db8ad8.png)

**Comment by ghost** [comment]
@emiprotech This not be have an error because this message in try catch block
![selection_076](https://user-images.githubusercontent.com/40756439/45422461-ea7aca00-b698-11e8-91fc-d49557a5b8f1.png)

**Comment by ghost** [comment]
ok let's check again from our side and let you know.

**Comment by ghost** [comment]
@emiprotech ok.
