### ISSUE TITLE
Region_ID is mandatory when we select shipping address from India

### ISSUE THREAD

**Issue by deepakkale** [magento/magento2#18024]
We are trying to place order using API. Whenever we pass any address of India as Shipping address, it throws back error "region_id is Mandatory"

### Preconditions

1. Magento 2.2.5
2. Products created.
3. Enable Guest checkout.
4.Create Order as Guest through API.

### Steps to reproduce
1. Create cart through API.
2. Add products through API.
3. Add shipping Address from India. (we tried address of Delhi and Pune)
4. Create Order.

### Expected result

1. It should return Order Id

### Actual result

1. {"message":"Please check the shipping address information. regionId is a required field."}
![image 2](https://user-images.githubusercontent.com/25586343/45403938-7e896900-b67a-11e8-8511-61c1a64c40c4.png)

![magentoaddresserror - copy](https://user-images.githubusercontent.com/25586343/45403875-30746580-b67a-11e8-9154-580d58117e08.jpg)

**Comment by magento-engcom-team** [comment]
Hi @deepakkale. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@deepakkale do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @deepakkale The region id is required field you need to get this id. 
Yo can get it on Database on table directory_country_region

**Comment by deepakkale** [comment]
> Hi @deepakkale The region id is required field you need to get this id.
> Yo can get it on Database on table directory_country_region

How do I get region_ID through API? I'm just using Magento API's and not actual Magento UI. ANd Why it's not mandatory for US and Australia's address and only for India's address?

**Comment by ghost** [comment]
@deepakkale get data from this request -> rest/all/V1/directory/countries

**Comment by ghost** [comment]
@deepakkale As i can understand, recently the region id for india is set as required .
