### ISSUE TITLE
Magento 2.2.1 - Search show no result when looking for a product wich contain a - or /

### ISSUE THREAD

**Issue by alvarogrillet** [magento/magento2#18033]
### Preconditions

1. Magento version 2.2.1

### Steps to reproduce

1. Set a product with a - or / in its name, save and reindex
2. Look for that product name or part of it but with the - in the search query

### Expected result

1. Lsit of the products with similar name or the extac product

### Actual result

1. No products in the search

When i search for part of that product without the - it appears correctly. I have even tried that in search extension vendors demos and same result.

**Comment by magento-engcom-team** [comment]
Hi @alvarogrillet. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@alvarogrillet do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @alvarogrillet thank you for you report, the fix for this issue has already available in 2.2.-develop branch
![selection_084](https://user-images.githubusercontent.com/40756439/45471905-31210080-b73b-11e8-87f2-2a3892d14a7b.png)

**Comment by alvarogrillet** [comment]
Hi @engcom-backlog-nazar

Thanks fo your quick reply.

Im sorry but how can i get that solution for my store?

Thanks and best regards
