### ISSUE TITLE
When i import products with .csv file and is successfull, the sidebar is broken and i cant see all options.

### ISSUE THREAD

**Issue by ilan121** [magento/magento2#18030]
### Preconditions

1.
2.

### Steps to reproduce

1.
2.

### Expected result

1. [Screenshots, logs or description]
2.

### Actual result

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
Hi @ilan121. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ilan121 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @ilan121    I'm not able to reproduce following steps your described, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
