### ISSUE TITLE
Multi store product images via JSON API

### ISSUE THREAD

**Issue by kolonuk** [magento/magento2#18032]
When using JSON to add product images to each store for the same item, images appear in each store multiple times on both the front and back end.

### Preconditions

1. Magento 2.2.5, fresh install
2. Setup integration API
3. Create some categories

### Steps to reproduce

1. Load a product using JSON API
2. Load the image for each store, either `rest/all/V1/products/{{SKU}}/media` or `rest/{{STOREID}}/V1/products/{{SKU}}/media`, setting the `types` field to `"image", "small_image", "thumbnail"`:
```
{
  "entry": { 
      "mediaType": "image",
      "position": 0,
      "disabled": false,
      "types": ["image","small_image","thumbnail"],
      "content":{
        "base64_encoded_data": "ENCODED_IMAGE",
        "type": "IMAGE_MIME",
        "name": "IMAGE_FILENAME"
    }
  }
}
```
3. 

### Expected result

1. On frontend at least, one image per item, and an image in the category view

### Actual result

1. Multiple images in the back end, one for each store, show regardless of store selected
![image](https://user-images.githubusercontent.com/5969835/45412641-15502880-b66f-11e8-9086-c64a2800c489.png)
2. Multiple images in the front end, regardless of store
![image](https://user-images.githubusercontent.com/5969835/45412723-4b8da800-b66f-11e8-913f-0592f34e3878.png)

The images loaded in the screen shots are the same for testing, but may be different in production (user action dependant).

If loading using the `default` store (adding default to the URL or no store at all), adds the image to the default store in the category and item front end, but nothing for the individual stores, hence doing the above.

**Comment by magento-engcom-team** [comment]
Hi @kolonuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kolonuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @kolonuk , thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by kolonuk** [comment]
Just to add, it also looks like the `types` field is only stored against a single image, and the JSON image delete when using the `all` storeid in the url doesn't delete all images - you need to list all the images, and then guess which image relates to which store and issue a delete (also #9136 doesn't help in this case!)

Looks like product images are broken in general...

**Comment by magento-engcom-team** [comment]
Hi @ketan-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
@kolonuk, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Comment by IanPaskin** [comment]
@kolonuk did you find a work around for this at all, i'm facing the same issue now using multiple store views

**Comment by kolonuk** [comment]
Nope, and I don't hold out much hope either.

TBH, my client has sort-of shelved the Magento project.  They have a "working" website for one store only.  I now push WooCommerce whenever I get the chance - so much easier to work with!

**Comment by adgoddrie** [comment]
@magento-engcom-team Please reopen this ticket, it seems trivial but it is a bug which still exists in 2.3.5 and it is more than annoying

**Comment by m4ttw** [comment]
Please reopen this ticket, this has caused my company a lot of issues
