### ISSUE TITLE
Product Customizable Options Value, can't save SKU value

### ISSUE THREAD

**Issue by SvanteAvenla** [magento/magento2#18037]
### Preconditions
1. Magento CE 2.2.3
2. PHP 7.0.30

### Steps to reproduce
1. Create a new Simple product.
2. Add a new *Customizable Option* ('Option Title' => 'Radio', 'Option Type' => 'Select - Radio Buttons').
3. Add two *Option Values* with these values:
    ['title' => 'One', 'Price' => '10', 'Price Type' => 'Fixed', 'SKU' => '#123'],
    ['title' => 'Two', 'Price' => '20', 'Price Type' => 'Fixed', 'SKU' => '#456']
4. Fill the rest of the required information to be able to save the new product.
5. Save the product.
6. Edit the products *Customizable Option*, change the *Option Values* to these values (SKU's are the same):
    ['title' => 'One', 'Price' => '10', 'Price Type' => 'Fixed', 'SKU' => '#123'],
    ['title' => 'Two', 'Price' => '20', 'Price Type' => 'Fixed', 'SKU' => '#123']
7. Save the product.

### Expected result
1. The product should contain a *Customizable Option* with two *Option Values*, both with SKU set to '#123'.

### Actual result

1. The product contains a *Customizable Option* with two *Option Values*, the first with SKU set to '#123' and the second with SKU set to '#456'.

### Additional notes
The SKU value is unset in the function `Magento\Framework\Model\ResourceModel\Db->prepareDataForUpdate($object)`.

**Comment by magento-engcom-team** [comment]
Hi @SvanteAvenla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@SvanteAvenla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by SvanteAvenla** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @SvanteAvenla. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @SvanteAvenla, here is your [Magento instance](https://i-18037-2-2-3.engcom.dev.magento.com).
Admin access: [https://i-18037-2-2-3.engcom.dev.magento.com/admin](https://i-18037-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by SvanteAvenla** [comment]
I was able to reproduce the issues on the vanilla Magento instance you provided me with.

**Comment by ghost** [comment]
Hi @SvanteAvenla The fix for this issue has already available in 2.2-develop branch.

**Comment by ghost** [comment]
![selection_085](https://user-images.githubusercontent.com/40756439/45475082-fe2f3a80-b743-11e8-94d7-0a9771c83402.png)

**Comment by SvanteAvenla** [comment]
Where is the commit fixing this issue? I would like to see how the fix is done?

**Comment by ghost** [comment]
@SvanteAvenla i'm can't find commit or PR , but i'm tested it on 2.2-develop branch and have no issue any more.

**Comment by SvanteAvenla** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @SvanteAvenla. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @SvanteAvenla, here is your [Magento instance](https://i-18037-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-18037-2-2-develop.engcom.dev.magento.com/admin](https://i-18037-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by SvanteAvenla** [comment]
Seems you are right. I can't reproduce the issue in the 2.2-develop either. If you find the commit and remember me please post the commit id here. I'm curious.

Thank you for your time!

**Comment by ghost** [comment]
@SvanteAvenla ok.

**Comment by Ctucker9233** [comment]
@engcom-backlog-nazar I'm interested in seeing the commit as well or at least what version of Magento it's slated for.
