### ISSUE TITLE
Product import - configurable limit of configurable_variations

### ISSUE THREAD

**Issue by ipascual** [magento/magento2#18036]
### Preconditions
1. Create attributes and values before importing

### Steps to reproduce
1. Try to import the attach file (change to .csv)
[configurable.txt](https://github.com/magento/magento2/files/2377743/configurable.txt)

### Expected result
1. Import the configurable product with all variations

### Actual result
1. Error: Invalid option value for attribute: xxx

When I was debugging the code, file magento/module-configurable-import-export/Model/Import/Product/Type/Configurable.php shows that the attribute is breaking into two, it seems the column length was reached. The error is not at all related to the issue, it is because the column length is broken and it reports the name of the attribute is not complete.

**Comment by magento-engcom-team** [comment]
Hi @ipascual. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ipascual do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @ipascual I'm not able to reproduce following steps you described, please try reproduce on vanilla instance.

**Comment by ipascual** [comment]
- Summary of the issue
We have a configurable product with 343 simple product variations. It also have 4 different attributes of dropdown. 

It only imports up to 100 variations.

- Information on your environment
Magento Cloud environment - integration and staging servers

- Steps to reproduce
Upload the CSV attached using System > Import > Products


- Expected and actual results
Magento Admin UI should support this amount of configurable variations. The product should be imported fine.

@magento-engcom-team give me 2.2.5instance

**Comment by ghost** [comment]
Hi @ipascual close this issue as duplicate ti ->https://github.com/magento/magento2/issues/14990 
if you'd like to update this issue please reopen
