### ISSUE TITLE
Product Attribute Values

### ISSUE THREAD

**Issue by Danatran** [magento/magento2#18042]
Hi there,

We are using Magento version 2.2.5. We encounter an issue with duplicate Product Attribute Values:

Backend -> Add new Config product -> Choose attributes -> You can add more values here. At this step, the Magento system has not check if the value is unique, so you can add as many values as you can. The bug came from this way.

**Comment by magento-engcom-team** [comment]
Hi @Danatran. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Danatran do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Danatran I'm not able to reproduce following steps your described, in the step when magento saves config product, automatically adds numbers to values that are unique

**Comment by Danatran** [comment]
Please see the attached about the issue:

![image](https://user-images.githubusercontent.com/43237158/45485105-964b1500-b780-11e8-8848-bd650299b9ca.png)


![image](https://user-images.githubusercontent.com/43237158/45485494-0a39ed00-b782-11e8-8b29-bbbec26a78f2.png)


![image](https://user-images.githubusercontent.com/43237158/45485127-a82cb800-b780-11e8-92ba-7cfc5286d8ea.png)
