### ISSUE TITLE
Products backorder remains In Stock

### ISSUE THREAD

**Issue by magento2dev** [magento/magento2#18040]
### Preconditions

1. Magento 2.2.3
2. Set backorders configuration (Catalog -> Inventory -> Backorders) equal to "Allow Qty Below 0"

### Steps to reproduce

1. Place an order containing a product with qty = 1 and stock status = In Stock

### Expected result

1. The product quantity should be equals to 0
2. The products stock status should be set to Out of Stock

### Actual result

1. Only the product quantity is updated the product stock status remains to In Stock

**Comment by magento-engcom-team** [comment]
Hi @magento2dev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magento2dev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@magento2dev, thank you for your report.
This is an expected behavior.
