### ISSUE TITLE
Text swatch translation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18041]
### Preconditions
1. Magento CE 2.2.5

### Steps to reproduce
1. Create multiple store views
2. Add text swatch attribute
3. Add different values for the label/description pairs of the admin scope and the store views.
4. Create configurable product with given attribute

### Expected result
1. Swatches for configurable product are rendered with the translated label

### Actual result
1. Swatches for configurable product are rendered with the label of the admin scope

**Comment by magento-engcom-team** [comment]
Hi @Culth. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Culth do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Culth this is duplicate for this ->https://github.com/magento/magento2/issues/17890

**Comment by ghost** [comment]
Ah thanks, couldn't find it. Have a nice day.

**Comment by ghost** [comment]
@Culth you too.
