### ISSUE TITLE
Static content deployment breaking template files in vendor

### ISSUE THREAD

**Issue by kamilszewczyk** [magento/magento2#18048]
### Preconditions

1. Magento 2.2.5

### Steps to reproduce

1. A module installed in vendor with a template file with a content
`<script src="//test.js/<?php echo $block->getParam() ?>/<?php echo $block->getParam() ?>"></script><script>runFunction(1, 2);</script>`
2. Run setup:static-content:deploy command
3. Check content of the phtml file

### Expected result

1. A correct phtml file (not modified)

### Actual result

1. Modified and broken phtml file

Changing the `<?php` echo syntax to `<?=` fixes the issue but I don't think it's a desired behaviour?

**Comment by magento-engcom-team** [comment]
Hi @kamilszewczyk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kamilszewczyk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by hostep** [comment]
@kamilszewczyk : I assume it only happens when html minification is enabled?
It sounds a bit like https://github.com/magento/magento2/issues/5316 (which should get fixed in 2.2.6), since you also have something which looks a bit like a comment: `//test.js` (I assume this is just a placeholder for an actual domain name?). Does changing that to `https://test.js` fixes the issue as well?

**Comment by kamilszewczyk** [comment]
@hostep 
the HTML minification is actually disabled.
The `//test.js` is a placeholder for the domain name to include with same protocol as the current site.
Changing to `https://test.js` seems to fix the issue, but so is changing to `<?=` in the php opening tags.

It does seem very similar to the #5316 I will keep an eye on this issue in 2.2.6

**Comment by ghost** [comment]
Hi @kamilszewczyk  I'm not able to reproduce following steps you described. see attachments
![selection_090](https://user-images.githubusercontent.com/40756439/45538222-1a4bde00-b80f-11e8-8e4d-0ad9acf6667f.png)
![selection_089](https://user-images.githubusercontent.com/40756439/45538223-1a4bde00-b80f-11e8-9e93-933c3743fe16.png)

**Comment by ghost** [comment]
@kamilszewczyk  if you like to update the issue please reopen.

**Comment by kamilszewczyk** [comment]
Hello @engcom-backlog-nazar 

I have just noticed the same issue occured on other 3rd party module and it was reported here https://github.com/YotpoLtd/magento2-plugin/issues/18
It seems that the PHP version is also a variable. 
I've been testing my code on `PHP 7.1.20-1+ubuntu18.04.1+deb.sury.org+1` can you please check reproducing of this error on it?

**Comment by ghost** [comment]
Hi @kamilszewczyk thank you for you reply, yes i'm will testing this again, but if i'm good remember,  I tested with the 7.1.20 php version

**Comment by kamilszewczyk** [comment]
Well at least thanks to the yotpo module bug report I know that it's not a isolated case that happened only for me, but is actually encountered by other people

**Comment by ghost** [comment]
Hi @kamilszewczyk I'm not able to reproduce this on clean instance, seems like this issue related only to custom module. Can we close issue ? and in future if someone found this we can reopen.

**Comment by ghost** [comment]
@kamilszewczyk  I'm closing this issue, If someone have the same issue, so in future we can reopen this. 
Thank you.
