### ISSUE TITLE
Fresh 2.2.5 installation - menu is not operational

### ISSUE THREAD

**Issue by magolovanov** [magento/magento2#18054]
### Preconditions

1. Install fresh 2.2.5

### Steps to reproduce
1. Navigate to http://magento2.catalog-on-demand.com/admin_XXX and log in

### Expected result
1. A screen where "Content", "System" etc links navigate to relevant UI sections

### Actual result
 All menu links ( "Content", "System" etc) are identical and navigate to the dashboard itself - like

http://magento2.catalog-on-demand.com/admin_b85qz8/admin/dashboard/index/key/420da14ca6272274e957b6c4836e6293d213534717c301e78550c9ff471186e9/

Only "admin" link navigates to "My Accont" screen but when this screen gets loaded, all menu links become

http://magento2.catalog-on-demand.com/admin_b85qz8/admin/system_account/index/key/377afdaf104caef93632bc68276f7ce47355798f2e6770e6fecbea3d6f0abb0b/

**Comment by magento-engcom-team** [comment]
Hi @magolovanov. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magolovanov do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @magolovanov I'm not able to reproduce following steps your described
![selection_092](https://user-images.githubusercontent.com/40756439/45546440-f3e56d00-b825-11e8-8a3a-7c187c0debdb.png)

**Comment by magolovanov** [comment]
Fixed this following http://www.dckap.com/blog/magento-2-admin-links-not-working-in-windows/

Other workarounds like https://stackoverflow.com/questions/34555776/magento-2-0-admin-menu-not-working did not work.

Probably there should be done something so that people do not struggle
