### ISSUE TITLE
Zero weight prevents checkout from working even on downloadable product

### ISSUE THREAD

**Issue by DerekBoothSEO** [magento/magento2#18051]
### Preconditions

1. Ver 2.2.5

### Steps to reproduce
1. When adding a downloadable product and selecting 'no weight' the checkout fails.
2. It also the same result on any other product type, no weight is a checkout fail.

### Expected result
1. a downloadable product will never have any weight, I expect the purchase to go through
2.

### Actual result
1. 
![order-error-no-weight](https://user-images.githubusercontent.com/42970190/45519815-b691c880-b7ae-11e8-9942-51465f1dffbf.PNG)

2.

**Comment by magento-engcom-team** [comment]
Hi @DerekBoothSEO. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DerekBoothSEO do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DerekBoothSEO** [comment]
If you select 'no weight' it fails
If you select 'it has weight' but dont enter a weight it fails
if you select 'it has weight' but put a '0' it works

**Comment by ghost** [comment]
@DerekBoothSEO, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. It's obvious your problem is caused by custom code.
