### ISSUE TITLE
REST Api SearchCriteria encoding error with %25 'like' requests

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18050]
**Summary of the issue**
When searching "like" results into products repository through REST API, values starting with % or %25 followed by some characters (e.g. "e" or "a") will give bad results, not as expected and described at "Logical OR search" section here: https://devdocs.magento.com/guides/v2.2/rest/performing-searches.html

### Preconditions
Environment: LAMP (Apache 2.4.6, php 7.1.0)
Magento version: 2.2.5
Blank installation with 1 admin user, 1 Category and 1 Product (e.g. named "Educational")

### Steps to reproduce
1. Call REST API to obtain admin token:
POST GET _YOUR_BASE_URL_ /rest/V1/integration/admin/token
Parameters: username, password

2. Call REST API to obtain products with the desired search criteria as follows:
GET _YOUR_BASE_URL_ /rest/V1/products
?searchCriteria[filter_groups][0][filters][0][field]=name
&searchCriteria[filter_groups][0][filters][0][value]=%edu%
&searchCriteria[filter_groups][0][filters][0][condition_type]=like

OR

GET _YOUR_BASE_URL_ /rest/V1/products
?searchCriteria[filter_groups][0][filters][0][field]=name
&searchCriteria[filter_groups][0][filters][0][value]=%25edu%25
&searchCriteria[filter_groups][0][filters][0][condition_type]=like

Where "edu" is the desired string.
It's the same with any "e" string + anything else, like "extreme" or "environment".
It seems to happen with many other characters (e.g. "%a" char combination)

### Expected result
1. Would expect % to be accepted or %25 to be encoded to % (as per https://devdocs.magento.com/guides/v2.2/rest/performing-searches.html, "Logical OR" section).
2. Would expect to receive correct results with _like_ search before and after the "edu" string.

### Actual result
1. It seems that the combination of "e" character after % and even after %25 is not encoded / decoded correctly.
2. In case you put %e it will return filter_group > filters > value as "?u%", no items.
3. In case you put %25e it will return a 200 OK response without any object, no items.

See attachments.

![screen1](https://user-images.githubusercontent.com/5660613/45518767-ed69dd80-b7b2-11e8-8dcb-bb161f1d2e1f.png)
![screen2](https://user-images.githubusercontent.com/5660613/45518769-ef33a100-b7b2-11e8-9d01-d86ae71c541c.png)

**Comment by magento-engcom-team** [comment]
Hi @LucaTerzaghi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LucaTerzaghi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @LucaTerzaghi. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @LucaTerzaghi, here is your [Magento instance](https://i-18050-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18050-2-2-5.engcom.dev.magento.com/admin](https://i-18050-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I confirm the issue has been reproduced on vanilla Magento instance.
1) Logged in as admin
2) Added a Category with a Product named "Educational"
3) Tried to call the REST APIs as described with admin token.

The issue has been reproduced. Please try by yourself:

REST API that works (with Edu% value)
https://i-18050-2-2-5.engcom.dev.magento.com/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=name&searchCriteria[filter_groups][0][filters][0][value]=Edu%&searchCriteria[filter_groups][0][filters][0][condition_type]=like

REST API that break (with %Edu% or %25edu%25 values)
https://i-18050-2-2-5.engcom.dev.magento.com/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=name&searchCriteria[filter_groups][0][filters][0][value]=%Edu%&searchCriteria[filter_groups][0][filters][0][condition_type]=like

https://i-18050-2-2-5.engcom.dev.magento.com/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=name&searchCriteria[filter_groups][0][filters][0][value]=%25Edu%25&searchCriteria[filter_groups][0][filters][0][condition_type]=like

**Comment by ghost** [comment]
> Hi @LucaTerzaghi. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me {$VERSION} instance`
> 
> where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @LucaTerzaghi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [X]  yes
> * [ ]  no

**Comment by ghost** [comment]
**WORKING**
![schermata 2018-09-14 alle 00 29 26](https://user-images.githubusercontent.com/5660613/45519439-56eaeb80-b7b5-11e8-9e56-2a5dc978786a.png)

**NOT WORKING**
![schermata 2018-09-14 alle 00 29 34](https://user-images.githubusercontent.com/5660613/45519441-5baf9f80-b7b5-11e8-9115-b68d376c7537.png)

![schermata 2018-09-14 alle 00 29 44](https://user-images.githubusercontent.com/5660613/45519443-5d796300-b7b5-11e8-8ece-d5b295eb716c.png)

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please label this ticket with `"acknowledged"` again.
Thanks!

**Comment by ghost** [comment]
Hi @LucaTerzaghi please add precondition steps and  Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-94999` were created

**Comment by ghost** [comment]
@LucaTerzaghi , thank you for your report. The fix for this issue already available in 2.3-develop branch
We've acknowledge the issue and added to our backlog.

**Comment by ghost** [comment]
@engcom-backlog-nazar Hi ~ how about for 2.2.5 ?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @LucaTerzaghi The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.

**Comment by bhupendravgroup** [comment]
What is the fix for this issue as I am still getting it in 2.3
