### ISSUE TITLE
Magento 2.2.5 - If Multi-Storefront, Shipping Rates on an Admin Order use rates from the default store

### ISSUE THREAD

**Issue by callumstar** [magento/magento2#18059]
### Preconditions
1. Magento 2.2.5
2. PHP 7
3. Multistore installation
4. Websites with a shipping method enabled with different rates

### Steps to reproduce
1. Create multistore version of Magento 2.2.5
2. Set up a single shipping method with different shipping fees for both websites in 'Stores > Configuration > Sales > Shipping Methods' (e.g. Flat Fee of £10.00 for default and Flat Fee of £15.00 for second storefront)
3. Attempt to create a new order in the admin area and use the second storefront
4. Click on the button 'Get shipping methods and rates'

### Expected result
1. Shipping Rate should appear with the cost of £15.00

### Actual result
1. Shipping Rate appears with the cost of £10.00 (as defined in the default store)

**Comment by magento-engcom-team** [comment]
Hi @callumstar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@callumstar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by callumstar** [comment]
Hi @magento-engcom-team,

Yes I can reproduce this with any shipping rate on any vanilla instance of Magento 2.2.5.

**Comment by callumstar** [comment]
Hi @magento-engcom-team,

I believe that this is linked to the following issue:
- #12889 (incorrectly closed)
- #15497
- #16604

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `G3 Passed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @callumstar I'm not able to reproduce following steps you described, see attachments
![selection_095](https://user-images.githubusercontent.com/40756439/45555390-59932280-b841-11e8-89e2-5b371665d2ec.png)
![selection_094](https://user-images.githubusercontent.com/40756439/45555392-59932280-b841-11e8-8e50-f4569aa54c99.png)

**Comment by ghost** [comment]
@callumstar if you like to update reopen this issue .

**Comment by callumstar** [comment]
Hi @engcom-backlog-nazar,

Can you please perform the same test with the Table Rates too? This is another shipping method we are seeing issues with.

**Comment by ghost** [comment]
@callumstar ok i'm try with table rates

**Comment by callumstar** [comment]
Hi @engcom-backlog-nazar,

Is there any update on this please?

**Comment by ghost** [comment]
Hi @callumstar, Yes the issue persist to table rates only.

**Comment by callumstar** [comment]
Hi @engcom-backlog-nazar,

So this is a confirmed issue with Table Rates? Is there a workaround for this?

**Comment by ghost** [comment]
@callumstar seems like no.

**Comment by ghost** [comment]
@callumstar ->https://github.com/magento/magento2/issues/16604

**Comment by callumstar** [comment]
Hi @engcom-backlog-nazar,

There isn't really a workaround/fix in that task. Is there a timeframe for fixing this bug?

What do we do in the meantime for this as it is quite a key component for most merchants with different shipping rates based on matrixes?

**Comment by ghost** [comment]
@callumstar  Wait for maintainers to fix this issue, as possibly soon.

**Comment by Rickertje** [comment]
@engcom-backlog-nazar why is this issue not reopened? I dont think maintainers will pick up this issue now.
