### ISSUE TITLE
how to use require_once in magento2

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1806]

**Comment by sivaschenko** [comment]
@LifeAsBook, could you describe the specific case where you'd like to use this function?

**Comment by LifeAsBook** [comment]
@sivaschenko, thank you! i want to include the 3rd provided function  that in a file.
2)another question may i  to use $_GET and $_POST ?

**Comment by sivaschenko** [comment]
@LifeAsBook I would recomend you to include required function within a class and get use of Magento autoload. As for $_GET and $_POST: it's better to use \Magento\Framework\App\RequestInterface::getParam instead

**Comment by LifeAsBook** [comment]
thank you!

**Comment by magento-engcom-team** [comment]
Hi @LifeAsBook. Thank you for your report. 
The issue has been fixed in magento/magento2#29979 by @engcom-Golf in 2.4-develop branch
Related commit(s):
 - [22da500519287b49c984ed615b66d0edd6f55bb0](https://github.com/magento/magento2/commit/22da500519287b49c984ed615b66d0edd6f55bb0)
 - [b5180c00976cafeee03a1ba55833c9ae871c6194](https://github.com/magento/magento2/commit/b5180c00976cafeee03a1ba55833c9ae871c6194)
 - [7cfbc3079550df1336ce5a090a3a54b0ca91dd70](https://github.com/magento/magento2/commit/7cfbc3079550df1336ce5a090a3a54b0ca91dd70)
 - [9a6bd96ac0a0d71a1a8a597cbbd031fc3c420bc8](https://github.com/magento/magento2/commit/9a6bd96ac0a0d71a1a8a597cbbd031fc3c420bc8)
 - [9d0252a47858a2c268181a2e77606a5a6bcdc6cb](https://github.com/magento/magento2/commit/9d0252a47858a2c268181a2e77606a5a6bcdc6cb)
 - [e832db8c0de8e554f3d4da7d42dbeab89483d5b9](https://github.com/magento/magento2/commit/e832db8c0de8e554f3d4da7d42dbeab89483d5b9)
 - [1db2872bb5999085f4e72474c8f9339fa468fb7d](https://github.com/magento/magento2/commit/1db2872bb5999085f4e72474c8f9339fa468fb7d)
 - [837dd9d228eaad4ee06f00f0383c03e6d2aebd6f](https://github.com/magento/magento2/commit/837dd9d228eaad4ee06f00f0383c03e6d2aebd6f)
 - [79ddf27679e697c2e1a79ade6ea96cfcd5312948](https://github.com/magento/magento2/commit/79ddf27679e697c2e1a79ade6ea96cfcd5312948)
 - [1535626df1c487201ded3eeab88d5e9e2f8e4161](https://github.com/magento/magento2/commit/1535626df1c487201ded3eeab88d5e9e2f8e4161)
 - [cbc38f64f28829ec4a0b9b86b0c9959ab0ddcdfd](https://github.com/magento/magento2/commit/cbc38f64f28829ec4a0b9b86b0c9959ab0ddcdfd)
 - [0cafa206549c4cfe9aff495f2566b3213273a196](https://github.com/magento/magento2/commit/0cafa206549c4cfe9aff495f2566b3213273a196)
 - [ccd7251f4ff7d59c3c16a9381071e587acc39e1a](https://github.com/magento/magento2/commit/ccd7251f4ff7d59c3c16a9381071e587acc39e1a)
 - [35642f7b3af5eadf3c05d47ee19412f547233ee4](https://github.com/magento/magento2/commit/35642f7b3af5eadf3c05d47ee19412f547233ee4)
 - [f6f5a5ecb7e07186037c7dc081393f9a2223d1c8](https://github.com/magento/magento2/commit/f6f5a5ecb7e07186037c7dc081393f9a2223d1c8)

The fix will be available with the upcoming 2.4.2 release.
