### ISSUE TITLE
Magento Web Installer doesn't show completeness

### ISSUE THREAD

**Issue by riconeitzel** [magento/magento2#18073]
### Preconditions
1. Download 2.2.5 ZIP Archive
2. Apache 2.2.34, fastCGI PHP 7.1.19

### Steps to reproduce
1. Run web installer (configure doc root to be magento root
2. keep all modules enabled
3. tail -f var/log/*

### Expected result
magento web installer runs 100% and shows success page.

### Actual result
1. log view shows `<span class="hidden">[Progress: 473 / 473]</span><br><span class="text-success">[SUCCESS] Magento installation complete.</span><br><span class="text-success">[SUCCESS] Magento Admin URI: /admin</span>`
2. web installer stuck at 73%

**Comment by magento-engcom-team** [comment]
Hi @riconeitzel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@riconeitzel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by denisflosi1** [comment]
#webjump

**Comment by magento-engcom-team** [comment]
@denisflosi1 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @denisflosi1. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by denisflosi1** [comment]
Hi @riconeitzel.
Please, check this troubleshoot doc:
[Setup Wizard installation stops at about 70%](https://devdocs.magento.com/guides/v2.2/install-gde/trouble/php/tshoot_70pct.html) and let me know if your problem has been solved.

**Comment by riconeitzel** [comment]
@denisflosi the described issues in this ticket are different.

**Comment by riconeitzel** [comment]
No errors anywhere! Installation was successful. Just the web page didn’t proceed.

**Comment by denisflosi1** [comment]
Hi @riconeitzel , this is some environment issue. You can have support to install this Magento version in apache, at the community forum, maybe someone have already faced this issue:
https://community.magento.com/

**Comment by riconeitzel** [comment]
I encountered this issue in various environments. How do you know it’s not a core issue?! 🤔

**Comment by okorshenko** [comment]
Hi @riconeitzel! Thank you for your report. 
Could you please try to reproduce the issue on latest 2.3-develop and 2.2-develop branches to confirm that the issue is still reproducible. 
If the behavior is not stable and we can't reproduce the issue, we won't be able to send this ticket for development. 
Thank you

**Comment by riconeitzel** [comment]
Hi, sure! gimme some good 24hrs and I'll come back with it :-)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @riconeitzel I'm not able to reproduce following steps you described. can you provide more information?
![selection_097](https://user-images.githubusercontent.com/40756439/45614143-32229c80-ba71-11e8-9217-854b15a4ede4.png)
![selection_096](https://user-images.githubusercontent.com/40756439/45614145-32bb3300-ba71-11e8-849e-9f9498eb90fb.png)

**Comment by riconeitzel** [comment]
Hi there!

which apache, php and magento version did you use?

rico

**Comment by ghost** [comment]
@riconeitzel Apache/2.4.18, fastCGI PHP 7.1.20  But this not be related to the issue ? 
or specific version of apache can do the error ?

**Comment by ghost** [comment]
@riconeitzel i'm able to reproduce in 2.2.5 with fasctCGI i'm missed config for virtual host
![selection_099](https://user-images.githubusercontent.com/40756439/45616241-8597e900-ba77-11e8-8895-8b3672f73086.png)
![selection_098](https://user-images.githubusercontent.com/40756439/45616243-8597e900-ba77-11e8-97f7-95d46639c8a9.png)

**Comment by ghost** [comment]
Hi @riconeitzel thank you for you report,  the fix for this issue has already available in 2.3-develop branch, And i can't find commit or PR where this was fixed.

**Comment by denisflosi1** [comment]
@magento-engcom-team give me 2.3.5-p1 instance
