### ISSUE TITLE
i try to install magento 2.2.5 in cpannel , after uploading the extaracted files to my public folder it is showing this error. i cannot proceed further - MAGENTO 2.2.5 ERROR  , public_html/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration

### ISSUE THREAD

**Issue by arifthiruvalla** [magento/magento2#18074]
### Preconditions

1.
2.

### Steps to reproduce

1.
2.

### Expected result

1. [Screenshots, logs or description]
2.

### Actual result

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
Hi @arifthiruvalla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@arifthiruvalla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by marcelo-monteiro** [comment]
#webjump

**Comment by magento-engcom-team** [comment]
@marcelo-monteiro thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by marcelo-monteiro** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro, here is your [Magento instance](https://i-18074-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18074-2-3-develop.engcom.dev.magento.com/admin](https://i-18074-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by arifthiruvalla** [comment]
![capture](https://user-images.githubusercontent.com/13810292/45596719-41eaa400-b9d1-11e8-81d0-ab5f92856f8c.JPG)

**Comment by arifthiruvalla** [comment]
please help me someone

**Comment by marcelo-monteiro** [comment]
@arifthiruvalla, could you please fulfill the steps to reproduce this error?

**Comment by marcelo-monteiro** [comment]
@arifthiruvalla, this is not a bug, this an environment issue.  You can have support to install this magento version in apache, at slack channel (faster communication): 
sign-up: tinyurl.com/engcom-signup
https://magentocommeng.slack.com/messages/C4YS78WE6
Or check in the forum, maybe someone already faced this issue, also you can ask for help there:
https://community.magento.com/
