### ISSUE TITLE
Issue with REST API Customer Create API & Customer Token Integration API

### ISSUE THREAD

**Issue by jyoti217** [magento/magento2#18088]
Issue is regarding REST API as per swagger documentation.

- **Customer Create API** - Create a customer with store_id = 0, you get error_code 400 and message below. This is fine but inspite of the error customer is created in the database. You can check it in admin panel. 
{
  "message": "Design config must have area and store."
}

- **Customer Token Integration API**  - Customers that created with store_id are only able to get token.

### Preconditions

1. I have tried this clean installation of Magento 2.2.5 and Magento 2.1.14
2. PHP 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce

1. Start with a clean installation of Magento 2.2.5
2. Create a customer(cust1) with customerAccountManagementV1 API with store_id = 0. You will get HTTP 400 Msg - Design config must have area and store.
3. Login to admin panel check customers you will see the customer gets created inspite of error.
4. Create another customer(cust2) with store_id 1.
5. Try to get Customer Bearer Token with API integrationCustomerTokenServiceV1 you will only be able to get token for cust1 and for cust2 you will get error msg : You did not sign in correctly or your account is temporarily disabled.

### Expected result

1. Expected result should be that no customer should be created with store_id = 0
2. Customers with store_id 1 should be able to get access token.

### Actual result

1. Customer is created  with store_id = 0
2. Customers with store_id 1 is not  able to get access token.

**Comment by magento-engcom-team** [comment]
Hi @jyoti217. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jyoti217 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jyoti217** [comment]
> Hi @jyoti217. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @jyoti217 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no

yes

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95053`, `MAGETWO-95054` were created

**Comment by ghost** [comment]
Hi @jyoti217 , thank you for your report.
We've acknowledge the issue and added to our backlog. 
In my case i'm reproduce only 1 scenario in 2.2-develop, 2.3-develop -> Customer is created with store_id = 0
but i'm able to get token -> Customers with store_id 1 is not able to get access token.

**Comment by jyoti217** [comment]
> Hi @jyoti217 , thank you for your report.
> We've acknowledge the issue and added to our backlog.
> In my case i'm reproduce only 1 scenario in 2.2-develop, 2.3-develop -> Customer is created with store_id = 0
> but i'm able to get token -> Customers with store_id 1 is not able to get access token.

@engcom-backlog-nazar I have tried this with multiple clean installations of Magento 2.2.5 but I am not able to get access token. Is there a step that I am missing or some wrong input parameter.  
Adding below bold lines to vendor/magento/module-customer/Model/CustomerRegistry.php only then I am able to get token. For customers this->storeManager->getStore()->getWebsiteId(); always returns 0.
Do I need to set store_id for customers somewhere.
 public function retrieveByEmail($customerEmail, $websiteId = null)
    {
        if ($websiteId === null) {
            $websiteId = $this->storeManager->getStore()->getWebsiteId();
			**if($websiteId<1){
				$websiteId=1;
			}**
        }
        $emailKey = $this->getEmailKey($customerEmail, $websiteId);
        if (isset($this->customerRegistryByEmail[$emailKey])) {
            return $this->customerRegistryByEmail[$emailKey];
        }

        /** @var Customer $customer */
        $customer = $this->customerFactory->create();

        if (isset($websiteId)) {
            $customer->setWebsiteId($websiteId);
        }

        $customer->loadByEmail($customerEmail);
        if (!$customer->getEmail()) {
            // customer does not exist
            throw new NoSuchEntityException(
                __(
                    'No such entity with %fieldName = %fieldValue, %field2Name = %field2Value',
                    [
                        'fieldName' => 'email',
                        'fieldValue' => $customerEmail,
                        'field2Name' => 'websiteId',
                        'field2Value' => $websiteId
                    ]
                )
            );
        } else {
            $this->customerRegistryById[$customer->getId()] = $customer;
            $this->customerRegistryByEmail[$emailKey] = $customer;
            return $customer;
        }
    }

**Comment by ghost** [comment]
@jyoti217 on 2.2.5
![postman](https://user-images.githubusercontent.com/40756439/45610001-04365b80-ba63-11e8-9dbd-434a5dfa60da.gif)

**Comment by jyoti-redlizard** [comment]
> 
> 
> @jyoti217 on 2.2.5
> ![postman](https://user-images.githubusercontent.com/40756439/45610001-04365b80-ba63-11e8-9dbd-434a5dfa60da.gif)

Hi @engcom-backlog-nazar   In the video 

1. You created a customer with email_id = user13@gmail.com and store_id =0  here you get an error 400 but in background customer is created with this email and store_id = 0
2. You have created another customer but with same email_id = user13@gmail.com only store_id = 1 so now we have 2 customers in with same email_id but different store_id. 
3. Now when you try to login with the email_id = user13@gmail.com you login into store_id 0. Which I have also faced many times.

So could you please try with different email_ids for both customers and share that video.
Thank you.

**Comment by ghost** [comment]
@jyoti217  with different email_ids same result
![postman2](https://user-images.githubusercontent.com/40756439/45610808-ecaca200-ba65-11e8-8e4e-361cd62fc673.gif)

**Comment by jyoti217** [comment]
> @jyoti217 with different email_ids same result
> ![postman2](https://user-images.githubusercontent.com/40756439/45610808-ecaca200-ba65-11e8-8e4e-361cd62fc673.gif)

@engcom-backlog-nazar  
I found the issue that I was having it was because I was trying to get the customer token in swagger 
where the curl url is **http://localhost.magento/rest/all/V1/integration/customer/token** 
When I removed **/all** it worked fine. Also in the video shared by you the url does not contain **/all**. 
In the Swagger documentation there should be some way to remove this **/all** while making requests for customer token and it needs to documented in more detail.

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by SunilKrishnan** [comment]
I tested this Fix on 2.2.7 and its is not working.

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](https://i-18088-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-18088-2-3-develop.instances.magento-community.engineering/admin](https://i-18088-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hiren0241** [comment]
Hi @engcom-backlog-nazar,

This issue has been already fixed in 2.3 version. But, when you pass store id = 0, you will get store id = 1 in json response. So, customer get access token. 

We can close this issue as it is fixed already.

**Comment by manishmittalm** [comment]
@magento Please confirm if this issue still need to fix. As I can see flag is ready for dev.

**Comment by engcom-Golf** [comment]
Hi @jyoti217,
I will close this issue as it has been already fixed on 2.3 in https://github.com/magento/magento2/commit/63d33c5081068ca8253e52763fb8ab7d5ffe8a1a
Thank you for your report

**Comment by magento-engcom-team** [comment]
Hi @jyoti217, @engcom-Golf. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24550` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
