### ISSUE TITLE
Paypal NVP CURL connection error

### ISSUE THREAD

**Issue by samuelecarpene** [magento/magento2#18089]
Paypal not working.

### Preconditions
1. Magento 2.2.5
2. Ubuntu 18.04
3. Php 7.1

### Steps to reproduce
1. Insert a product in cart
2. Go to checkout
3. Select paypal express checkout method a payment
4. Try to pay

### Expected result
1. I expect to be redirected to paypal payment page

### Actual result
1. Error message shown in the checkout page "Payment Gateway is unreachable at the moment. Please use another payment option."
2. Error logged in exception.log -> [2018-09-17 08:58:54] main.CRITICAL: PayPal NVP CURL connection error #7: Failed to connect to 127.0.0.1 port 808: Connection refused {"exception":"[object] (Exception(code: 0): PayPal NVP CURL connection error #7: Failed to connect to 127.0.0.1 port 808: Connection refused at /var/www/[site_folder]/releases/12/vendor/magento/module-paypal/Model/Api/Nvp.php:1214)"} []

**Comment by magento-engcom-team** [comment]
Hi @samuelecarpene. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@samuelecarpene do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @samuelecarpene  I'm not able to reproduce following steps your described, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by paras89** [comment]
@samuelecarpene Did you find a solution for this issue? We are facing the same issue on Magento 2.2.4

**Comment by aymansabi** [comment]
Having the same problem. Any solution. 

 Failed to connect to 127.0.0.1 port 808: Connection refused at /home/luckyeyesinc/public_html/vendor/magento/module-paypal/Model/Api/Nvp.php:1215)"} []

**Comment by fruit-ninja** [comment]
> Having the same problem. Any solution.
> 
> Failed to connect to 127.0.0.1 port 808: Connection refused at /home/luckyeyesinc/public_html/vendor/magento/module-paypal/Model/Api/Nvp.php:1215)"} []

Hey @aymansabi were you able to resolve this issue?

**Comment by pixiemediaweb** [comment]
I've just had this issue with 2.3.6- turned out CURL needed an update on the server.   You can test by logging into the server as root and running;

curl -v -s https://api-3t.sandbox.paypal.com/nvp

If this fails, update curl

yum update curl  (if you're in a centos environment)

Hope this helps someone.
