### ISSUE TITLE
Fatal Error when save configurable product in Magento 2.2.5

### ISSUE THREAD

**Issue by vpatidar009** [magento/magento2#18082]
### Preconditions
PHP 7.1
MYSQL 5.6
Magento 2.2.5

### Steps to reproduce
1. Add new configurable product with name and sku of 63 characters length For Example: "Amzer 203877 Kristal FULL HD Tempered Glass for OnePlus 6 Clear". **Screenshot**: https://drive.google.com/file/d/1YQGb1h2J3oAfy6ihkCeZ7-Elbk6EYMaP/view?usp=drivesdk
2. Create configuration of the product. **Screenshot**: https://drive.google.com/file/d/1EPspkolJGVhmSavKphDlIjOLT3k-QijU/view?usp=drivesdk
3. Now, When you try to save it's configuration, It shows client side validation error for child products SKUs. Decrease length of child product's SKUs and then save the product. It generates a error report as attached. **Screenshot**: https://drive.google.com/file/d/1VTuD3gE2NVa3H1ndfi8xus7fGx2xUpDJ/view?usp=drivesdk

### Expected result
1. Save products without any error with SKU length less then or equal to 64

### Actual result

1.Getting major error when save such product. even after decrease lenght of SKU to valid client side validation. 

[report.zip](https://github.com/magento/magento2/files/2386900/report.zip)

**Comment by magento-engcom-team** [comment]
Hi @vpatidar009. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vpatidar009 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @vpatidar009 I'm not able to reproduce following steps you described, I'm not have an error report generated.

**Comment by vpatidar009** [comment]
Hi @engcom-backlog-nazar ,
It is not possible as I have tested 2-3 instances of magento 2.2.5 version and all versions are vanilla magento.

I am pretty sure about the error and I can reproduce the issue at your environment if you can give me access of the environment.

**Comment by engcom-backlog-nazar** [comment]
@vpatidar009 Where located your report? because i'm not have  report files.

**Comment by vpatidar009** [comment]
@engcom-backlog-nazar https://github.com/magento/magento2/files/2386900/report.zip

I have also added screenshots URL in my initial message. Hope those screenshots will help you.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please label this ticket with `"acknowledged"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95055` were created

**Comment by ghost** [comment]
@vpatidar009 , thank you for your report.
We've acknowledge the issue and added to our backlog.

**Comment by vpatidar009** [comment]
@magento-engcom-team @engcom-backlog-nazar  We can also force sku length in the file "vendor\magento\module-configurable-product\view\adminhtml\web\js\variations\steps\summary.js" by 64 or less characters

**Comment by magento-engcom-team** [comment]
Hi @thiagolima-bm. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by sidolov** [comment]
Hi @vpatidar009. Thank you for your report. 
The issue has been fixed in magento/magento2#18462 by @thiagolima-bm in 2.3-develop branch
Related commit(s):
 - [cc16df90455a510083f4d4bebda27566c23e221e](https://github.com/magento/magento2/commit/cc16df90455a510083f4d4bebda27566c23e221e)
 - [77111659b520ebad13b53389f67144fddd5dfad6](https://github.com/magento/magento2/commit/77111659b520ebad13b53389f67144fddd5dfad6)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @vpatidar009. Thank you for your report. 
The issue has been fixed in magento/magento2#18461 by @thiagolima-bm in 2.2-develop branch
Related commit(s):
 - [03698da2ebc0cdb02ec1a0c4e65eb00097c61d42](https://github.com/magento/magento2/commit/03698da2ebc0cdb02ec1a0c4e65eb00097c61d42)
 - [38854b5fe8775a3b7a945ee8882a3661e10662b4](https://github.com/magento/magento2/commit/38854b5fe8775a3b7a945ee8882a3661e10662b4)

The fix will be available with the upcoming 2.2.8 release.
