### ISSUE TITLE
Catalog New Products List widget not sorting according to 'created_at'

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#18090]
The Catalog New Products List widget in Magneto 2 does not appear to be sorting products by their created date. Instead it seems to be selecting products according to the updated date, but no sorting them as such. The function _getRecentlyAddedProductsCollection() in file vendor/magento/module-catalog/Block/Product/Widget/NewWidget.php should sort by 'created_at', 'desc', but does not do so.

### Preconditions

1. Magento 2.2.1
2. Product catalog with a range of 'created_at' and 'update_at' values.
3. New product widget set to all products.

### Steps to reproduce

1. Add new product widget to page.
2. Check sort order of products against 'created_at' values in database.

### Expected result

1. Products should be sorted by ->addAttributeToSort('created_at', 'desc').

### Actual result

1. Products appear to be being selected according to 'update_at' and are not sorted by either attribute.

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BezV8 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @BezV8 thank you for you report, the fix for this issue has already available in 2.3-develop branch

**Comment by BezV8** [comment]
@engcom-backlog-nazar Thanks for the quick response, sorry I missed the previous ticket. Would you be able to tell me what file was modified for the fix? The issue is effecting one of our clients and I could make a module to temporarily fix until the new patch.

**Comment by ghost** [comment]
Hi @BezV8 No, i'm searching but cant find commit. But works perfectly on 2.*-dev branches
