### ISSUE TITLE
Orders and Returns status: You entered incorrect data. Please try again."

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#18093]
Issue with Orders and Returns.

### Preconditions

1. Magento 2.2.5
2. PHP 7.1

### Steps to reproduce

1. Check "orders and returns" information without login to customer account using website page `/sales/guest/form/`
2. Add ORDER INFORMATION details: Order ID, Billing Last Name, Find Order By: Email or ZIP Code
3. Click continue and always same error text: `You entered incorrect data. Please try again.`

### Expected result

1. It should be show order information for orders and returns.

### Actual result

1. Error: `You entered incorrect data. Please try again.`

**Comment by magento-engcom-team** [comment]
Hi @Userr017. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Userr017 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @Userr017 You entered incorrect data, order id should be like -> 000000001
![selection_103](https://user-images.githubusercontent.com/40756439/45626625-a3c21100-ba98-11e8-93af-685392f333b5.png)

**Comment by Mizogorou** [comment]
I have the same issue too on Magento 2.3.2 and PHP 7.2, but I solved by choose the proper store view i.e. when the order was created from 'EN' store view. Therefore when you submit an orders and returns form, you have to choose 'EN' store view before.

I don't know this scenario is a bug or feature. Can anyone confirm for this case?

Thank you.
