### ISSUE TITLE
Item qty declaration error

### ISSUE THREAD

**Issue by webusat** [magento/magento2#18092]
### Preconditions

1. Magento 2.2.0
2. PHP 7.0
3. MySQL 5.7

### Steps to reproduce

I don't know that you can reproduce.  This was working fine then this error showed up.  We more need some help in determining what can cause this error so we can fix it.

1. Add a product from the category page forces the users to the product page where this message appears - "Item qty declaration error".  This doesn't happen for every product or for the same product each time. 
2. Add a product to the cart from the product page.
3. Item Declaration error message "Item qty declaration error"appears  when the "Add to Cart" button is clicked.
4. This also shows in the cart page.  The first item is fine and the rest of the items show this message.
5. If the first item is deleted form the cart the page refreshes and the next item takes its place.  The message disappears for the first item again but remains for all the following item.

This doesn't seem to happen when there is a configurable item in the cart.  If I add a configurable item after this message shows, the message disappears from the cart.  If I remove the configurable item the message re-appears.

A few things we did before this happened:
- Added a new configurable item manually
- Uploaded some new CSS pages
- Added a new configurable product using a CSV file and the import function

### Expected result

Explained above

### Actual result

Explained above

Thanks for any help you can give.
Stan

**Product Page**
![screen shot 2018-09-17 at 9 03 40 am](https://user-images.githubusercontent.com/3420585/45624541-9ab14f80-ba58-11e8-9d9b-6337d3275d78.png)

**Cart - First item without message and the rest with the message**
![screen shot 2018-09-17 at 8 59 27 am](https://user-images.githubusercontent.com/3420585/45624516-840af880-ba58-11e8-8e51-322190433cab.png)

**Cart - First item removed and the next item moves up and the message is gone**
![screen shot 2018-09-17 at 9 04 39 am](https://user-images.githubusercontent.com/3420585/45624629-e4019f00-ba58-11e8-8613-ba4f5e8dd7ba.png)

**Comment by magento-engcom-team** [comment]
Hi @webusat. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@webusat do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @emilshamloo   I'm not able to reproduce following steps your described.
This issue related to your custom code, not magento core code.
please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

If you like to update it please describe detail step to reproduce. Thank you

**Comment by webusat** [comment]
I realize you may not be able to reproduce it.  I was looking for more direction as to why this error message would show up.  

Stan

**Comment by ghost** [comment]
@webusat This may become from this step -> Added a new configurable product using a CSV file and the import function

**Comment by webusat** [comment]
@engcom-backlog-nazar  Okay.  So maybe from adding a configurable product using the CSV file.  Any recommendation on what to look for or action to take other than the obvious of deleting the product?

**Comment by ghost** [comment]
@webusat You have empty value from $qty of configurable product. see attachments where this exception became
![selection_102](https://user-images.githubusercontent.com/40756439/45625942-c4896700-ba96-11e8-9cc1-feb4013315a8.png)

**Comment by webusat** [comment]
@engcom-backlog-nazar  Thanks so much!  Is this related to inventory or is it for the actual quantity added to the cart?  If it is quantity, why does it show on the product page when a quantity is selected and added to the cart like my first screenshot?

Also, if I add any configurable product this goes away.

**Comment by ghost** [comment]
@webusat this related to inventory, you have wrong import products qty. so you have this error on every page where using qty.

**Comment by webusat** [comment]
@engcom-backlog-nazar  Okay, that is a big help, it is inventory related.  Weird that it goes away if a configurable item is added to the cart.  A few more questions.

We are running multiple sites with this install and it is affecting all sites.  Would this be expected?

Could only one product affect all the sites?

Thanks so much!!

**Comment by ghost** [comment]
@webusat yes this may be affected to one product, and affected to sites where product is related

**Comment by webusat** [comment]
@engcom-backlog-nazar  Thanks.  I have 5 sites and each sites gets this error.  Also, some of the items that this error happens to, show quantity available in the Magento backend.  So why would this still happen?

I also noticed that some simple products also have a negative number available.  We do have it set to accept orders even if it is out of stock.  Is this normal?  I am figuring it is.

Could this at all be javascript even-though nothing shows in the console?

**Comment by ghost** [comment]
@webusat If you use EE version then yes, if CE you should have an error we not have such many "product name", So you need to fix your import products

**Comment by webusat** [comment]
@engcom-backlog-nazar  We are using Magento 2.2.0 CE

Just to note, I also activated the Luma Theme and still have the same issue.

So I have a CSV from the beginning of the month I can use to update the site.  But if I use replace then I lose all my sorting and have to redo it for 500+ products.  Will update work or do I need to use replace?  If I have to use replace, is there any way to keep my sorting?

I also have a SQL dump from a week ago, would that be better?  If so do I replace the whole database or is there a way to just do the products?

I am not really understanding - "if CE you should have an error we not have such many "product name", So you need to fix your import products".  How does that related to inventory if this is an inventory issue?

Please note, that if I add any configurable product to the cart this message goes away for all items.  If I remove the configurable item the error message comes back.

Thanks!

**Comment by ghost** [comment]
@webusat You just need correctly replace qty for you imported products

**Comment by webusat** [comment]
@engcom-backlog-nazar  Okay.  

All the products for each site?  Or just the one product we tried to update?

Replace them to what number?  How do I know?

It may not matter because I deleted the configurable product I manually created and that didn't help.

Keep in mind I only updated 1 configurable product through the CSV which didn't really work.  So I manually created the configurable product and created one item for that product.  Next I manually created the other products using the simple items already in Magento.  Then I deleted to original item I created leaving all the items I needed to be associated with that product.  This one product is only for one site but all the sites have this error.

I so greatly appreciate your help!  We have been working on this for days with no resolution.

**Comment by ghost** [comment]
@webusat Maybe only one product, Try debugging at this point https://github.com/magento/magento2/issues/18092#issuecomment-422016070

**Comment by webusat** [comment]
@engcom-backlog-nazar  Okay.  I deleted the one product we added but that didn't fix it.

Can you help me understand why it is an inventory issue when products are showing items in stock and we have it set to take orders even-though a product may be out of stock?

**Comment by webusat** [comment]
@engcom-backlog-nazar  I added this to vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php

Before line 329
$writer = new \Zend\Log\Writer\Stream(BP . '/var/log/logfile.log');
$logger = new \Zend\Log\Logger();
$logger->addWriter($writer);
$logger->info('Array Log'.print_r($this->_getData('qty'), true));

and it returned this:
2018-09-17T15:41:07+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:07+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:07+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:07+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:12+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:12+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:12+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:12+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:13+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:13+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:13+00:00 INFO (6): Array Log1.0000
2018-09-17T15:41:13+00:00 INFO (6): Array Log1.0000

It seems there is a quantity there unless I am mis-understanding something.

**Screenshot**
![screen shot 2018-09-17 at 11 44 33 am](https://user-images.githubusercontent.com/3420585/45633919-13bba180-ba6f-11e8-9d07-2bd73813885f.png)

Also, any idea why when I have all simple products added to the cart I see this error but when I add any configurable product this error message goes away?

**Comment by ghost** [comment]
@webusat Set a breakpoint on this ->see attachments. on file app/code/magento/quote/model/quote/item/Abstractitem.php and see if you have a qty. when you add product to card
![selection_107](https://user-images.githubusercontent.com/40756439/45673763-3cf23580-bb34-11e8-89da-3e0794a60f63.png)

**Comment by webusat** [comment]
@engcom-backlog-nazar  I will try to post what we did to track the problem.  This did end up being a plugin that was loaded so a minimum quantity was needed to order a particular configurable item.  For some reason this was also applying to simple products and throwing the error.  We have contacted the creator but for the time being disabling the plugin fixed the problem.  Thanks!
