### ISSUE TITLE
Configurable Product collection doesn't use flat tables

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18099]
### Preconditions
1. Magento 2.2.5
2. PHP 7.1
3. Mysql 5.6

### Steps to reproduce
1. Function isEnabledFlat of Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable\Product\Collection class always return false
```
public function isEnabledFlat()
{
    return false;
}
```
while his parent class has
```
public function isEnabledFlat()
{
   if (!isset($this->_flatEnabled[$this->getStoreId()])) {
       $this->_flatEnabled[$this->getStoreId()] = $this->getFlatState()->isAvailable();
    }
    return $this->_flatEnabled[$this->getStoreId()];
}
```

### Expected result
1. Configurable product on frontend uses flat tables

### Actual result
1. Configurable product on frontend doesn't use flat tables

It's bug or feature?

**Comment by magento-engcom-team** [comment]
Hi @Hesoy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Hesoy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @Hesoy thank you for you report, If you set a break point to both method you will see, that magento uses always parent method is Flat Enable, If you like to update this please reopen issue.

**Comment by ghost** [comment]
@engcom-backlog-nazar How it could use parent method if Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable\Product\Collection overrides it? I have setted break point on this two methods and it always return false when i'm trying render configurable product on catalog page.

**Comment by ghost** [comment]
@Hesoy I'm have no idea why magento use this, But magento use parent method, breakpoint stops on first parent then jump to extended, and then again to parent. so you always use parent method

**Comment by ghost** [comment]
@Hesoy No usages found in All Places, for second method.
and in construct    -> parent::_construct(); that use isEnabledFlat of parent method

**Comment by ghost** [comment]
@engcom-backlog-nazar Ok, I'm debugging renderer.phtml in module-swatches and in Magento\ConfigurableProduct\Block\Product\View\Type\Configurable::getAllowProducts() I'm trying to get allow products. I'll share my debug print screens.
https://prnt.sc/kvr9bk
https://prnt.sc/kvr997
https://prnt.sc/kvr97j
https://prnt.sc/kvr921

**Comment by ghost** [comment]
@Hesoy  sometimes it return IsEnabled method of extended class, but in construct of extend class set the parent IsEnabled Flat() method so you always get value of parent method.
![selection_110](https://user-images.githubusercontent.com/40756439/45695439-13ec9780-bb6a-11e8-8cd0-1730c548518a.png)
