### ISSUE TITLE
Wrong sort order for customer groups in customer grid filter

### ISSUE THREAD

**Issue by sreichel** [magento/magento2#18101]
### Preconditions

1. Magento-2.x (every version, same in M1)

### Steps to reproduce

1. imagine you've 50 customer groups (not only 3 default)
2. go to admin customer grid and filter by group

### Expected result

1. customer groups are listed alphabetically

### Actual result

1. customer groups are listed by ID (this is really unfavourable if you have a lot of groups)

![m2-18101](https://user-images.githubusercontent.com/5022236/45636919-6e71ef00-baa9-11e8-9d2c-572e77c927d1.PNG)

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sreichel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95065`, `MAGETWO-95066` were created

**Comment by ghost** [comment]
Hi @sreichel , thank you for your report.
We've acknowledge the issue and added to our backlog.

**Comment by slavvka** [comment]
Hi @sreichel. Thank you for your report. 
The issue has been fixed in magento/magento2#18117 by @dmytro-ch in 2.3-develop branch
Related commit(s):
 - [568fa46a9c5ec3bb7de2746ea168e16b90eb1aba](https://github.com/magento/magento2/commit/568fa46a9c5ec3bb7de2746ea168e16b90eb1aba)
 - [ed994905103bc3824e940b96cf72239a33d932b4](https://github.com/magento/magento2/commit/ed994905103bc3824e940b96cf72239a33d932b4)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your report. 
The issue has been fixed in magento/magento2#18280 by @dmytro-ch in 2.2-develop branch
Related commit(s):
 - [484bbba6407f03c7b2261992c0ec2433d00a2cb4](https://github.com/magento/magento2/commit/484bbba6407f03c7b2261992c0ec2433d00a2cb4)
 - [dd9b2948a03abdc487e712d4237a9180484cb17b](https://github.com/magento/magento2/commit/dd9b2948a03abdc487e712d4237a9180484cb17b)

The fix will be available with the upcoming 2.2.8 release.
