### ISSUE TITLE
[2.2] Ordered Products Report Date Input fields ignore interface locale

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#18103]
### Preconditions
1. Magento 2.2.5
2. Admin Interface Locale set to a locale that has dd/mm/YY date format. e.g "English United Kingdom"

### Steps to reproduce
1. Log into Admin Console
2. Select Reports -> Ordered
3. Select the from date 1st September 2018 from the calendar. Ensure date is 01/09/2018
4. Select the to date 10th September 2018 from the calendar. Ensure date is 10/09/2018

### Expected result
1. Should show a report with 10 lines in it, from 1st September to 10th September

### Actual result
1. A report with rows from 9th January 2018 to the 9th October 2018 is shown.

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @gwharton, here is your [Magento instance](https://i-18103-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18103-2-2-5.engcom.dev.magento.com/admin](https://i-18103-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gwharton** [comment]
I can confirm that the issue is reproduced on 2.2.5 test instance.

I can also confirm this issue is NOT present in 2.3-develop

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @gwharton thank you for you report, the fix for this issue has already available in 2.3-develop

**Comment by gwharton** [comment]
Does this mean we are no longer fixing issues in 2.2 if they are fixed in 2.3?

**Comment by ghost** [comment]
@gwharton  No this mean that this fix backported to 2.2-dev branch

**Comment by gwharton** [comment]
Step 4 of the new process above suggests that all issues will be closed if they cant be reproduced on 2.3-develop.

**Comment by ghost** [comment]
@gwharton Yes if issue fixed on 2.3-dev this means that someone created pr and resolved this issue, this is expected that fix will be ported to 2.2-dev.

**Comment by gwharton** [comment]
ok, thanks for that. I understand now.

**Comment by gwharton** [comment]
If anyone needs it before the next 2.2.x release, here is the commit that fixes the issue.

https://github.com/magento/magento2/commit/fea3b7a0f9151b3c236ea02475fde4b1793c7a0b
