### ISSUE TITLE
I am getting below error on browser console

### ISSUE THREAD

**Issue by dnesdeveloper** [magento/magento2#18105]
I am getting below error on browser console
"NetworkError: 400 Bad Request - https://yourdomain.com/rest/default/V1/carts/mine/payment-information"

and showing "Please specify the shipping method" error in payment section when clicking on place order button for login customer - Custom Shipping Module 

Magento CE Ver 2.2.3

**Comment by magento-engcom-team** [comment]
Hi @dnesdeveloper. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dnesdeveloper do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
