### ISSUE TITLE
purchase a downloadable product as guest checkout  it does not appear in my downloadable products section

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#18104]
Hi,

When I purchase a downloadable product as a guest and create account after, that product order does not appear in the my downloadable products section after completed purchase but invoice  is appear in My Orders.

Preconditions
magento 2.2.1
php 7

**Steps to reproduce**

- purchase downloadable product via guest checkout.
- successfully pay .
- Create Account.
- go to my email for the invoice downloadable products is there.
- go to my downloadable products in my account and it is not there

**Expected result**
New downloadable products should also show up in my downloadable products section after using guest checkout and create account .

**Actual result**
downloadable Product do not show up in my downloadable products section but invoice is show in my order section 
![magentodownload](https://user-images.githubusercontent.com/33385380/45645670-32319500-ba8f-11e8-8966-0979b54273e7.jpg)

**Comment by magento-engcom-team** [comment]
Hi @testmagento2. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@testmagento2 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @testmagento2 thank you for you report, the fix for this issue has already available in 2.2-develop branch

**Comment by testmagento2** [comment]
I just upgrade to latest version 2.2.6 and I am still getting the issue.
Where I can get the fix for that?

**Comment by testmagento2** [comment]
Why his issue wasn't ix on 2.2.6
Please help
