### ISSUE TITLE
Single Transaction with multiple models using service contractor pattern

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18106]
### Summary
Currently the core class \Magento\Framework\DB\Transaction uses the deprecated _getResource method, which makes it "impossible" to use correctly while implementing the service contractor pattern because it doesn't take into account the existence of a Repository logic (and so the repository save method gets bypassed entirely for the entities involved).

### Examples
Currently code which needs to commit an entity into db uses the following pattern:
$this->resourceRepository->save($resource)
which is fine only as long as one resource/resource type is involved. If I need to commit multiple ones i'm stuck with:
$transaction = $this->transactionFactory->create()
    ->addObject($user)
     ->addObject($order)
     ->save();
which skips the repository logic entirely.

### Proposed solution
Allow transactions to use repositories and invoke save methods on them, instead of _getResource ()->save() (which according to your annotations is deprecated).

**Comment by magento-engcom-team** [comment]
Hi @strychnide. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@strychnide do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
No need for an instance since it's a purely theoretical/logical matter.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @strychnide It will be processed faster if you move this to https://github.com/magento/community-features

Best regards!
