### ISSUE TITLE
Cache flush not working on product save ( change product status from disabled to enabled)

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#18116]
Preconditions
Magento-2.2.3 
Make sure varnish enabled on server

Steps to reproduce
=> must be enabled cache
=> must be production mode
=> go to any product page
=> go to admin and change product status to disabled
=> refresh product page it will go to 404 page
=> now change status to enabled
=> refresh product page again, it should show product page but still it is showing 404 page

Expected  Result
it should show product page

Actual  Result 
It is showing 404 page

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sunilit42 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by sunilit42** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by ghost** [comment]
Hi @sunilit42 I'm not able to reproduce following steps your described, see attachments. 
If you like to update please reopen issue.
![cache](https://user-images.githubusercontent.com/40756439/45689937-ed286400-bb5d-11e8-860e-330a6227e7bd.gif)

**Comment by sunilit42** [comment]
Hello @engcom-backlog-nazar 
make sure varnish on server

**Comment by ghost** [comment]
@sunilit42 Did you use varnish ? please describe precondition on this issue.

**Comment by sunilit42** [comment]
@engcom-backlog-nazar 

i did thanks

**Comment by ghost** [comment]
@sunilit42  Same with varnish server, problem may be related to you custom code. Please close issue or update it 
![cache2](https://user-images.githubusercontent.com/40756439/45691057-717be680-bb60-11e8-8d9c-8252eaea2373.gif)

**Comment by ghost** [comment]
@sunilit42  any updates ?

**Comment by sunilit42** [comment]
yes Magento version updated

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-18116-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18116-2-3-develop.engcom.dev.magento.com/admin](https://i-18116-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sunilit42** [comment]
check with 2.2.3

**Comment by sunilit42** [comment]
@engcom-backlog-nazar 

https://i-18116-2-3-develop.engcom.dev.magento.com/test.html

check this product
and backend product status is enabled

**Comment by ghost** [comment]
@sunilit42 You don't set qty and stock status check now https://i-18116-2-3-develop.engcom.dev.magento.com/test.html

**Comment by ghost** [comment]
@sunilit42  can you close issue please?

**Comment by sunilit42** [comment]
wait i m still checking

**Comment by sunilit42** [comment]
varnish is not there

**Comment by ghost** [comment]
@sunilit42 I told you that i can't reproduce with varnish.

**Comment by ghost** [comment]
@sunilit42 I close issue if you like to update please reopen issue if you have some additional information

**Comment by sunilit42** [comment]
@engcom-backlog-nazar 
for me happen only with varnish

i disabled varnish and i checked 

it is working fine so error with only varnish

**Comment by ghost** [comment]
@sunilit42 This related to your environment because i'm too use varnish and have no this issue.
Best regards.

**Comment by sunilit42** [comment]
today i checked with one of the cloud environment and same issue on the cloud as well


so it is related to varnish issue

**Comment by sunilit42** [comment]
check 

someone also said same issue

https://github.com/magento/magento2/issues/7392 : avdb comment

**Comment by ghost** [comment]
@sunilit42  So you issue is duplicate to this ->https://github.com/magento/magento2/issues/7392 
Please go to the discussion at referenced issue.
Thank you.
