### ISSUE TITLE
Almost impossible to update region

### ISSUE THREAD

**Issue by escopecz** [magento/magento2#18118]
### Preconditions

Magento 2.2.4
API authorization OAuth1a

### Steps to reproduce

1. If I try to update a customer with country "USA" via API with following region info it works fine.
```
     "region": {
        "region_code": "CA",
        "region": "California",
        "region_id": 12
      }
```
2. But if I try to update region with the same object but with country (for example "CZ) that does not support regions in Magento I get this error:
```
{
  "message": "Invalid value of \"%value\" provided for the %fieldName field.",
  "parameters": {
    "fieldName": "regionId",
    "value": "12"
  }
}
```

### Expected result

1. I provide `"region": "CA"` or `"region": "California"` and Magento will be able to match it with existing region.
2. How a 3rd party app can know what countries has regions and what ID it has? I don't see any endpoint for that at https://devdocs.magento.com/swagger/index_20.html

### Actual result

1. Sometimes an error message if I provide the region_id.
2. Sometimes the region will not be stored if I don't provide the region_id.
3. It's possible to send the region information only if I fetch it first so I know the region_id. But how can I modify this value?
4. Why Magento need all 3 information about region (name, short code, ID) when it represent the same thing? Can you pick one? (not the ID)

**Comment by magento-engcom-team** [comment]
Hi @escopecz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@escopecz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rparsi** [comment]
@escopecz There are 2 Rest endpoints (Magento version 2.2.x):
`/V1/directory/countries`
`/V1/directory/countries/{countryId}`

Country ID's are in ISO 2 char length formats (ie `CA` for Canada).
Country object returned in the json has array `available_regions`.

For any other data and/or processing you'll have to make your own Rest endpoint.
Refer to `vendor\magento\module-directory\etc\webapi.xml`

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @escopecz You can get region id on this endpoint ->/V1/directory/countries , And for some country region id is required, for some on not. And this is related ->https://github.com/magento/magento2/issues/18024 
If you like to update this, please reopen issue.
Best regards.

**Comment by escopecz** [comment]
Thanks guys! This helped me to get going. It's over complicated, would be nice if Magento would handle regions similarly as the country select, but at least I can finish the Magento implementation.
