### ISSUE TITLE
API: Postcode always required on customer update even if it isn't

### ISSUE THREAD

**Issue by escopecz** [magento/magento2#18111]
### Preconditions

1. Magento 2.2.4
2. API authorization OAuth1a

### Steps to reproduce

1. Get all address field definitions with `GET index.php/rest/V1/attributeMetadata/customerAddress`
2. It will return this default definition of the postcode field:
```
  {
    "frontend_input": "text",
    "input_filter": "",
    "store_label": "Zip\/Postal Code",
    "validation_rules": [],
    "multiline_count": 0,
    "visible": true,
    "required": false,
    "data_model": "Magento\\Customer\\Model\\Attribute\\Data\\Postcode",
    "options": [],
    "frontend_class": "",
    "user_defined": false,
    "sort_order": 110,
    "frontend_label": "Zip\/Postal Code",
    "note": "",
    "system": true,
    "backend_type": "static",
    "is_used_in_grid": true,
    "is_visible_in_grid": true,
    "is_filterable_in_grid": true,
    "is_searchable_in_grid": true,
    "attribute_code": "postcode"
  },
```
3. Notice the row `"required": false,`
4. Try to update an existing customer on endpoint `PUT index.php/rest/V1/customers/70165` with body:
```
{
  "customer": {
    "id": "70165",
    "email": "hhh@ggg.nn",
    "firstname": "Huberto",
    "lastname": "Bubao",
    "addresses": [
      {
        "city": "Prague2s5",
        "country_id": "DZ",
        "street": ["Address 11s5"],
        "telephone": "5553453445",
        "defaultShipping": true,
        "firstname": "Huberto",
        "lastname": "Bubao"
      }
    ],
    "website_id": 1,
    "store_id": 1,
    "group_id": 1
  }
}
```

### Expected result
Expected response:
```
{
  "id": 70165,
  "group_id": 1,
  "default_shipping": "26963",
  "created_at": "2018-09-14 15:08:08",
  "updated_at": "2018-09-18 08:39:16",
  "created_in": "Devices",
  "dob": "2018-09-25",
  "email": "hhh@ggg.nn",
  "firstname": "Huberto",
  "lastname": "Bubao",
  "prefix": "Lord",
  "gender": 2,
  "store_id": 1,
  "website_id": 1,
  "addresses": [
    {
      "id": 26963,
      "customer_id": 70165,
      "region": {
        "region_code": null,
        "region": null,
        "region_id": 0
      },
      "country_id": "DZ",
      "street": [
        "Address 11s5"
      ],
      "telephone": "5553453445",
      "city": "Prague2s5",
      "firstname": "Huberto",
      "lastname": "Bubao",
      "default_shipping": true
    }
  ]
}
```

### Actual result
Actual response:
```
{
  "message": "%fieldName is a required field.",
  "parameters": {
    "fieldName": "postcode"
  }
}
```
As we have to finish the Magento integration, is there some quick fix? Is postcode always required so we can hard-code it to the integration?

**Comment by magento-engcom-team** [comment]
Hi @escopecz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@escopecz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @escopecz this is expected behavior, you need choose country in admin, Who dont need a postal code required
![selection_109](https://user-images.githubusercontent.com/40756439/45677008-d07b3480-bb3b-11e8-924c-67af52590be5.png)

**Comment by escopecz** [comment]
Thanks for the answer! It makes more sense now, but shouldn't the list of fields then say that it is a required field? Even if it is only for some countries but it still is required.

Can you please describe how to get to that setting? I can't find it.

**Comment by ghost** [comment]
@escopecz store->configuration->general->general->Zip/Postal Code is Optional for; 
"but shouldn't the list of fields then say that it is a required " -> Seems yes, but optionaly you can change him.

**Comment by escopecz** [comment]
Thanks again! I do not control configuration of Magento instances. I just write API connection with another system that anybody will be able to use. So I have 2 options now:

1. Write into docs that each user should go to the post code field and mark it as required. But we all know that not many users read the docs.
2. Hard-code in the code that the post code field is always required. Which I will do, but it's an ugly hack.

Optimal solution would be if the post code field would be required by default. Than none of the above would be needed.

**Comment by ghost** [comment]
@escopecz Yes Optimal solution would be better, but this would be an feature request, not a  bug.
you can report here -> https://github.com/magento/community-features
