### ISSUE TITLE
Unable to login on frontend

### ISSUE THREAD

**Issue by melaxon** [magento/magento2#18119]
### Preconditions

1. Version 2.2.5

2. Local computer MAC (el capitan, apache2.4, php7.1), domain https://www.magento2.loc, self signed SSL, 

### Steps to reproduce

1. Click login on any page and enter username and password
2. Any browser

### Expected result

1. Must be logged in
2.

### Actual result

1. Not logged in with no error message
2. If I enter wrong username or password, I receive error message. With correct credentials it just reloaded the login page. I tried all possible settings with cookies and sessions, cleared generated, cache and sessions directories, disabled all modules in app/code and switched to blank theme. I changed the storage of sessions from files to db and back
The backend, by the way, worked normally. I could log in and out to the dashboard.

Sometimes the restart of the computer helps, sometimes not. Sometimes I can login on Safari and cannot on Firefox

Similar thing happened on Magento 1. I could comment some lines that validate cookies in Varien.php to solve this

Is there any workaround I could apply?

**Comment by magento-engcom-team** [comment]
Hi @melaxon. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@melaxon do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by melaxon** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @melaxon. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @melaxon, here is your [Magento instance](https://i-18119-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18119-2-2-5.engcom.dev.magento.com/admin](https://i-18119-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by melaxon** [comment]
> @melaxon do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [ ]  yes
> 
>     * [ X ]  no

No, vanilla instance is okay. I also could not reproduce it on the copy of my own shop on remote host. On localhost it also was okay. Till yesterday. 
I rolled back all changes and it did not help
And I wonder how not to reproduce it in production environment since the cause is still unknown, and what to do if this will happen. For example in M1 the same fault happened sometimes and it was unpredictable. But I knew the trick with commenting lines in Varien.php

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
HI @melaxon Problem related to your environment, maybe try use nginx, or change session to redis,
maybe that helps, or re check your configuration of apache.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
