### ISSUE TITLE
Magento 2.2.5 and PHP 7.2.9 - Fatal error:  Class Magento\Framework\Session\SaveHandler\Redis\Config contains X abstract methods and must therefore be declared abstract or implement the remaining methods (Cm\RedisSession\Handler\ConfigInterface::getSentinelServers, ...) in /lib/internal/Magento/Framework/Session/SaveHandler/Redis/Config.php on line 16 # php bin/magento setup:di:compile

### ISSUE THREAD

**Issue by janisuk** [magento/magento2#18129]
Get error when I run command

#php bin/magento setup:di:compile

Fatal error:  Class Magento\Framework\Session\SaveHandler\Redis\Config contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Cm\RedisSession\Handler\ConfigInterface::getSentinelServers, ...) in /lib/internal/Magento/Framework/Session/SaveHandler/Redis/Config.php on line 16 # php bin/magento setup:di:compile

Solution, works for me

Go to /lib/internal/Magento/Framework/Session/SaveHandler/Redis/

Open file Config.php

and change

class Config implements \Cm\RedisSession\Handler\ConfigInterface

to 

abstract class Config implements \Cm\RedisSession\Handler\ConfigInterface

#######################################################################

This is not just one problem. Before can I run this command php bin/magento setup:di:compile, I also changed the files:

\app\code\Magento\Tax\Model\System\Config\Source\Tax\Country.php
#public function toOptionArray($noEmpty = false)
public function toOptionArray($noEmpty = false, $foregroundCountries = '')

\app\code\Magento\Customer\Model\Customer\Attribute\Source\Group.php
#public function getAllOptions()
public function getAllOptions($withEmpty = true, $defaultValues = false)

\app\code\Magento\Customer\Model\Customer\Attribute\Source\Store.php
#public function getAllOptions()
public function getAllOptions($withEmpty = true, $defaultValues = false)

\app\code\Magento\Customer\Model\Customer\Attribute\Source\Website.php
#public function getAllOptions()
public function getAllOptions($withEmpty = true, $defaultValues = false)

\app\code\Magento\Customer\Model\ResourceModel\Address\Attribute\Source\Country.php
#public function getAllOptions()
public function getAllOptions($withEmpty = true, $defaultValues = false)

\app\code\Magento\Customer\Model\ResourceModel\Address\Attribute\Source\CountryWithWebsites.php
 #public function getAllOptions()
public function getAllOptions($withEmpty = true, $defaultValues = false)

\app\code\Magento\Customer\Model\ResourceModel\Address\Attribute\Source\Region.php
#public function getAllOptions()
public function getAllOptions($withEmpty = true, $defaultValues = false)

\app\code\Magento\Directory\Model\Config\Source\Country\Full.php
#public function toOptionArray($isMultiselect = false)
public function toOptionArray($isMultiselect = false, $foregroundCountries = '')

\app\code\Magento\Eav\Model\Entity\Attribute\Source\Store.php
#public function getAllOptions()
public function getAllOptions($withEmpty = true, $defaultValues = false)

-------------------------------------

All this problems start from admin panel

![magento-admin-panel](https://user-images.githubusercontent.com/4958428/45745936-a5abe180-bc0a-11e8-8f50-9e3c42d0f8f6.png)

I still have not gotten back

-----------------------------------------

# Update
Solved admin panel menu
PHP 7.2.9 downgrade to 7.1.2

**Comment by magento-engcom-team** [comment]
Hi @janisuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@janisuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
HI @janisuk I'm not able to reproduce following steps your described, I'm trying with redis-server, Please describe the issue .
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results.
Then reopen the issue.
Best Regards.
