### ISSUE TITLE
issue of using symlink to link app/design dir to Magento

### ISSUE THREAD

**Issue by haiwera-silk-cd** [magento/magento2#18125]
### Preconditions

1. version:2.2.5
2. php version: 7.1.0

### Steps to reproduce

1. use the `ln` command to link my design directory into Magento's app directory
2. there were get wrong absolute directory, such as I'll get `/var/www/mage2/app/code/design/backend/app/code/design` if the dir is linked to Magento from `/backend/app/code/design`

### Expected result

1. product image in frontend and product saving in admin panel should work fine

### Actual result

1. ![image](https://user-images.githubusercontent.com/37173598/45726668-cff1a500-bbf2-11e8-848f-8daaaf8b4ec3.png)

2. frontend is unable to work

**Comment by magento-engcom-team** [comment]
Hi @haiwera-silk-cd. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@haiwera-silk-cd do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by haiwera-silk-cd** [comment]
For now, To fix the issue temporarily I only can change the `registration.php` in the theme module as below:
![image](https://user-images.githubusercontent.com/37173598/45726950-34613400-bbf4-11e8-9ead-ace9a73c2fc0.png)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
@haiwera-silk-cd Thank you for you report, the fix for this issue has already available in 2.3-develop branch
