### ISSUE TITLE
Entity Type ID at Join

### ISSUE THREAD

**Issue by akimatze** [magento/magento2#18131]
### Preconditions
1. Magento EE 2.2.5
2. MySQL 5.7, PHP 7.1.14

### Steps to reproduce
1. Create new Entity Type with InstallData Script. Use eav_entity table as entity table with some random attributes.
2. Create Default EAV Model, ResourceModel and Collection
3. Use collection, addFieldToSelect of one of the attributes and load them.

### Expected result
1. Entries with added attribute

### Actual result
1. Integrity constraint violation: 1052 Column 'entity_type_id' in where clause is ambiguous, query was: SELECT `e`.`entity_id`, `t_d`.`attribute_id`, `t_d`.`value` FROM `eav_entity` AS `e` INNER JOIN `eav_entity_varchar` AS `t_d` ON e.entity_id = t_d.entity_id WHERE ( e.entity_id IN (1)) AND (t_d.attribute_id IN ('464')) AND (entity_type_id =12)

### Quick fix:
1. Magento\Eav\Model\Entity\Collection\AbstractCollection.php ~line 1235
2. Add to $select->where(..) statement: 'e.entity_type_id =?' instead of 'entity_type_id'

**Comment by magento-engcom-team** [comment]
Hi @akimatze. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@akimatze do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @akimatze this is duplicate for this -> https://github.com/magento/magento2/issues/17863 
The same logics affcted, to the query.
And this may be fixed with this pr -> https://github.com/magento/magento2/pull/17864
If you like to update this, please reopen the issue.

**Comment by engcom-backlog-nazar** [comment]
@akimatze Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95102`, `MAGETWO-95103` were created

**Comment by ghost** [comment]
@akimatze, thank you for your report.
We've acknowledge the issue and added to our backlog.

**Comment by sidolov** [comment]
Hi @akimatze. Thank you for your report. 
The issue has been fixed in magento/magento2#18437 by @strell in 2.3-develop branch
Related commit(s):
 - [2f4ad2f42dba88f53eb075b041465662061e2278](https://github.com/magento/magento2/commit/2f4ad2f42dba88f53eb075b041465662061e2278)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @akimatze. Thank you for your report. 
The issue has been fixed in magento/magento2#18658 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [53a06a9ba12c0f4be0b28fdf6f9cf45540cebae6](https://github.com/magento/magento2/commit/53a06a9ba12c0f4be0b28fdf6f9cf45540cebae6)

The fix will be available with the upcoming 2.2.8 release.
