### ISSUE TITLE
Magento 2.2.5 issue with widget conditions (featured)

### ISSUE THREAD

**Issue by kevinlab51** [magento/magento2#18130]
###Summary
After upgrade to 2.2.5 from 2.2.4, pages that contain a widget displaying featured products fail to load with an SQL error.

### Preconditions
1.PHP7
2.M2.2.5

### Steps to reproduce
1. Upgrade from 2.2.4 to 2.2.5
2. Have "featured products" in catalog
3. Have the featured attribute on scope "store view"
4. Have a widget on homepage with "featured products"

### Expected result
1. After upgrade (and cache:clean|flush, reindex, static-deploy etc. etc.), pages will load with no issues.

### Actual result
1. Pages containing featured products widget fail to load with SQL error:
`main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_featured_default.value' in 'where clause', query was: SELECT DISTINCT COUNT(DISTINCT e.entity_id) FROM mg_catalog_product_entity AS e INNER JOIN mg_catalog_category_product_index_store1 AS cat_index ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2' INNER JOIN mg_catalog_product_index_price AS price_index ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0 WHERE (((IFNULL(e.entity_id, at_featured_default.value) IN ('131', '146', '151', '164', '270', '336', '344', '345', '379', '385')) ))`

**Comment by magento-engcom-team** [comment]
Hi @kevinlab51. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kevinlab51 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by kevinlab51** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @kevinlab51. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @kevinlab51, here is your [Magento instance](https://i-18130-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18130-2-2-5.engcom.dev.magento.com/admin](https://i-18130-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kevinlab51** [comment]
@magento-engcom-team i am getting a error on your magento vanilla instance but i can't access the error file. And i can't run the indexer. What do i have to do here?

**Comment by ghost** [comment]
Hi @kevinlab51 maybe this is duplicate to -> https://github.com/magento/magento2/issues/16471 ?

**Comment by ghost** [comment]
@kevinlab51 I close issue as this is duplicate for referenced issue, if you like to update this please reopen the issue.
