### ISSUE TITLE
Preference for Magento\CatalogSearch\Block\Result does not work

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#18147]
### Preconditions

1. Magento EE 2.2.5

### Steps to reproduce

1. Create a new module with **di.xml** file
2. Set preference for `Magento\CatalogSearch\Block\Result` class
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
    <preference for="Magento\CatalogSearch\Block\Result" type="Qextensions\NoResult\Block\Result" />
</config>
```

### Expected result

1. Preference should work as expected with other blocks / models & helpers and new class should be used for block instance.

### Actual result

1. Preference does not work at all, I ended up creating a plugin for my task.

**Comment by magento-engcom-team** [comment]
Hi @qsolutions-pl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@qsolutions-pl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95114`, `MAGETWO-95115` were created

**Comment by jakwinkler** [comment]
@magento-engcom-team it is clean Magento 2 version, only LESS files were customized. We just started working on catalog search module and we've encountered this issue.

**Comment by sanjaychaudhary1412** [comment]
@qsolutions-pl :

Is your file **Qextensions\NoResult\Block\Result** extending the file **Magento\CatalogSearch\Block\Result** or you are simply overriding the whole file by creating a fresh block ?

I created a block that is extending the **Magento\CatalogSearch\Block\Result** file and I tried to overwrite the text in getSearchQueryText() function and it's working fine.

Let me know if you are trying a case other than this and please provide more details on it.

**Comment by ghost** [comment]
![selection_126](https://user-images.githubusercontent.com/40756439/46000148-7684ec80-c0b0-11e8-920b-ef8cb048eaa3.png)
@qsolutions-pl Seems like @sanjaychaudhary1412 is right, i extends the Magento\CatalogSearch\Block\Result end this works perfectly

**Comment by ghost** [comment]
@qsolutions-pl I'm  closing this issue as this is resolved, if you like to update this please reopen the issue
