### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in lib/internal/Magento/Framework/Filesystem/Directory/Write.php on line 35 in latest magento version 2.3 

### ISSUE THREAD

**Issue by vinaysikarwar** [magento/magento2#18146]
### Preconditions

1. Magento 2.3
2. php 7.1.2

### Steps to reproduce

1. do a fresh install of magento 2.3 from github repo
2. setup server with nginx and php 7.1.2

### Expected result

1. getting error  
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in lib/internal/Magento/Framework/Filesystem/Directory/Write.php on line 35
2. 

```php
public function __construct(
        \Magento\Framework\Filesystem\File\WriteFactory $fileFactory,
        \Magento\Framework\Filesystem\DriverInterface $driver,
        $path,
        $createPermissions = null,
        ?PathValidatorInterface $pathValidator = null
    ) {
        parent::__construct($fileFactory, $driver, $path, $pathValidator);
        if (null !== $createPermissions) {
            $this->permissions = $createPermissions;
        }
    }
```

? before PathValidatorInterface creating problem

### Actual result

1. magento will installed if everything will be working fine

**Comment by magento-engcom-team** [comment]
Hi @vinaysikarwar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vinaysikarwar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @vinaysikarwar I'm not able to reproduce following steps you described, i'm configure magento 2.3-dev with php7.2 and nginx and its worked perfectly.

**Comment by vinaysikarwar** [comment]
Please use php version 7.1.2 not 7.2

**Comment by ghost** [comment]
@vinaysikarwar But why you describe in precondition php 7.2 ?

**Comment by vinaysikarwar** [comment]
Sorry that was mistake instead of 7.1.2 I write 7.2.

But installed version is 7.1.2

**Comment by ghost** [comment]
@vinaysikarwar This problem related to your environment, i'm not able to reproduce, works perfectly.

**Comment by engcom-backlog-nazar** [comment]
@vinaysikarwar Be free to close issue.

**Comment by ishakhsuvarov** [comment]
Hi @vinaysikarwar 

Please check PHP version used by your web server. Looks like it still uses `7.0`. 

> ? before PathValidatorInterface creating problem

This syntax is fine with PHP 7.1+, as it indicates nullable type of the method parameter, please use this documentation [link](http://php.net/manual/en/migration71.new-features.php) for reference.

**Comment by vinaysikarwar** [comment]
PLease check attached screenshot
![image](https://user-images.githubusercontent.com/5436260/45804242-2fc27b80-bcd9-11e8-8afd-12d4c3dae1aa.png)

**Comment by ishakhsuvarov** [comment]
@vinaysikarwar This seems to be the output of CLI PHP installation, not php-fpm used by nginx.

**Comment by vinaysikarwar** [comment]
I will setup a new fresh server and will do update if it resolves or still has issue

**Comment by dharam1987** [comment]
I had the same issue, it is mostly to do with .PHP  version 7.0.x. It is working perfectly fine with PHP 7.2.0

> !!MIND YOU!! - Pls. ensure to check what is the php cli version by typing php -v in the command prompt. In my case even though my xampp PHP version was 7.2.0, the cli was still pointing to an old xampp installation.

Ensure to edit path variable for windows environment variable and set the correct PHP path.

![image](https://user-images.githubusercontent.com/966748/49863401-3a973300-fe26-11e8-9b01-6d046250e994.png)

![image](https://user-images.githubusercontent.com/966748/49863460-5995c500-fe26-11e8-828f-9f584c9a6640.png)
