### ISSUE TITLE
2.2.6 Special characters in email body are not encoded properly

### ISSUE THREAD

**Issue by Cristiano81** [magento/magento2#18157]
### Preconditions
1. Create an email template with special characters like à , è for example:
"Quando il pacco sarà  spedito, ti invieremo il numero di tracking."

### Steps to reproduce
1. Preview the email template from admin

### Expected result
1. The text shows the correct character à

### Actual result
1. The text shows character like Ã
"Quando il pacco sarÃ  spedito, ti invieremo il numero di tracking."

This worked in 2.2.5

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Cristiano81 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by Cristiano81** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Cristiano81, here is your [Magento instance](https://i-18157-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18157-2-2-6.engcom.dev.magento.com/admin](https://i-18157-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Cristiano81** [comment]
Thank you, the issue cannot be reproduce on vanilla Magento

**Comment by ghost** [comment]
Hi @Cristiano81 I'm also not able to reproduce this pn 2.2.6 instance.

**Comment by Cristiano81** [comment]
i will go further in testing

**Comment by ghost** [comment]
@Cristiano81 Can we close issue? and if you have some additional info, you can reopen in future.

**Comment by Cristiano81** [comment]
yes ok, i'm going to investigate on theme css

**Comment by ghost** [comment]
@Cristiano81 Ok, thank you, if you like to update this, please reopen the issue.
