### ISSUE TITLE
Cannot edit customer using inline edit if password is expired

### ISSUE THREAD

**Issue by Jeroenll** [magento/magento2#18162]
### Preconditions
1. Magento v2.2.5

### Steps to reproduce
1. Set `admin/security/password_is_forced` to `0` (_Recommended_).
2. Make sure Password Lifetime is past so the message `It's time to change your password.` is shown.
3. Open customer grid and try to edit and save using inline editor.

### Expected result
1. Customer is saved.

### Actual result
1. Above grid the message `It's time to change your password.` is shown

![image 2018-09-20 at 3 33 28 pm](https://user-images.githubusercontent.com/14925052/45821915-9d2ad800-bcea-11e8-9bbd-7caa59e2b8ac.png)

**Comment by magento-engcom-team** [comment]
Hi @JeroenVanLeusden. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@JeroenVanLeusden do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95128`, `MAGETWO-95129` were created

**Comment by dmytro-ch** [comment]
Looks like the issue cannot be reproduced on Magento 2.2.6 and 2.3 versions.

<img width="680" alt="screen shot 2018-09-22 at 4 14 03 pm" src="https://user-images.githubusercontent.com/11693779/45918206-1ca3dd00-be8c-11e8-97b8-62d75657bca3.png">

**Comment by ghost** [comment]
@dmytro-ch Please try again -> Open customer grid and try to edit and save using **inline editor.**
I'm able to reproduce on both instances.

**Comment by ghost** [comment]
@dmytro-ch  on 2.2-dev
![selection_123](https://user-images.githubusercontent.com/40756439/45940663-fd6b9380-bfe2-11e8-985a-7f78f50d9a8d.png)
on 2.3-dev
![selection_124](https://user-images.githubusercontent.com/40756439/45940666-02304780-bfe3-11e8-8760-146116b95f2a.png)

**Comment by dmytro-ch** [comment]
@engcom-backlog-nazar, thank you for the details!
It was my mistake, now I can reproduce the error.
I will handle this issue.

**Comment by slavvka** [comment]
Hi @JeroenVanLeusden. Thank you for your report. 
The issue has been fixed in magento/magento2#18308 by @dmytro-ch in 2.3-develop branch
Related commit(s):
 - [2eeb65ccd6201d95a667e5ccaf348b30d46317fe](https://github.com/magento/magento2/commit/2eeb65ccd6201d95a667e5ccaf348b30d46317fe)
 - [34830c61154ae4b199eef531901164a417ef6c7d](https://github.com/magento/magento2/commit/34830c61154ae4b199eef531901164a417ef6c7d)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @JeroenVanLeusden. Thank you for your report. 
The issue has been fixed in magento/magento2#18414 by @dmytro-ch in 2.2-develop branch
Related commit(s):
 - [33ba243a068b9e695fdb2520ab463aa3d5911f1a](https://github.com/magento/magento2/commit/33ba243a068b9e695fdb2520ab463aa3d5911f1a)
 - [2668f2df768d749f2069195715188afbf6d99348](https://github.com/magento/magento2/commit/2668f2df768d749f2069195715188afbf6d99348)

The fix will be available with the upcoming 2.2.8 release.
