### ISSUE TITLE
Checkout - Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18164]
@magento-engcom-team give me 2.2.6 instance

### Preconditions

1. Magento 2.2.6
2. PHP 7.1
3. MariaDB 10.2

### Steps to reproduce
1. Add an item into the cart.
2. Open Chrome devtools console.
3. Go to checkout

### Expected result
1. That checkout page doesn't display any console error.

### Actual result
1. The following (down below) console error is appearing in devtools console.
`Uncaught TypeError: Cannot read property 'code' of undefined
    at UiClass.initialize (/en_US/Magento_Checkout/js/view/progress-bar.js:31:93)`

**Comment by magento-engcom-team** [comment]
Hi @bruno-serfe. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bruno-serfe do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @bruno-serfe  I'm not able to reproduce following steps you described, this may be related to you custom code, or provide more information to step to reproduce. thank you.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-18164-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18164-2-2-6.engcom.dev.magento.com/admin](https://i-18164-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@bruno-serfe Here yours instance.

**Comment by ghost** [comment]
Hi @engcom-backlog-nazar thank you!, checking now..

**Comment by ghost** [comment]
Hi @engcom-backlog-nazar I can't reproduce either in this fresh instance and with that simple example product, you can close this, we can conclude that the issue should be related with external code or an extension then. thanks for the quick assistance on this, too much appreciated!

**Comment by ghost** [comment]
@bruno-serfe Ok. If you  would like to update you can reopen issue with some additional data.

**Comment by sidolov** [comment]
Hi @bruno-serfe. Thank you for your report. 
The issue has been fixed in magento/magento2#18495 by @ihor-sviziev in 2.2-develop branch
Related commit(s):
 - [e7f70abdd40b9bb1f46c45230412dbda0b421246](https://github.com/magento/magento2/commit/e7f70abdd40b9bb1f46c45230412dbda0b421246)
 - [25e3cfe56545df3a4dc502f0fa0d96f63f2e5e88](https://github.com/magento/magento2/commit/25e3cfe56545df3a4dc502f0fa0d96f63f2e5e88)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @bruno-serfe. Thank you for your report. 
The issue has been fixed in magento/magento2#18494 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [47978d74fb44398dd931cc762e53f1c802eab1a1](https://github.com/magento/magento2/commit/47978d74fb44398dd931cc762e53f1c802eab1a1)
 - [0fcbe126eff6cc5268268ec1154a261d49369152](https://github.com/magento/magento2/commit/0fcbe126eff6cc5268268ec1154a261d49369152)

The fix will be available with the upcoming 2.3.1 release.
