### ISSUE TITLE
Image CAPTCHA requires FT fonts support

### ISSUE THREAD

**Issue by jaideepghosh** [magento/magento2#18177]
I'm unable to login into the Magento-2 Admin Panel. After clicking on login, it is showing 

> There has been an error processing your request

In report it is showing the following:

`{"0":"Image CAPTCHA requires FT fonts support","1":"#0 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-captcha\/Model\/DefaultModel.php(92): Zend\\Captcha\\Image->__construct()\n#1 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Magento\\Captcha\\Model\\DefaultModel->__construct(Object(Magento\\Backend\\Model\\Auth\\Session\\Interceptor), Object(Magento\\Captcha\\Helper\\Adminhtml\\Data), Object(Magento\\Captcha\\Model\\ResourceModel\\LogFactory), 'backend_login')\n#2 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Captcha...', Array)\n#3 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\\\Captcha...', Array)\n#4 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-captcha\/Model\/CaptchaFactory.php(37): Magento\\Framework\\ObjectManager\\ObjectManager->create('Magento\\\\Captcha...', Array)\n#5 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-captcha\/Helper\/Data.php(100): Magento\\Captcha\\Model\\CaptchaFactory->create('DefaultModel', 'backend_login')\n#6 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-captcha\/Observer\/CheckUserLoginBackendObserver.php(53): Magento\\Captcha\\Helper\\Data->getCaptcha('backend_login')\n#7 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(72): Magento\\Captcha\\Observer\\CheckUserLoginBackendObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#8 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\Captcha\\Observer\\CheckUserLoginBackendObserver), Object(Magento\\Framework\\Event\\Observer))\n#9 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Event\/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#10 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('admin_user_auth...', Array)\n#11 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-user\/Model\/User.php(547): Magento\\Framework\\Event\\Manager\\Proxy->dispatch('admin_user_auth...', Array)\n#12 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-user\/Model\/User.php(603): Magento\\User\\Model\\User->authenticate('jaideepghosh', 'Admin@123')\n#13 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-backend\/Model\/Auth.php(156): Magento\\User\\Model\\User->login('jaideepghosh', 'Admin@123')\n#14 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\Model\\Auth->login('jaideepghosh', 'Admin@123')\n#15 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Backend\\Model\\Auth\\Interceptor->___callParent('login', Array)\n#16 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Backend\\Model\\Auth\\Interceptor->Magento\\Framework\\Interception\\{closure}('jaideepghosh', 'Admin@123')\n#17 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/generated\/code\/Magento\/Backend\/Model\/Auth\/Interceptor.php(26): Magento\\Backend\\Model\\Auth\\Interceptor->___callPlugins('login', Array, Array)\n#18 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(205): Magento\\Backend\\Model\\Auth\\Interceptor->login('jaideepghosh', 'Admin@123')\n#19 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(157): Magento\\Backend\\App\\Action\\Plugin\\Authentication->_performLogin(Object(Magento\\Framework\\App\\Request\\Http))\n#20 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(125): Magento\\Backend\\App\\Action\\Plugin\\Authentication->_processNotLoggedInUser(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#23 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/generated\/code\/Magento\/Backend\/Controller\/Adminhtml\/Index\/Index\/Interceptor.php(26): Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#24 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/App\/FrontController.php(55): Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#26 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#27 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#28 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#29 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#30 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#31 \/usr\/local\/nginx\/html\/Roanuz\/elko2\/local\/elko\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#32 {main}","url":"\/index.php\/admin\/admin\/index\/index\/key\/5e9869f3ce959a19795ec87ec53892f019e26f3a380c71205eea31be3c7cdf58\/","script_name":"\/index.php"}`

**Comment by magento-engcom-team** [comment]
Hi @jaideepghosh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jaideepghosh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
HI @jaideepghosh  Please describe steps to reproduce, so we can reproduce you issue, then reopen the issue. thank you.

**Comment by ghost** [comment]
@jaideepghosh  also please see https://github.com/magento/magento2/issues/11483

**Comment by jaideepghosh** [comment]
Thanks @engcom-backlog-nazar ,
Following solution solved my issue:
https://magento.stackexchange.com/questions/196527/image-captcha-requires-ft-fonts-support#answer-200043
