### ISSUE TITLE
Category object : Cannot programmatically set "Use Default Value" to attribute "Enable Category"

### ISSUE THREAD

**Issue by j0um** [magento/magento2#18178]
### Preconditions
1. Vanilla Magento 2.2.6

### Steps to reproduce
1. Have a category with the attribute "is_active" set to "1" at store level.
2. Create a script and programmatically set "is_active" to null
3. Save the category.

### Expected result
1. Category property "is_active" should be deleted at store level. On the adminhtml interface, at store level, looking at the category's properties should reveal the following :
Enable Category : "No"
Use default value : Checked.

### Actual result
1. Category property "is_active" value remains unchanged after save. On the adminhtml interface, at store level, looking at the category's properties should reveal the following :
Enable Category : "No"
Use default value : Unchecked.

The problem seems to be behind the logic CategoryRepository.php::save() that is quite different from ResourceModel\Category.php::save() : CategoryRepository doesn't accept properties with null values while ResourceModel\Category does.

**Comment by magento-engcom-team** [comment]
Hi @j0um. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@j0um do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @j0um thank you for your report, but if you set '0' this may works ?

**Comment by ghost** [comment]
@j0um  when you create the attribute you set default value as 'default'  => '0', so the magento accept only 1 or 0 but not 'null' for boolean, resource model can save this value, but you need to use repository, this is the best practice.

**Comment by j0um** [comment]
@engcom-backlog It is best practice indeed! The issue is that we cannot set the "Use default value" checkbox value using the repository. Right now we can only set it using the resource model and the resource model uses null values to set/unset the checkbox.

Setting "is_active" to 0 will deactivate the category but will not set the "use default value" checkbox. To set the "use default value" checkbox, we have to set "is_active" to null using the resource model logic.

**Comment by ghost** [comment]
@j0um As i can see the set IsActive() can have set only 2 types Boolean true and false 0,1 but not null ?
![selection_122](https://user-images.githubusercontent.com/40756439/45888039-c0768580-bdc5-11e8-933c-71c3b0638668.png)

**Comment by ghost** [comment]
@j0um also see -> https://github.com/magento/magento2/issues/12159 seems like this bug is acknowladged.

**Comment by j0um** [comment]
@engcom-backlog-nazar Oh nice find! It is indeed the same bug. Thank you! :)
