### ISSUE TITLE
Web installation Assistant 500 error

### ISSUE THREAD

**Issue by happydownload33** [magento/magento2#18182]
### Preconditions
1. Magento 2.2.4
2. Magento 2.2.5
3. Magento 2.2.6

### Steps to reproduce
1. Update Magento 2.2.3 to Preconditions version
2. Login Magento Dashboard
3. Go to System
4. Go to Web Installation Assistant

### Expected result
1. The 4 Blocks with upgrade magento option

### Actual result
1. Http 500 error 
2. Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by magento-engcom-team** [comment]
Hi @happydownload33. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@happydownload33 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @happydownload33 seems like this is your environment problem, check configuration osf apache.

**Comment by happydownload33** [comment]
Hi @engcom-backlog-nazar thanks for your fast message,

i have 2 servers a Testserver and a Production server hosted by a external company both gives the same issue which gives a 500 error.

With Magento 2.2.3 i didn`t have the issue.

**Comment by ghost** [comment]
Hi @happydownload33 very strange I'm  not able to reproduce, i'm trying with several times, but have no 500 error, this seems really problem in environment, Maybe some config option do this.

**Comment by ghost** [comment]
@happydownload33 Did you use CE version ?

**Comment by happydownload33** [comment]
@engcom-backlog-nazar 

Some update from my side : 

We use Version 2.2.6 CE my webhoster helps me fixed the problem.


-------------------------------------------------

We getting the error in the logs
[25-Sep-2018 08:32:39 UTC] PHP Fatal error: Uncaught Exception: Warning: ini_set(): Cannot find save handler 'db' in /home/site/public_html/vendor/magento/framework/Session/SessionManager.php on line 563 


--------------------------------------------------

the solution is changed file app/etc/env.php from: 

'session' => [ 
'save' => 'db' 

To : 

'session' => [ 
'save' => 'files ' 

Is this a new required option in magento open source 2.2.6?

**Comment by happydownload33** [comment]
@engcom-backlog-nazar

Have a test with a clean install yesterday on my Testserver with magento 2.2.6 and see it also works.

looks just now on app/etc/env.php there and see also there is filling

'session' => [
        'save' => 'files'

Reproduced on 2.2.6 to change it to db and 500 error is appears.

Not standing in the magento release log that this is changed.

**Comment by ghost** [comment]
@happydownload33 Nice! I can reproduce this :)
![selection_130](https://user-images.githubusercontent.com/40756439/46013725-c1fdc180-c0d5-11e8-98ee-5cd9e840f0f2.png)

**Comment by ghost** [comment]
@happydownload33 Thank you for you report the fix for this issue has already available in 2.3-develop branch
