### ISSUE TITLE
In Developer Mode: Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed.

### ISSUE THREAD

**Issue by Mukipun** [magento/magento2#18193]
Preconditions

1. Version Magento2 2.2.6
2. Occurred after update from 2.2.5

Steps to reproduce

1. Set mode to developer
2. Click a categroy in frontstore

Expected result

1. 1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed.
Line: 919
Element 'referenceBlock', attribute 'as': The attribute 'as' is not allowed.
Line: 919
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'class': The attribute 'class' is not allowed.
Line: 919
[log.txt](https://github.com/magento/magento2/files/2407695/log.txt)
Element 'referenceBlock', attribute 'as': The attribute 'as' is not allowed.
Line: 919
2.

### Actual result

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
Hi @Mukipun. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Mukipun do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Mukipun** [comment]
Have no vanilla Instance. Will check it.

**Comment by DanielRuf** [comment]
This is probably an issue in one of your xml files as you can not use `class` on `referenceBlock`. Please check your theme.

**Comment by DanielRuf** [comment]
https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/layouts/xml-instructions.html

**Comment by Mukipun** [comment]
Thank you much. 
My Solution: Delete Attribute "class" and "as" in /vendor/creativestyle/frontend-extension/view/frontend/layout/catalog_category_view.xml and it works so far without side effect :)
