### ISSUE TITLE
2.2.6 update failure

### ISSUE THREAD

**Issue by waymanxie** [magento/magento2#18194]
### Preconditions

1. 2.2.5 working fine
2. update from 2.2.5 to 2.2.6

### Steps to reproduce

1. Step by step following the update progress 
2.

### Expected result

1. update to 2.2.6 successfully
2.

### Actual result

1. update failed
2. then i click the "Rollback" button to roll back. unfortunately the roll back failed again.
3. now i visit my store, it just says "An error has happened during application run. See exception log for details. Could not write error message to log. Please use developer mode to see the message."

here i attached the Console log below.
[Update console log.txt](https://github.com/magento/magento2/files/2407845/Update.console.log.txt)

**Comment by magento-engcom-team** [comment]
Hi @waymanxie. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@waymanxie do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by waymanxie** [comment]
@magento-engcom-team give me $VERSION instance

**Comment by waymanxie** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @waymanxie. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @waymanxie, here is your [Magento instance](https://i-18194-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18194-2-2-5.engcom.dev.magento.com/admin](https://i-18194-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by waymanxie** [comment]
no

**Comment by waymanxie** [comment]
no, i can't reproduce this issue cause the setup page is not working at all.
![image](https://user-images.githubusercontent.com/41362735/45918594-e8e0ab80-bebb-11e8-8916-cc3ccbcc5406.png)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @waymanxie Seems like problem in you generated folders, try to clean,  Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
