### ISSUE TITLE
Not all address details are shown in checkout step 2

### ISSUE THREAD

**Issue by Rickertje** [magento/magento2#18190]
### Preconditions
1. 2.2.5

### Steps to reproduce
1. Add product to cart
2. Proceed to checkout
3. Enter shipping address. See attached image.
![afbeelding](https://user-images.githubusercontent.com/27420995/45908010-b7ec7200-bdfa-11e8-8720-b14e893cda70.png)
4. Go to step 2

### Expected result
1. All entered address details of the shipping and billing address are shown

### Actual result
1. Not all address details are shown which can make a customer wonder if he made a mistake. Company, VAT number, fax are missing. see attached image.
![afbeelding](https://user-images.githubusercontent.com/27420995/45907957-81aef280-bdfa-11e8-92e5-fe69c1674606.png)

**Comment by magento-engcom-team** [comment]
Hi @Rickertje. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Rickertje do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
HI @Rickertje  this is expected behavior, It will be processed faster if you move this to https://github.com/magento/community-features

Best regards!

**Comment by Rickertje** [comment]
@engcom-backlog-nazar I dont think this is expected behavior. I expect M2 to work in a logical and professional way with at least an avarage level of feedback to customers. Especially in the checkout process. But on quite a list of occasions even the most basic things dont work properly in Magento. Why should a customer go back to the Shipping details to check if he really forgot to fill out the company name ?? I dont understand why I should create feature requests for basic things like this, sorry. But ok if this is the procedure I will go ahead.
