### ISSUE TITLE
Creating customer new address in checkout and updating customer address in checkout  is breaking the sequence of address in my account when address has 4 lines as 'street','number','reference' and  'neighborhood'  

### ISSUE THREAD

**Issue by mahsn** [magento/magento2#18195]
### Preconditions

Magento 2.4-develop

### Steps to reproduce

**On clean 2.4-develop**
1.Go to  Stores -> Configuration->Customers->Customer Configuration->Name and Address Options->Number of Lines in a Street Address
2.Define 'Lines Count'   as 4  
3.Register customer 
4.Go to customer Address Book
5.Fill all required fields
6.Fill first and last field in Street Address section
7.Click Save Address
8.Check saved address: 
:heavy_check_mark: in Street Address section first and last fields are filled
![image](https://user-images.githubusercontent.com/51681379/72714092-cf667700-3b76-11ea-9f2d-3ae724c22c0c.png)
9.Click New Address
10.Add product to cart
11.Go to checkout page
12.Fill all required fields
13.Fill first and last field in Street Address section
![image](https://user-images.githubusercontent.com/51681379/72714266-1c4a4d80-3b77-11ea-86b2-b23a7afa5660.png)
14.Click Ship here
15.Place order
16.Go to customer Address Book
17.Check last added address

### Expected result
In Street Address section first and last fields are filled

### Actual result
In Street Address section first and second fields are filled
![image](https://user-images.githubusercontent.com/51681379/72714826-1012c000-3b78-11ea-865e-4b74e7b8e382.png)

**Original Steps to reproduce:**
1.Go to  Stores -> Configuration->Customers->Customer Configuration->Name and Address Options->Number of Lines in a Street Address
2.Define 'Lines Count'   as 4  
3.This lines are  street, number, reference and neighborhood
4.Street, number and neighborhood are required fields, reference is optional
![addressissue](https://user-images.githubusercontent.com/8084683/45951283-44ed2200-bfd9-11e8-8936-41658edbec06.png)

Expected result

1.The reference field is optional, therefore the clients don't have to define this field, but although this field is not defined, the value of field should be saved in database as empty  
2.The sequence of address should be like 'street', 'number', ' refenrence [ but empty if it is not defined]', and ' neighborhood'.
![expectedresult](https://user-images.githubusercontent.com/8084683/45918333-d040a900-be5b-11e8-8c94-9303acd366dd.png)

Actual result

1. When the reference field is not defined , the value of neighborhood is saving in field of reference 

![actualresult](https://user-images.githubusercontent.com/8084683/45918336-d6cf2080-be5b-11e8-86fe-4917b7098958.png)

We already debug this issue, see that the new-customer-address.js  in module-checkout/view/frontend/web/js/model/new-customer-address.js is breaking the sequence of address
The line  ' street: addressData.street ? _.compact(addressData.street) : addressData.street, ',  this method of JS _.compact is removing the empty fields from array of address.
https://underscorejs.org/#compact

compact_.compact(list) 
Returns a copy of the list with all falsy values removed. In JavaScript, false, null, 0, "", undefined and NaN are all falsy.

_.compact([0, 1, false, 2, '', 3]);
=> [1, 2, 3]

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mahsn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by mahsn** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nickolas. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
@mahsn Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please label this ticket with `"acknowledged"` again.
Thanks!

**Comment by mahsn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [Magento instance](https://i-18195-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18195-2-3-develop.engcom.dev.magento.com/admin](https://i-18195-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahsn** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [Magento instance](https://i-18195-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-18195-2-2-develop.engcom.dev.magento.com/admin](https://i-18195-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@mahsn Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please label this ticket with `"acknowledged"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@mahsn Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95202`, `MAGETWO-95203` were created

**Comment by wbeltranc** [comment]
#mm18mx

**Comment by wbeltranc** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ingbeltran. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ingbeltran, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18195-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18195-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18195-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by wbeltranc** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ingbeltran. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ingbeltran, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18195-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18195-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18195-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @slavvka. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ericflemes** [comment]
hello everyone, i created a patch to correct this for hour. Follow below.
https://github.com/ericflemes/magento2/tree/compact/patches

**Comment by magento-engcom-team** [comment]
Hi @mahsn, @rodrigowebjump, @mahsn, @slavvka, @engcom-backlog-nickolas. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-95202` was closed as `non-reproducible` in `2.2.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by mahsn** [comment]
@magento-engcom-team give me $VERSION instance

**Comment by mahsn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [Magento instance](https://i-18195-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-18195-2-3-develop.instances.magento-community.engineering/admin](https://i-18195-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-24577` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
