### ISSUE TITLE
Backend issue : "ratings isn't  available" website wise

### ISSUE THREAD

**Issue by hardik-krish** [magento/magento2#18192]
**Preconditions**
1. Magento 2.2.4 installed with sample data.
2. Created 2 website (French and German) apart from Default (English).
 
**Steps to reproduce**
1. Added review and ratings for English,German and France website products from storefront as Guest user and login user.
2. Login into Backend.
3. Go to Marketing -> User Content -> Reviews.
4. Edit review of English which is main website it is showing summry ratings.
5. Edit review of other website but it is showing  "ratings isn't  available".
6. Approved that reviews for each website.
7. Checked Storefront products its showing ratings summary in each website. 

 **Expected result**

1. Backend it must be show ratings summary in each website reviews.
2.
![excpected-result](https://user-images.githubusercontent.com/17062703/45915975-fbd38b80-be7b-11e8-97ef-24c14d558520.jpg)

 **Actual result**
1. Its showing "ratings isn't  available" apart from main website reviews.
![review](https://user-images.githubusercontent.com/17062703/45915979-04c45d00-be7c-11e8-8709-86b7c3fde50a.jpg)

**Comment by magento-engcom-team** [comment]
Hi @hardik-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hardik-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `acknowledged` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95195`, `MAGETWO-95196` were created

**Comment by magento-engcom-team** [comment]
Hi @jaimin-ktpl. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sidolov** [comment]
Hi @hardik-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#18888 by @saphaljha in 2.3-develop branch
Related commit(s):
 - [1c820bef8e6c793b3fb3e8dcfa996bef60dd7c1f](https://github.com/magento/magento2/commit/1c820bef8e6c793b3fb3e8dcfa996bef60dd7c1f)
 - [8ea303b63a8e4afd7a46e53b3369afdccb4e063f](https://github.com/magento/magento2/commit/8ea303b63a8e4afd7a46e53b3369afdccb4e063f)
 - [cd243969b796e658edd844a3fe91d43cb308f72a](https://github.com/magento/magento2/commit/cd243969b796e658edd844a3fe91d43cb308f72a)
 - [cbbaf120f228d4499bdb7ead40a26f6a2f1c2330](https://github.com/magento/magento2/commit/cbbaf120f228d4499bdb7ead40a26f6a2f1c2330)
 - [611969d9a56905613aefb981c8cd4be7efc24330](https://github.com/magento/magento2/commit/611969d9a56905613aefb981c8cd4be7efc24330)
 - [774164c2ae589e45fd3bdfcf09a6de4c6b0cba1a](https://github.com/magento/magento2/commit/774164c2ae589e45fd3bdfcf09a6de4c6b0cba1a)
 - [2ea37a87e250209d28d92b0987daddf068cfaf9c](https://github.com/magento/magento2/commit/2ea37a87e250209d28d92b0987daddf068cfaf9c)
 - [0e59e8c244463d74e7949bbb1710d13f1990537d](https://github.com/magento/magento2/commit/0e59e8c244463d74e7949bbb1710d13f1990537d)
 - [b9790c67d25af83e8cbaecad223c4317d4337e8d](https://github.com/magento/magento2/commit/b9790c67d25af83e8cbaecad223c4317d4337e8d)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @hardik-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#20183 by @saphaljha in 2.2-develop branch
Related commit(s):
 - [06443f99c0de046ac67f484709fe7be147b3e5df](https://github.com/magento/magento2/commit/06443f99c0de046ac67f484709fe7be147b3e5df)
 - [cb6ff7e15ae0488eda823194e2d931e200352a92](https://github.com/magento/magento2/commit/cb6ff7e15ae0488eda823194e2d931e200352a92)
 - [56a0f117de65f279d1404212858e16d46bc8288f](https://github.com/magento/magento2/commit/56a0f117de65f279d1404212858e16d46bc8288f)
 - [9c593568dae87bae3de2d52acf3e50d59f16e48c](https://github.com/magento/magento2/commit/9c593568dae87bae3de2d52acf3e50d59f16e48c)
 - [fd4dd390f0b03477d46011890c2e35457a384cb2](https://github.com/magento/magento2/commit/fd4dd390f0b03477d46011890c2e35457a384cb2)
 - [a26b9bd41de62c2665f756555c6d64440208ac30](https://github.com/magento/magento2/commit/a26b9bd41de62c2665f756555c6d64440208ac30)
 - [30a6d5af9d488b506441a66821b955cebd3b1933](https://github.com/magento/magento2/commit/30a6d5af9d488b506441a66821b955cebd3b1933)

The fix will be available with the upcoming 2.2.8 release.

**Comment by parekhreena** [comment]
@magento-engcom-team  This issue returned back in Magento CE 2.3.4
