### ISSUE TITLE
Wrong currency assigned after changing storeId by StoreCookieManager

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#18216]
### Summary

I've tried to create a website switcher. So basically there is 1 website (1 URL) but it has 4 different stores and 4 different currencies. A product price in each currency is a fixed value, it is not calculated by exchange rates that is why we need 4 website setup since Magento 2 does not allow prices per store view. 

I've created an observer on `controller_action_predispatch` event
and I change the storeId as this:
```
/**
     * @param EventObserver $observer
     * @return $this|void
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     * @throws \Magento\Store\Model\StoreIsInactiveException
     */
    public function execute(EventObserver $observer)
    {
        $store = $this->storeRepository->getActiveStoreById(2);
        $this->storeCookieManager->setStoreCookie($store);
        return $this;
    }
```

StoreID = 2 has EURO currency configured as base currency while storeID = 1 has US dollars.

### Steps to reproduce

1. Magento 2.2.5 CE
2. Create observer which will change storeId  (by storeCookieManager)

### Expected result

1. Proper store_view assigned
2. Currency visibiel on the frontend should be switched to website assigned one (based on storeId)

### Actual result

1. Cookie "store" has good value, but
2. frontend website ID does not change
3. currency does not switch to website assigned one

### Source of the problem:
In the class `\Magento\Store\Model\StoreResolver` in method `getCurrentStoreId()` system only fetches storeIds assigned to a loaded website, it does not load all store views.

**Comment by magento-engcom-team** [comment]
Hi @qsolutions-pl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@qsolutions-pl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @qsolutions-pl, thank you for you report, please add the -> Preconditions

**Comment by ghost** [comment]
Hi @qsolutions-pl Try to use setCurrentCurrencyCode(), in my case this works, if you like to update this, please reopen the issue. 
```
 $store = $this->storeRepository->getActiveStoreByCode('YOUR_STORE_CODE');
    $this->httpContext->setValue(Store::ENTITY, 'YOUR_STORE_CODE', 'DEFAULT_STORE_CODE');
    $this->storeCookieManager->setStoreCookie($store);
```

**Comment by jakwinkler** [comment]
@engcom-backlog-nazar currency code works, but the website ID is still wrong **during** first page load.
So even if I set EUR price = 199 and USD price = 259, price visible on the frontend will by 259 EUR because the website ID does not change.

Cookie is set during page load, so the website still uses old store cookie during page page load.
If you refresh page again, you will have correct price and currency, but the whole point of this task is to create website switcher.
