### ISSUE TITLE
Advanced Pricing on Multisite environment not saving

### ISSUE THREAD

**Issue by Sharpy310** [magento/magento2#18218]
### Preconditions

Magento CE 2.2.6
PHP v7.1.19-1
Ubuntu 17.10

### Steps to reproduce

1. Install vanilla Magento 2.2.6 instance
2. Enable a customer group to have special pricing on it, for sake of example lets call name it "wholesale" pricing
3. Enable a multi-site environment so that both websites will use the same product, lets call them "website 1" and "website 2"
4. On website 2, create a special price for the wholesale group on the Advance Pricing window, and save the product.

### Expected result

1. Special Price for multisite saves correctly and is served to customers according to customer groups.

### Actual result

1. Result saves in correctly, but a second record is created automatically with the same price as the wholesale group, but is set to "All websites" and as the "General" customer group as per image below:
2. Additionally, when this does happen and the product is saved again, it throws a Unique constraint violation error (img below) - the fix for this is to delete the record that was entered automatically and re-save, however on the re-save it will re-generate the record.

[Top entry entered automatically]
![4d08589f03f71b23d8bf7621037](https://user-images.githubusercontent.com/17251496/45946380-a8cb1700-bfe8-11e8-9481-ee61c0e7b4db.jpg)

[On product re-save]
![cf669307310ca6677d1ace3f3b46b070](https://user-images.githubusercontent.com/17251496/45946401-b84a6000-bfe8-11e8-85d5-37b4f39044b0.png)

**Comment by magento-engcom-team** [comment]
Hi @Sharpy310. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Sharpy310 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Sharpy310** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Sharpy310. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sharpy310, here is your [Magento instance](https://i-18218-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18218-2-2-6.engcom.dev.magento.com/admin](https://i-18218-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by Sharpy310** [comment]
@engcom-backlog-nazar I have replicated this issue on the test instance, please note you also need to set the product price scope to "Websites" in the configuration to replicate this issue.

**Comment by ghost** [comment]
Hi @Sharpy310 thank you for you report, seems like this is duplicate for this -> https://github.com/magento/magento2/issues/18154 isnt it ?

**Comment by ghost** [comment]
@Sharpy310 I'm closing this as duplicate, if you like to update this, please reopen the issue.

**Comment by Sharpy310** [comment]
@engcom-backlog-nazar My apologies, I believe it is the same issue - the only thing being is that it does also create a second record on the Advanced Pricing, should I add that as a note on the other issue or just leave it?

**Comment by ghost** [comment]
@Sharpy310 Yes shure add your opinion to the referenced issue, this will add insight to correct the issue
