### ISSUE TITLE
Configurable product don't change Price and Image based on Simple available

### ISSUE THREAD

**Issue by Raffoss** [magento/magento2#18214]
### Preconditions
 magento 2.2.4 (dev test upgrade) or magento 2.1.3(our actualy prod. )

 
### Steps to reproduce

Configurable product with configurable variations attribute: Color and size

Color: Red and green

size: small and large

4 simple sku:

sku0001 : Red Small T-shirt  : Set Price 10€ : Qnt 10

sku0002 : Red Large T-shirt : Set Price 20€ : Qnt 10

sku0003 : Green Small T-shirt : Set Price 15€ : Qnt 10

sku0004 : Green Large T-shirt: Set Price 20€ : Qnt 10

 

We import all the configuration by csv import and we setup the configurable image and price with 2 rules:

configurable image: the image of the simple product with the lower sku number

configurable price: the cheapest simple price 

In this example, the configurable have red t-shirt image and red t-shirt small price(10€)

 

To simplify the UX to our surfer, we disable simple product with our ERP integration when quantity is 0. So If the Red t-shirt goes out of stock like this:

 
sku0001 : Red Small T-shirt  : Set Price 10€ : Qnt 0

sku0002 : Red Large T-shirt : Set Price 20€ : Qnt 0

sku0003 : Green Small T-shirt : Set Price 15€ : Qnt 10

sku0004 : Green Large T-shirt: Set Price 20€ : Qnt 10

 
### Expected result
The configurable change image and price based on configuration available. In this case green image with sku0003 price.

### Actual result
The configurable maintain red t-shirt image and red small t-shirt price.

 

Magento give some configuration to make it easy?

 

I hope you can help us

 

Raffaello

**Comment by magento-engcom-team** [comment]
Hi @Raffoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Raffoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `G1 Passed` will be added to the issue automatically. Please, edit issue description if needed, until label `G1 Passed` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `G2 Passed` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `acknowledged` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report is acknowledged.

**Comment by ghost** [comment]
Hi @Raffoss thank your for you report, but if you set to Set Display Out of Stock Products to "no" they must be not displayed the products of qty 0.

**Comment by Raffoss** [comment]
Hi @engcom-backlog-nazar, thanks for your support!
Simple product with qty 0  they are disabled and not displayed correctly, but the configurable maintain the value of the simple product disabled.

**Comment by ghost** [comment]
@Raffoss Seems like this bug is acknowledged please see ->https://github.com/magento/magento2/issues/16069

**Comment by ghost** [comment]
@Raffoss  This issue is duplicate for this -> https://github.com/magento/magento2/issues/12578 
This issue has already fixed in 2.3-develop branch.
