### ISSUE TITLE
After upgrade to Magento 2.2.6 Only Customers Grid stays empty

### ISSUE THREAD

**Issue by richardreen** [magento/magento2#18226]
After upgrade from Magento 2.2.5 to 2.2.6 the Customers Only grid stays empty even when here are several customers/guests online. 
Even a staging server with a initial install of 2.2.6 has this problem. 
we suspect that this is a bug in de 2.2.6 code.

### Preconditions

1. Magento 2.2.5 
or no install present

### Steps to reproduce
Perform a update from 2.2.5 to 2.2.6 as described in the manual.
or
a clean install of a new M 2.2.6

### Expected result
With several customers or guest online we suspect to see their last activity in the onlline customers grid.page.

### Actual result
Screen stays empty and finds 0 records. See also screenshot below

![screenshot_20180924_153505](https://user-images.githubusercontent.com/18627705/45955427-29513e00-c010-11e8-959a-8c9a0f5ef86d.png)

**Comment by magento-engcom-team** [comment]
Hi @richardreen. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@richardreen do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by richardreen** [comment]
It is on version tag 2.2.6,
Yes we have also repoduced it on a fresh install of Magento 2.2.6

**Comment by tomekjordan** [comment]
Fix the bug title, its misleading

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @richardreen the fix for this issue has already available in 2.3-develop and 2.2-develop branch

**Comment by Ctucker9233** [comment]
@engcom-backlog-nazar That's great. It would help if commits were linked.
