### ISSUE TITLE
Product Import -> Upsert Category: Url Rewrites are just created for default website

### ISSUE THREAD

**Issue by ulftietze** [magento/magento2#18234]
### Preconditions

1. Magento 2.2.X
2. PHP 7
3. At least two websites

### Steps to reproduce

1. Create a CSV with Product Information which includes Category String
2. Category String Contains Category which does not exists so Magento does an "upsertCategory" internally

### Expected result

1. Magento creates URL Rewrites for all websites

### Actual result

1. Magento just create the URL-Rewrite for default website scope.

**Comment by magento-engcom-team** [comment]
Hi @ulftietze. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ulftietze do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @ulftietze I'm not able to reproduce steps you described, can you show your csv file ?

**Comment by ulftietze** [comment]
I can provide some more information about:

sku | categories | name | price | url_key | product_websites | attribute_set_code
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- 
123456789 | Default Category/Existing Category,Default Category/Existing Category/NotExisting Test | Test Produkt | 420 | custom-url-key-for-product-123456789 | de,at | default

Hope you can reproduce now

**Comment by BarnyShergold** [comment]
I have found there was a small patch being included during our build process that was causing the issue - it was created to solved some 2.2.6 build problems in Jenkins.

After reversing this patch the deadlock cleared. I am satisfied that the specific issue reported here is not caused by Core Magento.

**Comment by BarnyShergold** [comment]
Apologies two issues got confused on browser

**Comment by ulftietze** [comment]
@BarnyShergold i accept your apologize if you also can reproduce this issue :laughing:

**Comment by ghost** [comment]
@ulftietze Seem like this already fixed in 2.3-develop branch. I was testing this, and import generate url rewrites to both websites
![selection_132](https://user-images.githubusercontent.com/40756439/46016532-b6ae9400-c0dd-11e8-8458-a0b7b8687eaa.png)
![selection_131](https://user-images.githubusercontent.com/40756439/46016533-b6ae9400-c0dd-11e8-99f9-e08ca9d6a26c.png)

**Comment by ulftietze** [comment]
Hey @engcom-backlog-nazar :)

Ok nice, that this could be fixed in 2.3
But i'm not talking about the product url rewrites. I'm talking about the **category url rewrites**.
Testing with the newest Magento 2.2 Version, this isn't fixed, and as i can see in code, it shouldn't be fixed in 2.3 as well. (I does not have a running instance of Magento 2.3, maybe i get one later)

The product URL Rewrites are working fine like a charm, but the category URL Rewrites, which are created are just created for one of the StoreViews.

This happens because of the class:
`Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteSavingObserver::execute();`
This function is an observer of the category save action, which is also called during import, if you give some category path which does not exist.
So after this some magic is happening in:
`Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator::generate()`
This function makes a lookup for `$storeId = $category->getStoreId(); `in line 98.
The problem in here is: The StoreId isn't set and if it's not set, the storemanager is called and loads the scope for default store website.
And one to another: This is no global scope and the generation for the global scope isn't triggered, just for the default website scope.

And as long i didn't see something fixed in 2.3 in code, which could change something in this behavior, we shouldn't close this issue.

Thanks and greetz,
Ulf

**Comment by ghost** [comment]
@ulftietze Ok, but in my screen category have Url rewrite with gear ? or i miss something

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95255`, `MAGETWO-95256` were created

**Comment by ghost** [comment]
@ulftietze Sorry now clear, I'm confused with url rewrites :)

**Comment by ulftietze** [comment]
@engcom-backlog-nazar no problem :D 
I'm confused a little as well :)
Maybe i should have been more clearly in my report description.

Thanks for creating internally tickets.

**Comment by sidolov** [comment]
Hi @ulftietze. Thank you for your report. 
The issue has been fixed in magento/magento2#18271 by @ulftietze in 2.3-develop branch
Related commit(s):
 - [53a34562ae6aeab152cee9c9ac240bcb7259c2ff](https://github.com/magento/magento2/commit/53a34562ae6aeab152cee9c9ac240bcb7259c2ff)
 - [543fce4f671377309d68bc0132c33a0000342493](https://github.com/magento/magento2/commit/543fce4f671377309d68bc0132c33a0000342493)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @ulftietze. Thank you for your report. 
The issue has been fixed in magento/magento2#18563 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [e2f89c8543ca3461538f36cfb0f428ef9d502f66](https://github.com/magento/magento2/commit/e2f89c8543ca3461538f36cfb0f428ef9d502f66)
 - [4ad4849565650f1ddf77164b901afb42adbfa571](https://github.com/magento/magento2/commit/4ad4849565650f1ddf77164b901afb42adbfa571)

The fix will be available with the upcoming 2.2.8 release.

**Comment by jwundrak** [comment]
@ulftietze @magento-engcom-team 

Can we please reopen the ticket? In v2.2 the fix with $category->setStoreId(0) is in the git, but in >= v2.3.1 this commit: https://github.com/magento/magento2/commit/795bc1f0f449e1e599586bf42525d5c088cfbae2#diff-27c2b5f302ec1a16c88e3efbfaa54e59 revert this fix.
