### ISSUE TITLE
Can't create new order in admin when using multiple store views

### ISSUE THREAD

**Issue by pjw345** [magento/magento2#18235]
### Preconditions

1. Magento 2.2.6
2. PHP 7.0.32

### Steps to reproduce

1. Create second store view, first store view en_GB, second store view es_ES
2. Install language packs from crowdin.com/project/magento-2
3. Create a customer group for example Wholesale
4. Create an order from existing customer using Main Website Store en_GB

### Expected result

1. Expect to see Create New Order screen with Add products, etc
2. Please refer to screenshot
![capture1](https://user-images.githubusercontent.com/24723606/46009697-43465b80-c0b8-11e8-89ee-4da1f4142202.PNG)

### Actual result

1. Error 500 -  .../sales/order_create/loadBlock/key/.../block/header,data?isAjax=true 500
2. Form doesn't load
![capture2](https://user-images.githubusercontent.com/24723606/46009718-4a6d6980-c0b8-11e8-870b-7e75e11aef57.PNG)

3. Previously raised on issue 9997, but issue was closed.

**Comment by magento-engcom-team** [comment]
Hi @pjw345. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pjw345 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @pjw345 I'm not able to reproduce following steps you described. see attachments
![selection_128](https://user-images.githubusercontent.com/40756439/46011227-e5247300-c0cd-11e8-9cba-ab5621edfccd.png)

**Comment by pjw345** [comment]
Note:  Create customer group, here you are using customer group General, did you create a new customer group and a customer for that group?

**Comment by ghost** [comment]
@pjw345  Yes

**Comment by pjw345** [comment]
Your screen shot shows you are using a customer from the group General and not from another Customer Group

**Comment by ghost** [comment]
@pjw345  Same result, and in your screenshot you have general group.
![selection_129](https://user-images.githubusercontent.com/40756439/46012175-05096600-c0d1-11e8-9bd7-f355da94ae32.png)

**Comment by pjw345** [comment]
I am currently in the process of trying to debug what might be causing the issue, I've checked the header block and thought perhaps it was because it couldn't get the customer name or store name 

Magento\Sales\Block\Adminhtml\Order\Create\Header

and that appears to be working ok,

now looking where it could be failing in 
vendor\magento\module-sales\view\adminhtml\templates\order\create\data.phtml

and there are few places it could be going wrong, but either way I still have the issue.  Not sure if it's currency related, store related.

**Comment by pjw345** [comment]
You are correct in the screenshot it shows as a General customer, but the customer I selected was actually a Wholesale customer

**Comment by pjw345** [comment]
Checking the error logs and the timing I think it might actually be a Klarna issue

Missing required attribute(s) on create: "purchase_currency, orderlines". {"exception":"[object] (Klarna\\Core\\Model\\Api\\Exception(code: 0): Missing required attribute(s) on create: \"purchase_currency, orderlines\". at ...vendor/klarna/module-kp/Model/Api/Request/Builder.php:293)"}

**Comment by ghost** [comment]
@pjw345  Thank you, that you posted log file, now clear.

**Comment by pjw345** [comment]
I can confirm disabling the Klarna modules removes the exception, but the Error 500 remains

**Comment by pjw345** [comment]
And I can confirm 
sales/order_create/loadBlock/key/.../block/header?isAjax=true works OK
sales/order_create/loadBlock/key/.../block/data?isAjax=true - generates and error 500

**Comment by pjw345** [comment]
Turned on error reporting in bootstrap.php and the error returned is a failure to get a custom attribute from the customer data model

Call to undefined method Magento\Customer\Model\Data\Customer::getCreditLimit() 

This attribute is shown on the customer screen and added via the data migration process.  So strictly speaking this isn't a vanilla installation, but a clean Magento 2 installation with migrated data into it.   

Question remains, if the attribute is displayed via the customer screen why can the Order create form not get it?  Will have to look at the way data is retrieved.

If anything I hope this helps others when debugging Magento issues.
