### ISSUE TITLE
Add the adminhtml_customer option to Admin Customer Attributes - Forms to Use In - list

### ISSUE THREAD

**Issue by radub** [magento/magento2#18233]
### Summary

Crating feature request instead of issue reporting: https://github.com/magento/magento2/issues/18232

I have programatically created a customer attribute and set it to be displayed in **adminhtml_customer**. All is good, the attribute is being displayed only in the admin customer edit section as desired.
```
$attributeCode = 'attribute_code';

$eavSetup->addAttribute(Customer::ENTITY, $attributeCode,
    [
        'type'          => 'varchar',
        'label'         => 'Attribute Lable',
        'input'         => 'multiselect',
        'backend'       => \Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend::class,
        'global'        => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
        'source'        => \Magento\Eav\Model\Entity\Attribute\Source\Table::class,
        'visible'       => true,
        'user_defined'  => true,
        'system'        => false,
        'required'      => false,
        'unique'        => false,
        'position'      => 200
    ]
);

$attribute = $this->eavConfig->getAttribute(Customer::ENTITY, $attributeCode);

$attribute
    ->setData('used_in_forms', ['adminhtml_customer'])
    ->save();
```
However, when I try to edit the attribute in the Admin (Store/Attributes/Customer) - let's say I want to make it show in another area - the **adminhtml_customer** option is not available for selection in the _Forms to Use In_ list.

<img width="1019" alt="forms-to-use-in" src="https://user-images.githubusercontent.com/60108/46001938-4be96280-c0b5-11e8-9104-6411c2124c96.png">

### Examples
Looking through the code I found the following:
> \Magento\CustomerCustomAttributes\Helper\Customer::getAttributeFormOptions
```
/**
 * Return available customer attribute form as select options
 *
 * @return array
 */
public function getAttributeFormOptions()
{
    return [
        ['label' => __('Customer Registration'), 'value' => 'customer_account_create'],
        ['label' => __('Customer Account Edit'), 'value' => 'customer_account_edit'],
        ['label' => __('Admin Checkout'), 'value' => 'adminhtml_checkout']
    ];
}
```
adminhtml_customer is missing.

### Proposed solution
Since **adminhtml_customer** is a Magento 2 out of the box option, as long as this option is available for BE development, I would expect it to be available for selection in the _Forms to Use In_ as well.

**Comment by magento-engcom-team** [comment]
Hi @radub. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@radub do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by radub** [comment]
yes

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @radub Thank you for you report, Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
