### ISSUE TITLE
Removing 85.000 products from backend takes 28 hours!

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1823]
We've added 85000 products with rest, this takes 14 hours. This seems fair because of a request for each product. But when we remove the products all at once in the backend, it takes 28 hours!!

**Comment by kandy** [comment]
First of all, better to use indexation on schedule for this case. 
Second, in your case better to use import functionality that was optimized for mass update.

**Comment by rklerck** [comment]
Use import functionality for mass delete? We don't really care import takes this long, it's the initial load..

**Comment by vrann** [comment]
@rklerck hi, can you please confirm that you use "reindex on schedule" for all the indexers related to catalog?

**Comment by rklerck** [comment]
Tried that, ended up with https://github.com/magento/magento2/issues/1833

**Comment by pboisvert** [comment]
@choukalos Chuck--i see your reference to a closed issue. Can you take a look at this one and reassign as needed?

**Comment by acidreian666** [comment]
+1 @rklerck I have been attempting to add 180,000 products via Csv.. only success is to break up the file into 60k products in each csv file. Then to remove them via select All products then "Delete" Takes like you said almost days.. the Feature for importing Products for Magento2 is a Fail. Magmi was there to save the day for Magento 1.9 and you would think they would have Fixed the Product Add/Remove & Import/Export to be blazing fast and flawless..

4 core processor
8gb ram
ubuntu 16.04
php 7.0.8
nginx
percona xtradb 5.7

Slower then usable on a local computer for development.

**Comment by choukalos** [comment]
Hi @rklerck 

What version of Magento are you using?
Did you use REST API to delete the entire catalog ( i.e. all 85k products )?  
Is your use case the need to delete the entire catalog quickly - for what reason?  Is this a merchant use case, why?
Do you have merchant use cases where you'd only want to delete portions of the catalog?  What time to do so would you expect?

Thanks,
Chuck

**Comment by acidreian666** [comment]
@choukalos 
Having similar issues with my large product database also. Magento 2.1 is unable to import more then 95000 products at a time if it don't fail already because it says the "URL already exists" and it ends with importing 66k of the 95k list of products then breaks the indexing ability.

Then like @rklerck says Mass Delete function for me i have let run for 3 days to delete over 85k products at once because they imported and had missing data causing an Segmentation Core error while indexing keywords.

Magmi for 1.92 was amazing at importing/updating products but this isn't an option for magento 2.x
imagine having a perfect Database CSV file made with 180k products then using magento 2.x OEM import tool and it fails everytime.

to compare to what ever @rklerck server is mine is.
Magento 2.1
ubuntu 16.04 php7.08 Nginx mysql5.7
4 core cpu 24gb ram
mysql and php both tuned to use high amounts of memory
execution times = umlimited

result = magento 2.x needs Magmi style import/update/delete system.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Removing-85-000-products-from-backend-takes-28-hours/idi-p/45798).
