### ISSUE TITLE
Cosmetic display issue - Order / Account Information

### ISSUE THREAD

**Issue by pjw345** [magento/magento2#18237]
### Preconditions

1. Magento 2.2.6
2. PHP 7.0.32

### Steps to reproduce

1. Display a sales order that has been created in a currency other than the base currency
2.

### Expected result

1. Exchange rate should be displayed in the Order / Account Information
![capture](https://user-images.githubusercontent.com/24723606/46010540-f0ba6e80-c0ba-11e8-95fe-db535c630b96.PNG)

### Actual result

1. Exchange rate is not correctly aligned with the rest of the data in the table
2. Current code:
`               ```
 ```
<?php if ($order->getBaseCurrencyCode() != $order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $order->getOrderCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                        <th><?= $block->escapeHtml($order->getBaseToOrderRate()) ?></th>
                    </tr>
                <?php endif; ?>
```
`
```
I believe the second <th> should be a <td> instead, easily fixed

`           ```
     <?php if ($order->getBaseCurrencyCode() != $order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $order->getOrderCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                        <td><?= $block->escapeHtml($order->getBaseToOrderRate()) ?></td>
                    </tr>
                <?php endif; ?>
```
`
![capture3](https://user-images.githubusercontent.com/24723606/46010678-70e0d400-c0bb-11e8-80d9-4f386fb720b8.PNG)

**Comment by magento-engcom-team** [comment]
Hi @pjw345. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pjw345 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @pjw345, thank you for your report.
This is an expected behavior. And Exchange rate must be in this place.
