### ISSUE TITLE
Selections for bundle options of type checkbox are wrong on the wishlist

### ISSUE THREAD

**Issue by densen45** [magento/magento2#18240]
All selections of a bundle option of type checkbox that were checked once are added to the wishlist -- no matter if they were unchecked later, before the bundle is added to the wishlist.

### Preconditions

Magento 2.2.5
**Updated(09/19/2019):** Still actual on `2.3-develop`

### Steps to reproduce

1. Create a bundle product with at least one option of type checkbox
2. Add several (at least three) simple products to this option
3. Access the bundle product on frontend
4. Select and again deselect some of the checkbox options' selections
5. Add the bundle product to your wishlist

### Expected result

1. The selections of the bundle product on the wishlist match the previously chosen ones
2. Selection that I have unchecked again are not listed

### Actual result

1. Every selection of a checkbox option that you have checked at least once, no matter if you have unchecked it later, is listed for the wishlist bundle

### Investigations so far

1. The Magento\Wishlist\Controller\Index\Add already receives the wrong selection values.
2. Everytime a selection or a quantity is changed, the function _updateAddToWishlistButton(dataToAdd) from add-to-wishlist.js is called: https://github.com/magento/magento2/blob/5c82b225c700436ab0f14ad281b025fb0e75b3ad/app/code/Magento/Wishlist/view/frontend/web/js/add-to-wishlist.js#L103 Inside this function params.data is extended with the given dataToAdd. Since it is only extended, the properties for deselected selections are never removed.

**Comment by magento-engcom-team** [comment]
Hi @densen45. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@densen45 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by densen45** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @densen45. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @densen45, here is your [Magento instance](https://i-18240-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18240-2-2-5.engcom.dev.magento.com/admin](https://i-18240-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by densen45** [comment]
@magento-engcom-team @engcom-backlog-nazar
I was able to reproduce the issue on the provided vanilla Magento instance

Please, see attached image. I had selected the first two selections and deselected them again, but they are still added to the post data of the add to wishlist button, and so, they will be listed on the wishlist.

![issue-18240-001](https://user-images.githubusercontent.com/3801001/46021754-9bde1e80-c0e1-11e8-96c9-622d75f8c72b.png)

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95245`, `MAGETWO-95246` were created

**Comment by magento-engcom-team** [comment]
Hi @jaimin-ktpl. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by dhirenvasoya** [comment]
I will work on this #mm19in

**Comment by vass30** [comment]
@magento I am working on this

**Comment by vass30** [comment]
@magento add to contributors team

**Comment by engcom-Bravo** [comment]
Hi @densen45,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible and only elections of the bundle product on the wishlist match the previously chosen ones,Selection that I have unchecked again are not listed.

Hence We are Closing this issue.

Thanks.
