### ISSUE TITLE
Unable to add >50% of available product qty to order in admin panel

### ISSUE THREAD

**Issue by t-richards** [magento/magento2#18245]
### Preconditions

1. Magento 2.2.6, fresh install with all sample data
2. PHP 7.1.22
3. Apache 2.4.34

### Steps to reproduce

1. In the admin panel, select `Sales > Orders > Create New Order`.
2. Select the sample "Veronica Costello" customer.
3. Select "Add Products".
4. Locate the following sample product and fill in the quantity field:
 - SKU: `WSH12-32-Red`
 - Quantity: `51`
5. Select "Add Selected Product(s) to order"

### Expected result

1. 51 quantity of the desired product "Erika Running Short-32-Red" should be added to the order without error.
2. This operation should succeed without error because the product (like many products in the sample data set) starts with 100 in stock.

![expected-result](https://user-images.githubusercontent.com/3905798/46037158-64697500-c0d5-11e8-818f-acefd86bc1b6.png)

### Actual result

1. An error/notice message appears on the screen, saying
  > We don't have as many "Erika Running Short-32-Red" as you requested.
2. Due to the presence of the error message on the page, it is unclear to the admin user whether the product was successfully added to the order.

![actual-result-error](https://user-images.githubusercontent.com/3905798/46037146-5fa4c100-c0d5-11e8-9896-97dcaeaa55a4.png)

After tracing through the request, it appears that `Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList::getQty` is being improperly used. Either...

 - The function is being called too many times, or
 - The function is sometimes called with the wrong arguments

This causes the "checked" qty to double on line 39.
https://github.com/magento/magento2/blob/5c82b225c700436ab0f14ad281b025fb0e75b3ad/app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator/QuoteItemQtyList.php#L39

We should be checking whether there are 51 in stock, but we are actually checking whether there are 102 in stock.

**Comment by magento-engcom-team** [comment]
Hi @t-richards. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@t-richards do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by t-richards** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @t-richards. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @t-richards, here is your [Magento instance](https://i-18245-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18245-2-2-6.engcom.dev.magento.com/admin](https://i-18245-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by t-richards** [comment]
I can confirm that the issue is reproducible on the provided vanilla Magento instance. Here is a screen recording of this confirmation. (Click on the image to view full size)

![magento2-18245](https://user-images.githubusercontent.com/3905798/46038621-97156c80-c0d9-11e8-92e5-edf3a5a993f7.gif)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95240`, `MAGETWO-95241` were created

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh, here is your [Magento instance](https://i-18245-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18245-2-2-6.engcom.dev.magento.com/admin](https://i-18245-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jayankaghosh** [comment]
I am working on this

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by indefinitedevil** [comment]
I am working on this #squashtoberfest

**Comment by magento-engcom-team** [comment]
@indefinitedevil thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @indefinitedevil. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by indefinitedevil** [comment]
Not yet been able to track it back any further, but can verify a few things here:

1. This issue only happens when adding the product to the admin order initially
2. This issue does not happen when quantity is amended later (i.e. if you add 50, then add 1 more you do not get this error)
3. Also applicable with new customers
4. The getQty function is definitely called twice during this execution.
5. The event "sales_quote_item_qty_set_after" is being called twice when adding products to the admin order

My rough theory is that the "add to order" routine is running triggering the observer and then the "update order" is also triggering it.

This should be getting caught by the control check on it being the same item, but it seems that the first pass through isn't adding the quote item ID. Probably because it's just been added and hasn't had an ID generated yet.

And with that, I think I know exactly what the issue is. Will see if I can fix it.

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by keyurk-emipro** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro, here is your [Magento instance](https://i-18245-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-18245-2-3-develop.instances.magento-community.engineering/admin](https://i-18245-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Closed as cannot reproduce on the latest `2.4-develop` code.
But if you still faced the issue please create a new report for 2.4 with detailed steps
