### ISSUE TITLE
Clear bag does not work after upgrade to 2.2.6

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#18252]
### Preconditions
1. Magento 2.2.6 upgrade from 2.2.5
2. PHP 7.0.32
3. On both clean and custom theme with and without any 3rd party modules

### Steps to reproduce
1. Add something to cart
2. Go to cart page
3. Click on Clear bag button
4. First it will trigger spinner and then page is reloaded with products still in the cart
5. Try for couple of times and finally cart will be emptied

### Expected result
1. Cart to cleared on first click

### Actual result
1. Items stays in the cart

https://modche-gmail.tinytake.com/sf/Mjk0NzUwMF84ODQ2MTc4

**Comment by magento-engcom-team** [comment]
Hi @kerlama. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kerlama do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by kerlama** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @kerlama. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @kerlama, here is your [Magento instance](https://i-18252-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18252-2-2-6.engcom.dev.magento.com/admin](https://i-18252-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kerlama** [comment]
Hi,

I can confirm this is not happening on the vanilla 2.2.6. But still, I would like to hear others.

**Comment by ghost** [comment]
Hi @kerlama seem like problem in you custom theme, I'm not able to reproduce on 2.3-dev branch

**Comment by ghost** [comment]
@kerlama I'm closing this issue, if you like to update this or if someone in future have the same problem we can reopen this again. Thank you.
