### ISSUE TITLE
Unable to login or create account in magento 2.3 local setup

### ISSUE THREAD

**Issue by RamanMalhotra88** [magento/magento2#18250]
### Preconditions

1. Magento version 2.3 
2. Environment: Mac OS

### Steps to reproduce

We are facing issue while customer signup / sign-in in magento 2.3 local setup:

steps to reproduce:

1. created customer using rest api "POST /V1/customers" with below data:
{
  "customer": {
    "email": "test@test.com",
    "firstname": "test",
    "lastname": "test",
    "middlename": "test",
    "store_id": 1,
    "website_id": 1
  },
  "password": "test@123"
}
The api call creates user successfully as shown in below screenshot:
<img width="1680" alt="screen shot 2018-09-26 at 11 35 00 am" src="https://user-images.githubusercontent.com/7579467/46060468-1dd15480-c181-11e8-833c-f875aa0c0d40.png">

2. click on Signin on magento site.

3. enter credentials for above users and click login.

we have tried opening the site on incognito mode or delete all cookies. But still not working.
we have also tried following the steps mentioned in the post below, but with no luck. 
https://www.simicart.com/blog/magento-2-invalid-form-key/

### Expected result
1. User logs in successfully

### Actual result
following error is shown on page:
<img width="1674" alt="screen shot 2018-09-26 at 11 40 36 am" src="https://user-images.githubusercontent.com/7579467/46060444-0a25ee00-c181-11e8-9671-0db96abdf497.png">

**Comment by magento-engcom-team** [comment]
Hi @RamanMalhotra88. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@RamanMalhotra88 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @RamanMalhotra88  Did you try this url  /V1/all/customers or  /V1/default/customers ?
Seems like you dont set website for customer in url.

**Comment by ghost** [comment]
@RamanMalhotra88 In this url -> as a Swagger says /default/rest/all/V1/customers I'm create a customer and login successful, if you'd like to update this, please reopen th issue.
![selection_136](https://user-images.githubusercontent.com/40756439/46061423-43edf900-c16f-11e8-9ef2-ef686845b066.png)
![selection_135](https://user-images.githubusercontent.com/40756439/46061424-43edf900-c16f-11e8-823f-0e686a788942.png)

**Comment by RamanMalhotra88** [comment]
Thanks for the reply. It works when i try on safari. Might have been some caching issue :).
