### ISSUE TITLE
Unable to generate customer token via magento2.3 rest api call on local setup

### ISSUE THREAD

**Issue by RamanMalhotra88** [magento/magento2#18251]
### Preconditions

1. Magento version 2.3
2. Environment: Mac OS

### Steps to reproduce

1. call the rest api : POST /V1/integration/customer/token (localhost:8888/magento2ce/rest/all/V1/integration/customer/token)

2. body: {
  "username": "test@test.com",
  "password": "test@123"
}

### Expected result
customer token generated successfully

### Actual result
following error occurs on execution: 
{
  "message": "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later."
}

we have verified that the user is created in magento as shown in screenshot below:
<img width="1680" alt="screen shot 2018-09-26 at 11 35 00 am" src="https://user-images.githubusercontent.com/7579467/46060871-3ee67500-c182-11e8-898e-e59169e29ea8.png">

**Comment by magento-engcom-team** [comment]
Hi @RamanMalhotra88. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@RamanMalhotra88 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by zanatta** [comment]
@RamanMalhotra88 what have you done to fix? just started happening the same here.

**Comment by bhargavsejpalindianic** [comment]
Same issue here

**Comment by haelbichalex** [comment]
Check your `oauth_token_request_log` table as it could be the same issue as in #4432.

**Comment by taqvi** [comment]
Same issue in 2.3.3

**Comment by sheshagiricorra** [comment]
Same issue for the customer login in 2.3.6-p1
