### ISSUE TITLE
getAdditionalInformation() is null when buying a virtual product

### ISSUE THREAD

**Issue by VirtusB** [magento/magento2#18255]
Other issues regarding this:
https://github.com/magento/magento2/issues/13801
https://github.com/magento/magento2/issues/17302

### Preconditions
1. Magento 2.2.5
2. Apache 2.2
3. PHP 7.1
4. Product is virtual
5. Third party payment gateway

### Steps to reproduce
1. Use QuickPay or PayPal as payment module (issue is not with them)
2. Add virtual product to cart
3. Go to checkout, step 1 of checkout is skipped because product is virtual
4. Select payment method and click "Place Order"

### Expected result
1. Order is placed successfully with a virtual product, just like simple products

### Actual result
1. 500 internal server error is returned in console (or redirect to 500 page)
2. Following error "Call to a member function getAdditionalInformation() on null" is returned:
![image](https://user-images.githubusercontent.com/19517591/46072310-545b9f00-c182-11e8-9fbe-84d4f0baabdf.png)

The code that fails:
`$this->_objectManager->get('Magento\Checkout\Model\Session')->getLastRealOrder()`
If the product is virtual then getLastRealOrder() returns an empty order, getPayment() is therefore null and the error is thrown.

The full code of Redirect.php:

    namespace QuickPay\Payment\Controller\Payment;
    
    class Redirect extends \Magento\Framework\App\Action\Action
    {
        protected $_logger;
    
        protected $orderRepository;
    
        public function __construct(
            \Magento\Framework\App\Action\Context $context,
            \Psr\Log\LoggerInterface $logger,
            \Magento\Sales\Api\Data\OrderInterface $orderRepository
        )
        {
            $this->_logger = $logger;
            $this->orderRepository = $orderRepository;
    
            parent::__construct($context);
        }
    
    
        protected function _getCheckout()
        {
            return $this->_objectManager->get('Magento\Checkout\Model\Session');
        }
    
        /**
         * Redirect to to QuickPay
         *
         * @return string
         */
        public function execute()
        {
            try {
                $order = $this->_getCheckout()->getLastRealOrder();
    
                $paymentLink = $order->getPayment()->getAdditionalInformation(\QuickPay\Payment\Gateway\Response\PaymentLinkHandler::PAYMENT_LINK);
    
                return $this->_redirect($paymentLink);
            } catch (\Exception $e) {
                $this->messageManager->addException($e, __('Something went wrong, please try again later'));
                $this->_logger->critical($e);
                $this->_getCheckout()->restoreQuote();
                $this->_redirect('checkout/cart');
            }
        }
    }

Just to clarify: this is not an issue with any third party payment module - getPayment() is not supposed to return null when the product is virtual.

**Comment by magento-engcom-team** [comment]
Hi @VirtusB. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@VirtusB do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @VirtusB, thank you for you report, This problem related to QuickPay not magento core, beacouse all payments in magento paylpal e.g are check if payment have additional information, for virtual product there are not, so if you use paypal or braintree everything will be ok. 

Best regards.

**Comment by VirtusB** [comment]
@engcom-backlog-nazar So it's expected behaviour that getPayment() is null when the product is virtual, but not when the product is simple? getPayment() was not null in 2.2.4 even if the product was virtual, it wasn't a problem till 2.2.5

**Comment by ghost** [comment]
@VirtusB If product not virtual getPayment() not null, i'm checked with debugger for 2 payments paypal and braintree And have no issue on 2.2-devlop branch.

**Comment by VirtusB** [comment]
@engcom-backlog-nazar Exactly, if the product is not virtual then getPayment() is not null, but it shouldn't be null for virtual products either. getPayment() and getAdditionalInformation() should also work for virtual products, just like it did in 2.2.4 - how else are you supposed to retrieve the data? I'm sorry but I don't understand how this is intended. I'm not the only one with this issue, there are 2 links at the top that also mentions this.

**Comment by ghost** [comment]
@VirtusB Ok. but why i'm not able to reproduce your scenario ?

**Comment by VirtusB** [comment]
@engcom-backlog-nazar Maybe I misunderstood - when you tried, getPayment() was not null for virtual products? And getAdditionalInformation() worked? Did you use version 2.2.5 or 2.2.6? Thanks.

**Comment by ghost** [comment]
@VirtusB On 2.2-dev instance the same on 2.2.6 this works perfectly.
![selection_143](https://user-images.githubusercontent.com/40756439/46080867-acef6400-c1a3-11e8-82e3-d43947d818ae.png)
