### ISSUE TITLE
I am having the exact same problem as described above! I am using magento 2.2.5!

### ISSUE THREAD

**Issue by sourabh2yadav** [magento/magento2#18253]
The only difference that i can see between the products that exportet fine and the ones that have dublicates is the field "custom_options" - it looks like prducts with custom options get wrong export with dublicate products
![ipmsgclip_r_1537949793_0](https://user-images.githubusercontent.com/32545987/46066654-a9071600-c192-11e8-965c-12963befa4e0.png)

![image](https://user-images.githubusercontent.com/32599710/43067975-5900890e-8e69-11e8-8a43-6cd52ae33d2d.png)

_Originally posted by @simonmaass in https://github.com/magento/magento2/issues/7350#issuecomment-406992335_

**Comment by magento-engcom-team** [comment]
Hi @sourabh2yadav. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sourabh2yadav do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @sourabh2yadav Thank you for you report, this issue already fixed in 2.2-develop branch.

**Comment by sourabh2yadav** [comment]
> 
> 
> Hi @sourabh2yadav Thank you for you report, this issue already fixed in 2.2-develop branch.

Could you please provide me link for the solution.

**Comment by zulus** [comment]
I have this on 2.2.6, so I have to wait for 2.2.7 ?

**Comment by zulus** [comment]
Knock knock? Is this part of 2.2.7 or I have to upgrade to 2.3.0?

**Comment by simonmaass** [comment]
I am still having this issue in 2.2.7

**Comment by IgosYee** [comment]
Hey @engcom-backlog-nazar @sourabh2yadav ,

Is the problem fixed? If yes, can someone provide the link for the solution?

**Comment by sarfarazbheda** [comment]
We are still facing issue with 2.2.7. Is there any solution?

**Comment by ghost** [comment]
@sourabh2yadav the duplicate rows is expected behavior, this is non-issue, if you have 1 product in 2 websites or store view, the second row is product with the same sku for second store-view.

![selection_294](https://user-images.githubusercontent.com/40756439/52398661-81ba4100-2ac2-11e9-93d9-5caaa6baa506.png)

**Comment by ghost** [comment]
@sarfarazbheda also please look this pr -> https://github.com/magento/magento2/issues/19786 maybe problem casued by this issue.
