### ISSUE TITLE
M2.2.6 : Special price of 0.0000 is not shown on frontend, but is calculated in cart

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#18268]
If you have a product with a special price of 0.00, this is not shown on the frontend. Not in the product listings and also not on the product detail page.

However, if you add it to the cart, you'll see that the special price of 0.00 is used.

### Preconditions

1. Magento 2.2.6

### Steps to reproduce

1. Create a product with a regular price and a special price of 0.00
2. Check the product in product listings and product detail page.

### Expected result

The price should be shown as from/to

### Actual result

The regular price is shown. However, the 0.00 price is used for sorting and quote calculations

This bug can be dangerous because it can cause a typo to provide a free product without the frontend directly reflecting this (for example, an import process may accidentally have set all special prices to 0.00, but the store owner cannot see this on the frontend). Free products for everyone!

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kanduvisla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by testmagento2** [comment]
I have the same issue, also on a fresh magento 2.2.6

**Comment by testmagento2** [comment]
Hi
I found a temporary solution by create catalog price rule and it changed the price to 0

**Comment by sidolov** [comment]
Hi @kanduvisla. Thank you for your report. 
The issue has been fixed in magento/magento2#18604 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [8084aa985c10208c1ee5bfd14ab31014bd4edfd4](https://github.com/magento/magento2/commit/8084aa985c10208c1ee5bfd14ab31014bd4edfd4)
 - [8296637b258a9d03f81304bf00724cee553da029](https://github.com/magento/magento2/commit/8296637b258a9d03f81304bf00724cee553da029)
 - [42839360380bc3783e1840b0ff69eb922e97a99d](https://github.com/magento/magento2/commit/42839360380bc3783e1840b0ff69eb922e97a99d)
 - [899a8a30d14907f07887a814060712a4b163efdb](https://github.com/magento/magento2/commit/899a8a30d14907f07887a814060712a4b163efdb)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @kanduvisla. Thank you for your report. 
The issue has been fixed in magento/magento2#18631 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [e30a12e6bf954763662f68f5eec87d2cbc2e93dd](https://github.com/magento/magento2/commit/e30a12e6bf954763662f68f5eec87d2cbc2e93dd)

The fix will be available with the upcoming 2.3.1 release.
