### ISSUE TITLE
2.2.6 Product Attributes (dropdown/multi-select) issue with ampersands

### ISSUE THREAD

**Issue by CD0001** [magento/magento2#18263]
### Preconditions
**Magento 2.2.6**
This seems to have been added in 2.2.6 to work around PHP's `max_input_vars` (ini) restriction when using **Dropdown** or **Multi-Select** attributes.

### Summary of the issue
You can't enter ampersand characters as Options for Dropdown/Multi-Select attributes (Stores -> Attributes -> Product -> Properties -> Manage Options) - everything from the **&** character onwards gets stripped.

### Steps to reproduce
Create a new product attribute with type *Dropdown* (or *Multi-Select*).
Add an option like *"Fish & Chips"*
Save the attribute.

#### Result without an '&'
Data: `option[value][123]=Fish and Chips`
Becomes:

	Array
	(
		[option] => Array
			(
				[value] => Array
					(
						[123] => Fish and Chips
					)
			)
	)

#### Result with an '&'
Data: `option[value][123]=Fish & Chips`
Becomes: 

	Array
	(
		[option] => Array
			(
				[value] => Array
					(
						[123] => Fish 
					)
			)
		[Chips] => 
	)

Since the value that goes into the database is the data from `[option][value][123]` it has effectively stripped *& Chips* from the string - the resulting array *should* be...

### Expected Result

	Array
	(
		[option] => Array
			(
				[value] => Array
					(
						[123] => Fish & Chips
					)
			)
	)

### Source of the problem
*/vendor/magento/module-catalog/Controller/Adminhtml/Product/Attribute/Save.php* line 330

`parse_str($serializedOption, $option);`

Essentially `parse_str()` is being used here to convert strings from the options into PHP arrays - however the **&** in the string gets parsed as an additional URL parameter so you end up with:

	Array
	(
		[option] => Array
			(
				[value] => Array
					(
						[123] => Fish 
					)
			)
		[Chips] => 
	)

**Comment by magento-engcom-team** [comment]
Hi @CD0001. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@CD0001 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @CD0001 Please add Steps to reproduce, actual and expected result, thank you.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95266`, `MAGETWO-95267` were created

**Comment by bluemwhitew** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @bluemwhitew. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @bluemwhitew, here is your [Magento instance](https://i-18263-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18263-2-2-6.engcom.dev.magento.com/admin](https://i-18263-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @Mobecls. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by slavvka** [comment]
hey @CD0001 Thank you for reporting the issue. We are already working in the fix for 2.3 (MAGETWO-94962) and then will port it to 2.2 (MAGETWO-95426)

**Comment by chefbuitenhuis** [comment]
Any updates on this? We are able to reproduce this on both CE and EE 2.2.6 as well.

**Comment by slavvka** [comment]
@chefbuitenhuis the fix was delivered to 2.3-develop 7 days ago and also backported to be delivered as a part of 2.2.7

**Comment by satyaprakashpatel** [comment]
I am working on this at #dmcdindia1

**Comment by satyaprakashpatel** [comment]
Unable to reproduce this issue on M2.3.1

**Comment by magento-engcom-team** [comment]
Hi @CD0001. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-95267` was closed as `non-reproducible` in `2.3.x`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by CD0001** [comment]
> 
> 
> Unable to reproduce this issue on M2.3.1

Yes - it was fixed about 8 months ago on both the 2.2.x and 2.3.x branches.
