### ISSUE TITLE
Magento 2.2.6: Multiple refreshes on checkout page removes all items from cart

### ISSUE THREAD

**Issue by quangdo-aligent** [magento/magento2#18277]
### Preconditions

1. Magento 2.2.6
2. PHP 7.0.28

### Steps to reproduce

1. Add an item to cart
2. Enter checkout
3. Rapidly refresh two or more times

### Expected result

1. The checkout is refreshed

### Actual result

1. The user is redirected to the cart
2. All items are removed from the cart
3. The minicart still shows that there are items in the cart
4. Any attempt to enter the checkout will state that the cart is empty

Similar to [#16188](https://github.com/magento/magento2/issues/16188).

However, this is related to the changes made in dc687c6730ad87189e86867a30e5349388a10777 which now require a request to have a referrer in order to be considered 'secure'. If a request does not have a referrer, the session will be re-generated and, if this creates a new session (e.g. due to repeated refreshing), the cart will now be empty.

The fix would be to revert isSecureRequest() to its previous state in a6f146cd9302fbbb6305df9613c7ce3eea7a05ae.

**Comment by magento-engcom-team** [comment]
Hi @quangdo-aligent. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@quangdo-aligent do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by quangdo-aligent** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @quangdo-aligent. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @quangdo-aligent, here is your [Magento instance](https://i-18277-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-18277-2-2-develop.engcom.dev.magento.com/admin](https://i-18277-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @quangdo-aligent  Thank you for your report. 
The issue has been fixed in magento/magento2#14973 by @elioermini in 2.2-develop branch
Related commit(s):
 - [5e66f1b21b8741f9a4d54c6a31c7372e44780551](https://github.com/magento/magento2/commit/5e66f1b21b8741f9a4d54c6a31c7372e44780551)
 - [8f033ac342d8343e931a2104f0e2ba8f21156469](https://github.com/magento/magento2/commit/8f033ac342d8343e931a2104f0e2ba8f21156469)
 - [6ee737bb43adcd9b40c170170c5ea8e5d5ad6731](https://github.com/magento/magento2/commit/6ee737bb43adcd9b40c170170c5ea8e5d5ad6731)
 - [d63c2c3899e9f91d6afd0a9438a0ecf1de7842e9](https://github.com/magento/magento2/commit/d63c2c3899e9f91d6afd0a9438a0ecf1de7842e9)
 - [5dbce2a48e875cb38d82ba6648b5c04578bf9852](https://github.com/magento/magento2/commit/5dbce2a48e875cb38d82ba6648b5c04578bf9852)
 - [b1865674bff3c03b92fcc3a2c85f4446735054de](https://github.com/magento/magento2/commit/b1865674bff3c03b92fcc3a2c85f4446735054de)
 - [eabccc83c9ca4e4f55afe6451a93dee3f09115b9](https://github.com/magento/magento2/commit/eabccc83c9ca4e4f55afe6451a93dee3f09115b9)

The fix will be available with the upcoming 2.2.7 release.
