### ISSUE TITLE
Magento 2.2.5 - Admin Orders - Customer Group Pricing not being applied to Order Totals after selecting shipping methods

### ISSUE THREAD

**Issue by callumstar** [magento/magento2#18289]
When creating a new Magento Order in the admin on a multi-storefront Magento installation, if you have products that have customer group pricing applied to them, once you click to get the shipping rates the order totals at the bottom of the page update and go back to use the normal price not the discounted customer group.

### Preconditions
1. Magento 2.2.5 (Multi-storefront installation)
2. PHP 7.0.29

### Steps to reproduce
1. Create product in admin that has a set of customer group on it that reduces in price with the more quantity in the cart.
2. Create a new order in the Magento Admin.
3. Add the newly created product into the order and set the quantity value so that it activates a customer group price.
4. This will then use the correct price until you then fill out the billing/shipping address and click the link 'Get shipping methods and rates'.
5. This will then refresh the totals box at the bottom and the normal price will be then used in the calculations, not the customer group pricing, leading the customer to be charged incorrectly.

### Expected result
1. The order totals should use the customer group price that has been activated with the number of quantity added to the cart.

### Actual result
1. Customer is charged the incorrect price and the order totals use the normal Magento price instead.

**Comment by magento-engcom-team** [comment]
Hi @callumstar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@callumstar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by callumstar** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @callumstar. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @callumstar, here is your [Magento instance](https://i-18289-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18289-2-2-5.engcom.dev.magento.com/admin](https://i-18289-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by callumstar** [comment]
Hi @magento-engcom-team, I can't reproduce this in a vanilla instance of 2.2.5 as far as I can see.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @callumstar I'm not able to reproduce following steps you described, seems like problem related to you custom extensions or code, if you like to update this please reopen the issue.
