### ISSUE TITLE
Module ordering for modules without parent dependencies should be loaded in a consistent manner

### ISSUE THREAD

**Issue by kirkmadera** [magento/magento2#18296]
### Summary
Module ordering for modules without parent dependencies should be loaded in a consistent manner. Currently, it is very random and can cause issues that are unrelated to changes made within a release, thus making them very hard to debug.

### Examples
We have hit this twice in the last month. We inherited a codebase that does not correctly set module dependencies in most of its custom modules. Everything works correctly until something causes the module order in app/etc/config.php to change. Modules tend to get rearranged significantly with any small change.

Examples we ran into:
* Cart page was empty because there was a module that should have depended on Magento_Checkout that didn't. This module had a bad layout override that replaced a block in checkout, but it was not a visible issue because it loaded before the Magento checkout module. It used to be included (randomly) before it; after the deploy it was included randomly after it. We ended up having to fix this by fixing the layout, but the point is that the error presented itself randomly due to unrelated changes in the release.
* PDP swatch images were being rendered as very small images, then stretched causing them to be very pixellated. Same reason for the issue as above; It surfaced on a release due to random module sort order.

### Proposed solution
While declaring dependencies in module.xml files is the correct fix, this is not always possible with inherited inherited code. I think module loading could be less unreliable in this scenario if we added some consistent rules around loading modules without declared child dependencies.

I propose a ruleset similar to this:

1. Determine dependency order based on declared dependencies in module.xml files.
2. Where there is ambiguity and modules are at the same level in the dependency tree, load them in alphabetic order.
3. All modules without child dependencies should load last in alphabetic order

Alphabetic ordering would prevent the random sort issues we are seeing. Modules could continue to incorrectly not have module dependencies declared but still have consistent behavior across releases except in the case where we specifically change a related module. Right now, any module change can completely reorder modules and break any of these.

**Comment by magento-engcom-team** [comment]
Hi @kirkmadera. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kirkmadera do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by kirkmadera** [comment]
This is hard to explain how to reproduce. You need a dirty codebase in the first place. You would need to do something like this:

1. Make one or more modules that have an effect like changing layout that depends on another module loading. One example could be replacing a block in core Magento layout instead of referencing it in layout. If your module loads first, the block will be defined by your module and will be missing anything that the Magento module would load.
2. Ensure that these modules do not declare their dependencies. 
3. You may have to manually edit app/etc/config.php to get it to load in the order which causes the failure
4.  Create another test module and run setup:upgrade. This should rearrange app/etc/config.php ordering
5. Confirm that your change that was showing before, no longer shows

Environment data is not very relevant to this ticket. This will happen in both developer and production mode on any environment.

This issue would not be possible to reproduce on a vanilla instance. This is a request for an improvement to core code to help dealing with badly written custom code more consistently.

**Comment by LeeSaferite** [comment]
Here is an example of a badly written module that causes problems due to load order:
https://github.com/instantsearchplus/isp_magento2_extension/tree/be0198ea5f0103fe62f70d43697364759fd128de

The module is accessing the scope config during the schema install process in an attempt to phone home about an install (it wants to capture the URL, Email, and Multistore flag). 
https://github.com/instantsearchplus/isp_magento2_extension/blob/be0198ea5f0103fe62f70d43697364759fd128de/Setup/InstallSchema.php

This will 'work' if you are adding the module to an existing M2 install that has a fully setup core schema. It *won't* work if you attempt to do something like integration testing where you have an empty DB with no schema. 

Ignoring the bad design of a phone home in a schema install script, it is sorted *before* the core modules ('I' comes before 'M') and since it's missing the specification of it's deps, it causes all kinds of issues.

The issues with a module like this one would be solved by more intelligent module sorting as suggested in this issue. 

I would further refine the sorting to be: Modules sorted by defined `sequence` information, unreferenced core magento modules sorted lexicographically, all the rest sorted lexicographically.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @kirkmadera   thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features
