### ISSUE TITLE
Cannot view full custom option text when length is greater than 55 characters

### ISSUE THREAD

**Issue by jbokhari** [magento/magento2#18298]
Users on my website fill out special instructions for us inside of a textarea custom option. I was notified recently that the text is unreadable for some orders. After digging into the problem I found that this appears to be a bug in Magento. So far all I know that `$_option['remainder']` is never set inside the file `Magento_Sales/view/adminhtml/templates/items/column/name.phtml`:

    // Line 34: should set $_option['remainder'] if strlen($_option['value']) > 55
    <?php $_option = $block->getFormattedOption($_option['value']); ?>

I've tested this on both Magento OS 2.2.4 and 2.2.6. I am guessing this applies to regular text fields as well and I suspect that the filter is used in other places and does not work.

### Preconditions

(Where I originally encountered the error: `CentOS 6.10` `MySQL 5.6` `Apache/2.4.34` `PHP 7.0.32`)
`Mac OSX 10.13.6` ` MySQL 5.6.38` `Apache/2.2.34` `PHP 7.0.27`

1. Magento Open Source 2.2.6 without sample data is installed.
2. A simple product is created in Magento backend that includes a custom option for a text area.
3. Add test product to menu by creating a category.

### Steps to reproduce

1. Visit test product on front end
2. Fill out custom option text area with text exceeding 55 characters in length (preferably more to easily see the issue later on)
3. Add the item to cart
4. Complete checkout process
5. Review the order in Magento's backend

### Expected result

1. When viewing order information, special instructions is truncated to 55 characters followed by an ellipsis.
2. You should be able to use your mouse to hover over the ellipsis in order to reveal the remaining text.

### Actual result

1. Ellipsis does not appear, instead the abbreviated 55 characters appear with no ability to read the remaining information.

![_000000001___orders___operations___sales___magento_admin](https://user-images.githubusercontent.com/2964858/46168489-7ff78b80-c24d-11e8-85f3-94502fed1ddc.png)

**Comment by magento-engcom-team** [comment]
Hi @jbokhari. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jbokhari do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jbokhari** [comment]
> @jbokhari do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no

Yes I used a fresh, untouched magento installation. I have added my environment information as well

**Comment by magento-engcom-team** [comment]
@sidolov Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @jbokhari thank you for you report, the fix for this issue has already available on 2.2-develop and 2.3-develop branch.
![selection_172](https://user-images.githubusercontent.com/40756439/47428219-486ff680-d79b-11e8-81c4-e76adb1c04d3.png)
![selection_171](https://user-images.githubusercontent.com/40756439/47428176-21b1c000-d79b-11e8-8e10-a25038996f39.png)
