### ISSUE TITLE
CSS issue after upgrading from v 2.2.1 to v 2.2.6

### ISSUE THREAD

**Issue by allumanatu** [magento/magento2#18318]
After updating from Magento 2.2.1 to 2.2.6, the CSS is not shown anymore, even if it is loaded in the source code. When I try to open the CSS file in the browser, it shows me a 404.
I already tried to re-deploy the content.

This is how it looks like:

![magento_update_error](https://user-images.githubusercontent.com/38261208/46254825-a6a80300-c495-11e8-858c-eae5c7851211.png)

**Comment by magento-engcom-team** [comment]
Hi @allumanatu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@allumanatu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by allumanatu** [comment]
I don't know how to reproduct it, it just appears after upgrading. I need help, how the css is shown.

**Comment by pczerkas** [comment]
@magento-engcom-team give me $VERSION instance

**Comment by pczerkas** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @pczerkas. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @pczerkas, here is your [Magento instance](https://i-18318-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18318-2-2-6.engcom.dev.magento.com/admin](https://i-18318-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pczerkas** [comment]
How to reindex instance created by assistant (@magento-engcom-team give me ...)?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @allumanatu seems like problem with access to your folders, try add permissions to the folders.

**Comment by DanielRuf** [comment]
You may have to remove the content of `var/cache` and redeploy the static content.

**Comment by ghost** [comment]
@allumanatu I'm closing this issue as this not related to magento, if you like to update this please reopen the issue.
