### ISSUE TITLE
Layered Navigation not working in Magento 2.2.6

### ISSUE THREAD

**Issue by Sharon831** [magento/magento2#18319]
After upgrading from Magento 2.2.3 to 2.2.6 via command-line, the Layered Navigation in all sections (Product, Page, Static Block and etc.) become either grey (like inactive) or just the icon without text. There is no response after clicking.

### Preconditions

1. Magento 2.2.6
2. PHP 7.1 

### Steps to reproduce

1. Right after upgrading to Magento 2.2.6 from 2.2.3 via command-line method

### Expected result

1. https://bymagnet.com/test/2018-09-30.png (Page)
2. https://bymagnet.com/test/2018-09-30_2.png (Product)

### Actual result

1. https://bymagnet.com/test/2018-09-30_3.png

**Comment by magento-engcom-team** [comment]
Hi @Sharon831. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Sharon831 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
