### ISSUE TITLE
Magento2 (2.2.5) circuar redirection with 2 host deployment

### ISSUE THREAD

**Issue by ACGAshwin** [magento/magento2#18313]
### Preconditions

I have deployed vanilla Magento 2.2.5 on a 2 host farm (all AWS EC2 instances running amazon linux) with the following configurations :

1.2 app servers with a shared (EFS) media folder  (pub/media) . Apache2 listening on port 8080
2.The 2 app servers run Varnish 4.1.10 listening on port 80 and pointing to port 8080.
3.Elastic load balancer pointing to the 2 app servers as targets.
4.RDS MySQL running the core DB and ElasticCache (redis) is running session cache.

After setup i updated the secure and unsecure URLs (config ID 3 and 2 in the core_config_data) table to hold the DNS of the load balancer as mentioned in step 3 above

### Steps to reproduce

1. Browse the load balancer DNS URL in any browser

### Expected result

1. Magento 2 store front UI should be displayed

### Actual result

1. Cyclic redirection on app servers (HTTP Code 302) which eventually leads to a page not being displayed in browser

@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ACGAshwin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ACGAshwin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ACGAshwin** [comment]
> 
> 
> Hi @ACGAshwin. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * [ ]  Summary of the issue
> 
>     * [ ]  Information on your environment
> 
>     * [ ]  Steps to reproduce
> 
>     * [ ]  Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @ACGAshwin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [ ]  yes
> 
>     * [ ]  no

Yes i was able to reproduce using vanilla magento 2.2.5

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ACGAshwin thank you for you report, this is acknowledged issue ,and this is duplicate for this -> https://github.com/magento/magento2/issues/8800, -> https://github.com/magento/magento2/issues/17556
I'm closing this as duplicate.

**Comment by ACGAshwin** [comment]
@engcom-backlog-nazar Neither #8800 nor #17556 are duplicates based on preconditions. The Key precondition is that M2 is installed on 2 servers instead of one. Please reopen

**Comment by ghost** [comment]
@ACGAshwin They have one problem no matter if you have 2 or 1 servers, the problem is one, and if another 2 issues will be fixed, your issue also will be fixed.

**Comment by ghost** [comment]
@ACGAshwin `After setup i updated the secure and unsecure URLs (config ID 3 and 2 in the core_config_data) table to hold the DNS of the load balancer as mentioned in step 3 above` 
this is core problem, using this config fields .
