### ISSUE TITLE
Upgrade from M2.1.11 -> M2.2.6: problems with saving tier pricing

### ISSUE THREAD

**Issue by FerihumF** [magento/magento2#18326]
### Preconditions

1. Magento 2.2.6

### Steps to reproduce

1. Have a Magento 2.1.11 installation.
2. Create a product and add tier prices for at least one customer group.
3. Try to save the product -> should work.
4. Upgrade to Magento 2.2.6
5. Open the product in admin and try to save (without any changes)
6. Receiving a "Unique constraint violation found" message, product is not saved. (See log below)
7. Delete the tier price and try to save again => should work.
8. The tier pricing is not deleted!!

### Expected result

1. No constraint violation thrown when saving the product
2. When deleting tier prices they should stay deleted.

### Actual result

1. When saving the product: `SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-0-3-1.0000-0' for key 'UNQ_E8AB433B9ACB00343ABB312AD2FAB087', query was: INSERT INTO catalog_product_entity_tier_price (entity_id, all_groups, customer_group_id, qty, value, percentage_value, website_id) VALUES (?, ?, ?, ?, ?, ?, ?)`
2. When deleting tier prices and saving the product, tier prices are still present when you reopen the product.

**Comment by magento-engcom-team** [comment]
Hi @FerihumF. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@FerihumF do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by neodrg** [comment]
duplicate of #18154

**Comment by FerihumF** [comment]
Thank you @neodrg!

**Comment by ayasoftware** [comment]
I have just tried to edit a product with a tier pricing configuration and i got the error:
Unique constraint violation found - I'm using 2.2.6
