### ISSUE TITLE
 Products per Page on Grid Default Value / Products per Page on list Allowed Values does not work

### ISSUE THREAD

**Issue by avanish512** [magento/magento2#18325]
Hi,

I found an issue Products per Page on Grid Default Value / Products per Page on Grid Allowed Values does not work. it's displaying all products while category page load

I'm working with Magento ver. 2.2.4

Anybody, please help me to solve this issue?

**Comment by magento-engcom-team** [comment]
Hi @avanish512. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@avanish512 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by avanish512** [comment]
Hi,

I have already shared the issue summary and Magento version now I'm going to share the rest steps 

Steps to reproduce
Go to Stores > Configuration > Catalog > Catalog
In the Products per Page on Grid Allowed Values / Products per Page on Grid Allowed Values field, enter 9,18,27 for the value.

![image](https://user-images.githubusercontent.com/24352902/46272320-2903f600-c56e-11e8-8299-368a053fcd8c.png)

Click Save Config

Go to a product list on the front end. 

Expected result
On the category page, grid/list must load 9 product at a time while clicking on any category 

Actual result
On the category page loading all the products on the category page even at the backend, I have set the number of products to show on the page. you can check here also http://temp.fabninedesign.com/rings.html

![image](https://user-images.githubusercontent.com/24352902/46272366-69fc0a80-c56e-11e8-97ad-fc2d1ab4c86d.png)

you can see in above screenshot the scroll bar of the page is too small 

Hope this is enough to understand the issue but if there needed anything else please let me know.

Thanks

**Comment by avanish512** [comment]
Hi,

Please help me

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @avanish512 thank you for you report, i'm not able to reproduce following steps your described, seems like this related to your custom code. If you like to update this please reopen the issue.
