### ISSUE TITLE
Cannot add the value "00" (without quotes) as an attribute option

### ISSUE THREAD

**Issue by sidm** [magento/magento2#18324]
### Preconditions

1. Using Magento ver. 2.2.5

### Steps to reproduce

1. Create an attribute set
2. Create an attribute of type dropdown

![image](https://user-images.githubusercontent.com/728604/46263686-2bb80a00-c4e0-11e8-9461-019f01f088f1.png)

4. Attempt to add an attribute value that is just `00`

![image](https://user-images.githubusercontent.com/728604/46263673-1347ef80-c4e0-11e8-96f0-552684de62de.png)

5. Click "Save Attribute"

### Expected result

1. The attribute option to be saved successfully

### Actual result

1. I get a 404 error and upon going back to the attribute see that the attribute option was **not added**
![image](https://user-images.githubusercontent.com/728604/46263717-6621a700-c4e0-11e8-988e-1737878ec558.png)

**Comment by magento-engcom-team** [comment]
Hi @sidm. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sidm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sidm** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @sidm. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sidm, here is your [Magento instance](https://i-18324-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18324-2-2-5.engcom.dev.magento.com/admin](https://i-18324-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidm** [comment]
I verified this is not an issue on the vanilla instance.
