### ISSUE TITLE
I am facing the same issue in Magento 2.2.5

### ISSUE THREAD

**Issue by nowsathyasar** [magento/magento2#18327]
Let me know if any one has a better solution.
Thanks

_Originally posted by @nowsathyasar in https://github.com/magento/magento2/issue_comments#issuecomment-425846987_

**Comment by magento-engcom-team** [comment]
Hi @nowsathyasar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nowsathyasar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
