### ISSUE TITLE
2.2.6 Duplicate ID's on category page.

### ISSUE THREAD

**Issue by BezV8** [magento/magento2#18339]
In 2.2.6 there are numerous duplicated ID's on category pages. Elements are: modes-label, mode-list, toolbar-amount, limiter & sorter.

### Preconditions

1. Magento 2.2.6
2. Blank or Luma Theme
3. Category with at least 1 product.

### Steps to reproduce

1. Validate category page with W3C html validator.

### Expected result

1. Clean validation.

### Actual result

1. 5 Duplicate ID warnings.
![screenshot_2018-10-02 showing results for https i-18337-2-2-6 engcom dev magento com testcat html - nu html checker](https://user-images.githubusercontent.com/33320744/46346047-9f702900-c63e-11e8-92c2-4ca270bc0c0d.png)

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BezV8 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by BezV8** [comment]
@magento-engcom-team issue confirmed on vanilla test instance (using instance from issue #18337).

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](http://34.228.235.121/i-18339-2-3-develop/).
Admin access: [http://34.228.235.121/i-18339-2-3-develop//admin](http://34.228.235.121/i-18339-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TomashKhamlai** [comment]
[Html Checker 2.3-develop.pdf](https://github.com/magento/magento2/files/2571940/Html.Checker.2.3-develop.pdf)

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](http://34.228.235.121/i-18339-2-2-develop/).
Admin access: [http://34.228.235.121/i-18339-2-2-develop//admin](http://34.228.235.121/i-18339-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TomashKhamlai** [comment]
[Html Checker 2.2-develop.pdf](https://github.com/magento/magento2/files/2572008/Html.Checker.2.2-develop.pdf)

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96279`, `MAGETWO-96280` were created

**Comment by dhow** [comment]
#mm18jp

**Comment by magento-engcom-team** [comment]
@dhow thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @otsmyh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by KishorkumarKar** [comment]
I am working on this issue #mm19in

**Comment by ioweb-gr** [comment]
I've noticed that whenever a block is repeated in a page it always ends up with duplicate IDs. Even when you use in the phtml the following code. 

     <div id="<?php echo uniqid() ?>"> </div> 

Is there a best practice to avoid this issue?

**Comment by scottsb** [comment]
@ioweb-gr That is because once a block is generated, it is cached in memory and reused when it is output the second time rather than being regenerated. Hence your `uniqid()` call only runs once. The best practice is not to include the same block multiple times if it contains IDs.

**Comment by scottsb** [comment]
Note that this is an accessibility issue, as having duplicate IDs referenced by ARIA attributes, as these are, violates [WCAG 2.0 criterion 4.1.1 (level A)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html).

**Comment by ioweb-gr** [comment]
@scottsb I see, I understand why it's being cached but there are use cases like that. Imagine a menu that's included 3 times in the page (sticky menu, mobile menu, top menu) but using an unique ID. Creating 3 separate menu instances for this is not user friendly especially when you need to use the same menu items. There are sites with over 100 menu items and multilanguage means even more maintenance.  

It seems Magento is very smart and even when you add the block in your xml layout with different names it still caches it and keeps the ID so I haven't found a workaround without duplicate work in the backend by the end user. 

Often in the EU we try to make websites valid for HTML5 and WCAG AA and fix such cases in themes and even with Luma. It's very common in the most popular themes to face this issue too (porto , fastest , novetty). View Mode, Pager, Limiter and Sorter are the perfect examples because they're included above and below product list but they're the same block. 

Furthermore if you remove their IDs, their form input elements will be missing the ID needed by their Label elements. So you then have to also include the form elements in the label so that the relation is inferred instead of  having it explicitly declared. 

I was hoping there was some way to declare a different cache identity for each reference of these blocks so each instance is processed separately if needed. 

PS: sorry for the huge block of text

**Comment by scottsb** [comment]
@ioweb-gr Right, you don't want to have to manually reproduce the same block completely separately. As I understand it, when included via layout XML with two different names a block should not be reused from the in-memory cache. I'm not sure why you were seeing that.

This particular case is unusual, though, as the block is not included using normal layout XML practices. There is a block in the layout XML, but then it gets retrieved and rendered by special methods in the parent `ProductList` class before being included in the page. That makes it trickier to solve. We have a potential solution that we're testing internally. If it works, we're going to submit a PR.

**Comment by Bhavik-kumar** [comment]
is there any solution ? why it's not resolved from Oct 2, 2018. 👎

**Comment by pemann** [comment]
Is there any solution to this one?

**Comment by kanhaiya-ech** [comment]
Hi,
Is any solution, as its issue exist in 2.4.1 version also

@kanhaiya5590

**Comment by engcom-Bravo** [comment]
Hi @BezV8,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

<img width="1296" alt="Screenshot 2024-04-30 at 12 45 17" src="https://github.com/magento/magento2/assets/51680745/f1fbf06e-1ccc-40f4-88a5-78d4a6a136b4">


There are no duplicate warnings.

Hence We are closing this issue.

Thanks.
