### ISSUE TITLE
Rest Api for post method not working in Magento 2.1.3?

### ISSUE THREAD

**Issue by devqualwebs** [magento/magento2#18332]
### Preconditions

1. Installed Magento v.2.1.3, setup multistore and created custom checkout page to place order using rest Api..  
2. Trying to get shipping rates for guest customers and logged in customers using rest Api. 

### Steps to reproduce

1. Using https://mywebsiteurl/index.php/rest/english/V1/carts/mine/estimate-shipping-methods for logged in users.  
2. https://mywebsiteurl/index.php/rest/english/V1/guest-carts/:cartId/estimate-shipping-methods for guest users. 
I'm using these parameters for estimate shipping.
`{"address":{"region":"Queensland","country_id":"AG","street":["203 FA",""],"postcode":"4073","city":"test treet","firstname":"test","lastname":"test","email":"test221@mailinator.com","telephone":"7896541230","same_as_billing":"1"}}`

3. Tried any other Api for post methods. For Ex. /V1/carts/:cartId/billing-address , /V1/guest-carts/:cartId/billing-address. and suitable payloads for respected Api endpoints.

### Expected result

1. /V1/carts/mine/estimate-shipping-methods should return shipping rates for logged in users.
2. /V1/guest-carts/:cartId/estimate-shipping-methods should return shipping rates for guest users.
3. /V1/carts/:cartId/billing-address should resturn saved billing address id.

### Actual result

1. All post methods return this error. "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-5bb226799163a".

However, I'm getting the user authentication token and admin authentication token using post method. And it's working fine. But other Api endpoints are not working. and giving such errors. Also I've tried to search "5bb226799163a" inside /var/report/ folder. But nothing found related to this.

**Comment by magento-engcom-team** [comment]
Hi @devqualwebs. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@devqualwebs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-18332-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18332-2-2-6.engcom.dev.magento.com/admin](https://i-18332-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @devqualwebs    Thank you for you report,only 2.2.0+ bug reports are considered nowadays. Try upgrading. I'm not able to reproduce following steps your described.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
