### ISSUE TITLE
Wrong Foreign Key configuration, can't recreate sequence_catalog_category table 

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#18338]
### Preconditions

1. Magento 2.2.5 EE
2. I've created a dump of the database, can't import it again fully, some tables are missing due to wrong foreign keys. 

### Steps to reproduce

1. Drop table sequence_catalog_category
2. try to recreate the table  ```sequence_catalog_category``` using MySQL query in command line
```CREATE TABLE `sequence_catalog_category` (
 `sequence_value` int(10) unsigned NOT NULL AUTO_INCREMENT,
 PRIMARY KEY (`sequence_value`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4```
3. I've narrowed it down to the fact that some foreign keys do not match category row_id column definition. It is NOT NULL, at least one of foreign keys allows NULL to be YES
4. Run this query to identify foreign keys used for sequence_catalog_category table
```
 SELECT 
    TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
     FROM
       INFORMATION_SCHEMA.KEY_COLUMN_USAGE
     WHERE
     REFERENCED_TABLE_SCHEMA = "mag225_ee"
     and
       REFERENCED_TABLE_NAME = "sequence_catalog_category";
```
5. hint* - it will take long time to run this query

### Expected result

1. Table  ```sequence_catalog_category``` is recreated with no issues
2. I can add / remove categories

### Actual result

1. Table is not created due to issue with foreign keys 
2. MySQL error: `error 150 Foreign key constraint is incorrectly formed error`
3. Can't add new categories in magento admin panel

**Comment by magento-engcom-team** [comment]
Hi @qsolutions-pl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@qsolutions-pl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jakwinkler** [comment]
@magent-engcom-team yes, this is vanilla installation without any 3rd party modules.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @qsolutions-pl , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
