### ISSUE TITLE
Checkout - Infinite loading indicator when server returned error

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#18330]
### Preconditions
1. Magento 2.2.6

### Steps to reproduce
1. Create any simple product
2. Add to cart it on frontend and go to checkout
3. Open Chrome Dev Tools
4. Fill up shipping in US with any address
5. Find request to request like this: https://test-magento-instance.com/rest/default/V1/guest-carts/gFgmi7qopaxOgxlbXQ3hEo2Ny8gkNXXl/estimate-shipping-methods
6. Right click on this request on click "Block request URL" in order to emulate that we can't connect to server or server returned an error 
![image](https://user-images.githubusercontent.com/1873745/46289912-0fc17080-c593-11e8-9ef6-48284c9be548.png)
7. Change zipcode in shipping address and see that estimate-shipping-methods request was blocked in Dev Tools:
![image](https://user-images.githubusercontent.com/1873745/46290037-5b741a00-c593-11e8-9995-77e55ac162cb.png)

### Expected result
1. Loading indicator should be hidden
2. No shipping methods should be available

### Actual result
1. Infinite scrolling in "Shipping methods" appeared

### Additional info
Issue appearing here:
https://test-magento-instance.com/pub/static/version1538398224/frontend/Magento/luma/en_US/Magento_Checkout/js/model/shipping-rate-processor/new-address.js contains following line - errorProcessor tries to process response
![image](https://user-images.githubusercontent.com/1873745/46290149-b60d7600-c593-11e8-8d93-e1b2b356a8f2.png)
but it can't process JSON.parse on empty string and throwing exception:
![image](https://user-images.githubusercontent.com/1873745/46290231-efde7c80-c593-11e8-98d9-084c2e5ba26e.png)
As result we "always" section in new-address.js file is not processed.

We have following JS error in console:
![image](https://user-images.githubusercontent.com/1873745/46290292-1ac8d080-c594-11e8-89b4-8ca3c7467d3b.png)

PS: I tested it on following test instance: https://i-18112-2-2-6.engcom.dev.magento.com/test.html

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ihor-sviziev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@ihor-sviziev Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95448`, `MAGETWO-95449` were created

**Comment by slavvka** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#18331 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - [eea11c733b94d60639dabc4f83752c51ea1a70e5](https://github.com/magento/magento2/commit/eea11c733b94d60639dabc4f83752c51ea1a70e5)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#18369 by @ihor-sviziev in 2.2-develop branch
Related commit(s):
 - [74bed695b4ac0f381b10368c7d8a780b52b5c9f9](https://github.com/magento/magento2/commit/74bed695b4ac0f381b10368c7d8a780b52b5c9f9)

The fix will be available with the upcoming 2.2.8 release.
