### ISSUE TITLE
$this->_customerSession->getId() not working in block overriding

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#18342]
### Summary

I am using Magento 2.2.3
php 7.0.6
I have to override the Magento_Catelog catelog_product_view.xml. So in my custom block all the other functionalities are working other than getting the current looged in user user id. 
In my extended block i have done 
protected $_customerSession;
public function __construct(
\Magento\Catalog\Block\Product\Context $context,
\Magento\Customer\Model\Session $customerSession,
...
) {
$this->_customerSession = $customerSession;
}

public function myCustomFunction()
{
    $custid = $this->_customerSession->getId();
    echo  $custid;
}
Not printing current customer id.

Even 
$customerSession = $objectManager->get('Magento\Customer\Model\Session');  
$customerDatas = $customerSession->getCustomer()->getData(); //get all data of customerData
$customerData = $customerSession->getCustomer()->getId();//get id of customer  
print_r($customerDatas);

Only printing Array ( [group_id] => 1 )

**Comment by magento-engcom-team** [comment]
Hi @BabliDey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BabliDey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mageprashant** [comment]
@BabliDey 

I have tried like this and got the customer session object when the cache is enabled.

```
<?php

namespace Test\Stack\Model\Test;

use Magento\Framework\ObjectManagerInterface;

/**
 * @var \Magento\Framework\ObjectManagerInterface
 */
protected $_object;

class Test{

     public function __construct(ObjectManagerInterface $interface)
     {
        $this->_object = $interface;
     }

     public function getCustomerSession(){
        $customerSession = $this->_object->create('Magento\Customer\Model\SessionFactory')->create();
		$custid = $customerSession->getId();
		echo $custid; exit;
        return $customerSession;     
     }
}
```

it's working for me

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @BabliDey thank you for you report, this is expected behavior, if you don't have customer id in storage it will return null.
![selection_184](https://user-images.githubusercontent.com/40756439/47777786-2d066d80-dcfe-11e8-92a6-290a05ad63b5.png)
