### ISSUE TITLE
Cannot access login and frontend after theme installation

### ISSUE THREAD

**Issue by sonsec** [magento/magento2#18351]
##Preconditions
Magento 2.2.6
Local Server MAMP 5.3.1
PHP 7.0.8

##Steps to reproduce
1. magento2 2.2.6 installation via composer install
2. uploading of theme files
3. enabling theme and moduls via php bin/magento setup:upgrade
4. deployment of static files via php bin/magento setup:static-content:deploy

##Expected result
1. Able to login to backend
2. Frontend shown as before

##Actual result
1. Not able to login to backedn anymore
2. Frontend not reachable anymore

log recorded the following errors:

{"0":"Recoverable Error: Object of class Magento\\Framework\\View\\Page\\Title could not be converted to string in \/Applications\/MAMP\/htdocs\/magento2\/app\/code\/CleverSoft\/Base\/Model\/Renderer.php on line 141","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(4096, 'Object of class...', '\/Applications\/M...', 141, Array)\n
#1 \/Applications\/MAMP\/htdocs\/magento2\/app\/code\/CleverSoft\/Base\/Model\/Renderer.php(141): str_replace(Array, Array, '<meta name=\"%na...')\n
#2 \/Applications\/MAMP\/htdocs\/magento2\/app\/code\/CleverSoft\/Base\/Model\/Renderer.php(112): CleverSoft\\Base\\Model\\Renderer->renderMetadata()\n
#3 \/Applications\/MAMP\/htdocs\/magento2\/lib\/internal\/Magento\/Framework\/View\/Result\/Page.php(249): CleverSoft\\Base\\Model\\Renderer->renderHeadContent()\n
#4 \/Applications\/MAMP\/htdocs\/magento2\/lib\/internal\/Magento\/Framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#5 \/Applications\/MAMP\/htdocs\/magento2\/generated\/code\/Magento\/Backend\/Model\/View\/Result\/Page\/Interceptor.php(193): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#6 \/Applications\/MAMP\/htdocs\/magento2\/lib\/internal\/Magento\/Framework\/App\/Http.php(139): Magento\\Backend\\Model\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#7 \/Applications\/MAMP\/htdocs\/magento2\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n
#8 \/Applications\/MAMP\/htdocs\/magento2\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(257): Magento\\Framework\\App\\Http\\Interceptor->launch()\n
#9 \/Applications\/MAMP\/htdocs\/magento2\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n
#10 {main}","url":"\/magento2\/admin\/admin\/index\/index\/key\/9515287f3cbec2975561fadfb11c9a67ce4b3ce8292370547bda673ffc8d55b4\/","script_name":"\/magento2\/index.php"}

**Comment by magento-engcom-team** [comment]
Hi @sonsec. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sonsec do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @sonsec thank you for you report, I'm not able to reproduce following steps your described, this related to 3rth party module that you installed,
If you like to update, please reopen the issue.
