### ISSUE TITLE
Cachable false is not working when overriding 

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#18353]
### Summary

I am using magento 2.2.3
php 7.0.6

For over riding a block i am using:

    <?xml version="1.0"?>
    <page layout="1column" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
        <body>
            <referenceBlock name='catalog.product.related'>
                <action method='setTemplate'>
                    <argument name='template' xsi:type='string'>Vendor_MyModule::product/list/items.phtml</argument>
                </action>
                <arguments>
                    <argument name="cacheable" xsi:type="boolean">false</argument>
                </arguments>
            </referenceBlock>
        </body>
    </page>

It is not making the block cacheable false.. That is not getting logged in customer id by 
`$customerid = $this->_customerSession->getId();` in block function.

    <?xml version="1.0"?>
    <page layout="1column" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
        <body>
            <referenceContainer name="content.aside">
                <block class="Vendor\MyModule\Block\Product\ProductList\Related" name="catalog.product.related" template="Vendor_MyModule::product/list/items.phtml" cacheable="false"/>
            </referenceContainer>
        </body>
    </page>

This is not overriding the block

**Comment by magento-engcom-team** [comment]
Hi @BabliDey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BabliDey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pocallaghan** [comment]
I don't believe this is a bug, but a misunderstanding of the functionality.

Adding a node to the `<arguments>` node is not the same thing as adding an attribute, `cachable`, on the original block definition. The reason for this is the `<arguements>` node contains values to be passed to the block after it's instantiated, but the `cachable` attribute is a property that is parsed by the layout object (I can understand the confusion, given that this does work as a method for setting the template on the block).

Making every page that contains the block un-cachable can be done with something like:

    <referenceBlock name="category.products.list">
        <block class="Magento\Framework\View\Element\Text" cacheable="false" /> 
    </referenceBlock>

That said, it's important to point out that the attribute doesn't make the **block** not cacheable, it makes the **entire page** containing the block not cachable.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @BabliDey thank you for you report, i'm closing this, as this is not a bug. Please read the @pocallaghan  comment.
