### ISSUE TITLE
Bundle: Adding to cart from category when all options are single and required still redirect to product page

### ISSUE THREAD

**Issue by maximecarey** [magento/magento2#18363]
### Preconditions

1. Magento 2.2.5

### Steps to reproduce

1. Create a bundle product, add one product in the bundle items, and mark it default and required.
2. Add the bundle created to a category
3. Go to that category and try to add the product to the quick add to cart button.

### Expected result

1. The product should be added to cart (there's no choice to be made)
2. Stay on the category page

### Actual result

1. We get redirected to product page.
2. "Please specify product option(s)" warning shown in the message box

**Comment by magento-engcom-team** [comment]
Hi @werfu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@werfu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by maximecarey** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @werfu. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @werfu, here is your [Magento instance](https://i-18363-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-18363-2-2-5.engcom.dev.magento.com/admin](https://i-18363-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AirmanAJK** [comment]
This could be considered working as intended. If it's a required option, meaning it's not standard, one could argue that the customer is confirming that they are buying a product with some customization.

In our shop, we occasionally have reduced price products with problems, so we may have a required option of "Screen has a dim display". This is definitely something we want customers to be fully aware of and acknowledge when buying.

If you only have a single required option, why not just make it part of the product without the option? Perhaps update the product name to reflect this change. You may have reasoning why that won't work, but I don't think anything considered an "option" should be auto-chosen.

**Comment by maximecarey** [comment]
> If you only have a single required option, why not just make it part of the product without the option? Perhaps update the product name to reflect this change. You may have reasoning why that won't work, but I don't think anything considered an "option" should be auto-chosen.

Our use case implies many options, but all having a single option, and all of them being required. We use bundle as grouped products doesn't fit our pricing need. It may simply bad usage though?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @werfu, thank you for you report, this is expected behavior, you need to use grouped product instead of bundle. If you select required that means you need to buy this option anyway. this not means that you can add it quickly to cart
