### ISSUE TITLE
Custom Discount is adding Twice in Paypal Express

### ISSUE THREAD

**Issue by ankurverma5540** [magento/magento2#18371]
### Preconditions

I am using Magento 2.2.5 Enterprise Edition. I need to pass Custom Discount to Paypal express. That is My warranty discount. For this I am using payment_cart_collect_items_and_amounts Observer.

```
`<event name="payment_cart_collect_items_and_amounts">
        <observer name="warranty_paypal_express" instance="Vendor\Module\Observer\Addamounttopaypal" />
    </event>`
This is my Observer code
` public function execute(Observer $observer)
    {
        /** @var \Magento\Payment\Model\Cart $cart */
        $cart = $observer->getEvent()->getCart();
        $customAmount = $this->helper->getBaseWarrantyAmt();
        $handlingfee = $this->extafeehelper->getExtrafee();
        $discounntWarranty = $this->helper->getWarrayDiscountAmt();
        if($customAmount && $customAmount>0){
            $cart->addCustomItem(__('Warranty Amount'), 1, $customAmount, 'basewarranty');
        }
        if($discounntWarranty){
            $cart->setDiscount($discounntWarranty);
            $discountnamt = -1.00 * $discounntWarranty;
            $cart->addCustomItem(__('Warranty Discount'), 1,$discountnamt,'warrantydiscount');
        }
        if($handlingfee){
            $cart->addCustomItem(__('Environment Handling Fees'), 1, $handlingfee, 'fee');
        }
    }`
```

Custom Amount is adding fine. But the issue is with Discount. For the Discount i am adding negative value. 
`$discountnamt = -1.00 * $discounntWarranty;
            $cart->addCustomItem(__('Warranty Discount'), 1,$discountnamt,'warrantydiscount');`
But the Amount is getting passed. and got error for total mismatch.
Then I add the following code
`$cart->setDiscount($discounntWarranty);
            $discountnamt = -1.00 * $discounntWarranty;
            $cart->addCustomItem(__('Warranty Discount'), 1,$discountnamt,'warrantydiscount');`
Now Warranty Discount and discount is adding. But i only need Warranty Discount.  Warranty Discount is not adding without `$cart->setDiscount($discounntWarranty);`
Please check

### Steps to reproduce

1. Create Observer for payment_cart_collect_items_and_amounts event. 
2. Pass Custom Discount to Paypal using addCustomItem function

### Expected result

1. Custom Discount Should be add without  $cart->setDiscount($discounntWarranty)
2.

### Actual result

1. ![screenshot from 2018-10-04 12-16-12](https://user-images.githubusercontent.com/43195414/46457519-3f10f100-c7d0-11e8-9038-fc1fcf08ab03.png)

**Comment by magento-engcom-team** [comment]
Hi @ankurverma5540. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ankurverma5540 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ankurverma5540** [comment]
yes

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ankurverma5540  , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by rahuldambare** [comment]
did u get the solution on this ?
