### ISSUE TITLE
symfony/console dependecy locked at older version

### ISSUE THREAD

**Issue by DaimPiek** [magento/magento2#18384]
### Preconditions
Magento CE/EE 2.1.X, 2.2.X

### Steps to reproduce
1. Install Magento using composer
2. Attempt to find a suitable install candidate for symfony/yaml ('composer require symfony/yaml')

### Expected result
1. symfony/yaml module is installed.

### Actual result
Symfony yaml module can not be installed because of the following constraints: 
- Starting from symfony/dependency-injection 3.4.X, "symfony/yaml":"~3.4|~4.0". And symfony/yaml requires symfony/console: ~3.4|~4.0
- The magento project has set the following requirements for symfony/console
magento/product-community-edition  2.2.5    requires  symfony/console (~2.3, !=2.7.0)         
magento/project-community-edition  2.2.5    requires  symfony/console (v2.8.20 as v2.6.13)

There is no possible release I can use to install symfony/yaml due to constraints.

**Comment by magento-engcom-team** [comment]
Hi @DaimPiek. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DaimPiek do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment]
@DaimPiek: you can actually install `symfony/yaml` 3.3, but it's a bit tricky and will downgrade `symfony/dependency-injection` to a lower compatible version, here's how:

```
$ composer require --no-update symfony/yaml:^3.0
./composer.json has been updated

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Downgrading symfony/dependency-injection (v4.1.6 => v3.3.18): Downloading (100%)
  - Installing symfony/yaml (v3.3.18): Downloading (100%)
Writing lock file
Generating autoload files
```

The trick is to use the `--no-update` flag in the `require` command.
If you follow that up with a full `update` command, composer will put a lot more effort in finding a suitable set of dependencies which work together.

**Comment by DaimPiek** [comment]
@hostep : The issue seems to be resolved by forcing a downgrade of the symfony/dependency-injection package. 

However I don't think this should be the permanent solution, and that the locked version of symfony/console should be upgraded in Magento's composer.json.

**Comment by bartoszkubicki** [comment]
Generally some symfony components are lost in low version comparing to available. If possible they should by constantl upgraded, as many libraries requires newer versions.

**Comment by hostep** [comment]
In Magento 2.3 (currently bèta), the version constraint for `symfony/console` has been increased from [`~2.3`](https://github.com/magento/magento2/blob/2.2.6/composer.json#L49) to [`~4.1.0`](https://github.com/magento/magento2/blob/8f3dd40/composer.json#L50), so that looks like progress :)

Let's close this issue, since it's not really a bug in Magento I think.
