### ISSUE TITLE
Customer address book access issue unable to edit address or add address.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18395]
### Preconditions
1.Tested with Magento 2.2.6
2.PHP 7.1.18 
3.Ubuntu Development System 

### Steps to reproduce

1.Login as customer and click to Address book section.
2.Fatal error will be generate customer is unable to update their address.

### Expected result

![customer_addressbook_issue_](https://user-images.githubusercontent.com/28080068/46531021-5e377d80-c8b9-11e8-8321-15e10f544a0c.png)

### Actual result
1.Customer need to allow to edit or add new address.

### Further discussion
Magento 2.2.5 has solution only copy and past the edit.phtml file from Magento 2.2.5 version.
   vendor/magento/module-customer/view/frontend/templates/address/edit.phtml

**Comment by magento-engcom-team** [comment]
Hi @manishg0. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@manishg0 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by torhoehn** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [Magento instance](https://i-18395-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18395-2-2-6.engcom.dev.magento.com/admin](https://i-18395-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by torhoehn** [comment]
@manishg0 Could not reproduce you issue on vanilla instance so I'll close this issue.

<img width="1440" alt="screenshot 2018-10-05 at 23 43 10" src="https://user-images.githubusercontent.com/1945725/46561929-184ed980-c8fa-11e8-9cf6-9492273902bc.png">

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mirzasahaab** [comment]
Can you provide me the code of this file? 
vendor/magento/module-customer/view/frontend/templates/address/edit.phtml

**Comment by torhoehn** [comment]
@mirzasahaab It's available here: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/view/frontend/templates/address/edit.phtml

**Comment by saverdaj** [comment]
I encountered a very similar issue when upgrading to 2.3.1.  It turns out that a few new arguments were added to the customer edit xml here 
vendor/magento/module-customer/view/frontend/layout/customer_address_form.xml

Since I'm overriding that xml in a custom theme I need to add the additional arguments there as well.  Once the new arguments were added in everything started working as intended

**Comment by torhoehn** [comment]
@saverdaj Thank you for clarifying that it can come to this behaviour if the layout has been extended/overridden.
