### ISSUE TITLE
Tax classes info issue in Magento 2.2.6

### ISSUE THREAD

**Issue by manishmittalm** [magento/magento2#18402]
### Preconditions

1. Magento 2.2.6
2. PHP 7.1.13

### Steps to reproduce

1. Login to Magento admin
2. Store > Configuration > Sales > Tax > Tax Classes 
3. Showing info icon: You can manage customer and product tax classes at Sales->Tax menu

### Expected result

1. You can manage customer and product tax classes at Stores->Tax Rules->Edit Specific class->Addtional Settings

### Actual result

1. Showing info icon: You can manage customer and product tax classes at Sales->Tax menu. This is wrong guidance I can not find any Tax menu under Sales.
2. PFA, for your reference

![configuration settings stores magento admin](https://user-images.githubusercontent.com/37134503/46542078-35c07b00-c8db-11e8-8581-718f50858311.png)

**Comment by magento-engcom-team** [comment]
Hi @manishmittalm. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@manishmittalm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by manishmittalm** [comment]
> @manishmittalm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> *

Yes

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-18402-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18402-2-3-develop.engcom.dev.magento.com/admin](https://i-18402-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-18402-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-18402-2-2-develop.engcom.dev.magento.com/admin](https://i-18402-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-18402-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18402-2-2-6.engcom.dev.magento.com/admin](https://i-18402-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
Hi @manishmittalm 
Looks like the comment you are referencing is not Magento core code. Please check your 3rd party extensions. 

Also try to reproduce the issue on clean Magento instance.

**Comment by manishmittalm** [comment]
That is core Magento issue, I installed Vanilla Magento 2.2.6 and get that notification in that.
I will find more details and then I will share with you :+1:

**Comment by hostep** [comment]
@manishmittalm: the message is defined in the `Vertex_Tax` module. Magento doesn't consider it a core module, even though they include it as a core module. Which is ridiculous.

@okorshenko: I hate to keep bringing this up, but if you ask for a Magento instance, is there a chance it could get installed using composer instead of via a git clone? That way the Vertex module will be included and you'll be able to reproduce the problem.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-18402-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18402-2-3-develop.engcom.dev.magento.com/admin](https://i-18402-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
Hi @hostep @manishmittalm 
thank you for clarification. Issue has been reported in the vendor backlog: https://github.com/magento/ext-vertex/issues/26

**Comment by okorshenko** [comment]
@hostep just to clarify: this issue can not be fixed through the code in this repository. If Community Contributor will take the issue from this backlog, he/she won't be able to reproduce it and fix.

**Comment by hostep** [comment]
Got it! But I still consider this very confusing and issue reports like these will keep happening I'm afraid.

Just out of curiosity, we can't see https://github.com/magento/ext-vertex/, why is this hidden away? Revealing these repo's would help in reporting bugs to those modules and seeing open outstanding issues.

**Comment by maksek** [comment]
@hostep, we are working with extension providers to open the repos.

**Comment by okorshenko** [comment]
We are working right now with all vendors to open the code of all bundled extensions. Once ready, all community members will be able to see all reports or create new reports, as well as contribute any improvements

**Comment by navarr** [comment]
@manishmittalm Thank you for your report.  We have added this to the Vertex internal backlog.

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by navarr** [comment]
@manishmittalm We have updated this wording and have it targeted for release in the 2.3.x line.  You should see this change in 2.3.1

**Comment by Usuario001** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Usuario001. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line
