### ISSUE TITLE
Image Position issue with Associated Products

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#18410]
### Preconditions

1. Magento 2.2.5
2. Nginx
3. MySQL 5.6.x

### Steps to reproduce

1. Upgrade Magento from 2.1.7 to 2.2.5
2. Have product configurable **A** (visibility-catalog,search) and simple associated **X, Y, Z**(visibility-catalog). Simple products **X, Y, Z** is associated with **A**
3. Change the gallery image position of product **X** having 4 gallery images.

### Expected result

1. Changed gallery image position should reflect  when product **X** selected from configurable product **A**
2. Also the changed image position reflects on simple product page visible on category page

### Actual result

1.  Changed images position for product **X** reflecting for simple product page. But when go to configurable product page and select product **X**, changed images orders not reflecting.

**Comment by magento-engcom-team** [comment]
Hi @RishabhRkRai. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@RishabhRkRai do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rishabhrkrai** [comment]
@magento-engcom-team  Any update on this????

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96593`, `MAGETWO-96594` were created

**Comment by sivaschenko** [comment]
Hi @RishabhRkRai thanks for reporting the issue! Considering that this is an appearance problem, it would be really heplful to have the screenshots included in the description

**Comment by bhaveshsurani** [comment]
i am ready to work on this issue #MM19IN

**Comment by magento-engcom-team** [comment]
@bhaveshsurani thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @bhaveshsurani. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by aleromano89** [comment]
Hi @RishabhRkRai, I have tried to reproduce the issue on dev-2.3-develop but the order changes are reflected both on simple product page and on configurable page, by selecting product X.
Can you give me more details in order to reproduce this issue?

thanks

**Comment by ghost** [comment]
Hi @RishabhRkRai thank you for you report, this issue was retested and we can confirm that issue has already fixed in 2.3-develop branch and available on 2.3.1 release.
![deepin-screen-recorder_Select area_20190405145943](https://user-images.githubusercontent.com/40756439/55626276-c0633380-57b3-11e9-83fc-40a551299e17.gif)
