### ISSUE TITLE
Product Images Not Migrated ! Need Help

### ISSUE THREAD

**Issue by nithindyode** [magento/magento2#18411]
Summary of the issue
I was migrating a Magento 1.14.3 website to 2.2.3 version using the migration tool. I have migrated all products, customers, and orders. I copied my media/catalog/product folder to pub/media/catalog/product folder, But the images are not coming in frontend/backend.
    Information on your environment
Magento 2.2.3
    Steps to reproduce
 run the **php bin/magento catalog:image:resize** , but getting an error - Notice: getimagesize(): Read error! in /media/nithin/FCF83FD1F83F88C2/html/icuracaolocal/vendor/magento/module-catalog/Model/Product/Image.php on line 420
    Expected and actual results
Images are not showing at frontend or backend. Already checked the permission and all.

Can anyone please help to resolve the issue??

**Comment by magento-engcom-team** [comment]
Hi @nithindyode. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nithindyode do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by techguysourav** [comment]
To make format valid include these steps.
1.  Summary of the issue
2.   Information on your environment
3.   Steps to reproduce
4.   Expected and actual results

**Comment by okorshenko** [comment]
Hi @nithindyode 
Thank you for your report. If you have issues related to data migration, feel free to report it on the https://github.com/magento/data-migration-tool repository. Otherwise, your report might be lost on magento2 repository. 

Also I would recommend you post your question on the Magento forum or community slack
