### ISSUE TITLE
Magento orders page stuck

### ISSUE THREAD

**Issue by biancatde** [magento/magento2#18421]
### Preconditions

1. version 2.1.14
2. Entered an incorrect date in the search parameters in the Orders search bar, and when Magento couldn't find the results, it is now stuck with the rotating loading circle and will not allow me to do anything on the page. 

### Steps to reproduce

1. enter an invalid date in the search filters in the Orders page(in my case it was 01/20/2009)
2. I also searched a keyword and SKU at the same time. 

### Expected result

1. I expected to be able to try another search.
2. 

### Actual result

1. ![screen shot 2018-10-06 at 11 43 28 am](https://user-images.githubusercontent.com/43893466/46573005-1407d800-c95d-11e8-800c-2ca90ad87958.png)
![screen shot 2018-10-06 at 11 38 26 am](https://user-images.githubusercontent.com/43893466/46572998-f89ccd00-c95c-11e8-9dcf-bf76a4bb827f.png)

2.The screen stays stuck on this loading circle and never lets me clear the search parameters. I tried clearing the browser cookies which didn't work. And also opening it in another browser, but because it always saves the last search you tried, it always brings up the same error.

**Comment by magento-engcom-team** [comment]
Hi @biancatde. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@biancatde do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by biancatde** [comment]
I'm sorry, I don't understand what deploying vanilla Magento is...?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @biancatde thank you for you report, the fix for this issue has already available in 2.2.6 release.
