### ISSUE TITLE
404 page only when user is logged in (SQLSTATE[23000]: Integrity constraint violation: 1452)

### ISSUE THREAD

**Issue by nikmedlabs** [magento/magento2#18438]
Whenever a logged in user tries to do something related to his account, then he is redirected to 404 page. Below, I give 4 cases that the error occurs.
**Case 1.** User tries to login, the page is blank, then if you refresh the user account area appears with a message "We can't show you the wishlist now".
**Case 2.** User is logged in and tries to visit a product page, then he is redirected to the 404 page.
**Case 3.** User tries to add a product to cart, then he is redirected to the 404 page.
**Case 4:** Visitor (not logged in) orders a product and at the success page (after successfully submitting the order) decides to create an account (the system offers it with a button), then the same as **Case 1** happens.

I upgraded from Magento 2.2.0 to 2.2.5, but the problem is still there.

### Preconditions

1. Magento Version 2.2.0 and 2.2.5 (after update).
2. php 7.0.13 on apache and nginx / debian 9.
3. One Website, with Two stores and Two Store Views (one for each store).

### Steps to reproduce
In order to reproduce one has to login first or try to visit a product page so that he can face this 404 error. 

### Expected result

1. The logged in user should be able to visit a product's page.
2. The visitor should be able to login normally without error.

### Actual result

1. The logged in user was redirected to the 404 page (the product link on the browser is the correct one).
2. The visitor saw a blank page, then had to refresh in order to view his account page.

Here is an exception from exception.log file:

[2018-10-07 10:26:49] main.CRITICAL: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mysitedb`.`report_viewed_product_index`, CONSTRAINT `REPORT_VIEWED_PRD_IDX_CSTR_ID_CSTR_ENTT_ENTT_ID` FOREIGN KEY (`customer_id`) REFERENCES `customer_entity_renamed` (`entity_id`) ON D), query was: INSERT  INTO `report_viewed_product_index` (`customer_id`,`product_id`,`store_id`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `customer_id` = VALUES(`customer_id`), `product_id` = VALUES(`product_id`), `store_id` = VALUES(`store_id`) {"exception":"[object] (Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mysitedb`.`report_viewed_product_index`, CONSTRAINT `REPORT_VIEWED_PRD_IDX_CSTR_ID_CSTR_ENTT_ENTT_ID` FOREIGN KEY (`customer_id`) REFERENCES `customer_entity_renamed` (`entity_id`) ON D), query was: INSERT  INTO `report_viewed_product_index` (`customer_id`,`product_id`,`store_id`) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE `customer_id` = VALUES(`customer_id`), `product_id` = VALUES(`product_id`), `store_id` = VALUES(`store_id`) at /home/mysite/domains/mysitedb.mysite.com/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mysitedb`.`report_viewed_product_index`, CONSTRAINT `REPORT_VIEWED_PRD_IDX_CSTR_ID_CSTR_ENTT_ENTT_ID` FOREIGN KEY (`customer_id`) REFERENCES `customer_entity_renamed` (`entity_id`) ON D) at /home/mysite/domains/mysitedb.mysite.com/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"} []

**Comment by magento-engcom-team** [comment]
Hi @nikmedlabs. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nikmedlabs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nikmedlabs** [comment]
> Hi @nikmedlabs. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [yes ]  Summary of the issue
> * [ yes ]  Information on your environment
> * [ yes ]  Steps to reproduce
> * [ yes ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @nikmedlabs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ yes ]  yes
> * [ ]  no

**Comment by samars** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @samars. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @samars, here is your [Magento instance](https://i-18438-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18438-2-2-6.engcom.dev.magento.com/admin](https://i-18438-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gcampedelli** [comment]
I had a similar issue upgrading to Magento 2.2.6 but using a custom step checkout as first step where user can log in. Behavior is something like this. Customer add product to cart. Goes to checkout. Checkout first step only asks email. Customer log in and Magento 2 redirects him to 404. He has to reload checkout in order to proceed. 
Looking at logs, I found that progress bar has been cancelled and after that customer is redirected to 404. No errors in database. 
Hope this can help find the issue.

**Comment by nikmedlabs** [comment]
> I had a similar issue upgrading to Magento 2.2.6 but using a custom step checkout as first step where user can log in. Behavior is something like this. Customer add product to cart. Goes to checkout. Checkout first step only asks email. Customer log in and Magento 2 redirects him to 404. He has to reload checkout in order to proceed.
> Looking at logs, I found that progress bar has been cancelled and after that customer is redirected to 404. No errors in database.
> Hope this can help find the issue.

Thanks, if I figure something out I will post it back.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @nikmedlabs, thank you for you report,   i'm not able to reproduce following steps you described, seems like problem related to you custom modules, So if you have some additional information about steps to reproduce, after that i can reproduce this on clean instance, let me know, If you like to update, please reopen the issue.
