### ISSUE TITLE
Issues facing when upgrading magento 2.1.5 to Magento 2.2.6

### ISSUE THREAD

**Issue by abhisekhranjan** [magento/magento2#18446]
Unable to upgrade Magento2.1.5 to Magento2.2.6

Issues ======================
**Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install magento/product-community-edition 2.2.6
    - Conclusion: don't install magento/product-community-edition 2.2.5
    - Conclusion: don't install magento/product-community-edition 2.2.4
    - Conclusion: don't install magento/product-community-edition 2.2.3
    - Installation request for fooman/pdfcustomiser-m2 ^5.1 -> satisfiable by fooman/pdfcustomiser-m2[5.1.0, 5.1.1, 5.1.2].
    - magento/product-community-edition 2.2.0-rc20 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc21 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc22 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc23 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc30 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.1 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.2 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc20 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc21 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc22 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc23 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0-rc30 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.0 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.1 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.2 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.3 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.4 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.5 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/product-community-edition 2.2.6 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].**
My Composer.json file code is ================
_{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.1.5",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.2.*",
        "composer/composer": "@alpha",
        "magento/data-migration-tool": "2.2.*",
        "mageplaza/magento-2-social-login": "^2.2",
        "fooman/pdfcustomiser-m2": "^5.1"
        
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0",
        "sebastian/phpcpd": "2.0.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "magento": {
            "type": "composer",
            "url": "https://repo.magento.com"
        },
        "fooman": {
            "type": "composer",
            "url": "https://customer-repos.fooman.co.nz/www.vajor.com-b6a0119f1889fc9f8c3f6348fe072faeee063451"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}_

**Comment by magento-engcom-team** [comment]
Hi @abhisekhranjan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abhisekhranjan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @abhisekhranjan   Thank you for you report, I'm not able to reproduce following steps your described.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
