### ISSUE TITLE
Magento version 2.2.6 Alert widget gets close when click anywhere on screen

### ISSUE THREAD

**Issue by asgarh** [magento/magento2#18458]
### Preconditions

1. Magento version 2.2.6
2.

### Steps to reproduce

1. Add product to cart
2.Click on the cart icon at right top of screen
3.Click on delete icon
4.Now click any where on screen the alert widget will close

### Expected result

1.The alert widget should not close until user click cancel button 
2.

### Actual result

1. Alert widget gets close when click any where on screen
2.

**Comment by magento-engcom-team** [comment]
Hi @asgarh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@asgarh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by asgarh** [comment]
@magento-engcom-team give me $VERSION instance

**Comment by asgarh** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @asgarh. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @asgarh, here is your [Magento instance](https://i-18458-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18458-2-2-6.engcom.dev.magento.com/admin](https://i-18458-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by asgarh** [comment]
Yes I confirm that I was able to reproduce the issue on vanilla Magento instance

**Comment by asgarh** [comment]
Yes, I am able to reproduce the issue on vanilla Magento instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @asgarh. Thank you for your report. 
The issue has been fixed in magento/magento2#18865 by @Shubham-Webkul in 2.2-develop branch
Related commit(s):
 - [f59bc17a78570e4c62015b558b24b42094a6e17c](https://github.com/magento/magento2/commit/f59bc17a78570e4c62015b558b24b42094a6e17c)
 - [06b243f659bbe0d25a3c2e03ef447b6e7470e6af](https://github.com/magento/magento2/commit/06b243f659bbe0d25a3c2e03ef447b6e7470e6af)
 - [c3bc361a3274812b72650c00ccbbbadc4c746712](https://github.com/magento/magento2/commit/c3bc361a3274812b72650c00ccbbbadc4c746712)
 - [26a9520d326f4d57c9786791214ca00fa7dd7582](https://github.com/magento/magento2/commit/26a9520d326f4d57c9786791214ca00fa7dd7582)
 - [87167e743b11663bbb8c3420476e5ce7c9856166](https://github.com/magento/magento2/commit/87167e743b11663bbb8c3420476e5ce7c9856166)
 - [c6586ab4ace12c1cdd5adc3f2056e33dda8b1789](https://github.com/magento/magento2/commit/c6586ab4ace12c1cdd5adc3f2056e33dda8b1789)
 - [d40a26c3ee44d8904dabe921774885a7abe3b4d2](https://github.com/magento/magento2/commit/d40a26c3ee44d8904dabe921774885a7abe3b4d2)
 - [84c7391d9bec21d2f26aa99c9d2763e2fb25c559](https://github.com/magento/magento2/commit/84c7391d9bec21d2f26aa99c9d2763e2fb25c559)
 - [e1483f682281bd40b57ec5f5b9b7d87f9d320644](https://github.com/magento/magento2/commit/e1483f682281bd40b57ec5f5b9b7d87f9d320644)
 - [3b2e4e4c6cf0995a26c8ec6fcecc39b8b0fa77ca](https://github.com/magento/magento2/commit/3b2e4e4c6cf0995a26c8ec6fcecc39b8b0fa77ca)
 - [7dc2d1b1f6c7d38b6c672218d6ce71728977fcb2](https://github.com/magento/magento2/commit/7dc2d1b1f6c7d38b6c672218d6ce71728977fcb2)

The fix will be available with the upcoming 2.2.8 release.

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18458-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18458-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18458-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by florincyberion** [comment]
This is wrong and should be reverted. That was the normal expected behaviour with clickableOverlay on.

**Comment by Ouzned** [comment]
This should never have been merged, it broke a basic and correctly working feature
