### ISSUE TITLE
Partial Invoice is not working properly in Magento-2.1.12.

### ISSUE THREAD

**Issue by lovelysetia1992** [magento/magento2#18453]
I have 2 products in order,one is simple product and other is bundle product(dynamic).When I create Invoice for simple product using simple product order_item_id,It show wrong details.I will check through admin and api also.

### Preconditions

1.  Magento ver. 2.1.12
2. PHP Version :7.0.16
3. Window OS

### Steps to reproduce

1. Create An Order with two items.One is Simple Product and other is bundle product.
2. Go to Sales->Order.Click on invoice and generate simple product invoice .I will change quantity of bundle product items 0 and update quantities and Submit invoice.
3. One invoice is generated.

### Expected result

![image](https://user-images.githubusercontent.com/43880389/46598892-5c60fa80-cb03-11e8-90fd-266dfd15ea4b.png)

### Actual result

It show bundle item details also.What is issue in partial invoice.
![image](https://user-images.githubusercontent.com/43880389/46598828-1d32a980-cb03-11e8-86e4-10df6c005ade.png)

**Comment by magento-engcom-team** [comment]
Hi @lovelysetia1992. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lovelysetia1992 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by littlebutty** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @littlebutty. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @littlebutty, here is your [Magento instance](https://i-18453-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18453-2-3-develop.engcom.dev.magento.com/admin](https://i-18453-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lovelysetia1992** [comment]
I will check in  Magento Instance
<https://i-18453-2-3-develop.engcom.dev.magento.com/> .Problem is still
here,it will not be resolved.I will attach one screenshot :

![image](https://user-images.githubusercontent.com/43880389/46604318-74d91100-cb13-11e8-985b-f6ecbcdd501a.png)

Please Guide me.

**Comment by lovelysetia1992** [comment]
Please Resolve my issue @magento-engcom-team .

**Comment by lovelysetia1992** [comment]
When I have two or more items,if one or two is bundle,then create invoice.It show wrong response.Please reply me,its a big issue. @magento-engcom-team

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @lovelysetia1992 thank you for you report this issue has already fixed in 2.3-develop branch.
![selection_182](https://user-images.githubusercontent.com/40756439/47776207-8a002480-dcfa-11e8-8ff4-389414d55053.png)
