### ISSUE TITLE
Reports show results for different date when using GB locale (or other non-US date formats)

### ISSUE THREAD

**Issue by vseager** [magento/magento2#18457]
It appears that when your admin user locale is not set to US, and date inputs are not in US format, for example, dd/mm/yyyy, the data returned from the reports is incorrect.

### Preconditions
1. Magento 2.2.5
2. Admin user interface locale set to 'English (United Kingdom)'

### Steps to reproduce
1. Set the  'Interface Locale' for your admin user to 'English (United Kingdom)'
2. Go to a report, for example `Reports > Products > Ordered`
3. Set the "From" and "To" date (Format will be in English format - dd/mm/yyyy)
4. Click "Refresh"

### Expected result
1. Results for the date range specified, for example, 02/10/2018 should show results for 2nd October 2018.

### Actual result
1. Results for the selected date in US format, for example 02/10/2018 is showing results for 10th February 2018.
2. This has been verified in a live environment where the report is showing products from February which are no longer available and would be impossible to order on the selected date.
3. ![reporting-bug](https://user-images.githubusercontent.com/2035088/46658544-e1531f00-cbaa-11e8-9d81-b584009ed903.png)

**Comment by magento-engcom-team** [comment]
Hi @vseager. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vseager do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by indefinitedevil** [comment]
See #18103. Also fix: https://github.com/magento/magento2/commit/fea3b7a0f9151b3c236ea02475fde4b1793c7a0b

**Comment by missvickih** [comment]
Same issue with data format existing in 2.2.6 with store / user locale set as en_gb; running php 7.1.18.
Date parameters site wide, result in errors and inability to save date rules:
Special price at product level: DateTime::__construct(): Failed to parse time string (24/10/2018) at position 0 (2): Unexpected character
Set date from and to in promotional rules: rule saves but date format is incorrect as above

Is this a known bug being fixed in 2.3.- branches or any patches to correct tested in 2.2.6?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @vseager thank you for you report, this issue has already fixed in 2.3-develop.
![selection_201](https://user-images.githubusercontent.com/40756439/48397881-dc443b00-e727-11e8-9c82-fa8e558840b7.png)
