### ISSUE TITLE
Magento 2 down: replica Tales not found when reindexing!

### ISSUE THREAD

**Issue by mariamghalleb** [magento/magento2#18467]
### Preconditions
1.Magento 2.2.4,
2.PHP 7.0.30

### Steps to reproduce
1. php bin/magento indexer:reset 
2. php bin/magento indexer:reindex & cache:flush

### Expected result
1. Indexes built succefully

### Actual result
1. 

> Table "cataloginventory_stock_status_replica" does not exist Table 
> Table "catalog_product_index_eav_replica" does not exist Table
>  Table "cataloginventory_stock_status_replica" does not exist

2. 
![capture2](https://user-images.githubusercontent.com/28814080/46619957-15d3c600-cb2c-11e8-889d-8b2436baf119.PNG)

Exception Logs only shows this:

> [2018-10-07 10:00:58] main.CRITICAL: SQLSTATE[HY000]: General error: 3 Error writing file './databse_mag2/catalogrule_product__temp30fd3506.frm' (Errcode: 28 - No space left on device), query was: create table catalogrule_product__temp30fd3506 like catalogrule_product {"exception":"[object] (Zend_Db_Statement_Exception(code: 0): SQLSTATE[HY000]: General error: 3 Error writing file './databse_mag2/catalogrule_product__temp30fd3506.frm

System logs shows this:

> [2018-10-08 15:01:05] main.WARNING: Memory size allocated for the temporary table is more than 20% of innodb_buffer_pool_size. Please update innodb_buffer_pool_size or decrease batch size value (which decreases memory usages for the temporary table). Current batch size: 100000; Allocated memory size: 200000000 bytes; InnoDB buffer pool size: 134217728 bytes. [] []

I tried to reset the indexes, i tried setup: upgrade & deployed in vain.

**Comment by magento-engcom-team** [comment]
Hi @mariamghalleb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mariamghalleb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mariamghalleb** [comment]
> Hi @mariamghalleb. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @mariamghalleb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @mariamghalleb Thank you for you report this issue has already fixed in 2.2-develop and 2.3-develop branches.

**Comment by mariamghalleb** [comment]
@engcom-backlog-nazar  how can I fix it on my website? I don't intend to update

**Comment by codesnakers** [comment]
1.) Do a fresh install of the same magento version you're having problems with<br>
2.) export the structure of the tables "catalog_product_index_price_replica" and "catalog_product_index_eav_replica"<br>
3.) import those structures into your magento db where you're facing the issue<br>
4.) run the commands <br>
php bin/magento indexer:reset<br>
php bin/magento indexer:reindex <br>
these steps solved the issue for me in magento 2.2.7
