### ISSUE TITLE
Set maximum Qty Allowed in Shopping Cart is 0 still allow adding to cart

### ISSUE THREAD

**Issue by duongdiep212** [magento/magento2#18477]
### Preconditions

1. Magento Open Source and Commerce 2.2.x
2. PHP 7.1
3. Sample data is installed

### Steps to reproduce

1. Click to edit simple product, then click "Advanced Inventory ", enter 0  in "maximum Qty Allowed in Shopping Cart" field
2. Go to front-end and add this product to cart.

### Expected result

Show message can not add qty to cart :  The most you may purchase is 0.

### Actual result

Still adding qty to cart with no limit.

**Comment by magento-engcom-team** [comment]
Hi @duongdiep212. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@duongdiep212 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by duongdiep212** [comment]
I checked core and found the function below  : 
`if ($stockItem->getMaxSaleQty() && $qty > $stockItem->getMaxSaleQty()) {
            $result->setHasError(true)
                ->setMessage(__('The most you may purchase is %1.', $stockItem->getMaxSaleQty() * 1))
                ->setErrorCode('qty_max')
                ->setQuoteMessage(__('Please correct the quantity for some products.'))
                ->setQuoteMessageIndex('qty');
            return $result;
        }`
you can see it in :  vendor/magento/module-catalog-inventory/Model/StockStateProvider.php

The problem is when I set max qty = 0, so  $stockItem->getMaxSaleQty() return false in this condition , that means it will pass through this function and allow you adding to cart with no limit.

**Comment by pocallaghan** [comment]
Out of curiosity, what's the use case for having a value of 0 for max sale quantity?

**Comment by gelanivishal** [comment]
Yes. We can fix it by  **Maximum Qty Allowed in Shopping Cart** is greater than 0. Let me try it

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by tomekjordan** [comment]
> Out of curiosity, what's the use case for having a value of 0 for max sale quantity?

probably using product in some "catalog" mode without purchasing. but still holding some stock for admin orders etc

**Comment by sidolov** [comment]
Hi @duongdiep212. Thank you for your report. 
The issue has been fixed in magento/magento2#18481 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [d866790f6cec6aeed33f4efb939756079afbf533](https://github.com/magento/magento2/commit/d866790f6cec6aeed33f4efb939756079afbf533)

The fix will be available with the upcoming 2.3.1 release.

**Comment by sidolov** [comment]
Hi @duongdiep212. Thank you for your report. 
The issue has been fixed in magento/magento2#18552 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [db4ac896b7827e73b7948f1744ab40d9c661468f](https://github.com/magento/magento2/commit/db4ac896b7827e73b7948f1744ab40d9c661468f)

The fix will be available with the upcoming 2.2.8 release.

**Comment by duffner** [comment]
Team, 

In addition to #23319 , the use case for 0 in the world of Magento is a value for infinite. Now instead of setting 0, we have to set some artificial number that’s quite high. There’s no such thing as 0 allowed in cart. If there’s a use case for not allowed, the product should be out of stock.  

Please advise.

**Comment by duffner** [comment]
I vote on reverting this commit. If we are not going to revert, please provide solution for not restricting the max amount in the cart
