### ISSUE TITLE
Magento 2 Product image do not show up in Front end and product list thumbnails

### ISSUE THREAD

**Issue by modkore** [magento/magento2#18479]
### Summary

I am working on a project where I have to upload the products in a site. Unfortunately after adding the products in the backend "Images / Videos" section the image is not coming out in front end catalogue page and to the product list section of back end.

### Examples

I am not sure what to do yet on this one so I am not yet doing something for a patch.

**Comment by magento-engcom-team** [comment]
Hi @modkore. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@modkore do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
