### ISSUE TITLE
"Clear Shopping Cart" in Magento Blank theme no longer working after 2.2.6

### ISSUE THREAD

**Issue by perryholden** [magento/magento2#18475]
The "Clear Shopping Cart" button no longer works in the Magento blank theme after the 2.2.6 upgrade.

### Preconditions

1. Magento Open Source and Commerce 2.2.6
2. PHP 7.1.22
3. MySQL Ver 14.14 Distrib 5.6.41-84.1
4. Using the Magento Blank theme (_not_ Luma)
5. Sample data is installed

### Steps to reproduce

1. Ensure that your site is using the Magento blank theme:
	1. In admin, go to CONTENT > Design > Configuration.
	1. In the grid, select your "Default Store View"
	1. Select "Magento Blank" as your "Applied Theme"
	1. Click "Save Configuration"
1. From the frontend, add an item to your cart (e.g. Joust Duffle Bag).
1. Navigate to the cart page.
1. Click "Clear Shopping Cart".

### Expected result

* The cart is cleared.

### Actual result

* The page refreshes, and the cart is never cleared.

### Additional Details

* Before 2.2.6, `vendor/magento/module-checkout/view/frontend/templates/cart/form.phtml` had an empty value for data-mage-init on the form element (e.g. `data-mage-init='{"validation":{}}'`).
* Both the clear cart and the update cart button used the same HTML form, but they used different submit buttons each with a unique "update\_cart\_action" value.
* After 2.2.6, this form had additional validation added: `data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":{ ... }'`
* In this new file `update-shopping-cart.js`, it serializes the data using the serialize method (e.g. `this.element.serialize()`)
* Unfortunately, the `serialize()` method doesn't serialize _button_ values (again, which contains the "update\_cart\_action" value), cause the JS method doesn't know which button was clicked.
* As a result, the $updateAction variable in the update cart controller method (`\Magento\Checkout\Controller\Cart\UpdatePost::execute`) will always be null.
* However, that method will always default to updating the shopping cart, due to the switch call.
* In the Luma theme, the "Clear Shopping Cart" button was removed. So this functionality continued to work normally while still being _technically_ broken.

**Comment by magento-engcom-team** [comment]
Hi @dewayneholden. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dewayneholden do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by neodrg** [comment]
Hi, we encounter the same issu on 2.2.6.

**Comment by magento-engcom-team** [comment]
Hi @prakashpatel07. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by slavvka** [comment]
Hi @dewayneholden. Thank you for your report. 
The issue has been fixed in magento/magento2#18596 by @luukschakenraad in 2.3-develop branch
Related commit(s):
 - [cc3835f69324ec02ca7982259ebb0a41bad17425](https://github.com/magento/magento2/commit/cc3835f69324ec02ca7982259ebb0a41bad17425)

The fix will be available with the upcoming 2.3.1 release.

**Comment by ghost** [comment]
Hi @dewayneholden i'm closing this issue, as this already fixed in 2.3-develop branch.

**Comment by DanielRuf** [comment]
> Hi @dewayneholden i'm closing this issue, as this already fixed in 2.3-develop branch.

Wait, what a bout a backport or do you expect that we all upgrade to 2.3?

**Comment by ghost** [comment]
@DanielRuf but this issue fixed in 2.2-develop also, i  tested

**Comment by ghost** [comment]
@DanielRuf https://github.com/magento/magento2/pull/18597

**Comment by DanielRuf** [comment]
> @DanielRuf #18597

Ok, because this piece of information was missing here. Thanks for the link.
