### ISSUE TITLE
Table flag, column flag_data size is too small, causing bin/magento app:config:import to fail on configurations > 64k

### ISSUE THREAD

**Issue by brian-labelle** [magento/magento2#18489]
### Summary
`bin/magento app:config:import` fails when large config.php configurations are added to the environment due to the `flag` table's `flag_data` column size 

### Preconditions

1. Magento version 2.2.x
2. Large `config.php` configuration (< 64k)

### Steps to reproduce

1. Add a large configuration array to your `config.php` file (> 64k)
2. Run `bin/magento app:config:import`

### Expected result

1. `bin/magento app:config:import` runs successfully, with no errors

### Actual result

1.  `bin/magento app:config:import` fails with the following exception: "Import failed: Unable to unserialize value, string is corrupted."
2. The JSON stored in the `flag_data` is cut off because the column type is "text" with a size of 64k
3. `app:config:import` cannot unserialize the JSON because it is cut off

### Proposed Solution
Increase the column size for `flag.flag_data` in magento2-base installer

### Notes
The Schema setup for this table:
```
->addColumn(
    'flag_data',
    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
    '64k',
    [],
    'Flag Data'
)
```

**Comment by magento-engcom-team** [comment]
Hi @brian-labelle. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@brian-labelle do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by leoquijano** [comment]
I ran into this issue as well, using v2.2.6. It looks like the same issue as the one reported in #11657.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @brian-labelle, thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/11657
