### ISSUE TITLE
Plus char is replaced by space in product attribute dropdown value

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#18493]
When the + char is used for product dropdown attribute's options, after saving the attribute, all the + chars are replaced by spaces.

### Preconditions
1. Magento 2.2.6, 2.2.7-dev
2.

### Steps to reproduce
1. Create a new dropdown product attribute
2. Add several attribute options with + char(s)
3. Save the attribute

### Expected result
1. The attribute options should be saved in the same state as we entered
![1d1576681d](https://user-images.githubusercontent.com/15868188/46682446-3a947000-cbf6-11e8-9b92-9309aa64f2a4.jpg)

### Actual result
1. The + chars is actually replaced by spaces
![3951d41230](https://user-images.githubusercontent.com/15868188/46682699-edfd6480-cbf6-11e8-9378-1a9a2787c0cc.jpg)

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eduard13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18493-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18493-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18493-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by moderncodes** [comment]
We are having this similar issue as well.
We had about 100 different color name, as some colors are ("Black + Red", "Black & Blue",...).
After adding additional simple color (without any special character) then clicking submit, color attributes which already had those special characters are all modified and auto trimmed rest of the text after special character ("Black ", "Black ",...).
Have no choice but manually go through thousands of products and update then match the attributes, unless someone can suggest a better way.

**Comment by eduard13** [comment]
I'm going to work on this one.

**Comment by slavvka** [comment]
hey @eduard13 Thank you for reporting the issue. We are already working in the fix for 2.3 (MAGETWO-94962) and then will port it to 2.2 (MAGETWO-95426)

**Comment by eduard13** [comment]
Hey @slavvka, thank you for informing, should we close the issue, or leave it open till the issue is fixed?

**Comment by slavvka** [comment]
Hey @eduard13 no, leave it open. We will close it once the issue is fixed in both Magento release lines.

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97309`, `MAGETWO-97310` were created

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-18493-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-18493-2-2-6.instances.magento-community.engineering/admin](https://i-18493-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-18493-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-18493-2-2-7.instances.magento-community.engineering/admin](https://i-18493-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @eduard13 
 
The issue was fixed and delivered for 2.2.7 and 2.3.0 in the scope of internal tickets (MAGETWO-94962, MAGETWO-95426)
We also double-cheked described case on 2.2.7 and 2.3.0

 
For 2.2.7 see commits for more details:
 - 9a110d8b06733a8f82fed96cfb377afb06f4e9b2
 - 5e6801e44527a49472975e9e6670970d6f8263a8
 - 8722fa6a5529726fa3bc0291ef57fb159dec699d
 - 2b8896b5fdb8f5eeb9bdb0cf73a04d6b475199aa
 
 
For 2.3.0 see commits for more details:
 - 21fdaddba19cb329b58b6ee2efb74cb2298049ce
 - 3a7a1e358f8352f61c587f690850faf8b82b2282
 - 1550eb5e27f7e520612dcb4fe1d2c86de8ce42d6
 - fd226244e7350fd1ccad97c73ae53ff4d91dd706
 - 40c809f0d82e6bdd49f8624c42907d451f6924fb
 - 187c51a134a736883e78505bb0923259f3ed3daa
 - f90a8bd78ab269fcf7d3e1125a4778daeb37086b
 - 0b0b141e1bc28f1264b9d1bc9d8244b66d113e77
 
This ticket can be closed.
Please, feel free to reopen or create a new one if issue still exists or was not fully fixed

Thank you for feedback and collaboration
