### ISSUE TITLE
Authorize.net DirectPost Error: Sorry, but something went wrong. Please contact the seller.

### ISSUE THREAD

**Issue by jayanta88** [magento/magento2#18496]
### Summary (*)
We've some complaints from the customer they see an error popup saying "Sorry, but something went wrong. Please contact the seller." But order gets processed with Authorize.net DirectPost and they charged.

## Information on your environment
Magento 2.2.2

## Steps to reproduce
Set the authorize.net directpost method in admin with test gateway url and transaction url.
Then in checkout console of chrome you can see javascript error duplicate billing id for 2 payment methods.
When you will enter the test card details and place order, you will see the error but orders get processed. Now if you manually enter the url domain/checkout/onepage/success it will show you the success page with order id.

### Examples (*)
We've tried to replicate the issue with sandbox account and observed the following.

1. https://test.authorize.net/gateway/transact.dll this response is successful.
2. Then in the network tab, we can see the last get request /authorizenet/directpost_payment/redirect/x_invoice_num/1000001457/success/1/controller_action_name/directpost_payment/is_secure/1/
3. Then we see the error popup "Sorry, but something went wrong. Please contact the seller."
4. In the console we see the errors:
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: The page’s settings blocked the loading of a resource at https://staging.com/checkout/ (“frame-ancestors”).
5. In this scenario, if we manually go to checkout/onepage/success page it shows the success message with the order ID.
### Proposed solution
Please let us know.

Thanks

**Comment by magento-engcom-team** [comment]
Hi @jayanta88. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jayanta88 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jayanta88** [comment]
@magento-engcom-team give me 2.2.2 instance

**Comment by magento-engcom-team** [comment]
Hi @jayanta88. Thank you for your request. I'm working on Magento 2.2.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayanta88, here is your [Magento instance](https://i-18496-2-2-2.engcom.dev.magento.com).
Admin access: [https://i-18496-2-2-2.engcom.dev.magento.com/admin](https://i-18496-2-2-2.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jayanta88** [comment]
I confirm that I was able to reproduce the issue on vanilla Magento instance following steps to reproduce.

1. Set the authorize.net directpost method in admin with test gateway url and transaction url.
2. Then in checkout console of chrome you can see javascript error duplicate billing id for 2 payment methods. 
3. When you will enter the test card details and place order, you will see the error but orders get processed.  Now if you manually enter the url domain/checkout/onepage/success it will show you the success page with order id.

check your instance https://i-18496-2-2-2.engcom.dev.magento.com/simple-product.html

Thanks

**Comment by jayanta88** [comment]
I had contacted with Authorize.net they said the below regarding this issue.

This error message is a message from Magento.  You will want to reach out to Magento to find out why they return this message when the transaction was successful.
 
https://support.authorize.net/s/article/Why-Are-My-SIM-Relay-Response-Transactions-Timing-out-After-Submitting-the-Request

**Comment by inkobject** [comment]
@jayanta88 
This thread may shed more light on your observation:
[https://github.com/magento/magento2/issues/12366#issuecomment-420523861](https://github.com/magento/magento2/issues/12366#issuecomment-420523861)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96214`, `MAGETWO-96215` were created

**Comment by jayanta88** [comment]
@magento-engcom-team any solution for this. Transaction and order get successfully but still getting the popup. Please let us know if you have any solution.

**Comment by treii28** [comment]
I'm getting the same response from authorize as jayanta. Contact the magento community. Meanwhile, I have posted my issues with the patch not working to a couple of different threads, and it seems no one associated with the magento code base has even acknowledged yet on any of them that a problem even exists.

After applying the patch, removing the trans_key and the md5hash and adding a new generated signature, trying to process a payment returns a:

"The transaction was declined because the response hash validation failed"

**Comment by treii28** [comment]
Someone pointed out in a similar thread [https://github.com/magento/magento2/issues/21696](https://github.com/magento/magento2/issues/21696) that the authorize console shows the payment as successful but the patched/magento plugin sees an error and thus doesn't complete the checkout.

The item is also gone from the cart.

**Comment by treii28** [comment]
There is also a similar discussion on the Magento support blog:
[https://community.magento.com/t5/Magento-DevBlog/Authorize-Net-Direct-Post-Patch-for-M2-and-M1/bc-p/124989#M445](https://community.magento.com/t5/Magento-DevBlog/Authorize-Net-Direct-Post-Patch-for-M2-and-M1/bc-p/124989#M445)

**Comment by treii28** [comment]
anything new?

**Comment by ihor-sviziev** [comment]
Hi @jayanta88 ,
According to following announcement this extension was already removed from 2.4 version:
https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445

All future collaboration related to this extension should be on Marketplace using "Contacts" or "Bug reports" related to this extension.

I'm closing this issue.
