### ISSUE TITLE
Product are not displaying 

### ISSUE THREAD

**Issue by MuzzamilAli** [magento/magento2#18514]
1. when we are adding some new product they are going out of stock
2. (Cronjobs issue) we tried to set cron job with the help of hosting provider they fail to solve it and we as well kindly help about this topic.
https://www.ojee.pk/beauty-cosmetics/hair-care/hair-extensions-and-treatment
this is the link where you can see product are not displaying after 3

### Preconditions

we are using Magento 2.2.5 and cron job and re-indexing our main issue

1.
2.

### Steps to reproduce

as youtube, we ran commands with Terminal. only they can access this. I ask to send the login details where we can try to do something for clearing cron job and re-indexing issue but they can not be able to share the details. the 1st hosting provider I see they are not able to solve this they don't have tecqnishion in there the whole team. we are trying to make our server for special Magento. anyways after all of these, I saw Report an Issue in the bottom of Magento admin may this will be helpful for us.
when you provide the solution please tell merely cause our hosting provider is not able to do typical 

### Expected result
we are expected form you to solve both issue 1st corn jobs and 2nd product displaying
1. [Screenshots, logs or description]
2.

### Actual result
1.in this picture you can see the corn job error. when we started Magento we see this error that time
https://unsee.cc/3de35174/
2. in this picture we can't see the products after 3
https://unsee.cc/c6230d35/

**Comment by magento-engcom-team** [comment]
Hi @MuzzamilAli. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MuzzamilAli do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by zack6849** [comment]
@MuzzamilAli please attach screenshots to your issue with a hosting service that does not automatically delete them, as without those and no other error description, we have no info to diagnose and fix the issue at hand

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @MuzzamilAli  Thank you for you report, I'm not able to reproduce following steps your described.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
