### ISSUE TITLE
varienImport is not defined

### ISSUE THREAD

**Issue by Besselink** [magento/magento2#18513]
### Preconditions
1. Magento Version 2.2.6

### Steps to reproduce
1. Open Magento 2 Backend Import Page

### Expected result
1. I expect to see the import form

### Actual result
1. I see a page without form (see attachment)
![varienimport](https://user-images.githubusercontent.com/42958654/46736977-a92b0980-cc9a-11e8-8b71-f825d8ec07f4.png)

**Comment by magento-engcom-team** [comment]
Hi @Besselink. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Besselink do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by Besselink** [comment]
The Summary of the issue is, that i can't import anything.

We use PHP7.0 MySQL 5.6 and Magento 2.2.6.

Open just the import page in backend and you will see

i expected to see the import form and i actually see no form

@magento-engcom-team give me 2.2.6 instance

no, i actually have no vanilla instance, where i can reproduce the issue

**Comment by magento-engcom-team** [comment]
Hi @Besselink. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Besselink, here is your [Magento instance](https://i-18513-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18513-2-2-6.engcom.dev.magento.com/admin](https://i-18513-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Besselink** [comment]
many thanks. there is an other error in vanilla but no, i can't reproduce my error in vanilla.
![import](https://user-images.githubusercontent.com/42958654/46752310-1ea7d180-ccbd-11e8-8724-3a170448ded5.png)

**Comment by Besselink** [comment]
well, it seems my error was because the extension mageplaza layered navigation ultimate. after uninstall of this extension all works fine and no errors occurs. the vanilla error above doesn't occur, too. many thanks and feel free to close this issue.
