### ISSUE TITLE
Create custom attribute in catalog category display setting

### ISSUE THREAD

**Issue by sureshtenderwork** [magento/magento2#18510]
We are working to add custom attribute in catalog category display setting. but it not working in my server

could you please check my attached file and let us now where i made mistakes.

[Tendersoftware.zip](https://github.com/magento/magento2/files/2464227/Tendersoftware.zip)

**Comment by magento-engcom-team** [comment]
Hi @sureshtenderwork. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sureshtenderwork do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sureshtenderwork** [comment]
Summary of the issue with working module

**Comment by ishakhsuvarov** [comment]
Hi @sureshtenderwork 

Unfortunately we can not provide any code reviews here, as this issue tracker is intended only for core Magento technical issues. 

You may try discussing your solution at the Magento Stack Exchange or Community Forums.

Thank you
