### ISSUE TITLE
Reports -> Refresh Statistics (and other stats) not showing grid

### ISSUE THREAD

**Issue by rstylenl** [magento/magento2#18511]
Not able te refresh statistics for reports, and not able to see any stats for orders, tax, shipping, etc., etc.

Have the same setup on a different server and i can see the refresh statistic page, and i am able to see the stats for orders, tax, shipping, etc., etc.

### Preconditions

1. Magento CE 2.2.3
2. Nginx
3. PHP 7.

### Steps to reproduce
1. Login to Admin
2. Goto Reports
3. Click Refresh statistics

### Expected result

Expected to see this:
![refresh stats good](https://user-images.githubusercontent.com/6038697/46732043-acb79400-cc8c-11e8-9ab2-f1b4260eacce.png)

### Actual result

Instead i see this:
![refresh stats](https://user-images.githubusercontent.com/6038697/46731778-e2a84880-cc8b-11e8-813f-d31b86708290.png)

**Comment by magento-engcom-team** [comment]
Hi @rstylenl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rstylenl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rstylenl** [comment]
i could not reproduce this on a vanilla installation of Magento 2.2.3.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @rstylenl seems like problem may be related  to your enviroument, i'm not able to reproduce the following steps you described, please provide more information about steps to reproduce, and let me know, if you like to update please reopen the issue.

**Comment by rstylenl** [comment]
@engcom-backlog-nazar It was indeed a Enviroment issue, the problem was related to the Core_config_data table. Thnx for pointing me in the right direction!
