### ISSUE TITLE
Unable to Edit Account Information 2.2.4

### ISSUE THREAD

**Issue by goransl** [magento/magento2#18526]
### Preconditions
Magento 2.2.4

### Steps to reproduce

1. Go to Stores -> Configuration -> Customers -> Customer Configuration
2. Set Show Tax/VAT Number and Show Company as required.

### Expected result

1. Able to Edit Account Information and use Checkout.

### Actual result

1. On clicking checkout, you are rediected to Edit Account Information, where you enter your VAT number and after clicking Save it will throw error  _"Company" is a required value. "Company" length must be equal or greater than 1 characters._
I have even set company name in addres book.

![image](https://user-images.githubusercontent.com/28887142/46798227-a3dcc600-cd51-11e8-94c1-ded0f5aa7329.png)

**Comment by magento-engcom-team** [comment]
Hi @goransleko. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@goransleko do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @nilesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nilesh2jcommerce** [comment]
Hi @magento-engcom-team ,

Can you please provide me 2.2.4 Instance to check this issue ?

**Comment by nilesh2jcommerce** [comment]
Hi @goransleko ,

I have crosschecked this issue on 2.2.4 version and followed yours mentioned step. After set Tax/VAT Number and Company as required.
Click on checkout button for placing order and logically it redirect to account information page to add VAT number as it marked required in admin interface.

But I am not able to generate **error "Company" is a required value. "Company" length must be equal or greater than 1 characters** after adding VAT number details and click on checkout button it redirect properly on checkout page.

**Comment by goransl** [comment]
Hi @nilesh2jcommerce.

Did you try it with user that was registered and didn't have saved company name and tax before you've enabled Show Tax/VAT Number and Show Company as required?

I've noticed if I register new user after enabling Show Tax/VAT Number and Show Company as required or have manually edited user in backend, then it will work as expected.

**Comment by nilesh2jcommerce** [comment]
Hi @goransleko ,

Yes I have checked with registered which was not saved company name and tax before.Then enable Show Tax/VAT Number and Show Company as required.

Working with both registered and New register user.

Can you check same with both and let me know.
