### ISSUE TITLE
magento 2 Special price of 0 is not display on frontend

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#18539]
I am having big problems with special price after updating to Magento 2.2.6.

Steps:

- install a Magento 2.2.6 vanilla
- create a product with regular price
- edit that product and add a special price to 0 

Expected:

you should see the 0 special price being shown on the frontend

Actual:

you can't see the 0 special price.

**Comment by magento-engcom-team** [comment]
Hi @testmagento2. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@testmagento2 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by testmagento2** [comment]
Hi
I found a temporary solution by create catalog price rule and it changed the price to 0
