### ISSUE TITLE
WYSIWYG-Editor Insert Image-Popup is not working correctly with multiple WYSIWYG-Editors on page

### ISSUE THREAD

**Issue by 4ctobias** [magento/magento2#18548]
### Preconditions
Two or more wysiwyg-editors on the catalog product edit page, only the first one is in wysiwyg-mode - at least the last editor in the same "block" (eg. content) is hidden/in plain text-area-mode. 

Tested with Magento 2.2.6

### Steps to reproduce
1. Open the catalog product edit page
2. Open the "content" area"
3. Enable the WYSIWYG-Mode for the Description 
4. Hide the last editor in the same area (eg. Short Description or ItemDescV)
5. Click on Insert Image in the Description Editor
6. Click on the browse-icon for the Image URL
7. Select a image from the media browser
8. Click on insert file

### Expected result

1. The image URL is pushed into the field "Image URL" within the Insert/Edit Image dialog
2. No HTML-Code is inserted yet in the WYSIWYG-Editor

### Actual result

1. The Image URL field stays empty
2. An img-Tag is inserted in the non-editor of the last editor-element with the selected image URL. This happens only if the last editor in the same area is hidden.

**Comment by magento-engcom-team** [comment]
Hi @4ctobias. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@4ctobias do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by 4ctobias** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @4ctobias. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @4ctobias, here is your [Magento instance](https://i-18548-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18548-2-2-6.engcom.dev.magento.com/admin](https://i-18548-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 4ctobias** [comment]
@magento-engcom-team Yes, I was able to reproduce the issue on the vanilla Magento instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @4ctobias. Thanks for the report. This problem has already been fixed on 2.3 develop

**Comment by Ctucker9233** [comment]
@engcom-backlog-tomash This issue was reported against 2.2. Is there a backport?

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-18548-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-18548-2-2-develop.instances.magento-community.engineering/admin](https://i-18548-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99072` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @4ctobias. Thank you for your report. 
The issue has been fixed in magento/magento2#22174 by @Nazar65 in 2.2-develop branch
Related commit(s):
 - [8611d14d2cd91683348d4df075e1ba7df6171a0d](https://github.com/magento/magento2/commit/8611d14d2cd91683348d4df075e1ba7df6171a0d)
 - [bbe03ea8d2e5394b8e02ad9a8b6c0762ffd64bd9](https://github.com/magento/magento2/commit/bbe03ea8d2e5394b8e02ad9a8b6c0762ffd64bd9)
 - [84f0af856f3c0d81463963b5b2fa55567f16ae05](https://github.com/magento/magento2/commit/84f0af856f3c0d81463963b5b2fa55567f16ae05)

The fix will be available with the upcoming 2.2.9 release.

**Comment by VladimirZaets** [comment]
Hi @4ctobias. Thank you for your report. 
The issue has been fixed in magento/magento2#25556 by @engcom-Golf in 2.3-develop branch
Related commit(s):
 - [f22905662aeda6a0f2c073d650326dd6c2a6fd93](https://github.com/magento/magento2/commit/f22905662aeda6a0f2c073d650326dd6c2a6fd93)
 - [a07627c9b0c8dcb600cc1109a65c5a08ab375a71](https://github.com/magento/magento2/commit/a07627c9b0c8dcb600cc1109a65c5a08ab375a71)
 - [8e39f49b48692f2e820066815244e8532c247fde](https://github.com/magento/magento2/commit/8e39f49b48692f2e820066815244e8532c247fde)
 - [3be5ac8e2e83415b8cafc340486b298038ed0421](https://github.com/magento/magento2/commit/3be5ac8e2e83415b8cafc340486b298038ed0421)
 - [76a866ec70987dfb0e1c778db472a06c6d738781](https://github.com/magento/magento2/commit/76a866ec70987dfb0e1c778db472a06c6d738781)
 - [26dca1007e2458e29419ae5ecf7b77e0c1560658](https://github.com/magento/magento2/commit/26dca1007e2458e29419ae5ecf7b77e0c1560658)

The fix will be available with the upcoming 2.3.5 release.
