### ISSUE TITLE
Unable to reposition products in a grouped product across multiple pages

### ISSUE THREAD

**Issue by mjohns34** [magento/magento2#18542]
### Preconditions

1. Magento 2.2.6 CE is installed.
2. Create a grouped product.
3. Add >20 associated products to the grouped product.

### Steps to reproduce

1. In the admin, navigate to Catalog > Products and edit a grouped product with more than 20 products in the group (such that the product list is divided into 2 or more pages).
2. Try to drag & drop a product from the first page to the second page (or vice versa).

### Expected result

I should be able to update the position of a product from one page to another page, or there should be an option to disable paging so that I can position products wherever I want within the group.

### Actual result

It is impossible to reposition a product from one page to another without removing and then re-adding the products in the desired order (which can be tedious).

![grouped_products_issue](https://user-images.githubusercontent.com/8883142/46837038-232dc200-cd71-11e8-8282-45fef5cffea5.png)

**Comment by magento-engcom-team** [comment]
Hi @mjohns34. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mjohns34 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by mjohns34** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @mjohns34. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @mjohns34, here is your [Magento instance](https://i-18542-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18542-2-2-6.engcom.dev.magento.com/admin](https://i-18542-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mjohns34** [comment]
@magento-engcom-team Yes, I was able to reproduce the issue on the vanilla Magento instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @mjohns34  thank you for you report, i'm closing this as duplicate for this -> https://github.com/magento/magento2/issues/15219
