### ISSUE TITLE
Step 2 : Add a Database - "Next" button doesn't work

### ISSUE THREAD

**Issue by nogoodskam** [magento/magento2#18549]
Hello!
During "Step 2: Add a Database" the "Next" button doesn't work. It doesn't matter what data is entered into the different fields, right or wrong, pressing the "Next" button doesn't do anything. No error messages, no confirmation, nothing.
I'm using Magento 2.2.6 on wamp 3.1.4
Thank you!

**Comment by magento-engcom-team** [comment]
Hi @nogoodskam. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nogoodskam do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pocallaghan** [comment]
Windows isn't officially a supported operating system - https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html, so I'm not sure how much traction you'll get with this.

**Comment by nogoodskam** [comment]
I used xampp instead of wamp, and it resolve the issue
