### ISSUE TITLE
Import/Export settings problem

### ISSUE THREAD

**Issue by radicalbyte** [magento/magento2#18543]
### Preconditions
Magento 2.2.4

### Steps to reproduce
Click on systems > Import or Export > select attribute and no further options appear.

### Expected result

When you select an attribute, Further options appear to import or export

### Actual result

Nothing happened. No options appeared, No error appeared.

Note: import history still reads a CSV upload in progress since 2 days ago  and many other previously as well( if this could be the problem)

**Comment by magento-engcom-team** [comment]
Hi @radicalbyte. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@radicalbyte do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by radicalbyte** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @radicalbyte. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @radicalbyte, here is your [Magento instance](https://i-18543-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-18543-2-2-4.engcom.dev.magento.com/admin](https://i-18543-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by radicalbyte** [comment]
I confirm that i was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

Yes.

 - On my machine selecting any attributes in import or export does not  show further options
