### ISSUE TITLE
Getting error on compile time :  Cannot use Magento\Sales\Api\Data\OrderInterface as OrderInterface

### ISSUE THREAD

**Issue by mage2sol** [magento/magento2#18551]
### Summary
I recently install 2.2.6 with fresh code. its working good. but after upgrade and deploy i got below error:

Fatal error: Cannot use Magento\Sales\Api\Data\OrderInterface as OrderInterface because the name is already in use in /opt/lampp/htdocs/sambazon/vendor/temando/module-shipping-m2/Model/BatchProvider.php on line 7

### Steps to reproduce
Step 1 : bin/magento setup:upgrade -- **Success**
Step 2 : bin/magento setup:static-content:deploy -- **Success**
Step 3 : bin/magento setup:di:compile -- **Got Error** (Fatal error: Cannot use Magento\Sales\Api\Data\OrderInterface as OrderInterface because the name is already in use in /opt/lampp/htdocs/sambazon/vendor/temando/module-shipping-m2/Model/BatchProvider.php on line 7)

### Expected and actual results

**Expected** -- Compile with success message
**actual** -- Got Error

**Comment by magento-engcom-team** [comment]
Hi @mage2sol. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mage2sol do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mage2sol** [comment]
Any update please?

**Comment by mage2sol** [comment]
Close issue to no updates from team.
