### ISSUE TITLE
Magento 2.2.6 Default values are not rendering on Wishlist product edit page.

### ISSUE THREAD

**Issue by kirtinariya1** [magento/magento2#18555]
### Preconditions (*)

Magento 2.2.6

### Steps to reproduce (*)

1.Navigate to any configurable product page on the frontend.

2.Select the options and add the product to wishlist.

3.Navigate to My Wishlist page.

4.Click on Edit link given in wishlist item.

### Expected result (*)
1.It should auto-select the options on wishlist product edit page.
![expected-result](https://user-images.githubusercontent.com/28681937/46864768-f6dd7880-ce38-11e8-881e-150dfe9d1daa.png)

### Actual result (*)
It doesn't auto-select the options.
![actual-result](https://user-images.githubusercontent.com/28681937/46864813-12e11a00-ce39-11e8-9248-d9d65876590b.png)

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kirtinariya1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by kirtinariya1** [comment]
![list-page-product](https://user-images.githubusercontent.com/28681937/46865015-a581b900-ce39-11e8-9869-79fe76f7f6ca.png)
![wishlistproduct](https://user-images.githubusercontent.com/28681937/46865016-a581b900-ce39-11e8-8847-a6df09043746.png)

**Comment by pocallaghan** [comment]
I can confirm I can replicate this on 2.3-dev, it appears to only be an issue for swatch attributes, default drop-downs do appear to pre-populate.

**Comment by paco44** [comment]
#mm18mx

**Comment by paco44** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @paco44. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @paco44, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18555-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18555-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18555-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @paco44. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by paco44** [comment]
@magento-engcom-team give me 2.2.6-develop instance

**Comment by magento-engcom-team** [comment]
Hi @paco44. Thank you for your request. I'm working on Magento 2.2.6-develop instance for you

**Comment by webkul-ratnesh** [comment]
@paco44 I dont think this is an issue, because the same feature in propagating from magento 1 era, we can add this as a feature enhancement.

**Comment by webkul-ratnesh** [comment]
@paco44 I tried replicate the issue at my end and got to know that it is just caching issue. If you clear cache it will work correctly.

**Comment by webkul-ratnesh** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @webkul-ratnesh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@webkul-ratnesh Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@webkul-ratnesh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96025` were created

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1. Thank you for your report. 
The issue has been fixed in magento/magento2#18967 by @webkul-ratnesh in 2.2-develop branch
Related commit(s):
 - [2bb03296773ab56a8cc5ff46fb46dfad27c3270f](https://github.com/magento/magento2/commit/2bb03296773ab56a8cc5ff46fb46dfad27c3270f)

The fix will be available with the upcoming 2.2.8 release.
