### ISSUE TITLE
Internet Explorer 11: Edit customer in backend leads sometimes to a "loading circle" and error object does not support method "includes"

### ISSUE THREAD

**Issue by amenk** [magento/magento2#18562]
### Preconditions (*)
1. Magento 2.2.6
2. Internet Explorer 11

### Steps to reproduce (*)
1. Backend
2. Customers
3. All Customers
4. Choose user
5.  Click edit
6. Screen does not load, getting javascript error 
"object does not support method includes"

It is not always repeatable, but the error cause is clear (see below) and it should easily be fixable

### Expected result (*)

1. Screen loads

### Solution

Do not use "includes" which is not understood by Internet Explorer 11 in

https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Ui/view/base/web/js/form/element/country.js#L52

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amenk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by ghost** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18562-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18562-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18562-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
i tried to login to admin panel on Edge and IE 11 but was unsuccessful. :(
unable to check issue.

**Comment by amenk** [comment]
Seems to be an additional bug? Which kind of error did you get?

**Comment by sidolov** [comment]
Hi @amenk. Thank you for your report. 
The issue has been fixed in magento/magento2#19010 by @omiroshnichenko in 2.3-develop branch
Related commit(s):
 - [ed26e551c5f54ead331d0187316269eddc3dff74](https://github.com/magento/magento2/commit/ed26e551c5f54ead331d0187316269eddc3dff74)

The fix will be available with the upcoming 2.3.1 release.
