### ISSUE TITLE
Saving multiselect attribute, in some condition, doesn't work.

### ISSUE THREAD

**Issue by U12358** [magento/magento2#18579]
### Preconditions (*)

Bug was found on EE 2.1.4
	vendor/magento/module-catalog-message-bus/Plugin/Model/ResourceModel/Product.php::62
	vendor/magento/module-catalog-message-bus/Product/Mapper.php::116
		$magentoProduct->getCustomAttributes()

Also Bug present on CE 2.2.6

### Steps to reproduce (*)
You can reproduce bug as insert $product->getCustomAttributes() into save controller, see screenshot.
After that change multiselect attributes in backend and save product

![screenshot from 2018-10-13 09-58-24](https://user-images.githubusercontent.com/813985/46902758-7f105c00-ced3-11e8-91bb-5b2aebba939c.png)

### Expected result (*)
1. Must save multiselect attribute

### Actual result (*)
1. Doesnt save multiselect attribute

**Comment by magento-engcom-team** [comment]
Hi @SKovbel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@SKovbel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by U12358** [comment]
looks like old problem

    MAGETWO-90336: Calling the getCustomAttributes() method on a product instance before it is saved, internal _data property structure is changed and extracted incorrectly before saved

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @SKovbel thank you for you report, this issue has alredy fixed in 2.3-develop.
