### ISSUE TITLE
On sales/order_create/loadBlock/block Customer tier price remove

### ISSUE THREAD

**Issue by ghost** [magento/magento2#18577]
### Preconditions (*)
1. Magento 2.2.5 
2. PHP 7.0
### Steps to reproduce (*)
1.  Login to Magento Admin
2.  Sales -> Order
3.  Create Order
4.  add product which have tier price for different customer group like https://prnt.sc/l5jtqy
5. after add to cart click on get shipping method or select customer group from drop down or just refresh page .
6. **After remove product tier price removed and based price applied.**  

### Expected result (*)
Product tier price must remain as per customer group

### Actual result (*)
instead of product tier price (as per customer group price) product base price applied after refresh admin create order page

**Comment by magento-engcom-team** [comment]
Hi @navinbhudiya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@navinbhudiya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@magento-engcom-team give me $2.2.5 instance

**Comment by nicobatty** [comment]
I managed to reproduce it on a vanilla 2.2.6 instance and I figured out the root cause, though I haven't look into a fix at the moment.

### How to reproduce it:

* Create a new website (ie. B2B Website).
* Change the price configuration to be Per Website instead of Global.
* Create a product of price 30 available on both websites.
* Add a tier price for [B2B Website | Retailer] with a quantity of 1 and a price of 10.
* Create a new order on the B2B Website and setting the customer group to Retailer.
* Add the product with the "Add Products" button (the product is set to the tier price).

### Expected Result:

* Click on the "Update Items and Quantities" button. (Tier price remains).

### Actual Result:

* Click on the "Update Items and Quantities" button. (Tier price is removed and the product is back to the default price).

### The root cause:

Basically, when the product is added, it calls the addProduct quote function which load the entire product for the correct store including the `tier_price` information. Which is why there is no problem with the "Add Product" action.

The issue is that the load/block action (ie when you do Updated Items and Quantities) goes through the collection and add the tier price separately to the object.

The issue is that at one point, to link the tier price info with the product objects, it is trying to get the product website ID from the product model store ID. The issue is that the product collection doesn't have any `store_id` so when `$object->getStoreId()` is called, it is sending back the [storeManager store ID](https://github.com/magento/magento2/blob/82b50ac63fddad61d7767ffcd7c560bcb5193b1d/app/code/Magento/Catalog/Model/Product.php#L530).

So in this example, $object->getStoreId() will send back a store ID of 1 even though it should send back a store ID of 2.

You can see the error here when the load/block action is called:

https://github.com/magento/magento2/blob/82b50ac63fddad61d7767ffcd7c560bcb5193b1d/app/code/Magento/Catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php#L338


You can also debug here to see that the tier price is missing from the product model here:

https://github.com/magento/magento2/blob/82b50ac63fddad61d7767ffcd7c560bcb5193b1d/app/code/Magento/Quote/Model/Quote/Address/Total/Subtotal.php#L93

**Comment by magento360** [comment]
@nicobatty  issue is exactly you mentioned..  I tried completely by using Xdebugger when we Click on  "Update Items and Quantities"  it never use the same storeId that was at the time of  'addProducts'.
However if i add group price for "All Websites" then it work fine.
Below mentioned method is only called when clicking on 'addProducts' and then never get called again.
this may be reason of this bug. 

[magento2/app/code/Magento/Catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php](https://github.com/magento/magento2/blob/82b50ac63fddad61d7767ffcd7c560bcb5193b1d/app/code/Magento/Catalog/Model/Product/Attribute/Backend/GroupPrice/AbstractGroupPrice.php#L338)
` /**
     * Assign group prices to product data
     *
     * @param \Magento\Catalog\Model\Product $object
     * @return $this
     */

    public function afterLoad($object)
    {
        $data = $this->_getResource()->loadPriceData(
            $object->getData($this->getMetadataPool()->getMetadata(ProductInterface::class)->getLinkField()),
            $this->getWebsiteId($object->getStoreId())
        );
        $this->setPriceData($object, $data);
        return $this;
    }`

@nicobatty @magento-engcom-team  It would be great if you can post any solution for the same.

Thanks

**Comment by nicobatty** [comment]
Hi @vishal-magento360,

Since you asked for it, I just made a PR: #18784

@navinbhudiya

**Comment by magento360** [comment]
@nicobatty  thanks for the solution. But Unfortunately it doesn't fix my problem. still getting same problem.

Situation:  There are Two Website with Two Stores each . 
               a) Online  ->
               b) B2B -> a) Trade b) Bulk
in B2B scenario if tier price is allowed for only Bulk  ( Store b) then when we click on  "**Update Items and Quantities"**   it took base price of Store a ( trade in this case )

or If tier/group price is allowed for only Trade ( Store a ) then when we click on  "**Update Items and Quantities"**   it took base price of Store b ( Bulk in this case )

So reverse behaviour is happening. 

@nicobatty  I applied all changes as you mentioned in #18784  but still no luck. :( 

looking forward for more update on this issue. 

@nicobatty Thanks again

**Comment by magento360** [comment]
@nicobatty  @magento-engcom-team  any update on this issue ? kindly response.
Thanks

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Thanks @navinbhudiya  for the report. This problem has already been fixed on 2.2 develop and 2.3 develop

**Comment by magento360** [comment]
@engcom-backlog-andrii  can you please share commit id for the solution  applied , so i can try at my setup.
Thanks

**Comment by ghost** [comment]
@engcom-backlog-andrii can you please share commit id for the solution applied, so I can try at my setup.
Thanks

**Comment by ghost** [comment]
Hi @vishal-magento360, sorry i'm can't find related commit, maybe this was fixed by core team.
