### ISSUE TITLE
SHOWING INDEX.PHP FILE CODE ON MY MAGENTO2 WEBSITE JUST UPGRADE 16.04 TO 18.04 I have mangeto2.2

### ISSUE THREAD

**Issue by talhachance4u** [magento/magento2#18582]

**Comment by magento-engcom-team** [comment]
Hi @talhachance4u. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@talhachance4u do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by talhachance4u** [comment]
I have magento2.2 hosted on ec2 with rds just upgraded ubutnut16.04 to 18.04 
showing index.php page and mysql.php same thing showing code on both page

**Comment by gwharton** [comment]
Firstly, showing php code in web browser is a web server configuration issue, nothing to do with magento.

Secondly, Magento 2.2 will not run on Ubuntu 18.04 as Magento 2.2 does not support PHP 7.2 which comes on Ubuntu 18.04.

**Comment by talhachance4u** [comment]
Hi Thanks 
I did it 
Please see what I did 
I have installed Magento2.2 on ubuntu 16.4/PHP7.0 

I have installed theme from Template Monster (magetique) and add 200 products with 20 categories.

I was using Adminer for managing mysql .

I was using ec2 and rds.

now i have upgraded ubuntu 18.04 with php7.2 and It   stopped working

but As you said
I have downgraded php7.2 with php 7.1
Its working but 
I can't see any product 
I want to get back to my previous data with  200 product and 20 categories Will it be possible ?



when I looked with command show databases:

its not showing my databases.



but when i connect with RDS ec2  (mysql -h magentodb.*********.eu-west-2.rds.amazonaws.com -u magento_user -p 

Enter password:******) and try show databases; its showing my database;
