### ISSUE TITLE
Calendar Icon aligement Issue 

### ISSUE THREAD

**Issue by jignesh26** [magento/magento2#18581]
## Preconditions (*)
1.  2.2.7-dev

### Steps to reproduce (*)
1. Open the special price for simple products 
2. ![screenshot from 2018-10-13 14-16-08](https://user-images.githubusercontent.com/21121564/46903539-2ac9a400-cef4-11e8-853e-83e3c8895089.png)

### Expected result (*)

1. Alignment of Icon of selecting the calendar from and to

### Actual result (*)
1.  It should be properly aligned.
2.

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jignesh26 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by jignesh26** [comment]
@magento-engcom-team vanilla instance

**Comment by SyntaxKay** [comment]
Currently i am working this issue

**Comment by jignesh26** [comment]
@speedy008 Thanks for working on this.

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@speedy008 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by SyntaxKay** [comment]
Kindly note i have resolved In 2.2-develop and working on 2.3-develop 
i'll update till tomorrow once i resolved the issue.

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for your report. 
The issue has been fixed in magento/magento2#18593 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [a2b163b8d1dce7d8cc8c1e34a2e0ffa9e83d74d3](https://github.com/magento/magento2/commit/a2b163b8d1dce7d8cc8c1e34a2e0ffa9e83d74d3)

The fix will be available with the upcoming 2.2.8 release.

**Comment by slavvka** [comment]
Hi @jignesh26. Thank you for your report. 
The issue has been fixed in magento/magento2#18638 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [039c88dfdd6a6ad2cdb6031f52c07a87afeded28](https://github.com/magento/magento2/commit/039c88dfdd6a6ad2cdb6031f52c07a87afeded28)

The fix will be available with the upcoming 2.3.1 release.
