### ISSUE TITLE
Unable to save Dropdown Product Attribute Value that contains an " & "

### ISSUE THREAD

**Issue by jfahrni** [magento/magento2#18602]
After the last update, some of our Product-Attribute Values are suddenly strangely truncated. We can reproduce this behavior with a fresh Magento 2.2.6 installation: if a value contains an " & " it will be cut at this point (when saving) and only the first part will remain as  value.

### Preconditions (*)
1.  Fresh installation via Composer 
2. Magento 2.2.6 CE

### Steps to reproduce (*)
1. Go  to Stores => Attributes => Product
2. Add New Attribute
3. "Catalog Input Type for Store Owner" => Dropdown
4. Add Option: String that contains an &  (Example: "Dolce & Cabana")
5. Save (or Save and Continue Edit)

<img width="917" alt="screenshot_ 2018-10-13 at 22 16 46" src="https://user-images.githubusercontent.com/6941605/46909645-11e1e280-cf36-11e8-898c-4627cb56d0c1.png">

### Expected result (*)
1. The value (Value of your Option) is saved as entered

### Actual result (*)
1. Only the part bevor the & remains as Value of this Option
<img width="922" alt="screenshot_ 2018-10-13 at 22 19 59" src="https://user-images.githubusercontent.com/6941605/46909650-2a51fd00-cf36-11e8-9ede-6ae351e15943.png">

**Comment by magento-engcom-team** [comment]
Hi @jfahrni. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jfahrni do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment]
Let's close this one as it duplicates https://github.com/magento/magento2/issues/18263, thanks for the report though @jfahrni!
It looks like Magento is already fixing it internally based on [this comment](https://github.com/magento/magento2/pull/18293#issuecomment-425209668).
