### ISSUE TITLE
Customizeable options has a hidden dropdown option

### ISSUE THREAD

**Issue by icecoldPHP** [magento/magento2#18603]
### Preconditions (*)

1. Version 2.2.6
2. php7.1
3. debian9

### Steps to reproduce (*)

1. create product
2. add customizeable option of type file
3. save product
4. after save the file type has a default dropdown option so you can't save the product again
5. change customizeable option to dropdown
6. remove option
7. change type back to file
8. save btn works again

### Expected result (*)

1. to be able to just save the form without any extra steps

### Actual result (*)

https://www.vioms.com/assets/bugs/out-22.gif

**Comment by magento-engcom-team** [comment]
Hi @icecoldPHP. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@icecoldPHP do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by icecoldPHP** [comment]
This issue was due to the importer that added some records to catalog_product_option_type_title
which didn't belong there
