### ISSUE TITLE
Missing Fixed Product Tax total on PDF

### ISSUE THREAD

**Issue by Detzler** [magento/magento2#18617]
When using FPT, the FPT-total show up at the cart/checkout but is missing at the pdf invoice.

### Preconditions (*)
1. Magento v2.2.5
2. PHP7.1

### Steps to reproduce (*)

1. Activate FPT
2. Configure a product to have FPT
3. Place an order

### Expected result (*)

1. You should see a FPT-total in the pdf invoice

### Actual result (*)

1. FPT-total is missing

<img width="342" alt="bildschirmfoto 2018-10-15 um 13 25 26" src="https://user-images.githubusercontent.com/1556434/46948281-cdf9f500-d07d-11e8-9f09-9191b75eb0bf.png">

<img width="675" alt="bildschirmfoto 2018-10-15 um 13 25 16" src="https://user-images.githubusercontent.com/1556434/46948282-ce928b80-d07d-11e8-998b-33c26e22c70e.png">

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Detzler do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Detzler** [comment]
@magento-engcom-team give me 2.2 instance

**Comment by Detzler** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Detzler, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18617-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18617-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18617-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Detzler** [comment]
I have created an order. Check the pdf invoice in backend. The FPT is missing.

**Comment by Detzler** [comment]
> @Detzler do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

yes

**Comment by mahesh-rajawat** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95970` were created

**Comment by Cahoo** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@Cahoo thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @Cahoo. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#18649 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [382e550fe3161fb667f4673d53066d4918aedb74](https://github.com/magento/magento2/commit/382e550fe3161fb667f4673d53066d4918aedb74)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @Detzler. Thank you for your report. 
The issue has been fixed in magento/magento2#19061 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [73ff7cbc55cb1bbde88a96421daa5410f1fdd8c9](https://github.com/magento/magento2/commit/73ff7cbc55cb1bbde88a96421daa5410f1fdd8c9)

The fix will be available with the upcoming 2.3.1 release.
