### ISSUE TITLE
Field restriction incompatibilities between klarna_core_order and sales_order_payment last_trans_id

### ISSUE THREAD

**Issue by iancassidyweb** [magento/magento2#18615]
### Overview

- Klarna Orders have an identifier which is 36 characters long
- The **sales_order_payment** table has a column **last_trans_id** which stores the id of the transaction. 
- This column has a limit of 32 characters. [See Schema](https://github.com/magento/magento2/blob/2.2.6/app/code/Magento/Sales/Setup/InstallSchema.php#L2008-L2012)
- As Magento supports multiple 3rd party payment gateways, a field length of 32 characters is inconsistent with that of third party payment gateways. 
- See examples below.
    - **Table**: amazon_sales_order -> **Row**: amazon_order_reference_id  (_varchar 255_)
    - **Tabe**: klarna_core_order -> **Row**: klarna_order_id (_varchar 255_)
- At this point in time, this only affects Klarna orders as they have a length of 36 characters however this could also potentially impact Amazon orders in the future, if the length of the order reference increases beyond 32 characters.

### Preconditions (*)
- Clean installation of Magento 2.2.5 or Magento 2.2.6
- Configure Klarna in Sandbox Mode 

### Steps to reproduce (*)
1. Place an order in the Klarna Sandbox
2. Load the **sales_order_payment** table and observe the value inside last_trans_id column
3. Compare this value with the value in the **klarna_core_order** table
4. You will see the value inside **last_trans_id** is 4 characters shorter than that in the **klarna_core_order** table which is down to the table schema.

### Expected result (*)
1. When placing an order with Klarna the full order reference should be stored in the:
- Row**sales_** **last_trans_id** column.

### Actual result (*)
1. The value recorded in the last_trans_id column is 4 characters short. 

In order to resolve the issue the structure for 'sales_order_payment' 'last_trans_id' should be updated to varchar 255 so that it is in-line with 3rd party payment gateways. 

### Screenshots
![amazon_sales_order](https://user-images.githubusercontent.com/8160762/46941815-de04db00-d063-11e8-948c-76e6cdd8be3e.png)
![klarna_core_order](https://user-images.githubusercontent.com/8160762/46941816-de04db00-d063-11e8-87f6-53bc7906002e.png)
![sales_order_payment](https://user-images.githubusercontent.com/8160762/46941817-de04db00-d063-11e8-8a2b-a0f80a6b7a6f.png)

**Comment by magento-engcom-team** [comment]
Hi @iancassidyweb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@iancassidyweb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by iancassidyweb** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iancassidyweb. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iancassidyweb, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18615-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18615-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18615-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95975`, `MAGETWO-95976` were created

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by agorbulin** [comment]
Picking up.

**Comment by magento-engcom-team** [comment]
Hi @iancassidyweb. Thank you for your report. 
The issue has been fixed in magento/magento2#18621 by @iancassidyweb in 2.2-develop branch
Related commit(s):
 - [172ecf6f1d37825bfb72db4517c1653b047c01c3](https://github.com/magento/magento2/commit/172ecf6f1d37825bfb72db4517c1653b047c01c3)
 - [3590785e68331e7ab30dbc2f6c974f8f7a45b58a](https://github.com/magento/magento2/commit/3590785e68331e7ab30dbc2f6c974f8f7a45b58a)
 - [6d33140bf22dade3c3069933c846c12d72182154](https://github.com/magento/magento2/commit/6d33140bf22dade3c3069933c846c12d72182154)
 - [dd753a17c910a49c600b62d6db3b5e9f8961b9e4](https://github.com/magento/magento2/commit/dd753a17c910a49c600b62d6db3b5e9f8961b9e4)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @iancassidyweb. Thank you for your report. 
The issue has been fixed in magento/magento2#18620 by @iancassidyweb in 2.3-develop branch
Related commit(s):
 - [3f9784e3ee8c4b1f1e9df0a47ad91a6e4628024b](https://github.com/magento/magento2/commit/3f9784e3ee8c4b1f1e9df0a47ad91a6e4628024b)

The fix will be available with the upcoming 2.3.1 release.
