### ISSUE TITLE
Customer name in adminhtml's order management is "Guest"

### ISSUE THREAD

**Issue by densen45** [magento/magento2#18616]
If you place an order as an guest, the displayed customer name in the adminhtml's order management is "Guest". If the guest has created an account after placing the order, it is a link that points to the customer's account management. Invoice and shipping are also affected.  

### Preconditions (*)

1. Magento 2.2.5 or 2.2.6

### Steps to reproduce (*)

1. Create an order as a guest
2. Open the placed order in the adminhtml

### Expected result (*)

1. The name of the guest should be displayed for "Customer Name"

### Actual result (*)

1. "Guest" is displayed for "Customer Name" (if the customer has created an account after order placement, "Guest" is a link that points to the customer's account management)

### (probably) consequential issues
1. Created invoice and shipment are also affected
2. Sending the invoice and shipment emails, the customer is addressed as "Guest" (i.e. the first line of the emails is "Guest,") 

### Probably related issues

#11552

**Comment by magento-engcom-team** [comment]
Hi @densen45. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@densen45 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by densen45** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @densen45. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @densen45, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18616-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18616-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18616-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by densen45** [comment]
I was able to reproduce the described issue (except the wrong name in the invoice and shipping emails, because the provided instance does not seem to send any emails.!?). However, the name in the adminhtml's order / invoice / shipping management is always displayed as "Guest". Therefore I assume the name would be wrong in the invoice and shipping emails, as well.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95915`, `MAGETWO-95916` were created

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mahesh-rajawat** [comment]
fixed in #18640 PL

**Comment by mahesh-rajawat** [comment]
#SQUASHTOBERFEST

**Comment by madbounce** [comment]
#mageconf

**Comment by huzrulz** [comment]
@maksek can you please assign this ticket to me.? Thanks.

**Comment by ghost** [comment]
Hi @densen45 thank you for you report, this will be fixed by this PR -> https://github.com/magento/magento2/pull/19191
