### ISSUE TITLE
Products attribute updates via scheduled change don't re-process category rules?

### ISSUE THREAD

**Issue by zack6849** [magento/magento2#18628]
### Preconditions (*)
1. v2.2.6
2. Have a category with rules set via Visual Merchandiser
3. Have a scheduled update that would make the product meet the rules

### Steps to reproduce (*)
1. Update the product with a scheduled update in a way that would make the product now eligible for listing in the category 
2. Wait for the scheduled update to trigger

### Expected result (*)
1. I would expect the product to be added to the category, as it now meets the requirements to be listed

### Actual result (*)
1. The product is not added to the category

You can trigger it to re-process the rules and take in the updated product if you save the category in admin again

Saving the product manually with the change that would make it eligible for listing will also actually add the product to the category, but the scheduled update will not.

Here are some logs from my magento instance for a scheduled change set to trigger at 16:30 UTC that didn't show up in that category

https://gist.github.com/zack6849/0819e06c8de542c692c14a50bcb594d2

Please note, this is honestly caused by me trying to find a workaround for the lack of functionality to add a product to a category with a scheduled update, some facility to do so would probably solve the problem better than worrying very much about such an obscure use case

For reference, I did some bugging and noticed the following code

snippet from `src/vendor/magento/module-catalog-staging/Model/ProductApplier.php`

```
            $select = $this->productCollectionResource->getSelect()->reset()
                ->distinct(true)
                ->from($this->productCollectionResource->getTable('catalog_category_product'), ['category_id'])
                ->where('product_id IN (?)', $entityIds);
            $affectedCategories = $this->productCollectionResource->getConnection()->fetchCol($select);

            $this->cacheContext->registerEntities(\Magento\Catalog\Model\Category::CACHE_TAG, $affectedCategories);
            $this->cacheContext->registerEntities(\Magento\Catalog\Model\Product::CACHE_TAG, $entityIds);
```

My theory is that since technically at the time this code runs, the product isn't actually in the category, that it isn't registered as an affectedCategory.

**Comment by magento-engcom-team** [comment]
Hi @zack6849. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@zack6849 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by zack6849** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @zack6849. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @zack6849, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18628-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18628-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18628-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by zack6849** [comment]
It has just occurred to me that as CatalogStaging is a Magento Commerce only feature, I won't be able to test against the instance provided, I will just mark that I was able to reproduce.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @zack6849 , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
