### ISSUE TITLE
when create a new Catalog Rule price the schedule feacture never activated the rule

### ISSUE THREAD

**Issue by hausert** [magento/magento2#18629]
### Preconditions (*)
1. Magento 2 EE 

### Steps to reproduce (*)
1. Create a new Catalog price Rule 
2. Run catalog_apply

### Expected result (*)
1. The process set the rule in active
2. The process run indexer
3. the new rule apply in catalog 

### Actual result (*)
1. Is not activated the rule
 2. Dont applied in catalog

**Comment by magento-engcom-team** [comment]
Hi @hausert. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hausert do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dverkade** [comment]
This issue looks like it's the same as magento/magento2#13325

**Comment by hausert** [comment]
Hi Dverkade, 

I check this issue but i think  is not the same case. In my case i never see the rule change the activated status.
For example: 
i create a new catalog price rule for today, this case created a new scheduler for this rule. When i edit this scheduler allways see the rule like inactive. 
I try to run catalog_rule_apply, reindexer price and catalog_rules and dont change de status for this rule.

The solution for this is enter manually to the schedule and change the status, but i undestand this is not how its should work the scheduler process.

**Comment by dverkade** [comment]
Hi @hausert 

In Magento a price rule can be set to active or not. When a rule is inactive Magento will never ever do something with the rule. When the rule is active and it hits the start date of that rule, it will automatically apply that rule on the given date. In order to do so, the rule needs to be set to active. 

As I'm understanding you have a rule with a start date, and set it to "inactive" and you expect the rule to become active once you hit the start date. This is not how the active / inactive feature works in Magento, hope this helps for you.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @hausert , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
