### ISSUE TITLE
Magento 2.2.6: cookies.js blocked > Minicart not working, infinite checkout loader.

### ISSUE THREAD

**Issue by NostiLoke** [magento/magento2#18636]
### Preconditions (*)

1. PHP 7.1 
2. Fresh Magento 2.2.6 installtion (without and with sample data) - no admin settings changed
3. AdBlock-Extension in Chrome

### Steps to reproduce (*)

1. Reload page (F5)
2. Add article to cart
3. Go to checkout

### Expected result (*)

1. Article (and number) should be shown in the minicart.
2. Link with the "Proceed to Checkout" is visible
![0043](https://user-images.githubusercontent.com/44178841/46979490-0e835e00-d0d2-11e8-8091-068c5e8425be.png)
3. Checkout is useable and loader disappers after page is loaded

### Actual result (*)

1. Adblock activated. After page load "/mage/cookies.js net::ERR_BLOCKED_BY_CLIENT"
[ERROR] Failed to load the "Magento_Checkout/js/view/minicart" component.
![0041](https://user-images.githubusercontent.com/44178841/46979306-97e66080-d0d1-11e8-9edd-3b636593f64d.png)

2. After adding article to cart, minicart is shown as empty (and with no numer). 
![0042](https://user-images.githubusercontent.com/44178841/46979432-e7c52780-d0d1-11e8-83eb-74b36b32d31a.png)

3. After opening the /checkout/ manually - cookies.js still is blocked, loader doesn't disapear
![0044](https://user-images.githubusercontent.com/44178841/46979699-8baed300-d0d2-11e8-8103-1a78b281a5e5.png)

![0045](https://user-images.githubusercontent.com/44178841/46979786-d29cc880-d0d2-11e8-9bfc-b13f1a358454.png)

Similar issues where "real tracking" was blocked, but not cookies.js:
Solutions don't help with this issue:

Checkout 'hangs' in paymentstep when adblocker blocks Magento google-analytics javsascript file. #11208
Fix infinite checkout loader when some script wasn't loaded correctly because of network error #14874

**Comment by magento-engcom-team** [comment]
Hi @NostiLoke. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@NostiLoke do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by NostiLoke** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @NostiLoke. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @NostiLoke, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18636-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18636-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18636-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by NostiLoke** [comment]
![0046](https://user-images.githubusercontent.com/44178841/47095225-1efc1b80-d22d-11e8-93c9-99e1685a724c.png)

The issue is reproduceable.
Adblock blocks the cookies.js - this results in:
[ERROR] Failed to load the "Magento_Checkout/js/view/minicart" component.

Reason is an entry in the Fanboy's Annoyance List
`/mage/cookies.`
[https://easylist.to/easylist/fanboy-annoyance.txt](url)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by DanielRuf** [comment]
> Reason is an entry in the Fanboy's Annoyance List
> `/mage/cookies.`
> [https://easylist.to/easylist/fanboy-annoyance.txt](url)

Which should be changed there. Not an issue on our side.

**Comment by DanielRuf** [comment]
https://github.com/easylist/easylist
https://github.com/easylist/easylist/blob/master/fanboy-addon/fanboy_cookie_general_block.txt#L457
https://github.com/ryanbr/fanboy-adblock/issues

**Comment by NostiLoke** [comment]
the cookies.js is also blocked in magento 1.9., but this doesn't break the checkout.
Is the cookies.js so important that therefore the "Magento_Checkout/js/view/minicart" component can't be loaded?
Blocking google analytics ends in the same issue: #12428
Sounds like an problem with handling the blocked components like described in similar posts mentioned above.

**Comment by DanielRuf** [comment]
Yes it is a required dependency for other modules and to handle the cookies.
This is how requireJS works.

There might be (good) reasons why they added it to the blocklist.
In general I do not get this issue with the default setup of uBlock origin.

**Comment by DanielRuf** [comment]
See https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/cookies.js.
It is directly referenced in the sidebar of the checkout and page-cache.

**Comment by DanielRuf** [comment]
Not sure why this was added just because of one website / domain.
https://github.com/easylist/easylist/commit/0ceae38b14af544fd14ae989df015676b74dd9b6

**Comment by DanielRuf** [comment]
Also see https://github.com/ryanbr/fanboy-adblock/issues/532 and https://github.com/easylist/easylist/commit/cc914066ee89b8fba49d3df0a277eff43baabcc1
