### ISSUE TITLE
Getting a different downloadable product link after purchasing 

### ISSUE THREAD

**Issue by testmagento2** [magento/magento2#18635]
Can someone explain me why when I purchasing a download product I am receiving different download product ?

Magento 2.2.6

![download not the same](https://user-images.githubusercontent.com/33385380/46974231-7796b180-d091-11e8-8d54-da0a9974baab.PNG)

**Comment by magento-engcom-team** [comment]
Hi @testmagento2. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@testmagento2 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
