### ISSUE TITLE
Unable to finish compilation after upgrading from 2.2.5 to 2.2.6

### ISSUE THREAD

**Issue by viktordodev** [magento/magento2#18646]
### Preconditions (*)

1. Magento version 2.2.6
2. PHP 7.0.11
3. Bitnami Stack

### Steps to reproduce (*)

1. Upgrade to 2.2.6 from 2.2.5
2. Run compilation command 

### Expected result (*)

1. Exptected to finish the compilation 
2.

### Actual result (*)

1. Instead it trows an error on the 3 step of the compilation
2. This is the error:
 Cannot use Magento\Framework\Search\Request\Dimension as Dimension because the name is already in use in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Indexer/IndexStructure.php on line 14

**Comment by magento-engcom-team** [comment]
Hi @viktordodev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@viktordodev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by viktordodev** [comment]
Ok. I have found the issue. For some that might experience the same this might help.

I have upgraded magento using composer, however i realized that the file Dimension.php at location
/vendor/magento/framework/Indexer has different content than the official Magento downloaded zip.

Once I used the original content everything works fine.

Hey Viktor,
Thanks for helping yourself :)

**Comment by orlangur** [comment]
Nice catch, Viktor ;)

So, did Composer silently fail during upgrade?
