### ISSUE TITLE
Magento 2.3.0-beta18: ReflectionException on Backend -> Stores -> Configuration -> Services -> OAuth page

### ISSUE THREAD

**Issue by jhruehl** [magento/magento2#18655]
### Description
Admin Page "Stores -> Configuration -> Services -> OAuth" throws Reflection Exception.

### Preconditions (*)
1. Magento 2.3.0-beta18

### Steps to reproduce (*)
1. Login as admin and open the Stores -> Configuration -> Services -> OAuth page

### Expected result (*)
1. Page loads without an exception

### Actual result (*)
1. Page throws ReflectionException

**Comment by magento-engcom-team** [comment]
Hi @jhruehl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jhruehl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by jhruehl** [comment]
Either you make it easier again to create simple pull requests via patches without having to do this fork nonsense or developers like me will not actively contribute any more. The solution can be found in a rejected pull request of mine, because I didn't want to to this fork update nonsense, which has to be done in a local environment and cannot be done via the github page itself.

**Comment by mahesh-rajawat** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95977` were created

**Comment by pusachev** [comment]
#mageconf

**Comment by sidolov** [comment]
Hi @jhruehl. Thank you for your report. 
The issue has been fixed in magento/magento2#18750 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [78accc5569841afc37788f45847f11b52c0526c7](https://github.com/magento/magento2/commit/78accc5569841afc37788f45847f11b52c0526c7)

The fix will be available with the upcoming 2.3.1 release.

**Comment by ghost** [comment]
Hi @jhruehl i'm closing this issue as this already fixed in 2.3-develop branch.
