### ISSUE TITLE
Magento2.0: moveToCart functionality is not working from admin side

### ISSUE THREAD

**Issue by shaikhmasud147** [magento/magento2#18664]
### Preconditions (*)
Magento 2.0.17 

### Steps to reproduce (*)
1) Under customer, tab selects any one customer for edit.
2) Create a new order 
3) Add items in order grid
4) Select option move to the shopping cart
5) Click on the update button 

### Expected result (*)
When I click on update button then item added in cart.

### Actual result (*)
When I click on update button then page load and item not added in cart and item also removed from order grid.

**Comment by magento-engcom-team** [comment]
Hi @shaikhmasud147. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@shaikhmasud147 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@shaikhmasud147 Magento version must be 2.2+ for a bug report.

**Comment by shaikhmasud147** [comment]
Ok, Thanks!
