### ISSUE TITLE
In Admin customer(edit) section view return(RMA) page showing error 404 page

### ISSUE THREAD

**Issue by iamckdev** [magento/magento2#18669]
### Preconditions (*)

1. Install the newest version 2.2.6 (Enterprise edition)

### Steps to reproduce (*)

1. Place order
2. Create return

![1](https://user-images.githubusercontent.com/15726245/47081082-4cde6180-d227-11e8-99ef-53e7cf29f953.png)
![2](https://user-images.githubusercontent.com/15726245/47081092-523bac00-d227-11e8-9c70-fd809307cd78.png)

3. Go to customers
4. Open customer
5. Click on Return menu from left side.

![3](https://user-images.githubusercontent.com/15726245/47081118-6384b880-d227-11e8-9ce8-8747b40a44e6.png)

6. In Return grid click on View link.

![4](https://user-images.githubusercontent.com/15726245/47081139-70a1a780-d227-11e8-8493-582abb418f73.png)

7. Here you can see 404 page error.

![5](https://user-images.githubusercontent.com/15726245/47081144-74cdc500-d227-11e8-897e-73f45f53598b.png)

### Expected result (*)

1. Should be open return when click on view button.

### Actual result (*)

1. Showing 404 page error

![4](https://user-images.githubusercontent.com/15726245/47081035-30422980-d227-11e8-9288-e15971bd26c1.png)

![5](https://user-images.githubusercontent.com/15726245/47081004-23253a80-d227-11e8-81ed-d9e9d5df7855.png)

**Comment by magento-engcom-team** [comment]
Hi @iamckindia. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@iamckindia do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.
