### ISSUE TITLE
Components types in Magento 2

### ISSUE THREAD

**Issue by akashlal139** [magento/magento2#18684]
According to Magento 2 devdocs, components types are following:

Metapackage
Module
Theme
Language package

But, if I check "vendor/magento/framework/Component/ComponentRegistrar.php", components types are following:

`/**#@+
     * Different types of components
     */`
`const MODULE = 'module';`
`const LIBRARY = 'library';`
`const THEME = 'theme';`
`const LANGUAGE = 'language';`

So metapackage to be considered as library? or both are different?

**Comment by magento-engcom-team** [comment]
Hi @akashlal139. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@akashlal139 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@akashlal139, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
