### ISSUE TITLE
Unable to upload Logo, Magento 2.3.0 Beta18

### ISSUE THREAD

**Issue by davegog** [magento/magento2#18688]
Summary of the issue : Unable to upload logo via browser (Firefox) 
  Environment: Magento C.E 2.3.0 Beta18, PHP7.2, Apache 2.4.29 OS Ubuntu 18.04.1 LTS, Mysql Server version: 5.7.23, Server charset: UTF-8 Unicode (utf8) (External RDS  instance)

The webserver has been setup for TLS 1.2 communication.
 
    Expected and actual results: Ability to change the logo, Unable to upload logo 
    Error message :" A technical problem with the server created an error. Try again to continue what you were   doing. If the problem persists, try again later."

----------

### Preconditions (*)

1.  Magento 2.3.x

### Steps to reproduce (*)
1.  Content -> Design -> Configuration 
2.  Edit any Default Store View
3.  Other Settings -> Header
4.  Upload a favicon or logo

### Expected result (*)
1. Favicon or logo is uploaded and "filled in the form"

### Actual result (*)

1.   Error message :" A technical problem with the server created an error. Try again to continue what you were   doing. If the problem persists, try again later."
2.  <img width="1272" alt="image" src="https://user-images.githubusercontent.com/43999558/47159081-f2a3d600-d2e4-11e8-9018-a500dd5afc14.png">

**Comment by magento-engcom-team** [comment]
Hi @davegog. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@davegog do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by davegog** [comment]
Hi I have given all the required information above, 
New install of Magento via composer,  

Steps to reproduce 

Setup Apache on an  EC2 Ubuntu instance
Create an external RDS database
Ensure connectivity etc
Install CE edition via composer 

composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.3.* --stability=beta /var/www/html/

#Set pre-installation permissions
cd /var/www/html

find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \;
chown -R :www-data .
chmod u+x bin/magento

Setup Magento via browser: Everything  went through without any issues.

Afer magento installation:
php bin/magento cron:install
php bin/magento cron:install 
chmod 555 /var/www/html/app/etc

Hope this help, If needed I can setup a remote session for you to have a look.

Cheers,
Dave

**Comment by RickDBCN** [comment]
Hi,

Any error logs in the log files?

**Comment by davegog** [comment]
Hi Rick,

There were no errors in the log files. I've tried 2.2.6 with the same setup, and php 7.1x and it works perfectly. For the time being I've reverted back to 2.2.6 .

**Comment by magento-engcom-team** [comment]
Hi @wiardvanrij. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by wiardvanrij** [comment]
1. Use magento2.3 development branche
2. Content -> Design -> Configuration -> edit any Default Store View
3. Other Settings -> Header -> try to upload a favicon or logo

With the change of "fileuploader" to "imageuploader" the correct formElement was not updated to match the new "imageuploader".

Created PR.

**Comment by magento-engcom-team** [comment]
@wiardvanrij Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@wiardvanrij Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by davegog** [comment]
What more information do you need to confirm the issue when all information has been provided,  "Update issue content to follow format required by Issue Reporting Guidelines", well people don't have the time to follow your guidelines. Either you accept that there is an issue and open a ticket internally or you can be very pedantic and ignore the issue.Your choice! Version 2.2.6 doesn't have the same issue within the same setup!

**Comment by wiardvanrij** [comment]
@davegog 
I understand your "frustration" but it would be easier if you did not remove the mandatory guidelines for writing an issue. I personally updated your issue with the "guidelines" as an example. I also made the fix yesterday (see PR). 

I hope you understand that when dealing with a huge community there is some automation in place which focuses on formatting for easy management.  It is not perse about your issue content being bad, just simply not having the mandatory rules in it. 

Thanks for your effort in making the issue, please check the PR for the fix if you want to hotfix it in the meantime ;)

**Comment by magento-engcom-team** [comment]
@wiardvanrij Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95949` were created

**Comment by okorshenko** [comment]
Hi @davegog. Thank you for your report. 
The issue has been fixed in magento/magento2#18851 by @wiardvanrij in 2.3-develop branch
Related commit(s):
 - [ba69bfec127bed8c39c7d9e7b73d10b54449b158](https://github.com/magento/magento2/commit/ba69bfec127bed8c39c7d9e7b73d10b54449b158)

The fix will be available with the upcoming 2.3.1 release.

**Comment by engcom-backlog-nazar** [comment]
Hi @davegog i'm closing this issue, as this was fixed on 2.3-develop branch and not appear on 2.2-develop branch.

**Comment by ghost** [comment]
Hi @davegog , thank you for you report, this issue has already fixed in 2.3-develop branch, and will be available on 2.3.1 release.

**Comment by proman77** [comment]
I've got the same problem while trying to upload a watermark: 

> A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

**Comment by DanielRuf** [comment]
@proman77 it should be already fixed in the 2.3-develop branch.

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-18688-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-18688-2-3-develop.instances.magento-community.engineering/admin](https://i-18688-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
@proman77 please test using the link from https://github.com/magento/magento2/issues/18688#issuecomment-450316404

**Comment by proman77** [comment]
Done. Can't reproduce this issue there, It works correctly! @magento-engcom-team, I'm waiting for the fixing code here :)

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by DanielRuf** [comment]
If you use 2.2.x: https://github.com/magento/magento2/issues/18688#issuecomment-450320930

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-18688-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-18688-2-2-develop.instances.magento-community.engineering/admin](https://i-18688-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by proman77** [comment]
@DanielRuf I've tried 2.2.8 already. It's OK. No issue.

**Comment by abhaykhatariya** [comment]
#mm19in

**Comment by magento-engcom-team** [comment]
@abhaykhatariya thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.
