### ISSUE TITLE
Backorders are confusing to shoppers

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#18686]
### Preconditions (*)
1. Magento 2.2

### Steps to reproduce (*)
1. Create product
2. Set product to allow backorders and notify customer
3. Set Qty to 0
4. Set to Out of Stock.

### Expected result (*)
1. On product page, the Customer should be informed that the product is out of stock but available for backorder.
2. The customer should be able to add the item to cart, and told that they are on backorder during the checkout process.
3. If the Qty in stock is 1, and the customer orders 2, then it should say in stock on the main page, and then give the backorder message in the shopping cart.

### Actual result (*)
1. The customer is told the item is out of stock.
2. The customer is not given the option to backorder the item.

If I set the item to In Stock, Qty 0, Allow backorders and notify, then the customer is told the item is in stock (which it isnt). The customer is allowed to add the item to cart, and is informed in the shopping cart that the item is on backorder.

This is confusing for the customer, he is being told the item is in stock, but will be back ordered. Likely to result in abandoned cart and unexpected shipping expectations.

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment]
Able to reproduce on vanilla 2.2.6

**Comment by gwharton** [comment]
See also #11708

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-pb. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@gwharton, this is not a bug. A Customer should not be able to buy a Product with "Out of Stock" Stock Status in any circumstances.

**Comment by gwharton** [comment]
Errr, yes they should. This is the whole purpose of backorders. You allow your customers to buy products that arent in stock as they are being "backordered"!

The dictionary definition of a backorder is "a retailer's order for a product which is temporarily out of stock with the supplier."

**Comment by ruthgeridema** [comment]
It's not a bug, it's a feature! When you can't order the product at your supplier anymore, due to no stock for example (+ you cant backorder at them), you set the product to 'out of stock'. Disabling the product causes a 404, which is not good for your SERP rankings if the product will be back on stock at a later time.

**Comment by gwharton** [comment]
The three states of a product availability for purchase should surely be

- In stock - available for purchase
- Out of stock - available for backorder
- Out of stock - not available for backorder

Telling a customer that an item is "In stock" when it isn't, leads to elevated customer expectations on delivery. This is made worse if the store uses minicart straight to checkout links, and bypasses the shopping cart stage as they will never even be notified of the fact that the item is on backorder. #11708

**Comment by gwharton** [comment]
Looks like there are plenty of Magento addon modules that make backorders work properly. Shame its gonna require more financial investment to get this core feature working as one would expect it to.

**Comment by tomekjordan** [comment]
I agree, default Magento M1 and M2 backorder is not user/admin friendly.
There are many good M1 Preorder extensions, the problem - they override core, and other stock/product extensions are conflicting. Would be great if Magento Core team implement real-working Preorder feature built-in in the core. Something similar to Amasty Preorder, but working with MSI together.
1. give option to use negative QTY in stock
2. give option to ADD TO CART/OUT OF STOCK/PREORDER
3. give option to notify customer in expected way - frontend & emails
4. allow all default inventory walidation - min/max qty, qty step increment to working with it - just using the negative stock for it

**Comment by inkobject** [comment]
Was this bug really closed on you @gwharton ?
What is the purpose of setting a product to allow backorder?
I don't follow the logic of putting in the option with no functionality.

**Comment by gwharton** [comment]
I ended up buying Amasty's module. With a few customisations I now have it working beautifully.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gwharton ,  It will be processed faster if you move this to https://github.com/magento/community-features
