### ISSUE TITLE
Left Side Back End Menu Design fix

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#18687]
I have installed the Magento 2.2.5.

I have installed  many extensions which is creating User Menu in the Marketing tab.

Here is the issue that if there are more then 5 columns in the admin side sub menu then last column menu items cut off.
http://prntscr.com/l7jvlc

There should be automatic adjustment menu items so It will not cut off.

### Preconditions (*)
Left Side Back End Menu Design fix

**Information on your environment**
I have installed the Magento 2.2.5.

### Steps to reproduce (*)
Install the multiple extension which is creating sub menu in Marketing tab, and then access the admin side to see how it look like
http://prntscr.com/l7jvlc

### Expected result (*)
There should be automatic adjustment menu items so It will not cut off.

### Actual result (*)
http://prntscr.com/l7jvlc

**Comment by magento-engcom-team** [comment]
Hi @jigar48. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jigar48 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jigar48** [comment]
**Summary of the issue**
Left Side Back End Menu Design fix

**Information on your environment**
I have installed the Magento 2.2.5.

**Steps to reproduce**
Install the multiple extension which is creating sub menu in Marketing tab, and then access the admin side to see how it look like
http://prntscr.com/l7jvlc

**Expected and actual results**
There should be automatic adjustment menu items so It will not cut off.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95866`, `MAGETWO-95867` were created

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by angelgonzalezi4** [comment]
@Magento I am working on it

**Comment by VladimirZaets** [comment]
Hi @jigar48. Thank you for your report. 
The issue has been fixed in magento/magento2#26034 by @ptylek in 2.4-develop branch
Related commit(s):
 - [f59c1ca61e034a7973e0ac08ab765cbe4060ed84](https://github.com/magento/magento2/commit/f59c1ca61e034a7973e0ac08ab765cbe4060ed84)
 - [7a2bc8fe52e570cfec0201fa36c7118eaf26f6a4](https://github.com/magento/magento2/commit/7a2bc8fe52e570cfec0201fa36c7118eaf26f6a4)
 - [6bf903f0521c7ef1f2561af6db71e391ecdc39ea](https://github.com/magento/magento2/commit/6bf903f0521c7ef1f2561af6db71e391ecdc39ea)

The fix will be available with the upcoming 2.4.0 release.
