### ISSUE TITLE
FPT dynamic catalog configurable products prices

### ISSUE THREAD

**Issue by arnoldhauptricht** [magento/magento2#18697]
### Preconditions (*)

1. Magento 2.2.6
2. Functionality to change FPT in frontend

### Steps to reproduce (*)

1. We have a custom functionality that switches delivery country dynamically on a customer session. Based on this FPT is added to the price.
2. We are using a POST request to switch FPT.

### Expected result (*)

1. View product prices with FPT taken from saved cookie

### Actual result (*)

1. Once the product is cached in the system, when we switch FPT and chose an option for the configurable product, the product price shown is the cached price from the initial request.

The values are first cached in this template: vendor/magento/module-configurable-product/view/frontend/templates/product/view/type/options/configurable.phtml:37 
"spConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>

And then used for calculations here: vendor/magento/module-configurable-product/view/frontend/web/js/configurable.js:488 
newPrices = this.options.spConfig.optionPrices[_.first(config.allowedProducts)];

I've tried adding a sections.xml file for our FPT switcher action, but none of the sections I've target seemed to work. I've tried final_price, prices, etc. 
From the code it seems that there is no section defined for configurable product options.

We think this is a core issue because of the way the configurable item is defined. 
vendor/magento/module-configurable-product/etc/frontend/di.xml:10 
```
<type name="Magento\Checkout\CustomerData\ItemPoolInterface"> 
    <arguments> 
        <argument name="itemMap" xsi:type="array"> 
            <item name="configurable" xsi:type="string">Magento\ConfigurableProduct\CustomerData\ConfigurableItem</item> 
        </argument> 
    </arguments> 
</type>
```

**Comment by magento-engcom-team** [comment]
Hi @arnoldhauptricht. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@arnoldhauptricht do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @arnoldhauptricht  thank you for you report,
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
