### ISSUE TITLE
REST: Get same error with all requests

### ISSUE THREAD

**Issue by mateo2181** [magento/magento2#18690]
### Preconditions (*)
1. Magento 2.2.5

### Summary (*)

I have created an integration with all permissions but when I want to use the API always get the same error.
![selection_010](https://user-images.githubusercontent.com/12451246/47165400-41934080-d2d0-11e8-8b94-ce9c59081624.png)

### Examples (*)

Example API Requests:
http://127.0.0.1/rest/V1/stockItems/Mochila%20Swat
http://127.0.0.1/rest/V1/categories

**Comment by magento-engcom-team** [comment]
Hi @mateo2181. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mateo2181 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mateo2181** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @mateo2181. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @mateo2181, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18690-2-2-5/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18690-2-2-5//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18690-2-2-5//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mateo2181** [comment]
I get 404 not found when use the API REST.
I am trying with GET http://ec2-34-228-235-121.compute-1.amazonaws.com/rest/V1/products/remera from Postman. And using OAuth 1.0.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-pb. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@mateo2181, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
