### ISSUE TITLE
Magento triggers and sends some of order emails exactly one month later,while the order email was not enabled then

### ISSUE THREAD

**Issue by PiroozMB** [magento/magento2#18698]
### Preconditions (*)
1. Magento 2.2.3 

### Steps to reproduce (*)
1. disable order emails from Stores->configuration->sales emails to not send any email on any new order
2. after 40 days , enable the order emails from Stores->configuration->sales emails to send email on new orders

### Expected result (*)

1. after the fortieth day, magento should trigger and send order emails only on any new order which is placed after that 40th day and not send any order email related to the orders before the fortieth day because it was not enabled yet.

### Actual result (*)

1. Magento triggers and sends order emails on new orders perfectly, But it sends randomly some order emails too related to orders from exatly one month ego, while the order email was not enabled yet one month ago.

**Comment by magento-engcom-team** [comment]
Hi @PiroozMB. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@PiroozMB do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96002`, `MAGETWO-96003` were created

**Comment by magento-engcom-team** [comment]
Hi @serhiyzhovnir. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @PiroozMB. Thank you for your report. 
The issue has been fixed in magento/magento2#20953 by @serhiyzhovnir in 2.3-develop branch
Related commit(s):
 - [be874714e96cc17cd8d9de71159769aeabf7d10e](https://github.com/magento/magento2/commit/be874714e96cc17cd8d9de71159769aeabf7d10e)
 - [600e090a2c4acdcbcbc2e95851debf17858e1435](https://github.com/magento/magento2/commit/600e090a2c4acdcbcbc2e95851debf17858e1435)
 - [1efb4a9f3435e0ec1f2b1b9d0b6a3242eee20eb7](https://github.com/magento/magento2/commit/1efb4a9f3435e0ec1f2b1b9d0b6a3242eee20eb7)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @PiroozMB. Thank you for your report. 
The issue has been fixed in magento/magento2#20954 by @serhiyzhovnir in 2.2-develop branch
Related commit(s):
 - [9b6ef590ed0fc95c5da7e5ebfacf5b2452dead5e](https://github.com/magento/magento2/commit/9b6ef590ed0fc95c5da7e5ebfacf5b2452dead5e)
 - [d70186b5835f4839413c283a5f319618998b762e](https://github.com/magento/magento2/commit/d70186b5835f4839413c283a5f319618998b762e)

The fix will be available with the upcoming 2.2.9 release.
