### ISSUE TITLE
Empty cart after clicking in the minicart "Proceed to Checkout" and right after "View and Edit Cart"

### ISSUE THREAD

**Issue by stephansteiner** [magento/magento2#18701]
### Preconditions (*)
1. Tested and reproduced on Magento 2.2.3 and 2.2.5 using various themes as well as the magento Luma Theme
2. A slower server is helpful while debugging the issue. On normal cirumstances a user can't click both actions in the mini cart

### Steps to reproduce (*)
1. Put some products in the cart
2. Open the minicart eiother by hovering or clicking the basket icon (this is theme dependent)
3. Click on "Proceed to Checkout", then immediately on "View and Edit Cart"

### Expected result (*)
1. Since "View and Edit Cart" is the last action clicked, the URL /checkout/cart should be opened and the products you added before should be shown

### Actual result (*)
1. The cart is empty.

This is especially annoying if the "Proceed to Checkout" action is taking some time, and most customers click on "View and Edit Cart" right after - the cart is emptied. This doesn't seem to be a cache issue, but a concurrency issue between the /checkout (maybe also closeMinicart() javascript) and the /checkout/cart action.

**Comment by magento-engcom-team** [comment]
Hi @stephansteiner. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@stephansteiner do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-pb. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@stephansteiner, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![peek 2018-10-19 15-33](https://user-images.githubusercontent.com/40756187/47218426-606b0300-d3b4-11e8-94ab-9a0ae570392e.gif)

**Comment by stephansteiner** [comment]
Problem is related to this issue: https://github.com/magento/magento2/issues/12362
