### ISSUE TITLE
On key change event not update product options Related Image

### ISSUE THREAD

**Issue by rvpatel** [magento/magento2#1871]
Hello team,
I have just now seen demo magento 2 frontend. 
i have realized on mouse event on change product image but  key event on not change product Image.

See hear : http://magento2-demo.nexcess.net/breathe-easy-tank.html?options=cart

**Comment by guz-anton** [comment]
Hi Ravi,
Looks like on your personal instance old revision of Magento2 is installed. And now you don't have mentioned issue.
But in current mainline such issue still exist. It has internal ticket MAGETWO-43263. The fix is already done and on way of delivery. I'll notice here when we when it will be done.

Thanks for your attention!

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-43263 is closed and delivered to mainline. Please, let us know if you still have an issue.
