### ISSUE TITLE
Paypal Does Not Appear in Magento 2 Checkout

### ISSUE THREAD

**Issue by modkore** [magento/magento2#18716]
### Preconditions (*)

1. Magento 2.2.5
2. Paypal won't appear during checkout.

### Steps to reproduce (*)

1. We tried to activate a new theme to see if the problem is theme based but the issue came out same with Magento 2.2.5 even by using the default luma theme the same problem came out. I believe this is a huge issue in Magento 2.2.5

### Expected result (*)

1. I am expecting that Paypal will show up as an option to the checkout of Magento 2.2.5

### Actual result (*)

1. Paypal did not show up during checkout.

**Comment by magento-engcom-team** [comment]
Hi @modkore. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@modkore do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by modkore** [comment]
Yes

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @modkore I'm not able to reproduce following steps your described, Also  please look -> https://github.com/magento/magento2/issues/12878, Problem may be related to your custom code. 
If you like to update, please reopen the issue.

**Comment by modkore** [comment]
**Preconditions (*)**
Magento 2.2.5
Paypal won't appear during checkout.

**Steps to reproduce after installation of magento 2.2.5 website**
1. Configured recommended solutions Paypal Express Checkout
2. Applied allow guest checkout
3. Made paypal only appear to checkout
4. Add product in front end and proceed to checkout. 

**Expected result (*)**
After input of billing address and shipping address the Paypal must show up as payment method from the list.

**Actual result (*)**
Paypal did not show up during checkout.

![image](https://user-images.githubusercontent.com/40972882/50049723-a6c7ae80-0126-11e9-9c19-e2b6c1294218.png)
