### ISSUE TITLE
Save Button not working payment methode (Default config)

### ISSUE THREAD

**Issue by rachid-a** [magento/magento2#18721]
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Go to stores --> configuration --> Sales --> Payment methods
2. Try the save button (it doesn't work for me) in default config
3. Others config pages are working fine

### Expected result (*)

1. The save button should work when I press on it.

### Actual result (*)

1. Currently it doesn't do anything.

**Comment by magento-engcom-team** [comment]
Hi @rachid-a. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rachid-a do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rachid-a** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @rachid-a. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @rachid-a, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18721-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18721-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18721-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rachid-a** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @rachid-a. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @rachid-a, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18721-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18721-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18721-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rachid-a** [comment]
@magento-engcom-team no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @rachid-a, thank you for you report,  I'm not able to reproduce following steps your described, If you like to update, please reopen the issue.

**Comment by rachid-a** [comment]
Hi @engcom-backlog-nazar 

The issues is caused by core package Authorize.Net payment methods.
If I disable the module or check enable option out and set option to no then it save button is working again.
There is something with this extension that is causing the issue.

**Comment by ghost** [comment]
Hi @rachid-a, yes and i'm trying reproduce this on 2.3-develop branch but unsuccessful, If you have clear steps to reproduce, please, tell me know.

**Comment by rachid-a** [comment]
Hi @engcom-backlog-nazar,

I cannot reproduce it anymore after disabling/enabling the extension with command line. Also with the enable question yes/no in admin page.

It looks now that is fixed.
