### ISSUE TITLE
Graph Ql category tree structure is broken (children get moved to the last element)

### ISSUE THREAD

**Issue by raivisdejus** [magento/magento2#18736]
### Preconditions
Magento 2.3-develop

### Steps to reproduce
Run the following Graph Ql query
```
{
    category(id: 2) {
        children {
            name
            children {
                name
                children {
                    name
                    children {
                        name
                    }
                }
            }
        }
    }
}
```

### Expected result
Category tree with categories and their children. Tree matches site category structure

### Actual result
Categories are sorted according to their levels where last items get all the children.

### Solution
Remove the following line that is performing sorting and is breaking up the category tree structure.
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php#L104

**Comment by magento-engcom-team** [comment]
Hi @raivisdejus. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@raivisdejus do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
