### ISSUE TITLE
Change Shipping Address & Change Billing Address links change both Shipping and Billing Address.

### ISSUE THREAD

**Issue by harrigo** [magento/magento2#18738]
When a user has an account and wants to set separate shipping and billing addresses the link for change Shipping Address changes both billing and shipping address. Similarly the opposite occurs when changing Billing Address.

It seems that if the address is assigned to both Billing and Shipping in the system then the change shipping address / change billing address form will just edit that address which is already assigned to both Shipping and Billing addresses changing both. 

There should be a flag for when these links are clicked to create a new address if this address is assigned to both and then assign to just the billing or just the shipping depending on which link was clicked or just create a new address and assign it to the correct address type.

### Preconditions
1. Magento 2.2.5 (Has been present in earlier versions)

### Steps to reproduce
1. Create an Account
2. Navigate to My Account
3. Navigate to Address Book
4. Input initial address in your account.
5. Change either billing or shipping address by clicking "Change Billing Address" or "Change Shipping Address" and updating details.
6. Click Save Address

OR

1. Log in to existing account
2. Navigate to My Account
3. Navigate to Address Book
4. Add a new address and assign to both billing and shipping addresses
5. Change either billing or shipping address by clicking "Change Billing Address" or "Change Shipping Address" and updating details.
6. Click Save Address

### Expected result
1. Just the shipping address or just the billing address is changed.

### Actual result
1. Both Billing and Shipping addresses are now changed.

This is counter intuitive and have had complaints from customers about the way this works. I completely agree and feel that although you can workaround by adding a new address, assigning it to billing address or shipping and then everything works as expected however this should not be necessary.

**Comment by magento-engcom-team** [comment]
Hi @harrigo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@harrigo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by harrigo** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @harrigo. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @harrigo, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18738-2-2-5/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18738-2-2-5//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18738-2-2-5//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by harrigo** [comment]
I cannot create an account in that Magento Instance just loops on register page. No emails are sent so cant set a password for a customer account created from admin either.

**Comment by harrigo** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @harrigo. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @harrigo, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18738-2-2-4/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18738-2-2-4//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18738-2-2-4//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by harrigo** [comment]
Ok customer creation works within Firefox, however not within chrome which may be a bigger issue...

However I can also confirm that the actual behavior in question here exists in both the 2.2.4 and 2.2.5 instance that I just tested. There are flags that state that this address is the default billing, and default shipping however I believe if you click to change one or the other you should change one or the other it seems quite confusing for users.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @harrigo, thank you for you report, this is not a bug, you can set different addresses for customer only in admin area.

**Comment by harrigo** [comment]
You can set different addresses for customers from frontend not sure what you mean by your comment but follow my steps to reproduce. The comment is simply not true and users can change their addresses thankfully without having to contact an admin.

**Comment by ghost** [comment]
@harrigo seems like this is feature, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by onamfc** [comment]
Experiencing the same issue. How did you solve this? @harrigo
