### ISSUE TITLE
Admin's "Manage Encryption Key" function appends new encryption key to existing encryption key in env.php

### ISSUE THREAD

**Issue by nathancasebolt** [magento/magento2#18745]
### Preconditions

1. Magento 2.2.2
2. Ubuntu 16.04.5 LTS
3. Let's assume a fake existing encryption key of 'wt1pusxp339m8hhtm290iu5kqn3bierz'

### Steps to reproduce

1. Log into Magento Admin
2. Navigate to System > Manage Encryption Key
3. Manually enter a 32-character alphanumeric encryption key in the 'New Key' field (let's say, for example, 'mcy528m62xy4xiykx2ea9o52a7ijlmmr')
4. Click 'Change Encryption Key'
5. In a console, open env.php
6. Find the value of the 'crypt' key

### Expected result

This:
```
'crypt' =>
  array (
    'key' => 'mcy528m62xy4xiykx2ea9o52a7ijlmmr',
  ),
```

### Actual result
This:
```
'crypt' =>
  array (
    'key' => 'wt1pusxp339m8hhtm290iu5kqn3bierz
  mcy528m62xy4xiykx2ea9o52a7ijlmmr',
  ),
```

**Comment by magento-engcom-team** [comment]
Hi @nathancasebolt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nathancasebolt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@nathancasebolt this does not seem to be an issue since this is the way Magento stores the encryption keys by creating several versions and uses the latest version to encrypt data.

**Comment by nathancasebolt** [comment]
@ashutoshwebkul Fair enough. I didn't realize this was expected behavior, and I appreciate the feedback.
