### ISSUE TITLE
Tax breakup issue

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#18742]
### Preconditions (*)

1. Magento 2.1.7
2. Nginx, MySQL 5.6.x

### Steps to reproduce (*)

1. Add Tax Zones and Rates 
![image](https://user-images.githubusercontent.com/20873227/47292446-9e6e5e00-d624-11e8-81c9-83bc616921f7.png)
2. Add Tax Rules
![image](https://user-images.githubusercontent.com/20873227/47292470-b34af180-d624-11e8-832d-023c424c4df1.png)
3. Add a Product to Cart and go to **checkout/cart/** page.
4. Select **Canada** as a country and **British Columbia** as state and update the shipping.

### Expected result (*)

1. Tax as a breakup with the applied rules on cart page and on other places as invoice and admin order section.  Tax break up is showing on frontend but not with separate tax price. while it needs to showing with separate tax prices.
 

### Actual result (*)

1. On cart page - ![image](https://user-images.githubusercontent.com/20873227/47292706-7c291000-d625-11e8-894d-5b9d92dbf58b.png)
2. On Invoice - 
![image](https://user-images.githubusercontent.com/20873227/47292804-c4483280-d625-11e8-9d2a-74a337755985.png)
3. In admin Order section - 
![image](https://user-images.githubusercontent.com/20873227/47292837-e2ae2e00-d625-11e8-84d1-2a02eff09f71.png)

**Comment by magento-engcom-team** [comment]
Hi @RishabhRkRai. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@RishabhRkRai do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @prakashpatel07. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by rishabhrkrai** [comment]
@prakashpatel07 This issue has been solved now. I Go through the admin configurations and do this from there.

Here is what I do:

- Change the Sort Order and Priority of each Rule.
- Change the configuration **Store > Configuration > Sales > Tax > Orders, Invoices, Credit Memos Display Settings > Display Full Tax Summary** to **Yes**

And now the tax breakup is showing perfectly.
