### ISSUE TITLE
What is the logic behind the different .htaccess files / Why do we have two entry points (index.php and pub/index.php)?

### ISSUE THREAD

**Issue by amenk** [magento/magento2#1874]
Why are there so many .htaccess files with partially redundant information?
Can't this be merged to one file? What is the rationale behind this?

**Comment by wallermadev** [comment]
Got bless that edit functionality -- 

In general, Apache will use the most specific .htaccess to the resource being requested. This means that, for accessing files in /httpdocs/wordpress/, /httpdocs/wordpress/.htaccess will be used. Access to /httpdocs/foo/ will use /httpdocs/foo/.htaccess and, if that doesn't exist, it will use /httpdocs/.htaccess.

I would imagine the reason for multiple being using within magento is that it keeps the information relevant to the directory is lives in rather than having 1 long convoluted on living in the root directory.

**Comment by buskamuza** [comment]
As far as I know, you can't specify configuration for a specific folder in a root .htaccess file. So the only way is to have .htaccess per each such folder.

**Comment by amenk** [comment]
But the question is why different memory limits and mime types are specified per folder. Or does apache not head the /www/.htaccess if /www/media/.htaccess is present?

**Comment by wallermadev** [comment]
ding ding ding

**Comment by amenk** [comment]
@wallermadev ???

**Comment by buskamuza** [comment]
Just looked through `.htaccess` files in Magento. There are three big of them (I don't include tests):
- `.htaccess`
- `pub/.htaccess`
- `pub/media/.htaccess`

All others usually just restrict access an it can't be done from the upper level.

About `.htaccess` and `pub/.htaccess` - it's the same story as duplicating on `index.php`. We'd like to recommend to use `pub/` as an entry point for everyone and remove all these `index.php` and `.htaccess` from the root of Magento. But it may be a pain for non-experienced users to install Magento because it will require to configure web-server's document root to point to `pub` sub-folder instead of the root folder (unless somebody wants to have URLs like http://my.host.com/pub/). And we're not sure that it's an easy thing to do on different shared hostings.
So for now we're still keeping copies of `index.php` and `.htaccess` files in both root and `pub` folders.
And here's what we have:
- If you indeed configure your web-server so that its document root points to `pub`, than `.htaccess` from the root won't be loaded (just because Apache doesn't know anything about this upper folder)
- If you go easiest way and configure Apache to point to the Magento root, root `.htaccess` is loaded. Apache won't apply any settings from `pub/.htaccess` to the Magento root, of course.

If you can suggest some good solution that will cover both cases and, in the same time, avoid duplication. I believe, we would accept it gladly (we don't like this duplication either).

Can't say about `pub/media/.htaccess`. But looks like it has more specific options for different mimetypes, which is not needed for the root `.htaccess`.

**Comment by amenk** [comment]
I did not know that `pub` is the recommended doc root. That sounds pretty good. Also lots of other frameworks work with such a Document Root (Zend Framework 1, 2, Laravel) ... so I don't think we have to support setting the document root to the root of Magento.
Having two possible document roots is more confusing than requiring to the it to "pub" (why we don't call it "public"?). And a Magento system is anyways non-trivial to install.

**Comment by buskamuza** [comment]
I think, the difference between Magento and ZF, Symfony or Laravel is that the second are all frameworks and used by developers to create a real web-site. Though Magento should be ready for use as is. You can buy a theme, of course, but in general - it's a ready web-site.
It means that:

1. if it is just a framework, it can be used by developers. Non-developer users will not use it as is, they will use the result of the developer's work (which may have different root or will be just installed by the developer).
2. if it is a ready solution, like Magento, it can be used by non-developer people. It means that installation should be as simple as possible and it should just work.

All the above is IMO, maybe the reality is different.

> And a Magento system is anyways non-trivial to install.

It means there is a field to work on for us... :) Is it non-trivial because of: 1) non-standard requirements to the server, 2) bad error handling, 3) non-stable, 4) complicated UI, 5) something else?

**Comment by amenk** [comment]
Okay, I get the framework vs. app point. But: I think also most web apps which are based on the above frameworks require to the the DocumentRoot to a kind of public folder. It is not such a hard requirement though. I would drop those double index.php stuff.

**Comment by choukalos** [comment]
@amenk interestingly, we have a number of merchants ( assume small/low revenue ) that are on shared hosting providers.  Likely these are either 1 click installs or someone FTP'd them to the shared host and went through the web install.  When we researched this hosting path - most shared hosting providers expect the web root to be the entry point to the application.  Has that changed recently?  If so can you point to shared hosting providers that support a pub or similar such directory as the root hosting directory; would be interested to understand both support and the friction such a path would entail for these hobbyist merchants.

**Comment by amenk** [comment]
Actually I do not know which shared hosting providers support it or not. But there are many other web apps which have a `public` folder.  (Actually I also suggest renaming pub to public as this is more common)

Another option would be to suggest the public folder as entry root and add some documentation or .htaccess which uses mod_rewrite to use the entry point in the public folder.

See https://driesvints.com/blog/laravel-4-on-a-shared-host -> 2. Using .htaccess with mod_rewrite

**Comment by amenk** [comment]
Seems to be a dupe of #356
Let's continue there.
