### ISSUE TITLE
Magento 2.2.6 - Terms and Conditions not showing on backend

### ISSUE THREAD

**Issue by 99Fede** [magento/magento2#18746]
### Preconditions (*)

1. Magento 2.2.6
2. Php 7.0.31
3. MySQL 5.6.40

### Steps to reproduce (*)

1. Store > Setting > Terms and Condition
2. Add New condition > save

### Expected result (*)

1. new conditions should be listed on page

### Actual result (*)

1. No conditions are shown on the Terms and Conditions page, so it's impossibile to edit or delete them
![m226-termscondition_issue-backend](https://user-images.githubusercontent.com/44372754/47302535-0a9b9280-d622-11e8-9ed6-79ffdc5def8e.png)

**Comment by gwharton** [comment]
I couldn't reproduce this on a vanilla 2.2.6 install (PHP 7.0.32 and PHP 7.1.23)

**Comment by magento-engcom-team** [comment]
Hi @99Fede. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@99Fede do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by 99Fede** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @99Fede. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @99Fede, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18746-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18746-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18746-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 99Fede** [comment]
@magento-engcom-team on vanilla instance is working well, my bad i don't know what's wrong at this point...
Now my issue is how i can delete those conditions on my Magento without being able to see them on backend?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @99Fede Thank you for you report, I'm not able to reproduce following steps your described.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
