### ISSUE TITLE
X-Magento-Cache-Debug: MISS Magento 2.2.6

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#18757]
### Preconditions (*)

1. Centos 7.5
2. Varnish 4
3. Magento 2.2.6

### Steps to reproduce (*)

1.My /etc/varnish/default.vcl is follow this file: https://gist.github.com/dvershinin/de91aa78a96ae9f6e8d2950b3e1463a4
```
backend default {
    .host = "11.22.133.44";
    .port = "8080";
}

acl purge {
    "11.22.133.44";
}
```
2. ```
System > Full Page Cache > Setting > 
Access list:11.22.133.44
Backend host:11.22.133.44
Backend port:8080
Grace period:300
```

3. php bin/magento setup:config:set --http-cache-hosts=11.22.133.44:8080

4. My WHM setting Apache IP/port:8080. 

5.My /etc/varnish/varnish.params
```
RELOAD_VCL=1

VARNISH_VCL_CONF=/etc/varnish/default.vcl

VARNISH_LISTEN_ADDRESS=11.22.133.44
VARNISH_LISTEN_PORT=80

VARNISH_ADMIN_LISTEN_ADDRESS=11.22.133.44
VARNISH_ADMIN_LISTEN_PORT=6082

VARNISH_SECRET_FILE=/etc/varnish/secret

VARNISH_STORAGE="malloc,4096M"

VARNISH_USER=varnish
VARNISH_GROUP=varnish

DAEMON_OPTS="-a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,4096m -p thread_pool_min=5 -p thread_pool_max=500 -p thread_pool_tim$$ol_timeout=300"
```

### Expected result (*)
<!--- Tell us what should happen -->
1. Get X-Magento-Cache-Debug: HIT

### Actual result (*)
<!--- Tell us what happens instead -->
1.  I installed Varnish, but getting this message. Varnish cache not working. And check the var/page_cache/ directory is not empty.still have mage-tags file.

**Comment by magento-engcom-team** [comment]
Hi @andy17612. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@andy17612 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @andy17612  thank you for you report i'm not able to reproduce following steps you described.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
