### ISSUE TITLE
Shipping Table rate display issue on checkout with multistore

### ISSUE THREAD

**Issue by albsa** [magento/magento2#18755]
### Preconditions (*)

1. 2.2.6; 2.3-develop
2. PHP 7.1.31

### Steps to reproduce (*)

1. I have table rate shipping enabled, with 2 rates. 1 For germany, 1 for the netherlands.
Netherlands is the main domain and is set to 4.95 shipping price.
Germany is set to 6.95 shipping price.
2. When checking out on the german domain, initially the rate of netherlands is shown.
3. When filling in the zipcode address then the rate triggers and changes to 6.95. I expect on page load already when the locale is set to a specific country to take that shipping rate. Or take the shipping rate of the default country where it ships to.

### Expected result (*)

1. Expected to see the default shipping rate per country

### Actual result (*)

1. Got a different country shipping rate, instead of the right one. Shipping rate changes when the zip code is triggered during checkout
<img width="392" alt="schermafbeelding 2018-10-22 om 23 19 28" src="https://user-images.githubusercontent.com/8933779/47320401-a09ae180-d651-11e8-92c7-9f6cfff46029.png">

![shipping m2](https://user-images.githubusercontent.com/8933779/47320445-b8726580-d651-11e8-81b5-f10630327f77.gif)

**Comment by magento-engcom-team** [comment]
Hi @albsa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@albsa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by albsa** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @albsa. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @albsa, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18755-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18755-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18755-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by albsa** [comment]
Please use these settings for reproducing:
<img width="1007" alt="schermafbeelding 2018-10-23 om 14 31 32" src="https://user-images.githubusercontent.com/8933779/47360665-5b69c480-d6d0-11e8-9f6e-163bc8533743.png">

and this table rate csv.
```
Country,Region/State,"Zip/Postal Code","Weight (and above)","Shipping Price"
AUT,*,*,0.0000,6.9500
BEL,*,*,0.0000,6.9500
DEU,*,*,0.0000,6.9500
```

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](https://i-18755-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-18755-2-3-0.instances.magento-community.engineering/admin](https://i-18755-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TomashKhamlai** [comment]
@albsa, could you confirm that you see the expected result on the animation?
![peek](https://user-images.githubusercontent.com/11827230/49646198-4cd43400-fa16-11e8-9cb3-727028686b1e.gif)

**Comment by albsa** [comment]
@TomashKhamlai 
On your animation it looks like it works how it should work.

Just to confirm:

This is 1 STORE with 2 STOREVIEWS (2 different languages)
Both with their own default country settings when checkout page is loaded.
So storeview GERMANY is set as default country for the german URL
And the other with netherlands as settings

**Comment by TomashKhamlai** [comment]
@albsa previously I thought that this report describes behavior on Magento instance that has 2 websites on different domains, but according to your last comment now I understand that you were reporting about one store with two Store Views for different languages.

The first step in report processing is to identify whether problem is still is the latest code that is under development. I posted the animation that shows you how this works on development branch in case when there are 2 websites.
Later I tested on 2 Store Views and now I see that table rates are not listed until customer haven't specified the region or zip-code. I mean that it is impossible to reproduce your problem because table rates initially are prevented from displaying and when the customers specifies his location the table rates are calculated correctly.

Can I update your issue description to put there some more information that I collected?
- [ ] Yes
- [ ] No

I want to have some feedback from you, please answer the question:
How do you think would it be appropriate to merchants if customers were not able to have Table Rates listed in the checkout until they haven't filled the address information?
- [ ] Yes
- [ ] No

**Comment by albsa** [comment]
@TomashKhamlai It makes sense what you are saying that the table rates should only display after address information has been specified.

However, on the cart page, and on billing form page (checkout) the prices is already loaded initially with the wrong price.

> How do you think would it be appropriate to merchants if customers were not able to have Table Rates listed in the checkout until they haven't filled the address information?

another way what makes more sense is to set the table rate price related to the default shipping country of the store view.
In my opnion that is the most logic behaivour I would expect from it.
This also worked in M1 like that.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-tomash Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97406` were created

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @albsa ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce** - 
1. User should create 2 store views. Netherland (Default) and Germany
2. Navigate to Stores>Configuration
3. Select the scope to "Main Website"
<img width="871" alt="main website" src="https://github.com/user-attachments/assets/91abcd8f-d7bf-4374-88d5-a71e7a0f674f">
4. Click on sales> delivery methods
5. Export csv and then make changes with new shipping rates and import.
6.
