### ISSUE TITLE
Unique constraint violation found when changing order status

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#18763]
We are running into an issue that after successfully creating an order the order can't be cancelled or changed status. When we try do it we receive a "Unique constraint violation found" error. This problem also doesn't show up in the logs, so we haven't got any clue about whats happening. We expect the order to be cancelled or changed status.

### Preconditions (*)
Magento 2.2.6 (Developer mode)
PHP 7.1
MySQL 5.7

### Steps to reproduce (*)
1. Create order in the backend
2. Try to change the order status by changing its status or cancel / hold it.
3. Error occurs
4. Nothing shows up in the logs

### Expected result (*)
Order should be cancelled, hold or changed status.

### Actual result (*)
![schermafbeelding 2018-10-22 om 17 36 11](https://user-images.githubusercontent.com/7294081/47346187-d1f4cb00-d6ac-11e8-8102-35a0183b9171.png)

**Comment by magento-engcom-team** [comment]
Hi @jorgb90. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jorgb90 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by leanderf** [comment]
I can reproduce this issue, same setting.
Creating invoice for previous orders also fails.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-pb. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by jorgb90** [comment]
> I can reproduce this issue, same setting.
> Creating invoice for previous orders also fails.

@leanderf What do you think is causing it?

**Comment by leanderf** [comment]
@jorgb90 also found this post: https://magento.stackexchange.com/a/243837
But SALES_INVOICE_INCREMENT_ID_STORE_ID seems not related to this issue. I've also checked the DB for any kind of double entries. Are you working on a clean M2.2.6? 
Could be an upgrade issue from 2.2.5 to 2.2.6. No solution yet.

**Comment by jorgb90** [comment]
@leanderf Nearly clean, but its upgraded from previous versions, so an upgrade issue could be. Yours?

Edit: I think its not related as well..

**Comment by leanderf** [comment]
Currently I'm debugging the DB queries:
(https://devdocs.magento.com/guides/v2.2/config-guide/log/log-db.html)
and comparing M2.2.5 to 2.2.6:

Process: Create offline invoice for order with configurable product
```
# Missing in 2.2.6
SQL: DESCRIBE `sales_invoice`
```

Difference in inserting invoice items to DB:
2.2.5 (just the relevant parts)
```
INSERT INTO `sales_invoice_item`... (-> parent product)

UPDATE `sales_order_item`... (->parent product)
  5 => 'configurable',
  6 => '{"info_buyRequest":{"uenc":"aHR0cHM6Ly9wcmVsaXZlLm1mby1tYXRyYXR6ZW4uZGUvdml0YS1rYWx0c2NoYXVtbWF0cmF0emUtMjItY20tc29mdC1tZWRpdW0,","product":"128","selected_configurable_option":"","related_product":"","super_attribute":{"139":"31","140":"37"},"qty":"1"},"attributes_info":[{"label":"Gr\\u00f6\\u00dfe in cm","value":"140x200","option_id":139,"option_value":"31"},{"label":"H\\u00e4rtegrad","value":"medium - H3","option_id":140,"option_value":"37"}],"simple_name":"Matratze 22 cm medium 140x200","simple_sku":"7250100012","product_calculations":1,"shipment_type":0}',

INSERT INTO `sales_invoice_item` ... (->child product)

UPDATE `sales_order_item` (-> child product)
  5 => 'simple',
  6 => '{"info_buyRequest":{"uenc":"aHR0cHM6Ly9wcmVsaXZlLm1mby1tYXRyYXR6ZW4uZGUvdml0YS1rYWx0c2NoYXVtbWF0cmF0emUtMjItY20tc29mdC1tZWRpdW0,","product":"128","selected_configurable_option":"","related_product":"","super_attribute":{"139":"31","140":"37"},"qty":"1"}}',

```
2.2.6
```
INSERT INTO `sales_invoice_item` (->child product)

UPDATE `sales_order_item` (->child product)
  5 => 'simple',
  6 => '{"info_buyRequest":{"qty":1,"options":[]}}',
```

It seems like Magento would only save the child product on 2.2.6 whereas it saved both parent and child on 2.2.5. "options":[] are also empty at 2.2.6

@jorgb90 I'm trying the same now for simple products, but do you experience the issue on both types of products?

**Comment by leanderf** [comment]
its not limited to configurable products. It also happens with simple products.

**Comment by jorgb90** [comment]
@leanderf Yes we experience it on all types of products.

**Comment by jorgb90** [comment]
@leanderf We fixed the problem its not a core issue, but was related to the Amasty Product Grid module for Magento 2. I dont know if you have it installed as well, but its a problem with the QtySold indexer.

**Comment by leanderf** [comment]
ah yes - we are using the same module as well - thank you for this hint! Will give it a try!

**Comment by leanderf** [comment]
Issue solved - great job @jorgb90 !
Thank you!

**Comment by leanderf** [comment]
@jorgb90 did you already report this issue to Amasty? Otherwise I would get in contact.

**Comment by jorgb90** [comment]
@leanderf Great! Good to hear your problem is solved as well. Yes I have it reported to Amasty, but it shouldn't do any harm if you should do it as well!

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @jorgb90 thank you for you report, i'm closing this issue as this is not core magento issue and you solved this.
Best regards.

**Comment by orbisunom** [comment]
Just a quick input. on this problem and help others .. we are using amasty editor too so we try to install newly Magento 2.3.5 and migrate all product., order(Order, Invoice, Shipping)
the problem here is that Magento 1 have the same order, invoice, shipping number you need to update the sequence of 

Magento 2 

20200809 - any number or last order number from your Magento 1 site.
ALTER TABLE sequence_order_1 AUTO_INCREMENT = 20200809;
ALTER TABLE sequence_shipment_1 AUTO_INCREMENT = 20200809;
ALTER TABLE sequence_invoice_1 AUTO_INCREMENT = 20200811;
ALTER TABLE sequence_order_1 AUTO_INCREMENT = 20200811;

Before to proceed on migration you need to create a test product and process it so Magento 2 will not use order number 000000001 
TRY TO BUY 3 TIMES BEFORE MIGRATION OF ORDER

**Comment by huykon** [comment]
I am facing to this issue. Can anyone give me a solution?

**Comment by kostklip** [comment]
> Issue solved - great job @jorgb90 ! Thank you!

We have the same issue and using Amasty. Could you please let us know what exact steps you performed to solve the issue?

Thanks.
