### ISSUE TITLE
Dot (.) should be removed before validating customer email for GMAIL

### ISSUE THREAD

**Issue by mallikaverma** [magento/magento2#18760]
**Preconditions (*)**

1. Magento 2.2.x
2. PHP version: 7.0.24

 **Steps to reproduce (*)**

1. Go To Customer Create Account section
2. Create an account with email **mallikavermacedcommerce@gmail.com**
3. After creating you will receive a welcome email on **mallikavermacedcommerce@gmail.com**
4. Now again Go To Create Account section, create an account with email **mallikaverma.cedcommerce@gmail.com**.

 **Expected result (*)**

1. mallikaverma.cedcommerce@gmail.com customer should not be registered, As gmail considers **mallikavermacedcommerce@gmail.com** and **mallikaverma.cedcommerce@gmail.com** as same e-mail id.

**Actual result (*)**

1.  Account is successfully created and I received an welcome email on **mallikavermacedcommerce@gmail.com**

**Comment by magento-engcom-team** [comment]
Hi @mallikaverma. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mallikaverma do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mallikaverma** [comment]
@mallikaverma do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

**yes**

**Comment by gelanivishal** [comment]
Hello @mallikaverma,

Please check the attached screenshot, I can create an account
![2018-10-23_12-38-45](https://user-images.githubusercontent.com/12389799/47342191-b85d7e80-d6c0-11e8-8063-a016fcb5a65a.jpg)
Please check on vanilla version.

Thank you.

**Comment by pocallaghan** [comment]
The OP's point is that in gmail, Google ignores dots. This means that if you send an e-mail to `foobar@gmail.com` and `foo.bar@gmail.com`, they both end up in the same inbox. This is also possible with what Google calls labels, i.e. `foobar+anything@gmail.com` will also go to the same inbox. 

Whilst this can, in theory, be used to create infinite accounts using a single e-mail address. This is ultimate not that different to `anything@customdomain.com` re-directing to a catch-all inbox, allowing the same thing. The other potential problem would be if somebody could register an alternate account on Magento and session fixate the actual e-mail owner, they would potentially be confused into thinking it was their actual account, since, they'd receive order confirmation e-mails etc.

That said, I'm not sure it's the responsibility of Magento to deal with this. Every e-mail provider could have their own rules in this respect. I'd be interested why the OP thinks this is something Magento should be doing.

**Comment by mallikaverma** [comment]
@gelanivishal  
Please read my steps again. I know account with mallikaverma.cedcommerce@gmail.com and **mallikavermacedcommerce@gmail.com** both will be created on magento but welcome email for both accounts are getting send on **mallikavermacedcommerce@gmail.com** which is wrong.
As gmail consider both email ids as one.
But in magento, two accounts are created which will create issues.

Gmail will not allow to create account with **mallikaverma.cedcommerce@gmail.com** if **mallikavermacedcommerce@gmail.com** already exist.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mallikaverma** [comment]
@pocallaghan 
We can't ask Gmail people to make it compatible according Magento. Only we can make our system compatible with gmail.
In Magento we are having Modules like  Reward System, Referral System, Affiliate system and many more such Modules which will have issues like one customer will receive multiple emails but in magento they are different customers also if one customer will add dot in email id at 10 different places and create 10 different accounts so it will be harmful for site sometime.

**Comment by DanielRuf** [comment]
> mallikaverma.cedcommerce@gmail.com 

This is a totally different email address when it comes to the validation.
Same for any email address in this world.

This seems to be a specific edge case but I am sure that in most cases there can be email addresses like name and name.anotherstring @ gmail.

I would say that this is invalid.

**Comment by DanielRuf** [comment]
> The OP's point is that in gmail, Google ignores dots

I don't think that this is normal and that Google does this in general.

**Comment by DanielRuf** [comment]
> That said, I'm not sure it's the responsibility of Magento to deal with this.

I would say it is not our responsibility.

**Comment by DanielRuf** [comment]
> Please read my steps again. I know account with [mallikaverma.cedcommerce@gmail.com](mailto:mallikaverma.cedcommerce@gmail.com) and **[mallikavermacedcommerce@gmail.com](mailto:mallikavermacedcommerce@gmail.com)** both will be created on magento but welcome email for both accounts are getting send on **[mallikavermacedcommerce@gmail.com](mailto:mallikavermacedcommerce@gmail.com)** which is wrong.
> As gmail consider both email ids as one.
> But in magento, two accounts are created which will create issues.
> 
> Gmail will not allow to create account with **[mallikaverma.cedcommerce@gmail.com](mailto:mallikaverma.cedcommerce@gmail.com)** if **[mallikavermacedcommerce@gmail.com](mailto:mallikavermacedcommerce@gmail.com)** already exist.

We can not verify this and removing dots in general can cause more issues.

**Comment by DanielRuf** [comment]
https://support.google.com/mail/answer/10313?hl=en

This is very bad practice what Google is doing.

https://stackoverflow.com/questions/1586389/how-to-check-for-a-duplicate-email-address-in-php-considering-gmail-user-name

**Comment by ghost** [comment]
Hi @mallikaverma this is expected behavior, As says @DanielRuf -> "This is a totally different email address when it comes to the validation."

**Comment by ghost** [comment]
@mallikaverma I'm closing this issue, if you like to update, please reopen the issue, i'm not found the problem with creating another account, because they are different.

**Comment by mallikaverma** [comment]
Then how will Reward and Referral systems will work in any Magento based E-commerce site?

**Comment by ghost** [comment]
@mallikaverma To make this compatible with gmail magento needs apply the same logic as google filters his emails, this may cause more issues.
