### ISSUE TITLE
Translation issue send-friend in sendphtml

### ISSUE THREAD

**Issue by Franzld** [magento/magento2#18779]
### Preconditions (*)

1. Magento 2.2.6, , ,  
2. Unix Ubuntu 16.04.5 LTS
3. php 7.0.30
4. mysql 5.7.24

### Steps to reproduce (*)

1. install magento 2.2.6 with sample data 
2. add any translation (eg German) with the entry: "Email:,E-Mail:,,"
Set shop-> config->catalog->"Email to a friend" -> yes
3. call a Product -> Email to a Friend

### Expected result (*)

1. all labels should been shown right

### Actual result (*)

1. Label "E-Mail" of the invieder is shown wrong like -> "E\u002dMail"

### Fixing the issue (*)
/vendor/magento/module-send-friend/view/frontend/templates/send.phtml
remove "escapeJs" in line 34 : 
`<label for="recipients-email<%- data._index_ %>" class="label"><span><?= $block->escapeJs($block->escapeHtml(__('Email'))) ?></span></label>
`
change to:
`"<label for="recipients-email<%- data._index_ %>" class="label"><span><?= $block->escapeHtmlAttr(__('Email')) ?></span></label>"`

**Comment by magento-engcom-team** [comment]
Hi @Franzld. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Franzld do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Franzld** [comment]
To reproduce the issue without install a translation, you may edit 

> /vendor/magento/module-send-friend/view/frontend/templates/send.phtml

 replace `__('Email')` with

- `__('Em#ail')` or

 

- `__('E-Mail')`

**Comment by magento-engcom-team** [comment]
Hi @hardik-krish. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Franzld** [comment]
I'm sorry, but I'm not a developer and have only rudimentary programming skills.
I just found this problem and tried to fix it myself.

**Comment by ghost** [comment]
@Franzld - i checked this and there is no issue. You need to have utf-8 encoding in the csv file.
I think you opened the translation csv file in some text editor, due to this encoding standard of file was changed.
Please check.

**Comment by Franzld** [comment]
Thanks for your answer!
I've checked it and the same issue appears. Both files ( de_DE.csv and send.phtml) are encode to utf-8

please try to replace in 
 /vendor/magento/module-send-friend/view/frontend/templates/send.phtml at line 34
`__('Email')` to `__('E-mail')`
like this:
` <label for="recipients-email<%- data._index_ %>" class="label"><span><?= $block->escapeJs($block->escapeHtml(__('E-mail'))) ?></span></label> `

if there's no issue at your place, something with my server-config may be wrong.

**Comment by ghost** [comment]
@Franzld - Yes, I am able to reproduced the issue even with UTF-8 encoding.

**Comment by ghost** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @Franzld. Thank you for your report. 
The issue has been fixed in magento/magento2#18886 by @rahulwebkul in 2.2-develop branch
Related commit(s):
 - [443e681a41dfcd9c3a446c8c9c7b6c240c52857e](https://github.com/magento/magento2/commit/443e681a41dfcd9c3a446c8c9c7b6c240c52857e)

The fix will be available with the upcoming 2.2.8 release.

**Comment by okorshenko** [comment]
Hi @Franzld. Thank you for your report. 
The issue has been fixed in magento/magento2#18889 by @rahulwebkul in 2.3-develop branch
Related commit(s):
 - [008fe5d2bec2167e29d45001a674de8249e393e7](https://github.com/magento/magento2/commit/008fe5d2bec2167e29d45001a674de8249e393e7)
 - [7db2cc9fbac6adc17e43be576aa149b7e7965b8a](https://github.com/magento/magento2/commit/7db2cc9fbac6adc17e43be576aa149b7e7965b8a)
 - [0f91cb7280269b4cf3421eaf03643cc6670f7626](https://github.com/magento/magento2/commit/0f91cb7280269b4cf3421eaf03643cc6670f7626)
 - [1c23cf94322a1543f037b95ce36dde4029b948aa](https://github.com/magento/magento2/commit/1c23cf94322a1543f037b95ce36dde4029b948aa)

The fix will be available with the upcoming 2.3.1 release.
