### ISSUE TITLE
Product Advanced Pricing design issue

### ISSUE THREAD

**Issue by saphaljha** [magento/magento2#18775]
### Preconditions (*)

1. Install the newest version 2.3.X

### Steps to reproduce (*)

1. Add new product
2. Add new tierprice 

### Expected result (*)

![products-advance-pricing-catalog-magento-admin-expected](https://user-images.githubusercontent.com/23274052/47412052-3769ba00-d788-11e8-8bd7-76d966ded136.png)

### Actual result (*)

![products-advance-pricing-catalog-magento-admin-actual](https://user-images.githubusercontent.com/23274052/47412129-6a13b280-d788-11e8-9aad-c72553cd6aea.png)

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@saphaljha do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by sidolov** [comment]
Hi @saphaljha. Thank you for your report. 
The issue has been fixed in magento/magento2#18790 by @ashutoshwebkul in 2.3-develop branch
Related commit(s):
 - [6bb825873812cff3ab77d71f1f3542d40aae2b85](https://github.com/magento/magento2/commit/6bb825873812cff3ab77d71f1f3542d40aae2b85)

The fix will be available with the upcoming 2.3.1 release.

**Comment by engcom-backlog-nazar** [comment]
HI @saphaljha i'm closing this issue as this already fixed in 2.3-develop branch

**Comment by SyntaxKay** [comment]
Hi @engcom-backlog-nazar 
I have started working on 2.3x Instance to resolve this issue.

**Comment by ghost** [comment]
Hi @speedy008  this issue fixed in 2.3-develop, just leave this open.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96739` were created

**Comment by ghost** [comment]
Hi @saphaljha , thank you for you report, this issue has already fixed in 2.3-develop branch, and will be available on 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your report. 
The issue has been fixed in magento/magento2#21229 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [079d5d5f99f1cd6db5d03fb1adba3e685fd3b8f9](https://github.com/magento/magento2/commit/079d5d5f99f1cd6db5d03fb1adba3e685fd3b8f9)

The fix will be available with the upcoming 2.2.9 release.
