### ISSUE TITLE
Cron schedule on every day-of-week are random

### ISSUE THREAD

**Issue by dev-awevo** [magento/magento2#18770]
### Preconditions (*)

Magento v2.2.6

#### Configuration Locale Options (Default Config)
**Timezone**: Central European Standard Time (Europe/Paris)
**Locale**: French (France)
**First Day of Week**: Monday	
**Weekend Days**: Sunday, Saturday

#### Define any cronjob to run on every day-of-week from Monday through Friday, for example
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
    <group id="my_group">
        <job name="day_of_week_cronjob" instance="Some\Vendor\Class\Cronjob" method="execute">
            <schedule>0 12 * * 1-5</schedule>
        </job>
    </group>
</config>
```

### Expected result (*)

The cronjob should be executed at 12:00 on every day-of-week from Monday through Friday.

### Actual result (*)

The cronjob is executed randomly, without respecting the days of the week, for example I have weeks where the cron runs every day except for Friday, other weeks is Sunday and Monday that are skipped !

### Suggest solution
On the version 2.1.x of Magento, we do not encounter the problem, by comparing the files relating to the CRON, we observe the addition of line 115 in the model `Magento\Cron\Model\Schedule`

If you comment out line 115 or so in `Magento\Cron\Model\Schedule`:
```
$time = $this->timezoneConverter->date($time)->format('Y-m-d H:i');
```
We no longer observe this random problem of day-of-week.

**Comment by magento-engcom-team** [comment]
Hi @dev-awevo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dev-awevo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @dev-awevo thank you for you report, 
```
//convert time from UTC to admin store timezone
 //we assume that all schedules in configuration (crontab.xml and DB tables) are in admin store timezone
```
You need to set right timezone for  admin store timezone,
