### ISSUE TITLE
Checkout address custom attributes don't get rendered in address information components

### ISSUE THREAD

**Issue by tdgroot** [magento/magento2#18785]
Checkout address custom attributes don't get rendered in address information components. In fact, the rendering of such components produce errors:

```
Uncaught TypeError: Unable to process binding "foreach: function(){return getRegion('ship-to') }"
Message: Unable to process binding "template: function(){return getTemplate() }"
Message: Unable to process binding "foreach: function(){return { data:elems,as:'element'} }"
Message: Unable to process binding "template: function(){return element.getTemplate() }"
Message: Unable to process binding "if: function(){return visible() }"
Message: Unable to process binding "foreach: function(){return {data:address().customAttributes,as:'element'} }"
Message: Unable to process binding "foreach: function(){return {data:Object.keys(element),as:'attribute'} }"
Message: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at foreach (eval at createBindingsStringEvaluator (knockout.js:2992), <anonymous>:3:80)
    at knockout.js:4281
    at Object.init (knockout.js:5464)
    at init (knockout.js:4306)
    at knockout.js:3368
    at Object.ignore (knockout.js:1480)
    at knockout.js:3367
    at Object.arrayForEach (knockout.js:159)
    at applyBindingsToNodeInternal (knockout.js:3353)
```

I stumbled upon this problem when creating a new field for the shipping address in the checkout, using [this devdocs article](https://devdocs.magento.com/guides/v2.2/howdoi/checkout/checkout_new_field.html).

The issue occurs in the following places:
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Checkout/view/frontend/web/template/billing-address/details.html#L15
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Checkout/view/frontend/web/template/shipping-information/address-renderer/default.html#L15

The problem seems to be that address.customAttributes is an object that looks like this:
```
{ my_custom_attribute: "1234" }
```

But it actually needs to be an array that looks like:
```
[
  {
    "my_custom_attribute": {
      "label": "My custom field",
      "value": "1234"
    }
  }
]
```

### Preconditions (*)

1. Magento 2.2.5+ or 2.3

### Steps to reproduce (*)

1. Create a module which adds a field to the checkout address form.
2. Add product to cart.
3. Go to checkout.
4. Fill in address details, including the custom field.
5. Click on `Next` button.
6. See console error like shown above.

### Expected result (*)

1. Rendering of address information(both billing and shipping) produces error. Custom field is rendered in address information component.

### Actual result (*)

1. Rendering of address information(both billing and shipping) produces error. Custom field doesn't get rendered in address information component.

**Comment by magento-engcom-team** [comment]
Hi @tdgroot. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tdgroot do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @tdgroot thank you for you report, I'm no able to reproduce following steps your described
![field](https://user-images.githubusercontent.com/40756439/47782196-54623800-dd08-11e8-8893-230323371f4e.gif)

**Comment by tdgroot** [comment]
@engcom-backlog-nazar strange.. since I updated my local 2.3-develop environment, the problem seems to be solved. I can't reproduce it anymore as well. 

Thanks for checking the issue and my apologies for the inconvenience.

**Comment by nikunj8892** [comment]
The above issue is caused by Temando_ShippingM2 module, with the following code, it is overriding "ship-to" component in checkout page layout.

```
<item name="shipping-information" xsi:type="array">
    <item name="children" xsi:type="array">
        <item name="ship-to" xsi:type="array">
            <item name="rendererTemplates" xsi:type="array">
                <item name="customer-address" xsi:type="array">
                    <item name="component" xsi:type="string">Temando_Shipping/js/view/checkout/shipping-information/address-renderer/shipping</item>
                </item>
                <item name="new-customer-address" xsi:type="array">
                    <item name="component" xsi:type="string">Temando_Shipping/js/view/checkout/shipping-information/address-renderer/shipping</item>
                </item>
            </item>
        </item>
    </item>
</item>
```
So, in Temando_Shipping/js/view/checkout/shipping-information/address-renderer/shipping i.e.
vendor/temando/module-shipping-m2/view/frontend/web/js/view/checkout/shipping-information/address-renderer/shipping.js
JS File, which is rendering the custom Attributes in Ship To section on payment step of checkout is missing with the following function :
````
/**
 * Get customer attribute label
 *
 * @param {*} attribute
 * @returns {*}
 */
getCustomAttributeLabel: function (attribute) {
    var resultAttribute;

    if (typeof attribute === 'string') {
        return attribute;
    }

    if (attribute.label) {
        return attribute.label;
    }

    resultAttribute = _.findWhere(this.source.get('customAttributes')[attribute['attribute_code']], {
        value: attribute.value
    });

    return resultAttribute && resultAttribute.label || attribute.value;
}
````
So, adding this function by overriding the js file helped me.

To override the js file you can follow below steps:
1.Create Custom Module : Company_Module
2.Create requirejs-config.js file under directory 
app/code/Company/Module/view/frontend/
And add following code in it:

```
var config = {
    map: {
        '*': {
            'Temando_Shipping/js/view/checkout/shipping-information/address-renderer/shipping':'Company_Module/js/view/temando/checkout/shipping-information/address-renderer/shipping'
        }
    }
};
```
3. In the overridden file you can add the above function "getCustomAttributeLabel" which is written above.

Thanks

**Comment by mizzimizzi** [comment]
Please check this for the solution:
https://github.com/magento/magento2/commit/6d985af3486280a5a672ef32681a6cdb2a148aa3
