### ISSUE TITLE
Product Image Placeholders are not saved correctly in stores configuration section

### ISSUE THREAD

**Issue by Perzonallica** [magento/magento2#18781]
### Preconditions (*)

1. Magento version 2.2.6
2. PHP 7.0.32
3. nginx/1.10.3
4. MySQL 5.6.37

### Steps to reproduce (*)

1. Open Stores->Configuration->Catalog->Catalog page
2. Open _Product Image Placeholders tab_
3. Select images for placeholders
4. Save Config

### Expected result (*)

1. Upload the images to the server and save the correct path in the _core_config_data_ table which I assume is the following:
```
catalog/placeholder/thumbnail_placeholder
catalog/placeholder/swatch_image_placeholder
catalog/placeholder/small_image_placeholder
catalog/placeholder/image_placeholder
```
2. Uploaded images are visible in the Stores configuration section.

### Actual result (*)

1. Doesn't matter if I upload image only for Base, Small or for every option at once, Magento always uploads the file to the server, but saves the following path to the _core_config_data_ table:
`catalog/placeholder/placeholder`
2. It seems for me that the prefix is not generated correctly.
3. So because of this it is not possible to change the default placeholder image.

### Additional info
1. It works in Magento version 2.2.3 and 2.2.4

**Comment by magento-engcom-team** [comment]
Hi @Perzonallica. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Perzonallica do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Shubham0492** [comment]
@Perzonallica I have checked this issue in 2.2-dev.It has been fixed.

**Comment by Perzonallica** [comment]
@Shubham-Webkul Hi! Can you please give me a link, or any info about this fix, I couldn't find it anywhere.  Thanks.

**Comment by Shubham0492** [comment]
@Perzonallica Please check to 2.2-dev magento instance.This issue will not occur.

**Comment by martin-ramos** [comment]
I use Magento 2.2.6 and I have the same problem with image placeholders. I update to 2.2-dev and I have the same problem. Could you show me the code that correct this issue? or Could you tell me how did you resolve this problem?

**Comment by mropanen** [comment]
They're probably referring to this https://github.com/magento/magento2/pull/18660
