### ISSUE TITLE
Able to checkout even with an out of stock product

### ISSUE THREAD

**Issue by wittyvishwas** [magento/magento2#18793]
**Preconditions**

Magento 2.2.6 installed with sample data , PHP 7.1 and MYSQL 5.6 With Ngnix

Add an in stock product and proceed to checkout 

**Steps to reproduce**

1) Add product to cart
2) Proceed to checkout ,on payment page make the product in cart out of stock (Using the stock attribute not qty, keep the qty as it is ) and re-index if required.
3) Click on place order 

**Expected result**

order place failed with error message 

> Not all of your products are available in the requested quantity.

**Actual result**

Order Place success, which should not be possible for out of stock product 

On a contrary  ,
1) Add product to cart
2) Proceed to checkout ,on payment page make the product in cart out of stock by setting the qty to zero and re-index if required.
3) Click on place order 

Order place will fail and will get error message

**Comment by magento-engcom-team** [comment]
Hi @wittyvishwas. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@wittyvishwas do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @wittyvishwas thank you for you report, the fix for this issue has already available in 2.2-develop and 2.3-develop branch.
![selection_173](https://user-images.githubusercontent.com/40756439/47483726-9e4ba980-d842-11e8-84d0-dc35979f31ef.png)
