### ISSUE TITLE
Magento 2 catelog product - related products on different users are deleted when saved

### ISSUE THREAD

**Issue by stijnkuppens** [magento/magento2#18799]
### Preconditions (*)

1. Magento ver. 2.2.4 !! EE edition to restrict admins for store views
2. Backend Catalog products

### Steps to reproduce (*)

1. log in in backend of Magento 2
2. Edit a product that is available on the frontend and you have rights to edit, make sure there is another backend user that is able to edit this product
3. Add related products
4. Save the product
5. Logout
6. Login with the other admin user (with only storeview edit rights)
7. Go to catalog products to the same product you have edit before 
8. Go to related products
9. Add a new related product
10. save the product 

### Expected result (*)

1. The expected result is that the related product is saved and the existing related products are also still present.

### Actual result (*)

1. The actual result is that all related products are gone, deleted, not there.

**Comment by magento-engcom-team** [comment]
Hi @skdude. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@skdude do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by stijnkuppens** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @skdude. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @skdude, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18799-2-2-4/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18799-2-2-4//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18799-2-2-4//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by stijnkuppens** [comment]
@magento-engcom-team give me 2.2.4 Enterprise instance

**Comment by magento-engcom-team** [comment]
Hi @skdude. Thank you for your request. I'm working on Magento 2.2.4 Enterprise instance for you

**Comment by navarr** [comment]
@skdude If this is an issue with the enterprise edition, you should probably try contacting Magento support instead of creating a github issue

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @skdude , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
