### ISSUE TITLE
Multivalued filters don't work correctly with ElasticSearch

### ISSUE THREAD

**Issue by xi-ao** [magento/magento2#18802]
### Preconditions

1. Install Magento 2.2.6 and ES 5.x
2. Create a multiselect filterable attribute and assign 3 values to it : "A", "B", "C"
3. Create a category, an enabled product and select "A" and "C" values for the previous attribute. Put the product in the category.
4. Configure ES as search engine
5. Reindex all

### Steps to reproduce

1. Go to the category page, the product should be displayed

### Expected result

1. In the **filter block** the attribute should appear with the options "A" and "C" (the only values with non-null result after filtering)

### Actual result

1. The filter won't appear.

The cause seems to be because the attribute is registered in ES with the [`keyword` analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/analysis-keyword-analyzer.html) which creates a single term with the attribute's option IDs (let's say "`23 24`") and the search request is sent with the [`term` query](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/query-dsl-term-query.html) which searches for an exact match for each option ID (let's say "`23`" or "`24`", which obviously won't match here).

Of course, switching to MySQL search engine instead of ES solves the issue.

**Comment by magento-engcom-team** [comment]
Hi @xi-ao. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@xi-ao do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by xi-ao** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @xi-ao. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @xi-ao, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18802-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18802-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18802-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by xi-ao** [comment]
@magento-engcom-team This instance **does not** have an ES attached, I can't reproduce the problem in that conditions.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
### Preconditions
```
# Import GPG Key
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

# Install ElasticSearch 5.6 on Debian Stretch
sudo apt-get install apt-transport-https
echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
sudo apt-get update && sudo apt-get install elasticsearch
```
Magento 2.3-develop commit d7012b2ca1495676478d8afed8bf016ccd03bc8a

### Steps to reproduce

1. Login to admin
2. Create Simple Product 1 and assign it to Category 1 during the product creation(it will be existing product that got an attribute later)
3. Navigate to **Stores -> Attributes -> Product**
4. Click **Add New Attribute**
 - Default label **attr_multisel**
 - Catalog Input Type for Store Owner **Multiple Select**
 - Options: **A, B, C** (none of them is required or default)
 - Advanced Attribute Properties:
 - Scope: **Global**
 - Storefront Properties:
 - Use in Search **Yes**
 - Use in Layered Navigation: **Filterable (with results)**
5. Click **Save Attribute**
6. Navigate to **Stores -> Attributes -> Attribute Set**
7. Add **attr_multisel** to the **Default** attribute set
8. Perform **Full Reindex** and **Flush Cache**
9. Edit **Simple Product 1** to add A and C values and Save the product
10. Create **Simple Product 2** and assign it to **Category 2** and **Category 1**
11. Navigate to **Stores -> Configuration -> Catalog -> Catalog -> Catalog Search** and set **Search Engine** to **Elasticsearch 5.0+** then press **Test Connection**
12. Verify that button value changed to **Successful! Test again?** and click **Save Config**
13. Perform **Full Reindex** and **Flush Cache**
14. Navigate to Category 1 and Category 2

### Expected result
In the **filter block** the attribute should appear with the options "A" and "C" (the only values with non-null result after filtering)

### Actual result
There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: XXXXXXXXXXXX

### Exception log:
```
{"0":"Notice: Undefined index: manufacturer_bucket in \/var\/www\/html\/pr\/app\/code\/Magento\/Elasticsearch\/SearchAdapter\/Aggregation\/Builder\/Term.php on line 23","1":"#0 \/var\/www\/html\/pr\/app\/code\/Magento\/Elasticsearch\/SearchAdapter\/Aggregation\/Builder\/Term.php(23): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Undefined index...', '\/var\/www\/html\/p...', 23, Array)\n#1 \/var\/www\/html\/pr\/app\/code\/Magento\/Elasticsearch\/SearchAdapter\/Aggregation\/Builder.php(90): Magento\\Elasticsearch\\SearchAdapter\\Aggregation\\Builder\\Term->build(Object(Magento\\Framework\\Search\\Request\\Aggregation\\TermBucket), Array, Array, Object(Magento\\Elasticsearch\\SearchAdapter\\Dynamic\\DataProvider))\n#2 \/var\/www\/html\/pr\/app\/code\/Magento\/Elasticsearch\/Elasticsearch5\/SearchAdapter\/Adapter.php(127): Magento\\Elasticsearch\\SearchAdapter\\Aggregation\\Builder->build(Object(Magento\\Framework\\Search\\Request), Array)\n#3 \/var\/www\/html\/pr\/app\/code\/Magento\/Search\/Model\/SearchEngine.php(42): Magento\\Elasticsearch\\Elasticsearch5\\SearchAdapter\\Adapter->query(Object(Magento\\Framework\\Search\\Request))\n#4 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Search\/Search.php(72): Magento\\Search\\Model\\SearchEngine->search(Object(Magento\\Framework\\Search\\Request))\n#5 \/var\/www\/html\/pr\/app\/code\/Magento\/CatalogSearch\/Model\/ResourceModel\/Fulltext\/Collection.php(359): Magento\\Framework\\Search\\Search->search(Object(Magento\\Framework\\Api\\Search\\SearchCriteria))\n#6 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Data\/Collection\/AbstractDb.php(341): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection->_renderFiltersBefore()\n#7 \/var\/www\/html\/pr\/app\/code\/Magento\/CatalogSearch\/Model\/ResourceModel\/Fulltext\/Collection.php(409): Magento\\Framework\\Data\\Collection\\AbstractDb->_renderFilters()\n#8 \/var\/www\/html\/pr\/app\/code\/Magento\/Eav\/Model\/Entity\/Collection\/AbstractCollection.php(920): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection->_renderFilters()\n#9 \/var\/www\/html\/pr\/app\/code\/Magento\/Catalog\/Model\/ResourceModel\/Product\/Collection.php(790): Magento\\Eav\\Model\\Entity\\Collection\\AbstractCollection->load(false, false)\n#10 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection->load(false, false)\n#11 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callParent('load', Array)\n#12 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#13 \/var\/www\/html\/pr\/generated\/code\/Magento\/CatalogSearch\/Model\/ResourceModel\/Fulltext\/Collection\/Interceptor.php(325): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callPlugins('load', Array, Array)\n#14 \/var\/www\/html\/pr\/app\/code\/Magento\/Review\/Observer\/CatalogBlockProductCollectionBeforeToHtmlObserver.php(38): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->load()\n#15 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Event\/Invoker\/InvokerDefault.php(72): Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#16 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver), Object(Magento\\Framework\\Event\\Observer))\n#17 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Event\/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#18 \/var\/www\/html\/pr\/generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('catalog_block_p...', Array)\n#19 \/var\/www\/html\/pr\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(471): Magento\\Framework\\Event\\Manager\\Proxy->dispatch('catalog_block_p...', Array)\n#20 \/var\/www\/html\/pr\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(116): Magento\\Catalog\\Block\\Product\\ListProduct->initializeProductCollection()\n#21 \/var\/www\/html\/pr\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(348): Magento\\Catalog\\Block\\Product\\ListProduct->_getProductCollection()\n#22 \/var\/www\/html\/pr\/generated\/code\/Magento\/Catalog\/Block\/Product\/ListProduct\/Interceptor.php(154): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()\n#23 \/var\/www\/html\/pr\/app\/code\/Magento\/PageCache\/Model\/Layout\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct\\Interceptor->getIdentities()\n#24 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\Interceptor), '\\n    <script ty...')\n#25 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#26 \/var\/www\/html\/pr\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(494): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\n#27 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\n#28 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#29 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#30 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n#31 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#32 \/var\/www\/html\/pr\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(130): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\n#33 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#34 \/var\/www\/html\/pr\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#35 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(257): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#36 \/var\/www\/html\/pr\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#37 {main}","url":"\/category-1.html","script_name":"\/index.php"}
```

**Comment by TomashKhamlai** [comment]
I was not able to reproduce the issue on latest 2.2-develop and latest available ElasticSearch 5+, because ElasticSearch was not in the list of available search providers.

![screenshot_20181109_161614](https://user-images.githubusercontent.com/11827230/48267392-e837b080-e43a-11e8-81eb-6ca1f9467e19.png)

Additional information:
```
"version" : {
    "number" : "5.6.13",
    "build_hash" : "4d5320b",
    "build_date" : "2018-10-30T19:05:08.237Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  }
```

@xi-ao, please specify your version of ElasticSearch.
I check the version by executing this request:
```
curl -X GET "localhost:9200/"
```

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96261` were created

**Comment by xi-ao** [comment]
> @xi-ao, please specify your version of ElasticSearch.

We're using the version of ES provided by Magento Cloud, so:
```
{
  "version" : {
    "number" : "5.2.2",
    "build_hash" : "f9d9b74",
    "build_date" : "2017-02-24T17:26:45.835Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  }
}
```

**Comment by TomashKhamlai** [comment]
@lorikrell, @keharper, probably we will need a help with DevDocs from one of you.

In this [Config Guide](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html#es-install-es5) we see that there should be no problem if the most recent version of ElasticSearch is used. I am not sure but it looks to me that we should **strongly recommend** only 5.2.2 version of ElasticSearch because it was tested.

> You can select a more recent version of 5.x, but 5.2 has been tested.

I think this topic is disputable. So don't do it in a hurry, I must double check the problem. I will write a message after recheck.

The proposed change:
`3. Ubuntu: Install the Elasticsearch 5.2 version using the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/deb.html)`

`3. Ubuntu: Install the Elasticsearch 5.2 version using the [Elasticsearch documentation](https://www.elastic.co/downloads/past-releases/elasticsearch-5-2-2)`

The reason:
Existing link guides people to install from Apt Repository. Actually they show two different ways to get things done, but only second will work. Lot of user prefer installing from Apt Repository, because this allows you to get the latest updates. So even if the order of instructions was reversed, I do not think that it would change a lot for us.

**Comment by TomashKhamlai** [comment]
@xi-ao, thank you for update.

**Comment by TomashKhamlai** [comment]
Same symptoms here #18817

**Comment by TomashKhamlai** [comment]
@xi-ao, you mentioned that you use Magento Cloud edition. Most of the time we do not check on clouds. If the issue by your steps won't be reproducible on Magento 2 Open Source with ES 5.2.2, then this issue will be closed, and I will ask you to create a support ticket on Magento Cloud Platform.

**Comment by keharper** [comment]
I'll help with the documentation updates.

**Comment by xi-ao** [comment]
> @xi-ao, you mentioned that you use Magento Cloud edition. Most of the time we do not check on clouds. If the issue by your steps won't be reproducible on Magento 2 Open Source with ES 5.2.2, then this issue will be closed, and I will ask you to create a support ticket on Magento Cloud Platform.

We're using Magento Cloud for production of course, but the issue can be reproduce on local, development-oriented instances too.

**Comment by dan-ding** [comment]
seems to happen with 2.2.6 EE for the curious

**Comment by hmphu** [comment]
+1 happened for me with 2.3.0

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@dan-ding have you already created a support ticket on Magento Cloud Platform or Magento Commerce account?
ElasticSearch is a new feature for Magento Open Source 2.3.0 and we aknowledged the issue. Even when the issue will be fixed here you still should ask for help from Magento Commerce support team.

**Comment by seyuf** [comment]
Any news on this?
M 2.3.0 community
Elasticsearch
```
"version" : {
    "number" : "5.6.16",
    "build_hash" : "3a740d1",
    "build_date" : "2019-03-13T15:33:36.565Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
```

**Comment by sdzhepa** [comment]
Hello @xi-ao @seyuf @TomashKhamlai 

Could you please confirm is it still actual for `2.3-develop` latest code?

I see that related internal Jira tickets(`MAGETWO-96261`, `MC-5501`) has been closed with a resolution **Cannot Reproduce** and comment that it was fixed previously

**Comment by seyuf** [comment]
Hi @sdzhepa , 
Indeed im unable to reproduce the error.
The bug seems to be absent from current `2.3-develop`.
Tested on elasticsearch 5.6.1 with magento backend option `elasticsearch 5.0+`
```
{
  "name" : "kjc7x2r",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "wlx_aKCYRtSBNjSOjGumfQ",
  "version" : {
    "number" : "5.6.1",
    "build_hash" : "667b497",
    "build_date" : "2017-09-14T19:22:05.189Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}

```

Also tested on elasticsearch 6.X, with magento option `elasticsearch 6.0+` no issues there as well.

Side note:
_I encountered the error on 2.3.0 with elasticsearch 5.0.
(see @TomashKhamlai [steps to reproduce the bug](https://github.com/magento/magento2/issues/18802#issuecomment-437362675) )_

Regards.

**Comment by engcom-Delta** [comment]
Hi @seyuf thanks for reply. 
I rechecked issue on 2.3-develop with elasticsearch 6.x and issue is not reproducible.
```{
  "name" : "6Zvzjpo",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "qHO_qpnLQBOf2UPG8Fcr1w",
  "version" : {
    "number" : "6.5.4",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "d2ef93d",
    "build_date" : "2018-12-17T21:17:40.758843Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
Closed as fixed in 2.3-develop

**Comment by michaeldyl520** [comment]
The data written to elasticsearch is incorrect.
See file with namespace
Magento\Elasticsearch\Model\Adapter\BatchDataMapper\ProductDataMapper
line 293
replace 
```
return str_replace(',', ' ', $value);
```
to
```
return explode(',',$value);
```

**Comment by kestraly** [comment]
Magepow\Layerednav\Model\Layer\Filter\Attribute.php

`$productCollection->addFieldToFilter($attribute->getAttributeCode(), array('ln_filter' => $valueFilter));`

The code suggested in Elastic Search already exists. 

Will see if I can find a solution with this line of code
