### ISSUE TITLE
Using Multiple Filters in Layered Navigation May Lead to 0 Results

### ISSUE THREAD

**Issue by uandiweb** [magento/magento2#18819]
### Preconditions (*)

Magento 2.2.5 (2.2.6 should also have the same issue)

### Steps to reproduce (*)

1. Visit the category page "Women" > "Tops": https://uandi.work/Luma/women/tops-women

2. Under the filter "Style" select "Insulated" and you should see in the results item name "Inez Full Zip Jacket" (SKU WJ07).

3. Clear the filter (you should see all products in the category again).

4. Under the filter "Color" select "Purple" and you should see in the results item name "Inez Full Zip Jacket" (SKU WJ07).

5. Clear the filter (you should see all products in the category again).

6. Under the filter "Style" select "Insulated" + Under the filter "Color" select "Purple".

### Expected result (*)

1. Item name "Inez Full Zip Jacket" (SKU WJ07) should show in the results since it meets both filters (insulated & purple). Most likely other items also meet both filters and should show. 

### Actual result (*)

1. There are 0 results (Magento message "We can't find products matching the selection").

**Comment by magento-engcom-team** [comment]
Hi @uandiweb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@uandiweb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by webkul-ratnesh** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @ShawnAbramson. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@ShawnAbramson Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96036`, `MAGETWO-96037` were created

**Comment by uandiweb** [comment]
Is there a temporary fix? Any store that has multiple filters is probably losing sales due to the incorrect message: "We can't find products matching the selection". The 2018 holiday season is right around the corner, and this needs a fix.

Thank you!

**Comment by Stoux** [comment]
@uandiweb Did you manage to find a (temp-)fix?
We're experiencing the same issue. As soon as the other attribute filter [is added](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/LayeredNavigation/Block/Navigation.php#L67) the results dwindle to to 0.

**Comment by XxXgeoXxX** [comment]
@uandiweb
look  like you have problem  https://github.com/magento/magento2/issues/12240
Please, try a solution from attached issue.

**Comment by uandiweb** [comment]
> @uandiweb
> look like you have problem #12240
> Please, try a solution from attached issue.

I can confirm the solution for problem #12240 also resolves this issue (#18819).

**Comment by sdzhepa** [comment]
Closed according to the last comment from the reporter

> I can confirm the solution for problem #12240 also resolves this issue (#18819).

Link: https://github.com/magento/magento2/issues/18819#issuecomment-459106267
