### ISSUE TITLE
Unable to update simple product custom option in cart when quantity is 1

### ISSUE THREAD

**Issue by ikrestov** [magento/magento2#18812]
### Preconditions (*)

1. Magento CE 2.2.5, Updated(9/19/2019) **can be reproduced on 2.3**
2. Although reproduced in 2.2.2-2.2.4
3. Backorders disabled, minimum order qty is 1.
4. A simple product with at least one custom option, e.g. size - 1,2,3; price type fixed.

### Steps to reproduce (*)

1. Go to product page and select options and click add to cart. || _Update 9/19/2019_:  _**The quantity of the product added must be more than a half of its Stock quantity!**_ ||
2. Go to cart and select "Edit/Update Item"
3. Select different option from original and click update.

### Expected result (*)

1. Redirected back to cart
2. Product custom option updated.

### Actual result (*)

1. Error message on product page.
![image](https://user-images.githubusercontent.com/1066322/47514211-bbe73600-d877-11e8-963e-1d429115c4ee.png)
 || _Update 9/19/2019_: **_(Those messages haven't been observed at now. Only the one below still appears)_** ||
The requested qty is not available

### Notes
It manifests as well if you have configurable product, where associated product has 1 stock, and configurable has custom option. Once selected and added to cart. If you try to update only custom option, the result is the same.

It appears that the code in `Magento/Quote/Model/Quote.php#updateItem` updates product item or adds new one if product item with matching custom/configurable options does not exist and later removes old item.
Problem is inside `updateItem()`, call to to [addProduct()](https://github.com/magento/magento2/blob/2.2.5/app/code/Magento/Quote/Model/Quote.php#L1758) throws, because actual product qty is 1.

**Comment by magento-engcom-team** [comment]
Hi @ikrestov. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ikrestov do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ikrestov** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ikrestov. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ikrestov, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-5/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-5//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-5//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ikrestov** [comment]
@magento-engcom-team 
Reproduced.

![image](https://user-images.githubusercontent.com/1066322/47515981-1d110880-d87c-11e8-80ca-f5573be7c5d8.png)
![image](https://user-images.githubusercontent.com/1066322/47516005-2dc17e80-d87c-11e8-9f37-fc141bb122e9.png)
![image](https://user-images.githubusercontent.com/1066322/47516015-36b25000-d87c-11e8-97e1-7fc2df9ab5f1.png)

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-5/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-5//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-5//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18812-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Adding more to the issue reproduction:
The issue can be generated if the product stock quantity is equal to the quantity in cart and then we try to update the cart options, we are getting the error message as We don't have as many "test  product" as you requested.
Also, this is not related to qty 1 in stock, it can be reproduced with 50 qty in stock and then adding 50 qty in cart and then editing custom options.
It gives error until the qty is equal to at least double the qty in cart.

**Comment by magento-engcom-team** [comment]
@ayazwebkul Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@ayazwebkul Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@ayazwebkul Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95948` were created

**Comment by magento-engcom-team** [comment]
Hi @ketan-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-18812-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-18812-2-3-0.instances.magento-community.engineering/admin](https://i-18812-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Refresh

**Comment by shikhamis11** [comment]
#imagine2019

**Comment by shikhamis11** [comment]
#mleu2019

**Comment by shikhamis11** [comment]
@magento I am working on this issue

**Comment by ankursharma1930** [comment]
is this issue resolved #18812 ? Please let me know the commit or code

**Comment by sezio** [comment]
Hello, 
Did anybody found a solution for this problem ? Thanks

**Comment by Payless** [comment]
I have updated the magento version to 2.2.9 and it's working fine, maybe you need to update your magento version

**Comment by ankursharma1930** [comment]
I have updated the magento version to 2.2.9 and it's working fine, maybe you need to update your magento version

**Comment by Payless** [comment]
Thanks for your email,

Our office is currently not open until 8.30am in the morning. We appreciate your email and will get back to you ASAP.

Guy Dawson |

Payless Promotions

P: 1300 658 610

E: guy@paylesspromotions.com.au

Website<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fwww.paylesspromotions.com.au%2F&e=c06c7bd6&h=585d9e53&f=y&p=y> | Facebook<https://urlsand.esvalabs.com/?u=http%3A%2F%2Fwww.facebook.com%2FPaylessPromotions&e=c06c7bd6&h=71a569aa&f=y&p=y>

**Comment by sezio** [comment]
@ankursharma1930 thanks for your answer! 
In fact I'm already on 2.3.0 and I was forced to migrate from 2.2.5 because of an other feature which was broken and the fix never came out.
That's why I'm looking for a real fix to apply, I don't want to make an other migration as I'm not sure if it's fixed on more recent releases... 
I think I'll have to take a look to the differences between 2.2.9 and 2.3.0 and see if I find something....

**Comment by simonworkhouse** [comment]
This is still an issue in 2.3.4

**Comment by prabhakaran777** [comment]
> This is still an issue in 2.3.4

yes me also facing

**Comment by prabhakaran777** [comment]
i fixed with those plugins 

Magento 2.3.4 (tested)

i knew this is not right way  but for now it will work (We will check when new version released) 

your custom module 

Custom/Module/etc/graphql/di.xml

 ```
 <!-- this plugin fix_if_stock_is_one_error_qty_is_not_available custom options -->
    <type name="Magento\Quote\Model\Quote\Item">
        <plugin name="fix_if_stock_is_one_error_qty_is_not_available" type="Custom\Module\Plugin\Quote\ExtendedItem" disabled="false" sortOrder="10"/>
    </type>


    <!-- this plugin fix_if_stock_is_one_error_qty_is_not_available -->
    <type name="Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList">
        <plugin name="fix_if_stock_is_one_error_qty_is_not_available_quote_item" type="Custom\Module\Plugin\Quote\Item\QuantityValidator\QuoteItemQtyList" disabled="false" sortOrder="10"/>
    </type>
```

Custom\Module\Plugin\Quote\ExtendedItem.php

```
<?php

namespace Custom\Module\Plugin\Quote;

use Magento\Quote\Model\Quote\Item;

class ExtendedItem
{


    /**
     * @param Item $subject
     * @param  $result
     * @param $qty
     * @return mixed
     */
    public function afterAddQty(Item $subject,$result,$qty){

        if($subject->getQty()!=$qty)
        {
          $result->setQty($qty);
        }
        return $result;
    }
}
 
```


Custom\Module\Plugin\Quote\Item\QuantityValidator\QuoteItemQtyList.php

```
<?php


namespace Custom\Module\Plugin\Quote\Item\QuantityValidator;

use Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList as CoreQuoteItemQtyList;

class QuoteItemQtyList
{


    /**
     * @param CoreQuoteItemQtyList $subject
     * @param $productId
     * @param $quoteItemId
     * @param $quoteId
     * @param $itemQty
     * @return array
     */
    public function beforeGetQty(CoreQuoteItemQtyList $subject,$productId, $quoteItemId, $quoteId, $itemQty)
    {

        /**  we are using 0 because original qty was processed */
        if($itemQty!=0){
            $itemQty=0;
        }

        return [$productId, $quoteItemId, $quoteId, $itemQty];
    }
}
```

**Comment by titechnologies** [comment]
Is this issue sorted in 2.3.5 ?

**Comment by titechnologies** [comment]
> i fixed with those plugins
> 
> Magento 2.3.4 (tested)
> 
> i knew this is not right way but for now it will work (We will check when new version released)
> 
> your custom module
> 
> Custom/Module/etc/frontend/di.xml
> 
> ```
> 
>    <type name="Magento\Quote\Model\Quote\Item">
>        <plugin name="fix_if_stock_is_one_error_qty_is_not_available" type="Custom\Module\Plugin\Quote\ExtendedItem" disabled="false" sortOrder="10"/>
>    </type>
> 
> 
>    
>    <type name="Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList">
>        <plugin name="fix_if_stock_is_one_error_qty_is_not_available_quote_item" type="Custom\Module\Plugin\Quote\Item\QuantityValidator\QuoteItemQtyList" disabled="false" sortOrder="10"/>
>    </type>
> ```
> 
> Custom\Module\Plugin\Quote\ExtendedItem.php
> 
> ```
> <?php
> 
> namespace Custom\Module\Plugin\Quote;
> 
> use Magento\Quote\Model\Quote\Item;
> 
> class ExtendedItem
> {
> 
> 
>     /**
>      * @param Item $subject
>      * @param  $result
>      * @param $qty
>      * @return mixed
>      */
>     public function afterAddQty(Item $subject,$result,$qty){
> 
>         if($subject->getQty()!=$qty)
>         {
>           $result->setQty($qty);
>         }
>         return $result;
>     }
> }
>  
> ```
> 
> Custom\Module\Plugin\Quote\Item\QuantityValidator\QuoteItemQtyList.php
> 
> ```
> <?php
> 
> 
> namespace Custom\Module\Plugin\Quote\Item\QuantityValidator;
> 
> use Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList as CoreQuoteItemQtyList;
> 
> class QuoteItemQtyList
> {
> 
> 
>     /**
>      * @param CoreQuoteItemQtyList $subject
>      * @param $productId
>      * @param $quoteItemId
>      * @param $quoteId
>      * @param $itemQty
>      * @return array
>      */
>     public function beforeGetQty(CoreQuoteItemQtyList $subject,$productId, $quoteItemId, $quoteId, $itemQty)
>     {
> 
>         /**  we are using 0 because original qty was processed */
>         if($itemQty!=0){
>             $itemQty=0;
>         }
> 
>         return [$productId, $quoteItemId, $quoteId, $itemQty];
>     }
> }
> ```

This one worked in 2.3.5-p1

**Comment by walkwizus** [comment]
Hi, any update on this issue ?

**Comment by mattcat900** [comment]
Hi, any update on this issue ?

**Comment by tuanpt-0634** [comment]
@magento-engcom-team give me 2.4-develop instance

**Comment by alitopaloglu** [comment]
I can reproduce this on v2.4.6-p4

**Comment by engcom-Bravo** [comment]
Hi @ikrestov,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.


https://github.com/magento/magento2/assets/51680745/a4d92b59-31e5-472e-964b-ae8ce41d2a40




It is Redirected back to cart and the Product custom option was updated.

Hence We are closing this issue.


Thanks.
