### ISSUE TITLE
Unable to retrive abandoned guest email 

### ISSUE THREAD

**Issue by PetmePant** [magento/magento2#18824]
### Summary (*)

We have the following issue on sending our abandoned emails to guest customers: 

I tried to order with an unregistered account in order to test the abandoned emails if they are saved when I abandon an order and it seems that they are not saved and thus our abandoned emails cannot be send. 

Moreover, when I abandon an order with a registered account the emails are saved and succesfully retrieved.  

We are using 2.2.2 version of magento. 

### Examples (*)

Following is what I see when I try to abandon with a non registered account ( guest checkout) 
[issue](https://prnt.sc/lal0lh)

**Comment by magento-engcom-team** [comment]
Hi @PetmePant. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@PetmePant do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
