### ISSUE TITLE
'Manage shopping cart' page doesn't work when a product in the latest order no longer exists

### ISSUE THREAD

**Issue by DaimPiek** [magento/magento2#18829]
### Preconditions
1. Magento 2.2.2 EE (I suppose this issue can be reproduced in later versions as well)

### Steps to reproduce
1. Customer orders a product
2. Product is removed
3. Navigate to customer in backend and click 'Manage Shopping Cart'
4. Page doesn't load, response code 500. Following stack trace is visible in logs:

```
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function canConfigure() on null in /var/www/vendor/magento/module-advanced-checkout/Block/Adminhtml/Manage/Grid/Renderer/Product.php:31
Stack trace:
#0 /var/www/vendor/magento/module-backend/Block/Widget/Grid/Column.php(279): Magento\\AdvancedCheckout\\Block\\Adminhtml\\Manage\\Grid\\Renderer\\Product->render(Object(Magento\\Sales\\Model\\Order\\Item\\Interceptor))
#1 /var/www/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/extended.phtml(194): Magento\\Backend\\Block\\Widget\\Grid\\Column->getRowField(Object(Magento\\Sales\\Model\\Order\\Item\\Interceptor))
#2 /var/www/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vendor...')
#3 /var/www/vendor/magento/framework/View/Element/Template.php(270): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(Magento\\AdvancedCheckout\\Block\\Adminhtml\\Manage\\Accordion\\Ordered), '/var/www/vendor...', Array)
#4 /var/www/vendor/magento/framework/View/Element/Template.php(300): Ma...
', referer: http://project.local/admin/customer/index/edit/id/5263/key/9cae9740f859a348edeafaed9168a513279fb6b9eedf1b2c3bbabe907fbf6572/
```

### Expected result 
1. Page should be able to load and show the 'Last ordered items'

### Actual result
1. The stacktrace mentioned above is shown in the error logs.

### Debug
I have managed to determine the problem for this issue. In the following code snippet the non-existing products are removed from the collection's result set (\Magento\AdvancedCheckout\Block\Adminhtml\Manage\Accordion\Ordered::getItemsCollection):

```php
foreach ($collection as $item) {
    $productId = $item->getProductId();
    $product = $products->getItemById($productId);
    if ($product) {
        $item->setProduct($product);
    } else {
        $collection->removeItemByKey($item->getId());
    }
}
```

The problem occurs when before rendering the actual output of the block the clear function is called on the collection, causing the result set to be cleared: \Magento\Backend\Block\Widget\Grid\Extended::_prepareCollection.

### Fix
In order to fix this issue, I have created an override, in order to apply the product_id filter to the collection, like this:
```php
// Set products to items
$excludedProductIds = [];
foreach ($collection as $item) {
    $productId = $item->getProductId();
    $product = $products->getItemById($productId);
    if ($product) {
        $item->setProduct($product);
    } else {
        $excludedProductIds = $productIds;
    }
}

if (!empty($excludedProductIds)) {
    $collection->addAttributeToFilter('product_id', ['nin' => $excludedProductIds]);
    $collection->clear();
}
```

**Comment by magento-engcom-team** [comment]
Hi @DaimPiek. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DaimPiek do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @DaimPiek  , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
