### ISSUE TITLE
Why not using the Laravel concept in Magento?

### ISSUE THREAD

**Issue by uchsarath** [magento/magento2#1883]
why don't we use the same concept as Laravel which inspired by the Rails. Routing system in Laravel is also cool and easier to implement. Generating RESTful API is also another interesting point as most of eCommerce now are moving to Mobile App. 

Just my idea.
Thanks

**Comment by alankent** [comment]
Magento has its own framework, designed to allow extensions to be added to a site. Some of the other approaches used by other frameworks don't support this concept well.

Magento 2 comes with RESTful APIs out of the box, and its easy to define new ones. I am not sure from your comment if you are saying Magento 2 is doing a good job here, or you think something is missing. We certainly expect mobile native apps will use our RESTful APIs (or SOAP if they want to).

I would however observe that the majority of ecommerce sites these days use responsive sites. Mobile apps are reserved to those whose customer base is either large enough or significant enough to the Merchant to build and maintain a custom app.

Thanks for the feedback.

**Comment by choukalos** [comment]
Hi @uchsarath we believe that most software platforms for SMB - Enterprise are going to become a collection of micro services so business can more effectively leverage their investments for a variety of uses.  That's why you're seeing us push the service pattern ( i.e. MVC to MSVC).  

I used to do some rails development ( still hack at it every once in a while ) and admit I really like the convention style helpers that are provided.  The routes handler is totally awesome for small to medium sized web sites.  However having said that for larger code bases services save you a lot of time later and avoid some of the issues with a routes like helper if you want to make a significant change to controller/API behavior.  Also we wanted to reduce the amount of effort for our community to create business logic customizations that impact both APIs and the GUI.  So it can be as simple as doing a plugin on a service method(or methods) for a fully service layered module to change behavior.  Does that make sense - is there something we can do to make it easier?
