### ISSUE TITLE
Cant delete the sample link

### ISSUE THREAD

**Issue by Mor10Mort** [magento/magento2#18847]
### Preconditions (*)

1. Magento ver. 2.2.6
2.

### Steps to reproduce (*)

1. Created a "sample link" for a "Downloadable product"
2. I try to delete the "sample link", but upon saving, the link keeps reappearing (both in front and backend (of the product)

### Expected result (*)

1. I expected that the sample link would be deleted from backend and on product page.
2.

### Actual result (*)

1. The sample link is still there after trying to delete it.
![linkdoesntremovefrontendeither](https://user-images.githubusercontent.com/24694676/47591521-34312280-d970-11e8-900d-f60592a2d720.JPG)

![samplelinkcantbedeleted](https://user-images.githubusercontent.com/24694676/47591486-0fd54600-d970-11e8-920b-782f072b7b7a.png)

2.

### Additional information

1. Additional clarification for steps to reproduce from comment https://github.com/magento/magento2/issues/18847#issuecomment-433597822
>  Presently, I am able to reproduce this issue on magento instance and my local system as well. To reproduce this issue one more step is required which is missing in issue description.
>Here, If we directly create sample link and save than it work as expected. If we delete that sample link than it will be delete too.
>But, If we set Link and Sample and press save than it work as expected. If we delete that sample link than issue is arised.
>Third case, If we delete both the link than both get deleted. No issue arise.
>So, we have to fix for second case only.

**Comment by magento-engcom-team** [comment]
Hi @Mor10Mort. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Mor10Mort do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18847-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18847-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18847-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hiren0241** [comment]
@magento-engcom-team Presently, I am able to reproduce this issue on magento instance and my local system as well. To reproduce this issue one more step is required which is missing in issue description.

Here, If we directly create sample link and save than it work as expected. If we delete that sample link than it will be delete too.

But, If we set Link and Sample and press save than it work as expected. If we delete that sample link than issue is arised.

Third case, If we delete both the link than both get deleted. No issue arise.

So, we have to fix for second case only.

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@swnsma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96269`, `MAGETWO-96270` were created

**Comment by ansari-krish** [comment]
#19344

**Comment by ansari-krish** [comment]
#19431
