### ISSUE TITLE
"Invalid Form Key. Please refresh the page." message appears when a product is added to wishlist

### ISSUE THREAD

**Issue by paco44** [magento/magento2#18841]
### Preconditions (*)

Magento 2.3

### Steps to reproduce (*)

1.Navigate to any configurable product page on the frontend.

2.Select the options and add the product to wishlist.

### Expected result (*)

1. Product added to wishlist

### Actual result (*)

Message appears "Invalid Form Key. Please refresh the page."
![captura de pantalla 2018-10-26 a la s 13 05 06](https://user-images.githubusercontent.com/20520156/47584417-ff957a80-d91f-11e8-8b38-a10a1bb8ab68.png)

**Comment by magento-engcom-team** [comment]
Hi @paco44. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@paco44 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18841-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18841-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18841-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Shubham0492** [comment]
@magento-engcom-team yes, I am able to reproduce issue on vanilla Magento instance following steps to reproduce.
1-Add configurable product.
2-Goto product page and select option of this configurable product.
3-Click Add to wishlist.
![screencapture-ec2-34-228-235-121-compute-1-amazonaws-i-18841-2-3-develop-test-config-html-2018-10-28-01_34_33](https://user-images.githubusercontent.com/35595582/47608841-c4936400-da51-11e8-8307-8114d77edf94.png)

**Comment by Shubham0492** [comment]
Issue: Confirmed

**Comment by magento-engcom-team** [comment]
@Shubham-Webkul Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95950` were created

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18841-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18841-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18841-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@paco44 @Shubham-Webkul 
Working fine on my end. May be some browser related issue. I tried clearing browser cache it was working fine. 
Please let me know are you facing this issue on Magento's test instance only or on local setup too.
As I can check, there are alot form key issues on Magento's test instance the first time we request a setup.

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
working fine on fresh installation of Magento 2.3.*-beta.
@paco44 if you face this issue again, please reopen the issue and provide more details of your environment.

**Comment by ghost** [comment]
#SQUASHTOBERFEST

**Comment by sperl755** [comment]
was this issue fixed?  experiencing it in magento 2.3.0,

**Comment by cscd98** [comment]
@sperl755 No but it should be in 2.3.1

**Comment by bscbodyscience** [comment]
is this fixed? I am still getting the issue on 2.3.2

**Comment by NickvdMeij** [comment]
same here. magento 2.3.2

**Comment by Jeeva-Rathinam** [comment]
Getting the same error Magento 2.3.3 for both add-to-cart and customer registration.

**Comment by NickvdMeij** [comment]
@magento-engcom-team perhaps reopen this issue, since its clearly not fixed?...

**Comment by blazendic** [comment]
Same for me on 2.3.3. It happens on customer account creation. I've increased max_input_vars as some suggestions here and there but it did not help. Only once my account creation succeeded and I don't know how (from 50-100 tries). Fresh installation.
