### ISSUE TITLE
Design issue in backend align calendar icons

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#18855]
### Preconditions (*)

1. Magento Version 2.3.x
2.

### Steps to reproduce (*)

1. Go to Magento admin, Catalog -> Products, edit one of the product 
2. You are able to see the Set Product as New From calendar icons are 

### Expected result (*)

1.  Please review the attached screenshot, calendar icons should display properly align
2.

### Actual result (*)

1. Calendar icons are not aligned properly 
2
![screenshot_2](https://user-images.githubusercontent.com/43603387/47600642-6b401c00-d9e2-11e8-8768-feb92431a0fc.jpg)

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
