### ISSUE TITLE
Downloadable products - Downloadable Information - Link design issue

### ISSUE THREAD

**Issue by saphaljha** [magento/magento2#18854]
### Preconditions (*)

1. Magento 2.3-develop
2. PHP 7.1.22

### Steps to reproduce (*)

1. Create new downloadable product
2. Go to "**Downloadable Information**"  tab > Click on "**Add link**" button for **Links** and **Samples** as well, You will see the table header will be messy.

### Expected result (*)

1. 
![expected-download-products-inventory-catalog-magento-admin](https://user-images.githubusercontent.com/23274052/47600483-95440f00-d9df-11e8-9caa-409c7ea79b9b.png)

### Actual result (*)

1. 
![actual-download-products-inventory-catalog-magento-admin](https://user-images.githubusercontent.com/23274052/47600489-9ecd7700-d9df-11e8-998e-cae8eba3b56c.png)

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@saphaljha do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by okorshenko** [comment]
Hi @saphaljha. Thank you for your report. 
The issue has been fixed in magento/magento2#18856 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [7401795d5133c74d3f6273c9a3bc72b7ce2c48cf](https://github.com/magento/magento2/commit/7401795d5133c74d3f6273c9a3bc72b7ce2c48cf)
 - [cd97592752a02a6b3dcda3494f18557dcb93b6d3](https://github.com/magento/magento2/commit/cd97592752a02a6b3dcda3494f18557dcb93b6d3)

The fix will be available with the upcoming 2.3.1 release.

**Comment by vasilii-b** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b, here is your [Magento instance](http://34.228.235.121/i-18854-2-2-develop/).
Admin access: [http://34.228.235.121/i-18854-2-2-develop//admin](http://34.228.235.121/i-18854-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-backlog-nazar** [comment]
Hi @saphaljha i'm closing this issue as this was fixed in 2.3-developed and not appear in 2.2-develop.

**Comment by speedy008** [comment]
Hello 
I have started working on fixing this issue in 2.2x

**Comment by ghost** [comment]
Hi @saphaljha , thank you for you report, this issue has already fixed in 2.3-develop branch, and will be available on 2.3.1 release.
