### ISSUE TITLE
Magento backend  Notifications counter round icon small cut from right side

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#18887]
### Preconditions (*)

1.Magento 2.2

### Steps to reproduce (*)

1. Login into admin check notifications counters from the top right side.

### Expected result (*)

1. Please review screenshot http://prntscr.com/lb35lz

### Actual result (*)

1. https://prnt.sc/lb340w

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by SyntaxKay** [comment]
Hi @abrarpathan19 
I have reproduce this issue and i am working on it

**Comment by sidolov** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#19053 by @abrarpathan19 in 2.3-develop branch
Related commit(s):
 - [4a945f2807c391d6a5aca92ffb7cd4a09f9aa2f0](https://github.com/magento/magento2/commit/4a945f2807c391d6a5aca92ffb7cd4a09f9aa2f0)
 - [9e9c74c7b3b1e39112a5179da02db3948dc802c9](https://github.com/magento/magento2/commit/9e9c74c7b3b1e39112a5179da02db3948dc802c9)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#19356 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [132a754013526eaaeaad4d80270a654d594295b3](https://github.com/magento/magento2/commit/132a754013526eaaeaad4d80270a654d594295b3)
 - [91fc40c4eeafefddba2bcee6c0ae18d9fb95ea22](https://github.com/magento/magento2/commit/91fc40c4eeafefddba2bcee6c0ae18d9fb95ea22)

The fix will be available with the upcoming 2.2.8 release.
