### ISSUE TITLE
Forgot password form should not available while customer is logged in.

### ISSUE THREAD

**Issue by webkul-ratnesh** [magento/magento2#18901]
### Preconditions (*)

1. Issue is reproducible in all magento 2.2.x versions.

### Steps to reproduce (*)

1. From  customer login page, click on forgot password link.
2. After landing on forgot password page again click on customer login link.
3. Provide correct customer credentials to login for customer.

### Expected result (*)

1. When some one even intentionally hit your-magento-instance.com/customer/account/forgotpassword/ while customer is login it should redirect to customer dashboard instead of opening forgot password page.

### Actual result (*)

1. lands to customer forgot password page.

**Comment by magento-engcom-team** [comment]
Hi @webkul-ratnesh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@webkul-ratnesh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by webkul-ratnesh** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
@webkul-ratnesh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95967` were created

**Comment by agorbulin** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@agorbulin thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by sidolov** [comment]
Hi @webkul-ratnesh. Thank you for your report. 
The issue has been fixed in magento/magento2#19029 by @agorbulin in 2.3-develop branch
Related commit(s):
 - [76d478fa2c70c5c6ac07c7ef781ce46aeadffd06](https://github.com/magento/magento2/commit/76d478fa2c70c5c6ac07c7ef781ce46aeadffd06)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @webkul-ratnesh. Thank you for your report. 
The issue has been fixed in magento/magento2#19089 by @swnsma in 2.2-develop branch
Related commit(s):
 - [a651b31ec990cdd06d4a605a46a602ac1def0048](https://github.com/magento/magento2/commit/a651b31ec990cdd06d4a605a46a602ac1def0048)

The fix will be available with the upcoming 2.2.8 release.
