### ISSUE TITLE
Missing asterisk for admin required fields

### ISSUE THREAD

**Issue by dmytro-ch** [magento/magento2#18904]
There is a missing asterisk for admin required fields.
The issue has been already fixed for Magento 2.3.

### Preconditions (*)
1. Magento v.2.2.7

### Steps to reproduce (*)
1. Check the admin form with required fields. (E.g. Admin login page, admin order create page etc.)

### Expected result (*)

1. The asterisk is shown for the required foelds.
<img width="365" alt="screen shot 2018-10-28 at 12 26 13 pm" src="https://user-images.githubusercontent.com/11693779/47614897-d9064980-daaf-11e8-8a90-ed8486eb2d81.png">
<img width="822" alt="screen shot 2018-10-28 at 12 33 27 pm" src="https://user-images.githubusercontent.com/11693779/47614898-d9064980-daaf-11e8-8786-01ccf4c598de.png">

### Actual result (*)

1. The asterisk is not available for the required fields.
<img width="379" alt="screen shot 2018-10-28 at 12 47 45 pm" src="https://user-images.githubusercontent.com/11693779/47614899-ddcafd80-daaf-11e8-8118-08fdb7aa3ac6.png">
<img width="816" alt="screen shot 2018-10-28 at 12 36 07 pm" src="https://user-images.githubusercontent.com/11693779/47614900-ddcafd80-daaf-11e8-8c89-407ce8164932.png">

### Possible solution
Looks like the issue was accidentally caused by the following commit: https://github.com/magento/magento2/commit/7d4721dd38d832b072c2f77d74da3a23a53fa675

1. The same fix should be applied as for the Magento 2.3 in order to fix the issue: https://github.com/magento/magento2/commit/eb173dd1b90cf3c729ec10dd115652b56586108a
2. Also, the following temporary fix for admin login form should be reverted: https://github.com/magento/magento2/commit/af700494b83600a29d03badbef20374a81960b4a

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dmytro-ch do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18904-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18904-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18904-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18904-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18904-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18904-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@rogyar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96014` were created

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your report. 
The issue has been fixed in magento/magento2#18905 by @dmytro-ch in 2.2-develop branch
Related commit(s):
 - [38bfe669e125dd6116fa2581009796439b0ee36a](https://github.com/magento/magento2/commit/38bfe669e125dd6116fa2581009796439b0ee36a)
 - [7d2dd6519c8be94a8d0b59f834fbd2f307d22e80](https://github.com/magento/magento2/commit/7d2dd6519c8be94a8d0b59f834fbd2f307d22e80)
 - [4f07c6147ce0c52c563f9e0a983ed57335be8290](https://github.com/magento/magento2/commit/4f07c6147ce0c52c563f9e0a983ed57335be8290)

The fix will be available with the upcoming 2.2.8 release.
