### ISSUE TITLE
why Magento\Payment\Model\Info use setAdditionalInformation instead of setCustomAttribute？

### ISSUE THREAD

**Issue by LifeAsBook** [magento/magento2#1890]
What is the difference setAdditionalInformation and setCustomAttribute?
The following code and the fourth step not take a value, why
1、$payment = $this->_quote->getPayment();
2、$payment->setCustomAttribute(self::JD_ORDER_ID, $jdOrderResultArray['result']['jdOrderId']);
3、$this->quoteRepository->save($this->_quote);
 4、$payment->getCustomAttribute(self::JD_ORDER_ID);

thank you !

**Comment by dkvashninbay** [comment]
You should use AdditionalInformation field, as CustomAttribute storage is not implemented for Payment Info model.

**Comment by LifeAsBook** [comment]
@dkvashninbay  how to implemented CustomAttribute ? can you give me a some steps ? thank you！

**Comment by dkvashninbay** [comment]
What is the purpose of implementing CustomAttribute for Payment model?
Maybe it's better to use Extension Attributes? http://devdocs.magento.com/guides/v2.0/extension-dev-guide/attributes.html

**Comment by LifeAsBook** [comment]
@dkvashninbay  What is the biggest difference between  CustomAttribute   and  Extension Attributes

**Comment by alankent** [comment]
From memory (slightly risky!), extension attributes can be defined by "extensions" (or to be precise, modules that are part of an extension). So an extension developer can say "my extension needs this additional attribute". If you load the extension, the attribute will be there. Custom attributes are defined by Merchants via the Admin panel. So they are a lot more dynamic, there is no loaded configuration file, no PHP code referencing them. They are both "dynamic" ini a sense, but are created due to different reasons.

**Comment by LifeAsBook** [comment]
@alankent @dkvashninbay  thank you！
