### ISSUE TITLE
Unable to Unset Previously Set Top Desitinations

### ISSUE THREAD

**Issue by evagabond** [magento/magento2#18911]
### Preconditions (*)

1. Tested on a clean install of Magento 2.2.6
2. PHP 7.0.30

### Steps to reproduce (*)

1. Go to Stores -> Configuration -> General -> Country Options -> Top destinations
2. Select any Country and Save.
3. Now Unset the Country you selected in Step 2 and Save.

### Expected result (*)

1. Country selected in Top destination should unset.

### Actual result (*)

1.  Once a country has been selected from the Top destinations list, unable to unset it.

![gkntp](https://user-images.githubusercontent.com/25109212/47621803-3dafbb80-db25-11e8-9552-6e17bc978004.png)

**Comment by magento-engcom-team** [comment]
Hi @evagabond. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@evagabond do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by evagabond** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @evagabond. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @evagabond, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18911-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18911-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18911-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by evagabond** [comment]
@magento-engcom-team - confirming that I was able to reproduce the issue on vanilla Magento instance

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@anujwebkul Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@anujwebkul Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95982` were created

**Comment by anujwebkul** [comment]
#SQUASHTOBERFEST

**Comment by anujwebkul** [comment]
@magento-engcom-team  give me 2.2-develop instance

**Comment by anujwebkul** [comment]
@magento-engcom-team Issue has been fixed in 2.2-develop and 2.3-develop branch.

**Comment by evagabond** [comment]
@anujwebkul - Can you plz point me to the solution?

**Comment by anujwebkul** [comment]
@evagabond please check the solution which is already fixed in the develop branch of 2.2 & 2.3.
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Backend/etc/adminhtml/system.xml#L221

**Comment by shikhamis11** [comment]
since this issue seems to be fixed I am closing this
