### ISSUE TITLE
Magento catalog product page gallery hide magnifier when mouse leave.

### ISSUE THREAD

**Issue by krnshah** [magento/magento2#18919]
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Enable magnifier from app/design/frontend/YOUR_VENDOR/YoUR_THEME/etc/view.xml 
2. Go to product detail page and set mouse hover on product image.

### Expected result (*)

1. When we leave mouse hover from product image magnifier should be hide.

### Actual result (*)

1. Please review this link : https://drive.google.com/file/d/1rH7DQ0Ln_26YgIAYrAbyxBB10ZmMU_H5/view

**Comment by magento-engcom-team** [comment]
Hi @krnshah. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@krnshah do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment]
Already fixed

2.3
https://github.com/magento/magento2/pull/18702

2.2
https://github.com/magento/magento2/commit/c55480ef23b6eb9902053a59d421c29c5eeebc4f#diff-a3d63022f922ef08dd75e31dddb0025a
