### ISSUE TITLE
Asterisk sign display twice

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#18918]
### Preconditions (*)

1. Asterisk sign display twice
2. Magento 2.2.5

### Steps to reproduce (*)

1. Login into admin panel > Click on cagalog > Choose display Settings

### Expected result (*)

1. http://prntscr.com/lbpcto

### Actual result (*)

1. http://prntscr.com/lbpcl6

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @suryakant-krish thank you for you report this issue has already fixed in 2.2-develop and 2.3-develop branches.
![selection_180](https://user-images.githubusercontent.com/40756439/47702964-47214c80-dc27-11e8-9a92-cda6da619479.png)

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#18922 by @suryakant-krish in 2.2-develop branch
Related commit(s):
 - [9fbf41a5738af980a26c0bec43c8b1f4a2c60ed4](https://github.com/magento/magento2/commit/9fbf41a5738af980a26c0bec43c8b1f4a2c60ed4)
 - [fd9a4234ca7cbb5d8c00898c936686dd2deadd7a](https://github.com/magento/magento2/commit/fd9a4234ca7cbb5d8c00898c936686dd2deadd7a)
 - [7365f5f12b57883a434f33cf44d934cf4cbbc84f](https://github.com/magento/magento2/commit/7365f5f12b57883a434f33cf44d934cf4cbbc84f)
 - [c870f0d174cf391f5cad51529792e7c029b02e73](https://github.com/magento/magento2/commit/c870f0d174cf391f5cad51529792e7c029b02e73)
 - [11978455b392412ef764043fb84e00b217057f29](https://github.com/magento/magento2/commit/11978455b392412ef764043fb84e00b217057f29)
 - [c230c7e7129c4a9b9d6667cdcc2a87ac701d5fc9](https://github.com/magento/magento2/commit/c230c7e7129c4a9b9d6667cdcc2a87ac701d5fc9)

The fix will be available with the upcoming 2.2.8 release.
