### ISSUE TITLE
Add to basket issue with Varnish

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#18923]
I've discovered an issue with add to basket and Varnish. When I view a product page for the first time and add the product to the basket, this works as normal.

If I go into chrome developer tools, and delete my Magento cookies by clicking on 'clear storage', then navigate to the same product page, the add to basket no longer functions - it's not possible to add it to the basket. 

If I then view a different product, I can add that product to the basket.

### Preconditions (*)
1. Magento 2.2.6 EE
2. Varnish 5.2.1
3. PHP 7.1.23
4. Redis 4.0.11
5. MySQL 5.7.24

### Steps to reproduce (*)
1. View product page on front end of Magento
2. Add to basket. Re-directed to cart.
3. Clear your cookies.
4. Navigate back to the same product page.
5. You are no longer able to add to the basket the same product, you are just redirected to the cart.

### Expected result (*)
1. Product is added to basket and customer is re-directed.

Link is 
```<a class="action primary btn-cart" href="https://www-local2.xx.co.uk/checkout/cart/add/uenc/aHR0cHM6Ly93d3ctbG9jYWwyLnZheC5jby51ay92YXgtYmxhZGUtMi1tYXgtNDB2LWNvcmRsZXNzLXZhY3V1bS1jbGVhbmVy/product/11238/form_key/yJ7ba9Iw2yzVQeVB/" title="Add to Basket"> Add to Basket</a>```

### Actual result (*)
1. 302 re-direct to /checkout/cart/, basket is empty.
2. Nothing is added to the basket

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@craigcarnell just a quick guess - maybe it's related to `form_key` cookie? What if you remove just this one?

In such case I believe observed system behavior is correct. This is a protection mechanism against CSRF attack.

**Comment by cscd98** [comment]
@orlangur That's exactly what I think it is - however, why isn't a new form key generated?

**Comment by orlangur** [comment]
@craigcarnell oh, agree, it should happen on "9. Navigate back to the same product page."

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
@craigcarnell, please add `### Preconditions (*)` and move there
```
Magento 2.2.6 EE
Varnish 5.2.1
PHP 7.1.23
Redis 4.0.11
MySQL 5.7.24
```
from `### Steps to reproduce (*)` section

It is point "1." from [requirements](https://github.com/magento/magento2/issues/18923#issuecomment-437019105)

**Comment by TomashKhamlai** [comment]
Cannot reproduce on 2.3-develop
![cannot_reproduce](https://user-images.githubusercontent.com/11827230/48209079-f3c4a200-e37c-11e8-8517-31f4590283ee.gif)

**Comment by cscd98** [comment]
@TomashKhamlai If only 2.3 was released..

**Comment by cscd98** [comment]
I'd also should mention that when you add to the basket, you are re-directed to the basket, not to the same page.

**Comment by TomashKhamlai** [comment]
Please login as Admin and navigate to **Stores -> Settings -> Configuration -> Sales -> Checkout -> Shopping Cart** and check that option **After Adding a Product Redirect to Shopping Cart** is set to **No**.

If it is set to **Yes**, then let we do a temporary change:
Steps:
1) Navigate to **Stores -> Settings -> Configuration -> Sales -> Checkout -> Shopping Cart**
2) Flush Magento Cache
3) Restart Varnish
4) Open Guest Window or create new user in Chrome and use it for testing
5) Open the Storefront (it would be great if you could record your screen starting from this point)
6) Check if the issue has gone

If there is no issue anymore, then please update your **Preconditions** section and reopen this issue. If the issue persist then I still cannot help you.

**Comment by nicholasscottfish** [comment]
Was a solution ever found for this, it seems to be a very common error on Magento 2.2.*. Any help would be appreciated.
