### ISSUE TITLE
Magento version dev-2.3-develop Alert widget gets close when click anywhere on screen

### ISSUE THREAD

**Issue by Shubham0492** [magento/magento2#18934]
### Preconditions (*)

1.Magento version dev-2.3-develop

### Steps to reproduce (*)

1.Add product to cart
2.Click on the cart icon at right top of screen
3.Click on delete icon
4.Now click any where on screen the alert widget will close

### Expected result (*)

1. The alert widget should not close until user click cancel button

### Actual result (*)

1. Alert widget gets close when click any where on screen

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Shubham-Webkul do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18934-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18934-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18934-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@Shubham-Webkul Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by TomashKhamlai** [comment]
It is a configurable feature of the Magento UI. Closing as not a bug.
