### ISSUE TITLE
OAuth1 request is always failing with all proper creds

### ISSUE THREAD

**Issue by ichinna** [magento/magento2#18936]
## Summary
HI Team,

I was working on an integration.  So, I need to implement your Oauth1 based authentication.  But unfortunately, I am having issues with the `/oauth/token/request`.

I have tried all possible ways to figure it out, but couldn't solve the issue.  Please take a look at the bold text to see the error response.

**oauth_problem=Consumer+key+has+expired** . and its of course **401**

So, please try to help me, and I can share more if you want to discuss, and open for a screen share as well.  I really need to pull this blocker out, for my customers...

Thanks in advance! Any help would be greatly appreciated!

Best.
Chinna.

## Information on your environment
I am using Postman, and FYI I have my own integration platform works with over 200+ connectors worldwide.

## Steps to reproduce
* Just make a call to your `/oauth/token/request` 

## Expected and actual results
* I am expecting a response as described in your [docs](https://devdocs.magento.com/guides/v2.2/get-started/authentication/gs-authentication-oauth.html)

**Comment by magento-engcom-team** [comment]
Hi @ChinnaBabuSadam. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ChinnaBabuSadam do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ChinnaBabuSadam thank you for you report, i'm closing this as duplicate -> https://github.com/magento/magento2/issues/12032 and this -> https://github.com/magento/magento2/issues/13961

**Comment by ichinna** [comment]
Hi  @engcom-backlog-nazar 
Thank you!  That helped me to fix my issue...
