### ISSUE TITLE
Product added to shopping cart / comparison list message not translated by default

### ISSUE THREAD

**Issue by arnoudhgz** [magento/magento2#18931]
Currently the message that you have added something to your cart is not available in the i18n translation file. 

### Preconditions (*)
1. Magento 2.2.6
2. Non English store
3. Any environment

### Steps to reproduce (*)
1. Add product to cart
2. See "You added %1 to your <a href="%2">shopping cart</a>."
3. Add product to comparison list
4. See "You added product %1 to the <a href="%2">comparison list</a>."

### Expected result (*)
1. Strings available in app/code/Magento/Checkout/i18n/en_US.csv and app/code/Magento/Catalog/i18n/en_US.csv

### Actual result (*)
1. Strings not available in app/code/Magento/Checkout/i18n/en_US.csv and app/code/Magento/Catalog/i18n/en_US.csv

### Tech hints
1. Issue occurs since Magento 2.2.6
2. These commits changed the string used for these messages: https://github.com/magento/magento2/commit/323246531601f3537b4316eb815e47aeb4cbbe03#diff-e4942136d5aba114e8b2c0529c0a040d & https://github.com/magento/magento2/commit/edd6062d2f40056d0a0a376fd62bbe8b67a06437
3. `You added %1 to your <a href="%2">shopping cart</a>.` should be added to app/code/Magento/Checkout/i18n/en_US.csv
4. `You added product %1 to the <a href="%2">comparison list</a>.` should be added to app/code/Magento/Catalog/i18n/en_US.csv

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@arnoudhgz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
#SQUASHTOBERFEST

**Comment by ghost** [comment]
#mm18nyc

**Comment by magento-engcom-team** [comment]
@sundarcreosen thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @sundarcreosen. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sundarcreosen. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sundarcreosen, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18931-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18931-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18931-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
Hi @arnoudhgz. Thank you for your report. 
The issue has been fixed in magento/magento2#18938 by @ayazwebkul in 2.3-develop branch
Related commit(s):
 - [4c25f0e9fbac64044a4bf3cdda17362bac23ac6c](https://github.com/magento/magento2/commit/4c25f0e9fbac64044a4bf3cdda17362bac23ac6c)
 - [d64351b30bf3ab566d42a4acf312c9b1a08045da](https://github.com/magento/magento2/commit/d64351b30bf3ab566d42a4acf312c9b1a08045da)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your report. 
The issue has been fixed in magento/magento2#19461 by @JeroenVanLeusden in 2.2-develop branch
Related commit(s):
 - [3b521b0cf72426711d3cf22ed6cba139d7143101](https://github.com/magento/magento2/commit/3b521b0cf72426711d3cf22ed6cba139d7143101)

The fix will be available with the upcoming 2.2.8 release.

**Comment by apohutenumera** [comment]
Hi,
in 2.4, the message is still not translated
