### ISSUE TITLE
"Not yet calculated" for the tax in the summary section in the checkout is not translatable

### ISSUE THREAD

**Issue by rajeev-k-tomy** [magento/magento2#18939]
### Preconditions (*)

1. 2.2.3 (still present in 2.3-beta)
2. Those sites which uses more than 1 stores (languages).

### Steps to reproduce (*)

1. Setup a two-store site where the default store uses "en_Us" as the language and the second store uses "es_ES" (Spanish ).
2. Add Spanish translation for the text: "Not yet calculated" through the design section. i.e, in the file: `app/design/frontend/<Package>/<theme>/i18n/es_ES.csv`.
   
        "Not yet calculated","Aún no calculado"
2. Now on the frontend, switch to Spanish store. Then add a product to the cart and go for checkout.
3. In the payment step, under the summary section, you will see "Not yet calculated" is not translated for the **Tax** eventhough the same text corresponding to **Shipping** is translated.

### Expected result (*)

1. In the summary section in the checkout, we should see `Aún no calculado` for the **Tax** total.

### Actual result (*)

1. But what we see there is `Not yet calculated`

### Why this is happened

The issue occured because of there is no translation applied for the text: "Not yet calculated" in the UiComponent `Magento_Tax/js/view/checkout/summary/tax`.

This is how the text is called on the template. File: [`vendor/magento/module-tax/view/frontend/web/template/checkout/summary/tax.html`](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Tax/view/frontend/web/template/checkout/summary/tax.html#L31)

           
                <span class="not-calculated" data-bind="text: getValue()"></span>
            

So `getValue()` is providing the text here. So if we check in the component js file: [`vendor/magento/module-tax/view/frontend/web/js/view/checkout/summary/tax.js`](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Tax/view/frontend/web/js/view/checkout/summary/tax.js)

    return Component.extend({
        defaults: {
            ...
            notCalculatedMessage: 'Not yet calculated',
           ...
        },
        ...
        /**
         * @return {*}
         */
        getValue: function () {
            var amount;

            if (!this.isCalculated()) {
                return this.notCalculatedMessage;
            }
            amount = totals.getSegment('tax').value;

            return this.getFormattedPrice(amount);
        },
       ....

As you can see the text does not have any translations applied.

### How can fix this?

Apparently adding translation in the component will fix the issue. Example is shown:

File:  [`vendor/magento/module-tax/view/frontend/web/js/view/checkout/summary/tax.js`](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Tax/view/frontend/web/js/view/checkout/summary/tax.js)

    define([
        'ko',
        'mage/translate',
        'Magento_Checkout/js/view/summary/abstract-total',
        'Magento_Checkout/js/model/quote',
        'Magento_Checkout/js/model/totals'
    ], function (ko, $t, Component, quote, totals) {
        
        return Component.extend({
            defaults: {
                notCalculatedMessage: $t('Not yet calculated'),
            },
            ...
        });
    });

Awaiting the response. Thank you. :)

**Comment by magento-engcom-team** [comment]
Hi @progammer-rkt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@progammer-rkt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @anujwebkul. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@torhoehn Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96019`, `MAGETWO-96020` were created

**Comment by magento-engcom-team** [comment]
Hi @progammer-rkt. Thank you for your report. 
The issue has been fixed in magento/magento2#18959 by @torhoehn in 2.2-develop branch
Related commit(s):
 - [b51e3be2789eba8bb10f57c2714dffa482f3c4d8](https://github.com/magento/magento2/commit/b51e3be2789eba8bb10f57c2714dffa482f3c4d8)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @progammer-rkt. Thank you for your report. 
The issue has been fixed in magento/magento2#19174 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [0566957554fa964f79518b7b93920fe12db39c8a](https://github.com/magento/magento2/commit/0566957554fa964f79518b7b93920fe12db39c8a)

The fix will be available with the upcoming 2.3.1 release.
