### ISSUE TITLE
dev/tools/grunt/configs/themes.js gets replaced after update magento

### ISSUE THREAD

**Issue by iget-master** [magento/magento2#18949]
### Summary (*)
Magento docs suggests adding theme to `dev/tools/grunt/configs/themes.js` file in order to allow using grunt to process less, watch and more.

The problem is that this file gets replaced always that I upgarde the magento installation.

.gitignore file contains following line:

https://github.com/magento/magento2/blob/77af5d65ef4fb986e62d9d1bcc230828c7c07f1b/.gitignore#L36

Pointing that somehow this file should be used instead of modifying the main `themes.js`, but this file is not loaded anywhere, so we are required to update the gruntfile or the themes.js that will be always replaced.

### Proposed solution
Why not provide a solution out of the box by loading that `local-themes.js` file if present?

**Comment by magento-engcom-team** [comment]
Hi @iget-master. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@iget-master do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by torhoehn** [comment]
I think removing /dev/tools/grunt/configs/local-themes.js  from .gitignore should be okay.

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by iget-master** [comment]
@torhoehn Also the `local-themes.js` is not loaded on the provided .gruntfile.sample, requiring that developers understand the layout of the gruntfile instead of just running `grunt`.

**Comment by torhoehn** [comment]
@iget-master But it's in `grunt-config.json.sample` and it's part of the devdocs to copy it to `grunt-config.json`.

**Comment by magento-engcom-team** [comment]
Hi @iget-master. Thank you for your report. 
The issue has been fixed in magento/magento2#18960 by @torhoehn in 2.2-develop branch
Related commit(s):
 - [bc485de186bd2422d3f7e872dfcf81a50e7cb519](https://github.com/magento/magento2/commit/bc485de186bd2422d3f7e872dfcf81a50e7cb519)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @iget-master. Thank you for your report. 
The issue has been fixed in magento/magento2#19350 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [adb97a3efda543e0985a178b91b1fc6d9e1efa71](https://github.com/magento/magento2/commit/adb97a3efda543e0985a178b91b1fc6d9e1efa71)

The fix will be available with the upcoming 2.3.1 release.
