### ISSUE TITLE
Calling getCurrentUrl on Store will wrongly add "___store" parameter

### ISSUE THREAD

**Issue by LucaGallinari** [magento/magento2#18941]
### Summary (*)
I have the config "store code in URL" set to "yes" but when i use the method "getCurrentUrl" on a Store type variable i get the current URL but with the parameter "___store=[code]" in it, if the current store is not the one requested in the URL.
I want to use the getCurrentUrl method in order to redirect the user to the correct store based on some custom logic (like the browser language), but i don't want any additional parameters to be in the URL.
Form what i found out by looking around in the code, the parameter "___store" is mandatory when the config "use store code in URL" is set to "no" but not when it's set to "yes", as in my case. The store code is already in the URL (as set in system config) and it's not necessary to add any other parameters in the URL to remark this.

### Examples (*)

    <?php
    
    namespace Fonderia\StoreAutoRedirect\Observer;
    
    use Magento\Framework\Event\Observer;
    use Magento\Framework\Event\ObserverInterface;
    use Magento\Store\Model\Store;
    use Magento\Store\Api\StoreRepositoryInterface;
    
    class RedirectObserver implements ObserverInterface
    {
        /**
         * @var StoreRepositoryInterface
         */
        private $storeRepository;
    
        public function __construct(StoreRepositoryInterface $storeRepository) {
            $this->storeRepository = $storeRepository;
        }
    
        public function execute(Observer $observer)
        {
            $storeCode = '[your store code]';
    
            /** @var Store $store */
            $store = $this->storeRepository->get($storeCode);
            $url = $store->getCurrentUrl(true);
            // ...
        }
    }

### Proposed solution
Not a solution but this is what i found out by debugging.

[At this line of code](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Store/Model/Store.php#L1201) you can clearly see that it's applying the right logic. But if you try to debug you'll see that at this point of the code the variable $storeUrl has already the parameter "___store" set in it, because it's in [this line](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Store/Model/Store.php#L1176) that it do this. By going to the getUrl method implementation you'll found out that if the current store is not the one requested in the URL it'll add the "_scope_to_url" param at [this line](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Store/Model/Store.php#L589). This flag will eventually cause the problem because it will end up at [this line](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Store/Url/Plugin/RouteParamsResolver.php#L81) where i think the wrong logic is applied, it's the opposite as the one that i pointed out initially in this section.

**Comment by magento-engcom-team** [comment]
Hi @LucaGallinari. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LucaGallinari do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-95999`, `MAGETWO-96000` were created

**Comment by Eudemon** [comment]
#mm18nyc please give me access to the issue

**Comment by magento-engcom-team** [comment]
@Eudemon thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @Eudemon. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Thundar** [comment]
I can confirm both the issue and the analysis. The bug has been introduced in Magento 2.2.6 by this commit https://github.com/magento/magento2/commit/1115b3f6e39f9b4406ada0a6dae7ac60ea333da3#diff-4fbd3d4201dcd6192396c81a56a4a850
and was meant to solve this issue: https://github.com/magento/magento2/issues/16273

Actually I see no reason why the exclamation mark had to be removed: there is no reason why you should have the ___store parameter set when you have the "use store code in urls" set to yes.

**Comment by magento-engcom-team** [comment]
Hi @LucaGallinari. Thank you for your report. 
The issue has been fixed in magento/magento2#19135 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [0e8cd9ffc0b0ce1da6d3731fb4b21b68b40b5747](https://github.com/magento/magento2/commit/0e8cd9ffc0b0ce1da6d3731fb4b21b68b40b5747)
 - [300772deea6e9f8678dd964807dbb31d327b1ad1](https://github.com/magento/magento2/commit/300772deea6e9f8678dd964807dbb31d327b1ad1)
 - [b9a37ce922007187a16120fee813ebf387201144](https://github.com/magento/magento2/commit/b9a37ce922007187a16120fee813ebf387201144)
 - [1378074929c5ef4600e621b31bfc6df9c0da39c2](https://github.com/magento/magento2/commit/1378074929c5ef4600e621b31bfc6df9c0da39c2)
 - [70d76c75a0a2926fa7f96fab2d937c28c3996a25](https://github.com/magento/magento2/commit/70d76c75a0a2926fa7f96fab2d937c28c3996a25)
 - [2e5697dff82561d1b735c060332fd6996045b3ba](https://github.com/magento/magento2/commit/2e5697dff82561d1b735c060332fd6996045b3ba)
 - [b9f72f74197d811351949e8ec57304a3e3fab980](https://github.com/magento/magento2/commit/b9f72f74197d811351949e8ec57304a3e3fab980)
 - [22edbb904ae3856afbf871cc6e196edbd3bb679b](https://github.com/magento/magento2/commit/22edbb904ae3856afbf871cc6e196edbd3bb679b)
 - [3c869e71bc0db38a13c97d725a9e6d7363451f27](https://github.com/magento/magento2/commit/3c869e71bc0db38a13c97d725a9e6d7363451f27)
 - [f1363cf81a26cc04dc91e65e769af44eee7d23c7](https://github.com/magento/magento2/commit/f1363cf81a26cc04dc91e65e769af44eee7d23c7)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @LucaGallinari. Thank you for your report. 
The issue has been fixed in magento/magento2#19945 by @Nazar65 in 2.2-develop branch
Related commit(s):
 - [20a81dce822e49afe233d895dd87684df4133443](https://github.com/magento/magento2/commit/20a81dce822e49afe233d895dd87684df4133443)

The fix will be available with the upcoming 2.2.8 release.

**Comment by abrittis** [comment]
Will this issue be fixed in 2.1.x?  This is a pretty serious issue.
