### ISSUE TITLE
Placeholder values showing twice in dropdown in Layout/Theme option While creating Custom theme/Custom Layout

### ISSUE THREAD

**Issue by SathishDreamorbit** [magento/magento2#18948]
### Preconditions (*)

1. Magento version 2.1.X
2. MYSQL 5.6
3. PHP 7.0.32

### Steps to reproduce (*)
1. In Magento 2.1.9.  Create any custom theme/ custom layout. 
2.  Then Go to admin backend, select "Content"  -> Configuration -> Default Theme -> Applied Theme.
3. In drop down option is showing twice of " --No Theme--"

### Expected result (*)
1. Need to show the list without duplication.

### Actual result (*)

1. Placeholder/Default value showing twice.
![extra-nolayoutupdates](https://user-images.githubusercontent.com/41613424/47718020-4ca18580-dc6d-11e8-840d-a5f6f9d23b0a.png)

**Comment by magento-engcom-team** [comment]
Hi @SathishDreamorbit. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@SathishDreamorbit do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @SathishDreamorbit thank you for you report this issue has already fixed in 2.2-develop and 2.3-develop branches.
![selection_181](https://user-images.githubusercontent.com/40756439/47718521-4e5d5000-dc51-11e8-9975-121489aa8f25.png)

**Comment by SathishDreamorbit** [comment]
@engcom-backlog-nazar 

Yes, I noticed the issue is fixed in Magento 2.2 & Magento 2.3 version. Whereas no patches for Magento 2.1.X.

Could you please confirm whether any patches available for Magento 2.1.X?

**Comment by ghost** [comment]
@SathishDreamorbit seems like no, i tried to search some commits, but no found.

**Comment by SathishDreamorbit** [comment]
@engcom-backlog-nazar 

Then, how can we include the patches for Magento 2.1.9 version website. Kindly open this issue and 
 provide the patches

**Comment by SathishDreamorbit** [comment]
@engcom-backlog-nazar 

Can you re-open this issue?

**Comment by ghost** [comment]
@SathishDreamorbit No i can't, because this issue has already fixed, i'm try to find where is this has been fixed, and i will give you link to commit.

**Comment by SathishDreamorbit** [comment]
@engcom-backlog-nazar 

For your information, I do have solution for this issue. I will override the Js files and fix it. But, it is related with Magento core files issue. If the solution is provided with the patches for Magento 2.1.X version then the customer who using Magento version 2.1.X in their website could get benefit. 

For fixing the Magento issue in custom website by overriding the files. It leads memory size and performance issue. 

I hope you understand.
