### ISSUE TITLE
Unable to open URL for downloadable product in 2.2.6

### ISSUE THREAD

**Issue by supportnubix** [magento/magento2#18944]
### Preconditions (*)

1. Magento V2.2.6 Clean Install.
2. PHP 7.0.28
3. No special caching is present.

### Steps to reproduce (*)

1. Create downloadable product.
2. Add a link to this product, for example https://google.com
3. Save product.
4. Order product in front-end.
5. After order status complete navigate to your downloadable products in front-end.
6. Click the button to open the URL set in step 2 to download your product.

### Expected result (*)

1. A new page of https://google.com is opened and shown in browser.

### Actual result (*)

1. Page is not opened correctly and error by Magento is thrown:
Something went wrong while getting the requested content.

If you could give me an instance of Magento 2.2.6, I could set it up and let you check the issue.

**Comment by magento-engcom-team** [comment]
Hi @supportnubix. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@supportnubix do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by supportnubix** [comment]
The issue was reproducable on a clean 2.2.6 install.

@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @supportnubix. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @supportnubix, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18944-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18944-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18944-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96005`, `MAGETWO-96006` were created

**Comment by supportnubix** [comment]
There is no more information needed from my side?

I noticed it did work on product page sample with google.com, but other domains like https://www.nubix.nl/ etc don't work.

Thanks for looking into it.

**Comment by ghost** [comment]
@supportnubix I cheked the issue it is really not an issue because the url you have entered https://google.com is not correct actually google redirects it to https://www.google.com so the when you enter this url https://google.com or any other url which redirects to another url it gives status 301 or 302 in that case you get something went wrong error, if you will enter this url https://www.google.com you will not get any issue.

**Comment by supportnubix** [comment]
@ashutoshwebkul  You're on to something there, I'm sure they can use that info but;
The URL's didn't change, and the way this was set up worked before updating, so to my opinion it should be considered an issue nontheless.
Thanks for that info.

**Comment by denysyaroshevskyi** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@anxietyz thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @anxietyz. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-18944-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-18944-2-2-6.instances.magento-community.engineering/admin](https://i-18944-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @supportnubix. Thank you for your report. 
The issue has been fixed in magento/magento2#19996 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [76040cca09f858b264ad67b7dc4d9a498df1ac08](https://github.com/magento/magento2/commit/76040cca09f858b264ad67b7dc4d9a498df1ac08)
 - [d5b7745bbddeb94dc1e7017f1b7249c2b139bb2d](https://github.com/magento/magento2/commit/d5b7745bbddeb94dc1e7017f1b7249c2b139bb2d)
 - [32859084a65050c5397c26be5b00b158f9a0813a](https://github.com/magento/magento2/commit/32859084a65050c5397c26be5b00b158f9a0813a)
 - [116c4a7a1fa7f12598939272f80d373012c9dfa2](https://github.com/magento/magento2/commit/116c4a7a1fa7f12598939272f80d373012c9dfa2)
 - [5ecf4106c4642b7d240264846d76abdbab33437b](https://github.com/magento/magento2/commit/5ecf4106c4642b7d240264846d76abdbab33437b)
 - [01a5fce647de55f654cf75a40140ba40b2497cf4](https://github.com/magento/magento2/commit/01a5fce647de55f654cf75a40140ba40b2497cf4)
 - [f1867c9a83b4ae7b5da69c5923105a2e29334406](https://github.com/magento/magento2/commit/f1867c9a83b4ae7b5da69c5923105a2e29334406)
 - [20721002df8d8f52583874a401a06ff9b66dd1c6](https://github.com/magento/magento2/commit/20721002df8d8f52583874a401a06ff9b66dd1c6)
 - [1bb672c15cd34956342ad0e6cafd6b8452bbae76](https://github.com/magento/magento2/commit/1bb672c15cd34956342ad0e6cafd6b8452bbae76)
 - [5ba9c1b8beca3ff3d27fd76de66cd59e10cb5f1f](https://github.com/magento/magento2/commit/5ba9c1b8beca3ff3d27fd76de66cd59e10cb5f1f)
 - [420a06d92cdbe3a649d43d92ef9df18e2afc5928](https://github.com/magento/magento2/commit/420a06d92cdbe3a649d43d92ef9df18e2afc5928)
 - [c020b2c5a8326e4f5d738fe75a5f29f9b4825521](https://github.com/magento/magento2/commit/c020b2c5a8326e4f5d738fe75a5f29f9b4825521)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @supportnubix. Thank you for your report. 
The issue has been fixed in magento/magento2#21262 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [f0670b6675875620a0a92c57e96d943de3eb6e1b](https://github.com/magento/magento2/commit/f0670b6675875620a0a92c57e96d943de3eb6e1b)
 - [04f6cfedfd6ec39fcbe0d8ae8ae298c2c62f734d](https://github.com/magento/magento2/commit/04f6cfedfd6ec39fcbe0d8ae8ae298c2c62f734d)
 - [a89e6ed21e7044fa29d75866d7041af9b209fb7c](https://github.com/magento/magento2/commit/a89e6ed21e7044fa29d75866d7041af9b209fb7c)
 - [7058adb9fba8fb58c6d62ee7f4e1f27f2a7f58fc](https://github.com/magento/magento2/commit/7058adb9fba8fb58c6d62ee7f4e1f27f2a7f58fc)
 - [dac6687ed0b2eba02bd3e67913b2929afc940c9c](https://github.com/magento/magento2/commit/dac6687ed0b2eba02bd3e67913b2929afc940c9c)
 - [fc90509ec4cac3785de7f2cc537476a87e89e611](https://github.com/magento/magento2/commit/fc90509ec4cac3785de7f2cc537476a87e89e611)
 - [71a5f5d302088d638cec73dd7835358beba84f15](https://github.com/magento/magento2/commit/71a5f5d302088d638cec73dd7835358beba84f15)
 - [0fc730bb0c3545b3ff241d097efb74ad160c8e6d](https://github.com/magento/magento2/commit/0fc730bb0c3545b3ff241d097efb74ad160c8e6d)
 - [be3a5456339f66f98d2aaa42eebafbe9fcfa389f](https://github.com/magento/magento2/commit/be3a5456339f66f98d2aaa42eebafbe9fcfa389f)
 - [e5d04fa7171ad496e6d2836f56e6eff4d8a2e44d](https://github.com/magento/magento2/commit/e5d04fa7171ad496e6d2836f56e6eff4d8a2e44d)
 - [9817c50262fcdd45246bf59475795689e7cbca30](https://github.com/magento/magento2/commit/9817c50262fcdd45246bf59475795689e7cbca30)

The fix will be available with the upcoming 2.2.9 release.
