### ISSUE TITLE
The "dev/debug/debug_logging" path does not exist

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#18969]
### Preconditions (*)
Magento 2.2.6 (Developer mode)

### Steps to reproduce (*)
We want to turn production mode on for our Magento install, but it returns "The "dev/debug/debug_logging" path does not exist".

```
$ php bin/magento deploy:mode:set production
Enabling maintenance mode
Disabling maintenance mode
The "dev/debug/debug_logging" path does not exist
```

```
$ php bin/magento config:set dev/debug/debug_logging 1
The "dev/debug/debug_logging" path does not exist
```

```
$ php bin/magento deploy:mode:set production --skip-compilation
The "dev/debug/debug_logging" path does not exist
```

### Expected result (*)
I expect it to go into production mode.

### Actual result (*)
It stays in developer mode and outputs "The "dev/debug/debug_logging" path does not exist".

**Comment by magento-engcom-team** [comment]
Hi @jorgb90. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jorgb90 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @jorgb90 this issue may be related to you configuration, i did  on fresh 2.2.6 install.
![selection_185](https://user-images.githubusercontent.com/40756439/47784939-e0c42900-dd0f-11e8-9f03-1eb3cd7fc9ad.png)

**Comment by jorgb90** [comment]
@engcom-backlog-nazar  If so any idea what could cause this? Database path is there in core_config_data table..

![schermafbeelding 2018-10-31 om 12 31 12](https://user-images.githubusercontent.com/7294081/47785410-f08c3f00-dd08-11e8-8f27-45570781ef0c.png)

**Comment by ghost** [comment]
@jorgb90 Try to verify the path in core_config_data, there must not be spaces

**Comment by jorgb90** [comment]
@engcom-backlog-nazar There are no spaces. Really clueless..

**Comment by ghost** [comment]
@jorgb90 hm.. this error shows only if in the core_config_data have no this path. 
![selection_187](https://user-images.githubusercontent.com/40756439/47788962-ed4e7e80-dd1b-11e8-83cd-50bdc904febb.png)

**Comment by ghost** [comment]
@jorgb90 maybe change value to 1 ? in production mode it set to 0 in developer to 1, so if you in dev. mode, you need this value set to 1.

**Comment by jorgb90** [comment]
@engcom-backlog-nazar Thanks for your help for so far, but changing the value to 1 unfortunately doesn't make a difference :( 

I do find another occurence of it in 'flag' column, but I don't think it can do harm?

![schermafbeelding 2018-10-31 om 15 43 15](https://user-images.githubusercontent.com/7294081/47795978-b714fd00-dd23-11e8-8088-9d96c67d1c3c.png)

**Comment by jorgb90** [comment]
@engcom-backlog-nazar Mm to make it even stranger when I set the value to 1 and run "php bin/magento deploy:mode:set production" it sets it to 0 :S

**Comment by jorgb90** [comment]
@engcom-backlog-nazar I want to let you know that we finally fixed this problem and I think it maybe actually is a core issue.. The fix was eventually very simple by first setting Magento into default mode (which normally isn't possible) and after that setting the mode to production is working fine..

<img width="541" alt="schermafbeelding 2018-11-07 om 16 50 50" src="https://user-images.githubusercontent.com/7294081/48142568-50f12280-e2ad-11e8-9c06-53dbe7966c58.png">

**Comment by jorgb90** [comment]
@engcom-backlog-nazar We need to do this every time when coming back from production mode.

<img width="592" alt="schermafbeelding 2018-11-15 om 11 16 00" src="https://user-images.githubusercontent.com/7294081/48546208-10566200-e8c8-11e8-8576-026f414717ed.png">

**Comment by rojin-eglobeits** [comment]
@jorgb90 We also faced this issue, Could you please check for `\Magento\Config\Model\Config\Structure` in your custom modules or extensions as a class dependency, if so then check for the usage of the class in any console command class. 
In our case, one of our extension had a dependency on the above class and the dependent class directly injected into a command class. So while running `deploy:mode: set` command Magento will create the objects of all command classes. So in our case, the above class object created before Magento Config path validator class been created with empty data from ` core_config_data `table, When Magento` \Magento\Config\Model\Config\PathValidator` validate the `"dev/debug/debug_logging"` path the object of this class``\Magento\Config\Model\Config\Structure` 
returned from Object Manager doesn't contain any data from `core_confg_data` table . In this case Magento will through the above error.

If it helps you please let me know.
