### ISSUE TITLE
Bestseller collection is empty

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#18966]
### Preconditions (*)

1. Magento 2.2.3
2. 10.1.13-MariaDB

### Steps to reproduce (*)

1. Have placed order from front end in last one month.

### Expected result (*)

1. No data in sales_bestsellers_aggregated_daily or sales_bestsellers_aggregated_monthly or sales_bestsellers_aggregated_table. 
2. Admin dashboard bestseller section is also empty

### Actual result (*)

1. Should have data in sales_bestsellers_aggregated_daily , sales_bestsellers_aggregated_monthly , sales_bestsellers_aggregated_table. 
2. Best seller collection should not be empty

**Comment by magento-engcom-team** [comment]
Hi @BabliDey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BabliDey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @BabliDey 
Sales module has a cronjob defined in magento/module-sales/etc/crontab.xml:
```
<job name="aggregate_sales_report_bestsellers_data" instance="Magento\Sales\Model\CronJob\AggregateSalesReportBestsellersData" method="execute">
        <schedule>0 0 * * *</schedule>
</job>
```
So you have to configure your Magento's cron to be running properly and bestsellers tables are going to be populated at 00:00 on your store time.

**Comment by ghost** [comment]
@BabliDey And in admin, go to reports refresh statistics and you will get data to you tables.

**Comment by BabliDey** [comment]
Hello @engcom-backlog-nazar ,
Thank you for your reply. I have run the corn run command with command line 
php bin/magento cron:run [--group="<default>"].
and then checked admin > reports > refresh statistic section. 
But still there is no data in the tables

**Comment by ghost** [comment]
@BabliDey Did you do the refresh statistics ? not check
![selection_186](https://user-images.githubusercontent.com/40756439/47787428-8d55d900-dd17-11e8-88d5-f1614d85f530.png)
.

**Comment by BabliDey** [comment]
Hello @engcom-backlog-nazar ,
Yes i have refreshed after selecting all of them in the list for last day and even with lifetime data

**Comment by BabliDey** [comment]
Hello @engcom-backlog-nazar , 
After refreshing it 2 to 3 times now there is data in the tables. Thank you.
