### ISSUE TITLE
2.3-beta32: DB credentials are not updated in non-interactive mode by bin/magento setup:config:set 

### ISSUE THREAD

**Issue by aheadWorks** [magento/magento2#18965]
### Preconditions (*)

1. Magento 2.3 beta32
2. PHP 7.2

### Steps to reproduce (*)

1. Try to update db settings with CLI in non-interactive mode(-n flag):  
`bin/magento setup:config:set -n --db-host=$MYSQL_HOST --db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER --db-password=$MYSQL_PASSWORD`

### Expected result (*)

1. DB credentials are updated at app/etc/env.php

### Actual result (*)

1. DB credentials are not updated, no errors displayed. In interactive mode everything works as expected

**Comment by magento-engcom-team** [comment]
Hi @aheadWorks. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@aheadWorks do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by aheadWorks** [comment]
@magento-engcom-team  yes

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96028` were created

**Comment by sidolov** [comment]
Hi @aheadWorks. Thank you for your report. 
The issue has been fixed in magento/magento2#18970 by @aheadWorks in 2.3-develop branch
Related commit(s):
 - [3bfe826e29ea0d1a16416aa8c6bc164c562fb643](https://github.com/magento/magento2/commit/3bfe826e29ea0d1a16416aa8c6bc164c562fb643)

The fix will be available with the upcoming 2.3.1 release.

**Comment by ghost** [comment]
Closing this issue as this was fixed on 2.3-develop branch and will be available with the upcoming 2.3.1 release.
