### ISSUE TITLE
Magento 2.3 Beta version : Elastic search V 6.0 issue

### ISSUE THREAD

**Issue by tejasvyas1988** [magento/magento2#18974]
### Preconditions (*)
1.Magento 2.3 beta version
2.Elastic Search 6.4

### Steps to reproduce (*)
1.Install the Elastic Version 6.4
2.Select the option Elastic Search 5+ from admin Configuration
3. Perform Magento reindexing

### Expected result (*)

1. Getting the below error message in elastic Search log:
Enabling [_all] is disabled in 6.0. As a replacement, you can use [copy_to] on mapping fields to create your own catch-all field.

### Actual result (*)

1. It should be compatible with the latest Elastic Search version and should not show this message.

**Comment by magento-engcom-team** [comment]
Hi @tejasvyas1988. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tejasvyas1988 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by geerlingguy** [comment]
Note that in 2.2 (also tested in 2.3), it seems that connections to Elasticsearch silently fail when you click the 'Test Connection' button in the Store Configuration - Catalog Search admin section, and there's no indication that only 2.x and 5.x are officially supported either in any error messages (none are logged) or in the UI.

Just noting here that Elasticsearch 2.x was EOL almost a year ago (Feb 2018) and Elasticsearch 5.x will be EOL in March 2019 (when 7.0.0 is released); see: https://www.elastic.co/support/eol

It would be nice if Magento's ES support could be a little more lively, as I still feel the sting of running the unsupported Apache Solr 3.6.2 version for many many years for Magento 1.x sites :/

**Comment by pmclain** [comment]
ElasticSearch docs regarding changes to the `_all` meta field in v6 for reference https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.0.html#_the_literal__all_literal_meta_field_is_now_disabled_by_default

**Comment by tejasvyas1988** [comment]
> ElasticSearch docs regarding changes to the `_all` meta field in v6 for reference https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.0.html#_the_literal__all_literal_meta_field_is_now_disabled_by_default

I was checking in this file vendor\magento\module-elasticsearch\Elasticsearch5\Model\Client\Elasticsearch.php and find the below code in addFieldsMapping function:
                  '_all' => $this->prepareFieldInfo([
                        'enabled' => true,
                        'type' => 'text',
                    ]),
Should it be there as it is depricated in 5+?

**Comment by tejasvyas1988** [comment]
any updates on the previous question?  @magento-engcom-team

**Comment by slavvka** [comment]
Guys, Magento 2.3 is currently supporting Elasticsearch 5.2.x and Elasticsearch 2.x so it isn't an issue.
Look here https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by geerlingguy** [comment]
@slavvka - So... is there any plan to support a version of Elasticsearch which will not be deprecated/unsupported within the next 4 months?

**Comment by CajuCLC** [comment]
@slavvka So Magento 2.3 will be released with support to deprecated tools?

**Comment by misha-kotov** [comment]
Agreed it would be nice to keep up a bit better with ElasticSearch release cadence. This is something we are looking to improve. Remember that as of this spring, we had support for only Elastic 2.x (not that this is a good thing). As an FYI, support for 5.x was contributed by the community, so that is also an option. At the end of the day, this is currently a feature request and not a bug.

**Comment by geerlingguy** [comment]
Moving conversation here, which is a feature request: https://github.com/magento/magento2/issues/21277 (since this was closed).

Also, is MySQL search being deprecated? If so, it might be good to get Magento working with a more modern version of Elasticsearch...
