### ISSUE TITLE
2.2.6 CE Updating product quantity via REST API does not clean product cache

### ISSUE THREAD

**Issue by AndrewPenry** [magento/magento2#18999]
### Preconditions
1. Magneto 2.2.6 with Sample Data in production mode
2. PHP 7.0

### Steps to reproduce
1. View the product page for Chaz Kangeroo Hoodie (/chaz-kangeroo-hoodie.html)
2. Update the stock for Chaz Kangeroo Hoodie-XS-Orange via the REST API, setting it to 0:

   PUT http://example.com/rest/V1/products/MH01-XS-Orange/stockItems/54

~~~JSON
{
  "stockItem":
  {
    "item_id": 54,
    "product_id": 54,
    "stock_id": 1,
    "qty": 0,
    "is_in_stock": false,
    "is_qty_decimal": false,
    "show_default_notification_message": false,
    "use_config_min_qty": true,
    "min_qty": 0,
    "use_config_min_sale_qty": 1,
    "min_sale_qty": 1,
    "use_config_max_sale_qty": true,
    "max_sale_qty": 10000,
    "use_config_backorders": true,
    "backorders": 0,
    "use_config_notify_stock_qty": true,
    "notify_stock_qty": 1,
    "use_config_qty_increments": true,
    "qty_increments": 0,
    "use_config_enable_qty_inc": true,
    "enable_qty_increments": false,
    "use_config_manage_stock": true,
    "manage_stock": true,
    "low_stock_date": null,
    "is_decimal_divided": false,
    "stock_status_changed_auto": 1
  }
}
~~~

3. Refresh the product page for Chaz Kangeroo Hoodie (/chaz-kangeroo-hoodie.html)

### Expected result
1. The swatch for the out-of-stock simple product (Chaz Kangeroo Hoodie-XS-Orange) should immediately be non-selectable.

### Actual result
1. The swatch remains selectable until the cache is manually flushed.

It does not appear that changing the inventory from 0 to !=0 via the WebAPI clears the cache like it does when you save the product from the admin. A similar issue also occurs when the quantity of the last child of a configurable product is set to 0 via REST API. Both the child and parent change to out-of-stock, but the configurable product remains on catalog listing pages until the cache is manually flushed.

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@AndrewPenry do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by AndrewPenry** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AndrewPenry** [comment]
> @AndrewPenry do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [X]  yes
> * [ ]  no

 It's easier to start with the sample data, but I don't think the Assisant will let me. So here are instructions starting from vanilla without sample data:

### Steps to reproduce from vanilla
1. Create a new product (TEST) with 2 configurations (RED and BLUE). Give both of these simple products a positivew quantity.
2. View the product page for the new product.
3. Update the stock for one of the simple products via the REST API, setting it to 0:

   PUT /rest/V1/products/TEST-RED/stockItems/1

~~~JSON
{
  "stockItem":
  {
    "item_id": 1,
    "product_id": 1,
    "stock_id": 1,
    "qty": 0,
    "is_in_stock": false,
    "is_qty_decimal": false,
    "show_default_notification_message": false,
    "use_config_min_qty": true,
    "min_qty": 0,
    "use_config_min_sale_qty": 1,
    "min_sale_qty": 1,
    "use_config_max_sale_qty": true,
    "max_sale_qty": 10000,
    "use_config_backorders": true,
    "backorders": 0,
    "use_config_notify_stock_qty": true,
    "notify_stock_qty": 1,
    "use_config_qty_increments": true,
    "qty_increments": 0,
    "use_config_enable_qty_inc": true,
    "enable_qty_increments": false,
    "use_config_manage_stock": true,
    "manage_stock": true,
    "low_stock_date": null,
    "is_decimal_divided": false,
    "stock_status_changed_auto": 1
  }
}
~~~

3. Refresh the product page.

### Expected result
1. The option for the out-of-stock simple product (TEST-RED) should immediately be non-selectable.

### Actual result
1. The option remains selectable until the cache is manually flushed.

**Comment by AndrewPenry** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AndrewPenry** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18999-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AndrewPenry** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, here is your [Magento instance](http://34.228.235.121/i-18999-2-2-5/).
Admin access: [http://34.228.235.121/i-18999-2-2-5//admin](http://34.228.235.121/i-18999-2-2-5//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @AndrewPenry thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/19043, the same logic affected,
