### ISSUE TITLE
overwrite  for 'MAGE DIRS'

### ISSUE THREAD

**Issue by Nazar65** [magento/magento2#19013]
In the pub/index.php file MAGE_DIRS coming from $_SERVER are completely overwritten. This prevent someone to set a different directory (for example a different cache directory) when using the pub directory as document root.

### Preconditions (*)
1. Add a simple PHP script named test.php with the following content to the Magento's root directory:
```
`
<?php
use Magento\Framework\App\Bootstrap;
use Magento\Framework\App\Filesystem\DirectoryList;

$_SERVER[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS] = [
 DirectoryList::CACHE => [DirectoryList::PATH => 'var/cache2']
];

```
2. Add it to the Composer's autoloader:

```
 "autoload": {
        // ...
        "files": [
            "test.php"
            // ...
        ],
        // ...
    },
```

### Steps to reproduce (*)
1. Change document root to pub
2. Do the composer update
3. Go to storefront and do some actions

### Expected result (*)
In var/   have no other folders like cache2

### Actual result (*)
In var we have folder with cache-> cache2

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Nazar65 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Nazar65** [comment]
#mageconf
