### ISSUE TITLE
Newsletter - multistore bugs

### ISSUE THREAD

**Issue by novikor** [magento/magento2#19019]
### Preconditions

1. Magento ver. 2.2.7-dev
2. PHP 7.0.32
3. Ver 15.1 Distrib 10.1.34-MariaDB

#### Magento configuration
1. 2 stores: let's call them` first` and `second`
2. Bo -> Stores -> Configuration -> Customer Configuration -> Share Customer Accounts is set to 'Global'
### Short description
When customer creates an account with existing subscriptions, rows in `newsletter_subcsriber` table are not updated (customer_id remains 0 as for guest user);

If customer has an account and creates newsletter subscription on any store, wrong store_id is saved (Id of store where customer account is created from)

### Steps to reproduce 
**There are 2 bugs described (instead of, traditionally, 1), but they are related to the same problem and should be fixed together.**

#### Case 1
1. Go to `first` store and create newsletter subscription.
2. Go to `second` store, create newsletter subscription and create an account (for the same email)

#### Expected result 
1. There a 2 rows in `newsletter_subcsriber` table, both has correct `customer_id` value

#### Actual result 
1. `customer_id` is set for `second` store only, subscription created on `first` has `customer_id` = 0
![image](https://user-images.githubusercontent.com/26086561/47913453-d5563680-dea4-11e8-8ad0-80d489b3c3b6.png)

#### Case 2
1. Create an account on `first` store;
2. Create an email subscription on both stores

#### Expected result 
1. There are 2 rows in `newsletter_subcsriber` table with the same `customer_id` and different `store_id`

#### Actual result 
1. There are 2 rows in `newsletter_subcsriber` with the same `store_id` for the same customer
![image](https://user-images.githubusercontent.com/26086561/47913856-3df1e300-dea6-11e8-8418-abbccf1c8823.png)

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@novikor do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by novikor** [comment]
Well, this issue requires about 15 hours of development (incl. Integration and unit tests), - newsletter functionality should be totally remade.

Or, we also can remove multistore from Newsletter.

At the moment, I have not enough time to finish this issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @novikor. Thank you for your report. This issue is a duplicate https://github.com/magento/magento2/issues/19172
