### ISSUE TITLE
sales_order_item_save_commit_after and sales_order_save_commit_after events will never fire for guest checkout

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#19034]
### Preconditions

1.Magento version: 2.2.6
2. PHP 7.1.x
3. Completely clean install with no demo data

### Steps to reproduce
1. Create new observers for events **sales_order_item_save_commit_after** and **sales_order_save_commit_after**.
2. Complete checkout as guest user.

### Expected result

1. Events have fired.
2. Observers have processed events.

### Actual result 

1. Events have not fired.

### Additional information
For guest checkout there are two additional transactions open in 'GuestPaymentInformationManagement'. 
![image](https://user-images.githubusercontent.com/9420807/47922693-55d66080-dec0-11e8-8170-465324e01d32.png)
These transactions lead to fact that transaction level will never be set less than '2' and after commit callback will not be processed.
![image](https://user-images.githubusercontent.com/9420807/47922783-8e763a00-dec0-11e8-9fd1-50dda14c800d.png)

### Possible fix
Transactions were opened to solve issue with QTY concurrency while order is placing (concurrent order placement could lead to negative stock value). 
So, possible, issue could be fixed  by moving \Magento\CatalogInventory\Observer\SubtractQuoteInventoryObserver to Sales Order Save transaction.

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@swnsma do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by sidolov** [comment]
Hi @swnsma. Thank you for your report. 
The issue has been fixed in magento/magento2#19040 by @swnsma in 2.3-develop branch
Related commit(s):
 - [5dc7add05b66271f4ad8c8be85c20d4beb173306](https://github.com/magento/magento2/commit/5dc7add05b66271f4ad8c8be85c20d4beb173306)
 - [e19d70e3fd43184eeeb009129bf0a564fae002ea](https://github.com/magento/magento2/commit/e19d70e3fd43184eeeb009129bf0a564fae002ea)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your report. 
The issue has been fixed in magento/magento2#19036 by @swnsma in 2.2-develop branch
Related commit(s):
 - [429815bee09f999ef3e38b93a5c097363fe2cbbd](https://github.com/magento/magento2/commit/429815bee09f999ef3e38b93a5c097363fe2cbbd)

The fix will be available with the upcoming 2.2.8 release.

**Comment by navarr** [comment]
@sidolov This issue is not fixed in 2.3.1.  The issue's contents describe the same cause of #19040 but the underlying problem still exists.

**Comment by navarr** [comment]
@svitja: You committed 6fa1f22862c1620fd6235314d3792ff4ef867650 which is what resulted in this change of functionality.

Is there any reason you performed this change only for guest checkout?

**Comment by ghost** [comment]
HI @navarr I'm closing this one as this issue no longer reproducible, if you heva additional steps to reproduce this one, please describe steps to reproduce, and reopen issue, if you have another issue please open new one.

**Comment by navarr** [comment]
@engcom-backlog-nazar What steps are being used?  I ran through the outlined steps in 2.3.1 when I reopened the ticket and my observer was not called.

**Comment by ghost** [comment]
@navarr ok give me 5 minutes i'm will retest if observer not called i'm reopen. or you trying to say that this observer calls only for guest checkout ?

**Comment by navarr** [comment]
Any observer for the event `sales_order_save_commit_after` is not called during guest checkout.

The related change #19036 works around the issue as it affects the Downloadable module, but does not resolve the criteria in this ticket

**Comment by ghost** [comment]
@navarr ok i agree with you, can you open new issue so we be able to set new fix for this ? and link this issue and PR where issue comes from. thank you.

**Comment by navarr** [comment]
@engcom-backlog-nazar Understood.  Will add to my todo list and get it done a little later, thanks 👍
