### ISSUE TITLE
2.2.6 CE Buying the last of a simple product does not clean parent configurable product cache

### ISSUE THREAD

**Issue by AndrewPenry** [magento/magento2#19043]
When a user purchases the last of a simple product, even though the quantity is reduced to zero, the option is not disabled until the cache is manually flushed.

### Preconditions (*)

1. Magento 2.2.6
2. PHP 7.0
3. All default options. Manage Stock is ON.

### Steps to reproduce (*)

1. Create a new product (TEST). Give it a price and weight. Create 2 Configurable Options for color (RED and BLUE). Give them both a quantity of 1.
2. Visit the product page (test.html). Select the RED option and Add to Cart.
3. Proceed with a successful checkout.
4. Visit the product page (test.html). Attempt to select the RED option.

### Expected result (*)

1. You should not be able to select RED, because the quantity of "TEST-RED" is 0 and the status is "out-of-stock"

### Actual result (*)

1. You can select RED and click Add to Cart. When you do, you get the "You need to choose options for your item." message.
2. Manually flushing the cache (or casuing it to be flushed by saving the product) will remove the RED option.

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@AndrewPenry do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by AndrewPenry** [comment]
> Hi @AndrewPenry. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> @AndrewPenry do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes

I suspect this is related to #18999

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96150`, `MAGETWO-96151` were created

**Comment by subbu1993** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @subbu1993. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @subbu1993, here is your [Magento instance](http://34.228.235.121/i-19043-2-2-6/).
Admin access: [http://34.228.235.121/i-19043-2-2-6//admin](http://34.228.235.121/i-19043-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by chris-pook** [comment]
This is still an issue on 2.3.3.

When purchasing the last available stock of a simple product associated to a configurable product, the configurable's cache tag is not cleared. The same is true of updating the stock value via API /rest/V1/products/SKU/stockItems/ITEM_ID.

MAGETWO-96150 and MAGETWO-96151 were created for this in 2018. Please can we have an update of the status there? This is a pretty core mechanism of an eCommerce platform that's making stock control impossible using Magento.

**Comment by chris-pook** [comment]
The issue looks to be that the stock status of the simples is held in the `collections` and `block_html` caches and not re-queried when rendering the configurable's product detail page (despite the fact its FPC cache tag has been cleared). Disabling BOTH of these caches results in the stock updates working as expected.

**Comment by chris-pook** [comment]
This comes down to the `clean_cache_by_tags` event dispatched in Magento\CatalogInventory\Model\Indexer\Stock\CacheCleaner::clean() only cleaning the full page cache. There is no event observer for the `block_html` or `collections` cache to be cleaned alongside this.

**Comment by chris-pook** [comment]
Checking if this is fixed in 2.4.x

@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @chris-pook. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @chris-pook, here is your [Magento instance](https://i-19043-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-19043-2-4-develop.instances.magento-community.engineering/admin_06a3](https://i-19043-2-4-develop.instances.magento-community.engineering/admin_06a3)
Login: `349ae423` Password: `fdf1e181feac`
Instance will be terminated in up to 3 hours.

**Comment by chris-pook** [comment]
I can't replicate the issue on this 2.4-develop instance, so hopefully this is fixed upstream.

**Comment by chris-pook** [comment]
For anyone else coming across this, there is a fix as of the 2.3.4 release in the following files:

https://github.com/magento/magento2/blob/2.3.4/app/code/Magento/Indexer/etc/di.xml#L70-L72
https://github.com/magento/magento2/blob/2.3.4/app/code/Magento/Indexer/Model/Indexer/CacheCleaner.php

This new plugin causes the required cache flush of the parent configurable product when updating the stock values of the child simples. This fixes the issue of the configurable PDP not reflecting the updated stock status.

https://github.com/magento/magento2/blob/2.3.4/app/code/Magento/ConfigurableProduct/Model/Product/Type/Configurable.php

The changes here fix the issue of all out-of-stock options for a configurable products remaining visible on PDP.

Associated issues: #5948
Related PR: https://github.com/magento/magento2/pull/12936

**Comment by engcom-Golf** [comment]
Hi @AndrewPenry 
I was not able to reproduce this issue on 2.4-develop branch. Looks like it was fixed by https://github.com/magento/magento2/commit/efb7c618a35cb59b392a09572595c26d73488521
I will close this issue for now.
Thanks.

**Comment by magento-engcom-team** [comment]
Hi @AndrewPenry, @engcom-Golf. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24599` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by Tjitse-E** [comment]
@magento-engcom-team can you point me to the commit where `MC-24599` is fixed? Was this fixed by https://github.com/magento/magento2/commit/efb7c618a35cb59b392a09572595c26d73488521 as @engcom-Golf suggests?
