### ISSUE TITLE
Can't build Product EAV index

### ISSUE THREAD

**Issue by mikekenyon99** [magento/magento2#19045]
Hi,

I'm running Magento 2.2.6 and when I have 40k of products the Product EAV index builds fine.  I add another 40k and this index doesn't build.  I leave it for 24 hours and then when I come back the status is "Suspended".  How do I go about diagnosing this?  All the other indexes build <1 minute.  I have about 80 product attributes.  I have done lots of research on the internet and I can't find any tips.

Any ideas to help me diagnosis or get closer to finding out what is going on would be much appreciated. 

Thanks

Mike

**Comment by magento-engcom-team** [comment]
Hi @mikekenyon99. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mikekenyon99 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
