### ISSUE TITLE
Admin User Problems

### ISSUE THREAD

**Issue by cmcantrell** [magento/magento2#19049]
### Preconditions (*)
Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-138-generic x86_64)
PHP 7.0.32
This is Magento 2.2.6
running Smartwave Infortis theme

### Steps to reproduce (*)
Login to Magento's admin
Navigate to System > All Users > All Users > Add New User

### Expected Results:
Magento would work. The page that comes up has no data.  I see the User Menu, Back - Save User - Force Sign In... etc.

### Actual Results:
Where the form for user data is supposed to display is blank, so users cannot be edited or added.  
Additional Info:
I have manually removed generated files and recompiled, deployed numerous times.  The site originally had some permissions issues, I created a web user and resolved most of those, however, each time I compile, I find myself having to reset some of the folder permissions.
Errors:
I am seeing a few errors in the exception log while it compiles:
[2018-11-02 17:18:06] main.CRITICAL: Class Magento\Store\Model\Store\Interceptor does not exist {"exception":"[object] (ReflectionException(code: -1): Class Magento\\Store\\Model\\Store\\Interceptor does not exist at /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:19)"} []

Any idea what is going on?

**Comment by magento-engcom-team** [comment]
Hi @cmcantrell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@cmcantrell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](http://34.228.235.121/i-19049-2-2-develop/).
Admin access: [http://34.228.235.121/i-19049-2-2-develop//admin](http://34.228.235.121/i-19049-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
@cmcantrell i am not able to reproduce this issue on 2.2-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @cmcantrell  Thank you for you report, I'm not able to reproduce following steps your described.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
