### ISSUE TITLE
Can't purge Varnish 4.0.2 cache

### ISSUE THREAD

**Issue by U12358** [magento/magento2#19051]
### Preconditions (*)
Saving products doesn't clear cache, cache:clean command also doesn't clear cache 

Host provider has next configuration, which I can't change
> acl purge {
        "localhost";
        "127.0.0.1";
}

Investigation show that current Varnish configuration doesn't work with header param **Host:127.0.0.1** and requires real **Host: domain.com**.
Besides request must be sent to address **127.0.0.1:8080**.
I can't configure this situation without hardcode, plugin or override class.
For me help line 61

![screenshot from 2018-11-02 23-36-37](https://user-images.githubusercontent.com/813985/47941833-66a2c880-def8-11e8-8779-7146f138b289.png)

### Steps to reproduce (*)
1. Configure Varnish 4 with up config
2. Server backend 127.0.0.1:8080

### Expected result (*)
1. Must clear cache

### Actual result (*)
1. Doesn't clear cache

**Comment by magento-engcom-team** [comment]
Hi @SKovbel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@SKovbel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @SKovbel  this is not a bug, here -> https://devdocs.magento.com/guides/v2.0/config-guide/varnish/config-varnish-magento.html 
We recommend you open default.vcl and change the value of acl purge to the IP address of the Varnish host. (You can specify multiple hosts on separate lines or you can use CIDR notation as well.)
To export a Varnish configuration file from the Admin panel:

Click one of the export buttons to create a default.vcl you can use with Varnish.

For example, if you have Varnish 4, click Export VCL for Varnish 4
