### ISSUE TITLE
User created by admin cannot login

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#19060]
### Preconditions (*)

1. Magento 2.3 beta 32
2. PHP 7.1
3. Maria Db 11

### Steps to reproduce (*)
1. Create user at admin area (without password)
2. User try to login at frontend

### Expected result (*)
1. Succesful login or option to create password for first time user

### Actual result (*)
1. User cannot login and gets blank page
2. Server logs shows error and PLAIN USER PASSWORD that he tried to use (very wrong idea)

2018-11-04 10:35:27.611759 [NOTICE] [172.68.51.106:27986] [STDERR] PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, null given in /vendor/magento/framework/Encryption/Encryptor.php:236
Stack trace:
#0 /vendor/magento/framework/Encryption/Encryptor.php(236): explode(':', NULL, 3)
#1 /vendor/magento/framework/Encryption/Encryptor.php(205): Magento\Framework\Encryption\Encryptor->explodePasswordHash(NULL)
#2 /vendor/magento/framework/Encryption/Encryptor.php(197): Magento\Framework\Encryption\Encryptor->isValidHash('PLAIN PASSWORD HERE', NULL)
#3 /vendor/magento/module-customer/Model/Authentication.php(170): Magento\Framework\Encryption\Encryptor->validateHash('PLAIN PASSWORD HERE', NULL)
#4 /vendor/magento/module-customer/Model/AccountManagement.php(543): Magento\Customer\Model\Authentication->authenticate('2', 'PLAIN PASSWORD HERE in /vendor/magento/framework/Encryption/Encryptor.php on line 236

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tomekjordan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](http://34.228.235.121/i-19060-2-3-develop/).
Admin access: [http://34.228.235.121/i-19060-2-3-develop//admin](http://34.228.235.121/i-19060-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
@tomekjordan please confirm if you are able to reproduce this issue on the above instance.

**Comment by progreg** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @progreg, here is your [Magento instance](http://34.228.235.121/i-19060-2-3-develop/).
Admin access: [http://34.228.235.121/i-19060-2-3-develop//admin](http://34.228.235.121/i-19060-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by progreg** [comment]
@tomekjordan I confirm that issue can be reproduced on Magento 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@progreg Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@progreg Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96115` were created

**Comment by progreg** [comment]
Hi @tomekjordan. I already added PR to prevent blank page or exception if a customer has no password. But I don't sure about your expected result. From my side, I don't think that success login for a customer without password it's a good idea.

The customer always can reset his password through Forgot Your Password link. But if you have strong vision how it should be implemented please share it. Thanks

**Comment by sidolov** [comment]
Hi @tomekjordan. Thank you for your report. 
The issue has been fixed in magento/magento2#19066 by @progreg in 2.3-develop branch
Related commit(s):
 - [ed6649194f0844f8faae0ba63a5df52b3fe8d5c4](https://github.com/magento/magento2/commit/ed6649194f0844f8faae0ba63a5df52b3fe8d5c4)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for your report. 
The issue has been fixed in magento/magento2#19110 by @agorbulin in 2.2-develop branch
Related commit(s):
 - [35c234560342f1ce5e259679a983d51cec0e2858](https://github.com/magento/magento2/commit/35c234560342f1ce5e259679a983d51cec0e2858)

The fix will be available with the upcoming 2.2.8 release.
