### ISSUE TITLE
Wrong quantities of parent and child bundle products after creating invoice and (or) shipment

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#19069]
### Preconditions (*)

1. Magento CE 2.2.5

### Steps to reproduce (*)

1. Create and configure a separate bundle product, with **static* price and *separate shipping** for bundle items
1. Go to frontend and place an order with bundle product from the previous step. Please, note: quantity of thise bundle product should be > 1
1. Go to Admin panel and create a few separate invoices for bundle product (for example, a few invoices with quantity = 1 for that bundle)
1. Check 'sales*order*item' table for parent and child bundle items

### Expected result (*)

1. 'qty*invoiced' [= 'qty*ordered' field for bundle items 

### Actual result (*)

1. 'qty*invoiced' field for bundle items is much greater that 'qty*ordered'
1. See [sales*order_item.txt](https://github.com/magento/magento2/files/2549654/sales_order*item.txt)

### Additional information
It seems like 'qty*invoiced' = 'qty_invoiced' + 'qty*ordered' for all bundle items each time, when invoice for parent bundle order item is created
Also, the similar situation with 'qty*shipped' field of  parent bundle order item has been detected. After creation of 1 shimpent for all orde items, 'qty_shipped' field of  parent bundle order item equals to 1, despite of value of  'qty_ordered'  field. As a result, parent bundle order item will never reach 'Shipped' status, see ![aw*261](https://user-images.githubusercontent.com/24728606/48012987-537c3c80-e134-11e8-9a1c-42ba4e0621a3.png)
As a result of wrong values in  'qty*shipped'  and 'qty*invoiced' fields , Magento\Sales\Model\Order\Item::getStatusId() returns incorrect value of order item status

**Comment by magento-engcom-team** [comment]
Hi @avgust1111. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@avgust1111 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @avgust1111 thank you for you report, this issue has already fixed in 2.2-develop branch.
![selection_190](https://user-images.githubusercontent.com/40756439/48049276-cb834a80-e1a6-11e8-8cb3-350c2faa1e77.png)

**Comment by staradzinau** [comment]
Hi @engcom-backlog-nazar 
Please, check the specified issue for the bundle with fixed (static) price and separate shipping
![aw_262](https://user-images.githubusercontent.com/24728606/48056127-2d9d7900-e1c2-11e8-9de5-70e743d208ef.png)

The described issue has been reproduced on 2.2.6

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](http://34.228.235.121/i-19069-2-2-develop/).
Admin access: [http://34.228.235.121/i-19069-2-2-develop//admin](http://34.228.235.121/i-19069-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@avgust1111  can you recheck it on 2.2-develop instance ?  i'm tested  the bundle with fixed (static) price and separate shipping

**Comment by staradzinau** [comment]
@engcom-backlog-nazar, yes, I will check right now the issue in the instance, provided above

**Comment by staradzinau** [comment]
@engcom-backlog-nazar 
The described problem has been reproduced on the 2.2-develop instance
Order # 000000001, see screenshots:

- After order placement: ![aw_263](https://user-images.githubusercontent.com/24728606/48059190-88869e80-e1c9-11e8-94ad-bbae372984af.png)
- First invoice - please, check quantity of child and parent items: ![aw_264](https://user-images.githubusercontent.com/24728606/48059240-a3f1a980-e1c9-11e8-9e74-f5ded1b92922.png)
- After first invoice: ![aw_265](https://user-images.githubusercontent.com/24728606/48059258-b0760200-e1c9-11e8-87ec-780fba06ed4f.png)
- Second invoice: ![aw_266](https://user-images.githubusercontent.com/24728606/48059269-bbc92d80-e1c9-11e8-92bd-e33b13802af9.png)
- After second invoice, status of parent bundle order item is correct, "Invoiced": ![aw_267](https://user-images.githubusercontent.com/24728606/48059297-d3081b00-e1c9-11e8-9608-f2c29f8de493.png)
- Shipment - please, check ordered and invoiced quantitities of child items: ![aw_268](https://user-images.githubusercontent.com/24728606/48059342-f0d58000-e1c9-11e8-801b-67d2103fffe4.png)
- After shipment, instead of "Shipped" status, "Mixed" is displayed ![aw_269](https://user-images.githubusercontent.com/24728606/48059362-08146d80-e1ca-11e8-9f00-a1243d08eeab.png)

Please, reopen the issue

**Comment by ghost** [comment]
@avgust1111 thanks now clear.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96145`, `MAGETWO-96146` were created

**Comment by staradzinau** [comment]
@magento-engcom-team 
Also, please, note: the similar situation with the wrong quantities has been detected for bundle items when  **dynamic price** is set and **Ship Bundle Items** is set to **Together**. Wrong quantities were found for the invoiced quantity of parent bundle order item and for the shipped quantity of child bundle order items

**Comment by stoopman** [comment]
Can someone explain why the qty of the child items are not displayed for bundled products? Thanks!

**Comment by magento-engcom-team** [comment]
Hi @krnshah. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Kilo** [comment]
Hello @avgust1111 
Thanks for your report. I'm not able to reproduce this issue on 2.4-develop branch.
In case you still face this issue please feel free to create a new one.
![InvoiceBundleProduct](https://user-images.githubusercontent.com/60192090/114860543-ceada680-9df4-11eb-961c-569788a2fb97.gif)

**Comment by magento-engcom-team** [comment]
Hi @avgust1111. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24505` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
