### ISSUE TITLE
Magento CE 2.2.5 - Categories not updating and empty after creationg

### ISSUE THREAD

**Issue by ilgala** [magento/magento2#19067]
### Preconditions (*)
I'm Using a "Magento Certified by Bitnami" VM on the Google Cloud Platform with Magento 2.2.5 CE

### Steps to reproduce (*)
1. Create categories and subcategories from the admin panel.
1. Create product with categories and attributes from the web services.
2. Try to update or create/update a new category in order to test a new "categories fetch" from the webservices and products update.

### Expected result (*)
1. The new category correctly created/updated
2. Fetch from the the webservices successfully

### Actual result (*)
From the Admin panel
1. Nothing changes and new categories are empty.
![admin](https://user-images.githubusercontent.com/1577699/48007210-6e8c8380-e117-11e8-8b2e-6ba8c71dd107.png)

2. "Bridge webapp"  (developed using Laravel, connecting to the endpoint using Guzzle)
![webapp](https://user-images.githubusercontent.com/1577699/48007351-b6130f80-e117-11e8-8a55-155580ecb0bf.png)

### Additional infos
Any other feature in the Admin panel is correctly working. There are 2 developers working at this e-commerce atm (me and another frontend who's role is to setup the template, images and nothing else).

The "bridge web application" retrieves from the customer ERP all the product data and sync it with magento, using the magento attributes, categories and so on to match the data from the ERP. No other data entry has been made in the development endpoint, and all the "category features" were working since, as you can see, we prepared them a few weeks ago, before developing this "third party module". 

Thanks in advance for your support and I'm sorry for my bad english

**Comment by magento-engcom-team** [comment]
Hi @ilgala. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ilgala do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ilgala** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ilgala. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ilgala, here is your [Magento instance](http://34.228.235.121/i-19067-2-2-5/).
Admin access: [http://34.228.235.121/i-19067-2-2-5//admin](http://34.228.235.121/i-19067-2-2-5//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ilgala   Thank you for you report, I'm not able to reproduce following steps your described.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
