### ISSUE TITLE
Magento 2 placeholders not working

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#19070]
### Preconditions (*)

1. Magento 2.2.6
2. PHP 7.1
3. Cpanel Centos 7
4. Mysql

### Steps to reproduce (*)

1. Upload image placeholders in the backend of Magento Stores -> Settings -> Configuration - Catalog -> Catalog -> Product image holders
2. Save config
3. The image thumbnails that were uploaded are not showing in the configuration section
4. Flush cache and reindex Magento 2, cleared cache of the browser in use
5. Check the front end of the store, the result is that default placeholders still show and not the custom uploaded image placeholders
6. The uploaded image placeholders exist in location: pub/media/catalog/product/placeholder/default

Meaning they were uploaded but for some reason, they are not showing in the backend configuration section and also the store frontend.

### Expected result (*)

1. Upload image placeholders in the backend of Magento Stores -> Settings -> Configuration - Catalog -> Catalog -> Product image holders
2. Save config
3. The image thumbnails that were uploaded should be displayed in the configuration section
5. Check the front end of the store, custom uploaded placeholders show and default image placeholders have been replaced

### Actual result (*)

1. Custom uploaded placeholders thumbnails  are not showing after uploading in Magento Stores -> Settings -> Configuration - Catalog -> Catalog -> Product image holders
2. Custom uploaded placeholder images are not showing at the storefront end
3. Custom uploaded placeholders are found in the location: pub/media/catalog/product/placeholder/default

**Comment by magento-engcom-team** [comment]
Hi @GlobalOutsourcing. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@GlobalOutsourcing do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by GlobalOutsourcing** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @GlobalOutsourcing thank you for you report this issue has already fixed by this commit -> https://github.com/magento/magento2/pull/18160
