### ISSUE TITLE
Magento 225 - Google Analitycs doesn't show up

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#19076]
### Preconditions

- magento version: 2.2.5 (developer mode) with php 7.1.23 and apache 2.4.34

### Steps to reproduce

- enable google analitics from magento backend panel and insert a correct ua code (you can leave the experiment option to no)
- go to frontend, right click and select "Inspect element"

### Expected result

- I expect to see the google code between the comments "begin google analytics code" and "end google analytics code"

### Actual result

- google cannot trace the website

- on "inspect element" only the comments (begin and end google analytics code) are visible but there is no code between the comments (see screenshot 1)

![cattura1](https://user-images.githubusercontent.com/6501073/48049282-6c213c80-e19e-11e8-88d5-8bb002a353ff.JPG)

- if I select "view source code" from browser, I can see some magento code, but it's not the google code, is the magento require js code (see screenshot 2)

![cattura2](https://user-images.githubusercontent.com/6501073/48049289-70e5f080-e19e-11e8-84d5-932126f92202.JPG)

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @LouNik1984 thank you for you report this issue has alredy fixed in 2.2-develop branch. https://github.com/magento/magento2/pull/14513/files
![selection_192](https://user-images.githubusercontent.com/40756439/48049824-92e47080-e1a8-11e8-8b42-1a429d6f6918.png)

**Comment by LouNik1984** [comment]
Hi, sorry to bother again. I checked the https://github.com/magento/magento2/pull/14513/files commit and my code is already like this

**Comment by ghost** [comment]
@LouNik1984 But why you think that this is not google analytic code ? if they works perfectly?)

**Comment by LouNik1984** [comment]
But it doesn't work, that's the point. 
I cannot see the code from the inspect element and google cannot track the website. 

From the inspect element I only see the comments, there is no code between the comments:

![48049282-6c213c80-e19e-11e8-88d5-8bb002a353ff](https://user-images.githubusercontent.com/6501073/48051055-472fc800-e1a4-11e8-8106-05b331181931.JPG)

**Comment by ghost** [comment]
@LouNik1984 hmm, but i have already tested and in my google account i have in real time 1 user. maybe you have wrong account id ?

**Comment by LouNik1984** [comment]
Yes, the account is right because I can see it in google analytics. Google Tag assistant gives me a blue result instead of green (it would be red if the account were wrong, green means that everything is ok, blue means that there are problems to solve) with the alert "non standard implementation". If I try to verify the property on the google search console using the analytics code, the search console gives error because it says that it cannot find the ua code.

And again, I cannot see the code between the comments (I don't see this is intended behaviour) and at the beginning of the html document I have only 1 link to the analytics ( the script async src="//www.google-analytics.com/analytics.js") while in your screenshot you have two: mine plus another one just right above mine (the one ending with /plugins/ua/ec.js).

So something is not right: the fix you provided shows the same code I already have in my magento installation so the error must lie elsewhere

**Comment by ghost** [comment]
@LouNik1984 I'm can't find related commit, please try updates to 2.2.6

**Comment by itecedor** [comment]
@LouNik1984 did you find a solution to this problem? I had it in 2.2.6 and now in 2.3 as well
