### ISSUE TITLE
2.2.6 CE - Varnish and block with TTL could not load product

### ISSUE THREAD

**Issue by BrocksiNet** [magento/magento2#19078]
### Preconditions (*)
Magento 2.2.6 CE

### Steps to reproduce (*)
1. Setup Magento with **Varnish** and use the default vlc you can get from the backend
2. Let's say we want to set a **ttl** for these block **product.info** in a layout xml
3. Add something like this `<referenceBlock name="product.info" ttl="120"/>`

### Expected result (*)
1. You expect the part of the page to be cached for 120 seconds by varnish esi blocks
2. You change something in the backend on that product you view and that is in the part of **product.info**
3. You reload page after 120 seconds and the changes should be there

### Actual result (*)
1. You get an fatal error in core templates because the product could not be loaded

```
2018/11/06 09:29:08 [error] 4861#4861: *195 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getSku() on null in /var/www/src/vendor/magento/module-catalog/view/frontend/templates/product/view/form.phtml:19
Stack trace:
#0 /var/www/src/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 /var/www/src/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/var/www/src/...', Array)
#2 /var/www/src/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/src/...')
#3 /var/www/src/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\E" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /page_cache/block/esi/blocks/%5B%22product.info%22%5D/handles/WyJkZWZhdWx0IiwiY2F0YWxvZ19wcm9kdWN0X3ZpZXciLCJjYXRhbG9nX3Byb2R1Y3Rfdmlld190eXBlX2dyb3VwZWQiXQ%3D%3D/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.1-fpm.sock:"
```

And yes the stack trace looks like this in logs (like cut). If i do not set the ttl or set the ttl to 0 the page is working like it should. I did not dive deeper in that problem but i'm sure that some parts from magento are not loaded and because of that the product could not be loaded and then a function is called on null.

**Comment by magento-engcom-team** [comment]
Hi @bjoern-flagbit. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bjoern-flagbit do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pmclain** [comment]
This looks like a misunderstanding of how ttl and esi work.

https://github.com/magento/magento2/blob/9186f4ac77f2b68ea0faeaa1ac065dcf26877530/app/code/Magento/Catalog/Block/Product/AbstractProduct.php#L228

Works on the assumption that the product has been loaded to the registry. When viewing a product this is handled `Magento\Catalog\Controller\Product\View::_initProduct` calling `Magento\Catalog\Helper\Product::initProduct`. The `Magento\Catalog\Block\Product\View` block if tightly coupled to the controller and will cause exceptions like the one above if the product has not been preloaded to the registry.

The esi controller will only load the provided layout handles and render the requested blocks. It is the responsibility of the developer to ensure the requested blocks are capable of such rendering. For reference here is the esi controller code responsible for block rendering https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/PageCache/Controller/Block.php#L72-L97

**Comment by BrocksiNet** [comment]
Hi @pmclain thx for your feedback, this explains why the product could not be loaded. But should not work this out of the box? So i guess magento is not putting the product to the registry. So i could  add the product to the registry before the block is rendered. But i do not like this idea because registry is hard to debug. I tend to an ajax call and an own route that is not cached by varnish (so developers after me can also easy understand what is going on).
