### ISSUE TITLE
Editing an order in multi-website setup can change the product price

### ISSUE THREAD

**Issue by BlitzInternet** [magento/magento2#19075]
We have experienced a critical issue resulting in incorrect order and invoice totals. Editing an order in the backend can cause the price to switch to the default website price, but keep the currency of the original order. This results in a new, made-up product price.

I can confirm that this can be reproduced on a blank v2.2.5 installation

### Preconditions (*)

1. Mage 2.2.5
2. Default website set with base currency 1 (CHF)
3. Second website set with currency 2 (EUR)
4. Set Config - Catalog - Catalog Price Scope to Website
5. Create a product with price 7 CHF in website 1 and 9 EUR in website 2

### Steps to reproduce (*)

1. Create order in frontend (2nd website) using EUR
2. open the Edit order page in backend on this order
3. Hit "Update Items and Quantities"

### Expected result (*)

1. the product price and currency does not change
2. the totals should stay as in the original order since nothing has been changed

### Actual result (*)

1. the product price jumps from 9 EUR to 7 EUR - the price index is using the default website, but the currency stays the same
2. the grand total has changed as well

**Comment by magento-engcom-team** [comment]
Hi @BlitzInternet. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BlitzInternet do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
![currency setup 0](https://user-images.githubusercontent.com/11827230/48197899-d46b4c00-e35f-11e8-83aa-d976b95cf076.png)
![currency setup 2](https://user-images.githubusercontent.com/11827230/48197900-d46b4c00-e35f-11e8-8ce4-f69b230e3791.png)
![simple product 1](https://user-images.githubusercontent.com/11827230/48197901-d46b4c00-e35f-11e8-9162-bd344ffdf265.png)
![simple product 4](https://user-images.githubusercontent.com/11827230/48197902-d46b4c00-e35f-11e8-8ef6-5e52df4f3ba0.png)
Hello, @BlitzInternet! I'm sorry, you something missed in the bug description or it was fixed on 2.3-develop

Here is how the editing of the order process looks on 2.3-develop:
![cannot_reproduce](https://user-images.githubusercontent.com/11827230/48198060-48a5ef80-e360-11e8-81c2-399b99cdf701.gif)

**Comment by BlitzInternet** [comment]
@TomashKhamlai thanks for the response. It's good to know that it was fixed in 2.3
However, did you try to reproduce it in 2.2? We cannot simply upgrade to v2.3 in a hurry. 
If it was fixed, we need to know in which commit/file, so we can at least create a workaround for the moment until we can upgrade the system to 2.3
Also: v2.3 is not a stable release yet. How is this a solution to close?

**Comment by TomashKhamlai** [comment]
@BlitzInternet the current forkflow provided by @magento-engcom-team requires to stop reproducing procedure if it is not reproducible in 2.3-develop. I haven't tried and have no information about the fix.

Lot of functionality is backported by internal teams and by community but we cannot promise that this will be fixed. Some fixes were made in the scope of other task. You can try to add `help wanted` label, however there is a system that can automatically remove it. Some community members compete for contribution points, maybe they will be interested to help you. Or you can ask for help on [StackExchange](https://magento.stackexchange.com/)

Please address your last question to @magento-engcom-team. I believe they know the right answer. It  is not recommended for merchants with production sites to upgrade to 2.3-develop until it is not released.

**Comment by BlitzInternet** [comment]
Thanks for the info.

@magento-engcom-team In which commit was the issue described above solved? We would like to create a workaround and could backport it, if possible.
