### ISSUE TITLE
add-home-breadcrumb.js and breadcrumbs.js missing from 2.2.6

### ISSUE THREAD

**Issue by BenGlassAtlas** [magento/magento2#19081]
### Preconditions (*)
1. N/A

### Steps to reproduce (*)
1. Check `magento2/app/code/Magento/Theme/view/frontend/web/js/view/`
2. On version 2.2.4, 2.2.5 and even 2.3-develop `add-home-breadcrumb.js` and `breadcrumbs.js` exist
3. On version 2.2.6 the files do not exist

### Expected result (*)
1. Files to be there in 2.2.6

### Actual result (*)
1. Files do not exist in 2.2.6

Looking at `magento2/app/code/Magento/Theme/view/frontend/web/js/view/`:

- `2.2.4` - Latest commit 82eca18  on 21 Feb
- `2.2.5` - Latest commit 82eca18  on 21 Feb
- `2.2.6` - Latest commit e1c7b90  on 16 Feb

It seems really strange how the latest commit for 2.2.6 is behind 2.2.4 and 2.2.5. You can see this by navigating to https://github.com/magento/magento2/tree/2.2.6/app/code/Magento/Theme/view/frontend/web/js/view and changing the tag.

**Comment by magento-engcom-team** [comment]
Hi @BenSpace48. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BenSpace48 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96159` were created

**Comment by BenGlassAtlas** [comment]
Could it be that parts of 2.2.6 are behind 2.2.4? It may explain the Amazon payment module issue where the version in 2.2.6 is lower than 2.2.5. - https://github.com/magento/magento2/issues/18248

**Comment by BenGlassAtlas** [comment]
It does look like something has messed up with 2.2.6:

https://www.diffchecker.com/ui8gMY4C

![saved_diff_ui8gmy4c_-_diff_checker](https://user-images.githubusercontent.com/8895777/48075762-d3111680-e1db-11e8-8e76-84131f82659a.jpg)

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment]
@BenSpace48, please check again
[tag 2.2.5](https://github.com/magento/magento2/tree/2.2.5/app/code/Magento/Theme/view/frontend/web/js/view)
[tag 2.2.6](https://github.com/magento/magento2/tree/2.2.6/app/code/Magento/Theme/view/frontend/web/js/view)
[latest 2.2-develop](https://github.com/magento/magento2/tree/2.2-develop/app/code/Magento/Theme/view/frontend/web/js/view)

I was also confused, but check one more time.

**Comment by BenGlassAtlas** [comment]
It's all fine now and the branch is no longer visible, I suspect it was either GitHub caching or you've fixed it :D
