### ISSUE TITLE
Braintree Error Messages

### ISSUE THREAD

**Issue by gabwik** [magento/magento2#19088]
Hi,

I'm try to use Braintree on a Magento 2.2.6 multisite. Got the following error message on Magento standard checkout: Payment Credit Card (Braintree) can't be initialized. After talk to Braintree I got the following replay: Specifically, it appears that we aren't receiving a payment method nonce, which is a vital parameter as it represents the payment method that is being used for the transaction. Here's what we're seeing in the logs:

payment_method_nonce\"=>nil
Again, this validation error is being thrown because in the requests to create a transaction, a payment method nonce is not being included in the request - as you can see above, it is being passed as nil. I found several attempts to create transactions around the same time as the above, none of which contained a value for the payment method nonce. 

 

Any solution how to fix it?

**Comment by magento-engcom-team** [comment]
Hi @gabwik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gabwik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by gabwik** [comment]
Preconditions (*)
Magento V2.2.6 
Zend OPcache v7.0.27
Apache
Standard Magento one page checkout

No special caching is present.

- Steps to reproduce (*)
Enable Braintree as payment method 
Add something to cart
Go to checkout
Can't place an other with Braintree

- Expected result (*)
That you could place an order with Braintree

- Actual result (*)
You get a message: You get a message saying: Payment Credit Card (Braintree) can't be initialized

For some reason Magento sents payment_method_nonce"=>nil

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gabwik   Thank you for you report, I'm not able to reproduce following steps your described.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by gabwik** [comment]
Hi,
Try both in test and production mode?

**Comment by ghost** [comment]
Hi @gabwik yes, can you recheck it on vanilla instance ?

**Comment by atwixfirster** [comment]
Issue ties to empty Brain Tree client token in the [getClientToken](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Braintree/view/frontend/web/js/view/payment/adapter.js#L43).

To fix this problem please provide a correct `Public Key` and `Private Key` in the `Basic Braintree Settings` section.
