### ISSUE TITLE
Feature Request: Target specific module with `setup:upgrade`

### ISSUE THREAD

**Issue by tylers-username** [magento/magento2#19086]
### Description (*)

When developing a new module would be more efficient to target the module in development with `setup:upgrade` rather than having Magento process all modules.

i.e. `magento setup:upgrade Developer_Module`

### Expected behavior (*)

Upgrade module by name in order to have the Magento cli skip the processing of all other modules that do not need upgrading.

### Benefits

It would shave time off of development.

### Additional information

Nothing to add.

**Comment by magento-engcom-team** [comment]
Hi @tylerssn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tylerssn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tylers-username** [comment]
@magento-engcom-team - this is a feature request and not an issue.

**Comment by orlangur** [comment]
@tylerssn why would one keep a module requiring upgrade in code base without actually upgrading it?

**Comment by tylers-username** [comment]
The use case for me is in development of the module. While developing a module I may need to execute` setup:upgrade` multiple times as I uninstall and reinstall the module.

**Comment by orlangur** [comment]
And it will reinstall only one module, where do you observe performance degradation?

**Comment by tylers-username** [comment]
I'm proposing that rather than have the Magento cli check all modules for new versions, only check the module specified.

Using Docker on OSX (insert horror music here) this command takes a while to process before it hits the module I'm developing.

**Comment by orlangur** [comment]
> Using Docker on OSX (insert horror music here) this command takes a while to process before it hits the module I'm developing.

This is a problem of your improperly configured environment which makes Magento not really usable as a whole. With latest OSX and Docker there are a lot of tweaks arrived which made filesystem performance drastically better, another option is https://github.com/weprovide/valet-plus.

Closing as there is no real issue in described system behavior.

**Comment by magento-engcom-team** [comment]
Hi @orlangur. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.
