### ISSUE TITLE
New Link is not correctly shown as Current if contains default parts

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#19099]
### Preconditions (*)
1. Magento 2.2.6, 2.3
2.

### Steps to reproduce (*)
1. Add a new link to the customer account navigation using layouts
2. For path use the default part `index`, example: `vault/index/index/`
```xml
<block class="Magento\Framework\View\Element\Html\Link\Current" name="demo-link">
  <arguments>
          <argument name="path" xsi:type="string">vault/index/index/</argument>
          <argument name="label" xsi:type="string">Demo Link</argument>
          <argument name="sortOrder" xsi:type="number">161</argument>
   </arguments>
</block>
```
3. Open the customer dashboard
4. Go to the new added link (Demo Link)

### Expected result (*)

1. The link is marked as current
![05187bc0cb](https://user-images.githubusercontent.com/15868188/48124900-293a9400-e286-11e8-852c-0e4f67918fbc.jpg)

### Actual result (*)

1. The new added link isn't marked as current link
![1a4e46c02f](https://user-images.githubusercontent.com/15868188/48124700-a3b6e400-e285-11e8-8cff-48df550fd807.jpg)

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eduard13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by vasilii-b** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b, here is your [Magento instance](http://34.228.235.121/i-19099-2-2-develop/).
Admin access: [http://34.228.235.121/i-19099-2-2-develop//admin](http://34.228.235.121/i-19099-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.
- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@vasilii-b Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96189`, `MAGETWO-96190` were created

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#19134 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [29640f15077b1b6e75829054037b96703e5964a8](https://github.com/magento/magento2/commit/29640f15077b1b6e75829054037b96703e5964a8)
 - [fea9aafd36096a92304c8f0fc3d223637d6d665d](https://github.com/magento/magento2/commit/fea9aafd36096a92304c8f0fc3d223637d6d665d)
 - [508832b7446df1f4c434d24c479b55434eac134a](https://github.com/magento/magento2/commit/508832b7446df1f4c434d24c479b55434eac134a)
 - [769e46d47a237f1d06e53c2c52341d45cf610531](https://github.com/magento/magento2/commit/769e46d47a237f1d06e53c2c52341d45cf610531)
 - [42411759f399db628f8be42b62fba97f61a84121](https://github.com/magento/magento2/commit/42411759f399db628f8be42b62fba97f61a84121)
 - [3ee919028c0289f04236ffbfed80bdb8d4596ff1](https://github.com/magento/magento2/commit/3ee919028c0289f04236ffbfed80bdb8d4596ff1)
 - [2f8314cd04775e353c63d8b847bbf63b3db17bbd](https://github.com/magento/magento2/commit/2f8314cd04775e353c63d8b847bbf63b3db17bbd)
 - [64daebdd28bad68dd9e69b6924f3250c77eedcc6](https://github.com/magento/magento2/commit/64daebdd28bad68dd9e69b6924f3250c77eedcc6)
 - [a912d27573ac565918b6107982cce15d9f1ab4ff](https://github.com/magento/magento2/commit/a912d27573ac565918b6107982cce15d9f1ab4ff)

The fix will be available with the upcoming 2.3.1 release.

**Comment by sidolov** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#19927 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [0e027a091831828b163efb39bc1b5b4ce3468e4c](https://github.com/magento/magento2/commit/0e027a091831828b163efb39bc1b5b4ce3468e4c)
 - [1357888cb3f38f1b3589ebfbc84d93a97382d427](https://github.com/magento/magento2/commit/1357888cb3f38f1b3589ebfbc84d93a97382d427)
 - [83cbf32256b286c9a853f3f4b001361815ba6c2b](https://github.com/magento/magento2/commit/83cbf32256b286c9a853f3f4b001361815ba6c2b)
 - [02bc6fa5759ca6da18ec87ae5217a2326653ad76](https://github.com/magento/magento2/commit/02bc6fa5759ca6da18ec87ae5217a2326653ad76)
 - [cf1e877a76b6b5bb5f6802fd49bec81be70c8110](https://github.com/magento/magento2/commit/cf1e877a76b6b5bb5f6802fd49bec81be70c8110)
 - [a03c1563a0fc1ddeb50a0f5544daee29b5c5d77b](https://github.com/magento/magento2/commit/a03c1563a0fc1ddeb50a0f5544daee29b5c5d77b)

The fix will be available with the upcoming 2.2.8 release.

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.2-develop instance for you
