### ISSUE TITLE
API: salesOrderItemRepository does not include gift message

### ISSUE THREAD

**Issue by nthurston** [magento/magento2#19093]
### Preconditions (*)

1. Magento version 2.2.6
2. REST API

### Steps to reproduce (*)

1. Place order with line level gift message
2. Call GET /V1/orders/items/{id}

### Expected result (*)

1. Result should contain extension_attributes['gift_message'] element with gift message data

### Actual result (*)

1. Result does not contain gift_message element

**Comment by magento-engcom-team** [comment]
Hi @nthurston. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nthurston do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nthurston** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @nthurston. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nthurston, here is your [Magento instance](http://34.228.235.121/i-19093-2-2-6/).
Admin access: [http://34.228.235.121/i-19093-2-2-6//admin](http://34.228.235.121/i-19093-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nthurston** [comment]
Confirmed this on vanilla instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @nthurston, thank you for your report. Gift Wrapping available only on EE version. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by nthurston** [comment]
I'm not talking about gift wrap, I'm talking about gift message.

Swagger shows that the gift message should be available on the order item API, it is not.

**Comment by ghost** [comment]
@nthurston, ok  wait a second.

**Comment by nthurston** [comment]
If you're trying to say that Gift Message is not available in CE, that does not seem accurate.

CE Docs for 2.2
https://docs.magento.com/m2/2.2/ce/user_guide/sales/gift-options.html?Highlight=gift%20options

Options on a 2.2 CE instance
![image](https://user-images.githubusercontent.com/4097064/48134182-31cfa200-e267-11e8-96b5-9d7451732052.png)

The module I am referring to is Magento\module-gift-message.

It should also be noted that the Order level gift message shows up fine in the Order API.  The Item level message does not show up in the Order API or OrderItem API.  There is no way to get the item level gift message through the API as far as I can tell.

**Comment by ghost** [comment]
@nthurston sorry Now i'm clear understand, that is the gift Message module

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96184`, `MAGETWO-96185` were created

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by lfolco** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lfolco. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lfolco, here is your [Magento instance](https://i-19093-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19093-2-3-develop.instances.magento-community.engineering/admin](https://i-19093-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @nthurston. Thank you for your report. 
The issue has been fixed in magento/magento2#25946 by @lfolco in 2.4-develop branch
Related commit(s):
 - [30b5818dde145901eb0a7a0600ef65b9cd9a9cf3](https://github.com/magento/magento2/commit/30b5818dde145901eb0a7a0600ef65b9cd9a9cf3)
 - [f076e553211d4e6a4a9ffdd48b0521ab0ee3bf38](https://github.com/magento/magento2/commit/f076e553211d4e6a4a9ffdd48b0521ab0ee3bf38)

The fix will be available with the upcoming 2.4.0 release.
