### ISSUE TITLE
getFullCustomerObject doesn't return customer custom_attributes

### ISSUE THREAD

**Issue by nelero** [magento/magento2#19112]
We can't display custom_attributes from customer in email like "forgotten password" template or "reset password" or "new account" mail template.
Firstname, lastname , prefix are ok, but not custom_attributes.

### Preconditions (*)
Magento 2.2.3

### Steps to reproduce (*)
create customer custom attribute in module

```
$setup->startSetup();

        $customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);


        $customerSetup->addAttribute(\Magento\Customer\Model\Customer::ENTITY, 'my_field', [
            'type' => 'varchar',
            'label' => 'My custom Field',
            'input' => 'text',
            'source' => '',
            'required' => false,
            'visible' => true,
            'position' => 110,
            'system' => false,
            'backend' => ''
        ]);
        
        $attribute = $customerSetup->getEavConfig()->getAttribute('customer', 'my_field')
        ->addData(['used_in_forms' => [
                'adminhtml_customer',
                'adminhtml_checkout'
            ]
        ]);
        $attribute->save();
```
the field appears in backoffice it's ok.
Fill in the field in backend customer details and save. 
the field is saved and it's ok.

But impossible to add {{var customer.getCustomAttributes('my_field')}} in email template

### Expected result (*)
2. field value displayed in email template

### Actual result (*)
the variable is empty.

**Comment by magento-engcom-team** [comment]
Hi @nelero. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nelero do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96202`, `MAGETWO-96203` were created

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by orlangur** [comment]
@nelero described system behavior is correct. You should handle custom attributes loading by yourself but the recommended way is to use extension attributes instead, see https://devdocs.magento.com/guides/v2.2/extension-dev-guide/attributes.html for more details.

**Comment by magento-engcom-team** [comment]
Hi @orlangur. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@orlangur  Yes but the custom_attributes present in the variables, but if you get value like this -> 
{{var customer.custom_attributes.sample_attribute}}  you have an error
![selection_195](https://user-images.githubusercontent.com/40756439/48207454-561ba380-e379-11e8-946e-0769164ad631.png)

**Comment by ghost** [comment]
@orlangur 
![selection_196](https://user-images.githubusercontent.com/40756439/48207827-28832a00-e37a-11e8-99bd-77477449874f.png)

**Comment by nelero** [comment]
Hi,
any news about this issue ? 
How can we fix this to use custom_attributes in welcome email ?
Thanks

**Comment by nelero** [comment]
Hi, i fixed this calling 
**{{var customer.my_field}}** in the welcome mail template, where my_field is the attribute_code for the custom attribute (in the previous screenshot, it's **sample_attribute**)
And it's working
