### ISSUE TITLE
Dependency injection and optional module

### ISSUE THREAD

**Issue by yaroslav-zenin** [magento/magento2#19116]
### Summary (*)

I have a `module1` and this `module1` can use my another `module2` in case when latest present in the system. In can be installed via composer from `suggest` section. I use magento `2.3` and `2.2.6`
### Examples (*)

In `module2` I have defined logger in `module2/etc/di.xml`
```xml
<virtualType name="Module2LoggerHandlerDebug" type="Magento\Framework\Logger\Handler\Base">
    <arguments>
        <argument name="fileName" xsi:type="string">var/log/module2/debug.log</argument>
    </arguments>
</virtualType>
<virtualType name="Module2Logger" type="Magento\Framework\Logger\Monolog">
    <arguments>
        <argument name="name" xsi:type="string">module2_logger</argument>
        <argument name="handlers" xsi:type="array">
            <item name="module2_debug" xsi:type="object">Module2LoggerHandlerDebug</item>
        </argument>
    </arguments>
</virtualType>
```
now in `module1` I would like to add one additional handler to `Module2Logger`
so, I do in `module1/etc/di.xml`
```xml
<type name="Module2Logger">
    <arguments>
        <argument name="handlers" xsi:type="array">
            <item name="module1_handler" xsi:type="object">Module1LoggerHandlerDebug</item>
        </argument>
    </arguments>
</type>
```
it throw error in console even for simple command `cache:flush` in developer mode
`Source class "\Module2Logger" for "Module2Logger" generation does not exist.`
however if I add plugin 
```xml
<type name="Module2Logger">
    <arguments>
        <argument name="handlers" xsi:type="array">
            <item name="module1_handler" xsi:type="object">Module1LoggerHandlerDebug</item>
        </argument>
    </arguments>
    <plugin name="module2_plugin" type="PluginName"/>
</type>
```
it works good because `\Magento\Framework\Interception\Config\Config::_inheritInterception` does not executed if plugins exists
Questions:
- how to specify additional logger handler for `Module2Logger` (without extra module)?
- is there any case to specify sequence order for optional modules?
### Proposed solution

- In method `\Magento\Framework\Interception\Config\Config::_inheritInterception` should add condition to check if `$realType` exists and if no - then skip interception
- `<sequence><module name="Module2" optional="true" /></sequence>`

**Comment by magento-engcom-team** [comment]
Hi @yaroslav-zenin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@yaroslav-zenin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by orlangur** [comment]
>  if `$realType` exists and if no - then skip interception

This is not a reliable solution and will cause errors. Interception must work for virtual classes as well.

@yaroslav-zenin, GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @yaroslav-zenin  thank you for you report,
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
