### ISSUE TITLE
High Database Load for Sales Rule Validation

### ISSUE THREAD

**Issue by rauberdaniel** [magento/magento2#19117]
### Preconditions (*)

1. Magento 2.2.5
2. PHP 7.1 / MySQL 5.6.41

### Steps to reproduce (*)

1. Create multiple Sales Rules with multiple coupons each
2. Get a lot of customers to redeem codes

### Expected result (*)

1. High Performance, as finding sales rules is fast using indexes on Database

### Actual result (*)

1. Incredibly Low Performance, as SQL query is badly constructed so it cannot use indexes

### Description
We’re currently having about 400 sales rules (most of them are inactive or expired) as well as about 600.000 coupons. The query, that is currently being used by the sales-rule module is extremely inefficient on the database and therefore results in massive database CPU consumption when having several orders with coupons per minute. However, this query can greatly be optimized by splitting it into two queries.

The query that is generated by the `setValidationFilter` method in `magento/vendor/magento/module-sales-rule/Model/ResourceModel/Rule/Collection.php` currently looks like this:

```sql
SELECT `main_table`.*, `rule_coupons`.`code`
FROM `salesrule` AS `main_table`
INNER JOIN `salesrule_website` AS `website`
ON website.website_id IN ('1') AND main_table.rule_id = website.rule_id
INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 0
LEFT JOIN `salesrule_coupon` AS `rule_coupons` ON main_table.rule_id = rule_coupons.rule_id AND main_table.coupon_type != 1

WHERE (from_date is null or from_date <= '2018-11-01')
AND (to_date is null or to_date >= '2018-11-01')
AND (`is_active` = '1')
AND
(
    main_table.coupon_type = 1
    OR
    (
        (
            (main_table.coupon_type = 3 AND rule_coupons.type = 1)
            OR
            (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1)
            OR
            (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
        )
        AND
        rule_coupons.code = 'COUPONCODE'
        AND
        (rule_coupons.expiration_date IS NULL OR rule_coupons.expiration_date >= '2018-11-01')
    )
)
AND (`is_active` = '1') ORDER BY sort_order ASC;
```

The problematic part in this query is line 14 `main_table.coupon_type = 1 OR`. This part forces the database to filter the joined tables based on `coupon_type`. By simply removing that line, the `rule_coupons.code` can be used as an index to find exactly the one matching sales rule without having to join and filter a massive amount of rows. The line 14 is a completely separate case than the rest in that scope (line 13 to 29) and therefore should be treated separately e.g. by a second query in a `UNION` operation.

Some details using the MySQL `EXPLAIN` function:

Original Query:
![image](https://user-images.githubusercontent.com/447405/48203143-f61c0180-e366-11e8-977f-c41b8945aeab.png)

Query without line 14/15 (not added in a second query in this example, therefore ignoring sales rules without coupons):
![image](https://user-images.githubusercontent.com/447405/48203220-354a5280-e367-11e8-96ba-0c952c45c26b.png)

This is a major performance improvement especially for larger amounts of sales rules and coupons and absolutely critical.

**Comment by magento-engcom-team** [comment]
Hi @rauberdaniel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rauberdaniel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rauberdaniel** [comment]
To be a bit more precise, the alternative recommended query that has the equal result but split into two queries that are very fast because of index usage is:

```sql
SELECT `main_table`.*, `rule_coupons`.`code`
FROM `salesrule` AS `main_table`
INNER JOIN `salesrule_website` AS `website`
ON website.website_id IN ('1') AND main_table.rule_id = website.rule_id
INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 0
LEFT JOIN `salesrule_coupon` AS `rule_coupons` ON main_table.rule_id = rule_coupons.rule_id AND main_table.coupon_type != 1

WHERE (from_date is null or from_date <= '2018-11-08')
AND (to_date is null or to_date >= '2018-11-08')
AND (`is_active` = '1')
AND
   (
        (
            (main_table.coupon_type = 3 AND rule_coupons.type = 1)
            OR
            (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1)
            OR
            (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
        )
        AND
        rule_coupons.code = 'COUPONCODE'
        AND
        (rule_coupons.expiration_date IS NULL OR rule_coupons.expiration_date >= '2018-11-08')
    )
AND (`is_active` = '1')

UNION

SELECT `main_table`.*, NULL as code
FROM `salesrule` AS `main_table`
INNER JOIN `salesrule_website` AS `website`
ON website.website_id IN ('1') AND main_table.rule_id = website.rule_id
INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 0
WHERE (from_date is null or from_date <= '2018-11-08')
AND (to_date is null or to_date >= '2018-11-08')
AND (`is_active` = '1')
AND (main_table.coupon_type = 1)

ORDER BY sort_order ASC;
```

The first query will then use `rule_coupons.code` as the index to retrieve that one coupon as well as the respective sales rule, the second query has to filter the sales rules table which however is smaller than the coupon table (on any joined combination). In our case by a very big factor as one sales rule can have multiple thousands of individual coupons.

**Comment by orlangur** [comment]
@rauberdaniel great finding and analysis! Are you interested in preparing a pull request maybe?

**Comment by rauberdaniel** [comment]
@orlangur I absolutely would, however, I’m not very into Magento code (or PHP at all) and the class that defines this query as well as the abstract are pretty confusing to me.

**Comment by orlangur** [comment]
@rauberdaniel got it, no problem. Let's wait for a volunteer then.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96241`, `MAGETWO-96242` were created

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by progreg** [comment]
Hey @orlangur,

I already have some working solution, but I'm not sure about an extension point that I've used.
My solution is to clone `select` in `beforeLoad` method and filter all no needed conditions to prepare select for the union. The reason why I choose such a strategy is not crash custom conditions that can be added manually to origin `select`.

All conditions that should be deleted in cloned `select`would be marked by `/*@OPTIONAL*/` comment, for example:

```PHP
$select->where(
    '/*@OPTIONAL*/ (' . $orWhereCondition . ') AND ' . $andWhereCondition,
    null,
    Select::TYPE_CONDITION
);
```

So in result i have such `beforeLoad` method in `Magento\SalesRule\Model\ResourceModel\Rule\Collection`.

```PHP
protected function _beforeLoad()
{
    if ($this->getFlag('validation_filter')) {
        $connection = $this->getConnection();
        $noCouponWhereCondition = $connection->quoteInto(
            'main_table.coupon_type = ? ',
            \Magento\SalesRule\Model\Rule::COUPON_TYPE_NO_COUPON
        );

        $origin = $this->_select;
        $clone = clone $this->_select;
        $clone->where($noCouponWhereCondition);

        // Remove coupon join
        $fromPart = array_filter(
            $clone->getPart(Select::FROM),
            function ($item) {
                if ($item['joinType'] == 'left join' && $item['tableName'] == 'salesrule_coupon') {
                    return false;
                }
                return $item;
            }
        );
        $clone->setPart(Select::FROM, $fromPart);

        // Replace coupon code column with NULL value
        $columnsPart = array_map(
            function ($item) use ($connection) {
                if ($item[0] == 'rule_coupons' && $item[1] == 'code') {
                    $item[1] = new Zend_Db_Expr('NULL as ' . $connection->quote('code'));
                }
                return $item;
            },
            $clone->getPart(Select::COLUMNS)
        );
        $clone->setPart(Select::COLUMNS, $columnsPart);

        // Remove where conditions related to coupon_type
        $wherePart = array_filter(
            $clone->getPart(Select::WHERE),
            function ($item) {
                if (preg_match('/\*@OPTIONAL\*/', $item)) {
                    return false;
                }
                return $item;
            }
        );
        $clone->setPart(Select::WHERE, $wherePart);

        // Apply UNION
        $this->_select = $this->getConnection()->select();
        $this->_select->union([$origin, $clone]);
    }
    return parent::_beforeLoad();
}
```

This is just an idea of concrete realization, that's why I first wanna ask you what is the best solution for this issue in your opinion. Also please check maybe I miss something. 

Query Before:
```SQL
SELECT `main_table`.*, `rule_coupons`.`code`
FROM `salesrule` AS `main_table`
       INNER JOIN `salesrule_website` AS `website` ON website.website_id IN (1) AND main_table.rule_id = website.rule_id
       INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
         ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 1
       LEFT JOIN `salesrule_coupon` AS `rule_coupons`
         ON main_table.rule_id = rule_coupons.rule_id AND main_table.coupon_type != 1
WHERE (from_date is null or from_date <= '2018-11-20')
  AND (to_date is null or to_date >= '2018-11-20')
  AND (`is_active` = '1')
  AND (/*@OPTIONAL*/
          (
              (main_table.coupon_type = 3 AND rule_coupons.type = 1)
                OR
              (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1)
                OR
              (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
              )
            AND
          rule_coupons.code = 'asdasdasdasd'
            AND
          (rule_coupons.expiration_date IS NULL OR rule_coupons.expiration_date >= '2018-11-20')
          )
```

Query After:
```SQL
SELECT `main_table`.*, `rule_coupons`.`code`
FROM `salesrule` AS `main_table`
       INNER JOIN `salesrule_website` AS `website` ON website.website_id IN (1) AND main_table.rule_id = website.rule_id
       INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
         ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 1
       LEFT JOIN `salesrule_coupon` AS `rule_coupons`
         ON main_table.rule_id = rule_coupons.rule_id AND main_table.coupon_type != 1
WHERE (from_date is null or from_date <= '2018-11-20')
  AND (to_date is null or to_date >= '2018-11-20')
  AND (`is_active` = '1')
  AND (/*@OPTIONAL*/
          (
              (main_table.coupon_type = 3 AND rule_coupons.type = 1) 
                 OR
              (main_table.coupon_type = 2 AND main_table.use_auto_generation = 1 AND rule_coupons.type = 1) 
                 OR
              (main_table.coupon_type = 2 AND main_table.use_auto_generation = 0 AND rule_coupons.type = 0)
          ) 
          AND
          rule_coupons.code = 'asdasdasdasd' 
          AND
         (rule_coupons.expiration_date IS NULL OR rule_coupons.expiration_date >= '2018-11-20')
   )
UNION
SELECT `main_table`.*, NULL as 'code'
FROM `salesrule` AS `main_table`
       INNER JOIN `salesrule_website` AS `website` ON website.website_id IN (1) AND main_table.rule_id = website.rule_id
       INNER JOIN `salesrule_customer_group` AS `customer_group_ids`
         ON main_table.rule_id = customer_group_ids.rule_id AND customer_group_ids.customer_group_id = 1
WHERE (from_date is null or from_date <= '2018-11-20')
  AND (to_date is null or to_date >= '2018-11-20')
  AND (`is_active` = '1')
  AND (main_table.coupon_type = 1)
```

**Comment by progreg** [comment]
Hey @orlangur. Can you give me any feedback, is my solution may be good? Or I should add PR first?

**Comment by rauberdaniel** [comment]
@david-fuehr Thank you very much for your work on this issue!

**Comment by rauberdaniel** [comment]
@progreg Thank you for your work as well! Sorry to see you didn’t get any feedback on your work (which I’m unable to give due to little knowledge over Magento).

**Comment by progreg** [comment]
@rauberdaniel, At least I've tried) Anyway, if a solution of @david-fuehr will be better then all is good.

**Comment by david-fuehr** [comment]
@rauberdaniel @progreg Thanks for the report and your thoughts on this issue. With that, we were able to quickly solve that issue as we encountered it.
And as we have a working solution, I found a contribution appropriate ;)

**Comment by magento-engcom-team** [comment]
Hi @rauberdaniel. Thank you for your report. 
The issue has been fixed in magento/magento2#20484 by @david-fuehr in 2.3-develop branch
Related commit(s):
 - [79cefb5a1015fbfd870d3a691d3340aaf6ff451b](https://github.com/magento/magento2/commit/79cefb5a1015fbfd870d3a691d3340aaf6ff451b)
 - [41de8cbda332b839eddc754e51adb2c6ada54fcc](https://github.com/magento/magento2/commit/41de8cbda332b839eddc754e51adb2c6ada54fcc)
 - [fa7fb549db659d66b5530b2e6a32236e58b4b4a8](https://github.com/magento/magento2/commit/fa7fb549db659d66b5530b2e6a32236e58b4b4a8)
 - [18c8bb5717e32749f12dafe366d3d5e8631dafc3](https://github.com/magento/magento2/commit/18c8bb5717e32749f12dafe366d3d5e8631dafc3)
 - [0319bb001b37b42ede62091aec7ff901f027f990](https://github.com/magento/magento2/commit/0319bb001b37b42ede62091aec7ff901f027f990)
 - [83e1e8411cc777761bfed961bb5b96927fa4059c](https://github.com/magento/magento2/commit/83e1e8411cc777761bfed961bb5b96927fa4059c)
 - [24e7dd72e9a0a0c31ff753c3ac96c8eba1dc3d36](https://github.com/magento/magento2/commit/24e7dd72e9a0a0c31ff753c3ac96c8eba1dc3d36)
 - [91fecf7866b42c00c931188b06c28f1cc978960a](https://github.com/magento/magento2/commit/91fecf7866b42c00c931188b06c28f1cc978960a)
 - [5ca9dbd747683eac02c16a2e5914b4c214839fc4](https://github.com/magento/magento2/commit/5ca9dbd747683eac02c16a2e5914b4c214839fc4)
 - [11e5397f54e80945705dba0e819413ac018fa0fa](https://github.com/magento/magento2/commit/11e5397f54e80945705dba0e819413ac018fa0fa)
 - [e516ebc4dfa2e1f0236cda4ba7f322341b8d8644](https://github.com/magento/magento2/commit/e516ebc4dfa2e1f0236cda4ba7f322341b8d8644)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @rauberdaniel. Thank you for your report. 
The issue has been fixed in magento/magento2#21699 by @david-fuehr in 2.2-develop branch
Related commit(s):
 - [9a839d176f1d8d1ec46d5ce47f7a8ba6cea76067](https://github.com/magento/magento2/commit/9a839d176f1d8d1ec46d5ce47f7a8ba6cea76067)
 - [8e7ddbf4656b15fd37b1321cadabed9d9175ea6e](https://github.com/magento/magento2/commit/8e7ddbf4656b15fd37b1321cadabed9d9175ea6e)
 - [a3e87bdfbefe486eb5217b8dbdded50fffde1236](https://github.com/magento/magento2/commit/a3e87bdfbefe486eb5217b8dbdded50fffde1236)
 - [bfd1d4f7c38c0fe3c8e17449b621bbc5c996d59b](https://github.com/magento/magento2/commit/bfd1d4f7c38c0fe3c8e17449b621bbc5c996d59b)
 - [571cf9bfd6ba69ef2c8f4f7a6f1dacb17452a495](https://github.com/magento/magento2/commit/571cf9bfd6ba69ef2c8f4f7a6f1dacb17452a495)
 - [ea34b66bd90957d7495428f3adff94f83c92dbb5](https://github.com/magento/magento2/commit/ea34b66bd90957d7495428f3adff94f83c92dbb5)
 - [dbf671438ef01bf9cc8882c7a36bb28bea280434](https://github.com/magento/magento2/commit/dbf671438ef01bf9cc8882c7a36bb28bea280434)

The fix will be available with the upcoming 2.2.9 release.

**Comment by cesmendez** [comment]
Hello, I realize that this post is now closed.  But do you all know if there is a similar solution for M1 EE?

**Comment by david-fuehr** [comment]
Hello @cesmendez,

I don't believe that someone implemented this (or a similar) fix for M1. But as the code hardly changed, you could try to apply these changes: https://github.com/magento/magento2/pull/20484/files to `magento/app/code/core/Mage/SalesRule/Model/Resource/Rule/Collection.php`
