### ISSUE TITLE
Magento 2.2.6 setup:config:set will break db configuration.

### ISSUE THREAD

**Issue by zack6849** [magento/magento2#19119]
### Preconditions

1. Magento 2.2.6
2. A working configuration

### Steps to reproduce

1. Try to change your backend frontname ( I did `bin/magento setup:config:set --backend-frontname="admin"`)
2. Say yes to override the config settings, and flush cache
3. Try to run bin/magento setup:upgrade

### Expected result (*)

1. Successful upgrade

### Actual result (*)

```
[...]
Module 'Magento_Theme':
Running data recurring...
Module 'Magento_Cms':
Module 'Magento_Customer':
Module 'Magento_Indexer':
Running data recurring...MySQL adapter: Missing required configuration option 'host'
```

It seems that when you run that it re-saves the config it also adds the following lines to app/etc/env.php

<img width="970" alt="screen shot 2018-11-08 at 10 38 31 am" src="https://user-images.githubusercontent.com/1343898/48209184-809e3a00-e342-11e8-8c38-c15654b65847.png">

Now, that all looks fine, and notice that "host" is still there, under normal circumstances I'd just say it was unrelated but if I REVERT that change setup:upgrade works without issue.

**Comment by magento-engcom-team** [comment]
Hi @zack6849. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@zack6849 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by zack6849** [comment]
Engcom instances have no command line access so I can't test it with that instance, marking as yes to move the issue forward.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @zack6849 i'm not able to reproduce following steps you described, i have clean 2.2.6 installed via composer, in my case after `bin/magento setup:config:set --backend-frontname="admin")` In app/etc/env.php i have field host.

**Comment by zack6849** [comment]
@engcom-backlog-nazar maybe it's some quirk with our configuration files then, I suppose I'll close it then

**Comment by cmtickle** [comment]
I encountered the same issue in M2 2.2.6 (self-hosted). DB connection 'indexer' was created as below, resulting in the error as per original author
`
               'indexer' => [
                'active' => '1',
                'persistent' => NULL
            ]
`

**Comment by andreas-ateles** [comment]
We have same/similar issue on (deployed) Magento 2.3.3. Running `bin/magento setup:config:set --http-cache-hosts=1.2.3.4` adds the `http_cache_hosts` section to `env.php`  but also the DB `indexer` part (without a host). Which seems to break Magento cron for us (with the error: `MySQL adapter: Missing required configuration option 'host'`). Removing the `indexer` part solves the problem.
