### ISSUE TITLE
”Catalog Search indexer process unknown error” when reindexing “Search indexer” after module update

### ISSUE THREAD

**Issue by Pro100alez** [magento/magento2#19111]
I have a problem with reindexing “Search indexer” and all product pages gives me "503 Service Unavailable error". But I can enter any other places on the site. All static pages, catalogue, checkout, admin etc. This problem has appeared after module update in "Extension Manager".

### Preconditions
- Magento 2.2.5
- Stripe Metapackage version 2.0.0 (vendor: Stripeofficial)
- Current PHP Version: PHP 7.1

### Summary
1. Go to System > Web Setup Wizard
2. Click on extension manager
3. Updates available to all modules of stripeofficial/stripe-payments
4. Review updates and proceed with the update.
5. Do not change any settings after the install.
6. Run setup:upgrade and setup:di:compile and indexer:reindex

When I use `bin/magento indexer:reindex` I've got this message:
```
Catalog Search indexer process unknown error:
Notice: Undefined offset: 4 in /home/sellastu/public_html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Action/Full.php on line 384
```
When i'm done with static-content and go to site admin I saw system message "One or more indexers are invalid. Make sure your Magento cron job is running."

Now, when I open product pages I've got "503 Service Unavailable error" or "404".

In my log files I see this error:

```
[2018-11-07 17:12:09] main.ERROR: Cron Job indexer_reindex_all_invalid has an error: Notice: Undefined offset: 4 in /home/sellastu/public_html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Action/Full.php on line 384. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":121634816,"emalloc_start":115596096} [] []
```
I tried to remove all static files, restore database, which was created before module update, and still have the same problem.

### Examples (*)
You can try to open this [page](https://sellastudio.com/jenny-premium-leather-sleeper-sectional-left-hand-chase.html) or any other pages on this [site](https://sellastudio.com/).

**Comment by magento-engcom-team** [comment]
Hi @Pro100alez. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Pro100alez do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Pro100alez, thank you for you report, this problem related to your custom module, The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
