### ISSUE TITLE
Client side less compilation not working

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#19115]
### Preconditions (*)

1. Magento ver. 2.3.0-beta23
2. PHP 7.1.22

### Steps to reproduce (*)

1. Set Magento into developer mode
2. Login into Backend and navigate to Stores -> Configuration -> Advanced -> Developer -> Frontend Development Workflow
3. Set Workflow type to Client side less compilation
4. Load Storefront

### Expected result (*)

1. Theme should be rendered correctly

### Actual result (*)

1. SyntaxError: Cannot set property 'important' of undefined in styles-m.css
![screenshot 2018-11-08 at 10 24 36](https://user-images.githubusercontent.com/1945725/48189444-83982b00-e340-11e8-87c2-45e88c00f395.png)

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@torhoehn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by torhoehn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [Magento instance](http://34.228.235.121/i-19115-2-3-develop/).
Admin access: [http://34.228.235.121/i-19115-2-3-develop//admin](http://34.228.235.121/i-19115-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by torhoehn** [comment]
@magento-engcom-team Unfortunately it's working vanilla Magento instance.

**Comment by ghost** [comment]
Hi @torhoehn seem like this already fixed in 2.3-dev branch, i'm also cannot reproduce on 2.3-dev. If you like to update this please reopen the issue.

**Comment by torhoehn** [comment]
@engcom-backlog-nazar Do you know if something has changed or an idea where I have to search for that? So I would be able to apply a fix manually in our project.

**Comment by ghost** [comment]
@torhoehn Sorry i'm can't find where this was fixed, i was try search in history commits, but not found any related commits

**Comment by torhoehn** [comment]
@engcom-backlog-nazar We updated to Magento ver. 2.3.0-beta32. Now it's working again.
