### ISSUE TITLE
Declarative schema doesn't follow the setup_version indications

### ISSUE THREAD

**Issue by barbanet** [magento/magento2#19125]
### Preconditions (*)

1. Magento 2.3-beta23
2. Php 7.1
3. Mysql 5.7
4. Create a new module with only the db_schema.xml file.

### Steps to reproduce (*)

1. I've created a db_schema.xml file with a group of fields for my table.
2. I've enabled my module.
3. I've run the setup:upgrade command.
4. Everything looks fine.
5. I've changed the db_schema.xml definition and I've added a new field.
6. I didn't change the setup_version number.
7. Run the setup:upgrade command again.
8. The table was updated and the new column was added to the table.

### Expected result (*)

1. Since I can't find documentation that explains the relation between setup_version and db_schema.xml, I expect the table change if the setup_version is different.

### Actual result (*)

1. Table schema has changed and the setup version is the same.

**Comment by magento-engcom-team** [comment]
Hi @barbanet. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@barbanet do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @barbanet thank you for you report, this is expected behavior, the db_schema runs only 1 time when you install th module.

**Comment by barbanet** [comment]
Maybe I didn't explain correctly (sorry)

That's what's not happening. If you install for the first time the module and then you change the db_schemal.xml (adding a new column to the table) but you don't change the setup_version value,
and now you execute again the bin/magento setup:upgrade command and the table will change and will have the new definition/column.

Is that the expect behavior?
Can you point me in the right direction into the devdocs to understand better how this should work?

**Comment by ghost** [comment]
@barbanet Yes in 2.3-version you have only the db_chema and if you add new row it will automatically update table, i cant find official devdocs, but have found one link non official but have more information .https://magento-devdocs.github.io/devdocs-for-tests/guides/v2.3/extension-dev-guide/declarative-schema/
