### ISSUE TITLE
Product special price from field errors with UK interface locale

### ISSUE THREAD

**Issue by paul-blundell** [magento/magento2#19132]
### Preconditions (*)
Magento 2.2.6
PHP 7.0.30

### Steps to reproduce (*)
1. Edit your admin accounts interface locale to English (United Kingdom)
2. Create or edit a product
3. Click Advanced Pricing, and set a special price
4. Set the special price from date to 13/11/2018
5. Set the special price to date to 14/11/2018
6. Save the product

### Expected result (*)
The product should save with no errors.

### Actual result (*)
The following error occurs:

    DateTime::__construct(): Failed to parse time string (13/11/2018) at position 0 (1): Unexpected character

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@paul-blundell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by paul-blundell** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @paul-blundell, here is your [Magento instance](http://34.228.235.121/i-19132-2-2-6/).
Admin access: [http://34.228.235.121/i-19132-2-2-6//admin](http://34.228.235.121/i-19132-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by paul-blundell** [comment]
@magento-engcom-team I can confirm I was able to reproduce on the above instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @paul-blundell  thank you for you report, this is acknowladged issue, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/18158

**Comment by paul-blundell** [comment]
@engcom-backlog-nazar I originally commented on that issue but felt this was better on its own as its not quite the same. 

The fix for that issue does **not** fix this problem.

**Comment by ghost** [comment]
@paul-blundell ok give me 5 minutes i will check it

**Comment by paul-blundell** [comment]
@engcom-backlog-nazar Actually nevermind, on second viewing it looks like that is the same issue. Please leave this closed. Thank you.

**Comment by ghost** [comment]
@paul-blundell this issue present in 2.3-develop instance
