### ISSUE TITLE
Should magento keep using prototype.js?

### ISSUE THREAD

**Issue by vvo** [magento/magento2#1913]
Hi, I have been getting issues with magento old prototype.js library (it's 3 years old), notable the function.bind polyfill is not complete.

Two questions:
- can we upgrade prototype.js to the latest version (so that it does not overwrite function.prototype.bind
- how much work would be needed to completely get rid of prototype.js?

**Comment by guz-anton** [comment]
0. No, it should not. Magento is going to reduce use of `prototype.js`.
1. I think it doesn't make sense. Due to point 0.
2. It is not so easy to say. Main  issue is not in prototype itself, but in huge amount of code written on top of it. We are working on decreasing it. You can find that there places in _Admin area_ where instead of `prototype` classes we use [`uiComponents`](http://devdocs.magento.com/guides/v2.0/ui-library/ui-library-component.html).

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
