### ISSUE TITLE
Magento 2.2.1 Email Template issues

### ISSUE THREAD

**Issue by antheny916** [magento/magento2#19137]
**Summary-**
A couple days ago i've installed a theme to our magento 2 webstore. Everything seems to be working fine besides one thing that is bothering me! The email templates! For some reason the emails that are sent to customers are not i guess you'd say "styled" or "formatted" properly? I'm really not sure. Please look at the images to see what i'am talking about.

**Image Examples-**
Here is what's displayed when i try to preview the "new_order" template in my magento backend....

![wc email temp](https://user-images.githubusercontent.com/38775647/48280831-ac382780-e409-11e8-8eaa-9d082e029329.png)

As you can see, it's pretty much just plain text.

Well here is what it SHOULD look like (our other magento store with same theme)

![smdm temp](https://user-images.githubusercontent.com/38775647/48280929-f0c3c300-e409-11e8-89fc-a82640103f1b.png)

**Two more examples.....**

This is what the email looks like when it's sent to a customer.....just all over the place.....

![wc1](https://user-images.githubusercontent.com/38775647/48280956-00dba280-e40a-11e8-8a15-969bf69200b9.png)

Here is what it should look like.....

![smdm1](https://user-images.githubusercontent.com/38775647/48280959-033dfc80-e40a-11e8-9b88-195cde995e74.png)

Can anyone help with this? 

I'm new to Github, so i do apologize if this is posted in the wrong section. mods/ admins, feel free to move it to the correct spot if needed.

**Comment by magento-engcom-team** [comment]
Hi @antheny916. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@antheny916 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by antheny916** [comment]
@magento-engcom-team 
> Hi @antheny916. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @antheny916 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Comment by orlangur** [comment]
@antheny916,

This GitHub repository is intended for bug reports in core Magento modules, in case of problems with some third party extensions/themes their respective vendors should be contacted instead.

Are you able to reproduce this issue with default Magento theme?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @antheny916 thank you for you report, i'm not able to reproduce following steps you described, in clean magento instance, The GitHub issue tracker is intended for Magento Core technical issues only.
