### ISSUE TITLE
Home page store loge should be clickable to reload page

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#19142]
### Preconditions (*)

1. any Magento 2
2. any theme

### Steps to reproduce (*)

1. Visit Home page
2. Try to refresh page by clicking store logo
3. Nothing happens

### Expected result (*)
1. Page reload - user wants to reload quickly page. Hi thinks it can be made by clicking the logo.
 The only option to refresh is F5 (desktop only), or by refreshing browser very small icon. UX suffers on mobile/tablets. Users wants to quickly reload home page - and anyone expects it can be done by clicking store logo

### Actual result (*)
1. Nothing happens when you click logo on home page. But logo is clickable on other pages. User expects logo is clickable on all pages

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tomekjordan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by dimasalamatov** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov, here is your [Magento instance](http://34.228.235.121/i-19142-2-3-develop/).
Admin access: [http://34.228.235.121/i-19142-2-3-develop//admin](http://34.228.235.121/i-19142-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gwharton** [comment]
Are you saying clicking on the logo on any page should refresh the current page, or that it should take you to the home page. At the moment, clicking on the logo on any other page than the homepage will take you to the homepage, clicking on the logo on the homepage does nothing.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96297`, `MAGETWO-96298` were created

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by orlangur** [comment]
@tomekjordan is there any reason to reload home page?

**Comment by DanielRuf** [comment]
The logo should just link to the homepage. It should not work as a reload buttin imho.

**Comment by DanielRuf** [comment]
The logo should just link to the homepage. It should not work as a reload button imho.

**Comment by gwharton** [comment]
@DanielRuf. I agree there seems to be no reason to implement a reload button on the homepage, but i also dont think it doesnt do any harm, and if it helps some users on mobile then ....... Anyway, the PRs are there if it os decided to go forward with this.

**Comment by orlangur** [comment]
@DanielRuf @gwharton just trying to understand the use case as home page does not seem to contain any dynamic elements which would require refresh. Just in case when connection is interrupted probably but it would be strange to locate logo on page, if it is loaded, instead of constantly located refresh button in browser.

Asking for evaluation by some UX person from Magento now.

**Comment by DanielRuf** [comment]
> instead of constantly located refresh button in browser.

Exactly. Do not replicate / duplicate browser navigation inputs as this is not good UX.

**Comment by gwharton** [comment]
I totally agree that it is unnecessary, however it does seem to be a reasonably widely implemented practice for websites to have a clickable logo on their homepage, that takes you to their ...... ahem......homepage. e.g github, microsoft, yahoo, bbc, w3c etc. I'm sure there are just as many out there that don't though.

However.... I suspect that many of the sites that do implement it, do so because it is easier to leave it in, than code it out.

**Comment by orlangur** [comment]
@gwharton would be great to understand why it is not clickable in the first place but I doubt it is possible)

**Comment by gwharton** [comment]
Yeah, I did check when the Homepage logo click check was introduced and it was all the way back to the first alpha commit, i.e its always been there.

**Comment by magento-engcom-team** [comment]
Hi @orlangur. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by orlangur** [comment]
Just received an approval from @ericerway on this.

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for your report. 
The issue has been fixed in magento/magento2#19198 by @gwharton in 2.3-develop branch
Related commit(s):
 - [f6a6d11bc0219bc4847745d264f8991d04d5372e](https://github.com/magento/magento2/commit/f6a6d11bc0219bc4847745d264f8991d04d5372e)
 - [99c4d0080bde4201a1e3bce5367eb46bcd320ca7](https://github.com/magento/magento2/commit/99c4d0080bde4201a1e3bce5367eb46bcd320ca7)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for your report. 
The issue has been fixed in magento/magento2#19199 by @gwharton in 2.2-develop branch
Related commit(s):
 - [bd3cb9b44f7328bf1d46eadadbeac5851c6a3fd6](https://github.com/magento/magento2/commit/bd3cb9b44f7328bf1d46eadadbeac5851c6a3fd6)
 - [2ad7fd6c81a32457d87a386647e5d483df98f475](https://github.com/magento/magento2/commit/2ad7fd6c81a32457d87a386647e5d483df98f475)

The fix will be available with the upcoming 2.2.8 release.
