### ISSUE TITLE
category url key blank and saving to url rewrite table saves only .html

### ISSUE THREAD

**Issue by Rich07082** [magento/magento2#19156]
**Description (*)**

I've recently upgraded to Magento 2.2.6 and have run into the following problem.  I've been through all the category tables and everything looks correct.

When opening a category the url key is blank.  Check against CATALOG_CATEGORY_ENTITY_VARCHAR and there is data associated with the category but doesn't load.

If you save the category it will update the url_path in CATALOG_CATEGORY_ENTITY_VARCHAR and will update URL_REWRITE with just .html.

Created a dummy category with the same results.

All category tables seem to populate correctly except the URL_KEY, blank.

It populated the URL_PATH correctly with a automatically generated url.

Writes only .html to the URL_REWRITE table.

All other data and table references seems to be stored correctly.

No errors are in the logs or thrown when saving.  Once saved you get category have been saved or created.

**Expected behavior (*)**

popluates url_key with data from database on admin page.  Saves correct data to URL_REWRITE table and URL_Key

**Additional information**
 
Everything on the front end is working correctly. 

I've set up a fresh vanilla Magento 2.2.6 and it is working correctly.  I've compared both database tables and I can't find any differences.

Thanks
Rich

**Comment by magento-engcom-team** [comment]
Hi @Rich07082. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Rich07082 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Rich07082 , thank you for you report, The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by Nuranto** [comment]
Hi @Rich07082,

Did you find a solution for this problem ?

**Comment by Nuranto** [comment]
found it, ok so if someone have this issue, here it is :
The `setup:install` process miss some lines in `catalog_eav_attribute` (including the category's url_key one). 
So I just insert the missing line from another install, and it solved the issue.

Note : It was the first time it happened to me even though I made plenty of installs (always the same way)... So I don't know the conditions to reproduce... But if someone figures it out, please make an issue so the dev team can fix this.
