### ISSUE TITLE
Order saved wrong customer data

### ISSUE THREAD

**Issue by kevinvuillemin** [magento/magento2#19160]
The order save wrong customer data, the email, lastname and firstname but not customer ID.
This error appears in a production website wich use Magento 2.2.6.

### Preconditions (*)

1. Magento 2.2.6 
2. PHP 7.0
3. Mysql 5.6.41
4. OS FreeBSD 

### Steps to reproduce (*)

This error appears one time, and we can’t reproduce it – but it’s a critical one for the seller, and we should find a solution.

We have 2 customers (These informations are simulated):
Customer A (Information from table customer_entity): 
    • Name : Dupond
    • Firstname : Alexia
    • Dob : 1990-01-28
    • Email : alexia.dupond@gmail.com
    • Entity_id  : 236

Customer B :
    • Name : Martin
    • Firstname : Karine
    • Dob : 1978-11-21
    • Email : karine.martin@yahoo.com
    • Entity_id  : 217

Customer A (Alexia Dupond) ordered 1 product, and payed it correctly.  (But customer B received order's confirmation)

This is information from sales_order table :
entity_id : 295
customer_id : 236 (entity id of customer A : Alexia Dupond)
quote_id: 1287
customer_dob :1978-11-21
customer_email :karine.martin@yahoo.com

### Expected result (*)

![magento2_accountinformation_good](https://user-images.githubusercontent.com/12586404/48320371-81e6a400-e66d-11e8-96e7-601ba785de80.png)

### Actual result (*)

1. ![magento2_accountinformation](https://user-images.githubusercontent.com/12586404/48320315-970f0300-e66c-11e8-9abf-6ea82749da11.png)
2. As you can see on this screenshot, account information are bad, but the customer link to the order is the good one (236).

**Comment by magento-engcom-team** [comment]
Hi @kevinvuillemin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kevinvuillemin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@kevinvuillemin,

> This error appears one time, and we can’t reproduce it 

How anyone else can reproduce it then? Which actions were made by customer B at the time of order placement?

**Comment by kevinvuillemin** [comment]
Ok,

I was able to reproduce this.

It's an old cart from customer with different entity_id because I had to reimport customers who have a different entity_id.

The customer  "B"  created one quote before reimporting customers, and, after reimport, the customer "A" connect to magento with the same id of customer "B" without updating his cart . So, magento did not update quote. 

I updated all table quote with the correct custom_id associate to his email like this :

update quote inner join customer_entity on quote.customer_email = customer_entity.email set quote.customer_id = customer_entity.entity_id.

**Comment by orlangur** [comment]
> The customer "B" created one quote before reimporting customers, and, after reimport, the customer "A" connect to magento with the same id of customer "B" without updating his cart . So, magento did not update quote.

Magento is not supposed to update quote in case you modified customer ids directly in database.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @kevinvuillemin i'm not able to reproduce following steps you are described, and if you update customer ids direct in database, this is expected behavior.

**Comment by kevinvuillemin** [comment]
Hello,

Thank you very much for your answer

I want just add that i not updated customer ids direct in database, only import.

Magento2 update the quote of customer when you add or delete product in cart alright ? But if you  pay directly, the quote not updated, but i think it's important, because if the quote is very old and you pay directly an old cart nothing data updated. So you can have the wrong email or name associate to order.
