### ISSUE TITLE
Cant change Invoice/ CreditMemo sequnce numbers storeviewl-evel

### ISSUE THREAD

**Issue by nadeefit6** [magento/magento2#19162]
### Preconditions (*)

1. Magento 2.2.5
2. create 2 store views per web site

### Steps to reproduce (*)

1. Change In 'prefix' of 'sales_sequence_profile' table to 

 # update `sales_sequence_profile` set `prefix` = 11 where meta_id =11; (Storeview 1 - default website-Order)
# update `sales_sequence_profile` set `prefix` = 12 where meta_id =12; (Storeview 1 - default website-Invoice)
 # update `sales_sequence_profile` set `prefix` = 21 where meta_id =21; ( Storeview 2 - Order)
# update `sales_sequence_profile` set `prefix` = 22 where meta_id =22; ( Storeview 2 - Invoice))

### Expected result (*)

1. Storeview 1 Order ID prefix : 11
2. Storeview 1 Invoice ID prefix : 12
3.  Storeview 2 Order ID prefix : 21
4.  Storeview 2 Invoice ID prefix : 22

### Actual result (*)

1. Storeview 1 Order ID prefix : 11
2. Storeview 1 Invoice ID prefix : 12
3.  Storeview 2 Order ID prefix : 11
4.  Storeview 2 Invoice ID prefix : 12

That means 2nd Store does not change and gets the value of the default store.

**Comment by magento-engcom-team** [comment]
Hi @nadeefit6. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nadeefit6 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @nadeefit6 thank you for you report, as i can see, you just overwriting the same row with meta_id=12, and meta_id=11, so you basically not set id to storeview 2, this is not a bug.

**Comment by nadeefit6** [comment]
Mistake in writing.
Changed the query in description.
The actual values are not working with non-duplicae data as well.

And Also sequence tables are empty in this case.
Ex: sequence_invoice_2 table is empty.
Please check.

**Comment by ghost** [comment]
@nadeefit6 ok

**Comment by ghost** [comment]
@nadeefit6 magento not allow you to change the prefix for orders, and  this is not best way to change this on database.  It will be processed faster if you move this to https://github.com/magento/community-features
