### ISSUE TITLE
Broken UI on vanilla Magento 2.3 install from HEAD

### ISSUE THREAD

**Issue by vivek-graas** [magento/magento2#19167]
### Preconditions (*)

1.CE 2.3-develop - HEAD (Latest commit 072ef37)
2.Vanilla magento 2.3 installation on Ubuntu 18.04 and MySQL, Nginx, FPM
3. Chrome / Firefox browser on Ubuntu desktop

### Steps to reproduce (*)

1. Install Magento 2.3 from source using contributor guidelines from the HEAD
2.Note: I don't get the errors if I install from an earlier commit (Oct 31)

### Expected result (*)

1. Expect basic theme css and js to load without errors

### Actual result (*)

1. Chrome developer console errors:
`Refused to apply style from 'http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/mage/calendar.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to apply style from 'http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/css/styles-m.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 Refused to apply style from 'http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/css/styles-l.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):22 GET http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/requirejs/require.js net::ERR_ABORTED 404 (Not Found)
(index):23 GET http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/mage/requirejs/mixins.js net::ERR_ABORTED 404 (Not Found)
(index):24 GET http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/requirejs-config.js net::ERR_ABORTED 404 (Not Found)
(index):25 GET http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/mage/polyfill.js net::ERR_ABORTED 404 (Not Found)
(index):65 Uncaught TypeError: require.config is not a function
    at (index):65
(anonymous) @ (index):65
(index):105 GET http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/images/logo.svg 404 (Not Found)
(index):1 Refused to apply style from 'http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/css/print.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
favicon.ico:1 GET http://www.m23pwastore.com/pub/static/version1542015398/frontend/Magento/luma/en_US/Magento_Theme/favicon.ico 404 (Not Found)`

![image](https://user-images.githubusercontent.com/16497360/48340067-ab182c00-e68f-11e8-9d06-f5a3cf510b1b.png)

**Comment by magento-engcom-team** [comment]
Hi @vphalak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vphalak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by vivek-graas** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vphalak. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vphalak, here is your [Magento instance](http://34.228.235.121/i-19167-2-3-develop/).
Admin access: [http://34.228.235.121/i-19167-2-3-develop//admin](http://34.228.235.121/i-19167-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @vphalak  did you try to clean pub static folder ?

**Comment by ghost** [comment]
@vphalak i'm no able to reproduce following steps youre described, seems like problem related to your configuration, please try  to clean pub/static folder, and let me know if the issue still presist, if you like to update this please reopen the issue.

**Comment by vivek-graas** [comment]
I think I see the source of the issue. The page source shows **/pub/** being appended to baseUrl for loading static assets. See below. However, I am not certain what causes it. Regenerated pub/static files several times. Permissions look ok too.


```
<script>
--
  | var BASE_URL = 'http://www.m23store.com/';
  | var require = {
  | "baseUrl": "http://www.m23store.com/pub/static/version1542191804/frontend/Magento/luma/en_US"
  | };
  | </script>

```
Found a really old issue with the same problem: https://github.com/magento/magento2/issues/2711
