### ISSUE TITLE
Validation on Product quantity in case of decimals

### ISSUE THREAD

**Issue by manolismax** [magento/magento2#19209]
Hello, 
I have faced a validation issue, on product quantity when i work with decimals. I get a quantity validation error if i set decimal value to Increments

### Preconditions 
Magento 2.2.6
sample data

#### On admin->productPage -> Advanced Inventory 
Set :

- Minimum Qty Allowed in Shopping Cart = 0.5
- Qty Increments = 0.1

#### Frontend Product page
 Set:  quantity =1

### Expected result 
 quantity =1 is  a multiple of 0.5  , so the product has to be added on cart
### Actual result 
A validation error throws  always  **You can buy this product only in quantities of 0.1 at a time.**

### Explanation
As i tried to debug this error, I ended up on [this line](https://github.com/magento/magento2/blob/22539f972e32128aeeec0f65aebb1f29879f8231/lib/web/mage/validation.js#L1578) on [validation.js](https://github.com/magento/magento2/blob/22539f972e32128aeeec0f65aebb1f29879f8231/lib/web/mage/validation.js)

The bug is on `  qty % $.mage.parseNumber(params.qtyIncrements) === 0;` , cause the javascript modulo operator doesn't work correctly on floats. As you can see on the following links, unfortunately is a known js issue.
[link1](https://stackoverflow.com/questions/3966484/why-does-modulus-operator-return-fractional-number-in-javascript) [link2](http://adripofjavascript.com/blog/drips/avoiding-problems-with-decimal-math-in-javascript.html)

You can simply replicate it on console 

```
console.log(5%1)
0

console.log(.5%.1)
0.09999999999999998
```

As a quick solution, the only i can propose is to multiple both before validation with a big number Example: ` (10000 *qty) %( $.mage.parseNumber(params.qtyIncrements) * 10000) === 0;`

**Comment by magento-engcom-team** [comment]
Hi @manolismax. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@manolismax do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by eduard13** [comment]
Hi @manolismax looks like there is already a similar reported issue #12914 which looks to be in progress.

**Comment by orlangur** [comment]
@eduard13 I don't think so. The one you mentioned is about validation in Admin UI, this one is about rounding.

**Comment by orlangur** [comment]
Ref older issue: https://github.com/magento/magento2/issues/8404#issuecomment-342001698

Validation should occur the same way it works on PHP side.

Multiplication is not a good idea, it's better to introduce some delta:

```
console.log(Math.abs(.5%.1 - 0.1))
1 2.7755575615628914e-17
```

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96559`, `MAGETWO-96560` were created

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vasilii-b** [comment]
I'll grab this one since already involved in the topic. Thank you!

**Comment by hubertinio** [comment]
The issue still exists, there is a bug releated with js module, my resolution below:

```
diff --git a/lib/web/mage/validation.js b/lib/web/mage/validation.js
index dfa35473..7b0adceb 100644
--- a/lib/web/mage/validation.js
+++ b/lib/web/mage/validation.js
@@ -1610,7 +1610,7 @@
-                        qty % $.mage.parseNumber(params.qtyIncrements) === 0;
+                        (qty * 10) % ($.mage.parseNumber(params.qtyIncrements) * 10) === 0;
 
```

**Comment by krzksz** [comment]
It seems like this bug was fixed by https://github.com/magento/magento2/commit/0104df69d3c7fec10990ddc7a9d93690562cefb9 which is a part of 2.3.3 release.
