### ISSUE TITLE
Bundle Product Option with input type is checkbox and add to cart with 3 values only 2 values added to cart

### ISSUE THREAD

**Issue by sneha-panchal** [magento/magento2#19205]
All selections of a bundle option of type check box that were checked once are added to cart -- not all selected values displaying in cart.

### Preconditions (*)

1. Magento 2.2.5
2. sample data

### Steps to reproduce (*)
1. Open and edit this product Sprite Yoga Companion Kit (SKU : 24-WG080) (Bundle Product) on its own
2. Change first bundle option(option title is : Sprite Stasis Ball) input type to check box and save product
3. Open this product in front end and select all 3 values for option Sprite Stasis Ball and add to cart this product
4. Now check mini cart/cart page

### Expected result (*)

1. All selected check box values must be displayed in cart and mini cart

### Actual result (*)

1. We selected 3 values but it displaying only 2

![10 16 16 141 magento225 sprite yoga companion kit html](https://user-images.githubusercontent.com/29649994/48476181-5e198e80-e824-11e8-9b83-4fbd8f487ac2.png)

**Comment by magento-engcom-team** [comment]
Hi @sneha-panchal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sneha-panchal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](http://34.228.235.121/i-19205-2-2-develop/).
Admin access: [http://34.228.235.121/i-19205-2-2-develop//admin](http://34.228.235.121/i-19205-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](http://34.228.235.121/i-19205-2-3-develop/).
Admin access: [http://34.228.235.121/i-19205-2-3-develop//admin](http://34.228.235.121/i-19205-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96351` were created

**Comment by VladimirZaets** [comment]
Hi @sneha-panchal. Thank you for your report. 
The issue has been fixed in magento/magento2#19260 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [aa379ea60c5afbd020f72d53b2ccac1ffde753d9](https://github.com/magento/magento2/commit/aa379ea60c5afbd020f72d53b2ccac1ffde753d9)
 - [1a321d2fa30f031f4beb37d562a995aef94d5dd8](https://github.com/magento/magento2/commit/1a321d2fa30f031f4beb37d562a995aef94d5dd8)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @sneha-panchal. Thank you for your report. 
The issue has been fixed in magento/magento2#19261 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [9dfe1372ce941a36b700efe1dbb4851ea5bc3520](https://github.com/magento/magento2/commit/9dfe1372ce941a36b700efe1dbb4851ea5bc3520)
 - [eb2e505c68b1ed24ccc7d45e4a7eb4c2b0216f23](https://github.com/magento/magento2/commit/eb2e505c68b1ed24ccc7d45e4a7eb4c2b0216f23)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @sneha-panchal. Thank you for your report. 
The issue has been fixed in magento/magento2#19437 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [4bf63dadd2df27035063eb24d34c33bc57863470](https://github.com/magento/magento2/commit/4bf63dadd2df27035063eb24d34c33bc57863470)
 - [98ae6ae5f81ed8d9a2de2016390289d110756ac6](https://github.com/magento/magento2/commit/98ae6ae5f81ed8d9a2de2016390289d110756ac6)

The fix will be available with the upcoming 2.3.1 release.
