### ISSUE TITLE
Magento EE 2.2.6 - adblocker blocks checkout functionality with minified/merged js

### ISSUE THREAD

**Issue by asim-vax** [magento/magento2#19212]
### Preconditions (*)
1.php 7.1
2. Magento EE 2.2.6

### Steps to reproduce (*)
) Installed vanilla Magento EE 2.2.6 
2) created product (admin panel -> catalog -> products -> new product) 
3) admin panel -> store -> config -> sales -> google API -> enabled -> YES 
4) admin panel -> store -> config -> sales -> google API -> account number -> 12345 
5) admin panel -> store -> config -> advanced -> developer -> javascript settings -> merge javascript -> YES 
6) admin panel -> store -> config -> advanced -> developer -> javascript settings -> minify javascript -> YES 
7) admin panel -> system -> cache -> refresh all caches 
8) frontend visit product page -> add to cart 
9) click mini basket -> proceed to cart 
9a) with adblock turned off, this works 
9b) with adblock turned on, this doesn't work, infinite loading circle

### Expected result (*)

1. checkout to load

### Actual result (*)

1. checkout has infinite loader
2. error thrown error output: 
main.min.js:2 Error: Script error for: Magento_GoogleTagManager/js/google-analytics-universal 
http://requirejs.org/docs/errors.html#scripterror 
at makeError (44dbba8c0605596e4aba459b86c8d628.min.js:16)

**Comment by magento-engcom-team** [comment]
Hi @asim-vax. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@asim-vax do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by asim-vax** [comment]
Yes, confirm this is reproducible on vanilla magento enterprise 2.2.6
Possibly related to: #12428

**Comment by orlangur** [comment]
@asim-vax, according to https://github.com/magento/magento2/issues/12428#issuecomment-416556613 this problem is reproduced only with Magento Commerce.

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@asim-vax , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
