### ISSUE TITLE
x-magento-cache-control - Aditional Variables Included

### ISSUE THREAD

**Issue by JackWormUK** [magento/magento2#19215]
### Preconditions (*)

1. Magento 2.2.6 CE
2. Varnish 5.2.1
3. CentOS 7 with WHM/Cpanel and Apache
4. Engintron (Nginx)
5. APACHE cache modules through EasyApache4 (for reference and in case they are relevant);
mod_cache, mod_cache_disk, mod_cache_socache, mod_expires, mod_file_cache, mod_pagespeed

### Steps to reproduce (*)

1. Install Magento 2.2.6 CE through composer
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition
2. Activate Varnish cache in the back end and set up Varnish etc (with full page caching and routing through Varnish, you do not get this error)

### Expected result (*)

1. x-magento-cache-control: max-age=86400, public, s-maxage=86400
2. x-magento-cache-debug: HIT

### Actual result (*)

1.  x-magento-cache-control: max-age=86400, public, s-maxage=86400, max-age=0, no-cache, s-maxage=10
2. x-magento-cache-debug: MISS

**Comment by magento-engcom-team** [comment]
Hi @JackWormUK. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@JackWormUK do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by JackWormUK** [comment]
@magento-engcom-team 

Yes, i can reproduce this on a blank vanilla magento install, which is installed as above

**Comment by JackWormUK** [comment]
I have got a bit further with this issue.

It appears to be the Apache Module - mod_pagespeed.

With this disabled, everything works as expected.

However, it does not explain why varnish cache headers are correct when Caching Application is set to Built-In Cache but are not correct when the Caching Application is set to Varnish Cache with mod_pagespeed enabled?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @JackWormUK, thank you for you report, i'm not able to reproduce following steps you described.
 As well as installing mod_pagespeed you need to set it up correctly: 
https://www.modpagespeed.com/doc/downstream-caching
You will also have to make sure your version of mod_pagespeed supports 'Varnish' as this is currently an 'experimental feature'.
