### ISSUE TITLE
Magento 2.2.3 Admin Grid showing wrong date.

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#19219]
### Context (*)
Admin Grids are displaying the wrong date.
For the sake of this issue I will only refer to the customer grid which is native Magento.

### Preconditions (*)

1. Magento 2.2.3
2. The server running Magento and the Mysql server have the same timezone. UTC.

### Steps to reproduce (*)

1. Create customer at YYYY-MM-DD 01:00:00. e.g 2018-05-22 01:00:00.
    Or just set created_at to reflect above date or any date with that pattern.

### Expected result (*)

1. The customer since column of the row associated with above customer should have a value that reflects above date. e.g. 2018-05-22 01:00:00.

### Actual result (*)

1.   The customer since column of the row associated with above customer has the value 
May 21, 2018 6:00:00 PM.

Above example results in a one day difference (so May 22 is now May 21).
There are other example that cause this one day difference but all examples show different hours.

For e.g
For value 2012-12-15 16:23:52 it shows Dec 15, 2012 8:23:52 AM

If anything else is required from me please ask.
Thank you.

**Comment by magento-engcom-team** [comment]
Hi @victortodoran. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@victortodoran do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by victortodoran** [comment]
Nevermind. I set the wrong timezone in Magento.
