### ISSUE TITLE
Suddenly started using another logged in user's session

### ISSUE THREAD

**Issue by systems-diplomatic** [magento/magento2#19211]
### Preconditions (*)
1. Magento 2.2.6 (but we have also seen it on 2.2.4)
2. FPC enabled or disabled
3. SID NOT included in URL
4. At least one item (doesn't matter which one) needs to be in the shopping cart in two user's sessions

### Steps to reproduce (*)
1. Click on link to view cart (not minicart) or go to checkout

### Expected result (*)
1. The user must only see their own details, none from another user.

### Actual result (*)
1. You may see data from another user's session including their cart contents.
2. From this point the user will see all the information from the other user's session including account information, order history, etc.

**Comment by magento-engcom-team** [comment]
Hi @systems-diplomatic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@systems-diplomatic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by systems-diplomatic** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @systems-diplomatic. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @systems-diplomatic, here is your [Magento instance](http://34.228.235.121/i-19211-2-2-6/).
Admin access: [http://34.228.235.121/i-19211-2-2-6//admin](http://34.228.235.121/i-19211-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @systems-diplomatic thank you for you report, i'm not able to reproduce following steps you described, i'm really don't  know in which cases you have the actual result. this may bge related to your custom code.

**Comment by ghost** [comment]
@systems-diplomatic, also take a look  this commit, https://github.com/magento/magento2/pull/17608

**Comment by Jilco** [comment]
@systems-diplomatic, wat was the root cause and how did you solve this? I'm facing the same issue

**Comment by systems-diplomatic** [comment]
@Jilco, we installed redis to handle the sessions and finally the problem went away, however we never really found the root cause.

**Comment by Jilco** [comment]
I think i found it, it is in engintron NGINX. The micro cache is the problem
