### ISSUE TITLE
Magento 2 Header Sign In Sign Out Issue on Home Page

### ISSUE THREAD

**Issue by Aqib133** [magento/magento2#19228]
### Preconditions (*)

1. Magento 2.2 
2. Ultimo theme

### Steps to reproduce (*)

1.Go to home page

2.Click 'Sign In' from header

3.Enter login credentials to enter customer account

4.Click website logo to go back to home page

5.Notice that on the home page the header is still showing 'Sign In' instead of showing the customer is logged in and a 'Sign Out' link.

### Expected result (*)

1. Sign Out Link instead of sign in link

### Actual result (*)

1.  on the home page the header is still showing 'Sign In' instead of showing the customer is logged in and a 'Sign Out' link.

**Comment by magento-engcom-team** [comment]
Hi @Aqib133. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Aqib133 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mahesh-rajawat** [comment]
@Aqib133 , please test with Magento Default Luma theme, issue is not reproducible.

**Comment by Aqib133** [comment]
@maheshWebkul721 ,Thanks for the response. We are actually making changes to the live website, so cannot change the theme to Luma. Do you mean that the issue is with the Ultimo theme, should we contact their support team?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Aqib133  this issue relate to your custom theme,The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by shweta2014** [comment]
I am getting the same issue, I have installed Memcached and using Magento 2.2.7. I dont think its custom theme issue, as i checked the files all the code is coming from Magento/Customer.
