### ISSUE TITLE
How can I get the "Qty Increments" in addtocart.phtml ?

### ISSUE THREAD

**Issue by eTonki** [magento/magento2#19223]
In Magento 2.2.6 from the file

"/app/design/frontend/THEME/Magento_Catalog/templates/product/view/addtocart.phtml"
How can I get the "Qty Increments" that I set as in the screenshot? 
 [Screenshot](https://i.stack.imgur.com/KQRt9.png)

I have done a lot of tests but they do not work, for example:

<?php echo $product->getStockItem()->getData('qty_increments') ?>
<?php echo $block->getProductQtyIncrements() ?>
<?php echo $stockItem->getQtyIncrements() ?>
<?php echo $product->getStockItem()->getQtyIncrements() ?>

**Comment by magento-engcom-team** [comment]
Hi @eTonki. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eTonki do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
