### ISSUE TITLE
Backend product grid show price of default store view not the default value

### ISSUE THREAD

**Issue by rikwillems** [magento/magento2#19221]
### Preconditions (*)

1. Magento 2.2.3
2. Multistore setup

### Steps to reproduce (*)

1. Add a product and set a price
2. Switch to (default) store view and set new price
3. Go to product grid

### Expected result (*)

1. See the default price value

### Actual result (*)

1. See the price of the default store view

**Comment by magento-engcom-team** [comment]
Hi @rikwillems. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rikwillems do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](http://34.228.235.121/i-19221-2-3-develop/).
Admin access: [http://34.228.235.121/i-19221-2-3-develop//admin](http://34.228.235.121/i-19221-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by dmytro-ch** [comment]
Hello, @rikwillems,
thank you for the report.
By default, the product price value cannot be set per store view, as well as product SKU etc. In case you change the price, this value will be set globally.
<img width="356" alt="screen shot 2018-11-27 at 9 20 01 pm" src="https://user-images.githubusercontent.com/11693779/49105836-4c0b0780-f28a-11e8-864c-cf67909608f7.png">

**Comment by rikwillems** [comment]
@dmytro-ch the price can be set to website scope. This makes sense when you run a multi website setup. In that case this issue comes up.

**Comment by dmytro-ch** [comment]
@rikwillems, thank you for the details.
In this case, the price should be changed after switching the Store View filter for products grid.

It also looks like an expected behavior. In case the "All Store Views" is selected, the price for the default website is shown when available. Otherwise, the global price value is shown on products grid.

**Comment by TomashKhamlai** [comment]
@rikwillems, thank you for reporting this issue. This is an information from PO:

> The expected behavior for the products grid would be to show the default price (All Store Views) until a specific Store View is selected in the filter. Once a specific store view is selected we have to show the price which is set for that store view.

but currently the behavior is to display the price value in the grid from the Default Store View instead of All Store Views.

Checked on the latest 2.3-develop.
![peek 2018-12-04 14-04](https://user-images.githubusercontent.com/11827230/49441490-4d2ebe00-f7cf-11e8-98eb-1c444d7095e6.gif)

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96897` were created

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-19221-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19221-2-3-develop.instances.magento-community.engineering/admin](https://i-19221-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mamsincl** [comment]
appears with visibility as well ....

**Comment by iphigenie** [comment]
I think I have a related issue #28183 where in the columns and the filter, store view values are being used not admin values.

**Comment by iphigenie** [comment]
For the record this still happens - there are assumptions made when populating the data for the product grid that break functionality and make it hard for the people actually using the admin to do work

- label for options in select/multiselect is the front end one not the admin one, this is a huge usability loss for people actually working on sites in admin as one cannot optimise admin labels for speed of editing.
- dates are formatted for front end view, not admin - this is nowhere near as "skimmable" for people working on the content
- prices, visibility etc.
