### ISSUE TITLE
Magento 2.1.x deploy static lost SQL connection if session in DB

### ISSUE THREAD

**Issue by Jean-MarcS** [magento/magento2#19234]
### Preconditions (*)

1. Magento 2.1.7 (but had the same issue on precedent 2.1.X versions)
2. Magento on a LXC container and MariaDB 10.2 on another one (on Proxmox), working perfectly except that
3. System on production mode
4. Tested with MariaDB with Galera cluster and without
5. All MariaDB timeout variables set to more than 60s, buffers seem large enough

### Steps to reproduce (*)

1. Set session to db

### Expected result (*)

1. Static deployed

### Actual result (*)

1. MySQL errors pops

Things start smoothly 

```Requested languages: fr_FR
Requested areas: adminhtml, frontend
Requested themes: Magento/backend, Magento/blank, Magento/luma, Sm/himarket
=== adminhtml -> Magento/backend -> fr_FR ===
=== frontend -> Magento/blank -> fr_FR ===
.=== frontend -> Magento/luma -> fr_FR ===
.=== frontend -> Sm/himarket -> fr_FR ===
```

And then after about 30s

```
PHP Fatal error:  Uncaught Exception: Warning: PDOStatement::execute(): MySQL server has gone away in /_redacted_/deployment/production/releases/20181115083549/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228 in /_redacted_/deployment/production/releases/20181115083549/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'PDOStatement::e...', '/_redacted_...', 228, Array)
#1 /_redacted_/deployment/production/releases/20181115083549/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#2 /_redacted_/deployment/production/releases/20181115083549/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#3 /_redacted_/deployment/production/releases/20181115083549/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#4 in /_redacted_/deployment/production/releases/20181115083549/lib/internal/Magento/Framework/App/ErrorHandler.php on line 61
```

The last query arriving on the MySQL server is a SELECT on the `session` table, then an INSERT on the `session` table. There are 4 connections opened.

If using the -j flag to 1, no problem occurs, there is only one connection to DB, and a query every 15 seconds in our case.

I tried to do a small test in PHP, with opening the connection, do a query, idle during 100s, and then another query. No problem.

I perfectly know that it is not the last version in 2.1.x, and the problem might be elsewhere (network ? MariaDB ?). But I'm searching the web since the beginning of the week without any answer and I really think this is a bug somehow.

Feel free to close issue if it's not appropriate.

But I'm really wondering.

**Comment by magento-engcom-team** [comment]
Hi @Jean-MarcS. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Jean-MarcS do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Jean-MarcS i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.
