### ISSUE TITLE
Magento ver. 2.2.5 , Checkout errors

### ISSUE THREAD

**Issue by MuhammadUsman1947** [magento/magento2#19231]
Magento ver. 2.2.5 , Checkout errors, SEE SNAPSHOT.

  **Summary of the issue :** 

Was working on theme modification, added custom js and css files just.

  **Information on your environment**

Magento ver. 2.2.5 
Current PHP version:  7.1
Godaddy Hosting

  **Steps to reproduce**

Dont know, you can check live https://osakajdmmotors.com/

Let me know if there is any solution.

Thanks
![checkout page error](https://user-images.githubusercontent.com/14137102/48571055-c0a78300-e927-11e8-951f-2e91ba964dbd.png)

**Comment by magento-engcom-team** [comment]
Hi @MuhammadUsman1947. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MuhammadUsman1947 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by MuhammadUsman1947** [comment]
Hi, 

I have resolved the issue, I was created css and include in /public_html/app/design/frontend/Hiddentechies/bentriz/Magento_Theme/layout/default.xml

like this : 

`<head><css src="css/local-m.css" /></head>`

That causes error.
