### ISSUE TITLE
Magento 2 : fix php 7.2 error : Countable interface not implemented

### ISSUE THREAD

**Issue by gmachure** [magento/magento2#19247]
### Preconditions (*)

1. Magento ver. 2.3.0-beta32
2. PHP Version : 7.2.12

### Steps to reproduce (*)

1. Create custom module.
2. Add fileUploader form element in ui_component form).
```
<field name="image">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="dataType" xsi:type="string">string</item>
                    <item name="source" xsi:type="string">store</item>
                    <item name="label" xsi:type="string" translate="true">Image</item>
                    <item name="visible" xsi:type="boolean">true</item>
                    <item name="formElement" xsi:type="string">fileUploader</item>
                    <item name="allowedExtensions" xsi:type="string">jpg jpeg gif png</item>
                    <item name="uploaderConfig" xsi:type="array">
                        <item name="url" xsi:type="url" path="zodio_store/store/uploader"/>
                    </item>
                    <item name="notice" xsi:type="string" translate="true">Allowed extensions : jpg jpeg gif png. recommended size 600px*264px</item>
                    <item name="validation" xsi:type="array">
                        <item name="required-entry" xsi:type="boolean">true</item>
                    </item>
                </item>
            </argument>
        </field>
```
### Expected result (*)

1. ![image](https://user-images.githubusercontent.com/25632159/48633557-e1251b00-e9c3-11e8-904f-53e08dfbf32d.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/25632159/48633442-9acfbc00-e9c3-11e8-9861-30727122f639.png)

Error Message : Warning: count(): Parameter must be an array or an object that implements Countable in <base_dir>/vendor/magento/framework/File/Uploader.php on line 550

**Comment by magento-engcom-team** [comment]
Hi @gmachure. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gmachure do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96476` were created

**Comment by ghost** [comment]
Hi @gmachure i'm able to reproduce this issue on 2.3-develop instance
![selection_212](https://user-images.githubusercontent.com/40756439/48764671-f39b9f00-ecb8-11e8-99e7-720eca629dd8.png)

**Comment by magento-engcom-team** [comment]
Hi @gmachure. Thank you for your report. 
The issue has been fixed in magento/magento2#19249 by @gmachure in 2.3-develop branch
Related commit(s):
 - [f1e7e3f200470d255f953dc7bfef91db72f0ddb3](https://github.com/magento/magento2/commit/f1e7e3f200470d255f953dc7bfef91db72f0ddb3)
 - [a7b9122344fe2b333a371089e54e567621ceca0c](https://github.com/magento/magento2/commit/a7b9122344fe2b333a371089e54e567621ceca0c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by VZeroCool** [comment]
@gmachure @magento-engcom-team @orlangur   This doesn't seem to be fixed facing an issue while uploading an image for customer attribute with Magento CE 2.3 and PHP 7.2.13. 

Image uploaded to temp but the console has an error for Uncaught ReferenceError: Base64 is not defined. 

```
file.previewType = this.getFilePreviewType(file);

            if (!file.id && file.name) {
                file.id = Base64.mageEncode(file.name);
            }
```

**Comment by sumeetmobiwebtech** [comment]
@VZeroCool 
aftr try to fix uploader then getting error in console - Uncaught ReferenceError: Base64 is not defined

Anyone is there how solved it ?
