### ISSUE TITLE
Admin navigation covering page details

### ISSUE THREAD

**Issue by grlambert** [magento/magento2#19246]
Magento ver. 2.2.6
![m2 admin issue](https://user-images.githubusercontent.com/3420860/48633075-27f51f80-e988-11e8-9fe3-6388465b60c1.png)

### Steps to reproduce (*)
1.open admin. Click catalog>products and the page is only displaying whitespace. If you scroll down the products will appear. 
2.when you search for a product they will appear and then when you scroll the display area of the page clears to just white. If you scroll down to below the left navigation options the page renders, but it is hidden under the navigation bar.

### Expected result (*)

1. I would expect to see a page I could work on, but approximately 1/6 of it is hidden.

### Actual result (*)

1. There is no error message. The screen is just not displaying no matter what size you make it.
Please see the attached screenshot.

**Comment by magento-engcom-team** [comment]
Hi @grlambert. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@grlambert do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by grlambert** [comment]
I am not sure what other information you are looking for on this situation. Please advise.

**Comment by grlambert** [comment]
I am not a developer. I am a user and am having trouble using Magento 2.2.6 can you please help?

 


Sincerely, 

 


 

 




HEAVYGLARE EYEWEAR

14055 Grand Ave, STE G 

Burnsville, MN 55337

Monday through Friday

9:00 AM—6:00 PM CST

 

(651) 209-8474 | 888-548-0558

 

 <https://www.facebook.com/Heavyglare.eyewear>  <https://www.linkedin.com/in/grantlambert>   <https://twitter.com/Heavyglare>   <https://plus.google.com/+Heavyglare>   <https://www.pinterest.com/heavyglare/> 


Grant Lambert, ABOC

Founder–CEO

www.heavyglare.com <http://www.heavyglare.com/> 

 




“If you like us spread the word, if we did something wrong, let us know so we can make it right.”

 

CONFIDENTIALITY NOTICE: This e-mail message and all attachments transmitted with it may contain legally privileged and confidential information and is intended solely for the use of the recipient(s) named above.  If you are not an intended recipient, you may not review, copy or distribute this message.  If you have received this communication in error, please notify the sender immediately by telephone (888-548-0558) or by e-mail, and delete the original message and all copies or back-ups of this message.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @grlambert   , thank you for you report, I'm not able to reproduce following steps you described on clean magento 2.2.6 instance.The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
