### ISSUE TITLE
Customer Export Issue In M2

### ISSUE THREAD

**Issue by td-emerson** [magento/magento2#19242]
### Preconditions (*)
1. Magento 2.2.6

### Steps to reproduce (*)

1. Add an additional gender option for gender attribute and assign that option to any customer
**Screenshots**: [](https://drive.google.com/a/raveinfosys.com/file/d/1IDkWOteMOses6hQQiAfa08xpOx0Wwjby/view?usp=drivesdk)
[](https://drive.google.com/a/raveinfosys.com/file/d/1ej9pD86cZGx53OJepc8FvKn9WG3DFz8G/view?usp=drivesdk)
2. Now export customers from admin.

### Expected result (*)

1. Magento should generate customers csv

### Actual result (*)

1. Generating error.
2. main.ERROR: Notice: Undefined offset: 6 in /var/www/html/magento226/vendor/magento/module-customer/Ui/Component/DataProvider/Document.php on line 144

**Comment by magento-engcom-team** [comment]
Hi @td-emerson. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@td-emerson do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
