### ISSUE TITLE
can't translate country name

### ISSUE THREAD

**Issue by benyang2015** [magento/magento2#19257]
can't change country name ,change 台灣 to 中國台灣
（zh_Hant_TW）
I change vendor/magento/zendframework1/library/Zend/Locale/Data/zh_Hant.xml and vendor/magento/zendframework1/library/Zend/Locale/Data/zh_Hant_TW.xml
but does not work

### Preconditions (*)

1.magento2.2.6
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
Hi @benyang2015. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@benyang2015 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@benyang2015 GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

You're not supposed to change anything inside `vendor` and `Zend_Locale` is not used anymore AFAIR.
