### ISSUE TITLE
Category update/save after hierarchy changes with drag-and-drop breaks parent-child relationship

### ISSUE THREAD

**Issue by robyerevan** [magento/magento2#19253]
### Preconditions (*)

1. Magento ver. 2.2.3
2. Multistore setup

### Steps to reproduce (*)

1. Goto magento Admin -> Catalog -> Categories
2. Create multi-level category hierarchy
3. Move a sub-category from one level to upper level with mouse drag-and-drop
4. After successful ajax update click on save button located on right top corner

### Expected result (*)

1. New category hierarchy should be shown in admin area as well as in store front navigation
2. Save button may update category category records but it should consider hierarchy changes previously done with drag-and-drop (AJAX)

### Actual result (*)

1. New hierarchy appears correct in admin area, however in store front navigation we see no change
2. In catalog_category_entity DB table "parent_id" and "level" records are reverted back to old value, because of the SAVE action that partially updates records with old values

![workaround](https://user-images.githubusercontent.com/1753687/48654501-39f3b400-e9c2-11e8-876e-c90964c4b859.png)

### Proposed solution (*)

Unset parent_id and level elements after getData() method in vendor/magento/module-catalog/Model/Category/DataProvider.php

**Comment by magento-engcom-team** [comment]
Hi @robyerevan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@robyerevan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by robyerevan** [comment]
Tested with vanilla Magento 2.2.3 single store.
same issue.

Environment,
mysql@5.6,
nginx/1.15.5,
php@7.0,
Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

in admin area hierarchy will appear as changed however in store front end its old one.
DB records , "parent_id", "level" are wrong
DB record "path" is correct that's any its ambiguous, and we see different hierarchy in front end and admin area, different results.

Save is posting old values and messing with relationship records. See picture I have attached where i suggest not to click on save for store operators while issue is being investigated.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mahesh-rajawat** [comment]
Hi @robyerevan i am not able to reproduce this error on 2.2-develop

**Comment by robyerevan** [comment]
Hi @maheshWebkul721
It is reproducible on 2.2.3 tag release

MAGETWO-85040: Magento 2.2.3 Publication
 (build 2.2.3.024)

I guess it was fixed in later release

If you want to reproduce revert to tag 2.2.3
git reset --hard 2.2.3

**Comment by robyerevan** [comment]
It is reproducible on 2.2.3 tag release

It is not reproducible in current development branch
