### ISSUE TITLE
Access Token Lifetime for Customer is not working

### ISSUE THREAD

**Issue by ramkishansuthar** [magento/magento2#19256]
### Preconditions (*)

1. Magento 2.5
2. GET V1/carts/mine

### Steps to reproduce (*)

1. Set customer token life time to empty from admin by navigating to Store -> Configuration -> Services -> OAuth -> Access Token Expiration
2. Now generate customer token and access any API which requires customer token.
3. I am accessing GET V1/carts/mine service

### Expected result (*)

1. It should return cart informations

### Actual result (*)

1. 
![screenshot from 2018 11 17 12 34 28](https://user-images.githubusercontent.com/20473193/48658292-72989980-ea65-11e8-9b30-53ba519fdf07.png)

I found the code where customer token lifetime value comes in action and I can see there is no condition added for empty value. It typecast the value in integer. so it returns 0 in case value is saved as empty.
[https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Integration/Helper/Oauth/Data.php#LC121](Magento/Integration/Helper/Oauth/Data.php) 
[https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Webapi/Model/Authorization/TokenUserContext.php#LC125](Magento/Integration/Helper/Oauth/Data.php)

**Comment by magento-engcom-team** [comment]
Hi @ramkishansuthar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ramkishansuthar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ramkishansuthar. Thanks for the report. This problem has already been fixed on 2.2 develop and 2.3 develop
