### ISSUE TITLE
Can't add product with non-required Customizable Options Checkbox to Cart

### ISSUE THREAD

**Issue by magenest-dev** [magento/magento2#19267]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1.24
3. MySQL 5.7

### Steps to reproduce (*)

1. Create a product with a Customizable Option 
- type:Checkbox
- required: No
![2018-11-19 13 21 32](https://user-images.githubusercontent.com/44190478/48689792-96431780-ebfe-11e8-8918-3f5af760b787.png)
2. Go to product page on frontend
3. Add Product to Cart without checking any checkbox
![2018-11-19 13 23 23](https://user-images.githubusercontent.com/44190478/48689799-9fcc7f80-ebfe-11e8-9046-6f0dbd3cb0ec.png)

### Expected result (*)

1. Product is added to cart

### Actual result (*)

1. Error message: "The product's required option(s) weren't entered. Make sure the options are entered and try again."
![2018-11-19 13 24 05](https://user-images.githubusercontent.com/44190478/48689821-b1158c00-ebfe-11e8-9898-bcb9f1dba272.png)

If I check the option, I can add the product to cart, seem like it doesn't check if the option is required or not.
![2018-11-19 13 24 16](https://user-images.githubusercontent.com/44190478/48689843-cc809700-ebfe-11e8-9e47-25339493237e.png)
![2018-11-19 13 24 21](https://user-images.githubusercontent.com/44190478/48689845-ce4a5a80-ebfe-11e8-9fb0-5e0b16bd9760.png)

**Comment by magento-engcom-team** [comment]
Hi @magenest-dev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magenest-dev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magenest-dev** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @magenest-dev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @magenest-dev, here is your [Magento instance](http://34.228.235.121/i-19267-2-3-develop/).
Admin access: [http://34.228.235.121/i-19267-2-3-develop//admin](http://34.228.235.121/i-19267-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magenest-dev** [comment]
@magento-engcom-team I confirm that I was able to reproduce the issue on vanilla Magento instance following steps to reproduce

**Comment by magenest-dev** [comment]
I think this is where the problem lies: app/code/Magento/Catalog/Model/Product/Option/Type/Select.php:74

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96448` were created

**Comment by ashar01** [comment]
The issue is still there.I am facing same issue. Can anyone provide me quick fix of this issue ? 
@magento-engcom-team can you tell me when this issue will be fixed. we updated from magento 2.2 to 2.3 and now facing this issue with customizable options.

**Comment by salvofancello** [comment]
I confirm exactly the same issue after we update system to 2.3. Please fix it as soon as possible, thank you

**Comment by keyurk-emipro** [comment]
#mm19in

**Comment by magento-engcom-team** [comment]
@keyuremipro thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @ErikPel. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by rohitkundale** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@rohitkundale thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by rohitkundale** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rohitkundale. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rohitkundale, here is your [Magento instance](https://i-19267-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19267-2-3-develop.instances.magento-community.engineering/admin](https://i-19267-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rohitkundale** [comment]
Issue is not reproducible in 2.3-develop.

**Comment by hagotupagina-spa** [comment]
Still a thing on 2.4.5-p1
