### ISSUE TITLE
Poor UX when editing attribute options in multistore setup

### ISSUE THREAD

**Issue by sreichel** [magento/magento2#19262]
### Preconditions (*)

1. since 1.x/2.x
2. multiwebsite/store setup

- Website 1 - B2B - DE
- Website 1 - B2B - EN
- Website 1 - B2C - DE
- Website 1 - B2C - EN
- Website 2 ...
- ...

### Steps to reproduce (*)

1. multiple storeviews with same label/name. (You can not use cryptic names here b/c its displayed in store switcher) 
2. go to attribute edit page for a select/multiselect attribute like color
3. "try" to add frontend labels to the correct storeview. It's hard b/c you dont know wich column belongs to wich store.

### Expected result (*)

1. first row (storeview labels) should be grouped by store and website

### Actual result (*)

1. 

![m2-attribute-options](https://user-images.githubusercontent.com/5022236/48673220-844e6f80-eb3f-11e8-97e3-a5a1a9627a0d.PNG)

Found this: https://github.com/magento/magento2/issues/13053

As you can see here (https://user-images.githubusercontent.com/20454811/34669044-3ae7628c-f470-11e7-8381-ee12aa70b083.jpg) you can workaround with "cryptic"  storeview names, but this is also displayed in storeswitcher .... so its no good idea.

If there is no out-of-the-box-solution, please do not close this a feature request. 

Maybe you can add a new proprety `backend_label` to storeviews (also stores and websites)?

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sreichel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @sreichel this can be a feature request, It will be processed faster if you move this to https://github.com/magento/community-features
