### ISSUE TITLE
Why is SessionManager used instead of its Interface?

### ISSUE THREAD

**Issue by dyuk1987** [magento/magento2#19274]
### Summary (*)

I was trying to fix the issue mentioned in #12362, by injecting an updated version of SessionManager to replace the original **Magento\Framework\Session\SessionManager**, on a **Magento 2.2.5**. After a while, I managed to find a few exceptions being thrown around by some of the third-party modules I have previously installed. The main problem here is that some of the classes in those modules have directly included "**Magento\Framework\Session\SessionManager**" in the constructor (instead of **Magento\Framework\Session\SessionManagerInterface**). I was worried if the replacement would cause similar problems elsewhere in the system, so I have done a few greps to look for classes having the SessionManager directly injected into their constructors, and I managed to find a few of them in the core codepool, namely **Paypal\Controller\Transparent\RequestSecureToken** and **Magento\Framework\View\Context**.
I am not quite sure why it is so, but it seems to me the interface should be used instead.

### Examples (*)

I don't really have an example here.

### Proposed solution

To change **Magento\Framework\Session\SessionManager** to **Magento\Framework\Session\SessionManagerInterface**

In 
1. Magento/Authorizenet/Model/Directpost/Session.php
2. Magento/Customer/CustomerData/Plugin/SessionChecker.php
3. Magento/Paypal/Controller/Transparent/RequestSecureToken.php
4. lib/internal/Magento/Framework/View/Context.php

**Comment by magento-engcom-team** [comment]
Hi @dyuk1987. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dyuk1987 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96481`, `MAGETWO-96482` were created

**Comment by magento-engcom-team** [comment]
Hi @jaimin-ktpl. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @dyuk1987. Thank you for your report. 
The issue has been fixed in magento/magento2#19359 by @jaimin-ktpl in 2.3-develop branch
Related commit(s):
 - [8b30520d4d0bb5ca0ebcc1ddd51d33708df753ae](https://github.com/magento/magento2/commit/8b30520d4d0bb5ca0ebcc1ddd51d33708df753ae)
 - [05dadd8eac7113fa98f975a8bff575a4341a7702](https://github.com/magento/magento2/commit/05dadd8eac7113fa98f975a8bff575a4341a7702)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @dyuk1987. Thank you for your report. 
The issue has been fixed in magento/magento2#21357 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [f5df1a8e4e4a97ee5ce6b7f1fdd0e5f90a41c679](https://github.com/magento/magento2/commit/f5df1a8e4e4a97ee5ce6b7f1fdd0e5f90a41c679)
 - [737a79eb5aae8b7b3bb7065707f7e643aa750ede](https://github.com/magento/magento2/commit/737a79eb5aae8b7b3bb7065707f7e643aa750ede)

The fix will be available with the upcoming 2.2.9 release.
