### ISSUE TITLE
Category tree is slow with many category

### ISSUE THREAD

**Issue by smcpaiva** [magento/magento2#19271]
### Preconditions (*)

Magento 2.2.5 and 2.2.6
PHP 7, MySQL/MariaDB

### Steps to reproduce (*)

Have 25.000 categories from level 1 to 6
All categories are set to have is_anchor = 1.
At this moment I do not have products associated with categories.

### Expected result (*)

Display Time for Product Create / Edit page should be reasonable (2-3 s)

### Actual result (*)

Display time is around 2 min
Since it takes 2 min to create/save product in a category

--
Server specs are the following :
Processorr : Single Xeon 4-Core E3-1231 v3 3.4Ghz w/HT
RAM : 10 GB
Storage : 500GB x2 (RAID-10).
OS : CentOS 7 (64bit) w/CloudLinux

Others:
The innodb_buffer_pool_size is set to 8Go.
The Database size is approx. 30Mb.
I need the is_anchor to 1 for all categories.
1 websites / store views & customer groups
Flat category and products are both enabled
The categories have been imported.
post_max_size,upload_max_filesize = 200M
xdebug is disability
--
Notes: 
It is also slow to exclude products.
Test only with simple product.
Error after save.: No data to save

**Comment by magento-engcom-team** [comment]
Hi @smcpaiva. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@smcpaiva do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @smcpaiva thank you for you report, this is acknowledged issue, please look -> #18144
