### ISSUE TITLE
On Notification page Select All and Select Visible both works same

### ISSUE THREAD

**Issue by hellotaran** [magento/magento2#19285]
### Preconditions (*)

1. Magento Commerce 2.2.6, Magento Open Source 2.2.6
2. Possibly all 2.* version.

### Steps to reproduce (*)

1. Login to Magento Admin.
2. Select Notifications (Bell Icon from right top of the screen).
3. Click on "See All".
4. Default paging is set to 20 rows per page.
5. Make sure you have more than 20 notifications so that you can have paging available and some notification are on next pages.
6. Now from Mass Action dropdown select "Select All" action. This will select only visible notifications (currently 20, as 20 rows per page is setup) instead of all available records.

### Expected result (*)

1. See the screenshot. This must select all 137 records instead of just 20.

![image](https://user-images.githubusercontent.com/7958215/48806274-d03c1880-ece7-11e8-8140-cdc14826ff43.png)

### Actual result (*)

1. Only visible (20) records were got selected instead of 137.

**Comment by magento-engcom-team** [comment]
Hi @hellotaran. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hellotaran do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96541`, `MAGETWO-96542` were created

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @hellotaran. Thank you for your report. 
The issue has been fixed in magento/magento2#19302 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [58514a0f25c7596d98b8b135eefa1564f9ed7935](https://github.com/magento/magento2/commit/58514a0f25c7596d98b8b135eefa1564f9ed7935)
 - [a4b989bc916d769f92b3ec88303d1f5dd76ef3a7](https://github.com/magento/magento2/commit/a4b989bc916d769f92b3ec88303d1f5dd76ef3a7)
 - [c805752d4489a1b52a8f071a5d6d16153260b510](https://github.com/magento/magento2/commit/c805752d4489a1b52a8f071a5d6d16153260b510)
 - [45996466df7cdf193570389be7e2f2be48ec80c8](https://github.com/magento/magento2/commit/45996466df7cdf193570389be7e2f2be48ec80c8)
 - [daf5fb9b7ca965e6f24ddd05434d051a08e3b8d5](https://github.com/magento/magento2/commit/daf5fb9b7ca965e6f24ddd05434d051a08e3b8d5)
 - [c23a55ca68000fee4caa1790e956f3de79f9f9eb](https://github.com/magento/magento2/commit/c23a55ca68000fee4caa1790e956f3de79f9f9eb)
 - [9de08844e936403918075c1693c2ca407f17ba25](https://github.com/magento/magento2/commit/9de08844e936403918075c1693c2ca407f17ba25)
 - [ac1355e9c92820eff6c50d0277fca3e998b2337d](https://github.com/magento/magento2/commit/ac1355e9c92820eff6c50d0277fca3e998b2337d)
 - [77670fae8ae53d4d37bec6a2a858816c66bf28ae](https://github.com/magento/magento2/commit/77670fae8ae53d4d37bec6a2a858816c66bf28ae)
 - [fad31c6d55b7960b6b63633aa92c48c887a88389](https://github.com/magento/magento2/commit/fad31c6d55b7960b6b63633aa92c48c887a88389)
 - [d2e5d87b3e5cce693b7ef71d5a55e9dab5eedeb5](https://github.com/magento/magento2/commit/d2e5d87b3e5cce693b7ef71d5a55e9dab5eedeb5)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @hellotaran. Thank you for your report. 
The issue has been fixed in magento/magento2#19910 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [9804da7b76f3bbb4e3a1503d35f707fb66581280](https://github.com/magento/magento2/commit/9804da7b76f3bbb4e3a1503d35f707fb66581280)
 - [c4bf9d2ed208a1c8aebcc755670aaa0abe11c2e5](https://github.com/magento/magento2/commit/c4bf9d2ed208a1c8aebcc755670aaa0abe11c2e5)
 - [9e378953602730bed40bd7af212cfed5048db5d9](https://github.com/magento/magento2/commit/9e378953602730bed40bd7af212cfed5048db5d9)
 - [b39a770b286a26c88505de02b13050775c87db20](https://github.com/magento/magento2/commit/b39a770b286a26c88505de02b13050775c87db20)
 - [c0ea9e453fad0a173afd6913fe90f419c884d955](https://github.com/magento/magento2/commit/c0ea9e453fad0a173afd6913fe90f419c884d955)
 - [0810a4a56f28f4707b1797b3fae30af76d36dc33](https://github.com/magento/magento2/commit/0810a4a56f28f4707b1797b3fae30af76d36dc33)
 - [a69b2d9c52ace3924af0719c6669a2ac6e5d6b72](https://github.com/magento/magento2/commit/a69b2d9c52ace3924af0719c6669a2ac6e5d6b72)
 - [598881f0dccc57cefc6b53d67f9728710e5435c5](https://github.com/magento/magento2/commit/598881f0dccc57cefc6b53d67f9728710e5435c5)
 - [84461c56077e73c59bbaf8babe83fc93f88a8407](https://github.com/magento/magento2/commit/84461c56077e73c59bbaf8babe83fc93f88a8407)
 - [83974791f74553775791c6e5a321a0e8fe5ca3a3](https://github.com/magento/magento2/commit/83974791f74553775791c6e5a321a0e8fe5ca3a3)
 - [380826604500cf6c2ccad02122b22b7d542fe492](https://github.com/magento/magento2/commit/380826604500cf6c2ccad02122b22b7d542fe492)
 - [108b19008ff6e60469b337d3424acb15d76320bf](https://github.com/magento/magento2/commit/108b19008ff6e60469b337d3424acb15d76320bf)
 - [25a6c2e4a1c7a6529e3ceadfb184479cf84080c6](https://github.com/magento/magento2/commit/25a6c2e4a1c7a6529e3ceadfb184479cf84080c6)
 - [4fd5c955d50d93173462ddb19ca24fcd206da84d](https://github.com/magento/magento2/commit/4fd5c955d50d93173462ddb19ca24fcd206da84d)
 - [2c55232bdf694c38c964841f7c7680b7d21e52eb](https://github.com/magento/magento2/commit/2c55232bdf694c38c964841f7c7680b7d21e52eb)

The fix will be available with the upcoming 2.2.8 release.
