### ISSUE TITLE
Category path issue

### ISSUE THREAD

**Issue by Shubham988** [magento/magento2#19289]
The first path which I followed is this: (Default Category, Default Category/Parent Category, Default Category/Parent Category/Sub Category). I am following this path because when I exported a csv format file from admin panel I got this written in it.
I am trying to add products to my website and the category path I am defining is in this format (Default Category,Default Category/Subjects,Default Category/Subjects/Business Management)
![whatsapp image 2018-11-14 at 10 39 35 am](https://user-images.githubusercontent.com/27619465/48824023-ffef2d00-ed88-11e8-86ea-7f8571cb482e.jpeg)
instead of adding the product into an existing category which I created manually it creates a new category for the imported product like, in this case, it is Business management under (writing | Research Methods).
![whatsapp image 2018-11-14 at 10 40 43 am](https://user-images.githubusercontent.com/27619465/48824095-46448c00-ed89-11e8-83d4-09fd8ad1e3ba.jpeg)
The category which I created manually (Business Management) is showing 0 products added in it.
![whatsapp image 2018-11-14 at 10 42 31 am](https://user-images.githubusercontent.com/27619465/48824125-5bb9b600-ed89-11e8-9335-ef375474f10f.jpeg)
I tried some alternate methods to overcome this problem by using category id instead of using category name.
![whatsapp image 2018-11-15 at 1 23 31 pm](https://user-images.githubusercontent.com/27619465/48824150-6d9b5900-ed89-11e8-8f85-aaa3aa506b73.jpeg)
but I got these results.
![whatsapp image 2018-11-15 at 1 24 16 pm](https://user-images.githubusercontent.com/27619465/48824172-7d1aa200-ed89-11e8-969f-df5dad003502.jpeg)
I also tried this path (Default Category, Default Category/Parent Category/Sub Category) and (Default Category/Parent Category/Sub Category)
Please suggest me some methods to solve this problem. Thank You

**Comment by magento-engcom-team** [comment]
Hi @Shubham988. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Shubham988 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Shubham988   , thank you for you report, The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
