### ISSUE TITLE
Wrong pager style

### ISSUE THREAD

**Issue by gujjwal00** [magento/magento2#19286]
### Preconditions (*)

1. In Magento version 2.2.6
2. Not in 2.2.5

### Steps to reproduce (*)

1. Place more than 10 orders (so that pager gets activated) as registered customer.
2. Go to 'My Orders' in My Account
3. Pager should be visible

### Expected result (*)

1. Pager should be displayed correctly (Limiter should float to right side)
![image](https://user-images.githubusercontent.com/27951674/48804620-28e8d100-ed3b-11e8-99ac-334ac9dc9f24.png)

### Actual result (*)

1. Pager is broken because the Limiter is over page links and we can't go to any other page.
 ![screenshot_2018-11-21 my orders - buy spares online](https://user-images.githubusercontent.com/27951674/48804900-dfe54c80-ed3b-11e8-8083-bc4b721a42ac.png)

I think this issue is caused by  #15878 .
Pager works correctly if I revert the changes done in this PR.

**Comment by magento-engcom-team** [comment]
Hi @gujjwal00. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gujjwal00 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gujjwal00** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @gujjwal00. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @gujjwal00, here is your [Magento instance](https://i-19286-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19286-2-2-6.instances.magento-community.engineering/admin](https://i-19286-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gujjwal00** [comment]
I was able to reproduce the issue on given instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96539`, `MAGETWO-96540` were created

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @gujjwal00. Thank you for your report. 
The issue has been fixed in magento/magento2#19296 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [301d73dd53db2861c2fd57b683a766229902fc3e](https://github.com/magento/magento2/commit/301d73dd53db2861c2fd57b683a766229902fc3e)
 - [7c013a136413d015dac1a9434210cd2e086544f6](https://github.com/magento/magento2/commit/7c013a136413d015dac1a9434210cd2e086544f6)
 - [584242c822875d69d349199116052728d350c506](https://github.com/magento/magento2/commit/584242c822875d69d349199116052728d350c506)
 - [ee0bae84eb582d488547f9f753f387b1d5ad0bb3](https://github.com/magento/magento2/commit/ee0bae84eb582d488547f9f753f387b1d5ad0bb3)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @gujjwal00. Thank you for your report. 
The issue has been fixed in magento/magento2#19298 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [ded5c49b392b341ff764d77e5031bba46e775eab](https://github.com/magento/magento2/commit/ded5c49b392b341ff764d77e5031bba46e775eab)
 - [2f60707cc599d69adb522d7a00c47c06fe9101ff](https://github.com/magento/magento2/commit/2f60707cc599d69adb522d7a00c47c06fe9101ff)
 - [d445e48ecbec6d7288bd013c116f96d88610df05](https://github.com/magento/magento2/commit/d445e48ecbec6d7288bd013c116f96d88610df05)

The fix will be available with the upcoming 2.3.1 release.
