### ISSUE TITLE
Losing Sample Data after Creating new theme

### ISSUE THREAD

**Issue by danielc1234** [magento/magento2#1929]
Hi,

I have been trying to create a theme based on the luma theme. I have successfully created the new theme, but once I switch over to the new theme, the sample data does not show up any more. Do I have to change settings somewhere? In my theme.xml I have the luma set as parent theme.

Thanks Dan

**Comment by alankent** [comment]
Could you be more precise about "does not show up"? I have been playing with themes myself with Luma recently myself. I can still search and find products. It does not really make sense that switching theme would remove products from the database etc. I would first check you are talking to the same web server/database combination.

Otherwise, can you describe the steps you used to enable the theme?  Maybe one of the commands accidentally wiped the database contents (because you ran the wrong command).

**Comment by danielc1234** [comment]
@alankent So I followed the create new theme as described here http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-create.html

I created my folder system like this..

![image](https://cloud.githubusercontent.com/assets/1151357/10024490/6961872c-6125-11e5-9a10-81194db835f1.png)

In my theme.xml, I set the  <parent>Magento/luma</parent>

Then changed the theme design in my admin, cleared all cache and removed pub static files. 

It is at that point, no products show up or images at all. I was hoping to keep the luma theme in tact while making some modifications to suite our needs. Really just playing at this point, but trying to get a handle on it.

Thanks

**Comment by alankent** [comment]
Could you try the following steps:
 * Via admin put theme back to Magento Luma, flush cache. Can you see products now? (If no, something must have wiped database; if you can still see products.)
 * With Luma theme, try a query for "red". Do you see products come up?
 * Put theme back to your new theme, flush cache. Do a search such as "red". Do any matching products come up?

Things I am wondering: is contents still in DB, were images accidentally deleted when you flushed caches, etc.  The above will hopefully narrow down options here.
Thanks

**Comment by danielc1234** [comment]
@alankent - Thanks for helping.

-- Put in Magento Luma and all images and products show
-- Search in Luma theme for red shows products
-- Search in Poly/main shows products when searching for red.

What is missing is homepage, category imaging and other theme related images. If I have my new theme as set to have the Magento/luma as parent, shouldn't it be that I would see the exact luma theme using mine?

**Comment by alankent** [comment]
Ah, OK - gotcha.  So the products are still present in the database.  I understand what the issue is now, but need to chase up some internal details so I give you a correct response. Feel free to ping me in case I don't get back to you in a few days.

**Comment by alankent** [comment]
First, we do not recommend inheriting from the Luma theme. We reserve the right to change this theme at any time. It is our demo. We only recommend inheriting from the blank theme.

That aside, I was trying to work out if there was an immediate solution to see if we had a functionality gap. Bottom line: no. We are going to think about it more to see what we can do (but no promises at this stage).

The issue you are seeing is because the Luma demo store experience is more than just the Luma theme. It also uses CMS functionality to populate the home page and other places. CMS functionality is not defined via themes - our sample data fixtures load up CMS content as well. The CMS widgets are currently linked to a specific theme name. There is no inheritance supported (today) in the CMS linkage with the theme. This is one thing we are reviewing.  The bigger question is whether themes should be able to define CMS blocks etc. That is a much bigger question, but we have some CMS review work coming up. Don't expect a quick answer on that one. (Theme developer community feedback on that one would be interesting!)

If you want to make it work today, you can, but not just using a theme. You need to go into the "Content" section, then look at each "Frontend App" (aka CMS Widget) that is associated with the "Magento Luma" theme. Today, you need to create a clone of the Frontend App associated with your new theme name. Then it will work today. (The CMS blocks don't need duplicating, just the frontend apps as they are the part bound to the currently selected theme name.)

**Comment by danielc1234** [comment]
@alankent 

Excellent explanation...thank you.

I was really just following the video on the Magento 2 dev pages. I was also just playing around with the theme to get familiar with how to modify things.

I see your point on the Frontend Apps, but in the admin the section it is grayed out to give you the ability to change themes. Is that the reason why they need to be duplicated?

![image](https://cloud.githubusercontent.com/assets/1151357/10055749/f14f98c8-6205-11e5-902f-d509ebb37d23.png)

**Comment by debuysserk** [comment]
@danielc1234 indeed, that's why you need to make new ones with the exact same settings except for the Design Package/Theme. A duplicate button would be a nice addition though.

We ran into the same thing when creating our theme, even the content on the category image disappeared where I expected it to be configured in the category section (display static block & products) but after inspection, they were front-end apps, aka widgets in Magento 1.x

**Comment by alankent** [comment]
I would be interested in understanding what theme developers would like to be able to do in addition to what we have. For example, if there was a (PHP/view element) block you could put in a layout file to access CMS Static Block content, would that be useful/sufficient? Or do themes not need to touch CMS blocks etc?  (This is not for GA - this is for the future.)

**Comment by debuysserk** [comment]
That's actually what we're using now in our own base Magento 1.x theme as well to load static blocks that we always use in our projects (client theme with our own base theme as parent). We'll be adding this to our (WIP) Magento 2.x base theme as well.

We only need to put the actual static blocks in the database for this to work after applying our theme. We'll be looking for an automated task to create these blocks too, to be even more efficient.

@alankent Having a widget example with static blocks in the demo theme is a good thing though, to show what it can do. But since it's theme dependant (and not changeable without making a new frontend-app (I need to get used to the name :)) it's a bit confusing for very new front-end developers messing around a bit.

**Comment by alankent** [comment]
Thanks for the feedback.

Warning: Don't get hung up on the name "Frontend-app". We are reviewing the name internally because the underlying code and UI concepts appear to be named differently. I personally dislike this - change names everywhere or nowhere is my moto. But every change as we close in on GA, no matter how minor, needs more careful thought due to potential impact. (So we would be unlikely to change the code, only the naming on the UI.)

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by theskillwithin** [comment]
What?  this even breaks with the blank theme that comes with magento2.  How is this not an issue?

**Comment by haydave** [comment]
Seems that the issue is related to elasticsearch service, which is stopped.

**Comment by CoutoDev** [comment]
@haydave I have to disagree with you, I have the same issue every time even with elasticsearch enabled
