### ISSUE TITLE
Estimate Shipping In Order Summary Not showing included tax

### ISSUE THREAD

**Issue by Mkennethsmith** [magento/magento2#19303]
### Preconditions (*)

1. Magento 2.1.15

### Steps to reproduce (*)
(see screen shots for reference)
1. Create a new shipping tax rule, with a 20% tax rate for the country you intend to checkout with. When creating the tax rule, creating a new product tax class named shipping and set the rule to use it.
2. Specify under Sales > Tax > Tax Class to use the new product tax class you just made.
3. Set the following:
Calculation Settings -> Shipping Prices = Excluding Tax
Price Display Settings > Display Shipping Prices = Including Tax
Shopping Cart Display Settings > Display Shipping Prices = Including Tax.
4. Add a product to the cart, then go to the cart and look at the shipping estimates in the order summary box to the right.

### Expected result (*)
1. I would expect to see the shipping estimates shown inclusive of tax in the order summary of the cart.

### Actual result (*)
1. Shipping estimates are shown excluding tax.

![screenshot 2018-11-21 at 14 32 42](https://user-images.githubusercontent.com/16221145/48848254-5feecf00-ed9b-11e8-8ae3-095620d5c10a.png)
![screenshot 2018-11-21 at 14 33 20](https://user-images.githubusercontent.com/16221145/48848255-5feecf00-ed9b-11e8-854e-d295db0fdfc1.png)
![screenshot 2018-11-21 at 14 41 14](https://user-images.githubusercontent.com/16221145/48848454-d7bcf980-ed9b-11e8-8499-84cef06cecd0.png)

**Comment by magento-engcom-team** [comment]
Hi @Mkennethsmith. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Mkennethsmith do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Mkennethsmith, thanks for the report. This problem has already been fixed on 2.2 develop and 2.3 develop

**Comment by ci2014** [comment]
@magento-engcom-team I have the same issue as described with Magento 2.3.0. In which file has this been solved? Thank you.

**Comment by nawabamit** [comment]
Hi,
I have the same issue in Magento 2.3 version. I have already created tax-rule etc and do the needfull setting in config->Tax.
(iii)Assing tax class to the product. but it always shows tax price 0.
