### ISSUE TITLE
magento 2.1.13 cannot create store view

### ISSUE THREAD

**Issue by kei2278lee** [magento/magento2#19320]
Information on your environment:
magento 2.1.3
php 7.0.29
Apache 2.4.6
Mysql 5.6.38

Steps to reproduce
when I create or enable store view will show 
There has been an error processing your request
Notice: Array to string conversion in /var/www/html/colorize/vendor/magento/framework/App/Config.php on line 84

 Summary of the issue
error log
a:4:{i:0;s:116:"Notice: Array to string conversion in /var/www/html/colorize_test/vendor/magento/framework/App/Config.php on line 84";i:1;s:6218:"#0 /var/www/html/colorize_test/vendor/magento/framework/App/Config.php(84): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/var/www/html/c...', 84, Array)
#1 /var/www/html/colorize_test/app/code/TemplateMonster/ThemeUpdater/Model/ThemeData.php(180): Magento\Framework\App\Config->getValue('themeupdater/ge...', 'stores', Array)
#2 /var/www/html/colorize_test/app/code/TemplateMonster/ThemeUpdater/Helper/Data.php(97): TemplateMonster\ThemeUpdater\Model\ThemeData->getVersion()
#3 /var/www/html/colorize_test/app/code/TemplateMonster/ThemeUpdater/Model/UpdateData.php(112): TemplateMonster\ThemeUpdater\Helper\Data->getVersion()
#4 /var/www/html/colorize_test/app/code/TemplateMonster/ThemeUpdater/Observer/Backend/UpdateObserver.php(41): TemplateMonster\ThemeUpdater\Model\UpdateData->isUpdateRequired()
#5 /var/www/html/colorize_test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): TemplateMonster\ThemeUpdater\Observer\Backend\UpdateObserver->execute(Object(Magento\Framework\Event\Observer))
#6 /var/www/html/colorize_test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(TemplateMonster\ThemeUpdater\Observer\Backend\UpdateObserver), Object(Magento\Framework\Event\Observer))
#7 /var/www/html/colorize_test/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#8 /var/www/html/colorize_test/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('controller_acti...', Array)
#9 /var/www/html/colorize_test/vendor/magento/framework/App/Action/Action.php(91): Magento\Framework\Event\Manager\Proxy->dispatch('controller_acti...', Array)
#10 /var/www/html/colorize_test/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/html/colorize_test/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/colorize_test/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor->___callParent('dispatch', Array)
#13 /var/www/html/colorize_test/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor), Array, 'adminAuthentica...')
#14 /var/www/html/colorize_test/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/www/html/colorize_test/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/colorize_test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor), Array, 'adminMassaction...')
#17 /var/www/html/colorize_test/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/colorize_test/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/colorize_test/var/generation/Magento/Backend/Controller/Adminhtml/System/Store/Save/Interceptor.php(26): Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#20 /var/www/html/colorize_test/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\System\Store\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/colorize_test/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/colorize_test/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#23 /var/www/html/colorize_test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#24 /var/www/html/colorize_test/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/colorize_test/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/colorize_test/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#27 /var/www/html/colorize_test/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/colorize_test/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#29 /var/www/html/colorize_test/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#30 {main}";s:3:"url";s:121:"/colorize_test/admin_1c8rmp/admin/system_store/save/key/a4c6ca5e4f6b0ffd2806abaa5713c78f834824bc90fdfd79d49008340354ac88/";s:11:"script_name";s:24:"/colorize_test/index.php";}

  Expected and actual results:
Can enable store view

**Comment by magento-engcom-team** [comment]
Hi @kei2278lee. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kei2278lee do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by kei2278lee** [comment]
I try 3 time and up to 2.1.15 
cannot fix this

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @kei2278lee, thank you for you report, only 2.2.0+ bug reports are considered nowadays. Try upgrading. The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
