### ISSUE TITLE
Unclear if tabs.test is correct

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#19327]
### Summary (*)

Shouldn't it be `.collapsible()` there?
https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/dev/tests/js/jasmine/tests/lib/mage/tabs.test.js#L39

Because I wanted to check if these tests are run on CI but I did not find them there.

### Proposed solution

Use `.collapsible()` to initialize collapsible?

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DanielRuf do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by larsroettig** [comment]
@omiroshnichenko  can you check this pls thank you

**Comment by omiroshnichenko** [comment]
Hi @DanielRuf, this test is correct. This test was written for tabs widget that defined in https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/tabs.js#L14. You could search in log for `mage/tabs`

**Comment by DanielRuf** [comment]
Yes but how does this initialize `collapsible`?

**Comment by omiroshnichenko** [comment]
@DanielRuf There are no collapsible, this test works with tabs widget. Where did you see initialization of collapsible?

**Comment by DanielRuf** [comment]
See the description of the test.

**Comment by DanielRuf** [comment]
> Check tabs collapsible inited

Another file with this comment has different code.

**Comment by omiroshnichenko** [comment]
tabs widget is a wrapper over collapsible widget from jQueryUI library. Inside tabs widget you can find initialization of collapsible https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/tabs.js#L159. So `Check tabs collapsible inited` checks that when you creating tabs widget collapsible widget will initialized on some elements https://github.com/magento/magento2/blob/0eb8677b0b4e35606032e856cc1ef7c80e68829f/dev/tests/js/jasmine/tests/lib/mage/tabs.test.js#L35-L43.

> Another file with this comment has different code.
I don't understand about what 'another file' you are talking about and how it could be related to this test.

**Comment by DanielRuf** [comment]
Ok, so `tabs()` in general is just a bit unclear.
