### ISSUE TITLE
Success Message Icon vertically misaligned in admin panel 

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19328]
### Preconditions (*)

1.Magento 2.2-develop

### Steps to reproduce (*)

1.Login to admin panel > System > Import.
2.Select necessary Option > Upload CSV.
3.Click on Check Data Button > Check success Message Icon 

### Expected result (*)

 ![expacted_result](https://user-images.githubusercontent.com/33230237/48892988-4d40cc80-ee65-11e8-83bb-93226f0e7a4e.png)

### Actual result (*)

![actual_result](https://user-images.githubusercontent.com/33230237/48893063-6ea1b880-ee65-11e8-991e-d9cb15dcb3e1.png)

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96585`, `MAGETWO-96586` were created

**Comment by ghost** [comment]
Hi @speedy008 this is not fixed in 2.2 and 2.3, when your PR will be merged then labels automatically added.

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19334 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [6be4ebf95d562fb3310812cc586dd02af57f5cdb](https://github.com/magento/magento2/commit/6be4ebf95d562fb3310812cc586dd02af57f5cdb)
 - [0cabc15ce233e4b16c665733a6aad4aa1d9944ca](https://github.com/magento/magento2/commit/0cabc15ce233e4b16c665733a6aad4aa1d9944ca)
 - [67c59ec844b4fb475ad45304522b878e3c4a4847](https://github.com/magento/magento2/commit/67c59ec844b4fb475ad45304522b878e3c4a4847)
 - [da33798488ac4eab87fee0837a8203758946d5ee](https://github.com/magento/magento2/commit/da33798488ac4eab87fee0837a8203758946d5ee)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19333 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [4fcc190b29946dc0b9920aafb094def6ae859df8](https://github.com/magento/magento2/commit/4fcc190b29946dc0b9920aafb094def6ae859df8)
 - [aa13b7dc9fd4d868b3ff4f9ea07450588cbf7d4d](https://github.com/magento/magento2/commit/aa13b7dc9fd4d868b3ff4f9ea07450588cbf7d4d)
 - [330b6ccce484a79ee4beb91f781c70033003613f](https://github.com/magento/magento2/commit/330b6ccce484a79ee4beb91f781c70033003613f)
 - [5cab3ff0b3fdbca752c340c32a24b799eb83bacc](https://github.com/magento/magento2/commit/5cab3ff0b3fdbca752c340c32a24b799eb83bacc)
 - [373c3b374892cf353b9d17ca098370aba2bf7aa2](https://github.com/magento/magento2/commit/373c3b374892cf353b9d17ca098370aba2bf7aa2)
 - [07216dde117d445d34c0e3e306dbee74c2f18fb0](https://github.com/magento/magento2/commit/07216dde117d445d34c0e3e306dbee74c2f18fb0)
 - [b7fa7f5847bad5f47739cab8d8fdf742db13580a](https://github.com/magento/magento2/commit/b7fa7f5847bad5f47739cab8d8fdf742db13580a)

The fix will be available with the upcoming 2.2.9 release.

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#21069 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [505352c0f87cff15ccdf00494694675263a6f2b0](https://github.com/magento/magento2/commit/505352c0f87cff15ccdf00494694675263a6f2b0)
 - [5efc288db2c5f5bdc45bf4c25bbf8458eb6996de](https://github.com/magento/magento2/commit/5efc288db2c5f5bdc45bf4c25bbf8458eb6996de)
 - [8d9ec3603aa8f0377a0b7deb3da105a241efeff9](https://github.com/magento/magento2/commit/8d9ec3603aa8f0377a0b7deb3da105a241efeff9)

The fix will be available with the upcoming 2.3.2 release.
