### ISSUE TITLE
Sample Link Issue in Downloadable product.

### ISSUE THREAD

**Issue by ansari-ziyaurrahman** [magento/magento2#19344]
### Preconditions (*)

1. Magento version 2.2.6 
2.

### Steps to reproduce (*)

1.Create a new Downloadable product.
2.Create a Link select with file type url. Create a Sample link with file type url.
3. Save product
4. Now delete sample link only and save product again. 
5. After save sample link reappearing.

### Expected result (*)

1. Sample link will be removed.
2.

### Actual result (*)

1. Sample link is not deleted upon save.
2.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ansari-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by agorbulin** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @agorbulin, here is your [Magento instance](https://i-19344-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19344-2-3-develop.instances.magento-community.engineering/admin](https://i-19344-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by agorbulin** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @agorbulin, here is your [Magento instance](https://i-19344-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19344-2-2-develop.instances.magento-community.engineering/admin](https://i-19344-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by agorbulin** [comment]
@ansari-krish 
Hi,
I've reproduced issue on 2.3 develop and made clarifications in steps to reproduce

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by agorbulin** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @agorbulin, here is your [Magento instance](https://i-19344-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19344-2-2-develop.instances.magento-community.engineering/admin](https://i-19344-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by agorbulin** [comment]
Seems fixed in pull request already https://github.com/magento/magento2/pull/19150

**Comment by ansari-ziyaurrahman** [comment]
Hi @agorbulin,
That solution is not working for me. I am also working on this issue.

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96693`, `MAGETWO-96694` were created

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-19344-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19344-2-3-develop.instances.magento-community.engineering/admin](https://i-19344-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-19344-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19344-2-2-develop.instances.magento-community.engineering/admin](https://i-19344-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19431 by @ansari-krish in 2.2-develop branch
Related commit(s):
 - [eed84854506e46f96a866a1a396d2737b0488cd1](https://github.com/magento/magento2/commit/eed84854506e46f96a866a1a396d2737b0488cd1)
 - [99dbb540300e888d2e04d46ec17e23edb00fa619](https://github.com/magento/magento2/commit/99dbb540300e888d2e04d46ec17e23edb00fa619)
 - [29eea73a254e5b50cdbe03baf940bcdad9365945](https://github.com/magento/magento2/commit/29eea73a254e5b50cdbe03baf940bcdad9365945)
 - [3b6307bb8b162455e5150189234ca57ac21734a6](https://github.com/magento/magento2/commit/3b6307bb8b162455e5150189234ca57ac21734a6)
 - [e519bc6f5c1a25d54e44c643ad04fb1812724922](https://github.com/magento/magento2/commit/e519bc6f5c1a25d54e44c643ad04fb1812724922)

The fix will be available with the upcoming 2.2.8 release.
