### ISSUE TITLE
Incorrect caching subscription status in newsletter plugin  

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#19345]
### Preconditions

1. Magento 2.4-develop

### Steps to reproduce

I spot the issue during placing order with two different community modules installed. In short, during placing order the customer object is subscribed by custom code which utilizes newsletter module, then customer object is saved a couple times, and it results with subscribing him, unsubscribing and subscribing again.

It is a bit complicated to prepare such environment and to reproduce it so I prepared short steps which show incorrect framework behavior.

1. Load customer object using repository and check his subscription status:

    $customer = $customerRepository->getById($customerId);
    $extensionAttributes = $customer->getExtensionAttributes();
    var_dump($extensionAttributes->getIsSubscribed()); // returns false

2. Subscribe customer to newsletter:

    $subscriber = $subscriberFactory->create();
    $subscriber->subscribeCustomerById($customerId);

3. Check subscription status again:

    $customer = $customerRepository->getById($customerId);
    $extensionAttributes = $customer->getExtensionAttributes();
    var_dump($extensionAttributes->getIsSubscribed()); // still returns false

### Expected result

1. getIsSubscribed returns true when runs after subscribing customer

### Actual result

1. getIsSubscribed returns false

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@wojtekn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@wojtekn,
> then customer object is saved a couple times

Such problem is not observed when customer is saved using `CustomerRepository`.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @wojtekn, Hi @orlangur  thank you for your report, in first time when i run this on console command i'm have false, but another time always return true, so problem with registry, when you load customer from repository you have no choise to load from.
![selection_215](https://user-images.githubusercontent.com/40756439/48936424-93546980-ef13-11e8-936d-3a697f0094e5.png)

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96607`, `MAGETWO-96608` were created

**Comment by orlangur** [comment]
@engcom-backlog-nazar correct, I noticed from `subscribeCustomerById` implementation that there is no way customer instance may be reloaded. What I was saying is that it is quite easy to circumvent in third-party code.

**Comment by ghost** [comment]
@orlangur we need some additional options like in productRepository force Reload = true.
![selection_216](https://user-images.githubusercontent.com/40756439/48936718-70768500-ef14-11e8-9736-9e8c0c46955c.png)

**Comment by orlangur** [comment]
@engcom-backlog-nazar introducing such flags is _really_ lame. It would be better if invalidation occurs somewhere inside `subscribeCustomerById`, we already have `push` method to achieve this.

**Comment by wojtekn** [comment]
@engcom-backlog-nazar I think changing getById implementation to preserve extension attributes also makes sense. It wouldn't solve my use case, but it would fix other ones. Eg. I could write plugin for subscribeCustomerById and fill extension attribute there instead of removing this variable caching in the core file patch.

@orlangur it makes sense IMO.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-24525` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#32254 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [c2b038e42c0e678440d151cc5f835e96eeb83e2f](https://github.com/magento/magento2/commit/c2b038e42c0e678440d151cc5f835e96eeb83e2f)
 - [8a90819df3ee53f9d0b45fb6aa1b5ac5e56cb769](https://github.com/magento/magento2/commit/8a90819df3ee53f9d0b45fb6aa1b5ac5e56cb769)
 - [6df702e2e81252fdf1795e490036a77b7fff8c34](https://github.com/magento/magento2/commit/6df702e2e81252fdf1795e490036a77b7fff8c34)
 - [c6e170e7ecac170b8f43e051992fa9f581b3b384](https://github.com/magento/magento2/commit/c6e170e7ecac170b8f43e051992fa9f581b3b384)
 - [b1f9f8eb61b0b2810c4b7eb66d7e068819053ed4](https://github.com/magento/magento2/commit/b1f9f8eb61b0b2810c4b7eb66d7e068819053ed4)
 - [a82f3e96693be0d330a966967c776cd110a14626](https://github.com/magento/magento2/commit/a82f3e96693be0d330a966967c776cd110a14626)

The fix will be available with the upcoming 2.4.3 release.
