### ISSUE TITLE
CSV Product import failure - URL key for specified store already exists

### ISSUE THREAD

**Issue by tookuul-owner** [magento/magento2#19367]
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Create 2 websites, lets call them Site1 and Site2
2. Create separate root categories for each site, lets call them Root1 and Root2
3. Attempt to import a product with CSV file, assigning it to subcategories with the same names, for example:
Root1/MySub/MySubSub
Root2/MySub/MySubSub

### Expected result (*)

1. The new subcategories categories are created under the existing root categories

### Actual result (*)

1. Import fails and shows this error:

```
Category " has not been created. URL key for specified store already exists. in row(s): 1
General system exception happened
Additional data:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`eurobeautiful_dev`.`catalog_category_product`, CONSTRAINT `CAT_CTGR_PRD_CTGR_ID_CAT_CTGR_ENTT_ENTT_ID` FOREIGN KEY (`category_id`) REFERENCES `catalog_category_entity` (`entity_id`) ON DELETE), query was: INSERT INTO `catalog_category_product` (`product_id`,`category_id`,`position`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?) ON DUPLICATE KEY UPDATE `product_id` = VALUES(`product_id`), `category_id` = VALUES(`category_id`)
```

Note: I have checked that the CSV is formatted correctly. I have been able to import when I remove categories that have the "duplicate" categories.

**Comment by magento-engcom-team** [comment]
Hi @tookuul-owner. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tookuul-owner do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tookuul-owner** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @tookuul-owner. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @tookuul-owner, here is your [Magento instance](https://i-19367-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19367-2-2-6.instances.magento-community.engineering/admin](https://i-19367-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tookuul-owner** [comment]
I am not able to reproduce in vanilla instance. Thank you!
