### ISSUE TITLE
Links once created not deleted from The Links Section in Downloadable products

### ISSUE THREAD

**Issue by ansari-ziyaurrahman** [magento/magento2#19386]
### Preconditions (*)

1. Magento version 2.2.6
2.

### Steps to reproduce (*)

1.Create a new Downloadable product.
2.Create a Link select with file type url. Create a Sample link with file type url.
3. Save product
4. Now try to delete links only do not delete sample link and save product again.
5. After save links reappearing.

### Expected result (*)

1. https://drive.google.com/file/d/1sbvE1f4xxzT0ieXXdEueYcg3oJgFJV5y/view?usp=drivesdk
2. Link from the links section should be deleted.

### Actual result (*)

1. Link from the links section is not deleted upon save.
2.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ansari-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ansari-ziyaurrahman** [comment]
Hi @orlangur 
Thanks for review this issue.
I have to say that  #19150 and #19389 both have different issues. Look at once it show similar but they have different files. Sure patch are same in both issues but they are in different files. First issue in sample links section (#19150 ) and this issue in Links section issue. Please let me know if you have any confusion.
Thanks.
