### ISSUE TITLE
Sales admin new order with configurable product selection of options design issue

### ISSUE THREAD

**Issue by jignesh26** [magento/magento2#19380]
### Preconditions (*)

1. Magento 2.2 Develop Vanilla version

### Steps to reproduce (*)

1. Create New order from admin
2. Add configurable product and try to select options you will see misalignment of qty box.

### Expected result (*)

![expected_result](https://user-images.githubusercontent.com/21121564/48967775-c843e780-f00b-11e8-9200-b3b41c8503e1.png)

### Actual result (*)

![actual_result](https://user-images.githubusercontent.com/21121564/48967779-d2fe7c80-f00b-11e8-8128-965e29d812d5.png)

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jignesh26 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by jignesh26** [comment]
@magento-engcom-team give me 2.3 develope instance

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for your request. I'm working on Magento 2.3 develope instance for you

**Comment by SyntaxKay** [comment]
Hi @jignesh26 
I have reproduce this issue in magento-2.3-develop branch and i am working on resolving it.

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97304` were created

**Comment by ghost** [comment]
HI @jignesh26 thank you for you report, i'm closing this, as this issue has already fixed in 2.3-develop branch.
