### ISSUE TITLE
When adding a new product, Magento does not save content which is drag&dropped.

### ISSUE THREAD

**Issue by pieterhollander** [magento/magento2#19401]
### Preconditions (*)

1. Magento 2.2.6
2. Ubuntu 17.10, Nginx, Varnish, Redis, MariaDB.

### Steps to reproduce (*)

1. Log in to admin, using Opera, Firefox, Chrome on Windows or macOS.
2. Open an article you want to use as a template for a new one
3. In a new window, open catalog -> product -> add product.
2. Drag and drop content (short description and description) and click save.

### Expected result (*)

1. Content is saved. Shop admin is happy.

### Actual result (*)

1. Please refer to this screencast (30 seconds): <https://youtu.be/zqjuIaNxntw>
2. Content is not saved. Shop admin is not happy.

### Additional information
NB: Using CMD+C, CMD+V does work. However, user is not comfortable doing this and dragging and dropping should render the same result. It does not matter whether the WYSIWYG editor is or is not used.

**Comment by magento-engcom-team** [comment]
Hi @phol. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@phol do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pieterhollander** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @phol. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @phol, here is your [Magento instance](https://i-19401-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19401-2-2-6.instances.magento-community.engineering/admin](https://i-19401-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pieterhollander** [comment]
Issue is confirmed on 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @phol  this can be a feature request, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by pieterhollander** [comment]
Why is this a feature request? It used to work in previous Magento versions, so I would therefore regard this as a bug.

**Comment by ghost** [comment]
The content is successfully saved after dragging the content and click on the area (short description or description). This is a browser specification.
