### ISSUE TITLE
Customer group auto-assign prevents data from being saved

### ISSUE THREAD

**Issue by stephan-cream** [magento/magento2#19432]
### Preconditions (*)
1. Any Magento 2.2.* version. **EDIT**: This was also tested on 2.3.0
2. Auto-assign of customer group based on an (in)valid VAT ID is enabled and configured.
3. PHP 7.0 (and tested with PHP 7.1 as well).
4. Clean install of Magento.

### Steps to reproduce (*)
1. Log into the backoffice and go to "Stores => Configuration => Customers => Customer Configuration.
2. Enable Automatic Assignment to Customer Group under "Create New Account Options".
3. Set a different customer group for a valid VAT ID and for an invalid VAT ID.
e.g: Group for Valid VAT ID - Domestic = Retailer, Group for Invalid VAT ID = General.
4. Create a new account on the frontend and create an address with an invalid VAT ID.
5. Check the new customer group in the backoffice (customer should be General).
6. Enter a valid VAT ID for the customer in the existing address and some other changes to the account like the firstname and save the customer.
7. Check the customer group and check the VAT ID.

### Expected result (*)
1. Customer group is changed accordingly to Retailer.
2. VAT ID is properly updated.
3. Other customer data is properly updated.

### Actual result (*)
1. Customer group is changed accordingly to Retailer.
2. VAT ID is **_not_** updated (old value remains).
3. Other customer data is **_not_** updated (old values remain).

### Additional information on the possible cause (*)
1. Try making the same changes again and save the customer.
Result: The new data is now saved, the customer group remains Retailer (as a valid VAT ID is provided).
2. Change the customer group to General and save the customer.
Result: The customer group is now General.
3. Save the customer again.
Result: The customer group is now Retailer.
4. Enter an invalid VAT ID and save the customer.
Result: The customer group is now General, the new VAT ID is **_not_** saved.
5. Save the customer again.
Result: The customer group is now Retailer (because of the old valid VAT ID).

This would suggest any data being saved during the auto-change of the customer group other than the group change itself is ignored completely and not updated in the database.

**Comment by magento-engcom-team** [comment]
Hi @stephan-cream. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@stephan-cream do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @stephan-cream. Thanks for the report. I'm not able to reproduce following steps your described, but I get the following results:
1. Customer group is **_not_** changed accordingly to Retailer.
2. VAT ID is properly updated.
3. Other customer data is properly updated.

**Comment by ghost** [comment]
Please look -> #19497

**Comment by stephan-cream** [comment]
Please watch the screencapture movie that i uploaded https://takeafile.com/?f=virurajuhu.
It displays all the steps and the situations.
This was tested with 2.3.0 (just in case) and is still existing there.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-19432-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19432-2-3-0.instances.magento-community.engineering/admin](https://i-19432-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-19432-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19432-2-2-develop.instances.magento-community.engineering/admin](https://i-19432-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97262`, `MAGETWO-97263` were created

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @ankur-cedcoss. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by verma-ankur** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ankur-cedcoss. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by verma-ankur** [comment]
I am working on it #MM19IN

**Comment by engcom-Kilo** [comment]
Hello @stephan-cream 
Thanks for your report. I'm not able to reproduce this issue on 2.4-develop.
In case you still facing this issue please feel free to create new one.
![CustomerAutogroup](https://user-images.githubusercontent.com/60192090/114865149-872a1900-9dfa-11eb-975c-8c6d1e577750.gif)

**Comment by magento-engcom-team** [comment]
Hi @stephan-cream, @engcom-Kilo. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24500` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
