### ISSUE TITLE
CE 2.3.0 And CE 2.2.7 - Issue can't install via Xampp - Window 10

### ISSUE THREAD

**Issue by tuongnv-ub** [magento/magento2#19444]
### Preconditions (*)
1. Magento CE 2.2.7
2. Magento CE 2.3.0
3. Window 10 OS
4. PHP Version 7.1.22

### Steps to reproduce (*)
1. Install from Localhost using Xampp Latest support Magento 2.3

### Expected result (*)
1. Front-end and backend to show.

### Actual result (*)
1. Front-end not show
2. Backend not show
3. I check the log and see the issue from JS.
[Screenshot] https://www.dropbox.com/s/fal18azmt4xjo28/2018-11-29_09-46-57.png?dl=0

**Comment by magento-engcom-team** [comment]
Hi @tuongnv-ub. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tuongnv-ub do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by minhluan259** [comment]
Same issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @tuongnv-ub    thank you for you report, i'm not able to reproduce following steps you described 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by bleenders** [comment]
I am experiencing the same problem on Windows 10. I am not with XAMPP but Apache 2.4 and PHP installed separately.

**Summary of the issue**
On clean installs of 2.2.7 & 2.3.0 and also on an upgraded installation (2.2.6 => 2.2.7) require.js seems to fail.
Require.js is getting fetched without a problem.
http://localhost/pub/static/version1543498691/frontend/Magento/luma/en_US/requirejs/require.js
But files being fetched by require.js are being fetched from a wrong path:
http://localhost/jquery.js
http://localhost/jquery/jquery.mobile.custom.js
http://localhost/mage/dataPost.js
http://localhost/mage/bootstrap.js
http://localhost/mage/translate-inline.js
http://localhost/Magento_Theme/js/responsive.js
http://localhost/Magento_Theme/js/theme.js

[Screenshot](https://imgur.com/a/Gk4wY8z)
This screen shot is taken from a clean install of 2.3.0 without any extensions or theme's installed. But the exact same thing happens with a clean install of 2.2.7 and an upgraded installation 2.2.6 => 2.2.7

**Information on your environment**
OS: Windows 10
Webserver: Apache 2.4
PHP: I tried 7.1.13 - 7.1.24 - 7.2.12 all with the same result(did not try 7.2.12 on the 2.2.7 installations)

**Steps to reproduce**
Download the 2.3.0 ZIP file from magento.com and install it using the Setup Wizard.
Download the 2.2.7 ZIP file from magento.com and install it using the Setup Wizard.
Upgrade 2.2.6 to 2.2.7 using the CLI as described in the [documentation](https://devdocs.magento.com/guides/v2.2/comp-mgr/cli/cli-upgrade.html).

**Expected and actual results**
I expected to have a working clean installation. The actual result is described above.

**EDIT**
I just setup a VirtualBox with Ubuntu 18.04 - Nginx/Apache - PHP 7.2.12 installed. Mounted it on the same location as the 2.3.0 installation and all the problems instantly disapeared. It seems to be a conflict with require.js in combination with Windows 10.
