### ISSUE TITLE
Duplicate key name 'AMAZON_QUOTE_QUOTE_ID' - Magento 2.3.0-beta32 upgrade to Magento 2.3.0 

### ISSUE THREAD

**Issue by evodus** [magento/magento2#19440]
### Preconditions (*)

1. 2.3.0-beta32
2. Ubuntu 18 + nginx + php7.1 + fpm + percona5.7

### Steps to reproduce (*)

1. Exist magento 2.3-beta32 clean install
2. composer require magento/product-community-edition=2.3.0 --no-update
3. composer update
4. Cleared caches
5. php bin/magento setup:upgrade

### Expected result (*)

1. Magento must upgrade database

### Actual result (*)

1.  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'AMAZON_QUOTE_QUOTE_ID', query was: ALTER TABLE `amazon_quote` ADD CONSTRAINT `AMAZON_QUOTE_QUOTE_ID` UNIQUE KEY (`quote_id`)
![screen shot 2018-11-29 at 00 56 07](https://user-images.githubusercontent.com/36575297/49187925-b2b72080-f371-11e8-870a-68573b94fc2c.png)

**Comment by magento-engcom-team** [comment]
Hi @evodus. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@evodus do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by adaudenthun** [comment]
I have the same issue

**Comment by ghost** [comment]
Hi @evodus Thank you for you report, i'm closing this as this occurs only with beta version, beta version is not release :)

**Comment by importwholesales** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'AMAZON_QUOTE_QUOTE_ID', query was: ALTER TABLE `amazon_quote` ADD CONSTRAINT `AMAZON_QUOTE_QUOTE_ID` UNIQUE K                                  EY (`quote_id`)

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'AMAZON_SALES_ORDER_ORDER_ID', query was: ALTER TABLE `amazon_sales_order` ADD CONSTRAINT `AMAZON_SALES_ORDER_ORDER_ID` UNIQUE KEY (`order_id`)

to fix
login to your database 
and rename or remove the two keys 
It will work after

Table 
amazon_sales_order - rename AMAZON_SALES_ORDER_ORDER_ID to AMAZON_SALES_ORDER_ORDER_ID2
amazon_quote - rename AMAZON_QUOTE_QUOTE_ID to AMAZON_QUOTE_QUOTE_ID2

**Comment by yosoyfunes** [comment]
```
ALTER TABLE `amazon_sales_order` RENAME INDEX AMAZON_SALES_ORDER_ORDER_ID to AMAZON_SALES_ORDER_ORDER_ID2
````
```
ALTER TABLE `amazon_quote` RENAME INDEX AMAZON_QUOTE_QUOTE_ID to AMAZON_QUOTE_QUOTE_ID2
```

it worked for me.

Thanks @importwholesales

**Comment by MichaelThessel** [comment]
Looks like older versions of MySQL (<5.7) don't support `RENAME INDEX`. Dropping the indexes and running `setup:upgrade` does the trick as well.

```
alter table amazon_sales_order drop foreign key AMAZON_SALES_ORDER_ORDER_ID_SALES_ORDER_ENTITY_ID;
alter table amazon_sales_order drop index AMAZON_SALES_ORDER_ORDER_ID;           
alter table amazon_quote drop foreign key AMAZON_QUOTE_QUOTE_ID_QUOTE_ENTITY_ID; 
alter table amazon_quote drop index AMAZON_QUOTE_QUOTE_ID;    
```
