### ISSUE TITLE
wrong php version in app/bootstrap.php

### ISSUE THREAD

**Issue by fballiano** [magento/magento2#19453]
### Summary (*)
By mistake I was trying to run M2.3.0 on a PHP5, and the system told me "Magento supports PHP 7.0.2, 7.0.4, and 7.0.6 or later. Please read Magento System Requirements." which is wrong because minimum php version for 2.3 is 7.1.3 https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

### Examples (*)
"Magento supports PHP 7.0.2, 7.0.4, and 7.0.6 or later. Please read Magento System Requirements."

### Proposed solution

going to create a PR as soon as possible

**Comment by magento-engcom-team** [comment]
Hi @fballiano. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@fballiano do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by fballiano** [comment]
This is the PR: https://github.com/magento/magento2/pull/19455

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96735` were created

**Comment by magento-engcom-team** [comment]
Hi @fballiano. Thank you for your report. 
The issue has been fixed in magento/magento2#19455 by @fballiano in 2.3-develop branch
Related commit(s):
 - [8f22688c3129b973c2bfce69f5871fec1fbcbc92](https://github.com/magento/magento2/commit/8f22688c3129b973c2bfce69f5871fec1fbcbc92)
 - [381c3a04b114c14e442157747b2ab90834104753](https://github.com/magento/magento2/commit/381c3a04b114c14e442157747b2ab90834104753)
 - [ebce9f357021babb30fcffe01cc8ae7bfbdfe8d9](https://github.com/magento/magento2/commit/ebce9f357021babb30fcffe01cc8ae7bfbdfe8d9)

The fix will be available with the upcoming 2.3.1 release.
