### ISSUE TITLE
Bundle Items not displaying in admin product edit section

### ISSUE THREAD

**Issue by sneha-panchal** [magento/magento2#19457]
Bundle items not displaying in Admin Product edit.
### Preconditions (*)

1. Magento 2.3.0
2. sample data

### Steps to reproduce (*)

1. Open and edit this product Sprite Yoga Companion Kit (SKU : 24-WG080) (Bundle Product) on its own

### Expected result (*)

1. All associated Bundle Items need to disaply

### Actual result (*)

1. Bundle Items tab is not displaying

![sprite yoga companion kit products inventory catalog magento admin 1](https://user-images.githubusercontent.com/29649994/49221690-d3c65280-f3ff-11e8-887e-13e2f9c21128.png)

**Comment by magento-engcom-team** [comment]
Hi @sneha-panchal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sneha-panchal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @sneha-panchal. Thanks for the report. i'm not able to reproduce following steps you described. Bundle Items tab is displaying. My result: 
![bundle](https://user-images.githubusercontent.com/41946904/49222665-234b5500-f3e5-11e8-93eb-9c9cdcac2e0a.png)

**Comment by himanshu8dev** [comment]
I am facing the same issue as described above step
I have installed sample data & edited "24-WG080" main bundle product but `Bundle Items` TAB is not showing.

If It Is working then let me know the step to follow for showing `bundle item tab` 
else please re-open this issue.

**Comment by PierreLeMaguer** [comment]
I am facing the same issue as described above step
I have installed sample data & edited "24-WG080" main bundle product but Bundle Items TAB is not showing.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @himanshu8dev this problem maybe related to your custom modules or some else, i''m have clean 2.3.0 instance with sample data and i have Bundled items tab.
![selection_274](https://user-images.githubusercontent.com/40756439/51378510-1827c200-1b16-11e9-9b7b-3b472e3f4002.png)

**Comment by mohammadbharmal** [comment]
I think you have removed the bundle attribute group from the attribute set.
![image](https://user-images.githubusercontent.com/73457616/97541538-57718b00-19eb-11eb-8f55-f9fd641abb9e.png)
