### ISSUE TITLE
Make State/Province required field in checkout view

### ISSUE THREAD

**Issue by woliu** [magento/magento2#19452]
### Preconditions (*)

1.Magento 2.2.6
### Steps to reproduce (*)

1.I have specified "State" field as mandatory for customer address for my Country (United States) from Admin.
Stores > Setting Configuration > General > General > Country Options > State Options > State is Required for.
2.when I visit the url(http:://klipsch.com/checkout/cart),I find the State/Province is not required.
3.I try to add code in /var/www/html/klipsch/vendor/magento/module-checkout/view/frontend/layout/checkout_cart_index.xml
`   <item name="region_id" xsi:type="array">
         <item name="component" xsi:type="string">Magento_Ui/js/form/element/region</item>
         <item name="sortOrder" xsi:type="string">112</item>
         <item name="config" xsi:type="array">
         <item name="template" xsi:type="string">ui/form/field</item>
         <item name="elementTmpl" xsi:type="string">ui/form/element/select</item>
         <item name="customEntry" xsi:type="string">shippingAddress.region</item>
         </item>
              <item name="validation" xsi:type="array">
                 <item name="required-entry" xsi:type="boolean">true</item>
         </item>
         
         <item name="filterBy" xsi:type="array">
         <item name="target" xsi:type="string"><![CDATA[${ $.provider }:${ $.parentScope }.country_id]]></item>
         <item name="field" xsi:type="string">country_id</item>
         </item>
   </item>`
![1543486146 2](https://user-images.githubusercontent.com/11054138/49215399-ad0a1b00-f403-11e8-9ee8-1f594115380c.jpg)
4.the result is the same as before.
### Expected result (*)

![1543486146 1](https://user-images.githubusercontent.com/11054138/49215471-d460e800-f403-11e8-87c8-fc477d4e0a93.jpg)
![1543486146](https://user-images.githubusercontent.com/11054138/49215418-b8f5dd00-f403-11e8-9b0a-c545b9b7fb5d.jpg)

### Actual result (*)

1. Since 'State' is not shown as required, customer is able to create address without the state. it's not friendly.

**Comment by magento-engcom-team** [comment]
Hi @woliu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@woliu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @woliu. Thanks for the report. This page does not provide such validation. Validation must be on the shipping page. This can be a feature request, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by woliu** [comment]
if i want to add validation in checkout page, what can i do?

**Comment by claudioxu** [comment]
@woliu 

The validation already exists in checkout page, need not do anything, it just can not work in cart page (estimate shipping)
