### ISSUE TITLE
Making payment not possible after upgrading 2.2.5 to 2.2.6

### ISSUE THREAD

**Issue by LSchonewille** [magento/magento2#19468]
### Preconditions (*)
1. We've got two shops, one started as installation on 2.2.6, the other one started as 2.2.5. We've upgraded one shop from 2.2.5 to 2.2.6. The first store (started on 2.2.6) payments are going great. The second store; in configuration and extension use exactly the same as the first store, all payments fail with error "An error occurred on the server. Please try to place the order again."

### Steps to reproduce (*)
1. Install M2 version 2.2.5
2. Upgrade to 2.2.6 using composer
3. Try to make any payment (on my case Klarna, Sisow and Afterpay all failing)

### Expected result (*)
1. Success page on payment and order ID

### Actual result (*)
1. Error "An error occurred on the server. Please try to place the order again.".

So just to be clear, we've got two shops with identical configuration and identical extension use. The first shop is 2.2.6 and the second shop was 2.2.5 and upgraded to 2.2.6. The problems are only active on the last shop. I cannot find any thread explaining how this can happen or I can fix the issue.

**Comment by magento-engcom-team** [comment]
Hi @LSchonewille. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LSchonewille do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by LSchonewille** [comment]
Issue can be closed. It's caused by een certificate issue from an third-party extension. With all the credits to the M2 contributors that have helped me out on this one.

**Comment by ghost** [comment]
@LSchonewille ok thanks.
