### ISSUE TITLE
Cannot upgrade from 2.2.6 to 2.3.0 with sample data

### ISSUE THREAD

**Issue by treestonemedia** [magento/magento2#19464]
### Preconditions

1. Currently on Magento 2.2.6
2. Installed via composer
3. Using the sample data module

### Steps to reproduce

1. Ran through the steps outlined in [Magento dev docs for command line upgrade](https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html)
2. run `composer update`

### Expected result 

1.  composer successfully updates

### Actual result

	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
		- magento/module-wishlist-sample-data 100.2.0 requires magento/module-wishlist 101.0.* -> satisfiable by magento/module-wishlist[101.0.4, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.5].
		- magento/module-wishlist-sample-data 100.2.0 requires magento/module-wishlist 101.0.* -> satisfiable by magento/module-wishlist[101.0.4, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.5].
		- Can only install one of: magento/module-wishlist[101.1.0, 101.0.4].
		- Can only install one of: magento/module-wishlist[101.1.0, 101.0.0].
		- Can only install one of: magento/module-wishlist[101.1.0, 101.0.1].
		- Can only install one of: magento/module-wishlist[101.1.0, 101.0.2].
		- Can only install one of: magento/module-wishlist[101.1.0, 101.0.3].
		- Can only install one of: magento/module-wishlist[101.1.0, 101.0.4].
		- Can only install one of: magento/module-wishlist[101.1.0, 101.0.5].
		- magento/product-community-edition 2.3.0 requires magento/module-wishlist 101.1.0 -> satisfiable by magento/module-wishlist[101.1.0].
		- Installation request for magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0].
		- Installation request for magento/module-wishlist-sample-data 100.2.* -> satisfiable by magento/module-wishlist-sample-data[100.2.0].

**Comment by magento-engcom-team** [comment]
Hi @treestonemedia. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@treestonemedia do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by treestonemedia** [comment]
@magento-engcom-team 

- The summary of the issue is that I cannot upgrade
- My environment is a clean vanilla Magento 2.2.6 running on PHP 7.1 that was installed via composer and using the sample data module.
- I provided clear steps to reproduce.
- I provided expected and actual results.

I confirm that I was able to reproduce the issue on vanilla Magento instance following steps to reproduce

**Comment by larsroettig** [comment]
@treestonemedia duplicated by #19446

**Comment by treestonemedia** [comment]
@larsroettig it's actually not a duplicate - my issue is because of sample data

**Comment by treestonemedia** [comment]
The issue was the sample data - if you have sample data installed then first run `php bin/magento sampledata:remove`

Thanks to Alan Storm!
