### ISSUE TITLE
duplicate on (multi)select attribute breaks validation

### ISSUE THREAD

**Issue by Schrank** [magento/magento2#19465]
### Preconditions (*)
Demo build on the demo store of basecom: https://www.basecom.de/magento2/demo
Magento Ver.-2.2.6

On (multi)select attributes it is possible to save duplicates. The validation is correct, but for some reason the list of options is hidden after validation and not validated again due to that.

### Steps to reproduce (*)
1. Open product attribute "activity"
2. add new option "Urban"
![image](https://user-images.githubusercontent.com/379680/49237959-b5f8ed80-f3ff-11e8-9d51-f2868b90883a.png)
![image](https://user-images.githubusercontent.com/379680/49237970-bee9bf00-f3ff-11e8-8200-faf5e1626b71.png)
3. Click on Save Attribute
4. Click a second time on "Save Attribute"

### Expected result (*)
1. Error is shown on the two options
2. List of options does not vanish
3. after correction the attribute is saved WITHOUT duplicate

### Actual result (*)
1. List of Attributes vanishes
![image](https://user-images.githubusercontent.com/379680/49238007-ce690800-f3ff-11e8-8e54-e8e8510325da.png)
2. See the error triangle on the tab on the left
3. The attribute is saved WITH duplicate

Might be connected to https://github.com/magento/magento2/issues/7646

**Comment by magento-engcom-team** [comment]
Hi @Schrank. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Schrank do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96743` were created

**Comment by dmytro-ch** [comment]
Hello @Schrank, thank you for the report.
I've reproduced the issue for latest Magento 2.2 version.
It also looks like the issue has been allready fixed for Magento 2.3.

**Comment by Schrank** [comment]
Good to read, thanks @dmytro-ch

**Comment by ghost** [comment]
Hi @dmytro-ch Will you create the pr to 2.2-dev ? or we can close as this was fixed in 2.3-develop ?

**Comment by Schrank** [comment]
I opt for option 1 :-)

If you have any indication (internal ticket number, external ticket number, ...) about the commit(s) which fixed the problem? Then I'm happy to send a PR (or fix it only in our install)

**Comment by dmytro-ch** [comment]
I've briefly checked the changes.

Here is the commits history for the `app/code/Magento/Catalog/view/adminhtml/web/js/options.js` file: https://github.com/magento/magento2/commits/2.3-develop/app/code/Magento/Catalog/view/adminhtml/web/js/options.js

Most likely, the issue has been fixed in the scope of the `MAGETWO-94819` and `MAGETWO-94962` internal tickets. There are a lot of changes done in many files.
https://github.com/magento/magento2/search?q=MAGETWO-94819&type=Commits
https://github.com/magento/magento2/search?q=MAGETWO-94962&type=Commits

The issue requires a deep investigation and we should also consider the bugs related to `MAGETWO-94819` and `MAGETWO-94962`.
Unfortunately, I'm not sure how soon I would be able to get to this issue. So volunteers are welcome. 😃

**Comment by Schrank** [comment]
Hey, just to get the current status... It is fixed in 2.3 and it won't get fixed in 2.2, correct?

Totally fine to me, just want to make sure we are on the same page.
