### ISSUE TITLE
2.2.6 Newsletter subscription management generates blank page

### ISSUE THREAD

**Issue by MicheleAlice** [magento/magento2#19460]
<! ---
Consult our guidelines before adding a new problem: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Fields marked with * are mandatory. Please do not remove the model.
->

### Preconditions (*)
<! ---
The magento version is 2.2.6
->
1.
2.

### Steps to Reproduce (*)
<! ---
The bug, so defined by the theme support, is located at the link https://www.coccinella.bio/newsletter/manage/ this link is located in the client's account precisely in the "Change" button for the subscription of the Newsletter . If the user is not logged into the home page, the newsletter subscription block appears, by entering the email and clicking on send Magento creates the subscription, logs the user and sends the confirmation email, but if the user logs in and wants to modify the subscription the link generates a blank page with the first error of missing the waypoints.js file. (see screen shot) if you switch on the Luma theme the same thing happens without any error from Google Chrome. Actually the file is missing in the path.
->
1.
2.

### Expected result (*)
<! --- I expect you to open a page where the user can change the subscription to the news letter. ->
1. [Screenshots, registers or description]
2.

### Current result (*)
<! --- currently opens a completely white page ->
1. [Screenshots, registers or description]
2.
![schermata 2018-11-29 alle 13 55 23](https://user-images.githubusercontent.com/45447242/49227905-7e337b00-f3ea-11e8-9066-98014b701ad1.png)

#13320

**Comment by magento-engcom-team** [comment]
Hi @MicheleAlice. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MicheleAlice do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @MicheleAlice 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
