### ISSUE TITLE
Compatibility issues between Magento 2.3.0 & Magento Marketplace EQP

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#19477]
### Preconditions
1. Magento 2.3.0 installed with composer
2. Require Marketplace EQP version 1.0.4 or later

### Steps to reproduce
1. Have a clean installation of Magento 2.3.0.
2. Add the Marketplace EQP requirement to the "require-dev" for "marketplace-eqp" version 1.0.4 or higher. I have included my composer.json file below.
3. Run the command: `composer update`

```
{
    "name": "creaminternet/magento-2-demo",
    "description": "Magento 2 Demo environment for Cream",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "magento/product-community-edition": "2.3.0",
        "creaminternet/magento2-setup": "@stable"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "~2.13.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento2-functional-testing-framework": "2.3.9",
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "3.3.1",
        "magento/marketplace-eqp": "~1.0.4"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "stable",
    "repositories": {
        "cream": {
            "type": "composer",
            "url": "https://repo.packagist.com/cream/"
        },
        "magento": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}
```

### Expected result
1. Newest release of Marketplace EQP can be installed

### Actual result
1. Composer throws an error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/marketplace-eqp 1.0.5 requires squizlabs/php_codesniffer 2.6.2 -> satisfiable by squizlabs/php_codesniffer[2.6.2] but these conflict with your requirements or minimum-stability.
    - magento/marketplace-eqp 1.0.4 requires squizlabs/php_codesniffer 2.6.2 -> satisfiable by squizlabs/php_codesniffer[2.6.2] but these conflict with your requirements or minimum-stability.
    - Installation request for magento/marketplace-eqp ~1.0.4 -> satisfiable by magento/marketplace-eqp[1.0.4, 1.0.5].
```

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dverkade do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by orlangur** [comment]
Hi @dverkade, you need to use 2.0.0 version of MEQP which looks like should be released pretty soon: https://github.com/magento/marketplace-eqp/pull/99/files

@lenaorobei any idea when 2.0.0 tag will become available?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96814` were created

**Comment by lenaorobei** [comment]
@dverkade we are preparing new MEQP `2.0.0` release now and updating our internal tools. At the beginning of next week all should be done. It will fix your issue.

**Comment by lenaorobei** [comment]
@dverkade `magento/marketplace-eqp 2.0.0` release is [available now on GitHub](https://github.com/magento/marketplace-eqp/releases/tag/2.0.0) as well as on repo.magento.com.
Please try `composer require magento/marketplace-eqp --dev`.

**Comment by dverkade** [comment]
@lenaorobei, I have added marketplace-eqp 2.0.0 to my repo which is now working fine in combination with squizlabs/php_codesniffer version 3.3.1. So I'm closing this issue since it has been resolved.
