### ISSUE TITLE
Magento 2.2.6 to 2.3.0 upgrade error - Cannot process definition to array for type enum

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#19479]
### Preconditions (*)
1. Magento 2.2.6 EE to
2. Magento 2.3.0 EE

### Steps to reproduce (*)
1. bin/magento setup:upgrade

### Expected result (*)
1. Upgrade to complete

### Actual result (*)
1. Error generated:

bin/magento setup:upgrade
```
Cache cleared successfully
File system cleanup:
/home/ccarnell/Sites/xx-uk2/generated/code/Amasty
/home/ccarnell/Sites/xx-uk2/generated/code/Bazaarvoice
/home/ccarnell/Sites/xx-uk2/generated/code/Composer
/home/ccarnell/Sites/xx-uk2/generated/code/MSP
/home/ccarnell/Sites/xx-uk2/generated/code/Magento
/home/ccarnell/Sites/xx-uk2/generated/code/Migration
/home/ccarnell/Sites/xx-uk2/generated/code/Mirasvit
/home/ccarnell/Sites/xx-uk2/generated/code/Symfony
/home/ccarnell/Sites/xx-uk2/generated/code/VaxLtd
The directory '/xx-uk2/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
Cannot process definition to array for type enum
```

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment]
```
/home/ccarnell/Sites/xx-uk2/generated/code/Amasty
/home/ccarnell/Sites/xx-uk2/generated/code/Bazaarvoice
...
/home/ccarnell/Sites/xx-uk2/generated/code/Mirasvit
```

@craigcarnell does not look like you have a vanilla Magento 2 instance :)

I doubt "Cannot process definition to array for type enum" is enough information for investigation, can you provide an isolated case for a clean Magento installation maybe?

**Comment by cscd98** [comment]
@orlangur Perhaps the error reporting in Magento logs should be improved? They don't provide enough information.

**Comment by ghost** [comment]
Hi @craigcarnell. I'm not able to reproduce following steps you described.
Thanks for the report.

**Comment by orlangur** [comment]
@craigcarnell probably yes. Did you post the full log? So, it does not say in which extension the problem occurs?

Did you bother to update all third-party extensions to 2.3.x compatible version or disabled them?

**Comment by cscd98** [comment]
@orlangur 

This is what i've debugged so far:

```
Cannot process definition to array for type enum
vendor/magento/framework/Setup/Declaration/Schema/Db/DefinitionAggregator.php
line 58
(
    [name] => scope
    [default] => 
    [type] => enum
    [nullable] => 1
    [definition] => enum('global','website','group','view')
    [extra] => 
    [comment] => 
)
```

How am I supposed to debug which extension?

**Comment by orlangur** [comment]
@craigcarnell cannot look into the code at the moment.

As this is a definition aggregator, you need to find out which particular definition is causing trouble. Each definition comes from a concrete extension.

**Comment by cscd98** [comment]
@orlangur I've now disabled all our own custom modules and all those we have supplied by external companies in config.php. Cleared cache. Same issue. 

```
bazaarvoice_index_product
Cannot process definition to array for type enum Array
(
    [name] => scope
    [default] => 
    [type] => enum
    [nullable] => 1
    [definition] => enum('global','website','group','view')
    [extra] => 
    [comment] => 
)
```

However, I disabled this module in config.php ??

**Comment by cscd98** [comment]
@orlangur Certainly is this module, not Magento. Will bring it up with them for now. Thanks.

**Comment by cscd98** [comment]
https://github.com/bazaarvoice/magento2-extension/issues/45

**Comment by seyuf** [comment]
Similar error encountered on aurora dump to mysql rds aws.
magento2 2.3 error at setup upgrade:
```
Array
(
    [name] => Column_priv
    [default] => 
    [type] => set
    [nullable] => 0
    [definition] => set('Select','Insert','Update','References')
    [extra] => 
    [comment] => 
)
Cannot process definition to array for type set

```
`Column_priv` is an aws generate table.

**Comment by r-martins** [comment]
In order to reproduce/debug the erorr, I've added an `xdebug_break()` before the throw exception on \Magento\Framework\Setup\Declaration\Schema\Db\DefinitionAggregator::fromDefinition.
This way I was able to Xdebug and see the module that was causing the problem...
![debugging-it](https://user-images.githubusercontent.com/191149/53999323-1930b380-4197-11e9-86cb-a5882afaa6a4.jpg)

You may need to change the column types to text or varchar until someone create a DbDefinitionProcessor in vendor/magento/framework/Setup/Declaration/Schema/Db/MySQL/Definition/Columns.

I still don't know how this can impact modules with enum, tinytext, time, mediumtext, and other types.

**Comment by agata-maksymiuk** [comment]
For all coming here from google as me - this issue is caused by some custom modules.
Disabling (or even removing) module wouldn't work. It's issue with an existing table in database, not the code. You have to change column type in database.

**Comment by seyuf** [comment]
The issue here is that magento2 is unable to handle certain types encountered in the database.
Like in my case, some external table to magento created by aws. This is still linked to magento2 as there should be a mechanism to simply discard the table/column in question or just throw a warning instead of a critical error like it is the case today.

**Comment by daniel-kratohvil** [comment]
In my case the issue was caused by the "pma__tracking" table created by PhpMyAdmin (in a local installation). I had to delete those pma__xxx tables to be able to complete the setup:upgrade. Definitely a Magento bug IMHO.

**Comment by QuentinFarizon** [comment]
At least the log must be improved.

**Comment by webspeaks** [comment]
To debug the faulty column, you can add `var_dump` in `/vendor/magento/framework/Setup/Declaration/Schema/Db/DefinitionAggregator.php` as below 

![image](https://user-images.githubusercontent.com/1465109/60702832-9ee22700-9f1d-11e9-8d4d-a6128e909860.png)

It will show you the incorrect column, so you can fix that column.
![image](https://user-images.githubusercontent.com/1465109/60702794-87a33980-9f1d-11e9-9073-31ed8a617aeb.png)

**Comment by dan-ding** [comment]
@orlangur, @engcom-backlog-tomash if magento isn't going to support a standard database column type, or any other standard of the softwares it uses, it should be documented, preferably well.  
no one is going to remember/find years old conversations about the enum column type or why magento barfs on it. https://github.com/magento/magento2/issues/9883

the documentation should also be changed to say -- that it is NOT fully compatible with maria/mysql/whatever. because, in this example, erring on the datatype IS breaking compatibility. which sorta makes it a magento bug while magento is declaring itself compatible.

**Comment by BlackRhinoMedia** [comment]
Hello everyone - this isn't limited to tables created by extensions this is also an issue if you have other tables sharing your M2 database - it is as if Magento goes through every table in the database regardless of whether it is associated with Magento2/an extension or not!

So for example if you had a wordpress installation in the same db as Magento I am confident this process will look through the wordpress tables.

**Comment by Jimgitsit** [comment]
Seems to me this issue was closed without a resolution. Isn't the fix here to add a definition processor for the unsupported data types (enum, tinytext, etc.)? I agree with @dan-ding that this is an issue with Magento not fully supporting MySQL.

**Comment by vipin12117** [comment]
Why this issue was closed even not solved ? Why error message does not give profile file or table name to fix ? I downloaded latest version today and faced that error.

**Comment by ivankristic** [comment]
what in the a**...??
why is this closed @craigcarnell ?
its just closed in the other issue as well

this is your damn bug.

1. get vanilla instance
2. create A table **directly** in DB with `enum` type column
3. watch how your magnificent framework breaks...

its ridiculous that it reads whole DB on setup:upgrade.
WHY?

i created audit table, because, guess what, theres smth buggy with magento and i needed to find exactly what changed so i could retrieve the values before i fix that bs.
and now IT BREAKS BECAUSE IM TRYING TO FIX YOUR MESS??

i should be able to impregnate my DB with spawns of Satan for all you care.

WHY are you reading my setup on your setup and fix this.

P.S. this is also going to all our EE clients affected by this, just so theyre aware what theyre paying for

**Comment by Jimgitsit** [comment]
Looks like the user that closed this had their account deleted. Any one at Magento got eyes on this issue anymore or are our comments going into the ether?

**Comment by ivankristic** [comment]
heck, sry @craigcarnell , i saw ghost being out and thought you took the assignment..

lets try like this @Jimgitsit 

@magento-team @ajijshekh123 @srsathish92 @vincent-le89 @pawankparmar @Usik2203 @ramesh-durairajaram @ilnytskyi @shikhamis11 @sergiy-v @viktym @sdzhepa 

hopefully thats enough

**Comment by ingedicson** [comment]
I had this message:

Cannot process definition to array for type bit

This is a new table that I created on Magento.
And my solutions was change data type to column, from bit to int.

Now, the command work correctly!  bin/magento setup:upgrade

**Comment by tschallacka** [comment]
For those that find this via google, to help you find out which things cause issues, change vendor/magento/framework/Setup/Declaration/Schema/Db/DefinitionAggregator.php in the fromDefinition, to give a meaningfull error message in the sprintf.

```php
public function fromDefinition(array $data)
    {
        $type = $data['type'];
        if (!isset($this->definitionProcessors[$type])) {
            throw new \InvalidArgumentException(
                sprintf("Cannot process definition to array for type '%s' in field '%s'. Run `SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE DATA_TYPE ='%s' and COLUMN_NAME='%s';` and change to to an appropriate type", $type, $data['name'], $type, $data['name'])
            );
        }
```

it will then give a meaningful error message and a copy paste solution to find out which table is causing the issues.

![image](https://user-images.githubusercontent.com/8638425/119649571-1297c080-be23-11eb-9be8-4978cc36f440.png)

**Comment by marcatos** [comment]
I stumbled upon the same error today, I share my experience to whom who could resolve in the same way. 
In my case the error was thrown because I accidentally imported non M2 tables on M2 database, it seems that Magento checks every table present on its database.

**Comment by francisco-serfe** [comment]
I just stumbled into this error after allowing PhpMyAdmin to write its tables into the `magento2` database, since I wasn't able to procure authorization to create a new database. 

Should we not be allowed to create tables on the same database as the Magento installation? An audit table as [this comment](https://github.com/magento/magento2/issues/19479#issuecomment-587652961) mentions sounds like a valid use case.
