### ISSUE TITLE
Show issue when turn on Developer Mode - CE 2.3.0

### ISSUE THREAD

**Issue by tuongnv-ub** [magento/magento2#19471]
### Preconditions (*)

1. Magento Version: CE 2.3.0
2.  PHP Version 7.1.22
3. XamPP Server Localhost
4. Window 10
5. Developer Mode
6. Show error mode

### Steps to reproduce (*)

1. Setup Magento Core CE 2.3.0 
2. See Front-end

### Expected result (*)

1. Show front-end without any issue.

### Actual result (*)

1. Show error issue https://www.dropbox.com/s/tm0h1w58nil7j83/2018-11-30_10-23-09.png?dl=0

**Comment by magento-engcom-team** [comment]
Hi @tuongnv-ub. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tuongnv-ub do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by phuongnd** [comment]
issue confirmed. We get the same issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment]
@tuongnv-ub,

> XamPP Server Localhost
> Windows 10

This is not a valid environment, please check https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by 00110000** [comment]
@orlangur But a LOT of people do their development work on windows.

This change is not deliberate; it's an error introduced by Magento and their Vagrant-only development ritual.

magento\framework\View\Element\Template\File\Validator.php
```
    /**
     * Checks whether path related to the directory
     *
     * @param string $path
     * @param string|array $directories
     * @return bool
     */
    protected function isPathInDirectories($path, $directories)
    {
        if (!is_array($directories)) {
            $directories = (array)$directories;
        }
        $realPath = $this->fileDriver->getRealPath($path);
        foreach ($directories as $directory) {
            if (0 === strpos($realPath, $directory)) {
                return true;
            }
        }
        return false;
    }
```

`$realPath` was added in 2.3.0 and does not return the expected slashes.

`$realPath = 'C:\Server\Apache24\htdocs\magento-2.3\vendor\magento\module-theme\view\frontend\templates\page\js\require_js.phtml'`
`$directory = 'C:/Server/Apache24/htdocs/magento-2.3/vendor/magento/module-theme'`

`strpos` cannot return 0 on Windows.

**Comment by orlangur** [comment]
@00110000,

> a LOT of people do their development work on windows

It means nothing but they do their development wrong and at their own risk. There are a lot of options nowadays, like Docker, Vagrant or other virtualization technics available for Windows.

Windows is not supported, was never supported and always led to some bugs. Patches for Windows compatibility are not acceptable in this repo.

The only thing Magento lacks here is proper environment check, similar to an unsupported PHP version check. Hope it will change soon.

**Comment by 00110000** [comment]
> but they do their development wrong

Yeah, my bad I forgot PHP was Linux only, you guys are the geniuses who do development RIGHT.

![image](https://user-images.githubusercontent.com/16885744/49289304-4a645e00-f49b-11e8-9361-d2d4bf5d0cb0.png)

>here are a lot of options nowadays, like Docker, Vagrant or other virtualization technics available for Windows.

These virtualisation "technics" are great for making contributions to Magento's core codebase, but fall short and make development tedious when creating multiple stores using Magento.

>Windows is not supported, was never supported and always led to some bugs. Patches for Windows compatibility are not acceptable in this repo.

These are your bugs. Why use a cross-platform language if you're going to keep reintroducing bugs that make it platform specific?

>The only thing Magento lacks here is proper environment check

And proper developers.

**Comment by ghost** [comment]
@tuongnv-ub  @00110000 -> https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by 00110000** [comment]
> @tuongnv-ub @00110000 -> https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

Yeah, I'm working on setting up Magento 2 via WSL right now.

I'm hoping it doesn't have the same permission issues when mounting to a Windows drive as Vagrant and Docker did (e.g. executable permissions in bin/magento)

**Comment by ghost** [comment]
@00110000 i'm know a guy, who works with WSL a long time, and have no issue with it. so this may be a good solution

**Comment by 00110000** [comment]
@engcom-backlog-nazar WSL is great! None of the limitations we experienced with vagrant and docker are here.

**Comment by tuongnv-ub** [comment]
@engcom-backlog-nazar , @00110000 . Thanks for sharing. I'm Setup and working with WSL as well.

**Comment by orlangur** [comment]
@engcom-backlog-nazar would be great to have such setup described somewhere in DevDocs for Windows guys. It would be much more friendly than just pointing to system requirements: https://github.com/magento/magento2/blob/2.3-develop/app/bootstrap.php#L17
