### ISSUE TITLE
Increase product quantity with disabled Manage Stock when place order is failed

### ISSUE THREAD

**Issue by iGerchak** [magento/magento2#19482]
After failed order, Magento increase product quantity, make reindex for this product and flush cache while in the product Manage Stock in disabled

### Preconditions
1. Magento 2.2.6
2. PayPal Express payment method

### Steps to reproduce
1. In the admin panel set for a product **Manage Stock: No** and **Quantity: 100**
2. Place an order with this product via PayPal, **but with a card that does not have enough money to pay for the order**

### Expected result
1. Product Quantity is **100**

### Actual result
1. Product Quantity is **101**

### Tech details
It happens becouse Catalog Inventory has event for `sales_model_service_quote_submit_failure`
how run `$this->stockManagement->revertProductsSale($items, $quote->getStore()->getWebsiteId());` where `$items` its all items from Quote
`revertProductsSale` make `correctItemsQty` (increase) for each items (include itemd with Manage Stock in disabled)

**Comment by magento-engcom-team** [comment]
Hi @iGerchak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@iGerchak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96891`, `MAGETWO-96892` were created

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @iGerchak. Thank you for your report. 
The issue has been fixed in magento/magento2#19997 by @agorbulin in 2.3-develop branch
Related commit(s):
 - [c608b021a28d6bd18c4d6b505f893abca5a20745](https://github.com/magento/magento2/commit/c608b021a28d6bd18c4d6b505f893abca5a20745)
 - [1a5a6be6d85599431ad55901417d44e75cf42907](https://github.com/magento/magento2/commit/1a5a6be6d85599431ad55901417d44e75cf42907)
 - [eb60f47f8a5686676aa47ec9b85878d0c3d4c84c](https://github.com/magento/magento2/commit/eb60f47f8a5686676aa47ec9b85878d0c3d4c84c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by ihor-sviziev** [comment]
Hi @agorbulin,
It's amazing to see this issue fixed! Thank you so much! Very important fix for websites under high load!

Because of this issue Inventory for product is changing time to time -->  it's causing product reindexing --> it's causing **flushing cache for this product**.

For best sellers flushing cache during big promos - really not expected thing.

**Comment by magento-engcom-team** [comment]
Hi @iGerchak. Thank you for your report. 
The issue has been fixed in magento/magento2#20644 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [abddea84f8aa4edf949c04663c9285ce5a24f489](https://github.com/magento/magento2/commit/abddea84f8aa4edf949c04663c9285ce5a24f489)
 - [5d38ec623a83128be1fcaade22e9418d12a6c8a0](https://github.com/magento/magento2/commit/5d38ec623a83128be1fcaade22e9418d12a6c8a0)
 - [582a1e7beee224839ee21b554d55c55af56f38e4](https://github.com/magento/magento2/commit/582a1e7beee224839ee21b554d55c55af56f38e4)

The fix will be available with the upcoming 2.2.9 release.
