### ISSUE TITLE
Magento 2.3. | Can't Access Web Setup Wizard | Welcome to Magento Admin, your online store headquarters. To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard

### ISSUE THREAD

**Issue by 3615helloworld** [magento/magento2#19491]
## Preconditions
Magento 2.3
 
## Steps to reproduce

1. Try to access Web Setup Wizard
 
## Expected result
Access to Web Setup Wizard

## Actual result
1. `?app=setup`  Response 302
2. `setup`            Response 301
3. `setup/`           Response 302
4. `setup/index.php/session/unlogin`     Response 401
 
Welcome to Magento Admin, your online store headquarters. To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard`

I am on Magento 2.3. I can't access web setup wizard. This issue was supposed to be fixed (see issue https://github.com/magento/magento2/issues/5247)

@tlc033 fix does not work for me. Did a genius managed to fix that? A step by step would be much appreciated!

> Solution for me was:
> Base URLs (Secure)
> -> Use Secure URLs on Storefront -> Yes
> -> Use Secure URLs in Admin -> Yes
> -> Enable HTTP Strict Transport Security (HSTS) -> Yes
> -> Upgrade Insecure Requests -> Yes
> php bin/magento cache:clean
> https://yadi.sk/i/iPJi4k7X3S86Za
> I SOLVE THIS.

Also, there is no /setup folder in my /pub directory. Does the Symlink solution would still work? @TechnoBuddhist

> What worked for me...

> ln -s [magento-install-dir]/setup [magento-install-dir]/pub/setup

> After installing mods/updates, remove the link

> rm [magento-install-dir]/setup

> If the symbolic link doesn't work for you, check permissions and ownership(mine was set to nobody - the apache.http user)

> chown [magento-user]:[magento-user] [magento-install-dir]/setup/*

> Hope this helps!

See issue: https://github.com/magento/magento2/issues/5247

**Comment by magento-engcom-team** [comment]
Hi @3615helloworld. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@3615helloworld do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by happydownload33** [comment]
Check your app/etc/env.php and look for 'session' => [ 
'save' => 
Is this standing on files or on db ?

If setting is db change it to files works for me in 2.2.6 version

(https://github.com/magento/magento2/issues/18182)

**Comment by 3615helloworld** [comment]
@happydownload33 Thanks for your help! Unfortunately it is on files

**Comment by 3615helloworld** [comment]
Ok you can close the issue. I fixed it. Solution for me was:
Base URLs (Secure)
-> Use Secure URLs on Storefront -> Yes
-> Use Secure URLs in Admin -> Yes
-> Enable HTTP Strict Transport Security (HSTS) -> Yes
-> Upgrade Insecure Requests -> Yes
php bin/magento cache:clean + **php bin/magento cache:flush**. 

If you do not do both or setup:upgrade instead, it will not work. Also, I don't know if it has an impact but I switched from default to developer mode.

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Nazar65** [comment]
Hi @3615helloworld, i'm  close this one as this is resolved.

**Comment by ammad-khan** [comment]
Hi @Nazar65 @magento-engcom-team same issue is persisting once install magento 2.3.x, changes have been done as prescribed but still same problem and redirecting to setup/index.php/session/unlogin

**Comment by Kashiffrq** [comment]
> 
> 
> Ok you can close the issue. I fixed it. Solution for me was:
> Base URLs (Secure)
> -> Use Secure URLs on Storefront -> Yes
> -> Use Secure URLs in Admin -> Yes
> -> Enable HTTP Strict Transport Security (HSTS) -> Yes
> -> Upgrade Insecure Requests -> Yes
> php bin/magento cache:clean + **php bin/magento cache:flush**.
> 
> If you do not do both or setup:upgrade instead, it will not work. Also, I don't know if it has an impact but I switched from default to developer mode.
highly recommended

**Comment by mostafa-elkholy** [comment]
I have magento 2.3.0 and when try to upgrade using the admin gives me ( Welcome to Magento Admin, your online store headquarters. 
To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard ) I have tried Kashiffrq solution but the same issue.

**Comment by Kashiffrq** [comment]
> 
> 
> I have magento 2.3.0 and when try to upgrade using the admin gives me ( Welcome to Magento Admin, your online store headquarters.
> To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard ) I have tried Kashiffrq solution but the same issue.

@mostafa-elkholy i had try on 2.2.6 it works for me

**Comment by vtransy** [comment]
Noted solution here:
https://mrvts.wordpress.com/2019/09/18/magento-2-2-2-web-setup-wizard-not-visible-in-backend/

**Comment by soopermouse** [comment]
this is still not fixed.
Why are issues closed when they are still not solved?

**Comment by MariuHub** [comment]
Having same issue here. 
Is this solved or anyone has anything new on the issue?

**Comment by Solunsky** [comment]
Magento 2.3.4 Not fixed this problem....

**Comment by Sepremex** [comment]
This issue still there, I'm using:
Debian 10
apache 2, MariaDB, I was hopping I could use PHP7.4 but the installation told me NOT.. so 7.2 it is...
The server is a dedicated custom build...
aside from the other comments, on my case the only thing I got on the error log is:
`[Fri Feb 14 23:19:07.371332 2020] [proxy_fcgi:error] [pid 20303:tid 140677054547712] (70007)The timeout specified has expired: [client 127.0.0.1:53830] AH01075: Error dispatching request to : (polling)`
Other than that I go the same thing as the others...
