### ISSUE TITLE
Address update issue when using VAT id and automatic assignment to customer group.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#19497]
### Preconditions (*)

1. Magento CE 2.3.0
2. PHP 7.2.12

### Steps to reproduce (*)

**Change Magento settings:**

1. Change Magento settings:
2. Customers > Customer Configuration > Create New Account Options
3. Enable Automatic Assignment to Customer Group > yes
4. Tax Calculation Based On > Billing Address
5. Default Group > General
6. Group for Valid VAT ID - Domestic > Wholesale
7. Group for Valid VAT ID - Intra-Union > General
8. Group for Invalid VAT ID > Retailer
9. Validation Error Group > Retailer
10. Validate on Each Transaction > Yes
11. Default Value for Disable Automatic Group Changes Based on VAT ID > No
12. Show VAT Number on Storefront > Yes

**Steps:**

1. Log in as a customer
2. Go to "My Account" > "Address Book" > "Change Billing Address"
3. Enter valid "VAT Number" and select appropriate country, save address
4. Messages appear:
                     "Your VAT ID was successfully validated."
5. Then went to admin side and checked customer of that customer. Customer group was not update.

### Expected result (*)

1. [Screenshots, logs or description]
2.Customer group should be updated by automatic.

### Actual result (*)

1. [Screenshots, logs or description]
2. Customer group was not update automatic.

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96856`, `MAGETWO-96857` were created

**Comment by mallikaverma** [comment]
@emiprotech 
I have followed the steps which you have mentioned, customer group is being updated.

**I have just performed one extra step i.e running reindex command.**  
As after changing Customers > Customer Configuration > Create New Account Options , Customer grid indexes are being invalidated.

I have set Group for **Valid VAT ID - Intra-Union > Retailer so that I could differentiate between Default Group and Intra-Union group**. 

Then I have  edited address from Customer Account and changed it to **Belgium and added its Vat number**. After this **Customer group was changed to Retailer**(I have used Belgium because in Magento Admin I have set in European Union Countries = Belgium).

**Comment by magento-engcom-team** [comment]
Hi @ankur-cedcoss. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by verma-ankur** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ankur-cedcoss. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by verma-ankur** [comment]
@emiprotech and @engcom-backlog-tomash 
I followed the step mentioned above but was not able to reproduce it.

**Comment by othuress** [comment]
We are on Magento 2.3 and have this issue, Magento does not assign the correct customer gorup for valid VAT. Could be that it is just intra union VATs that is the problem. Magento might not handle DEXXXXX or ATUXXXXXX and assign a valid customer group based on that. 
Please see
https://magento.stackexchange.com/questions/123436/magento2-new-customer-assignment-to-group-for-valid-vat-id-doesnt-seem-to-work

@verma-ankur can you try again with a valid intra union VAT and see if you can reproduce this. I can otherwise make an video from our environment and you will see how it behave.
