### ISSUE TITLE
Tax Calculation is going wrong after applying coupon code in magento 2?

### ISSUE THREAD

**Issue by devqualwebs** [magento/magento2#19494]
### Preconditions (*)

1. Installed Magento v 2.1.7

### Steps to reproduce (*)

1. Created a Tax Class and Tax rule and applied it for a single country.
2. Selected this Tax Class in all products.
3. Put product price incl. tax for all products, and selected "Including Tax" in Configuration > Tax > Calculation Settings > Catalog Prices, and "Excluding Tax" in Configuration > Tax > Calculation Settings > Apply Discount On Prices.
4. Selected "Apply Customer Tax" to "After Discount" in Configuration > Tax > Calculation Settings . So tax will calculate after applying all the discounts.
5. Created One shopping cart price rule to apply 5% discount if payment method is "Credit Card"
6. Created One another shopping cart price rule to apply 10% discount for a specific coupon code.

**Now on Frontend Tax Calculation**
1. Selected the country which satisfy the tax rule condition. So it will add 5% tax.
2. Selected "Credit Card" payment method to get 5% discount.
3. Applied Coupon Code to get additional 10% discount.

### Expected result (*)

1. Product price is 100 excl. tax and 105 is put in admin section, with select 5% vat class.
2. On Calculation I'm getting 5% tax for that specific country, and which is right. 
3. On selecting "Credit Card" method as payment option, I'm getting 5% Discount, say for ex. the ** product price excl tax. - 5% dicount for credit card ** so it will 100 - 5 = 95. Now Tax will calculate for 95. and I will get **4.76**. Which is 5% of 95. That is also right thing.
4. Now If I will apply Coupon code to get extra 10% discount. I'm getting tax **4.76** again. But the discount is applying.

### Actual result (*)

1. Since I've selected **"Apply Customer Tax" to "After Discount" in Configuration > Tax > Calculation Settings** ,  then it means my tax will calculate in the end, first all discount will be calculate, But here I'm getting like 5% discount for credit card, then tax calculation, and the 10% dicount for coupon code.

It should be like apply all discount and then calculate the tax like 100 - 5 = 95 , 95 - 10 = 85 and then tax calculation for 85. But It's applying tax for the amount of 95.

Also I'm providing secreenshow for the configuration settings and the result in frontend.

[Here is the link for calculation settings](https://www.awesomescreenshot.com/image/3766708/124926476593b056d85e28cceb714ffd)

[Here is the link for result which I'm getting on frontend](https://www.awesomescreenshot.com/image/3766711/9e88d1fd01b544d56d73b0ab9f0b4b0a)

**Comment by magento-engcom-team** [comment]
Hi @devqualwebs. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@devqualwebs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by devqualwebs** [comment]
> Hi @devqualwebs. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @devqualwebs do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no

**Yes I'm able to reproduce the issue.**

**Comment by orlangur** [comment]
@devqualwebs,

> where $VERSION is version tags (starting from 2.2.0+) or develop branches (for example: 2.3-develop)

Note that it is too late to report 2.1.x issues.

**Comment by altafhussain10** [comment]
@devqualwebs this is a known issue in magento 2.1.x and and until 2.2.6 and I am not sure about version after that. I was facing this issue for a very long time and was not sure why it is happening. 
After some more research and digging into quote tables and tax calculations, I found two reasons for this issue. Both issues are coming from `\Magento\Tax\Model\Calculation\UnitBaseCalculator` in the method `calculateWithTaxInPrice`.

- Magento applies a another tax called `discount_compensation_tax_amount` which is applied on each item in `quote_item` table. It is kinda hidden tax. Some details a few years old can be found here https://stackoverflow.com/questions/28614772/magento-what-is-hidden-tax-amount . If you check the above mentioned file you will find code as below:  

      `$unitDiscountTaxCompensationAmount = $uniTax - $unitTaxAfterDiscount;
       $discountTaxCompensationAmount = $unitDiscountTaxCompensationAmount * $quantity;`

   Now here the `$discountTaxCompensationAmount` value for a unit or item is calculated from    `ItemTax - ItemTaxAfterDiscount`, which means if your item has a tax of $5 and a tax of $4.75 after discount, then the value of `$discountTaxCompensationAmount` will be `5 - 4.75 = 0.25 * Qty in cart for the item` and it is saved is `discount_compensation_tax_amount` field for each item.
When Magento is calculating final grand totals and taxes, this `discount_compensation_tax_amount` is also added to it, which causes the taxes and grand totals differences. In our case, it was a wrong calculation and `discount_compensation_tax_amount` should be always 0.

- The second issue is coming in the same file and in same method. Magento calculates `$taxableAmount` and this is the amount on which the tax will be applied after discount. Now, in the code, this is how Magento is calculation in that file and method. 

   
      if ($applyTaxAfterDiscount) {
            //TODO: handle originalDiscountAmount
            $unitDiscountAmount = $discountAmount / $quantity;

            $taxableAmount = max($priceInclTax - $unitDiscountAmount, 0);

            . ..
            ...
            ...
         }

Now as can be seen above, if i am applying tax after discount, then why the taxable amount after discount si calculated from `$priceInclTax` . It should calculate the `$taxableAmount` from the price excluding tax. 

My issue was fixed by setting the `discount_compensation_tax_amount` to 0 and calculating the `$taxableAmount`  from `$price` instead.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by devqualwebs** [comment]
> discount_compensation_tax_amount

@altafhussain10 can you please let me know how can I set "discount_compensation_tax_amount" to 0 for every quote?

**Comment by ghost** [comment]
HI @devqualwebs how you create this attribute -> Created One shopping cart price rule to apply 5% discount if payment method is "Credit Card" ?

**Comment by ghost** [comment]
@devqualwebs,  thank you for your report.
"Payment method" Cart Price Rule condition is removed in actual Magento 2 versions.

**Comment by devqualwebs** [comment]
@engcom-backlog-nazar Please have a look [here](https://www.awesomescreenshot.com/image/3776978/1a65ba75334a1f675e88bdbf0e4fe282).
I'm able to use payment method in Cart price rules condition. And the rule also applying.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-19494-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19494-2-3-0.instances.magento-community.engineering/admin](https://i-19494-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@devqualwebs in this instance you don't have conditioner in Cart price rules
