### ISSUE TITLE
Multiselect attribute is not saving with plus(+) in value

### ISSUE THREAD

**Issue by amanuni** [magento/magento2#19506]
### Preconditions (*)

1. Magento 2.2.6
2. MariaDB 10.2.19-MariaDB - MariaDB Server
3. Linux

### Steps to reproduce (*)

1. Add a multi-select attribute for product from Store->Attribute->Product->Add New Attribute
2. Add a option value with plus symbol e.g. (+300)

### Expected result (*)

1. Expected option value will save with plus symbol e.g. (+300) but it saved as ( 300)

### Actual result (*)

1. Its saves option 300 instead of +300

**Comment by magento-engcom-team** [comment]
Hi @amanuni. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amanuni do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by amanuni** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @amanuni. Thank you for your request. I'm working on Magento 2.26 instance for you

**Comment by amanuni** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @amanuni. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @amanuni, here is your [Magento instance](https://i-19506-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19506-2-2-6.instances.magento-community.engineering/admin](https://i-19506-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amanuni** [comment]
@magento-engcom-team issue is confirmed i have tested on provided on above instance and it same its not saving + symbol in value. I have tested by creating a attribute name "Test Multiselect" and added two option value one is "-100" and another is "+200" first value saved correctly and and displaying "-100" after save however 2nd value "+200" is displaying "200" after save.

**Comment by magento-engcom-team** [comment]
Hi @omaxmo. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by omaxmo** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @omaxmo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @omaxmo, here is your [Magento instance](https://i-19506-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19506-2-3-develop.instances.magento-community.engineering/admin](https://i-19506-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by omaxmo** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @omaxmo. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @omaxmo, here is your [Magento instance](https://i-19506-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-19506-2-2-7.instances.magento-community.engineering/admin](https://i-19506-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by omaxmo** [comment]
issue is not reproducible on 2.2.7
issue is not reproducible on 2.3

**Comment by amanuni** [comment]
@omaxmo thank you it would be great if i am able to know which files are updated for fixing this issue.

**Comment by omaxmo** [comment]
#18263 #18493 https://github.com/magento/magento2/pull/18293#issuecomment-425209668
