### ISSUE TITLE
Catalog bundle product Bundle Items inconsistent box border 

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#19509]
### Preconditions (*)

1. Magento 2.3 Develop

### Steps to reproduce (*)

1. Admin -> Catalog -> Product -> add/edit (Bundle product) 
2. Bundle Items -> add options -> adding product
3. Collapsible title box border top  inconsistent

### Expected result (*)

1. Collapsible title box border should be equal width from all side.
2. Please find attached review : http://prntscr.com/lpcb1f

### Actual result (*)

1. Collapsible title box border top not equal in uniform, First box top border is thin and rest are thick.
2.  Please find attached review : https://prnt.sc/lpc4hd

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96859`, `MAGETWO-96860` were created

**Comment by kunj1988** [comment]
@magento-engcom-team can you assign me, so I can try to resolve it.

**Comment by abrarpathan19** [comment]
@kunj1988 
The issue already resolved.

**Comment by kunj1988** [comment]
@abrarpathan19, thank you for information.

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#19510 by @abrarpathan19 in 2.3-develop branch
Related commit(s):
 - [529b086a10e78c49e8cfffb542bbc9c9eb075144](https://github.com/magento/magento2/commit/529b086a10e78c49e8cfffb542bbc9c9eb075144)
 - [43c1ba81ea1bf8fceaa9d48884ca84d890ddb586](https://github.com/magento/magento2/commit/43c1ba81ea1bf8fceaa9d48884ca84d890ddb586)
 - [9ec154e3d5ce7a81a7c01fc36e9634b975eb0b9f](https://github.com/magento/magento2/commit/9ec154e3d5ce7a81a7c01fc36e9634b975eb0b9f)
 - [d93f023ba1650f3339e43952a225bac9b94cc05f](https://github.com/magento/magento2/commit/d93f023ba1650f3339e43952a225bac9b94cc05f)

The fix will be available with the upcoming 2.3.1 release.
