### ISSUE TITLE
Frontend Minicart dropdown alignment issue

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19507]
### Preconditions (*)

1.Magento 2.3-develop

### Steps to reproduce (*)

1.Open Minicart Dropdown in frontend

### Expected result (*)

![expected](https://user-images.githubusercontent.com/33230237/49328328-bbd40780-f594-11e8-9a26-03a809604ad5.png)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/33230237/49328331-c4c4d900-f594-11e8-86ac-04de61d37cff.png)

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96901`, `MAGETWO-96902` were created

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19508 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [edc9a5cf882103c7c1417e89f6b4b7fd7df50789](https://github.com/magento/magento2/commit/edc9a5cf882103c7c1417e89f6b4b7fd7df50789)
 - [17ad0dfb23bd692da2cf96828f5019dca411fa4a](https://github.com/magento/magento2/commit/17ad0dfb23bd692da2cf96828f5019dca411fa4a)
 - [d6ffca79be92114113dd88adde1e99614d59805e](https://github.com/magento/magento2/commit/d6ffca79be92114113dd88adde1e99614d59805e)
 - [f284eba8eae66d931c3aa7d9f467ceac0f16c0a7](https://github.com/magento/magento2/commit/f284eba8eae66d931c3aa7d9f467ceac0f16c0a7)
 - [2c488bcf0adef12fc99afa88cb9689a9abe9ef1a](https://github.com/magento/magento2/commit/2c488bcf0adef12fc99afa88cb9689a9abe9ef1a)
 - [e864a0c577e2eea5e4a8316a8a809c4998af3af1](https://github.com/magento/magento2/commit/e864a0c577e2eea5e4a8316a8a809c4998af3af1)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19889 by @speedy008 in 2.2-develop branch
Related commit(s):
 - [afba6e469daa725e1d3cd7ed37e55c040de6b982](https://github.com/magento/magento2/commit/afba6e469daa725e1d3cd7ed37e55c040de6b982)

The fix will be available with the upcoming 2.2.8 release.
