### ISSUE TITLE
Magento 2.3.0 cannot install with "short" secret key (at first time)

### ISSUE THREAD

**Issue by giuseppemorelli** [magento/magento2#19516]
### Preconditions (*)
1. Magento 2.3.0 - download via composer, no installation made
2. Environment: 
- OS: debian 9
- PHP 7.2
- Apache2
- MySQL 5.7

### Steps to reproduce (*)
1. After download magento 2.3.0 via composer open browser to get setup wizard page
2. When asked in setup wizard insert a custom secret key with at least 10 chars (ex. mykeytest)

![image](https://user-images.githubusercontent.com/1280769/49333250-8db5ee00-f5bb-11e8-9bee-74c6b6c92077.png)

3. Continue to finish setup and try to install magento

### Expected result (*)
Installation complete

### Actual result (*)
1. Error during the installation
2. Logs:
Module 'Magento_InventorySales':
[ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\InventorySales\Setup\Patch\Schema\InitializeWebsiteDefaultSock for module Magento_InventorySales. Original exception message: secret key size should be SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES bytes in /var/www/html/htdocs/vendor/magento/framework/Setup/Patch/PatchApplier.php:232
Stack trace:
#0 /var/www/html/htdocs/setup/src/Magento/Setup/Model/Installer.php(1000): Magento\Framework\Setup\Patch\PatchApplier->applySchemaPatch('Magento_Invento...')
#1 /var/www/html/htdocs/setup/src/Magento/Setup/Model/Installer.php(831): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
#2 [internal function]: Magento\Setup\Model\Installer->installSchema(Array)
#3 /var/www/html/htdocs/setup/src/Magento/Setup/Model/Installer.php(367): call_user_func_array(Array, Array)
#4 /var/www/html/htdocs/setup/src/Magento/Setup/Controller/Install.php(109): Magento\Setup\Model\Installer->install(Array)
#5 /var/www/html/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Magento\Setup\Controller\Install->startAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/html/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/html/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/htdocs/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/html/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/html/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/html/htdocs/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/htdocs/setup/index.php(39): Zend\Mvc\Application->run()
#16 {main}

### How to solve
1. Go back to step 3 "Web configuration"
2. Continue steps and try to install again
3. Installation is complete...

Info: .maintenance.flag still present and need to be delete

OR

1. Install magento with autogenerated keys (or custom with more 10 chars)

---------------------------

It's clear the message: "secret key size should be SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_IETF_KEYBYTES bytes" but why on second time the installation is complete?
Really strange.
Hope this issue can help others with the same problems

**Comment by magento-engcom-team** [comment]
Hi @giuseppemorelli. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@giuseppemorelli do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by giuseppemorelli** [comment]
Hi @magento-engcom-team ,
I think all the informations are ok.

The issue is on installation, so is not necessary to deploy a new vanilla instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @giuseppemorelli. Thanks for the report. I'm not able to reproduce following steps you described. Please see attachment
![install](https://user-images.githubusercontent.com/41946904/49376343-9a4b5b00-f70f-11e8-84fe-7b6457e797d7.png)

**Comment by alexeybordachyov** [comment]
I can reproduce it during CLI installation in vagrant. I tried to install fresh 2.3.0 + sample data.

bin/magento setup:install --backend-frontname="admin" --key="admin" --session-save="files" --db-host="localhost" --db-name="magento2" --db-user="root" --db-password="123" --base-url="https://m230.loc/" --base-url-secure="https://m230.loc/" --admin-user="admin" --admin-password="changeme12" --admin-email="admin@admin.com" --admin-firstname="Admin" --admin-lastname="Admin"

I was able to make it work only by passing some key param additionally, i.e.
--key="6f798255dfa145f15cbc9721901a8e68"

Looks like giuseppemorelli has very simple secret key, seems this is not allowed anymore.
