### ISSUE TITLE
Custom option styles are broken in product administraction

### ISSUE THREAD

**Issue by jaromirmuller** [magento/magento2#19539]
### Preconditions (*)

1. Magento ver. 2.3.0

### Steps to reproduce (*)

1. In administraction go to Catalog > Products and edit any simple product or create new one.
2. Go to Customizable Options
3. Add a dropdown option and add few values, no matter how many. 

### Expected result (*)

1. I would expect that form fields Title, Price, Price Type and SKU are aligned in one row. see attached screenshot, taken in Magento 2.2.5:
![customoptions_correct](https://user-images.githubusercontent.com/194480/49428818-4e4bf500-f7a7-11e8-957f-0d533978fc8d.png)

### Actual result (*)

1. I got unaligned form fields, see attached screenshot:
![customoptions_wrong](https://user-images.githubusercontent.com/194480/49428863-6885d300-f7a7-11e8-8ebd-45e77a293674.png)

**Comment by magento-engcom-team** [comment]
Hi @jaromirmuller. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jaromirmuller do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jaromirmuller** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @jaromirmuller. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jaromirmuller, here is your [Magento instance](https://i-19539-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19539-2-3-0.instances.magento-community.engineering/admin](https://i-19539-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jaromirmuller** [comment]
Yes, I can confirm the issue in 2.3.0 vanilla instance.

**Comment by jaromirmuller** [comment]
See attached:
![snimek obrazovky 2018-12-04 v 9 39 05](https://user-images.githubusercontent.com/194480/49429306-78ea7d80-f7a8-11e8-8a15-deed0598abc2.png)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @jaromirmuller thank you for you report, this issue already fixed in 2.3-develop and will be available in 2.3.1-release.
