### ISSUE TITLE
Grunt watch triggers entire page reload

### ISSUE THREAD

**Issue by pooshok** [magento/magento2#19544]
### Preconditions

1. Magento 2.3.0
2. Compiling less with grunt and livereload

### Steps to reproduce 

1. grunt exec:`<theme>`
2. grunt less:`<theme>`
3. grunt watch

### Expected result
less changes triggers styles refresh

### Actual result
livereload triggers twice: first - refresh styles, second - reload entire page

### Proposed solution

Revert back this https://github.com/magento/magento2/pull/10836

**Comment by magento-engcom-team** [comment]
Hi @pooshok. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pooshok do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @pooshok i'm not able to reproduce following steps you described in my case less changes triggers styles refresh. 
![selection_225](https://user-images.githubusercontent.com/40756439/49507344-f2599d00-f888-11e8-994c-0c8dade95751.png)

**Comment by pooshok** [comment]
Hi @engcom-backlog-nazar. Looking to your "grunt watch --verbose" output I see you have "Live reloading" fired twice. So maybe the problem is still there.
I've noticed that issue on cart page: cart summary block reloaded on every livereload. Please check it on some page, containing some "slow js generated block" like this

**Comment by ghost** [comment]
@pooshok `ivereload triggers twice: first - refresh styles, second - reload entire page` 
This trigger reload styles, not a page.

**Comment by rommelfreddy** [comment]
same issue.
same steps to reproduce...

**Comment by aledefreitas** [comment]
@pooshok @Fredwak 

Since magento team most of the times don't really care enough to solve simple problems like this one, I came up with a simple solution to prevent entire page reloads:

Just comment out the following line: https://github.com/magento/magento2/blob/2.3-develop/dev/tools/grunt/configs/watch.js#L17

This way Live reload won't be triggered by `.less` files, and will only be triggered by `.css` files thus not reloading the entire page.
This speeds up theme development by quite a bunch.

**Comment by rommelfreddy** [comment]
great @aledefreitas !
this works for me! - thank you!

**Comment by riconeitzel** [comment]
it's still an issue in 2.3.x — we confirmed it in one of the core principles of theming in magento trainings.

https://github.com/magento/magento2/issues/19544#issuecomment-463170558 fixed it

**Comment by lduivenvoorde-zz** [comment]
> @pooshok @Fredwak
> 
> Since magento team most of the times don't really care enough to solve simple problems like this one, I came up with a simple solution to prevent entire page reloads:
> 
> Just comment out the following line: https://github.com/magento/magento2/blob/2.3-develop/dev/tools/grunt/configs/watch.js#L17
> 
> This way Live reload won't be triggered by `.less` files, and will only be triggered by `.css` files thus not reloading the entire page.
> This speeds up theme development by quite a bunch.

For me, this comment solved the problem. Thanks!!!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99039` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @pooshok. Thank you for your report. 
The issue has been fixed in magento/magento2#22276 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [066a68febbd4cfb15e8cc271a984ce75bc8f6f3f](https://github.com/magento/magento2/commit/066a68febbd4cfb15e8cc271a984ce75bc8f6f3f)

The fix will be available with the upcoming 2.3.2 release.
