### ISSUE TITLE
Express Checkout Vipps dose not work

### ISSUE THREAD

**Issue by emilshamloo** [magento/magento2#19543]
Hi, I have installed Vipps extension. It works but, I have problem with EXPRESS CHECKOUT. in my site: https://www.delikatematgaver.no

### Preconditions (*)
Magento 2.2.2

### Steps to reproduce (*)
From the back-end, in the Configuration/sales/payment methods/Vipps/ express checkout, I enable it. please, look at the picture attached.
![payment-method](https://user-images.githubusercontent.com/2904897/49443331-76018400-f7cc-11e8-8ce7-be7521f8796e.jpg)

### Expected result (*)
I expect, the page send me to Vipps site to procced the payment!

### Actual result (*)
 In the front end, I see the bottom "express Checkout"/ "Vipps hurtigkasse", but when I click on it, I get this error message: "Kan ikke prosessere denne forespørselen. Vennligst prøv igjen senere eller kontakt administrator."/ "Unable to process this request. Please try again later or contact administrator." please, look at the picture attached.
![error-message](https://user-images.githubusercontent.com/2904897/49443256-405c9b00-f7cc-11e8-9af3-81f00568fbb2.jpg)

I've got contact to the bank and they tell me something I do not undrestand:
This is a respond of your page, when we send a callback:
"2018-11-26T12:12:10,199 thrId=”[I/O dispatcher 1481481]” lLv=”WARN” threadContext=[{}] jLoc=”no.vipps.payment.event.listener.infrastructure.CallBackResponsehandler” jMess=[[merchant.callback.failed Merchant call-back failed : merchantSerialNo=540443, orderId=000000146, callBackURL=https://www.delikatematgaver.no/vipps/payment/callback/v2/payments/000000146, error=Response: HTTP/1.1 500 Internal Server Error –
{“status”:500,”message”:”En feil har oppst\u00e5tt under callback prosesseringen.”}]]"
Regards

**Comment by magento-engcom-team** [comment]
Hi @emilshamloo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@emilshamloo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @emilshamloo The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
