### ISSUE TITLE
Variable @button-primary__font-family is undefined

### ISSUE THREAD

**Issue by ityetti** [magento/magento2#19550]
Hi. After upgrade Magento from v2.2.3 to v2.2.7 I faced with strange error when try to change Magento mode to production. 

### Preconditions (*)

1. 2.2.7
2. Bug reproduce on different system (MacOS apache, Centos, Windows XAMPP)
3. PHP 7.0.*

### Steps to reproduce (*)

1. Upgrade Magento from v2.2.3 to v2.2.7
2. Run command **php bin/magento deploy:mode:set production -vvv**

### Expected result (*)

Correct style compilation.

### Actual result (*)

> Compilation from source: /vendor/magento/theme-frontend-blank/web/css/styles-m.less
> variable @button-primary__font-family is undefined in file /var/view_preprocessed/pub/static/frontend/CustomVendor/CustomTheme/en_US/css/source/lib/_buttons.less in _buttons.less on line 279, column 27
> 277| 
> 278| .lib-button-primary(
> 279|     @_button-font-family: @button-primary__font-family,

For correct work compilation locally I commented lines from this commit -https://github.com/magento/magento2/commit/f3452c33e973f96e33f3b3c892f511130b1bc0c0

**Comment by magento-engcom-team** [comment]
Hi @ityetti. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ityetti do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hitesh-wagento** [comment]
Hi @ityetti 

I have tested above issue in my local  Magento ver. 2.2.7-dev but can't reproduce above issue and didn't get any error.

> /var/www/html/magento2PR$ php bin/magento deploy:mode:set production -vvv
Enabling maintenance mode
Starting compilation
Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 50.0 MiB%message% 0/7 [>---------------------------]   0% < 1 sec 50.0 MiBProxies code generation... 0/7 [>---------------------------]   0% < 1 sec 50.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 54.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 54.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 10 secs 154.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 10 secs 154.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 10 secs 154.0 MiB
Application code generator... 3/7 [============>---------------]  42% 10 secs 154.0 MiB
Application code generator... 4/7 [================>-----------]  57% 19 secs 174.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 19 secs 174.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 30 secs 190.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 30 secs 190.0 MiB
Area configuration aggregation... 6/7 [========================>---]  85% 35 secs 258.0 MiB
Interception cache generation... 6/7 [========================>---]  85% 35 secs 258.0 MiB
Interception cache generation... 7/7 [============================] 100% 38 secs 258.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content

Deploy using quick strategy
adminhtml/Magento/backend/en_US         2047/2047           ============================ 100% %  17 secs
frontend/Magento/blank/en_US            2052/2052           ============================ 100% %  43 secs
frontend/Magento/luma/en_US             2068/2068           ============================ 100% %  35 secs

Execution time: 103.47532701492
Deployment of static content complete

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ityetti thank you for you report, i'm not able to reproduce following steps you described, this may be related to you custom theme or modules.

**Comment by vk-chts** [comment]
Still facing same.
Please read the details shared by **ityetti** before commenting and providing fake solutions just to get yourself boost up in the community. 
Try updating the version from 2.2.3/ 2.2.4 to 2.27 or higher.

There are some css- less variables which throw undefined errors.
