### ISSUE TITLE
Product price is not save correctly

### ISSUE THREAD

**Issue by justin17757** [magento/magento2#19557]
### Preconditions (*)

1. Magento CE 2.2.6 without sample data is installed.
2. Store currency is JPY.

### Steps to reproduce (*)

1. Login admin account
2. Create new simple product
3. Add required information and set price, then save product.

### Expected result (*)

1. When price is set as 10,000 expect result is 10,000.00

### Actual result (*)

1. When price is set as 10,000 actual result is 10.00

**Comment by magento-engcom-team** [comment]
Hi @justin17757. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@justin17757 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by milindsingh1** [comment]
@justin17757 I think Magento 2 does not support prices to be input with the separators for any currency.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @justin17757 thank you for you report, Magento 2 does not support prices to be input with the separators for any currency, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by Tarek-Adra** [comment]
Magento not accepting your format you can use only 2 formats to be saved correctly 
1- Normal Number without and character like 123456789
2- the Default format provided by Magento 2 "123,456.00"

in your example :
if you put 10000 => it will save like 10,000.00
if you put 10,000=> it will save like 10
if you put 10,000.00 => it will save like 10,000.00

so you have to be sure ".00" exist if you used number format with ","

Thanks

**Comment by isxam** [comment]
@magento give me 2.4-develop instance
