### ISSUE TITLE
Blank admin page after new install 2.2.7

### ISSUE THREAD

**Issue by gfxguru** [magento/magento2#19555]
### Preconditions (*)

Magento 2.2.7 and 2.3

Windows 2012 R2 New Magento install, Apache 2.4, php 7.1.24 for Magento 2.2.7 and 7.2 for Magento 2.3
1.  Trying to login to admin backend produces a blank page for admin. 
2.  same results for both versions 2.2.7 and 2.3 on this machine

### Expected result (*)
see login page

### Actual result (*)

1. see https://github.com/magento/magento2/issues/19448 same screen.

**Comment by magento-engcom-team** [comment]
Hi @gfxguru. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gfxguru do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gfxguru 
```
Magento 2.3.x technology stack requirements
Operating systems (Linux x86-64)
Linux distributions, such as RedHat Enterprise Linux (RHEL), CentOS, Ubuntu, Debian, and similar.
```
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by gfxguru** [comment]
I've run Magento on Windows servers since it was born and now you're going to tell me I can't? Really

**Comment by gfxguru** [comment]
And you closed the ticket instead of looking into a fix. Now that's a bug.

**Comment by ghost** [comment]
@gfxguru magento not support windows only Operating systems (Linux x86-64)

**Comment by ghost** [comment]
@gfxguru https://github.com/magento/magento2/issues/19589
