### ISSUE TITLE
Custom option price calculation is wrong with multi currency when option price type is percentage. 

### ISSUE THREAD

**Issue by nimitaemipro** [magento/magento2#19561]
When we set multi currency custom option with percentage price type, the price calculation is wrong.
### Preconditions (*)

1. Magento  V2.3.0 with sample data
2. PHP 7.1

### Steps to reproduce (*)

Set multi currency in Magento from Stores > Configuration > General > Currency setup (I have set indian Rupee)

1. Set Currency Rates in Magento from  Stores > Currency Rates ( Ist -> 70.09, Usd -> 1)
2. Goto Catalog > Product  and edit any Simple product.
3. Set custom option typed ‘dropdown’ and add options with Price type  ‘percentage’.
4. Go to Front end product details page in which you have created custom options.
5. Change currency from Currency drop down. 
6. Now option price is changed with wrong value.
7. It is converted twice time from previous currency.

### Expected result (*)

Product Price= 34$ => 2383.06 RS.
Custom option price: 10% =3.4$ => 238.30RS
Here option price should be 238.3 RS because I have set 10% price of this option.

### Actual result (*)

Product Price= 34$ => 2383.06 RS.
Custom option price: 10% =3.4$ => 238.30RS
Here option price displayed 16702.87 RS which is wrong because it is converted twice time.

![wrong_price_calculation](https://user-images.githubusercontent.com/34769452/49494334-537f7180-f885-11e8-8a52-bbca505d0ab0.png)

**Comment by magento-engcom-team** [comment]
Hi @nimitaemipro. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nimitaemipro do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96968`, `MAGETWO-96969` were created

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @nimitaemipro. Thank you for your report. 
The issue has been fixed in magento/magento2#19608 by @emiprotech in 2.3-develop branch
Related commit(s):
 - [f7fb1865aac9b80d1bc57d6d1e28e78aff8bc7ee](https://github.com/magento/magento2/commit/f7fb1865aac9b80d1bc57d6d1e28e78aff8bc7ee)
 - [4d84a7a5af05d347e1b726d5c4dca4d4cc7c97c6](https://github.com/magento/magento2/commit/4d84a7a5af05d347e1b726d5c4dca4d4cc7c97c6)
 - [8bdedc57dcb23bb0945f28e29a9f7d22c82bdec0](https://github.com/magento/magento2/commit/8bdedc57dcb23bb0945f28e29a9f7d22c82bdec0)
 - [fde7fb1940d41214911bf3f91016f86524a0ff2b](https://github.com/magento/magento2/commit/fde7fb1940d41214911bf3f91016f86524a0ff2b)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @nimitaemipro. Thank you for your report. 
The issue has been fixed in magento/magento2#21263 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [cbf2c011a88210984dc77dda7a5ddd5a55ee72f7](https://github.com/magento/magento2/commit/cbf2c011a88210984dc77dda7a5ddd5a55ee72f7)
 - [ee8402fd25974d64c98a8da28fcbf042251b4da6](https://github.com/magento/magento2/commit/ee8402fd25974d64c98a8da28fcbf042251b4da6)
 - [5c073d9de2b11eb16548cc79f49ebf4b19f2ae71](https://github.com/magento/magento2/commit/5c073d9de2b11eb16548cc79f49ebf4b19f2ae71)
 - [040c20e30db0ba6d83675bfc9c9b1e47fbc48da5](https://github.com/magento/magento2/commit/040c20e30db0ba6d83675bfc9c9b1e47fbc48da5)

The fix will be available with the upcoming 2.2.9 release.
