### ISSUE TITLE
Wrong Button style on wishlist page in buttons

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#19564]
### Summary
Wrong Button style on Wishlist page in below buttons.
1. Update Wish List
2. Share Wish List
3. Add All to Cart

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Login in your frontend.
2. Add any product to Wishlist.
3. Go to Wishlist page
4. You can see Grey button

### Expected result

1. Buttons should be Blue background color.
![expected](https://user-images.githubusercontent.com/23443991/49495449-01d8e600-f889-11e8-964a-eb677fdb5c71.jpg)

### Actual result

1. Buttons background color was Grey.
![actual](https://user-images.githubusercontent.com/23443991/49495446-000f2280-f889-11e8-9ddb-bb992af8ab52.jpg)

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hitesh-wagento do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by rogyar** [comment]
Hi @hitesh-wagento. Thank you for the report. Could you provide more details, please, why you consider the current button styles as "wrong"? Thank you

**Comment by hitesh-wagento** [comment]
Hi @rogyar  I am consider the current button styles wrong because in our default theme we have used blue button background color and in wishlist page it's showing grey background color.

**Comment by rogyar** [comment]
Hi @hitesh-wagento. Thanks for the explanation. We cannot consider it as an "issue" since the mentioned buttons have "action" class without "primary" class. It's done for a purpose like on the shopping cart page (update, clear, apply coupon). It does not mean that the buttons style is wrong somehow, it's just different. The design idea did not highlight these buttons as primary.
