### ISSUE TITLE
Cant add & to attributes

### ISSUE THREAD

**Issue by fbkaasa** [magento/magento2#19571]
### Preconditions (*)

1. Magento Commerce 2.2.6
2. Production and Staging environment

### Steps to reproduce (*)

1. Add a brand to the manufacturer attribute (works)
2. Add a brand that contains & ( IE: Toni & Guy )

### Expected result (*)

1. Expected that the brand would be saved and displayed as Toni & Guy

### Actual result (*)

1. Prints an error ( or not actually an error, but something went wrong )
2. screenshot: https://mrkr.io/s/5c07a0889115ac1ac8a377e7/0

**Comment by magento-engcom-team** [comment]
Hi @fbkaasa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@fbkaasa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by fbkaasa** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @fbkaasa. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @fbkaasa, here is your [Magento instance](https://i-19571-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19571-2-2-6.instances.magento-community.engineering/admin](https://i-19571-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by fbkaasa** [comment]
I can verify that this issue persists on a clean Magento 2.2.6 install.

https://mrkr.io/s/5c07a2ae9115ac1ac8a377e9/0

Expected output was Toni & Guy

**Comment by ghost** [comment]
Hi @fbkaasa thank you for you report please look -> https://github.com/magento/magento2/issues/19370

**Comment by ghost** [comment]
@fbkaasa this issue has already fixed in 2.3-develop branch, and will be available on 2.3.1 release.

**Comment by fbkaasa** [comment]
That is not acceptable. We cannot move clients to 2.3 as it was only released a week ago, and 3rd party modules does not fully support it.

Do you have a workaround for 2.2.6/2.2.7?

**Comment by ghost** [comment]
@fbkaasa https://github.com/magento/magento2/pull/19375

**Comment by marcusirgens** [comment]
@engcom-backlog-nazar Which commit solves this issue? The current state of the file on the 2.2 branch is a huge rewrite from what we have in our code base at the moment: https://github.com/magento/magento2/commit/815a767dac5f577c2c4f1d4bd400411222f04f7e#diff-6268e71ecaea11cb09a0f07841941ac3
Will this be compatible with 2.2.6?

**Comment by ghost** [comment]
@fbkaasa @marcusirgens  https://github.com/magento/magento2/pull/18354
We will aim to release these changes as part of 2.2.8.
