### ISSUE TITLE
Input type import file alignment issue.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19579]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1.  Login into admin panel > System >Choose  Import > Select any  Entity Type > Select File to Import aligment issue.

### Expected result (*)

![expected-result](https://user-images.githubusercontent.com/43638601/49513869-5778b700-f8b8-11e8-9591-f13567c60c9a.png)

### Actual result (*)

 ![actual-result](https://user-images.githubusercontent.com/43638601/49513890-6b241d80-f8b8-11e8-9a6d-1b0d63ae4891.png)

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
@suryakant-krish for simple code changes, like this one, please propose a PR directly. Thanks for collaboration!

**Comment by suryakant-krish** [comment]
Sure, Next time I will take care of it. 
Thanks for suggesting me.

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19580 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [914382081598500a232f020f4338860ad762c182](https://github.com/magento/magento2/commit/914382081598500a232f020f4338860ad762c182)
 - [1d7971e0c3dc088595946348fd622346adcf6e08](https://github.com/magento/magento2/commit/1d7971e0c3dc088595946348fd622346adcf6e08)

The fix will be available with the upcoming 2.3.1 release.
