### ISSUE TITLE
Alignment Issue when create a new email template admin.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19573]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Login into admin panel > Marketing > Email Templates > Create new Email template Load any default template. Current used For Alignment issue.

### Expected result (*)

1. https://prnt.sc/lqykjw

### Actual result (*)

1. https://prnt.sc/lqyjq4

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @suryakant-krish did you load some long breadcrumbs ?
![selection_226](https://user-images.githubusercontent.com/40756439/49507788-dacee400-f889-11e8-9562-8446e9246e66.png)

**Comment by suryakant-krish** [comment]
Yes, I have load some long breadcrumbs.

**Comment by ghost** [comment]
@suryakant-krish SO why you think this is a bug ?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@suryakant-krish,  I don't think that this is the good idea
![selection_227](https://user-images.githubusercontent.com/40756439/49509713-c80ade00-f88e-11e8-9cdd-f2baa414d43b.png)

**Comment by suryakant-krish** [comment]
Yes, you are absolutely right but when breadcrumb in single line alignment not proper.
I will work on that with other solution.

**Comment by ghost** [comment]
@suryakant-krish   **`margin-top: 6px;`**

**Comment by suryakant-krish** [comment]
Yes, I have already applied it and added one more commit please review it.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96964`, `MAGETWO-96965` were created

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19574 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [914382081598500a232f020f4338860ad762c182](https://github.com/magento/magento2/commit/914382081598500a232f020f4338860ad762c182)
 - [b1c929db5763a5002820c0d2f0ce21dbda50fe87](https://github.com/magento/magento2/commit/b1c929db5763a5002820c0d2f0ce21dbda50fe87)
 - [81bae5c088f986a6fe373c9e8e302a4ce4664a4e](https://github.com/magento/magento2/commit/81bae5c088f986a6fe373c9e8e302a4ce4664a4e)
 - [72438dec51fd3472590675eb24160adf727951fd](https://github.com/magento/magento2/commit/72438dec51fd3472590675eb24160adf727951fd)
 - [da8b3165e3349c918e62cc1dff90722930fc63b5](https://github.com/magento/magento2/commit/da8b3165e3349c918e62cc1dff90722930fc63b5)

The fix will be available with the upcoming 2.3.1 release.
