### ISSUE TITLE
Checkbox alignment issue

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#19576]
### Summary

Checkbox alignment issue

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Login in your frontend.
2. Add any product to Wishlist.
3. Go to Account page
4. Click on Account Information tab from left side.

### Expected result

1. Checkbox should be aligned.
![expected](https://user-images.githubusercontent.com/23443991/49509174-96a00b80-f8aa-11e8-8575-a94397a62586.jpg)

### Actual result

1. Checbox little bit up.
![actual](https://user-images.githubusercontent.com/23443991/49509176-9869cf00-f8aa-11e8-93a9-a88d7c9bf199.jpg)

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hitesh-wagento do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@hitesh-wagento what's wrong here ?

**Comment by hitesh-wagento** [comment]
Hi @engcom-backlog-nazar it's checkbox alignment issue. checkbox is little bit up compare to text.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96966`, `MAGETWO-96967` were created

**Comment by hitesh-wagento** [comment]
I am working on this.

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me test instance

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-19576-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19576-2-3-develop.instances.magento-community.engineering/admin](https://i-19576-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jayachandraoggy** [comment]
give me 2.3-develop instance

**Comment by marcelo-monteiro** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @marcelo-monteiro, here is your [Magento instance](https://i-19576-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19576-2-3-develop.instances.magento-community.engineering/admin](https://i-19576-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by marcelo-monteiro** [comment]
Tested with version above and it's fixed.

![checkbox_alligned](https://user-images.githubusercontent.com/30471434/64053527-17014d80-cb59-11e9-8ba7-efa9e764f41e.jpg)
