### ISSUE TITLE
Custom shipping attributes not passed through for shipping estimates.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#19578]
### Summary (*)
I am trying to use extra attributes added to the shipping address during shipping rate estimate calculations and to decide the availability of shipping methods. (Via a module called owebia magento2 module advanced shipping setting)

I can see the attributes present on the shipping address but they are always NULL.
owebia/magento2-module-advanced-shipping-setting#46

### Examples (*)
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Quote/Model/Quote/Address.php#L984

### Proposed solution
I suspect the extra attributes need to actually be set on the RateRequest.
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Quote/Model/Quote/Address/RateRequest.php

Possibly related to #15026

**Comment by magento-engcom-team** [comment]
Hi @LiamKarlMitchell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LiamKarlMitchell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
hi @LiamKarlMitchell 
`I can see the attributes present on the shipping address but they are always NULL.`
Where you set your extension attributes ? 
please describe more information.

**Comment by ghost** [comment]
@LiamKarlMitchell 
1.Run $ bin/magento setup:di:compile to generate ShippingMethodExtensionInterface and a class that implements this (this is not done on each request even with disabled cache)

2.In your plugin instantiate Magento\Quote\Api\Data\ShippingMethodExtension and add data to that object and then the entire object add to the entity with $entity->setExtensionAttributes($extensionModel)

**Comment by ghost** [comment]
@LiamKarlMitchell -> https://devdocs.magento.com/guides/v2.0/extension-dev-guide/extension_attributes/adding-attributes.html

**Comment by LiamKarlMitchell** [comment]
Thanks for the advice I'll give it a go.

**Comment by evs-xsarus** [comment]
@liam-wiltshire I have the same issue, did you solve this and can you provide example code?

**Comment by LiamKarlMitchell** [comment]
Hey @evs-xsarus , Yes I stopped using Owebia and ended up writing my own shipping/carrier module with the custom logic for the customer(s) as needed...

For example: Free shipping within X distance of their stores.
Shipping via heavier/larger items via Truck, removing other shipping options if too large/heavy to go in them.

**Comment by hansoncitra** [comment]
Hi @LiamKarlMitchell can you please tell us how you solved this issue? I have the exactly same issue, I want to get custom attributes from address, but cant get it on rateRequest variable. Thank you in advance.
