### ISSUE TITLE
Can't create CreditMemo for order older than 30 days

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#19588]
### Preconditions (*)

1. Magento CE 2.2.6
2. Have olders older by 30 days

### Steps to reproduce (*)

1. Create few orders
2. Make sure orders and quotes are older than 30 days (the best way is to modify it on database level)
3. By default Magento 2 removes quotes which are older than 30 days [configurable value]
4. Run CRONs
5. Try to create a credit memo in the backend for those orders

### Expected result (*)

1. Credit memo is created
2. Order is refunded

### Actual result (*)

1. Credit Memo is not created
2. Order Status is not updated
3. Order is not refunded
4. Error in Admin Panel ```No such entity with cartId = xxxx``` where xxxx is the quoteId / cartId

In my opinion: CartId / QuoteId should not be related to Credit Memos / Invoices

**Comment by magento-engcom-team** [comment]
Hi @qsolutions-pl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@qsolutions-pl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @qsolutions-pl Thank you for you report, this issue has already fixed in 2.3-develop branch, I have a quote that is deleted by cron job, but when i create credit memo all works fine.

**Comment by patrick-bigbridge** [comment]
@engcom-backlog-nazar Can you give me a commit for this fix? Upgrading to 2.3 is not an option for our client just now.

**Comment by patrick-bigbridge** [comment]
The problem we had occurred in a third party extension, so we don't need this commit anymore.
