### ISSUE TITLE
Text swatch value for multi store view wrong on frontend

### ISSUE THREAD

**Issue by ryanfern86goa** [magento/magento2#19582]
### Preconditions (*)

1. Magento version 2.2.5
2. nginx version: nginx/1.15.3
3 PHP 7.1.14

### Steps to reproduce (*)

1. Create 2 websites with 1 store view each or just 2 store views
2. Create configurable select attribute eg (size) with different store view value and label
3) Go to frontend, default store (GB) and any category page with configurable products with size as one of the attribute
4) switch to a different website/ store view (US)

### Expected result (*)

1.  Once we switch to website/ store view (US), we should see the size's value to show according to the value set for that store view  in the attribute edit section ( see screenshot)

### Actual result (*)

1. When we switch from default website/ store view (GB) to US store view, we still see the GB store view attribute option values
[https://drive.google.com/open?id=1o1icWLnmyE0rM2E-QeCwxdb1xhw_P4O1]
[https://drive.google.com/open?id=1lZ1JR0-m80bB6AyQs0a0SWR9h4bFn36l]

**Comment by magento-engcom-team** [comment]
Hi @ryanfern86goa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ryanfern86goa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ryanfern86goa** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ryanfern86goa. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ryanfern86goa, here is your [Magento instance](https://i-19582-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-19582-2-2-5.instances.magento-community.engineering/admin](https://i-19582-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ryanfern86goa** [comment]
Hi,

I have found a fix for similar issue here https://github.com/magento/magento2/pull/15960 but don't believe this is a complete fix for magento version 2.2.5.

So the fix should be 
1) vendor/magento/module-swatches/Helper/Data.php

On line 444, after $currentStoreId = $this->storeManager->getStore()->getId(); add
$swatchCollection->addStoreFilter($currentStoreId);

2) vendor/magento/module-swatches/Helper/Data.php

On line 503, replace with

              if (isset($optionsArray[self::DEFAULT_STORE_ID])) {
                    $swatches[$optionId] = $optionsArray[self::DEFAULT_STORE_ID];
                } elseif (isset($optionsArray[$currentStoreId])) {
                    $swatches[$optionId] = $optionsArray[$currentStoreId];
                }

Thanks

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
Thank you for contributing this issue. This issue is not reproducible on the latest 2.3-develop.
![peek 2018-12-05 17-41](https://user-images.githubusercontent.com/11827230/49525033-86d9f480-f8b5-11e8-8934-17937bfc2533.gif)

**Comment by ryanfern86goa** [comment]
Hi @TomashKhamlai 

This issue is currently effecting magento 2.2.5 commerce version. Shouldn't you test this on it ?.

Can you please check on this version

Thanks

**Comment by TomashKhamlai** [comment]
@ryanfern86goa, according to the current workflow we should stop the verification process if the issue is not reproducible on the latest code.
Please take a look on this [message](https://github.com/magento/magento2/issues/19582#issuecomment-444502210):
![image](https://user-images.githubusercontent.com/11827230/49531244-885de980-f8c2-11e8-9efe-bf1824c44d69.png)

**Comment by ryanfern86goa** [comment]
Hi @TomashKhamlai 

Thanks for your reply. 

Does this mean magento has stopped support, bug fixes and patch releases for 2.2.X ?, if so please confirm here so that I can forward this on-to forums and other developer chat groups.

Would also help us to convey this message to our clients. (note: we are magento partners)

Thanks

Regards
Ryan

**Comment by TomashKhamlai** [comment]
@ryanfern86goa, issues about Magento Commerce should be submitted to [Magento Support](https://support.magento.com/hc/en-us). To submit a support ticket, you need to login there. You already have an account there if you use Magento Commerce. If there is an issue with conditions that describes the problem on Magento Commerce and there are no limitations in Magento Open Source, so that it is possible to check these conditions, then we also check this issue, but we care only about Magento Open Source functionality.

Please, read the [message](https://github.com/magento/magento2/issues/19582#issuecomment-444502210) from @magento-engcom-team. Click on Details in the Step 4. There is an answer on your question.

If the problem is fixed in 2.3.0 it is possible that it will be backported by internal team or by someone from community, but if you do not want to wait then it is recommended to create all kinds of backups before upgrading to 2.3.0.

**Comment by ryanfern86goa** [comment]
Hi @TomashKhamlai 

I will open a ticket in our commerce support section, but just to let you know this should also affect community edition.

What sounds appalling to me is that, I'm reporting a bug for 2.2.5 version and rather than check it in this version you guys are testing it on 2.3.0 dev version, now dev is not the current release, is it ?.

You guys should be testing to replicate this on 2.2.5 version as this is the version we are reporting this bug for. Now if this bug is not reproduce-able in 2.3.0 dev than that means this is fixed and you should be giving me the patch for 2.2.5 version.

I think you should use a bit common sense rather than just pointing to point 4.

You h=guys should understand and know that you an't just upgrade a clients project from 2.2.5 to 2.3.0. This is something that needs to come from the client approval and not a simple case of just upgrading the version.

If this is something you cannot accept then please confirm in writing that you (magento) don't support 2.2.X anymore.

Regards,
Ryan
