### ISSUE TITLE
2.3.0 Has finally made it so that windows won't work.

### ISSUE THREAD

**Issue by PathToLife** [magento/magento2#19589]
### Summary (*)
Up till now, windows developers have been able to use WAMP/BITNAMI/XAMPP to run a local magento instance for dev purposes.

ENV:
Windows 10 Pro 64 Bit.
Magento Sample 2.3.0 from downloads (tar.gz)
WAMP. PHP.ini configured with vanilla sample

Problem:
0. Config WAMP with Magento Php.ini, make SQL DB.
1. Install Magento.
2. Admin window will not load, main page will be broken. (Validator.php causes this)

### Examples (*)
This is the main commit that totally breaks everything.
https://github.com/magento/magento2/commit/8110949e4dd4faa8d36b25ecfeb7779ebbac5741

### Proposed solution
Not officially support, but still code so that windows pathing works.
Just like Wordpress/Drupal/OpenCart/Joomla/SilverS/Presta...
I do see how it'll be hard given the unique way magento routes things.

### My Goal
To get official responses about windows pathing support, so that developers who previously were working in windows, won't waste time when 2.3 goes kaput, so everyone basically knows 'hey, it's finally gone for good'.
NO SUPPORT?: Please Ideally put a warning in setup. Suggest VM alternative?.
YES SUPPORT?: Horrary! Can play battlefield5 while developing.

**Comment by magento-engcom-team** [comment]
Hi @PathToLife. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@PathToLife do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @PathToLife thnk you for you report please look -> https://github.com/magento/magento2/issues/19471

**Comment by ghost** [comment]
@PathToLife https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by PathToLife** [comment]
Thanks for replying while i was busy coding some things using cross platform apache server, with cross platform php, and with cross platform mysql.

Since windows is not officially supported, I guess Linux bash shell on windows is not either right?

Can we get a big ass warning somewhere in official documentation?  And in the initial checkup setup page?

I just spent 5 hours getting NAT, chmod bs, user group bs, xdebug, sftp sync, static ip configuring, broken ass netmanger that doesnt parse tabs, vim highlighting said tabs so can remove said tabs, all to get magento 2.3 working in a fresh Ubuntu VM install so I develop some modules without fear of borking something and getting closed because windows not activated, sorry I mean not supported.

**Comment by ghost** [comment]
@PathToLife  Just try install WSL, this is not hard, and i configured all on windows 10 on 10 minutes.

**Comment by ghost** [comment]
@PathToLife  you can report here -> https://github.com/magento/devdocs/pulls
