### ISSUE TITLE
Catalog | Products | Update Affecting All Products Insted of Selected Ones

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#19595]
Preconditions

1- php 7.1
2- magento 2.2.4
Steps to reproduce

1- filter catalog view to view a cretin products
2- select one catalog
3- update catalog status to "disabled" by clicking the option 2 times, if you click it once nothing will happen but if you click it twice the problem will show up

video of issue regenerated here : https://drive.google.com/file/d/18qxaxOZ6qHN3aUPuGa6HXkBD4w0S7lMT/view?usp=sharing
https://drive.google.com/file/d/1IcscMjAMQRVnxTE4S99wJpSO6axIxQSU/view
Expected result

selected product should be updated instead of affecting all products... screen recording below:
https://drive.google.com/file/d/1IcscMjAMQRVnxTE4S99wJpSO6axIxQSU/view

**Comment by magento-engcom-team** [comment]
Hi @salehawal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@salehawal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by salehawal** [comment]
it is same as this one : https://github.com/magento/magento2/issues/17856, but now we know exactly where the problem comes from

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @salehawal i'm not able to reproduce following steps you described, this may be related to you custom modules.
