### ISSUE TITLE
Missing variable for copyright background color in _module.less

### ISSUE THREAD

**Issue by pixel-paul** [magento/magento2#19600]
### Preconditions (*)
1. Magento 2.3
2. PHP 7.1

### Steps to reproduce (*)
1. Install fresh version of Magento
2.

### Expected result (*)
1. No error message. Less to compile without error

### Actual result (*)
Error meesage is generated
1. `variable @copyright__background-color is undefined in file var/view_preprocessed/pub/static/frontend/example/eg/en_US/Magento_Theme/css/source/_module.less in _module.less on line 265, column 36`

This is still present. Originally reported in #12398

**Comment by magento-engcom-team** [comment]
Hi @pixel-paul. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Steps to reproduce
- [ ] Information on your environment
- [ ] Summary of the issue
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pixel-paul do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by amol2jcommerce** [comment]
1) Clear the content of pub/static and var/view_preprocessed 

2) Deploy : php bin/magento setup:static-content:deploy -f

3) Clean the cache: php bin/magento cache:clean

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by pixel-paul** [comment]
@amol2jcommerce - yes I did try that.

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by abrarpathan19** [comment]
Hello, 

@pixel-paul 
variable `@copyright__background-color` is already defined in Luma theme `\vendor\magento\theme-frontend-luma\web\css\source\_theme.less`  line number 302  `@copyright__background-color: @color-gray-middle4;` so It is not requered to definded in `Magento_Theme/css/source/_module.less `

**Comment by ghost** [comment]
HI @pixel-paul I'm closing this as this expected behavior please look comment on @abrarpathan19 ->https://github.com/magento/magento2/issues/19600#issuecomment-445439061
