### ISSUE TITLE
Don't static compile disabled modules

### ISSUE THREAD

**Issue by joshuaadickerson** [magento/magento2#19605]
### Summary (*)

When running static-content:deploy, there are disabled module content in pub/static.

### Examples (*)

Disable modules that have frontend resources.
Run `bin/magento setup:static-content:deploy`
Observe that `pub/static/...` contains the resources.

### Proposed solution

Check the disabled modules and skip them when compiling static content

**Comment by magento-engcom-team** [comment]
Hi @joshuaadickerson. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@joshuaadickerson do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @joshuaadickerson . Thank you for you report,  It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by DrewML** [comment]
Re-opening. I don't consider this to be a feature request. If the issue is as @joshuaadickerson reported (I have not tested, but don't have reason to believe otherwise) this is certainly a bug. Copying over unused code to `pub/static` will mean that those using the built-in JS bundling strategy will be over-shipping code.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97027`, `MAGETWO-97028` were created

**Comment by magento-engcom-team** [comment]
Hi @milindsingh1. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by DrewML** [comment]
Slightly related: https://github.com/magento/magento2/issues/15967

**Comment by magento-engcom-team** [comment]
Hi @joshuaadickerson. Thank you for your report. 
The issue has been fixed in magento/magento2#19751 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [83f8e98ae9749841ff808952e04f0ddd5bc15e35](https://github.com/magento/magento2/commit/83f8e98ae9749841ff808952e04f0ddd5bc15e35)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @joshuaadickerson. Thank you for your report. 
The issue has been fixed in magento/magento2#19989 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [1f5ec6fda14aa0c767e2b396da9e51ec99177787](https://github.com/magento/magento2/commit/1f5ec6fda14aa0c767e2b396da9e51ec99177787)
 - [484b79acbf0249eee6126bb83503b38e5ec67697](https://github.com/magento/magento2/commit/484b79acbf0249eee6126bb83503b38e5ec67697)
 - [d291cf353d0853a2298e2a1a4d22882de91e2643](https://github.com/magento/magento2/commit/d291cf353d0853a2298e2a1a4d22882de91e2643)

The fix will be available with the upcoming 2.2.8 release.
