### ISSUE TITLE
Google reCAPTCHA : Sometimes reCAPTCHA doesn't display - hidden dependance

### ISSUE THREAD

**Issue by michelecanal** [magento/magento2#19618]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)
1. clean magento 2.3 installed (composer)
2. I am using Magento's default Luma theme
3. I have configured 'Google reCAPTCHA' (v2 or invisible) and then enabled it for frontend forms.
4. disable module magento_captcha

### Expected result (*)
1. In contact form, it should display the google reCAPTCHA button and convalidate the form2.

### Actual result (*)
1. Sometimes it works correctly
2. Generally reCAPTCHA is not displayed and the form doesn't work ("Incorrect reCAPTCHA")

If I enable the module magento_captcha the contact form works correctly

So, in my opinion, there is an hidden dependence between magento_captcha and msp/reCAPTCHA
This is not clear because in the admin the store/configuration/admin/advanced/admin speak about "captcha in admin", not in frontend.

**Comment by magento-engcom-team** [comment]
Hi @michelecanal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@michelecanal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by hiren0241** [comment]
Hi @michelecanal,
I am able to reproduce this issue on fresh instance of 2.3. I am working upon this and I will let you know the progress.

**Comment by sibhis** [comment]
We face similar issue in customer registration page with Magento2.2. Sometime, customer account is created successfully without captcha even if it enabled in admin configuration and sometime shows error message like 'Incorrect Captcha'

**Comment by orlangur** [comment]
@michelecanal is `msp/reCAPTCHA` a core module?

**Comment by michelecanal** [comment]
@orlangur from 2.3 yes

https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html

**Comment by orlangur** [comment]
@michelecanal which sentence are you referring to? Cannot find anything related by "msp" or "captcha".

**Comment by michelecanal** [comment]
have you installed a fresh install of magento 2.3 via composer?

**Comment by orlangur** [comment]
@michelecanal I'm asking to which sentence of release notes you are referring to. Looks like it is a new bundled extension not mentioned in release notes.

> there is an hidden dependence between magento_captcha and msp/reCAPTCHA

Seems like the latter should be fixed but it is not placed in this repo.

**Comment by michelecanal** [comment]
https://github.com/magespecialist/m2-MSP_ReCaptcha

**Comment by orlangur** [comment]
@michelecanal thanks, now it's clear!

Then this issue must be reported in https://github.com/magento/magespecialist_ReCaptcha/ which you already did.

**Comment by koushikch7** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @koushikch7. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @koushikch7, here is your [Magento instance](https://i-19618-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19618-2-3-0.instances.magento-community.engineering/admin_a3b8](https://i-19618-2-3-0.instances.magento-community.engineering/admin_a3b8)
Login: `62a0ce0a` Password: `24766071239a`
Instance will be terminated in up to 3 hours.

**Comment by koushikch7** [comment]
@magento-engcom-team give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @koushikch7. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @koushikch7, here is your [Magento instance](https://i-19618-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-19618-2-3-3.instances.magento-community.engineering/admin_7839](https://i-19618-2-3-3.instances.magento-community.engineering/admin_7839)
Login: `15f994b6` Password: `f777ac92a870`
Instance will be terminated in up to 3 hours.
