### ISSUE TITLE
Dynamic Block

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#19616]
### Preconditions (*)
In the release notes, there is a reference to Banners that have been renamed to Dynamic Block. 
I have a clean install of M2.3 but there are no options for Dynamic Block's

https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html

### Steps to reproduce (*)
Content > Widget > Widget type 

### Expected result (*)
See an option for Dynamic Block

### Actual result (*)
No Dynamic Block options

**Comment by magento-engcom-team** [comment]
Hi @oefterdal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@oefterdal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by oefterdal** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by oefterdal** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oefterdal. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @oefterdal, here is your [Magento instance](https://i-19616-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19616-2-3-develop.instances.magento-community.engineering/admin](https://i-19616-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by oefterdal** [comment]
I get the same result on the 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](https://i-19616-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19616-2-2-develop.instances.magento-community.engineering/admin](https://i-19616-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by oefterdal** [comment]
For your information, I have never seen this functionality in older releases either.

**Comment by TomashKhamlai** [comment]
@oefterdal in older releases it should look like in the [documentation](https://docs.magento.com/m2/2.2/ee/user_guide/cms/banner-create.html).

GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by TomashKhamlai** [comment]
@oefterdal, thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by TomashKhamlai** [comment]
@keharper, do we have Dynamic Block's functionality described in the documentation?

**Comment by oefterdal** [comment]
@TomashKhamlai The release note I am referring to is not for commerce but open source. 

_Here is a snippet from the release notes:_ 

**Highlights**

Magento Open Source 2.3.0 includes a wealth of new features as well as hundreds of enhancements and fixes to the core product. Look for the following highlights in this release:

Merchant tool enhancements

CMS enhancements include banner enhancements. You can now create banner content in native Magento WYSIWYG. (Within the product interface, we now use the term “dynamic block” instead of “banner”.) We’ve also updated the WYSIWYG editor to use TinyMCE 4.6. (TinyMCE is now integrated into Magento through an adapter that allows it to be replaced with any other WYSIWYG editor.)


**Banner (now Dynamic Block)**

The Magento CMS banner has been renamed to dynamic block to better represent this feature. Banners from **Content > Banners** have been renamed across the Admin and the code base. Correspondingly, the Magento widget banner rotator type (from **Content > Widget > Widget type**) has been renamed to dynamic blocks rotator.
You can now create dynamic block (formerly banners) content from the WYSIWYG editor. You can create store-specific content for dynamic blocks by switching between scopes using the Magento Scope Selector.

Link: https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html

**Comment by keharper** [comment]
Banners/dynamic blocks are a Commerce feature. These items need to be removed from the Open Source release notes.
