### ISSUE TITLE
Can not upload “Transactional Emails” logo from magento backend.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#19615]
From admin panel admin can not upload the Transactional Emails logo from Content > Design > Edit Theme > Transactional Emails > Upload Logo from  Logo Image. Image will not upload from backend. 
### Preconditions (*)

1. Magento  V2.3.0 with sample data
2. PHP 7.1

### Steps to reproduce (*)

1. Goto : Content > Design > Edit Theme > Transactional Emails and  Upload Logo from  Logo Image
2.  Error message at the time of upload logo : “A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.”

### Expected result (*)

1. Image was uploaded at admin side and that image must be displayed in all transactional emails. 
### Actual result (*)

1. [Screenshots, logs or description]
2. Image was not uploaded from backend.

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @emiprotech this is duplicate to this -> https://github.com/magento/magento2/issues/19581

**Comment by ghost** [comment]
@engcom-backlog-nazar,
This is not duplicate , because in 2.2.6 , we can upload logo from admin side and in 2.3 we are not able to set logo from backend.

**Comment by ghost** [comment]
@emiprotech in referenced issue you not able to upload logo on 2.3, the label are present "reproduce on 2.3" and have already assigned contributor.

**Comment by ghost** [comment]
@emiprotech  you can add description to ->#19581

**Comment by sumeetmobiwebtech** [comment]
@emiprotech 
How did you Solved?Would you please let us know ?
