### ISSUE TITLE
Error message for the website admin when trying to add a review Magento 2.3

### ISSUE THREAD

**Issue by jessicana** [magento/magento2#19623]
Magento 2.3 admin receives an error message when trying to add a review and the stars rating is unavailable. I suppose the stars issue was in Magento 2.2.6 and continues to be unresolved.

### Preconditions (*)

1. Magento 2.3
2. PHP 7.1.22

### Steps to reproduce (*)

1. Sign in to Magento backend.
2. Marketing > Reviews > New Review
3. Select a product to review

### Expected result (*)

1. Admin must be able to add a review
2. A review window should show the nick name, summary of review, STARS and review
3. Rating isn't Available

### Actual result (*)

1. The admin gets this message: A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.
2. Have a look at the picture below:
![review](https://user-images.githubusercontent.com/7415824/49674934-07068280-fa8d-11e8-80cf-d3bb66ca8037.png)
Product review settings:
Go to Stores > Settings > Configuration
Under Catalog, select Catalog.

![gust review](https://user-images.githubusercontent.com/7415824/49675256-471a3500-fa8e-11e8-86d2-3f7a4c824d2c.png)

**Comment by magento-engcom-team** [comment]
Hi @jessicana. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jessicana do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by jignesh26** [comment]
@jessicana, Thank your for the issue. I am checking the issue. its showing the error message , i am checking that but for your note you can still submit the review from the admin.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by suneet64** [comment]
Hi Guys,

This issue is replicable on the clean installation of Magento 2.3 and I have resolved it under the https://github.com/magento/magento2/pull/20146 pull request.

**Comment by milindsingh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @milindsingh, here is your [Magento instance](https://i-19623-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19623-2-3-develop.instances.magento-community.engineering/admin](https://i-19623-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@milindsingh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97534` were created

**Comment by eduard13** [comment]
Wasn't able to reproduce this one on the latest version.
![image](https://user-images.githubusercontent.com/15868188/77948757-8fd2ae80-72ce-11ea-851f-775981a50b5c.png)
Most probably was fixed in scope of #20146.
Closing this one as not being actual anymore.
Thank you.
