### ISSUE TITLE
FPC not working on multisotre

### ISSUE THREAD

**Issue by bobmats** [magento/magento2#19622]
### Summary of the issue

When fpc cache is on main domain gets cache hit  

Set-cookie | PHPSESSID=qtu3amjes5ck6abl74455gulog; expires=Fri, 07-Dec-2018 21:27:33 GMT; Max-Age=3600; path=

when visiting a product on the second domain (other website)

Set-Cookie | X-Magento-Vary=e96b7c37def15b1cd76dd9dcea7d889fabef16f4; expires=Fri, 07-Dec-2018 16:51:49 GMT; Max-Age =3600; path=/; secure; HttpOnly

Time to first byte on the main website <200 ms
Time to first byte on second domain around 2 seconds
Even when fpc is on page visited several times, message cache miss

We have around 6 other websites in mutlistore, all have slow time to first byte and magento vary cookie set.

Tested on live 2.2.5 and dev 2.2.7
When fpc is disabled
main domain shows this:

set-cookie | PHPSESSID=qtu3amjes5ck6abl74455gulog; expires=Fri, 07-Dec-2018 21:27:33 GMT; Max-Age=3600; path=

second domain shows both cookies

PHPSESSID=t8dndjip9mh20284kqrqo78jbb; expires=Fri, 07-Dec-2018 21:27:18 GMT; Max-Age=3600
and
X-Magento-Vary=e96b7c37def15b1cd76dd9dcea7d889fabef16f4; expires=Fri, 07-Dec-2018 21:27:19 GMT; Max-Age
=3600; path=/; secure; HttpOnly

tested both in nginx and apache, both give same behavior

### Preconditions (*)

Magento version 2.2.5 (live) Magento 2.2.7 (Dev)

### Steps to reproduce (*)
Magento installation multistore
2 domains
main website using main domain.
second website using the second domain

### Expected result (*)

Cache hit on all domains
maganto phpssid set on all domains, not x-magento-vaty.

-- | --

**Comment by magento-engcom-team** [comment]
Hi @bobmats. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bobmats do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by bobmats** [comment]
First install was magento 2.2.2
updated to 2.2.3 than 2.2.5 than 2.2.7 problem is still there.
Yesterday disabled all thrid party extensions to check if these gave a problem.
Problem is still there.

Did a new install on subdomain and there seems to be now problem.

Issue seems to be similar to this issue: https://github.com/magento/magento2/issues/15828

We use nginx on server, as test this is disabled to only apache. This did not solve the problem.

**Comment by ghost** [comment]
HI @bobmats thank you for you report, the fix for this issue will be avaible on 2.3.1 release, -> https://github.com/magento/magento2/issues/15828#issuecomment-441109770

**Comment by bobmats** [comment]
Thanks for the update, is there no option to have this fixed on the current setup ?
