### ISSUE TITLE
Backend Marketing Cart Price Rule Label Alignment Issue

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19632]
### Preconditions (*)

1.Magento 2.3-Develop

### Steps to reproduce (*)

1.Open Marketing -> Cart Price Rules ->Store View Specific Labels in Backend
2.Check Help Icon Alignment

### Expected result (*)

 ![expected](https://user-images.githubusercontent.com/33230237/49682785-604bd180-fae0-11e8-98b1-285f99d3ac80.png)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/33230237/49682790-680b7600-fae0-11e8-8f1a-e814ba7f99a2.png)

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by jignesh26** [comment]
@speedy008 thanks for issue, i think you have resolved this and please create the pull request asap.

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97272` were created

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#19637 by @speedy008 in 2.3-develop branch
Related commit(s):
 - [2e855c44cc81096d6ea18e446e16fe95b9529d61](https://github.com/magento/magento2/commit/2e855c44cc81096d6ea18e446e16fe95b9529d61)
 - [f4de9140885de05d73573dea06bfc81ecba557a4](https://github.com/magento/magento2/commit/f4de9140885de05d73573dea06bfc81ecba557a4)

The fix will be available with the upcoming 2.3.2 release.
