### ISSUE TITLE
Frontend Component theme sort by arrow icon vertical alignment issue.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19639]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Go to frontend  > choose any category > see on product list page > sort by arrow icon alignment.
It is little bit down.

### Expected result (*)

1. ![expected-result](https://user-images.githubusercontent.com/43638601/49684371-2e933480-faf9-11e8-8dd6-e518f8f91845.png)

### Actual result (*)

1. ![actual-result](https://user-images.githubusercontent.com/43638601/49684373-3521ac00-faf9-11e8-98d8-8f5dc1950170.png)

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19640 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [e5675102f15f7344fdef4fc49d3619351099acc2](https://github.com/magento/magento2/commit/e5675102f15f7344fdef4fc49d3619351099acc2)

The fix will be available with the upcoming 2.3.1 release.
