### ISSUE TITLE
Checkbox alignment issue backend.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19630]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Login into admin panel > System > Export > checkbox alignment issue "Fields Enclosure". 

### Expected result (*)

1. ![expacted-result](https://user-images.githubusercontent.com/43638601/49682735-a05e8480-fadf-11e8-8a9f-a08d20f2beca.png)

### Actual result (*)

1. ![actual-result](https://user-images.githubusercontent.com/43638601/49682739-abb1b000-fadf-11e8-922b-0959dd6fdad9.png)

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97270` were created

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19631 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [d0c0bccdfec92a7657c3d94e86f7fa13b70b4df2](https://github.com/magento/magento2/commit/d0c0bccdfec92a7657c3d94e86f7fa13b70b4df2)
 - [dce80fd6606eabbfb25447c4ca4eed8d8f9434a4](https://github.com/magento/magento2/commit/dce80fd6606eabbfb25447c4ca4eed8d8f9434a4)
 - [dd044438503cbe87d3341f6e100e9572cdd724eb](https://github.com/magento/magento2/commit/dd044438503cbe87d3341f6e100e9572cdd724eb)
 - [d0d57e38a727630393f7cc6a630af81cc36cb1ee](https://github.com/magento/magento2/commit/d0d57e38a727630393f7cc6a630af81cc36cb1ee)
 - [a2c9050f7bb22fdacffe3194b036e0d1c894a0bd](https://github.com/magento/magento2/commit/a2c9050f7bb22fdacffe3194b036e0d1c894a0bd)

The fix will be available with the upcoming 2.3.2 release.
