### ISSUE TITLE
Frontend apps for ALL cms pages

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1964]
Frontend apps now are very usefull, but is not possibile to assign something to a custom cms page, without using the xml editor. 
I have trouble understanding why you can select "Specific Pages", but the drop down menu only offers those options: Home, no cookies, 404 and a generic "All Pages".

At this point it would make more sense to add also the possibility to select a page (or even apage ID manually).

**Comment by alankent** [comment]
CMS is going to get a bit of an overhaul in the not too distant future. Feel free to describe what you would like the behavior to be.

**Comment by CRYX2** [comment]
Ok thanks, those modifications will be applied before the GA?

**Comment by acharrex** [comment]
I've the same issue / problem.

@alankent: Can you provide us more information about the scope of the new CMS?

**Comment by alankent** [comment]
I don't think much more is coming for CMS for 2.0 GA (that I know). GA really finishing off last bits of work for what is there, then testing testing and more testing. Post 2.0 we have a backlog, and do have CMS work on that backlog. I passed the question on to the PM who owns that area. I think is better that they share what is planned rather than me guess!

I was personally looking into the relationship between themes and CMS static blocks. There is currently not a good way for a theme to reference a static block (you have to specify the block id from the database, which is not portable in a theme). It seems nice for a theme to be able to be shipped referencing a static block, so theme developer can set up a better theme, but allow administrator to adjust the static block content.

I was curious to see what other people wanted to do so we could feed that into internal discussions. What gaps do other people see?  That might feed into how much time we invest - e.g. should we invest more but provide more? What I described above is relatively small.

We frequently operate by budget. We want to boil the ocean, but cannot. So we often allocate work a budget and do the best we can with that budget. Hence knowing what customers would find most useful is useful to us. We collect this information from a number of channels all the time - you are welcome to add your requests here if you want to in order to add it to the list. But until we review ourselves, we don't know exactly what will make the cut list.

**Comment by acharrex** [comment]
Thanks a lot for your feedback!

**Comment by daim2k5** [comment]
I close the ticket for know, if you are uncomfortable with my decision feel free to reopen.
