### ISSUE TITLE
Area Frontend: Account information page checkbox alignment issue.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19645]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Login into Frontend > Choose Account Information > Look at change email and change password checkbox alignment little bit up.

### Expected result (*)

1. http://prntscr.com/lsapwz

### Actual result (*)

1. http://prntscr.com/lsanwl

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97295` were created

**Comment by sidolov** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19646 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [0811a711fb78e5df2153055d78504cc890fece30](https://github.com/magento/magento2/commit/0811a711fb78e5df2153055d78504cc890fece30)

The fix will be available with the upcoming 2.3.1 release.

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-19645-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19645-2-2-develop.instances.magento-community.engineering/admin](https://i-19645-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#20457 by @suryakant-krish in 2.2-develop branch
Related commit(s):
 - [4cdc2f0781647eb6d3d06d4adccaebe365361683](https://github.com/magento/magento2/commit/4cdc2f0781647eb6d3d06d4adccaebe365361683)

The fix will be available with the upcoming 2.2.8 release.
