### ISSUE TITLE
Backend Marketing Store View Specific Labels Options Label not aligned

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#19647]
### Preconditions (*)

1.Magento 2.3-Develop

### Steps to reproduce (*)

1.Open Backend
2.Marketing -> Cart Price Rules -> Labels -> Store View Specific Labels 
3.Check  Options Alignment

### Expected result (*)

![expected](https://user-images.githubusercontent.com/33230237/49685134-f2b19c80-fb03-11e8-8e29-eafd1008423b.png)

### Actual result (*)

![actual](https://user-images.githubusercontent.com/33230237/49685138-fe04c800-fb03-11e8-9fff-3e9cfacf4cbf.png)

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97178` were created

**Comment by misha-kotov** [comment]
@speedy008 @dmytro-ch which browser was used for testing?

**Comment by SyntaxKay** [comment]
@misha-kotov 
Chrome Version 71.0.3578.98

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-19647-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19647-2-3-develop.instances.magento-community.engineering/admin](https://i-19647-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am working on this issue #cdwebkul

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sanjaychouhan-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sanjaychouhan-webkul, here is your [Magento instance](https://i-19647-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19647-2-3-develop.instances.magento-community.engineering/admin](https://i-19647-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Karlasa** [comment]
got fixed under PR #22423
will close this issue.
