### ISSUE TITLE
Unable to define Translation Function before Magento_Framework

### ISSUE THREAD

**Issue by bentideswell** [magento/magento2#19671]
Running Magento 2.2.7 and above when installed using Composer changes the registration.php include order. When installed via GitHub, the Magento Framework's registration.php is included after all the module registration.php files. This allows custom modules to define the translation function. When installed via composer, the framework's registration.php is included first, making it impossible to define the translation function without modifying a core Magento file.

### Preconditions (*)
1. Magento 2.2.7 installed via Composer (not a GitHub installation)

### Steps to reproduce (*)
1. Install Magento 2.2.7 or above via Composer
2. Setup a custom module and in your modules registration.php, add:

```
if (function_exists('__')) {
  echo 'Translation function already defined. It is not possible to replace this function.';
  exit;
}
else {
  echo 'Translation function not yet defined.';
  exit;
}
```

### Expected result (*)
1. The translation function should not yet be defined so the 'Translation function not yet defined' message should be displayed.

### Actual result (*)
1. The registration.php from Magento_Framework has already been included so the translation function has already been defined. The 'Translation function already defined' message is displayed.

Regardless of whether Magento is installed via Composer or GitHub, it should be possible to define the translation function in a custom module before Magento defines it (Magento/Framework/Phrase/__.php).

This is the whole point of Magento removing app/functions.php and adding the translation function to the framework and wrapping it in a call to function_exists. This works on GitHub (where the dev who did it probably tested it) but breaks with Composer.

Magento should ensure that the Magento_Framework registration.php loads last, giving custom modules a chance to define the translation function (wrapped in a call to function_exists('__') of course).

**Comment by magento-engcom-team** [comment]
Hi @bentideswell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bentideswell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by orlangur** [comment]
@bentideswell,

> it should be possible to define the translation function in a custom module before Magento defines it 

What is the basis for such expectation?

> This is the whole point of Magento removing app/functions.php and adding the translation function to the framework and wrapping it in a call to function_exists

Nope, you can read the corresponding PR. `function_exists` is just for compatibility with installations where `app/functions.php` is still not removed.

Please tell more on what are you trying to achieve.

**Comment by bentideswell** [comment]
I am the developer of [FishPig_WordPress](https://github.com/bentideswell/magento2-wordpress-integration), a popular free Magento WordPress Integration module that integrates the WordPress code base into Magento. 

In Magento 2, the __ function now returns a Phrase object rather than a string. This breaks some code in WP that use this function to define array keys.

Here's an example from WordPress:

`$someArray[__('Monday')] = 'Monday';`

This throws an error because it sets the array key as a Phrase object rather than a string.

To get around this I define the translation function before Magento. My version of this function is identical to the default Magento version except a small change.

```
if (!function_exists('__')) {
  function __()
  {
    $argc = func_get_args();
    $text = array_shift($argc);

    if (!empty($argc) && is_array($argc[0])) {
      $argc = $argc[0];
    }
  
    if (isset($GLOBALS['phrase_as_string'])) {
      return (string)new \Magento\Framework\Phrase($text, $argc);
    }
  
    return new \Magento\Framework\Phrase($text, $argc);
  }
  
  FishPig\WordPress\Model\Integration\CoreTest::setMagentoTranslationPatchIsApplied(true);
}
```

The extra part is:
```
if (isset($GLOBALS['phrase_as_string'])) {
  return (string)new \Magento\Framework\Phrase($text, $argc);
}
```

All this does is ensure that the return type is a string. The global variable that triggers this function is set when my module starts the WordPress simulation and this is unset when code is returned to Magento. It has no effect on Magento at all.

To get around this, I have had to add code to my module to patch the Phrase/__.php file. This is something I really want to avoid. I want to achieve this without modifying any core files.

All code in Magento is extensible except the __ function. Allowing custom modules to define it first (as is possible when insalling Magento via GitHub) would be perfect. Would this be possible?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by kunj1988** [comment]
I think you can try this:
```
$monday= __('Monday');
$someArray[$monday->getText()] = 'Monday';

```

**Comment by bentideswell** [comment]
@kunj1988 I think you misunderstand the issue. Yes it would fix the issue to call getText() on every instance of the __ function, it would also work to cast it as a string. This isn't possible though as the code is core WordPress code. The example I gave was a basic example to highlight the issue but WordPress is littered with code just like this.

**Comment by orlangur** [comment]
@bentideswell very interesting case.

How did https://github.com/bentideswell/magento2-wordpress-integration/blob/master/functions.php work before when `__` function was defined in `app/functions.php`?

**Comment by bentideswell** [comment]
Previously I modified app/functions.php directly and copied my functions.php into app/functions.php.

The best solution would be for the __ function to always return a string. This would solve the issue completely. This is how it worked in M1.

I had a discussion with @Vinai about this [here](https://github.com/magento/magento2/issues/5170). The only instance it seems where a Phrase object is used is in the \Magento\Framework\Exception\LocalizedException, but is this needed and could it be refactored?

Alternatively if I could include a file before the Magento_Framework registration.php, I could define the function before Magento does.

Another option would be for the the Magento function definition to include the small change that I ad myself, although I think this is the least likely solution.

**Comment by orlangur** [comment]
@bentideswell,

> Previously I modified app/functions.php directly and copied my functions.php into app/functions.php

So, nothing has changed from this perspective due to `__` declaration movement.

> The best solution would be for the __ function to always return a string

This is not a solution at all. `Phrase` was intentionally made lazy-evaluated.

> Alternatively if I could include a file before the Magento_Framework registration.php, I could define the function before Magento does

Feel free to provide such pull request. However, generally loading order of Composer packages is not guaranteed.

> Another option would be for the the Magento function definition to include the small change that I ad myself, although I think this is the least likely solution.

Yep, this would be pretty strange condition for core.

To summarize, I don't see any core "bug" here. `__` function is not customizable and you was never able actually customize it. What you actually did is rewriting of `app/functions.php`, now you need to rewrite `Magento/Framework/Phrase/__.php`. I would recommend using Composer patches for this.

**Comment by bentideswell** [comment]
When the declaration for __ was moved the Framework, a GitHub installation of Magento 2 loaded the registration.php of modules before it loaded the registation.php of Magento_Framework. In this situation I was able to define the translation function in registration.php and this was called prior to the M2 implementation of it. This is the perfect solution.

I really don't want to have to patch Magento core files. A lot of servers only have read access and it makes installing my module difficult.

I agree that this isn't really a bug. I couldn't think of a more suitable place to post this, hence why I posted it here.

The only potential way that this could be a bug is that different installation options produce different results. Installing via GitHub loads modules in a very different order to composer. Wouldn't this technically be a bug? Shouldn't the system be the same, regardless of the installation choice?

**Comment by Vinai** [comment]
Just to chime in here, I still find the `Phrase` and it being evaluated lazily a suboptimal situation.
For example, if I call `__()` inside `\Magento\Framework\App\State::emulateAreaCode` , I expect the phrase to translated according to the emulated area, but it is in fact translated later after the emulation ends (well, depending on when it's cast to a string).
Of course there are workarounds (explicit cast to string, rewriting `Phrase` to encapsulate the current locale, ...), but returning a string would be so much simpler.

What was the reasoning to introduce the `Phrase` object and make it lazily evaluated without encapsulating the current locale when it is called? Maybe an explanatory comment in the class definition could be added so it is less annoying when people run into issues with it?

**Comment by ghost** [comment]
Hi @bentideswell thank you for you report,  `__ function is not customizable and you was never able actually customize it.` 
There no issue here for core magento functional.
You can report here -> https://github.com/magento/community-features

**Comment by orlangur** [comment]
@bentideswell,

> The only potential way that this could be a bug is that different installation options produce different results. Installing via GitHub loads modules in a very different order to composer. Wouldn't this technically be a bug? Shouldn't the system be the same, regardless of the installation choice?

System should be the same, components should be written in such a way that system behavior does not depend on their order of loading.

@Vinai good point, I don't remember why lazy evaluation was considered the benefit, probably inline translation is quite slow or something. Will raise this question in `#appdesign`.

**Comment by bentideswell** [comment]
I understand that this isn't a bug and not even an issue but if it was possible to allow a custom translation function to be defined without breaking any Magento functionality, would that be an issue?

I have created a simple [pull request](https://github.com/magento/magento2/pull/19756) that does exactly this. It delays the loading of the __ function to after the app/autoload.php file has finished. This gives any module with a registration.php file the chance to define the __ function. This is how things already work when installing via GitHub as the Magento Framework registration.php file is loaded last, meaning other modules can first define the __ function.

The pull request makes only a few small changes, doesn't affect Magento performance while allowing integrations with other applications that use __ as the translation function name.
