### ISSUE TITLE
Modifying Page cache parameters

### ISSUE THREAD

**Issue by jayankaghosh** [magento/magento2#19676]
### Summary (*)
Supposing a developer wants to create two versions of the homepage. One for guest users and one for logged in users. There's no easy way to do it.

### Examples (*)
I have injected a dynamic block into the homepage where I am echoing content based on the customer's login state. But that value is getting cached. After some research, I've found that the `Magento\Framework\App\PageCache\Identifier::getValue()` method is responsible for creating/rendering the page cache. But since it returns a string (serialized and then sha1 hashed), the only way to modify it is to add an around plugin for it and copying and pasting everything on the original function into it, then modifying

### Proposed solution
There should be another method called, let's say `Magento\Framework\App\PageCache\Identifier::getParameters()` which should return the array of parameters and the `Magento\Framework\App\PageCache\Identifier::getValue()` method should just have `return sha1($this->serializer->serialize($this->getParameters()));` so that developers may write an after plugin for the `getParameters` method and modify the parameters as required.

__P.S__ We could also implement di so that developers can inject modifiers to the parameters as well

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jayankaghosh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by sivaschenko** [comment]
Hi @jayankaghosh , thanks for your report. The `Magento\Framework\App\PageCache\Identifier` is using data from `Magento\Framework\App\Http\Context` to get a variation hash. The HTTP context does have `customer_logged_in` value set here https://github.com/magento/magento2/blob/6478d2b09297859c4a082d71a78186d7b6600177/app/code/Magento/Customer/Model/Session.php#L428 so there should be no need for additional modifiers. There are two separate home page caches for logged in and not logged in customer based on the http context value.

Please take a look at how block content is differentiated based on customer login state i.e. here: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/Block/Account/AuthorizationLink.php

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by jayankaghosh** [comment]
Hi @sivaschenko, I just gave the customer login state as an example. There might be other modifiers required at times. For example, our company was working on a module recently to show dynamic data based on the customer's country. The only other choice we had left was to use a uiComponent, when it could've easily be done by creating separate page caches based on country

**Comment by orlangur** [comment]
@jayankaghosh that's what contexts are intended for.

For example, there is a context for currency already: `\Magento\Framework\App\Http\Context::CONTEXT_CURRENCY`. Check how it is implemented and do similarly for a country.

**Comment by jayankaghosh** [comment]
Hi @orlangur . I wasn't aware of that. Ok I'll have a look on that. Thanks

**Comment by ghost** [comment]
Hi @jayankaghosh thank you for you report, we closing this as this is non-issue,
