### ISSUE TITLE
Product's images cache not displayed /regenerated after Flush Catalog Images Cache

### ISSUE THREAD

**Issue by Drakas** [magento/magento2#19670]
### Preconditions (*)
1.Magento 2.3.0
2. Mysql 5.6.41
3. Php 7.2

### Steps to reproduce (*)
1. Import products with images
2. Go on Magento's Backed and click on: Flush Catalog Images Cache  

### Expected result (*)
1. Product's Images cache regenerated on visiting the single page's product
2. See the images of products that point on the cache folder

### Actual result (*)
1.  Cache's images not found and of course not displayed
For example:
pub/media/catalog/product/cache/9d08971813a040f8f96067a40f75c615/b/l/bl0090-41_05.jpg with bl0090-41_05.jpg that not exist or regenerated. 
2. The image of Catalog of product on frontend and backend are displayed correctly
3. No apache errors, php or exception thrown 
4. Flush Catalog Images Cache works but it takes too much times for works (hours) on most shared hosting.

**Comment by magento-engcom-team** [comment]
Hi @Drakas. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Drakas do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Drakas** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by Drakas** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @Drakas. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Drakas, here is your [Magento instance](https://i-19670-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19670-2-3-0.instances.magento-community.engineering/admin](https://i-19670-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @Drakas  i'm not able to reproduce following steps you described on clean magento 2.3.0 instance. In my case i have -> Product's Images cache regenerated on visiting the single page's product

**Comment by sjamesc** [comment]
@Drakas did you ever solve this? I'm having the same problem and curious if you came to a solution here.

**Comment by ankit-sf** [comment]
same issue

**Comment by rodrigowebjump** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-19670-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19670-2-3-0.instances.magento-community.engineering/admin](https://i-19670-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rodrigowebjump** [comment]
Hi
The issue was not reproduced.
The images are automatic generated by pub/get.php file. Probably the issue is related with webserver configuration.

**Comment by 29sunil** [comment]
Hello Friends,

We are facing same problem. After flush Flush Catalog Images Cache .Product images are not showing at list and details page. our Magento version is 2.3.0. 
Our PHP version is 7.1. So kindly suggest to us what is the reason.  If it is server issue then what is missing .

**Comment by mattyl** [comment]
I am experiencing this across a number of magento installations 2.2.9 and 2.3.3 - after flushing image cache - only product image is rengenerated, media gallery isnt - I am forced to do the teerrible bin/magento catalog:image:resize command (terrible because its very slow on large catalogues and if it fails you have to start from the begining - would be better if we could batch, define start number)

**Comment by jonasGossiaux** [comment]
Still having this issue on magento 2.3.5-p1, we are using a custom theme with a custom view.xml file.
It seems as if the image cache is not regenerating after flushing it

**Comment by manuelcanepa** [comment]
Same issue here `bin/magento catalog:image:resize` takes forever

**Comment by vertic4l** [comment]
Why is this closed ? It's still an issue magento 2.3.5-p1

**Comment by mattyl** [comment]
My issue turned out to be nginx settings on plesk - it worked better with apache and using the pleask settings to keep proxy mode on solved the issue for me. I am sure someone could make the nginx configuration work so the permission were correct for on the fly file creation but i found the combo of plesk and nginx extremely cumbersome.

**Comment by mattyl** [comment]
that doesnt address how poor the command catalog:image:resize is, but it doesnt look like anyone wants to invest time improving that.
