### ISSUE TITLE
Magento 2 wrong paypal express checkout token specified

### ISSUE THREAD

**Issue by Raizer96** [magento/magento2#19691]
### Preconditions
Magento 2.3
Php 7.1

### Steps to reproduce 
Place an order, and check out, then click continue to Paypal and complete the checkout 

### Expected result
Order should be placed 

### Actual result
Magento return error: "wrong paypal express checkout token specified"
Payment Log
[2018-12-07 10:38:17] main.DEBUG: array (
  'url' => 'https://api-3t.paypal.com/nvp',
  'SetExpressCheckout' =>
  array (
    'PAYMENTACTION' => 'Sale',
    'AMT' => '14.00',
    'CURRENCYCODE' => 'EUR',
    'RETURNURL' => 'http://magento2.gioglipesca.it/paypal/express/return/',
    'CANCELURL' => 'http://magento2.gioglipesca.it/paypal/express/cancel/',
    'INVNUM' => '000000075',
    'SOLUTIONTYPE' => 'Sole',
    'GIROPAYCANCELURL' => 'http://magento2.gioglipesca.it/paypal/express/cancel/',
    'GIROPAYSUCCESSURL' => 'http://magento2.gioglipesca.it/checkout/onepage/success/',
    'BANKTXNPENDINGURL' => 'http://magento2.gioglipesca.it/checkout/onepage/success/',
    'SHIPPINGAMT' => '5.00',
    'ITEMAMT' => '7.38',
    'TAXAMT' => '1.62',
    'BUSINESS' => 'Giogli Pesca',
    'NOTETEXT' => NULL,
    'EMAIL' => '******',
    'FIRSTNAME' => '******',
    'LASTNAME' => '******',
    'MIDDLENAME' => NULL,
    'SALUTATION' => NULL,
    'SUFFIX' => NULL,
    'COUNTRYCODE' => 'IT',
    'STATE' => '******',
    'CITY' => '******',
    'STREET' => '******',
    'ZIP' => '******',
    'PHONENUM' => '******',
    'SHIPTOCOUNTRYCODE' => 'IT',
    'SHIPTOSTATE' => '******',
    'SHIPTOCITY' => '******',
    'SHIPTOSTREET' => '******',
    'SHIPTOZIP' => '******',
    'SHIPTOPHONENUM' => '******',
    'SHIPTOSTREET2' => '',
    'STREET2' => '',
    'SHIPTONAME' => '******',
    'ADDROVERRIDE' => 1,
    'METHOD' => 'SetExpressCheckout',
    'VERSION' => '72.0',
    'USER' => '****',
    'PWD' => '****',
    'SIGNATURE' => '****',
    'BUTTONSOURCE' => 'Magento_Cart_Community',
  ),
  'response' =>
  array (
    'TOKEN' => 'EC-3NE85213955529058',
    'TIMESTAMP' => '2018-12-07T10:38:17Z',
    'CORRELATIONID' => '586972c7a2030',
    'ACK' => 'Success',
    'VERSION' => '72.0',
    'BUILD' => '000000',
  ),
) [] []

**Comment by magento-engcom-team** [comment]
Hi @Raizer96. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Raizer96 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Raizer96 thank you for you report, i'm not able to reproduce following steps you described.
This may be related to your configuration with paypal account.
