### ISSUE TITLE
Magento 2.3 admin product catalag Value '100,000000' has to be numeric 

### ISSUE THREAD

**Issue by giuliano72** [magento/magento2#19694]
### Preconditions (*)

1. Magento 2.3.0
2. Country Settings Italia (override system default)
3. Currency settings and default setting for Currency to Euro
4.PHP 7.1.24-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:23:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.24-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans

### Steps to reproduce (*)

1.Bug show itself randomly sometimes allow access to product catalog, other throw error 'Value '100,000000' has to be numeric' for the first product it load
2. when success insert first product but with price bad formatted 
3. exception log report: [2018-12-10 17:18:51] main.CRITICAL: Value '100,000000' has to be numeric {"exception":"[object] (Zend_Currency_Exception(code: 0): Value '100,000000' has to be numeric at /mnt/toshiba480/Sites/local/www.magento2.local/vendor/magento/zendframework1/library/Zend/Currency.php:166)"} []

### Expected result (*)

1. for price of 100,00 Euro expected 100,00 € 
2.

### Actual result (*)

1. actual result 10.000.000,00 €
2.

**Comment by magento-engcom-team** [comment]
Hi @giuliano72. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@giuliano72 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by giuliano72** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @giuliano72. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @giuliano72, here is your [Magento instance](https://i-19694-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19694-2-3-0.instances.magento-community.engineering/admin](https://i-19694-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by giuliano72** [comment]
Just dropped the old mysql db and reinstalled from downloaded 2.3.0,zip but always the same problem with prices

**Comment by giuliano72** [comment]
The problem cannot be reproduced but i suppose that real problem is in hosting PHP enviroment that i cannot view in vanilla test instance

**Comment by giuliano72** [comment]
My PHP enviroment is localized

**Comment by giuliano72** [comment]
Ok i understand i will drop magento its impossible to provide a valid solution to my customers with this platform

**Comment by davidverholen** [comment]
Hey @giuliano72 ,
my best guess currently would be that for some reason the price is saved in the db with a , (comma) instead of . (point) as decimal separator. That seemingly leads to the decimal part of the price being interpreted as part of the integer value.
Does your hosting provider use one of the supported database servers? https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by giuliano72** [comment]
There is no hosting provider, local installation was used with 
- PHP 7.1.24-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:23:58) ( NTS )
- mysql 5.7.24 ubuntu 18.04.1 
and apache 2.4.29 virtual hosting 

and i checked the db entry on table **catalog_product_entity_decimal**
the value was with a point (.) this is a dump:

value_id, attribute_id, store_id, entity_id, value
1, 77, 0, 1, 100.0000

the problem probabily is on localization of Zend Framework as repoterd by exception of class ../vendor/magento/zendframework1/library/Zend/Currency.php on line 166 on method public function toCurrency($value = null, array $options = array())

the value arrives with comma (,) but in db is with (.) point so was formatted before with (,) as decimal separator according with it localization but on line 164 th is_numeric($value) does not recognize the value as number and force a Zens_Currency_Exception.
Actually the only way to unlock the use of administration area is to comment line 166 but formatting is still bad

**Comment by giuliano72** [comment]
![image](https://user-images.githubusercontent.com/6089666/49764648-4ffa4900-fcd0-11e8-9ba9-2300cadc6c95.png)
 and later 
![image](https://user-images.githubusercontent.com/6089666/49764700-702a0800-fcd0-11e8-9bce-50f8092c1afc.png)

**Comment by davidverholen** [comment]
@giuliano72 that's "interesting" ;)

since it seemingly cannot be reproduced on the provided instances (and you cannot view log files), I would try to reproduce it in a local instance tomorrow.

Could you maybe provide some php settings regarding localization that could be relevant for the behavior? (earlier you said, your php env. is localized)

**Comment by giuliano72** [comment]
[phpinfo.pdf](https://github.com/magento/magento2/files/2665164/phpinfo.pdf)

this is my phpinfo

**Comment by davidverholen** [comment]
@giuliano72 sry for the late answer, just as an update, so far I wasn't able to reproduce it on my local system

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@giuliano72, thank you for reporting!
I was not able to reproduce even after setting 
```
[intl]
intl.default_locale = it_IT
```
to my php.ini, also I tried setting it directly to the database, but this action is forbidden by phpMyAdmin validator.

**Comment by slackerzz** [comment]
This somehow depends from system locale, we had the same problem after upgrading from PHP 7.0.x to 7.1.x.
Setting the system locale to en_US.utf8 (it was it_IT.utf8) fixed the issue

**Comment by decece** [comment]
Hello,

just for the record, for whoever ends up in this thread: Check your PDO extensions!

We had this issue happen as well:
PHP 7.1 or 7.2
Debian 9
Magento 2.3

The database values were alright, but they weren't showing that well on the frontend (values multiplied, due to the comma and period being mixed out). On the backend you couldn't browse any product, due to the dreaded error: 'value x,000 has to be numeric'.

We had just installed PDO_SQLSERV extension using PECL (we also had to connect to a remote MS SQL server), and it seems it overrides locales set in php.ini. We disabled the extension, and after a service restart we were fine. We're using Microsoft's ODBC driver instead.

It seems the problem can be solved by specifying the right LC_Numeric value in PHP (perhaps doing so in .htaccess will solve the issue).

Source:
https://github.com/Microsoft/msphpsql/issues/840

**Comment by lucacondotta** [comment]
Hi everyone, I know this issue is closed but I found a possible solution.

By default, when you install sqsrv and pdo_sqlsrv extensions their configuration overrides the php configuration for locale (as @decece said) by reading LC_CTYPE or LC_ALL system variable ([Microsoft docs](https://docs.microsoft.com/en-US/sql/connect/php/non-system-locale-settings?view=sql-server-ver15#set-locale-info-using-the-pdo_sqlsrv-driver)).

I changed the configuration for the extensions in the following way:

```
sqlsrv.SetLocaleInfo = 0
```

and

```
pdo_sqlsrv.set_locale_info = 0
```
in order to prevent the extensions to override php configuration with values of those system variables (according to Microsoft documentation `0 => The driver ignores the system locale settings.`)
