### ISSUE TITLE
Braintree environment specific settings

### ISSUE THREAD

**Issue by leoquijano** [magento/magento2#19699]
Hello,

### Summary (*)

When using the sensitive and environment specific settings feature of Magento 2.2 (https://devdocs.magento.com/guides/v2.2/extension-dev-guide/configuration/sensitive-and-environment-settings.html), Braintree correctly configures the ```payment/braintree/private_key``` as a sensitive setting.

_Note_: I'm using Magento 2.2.7.

See: ```app/code/Magento/Braintree/etc/di.xml```

However, it doesn't configure environment specific settings, including:
- The environment type (production vs sandbox).
- The private key.
- The public key.
- The merchant ID.
- The merchant account ID.

See: https://articles.braintreepayments.com/control-panel/important-gateway-credentials
The following additional settings might be helpful as well:
- The Kount ID.
- The debug enabled status.
- The PayPal module debug enabled status.

This means that if you run: 

```bin/magento app:config:dump```

... while having Braintree configured, Magento will export the settings above as shared settings. This means that they will be shared between production and sandbox sites (or any other setups the developer may have), when using the pipeline deployment system.

### Examples (*)

This is an issue when configuring different Braintree accounts across production and staging sites, since they will have different settings.

For example, if a production site has live Braintree public and private keys while a staging site has sandbox ones, developers won't be able share the ```app/etc/config.php``` settings between them. This is a problem since the purpose of a staging site is to _replicate_ production as close as possible, modeling factor 3 in the 12-factor app design guidelines (as mentioned [here](https://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/)).

### Proposed solution

Add the settings mentioned above to the environment specific type pool.

In ```app/code/Magento/Braintree/etc/di.xml```.

```xml
<type name="Magento\Config\Model\Config\TypePool">
    <arguments>
        <argument name="sensitive" xsi:type="array">
            <!-- ... -->
        </argument>
        <argument name="environment" xsi:type="array">
            <!-- ... -->
            <item name="payment/braintree/environment" xsi:type="string">1</item>
            <item name="payment/braintree/kount_id" xsi:type="string">1</item>
            <item name="payment/braintree/merchant_id" xsi:type="string">1</item>
            <item name="payment/braintree/merchant_account_id" xsi:type="string">1</item>
            <item name="payment/braintree/public_key" xsi:type="string">1</item>
            <item name="payment/braintree/private_key" xsi:type="string">1</item>
            <item name="payment/braintree/debug" xsi:type="string">1</item>
            <item name="payment/braintree_paypal/debug" xsi:type="string">1</item>
        </argument>
    </arguments>
</type>
```

**Comment by magento-engcom-team** [comment]
Hi @leoquijano. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@leoquijano do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by leoquijano** [comment]
Thanks @magento-engcom-team. 

Summary, information and expected/actual results are available in the description above.

The environment specific configuration is clear from ```app/code/Magento/Braintree/etc/di.xml```, so no new Magento instance is required to confirm. But please let me know if you need anything else.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @leoquijano thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by leoquijano** [comment]
Thanks @engcom-backlog-nazar. 

Here it is: magento/community-features/issues/103

**Comment by sdzhepa** [comment]
Hello @leoquijano 
Thank you for creating a Feature Request!
To avoid duplication I am closing this one.
Please continue tracking the process  by this reference:  https://github.com/magento/community-features/issues/103

Thank you for collaboration
