### ISSUE TITLE
[Bundle product] Shipment type "separately" not working

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#19692]
Can be reproduced on a normal Magento instance with sample data.

### Preconditions (*)

1. Magento Open Source 2.3 (also 2.2.7)

### Steps to reproduce (*)

1. Bundle product with shipment_type set to "Separately"
2. Product flat index enabled
3. Paypal Express enabled and configured
4. Buy the bundle product product using Paypal Express
5. Create a shipment

### Expected result (*)

1. When creating a shipment from admin, each item from the bundle product can be shipped

### Actual result (*)

1. Items cannot be shipped separately, behaves like Shipment Type: Together

The reason for this is because attribute **shipment_type** of bundle product is not inside product index so when quote_item is transformed into order_item the attribute is null.

The attribute has a [custom source model](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Bundle/Model/Product/Attribute/Source/Shipment/Type.php) which doesn't implement [getFlatColumns](https://github.com/magento/magento2/blob/2.3.0/app/code/Magento/Eav/Model/Entity/Attribute/Source/AbstractSource.php#L116) so it cannot get included in the index.

The solution is probably just to implement that method:
```
public function getFlatColumns()
    {
        $attributeCode = $this->getAttribute()->getAttributeCode();

        return [
            $attributeCode => [
                'unsigned' => false,
                'default' => null,
                'extra' => null,
                'type' => \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                'length' => null,
                'nullable' => true,
                'comment' => $attributeCode . ' column',
            ],
        ];
    }

   
    public function getFlatUpdateSelect($store)
    {
        return $this->optionFactory->create()->getFlatUpdateSelect($this->getAttribute(), $store, false);
    }
```

Maybe related #8809.

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@domeglic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by mahesh-rajawat** [comment]
@domeglic i have created two orders, one with **ship bundle items Together**  and one with **separately**,  you can check both conditions, 
For Separately: https://prnt.sc/lt821r .
For Together: https://prnt.sc/lt832d .

I am not able to reproduce it.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by domeglic** [comment]
@maheshWebkul721 I was only able to reproduce the issue using Paypal Express (the one included in Magento).

@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @domeglic, here is your [Magento instance](https://i-19692-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19692-2-3-0.instances.magento-community.engineering/admin](https://i-19692-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by domeglic** [comment]
@magento-engcom-team I cannot reproduce this on the deployed vanilla instance because it has no paypal express and I cannot reindex product flat after activating it since it requires CLI.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @domeglic thank you for you report i'm not able to reproduce following steps you described.
Please look at attachments
![download](https://user-images.githubusercontent.com/40756439/49792613-df891180-fd3b-11e8-8567-ff07a3a3cafa.png)
