### ISSUE TITLE
Datepicker misaligned on product edit page

### ISSUE THREAD

**Issue by sreichel** [magento/magento2#19695]
### Preconditions (*)

1. 2.3.0

It seems it already fixed / not broken in 2.3-develop, but I cant any PR.

### Steps to reproduce (*)

1. open admin product edit page (some for advanced pricing)
2. check date picker position

### Expected result (*)

1. correct position

### Actual result (*)

![m2-datepicker](https://user-images.githubusercontent.com/5022236/49749981-00088b80-fcaa-11e8-8711-b45f23d60deb.PNG)

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sreichel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sreichel** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sreichel, here is your [Magento instance](https://i-19695-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19695-2-3-0.instances.magento-community.engineering/admin](https://i-19695-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sreichel** [comment]
Duplicate ... https://github.com/magento/magento2/pull/18638
