### ISSUE TITLE
MoneyBooker -> "Validate email" return "404 Not Found"

### ISSUE THREAD

**Issue by hackin88** [magento/magento2#197]
MoneyBooker -> "Validate email" return "404 Not Found"

When accessing

/backend/admin/system_config/edit/section/moneybookers

and click on "Validate email" is returned the error page not found

http://localhost/magento2.0.0.0-dev39/index.php/backend/admin/moneybookers/checkemail/key/466c55f3dec470116c6a2b1f9740cb81/?email=&isAjax=true&&form_key=Ok5ZOUtApAATBRSs

**Comment by gabrieldagama** [comment]
Hi @hackin88. Thank you for your report. 
The issue has been fixed in magento/magento2#30774 by @vovayatsyuk in 2.4-develop branch
Related commit(s):
 - [e4c9861c6ed88f4b4081d0779af78cd0069fa5a9](https://github.com/magento/magento2/commit/e4c9861c6ed88f4b4081d0779af78cd0069fa5a9)

The fix will be available with the upcoming 2.4.2 release.
