### ISSUE TITLE
Javascript translation issue on modal buttons when removing items from product compare page

### ISSUE THREAD

**Issue by mfickers** [magento/magento2#19705]
### Preconditions

1. Magento 2.3.0 Open Source
2. At least one product available in store
3. A translation file for the luma theme and storefront locale containing the phrase `"Cancel","Test"`
4. Static Content is deployed for the right locale and the translation cache is cleaned

### Steps to reproduce

1. Add an item to product compare list
2. Go to product compare page
3. Click on the remove item icon

### Expected result

1. A modal pops up asking to confirm the removal
2. The left button of this modal should have the text "Test" on it

### Actual result

1. The text of the left modal button is "Cancel"

### Additional information
The very first item in my js-translation.json is `"Cancel":"Test"`, so this is not the issue.

When `mage/translate.js` is called from `modal/confirm.js` the `_data[]` array is empty:

![bildschirmfoto 2018-12-11 um 15 03 42](https://user-images.githubusercontent.com/12683535/49805683-0bb18c00-fd56-11e8-8d0c-749bb0742c9a.png)

During the same page load, it will be loaded containing all phrases from the js-translation.json including the right phrase:

![bildschirmfoto 2018-12-11 um 15 04 07](https://user-images.githubusercontent.com/12683535/49805690-0f451300-fd56-11e8-9d54-c7d512b91927.png)

**Comment by magento-engcom-team** [comment]
Hi @mfickers. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mfickers do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97061` were created

**Comment by mfickers** [comment]
There is already [this pull request](https://github.com/magento/magento2/pull/17275) which fixed the same issue in 2.2, the fix was ported to 2.3, but does not seem to work anymore.

**Comment by mfickers** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @mfickers. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @mfickers, here is your [Magento instance](https://i-19705-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19705-2-3-0.instances.magento-community.engineering/admin](https://i-19705-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mfickers** [comment]
In Magento 2.2, `translate-init` will be called _before_ the first time a js string is translated, in Magento 2.3 there are some strings where this is not the case.

I logged every call to translate.translate with console.log(text, _data[text]) and every call to translate.add with console.log('translator initialized') and this was the output:
<img width="311" alt="bildschirmfoto 2018-12-14 um 17 15 29" src="https://user-images.githubusercontent.com/12683535/50014300-e033d900-ffc3-11e8-9e6c-c36cc3efadb1.png">

I haven't found out why the order in which translate-init and the confim modal are loaded is wrong, but that is the issue.

**Comment by mfickers** [comment]
[This commit](https://github.com/magento/magento2/commit/459ce25867fe931bdac856ec2cd275731e29640e) refactored the translator initialisation into its own javascript file, but does not make sure the requirejs dependencies are right, which breaks js-translations in some parts. `translate-init`and especially its `callback`-function will not always be loaded _before_ the first time translate.translate() is called.

As a temporal fix I overrode `Magento_Translation/view/base/templates/translate.phtml` with the 2.2 version which rolls back the breaking change.

**Comment by magento-engcom-team** [comment]
Hi @mfickers. Thank you for your report. 
The issue has been fixed in magento/magento2#20109 by @mfickers in 2.3-develop branch
Related commit(s):
 - [dbf5c4577c6559edd7cfb28ba0d384050be7ddf5](https://github.com/magento/magento2/commit/dbf5c4577c6559edd7cfb28ba0d384050be7ddf5)
 - [a185ca1566097bdbec94bc3fbd356f976081baba](https://github.com/magento/magento2/commit/a185ca1566097bdbec94bc3fbd356f976081baba)

The fix will be available with the upcoming 2.3.1 release.
