### ISSUE TITLE
Qty per website or possibly store view, not global

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#19708]
### Description (*)
On different stores in the same instance of Magento 2, it would be useful to manage stock per website or per store view, and not globally.

### Expected behavior (*)
additional table cataloginventory_stock_item_store table to maintain different levels
cataloginventory_stock_status already contains website_id
ability to edit this in Manage Products level.
Update stock via API

### Benefits
Now that we have multiple sources of inventory, this would be a beneficial to a single magento install to manage those inventories for different store views

You would be able to sell different quantities on different stores

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by tomekjordan** [comment]
Confirming. Thats real disadvantage when you have 2 or more websites. Still cannot understand while Inventory tab mostly works ONLY with global values (min/max qty allowed in the cart, increments etc). 
Since Magento is multistore it should be configurable at website/store scope.
Probably you will get answer - to ask #msi to add this as "feature" :) and your ticket will be closed

**Comment by ghost** [comment]
HI @craigcarnell @tomekjordan this opportunity available on MSI module look -> https://github.com/magento-engcom/msi

**Comment by ingedicson** [comment]
Hi

Yes, this is an issue very important.

I have:

1 WebSite
1 Store
64 Store View (for Each one City in Colombia)

In each Store View and for each product, I need different quantities and prices different.

Example:

- Store View 1
SKU: 123
Name: T-Shirt
Qty: 100
Price: 25 USD

- Store View 2
SKU: 123
Name: T-Shirt
Qty: 50
Price: 30 USD

...

- Store View N
SKU: 123
Name: T-Shirt
Qty: Variable
Price: Variable



That two fields must be the scope Store View, not Global.

Please, I hope that in the versión 2.4.2 include this Issue.
