### ISSUE TITLE
PaymentTokenRepositoryInterface: missing setTotalCount in getList() method

### ISSUE THREAD

**Issue by textarea** [magento/magento2#19706]
### Preconditions (*)

1. Magento version 2.3.0

### Steps to reproduce (*)

/** @var \Magento\Vault\Api\PaymentTokenRepositoryInterface */
echo $this->paymentTokenRepository->getList(
    $this->searchCriteriaBuilder->create()
)->getTotalCount();

### Expected result (*)

1. returned the vault data total count 

### Actual result (*)

1. null

**Comment by magento-engcom-team** [comment]
Hi @textarea. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@textarea do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by textarea** [comment]
Issue: Confirmed

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97058`, `MAGETWO-97059` were created

**Comment by textarea** [comment]
Hello, have this pull request #19707

**Comment by magento-engcom-team** [comment]
Hi @textarea. Thank you for your report. 
The issue has been fixed in magento/magento2#19707 by @textarea in 2.3-develop branch
Related commit(s):
 - [0a2330a78de2aa7b2f752f05b7a055352100103e](https://github.com/magento/magento2/commit/0a2330a78de2aa7b2f752f05b7a055352100103e)
 - [eb62681291b73d80ffae7adbe2cdb28260059256](https://github.com/magento/magento2/commit/eb62681291b73d80ffae7adbe2cdb28260059256)

The fix will be available with the upcoming 2.3.1 release.
