### ISSUE TITLE
Magento 2.3 Shopping Cart Taxes Missing Calc Line

### ISSUE THREAD

**Issue by Rjgoolsby** [magento/magento2#19701]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Create Tax Rules with at least TWO rules. 
2. Make sure "Calculate Off Subtotal Only" is checked for both rules. 
3. Select the SAME Product Tax Class. We want to apply two separate taxes to product and we want them based off the subtotal. 
4. Create Virtual Product. (Important as there's no shipping with this store. Everything is pickup in store).
5. Add Selected Tax class from above to product.
6. Add Product to Cart.

### Expected result (*)

1. Tax Calculations should be broken out for guest to see
2. Tax Calculation is missing for last line. Calculation is correct. I verified the math but it's not showing up on the screen. See Screenshot 
![screen shot 2018-12-11 at 1 11 47 am](https://user-images.githubusercontent.com/10386821/49781951-8d67d200-fce2-11e8-83eb-86167dc9d02b.png)

### Actual result (*)

1. Calculation is correct but the totals aren't correctly showing up. Hospitality Tax should equal $0.36
2. SC Sales Tax should equal $1.26. 
3. Total is correct at $1.62. But not displaying correctly in summary. 

Confirm this is desired activity or a bug?

**Comment by magento-engcom-team** [comment]
Hi @Rjgoolsby. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Rjgoolsby do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Rjgoolsby Tax rules available only on EE version.
@Rjgoolsby , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by Rjgoolsby** [comment]
@engcom-backlog-nazar  I'm using Magento Community Edition. What do you mean Tax Rules are only in EE. I have screen shots showing it's available in the community edition. Please re-open ticket

**Comment by Rjgoolsby** [comment]
@engcom-backlog-nazar Is this a bot or a real person? 
Here's proof that Tax Rules aren't a EE feature 

https://docs.magento.com/m2/ce/user_guide/tax/tax-rules.html

These are the CE (Community Edition) User Docs. Please re-open ticket or specify whether this is desired behavior or a bug.

**Comment by engcom-backlog-nazar** [comment]
@Rjgoolsby Create Tax Rules with at **least TWO rules.**
I'm tolking about tax rules on Configuration, how you apply 2 tax rules on 1 product ?

**Comment by ghost** [comment]
hi @Rjgoolsby sorry for i misunderstood how apply 2 taxes from your description, now i'm able to reproduce it.
![selection_234](https://user-images.githubusercontent.com/40756439/49861202-03178f00-fe04-11e8-9279-6685baaf0986.png)

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97092`, `MAGETWO-97093` were created

**Comment by Rjgoolsby** [comment]
@engcom-backlog-nazar. Thanks. No worries. I know you all get a lot of these and it has to be hard to sort through them all. We're just upgrading to 2.3 so I figured I would help by posting things we encounter to help. Again thanks!!!

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Rjgoolsby. Thank you for your report. 
The issue has been fixed in magento/magento2#20682 by @niravkrish in 2.3-develop branch
Related commit(s):
 - [2258f50be930dddee4eb3e575e3826a2edbdd817](https://github.com/magento/magento2/commit/2258f50be930dddee4eb3e575e3826a2edbdd817)
 - [938eaf39d5406f8327d7cb445b0a16686aa7d063](https://github.com/magento/magento2/commit/938eaf39d5406f8327d7cb445b0a16686aa7d063)
 - [d6b100028f3c17a220015c44dde309c83557c4fa](https://github.com/magento/magento2/commit/d6b100028f3c17a220015c44dde309c83557c4fa)
 - [8e4c9ad3ce91dad42d5d22a60438d97fdf7d0380](https://github.com/magento/magento2/commit/8e4c9ad3ce91dad42d5d22a60438d97fdf7d0380)
 - [11b9b442109f13db51e9da589f42c57f42793c0d](https://github.com/magento/magento2/commit/11b9b442109f13db51e9da589f42c57f42793c0d)
 - [47a53b5039027850902d14d34edcff8b1d6ad686](https://github.com/magento/magento2/commit/47a53b5039027850902d14d34edcff8b1d6ad686)
 - [1c6138cf67cda426d6472560d3347eff62dac69e](https://github.com/magento/magento2/commit/1c6138cf67cda426d6472560d3347eff62dac69e)
 - [e5f5ecebd5a896bdcbf180434448c0fbfeffcb57](https://github.com/magento/magento2/commit/e5f5ecebd5a896bdcbf180434448c0fbfeffcb57)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @Rjgoolsby. Thank you for your report. 
The issue has been fixed in magento/magento2#21961 by @hiren0241 in 2.2-develop branch
Related commit(s):
 - [bd87d77581c8c62d1df853c6504df79ba66727f3](https://github.com/magento/magento2/commit/bd87d77581c8c62d1df853c6504df79ba66727f3)
 - [544100fc4b5bcfd0339e7bb61a393e53839e89d7](https://github.com/magento/magento2/commit/544100fc4b5bcfd0339e7bb61a393e53839e89d7)
 - [200fac8d63966b699a7a6e73f92b701e34c919c7](https://github.com/magento/magento2/commit/200fac8d63966b699a7a6e73f92b701e34c919c7)
 - [d41773877558c955cb8acbaa21a44209fd8de222](https://github.com/magento/magento2/commit/d41773877558c955cb8acbaa21a44209fd8de222)

The fix will be available with the upcoming 2.2.9 release.
