### ISSUE TITLE
Order purchase date filter range not showing expected results.

### ISSUE THREAD

**Issue by bilalyounus** [magento/magento2#19717]
### Preconditions

1. Magento 2.2.2, Nginx, Redis.
2. Magento local timezone AEDT, 
3. server time AEDT
4. mysql SELECT CURRENT_TIMESTAMP(); returns AEDT time 
5. SELECT @@global.time_zone, @@session.time_zone; returns SYSTEM.

### Steps to reproduce

1. Go to Sales order grid
2. Apply purchase date range it should be a week or more in my case it's from 5-12-2018 to 12-12-2018 (7 days).

### Expected result

1. It should display all orders in this range in my case it should show 42 orders.

### Actual result

1. Not displaying all order in from 5-12-2018 to 12-12-2018 (7 days), its showing 39 Order and the last order is 000153. See below screenshot for reference.

![selection_123](https://user-images.githubusercontent.com/4567395/49849213-584ea300-fdfa-11e8-93ad-b7f08a643c73.png)

2. When I increase my date range in my case 4-12-2018 to 12-12-2018 (8 days) it's showing 3 more orders from 5-12-2018. See below screenshot for reference.

![selection_124](https://user-images.githubusercontent.com/4567395/49849238-71efea80-fdfa-11e8-9296-e756936453cc.png)

**Comment by magento-engcom-team** [comment]
Hi @bilalyounus. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bilalyounus do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @bilalyounus Thank you for you report, this issue has already fixed in 2.3-develop branch , and available on 2.3.0 release.

**Comment by bilalyounus** [comment]
> Hi @bilalyounus Thank you for you report, this issue has already fixed in 2.3-develop branch , and available on 2.3.0 release.

It would be better if you provide me the patch for that.
