### ISSUE TITLE
Store switcher doesn't work multistore setup with different product urls

### ISSUE THREAD

**Issue by sreichel** [magento/magento2#19714]
### Preconditions (*)

1. any version
2. +1 storeview

### Steps to reproduce (*)

1. goadmin product edit page
2. switch to second storeview
3. set another URL in seo section
3.1. default URL: `some-name.html`
3.2 storeview URL: `some-localized-name.html`
4. check product on frontend
5. use storeswitcher more then once

Tested on https://pr-18895.instances.magento-community.engineering (2.3-dev) with product "Dekor Test".

### Expected result (*)

1. redirects between storeview

### Actual result (*)

1. redirect to home page

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sreichel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by hostep** [comment]
This is related to https://github.com/magento/magento2/issues/14674 I believe, but I'm not sure if it's an exact duplicate.

There is however [a comment](https://github.com/magento/magento2/issues/14674#issuecomment-442120476) in there, which might solve your problem (untested).

**Comment by sreichel** [comment]
@hostep it is maybe relatet, but not the same.

> On Stores -> Configuration -> Web , I set "Add Store code to URLs" to "YES"

I've default setup, w/o changing anything in config - see test instance.

For the comment ... not tested, but i guess it doesnt solve it, since target pathes uses same store id there ...

            $currentRewrites = $this->urlFinder->findAllByData([
                UrlRewrite::TARGET_PATH => $oldRewrite->getTargetPath(),
                UrlRewrite::STORE_ID => $targetStore->getId(),
            ]);

I think we wood need all latest target urls for all available storeview with storeview based category/product URL.

@sidolov @orlangur is it possible to set up test instances with different base URLs (subdomain/subfolder)?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97088`, `MAGETWO-97089` were created

**Comment by magento-engcom-team** [comment]
Hi @janakbhimani. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your report. 
The issue has been fixed in magento/magento2#19798 by @janakbhimani in 2.3-develop branch
Related commit(s):
 - [927ca80fca4c1ec298df925c137dba7d1d799808](https://github.com/magento/magento2/commit/927ca80fca4c1ec298df925c137dba7d1d799808)
 - [b36dc042a8ac9c414c65dffa7538ea1af1fc412f](https://github.com/magento/magento2/commit/b36dc042a8ac9c414c65dffa7538ea1af1fc412f)
 - [3d882cf115c48654012105c217aa8e0f09a92372](https://github.com/magento/magento2/commit/3d882cf115c48654012105c217aa8e0f09a92372)
 - [c7b4aaebf9898229196cb2287c8d5da57e2b01ef](https://github.com/magento/magento2/commit/c7b4aaebf9898229196cb2287c8d5da57e2b01ef)
 - [54a403993d2b6f919f018230854a33e1f8984e14](https://github.com/magento/magento2/commit/54a403993d2b6f919f018230854a33e1f8984e14)
 - [618d8e3c5ad7ac77f8d35ecce23788816a0b445d](https://github.com/magento/magento2/commit/618d8e3c5ad7ac77f8d35ecce23788816a0b445d)
 - [8a05dbb95cdb2162fb0b859d26a31d670e8b658d](https://github.com/magento/magento2/commit/8a05dbb95cdb2162fb0b859d26a31d670e8b658d)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your report. 
The issue has been fixed in magento/magento2#21140 by @janakbhimani in 2.2-develop branch
Related commit(s):
 - [bd1e5380e64634a2275d224c2c08e8d1dcd974e7](https://github.com/magento/magento2/commit/bd1e5380e64634a2275d224c2c08e8d1dcd974e7)
 - [a8861035b34da209b00d4a37a7704208853c0d0c](https://github.com/magento/magento2/commit/a8861035b34da209b00d4a37a7704208853c0d0c)
 - [78df524058bfeb23368cb865047e185aec80345b](https://github.com/magento/magento2/commit/78df524058bfeb23368cb865047e185aec80345b)
 - [7ebc03ffcd0a4ace268488112e101971cc2ad661](https://github.com/magento/magento2/commit/7ebc03ffcd0a4ace268488112e101971cc2ad661)
 - [7e4fe31d4b3ae19c8a462598b77b4bdf4fa4c36f](https://github.com/magento/magento2/commit/7e4fe31d4b3ae19c8a462598b77b4bdf4fa4c36f)

The fix will be available with the upcoming 2.2.9 release.

**Comment by AnotherAlexSmith** [comment]
@magento-engcom-team tell me please, when 2.2.9 will be available?

**Comment by hostep** [comment]
@AnotherAlexSmith: since Magento releases a new version every 3 months, it is expected that 2.2.8 will be released end of February and 2.2.9 end of May.

**Comment by TimQSO** [comment]
I guess this ticket should be reopened. The switches now works while not being logged in. But when you login with a customer account, the behaviour is like described in this ticket.

**Comment by hostep** [comment]
@GuiltyNL: that's a new bug being tracked in https://github.com/magento/magento2/issues/24942

**Comment by TimQSO** [comment]
@hostep Thanks!
