### ISSUE TITLE
404 on attribute set select

### ISSUE THREAD

**Issue by patvdleer** [magento/magento2#19722]
I've created a CSV for all the attributes and sets that need to be added and a script to import them. After doing so I'm unable to load the attribute sets in the admin while creating a new product. They (attribute sets) do show up in the list but once selected it returns a 404.

### Preconditions (*)

1. Magento CE 2.2.6 without sample data

### Steps to reproduce (*)

1. Added attributes and set via script

```php
/**
 * @param ModuleDataSetupInterface $setup
 * @param ModuleContextInterface $context
 * @throws \Magento\Framework\Exception\LocalizedException
 */
public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
{
    $setup->startSetup();
    $this->setup = $setup;
    $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);
    
    $categorySetup = $this->categorySetupFactory->create(['setup' => $setup]);
    $entityTypeId = $categorySetup->getEntityTypeId(\Magento\Catalog\Model\Product::ENTITY);
    $attributeSetId = $categorySetup->getDefaultAttributeSetId($entityTypeId);

    // Create attribute sets
    foreach($this->csv_helper->getAttributeSets() as $attributeSetName) {
        if($eavSetup->getAttributeSet($entityTypeId, $attributeSetName))
            continue;

        $this->logger->debug("Creating attribute set: $attributeSetName");            
        $eavSetup->addAttributeSet(
            $entityTypeId,
            $attributeSetName
        );
    }

    // Create attributes
    foreach($this->getAttributes() as $attributeData) {
        $attributeCode = $attributeData['code'];
        if ($eavSetup->getAttribute($entityTypeId, $attributeCode))
            continue;

        $this->logger->debug("Creating attribute: $attributeCode");
        
        $eavSetup->addAttribute(
            $entityTypeId,
            $attributeCode,
            $this->prepAttributeProperties($attributeData)
        );
    }
    
    $setup->endSetup();
}
```

```php
public function assignAttributeToSet($eavSetup, $attributeSet, $attributeCodes, $attributeGroupCode="General") {

    $entityTypeId = $eavSetup->getEntityTypeId('catalog_product');

    /** @var Set $attributeSet */
    foreach ($attributeCodes as $attributeCode) {
        $n = $attributeSet->getAttributeSetName();
        if(empty($n))
            continue;
    
        $attributeGroupId = $eavSetup->getAttributeGroupId(
            $entityTypeId, 
            $attributeSet->getId(), 
            $attributeGroupCode
        );

        if(!$attributeGroupId) {
            $eavSetup->addAttributeGroup(
                $entityTypeId, 
                $attributeSet->getId(), 
                $attributeGroupCode
            );
            $attributeGroupId = $eavSetup->getAttributeGroupId(
                $entityTypeId, 
                $attributeSet->getId(), 
                $attributeGroupCode
            );
        }
        
        $attributeId = $eavSetup->getAttributeId($entityTypeId, $attributeCode);
        $eavSetup->addAttributeToGroup(
            $entityTypeId, 
            $attributeSet->getId(), 
            $attributeGroupId, 
            $attributeId, 
            null
        );
    }
}
public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
{
    $setup->startSetup();
    $this->setup = $setup;
    $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);

    // Assign attribute to attribute set
    $attibutesToSets = $this->csv_helper->getAttributesToSets();
    foreach($this->getAttributes() as $attributeData) {
        $attributeCode = $attributeData['code'];
        if(array_key_exists($attributeCode, $attibutesToSets)) {
        				
            foreach($attibutesToSets[$attributeCode] as $attributeSetName) {                
                if(!$attributeData['group'] || empty($attributeData['group'])) {
                    $this->logger->error("Group is empty for attribute '$attributeCode'");
                    continue;
                }
                $this->logger->debug("Assigning '$attributeCode' to $attributeSetName");
                $this->assignAttributeToSet(
                    $eavSetup, 
                    $this->getAttributeSetByName($attributeSetName), 
                    array($attributeCode), 
                    $attributeData['group']
                );
            }
        }
    }
    $setup->endSetup();
}
```

2. `bin/magento setup:upgrade`
2. `bin/magento indexer:reindex`
3. `bin/magento cache:flush`
4. open admin
5. Validate the attribute set via `admin/catalog/product_set/index`

![image](https://user-images.githubusercontent.com/1138136/49865678-ea0fdd80-fe05-11e8-803c-00644c8cda85.png)

6. Add simple product
7. select attribute set

### Expected result (*)

1. attributes to add new product

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/1138136/49865734-06ac1580-fe06-11e8-8c9c-c11a33c27e88.png)

2. `POST /admin_/catalog/product/reload/type/simple/store/0/popup/1/componentJson/1/prev_set_id/12/key/XXXXX/?set=&isAjax=true`

POST DATA:
```
form_key=ZTg4P3I1Fi6j5Ftf
```

**Comment by magento-engcom-team** [comment]
Hi @patvdleer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@patvdleer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by patvdleer** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @patvdleer. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @patvdleer, here is your [Magento instance](https://i-19722-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19722-2-2-6.instances.magento-community.engineering/admin](https://i-19722-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by patvdleer** [comment]
Started digging, before the 404 request the following happens:
`/admin_/catalog/product/reload/type/simple/store/0/popup/1/componentJson/1/prev_set_id/9/key/XXX/?set=undefined&isAjax=true`

```
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 3 passed to Magento\Framework\View\Element\UiComponentFactory::mergeMetadataElement() must be of the type array, null given, called in vendor/magento/framework/View/Element/UiComponentFactory.php on line 379 and defined in vendor/magento/framework/View/Element/UiComponentFactory.php:329
Stack trace:
#0 vendor/magento/framework/View/Element/UiComponentFactory.php(379): Magento\Framework\View\Element\UiComponentFactory-&gt;mergeMetadataElement(Array, 'configurableExi...', NULL, false)
#1 vendor/magento/framework/View/Element/UiComponentFactory.php(404): Magento\Framework\View\Element\UiComponentFactory-&gt;mergeMetadataItem(Array, Array, false)
#2 vendor/magento/framework/View/Element/UiComponentFactory.php(404): Magento\Framework\Vi in <b>vendor/magento/framework/View/Element/UiComponentFactory.php</b> on line <b>329</b><br />
```

**Comment by patvdleer** [comment]
```php
/**
 * Merge metadata item to components
 *
 * @param array $bundleComponents
 * @param array $metadata
 * @param bool $reverseMerge
 * @return array
 * @throws LocalizedException
 * @since 100.1.0
 */
protected function mergeMetadataItem(array $bundleComponents, array $metadata, $reverseMerge = false)
{
    foreach ($metadata as $name => $data) {
        $selfData = $data;
        if (isset($selfData['children'])) {
            unset($selfData['children']);
        }

        list($bundleComponents, $isMerged) = $this->mergeMetadataElement(
            $bundleComponents,
            $name,
            $selfData,
            $reverseMerge
        );
```

the `$name` in this case is `configurableExistingAttributeSetId`

**Comment by patvdleer** [comment]
Issues seems related to:
* https://github.com/magento/magento2/issues/15117
* https://github.com/magento/magento2/issues/7825

**Comment by patvdleer** [comment]
Magento CE 2.2.7 has the same issue

**Comment by orlangur** [comment]
@patvdleer same as https://github.com/magento/magento2/issues/15117#issuecomment-394355268 - please provide clear steps to reproduce using Admin UI and not some custom scripts.

**Comment by patvdleer** [comment]
@orlangur when I use the Magento admin UI it does work but when I use a script, based on `eavSetupFactory`, to install the 400+ attributes over 30 attribute sets it fails. I currently can't upgrade to Magento 2.3.0 due to https://github.com/tig-nl/postnl-magento2/issues/78

**Comment by orlangur** [comment]
@patvdleer then you should figure out how your code is different from one involved when you create entity via Admin UI instead of reporting a "bug".

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @patvdleer thank you for you report, 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
If you like to update this, please reopen the issue.

**Comment by patvdleer** [comment]
Question moved to StackOverflow https://magento.stackexchange.com/questions/253483/magento-ce-2-2-x-unable-to-set-attribute-set-for-new-product
