### ISSUE TITLE
Strings not translated in all email templates, keep curly braces around string 

### ISSUE THREAD

**Issue by sezio** [magento/magento2#19728]
Hello 

In our mails, some strings are not translated and included with the curly brackets around it. 
But if magento send the same mail again to an other customer, it will probably be translated fine without the curly brackets around the string. 
We can't understand why the same string in the same mail templates, in the same language, are sometimes translated and sometimes not. 

### Preconditions (*)

1. 2.2.5
2. php 7.2
3. apache 2.4

### Steps to reproduce (*)

1. ?

### Expected result (*)

1. All the translation in all the sent mails are translated fine. 

### Actual result (*)

1. Curly braces are not removed from some translation in some mails. In other mails, the same translation are fine. 

Example 1 : 
Here is the subject of a wrong stock email alert : 
`{{{De retour en stock!}}{{De retour en stock!}}{{De retour en stock!}}{{theme}}}`
While other stock email alert are fine with the good translation : 
`De retour en stock!`

Example 2 :
In a first new_order mail with paypal payment method : 
`{{{Email du Payeur}}{{Email du Payeur}}{{Payer Email}}{{theme}}}`
In a second one, we'll have : 
`Email du Payeur`

Any help would be appreciated, I don't understand why it can be translated in some mails while not in some other. 
Did anybody already had the same issue ?

Thank you :)

**Comment by magento-engcom-team** [comment]
Hi @sezio. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sezio do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sezio** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @sezio. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sezio, here is your [Magento instance](https://i-19728-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-19728-2-2-5.instances.magento-community.engineering/admin](https://i-19728-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sezio** [comment]
Can't reproduce it on the vanilla instance because there's no possibility to install a language pack

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @sezio thank you for you report, the fix for this issue has already available on 2.3.0 release.

**Comment by steffen-wirth** [comment]
@engcom-backlog-nazar  is there any patch for 2.2 or can you link to the related commit ? thanks

**Comment by ghost** [comment]
@steffen-wirth maybe this one https://github.com/magento/magento2/pull/14914

**Comment by steffen-wirth** [comment]
@engcom-backlog-nazar the issue #14914 is different to the subject in this issue. i would say they are not related

**Comment by ghost** [comment]
@steffen-wirth i'm not talking about issue.

**Comment by steffen-wirth** [comment]
@engcom-backlog-nazar the issue #14914 was your suggestion for a patch or commit so why are you not talking about this? 
i think it is more related to #16633 or perhaps also #18519

**Comment by steffen-wirth** [comment]
hi @sezio did you had time to investigate it further? how did you solve this problem?

**Comment by sezio** [comment]
Hi @steffen-wirth 
I think this current issue is not related to your problem. This issue is only related to the translation in the order confrmation email. 

But if you have any problem with the js-translation file on the frontend (not in the emails), I posted a message here in #18519 : https://github.com/magento/magento2/issues/18519#issuecomment-431087337 explaining that the problem (for me), happened when the inline translation was enabled. It seems it broke my js translation file. When I disabled the inline translation, and after redeploying statc files, the problem was solved. 
So : 
1/ disable the inline translation 
2/ rm your pub/static/frontend directory 
3/ redeploy the frontend 

If you don't remove pub/static/frontend, I'm not sure magento will redeploy your js translation file  

Hope it helps !
