### ISSUE TITLE
Invalid "No Payment Method Needed" message in admin

### ISSUE THREAD

**Issue by navarr** [magento/magento2#19729]
When re-ordering an order that contains only virtual products, the message "No Payment Information Required" is erroneously displayed unless you update the order

### Preconditions (*)

1. Magento 2.3.0 installed with sampledata

### Steps to reproduce (*)

1. Navigate to instance homepage
2. Login as sampledata user (Veronica Costello)
3. Enter "Solo Power Circuit" into search bar and hit enter
4. Click "Add to Cart" button underneath "Solo Power Circuit" product
5. Click "Minicart" icon
6. Click "Proceed to Checkout" button
7. Click "Place Order" button.  Note the order number.
8. Login to admin panel
9. Click "Sales > Orders".  Navigate to Order placed via "View" link in grid
10. Click "Reorder" in header
11. View "Payment & Shipping Information" section

### Expected result (*)

1. Radio buttons for valid payment methods (such as "Check or Money Order") appear

### Actual result (*)

1. Message "No Payment Information Required"

### Notice
* Issue does not occur for orders placed with a Guest user

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@navarr do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by navarr** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @navarr, here is your [Magento instance](https://i-19729-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-19729-2-3-0.instances.magento-community.engineering/admin](https://i-19729-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
please check #15059

**Comment by navarr** [comment]
Yeah, this looks like a duplicate. Thanks
