### ISSUE TITLE
Cart Items are deleted after fail checkout

### ISSUE THREAD

**Issue by devmag1** [magento/magento2#19731]
### Preconditions (*)

1. Magento v2.1.7
2. Products should be added in the cart
3. Payment Gateway that accepts online transaction

### Steps to reproduce (*)

1. Add products to cart
2. Go to the checkout page
3. Fill out all the information
4. let's say I select PayUMoney payment gateway
5. Next, I click PLACE ORDER button (on click of this button the order gets placed as pending in the Magento 2 backend)
6. A popup opens asking me to enter credit card details
7. If I close the popup the cart/checkout is empty and there are no products that I had selected

### Expected result (*)

1. On PLACE ORDER button click, the order should not get placed in the Magento Backend.
2. On Succesful payment only, the order should get placed in the Magento backend
3. If I cancel/fail the order, then cart items should not get cleared and I should be able to checkout again with another payment option. 

### Actual result (*)

1. The order is placed on the backend as pending in Magento 2 backend irrespective of successful or failed payment.
2. If I cancel/fail the payment, the cart items should not get cleared and I should be able to reorder again through another or same payment gateway.

**Comment by magento-engcom-team** [comment]
Hi @devmag1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@devmag1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @devmag1  i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.

**Comment by devmag1** [comment]
I have upgraded the magento version 2.2.1 but it still reflects the same issue.

![screenshot from 2018-12-13 18-56-24](https://user-images.githubusercontent.com/45827428/49941561-e44ef080-ff08-11e8-8962-7f6a21473b8b.png)

I am using payumoney payment method. please check the below link
http://demotheme.tidbitsolutions.co/
