### ISSUE TITLE
[Frontend] Modal content in admin area is under the close button

### ISSUE THREAD

**Issue by vasilii-b** [magento/magento2#19733]
Modal content in admin area is under the close button.

### Preconditions (*)

1. Magento 2.3, Magento 2.3-develop
2. Any kind of product
3. Website with one store and 2 store views (at least) OR Website with 2 stores (and each of it with one store view)
4. Access to admin area

### Steps to reproduce (*)

1. Login to admin area
2. Open any product to edit
3. Where it says "Store View: All Store Views" click on the button to open the dropdown
![image](https://user-images.githubusercontent.com/13456702/49892329-667bde00-fe51-11e8-899e-c87ddeba9525.png)
4. Select any store store view

### Expected result (*)
Modal content is not under modal close button and can be easily read:
![image](https://user-images.githubusercontent.com/13456702/49892307-5401a480-fe51-11e8-8bc0-c28252b6b96c.png)

### Actual result (*)
Modal content is under the modal close button:
![image](https://user-images.githubusercontent.com/13456702/49892241-2b79aa80-fe51-11e8-86c6-591ccab131f3.png)

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vasilii-b do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-19733-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19733-2-3-develop.instances.magento-community.engineering/admin](https://i-19733-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @vasilii-b thank you for you report,  this issue has already fixed on 2.3-develop branch.

**Comment by vasilii-b** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b, here is your [Magento instance](https://i-19733-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19733-2-2-develop.instances.magento-community.engineering/admin](https://i-19733-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
