### ISSUE TITLE
Bundle Selection not loading ExtensionAttributes data

### ISSUE THREAD

**Issue by vo1** [magento/magento2#19732]
### Preconditions (*)

1. Magento 2.3 (and possibly below)

### Steps to reproduce (*)

1. Define new extension attribute for Magento\Bundle\Api\Data\LinkInterface (bundle selection item)
```
        <attribute code="selection_sap_id" type="string">
            <join reference_table="catalog_product_bundle_selection_extension_attributes" reference_field="selection_sap_id" join_on_field="selection_id">
                <field>selection_sap_id</field>
            </join>
        </attribute>
```
2. Try reading it via $selection->getExtensionAttributes()->getSelectionSapId()

### Expected result (*)

1. Field taken from external table via join

### Actual result (*)

1. Field is not present in _data of LinkInterface object

### Resolution
add joinProcessor to Magento\Bundle\Model\Product\Type class constructor and call it in getSelectionsCollection: $this->joinProcessor->process($selectionsCollection).

Currently AbstractDb::joinExtensionAttribute is not called on Selections collection. Also, since selection class is actually a product collection (```SELECT e.*, selection.* FROM catalog_product_entity AS e ... ```), join_on_field parameter for join must be changed to support dot, e.g. : join_on_field="selection.selection_id".
At this moment it tries to join on e.selection.selection_id resulting in invalid SQL.

**Comment by magento-engcom-team** [comment]
Hi @vo1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vo1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @vo1 thank you for you report, i'm not able to reproduce following steps you described, Please try create extension attributes correctly.
```
<extension_attributes for="Magento\Catalog\Api\Data\ProductInterface">
    <attribute code="stock_item" type="Magento\CatalogInventory\Api\Data\StockItemInterface">
        <join reference_table="cataloginventory_stock_item" reference_field="product_id" join_on_field="entity_id">
            <field>qty</field>
        </join>
    </attribute>
</extension_attributes>
```
In the following example, an attribute named stock_item of type Magento\CatalogInventory\Api\Data\StockItemInterface added to the Magento\Catalog\Api\Data\ProductInterface.
If you like to update this please reopen the issue.

**Comment by vo1** [comment]
Described them same way as catalog inventory by passing up all to a class.
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Bundle\Api\Data\LinkInterface">
        <attribute code="zzz_bundle_selection" type="ZZZ\Bundle\Model\BundleSelection">
            <join reference_table="catalog_product_bundle_selection_extension" reference_field="selection_id" join_on_field="selection_id">
                <field>sap_id</field>
                <field>isbn</field>
                <field>label</field>
            </join>
        </attribute>
    </extension_attributes>
</config>

```

Collection of Magento\Bundle\Api\Data\LinkInterface is retrieved by Magento\Bundle\Model\Product\LinksList::getItems(). it gets SelectionCollection via $selectionCollection = $this->type->getSelectionsCollection. 
**Problem 1:**
Neither LinksList::getItems() nor bundleType->getSelectionCollection uses extensionAttributesJoinProcessor to join attributes, and this method is used everywhere to retrieve bundle products selections.
**Problem 2: ** when you apply ```extensionAttributesJoinProcessor->process($selectionCollection, 'Magento\Bundle\Api\Data\LinkInterface')```, the SQL generated will be:

```
SELECT
	`e`.*, `selection`.*, `extension_attribute_zzz_bundle_selection`.`sap_id` AS `extension_attribute_zzz_bundle_selection_sap_id`,
	`extension_attribute_zzz_bundle_selection`.`isbn` AS `extension_attribute_zzz_bundle_selection_isbn`,
	`extension_attribute_zzz_bundle_selection`.`label` AS `extension_attribute_zzz_bundle_selection_label`
FROM
	`catalog_product_entity` AS `e`
INNER JOIN `catalog_product_bundle_selection` AS `selection` ON selection.product_id = e.entity_id
LEFT JOIN `catalog_product_bundle_selection_extension` AS `extension_attribute_zzz_bundle_selection` ON e.selection_id = extension_attribute_zzz_bundle_selection.selection_id
WHERE
	(
		(
			(
				(`e`.`required_options` != 1)
				OR (
					`e`.`required_options` IS NULL
				)
			)
		)
		AND (selection.option_id IN('1'))
		AND (
			selection.parent_product_id = '8'
		)
	)
AND (e.created_in <= 1)
AND (e.updated_in > 1)
ORDER BY
	`selection`.`position` ASC,
	`selection`.`selection_id` ASC
```
You can see here the problem I've described in initial post: ```ON e.selection_id = extension_attribute_zzz_bundle_selection.selection_id```
Because entity table is the main table here.
