### ISSUE TITLE
Customer import do not reindex customer grid

### ISSUE THREAD

**Issue by peterlembke** [magento/magento2#19741]
Customers that have been imported with the Magento importer do not show up in the admin customer grid.

### Preconditions (*)
Magento CE 2.2.5
Magento CE 2.3-develop branch

### Steps to reproduce (*)
Use Admin >> System >> Import >> "Customers main file" and import a customer file.

### Expected result (*)
Expect new customers to be visible in the admin customers grid.

### Actual result (*)
New imported customers do not show in the customers grid.

### Work around
A manual full reindex of "customer grid" is needed then the customers show in the list.

### Bug or feature request?
A quick poll at the office gave an overweight to bug.

### Why does this happen?
The importer in
\Magento\CustomerImportExport\Model\Import\Customer -> _importData()
use SQL to inject the data into the table and does not seem to reindex after the import.

### Suggested solution
Add indexing in _importData() at the end of each bunch.

$customerIdsToIndex = $this->pullOutAllAffectedCustomerIds($processedData);
$this->indexerHelper->reindexList('customer_grid', $customerIdsToIndex);
(This is a part of the code)

Yes the import will be slightly slower.
I have implemented this solution in a separate module and it works well.

### Does the latest version solve this?
There seem to be no mentioning of indexers in the code.
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CustomerImportExport/Model/Import/Customer.php
But there might be something at a lower level that I don't see.

### Similar tasks
I found no mention of customer import and customer grid in open or closed tasks.

**Comment by magento-engcom-team** [comment]
Hi @peterlembke. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@peterlembke do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97133`, `MAGETWO-97134` were created

**Comment by ghost** [comment]
Hi @peterlembke this is expected behavior, to do the reindex after you import the customers, you can configure cron job to reindex your customers.
https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-index.html
