### ISSUE TITLE
Magento 2.3.0 - Flush Static Files Cache

### ISSUE THREAD

**Issue by pjw345** [magento/magento2#19744]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1.25

Site has a digital certificate
Stores -> Configuration -> Web -> Base URLs (secure) -> Use Secure URLs in Admin -> Yes

### Steps to reproduce (*)

1. System -> Cache Management -> Flush Static Files Cache

### Expected result (*)

1. Should flush the static files cache

### Actual result (*)

1. Flushes the static files cache
2a. On next action the user is logged off, this didn't happen with 2.2.7 or previous versions
2b. This also appears to happen if you use the CLI php bin/magento setup:upgrade
2c. This behaviour doesn't appear to happen if "Use Secure URLs in Admin" is set to No

**Comment by magento-engcom-team** [comment]
Hi @pjw345. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pjw345 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pjw345** [comment]
I can confirm this happens on a vanilla Magento 2.3.0 version

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment]
@pjw345, thank you for reporting this issue.
I will post here a recording where everything works.
The possible reasons:
 - as you mentioned `php bin/magento setup:upgrade` can be the problem if upgrade wasperformed with errors.
 - there is an issue with logging off but this issue exissts regardless of the web protocol or static cache

**Comment by TomashKhamlai** [comment]
I was able to reproduce this twice in a row, so I changed my mind.

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97141` were created

**Comment by ghost** [comment]
I was also facing same issue.
But after correcting the permission of pub/static folder.
Everything just start working properly. So it can be permission issue.

**Comment by pjw345** [comment]
I've just checked the permissions on pub/static - directories are 775 and files are 664

**Comment by jurpro** [comment]
How to fix this issue? I still getting this error everytime flush static files cache

**Comment by cscd98** [comment]
https://github.com/magento/magento2/issues/20060

**Comment by magento-engcom-team** [comment]
@m2-backlog[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!
