### ISSUE TITLE
Wishlist button issue 

### ISSUE THREAD

**Issue by namratavora** [magento/magento2#19748]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Add product into Wishlist
2. Go to my Wishlist

### Expected result (*)

**Add to cart** and **Share wishlist** button should be primary color.
![2018-12-05_14-58-28](https://user-images.githubusercontent.com/24732024/49935964-84504e00-fef8-11e8-868d-5b887e2af248.jpg)

### Actual result (*)

Currently, All buttons have same color.
![2018-12-13_17-01-27](https://user-images.githubusercontent.com/24732024/49936040-d1342480-fef8-11e8-8ad1-46818e0efcfe.jpg)

**Comment by magento-engcom-team** [comment]
Hi @namratavora. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@namratavora do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by namratavora** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @namratavora. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @namratavora, here is your [Magento instance](https://i-19748-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19748-2-3-develop.instances.magento-community.engineering/admin](https://i-19748-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by namratavora** [comment]
I can reproduce issue on 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @namratavora .  We cannot consider it as an "issue" since the mentioned buttons have "action" class without "primary" class. It's done for a purpose like on the shopping cart page (update, clear, apply coupon). It does not mean that the buttons style is wrong somehow, it's just different. The design idea did not highlight these buttons as primary.

**Comment by namratavora** [comment]
I have checked those button color different on Magento 1's rwd theme so I have recommended to you.

**Comment by ghost** [comment]
@namratavora  this is new theme and new standards, this is not  `RWD` theme.

**Comment by priti2jcommerce** [comment]
Hi @engcom-backlog-nazar ,
I have seen the white space at top of the button, is this proper or  issue?

![2018-12-14_16-01_d1342480-fef8-11e8-8a](https://user-images.githubusercontent.com/18118695/49998314-fd63aa00-ffb9-11e8-8701-3640529d4f9c.jpg)

Please check the attach.
