### ISSUE TITLE
2.2.6 to 2.2.7 Upgrade - Create New Customer Account DOB calendar not showing

### ISSUE THREAD

**Issue by gilbertsohal** [magento/magento2#19740]
### Preconditions (*)

1. Magento 2.2.7
2. PHP 7.1

### Steps to reproduce (*)

1. Upgrade Magento 2.2.6 to 2.2.7
2. Add Dob field optional or mandatory
3. Check Create New Customer Account Page

### Expected result (*)

1. Create New Customer Account Page work as normal with DOB calendar icon field
2. Click on DOB Calendar icon show DOB calendar to select DOB
3. No JS errors showing in console 

Screenshot 1
https://prnt.sc/luahjv

Screenshot 2
![console-errors](https://user-images.githubusercontent.com/29964872/49915122-1dc33400-fee8-11e8-80cb-f8ae945dc03f.jpg)

### Actual result (*)

1. Create New Customer Account Page work as normal but without DOB calendar icon field
2. DOB Calendar icon not showing to select DOB
4. Bunch of JS errors showing in console

**Comment by magento-engcom-team** [comment]
Hi @gilbertsohal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gilbertsohal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gilbertsohal. Thanks for the report. I'm not able to reproduce following steps you described. Please see attachment of screen.
![dob](https://user-images.githubusercontent.com/41946904/49934187-5a862f80-fed6-11e8-91ed-cb93a5c62c9a.png)
