### ISSUE TITLE
Can not delete address from address book

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#19747]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Create an account
2. Add additional addresses to address book
3. Click on ' Delete Address' link in address book

### Expected result (*)

Additional address is removed from address book

### Actual result (*)

Customer is redirected to 404 not found page

![desktop screenshot](https://user-images.githubusercontent.com/8502721/49935200-b483f680-fed0-11e8-8da3-58e5803de074.png)

**Comment by magento-engcom-team** [comment]
Hi @lyusya-nnn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lyusya-nnn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @lyusya-nnn. Thanks for the report. I'm not able to reproduce following steps you described. Please see attachment of screen.
![delete_address](https://user-images.githubusercontent.com/41946904/49937818-a9d15d80-fee0-11e8-98da-b244370ce40c.png)

**Comment by lyusya-nnn** [comment]
Please make sure you are using the latest version - 2.3.0

Delete request is sent as GET request in magento2/app/code/Magento/Customer/view/frontend/web/js/address.js

 confirm({
                content: this.options.deleteConfirmMessage,
                actions: {

                    /** @inheritdoc */
                    confirm: function () {
                        if (typeof $(e.target).parent().data('address') !== 'undefined') {
                            window.location = self.options.deleteUrlPrefix + $(e.target).parent().data('address') +
                                '/form_key/' + $.mage.cookies.get('form_key');
                        } else {
                            window.location = self.options.deleteUrlPrefix + $(e.target).data('address') +
                                '/form_key/' + $.mage.cookies.get('form_key');
                        }
                    }
                }
            });


 but in controller its should be POST - magento2/app/code/Magento/Customer/Controller/Address/Delete.php
class Delete extends \Magento\Customer\Controller\Address implements **HttpPostActionInterface**

that generates an exeption and redirects to 404 page

**Comment by ghost** [comment]
Hi @lyusya-nnn the fix for this issue has already available on 2.3-develop branch, and will be avaible on 2.3.1 release.

**Comment by lyusya-nnn** [comment]
thanks!

**Comment by manohar-prabhu** [comment]
I have resolved this by doing some modification in the code.

override vendor/magento/module-customer/Controller/Address/Delete.php
and replace `use Magento\Framework\App\Action\HttpPostActionInterface` with `use Magento\Framework\App\Action\HttpGetActionInterface;` 

![image](https://user-images.githubusercontent.com/35934158/50823496-23cafa00-135a-11e9-81fe-56b481733ccb.png)

**Comment by arvindsharma4** [comment]
Yes, Thanks @mrprabhu 
This resolved my issues

**Comment by herman-aka-wouter** [comment]
> I have resolved this by doing some modification in the code.
> 
> override vendor/magento/module-customer/Controller/Address/Delete.php
> and replace `use Magento\Framework\App\Action\HttpPostActionInterface` with `use Magento\Framework\App\Action\HttpGetActionInterface;`
> 
> ![image](https://user-images.githubusercontent.com/35934158/50823496-23cafa00-135a-11e9-81fe-56b481733ccb.png)

there is an diff patch for 
https://github.com/magento/magento2/commit/312cd809b49b569ad0b5900504c4dec76c573cbd.diff

**Comment by LTroya** [comment]
@mrprabhu how do you replace the core magento class to change the implementation?
