### ISSUE TITLE
telefonnumber is a required filed in admin backend when it is set to optional in customer configuration

### ISSUE THREAD

**Issue by frostblogNet** [magento/magento2#19755]
### Summary (*)

If the telefonnumber is set to optional (store -> configuration -> customer -> customer configuration -> Name and Address Options -> Show Telephone) and you go to the admin section customer. If you try to change the address of an existing user the telefonnumber is marked as required.

### Preconditions (*)
. 

    Magento Enterprise Edition v2.2.7
    Magento Community Edition v2.2.6

### Steps to reproduce (*)

1. In admin area go to store -> configuration -> customer -> customer configuration -> Name and Address Options -> Show Telephone
2. set "Show Telephone" to optional
3. clear cache
4. do to the customer section in the admin backend.
5. click on the edit button of any existing user
6. click on address menue in the sidebar
7. if you scroll down to  "Phone Number", you will see that this field is still marked as required and you can not save with an empty value. 

### Expected result (*)

1. As you can see in the frontend checkout this field is not required there and it can be saved with an empty value. 
2. This should also be the case it the admin area.

### Actual result (*)

![grafik](https://user-images.githubusercontent.com/19548641/49945783-e788b300-feed-11e8-8d73-d56b799ba1a2.png)

1. The field is marked as required and can not be saved with an empty value

**Comment by magento-engcom-team** [comment]
Hi @frostblogNet. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@frostblogNet do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by frostblogNet** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97138` were created

**Comment by ghost** [comment]
Hi @frostblogNet, thank for you report the fix for this issue has already avaible on 2.3-develop branch, and will be avaible on next 2.3.1 release
