### ISSUE TITLE
Admin Sales Order Create Fails with PayflowPro

### ISSUE THREAD

**Issue by pmclain** [magento/magento2#19763]
### Preconditions (*)
1. Magento 2.3.0
2. Configure Paypal PayFlow Pro for credit card payment method

### Steps to reproduce (*)
1. Create new order in admin panel
2. Select credit card payment method for PayFlow Pro

### Expected result (*)
1. Order placement succeeds

### Actual result (*)
1. Order creation fails with error `Invalid account number`

The order creation fails because `Magento_Payment/js/transparent` fails to load. This file was moved in 2.2, https://github.com/magento/magento2/commit/0ce439b1ecc2906dd840f37989c7c8ccf84dc6bf#diff-b0845d35ccdd892fe5e1a93a9b714b66 and updated in `requirejs-config` https://github.com/magento/magento2/commit/0ce439b1ecc2906dd840f37989c7c8ccf84dc6bf#diff-7fec090bf536a50e1bdfa20e039e27edR9 https://github.com/magento/magento2/commit/0ce439b1ecc2906dd840f37989c7c8ccf84dc6bf#diff-6de82c32cd46b3be45d4d65e403f4136R9

It looks like the file relocation was not ported to 2.3.0, but the `requirejs-config` was, causing the 404 error and order creation failure.

**Comment by magento-engcom-team** [comment]
Hi @pmclain. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pmclain do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by pmclain** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pmclain. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pmclain, here is your [Magento instance](https://i-19763-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19763-2-3-develop.instances.magento-community.engineering/admin](https://i-19763-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pmclain** [comment]
<img width="1678" alt="screenshot 2018-12-14 at 00 24 47" src="https://user-images.githubusercontent.com/12674247/49984701-28f18080-ff37-11e8-96b2-87ca1ce45682.png">

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97154` were created

**Comment by magento-engcom-team** [comment]
Hi @pmclain. Thank you for your report. 
The issue has been fixed in magento/magento2#19764 by @pmclain in 2.3-develop branch
Related commit(s):
 - [8e5c631f2b0360117e29f0b8c720589ea37a2714](https://github.com/magento/magento2/commit/8e5c631f2b0360117e29f0b8c720589ea37a2714)
 - [fd2200a45bf6970fd053c7d70ca346bd372d980d](https://github.com/magento/magento2/commit/fd2200a45bf6970fd053c7d70ca346bd372d980d)

The fix will be available with the upcoming 2.3.1 release.
