### ISSUE TITLE
Bag inventory after place order bellow 0

### ISSUE THREAD

**Issue by Vladwww2015** [magento/magento2#19771]
### Preconditions (*)

1. 2.1.x
2. 2.2.x
3. 2.3

### Steps to reproduce (*)

1. We set the quantity of product 4 (in stock)
2. Two browser tabs (incognito and simple)
3. In different tabs add 3 products to the cart
4. Go to checkout and fill in all fields
5. We try to place orders as quickly as possible and at the same time.
6. Orders are made and the quantity decreases less than 0
see screencast https://www.youtube.com/watch?v=Tckg4dcwLZ8&feature=youtu.be

### Expected result (*)

1. Both orders are processed

### Actual result (*)

1.one of the orders is not issued, because the quantity of products is not enough

**Comment by magento-engcom-team** [comment]
Hi @Vladwww2015. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Vladwww2015 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @Vladwww2015 how you can reproduce this, because i try several times but no have actual result.
![invertory](https://user-images.githubusercontent.com/40756439/49994471-4273e600-ff92-11e8-864b-43b8f44b40a5.gif)

**Comment by ghost** [comment]
@Vladwww2015  Seems like this fixed on 2.3-dev branch.
