### ISSUE TITLE
Can only export default store view items when upgrade to 2.3.0

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#19786]
Component: ImportExport
### Preconditions (*)

1.Nginx 1.14.0  + PHP 7.1.24 + MySQL5.7.19 
2.Clean install Magento 2.2.6 and upgrade to 2.3.0 by command.
3.
### Steps to reproduce (*)

1.Clean install Magento 2.2.6 without any unnecessary module. 
2.Creat a new Website with a new store and a new store view "storeview2".
3.Upload a item with different price in different store view. Now the product export file is correct with 2 rows.
4.Upgrade to 2.3.0, now the exported file have only 1  row  and do not have the price information of "storeview2"

### Expected result (*)

1. Exported file should have 2 rows , row 1 should be the information of All store view, row 2 should be the price of "storeview2"

### Actual result (*)

1. The file have only 1 row with All store view information. and lost the price information of "storeview2"

**Comment by magento-engcom-team** [comment]
Hi @Yuwei9291. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Yuwei9291 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @developerarun. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97206` were created

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Yuwei9291** [comment]
can anyone solve this issue ? many thanks !

**Comment by allozaur** [comment]
@magento-engcom-team this issue is relevant for many Magento store owners/developers - me included

Even if i upload CSV file, having each of the positions having row for each store view (default (`pln`), `eur`, `usd` and `gbp` in my case), then after clicking _System > Data Transfer > Export > Products_ then i get just the CSV with my products for the default store view, loosing all the rows for other store views

## Attached Screenshots

### This is a screenshot of a part of CSV that was **imported** to Magento

![zrzut ekranu 2019-01-20 o 00 17 50](https://user-images.githubusercontent.com/37627284/51433358-e9f6cf00-1c48-11e9-8267-49901cfae0df.jpg)

### On this screenshot there are *the same products as below* but from the **exported** CSV from the same Magento instance just moment after importing the data from previous screenshot

![zrzut ekranu 2019-01-20 o 00 21 11](https://user-images.githubusercontent.com/37627284/51433384-51148380-1c49-11e9-92bd-683a343dc585.jpg)

**Comment by Nazar65** [comment]
Hi @Yuwei9291 @allozaur I'm working on this

**Comment by allozaur** [comment]
@Nazar65 great to hear that! Do you have any time estimate for this issue to be closed?

**Comment by Nazar65** [comment]
@allozaur yes , i will provide a PR soon

**Comment by Nazar65** [comment]
@allozaur I'm finally found the problem, this is very simple fix :)

**Comment by allozaur** [comment]
@Nazar65 oh, i see - it looks really simple :)

**Comment by Nazar65** [comment]
@allozaur on file -> app/code/Magento/CatalogImportExport/Model/Export/Product.php move  LINE  952 
`$collection->clear();` to LINE  951 

So after each iteration we have new collection. this was casued by https://github.com/magento-engcom/magento2ce/commit/461009ef7492cae1ca17183fac5b26d142b6e01f

https://github.com/magento/magento2/blob/5e48ff735453be3d18ef6070adfa71f5c492ee75/app/code/Magento/CatalogImportExport/Model/Export/Product.php#L951

**Comment by allozaur** [comment]
@Nazar65 it seems not to fix our problem, any other ideas?

**Comment by Nazar65** [comment]
@allozaur hmm... strange, can you please provide screenshot of sample export csv ? you can deploy test instance on the my PR and recheck ? 
`@magento-engcom-team give me test instance`

![selection_294](https://user-images.githubusercontent.com/2481206/51822300-7c037500-22e4-11e9-9854-764f569da320.png)

**Comment by Nazar65** [comment]
@allozaur did you set Catalog Price Scope -> website ?

**Comment by swnsma** [comment]
The fix #19395.

**Comment by allozaur** [comment]
@Nazar65 yes, of course

![zrzut ekranu 2019-01-31 o 03 19 49](https://user-images.githubusercontent.com/37627284/52026151-1a6f2080-2507-11e9-9cf1-748b6c55931e.jpg)

**Comment by allozaur** [comment]
@Nazar65 Ok issue is solved for us!! We had some complications with the deploy process and the modified files weren't being recognized properly. Thanks a lot for your help!

**Comment by magento-engcom-team** [comment]
Hi @Yuwei9291. Thank you for your report. 
The issue has been fixed in magento/magento2#19395 by @Valant13 in 2.3-develop branch
Related commit(s):
 - [ea9f3598a400878d8e1daeb7ef5a07410ebd242a](https://github.com/magento/magento2/commit/ea9f3598a400878d8e1daeb7ef5a07410ebd242a)

The fix will be available with the upcoming 2.3.2 release.

**Comment by janmyszkier** [comment]
this should be reopened, the problem is there again on 2.3.3
