### ISSUE TITLE
Logo vertical misalignment.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19791]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Login into admin panel > Look at left top corner logo alignment vertical align not centerd.

### Expected result (*)

1. ![expected-result](https://user-images.githubusercontent.com/43638601/50039886-fd1dea00-005f-11e9-9065-d670f7808901.png)

### Actual result (*)

1. ![actual-result](https://user-images.githubusercontent.com/43638601/50039887-01e29e00-0060-11e9-8333-9217c646fc1a.png)

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-19791-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19791-2-2-develop.instances.magento-community.engineering/admin](https://i-19791-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97220` were created

**Comment by sidolov** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19792 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [485b89fba36dfb52156e7de6a4bf4c7688d9ff67](https://github.com/magento/magento2/commit/485b89fba36dfb52156e7de6a4bf4c7688d9ff67)
 - [3a56397a2dd137378fe6cbd3095e6771d8cd8e26](https://github.com/magento/magento2/commit/3a56397a2dd137378fe6cbd3095e6771d8cd8e26)
 - [8e59e4bf4c679cb981f89b7384d00935748ff5bf](https://github.com/magento/magento2/commit/8e59e4bf4c679cb981f89b7384d00935748ff5bf)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#20456 by @suryakant-krish in 2.2-develop branch
Related commit(s):
 - [7b235def709ae6de06a3bf5a4d683cf1bc9ad234](https://github.com/magento/magento2/commit/7b235def709ae6de06a3bf5a4d683cf1bc9ad234)

The fix will be available with the upcoming 2.2.8 release.
