### ISSUE TITLE
File upload Field alignment issue.

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19808]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Login into admin panel > Catalog > Products > choose any product > Images And Videos  > Click on "Add video" Button.

### Expected result (*)

 ![expected-result](https://user-images.githubusercontent.com/43638601/50041962-f6549e80-0082-11e9-8fb0-2a940739d499.png)

### Actual result (*)

 ![actual-result-1](https://user-images.githubusercontent.com/43638601/50041965-feacd980-0082-11e9-8f2f-20083f920399.png)

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97184`, `MAGETWO-97185` were created

**Comment by ghost** [comment]
HI @suryakant-krish, thank you for you report, for simple code changes, like this one, please propose a PR directly. Thanks for collaboration!
