### ISSUE TITLE
Contact us : design improvement

### ISSUE THREAD

**Issue by suryakant-krish** [magento/magento2#19800]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Go to frontend > choose to contact us link from footer link.

### Expected result (*)

![expected-result](https://user-images.githubusercontent.com/43638601/50041370-d40a5300-0079-11e9-91be-09f22ec89db5.png)

### Actual result (*)

![actual-result-1](https://user-images.githubusercontent.com/43638601/50041373-da003400-0079-11e9-8f5e-7b999b2995d8.png)

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@suryakant-krish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-19800-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19800-2-2-6.instances.magento-community.engineering/admin](https://i-19800-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-19800-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19800-2-3-develop.instances.magento-community.engineering/admin](https://i-19800-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97182`, `MAGETWO-97183` were created

**Comment by dmytro-ch** [comment]
Please note, the issue can be reproduced on the vanilla Magento instance with **sample data** only.

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#19803 by @suryakant-krish in 2.3-develop branch
Related commit(s):
 - [10e7927dbe7e3bc26618fb24706ed857a9371bd9](https://github.com/magento/magento2/commit/10e7927dbe7e3bc26618fb24706ed857a9371bd9)
 - [b618757229157d977e0acf584ea036040ba5e225](https://github.com/magento/magento2/commit/b618757229157d977e0acf584ea036040ba5e225)
 - [c8fa36fec9f4a5af14117f3f6ce5df3382d394f6](https://github.com/magento/magento2/commit/c8fa36fec9f4a5af14117f3f6ce5df3382d394f6)
 - [abfa040f4255dd91b7c01f4b9f07b8bedde6417c](https://github.com/magento/magento2/commit/abfa040f4255dd91b7c01f4b9f07b8bedde6417c)
 - [2e08f60e1bd43ccf45a89364e76092cbc6d6da4e](https://github.com/magento/magento2/commit/2e08f60e1bd43ccf45a89364e76092cbc6d6da4e)
 - [6e47e583e2e46daaca7b1210648da36a6c1d2270](https://github.com/magento/magento2/commit/6e47e583e2e46daaca7b1210648da36a6c1d2270)
 - [9bf7ab7da8fab2031068f9c74bec02f5d74a5915](https://github.com/magento/magento2/commit/9bf7ab7da8fab2031068f9c74bec02f5d74a5915)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your report. 
The issue has been fixed in magento/magento2#20455 by @suryakant-krish in 2.2-develop branch
Related commit(s):
 - [e8dc4614d733bc4915aca63fbc5c9a3dcc2c4cf0](https://github.com/magento/magento2/commit/e8dc4614d733bc4915aca63fbc5c9a3dcc2c4cf0)
 - [3fcc2eb7f7e24c6c914f7db30de6aacdc5cbe632](https://github.com/magento/magento2/commit/3fcc2eb7f7e24c6c914f7db30de6aacdc5cbe632)
 - [c1432e67b89db5c562387e558bae2405fef6f931](https://github.com/magento/magento2/commit/c1432e67b89db5c562387e558bae2405fef6f931)
 - [c57fb365eecb98c78acb35d86893e6eb31717c11](https://github.com/magento/magento2/commit/c57fb365eecb98c78acb35d86893e6eb31717c11)
 - [6f3207f5a9b8247a98628e3ae122152c4d632ebd](https://github.com/magento/magento2/commit/6f3207f5a9b8247a98628e3ae122152c4d632ebd)
 - [ab99ef71c8bc2931fb2685c7e89135b5f58f970e](https://github.com/magento/magento2/commit/ab99ef71c8bc2931fb2685c7e89135b5f58f970e)
 - [0641711a740193a73a1fb9e33fb5cf3ceefb068f](https://github.com/magento/magento2/commit/0641711a740193a73a1fb9e33fb5cf3ceefb068f)

The fix will be available with the upcoming 2.2.8 release.
