### ISSUE TITLE
Better grunt workflow / local theme.js

### ISSUE THREAD

**Issue by amenk** [magento/magento2#1981]
When installing a new theme, I would add it to

`dev/tools/grunt/configs/themes.js`

(according to http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html#grunt_prereq)

But this file is in the standard git ignore and would be overwritten when doing a composer update (if Magento is installed via composer)

How can we fix this?

Maybe an additional file custom_themes.js which is included if it exists?

**Comment by amenk** [comment]
see PR https://github.com/magento/magento2/issues/1982

**Comment by amenk** [comment]
I am not so happy with my pull request. I was thinking about auto-detecting the installed themes for grunt. 
But I am not sure if we also can auto detect the locale which is needed for less generation.
What do you think?

**Comment by amenk** [comment]
I updated my PR #1982 and I am more happy with it now :) - please have a look

**Comment by anton-huz** [comment]
Just a notice: internal ticket MAGETWO-55345 has been created.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Better-grunt-workflow-local-theme-js/idi-p/46911).

**Comment by anton-huz** [comment]
Hi @amenk ,
We did not forget about the issue. Recently we introduced small improvement in current develop branch (it should be available in 2.2).

From now you have ability to place local
`dev/tools/grunt/configs/themes.loc.js` config file.

I hope it solves your task.

**Comment by hostep** [comment]
@guz-anton: @amenk is really correct in [his comment](https://github.com/magento/magento2/commit/494cdbc46de764520cf15f7f1e9a2b0bcb71f5c9#commitcomment-18973835) on this change. Using `.loc` instead of `.local` is just stupid and potentially very confusing.

So if you could please get the developers to change this before this is shipped in a new release, that would be great. Otherwise if you only change it after it was shipped in a new release, it would mean that we (yet again) have to change our workflows.

Thanks!

Completely offtopic, but it made me think of this:

> There are only two hard things in Computer Science: cache invalidation and naming things.
> 
> -- Phil Karlton
