### ISSUE TITLE
Put product in cart to get odd invoice amount and log in - subtotal goes to zero and payment methods disappear 

### ISSUE THREAD

**Issue by Jilco** [magento/magento2#19828]
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Put product in Cart to get an odd invoice amount, eg 1,7 x 16,95 (product price per meter)
2. Total price is now 28.815 (te last digit is the problem i think)
3. Login
4. Cart subtotal (in minicart) goed to zero (also strange)
5. Go to next step (payment)
6. Payment methods disappear in step 2 (so order can't be finished)

### Expected result (*)

1. When logging in the cart subtotal is the same when not logged in (28,82)
2. Payment methods are stil there is step 2 so user can finish order (and pay!)

### Actual result (*)

1. Minicart subtotal goed to zero
2. Payment methods dissappear
![naamloos](https://user-images.githubusercontent.com/23727130/50051795-f4d5b580-0118-11e9-9f6e-c75a9a45f282.png)
![naamloos2](https://user-images.githubusercontent.com/23727130/50051796-facb9680-0118-11e9-89f4-01224b2ac6c6.jpg)

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Jilco do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Jilco** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @Jilco. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jilco, here is your [Magento instance](https://i-19828-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19828-2-2-6.instances.magento-community.engineering/admin](https://i-19828-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Jilco** [comment]
Able to reproduce on vanilla Magento instance

![naamloos23](https://user-images.githubusercontent.com/23727130/50051955-3f0c6600-011c-11e9-8046-dd5b86943f2d.jpg)

**Comment by Jilco** [comment]
I'm not sure if it's related, but it looks a lot like it is. Sometimes this error in exeptions.log

[2018-12-15 23:46:40] main.CRITICAL: Report ID: webapi-5c159260f1b14; Message: Warning: Division by zero in vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 41 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5c159260f1b14; Message: Warning: Division by zero in /vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 41 at vendor/magento/framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Warning: Division by zero in vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php on line 41 at vendor/magento/framework/App/ErrorHandler.php:61)"} []

**Comment by Jilco** [comment]
Some extra testing and the problem gets bigger, it is not only with 3 digit prices but also with normal prices. Add product to cart, login in cart screen, prices go to zero.

![naamloo222s](https://user-images.githubusercontent.com/23727130/50052910-4cc9e780-012c-11e9-840d-f04c97f997ac.png)

**Comment by Jilco** [comment]
Payment methods drop away because they get a zero amount (and they don't like that and i also dont :-))

[2018-12-16 11:02:21] Mollie.ERROR: error: Function: getActiveMethods: Error executing API call (400: Bad Request): The amount is lower than the minimum. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors [] []

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-19828-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-19828-2-2-develop.instances.magento-community.engineering/admin](https://i-19828-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-19828-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-19828-2-2-6.instances.magento-community.engineering/admin](https://i-19828-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
Hi @Jilco , i am not able to reproduce with steps you provided. check the below screenshots.

![screenshot1](https://user-images.githubusercontent.com/32479280/50103700-416edd00-024e-11e9-85c3-d648afae44b3.png)

Payment Page:

![screenshot2](https://user-images.githubusercontent.com/32479280/50103770-682d1380-024e-11e9-988a-5242d71ce276.png)

**Comment by Jilco** [comment]
Have jou logged in after adding product?



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Mahesh Singh <notifications@github.com>
Datum: 17-12-18 18:23 (GMT+01:00)
Aan: magento/magento2 <magento2@noreply.github.com>
Cc: Jilco <jilcotigchelaar@hotmail.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [magento/magento2] Put product in cart to get odd invoice amount and log in - subtotal goes to zero and payment methods disappear  (#19828)


Hi @Jilco<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJilco&data=02%7C01%7C%7C99e8fd6db1b6474b1d0908d664446b17%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806642341792850&sdata=6Euthwj5Uy1fkJbEMuYpdPingufXjmjs2VEYd0zarHk%3D&reserved=0> , i am not able to reproduce with steps you provided. check the below screenshots.

[screenshot1]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32479280%2F50103700-416edd00-024e-11e9-85c3-d648afae44b3.png&data=02%7C01%7C%7C99e8fd6db1b6474b1d0908d664446b17%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806642341949097&sdata=jDhngLxIiu%2FccciXiVPLg7q6BoFiiq9kccoPjPM%2BTF8%3D&reserved=0>

Payment Page:

[screenshot2]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32479280%2F50103770-682d1380-024e-11e9-988a-5242d71ce276.png&data=02%7C01%7C%7C99e8fd6db1b6474b1d0908d664446b17%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806642341949097&sdata=VZEo4T4llS5j1TwPazaK0cgoWy0EcZfiAZ%2Fu6GHJr6s%3D&reserved=0>

**Comment by Jilco** [comment]
Also add a tax class to the product



Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Mahesh Singh <notifications@github.com>
Datum: 17-12-18 18:23 (GMT+01:00)
Aan: magento/magento2 <magento2@noreply.github.com>
Cc: Jilco <jilcotigchelaar@hotmail.com>, Mention <mention@noreply.github.com>
Onderwerp: Re: [magento/magento2] Put product in cart to get odd invoice amount and log in - subtotal goes to zero and payment methods disappear  (#19828)


Hi @Jilco<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJilco&data=02%7C01%7C%7C99e8fd6db1b6474b1d0908d664446b17%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806642341792850&sdata=6Euthwj5Uy1fkJbEMuYpdPingufXjmjs2VEYd0zarHk%3D&reserved=0> , i am not able to reproduce with steps you provided. check the below screenshots.

[screenshot1]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32479280%2F50103700-416edd00-024e-11e9-85c3-d648afae44b3.png&data=02%7C01%7C%7C99e8fd6db1b6474b1d0908d664446b17%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806642341949097&sdata=jDhngLxIiu%2FccciXiVPLg7q6BoFiiq9kccoPjPM%2BTF8%3D&reserved=0>

Payment Page:

[screenshot2]<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F32479280%2F50103770-682d1380-024e-11e9-988a-5242d71ce276.png&data=02%7C01%7C%7C99e8fd6db1b6474b1d0908d664446b17%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636806642341949097&sdata=VZEo4T4llS5j1TwPazaK0cgoWy0EcZfiAZ%2Fu6GHJr6s%3D&reserved=0>

**Comment by Jilco** [comment]
@maheshWebkul721 mahes are you able to reproduce with a tax class added?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @Jilco thank you for you report, this issue has already fixed on 2.3-develop branch and will be available on 2.3.1 release.

**Comment by Jilco** [comment]
@engcom-backlog-nazar so i have to upgrade to get rid of this problem? Than some of my modules will go into stress i think :-)

**Comment by Jilco** [comment]
@magento-engcom-team is this only solved in 2.3 and not in 2.2.8? Because i see the problem pretty often in my logs....
