### ISSUE TITLE
Can't create admin user Magento 2.3

### ISSUE THREAD

**Issue by pklingenberg** [magento/magento2#19832]
### Steps to reproduce (*)
1. Login to backend and create a new admin user.
2. the password for the user contains an exclamation point "!"

### Expected result (*)
Admin user is created

### Actual result (*)
It acts like a user is created and then nothing happens.

SOLUTION:
Avoid using an exclamation within the password and the user is created perfectly.

**Comment by magento-engcom-team** [comment]
Hi @pklingenberg. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pklingenberg do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pklingenberg** [comment]
This was a vanilla install, no additional settings, and the theme Ultimo installed with no additional settings changed.

**Comment by LuciferStrome** [comment]
Can not reproduce this issue in 2.3

**Comment by milindsingh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @milindsingh, here is your [Magento instance](https://i-19832-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19832-2-3-develop.instances.magento-community.engineering/admin](https://i-19832-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by milindsingh** [comment]
Not able to reproduce in  2.3-develop
