### ISSUE TITLE
Category Swatches Product Image Fallback Issue on M 2.3

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#19830]
### Preconditions (*)

1. Magento 2.3
2. 3rd Party Themes & Modules disabled
3. Running in developer mode.

### Steps to reproduce (*)

1. **Make setting to show product image as swatch if possible** http://nimb.ws/hfcAso
2. Visit a category page where swatches would properly show on magento 2.2.5 (upgraded directly from this) and ran recreate catalog images requirement that were listed in 2.2.6 release notes

### Expected result (*)

1. Expecting swatches to show properly on catalog pages.

### Actual result (*)

1. Swatches missing on category pages http://nimb.ws/OpLlN1 and have removed pub/static/frontend and flushed caches several times.
2. Mirasvit confirmed as well that this is a core bug with the following info/fix:

"Locally we have switched the attribute option "Use Product Image for Swatch if Possible" to "Yes" and we get the same error in the browser console, saying "Uncaught TypeError: Cannot read property 'swatchImage' of undefined". This error happens only on category pages because Magento initializes the swatches without required option "jsonSwatchImageSizeConfig".

To fix it you need to add the string ""jsonSwatchImageSizeConfig": <?php /* @noEscape */ echo $block->getJsonSwatchSizeConfig() ?>" to the file "vendor/magento/module-swatches/view/frontend/templates/product/view/renderer.phtml""

3. Error in chrome console:

swatch-renderer.js:555 Uncaught TypeError: Cannot read property 'swatchImage' of undefined
    at Object.<anonymous> (swatch-renderer.js:555)
    at Function.each (jquery.js:370)
    at $.(/shop/anonymous function).(anonymous function)._RenderSwatchOptions (https://devtgn.com/pub/static/version1544449453/frontend/Magento/luma/en_US/Magento_Swatches/js/swatch-renderer.js:496:15)
    at $.(/shop/anonymous function).(anonymous function)._RenderSwatchOptions (https://devtgn.com/pub/static/version1544449453/frontend/Magento/luma/en_US/jquery/jquery-ui.js:402:25)
    at Object.<anonymous> (swatch-renderer.js:395)
    at Function.each (jquery.js:370)
    at $.(/shop/anonymous function).(anonymous function)._RenderControls (https://devtgn.com/pub/static/version1544449453/frontend/Magento/luma/en_US/Magento_Swatches/js/swatch-renderer.js:392:15)
    at $.(/shop/anonymous function).(anonymous function)._RenderControls (https://devtgn.com/pub/static/version1544449453/frontend/Magento/luma/en_US/jquery/jquery-ui.js:402:25)
    at $.(/shop/anonymous function).(anonymous function)._init (https://devtgn.com/pub/static/version1544449453/frontend/Magento/luma/en_US/Magento_Swatches/js/swatch-renderer.js:310:22)
    at $.(/shop/anonymous function).(anonymous function)._init (https://devtgn.com/pub/static/version1544449453/frontend/Magento/luma/en_US/jquery/jquery-ui.js:402:25)

**Comment by magento-engcom-team** [comment]
Hi @snoroozi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@snoroozi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @milindsingh, here is your [Magento instance](https://i-19830-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19830-2-3-develop.instances.magento-community.engineering/admin](https://i-19830-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @snoroozi thank you for you report, i'm not able to reproduce following steps you described, I try several times but have not this error after upgrading from 2.2.5 to 2.3.0 or 2.2.6 to 2.3.0.
![selection_239](https://user-images.githubusercontent.com/40756439/50143026-2b940300-02b4-11e9-8e08-6dd1c2dbd9de.png)

**Comment by ladle3000** [comment]
@engcom-backlog-nazar are you sure you followed the steps right? Because even @joebordo confirmed on the original report https://github.com/magento/magento2/issues/19688

**Comment by joebordo** [comment]
Why did you close this? I have the same Issue on a fresh 2.3 install. I had to add the line suggested by @snoroozi  to get it to work on just fresh install.

**Comment by ghost** [comment]
HI @snoroozi can yo confirm on vanilla instance ?
