### ISSUE TITLE
Bulk product insert with multiple consumers creates errors

### ISSUE THREAD

**Issue by Khartir** [magento/magento2#19843]
### Preconditions (*)
1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)
1. Have multiple instances of the "async.operations.all" consumer running
2. Send bulk request to create multiple new products

### Expected result (*)
According to https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-mysql.html it should be possible to run multiple instances of a consumer:

> You can also run multiple instances of the magento queue:consumers:start command to process large message queues.

This should therefore create all products that have been queued.

### Actual result (*)
Multiple products could not be created.
![magento-import-fail](https://user-images.githubusercontent.com/5592420/50098916-30f23e80-021d-11e9-92c6-81d85fa569f5.png)

**Comment by magento-engcom-team** [comment]
Hi @Khartir. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Khartir do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Khartir thank you for you report,  I'm not able to reproduce following steps you described,  this may be related to your custom code. 
Error in your screen says that magento unable to save StockItem.
![selection_243](https://user-images.githubusercontent.com/40756439/50220656-9b30ed80-039b-11e9-88c4-73d1665b4486.png)

**Comment by Khartir** [comment]
@engcom-backlog-nazar: I did a couple more checks with a fresh installation of Magento in development mode. This is a runtime error. Reproducing it is not easy and probably depends on the system it is running on.
This is what I found out:
The actual exception is due to a deadlock.
```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT  INTO `cataloginventory_stock_status` (`product_id`,`website_id`,`stock_id`,`qty`,`stock_status`) VALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `qty` = VALUES(`qty`), `stock_status` = VALUES(`stock_status`)
```
The error is more likely to occur, the more instances of the consumer are running. I tested with packages of 100.
With 1 instance there were no errors (as expected)
With 2 instances there were < 1 error  per package. (i.e. mostly no errors, every now and again there was an error)
With 3 instances there were about 5 errors per package.
With 4 instances there were about 15 errors per package.

I assumed this error only occured when creating new products, but it turns out I was wrong.
The errors occur more often, if the products are not created but updated.
With 2 instances there were about 5 errors per package.
With 3 instances there were about 15 errors per package.
With 4 instances there were 25-50 errors per package.

When updating the deadlocks are different:
```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: DELETE FROM `catalog_product_index_website`
```
```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: DELETE FROM `cataloginventory_stock_status` WHERE (product_id in (181))
```

**Comment by ghost** [comment]
@Khartir please look this -> https://github.com/magento/magento2/issues/8933

**Comment by PascalBrouwers** [comment]
They made a workaround for the issue by retrying the queue item that fails, but only when it runs via cron.
This issue still exists if you run consumers via rabbitmq.
