### ISSUE TITLE
Ability to disable or "police" Newsletter signups

### ISSUE THREAD

**Issue by DevEpic** [magento/magento2#19849]
### Description (*)
Make it possible to disable the newsletter functionality entirely via the admin backend for those who do not want/need it and add optional CAPTCHA integration to the signup for those who do but also require some security.

### Expected behavior (*)
An on/off toggle in the Stores/Configuration/Newsletter section of the admin backend would allow site owners to disable or enable newsletter functionality entirely, thus removing it from the frontend.

An additional option to enable CAPTCHA in this section would not go amiss for those who want to retain newsletter capabilities but also require security and surety that the email addresses being used to sign up are indeed legitimate.

### Benefits
Many spam bots use the newsletter signup to spam email addresses, this can mean your server sends out thousands of newsletter subscription emails to people who have no idea my site exists and never signed up for it.

**This unsolicited email behavior is illegal in many countries and in severe cases could lead to legal repercussions!**

These bots can also spam non-existent email addresses forcing bounces negatively affecting your email ranking and server load.

### Additional information
Having to disable this module via CLI is extremely unfriendly especially considering it must be forced in order to avoid superfluous "error" messages, in addition it is not always possible to access a CLI in order to disable a module, this functionality is vital to adequate site deployment.

**Comment by magento-engcom-team** [comment]
Hi @DevEpic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DevEpic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DevEpic** [comment]
Please remove this, submitted in wrong area.

**Comment by orlangur** [comment]
> Having to disable this module via CLI is extremely unfriendly especially considering it must be forced in order to avoid superfluous "error" messages, in addition it is not always possible to access a CLI in order to disable a module, this functionality is vital to adequate site deployment.

If `Magento_Newsletter` module can be disabled, there is nothing to add here, we should not duplicate existing functionality in Admin UI. It sounds exactly like a deprecated feature `Disable Module Output` which led to a lot of bugs when condition like `if (isModuleEnabled('Magento_Review'))` was forgotten.

Captcha addition looks like a reasonable feature request to me.
