### ISSUE TITLE
A catalog price rule doesn't save the discount in sales_order_item

### ISSUE THREAD

**Issue by stephan-cream** [magento/magento2#19858]
### Preconditions (*)
1. Magento 2.3.* and 2.2.*.
2. Catalog price rule which is enabled.
3. A visible and enabled product.

### Steps to reproduce (*)
1. Create a product with the sku 'A'.
2. Create a catalog price rule for the product with the sku 'A' with a percentage discount or a fixed discount.
3. Apply and save the catalog price rule.
4. Run the command `bin/magento index:reindex`.
5. Place the product with the sku 'A' in your cart.
6. Complete the checkout process.

### Expected result (*)
1. Product 'A' is shown with the discounted price on the product detail page and in the checkout [frontend].
2. In the backoffice the discounted amount/percentage is shown in the order per order item [backend].
3. In the table `sales_order_item` the `discount_amount` or `discount_percent` value is saved [database].

### Actual result (*)
1. Product 'A' is shown with the discounted price on the product detail page and in the checkout [frontend].
2. In the backoffice the discounted amount/percentage is **NOT** shown in the order at all [backend].
3. In the table `sales_order_item` the `discount_amount` or `discount_percent` value is **NOT** saved [database].

At the moment there is no proper way to ascertain whether an order item actually has a discount or not.
The `applied_rule_ids` does not necessarily mean it is a discount for the product, it could also be free shipping for example.

**Comment by magento-engcom-team** [comment]
Hi @stephan-cream. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@stephan-cream do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97207`, `MAGETWO-97208` were created

**Comment by sidolov** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by sidolov** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Rus0** [comment]
This behaviour has the result as expected, since the catalog price rule acts like a special price, it does not makes discount in the cart.

**Comment by dverkade** [comment]
I'm reopening this issue, because this issue has not been resolved. The issue has been reproduced and is acknowledged, so this behaviour is not as expected. 

Also, it doesn't matter whether the discount is applied with a catalog price rule or a cart price rule. Both are discounts and you want to register to the total amount of discount given. In the current situation you can't see the original price of the item when a catalog price rule is being used, so that valuable data is being lost. This will also mess up reports in Magento if you want to see how much discount has been given, because it will only calculate discounts from cart price rules. 

Either way, a special price or a price different then the original price is a discounter, and it shouldn't matter where this discount is applied. It could be applied in the catalog or it could be applied in the cart, you're giving a discount on the price of the product. This should be registered as a discount.

**Comment by sdzhepa** [comment]
Hello @stephan-cream and @dverkade 

Thank you for collaboration!

Internal Magento team reviewed and investigated this issue in the scope of [related jira tickets](https://github.com/magento/magento2/issues/19858#issuecomment-448177105) `MAGETWO-97207`, `MAGETWO-97208`

All related tickets were closed with resolution `Not a Bug` and comment/explanation: 

> This is not a bug, since Catalog Price rules are designed in a way to adjust prices of the products, but not order amounts.

**Comment by dverkade** [comment]
Hi @sdzhepa,

I'm reopening this issue for two reasons: 

First this behaviour was working in M1. When a catalog price rule changed the product price in M1 this was reflected in the discount fields of the sales_order_item database table. This way you could always determine if a discount was used when the product was ordered. 

Secondly, either way, a special price or a price different then the original price is a discount, and it shouldn't matter where this discount is applied. It could be applied in the catalog or it could be applied in the cart, you're giving a discount on the price of the product. This should be registered as a discount.

Please reopen the internal tickets within Magento Jira as well.

**Comment by engcom-Charlie** [comment]
Hi @sdzhepa and @dverkade .
This issue is still reproducible on fresh Magento 2.3-develop.

In the backoffice "Discount Amount" value = 0$:
![image](https://user-images.githubusercontent.com/51680850/62194076-c3e18280-b381-11e9-8763-90fed87c53ee.png)

In the table sales_order_item the discount_amount or discount_percent value = 0 too.
![image](https://user-images.githubusercontent.com/51680850/62194177-060ac400-b382-11e9-85e1-6608399db8ff.png)

Will you confirm it?

**Comment by Rus0** [comment]
It is still reproducible, I am working on a solution.

**Comment by engcom-Charlie** [comment]
@Rus0 , okay i confirm it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18787` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @dverkade @Rus0 

Thank you for the feedback and argumentation.
I have updated internal Jira ticket with additional information and argumentations.


to: @engcom-Charlie 
Please, take into account next:
- when you confirm Issue, especially in the case that was reopened, you should **update Issue description with additional information like reasons for reopening** or at least lates affected Magento version.

**Comment by kamilszewczyk** [comment]
I can see this issue being closed as completed in 2020, however I can still replicate the same behaviour in later M2 releases.
Has this been fixed? Which version should have the fix applied, or is it available as a patch somewhere?

**Comment by simonnewnordic** [comment]
Tagging along. Can this be reopened if it hasn't been fixed? It's causing a great deal of confusion.

**Comment by tschallacka** [comment]
It's 2025, and with magento 2.4.5-p10 this issue still persists, causing multiple issues with PSP and invoice generation.

The root cause of the issue is that the data generated by the sales.xml salesrules isn't persisted in the quote.
The quote only contains a total_with_discount but not a total_discount field.
So there is nothing to "transfer" to the order item.

This needs to be set manually the moment the quote is converted into an order using the `sales_model_service_quote_submit_before` event.

```xml
   <event name="sales_model_service_quote_submit_before">
        <observer name="transfer_discount_info" instance="Tschallacka\MixAndMatch\Observers\TransferDiscountInfoObserver" />
    </event>
```

```php
class TransferDiscountInfoObserver implements ObserverInterface
{
    public function __construct(
        protected PersonalPricingHelper $personalPricingHelper,
    ) { }

    public function execute(Observer $observer)
    {
        $quote = $observer->getQuote();
        static $results;
        if (is_null($results)) {
            $results = $this->personalPricingHelper->getPprData();
        }
        if (!$results) {
            return $this;
        }

        $order = $observer->getOrder();

        $order->setDiscountAmount($results[PersonalPricingHelper::TOTAL_DISCOUNT_RAW]);
        $order->setBaseDiscountAmount($results[PersonalPricingHelper::TOTAL_DISCOUNT_RAW]);
        $order->setDiscountDescription(__('Personal Pricing Rules'));

        foreach ($order->getAllItems() as $orderItem) {
            $quoteItem = $quote->getItemById($orderItem->getQuoteItemId());
            if ($quoteItem) {
                $data = $results[PersonalPricingHelper::PPR_ITEM_DATA][$quoteItem->getId()];
                $orderItem->setData('discount_info', $quoteItem->getData('discount_info'));
                $orderItem->setDiscountAmount($data[PersonalPricingHelper::ROW_TOTAL_APPLIED_DISCOUNT_AMOUNT_RAW]);
                $orderItem->setBaseDiscountAmount($data[PersonalPricingHelper::ROW_TOTAL_APPLIED_DISCOUNT_AMOUNT_RAW]);
            }
        }
    }

**Comment by roman204** [comment]
Even on Magento 2.4.7-p4 the issue seems to exist...
