### ISSUE TITLE
How to debug composer conflicting component dependencies

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#19850]
**Description (*)**

Issue i got when install third-party package via composer use wizard ui browser. I got issue but i can't find where to see details of issue (log, reports)

![screenshot from 2018-12-18 11-54-38](https://user-images.githubusercontent.com/1908873/50133231-428b2300-02bd-11e9-9df3-6f41e918478d.png)

Using magento 2.3.0 stable version with composer version 1.8.0

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mrtuvn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by gelanivishal** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by orlangur** [comment]
@mrtuvn GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions.

@gelanivishal how did you plan to reproduce it with lack of information? :)
