### ISSUE TITLE
Argument 1 passed to Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice::getSelectionRequestItems() must implement interface Traversable, array given

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#19862]
### Preconditions (*)
1. Magento 2.3.0 EE
2. PHP 7.2.13
3. MySQL 5.7.24

### Steps to reproduce (*)
1. Add to basket a simple product and a virtual product
2. Proceed to checkout
3. In code, the invoice is captured and saved in my own controller after 3dsecure has completed. This code works perfectly when payment for a simple sku on it's own.

```
 /**
     * @param OrderInterface $order
     */
    private function capture($order) {

        /** @var Invoice $invoice */
        $invoice = null;

        foreach ($order->getInvoiceCollection() as $previousInvoice) {
            $invoice = $previousInvoice;
            $invoice->capture();
        }

        if($invoice && $invoice->getId()) {
            $this->invoiceRepository->save($invoice);
        }
    }
```

After save, VirtualSourceDeductionProcessor is called from here due to event 'sales_order_invoice_save_after' in vendor/magento/module-inventory-shipping/etc/events.xml

An exception is generated below.

### Expected result (*)
1. No crash

### Actual result (*)
1.

Exception thrown:

```
2018/12/18 16:59:26 [error] 18261#18261: *8430 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice::getSelectionRequestItems() must implement interface Traversable, array given, called in /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Model/GetSourceSelectionResultFromInvoice.php on line 96 and defined in /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Model/GetSourceSelectionResultFromInvoice.php:107
Stack trace:
#0 /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Model/GetSourceSelectionResultFromInvoice.php(96): Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice->getSelectionRequestItems(Array)
#1 /home/ccarnell/Sites/xx-uk2/vendor/magento/module-inventory-shipping/Observer/VirtualSourceDeductionProcessor.php(96): Magento\InventoryShipping\Model\GetSourceSelectionResultFromInvoice->execute(Object(Magento\Sales\Model\Order\Invoice))
#2 /home/ccarnell/Sites/xx-uk2/vendor/magento/f" while reading response header from upstream, client: 127.0.0.1, server: www-local2.xx.co.uk, request: "POST /realex/remote/validate3d/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "www-local2.xx.co.uk", referrer: "https://pit.3dsecure.net/VbVTestSuiteService/pit1/acsService/paReq?summary=xx"
````

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @craigcarnell thank you for you report please open your issue here -> https://github.com/magento-engcom/msi

**Comment by cscd98** [comment]
https://github.com/magento-engcom/msi/issues/1952

**Comment by muneshj99** [comment]
> Hi @craigcarnell. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * [ ]  Summary of the issue
> 
>     * [ ]  Information on your environment
> 
>     * [ ]  Steps to reproduce
> 
>     * [ ]  Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [ ]  yes
> 
>     * [ ]  no

fuck
