### ISSUE TITLE
Unable to update images in design configuration form

### ISSUE THREAD

**Issue by faisal2010** [magento/magento2#19869]
### Preconditions
1. Download & install a fresh copy of magento CE 2.3.0 without sample data either through composer or archive package from Magento download page.
2. Did not make any change in database and files.

### Steps to reproduce
1. Login to admin
2. Click on Content form left menu and click Configuration under Design.
3. Click Edit in Action column on any of the three default record from grid.
4. Click on HTML HEAD tab under Other Configuration section.
5. Upload an image to Favicon Icon through upload button.

### Expected result
1. Image should upload instantly through ajax and show a preview
2. 
![image](https://user-images.githubusercontent.com/1714124/50206879-a5002400-038e-11e9-8305-5a28c594f7b7.png)

### Actual result
1. Page just flick sightly and nothing happens.
2. Click on Save and Continue or Save Configuration button. A success message display but image path is not saving in database nor image upload to disk.
3. 
![image](https://user-images.githubusercontent.com/1714124/50206979-f7d9db80-038e-11e9-83c6-eae8965cc731.png)

### Additional information
The image [uploadeConfig](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Theme/view/adminhtml/ui_component/design_config_form.xml#L64-L72) defined in form ui_component is not working correctly. Ajax uploader request url should be `theme/design_config_fileUploader/save` BUT it is going to `theme/design_config/edit` .

**Comment by magento-engcom-team** [comment]
Hi @faisal2010. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@faisal2010 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @faisal2010 thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release

**Comment by ghost** [comment]
@faisal2010 -> https://github.com/magento/magento2/pull/18851
