### ISSUE TITLE
Magento 2.3 category edit page "Select from gallery" button not working.

### ISSUE THREAD

**Issue by aasim110** [magento/magento2#19872]
### Preconditions (*)

1. Magento 2.3
2. PHP 7.1.x

### Steps to reproduce (*)

1.1 Set docroot to **pub**
1. Go to Admin >> Catalog >> Categories >> Select any category
2. Now select any category image using **"Select from gallery"** button
3. Selected image showing on image preview block
4. After save image is not showing on image preview block

### Expected result (*)

1. When we save any category image should show on category edit image preview block. 
2. And image should be save properly with that category.

### Actual result (*)

1. After save image coulden't save properly
2. No image showing on image preview block.

**Comment by magento-engcom-team** [comment]
Hi @aasim110. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@aasim110 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team  give me 2.3-develop instance

**Comment by ghost** [comment]
Hi @aasim110 thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release
![selection_242](https://user-images.githubusercontent.com/40756439/50213681-f9070a80-0386-11e9-8f2f-f360686a9f4d.png)

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-19872-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19872-2-3-develop.instances.magento-community.engineering/admin](https://i-19872-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Bartlomiejsz** [comment]
Reopening due to #21131 - still not fixed on develop (it may work depending of where Magento installation is placed - faced this error when placed in pub directory, not in root).

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@Bartlomiejsz Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Bartlomiejsz
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98877` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
Hi @dmytro-ch why this confirmed ? did you test this ? because on provided steps issue not present .

**Comment by ghost** [comment]
@dmytro-ch ok. i'm just edited the issue. and  add docroot.

**Comment by dmytro-ch** [comment]
Hi @engcom-backlog-nazar, sorry for the misunderstanding.

I was able to reproduce the issue on my local environment.
So I've also updated the preconditions in the issue description.

After switching to PHP 7.2 the issue is not reproducible for me as well.
But still, I'm not sure exactly if it really can be related to the PHP version. Maybe there are some specific environment configurations that require deeper investigation.
However, Magento 2.3 still supports PHP ~7.1.3, so I guess we also need to make sure it's compatible.

Thank you!

**Comment by jasonkcarter** [comment]
Just adding my $0.02.  I can reproduce in PHP 7.2 on my local dev environment.  I also made a quick and dirty "fix" plugin that just adds '/pub' to the beginning of the `$filePath` param of any public methods of app/code/Magento/Model/Category/FileInfo.php if the param starts with '/' and doesn't already start with '/pub/'.  There's probably a better way to do it in the Magento codebase, with full access to the private methods, but this worked for me as a temporary fix.

[Liventus_MageFixes.zip](https://github.com/magento/magento2/files/3034416/Liventus_MageFixes.zip)

**Comment by magento-engcom-team** [comment]
Hi @aasim110. Thank you for your report. 
The issue has been fixed in magento/magento2#21131 by @Bartlomiejsz in 2.3-develop branch
Related commit(s):
 - [ed43407dde622f7b6047b99c65fa5bd71db6d986](https://github.com/magento/magento2/commit/ed43407dde622f7b6047b99c65fa5bd71db6d986)
 - [619475dd35eb101e526ec98c6580ff7cb205a7cb](https://github.com/magento/magento2/commit/619475dd35eb101e526ec98c6580ff7cb205a7cb)
 - [17ed8d47f722dea48ea6ddb80c16a08228205702](https://github.com/magento/magento2/commit/17ed8d47f722dea48ea6ddb80c16a08228205702)
 - [ae61b7093715964364327c4e3e617a10225b5750](https://github.com/magento/magento2/commit/ae61b7093715964364327c4e3e617a10225b5750)
 - [112476a20ce1e2685fc62f315372870cb0da3743](https://github.com/magento/magento2/commit/112476a20ce1e2685fc62f315372870cb0da3743)
 - [8522a14fefe581e64691bdaebf8f6589a927978b](https://github.com/magento/magento2/commit/8522a14fefe581e64691bdaebf8f6589a927978b)
 - [07a296a5abd558f543c6207c5746d03475ed9102](https://github.com/magento/magento2/commit/07a296a5abd558f543c6207c5746d03475ed9102)
 - [a142ef2f71eaa78e18829e9b6990bd523254e158](https://github.com/magento/magento2/commit/a142ef2f71eaa78e18829e9b6990bd523254e158)
 - [de8df60b1d5b38e1b9fa53850076078a4218c320](https://github.com/magento/magento2/commit/de8df60b1d5b38e1b9fa53850076078a4218c320)
 - [d06fb10173f5080090c9983ed6b9f3f106788313](https://github.com/magento/magento2/commit/d06fb10173f5080090c9983ed6b9f3f106788313)

The fix will be available with the upcoming 2.3.3 release.
