### ISSUE TITLE
getRatio fails when passing null values. 

### ISSUE THREAD

**Issue by Sunshine4209** [magento/magento2#19881]
failing to call `getImage` with an image type. 

### Preconditions (*)

1. Magento version 2.3.0 with sample data. 
2. php-nginx set up on mac.

### Steps to reproduce (*)

1. call `getImage` method on `Magento\Catalog\Block\Product\ListProduct`. 
` /** @var ListProduct $imageBlock */
   $imageBlock = $this->blockFactory->createBlock(ListProduct::class);
   $productImage = $imageBlock->getImage($product, $imageType);`
`$product` is the current product registered in the registry and $imageType is `'product_page_image_large'`.
this call fails in Magento\Catalog\Block\Product\ImageFactory method `getRatio` line 92. The width and height for this particular image comes back null but getRatio requires ints. The method gets called from the `create` method line 122. 
`$this->imageParamsBuilder->build($viewImageConfig)` on line 130 allows width and height to be null. 

### Expected result (*)

1. even if the image has no width and height, the product page should load. 

### Actual result (*)

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Catalog\Block\Product\ImageFactory::getRatio() must be of the type integer, null given, called in /Sources/Zonos/magento-2.3.0/vendor/magento/module-catalog/Block/Product/ImageFactory.php on line 155 and defined in /Sources/Zonos/magento-2.3.0/vendor/magento/module-catalog/Block/Product/ImageFactory.php:92

**Comment by magento-engcom-team** [comment]
Hi @Sunshine4209. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Sunshine4209 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Sunshine4209 thank you for you report, i'm not able to reproduce following steps you described please use the code below
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl =  $objectManager->get('Magento\Store\Model\StoreManagerInterface')
             ->getStore()
             ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA); 
$diamondIcon=$product->getResource()->getAttribute('diamond_icon')->getFrontend()->getValue($product);
```

**Comment by Sunshine4209** [comment]
Hello @engcom-backlog-nazar ,
Thanks for responding quickly. I think if you allow width and height to be null then a few lines down call `getRatio` that requires width and height to be ints, this will keep causing issues. Your method signature is `getRatio(int width, int height)` in my opinion it should be `getRatio(?int width, ?int height)` besides, you are still checking if those value are null inside the method.

I also tried the code you suggested and it gave me the following error: 
`Fatal error: Uncaught Error: Call to a member function getFrontend() on boolean in /Sources/Zonos/magento-2.3.0/app/code/Zonos/Hello/Block/ProductConfig.php:105 ` . 
getResource is also deprecated.

**Comment by ghost** [comment]
@Sunshine4209  this one ? -> 
```
$productImageAttr = $product->getCustomAttribute( 'icon_image' );
$productImage = $this->helper('Magento\Catalog\Helper\Image')
->init($product, 'icon_image')
->setImageFile($productImageAttr->getValue());
```

**Comment by Sunshine4209** [comment]
@engcom-backlog-nazar  where is this `$this->helper` come from? my class has no such method nor is `Magento\Framework\View\Element\Template;` which I extend.

**Comment by harrigo** [comment]
@Sunshine4209 Did you find a workaround for this I was using below code:

    $productImageGrid = $this->getImage($selection, 'category_page_grid')->toHtml();

    public function getImage($product, $imageId, $attributes = [])
    {
        return $this->imageBuilder->setProduct($product)
            ->setImageId($imageId)
            ->setAttributes($attributes)
            ->create();
    }

However since updating to 2.3.1 from 2.1.7 I am witnessing the same issue as yourself. The amendment to getRatio fixes however do not want to be modifying the core to get around.

**Comment by kweij** [comment]
This ticket should be reopened, although it is not reproducible on a vanilla Magento instance. Please consider:

In the documentation it's stated that for images (definitions) in `<theme_dir>/etc/view.xml` the `width` and `height` are optional: https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-images.html#view_xml_structure. In a vanilla Magento instance there are no examples it this, but it should be allowed to, for example, only set a `width` for an image (my usecase).

Because of the strict typing of the parameters in `Magento/Catalog/Block/Product/ImageFactory::getRatio()`, null values are not accepted and will throw the aforementioned exception:

```
Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Catalog\Block\Product\ImageFactory::getRatio() must be of the type int, null given
```

https://github.com/magento/magento2/blob/38d712ef2b384b2b905dea7ef35a51bc5717e7cc/app/code/Magento/Catalog/Block/Product/ImageFactory.php#L102

Just as @Sunshine4209 mentioned, the method signature should be changed to `getRatio(?int width, ?int height)` to comply with the documentation and intention of the functionality (the method _does_ check if `width` or `height` is set).
