### ISSUE TITLE
Credit memo for $0 order without refunded shipping produces negative credit memo

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#19899]
### Preconditions

1. Clean 2.3.0
2. No sample data

### Steps to reproduce

1. Create Cart Price Rule with 100% discount, applied to shipping, available for everyone
2. Create simple product with positive stock and price = $100
3. Place order in backend for the created product with qty =1 and flat rate shipping ($5 by default). 
4. Invoice order (but don't create shipment)
5. Navigate to Credit Memo form
6. Change Refund Shipping from 5 to 0
7. Click "Refund Offline"

### Expected result

1. Credit Memo with Total Refunded = 0 is created

### Actual result

1. Credit Memo with Total Refunded = -$5.00 is created (negative value)

In Magento Commerce in the same case credit memo fails completely with "You can't use more store credit than the order amount." error. In Open Source it goes through with mentioned negative amount. As far as I see, in both cases behavior is incorrect.

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@wojtekn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by wojtekn** [comment]
@magento-engcom-team give me 2.3.0+ instance

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your request. I'm working on Magento 2.3.0+ instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97257`, `MAGETWO-97258` were created

**Comment by sidolov** [comment]
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#19900 by @wojtekn in 2.3-develop branch
Related commit(s):
 - [e840e41fb2099aa1aeee6797047392623c159fe9](https://github.com/magento/magento2/commit/e840e41fb2099aa1aeee6797047392623c159fe9)
 - [4a77f295f2ed085db9cff24a6edae44916cae252](https://github.com/magento/magento2/commit/4a77f295f2ed085db9cff24a6edae44916cae252)
 - [5b4fdca34a3668d3fda6890651a0c21ec3b08d9a](https://github.com/magento/magento2/commit/5b4fdca34a3668d3fda6890651a0c21ec3b08d9a)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#20508 by @mageprince in 2.2-develop branch
Related commit(s):
 - [d46a076cd1d8ae2c0dc67f35d6bc6c9458576f3b](https://github.com/magento/magento2/commit/d46a076cd1d8ae2c0dc67f35d6bc6c9458576f3b)
 - [c830d613b1b678e3b0370d61ae7b0978a223e722](https://github.com/magento/magento2/commit/c830d613b1b678e3b0370d61ae7b0978a223e722)

The fix will be available with the upcoming 2.2.8 release.
