### ISSUE TITLE
product_type attribute contains incorrect value in mass import export csv after creating custom type_id attribute. actual type_id value in database gets change with newly created attribute type_id.

### ISSUE THREAD

**Issue by surabhisrivastava09** [magento/magento2#19891]
### Preconditions (*)
1. magento 2.2.4 
2. PHP 7.0.15

### Steps to reproduce (*)
1. Create dropdown type product attribute with attribute code "type_id" and assign the product attribute to attribute set.
2. Create new product using that attribute and save it.
3. Export the product. 
4. Import using the same csv.

### Expected result (*)
1. Magento shouldn't allows to create attribute with attribute code type_id. 
2. product_type column in csv should not contain the custom type_id attribute value.
3. If it is allows to create attribute but it shouldn't allows to create product.

### Actual result (*)
1. Magento allows to create the attribute with attribute code type_id. 
2. product_type column in csv contains the custom type_id attribute value.
3. After creating product using type_id attribute , price & quantity fields value become 0 or null.

http://i.imgur.com/UTDCehu.png
http://i.imgur.com/43j5o1x.png
i.imgur.com/7PGBpXi.png

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Surabhi-Cedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-19891-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19891-2-3-develop.instances.magento-community.engineering/admin](https://i-19891-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97253`, `MAGETWO-97254` were created

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20115 by @GovindaSharma in 2.3-develop branch
Related commit(s):
 - [b9d13e69c4928a0b6d740845bed305a399a42fd5](https://github.com/magento/magento2/commit/b9d13e69c4928a0b6d740845bed305a399a42fd5)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#21208 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [474cc79c77289c596466f8ab95422b94edc61786](https://github.com/magento/magento2/commit/474cc79c77289c596466f8ab95422b94edc61786)

The fix will be available with the upcoming 2.2.9 release.
