### ISSUE TITLE
Magento 2.3 search results relevance with elasticsearch?

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#19896]
### Preconditions (*)

1.Magento 2.3
2.Elasticsearch 5.2

### Steps to reproduce (*)

1.Search for a random keyword with elasticsearch as search engine and also then reconfigure and try the same with mysql.
2.

### Expected result (*)

1. Magento 2.3 integrated with Elasticsearch 5.2 provides search results similar to Mysql search in terms of relevance. For example a keyword Pink, search output is 126 items found both in Mysql and Elasticsearch. Isn't elasticsearch supposed to provide more relevant results? When an extension like Wymoind or Amasty elastic search extension is added, then the results for Pink keyword narrows down and looks more relevant which results in 31 items. Is this how it is supposed to work or am I missing something? I know for sure elasticsearch is working because when turn off the server and do a search, i get node not found exception.

2.

### Actual result (*)

1. Relevant search results
2.

**Comment by magento-engcom-team** [comment]
Hi @ethniccode. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ethniccode do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@ethniccode please provide more details playing with a vanilla Magento instance using sample data.

> For example a keyword Pink, search output is 126 items found both in Mysql and Elasticsearch

Are some of those irrelevant to your query?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by monotheist** [comment]
@orlangur Yes. It is irrelevant. I am not sure how to reproduce this on vanilla instance. I am seeing this on a production store. My skype id is my user id. I can provide the production store URL which now configured to elasticsearch and 100% reproducible.

**Comment by orlangur** [comment]
@ethniccode this is not the way core bugs are supposed to be reproduced.

**Comment by monotheist** [comment]
@orlangur Okay give me 2.3 instance with elasticserver 5.2

**Comment by orlangur** [comment]
@ethniccode I'm not a bot (at least I hope so :)).

Please check https://github.com/magento/magento2/issues/19896#issuecomment-448926351 on deploy command.

**Comment by ghost** [comment]
Hi @ethniccode     thank you for you report,
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
