### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 issue

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#19901]
Table not found issue after updating magento 2.2.7 to 2.3.0. How fix this issue?

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1
3. No sample data

### Steps to reproduce (*)
1. Updated magento 2.2.7 to 2.3.0.
2. Run command bin/magento setup:upgrade
3. It stop before the command operation is completed.

![error_3](https://user-images.githubusercontent.com/26794034/50289232-e1a44c00-0470-11e9-89bd-0e673a3f0246.JPG)

4. Notification: Cannot process definition to array for type enum
5.  var/log/exception.log
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table '*database_name*.magento_bulk' doesn't exist, query was: DELETE FROM `magento_bulk` WHERE (start_time <= '2018-10-21 11:59:16') {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*database_name*.magento_bulk' doesn't exist, query was: DELETE FROM `magento_bulk` WHERE (start_time <= '2018-10-21 11:59:16') at /home/***/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table '*database_name*.magento_bulk' doesn't exist at /home/***/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"}
```

### Expected result (*)

1. It must complete the operation of the command without any error.

### Actual result (*)

1. Table error message

Tested also commands:
php -f bin/magento setup:db-data:upgrade
php -f bin/magento setup:db-schema:upgrade 
php -f bin/magento setup:db:status 

![error_2](https://user-images.githubusercontent.com/26794034/50289242-e963f080-0470-11e9-836e-098b1dfe6bbc.JPG)

**Comment by magento-engcom-team** [comment]
Hi @Userr017. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Userr017 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Userr017 thank you for you report, i'm not able to reproduce following steps you described, this may be related to your custom modules.

**Comment by tuyennn** [comment]
@magento-engcom-team I'm facing this issue while upgrading from 2.1.x to 2.3.4. Probably the **Catalog Flat for Category** is being used
