### ISSUE TITLE
Configurable - created variants missing all info on products grid at admin area

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#19916]
### Preconditions (*)

1. Magento 2.3 CE
2. PHP 7.2

### Steps to reproduce (*)

1. Create Configurable
2. Add Variants with custom created attribute (I added dropdown type with just "dose"
3. Magento will create variants but all of them are missing any info on product's grid - no name, no product type, no custom attribute value
http://prntscr.com/lxpfdb
http://prntscr.com/lxpfi3
4. Checked and when I open variant product page - all attributes are filled and showing correctly,
 but on main product grid this is empty
Screenshot: http://prntscr.com/lxpcr6
5. BTW I added variants and set default options at the last step for variant creation - to not add price, qty etc and add it later http://prntscr.com/lxpfkw

### Expected result (*)

1. Product variants created should have all products info filled on products grid at admin area - because now you dont see anything - and you cannot even know what the products are.

### Actual result (*)

1. Screenshot: http://prntscr.com/lxpcr6
2. Products grid shows simple variants created but without any info - name, attribute used to create, all other data, except qty

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tomekjordan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tomekjordan** [comment]
please close this issue, I need to investigate it more. since there were some other extensions installed
