### ISSUE TITLE
Incorrect index pricing when "Special Price from" is specified, but not "special price"

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#19915]
### Preconditions
1. Magento 2.2.7 (and 2.2.6)
2. A product configured with a "Special Price from" is specified, but not "special price", under advanced pricing
![image](https://user-images.githubusercontent.com/7268384/50317763-4c628100-048b-11e9-9607-3f61c3b70a0a.png)

### Steps to reproduce
1. Navigate in admin html
2. catalog -> Product
3. create a product
4. fill in all required values
5. Click on advanced pricing
6. Put a special price date that is PRIOR to today, but leave Special price blank.
7. (Optional, repeat Steps 1-4, but do not configure any advanced pricing. This way you can compare the index
8. Run all indexers (Product flat especially) - ```bin/magento indexer:reindex```
The issue becomes more apparent if you configure customer groups, and pricing for these groups in BOTH of the products.

### Expected result
1. The Mysql ```catalog_product_index_price``` table for step 7, above should show the final price. ie:
```
select * from catalog_product_index_price WHERE entity_id = 267044;
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
| entity_id | customer_group_id | website_id | tax_class_id | price    | final_price | min_price | max_price | tier_price |
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
|    267044 |                 0 |          1 |            2 | 424.9900 |    424.9900 |  424.9900 |  424.9900 |       NULL |
|    267044 |                 1 |          1 |            2 | 424.9900 |    424.9900 |  424.9900 |  424.9900 |       NULL |
|    267044 |                 2 |          1 |            2 | 424.9900 |    424.9900 |  424.9900 |  424.9900 |       NULL |
|    267044 |                 3 |          1 |            2 | 424.9900 |    424.9900 |  424.9900 |  424.9900 |       NULL |
|    267044 |                 4 |          1 |            2 | 424.9900 |    339.7500 |  339.7500 |  339.7500 |   339.7500 |
|    267044 |                 6 |          1 |            2 | 424.9900 |    407.8600 |  407.8600 |  407.8600 |   407.8600 |
|    267044 |                 7 |          1 |            2 | 424.9900 |    407.8600 |  407.8600 |  407.8600 |   407.8600 |
|    267044 |                 8 |          1 |            2 | 424.9900 |    407.8600 |  407.8600 |  407.8600 |   407.8600 |
|    267044 |                 9 |          1 |            2 | 424.9900 |    407.8600 |  407.8600 |  407.8600 |   407.8600 |
|    267044 |                10 |          1 |            2 | 424.9900 |    407.8600 |  407.8600 |  407.8600 |   407.8600 |
|    267044 |                11 |          1 |            2 | 424.9900 |    407.8600 |  407.8600 |  407.8600 |   407.8600 |
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
11 rows in set (0.000 sec)
```
### Actual result
1. The final price is being filled in with all 0.0000:
```
 select * from catalog_product_index_price WHERE entity_id = 267045;
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
| entity_id | customer_group_id | website_id | tax_class_id | price    | final_price | min_price | max_price | tier_price |
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
|    267045 |                 0 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |       NULL |
|    267045 |                 1 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |       NULL |
|    267045 |                 2 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |       NULL |
|    267045 |                 3 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |       NULL |
|    267045 |                 4 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |   374.0600 |
|    267045 |                 6 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |   449.0500 |
|    267045 |                 7 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |   449.0500 |
|    267045 |                 8 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |   449.0500 |
|    267045 |                 9 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |   449.0500 |
|    267045 |                10 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |   449.0500 |
|    267045 |                11 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |   449.0500 |
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
11 rows in set (0.000 sec)
```

This does not appear to affect anything on the front end, HOWEVER, for anything that relies on this index and its ```final_price```  the incorrect pricing is returned. One such example is the popular and excellent Smile Elasticsuite: [https://github.com/Smile-SA/elasticsuite/blob/a716af57be09dd2e39b8170bd3d3323b87c7c7d7/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/PriceData.php#L41](https://github.com/Smile-SA/elasticsuite/blob/a716af57be09dd2e39b8170bd3d3323b87c7c7d7/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/PriceData.php#L41)

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@justinharris1986 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @justinharris1986 thank you for you report, This is the expected behavior, the final price is not used if it is 0, for this case there is a minimum price and a maximum price.

**Comment by rbayet** [comment]
Hi @engcom-backlog-nazar,

Can you clarifiy your point of view when you say : 
> for this case there is a minimum price and a maximum price

In @justinharris1986 exemple, you can see that minimum and maximum price are also affected and set to 0 in the index table.

**Expected**
```
select * from catalog_product_index_price WHERE entity_id = 267044;
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
| entity_id | customer_group_id | website_id | tax_class_id | price    | final_price | min_price | max_price | tier_price |
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
|    267044 |                 0 |          1 |            2 | 424.9900 |    424.9900 |  424.9900 |  424.9900 |       NULL |
|    267044 |                 1 |          1 |            2 | 424.9900 |    424.9900 |  424.9900 |  424.9900 |       NULL |
|    267044 |                 2 |          1 |            2 | 424.9900 |    424.9900 |  424.9900 |  424.9900 |       NULL |
````

**Actual**

```
 select * from catalog_product_index_price WHERE entity_id = 267045;
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
| entity_id | customer_group_id | website_id | tax_class_id | price    | final_price | min_price | max_price | tier_price |
+-----------+-------------------+------------+--------------+----------+-------------+-----------+-----------+------------+
|    267045 |                 0 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |       NULL |
|    267045 |                 1 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |       NULL |
|    267045 |                 2 |          1 |            2 | 467.9900 |      0.0000 |    0.0000 |    0.0000 |       NULL |
```

Regards,

**Comment by Nazar65** [comment]
Hi @rbayet maybe related : https://github.com/magento/magento2/issues/19877

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @justinharris1986 this is really duplicate to this -> https://github.com/magento/magento2/issues/19877  and they have already made a PR.
