### ISSUE TITLE
Close button overlapping in shipping address label whenever any user adding new shipping address in mobile view in checkout 

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#19925]
Close button overlapping in shipping address label whenever any user adding new shipping address in mobile view in checkout 

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

Steps to reproduce
_**Note : testing should be in tab view or mobile view**_ 
    Step 1: Go to frontend
    Step 2: login as customer 
    Step 3: now add any product to cart and go to checkout 
    Step 4: in shipping address steps, you will see an saved address
    Step 5: now click on add new address button or edit any saved address, then popup will open 
    (Now see actual result screenshot)

### Expected result (*)

![sol](https://user-images.githubusercontent.com/26018716/50340488-25668680-0541-11e9-90f8-0f5e0d686183.png)

### Actual result (*)

![issues](https://user-images.githubusercontent.com/26018716/50340498-357e6600-0541-11e9-9277-49b418d17d7a.png)

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@cedarvinda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-19925-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19925-2-3-develop.instances.magento-community.engineering/admin](https://i-19925-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97283`, `MAGETWO-97284` were created

**Comment by 00F100** [comment]
i work to make this fix

**Comment by 00F100** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @00F100. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @00F100, here is your [Magento instance](https://i-19925-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19925-2-3-develop.instances.magento-community.engineering/admin](https://i-19925-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 00F100** [comment]
I performed the test and did not find this problem

**Comment by thurow** [comment]
Looks like this issue is already fixed. As you can see in the screenshot below, theres not an overlapping anymore.
Firefox:
![Captura de Tela 2019-09-14 às 13 14 41](https://user-images.githubusercontent.com/14911960/64910916-f2c57500-d6f1-11e9-9d64-c2e7e38b0e9b.png)
Chrome:
![Captura de Tela 2019-09-14 às 13 13 02](https://user-images.githubusercontent.com/14911960/64910917-f35e0b80-d6f1-11e9-995e-8ee6632843f7.png)
