### ISSUE TITLE
Success message is not showing when creating invoice & shipment simultaniously 

### ISSUE THREAD

**Issue by surabhisrivastava09** [magento/magento2#19942]
### Preconditions (*)
1. Magento 2.3
2. PHP 7.1.3

### Steps to reproduce (*)
1. Create order from admin panel.
2. View order at admin panel and Click "create invoice".
3. Check the checkbox "create shipment" and "Email copy of invoice" while generating invoice. and click submit invoice button.

### Expected result (*)
1. Success message should show as "You created the invoice and shipment."

### Actual result (*)
1. Invoice has been created but no success message is appearing.

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Surabhi-Cedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-19942-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19942-2-3-develop.instances.magento-community.engineering/admin](https://i-19942-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97300` were created

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by XxXgeoXxX** [comment]
Messages are removed after call method app/code/Magento/Email/Model/Template/Filter.php:blockDirective because all/only shipment email template used construction '{{block}}'. When shipment and invoice created together with send email functionality mesages were added and after that Magento creates block(according templates app/code/Magento/Sales/view/frontend/email/shipment_new.html) by layout functionality(\Magento\Framework\View\LayoutInterface) and it call method initMessages which remove all of them.

This does not happen when we only ship order because method add messages called after send email.

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20142 by @Surabhi-Cedcoss in 2.3-develop branch
Related commit(s):
 - [e6c41bac830e622dc8683fc4b24ee3e46345af4b](https://github.com/magento/magento2/commit/e6c41bac830e622dc8683fc4b24ee3e46345af4b)
 - [0689a17f50c1df4e73ff44f4c871dc7907800094](https://github.com/magento/magento2/commit/0689a17f50c1df4e73ff44f4c871dc7907800094)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20776 by @GovindaSharma in 2.2-develop branch
Related commit(s):
 - [0ec113f8a5d680210ebfa6e84d950e7c5f23c71e](https://github.com/magento/magento2/commit/0ec113f8a5d680210ebfa6e84d950e7c5f23c71e)
 - [a44cb0e9082c73a8512e9f42ab2ef124b1ceb03e](https://github.com/magento/magento2/commit/a44cb0e9082c73a8512e9f42ab2ef124b1ceb03e)

The fix will be available with the upcoming 2.2.9 release.
