### ISSUE TITLE
Out of Stock products does not display on 2.2.3 also

### ISSUE THREAD

**Issue by HEALTHYHOOKAHCA** [magento/magento2#19948]
### Preconditions (*)

1. Magento 2.2.4

### Steps to reproduce (*)

1. Go to Admin side .. from left menu..  Stores >> Configuration >> Catalog >> Inventory
In that, check "Stock Options" tab, in which I've set "Display Out of Stock Products" to "Yes", for all my views, website view, in default settings.
2. on Customer side, I can not see my all the products(Configurable Products). "Out-of-stock" configurable products are still missing.
Like, I've one configurable product(Jam bottle), which has 12 flavors.
Now, some of the flavors are not in stock. So these flavored products are not displaying on customer side.

### Expected result (*)

1.  All the flavors should be there in the dropdown list, see the image.
![image](https://user-images.githubusercontent.com/46086147/50384196-84fe9680-06e7-11e9-9832-b6cdfd698526.png)

I can see only 10 of them right now, there should be 12 flavors in the list.
the flavors not appearing here are having 0 quantities. So they are out of stock proudcts.
Technically they should appear here as on admin side the flag is set to "Yes" for Out of stock products.

### Actual result (*)

1. on Customer side, I can not see my all the products(Configurable Products). "Out-of-stock" configurable products are still missing.
Like, I've one configurable product(Jam bottle), which has 12 flavors.
Now, some of the flavors are not in stock. So these flavored products are not displaying on customer side.

**Comment by magento-engcom-team** [comment]
Hi @HEALTHYHOOKAHCA. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@HEALTHYHOOKAHCA do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @HEALTHYHOOKAHCA thank you for you report, this issue has already fixed on 2.2-develop and 2.3-develop branch and available on 2.2.7 release and 2.3.0 release.

**Comment by HEALTHYHOOKAHCA** [comment]
My magento version is 2.2.4, so u r saying that i will have to upgrade my magento to 2.3.0 to resolve this issue?
