### ISSUE TITLE
Creating creditmemo doesn't fire model_save_commit_after, sales_order_creditmemo_save_commit_after events

### ISSUE THREAD

**Issue by unicoder88** [magento/magento2#19957]
### Preconditions (*)

1. Magento 2.2.6 Community edition.
2. I believe this problem is still relevant in Magento 2.3.0 Community edition since [Magento\Sales\Model\Service\CreditmemoService::refund](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Service/CreditmemoService.php#L145) has not changed.
3. *WORKS IN Commerce Edition* - events are eventually fired in commit callback thanks for Logger that makes one more AbstractDb->save() in `Magento\Logging\Model\Processor::logAction`.

### Steps to reproduce (*)

1. In your module, subscribe to events `model_save_commit_after`, `sales_order_invoice_save_commit_after` and `sales_order_creditmemo_save_commit_after`, set up logging or debug breakpoint.
  https://prnt.sc/lyzbrk
  https://prnt.sc/lyzffj

1. Create an order.
  https://prnt.sc/lyzfmn
  https://prnt.sc/lyx2w6

1. Create an invoice for the order.
  Logger caught invoice events `model_save_commit_after` and `sales_order_invoice_save_commit_after`.
  https://prnt.sc/lyzkgf

1. Create new Credit memo from order (or from Invoice if payment is online).
  https://prnt.sc/lyzl0o

I debugged this and see that service [Magento\Sales\Model\Service\CreditmemoService::refund](https://github.com/magento/magento2/blob/2.2.6/app/code/Magento/Sales/Model/Service/CreditmemoService.php#L156) is to blame. It starts and commits transaction, and when creditmemo model is saved, commit callbacks are not runs because of transaction level (https://github.com/magento/magento2/blob/2.2.6/lib/internal/Magento/Framework/Model/ResourceModel/AbstractResource.php#L94).

### Expected result (*)

1. Events fired for both Invoice and Creditmemo

### Actual result (*)

1. Events only fired for Invoice.

**Comment by magento-engcom-team** [comment]
Hi @unicoder88. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@unicoder88 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @unicoder88 thank you for you report, this events available only on EE version.

**Comment by unicoder88** [comment]
Hi @engcom-backlog-nazar , thanks for your review. Exactly, they are *broken* on CE :) So I would like them fixed, by means of an issue or pull request if we have an idea for proper fix.

Please reopen the issue, we (developers) need this event, we deserved it :)

**Comment by ghost** [comment]
@unicoder88  ok, you can open here -> https://github.com/magento/community-features/issues
