### ISSUE TITLE
 1823 Failed to add the foreign key constraint 'EAV_ATTRIBUTE_OPTION_SWATCH_STORE_ID_STORE_STORE_ID' to system tables,

### ISSUE THREAD

**Issue by gouravsyscraft** [magento/magento2#19953]
******Summary** of the issue:****

Hello Team,

I am trying to update magento from 2.2 to 2.3 but when  i am running below command.
php bin/magento setup:upgrade

then i am getting this error.

SQLSTATE[HY000]: General error: 

1823 Failed to add the foreign key constraint 'devphoto_pmtest/EAV_ATTRIBUTE_OPTION_SWATCH_STORE_ID_STORE_STORE_ID' to system tables, query was: ALTER TABLE `eav_attribute_option_swatch` ADD CONSTRAINT `EAV_ATTRIBUTE_OPTION_SWATCH_STORE_ID_STORE_STORE_ID` FOREIGN KEY (`store_id`) REFERENCES `store` (`store_id`)  ON DELETE CASCADE, ADD CONSTRAINT `EAV_ATTR_OPT_SWATCH_OPT_ID_EAV_ATTR_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option_id`)  ON DELETE CASCADE

Can anybody help me?

**Environment:**

Right now i am using magento 2.2 and trying to update it to 2.3

**Step to reproduce**
1) Use any magento 2.2 setup
2) Then download magento 2.3 setup and over wright this file on magento 2.2 setup
3) Then try to run below command
php bin/magento setup:upgrade

So i am getting below error.
SQLSTATE[HY000]: General error: 

1823 Failed to add the foreign key constraint 'devphoto_pmtest/EAV_ATTRIBUTE_OPTION_SWATCH_STORE_ID_STORE_STORE_ID' to system tables, query was: ALTER TABLE `eav_attribute_option_swatch` ADD CONSTRAINT `EAV_ATTRIBUTE_OPTION_SWATCH_STORE_ID_STORE_STORE_ID` FOREIGN KEY (`store_id`) REFERENCES `store` (`store_id`)  ON DELETE CASCADE, ADD CONSTRAINT `EAV_ATTR_OPT_SWATCH_OPT_ID_EAV_ATTR_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option_id`)  ON DELETE CASCADE

**Expected result**

This should be update properly with data base schema.

Please help me asap.

**Comment by magento-engcom-team** [comment]
Hi @gouravsyscraft. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gouravsyscraft do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gouravsyscraft, thank you for you report,  this problem related to your custom module.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
