### ISSUE TITLE
CLI command is giving fatal error (Out of Memory)

### ISSUE THREAD

**Issue by arshaim39** [magento/magento2#19950]
### Summary (*)
I have some issue in Magento 2 CLI. Whenever I try to run a command in CLI, it generates an error and does not proceed any command.

### Examples (*)
I am running following command to reindex the website.

**ea-php70 magento indexer:reindex**

It generates following error in CLI:

**mmap() failed: [12] Cannot allocate memory

Fatal error: Out of memory (allocated 2097152) (tried to allocate 65536 bytes) in /public_html/vendor/composer/ClassLoader.php on line 444**

### Proposed solution
I have tried to fix it by increasing its memory but nothing is working. You can see its all settings by following url: **https://mushkiya.com/test.php**

I have also tried to increase its memory in .htaccess and .user.ini file but nothing is worked for me.

I have also used following: **ea-php70 -d memory_limit=-1 magento indexer**

But not worked.

Please help.
![cpanel terminal](https://user-images.githubusercontent.com/46088426/50385040-1247e800-06f4-11e9-89c6-da609a988642.png)

**Comment by magento-engcom-team** [comment]
Hi @arshaim39. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@arshaim39 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by arshaim39** [comment]
@magento-engcom-team give me $VERSION instance

**Comment by arshaim39** [comment]
Yes

**Comment by mahesh-rajawat** [comment]
@arshaim39 please use command as `php -d memory_limit=2G bin/magento indexer:reindex`

**Comment by arshaim39** [comment]
Not working. Please see following screenshot.

![cpanel terminal 1](https://user-images.githubusercontent.com/46088426/50385264-d8c5ab80-06f8-11e9-86bd-d0e3b0b9a77c.png)

**Comment by milindsingh** [comment]
@arshaim39 What is your total memory?

**Comment by arshaim39** [comment]
![screenshot_2018-12-24-08-56-24](https://user-images.githubusercontent.com/46088426/50390234-a8165e00-075a-11e9-85bc-c46357fdda39.png)

As I cannot see total memory in my cpanel section but I found this in terminal by 'top' command.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by DanielRuf** [comment]
Well it's already using the swap. Ask your hoster to increase the available memory or stop other processes to free up some memory.

Also there is often a limit by hosters.

The issue tracker is for Magento CE.
For issues with the usage consult https://magento.stackexchange.com
