### ISSUE TITLE
Magento 1 - Patch SUPEE-10415 is not applied

### ISSUE THREAD

**Issue by ratnesh-kadam** [magento/magento2#19952]
I have tried to apply path SUPEE-10415 to magento 1.9.1.0, but its won't succedeed.

Please find the report below. Checking if patch can be applied/reverted successfully.

ERROR: Patch can't be applied/reverted successfully.

checking file app/Mage.php checking file app/code/core/Mage/Adminhtml/Block/Report/Review/Detail.php checking file app/code/core/Mage/Adminhtml/Block/Report/Tag/Product/Detail.php checking file app/code/core/Mage/Adminhtml/Block/Review/Add.php checking file app/code/core/Mage/Adminhtml/Block/Review/Edit/Form.php checking file app/code/core/Mage/Adminhtml/Controller/Action.php Hunk #1 FAILED at 186. 1 out of 1 hunk FAILED checking file app/code/core/Mage/Adminhtml/Model/LayoutUpdate/Validator.php Hunk #1 FAILED at 142. 1 out of 1 hunk FAILED checking file app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Filename.php checking file app/code/core/Mage/Api/Helper/Data.php checking file app/code/core/Mage/Api/Model/Server/Adapter/Soap.php checking file app/code/core/Mage/Api/Model/Wsdl/Config.php checking file app/code/core/Mage/Api/Model/Wsdl/Config/Base.php checking file app/code/core/Mage/Core/Helper/String.php checking file app/code/core/Mage/Core/Model/File/Validator/Image.php Hunk #1 FAILED at 90. 1 out of 1 hunk FAILED checking file app/code/core/Mage/Core/etc/config.xml Hunk #1 FAILED at 456. 1 out of 1 hunk FAILED checking file app/code/core/Mage/Core/etc/system.xml Hunk #1 succeeded at 650 (offset -1 lines). Hunk #2 succeeded at 660 (offset -1 lines). checking file app/code/core/Mage/Customer/Model/Customer.php checking file app/code/core/Mage/Eav/Model/Entity/Attribute/Backend/Serialized.php checking file app/code/core/Mage/Log/Helper/Data.php checking file app/code/core/Mage/Rule/Model/Abstract.php checking file app/code/core/Mage/Sales/Block/Adminhtml/Billing/Agreement/Grid.php checking file app/code/core/Zend/Form/Decorator/Form.php checking file app/design/adminhtml/default/default/template/backup/dialogs.phtml Hunk #1 FAILED at 132. 1 out of 1 hunk FAILED checking file app/design/adminhtml/default/default/template/sales/billing/agreement/view/tab/info.phtml checking file app/design/adminhtml/default/default/template/xmlconnect/edit/tab/content.phtml checking file app/design/adminhtml/default/default/template/xmlconnect/edit/tab/design/image_edit.phtml checking file app/locale/en_US/Mage_Adminhtml.csv checking file app/locale/en_US/Mage_Customer.csv checking file js/mage/adminhtml/backup.js checking file lib/Varien/Filter/FormElementName.php

**Comment by magento-engcom-team** [comment]
Hi @ratnesh-kadam. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ratnesh-kadam do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ratnesh-kadam  i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.
