### ISSUE TITLE
Magento 2 : Remove Specific Product From All Active Carts

### ISSUE THREAD

**Issue by anonspkdk** [magento/magento2#19956]
i am trying to remove specific product from all active carts.

```
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
	$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
	$connection = $resource->getConnection();
	$tableName = $resource->getTableName('quote_item'); //gives table name with prefix
			 
	//Select Data from table
	$sql = "Select * FROM " . $tableName." WHERE product_id=".$product_id;
	$result = $connection->fetchAll($sql); // gives associated array, table fields as key in array.
	foreach ($result as $r) {
	// echo $r['quote_id'];
	$quote = $objectManager->get('\Magento\Quote\Model\Quote')->load($r['quote_id']);

 	if ($r['product_id'] == $product_id ) {
 	$quote_item = $resource->getTableName('quote_item'); //gives table name with prefix
 
	//Delete Data from table
	$sql_del = "Delete FROM " . $tableName." Where product_id = ".$product_id;
	$connection->query($sql_del);
	$quote->collectTotals()->save();
 				}
			}

```
Through this code when i disable any product from admin pannel, it automatically removes that product from all of the active carts 
but i have one problem, it doesn't update minicart. 

https://i.stack.imgur.com/BYzDo.png

As you can see in picture the inner portion of minicart is updating correctly like now i have one product in minicart and its showing 1 Item. but at minicart icon its showing 2 items in minicart. 
i used This code to update minicart :

```
    require([
			           'Magento_Customer/js/customer-data'
			        ], function (customerData) {
			            var sections = ['cart'];
			            customerData.invalidate(sections);
			            customerData.reload(sections, true);
			        });
```

But this code doesn't works on my website.

**Comment by magento-engcom-team** [comment]
Hi @anonspkdk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@anonspkdk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @anonspkdk This is not best practice to delete product from quote. please use repository.
