### ISSUE TITLE
The new custom datetime eav attribute of the product category cannot be saved normally.

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento2#19963]
### Preconditions (*)

1.Magento 2.2.6
2.php7.1.25
3.mariadb 10.1.29
4.apache 2.4.33

### Steps to reproduce (*)

1.Add new custom eav attribute model_year like below:
```php
<?php
//app/code/Test/Category/registration.php
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'Test_Category',
    __DIR__
);
```
```xml
<!--app/code/Test/Category/etc/module.xml-->
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Test_Category" setup_version="0.1.0" />
</config>
```
```xml
<!--app/code/Test/Category/etc/di.xml-->
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Catalog\Model\Category\DataProvider" type="Test\Category\Model\Category\DataProvider"/>
</config>
```
```php
<?php
//app/code/Test/Category/Model/Category/DataProvider.php
namespace Test\Category\Model\Category;


class DataProvider extends \Magento\Catalog\Model\Category\DataProvider
{
    protected function getFieldsMap()
    {
        $fields = parent::getFieldsMap();
        $fields['content'][] = 'model_year'; // custom image field

        return $fields;
    }
}
```
```php
<?php
//app/code/Test/Category/Setup/UpgradeData.php
namespace Test\Category\Setup;
use Magento\Catalog\Setup\CategorySetupFactory;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\UpgradeDataInterface;

class UpgradeData implements UpgradeDataInterface
{
    /**
     * @var CategorySetupFactory
     */
    protected $categorySetupFactory;

    /**
     * UpgradeData constructor.
     * @param CategorySetupFactory $categorySetupFactory
     */
    public function __construct(CategorySetupFactory $categorySetupFactory)
    {
        $this->categorySetupFactory = $categorySetupFactory;
    }

    /**
     * Upgrades data for a module
     *
     * @param ModuleDataSetupInterface $setup
     * @param ModuleContextInterface $context
     * @return void
     */
    public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $setup->startSetup();
        if (version_compare($context->getVersion(), '0.0.2') < 0){
            $categorySetup = $this->categorySetupFactory->create(['setup' => $setup]);
            $categorySetup->addAttribute(
                \Magento\Catalog\Model\Category::ENTITY, 'model_year', [
                    'type' => 'datetime',
                    'label' => 'Model Year',
                    'input' => 'date',
                    'required' => false,
                    'sort_order' => 100,
                    'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_STORE,
                    'group' => 'General Information',
                    'default' => null,
                    'visible' => 1,
                    'user_defined' => 1
                ]
            );
        }
        $setup->endSetup();
    }
}
```
```xml
<!--app/code/Test/Category/view/adminhtml/ui_component/category_form.xml-->
<?xml version="1.0"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="content">
        <field name="model_year" sortOrder="100">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="label" xsi:type="string" translate="true">Model Year</item>
                    <item name="options" xsi:type="array">
                        <item name="showsTime" xsi:type="boolean">true</item>
                    </item>
                </item>
            </argument>
        </field>
    </fieldset>
</form>
```
2.Open catalog categories in backend.
3.Selecting any category, opening content, selecting the current time and then saving, and then viewing the selected time, is incorrect.

### Expected result (*)

1. The time and save time can be selected normally in the classification.

### Actual result (*)

1. Time can be selected normally but cannot be saved correctly.
![20181225103742](https://user-images.githubusercontent.com/4518013/50410004-555ba580-0831-11e9-9758-cccc51a89b48.gif)

**Comment by magento-engcom-team** [comment]
Hi @michaeldyl520. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@michaeldyl520 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by milindsingh** [comment]
`user_defined' => 1` I think these attributes are not saved automatically.
You need to update the save functionality too.

**Comment by michaeldyl520** [comment]
@milindsingh Not for this reason.We can set outputDateTimeToISO to resolve save wrong bug. Like below:
![_ _20181225150441](https://user-images.githubusercontent.com/4518013/50415547-86020600-0856-11e9-8e72-6b7141b536e2.png)
 When we need to add a custom datetime to the category, the current code will filter out hours, minutes and seconds. 
See this link below:
https://github.com/magento/magento2/blob/c4fb1ee447862966afcf4115eb3e65ef8579d04d/app/code/Magento/Catalog/Controller/Adminhtml/Category.php#L174
The backend type is datetime, but the filter uses the date Filter, which is wrong. It should use dateTime Filter. Then everything will be fine. So I think this is a magento bug. Please fix that.

**Comment by milindsingh** [comment]
@michaeldyl520 did you tried setting up a default date format in date field in your ui component?

**Comment by michaeldyl520** [comment]
@milindsingh What should I do, please give me an example. Thanks.

**Comment by milindsingh** [comment]
@michaeldyl520 try this
```
<field name="created_after">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="component" xsi:type="string">Magento_Ui/js/form/element/date</item>
                    <item name="visible" xsi:type="boolean">true</item>
                    <item name="dataType" xsi:type="string">text</item>
                    <item name="formElement" xsi:type="string">input</item>
                    <item name="source" xsi:type="string">amazon_order_import_form_data_source</item>
                    <item name="label" xsi:type="string" translate="true">Created After</item>
                    <item name="tooltip" xsi:type="array">
                        <item name="description" xsi:type="string"><![CDATA[Select the created after date in yyyy-MM-dd format. Example: "2018-03-01", Default 3 months from today.]]></item>
                    </item>
                    <item name="options" xsi:type="array">
                        <item name="dateFormat" xsi:type="string">y-MM-dd</item>
                        <item name="showsTime" xsi:type="boolean">false</item>
                    </item>
                </item>
            </argument>
        </field>
```

**Comment by vishalthakurcg** [comment]
What about this issue ? is it fixed or not ?

**Comment by rudrendrasingh** [comment]
@vishalthakurcg 

This is Magento bug. They have used Date filter for all Datetime attribute DateTimeProcessing Abstract Category. They should use Datetime instead of Date or add some options to choose the different filter for date and different for datetime.


Quick Sol:- Create a di.xml an any module under adminhtml folder and and paste below code to change the argument of the Abstract Category Controller .

`<type name="Magento\Catalog\Controller\Adminhtml\Category">
	<arguments>
		<argument name="dateFilter" xsi:type="object">Magento\Framework\Stdlib\DateTime\Filter\DateTime</argument>
	</arguments>
</type>`



<img width="736" alt="Screenshot 2023-01-24 165834" src="https://user-images.githubusercontent.com/109784298/214280701-38552143-c5e6-4b07-808f-4468bdf3c6c7.png">

**Comment by aurmil** [comment]
I can confirm this bug is still present on 2.4.6 (and apparently in last version too) and @rudrendrasingh is correct about the input filter, that's also where I ended up to

input filter is set here on datetime attributes during save process: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Controller/Adminhtml/Category.php#L214

and filter input class is \Magento\Framework\Stdlib\DateTime\Filter\Date 

... so date AND time can't be processed natively by Magento on categories...
