### ISSUE TITLE
Design config edit for default theme keeps loading in Magento 2.3

### ISSUE THREAD

**Issue by MichielTG** [magento/magento2#19960]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Add a custom theme to Magento 2.3
2. Go to Design -> Configuration
3. Select the first default view
4. Select the custom theme and press save

### Expected result (*)

1. The settings page theme/design_config/edit/scope/default/ opens normally

### Actual result (*)

5. Go the the design_config_grid_flat table
![schermafbeelding 2018-12-24 om 14 18 56](https://user-images.githubusercontent.com/46106706/50400431-f4779300-0786-11e9-9a75-7729a5d092a5.png)
6. Store_website_id will be set to null
7. The website will keep loading / unable to edit any settings
![schermafbeelding 2018-12-24 om 14 21 58](https://user-images.githubusercontent.com/46106706/50400470-4e785880-0787-11e9-8707-c4c12f1723b9.png)

### Temporary fix
When going to the database and set the Store_website_id for the default view to '1' will fix the issue. However, this should be done every time when saving the page.

**Comment by magento-engcom-team** [comment]
Hi @MichielTG. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MichielTG do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by MichielTG** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MichielTG. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MichielTG, here is your [Magento instance](https://i-19960-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19960-2-3-develop.instances.magento-community.engineering/admin](https://i-19960-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by MichielTG** [comment]
### Steps to reproduce (*)

1. Add a custom theme to Magento 2.3
2. Go to Design -> Configuration
3. Select the first default view
4. Select the custom theme and press save

**Comment by MichielTG** [comment]
Issue: Confirmed

**Comment by MichielTG** [comment]
I'm unable to add a custom theme to the vanilla environment, so I can't test this. However I had a clean magento 2.3 installation so the issue does exist.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97323` were created

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @MichielTG 

`Turns out the Base64 error was just a symptom of not being able to upload logo or favicon on the page. This commit fixed my issue entirely. Happy days!`

https://github.com/magento/magento2/pull/18851/commits/ba69bfec127bed8c39c7d9e7b73d10b54449b158

**Comment by MichielTG** [comment]
Problem solved, thanks!
