### ISSUE TITLE
Magento 2.3: How to solve the message “Unable to send email”?

### ISSUE THREAD

**Issue by babybeddingdesign** [magento/magento2#19973]
Hi,
i have a problem with Magento 2.3 on the contact page and also on admin with email not been send.
1) i am getting this error on the contact page " “Unable to send email”.
2) i have flow up email extension that when i try to go into the email i get this errors: 
`
2 exception(s):
Exception #0 (ReflectionException): Class Magento\Email\Model\Source\Variables does not exist
Exception #1 (ReflectionException): Class Magento\Email\Model\Source\Variables does not exist
`
3) also on confirmation order that been send out it shows FROM: decornmo@ca-apro2.aspirationcloud.com and not FROM: sales@babybeddingdesign.com
Preconditions:
A Magento 2.3.x instance with at least one product. Reproduced on 2.3.x

Steps to reproduce:

1)
I tried update Magento with recently get the recent update and ran the commands to set up upgrade, di:compile, deploy static contents, clear cache, etc to check the issue. It could not solve the error. I checked and found that many of them reported the mail issue with Magento 2.3.0. In there, I can see that some class removed from latest Magento(2.3.0) which was included in the older version. Also, it generate compatibility issue with SMTP module. Please see the URL below for more details. Also, I noticed some compatibility issue mentioned with Magento 2.3.0, Porto theme and MagePlaza extension. I am sure about this and how to solve the error as well. 
https://github.com/mageplaza/magento-2-smtp/issues/127
2) after reading this: https://stackoverflow.com/questions/52054370/magento-2-email-sender-incorrect
I've disabled Amazon plugin and deployed static file. This not affect anything.
3)I've uploaded old jquery version to v3 from v1. Magento2.3.0 core not using latest jquery version.

![email not send](https://user-images.githubusercontent.com/44744859/50436793-22c4b200-08f0-11e9-82cc-c623b6f0cc67.JPG)
![screenshot_3](https://user-images.githubusercontent.com/44744859/50436795-22c4b200-08f0-11e9-9c02-63dc855e86ca.png)
![screenshot_4](https://user-images.githubusercontent.com/44744859/50436796-22c4b200-08f0-11e9-94d4-83a61837d5af.png)
Expected Result:

fix the problom .

Actual Result:

nothing change.

**Comment by magento-engcom-team** [comment]
Hi @babybeddingdesign. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@babybeddingdesign do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @babybeddingdesign  thank you for you report,  this problem related to your custom module.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by babybeddingdesign** [comment]
Hi,
this problem is not with custom module this is with Magento core email problem. also on a clean Magento 2.3 i cant send email.

**Comment by ghost** [comment]
Hi @babybeddingdesign but why i'm able to send email on clean 2.3 ?

**Comment by babybeddingdesign** [comment]
have no idea. where is my problem then?

**Comment by srenon** [comment]
@babybeddingdesign.... Seem like your issue has something to with "Aheadworks/Foll.." extension.
