### ISSUE TITLE
E-Mail subject not showing utf-8 characters

### ISSUE THREAD

**Issue by 4lexvav** [magento/magento2#19977]
### Preconditions
1. Magento Version 2.3.0 installed via composer
2. PHP Version 7.1.25

### Steps to reproduce
1. Create an e-mail template containing the "Ő" letter in the subject. For example, based on the Newsletter **Subscription Success** email template.
1. Change **Success Email Template** at the system Newsletter settings.
1. Subscribe for newsletter.
1. View the email in your email client. In my case, macOS Mail.app.

### Expected result
1. Email subject should contain the "Ő" letter in its subject.

### Actual result
1. Email subject contains question mark: ![](https://www.dropbox.com/s/xbekyz8aqgaaa1g/screen%202018-12-26%20at%2012.47.30.png?raw=1)

**Comment by magento-engcom-team** [comment]
Hi @4lexvav. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@4lexvav do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97339` were created

**Comment by sidolov** [comment]
Hi @4lexvav. Thank you for your report. 
The issue has been fixed in magento/magento2#19978 by @4lexvav in 2.3-develop branch
Related commit(s):
 - [bccc949cb08491a15ed0392ea29c7f34b577b215](https://github.com/magento/magento2/commit/bccc949cb08491a15ed0392ea29c7f34b577b215)

The fix will be available with the upcoming 2.3.1 release.
