### ISSUE TITLE
Catalogsearch Reindex

### ISSUE THREAD

**Issue by vincent2090311** [magento/magento2#19982]
### Preconditions (*)

1. Magento 2.2.7

### Steps to reproduce (*)

1. in this file vendor/magento/module-catalog-search/etc/indexer.xml has 2 classes
`<saveHandler class="Magento\CatalogSearch\Model\Indexer\IndexHandler" />
        <structure class="Magento\CatalogSearch\Model\Indexer\IndexStructure" />`
I dont see those classes in magento, beside that, I found 2 classes
Magento\CatalogSearch\Model\Indexer\IndexerHandler and Magento\CatalogSearch\Model\Indexer\IndexStructure

Is there anything wrong in define indexer

### Expected result (*)

1. The classes defined in xml should be existed

### Actual result (*)

1. Classes defined in xml not found

**Comment by magento-engcom-team** [comment]
Hi @vincent2090311. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vincent2090311 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@vincent2090311 can you please elaborate your issue?

**Comment by vincent2090311** [comment]
@GovindaSharma 
It isn't actually an issue (or I haven't look into the flow to check so I don't know there is any issue). I just dont understand why they put wrong class name into indexer.xml.

**Comment by magento-engcom-team** [comment]
@dmytro-ch Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97348` were created

**Comment by dmytro-ch** [comment]
@vincent2090311, thank you for the report.
This issue has been already fixed for 2.3.x version by the following PR: https://github.com/magento/magento2/pull/11626.
I think we just need to create backport for 2.2.x.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Closing as fixed #11626

**Comment by magento-engcom-team** [comment]
Hi @vincent2090311. Thank you for your report. 
The issue has been fixed in magento/magento2#19984 by @dmytro-ch in 2.2-develop branch
Related commit(s):
 - [089c660a826808545fb3fe9384bca7dd64c90fa7](https://github.com/magento/magento2/commit/089c660a826808545fb3fe9384bca7dd64c90fa7)

The fix will be available with the upcoming 2.2.8 release.
