### ISSUE TITLE
Magento Installation stucks at 69%. 

### ISSUE THREAD

**Issue by amustci065** [magento/magento2#19990]
Im very new to Magento, Would really appreciate everyones here. been trying to install for the past 2 days now. Installation stops at 69%

![magento](https://user-images.githubusercontent.com/33057348/50478498-bae69800-09d1-11e9-868a-11f39640f35e.png)
![magento 2](https://user-images.githubusercontent.com/33057348/50478504-c0dc7900-09d1-11e9-817c-75baf23f1731.png)

**Comment by magento-engcom-team** [comment]
Hi @amustci065. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amustci065 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
Possible duplicate of the other issues. Please check the logfile.

**Comment by DanielRuf** [comment]
For such things please use https://magento.stackexchange.com

**Comment by DanielRuf** [comment]
It seems the sample data can not be downloaded. Check the timeout and memory limits and so on.

**Comment by DanielRuf** [comment]
See https://github.com/magento/magento2/search?q=downloadablesampledata&type=Issues

**Comment by amustci065** [comment]
None of those solutions work for me. Thank you anyway.

**Comment by DanielRuf** [comment]
Please open a question at the mentioned stackexchange site and provide the full error log entry.
