### ISSUE TITLE
Enable Minimum order amount with Include Tax to Amount configuration. it's not  working on magento 2 default functionality.

### ISSUE THREAD

**Issue by himanshu-limbani** [magento/magento2#20004]
### Preconditions (*)
1) Currently use Magento 2.2.5 version And also check on all magento 2 version 

### Steps to reproduce (*)
Step 1: Login to admin panel
Step 2: Go to store > configuration > sales section > sales >  Minimum order Amount
Step 3: Enable Minimum order Amount , set minimum amount 100 and set Include Tax to Amount to yes
step 4: Go to fronted and add to cart product then go to cart page.

### Expected result (*)
I have to set minimum amount 100 and set Include Tax to Amount to yes then fronted add to cart product and go to cart page and see grand total is 106 with including tax. so  minimum amount is  100 and order total is 106 then able to move in next step (process to checkout)

### Actual result (*)
![cartpage](https://user-images.githubusercontent.com/45997589/50515328-e2209080-0ac9-11e9-8797-5a7d0aa88f38.png)

**Comment by magento-engcom-team** [comment]
Hi @himanshu-limbani. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@himanshu-limbani do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by himanshu-limbani** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @himanshu-limbani. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @himanshu-limbani, here is your [Magento instance](https://i-20004-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20004-2-3-develop.instances.magento-community.engineering/admin](https://i-20004-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by himanshu-limbani** [comment]
Reproduced on 2.3.x

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97375`, `MAGETWO-97376` were created

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by himanshu-limbani** [comment]
Component: Catalog

**Comment by himanshu-limbani** [comment]
Component: Catalog

**Comment by himanshu-limbani** [comment]
@magento-engcom-team give me 2.3-develop

**Comment by maheshWebkul721** [comment]
@magento-engcom-team Tax amount should not be included in total order amount, i have checked in other
 eCommerce platform as well. So i think its correct.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by EChandresh** [comment]
Is it resolved?

**Comment by himanshu-limbani** [comment]
@EChandresh Not yet

**Comment by sdzhepa** [comment]
Hello @milindsingh, @shikhamis11, @maheshWebkul721 

I see all of you in the assignment list for this issue.
Are you still working on it?
Is it still actual for the `2.3-develop` branch?

**Comment by Pavel-Fekete** [comment]
Still facing this issue on 2.4-develop

**Comment by gabrieldagama** [comment]
It would be good to review the terminology on the configuration as "Amount" is too abstract.

**Comment by viniciusbord9** [comment]
@magento I am working on this

**Comment by viniciusbord9** [comment]
@magento add to contributors team

**Comment by viniciusbord9** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @himanshu-limbani,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce** (*)

Step 1: Login to admin panel
Step 2: Go to store > configuration > sales section > sales > Minimum order Amount
Step 3: Enable Minimum order Amount , set minimum amount 100 and set Include Tax to Amount to yes
step 4: Go to fronted and add to cart product then go to cart page.


<img width="964" alt="Screenshot 2024-04-03 at 12 14 05" src="https://github.com/magento/magento2/assets/51680745/756ac6da-e0a0-4b03-9e30-20a31c4d2e3c">




https://github.com/magento/magento2/assets/51680745/d9eee3cb-077e-4a63-a361-be7f94a97996



We are able to move forward to Proceed to checkout.

Issue is no more reproducible in Latest Magento 2.4-develop instance and hence we are closing this issue.

Please feel to reopen the issue if you are facing any issue.

Thanks.
