### ISSUE TITLE
Required field validation issue in custom option on the front side 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#20006]
From admin panel admin will edit the product and set custom options as not required. Now front side try to add product in cart without select any options. The product will not add in cart and the message will display like **“The product's required option(s) weren't entered. Make sure the options are entered and try again.”**
### Preconditions (*)

1. Magento  V2.3.0 with sample data
2. PHP 7.2

### Steps to reproduce (*)

1. Go to Admin side product edit page > add custom option “Drop Down, Check Box, Radio button” as not required.
2. Goto Front side on that product > add that product in cart without selecting any options.
You will get message like this **“The product's required option(s) weren't entered. Make sure the options are entered and try again.”**

### Expected result (*)

1. Customer can order the items without selecting any product custom options. 

### Actual result (*)

1. Customer can’t order the items without selecting any product custom options. And they get message like  **“The product's required option(s) weren't entered. Make sure the options are entered and try again.”**

**Comment by magento-engcom-team** [comment]
Hi @pansuriya-emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pansuriya-emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
