### ISSUE TITLE
Cannot checkout when coupon code applied when coupon value > subtotal but less than order total (when factoring in shipping)

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#20014]
### Preconditions
1. Magento 2.2.7
2. PHP 7.1.25

### Steps to reproduce
There are 2 places where this issue occurs, for both issues:
1. Create a product. Set a price for 99 cents.
2. Create a flat rate shipping, say for 5.95. (This value MUST be greater than the value in step 1)
3. Create a coupon, Apply a fixed amount discount for the whole cart, for the value of shipping(5.95) Check apply to shipping amount
![image](https://user-images.githubusercontent.com/7268384/50542018-22dae100-0b80-11e9-89fe-d7950c37f240.png)

for Issue number 1:
4a. add product to cart
5a. proceed to checkout,
7a. Complete the shipping, Ensure that shipping dollar amount is applied. proceed to review and payments
8a. Add coupon
9a. proceed to checkout with anything other than the "0 total" checkout
![image](https://user-images.githubusercontent.com/7268384/50541995-dbeceb80-0b7f-11e9-84de-c970960ceaa1.png)

for issue number 2:
4b. add product to cart
5b. Proceed to cart page
6b. Estimate shipping and tax. Ensure that the shipping is applied
7b. Apply coupon
8b. You cannot proceed to checkout
![image](https://user-images.githubusercontent.com/7268384/50541918-4735be00-0b7e-11e9-9288-32ee3fc6197d.png)

### Expected result
1. You can checkout for 99 cents Plus tax, if applicable

### Actual result
1. You cannot checkout. (See screenshots above)

This is set up like this to provide free ground shipping to customers. We cannot enable the "free shipping" option because we also provide expedited shipping. We do not want to provide free expedited shipping.

I have not tested it, however, I believe the same could also happen when tax is greater than the subtotal.

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@justinharris1986 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by justinharris1986** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986, here is your [Magento instance](https://i-20014-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-20014-2-2-7.instances.magento-community.engineering/admin](https://i-20014-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by justinharris1986** [comment]
Ugh - I couldn't reproduce it in your instance. I'll go back with a fresh install and try to find the exact trigger on my side.
