### ISSUE TITLE
New product form fields disappeared

### ISSUE THREAD

**Issue by monotheist** [magento/magento2#20019]
### Preconditions (*)

1. Magento 2.2.6
2. Percona Server 5.7
3. PHP 7.1
4. CentOS
5. Ngnix

### Steps to reproduce (*)

1.The problem is I am unable to reproduce this. Suddenly the product entry fields disappeared which resulted in inability to create products. Only thing that I did was install Wyomind Elastic Search which required me to execute composer require guzzlehttp/guzzle and guzzlehttp/ring
2. But I disable and remove the extension and the composer packages as well and also disabled and removed all of the installed extensions. Couldn't solve this issue. Only thing I did was restore from previous day backup. I am still not sure what could have caused this issue.
![product](https://user-images.githubusercontent.com/16968205/50548334-c0add900-0c70-11e9-821e-9312a7c9f2cc.jpg)

### Expected result (*)

1. Ability to create product

### Actual result (*)

1. Inability to create product since most of the product and attribute fields disappeared.

**Comment by magento-engcom-team** [comment]
Hi @ethniccode. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ethniccode do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by monotheist** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @ethniccode. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ethniccode, here is your [Magento instance](https://i-20019-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-20019-2-2-6.instances.magento-community.engineering/admin](https://i-20019-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment]
@ethniccode I wasn't able to reproduce it on the this version.

**Comment by monotheist** [comment]
How did you test this? Explain please.

**Comment by cedarvinda** [comment]
Yes,
Step 1: Loged in to admin panel 
Step 2: Go to catalog link from left menu > product 
Step 3: Create new product ..

**Comment by monotheist** [comment]
Please read my observations and see the screenshot. The problem exists but it is not easy to reproduce. This happens on a production server not a vanilla install. You should test with the pre-conditions I have mentioned. Does the instance have percona 5.7 and did you install the composer packages?

**Comment by monotheist** [comment]
@magento-engcom-team Please reopen this issue.
