### ISSUE TITLE
PayPal API settings missing in admin panel

### ISSUE THREAD

**Issue by smadasam** [magento/magento2#20029]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2
3. Debian

### Steps to reproduce (*)

1. log into the admin panel
2. navigate to paypay express checkout to set API settings

### Expected result (*)

1. API settings are available to use
2. eg API username, password, signature, etc.

### Actual result (*)

1. These sections are missing
2.

**Comment by magento-engcom-team** [comment]
Hi @smadasam. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@smadasam do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by smadasam** [comment]
[https://cloud.githubusercontent.com/assets/131546/15627897/351b4ff6-24f3-11e6-9339-a2ad5d0822ff.png](url)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @smadasam thank you for you report, this issue has already fixed in 2.3-develop branch
![selection_251](https://user-images.githubusercontent.com/40756439/50583454-fa016700-0e71-11e9-8646-4b1681687125.png)

**Comment by tkymuk** [comment]
are the username, password and signature field supposed to truncate after saving?

**Comment by VZeroCool** [comment]
@engcom-backlog-nazar can you please tell me commit. I'm having same issue I've upgraded to 2.3.1 from 2.3 CE. Suddenly this setting missing. It was there when I was on 2.3 but when it get disappear dont know. Please reference commit to fix this.
