### ISSUE TITLE
Throwing fatal error while customer login when customer is created from Admin

### ISSUE THREAD

**Issue by ghost** [magento/magento2#20020]
### Preconditions (*)

1. Magento - 2.3.0
2. PHP - 7.2.5

### Steps to reproduce (*)

1. Login into Magento Admin Panel.
2. Create Customer from Admin Panel.
3. Try to login this customer with any password from frontend.

### Expected result (*)

1. There should be message that email or password is invalid or some similar error.

### Actual result (*)

1. Throwing fatal error on frontend.

![customer login](https://user-images.githubusercontent.com/15954089/50548832-66fddc80-0c79-11e9-99dc-b2d077245c95.png)

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rahulwebkul do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-20020-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20020-2-3-develop.instances.magento-community.engineering/admin](https://i-20020-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
issue is fixed in Magento 2.3-develop
