### ISSUE TITLE
Install 2.3.0 Unable to apply patch

### ISSUE THREAD

**Issue by alex4allofyou** [magento/magento2#20034]
### Preconditions 
1. Magento 2.3.0
2. CentOS7
3. PHP 7.2.13
4. Apache 2.4.6
5. MySQL 5.7.23

### Steps to reproduce
1. Download magento 2.3.0 with Composer and open browser to get setup wizard page
2. Readiness Check : approved
3. Select DB
4. Use normal settings, a Magento generated key
5. Uncheck all additional modules, or check them all, tried both variations
6. Click install button

### Expected result
Install.

### Actual result
Install hangs at: Installing... 15%.
Clicking on Console Log shows that this is at Module 'Magento_InventorySales'

`Module 'Magento_InventorySales':
[ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\InventorySales\Setup\Patch\Schema\InitializeWebsiteDefaultSock for module Magento_InventorySales. Original exception message: The store that was requested wasn't found. Verify the store and try again.`

### With Composer
`Fatal error: Uncaught Error: Cannot instantiate interface Magento\InventoryCatalogApi\Api\DefaultStockProviderInterface in C:\domain.localhost\vendor\magento\framework\ObjectManager\Factory\Dynamic\Developer.php:50`

**Comment by magento-engcom-team** [comment]
Hi @alex4allofyou. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@alex4allofyou do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment]
@alex4allofyou Have you tried installation in incognito or private window of the browser?
I tried and can successfully install 2.3 via composer.

**Comment by ghost** [comment]
Hi @alex4allofyou thank you for you report please report here -> https://github.com/magento-engcom/msi-module

**Comment by alex4allofyou** [comment]
I have no idea to reproduce this 

> 
> 
> @alex4allofyou Have you tried installation in incognito or private window of the browser?
> I tried and can successfully install 2.3 via composer.

Tried it, but it does the same. 
It hangs and when you refresh you will see 'You're ready! Install Now' again.

**Comment by alex4allofyou** [comment]
Does anybody know what it means with 'The store that was requested wasn't found. Verify the store and try again.'? Why would it request a shop which has to be installed?

**Comment by alex4allofyou** [comment]
Dependancy Check failed, did not warn. 

You need InventoryCache, Catalog, CatalogAdminUI and CatalogSearch as well.

**Comment by JianxunSu** [comment]
Module 'Magento_InventorySales':
Has the same issue when install magento2 2.3 from fresh, both with composer and webclient, same error as following: 
[ERROR] Magento\Framework\Setup\Exception: Unable to apply patch Magento\InventorySales\Setup\Patch\Schema\InitializeWebsiteDefaultSock for module Magento_InventorySales. Original exception message: Stock with id "1" does not exist. in /shared/httpd/echair/htdocs/vendor/magento/framework/Setup/Patch/PatchApplier.php:232
----------------------------------------------
This issue happened when modules selected manually or none of them, when select all and install, it got a success.

**Comment by adamzero1** [comment]
For anybody still experiencing this issue on fresh installs please see: https://magento.stackexchange.com/questions/315644/unable-to-apply-patch-magento-inventorysales-setup-patch-schema-initializewebsit/315645#315645

**Comment by phoenix-bjoern** [comment]
We still experience this issue in 2.4. When patching `vendor/magento/module-inventory-sales/Setup/Operation/AssignWebsiteToDefaultStock.php` and reinit stores, it works:

```
    public function execute()
    {
        $this->storeManager->reinitStores();
        $websiteCode = $this->storeManager->getWebsite()->getCode();
```

So why has this issue been closed if it can only work if manually patching core files?!
