### ISSUE TITLE
Images inserted in category description broken in the frontend

### ISSUE THREAD

**Issue by jayanta88** [magento/magento2#20031]
### Preconditions (*)

1. Magento CE 2.2.3

### Steps to reproduce (*)

1. Login to Admin
2. Add category description and click WYSIWYG Editor button, it will open a popup.
3. Then add an image using Insert Image Button there.
4. Now when you will save it. You will see the image url is like domain.com/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYm94LWltZzIuanBnIn19/

### Expected result (*)

1. It should generate pub/media url which will show in frontend.

### Actual result (*)

1.  Instead of showing admin image url like domain.com/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvYm94LWltZzIuanBnIn19/

**Comment by magento-engcom-team** [comment]
Hi @jayanta88. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jayanta88 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jayanta88** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @jayanta88. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayanta88, here is your [Magento instance](https://i-20031-2-2-3.instances.magento-community.engineering).
Admin access: [https://i-20031-2-2-3.instances.magento-community.engineering/admin](https://i-20031-2-2-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jayanta88** [comment]
@magento-engcom-team I've reproduced the same issue in the above Magento instance. Please see this http://take.ms/6InZr

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @jayanta88 . Thank you for your report. 
The issue has been fixed in magento/magento2#18215 by @adammada in 2.2-develop branch
Related commit(s):
 - [4e62fe32bf6f27b583eeb8d5d2309c7abebd5535](https://github.com/magento/magento2/commit/4e62fe32bf6f27b583eeb8d5d2309c7abebd5535)
 - [bf2efffff0da82f33796c82d643403545466911d](https://github.com/magento/magento2/commit/bf2efffff0da82f33796c82d643403545466911d)

The fix will be available with the upcoming 2.2.8 release.

**Comment by jayanta88** [comment]
Hi @engcom-backlog-nazar 

I've added the fixes. Replaced the method with the below but still, it's generating admin url like admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvY2F0ZWdvcnkvaGVyY3VsZXMuanBlZyJ9fQ,,/


      decodeDirectives: function (content) {
            // escape special chars in directives url to use it in regular expression
            var url = this.makeDirectiveUrl('%directive%').replace(/([$^.?*!+:=()\[\]{}|\\])/g, '\\$1'),
                reg = new RegExp(url.replace('%directive%', '([a-zA-Z0-9,_-]+)')),
                uriReg = /___directive\/(.*)\/key\//g;

            content = content.replace(uriReg, function (match) {
                return decodeURIComponent(match);
            });

            return content.gsub(reg, function (match) { //eslint-disable-line no-extra-bind
                return Base64.mageDecode(match[1]);
            });
        }

**Comment by jayanta88** [comment]
@magento-engcom-team - 

I've applied the same [solution here ](https://github.com/magento/magento2/commit/4e62fe32bf6f27b583eeb8d5d2309c7abebd5535) still this is not working. Is there anything else need to do?

Thanks
