### ISSUE TITLE
loading icon disappearing before background process completes for braintree payment (Admin order)

### ISSUE THREAD

**Issue by bharanikonda** [magento/magento2#20038]
### Preconditions (*)

1. Magento 2.1.15
2.

### Steps to reproduce (*)

1. Enable Braintree payment method 
2. Navigate to create order page in admin
3. Add items, Enter address, Select shipping method
4. Select braintree credit card/braintree saved card as payment method
5. Click on submit button(at the bottom of the page)

### Expected result (*)

1. Loading icon must be displayed untill the page is redirected to new order view page.

### Actual result (*)

1. Loading icon is disappearing before background process completes (https://www.screencast.com/t/AqqwzC0B ). 
2. Since loading icon is disappeared, admin can click on another submit button(at the top). If so, multiple orders are creating.

**Comment by magento-engcom-team** [comment]
Hi @bharanikonda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bharanikonda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @bharanikonda  i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.

**Comment by bharanikonda** [comment]
Hi, 

This issue is replicating in 2.2.6 as well. Please find the below reference screencast.
https://www.screencast.com/t/x2lIGpofu

Thanks.

**Comment by ghost** [comment]
@bharanikonda ok. I will recheck on 2.3-develop

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97401`, `MAGETWO-97402` were created

**Comment by ghost** [comment]
I am working on this at #dmcdindia19”

**Comment by magento-engcom-team** [comment]
@kunal-rtpl thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @bharanikonda. Thank you for your report. 
The issue has been fixed in magento/magento2#22675 by @kunal-rtpl in 2.3-develop branch
Related commit(s):
 - [1a62a1094829fc4d00b68466d365aaf1d32deadf](https://github.com/magento/magento2/commit/1a62a1094829fc4d00b68466d365aaf1d32deadf)
 - [c1a2bd712f726112d2005b5475656e017808b14b](https://github.com/magento/magento2/commit/c1a2bd712f726112d2005b5475656e017808b14b)
 - [2f35a3bf269c36bbead7475f780e6033edf84fe3](https://github.com/magento/magento2/commit/2f35a3bf269c36bbead7475f780e6033edf84fe3)

The fix will be available with the upcoming 2.3.3 release.
