### ISSUE TITLE
Bug: «Please wait...» spinner text is untranslatable on admin pages

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2003]
A detailed bug description: https://mage2.pro/t/101

**Comment by okorshenko** [comment]
@dfediuk, thank you for reporting of untranslatable issues. Analyzing all issues that you have already reported, I can notice that you have already fixed most of these issues on your side. It would great, if you can merge all your fixes from [reported issues](https://github.com/magento/magento2/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+author%3Adfediuk+untranslatable+in%3Atitle) into one Pull Request. In this case we will deliver your fixes to Magento 2 code base faster with keeping your name in Magento 2 history. Thank you for helping us make Magento 2 better!

**Comment by anton-huz** [comment]
Hi Dmitrii,
Described issue is not only the _loader_ problem. It touches all client side app. Because as you found _dictionary_ is loaded in async way.

In 2.1 we improved loading dictionary in browser. But it still is faw from ideal. And we are looking for improvement.

Current issue has limited scope and fixed in 2.1. I close the issue.

But if you has any ideas for translation improvements — you are welcome!

## 

Thanks,
Anton Guz
