### ISSUE TITLE
Magento 2 Catalog price rule preview

### ISSUE THREAD

**Issue by abbasalibutt** [magento/magento2#20036]
### Preconditions (*)

1. Magento EE 2.2.2
2. PHP 7.0.33
3. MySQL 

### Steps to reproduce (*)

1. Create Catalog price rule
2. Marketing -> Promotions -> Catalog price rule
3. Websites: Select all websites
4. Select all customer groups
5. Conditions: Category is 4 or you can set no condition so it will apply for all products
![selection_096](https://user-images.githubusercontent.com/1251949/50585147-f6dc9a00-0eb6-11e9-8576-3fcbedda6354.png)

6. Actions: 
         Apply : Adjust final price to discount value
         Discount Amount: 7.0000
7. Click save
![selection_097](https://user-images.githubusercontent.com/1251949/50585177-1ecbfd80-0eb7-11e9-8787-4ff55433e8a0.png)

8. Click schedule new update
         Start Date: Any future date
         End Date: Any future date but should be greater than Start Date
         Rule Information: Active
9. Click Save
![selection_098](https://user-images.githubusercontent.com/1251949/50585205-3a370880-0eb7-11e9-9fe4-ee8aa49c15d3.png)

10. Click Preview link in scheduled changes 

### Expected result (*)

1. When Add the product to the cart according to the rule conditions then product price should be 7

### Actual result (*)

1. It is showing it's original price without discount
![selection_099](https://user-images.githubusercontent.com/1251949/50585256-74080f00-0eb7-11e9-8b8a-c589a2b938f0.png)
![selection_100](https://user-images.githubusercontent.com/1251949/50585292-9863eb80-0eb7-11e9-99bd-ff11b0f970a7.png)

**Comment by magento-engcom-team** [comment]
Hi @abbasalibutt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abbasalibutt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @abbasalibutt  , thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by abbasalibutt** [comment]
Why this issue is closed?

**Comment by ghost** [comment]
@abbasalibutt `Click schedule new update` schedule available only on EE version.

**Comment by abbasalibutt** [comment]
@engcom-backlog-nazar Yes I am using EE edition and if you will see my details I am clicking on schedule preview after create a schedule.

![selection_101](https://user-images.githubusercontent.com/1251949/50585762-e548c180-0eb9-11e9-8dff-ee6ccf16bba5.png)

**Comment by ghost** [comment]
@abbasalibutt GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
