### ISSUE TITLE
Static composer tests fail - version property error

### ISSUE THREAD

**Issue by sta1r** [magento/magento2#20040]
If I clone a fresh copy of magento2 and run the static test suite, the ComposerTest fails because each packaged module has a 'version' property. This is problematic in an automated build scenario for a custom module. 

### Preconditions (*)

1. Magento v2.3

### Steps to reproduce (*)

1. Clone magento2 repo
2. Run `vendor/bin/phpunit -c dev/tests/static/phpunit.xml.dist`

### Expected result (*)

1. Static test suite passes

### Actual result (*)

1. Static test suite fails with multiple errors:
```
Version must not be specified in the root and package composer JSON files in Git
Failed asserting that object of class "stdClass" does not have attribute "version".
```

**Comment by magento-engcom-team** [comment]
Hi @sta1r. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sta1r do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Thank you for reporting this issue!
I was not able to reproduce this issue by the given steps.

### Action:
`vendor/bin/phpunit -c dev/tests/static/phpunit.xml.dist`
### Output:
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.

```
.......S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  231 / 4230 (  5%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....................I........................SSS....S........SSS......SSS......................................................................................................  462 / 4230 ( 10%)
.......................................................................................................................................................................................................................................  693 / 4230 ( 16%)
.......................................................................................................................................................................................................................................  924 / 4230 ( 21%)
....................................................................................................................................................................................................................................... 1155 / 4230 ( 27%)
....................................................................................................................................................................................................................................... 1386 / 4230 ( 32%)
....................................................................................................................................................................................................................................... 1617 / 4230 ( 38%)
....................................................................................................................................................................................................................................... 1848 / 4230 ( 43%)
....................................................................................................................................................................................................................................... 2079 / 4230 ( 49%)
....................................................................................................................................................................................................................................... 2310 / 4230 ( 54%)
....................................................................................................................................................................................................................................... 2541 / 4230 ( 60%)
....................................................................................................................................................................................................................................... 2772 / 4230 ( 65%)
....................................................................................................................................................................................................................................... 3003 / 4230 ( 70%)
....................................................................................................................................................................................................................................... 3234 / 4230 ( 76%)
....................................................................................................................................................................................................................................... 3465 / 4230 ( 81%)
....................................................................................................................................................................................................................................... 3696 / 4230 ( 87%)
....................................................................................................................................................................................................................................... 3927 / 4230 ( 92%)
....................................................................................................................................................................................................................................... 4158 / 4230 ( 98%)
........................................................................                                                                                                                                                                4230 / 4230 (100%)

Time: 5.64 minutes, Memory: 532.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 4230, Assertions: 42018, Skipped: 288, Incomplete: 1.
```

**Comment by sta1r** [comment]
I see now that the `version` property is removed from module composer files on 2.3-develop (but is present on 2.3, which I was using in my build).
