### ISSUE TITLE
Empty cart FPC Enable Drop Items

### ISSUE THREAD

**Issue by ElundKasper** [magento/magento2#20049]
### Preconditions (*)
1. Magento 2.3

When installing following modules have been removed for setup:

Dotdigitalgroupemail
Magento-analytics
Magento Authorizenet
Magento Braintree
Magento markedsplace
Magento NewRelicReporting
Magento Persistent
Magento Sampledata

After fresh install.
Install sampledata via composer
Run bin/magento setup:upgrade

### Steps to reproduce (*)
1. select top category women 
2. add product to cart
3. select Gear category

minicart is now empty

4. add product to cart

1 product now added to cart

### Expected result (*)
2 products added to cart - but only one is in.

### Actual result (*)
1 product in cart the last one added the first has been dropped.

It seems like this only happens when the page is not cached.
if you start all over then you will have 2 products in cart like suposed.

When you flush the cache it all start over again.

[Recording #4.zip](https://github.com/magento/magento2/files/2721978/Recording.4.zip)

**Comment by magento-engcom-team** [comment]
Hi @ElundKasper. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ElundKasper do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ElundKasper thank you for you report, i'm not able to reproduce following steps you described, seems like this is your environment problem.
