### ISSUE TITLE
CMS API does not allow Block or Page to link to Stores - Interface has missing methods

### ISSUE THREAD

**Issue by johnorourke** [magento/magento2#20053]
### Summary (*)

The CMS module Data API does not let you view or set the store links when using the Interfaces, but the underlying Page or Block model does have support for it. The core code uses the magic getter/setter getStoreId and setStoreId to implement this, but those methods are not exposed in the interface.  

The Models have an additional 'getStores' method, and the phpdoc specifically mentions getStoreId and setStoreId.

### Examples (*)

1. from a clean 2.3.0 installation with sample data
1.1. if you do not have any sample data, add a cms Page. It will be given ID 1. 
2. make the REST API call `GET /rest/V1/cmsPage/1` - you will see no 'stores' or 'store_id' 
3. make the REST API call `PUT /rest/V1/cmsPage/1` with data `{"page":{"title":"test title change","store_id":[1]}`

The tests above will fail, of course. Apply this simple patch in the app/code/Magento/Cms directory, and the code will now work:
https://gist.github.com/johnorourke/5a7846c75382d739915a67251b069e18 

### Proposed solution

The patch above simply adds the missing methods. It does not break any core code, and would only break an external module that provides a different Page or Block model implementation without inheriting the core Page or Block model - I think this is unlikely to be a real situation because most developers would extend the core Page and Block model, so they would inherit the methods.

**Comment by magento-engcom-team** [comment]
Hi @johnorourke. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@johnorourke do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by johnorourke** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @johnorourke. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @johnorourke, here is your [Magento instance](https://i-20053-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20053-2-3-develop.instances.magento-community.engineering/admin](https://i-20053-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by johnorourke** [comment]
Added 1.1 in the steps to reproduce, because default test instances do not have sample data installed.

**Comment by johnorourke** [comment]
Also see #17458 and its PR #17995 regarding adding Extension Attributes support to these same models - related but not duplicate.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97415`, `MAGETWO-97416` were created

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @johnorourke   thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by PivitParkour94** [comment]
Are there any plans to actually have this implemented? Some sort of time estimate for when this will be available?
