### ISSUE TITLE
Catalog Price Rules not working according to specific customer group

### ISSUE THREAD

**Issue by brightnessjsoni** [magento/magento2#20062]
**Description (*)**
I have created one catalog price rule with 10% discount to specific category(for eg. 'cat1') and assign specific customer group(for eg. 'ABC') to created rule. In frontend, I am not able to see discounted price on product detail page if logged in customer belongs to specific customer group('ABC') and check product of category 'cat1'.

**Preconditions**
    Magento 2.2.6 & 2.3.0.
    
**Steps to reproduce**
    Create Customer Group('ABC').
    Create Catalog Price Rule('Test') with 10% discount with specific category('cat1') and assign rule to 
    new created customer group('ABC')
    Create customer('Joe') from frontend and assigned new created customer('Joe') to customer 
    group('ABC')
    Login with created customer('Joe') from frontend and check any category('cat1') product and go to 
    product detail page.

**Expected result**
    Catalog Price Rule('Test') should apply.

**Actual result**
    Catalog Price Rule is not applied.

**Comment by magento-engcom-team** [comment]
Hi @brightnessjsoni. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@brightnessjsoni do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by brightnessjsoni** [comment]
Issue has been resolved now. I am closing this issue.
