### ISSUE TITLE
Magento2 Frontend next Site not showing

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#20065]
Hello,

i am using the magento 2.2.6, in the customer fronted under the downloadable products the next sites are not showing.

![image](https://user-images.githubusercontent.com/31250340/50686413-9a47bf00-101d-11e9-88f0-776e1f17b16c.png)

The  grey field under the orders, where i can show the older orders or the next / previous site is empty.

I think it is the following Code, but i have no solution.

##<div class="toolbar downloadable-products-toolbar bottom">
##
   
 ## <div class="pager">
  ## <p class="toolbar-amount">
  ## <span class="toolbar-number">
  ## Artikel 1 bis 10 von 109 gesamt                        </span>
  ## </p>
    
 ##  <div class="pages">
  ## <strong class="label pages-label" id="paging-label">Seite</strong>
  ## <ul class="items pages-items" aria-labelledby="paging-label">
    
    
    
  ## <li class="item current">
  ## <strong class="page">
  ## <span class="label">Sie lesen gerade Seite</span>
  ## <span>1</span>

Kind regards 
Olek

**Comment by magento-engcom-team** [comment]
Hi @Olek89. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Olek89 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Olek89 Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

**Comment by ghost** [comment]
@Olek89 Please describe the issue in more detail. what did you mean next sites ? Describe your problem more detail, then reopen the issue.

**Comment by Olek89** [comment]
How can i reopen it?

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-20065-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-20065-2-2-6.instances.magento-community.engineering/admin](https://i-20065-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@Olek89 Can you reproduce this on provided instance ?

**Comment by Olek89** [comment]
Thank you for the login, but there are no products to reproduce so much orders,
to show it in the customer login site.

**Comment by ghost** [comment]
@Olek89 you can create it.

**Comment by Olek89** [comment]
in the test shop it is shown, what i have marked, why not at me?
![image](https://user-images.githubusercontent.com/31250340/50687402-78503b80-1021-11e9-9488-f4c933227a14.png)

**Comment by ghost** [comment]
@Olek89 this may be related to your custom theme or module.

**Comment by Olek89** [comment]
Did you know where i can check it?
Which modul is it?

**Comment by ghost** [comment]
@Olek89 No have no idea.

**Comment by Olek89** [comment]
Can you reopen the ticket?
