### ISSUE TITLE
2.3.0 - clearing pub/static makes me login 3 times

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#20060]
When I am developing locally, I remove the contents of pub/static by running a script that I wrote. It also clears the cache.

But, the act of clearing pub/static seems to be causing a login issue that did not exist pre-2.3 release. I have managed to determine that it the act of clearing pub/static on it's own that causes this.

### Preconditions (*)
1. Magento 2.3.0
2. PHP 7.2.13
3. MySQL 5.7.24
4. 'MAGE_MODE' => 'default'
5. FPC is Varnish
6. Varnish installed on port 80, nginx on 8080 and 443. php7.2-fpm is in use.
7. Front and back end is set to https, so Varnish is bypassed on my setup at the moment.
8. All cache types in Magento are enabled.

### Steps to reproduce (*)
1. Clear contents of pub/static/* folder
2. Clear browser cookies (not required) and browser cache (not required). Just doing this step to ensure everything is "clean"
3. Go to admin login on https.
4. Attempt to login
5. Invalid Form Key. Please refresh the page.
6. Attempt to login - works this time.
7. Go to Stores->Configuration
8. Visible section not found.
9. Redirected to login
10. Login again. This time it works.

### Expected result (*)
1.  Login to work first time.

### Actual result (*)
1. Have to login 3 times!

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@milindsingh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97428` were created

**Comment by cscd98** [comment]
@milindsingh Any updates on this issue?

**Comment by cscd98** [comment]
Any updates on this, this bug is behond annoying.

**Comment by tvaught991** [comment]
Agreed. Having the issues as well!

**Comment by cscd98** [comment]
@tvaught991 @milindsingh This appears fixed in 2.3-develop, does anyone know which PR fixed it?

**Comment by orlangur** [comment]
@craigcarnell closing issue on the strength of your comment, really doubt it's possible to determine without `git bisect` or something.

**Comment by cscd98** [comment]
@orlangur 

Is there anyway to checkout a specific milestone? I could do with checking out 2.3.1 (https://github.com/magento/magento2/milestone/23) or 2.3.2 to help me track where the bug is fixed.

I need to launch a site based on 2.3.0 but I can't with this bug.

**Comment by orlangur** [comment]
@craigcarnell milestones were introduced just recently, I added 2.3.2 now as issue seems to be fixed in `2.3-develop` according to your testing.

**Comment by cscd98** [comment]
@orlangur It's taken me about an hour but I found it..

https://github.com/magento/magento2/commit/49a25f2de1f5abb3c9399102c651a91b73417f39

It actually says in amongst the other comments!!

```
* [MC-10938](https://jira.corp.magento.com/browse/MC-10938) 2.3.0 - clearing pub/static makes me login 3 times
```

**Comment by orlangur** [comment]
@craigcarnell hmm, at least they have it in comment messages. I'll raise in Slack that such fixes should be properly linked to GitHub issues. Thanks for sorting this out!

**Comment by cscd98** [comment]
@orlangur Thanks that would be very helpful :+1:, but I do not know which particular commit to add locally, due to all being merged under one PR.

**Comment by hostep** [comment]
@craigcarnell: it's probably this commit: https://github.com/magento/magento2/commit/a6240195157c0415a155507995d2cf9d4ce03380

If you have a local clone of Magento2's repository, you can usually find the commits using:
`git log --grep 'MC-10938' 2.3-develop`

**Comment by cscd98** [comment]
@hostep Woot :+1: 

https://github.com/magento/magento2/commit/a6240195157c0415a155507995d2cf9d4ce03380

```
commit 49a25f2de1f5abb3c9399102c651a91b73417f39
Merge: 7cdcb277d75 17c10c527c6
Author: Roman Ganin <rganin@adobe.com>
Date:   Mon Feb 11 20:33:36 2019 -0600

    Merge pull request #3725 from magento-epam/EPAM-PR-38-39-40
    
    * [MAGETWO-91631](https://jira.corp.magento.com/browse/MAGETWO-91631) [Magento Cloud]Prefix in checkout not starting with blank value
    * [MAGETWO-95836](https://jira.corp.magento.com/browse/MAGETWO-95836) [Magento Cloud] If a product has a custom attributes which requires a Unique Value, it cannot be saved when there's an active Scheduled Update
    * [MAGETWO-96852](https://jira.corp.magento.com/browse/MAGETWO-96852) [2.3.x] Impossible to sort Root Categories via drag'n'drop
    * [MAGETWO-96421](https://jira.corp.magento.com/browse/MAGETWO-96421) [2.3.x] Header Minicart ,Shopping cart page and Checkout page show incorrect product name
    * [MAGETWO-95812](https://jira.corp.magento.com/browse/MAGETWO-95812) Required RMA Attributes are not validated while Customer submits a return
    * [MAGETWO-95186](https://jira.corp.magento.com/browse/MAGETWO-95186) [2.3] Incorrect table rates shipping charge at check out with cart price rule
    * [MC-4316](https://jira.corp.magento.com/browse/MC-4316) Tax calculation process does not follow "Apply Tax On" setting - GitHub #14469
    * [MAGETWO-96545](https://jira.corp.magento.com/browse/MAGETWO-96545) Wrong calculation of invoiced items in shipment document in order with bundle product after partial invoice
    * [MC-10963](https://jira.corp.magento.com/browse/MC-10963) Can only export default store view items when upgrade to 2.3.0
    * [MAGETWO-64324](https://jira.corp.magento.com/browse/MAGETWO-64324) WebAPI: product "has_options" flag not updated when options added via API
    * [MC-10938](https://jira.corp.magento.com/browse/MC-10938) 2.3.0 - clearing pub/static makes me login 3 times
    * [MC-10944](https://jira.corp.magento.com/browse/MC-10944) [B2B] My Quote disappears from Customer account when FPC is on
    * [MC-5542](https://jira.corp.magento.com/browse/MC-5542) Fix testOutputErrorsWithMessageCategoryAndTrace on PHP 7.2
    * [MAGETWO-58841](https://jira.corp.magento.com/browse/MAGETWO-58841) API call with pageSize and currentPage > items should return error

commit a6240195157c0415a155507995d2cf9d4ce03380
Merge: 8cd25499a2c 5fd9eeea06a
Author: Veronika Kurochkina <veronika_kurochkina@epam.com>
Date:   Thu Feb 7 17:15:28 2019 +0300

    Merge remote-tracking branch 'remotes/github/MC-10938' into EPAM-PR-40

commit 5fd9eeea06a82ea6e49bd07b379242d543446906
Merge: e1e9328f6d7 295773182e2
Author: Yauhen_Lyskavets <yauhen_lyskavets@epam.com>
Date:   Tue Jan 29 10:10:48 2019 +0300

    Merge branch '2.3-develop' of github.com:magento-epam/magento2ce into MC-10938

commit e1e9328f6d7a96fa3c438ed653b793c2dd06771c
Merge: 2d9647ad547 b8eb424c108
Author: Yauhen_Lyskavets <yauhen_lyskavets@epam.com>
Date:   Mon Jan 28 19:19:01 2019 +0300

    Merge branch '2.3-develop' of github.com:magento-epam/magento2ce into MC-10938

commit 2d9647ad547edc92ac2b7a8488f967f52148649d
Author: Yauhen_Lyskavets <yauhen_lyskavets@epam.com>
Date:   Mon Jan 28 14:26:10 2019 +0300

    MC-10938: 2.3.0 - clearing pub/static makes me login 3 times
    
    - Disable session initialization when backend json statics generated.
```

**Comment by cscd98** [comment]
Patch seems to be included in 2.3.1

**Comment by orlangur** [comment]
@craigcarnell there is no `2.3.1` milestone available though :(

**Comment by hostep** [comment]
Sure there is: https://github.com/magento/magento2/milestone/23 ;)
But since 2.3.1 was released today, it makes no sense to keep it open I guess.
