### ISSUE TITLE
2.3.0 instance Terms & Conditions saved, but not appear at Store→Terms and Conditons

### ISSUE THREAD

**Issue by Nedertoys** [magento/magento2#20061]
All,
I have a challange by setting up the terms and conditions. I am using Magento version 2.3.0

I added new Terms & Conditions, saved it, but they do not appear on my backend. On my frontend no problems at all. However I cano ot deactivate them 

I will try to explain it step by step:

- I started the following path: Store→Settings→Terms and Conditions and everything looks normal
![1](https://user-images.githubusercontent.com/46358299/50661627-f968ed80-0fa3-11e9-96d5-7fb3616f1f30.JPG)

- Then I added and applied the new Terms and Conditions(on my Frontend it works fine)
![2](https://user-images.githubusercontent.com/46358299/50661714-3634e480-0fa4-11e9-9313-18fdd8292172.JPG)

- But when I got back to Store→Settings→Terms and Conditions There's nothing to select anymore. 
![3](https://user-images.githubusercontent.com/46358299/50661743-52d11c80-0fa4-11e9-8706-ff20b2181023.JPG)

Expected Result: that the new terms and conditions appeared at the Store→Settings→Terms and Conditions
Actual result: just a blank screen

How will I be able to change or disable it whenever I want if it does not appear? Hope to hear from you soon.

**Comment by magento-engcom-team** [comment]
Hi @Nedertoys. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Nedertoys do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Nedertoys** [comment]
Yes

**Comment by Nedertoys** [comment]
I Expected that the new terms and conditions appeared at the Store→Settings→Terms and Conditions 
The actual result where just a blank screen

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@Nedertoys please correct the format of issue creation
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20061-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20061-2-3-develop.instances.magento-community.engineering/admin](https://i-20061-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
This issue is not present at 2.3-develop instace 
![screenshot_20190104-073458__01](https://user-images.githubusercontent.com/25526037/50670720-71aacf80-0ff3-11e9-9e11-52af088ed84d.jpg)

**Comment by shikhamis11** [comment]
@Nedertoys since I am not able to reproduce this I am closing this issue if you still think it's valid one please update more about issue also share video of the issue I will reopen this
