### ISSUE TITLE
Can't checkout with Paypal by Braintree with Virtual Products

### ISSUE THREAD

**Issue by gavinlimely** [magento/magento2#20066]
### Preconditions (*)

1.  Magento 2.3.0
2. Paypal by Braintree enabled.

### Steps to reproduce (*)

1.  Add Virtual product to the cart & try to checkout using Paypal by Braintree.

### Expected result (*)

1. You should be able to checkout as normal.

### Actual result (*)

1. You get an error message stating the following: 

```
Please check the billing address information.
firstname is a required field. 
lastname is a required field. 
street is a required field. 
city is a required field. 
telephone is a required field. 
postcode is a required field. 
countryId is a required field.
```

**Comment by magento-engcom-team** [comment]
Hi @gavinlimely. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gavinlimely do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gavinlimely thank you for you report, i'm not able to reproduce following steps you described, this may be related to your custom module or theme.

**Comment by gavinlimely** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @gavinlimely. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @gavinlimely, here is your [Magento instance](https://i-20066-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20066-2-3-0.instances.magento-community.engineering/admin](https://i-20066-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gavinlimely** [comment]
hi @magento-engcom-team 

This is definitely still a problem on a Vanilla instance. The issue only happens when you actually click pay. The OAuth flow works fine. However once you're redirected back to the site, after selecting your payment method within the Paypal dialogue. If you then click pay now, you get the error message as described above.

**Comment by ghost** [comment]
@gavinlimely this is acknowledged issue, and fixed on 2.3-dev branch, and will be available on 2.3.1 release

**Comment by ghost** [comment]
@gavinlimely this issue-> https://github.com/magento/magento2/issues/18765

**Comment by nicholasscottfish** [comment]
Hi there,

Has there been an official patch for this issue. I'm also experiencing this on v2.2.5, any help would be appreciated?

"Please check the billing address information. firstname is a required field. lastname is a required field. street is a required field. city is a required field. telephone is a required field. postcode is a required field. countryId is a required field."
