### ISSUE TITLE
Magento 2.2.5 setup upgrade not working

### ISSUE THREAD

**Issue by mohammadalfaz** [magento/magento2#20089]
Hi,

I have used Magento 2.2.3. Now currently I am using 2.2.5. In this version when I run setup upgrade command then admin & frontend will not load css and js. But after content deploy command it works. In 2.2.3, If I run setup upgrade the js and css was working fine.

Whether anything related to this has been changed?

**Comment by magento-engcom-team** [comment]
Hi @mohammadalfaz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mohammadalfaz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by davidverholen** [comment]
Hi @mohammadalfaz ,

this is only intended for bug tracking. For questions about magento please go to https://magento.stackexchange.com/ or https://community.magento.com/

(First guess would be that you are not in developer mode, where assets are generated dynamically - https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-mode.html)
