### ISSUE TITLE
Product image issue: upgrade magento 2.2.7 to 2.3.0.

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#20090]
Product image issue when upgrade magento 2.2.7 to 2.3.0.

I have two stores (id_1) and (id_2) and with different language.

Issue (id_1): Every category page is only Magento 2 default product image for all products. No anything real product images what is added to products. How fix this issue? Everything works well in the store (id_2) without any problems.

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1
3. No sample data

### Steps to reproduce (*)

1. Upgrade magento 2.2.7 to 2.3.0 using script [https://raw.githubusercontent.com/magento/magento2/2.3.0/dev/tools/UpgradeScripts/pre_composer_update_2.3.php](url)

Execution of commands: 

- php -f pre_composer_update_2.3.php -- --root='<path/to/magento/install/dir>' --repo=https://repo.magento.com/
- composer update
- rm -rf pub/static/adminhtml/ pub/static/frontend/ pub/static/_cache/ pub/static/_requirejs/ var/generation/* var/di/* var/cache/*
- php bin/magento setup:upgrade, setup:di:compile, setup:static-content:deploy -f, setup:static-content:deploy fi_FI -f, indexer:reindex, cache:flush

### Expected result (*)

1. The category page should see the product images of what is set for products. **This is now only in the store (id_2).**

![image2](https://user-images.githubusercontent.com/26794034/50730272-0fb4ac00-1152-11e9-8d96-32c682524065.JPG)

### Actual result (*)

1. The category page is only Magento 2 default product image for all products. No anything real product images what is added to products.  **Store (id_1)**

![image](https://user-images.githubusercontent.com/26794034/50730233-5229b900-1151-11e9-9db2-ca08cb6a1987.JPG)

Also tested and doesn't work:
- Restore old backup and upgrade again Magento 2.2.7 to 2.3.0
- disable all custom modules and theme
- enable magento 2 luma theme
- Command: bin/magento catalog:images:resize
- Pub and media folder added permission 777

I do not find anything solution for this so it is magento 2.3.0 multi-store issue? Because everything works well with magento 2.2.7.

**Comment by magento-engcom-team** [comment]
Hi @Userr017. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Userr017 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Userr017** [comment]
If need more details. Please give me someone magento 2 developer your email address so i send for you my website link. Thanks

**Comment by uurtsaikh0904** [comment]
Hello there,

I am having a similar issue. 
We updated the Magento 2.2.2 to Magento 2.3.0.

The issue we are having is that the old products, which were created when we were using Magento 2.2.2, are having a problem when we update them. 

The new products are fine, but the old products have a problem.

Here is additional information from my client: 

I've added photos to a number of products lately, and with most of them, while I've been able to change the product page, in the website search the thumbnail image has not changed, and in the backend, the thumbnails are either blank or are still the previous image, if that image has not been deleted.

Thanks,
Tom

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Userr017 thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/19710

**Comment by Userr017** [comment]
This is sure same issue? https://github.com/magento/magento2/issues/19710

Because when i change product name example. Bag3 to Bag4 and url key baq4 for Store (id_1) and keep store (id_2) default product name Bag3 and url key bag3. It display in Store (id_1) real product images what is added to product. 

Why this don't display real product images for Store (id_1) if update magento 2.2.7 to 2.3.0? Anything solution fix this?
