### ISSUE TITLE
Several 404 errors with requirejs after fresh installation of Magento 2.1.16

### ISSUE THREAD

**Issue by csmith-fm** [magento/magento2#20102]
### Preconditions (*)

1. Magento version 2.1.16
2. Windows 7 Professional SP1
3. XAMPP v3.2.2 (Win32) in Administrator mode, running:
  **a.** Apache 2.4.25
  **b.** PHP 7.0.18
  **c.** MariaDB 10.1.10

### Steps to reproduce (*)

1. Download version 2.1.16 from https://magento.com/tech-resources/download (can be with or without sample data)
2. Extract files to subdirectory in C:\xampp\htdocs
3. Set up hosts information in httpd-vhosts.conf; example:
```
<VirtualHost *:80>
    DocumentRoot "/xampp/htdocs/magento"
    ServerName local.magento.com
	<Directory /xampp/htdocs/magento>
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```
4. Add entry into hosts file, located at C:\Windows\System32\drivers\etc:
127.0.0.1 local.magento.com
5. Create new database
6. Restart server
7. Visit local.magento.com and follow the instructions to install Magento - change the Admin Address to "admin"
8. Change the Store Default Currency to British Pound (GBP)
9. After successful installation, visit either the frontend or backend of the website

### Expected result (*)

1. The frontend and backend of the website should load successfully
2. No errors should appear in the browser's console log

### Actual result (*)

1. The frontend of the website shows errors involving requirejs and the inability to load additional scripts; the styling is also not loading properly, and no content is loaded except for the header and footer
    1. Go to the browser's developer tools and go to the Network tab; the requirejs script is constantly aborting.
![frontend error](https://user-images.githubusercontent.com/46444343/50766818-8ea10600-1272-11e9-9e0d-580fe3ad93dd.png)
    1. After running setup:static-content-deploy, the requirejs loads but there is a lot of other scripts that are producing a 404 error.
![frontend error after static content deploy](https://user-images.githubusercontent.com/46444343/50766830-9e204f00-1272-11e9-92b7-f6311bc07b33.png)
    1. This suggests that it's also failing to load dynamic content that would normally appear.

2. The backend shows a grey background, but no login form.
    1. No 404 errors are produced, but instead in the console, there's a error that reads "Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", and produced five times.
![backend error](https://user-images.githubusercontent.com/46444343/50766846-aa0c1100-1272-11e9-8c43-d24967362964.png)
    1. After further analysis, it appears that the scripts are being redirected back to the Magento admin, which means that they are rendering HTML instead, hence why the messages are appearing.

If you require any additional information, then please ask away!

**Comment by magento-engcom-team** [comment]
Hi @csmith-fm. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@csmith-fm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by csmith-fm** [comment]
@magento-engcom-team give me 2.1.16 instance

**Comment by magento-engcom-team** [comment]
Hi @csmith-fm. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by orlangur** [comment]
@csmith-fm, please note

> where $VERSION is version tags (starting from 2.2.0+) or develop branches

Also, Windows is not supported and thus facing some troubles is quite expectable.

**Comment by csmith-fm** [comment]
Hi @orlangur ,

Thank you for your response. I have added the required comment, but I get a message indicating that only versions 2.2+ can be deployed.

As for Windows, I am aware that you support Linux x86-64, however with our development it creates a LAMP-like environment, and so it should work fine, as long as you are running in Administrator mode, which is required to successfully create symlinks. I have used previous versions of Magento 2 with great success on a Windows machine running Apache (albeit a bit slow). Please bear in mind that this is currently a development environment, and once migrating onto a production server, it will be using Linux running CentOS.

What I will do in the mean time is move onto a Linux development server running on Ubuntu, and witness if we're getting similar errors.

**Comment by csmith-fm** [comment]
Okay so I've installed 2.1.16 directly only a system running Ubuntu, and it works first time. Furthermore I've found a zipped up package with version 2.1.12, and after extracting the contents and installing it on my Windows environment, it works fine on there (although I did have to do a setup:static-content:deploy).

Therefore somewhere in the code, there has been some actioned amends between those two versions that would have ceased optimal functionality on a Windows environment. Is anyone aware of any potential changes made that could have caused this?

**Comment by orlangur** [comment]
@csmith-fm problems with `2.1.x` versions are not tracked & investigated here.

Windows environment may cause troubles as it is not verified by CI builds, you can check https://github.com/magento/magento2/issues/19471#issuecomment-443195351 for an easiest solution to deploy under Windows 10.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @csmith-fm  i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.
