### ISSUE TITLE
Cannot update telephone / fax numbers 

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#20100]
### Summary of Issue

Cannot update telephone / fax numbers.
Magento\Framework\Model\ResourceModel\Db\VersionControl\Snapshot.php checks each fields data update when save method is called from Model class, but non-strict value comparison sometimes causes unexpected result. For example:

- Old value: 1234567890
- New value: 01234567890

PHP automatically converts new value into integer and both values are recognized as same value.
### Environment
1. Ubuntu Linux 18.04 / 16.04 LTS
2. Apache 2.4.x
3. PHP7.1.x / 7.2.x
4. MySQL 5.7.x

### Preconditions (*)

1. Install Magento 2.2.x or 2.3.x.
2. Create customer account.
3. Create customer address data with telephone / fax number like '1234567890'.

### Steps to reproduce (*)

1. Login as registered customer that created in preconditions step.
2. Choose existing address data from address book that created in preconditions step.
3. Set new telephone / fax number like '01234567890'.
4. Save address.

### Expected result (*)

1. Telephone / fax number data are correctly updated into new value.

### Actual result (*)

1. Values are not updated.

**Comment by magento-engcom-team** [comment]
Hi @HirokazuNishi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@HirokazuNishi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by HirokazuNishi** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @HirokazuNishi. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
This issue is similar to #17452

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97468`, `MAGETWO-97469` were created

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-20100-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20100-2-3-develop.instances.magento-community.engineering/admin](https://i-20100-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by oalvarezI4** [comment]
I am working on this issue.

**Comment by andrewbess** [comment]
Hello @shikhamis11 
Are you sure that this bug is reproduced?
I cannot reproduce it.
Please take a look my [gif](https://monosnap.com/file/1onWeCMUEGftkwO7QM513uVTpOPSc8).
Please clarify steps for reproduce and reopen issue if it still reproduces.
