### ISSUE TITLE
Email Template Information Insert Variable popup blank 

### ISSUE THREAD

**Issue by priti2jcommerce** [magento/magento2#20111]
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. Go to admin>>MARKETING>>Email Templates>> edit the template
2.

### Expected result (*)

1. 
![image](https://user-images.githubusercontent.com/18118695/50820984-0c890e00-1354-11e9-8a96-98ae91203054.png)

2.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/18118695/50820915-e5cad780-1353-11e9-907a-7d78f9ecb354.png)

2.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@priti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by priti2jcommerce** [comment]
Hi
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @priti2jcommerce thank you for you report, i'm not able to reproduce following steps you described, this may be related to your custom modules 
![selection_256](https://user-images.githubusercontent.com/40756439/50821211-50b9e580-1337-11e9-8037-419a74f3f5ec.png)

**Comment by priti2jcommerce** [comment]
Hi @engcom-backlog-nazar ,

this issue not with creating new one, this is with editing the existing email template.
I have created one template and try to edit but the pop-up showing blank

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97482` were created

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20111-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20111-2-2-develop.instances.magento-community.engineering/admin](https://i-20111-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20111-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20111-2-3-develop.instances.magento-community.engineering/admin](https://i-20111-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hapablap** [comment]
To fix this issue by your own, until an update is provided:
The source of the bug is in vendor/magento/module-variable/view/adminhtml/web/variables.js, line 53. The iteration on variables fails. You only need to change this single line from
`variables.each(function (variableGroup) {`
to
`jQuery.each(variables, function (index, variableGroup) {`

Of course, you should not edit files in the vendor folder. So you need to override it. To learn how to override a core js file, please refer to https://magento.stackexchange.com/a/60667

**Comment by Zyles** [comment]
> variableGroup

Not found in `vendor/magento/module-variable/view/adminhtml/web/variables.js`

Correct file is `vendor/magento/module-email/view/adminhtml/web/js/variables.js`

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#22469 by @Bartlomiejsz in 2.3-develop branch
Related commit(s):
 - [7d584acbd86a034402047431479aee22759def88](https://github.com/magento/magento2/commit/7d584acbd86a034402047431479aee22759def88)
 - [4f6a15a487656892490e3042ae7ffe395988b14a](https://github.com/magento/magento2/commit/4f6a15a487656892490e3042ae7ffe395988b14a)
 - [65a61a5c8560f800824f2c18e0b53dad1dd49675](https://github.com/magento/magento2/commit/65a61a5c8560f800824f2c18e0b53dad1dd49675)

The fix will be available with the upcoming 2.3.2 release.
