### ISSUE TITLE
Magento Upgrade from 2.2.6 to 2.3.0 Failed

### ISSUE THREAD

**Issue by rosariomarsala** [magento/magento2#20116]
Preconditions

1. Magento Currently Version 2.2.6
2. Magento Start Version 2.2.4 - data migrated with migration tool from magento 1.9.3.8
3. PHP Version 7.1.5
4. MySQL Version 10.1.23-MariaDB
5. Memory limit 1024M
6. Max execution time 1800
7. My composer.json file before upgrade:

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.2.4",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.2.6",
        "composer/composer": "@alpha",
        "magento/data-migration-tool": "2.2.4",
        "phoenix/module-cashondelivery": "1.0.2",
        "magento2translations/language_it_it": "dev-master",
        "magento2translations/language_fr_fr": "dev-master",
        "msp/security-suite": "^2.1",
        "feedaty/module-badge2": "^2.2",
        "multisafepay/magento2msp": "^1.6"
    },
    "require-dev": {
        "phpunit/phpunit": "~6.2.0",
        "squizlabs/php_codesniffer": "3.2.2",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.5.2",
        "friendsofphp/php-cs-fixer": "~2.2.1",
        "lusitanian/oauth": "~0.8.10",
        "sebastian/phpcpd": "2.0.4"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "stable",
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "magento": {
            "type": "composer",
            "url": "https://repo.magento.com"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}

Steps to reproduce

1. php bin/magento maintenance:enable
2. php /usr/local/bin/mycomposer.phar require magento/product-community-edition=2.3.0 --no-update
3. php /usr/local/bin/mycomposer.phar require --dev phpunit/phpunit:~6.2.0 friendsofphp/php-cs-fixer:~2.10.1 lusitanian/oauth:~0.8.10 pdepend/pdepend:2.5.2 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:3.2.2 --no-update
4. php /usr/local/bin/mycomposer.phar remove --dev sjparkinson/static-review fabpot/php-cs-fixer --no-update
5. update the composer.json --> add line "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/" as in documentation
6. php /usr/local/bin/mycomposer.phar update

Expected result

Update from Magento version 2.2.6 to 2.3.0

Actual result

Update Failed

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: don't install magento/product-community-edition 2.3.0
- magento/data-migration-tool 2.2.6 requires magento/framework ~101.0.0 -> satisfiable by magento/framework[101.0.7, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.4, 101.0.5, 101.0.6].
- magento/data-migration-tool 2.2.6 requires magento/framework ~101.0.0 -> satisfiable by magento/framework[101.0.7, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.4, 101.0.5, 101.0.6].
- magento/data-migration-tool 2.2.6 requires magento/framework ~101.0.0 -> satisfiable by magento/framework[101.0.7, 101.0.0, 101.0.1, 101.0.2, 101.0.3, 101.0.4, 101.0.5, 101.0.6].
- magento/framework 101.0.1 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
- magento/framework 101.0.2 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
- magento/framework 101.0.3 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
- magento/framework 101.0.1 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
- magento/framework 101.0.2 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
- magento/framework 101.0.3 requires colinmollenhour/php-redis-session-abstract 1.3.4 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.4].
- magento/framework 101.0.0 requires colinmollenhour/php-redis-session-abstract ~1.2.2 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.2.2].
- magento/framework 101.0.0 requires colinmollenhour/php-redis-session-abstract ~1.2.2 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.2.2].
- magento/framework 101.0.7 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.4 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.5 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.6 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.7 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.4 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.5 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.6 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- magento/framework 101.0.7 requires magento/zendframework1 ~1.13.0 -> satisfiable by magento/zendframework1[1.13.1, 1.13.0].
- Can only install one of: colinmollenhour/php-redis-session-abstract[v1.4.0, v1.3.4].
- Can only install one of: colinmollenhour/php-redis-session-abstract[v1.4.0, v1.3.4].
- Can only install one of: colinmollenhour/php-redis-session-abstract[v1.4.0, v1.2.2].
- Can only install one of: magento/zendframework1[1.14.1, 1.13.0].
- Can only install one of: magento/zendframework1[1.14.1, 1.13.1].
- Can only install one of: magento/zendframework1[1.14.1, 1.13.1].
- magento/product-community-edition 2.3.0 requires colinmollenhour/php-redis-session-abstract ~1.4.0 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.4.0].
- magento/product-community-edition 2.3.0 requires magento/zendframework1 ~1.14.1 -> satisfiable by magento/zendframework1[1.14.1].
- Installation request for magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0].
- Installation request for magento/data-migration-tool 2.2.6 -> satisfiable by magento/data-migration-tool[2.2.6].

**Comment by magento-engcom-team** [comment]
Hi @wwwmage. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@wwwmage do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @wwwmage thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/19446
