### ISSUE TITLE
Sort By label is hidden by Shop By Menu on listing page in iphone5 device

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#20124]
Sort By label is hidden by Shop By Menu on listing page in iphone5 device

### Preconditions (*)

1. Issue is present in version 2.2.5, 2.3
2 .On iphone5 device

### Steps to reproduce (*)

1. Go to listing page on iphone5 device you can see that Shop By menu is overlapping sort by option
2.  you can see that Shop By menu is overlapping Sort By Label 

### Expected result (*)

1. When we will go to listing page Shop By menu and sort by have to look like this 

![2019-01-08_18-52_tops](https://user-images.githubusercontent.com/18118638/50833881-9fd43a80-1378-11e9-8fba-4e5d681281b5.jpg)

### Actual result (*)

1 Sort By label is hidden by Shop By Menu on listing page

![2019-01-08_19-08_tops](https://user-images.githubusercontent.com/18118638/50833976-df028b80-1378-11e9-96d4-e88009f2364f.jpg)

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@irajneeshgupta Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97506`, `MAGETWO-97507` were created

**Comment by dipti2jcommerce** [comment]
I am working on this issue

**Comment by cedarvinda** [comment]
@magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda, here is your [Magento instance](https://i-20124-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20124-2-3-develop.instances.magento-community.engineering/admin](https://i-20124-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20135 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [11af87753f43c38d95c373a046ed9490cc2f88e3](https://github.com/magento/magento2/commit/11af87753f43c38d95c373a046ed9490cc2f88e3)
 - [42b81c0d97d5948fb7f0c45970fab33cf2f9af99](https://github.com/magento/magento2/commit/42b81c0d97d5948fb7f0c45970fab33cf2f9af99)

The fix will be available with the upcoming 2.3.3 release.
