### ISSUE TITLE
Design issue in product creation form

### ISSUE THREAD

**Issue by mohammadzakir** [magento/magento2#20125]
### Preconditions (*)

1. Magento 2.3.0 with sample data
2. Php Version 7.2

### Steps to reproduce (*)

1. Login to admin panel
2. On left navigation goto Stores-> Attributes-> Attribute Set
3. Create new attribute set on based on default attribute
4. Now Stores-> Attributes -> Product
5. Create an attribute of the text field
6. Now assign created attribute to previously created attribute set on step 3.
7. Now try to create a product with the above-created attribute set

### Expected result (*)

1. Product Creation form design should be correct.

### Actual result (*)

1. Product Creation form design is disturbed

![image](https://user-images.githubusercontent.com/43291220/50836283-db720300-137e-11e9-8bda-268fc8a053d6.png)

**Comment by magento-engcom-team** [comment]
Hi @mohammadzakir. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mohammadzakir do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97492` were created

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by cedarvinda** [comment]
I am working in this.

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh, here is your [Magento instance](https://i-20125-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20125-2-3-develop.instances.magento-community.engineering/admin](https://i-20125-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh, here is your [Magento instance](https://i-20125-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20125-2-3-develop.instances.magento-community.engineering/admin](https://i-20125-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Manwanigaurav** [comment]
I am working on this at #dmcdindia19”

**Comment by magento-engcom-team** [comment]
@Manwanigaurav thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by kandarp26** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kandarp26. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kandarp26, here is your [Magento instance](https://i-20125-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20125-2-3-develop.instances.magento-community.engineering/admin](https://i-20125-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ronn0** [comment]
@magento-engcom-team I am working in this.

**Comment by ronn0** [comment]
@magento-engcom-team  I am working in this.

**Comment by ronn0** [comment]
@magento I am working on it

**Comment by roerlemans** [comment]
@magento I am working on it

**Comment by roerlemans** [comment]
@magento-engcom-team can i please be added to the Magento organisation? It would be nice if i can assign Some issues to myself.

**Comment by roerlemans** [comment]
@magento-engcom-team how is this possible? Your bot is not working. I was working on this

**Comment by tymzap** [comment]
@magento I am working on it

**Comment by tymzap** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tymzap. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tymzap, here is your [Magento instance](https://i-20125-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20125-2-3-develop.instances.magento-community.engineering/admin](https://i-20125-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by alexey-rakitin** [comment]
@magento I am working on it

**Comment by alexey-rakitin** [comment]
Issue is not reproducible on 2.3-develop
Fixed & merged in: https://github.com/magento/magento2/commit/9097ecccbc95c1c15e385ece55fcb2bda62557a7
