### ISSUE TITLE
Cancel order increases stock although "Set Items' Status to be In Stock When Order is Cancelled" is set to No

### ISSUE THREAD

**Issue by denzyk** [magento/magento2#20121]
We've recently run into issue where stock quantity is restored (increased back by 1) after the order has been canceled although **Set Items' Status to be In Stock When Order is Cancelled** is set to **No**.

### Preconditions

1. Magento 2.2.6 Community
2. Reproduced on PHP 7.1.18 and 7.1.25
3. MariaDB 10.1.26 and 10.3.11
4. Go to Stores -> Configuration -> Catalog -> Inventory and make sure the following options are set as per below:
 * **Decrease Stock When Order is Placed** to **Yes**
 * **Set Items' Status to be In Stock When Order is Cancelled** to **No**
 * **Manage Stock** to **Yes**
 * **Automatically Return Credit Memo Item to Stock** to **No**
(see screenshot below)
![image](https://user-images.githubusercontent.com/12296157/50830354-3d674400-1350-11e9-9278-81b92aef7761.png)

### Steps to reproduce

1. Place an order with 1 item of product (i.e. qty = 1)
2. Cancel order

### Expected result

1. Product quantity in product catalog is decreased by 1 after order is created
2. Product quantity remains the same (i.e. does not increase) after order is canceled

### Actual result

1. Product quantity in product catalog is decreased by 1 after order is created
2. Product quantity is increased by 1 immediately after order is canceled

**Comment by magento-engcom-team** [comment]
Hi @denzyk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@denzyk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by denzyk** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @denzyk. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97493`, `MAGETWO-97494` were created

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @routbiplab. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @denzyk. Thank you for your report. 
The issue has been fixed in magento/magento2#20252 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [473f907264cbff215a645518dfc5cc75849119d1](https://github.com/magento/magento2/commit/473f907264cbff215a645518dfc5cc75849119d1)
 - [8d3fc5c138b4328baab27f44e6fd6d58b0149dca](https://github.com/magento/magento2/commit/8d3fc5c138b4328baab27f44e6fd6d58b0149dca)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @denzyk. Thank you for your report. 
The issue has been fixed in magento/magento2#20547 by @irajneeshgupta in 2.2-develop branch
Related commit(s):
 - [331b5c1456f901dffcb0fc92a86f650ea57b3783](https://github.com/magento/magento2/commit/331b5c1456f901dffcb0fc92a86f650ea57b3783)
 - [cc6b848d242d4458e2c270273cc36e55b822b4be](https://github.com/magento/magento2/commit/cc6b848d242d4458e2c270273cc36e55b822b4be)

The fix will be available with the upcoming 2.2.8 release.
