### ISSUE TITLE
2.3 : Payment gateway adapter : fetch_transaction_info vs fetch_transaction_information

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#20139]
Magento 2 offers an option to show a button `Get Payment Update` in the admin/order/view page. To be able to show this button you need to add the key `can_fetch_transaction_info` to your `config.xml`. When this button is clicked, a method is executed, but the key for this method is `fetch_transaction_information`.

See `Magento\Payment\Model\Method\Adapter`:

    /**
     * @inheritdoc
     */
    public function canFetchTransactionInfo()
    {
        return $this->canPerformCommand('fetch_transaction_info');
    }

    ...

    /**
     * @inheritdoc
     */
    public function fetchTransactionInfo(InfoInterface $payment, $transactionId)
    {
        return $this->executeCommand(
            'fetch_transaction_information',
            ['payment' => $payment, 'transactionId' => $transactionId]
        );
    }

The `executeCommand()`-method also includes the `canPerformCommand()`-method in it:

    /**
     * @inheritdoc
     */
    private function executeCommand($commandCode, array $arguments = [])
    {
        if (!$this->canPerformCommand($commandCode)) {
            return null;
        }

        ...

Se even if `canFetchTransactionInfo()` will return true, the `fetchTransactionInfo()` will always return `null` because of the 2 different keys. To get this working properly, you need to add 2 properties to your `config.xml`:

    <can_fetch_transaction_information>1</can_fetch_transaction_information>
    <can_fetch_transaction_info>1</can_fetch_transaction_info>

Which is weird to say the least.

### Preconditions

1. Magento 2.3-develop (discovered this issue in Magento 2.2.6)

### Steps to reproduce

1. Configure a payment method to be able to have the 'Get Payment Update'-button (`can_fetch_transaction_info`).
2. Configure the proper command in your `di.xml` / commandPool:

    <item name="fetch_transaction_information" xsi:type="string">Vendor\Module\Gateway\Command\FetchTransactionInformation</item>

### Expected result

The command should be executed when the button is clicked.

### Actual result

The command is not executed and instead the message _"There is no update for the transaction."_ is shown.

---

The main question here is what the name of the property should be. `fetch_transaction_info` or `fetch_transaction_information`.

- If you opt to only use `fetch_transaction_info` the configuration will still be ok (and the button is shown), but the item in the commandPool is no longer matching.
- If you opt to only use `fetch_transaction_information` the configuration is no longer ok, but the commandPool is.

However, since the Adapter and it's interface state that the method should be called `fetchTransactionInfo()`, the key `fetch_transaction_info` would make the most sense.

Ditching `fetch_transaction_information` might however be a backward-breaking change for some payment methods (which can be easily fixed by editing the commandPool in the `di.xml`).

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kanduvisla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97544`, `MAGETWO-97545` were created

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24347` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by cjnewbs** [comment]
This bug is still present in 2.4.4 😩 

@magento-engcom-team are you able to shed more light on what was fixed in MC-24347?
