### ISSUE TITLE
Multi website using store code. Url without any store code should redirect to default store view

### ISSUE THREAD

**Issue by raulsinapsis** [magento/magento2#20147]
### Preconditions (*)

1. Magento CE 2.2.5 (I believe it should happen in any previous version, not tested in 2.3)
2. Multi website, using store codes for (assumed) all store views

### Steps to reproduce (*)

1. Navigate to any url without any store code, for instance: mydomain.com/abc

### Expected result (*)

1. Application should redirect to url with store code of default store view (as it happens in Magento1). For instance, mydomain.com/en/abc

### Actual result (*)

1. Url loads ok, leading to potential SEO problems due to duplicated content

**Comment by magento-engcom-team** [comment]
Hi @raulvian. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@raulvian do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@irajneeshgupta Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97533` were created

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @raulvian thank you for you report, this is non-issue, for that behavior please configure your store to use different base url .
https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_nginx.html

**Comment by raulsinapsis** [comment]
Sorry @engcom-backlog-nazar do you mean we should force the default store code appended to default store base url? Is it?

Providing just a solution for Nginx (and not the equivalent for Apache) doesn't seem enough for me, sorry. Apart from that, there are some **assumptions** in that devdoc which doesn't fit this case, for instance

> You have two websites other than the default:
> 
>     french.mysite.mg with website code french and store view code fr
>     german.mysite.mg with website code german and store view code de
>     mysite.mg is the default website and default store view

This is not the case, as subdomains weren't mentioned in **Preconditions**, precisely because we use same domain (without any subdomain) for all store views in the project

**Comment by ghost** [comment]
@raulvian 

> Url without any store code should redirect to default store view

On 2.3 instance  i'm have the following result.

**Comment by raulsinapsis** [comment]
Ok @engcom-backlog-nazar, remove **Reproduced on 2.3.x** tag then, if that's the case... but 2.2.x problem is still there

**Comment by ghost** [comment]
@raulvian i'm will recheck on 2.2-develop

**Comment by raulsinapsis** [comment]
Thanks @engcom-backlog-nazar

**Comment by raulsinapsis** [comment]
@engcom-backlog-nazar @irajneeshgupta @magento-engcom-team
By the way, our fix for this, just to provide a workaround solution for any other user with same problem (please, don't Close the ticket if it's not confirmed to be fixed in previous versions)

Observe **controller_action_predispatch** event, and create observer class 

    protected $storeManager;
    protected $url;

    public function __construct(
        \Magento\Store\Model\StoreManagerInterface $storeManager,
        \Magento\Framework\UrlInterface $url
    ) {
           $this->storeManager = $storeManager;
           $this->url = $url;
    }

    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        // get current url
        $url = parse_url($this->url->getCurrentUrl());
        $path = ltrim($url['path'], '/');
        $urlParts = explode('/', $path);
        // if first part is not any frontend store code
        if (! in_array($urlParts[0], array_keys($this->storeManager->getStores(false, true)))) {
            // inject default store code & redirect
            header("Location: " . $this->storeManager->getDefaultStoreView()->getBaseUrl() . $path, 301);
            exit();
        }
    }

We need to check every single request, as 404 is not reached for existing urls... so the fix is totally obstrusive :S

**Comment by krisdante** [comment]
Why this ticket is closed? 
There is still no redirection. The default shop is loaded, but the URL stays old.

**Comment by cptX** [comment]
Please reopen! This is very important issue!

**Comment by cptX** [comment]
@raulsinapsis have you found a better solution? I'm thinking to implement the solution in nginx redirecting the non prefix url to the language prefix url. What is your opinion. I tried to do so but I have some difficulty. If you have a solution in nginx please tell.

**Comment by cptX** [comment]
Hi @irajneeshgupta can you please reopen this issue? I don't understand why it was closed in the first place!

**Comment by raulsinapsis** [comment]
> @raulsinapsis have you found a better solution? I'm thinking to implement the solution in nginx redirecting the non prefix url to the language prefix url. What is your opinion. I tried to do so but I have some difficulty. If you have a solution in nginx please tell. I'm really surprised how people treated this major issue as such unimportant. I even created a thread in magento forums and the answers I got were completely irrelevant!!

Check this https://magento.stackexchange.com/a/223513/3566

**Comment by cptX** [comment]
Hi @raulsinapsis,
I had seen this already but it's not working. Probably there is some syntax mistake or some characters are wrongly represented.

Anyway thanks!
