### ISSUE TITLE
Problems with composer path repositories in >= 2.2.7

### ISSUE THREAD

**Issue by renttek** [magento/magento2#20145]
### Summary
Can't use composer path-repositories outside of magento root (with symlinks) in Magento >= 2.2.7

Prior to 2.2.7 it was possible to use composer path-repositories which are outside of the magento root and let composer symlink them into vendor. This made module development very easy.

(There is a small problem with templates if the path resolves to something outside of the Magento root, but this is easily fixable by replacing "Magento\Framework\View\Element\Template\File\Validator" via di.xml/preference. I built an AllowSymlink-Module and put it in the "require-dev" section of my projects composer.json)

Since 2.2.7 there is a new \Magento\Framework\Filesystem\Directory\PathValidator which checks if a given template path resolves to something the magento 2 root and if it does not, the validator throws an ValidatorException

See: https://github.com/magento/magento2/blob/2.2.7/lib/internal/Magento/Framework/Filesystem/Directory/PathValidator.php#L58-L67

The problem here is, that the new validator is instantiated by a "new PathValidator()" and cannot be "replaced" by di.xml/preference.

See: https://github.com/magento/magento2/blob/2.2.7/lib/internal/Magento/Framework/Filesystem/Directory/WriteFactory.php#L49

#### Steps to reproduce

Given the following directory structure:

```
<project-root>
├── modules (<modules root>)
└── src (<magento root>)
    └── composer.json
```

If you use a composer path-style repository in "src/composer.json" like this:

```js
{
  // ...
  "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        {
            "type": "path",
            "url": "../modules/*"
        }
    ],
   // ...
}
```

You could easily add a module under "modules/" likes this:

##### 1. Add Module to "modules/<path>"

Structure:
```
<project-root>
├── modules (<modules root>)
│   └── my-module 
│       ├── composer.json
│       └── ...
└── src (<magento root>)
    ├── composer.json
    └── ...
```
##### 2. create composer json for module

modules/my-module/composer.json:
```json
{
  "name": "vendor/my-module",
  "license": "proprietary",
  "version": "0.0.1",
  "autoload": {
    "files": ["registration.php"],
    "psr-4": { "Vendor\\Module\\": "src"}
  }
}
```

##### 3. Add module to Magento

src/composer.json:
```js
{
  // ...
  "require": {
            // ...
            "vendor/my-module": "0.0.1"
    },
   // ...
}
```

##### 4. Run composer install

"composer install" will find the module and symlink it into vendor (symlink is the default behaviour for path repositories):

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing vendor/my-module (0.0.1): Symlinking from ../modules/my-module
Generating autoload files

```

##### 5. Deployments & Symlinks

Currently my deployment includes building an artifact with `tar` including the `dereference`-flag (`-h` or `--dereference`), which resolves all the symlinks and archives them as if they were real paths.

----

With this it possible to develop new modules es seperate packages without running "composer install/update" after every change or developing in app/code and extracting after the module is finished.

#### Example Code

I prepared an example Magento 2 project with the described setup as example:

https://github.com/renttek/magento2-composer-path-repository

### Proposed solution

I don't really have a solution for this at hand.
One idea could be to allow symlinks in development (developer-mode), but I'm open for other solutions.

**Comment by magento-engcom-team** [comment]
Hi @renttek. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@renttek do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ulftietze** [comment]
Vote +1 for this issue :+1:

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment]
@renttek 
> The problem here is, that the new validator is instantiated by a "new PathValidator()" and cannot be "replaced" by di.xml/preference.

Can we update and add the dependencies via construct in the class `Magento\Framework\Filesystem\Directory\WriteFactory` ?

**Comment by davidverholen** [comment]
@renttek the Problem seems to be that the object manager is not initialized the first time this object is used and so it cannot rely on di.
I just tried to inject a factory for the validator interface which fails with that exact error "ObjectManager isn't initialized" 
also for that reason it's instantiated directly with new in several places meaning the di config would have no effect there

a possible solution might be to introduce a new env config to explicitly allow symlinks outside of magento root dir, or maybe even an array containing paths to trusted directories outside of the root

**Comment by milindsingh** [comment]
> a possible solution might be to introduce a new env config to explicitly allow symlinks outside of magento root dir, or maybe even an array containing paths to trusted directories outside of the root

@davidverholen would this be a new feature then?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @renttek Same as https://github.com/magento/magento2/issues/13375#issuecomment-431146467 - paths outside of Magento base path should not be accessible for security reasons.

**Comment by ghost** [comment]
@renttek https://github.com/magento/magento2/issues/5326, https://github.com/magento/magento2/issues/13375, https://github.com/magento/magento2/pull/15252

**Comment by renttek** [comment]
Ehm yeah, but they are only outside of magento when developing. Every symlink gets dereferenced/resolved on deployment

**Comment by renttek** [comment]
@davidverholen  I like the idea of having a dev config which allows symlinks.

@engcom-backlog-nazar using composer path repositories is used by many devs and i think it's really sad that my only options are not upgrading to >2.2.6 or using composer patches to nuke the validation in development.
