### ISSUE TITLE
Can't refund to store credit an order paid by store credit

### ISSUE THREAD

**Issue by QuentinFarizon** [magento/magento2#20149]
### Preconditions
Magento 2.1.16

### Steps to reproduce
- Add 10$ store credit to a customer
- WIth this customer, buy a 10$ item, with 0$ shipping
- Use the 10$ store credit, so nothing to pay, free payment is selected
- Complete order
- In the back-office, create a credit memo for this order, select all products and shipping fees
- Tick "refund to store credit" (10$)
- Submit credit memo

### Expected result
Credit memo created successfully
Client has 10$ store credit

### Actual result
Error message : "The credit memo's total must be positive."

![image](https://user-images.githubusercontent.com/33634848/50917776-bb097d80-143e-11e9-812c-475028fcd096.png)

**Comment by magento-engcom-team** [comment]
Hi @QuentinFarizonAfrimarket. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@QuentinFarizonAfrimarket do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team magento-engcom-team give me 2.3.0 instance

**Comment by aditisinghcedcoss** [comment]
@QuentinFarizonAfrimarket
Can you please confirm your magento distribution is EE or CE?

**Comment by irajneeshgupta** [comment]
This issue is not reproducible and close the issue and stop verification process here!

**Comment by QuentinFarizon** [comment]
@magento-engcom-team magento-engcom-team give me 2.2-develop instance

**Comment by QuentinFarizon** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @QuentinFarizonAfrimarket. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @QuentinFarizonAfrimarket, here is your [Magento instance](https://i-20149-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20149-2-2-develop.instances.magento-community.engineering/admin](https://i-20149-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Enigmativity** [comment]
This is definitely still and issue.

Just create an order in the back-end and give yourself a 100% discount on the item. When checking out use a free shipping option. The cart total is $0.00. You can't then cancel or create a credit memo for the order.
