### ISSUE TITLE
Multi website / store. Admin created customers are redirected to wrong store after password create & login

### ISSUE THREAD

**Issue by raulsinapsis** [magento/magento2#20148]
### Preconditions (*)

1. Magento CE 2.2.5 (I believe it should happen in any previous version, not tested in 2.3)
2. Multi website / store, using store codes for all store views (not sure if using store codes is relevant)
3. This report affects only the explained flow in "Steps to reproduce", regular login works as expected

### Steps to reproduce (*)

1. Create new customer in admin with associated website / store different than default store
2. Welcome mail with a link to "create password" feature is then sent to new customer
3. Create password works fine, and the customer is redirected to associated store login page

### Expected result (*)

1. After login, customer should be redirected to homepage (or dashboard, if configured... or any other page) of associated store

### Actual result (*)

1. After login, customer is redirected to homepage of default store

**Comment by magento-engcom-team** [comment]
Hi @raulvian. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@raulvian do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20148-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20148-2-2-develop.instances.magento-community.engineering/admin](https://i-20148-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@raulvian I checked this at Magento 2.2.5 this issue is  reproduceable there. after login customer is redirected to default store store view

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97541` were created

**Comment by raulsinapsis** [comment]
I have found **Expected / Actual result** messages were crossed. My mistake there... I have edited it. Although I think the report was understood, give it a look @shikhamis11 @magento-engcom-team

Just to clarify... what should happen is customer should be redirected to homepage (or any other page, such as dashboard) of associated store, not default one

**Comment by shikhamis11** [comment]
@raulvian yes I created a customer in store 2 that was not default store but after login it is redirected to default one . It should redirect to the associated store of customer

**Comment by raulsinapsis** [comment]
@shikhamis11 I have tried upgrading from 2.2.5 to 2.2.6 and it seems it is working properly there. However, not sure which concrete code change could solve the issue in 2.2.5

**Comment by shikhamis11** [comment]
@raulvian let me check I will update you

**Comment by raulsinapsis** [comment]
No, my mistake @shikhamis11 
If you follow strictly the steps to reproduce problem still persists in 2.2.6

**Comment by raulsinapsis** [comment]
@magento-engcom-team give me 2.2.7 instance

I want to check if upgrading to 2.2.7 will fix the issue

**Comment by magento-engcom-team** [comment]
Hi @raulvian. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @raulvian, here is your [Magento instance](https://i-20148-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-20148-2-2-7.instances.magento-community.engineering/admin](https://i-20148-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by raulsinapsis** [comment]
It seems cron / email sending is not enabled in this environment, so there's no way to validate it

**Comment by shikhamis11** [comment]
@raulvian you can check and work on this issue at your local environment and can create pull request if you find it's solution

**Comment by raulsinapsis** [comment]
I have been debugging this in local environment. I supposed some piece of code was setting the wrong url to redirect after the whole process, but it doesn't seem so

The flow in this case ( CreatePassword -> ResetPasswordPost -> LoginPost ) ends up in **Magento\Customer\Model\Account::getRedirect()** 

    public function getRedirect()
    {
        $this->updateLastCustomerId();
        $this->prepareRedirectUrl();

        /** @var ResultRedirect|ResultForward $result */
        if ($this->session->getBeforeRequestParams()) {
            $result = $this->resultFactory->create(ResultFactory::TYPE_FORWARD);
            $result->setParams($this->session->getBeforeRequestParams())
                ->setModule($this->session->getBeforeModuleName())
                ->setController($this->session->getBeforeControllerName())
                ->forward($this->session->getBeforeAction());
        } else {
            $result = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
            $result->setUrl($this->session->getBeforeAuthUrl(true));
        }
        return $result;
    }

For this concrete flow, and after some debugging, there are no BeforeRequestParams in session, so this should end redirecting to **$this->session->getBeforeAuthUrl(true)** 

I have printed that & it has the right url: <base_url_of_right_store_including_store_code>customer/account

Browser loads the url & then redirect 302 to <base_url> (without any store code, which I think could be a relevant detail), which seem to be the problem. Why that redirect?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by raulsinapsis** [comment]
Any updates with this?

**Comment by raulsinapsis** [comment]
As a workaround for this, we are rewriting **Magento\Customer\Model\AccountManagement** `resetPassword()`, setting customer as logged in at the end of that function 

    class AccountManagement extends \Magento\Customer\Model\AccountManagement
    {

        /** Need to copy here, cause of private scope */
        private function validateResetPasswordToken($customerId, $resetPasswordLinkToken)
        {

            $customerRegistry = ObjectManager::getInstance()->get(\Magento\Customer\Model\CustomerRegistry::class);
            if (empty($customerId) || $customerId < 0) {
                throw new InputException(
                    __(
                        'Invalid value of "%value" provided for the %fieldName field.',
                        ['value' => $customerId, 'fieldName' => 'customerId']
                    )
                );
            }
            if (!is_string($resetPasswordLinkToken) || empty($resetPasswordLinkToken)) {
                $params = ['fieldName' => 'resetPasswordLinkToken'];
                throw new InputException(__('%fieldName is a required field.', $params));
            }

            $customerSecureData = $customerRegistry->retrieveSecureData($customerId);
            $rpToken = $customerSecureData->getRpToken();
            $rpTokenCreatedAt = $customerSecureData->getRpTokenCreatedAt();

            if (!Security::compareStrings($rpToken, $resetPasswordLinkToken)) {
                throw new InputMismatchException(__('Reset password token mismatch.'));
            } elseif ($this->isResetPasswordLinkTokenExpired($rpToken, $rpTokenCreatedAt)) {
                throw new ExpiredException(__('Reset password token expired.'));
            }

            return true;
        }

        /** Do NOT destroy session after password reset */
        public function resetPassword($email, $resetToken, $newPassword)
        {
            $customerRepository = ObjectManager::getInstance()->get(\Magento\Customer\Api\CustomerRepositoryInterface::class);
            $customerRegistry = ObjectManager::getInstance()->get(\Magento\Customer\Model\CustomerRegistry::class);
            $customerSession = ObjectManager::getInstance()->get(\Magento\Customer\Model\Session::class);

            $customer = $customerRepository->get($email);
            //Validate Token and new password strength
            $this->validateResetPasswordToken($customer->getId(), $resetToken);
            $this->checkPasswordStrength($newPassword);
            //Update secure data
            $customerSecure = $customerRegistry->retrieveSecureData($customer->getId());
            $customerSecure->setRpToken(null);
            $customerSecure->setRpTokenCreatedAt(null);
            $customerSecure->setPasswordHash($this->createPasswordHash($newPassword));
            //$this->sessionManager->destroy();
            //$this->destroyCustomerSessions($customer->getId());
            $customerRepository->save($customer);

            // login customer
            $customerSession->setCustomerDataAsLoggedIn($customer);
            $customerSession->regenerateId();

            return true;
        }
    }

**Comment by raulsinapsis** [comment]
Any updates with this?

**Comment by engcom-Charlie** [comment]
Hi @raulsinapsis,

Thank you for your contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

Could You take a look?
