### ISSUE TITLE
My account page "Recently Ordered" check box misaligned on tab portrait view 

### ISSUE THREAD

**Issue by ajay2jcommerce** [magento/magento2#20143]
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. placed order with login customer on my account page in sidebar check resend order product.
2.

### Expected result (*)

1.
![2019-01-09_18-23_my account](https://user-images.githubusercontent.com/18118570/50901213-80531580-143d-11e9-8c18-37e308ed4a7b.jpg)

2.

### Actual result (*)

1. 
![2019-01-09_18-13_my account](https://user-images.githubusercontent.com/18118570/50901232-8e089b00-143d-11e9-96e9-e8e420f2a55a.jpg)

2.

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ajay2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20143-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20143-2-3-develop.instances.magento-community.engineering/admin](https://i-20143-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
this issue does not exist in 2.3 develop branch Please check this image
![screenshot_2019-01-09_18-53-00](https://user-images.githubusercontent.com/25526037/50902025-d0cb7280-143f-11e9-898a-4341ae6559cf.png)

**Comment by ajay2jcommerce** [comment]
I have check this is on tab portrait view.

**Comment by ajay2jcommerce** [comment]
hi @shikhamis11 

I have checked with the existing product name as mentioned in the screen

**Comment by shikhamis11** [comment]
@ajay2jcommerce let me check this again I am reopening this issue

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97524` were created

**Comment by ajay2jcommerce** [comment]
I am working on it.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20155 by @ajay2jcommerce in 2.3-develop branch
Related commit(s):
 - [5515f7e39c9f306c692064c95e8b6e69e0be9631](https://github.com/magento/magento2/commit/5515f7e39c9f306c692064c95e8b6e69e0be9631)
 - [15ddead5dde8f362c6cad9d245dc828e0c61c077](https://github.com/magento/magento2/commit/15ddead5dde8f362c6cad9d245dc828e0c61c077)
 - [12c7e05b694feb9be12d1f71e1b96322f82eb728](https://github.com/magento/magento2/commit/12c7e05b694feb9be12d1f71e1b96322f82eb728)
 - [57df489cb5f7ca7e714bf48a5b9ad7c52fbbb8fd](https://github.com/magento/magento2/commit/57df489cb5f7ca7e714bf48a5b9ad7c52fbbb8fd)

The fix will be available with the upcoming 2.3.1 release.
