### ISSUE TITLE
Web Setup Wizard redirects to 404 Not Found after upgrading from 2.2.5 to 2.2.6

### ISSUE THREAD

**Issue by jos-zz** [magento/magento2#20151]
The **Web Setup Wizard redirects to 404 Not Found** (on storefront) after upgrading from Magento CE 2.2.5 to CE 2.2.6. The upgrade was performed using the Web Setup Wizard on CE 2.2.5.

### Preconditions (*)
1. **Magento CE 2.2.6** (freshly upgraded from CE 2.2.5)
2. CentOS Linux release 7.5.1804 (Core)
3. Apache/2.4.33 64-bit (built: Apr 23 2018 21:10:29) 
4. The apache server configuration points to the root directory (**/store/**) and NOT /store/pub/

### Steps to reproduce (*)
1. Setup Magento 2.2.5 (everything is working)
2. Upgrade to Magento 2.2.6 with Web Setup Wizard
3. Go to admin area, from the menu, click on the link in System > Web Setup Wizard

### Expected result (*)
It's expected that the web setup wizard screen will show as it's supposed to.

### Actual result (*)
What happens is that the admin area runs the url and redirects and to the storefront with the screen "Whoops, our bad...".  
![image](https://user-images.githubusercontent.com/319433/50921070-c0bb8f00-144f-11e9-8720-85ef2122172d.png)

**Comment by magento-engcom-team** [comment]
Hi @jos-zz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jos-zz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jos-zz** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @jos-zz. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jos-zz, here is your [Magento instance](https://i-20151-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-20151-2-2-6.instances.magento-community.engineering/admin](https://i-20151-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-20151-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-20151-2-2-7.instances.magento-community.engineering/admin](https://i-20151-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97535` were created

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-20151-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-20151-2-2-5.instances.magento-community.engineering/admin](https://i-20151-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jos-zz** [comment]
Hi @maheshWebkul721 ,
Thank you for looking into this issue.
Please let me know which steps/tests did you perform and if you think there's a solution in the horizon.
Looking forward to hearing from you.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@maheshWebkul721 On vanilla instance this page doesn't work for security reason,

**Comment by ghost** [comment]
Hi @jos-zz i'm not able to reproduce following steps you described, can you please show your apache configuration ? and link to setup wizard ?

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-20151-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-20151-2-2-6.instances.magento-community.engineering/admin](https://i-20151-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jos-zz** [comment]
Hi @engcom-backlog-nazar,

Please attached find a copy of the related section in the apache httpd.conf and the loaded apache Modules.
Let me know if you need a more specific details and where can I find it.

[apacheModules.txt](https://github.com/magento/magento2/files/2745992/apacheModules.txt)
[httpd.conf.txt](https://github.com/magento/magento2/files/2745996/httpd.conf.txt)

**Comment by ghost** [comment]
Hi @jos-zz i'm not able to reproduce on my local environment, i'm following this instruction to configure my server
https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_apache.html
https://devdocs.magento.com/guides/v2.3/install-gde/prereq/apache.html

**Comment by jos-zz** [comment]
Hi @engcom-backlog-nazar ,
Just want to point out that the Magento version that's having the issue in question is 2.2.6, you are looking in Magento 2.3.x docs.
What actions would you suggest in order to help you reproduce the issue or try to work around it?

**Comment by jos-zz** [comment]
This issue has not been resolved yet. Please provide instructions on how to debug.
The marketplace being not accessible is a major issue and will result in negative reviews rendering Magento as a bad product.
