### ISSUE TITLE
Magento 2.3 - Multi-Source Inventory discrepancy with stock at source and salable quantity

### ISSUE THREAD

**Issue by karthi5053** [magento/magento2#20162]
Thanks for incorporating, Multi source Inventory module in magento. But, we are facing some issues while incorporating and using this module on a realtime scenario.

Preconditions (*)
1) Magento 2.3.0

Steps to reproduce (*)

1) Create a Inventory source under (Store-> Inventory-> Sources) as "NY-Warehouse".
2) Create a stock as "NY-Warehouse Stock" under (Store-> Inventory-> Stocks), and assign to a Sales Channels for a website.
3) Now, for a simple product (Eg : SKU code - 24-MG02), assign this source, NY-Warehouse with stock as 100, unassign "Default Source".
    Here, 
        Quantity at source is 100,
        salable quantity is 100 
    is shown in catalog grid, which is fine as shown in image s1.png.
4) Now place, an order with 20 qty for the sku 24-MG02.
    Here, 
         Quantity at source remains as 100,
         salable quantity is 80, since we placed an order with qty 20. Refer s2.png
5) In realtime scenario, Sources means physical warehouse, so we may get latest stock from warehouse on a time to time basis.
   Consider, there is some new stocks arrived to warehouse for the sku : 24-MG02 and they increased the stock for the sku from 100 to 200, which can sold in the website. Now, we update the stock as source for "NY-Warehouse" to 200.
    Here,    
        Quantity at source remains as 200,
        however, salable quantity is 180. Refer s3.png

Expected result (*):

Upon, updating the stock at source for "NY-Warehouse" to 200, we expect the 200 quantity i.e salable quantity can be allowed for the users to place orders in website. But, we allowed to purchase upto 180 qty only. The remaining 20 qty is locked as the, order in warehouse for fullfillment. 
If the order is fullfilled i.e invoice and shipments are created,
    Quantity at changed to 180,
    Salable quantity is 180. Refer s4.png

Until, the placed orders is fullfilled, the salable qty is calculated by stock at source - pending orders in website.
    i.e 200 - 20 = 180.

In realtime scenario, we expect 200 quantity, that can be sold in website, as 200 qty is available in the warehouse, because warehouse will deduct the on-hand stock after shipping the order from their end.

![s1](https://user-images.githubusercontent.com/7961427/50961471-d089b080-14ed-11e9-940b-a8c62855d027.png)
![s2](https://user-images.githubusercontent.com/7961427/50961472-d089b080-14ed-11e9-9231-94dab222f96d.png)
![s3](https://user-images.githubusercontent.com/7961427/50961473-d089b080-14ed-11e9-902c-3944e4f548c7.png)
![s4](https://user-images.githubusercontent.com/7961427/50961476-d1224700-14ed-11e9-9a58-892a10a44061.png)

Regards,
Karthi Kumar.

**Comment by magento-engcom-team** [comment]
Hi @karthi5053. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@karthi5053 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @karthi5053 thank you for you report, please open issue here -> https://github.com/magento-engcom/msi
