### ISSUE TITLE
On customer login page input field are short width on tablet view

### ISSUE THREAD

**Issue by nainesh2jcommerce** [magento/magento2#20172]
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. go to customer login page 
2. check in put fields in tablet view 

### Expected result (*)

1. 
![image](https://user-images.githubusercontent.com/18118539/50970291-08e9b880-1507-11e9-8823-f5a2c7bec766.png)

2.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/18118539/50970373-2880e100-1507-11e9-8cc9-c6148d71cab8.png)

2.

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nainesh2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop  instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop  instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @nainesh2jcommerce thank you for you report, i;m not able to reproduce following steps you described.
![selection_260](https://user-images.githubusercontent.com/40756439/50971208-1a719700-14ec-11e9-9b46-68b81a476e0f.png)

**Comment by nainesh2jcommerce** [comment]
Hi @engcom-backlog-nazar, 
on customer login page, in tablet view, width of email input field and password field is too short width.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97557`, `MAGETWO-97558` were created

**Comment by nainesh2jcommerce** [comment]
I am working on this

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20369 by @nainesh2jcommerce in 2.2-develop branch
Related commit(s):
 - [4de166f5a78c1a08ca0b0074785493be5685f380](https://github.com/magento/magento2/commit/4de166f5a78c1a08ca0b0074785493be5685f380)

The fix will be available with the upcoming 2.2.8 release.

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20173 by @nainesh2jcommerce in 2.3-develop branch
Related commit(s):
 - [645617a7978c2eed2b4b483f8cfc9d120764c6aa](https://github.com/magento/magento2/commit/645617a7978c2eed2b4b483f8cfc9d120764c6aa)
 - [3f6c2c84db3ae61231c646361c6876d000cb8ec9](https://github.com/magento/magento2/commit/3f6c2c84db3ae61231c646361c6876d000cb8ec9)
 - [34f8e2129b2b5795b732409de5ea9188fc13f444](https://github.com/magento/magento2/commit/34f8e2129b2b5795b732409de5ea9188fc13f444)

The fix will be available with the upcoming  release.
