### ISSUE TITLE
Magento TechResources Release 2.2.7 download differs from composer install

### ISSUE THREAD

**Issue by azue** [magento/magento2#20175]
### Preconditions (*)

1. Magento 2.2.7 download form https://magento.com/tech-resources/download  Magento-CE-2.2.7-2018-11-20-10-24-34.tar.gz  `SHA1(Magento-CE-2.2.7-2018-11-20-10-24-34.tar.gz)= f3c4f04e8efb110ae5af94843775e4c70f25d098`
2. Composer install with `  "require": {
    "magento/product-community-edition": "2.2.7", ..
`

### Steps to reproduce (*)

1. Download the release Magento-CE-2.2.7-2018-11-20-10-24-34.tar.gz
2. Install a empty m2 instance with magento in different location
3. compare both files in  vendor/magento/module-catalog-import-export/composer.json

### Expected result (*)

1.  Release tar-ball comes with the same version as the composer-install versions.
 ( OR Composer-install results in a newer vendor versions )

### Actual result (*)

1. The tar download contains the module `magento/module-catalog-import-export` in version 100.2.6 
2. The composer-install version of `magento/module-catalog-import-export` is 100.2.4
3. The tar archive has a newer version, compared to the composer install. This version is buggy e.g. #20098

**Comment by magento-engcom-team** [comment]
Hi @azue. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@azue do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @azue thank you for you report i'm not see on composer version 100.2.4 import-export
![selection_263](https://user-images.githubusercontent.com/40756439/50975231-bb188480-14f5-11e9-8caa-22eabef9f191.png)

**Comment by azue** [comment]
your correct - i went to fast.  I missed the composer.lock, so my composer patch for `magento/module-catalog-import-export`  100.2.6 is working
