### ISSUE TITLE
Boolean Product attribute filter No doesn't affect and No result response from Product Grid

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#20205]
As I create a product attribute with source as boolean, basically all my products will not have this attribute value yet, but using this from product grid when filter No -> This return No result available.

### Preconditions (*)

1. Magento 2.2.8 (2.2-develop)
2. PHP 7.0
3. MariaDB 10.0.36

### Steps to reproduce (*)

1. Create a boolean product attribute **posted_to_instagram**

````
$eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'posted_to_instagram',
            [
                'type' => 'int',
                'group' => 'Auto Instagram Post',
                'backend' => 'Magento\Catalog\Model\Product\Attribute\Backend\Boolean',
                'frontend' => '',
                'label' => 'Instagram Status',
                'input' => 'select',
                'class' => '',
                'source' => 'Magento\Eav\Model\Entity\Attribute\Source\Boolean',
                'global' => Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'visible' => false,
                'required' => false,
                'user_defined' => true,
                'searchable' => false,
                'filterable' => false,
                'comparable' => false,
                'visible_on_front' => false,
                'used_in_product_listing' => false,
                'used_for_sort_by' => false,
                'is_used_in_grid' => true,
                'is_filterable_in_grid' => true,
                'unique' => false,
                'apply_to' => '',
                'default' => 0
            ]
        );
````

2. Try to save 1 product with posted_to_instagram = 1
3. Go to product grid while posted_to_instagram attribute column was enabled from grid
4. Go filter the value Yes - No

### Expected result (*)

1. Choose Yes -> 1 product available 
2. Choose No -> The left except above product 
3. Or **Yes**, **No** or **No Value** should be the values of the Boolean attribute filter

### Actual result (*)

1. Choose Yes -> 1 product available -> Correct
2. Choose No -> No result available. Assume the filter was filter correctly with the value No because there products have no attribute value yet but how to filter them while the value was not updated to.

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tuyennn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment]
@tuyennn 
`'filterable' => false,` why you have set filterable false. It should be true while creation of attribute.

**Comment by ghost** [comment]
Hi @tuyennn thank you for you report, this is acknowladged issue, please look -> https://github.com/magento/magento2/issues/16367

**Comment by tuyennn** [comment]
@engcom-backlog-nazar Thanks for your report, glad to see this but seem no one has activity with ref issue.

**Comment by ghost** [comment]
@tuyennn seems like this very difficult to fix.

**Comment by minhlam3118410220** [comment]
Have you fixed this error yet?
