### ISSUE TITLE
Magento 2.3 EE : Coupon Type is not changing in salesrule table for schedule changes of cart price rules

### ISSUE THREAD

**Issue by sneha-panchal** [magento/magento2#20211]
### Preconditions (*)

1. Magento 2.3 Enterprise

### Steps to reproduce (*)

1. Create cart price rule with coupon type Auto and Action is Fixed amount discount and save.
2. Now Schedule new update in that rule and add from and to date for the rule and save that update and also save the rule.
3. Now please check **salesrule** table.
4. You have 3 rows added for this rule and all having coupon_type = 3 (3 is for Auto coupon type).
5. Now please edit the same rule and change coupon type "Auto" to "Specific Coupon" and save that rule.
6. Now please check **salesrule** table.

### Expected result (*)

1. Our rule data rows in **salesrule** table having coupon_type = 3 will be changed to 2 (2 is for specific coupon type).

### Actual result (*)

1. When i check **salesrule** table schedule changed data row's coupon_type is displaying 3 (3 is for Auto).
2. Scheduled changes row is not updating coupon_type in table.

Please check attached screenshots :

![fixed amount discount promotions marketing magento admin](https://user-images.githubusercontent.com/29649994/51028009-4e19f300-15b8-11e9-9408-2947291405e1.png)

![fixed amount discount promotions marketing magento admin 3](https://user-images.githubusercontent.com/29649994/51028039-5d00a580-15b8-11e9-8f3d-916879a9ff4a.png)

![fixed amount discount promotions marketing magento admin 2](https://user-images.githubusercontent.com/29649994/51028043-638f1d00-15b8-11e9-97fa-cbd7a07a606a.png)

**Comment by magento-engcom-team** [comment]
Hi @sneha-panchal. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sneha-panchal do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @sneha-panchal  GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
