### ISSUE TITLE
Password validation message not conatin complete background for create an account page

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#20220]
Password validation message not contain complete background for create an account page

### Preconditions (*)

1.Issue is arises in 2.3 version of magneto
2.In desktop tablet view and for mobile view

### Steps to reproduce (*)

1.Click on create an account page link present on header. while creating account if password is weak or medium the message come with incomplete background
2.while creating account if password is weak or medium the message come with incomplete background

### Expected result (*)
It should contain complete background for password validation

### Actual result (*)

![2019-01-11_18-14_create new customer account](https://user-images.githubusercontent.com/18118638/51035389-d952b300-15cf-11e9-83cf-855066e9bfea.jpg)

![2019-01-11_18-17_create new customer account](https://user-images.githubusercontent.com/18118638/51035390-d952b300-15cf-11e9-86e0-891c1167f3c5.jpg)

![2019-01-11_18-29_create new customer account](https://user-images.githubusercontent.com/18118638/51035391-d9eb4980-15cf-11e9-86e2-837efb7e6f5a.jpg)

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-20220-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20220-2-3-develop.instances.magento-community.engineering/admin](https://i-20220-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amol2jcommerce** [comment]
Hi @dipti2jcommerce  this is expected behavior , this is non issue.

**Comment by GovindaSharma** [comment]
@dipti2jcommerce , i checked this is not an issue.I have checked in vanilla instance the issue which you have reported does not exist.So i am closing this now.
