### ISSUE TITLE
Review text Should be capitalized

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#20234]
### Preconditions (*)

1.Magento 2.3-develop

### Steps to reproduce (*)

1.Open any Product Listing page in  front-end side

### Expected result (*)

http://prntscr.com/m65abw

### Actual result (*)

http://prntscr.com/m65aj9

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@speedy008 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-20234-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20234-2-3-develop.instances.magento-community.engineering/admin](https://i-20234-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by milindsingh** [comment]
@speedy008  Is it really an Issue? 
`add your review` vs `Add Your Review`

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by SyntaxKay** [comment]
@milindsingh 
Its Improvement. 
It should be capitalized.

**Comment by milindsingh** [comment]
@speedy008 It a matter of opinion I think.
As I see it looks good without being capitalized.
![home page](https://user-images.githubusercontent.com/13949703/51070365-0ce01c80-1666-11e9-826d-9c910dd3c0ca.png)

**Comment by SyntaxKay** [comment]
@milindsingh 
In Product Detail page it is capitalized and to maintain consistency
![image](https://user-images.githubusercontent.com/33230237/51070385-62b4c480-1666-11e9-99ca-527946829dfc.png)

**Comment by milindsingh** [comment]
@speedy008 At the same time, when there is no review the text is not capitalized for every word.
![asdsad](https://user-images.githubusercontent.com/13949703/51070574-744b9b80-1669-11e9-83f5-6dce73ef31d1.png)

**Comment by SyntaxKay** [comment]
@milindsingh Please have a look on attached screenshot.:

![whatnew](https://user-images.githubusercontent.com/33230237/51071158-90a00600-1672-11e9-9a33-baa88bccec5c.png)

**Comment by milindsingh** [comment]
![test](https://user-images.githubusercontent.com/13949703/51071513-1e322480-1678-11e9-9b99-b5abf4c40523.png)

**Comment by SyntaxKay** [comment]
@milindsingh, Do we need to capitalize this as well?

**Comment by rogyar** [comment]
This issue is very doubtful because of many factors. 
We cannot consider it as an issue since the number of reviews is not capitalized as well. So, here is another question, should we have the add review link capitalized as well. 
If the entire row is not capitalized, it's rather designers decision than an issue.

**Comment by orlangur** [comment]
> Review text Should be capitalized

Agree that it should not as "add your review" looks muuuch cleaner in current design.

Also, please note that whenever we decide to change such caption, it should not be achieved with CSS.

**Comment by SyntaxKay** [comment]
@orlangur , Thanks, So should I do that in PHTML file instead of CSS?
Also, We can change the text from  "add your review" to "Submit Review"?

**Comment by ghost** [comment]
"I am working on this at #dmcdindia19”"

**Comment by magento-engcom-team** [comment]
@surbhi-ranosys thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Charlie** [comment]
Hello @speedy008 
I can't reproduce this issue on fresh Magento 2.3-develop.
Screenshot:
![image](https://user-images.githubusercontent.com/51680850/62683945-47295680-b9c8-11e9-87c5-4323f5e7dfce.png)

So i close it.
Thank for your report!
