### ISSUE TITLE
Magento crontab does not re-index anymore

### ISSUE THREAD

**Issue by RedAtRareCandy** [magento/magento2#20242]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1.25
3. CentOS 6

### Steps to reproduce (*)

1. Install Magento 2.3.0
2. Install cronjobs with bin/magento cron:install
3. Add new product and category and connect product to category and add a price.
4. Go to System > Index Management and should see "Reindex Required" red boxes.
5. Change all of the Indexers to "Update by Schedule".
6. Wait 30 minutes and refresh.

### Expected result (*)

1. The red boxes saying "Reindex Required" should be gone because cron reindexed correctly?

### Actual result (*)

1. 30 minutes after change to products/categories, the red boxes in Index Management are still there saying "Reindex Required". Cron isn't reindexing them?

**Comment by magento-engcom-team** [comment]
Hi @RedAtRareCandy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@RedAtRareCandy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by RedAtRareCandy** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @RedAtRareCandy. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @RedAtRareCandy, here is your [Magento instance](https://i-20242-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20242-2-3-0.instances.magento-community.engineering/admin](https://i-20242-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by RedAtRareCandy** [comment]
> Hi @RedAtRareCandy. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
>     * [x]  Summary of the issue
> 
>     * [x]  Information on your environment
> 
>     * [x]  Steps to reproduce
> 
>     * [x]  Expected and actual results
> 
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @RedAtRareCandy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
>     * [x]  yes
> 
>     * [ ]  no

**Comment by saphaljha** [comment]
@RedAtRareCandy Prefer the original Comment:
https://github.com/magento/magento2/issues/20242#issuecomment-453734075

**Comment by RedAtRareCandy** [comment]
> @RedAtRareCandy Prefer the original Comment:
> [#20242 (comment)](https://github.com/magento/magento2/issues/20242#issuecomment-453734075)

Hi - Not sure how to "tick" the boxes. Can't find instructions to do so..

**Comment by RedAtRareCandy** [comment]
Noticed cron_schedule db table does not have any "indexer_reindex_all_invalid" jobs and when new table entries are made they're not added then either?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @RedAtRareCandy thank you for you report, i'm not able to reproduce following steps you described.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by RedAtRareCandy** [comment]
Hi @engcom-backlog-nazar 

I think you might have closed this prematurely? As soon as I changed the PHP CLI version to 7.2(.13), it looks now like the cron_schedule table is being populated with jobs that it wasn't getting under PHP CLI version 7.1.25.

Did you test with PHP 7.1 or PHP 7.2?
