### ISSUE TITLE
In mobile view of Mini cart block ,update button overlapping edit and remove link

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#20275]
In mobile view of Mini cart block update button overlapping edit and remove link  

### Preconditions (*)

1.In mobile view for all browser

### Steps to reproduce (*)

1.Go to minicart basket dropdown present in header by adding product
2.In mobile view of Mini cart block update button overlapping edit and remove link for all version

### Expected result (*)
![2019-01-14_18-21_shopping cart](https://user-images.githubusercontent.com/18118638/51113800-5af14d80-1829-11e9-97f2-2f394aa51b21.jpg)

### Actual result (*)
![2019-01-14_18-11_cassius sparring tank](https://user-images.githubusercontent.com/18118638/51113808-5f1d6b00-1829-11e9-9002-15efd7ab592a.jpg)

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @dipti2jcommerce thank you for you report, this is no-issue because this button appear only if you enter qty for product, and will disappear when you update.

**Comment by dipti2jcommerce** [comment]
In magneto 2.2 button is showing below qty box,
![2019-01-14_18-38_home page](https://user-images.githubusercontent.com/18118638/51114573-b3c1e580-182b-11e9-879b-150470dbe057.jpg)

But in 2.3 version update button overlapping edit and remove link in mobile view

**Comment by ghost** [comment]
@dipti2jcommerce  i think this issue only on 2.2 , I think the behavior of what is 2.3 is correct

**Comment by irajneeshgupta** [comment]
![download](https://user-images.githubusercontent.com/18143480/51114955-d56f9c80-182c-11e9-87a6-a36206d857b6.png)

@engcom-backlog-nazar Its reproduced in 2.3-develop

**Comment by ghost** [comment]
@irajneeshgupta 
![selection_267](https://user-images.githubusercontent.com/40756439/51115082-e52cb800-180f-11e9-88e1-21d037ba238c.png)

**Comment by irajneeshgupta** [comment]
@engcom-backlog-nazar 
i was checking in this instance without sample data:
https://i-20273-2-3-develop.instances.magento-community.engineering/test-product.html
