### ISSUE TITLE
Uploaded file for custom option can't be downloaded again

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#20277]
### Preconditions
1. Magento 2.3.0 and Magento 2.2.X

### Related issues
I found the following related issue, which was already closed: 
- #6558 

### Steps to reproduce
1. Create a product with a custom option of the type "File"
2. Create a new order and upload a file for the product as a custom option
3. Check the order and download the file, this is working.
4. Update the product and delete the custom option from the product.
5. Go back to the order and try to download the file again. This will result in a 404. 

### Expected result
1. I can download the file which is attached to the product in the order no matter if the custom option is still available or not. 

### Actual result
1. Downloading a file from an order where the custom option is no longer present results in a 404.

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dverkade do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @dverkade now we have 2 open issue ?

**Comment by magento-engcom-team** [comment]
Hi @gulshanchitranshcedcoss. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97620`, `MAGETWO-97621` were created

**Comment by nadim2jcommerce** [comment]
Hi @dverkade/@magento-engcom-team

This issue is still on 2.2.4 version. Not yet fixed. 
Fix has been added by @paales in #6558.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-20277-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20277-2-2-develop.instances.magento-community.engineering/admin](https://i-20277-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your report. 
The issue has been fixed in magento/magento2#20354 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [07590265b65809fa3d86f8ba92202920375d8d5f](https://github.com/magento/magento2/commit/07590265b65809fa3d86f8ba92202920375d8d5f)
 - [9c6af937aeac51ba4f9bef9241a8ab1930cf521a](https://github.com/magento/magento2/commit/9c6af937aeac51ba4f9bef9241a8ab1930cf521a)
 - [bf246dab9ddd849bed312e6570983aeb5522c888](https://github.com/magento/magento2/commit/bf246dab9ddd849bed312e6570983aeb5522c888)
 - [45c6fc7fdf35e20365baa872ca796a8ee44c69d3](https://github.com/magento/magento2/commit/45c6fc7fdf35e20365baa872ca796a8ee44c69d3)
 - [3a01bc08c57a8ff3f12f1745223dccf9996c793c](https://github.com/magento/magento2/commit/3a01bc08c57a8ff3f12f1745223dccf9996c793c)
 - [18ae227d2411b7d0f1709971b1ce93dfce2e8108](https://github.com/magento/magento2/commit/18ae227d2411b7d0f1709971b1ce93dfce2e8108)

The fix will be available with the upcoming 2.3.1 release.
