### ISSUE TITLE
Admin - Multi-country - can't create order - Invalid value countryId

### ISSUE THREAD

**Issue by vitalygrigorishin** [magento/magento2#20287]
### Preconditions (*)
1. Magento version 2.2.7
2. We have 2 (2+) websites:
2.1 Main Website - for USA (Allowed countries option - only USA selected)
2.2 Canadian Website - For Canada (Allowed countries option -  only Canada selected)

### Steps to reproduce (*)
1. Go to Admin --> Sales --> Orders -- > Create New Order
2. Create New Customer
3. Select Store view Canadian of website
4. Place an order for Canadian Address (Shipping and billing can be similar)

Note: Only Canada is available
![capture 2019-01-14 at 17 19 24](https://user-images.githubusercontent.com/11736731/51121739-d39fdc00-1820-11e9-85a2-4af3b2407ced.png)

### Expected result (*)
1. The order was placed

### Actual result (*)
1. The order can't be placed - an error occured: Please check the shipping address information. Ivalid value of "CA" provided for the countryId field.
![capture 2019-01-14 at 17 22 37](https://user-images.githubusercontent.com/11736731/51121851-182b7780-1821-11e9-91a1-39f82079f05f.png)

**Note from development:**
I debugged it - looks like during Shipping address validation allowed countries from  Main Website were used (not from Current Website or Default/Global one)

**Comment by magento-engcom-team** [comment]
Hi @vitalygrigorishin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vitalygrigorishin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20287-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20287-2-2-develop.instances.magento-community.engineering/admin](https://i-20287-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@vitalygrigorishin this issue is not reproduceable at current magento 2.2-develop instance

**Comment by shikhamis11** [comment]
@vitalygrigorishin since this issue is not reproduceable I am closing this.

**Comment by vitalygrigorishin** [comment]
Thanks
