### ISSUE TITLE
Twice url in sitemap image path

### ISSUE THREAD

**Issue by key-dev** [magento/magento2#20289]
### Preconditions (*)
Magento 2.2.2
Apache 2.4
document root public_html

### Steps to reproduce (*)
Add a sitemap with a path of /sitemaps/
Allow cron to generate the sitemap

### Expected result (*)
<image:loc>https://www.site.com/pub/media/catalog/product/cache/c9e0b0ef589f3508e5ba515cde53c5ff/c/m/cm265c.jpg</image:loc>

### Actual result (*)
<image:loc>https://www.site.com/pub/media/https://www.site.com/pub/media/catalog/product/cache/c9e0b0ef589f3508e5ba515cde53c5ff/c/m/cm265c.jpg</image:loc>

Please help

**Comment by magento-engcom-team** [comment]
Hi @key-dev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@key-dev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-20289-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20289-2-2-develop.instances.magento-community.engineering/admin](https://i-20289-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @key-dev thank you for you report, this issue has already fixed in 2.2-develop and 2.3-develop branch. and available on 2.3.0 release

**Comment by key-dev** [comment]
Hello @engcom-backlog-nazar 
Can you give me the reference of this fix so i can update my code?
I am actually using Magento ver 2.2.2 and i don't want to upgrade it because of some custom APIs and things.
Thank you

**Comment by zapateroremendon** [comment]
Hi,
Same issue with magento 2.2.7, centos 7, nginx, varnish and php-fpm71.
anybody have resolved?

**Comment by omair-rltsquare** [comment]
In my case, It was due to the 3rd party SEO extension which was using a deprecated method:
\Magento\Sitemap\Model\Sitemap::_getMediaUrl

Removing the usage of this method from code fixed the issue, as url was already provided.
