### ISSUE TITLE
Module Catalog Url Rewrite: Permanent Redirect for old URL is missed when product was imported

### ISSUE THREAD

**Issue by ghost** [magento/magento2#20282]
### Preconditions (*)

1. Magento 2.2.7

### Steps to reproduce (*)

1. Export some visible product via System-> Data Transfer-> Export.
2. Change 'url-key' for this product in CSV file.
3. Import this product via System-> Data Transfer-> Import.

### Expected result (*)

1. When you try to open the changed product by the old URL key you are redirected to the new URL.

### Actual result (*)

1. When you try to open the changed product by the old URL key you receive 404-page.

**Comment by magento-engcom-team** [comment]
Hi @olegAleksin. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@olegAleksin do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20282-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20282-2-2-develop.instances.magento-community.engineering/admin](https://i-20282-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@olegAleksin did you tried reindexing after changing url key ??

**Comment by ghost** [comment]
@shikhamis11 Yes, I did

**Comment by oleksandr-butenko** [comment]
> @olegAleksin did you tried reindexing after changing url key ??

URL rewrites are not created during to reindex. 
URL rewrites are created during saving product or import process. 

So if you imported a new file, but URL rewrites are not correct - no need to wait for indexes. 
You better check your file, products and Marketing > SEO & Search > URL Rewrite page.

**Comment by shikhamis11** [comment]
@olegAleksin yes url rewrites are created during saving product .

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97622` were created

**Comment by nadim2jcommerce** [comment]
Hi @olegAleksin,

This is not an issue. Also not indexing issue. You should add url redirect in Admin for this.
Redirection old url to New url
Magento Admin=>Marketing=>Seo and Search=>URL Rewrites.

Thanks!
Nadim

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @olegAleksin. Thank you for your report. 
The issue has been fixed in magento/magento2#20344 by @ankur-cedcoss in 2.3-develop branch
Related commit(s):
 - [e331b3f849b9f1ed98dd9dce1f53041298dffe63](https://github.com/magento/magento2/commit/e331b3f849b9f1ed98dd9dce1f53041298dffe63)
 - [86685289a45c89fba908c3c620a03387bb02a260](https://github.com/magento/magento2/commit/86685289a45c89fba908c3c620a03387bb02a260)

The fix will be available with the upcoming 2.3.1 release.

**Comment by sidolov** [comment]
Hi @olegAleksin. Thank you for your report. 
The issue has been fixed in magento/magento2#20737 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [1cb5e515a0aad074fb67dcc73ad9075214cbdcac](https://github.com/magento/magento2/commit/1cb5e515a0aad074fb67dcc73ad9075214cbdcac)
 - [7de5e7ea7319bb6c1ab0c44e0ccbc898939d2983](https://github.com/magento/magento2/commit/7de5e7ea7319bb6c1ab0c44e0ccbc898939d2983)

The fix will be available with the upcoming 2.2.9 release.
