### ISSUE TITLE
Order item details label not aligned in mobile view 

### ISSUE THREAD

**Issue by ghoshsweta** [magento/magento2#20299]
Order item details label not aligned in mobile view 

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

Step 1: Open frontend and login as customer 
Step 2: Go to my account section
Step 3: Click on My order link and open detail any order in mobile 
Step 4: You will issue as shown in screenshot 

### Expected result (*)
![sol](https://user-images.githubusercontent.com/25763126/51176667-889acd00-18e3-11e9-8d03-bb615c1b11ee.png)

### Actual result (*)

![issue](https://user-images.githubusercontent.com/25763126/51176682-918b9e80-18e3-11e9-8b67-2647dee8785e.png)

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@swetacedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda, here is your [Magento instance](https://i-20299-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20299-2-3-develop.instances.magento-community.engineering/admin](https://i-20299-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@cedarvinda Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97636` were created

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20299-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20299-2-2-develop.instances.magento-community.engineering/admin](https://i-20299-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20301 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [0652e87b1941d868c8d2469ba12e07fd35d6d130](https://github.com/magento/magento2/commit/0652e87b1941d868c8d2469ba12e07fd35d6d130)
 - [b1e21dbabe207997ce877390bb5e58456f5a4d66](https://github.com/magento/magento2/commit/b1e21dbabe207997ce877390bb5e58456f5a4d66)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20466 by @priti2jcommerce in 2.3-develop branch
Related commit(s):
 - [4b04aed0dbc2708eb66973b3a67dc80c56983c43](https://github.com/magento/magento2/commit/4b04aed0dbc2708eb66973b3a67dc80c56983c43)
 - [3475a1f309305fb08123ba495b83ecf8553e3468](https://github.com/magento/magento2/commit/3475a1f309305fb08123ba495b83ecf8553e3468)
 - [c1a99589de4f5c41968bbda5853a697f4c41999f](https://github.com/magento/magento2/commit/c1a99589de4f5c41968bbda5853a697f4c41999f)
 - [4812aa4ebbe72d9801fedb26fb50d7cf03e5033b](https://github.com/magento/magento2/commit/4812aa4ebbe72d9801fedb26fb50d7cf03e5033b)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20539 by @irajneeshgupta in 2.2-develop branch
Related commit(s):
 - [867f47465bfee044b51b621392ca3228fb803a2c](https://github.com/magento/magento2/commit/867f47465bfee044b51b621392ca3228fb803a2c)
 - [362f81fada5975a193b1a41415725cf9bdad4ef7](https://github.com/magento/magento2/commit/362f81fada5975a193b1a41415725cf9bdad4ef7)

The fix will be available with the upcoming 2.2.9 release.

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#21243 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [4b07a5c8806a22758c46d17d4493de2c3c362044](https://github.com/magento/magento2/commit/4b07a5c8806a22758c46d17d4493de2c3c362044)
 - [ef4cdb62bc1044e2f2fcb402465f7f8b5b92f52a](https://github.com/magento/magento2/commit/ef4cdb62bc1044e2f2fcb402465f7f8b5b92f52a)
 - [e956712022174e1eaf46b152b25b60e98515e674](https://github.com/magento/magento2/commit/e956712022174e1eaf46b152b25b60e98515e674)
 - [597c4af3d5ea9b47200108adac46909d95a3b808](https://github.com/magento/magento2/commit/597c4af3d5ea9b47200108adac46909d95a3b808)
 - [a12d7af12c33180657f038c007521c7cf55e07f6](https://github.com/magento/magento2/commit/a12d7af12c33180657f038c007521c7cf55e07f6)

The fix will be available with the upcoming 2.2.9 release.
