### ISSUE TITLE
REST API  special-price without price_to param set a wrong value

### ISSUE THREAD

**Issue by dachaga** [magento/magento2#20321]
When a request to special-price API is sent without price_to param, the special price value is setted with a incorrect value

### Preconditions (*)
1. Magento version 2.3.0
2. One product in the catalog.
3. Use Postman to do request to the Magento API

### Steps to reproduce (*)
1. Use postman to get token to operate with magento API. 
http://site.com/rest/V1/integration/admin/token?username=user&password=pass
2. Use postman and token got in step 1 to set special-price
http://site.com/rest/V1/products/special-price
Example Body:
{
	"prices": [
{
	"price": 789.99,
	"store_id": 0,
	"sku": "sku1",
	"price_from": "2019-02-01 00:00:00"
}
]
}

3. Use postman and token got in step 1 to get special-price information 
http://site.com/rest/V1/products/special-price-information
Example Body:
{
	"skus": [
                    "sku1"
         ]
}

### Expected result (*)

1.The special price value should be  789.99
 {
        "price": 900,
        "store_id": 0,
        "sku": "sku1",
        "price_from": "1970-01-01 00:00:01",
        "price_to": "2019-02-01 00:00:00"
    },
    {
        "price": 789.99,
        "store_id": 0,
        "sku": "sku1",
        "price_from": "2019-02-01 00:00:00",
        "price_to": "2038-01-19 03:14:07"
    }

### Actual result (*)

1. The actual price value is the same to that schedule, because price_to was not sent uin request to special-price
 {
        "price": 900,
        "store_id": 0,
        "sku": "sku1",
        "price_from": "1970-01-01 00:00:01",
        "price_to": "2019-02-01 00:00:00"
    },
    {
        "price": 900,
        "store_id": 0,
        "sku": "sku1",
        "price_from": "2019-02-01 00:00:00",
        "price_to": "2038-01-19 03:14:07"
    }

**Comment by magento-engcom-team** [comment]
Hi @dachaga. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dachaga do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-20321-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20321-2-3-develop.instances.magento-community.engineering/admin](https://i-20321-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by irajneeshgupta** [comment]
@dachaga 
I was not able to reproduce it.
[https://i-20321-2-3-develop.instances.magento-community.engineering/rest/all/V1/products/special-price-information
](https://i-20321-2-3-develop.instances.magento-community.engineering/rest/all/V1/products/special-price-information)
`[
  {
    "price": 2800,
    "store_id": 0,
    "sku": "teest",
    "price_from": "2019-02-01 00:00:00",
    "price_to": null
  }
]`

**Comment by dachaga** [comment]
That Magento instance have not module-staging installed. The problem is with that module, because Magento creates schedules with different special prices when these are updated.
