### ISSUE TITLE
Shipping address form City, State/Province, Zip/Postal Code, Country not in right Order in checkout 

### ISSUE THREAD

**Issue by ghoshsweta** [magento/magento2#20332]
Shipping address form **City, State/Province, Zip/Postal Code, Country fields** not in right Order in checkout 

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

Step 1: Open frontend 
Step 2: Add any product in cart 
Step 3: Go to checkout and and see shipping address form

### Expected result (*)
Order should be in : **Country**, **State/Province**, **City**, **Zip/Postal Code fields**

![sol](https://user-images.githubusercontent.com/25763126/51231918-25fd0c00-198b-11e9-9011-b0230f0201b9.png)

### Actual result (*)

![arpklxz](https://user-images.githubusercontent.com/25763126/51231928-2e554700-198b-11e9-8622-754428f47aec.png)

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@swetacedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
@cedarvinda Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97652` were created

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mayurasisodia** [comment]
I am working on this issue #mm19in

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#24784 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [2d759c01d80478f61892dfe4c38a283f7caff0bf](https://github.com/magento/magento2/commit/2d759c01d80478f61892dfe4c38a283f7caff0bf)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss, @Bartlomiejsz. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24417` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by chris-pook** [comment]
Hi @swetacedcoss, @Bartlomiejsz 

This looks like it has caused an issue with the shipping address fields on the checkout shipping address section (tested in 2.4.2). The country selection now comes straight after the street input fields. It doesn't look like this was intentional as part of this fix:

![image](https://user-images.githubusercontent.com/4628660/110776972-83820000-8258-11eb-9c86-f3b790ac5523.png)

**Comment by rhoerr** [comment]
For anyone else caught off guard by this and the user experience implications for US customers and US-focused businesses, you can revert the field order to [city, state, zip, country] with these two SQL queries:

```
update customer_eav_attribute cea
inner join eav_attribute ea on ea.attribute_id=cea.attribute_id
set cea.sort_order=115
where ea.attribute_code in ('country_id') and ea.entity_type_id=2;

update customer_eav_attribute cea
inner join eav_attribute ea on ea.attribute_id=cea.attribute_id
set cea.sort_order=105
where ea.attribute_code in ('region', 'region_id') and ea.entity_type_id=2;
```
