### ISSUE TITLE
Option Title breaking in two line because applying  wrong css for manage width

### ISSUE THREAD

**Issue by ghoshsweta** [magento/magento2#20337]
Option Title breaking in two line because applying  wrong css for manage width

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)
1. Login to admin panel 
2. Go in **Catalog > product** section 
3. Create new product and go to tab **Customizable Options**  and click on **Add option** button
and see first label **Option Title**  (See screenshot shown)

### Actual result (*)

![w6xu66h](https://user-images.githubusercontent.com/25763126/51245641-4f7b5f00-19ae-11e9-9d0f-bd398c17bb22.png)

### Expected result (*)

![sol](https://user-images.githubusercontent.com/25763126/51245655-5ace8a80-19ae-11e9-8c0f-b30d1fa0709f.png)

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@swetacedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment]
@magento-engcom-team  give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97659` were created

**Comment by dipti2jcommerce** [comment]
Hi @engcom-backlog-nazar ,
Can You Please provide me testing instance.

**Comment by ghost** [comment]
@dipti2jcommerce you can recheck on your local environment.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by amol2jcommerce** [comment]
Hi @swetacedcoss  

I can't reproduced it.

**Comment by cedarvinda** [comment]
@amol2jcommerce It's Reproduced in my local system 
http://i.imgur.com/wkFhhwu.png

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-20337-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20337-2-3-develop.instances.magento-community.engineering/admin](https://i-20337-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amol2jcommerce** [comment]
Hi @cedarvinda 

It's Not Reproduced in given instance.
![2019-01-16_18-28_new product - products](https://user-images.githubusercontent.com/18118631/51251050-5742ff80-19be-11e9-9e5e-c654239d5f69.jpg)

**Comment by ghost** [comment]
@amol2jcommerce thank you

**Comment by ghost** [comment]
@amol2jcommerce please recheck this issue on tablet view 
![selection_268](https://user-images.githubusercontent.com/40756439/51252102-9a43a980-19a3-11e9-8e31-61a634886e0c.png)

**Comment by cedarvinda** [comment]
I am checking 1366 x 768 resolution device Its reproduced.
If it's on tablet view, should be fixed.

**Comment by magento-engcom-team** [comment]
Hi @swetacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#20339 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [74b2098d878e71ec39284019ad887edce815f049](https://github.com/magento/magento2/commit/74b2098d878e71ec39284019ad887edce815f049)
 - [d7ba787a107ec5599dd60af84ca99fa73fff6b40](https://github.com/magento/magento2/commit/d7ba787a107ec5599dd60af84ca99fa73fff6b40)

The fix will be available with the upcoming 2.3.2 release.
