### ISSUE TITLE
Magento community edition 2.1.* to 2.3.* - bin/magento setup:upgrade - Schema creation/updates: SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by ghost** [magento/magento2#20346]
Hi there,

I'm upgrading from "magento/product-community-edition": "2.1.8" to "magento/product-community-edition": "2.3.0" using the command-line - https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html#upgrade-cli-upgr

Unfortunately it fails when updating the database schema and data - https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html#update-the-database-schema-and-data

`php bin/magento setup:upgrade -vvv`
```
Updating modules:
Schema creation/updates:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-' for key 'EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE', query was: ALTER TABLE `eav_attribute_grou
p` ADD CONSTRAINT `EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_CODE` UNIQUE KEY (`attribute_set_id`,`attribute_group_code`)
```

I can see the offending rows in the "eav_attribute_group" table but I don't want to delete any data for obvious reasons.

Thanks for your time and any help is appreciated.
Mike

**Comment by magento-engcom-team** [comment]
Hi @mibu31. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mibu31 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @mibu31 thank you for you report, this may be related to your custom modules, that created a additional attribute group, on clean 2.1 release  i am able successfully upgrade to 2.3.0

**Comment by ghost** [comment]
Thanks for the quick reply. 
Note that this build used the "data-migration-tool" from 1.8.0.0 to 2.1.8 - are you sure it's a custom module issue and not something that may have been corrupt during the data migration?
Cheers

**Comment by ghost** [comment]
@mibu31 i think you need report here -> https://github.com/magento/data-migration-tool

**Comment by ghost** [comment]
Thank you.
