### ISSUE TITLE
Module uninstall without composer package don't work

### ISSUE THREAD

**Issue by iget-esoares** [magento/magento2#20342]
### Summary (*)

Running `bin/magento module:uninstall Local_Package` when `Local_Package` is a package that's inside `app` folder fails with:

>     Local_Package is not an installed composer package

And this prevents developers from testing the `Setup/Uninstall` script.

### Examples (*)

My development approach is to develop inside `app` until my package is mature enough to go to a composer package. Using a composer package to early development is a pain for me because or I make a symbolic link on vendor, or I need to push, wait composer sync, then composer update.

### Proposed solution

1. When the package is not installed though composer, we can just ignore other steps and run the `Setup/Uninstall` script
2. Alternatively we can add a `--force` argument to the `module:uninstall` command.

**Comment by magento-engcom-team** [comment]
Hi @iget-esoares. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@iget-esoares do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by iget-esoares** [comment]
@engcom-backlog-nazar Please note that the composer is related to this command just to allow running `composer remove` command.

If the module is not a composer package, so there's no reason to do that command, so we can just skip it and throw an warning to the user like: "The module Namespace_Module is not a composer package. It files won't be removed."

**Comment by ghost** [comment]
Hi @iget-esoares  thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features
