### ISSUE TITLE
The parent product doesn't have configurable product options.

### ISSUE THREAD

**Issue by usamahabib786** [magento/magento2#20366]
### Preconditions (*)

PHP 7.2
MySQL CE 5.6.30
Magento 2.3

### Steps to reproduce (*)

1.Create a Configurable product, Set the configurable attribute and Link the simple products to the configurable product using BULK API endpoint: rest/async/bulk/V1/configurable-products/bySku/child
2. **Input POST**
[
  {
    "sku": "parentSku",
    "childSku": "ChildNo1Sku"
  },
  {
    "sku": "parentSku",
    "childSku": "ChildNo2Sku"
  },
  {
    "sku": "parentSku",
    "childSku": "ChildNo3Sku"
  }
]

**RESPONSE:** 
{
    "bulk_uuid": "d934bf6f-bc8f-4189-b6b9-9a85896c8641",
    "request_items": [
        {
            "id": 0,
            "data_hash": null,
            "status": "accepted"
        },
        {
            "id": 1,
            "data_hash": null,
            "status": "accepted"
        },
        {
            "id": 2,
            "data_hash": null,
            "status": "accepted"
        }
    ],
    "errors": false
}

### Expected result (*)

1.Mass update for Topic async.V1.configurable-products.sku.child.POST should be updated successfully.

### Actual result (*)

1. Mass update for Topic async.V1.configurable-products.sku.child.POST failed.
2. On checking the status of bulk uuid response is: 
 {
    "operations_list": [
        {
            "id": 298,
            "status": 3,
            "result_message": "The parent product doesn't have configurable product options.",
            "error_code": 0
        },
        {
            "id": 299,
            "status": 3,
            "result_message": "The parent product doesn't have configurable product options.",
            "error_code": 0
        },
        {
            "id": 300,
            "status": 3,
            "result_message": "The parent product doesn't have configurable product options.",
            "error_code": 0
        }
    ],
    "user_type": 1,
    "bulk_id": "d934bf6f-bc8f-4189-b6b9-9a85896c8641",
    "description": "Topic async.V1.configurable-products.sku.child.POST",
    "start_time": "2019-01-17 10:31:04",
    "user_id": 1,
    "operation_count": 3
}
3.![image](https://user-images.githubusercontent.com/46779974/51312886-bf005580-1a65-11e9-8202-cf3504583e52.png)

### NOTES(*)
Please not that when i am trying to link the simple products to the configurable product with restApi endpoint magento 2.3 which is 
rest/V1/configurable-products/:sku/child
##Input: {"childSku":"BDM-MLI-611041-A-BK"}
##Response: "true"

actual and expected result are similar and children get assigned to it's parents but when it comes to bulk api this is the exception which i am getting at **Magento\ConfigurableProduct\Model\LinkManagement** class in function **addChild** line no **122 - 125**

**Comment by LuciferStrome** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome, here is your [Magento instance](https://i-20366-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20366-2-3-develop.instances.magento-community.engineering/admin](https://i-20366-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @usamahabib786. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@usamahabib786 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@LuciferStrome Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@LuciferStrome Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97691`, `MAGETWO-97692` were created

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by usamahabib786** [comment]
> Hi @usamahabib786. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [*]  Summary of the issue
> * [*]  Information on your environment
> * [*]  Steps to reproduce
> * [*]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me $VERSION instance`
> 
> where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop).
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @usamahabib786 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [*]  yes
> * [*]  no

**Comment by usamahabib786** [comment]
Hi @engcom-backlog-nazar is there any update you wnat from me clearly i have mentioned everything required and tested it with magento 2.3 Community edition version furthermore I can provide any othere information required

**Comment by ghost** [comment]
@usamahabib786 i think this is non-issue, you may have wrong payload, or some else. now i rechecking this

**Comment by usamahabib786** [comment]
@engcom-backlog-nazar i have mentioned the payload for this bulk call. If i provide wrong payload to the endpoint before it executes the request it returns field name required message with the key mentioned as u know. The main issue is when i am going with traditional rest api endpoint for linking products its all working fine as i move to bulk api this is the message.

**Comment by usamahabib786** [comment]
@engcom-backlog-nazar But if my payload for this request is wrong, if you could please help me with providing correct payload to this endpoint for bulk api. 

endpoint: rest/async/bulk/V1/configurable-products/bySku/child

**Comment by ghost** [comment]
@usamahabib786 i'm really confused, is your  parent product have configurable  options ? 
Because i'm not able to reproduce following steps you described, the error you have, says that your's parent product  dosn't have configurable options. 
![selection_273](https://user-images.githubusercontent.com/40756439/51319825-caa04c00-1a66-11e9-9702-58a07b99fae3.png)

**Comment by usamahabib786** [comment]
@engcom-backlog-nazar i am using this endpoint with following payload to assign configurable attribute options 
endpoint : **rest/async/bulk/V1/configurable-products/bySku/options**
payload: 
[
  {
    "sku": "BDD-PRI-K1150-A-CP-C",
    "option": {
      "attribute_id": 139,
      "label": "finish",
      "position": 0,
      "is_use_default": true,
      "values": [
        {
          "value_index": 123
        },
        {
          "value_index": 125
        },
        {
          "value_index": 124
        }
      ]
    }
  }
]
you can check with it as well. I am using bulk api for creation of options and child parent link

**Comment by ghost** [comment]
@usamahabib786 I'm understand clearly,i'm following your steps, but i'm created option for configurable products in admin area,so basically your issue about correctly set product as configurable, there no issue on magento side.

**Comment by ghost** [comment]
@usamahabib786 is your product have a type of configurable ?

**Comment by usamahabib786** [comment]
@engcom-backlog-nazar Yes my product is configurable type.

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Nazar65** [comment]
@usamahabib786 i'm also not able to reproduce, seems like you have wrong flow to create configurable product.

**Comment by rddwh** [comment]
I am having exactly the same issue on a Magento 2.3 EE vanilla installation.  The rest/async/bulk/V1/configurable-products/bySku/child bulk enpoint always returns **The parent product doesn't have configurable product options**.  Calling the standard REST endpoint (rest/V1/configurable-products/{ParentSKU}/child) for exactly the same Parent/Child SKU works so there must be something wrong with the bulk API.

The steps to reproduce this are:

1.  Create a configurable product and simple child products in a single payload via the bulk framework (using the rest/async/bulk/V1/products endpoint)
2.  Create the configurable product options using the rest/async/bulk/V1/configurable-products/bySku/options endpoint
3.  Try and link the child SKUs to parents using the rest/async/bulk/V1/configurable-products/bySku/child endpoint

**Comment by Nazar65** [comment]
HI @rddwh thank for explanation i'm will recheck

**Comment by rddwh** [comment]
@Nazar65 - More detailed document with example payloads attached:

[Product Bulk API Issue.docx](https://github.com/magento/magento2/files/2786469/Product.Bulk.API.Issue.docx)

A grep search indicates the only location of the string "The parent product doesn't have configurable product options." can be found in:

**/vendor/magento/module-configurable-product/Model/LinkManagement.php**

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Nazar65** [comment]
@rddwh thank you, now i'm able to reproduce :+1:

**Comment by Nazar65** [comment]
I'm working on this

**Comment by rddwh** [comment]
Hi @Nazar65 any luck with this?

**Comment by rddwh** [comment]
@Nazar65 Slight development our end on this.  We have the RabbitMQ management plugin installed and if we force a close on the connection in between sending each payload everything works correctly.  It's feels like something is being cached and forcing a close on the connection clears it.  Hopefully this helps diagnose the issue further, we are continuing to look our end and will post any further information here.

**Comment by Nazar65** [comment]
@rddwh thank for explanations, but i'm found that product dose not have flag has_options when created wia bulk api

**Comment by rddwh** [comment]
@Nazar65 I've just tried this via the standard endpoints:

rest/V1/products
rest/V1/configurable-products/:sku/options
rest/V1/configurable-products/:sku/child

And the has_options is still 0 on the configurable:

![image](https://user-images.githubusercontent.com/40596494/52059577-16242100-2562-11e9-8470-f3dc06c85a68.png)

It's not until I save the item in the admin UI page that it gets set to 1.

**Comment by rddwh** [comment]
I've also tried to send the product payload, then the configurable product options and before posting the link child to parent manually updating the has_options and required_options to 1 before posting the payload.  It still fails.

**Comment by usamahabib786** [comment]
@rddwh hi did you able to find a way for creating configurable products with bulk api? or still waiting for magento's update? Any reply soon will be highly appreciated as i am seriously facing issue at my work due to this

thanks

**Comment by rddwh** [comment]
@usamahabib786 I've managed to get the products in using only the **rest/async/bulk/V1/products** endpoint.  The process was to upload all the simple products first, download the results from the bulk status endpoint and read the product IDs.  Once you have them you can send a payload for the configurable products and include the configurable options and child linking e.g:

`"configurable_product_options":[
   {
	  "attribute_id":"547",
	  "label":"Colour",
	  "position":0,
	  "values":[
		 {
			"value_index":205
		 }
	  ]
   },
   {
	  "attribute_id":"580",
	  "label":"Size",
	  "position":0,
	  "values":[
		 {
			"value_index":1033
		 },
		 {
			"value_index":1039
		 },
		 {
			"value_index":1042
		 },
		 {
			"value_index":1045
		 },
		 {
			"value_index":1048
		 },
		 {
			"value_index":1099
		 }
	  ]
   }
],
"configurable_product_links":[
   23125,
   23128,
   23131,
   23134,
   23137,
   23140
]
}`

I have multiple tickets open with Magento Support around RabbitMQ though as it's riddled with bugs.  Issues include payloads being ignored and sitting with a status of 4 (pending).  Some payloads being successfully sent and creating products in Magento but the bulk status returning that they are still pending and performance issues.  We did a test and uploaded 11,658 products to the production instance of a Magento Cloud Pro package (48 cores, 64GB RAM) and it took 4.5 hours to complete!  I was the only person using the instance at the time so technically had the full grunt of the box to utilise.

**Comment by usamahabib786** [comment]
@rddwh thanks for responding, its seem this is the only approach as of now until magento fixes that approach mentioned in official documentation. i am also using it. but how you were able to send this big number of products as i tried posting 3200 approx and i got exception of too big data packet from api it self.

**Comment by rddwh** [comment]
@usamahabib786 I'm sending 500 SKUs at a time.  The payloads get queued in RabbitMQ so there's no need to send them up in 1 go.

**Comment by usamahabib786** [comment]
@rddwh thanks a lot for being a help.

**Comment by korbax** [comment]
@magento-engcom-team Could you please assign this ticket to me? I will work on it.

**Comment by magento-engcom-team** [comment]
Hi @usamahabib786. Thank you for your report. 
The issue has been fixed in magento/magento2#21083 by @pedrosousa13 in 2.3-develop branch
Related commit(s):
 - [b3b6c90480942d7b56a398e33d1ce0a357358997](https://github.com/magento/magento2/commit/b3b6c90480942d7b56a398e33d1ce0a357358997)
 - [a7f03dd4f2ec0927e913c753a9b178394b5cd542](https://github.com/magento/magento2/commit/a7f03dd4f2ec0927e913c753a9b178394b5cd542)
 - [ac98b1f6cbfec75b4921af9e44f7f0546197926d](https://github.com/magento/magento2/commit/ac98b1f6cbfec75b4921af9e44f7f0546197926d)
 - [c78535dfaa1dbd594d9f6a2bca37f3fb545a1919](https://github.com/magento/magento2/commit/c78535dfaa1dbd594d9f6a2bca37f3fb545a1919)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @usamahabib786. Thank you for your report. 
The issue has been fixed in magento/magento2#22295 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [1ec99eecdcde8a702facfa1d3a5b308bae3f181c](https://github.com/magento/magento2/commit/1ec99eecdcde8a702facfa1d3a5b308bae3f181c)
 - [1b7a2e0b2396a600c50ebdef451465de2711d02f](https://github.com/magento/magento2/commit/1b7a2e0b2396a600c50ebdef451465de2711d02f)
 - [fce2445035f1650f2a26df6481e2d5c7ae339100](https://github.com/magento/magento2/commit/fce2445035f1650f2a26df6481e2d5c7ae339100)

The fix will be available with the upcoming 2.2.9 release.

**Comment by ziyaindia** [comment]
Hi All,

My URL is 

https://{base_url}/index.php/rest/V1/configurable-products/:sku/children

When I am calling above URL getting following response. Not getting any clue to fix it.

![Screenshot from 2020-08-11 10-24-25](https://user-images.githubusercontent.com/8448843/89858782-17092a80-dbbd-11ea-86ad-2dfb4f58c115.png)
