### ISSUE TITLE
Order view invoices template not display proper on ipad 

### ISSUE THREAD

**Issue by ranee2jcommerce** [magento/magento2#20373]
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. In admin Go to Sales -> Orders ->click on view -> check invoices tab under Order view

### Expected result (*)

1. 
![2019-01-17_18-18_orders](https://user-images.githubusercontent.com/18118755/51320269-50cb8b00-1a85-11e9-8007-78447885a89d.jpg)

### Actual result (*)

1. 
![2019-01-17_16-22_orders](https://user-images.githubusercontent.com/18118755/51320286-59bc5c80-1a85-11e9-9f04-a3109fba4208.jpg)

**Comment by magento-engcom-team** [comment]
Hi @ranee2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ranee2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20373-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20373-2-3-develop.instances.magento-community.engineering/admin](https://i-20373-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97693` were created

**Comment by magento-engcom-team** [comment]
Hi @ranee2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20374 by @ranee2jcommerce in 2.3-develop branch
Related commit(s):
 - [53274009c094a07f357d5739b3afd86dd9dc311a](https://github.com/magento/magento2/commit/53274009c094a07f357d5739b3afd86dd9dc311a)

The fix will be available with the upcoming 2.3.1 release.

**Comment by sidolov** [comment]
Hi @ranee2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20546 by @irajneeshgupta in 2.2-develop branch
Related commit(s):
 - [b850eb0e46fcc72036b32793f88d03d2267c771d](https://github.com/magento/magento2/commit/b850eb0e46fcc72036b32793f88d03d2267c771d)

The fix will be available with the upcoming 2.2.8 release.
