### ISSUE TITLE
Schedule Update From (Schedule Design Update) not saving When switch store view from admin

### ISSUE THREAD

**Issue by nadim2jcommerce** [magento/magento2#20377]
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. Go to admin panel
2. Admin=>Catalog=>Categories=>Navigate any category=>Schedule Design Update
3. Switch store to "default store view"
4. Click on checkbox (Checked) and save.

### Expected result (*)

1. 
![expected](https://user-images.githubusercontent.com/22003848/51328247-f3d9d000-1a98-11e9-947b-82bdc7cb469b.jpg)

### Actual result (*)

1. 
![actual](https://user-images.githubusercontent.com/22003848/51328276-03591900-1a99-11e9-9d63-a69b703bd26a.jpg)

**Comment by magento-engcom-team** [comment]
Hi @nadim2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nadim2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by yashwant2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce, here is your [Magento instance](https://i-20377-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20377-2-3-develop.instances.magento-community.engineering/admin](https://i-20377-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@yashwant2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97821` were created

**Comment by ghost** [comment]
@yashwant2jcommerce please do not touch issue if is already have assigned!

**Comment by magento-engcom-team** [comment]
Hi @nadim2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20431 by @nadim2jcommerce in 2.3-develop branch
Related commit(s):
 - [6eb9717b7a2811598a08dbdb6b3984cf36854400](https://github.com/magento/magento2/commit/6eb9717b7a2811598a08dbdb6b3984cf36854400)
 - [aa11360d6c7ef24a2fd65bc7b0302767c3dd0796](https://github.com/magento/magento2/commit/aa11360d6c7ef24a2fd65bc7b0302767c3dd0796)

The fix will be available with the upcoming 2.3.4 release.
