### ISSUE TITLE
Quikwallet Gateway Integration

### ISSUE THREAD

**Issue by meshmarketing** [magento/magento2#20401]
### Summary (*)
Not able to install this module

I extracted all the files of this module in my root directory

and run these commands:

php bin/magento setup:upgrade

But module is still not showing in module section.

I am attaching the module. Please check and help me.

[Quikwallet.zip](https://github.com/magento/magento2/files/2772946/Quikwallet.zip)

**Comment by magento-engcom-team** [comment]
Hi @meshmarketing. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@meshmarketing do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by irajneeshgupta** [comment]
@meshmarketing
github is intended for magento core issues only.

**Comment by meshmarketing** [comment]
@irajneeshgupta I know but can you help me in this.
