### ISSUE TITLE
Magento 2.3.0 “A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.” When uploading the logo/favicon image

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#20405]
### Preconditions (*)

 1.Magento 2.3.0

### Steps to reproduce (*)

1. Go to admin and try uploading the logo image.

### Expected result (*)

1. Logo image uploaded and saved.

### Actual result (*)

1. A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

**Comment by magento-engcom-team** [comment]
Hi @routbiplab. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@routbiplab do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@routbiplab  I'm closing this issue as this is already fixed in the 2.3-develop branch in this pr https://github.com/magento/magento2/pull/18851 and will be in 2.3.1

**Comment by routbiplab** [comment]
okay

**Comment by ghost** [comment]
I am talking from a non programmer prospective.
I don't understand what the right way is of solving problems, but this is far from user friendly.

I also do not know any kind of software that does not repair issues with patches except for magento.
Isn't it a good idea to put fixes and minor repairs in patches that are easy to use and implement for everyone? In stead of putting every minor bug into the next version and let a huge amount of people wait for the next version? 

It would also be nice to announce when a next version is getting released.
I see this question everywhere and it is asked hundreds of times when magento releases version 2.3.1.
No reaction not even a short reaction that it will be soon or we will announce this shortly.
It is almost a little brutal to let people swim in the mud with no clean water in sight.
Because as usual, magento 2.3.0 is with bugs again and the best answer is to wait for 2.3.1
Or is this method of working to keep the too expansive programmer alive and kicking to send out the huge bills for a little bit of work again? Because I **was** used to that.

So when is magento 2.3.1 ready and downloadable for everyone or can you give us a patch for all known minor issues?

These bugs are affecting peoples revenue (income) in  the end, time is money.

Thanks.
