### ISSUE TITLE
Sign in popup on checkout even after user is logged in

### ISSUE THREAD

**Issue by akbar-shah** [magento/magento2#20415]
### Preconditions (*)

1.  Magento 2.3.0

### Steps to reproduce (*)

1.  User logs in to their account and adds products to cart
2.  Click Proceed to Checkout either in Cart page or from the minicart 
3. Login/signin popup shows

### Expected result (*)

1. Should go to checkout screen

### Actual result (*)

1. Popup shows instructing user to log in. However the user is already logged in.

![image](https://user-images.githubusercontent.com/19673934/51409703-730de900-1b17-11e9-981a-5bca667bdce3.png)

**Comment by magento-engcom-team** [comment]
Hi @asdf93034904. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@asdf93034904 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda, here is your [Magento instance](https://i-20415-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20415-2-3-develop.instances.magento-community.engineering/admin](https://i-20415-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cedarvinda** [comment]
@asdf93034904 Thankyou for reporting but it's not reproduce.

**Comment by akbar-shah** [comment]
Would you have any idea why its happening? I disabled all of my modules and it still occurs.

**Comment by xtremevision** [comment]
Still happening for me as well, Magento 2.3.5-p1, customer is logged in, but I am still getting the auth pop-up.

**Comment by Eddcapone** [comment]
This still happens to me on 2.4.2 Enterprise. I am logged in and click on "To checkout" button but this pop up is showing instead.
