### ISSUE TITLE
Mail Sending from Default Server

### ISSUE THREAD

**Issue by meshmarketing** [magento/magento2#20422]
### Summary (*)
I Have magento 2.2.7 version. I updated all the email setting in Configuration but still all the mail is sent through the server's mail address.

Please check this Issue.

### Proposed solution
I searched on github and found that after disabling amazon modules it will work. But i already disabled all the amazon modules and still having the same problems.

**Comment by magento-engcom-team** [comment]
Hi @meshmarketing. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@meshmarketing do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by milindsingh** [comment]
Hi @meshmarketing 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

(Note: your `sendmail` is not set up, which results in failure in sending mails)

**Comment by hostep** [comment]
@meshmarketing: this sounds like a duplicate of #14952

There is a fix in the works in: #18472 for Magento 2.2.x.
For Magento 2.3.x, this fix was recently approved: #18471
