### ISSUE TITLE
Product URL duplicate when changing visibility via mass action

### ISSUE THREAD

**Issue by laurentplenet** [magento/magento2#20434]
### Preconditions (*)
This is about the Magento 2.2.6 version. Tried on a fresh magento 2 installation, and others 2.2.6 used on production mode.

### Steps to reproduce (*)
**Step 1**. Create a product with the following URL (or any of your choice) : « mon-produit-de-test » - Visible product (catalog, search)
**Step 2**. Create a second product with the exact same values and URL « mon-produit-de-test-1 »
**Step 3**. Create a third one with the same values but invisible individually then URL « mon-produit-de-test »

### Expected result (*)
**On step 1.** - Nothing special
**On step 2.** - If you put the same URL as the step 1, an error message appears teeling you that there's already a product with the same URL ... Logic!
**On step 3.** - Even if the product is invisible, this shouldn't be saved because there's already a product with the same URL. There's no error message.

### Actual result (*)
If you now go to mass product action, then change de visibility of your Product #3 that have the same URL of your Product #1, you got duplicated URL for those 2 products. You can try to change the URL of your product #2 to the URL of product #1 and it works too. In the end, you got duplicated product URLs problem.

**Did anyone has a solution for this ? Any way to fix this in 2.2.6 version ?**

Regards,
Laurent

**Comment by magento-engcom-team** [comment]
Hi @laurentplenet. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@laurentplenet do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97849`, `MAGETWO-97850` were created

**Comment by magento-engcom-team** [comment]
Hi @VitaliyBoyko. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by VitaliyBoyko** [comment]
During an investigation of the issue, I've found out that the observer (event `catalog_product_save_after`) app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:58 is responsible for the processing and validating URL rewrite. 
The mentioned observer checks the value of `isVisibleInSiteVisibility` attribute (see line 68), if the value is positive, a URL rewrite being processed and saved to the `url_rewrite` DB table. If URL key attribute value is set, URL rewrite being created based on it, otherwise, URL rewrite being autogenerated based on the product name. The Url key EAV attribute being saved to the DB table  `catalog_product_entity_varchar` on Product Save action,  either way, the product is visible or not.

The mass action saves directly EAV attributes, so the product model `catalog_product_save_after action` not being dispatched  ( see
app/code/Magento/Catalog/Controller/Adminhtml/Product/Action/Attribute/Save.php:115) and URL rewrite not being created that cause data inconsistency. In the end, we have got a product with URL key attribute but with no URL rewrite.

The issue solution might be to observe the saving attribute via mass action, creating/deleting URL rewrites appropriately on the visibility attribute change. 

@magento-engcom-team
@ishakhsuvarov 
What do you think?

**Comment by laurentplenet** [comment]
I've read the entire process you explain up here and agree with this, but How to process ? @VitaliyBoyko

**Comment by VitaliyBoyko** [comment]
@laurentplenet Feel free to check the referenced PR above this comment. If those changes are acceptable for you, feel free to copy them into your project.

**Comment by magento-engcom-team** [comment]
Hi @riccardougolini. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @laurentplenet. Thank you for your report. 
The issue has been fixed in magento/magento2#20774 by @VitaliyBoyko in 2.3-develop branch
Related commit(s):
 - [24382e3eb968d13e4a86955cbdc2966b989afe1c](https://github.com/magento/magento2/commit/24382e3eb968d13e4a86955cbdc2966b989afe1c)
 - [4d18c9a92cd8f1acdd780ce933f2860e7d092f7f](https://github.com/magento/magento2/commit/4d18c9a92cd8f1acdd780ce933f2860e7d092f7f)
 - [6a5776c46396810875f46e986e56594e8e5ea30c](https://github.com/magento/magento2/commit/6a5776c46396810875f46e986e56594e8e5ea30c)
 - [f2088d9b59d0fcf6d521d510fcc37d11e3308f03](https://github.com/magento/magento2/commit/f2088d9b59d0fcf6d521d510fcc37d11e3308f03)
 - [4edec382f3517f64284ba45fb341e4bcce1745ab](https://github.com/magento/magento2/commit/4edec382f3517f64284ba45fb341e4bcce1745ab)
 - [a8d1dc042d663adf6b1667192ba3f044c57d51f1](https://github.com/magento/magento2/commit/a8d1dc042d663adf6b1667192ba3f044c57d51f1)
 - [5687704ffdde8534164d439f387ebc09eaa004c8](https://github.com/magento/magento2/commit/5687704ffdde8534164d439f387ebc09eaa004c8)
 - [c865bdc25ff73168e2c2e0e093787ed766a2d068](https://github.com/magento/magento2/commit/c865bdc25ff73168e2c2e0e093787ed766a2d068)
 - [1c608d7b54bf08d4fe592c2a0153502c9a9527d4](https://github.com/magento/magento2/commit/1c608d7b54bf08d4fe592c2a0153502c9a9527d4)
 - [a80943f529a337b36f59d3964a8448816f5e2532](https://github.com/magento/magento2/commit/a80943f529a337b36f59d3964a8448816f5e2532)
 - [a8d9be1c4f617a3ff0312f433f080b67b41ed3b6](https://github.com/magento/magento2/commit/a8d9be1c4f617a3ff0312f433f080b67b41ed3b6)

The fix will be available with the upcoming 2.3.2 release.
