### ISSUE TITLE
Variable-length argument lists are not supported by Interceptor generation

### ISSUE THREAD

**Issue by xi-ao** [magento/magento2#20430]
### Preconditions (*)

On Magento 2.0/2.1/2.2.
1. Create an interceptable class, for example `\Foo\Bar\Controller\Index` (extending `\Magento\Framework\App\Action\Action`)
2. Add a method using the [_variable-length argument list_](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) notation:
```
    public function hook($hook, &...$params)
    {
        if (method_exists($this, $hook)) {
            return call_user_func_array([$this, $hook], $params);
        }
    }
```

### Steps to reproduce (*)

1. Access this controller to trigger the generation of the `Interceptor` class in developer mode.

### Expected result (*)

1. The controller should render what's defined in the `execute()` method.

### Actual result (*)

```
Warning: Declaration of Foo\Bar\Controller\Index\Interceptor::hook($hook, &$params) should be compatible with Foo\Bar\Controller\Index::hook($hook, &...$params) in /var/www/var/generation/Foo/Bar/Controller/Index/Interceptor.php on line 8
#0 /var/www/var/generation/Foo/Bar/Controller/Index/Interceptor.php(8): MBaro\Framework\App\ErrorHandler->handler(2, 'Declaration of ...', '/var/www/mBar...', 8, Array)
#1 /var/www/vendor/mBaro/framework/Code/Generator/Io.php(158): include('/var/www/mBar...')
#2 /var/www/vendor/mBaro/framework/Code/Generator.php(108): MBaro\Framework\Code\Generator\Io->includeFile('/var/www/mBar...')
#3 /var/www/vendor/mBaro/framework/Code/Generator/Autoloader.php(35): MBaro\Framework\Code\Generator->generateClass('Foo\\Bar\\Con...')
#4 [internal function]: MBaro\Framework\Code\Generator\Autoloader->load('Foo\\Bar\\Con...')
#5 [internal function]: spl_autoload_call('Foo\\Bar\\Con...')
#6 /var/www/vendor/mBaro/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Foo\\Bar\\Con...')
#7 /var/www/vendor/mBaro/framework/ObjectManager/Definition/Runtime.php(44): MBaro\Framework\Code\Reader\ClassReader->getConstructor('Foo\\Bar\\Con...')
#8 /var/www/vendor/mBaro/framework/ObjectManager/Factory/Dynamic/Developer.php(71): MBaro\Framework\ObjectManager\Definition\Runtime->getParameters('Foo\\Bar\\Con...')
#9 /var/www/vendor/mBaro/framework/ObjectManager/ObjectManager.php(57): MBaro\Framework\ObjectManager\Factory\Dynamic\Developer->create('Foo\\Bar\\Con...', Array)
#10 /var/www/vendor/mBaro/framework/App/ActionFactory.php(37): MBaro\Framework\ObjectManager\ObjectManager->create('Foo\\Bar\\Con...')
#11 /var/www/vendor/mBaro/framework/App/Router/Base.php(300): MBaro\Framework\App\ActionFactory->create('Foo\\Bar\\Con...')
#12 /var/www/vendor/mBaro/framework/App/Router/Base.php(161): MBaro\Framework\App\Router\Base->matchAction(Object(MBaro\Framework\App\Request\Http), Array)
#13 /var/www/vendor/mBaro/framework/App/FrontController.php(50): MBaro\Framework\App\Router\Base->match(Object(MBaro\Framework\App\Request\Http))
#14 [internal function]: MBaro\Framework\App\FrontController->dispatch(Object(MBaro\Framework\App\Request\Http))
#15 /var/www/vendor/mBaro/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#16 /var/www/vendor/mBaro/framework/Interception/Chain/Chain.php(70): MBaro\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#17 /var/www/vendor/mBaro/framework/Interception/Interceptor.php(136): MBaro\Framework\Interception\Chain\Chain->invokeNext('MBaro\\Framewo...', 'dispatch', Object(MBaro\Framework\App\FrontController\Interceptor), Array, 'install')
#18 /var/www/vendor/mBaro/framework/Module/Plugin/DbStatusValidator.php(69): MBaro\Framework\App\FrontController\Interceptor->MBaro\Framework\Interception\{closure}(Object(MBaro\Framework\App\Request\Http))
#19 [internal function]: MBaro\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(MBaro\Framework\App\FrontController\Interceptor), Object(Closure), Object(MBaro\Framework\App\Request\Http))
#20 /var/www/vendor/mBaro/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#21 /var/www/var/generation/MBaro/Framework/App/FrontController/Interceptor.php(26): MBaro\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /var/www/vendor/mBaro/framework/App/Http.php(115): MBaro\Framework\App\FrontController\Interceptor->dispatch(Object(MBaro\Framework\App\Request\Http))
#23 /var/www/vendor/mBaro/framework/App/Bootstrap.php(258): MBaro\Framework\App\Http->launch()
#24 /var/www/pub/index.php(37): MBaro\Framework\App\Bootstrap->run(Object(MBaro\Framework\App\Http))
#25 {main}
```

Because in the interceptor, the method has been declared as follows:
```
    /**
     * {@inheritdoc}
     */
    public function hook($hook, &$params)
    {
        $pluginInfo = $this->pluginList->getNext($this->subjectType, 'hook');
        if (!$pluginInfo) {
            return parent::hook($hook, $params);
        } else {
            return $this->___callPlugins('hook', func_get_args(), $pluginInfo);
        }
    }
```

**Comment by magento-engcom-team** [comment]
Hi @xi-ao. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@xi-ao do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by LuciferStrome** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome, here is your [Magento instance](https://i-20430-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20430-2-3-develop.instances.magento-community.engineering/admin](https://i-20430-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @xi-ao    thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by xi-ao** [comment]
IMHO this is not a "feature", but a bug.

Anyway.

For those who could stumble upon this too, it's due to an outdated version of Zend Code, which is the library reponsible for generating Interceptors in M2.

Check out the latest version here: https://github.com/zendframework/zend-code/blob/master/src/Generator/ParameterGenerator.php (where `$variadic` is present and is what we need)

**Comment by ghost** [comment]
@xi-ao https://github.com/magento/magento2/pull/16081

**Comment by xi-ao** [comment]
Nice, thanks! :+1:
