### ISSUE TITLE
Customer Information reward points notifications missaligned

### ISSUE THREAD

**Issue by priti2jcommerce** [magento/magento2#20444]
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. Go to admin >> Customer >>All customer
2. Edit 
3. click on Reward Points

### Expected result (*)

1. 
![image](https://user-images.githubusercontent.com/18118695/51476650-242cb180-1dac-11e9-9697-413c535945d1.png)

2.

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/18118695/51476609-01020200-1dac-11e9-831e-9929e7013773.png)

2.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@priti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me $VERSION instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop  instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop  instance for you

**Comment by irajneeshgupta** [comment]
hi @priti2jcommerce 

GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by priti2jcommerce** [comment]
hi @irajneeshgupta ,

Thanks for the update, I have created pull request for the changes. because the common file used for the community and enterprise.

**Comment by sdzhepa** [comment]
Hello @priti2jcommerce 

Thank you for contribution and collaboration!

I checked this issue on the latest `2.3-develop` branch on the Magento Commerce version.
And this issue was already fixed and cannot be reproduced by provided steps from the description

![20444](https://user-images.githubusercontent.com/3409584/54953994-9427f700-4f17-11e9-9940-c45484c1589b.jpg)
