### ISSUE TITLE
In Admin when click on REPORTS block in tablet view,fourth column is not  proper it is cutting 

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#20445]
In Admin when click on REPORTS block in tablet view,fourth column is not  proper it is cutting 

### Preconditions (*)

1.Magento version 2.3
2.Tablet view

### Steps to reproduce (*)

1.Go to admin click on REPORTS from left menu in tablet view
2.fourth column is not proper

### Expected result (*)
![2019-01-21_19-07_dashboard - magento admin](https://user-images.githubusercontent.com/18118638/51477896-c7cb9100-1daf-11e9-8ea8-84064be71fb7.jpg)

### Actual result (*)
![2019-01-21_18-22_dashboard - magento admin](https://user-images.githubusercontent.com/18118638/51477790-8804a980-1daf-11e9-8cd5-e2a567dccceb.jpg)

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team,
Please give me magento 2.3.x

**Comment by milindsingh** [comment]
Hi @dipti2jcommerce @engcom-backlog-nazar  I think the `Magento Admin` is currently not responsive or device friendly rather than on desktop view.

**Comment by ghost** [comment]
@milindsingh this already fixed, give 5 minutes

**Comment by ghost** [comment]
@dipti2jcommerce this is duplicate to this -> https://github.com/magento/magento2/issues/18687 :)

**Comment by ghost** [comment]
@dipti2jcommerce but PR was closed https://github.com/magento/magento2/pull/19560
