### ISSUE TITLE
Index with elasticsearch bug. [Issue: Clear Description]

### ISSUE THREAD

**Issue by vaggelis2018** [magento/magento2#20462]
### Preconditions (*)
1. Magento Version 2.3
2. Elasticsearch 5.6

### Steps to reproduce (*)
1. Created a product only with required fields
2. run bin/magento indexer:reindex in console

### Expected result (*)
1. Index data with elasticsearch

### Actual result (*)
1. It throws an error the error below
Design Config Grid index has been rebuilt successfully in 00:00:02
Customer Grid index has been rebuilt successfully in 00:00:01
Category Products index has been rebuilt successfully in 00:00:01
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:01
Product EAV index has been rebuilt successfully in 00:00:01
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Catalog Search indexer process unknown error:
{"error":"MapperParsingException[Wrong value for index [false] for field [country_of_manufacture]]","status":400}

It happens only if i have products and event if i tried to add manufacture country in product the error keep pops up and indexing status of catalog search is always on required re index.

**Comment by magento-engcom-team** [comment]
Hi @vaggelis2018. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vaggelis2018 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by vaggelis2018** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vaggelis2018. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by vaggelis2018** [comment]
@magento-engcom-team ok thanks

**Comment by magento-engcom-team** [comment]
Hi @vaggelis2018, here is your [Magento instance](https://i-20462-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20462-2-3-develop.instances.magento-community.engineering/admin](https://i-20462-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vaggelis2018** [comment]
@magento-engcom-team   It is not possible to test it because my elasticsearch server is local.

**Comment by amol2jcommerce** [comment]
Hi @vaggelis2018 

I'm not able to reproduce 2.3. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by vaggelis2018** [comment]
@amol2jcommerce @engcom-backlog-nazar note that is a vamilla magento install and i have not touched anything in the code or in the modules.

**Comment by ghost** [comment]
Hello @vaggelis2018 . I believe that there is a mistake in Magento DevDocs. Please look here for additional details [https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html)

It said that only 5.2.x is supported. I understand that you can provide a links where it said that 5.x is supported, but that's mistake. We are working on it.

Try to use Magento with ES 5.2.2. Feel free to reopen if this step won't help you.
