### ISSUE TITLE
Bug/feature sales email sending

### ISSUE THREAD

**Issue by zhartaunik** [magento/magento2#20473]
Magento 2.2.7

The issue was reproduced by me only with installed 3rd party extension which is responsible for mail sending via API. **andelux/mailgun-magento2**

After following changes were applied:
https://github.com/magento/magento2/commit/9a7c9e553b1c9814907105388bffc2e8a91353a5?diff=split
we have faced with an issue.

If you have a look at: 
magento/module-sales/Model/Order/Email/SenderBuilder.php

You may see two transports:

```
    /**
     * @var TransportBuilder
     */
    protected $transportBuilder;

    /**
     * @var TransportBuilderByStore
     */
    private $transportBuilderByStore;
```

Each of them has object `\Magento\Framework\Mail\Message $message`

After commit from above **$transportBuilderByStore** now has it's unique **$message** object which differs from message that inside **$transportBuilder**.

The question is: 
Is it expected result or not? Should we inject $message object or create it by factory?

How it affects on overall flow:
When system assign sender on message object here:
`\Magento\Sales\Model\Order\Email\SenderBuilder::configureEmailTemplate`
Sender was assigned on both messages (which is inside **transportBuilder** and **transportBuilderByStore**).
But starting from 2.2.7 there are two different $message objects. And **$transportBuilder->message** does not have sender anymore

**Comment by magento-engcom-team** [comment]
Hi @zhartaunik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@zhartaunik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @zhartaunik thank you for your report, yes this is expected behavior, please look at this commit https://github.com/magento-engcom/magento2ce/commit/523b0464966f81f1f01aa13073092bfddf363219

**Comment by zhartaunik** [comment]
Thanks for the response.
Looks like due insufficient privileges I'm unable to see that commit (I'm getting 404).
Is there another way to view it somewhere else? Diff/patch?

**Comment by ghost** [comment]
@zhartaunik ok, just recheck your issue on 2.3-dev branch, they are deprecated
