### ISSUE TITLE
[Back-Office issue] Incorrect date in active date filter after reloading page

### ISSUE THREAD

**Issue by yaroslav-drach** [magento/magento2#20479]
### Preconditions (*)
1. Magento ver. 2.2.5

### Steps to reproduce (*)
1. Go to "Back-Office > SALES > Orders" or any page with date filter.
2. Select "Filters".
3. Set value in any date filter. For example, use value 01/10/2016 (Jan 10, 2016).
4. Apply Filters.
5. Reload page with F5 (or go to view order, then back)
6. You can see incorrect date 10/20/2001

### Expected result (*)
1. The date in active filters is not changed after reloading page.

### Actual result (*)
1. The date in active filters is incorrect: 10/20/2001
2. The numbers of the date are cyclically shifted to the left (please, see attached image).

![image](https://user-images.githubusercontent.com/46928765/51541300-269d1300-1e61-11e9-9799-e5b422f82276.png)

**Comment by magento-engcom-team** [comment]
Hi @yaroslavdrach. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@yaroslavdrach do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @yaroslavdrach thank you for you report this issue has already fixed in 2.2 and 2.3-dev branch and, available on 2.2.7 release
