### ISSUE TITLE
Base prices in admin order create (multistore)

### ISSUE THREAD

**Issue by kerlama** [magento/magento2#20496]
### Preconditions (*)

1. Magento 2.1.6 clean install with sample data + one more store created
2. PHP 7.0.32

### Steps to reproduce (*)

1. Create another website/store/storeview within magento, lets say US
2. Assign all products to US website
3. Configure US store to have US Dollar base price and default store to be GBP
4. Under Catalog > Price set Catalog price scope to Website
5. Set US price for one product
6. Proceed creating new order from admin
7. Select US Store view and customer
8. Add product which have different US price
9. Click on Update items and quantities button

### Expected result (*)

1. US prices should be kept in "items ordered"
![screenshot_15](https://user-images.githubusercontent.com/4161312/51598787-8dbcd500-1efe-11e9-9582-f523b799632e.jpg)

$100 is US price, which is correct, but when you click on the update items and quantities button, you will see base price, in GBP with $ currency sign.

### Actual result (*)

![screenshot_16](https://user-images.githubusercontent.com/4161312/51598838-a7f6b300-1efe-11e9-816e-ce0f7fdd75d9.jpg)

$34.00 is actually 34.00 GBP.

![issue](https://user-images.githubusercontent.com/4161312/51599036-0754c300-1eff-11e9-84f2-47234ca81a6c.gif)

**Comment by magento-engcom-team** [comment]
Hi @kerlama. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kerlama do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @kerlama   i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.
