### ISSUE TITLE
Product customizable options issue

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#20497]
### Preconditions (*)
1. Magento 2.3-develop
2. 

### Steps to reproduce (*)
1. Open the product page (new or existing one) in Admin Panel
2. Add several new Customizable Options

### Expected result (*)

1. The new added options should have a bottom border, for having a good look
![xnip2019-01-23_12-05-33](https://user-images.githubusercontent.com/15868188/51598929-3a9b5000-1f07-11e9-9eab-3affa00e0393.jpg)

### Actual result (*)

1. The border is missing for the customizable options
![xnip2019-01-23_12-00-08](https://user-images.githubusercontent.com/15868188/51598831-058efd80-1f07-11e9-8a83-4d701a676225.jpg)

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@eduard13 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@irajneeshgupta Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97882` were created

**Comment by rogyar** [comment]
@irajneeshgupta thank you for the confirmation. Does it really take 1 minute for you to reproduce the issue?

**Comment by irajneeshgupta** [comment]
> @irajneeshgupta thank you for the confirmation. Does it really take 1 minute for you to reproduce the issue?

@rogyar 
yeah, i have local setup of dev-2.3-develop , it takes hardly 1 min to view an item and click on Customizable Options ->add options. 

@eduard13
I assumed that it will take sometime to create PR of it.
 
@engcom-backlog-nazar 

https://i-20487-2-3-develop.instances.magento-community.engineering/admin
all 2.3-develop instance are redirecting to 2.2-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#20498 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [6f10b643f4e8413a2837e851addac265d6ffca1c](https://github.com/magento/magento2/commit/6f10b643f4e8413a2837e851addac265d6ffca1c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-20497-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20497-2-2-develop.instances.magento-community.engineering/admin](https://i-20497-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#20821 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [06f74305096998fef2434966adec7308fbc20bf8](https://github.com/magento/magento2/commit/06f74305096998fef2434966adec7308fbc20bf8)

The fix will be available with the upcoming 2.2.9 release.
