### ISSUE TITLE
Create a new product attribute form. Styles for the swatch input looks broken.

### ISSUE THREAD

**Issue by DenisSaltanahmedov** [magento/magento2#20513]
### Preconditions (*)
1. Magento 2.3
2. Luma Theme

### Steps to reproduce (*)
1. In Admin go to Stores > Attributes > Product > Add New Attribute
2. In "Attribute Properties" > Catalog Input Type for Store Owner > Choose "Text Swatch"
3. In Manage Swatch (Values of Your Attribute) > Add Swatch

### Expected result (*)
1. Styles for the swatch input looks good
![expected-result](https://user-images.githubusercontent.com/7371730/51603825-8f44c800-1f13-11e9-8ed7-d1977afdbef4.png)

### Actual result (*)
1. Styles for the swatch input are broken
![actual-result](https://user-images.githubusercontent.com/7371730/51603878-ba2f1c00-1f13-11e9-85b2-d28a52f150e1.png)

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DenisSaltanahmedov do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@nainesh2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97888` were created

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by SyntaxKay** [comment]
@magento-engcom-team Please give me magento-2.3 instance

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-20513-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20513-2-2-develop.instances.magento-community.engineering/admin](https://i-20513-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @DenisSaltanahmedov thank you for you report, this issue has already fixed in 2.3-develop branch, so i'm closing this.
