### ISSUE TITLE
Deadlock errors during product save or trying to index product price

### ISSUE THREAD

**Issue by denzyk** [magento/magento2#20525]
### Preconditions

1. Magento 2.2.6 Community
2. PHP 7.0.33 (running as php-fpm)
3. MariaDB 10.1.37
4. Session storage: Redis

### Steps to reproduce

1. Add many products to DB (we have around 22K at the moment)
2. Cron options:
![image](https://user-images.githubusercontent.com/12296157/51611633-5ebb5900-1f28-11e9-86e7-127cec3fb051.png)
![image](https://user-images.githubusercontent.com/12296157/51611660-6f6bcf00-1f28-11e9-89db-8f5c6d68dad4.png)
3. Change product's price in admin and save

### Expected result

1. Product is saved
2. Scheduled cron task `indexer_reindex_all_invalid` succeeds

### Actual result

1. Quite often product save fails with error message "Catalog rule indexing failed"
2. Cron task `indexer_reindex_all_invalid` fails with error:
```mysql
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: UPDATE `catalog_product_index_price_temp` AS `i`
 INNER JOIN `catalog_product_index_website` AS `cpiw` ON cpiw.website_id = i.website_id
 INNER JOIN `catalogrule_product_price` AS `cpp` ON cpp.product_id = i.entity_id AND cpp.customer_group_id = i.customer_group_id AND cpp.website_id = i.website_id AND cpp.rule_date = cpiw.website_date
SET `i`.`final_price` = LEAST(final_price, IFNULL(cpp.rule_price, i.final_price)), `i`.`min_price` = LEAST(min_price, IFNULL(cpp.rule_price, i.min_price))
WHERE (i.entity_id IN (25001, 25002, 25003, <cut...>, 27955))```

Number of `entity_id` in the `IN (..)` statement that we observe is around 2900-4500.

**Comment by magento-engcom-team** [comment]
Hi @denzyk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@denzyk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @denzyk thank you for you report, i;m closing this as duplicate to this -> https://github.com/magento/magento2/issues/8933
