### ISSUE TITLE
checkoutSession->getLastRealOrderId() returns null in controller occassionally when Varnish enabled

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#20520]
### Summary (*)
I have developed a custom payment method which implements card payments. As part of the process, the user is re-directed to a 3dsecure bank URL and then returned to a Magento controller.

After returning from the bank in my controller - sometimes, but not always, $this->checkoutSession->getLastRealOrderId() returns null, which means in my controller I do not know which order is being returned so I can continue the final checkout process.

This problem only seems to occur when caching is enabled, in this case Varnish.

In my controller I have::

```
$page = $this->pageFactory->create();
$page->setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0', true);
```

If getLastRealOrderId() is null, I re-direct the customer to $this->_redirect('checkout/cart'); and return $page;

### Examples (*)
In my method renderer js:

```
return ccFormComponent.extend({
defaults: {
                redirectAfterPlaceOrder: false /* for 3d secure */
            },
            afterPlaceOrder: function () {
                window.location.replace(url.build(window.checkoutConfig.payment.realex_remote.redirectUrl));
            },
```

redirectUrl is set to my custom controller in Magento 2.

If 3dsecure is disabled through a admin setting, redirectUrl is the checkout/onepage/success url. 
If 3dsecure is enabled, I am re-directed to my controller which loads the template & block with hidden payment 3dsecure provider form (which has cacheable="false"), which submits itself, then re-directed to the bank.

After returning from the bank, the user hits my controller again, which checks the response and if successful updates order status etc. and then re-directs the user to the success page.

This re-redirect is done in **afterPlaceOrder**, can this be done before **placeOrder** for example, would this fix getLastRealOrderId() being null?

I would need the increment id to give to the payment provider.

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @craigcarnell can you please look -> https://github.com/magento/magento2/issues/17161#issuecomment-408127149

**Comment by ghost** [comment]
@craigcarnell i'm not able to reproduce following steps you described, please see comment mentioned later, this really may cause this issue.
Best regards.

**Comment by cscd98** [comment]
@engcom-backlog-nazar Wouldn't that result in a wrong increment id rather than no increment id being returned?

Is there an ETA to fix 17161?

**Comment by theBigBlackEyes** [comment]
How are you Craig :)
I miss you and Alex so much...

**Comment by rossparachute** [comment]
Hi @craigcarnell ,

I know this is a bit of a long shot as this issue is from 2 years ago but we've had similar pains for about a year or so. We've seen others with the same problem but no fixes thus far.

Was there ever a Varnish configuration or likewise that resolved this for you?

No worries if not, bit of a hail mary effort really.

Cheers,
Ross
