### ISSUE TITLE
[Admin] Configurable product variations table cell labels wrong position

### ISSUE THREAD

**Issue by vasilii-b** [magento/magento2#20527]
### Preconditions (*)
1. Magento 2.3-develop
2. Configurable product with variations

### Steps to reproduce (*)
1. Open a configurable product with variations
2. Scroll down to the variations table

### Expected result (*)
You are able to see the variations table without any unnecessary text next to "Current variations" heading.
![xnip2019-01-23_16-47-44](https://user-images.githubusercontent.com/13456702/51615164-db9e0100-1f2f-11e9-98a0-ec396bbb50a4.jpg)

### Actual result (*)
![xnip2019-01-23_14-34-51](https://user-images.githubusercontent.com/13456702/51615234-025c3780-1f30-11e9-9baa-bbaa984b0438.jpg)

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vasilii-b do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@eduard13 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97897` were created

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your report. 
The issue has been fixed in magento/magento2#20528 by @vasilii-b in 2.3-develop branch
Related commit(s):
 - [af11e87e2d01c293cd7b59e2731631f6662def06](https://github.com/magento/magento2/commit/af11e87e2d01c293cd7b59e2731631f6662def06)
 - [ed2a80c45a3dee49380f8c6cc9cd971f2045c121](https://github.com/magento/magento2/commit/ed2a80c45a3dee49380f8c6cc9cd971f2045c121)
 - [d9c962ffe0088fbad9b0464b014ccd95f53870d5](https://github.com/magento/magento2/commit/d9c962ffe0088fbad9b0464b014ccd95f53870d5)
 - [e8adeca7746b332dc6e16270d1d389fc61c14a85](https://github.com/magento/magento2/commit/e8adeca7746b332dc6e16270d1d389fc61c14a85)

The fix will be available with the upcoming 2.3.2 release.

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-20527-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20527-2-2-develop.instances.magento-community.engineering/admin](https://i-20527-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your report. 
The issue has been fixed in magento/magento2#21691 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [adf4425136c276f0e482f154198c4f39cc15d00d](https://github.com/magento/magento2/commit/adf4425136c276f0e482f154198c4f39cc15d00d)

The fix will be available with the upcoming 2.2.9 release.
