### ISSUE TITLE
Problems Importing Product CSV file

### ISSUE THREAD

**Issue by BartPlevoets** [magento/magento2#20537]
Problems Importing Product CSV file   
Dear Sir, madam
 
I have a big issue with reading my csv file.
When i do a export and open it in Google doc or Excel the price and qty not show correct.
Magento 2.2.6
 
https://docs.google.com/spreadsheets/d/1uJ_CLLGG1WLi_udJTIEHQhx8nCLCHSTxuO-c3kw1XaM/edit?usp=sharing
 
Can you help me please?
 
Greetings Bart

**Comment by magento-engcom-team** [comment]
Hi @BartPlevoets. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@BartPlevoets do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by milindsingh** [comment]
Hi @BartPlevoets
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
