### ISSUE TITLE
Varnish (with apache plus mod expires) will cache all your GET API requests for 1 year

### ISSUE THREAD

**Issue by mmenozzi** [magento/magento2#20538]
Given the preconditions described below all GET API requests are cached for 1 year!

### Preconditions (*)
1. Tested on Magento 2.2.5 but I'm sure that all versions are affected
2. Varnish (tested with version 5.2) setup as described in documentation: https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish.html
3. Apache as backend webserver as described in documentation: https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-configure.html
4. Apache mod expires enabled (https://httpd.apache.org/docs/2.4/mod/mod_expires.html)

### Steps to reproduce (*)
1. Make any `GET` API request. For example: `curl -i -X GET "http://my-store.test/rest/all/V1/directory/currency" -H "accept: application/json"` to get the list of store currencies.
2. Take note of the items returned by the API
3. From the Magento admin panel add a new store view with a different currency and its exchange rate
4. Make the same request again `curl -i -X GET "http://my-store.test/rest/all/V1/directory/currency" -H "accept: application/json"`

### Expected result (*)
1. You'd expect to get the new currency in the API response

### Actual result (*)
1. You get the same currencies as the first API request
2. If you restart Varnish and make the same request again you'll see the new currency in the response

This happens because Varnish caches the first response.
This happens because the backend (Apache) returns the `Cache-Control: max-age=31536000` response header.
This happens because Apache with mod expires enabled executes these lines from the standard `.htaccess` file provided by Magento (the same happens for the `pub/.htaccess` file): https://github.com/magento/magento2/blob/2.3-develop/.htaccess#L195

IMHO it's not a good idea to cache every content for 1 year except `text/html` and `text/plain`. I'd do the opposite: no cache for anything by default and cache only for expected content types like images, CSS, JS, etc...

**Comment by magento-engcom-team** [comment]
Hi @mmenozzi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mmenozzi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by milindsingh** [comment]
@mmenozzi I tried and was able to reproduce the issue, I am curious that it **only happens if a new store is added**, and No matter what I do, the currencies are only displayed for `Default Store` only.

1. As the API describes, `Get currency information for the store.` but no way to add `store_id` as a param.
2. For default store, the currency is updated instantly, so it may not be due to `varnish` or `mod_expires`.

I am confirming the issue as the currency API is not delivering all allowed `currencies` no matter what the cause is.

**Comment by magento-engcom-team** [comment]
@milindsingh Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97909`, `MAGETWO-97910` were created

**Comment by mmenozzi** [comment]
@milindsingh the currency API is only an example. The cache for 1 year problem occurs with every GET API request.

The fact of the matter is how expires directives are in the htaccess file. It’s not only an API problem. Given those directives every response  with a content type different than text/plain or text/html (for example a PDF) will be cached for 1 year. And this could be a problem if the response is dynamic (for example a PDF generated on the fly with data subject to change).

**Comment by magento-engcom-team** [comment]
Hi @mmenozzi. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24327` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
