### ISSUE TITLE
Can't change custom options prices per store view

### ISSUE THREAD

**Issue by Tohmas** [magento/magento2#20550]
I can't change custom option prices according to store view for my simple products.
I'm using dropdown custom options...

### Preconditions (*)

Magento EE 2.2.6
PHP 7.1.23

### Steps to reproduce (*)

Create multiple store views for the same website
Create a simple product and a custom dropdown option
Set +20€ fot the first option for the default store view.
Change store view to the second one and try to change for instance 20€ to 11,5€ fot the same option.
The change is saved for all options instead of only the second one....

### Expected result (*)

The price for the second store view product option should be 11,5€ and not 20€

**Comment by magento-engcom-team** [comment]
Hi @Tohmas. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Tohmas do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Tohmas** [comment]
Magento EE ver. 2.2.6

**Comment by Tohmas** [comment]
@magento-engcom-team give me {Magento EE 2.2.6} instance

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by saphaljha** [comment]
Hello @Tohmas, Please submit your issue in Magento 2 EE repository of github. Also, Please have a look on my comments below.

Magento does not allow setting a per store price. You can do this on a per website basis follow below step.
To do so, you need to go to
**System->Configuration->Catalog->Catalog**

Then in the tab "Price", set price scope to Website instead of global.

On the product edit page, you can then set the scope on the upper left side to your website and then enter a per website price.

Magento does not allow setting a per store price. However, there are some extensions which will allow you a per store price.

Please feel free to reopen this ticket.
