### ISSUE TITLE
Can't save product with Customizable Options on Admin

### ISSUE THREAD

**Issue by levinskipolish** [magento/magento2#20551]
### Preconditions (*)

1.Magento version 2.2.6
2.Linux cloudhost - GNU/Linux

### Steps to reproduce (*)

1. When Customizable Options are added or imported from a different product it can't be saved  
2. For the products without this options saving changes are fine

### Expected result (*)

1. I just need to save and see the changes reflecting on product grid as well as in product pages 

### Actual result (*)

1.<img width="2560" alt="screen shot 2019-01-23 at 6 18 58 pm 2" src="https://user-images.githubusercontent.com/26575900/51643717-7d771b00-1f3b-11e9-8e9d-d72a25d66b9a.png">

**Comment by magento-engcom-team** [comment]
Hi @levinskipolish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@levinskipolish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by levinskipolish** [comment]
@magento-engcom-team give me $VERSION instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by saphaljha** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @levinskipolish thank you for you report, i'm not able to reproduce following steps you described, please verify that your data in cvs are correct, and have all required fields.

**Comment by levinskipolish** [comment]
@magento-engcom-team Thanks you for your quick response. I'm not sure if I understood, but I'll try to reproduce the steps below. I could dig down a bit more into the problem origin and fix it my self, but I have plenty to do already.


### Precondition 
1. Magento 2.2.6 CE  CentOS Linux. 
2. Can't save product customizable options on **edit product admin**.
3. Category is set up
4. Product were created and assigned to the existing category.
5. Both product and options are visible form back end front end.

### Steps to reproduce issue
1. Navigate to admin
2. Catalog > products >(Chose a product that has custom option).
3. Edit > (Try to save the product with any product modification, **change the option title for ex**).

<img width="1277" alt="screen shot 2019-01-24 at 8 12 53 am" src="https://user-images.githubusercontent.com/26575900/51680533-062f9e80-1fb0-11e9-8d03-483277ac4b4e.png">


4. Out put error:

<img width="1257" alt="screen shot 2019-01-24 at 7 59 35 am" src="https://user-images.githubusercontent.com/26575900/51679852-0a5abc80-1fae-11e9-974b-416e59ebd8c2.png">

5. Using google chrome > Inspect element > open page console.
   
<img width="1276" alt="screen shot 2019-01-24 at 8 01 33 am" src="https://user-images.githubusercontent.com/26575900/51679959-5f96ce00-1fae-11e9-8871-9b8d4430b261.png">

7. 404 url:
https://3acaaab1f9.nxcli.net/admin/catalog/product/validate/id/218/type/simple/store/0/set/4/key/4279fa5f8b2421eeee957469e0d180bfdd02b3751766dce828a67049c726aa58/?isAjax=true

8. Even when I execute the commands: **bin/magento setup:upgrade** > **bin/magento setup:static-content -f**. in order to regenerate new pub/static files, it does the same.

9. I also try to use **composer require magento/module-catalog** after, installing all magento modules. 

### Expected result
1. Save product successfully and see the changes reflected on both storefront and admin.

**Comment by ghost** [comment]
HI @levinskipolish can you reproduce this on vanilla instance ?
