### ISSUE TITLE
MobileMenu fails at 767px

### ISSUE THREAD

**Issue by joinso** [magento/magento2#20568]
### Preconditions (*)

1. Magento 2.3 CE
2. PHP 7.2.13
3. Luma Theme or any that extends it.
4. Demo Sample Data or any data that setups some categories.

### Steps to reproduce (*)

1. Setup your theme as Luma or any that extends it.
2. Setup some categories to fill your store menu.
3. In browser like Chrome or Firefox, open Developer Tools (F12) and activate responsive mode.
4. Setup screen width at 767px

### Expected result (*)

1. Like in 766px or 768px width where menu is collapsed, and is show or hidden when you click on menu icon:
First view of the page:
<img width="305" alt="magento2_issue_mobile_menu_767_01" src="https://user-images.githubusercontent.com/14755728/51665885-05e9d000-1fbd-11e9-89cb-ceae6831ebaf.png">
When you click on menu on icon:
<img width="303" alt="magento2_issue_mobile_menu_767_02" src="https://user-images.githubusercontent.com/14755728/51665890-084c2a00-1fbd-11e9-8936-e15486adcdb8.png">

### Actual result (*)

1. In this case, at only at 767px (not at 766px or 768px), mobile menu fails to render and collapse:

<img width="340" alt="magento2_issue_mobile_menu_767" src="https://user-images.githubusercontent.com/14755728/51665519-3a10c100-1fbc-11e9-9eb3-ab3488b9a599.png">
Click on icon does not work.

Some extra hints:

We found some Magento 2 Online Demos with the same issue.

http://demo-acm-2.bird.eu/
http://demo-acm-2.bird.eu/magento_version : 2.2 CE

https://magento.nublue.co.uk
https://magento.nublue.co.uk/magento_version: 2.3 CE

Regards,
JOINSO

**Comment by magento-engcom-team** [comment]
Hi @joinso. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@joinso do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@amol2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97906` were created

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by amol2jcommerce** [comment]
Hi @joinso by mistake added label but it's not reproducible 2.3

**Comment by joinso** [comment]
Conclusion:
Is related to Luma Theme?

**Comment by jordipujol-mcneel** [comment]
> Hi @joinso by mistake added label but it's not reproducible 2.3

Conclusion:
Is related to Luma Theme?

**Comment by irajneeshgupta** [comment]
@amol2jcommerce 
Seriously  , you  have added 4 labels by mistake.
https://github.com/magento/magento2/issues/20524
