### ISSUE TITLE
Redis customer session lost or use previous customer session

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#20571]
As I use a customer account to login a store. After a bit of time 2-3 sec I see previous customer name appeared from header not my name

### Preconditions (*)

1. Magento 2.1.9 - Running Production Mode
2. PHP 7.0
3. Nginx
4. Redis for session
5. Cm_Cache_Backend_Redis for cache

### Steps to reproduce (*)

1. Go login from login form
2. Wait a bit second to see the customer name is not mine.

### Expected result (*)

1. The customer name should be mine after login
2. Why the customer get lost when using fpc(Full Page Cache) and Redis or Vanish

### Actual result (*)

1. 2-3 seconds then I could get my name, before it was a straight person
2. Debugged the customer session always get lost when fpc and redis or Vanish enabled
3. I cannot disable my fpc by using a `cacheable = false` on header, this is so dumb

My env.php

```
<?php
return array (
  'backend' => 
  array (
    'frontName' => 'admin_la69om',
  ),
  'crypt' => 
  array (
    'key' => 'b4b0f3bfbfd373f9837401f3a52df36c',
  ),
  'session' => 
  array (
    'save' => 'redis',
    'redis' => 
    array (
      'host' => 'localhost',
      'port' => '6379',
      'password' => '',
      'timeout' => '2.5',
      'persistent_identifier' => '',
      'database' => '3',
      'compression_threshold' => '2048',
      'compression_library' => 'gzip',
      'log_level' => '1',
      'max_concurrency' => '6',
      'break_after_frontend' => '5',
      'break_after_adminhtml' => '30',
      'first_lifetime' => '600',
      'bot_first_lifetime' => '60',
      'bot_lifetime' => '7200',
      'disable_locking' => '1',
      'min_lifetime' => '60',
      'max_lifetime' => '2592000',
    ),
  ),
  'db' => 
  array (
    'table_prefix' => '',
    'connection' => 
    array (
      'default' => 
      array (
        'host' => 'localhost',
        'dbname' => 'dbname',
        'username' => 'username',
        'password' => password,
        'active' => '1',
        'model' => 'mysql4',
        'engine' => 'innodb',
        'initStatements' => 'SET NAMES utf8;',
      ),
    ),
  ),
  'cache' => 
  array (
    'frontend' => 
    array (
      'default' => 
      array (
        'backend' => 'Cm_Cache_Backend_Redis',
        'backend_options' => 
        array (
          'server' => 'localhost',
          'database' => '4',
          'port' => '6379',
          'password' => '',
          'persistent' => '',
          'force_standalone' => '0',
          'connect_retries' => '1',
          'read_timeout' => '10',
          'automatic_cleaning_factor' => '0',
          'compress_data' => '1',
          'compress_tags' => '1',
          'compress_threshold' => '20480',
          'compression_lib' => 'gzip',
        ),
      ),
      'page_cache' => 
      array (
        'backend' => 'Cm_Cache_Backend_Redis',
        'backend_options' => 
        array (
          'server' => 'localhost',
          'port' => '6379',
          'password' => '',
          'persistent' => '',
          'database' => '5',
          'force_standalone' => '0',
          'connect_retries' => '1',
          'read_timeout' => '10',
          'automatic_cleaning_factor' => '0',
          'compress_data' => '0',
          'compress_tags' => '1',
          'compress_threshold' => '20480',
          'compression_lib' => 'gzip',
        ),
      ),
    ),
  ),
  'resource' => 
  array (
    'default_setup' => 
    array (
      'connection' => 'default',
    ),
  ),
  'x-frame-options' => 'SAMEORIGIN',
  'MAGE_MODE' => 'production',
  'cache_types' => 
  array (
    'config' => 1,
    'layout' => 1,
    'block_html' => 1,
    'collections' => 1,
    'reflection' => 1,
    'db_ddl' => 1,
    'eav' => 1,
    'customer_notification' => 1,
    'full_page' => 1,
    'config_integration' => 1,
    'config_integration_api' => 1,
    'translate' => 1,
    'config_webservice' => 1,
    'compiled_config' => 1,
    'amasty_shopby' => 0,
    'ec_cache' => 1,
  ),
  'install' => 
  array (
    'date' => 'Mon, 05 Jun 2017 04:08:06 +0000',
  ),
);

```

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tuyennn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97907`, `MAGETWO-97908` were created

**Comment by tuyennn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by dipti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ghost** [comment]
redis or varnish not available on vanilla instance.@tuyennn @dipti2jcommerce try reproduce on local environment

**Comment by cscd98** [comment]
@engcom-backlog-nazar Any update on this issue please?

**Comment by cscd98** [comment]
@engcom-backlog-nazar This is a major bug, can I please have an update?

**Comment by keevitaja** [comment]
hello.

i am using redis (no varnish) on multiple magento 2.2 and 2.3 installations and only one of them has this problem (client feedback). but i am unable to recreate this problem myself. 

are there any preconditions to recreate the issue not mentioned here?
how did you recreate it?

**Comment by tuyennn** [comment]
@craigcarnell To handle this, every times page load I have to reload the customer data then get it once again. This is pretty major bug but no fixing, in some countries the revealing customer information is so bad and makes some bad situations which clients have to explain to government.

**Comment by keevitaja** [comment]
https://github.com/magento/magento2/commit/f3bd0c2f16e038f687ba40ed2a575b04698ccd76

apply this fix. it has something todo with updated zend packages.

**Comment by cscd98** [comment]
Does anyone know if this has been rectified in 2.3.1?

**Comment by cscd98** [comment]
Answered my own question, https://github.com/magento/magento2/commit/f3bd0c2f16e038f687ba40ed2a575b04698ccd76 is included in 2.3.1

Is this issue resolved or not?

**Comment by vuon9** [comment]
I just put here to show the way solving problem for anyone has the same case.

## My case-problem
Magento: v2.2.6

I customized the routes for login flow because we use a third-party service instead the Magento login, then `customer-data` couldn't be loaded by default sections.

```
vendor/magento/module-customer/etc/frontend/sections.xml
```

My customized route looks like:

```
customer/account/callback
```

I mean my problem not came from the header. IMO, the problem that I was not follow the routing flow to invalidate/refresh the default section data. We cannot change the flow of login right now, just focus on the way to solve front-end problem without touch authenticate backend flow.

Base on those reason, this one https://github.com/magento/magento2/commit/f3bd0c2f16e038f687ba40ed2a575b04698ccd76 cannot solve my problem. I've checked our source, we already has this patch.

## The temporary solution

I customized the authenticate component and add a simple script:
```phtml
<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Customer\Model\Session $customerSession */
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

?>
<?php if ($customerSession->isLoggedIn()) { ?>
<script>
        require([
            'jquery',
            'Magento_Customer/js/customer-data'
        ], function ($, customerData) {
            'use strict';
            // Check if the customer data is exists, then invalidate if it is not
            if (!$.localStorage.get('mage-cache-storage').customer) {
                customerData.invalidate(['customer']);
            }
        });
</script> 
<?php } ?>
```

I think these articles will be useful for finding the way customer data works:

https://devdocs.magento.com/guides/v2.2/extension-dev-guide/cache/page-caching/private-content.html
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/etc/frontend/sections.xml
https://github.com/magento/magento2/blob/d7ac52bbbc11e35aac5f87f0ff0fd6232d75e79b/app/code/Magento/Customer/view/frontend/web/js/customer-data.js

**Comment by craigcarnell** [comment]
@engcom-backlog-nazar please confirm if this is fixed?!?!?

**Comment by cscd98** [comment]
@engcom-backlog-nazar This is not fixed.

Redis sessions is causing our application to re-use increment_id in checkout!

This needs resolving ASAP!!!!

The only solution that works for me is <disable_locking>1</disable_locking>

**Comment by sdzhepa** [comment]
Hello @tuyennn , @craigcarnell 

Thank you for your report and collaboration!

All related to this Issue internal Jira ticket(`MAGETWO-97907`, `MAGETWO-97908`) were closed by Magento team as `Cannot Reproduce` because already fixed in 
- https://github.com/magento/magento2/commit/f3bd0c2f16e038f687ba40ed2a575b04698ccd76

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
