### ISSUE TITLE
MobileMenu fails at 767px in some screen resolutions

### ISSUE THREAD

**Issue by joinso** [magento/magento2#20599]
### Preconditions (*)

1. Magento 2.3 CE
2. PHP 7.2.13
3. Luma Theme or any that extends it.
4. Demo Sample Data or any data that setups some categories.
5. Any monitor can manager high resolutions like 4K.

### Steps to reproduce (*)

1. Setup your theme as Luma or any that extends it.
2. Setup some categories to fill your store menu.
3. Use screen resolution: 3840x2160 at start point
4. In browser like Chrome or Firefox, open Developer Tools (F12) and activate responsive mode.
5. Setup screen width at 767px

### Expected result (*)

1. Like in 766px or 768px width where menu is collapsed, and is show or hidden when you click on menu icon:
First view of the page:
<img width="305" alt="magento2_issue_mobile_menu_767_01" src="https://user-images.githubusercontent.com/14755728/51665885-05e9d000-1fbd-11e9-89cb-ceae6831ebaf.png">
When you click on menu on icon:
<img width="303" alt="magento2_issue_mobile_menu_767_02" src="https://user-images.githubusercontent.com/14755728/51665890-084c2a00-1fbd-11e9-8936-e15486adcdb8.png">

### Actual result (*)

1. In this case, at only at 767px (not at 766px or 768px), mobile menu fails to render and collapse:

<img width="340" alt="magento2_issue_mobile_menu_767" src="https://user-images.githubusercontent.com/14755728/51665519-3a10c100-1fbc-11e9-9eb3-ab3488b9a599.png">
Click on icon does not work.

Some extra hints:

We are testing using a 24" Dell monitor with 3840x2160 resolution.

It seems that only happens in some screen resolutions.

For test we are using a 24" monitor, but can be happen with any that can manage this resolutions.

This is the result of our tests:

3840x2160 --> Fails. In this case, the width of the HTML element is 767,33333 px.
2560x2048 --> Fails. In this case, the width of the HTML element is 767,33333 px.
2560x1920 --> Fails. In this case, the width of the HTML element is 767,33333 px.
2560x1600 ---> Fails. In this case, the width of the HTML element is 767,2 px.
2560x1400 --> Ok.In this case, the width of the HTML element is 767 px.
2048x1536 --> Ok.In this case, the width of the HTML element is 767 px.
2048x1280 --> Ok.In this case, the width of the HTML element is 767 px.
2048x1152 --> Ok.In this case, the width of the HTML element is 767 px.
1920x2160 ---> Fails. In this case, the width of the HTML element is 767,333 px.
1920x1440 ---> Ok.In this case, the width of the HTML element is 767 px.
1920x1200 --> Ok. In this case, the width of the HTML element is 767px.
1920x1080 --> Ok. In this case, the width of the HTML element is 767px.
1856x1932 --> Ok. In this case, the width of the HTML element is 767px.

So, the problem seems is that the mobile menu fails at 767px, when "html" element has a width not equal at 767px.

We found some Magento 2 Online Demos with the same issue.
http://demo-acm-2.bird.eu/
http://demo-acm-2.bird.eu/magento_version : 2.2 CE

https://magento.nublue.co.uk
https://magento.nublue.co.uk/magento_version: 2.3 CE

Regards,
JOINSO

**Comment by magento-engcom-team** [comment]
Hi @joinso. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@joinso do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ajay2jcommerce** [comment]
Hi 
 
PR already created #20568 .

**Comment by jordipujol-mcneel** [comment]
Hi @ajay2jcommerce !

I created #20568 yesterday, but it's closed.
This one is more detailed because we find more details, and it seems that now the issue can be reproduced.

Regards.
JOINSO

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @joinso i'm not able to reproduce following steps you described, and i'm not sure in which devices you have this issue ?

**Comment by joinso** [comment]
Hi!

It is more a display issue, not a device issue.
It is very strange to have a 767px screen width device.

For test you need a screen that can handle high resolutions, like 4K.

The first fail is when resolution of screen is: 3840x2160
Then you press F12 in browser, set responsive mode, and setup width at 767px.
Then the mobilemenu not rendered correctly and not collapse.
In this case, the computed width of the HTML element is 767,33333 px.

So it seems, than the function that handles this, fails in this case: when HTML width is not exactly: 767px.

Regards,
JOINSO

**Comment by joinso** [comment]
> Hi @joinso i'm not able to reproduce following steps you described, and i'm not sure in which devices you have this issue ?

Hi!

It is more a display issue, not a device issue.
It is very strange to have a 767px screen width device.

For test you need a screen that can handle high resolutions, like 4K.

The first fail is when resolution of screen is: 3840x2160
Then you press F12 in browser, set responsive mode, and setup width at 767px.
Then the mobilemenu not rendered correctly and not collapse.
In this case, the computed width of the HTML element is 767,33333 px.

So it seems, than the function that handles this, fails in this case: when HTML width is not exactly: 767px.

Regards,
JOINSO

**Comment by joinso** [comment]
> Hi @joinso i'm not able to reproduce following steps you described, and i'm not sure in which devices you have this issue ?

Hi!

It is more a display issue, not a device issue.
It is very strange to have a 767px screen width device.

For test you need a screen that can handle high resolutions, like 4K.

The first fail is when resolution of screen is: 3840x2160
Then you press F12 in browser, set responsive mode, and setup width at 767px.
Then the mobilemenu not rendered correctly and not collapse.
In this case, the computed width of the HTML element is 767,33333 px.

So it seems, than the function that handles this, fails in this case: when HTML width is not exactly: 767px.

Regards,
JOINSO

**Comment by jordipujol-mcneel** [comment]
> Hi @joinso i'm not able to reproduce following steps you described, and i'm not sure in which devices you have this issue ?

Hi!

It is more a display issue, not a device issue.
It is very strange to have a 767px screen width device.

For test you need a screen that can handle high resolutions, like 4K.

The first fail is when resolution of screen is: 3840x2160
Then you press F12 in browser, set responsive mode, and setup width at 767px.
Then the mobilemenu not rendered correctly and not collapse.
In this case, the computed width of the HTML element is 767,33333 px.

So it seems, than the function that handles this, fails in this case: when HTML width is not exactly: 767px.

Regards,
JOINSO

**Comment by ghost** [comment]
@joinso ok, but i'm not have an actual result. 
![selection_290](https://user-images.githubusercontent.com/40756439/51733802-3dbf4900-208b-11e9-87a4-189b56395883.png)

**Comment by jordipujol-mcneel** [comment]
The test must be done at 767px, not 766px.

**Comment by ghost** [comment]
@joinso same here 
![selection_291](https://user-images.githubusercontent.com/40756439/51734038-00a78680-208c-11e9-81a8-8ad3cbb04859.png)

**Comment by jordipujol-mcneel** [comment]
We are not sure that you test scenario is correct.
For this reason can you send this data, please?

1.- Resolution of your monitor?
2.- Computed width of html element?

In our test scenario:

<img width="883" alt="display_issue_at_767px_01" src="https://user-images.githubusercontent.com/14755728/51734510-09e12500-2085-11e9-931f-45b78c809a4b.png">

<img width="745" alt="display_issue_at_767px" src="https://user-images.githubusercontent.com/14755728/51734513-0c437f00-2085-11e9-8b19-99f2e6cc1098.png">
