### ISSUE TITLE
Magento 2.2.2 layered navigation shows also out of stock products 

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#20593]
I know there are already closed issues for this problem but none has worked for me. 

### Preconditions (*)
magento 2.2.2 on ubuntu 16.04, apache2, php 7.1.26, mysql 5.7.25, with configurable products with a text swatch attribute (eg: size) which is filterable with results in layered navigation. Option "show out of stock products" is set to NO.

### Steps to reproduce (*)
- open a configurable product from backend, go to configuration section and set an associated simple product (eg: size = 42) to qty = 0 and out of stock, then save the product, clean cache and reindex
- go to category page in frontend to see list of products, then filter the list with the attribute you set out of stock (eg: size 42)

### Expected result (*)
Search should list only configurable product that have size 42 available (in stock)

### Actual result (*)
Search shows also the product which has the size 42 out of stock among the product which have that size available

### Notes
I have a staging environment with mysql 5.6 as only difference from the production environment and here the layered navigation works as expected.

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-20593-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20593-2-2-develop.instances.magento-community.engineering/admin](https://i-20593-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by amol2jcommerce** [comment]
Hi @LouNik1984 Not reproduce 2.2-develop

**Comment by LouNik1984** [comment]
I have two environments that are almost identical. The only difference I have on those two environments is the mysql version. On the environment with mysql 5.6 the layered navigation works properly. On the environment with mysql 5.7 the layered navigation shows the described issue. What mysql version had the magento instance that was used to try and reproduce the issue?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @LouNik1984 thak you for you report, seesm like this already fixed in 2.2-develop branch, i'm tested on 
mysql 
![selection_293](https://user-images.githubusercontent.com/40756439/51736754-94c91c00-2093-11e9-8912-d58e9a2ab81c.png)

**Comment by LouNik1984** [comment]
"seesm like this already fixed in 2.2-develop branch"

so how can I fix mine?

**Comment by ghost** [comment]
@LouNik1984 give me 10 minutes i will try find related commit

**Comment by ghost** [comment]
@LouNik1984 https://github.com/magento/magento2/pull/13417, https://github.com/magento/magento2/pull/12063 ,

**Comment by LouNik1984** [comment]
Unfortunately those commit didn't help me, so I created a clone of my buggy version on the same server to further test and finally I found the root of the issue: elasticsearch. If I switch to mysql as search engine via magento backend configuration and clear cache (magento cache:clean) then the layered navigation works as expected. If I switch back to elasticsearch and clear cache (again with cache:clean) then the issue is present again.

**Comment by ghost** [comment]
@LouNik1984 ok, which version  elasticsearch you're used ?

**Comment by LouNik1984** [comment]
I'm using aws elasticsearch service, version 5.3.2

**Comment by ghost** [comment]
@LouNik1984 i'm will retest with elasticsearch

**Comment by LouNik1984** [comment]
Thank you very much, sorry for my previous mistake

**Comment by anatolij-p** [comment]
@LouNik1984 
Can you provide some more info on did you solve the Elastic Search issue?
I'm having the same problem.

**Comment by LouNik1984** [comment]
@anatolij-p 
I'm sorry but I didn't find a solution to solve it

**Comment by mikehenze** [comment]
Please reopen.
This issue still persist even with m2.3.5-p2 and elasticsearch 7
