### ISSUE TITLE
Shopping Cart Display Settings > Display Subtotal = Including Tax - should only show one subtotal

### ISSUE THREAD

**Issue by gchristian17** [magento/magento2#20591]
### Preconditions (*)

1. Magento ver. 2.3.0
2. Multi-store installation

### Steps to reproduce (*)

1. Go to Config > [select store] > Sales > Tax > Shopping Cart Display Settings
2. Set the following:

<ul>
	<li>Display Prices = Including Tax</li>
	<li>Display Subtotal = Including Tax</li>
	<li>Display Shipping Amount = Including Tax</li>
	<li>Display Gift Wrapping Prices = Including Tax</li>
	<li>Display Printed Card Prices = Including Tax</li>
	<li>Include Tax In Order Total = Yes</li>
	<li>Display Full Tax Summary = No</li>
	<li>Display Zero Tax Subtotal = No</li>
</ul>

![config-sales-tax-display-settings](https://user-images.githubusercontent.com/28341968/51688867-5ed15c80-1fed-11e9-8987-f5e8e0796657.png)

### Expected result (*)

1. Shopping cart and checkout summary should display just one total (the one including tax)

### Actual result (*)

1. Two subtotals are displayed: Incl. Tax and Excl. Tax

![checkout-cart-totals-with-tax](https://user-images.githubusercontent.com/28341968/51688882-642ea700-1fed-11e9-9830-b39c7c92c592.png)

**Comment by magento-engcom-team** [comment]
Hi @gchristian17. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gchristian17 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by gchristian17** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @gchristian17. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @gchristian17, here is your [Magento instance](https://i-20591-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20591-2-3-0.instances.magento-community.engineering/admin](https://i-20591-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gchristian17** [comment]
@magento-engcom-team Yes, can confirm able to reproduce on vanilla Magento instance following steps to reproduce.

Settings:
![screenshot from 2019-01-24 15-52-02](https://user-images.githubusercontent.com/28341968/51690149-08195200-1ff0-11e9-89d8-777078b51f1d.png)

Output:
![screenshot from 2019-01-24 15-50-22](https://user-images.githubusercontent.com/28341968/51690159-0bacd900-1ff0-11e9-99e7-25aaf14fd10e.png)

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-20591-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20591-2-3-0.instances.magento-community.engineering/admin](https://i-20591-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-20591-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20591-2-2-develop.instances.magento-community.engineering/admin](https://i-20591-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @gchristian17 thank you for you report, this is non issue this label `Include Tax In Order Total`
Show all Exc. and incl. tax on **Order total** This is expected beahvior please set this option to no.

**Comment by gchristian17** [comment]
Hi @engcom-backlog-nazar

Thank you for looking into this. 

I do not agree that this is expected behaviour. The available options are as follows -

Display Subtotal:

 - Excluding Tax
 - Including Tax
 - Including and Excluding Tax 

If we want both, we could select "Including and Excluding Tax" to get them. If we select "Including Tax" there should only be one Subtotal displayed. But this is not what happens. Please look again.

![display-subtotal-options](https://user-images.githubusercontent.com/28341968/51736118-2e3b0280-2081-11e9-9eac-ba22f6e36ad2.png)

If you think this is expected behaviour for this element, then the labels are wrong.

**Comment by ghost** [comment]
@gchristian17 this is **SUB** but not **total** -> Include Tax In Order **Total**

**Comment by ghost** [comment]
@gchristian17 
![selection_292](https://user-images.githubusercontent.com/40756439/51736623-313eee80-2093-11e9-9dac-583924061be7.png)

**Comment by gchristian17** [comment]
@engcom-backlog-nazar - got it, thanks for your help
