### ISSUE TITLE
Unable to pass enum value as argument in GraphQL query

### ISSUE THREAD

**Issue by kouma** [magento/magento2#20590]
Hello there, 

When you pass enum values as argument in your GraphQL queries, the validation fails. To reproduce this bug, let's use the super simple `SortEnum` that contains only 2 attributes, `ASC` and `DESC` :

```text
enum SortEnum @doc(description: "This enumeration indicates whether to return results in ascending or descending order") {
    ASC
    DESC
}
```
We'll use it on the `products` query to sort the paginated result.

### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Install GraphiQL extension for Chrome [here](https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij)
2. Set the endpoint with your site uri  : `https://yoursite.com/graphql`
3. In the left column, type this query :

```text
query Products(
  $price: String,
  $sort: SortEnum = DESC
) {
    products (
        filter: {
          price: {
            gt: $price
          }
        },
        sort: {
          name: $sort
        }
    ) {
      items {
        id
        name
      }
    }
  }
```
Type these variables in the "Query Variables" block on the bottom left :
```json
{
  "sort": "ASC",
  "price": "1"
}
```
...and hit the big upper button to perform the request.

### Expected result (*)

1. Normally in GraphQL, you are able to pass enum types as variables. The result should be a paginated list of products sorted by name ASC. 

### Actual result (*)

1. The request doesn't perform well : 

![enum_issue](https://user-images.githubusercontent.com/1068013/51687453-d05fd980-1ff2-11e9-874e-d8e028e8e70e.png)

```json
{
  "errors": [
    {
      "message": "Variable \"$sort\" of type \"SortEnum\" used in position expecting type \"SortEnum\".",
      "category": "graphql",
      "locations": [
        {
          "line": 3,
          "column": 3
        },
        {
          "line": 12,
          "column": 17
        }
      ]
    }
  ]
}
```
I don't know if it's a Magento or a graphql-php related error. The error seems to be caused by the graphql-php validation process, the class `GraphQL\Validator\Rules\VariablesInAllowedPosition` is causing the error. 

I tested with custom enums and the issue is the same. The only way to succeed is to change the type `SortEnum` to `String` and pass value as a string, but it's not a proper solution at all.
Actually this is very annoying because you can't use enum types as arguments for queries.

**Comment by magento-engcom-team** [comment]
Hi @kouma. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kouma do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @kouma thank you for you report, please open issue here -> https://github.com/magento/graphql-ce
