### ISSUE TITLE
Customer Admin Shopping Cart View Missing

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#20598]
### Summary (*)
In Magento 1.x.x in Reports>Shopping Cart> Abandoned Carts you are able to view a list of customers and when you click on them you will see the products in their cart. 

You are forwarded to a URL within the admin: /customer/edit/id/12345/active_tab/cart/key/xxxxxx

In Magento 2, when you go to Reports>Marketing>Abandoned Carts you are able to view a list of customers, and when you click on the customer, you are forwarded to the URL:

/customer/index/edit/id/12345/active_tab/cart/key/xxxxxxxx

But instead of seeing a list of products, it forwards you to the Customer View tab of the customer page.

### Preconditions (*)
1. Magento 2.2.5

### Steps to reproduce (*)
1. Reports>Marketing>Abandoned Carts
2. Click on customer

### Expected result (*)
1. forwarded to /customer/index/edit/id/12345/active_tab/cart/key/xxxxxxxx
2. See list of products in customers cart.

### Actual result (*)
1. forwarded to /customer/index/edit/id/12345/active_tab/cart/key/xxxxxxxx which actually forwards to the main index of the Customer View instead of the /cart/ tab.

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nickpiro do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@amol2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97919` were created

**Comment by irajneeshgupta** [comment]
@amol2jcommerce @engcom-backlog-nazar 

How you reproduced this issue as it is not reproduced on vanilla instance?
Magento behavior is correct , abondoned cart is visible in admin without any issues.
Do not verify/confirm any issue which you can not reproduced , it will create mess up whole process.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
HI @nickpiro thank you for you report, Not really a fix or anything, but if you press the "Create Order" button it will show the items on the cart on that page.

**Comment by nickpiro** [comment]
I tested this in vanilla and I am getting the same blank abandoned cart...So I do not see how this should be closed!

**Comment by ghost** [comment]
@nickpiro https://github.com/magento/magento2/issues/6287

**Comment by nickpiro** [comment]
@engcom-backlog-nazar that doesn't answer my question? This is clearly a feature in community. So why doesn't it work? It clearly attempts to send you to this page, the file exists cart.phtml, but it's not displaying! How is referring me to this old issue which also has yet to be resolved? How isn't anyone else complaining about this?

**Comment by ghost** [comment]
@nickpiro ok,  you can report here ->  https://github.com/magento/community-features
