### ISSUE TITLE
Gift option message overlap edit and remove button

### ISSUE THREAD

**Issue by ajay2jcommerce** [magento/magento2#20604]
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. Login Admin
2. Go to Store >> Configuration >> sales >> sales >>gift option>> enable both settings
3. add product to cart.
4. add gift option massage.

### Expected result (*)

1. 
![expectedt](https://user-images.githubusercontent.com/18118570/51729370-63534f00-2099-11e9-8933-34ca7fafd896.jpg)

### Actual result (*)

1. 
![actual](https://user-images.githubusercontent.com/18118570/51729376-6bab8a00-2099-11e9-8c96-9db2410a8494.jpg)

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ajay2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nainesh2jcommerce** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce, here is your [Magento instance](https://i-20604-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20604-2-3-0.instances.magento-community.engineering/admin](https://i-20604-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@nainesh2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97922` were created

**Comment by irajneeshgupta** [comment]
@nainesh2jcommerce @engcom-backlog-nazar  
you are wasting the instance per issue, if you do not need it... don't ask engcom team bot for new instances.I checked that you have not tested anything in this instance.

**Comment by nainesh2jcommerce** [comment]
Hi @irajneeshgupta, 

Instance which I requested to engcom team in that I am able to re-produce the issue and I have created test product in that to verify issue. How you mentioned that I haven't checked anything in that instance.

Also for your confirmation please check attachment in which I have created product along with case on shopping cart. 
![image](https://user-images.githubusercontent.com/18118539/51732125-4754ab00-20a3-11e9-9dc4-b764cbc64813.png)

Please check properly from you end after that raise issue in ticket also PR already generated for this ticket.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by irajneeshgupta** [comment]
@nainesh2jcommerce 
previously you tested in another instance and  when i reported , you edited/deleted your messages. 
not expected these things , play with your instances good luck.
![download](https://user-images.githubusercontent.com/18143480/51732929-d662c280-20a5-11e9-9348-79767faca1c4.png)

**Comment by ghost** [comment]
Hi @irajneeshgupta can confirm this iss
![selection_289](https://user-images.githubusercontent.com/40756439/51733641-9e01bb00-208a-11e9-90ec-4a108f77538b.png)
ue exist on 2.3-develop

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20605 by @ajay2jcommerce in 2.3-develop branch
Related commit(s):
 - [93b34b0cd11280b1c9961d0a6f6c0a1f1a597b49](https://github.com/magento/magento2/commit/93b34b0cd11280b1c9961d0a6f6c0a1f1a597b49)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20784 by @ajay2jcommerce in 2.2-develop branch
Related commit(s):
 - [adf8d4cccb28e168d9accae2edad202bb4914d7f](https://github.com/magento/magento2/commit/adf8d4cccb28e168d9accae2edad202bb4914d7f)

The fix will be available with the upcoming 2.2.8 release.
