### ISSUE TITLE
In admin Catalog Start time field & Date Field order misaligned in iPad

### ISSUE THREAD

**Issue by amol2jcommerce** [magento/magento2#20600]
### Preconditions (*)

1. Magento 2.3.x
2. Magento 2.2.x

### Steps to reproduce (*)

1. In Admin Stores >> Configuration >> Catalog >> Product Alerts Run Settings >> Start Time
2. In Admin Stores >> Configuration >> Catalog >> Date & Time Custom Options >> Date Fields Order

### Expected result (*)

1. 
![2](https://user-images.githubusercontent.com/18118631/51726196-2af94400-208c-11e9-85d0-38b3c0c4f7bf.jpg)

2. 
![2-1](https://user-images.githubusercontent.com/18118631/51726202-2f256180-208c-11e9-9a98-af0e9928ec05.jpg)

### Actual result (*)

1. 
![1](https://user-images.githubusercontent.com/18118631/51726207-364c6f80-208c-11e9-8f0d-bfd2b573f5a8.jpg)

2. 
![1-1](https://user-images.githubusercontent.com/18118631/51726211-3b112380-208c-11e9-817b-a4bef291b779.jpg)

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amol2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@amol2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97920`, `MAGETWO-97921` were created

**Comment by dipti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce, here is your [Magento instance](https://i-20600-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20600-2-3-develop.instances.magento-community.engineering/admin](https://i-20600-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cedarvinda** [comment]
@amol2jcommerce this issue already fixed #20580 in same less 3 time PR with same line number what is this. You don't know global solution ?
