### ISSUE TITLE
FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by kalalruturaj** [magento/magento2#20635]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2.13 (cli)

**We are using AWS Cloudformation template which was supported for Magento 2.1 but we have manually upgraded it to Magento 2.3.0. I am not sure how this can affect. **

Upgraded Magento 2.1.16 to Magento 2.3.0, I am getting an error on the browser HTTP 500 but i can see the request on nginx. 

Error in access log is:

`2019/01/26 06:44:59 [error] 12354#0: *1 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/vendor/magento/framework/Filesystem/Directory/Write.php on line 35" while reading response header from upstream, client: 10.0.157.172, server: www.example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.socket:", host: "binaryhat.com"`

If i remove the ? new error occurs in Read.php 

![image](https://user-images.githubusercontent.com/14205802/51789681-7b8aa300-2159-11e9-8403-187d07106a38.png)

**Comment by magento-engcom-team** [comment]
Hi @kalalruturaj. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kalalruturaj do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by kalalruturaj** [comment]
@magento-engcom-team give me Magento 2.3.0 instance

**Comment by kalalruturaj** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @kalalruturaj. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalalruturaj, here is your [Magento instance](https://i-20635-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20635-2-3-0.instances.magento-community.engineering/admin](https://i-20635-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment]
dublicate issue ref ->https://github.com/magento/magento2/issues/18146

**Comment by sagar123pawar** [comment]
In aws : amaon linux os:
vim /etc/php-fpm-7.0.conf

check as follows:

[global]
pid = /var/run/php-fpm/php-fpm-7.0.pid
error_log = /var/log/php-fpm/7.0/error.log
daemonize = yes
[www]
user = nginx
group = nginx
listen = /tmp/php-cgi.socket
listen.owner = nginx
listen.group = nginx
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
slowlog = /var/log/php-fpm/www-slow.log
php_admin_value[error_log] = /var/log/php-fpm/7.0/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path]    = /var/lib/php/7.0/session
php_value[soap.wsdl_cache_dir]  = /var/lib/php/7.0/wsdlcache

**Comment by DanielRuf** [comment]
Please upgrade your PHP version.

**Comment by DanielRuf** [comment]
Please upgrade your PHP version to 7.2.0.

**Comment by kalalruturaj** [comment]
@sagar123pawar This works.
