### ISSUE TITLE
Path "/var/www/html/var/composer_home/" cannot be used with directory "/var/www/html/var/composer_home/"

### ISSUE THREAD

**Issue by kalalruturaj** [magento/magento2#20639]
I have just upgraded from Magento 2.1.16 to Magento 2.3.0, and I am not able to connect to the Magento Market place I am keep getting an error message when i enter the Private and Public Key

### Preconditions (*)

1. Connecting to Marketplace using Private and Public Key
2. I have confirmed that **/var/www/html/var/composer_home/** this folder is available and permissions are 
![image](https://user-images.githubusercontent.com/14205802/51795392-8b81a180-21b0-11e9-81f2-f55c5ce7652a.png)

### Steps to reproduce (*)

1. Enter Keys from Marketplace Profile

### Expected result (*)

1. Expected to see the results and install new extensions.

### Actual result (*)

1. Getting Error Message **Path "/var/www/html/var/composer_home/" cannot be used with directory "/var/www/html/var/composer_home/"**
 
![image](https://user-images.githubusercontent.com/14205802/51795352-aa336880-21af-11e9-9e92-c23f0d6531ea.png)

**Comment by magento-engcom-team** [comment]
Hi @kalalruturaj. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kalalruturaj do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by kalalruturaj** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @kalalruturaj. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalalruturaj, here is your [Magento instance](https://i-20639-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-20639-2-3-0.instances.magento-community.engineering/admin](https://i-20639-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sagar123pawar** [comment]
set permission 2775   (/var/www/html/var/) to all var directory of magento root folder as:

` sudo chmod 2775 /var/www/html/var/   `

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by kalalruturaj** [comment]
@sagar123pawar It worked thanks Sagar you are awesome!!
