### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS  when adding conditions on catalog/cart price rules

### ISSUE THREAD

**Issue by ahmadssb** [magento/magento2#20649]
I am using Magento 2.3 installed via CPanel from hosting

I am trying to create a catalog price rule, when I click on condition and selects Catalog it takes time to load then displays an error

I have tried this on multiple browsers , (my website not using https)

check the video I Captured for my problem

https://youtu.be/6B8qFuUgf_c

### Preconditions (*)

1. Magento version 2.3
2. installed from CPanel

### Steps to reproduce (*)

1. Click Marketing
2. open (catalog  or  cart) price rules page
3. click "add new rule"
4. open conditions section
5. click (+) button
6. select any option from drop down list 
7. "please wait" dialog appears 
8. a message "This won't take long" with gif loading appears in place of drop down list 
9. "please wait" dialog disappears

### Expected result (*)

1.  a message "This won't take long" disapear
2. a drop down list for selected condition appears  to select

### Actual result (*)

1. Check this video : https://youtu.be/6B8qFuUgf_c
2.  page keep loading
3. it redirect me to this link and keep loading
http://xxxxx.com/admin/catalog_rule/index/index/key/70e5714b5f7a4c50716768abd4c3f078faade0b52ab978e1bb441e04edc7d495/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/adminhtml/dashboard

4. even in this page it keeps loading until it givs me this error in chrome :
ERR_TOO_MANY_REDIRECTS

**Comment by magento-engcom-team** [comment]
Hi @ahmadssb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ahmadssb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ahmadssb** [comment]
yes

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-20649-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20649-2-3-develop.instances.magento-community.engineering/admin](https://i-20649-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by GovindaSharma** [comment]
@ahmadssb i am not able to reproduce this issue on the given instance.It is related to rewrite rule which you need to configure in your server.

**Comment by ahmadssb** [comment]
It is found that certain script is being blocked by ModSecurity that is breaking the function. 

I have proceed to bypass the ModSecurity for the domain and have verify from my end that the function is now working as usual.

**Comment by hgati** [comment]
In Magento 2.4.6, requests are being blocked by ModSecurity, as they are being identified as SQL injection attempts.

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `^0?$' against variable `REQUEST_HEADERS:content-length' (Value: `104' ) [file "/usr/local/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "162"] [id "920170"] [rev ""] [msg "GET or HEAD Request with Body Content"] [data "104"] [severity "2"] [ver "OWASP_CRS/3.3.5"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [hostname "140.82.42.74"] [uri "/admin/catalog_rule/promo_catalog/newConditionHtml/form/catalog_rule_formrule_conditions_fieldset_1/form_namespace/catalog_rule_form/key/24f454bf55b63a7ec6c7a89e5c78bf7c97fcf01bb410521902d2bc78088a79 (3 characters omitted)"] [unique_id "169572249555.625089"] [ref "o0,3v0,3v261,3"]
ModSecurity: Warning. detected SQLi using libinjection. [file "/usr/local/modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "46"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: 1c found within ARGS:id: 1--2"] [severity "2"] [ver "OWASP_CRS/3.3.5"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [hostname "140.82.42.74"] [uri "/admin/catalog_rule/promo_catalog/newConditionHtml/form/catalog_rule_formrule_conditions_fieldset_1/form_namespace/catalog_rule_form/key/24f454bf55b63a7ec6c7a89e5c78bf7c97fcf01bb410521902d2bc78088a79 (3 characters omitted)"] [unique_id "169572249555.625089"] [ref "v2325,4"]
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `10' ) [file "/usr/local/modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 10)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.5"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "140.82.42.74"] [uri "/admin/catalog_rule/promo_catalog/newConditionHtml/form/catalog_rule_formrule_conditions_fieldset_1/form_namespace/catalog_rule_form/key/24f454bf55b63a7ec6c7a89e5c78bf7c97fcf01bb410521902d2bc78088a79 (3 characters omitted)"] [unique_id "169572249555.625089"] [ref ""]
```
