### ISSUE TITLE
Exceptions on login are not logged

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#2066]
Is there a reason for _not_ logging them? Because I think they should definitely be logged.

https://github.com/magento/magento2/blob/4985acecc2a9204712531ba25b0c867ef09a4667/app/code/Magento/Customer/Controller/Account/LoginPost.php#L101-L103

**Comment by slavvka** [comment]
@adragus-inviqa, thank you for your notification. Please feel free to contribute it with your pull request. Thank you!

**Comment by daim2k5** [comment]
@adragus-inviqa do you like provide a PR?

**Comment by therouv** [comment]
I think the reason for not logging the exceptions here is because of a possible PA DSS validation as in the exception message can contain sensitive customer data.

M1 does not log the exceptions here as well, see https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Customer/controllers/AccountController.php#L177

**Comment by adragus-inviqa** [comment]
Then why is this "up for grabs"? That's why I ask first.

**Comment by davidalger** [comment]
@therouv is correct… adding an exception log call here would be a PA-DSS violation - it is because the username/password are passed directly as arguments to the authenticate() method vs being passed as an object. An exception backtrace would contain the username and password in plaintext within the backtrace.

I've opened a PR to correct the error message displayed to the user and also to re-add the note which was formerly there in M1. Closing this issue page. Please reopen if you disagree with this assessment.
