### ISSUE TITLE
My account page title extra space on mobile (when not display error or success messages)

### ISSUE THREAD

**Issue by priti2jcommerce** [magento/magento2#20723]
### Preconditions (*)

1. Magento 2.3.0

### Steps to reproduce (*)

1. My Account page title in mobile view

### Expected result (*)

1. 
![my account - 02](https://user-images.githubusercontent.com/18118695/51834648-f5b95400-2320-11e9-9272-b7e75fd4dc0f.jpg)

### Actual result (*)

1. 
![my account - 01](https://user-images.githubusercontent.com/18118695/51834669-05d13380-2321-11e9-82be-f64b2ad40764.jpg)

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@priti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [Magento instance](https://i-20723-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20723-2-3-develop.instances.magento-community.engineering/admin](https://i-20723-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@amol2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97948` were created

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20723-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20723-2-2-develop.instances.magento-community.engineering/admin](https://i-20723-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [Magento instance](https://i-20723-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20723-2-2-develop.instances.magento-community.engineering/admin](https://i-20723-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by roma-glushko** [comment]
@priti2jcommerce @amol2jcommerce , 
Can you tell me what's difference between these two screenshots? This doesn't look like a bug or anything that should be reported/fixed in Magento Github. If you need to change Luma styles, please reach community out in https://magento.stackexchange.com/ .
Thank you for understanding.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20725 by @amol2jcommerce in 2.3-develop branch
Related commit(s):
 - [ac39ca2e54fad653d1aef3f7f2a96affcbde5c78](https://github.com/magento/magento2/commit/ac39ca2e54fad653d1aef3f7f2a96affcbde5c78)
 - [89ece35ab57c0990a7468c24c87b64ee20ca3b5e](https://github.com/magento/magento2/commit/89ece35ab57c0990a7468c24c87b64ee20ca3b5e)
 - [fe35a75689b5950540f2731b6b0f19ce33e21fe9](https://github.com/magento/magento2/commit/fe35a75689b5950540f2731b6b0f19ce33e21fe9)
 - [5e2ac52500fee0ccc9340b95cde9f7675b12d2fe](https://github.com/magento/magento2/commit/5e2ac52500fee0ccc9340b95cde9f7675b12d2fe)
 - [b208e444bf108f8d5dfd800d952376ad2e4d4c13](https://github.com/magento/magento2/commit/b208e444bf108f8d5dfd800d952376ad2e4d4c13)

The fix will be available with the upcoming 2.3.1 release.

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-20723-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20723-2-2-develop.instances.magento-community.engineering/admin](https://i-20723-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20782 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [615a59504aed5401e9aa866e913623505b75cbe2](https://github.com/magento/magento2/commit/615a59504aed5401e9aa866e913623505b75cbe2)
 - [880362a5c89210225ede192d419439c14d51a18d](https://github.com/magento/magento2/commit/880362a5c89210225ede192d419439c14d51a18d)

The fix will be available with the upcoming 2.2.9 release.
