### ISSUE TITLE
Inconsistent Behaviour of Elasticsearch HTTP Auth (Username and Password fields not available)

### ISSUE THREAD

**Issue by ndianabasi** [magento/magento2#20732]
### Preconditions (*)
1. Magento 2.3 OpenSource
2. PHP 7.2
3. Nginx
4. MySql (Percona drop-in)
5. Ubuntu 16.04 LTS

### Steps to reproduce (*)
1. Configure unsecure Nginx server block for Elasticsearch using instructions here: https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html.
2. Test configuration on Magento Admin via **Stores > Settings > Configuration > Catalog > Catalog > Catalog Search.**. Connection is successful.
3. Commandline **curl** test succeeds without authentication details.
4. Configure HTTP Auth for Nginx server block for Elasticsearch using instructions here: https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html.
5. Commandline **curl** test fails with 401 error when no authentication details are supplied.
6. From **Stores > Settings > Configuration > Catalog > Catalog > Catalog Search**, set **Enable Elasticsearch HTTP Auth** to "Yes".
7. **Auth username and password fields are not revealed for supply of basic authentication credentials**.
8. Click test button, connection fails with warning: "The search failed because of a search engine misconfiguration."
9. Set **Enable Elasticsearch HTTP Auth** to "No."
10. Click test button and connection succeeds even when Nginx server block now requires authentication.

### Expected result (*)
1. Username and Password fields should be displayed for authentication.
2. Connection test should fail when **Enable Elasticsearch HTTP Auth** to "No" and Nginx Server block already requires authentication.

### Actual result (*)
1. No username or password fields for basic authentication.
2. When **Enable Elasticsearch HTTP Auth** to "No" and Nginx Server block already requires authentication, connection still succeeds.

![screenshot](https://user-images.githubusercontent.com/13512173/51864261-84d76380-2343-11e9-9333-dda6c591c4ea.png)

Nginx block in use.

```
server {
    listen <custom_port_number>;
    server_name 127.0.0.1;
    location / {
        limit_except HEAD {
		   auth_basic "Restricted";
		   auth_basic_user_file  <path>/.elasticsearch;
		}
		proxy_pass http://127.0.0.1:9200;
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /_aliases {
		auth_basic "Restricted";
		auth_basic_user_file  <path>/.elasticsearch;
		proxy_pass http://127.0.0.1:9200;
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
```

**Comment by magento-engcom-team** [comment]
Hi @ndianabasi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ndianabasi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by engcom-backlog-nazar** [comment]
Hi @ndianabasi  Magento 2.3 is currently supporting Elasticsearch 5.2.x and Elasticsearch 2.x so it isn't an issue.
Look here https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by ghost** [comment]
Hi  @ndianabasi  wich version of Elastic you use ?

**Comment by ndianabasi** [comment]
@engcom-backlog-nazar 

I'm using Elasticsearch 5.6.14.

**Comment by ghost** [comment]
@ndianabasi  . I believe that there is a mistake in Magento DevDocs. Please look here for additional details [https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html)

It said that only 5.2.x is supported. I understand that you can provide a links where it said that 5.x is supported, but that's mistake. We are working on it.

Try to use Magento with ES 5.2.2. Feel free to reopen if this step won't help you.

**Comment by ndianabasi** [comment]
Hi @engcom-backlog-nazar. I've installed Elasticsearch 5.2.2.

Any response to why the username and password fields aren't displaying when you set **Enable Elasticsearch HTTP Auth** to "Yes"?
