### ISSUE TITLE
cms page top spacing issue at mobile

### ISSUE THREAD

**Issue by priti2jcommerce** [magento/magento2#20755]
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. Go to cms page 
2. check on mobile view

### Expected result (*)

1. 
![privacy and cookie policy - 2](https://user-images.githubusercontent.com/18118695/51893169-1ee1ef00-23ca-11e9-8da0-dcfdbecf0179.jpg)

2.

### Actual result (*)

1. 
![privacy and cookie policy - 1](https://user-images.githubusercontent.com/18118695/51893195-328d5580-23ca-11e9-9792-f65c1e5c96e1.jpg)

2.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@priti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20755-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20755-2-3-develop.instances.magento-community.engineering/admin](https://i-20755-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@priti2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97964` were created

**Issue Available**: @priti2jcommerce, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20755-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20755-2-2-develop.instances.magento-community.engineering/admin](https://i-20755-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20756 by @ranee2jcommerce in 2.3-develop branch
Related commit(s):
 - [85a5e4dcc487bbfc87ec0ff049da3254005c6dd4](https://github.com/magento/magento2/commit/85a5e4dcc487bbfc87ec0ff049da3254005c6dd4)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20781 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [7383946a868dbe8c36ffeb1605097addfb08a2f5](https://github.com/magento/magento2/commit/7383946a868dbe8c36ffeb1605097addfb08a2f5)

The fix will be available with the upcoming 2.2.9 release.
