### ISSUE TITLE
[Widgets] Bulk delete is not available

### ISSUE THREAD

**Issue by vasilii-b** [magento/magento2#20764]
### Preconditions (*)
1. Magento 2.3-develop instance
2. A couple of widget instances created under *Content -> Widgets* page in admin area

### Steps to reproduce (*)
1. Go to *Content -> Widgets* page in admin area
2. Try to delete multiple widgets at once

### Expected result (*)
You should be able to mass-delete widget instances.
![xnip2019-01-29_12-22-11](https://user-images.githubusercontent.com/13456702/51901732-0ae5bf80-23c1-11e9-8aa7-cd8a57a79b39.jpg)

### Actual result (*)
You cannot select multiple instances do delete at once.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@eduard13 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97967` were created

**Issue Available**: @eduard13, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by irajneeshgupta** [comment]
@eduard13 
Thanks for verifying the issue. Does it really takes 30 seconds to reproduce this issue on vanilla instance.

**Comment by eduard13** [comment]
Hi @irajneeshgupta, actually it's an issue which I noticed few days ago (while working with widgets), moreover this one it was inherited from 2.2 version, where such functionality is also missing.
So, yes - for me it doesn't take too much time when an issue that I'm aware of, is reported.

**Comment by orlangur** [comment]
@vasilii-b this is intentional system behavior, same as mass product deletion is not available as far as I remember. Normally you don't delete many widgets at ones.

**Comment by vasilii-b** [comment]
@orlangur how is that "normally you don't delete any widgets at once" ?! Maybe you don't. I do, and someone else is doing so as well. 
Imagine a SALE period on production website that has added a couple of widgets across the website, specifically for the sale - CMS blocks, image banners, etc. etc. After the sale ends - should that person go and delete one by one 5-10 widgets ? You're serious ? 🤔 
Would be glad to know your thoughts on this. 
Thank you!

**Comment by orlangur** [comment]
Widgets are normally not removed but used in next promotion, for example, next year. 10 widgets for one promotion does not look realistic as well while it's quite easy to open as many of them as you want and remove one-by-one.

Delete as mass action is not available to avoid data loss as this is quite a non-typical scenario. For products, widgets, maybe some other entities.

Please do not reopen until you receive a confirmation from Product Owner that such functionality is desirable.

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your report. 
The issue has been fixed in magento/magento2#20765 by @vasilii-b in 2.3-develop branch
Related commit(s):
 - [073121aaf7bc42e30f9ab19ce78ae3cb0c1c7281](https://github.com/magento/magento2/commit/073121aaf7bc42e30f9ab19ce78ae3cb0c1c7281)
 - [4376b91ff1fe7c63e1593c83e782be84891c3d42](https://github.com/magento/magento2/commit/4376b91ff1fe7c63e1593c83e782be84891c3d42)
 - [7d92ade07f0173416efc9dc4e02a76c5d19c781f](https://github.com/magento/magento2/commit/7d92ade07f0173416efc9dc4e02a76c5d19c781f)
 - [0de0857acbd46871204eb6d521f71c588e66ec6e](https://github.com/magento/magento2/commit/0de0857acbd46871204eb6d521f71c588e66ec6e)
 - [2fd6ef1c26c58f0a8b083c3a7cdd5b6aa16a0ba7](https://github.com/magento/magento2/commit/2fd6ef1c26c58f0a8b083c3a7cdd5b6aa16a0ba7)
 - [8225526e4e6223fd7d1e2e4ae8ea9fcde54e58ab](https://github.com/magento/magento2/commit/8225526e4e6223fd7d1e2e4ae8ea9fcde54e58ab)
 - [8746079fafa075b9223658d68d0b8f69f651cba3](https://github.com/magento/magento2/commit/8746079fafa075b9223658d68d0b8f69f651cba3)
 - [b56c3c43f0d00fcc4db727a652e4ccc762012796](https://github.com/magento/magento2/commit/b56c3c43f0d00fcc4db727a652e4ccc762012796)

The fix will be available with the upcoming 2.3.4 release.
