### ISSUE TITLE
Admin Customer configuraion in whishlist associated product for configurable product misalign

### ISSUE THREAD

**Issue by nainesh2jcommerce** [magento/magento2#20760]
### Preconditions (*)

1. 2.3.x
2.

### Steps to reproduce (*)

1. Go to admin
2. Customers >>All customers>> edit customer>> wishlist
3. Action Configure
### Expected result (*)

1. 
![51659410-60d8f280-1fd0-11e9-88f7-e6e4e1123c06](https://user-images.githubusercontent.com/18118539/51897869-b862ce00-23d5-11e9-86e0-9fe9a097b243.jpg)

2.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/18118539/51897928-d0d2e880-23d5-11e9-873f-137779900f86.png)

2.

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nainesh2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nainesh2jcommerce** [comment]
issue reproduce
![image](https://user-images.githubusercontent.com/18118539/51898374-c9600f00-23d6-11e9-80bc-79516db7a4c2.png)

**Comment by magento-engcom-team** [comment]
@nainesh2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97965` were created

**Issue Available**: @nainesh2jcommerce, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20558 by @priti2jcommerce in 2.3-develop branch
Related commit(s):
 - [7495afbc8c78e9a27292a5f358a243363b9c6050](https://github.com/magento/magento2/commit/7495afbc8c78e9a27292a5f358a243363b9c6050)
 - [565f6250b427b30dc2db9f09f1e59a521dbc5479](https://github.com/magento/magento2/commit/565f6250b427b30dc2db9f09f1e59a521dbc5479)

The fix will be available with the upcoming 2.3.1 release.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-20760-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20760-2-3-develop.instances.magento-community.engineering/admin](https://i-20760-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-20760-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20760-2-2-develop.instances.magento-community.engineering/admin](https://i-20760-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21173 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [e9102ecb206fd19b73493b0f7e1e00dbc92d661f](https://github.com/magento/magento2/commit/e9102ecb206fd19b73493b0f7e1e00dbc92d661f)
 - [17d416a1d0fda6d3d2cc8730198d354a56ce4923](https://github.com/magento/magento2/commit/17d416a1d0fda6d3d2cc8730198d354a56ce4923)
 - [5d42fa8d04ba2fe7ad45ad5a2a6e79f6d0cf0ebe](https://github.com/magento/magento2/commit/5d42fa8d04ba2fe7ad45ad5a2a6e79f6d0cf0ebe)

The fix will be available with the upcoming 2.2.9 release.
