### ISSUE TITLE
Grunt workflow documentation has errors

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#20779]
### Summary (*)

Grunt workflow documentation has errors.

### Examples (*)

I followed the docs on how to set up grunt for a custom theme. Specifically a theme that inherits from a parent theme. In point 5 the [documentation](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css_debug.html) states:

> You need to specify all root source files of the theme. If your theme [inherits] from a certain theme, and does not contain its own root source files, specify the root source files of the parent theme.

This is incorrect though. You have to specify the parent themes root source files either way. If you just specify the child's root source files grunt watch will not re-compile styles-m.css and styles-l.css and therefore your changes are not reflected on the site. 

See #20356 for details which I filed earlier because I thought I encountered a bug.

My theme inheritance:
ac_retail inherits from ac_default inherits from luma and
ac_wholesale inherits from ac_default inherits from luma

This local-themes.js finally works correctly in that it re-compiles styles-m.css and styles-l.css when the child themes less files change:

```
>>'use strict';                                                                    
>>module.exports = {                                                               
      ac_default: {                                                                
          area: 'frontend',                                                        
          name: 'Ac/Default',                                                      
          locale: 'en_US',                                                         
          files: [                                                                 
              'css/styles-m',                                                      
              'css/styles-l',                                                         
          ],                                                                          
          dsl: 'less'                                                                 
      },                                                                              
      ac_retail: {                                                                    
          area: 'frontend',                                                           
          name: 'Ac/Retail',                                                       
          locale: 'en_US',                                                         
          files: [                                                                 
              'css/styles-m',                                                      
              'css/styles-l',                                                      
          ],                                                                       
          dsl: 'less'                                                              
      },                                                                           
      ac_wholesale: {                                                              
          area: 'frontend',                                                        
          name: 'Ac/Wholesale',                                                    
          locale: 'en_US',                                                         
          files: [                                                                 
              'css/styles-m',                                                      
              'css/styles-l',                                                      
          ],                                                                       
          dsl: 'less'                                                              
      }                                                                            
  };  
```

### Proposed solution

Fix the error in the documentation. Please consider improving the documentation for key development aspects like the Grunt workflow. More examples for different use cases would be helpful.

**Comment by magento-engcom-team** [comment]
Hi @MichaelThessel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MichaelThessel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@suryakant-krish Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@irajneeshgupta Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97977` were created

**Issue Available**: @irajneeshgupta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by irajneeshgupta** [comment]
@MichaelThessel 
you can move the issue here ->
https://github.com/magento/devdocs

**Comment by ghost** [comment]
@irajneeshgupta so why confirmed ? as this is devdocs bug ?

**Comment by irajneeshgupta** [comment]
@engcom-backlog-nazar 
yes it is devdocs issue, hence i requested him to move it to devdocs repo.
i assumed that labels should also moved while transferring issue.
