### ISSUE TITLE
Upgrade 2.3.0 - Base table or view not found queue

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#20771]
Hi, 

Magento's upgrade from 2.2.3 to 2.3.0 is blocked due to  MySQL error

### Preconditions

1. Magento 2.2.3
2. Upgrade to Magento 2.3.0 using upgrade script
3. PHP 7.1
4. MySQL version 10.0.37-MariaDB-1~xenial with innodb_version 5.6.39-84.1

### Steps to reproduce

1. Install Magento 2.2.3
2. Upgrade to Magento 2.3.0 using upgrade script
3. Run `php bin/magento setup:upgrade` command

### Expected result

1. The database upgrade should process correctly

### Actual result

1. An error happens on "Magento_MysqlMq" module : 
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'peugeotsaveurs_230.queue' doesn't exist, query was: SELECT `queue`.`name` FROM `queue`
![image](https://user-images.githubusercontent.com/3015249/51919440-b4d64380-23e3-11e9-867a-791053bad6c6.png)

**Comment by magento-engcom-team** [comment]
Hi @Axel29. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Axel29 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Axel29** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Axel29. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Axel29, here is your [Magento instance](https://i-20771-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20771-2-2-develop.instances.magento-community.engineering/admin](https://i-20771-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Axel29** [comment]
Hi,

I can't reproduce this on a fresh installation.
After puttin manually the "queue" table, the setup:upgrade command worked BUT I noticed that none of the new declarative schema tables were created.

It seems like something is blocking them, any idea of what could do that please?

Thank you,

Axel

**Comment by ghost** [comment]
Hi @Axel29 i'm also not able to reproduce following steps you described, maybe this related to some of your custom modules ?

**Comment by Axel29** [comment]
Hi,

If someone else faces this issue, I finally found the reason why it wasn't working.
I've made a fresh install of Magento 2.2.3 that I've upgraded to Magento 2.3.0 on a side project, and used a rsync to show differences.

It seems like the directory "setup" wasn't updated correctly on my project when I upgraded it, which was the reason why the `bin/magento setup:upgrade` command failed for some reason.

**Comment by Salayka** [comment]
Getting this same error for this table in same conditions. What did you notice was not setup correctly?

**Comment by Axel29** [comment]
> Getting this same error for this table in same conditions. What did you notice was not setup correctly?

Did you try getting "setup" directory from Magento's repo (at your version)?
For me the problem was that many files from there (and "lib" from memory) were deleted by the upgrade when they shouldn't have been. 
Updating the sources from Magento's repo fixed the issue for me.

**Comment by Axel29** [comment]
@stoya42

> Getting this same error for this table in same conditions. What did you notice was not setup correctly?

Did you try getting "setup" directory from Magento's repo (at your version)?
For me the problem was that many files from there (and "lib" from memory) were deleted by the upgrade when they shouldn't have been. 
Updating the sources from Magento's repo fixed the issue for me.

**Comment by Sharmilasrini95** [comment]
i am getting the same error.i replaced the setup module.but it doesn't work
