### ISSUE TITLE
Luma theme My Wish List page Edit and Remove icons consistency design improvement 

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#20790]
### Preconditions (*)

1. Magento 2.3 and Magento 2.2.X

### Steps to reproduce (*)

1. Add Item in the wishlist 
2. Go to wishlist page you can see edit and delete link instead of icons 

### Expected result (*)

1. http://prntscr.com/me4lwq

### Actual result (*)

1. http://prntscr.com/me4cj0

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [x] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by saphaljha** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @saphaljha, here is your [Magento instance](https://i-20790-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20790-2-3-develop.instances.magento-community.engineering/admin](https://i-20790-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by milindsingh** [comment]
@abrarpathan19 I think its different context, hence icons are not needed.
@engcom-backlog-nazar I think this is feature improvement which might not always be needed.

**Comment by magento-engcom-team** [comment]
@saphaljha Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@saphaljha Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97983`, `MAGETWO-97984` were created

**Issue Available**: @saphaljha, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @abrarpathan19 thank you for your report, can you explain in which cases you need this and why this an issue ?

**Comment by abrarpathan19** [comment]
@magento-engcom-team It is design improvement on wishlist page remove & delete icons consistency as per the entire luma theme.

**Comment by ghost** [comment]
@abrarpathan19 as i can see the mini cart contain icons because this the mini-cart there no space to show full text button, but why on wish list we need this changes ?

**Comment by abrarpathan19** [comment]
@engcom-backlog-nazar 
Yes, It is necessary to change the text to an icon on the wishlist page there are many reasons : 

1) First at the entire luma theme should have the same UI consistency and uniformity design.
2) In wishlist blog also have space issue same like minicart when we use the stores/website in different languages for examples in FR or DE. http://prntscr.com/me6jwd
3) As per the user point of view, it should be icons. 

Thanks.

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@engcom-backlog-nazar Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#20791 by @abrarpathan19 in 2.3-develop branch
Related commit(s):
 - [5f258f2ca735ec951fca8945d379e6ffc063438d](https://github.com/magento/magento2/commit/5f258f2ca735ec951fca8945d379e6ffc063438d)
 - [f4e9176a17f5a9bd3efd2bba08e2840bafeffe37](https://github.com/magento/magento2/commit/f4e9176a17f5a9bd3efd2bba08e2840bafeffe37)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#21118 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [b24df575092f94e94688cbb93f2efe0e49b7ba57](https://github.com/magento/magento2/commit/b24df575092f94e94688cbb93f2efe0e49b7ba57)
 - [a3535662fafb1d4355e7db851a46c60d21f08ae3](https://github.com/magento/magento2/commit/a3535662fafb1d4355e7db851a46c60d21f08ae3)
 - [abc1d24dd5594b4a1eeb736309f5be9d52b98c8a](https://github.com/magento/magento2/commit/abc1d24dd5594b4a1eeb736309f5be9d52b98c8a)
 - [330d202567bf262040d6997a71e4e42505915a41](https://github.com/magento/magento2/commit/330d202567bf262040d6997a71e4e42505915a41)

The fix will be available with the upcoming 2.2.9 release.
