### ISSUE TITLE
Error while submitting marketplace keys

### ISSUE THREAD

**Issue by LBeekie** [magento/magento2#20795]
I have a server from versio. I have installed magento through the app installer (softaculous) in DirectAdmin. Everything is working fine except the described error. I already did a clean install, but the error stays the same.

**Preconditions**
Magento version: 2.3.0
PHP version: 7.2.13
MySQL version: 
HTTP/2 is supported

**Steps to reproduce**
1. Get marketplace access keys 
2. Go to the setup wizard
3. Click extension manager
4. Fill in public and private key
5. Click submit

**Expected result**
When the submit button is pressed the keys are saved and I can use the wizard setup for adding extensions.

**Actual result**
See image: Invalid response line returned from server: HTTP/2 200 
![image](https://user-images.githubusercontent.com/7432031/51974468-485d5200-2480-11e9-84ca-bdda6d8648d0.png)

**Comment by magento-engcom-team** [comment]
Hi @LBeekie. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LBeekie do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LBeekie** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LBeekie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LBeekie, here is your [Magento instance](https://i-20795-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20795-2-3-develop.instances.magento-community.engineering/admin](https://i-20795-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by LBeekie** [comment]
Ok. So I tested this on the vanilla Magento instance and it works.
There is something wrong with my own server configuration and I have no idea what. Any solutions?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @LBeekie . Thank you for your report. 
The issue has been fixed in magento/magento2#19143 by @vovayatsyuk in 2.3-develop branch
Related commit(s):
 - [e827b3220c12cc8e793e0486cd9425e4ca4c2853](https://github.com/magento/magento2/commit/e827b3220c12cc8e793e0486cd9425e4ca4c2853)

The fix will be available with the upcoming 2.3.1 release.

**Comment by LBeekie** [comment]
Ok, thanks.
