### ISSUE TITLE
Magento 2.2.5, Header link is Displaying the login link even after login

### ISSUE THREAD

**Issue by saravanandscbe** [magento/magento2#20792]
### Preconditions (*)

1. Install Magento ver 2.2.5

### Steps to reproduce (*)

1. Login to front end with customer data.
2. Check the header link. It is showing Sign in only even after logged In.
3. I tried this code too.

```
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
            if(!$customerSession->isLoggedIn()) {
        ?>
            <li class="level0 nav-8 last level-top ui-menu-item" role="presentation"><a href="<?php echo $storeManager->getStore()->getUrl('customer/account/login');?>" class="level-top ui-corner-all" id="ui-id-9" tabindex="-1" role="menuitem"><span><?php echo __("Login")?></span></a>
            </li>
        <?php
            }else{
        ?>
        <li class="level0 nav-8 last level-top ui-menu-item" role="presentation"><a href="<?php echo $storeManager->getStore()->getUrl('customer/account');?>" class="level-top ui-corner-all" id="ui-id-9" tabindex="-1" role="menuitem"><span><?php echo __("My Account")?></span></a>
        <ul class="logout-wrap"><li class="" role="menuitem"><a href="<?php echo $storeManager->getStore()->getUrl('customer/account/logout');?>" class="level-top ui-corner-all" id="ui-id-10" tabindex="-1" role="menuitem"><span><?php echo __("Logout")?></span></a></span></li></ul>
        </li>
    <?php
        }
    ?>
```

### Expected result (*)

1. Should display the My Account, Wish List and Sign Out links.

### Actual result (*)

1. Header Link is showing Login link. I checked by disabling Page Cache in backend.

**Comment by magento-engcom-team** [comment]
Hi @saravanandscbe. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@saravanandscbe do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ravi-chandra3197** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197, here is your [Magento instance](https://i-20792-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20792-2-3-develop.instances.magento-community.engineering/admin](https://i-20792-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ravi-chandra3197** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197, here is your [Magento instance](https://i-20792-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20792-2-2-develop.instances.magento-community.engineering/admin](https://i-20792-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ravi-chandra3197** [comment]
Hello @magento-engcom-team @saravanandscbe 
I have tried to reproduce the issue in 2.2 and 2.3 using the above step 
but this issues does not reproduce in 2.2 and 2.3

**Comment by saravanandscbe** [comment]
@ravi-chandra3197 @magento-engcom-team . I added custom phtml(topmenu.phtml) file with below content. It is having this issue.

```
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
            if(!$customerSession->isLoggedIn()) {
        ?>
            <li class="level0 nav-8 last level-top ui-menu-item" role="presentation"><a href="<?php echo $storeManager->getStore()->getUrl('customer/account/login');?>" class="level-top ui-corner-all" id="ui-id-9" tabindex="-1" role="menuitem"><span><?php echo __("Login")?></span></a>
            </li>
        <?php
            }else{
        ?>
        <li class="level0 nav-8 last level-top ui-menu-item" role="presentation"><a href="<?php echo $storeManager->getStore()->getUrl('customer/account');?>" class="level-top ui-corner-all" id="ui-id-9" tabindex="-1" role="menuitem"><span><?php echo __("My Account")?></span></a>
        <ul class="logout-wrap"><li class="" role="menuitem"><a href="<?php echo $storeManager->getStore()->getUrl('customer/account/logout');?>" class="level-top ui-corner-all" id="ui-id-10" tabindex="-1" role="menuitem"><span><?php echo __("Logout")?></span></a></span></li></ul>
        </li>
    <?php
        }
    ?>
```

**Comment by nainesh2jcommerce** [comment]
Hi @saravanandscbe, we can't reproduce issue for custom work, only issue with vanilla instance is valid.

thanks!

**Comment by ghost** [comment]
Hi @saravanandscbe   i'm not able to reproduce following steps your described, 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
