### ISSUE TITLE
Unable to add new review from backend

### ISSUE THREAD

**Issue by SatishDubariya** [magento/magento2#20796]
### Preconditions (*)

1. Magento 2.3.0
2. PHP Version 7.2.14

### Steps to reproduce (*)

1. Login to Magento backend.
2. Navigate to Marketing > Reviews 
3. Click on New Review Button
4 Select Product from the Product grid.

### Expected result (*)

1. Display New Review form with pre-filled Product field with Selected product name.
2 After filling other fields  when  save, it should be saved and appeared in grid with Success message.

### Actual result (*)

1. Display New Review form with pre-filled Product field with "product_name" text.
2. After filling other fields, when save it display success message but review does not appear in grid.
![review-1](https://user-images.githubusercontent.com/21054477/51975384-1233c880-24a8-11e9-8d1a-ed4c705df037.png)
![review-2](https://user-images.githubusercontent.com/21054477/51975383-1233c880-24a8-11e9-8809-4d0ab35c1cb0.png)

**Comment by magento-engcom-team** [comment]
Hi @SatishDubariya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@SatishDubariya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team please provide 2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment]
Hi @SatishDubariya ,this issue is alreday reported, check this #20122

**Comment by SatishDubariya** [comment]
Ok. Thank you for quick response.

**Comment by ghost** [comment]
Hi @SatishDubariya . Thank you for your report. 
The issue has been fixed in magento/magento2#20146 by @suneet64 in 2.3-develop branch
Related commit(s):
 - [da809e36e486ccaa02217b2b1b31df6a01745f93](https://github.com/magento/magento2/commit/da809e36e486ccaa02217b2b1b31df6a01745f93)
 - [130f1ae59221964dd6c74ebf0545828cbed9a583](https://github.com/magento/magento2/commit/130f1ae59221964dd6c74ebf0545828cbed9a583)
 - [eed3bc376b8afa124effb1870fd2ab20ac433b14](https://github.com/magento/magento2/commit/eed3bc376b8afa124effb1870fd2ab20ac433b14)

The fix will be available with the upcoming 2.3.1 release.
