### ISSUE TITLE
On account my recent reviews alignment issue

### ISSUE THREAD

**Issue by priti2jcommerce** [magento/magento2#20800]
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. add reviews with logged in customer 
2. on my account dashboard 
3. reviews alignment not proper (vertically)

### Expected result (*)

1. 
![2019-01-30_16-50_my account 2](https://user-images.githubusercontent.com/18118695/51978264-bf5e0f00-24af-11e9-8146-80baedf592f2.jpg)

### Actual result (*)

1. 
![2019-01-30_16-50_my account](https://user-images.githubusercontent.com/18118695/51978276-c6851d00-24af-11e9-9365-84c506f01fa6.jpg)

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@priti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nainesh2jcommerce** [comment]
issue reproduce on previously provided instance
![image](https://user-images.githubusercontent.com/18118539/51978664-c0dc0700-24b0-11e9-8bb7-0bd121e3ea2f.png)

**Comment by magento-engcom-team** [comment]
@nainesh2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97985` were created

**Issue Available**: @nainesh2jcommerce, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by rogyar** [comment]
@priti2jcommerce @nainesh2jcommerce could you provide more information regarding this issue, please? The difference between these two screenshots is in a slightly increased gap between the summary and the rating starts.
The question is why the current space between the two mentioned elements is incorrect? I believe the good point here would be mentioning relations (i.e. the gap here should be increased because other elements on the page have the same gap).
Thank you

**Comment by priti2jcommerce** [comment]
Hi @rogyar 

there is  vertical alignment issue
![image](https://user-images.githubusercontent.com/18118695/51984139-9b56f980-24c0-11e9-9128-bd6f7400551f.png)

**Comment by rogyar** [comment]
Hi @priti2jcommerce. Thank you for the clarification. Could you provide more details (via text) why do you consider this alignment as an issue? Do the other elements on this page have different alignment rules? Thank you.

**Comment by priti2jcommerce** [comment]
Hi @rogyar ,

I have checked and found that there is text going to top and rating on bottom, that is not looking proper at the browser that's why consider as a bug and other text look vertically centered.
Please review
Thanks!

**Comment by rogyar** [comment]
Thank you for the details

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20801 by @priti2jcommerce in 2.3-develop branch
Related commit(s):
 - [3dc4f9b3de87943580b100c41cfeec99fe857ff7](https://github.com/magento/magento2/commit/3dc4f9b3de87943580b100c41cfeec99fe857ff7)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21172 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [a16427dbf793d530491c3969f77e085a1208d3ce](https://github.com/magento/magento2/commit/a16427dbf793d530491c3969f77e085a1208d3ce)

The fix will be available with the upcoming 2.2.9 release.
