### ISSUE TITLE
Advanced Search layout not proper

### ISSUE THREAD

**Issue by amol2jcommerce** [magento/magento2#20809]
### Preconditions (*)

1. Magento 2.3.0

### Steps to reproduce (*)

1. Click Advanced Search link in footer

### Expected result (*)

1. 
![advanced search - 2](https://user-images.githubusercontent.com/18118631/51982769-e969fe00-24bc-11e9-95a9-a763b74d0ac5.jpg)

### Actual result (*)

1. 
![advanced search - 1](https://user-images.githubusercontent.com/18118631/51982792-f5ee5680-24bc-11e9-9e1a-efa76d1ae551.jpg)

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@amol2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
@amol2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97987` were created

**Issue Available**: @amol2jcommerce, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by milindsingh** [comment]
@amol2jcommerce What's not proper in the full page design?
@engcom-backlog-nazar I think a issue must be verified by more 1 contributor, to make sure that's it's actually a issue.

**Comment by amol2jcommerce** [comment]
Hi @milindsingh, @engcom-backlog-nazar when you check customer registration page and contact us page design are same but not advance search page design.

Customer Registration page
![2019-01-30_22-30_create new customer account](https://user-images.githubusercontent.com/18118631/51998660-116a5900-24df-11e9-85b5-c416fdee13f0.jpg)

Contact Us page
![2019-01-30_22-31_contact us](https://user-images.githubusercontent.com/18118631/51998666-13ccb300-24df-11e9-8cc6-73e8745f35dd.jpg)

Hence we create a Issue and this page design also same as per both design.
Like:
![2019-01-30_22-37_advanced search](https://user-images.githubusercontent.com/18118631/51998987-c735a780-24df-11e9-8a99-5cabf79bd44c.jpg)


Thanks

**Comment by cedarvinda** [comment]
@amol2jcommerce You doing same changes in same file with different PR
https://github.com/magento/magento2/pull/20810/commits/f12116e56e4c77ae0852a3af47f0878baebdd1b8

https://github.com/magento/magento2/pull/20817/commits/604ab26369ae150e108825f26e14a4a9a10268fe

If you have done in PR #20810, Then no need for #20817 PR.

@engcom-backlog-nazar Please check, Right now I am closing #20817
@amol2jcommerce If you have any query please reach with me Thankyou.

**Comment by amol2jcommerce** [comment]
@cedarvinda why you close PR ?
Are you sure both PR changes are same? No different?
@engcom-backlog-nazar please check.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by rogyar** [comment]
I believe it's a good idea to have the same layout for all basic forms

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21611 by @amol2jcommerce in 2.3-develop branch
Related commit(s):
 - [13991bbefd2ad895c4d6047d8c0e4675130ca8f6](https://github.com/magento/magento2/commit/13991bbefd2ad895c4d6047d8c0e4675130ca8f6)
 - [1f0f7a1b920a1289bffa5c1ffa9a415c264bef61](https://github.com/magento/magento2/commit/1f0f7a1b920a1289bffa5c1ffa9a415c264bef61)
 - [caa0727f1913f916fdba56b06b415b1e66e82aa8](https://github.com/magento/magento2/commit/caa0727f1913f916fdba56b06b415b1e66e82aa8)
 - [23e7e36ca80b59899fc67a5288c3860d13dfca67](https://github.com/magento/magento2/commit/23e7e36ca80b59899fc67a5288c3860d13dfca67)

The fix will be available with the upcoming 2.3.2 release.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-20809-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20809-2-2-develop.instances.magento-community.engineering/admin](https://i-20809-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21892 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [67b732c00de7a3720d342d945099ede93b600ef7](https://github.com/magento/magento2/commit/67b732c00de7a3720d342d945099ede93b600ef7)
 - [af75c5abe40b169dea6f798b081ef00d3007b7a3](https://github.com/magento/magento2/commit/af75c5abe40b169dea6f798b081ef00d3007b7a3)

The fix will be available with the upcoming 2.2.9 release.
