### ISSUE TITLE
Card Holder Name field in cc-form?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#20805]
### Preconditions (*)
1. Magento 2.3.0

### Steps to reproduce (*)
1.With a custom payment method that uses vendor/magento/module-payment/view/frontend/web/template/payment/cc-form.html, there is no field for Card Holder Name.

I have been taking this value from billing address fields, but I need to add another field instead 'Card Holder Name' (or something like Name on Card) to vendor/magento/module-payment/view/frontend/web/template/payment/cc-form.html

There doesn't appear to be a way to do this without replacing the cc-form in my own module.

### Expected result (*)
1. Card Holder Name field to appear in vendor/magento/module-payment/view/frontend/web/template/payment/cc-form.html

2. This is typical of most checkout processes where card holder name appears next to card number, cvv etc.

3. Make this an option?

4. This data is stored in cc_owner field in sales_order_payment

### Actual result (*)
1. No Card Holder Name field

e.g. 

```
<!-- ko if: (hasCardHolderName())-->
    <div class="field number required">
        <label data-bind="attr: {for: getCode() + '_cc_owner'}" class="label">
            <span><!-- ko i18n: 'Card Holder Name'--><!-- /ko --></span>
        </label>
        <div class="control">
            <input type="text" name="payment[cc_owner]" class="input-text" value=""
                   data-bind="attr: {
                                    autocomplete: off,
                                    id: getCode() + '_cc_owner',
                                    title: $t('Card Holder Name'),
                                    'data-container': getCode() + '-cc-owner',
                                    'data-validate': JSON.stringify({'required-entry':true})},
                              enable: isActive($parents),
                              value: creditCardOwner,
                              valueUpdate: 'keyup' "/>
        </div>
    </div>
    <!-- /ko -->
```

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
Hi @craigcarnell thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features
