### ISSUE TITLE
Error with editing user roles - Undefined Index title

### ISSUE THREAD

**Issue by asim-vax** [magento/magento2#20813]
### Preconditions
1. ubuntu 18.04/18.10 php 7.1
2. magento CE 2.3.0

### Steps to reproduce

1. log into admin panel
2. system -> user roles
3. click any user role

### Expected result
1.  screen to edit clicked on user role permissions

### Actual result
1. blank page
2. error in system.log - Notice: Undefined index: title in /home/alex/Documents/Vax/sites/www/oreck2/vendor/magento/module-integration/Helper/Data.php on line 24 [] []

**Comment by magento-engcom-team** [comment]
Hi @asim-vax. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@asim-vax do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by asim-vax** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @asim-vax. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @asim-vax, here is your [Magento instance](https://i-20813-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20813-2-3-develop.instances.magento-community.engineering/admin](https://i-20813-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by asim-vax** [comment]
Closing due to issue with local instance, not core magento
