### ISSUE TITLE
Orders and Returns layout not proper

### ISSUE THREAD

**Issue by yashwant2jcommerce** [magento/magento2#20816]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Click Orders and Returns link in footer

### Expected result (*)

1. 
![orders and returns - 1](https://user-images.githubusercontent.com/26630846/51989469-20e0a680-24cd-11e9-8fc5-740902145893.jpg)

### Actual result (*)

1. 
![orders and returns - 2](https://user-images.githubusercontent.com/26630846/51989488-305fef80-24cd-11e9-9ea9-f161cbe882be.jpg)

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@yashwant2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [Magento instance](https://i-20816-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20816-2-3-develop.instances.magento-community.engineering/admin](https://i-20816-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@amol2jcommerce Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97988` were created

**Issue Available**: @amol2jcommerce, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#20817 by @amol2jcommerce in 2.3-develop branch
Related commit(s):
 - [604ab26369ae150e108825f26e14a4a9a10268fe](https://github.com/magento/magento2/commit/604ab26369ae150e108825f26e14a4a9a10268fe)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21163 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [ce53cee6adf5a58978333e42e9c4bc8309e0c0cb](https://github.com/magento/magento2/commit/ce53cee6adf5a58978333e42e9c4bc8309e0c0cb)

The fix will be available with the upcoming 2.2.9 release.

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce, @amol2jcommerce. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24346` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
