### ISSUE TITLE
Cannot add required field to Attribute using InstallScript

### ISSUE THREAD

**Issue by ghost** [magento/magento2#20854]
### Preconditions (*)
1. Magento Version 2.3

### Steps to reproduce (*)
1. Install Magento 2.3
2. Create a basic module (registration.php/module.xml)
3. Create InstallData.php under Setup directory
4. Add the below code into InstallData.php
```
<?php

namespace Namespace\Module\Setup;

use Magento\Eav\Setup\EavSetupFactory;
use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class InstallData implements InstallDataInterface
{
    private $eavSetupFactory;

    public function __construct(EavSetupFactory $eavSetupFactory)
    {
        $this->eavSetupFactory = $eavSetupFactory;
    }

    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $setup->startSetup();

        $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);

        $eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'promo_banner_image',
            [
                'filterable' => true,
                'input' => 'media_image',
                'group' => 'Images',
                'label' => 'Promo Banner Image',
                'visible_on_front' => false,
                'required' => false,
            ]
        );

        $setup->endSetup();
    }
}
```

### Expected result (*)
1. 'is_required' column within the 'eav_attribute' table to be set to 0 for the installed attribute

### Actual result (*)
1. 'is_required' column within the 'eav_attribute' table is actually set to 1 for the installed attribute

**Comment by magento-engcom-team** [comment]
Hi @ajduff14. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ajduff14 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ajduff14 thank you for your report is this only with install script ? or also with upgrade data?

**Comment by ghost** [comment]
Hi, I only know that this is the case with the install script. It's possible it could also be upgrade but I have not tested this.

**Comment by ghost** [comment]
@ajduff14 ok thanks, because i'm have a several attributes with upgrade script and this works perfectly.

**Comment by ghost** [comment]
@ajduff14 i'm not able to reproduce following steps you described, maybe this related to some custom modules ?
![selection_308](https://user-images.githubusercontent.com/40756439/52056704-9bf89a00-256b-11e9-8995-c2fb8260e75c.png)

**Comment by ghost** [comment]
You are most likely right! Thanks for your time.

**Comment by ghost** [comment]
@ajduff14 can we close ticket ? or you can always reopen, if had some additional info.

**Comment by ghost** [comment]
I will close the ticket. Thanks again.
