### ISSUE TITLE
Path "/var/www/vhosts/xx-uk2-staging/releases/20190131130846/var/" cannot be used with directory "/var/www/vhosts/xx-uk2-staging/releases/20190131130846/var/

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#20857]
### Preconditions (*)
1. Magento 2.3.0
2. PHP 7.2.14

### Steps to reproduce (*)
1. Deploy magento 2 via capistrano-magento2
2. View system.log or support_report.log:

```
[2019-01-31 13:34:39] report.ERROR: Path "/var/www/vhosts/xx-uk2-staging/releases/20190131130846/var/" cannot be used with directory "/var/www/vhosts/xx-uk2-staging/releases/20190131130846/var/" [] []
[2019-01-31 13:34:39] report.CRITICAL: Path "/var/www/vhosts/xx-uk2-staging/releases/20190131130846/var/" cannot be used with directory "/var/www/vhosts/xx-uk2-staging/releases/20190131130846/var/" [] []
```

The paths are the same??

### Expected result (*)
1. No error as folder is the same!

### Actual result (*)
1. As steps to reproduce

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @craigcarnell 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by cscd98** [comment]
@engcom-backlog-nazar This is a core magento issue..

**Comment by ghost** [comment]
@craigcarnell ok so how we can reproduce this with clean magento ?

**Comment by cscd98** [comment]
@engcom-backlog-nazar I'm not sure how to reproduce, however it's quite an erroneous error - the paths are the same..

**Comment by ghost** [comment]
@craigcarnell ok i'm will recheck with   capistrano-magento2

**Comment by cscd98** [comment]
@engcom-backlog-nazar I can create this issue also by trying to generate a sitemap in the back end.

**Comment by ghost** [comment]
@craigcarnell i'm try to search the problem but im still not able to reproduce, and found that this error appears if you real path !== path (/home/ == /var/home/) so if you have this condition with true, the error appear.
![selection_311](https://user-images.githubusercontent.com/40756439/52112301-c18aaf80-260e-11e9-8104-e1ac70cd5ed2.png)

**Comment by ghost** [comment]
@craigcarnell the real problem that they must not be the **SAME**

**Comment by ghost** [comment]
@craigcarnell have you some custom modules ? because magento dosen't write exception to log file, just stack on error, so i think one of the custom module provide this exception you can evaluate expression with you folders http://micmap.org/php-by-example/en/function/mb_strpos and this returns 0 so magento don't give you error.

**Comment by ghost** [comment]
@craigcarnell i'm closing this issue, because i'm unable to reproduce, if you have some additional info how we can reproduce this with clean magento please reopen the issue.
