### ISSUE TITLE
Luma theme - Input Box and Radio Button shadow is not proper

### ISSUE THREAD

**Issue by saphaljha** [magento/magento2#20859]
### Preconditions (*)

1.Magento 2.3 and Magento 2.2.X

### Steps to reproduce (*)

1. Magento luma theme frontend in all the form 
2. You can find checkbox, Radio input box shaddow
Reproduce pages : create account page, cart page and chekout page

### Expected result (*)

1. Screenshot URL: http://prntscr.com/menfs1

### Actual result (*)

1. Screenshot URL: http://prntscr.com/mennmt

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@saphaljha do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mage2pratik** [comment]
![reproduce](https://user-images.githubusercontent.com/33807558/52058882-65804680-258e-11e9-818f-7132ddc4f4ab.jpg)
![reproduce1](https://user-images.githubusercontent.com/33807558/52058892-6c0ebe00-258e-11e9-9e38-7ad59990039d.jpg)

**Comment by magento-engcom-team** [comment]
@mage2pratik Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @mage2pratik
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @mage2pratik
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @nainesh2jcommerce
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by mage2pratik** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by mage2pratik** [comment]
@magento-engcom-team : I've reviewed in my local 2.3-develop, 2.2-develop latest instance and also reproduced and added screenshots. Kindly have a look.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @mage2pratik
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by mage2pratik** [comment]
@magento-engcom-team : As I've confirmed the issue but not able to add **Issue: Confirmed** label.

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @mage2pratik
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @amol2jcommerce
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98019`, `MAGETWO-98020` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your report. 
The issue has been fixed in magento/magento2#20861 by @abrarpathan19 in 2.3-develop branch
Related commit(s):
 - [5f258f2ca735ec951fca8945d379e6ffc063438d](https://github.com/magento/magento2/commit/5f258f2ca735ec951fca8945d379e6ffc063438d)
 - [394665fd154f83f874042c844fd4cab983b591a3](https://github.com/magento/magento2/commit/394665fd154f83f874042c844fd4cab983b591a3)
 - [2cf9413cf14f72246581866b3fdfd70591ef634c](https://github.com/magento/magento2/commit/2cf9413cf14f72246581866b3fdfd70591ef634c)

The fix will be available with the upcoming 2.3.1 release.

**Comment by dmytro-ch** [comment]
Hi guys,
it looks like the latest changes violate accessibility standards by complicating the navigation through a keyboard interface.

https://www.w3.org/TR/WCAG20/#keyboard-operation

The purpose of this shadow is to highlight the focus on the element. And as for me, we have nothing to fix here. :)
After the latest fixes, it's hard to guess which element is under focus.

Shouldn't we revert these changes?

@sidolov @VladimirZaets

**Comment by abrarpathan19** [comment]
@dmytro-ch As per your suggestion, we can do manage shadow design: http://prntscr.com/mjws42

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-20859-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20859-2-3-develop.instances.magento-community.engineering/admin](https://i-20859-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your report. 
The issue has been fixed in magento/magento2#21851 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [f8b9147302c6a5c81ee180f13ebc2bc544c5fea3](https://github.com/magento/magento2/commit/f8b9147302c6a5c81ee180f13ebc2bc544c5fea3)

The fix will be available with the upcoming 2.3.2 release.
