### ISSUE TITLE
Payment page not loading

### ISSUE THREAD

**Issue by meichenblatt** [magento/magento2#20867]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

1. Go to https://www.lms.sohotest.com/
2. Add a product to the cart 
3. In the cart select "proceed to checkout"
4. Fill in shipment information and click next

### Expected result (*)

1. Go to payment page

### Actual result (*)

1. Spinner runs but it doesn't go to the next page.
2. In the console there is an error being thrown:
plugin.min.js:1 Uncaught TypeError: steps.sort(...).forEach is not a function
    at Object.target.next (plugin.min.js:1)
    at Object.<anonymous> (shipping.min.js:4)
    at fire (jquery.min.js:212)
    at Object.fireWith [as resolveWith] (jquery.min.js:218)
    at done (jquery.min.js:628)
    at XMLHttpRequest.callback (jquery.min.js:655)

This is the content of plugin.min.js:
define(function(){'use strict';return function(target){var steps=target.steps;target.next=function(){var activeIndex=0;steps.sort(this.sortItems).forEach(function(element,index){if(element.isVisible()){element.isVisible(false);activeIndex=index;}});if(steps().length>activeIndex+1&&'undefined'!==typeof AEC){var code=steps()[activeIndex+1].code;AEC.checkoutStep(activeIndex,activeIndex+1,code);steps()[activeIndex+1].isVisible(true);window.location=window.checkoutConfig.checkoutUrl+"#"+code;document.body.scrollTop=document.documentElement.scrollTop=0;}}
return target;};});

Is anybody else having this issue?

Thanks!

**Comment by magento-engcom-team** [comment]
Hi @meichenblatt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@meichenblatt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-20867-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20867-2-3-develop.instances.magento-community.engineering/admin](https://i-20867-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@meichenblatt This is not reproduced on current Magento 2.3-develope instace . This issue may be due to some customization at your server.

**Comment by meichenblatt** [comment]
Thank you! We think we cornered it down to one of our modules. I appreciate the help.

**Comment by matthewhaworth** [comment]
@meichenblatt  which module mate?
