### ISSUE TITLE
Magento 2.2.7 Databse Deadlock Occurs When Cron Jobs Are Not Automatically Cleared

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#20871]
There appears to be a problem with cron job creation which eventually leads to a database deadlock

### Preconditions (*)

1. Magento 2.2.7
2. 

### Steps to reproduce (*)

1. Vanilla Magento 2.2.7
2. Set up cron jobs per Magento documentation

### Expected result (*)

1. Cron jobs run smoothly without deadlock

### Actual result (*)

1. It appears as if multiple cron jobs of the same kind are created. See screenshot.
![capture](https://user-images.githubusercontent.com/19523985/52092065-5045f080-256b-11e9-9b29-e28888701538.PNG)
2. Only a few of the cron jobs get executed sucessfully. The rest get marked pending or missed when timeout occurs.
3. Skipped jobs are not removed, eventually leading to a large table and a database deadlock.

 SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: DELETE FROM `mgit_cron_schedule` WHERE (status = 'pending') AND (job_code in ('currency_rates_update', 'visitor_clean', 'catalog_index_refresh_price', 'catalog_product_flat_indexer_store_cleanup', 'catalog_product_outdated_price_values_cleanup', 'catalog_product_frontend_actions_flush', 'catalog_product_attribute_value_synchronize', 'backend_clean_cache', 'system_backup', 'sales_clean_quotes', 'sales_clean_orders', 'aggregate_sales_report_order_data', 'aggregate_sales_report_invoiced_data', 'aggregate_sales_report_refunded_data', 'aggregate_sales_report_bestsellers_data', 'sales_grid_order_async_insert', 'sales_grid_order_invoice_async_insert', 'sales_grid_order_shipment_async_insert', 'sales_grid_order_creditmemo_async_insert', 'sales_send_order_emails', 'sales_send_order_invoice_emails', 'sales_send_order_shipment_emails', 'sales_send_order_creditmemo_emails', 'security_clean_admin_expired_sessions', 'security_clean_password_reset_request_event_records', 'paypal_fetch_settlement_reports', 'outdated_authentication_failures_cleanup', 'expired_tokens_cleanup', 'newsletter_send_all', 'analytics_subscribe', 'analytics_update', 'analytics_collect_data', 'catalogrule_apply_all', 'magento_newrelicreporting_cron', 'catalog_product_alert', 'aggregate_sales_report_coupons_data', 'persistent_clear_expired', 'captcha_delete_old_attempts', 'captcha_delete_expired_images', 'get_amazon_capture_updates', 'get_amazon_authorization_updates', 'amazon_payments_process_queued_refunds', 'aggregate_sales_report_shipment_data', 'sitemap_generate', 'aggregate_sales_report_tax_data', 'temando_process_platform_events')) AND (created_at < '2019-01-23 22:21:02') .

Work Around: Every few days truncate database table and run cron:run CLI Command.

**Comment by magento-engcom-team** [comment]
Hi @Ctucker9233. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Ctucker9233 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by Ctucker9233** [comment]
@magento-engcom-team 

I can confirm it on vanilla Magento. I would ask for a Magento instance, but that does not allow me to see the database side.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@Ctucker9233 the issue is already created please check #8933

**Comment by Ctucker9233** [comment]
Thanks @shikhamis11 I'll +1 there.
