### ISSUE TITLE
No result searches for queries with non alphanumeric characters like "1:20"

### ISSUE THREAD

**Issue by neil-jennings** [magento/magento2#20878]
### Preconditions (*)

1. Magento OpenSource 2.2.6
2. PHP 7.1
3. MySQL 5.7.18 

### Steps to reproduce (*)

1. Added product with name "Test (1:20)"
2. Searching for scale values using the search box i.e  "1:20"

### Expected result (*)

1. "Test (1:20)" to show up

### Actual result (*)

1. No results found

Same result with other non alphanumeric characters used in place of the colon well.

**Comment by magento-engcom-team** [comment]
Hi @neil-jennings. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@neil-jennings do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by neil-jennings** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @neil-jennings. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @neil-jennings, here is your [Magento instance](https://i-20878-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20878-2-2-develop.instances.magento-community.engineering/admin](https://i-20878-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@neil-jennings https://github.com/magento/magento2/pull/20876

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
@ravi-chandra3197 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by ghost** [comment]
@ravi-chandra3197 i'm verifyng this issue, do not touch labes

**Comment by ravi-chandra3197** [comment]
Hello @engcom-backlog-nazar 
I have reproduced the issue on 2.2

**Comment by ghost** [comment]
@neil-jennings thanks, but i have another result so please wait.

**Comment by ravi-chandra3197** [comment]
Hello @engcom-backlog-nazar
I have reproduced the issue on 2.2-develop instance

search results for test

![search results for test](https://user-images.githubusercontent.com/43946827/52124811-798c7c80-2650-11e9-8126-2dd906acf726.png)

search results for 1 20

![search results for 1 20](https://user-images.githubusercontent.com/43946827/52124810-798c7c80-2650-11e9-9ecc-48dff31537a5.png)

**Comment by ravi-chandra3197** [comment]
Hello @engcom-backlog-nazar 
I created a patch for this issue once you are done. 
add a labels so I can create PR.

**Comment by ghost** [comment]
@ravi-chandra3197 can you share ? feel free to create a Pull Request

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ravi-chandra3197
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98026`, `MAGETWO-98027` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@neil-jennings seems like this is non issue,

> After changing any of these options, rebuild your FULLTEXT indexes for the change to take effect. For example, to make two-character words searchable, you could put the following lines in an option file:
```
[mysqld]
innodb_ft_min_token_size=2
ft_min_word_len=2
```
https://dev.mysql.com/doc/refman/8.0/en/fulltext-fine-tuning.html

**Comment by ghost** [comment]
@neil-jennings  also In "vendor/magento/module-catalog-search/etc/search_request.xml" change
```
<query xsi:type="boolQuery" name="quick_search_container" boost="1">
    <queryReference clause="should" ref="search" />
    <queryReference clause="must" ref="category"/>
    <queryReference clause="must" ref="price"/>
    <queryReference clause="must" ref="visibility"/>
</query>
``` 
to 
```
<query xsi:type="boolQuery" name="quick_search_container" boost="1">
    <queryReference clause="must" ref="search" />
    <queryReference clause="must" ref="category"/>
    <queryReference clause="must" ref="price"/>
    <queryReference clause="must" ref="visibility"/>
</query>
```
