### ISSUE TITLE
 Preconditions (

### ISSUE THREAD

**Issue by mattsulony** [magento/magento2#20883]
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by magento-engcom-team** [comment]
Hi @mattsulony. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mattsulony do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
