### ISSUE TITLE
Minicart, search & logo not vertically aligned between 640 to767 device pixel.

### ISSUE THREAD

**Issue by surabhisrivastava09** [magento/magento2#20905]
### Preconditions (*)
1. Magento2.3
2. PHP7.2

### Steps to reproduce (*)
1.Go to frontend -> resize screen (min width 640 and max width 767).

### Expected result (*)
1. http://i.imgur.com/xyixJIU.png
 
### Actual result (*)
1. http://i.imgur.com/6Xz5Ujb.png

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Surabhi-Cedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by cedmudit** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedmudit. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedmudit, here is your [Magento instance](https://i-20905-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20905-2-3-develop.instances.magento-community.engineering/admin](https://i-20905-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cedmudit** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedmudit. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedmudit, here is your [Magento instance](https://i-20905-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20905-2-2-develop.instances.magento-community.engineering/admin](https://i-20905-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98164`, `MAGETWO-98165` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#21638 by @amol2jcommerce in 2.3-develop branch
Related commit(s):
 - [a21901aac61365d1ceb8f58b77246abe3a6a8cd3](https://github.com/magento/magento2/commit/a21901aac61365d1ceb8f58b77246abe3a6a8cd3)

The fix will be available with the upcoming 2.3.2 release.
