### ISSUE TITLE
Alignment Issue While Editing Order Data containing Downlodable Products in Admin Section

### ISSUE THREAD

**Issue by pankaj-cedcoss** [magento/magento2#20917]
Alignment Issue While Editing Order Data containing Downlodable Products in Admin Section

### Preconditions (*)
1. Magento 2.2
2. php 7.2

### Steps to reproduce (*)
>> login into admin panel 
>> go to Order grid section from Sales > Orders
>> Edit any order containing downladable product with "Links can be purchased separately" enabled.
>> a modal will appear like http://i.imgur.com/MJePtn5.png
>> now click on configure button, another modal will display and issue will appear

### Expected result (*)
![expected_result](https://user-images.githubusercontent.com/13777300/52174743-410ab100-27be-11e9-8615-f7582a5879ce.png)

### Actual result (*)
![actual_result](https://user-images.githubusercontent.com/13777300/52174746-4a941900-27be-11e9-9e69-19d2cdf87662.png)

**Comment by magento-engcom-team** [comment]
Hi @pankaj-cedcoss. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pankaj-cedcoss do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by cedmudit** [comment]
@magento-engcom-team  give me 2.3-develop instance

**Comment by cedmudit** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedmudit. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by pankaj-cedcoss** [comment]
#MM19IN

**Comment by magento-engcom-team** [comment]
Hi @cedmudit, here is your [Magento instance](https://i-20917-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20917-2-3-develop.instances.magento-community.engineering/admin](https://i-20917-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cedmudit** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedmudit. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedmudit, here is your [Magento instance](https://i-20917-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20917-2-2-develop.instances.magento-community.engineering/admin](https://i-20917-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98039`, `MAGETWO-98040` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @pankaj-cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#22298 by @ansari-krish in 2.3-develop branch
Related commit(s):
 - [9e24d22ac0c6ff6afedefadc9401da6907980d48](https://github.com/magento/magento2/commit/9e24d22ac0c6ff6afedefadc9401da6907980d48)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @pankaj-cedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#22582 by @webkul-deepakkumar in 2.2-develop branch
Related commit(s):
 - [223b71017578ddf9a27989c96f11c60dd74447fb](https://github.com/magento/magento2/commit/223b71017578ddf9a27989c96f11c60dd74447fb)

The fix will be available with the upcoming 2.2.9 release.
