### ISSUE TITLE
Email label and email field not aligned from left for reorder of guest user

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#20919]
Email label and email field not aligned from left for reorder of guest user

### Preconditions (*)
1. Magento 2.3 
2. php 7.2

### Steps to reproduce (*)

1. Open frontend and order an product as guest customer
2. open  admin panel, open order grid from sales > order
3. edit same order whatever you purchase
4. click on reorder button
5. page will open and will get issue ref screenshot

### Expected result (*)

![new order orders operations sales magento admin 3](https://user-images.githubusercontent.com/26018716/52174783-0e14ed00-27bf-11e9-974a-14e761ea4851.png)

### Actual result (*)

![new order orders operations sales magento admin 2](https://user-images.githubusercontent.com/26018716/52174786-1836eb80-27bf-11e9-9075-44082d5959b4.png)

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@cedarvinda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by cedmudit** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cedmudit. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedmudit, here is your [Magento instance](https://i-20919-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20919-2-3-develop.instances.magento-community.engineering/admin](https://i-20919-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cedarvinda** [comment]
@cedmudit Please check 
![udcdvbc png png image 1340 x 689 pixels scaled 87](https://user-images.githubusercontent.com/26018716/52175032-79f95480-27c3-11e9-9e75-aa26385088b8.png)

**Comment by cedmudit** [comment]
Yes got it now..

**Comment by magento-engcom-team** [comment]
Hi @cedmudit. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98049` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-20919-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20919-2-3-develop.instances.magento-community.engineering/admin](https://i-20919-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta, here is your [Magento instance](https://i-20919-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20919-2-3-develop.instances.magento-community.engineering/admin](https://i-20919-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#21009 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [20dc45a8a27f64914626dd25baa1773005ef85a5](https://github.com/magento/magento2/commit/20dc45a8a27f64914626dd25baa1773005ef85a5)
 - [32accc927c867cbf42e218063f4d449ee9346f27](https://github.com/magento/magento2/commit/32accc927c867cbf42e218063f4d449ee9346f27)

The fix will be available with the upcoming 2.3.2 release.

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-20919-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20919-2-2-develop.instances.magento-community.engineering/admin](https://i-20919-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#21241 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [512430af08837ba1ef8d8d4a598a98db90b47636](https://github.com/magento/magento2/commit/512430af08837ba1ef8d8d4a598a98db90b47636)
 - [c1057381bcde28433edfafe62d339405facd7139](https://github.com/magento/magento2/commit/c1057381bcde28433edfafe62d339405facd7139)
 - [0c5f4a16d48e0e510db3cdd111e7b426bf43c510](https://github.com/magento/magento2/commit/0c5f4a16d48e0e510db3cdd111e7b426bf43c510)
 - [c753b2a081ccba854124002069ec65c198883ba3](https://github.com/magento/magento2/commit/c753b2a081ccba854124002069ec65c198883ba3)

The fix will be available with the upcoming 2.2.9 release.
