### ISSUE TITLE
Reviews ACL issue - showing Reviews menu two times under System > User Roles > Add New Role > Role Resources

### ISSUE THREAD

**Issue by dankhrapiyush** [magento/magento2#20924]
### Preconditions (*)

1. Magento 2.1.x 2.2.x 2.3x

### Steps to reproduce (*)

1. Go to: System > User Roles > Add New Role > Role Resources
2. [Screenshot](https://www.dropbox.com/s/dm8f39j8dg91typ/review_acl.jpg)

### Expected result (*)

1. It should be a correct label for Pending Reviews under System > User Roles > Add New Role > Role Resources
2. Add a menu for Pending Reviews under Marketing > User Content

### Actual result (*)

1. Showing Reviews menu two times under System > User Roles > Add New Role > Role Resources
2. [Screenshot](https://www.dropbox.com/s/dm8f39j8dg91typ/review_acl.jpg)

**Comment by magento-engcom-team** [comment]
Hi @dankhrapiyush. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dankhrapiyush do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by dankhrapiyush** [comment]
I am working on this #mm19in

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98061`, `MAGETWO-98062` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rav-redchamps. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by rav-redchamps** [comment]
@dankhrapiyush I have created a pull request https://github.com/magento/magento2/pull/21042 for the change. It should be processed soon.

**Comment by magento-engcom-team** [comment]
Hi @dankhrapiyush. Thank you for your report. 
The issue has been fixed in magento/magento2#20936 by @dankhrapiyush in 2.3-develop branch
Related commit(s):
 - [01d68c6849149d499fe1412e1f40b236d6791b44](https://github.com/magento/magento2/commit/01d68c6849149d499fe1412e1f40b236d6791b44)
 - [0b5e0e29d22a39c3c368ffe5491ce5f99d3890a5](https://github.com/magento/magento2/commit/0b5e0e29d22a39c3c368ffe5491ce5f99d3890a5)
 - [a4d81ca190efdcc59a50a13e4a7901026db3623b](https://github.com/magento/magento2/commit/a4d81ca190efdcc59a50a13e4a7901026db3623b)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @dankhrapiyush. Thank you for your report. 
The issue has been fixed in magento/magento2#21849 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [dd3a94a7a0bd2ec81c6a58538efa0ff0882b7367](https://github.com/magento/magento2/commit/dd3a94a7a0bd2ec81c6a58538efa0ff0882b7367)
 - [5c8dba8ecab605be8fdbc7c44b9b399704196b61](https://github.com/magento/magento2/commit/5c8dba8ecab605be8fdbc7c44b9b399704196b61)
 - [95c1bc86ca8e5de7e5607d1b83d0fa46e9ded636](https://github.com/magento/magento2/commit/95c1bc86ca8e5de7e5607d1b83d0fa46e9ded636)

The fix will be available with the upcoming 2.2.9 release.
