### ISSUE TITLE
Disable configurable option drop down till the time option values are not loaded

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#20934]
### Preconditions (*)

1. Magento 2.3.0
2. Configurable product with the only dropdown options

### Steps to reproduce (*)

1. Open a configurable product having DropDown options
2. When the page is being loaded, you will notice that the dropdowns has no values
3. Click Add To Cart button during this time. The page will be reloaded and a notice message "You need to choose options for your item" will be shown 

### Expected result (*)

When values of dropdown options are being loaded, the Add to Cart button should be disabled and DropDown should somehow show that values are being loaded.

### Actual result (*)

The add to cart button is clickable and dropdown options have no values

**Comment by magento-engcom-team** [comment]
Hi @rav-redchamps. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rav-redchamps do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by rav-redchamps** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rav-redchamps. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rav-redchamps, here is your [Magento instance](https://i-20934-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20934-2-3-develop.instances.magento-community.engineering/admin](https://i-20934-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
#MM19IN

**Comment by shikhamis11** [comment]
@rav-redchamps are you trying to add product into cart before page is loaded completely? 
since the option data is dynamic. The options becomes available after few secs

**Comment by rav-redchamps** [comment]
Hi @shikhamis11 

Yes, I know the option values are updated dynamically after few seconds.

But if someone clicks add to cart in the meantime then the page get refreshed with notice. This is a usability problem.

I think it will be better if we disable the add to cart button till the time option values are loaded and show somehow to user that values are being loaded.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98041`, `MAGETWO-98042` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by abbasalis** [comment]
@magento-engcom-team , i am working on this issue at #dmcdindia1

**Comment by magento-engcom-team** [comment]
@abbasalis thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by abbasalis** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @abbasalis. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @abbasalis, here is your [Magento instance](https://i-20934-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20934-2-3-develop.instances.magento-community.engineering/admin](https://i-20934-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by abbasalis** [comment]
@magento-engcom-team I can't reproduce this issue in Magento 2.3-develop instance.

**Comment by rav-redchamps** [comment]
@abbasalis This issue has been fixed in pull request https://github.com/magento/magento2/pull/21007 that's why it's not repeatable on Magento 2.3-develop instance.

Seems like this issue can be closed.
