### ISSUE TITLE
Gift Message for the Entire Order form fields are misaligned

### ISSUE THREAD

**Issue by yashwant2jcommerce** [magento/magento2#20957]
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. In Admin Sales >> Orders >> view any order >> Information >> Gift options
2. To show Gift options in orders enable Gift option from
Stores >> Configuration >> Sales >> Sales >> Gift Options >> Allow Gift Messages on Order Level >> Yes

### Expected result (*)

1. 
![gift-message-expected](https://user-images.githubusercontent.com/26630846/52193792-de292080-2876-11e9-814e-dd0dc8333ee6.jpg)

### Actual result (*)

1. 
![gift-message-actual](https://user-images.githubusercontent.com/26630846/52193799-e5e8c500-2876-11e9-983c-714b79f046d8.jpg)

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@yashwant2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nainesh2jcommerce** [comment]
@magento-engcom-team please give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dipti2jcommerce
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by VitaliyBoyko** [comment]
Hi.
It looks nicer as it is now. I believe there is no any issue.
Moreover, this requires alignment improvements of admin CSS classes that may influence other forms.
Thank you!

**Comment by junkkiller** [comment]
@VitaliyBoyko 

I see a lot of misalignment issues these days, no real issues. 
why don't these guys directly create a PR ?

**Comment by VitaliyBoyko** [comment]
@junkkiller 
Actually, they have done a lot of PR's to fix misalignment. Each PR dedicated to 1 form or page, something like that:
```
.giftmessage-whole-order-container{
    .admin__fieldset {
        > .admin__field {
            > .admin__field-label, > .admin__field-control{
                margin-left: 0;
            }
        }
    }
}
``` 

But I believe it brings mess. Styles for the form elements are common across the whole admin. And it is weird to fix them just in some points, isn't it?

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

_Next steps are available in case you are a member of **Quality Maintainers** or **Open Source Maintainers**_

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @yashwant2jcommerce thank you for you report, i'm closing this as this is non-issue. thanks for collaboration.
