### ISSUE TITLE
Removing a theme does not remove it from theme database table

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#20961]
### Preconditions (*)

1. Magento 2.2.x CE & EE - latest
2. Magento 2.3 CE

### Steps to reproduce (*)

1. Create a new theme
2. Create a second theme that extends first theme
3. Visit admin panel and make sure themes are visible
4. Change name of the second theme to something else and visit admin again.
5. Remove all themes from app/design folder
6. In Content -> Design -> Configuration those themes are still there, even after cache is cleared and developer mode enabled (3 entries)

### Expected result (*)

1. Removed themes should be removed from theme table, it is easy to create a mess if they are not removed. For example, changing theme name (folder) is causing extra entries in that table, picking wrong one will break frontend entirely.
2. Magento should SET default theme if a selected theme does not exists

### Actual result (*)

1. Removed themes are stores in theme table and it is possible to pick them even though the folder and files no longer exists.
2. Picking theme which is no longer present in the code base will crash the site.

**Comment by magento-engcom-team** [comment]
Hi @qsolutions-pl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@qsolutions-pl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Dharmeshvaja91
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Dharmeshvaja91
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Dharmeshvaja91
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by ghost** [comment]
@Dharmeshvaja91 please don't touch label if someone has already assigned, and verifying this  issue.

**Comment by ghost** [comment]
Hi @qsolutions-pl did you try unistall by `php bin/magento theme:uninstall frontend/Custom/CustomTheme` ?

**Comment by ghost** [comment]
@qsolutions-pl 
![selection_312](https://user-images.githubusercontent.com/40756439/52208341-e8ecb100-2888-11e9-8a69-5311280a7ec2.png)
