### ISSUE TITLE
Query slow when using quotes for integers in WHERE statements

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#20975]
### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Any query that selects values from an integer value. Load a product in the backend and check the query log.
2. The lookup of the query is allot longer when for example 'attribute_id' has a where as `attribute_id = '73'` than a where as `attribute_id = 73`
3. problem is more evident when checking queries which have multiple joins

### Expected result (*)

1. Queries should use a better lookup

### Actual result (*)

1. Queries us a bad lookup up because where statements are evaluated as strings instead of integers.

Inspired by @Flyingmana who mentioned this in https://github.com/OpenMage/magento-lts/pull/383

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@PascalBrouwers do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by PascalBrouwers** [comment]
Related: https://github.com/magento/magento2/issues/20969

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @PascalBrouwers thank you for you report, nice find!  but seems like this is very identical issue maybe close this one ? https://github.com/magento/magento2/issues/20969 this issue has more clear description

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98085`, `MAGETWO-98086` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by PascalBrouwers** [comment]
Yes, that issue looks related. I only fixed it for this class. It's a bit harder to fix it for addFieldToFilter where an array of values will be used, etc.

**Comment by PascalBrouwers** [comment]
I was thinking, maybe we can cache the 'describe' of all magento tables and use that? But I don't know what kind of impact that has on performance.

**Comment by PascalBrouwers** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24324` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
