### ISSUE TITLE
TinyMCE 4 doesn't allow the parcing of all characters

### ISSUE THREAD

**Issue by Vallance21** [magento/magento2#20977]
![screenshot_2019-02-04 1](https://user-images.githubusercontent.com/1458928/52237267-02115400-28c1-11e9-9aab-2788a9cadf53.png)
![screenshot_2019-02-04 2](https://user-images.githubusercontent.com/1458928/52237269-02115400-28c1-11e9-9147-fb5033627fa5.png)

Magento 2  version 2.3.0 - TinyMCE 4

TinyMCE 4 fails to out put all data stored in the database table.

CMS Block (may not be limited to just this table!)

After reverting to TinyMCE 3 deprecated fixed issue and outputs all content stored with in the block/table.

I can only assume there is a misconfiguration with the module settings and the number of characters allowed to be displayed.  

Total number of characters stored 6730. fails to parse after 5829 when using TinyMCE 4. Parses fine in TinyMCE 3 (Deprecated)

**Comment by magento-engcom-team** [comment]
Hi @Vallance21. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Vallance21 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Vallance21 can you please provide more steps to reproduce ? because in current description i don't understand where the issue is coming. thank you

**Comment by ghost** [comment]
Please provide following information

- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Then please reopen the issue.
