### ISSUE TITLE
PathValidator won't allow any paths outside BP, even if specified in Bootstrap

### ISSUE THREAD

**Issue by tschirmer** [magento/magento2#20979]
### Preconditions (*)

1. Magento 2.3
2. PHP 7.1

### Steps to reproduce (*)

1. Setup bootstrap to include paths outside of Magento's root

```
//for this example, we'll assume autoscaling architecture, which we want to include restricted directories in the image, and automount the writeable directories.
//just anything outside of root.
$automountingWriteableDir = '/home/sites/stagingbuild-309/httpdocs';
$staticRestrictedDir = '/usr/share/magento-core/latest';
$tmpDir = '/var/www/html/tmpfs';


$params = $_SERVER;
$filesystemsDirs = $params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS];
$filesystemsDirs[DirectoryList::ROOT]      = [DirectoryList::PATH => $staticRestrictedDir . "/var/cache"];
$filesystemsDirs[DirectoryList::CONFIG]    = [DirectoryList::PATH => $automountingWriteableDir. "/app/etc"];
$filesystemsDirs[DirectoryList::MEDIA]     = [DirectoryList::PATH => $automountingWriteableDir . "/pub/media"];
$filesystemsDirs[DirectoryList::GENERATED] = [DirectoryList::PATH => $tmpDir . "/generated"];
$filesystemsDirs[DirectoryList::CACHE]     = [DirectoryList::PATH => $tmpDir . "/var/cache"];

$params[Bootstrap::INIT_PARAM_FILESYSTEM_DIR_PATHS] = $filesystemsDirs;

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);

```
2. Run Magento command: bin/magento maintenance:enable

### Expected result (*)

1. CLI should return with: Maintenance Mode Enabled

### Actual result (*)

1. CLI returns with: Path "/home/sites/stagingbuild-309/httpdocs/app/etc/env.php" cannot be used with directory "/usr/share/magento-core/latest/"

**Comment by magento-engcom-team** [comment]
Hi @tschirmer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tschirmer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @tschirmer thank you for you report, this is expected behavior, paths outside of Magento base path should not be accessible for security reasons.
