### ISSUE TITLE
Excessive loading of zend locale information from Cache

### ISSUE THREAD

**Issue by tim-reynolds-visionet** [magento/magento2#20973]
While investigating performance issues we became aware that our server was making hundreds of requests to our cache backend (Redis) for static locale information that would not change. 

An example cache key is: 35e_Zend_LocaleC_en_BE_currencynumber_

Essentially anything with Zend_Locale should never change for the given key within a single run, yet to us it seems it is hitting the cache every time the data is needed. 

Example: 
magento/zendframework1/library/Zend/Currency.php method _checkParams calls
Zend_Locale_Data::getContent which, if caching is on (how do we disable?) loads the currency to region value from the cache. It does not save it in any type of local cache though. And it seems to get this info every time we call formatCurrency. Even if we turned the cache off, it would be re-loading this from disk every single call. This seems very inefficient. 

On some of our larger pages we found it was loading from a few specific keys hundreds of times. 

### Steps to reproduce (*)
1. Add the following code to the 'load' method of your chosen cache backend at the beginning of the method:
if(!isset($_SERVER['cache_counter'][$id])){$_SERVER['cache_counter'][$id] = 0;}
$_SERVER['cache_counter'][$id]++;
asort($_SERVER['cache_counter']);
2. Add a breakpoint at the end of the execution of index.php, and inspect the $_SERVER['cache_counter'] variable to see how many times each ID was requested from cache. You should see that Zend_Locale dominates with repeated calls. 

### Expected result (*)
1. Static information that will never change in the course of a page load should not be requested more than once. 

### Actual result (*)
1. Static information that should not be requested more than once is requested many many times.

**Comment by magento-engcom-team** [comment]
Hi @tim-reynolds-visionet. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tim-reynolds-visionet do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment]
@tim-reynolds-visionet expected result is quite doubtful to me. How much time such loading from cache actually takes?

**Comment by ghost** [comment]
HI @tim-reynolds-visionet thank you for you report, i;m not able to reproduce following steps you described, please provide more information, about you magento version and clearly actual and expected results. Then please reopen the issue. 
Best Regards

**Comment by frankatwork** [comment]
Hi. I am experiencing the same, did you find a fix?

**Comment by tim-reynolds-visionet** [comment]
@frankatwork yes here is essentially the code I used. You have to change the class used for cache in the app/etc/env.php file but with this the problem went from a couple thousand cache hits to load a page to less than 100 for me. 

    <?php
    
    
    class Example_Cache_Redis extends Cm_Cache_Backend_Redis
    {
    
        static $_special_cache = [];
        static $_special_patterns = ['/Zend_Locale/'];
        public function load($id, $doNotTestCacheValidity = false)
        {
            if(isset(self::$_special_cache[$id]))
            {
                return self::$_special_cache[$id];
            }
            $result = parent::load($id, $doNotTestCacheValidity);
            if($result !== false)
            {
                foreach (self::$_special_patterns as $pattern)
                {
                    if (preg_match($pattern, $id))
                    {
                        self::$_special_cache[$id] = $result;
                    }
                }
             }
            return $result;
        }

    }

**Comment by orlangur** [comment]
@tim-reynolds-visionet,

> went from a couple thousand cache hits to load a page to less than 100 for me

How much is that in terms of absolute time?

**Comment by ilnytskyi** [comment]
Time does not matter if merchant pays for amount of data transfered between redis and app.
e.g. 1 call = 10kb
100 calls = 1000kb

literally means merchant pays 10 times more

**Comment by Dren7755** [comment]
Looks like we have the same problem on our production server.
From time to time we can see following situation in newrelic 
![image](https://user-images.githubusercontent.com/19759530/107757590-6f68e280-6d2e-11eb-9578-c07e8930e461.png)

**Comment by braders** [comment]
I'm seeing New Relic reporting requests spending 40% time in Zend_Locale_Data::_getFile, similar to @Dren7755 above. Does anyone know if this is the same issue as is fixed in the PR above, and has anyone had success with that PR? Thanks.

**Comment by sramesh1988** [comment]
We are getting the same issue in Magento version 2.4.3-P1. **Dren7755** / **braders** Have you find the solution for this issue. If, yes can you please share.
