### ISSUE TITLE
Very bad Google Page Speed Score 

### ISSUE THREAD

**Issue by magefan** [magento/magento2#20974]
### Preconditions (*)
Magento 2.3.0
Enabled css minification and merge
Enabled js minification, merge, bundling
Enabled HTML minification
Production mod is on
Gzip is enabled on webserver
Expire headers is configured on webserver

### Steps to reproduce (*)
Setup valina Magento 2.3. with the preconditions settings.
Go to the google page speed test page
https://developers.google.com/speed/pagespeed/insights
make a test. 

### Expected result (*)
Expect good result as you made all required performance inmrovements

### Actual result (*)
Bad score, espacisaly for mobile.

Actualy I thin that is due to new "features" google added into the test, e.g. : 
 - Defer unused CSS

**Comment by magento-engcom-team** [comment]
Hi @magefan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magefan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sjamesc** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @scottjcampbell. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @scottjcampbell, here is your [Magento instance](https://i-20974-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20974-2-3-develop.instances.magento-community.engineering/admin](https://i-20974-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
@magefan,

> Enabled css minification and merge
> Enabled js minification, merge, bundling

I doubt this is a recommended setting. PageSpeed rank was quite well-optimized at some point and was enforced by an internal test.

**Comment by magefan** [comment]
@orlangur, can you provide suggested settings for better performance?
Note, that with these settings Google Page Speed provided better result earlier. Now if you try to test vanilla  M2 it is drama
https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fi-20974-2-3-develop.instances.magento-community.engineering%2F&tab=desktop
See saved results
https://magefan.com/media/tests/mobile-results.html (mobile score = 29)
https://magefan.com/media/tests/desktop-results.html (desktop score = 71)

And it's vanilla M2 without ever product images.
Please pay attantion to this new Google Speed rule https://prnt.sc/mgll1z "Defer unused CSS".

> Remove unused rules from stylesheets to reduce unnecessary bytes consumed by network activity. Learn more.
https://developers.google.com/web/tools/lighthouse/audits/unused-css

I think it's due to Magento style-l, style-m css files that is created from less, and contain css for different Magento pages, not only those one is visiting.

**Comment by DanielRuf** [comment]
> I think it's due to Magento style-l, style-m css files that is created from less, and contain css for different Magento pages, not only those one is visiting.

Which is quite normal for a single CSS file.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-20974-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20974-2-3-develop.instances.magento-community.engineering/admin](https://i-20974-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
@magefan, https://devdocs.magento.com/guides/v2.3/performance-best-practices/configuration.html

**Comment by magefan** [comment]
@DanielRuf , yes it is normal for a single CSS file, but Google page speed says that a single CSS file which contains CSS for elements that are not included on the current page is bad practice
"Remove unused rules from stylesheets to reduce unnecessary bytes consumed by network activity. " 
https://developers.google.com/web/tools/lighthouse/audits/unused-css

We know that a single CSS file it is how Magento 2 works, but a lot of merchants wants to see their websites green, with a high rate on Google Page Speed.

**Comment by DanielRuf** [comment]
It is a best practice but not practical ;-)

Did you already try Brotli compression?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magefan Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by PiroozMB** [comment]
Could you view this because Google is reranking websites based on their speed and magento2 mobile scores really bad. it's barely getting a score above 20.
