### ISSUE TITLE
Admin Customizable Options Dropdown sort_order issue

### ISSUE THREAD

**Issue by dharmendra-wagento** [magento/magento2#20989]
### Preconditions (*)

1. Magento ver. dev-2.3-develop / Magento ver. 2.2-dev

### Steps to reproduce (*)

1. Go to Catalog > Products
2. Edit/New Product
3. Expand Customizable Options and click on Add Option
4. Choose Drop Dowm as New Option Type
5. Add 1 or 2 Values 
6 . Now , Change Option type from drop down to field or area
7. Now again choose Drop Dowm as Option Type
8. Add 1 or 2 Values 

### Expected result (*)

1. Sort Order should not be display when we choose dropdown again from option type
![3](https://user-images.githubusercontent.com/20059461/52264810-8367f580-2958-11e9-81fb-a38297b2c563.png)

### Actual result (*)

1. Sort Order is displaying when we choose dropdown again from option type

2. Sort Order is displaying which should not display while selecting drop down option type
![1](https://user-images.githubusercontent.com/20059461/52264692-44d23b00-2958-11e9-924d-9c9b781036c8.png)
3. Below result after reproducing the above steps and added new drop down value
![2](https://user-images.githubusercontent.com/20059461/52264693-44d23b00-2958-11e9-8f32-4f235f3d38ed.png)

**Comment by magento-engcom-team** [comment]
Hi @dharmendra-wagento. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dharmendra-wagento do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-20989-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20989-2-3-develop.instances.magento-community.engineering/admin](https://i-20989-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98083`, `MAGETWO-98084` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sskulkarni. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @dharmendra-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#20990 by @dharmendra-wagento in 2.3-develop branch
Related commit(s):
 - [734c44080dce9e13252da70224961187ec65cb2f](https://github.com/magento/magento2/commit/734c44080dce9e13252da70224961187ec65cb2f)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @dharmendra-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#21159 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [9612b4221fac3d1cbac3ca1dac338e92fb92dc3c](https://github.com/magento/magento2/commit/9612b4221fac3d1cbac3ca1dac338e92fb92dc3c)

The fix will be available with the upcoming 2.2.9 release.

**Comment by magento-engcom-team** [comment]
Hi @dharmendra-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#21371 by @omiroshnichenko in 2.3-develop branch
Related commit(s):
 - [4e348fd0a595579a4be08795c18f13c71ebecea0](https://github.com/magento/magento2/commit/4e348fd0a595579a4be08795c18f13c71ebecea0)
 - [e270deef1b38a89989cb6677d128bc47233a9beb](https://github.com/magento/magento2/commit/e270deef1b38a89989cb6677d128bc47233a9beb)
 - [795d5329c18dd7a732fc71261ee5b74398882b1f](https://github.com/magento/magento2/commit/795d5329c18dd7a732fc71261ee5b74398882b1f)

The fix will be available with the upcoming 2.3.2 release.
