### ISSUE TITLE
Magento 2 : how to add extension attribute to filter?

### ISSUE THREAD

**Issue by dharmesh143** [magento/magento2#20981]
### Summary 
I am facing issue with Magento 2.2.0 EE.  I am trying to add extension attribute on searchCriteriaBuilder filter. But  that extension attribute, not adding to filter in collection. it is showing error of `Invalid attribute name`

### Examples 

here is my method

```
public function getProductList($filterValue)
    {
        // Filter products
        $this->searchCriteriaBuilder
            ->addFilter('brand', 15)
            ->addFilter("extension_attribute_parent_product_id.parent_product_id", null, "null");


        // Get the first 5 products
        $this->searchCriteriaBuilder
            ->setPageSize(5)
            ->setCurrentPage(1);

        $searchCriteria = $this->searchCriteriaBuilder->create();

        // get products list
        $products = $this->productRepository
            ->getList($searchCriteria);

        foreach ($products->getItems() as $product){
            echo $product->getName();
        }

        exit;
    }
```

here is my extension_attributes.xml

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Api/etc/extension_attributes.xsd">
    <extension_attributes for="Magento\Catalog\Api\Data\ProductInterface">
        <attribute code="parent_product_id" type="int">
            <join reference_table="catalog_product_bundle_selection" reference_field="product_id" join_on_field="entity_id">
                <field>parent_product_id</field>
            </join>
        </attribute>
    </extension_attributes>
</config>
```

Any solutions for this?

**Comment by magento-engcom-team** [comment]
Hi @dharmesh143. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dharmesh143 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @dharmesh143 l  GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
