### ISSUE TITLE
Magento 2.2.7: Image deletion via Rest API not working as expected

### ISSUE THREAD

**Issue by jhruehl** [magento/magento2#20996]
### Preconditions (*)
1. Magento 2.7 CE
2. At least two Store Views in same Website
2. PHP 7.1

### Steps to reproduce (*)
1. Open a product in backend
2. Switch to other store view than default
3. Upload image in this store view
4. Delete image for all store views via Rest-API Call to rest/all/V1/products/<SKU>/media/<ENTRY_ID>

### Expected result (*)
1. Frontend before deletion via rest call: Image is only shown in store view for which it was uploaded.
2. Rest API: After DELETE-requests returns true, media-GET request should return no data for deleted image and image is deleted for all store views
3. Frontend after deletion via rest call: Image not shown in product detail page

### Actual result (*)
1. Frontend before deletion: Image is still shown in product view in all store views
2. Rest API: Image not deleted, GET calls for each store view return image data
3. Frontend after deletion: Image shown in all store views.

### Current workaound
After deleting a product image via REST call for all store views another GET request for the product is done and if unexpected values are returned, DELETE calls are made for each store view. It suffices though to make a DELETE call to the rest api only for the store view the image was uploaded in, but no rest API call makes this information available. The response data of the GET calls for each store view has no significant difference or information, in which store view the image was actually set.

This seems to be only one case, which leads to this behaviour. But uploading an image in a store view other than default makes the deletion via a single DELETE call to rest/*all*/V1/products/<SKU>/media/<ENTRY_ID> impossible.

**Comment by magento-engcom-team** [comment]
Hi @jhruehl. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jhruehl do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @jhruehl thank you for you report, i'm not able to reproduce following steps you described.
![selection_316](https://user-images.githubusercontent.com/40756439/52279763-fbd3b400-2962-11e9-937c-373cfe55e65e.png)
![selection_315](https://user-images.githubusercontent.com/40756439/52279764-fc6c4a80-2962-11e9-9d4d-bb3497a1cc14.png)

**Comment by jhruehl** [comment]
@magento-engcom-team  You did the GET request with the image ID specified. If you do a general GET request without the image id to get all media data for the given product, it still returns the data for the uploaded image (or should be deleted image).

**Comment by jhruehl** [comment]
Furthermore you could look up, if the image is still listed in the backend. And if you upload the image only in the default store view, everything works as expected.

**Comment by ghost** [comment]
@jhruehl 
![selection_317](https://user-images.githubusercontent.com/40756439/52281057-eb710880-2965-11e9-9d8f-8457bb8be1a8.png)

**Comment by ghost** [comment]
@jhruehl I'm trying upload for second default storview but always image was deleted

**Comment by jhruehl** [comment]
No. Not default store view.. In a non default store view, which has a default store view as a "parent". But if you cannot reproduce, it's not such a drama.

**Comment by jhruehl** [comment]
In my case I switched to the store view with ID 2 in the backend and uploaded the image there. Store view 2 has the default store view with ID 0 as parent.

**Comment by ghost** [comment]
@jhruehl same result , can you try in vanilla instance ?

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-20996-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20996-2-3-develop.instances.magento-community.engineering/admin](https://i-20996-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jhruehl** [comment]
Hm. Seems I cannot reproduce it there. Really really strange though. I guess I'm missing something in this setup. Tried a configurable product, but no.

Sorry and thanks for your efforts. If I'm getting to the bottom of the problem some time, I'll let you know.

**Comment by jhruehl** [comment]
Hm. I just see that this was a Magento 2.3 instance. Maybe the bug or whatever this is was resolved in 2.3. Until then we'll probably use the workaround anyway.

**Comment by ghost** [comment]
@jhruehl I also thought that this bug is only 2.2 but there's the same result . If you have some additional info reopen the issue.
