### ISSUE TITLE
Itemwith the same ID “35436” already exists because it is in two categories

### ISSUE THREAD

**Issue by vaso123** [magento/magento2#20999]
### Preconditions
Our customer uses Magento ver. 2.2.6.
Using latest stable mysql, and Ubunut 18.04 LTS

### Steps to reproduce
Add an item to your cart what has Default and a default child category and go to checkout.

### Expected result
Checkout page appears.

### Actual result
You will get an error:
`Itemwith the same ID “[product_id]” already exists`

### Description

This is frequently asked question on the web, I just did not found the solution.

I've checked the

`SELECT * FROM cataloginventory_stock_item
WHERE product_id in (
    SELECT product_id 
    FROM cataloginventory_stock_item
    GROUP BY product_id
    HAVING ( COUNT(product_id) > 1 )
)`

and I have no duplicates in `cataloginventory_stock_item` table.

I started to debug, why is it already exists and found this: in the Framework\Data\Collection\AbstractDb.php line 569 in function loadWithFilter I've just dumped the $data variable. First two dump is about the store, but later I've got this:

`array (size=2)
0 => 
 array (size=56)
  'item_id' => string '35436' (length=5)
  'quote_id' => string '1683' (length=4)
  'created_at' => string '2019-02-05 15:41:14' (length=19)
  'updated_at' => string '0000-00-00 00:00:00' (length=19)
  'product_id' => string '12' (length=2)
  'store_id' => string '1' (length=1)
  'parent_item_id' => null
  'is_virtual' => string '1' (length=1)

  ....

  'category_id' => string '2' (length=1)
  'category_name' => string 'Default Category' (length=16)
1 => 
 array (size=56)
  'item_id' => string '35436' (length=5)
  'quote_id' => string '1683' (length=4)
  'created_at' => string '2019-02-05 15:41:14' (length=19)
  'updated_at' => string '0000-00-00 00:00:00' (length=19)
  'product_id' => string '12' (length=2)
  'store_id' => string '1' (length=1)
  'parent_item_id' => null

   ...

  'category_id' => string '8' (length=1)
  'category_name' => string 'Events' (length=6)`

It seems, magento2 try to add the item to the collection twice becuse it has two categories.

Does somebody faced an issue like this?

**Comment by magento-engcom-team** [comment]
Hi @vaso123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vaso123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by vaso123** [comment]
I've just updated my issue, please review.

**Comment by santosh142** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @santosh142. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @santosh142, here is your [Magento instance](https://i-20999-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20999-2-2-develop.instances.magento-community.engineering/admin](https://i-20999-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @vaso123  thank you for you report, i'm not able to reproduce following steps you described, please provide more information, did have you some custom modules ? your magento version is CE ?
