### ISSUE TITLE
You cannot define a correlation name 'links' more than once

### ISSUE THREAD

**Issue by gerym77** [magento/magento2#20991]
### Summary (*)
When I click on a product in frontend detail view in Magento 2.2.6  I get the error message "You cannot define a correlation name 'links' more than once". All date comes from magenta migration tool. I have a lot of imported attributes. Magento is a clean version with no extensions or any changes in the code. there are no attributes called "links"

###  Information on your environment (*)
Magento 2.2.6
migrated from 1.9.3.10

### Examples (*)
this is link to a detail view which shows the error: http://dev.emeibaby.com/en/catalog/product/view/id/426/s/emeibaby-babycarrier-chichi-red-baby-size/category/82/
this is not happening on all products, for example this one works fine:
http://dev.emeibaby.com/en/catalog/product/view/id/630/s/emeibaby-babycarrier-all-surya-mela-baby-size/category/82/

### Expected and actual results (*)
show product standard detail view, 
actual result: error message on some products, not all

**Comment by magento-engcom-team** [comment]
Hi @gerym77. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gerym77 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gerym77     thank you for your report,  problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by dcwnaveen** [comment]
We are getting the same issue after migrating to 2.3.1.
Please provide me a solution.

**Comment by dcwnaveen** [comment]
This solution is working fine for me.
https://stackoverflow.com/questions/55001060/you-cannot-define-a-correlation-name-links-more-than-once
