### ISSUE TITLE
[Performance] Cart Price Rule - Recreates all product attributes for each order

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#20998]
### Preconditions (*)
1. Magento 2.2.7

### Steps to reproduce (*)
1. Create two products: skus - test-1, test-2
2. Go to Admin >> Marketing >> Cart Price Rules3
3. Create new rule like this:
![capture 2019-02-05 at 16 36 54](https://user-images.githubusercontent.com/1873745/52280448-98e31c80-2964-11e9-8494-8bc3210917a0.png)
![capture 2019-02-05 at 16 38 30](https://user-images.githubusercontent.com/1873745/52280453-9d0f3a00-2964-11e9-81aa-9580ea079a31.png)
![capture 2019-02-05 at 16 37 40](https://user-images.githubusercontent.com/1873745/52280459-a13b5780-2964-11e9-93eb-841a80eb0c69.png)
![capture 2019-02-05 at 16 38 06](https://user-images.githubusercontent.com/1873745/52280463-a39db180-2964-11e9-8a0d-f4d34503d68a.png)
4. Go to frontend and place order using product test-2

### Expected result (*)
1. Values in table `salesrule_product_attribute` should not be deleted and added back during placing an order

### Actual result (*)
1. Values in table `salesrule_product_attribute` were deleted and added back during placing an order

### Tech details
During testing one project with jMeter I found one really strange thing - in performance_schema table we have table `salesrule_product_attribute` with biggest amount of write bytes, than others, even more than orders and quotes tables. That's really strange.

I investigated deeper and found that queries to this table were following:

Select - that's ok.
```sql
SELECT DISTINCT ea.attribute_code
FROM `salesrule_product_attribute` AS `a`
INNER JOIN `eav_attribute` AS `ea` ON ea.attribute_id = a.attribute_id;
```

Delete - that's strange that we have a lot of them:
```sql

DELETE
FROM `salesrule_product_attribute`
WHERE (rule_id = '284');
```

Insert - that's strange that we have a lot of the:
```sql
INSERT INTO `salesrule_product_attribute` (`rule_id`, `website_id`, `customer_group_id`, `attribute_id`)
VALUES ('284', '3', '0', '68'), ('284', '4', '0', '68'),('284', '6', '0', '68'),('284', '3', '1', '68'),('284', '4', '1', '68'),('284', '6', '1', '68'),('284', '3', '3', '68'),('284', '4', '3', '68'),('284', '6', '3', '68'),('284', '3', '4', '68'),('284', '4', '4', '68'),('284', '6', '4', '68'),('284', '3', '7', '68'),('284', '4', '7', '68'),('284', '6', '7', '68'),('284', '3', '8', '68'),('284', '4', '8', '68'),('284', '6', '8', '68'),('284', '3', '9', '68'),('284', '4', '9', '68'),('284', '6', '9', '68'),('284', '3', '10', '68'),('284', '4', '10', '68'),('284', '6', '10', '68'),('284', '3', '11', '68'),('284', '4', '11', '68'),('284', '6', '11', '68'),('284', '3', '12', '68'),('284', '4', '12', '68'),('284', '6', '12', '68'),('284', '3', '13', '68'),('284', '4', '13', '68'),('284', '6', '13', '68'),('284', '3', '14', '68'),('284', '4', '14', '68'),('284', '6', '14', '68');
```

I found following piece of code that triggers those delete & insert queries:
https://github.com/magento/magento2/blob/0a48caf80da4d9ba3be27ae8cab708ac223e433f/app/code/Magento/SalesRule/Model/ResourceModel/Rule.php#L315-L356

I checked where this piece is executing - just inside "after save" method:
https://github.com/magento/magento2/blob/0a48caf80da4d9ba3be27ae8cab708ac223e433f/app/code/Magento/SalesRule/Model/ResourceModel/Rule.php#L178

In general when model saves from the admin - it's ok to re-create some product attributes, but issue there that it actually no real changes in this model, it was just updated "how many times it was used"
https://github.com/magento/magento2/blob/940cc642801f75ef5dc16fb4246b95225ec8f947/app/code/Magento/SalesRule/Model/Coupon/UpdateCouponUsages.php#L101-L102

Those queries not really hard in terms of performance, but when we have high traffic and each order will do that - that will be bottleneck.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ihor-sviziev do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment]
@kandy could you please evaluate this? I remember there was even a deadlock here.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98966`, `MAGETWO-98967` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by orlangur** [comment]
Ping @kandy :)

**Comment by kandy** [comment]
@orlangur this issue certainly make sense

**Comment by orlangur** [comment]
Ok, just in case this is a regression of problem which was already fixed you may be aware of some details.

**Comment by ihor-sviziev** [comment]
Seems like this issue isn't causing big performance issues, so it would be better to focus on more important things. I'm closing this issue as not relevant.
