### ISSUE TITLE
Hardcoded entity code is forcing to load "customer" attributes on create new Scheduled Export

### ISSUE THREAD

**Issue by andkirby** [magento/magento2#20993]
### Summary (*)

Hardcoded entity code is forcing to load "customer" attributes in file `vendor/magento/module-scheduled-import-export/view/adminhtml/templates/scheduled/form/before.phtml:118` on create Scheduled Export.

Magento EE v2.2.5

### Examples (*)

I've created my own export/import entity and when I'm trying to create scheduled export it's always loading "customer" attributes due to following code:
```javascript

        /**
         * Post form data and process response via AJAX
         */
        getFilter: function() {
            if ($('entity') && $F('entity')) {
                var entity = $F('entity');
                if (entity != 'catalog_product') {
                    entity = 'customer';             // <<<< bad code here
                }
// ....
```

### Proposed solution

Remove this workaround with hardcoded entities:
```
                if (entity != 'catalog_product') {
                    entity = 'customer';
                }
```

**Comment by magento-engcom-team** [comment]
Hi @andkirby. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@andkirby do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @andkirby   GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by andkirby** [comment]
@engcom-backlog-nazar , are there certain links to understand what you are talking about?

**Comment by ghost** [comment]
@andkirby module-scheduled-import-export available on EE version,  GitHub is intended for Magento Open Source CE version

**Comment by andkirby** [comment]
@engcom-backlog-nazar , yeah, it's clear. Where exactly this issue should be created in?

**Comment by ghost** [comment]
@andkirby https://support.magento.com  Support portal associated with your account

**Comment by andkirby** [comment]
Got it, thanks.
