### ISSUE TITLE
Magento 2.2.6 customer login cause server error

### ISSUE THREAD

**Issue by mnatali80** [magento/magento2#21000]
### Preconditions (*)
Magento 2.2.6

### Steps to reproduce (*)
1. Register a customer 
2. Login ->ok
3. After some days (but not whith all customer) retry to login and encounter the error

### Expected result (*)

1.Normalli login with email and password

1.After some days and apparently random the customer(that was able to login without problem until some days ago) can't login and after some seconds (about 40 second) receive a 503 message error from server and from log of server i have this line
Failed to read FastCGI header, referer: https://mysite.com/customer/account/login/referer/aHR0cHM6Ly90ZXN0Lm1hc3NldGFuaXNob3AuY29tLw%2C%2C/
[Tue Feb 05 16:48:06.418749 2019] [proxy_fcgi:error] [pid 13550] (104)Connection reset by peer: [client 178.250.70.70:47924] AH01075: Error dispatching request to : , referer: https://mysite.com/customer/account/login/referer/aHR0cHM6Ly90ZXN0Lm1hc3NldGFuaXNob3AuY29tLw%2C%2C/
2. Ohter customer can login without any problems

**Comment by magento-engcom-team** [comment]
Hi @mnatali80. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mnatali80 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@mnatali80,

> .After some days and apparently random the customer

Issue should be reproduced on a vanilla Magento installation and not randomly.

Is there something in PHP or Magento logs maybe? Like fatal error.

**Comment by mnatali80** [comment]
> 
> 
> @mnatali80,
> 
> > .After some days and apparently random the customer
> 
> Issue should be reproduced on a vanilla Magento installation and not randomly.
> 
> Is there something in PHP or Magento logs maybe? Like fatal error.

@orlangur 
thanks for your reply.
My problem is this(sorry for my english)
first day: customer register himself and can login and buy
second day: customer can login and buy
3th day: customer can login and buy
.
.
.
about after 7/8 days (but there isn't a specific day) customer can't login anymore and a ireceive this error
503 POST /customer/account/loginPost/referer/aHR0cHM6Ly9tYXNzZXRhbmlzaG9wLmNvbS9wYXRyaXppYS1wZXBlLXQtc2hpcnQtZmludG8tZ2lsZXQtOG0wNzU0LWExMGYybnMtYy5odG1s/ HTTP/1.0

AH01067: Failed to read FastCGI header, referer: https://mysite.com/customer/account/login/referer/aHR0cHM6Ly9tYXNzZXRhbmlzaG9wLmNvbS9wYXRyaXppYS1wZXBlLXQtc2hpcnQtZmludG8tZ2lsZXQtOG0wNzU0LWExMGYybnMtYy5odG1s/

(104)Connection reset by peer: AH01075: Error dispatching request to : , referer: https://mysite.com/customer/account/login/referer/aHR0cHM6Ly9tYXNzZXRhbmlzaG9wLmNvbS9wYXRyaXppYS1wZXBlLXQtc2hpcnQtZmludG8tZ2lsZXQtOG0wNzU0LWExMGYybnMtYy5odG1s/

I don't know why this happen and why it happen in some customer and in other is all ok..

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by mnatali80** [comment]
Hi,
yesterday i have done other test..i have used a fresh installation of magento 2.2.6 and imported a copy of the db with customers inside. all is working. After that i switch to production mode the problem has happened..

**Comment by ghost** [comment]
Hi @mnatali80 did you use varnish ?

**Comment by mnatali80** [comment]
hi @engcom-backlog-nazar no..i use redis

**Comment by ghost** [comment]
@mnatali80 can you provide more information about your environment ?

**Comment by ghost** [comment]
@mnatali80 i think this is issue with your environment
Add the following lines to the text boxes Additional directives for HTTP and Additional directives for HTTPS: 
/etc/apache2/mods-enabled/fcgid.conf
```
FcgidIdleTimeout 600
FcgidProcessLifeTime 600
FcgidConnectTimeout 600
FcgidIOTimeout 600
```

**Comment by mnatali80** [comment]
sure..is an ubuntu 16:04 on a server with 4G of ram. I have mount a plesk license. Magento is running on a php 7.1.26 fpm...i have already set FcgidIdleTimeout ...the strange is that this issue happen with some customer and with other not..

**Comment by ghost** [comment]
@mnatali80 Check your php.ini file or opcache.ini file and try increasing the caching memory like this (by default should be 64 or 128)
```
[opcache]
opcache.memory_consumption = 512
```
Try setting this in nginx.conf:
```
worker_rlimit_nofile 65535;
keepalive_requests 1024;
keepalive_timeout 10s
```
In /etc/security/limits.conf add at the end of the file:
```
nginx       soft    nofile   10000
nginx       hard    nofile   70000
```
In /etc/sysctl.conf (save the file & run sysctl -p after that so you'll activate the changes):

`fs.file-max = 209708`

Try settting something like this in php-fpm.d/ for the desired pool (in my case it's /etc/php-fpm.d/www.conf

```
pm = dynamic
pm.max_children = 100
pm.start_servers = 15
pm.min_spare_servers = 5
pm.max_spare_servers = 50
pm.process_idle_timeout = 90s
pm.max_requests = 4096
```

Restart nginx, restart php-fpm and check if you see any improvement

**Comment by gelanivishal** [comment]
@mnatali80 Also, Share server error log.

**Comment by ghost** [comment]
@mnatali80 i'm closing this for now, if you have some additional steps or information to help us reproduce this issue , please reopen .

**Comment by mnatali80** [comment]
Hi guys, sorry for the late. i have seen that i receive a loop in this file i think vendor/magento/module-customer/Model/Session.php
In the function setCustomerDataAsLoggedIn($customer) if i comment the line 
//$this->_eventManager->dispatch('customer_login', ['customer' => $customerModel]);
i can login but also i receive other error, for example i can't logout and i can't finish the checkout..

**Comment by orlangur** [comment]
@mnatali80 then please check all the observers subscribed to this event (most important - third-part ones).

**Comment by mnatali80** [comment]
Hi guys i grave round the problem :( i' m very sorry..It was a plugin forse cash on delivery ..very very Sorry

**Comment by orlangur** [comment]
@mnatali80 no problem, great that you figured it out and returned back to us with the result of your investigation 👍

**Comment by rakeshdonga** [comment]
hello
i have same issue facing in magento 2.3.2 
any solution about this? 
Thanks!!

**Comment by jo3han** [comment]
> ### Preconditions (*)
> Magento 2.2.6
> 
> ### Steps to reproduce (*)
> 1. Register a customer
> 2. Login ->ok
> 3. After some days (but not whith all customer) retry to login and encounter the error
> 
> ### Expected result (*)
> 1.Normalli login with email and password
> 
> 1.After some days and apparently random the customer(that was able to login without problem until some days ago) can't login and after some seconds (about 40 second) receive a 503 message error from server and from log of server i have this line
> Failed to read FastCGI header, referer: https://mysite.com/customer/account/login/referer/aHR0cHM6Ly90ZXN0Lm1hc3NldGFuaXNob3AuY29tLw%2C%2C/
> [Tue Feb 05 16:48:06.418749 2019] [proxy_fcgi:error] [pid 13550] (104)Connection reset by peer: [client 178.250.70.70:47924] AH01075: Error dispatching request to : , referer: https://mysite.com/customer/account/login/referer/aHR0cHM6Ly90ZXN0Lm1hc3NldGFuaXNob3AuY29tLw%2C%2C/
> 2. Ohter customer can login without any problems

I had this issues a few days ago, upon checking the DB CPU UTILIZATION was at 98% , figured out that the customer queries were causing the timeout due to unable to find customer quote.  So in your mysql editor, run the following command.

`DELETE FROM quote`

this will clear all rows from the quote table.

Question :

- Will removing a row from Quote Table cause issues?
By Default, Quote table contain shopping cart related stuff  and those record is held until the customer decides to finish placing the order from site. For Completed quotes that have been converted to Sales-Order when placed order successfully, Magento automatically clears them with a cron job.

So Quote row is used only Shopping cart to Sales order conversion process. If you delete those row your current quote for Cart will be removed and after add new product new row will be generated.

If your Row with field value is_active equal to 0 means your quote will be not used next time, that record will be useless. 

You can remove your quote row without any worry.

- I hope this helps out someone with the same issue.
