### ISSUE TITLE
"Column not found" SQL error when saving a rule that references `sku` in its conditions

### ISSUE THREAD

**Issue by nathancasebolt** [magento/magento2#21002]
### Preconditions
1. Magento 2.3.0
2. Ubuntu 18.04.1 LTS
3. PHP 7.2.10
4. MySQL 14.14 Distrib 5.7.25
5. Static eav_attribute 74 (`sku`) is set to Store scope

### Steps to reproduce
1. Log into Magento Admin
2. Navigate to **MARKETING > Promotions > Catalog Price Rule**
3. Click the _Add New Rule_ button
4. Create and save a new rule referencing SKU under Conditions

### Expected result
![good](https://user-images.githubusercontent.com/37882858/52302223-1baeac00-2952-11e9-9679-fdaf2a0d9f93.png)

### Actual result
![bad](https://user-images.githubusercontent.com/37882858/52302289-54e71c00-2952-11e9-8057-33fbc90cef53.png)

Database log:
`[2019-02-05 14:42:24] main.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cpa.store_id' in 'field list', query was: SELECT `cpe`.`entity_id`, `cpa`.`store_id`, `cpa`.`value` FROM `catalog_product_entity` AS `cpe` INNER JOIN `catalog_product_entity` AS `cpa` ON cpe.entity_id = cpa.entity_id WHERE (attribute_id = 74)`

### Possible Pain Points
Here's what I think is going on, starting here:

**\Magento\Rule\Model\Condition\Product\AbstractProduct.php:353**
```
if ('category_ids' != $attribute) {
	// stuff
	if ($this->getAttributeObject()->isScopeGlobal()) {
		// stuff
	} else {
                $this->_entityAttributeValues = $productCollection->getAllAttributeValues($attribute);
        }
}
```
Since `sku` has a Store scope rather than Global, we take the `else` path, eventually winding up at the `getAllAttributeValues` function in **\Magento\Catalog\Model\ResourceModel\Product\Collection:1048**. Once we get here, because `sku` has a static `backend_type` with no other associated attribute table, Magento joins the `catalog_product_entity` table to itself, looks for `store_id` (which doesn't exist in that table), and crashes.

**Comment by magento-engcom-team** [comment]
Hi @nathancasebolt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nathancasebolt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Dharmeshvaja91** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91, here is your [Magento instance](https://i-21002-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21002-2-3-develop.instances.magento-community.engineering/admin](https://i-21002-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Dharmeshvaja91** [comment]
Hi @nathancasebolt  i am not able to reproduce the issue.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-21002-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21002-2-3-develop.instances.magento-community.engineering/admin](https://i-21002-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @nathancasebolt this is not best practices to change static attributes `5\. Static eav_attribute 74 (`sku`) is set to Store scope`

**Comment by shikhamis11** [comment]
yes @engcom-backlog-nazar but I have found an issue that we can change the scope of attribute while editing removing disabled attribute of html from web developer tool of browser

**Comment by nathancasebolt** [comment]
> HI @nathancasebolt this is not best practices to change static attributes `5\. Static eav_attribute 74 (`sku`) is set to Store scope`

Hey @engcom-backlog-nazar, thanks for the feedback. Yes, I suspect this problem would be resolved by changing the scope of static attribute `sku` to Global, and perhaps that's how this attribute would be scoped be in a fresh vanilla 2.3 instance (I don't know). However, we migrated this attribute from our Magento 1.7 database, and `sku` in that source db is scoped to Store. At the very least, perhaps the code doesn't account for an attribute that's been scoped one way in Magento 1.x and then migrated into 2.x?

**Comment by ghost** [comment]
@nathancasebolt  thanks for explanation, problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by nathancasebolt** [comment]
> @nathancasebolt thanks for explanation, problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

Thanks. Before I do that, would you be able to tell me whether or not `sku` would be scoped to Global on a fresh instance of Magento 2.3?

**Comment by ghost** [comment]
@nathancasebolt Yes on fresh install 2.3 sku is set to scope global
