### ISSUE TITLE
XSS injection ko checkout

### ISSUE THREAD

**Issue by CompactCodeEU** [magento/magento2#21015]
We were checking a new project for XSS injections on the frontend (controllable fields by the end user). 
You can find them in the next files 

> vendor\magento\module-checkout\view\frontend\web\template\shipping-information\address-renderer\default.html
> vendor\magento\module-checkout\view\frontend\web\template\shipping-address\address-renderer\default.html
> vendor\magento\module-checkout\view\frontend\web\template\billing-address\details.html

They contain fields like : 

`<span html="currentBillingAddress().region"></span>`

### Preconditions (*)
1. Magento 2.2 or 2.3
2. Apache or NGINX
3. Production and developer mode

### Steps to reproduce (*)
1. Create a frontend account
2. Create an address with for example region set to `<script>alert('test')</script>`
3. Go to the checkout page
4. Notice the script alerting

### Expected result (*)
`<span html="currentBillingAddress().region"></span>`
should be
`<text args="currentBillingAddress().region"></text>`

so they are escaped

### Actual result (*)
1.  Script is triggered

**Comment by magento-engcom-team** [comment]
Hi @CompactCodeEU. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@CompactCodeEU do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by CompactCodeEU** [comment]
I can confirm that you can reproduce this on a vanilla Magento instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @CompactCodeEU thank you for you report, this issue has already fixed in 2.3-dev branch.

**Comment by ghost** [comment]
@CompactCodeEU https://github.com/magento-engcom/magento2ce/commit/f9bde4091d147c65944f2e08cad1c84650ca952f

**Comment by CompactCodeEU** [comment]
We are testing this on a 2.3.0 instance. I can confirm that the dev branch does have this fixed. When is this released to the stable version? 2.3.1? The commit links to a 404 page not found

**Comment by DanielRuf** [comment]
See https://github.com/magento/magento2/commit/f9bde4091d147c65944f2e08cad1c84650ca952f

**Comment by CompactCodeEU** [comment]
Ok thanks for the information!
