### ISSUE TITLE
Magento Luma theme cart page move to wishlist icons issue 

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#21026]
### Preconditions (*)

1. Magento 2.3 and Magento 2.2.X

### Steps to reproduce (*)

1. Login to frontend luma theme and add to cart any product.
2. Go to the checkout cart page check  wishlist icons in mobile view
3. wishlist icons  cuts from the right side

### Expected result (*)

1. http://prntscr.com/mhgahg

### Actual result (*)

1. http://prntscr.com/mhgfma

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
