### ISSUE TITLE
Large X-Magento-Tags-Pattern headers not accepted  by varnish

### ISSUE THREAD

**Issue by k4emic** [magento/magento2#21043]
### Preconditions (*)

1. Magento 2.x
2. Any recent varnish with default configuration (with Magento VCL)
3. Very large catalog (67685 products,  10370 categories, 125564 category-product links)

### Steps to reproduce (*)

1. Issue large purge request (as when moving large category structures and/or reindexing large catalogs)

### Expected result (*)

1. PURGE requests sent to Varnish is successful
2.

### Actual result (*)

1. Varnish will respond with either 400 Bad Request (or not respond at all, in extreme cases)
2.

# Analysis
We started seeing this error being reported regularly on our cron server.

```
A valid response status line was not found in the provided string {"method":"GET","url":"http:/","invalidateInfo":{"server":"[object] (Zend\\Uri\\Uri: http://<domain>.net:80/)","tagsPattern":"((^|,)cat_p_49877(,|$))|((^|,)cat_p_49879(,|$))|((^|,)cat_p_49881(,|$))|((^|,)cat_p_49883(,|$))|((^|,)cat_p_49887(,|$))|((^|,)cat_p_49889(,|$))|((^|,)cat_p_49973(,|$))|((^|,)cat_p_49977(,|$))|((^|,)cat_p_50043(,|$))|((^|,)cat_p_50061(,|$))|((^|,)cat_p_50063(,|$))|((^|,)cat_p_50145(,|$))|((^|,)cat_p_50147(,|$))|((^|,)cat_p_50151(,|$))|((^|,)cat_p_50153(,|$))|((^|,)cat_p_50155(,|$))|((^|,)cat_p_50161(,|$))|((^|,)cat_p_50169(,|$))|((^|,)cat_p_50171(,|$))|((^|,)cat_p_50175(,|$))|((^|,)cat_p_50197(,|$))|((^|,)cat_p_50201(,|$))|((^|,)cat_p_50243(,|$))|((^|,)cat_p_63675(,|$))|((^|,)cat_p_63681(,|$))|((^|,)cat_p_64871(,|$))|((^|,)cat_p_64875(,|$))|((^|,)cat_p_64877(,|$))|((^|,)cat_p_64881(,|$))|((^|,)cat_p_80601(,|$))|((^|,)cat_p_80603(,|$))|((^|,)cat_p_80605(,|$))|((^|,)cat_p_80609(,|$))|((^|,)cat_p_80613(,|$))|((^|,)cat_p_80615(,|$))|((^|,)cat_p_80617(,|$))|((^|,)cat_p_80619(,|$))|((^|,)cat_p_80621(,|$))|((^|,)cat_p_80623(,|$))|((^|,)cat_p_80625(,|$))|((^|,)cat_p_80691(,|$))|((^|,)cat_p_80701(,|$))|((^|
....
```

The total length of these tag patterns were exceeding 500KB, containing ~24.000 tags each.

I did some testing to see what happened, and it appeared that varnish was not responding to the PURGE requests.

I did some testing and found the following limitations for request sizes to Varnish:

| request size (bytes) 	| response        	|
|----------------------	|-----------------	|
| 8257                 	| 200 Purged      	|
| 8258                 	| 400 Bad Request 	|
| 32768                	| 400 Bad Request 	|
| 32769                	| \<no response\>   	|

The limitations are tied into these two settings for Varnish:

[http_req_hdr_len](https://varnish-cache.org/docs/6.0/reference/varnishd.html#http-req-hdr-len
) - 8k by default, giving the 400 Bad Request if exceeded.

[http_req_size](https://varnish-cache.org/docs/6.0/reference/varnishd.html#http-req-size) - 32k by default, no response if exceeded.

To remedy this problem, cache tags must either be significantly reduced in size or the purge request must be broken into smaller requests.

**Comment by magento-engcom-team** [comment]
Hi @k4emic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@k4emic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by k4emic** [comment]
Found #8815 after creating this, which is the same problem. Should I close this issue?

**Comment by ghost** [comment]
Hi @k4emic yes, you was find this faster than i'm :)

**Comment by ghost** [comment]
@k4emic ->https://github.com/magento/magento2/pull/8919
