### ISSUE TITLE
If the /customer/section/load call is not made before the user adds a item to the cart, you get an error

### ISSUE THREAD

**Issue by justinharris1986** [magento/magento2#21049]
### Preconditions
1. Magento 2.2.7
2. Slow server/Connection

### Steps to reproduce
1. Load a (in stock) product in to magento
2. with a fresh session navigate directly to that product. (You can navigate to it from the homepage/menu however it is more difficult to trigger this bug.) It is helpful to turn on throttling in your developer tools in Chrome or FF before you visit the page to simulate a poor network connection.
![image](https://user-images.githubusercontent.com/7268384/52437493-0b7b0600-2ae5-11e9-9158-42beb8c78430.png)
3. quickly add that product to the cart, before /customer/section/load is called. 
4. Observe the "your session expired" error

### Expected result
1. Product adds to the cart successfully

### Actual result
1. ![image](https://user-images.githubusercontent.com/7268384/52436984-b7235680-2ae3-11e9-8d09-b5cc1225d377.png)

once the PHPSESSID and the form_key cookies are set this is no longer an issue. It appears that these cookies are set when the browser calls "GET /customer/section/load/"
![image](https://user-images.githubusercontent.com/7268384/52437402-d2429600-2ae4-11e9-8e30-d4791e72bf72.png)

This becomes more of an issue with a slow server, Lots of products/scripts, or a slow/latent/poor connection
2 thoughts on fixing this:
1. have Magento create PHPSESSID and the form_key cookies if they are missing, and then add the product to the cart (preferred - this will help fix other timeouts, say when they leave their browser idle, and the session times out)
2. have this call launch sooner, still may run in to a race condition

This becomes an issue when people land directly on a product page, say from google adwords. The more a user clicks around on the site, the more likely these cookies will be set.

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@justinharris1986 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by justinharris1986** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986, here is your [Magento instance](https://i-21049-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21049-2-2-develop.instances.magento-community.engineering/admin](https://i-21049-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by justinharris1986** [comment]
@magento-engcom-team I was able to reproduce this in a 2.2-dev instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @justinharris1986 thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release

**Comment by justinharris1986** [comment]
Good afternoon @engcom-backlog-nazar 
I appreciate you looking in to this. Are there any plans in fixing it in the 2.2.x branch?

**Comment by cscd98** [comment]
@engcom-backlog-nazar Do you have a link to the PR please?

**Comment by Webroju** [comment]
Has someone found a solution for 2.2.x?
