### ISSUE TITLE
Configurable Product Attributes - Product Page Error after Upgrade from 2.2.2 to 2.3.0

### ISSUE THREAD

**Issue by johnny-longneck** [magento/magento2#21056]
### Preconditions (*)

1. Upgrade from 2.2.2 to 2.3.0
2. Flat Product Table
3. Production or Developer mode

### Steps to reproduce (*)

1. Created custom attributes for product detail page
2. Use attributes for configurables
3. Open a product detail page of a configurable product

### Expected result (*)

1. Product Page has no errors and is displayed correctly

### Actual result (*)
Product Detail Page breaks completely with following error:

```
019/02/07 15:37:13 [error] 16173#16173: *424 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Block\Product\View\Attributes::isVisibleOnFrontend() must be an instance of Magento\Eav\Model\Entity\Attribute\AbstractAttribute, array given, called in /home/magento/www/magento-230/vendor/magento/module-catalog/Block/Product/View/Attributes.php on line 82 and defined in/home/magento/www/magento-230/vendor/magento/module-catalog/Block/Product/View/Attributes.php:110
Stack trace:
#0 /home/magento/www/magento-230/vendor/magento/module-catalog/Block/Product/View/Attributes.php(82): Magento\Catalog\Block\Product\View\Attributes->isVisibleOnFrontend(Array, Array)
#1 /home/magento/www/magento-230//generated/code/Magento/Catalog/Block/Product/View/Attributes/Interceptor.php(37): Magento\Catalog\Block\Product\View\Attributes->getAdditionalData(Array)
#2 /home/magento/www/magento-230/app/design/frontend/THEME/default/Magento_Catalog/templates/product/view/attributes.phtml(5): Magento\Catalog\Block\Product\View\Attributes\Interceptor->getAdditionalData()
#" while reading response header from upstream, client: 127.0.0.1, server: local.mag.com, request: "GET /eu/cool-product.html HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "local.mag.com", referrer: "https://local.mag.com/eu/products/cool-product-category.html"
```

### Note
I could fix it temporarily with opening specific attributes in the backend and saving them again - but the error seem to come back.

**Comment by magento-engcom-team** [comment]
Hi @johnny-longneck. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@johnny-longneck do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @johnny-longneck did you migrated from magento 1 ?

**Comment by johnny-longneck** [comment]
> Hi @johnny-longneck did you migrated from magento 1 ?

Hi, No. The first version going live was 2.1.3 up to 2.2.2 and now I was upgrading to 2.3.0.
In short: All configurable products get this error.

Edit: Both relevant attributes are text swatches.

**Comment by ghost** [comment]
Hi @johnny-longneck i'm not able to reproduce following steps you described, have you installed some custom modules ?

**Comment by johnny-longneck** [comment]
Okay I was busy the day fixing it. 
It might have been because of an template file in my custom theme, which I copied from Core.
This template file, might have been adjusted in the core which was not taking affect due my override.

I close it for now but will investigate if it is 100% fixed.

**Comment by ghost** [comment]
@johnny-longneck Thanks

**Comment by johnny-longneck** [comment]
Just to finish this. 
Now I am 100% sure it was the Amasty - Color Swatches Pro Module which was supposed to be compatible with 2.3.0 but it is not - not in our case.

Disabled it, and everything runs now as expected.
