### ISSUE TITLE
Magento CE 2.3.0: Design issue with custom option fields

### ISSUE THREAD

**Issue by yutv** [magento/magento2#21057]
### Preconditions (*)
1. Magento CE 2.3.0

### Steps to reproduce (*)
1. Create a new product and add a dropdown custom option with a few values

### Expected result (*)
1. Layout should look like this (screenshot from clean Magento CE 2.2.7): 
![2 2 7-clean-magento](https://user-images.githubusercontent.com/1616522/52465782-8fd29500-2b88-11e9-946d-3e3dd6c2a80e.png)

2. Layout with additional fields added by custom module (screenshot from Magento CE 2.2.7):
![2 2 7-with-custom-filds](https://user-images.githubusercontent.com/1616522/52465822-b8f32580-2b88-11e9-976d-11f706fe40a8.png)

### Actual result (*)
1. Clean Magento CE 2.3.0: 
![2 3 0-clean-magento](https://user-images.githubusercontent.com/1616522/52465900-ffe11b00-2b88-11e9-8bd1-7bc53498e9b3.png)

2. Magento CE 2.3.0 + additional fields from custom module:
![2 3 0-with-custom-fields](https://user-images.githubusercontent.com/1616522/52465930-2010da00-2b89-11e9-80b7-98d1a1d1a22d.png)

**Comment by magento-engcom-team** [comment]
Hi @yutv. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@yutv do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @yutv thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release.
![screen](https://user-images.githubusercontent.com/40756439/52466220-471bdb80-2b8a-11e9-8068-df65b867c39d.png)

**Comment by yutv** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @yutv. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @yutv, here is your [Magento instance](https://i-21057-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21057-2-3-develop.instances.magento-community.engineering/admin](https://i-21057-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by yutv** [comment]
It is not completely fixed in 2.3-develop branch, see the screenshot:

![2 3-develop](https://user-images.githubusercontent.com/1616522/52466784-1d63b400-2b8c-11e9-851c-1a5d6c4bd0c6.png)

**Comment by ghost** [comment]
@yutv the pr for this issue in progress

**Comment by ghost** [comment]
@yutv https://github.com/magento/magento2/issues/20337
