### ISSUE TITLE
Website switcher 2.3

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#21058]
Hello,

Since upgrading to Magento 2.3.0, it looks like there is two new Controllers that manage switching stores: 
- \Magento\Store\Controller\Store\Redirect 
- \Magento\Store\Controller\Store\SwitchAction

The problem is that these controllers do not seem to allow us to redirect from a website to an other.

### Preconditions

1. Magento 2.3.0
2. Multi-websites instance
3. PHP 7.2
4. MySQL 5.7

### Steps to reproduce

1. Install Magento 2.3
2. Create at least two websites
3. Create at least one
4. Extend "vendor/magento/module-store/view/frontend/templates/switch/languages.phtml" template to add the websites to the `foreach` loop
5. Try to use the switcher to go to the other website

### Expected result

1. The redirection works

### Actual result

1. The user is being redirected to the same website's homepage

### Additional information

I've tried to debug on my own, and the problem seems to come from the method \Magento\Store\App\Response\Redirect::_getUrl that, instead of getting the base URL of the target website, uses the current store's base URL.

The debug process is the following:

1. `vendor/magento/module-store/view/frontend/templates/switch/languages.phtml` calls `\Magento\Store\Block\Switcher::getTargetStorePostData` method
2. `\Magento\Store\Block\Switcher::getTargetStorePostData` redirects to the Controller `\Magento\Store\Controller\Store\Redirect` 
3. `\Magento\Store\Controller\Store\Redirect` redirects to the Controller `\Magento\Store\Controller\Store\SwitchAction`
4. `\Magento\Store\Controller\Store\SwitchAction` calls the `\Magento\Store\App\Response\Redirect::getRedirectUrl` method
5. `\Magento\Store\App\Response\Redirect::getRedirectUrl` calls the `\Magento\Store\App\Response\Redirect::_getUrl` method
6. The `\Magento\Store\App\Response\Redirect::_getUrl` method uses the current store base URL:
```php
$refererUrl = $this->_storeManager->getStore()->getBaseUrl();
```

**Comment by magento-engcom-team** [comment]
Hi @Axel29. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Axel29 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Axel29** [comment]
Hi @magento-engcom-team,

I confirm that I can reproduce the issue on vanilla Magento instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Axel29 thank you for you report, i'm not able to reproduce following steps, you described, 
`<a href='<?php echo $website->getDefaultStore()->getCurrentUrl() `
I  my case all works perfectly.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by Axel29** [comment]
Hi,

I've managed to narrow down the issue. The bug only seems to appear when using store codes in URLs.

**Comment by Axel29** [comment]
Hi @engcom-backlog-nazar ,

I've managed to narrow down the issue. The bug only seems to appear when using store codes in URLs and when the two websites have different URLs (e.g: http://mywebsite.com/ + http://en.mywebsite.com/)

**Comment by Axel29** [comment]
New comment @engcom-backlog-nazar , the problem is in `\Magento\Store\App\Response\Redirect::_isUrlInternal` method that compares the base URL of the current website to the destination's website base URL.
