### ISSUE TITLE
Magento 2.2.6 Searching for product with dash doesn't work

### ISSUE THREAD

**Issue by Luuk-Meijer** [magento/magento2#21059]
### Preconditions (*)
1. Magento 2 version 2.2.6

### Steps to reproduce (*)
1. In "vendor/magento/module-catalog-search/etc/search_request.xml" change 
```xml
<query xsi:type="boolQuery" name="quick_search_container" boost="1">
    <queryReference clause="should" ref="search" />
    <queryReference clause="must" ref="category"/>
    <queryReference clause="must" ref="price"/>
    <queryReference clause="must" ref="visibility"/>
</query>
```
to
```xml
<query xsi:type="boolQuery" name="quick_search_container" boost="1">
    <queryReference clause="must" ref="search" />
    <queryReference clause="must" ref="category"/>
    <queryReference clause="must" ref="price"/>
    <queryReference clause="must" ref="visibility"/>
</query>
```
So that the search query "blue boot" only shows products with both the words.
2. Add a product in the back-end with a name with a dash (-) in the name.
For instance "Lakboot Black Mat New A-327 N118" in my case
3. On the frontend search for that product.
So with my example you would search for "A-327".
4. Now when you have the search clause for must nothing is going to show up.

### Expected result (*)
1. You would expect the product to show up

### Actual result (*)
1. There are no results found

**Comment by magento-engcom-team** [comment]
Hi @DeLuuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DeLuuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Luuk-Meijer** [comment]
@magento-engcom-team I can't reproduce this on a vanilla instance since the "vendor/magento/module-catalog-search/etc/search_request.xml" needs to be changed first.

I know that that would maybe mean it isn't a vanilla bug but in my opinion editing that clause should be possible and should work.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @DeLuuk thank you for you report, this will fixed by this pr -> https://github.com/magento/magento2/pull/20727

**Comment by ghost** [comment]
@DeLuuk 
> After changing any of these options, rebuild your FULLTEXT indexes for the change to take effect. For example, to make two-character words searchable, you could put the following lines in an option file:
```
[mysqld]
innodb_ft_min_token_size=2
ft_min_word_len=2
```
https://dev.mysql.com/doc/refman/8.0/en/fulltext-fine-tuning.html

**Comment by Luuk-Meijer** [comment]
@magento-engcom-team thanks for linking other issue but Im still having trouble.

I want to be able to search for "A-327" **not** just "A-".
I haven't edited my option file yet, don't even know where that file is, but even if I do I dont think that would fix my problem.

Like I said in the reproduce steps, this isn't just a vanilla Magento 2.2.6 enviroment.

I edited "vendor/magento/module-catalog-search/etc/search_request.xml". If I reverse does changes then it works. But I want to keep those changes since I dont want my search query to work with OR but with AND.

And those changes aren't made in pr -> #20727.

So if I can I'm reopening this since it isn't fixed.

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar can this issue be opened again?

**Comment by ghost** [comment]
@DeLuuk i'm will recheck, this must be environmental issue

**Comment by ghost** [comment]
@DeLuuk yes this is non-issue after i apply changes from pr and set -> https://github.com/magento/magento2/issues/21059#issuecomment-461738901
![selection_321](https://user-images.githubusercontent.com/40756439/52469923-77b54280-2b95-11e9-8472-3075a47fb575.png)

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar but now change:
"vendor/magento/module-catalog-search/etc/search_request.xml" change
```
<query xsi:type="boolQuery" name="quick_search_container" boost="1">
    <queryReference clause="should" ref="search" />
    <queryReference clause="must" ref="category"/>
    <queryReference clause="must" ref="price"/>
    <queryReference clause="must" ref="visibility"/>
</query>
```
to
```
<query xsi:type="boolQuery" name="quick_search_container" boost="1">
    <queryReference clause="must" ref="search" />
    <queryReference clause="must" ref="category"/>
    <queryReference clause="must" ref="price"/>
    <queryReference clause="must" ref="visibility"/>
</query>
```
And see what happens then

**Comment by ghost** [comment]
@DeLuuk yes i'm set this :)
![selection_322](https://user-images.githubusercontent.com/40756439/52470014-b0edb280-2b95-11e9-8a57-5be25ed7a9ab.png)

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar oke in that case Im gone try editing that option file.

Where can I find that option file? The url you linked is just for MySql specific, not Magento specific.

I mean I can't put that in a .htaccess or something?

**Comment by ghost** [comment]
@DeLuuk you on ubuntu ? this is in mysqld  `sudo nano /etc/mysql/mysql.conf.d/mysqld.cnf `
find the [mysqld] section  add following 
```
[mysqld]
innodb_ft_min_token_size=2
ft_min_word_len=2
```
then restart mysql server

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar is that server wide? I have my test shop on the same server as the live shops. So I want to be sure that I dont break anything

**Comment by ghost** [comment]
@DeLuuk this will affect for all websites if they use same server. try to test this locally.

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar I have CentOS not Ubuntu.

Also I know Im asking a lot of questions and this isn't support but how can I test it locally.. 😅

**Comment by ghost** [comment]
@DeLuuk in centOS this file in ->` /etc/my.cnf` add after [mysqld]
```
innodb_ft_min_token_size=2
ft_min_word_len=2
```

**Comment by Luuk-Meijer** [comment]
Oke @engcom-backlog-nazar Im gone have to believe you on your word then since Im not adding this for the live just yet!!

Im gone push it live next tuesday morning so I'm hoping this is gone work!!

Thanks for answering all my questions!

**Comment by ghost** [comment]
@DeLuuk your welcome,  But also add changes from reference Pull Request.

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar Yes I realise that thanks!! Will do 😄

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar Oke I just changed the files to match this [commit](https://github.com/magento/magento2/pull/20727/commits/cb681ab9f7f44457b420d7ae86cf7b324b7b8c94) and added this to `/etc/my.cnf`:
```
innodb_ft_min_token_size=2
ft_min_word_len=2
```

But I still can't search for "A-327".
(And yes I restarted mysql, upgraded, compiled, redeployed, reindexed and flushed the cache)

**Comment by ghost** [comment]
@DeLuuk wrong commit you simply need add "-" to this ->   
` const SPECIAL_CHARACTERS = '-+~/\\<>\'":*$#@()!,.?`=%&^';`

https://github.com/Nazar65/magento2/blob/7539e8e6829197467b59e417e317d38ea39a005b/lib/internal/Magento/Framework/Search/Adapter/Mysql/Query/Builder/Match.php#L29

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar the reason I did the [other commit](https://github.com/magento/magento2/pull/20727/commits/cb681ab9f7f44457b420d7ae86cf7b324b7b8c94) is because [that commit](https://github.com/Nazar65/magento2/blob/7539e8e6829197467b59e417e317d38ea39a005b/lib/internal/Magento/Framework/Search/Adapter/Mysql/Query/Builder/Match.php#L29) was already in my Magento 2.2.6 environment.
But I just removed the [other commit](https://github.com/magento/magento2/pull/20727/commits/cb681ab9f7f44457b420d7ae86cf7b324b7b8c94) just incase. But that also doesn't work.

**Comment by ghost** [comment]
@DeLuuk ok thanks, give me 5 minutes i'm will recheck, because i'm migrated to archlinux :)

**Comment by ghost** [comment]
@DeLuuk 
![deepin-screen-recorder_chromium_20190213112004](https://user-images.githubusercontent.com/40756439/52700789-7747ed80-2f81-11e9-9eb8-839b2f06361b.gif)

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar I see. I noticed that thats a 2.3dev environment. Does this also work on a 2.2.6 environment?

**Comment by ghost** [comment]
@DeLuuk hm.. try  change to     `<queryReference clause="should" ref="search" />`

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar yeah but that's the whole point! That would indeed work.

But then if customers search for "Blue boots" they get all the products with "Blue" **or** "boots". My client wants to only show products that have "Blue" **and** "boots". That way the search results go from 300 to 20.

**Comment by ghost** [comment]
@DeLuuk yeap, i'm found the problem this works for skus like this 41-315 but does not for sku like yours A-315

**Comment by Luuk-Meijer** [comment]
Oke @engcom-backlog-nazar but now what?

Can this be fixed or is it already fixed somewhere? Or?

**Comment by ghost** [comment]
@DeLuuk i will recheck it deeper this may be related to minimal search words, but anyway i'm will reopen this if have no solution and this caused by magento

**Comment by ghost** [comment]
@DeLuuk The core problem in Mysql because they have not ability to set min_search_world to =1 , your select is `AGAINST ('+a* +315*' IN BOOLEAN MODE))` where +a have 1 lenth word that mysql does not find product but if you have 2 words that it works.

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar oke so you're saying that for it to work you need to be able to search for 1 character?
Damn... That works great for "A-327", but if 10 people search for just "A" that could be bad..

What do you suggest? Is there a fix for this?

**Comment by ghost** [comment]
@DeLuuk https://lists.mysql.com/mysql/174354

**Comment by ghost** [comment]
@DeLuuk this is Mysql bug https://bugs.mysql.com/bug.php?id=2095

**Comment by ghost** [comment]
@DeLuuk here is another workaround. It was recently added to the manual:
"
Modify a character set file: This requires no recompilation. The true_word_char()  macro uses a “character type” table to distinguish letters and numbers from other characters. . You can edit the <ctype><map> contents in one of the character set XML files to specify that '-' is a “letter.” Then use the given character set for your FULLTEXT indexes.
"

**Comment by Luuk-Meijer** [comment]
@engcom-backlog-nazar Oke and I'm guessing you have to use the true_word_char() macro when you sent the string to mysql?
If so, do you know the file that that's located in? I had searched that file for a long time and couldn't find it before..

But again thanks for helping me so far!

**Comment by Puru2016** [comment]
Any solution in Magento 2.2.6 ? I am still facing this issue

**Comment by Luuk-Meijer** [comment]
@Puru2016 in the end I didn't get it working with standard Magento 2 unfortunately.

I did however install this extension that made it work.

[https://mirasvit.com/magento-2-extensions/sphinx-search-ultimate.html](https://mirasvit.com/magento-2-extensions/sphinx-search-ultimate.html)

**Comment by toanthree** [comment]
> @Puru2016 in the end I didn't get it working with standard Magento 2 unfortunately.
> 
> I did however install this extension that made it work.
> 
> https://mirasvit.com/magento-2-extensions/sphinx-search-ultimate.html

Thanks for pointing it out. Mirasvit extension works for me as well.
