### ISSUE TITLE
v2.3.0 serving site from pub, now images get 404

### ISSUE THREAD

**Issue by travis5491811** [magento/magento2#21052]
### Preconditions (*)

1. Version 2.3.0 Community edition. 
2. Ubuntu 18.04 and Apache, default config.
3. apache config set with DocumentRoot set to `/var/www/html/magento2/pub`

### Steps to reproduce (*)

1. Setup new site, add images to categories and make sure everything is displaying normally.
2. Change site to be served from doc root following steps from magento [here](https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html).
3. Visit site.

### Expected result (*)

1. Pages load normally and show images.

### Actual result (*)

1. Images in backend and front-end do not load. 
2. Browser console output example `GET http://192.168.5.10/pub/media/Shoes/nike.jpg 404 (Not Found)`

### What i've tried without success.

 1. Looking for errors in `/var/log/apache2/error.log` and  `/var/log/apache2/error.log` (found nothing other than a record of 404 but no permission errors.)
 2. Checked `magento/var/log/system.log`, `magento/var/log/exception.log` and `magento/var/log/debug.log`, no permission errors.
 3. Switching modes:

        bin/magento deploy:mode:set production  
        bin/magento cache:flush  
        bin/magento deploy:mode:set developer  
        bin/magento cache:flush  

 4. Made sure had default `.htaccess` in `magento` directory.

 5. Made sure `pub/` had default `.htaccess`.

 6. `bin/magento setup:static-content:deploy -f`

 7. "Flush Cache Storage", "Flush Magento Cache", "Flush Catalog Images Cache", and "Flush Static Files Cache" from admin area > System > Cache Management.

 8. Refresh all cache types from admin area > System > Cache Management.

 9. Re-ran [permissions][2] as root `cd /var/www/html/magento2 && find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} + && find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} + && chown -R :www-data . && chmod u+x bin/magento`

 10. Checking permissions of example image from magento directory:

        magentouser$ ls -al pub/media/Shoes/nike.jpg
        -rw-rw-r-- 1 magentouser www-data 77645 Jan 15 17:14 pub/media/Shoes/nike.jpg

 11. `rm -rf var/cache`

 12. `bin/magento indexer:reindex`

 How do you resolve this?

  [1]: https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html
  [2]: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/file-system-perms.html

**Comment by magento-engcom-team** [comment]
Hi @travis5491811. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@travis5491811 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by travis5491811** [comment]
@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @travis5491811. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @travis5491811, here is your [Magento instance](https://i-21052-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21052-2-3-develop.instances.magento-community.engineering/admin](https://i-21052-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by travis5491811** [comment]
This is insufficient access to reproduce the issue. Your magento docs state to modify the apache2 DocumentRoot to serve from pub. You only gave me access to the magento admin GUI.

@travis5491811 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?

* [x]  yes
* [ ]  no

**Comment by ananth-iyer** [comment]
@travis5491811 
If Apache config set with DocumentRoot set to `/var/www/html/magento2/pub`

Then media & static files base url must be as below:
**Media base url**
http://192.168.5.10/media/

**Status base url**
http://192.168.5.10/static/

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @travis5491811 thank you for you report, refer to https://github.com/magento/magento2/issues/21052#issuecomment-461693505, i'm closing this one as this is non-issue

**Comment by travis5491811** [comment]
hello @ananth-iyer, where do i update the following?

> Then media & static files base url must be as below:
> **Media base url**
> http://192.168.5.10/media/
> 
> **Status base url**
> http://192.168.5.10/static/

The [docs](https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html) only inform users about what to update for base url

> Log in to the Magento database:
> 
> mysql -u <user> -p
> Specify the Magento database you created when you installed Magento:
> 
> use <database-name>
> Update the base URL:
> 
> UPDATE core_config_data SET value='http://192.168.33.10' WHERE path='web/unsecure/base_url';

**Comment by travis5491811** [comment]
@magento-engcom-team re-open issue

@ananth-iyer I have no idea how "/pub/" ended up in the URL. I did not manually change anything other than what the docs said to change. This is a bug in magento 2.3.0 when serving from pub after the site has been developed.

**Comment by ananth-iyer** [comment]
@travis5491811 Can you set apache documentRoot to **/var/www/html/magento2** (After that restart apache server)? let me know what you see

**Comment by travis5491811** [comment]
@ananth-iyer Ok, I set doc root back to magento2, restarted apache.

First thing i noticed: pub is still in image url and image not found. I'm not sure how my site got broken just from serving from pub.

So i did:
```
bin/magento deploy:mode:set production  
bin/magento cache:flush  
bin/magento deploy:mode:set developer  
bin/magento cache:flush
```
But still same problem is there. Not sure what else to do.


**UPDATE**: i was in the wrong demo server during the above test. I had spun up so many test servers trying to re-duplicate the issue in different ways. I noticed while deleting all the demo servers from the network that the command was in the wrong one. Here are the correct results after switching back to documentRoot to **/var/www/html/magento2**

All images show up again normally. but the URL is still like (example): http://192.168.5.10/pub/media/Shoes/nike.jpg

still not sure how "pub" got in there or even how i would add "pub" if it was't there and I wanted it.

**Comment by travis5491811** [comment]
@ananth-iyer I am able to get to the image if i remove "pub" from url manually. I just do know how to correct all the urls.

I even tried to run this again:
```
UPDATE core_config_data SET value='http://192.168.5.10' WHERE path='web/unsecure/base_url';
```

**Comment by travis5491811** [comment]
@ananth-iyer 

Even more strange:

If i go back to the category and click content > select from gallery > and choose the image and click "save". The image shows up on the front end with the correct url  (without pub) like:

```
http://192.168.5.10/pub/media/Shoes/nike.jpg
```
But now, if i revist that category on the backend, and click content, there is no image there! Not even a broken image. It just looks like it did before i ever tried to upload an image even through the image is showing up on the front-end now.

This is a default installation of 2.3.0, with no additional third party modules installed.

**Comment by ghost** [comment]
@travis5491811 seems like something wrong with your environment

**Comment by travis5491811** [comment]
@engcom-backlog-nazar like what? How to troubleshoot?

"something wrong with environment" yes but with a default installation, it seems more like magento is full of bugs (that get closed quickly unresolved) and I've somehow manged to perform the right order of operations in a long process to trigger evidence of how buggy magento is. 

If that's not the case, someone from magento should be able to look at the information i've provided for a default installation and say "that is affected by X in a default installation....do this." but it appears the designer of magento is far from the people responsible for maintaining docs and implementing other logic in the code base, or looking at issues opened.

I could understand if i had added some third party modules, or manually created a folder structure via the command line on the back-end.

**Comment by ghost** [comment]
@travis5491811 but why i'm able to install magento with Docroot "pub" and many people, and you not ?

**Comment by travis5491811** [comment]
@engcom-backlog-nazar I can too. I've done it on two different machines. 

Try default magento install (not serving from pub), then creating 4 categories that each have 20 or more sub categories. Then add content > image to each sub category. 

Browse the site and make sure everything looks normal. At this point adding products isn't important, you just want to click the navigation menus that show up as a result of creating the categories. 

Now change the site to serve from pub following the docs....problem shows up.

If i start building a site that is serving from pub...no problem. But existing site being moved to pub...bug appears.

Also NOTE: My installation does include the [following customization](https://magento.stackexchange.com/questions/252256/magento-2-3-favicon-and-logo-upload-does-not-take-hold/255782#255782) to work around this 2.3.0 bug that apparently is fixed in 2.3.1:

```
File path : /vendor/magento/module-theme/view/adminhtml/ui_component/design_config_form.xml

Find and replace :

<field name="header_logo_src" formElement="fileUploader">
To
<field name="header_logo_src" formElement="imageUploader">

<field name="head_shortcut_icon" formElement="fileUploader">
To
<field name="head_shortcut_icon" formElement="imageUploader">
```

No other code changes, code customizations or third party modules are on my installation.

**Comment by ghost** [comment]
@travis5491811 thanks for explanation, i'm will recheck

**Comment by travis5491811** [comment]
@engcom-backlog-nazar do you have a place i can send a pre-configured esxi image of before/after?
