### ISSUE TITLE
Attention something went wrong. On new installation after disabling cache.

### ISSUE THREAD

**Issue by kingshukdeb** [magento/magento2#21066]
### Preconditions (*)

1. Magento version 2.2.7

### Steps to reproduce (*)

1. Install magento.
2. Go to backend. Disable cache.
3. Go to content->design-> Theme configuration.
4. Open the store view clicking on edit (you can open website also ) -> click on save configuration. 

### Expected result (*)

1. It should save without throwing an error.

### Actual result (*)

1. [Screenshots, logs or description]
2. It saves data. But throws the error Attention something went wrong.
![screenshot from 2019-02-08 11-22-08](https://user-images.githubusercontent.com/4508615/52476047-548a9300-2b95-11e9-8b2a-6502242372f4.png)

**Comment by magento-engcom-team** [comment]
Hi @kingshukdeb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kingshukdeb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @kingshukdeb thank you for you report, this issue has already fixed in 2.2-devlop branch and will be avaible on 2.2.8 release.

**Comment by kingshukdeb** [comment]
Can you let us know the commit id for this?

**Comment by ghost** [comment]
@kingshukdeb i will try to find, I'm just tested on fresh 2.2-dev and error does not appear

**Comment by kingshukdeb** [comment]
Also does this mean this issue should be fixed on 2.3 already..because i am able to reproduce that on 2.3

**Comment by ghost** [comment]
@kingshukdeb on 2.3.0 ? or 2.3-develop ?

**Comment by kingshukdeb** [comment]
2.3.0 - the latest release one.

**Comment by ghost** [comment]
@kingshukdeb just checked on 2.3.0 have no this error, some additional information ?

**Comment by kingshukdeb** [comment]
Can you give me a 2.3.0 instance please

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21066-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21066-2-3-develop.instances.magento-community.engineering/admin](https://i-21066-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kingshukdeb** [comment]
Not able to login. Can you please check

**Comment by ghost** [comment]
@kingshukdeb i'm able to login. please try again

**Comment by kingshukdeb** [comment]
Here is the error there. I just had to disable cache and it poped up.
![screenshot from 2019-02-08 13-01-08](https://user-images.githubusercontent.com/4508615/52479793-bcdf7180-2ba1-11e9-8cd4-2c729710ee3e.png)

**Comment by kingshukdeb** [comment]
Can you give me a 2.2 develop please

**Comment by kingshukdeb** [comment]
Its really a weird one sometime it just comes directly after disabling cache. Sometimes after save a theme sometimes somewhere else. But its there.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98178`, `MAGETWO-98179` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
