### ISSUE TITLE
Product list sort order is saved but not used

### ISSUE THREAD

**Issue by michi-p** [magento/magento2#21076]
### Preconditions (*)

1. Magento CE version 2.2.6
2. PHP 7.1.25
3. At least two categories with an arbitrary number of products each.

### Steps to reproduce (*)

1. Open a category in your shop (e. g. shop.example.com/food.html)
2. Change the sort order (e. g. from 'position' to 'name'). URL changes to *shop.example.com/food.html?product_list_order=name*
3. Switch to other category (e. g. shop.example.com/drinks.html)

### Expected result (*)

1. The products of the category `drinks` should be shown sorted by their names

### Actual result (*)

1. The products of the category `drinks` are shown sorted by position (default value)

### Additional information
The function [\Magento\Catalog\Block\Product\ProductList\Toolbar::getCurrentOrder](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Block/Product/ProductList/Toolbar.php#L232) calls the method `_memorizeParam` where the selected sort order is saved in the catalog session. (It's not disabled in my case, the function [setData](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Block/Product/ProductList/Toolbar.php#L172) is called and the saved value is correct as well).  
However, this session value seems to be not used again anywhere.

**Comment by magento-engcom-team** [comment]
Hi @michi-p. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@michi-p do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @michi-p   thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by fritzmg** [comment]
@engcom-backlog-nazar This is not a feature request. Magento 1.x supports this functionality by default and Magento 2.x already saves the last sort order in the session. However, it never actually reads the last sort order from the session, as explained in the original post.

**Comment by ghost** [comment]
@fritzmg but this is magento 2 not one. so this is feature.

**Comment by fritzmg** [comment]
As already said, 

>  Magento 2.x already saves the last sort order in the session.

Yet, it does not use it anywhere. Why would that be on purpose?

**Comment by ghost** [comment]
@fritzmg ok can you provide more information ?  so we can edit this issue and report as issue.

**Comment by fritzmg** [comment]
@engcom-backlog-nazar the necessary information is already posted here: https://github.com/magento/magento2/issues/21076#issue-408160019

> The function [\Magento\Catalog\Block\Product\ProductList\Toolbar::getCurrentOrder](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Block/Product/ProductList/Toolbar.php#L232) calls the method `_memorizeParam` where the selected sort order is saved in the catalog session. 
> However, this session value seems to be not used again anywhere.

https://github.com/magento/magento2/blob/32e14dbda4da211f86fc25ef62a42378448fa434/app/code/Magento/Catalog/Block/Product/ProductList/Toolbar.php#L252-L254

https://github.com/magento/magento2/blob/32e14dbda4da211f86fc25ef62a42378448fa434/app/code/Magento/Catalog/Block/Product/ProductList/Toolbar.php#L169-L175

The `sort_order` parameter is saved in the session, but never loaded from the session anywhere again. The same applies to `sort_direction` by the way.

**Comment by fritzmg** [comment]
Look at the differences between the old Magento 1.x code and the new Magento 2.x code:

### Magento 1.x

```php
/**
 * Get grit products sort order field
 *
 * @return string
 */
public function getCurrentOrder()
{
    $order = $this->_getData('_current_grid_order');
    if ($order) {
        return $order;
    }

    $orders = $this->getAvailableOrders();
    $defaultOrder = $this->_orderField;

    if (!isset($orders[$defaultOrder])) {
        $keys = array_keys($orders);
        $defaultOrder = $keys[0];
    }

    $order = $this->getRequest()->getParam($this->getOrderVarName());
    if ($order && isset($orders[$order])) {
        if ($order == $defaultOrder) {
            Mage::getSingleton('catalog/session')->unsSortOrder();
        } else {
            $this->_memorizeParam('sort_order', $order);
        }
    } else {
        $order = Mage::getSingleton('catalog/session')->getSortOrder();
    }
    // validate session value
    if (!$order || !isset($orders[$order])) {
        $order = $defaultOrder;
    }
    $this->setData('_current_grid_order', $order);
    return $order;
}
```

### Magento 2.x

```php
/**
 * Get grit products sort order field
 *
 * @return string
 */
public function getCurrentOrder()
{
    $order = $this->_getData('_current_grid_order');
    if ($order) {
        return $order;
    }

    $orders = $this->getAvailableOrders();
    $defaultOrder = $this->getOrderField();

    if (!isset($orders[$defaultOrder])) {
        $keys = array_keys($orders);
        $defaultOrder = $keys[0];
    }

    $order = $this->_toolbarModel->getOrder();
    if (!$order || !isset($orders[$order])) {
        $order = $defaultOrder;
    }

    if ($order != $defaultOrder) {
        $this->_memorizeParam('sort_order', $order);
    }

    $this->setData('_current_grid_order', $order);
    return $order;
}
```

Magento 2.x is missing the following:

```diff
 /**
  * Get grit products sort order field
  *
  * @return string
  */
 public function getCurrentOrder()
 {
     $order = $this->_getData('_current_grid_order');
     if ($order) {
         return $order;
     }
 
     $orders = $this->getAvailableOrders();
     $defaultOrder = $this->getOrderField();
 
     if (!isset($orders[$defaultOrder])) {
         $keys = array_keys($orders);
         $defaultOrder = $keys[0];
     }
 
     $order = $this->_toolbarModel->getOrder();
+    if ($order && isset($orders[$order])) {
+        if ($order == $defaultOrder) {
+            $this->_catalogSession->unsetData('sort_order');
+        }
+    } else {
+        $order = $this->_catalogSession->getData('sort_order');
+    }
+
     if (!$order || !isset($orders[$order])) {
         $order = $defaultOrder;
     }
 
     if ($order != $defaultOrder) {
         $this->_memorizeParam('sort_order', $order);
     }
 
     $this->setData('_current_grid_order', $order);
     return $order;
 }
```
Or may be use the old code structure:
```diff
 /**
  * Get grit products sort order field
  *
  * @return string
  */
 public function getCurrentOrder()
 {
     $order = $this->_getData('_current_grid_order');
     if ($order) {
         return $order;
     }
 
     $orders = $this->getAvailableOrders();
     $defaultOrder = $this->getOrderField();
 
     if (!isset($orders[$defaultOrder])) {
         $keys = array_keys($orders);
         $defaultOrder = $keys[0];
     }
 
     $order = $this->_toolbarModel->getOrder();
+    if ($order && isset($orders[$order])) {
+        if ($order == $defaultOrder) {
+            $this->_catalogSession->unsetData('sort_order');
+        } else {
+            $this->_memorizeParam('sort_order', $order);
+        }
+    } else {
+        $order = $this->_catalogSession->getData('sort_order');
+    }
+
     if (!$order || !isset($orders[$order])) {
         $order = $defaultOrder;
     }
 
-    if ($order != $defaultOrder) {
-        $this->_memorizeParam('sort_order', $order);
-    }
 
     $this->setData('_current_grid_order', $order);
     return $order;
 }
```
(untestet)

**Comment by ghost** [comment]
@fritzmg nice find!, can you prepare a pull request  for this ?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98216`, `MAGETWO-98217` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by fritzmg** [comment]
The same applies to `Toolbar::getCurrentDirection()`.

> @fritzmg nice find!, can you prepare a pull request for this ?

Yes, we can test the changes and prepare a Pull Request.

**Comment by fritzmg** [comment]
@engcom-backlog-nazar since this is something that (presumably) never worked in Magento 2.x, but did work in Magento 1.x - should it still be considered a bug fix, or would it technically be a new feature? Against which branch should this PR be targeted?

**Comment by ghost** [comment]
@fritzmg 2.3-develop, this would be a feature request and need to be cover with tests.

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by engcom-Charlie** [comment]
Hi @michi-p,
We are not able to reproduce issue by the following steps:

1. Go to Store -> Configuration -> Catalog -> Catalog -> Storefront.
2. Set `Remember Category Pagination` to `Yes`.
3. Open a category in your shop.
4. Change the sort order (e. g. from 'position' to 'name').
5. Switch to another category.

**AR**: The products of the category should be shown sorted by their names.

Please could you take a look?

**Comment by michi-p** [comment]
I'm not using Magento's default category functionality anymore and updated to Magento 2.3 in the meantime. So, can you provide a Magento 2.2.6 instance where I can check if the issue is still reproducible?

**Comment by engcom-Charlie** [comment]
Hi @michi-p,
Can You please verify on latest 2.4-develop?
You can get instance by typing comment with text `@magento give me 2.4-develop instance`

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-21076-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-21076-2-4-develop.instances.magento-community.engineering/admin_6fbd](https://i-21076-2-4-develop.instances.magento-community.engineering/admin_6fbd)
Login: `4a11a3c1` Password: `f8b28e1c6262`
Instance will be terminated in up to 3 hours.

**Comment by michi-p** [comment]
Hi @engcom-Charlie,
just tested on 2.4-develop instance and it's not reproducible anymore. When `Remember Category Pagination` is set to `Yes`, the sorting of the product list remains the same.

**Comment by engcom-Charlie** [comment]
Nice, then I'll close the issue.
