### ISSUE TITLE
Generates duplicate rows for the store view which is not selected in product export

### ISSUE THREAD

**Issue by vrutiksuthar** [magento/magento2#21082]
Feature: Import/Export

### Preconditions (*)
1. Magento 2.2.7 Fresh Install

### Steps to reproduce (*)
1. Create multiple website and store views.
2. Create a simple product and add custom options.
3. Set product in only one website.
4 Export the product from the export feature.

### Expected result (*)
1. The product should only generate the rows for the assigned store view and default store view in the CSV file.

### Actual result (*)
1. Product data showing for the store view in the exported CSV file which is not selected for the product.
2. Product website configurations
![product_configuration](https://user-images.githubusercontent.com/37930309/52485595-3fd2ed00-2bdf-11e9-9e39-1828ed137d17.png)
3. Exported Result which should not have the row for "Test Website Two" store view as its not selected in product configurations.
![csv_result](https://user-images.githubusercontent.com/37930309/52485623-4e210900-2bdf-11e9-943b-b4e11f29ac5a.png)

**Comment by magento-engcom-team** [comment]
Hi @mage-master. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mage-master do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @mage-master seem like this may be fix your problem -> https://github.com/magento/magento2/pull/19395

**Comment by vrutiksuthar** [comment]
Hello @engcom-backlog-nazar ,

I have checked solution #19395 which is already there for Magento 2.2.7 still I am facing this issue.

Kindly provide a working solution OR commit reference for the same.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21082-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21082-2-3-develop.instances.magento-community.engineering/admin](https://i-21082-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
HI @vrutiksuthar i'm not able to reproduce following steps you described on 2.2-develop and 2.3-develop branch this may be related to your custom modules.

**Comment by vrutiksuthar** [comment]
Hello @engcom-backlog-nazar,

It seems to be fixed in the 2.3-develop instance, but currently, I am facing this issue on one of my live site so would you able to share specific commit reference OR patch which fixed this issue and I can apply in my instance?

Thank you.

**Comment by vrutiksuthar** [comment]
Hello @engcom-backlog-nazar @magento-engcom-team,

Any update???

**Comment by amcguireweb** [comment]
> Hi @magento-engcom-team 
> I am facing the same issue on Magento 2.4.8-p5 instance, any update for this one?

I am also seeing this suddenly after updating to 2.4.8-p5!

**Comment by amcguireweb** [comment]
For anyone hitting this on 2.4.x (including the 2.4.8-p5 report above) — the cause for us was the **`ACP2E-3731`** quality patch.

**What it does:** ACP2E-3731 rewrites `Magento\CatalogImportExport\Model\Export\Product::loadCollection()` to build a fresh product collection per store view, but never re-applies the pagination `export()` sets. So the data-load step ignores the page limit and **every export batch re-loads and re-writes the entire catalog** — each product is duplicated N times, where N = the number of batches the export runs (exports in 4 batches → ×4). It's also why this never reproduces on vanilla: vanilla's `loadCollection()` reuses the single, already-paginated collection.

**Confirm you have ACP2E-3731:** in `vendor/magento/module-catalog-import-export/Model/Export/Product.php`, if `loadCollection()` calls `$this->_getEntityCollection(true)` *inside* the store-view loop, it's applied.

**Fix** — re-apply the page window to each per-store collection. ⚠️ **Prerequisite: ACP2E-3731 must be applied first** — this patches the code that patch introduces, so it won't apply to a vanilla install. (Line context targets 2.4.8-p5 + ACP2E-3731; adjust for your version.)

```diff
     protected function loadCollection(): array
     {
         $data = [];
+        $curPage = $this->_getEntityCollection()->getCurPage();
+        $pageSize = $this->_getEntityCollection()->getPageSize();
         foreach (array_keys($this->_storeIdToCode) as $storeId) {
             $collection = $this->_getEntityCollection(true);
             $collection->setOrder('entity_id', 'asc');
             $collection->setStoreId($storeId);
             $this->_prepareEntityCollection($collection);
+            $collection->setCurPage($curPage);
+            $collection->setPageSize($pageSize);
             $collection->load();
             foreach ($collection as $itemId => $item) {
                 $data[$itemId][$storeId] = $item;
             }
             $collection->clear();
         }

         return $data;
     }
```

The first added pair captures the page window before the per-store loop resets the collection; the second re-applies it so each batch loads only its slice — while keeping ACP2E-3731's per-store visibility fix. Verified on a live 2.4.8-p5 store: a multi-store product export went from every product duplicated to exactly one row each (plus legit store-view rows), identical to a single-batch export.
