### ISSUE TITLE
Allow viewModels in widgets

### ISSUE THREAD

**Issue by Schrank** [magento/magento2#21099]
### Description (*)
Make it possible to add viewModel(s) to widgets

### Expected behavior (*)
`widget` node in `widget.xml` allows `arguments` as in layout xml.

### Benefits
You can easily add viewModels (and other dependencies) to widgets and can easily use composition over adding all the code to the widget.

**Comment by magento-engcom-team** [comment]
Hi @Schrank. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Schrank do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Schrank** [comment]
https://blog.fabian-blechschmidt.de/adding-viewmodels-to-widgets/
