### ISSUE TITLE
Customer Image Attribute

### ISSUE THREAD

**Issue by pbmage** [magento/magento2#21103]
### Preconditions (*)

1.  Add new customer image attribute programmatically.  (Magento Version 2.3.0 Latest)
2.  Custom image attribute display fine in customer admin form.
3.  When we try to add image of customer when adding customer it is throw a exception. 

### Steps to reproduce (*)

1. Add new customer image attribute programmatically.
2. Try to add image of customer from admin customer form and it throw a exception.

### Expected result (*)

1. Customer image upload successfully in admin customer form and we ready to save using "Save Customer" button. See like below screenshot.
![image](https://user-images.githubusercontent.com/28181522/52524541-1049e080-2cc4-11e9-96c8-cefd6cc6a0e8.png)

### Actual result (*)

1. Customer image not upload and throw a exception. See like below screenshot.
![image](https://user-images.githubusercontent.com/28181522/52524574-6a4aa600-2cc4-11e9-93a5-ad9b6e96dc8d.png)

**Comment by magento-engcom-team** [comment]
Hi @pbmage. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@pbmage do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pbmage** [comment]
@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @pbmage. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by Nazar65** [comment]
https://github.com/magento/magento2/pull/19988

**Comment by magento-engcom-team** [comment]
Hi @pbmage, here is your [Magento instance](https://i-21103-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21103-2-3-develop.instances.magento-community.engineering/admin](https://i-21103-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pbmage** [comment]
Provided Magento instance has no facility to add custom customer image attribute from admin to check. So can you please check and verify from your end. Thanks!
PS:
I am using my below extension for add custom customer image attribute.
https://marketplace.magento.com/pbmage-attributemanager.html

**Comment by pbmage** [comment]
![52536750 94639d00 2d84 11e9 8a07 685e51f4757f png png image 1366 x 768 pixels scaled 85](https://user-images.githubusercontent.com/28181522/52536841-882c0f80-2d85-11e9-87a5-3aece61110b6.png)

Please see more details...! I can not overwrite this code using Plugin or Preference...! I tried both way but no luck. So i can not make my extension compatible with Magento 2.3 version. Can you please do needful for next release regarding this!

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @pbmage I'm not able to reproduce following steps you described, 
also this is duplicate to this -> https://github.com/magento/magento2/issues/19983
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
