### ISSUE TITLE
Area code not set inside emulateAreaCode when using OrderRepository in CLI

### ISSUE THREAD

**Issue by marcusirgens** [magento/magento2#21109]
### Preconditions (*)

1. Magento 2.3.0 with sample data

### Steps to reproduce (*)

1. Create a console command that fetches an Order by ID inside an emulated area using State::emulateAreaCode

### Expected result (*)

1. The OrderRepository should fetch the provided Order or throw a NoSuchEntityException

### Actual result (*)

1. A LocalizedException is thrown with an "Area code is not set" message.

**Comment by magento-engcom-team** [comment]
Hi @marcusirgens. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@marcusirgens do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by marcusirgens** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @marcusirgens. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @marcusirgens, here is your [Magento instance](https://i-21109-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21109-2-3-0.instances.magento-community.engineering/admin](https://i-21109-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by marcusirgens** [comment]
I didn't know I couldn't install modules on those instances-

I created a [sample module](https://github.com/marcusirgens/module-order-repository-cli-test) that reproduces this issue. Install it with 
```
composer install marcuspi/module-order-repository-cli-test:^0.1
```

The specific code that reproduces the error (with annotations for readability):
```php
protected function execute(
        \Symfony\Component\Console\Input\InputInterface $input, 
        \Symfony\Component\Console\Output\OutputInterface $output
) {
    $orderId = (int) $input->getArgument("entity_id");

    // Emulate adminhtml area code
    /** @var $appState \Magento\Framework\App\State */
    $appState = $this->appState;
    $appState->emulateAreaCode(\Magento\Framework\App\Area::AREA_ADMINHTML, function () use ($output, $orderId) {
        /** @var \Magento\Sales\Api\OrderRepositoryInterface $orderRepository */
        $orderRepository = $this->orderRepositoryFactory->create();
        
        try {
            $order = $orderRepository->get($orderId);
            $output->writeln("Found " . $order->getIncrementId());
        } catch (\Magento\Framework\Exception\NoSuchEntityException $nse) {
            $output->writeln($nse->getMessage());
        }
    });
}
```

**Comment by marcusirgens** [comment]
Aaaaand after X hours of debugging, of course this only happens using magerun2. Closing this issue.
