### ISSUE TITLE
Magento 2.3.0 product image cache resizing images to look very bad

### ISSUE THREAD

**Issue by babybeddingdesign** [magento/magento2#21108]
i have uplpud images to magento 2.3 and when i look on prodact page i can see it been resizing to different size with white lines. look : original images that been upload: https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/d/u/dumbo_bedding_set.jpg the one seen on my site: https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/cache/9d08971813a040f8f96067a40f75c615/d/u/dumbo_bedding_set.jpg

link to the item: https://babybeddingdesign.com/dumbo-crib-bedding-collection-crib-bedding-set

all my products also old ones have been resizing. what is the problem with Magento 2.3?

**Comment by magento-engcom-team** [comment]
Hi @babybeddingdesign. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@babybeddingdesign do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @babybeddingdesign 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by babybeddingdesign** [comment]
you can see this is a core problem as Magento change size of the images! its not a theme problom its Magento problem that need to be fix!

**Comment by ghost** [comment]
@babybeddingdesign so please provide clean steps to reproduce and more detail information.

**Comment by babybeddingdesign** [comment]
Hi,
sorry i am not sure i undersntd what you mean but it very simaple.
i uploud images from admin that looks like that (1024X1024): https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/d/u/dumbo_bedding_set.jpg

very good full images.
and Magento resize it to look like that (1000X1320): https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/cache/9d08971813a040f8f96067a40f75c615/d/u/dumbo_bedding_set.jpg

i have read that its a bug on Magento that need fix. not sure if this is the problom but it look same.

https://github.com/magento/magento2/issues/4622

**Comment by gelanivishal** [comment]
Hello @babybeddingdesign
Can you please upload below image on same product?

![baby](https://user-images.githubusercontent.com/12389799/52551449-95d3aa80-2e02-11e9-8c60-690d629539a8.jpg)

Let me know.

**Comment by babybeddingdesign** [comment]
Hi,
the only image i have upload to Magento from admin to this product: https://babybeddingdesign.com/dumbo-crib-bedding-collection-crib-bedding-set
as you attach (https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/d/u/dumbo_bedding_set.jpg)
magento change it and make it look like this: https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/cache/9d08971813a040f8f96067a40f75c615/d/u/dumbo_bedding_set.jpg

her is more samples:
original : https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/m/i/mickey_mouse_90_years_of_magic_1.jpg
resized: https://babybeddingdesign.r.worldssl.net/pub/media/catalog/product/cache/9d08971813a040f8f96067a40f75c615/m/i/mickey_mouse_90_years_of_magic_1.jpg 

you need to understand all my images have been resizing because Magento have a bug that did it. 
i am not the only one that reports on this problem i see more and more over the internet
