### ISSUE TITLE
Failed to set ini option session.use_only_cookies

### ISSUE THREAD

**Issue by a7medeeuae** [magento/magento2#21111]
Hi

Everyone after I install magento 2.3 on my godady hosting
Showing me this error

There has been an error processing your request
Failed to set ini option session.use_only_cookies to value 1.
Error log record number: 1154399512761

`{"0":"Failed to set ini option session.use_only_cookies to value 1. ","1":"#0 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/Session\/SessionManager.php(181): Magento\\Framework\\Session\\SessionManager->initIniOptions()\n#1 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\Session\\SessionManager->start()\n#2 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Session\\Generic\\Interceptor->___callParent('start', Array)\n#3 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\Session\\Generic\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#4 \/home\/a7med\/public_html\/m2\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(52): Magento\\Framework\\Session\\Generic\\Interceptor->___callPlugins('start', Array, Array)\n#5 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/Session\/SessionManager.php(127): Magento\\Framework\\Session\\Generic\\Interceptor->start()\n#6 \/home\/a7med\/public_html\/m2\/generated\/code\/Magento\/Framework\/Session\/Generic\/Interceptor.php(14): Magento\\Framework\\Session\\SessionManager->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State\\Interceptor))\n#7 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(116): Magento\\Framework\\Session\\Generic\\Interceptor->__construct(Object(Magento\\Framework\\App\\Request\\Http), Object(Magento\\Framework\\Session\\SidResolver\\Proxy), Object(Magento\\Framework\\Session\\Config), Object(Magento\\Framework\\Session\\SaveHandler), Object(Magento\\Framework\\Session\\Validator), Object(Magento\\Framework\\Session\\Storage), Object(Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager), Object(Magento\\Framework\\Stdlib\\Cookie\\CookieMetadataFactory), Object(Magento\\Framework\\App\\State\\Interceptor))\n#8 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#9 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#10 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(160): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#11 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'session', 'Magento\\\\Framewo...')\n#12 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#13 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#14 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#15 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(160): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#16 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'formKey', 'Magento\\\\Framewo...')\n#17 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Framewo...', Array, Array)\n#18 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Framewo...', Array, Array)\n#19 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#20 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(160): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#21 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, 'Magento\\\\Framewo...', NULL, 'formKeyValidato...', 'CsrfRequestVali...')\n#22 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('CsrfRequestVali...', Array, Array)\n#23 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('CsrfRequestVali...', Array, Array)\n#24 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('CsrfRequestVali...')\n#25 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(196): Magento\\Framework\\ObjectManager\\ObjectManager->get('CsrfRequestVali...')\n#26 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(172): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->parseArray(Array)\n#27 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(246): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgument(Array, NULL, NULL, 'validators', 'RequestValidato...')\n#28 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('RequestValidato...', Array, Array)\n#29 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('RequestValidato...', Array, Array)\n#30 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('RequestValidato...')\n#31 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/App\/FrontController.php(71): Magento\\Framework\\ObjectManager\\ObjectManager->get('RequestValidato...')\n#32 \/home\/a7med\/public_html\/m2\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(14): Magento\\Framework\\App\\FrontController->__construct(Object(Magento\\Framework\\App\\RouterList), Object(Magento\\Framework\\App\\Response\\Http\\Interceptor), NULL, NULL, NULL)\n#33 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(116): Magento\\Framework\\App\\FrontController\\Interceptor->__construct(Object(Magento\\Framework\\App\\RouterList), Object(Magento\\Framework\\App\\Response\\Http\\Interceptor), NULL, NULL, NULL)\n#34 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\\\Framewo...', Array)\n#35 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/ObjectManager\/ObjectManager.php(70): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Framewo...')\n#36 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/App\/Http.php(134): Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\\\Framewo...')\n#37 \/home\/a7med\/public_html\/m2\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#38 \/home\/a7med\/public_html\/m2\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#39 \/home\/a7med\/public_html\/m2\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#40 {main}","url":"\/m2\/","script_name":"\/m2\/index.php"}`

Please help

**Comment by magento-engcom-team** [comment]
Hi @a7medeeuae. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@a7medeeuae do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by gelanivishal** [comment]
Hello @a7medeeuae ,

There is look like the server is not stored session, Please follow the below steps and let me know if you still got an issue. 

Find below code in php.ini file 
```
session.save_handler = files
;session.save_path = "/tmp"
```
replace with
```
session.save_handler = files
session.save_path = "var/www/magento2/var/session"

```

Also edit php.env file:
```
'session' =>
     array (
    'save' => 'files',
   ),

```
replace with
```
'session' =>
     array (
    'save' => 'files',
    'save_path' => '/var/www/magento2/var/session',
   ),
```

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @a7medeeuae 
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
