### ISSUE TITLE
Configured products not saving

### ISSUE THREAD

**Issue by vkharlamov** [magento/magento2#21149]
### Preconditions (*)

1. Magento v. 2.2.2, 2.2.6 
2. PHP 7.0.31-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2018 10:00:37) ( NTS )

### Steps to reproduce (*)

1.  Open admin side, Open configurable product edit page with relative product(s) 
2. Clear any required(*) fields and click save button. Got focus on that field(This is a required field.)
3. Set value for fields and save product 
### Expected result (*)

1. Got "You saved the product." message with reloaded page

### Actual result (*)

1. Result after saving page: Warning: `vendor/magento/module-configurable-product/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Configurable.php on line 145 `
[https://i.imgur.com/aJbNTFW.png](https://i.imgur.com/aJbNTFW.png)
2. This happens due post data serializing:
Note: vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/variations.js:409 

--> delete this.source.data['configurable-matrix']
--> delete this.source.data['associated_product_ids']

Well, on first "serializeData()" call data will be lost.
And POST send with no value for a fields:
configurable-matrix-serialized: 
associated_product_ids_serialized:

**Comment by magento-engcom-team** [comment]
Hi @vkharlamov. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vkharlamov do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @vkharlamov thank you for you report this issue has already fixed in 2.2-develop and 2.3-develop branch and will be available on 2.3.1 release
https://github.com/magento/magento2/commit/ea3a8c7a42ad4132f5641de6d47e9b8d7020cdef
