### ISSUE TITLE
Product Import - Create new product with same SKU

### ISSUE THREAD

**Issue by santosh051987** [magento/magento2#21143]
Encountered an issue, still would love to hear from other if this issue really persists or is only replicating on my end.

### Steps to reproduce (*)

1.In System > Import > Entity type (Products) & Import behaviour is Add/Update, while importing products of SKU's which are already in inventory, same products are inserted in database as a new entry where as the stock of the existing item should be updated in the database.
2.In case, while importing a CSV any error occurs still system inserts the data of products into the database.
Magento Version 2.2.2
![screenshot from 2019-02-12 12 24 10](https://user-images.githubusercontent.com/32891360/52617290-561fc800-2ec1-11e9-92f6-ea5e86e4c968.png)

**Comment by magento-engcom-team** [comment]
Hi @santoshsingsys. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@santoshsingsys do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by santosh051987** [comment]
I am able to reproduce the issue on our server with Magento Version 2.2.2, I did not check on vanilla Magento instance.
I will check this issue on vanilla Magento instance.
Thanks

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @santoshsingsys thank you for you report, i'm not able to reproduce following steps you described, this may be related to your custom modules.
