### ISSUE TITLE
Possible wrong implementation of denyPayment()

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#21152]
If you consider the following method `\Magento\Sales\Model\Order\Payment::deny()`, you'll notice the following part:

    if ($isOnline) {
        /** @var \Magento\Payment\Model\Method\AbstractMethod $method */
        $method = $this->getMethodInstance();
        $method->setStore($this->getOrder()->getStoreId());

        $result = $method->denyPayment($this);
    } else {
        $result = (bool)$this->getNotificationResult();
    }

    if ($result) {
        // do some magic

You'll see that `$result` is at one point casted to a boolean, and the otherwise it's the return value of the `denyPayment()`-method. The problem is in `$result = $method->denyPayment($this);`. If you look closer at this method (which is deprecated I know, but it stil exists in the latest codebase), You'll see that it is expected to return a boolean value.

However, if you create a payment method using the abstract adapter (which is the recommended case of implementing payment gateways), you'll see that the return value is the method instance (`\Magento\Payment\Model\Method\Adapter::denyPayment()`):

    public function denyPayment(InfoInterface $payment)
    {
        $this->executeCommand('deny_payment', ['payment' => $payment]);

        return $this;
    }

This will cause the `if ($result)` to always loosly cast to true, since an object is truthy. Isn't this going to cause issues?

### Preconditions

1. Magento 2.3-dev

### Steps to reproduce

No clear steps

### Expected result

Payment Adapter should also return boolean

### Actual result

Payment Adapter returns itself as object

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kanduvisla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by YevSent** [comment]
@kanduvisla , as you mentioned, this implementation depends on deprecated `AbstractMethod`, there are still payment integrations which based on `AbstractMethod` and we should still support the old return type.

I don't think that is an issue for the payment integrations based on `Adapter` because of a result processing and entities modifications (like payment or order) are performed in command execution.

The current logic of `\Magento\Sales\Model\Order\Payment::deny` not fully correct (depends on the implementation of `AbstractMethod`) and should catch exceptions but not rely on a result.

As `AbstractMethod` will be removed, we can refactor existing code.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98294`, `MAGETWO-98295` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24309` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
