### ISSUE TITLE
Problem in creating as well as setting attributes

### ISSUE THREAD

**Issue by Abdullah-Mza** [magento/magento2#21183]
### Preconditions (*)

1. Magento version (example: 2.1.15)

### Steps to reproduce (*)

1. Create Product
2. Add attributes to product
3. Try to Set Attribute Values

1. Edit product attributes.
2. Save

### Expected result (*)

1. To work properly And set attributes

1. Save without error

### Actual result (*)

1. Uncaught TypeError: Cannot create property 'chosenOptions' on string '<'
   and page gets stuck on reloading.
https://mockupr.com/mu/uwaq9110

1. Fatal error: Uncaught Error: Call to a member function unserialize() on null
https://mockupr.com/mu/puok2652

**Comment by magento-engcom-team** [comment]
Hi @Abdullah-Mza. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Abdullah-Mza do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Abdullah-Mza** [comment]
> Hi @Abdullah-Mza. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [✓ ]  Summary of the issue
> * [✓ ]  Information on your environment
> * [ ✓]  Steps to reproduce
> * [ ✓]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @Abdullah-Mza do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no

**Comment by magento-engcom-team** [comment]
Hi @Abdullah-Mza. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Abdullah-Mza, here is your [Magento instance](https://i-21183-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21183-2-3-develop.instances.magento-community.engineering/admin](https://i-21183-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Abdullah-Mza i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.

**Comment by Abdullah-Mza** [comment]
theme is built for that version, can't do anything about the version, using Claue theme
