### ISSUE TITLE
Can't view products list in admin

### ISSUE THREAD

**Issue by Pekkonen** [magento/magento2#21185]
### Preconditions (*)
1. Magento 2.3.0.
2. PHP 7.2.14
3. MySQL - 5.6.43

### Steps to reproduce (*)

1. I have about 6700 products on site (migrated from Magento 1.9 with Migration Tool)
2. When I open Catalog - Products I see list of products
3. I need sort products by descending ID and click to "ID header"

### Expected result (*)
1. Standard product list

### Actual result (*)
1. I see an error http://easycaptures.com/fs/uploaded/1144/6116459710.jpg "Attention. Something went wrong." and "Something went wrong with processing the default view and we have restored the filter to its original state."
2. If I click to "OK" I still see infinite loader, can't change sorting for products or change filter settings because this area is inactive - http://easycaptures.com/fs/uploaded/1144/1345750737.png
3. Now I can't view products and can't change any settings, e.g. sort by name etc.
4. Magento logs is clean

**Comment by magento-engcom-team** [comment]
Hi @Pekkonen. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Pekkonen do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Pekkonen     thank you for your report,  problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by Pekkonen** [comment]
Hi @engcom-backlog-nazar!
I'm not sure problem with Migration tool!
Now I can't view any products in admin and don't reset sorting settings!
Everything was fine - I can see products, and manipulate it as I need. Before I click to "ID header".
Anyway - I think problems in admin interface on M2.3 is exist and this situation with infinite loader is abnormal

**Comment by ghost** [comment]
@Pekkonen this also may be related to some custom modules, on clean magento 2.3.0 i'm not able to reproduce this. So this problem maybe in migration tool or custom modules.

**Comment by Pekkonen** [comment]
> @Pekkonen this also may be related to some custom modules, on clean magento 2.3.0 i'm not able to reproduce this. So this problem maybe in migration tool or custom modules.
Yes, it's possible...
Now I have clean M2.3 instance without custom modules, and I could import all products to this shop. 
But it's will be not clear test, because products was migrated from Magento 1.9
BTW - how many products do you have on your test site?

**Comment by ghost** [comment]
@Pekkonen I'm generate product with magento tool  `600000`

**Comment by Pekkonen** [comment]
> @Pekkonen I'm generate product with magento tool `600000`

Hmmm. That should be enough.
Thanks, I will report to migration tool repository!
NB!
**Now I successfully reset this sorting to default, see product list in backend and removed loader after I clear table 'ui_bookmark' in database.** 
Another one click to "ID header" returned this problem again

**Comment by ndianabasi** [comment]
I'm having this issues on Magento 2.3.1. If I reset the bookmarks in the ui_bookmark table, the product list will appear but any filter query will return the problem.
