### ISSUE TITLE
Magento 2.2.7 and above - missing theme path  for part of js files after clean install

### ISSUE THREAD

**Issue by Dieudon** [magento/magento2#21186]
Magento 2.2.7 and above

############# Environment #############
Windows10
Wampserver: 3.1.0
Apache: 2.4.27
PHP: 7.1
Mysql: 5.7.19

############# Issue description #############
When I do a clean install of Magento 2.2.7 or above some of the core js files are not given a 404 because the them path is missing in the URL. This is for both frontend and backend.
examples
- http://domain.name/mage/bootstrap.js
- http://domain.name/jquery.js
- http://domain.name/mage/translate-inline.js

- Frontend only show header with text "Default welcome msg! " and footer show only block "footer links" 
- Backend shows grey page without anything on it (no login form)

Other files like css are working correct and are using the theme path in the URL.
If I install any version below 2.2.7 everything is working just fine.

############# Steps to reproduce #############
1. Install a clean Magento 2.2.7 or above
2. Aftyer install open website in browser

 ############# Expected result #############
All static files being loaded with theme path in the URL
- http://domain.name/pub/static/frontend/Magento/luma/en_US/mage/bootstrap.js
- http://domain.name/pub/static/frontend/Magento/luma/en_US/jquery.js
- http://domain.name/pub/static/frontend/Magento/luma/en_US/mage/translate-inline.js

 ############# Actual result  ############# 
Some static files being loaded without theme path in the URL
- http://domain.name/mage/bootstrap.js
- http://domain.name/jquery.js
- http://domain.name/mage/translate-inline.js

**Comment by magento-engcom-team** [comment]
Hi @Dieudon. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Dieudon do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
`@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21186-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21186-2-2-develop.instances.magento-community.engineering/admin](https://i-21186-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @Dieudon thank you for you report, i'm not able to reproduce following steps you described, this may be related to your environment.

**Comment by Dieudon** [comment]
I dont understand this is related to my environment.
As I have described all versions work on the same environment except from 2.2.7 and above.
Has there been any changes to the requirements since this version?

And I dont understand it happens for certain files (see attached screenshot)
![404_errors](https://user-images.githubusercontent.com/3502039/52715636-35c53b80-2f9d-11e9-8329-c676441343f0.JPG)

It is with every installation the same files!

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.7 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2.7 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21186-2-2-7.instances.magento-community.engineering).
Admin access: [https://i-21186-2-2-7.instances.magento-community.engineering/admin](https://i-21186-2-2-7.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by clark-97** [comment]
@Dieudon I got the same error with 2.3 version
