### ISSUE TITLE
backend and frontend Css and JS not loading on fresh magento 2.3

### ISSUE THREAD

**Issue by Sharlyll** [magento/magento2#21188]
Hi,

**### Preconditions (*)**

1. Magento version 2.3
2. server: Php 7.1

**### Steps to reproduce (*)**

1. Download Magento2.3 from magento site
2. upload zip on live server and install following magento install instructions

**### Expected result (*)**

1. beautiful luma theme on magento2.3 site
2. No errors

**### Actual result (*)**

1.  css and js not loading on frontend and backend
see image
![screenshot 2019-02-13](https://user-images.githubusercontent.com/22851271/52712077-3dd0ab80-2f9c-11e9-8754-dfbd6d171dfa.png)

**Solutions I have tried**
ran these on command line

find . -type f -exec chmod 644 {} \; 
 find . -type d -exec chmod 755 {} \; 
 find ./generated -type d -exec chmod 777 {} \; 
 find ./pub/media -type d -exec chmod 777 {} \; 
 find ./pub/static -type d -exec chmod 777 {} \; 
 chmod 777 ./app/etc 
 chmod 644 ./app/etc/*.xml

still not working. Please help?
![screenshot 2019-02-13 at 14 35 20](https://user-images.githubusercontent.com/22851271/52712226-9bfd8e80-2f9c-11e9-9d73-b525334f44c6.png)

thanks.

**Comment by magento-engcom-team** [comment]
Hi @Sharlyll. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Sharlyll do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21188-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21188-2-3-0.instances.magento-community.engineering/admin](https://i-21188-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @Sharlyll thank you for you report i'm not able to reproduce following steps you described.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
