### ISSUE TITLE
Types not merged for etc/di.xml etc/adminhtml/di.xml

### ISSUE THREAD

**Issue by theodorhanu** [magento/magento2#21193]
### Preconditions (*)
1. Magento 2.3

### Steps to reproduce (*)
1. Create a custom listing in custom module which adds a new collection data source to Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory in etc/adminhtml/di.xml
```
<type name="Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory"> 
   <arguments>
      <argument name="collections" xsi:type="array">
         <!-- add virtual type as custom listing source -->
         <item name="custom_listing_data_source" xsi:type="string">Vendor\CustomModule\Model\ResourceModel\Grid\Collection</item>
      </argument>
   </arguments>
</type>
```

### Expected result (*)
1. Add custom collection among others defined in etc/di.xml, for example sales_order_grid_data_source

### Actual result (*)
1. Other custom collections added to Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory (located in etc/di.xml) are ignored. This results in broken admin grids -> sales/* grids

**Comment by magento-engcom-team** [comment]
Hi @theodorhanu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@theodorhanu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by theodorhanu** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @theodorhanu. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @theodorhanu, here is your [Magento instance](https://i-21193-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21193-2-3-develop.instances.magento-community.engineering/admin](https://i-21193-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by theodorhanu** [comment]
The problem seems to reside in vendor/magento/framework/App/ObjectManager/ConfigLoader.php in load method:
```
public function load($area)
    {
        $cacheId = $area . '::DiConfig';
        $data = $this->_cache->load($cacheId);

        if (!$data) {
            $data = $this->_getReader()->read($area);
            $this->_cache->save($this->getSerializer()->serialize($data), $cacheId);
        } else {
            $data = $this->getSerializer()->unserialize($data);
        }

        return $data;
    }
```
The problem is with this line: ` $data = $this->_getReader()->read($area);`
 When accessing admin area, $area variable is set to 'adminhtml', thus, the configLoader only takes into account di.xml's found in etc/adminhtml. 
Logically for me would be to merge config values with those found in global scope, something like this
```
$globalData = $this->_getReader()->read('global');
$data = array_merge_recursive($globalData, $this->_getReader()->read($area));
```

**Comment by ghost** [comment]
Hi @theodorhanu thank you for you report, can you please explain actual result.
![deepinscreenshot_select-area_20190214111939](https://user-images.githubusercontent.com/40756439/52776677-cdcd2e80-304a-11e9-9f92-661af384b0e8.png)
![deepinscreenshot_select-area_20190214112138](https://user-images.githubusercontent.com/40756439/52776679-cdcd2e80-304a-11e9-9a0d-efe79e1d8c52.png)

**Comment by theodorhanu** [comment]
Hi @engcom-backlog-nazar. Thanks for checking the issue.
If the ...CollectionFactory's  additional collection script is placed in etc/adminhtml/di.xml( see steps to reproduce from my first comment), other grids will be broken and page will display "Not registered handle [collection_data_source handle]". Eg: Not registered handle cms_block_listing_data_source

Please see this stackoverflow thread: https://stackoverflow.com/questions/39763550/magento-2-1-1-admin-content-pages-not-loading-handle-not-registered

**Comment by ghost** [comment]
@theodorhanu Thanks i'm was  not see that di.xml must be in adminhtml

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98272`, `MAGETWO-98273` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Nazar65** [comment]
@Nazar65 test

**Comment by Nazar65** [comment]
@Nazar65 test

**Comment by Nazar65** [comment]
HI @theodorhanu your issue fixed in this PR -> https://github.com/magento/magento2/pull/20891

**Comment by theodorhanu** [comment]
Hi @Nazar65 

Thanks for the update.
Is there any chance that you can provide/know an estimate release date for a magento 2.3.(1?) version, which includes these fixes?

**Comment by Nazar65** [comment]
@theodorhanu on 2.3.2 release

**Comment by MaksymGrom** [comment]
#kharkivcd19

**Comment by magento-engcom-team** [comment]
@MaksymGrom thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @MaksymGrom. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by korostii** [comment]
Hi @magento-engcom-team , considering that both #20891 and #21796 pull requests got closed, is there an acceptable approach to tackling this issue in 2.3, at all?

Or perhaps this is just something that should be done in 2.4 as a breaking change?

**Comment by MaksymGrom** [comment]
Hi @korostii, I recomend you to replace \ before className in all di.xml. Script take both with \ and without \ as separate nodes. So you should follow magento way and avoid \

«type name="\Magento\Cms\Block\Block" >must be replaced on «type name="Magento\Cms\Block\Block"/>

**Comment by AleksLi** [comment]
I found the exact line where the config of Global DI.xml would be overridden by the local di.xml file.

lib/internal/Magento/Framework/ObjectManager/Config/Config.php:248 _mergeConfiguration method. Replacing the old configuration with the new one.

**Comment by tufahu** [comment]
https://github.com/magento/magento2/pull/21796 already closed here.

**Comment by sivaschenko** [comment]
Closing as a duplicate to https://github.com/magento/magento2/issues/26433 (that is already getting processed)
