### ISSUE TITLE
appendTimeIfNeeded supplies wrong datetime format on 2.3 php7.1, cannot set product new from/to dates

### ISSUE THREAD

**Issue by goivvy** [magento/magento2#21209]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1.26

### Steps to reproduce (*)

1. Open up any product edit page in admin
2. Set Product as New From / To dates
3. Click on Save

### Expected result (*)

1. Product is saved correctly

### Actual result (*)

1. An error is displayed 'Invalid input datetime format of value'

This is clearly a bug (at least for my php version).

It was introduced in 2.3.0 when someone made this change:

vendor/magento/framework/Stdlib/DateTime/Timezone.php:

```
@@ -355,15 +332,16 @@ class Timezone implements TimezoneInterface
-    private function appendTimeIfNeeded(string $date) : string
+    private function appendTimeIfNeeded($date, $includeTime)
     {
-        if (!preg_match('/\d{1,2}:\d{2}/', $date)) {
-            $date .= " 00:00";
+        if ($includeTime && !preg_match('/\d{1}:\d{2}/', $date)) {
+            $date .= " 0:00am";
         }
         return $date;
     }

```

Now DateTime gets a string like '01/01/2018 00:00am' and it doesn't like it.

A fix that I'm using right now:

```
-            $date .= " 0:00am";
+            $date .= " 0:00 AM";

```

It's a major bug for my client as she's using new products a lot.

**UPDATE**: upon further investigation it seems this bug is **specific to my php version 7.1.26**.
When I try to run the following test.php file:

```
try{
$new = new \DateTime('01/01/2018 00:00am');
}catch(\Exception $e){die($e->getMessage());}
echo 'ok';
```

I get:

DateTime::__construct(): Failed to parse time string (01/01/2018 00:00am) at position 16 (a): The timezone could not be found in the database

**Comment by magento-engcom-team** [comment]
Hi @goivvy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@goivvy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by goivvy** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @goivvy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @goivvy, here is your [Magento instance](https://i-21209-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21209-2-3-develop.instances.magento-community.engineering/admin](https://i-21209-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by goivvy** [comment]
Well, I cannot replicate it on your system but I can sure replicate it on my system.

**Comment by adarshkhatri** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by adarshkhatri** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri, here is your [Magento instance](https://i-21209-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21209-2-3-0.instances.magento-community.engineering/admin](https://i-21209-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @goivvy thank you for you report i'm not able to reproduce following steps you described, did you change the datepicker to use hours ?

**Comment by goivvy** [comment]
Why did you close it? The issue is reproduced if you use php 7.1.26

**Comment by ghost** [comment]
@goivvy I have the same version php and issue not appear
![deepinscreenshot_select-area_20190215095153](https://user-images.githubusercontent.com/40756439/52842303-590bfa00-3107-11e9-81f1-42d3b9f09e7f.png)

**Comment by ghost** [comment]
Seeing this issue on v2.3.1. 

PHP Version:
PHP 7.1.28 (cli) (built: Apr  8 2019 17:57:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
