### ISSUE TITLE
Different behaviour between grunt and setup:static-content:deploy

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#21205]
### Summary (*)

I expect that when the grunt asset compilation succeeds without errors that setup:static-content:deploy will work with identical results. This doesn't seem to be the case.

### Examples (*)

I have a custom theme. that defines custom variables in: `app/design/frontend/vendor/theme/web/css/source/_custom-variables.less`

the file is imported via `@import "_custom-variables.less";` in theme.less

I use the variables there in the theme less and in the less of regular modules of the same vendor.

When compiling the assets with less everything works as expected.

When compiling the assets with setup:static-content:deploy the compilation fails with:

```
Compilation from source: /data/src/m2/vendor/magento/theme-frontend-blank/web/css/styles-l.less                                   
variable @color-highlight is undefined in file /data/src/m2/var/view_preprocessed/pub/static/frontend/Magento/blank/en_US/Ac_Megamenu/css/source/_module.less in _module.less on line 8, column 16 
06|       color: @color-white;                                   
07|       &:hover {                                              
08|         color: @color-highlight;                             
09|       }                                                      
10|     }                                                        
11|     h3 { in _responsive.less 
```
### Proposed solution

Both asset compilation processes should have the same result.

**Comment by magento-engcom-team** [comment]
Hi @MichaelThessel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MichaelThessel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @MichaelThessel thank you for you report i'm not able to reproduce following steps you described.
![deepinscreenshot_select-area_20190214153817](https://user-images.githubusercontent.com/40756439/52790216-b30cb100-306e-11e9-8404-f48d0d8589af.png)
![deepinscreenshot_select-area_20190214153831](https://user-images.githubusercontent.com/40756439/52790217-b3a54780-306e-11e9-952e-f54a311faf13.png)
![deepinscreenshot_select-area_20190214153844](https://user-images.githubusercontent.com/40756439/52790218-b3a54780-306e-11e9-8654-038fd2f4f39e.png)

**Comment by hostep** [comment]
@MichaelThessel: you shouldn't use custom less variables defined in a theme directly in a module itself (in `app/code/Ac/Megamenu` or `vendor/ac/megamenu`), because you are creating an incorrect dependency. A module doesn't know if a particular theme exists so it shouldn't rely on less variables from a specific theme.
You should create a module directory in your theme itself (`app/design/frontend/{Vendor}/j{theme}/Ac_Megamenu`) which uses those custom variables from your theme.

In theory it will work when only compiling your theme, but if you compile other themes like the built-in `Magento/blank` or `Magento/luma` themes it will break which is expected.

Hope this helps :)

**Comment by MichaelThessel** [comment]
@hostep, thanks, that totally makes sense now. Much appreciated!
