### ISSUE TITLE
Static content not generated, only generated file is requirejs-config.js

### ISSUE THREAD

**Issue by Cristy94** [magento/magento2#21201]
### Preconditions (*)

1. PHP Version 7.1
2. Magento CE 2.3.0
3. Installed on a shared server, only have cPanel access, no shell

### Steps to reproduce (*)

1. Fresh installation of Magento 2.3.0
2. Installation is successful, but when I access the frontend no CSS is loaded:

### Expected result (*)

1. I expect the store to properly load CSS, which is requested (but missing) from the static folder.

### Actual result (*)

1. Only HTML is loaded, the only file generated in pub/static/Magento/luma/locale is requirejs-config.js
![image](https://user-images.githubusercontent.com/1384885/52742075-3ed2fe80-2fd7-11e9-8f59-5ece850ced59.png)

![image](https://user-images.githubusercontent.com/1384885/52742068-37abf080-2fd7-11e9-99ce-efc55cb1b8a4.png)

I have tried to somehow trigger the static content generation as explained [here](https://magento.stackexchange.com/questions/125064/how-to-install-module-magento-2-dont-need-run-command-line-bin-magento-setupup/125090#125090), but it didn't seem to do anything.

I also tried reinstalling the store from scratch, same result. I don't think there is a permissions issue as the requirejs-config file can be copied there, so there are write permissions.

**Comment by magento-engcom-team** [comment]
Hi @Cristy94. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Cristy94 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Cristy94 thank you for you report,
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by Cristy94** [comment]
How is this not a core issue? A fresh installation does not work while the installer passes all checks and says installation was successful. Why does it say everything is ok if it is clearly not?

**Comment by ghost** [comment]
@Cristy94 But why many people can install without this errors ?

**Comment by Cristy94** [comment]
@engcom-backlog-nazar That's how bugs work, right? It's like saying, if 2 planes crash but 998 are fine, then there is no problem, **as the majority are fine**.

It's clearly an issue when a locale is used, there are many people having this issue (just first results from some google searches):
https://magento.stackexchange.com/questions/219268/setupstatic-contentdeploy-issue-with-locale
https://stackoverflow.com/questions/34040496/magento-2-not-loading-css-and-javascript/45114847
https://magento.stackexchange.com/questions/212514/refused-to-apply-style-because-its-mime-type-text-html-is-not-a-supported-s
https://community.magento.com/t5/Magento-2-x-Technical-Issues/Refused-to-apply-style-quot-because-its-MIME-type-text-html-is/td-p/86721/page/2

There were also a few blog posts about it, but can't find them at the moment.

I understand there might be some server specifications issues, but the biggest question is why it only generates some files (the requirejs file, it can create the required folders etc) and why it says it's working as expected when it is not.

I don't think the mentality of "the platform is fine because it works for most users" is the way to go for such a big product.

**Comment by ghost** [comment]
@Cristy94 ok i agree with you , but how we can reproduce this ? without reproduce issue we cannot create a PR

**Comment by Cristy94** [comment]
I can 100% reproduce it on my environment. 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @Cristy94. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Cristy94, here is your [Magento instance](https://i-21201-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21201-2-3-develop.instances.magento-community.engineering/admin](https://i-21201-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Cristy94** [comment]
I tried to reproduce it in your Environment, but:

1) When I installed Magento 2 in my case, I selected at installation time the ro_RO locale.
2) When I changed the locale in your environment to ro_RO, the frontend store language (text) was still in English (language doesn't seem to change).

![image](https://user-images.githubusercontent.com/1384885/52877542-9483e400-315a-11e9-8d94-6c1ed370d535.png)


Yet all text on the store is in English (after flushing cache).

![image](https://user-images.githubusercontent.com/1384885/52877578-b3827600-315a-11e9-9fc8-9ffe1b5f4144.png)

**Comment by gitxsun** [comment]
I have exact same issue.   Already wasted one whole days , then saw this post.      My dev is using PHP 7.1 .   but my testing production server is using PHP 7.2.        I suspect that it is a PHP 7.2 and Magento 2.3 bug.

**Comment by Cristy94** [comment]
I have PHP 7.1 on my servver and have this issue, so not sure it is related to the PHP version. Do you also have have your shop in a  locale different than the default one (en_US) ?

**Comment by Cristy94** [comment]
I have fixed my issue by switching from Magento to WooCommerce, the installation was infinitely more pleasant and hassle free and  importing the products from Magento to WooCommerce was quick.

I won't recommend anyone Magento, it's just an old platform with bad support.

**Comment by arslanfarooq** [comment]
I have the same issue. Wasted whole day on it, did fresh install twice. Then came to this from another report that was closed.

If this is your way of nudging people to go for premium version of Magento, it won't work in the long term.  You guys will lose.

**Comment by kmv** [comment]
Sometime it is a hosting settings issue - its try to find "static" folder directly in magento root but not in pub/
To fix it try to make symbol link in magento root directory
$ ln -s pub/static static

**Comment by Nader-GenKO** [comment]
have the same exact issue, first use of Magento. searching for a solution without luck.

**Comment by angelascone** [comment]
Magento CE 2.3.1, PHP 7.2, shared hosting. I replicated the same issue today. In developer mode only one requirejs-config.js was deployed after requesting the homepage. After dozen minutes of useless searching I made "a big job" to get the Apache log from the provider :).
I found: 
_***/pub/static/.htaccess: Option MultiViews not allowed here, referer: ***_
I commented out line (10) **Options -MultiViews** in the file <magento_root>/pub/static/.htaccess and then the static contents have been correctly deployed.
Of course, better way is to allow multiviews overriding within .htaccess files by default but it doesn't have to be always possible on hosting servers.   
Hope it helps anyone.

**Comment by antoinekociuba** [comment]
Hi there, if some people are still in trouble with that issue, simply remove or switch _dev/static/sign_ setting, from _core_config_data_ table, to 0.

It did the trick on my side.

Check https://github.com/magento/magento2/issues/7869 for more details.

**Comment by sanjay-kumar-forevernew** [comment]
atleast give proper docs how to do setup using respective os - mac, ubuntu,windows
