### ISSUE TITLE
Salable Qty=0 still showing on list pages

### ISSUE THREAD

**Issue by farrukhk** [magento/magento2#21218]
Precondition
(1) Magento Commerce 2.3.0
(2) PHP 7.2

Steps to reproduce (*)
(1) Add a product having stock 1
(2) Buy the same product by placing an order.
(3) The order will show in processing and you will notice that product Quantity is shown as 1 while the salable quantity is shown as 0.
(4) In catalog/inventory "Display Out of Stock Products=No

Expected result (*)
(1) Product should be removed from list pages as it is not available for sale. 

Actual result (*)
(1) Product is not removed from list page. It should be removed from list page as it is not available for sale anymore.  
(2) When we click on the product shown on the list page to visit the product detail page, product is shown as out of stock.

**Comment by magento-engcom-team** [comment]
Hi @farrukhk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@farrukhk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @farrukhk thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1` release

**Comment by farrukhk** [comment]
Hi,
Is there a temporary workaround for this?

**Comment by farrukhk** [comment]
Hi,
I just upgraded to 2.3.1 Commerce and I can still see the issue and it is not resolved. Can you confirm if this was fixed in the new release of commerce edition.

**Comment by dbkab** [comment]
hey @farrukhk, any update on the issue you described? I am experiencing the same problem and can't seem to find any solution.

**Comment by farrukhk** [comment]
> hey @farrukhk, any update on the issue you described? I am experiencing the same problem and can't seem to find any solution.

Hi,
No fix for this. They say that this is supposed to be that way only. They do not plan to fix it. We have Commerce Edition and no support so far. Our customers are going crazy as they see out of stock products i.e. salable=0 on list pages.

**Comment by pknap** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pknap. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pknap, here is your [Magento instance](https://i-21218-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21218-2-3-develop.instances.magento-community.engineering/admin](https://i-21218-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by simonrl** [comment]
Why has this issue been closed? Is this fixed in any version? Doesn't look as if it were.

**Comment by khnaim** [comment]
hey @farrukhk, any update on the issue you described?
