### ISSUE TITLE
Magento 2.2.6 - uploading PNG image throws warning

### ISSUE THREAD

**Issue by Mohsin07** [magento/magento2#21217]
### Summary (*)

When I try to upload a PNG image (transparent background) for my custom form I get this warning message. 
**Warning: file_get_contents(): stream does not support seeking in \/var\/www\/html\/RootFolder\/vendor\/magento\/framework\/Image\/Adapter\/Gd2.php on line
294"**
This warning does not occur when I use a JPEG image.

### Examples (*)

The Gd2.php file has the following code on line 294 as per the error report.

    **public function checkAlpha($fileName)
    {
        return (ord(file_get_contents($fileName, false, null, 25, 1)) & 6 & 4) == 4;
    }**

**Comment by magento-engcom-team** [comment]
Hi @Mohsin07. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Mohsin07 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Mohsin07 thank you for you report, 
See file_get_contents(): stream does not support seeking PHP

You are working with a remote file. Seeking is only supported for local files.

You probably need to copy the file to your local file system before using file_get_html. It should work fine on localhost.

**Comment by Mohsin07** [comment]
Hi @engcom-backlog-nazar  thanks for the suggestion.

I face this issue in the production server. It works fine in my testing server and in my local system. If I need to copy the file to the local system, then how come it works for JPEG file formats?
