### ISSUE TITLE
Cannot create shipment: Source item not found by source code: default and sku: sols-imp-adult-t-shirt-Black-Full Colour - position 2

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#21219]
### Preconditions (*)

1. Magento Open Source 2.3
2. Inventory Source Enabled (By default? cannot disable)
3. https://imgur.com/uFZE5Y4

### Steps to reproduce (*)

1. Config product with Custom Options
2. Place order from frontend
3. Create Invoice
4. Create Shipment

### Expected result (*)

1. It should create shipment

### Actual result (*)

1. Source item not found by source code: default and sku: sols-imp-adult-t-shirt-Black-Full Colour - position 2.
2. No shipment created. No logs

**Comment by magento-engcom-team** [comment]
Hi @adarshkhatri. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@adarshkhatri do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by adarshkhatri** [comment]
I checked in Vanilla instance v2.3.0 but couldn't see "inventory source" section. I strongly believe the error is related to this new module.

In vanilla 2.3.0 instance (without "inventory source"), I was able to create shipment.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @adarshkhatri thank you for you report, please open issue here -> https://github.com/magento-engcom/msi
