### ISSUE TITLE
Catalog Product List Widget throws Integrity constraint violation

### ISSUE THREAD

**Issue by tzsolti** [magento/magento2#21222]
### Preconditions (*)

1. Magento 2.3.0 with sample data
2. PHP 7.2.13
3. MySQL 5.7.24
4. CentOS 7 (the same happens also under Windows 10)
5. Nginx 1.15.7

### Steps to reproduce (*)

1. Edit page "Home page" in the backend
2. Insert widget "Catalog Product List", set some title, display page control No, number of products 10, template Products Grid Template (or any other), cache lifetime empty. Do not Save it yet!
3. the most important part comes here, set the following Conditions: "Attribute Set Is" "Downloadable" (or any other attribute set)
4. Save the widget, save the page, clear your cache
5. Load the home page

### Expected result (*)

1. Homepage should show up
2. It should contain a list of products which are in the Downloadable attribute set (or whatever you chose)

### Actual result (*)

1. There has been an error processing your request
2. In the report the following appears:
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'attribute_set_id' in where clause is ambiguous, query was: SELECT DISTINCT  `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `stock_status_index`.`is_salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id='1' AND cat_index.visibility IN(2, 4) AND cat_index.category_id='2'
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.website_id = '1' AND price_index.customer_group_id = 0
 INNER JOIN `catalog_product_entity` AS `product` ON product.entity_id = e.entity_id
 INNER JOIN `inventory_stock_1` AS `stock_status_index` ON product.sku = stock_status_index.sku WHERE (((IFNULL(`attribute_set_id`, 0) = '14') )) AND (stock_status_index.is_salable = 1) LIMIT 10

**Comment by magento-engcom-team** [comment]
Hi @tzsolti. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tzsolti do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by tzsolti** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tzsolti. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by ghost** [comment]
HI @tzsolti thank you for you report this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @tzsolti, here is your [Magento instance](https://i-21222-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21222-2-3-develop.instances.magento-community.engineering/admin](https://i-21222-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tzsolti** [comment]
Thanks. It works indeed with the 2.3-develop version.
