### ISSUE TITLE
Magento backend Cache Management mass action checkbox alignment is not proper.

### ISSUE THREAD

**Issue by mage2pratik** [magento/magento2#21255]
Magento backend Cache Management mass action checkbox alignment is not proper.

### Preconditions (*)

1. Magento 2.3.x
2. Php 7.1.2

### Steps to reproduce (*)

1) Login to admin panel
2) Navigate on System -> Tools (Cache Management)
3) Observe the mass action check-box 

### Expected result (*)

![screenshot2](https://user-images.githubusercontent.com/33807558/52845732-d480a200-312d-11e9-87cb-3956b989c2d3.png)

### Actual result (*)

![screenshot](https://user-images.githubusercontent.com/33807558/52846727-6093c900-3130-11e9-9ea9-1406dc1d9d18.png)

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mage2pratik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-21255-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21255-2-3-develop.instances.magento-community.engineering/admin](https://i-21255-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by ghost** [comment]
HI @mage2pratik please edit screen shot and set red color where issue is present. thank you

**Comment by mage2pratik** [comment]
Hi @engcom-backlog-nazar just updated.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98289` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
The issue has been fixed in scope of #20237.
Thank you!

**Comment by deiserh** [comment]
Now with Magento 2.3.2 and 2.3.3 the checkboxes are moved to the left.

![Selection_290](https://user-images.githubusercontent.com/16748061/70989008-246c2480-20c3-11ea-9fd7-50947d0c35c3.png)
![Selection_291](https://user-images.githubusercontent.com/16748061/70989536-1965c400-20c4-11ea-8c63-894533e2d5c4.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-21255-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-21255-2-4-develop.instances.magento-community.engineering/admin](https://i-21255-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-21255-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-21255-2-4-develop.instances.magento-community.engineering/admin](https://i-21255-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@deiserh It works fine in latest magento instance so no need to open this issue.
That fix will be included in Magento 2.3.4 .
You can review it at #25773
Review the PR #25443

![image](https://user-images.githubusercontent.com/46617848/71056377-17147000-217f-11ea-9e11-7daa8b7fc845.png)

![image](https://user-images.githubusercontent.com/46617848/71056402-24c9f580-217f-11ea-81da-897041778909.png)
