### ISSUE TITLE
magento 2.3 import update product Customizable Options not working

### ISSUE THREAD

**Issue by alen9788** [magento/magento2#21259]
### Preconditions (*)

1. MCE2.3
2. PHP7.2

### Steps to reproduce (*)

1. Export the products by the System>>Export
2. Open the csv file, there are 2 custom options of size&color for the clothes
3. There are several colors such as Green, red. Changed the color Green to DeGreen
4.Save the file and upload it by the System>>Import>> Add/update

### Expected result (*)

There should be still 2 custom options of size&color and the green color become DeGreen

### Actual result (*)

yes, the Green Color become DeGreen, but The old options were still there.
means there are 4 options there, added the 2 options rather than update them.

**Comment by magento-engcom-team** [comment]
Hi @alen9788. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@alen9788 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21259-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21259-2-3-develop.instances.magento-community.engineering/admin](https://i-21259-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @alen9788 thank you for you report, i;m not able to reproduce following steps you described on clean magento 2.3-dev instance
![deepinscreenshot_select-area_20190215120638](https://user-images.githubusercontent.com/40756439/52849659-3800d480-311a-11e9-969d-b8ed93fac550.png)

**Comment by alen9788** [comment]
Thanks for the quick reply.

Please try to reproduce it again. Drop down type is selected.

https://prnt.sc/mlfcfa

After we import , it become this
https://prnt.sc/mlfdoo

If one product is updated normally, please try large , such as 100, 200 products uploaded, probably some working, some not working.

**Comment by ghost** [comment]
@alen9788 Magento  add new row when i change the title but other updates works perfectly
![deepinscreenshot_select-area_20190215122718](https://user-images.githubusercontent.com/40756439/52850833-2c62dd00-311d-11e9-9db8-4202ffbb215d.png)

**Comment by alen9788** [comment]
So what to do if we want to update the "red" to other word such as "DeRed"  ?The option title is still Color

**Comment by ghost** [comment]
@alen9788 but this works as expected see screenshot
![deepinscreenshot_select-area_20190215124358](https://user-images.githubusercontent.com/40756439/52851693-6d5bf100-311f-11e9-82c7-b5c761c2d758.png)

**Comment by ghost** [comment]
@alen9788 if you change Option title, this is the new option so that was magento create new because this option no more Color

**Comment by alen9788** [comment]
yes what we faced is that we did not change the option title, just change the option, but still they are added rather than updated.
https://prnt.sc/mlfdoo

As you see, duplicated Size&Color

**Comment by ghost** [comment]
@alen9788 No in my case i have successfully update Color, can you recheck on vanilla instance ?

**Comment by ghost** [comment]
@alen9788 i'm closing this for now, if you have some additional information please reopen the issue.
