### ISSUE TITLE
Compared items in database have no visitor and no customer ID

### ISSUE THREAD

**Issue by peterjaap** [magento/magento2#21264]
Our client noticed that on a lot of computers (and customers), the Compare Products option showed up in the header;

![image](https://user-images.githubusercontent.com/431360/52851010-4ef0f800-3115-11e9-862a-373da78a54b5.png)

After some searching and [wrong conclusions](https://github.com/magento/magento2/issues/17813#issuecomment-463991314), I found that the culprit was the `catalog_compare_item` table. It contained the exact 4 products I found in the localStorage `recently_compared_product` with a `0` in the `visitor_id` column and a `NULL` in the `customer_id` column; 

![image](https://user-images.githubusercontent.com/431360/52853253-50252380-311b-11e9-881a-069715a21c79.png)

Magento then decides that these products should be shown in the compare products functionality for all clients that do not have a session set yet.

### Preconditions (*)

1. Magento 2.2.7

### Steps to reproduce (*)

1. - Add rows to the `catalog_compare_item` table with a valid product entity ID, `customer_id = NULL` and `visitor_id = 0`.
2. Open the frontend

### Expected result (*)

1. These items should not exist in the database,
2. **Or** if they exist, they should never be added to the compare product functionality on the frontend.

### Actual result (*)

1. They do exist in the database,
2. **And** they appear in the frontend.

A few 'quick fixes' come to mind;
1. Set an extra check on `\Magento\Catalog\Model\Product\Compare\Item::getCustomerId` and `\Magento\Catalog\Model\Product\Compare\Item::getVisitorId` to disallow adding an entry to the table when they are both `0`/`NULL`.
2. Changing the repository to filter out the rows in the database that have `0`/`NULL` set for both columns.

But maybe there's an underlying issue that's the reason why `visitor_id` has a `0` value in the first place?

**Comment by magento-engcom-team** [comment]
Hi @peterjaap. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@peterjaap do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by peterjaap** [comment]
Well here's how to reproduce the bug itself;
- Add rows to the `catalog_compare_item` table with a valid product entity ID, `customer_id = NULL` and `visitor_id = 0`.

I've updated the OP.

**Comment by ghost** [comment]
@peterjaap where they must be appear ? 

> 2\. **Or** if they exist, they should never be added to the compare product functionality on the frontend.

**Comment by peterjaap** [comment]
@engcom-backlog-nazar only when the current customer actively added them to the compare list.

**Comment by ghost** [comment]
@peterjaap just checked and they not appear on frontend, any other case ? maybe you have some module that break session ?

**Comment by ghost** [comment]
@peterjaap My observation when visitor becomes to 0 
1 go to frontend  as guest
2 add to compare product 
3 register Customer 
4 Logout now you have visitor_id =0 but have customer_id 

So if you have some bug with session you may have also customer_id=null

**Comment by ghost** [comment]
Hi @peterjaap i'm closing this for now, as we not have clear steps to reproduce. if you have some additional information please reopen the issue.

**Comment by Sil-B** [comment]
We have the same problem with multiple m2.2.7 shops.

**Comment by tsalumets** [comment]
Also have the same problem on one of our shops. 
Magento ver. 2.2.6

**Comment by tiacocstoe** [comment]
Also experiencing the same thing in one of my magento stores so the problem is real. Somehow entries with visitor_id=0 appears and them shows to all visitors on site. Fix needed. Magento 2.2.8

**Comment by harrigo** [comment]
I can also confirm on 2.2.7 this occurs although not tested on vanilla. Seems that a user adds to compare as a guest creating the record with a null customer_id and a valid visitor_id however somehow the visitor_id gets changed to 0 and shows for every user.

I have managed to reproduce twice by signing in and out adding and removing products however cannot give exact details as when trying to reproduce again to give exact steps I struggled.

**Comment by techtoni** [comment]
Same issue, 2.2.6

**Comment by DinkoIlicic** [comment]
We found a way to reproduce and solve the issue. Magento version 2.2.6

Steps to reproduce:

1. Add rows to the catalog_compare_item table with a valid product entity ID, customer_id = NULL and visitor_id = 0.

2. Every user that comes to the site and did not retrieve an ID will see the item in the compare products page. If he clicks on the compare products link, the item is shown and compare-products data is saved in local storage. The compare products data contains URL "<domain>/catalog/product_compare/index/items/2032/uenc/aHR...", that link will be shown on front page for every user. When you delete the entry in catalog_compare_item and any user that goes to that URL will re-add the product to catalog_compare_item table even if he does not have a visitor and customer ID. 

3. To test point 2. Add `console.log(this.compareProducts());` in vendor/magento/module-catalog/view/frontend/web/js/view/compare-products.js on line 34 after `this.compareProducts = customerData.get('compare-products');` to see the compare product data when you visit /catalog/product_compare/index/

4. catalog/product_compare/index controller checks for items in URL parameters and if any exists, he adds them to catalog_compare_item table even if the visitor and customer ID are null. 

Solution:

1. To prevent this from happening we added check to not allow re-adding products if there is no visitor ID and customer ID 
`if (!$this->_customerVisitor->getId() && !$this->_customerSession->isLoggedIn()) {
            return $this->resultPageFactory->create();
        }`
![visitorcustomercheck](https://user-images.githubusercontent.com/46704048/63577967-ce152c00-c58f-11e9-87ca-3acab8b5c245.png)

2. Additionally, we need to reload compare product data in local storage. Adding `customerData.reload('compare-products', true);` on line 28 before `this.compareProducts = customerData.get('compare-products');` in vendor/magento/module-catalog/view/frontend/web/js/view/compare-products.js 
![reload](https://user-images.githubusercontent.com/46704048/63578109-192f3f00-c590-11e9-8877-dab31ec14c1c.png)

**Comment by AnshuMishra17** [comment]
I can see this issue in Magento 2.3.4.

**Comment by tsalumets** [comment]
This issue was closed ??!! We can also see the issue. Whats the resolution?

**Comment by peterjaap** [comment]
@AnshuMishra17 it looks like nobody found a way to reproduce it without making manual entries.

@tsalumets see https://github.com/magento/magento2/issues/21264#issuecomment-524234603, under 'Solution'

**Comment by Manak** [comment]
I've found a way to reproduce this issue.

<domain>/catalog/product_compare/index/1,2

seems to create the broken entry.

**Comment by aholovan** [comment]
I've got the same problem. It might be due to session expire (for example if catalog page opened for some time).
Related issue: https://github.com/magento/magento2/issues/26911

**Comment by di-ivanov** [comment]
A straight forward way to reproduce the issue is to use the GraphQl mutation `CreateCompareList`
On a clean Magento instance add a new simple product enable it and make it show on FE
Run the graphQl mutation
```
mutation CreateCompareList($productid: [ID]!) {
  createCompareList(input: {products: $productid}) {
    items {
      product {
        uid
        sku
        name
      }
    }
  }
}
```
with variables - your product id:
```
{"productid":[1]}
```

Will result in `catalog_compare_item` entry like this one:

catalog_compare_item
---
| catalog_compare_item_id | visitor_id | customer_id | product_id | store_id | list_id | 
| ---: | ---: | ---: | ---: | ---: | ---: | 
| 1 | 0 | NULL | 1 | 1 | 1 |
