### ISSUE TITLE
No supported version of Elasticsearch will work with Magento 2.x as of 2019-03-11

### ISSUE THREAD

**Issue by geerlingguy** [magento/magento2#21277]
### Description (*)

In https://github.com/magento/magento2/issues/18974, it was reported that Elasticsearch 6.x versions are incompatible with Magento 2, and installations will silently fail the test connection, and you can't index or search Magento data with Elasticsearch 6 or later.

That issue was closed as it was not considered a bug that Magento supported Elasticsearch 2.x and 5.x and didn't work with 6.x.

[Elasticsearch 5.x's End-of-Life date is 2019-03-11](https://www.elastic.co/support/eol) (only a couple weeks away now), and so it will become harder and harder to use Magento with any version of Elasticsearch (especially in cloud environments) after that day arrives.

### Expected behavior (*)

* A supported version of Elasticsearch should be able to be used by Magento 2.x.
* The Magento UI for Elasticsearch allows you to select 'Elasticsearch 5.0+', which _implies_ 6 may work (since it's technically '5.0+'), so it would work with Elasticsearch 6.x.

### Benefits

* People would be able to use Magento 2.x with a modern, supported version of Elasticsearch.
* People would not have to spend many hours trying to figure out how to get Elasticsearch 5 or 2 running when it is not well supported in most cloud environments, and harder to install than the latest/supported version(s).

### Additional information

N/A

**Comment by magento-engcom-team** [comment]
Hi @geerlingguy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@geerlingguy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by geerlingguy** [comment]
@magento-engcom-team - Yes. I'm testing on enterprise but also confirmed with community edition.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi  @geerlingguy    thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by geerlingguy** [comment]
@engcom-backlog-nazar - Thanks, I've opened ticket https://github.com/magento/community-features/issues/141, we'll see if the third time's a charm.
