### ISSUE TITLE
Cannot run catalog price index by tmp table is full

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2#21274]
Product price indexer cannot execute index update. Magento can update indexes by schedule, but if huge entity id differences in same schedule job, product price indexer will be stopped by tmp table size is full. This issue caused by Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\Query\BaseFinalPrice Line 221. "BETWEEN" condition specifies huge amount of rows at once. (For example, "e.entity_id between 100 and 1000000". This will cause really huge size insert SQL, and tmp table size becomes full even if database user can increase tmp table size on its session.) 

### Preconditions (*)

1. Magento 2.2.7 (maybe same in 2.3.x)
2. Prepare 1M simple products 
3. Scheduled Indexer mode

### Steps to reproduce (*)

1. Setup vanilla Magento(2.2.7 or 2.3-develop)
2. Prepare 1M simple products
3. Set all indexer mode into schedule
4. Update small entity id product
5. Update large entity id product (over 100K is good)
6. Run indexer via cron (do not run it via bin/magento)
7. Indexer is stopped by tmp table size is full

### Expected result (*)

1. Indexer can finish

### Actual result (*)

1. Indexer is stopped by tmp table size is full

**Comment by magento-engcom-team** [comment]
Hi @HirokazuNishi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@HirokazuNishi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98304`, `MAGETWO-98305` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
Hi @HirokazuNishi thank you for your report, `Run indexer via cron (do not run it via bin/magento)`
If you run manually php bin/magento cron:run. then indexer works as expected ? it only occurus when indexer runs on shedule ?

**Comment by HirokazuNishi** [comment]
@engcom-backlog-nazar yes, this issue only happened on schedule reindex. Manual reindex from bin/magento can finish without any errors.

**Comment by mohitka** [comment]
Hi @engcom-backlog-nazar @magento-engcom-team @HirokazuNishi 
Is there any update on this issue?

I am also facing the same problem in Magento 2.2.6. I have approx. 1 million products in my Magento Open Source website. If I update the prices of a few products, having IDs on a large difference (like product Ids 10, 5000, 35000, 200000, etc.), Magento takes the Lowest ID and the Highest ID which have the price changed. And based on it, Magento reindexes for all the products in this range.

This is the same case as explained by @HirokazuNishi in the reported issue.

Kindly look into it as soon as possible.

**Comment by gulshankumar** [comment]
Hi All,

Exactly the same issue I also am facing. It takes ages to complete price index update just for a few product updates.

Please keep updated if anyone got any fix to this.

Thanks

**Comment by richardcrichardc** [comment]
Looks like the fix landed in [2.3.3](https://github.com/magento/magento2/commit/10966be289465ebcc39a2f32c3a15ddce4398a37). We were experiencing this issue. Upgrading from 2.2.2 fixed it.

**Comment by okorshenko** [comment]
Looks like fixed by this PR: https://github.com/magento/magento2/pull/22575
Thanks to @mtwegrzycki and @orlangur

**Comment by engcom-Golf** [comment]
Hi @HirokazuNishi the issue has been tested and we can confirm that this already fixed in 2.3-develop branch and available on 2.3.3 release.

The issue has been fixed in https://github.com/magento/magento2/pull/22575 by @mtwegrzycki in 2.3-develop branch
Related commit(s):
 - 1f3f984aef9233c19a566513dcd6f39dfa49b18b
