### ISSUE TITLE
Sitemap generated has wrong url when docroot is changed to pub

### ISSUE THREAD

**Issue by tschirmer** [magento/magento2#21290]
### Preconditions (*)

1. Magento 2.3
2. Apache 2.4
3. PHP 7.1

### Steps to reproduce (*)

1. Setup Apache's docroot directory to Magento's pub dir ( /var/www/html/magento/pub/ ) as per install guide: https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html
2. Goto Backend of magento and generate sitemap under Marketing -> Sitemaps.
3. Create new sitemap
4. Click on url in backend

### Expected result (*)

1. Url produced should reflect actual url (e.g. https://example.com/sitemap.xml)
2. When clicked url should contain sitemap

### Actual result (*)

1. Url produced contains the pub directory when no longer required url (e.g. https://example.com/pub/sitemap.xml)
2. This produces a 404 not found when clicked.

**Comment by magento-engcom-team** [comment]
Hi @tschirmer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tschirmer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by VZeroCool** [comment]
@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VZeroCool, here is your [Magento instance](https://i-21290-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21290-2-3-develop.instances.magento-community.engineering/admin](https://i-21290-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @tschirmer thank you for you report, I'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/5321
