### ISSUE TITLE
Google Analytics isAnonymizedIpActive always true

### ISSUE THREAD

**Issue by apomili** [magento/magento2#21292]
### Preconditions (*)

1 - Magento ver. 2.2.7 (and below, I suppose)
2 - Google Analycs correctly activated and Anonymize Ip turned to off.

### Steps to reproduce (*)
1 - Install and activate GA Debbugger chrome extension 
2 - Open the chrome console and browse the shop

### Expected result (*)
GA set with no ip anon

### Actual result (*)
Running command: ga("set", "anonymizeIp", true)

-----------------------------

The bug seems to be in the file google-analytics.js on the google-analytic module.
On the line 51 the condition is always verified cause config.pageTrackingData.isAnonymizedIpActive is a string

**Comment by magento-engcom-team** [comment]
Hi @apomili. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@apomili do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21292-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21292-2-3-develop.instances.magento-community.engineering/admin](https://i-21292-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @apomili thank you for you report, i'm not able to reproduce following steps you described, on clean magento 2.3-develop instance 
![deepinscreenshot_select-area_20190218164042](https://user-images.githubusercontent.com/40756439/52958090-06973b80-339c-11e9-9f54-a45f6f6ef245.png)
![deepinscreenshot_select-area_20190218164724](https://user-images.githubusercontent.com/40756439/52958514-e4ea8400-339c-11e9-9b11-a581bc120f12.png)

**Comment by apomili** [comment]
The variable in ga.phtml is passed correcty, but  when is checked in the file google-analitycs .js

`            if (config.pageTrackingData.isAnonymizedIpActive) {
                ga('set', 'anonymizeIp', true);
            }`

the condition is always **true**

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Nazar65
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98312`, `MAGETWO-98313` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @apomili. Thank you for your report. 
The issue has been fixed in magento/magento2#21303 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [edb9c6ebbb92fd97d953a4160d6b48e6654af448](https://github.com/magento/magento2/commit/edb9c6ebbb92fd97d953a4160d6b48e6654af448)
 - [1e86f88082360477a56d3beff6fd3d5c877ddaab](https://github.com/magento/magento2/commit/1e86f88082360477a56d3beff6fd3d5c877ddaab)
 - [67ea734015ceab3aa05f740a55e5689450e3f1cd](https://github.com/magento/magento2/commit/67ea734015ceab3aa05f740a55e5689450e3f1cd)

The fix will be available with the upcoming 2.3.2 release.
