### ISSUE TITLE
URL Rewrites are overwritten 

### ISSUE THREAD

**Issue by AnshuMishra17** [magento/magento2#21329]
### Preconditions (*)
I am able to reproduce the issue of the following Magento Open Source version
1. 2.2.6
2. 2.2.7

### Steps to reproduce (*)
1. Add multiple websites, for example I have three websites, each website has its own store and corresponding store view.
![step1](https://user-images.githubusercontent.com/3141554/53007841-1414fa00-345e-11e9-875f-522a811771cf.png)
2. Go to Catalog -> Product -> select any product and edit it.
For example, I have selected product with id 1 (Joust Duffle Bag)
3. From Store view dropdown, select Default Store View.
4. Under the Search Engine Optimization, uncheck the Use Default Value checkbox for URL Key and modifiy the URL key and save the product.
![step4](https://user-images.githubusercontent.com/3141554/53007902-360e7c80-345e-11e9-82ae-6a0be9181c65.png)
5. Now, in Marketing -> URL rewrites, try to find the url rewrite for your selected product and you will able to see your new rewrites.
6. Now, from the product listing page, select the same product as in step 2 and select update attributes from the Actions dropdown.
![step5](https://user-images.githubusercontent.com/3141554/53007921-40307b00-345e-11e9-904e-7feb04150d10.png)
7. Select the website tab and in Add product to websites select any new website and save.
For example, my product was already in main website, so I have selected website 2.
8. Now again go in Marketing -> URL rewrites and try to find all the url rewrites for your product.
You will see the URL rewrites that has been generated in step 4 and step 5 no longer exist and you will only see the latest rewrite that has been generated in step 7.
![step8](https://user-images.githubusercontent.com/3141554/53007948-49b9e300-345e-11e9-8447-dc3929431d2d.png)

### Expected result (*)
URL rewrites for all the websites should exist.

### Actual result (*)
URL rewrites are overwritten.

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@AnshuMishra17 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98330`, `MAGETWO-98331` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your report. 
The issue has been fixed in magento/magento2#21462 by @AnshuMishra17 in 2.3-develop branch
Related commit(s):
 - [7cacec1f4b4abe09d991c79f4e15cb465056b670](https://github.com/magento/magento2/commit/7cacec1f4b4abe09d991c79f4e15cb465056b670)

The fix will be available with the upcoming 2.3.2 release.

**Comment by Ctucker9233** [comment]
@magento-engcom-team Shouldn't this stay open until the the 2.2 backport is merged? This is how a lot of bug fixes get lost.

**Comment by ghost** [comment]
Hi @Ctucker9233 there is a backport PR, -> https://github.com/magento/magento2/pull/21358 

>  If the issue is reproducible on 2.3-develop branch, please, add the label Reproduced on 2.3.x.
> - If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and stop verification process here!
