### ISSUE TITLE
Attribute code is invalid

### ISSUE THREAD

**Issue by matthiashamacher** [magento/magento2#21332]
### Preconditions (*)

1. Magento Version: 2.3.0

### Steps to reproduce (*)

1. Add an attribute with attribute code longer than 31 characters i.e. "farbmuster_blankleder_futterleder"
2. Try to save the attribute

### Expected result (*)

1. The attribute should be saved
2. No errors should be shown

### Actual result (*)

1. An error message is being shown `Attribute code "farbmuster_blankleder_futterleder" is invalid. Please use only letters (a-z), numbers (0-9) or underscore(_) in this field, the first character should be a letter.`
2. The attribute cannot be saved

I debugged the attribute save process and found the following regex which checks the attribute code:
`['pattern' => '/^[a-z\x{600}-\x{6FF}][a-z\x{600}-\x{6FF}_0-9]{0,30}$/u']`
At this point, the validation fails because the attribute code is longer than 30 characters. In the Regex, the attribute code is limited to 31 characters but under the attribute code field, it says `This is used internally. Make sure you don't use spaces or more than 60 symbols.`.

**Comment by magento-engcom-team** [comment]
Hi @matthiashamacher. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@matthiashamacher do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
HI @matthiashamacher thank you for you report, i'm closing this as duplicate to this one -> https://github.com/magento/magento2/issues/20766
