### ISSUE TITLE
URL rewrites removal issue while removing product from website from product edit mass action

### ISSUE THREAD

**Issue by AnshuMishra17** [magento/magento2#21348]
### Preconditions (*)
I am able to reproduce the issue on Magento Open Source 2.2.7

### Steps to reproduce (*)
1. Add multiple websites, for example I have three websites, each website has its own store and corresponding store view.
![step1](https://user-images.githubusercontent.com/3141554/53067636-0feaea00-34fb-11e9-8354-1fcfc1c86408.png)
2. Go to Catalog -> Product -> select any product and edit it.
    For example, I have selected product with id 2 (Strive Shoulder Pack)
3. From Store view dropdown, select Default Store View.
4. Under the Search Engine Optimization, uncheck the Use Default Value checkbox for URL Key and modifiy the URL key and save the product.
![step4](https://user-images.githubusercontent.com/3141554/53067646-1aa57f00-34fb-11e9-8127-a95fdd724f8c.png)
5. For the same product that you have selected in step2, add this product to multiple websites and save.
For example, I have added this product to Main website, website 1 and website 2.
![step5](https://user-images.githubusercontent.com/3141554/53067655-23965080-34fb-11e9-8c21-42c0592fbd34.png)
6. Now, in Marketing -> URL rewrites, try to find the url rewrite for your selected product and you will able to see your new rewrites.
7. Now, from the product listing page, select the same product as in step 2 and select update attributes from the Actions dropdown.
![step7](https://user-images.githubusercontent.com/3141554/53067661-2c872200-34fb-11e9-9155-ca95ebc177ca.png)
8. Select the website tab and in Remove product from websites select any new website and save.
    For example, I have selected website 2.
![step8](https://user-images.githubusercontent.com/3141554/53067667-34df5d00-34fb-11e9-844e-a4f44c87b72f.png)
9. Now again go in Marketing -> URL rewrites and try to find all the url rewrites for your product.
    You will see the URL rewrites for the product for the website that you have selected for removal has been removed. Also the url rewrite for the product for the website that had URL key value at the store level (not the default config value, step 4) has been removed as well.  
![step9](https://user-images.githubusercontent.com/3141554/53067693-50e2fe80-34fb-11e9-93e0-c9aaa492c012.png)

### Expected result (*)
URL rewrites should be removed for the product for the website that has been selected for removal.

### Actual result (*)
URL rewrites for the product for the website that you have selected for removal has been removed. Also the URL rewrite for the product for the website that had URL key value at the store level (not the default config value) has been removed as well.

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@AnshuMishra17 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @AnshuMishra17 thank you for you report i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/21329

**Comment by AnshuMishra17** [comment]
@engcom-backlog-nazar How it is duplicate #21329?
#21329 is while we are adding to a website using mass action.
This one is while we are removing the website using mass action.
These are two different cases.

**Comment by ghost** [comment]
@AnshuMishra17, this problem related to mass action, so just add additional description to your first issue and this also will be fixed.

**Comment by AnshuMishra17** [comment]
@engcom-backlog-nazar I just saw that you have already referenced this issue on #21329. So, I am assuming this will also be considered while working on #21329
