### ISSUE TITLE
Order email sender not working magento 2.3

### ISSUE THREAD

**Issue by miquelmauri** [magento/magento2#21342]
### Preconditions (*)

1. magento version 2.3.0

### Steps to reproduce (*)

1. send order email

### Expected result (*)

1. email sender uses defined sales representative sender name and email

### Actual result (*)

1. host user email used

**Comment by magento-engcom-team** [comment]
Hi @miquelmauri. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@miquelmauri do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by miquelmauri** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @miquelmauri. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @miquelmauri, here is your [Magento instance](https://i-21342-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21342-2-3-develop.instances.magento-community.engineering/admin](https://i-21342-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @miquelmauri thank you for you report, i'm not able to reproduce following steps you described, this may be related to your server configuration.
![deepinscreenshot_select-area_20190220100005](https://user-images.githubusercontent.com/40756439/53075670-6ace1280-34f6-11e9-9732-b2e18783ff8a.png)
![deepinscreenshot_select-area_20190220100631](https://user-images.githubusercontent.com/40756439/53076000-3a3aa880-34f7-11e9-8163-9ce486c6346d.png)

**Comment by miquelmauri** [comment]
No changes to host configuration between 2.2.6 and 2.3.0. I upgraded to 2.3.0 in new folder and if I activate 2.2.6 again, mail sender is working fine...
