### ISSUE TITLE
Publish the composer.json of magento2-base on GitHub

### ISSUE THREAD

**Issue by amenk** [magento/magento2#2134]
I can't seem to find the composer JSON of magento/magento2-base (for example as in http://packages.magento.com/_packages/magento_magento2-base-1.0.0-beta5.zip) in the GitHub repository. Can you please put it somewhere? For example into a new repository...

**Comment by buskamuza** [comment]
Hi @amenk ,
we don't have this file as is, it is generated during publication of the Base package. Do you need it for some specific reason? Is it for https://github.com/m2split ?

**Comment by amenk** [comment]
Yes. But I don't know if I continue with m2split...

**Comment by ihor-sviziev** [comment]
:+1: good idea!

**Comment by alankent** [comment]
Just one note, Magento 2 is going to have newer installation experiences compared to M1. Not all of this experience is available yet. There is going to be a bit of "try to keep things minimal to avoid duplicated/wasted effort" while "listen for real problem areas to make sure we fix them". So while we are very interested in hearing of things to help installation, some we may go slow on because we know the full installation experience is not 100% there yet (not available for external people to actually try).

For example, we want to "encourage" merchants towards a standard installation flow, one where we control the downloads a lot more for security reasons. We would like to keep alternative installation paths minimial to reduce confusion etc, and want to encourage official production site installs via our standard process (get master from our official Composer repo, not from GitHub). One example goal is so we know exactly what code they have installed (none of this "develop" versus "master" versus "beta-132.sub-branch A" stuff). There is also streamlining of security patch installation. So we are purposely trying to encourage the majority of installations via the "one true composer repository" where official releases are made.

GitHub will still be there, and some people may prefer to use that. But we don't want to encourage that to be the norm - it can become risky if they grab the wrong branch. E.g. DB upgardes are only supported between official release levels - not every 'develop' branch commit.

Absolutely interested in hearing where the gaps or pain points are. And I know its a bit frustrating because the full new developer experience is not completely available. (E.g. there is "Component Manager" and "Softare Upgrade" in the installation wizard, but we don't have good stable releases in a repo to truly experiment with an upgrade experience.

**Comment by alankent** [comment]
(Oops! Tried to move curson on ipad and hit close by mistake! Reopened.)

**Comment by amenk** [comment]
The idea of subtree splitting of the GitHub repo evolved, when there was not yet a release and the composer repo was lacking behind. No that there are releases, there is not so much need for this modular GitHub install.

Another nice-to-have is the `--prefer-source` option, which I guess does not work with the composer repo and allows easily to contribute patched during development. But I think it is also okay to work with the full github checkout then. An issue might be the different installation layouts (let's say I want to fix a bug that only appears, when Magento lives in vendor/ - this might not reproducible when working with the `git clone`)
