### ISSUE TITLE
Magento 2.2.7 - Cannot create attribute option via Rest API

### ISSUE THREAD

**Issue by fabianaromagnoli** [magento/magento2#21349]
### Preconditions
1. Magento 2.2.7 (But it was experienced also on 2.2.5)
2.PHP 7.1

### Steps to reproduce
1. Setup a fresh installation of Magento 2.2.7
2. Login to admin
3. Create a new product attribute, with type dropdown (leave all other fields default)
4. Create 2 options for this attribute: one with admin label **0** and the other one with admin label **00**, like this:
![attribute](https://user-images.githubusercontent.com/23638004/53075757-41a98400-34ee-11e9-856e-17cfa5347d05.png)
5. Now, get a token for using rest api, using endpoint integration/admin/token like this:
<img width="1248" alt="curl-login" src="https://user-images.githubusercontent.com/23638004/53075967-c7c5ca80-34ee-11e9-8076-3b597ad9c69e.png">
6. And try to create a new attribute option **000** for this attribute, using endpoint products/attributes/{attribute-name}/options, like this:
<img width="1252" alt="screenshot 2019-02-20 at 09 11 01" src="https://user-images.githubusercontent.com/23638004/53076239-8386fa00-34ef-11e9-87fd-9fb5fffdd1fd.png">

### Expected result
I would expect true as a result, but, as you can see from the last screenshot, I got a false, and the option is not created.

### Actual result
The API returns false. If iI try to add 000 via admin the operation is successful.

**Comment by magento-engcom-team** [comment]
Hi @fabianaromagnoli. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@fabianaromagnoli do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @fabianaromagnoli thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release
![deepinscreenshot_select-area_20190220102242](https://user-images.githubusercontent.com/40756439/53077000-b7ffb380-34f9-11e9-82d0-154d5db701e7.png)
![deepinscreenshot_select-area_20190220102248](https://user-images.githubusercontent.com/40756439/53077001-b7ffb380-34f9-11e9-81f6-9cb064ee12bf.png)

**Comment by fabianaromagnoli** [comment]
Hi, and thanks for your feedback.
Could you please indicate which is the commit that fixes this issue?
Thanks in advance.
