### ISSUE TITLE
Product name not changing in cart and mincart after language switch in Magento 2.2.6

### ISSUE THREAD

**Issue by magentopits** [magento/magento2#21352]
### Preconditions

1. Magento 2.2.6
2. PHP 7.1.9
3. MySQL 5.7.19
4. Ubuntu 16.04.5 LTS

### Steps to reproduce
1. Login to admin.

2. Create a product with names PRODUCT-NAME-ENGLISH and PRODUCT-NAME-GERMAN for languages ENGLISH and GERMAN respectively.

3. Go to front-end and switch language to ENGLISH.

3. Go to the product category page or product detail page and add product to cart.

4. Go to checkout/cart.

5. Switch language to GERMAN.

### Expected result

1. Product name in the cart and mini-cart is changed to PRODUCT-NAME-GERMAN.

### Actual result

1. Product name in the cart and mini-cart is PRODUCT-NAME-ENGLISH. Product name is not changed according to store-view.

**Comment by magento-engcom-team** [comment]
Hi @magentopits. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magentopits do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @magentopits thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.1 release.

**Comment by magentopits** [comment]
Hi,

Is there a patch or commit for this, so that i can apply it in my installation?
