### ISSUE TITLE
Bestsellers collection is using ratingLimit as sql select limit

### ISSUE THREAD

**Issue by zimme** [magento/magento2#21361]
### Summary (*)

1. 2.2.6, but looking in the 2.3-develop branch it seems to have the same bug.

### Examples (*)
[Here](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/ResourceModel/Report/Bestsellers/Collection.php#L136) and [here](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/ResourceModel/Report/Bestsellers/Collection.php#L171) the bestsellers collection is using the `_ratingLimit` for the select statements limit... which is restricting the collection size to 5 as that's the default `_ratingLimit`.
### Proposed solution
I don't know what the best solution is, if it's just removing the limit in the select or get the proper limit from some inherited variable... not familiar enough with magento's internal to know where to find that in this case.

**Comment by magento-engcom-team** [comment]
Hi @zimme. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@zimme do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98374`, `MAGETWO-98375` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by tuyennn** [comment]
@zimme @magento-engcom-team As bestseller collection limit at 5 because of the limitation from **Bestseller Report** from admin-end.
Each period row in the report contains bestseller items which limit at 5. Without the limitation the Grid should be messed up.

**Comment by zimme** [comment]
@tuyennn Interesting, but even so. I would not expect the limiting value coming from `_ratingLimit` which is used to filter out any items that have a lower rating than `5`. If it is supposed to be limited to 5 items by default that value should be in it's own (configurable) variable in my mind.

**Comment by dev-ajaysaini** [comment]
I think there should be a field in admin configuration to set the bestseller limit.

**Comment by missoxd** [comment]
I am working on it. #imagine2019

**Comment by missoxd** [comment]
#imagine2019

**Comment by missoxd** [comment]
#imagine2019

**Comment by magento-engcom-team** [comment]
@missoxd thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by semajeg** [comment]
hey @yuriichayka, from the logs above it looks like you're working on this. Would be worth assigning it to yourself so that others know not to pick it up :)

Also, there was a PR that references this (see https://github.com/magento/magento2/pull/22851) which you could pick up where it was left off,rather than starting from scratch

Hope this helps!

**Comment by yvaliya** [comment]
#imagine2019

**Comment by magento-engcom-team** [comment]
Hi @zimme. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24341` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by sukeshini-kot** [comment]
Is there any update on this?
