### ISSUE TITLE
Possibility to rename frontend and backend session cookie names

### ISSUE THREAD

**Issue by micmeister59** [magento/magento2#2136]
With Magento 1, it's hard to rename the session cookie name ("frontend" and "adminhtml"). It's a constant in controller without the possibility to change names. It would be nice to change that in backoffice.

**Comment by mblarsen** [comment]
+1 with option of scope

**Comment by piotrekkaminski** [comment]
@micmeister59 @mblarsen can you provide some information why it would be useful? What is the use case? Is it security? Is it not conflicting with other tools?

**Comment by misaert** [comment]
It is useful because we have three websites with the same domains. Only the subdomain changes. The websites 1 and 2 (the same magento) have the common cart. It is why we choosed the same domain for cookie domain. The website 3 (an other magento) is different compared to websites 1 and 2 but it has the same domain to keep brand image for client : with the same frontend, we have conflicts.
I thinf it's safe because it's just change session cookie name (http://php.net/manual/en/function.session-name.php).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Possibility-to-rename-frontend-and-backend-session-cookie-names/idi-p/44868).
