### ISSUE TITLE
Fresh 2.2 install, mcrypt_module_open is deprecated

### ISSUE THREAD

**Issue by ghost** [magento/magento2#21379]
M2 v 2.2
PHP 7.1.26

Fresh install via

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.2
```

Inside a Vagrant VM, running Debian Jessie.

After running the following

```
bin/magento setup:install --base-url=http://demo.local --db-host=localhost --db-name=magento --db-user=root --db-password=root --backend-frontname=admin --admin-firstname=John --admin-lastname=Smith --admin-email=john.smith@email.com --admin-user=admin --admin-password=Password123 --use-rewrites=1
```

When I navigate to http://demo.local, I get `An error has happened during application run. See exception log for details. Could not write error message to log. Please use developer mode to see the message.`

So I check the logs (as well as enable developer mode) and I get this

```
Exception: Deprecated Functionality: Function mcrypt_module_open() is deprecated in /var/www/magento2/vendor/magento/framework/Encryption/Crypt.php on line 59 in /var/www/magento2/vendor/magento/framework/App/ErrorHandler.php:61
```

Now, I checked the file, and the line

`$this->_handle = @mcrypt_module_open($cipher, '', $mode, '');`

Why am I seeing the error when the function is prefixed with the @ symbol?

And how do i fix this?

**Comment by magento-engcom-team** [comment]
Hi @paul-gene. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@paul-gene do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @paul-gene thank you for you report, this issue has already fixed in 2.3-develop branch and 2.2-develop branch and will be available on 2.3.1 release and 2.2.8 release

**Comment by ghost** [comment]
@engcom-backlog-nazar so the only current way to fix the issue is to suppress the error?

**Comment by ghost** [comment]
@paul-gene i don't have an error like you have, but this class really deprecated and on develop branches this was fixed, but i'm really not understand why you get this error.

**Comment by ghost** [comment]
@engcom-backlog-nazar How was it fixed on the develop branch / in 2.2.8 ?

**Comment by ghost** [comment]
@paul-gene https://github.com/magento/magento2/issues/5880

**Comment by ghost** [comment]
@engcom-backlog-nazar the link to https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Encryption/Crypt.php#L59 does not work, so i cannot see the solution.

Other than that, there is no mention in that issue on how to fix this other than suppressing the error.
