### ISSUE TITLE
[2.3] CSV Product Import - Import a external URL image

### ISSUE THREAD

**Issue by ankit-sf** [magento/magento2#21387]
### Preconditions (*)
Magento 2.3.x

### Steps to reproduce (*)

1. import csv file with external url in images like https://s3-ap-southeast-1.amazonaws.com/cdn.uvdesk.com/website/1/buddha.jpg

### Expected result (*)

1. Image should be imported just like magento 2.2.4
2. no error/waning should be shown2.

### Actual result (*)

1.<strong>Following Error(s) has been occurred during importing process:</strong><br><div class="import-error-wrapper">Only first 100 errors are displayed here.<div class="import-error-list">1. Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in rows: 1<br></div></div>Import finished. Elapsed time: 3.73s

**Comment by magento-engcom-team** [comment]
Hi @ankit-sf. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ankit-sf do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ankit-sf** [comment]
example csv content:
it's just sample data provided by magento with a image field added


`sku,store_view_code,attribute_set_code,product_type,categories,product_websites,name,description,short_description,weight,product_online,tax_class_name,visibility,price,special_price,special_price_from_date,special_price_to_date,url_key,meta_title,meta_keywords,meta_description,created_at,updated_at,new_from_date,new_to_date,display_product_options_in,map_price,msrp_price,map_enabled,gift_message_available,custom_design,custom_design_from,custom_design_to,custom_layout_update,page_layout,product_options_container,msrp_display_actual_price_type,country_of_manufacture,additional_attributes,qty,out_of_stock_qty,use_config_min_qty,is_qty_decimal,allow_backorders,use_config_backorders,min_cart_qty,use_config_min_sale_qty,max_cart_qty,use_config_max_sale_qty,is_in_stock,notify_on_stock_below,use_config_notify_stock_qty,manage_stock,use_config_manage_stock,use_config_qty_increments,qty_increments,use_config_enable_qty_inc,enable_qty_increments,is_decimal_divided,website_id,deferred_stock_update,use_config_deferred_stock_update,related_skus,crosssell_skus,upsell_skus,hide_from_product_page,custom_options,bundle_price_type,bundle_sku_type,bundle_price_view,bundle_weight_type,bundle_values,associated_skus,additional_images
24-WG085,,Default,simple,"Default Category/Gear,Default Category/Gear/Fitness Equipment",base,Sprite Yoga Strap 6 foot,"<p>The Sprite Yoga Strap is your untiring partner in demanding stretches, holds and alignment routines. The strap's 100% organic cotton fabric is woven tightly to form a soft, textured yet non-slip surface. The plastic clasp buckle is easily adjustable, lightweight and urable under strain.</p><ul><li>100% soft and durable cotton.<li>Plastic cinch buckle is easy to use.<li>Three natural colors made from phthalate and heavy metal free dyes.</ul>",,1,1,Taxable Goods,"Catalog, Search",14,,,,sprite-yoga-strap-6-foot,Meta Title,"meta1, meta2, meta3",meta description,"2015-10-25 03:34:20","2015-10-25 03:34:20",,,Block after Info Column,,,,,,,,,,,Use config,,"has_options=1,quantity_and_stock_status=In Stock,required_options=0",100,0,1,0,0,1,1,0,0,1,1,,1,0,1,1,0,1,0,0,1,0,1,"24-WG087,24-WG086","24-WG087,24-WG086","24-WG087,24-WG086",,"name=Custom Yoga Option,type=drop_down,required=0,price=10.0000,price_type=fixed,sku=,option_title=Gold|name=Custom Yoga Option,type=drop_down,required=0,price=10.0000,price_type=fixed,sku=,option_title=Silver|name=Custom Yoga Option,type=drop_down,required=0,price=10.0000,price_type=fixed,sku=yoga3sku,option_title=Platinum",,,,,,,https://s3-ap-southeast-1.amazonaws.com/cdn.uvdesk.com/website/1/buddha.jpg
`

**Comment by ankit-sf** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ankit-sf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ankit-sf, here is your [Magento instance](https://i-21387-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21387-2-3-develop.instances.magento-community.engineering/admin](https://i-21387-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ankit-sf** [comment]
possible related https://github.com/magento/magento2/pull/20761
but not finding resolved even after making changes in given pull manually for Magento 2.3

**Comment by ankit-sf** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by ankit-sf** [comment]
can't reproduce on 2.3-develop instance but can reproduce on 2.3.0 branch on local

**Comment by ankit-sf** [comment]
what should do in order to update my local and live 2.3.0 to latest version

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ankit-sf thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/2666

**Comment by marco7319** [comment]
Hi
when I import in magento 2.3.2 with a csv in backend, and that I put the url address of google to go to take a picture remotely, via url external, that I put in the cell column base_image, I have an error in the import report :
Imported resource (image) could not be downloaded from external resource due to timeout or access permissions

**Comment by marco7319** [comment]
Hi, i have the same problem, if i want to import in the backend of magento 3.2.3 with a csv file. if i have a url external in a cell in the column base_image .. additional_images ....
Message : Imported resource (image) could not be downloaded from external resource due to timeout or access permissions
THANKS

**Comment by marco7319** [comment]
solution : active allow_url_fopen in the editor ini multi php in the cpanel
