### ISSUE TITLE
Magento FPC get flushed completely when changing category or adding a new product.

### ISSUE THREAD

**Issue by TimQSO** [magento/magento2#21385]
**Preconditions (*)**

1. Magento 2.2.7
2. Redis Cache Enabled
3. Built-In FPC Enabled

**Steps to reproduce (*)**

1. Warm all pages into the cache, for example with a cache warmer
2. Check if pages are warmed on the frontend
3. Optionally check how many Redis keys you have in Database 1 (In my case it will be 23.000+)
4. Add a new product and add the product to a category too
5. Save the product

**Expected result (*)**

1. Check check another, existing product on the frontend, it should still be cached
2. Check one of the other category pages (one you didn't use to assign to your newly added product) on the frontend, it should still be cached
3. Optionally, check the amount of Redis keys in Database 1,  you would expect about the same amount of keys before adding your new product. (In my case it would be about 23.000)

**Actual result (*)**

1. Check check another, existing product on the frontend, this one isn't cached anymore
2. Check one of the other category pages (one you didn't use to assign to your newly added product) on the frontend, this isn't cached anymore
3. Optionally, check the amount of Redis keys in Database 1, you will see that you have far less keys than before the product save. (In my case it will be about 5.000)

**Note.**
The page cache is being flushed to aggressive. Pages that haven't been changed are removed from the cache while this is unneeded. It causes that a site alsmost doesn't server pages from FPC and when you use a cache warmer, this warmer isn't able to keep up on busy e-commerce sites.

When flushing like this, almost every Magento 2 store has an almost empty FPC, which is a bit akward.

**Comment by magento-engcom-team** [comment]
Hi @GuiltyNL. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@GuiltyNL do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TimQSO** [comment]
@magento-engcom-team Yes, this has been reproduced on a vanilla Magento instance.

**Comment by ghost** [comment]
Hi @GuiltyNL thank you for you report, i;m not able to reproduce following steps you described on clean 2.3-develop instance.
![deepin-screen-recorder_select area_20190222113837](https://user-images.githubusercontent.com/40756439/53233678-a3a4ed80-3696-11e9-9a8f-a09d7e619600.gif)

**Comment by TimQSO** [comment]
https://github.com/magento/magento2/issues/13996

https://github.com/magento/magento2/issues/4422

I'm not alone. :)

**Comment by hostep** [comment]
@GuiltyNL: How are your indexers setup, as `Updated by Schedule` or `Update on Save`?

I remember [a talk](https://www.meet-magento.nl/session/stop-flushing-the-magento-cache) from @johnhughes1984 at MM19NL saying there is a bug in Magento when the latter is chosen in that it always flushes the entire cache instead of only flushing the cache specific to a certain product/category.

**Comment by TimQSO** [comment]
Hi @hostep indexers are updated by schedule.

Also the FPC always changes to 'INVALIDATED' after a (short) while.

The cache is also completely flushed after a customer places an order. And sometimes that is every few minutes. So our shop is uncached most of the time.

Our cache warmer tries to keep up and warms about 1.200.000 pages per day because of the constant flushing.

**Comment by vnsinfo** [comment]
Hi GuiltyNL
Did you find a solution to this ?

thanks

**Comment by GuiltyNL** [comment]
Yes, our developers wrote a fix, it has something to do with the anchors in the 'Top Menu' because of that everything was chained together and everything was flushed.

**Comment by vnsinfo** [comment]
Hi There

Thanks for getting back. It would be a great help if you could point me to your developers as we have a similar problem and we are at a total loss about this.

 

Your help is much appreciated.

 

Kind Regards
Hemant

**Comment by luitelbj** [comment]
hi @GuiltyNL, 

I'm facing the same issue, I truly appreciate if you can share the fix.

Thank You
