### ISSUE TITLE
sales_shipment.packages data is broken after sending running sales_send_order_shipment_emails cron job

### ISSUE THREAD

**Issue by isydorenko** [magento/magento2#21390]
### Preconditions (*)

1. Magento 2.3.0
2. `Store > Configration > Sales > Sales Emails > General Settings > Asynchronous sending` is enabled

### Steps to reproduce (*)

1. Place an order
2. Create a shipment for this order
3. Wait for an email sent by sales_send_order_shipment_emails cron job

### Expected result (*)

1. sales_shipment.packages = []
2. Ability to open shipment item page in admin panel

### Actual result (*)

1. sales_shipment.packages = "[]" (quotes added)
2. Error on created shipment item in admin panel

**Comment by magento-engcom-team** [comment]
Hi @isydorenko. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@isydorenko do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by isydorenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @isydorenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @isydorenko, here is your [Magento instance](https://i-21390-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21390-2-3-develop.instances.magento-community.engineering/admin](https://i-21390-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by isydorenko** [comment]
@magento-engcom-team seems it's impossible to reproduce the issue on the provided environment because email haven't been sent by cron.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @isydorenko thank you for you report i'm not able to reproduce following steps you described.
![deepinscreenshot_select-area_20190222101511](https://user-images.githubusercontent.com/40756439/53228793-f5477b00-368a-11e9-8e1b-a77bfd311a18.png)
![deepinscreenshot_select-area_20190222101516](https://user-images.githubusercontent.com/40756439/53228794-f5477b00-368a-11e9-8623-c2a59fcbb42e.png)
![deepinscreenshot_select-area_20190222101709](https://user-images.githubusercontent.com/40756439/53228811-085a4b00-368b-11e9-80ea-fdf421cd6719.png)

**Comment by isydorenko** [comment]
Hi @engcom-backlog-nazar,

Thanks for checking, but for reproducing this issue shipment confirmation email should be sent by  sales_send_order_shipment_emails cron job. In your example even order confirmation email hasn't been sent. 

The problem is that  `\Magento\Sales\Model\EmailSenderHandler::sendEmails()` loads shipment collection, sets email_sent => true and saves a shipment item. However, `\Magento\Sales\Model\ResourceModel\Order\Shipment\Collection` doesn't have unserialize call after load. That means that `\Magento\Sales\Model\EmailSenderHandler::sendEmails()` loads and saved the shipments with packages = [] instead of array(). `\Magento\Framework\Model\ResourceModel\Db\AbstractDb::save()` contains serialization. That means that [] saves as "[]" to the DB.

**Comment by ghost** [comment]
@isydorenko i'm clearly understand and i have also email confirmation and email send by async
![deepinscreenshot_select-area_20190222112145](https://user-images.githubusercontent.com/40756439/53232599-12cd1280-3694-11e9-9d6e-f9b5612fb015.png)
![deepinscreenshot_select-area_20190222112156](https://user-images.githubusercontent.com/40756439/53232600-1365a900-3694-11e9-8514-d7d798e58081.png)

![deepinscreenshot_select-area_20190222112508](https://user-images.githubusercontent.com/40756439/53232776-8838e300-3694-11e9-93fe-fffbe689e603.png)

**Comment by isydorenko** [comment]
@engcom-backlog-nazar oh, the fix is already there https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/ResourceModel/Order/Shipment/Collection.php, but not included to the last stable release. Sorry for taking your time.

**Comment by ghost** [comment]
@isydorenko perfectly :+1:
