### ISSUE TITLE
Magento 2.2.6."No such entity." in admin customer grid. Missing validation when delete website

### ISSUE THREAD

**Issue by hivikas** [magento/magento2#21407]
### Preconditions (*)
 Getting error "No Such entity "on admin customer gird if website id is in double digits.

Version
 Magento version 2.2.6.

### Steps to reproduce (*)
 Create 10 new stores and websites from magento admin and delete all stores and websites. Now create new store and website , new stores and website id's must be in double digits for example 11. 
Or you can reproduce that issue if magento website id is in double digits.
**OR** 
1 - Create Website -> store -> storeview
2. Create customer for this store 
3. Delete Website.

### Expected result (*)
Customer grid load correctly
 All customer data should be shown in admin customers grid.
![image](https://user-images.githubusercontent.com/30468431/53241283-38bfda80-36c7-11e9-9117-cbef663ecc57.png)

### Actual result (*)
Customer grid fail to load -> `The website with id 12 that was requested wasn't found. Verify the website and try again.`
"No such entity." error.
![image](https://user-images.githubusercontent.com/30468431/53241249-2645a100-36c7-11e9-8041-4ba4a861f351.png)
![deepinscreenshot_select-area_20190222151447](https://user-images.githubusercontent.com/40756439/53244812-9d256e80-36b4-11e9-9b9a-86830c6d25bc.png)

**Comment by magento-engcom-team** [comment]
Hi @hivikas. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hivikas do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @hivikas did you delete default store view ?

**Comment by hivikas** [comment]
Hi @engcom-backlog-nazar , No. I deleted other stores.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21407-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21407-2-3-develop.instances.magento-community.engineering/admin](https://i-21407-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
HI @hivikas this is non issue `Deleting a website will not delete the information associated with the website (e.g. categories, products, etc.), but the website will not be able to be restored. It is suggested that you create a database backup before deleting the website.`
