### ISSUE TITLE
[2.3] Database Media Storage not saving media to database

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#21417]
### Preconditions (*)
1. magento 2.3-develop
or
2. magento 2.2-develop

### Steps to reproduce (*)
1. Fresh install
2. Change media storage to database and Synchronise
3. Clear cache
4. Create new product with image

### Expected result (*)
1. Verify that image exists on filesystem
2. Verify that image exists in media_storage_file_storage table

### Actual result (*)
1. File exists on filesystem
2. File does not exist in media_storage_file_storage table

Verified just now on both 2.2-develop and 2.3-develop

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment]
In addition, the same thing happens when setting header logo and favicon images.

**Comment by gwharton** [comment]
Unable to use engcom test instances as need backend database access. Reproduced locally on 2.3-develop and 2.2-develop vanilla installs.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @gwharton  GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by ghost** [comment]
@gwharton https://docs.magento.com/m2/ee/user_guide/system/media-storage-database.html **EE**

**Comment by gwharton** [comment]
This is an open source issue. I followed the instructions you posted and it does not work on community edition.

**Comment by ghost** [comment]
@gwharton how you can configure this on CE version ?

**Comment by ghost** [comment]
@gwharton ok nevermind, i'm just not found that this feature available on ce.

**Comment by ghost** [comment]
@gwharton in my case file exist in database, but image not appear 
![deepinscreenshot_select-area_20190225105410](https://user-images.githubusercontent.com/40756439/53325336-c67c0f80-38eb-11e9-82bb-c0300d732126.png)
![deepinscreenshot_select-area_20190225105506](https://user-images.githubusercontent.com/40756439/53325358-d267d180-38eb-11e9-8205-4f0de5395091.png)

But not exist on file system

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98415`, `MAGETWO-98416` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment]
OK, ive just redeployed both of my 2.2 and 2.3 test instances from scratch in vanilla form to retest this issue.

**2.2-develop** instance created the image in database and processed the image into all cache'd variants, all also in the database. The correct behaviour it would seem.
```
www-data@dev:~/dev1$ php bin/magento catalog:images:resize
1/1 [============================] 100% 1 sec 36.0 MiB  | /t/e/test.png
Product images resized successfully.

```
/pub/media/catalog contains the image and cached variants.
database contains the image and cached variants.

**2.3-develop** instance the image was created in the database, but the cached variants were not created. This leads to the same behaviour you saw above.
```
www-data@dev:~/dev2$ php bin/magento catalog:images:resize
File '/var/www/dev2/pub/media/catalog/product/t/e/test.png' does not exist.

```
/pub/media/catalog is empty
database contains only the main image.

This is still different behaviour to the original bug report though, which I can no longer reproduce.

**Comment by ghost** [comment]
@gwharton updated my 2.2-dev branch and files now located in `catalog/product/cache/e908639258c73f6e87464e14b0d2acd7/d/e` and issue not apear 
but on 2.3-dev path for directory in `tmp/catalog/product/a/b`

**Comment by gwharton** [comment]
When you upload the image it is created with the path tmp/catalog/product/t/e/test.jpg, and when you save the product it is moved to catalog/product/t/e/test.jpg.

So, add the image to the product, database should have /tmp/catalog/product/t/e/test.jpg and then when you save the product, you should get /catalog/product/t/e/test.jpg and all cached variants.

**Comment by gwharton** [comment]
To add to this, it is also broken when you duplicate a product (only tested on 2.2-develop)

Create new product and assign image. Check in database that primary image and cached images exist.

Now "Save and duplicate" the product. The primary image is duplicated in the database, now /catalog/product/t/e/test_1.jpg, but none of the cached variants of the new image are created. This causes the product page to report 0 size and fail to show the newly duplicated products image. If you then save this duplicated product, the cached images are created and everything works as it should from then on.

**Comment by ghost** [comment]
@gwharton upload images to category give me link to image `http://base.url/image.png `on 2.2-develop `http://base.url/pub/media/catalog/category/image.png`  seems like issue must be in "relative path" to files.

And after save category  files moves to `"maedia/category" `and in database still `catalog/tmp/category`

image losts somewhere when we save product or category, if we manually copy image to the path, everything works as expected

**Comment by gwharton** [comment]
Right, I think this original image may have been operator error on my part. I missed a step between 2 and 3 in the original report which was to Save the config after synchronisation.

Thats not to say there arent other issues. I'm going to close this issue and open new one for the real issue I was trying to diagnose, which is what you encountered above.

**Comment by gwharton** [comment]
See #21546 for the reworded issue that covers the above behaviour.
