### ISSUE TITLE
cant create any categories or sub categories: 1. Call to a member function setActive() on boolean in vendor/magento/module-backend/Model/View/Result/Page.php

### ISSUE THREAD

**Issue by nutmix** [magento/magento2#21416]
### Preconditions (*)

1. 2.3.0
2. installed by ISB (TSOHOST) on linux hosting.
3. PHP 7.1

### Steps to reproduce (*)

1. click on "new root category" or "add subcategory".

### Expected result (*)

1. the new category dialog to show.

### Actual result (*)

1. [Screenshots, logs or description]
Fatal error: Uncaught Error: Call to a member function setActive() on boolean in /var/sites/xxx.store/public_html/vendor/magento/module-backend/Model/View/Result/Page.php:27 Stack trace: #0 /var/sites/j/xxx.store/public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Catalog...') #1 /var/sites/j/xxx.store/public_html/vendor/magento/module-catalog/Controller/Adminhtml/Category/Add.php(72): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Catalog...') #2 /var/sites/j/xxx.store/public_html/generated/code/Magento/Catalog/Controller/Adminhtml/Category/Add/Interceptor.php(24): Magento\Catalog\Controller\Adminhtml\Category\Add->execute() #3 /var/sites/j/xxx.store/public_html/vendor/magento/framework/App/Action/Action.php(108): Magento\Catalog\Controller\Adminhtml\Category\Add\Interceptor->execute() #4 /var/sites/j/xxx.store/public_html/vendor/magento/module-backend/App/AbstractAction.php(23 in /var/sites/j/xxx.store/public_html/vendor/magento/module-backend/Model/View/Result/Page.php on line 27

**Comment by magento-engcom-team** [comment]
Hi @nutmix. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nutmix do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nutmix** [comment]
Hi, I dont see the relevance of if I can reproduce on vanila or not.  Its a bug either way. I have installed no plugins or made any code changes.

**Comment by nutmix** [comment]
Hi, how do I confirm these things? I cant edit the form to tick the boxes.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @nutmix thank you for you report, i'm not able to reproduce following steps you described, please provide more information about steps to reproduce.

**Comment by nutmix** [comment]
Thanks for trying.  Basically, I have a virgin install from about 2 weeks ago,I have hadded no plugins or themes, nor touched any php or settings on the server other than using the m2 admin web.  I did try creating a second shop, site and view, which threw an error (as does most operations in m2), but it did it anyway (i.e. created the shop, site and view). Since about then, I cant add any categories or sub categories.  

Can you tell from the source code and line number what the issue might be? Would it be useful if I stuck some debug statements into the php for you? (just send a "change this to this" instruction).
