### ISSUE TITLE
Customer's prefix dropdown option not storing any value

### ISSUE THREAD

**Issue by Ketika** [magento/magento2#21415]
### Preconditions (*)

1. Magento 2.3.0 Open Source

### Steps to reproduce (*)

1. Go to Magento admin side. Stores-> Configuration -> Customers -> Customers Configuration -> Name and Address option
2. Now, select "Show Prefix" option as "Optional/ Required". Also fill values in "Prefix Drop down Option" like "Mr.;Ms;".
3. Click on "Save Config". Now when you come back on this page, then you will realize that Show Prefix is still showing "No" and there is no value in Prefix Drop down Option field.

### Expected result (*)

1. In back-end, value for Show Prefix and Prefix Drop down Option, should populate correctly.
2. It should show the "Name Prefix" option in front end along with drop down values.

### Actual result (*)

1. In back-end, value for Show Prefix is showing as "No".
2. And for Prefix Drop down Option - Not showing anything.
3. It is showing the "Name Prefix" option in frontend. But options are not appearing.

**Comment by magento-engcom-team** [comment]
Hi @Ketika. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Ketika do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by Ketika** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Ketika. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Ketika, here is your [Magento instance](https://i-21415-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21415-2-3-develop.instances.magento-community.engineering/admin](https://i-21415-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Ketika** [comment]
Hi @magento-engcom-team this is working fine on provided vanila Magento instance.

**Comment by ghost** [comment]
Hi @Ketika . Thank you for your report. 
The issue has been fixed in magento/magento2#20896 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [8ff4aa55e320cb9facba7149ca71bca3b5ecebea](https://github.com/magento/magento2/commit/8ff4aa55e320cb9facba7149ca71bca3b5ecebea)
 - [fa72ee7f925963020ec5f5af558abff09fa4795b](https://github.com/magento/magento2/commit/fa72ee7f925963020ec5f5af558abff09fa4795b)

The fix will be available with the upcoming 2.3.2 release.
