### ISSUE TITLE
Fatal error on catalog comparison list page.

### ISSUE THREAD

**Issue by sanjay-github** [magento/magento2#21428]
### Preconditions (*)

1. Magento 2.3
2.

### Steps to reproduce (*)

1.Add two products in comparison list and leave the description field of one of the product empty.
2.Now observe the catalog comparison list.

### Expected result (*)

1. Catalog comparison list should be displayed without breaking even if description not added in a product.
2.

### Actual result (*)

1.Catalog comparison list throws fatal error as given below:
Fatal error: Uncaught TypeError: preg_match() expects parameter 2 to be string, object given in /var/www/html/marinehub/vendor/magento/module-catalog/Helper/Output.php:229
2.

**Comment by magento-engcom-team** [comment]
Hi @sanjay-github. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sanjay-github do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sanjay-github** [comment]
Update: 
Please leave the description field empty of one of the product  before adding product to comparison list.

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-21428-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21428-2-3-develop.instances.magento-community.engineering/admin](https://i-21428-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @sanjay-github thank you for your report, i'm not able to reproduce following steps you described, please provide more information about steps to reproduce. thank you

**Comment by sanjay-github** [comment]
Hi @engcom-backlog-nazar !
Please follow below steps to find the issue :

1. You need to create two or more products from admin panel. While creating products leave the description field empty for one of those products.
2. Once product created , move to storefront and add those products to compare list.
3. Now observe the comparison listing page where all these added products can be seen.

**Comment by manutecon2** [comment]
Hi! 
Same problem here with magento 2.3.
Configurable product with empty short description returns fatal error in product compare page :  
![image](https://user-images.githubusercontent.com/31466237/54042666-f7512400-41ca-11e9-8e97-7937b1ce7280.png)

**Comment by sanjay-github** [comment]
@mvillarejoruiz : 

Exactly, I think the issue should be reopened.

**Comment by manutecon2** [comment]
https://github.com/magento/magento2/commit/0b1983133d48e393388808d0592ccf00d1e540e6 

This commit solves the problem
