### ISSUE TITLE
Bundle Product price is required when dynamic price enabled after data migration from magento1 to magento2

### ISSUE THREAD

**Issue by magentoguyssageone** [magento/magento2#21438]
### Preconditions (*)

1. Install Fresh Magento version 2.2.7
2. Install Data Migration tool 
3. Complete Data Migration from Magento1(Magento versie 1.9.3.2) to Magento2

### Steps to reproduce (*)

1. After Complete Data migration go to Magento2 admin and Edit any migrated bundle product
2. Bunle Product has Dynamic Price set to Yes : http://prntscr.com/mptl6t
3. Try to Save Bundle Product but unable to save becuase Price is Required field for bundle product for my magento2 website. : http://prntscr.com/mptlxk

### Expected result (*)

1. Bundle Product price should not required as Dynamic Price is Yes
2. Bundle Product should Save Successfully without required price error.

### Actual result (*)

1.  Try to Save Bundle Product but unable to save becuase Price is Required field for bundle product for my magento2 website. : http://prntscr.com/mptlxk but it should not required and price filed should disabled.

**Comment by magento-engcom-team** [comment]
Hi @magentoguyssageone. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magentoguyssageone do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magentoguyssageone** [comment]
Hi,

I have already submitted issue according to proper steps so please review my issue.

Thanks

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @magentoguyssageone , problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.

**Comment by magentoguyssageone** [comment]
Hi,

OK I will also report this issue on data-migration-tool repository but I want to make sure its not related to Magento2 also.

Thanks

**Comment by ghost** [comment]
@magentoguyssageone i'm will recheck.

**Comment by MagentoGuysProjects** [comment]
Hi,

this issue is still not solved and waiting for more then 3 months.
https://github.com/magento/data-migration-tool/issues/661

Please check and provide any solution for this.

Thanks
