### ISSUE TITLE
Advance reporting is not working for magento 2?

### ISSUE THREAD

**Issue by Ridik123** [magento/magento2#21449]
I have followed all the steps as per the Magento guideline.

but the advance reporting is still not working any help?
My Magento version is 2.2.5

**Comment by magento-engcom-team** [comment]
Hi @Ridik123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Ridik123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by krishprakash** [comment]
Hi @Ridik123. Thank you for your report.
Can you please explain in proper issue format so we can review as per steps for reproduce.

**Comment by Ridik123** [comment]
I have followed all instruction given on Magento guideline.
URL: https://docs.magento.com/m2/ce/user_guide/reports/advanced-reporting.html
https://nimb.ws/5G31mD
https://nimb.ws/5XiUAr
the andvance reporting status is changed from pending to enabled
https://nimb.ws/mXhLG2

I have reauthorized the analytic user
https://nimb.ws/0rkEPl

waited for 2-3 days but the advance reporting leads to 404 page
https://nimb.ws/KUCAB6

**Comment by Ridik123** [comment]
> Hi @Ridik123. Thank you for your report.
> Can you please explain in proper issue format so we can review as per steps for reproduce.

why are you closing this
