### ISSUE TITLE
Magento swatches fails to deploy

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#21441]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1

### Steps to reproduce (*)

1. Magento 2.3.0 Luma theme
2. php bin/magento setup:static-content:deploy sv_SE -f

### Expected result (*)

No errors in Chrome console.

### Actual result (*)

I had this issue for over a week now. This file refuses to deploy on many occasions and I don't know why. I have not touched it.

Error in chrome console when visiting a product page that does not have swatches:

`Refused to apply style from 'http://demo/static/version1551109164/frontend/Vendor/theme/sv_SE/Magento_Swatches/css/swatches.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Going to the URL results in an error:

`Unable to resolve the source file for 'frontend/Vendor/theme/sv_SE/Magento_Swatches/css/swatches.css'`

Is this issue related to custom languages?

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Zyles do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ananth-iyer** [comment]
@Zyles I think so Yes because it could be returning 404 page

Did you run deploy command for sv_SE language?

> php bin/magento setup:static-content:deploy sv_SE en_US -f

If not then run the above command & check in Private/Incognito Window

**Comment by Zyles** [comment]
> @Zyles I think so Yes because it could be returning 404 page
> 
> Did you run deploy command for sv_SE language?
> 
> > php bin/magento setup:static-content:deploy sv_SE en_US -f
> 
> If not then run the above command & check in Private/Incognito Window

Yes of course.

It deploys all my other stuff, CSS, JS etc.

I use:

```
php bin/magento setup:static-content:deploy -f &&
php bin/magento setup:static-content:deploy sv_SE -f
```

**Comment by Zyles** [comment]
Oh and the JS dir for Magento_Swatches is deployed. But not the CSS.

I can find these files:
```
sv_SE/Magento_Swatches/js/
catalog-add-to-cart.js
configurable-customer-data.js
swatch-renderer.js
```
In category view the swatches in Magento sample data, color size etc. show up. Error only shows on product page with or without swatches on the product.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ananth-iyer** [comment]
* @Zyles Can you open below link? `http://demo/static/frontend/Vendor/theme/sv_SE/Magento_Swatches/css/swatches.css`

**Comment by Zyles** [comment]
> @Zyles
> Can you open below link?
> `http://demo/static/frontend/Vendor/theme/sv_SE/Magento_Swatches/css/swatches.css`

404

**Comment by ananth-iyer** [comment]
@Zyles 
Can you open below link?
http://**{your-magento-base-url-here}**/static/frontend/Magento/luma/sv_SE/Magento_Swatches/css/swatches.css

**Updated**

**Comment by ghost** [comment]
Hi @Zyles thank you for you report, i'm not able to reproduce following steps you described, this may be related to your custom modules or theme,  i'm closing this as this is non issue.

**Comment by vtransy** [comment]
I have custom css file in theme of swatches and get same problem after update from 2.1 to 2.3
I found solution and noted here:
https://mrvts.wordpress.com/2019/08/21/magento-2-3-custom-css-file-not-merged-to-styles-m-css-and-styles-l-css-how-to-fix/

**Comment by kennylawrence** [comment]
FWIW I get this error on a fresh install of M2.3.2 at Nexcess, installed using Composer. I'm in developer mode. Also, I am using the default Luma theme.. nothing custom about the installation except some extensions installed.

**Comment by kennylawrence** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @kennylawrence. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @kennylawrence, here is your [Magento instance](https://i-21441-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-21441-2-3-2.instances.magento-community.engineering/admin](https://i-21441-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ananth-iyer** [comment]
I think this could be file system ownership issue because you are running deploy commands from root user & web server is running on different user that is restricted to read files.

**Comment by redienss** [comment]
Also the same bug on fresh 2.3.3 EE

commit: https://github.com/magento/magento2/commit/f2cd7e548a8960736a1fd6c44b3f77915058d18c
**Swatches styles migrated form CSS file in module to LESS in Blank theme**

Styles was moved from swatches.css to app/design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less

but file is still used in layouts:

module-swatches/view/adminhtml/layout/catalog_product_form.xml
module-swatches/view/adminhtml/layout/catalog_product_attribute_edit.xml
module-swatches/view/adminhtml/layout/catalog_product_attribute_edit_popup.xml

I think this causes problem

**Comment by kennylawrence** [comment]
@ananth-iyer  negative - I am in developer mode (all static resources are created on demand) and swatches.css is the ONLY resource that doesn't get created. I think @redienss may be on to something. Did you install the sample data as well? I had done this in my 2.3.2 install when seeing the issue.

I have just installed a fresh CE 2.3.3 using Composer, WITHOUT sample data, and do not see the swatches.css resource being called.

**Comment by ananth-iyer** [comment]
@kennylawrence Yes, I have installed the sample data as well on Magento 2.3.2. I think swatches.css comes with blank or luma theme.

**Comment by kennylawrence** [comment]
@ananth-iyer it does not appear in the packaged blank and luma themes if sample data was not installed...
In any case, I would hope someone at Magento would care that out of the box, with sample data installed, a fresh installation will result in a 404 network error on the home page for the swatches.css assest.... @engcom-backlog-nazar

**Comment by netwrk-it** [comment]
I see the swatches.css is totally removed from vendor/magento/module-swatches/view/frontend/web/css.
Just added an old one in my theme (and after deploying static content) the error is solved.
