### ISSUE TITLE
Megento Support for php 7.3.4

### ISSUE THREAD

**Issue by estack-co** [magento/magento2#21448]
### Preconditions (*)

I'm Running Magento 2.3-develop branch. As I tried to install magento, I got an error during readiness check saying "Your PHP version is 7.3.2. The required PHP version is ~7.1.3||~7.2.0."

### Actual result (*)

Uploaded the screenshot for reference.
![screenshot 22](https://user-images.githubusercontent.com/45296518/53384368-9e021d00-39a0-11e9-8ab4-a1ac3b2257ba.png)

**Comment by magento-engcom-team** [comment]
Hi @estack-co. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@estack-co do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi  @estack-co    thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features
