### ISSUE TITLE
Cronjob eating CPU for over 5 hours

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#21442]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1

### Steps to reproduce (*)

1. Install Magento 2.3.0
2. Do development for a week
3. Suddenly realize the site is slow and breaking because cronjob is eating 80% CPU
4. Debug for 2 hours
5. Go into SQL table cron_schedule only to find 100+ rows with "get_amazon_capture_updates" with pending status
6. Ask yourself WTF is going on, because you don't even use amazon to begin with.
7. Finding bulk_cleanup queued 100 times on the exact same time
8. Wondering if schedule_id of 486408 is a normal number
9. Truncate table only to be swarmed with new cronjobs

### Expected result (*)

Not crawl the server to a halt with cronjobs.

### Actual result (*)

Spending CPU 80% for multiple hours on end.

Is this normal behaviour?

Look at the image.
![cronjob_magento](https://user-images.githubusercontent.com/1741593/53353103-59d13700-3924-11e9-9ec0-c607cac8903f.PNG)

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Zyles do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Zyles, thank you for you report, for development process this is expected behavior

**Comment by ghost** [comment]
@Zyles  https://github.com/magento/magento2/issues/21380
