### ISSUE TITLE
Javascript is not Minify after Minify that from the backend.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#21463]
From Admin panel go to stores > configuration > Advanced > Developer > javascript > then minify and merge the javascript. but that is not minify 

### Preconditions (*)

1.Magento  V2.3.0 with sample data
2.PHP 7.2

### Steps to reproduce (*)

1. Go to stores > configuration > Advanced > Developer > javascript
2. Set minify and merge javascript to yes. 
3. Clear cache data.
4. Go to the front side and view the page source of any page (in my case I have check product page )
5. Javascript is not properly marge.     
### Expected result (*)

1. [Screenshots, logs or description]
2. After applying configuration, Javascript should be merged properly 

### Actual result (*)

1. [Screenshots, logs or description]
2. After applying configuration, Javascript not merge properly 

![screenshot from 2019-02-26 19-21-56](https://user-images.githubusercontent.com/2203580/53417551-d97e0500-39fb-11e9-809a-8822c65fbacb.png)

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@emiprotech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@emiprotech same as https://github.com/magento/magento2/issues/21413 - expected result is wrong.
