### ISSUE TITLE
Images are not shown on cart page

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#21460]
### Summary
Product image is not displayed on checkout cart page.

### Preconditions (*)

1. Magento ver. 2.3.0
2. Setup multistore with different domains
3. set in .htaccess SetEnvIf conditions for each store / website 
4.  Composer.json part: 
>"require": {
        "geoip2/geoip2": "^2.9",
        "honl/magento2-nl-nl": "^1.1",
        "magento/product-community-edition": "2.3.0",
        "olegkoval/magento2-regenerate-url-rewrites": "^1.4",
        "sisow/plg-magento2": "^5.2"
    },

### Steps to reproduce (*)

1. Add any simple product to cart and proceed to view cart page.

### Expected result (*)

1. Images must be working on cart page since they are correctly displayed on product detail page.
<img width="1258" alt="schermafbeelding 2019-02-26 om 12 20 56" src="https://user-images.githubusercontent.com/37579149/53409345-019c4280-39c1-11e9-8482-2e9efe846d8a.png">

### Actual result (*)

1. Images are not working on cart page. 
<img width="850" alt="schermafbeelding 2019-02-26 om 12 20 02" src="https://user-images.githubusercontent.com/37579149/53409313-e3cedd80-39c0-11e9-98d2-78978eeca787.png">

**Comment by magento-engcom-team** [comment]
Hi @Naberdz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Naberdz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Naberdz** [comment]
@magento-engcom-team i have updated initial starting topic. 
not sure if it's vanilla version of magento. Installed magento with composer
> composer create-project --repository=https://repo.magento.com/ magento/project-community-edition

**Comment by ghost** [comment]
HI @Naberdz thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.3-develop instance, this may be related to your custom modules, this issue is not present on clean magento. The GitHub issue tracker is intended for Magento Core technical issues only

**Comment by Naberdz** [comment]
> HI @Naberdz thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.3-develop instance, this may be related to your custom modules, this issue is not present on clean magento. The GitHub issue tracker is intended for Magento Core technical issues only

Yes it seem to be error in my template. since when i had switched it to Luma everything worked just fine.
