### ISSUE TITLE
Countries dropdown is empty

### ISSUE THREAD

**Issue by SLv99** [magento/magento2#2146]
Hi,

Everywhere in my Magento webshop the dropdown to select countries is empty. For example General > General > Country options > Default Country is empty (The only option is --Please Select--).

Also under locale options (I'm trying to change the store view locale) the dropdown is empty.

Is this a known issue? How can I fix this for my installation? I have other Magento 2 installations running that does not have this problem. Maybe the way of installing Magento is the cause (via Composer or download from Github)?

**Comment by choukalos** [comment]
I'm not able to replicate that issue;  Did you have this issue as an upgrade on top of a prior commit of Magento 2?  If so it's possible it's a javascript issue or a database creation/update issue.  Easy try might be :  rm -rf var/* ; bin/magento setup:di:compile ; bin/magento setup:static-content:deploy   - to force recompile/re publish of static JS widgets,etc.  If DB issue then I'd recommend dropping the DB and try reinstalling.

**Comment by SLv99** [comment]
I think it's a database related problem. When I try to run php bin/magento setup:static-content:deploy I get this error: 

  [InvalidArgumentException]                                                                     
  en_US argument has invalid value, please run info:language:list for list of available locales  

When I run php bin/magento info:language:list I get this:
+----------+------+
| Language | Code |
+----------+------+

After that I reinstalled everything and now it's working fine.

**Comment by daim2k5** [comment]
@SLv99 did you use the develop branch? If you get the error still with a fresh install?

**Comment by SLv99** [comment]
I did not use the develop branch. The problem I had was on 1.0.0-beta, when I reinstalled and updated to 1.0.0-beta4 the problem was solved.

**Comment by au00433276** [comment]
also in checkout shipping  and billing country select box, there are 2 blank options values before country list, how to deal with that ?

**Comment by namratavora** [comment]
@au00433276 : I am facing the same issue in Magento 2.1.8

**Comment by gritdigital-mibu** [comment]
@au00433276 @namratavora Also happening for me using Magento 2.1.8. I suspect it could be related to the data migration tool?

![2017-10-31 11_12_19-checkout](https://user-images.githubusercontent.com/11611416/32221167-67a55b78-be2c-11e7-8615-980c3e851d5c.png)

**Comment by gixid192** [comment]
This can be reproduced with a fresh installation, however, Magento fixed it in 2.2.x
Magento fixed the vendor/magento/module-ui/view/base/web/js/form/element/select.js file (line 40)
`parseOptions` function.
An alternative way for the lower versions is to change `vendor/magento/module-directory/Model/ResourceModel/Country/Collection.php` (line 240) at the end of function `toOptionArray`  ![fix](https://content.screencast.com/users/Lovemagic/folders/Jing/media/be7679ab-b473-440a-a0bd-e938a9d3ebb8/2018-03-19_1535.png)

I haven't fully tested with the second way but it is working for me in cart and checkout pages.

**Comment by namratavora** [comment]
@au00433276 , @gritdigital-mibu ,

Yes, the issue is been fixed in Magento version 2.2.2

**Comment by sidolov** [comment]
Hi @SilvanLaroo. Thank you for your report. 
The issue has been fixed in magento/magento2#17194 by @nilesh2jcommerce in 2.1-develop branch
Related commit(s):
 - [cbbc584fe9359cd0e1b9930f1844881c773a6d6e](https://github.com/magento/magento2/commit/cbbc584fe9359cd0e1b9930f1844881c773a6d6e)
 - [ccd70ce4f700bda623bfe1e0fe707175008bb478](https://github.com/magento/magento2/commit/ccd70ce4f700bda623bfe1e0fe707175008bb478)
 - [f84271004b92b8427d4dd7065f0fab01fd7da647](https://github.com/magento/magento2/commit/f84271004b92b8427d4dd7065f0fab01fd7da647)
 - [7f4196d01956eb1ce06488c91609585429b137f9](https://github.com/magento/magento2/commit/7f4196d01956eb1ce06488c91609585429b137f9)
 - [004de46f0adf824392f3324052fd9a7ed7831e84](https://github.com/magento/magento2/commit/004de46f0adf824392f3324052fd9a7ed7831e84)
 - [18c9e6088cda4cba137c59b9373f066b9b500be0](https://github.com/magento/magento2/commit/18c9e6088cda4cba137c59b9373f066b9b500be0)
 - [b413c17fddeaa72a26949e85a7c020315a698154](https://github.com/magento/magento2/commit/b413c17fddeaa72a26949e85a7c020315a698154)
 - [213b461cb2c90129ebe2baaaf3995b4f92887410](https://github.com/magento/magento2/commit/213b461cb2c90129ebe2baaaf3995b4f92887410)
 - [70f336a81bbb0ac87f3da71734e53be57bc2c48a](https://github.com/magento/magento2/commit/70f336a81bbb0ac87f3da71734e53be57bc2c48a)

The fix will be available with the upcoming 2.1.16 release.
