### ISSUE TITLE
Website Restrict mode on Magento Commerce, giving error

### ISSUE THREAD

**Issue by Ketika** [magento/magento2#21464]
### Preconditions (*)

1. Magento commerce version 2.3.0

### Steps to reproduce (*)

1. Go to Admin side. Follow this path: Stores-> Settings -> Configuration -> General ->Website Restriction
2. Set "Access Restriction" field to "Yes".
3. Select "Restriction Mode" is to "Website Closed". Also selected landing page as "404 page".
4. Save this configuration.

### Expected result (*)

1. Open the front end of Magento commerce and it should redirect user to 404 page.

### Actual result (*)

1. When opening the front end then it is throwing error instead of showing 404 page.
Error: "1 exception(s):
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'Magento_Theme::js/require_js.phtml' in module: '' block's name: 'require.js'"
2. 
![m2ee](https://user-images.githubusercontent.com/8788037/53440307-3db7bd80-3a2a-11e9-9cb0-8778cd73a80f.png)

**Comment by magento-engcom-team** [comment]
Hi @Ketika. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Ketika do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Ketika** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Ketika. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Ketika, here is your [Magento instance](https://i-21464-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21464-2-3-develop.instances.magento-community.engineering/admin](https://i-21464-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Ketika** [comment]
Hi @magento-engcom-team I need vanila Magento Commerce Instance. Right now, it is a Magento open source instance.

**Comment by Nazar65** [comment]
@Ketika github intended only for CE version

You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by dmanners** [comment]
Incase anyone else comes across this issue this is still an issue with 2.4.5-p1 and can be fixed with the following code in a new module's layout.xml.

```xml
<?xml version="1.0"?>
<layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/layout_generic.xsd">
    <referenceBlock name="require.js">
        <action method="setTemplate">
            <argument name="template" xsi:type="string">Magento_Theme::page/js/require_js.phtml</argument>
        </action>
    </referenceBlock>
</layout>
```

Problem is that the template in the core layout xml is written without the page part and so Magento cannot find the template.
