### ISSUE TITLE
Products cannot be updated

### ISSUE THREAD

**Issue by dixilota** [magento/magento2#21461]
### Preconditions (*)

1.Magento 2.3.0
2.

### Steps to reproduce (*)

1.* Set Price Scope to Website (Stores -> Configuration -> Catalog -> Catalog -> Prices)
2.  Try to update Product

### Expected result (*)
1. 1. Product Values are updated

### Actual result (*)

1. ![pantallazo](https://user-images.githubusercontent.com/48016996/53411168-17603680-39c6-11e9-8de9-54ded5a6e2d1.jpg)
2.
[2019-02-26 11:54:55] main.CRITICAL: Unique constraint violation found {"exception":"[object] (Magento\\Framework\\Exception\\AlreadyExistsException(code: 0): Unique constraint violation found at /var/www/vhosts/test-overalia.com/magento.test-overalia.com/vendor/magento/framework/EntityManager/Operation/Update.php:121, Magento\\Framework\\DB\\Adapter\\DuplicateException(code: 1062): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '60-0-4-1.0000-0' for key 'UNQ_E8AB433B9ACB00343ABB312AD2FAB087', query was: INSERT INTO `catalog_product_entity_tier_price` (`entity_id`, `all_groups`, `customer_group_id`, `qty`, `value`, `percentage_value`, `website_id`) VALUES (?, ?, ?, ?, ?, ?, ?) at /var/www/vhosts/test-overalia.com/magento.test-overalia.com/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:588, Zend_Db_Statement_Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '60-0-4-1.0000-0' for key 'UNQ_E8AB433B9ACB00343ABB312AD2FAB087', query was: INSERT INTO `catalog_product_entity_tier_price` (`entity_id`, `all_groups`, `customer_group_id`, `qty`, `value`, `percentage_value`, `website_id`) VALUES (?, ?, ?, ?, ?, ?, ?) at /var/www/vhosts/test-overalia.com/magento.test-overalia.com/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '60-0-4-1.0000-0' for key 'UNQ_E8AB433B9ACB00343ABB312AD2FAB087' at /var/www/vhosts/test-overalia.com/magento.test-overalia.com/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228)"} []

**Comment by magento-engcom-team** [comment]
Hi @dixilota. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dixilota do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dixilota** [comment]
Yes, give me instance



Mikel Poza
Sistemas
Email: mikel@overalia.com
Tel: 902 820 920 <902%20820%20920%20> / Fax: 943 224 901 <943224901>
Dirección: Portuetxe 23 B, 1º of. 2 - 20018 San Sebastián
Web: www.overalia.com

Este correo electrónico y, en su caso, cualquier fichero anexo al mismo, se
dirige exclusivamente a su destinatario y puede contener información
CONFIDENCIAL sometida a secreto profesional o cuya divulgación esté
prohibida en virtud de la legislación vigente. Si ha recibido este mensaje
por error, le rogamos que nos lo comunique inmediatamente por esta misma
vía y proceda a su destrucción.

**Comment by magento-engcom-team** [comment]
Hi @dixilota. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dixilota, here is your [Magento instance](https://i-21461-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21461-2-3-develop.instances.magento-community.engineering/admin](https://i-21461-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by dixilota** [comment]
that issue is not reproducible



Mikel Poza
Sistemas
Email: mikel@overalia.com
Tel: 902 820 920 <902%20820%20920%20> / Fax: 943 224 901 <943224901>
Dirección: Portuetxe 23 B, 1º of. 2 - 20018 San Sebastián
Web: www.overalia.com

Este correo electrónico y, en su caso, cualquier fichero anexo al mismo, se
dirige exclusivamente a su destinatario y puede contener información
CONFIDENCIAL sometida a secreto profesional o cuya divulgación esté
prohibida en virtud de la legislación vigente. Si ha recibido este mensaje
por error, le rogamos que nos lo comunique inmediatamente por esta misma
vía y proceda a su destrucción.

**Comment by ghost** [comment]
Hi @dixilota thank you for you report, i'm not able to reproduce following steps you described, this may be related to your custom modules.
