### ISSUE TITLE
addAttributeGroup for attribute_group_name "Images"

### ISSUE THREAD

**Issue by alex5513** [magento/magento2#21479]
### Preconditions (*)

1. Magento 2.2.6 or 2.3.0

### Steps to reproduce (*)

1. Use addAttributeGroup("4", "4", "Images") from EavSetup class

### Expected result (*)

1. The attribute already exists by default in Magento, we should pass into the updateAttributeGroup method (l.540)

### Actual result (*)

1. In the addAttributeGroup function, attribute_group_code is worth "images" because of convertToAttributeGroupCode method. In DB the attribute_group_code of "Images" is "image-management".

So it doesn't recognize the attribute code and pass into the insert method (l.552) so I have a SQL error

![capture d ecran 2019-02-27 a 15 36 24](https://user-images.githubusercontent.com/6359584/53497957-9d06e380-3aa5-11e9-8297-39e6365c186e.png)

**Comment by magento-engcom-team** [comment]
Hi @alex5513. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@alex5513 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by irajneeshgupta** [comment]
@alex5513
it is a duplicate issue -> https://github.com/magento/magento2/issues/19783

**Comment by alex5513** [comment]
Thanks for you reply but it's not the same issue. You try to add new attribute image to Images attribute group, i try to add many new attribute groupes of which "Images", it's a constraint that I can not change. In addition addAttributeGroup takes as parameter only attribute_group_name and not attribute_group_code. 
The attribute code should be images and not image-management because Magento pass the attribute group name in the strtolower function to find the attribute group code in addAttributeGroup method.
