### ISSUE TITLE
Adding a $0.00 product to a wishlist causes Uncaught TypeError

### ISSUE THREAD

**Issue by CHallski** [magento/magento2#21485]
### Preconditions (*)
Magento 2.2.5

### Steps to reproduce (*)
1. Create a simple product with a price of $0.00
2. Add the product to your wishlist

### Expected result (*)
I expect the product to add to the wishlist and the wishlist to remain functional.

### Actual result (*)
Wishlist loads up to that product and produces the following

Fatal error: 
Uncaught TypeError: 
Argument 1 passed to Magento\Catalog\Pricing\Price\ConfiguredOptions::getItemOptionsValue() must be of the type float, boolean given, 
called in /srv/public_html/releases/20190211174544/vendor/magento/module-catalog/Pricing/Price/ConfiguredRegularPrice.php on line 74 
and defined in /srv/public_html/releases/20190211174544/vendor/magento/module-catalog/Pricing/Price/ConfiguredOptions.php:24

**Comment by magento-engcom-team** [comment]
Hi @CHallski. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@CHallski do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by CHallski** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CHallski. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CHallski, here is your [Magento instance](https://i-21485-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21485-2-3-develop.instances.magento-community.engineering/admin](https://i-21485-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by CHallski** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @CHallski. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @CHallski, here is your [Magento instance](https://i-21485-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-21485-2-2-5.instances.magento-community.engineering/admin](https://i-21485-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by CHallski** [comment]
Issue confirmed in vanilla 2.2.5
Issue not present in vanilla 2.3-develop

**Comment by CHallski** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CHallski. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CHallski, here is your [Magento instance](https://i-21485-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21485-2-2-develop.instances.magento-community.engineering/admin](https://i-21485-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by CHallski** [comment]
Issue also not present in 2.2-develop: presumably was resolved by previous patch
