### ISSUE TITLE
addAttributeGroup for attribute_group_name "Images"

### ISSUE THREAD

**Issue by alex5513** [magento/magento2#21481]
It's not the same issue than -> [#19783](https://github.com/magento/magento2/issues/19783).

They try to add new attribute image to Images attribute group, i try to add many new attribute groupes of which "Images", it's a constraint that I can not change. 

In addition addAttributeGroup takes as parameter only attribute_group_name and not attribute_group_code.

The attribute code should be images and not image-management because Magento pass the attribute group name in the strtolower function to find the attribute group code in addAttributeGroup method.

### Preconditions (*)

1. Magento 2.2.6 or 2.3.0

### Steps to reproduce (*)

1. Use addAttributeGroup("4", "4", "Images") from EavSetup class

### Expected result (*)

1. The attribute already exists by default in Magento, we should pass into the updateAttributeGroup method (l.540)

### Actual result (*)

1. In the addAttributeGroup function, attribute_group_code is worth "images" because of convertToAttributeGroupCode method. In DB the attribute_group_code of "Images" is "image-management".

So it doesn't recognize the attribute code and pass into the insert method (l.552) so I have a SQL error

![capture d ecran 2019-02-27 a 15 36 24](https://user-images.githubusercontent.com/6359584/53503440-59fe3d80-3ab0-11e9-9184-e96e458a9b0f.png)

**Comment by magento-engcom-team** [comment]
Hi @alex5513. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@alex5513 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @alex5513 , based on

> If we add 'group' => 'image-management' , it will create fine because image-management is correct attribute_group_code but 'group' => 'Images' expects attribute_group_name so i can not simply change it.

I make a conclusion that provided code snippet is incorrect. It looks like there is nothing to fix here from core perspective. Please verify if proposed solution works for you.

**Comment by alex5513** [comment]
Proposed solution don't works for me !!! 
Read my ticket please !!!

addAttributeGroup takes as parameter only attribute_group_name and not attribute_group_code !! 

My request use this parameters : addAttributeGroup("4", "4", "Images")

**Comment by ghost** [comment]
@alex5513 This name already exist in your Database, i'm not able to reproduce on clean DB install 
![deepinscreenshot_select-area_20190301122944](https://user-images.githubusercontent.com/40756439/53632569-03af0d00-3c1e-11e9-8636-4075a32d9cdb.png)
but if i do this request again for second group 
![deepinscreenshot_select-area_20190301123233](https://user-images.githubusercontent.com/40756439/53632614-1de8eb00-3c1e-11e9-881d-f5d271f87e0e.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98513`, `MAGETWO-98514` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by alex5513** [comment]
Thank you for reopening the ticket. I add that you are testing using a SQL query. 
I'm talking about the addAttributeGroup() method and convertToAttributeGroupCode(). Attribute_group_name "Images" already exist in clean DB for product entity

**Comment by wclrz** [comment]
Up

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by sdzhepa** [comment]
Hello @cstergianos 

It seems our bots got crazy in this Issue...
I suppose it could be because of delays while webhooks processing.

Could you please confirm this is still an actual Issue and you are going to work on it?
or it should be closed 

Sorry for inconveniences
