### ISSUE TITLE
Elasticsearch: Product Attribute Multiple Select: store views with multiple locales: search always use Default Store View locale

### ISSUE THREAD

**Issue by fgagne** [magento/magento2#21490]
### Preconditions (*)
1. Install Magento 2.3.0 CE + sample data + ElasticSearch 5.x
2. Configure ElasticSearch as Search Engine
3. Reindex

### Steps to reproduce (*)
1. Login to admin
2. Navigate to **Stores -> Settings -> All Stores**
3. Click **Create Store View**

* Store: Main Website Store
* Name: French
* Code: french
* Status: Enabled

4. Click **Save Store View**
5. Navigate to **Stores -> Settings -> Configuration**
6. Select the **Store View:**: **French**
7. Navigate in the left pane -> **GENERAL** -> **General**
8. Go to the **Locale Options** section
9. For the **Locale** field, uncheck **Use Website** and select **French (France)**
10. Click **Save Config**
11. Navigate to **Stores -> Attributes-> Product**
12. Edit **Climate**
13. Go to the **Manage Options (Values of Your Attribute)** section
14. In the **French** column, row **Wintry** enter **Hivernal**
14. Navigate in the left pane -> **ATTRIBUTE INFORMATION** -> **Storefront Properties**
15. Edit **Use in Search** to **Yes**
16. Click **Save Attribute**
17. Perform **Full Reindex** (php bin/magento indexer:reindex) and **Flush Cache**
18. Open the customer facing website
19. Verify that you are on the default store view, not the newly created French store view
20. Do a quick search for **Wintry**
21. It should show ~19 results (this is to verify that everything is setup correctly)

The problematic part:
1. Open the customer facing website
2. Change the current store view to **French** (the dropdown on the top right)
3. Do a quick search for **Hivernal**
4. The search returns no results, it should returns the same ~19 results as above

Changing the default store view changes the locale used by the search
1. Login to admin
2. Navigate to **Stores -> Settings -> All Stores**
3. Click **Main Website Store**
4. Change the **Default Store View** to **French**
5. Click **Save Store**
6. Perform **Full Reindex** (php bin/magento indexer:reindex) and **Flush Cache**

Retry the above quick search:
1. Open the customer facing website
2. Change the current store view to **French** (the dropdown on the top right)
3. Do a quick search for **Hivernal**
4. Now the search returns ~19 results as it should

Now the default English store view ain't working
1. Open the customer facing website
2. Change the current store view to the default store view (the dropdown on the top right)
3. Do a quick search for **Wintry**
4. The search returns no results, it should returns the same ~19 results as above

### Expected result (*)
1. Searching Product Attribute of type **Multiple Select** should work for all store views, in all locales, ignoring the **Default Store View** setting.

### Actual result (*)
1. As stated in the **Steps to reproduce**, when search looks in products attributes, it always do so in the **Default Store View** locale even when a store view with a different locale is selected.

**Comment by magento-engcom-team** [comment]
Hi @fgagne. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@fgagne do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by fgagne** [comment]
@magento-engcom-team unless mistaken, that vanille Magento instance don't come with ElasticSearch and thus is impossible to reproduce on the provided test facility.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98580` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @fgagne. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24414` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
