### ISSUE TITLE
Cart is emptied when enter is pressed after changing product quantity

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#21499]
### Preconditions

1. Latest 2.3-develop

### Steps to reproduce

1. Add any product to cart
2. Navigate to the cart
3. Un-hide "Clear Shopping Cart" button which is hidden in Luma by default by running this in browser console:
`jQuery("#empty_cart_button").show();`
4. Change item quantity in the input
5. Press "Enter"

### Expected result

1. Page is reloaded and item quantity is changed

### Actual result

1. Cart is cleared

This happens because there are two submit buttons in the cart form, and when enter is pressed, the first one is executed. First one is "Clear Shopping Cart", so cart is cleared instead of updated. The simplest fix is to change order of those elements in source code.

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@wojtekn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by wojtekn** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wojtekn, here is your [Magento instance](https://i-21499-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21499-2-3-develop.instances.magento-community.engineering/admin](https://i-21499-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by wojtekn** [comment]
I reproduced the issue on provided instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98486` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lfluvisotto** [comment]
@wojtekn , @rogyar 

Have a look at this PR https://github.com/magento/magento2/pull/21509, it doesn't need to change the button's order/position

**Comment by lfluvisotto** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lfluvisotto. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lfluvisotto, here is your [Magento instance](https://i-21499-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21499-2-2-develop.instances.magento-community.engineering/admin](https://i-21499-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by wojtekn** [comment]
@lfluvisotto it's still better to adjust their position to have primary button first in the DOM, also, if issue can be clearly fixed by using better HTML, we don't need to add JS hacks.

**Comment by magento-engcom-team** [comment]
Hi @lfluvisotto. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by lfluvisotto** [comment]
@wojtekn 

It isn't a JS hack it's a JS fix, since magento 1 and now with magento 2 that button to clear/empty the cart comes before the update cart button.

For example: your fix is about changing the position of buttons, but if the user want to keep in their layout/template without CSS hack, the clear/empty cart button button before update cart button, your fix it's going to fail.

cc @VladimirZaets

**Comment by magento-engcom-team** [comment]
Hi @magento-engcom-team. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#21509 by @lfluvisotto in 2.3-develop branch
Related commit(s):
 - [539766f41049e8e86490b2861de8c98227236198](https://github.com/magento/magento2/commit/539766f41049e8e86490b2861de8c98227236198)
 - [fd3344be60488b5f59c4fcffb1080c2a7689ad81](https://github.com/magento/magento2/commit/fd3344be60488b5f59c4fcffb1080c2a7689ad81)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#21512 by @lfluvisotto in 2.2-develop branch
Related commit(s):
 - [5a736409eef6c7841f4a6fc8f3a7a8a8affd2a32](https://github.com/magento/magento2/commit/5a736409eef6c7841f4a6fc8f3a7a8a8affd2a32)
 - [f4a83f6344c6fc11400fcd0e8d206ec206c9f37c](https://github.com/magento/magento2/commit/f4a83f6344c6fc11400fcd0e8d206ec206c9f37c)
 - [5d0245df8119614ad52768f7d1b1bbfd35c4c626](https://github.com/magento/magento2/commit/5d0245df8119614ad52768f7d1b1bbfd35c4c626)

The fix will be available with the upcoming 2.2.9 release.

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#24499 by @edenduong in 2.3-develop branch
Related commit(s):
 - [7005d99ae4af1f3ffdf35ba8370c4295c0bfbfe6](https://github.com/magento/magento2/commit/7005d99ae4af1f3ffdf35ba8370c4295c0bfbfe6)
 - [5847d9f64dad423d83bf0c742d810783ca213639](https://github.com/magento/magento2/commit/5847d9f64dad423d83bf0c742d810783ca213639)

The fix will be available with the upcoming 2.3.4 release.
