### ISSUE TITLE
Magento 2.3.0 wysiwyg editor does not shows script tag while editor mode

### ISSUE THREAD

**Issue by dasharath-wagento** [magento/magento2#21495]
### Preconditions (*)

1. Install Magento 2.3.0 CE + sample data

### Steps to reproduce (*)

1. Login to admin
2. Navigate to Content -> Element -> Blocks ->
3. Create a New Block  Add New Block
4. Paste data in content as below

[test_code.txt](https://github.com/magento/magento2/files/2913756/test_code.txt)
5. then save cms block.

### Expected result (*)

1. [Screenshots, logs or description]
![screenshot from 2019-02-28 12-18-49](https://user-images.githubusercontent.com/18435810/53547540-51137780-3b55-11e9-8c92-4b791692c906.png)

### Actual result (*)

1. [Screenshots, logs or description]
![screenshot from 2019-02-28 12-19-56](https://user-images.githubusercontent.com/18435810/53547562-5ec8fd00-3b55-11e9-89df-485d507f9508.png)

**Comment by magento-engcom-team** [comment]
Hi @dasharath-wagento. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dasharath-wagento do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @dasharath-wagento thank you for you report, The editor is removing by default the <script> tag in order to prevent possible XSS attacks. Although we don't recommend to do that, you can allow it inside the editable area by changing the htmlRemoveTags option.

**Comment by Interghost** [comment]
where is the htmlRemoveTags option?

**Comment by JiyaadDolly** [comment]
HI, where is the htmlRemoveTags option?

**Comment by guilhermengler** [comment]
Hi, where is the htmlRemoveTags option?

**Comment by adarshkhatri** [comment]
Hi, where is the htmlRemoveTags option?

**Comment by Sufi737** [comment]
Hi, where is the htmlRemoveTags option?

**Comment by schnyadav161** [comment]
You can fix this using below url
https://magento.stackexchange.com/questions/335036/m2-tinymce4-javascript-disappear-after-switch-to-tinymce-and-back-to-html-edit/353841#353841
This will allow you show your script tag while editor mode
