### ISSUE TITLE
Performance ToolKit missing Invoices

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento2#21491]
### Preconditions (*)

1. Magento 2.2.7 & 2.3.0
2. Dev environment

### Steps to reproduce (*)
1. Run performance toolkit:
`bin/magento setup:performance:generate-fixtures -s setup/performance-toolkit/profiles/ce/medium.xml`
2. Open Admin panel
3. Observe no invoices

### Expected result (*)
1. Invoices to be generated with Orders

### Actual result (*)
1. No Invoices generated

### WHY THIS MATTERS
For large sites with many orders and invoices, the Admin Dashboard is horribly slow. This is caused by the query that calculates the lifetime sales total

Magento _may_ have caught this if invoices were populated using the performance toolkit.

Though a slow admin dashboard is not the reported issue of this ticket, it is important that Magento populates as much order data as possible for realistic performance metrics.

**Comment by magento-engcom-team** [comment]
Hi @Stoyvo. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Stoyvo do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi  @Stoyvo   thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by Stoyvo** [comment]
@engcom-backlog-nazar Not sure I understand. Am I to make a ticket there, linked to my pull request on this repo?

**Comment by ghost** [comment]
@Stoyvo Yes you need to open issue there and create PR linked issue to this repo. like this -> https://github.com/magento/community-features/issues/141

**Comment by Stoyvo** [comment]
Thanks @engcom-backlog-nazar 

https://github.com/magento/community-features/issues/147
