### ISSUE TITLE
Magento 2.3.0: Elasticsearch 5.0+: Enable Elasticsearch HTTP Auth: HTTP Username/Password fields not showing up

### ISSUE THREAD

**Issue by fgagne** [magento/magento2#21494]
### Preconditions
1. Install Magento 2.3.0 CE

### Steps to reproduce
1. Login to admin
2. Navigate to **Stores -> Settings -> Configuration**
4. Navigate in the left pane -> **CATALOG** -> **Catalog**
5. Go to the **Catalog Search** section
6. Change **Search Engine** field to **Elasticsearch 5.0+**
7. Change **Enable Elasticsearch HTTP Auth** field to **Yes**

### Expected result
1. The fields **Elasticsearch HTTP Username** and **Elasticsearch HTTP Password** should now be visible.

This works fine when **Search Engine** is set to **Elasticsearch** (beware that the fields aren't the same for **Elasticsearch 5.0+**, **catalog_search_elasticsearch_username** vs **catalog_search_elasticsearch5_username** and **catalog_search_elasticsearch_password** vs **catalog_search_elasticsearch5_password**)

### Actual result
1. The fields **Elasticsearch HTTP Username** and **Elasticsearch HTTP Password** stay hidden.

### Workaround:
I've found this workaround while filling this bug report.
1. Change **Search Engine** field to **Elasticsearch**
2. Change **Enable Elasticsearch HTTP Auth** field to **Yes**
3. Change **Search Engine** field to **Elasticsearch 5.0+**

Now the fields **Elasticsearch HTTP Username** and **Elasticsearch HTTP Password** are visible.

**Comment by magento-engcom-team** [comment]
Hi @fgagne. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@fgagne do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by fgagne** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @fgagne. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @fgagne, here is your [Magento instance](https://i-21494-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21494-2-3-develop.instances.magento-community.engineering/admin](https://i-21494-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by fgagne** [comment]
Thanks @magento-engcom-team, the issue is fixed in 2.3-develop.
