### ISSUE TITLE
Page jumping on top while scroll on media gallery product page

### ISSUE THREAD

**Issue by andy1786** [magento/magento2#21507]
### Preconditions (*)

Problem is on Magento 2.2.6, product page with media gallery

### Steps to reproduce (*)

When I am on product page on mobile and I swipe down then is automatically pushing me on the top of the page. It is scrolling for 50% of the page and then is scrolling up. If I swipe faster, then is getting the gallery out of the screen and there is no problem anymore.

This is only on Android phones and I could not reproduce it on iOS or browsers on desktop.

### Expected result (*)

When I disable swipe from view.xml, then this should not happen anymore.

### Actual result (*)

When I am on product page on mobile and I swipe down then is automatically pushing me on the top of the page. It is scrolling for 50% of the page and then is scrolling up. If I swipe faster, then is getting the gallery out of the screen and there is no problem anymore.

**Comment by magento-engcom-team** [comment]
Hi @andy1786. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@andy1786 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @andy1786 thank you for you report, this issue has already fixed in 2.3-develop branch https://github.com/magento/magento2/issues/7906

**Comment by Ctucker9233** [comment]
@magento-engcom-team Shouldn't this stay open until it's backported to 2.2? It seems a lot of bug fixes get missed.

**Comment by ghost** [comment]
Hi @Ctucker9233 backport already here -> #22078 thank you for collaboration :+1:
