### ISSUE TITLE
Canceled Shipped order not returning item to stock

### ISSUE THREAD

**Issue by prog7707** [magento/magento2#21517]
When an order is in pending state then it is shipped, the item quantity for that order is decreased and the state of the order becomes processing. If the order in this state get canceled the item does not return back to stock.
I use this process Make order then Ship then invoice, because using cash on delivery so the shipment is before payment.
### Preconditions (*)
Magento CE
1. 2.2.6
2. 2.2.7

### Steps to reproduce (*)
1. Make an order
2. Ship that order (do not invoice)
3. Cancel that order

### Expected result (*)

1. items must return back to stock if canceled

### Actual result (*)

1. Item not returning to stock

**Comment by magento-engcom-team** [comment]
Hi @nexus4alii1991. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nexus4alii1991 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21517-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21517-2-2-develop.instances.magento-community.engineering/admin](https://i-21517-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi  @nexus4alii1991  thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by bmullins420** [comment]
Hello @ghost and @nexus4alii1991.  Is there a resolution for this? we process orders the same way Order->Ship->Invoice because we are cash on delivery only.  When a shipped order is canceled, items are not returned to stock in 2.4

**Comment by cptX** [comment]
I also want to know the answer for this! When cancelled order should return items back in stock

**Comment by cptX** [comment]
Why did you close such an important issue!!!???? Please reopen. I have to manually set the quantities of all items in every order that is returned!!! This feature is necessary!!!
