### ISSUE TITLE
Create order from backend not always showing shipping method

### ISSUE THREAD

**Issue by prog7707** [magento/magento2#21516]
Shipping Method is not always appearing when creating an order from the backend, the problem appears when removing an item already selected and adding another one. I stated this issue earlier but they couldn't reproduce it so i made a YouTube video showing how:
https://youtu.be/H9VSFp6dOTo

If this issue is solved in version 2.3 can you please show me what to change to solve it in version 2.2.6 and 2.2.7.

### Preconditions (*)

Versions Tested on Magento CE

    1. 2.2.6

    2. 2.2.7

### Steps to reproduce (*)

1. create new order
2. Select customer
3. Select item and add to order
4. Get Shipping Method (to this point it works)
5. remove item selected previously
6. add another item to order
7. Get Shipping Method( it gives Sorry, no quotes are available for this order.)
8. edit customer info just add anything
9. Get Shipping Method again (here it works)

### Expected result (*)

    1. At step 7, lsit of shipping methods must appear

### Actual result (*)

    1. No shipping method appears at step 7

    2. If customer info is changed(just adding anything a letter to street then removing it) this will cause another ajax loading then shipping methods appear correctly.

**Comment by magento-engcom-team** [comment]
Hi @nexus4alii1991. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nexus4alii1991 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi  @nexus4alii1991 thank you for you report, this issue  fixed in 2.3-develop and will be available on 2.3.1 release, but i cannot find related commit on github, seems like this have been fixed by core team.
