### ISSUE TITLE
500 error when creating configurable products

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#21515]
### Preconditions (*)

1. Magento 2.3.0 CE
2. PHP 7.1
3. Nginx

### Steps to reproduce (*)

500 error if you do not finish the configurable configurations products flow.

1. Install using composer https://devdocs.magento.com/guides/v2.3/install-gde/composer.html
2. Go to Backend > Products, click the little arrow to create "Configurable product"
3. The interface loads a simple product GUI (ability to add stock qty) etc. Fill in the req fields only and hit Save.
4. Be greeted by 500 error
5. Click back on browser and go back to product list, a new **Simple Product** has been created 

### Expected result (*)

Save product as configurable product type **or** stop the user from saving it with an error before they generate products.

### Actual result (*)

500 error on saving before generating products.

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Zyles do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21515-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21515-2-3-0.instances.magento-community.engineering/admin](https://i-21515-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @Zyles i'm not able to reproduce following steps you described, can you recheck on vanilla instance ?

**Comment by ghost** [comment]
@Zyles My actual result product saves as simple product .

**Comment by Zyles** [comment]
> @Zyles My actual result product saves as simple product .

Yep I used a vanilla instance, fresh install.

Then it is broken because it should save as configurable product type not simple product.

You need to fill in product name, sku and price. NOTHING ELSE.

**Comment by ghost** [comment]
@Zyles yes i do exactly what in your steps to reproduce but not have 500 error
