### ISSUE TITLE
Having a system customer attribute exposed in \Magento\Customer\Api\Data\CustomerInterface

### ISSUE THREAD

**Issue by adragus-inviqa** [magento/magento2#2152]
I need to save a custom Customer attribute (`apid`, which is **system** and static) via a `\Magento\Customer\Api\Data\CustomerInterface` implementation, which I receive as a method argument.

First, I tried `$customer->setCustomAttribute('apid', 'some value');`.

But the condtions [here](https://github.com/magento/magento2/blob/098d3ff5e9f4500ca67e93d9524df58834acab8a/app/code/Magento/Customer/Model/Metadata/CustomerMetadata.php#L134-L139) won't let me: it only adds the non-system attributes that are not declared via extensions. Sure, no problem. But why? What's the reason behind that condition?

How can I save a custom.. erm.. Customer **system** attribute via `\Magento\Customer\Api\Data\CustomerInterface`? 

PS: I need this particular interface because of certain custom logic which led me to an around-interceptor for a method which receives that particular interface as an argument:
```php
public function aroundCreateAccount(
    AccountManagementInterface $subject,
    \Closure $proceed,
    \Magento\Customer\Api\Data\CustomerInterface $customer,
    $password,
    $redirectUrl
) {
    // stuff

    $customer->setCustomAttribute('apid', 'some value'); // this is disregarded
    
    return $proceed($customer, $password, $redirectUrl);
}
```

**Comment by adragus-inviqa** [comment]
I fixed that by changing the customer attribute's `is_system` to `0`. I almost confused it with `is_user_defined`. What's the purpose of that customer attribute.. attribute?

**Comment by vkorotun** [comment]
Hi @adragus-inviqa for such a long silence,

System attributes are referred from the code, while custom attributes are the ones that could be created and deleted via Admin Panel UI. So, we won't find references to such attributes through the code.

The condition you've mentioned is valid, and we don't want system attributes to be returned out that method, since the result might be used for example to delete attributes from result set or to do other undesired actions against system attributes.

If you need to define system attribute from your extension, then it should be declared as 'extension attribute'. See as an example [here](https://github.com/magento/magento2/blob/098d3ff5e9f4500ca67e93d9524df58834acab8a/app/code/Magento/Tax/etc/extension_attributes.xml). In example module Tax added extension attributes to TotalSegmentInterface and OrderInterface entities. 

If your extension attribute is added normally as EAV, then it should be persisted as any other attribute.

And [here](https://github.com/magento/magento2/blob/098d3ff5e9f4500ca67e93d9524df58834acab8a/app/code/Magento/Tax/Model/Quote/GrandTotalDetailsPlugin.php#L112-L117) you'll find how extension attribute is stored to databases with plugin when it is not of EAV type, so you need to take care of all things.

**Comment by andreymoskvenkov** [comment]
What is the goal of "is_system" column in the eav_attribute table, if the values of such attributes cannot be saved via Admin interface?
Example: I have created a new attribute "is_fraud_whitelisted" (boolean) in "customer_eav_atribute" table for Customer entity. I have set "is_system=1" and "is_user_defined=0" for this attribute. I have also added it to "General" group, added this attribute the the "customer_form_attribute" table. Now I see it in the admin interface, when edit a customer. But I cannot save selected value of this attribute there, because Magento code skips "is_system" attributes and desides that such attributes are not "custom attribute".

So the question is: what is the reason of having "is_system" column in EAV table ? More particular question: What could be a reason of having a record in customer_eav_atribute table with is_system = 1, when the only action, that this flag does, - it makes this attribute not working in EAV architecture? 
So as an example: I have created an attribute and set "is_system=1" for it and now I neither can save this attribute for a customer in Admin panel, nor set it in the code and use/save it in the code.

I have tried to add this attribute to "extension_attributes" xml file, but no luck - saving from the admin panel also does not work, because I have created an EAV record for this attribute in eav_attribute table (for having a simple ability to manage it for customers through the Admin interface), therefore Magento identifies it as Not "extension attribute" and tries to store the customer value into "custom_attribute" array, which is not then processed by Magento EAV model, because this attribute is set as "is_system".

**Comment by andreymoskvenkov** [comment]
Ok, is_user_defined = 0 in Magento 2.1.6 acts as "is_system = 1" normally acted in Magento1.
I have updated all migrated custom  customer attributes, which had "is_system=1" in Magento 1, to "is_system=0" and "is_user_defined=0" and now I am not able to delete those attributes from the Admin panel and able to edit customer values from the Admin panel, that is what I actually tried to achieve. Seems that "is_system" column is redundant in Magento 2.

**Comment by PivitParkour94** [comment]
A quick and dirty solution that can then be replaced with using the Customer Setup script in a data patch can be useful. I have used this successfully

`UPDATE customer_eav_attribute SET is_system = 0 WHERE attribute_id = (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = 1 AND attribute_code IN ('MY_CUSTOM_ATTRIBUTE'));`

Something to definitely be aware of when upgrading from M1 as 3rd party created attributes could have is_system = 1 and still work as expected.
