### ISSUE TITLE
Cron Jobs are not working. Schedule_id always 0

### ISSUE THREAD

**Issue by harimayco** [magento/magento2#21523]
Our Magento 2 cron jobs not working anymore since upgrading from 2.17 to 2.2.7.
so we need to manualy reindex every time.

### Preconditions (*)

1. Magento 2.2.7
2. PHP 7.1

### Steps to reproduce (*)

1. run bin/magento cron:run wil give u error

```
[Exception]
Item (Magento\Cron\Model\Schedule) with the same ID "0" already exists.
```

### Expected result (*)

1. Ran jobs by schedule.

### Actual result (*)

1. I checked the cron_schedule table the I found that the schedule ID generated by magento always 0
![screenshot_20190301_112817](https://user-images.githubusercontent.com/5478980/53616671-51277c00-3c16-11e9-8221-041767d70b00.png)

same issue: https://magento.stackexchange.com/questions/188500/magento2-2-1-5-cronjob-doesnt-get-executed-id-always-0
but still cannot find the solution.

Thank you

**Comment by magento-engcom-team** [comment]
Hi @harimayco. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@harimayco do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by harimayco** [comment]
After comparing our upgraded version with fresh installation of magento 2.2.7 we found that the table cron_schedule has missing index key. so we ran 
```
ALTER TABLE `cron_schedule`
  ADD PRIMARY KEY (`schedule_id`),
  ADD KEY `CRON_SCHEDULE_JOB_CODE` (`job_code`),
  ADD KEY `CRON_SCHEDULE_SCHEDULED_AT_STATUS` (`scheduled_at`,`status`);
ALTER TABLE `cron_schedule`
  MODIFY `schedule_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Schedule Id';
```

and the issue fixed, I don't know why and when the key was gone. but when I check our 2.1.7 database version it has the same structure. no key inside it.

we may accidentally delete it or some unfinished process when migrating the db.

Thank you.
