### ISSUE TITLE
Checkout page refreshes session

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#21544]
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Add a product to the cart
2. Go to the checkout page
3. Note down your PHPSESSID
4. Refresh the checkout page
5. See that the PHPSESSID has changed

### Expected result (*)

1. Don't change the session on a page refresh

### Actual result (*)

1. New session is created, losing all data when coming back from a payment provider when a payment is cancelled.

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@PascalBrouwers do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [x] no

**Comment by PascalBrouwers** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers, here is your [Magento instance](https://i-21544-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21544-2-2-develop.instances.magento-community.engineering/admin](https://i-21544-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by PascalBrouwers** [comment]
Ok, can't seem to reproduce it on latest 2.2.x
