### ISSUE TITLE
[2.3] Database Media Storage - New Product Images fail to be processed correctly

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#21546]
### Preconditions (*)
1. Magento 2.3-develop

### Steps to reproduce (*)
1. Vanilla Install 2.3-develop
2. Change database media storage configuration to database and Synchronise
3. Save settings
4. Create new product, add new image to product (in my test case refrigerationgauges.200x100.jpg)
5. Save Image

Expected Result is what happens under 2.2-develop. Actual Result is what happens under 2.3-develop.

### Expected result (*)
```
www-data@dev:~/dev1$ find pub/media -name *.jpg
pub/media/catalog/product/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/36fa622c226395c7a03aea76cb6f177a/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/12479842094003d6e8198e99b15d1aad/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/e4d64343b1bc593f1c5348fe05efa4a6/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/c430e3e26517992a27628ce5995d6769/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/411ddd1079653e9744172963f7b57a7a/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/a8be410535bd10951f8c121e888302ad/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/647c742965ace57b5484ad847e8cd3cc/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/e97e30f46ad3af2c4402aa864120074b/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/0b518a73ed92eecbe9790ec3a622cd2d/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/aefcd4d8d5c59ba860378cf3cd2e94da/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/d664e1acc15f6090304d588386caff1d/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/add01ceb5699006aaeaaa55353b05d62/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/f0eed8c49b05a5a279de03029e69388c/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/ecd051e9670bd57df35c8f0b122d8aea/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/10f519365b01716ddb90abc57de5a837/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/35d197d4a86bb7af9ea497ddcb0426c9/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/79cd194851544f88bafc552bf5216e5d/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/f9bb4946b08eb56afc1e83d5b55bf276/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/93545884bf1d6d40eefc44b2e3958bec/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/66336d755d72c30139c8c62793bff496/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/3e75d17be04cbebee9a78c36b24b6eea/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/08a0b36ebc62d1aabd4a717a82ad731c/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/19796d7732cc0b8676f199bbe04c742a/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/07aa3e3829adcf2640e41cdeee09b5bb/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/da51c19fe8c21b068c481cfb28c65074/r/e/refrigerationgauges.200x100.jpg
pub/media/catalog/product/cache/6b1c09900b407c50fce2db5e66ebc123/r/e/refrigerationgauges.200x100.jpg
www-data@dev:~/dev1$ mysql dev1_magento -e "select filename,directory FROM media_storage_file_storage"
+----------------------------------+------------------------------------------------------------+
| filename                         | directory                                                  |
+----------------------------------+------------------------------------------------------------+
| preview_image_5c795024ca7af.jpeg | theme/preview                                              |
| preview_image_5c795024dc145.jpeg | theme/preview                                              |
| refrigerationgauges.200x100.jpg  | catalog/product/r/e                                        |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/0b518a73ed92eecbe9790ec3a622cd2d/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/79cd194851544f88bafc552bf5216e5d/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/12479842094003d6e8198e99b15d1aad/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/aefcd4d8d5c59ba860378cf3cd2e94da/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/93545884bf1d6d40eefc44b2e3958bec/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/3e75d17be04cbebee9a78c36b24b6eea/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/07aa3e3829adcf2640e41cdeee09b5bb/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/19796d7732cc0b8676f199bbe04c742a/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/08a0b36ebc62d1aabd4a717a82ad731c/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/da51c19fe8c21b068c481cfb28c65074/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/c430e3e26517992a27628ce5995d6769/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/6b1c09900b407c50fce2db5e66ebc123/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/10f519365b01716ddb90abc57de5a837/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/ecd051e9670bd57df35c8f0b122d8aea/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/f9bb4946b08eb56afc1e83d5b55bf276/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/e4d64343b1bc593f1c5348fe05efa4a6/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/f0eed8c49b05a5a279de03029e69388c/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/66336d755d72c30139c8c62793bff496/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/a8be410535bd10951f8c121e888302ad/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/35d197d4a86bb7af9ea497ddcb0426c9/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/d664e1acc15f6090304d588386caff1d/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/411ddd1079653e9744172963f7b57a7a/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/647c742965ace57b5484ad847e8cd3cc/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/add01ceb5699006aaeaaa55353b05d62/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/e97e30f46ad3af2c4402aa864120074b/r/e |
| refrigerationgauges.200x100.jpg  | catalog/product/cache/36fa622c226395c7a03aea76cb6f177a/r/e |
+----------------------------------+------------------------------------------------------------+
www-data@dev:~/dev1$ php bin/magento catalog:images:resize
1/1 [============================] 100% < 1 sec 36.0 MiB        | /r/e/refrigerationgauges.200x100.jpg
Product images resized successfully.
```

### Actual result (*)
```
www-data@dev:~/dev2$ find pub/media -name *.jpg
www-data@dev:~/dev2$ mysql dev2_magento -e "select filename,directory FROM media_storage_file_storage"
+----------------------------------+---------------------+
| filename                         | directory           |
+----------------------------------+---------------------+
| preview_image_5c79502710eae.jpeg | theme/preview       |
| preview_image_5c7950272dcaf.jpeg | theme/preview       |
| refrigerationgauges.200x100.jpg  | catalog/product/r/e |
+----------------------------------+---------------------+
www-data@dev:~/dev2$ php bin/magento catalog:images:resize
File '/var/www/dev2/pub/media/catalog/product/r/e/refrigerationgauges.200x100.jpg' does not exist.
```

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment]
Not able to use magento-engcom instances as I need DB and filesystem access to prove, but confirmed reproducable 100% on 2.3-develop vanilla instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98525` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment]
A quick look at the code on this. 2.3 processes the image cache differently to 2.2.

In 2.3 it now uses an Observer that triggers after product save. This then uses \Magento\MediaStorage\Service\ImageResize.php to generate the cached images on the filesystem.

HOWEVER

The above function was implemented without any consideration for the database media storage mode. Its not a bug, it is completely missing the functionality to handle images in the database. The ImageResize class assumes everything is filesystem based.

**Comment by riccardougolini** [comment]
hi,
i tried to reproduce it on Magento 2.3: i followed the steps but seems to be fine on this version. @gwharton have you tried to clean cache after changing db settings? @magento-engcom-team

**Comment by gwharton** [comment]
@riccardougolini Yeah, ive tried clearing cache. See the below video.

https://www.youtube.com/watch?v=2jFL7l1fZGs

If you apply #21605 and rerun the test then you make some progress and the image is copied locally and displays correctly on the admin page, but the cached images are still not pre-processed, as per this bug.

**Comment by riccardougolini** [comment]
@gwharton I tried again following your video but seems to be ok. Can i've a copy of your config.php? is a clear magento 2.3 installation?

**Comment by gwharton** [comment]
Yeah, I'm not sure why you can't reproduce it. I dont do anything special in my test deployments.

The steps in my install script are

```
git clone --branch $tag $repo $folder
cd $folder
git config credential.helper store
composer install
php bin/magento setup:install --db-host $dbhost --db-name $database --db-user $user --db-password $passwd --use-secure 1 --base-url $url --base-url-secure $url --use-secure-admin 1 --timezone Europe/London --language en_GB --currency=GBP --admin-user $user --admin-password $passwd --admin-email $email --admin-firstname Admin --admin-lastname Admin --use-rewrites 1 --backend-frontname admin
mysql $database -e "UPDATE admin_user SET interface_locale='en_GB' WHERE user_id = '1'"
```

**Comment by gwharton** [comment]
Code inspection shows the following series of events when saving product in Database Media Storage Mode.

Create new product and add new image
image.jpg is created in database with filename tmp/catalog/product/i/m/image.jpg
image.jpg is created in pub/media with filename tmp/catalog/product/i/m/image.jpg

Save Product
image.jpg is renamed in database from tmp/catalog/product/i/m/image.jpg to catalog/product/i/m/image.jpg
tmp/catalog/product/i/m/image.jpg is deleted from pub/media
Image resize command is called which fails as it checks for the presence of catalog/product/i/m/image.jpg in pub/media which does not exist.

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#21605 by @gwharton in 2.3-develop branch
Related commit(s):
 - [5f6e24fa20087d3d37063bfab77ffca42625c9c5](https://github.com/magento/magento2/commit/5f6e24fa20087d3d37063bfab77ffca42625c9c5)

The fix will be available with the upcoming 2.3.3 release.

**Comment by gwharton** [comment]
Incorrectly closed. Reopened.

**Comment by gwharton** [comment]
See #23596
