### ISSUE TITLE
Grouped Product getParentIdsByChild() returns row_id of catalog_product_entity instead of entity_id

### ISSUE THREAD

**Issue by sean-breeden** [magento/magento2#21556]
### Preconditions (*)
1. Magento EE 2.2.2

### Steps to reproduce (*)
1. Create a bundled product. Add a couple of products to it.
2. Find your grouped product ID the table `catalog_product_link`
3. Add another product to the bundle
4. Go back to the table `catalog_product_link` and locate your grouped product
5. Now view `catalog_product_entity` for the `product_id` from `catalog_product_link`. It is the `row_id` instead of `entity_id`.
6. The method getParentIdsByChild() is returning the `entity_id` which is useless for acting on the returned data. `product_id` should equal the `entity_id` of `catalog_product_entity` instead of the `row_id`. 

### Expected result (*)
1. See Actual Result below. 

### Actual result (*)
1. 
![grouped-m2-bug](https://user-images.githubusercontent.com/19490078/53700687-ed8e8180-3dc2-11e9-89f7-238a6e4a3168.jpg)

**Comment by magento-engcom-team** [comment]
Hi @sean-wcb. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sean-wcb do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @sean-wcb thank you for you report, this issue has already fixed in 2.3-develop branch and will be available on 2.3.2 release.
 GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Comment by nbennett25** [comment]
I am able to reproduce this issue with EE v 2.4.2-p1.

**Comment by JulianCampolongo** [comment]
were you able to solve it? The same thing is happening to me and I don't know how to continue.

**Comment by alexander-vodov** [comment]
Same issue on Adobe Cloud 2.4.6-p5
