### ISSUE TITLE
sales address attribute is not copy to customer address as a custom attribute

### ISSUE THREAD

**Issue by tnsezer** [magento/magento2#21552]
### Preconditions (*)

1. Magento CE 2.2.5

### Steps to reproduce (*)

1. create custom attribute for customer address, sales_address and quote_address for example "my_attribute"
2. create fieldsets.xml and define the attribute

```
        <fieldset id="order_address">
            <field name="my_attribute">
                <aspect name="to_customer_address" />
            </field>
        </fieldset>
```

3. create extension_attributes.xml

```
    <extension_attributes for="Magento\Customer\Api\Data\AddressInterface">
        <attribute code="my_attribute" type="string" />
    </extension_attributes>
    <extension_attributes for="Magento\Sales\Api\Data\OrderAddressInterface">
        <attribute code="my_attribute" type="string" />
    </extension_attributes>
```

4. copy field via objectCopyService from "order_address" to "to_customer_address"

```
$addressData = $this->objectCopyService->copyFieldsetToTarget(
                'order_address',
                'to_customer_address',
                $address,
                []
            );
```
5. create a customer address
`$this->addressFactory->create(['data' => $addressData]);`

4. then try to get custom attribute via getCustomAttributes method
```
$customerAddress = $this->addressFactory->create()->load($lastAddressId);
$customAttribute = $customerAddress->getCustomAttribute('my_attribute');
```

### Expected result (*)

1. my_attribute value

### Actual result (*)

1. null

It happens when placed order as a guest then click "Create Account", Magento run \Magento\Sales\Model\Order\OrderCustomerExtractor:extract method which copy address from order_address to customer_address via objectCopyService. After set your password and click create account button which runs \Magento\Customer\Model\Address:updateData method which gets address, to each pre-defined attributes and set them then to each customAttributes but it return empty array because of that bug issue. The attribute just could be reachable via _get method. Because the objectCopyService copy the attribute from data object to data object. It must be in custom_attribute object for customer address model.

**Comment by magento-engcom-team** [comment]
Hi @tnsezer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tnsezer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tnsezer** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @tnsezer. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by Alex-Lunkov** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment]
@tnsezer,

```
$customerAddress = $this->addressFactory->create(['data' => $addressData]);
```

This is not a proper way to load customer address.

**Comment by tnsezer** [comment]
@orlangur 

It is in magento core: Magento\Sales\Model\Order\OrderCustomerExtractor:extract method

**Comment by orlangur** [comment]
@tnsezer then please change steps as currently 5 and 6 should lead to actual result, not expected.

**Comment by tnsezer** [comment]
@orlangur  It already leads actual result. It is happening in magento 2 core I explained next to the steps. I just described bugs in the steps. It is also still continue for magento 2.3. I changed last steps and added load method. It would give same actual result by the way.

**Comment by fooman** [comment]
Just to note a custom attribute is not the same as an extension attribute.

**Comment by ghost** [comment]
Hi @tnsezer thank you for your report, extension attributes and custom_attribute are completely different, please refer to https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html

**Comment by tnsezer** [comment]
@fooman  @engcom-backlog-nazar I also can not reach the data via getExtensionAttribute. There are a bug issue.

**Comment by ghost** [comment]
@tnsezer you need to set extension_attributes. 
```
public function afterSave
(
    \Magento\Catalog\Api\ProductRepositoryInterface $subject,
    \Magento\Catalog\Api\Data\ProductInterface $entity
) {
    $extensionAttributes = $entity->getExtensionAttributes(); /** get current extension attributes from entity **/
    $ourCustomData = $extensionAttributes->getOurCustomData();
    $this->customDataRepository->save($ourCustomData);

    return $entity;
}
```
@tnsezer https://devdocs.magento.com/guides/v2.3/extension-dev-guide/extension_attributes/adding-attributes.html
