### ISSUE TITLE
Configuration for path: "customer/account_share/scope" doesn't exist

### ISSUE THREAD

**Issue by FuzzyPones** [magento/magento2#21574]
### Preconditions (*)

1. Magento version 2.3.0
2. Get the configuration path for "Share Customer Accounts" from : https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-most.html

### Steps to reproduce (*)

1. Fresh checkout and setup based on magento installation guide https://devdocs.magento.com/guides/v2.3/install-gde/prereq/nginx.html
2. Execute: bin/magento config:show customer/account_share/scope

### Expected result (*)

1. Show value of config

### Actual result (*)

1. Configuration for path: "customer/account_share/scope" doesn't exist

**Comment by magento-engcom-team** [comment]
Hi @FuzzyPones. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@FuzzyPones do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @FuzzyPones thank you for you report, please uncheck checkbox in store->configuration->customer configuration.
![deepinscreenshot_select-area_20190305125906](https://user-images.githubusercontent.com/40756439/53800953-96191e80-3f46-11e9-8e29-8cee2bb37584.png)

**Comment by FuzzyPones** [comment]
Okay, can this error be a bit more declarative then? How are improvements being issued?

Doesn't exist != unavailable due to checkboxes being ticked
