### ISSUE TITLE
Magento 2.3 - Phone number, fax and company not showing on the signup page

### ISSUE THREAD

**Issue by joeyazar** [magento/magento2#21571]
### Preconditions (*)

1. Magento 2.3
2. Front end Registration page

### Steps to reproduce (*)

1. Access the backend, store > configuration > customer configuration
2. change the phone number, fax and company to required or optional

### Expected result (*)

1. When user clicks on the SIgn Up button he should be able to see all the required and optional fields in addition to the Name, email and password

### Actual result (*)

1. Phone number, Fax and Company are not showing at all in the form. I tried to put it required then optional, but same result. I m clearing the cache always.
2.  I tried it on a clean install of magento, without any theme and i end up with the same result. Fields not showing.

![image](https://user-images.githubusercontent.com/36643877/53787361-4f67fc00-3f27-11e9-9e31-de104cf0d5e2.png)
![image](https://user-images.githubusercontent.com/36643877/53792109-978d1b80-3f33-11e9-8ce7-80679033a12f.png)

**Comment by magento-engcom-team** [comment]
Hi @joeyazar. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@joeyazar do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by joeyazar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @joeyazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @joeyazar, here is your [Magento instance](https://i-21571-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21571-2-3-develop.instances.magento-community.engineering/admin](https://i-21571-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by joeyazar** [comment]
Hi. Sorry i'm new to Magento and it might be a silly question from my end but i can't figure it out.
Same issue here. The "Show Telephone" is required and "Show Company" is optional in the back end, and still they don't appear in the sign up page in the front end.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @joeyazar thank you for you report, this settings allow you to add required field on customer account information, and not on "customer account create", this fields appears on customer checkout, and in customer account.

**Comment by joeyazar** [comment]
Thank you for your reply. 
But why when i select from the same list Suffix, Prefix, Middle name, date of birth, vat and gender they all appear in the account sign up.
![image](https://user-images.githubusercontent.com/36643877/53792029-6f052180-3f33-11e9-96b7-af45f896aa6c.png)

**Comment by donniesg** [comment]
@engcom-backlog-nazar This should not be classify as a non-issue. I agree with joeyazar. 

Based on the official Magento Docs at https://docs.magento.com/m2/ce/user_guide/customers/customer-account-configuration.html

The customer account settings **determine the information that is collected during customer registration**, and the experience that customers have during the process. Customer configuration settings include:

Account Scope
Login Landing Page
New Account Options
**Name and Address Options**
Password Options
Customer Session Lifetime

It is clearly stated that the settings determine the information that is collection during customer registration. Phone number, Company and fax number goes under the "Name and Address Options" and should behave the same as the other fields in the same section i.e., Prefix, Suffix, Middle Name, DOB, VAT Number and Gender. 

This behavior is reproducible in Magento CE 2.2.5 and 2.2.6 as well.  There is clearly something wrong with this.
