### ISSUE TITLE
In admin area the Minimum Qty Allowed in Shopping Cart should be always less than the Maximum Qty Allowed in Shopping Cart

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#21578]
### Preconditions (*)

1. Simple Product with qty 100500 or Configurable option with visibility set to Catalog, Search

### Steps to reproduce (*)

1. Edit the product in Advanced Inventory set 
Minimum Qty Allowed in Shopping Cart to 5000
and set
Maximum Qty Allowed in Shopping Cart to 100
2. Click 'Done' and Save the product

### Expected result (*)

1. Cannot click 'Done' or 'Save'

### Actual result (*)

1. When trying to add the product to Cart from Storefront got a problem.
for 99:
Could not add the product with SKU configurable-product-option1 to the shopping cart: The fewest you may purchase is 5000.
for 5001:
Could not add the product with SKU configurable-product-option1 to the shopping cart: The most you may purchase is 100.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@TomashKhamlai do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by orlangur** [comment]
@TomashKhamlai such validation seems to be pretty useless to me. What is the problem with current system behavior?

**Comment by TomashKhamlai** [comment]
It's useless for me too but the problem is that we have ability to configure Magento to generate conflicting statements on Storefront and this problem will only appear if Merchant is not attentive.

This check looks so simple that I have never tried to break it before :)

**Comment by orlangur** [comment]
@TomashKhamlai everything can be implemented, just doubt such validation rule added would bring a lot of value :) Not closing though, maybe somebody will want to embody it into life.

**Comment by ghost** [comment]
Hi @TomashKhamlai thank you for you report, i dont think that we need add validation for this simple case. This is simple logic between min and max values.
