### ISSUE TITLE
Broken Tax Zones and Rates Search - SQLSTATE[42S22]

### ISSUE THREAD

**Issue by robyerevan** [magento/magento2#21587]
### Preconditions (*)

1. Magento 2.2.3

### Steps to reproduce (*)

1. Go to Admin -> Stores -> Taxes -> Tax Zones and Rates
2. Add New Tax Rate, save few tax rates
3.  Do combined search using **Tax Identifier = AL and State Region = AL** 

### Expected result (*)

1. Combined search executed and output is displayed to admin
2. Admin can continue using "Tax Zones and Rates" search again

### Actual result (*)

1. In production mode blank area displayed instead of grid, admin can not use "Tax Zones and Rates" search anymore until session/cookies cleared manually
![tax zones and rates taxes](https://user-images.githubusercontent.com/1753687/53847620-5104e480-3f66-11e9-89af-2efe912ef1e9.png)
2. MySQL error is thrown

> Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'region_name' in 'where clause', query was: SELECT COUNT(*) FROM `tax_calculation_rate` AS `main_table`
 LEFT JOIN `directory_country_region` AS `region_table` ON main_table.tax_region_id = region_table.region_id WHERE ((`main_table`.`code` LIKE '%Al%')) AND ((`region_name` LIKE '%AL%'))
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'region_name' in 'where clause'

**Comment by magento-engcom-team** [comment]
Hi @robyerevan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@robyerevan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by robyerevan** [comment]
This issue is similar to [issue 21521](https://github.com/magento/magento2/issues/21521) but it is not the same
they happen in 2 different pages "Tax Zones and Rates" and "Tax Rules"

**Comment by robyerevan** [comment]
@magento-engcom-team give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @robyerevan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @robyerevan, here is your [Magento instance](https://i-21587-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21587-2-3-develop.instances.magento-community.engineering/admin](https://i-21587-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by robyerevan** [comment]
> Hi @robyerevan. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @robyerevan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [x ]  no

**Comment by magento-engcom-team** [comment]
Hi @robyerevan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @robyerevan, here is your [Magento instance](https://i-21587-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21587-2-3-develop.instances.magento-community.engineering/admin](https://i-21587-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by robyerevan** [comment]
Won't reproduce on Magento ver. dev-2.3-develop

**Comment by dipti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce, here is your [Magento instance](https://i-21587-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21587-2-3-develop.instances.magento-community.engineering/admin](https://i-21587-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @robyerevan thank you for your report, this issue has already fixed in 2.3-develop and will be available on 2.3.2 release.
