### ISSUE TITLE
Newsletter subscription input box in footer: on iPad (9.7"), in portrait mode, placeholder text is not visible

### ISSUE THREAD

**Issue by dipti2jcommerce** [magento/magento2#21592]
### Preconditions (*)
Magento Open Source 2.3-develop
iPad emulation in Chrome 72
<img width="648" alt="screen shot 2019-03-06 at 17 50 57" src="https://user-images.githubusercontent.com/33287185/53894259-78c47d00-4038-11e9-84a2-2cdc0a754ad6.png">

### Steps to reproduce (*)
1. Open any Luma storefront page on iPad (9.7")
2. Scroll down to newsletter subscription block in the global footer.

### Expected result (*)
The placeholder text in the box is fully visible:
![2019-03-06_13-25_advanced search](https://user-images.githubusercontent.com/18118638/53864778-62f09100-4013-11e9-8d0a-f465aad9deba.jpg)

### Actual result (*)
The text is cut off:
![2019-03-06_13-18_shopping cart](https://user-images.githubusercontent.com/18118638/53864721-35a3e300-4013-11e9-8a43-d328e0530f76.jpg)

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dipti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Al3ks73** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Al3ks73. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-21592-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21592-2-3-develop.instances.magento-community.engineering/admin](https://i-21592-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-21592-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21592-2-2-develop.instances.magento-community.engineering/admin](https://i-21592-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by oleksii-lunkov** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov, here is your [Magento instance](https://i-21592-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21592-2-3-develop.instances.magento-community.engineering/admin](https://i-21592-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Alex-Lunkov 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98586`, `MAGETWO-98587` were created

**Issue Available**: @Alex-Lunkov, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by afazcar** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
@afazcar thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by Iamwade** [comment]
@magento I am working on it

**Comment by Iamwade** [comment]
@dipti2jcommerce I investigated the problem and found that this problem is reproduced not only on the ipad.
The placeholder is cropped and on other devices at a resolution of 768 - 940. This problem can be solved by increasing the width of .block.newsletter from 34% to 42%. But I think this is a bad solution to the problem since, for other languages ​​in which the text is longer, it will also be cut off. I recommend using text-overflow: ellipsis;
It will automatically deliver "..." if the placeholder does not fit into the input.

**Comment by folektoras** [comment]
@magento I am working on it

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#25184 by @cstergianos in 2.3-develop branch
Related commit(s):
 - [7cc4507e664596e89c1d50ccc4757c16039f567f](https://github.com/magento/magento2/commit/7cc4507e664596e89c1d50ccc4757c16039f567f)
 - [4916152f76710695e6538dc679cf27870ead5afa](https://github.com/magento/magento2/commit/4916152f76710695e6538dc679cf27870ead5afa)
 - [991b9141060108420cec21d9ade2ace0d1313222](https://github.com/magento/magento2/commit/991b9141060108420cec21d9ade2ace0d1313222)
 - [459121b0bce215bdb9a0fd00d5d1f4475c0a2ef4](https://github.com/magento/magento2/commit/459121b0bce215bdb9a0fd00d5d1f4475c0a2ef4)
 - [8f50b4581177e3ef975f7730d77fb539caa47d31](https://github.com/magento/magento2/commit/8f50b4581177e3ef975f7730d77fb539caa47d31)

The fix will be available with the upcoming 2.3.4 release.
