### ISSUE TITLE
GraphQL not working on fresh install of 2.3

### ISSUE THREAD

**Issue by rossmc** [magento/magento2#21608]
### Summary
I'm trying to set use GraphQL on a fresh install of 2.3 so I can use it with PWA studio, but GraphQL is not working. It gives the following error.
`SyntaxError: Unexpected token < in JSON at position 0`

### Preconditions (*)

1. Magento 2.3
2. PHP 7.2
3. Set Magento to _developer mode_

### Steps to reproduce (*)

1. Followed the steps from the [devdocs](https://devdocs.magento.com/guides/v2.3/graphql/#how-to-access-graphql) to test graphql with the  ChromeiQL extension
2. Set Magento to _developer mode_

### Expected result (*)

1. Expected to see graphql result in the results panel of 

### Actual result (*)

1. Received the following error in the results panel 
`SyntaxError: Unexpected token < in JSON at position 0`
2. Checked the result in the response tab and found it was the html content of the homepage
<img width="1209" alt="screenshot 2019-03-06 at 22 56 42" src="https://user-images.githubusercontent.com/2452991/53916720-277db300-4063-11e9-9537-6a45d36c72c6.png">

**Comment by magento-engcom-team** [comment]
Hi @rossmc. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rossmc do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @rossmc thank you for you report, i'm not able to reproduce following steps you described, please recheck your configurations.
![deepin-screen-recorder_select area_20190307100221](https://user-images.githubusercontent.com/40756439/53941200-2d55b180-40c0-11e9-8f31-0238e6e83046.gif)

**Comment by rossmc** [comment]
@engcom-backlog-nazar 
Discovered the issue.  I installed magento with composer which have GraphQL modules remove by the replace array.
https://github.com/magento/magento2/blob/2.3-develop/composer.json#L160

I remove them from the replace array and ran composer update, and it now works :)
