### ISSUE TITLE
Magento 2.2.6 Unable to create a new image entry with SOAP method catalogProductAttributeMediaGalleryManagementV1Create

### ISSUE THREAD

**Issue by SEtela** [magento/magento2#21615]
### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Create a SOAP call for catalogProductAttributeMediaGalleryManagementV1Create.
2. Try to add a new image to an existing product. 

### Expected result (*)

1. The call creates a new image for the product and the image is visible in magento backend.

### Actual result (*)

1. The Create call returns:
[faultstring] => Argument 1 passed to Magento\Framework\Api\ImageContentValidator::isValid() must be an instance of Magento\Framework\Api\Data\ImageContentInterface, null given, called in {magento_root}/vendor/magento/module-catalog/Model/Product/Gallery/GalleryManagement.php on line 53

When examining GalleryManagement.php lines 48-55:

     48     public function create($sku, ProductAttributeMediaGalleryEntryInterface $entry)
     49     {
     50         /** @var $entry ProductAttributeMediaGalleryEntryInterface */
     51         $entryContent = $entry->getContent();
     52 
     53         if (!$this->contentValidator->isValid($entryContent)) {
     54             throw new InputException(__('The image content is not valid.'));
     55         }

the call should return an error text from line 54 if $entryContent argument isn't validated in isValid() function. Instead the argument ($entryContent) is null.

During the error we give the method an array:

```
$image_details = [
    'sku' => 'testproduct12345',
    'entry' => [
        'mediaType' => 'image',
        'label' => '',
        'position' => 0,
        'disabled' => false,
        'types' => [
            'image'
        ]
    ],
    'content' => [
        'base64EncodedData' => $img_encoded,
        'type' => 'image/png',
        'name' => 'imagetest.png'
    ]
];
```

The image is encoded with php function base64_encode. Same error happens if the image type is jpg.

**Comment by magento-engcom-team** [comment]
Hi @SEtela. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@SEtela do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @SEtela thank you for you report, magento supports only 7.1.3+ | 7.2.x- | --
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

**Comment by SEtela** [comment]
Hello @engcom-backlog-nazar the php version was incorrectly informed in the post by me. I checked the server end of magento and the php version there is 7.1.17. Could you please reopen the bug issue.

**Comment by ghost** [comment]
@SEtela ok, i'm will recheck if issue exist i will reopen.

**Comment by ghost** [comment]
@SEtela  i'm not able to reproduce following steps you described. on 2.3-develop branch, seems like you have null at this point.
![deepinscreenshot_select-area_20190307171021](https://user-images.githubusercontent.com/40756439/53966525-0321e500-40fc-11e9-9e47-3ad6a88579c4.png)

**Comment by importwholesales** [comment]
* this was my error
"content" was not in "entry"
and image/jpg needed to be image/jpeg

Not sure if you want to delete this or not.
sorry


I get this on 2.3 CE release

PHP 7.2.16 (cli) (built: Mar  5 2019 13:10:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.16, Copyright (c) 1999-2018, by Zend Technologies

CentOS Linux release 7.6.1810 (Core)

nginx version: nginx/1.12.2


2019/03/21 09:46:36 [error] 18577#0: *303 FastCGI sent in stderr: "PHP message: PHP Fatal error:  
Uncaught TypeError: Argument 1 passed to Magento\Framework\Api\ImageContentValidator::isValid() must be an instance of Magento\Framework\Api\Data\ImageContentInterface, null given, called in m2/vendor/magento/module-catalog/Model/Product/Gallery/GalleryManagement.php on line 56 and defined in m2/vendor/magento/framework/Api/ImageContentValidator.php:50
Stack trace:
#0 m2/vendor/magento/module-catalog/Model/Product/Gallery/GalleryManagement.php(56): Magento\Framework\Api\ImageContentValidator->isValid(NULL)
#1 [internal function]: Magento\Catalog\Model\Product\Gallery\GalleryManagement->create('12345222222', Object(Magento\Catalog\Model\Product\Gallery\Entry))
#2 m2/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#3 m2/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->proces" while reading response header from upstream, client: 10.10.10.1, server: m2, request: "POST /rest/V1/products/12345222222/media HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "m2"

here is my json
I also tried jpg in replace of jpeg
I also tried pasting this into the swagger URL for media

[json.txt](https://github.com/magento/magento2/files/2992317/json.txt)

**Comment by SEtela** [comment]
@importwholesales Thanks for your answer. We had the exact same error, added 'content' inside 'entry' array and now the image creating works.
