### ISSUE TITLE
[MFTF] Lack of Nginx configuration to run command.php

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#21613]
### Description (*)
In Magento Functional Testing Framework we have example .htaccess file for `magento2/dev/tests/acceptance/.htaccess.sample`, but there's no configuration for Nginx.

### Expected behavior (*)
There should be nginx.config.sample

### Benefits
Safe Nginx text environment

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lbajsarowicz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
HI @lbajsarowicz thank you for your report, for this small changes, please create  PR directly.
