### ISSUE TITLE
path error validation for setting values on store_config_data when path is greater than three levels

### ISSUE THREAD

**Issue by Salle79** [magento/magento2#21625]
### Description (*) (tested on pure magento)
A validator regarding amount of allowed path levels for when saving to store_config_data ($this->scopeConfig->setValue('path/to/value, "value") since more than three levels (three/level/path/to/value) breaks index=>value association when values are being read.

### Expected behavior (*)
When developer tries to set value with a invalid path Ie (too/many/levels/of/path/to/desired/value) a exception should be thrown explaining that the path being used will not work.

### Benefits
Magento will become more transparent since various versions of Magento2, allows this, even though it will break the system.

**Comment by magento-engcom-team** [comment]
Hi @Salle79. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Salle79 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @Salle79 thank you for you report, in magento we have more than 3 levels, and this works as expected.
![deepinscreenshot_select-area_20190307164132](https://user-images.githubusercontent.com/40756439/53964463-159a1f80-40f8-11e9-98e0-68c26393b02f.png)
