### ISSUE TITLE
Duplicate private_content_version cookie in POST response

### ISSUE THREAD

**Issue by ArtemLysak** [magento/magento2#21627]
### Preconditions (*)
1. Magento 2.3.0 - both Open Source and Commerce editions
2. FPC is enabled
2. Varnish selected as FPC processor

### Steps to reproduce (*)
1. Make any POST request to magento (add product to the cart, for example)

### Expected result (*)
There are **one** `private_content_version` cookie in magento response

### Actual result (*)
There are **two** `private_content_version` cookie in magento response with different values

### Technical details
Seems like `Magento\Framework\App\PageCache::process` calls two times:
`Magento\PageCache\Model\Controller\Result\VarnishPlugin::afterRenderResult` - calls in `Magento\Framework\App\Http::launch - 135`
`Magento\PageCache\Model\App\FrontController\VarnishPlugin::afterDispatch` - calls in 
`Magento\Framework\App\Http::launch - 139`

I assume that `Magento\PageCache\Model\Controller\Result\VarnishPlugin::afterRenderResult` should be deleted because we already set `private_content_version` cookie in `Magento\PageCache\Model\App\FrontController\VarnishPlugin::afterDispatch`

**Comment by magento-engcom-team** [comment]
Hi @ArtemLysak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ArtemLysak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @ArtemLysak thank you for you report, i'm not able to reproduce following steps you described, seems like this related to your configurations.
![DeepinScreenshot_select-area_20190415141632](https://user-images.githubusercontent.com/40756439/56128827-63bd0100-5f89-11e9-954a-5a35b3954b44.png)
