### ISSUE TITLE
Free Shipping Cart Price Rule Issue Magento 2.3.x

### ISSUE THREAD

**Issue by nickpiro** [magento/magento2#21637]
I'm not sure if this has been posted already, but we've been having an issue with cart price rules. We created a Cart Price Rule for Free Shipping for Matching Items Only. When you add an item to the cart that fits the criteria, free shipping is available. When you add a second product to the cart, one that is NOT a matching item, free shipping is still available. Please see below! Hopefully I explained enough.

### Preconditions (*)
1. Magento 2.2.5
2. Shipping Method: Free Shipping: Yes, Minimum Amount: 999999.99

### Steps to reproduce (*)

1. Create Yes/No Attribute 'Free Shipping' (free_shipping), Add to Attribute Set
2. Create Cart Price Rule with following settings:
Step 1
<img width="1764" alt="cart-price-rule-1" src="https://user-images.githubusercontent.com/36938969/54006643-311f1d80-412c-11e9-8e38-a8861676eaf6.png">
Step 2
<img width="795" alt="cart-price-rule-2" src="https://user-images.githubusercontent.com/36938969/54006653-3da37600-412c-11e9-8aa8-5b84a6f81018.png">
Step 3 - Free Shipping FOR MATCHING ITEMS ONLY
<img width="1101" alt="cart-price-rule-3" src="https://user-images.githubusercontent.com/36938969/54006662-42682a00-412c-11e9-8084-4c1948dfa577.png">

3. Add product and select 'Yes' on Free Shipping Attribute
<img width="443" alt="free-shipping-product" src="https://user-images.githubusercontent.com/36938969/54006708-75122280-412c-11e9-8d64-fc09448f8df5.png">

4. Add product with Free Shipping (Yes) to cart. Shipping is free.
<img width="160" alt="free-shipping-0" src="https://user-images.githubusercontent.com/36938969/54006791-c91d0700-412c-11e9-917c-dccaea06e8f1.png">

5. Add product with Free Shipping (No) to cart. Free Shipping is still available.

If you add the Free Shipping (Yes) product AFTER a non-free shipping product, it does not seem to cause an issue (at least it doesn't show free shipping as an option.) But if you add the Free Shipping item first, that is when the error occurs.

### Expected result (*)
1. When you add non-free-shipping item to cart AFTER Free Shipping item, Free shipping is no longer available.

### Actual result (*)
1. After adding Non-Free-shipping item, free shipping is still an option for entire cart instead of MATCHING ITEM ONLY.

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nickpiro do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by nickpiro** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nickpiro, here is your [Magento instance](https://i-21637-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-21637-2-2-5.instances.magento-community.engineering/admin](https://i-21637-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nickpiro** [comment]
I was able to reproduce the issue in vanilla 2.2.5

**Comment by sivaschenko** [comment]
#magettestfest19

**Comment by nickpiro** [comment]
Anyone? I would think more websites would have issues with free shipping being added to products that don't ship free. Surprised it's still an issue in 2.2.5.

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](https://i-21637-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21637-2-3-develop.instances.magento-community.engineering/admin](https://i-21637-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by NishaJangid** [comment]
Hello @magento-engcom-team I want to work on this issue. Can you please help how can I assign it to me ?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @Alex-Lunkov. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98795`, `MAGETWO-98796` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Rus0** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Rus0, here is your [Magento instance](https://i-21637-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21637-2-3-develop.instances.magento-community.engineering/admin](https://i-21637-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Rus0** [comment]
It is no longer reproducible in 2.3-develop:
![image](https://user-images.githubusercontent.com/6666392/54719907-b2f74980-4b23-11e9-9be2-5870e57c603d.png)
![image](https://user-images.githubusercontent.com/6666392/54719914-b7236700-4b23-11e9-8a84-c00492ddf84f.png)
![image](https://user-images.githubusercontent.com/6666392/54719917-b985c100-4b23-11e9-9505-d9f0829f6919.png)
![image](https://user-images.githubusercontent.com/6666392/54719930-c0accf00-4b23-11e9-917b-bc878ce03dda.png)

@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Rus0, here is your [Magento instance](https://i-21637-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21637-2-2-develop.instances.magento-community.engineering/admin](https://i-21637-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Rus0** [comment]
No longer reproducible in development branch.

There is nothing for a dev to do

**Comment by nickpiro** [comment]
What was changed/what is the fix?

**Comment by nickpiro** [comment]
@Rus0 what was the fix that was done? The other day when I tested in that branch it did not work and I am not the only one to check!

**Comment by ghost** [comment]
@Rus0  this is reproducible with coupon code , please try again.

**Comment by ghost** [comment]
@Rus0 
![DeepinScreenshot_select-area_20190321095917](https://user-images.githubusercontent.com/40756439/54739304-467e5800-4bc0-11e9-8df6-2b5c376e0bee.png)
![DeepinScreenshot_select-area_20190321100056](https://user-images.githubusercontent.com/40756439/54739305-467e5800-4bc0-11e9-940a-78f3c4febe50.png)

**Comment by nickpiro** [comment]
@engcom-backlog-nazar was the initial issue I found fixed? When I tested it on the develop branch on March 13th the issue was still there. Now when I check the dev branch it doesn't seem to be! If someone could direct me to what was done to fix it?

**Comment by ghost** [comment]
@nickpiro but when i try to reproduce this with coupon code issue is still here, Did you able to reproduce with coupon code ?

**Comment by nickpiro** [comment]
@engcom-backlog-nazar we don't use free shipping with coupon, but for us, we still don't have a fix for my initial issue. No one attached to the fix. I know for sure when I tested it on the vanilla 2.2 that my issue was happening. Now it doesn't seem to be happening! I'm confused. I still don't have a fix.

**Comment by nickpiro** [comment]
@engcom-backlog-nazar also, it seems I tested it in 2.2.5 vanilla and not the latest 2.2 develop branch. But is there a way for me to find what was updated between 2.2.5 and let's say later versions 2.2.6, 2.2,7?

**Comment by Rus0** [comment]
@engcom-backlog-nazar the issue was reported without coupon, I will check it out with the coupon.

@nickpiro  it'll be hard to track the changes, you can start in the commits in the SalesRule in the 2.2-develop: https://github.com/magento/magento2/commits/2.2-develop/app/code/Magento/SalesRule to see them, maybe in the error with coupon I will check it out

**Comment by gulshanchitransh** [comment]
I am working on this at #dmcdindia1

**Comment by Rus0** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by nickpiro** [comment]
Has this issue been resolved in any versions? Still an issue in 2.3.x

**Comment by nickpiro** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @nickpiro. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by nickpiro** [comment]
@magento-engcom-team never got my instance...
