### ISSUE TITLE
Fatal Error on Category page if the category has a description : Uncaught TypeError: preg_match() expects parameter 2 to be string, boolean given

### ISSUE THREAD

**Issue by 0-Sony** [magento/magento2#21632]
### Preconditions (*)

1. Magento 2.3.0
2. php 7.2.15

### Steps to reproduce (*)

1. Add a description to a category in the back office and save.
2. Go to the category page on front

### Expected result (*)

1. See the category page with the description

### Actual result (*)

1. "Fatal error: Uncaught TypeError: preg_match() expects parameter 2 to be string, boolean given in [site_root]/vendor/magento/module-catalog/Helper/Output.php on line 229"

A similar issue has been fixed [#20229](https://github.com/magento/magento2/issues/20229)

**Comment by magento-engcom-team** [comment]
Hi @0-Sony. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@0-Sony do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by 0-Sony** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @0-Sony. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @0-Sony, here is your [Magento instance](https://i-21632-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21632-2-3-develop.instances.magento-community.engineering/admin](https://i-21632-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 0-Sony** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by 0-Sony** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @0-Sony. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @0-Sony, here is your [Magento instance](https://i-21632-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21632-2-3-0.instances.magento-community.engineering/admin](https://i-21632-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 0-Sony** [comment]
I am not able to reproduce the issue on develop and master instance. I close the issue.

**Comment by 0-Sony** [comment]
@magento-engcom-team give me 2.3.1 master
