### ISSUE TITLE
CSV upload removing configurable_variations from configuarble products

### ISSUE THREAD

**Issue by tkymuk** [magento/magento2#21636]
### Preconditions (*)

1. Magento 2.3.0 CE running on siteground shared host.
2.

### Steps to reproduce (*)
1. I created a configurable product with 4 simple products as variations. I downloaded the CSV for these a template. Deleted the products on the site. Added 5 more configurable products with 4 simple products for each configurable. I uploaded this CSV to find that the simple products linked to the Configurables via configurable_variations i.e. sku=TK-BGSA-222-10,adult_boxing_glove_size=10 oz|sku=TK-BGSA-222-12,adult_boxing_glove_size=12 oz, were not linked and were seperate in the product view. I then downloaded the data for the products and found that there was no data in the configurable_variations. It looks like Magento has stripped the data out and ignored it. This raises an issue of how do you bulk upload configurable products?

### Expected result (*)

I expected configurable products with variations to be uploaded.

### Actual result (*)

It didn't happen. Variations were seperate from their configurable [parents.](url)

**Comment by magento-engcom-team** [comment]
Hi @tkymuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tkymuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by harshvardhanmalpani** [comment]
Yes, I was able to reproduce it on vanilla installation of Magento 2.2.3
Uploaded a CSV to generate 1 simple product 
`"sku","attribute_set_code","product_type","name","configurable_variations","configurable_variation_labels","visibility","price","product_online","product_websites","qty","is_in_stock","size"
"th3pirat3-dummy-product","Default","simple","dummy name for dummy product",,,"Catalog, Search",221,1,"base",34,1,
`
https://prnt.sc/mw7968


Uploaded a CSV to generate 2 new simple product and update previous one as configurable (with blank cell for price column)
`"sku","attribute_set_code","product_type","name","configurable_variations","configurable_variation_labels","visibility","price","product_online","product_websites","qty","is_in_stock","size"
"th3pirat3-dummy-product","Default","configurable","dummy name for dummy product","sku=th3pirat3-dummy-product-1,size=5|sku=th3pirat3-dummy-product-2,size=6","size=Ring Size","Catalog, Search",,1,"base",,1,
"th3pirat3-dummy-product-1","Default","simple","dummy name for dummy product-1",,,"Not Visible Individually",99,1,"base",2,1,5
"th3pirat3-dummy-product-2","Default","simple","dummy name for dummy product-2",,,"Not Visible Individually",129,1,"base",2,1,6
`
https://prnt.sc/mw79je


Uploaded a CSV to generate 2 new simple product and update previous one as configurable (with 0 as price)
`"sku","attribute_set_code","product_type","name","configurable_variations","configurable_variation_labels","visibility","price","product_online","product_websites","qty","is_in_stock","size"
"th3pirat3-dummy-product","Default","configurable","dummy name for dummy product","sku=th3pirat3-dummy-product-1,size=5|sku=th3pirat3-dummy-product-2,size=6","size=Ring Size","Catalog, Search",0,1,"base",,1,
"th3pirat3-dummy-product-1","Default","simple","dummy name for dummy product-1",,,"Not Visible Individually",99,1,"base",2,1,5
"th3pirat3-dummy-product-2","Default","simple","dummy name for dummy product-2",,,"Not Visible Individually",129,1,"base",2,1,6
`
https://prnt.sc/mw7a0t
https://prnt.sc/mw7ab8



====

[csv-all3.zip](https://github.com/magento/magento2/files/2951347/csv-all3.zip)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @tkymuk thank you for your report, issue already here -> https://github.com/magento-engcom/import-export-improvements/issues/90

**Comment by tkymuk** [comment]
@engcom-backlog-nazar is there a fix or a work around in place for this yet?

**Comment by harshvardhanmalpani** [comment]
@tkymuk can you check `type_id` and `has_options` in table `catalog_product_entity` for your configurable products?
I had a similar issue #21682  and  I worked around it using the following command
UPDATE `catalog_product_entity` SET `type_id` = "configurable" where sku in ("configurable-sku-1","configurable-sku-2","configurable_sku_3");

>use backticks around column and table names

**Comment by tkymuk** [comment]
@harshvardhanmalpani thanks for the reply...is this a code edit or a table in phpMyAdmin?

**Comment by harshvardhanmalpani** [comment]
table `catalog_product_entity`
check for the product which you are trying to update
