### ISSUE TITLE
Using two databases, one with the other without table_prefix

### ISSUE THREAD

**Issue by OvalMedia** [magento/magento2#21642]
### Summary (*)
magento 2.2.7

I created an additional custom database connection. While the magento database uses a table_prefix, the custom database does not. When accessing the custom database through custom models magento tries to access the tables with a prefix.

env.php:

```
'db' => [
	'table_prefix' => 'abc_',
	'connection' => [
		'default' => [
			'host' => 'localhost',
			'dbname' => 'db1',
			'username' => 'db1',
			'password' => 'pw1',
			'active' => '1'
		],
		'custom' => [
			'host' => 'localhost',
			'dbname' => 'db2',
			'username' => 'db2',
			'password' => 'pw2',
			'active' => '1'
		]
	]
],
```
I have looked all over the internet but nobdy seems to have a solution.

### Proposed solution
Since the table_prefix obviously seems to apply to all connections it might be useful to to have the setting on a connection basis instead for all connections globaly:

```
'db' => [
	'connection' => [
		'default' => [
			'host' => 'localhost',
			'dbname' => 'db1',
			'username' => 'db1',
			'password' => 'pw1',
			'active' => '1',
                        'table_prefix' => 'abc_',
		],
		'custom' => [
			'host' => 'localhost',
			'dbname' => 'db2',
			'username' => 'db2',
			'password' => 'pw2',
			'active' => '1',
                        'table_prefix' => '',
		]
	]
],
```

If there is another solution, I am all ears.

**Comment by magento-engcom-team** [comment]
Hi @OvalMedia. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@OvalMedia do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi  @OvalMedia   thank you for you report, It will be processed faster if you move this to https://github.com/magento/community-features

**Comment by OvalMedia** [comment]
I will do. But I think this is more of a bug than a feature request.
