### ISSUE TITLE
Different default ON_DELETE parameters in two classes

### ISSUE THREAD

**Issue by samuel27m** [magento/magento2#21645]
### Summary (*)

Function `Magento\Framework\DB\Ddl\Table::addForeignKey` has onDelete parameter default to null which leads to be set in the table as NO ACTION

Function `Magento\Framework\DB\Adapter\AdapterInterface::addForeignKey` has onDelete parameters default which leads to be set in the table as CASCADE

### Examples (*)

$connection is a `Magento\Framework\DB\Adapter\AdapterInterface` object in this example

`$connection->newTable('TEST')->addForeignKey('TEST_123', 'field', 'customer_entity', 'entity_id')`
vs 
`$connection->addForeignKey('TEST_123', 'TEST', 'field', 'customer_entity', 'entity_id')`

In the first example foreign key ON DELETE action gets set as NO ACTION
In the second example foreign key ON DELETE action gets set as CASCADE
Even though default parameter is being used, there are different outcomes depending on the function that you choose.

### Proposed solution

Make both default ON DELETE parameters as CASCADE or NO ACTION.
In my opinion it's better to change it on `Magento\Framework\DB\Ddl\Table` to CASCADE as the MYSQL adapter has this default behaviour.

**Comment by magento-engcom-team** [comment]
Hi @samuel27m. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@samuel27m do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
