### ISSUE TITLE
Datetime format error

### ISSUE THREAD

**Issue by garmentprinterink** [magento/magento2#21659]
### Preconditions (*)

1. Magento Open Souce 2.3
2.Linux server running CentOS release 6.10 (Final)

### Steps to reproduce (*)

1. Upgrade from Magento 2.2.5 to 2.3
2. Create a new product > Set Product as New from and to 
3. Click save.

### Expected result (*)

1. I expected the product to be saved. 
2. For the product to be labeled as new for the time period I selected.

### Actual result (*)

1. [Screenshots, logs or description]
2.Invalid input datetime format of value.
![image](https://user-images.githubusercontent.com/43342733/54039642-74f83e00-4191-11e9-8115-4190a347c2aa.png)

**Comment by magento-engcom-team** [comment]
Hi @garmentprinterink. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@garmentprinterink do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by garmentprinterink** [comment]
Yes, I was able to reproduce this error on a vanilla version of Magento.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-21659-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21659-2-3-develop.instances.magento-community.engineering/admin](https://i-21659-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @garmentprinterink 

The issue was reproduced in 2.3.0 but **fixed** in 2.3-develop. 

So, Please wait for a feature release 2.3.1. 

Thank you!

**Comment by garmentprinterink** [comment]
Thank you very much. Do you have any idea when 2.3.1 will be released?
