### ISSUE TITLE
\Magento\Framework\Data\Collection::clear does not clear the result for \Magento\Framework\Data\Collection::getSize

### ISSUE THREAD

**Issue by sergiynezbritskiy** [magento/magento2#21654]
:

### Preconditions (*)

1. Magento version: 2.2.5 - 2.2.7

### Steps to reproduce (*)

1. Create any instance of \Magento\Framework\Data\Collection. e.g. \Magento\Sales\Model\ResourceModel\Order\Collection
2. Get count for this collection, call getSize().
3. Change collection select. e.g. add some additional filter by calling \Magento\Framework\Data\Collection\AbstractDb::addFieldToFilter('entity_id', ['lt' => 1]) or \Magento\Framework\Data\Collection::addFilter
4. Call \Magento\Framework\Data\Collection::clear() in order to flush previous result
5. Get count for this collection, call getSize().

### Expected result (*)

1. The result should reflect added filters

### Actual result (*)

1. The result of getSize() method always remains the same after the first call, and ignores clear() method

**Comment by magento-engcom-team** [comment]
Hi @sergeynezbritskiy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sergeynezbritskiy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by sergiynezbritskiy** [comment]
#kharkivcd19

**Comment by sergiynezbritskiy** [comment]
The issue is fixed now, here is the PR https://github.com/magento/magento2/pull/21670

**Comment by magento-engcom-team** [comment]
Hi @sergeynezbritskiy. Thank you for your report. 
The issue has been fixed in magento/magento2#21670 by @sergeynezbritskiy in 2.3-develop branch
Related commit(s):
 - [2038d7d00ae6428fd4aea976f275ff01924eecee](https://github.com/magento/magento2/commit/2038d7d00ae6428fd4aea976f275ff01924eecee)
 - [71effbe9252a1a8a840860c102d02e690fbded29](https://github.com/magento/magento2/commit/71effbe9252a1a8a840860c102d02e690fbded29)
 - [eea6126c03b6bb807569b73b7141d74257883729](https://github.com/magento/magento2/commit/eea6126c03b6bb807569b73b7141d74257883729)

The fix will be available with the upcoming 2.3.2 release.
