### ISSUE TITLE
Saving product with options with thousands separator in price fails

### ISSUE THREAD

**Issue by MartinAarts** [magento/magento2#21650]
### Preconditions (*)

Magento 2.2.7
Set admin user locale to for example dutch
### Steps to reproduce (*)

1. Create a product with custom options
2. set price of custom option to 1000
3. Save product
4. open product again, and try to save.

### Expected result (*)

1. Product should save fine.

### Actual result (*)

1. When opening product for the second time, the price of the product has been changed to 1.000,00 and thus throws an error when trying to save.
2. products with a custom option with a negative price, also give an error. You enter them as -100 but when reopening a product it's shown as 100- and cannot be saved.
![schermafbeelding 2019-03-08 om 12 59 38](https://user-images.githubusercontent.com/22233203/54028197-88f96b00-41a4-11e9-93b3-960719a16680.png)
![schermafbeelding 2019-03-08 om 12 59 19](https://user-images.githubusercontent.com/22233203/54028198-89920180-41a4-11e9-8927-ca317874c77b.png)

**Comment by magento-engcom-team** [comment]
Hi @MartinAarts. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@MartinAarts do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by MartinAarts** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MartinAarts. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MartinAarts, here is your [Magento instance](https://i-21650-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21650-2-3-develop.instances.magento-community.engineering/admin](https://i-21650-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by MartinAarts** [comment]
Just reproduced this issue on 2.3 develop.
![schermafbeelding 2019-03-08 om 13 44 53](https://user-images.githubusercontent.com/22233203/54029352-65d0ba80-41a8-11e9-8390-9f7ccd1f5654.png)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98672`, `MAGETWO-98673` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by geet07** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @geet07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @geet07, here is your [Magento instance](https://i-21650-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21650-2-3-develop.instances.magento-community.engineering/admin](https://i-21650-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @MartinAarts. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24081` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by JohanCore** [comment]
Still having this issue in 2.4.3-p1
