### ISSUE TITLE
Advanced reports fails to export on certain operating systems

### ISSUE THREAD

**Issue by matthewhaworth** [magento/magento2#21653]
### Preconditions (*)

1. Clean install of Magento 2.3.0

### Steps to reproduce (*)

1. Enable the Magento Advanced Reporting cron job
2. Wait for the cron job to run

### Expected result (*)

1. The cron job should finish successfully 
2. Access to advanced reporting should therefore be granted (provided other conditions are satisfied).

### Actual result (*)

1. The cron job fails due to an infinite loop

This is due to the file ordering of scandir in magento/framework/Archive/Tar.php line 253. It _assumes_ that the result will provide the files in order so that '.' and '..' will be first. However as it specifies 'SCANDIR_SORT_NONE', this is not guaranteed. As a result, '.' and '..' directories are not removed by the subsequent array shift and the function continues to execute recursively resulting in file paths such as 

```
/tmp/analytics/tmp/././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././rating_option_votes.csv
```

**Comment by magento-engcom-team** [comment]
Hi @matthewhaworth. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@matthewhaworth do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by matthewhaworth** [comment]
I've found that this appears to have already been fixed here: https://github.com/magento/magento2/commit/f08a19d0ee62362dfb64596377fe786c3f95cd09
