### ISSUE TITLE
setup:static-content:deploy's `--symlink-locale` option does nothing

### ISSUE THREAD

**Issue by danemacmillan** [magento/magento2#21656]
Version: `2.2.7` vanilla install

Not only does the `--symlink-locale` option do nothing, it has no mention in the docs. In fact, there is just about no code in the core related to this functionality, beyond the constant assigned the option name. If this option is no longer valid, why do you keep it in the code?

😠 

I've made mention of this issue in #21655 as well.

**Comment by magento-engcom-team** [comment]
Hi @danemacmillan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@danemacmillan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @danemacmillan thank you for you report, 
![DeepinScreenshot_select-area_20190311104502](https://user-images.githubusercontent.com/40756439/54110724-ce0ede80-43ea-11e9-95dc-5531734fff1d.png)
this options uses, you may create issue on dev-docs. https://github.com/magento/devdocs

**Comment by danemacmillan** [comment]
@engcom-backlog-nazar 

This is exactly my point; your screenshot unwittingly demonstrates it. That is the `SYMLINK_LOCALE` constant that is assigned its option name, `symlink-locale`, then defined as an option in the `getBasicOptions` method, then nothing more is done. That option is never used anywhere. It's just a dud, doing nothing. It's literally just an option that does nothing. How, in your mind, does this become a devdocs issue? Should I make a commit to the devdocs that state, "This option literally does nothing. Pass it if you'd like, or don't. It could look cool if you do. We don't care--nothing matters anymore. No ones keeping score. La la la la. Cats have hair. Puddles are wet."

This issue has not been addressed. You know what the solution is? Remove the option, as it does nothing, or create the functionality that this option purports to do. Instead, you recommend adding this nothingburger of an option to the documentation? Could you personally demonstrate even less knowledge of the framework you manage? I don't think you've sunk quite as low as needed.

**Comment by okorshenko** [comment]
Hi @danemacmillan 
This constant was used [as a part of Quick Deploy](https://github.com/magento/magento2/commit/434441ded53f94fb4af98c6bbf655d124c2bf54a#diff-098f5c2b3fc174e29c76fc62b00c2586R121) which was desperate since 2.2.0 and removed [later](https://github.com/magento/magento2/commit/70502d64755ef50bfd9fd31a695dbdf37e840069)

Constant declaration is a leftover from this functionality. As @engcom-backlog-nazar suggested, feel free to create an issue or submit a PR to https://github.com/magento/devdocs to reflect that this option is not used anymore, as well as create PR to the magento2 repository to clean up the code

Also, please consider [Magento Code of Conduct](https://github.com/magento/magento2/wiki/Magento-Code-of-Conduct)

**Comment by ivankristic** [comment]
> This constant was used as a part of Quick Deploy which was desperate since 2.2.0 and removed later

This whole thing is _desperate_ unfortunately
