### ISSUE TITLE
Uncaught Error: Call to undefined method Magento\\Bundle\\Model\\Product\\Type::getConfigurableAttributeCollection()

### ISSUE THREAD

**Issue by ankit-root** [magento/magento2#21664]
**1) Summary of the issue**
 
    I have faced the below issue on Magento 2.2.6 before we have migration from M1.1.9 to M2.2.6
    When I added Configurable products on the cart then added Simple product on the cart will facing error but when we added Simple product on the cart then added Configurable product on the cart after working fine

**2) Information on your environment**
  - Magento 2.2.6 
  - Nginx and apache Server

**3) Steps to reproduce**
    1) Migrate 1.1.9 to 2.2.6
    2) first we add Bundle product on cart 
    3) second we add configurable product on cart 

**4) Expected results**
    - how to solve this issue and how to sure after migration, not breakup functionality?

**5) Actual results**
   - When we add Configurable products on the cart then add Simple product on the cart will facing error

     `PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Bundle\\Model\\Product\\Type::getConfigurableAttributeCollection() in /var/www/html/magentothird/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:53\nStack trace:\n#0 /var/www/html/magentothird/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\\ConfigurableProduct\\Helper\\Product\\Options\\Loader->load(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 /var/www/html/magentothird/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\\ConfigurableProduct\\Model\\Product\\ReadHandler->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#2 /var/www/html/magentothird/vendor/magento/framework/EntityManager/Operation/Read.php(112): Magento\\Framework\\EntityManager\\Operation\\Read\\ReadExtensions->execute(Object(Magento\\Catalog\\Model\\Product\\Interceptor), Array)\n#3 /var/www/html/magentothird/vendor/magento/framework/EntityManager/EntityManager.php(70): Magento\\Framework\\Ent in /var/www/html/magentothird/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php on line 53, referer: http://ehp2.root.com/ehp-configurable.html
`

**Comment by magento-engcom-team** [comment]
Hi @ankit-root. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ankit-root do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ankit-root** [comment]
> Hi @ankit-root. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @ankit-root do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [ ]  no

no

**Comment by magento-engcom-team** [comment]
Hi @ankit-root. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ankit-root, here is your [Magento instance](https://i-21664-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21664-2-3-develop.instances.magento-community.engineering/admin](https://i-21664-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @ankit-root , problems with data migration from 1.x must be reported in https://github.com/magento/data-migration-tool repository.
