### ISSUE TITLE
Category Layout Update XML not working in production

### ISSUE THREAD

**Issue by santhoshnsscoe** [magento/magento2#21689]
### Preconditions 
1. Magento 2.2.7
2. Production Mode

### Steps to reproduce 
1. In category admin page, got to Design >  Layout Update XML
2. Add custom layout xml code

### Expected result 
1. The xml layout changes should get updated in frontend

### Actual result 
1. Not layout updates are getting applied.
2. In developer mode, the layouts are working fine, but in production mode, it is not working.

**Comment by magento-engcom-team** [comment]
Hi @santhoshnsscoe. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@santhoshnsscoe do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @santhoshnsscoe thank you for you report, i;m not able to reproduce following steps you described, 
```
<referenceContainer name="columns.top">
    <referenceBlock name="page.main.title" remove="true" />
</referenceContainer>
```
![DeepinScreenshot_select-area_20190313094919](https://user-images.githubusercontent.com/40756439/54261817-689b2900-4575-11e9-856d-ff0a7bd8fcba.png)

**Comment by santhoshnsscoe** [comment]
@engcom-backlog-nazar are you checking it in production mode or developer mode. The problem only comes when it is in production mode. In developer mode, it works fine.

We have shifted the code to theme layout xml and it is now working in production also.

```
<referenceContainer name="main.content">
    <container name="l.subcategories.wrapper" htmlTag="div" htmlClass="l-subcategories-wrapper" before="columns">
        <block class="\Magento\Framework\View\Element\Template" name="l.subcategories" template="subcategories.phtml" />
    </container>
</referenceContainer>

```

**Comment by janmech** [comment]
Any news on that issue? I experience something similar: Some layout XMLs in a custom module are not loading in production mode, but in developer and standard mode they load as expected.
The issue appeared after upgrading from 2.2.7 to 2.2.9

**Comment by alexandrosk** [comment]
I'm experiencing a similar problem on Enterprise solution because of the From - To Date on custom layout update. Although enterprise won't let me change those fields :/
