### ISSUE TITLE
Currency sign for "Layered Navigation Price Step" is not according to default settings

### ISSUE THREAD

**Issue by dmak** [magento/magento2#21684]
### Preconditions (*)

1. Magento CE 2.7 or 2.3
2. Please set Base Currency = Euro
3. Please set Default Currency = Euro
4. Please set Allow Currency = Euro

### Steps to reproduce (*)

1. Go to catalog --> Categories --> Add Sub Category
2. Expand Display Settings
3. Check currency symbol in Layered Navigation Price Step 
 
### Expected result (*)

With these settings the currency displayed in Layered Navigation Price Step must be euro sign (€).

### Actual result (*)

With these settings the currency displayed in  Layered Navigation Price Step is incorrect: displays dollar sign ($), but expected euro sign (€):
![image](https://user-images.githubusercontent.com/366965/54115609-10391f80-43ed-11e9-987c-881f21caa891.png)

### Note (*) 

currency displayed in product (Price, Customizable Options → Option → Price) are correct.

**Comment by magento-engcom-team** [comment]
Hi @dmak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dmak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](https://i-21684-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21684-2-3-develop.instances.magento-community.engineering/admin](https://i-21684-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@hiren0241 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @hiren0241
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](https://i-21684-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21684-2-2-develop.instances.magento-community.engineering/admin](https://i-21684-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-21684-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21684-2-3-develop.instances.magento-community.engineering/admin](https://i-21684-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98953`, `MAGETWO-98954` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-21684-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21684-2-3-develop.instances.magento-community.engineering/admin](https://i-21684-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Shubham0492** [comment]
reproducible on 2.3-develop

**Comment by VladimirZaets** [comment]
Hi @dmak. Thank you for your report. 
The issue has been fixed in magento/magento2#24815 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [2c705123e2ea9f5fdb34fc89eaf568f2336c1239](https://github.com/magento/magento2/commit/2c705123e2ea9f5fdb34fc89eaf568f2336c1239)
 - [2a5c87ce994e8aa0e8fe206d0af0be64606bd5dd](https://github.com/magento/magento2/commit/2a5c87ce994e8aa0e8fe206d0af0be64606bd5dd)
 - [d3515492bc36c960ca41e201d06a81725df03b2b](https://github.com/magento/magento2/commit/d3515492bc36c960ca41e201d06a81725df03b2b)
 - [9c4c965d82a076be62667c38f70c81af3a71b7a9](https://github.com/magento/magento2/commit/9c4c965d82a076be62667c38f70c81af3a71b7a9)

The fix will be available with the upcoming 2.4.0 release.
