### ISSUE TITLE
Parameter length makes a mistake in isArrayLike function

### ISSUE THREAD

**Issue by ghost** [magento/magento2#21688]
### Summary (*)

Magento 2.3
The browser is Google Chrome
### Steps to reproduce (*)

I have a form in admin panel and it has JSON code after clicking on submit button

Then function "flatten" from file vendor/magento/magento2-base/lib/web/mage/utils/objects.js run

Then function "isArrayLike" from file vendor/magento/magento2-base/lib/web/underscore.js run
### Examples (*)
I showed the reproduced problem below.
This is an example of data of form and function isArrayLike. This function returns an incorrect value
As you see form data have a name of parameter "length". It did a mistake
```
var MAX_ARRAY_INDEX = Math.pow(2, 53) - 1;
  var isArrayLike = function(collection) {
    var length = collection && collection.length;
    return typeof length == 'number' && length >= 0 && length <= MAX_ARRAY_INDEX;
  };
isArrayLike({"id":"34","name":"Iris Workout Top-XS-Red","type":"simple","qty":"1.0000","product_id":"1421","parent_id":"33","parent_product_id":"1434","basePrice":0,"baseCurrency":"USD","price":0,"currency":"GBP","weight":13607760,"width":2032000,"length":3048000,"height":2540000,"sku":"WS03-XS-Red","is_use_box":false,"has_children":[]});
```
result: true
### Proposed solution

**Comment by magento-engcom-team** [comment]
Hi @Faradey. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Faradey do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99041`, `MAGETWO-99042` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by anzin** [comment]
#cdkyiv2019

**Comment by magento-engcom-team** [comment]
@anzin thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by atishgoswami** [comment]
I am working on this at #dmcdindia19

**Comment by atishgoswami** [comment]
Seems like the underscore.js library is working implementing a solution for this and have related issues opened, related to this bug.

Have to wait till they release a fix
