### ISSUE TITLE
Catalog price rules doesn't take effect

### ISSUE THREAD

**Issue by laladtn** [magento/magento2#21680]
### Preconditions (*)

1. Magento 2 EE ver. 2.2.5

### Steps to reproduce (*)

1. Marketing > Catalog Price Rules
2. Add new rule
3. Fill in Rule name, Select all in Websites and Customer Groups
4. Conditions: no conditions
5. Actions: Apply as percentage of original - Discount amount: 10%
6. Save
7. Flush cache 

### Expected result (*)

1. On front-end, product price is marked down 10% from the regular price

### Actual result (*)

1. On front-end, product price only display the regular price, the rule takes no effect

**Comment by magento-engcom-team** [comment]
Hi @laladtn. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@laladtn do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by gavinhoman** [comment]
@laladtn Did you notice if the 'status Active or Inactive' toggle is visible when you created the price rule? I was just about to raise a similar issue with v2.3.0 and for me, it is set to 'display:none' so the rule cannot be activated in the first place. I noticed this on 2.2.0 version and 2.2.7 version for other sites we look after.

![image](https://user-images.githubusercontent.com/1886820/54109748-7155f880-43d7-11e9-9269-66330cfc4f01.png)

**Comment by laladtn** [comment]
@gavinhoman I don't think there's any Status field when the rule is created in magento 2 EE but the "Schedule Update" feature.

**Comment by gavinhoman** [comment]
@laladtn is that by design then? It's in the schedule popout so by default it looks like the rule is 'inactive' and then only available to be 'active' if you set a start and end date via the scheduler?

Application of the rule would then depend on cron firing properly and front end caching refreshing.

**Comment by laladtn** [comment]
Yes I schedule the campaign and set the status to "acitve" already. I tried reindex, clear cache everything but nothing seems to work. 
![image](https://user-images.githubusercontent.com/40824750/54119660-7727fa00-4428-11e9-8f43-c2a19e171556.png)

In the Content Staging Dashboard, those campaigns are "Upcoming" and won't change to "Active" even though it's pass Start date
![image](https://user-images.githubusercontent.com/40824750/54119830-e271cc00-4428-11e9-8d58-0346c02b9416.png)

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @laladtn  GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
