### ISSUE TITLE
"Something went wrong while compiling generated code." when submitting package to marketplace

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#21681]
I'm posting this question in the GitHub issue tracker, because I feel it is the only place where I can get support from Magento core developers. Mainly because:

- The "Support" link when submitting an extension refers to the (more generic) marketplace help center.
- If I click on "Submit a ticket" on the marketplace help center, it simply redirects to the "default" help center (i.e.: I can not submit a ticket).
- If I scroll down through the topics I see "Can't find what you're looking for?", but no button/form or link whatsoever.

So having ranted that, this is what I'm running in to:

### Summary

I'm trying to submit an extension to the Magento Marketplace, but it fails on the "Installation & Varnish Test":

```
> php bin/magento deploy:mode:set production 
Enabling maintenance mode
Starting compilation
Something went wrong while compiling generated code. See the error log for details.
Disabling maintenance mode
Command returned non-zero exit code:
`/usr/bin/php -f /var/www/html/bin/magento setup:di:compile`
```

If I try this locally (in a vanilla installation), everything works as expected:

```
bin/magento deploy:mode:set production
Enabling maintenance mode
Starting compilation
Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 56.0 MiB%message% 0/7 [>---------------------------]   0% < 1 sec 56.0 MiBProxies code generation... 0/7 [>---------------------------]   0% < 1 sec 56.0 MiB
Proxies code generation... 1/7 [====>-----------------------]  14% 2 secs 60.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 60.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 29 secs 170.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 29 secs 170.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 30 secs 170.0 MiB
Application code generator... 3/7 [============>---------------]  42% 30 secs 170.0 MiB
Application code generator... 4/7 [================>-----------]  57% 1 min 192.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 1 min 192.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 1 min 210.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 1 min 210.0 MiB
Area configuration aggregation... 6/7 [========================>---]  85% 1 min 288.0 MiB
Interception cache generation... 6/7 [========================>---]  85% 1 min 288.0 MiB
Interception cache generation... 7/7 [============================] 100% 2 mins 288.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete

... etc ...
```

I found an older article on Stack Exchange (https://magento.stackexchange.com/questions/158910/errors-during-installation-submitting-package-to-magento-marketplace) of somebody with the same issue, and it seems that some core team members answered those. One of these answers was that a `system.log` should be available for download when submitting to the marketplace, but I don't see this anywhere.

I'm not sure what to do now. Can anyone shine some light on this? The problem is now that a black box at Magento is throwing an error and I have no idea what it could be. It could be a memory issue for as far as I know, nothing I can do something about :-(

**Comment by magento-engcom-team** [comment]
Hi @kanduvisla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kanduvisla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @kanduvisla thank you for your report,   I would recommend you post your question on the Magento forum or community slack
