### ISSUE TITLE
Magento 2.3.0 Newsletter Module Problem

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#21687]
### Preconditions (*)

1.  Magento 2.3.0

### Steps to reproduce (*)

1. Queue a newsletter to more than one subscriber. For example, 100.

### Expected result (*)

1. Default magento settings should send to 100 subscribers in 2 cron runs I believe. The observer indicates 3 batches of 20 per every cron run, which is by default 5 min for the newsletter module.

### Actual result (*)

1.  Look at queue process every 5-9 minutes, and only **1** contact is sent newsletter each run.
2.  This obviously makes the newletter module unusable unless sending to a very very small list.

**Comment by magento-engcom-team** [comment]
Hi @snoroozi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@snoroozi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ladle3000** [comment]
@magento-engcom-team give me a test instance please.

**Comment by ghost** [comment]
Hi @snoroozi thank you for you report, this actually non-issue if you want more the 20 clients per batch, you can create you own plugin to change subscribed per batch, thanks for collaboration :+1:
