### ISSUE TITLE
Existing simple product can not become configurable via csv Import

### ISSUE THREAD

**Issue by harshvardhanmalpani** [magento/magento2#21682]
### Preconditions (*)
Magento 2.2.3

### Steps to reproduce (*)
1. Create a simple product
2. Try to upload csv with product_type changed to configurable and 2 new products as its variants

### Expected result (*)
1. The previous product becomes configurable and has 2 variants

### Actual result (*)
All 3 products remain simple products and no link in between.

@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @harshvardhanmalpani. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@harshvardhanmalpani do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by harshvardhanmalpani** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @harshvardhanmalpani. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @harshvardhanmalpani, here is your [Magento instance](https://i-21682-2-2-3.instances.magento-community.engineering).
Admin access: [https://i-21682-2-2-3.instances.magento-community.engineering/admin](https://i-21682-2-2-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by harshvardhanmalpani** [comment]
Yes, I was able to reproduce it on vanilla installation of Magento 2.2.3
Uploaded a CSV to generate 1 simple product 

>"sku","attribute_set_code","product_type","name","configurable_variations","configurable_variation_labels","visibility","price","product_online","product_websites","qty","is_in_stock","size"
 "th3pirat3-dummy-product","Default","simple","dummy name for dummy product",,,"Catalog, Search",221,1,"base",34,1,

https://prnt.sc/mw7968


Uploaded a CSV to generate 2 new simple product and update previous one as configurable (with blank cell for price column)
>"sku","attribute_set_code","product_type","name","configurable_variations","configurable_variation_labels","visibility","price","product_online","product_websites","qty","is_in_stock","size"
"th3pirat3-dummy-product","Default","configurable","dummy name for dummy product","sku=th3pirat3-dummy-product-1,size=5|sku=th3pirat3-dummy-product-2,size=6","size=Ring Size","Catalog, Search",,1,"base",,1,
"th3pirat3-dummy-product-1","Default","simple","dummy name for dummy product-1",,,"Not Visible Individually",99,1,"base",2,1,5
"th3pirat3-dummy-product-2","Default","simple","dummy name for dummy product-2",,,"Not Visible Individually",129,1,"base",2,1,6

https://prnt.sc/mw79je


Uploaded a CSV to generate 2 new simple product and update previous one as configurable (with 0 as price)
>"sku","attribute_set_code","product_type","name","configurable_variations","configurable_variation_labels","visibility","price","product_online","product_websites","qty","is_in_stock","size"
"th3pirat3-dummy-product","Default","configurable","dummy name for dummy product","sku=th3pirat3-dummy-product-1,size=5|sku=th3pirat3-dummy-product-2,size=6","size=Ring Size","Catalog, Search",0,1,"base",,1,
"th3pirat3-dummy-product-1","Default","simple","dummy name for dummy product-1",,,"Not Visible Individually",99,1,"base",2,1,5
"th3pirat3-dummy-product-2","Default","simple","dummy name for dummy product-2",,,"Not Visible Individually",129,1,"base",2,1,6

https://prnt.sc/mw7a0t
https://prnt.sc/mw7ab8



====

[csv-all3.zip](https://github.com/magento/magento2/files/2951347/csv-all3.zip)

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21682-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21682-2-3-develop.instances.magento-community.engineering/admin](https://i-21682-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
HI @harshvardhanmalpani thank you for you report, this is expected behavior, and its not best practice to create configurable via import, please use API.

**Comment by harshvardhanmalpani** [comment]
How is this expected behavior?
The type_id in catalog_product_entity changes from simple to configurable when we create configurable products manually from Magento Admin UI, same should happen on CSV upload.
Best practice or not, if a feature is available for use, people are going to use it.

I tried using API,
POST xxx/rest/all/V1/configurable-products/th3pirat3-dummy-product/options
with payload
`{
  "option": {
    "attribute_id": "280",
    "label": "Size",
    "position": 0,
    "is_use_default": true,
    "values": [
      {
        "value_index": 1204
      }
    ]
  }
}`
I received option_id 242 which was present in catalog_product_super_attribute table
But when I tried
POST xxx/rest/all/V1/configurable-products/th3pirat3-dummy-product/child
with payload
`{
	"childSku": "th3pirat3-dummy-product-1"
}`
I received **Parent product does not have configurable product options** error.
because `type_id` and `has_options` remained "simple" and "0" in `catalog_product_entity`

**Comment by tkymuk** [comment]
Is there a working fix for this?

**Comment by harshvardhanmalpani** [comment]
@engcom-backlog-nazar How is an end user supposed to use API, not every store manager can use API unless someone prepares everything about it and then provide them as a solution. If not CSV, what all bulk import options are available to a regular store manager?
