### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by netzwelt-nishu** [magento/magento2#21707]
After Migration to Magento 2, I am facing order created at date different in admin as compared to magento1. 

### Preconditions (*)

1. Magento version (2.3.0)
2. Timezone set to Europe/Budapest
3. Order time is same in both the databases;

### Steps to reproduce (*)

1.   try to check order date in magento admin.

### Expected result (*)

1. Order date should be same like Magento 1. 

### Actual result (*)

1. Both the dates are different and i hour difference because of timezone.

**Comment by magento-engcom-team** [comment]
Hi @netzwelt-nishu. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@netzwelt-nishu do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @netzwelt-nishu 
Thank you for your report. If you have issues related to data migration, feel free to report it on the https://github.com/magento/data-migration-tool repository. Otherwise, your report might be lost on magento2 repository. 

Also I would recommend you post your question on the Magento forum or community slack

**Comment by netzwelt-nishu** [comment]
This issue is not related to Data migration, there is some issue related to timezone settings in Magento 2.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21707-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21707-2-3-develop.instances.magento-community.engineering/admin](https://i-21707-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by netzwelt-nishu** [comment]
Hi @engcom-backlog-nazar ,

are you able to reproduce this issue or any solution did you find for the same. Please let me know..

**Comment by cscd98** [comment]
https://github.com/magento/magento2/issues/13773
