### ISSUE TITLE
Adding a child product to a grouped product removes other child product

### ISSUE THREAD

**Issue by niclashoyer** [magento/magento2#21706]
### Preconditions
1. Magento 2.2.5

### Steps to reproduce
1. Add a grouped product
2. Add 42 child products to this products
3. Add another child product

### Expected result
1. 43 childs should be assigned

### Actual result
1. 42 products are assigned

It seems that the relations are deleted randomly. We are currently facing this on a production installation and try to reproduce on a test installation. This currently affects all grouped products. Changing PHP variables like `memory_limit` or `max_input_vars` has no effect.

**Comment by magento-engcom-team** [comment]
Hi @niclashoyer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@niclashoyer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by niclashoyer** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @niclashoyer. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @niclashoyer, here is your [Magento instance](https://i-21706-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-21706-2-2-5.instances.magento-community.engineering/admin](https://i-21706-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by niclashoyer** [comment]
Here is a CSV file that will add 50 simple products and a grouped product with 42 associated products: 
[42products.zip](https://github.com/magento/magento2/files/2956139/42products.zip)

Unfortunately we are not yet able to reproduce this on the clean Magento instance. Is there anything we can do to further debug this?

**Comment by niclashoyer** [comment]
We got a little further. It may be a caching and/or admin issue. We noticed that the entries in the `catalog_product_link` table are always correct. But sometimes products are missing in the admin in the section of the linked products.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @niclashoyer thank you for you report, this issue is not reproducible on 2.2-develop and 2.3-develop branches.
