### ISSUE TITLE
magento 2.2.5 lots of catalogrule_product_temp tables makes database huge

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#21705]
### Preconditions (*)
magento 2.2.5 on apache and php 7.1

### Steps to reproduce (*)
Just use the store, I don't know what exactly triggers the creation of all these tables

### Expected result (*)
database should keep reasonable dimensions and have only normal tables

### Actual result (*)
Database gets huge: it's all clogged by catalogrule_product_tempX (where X is a random string of number and characters, eg: catalogrule_product_temp002521f3): these tables are all empty but they keep getting added and it's making impossible to simply backup the database.

Is it safe to delete those empty tables?
is there a way to avoid the issue?

**Comment by magento-engcom-team** [comment]
Hi @LouNik1984. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LouNik1984 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LouNik1984** [comment]
"Please make sure that the issue is reproducible on the vanilla Magento instance following Steps to reproduce."

I cannot ask for a vanilla instance as I cannot see the database of the vanilla instance: from backend/frontend of magento everything seems to be fine, this only affects the tables in database and I cannot see the database of the vanilla instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
hi @LouNik1984 thank you for you report, i'm not able to reproduce following steps you described, on clean 2.3-develop instance, this temp, table may be created with some of yours custom modules, but on clean magento  this tables always  deleted. Seems like this already fixed in 2.2-develop and 2.3-develop branches

**Comment by LouNik1984** [comment]
HI, I have tested both a previous version (2.2.2) and subsequent versions (2.2.6, 2.2.7) and none seems to have this issue, but every 2.2.5 version I have installed and tested has this issue. So this is a problem of all 2.2.5 versions: those table are not deleted. Can you point me a commit where this issue is solved? So I can try it on my test install and check whether it works. Thank you

**Comment by heyepic** [comment]
I also have a HUGE database full of catalogrule_product__temp tables. I cloned my live site and deleted these tables via phpmyadmin on my clone and everything seems fine. Question is - why are these not wiping after a catalog/cart rule is over / not active? Are these safe to delete?

![Capture](https://user-images.githubusercontent.com/12517908/55896586-413f7800-5b84-11e9-966d-f4cec88c2b23.JPG)

**Comment by santibm** [comment]
We are having this issue with magento 2.2.6 too, for the moment we deleted all the temp tables

**Comment by paul-blundell** [comment]
We are seeing this same issue on 2.2.7. We had nearly 10,000 of these temp tables created!

**Comment by torykepler** [comment]
We've got this same issue using 2.2.6.  22GB of wasted disk space because of these temp tables.

**Comment by Arul2020** [comment]
The same issue exists on Magento 2.4.0.

**Comment by markojak** [comment]
Why is this issue closed when it's an ongoing issue!
