### ISSUE TITLE
Homepage 404

### ISSUE THREAD

**Issue by robert-schmidt** [magento/magento2#21703]
### Preconditions (*)

1. Magento 2.3
2. PHP 7.2, Apache 2.4, redis, plesk

### Steps to reproduce (*)

1. The homepage turns into the 404 page. It happens randomly, analysing the input I have so far (nothing in the logs, no empty rows in the url_rewrite table). It comes back after clearing the cache. I could not find a way to reproduce it. 
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. No 404.

### Actual result (*)

1. [Screenshots, logs or description]
2. 404.

**Comment by magento-engcom-team** [comment]
Hi @robert-schmidt. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@robert-schmidt do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @robert-schmidt thank you for your report, we cannot accept issue which "I could not find a way to reproduce it." so please find clearly steps to reproduce and then reopen issue. thank you

**Comment by robert-schmidt** [comment]
I truly understand, but that's the only defining statement, atm. 

"Vanilla magento"... that's a broad way to put it. But impossible for me to achieve it now, considering the website is live and money on advertising are being spent every day. It did not happen during development though.

It seems I'm not the only one having this issue though: 
- https://community.magento.com/t5/Magento-2-x-Technical-Issues/Whoops-our-bad-error-on-main-store-page-every-day/td-p/116724 
- https://magento.stackexchange.com/questions/257232/magento-2-3-homepage-redirect-to-404-page-not-found

But I'm guessing it's not officially an issue until somebody finds a way to reproduce it.

**Comment by ghost** [comment]
@robert-schmidt  https://github.com/magento/magento2/issues/21299

**Comment by miteshdhaduk** [comment]
Hello @engcom-backlog-nazar 

I also face this type of issue on the homepage only.

Magento2.3 - My site homepage gives 404 page not found an error and it is randomly generated issue. All other pages of the site are working properly. After a clear page cache, it is working properly. And also I got this problem in my other 2 sites.

So please reopen it and find a solution to this issue.

**Comment by lexiconnect** [comment]
We also have this issue on one of our Magento 2.3 instances.  I have just uploaded some more advanced pricing via the import and the site has 404 error again.  Clearing cache fixed the issue.

**Comment by miteshdhaduk** [comment]
@engcom-backlog-nazar Can not possible to reproduce this issue. Just because of it is randomly generated issue. And many of occurred this type of issue in Magento 2.3(Community Edition).

So please find something on this issue.

**Comment by ghost** [comment]
@robert-schmidt issue already created and have a Pull request please refer to  https://github.com/magento/magento2/issues/21299
