### ISSUE TITLE
Configurable product price after index is always zero

### ISSUE THREAD

**Issue by datwiki** [magento/magento2#21720]
Summary: Configurable product price after index is always zero

Environment: Magento CE 2.3

Steps to reproduce:
1. Create a Configurable Product with some Child Products
2. Set discount 50% to all Childs
3. Run reindex
4. Check table catalog_product_index_price

Expected Result:
min_price, max_price, final_price have value

Actual Result:
only min_price, max_price work, final_price always get zero

- We will need the final_price to has value so we can sort by Highest Discount

We tried to take a look at vendor/magento/module-catalog/Model/ResourceModel/Product/Indexer/Price/Query/BaseFinalPrice.php and observe:

$select->columns(
            [
                //orig_price in catalog_product_index_price_final_tmp
                'price' => $connection->getIfNullSql($price, 0),
                //price in catalog_product_index_price_final_tmp
                'final_price' => $connection->getIfNullSql($finalPrice, 0),
                'min_price' => $connection->getIfNullSql($finalPrice, 0),
                'max_price' => $connection->getIfNullSql($finalPrice, 0),
                'tier_price' => $tierPrice,
            ]
        );

All the "0" look suspicious. Please help.

**Comment by magento-engcom-team** [comment]
Hi @datasiantech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@datasiantech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no
