### ISSUE TITLE
Ability to configure Google reCaptcha in 2.3+ to work with custom submit forms and ajax/controller requests.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/magento2#21727]
### Description (*)
Support for Google reCAPTCHA to be configured on custom forms and ajax requests/controllers.

### Expected behavior (*)
Admin could add Url's to enable it on and selectors for the forms to secure.

![image](https://user-images.githubusercontent.com/1968109/54253730-6f499080-45b5-11e9-8bea-c6a212137345.png)

Example: See [Amasty's Invisible Captcha](https://amasty.com/google-invisible-recaptcha-for-magento-2.html)

### Benefits

This would allow admins to easily secure their other custom submission forms from various modules.

### Additional information

Magento 2.3+

Please correct me if I am mistaken and this is already a feature, I could not find a way in the GUI to do it.
https://docs.magento.com/m2/ce/user_guide/stores/security-google-recaptcha.html

**Comment by magento-engcom-team** [comment]
Hi @LiamKarlMitchell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LiamKarlMitchell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @LiamKarlMitchell 
First call the Google recaptha JavaScript file in your header. Fix the recaptcha Js in your individual layout file as coded mentioned below:

```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">

<head>

<script src="https://www.google.com/recaptcha/api.js" src_type="url" />

</head>

</page>
```
Then add the below code in your custom form before the end of the </form> tag. (to display captcha in the bottom)

`<div class="g-recaptcha" data-sitekey="<--your site key-->"></div>`
Now you can capable to observe captcha shown in your form. But the consumer response is not confirmed yet. To build it, perform the following code changes in your Save action controller.
