### ISSUE TITLE
Configurable product price after index is always zero

### ISSUE THREAD

**Issue by datwiki** [magento/magento2#21722]
Preconditions (*)
2.30

Steps to reproduce (*)
1. Create Configurable Products with Child items
2. Set discount price to Child items
3. Run full reindex
4. Check table catalog_product_index_price

Expected result (*)
1. min_price, max_price, final_price, original_price has value, we intended to do sort by Highest Discount

Actual result (*)
1. Only min_price, max_price have value
2. The rest are zero

**Comment by magento-engcom-team** [comment]
Hi @datasiantech. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@datasiantech do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by datwiki** [comment]
select max(price) from catalog_product_index_price where entity_id in (select product_id from catalog_product_super_link where parent_id='xxxx')

We need value as this sql to use to calculate Highest Discount Sort in Catalog page

**Comment by aholovan** [comment]
So, why this issue was closed? Has it been fixed? I've faced the same bug for some configurable products..
