### ISSUE TITLE
Cart Rule still active after disabling

### ISSUE THREAD

**Issue by bonucci** [magento/magento2#21735]
### Summary (*)
So the problem is quite straitforward:
### Examples (*)
1) Create a Cart price rule of X % for 2 items in the cart.

2) Be sure to have this 2 items in the cart when the campaign rule i active.

3) Go to admin and disable the cart rule price;

4) You can checkout from the page with a campaign discount that was disabled.

The only way to update the cart with the current rules is updating the quantity or something, i believe that cart information is being loaded from the storage, and the storage is only updated when a use updates his information (ex: quantity).

Magento ver. 2.2.7

**Comment by magento-engcom-team** [comment]
Hi @bonucci. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bonucci do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by bonucci** [comment]
yes

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21735-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21735-2-3-develop.instances.magento-community.engineering/admin](https://i-21735-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98701`, `MAGETWO-98702` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmzaiets** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @funnyboy1190. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @funnyboy1190, here is your [Magento instance](https://i-21735-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21735-2-3-develop.instances.magento-community.engineering/admin](https://i-21735-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by aleromano89** [comment]
@bonucci I can't reproduce the issue on 2.3-develop. Can you give us more details? For example, the cart price rule should have a specific coupon? 
thanks

**Comment by ananth-iyer** [comment]
@bonucci Did you add the Coupon code to Cart price rule?

**Comment by mallikaverma** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @bonucci. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24403` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
