### ISSUE TITLE
Error in JS validation rule

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#21734]
### Preconditions (*)

1. Magento 2.1.x | 2.2.x | 2.3.x

### Steps to reproduce (*)

1. Open any UI form component XML file
2. Add to any input field following validation rule: **validate-per-page-value-list**
3. Set some value to the input from the previous step

### Expected result (*)

1. Validation works correctly

### Actual result (*)

1. Validation is failed for every non-empty value, even valid (for example "10,20")

### Additional Information
Please, check corresponding JS file: https://github.com/magento/magento2/blob/2.3/app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js, line 897 
When value is not empty, that validation rule will always return false

**Comment by magento-engcom-team** [comment]
Hi @avgust1111. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@avgust1111 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @kisroman. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by kisroman** [comment]
@avgust1111 I can not reproduce this issue. Fresh Magento 2.3 installation. Go to Stores -> Configuration -> Catalog -> Catalog -> Storefront -> Products per Page on Grid Allowed Values - enter some valid value and press save - save is successful for me.

**Comment by staradzinau** [comment]
@kisroman You can't reproduce the issue, because that kind of validation is not supported on the Stores -> Configuration pages.
Please, add specified validation rule (validate-per-page-value-list) to any input, which is declared within backend UI component XML to reproduce the issue

**Comment by kisroman** [comment]
@avgust1111 thank you for additional information. I am able to reproduce it now.

**Comment by magento-engcom-team** [comment]
@kisroman Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @kisroman
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment]
Hi @kisroman. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98942`, `MAGETWO-98943` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @avgust1111. Thank you for your report. 
The issue has been fixed in magento/magento2#21776 by @kisroman in 2.3-develop branch
Related commit(s):
 - [c8ed1e8ce498174df804b578665a5bcfd4c9e850](https://github.com/magento/magento2/commit/c8ed1e8ce498174df804b578665a5bcfd4c9e850)
 - [b030da0d92eeb455b03059807b66a9de29d2a1bf](https://github.com/magento/magento2/commit/b030da0d92eeb455b03059807b66a9de29d2a1bf)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @avgust1111. Thank you for your report. 
The issue has been fixed in magento/magento2#21813 by @kisroman in 2.2-develop branch
Related commit(s):
 - [6bb24ef4cccf52d56ee5c8ef43c9365509075d8a](https://github.com/magento/magento2/commit/6bb24ef4cccf52d56ee5c8ef43c9365509075d8a)
 - [0add8b722cb1591a3a2b8fe74e20d492431f5b18](https://github.com/magento/magento2/commit/0add8b722cb1591a3a2b8fe74e20d492431f5b18)

The fix will be available with the upcoming 2.2.9 release.
