### ISSUE TITLE
Products in wishlist are shown with normal price instead of special price

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#21743]
Hi guys,

We're having a problem with showing the special price on the wishlist. According to ticket https://github.com/magento/magento2/issues/11305 this problem should've been fixed in 2.2 and 2.3. 
Unfortunately this can still be reproduced. 

### Preconditions (*)
1. Magento 2.2.7

### Steps to reproduce (*)

1. Create a customer group
2. Create product with special price for that customer group
3. Login with customer, linked to the group
4. Add the product to the wishlist.

### Expected result (*)

1. Product should be shown with the price for that customer group

### Actual result (*)

1. Normal price of the product is shown.

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@duckchip do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by duckchip** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @duckchip, here is your [Magento instance](https://i-21743-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21743-2-3-develop.instances.magento-community.engineering/admin](https://i-21743-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by duckchip** [comment]
Can be reproduced on vanilla instance

login: test@test.test
pass: Qwerty123

Product has a normal price of $50 but a special price of $20. The normal price is shown on the wishlist

**Comment by ghost** [comment]
Hi @duckchip but you set special price for users there are no logged in ? whats wrong here ?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by duckchip** [comment]
@engcom-backlog-nazar I changed the special price to be visible for customers with customer group 'retailer' 
If you log in, you'll see the special price on the product view page, but the normal price on the wishlist page.

**Comment by duckchip** [comment]
Okay weird, it does show the special price in magento 2.3 
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @duckchip, here is your [Magento instance](https://i-21743-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21743-2-2-develop.instances.magento-community.engineering/admin](https://i-21743-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@duckchip i'm closing as this is not reproducible, if you find a way how to reproduce this on 2.3-develop instance, feel free to reopen issue.
