### ISSUE TITLE
Empty quantity cause fatal error on 2.3.0

### ISSUE THREAD

**Issue by bmxmale** [magento/magento2#21746]
On clean Magento 2.3.0 installation when I want to create Configurable product with no quantity specified we are getting fatal error. Visible on developer/production mode.

![image](https://user-images.githubusercontent.com/23213308/54358549-f142c380-4660-11e9-81b9-dd453d0b4960.png)

**Error log:**

![image](https://user-images.githubusercontent.com/23213308/54358743-5e565900-4661-11e9-95bc-186ce2e6adc0.png)

```
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Inventory\Model\SourceItem::setQuantity() must be of the type float or null, string given, called in /srv/magento2.3/vendor/magento/framework/Api/DataObjectHelper.php on line 125 and defined in /srv/magento2.3/vendor/magento/module-inventory/Model/SourceItem.php:75 Stack trace: 

#0 /srv/magento2.3/vendor/magento/framework/Api/DataObjectHelper.php(125): Magento\Inventory\Model\SourceItem->setQuantity('') 
#1 /srv/magento2.3/vendor/magento/framework/Api/DataObjectHelper.php(85): Magento\Framework\Api\DataObjectHelper->_setDataValues(Object(Magento\Inventory\Model\SourceItem), Array, 'Magento\\Invento...') 
#2 /srv/magento2.3/vendor/magento/module-inventory-catalog-admin-ui/Observer/SourceItemsProcessor.php(104): Magento\Framework\Api\DataObjectHelper->populateWithArray(Object(Magento\Inventory\Model\SourceItem), Array, 'Magento\\Invento...') 
#3 /srv/magento2.3/vendor/magento/module-inventory-catalog-admin-ui/Observer/ProcessSourceItemsObserver.php(120): Magento\Inve in /srv/magento2.3/vendor/magento/module-inventory/Model/SourceItem.php on line 75
```

**Disabled modules:**
```
List of disabled modules:
Magento_Dhl
Amazon_Core
Magento_Fedex
Magento_Braintree
Magento_Marketplace
Klarna_Core
Amazon_Login
Amazon_Payment
Klarna_Ordermanagement
Magento_Signifyd
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Ups
Magento_SampleData
Magento_Usps
Klarna_Kp
Magento_Weee
Magento_WeeeGraphQl
Dotdigitalgroup_Email
Temando_Shipping
Vertex_Tax
```

**Comment by magento-engcom-team** [comment]
Hi @bmxmale. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [ ] Information on your environment
- [x] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bmxmale do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by bmxmale** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21746-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21746-2-3-0.instances.magento-community.engineering/admin](https://i-21746-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @bmxmale thank you for you report, please open issue here https://github.com/magento-engcom/msi

**Comment by larsroettig** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, here is your [Magento instance](https://i-21746-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21746-2-3-0.instances.magento-community.engineering/admin](https://i-21746-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by maghamed** [comment]
the issue is fixed in the scope of MSI project 
here is PR addressing this issue - https://github.com/magento-engcom/msi/pull/2098

**Comment by mishrasumit45** [comment]
I also faced this below fatal error in Magento2.3.1.
@magento-admin, Please confirm We cannot save configurable products without quantity??

****Error when saving configurable product without quantity:****

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Inventory\Model\SourceItem::setQuantity() must be of the type float or null, string given, called in /var/www/public_html/vendor/magento/framework/Api/DataObjectHelper.php on line 125 and defined in /var/www/public_html/vendor/magento/module-inventory/Model/SourceItem.php:75 Stack trace: #0 /var/www/public_html/vendor/magento/framework/Api/DataObjectHelper.php(125): Magento\Inventory\Model\SourceItem->setQuantity('') #1 /var/www/public_html/vendor/magento/framework/Api/DataObjectHelper.php(85): Magento\Framework\Api\DataObjectHelper->_setDataValues(Object(Magento\Inventory\Model\SourceItem), Array, 'Magento\\Invento...') #2 /var/www/public_html/vendor/magento/module-inventory-catalog-admin-ui/Observer/SourceItemsProcessor.php(104): Magento\Framework\Api\DataObjectHelper->populateWithArray(Object(Magento\Inventory\Model\SourceItem), Array, 'Magento\\Invento...') #3 /var/www/public_html/vendor/magento/module-inventory-catalog-admin-ui/Observer/ProcessSourceItemsO in /var/www/public_html/vendor/magento/module-inventory/Model/SourceItem.php on line 75
