### ISSUE TITLE
catalog_product_flat_data for store view populated with default view data when it should be store view data

### ISSUE THREAD

**Issue by bengower** [magento/magento2#21747]
**Preconditions (*)**

1. A Magento CE 2.3 installation with multiple websites setup (I have four websites each setup with one store and one store view).
2. Add a custom product attribute (Attribute A) with a ‘Catalog Input Type for Store Owner’ of Text Field, ‘Scope’ of Store View, ‘Allow HTML Tags on Storefront’ of Yes and ‘Used in Product Listing’ of Yes. Add it to an Attribute Set.
3. Create a product (Product A) that uses the attribute set with this custom attribute in it. Add this product to all websites and enable it on all websites.
4. Enable ‘Use Flat Catalog Product’ in Store > Configuration > Catalog > Catalog in the Storefront section.

**Steps to reproduce (*)**

1. I open to edit Product A from Catalog > Products and add some text (‘Multi-buy Offer’) to the default view in Attribute A as I would like this text to appear on all but one site and then save.
2. I then change the store view to that of one of the other store views (Store View 3). I go to Attribute A and untick ‘Use Default Value’ I then make sure the value of the Attribute A field is empty (just for this store view) and save.
3. I then make sure that the indexes are up to date with the latest changes.

**Expected result (*)**

1. The catalog product flat data table in the DB for the Store View 3 in the row for Product A contains Attribute A showing the empty value that was set for Store View 3.

**Actual result (*)**

1. The catalog product flat data table in the DB for the Store View 3 in the row for Product A contains Attribute A but it shows the Default View value instead of empty value that was set for Store View 3.
2. This incorrect value then appears on the frontend of the website associated with Store View 3

Disabling ‘Use Flat Catalog Product’ shows the correct data in Store View 3.

**Comment by magento-engcom-team** [comment]
Hi @bengower. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bengower do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by bengower** [comment]
@magento-engcom-team I can reproduce on a vanilla Magento instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98864`, `MAGETWO-98865` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bravarg** [comment]
To be more precisely, when you save product with indexer settings: "update on save" it saves data correctly on each store flat table. However after running bin/magento indexer:reindex it sets incorrect (default store view) data, instead of store view data.

**Comment by magento-engcom-team** [comment]
Hi @bengower. Thank you for your report. 
The issue has been fixed in magento/magento2#22318 by @OlehWolf in 2.3-develop branch
Related commit(s):
 - [ae7179f7bee1b99597aee46da79f581a8a45a018](https://github.com/magento/magento2/commit/ae7179f7bee1b99597aee46da79f581a8a45a018)
 - [1a1eda6a26301b10d97b6b33ab5e3a195e212f94](https://github.com/magento/magento2/commit/1a1eda6a26301b10d97b6b33ab5e3a195e212f94)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @bengower. Thank you for your report. 
The issue has been fixed in magento/magento2#22581 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [020f970e51c754805674ce81e85ccfdd34301579](https://github.com/magento/magento2/commit/020f970e51c754805674ce81e85ccfdd34301579)
 - [aae1e595654105d450ba7b773bf2ae0c616cb9d3](https://github.com/magento/magento2/commit/aae1e595654105d450ba7b773bf2ae0c616cb9d3)

The fix will be available with the upcoming 2.2.10 release.
