### ISSUE TITLE
Cash on Delivery COD based on billing address instead on shipping address

### ISSUE THREAD

**Issue by Webroju** [magento/magento2#21745]
COD based actual on the billing address instead on the shipping address - but how the name it says, Cash on delivery: it has to be paid by the person who receives the delivery, so the shippment address is important not the billing address.

### Preconditions (*)

1. Magento 2.2.7

### Steps to reproduce (*)

1. Allow COD for one Country, e.g Germany
2. go to checkout, choose at the shipping step: shipping address country =>germany
3 . At the payment step, choose another billing country than germany,

### Expected result (*)

1. I can place the order

### Actual result (*)

1. I can't place the order
![Payment_not_available](https://user-images.githubusercontent.com/13220558/54352553-37445b00-4652-11e9-9f92-ae64d9152b44.jpg)

**Comment by magento-engcom-team** [comment]
Hi @Webroju. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Webroju do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Webroju** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Webroju. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Webroju, here is your [Magento instance](https://i-21745-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21745-2-3-develop.instances.magento-community.engineering/admin](https://i-21745-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Webroju** [comment]
I can confirm that I was able to reproduce the issue on vanilla Magento instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
Hi @Leandry. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Leandry** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leandry. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leandry, here is your [Magento instance](https://i-21745-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21745-2-2-develop.instances.magento-community.engineering/admin](https://i-21745-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Leandry** [comment]
Hi, The issue was reproduced when the "Cache On Delivery" payment restricted by country and failed on billing address validation. 
![2019-03-16_10-56-52](https://user-images.githubusercontent.com/9416636/54473110-422af700-47dc-11e9-85e1-fcc72df18cc4.png)
![2019-03-16_10-50-51](https://user-images.githubusercontent.com/9416636/54473113-4525e780-47dc-11e9-9cf2-577ec9a9e8f7.png)

**Comment by magento-engcom-team** [comment]
@Leandry Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98741`, `MAGETWO-98742` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @VitaliyBoyko. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by VitaliyBoyko** [comment]
Hi @Leandry @engcom-backlog-nazar @Webroju 
I believe this is expected behavior.
Initially, after set shipping information, the address is ok.

> 3 . At the payment step, choose another billing country than germany,

So we have chosen the forbidden country for billing (in this case for shipping either as it is COD) and expect that order should be placed? I believe this is ok that error being displayed.

**Comment by ghost** [comment]
Hi @VitaliyBoyko yes i'm also think that this is expected behavior.

**Comment by ghost** [comment]
HI @Webroju thank you for you report, i'm closing this as this is non-issue.

**Comment by Webroju** [comment]
Hi @engcom-backlog-nazar ,
I do not agree with that, because the customer pays from a country, which is allowed.
It is the question of how to define billing address and payment method, for me there are two different things.
It also means billing address and not payment address.
Because the payment method determines where and how I pay, and that has nothing to do with the billing address.
