### ISSUE TITLE
A question for theme troubleshooting section in official documentation

### ISSUE THREAD

**Issue by nettree** [magento/magento2#21762]
### Summary (*)
In https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/themes/theme-create.html, down to the bottom of this page, there is a section `Troubleshooting`, there it suggests we can run command like `magento setup:static-content:deploy en_US` to see if it can resolve the theme is not visible issue, can I ask why? Based on my understanding, if we're in developer mode, this command should NEVER be run, right? Thank you.

### Examples (*)
When a customised child theme of Luma is not visible during the creation.

### Proposed solution
I was just asking a question.

**Comment by magento-engcom-team** [comment]
Hi @nettree. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nettree do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
Hi, please ask this in the devdocs / community repo.

This issue tracker here is for bugs in Magento 2.

**Comment by DanielRuf** [comment]
https://github.com/magento/devdocs

**Comment by nettree** [comment]
Thanks @DanielRuf, will do :)
