### ISSUE TITLE
Local time off with one hour on 8 Magento 2.3 installations

### ISSUE THREAD

**Issue by onepack** [magento/magento2#21783]
### Preconditions (*)

1. Magento 2.3
2. PHP 7.2

### Steps to reproduce (*)

1. Set the Server time and Check via SSH with "date" for the server time. The correct (Europe/Amsterdam) time is given.
2. Set the PHP time zone and Check the PHP time via php_info() gives Europe/Amsterdam (correct).
3. Set the Magento 2.3 config time zone to Europe/Amsterdam.

### Expected result (*)

1. Expected result is that I will get the actual Europe/Amsterdam time and not the Europe/London time in Magento.

### Actual result (*)

1. The result is that I get the Europe/London time on all the 8 magento 2.3 installations.
2. Cron result from just now:
 [2019-03-15 22:10:09] main.INFO: Cron Job newsletter_send_all is successfully finished.
It is actually: 23:10 now.

**Comment by magento-engcom-team** [comment]
Hi @onepack. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@onepack do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by onepack** [comment]
I set .user.ini with:
date.timezone = UTC

It is shown as a local value in php_info() but still the hour is one off.
I'm out of ideas.

**Comment by keyurk-emipro** [comment]
@onepack  I think it is because of `date_default_timezone_set('UTC');` in app/bootstrap.php

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by onepack** [comment]
So what I did is:
remove the UTC I set in the .user.ini as it was already set in the bootstrap.
I knew about the bootstrap setting but thought it wasn't working as we should have offsets in the Magento using this UTC base.

I noticed there was no change with the UTC in the .user.ini
So this meant that the problem has to be in the Magento core.

This conclusion seemed to be correct as choosing the Chinese local time stamp kept my time as it has always been. One hour earlier that my actual time.

So this setting seems to be completely useless.

I removed the UTC value from bootstrap as well and now the timezone from PHP kicks in and that is the correct one.

Conclusion: there is a big bug in the magento2 local timezone settings. The offsets are not working at all from the UTC base.
Because of this the UTC setting in the bootstrap has become a problem as it prevents anyone from using the time from the server or PHP and so not being able to set the time at all.

**Comment by tomekjordan** [comment]
Probably its the sam problem with Content Staging on Commerce version I think where updates are not triggered properly according to server time.

**Comment by onepack** [comment]
I checked the cron_schedule table because of this and it was gigantic. Probably because all the crons missed due to the time mismatch.
I will keep an eye on this table to see if things are working out now.
Checking the system.log also showed the correct time now.

**Comment by onepack** [comment]
System.log also has the proper time now.

**Comment by onepack** [comment]
After checking again I noticed the following.
The crons all missed as they all were scheduled one hour ahead because I removed the UTC from the bootstrap.
This means keeping the UTC setting in the bootstrap will make sure all crons will run with success in the correct local time.
However, the rest of the magento 2.3 time, like the logs and the output of the locale time, is now one hour behind again from my actual time. So it's 50/50. On some places the time is correct and some other places one hour behind.
I will leave it like this for now to make sure the crons run but it's quite worrying that a big project like Magento has so many flaws.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98806` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @onepack. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24434` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
