### ISSUE TITLE
Magento 2.3 Unassign product from category makes category unavailable

### ISSUE THREAD

**Issue by tsifra** [magento/magento2#21794]
### Preconditions (*)
1. Magento 2.3 
2. deploy:mode:set default
3. Apache2 + MySql clean install (no opcache etc.)

### Steps to reproduce (*)
1. Open category where test product is in frontend. Make sure that you see the product. For example it is https://dev.site.com/category1/category2
2. Open product page in new tab
3. Go to backend Catalog - Product - [product]
4. Delete the category from "Categories" field and save product
5. Refresh product page in frontend. Check breadcrumbs zone. It's okay page loaded, there is no breadcrumb hierarchy has gone.
6. Refresh category page in frontend

Optional steps:
7. run bin/magento indexer:reindex
8. php bin/magento cache:flush

### Expected result (*)
1. See category page without unassigned product

### Actual result (*)
1. 404 page not found
2. If you check url in menu now it is https://dev.site.com//category2.html Notice two slashes, top category "category1" disapeared and .html appeared in the end. All other menu items are okay and i can browse other categories. 

So reindexing and category editing make no sense. I'm not able to replace categories for existing product through import with add/update option without loosing product related data like described in #7930 bug from 2016 for previous versions of Magento. Now i've lost ability to do category editing through web-interface. I even tried code-way $categoryLinkRepository->deleteByIds($categoryId, $sku) Result is the same. Category is gone, not able to restore it.

**Comment by magento-engcom-team** [comment]
Hi @tsifra. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tsifra do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tsifra** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tsifra. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tsifra, here is your [Magento instance](https://i-21794-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21794-2-3-develop.instances.magento-community.engineering/admin](https://i-21794-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tsifra** [comment]
I've tried to reproduce test case on offered instance,
Created 2 categories and one product. Can't confirm bug. Made clean test case on my dev and can't reproduce. Doing deeper testing on my side.

**Comment by tsifra** [comment]
It is some kind of Schrödinger's bug. I've checked catalog_category_entity* tables in my database. Somehow data in table catalog_category_entity_varchar that corresponds url key field in interface was split to two store_id’s (0 -default and 1 - new one). Default store_id for all settings is 0, but some categories that i described in initial report duplicate these settings for store_id = 1. In some cases url_key and url_path became null for admin store. Have no idea how this happenned. One thing i can confirm that this duplication appeared not as result of manual editing category attributes. Duplication of database attributes was related only to some categories, that i unassigned product from via product edit interface. If I can repeat data duplication on my database one more time I can offer my database copy to you. Case closed.
