### ISSUE TITLE
Magento2 stops every night

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#21806]
Hello,

i didn`t know if it is realy a bug in Magento2 or in the configuration of magento2, server and plesk.
All Crons are working and the error files are also okay.
I have the problem, that my webstore every night at 01 till 02 o`clock gowing down,
but i dont now why.
if i restart the cache in the backend, the site comes up.
Can yomebody help me?

It is M 2.3 on an Plesk 17.8.11 System with Debian 8.11.
The PHP Settings are with 7.2.16 FstCGI from Apache.
Server: Localhost via UNIX socket
Server-Typ: MariaDB
Server-Verbindung: SSL wird nicht verwendet Dokumentation
Server-Version: 10.0.38-MariaDB-0+deb8u1 - (Debian)
Protokoll-Version: 10

Thank You!!!!

**Comment by magento-engcom-team** [comment]
Hi @Olek89. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Olek89 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LiamKarlMitchell** [comment]
Enough CPU's?
Can you check for long running mysql process or in htop any long running cron or php-fpm/php processes?

https://magento.stackexchange.com/questions/203107/magento-2-cron-schedule-table-increasing-and-cpu-100
Maybe cron_schedule table too full of records
? Just thoughts... no idea why this happens for you.

**Comment by Olek89** [comment]
Thank You, i will test it with the cron job and cron_schedule.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @Olek89  
```
Magento versions higher than 2.1.0, e.g. 2.2.4, are not available for the installation via Plesk Application Catalog and thus are not supported.
If an installation/upgrade of Magento version higher than 2.1.0 is required, it should be performed on your own.
In case of any errors appeared during installation/upgrade operations, contact Magento support for the assistance.
```
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
