### ISSUE TITLE
When I try to upload an image from Magento 2.3 backend. i got error "File 'image/jpeg' doesn't exist" can you guys tell me what is the solution

### ISSUE THREAD

**Issue by nawabamit** [magento/magento2#21807]
1. Magento 2.3 ,PHP Version 7.1.27  ,MySQL 5.0.12
1. When I try to upload an image from Magento 2.3 backend. i got error "File 'image/jpeg' doesn't exist"
can you guys tell me what is the solution

![image-not -uploaded-issue](https://user-images.githubusercontent.com/24496702/54488645-45041580-48ca-11e9-9450-838f3d45b94b.png)

**Comment by magento-engcom-team** [comment]
Hi @nawabamit. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@nawabamit do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanielRuf** [comment]
It seems you have deleted some parts of the issue template. Please do not delete but replace with your issue content.

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.3.0 instance

Can you verify the bug there?

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-21807-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-21807-2-3-0.instances.magento-community.engineering/admin](https://i-21807-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
Please test it there @nawabamit:
https://github.com/magento/magento2/issues/21807#issuecomment-473652828

**Comment by nawabamit** [comment]
I have tested. the image uploading process is working fine.but in my case it is not working only on cms page. on catalog product, everything works fine.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by nawabamit** [comment]
Any success @engcom-backlog-nazar @DanielRuf on the same.?

**Comment by ghost** [comment]
HI @nawabamit did you have some custom  module installed ? or did you migrate from magento 1 or others 2.2 ?

**Comment by nawabamit** [comment]
@engcom-backlog-nazar  No module installed yet and I did not migrate it. I have installed a fresh Magento  2.3 setup.

**Comment by ghost** [comment]
@nawabamit please provide more information about your configuration

**Comment by ghost** [comment]
@nawabamit i'm closing this for now, if you have some additional information which help us to reproduce , feel free to reopen issue.

**Comment by nawabamit** [comment]
what information do you want know.?  Again explaining here.
Magento version-2.3
PHP version- 7.1.26
the issue is when I try to upload an image from cms page text editor. it shows "File 'image/jpeg' doesn't exist".  
Process-CONTENT-pages->content (uploading image)

**Comment by ghost** [comment]
@nawabamit but as you can see, it's reproducible only on your instance would be great to know, your system is linux or windows ?

**Comment by nawabamit** [comment]
@engcom-backlog-nazar  Window.

**Comment by ghost** [comment]
@nawabamit this may cause the issue, only unix system are supported by magento.

**Comment by nawabamit** [comment]
i have another website . where image upload process is working fine. i am using window for both website.

**Comment by ghost** [comment]
@nawabamit both 2.3.0 ?

**Comment by nawabamit** [comment]
@engcom-backlog-nazar  yes both are 2.3.0
