### ISSUE TITLE
collect-theme-phrases not picking up translation strings

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#21827]
### Preconditions (*)

1. Magento 2.2.6, but it's also not fixed in 2.3.x

### Steps to reproduce (*)

1. Run: `bin/magento i18n:collect-theme-phrases`
2. Collected phrases should include these for .html files: `translate="'your_string'"` and `attr="title: $t('your_string')"`

### Expected result (*)

1. The generated csv file should contain all translate strings.

### Actual result (*)

1. The generated csv file does not contain all translate strings. It only has the ones starting with `i18n:`
2. A nice string to check is `Upload Image` from: vendor/magento/module-configurable-product/view/adminhtml/web/template/components/file-uploader.html
3. Or check for `Record contains unsaved changes` from: vendor/magento/module-ui/view/base/web/templates/grid/editing/row.html

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@PascalBrouwers do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by PascalBrouwers** [comment]
The file that has the bug is: `setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php` but I suggest to take a look at the other adapters as well.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@PascalBrouwers why closed ?
