### ISSUE TITLE
Shipping method values becomes zero when apply a cart price rule in checkout 

### ISSUE THREAD

**Issue by sheyan-ascentic** [magento/magento2#21832]
### Preconditions (*)
1. Magento 2.2.5

### Steps to reproduce (*)
1. Enable Free shipping, table rates and flat rates from admin->configurations ->shipping methods.
1. Create a Cart price rule to discount a specific shipping amount.
Marketing -> Cart price rule.

https://user-images.githubusercontent.com/34059011/54592574-abb43b00-4a52-11e9-8f32-5b32957a377a.png
https://user-images.githubusercontent.com/34059011/54592624-c71f4600-4a52-11e9-8b64-59ba1070725a.png
https://user-images.githubusercontent.com/34059011/54592662-dbfbd980-4a52-11e9-9f2c-d17e24ee6cc9.png
https://user-images.githubusercontent.com/34059011/54592686-e61dd800-4a52-11e9-9776-65881fabdd3c.png

1. Apply the discount code by selecting the flat rate from the checkout shipping methods
1. Go to home page and come back to the checkout page

### Expected result (*)
1. After going to the homepage and come to Checkout flat rate shipping method should be 0 but table rate shipping method should be a value set in the table rate matrix.

### Actual result (*)
1. After going to the homepage and come to Checkout flat rate shipping method is 0 and table rate shipping method also became 0 .
https://user-images.githubusercontent.com/34059011/54593111-c89d3e00-4a53-11e9-84de-a475f6597a3e.png

**Comment by magento-engcom-team** [comment]
Hi @sheyan-ascentic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@sheyan-ascentic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by sheyan-ascentic** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @sheyan-ascentic. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @sheyan-ascentic, here is your [Magento instance](https://i-21832-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-21832-2-2-5.instances.magento-community.engineering/admin](https://i-21832-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sheyan-ascentic** [comment]
Configurations done on the instance. Select country as Australia as it is configured in the table rates matrix. Other details mentioned as steps to reproduce section above.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98792`, `MAGETWO-98793` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by sheyan-ascentic** [comment]
Any update on this?

**Comment by nitishcs6** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
@nitishcs6 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by nitishcs6** [comment]
Hi Magento Team,
@magento-engcom-team

I think it is default behavior considering current functionality/behavior of sales rules.(inherited from M1)

Below is what happening considering mentioned scenario :

1. Customer has selected "Flat Rate" on checkout.

2. Rule present in **Conditions** section inside sales rule get passed i.e. shipping method is "flatrate_flatrate"

3. Rules present in **Actions** section are also passed (Matching Items)

4. As Every shipping method in magento checks inside **collectRates**
`$item->getFreeShipping() || $item->getAddress()->getFreeShipping()
`
and based on this condition change Shipping Price to 0.
hence once **FreeShipping** **Flag** is set on an item, Every method will pick that and put Shipping price as 0.

### **Below is possible approach to solve this issue.**

A. We need to introduce a new Flag if rule contains Shipping method condition

like 
`$item->setFreeShippingMethod($validatedMethodCode)` 
inside
Magento\OfflineShipping\Model\SalesRule\Calculator::processFreeShipping
 ```
public function processFreeShipping(\Magento\Quote\Model\Quote\Item\AbstractItem $item)
    {
        $address = $item->getAddress();
        $item->setFreeShipping(false);

        foreach ($this->_getRules($address) as $rule) {
            /* @var $rule \Magento\SalesRule\Model\Rule */
            if (!$this->validatorUtility->canProcessRule($rule, $address)) {
                continue;
            }

            if (!$rule->getActions()->validate($item)) {
                continue;
            }

            switch ($rule->getSimpleFreeShipping()) {
                case Rule::FREE_SHIPPING_ITEM:
                    $item->setFreeShipping($rule->getDiscountQty() ? $rule->getDiscountQty() : true);
                    break;

                case Rule::FREE_SHIPPING_ADDRESS:
                    $address->setFreeShipping(true);
                    break;
            }
            if ($rule->getStopRulesProcessing()) {
                break;
            }
        }
        return $this;
    }
```
B. and Inside each method, it should check 
for both conditions

`$item->getFreeShipping() || $item->getAddress()->getFreeShipping()`

and 

`$item->getFreeShippingMethod() && $item->getFreeShippingMethod() == "currentMethodCode"`

Its kind of introducing new functionality. Lemme know this needs to be solved.

**Comment by sheyan-ascentic** [comment]
Hi @nitishcs6 So Can you give me the finalize fix where to edit that?

**Comment by marcosdsdba** [comment]
@nitishcs6  In my case i created the Rule to two or more items in the Cart, to apply set Free Shipping but doesn't work . The rule apply discount in Product Price and Return NaN in Total. 

How to create a correct rule that when the affection contain two items or more apply free shipping?

Magento 2 Version 2.3.1.

![Error-freeshipping](https://user-images.githubusercontent.com/8545697/57478896-81bd0f00-7272-11e9-95af-63167577a6a1.png)

**Comment by zakdma** [comment]
@magento i am working on it
