### ISSUE TITLE
If we create order in Magento with billing address of US country and shipping address of Norway country[any country which has no states in Magento2] then billing address region is saving in shipping address region in sales_order_address table and quote_address table

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#21848]
Preconditions

1.      Magento EE 2.2.6

2.      PHP 7.1

 

Steps to Reproduce

1. Place an Order from Magento frontend with billing address as US country and shipping address as Norway country and State being any text

2. Go to the Magento database and select the sales_order_address table

3. Check the region_id column in shipping address of order

4. Go to the Magento database and select the quote_address

5. Check the region_id column in shipping address of quote

 

Expected result

1. Order shipping address should not have region_id in it i.e., region_id is NULL.

 

Actual result

1. Order shipping address have region_id in it i.e., region_id is not NULL.

 

Screen-cast: https://www.screencast.com/t/zICGFBgDJRE

**Comment by magento-engcom-team** [comment]
Hi @i95devdivya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@i95devdivya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @i95devdivya thank you for you report, what the point of this issue ? why they cannot be the null ?

**Comment by ghost** [comment]
@i95devdivya expected result on 2.3.0 EE instance 
![DeepinScreenshot_select-area_20190320103853](https://user-images.githubusercontent.com/40756439/54670472-65b3b180-4afc-11e9-9945-a563cd4637ef.png)

**Comment by ghost** [comment]
Hi @i95devdivya thank you for you report, closing this as this was fixed in 2.3.0 release
