### ISSUE TITLE
ThemeFactory getTheme function always returns null

### ISSUE THREAD

**Issue by vaso123** [magento/magento2#21850]
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1-fpm
3. Ubuntu 18.04LTS
4. nginx

### Steps to reproduce (*)

Write a controller, API, anything what you can execute.

`public function getHeader()
    {
        $themeId = $this->scopeConfig->getValue(
            \Magento\Framework\View\DesignInterface::XML_PATH_THEME_ID,
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE,
            $this->storeManager->getStore()->getId()
        );

        /** @var $theme \Magento\Framework\View\Design\ThemeInterface */
        $theme = $this->themeProvider->getThemeById($themeId);
    }`

### Expected result (*)

In `$theme` there should be the data of theme.

### Actual result (*)

Always get null.

The `getThemeById` call the `ThemeProvider` what calls the the `ThemeFactory`.

This is in `ThemeFactory`

` public function getTheme($themeId)
    {
        return null;
    }`

**Comment by magento-engcom-team** [comment]
Hi @vaso123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@vaso123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@vaso123 can you check your $themeId ? i think at this point you have null 
![DeepinScreenshot_select-area_20190320111732](https://user-images.githubusercontent.com/40756439/54672882-d6110180-4b01-11e9-8ad3-401ccdc608b6.png)

**Comment by vaso123** [comment]
> @vaso123 can you check your $themeId ? i think at this point you have null

Nope, there is the id, but anyway, it was my fault.
I've just copied it from stackoverflow, and I've used the wrong `\Magento\Framework\View\Design\Theme\ThemeProviderInterface`.

I've changed it to `Magento\Theme\Model\Theme\ThemeProvider`  and now it works.

**Comment by ghost** [comment]
@vaso123 ok, so i'm closing this one, thank you for collaboration. :+1:
