### ISSUE TITLE
Tiered price create & delete when Catalog Price Scope = Website

### ISSUE THREAD

**Issue by jonathan-may** [magento/magento2#21871]
### Preconditions (*)

1. Magento Commerce 2.3.0
2. Global-Settings catalog/price/scope = 1 (WEBSITE)
 `bin/magento config:set catalog/price/scope 1`

### Steps to reproduce (*)

1. Login to Admin
2. Create & Save Product with Tier-Price using All Websites
3. Update Product, change Tier-Price from All Websites to Main Website, Save Product

### Expected result (*)

1. Product should display one Tier-Price for Main Website.

### Actual result (*)

1. Product display two Tier-Prices, one for Main Website and one for All Websites
2. Additionally, the Tier-Price for All Websites does not remove after deleting the Tier-Price and saving the product.

Issue seems to be related to: [#19958](https://github.com/magento/magento2/issues/19958), [#21823](https://github.com/magento/magento2/issues/21823) and [#18154](https://github.com/magento/magento2/issues/18154)

@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jonathan-may do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @jonathan-may thank you for you report, i'm not able to reproduce following steps you described, can you recheck on clean magento ?
![Selection_021](https://user-images.githubusercontent.com/40756439/54830239-ce4b8b80-4cc0-11e9-8d67-b1aa84ec0268.png)
![Selection_022](https://user-images.githubusercontent.com/40756439/54830240-cee42200-4cc0-11e9-8e9d-368266416c94.png)

**Comment by ghost** [comment]
Hi @jonathan-may we are not able to reproduce following steps you described, this may be related to your custom code or module, please retest on clean magento 2.3? and if issue still exist feel free to reopen this issue. thanks for collaboration.

**Comment by jonathan-may** [comment]
@engcom-backlog-nazar,
The first image you added displaying the tiered pricing shows that you did reproduce the issue. 

If you delete both tiered prices and save the product, then recheck the tiered prices the All Websites tiered price would still be displayed.

Additionally, the issue I was describing only relates to the admin, not the frontend.

@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jonathan-may, here is your [Magento instance](https://i-21871-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21871-2-3-develop.instances.magento-community.engineering/admin](https://i-21871-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jonathan-may** [comment]
I was not able to reproduce bug in 2.3-develop instance.

**Comment by MeetKamal** [comment]
Able to re-produce in Magento 2.4.5 as well.
