### ISSUE TITLE
DatePicker date format does not reflect user's locale in grid filters

### ISSUE THREAD

**Issue by lhall-amphibee** [magento/magento2#21877]
Part of this bug was covered in https://github.com/magento/magento2/issues/6858 and it does work just fine on detail view, but not in grid filters.

### Preconditions (*)

1. Magento 2.3.0 fresh install

### Steps to reproduce (*)

1. Log into backend with a user using a non-english locale (e.g. French)
2. Navigate to a grid with a datepicker (e.g. Sales)
3. Fill a date in a filter

### Expected result (*)

1. Datepickers should use the user's locale.

### Actual result (*)

1. Datepicker format is using English locale.

![image](https://user-images.githubusercontent.com/15910616/54764721-99740180-4bf8-11e9-8d96-055e5aacae2c.png)

**Comment by magento-engcom-team** [comment]
Hi @lhall-adexos. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lhall-adexos do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by lhall-amphibee** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lhall-adexos. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lhall-adexos, here is your [Magento instance](https://i-21877-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21877-2-3-develop.instances.magento-community.engineering/admin](https://i-21877-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lhall-amphibee** [comment]
The bug seems to be fixed in branch develop, so it should be available in the upcoming 2.3.1 release ?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @lhall-adexos thank you for you report, this issue has already fixed in 2.3-develop branch and will be avaible on 2.3.1 release.

**Comment by angelflo** [comment]
Hi, does someone find a solution to have the datepicker who work correctly in backend filter.
I currently use magento **2.2.10** with French backend admin and have this pb of date when i try to filter orders. (if I switch in english it's ok ... but this is not a solution).
Thanks a lot for your help
