### ISSUE TITLE
Disable Modules Output

### ISSUE THREAD

**Issue by leedave** [magento/magento2#21875]
### Description (*)
Please bring back the adminhtml option "Disable Modules Output"

### Expected behavior (*)
Prevent Output of modules that should not render to screen in specific environments

### Benefits
Better control over shop behaviour

### Additional information
I cannot see why this feature was removed in 2.2. It is very central if you are running different instances of Magento.

**Comment by magento-engcom-team** [comment]
Hi @leedave. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@leedave do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by leedave** [comment]
Enviroment: 
Apache 2.4, PHP 7.2, Magento CE 2.3.0

Steps to reproduce
- Login to Admin Area
- Open "Stores" -> "Configuration"
- Search for Advanced / Advanced 

I confirm this issue can be reproduced in a vanilla Magento installation

**Comment by hostep** [comment]
This was removed when Magento 2.2.0 was released, see [release notes](https://devdocs.magento.com/guides/v2.2/release-notes/ReleaseNotes2.2.0CE.html):

> The ability to disable module output has been removed from Admin. If you disabled module output from Admin in a previous release, you must manually configure these settings. See [Disable module output](https://devdocs.magento.com/guides/v2.2/config-guide/config/disable-module-output.html) for details.

But the documentation link they refer in there might be able to help you further?
