### ISSUE TITLE
Visible totals table with "Not yet calculated" on checkout first shipping-step

### ISSUE THREAD

**Issue by likemusic** [magento/magento2#21883]
### Preconditions (*)

1. MagentoCE v2.2.7 and 2.2-develop (f44720a6d89ff5a7886d29c6b65a5f7e8f58d6e7)

### Steps to reproduce (*)
1. Add product to cart.
2. In Crome DevTools on the "Network" tab check "Disable Cache" and change "Throttling" from "Online" to "Slow 3G" (or custom defined slow network speed).
![image](https://user-images.githubusercontent.com/603401/54793727-e4bbfd80-4c54-11e9-8134-00612c6ed0c4.png)

3. Go to checkout page (`checkout/#shipping`).

### Expected result (*)
1. Totals table not visible.
![image](https://user-images.githubusercontent.com/603401/54793537-f4871200-4c53-11e9-9328-060274ee60de.png)

### Actual result (*)
1. Visible totals table with "Not yet calculated" values for "Shipping and Tax".
![Shipping-Not yet calculated](https://user-images.githubusercontent.com/603401/54793600-2ef0af00-4c54-11e9-9901-4d597e4d1b52.png)

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@likemusic do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by likemusic** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @likemusic, here is your [Magento instance](https://i-21883-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21883-2-3-develop.instances.magento-community.engineering/admin](https://i-21883-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by likemusic** [comment]
Seems that it issue fixed in 2.3-develop. Totals table initially shown but hide by the loads and renedering complete.

**Comment by likemusic** [comment]
Seems that add step to step-navigator triggers updates in templates in 2.3-develop but not in 2.2-develop.
![image](https://user-images.githubusercontent.com/603401/54795643-18e7ec00-4c5e-11e9-896f-1528e5f16271.png)

Possible because `steps().sort()` used in 2.3-develop in `Magento/Checkout/view/frontend/web/js/model/step-navigator.js`.
Related commit: https://github.com/magento/magento2/commit/216b595d69f601019779ca57e446d7c904f89175

But `step-navigator.js` still have one call `steps.sort()` on line 39. Is it bug?

**Comment by likemusic** [comment]
While I investigate this issue on 2.2-develop branch I found possible 2 bugs.

1) In `module-checkout\view\frontend\web\js\model\step-navigator.js` isProcessed-method.
https://github.com/magento/magento2/blame/2.3-develop/app/code/Magento/Checkout/view/frontend/web/js/model/step-navigator.js#L137

In current implementation method returns `true` for step-codes that not exists in step-navigator at all. Seems that it should return false in that case, because not existed steps couldn't be processed. Isn't it?

2) Some components listed below uses calls like `stepNavigator.isProcessed('shipping')`.
- Magento_Checkout/js/view/summary/abstract-total.js
- Magento_Checkout/js/view/summary/cart-items.js
- Magento_Checkout/js/view/shipping-information.js

This call means that this components have `shipping` component as dependence and expected that it already exists and initialized, but `Magento_Checkout/js/view/shipping.js` not listed first argument array for define()-function. Seems that with `shipping`-component in requirejs dependencies this components would be rendered when shipping-step was already registered in step-navigator. It will fix this issue in 2.2-develop and prevent duble rendering for totals table in page components initialization process for 2.3-develop.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98838`, `MAGETWO-98839` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [Magento instance](https://i-21883-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21883-2-3-develop.instances.magento-community.engineering/admin](https://i-21883-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by victor-ruiz** [comment]
#cd19latam

**Comment by magento-engcom-team** [comment]
Hi @likemusic. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24311` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
