### ISSUE TITLE
Mutation is not working if we pass object as mutation parameter and it is working if we pass string as parameter

### ISSUE THREAD

**Issue by i95devdivya** [magento/magento2#21886]
Preconditions

1.      Magento CE 2.3

2.      PHP 7.2.16

 

Steps to Reproduce

1. Create a module for graphql implementation

2. Define the following in etc/schema.graphqls

type Mutation {

  createCustomer(cust: Customer!): CustomerCreate @resolver(class: "\\I95Dev\\CustomerOrder\\Model\\Resolver\\Customer") @doc(description:"Create Customer and returns its Id and corresponding message")

}

type CustomerCreate {

  message: String @doc(description: "Success or error Message")

  id: Int @doc(description: "The customer id")  

}

input Customer {

 firstname: String!

 lastname: String!

 email: String!

}

3. Run php bin/magento setup:upgrade command

4. Provide 777 permissions to generated, var and pub directories inside Magento application root folder

5. Then try to set the graphql endpoint as yourdomain.com/graphql in GraphIQL extension of chrome browser

 

Expected result

1. endpoint should be set without error and graphql schema document should be shown

 

Actual result

1. getting error like "Schema must contain unique named types but contains multiple types named \"Customer\" (see http://webonyx.github.io/graphql-php/type-system/#type-registry)." while setting endpoint

 

Screen-cast: https://www.screencast.com/t/xC3vxZ0Uc

**Comment by magento-engcom-team** [comment]
Hi @i95devdivya. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@i95devdivya do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @i95devdivya thank you for you report, please open issue here -> https://github.com/magento/graphql-ce

**Comment by i95devdivya** [comment]
Note: If I create a mutation like below it is working
type Mutation {
  createCustomer(firstname: String!,lastname: String!, email: String!): CustomerCreate @resolver(class: "\\I95Dev\\CustomerOrder\\Model\\Resolver\\Customer") @doc(description:"Create Customer and returns its Id and corresponding message")
}

type CustomerCreate {
  message: String @doc(description: "Success or error Message")
  id: Int @doc(description: "The customer id")  
}
