### ISSUE TITLE
Exception when I order bundle product which have simple product as child

### ISSUE THREAD

**Issue by ankurAuriga** [magento/magento2#21887]
### Preconditions (*)

1. Magento 2.3.0
2.

### Steps to reproduce (*)

1. Create bundle product which has at-least 1 simple product as child 
2. On place order, exception generated in multisource inventory module. 

### Expected result (*)

1. Order should get placed successfully with processing status
2.

### Actual result (*)

1. Magento throws exception - Uncaught TypeError: Return value of Magento\\InventorySourceSelection\\Model\\Request\\InventoryRequest::getItems() must be of the type array, null returned in vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102
2. I think issue is in vendor/magento/module-inventory-shipping/Model/GetSourceSelectionResultFromInvoice.php at line no - 113 where it is skipping child product.

**Comment by magento-engcom-team** [comment]
Hi @ankurAuriga. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ankurAuriga do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @ankurAuriga thank you for your report, did your simple product have custom source ?

**Comment by ankurAuriga** [comment]
@engcom-backlog-nazar - No, I am using default source only. I do not have any other source

**Comment by ghost** [comment]
@ankurAuriga is this clean magento or you migrated from some version ?

**Comment by ankurAuriga** [comment]
@engcom-backlog-nazar  - We upgraded from Magento 2.2.6

**Comment by ghost** [comment]
@ankurAuriga did you enable MSi modules ? because when you upgrade from 2.2 all modules are disabled.

**Comment by ankurAuriga** [comment]
@engcom-backlog-nazar - Yes it is enabled and error is coming only for this case. For all other product types, it is working fine.

**Comment by ghost** [comment]
@ankurAuriga You manually enabled or this automatically enabled ?

**Comment by ankurAuriga** [comment]
Automatically

**Comment by ghost** [comment]
@ankurAuriga i'm not able to reproduce following steps you described, i'm successfully update from 2.2.6 to 2.3.0 and all msi modules are disabled. try to reproduce this on clean magento without any extensions installed. Feel free to open ticket here -> https://github.com/magento-engcom/msi if problem still exists.

**Comment by ankurAuriga** [comment]
@engcom-backlog-nazar - I did not understand why you are validating if MSI is enabled or not. Do you mean I need to disable MSI module to make this work?

**Comment by ghost** [comment]
@ankurAuriga i think yes because all this modules need to be disable after upgrading.

**Comment by ankurAuriga** [comment]
@engcom-backlog-nazar - But why I need to disable MSI module.
