### ISSUE TITLE
Search Engine - Elasticsearch throws "mapper_parsing_exception" 

### ISSUE THREAD

**Issue by jaideepghosh** [magento/magento2#21889]
### Preconditions (*)

1. Downloaded magento2.3.0 from [magento.com](https://magento.com/tech-resources/download) and installed.
2. Installed elasticsearch 6.4.2
3. Configure Magento to use Elasticsearch. ([Source](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html#elastic-m2-configure))

### Steps to reproduce (*)

1. Configure Magento to use Elasticsearch. ([Source](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html#elastic-m2-configure))
2. Execute `php <your Magento install dir>/bin/magento indexer:reindex catalogsearch_fulltext
` as mentioned in [Dev Docs](https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html#es-reindex)

### Expected result (*)

<img width="612" alt="Screen Shot 2019-03-22 at 4 56 38 PM" src="https://user-images.githubusercontent.com/3909648/54819940-837f4300-4cc3-11e9-9bc4-389e8a0a7ea2.png">

### Actual result (*)

<img width="1440" alt="Screen Shot 2019-03-22 at 4 57 50 PM" src="https://user-images.githubusercontent.com/3909648/54819989-af9ac400-4cc3-11e9-9873-33b9306eb717.png">

> Catalog Search indexer process unknown error:
> {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [category_ids]"}],"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [category_ids]"},"status":400}

**Comment by magento-engcom-team** [comment]
Hi @jaideepghosh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jaideepghosh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jaideepghosh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jaideepghosh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jaideepghosh, here is your [Magento instance](https://i-21889-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21889-2-3-develop.instances.magento-community.engineering/admin](https://i-21889-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jaideepghosh** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by jaideepghosh** [comment]
I found an alternate solution for this issue, ie: 
> Implementation of elasticsearch 6.0 already on 2.3-develop branch and will be available on 2.3.1 release. [#21458](https://github.com/magento/magento2/pull/21458)

**Comment by jaideepghosh** [comment]
After switching to elasticsearch 5.4.2 from elasticsearch 6.4.2, Still getting the same error, ie: 
>{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Illegal dynamic template parameter: [match_mapping]"}],"type":"illegal_argument_exception","reason":"Illegal dynamic template parameter: [match_mapping]"},"status":400}

Here is my elasticsearch status:
<img width="388" alt="Screen Shot 2019-03-22 at 6 56 33 PM" src="https://user-images.githubusercontent.com/3909648/54825736-44a5b900-4cd4-11e9-8d8b-ef556aac9147.png">

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @jaideepghosh thank you for your report, only elasticsearch 5.2.x supported not 5.x .https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html
Magento Open Source 2.3.x supports the following Elasticsearch versions:

Elasticsearch 5.2
Elasticsearch 2.x
