### ISSUE TITLE
Magento 2.3 - Rabbitmq Queue Consumer.

### ISSUE THREAD

**Issue by karthi5053** [magento/magento2#21894]
### Preconditions (*)

1. Magento 2.3 EE
2. Rabbitmq and consumer

### Steps to reproduce (*)

1. Push message to rabbitmq topic.

### Expected result (*)

1. Message pushed to queue.

### Actual result (*)

1. Message is executed by the consumer which is ran by cronjob.

Problem Here:
I am pushing a messages to Rabbitmq topic, and i have consumer. This consumer is always being executed by magento cron. I will execute the below consumer command in daemon such supervisord, etc as a long running process. 
php bin/magento queue:consumer:start <consumername>
I don't want the message processed by magento cron.

As per, document.
https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-mysql.html

/vendor/magento/module-message-queue/etc/crontab.xml

Has the configuration for that runs the consumer job. There is an option to disable that in app/et/env.php in the document, but that didn't help me. Please let us the option so that messages are executed by consumer command rather than magento cron.

**Comment by magento-engcom-team** [comment]
Hi @karthi5053. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@karthi5053 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by karthi5053** [comment]
When trying to add 

'system' => [
        'default' => [
            'dev' => [
                'debug' => [
                    'debug_logging' => NULL
                ]
            ]
        ]
    ]
in app/etc/env.php, i'm getting below while running setup upgrade.
Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Framework\Stdlib\ArrayManager::get() must be of the type array, boolean given, called in /var/www/html/vendor/magento/module-theme/Model/Config/Processor/DesignTheme.php on line 75 and defined in /var/www/html/vendor/magento/framework/Stdlib/ArrayManager.php:57
Stack trace:
#0 /var/www/html/vendor/magento/module-theme/Model/Config/Processor/DesignTheme.php(75): Magento\Framework\Stdlib\ArrayManager->get('design/theme/th...', false)
#1 /var/www/html/vendor/magento/module-theme/Model/Config/Processor/DesignTheme.php(57): Magento\Theme\Model\Config\Processor\DesignTheme->changeThemeFullPathToIdentifier(false)
#2 /var/www/html/generated/code/Magento/Theme/Model/Config/Processor/DesignTheme/Proxy.php(95): Magento\Theme\Model\Config\Processor\DesignTheme->process(Array)
#3 /var/www/html/vendor/magento/framework/App/Config/PreProcessorComposite.php(35): Magento\Theme\Model\Config\Processor\DesignTheme\Proxy->process(Array)
#4 /var/www/html/vendor/magento/module-config in /var/www/html/vendor/magento/framework/Stdlib/ArrayManager.php on line 57

**Comment by karthi5053** [comment]
Upon adding the below, in app/etc/env.php
'cron_consumers_runner' => [
        'cron_run' => false,
        'max_messages' => 10000,
        'consumers' =>
        [],
    ],

Still, the messages from Rabbitmq is processed by cron job. I want this to be executed by 
php bin/magento queue:consumer:start <consumer name> command.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @karthi5053 thank you for you report, i;m not able to reproduce following steps you described, and at this screenshot you can see, that consumer not runs by cron if configuration disabled.
![DeepinScreenshot_select-area_20190325100706](https://user-images.githubusercontent.com/40756439/54904066-1a2b4a00-4ee6-11e9-89dd-e5f8a2a397be.png)
