### ISSUE TITLE
Can't Switch Back to PHP 7.1 on Mage 2.3

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#21893]
### Preconditions (*)

1. Magento 2.3
2. Upgraded from 2.2.5

### Steps to reproduce (*)

1. I updated to magento 2.3 from 2.2.5 and the update went okay.  However, I have found that I must keep my server on php 7.2 or my site won't work now.  If I roll back to 7.1 my site just loads and loads.  This wouldn't be an issue, however for some necessary reasons at cloudways I need to temporarily step back to 7.1.  Is there something in magento that needs to be changed to make it work with 7.1 again?

### Expected result (*)

1. For Magento 2.3 to work with php 7.1 or 7.2

### Actual result (*)

1. Site won't load on 7.1

**Comment by magento-engcom-team** [comment]
Hi @snoroozi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@snoroozi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@snoroozi,

> If I roll back to 7.1 my site just loads and loads

What exact error do you see?

There could be a problem, for instance, if you install composer dependencies with PHP 7.2 and then run them on PHP 7.1.

> Is there something in magento that needs to be changed to make it work with 7.1 again?

No, there is nothing like this in Magento itself.

**Comment by ladle3000** [comment]
@orlangur I ran the script that Magento provided for update from 2.2.5 to 2.3.  I assume that updated dependencies to be compatible with 7.2.  

But still if Magento is compliant with either php version, shouldn't its dependencies be the same.

**Comment by orlangur** [comment]
> updated dependencies to be compatible with 7.2.

It's up to dependencies, some of them, like `zend-code`, may be not compatible with both versions at the same time.

> if Magento is compliant with either php version, shouldn't its dependencies be the same

If you use provided `composer.lock`, it will. It contains 7.1-compatible dependencies as far as I remember.

@snoroozi without

> What exact error do you see?

answer nothing can be investigated.

**Comment by ladle3000** [comment]
@orlangur I put server on 7.1 again to collect any error logs for you and magically it worked without issue this time. Oh well. Closing this issue.
