### ISSUE TITLE
Error when trying to create an order in Admin using a stored credit card.

### ISSUE THREAD

**Issue by pingu1m** [magento/magento2#21900]
### Preconditions (*)

1. Magento 2.3 installed
2. PHP 7.1
4. Paypal Payflow installed and configured
5. Add a fraud rule to Paypal Payflow in order to spot mismatch of billing and shiping addresses

### Steps to reproduce (*)

1. Go to admin
2. Select "Create New Order"
3. Select a costumer with stored credit card
4. Add a product
5. Select a shipping address different from billing address
6. Select credit card payment method and place the order with a stored credit card

### Expected result (*)

1. A warning should appear: "The billing and shipping addresses did not match"
2. The order should be processed as it is in the store front

### Actual result (*)

1. Get the following error:
![image](https://user-images.githubusercontent.com/1612032/54840322-7fdfc200-4cab-11e9-84b6-98a27a2c3c74.png)

**Comment by magento-engcom-team** [comment]
Hi @fgmonad. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@fgmonad do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @fgmonad thank you for you report, but i'm not able to reproduce following steps you described, In your case you have response from paypal with array, but according to devdocs, it always string wich contains xml_ fraud rules, you can check it here -> https://developer.paypal.com/docs/classic/payflow/fraud-protection/#screening-transactions-using-the-payflow-sdk
![DeepinScreenshot_select-area_20190327101224](https://user-images.githubusercontent.com/40756439/55059897-d3ba2480-5078-11e9-98d2-c09c20fca036.png)  

Could you please try reproduce this with clean magento ? thanks.

**Comment by ghost** [comment]
@fgmonad we are closing this issue due inactivity. Feel free to reopen this one, if issue still exists.
