### ISSUE TITLE
Tax Calculation Issue

### ISSUE THREAD

**Issue by rgarner1987** [magento/magento2#21903]
### Preconditions (*)
I am using Magento 2.1 and have set up 20% VAT on all UK and EU orders and I believe I have configured the tax settings correctly to include tax in the products and show it correctly in the cart/checkout.

![screenshot](https://user-images.githubusercontent.com/43443121/54847092-5d629e80-4cd5-11e9-802e-3560d3c76741.jpg)

### Steps to reproduce (*)
When I add my £300 product to cart the price changes to £250 (this is the amount less the 20% tax). The cart then shows tax on £250.

<img width="278" alt="Screen Shot 2019-03-22 at 19 07 14" src="https://user-images.githubusercontent.com/43443121/54847305-ec6fb680-4cd5-11e9-8822-197f5ff5bb0c.png">
<img width="394" alt="Screen Shot 2019-03-22 at 19 07 27" src="https://user-images.githubusercontent.com/43443121/54847321-f1cd0100-4cd5-11e9-9d8d-12afbcd76dc6.png">
<img width="1129" alt="Screen Shot 2019-03-22 at 19 07 55" src="https://user-images.githubusercontent.com/43443121/54847329-f5f91e80-4cd5-11e9-9e80-3833661704cd.png">

### Expected result (*)
What should happen is that when I add a product to Cart/Checkout the subtotal should include 20% tax of £50 (subtotal of £300).

### Actual result (*)
When I add my £300 product to cart the tax (20%/£50) is removed from the price and tax is calculated on the incorrect figure.

**Comment by magento-engcom-team** [comment]
Hi @rgarner1987. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rgarner1987 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tomekjordan** [comment]
Why you raise bugs if your store configuration is not correct? Better read about tax calculations and how to create tax rules. then raise bugs - if you are 100% convinced its a bug.
Beause your ticket is a waste of time. its not a bug, you haven't created any tax rules yet!

**Comment by rgarner1987** [comment]
I didn't open a bug report, I chose "open a regular issue".

<img width="785" alt="Screen Shot 2019-03-23 at 18 15 54" src="https://user-images.githubusercontent.com/43443121/54869957-dcb8a680-4d97-11e9-91b5-7f7f19cd3cb2.png">

**Comment by rgarner1987** [comment]
I didn't open a bug report, I chose "open a regular issue".

<img width="785" alt="Screen Shot 2019-03-23 at 18 15 54" src="https://user-images.githubusercontent.com/43443121/54869957-dcb8a680-4d97-11e9-91b5-7f7f19cd3cb2.png">

I have also created tax rules. Did I not say above that I have created 20% VAT? I did.

<img width="1814" alt="Screen Shot 2019-03-23 at 18 19 09" src="https://user-images.githubusercontent.com/43443121/54869981-52bd0d80-4d98-11e9-9a60-a0db4ccc56ed.png">

I await your _helpful_ reply.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @rgarner1987   i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading.
