### ISSUE TITLE
Bug on Discount calculation

### ISSUE THREAD

**Issue by barbarich-p** [magento/magento2#2190]
Hello, 
I found a bug on discount calculation.

File app/code/Magento/SalesRule/Model/RulesApplier.php Line 143
```
$qty = $this->validatorUtility->getItemQty($item, $rule);
```
deeper - 
```
 public function getItemQty($item, $rule)
 {
 $qty = $item->getTotalQty();
 $discountQty = $rule->getDiscountQty();
 return $discountQty ? min($qty, $discountQty) : $qty;
 }
```

Line 157 - ```$this->validatorUtility->minFix($discountData, $item, $qty);```
go deeper - 
File app/code/Magento/SalesRule/Model/Utility.php
```$discountAmount = min($itemDiscountAmount + $discountData->getAmount(), $itemPrice * $qty);```

As a result, if some rule with field DiscountQty is applied after a rule without this field, the second one redefines the discount of the first one.

I wrote a blog post with more details about the issue here - https://blog.amasty.com/little-known-discount-issue-in-magento-and-how-to-fix-it/

This bug comes from Magento 1, and also you can reproduce this issue at all Magento 1.4 + versions

**Comment by choukalos** [comment]
Update from Team - currently this is per design

In the Priority field, set the promotion’s priority. This is useful if you have two or more shopping cart price rules enabled at once. This priority tells Magento in which order to process the rules. This is important because it may affect the final amount of the discount.

Example
You have two rules: “10% off T-shirts” and “$1 off all Blue items”. If you prioritize the 10% rule first, a $20 Blue T-shirt would first receive a 10% discount of $2 and then a $1 discount. However, if you prioritize the $1 rule first, a $20 blue T-shirt would first receive a $1 discount and then a 10% discount of $1.90. The priority affects the total discount offered.

Converting this into a feature request and tagging Olena for review as she's exploring changes to the promotion system in Magento.

**Comment by tkacheva** [comment]
Clear priority for promos is in promotion enhancements backlog -  MAGETWO-36565

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Bug-on-Discount-calculation/idi-p/46512).
