### ISSUE TITLE
Magento 2.3.0 nginx config 404 error using wget

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#21909]
So I have a very strange and severe issue with the Nginx config bundled with the installation. When using wget I can generate 404 error pages on home page, category page, product page on uncached requests. But when I use a browser the site works fine.

The site also works fine with Apache. So this is 100% an Nginx issue with something related to Magento.

This causes a real issue if I want to use wget for example to cache warmup the site with a crawler. And even the thought of someone using wget on my site to render 404 pages that are then CACHED as 404 pages, for production sites is mindboggling and I see this as a security issue.

How this is technically possible, I don't know but it has to do with Nginx config.

I have been able to reproduce this issue on two freshly installed servers.

### Preconditions (*)

1. Magento 2.3.0
2. Nginx 1.10.3
3. PHP 7.1.26
4. Default Nginx config located in file `nginx.conf.sample`
5. wget 1.18
6. Default Luma theme and sample data

### Steps to reproduce (*)

1. Configure Nginx to work as usual instead of Apache on port 80
2. Enable Magento Filesystem Cache
3. Run the following wget command to crawl the site:
`wget --spider -o wget.log -e robots=off -r -l 5 -p -S -T3 --header="X-Bypass-Cache: 1" -H --domains=example.com http://example.com --delete-after`

This should start crawling the site and generate a log file in `wget.log`. It should die immediately because of the broken link.

In the log file you should see:
```
Remote file does not exist -- broken link!!!

Found 1 broken link.

http://example.com
```

And finally visit the page in browser, you see the 404 error page "Whoops".

Now clear cache and try with your favorite browser instead and the site should work fine.

### Expected result (*)

Able to crawl site using wget without generating 404 cache pages.

### Actual result (*)

Generates 404 cache pages.

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Zyles do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21909-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21909-2-3-develop.instances.magento-community.engineering/admin](https://i-21909-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @Zyles duplicate to this -> https://github.com/magento/magento2/issues/21299
