### ISSUE TITLE
Complex Multi Store Issue

### ISSUE THREAD

**Issue by rgarner1987** [magento/magento2#21902]
### Preconditions (*)
I am building a Magento 2.1 site on A2 dedicated hosting and want my website to have 3 _sub-folder_ domains (NOT subdomains) for SEO purposes.

### Steps to reproduce (*)
I have created three websites in "**Stores > All Stores**" as well as in the FTP **(public_html)**, all with the same base domain name (thespacecollective.com).

**i.e.**
thespacecollective.com (base domain)
thespacecollective.com/us
thespacecollective.com/eu-wholesale
thespacecollective.com/us-wholesale

I have also set up different Stores and Store Views (see below).

<img width="1392" alt="Screen Shot 2019-03-22 at 18 37 46" src="https://user-images.githubusercontent.com/43443121/54845872-73229480-4cd2-11e9-9fbf-025a6c987352.png">

<img width="208" alt="Screen Shot 2019-03-22 at 18 21 23" src="https://user-images.githubusercontent.com/43443121/54845905-86356480-4cd2-11e9-87fd-90d8911d299c.png">

### Expected result (*)
My desire is that each of the websites should appear in the "Change Store View" and populate the sub-folders I have created in the FTP (public_html).

<img width="191" alt="Screen Shot 2019-03-22 at 18 45 37" src="https://user-images.githubusercontent.com/43443121/54845987-bc72e400-4cd2-11e9-8559-25f2cfb8c638.png">

### Actual result (*)
What actually happens is that no store views appear.

**Comment by magento-engcom-team** [comment]
Hi @rgarner1987. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@rgarner1987 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @rgarner1987   i'm not able to reproduce following steps your described, only 2.2.0+ bug reports are considered nowadays. Try upgrading. also please refer to -> https://devdocs.magento.com/guides/v2.3/config-guide/multi-site/ms_websites.html
