### ISSUE TITLE
Magento 2.3 & 2.3.1 develop cron indexing is not working

### ISSUE THREAD

**Issue by tomekjordan** [magento/magento2#21912]
### Preconditions (*)

Magento 2.3.0 or latest 2.3.x develop version
PHP 7.1.27
Debian 9 x64

### Steps to reproduce (*)

1. Install vanilla Magento 2.3.0 or latest 2.3.x develop version
2. Set indexes to be updated by schedule
3. Crontab is working and its correctly set with */1
php -f /home/admin/domains/domain.com/public_html/bin/magento cron:run >/dev/null 2>&1

### Expected result (*)

1. Correct index refresh each time cron is run

### Actual result (*)

1. indexers are not refreshed
2. Only manual reindex via cli is working with  php bin/magento indexer:reindex
3. Behavior observed on all Magento 2.3 and 2.3.x installs - by composer or installatron or by manual install from zip.
Server correctly set, other apps cron are working, logs shows cron is run each minute, but Magento 2.3.x still shows all indexers except Design Config Grid need update

**Comment by magento-engcom-team** [comment]
Hi @tomekjordan. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tomekjordan do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hmphu** [comment]
@tomekjordan Could you please run the command `php bin/magento indexer:status` and see the Schedule Status colum? Is this always in working status despite the backlog number is still increase?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @tomekjordan thank you for you report i;m not able to reproduce following steps you described.
![DeepinScreenshot_select-area_20190325141035](https://user-images.githubusercontent.com/40756439/54918780-d21d1f00-4f07-11e9-9b81-005eb6be8639.png)

**Comment by tomekjordan** [comment]
admin@serwer:~/domains/domain.com/public_html/3$ php bin/magento indexer:status
+----------------------+------------------+-----------+---------------------+---------------------+
| Title                | Status           | Update On | Schedule Status     | Schedule Updated    |
+----------------------+------------------+-----------+---------------------+---------------------+
| Catalog Product Rule | Ready            | Schedule  | idle (3 in backlog) | 2019-03-25 16:59:28 |
| Catalog Rule Product | Ready            | Schedule  | idle (0 in backlog) | 2019-03-25 16:59:27 |
| Catalog Search       | Reindex required | Schedule  | idle (3 in backlog) | 2019-03-25 16:59:28 |
| Category Products    | Reindex required | Schedule  | idle (3 in backlog) | 2019-03-25 16:59:26 |
| Customer Grid        | Reindex required | Schedule  | idle (0 in backlog) | 2019-03-25 16:59:26 |
| Design Config Grid   | Ready            | Schedule  | idle (0 in backlog) | 2019-03-25 16:59:26 |
| Product Categories   | Ready            | Schedule  | idle (2 in backlog) | 2019-03-25 16:59:27 |
| Product EAV          | Ready            | Schedule  | idle (3 in backlog) | 2019-03-25 16:59:27 |
| Product Price        | Ready            | Schedule  | idle (3 in backlog) | 2019-03-25 16:59:27 |
| Stock                | Ready            | Schedule  | idle (3 in backlog) | 2019-03-25 16:59:27 |
+----------------------+------------------+-----------+---------------------+---------------------+

Looks like cron is not triggered, But it works, I checked it and it should work normally, crontab shows everything OK, but its not running. The problem didnt appear in 2.2.5 or 2.2.6. It appeared in 2.3.0 and continunes in latest develop versions.
OR
cron command is not correct? php -f /home/admin/domains/d*****.com/public_html/bin/magento cron:run >/dev/null 2>&1

Dont know why, but its vanilla install, everything should work, and each time I try to install Magento 2.3.0  the problem appears.

**Comment by tomekjordan** [comment]
UPDATE: dont know if the problem is not related to the timezone in the store.

admin@serwer:~/domains/domain.com/public_html$ php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
admin@serwer:~/domains/domain.com/public_html$ php bin/magento indexer:status
+----------------------+--------+-----------+---------------------+---------------------+
| Title                | Status | Update On | Schedule Status     | Schedule Updated    |
+----------------------+--------+-----------+---------------------+---------------------+
| Catalog Product Rule | Ready  | Schedule  | idle (2 in backlog) | 2019-03-25 17:42:04 |
| Catalog Rule Product | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:28 |
| Catalog Search       | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:29 |
| Category Products    | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:28 |
| Customer Grid        | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:28 |
| Design Config Grid   | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:27 |
| Product Categories   | Ready  | Schedule  | idle (2 in backlog) | 2019-03-25 17:42:02 |
| Product EAV          | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:29 |
| Product Price        | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:29 |
| Stock                | Ready  | Schedule  | idle (0 in backlog) | 2019-03-25 17:56:29 |
+----------------------+--------+-----------+---------------------+---------------------+
admin@serwer:~/domains/domain.com/public_html$ date
Mon Mar 25 18:56:38 CET 2019


as you see scheduled jobs are for 17.42 while I already have 18.52
gives 1 hour difference. and maybe this is the problem Cronjobs are not starting because they are already in the past? I saw similar things in Content Staging - that didnt trigger at a time.
I'm using CET time, which is GMT+1 or UTC+1
Server is set correctly but the problem appear only in Magento 2.

**Comment by tomekjordan** [comment]
Sorry, we can close, cron was not working due to it was not set according to Magento manual for M2.
It was created manually instead of php bin/magento cron:install.
This command helped with all things

Funny that:
`* | * | * | * | * | /usr/local/php71/bin/php71 /home/admin/domains/domain.com/public_html/3/bin/magento cron:run 2>&1`
WORKED, 
while manually set:
`*/1 | * | * | * | * | php -f /home/admin/domains/domain.com/public_html/3/bin/magento cron:run >/dev/null 2>&1`

DIDNT' work

Anybody knows the reason?

**Comment by ghost** [comment]
@tomekjordan i think cron must run magento every time but not */1 (every minute), or path must be full to the binary file. i'm closing this one, as this is non-issue. Thanks for collaboration.

**Comment by ghost** [comment]
@tomekjordan on first example you run php on second php71 this may be the problem
