### ISSUE TITLE
Magento 2.3 install without composer

### ISSUE THREAD

**Issue by czokie** [magento/magento2#21915]
### Preconditions (*)
1. Magento 2.3
2. BlueOnyx 5209R server (Centos 7.x based)
3. Apache 2.4.6
4. PHP 7.3.3
5. FPM/FastCGI for PHP invocation
6. MariaDB 5.6.60

### Requirement
Need to install without using Composer by using either CLI install or setup.php install. End goal is to have this wrapped into a package that will install on BlueOnyx (similar to say a Plesk or installation installer). Your documentation indicates that an install using the cli or setup wizard is supported, however it does not function in accordance with your documentation.

### Steps to reproduce (*)
1. Follow documented install process here: https://devdocs.magento.com/guides/v2.3/install-gde/install-flow-diagram.html
2. Setup environment and test
3. Get Magento software as a compressed archive, and unpack
4. Ensure permissions and file ownership are set correctly after unpacking.
5. Either (a) Attempt to run bin/magento or go to setup.php page

### Expected result (*)
1. Successful install

### Actual result (*)
> Autoload error
> Vendor autoload is not found. Please run 'composer install' under application root directory.

**Comment by magento-engcom-team** [comment]
Hi @czokie. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@czokie do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by czokie** [comment]
Note: Reproduce question is not applicable. Vanilla instance build would use composer. This is attempting an install without composer, in accordance with your documentation for this install variant.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @czokie thank you for you report i'm not able to reproduce following steps you described. https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli.html 
![DeepinScreenshot_select-area_20190325123120](https://user-images.githubusercontent.com/40756439/54912741-ebb76a00-4ef9-11e9-96f6-abe6b5ecc1d3.png)
![DeepinScreenshot_select-area_20190325123359](https://user-images.githubusercontent.com/40756439/54912896-49e44d00-4efa-11e9-85e3-476494aad206.png)

**Comment by czokie** [comment]
Um. I don't see how that is possible. Remember, your test suite is installing vanilla builds that may have a composer file already created.

Looking at the flow:
1. setup/index.php includes app/bootstrap.php
2. bootstrap.php includes app/autoload.php
3. autoload.php looks for ../vendor/autoload.php which does not exist, and an exception is thrown.

For this to work on your test server, vendor/autoload.php must exist. It is not provided in the archive files, and the instructions do not provide any details for creation of this file.

**Comment by ghost** [comment]
@czokie I'm just downloaded package from -> https://magento.com/tech-resources/download 
and install via command line.

**Comment by czokie** [comment]
ACK> I downloaded from GitHub release archive - I will try to get a copy from there - it is possible that there is a difference in that file and those provided on GitHub. I will advise after I get the archive from the link you provided.

**Comment by czokie** [comment]
Confirmed - the GitHub archive release files are not the same as the files on the link you provided. I am yet to test, but I am confident that will resolve the issue. Can I humbly suggest it might be worthwhile providing copies  of the full release files on GitHub going forward as an option.
