### ISSUE TITLE
Magento 2.3 Import customer addresses _address_default_shipping_ not working

### ISSUE THREAD

**Issue by onepack** [magento/magento2#21914]
### Preconditions (*)

1. Magento 2.3
2. PHP 7.2
3. No sample data

### Steps to reproduce (*)

1. First import all customers with a customer main file.
2. Import all addresses as default billing and default shipping.
2. Create an 3th import file with all customers that have an extra addresses for shipping that is default.
3. Set _address_default_billing_ to 0 and _address_default_shipping_ to 1.
4. Import the new address for an customer with customer addresses + add/update as options.
--

### Expected result (*)

1. I expect a new extra default shipping address to be created next to the default billing.

### Actual result (*)

1. The new shipping address will overwrite _address_default_billing_ no matter if I set   _address_default_billing_ to 0 and _address_default_shipping_ to 1.
2. there is never a second address created.

**Comment by magento-engcom-team** [comment]
Hi @onepack. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@onepack do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by onepack** [comment]
M2.3 is in developer mode
I have deleted all generated files
Two modules that might interfere with the customer logic were disabled. (Mailchimp by Ebizmarts and login as customer by magefan.)
I have cleared the import history.
Renamed the .csv file.
Set the error count to 1.

Nothing in the logs
Just always an overwrite of the default billing.

I can manually add a new address but the import fails and with 500 extra default shipping addresses this is going to be a problem.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98867`, `MAGETWO-98868` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by mahesh-rajawat** [comment]
I am working on this at #dmcdindia1

**Comment by mahesh-rajawat** [comment]
@onepack , i have followed the below steps.
Magento 2.3.1 fresh installation.

1. import customers with Customers Main file. (customers imported successfully).
2. import Customer Addresses with default billing and shipping 1 .
3. import Customers and Addresses (single file) with default billing 0 and shipping 1.

Result:
I can see that there is a new entry for address an default shipping address updated.

**Comment by magento-engcom-team** [comment]
Hi @onepack. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-24422` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
