### ISSUE TITLE
Magento backend catalog "MSRP" without currency symbol

### ISSUE THREAD

**Issue by mage2pratik** [magento/magento2#21910]
### Preconditions (*)

1. Magento 2.3.X
2. Magento 2.2.X

### Steps to reproduce (*)

1. Admin Menu > Stores > Settings > Configuration > Sales > Minimum Advertised Price = Yes
2. Navigate to admin catalog product grid
3. Using "Columns" selection, add 'Manufacturer's Suggested Retail Price'(MSRP) column in the grid

### Expected result (*)

1. "MSRP" will be shown with currency code

### Actual result (*)

![Screenshot](https://user-images.githubusercontent.com/33807558/54871080-f9270400-4dd4-11e9-9f5f-4adb3266d51f.png)

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mage2pratik do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by orlangur** [comment]
Same steps applicable to Special Price field also. Whoever will fix it, please fix both cases within the same issue.

@mage2pratik, please do not set labels like `Reproduced on ...` by yourself.

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-21910-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21910-2-3-develop.instances.magento-community.engineering/admin](https://i-21910-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-21910-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21910-2-2-develop.instances.magento-community.engineering/admin](https://i-21910-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [Magento instance](https://i-21910-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21910-2-3-develop.instances.magento-community.engineering/admin](https://i-21910-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98854`, `MAGETWO-98855` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment]
The issue is reproducible for both 2.2.x and 2.3.x versions.
![Screen Shot 2019-03-25 at 1 40 45 PM](https://user-images.githubusercontent.com/11693779/54917103-b9126f00-4f03-11e9-9568-8f4b831b2bf2.png)

**Comment by rohitkundale** [comment]
I am working on this at #dmcdindia19

**Comment by paco44** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @paco44. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @paco44, here is your [Magento instance](https://i-21910-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21910-2-3-develop.instances.magento-community.engineering/admin](https://i-21910-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by paco44** [comment]
#cd19latam

**Comment by 00F100** [comment]
i working in this fix

**Comment by 00F100** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @00F100. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @00F100, here is your [Magento instance](https://i-21910-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21910-2-3-develop.instances.magento-community.engineering/admin](https://i-21910-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kkorushkin** [comment]
This issue is appearing on **Special Price** column as well.
![21910](https://user-images.githubusercontent.com/13004402/66217472-0ac85d00-e6d0-11e9-9cd1-60b0eea9a22a.png)

**Comment by akondratenkeo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @alexkwellbe. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @alexkwellbe, here is your [Magento instance](https://i-21910-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21910-2-3-develop.instances.magento-community.engineering/admin](https://i-21910-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment]
Hi @mage2pratik. Thank you for your report. 
The issue has been fixed in magento/magento2#27261 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [d81d1d451bb7f10492d249e2c0c70e9d8d1df905](https://github.com/magento/magento2/commit/d81d1d451bb7f10492d249e2c0c70e9d8d1df905)

The fix will be available with the upcoming 2.4.0 release.
