### ISSUE TITLE
EAV Attibute argument attribute_set_id is ignored

### ISSUE THREAD

**Issue by frostblogNet** [magento/magento2#21923]
According to this magento documentation (https://devdocs.magento.com/guides/v2.3/extension-dev-guide/attributes.html) it is possible to assign a new attibute directly to a attribute set using the parametert attribute_set_id.

### Preconditions (*)
1. magento 2.3.0 CE and EE

### Steps to reproduce (*)
1. Create a Attibute Set which is a child of the default attribute set
2. Now create a update data scipt which added a new eav attribute like this.

` $eavSetup->addAttribute(
                Product::ENTITY,
                'collections',
                [
                    'label' => 'Season',
                    'attribute_set_id' => 11, // change to your id
                    'group' => 'assortment',
                    'type' => 'text',
                    'input' => 'multiselect',
                    'backend' => \Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend::class,
                    'required' => false,
                    'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
                    'user_defined' => true,
                    'visible' => true,
                    'visible_on_front' => true,
                    'used_in_product_listing' => true,
                    'filterable' => true,
                    'is_filterable_in_grid' => true,
                    'is_used_in_grid' => true
                ]
            );`

3. Login to the admin menue go to attribute sets and see that it is assigned to default not to the one you aspected.

### Expected result (*)
This new attribute should only be assigned to the child attribute set not to the default once.

### Actual result (*)
1. attribute is assigned to the default set.

**Comment by magento-engcom-team** [comment]
Hi @frostblogNet. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@frostblogNet do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @frostblogNet thank you for you report, this is duplicate to this -> https://github.com/magento/magento2/issues/14793
