### ISSUE TITLE
No password validation when removing user role

### ISSUE THREAD

**Issue by luffarvante** [magento/magento2#21937]
### Preconditions (*)
1. Magento 2.2.6 (Community and Commerce)
2. Added a custom user role
3. Logged in to a user with permissions to edit user roles

### Steps to reproduce (*)
1. Navigate to User Roles (Admin > System > Permissions > User Roles)
2. Create a new User Role
3. Delete the newly created User Role

### Expected result (*)

1. The action should require you to insert your password, the same way any other User and User Role related action requires.
2. The excepted result can be found if you try this action on a Admin User; it has both front- and backend validation.

### Actual result (*)

1. The User Role is removed without any validation required

**Comment by magento-engcom-team** [comment]
Hi @luffarvante. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@luffarvante do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by orlangur** [comment]
@luffarvante are there validations in case you assign some users to role after "Create a new User Role"?

**Comment by luffarvante** [comment]
@orlangur as far as i can tell, there is validation on every action on user roles, except for the "Delete" button.

**Comment by orlangur** [comment]
Ok, I mean there is no reason to prevent role deletion without users assigned.

**Comment by luffarvante** [comment]
Oh sorry, i misunderstood your question.
I have to check when i get back into the office tomorrow, but i think i can remove it even if it has users assigned. Regardless it's still odd you can remove but not rename a role, no?

**Comment by orlangur** [comment]
@luffarvante I mean I wouldn't add any additional check if there are no users assigned - this is not a harmful operation. While other actions may change permissions and then we need a confirmation.

But probably we don't need a confirmation for deletion at all as it is not a security breach.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @luffarvante thank you for you report, this is expected behavior, as a @orlangur says that not a security breach.

**Comment by luffarvante** [comment]
@orlangur i checked now and i can delete groups with members in them as well, without any validation.

What happens if someone removes the administrator group? Suddenly all the site admins wont be able to access the site at all.
From my point of view there should either be validation when deleting roles, or no validation for fields like changing name and such at least.

Maybe its intentional but i get the impression that its simply an oversight and the original intention was to have it work like the Users tab does.

If its a question of time, i figure i could just solve it myself sometime next week as well, although i haven't really looked into whats required to contribute to CE.

**Comment by orlangur** [comment]
@luffarvante,

> What happens if someone removes the administrator group? Suddenly all the site admins wont be able to access the site at all.

This case could be valid as to me.

> Logged in to a user with permissions to edit user roles

Please check if such user with limited permissions is able to affect superadmins so that they are not able to administrate.

**Comment by luffarvante** [comment]
Isn't the point of having an extra password validation on the user role management page to stop unauthorized users from modifying the roles **at all** in case they find a computer where a admin with the correct ACL to do this is logged in?

I mean, either you allow a user with the correct permissions to change user roles without password, or you require a password as a extra security measure.
Right now anyone that stumbles upon a computer with a logged in admin account (with the correct permissions) could simply wipe all user groups, efficiently locking everyone out.

It's not a huge security flaw or anything, i just saw something that seemed like an oversight, but if you feel it is not an issue i can just fix it in our internal bugfix module.

**Comment by orlangur** [comment]
> could simply wipe all user groups, efficiently locking everyone out

@luffarvante just check that this can actually happen and feel free to reopen issue. Also, you can try git blame for some other password-checking code to see if there is some thinking behind bypassing it for deletion.
