### ISSUE TITLE
Freezing browser when filling new product form (title)

### ISSUE THREAD

**Issue by francescorm** [magento/magento2#21935]
### Preconditions (*)
Magento 2.2.6

### Steps to reproduce (*)
Create new product, filling title before the sku, every browser and platform freeze.
If i fill the sku before the titile it's okey

### Expected result (*)
1. No freezing Browser, i should fill the form without problem.
2.

### Actual result (*)

1. Freezing browser.
Reading the logs i have an error
"Too Much Recursion" on observable_array.js

![Schermata del 2019-03-26 11-40-01](https://user-images.githubusercontent.com/47854158/54991674-bd9b5e00-4fbd-11e9-8124-b9c6a0b5310b.png)

**Comment by magento-engcom-team** [comment]
Hi @francescorm. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@francescorm do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by francescorm** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @francescorm. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @francescorm, here is your [Magento instance](https://i-21935-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21935-2-2-develop.instances.magento-community.engineering/admin](https://i-21935-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by francescorm** [comment]
no, i was not able to reproduce the issue. Does it means it depends on other problems?

**Comment by ghost** [comment]
Hi @francescorm yes problem may be related to one of your custom modules.

**Comment by ghost** [comment]
@francescorm i'm closing this one, as this is not reproducible on 2.2-develop branch, if you have some additional steps that help us to reproduce this issue on clean magento, please reopen the issue.
