### ISSUE TITLE
2.3.1 Fatal error: Class Temando\Shipping\Rest\ShipmentAdapter contains 1 abstract method and must therefore be declared abstract

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#21947]
### Preconditions (*)
1. Magento 2.3.1

Fatal error: Class Temando\Shipping\Rest\ShipmentAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Temando\Shipping\Rest\Adapter\ShipmentApiInterface::getTrackingEvents) in /vendor/temando/module-shipping-m2/Rest/ShipmentAdapter.php on line 32

### Steps to reproduce (*)
1. Upgrade from 2.3.0 to 2.3.1
2. Clear cache, run bin/magento setup:upgrade
3. Clear cache, View home page

### Expected result (*)
1. No error

### Actual result (*)
1. [Screenshots, logs or description]

As above.

**Comment by magento-engcom-team** [comment]
Hi @craigcarnell. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@craigcarnell do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by cscd98** [comment]
Error seems to have gone away, will close for now..
