### ISSUE TITLE
Duplicated Unique Route Frontname

### ISSUE THREAD

**Issue by LucianMihalache** [magento/magento2#21958]
### Preconditions (*)
1. Magento 2.3.1 (Upgraded from 2.3.0)

### Steps to reproduce (*)

1. Have backend url "admin"
![adminuri](https://user-images.githubusercontent.com/48981554/55060336-eb45dd00-5079-11e9-820a-d89ec2796d9e.png)

2. Have custom module with custom route that uses frontname "admin"
![route](https://user-images.githubusercontent.com/48981554/55060344-eed96400-5079-11e9-900a-eae4defcd259.png)

### Expected result (*)

1. When accessing the backend (/admin), admin should render as normal.

### Actual result (*)

1. Exception happening:

> 1 exception(s):
> Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid Document 
> Element 'route': Duplicate key-sequence ['admin'] in unique identity-constraint 'uniqueRouteFrontName'.
> Line: 5

![bug](https://user-images.githubusercontent.com/48981554/55060146-796d9380-5079-11e9-808b-c9f3370ae25d.png)

**Comment by magento-engcom-team** [comment]
Hi @LucianMihaalche. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@LucianMihaalche do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by LucianMihalache** [comment]
@magento-engcom-team give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LucianMihaalche. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @LucianMihaalche thank you for you report, please do not use Frontname as admin, this is not best practice. This issue related to 3th party extension. please contact to the developer of this extension.

**Comment by ghost** [comment]
@LucianMihaalche or as temporary fix you can set different admin name in app/etc/env.php
![DeepinScreenshot_select-area_20190327103811](https://user-images.githubusercontent.com/40756439/55061425-6c9e6f00-507c-11e9-9408-37d7eae1a868.png)

**Comment by LucianMihalache** [comment]
@engcom-backlog-nazar Thank you for your response. I know that this is not best practices, that is my dev env.
Before upgrading to 2.3.1, the component worked as expected and no exception was thrown.

I wanted to report this because I thought there might be a problem when you'd want to use the same frontend route multiple times in different components. And I wanted to have all my backend routes follow the default backend frontname (admin).

Edit: but since there is no problem, this should remain closed.

**Comment by ghost** [comment]
@LucianMihaalche according to  https://devdocs.magento.com/guides/v2.3/extension-dev-guide/routing.html 
![DeepinScreenshot_select-area_20190327105142](https://user-images.githubusercontent.com/40756439/55062295-51346380-507e-11e9-87d4-825b8b2574c5.png)
