### ISSUE TITLE
How to get the current category without a registry? 

### ISSUE THREAD

**Issue by ityetti** [magento/magento2#21950]
### Summary (*)

Hello, everyone. I develop a small extension which adds custom banner for the category. And faced with an interesting problem. I can't get the current category without using the registry. I checked core files and all code that I find looks like - 
`$this->_coreRegistry->register('current_category', $category);`
`$this->_coreRegistry->registry('current_category');`

But when I try to use the registry in custom extension, I catch an error that registry is deprecated. You can check it this - https://github.com/magento/magento2/blob/4f6c78e81b3d91947287094316682461b06d372f/lib/internal/Magento/Framework/Registry.php#L26-L40

**All that I need on the current category page get a custom attribute. That's all. But I want to do this without deprecated methods.**

### Examples (*)

For the custom model, I use dataPersisor and my code looks like this.
`$data = $this->getRequest()->getPostValue();`
`$this->entityRepository->save($model);`
`$this->messageManager->addSuccessMessage(__('You saved the entity.'));`
`$this->dataPersistor->set('entity', $data);`
Where dataPersistor is https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/App/Request/DataPersistorInterface.php

### Proposed solution

My thoughts. Ideally, add some dataPersistor instead of register. But this is still a dream. 
Who solved this problem and what are the options and ideas?

**Comment by magento-engcom-team** [comment]
Hi @ityetti. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ityetti do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Bartlomiejsz** [comment]
@ityetti you should use `$categoryId = (int)$this->getRequest()->getParam('id', false);`, and then with instantiated `\Magento\Catalog\Api\CategoryRepositoryInterface` use `$this->categoryRepository->get($categoryId);`.

But keep in mind that this is rather technical question and should be asked on i.e. stackoverflow. Github is place for issues only.

**Comment by ityetti** [comment]
@Bartlomiejsz got it, thanks.
