### ISSUE TITLE
Able to use a single use coupon code on two orders

### ISSUE THREAD

**Issue by bawwwa** [magento/magento2#21952]
### Preconditions (*)

1. Magento 2.2.7 and Magento 2.3.0 (community and enterprise) 
2. Installed with sample data and theme used 'Magento Luma'

### Steps to reproduce (*)

1. Created a cart price rule with a specific code '20OFF' with an action to discount everything with 20%.
2. Uses per coupon code should be set to 1. ![image](https://user-images.githubusercontent.com/45529692/55042168-775d0200-5084-11e9-974e-bf9dd3375a58.png)
3. Browser the website using two browsers (2 sessions) and add the coupon to the cart. 
4. Place orders at the same time.

### Expected result (*)

1. Only one order should be successful. 
2. Second order should result in an error due to the coupon code or be placed without the discount.

### Actual result (*)

1. Both orders are being placed. 
Order #'000000008'
![image](https://user-images.githubusercontent.com/45529692/55042313-09fda100-5085-11e9-9d52-4128aa11fff1.png)

Order #'000000009'
![image](https://user-images.githubusercontent.com/45529692/55042278-e3d80100-5084-11e9-9f35-90e9e5addec2.png)

NOTE: On enterprise the same issue is visible with the giftcards. $60 giftcard can be used in two orders if placed at the same time. 

Giftcard history for the enterprise installation.
![image](https://user-images.githubusercontent.com/45529692/55042379-4b8e4c00-5085-11e9-89a7-b8f2fd39c71e.png)

Thanks!

**Comment by magento-engcom-team** [comment]
Hi @bawwwa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@bawwwa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by vpodorozh** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh, here is your [Magento instance](https://i-21952-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21952-2-2-develop.instances.magento-community.engineering/admin](https://i-21952-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99095`, `MAGETWO-99096` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vpodorozh** [comment]
@magento-engcom-team give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by vpodorozh** [comment]
@magento-engcom-team give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by singhabhinay** [comment]
I am working on this at #dmcdindia1

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3.1-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3.1-develop instance for you

**Comment by Shubham0492** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-21952-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21952-2-3-develop.instances.magento-community.engineering/admin](https://i-21952-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by georgebabarus** [comment]
@magento give me 2.3.5-p1 instance

**Comment by nidhigupta13-ey** [comment]
@magento I am working on this

**Comment by nidhigupta13-ey** [comment]
Hi All,

Below is the update on this task:

I installed magento 2.3.0 instance in my local and try to reproduce the issue, but the issue is not reproducible in my local. The coupon is applied only one time and in second order the coupon is not getting applied. Below are the screenshots:

<img width="1689" alt="Screenshot 2023-10-03 at 2 12 07 PM" src="https://github.com/magento/magento2/assets/93646392/5c22c40b-c8fd-481e-9731-b84f5dfc86c9">


<img width="1699" alt="Screenshot 2023-10-03 at 2 11 25 PM" src="https://github.com/magento/magento2/assets/93646392/705bed82-1eaa-446c-8152-d1acc95d4d49">

**Comment by engcom-Bravo** [comment]
Hi @bawwwa,

As per this https://github.com/magento/magento2/issues/21952#issuecomment-1746288394 We are closing this issue since issue is no more reproducible.

Thanks.
