### ISSUE TITLE
Add to cart issue when adding bundle and configurable product at the same time

### ISSUE THREAD

**Issue by Ridik123** [magento/magento2#21969]
I am using MAgento version 2.2.7

My site has different type of products

But I am facing problem when I am adding bundle and configurable product at the same time.
Call to undefined method Magento\Bundle\Model\Product\Type::getConfigurableAttributeCollection() in /home/nichefas/public_html/perpetuity.fashionaxess.com/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php:52
Stack trace:
#0 /home/nichefas/public_html/perpetuity.fashionaxess.com/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php(48): Magento\ConfigurableProduct\Helper\Product\Options\Loader-&gt;load(Object(Magento\Catalog\Model\Product\Interceptor))
#1 /home/nichefas/public_html/perpetuity.fashionaxess.com/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Magento\ConfigurableProduct\Model\Product\ReadHandler-&gt;execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#2 /home/nichefas/public_html/perpetuity.fashionaxess.com/vendor/magento/framework/EntityManager/Operation/Read.php(112): Magento\Framework\EntityManager\Operation\Read\ReadExtensions-&gt;execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
# in <b>/home/nichefas/public_html/perpetuity.fashionaxess.com/vendor/magento/module-configurable-product/Helper/Product/Options/Loader.php</b> on line <b>52</b><br />

**Comment by magento-engcom-team** [comment]
Hi @Ridik123. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Ridik123 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Ridik123** [comment]
Summary of the issue : when i tried to add bundle and configurable product into my cart I get an issue.
both product are add to cart if i tried them seperately

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
HI @Ridik123 thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.2-develop instance, can you recheck on vanilla installation ? @magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-21969-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21969-2-2-develop.instances.magento-community.engineering/admin](https://i-21969-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@Ridik123 
![DeepinScreenshot_select-area_20190327161012](https://user-images.githubusercontent.com/40756439/55082709-d33a8180-50aa-11e9-80cd-7edcc53ea8fc.png)
