### ISSUE TITLE
2.3.1 - MFTF fails to run due defective Klarna test

### ISSUE THREAD

**Issue by magicsunday** [magento/magento2#21964]
Trying to run the MFTF tests fails due to defective tests in the module klarna/module-kp.

### Preconditions (*)
Magento 2.3.1
PHP 7.2

### Steps to reproduce (*)
Run MFTF AdminLoginTest
`vendor/bin/mftf run:test AdminLoginTest --remove`

### Expected result (*)
Test should run.

### Actual result (*)
```
Entity cannot use keys more than once.
        key: use_auto_generation is used more than once. (Parent: KpTestSalesRuleData)
        in file: /var/www/html/vendor/klarna/module-kp/Test/Mftf/Data/KpSalesRuleData.xml.
  Exception occurred parsing action at StepKey "disableWYSYWYG"

```
### Workaround
Disable the module 
`bin/magento module:disable Klarna_Kp`

Are you executing the MFTF tests yourself before releasing a new version of magento?
Why gets my AdminLoginTest stuck, if the Klarna test is misconfigured? They have both nothing to do with each other and should not rely on it!

**Comment by magento-engcom-team** [comment]
Hi @magicsunday. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@magicsunday do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by lupoiuAlinN** [comment]
https://magento.stackexchange.com/questions/269349/magento-2-3-1-mftf-is-not-generated-test-core

**Comment by lupoiuAlinN** [comment]
I have the same issue. Once i solved the problem from Klarna, i faced other issues related with the core tests.
I can't generate any test.
I am very curious if somebody from magento team was actually tested  the tests generation before the release of 2.3.

I am using EE edtion and magento 2.3.1

**Comment by mmularski** [comment]
I'm also facing this issue. Any plans for fixing it?

**Comment by engcom-Delta** [comment]
Hi @magicsunday I cannot reproduce issue on the latest composer version 2.3.2.
**Steps to reproduce:**
- Set Stores > Settings > Configuration > Advanced > Admin > Security > Add Secret Key to URLs to No.
- Set the Stores > Settings > Configuration > General > Content Management > Enable WYSIWYG Editor option to Disabled Completely
- Run MFTF AdminLoginTest `vendor/bin/mftf run:test AdminLoginTest --remove`

**Result:**
:heavy_check_mark: Test is passed
![#21964issue](https://user-images.githubusercontent.com/51681379/61525197-965f1580-aa20-11e9-8889-218e620d18fc.png)

If you'd like to update issue, please reopen it.

**Comment by WinstonN** [comment]
I get the following error which seems similar to this one, Magento 2.2.9

```
bin/mftf run:test AdminLoginTest --remove

DEPRECATION: Test AdminCreateStoreGroupTest is missing required annotations.{"testName":"AdminCreateStoreGroupTest","missingAnnotations":"severity"}
DEPRECATION: Test AdminMoveAnchoredCategoryTest is missing required annotations.{"testName":"AdminMoveAnchoredCategoryTest","missingAnnotations":"stories"}
DEPRECATION: Test DeleteCategoriesTest is missing required annotations.{"testName":"DeleteCategoriesTest","missingAnnotations":"stories"}
DEPRECATION: Test StorefrontAddMultipleStoreProductsToWishlistTest is missing required annotations.{"testName":"StorefrontAddMultipleStoreProductsToWishlistTest","missingAnnotations":"stories, severity"}
DEPRECATION: Test StorefrontDeletePersistedWishlistTest is missing required annotations.{"testName":"StorefrontDeletePersistedWishlistTest","missingAnnotations":"severity"}
DEPRECATION: Test PriceRuleCategoryNestingTest is missing required annotations.{"testName":"PriceRuleCategoryNestingTest","missingAnnotations":"stories, title"}
DEPRECATION: Test AdminConfigPaymentsSectionState is missing required annotations.{"testName":"AdminConfigPaymentsSectionState","missingAnnotations":"stories, title"}

In ActionMergeUtil.php line 278:

  Section cannot use names more than once.
  	name: v4 is used more than once. (Parent: ProductWYSIWYGSection)
  	in file: /Users/User/Projects/domain/magento2/src/dev/tests/acceptance/tests/functional/Magento/FunctionalTest/Catalog/Section/AdminProdu
  ctFormSection.xml.
  Exception occurred parsing action at StepKey "disableWYSYWYG"
```

I have the settings as described above by @magento-engcom-team 

> Hi @magicsunday I cannot reproduce issue on the latest composer version 2.3.2.
> **Steps to reproduce:**
> 
> * Set Stores > Settings > Configuration > Advanced > Admin > Security > Add Secret Key to URLs to No.
> * Set the Stores > Settings > Configuration > General > Content Management > Enable WYSIWYG Editor option to Disabled Completely
> * Run MFTF AdminLoginTest `vendor/bin/mftf run:test AdminLoginTest --remove`
> 
> **Result:**
> ✔️ Test is passed
> ![#21964issue](https://user-images.githubusercontent.com/51681379/61525197-965f1580-aa20-11e9-8889-218e620d18fc.png)
> 
> If you'd like to update issue, please reopen it.
