### ISSUE TITLE
Magento doesn't work after upgrade from 2.3.0 to 2.3.1

### ISSUE THREAD

**Issue by dweerd** [magento/magento2#21976]
### Preconditions (*)

1. Magento version 2.3.1
2. PHP version 7.1.x + Redis
3. Deploy mode: production

### Steps to reproduce (*)

1. I upgraded a production environment to magento 2.3.1
2. I ran setup:upgrade and setup:di:compile
3. I visited homepage

### Expected result (*)

1. See the homepage

### Actual result (*)

1. Server error log contained the following error: `Backend fatal error: PHP Fatal error:  Uncaught RuntimeException: Source class "\\Magento\\Cron\\Model\\Virtual" for "Magento\\Cron\\Model\\VirtualLogger" generation does not exist.`

This seems related to the following change in Magento 2.3.1: https://github.com/magento/magento2/pull/18209

**Comment by magento-engcom-team** [comment]
Hi @dweerd. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dweerd do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment]
Hi @dweerd 

Would you be able to list all the exact steps you performed after the upgrade?
Because I can't seem to reproduce this after upgrading a vanilla 2.3.0 to 2.3.1 and putting 2.3.1 in production mode.

Thanks!

**Comment by bahramdavoodi** [comment]
Hi @dweerd,
I had the same problem on Amasy Layered Navigation extension with Magento 2.3.1, but with a different error: Issue [#21916](https://github.com/magento/magento2/issues/21916). if you installed some extension, you can to try to disable one by one extensions.

Thanks

**Comment by hostep** [comment]
@bahramdavodi: thanks for the link!
If I understand it correctly, in case of this issue, it might be that some custom module has a plugin on the class `Magento\Cron\Observer\ProcessCronQueueObserver`, and by introducing a different typed `$logger` argument in #18209, it might cause this problem. (not 100% sure if this description is correct, not fully understanding it yet).

@dweerd: can you check the custom code (your own or 3rd party) if there is a plugin defined on `Magento\Cron\Observer\ProcessCronQueueObserver` somewhere?

**Comment by dweerd** [comment]
@bahramdavodi I had that same error as well, which I got around by disabling the Magento_ElasticSearch6 module. That error prevented setup:di:compile to complete. After disabling the module, the compile would run fine.

The error reported here actually didn't occur during setup:di:compile, but happens upon visiting the backend/frontend.

@hostep as far as I can tell, there is no plugin defined on that class in my code.

I didn't get the error on my development environment, but did get it on the production environment.

For the upgrade I did these things:

- enabled maintenance mode
- pulled new code from git
- ran `composer install --no-dev -o`
- `php bin/magento setup:upgrade`
- `redis-cli -s /tmp/redis.sock flushall`
- I then noticed the deploy mode was no longer 'production' so I ran `bin/magento deploy:mode:set production`
- I ran into the error linked to by @bahramdavodi, and fixed it by running `bin/magento module:disable Magento_Elasticsearch6`
- This time compilation / switching to production mode worked, and I tried visiting the frontend, ending up with the error about the Cron class.

Looking at the error, where should the class '\\Magento\\Cron\\Model\\Virtual' come from? I actually don't see this class defined in code?

**Comment by hostep** [comment]
@dweerd, thanks for the info.

Very good remark about `Magento\Cron\Model\Virtual`, this is really weird, because the virtual type `Magento\Cron\Model\VirtualLogger` got introduced in https://github.com/magento/magento2/pull/18209/files. But for some reason, in your error it strips of the `Logger` part of the class, which is really strange ...

**Comment by dweerd** [comment]
> 
> 
> @dweerd, thanks for the info.
> 
> Very good remark about `Magento\Cron\Model\Virtual`, this is really weird, because the virtual type `Magento\Cron\Model\VirtualLogger` got introduced in https://github.com/magento/magento2/pull/18209/files. But for some reason, in your error it strips of the `Logger` part of the class, which is really strange ...

See: https://magento.stackexchange.com/questions/132700/magento-2-what-are-generated-logger-classes-for. Maybe this is related?

**Comment by hostep** [comment]
@dweerd: this seems to be related to the issue https://github.com/magento/magento2/issues/21916
And there is a possible fix proposed in https://github.com/magento/magento2/pull/22046

Maybe you can test that fix and see if it fixes your issue as well?

**Comment by magento-engcom-team** [comment]
Hi @dweerd. Thank you for your report. 
The issue has been fixed in magento/magento2#22046 by @phoenix128 in 2.3-develop branch
Related commit(s):
 - [fa079c94c9c0a6d3cd7d9dca3b52d3394de50934](https://github.com/magento/magento2/commit/fa079c94c9c0a6d3cd7d9dca3b52d3394de50934)
 - [75684cadfe6231e352c959cbd0648612489b533a](https://github.com/magento/magento2/commit/75684cadfe6231e352c959cbd0648612489b533a)
 - [b8ab61b86f05c45343c78c3341920756f888904f](https://github.com/magento/magento2/commit/b8ab61b86f05c45343c78c3341920756f888904f)
 - [6d873304742ee5114ec661d6b799bd2f0a4f3cff](https://github.com/magento/magento2/commit/6d873304742ee5114ec661d6b799bd2f0a4f3cff)

The fix will be available with the upcoming 2.3.2 release.
