### ISSUE TITLE
mini cart not refreshing

### ISSUE THREAD

**Issue by singhshubham1** [magento/magento2#21988]
Hi i had install magento 2.2.7 on my site http://173.249.54.193, In this i got 2 stores. and when i am adding a product from store 1 mini cart showing proper , but when i switch to store 2 it is not getting empty. 
Can some 1 help me in this ?

**Comment by magento-engcom-team** [comment]
Hi @singhshubham1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@singhshubham1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
Hi @singhshubham1 duplicate to this -> https://github.com/magento/magento2/issues/21987
