### ISSUE TITLE
Sitemap Generating Wrong URLs

### ISSUE THREAD

**Issue by jarrar1214** [magento/magento2#21980]
### Summary
Our magento 2 store is generating sitemap with wrong URLs. It is bringing almost all the URLs "/catalog/product" like this one instead of correct URLs which are created based on product title. 

Canonical are already added with "catalog" urls but still sitemap is generating them. 

### Examples
![image](https://user-images.githubusercontent.com/47089494/55109619-07885f00-50f8-11e9-8e3b-22eb37a84895.png)

**Comment by magento-engcom-team** [comment]
Hi @jarrar1214. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@jarrar1214 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by jarrar1214** [comment]
No it is only appearing in our instance not on vanilla instance.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
Hi @jarrar1214 thank you for your report, which version of magento you use ?

**Comment by ghost** [comment]
Hi @jarrar1214 thank you for you report, i'm not able to reproduce following steps you described, on clean magento 2.3-dev instance. this may be related to your custom code or url-rewrites.

**Comment by ghost** [comment]
@jarrar1214 
![DeepinScreenshot_select-area_20190328095723](https://user-images.githubusercontent.com/40756439/55140071-e6e3f780-513f-11e9-9f1f-3f5807324ace.png)

**Comment by jarrar1214** [comment]
Hi @engcom-backlog-nazar 

We are using magento 2.2.6 and this issue is only appearing on this version i guess. 

Can you suggest some workarounds for this. How we can bring Product name urls in to the sitemap instead of catalog urls. 

Thanks
