### ISSUE TITLE
how to set different quantity in multiple store in same product and display on product that quantity

### ISSUE THREAD

**Issue by singhshubham1** [magento/magento2#21991]
how to set different quantity in multiple store in same product and display on product that quantity.
magento 2.2.7 version

please help me

**Comment by magento-engcom-team** [comment]
Hi @singhshubham1. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@singhshubham1 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by singhshubham1** [comment]
yes

**Comment by singhshubham1** [comment]
> m that you was able t

yes

**Comment by ghost** [comment]
Hi @singhshubham1 you need to set price per website in configuration.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
