### ISSUE TITLE
config:set not storing scoped values

### ISSUE THREAD

**Issue by ochnygosch** [magento/magento2#21993]
### Preconditions (*)

1. Magento 2.3.1
2. Disabled single store mode
3. Two stores
  * website_code: website_test_1, store_code: store_test_1
  * website_code: website_test_2, store_code: store_test_2

### Steps to reproduce (*)

1. execute command `bin/magento config:set --scope websites --scope-code website_test_1 web/unsecure/base_url http://test1.example.com/`
2. execute command `bin/magento config:set --scope websites --scope-code website_test_2 web/unsecure/base_url http://test2.example.com/`

### Expected result (*)

1. at least two rows in table core_config_data

scope | scope_id | path | value
--------|--------------|-------|-------
websites | <number> | web/unsecure/base_url | http://test1.example.com/
websites | <number> | web/unsecure/base_url | http://test2.example.com/

### Actual result (*)

1. Just a row for the default scope in core_config_data with the value of the last executed command

scope | scope_id | path | value
--------|--------------|-------|-------
default | 0 | web/unsecure/base_url | http://test2.example.com/

**Comment by magento-engcom-team** [comment]
Hi @ochnygosch. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ochnygosch do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98929`, `MAGETWO-98930` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @ochnygosch. Thank you for your report. 
The issue has been fixed in magento/magento2#22012 by @ochnygosch in 2.3-develop branch
Related commit(s):
 - [f826017acfb81d549d5eaada07a0081ddc2498c5](https://github.com/magento/magento2/commit/f826017acfb81d549d5eaada07a0081ddc2498c5)
 - [d53690cbfe4aeac02d05c2078424698ce1fb7d3f](https://github.com/magento/magento2/commit/d53690cbfe4aeac02d05c2078424698ce1fb7d3f)

The fix will be available with the upcoming 2.3.2 release.

**Comment by alepane21** [comment]
If someone need a fast patch for Magento 2.2 (should also work on 2.3): https://github.com/Hevelop/magento2-patches/blob/master/Patch-Magento_Config-2.2.8-fix-config-set.diff
