### ISSUE TITLE
ce231 - can't update attribute for all product

### ISSUE THREAD

**Issue by huyenvk2017** [magento/magento2#22004]
### Preconditions (*)

1. ce2.3.1
2. Create at least 2 store view

### Steps to reproduce (*)

1. Go to Catalog > Product
2. Select All Product http://prntscr.com/n429o3
3. Select mass action = Update Attribute
4, In Website tab, tick Add Product To Websites > Main Website http://prntscr.com/n42ank
5. Click Save

### Expected result (*)

1. Update all Product. Both store views will have exactly the same products
http://prntscr.com/n42hsr

### Actual result (*)

1. Only update 20 product http://prntscr.com/n42b9f

**Comment by magento-engcom-team** [comment]
Hi @huyenvk2017. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@huyenvk2017 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98933` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-22004-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22004-2-3-develop.instances.magento-community.engineering/admin](https://i-22004-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ansari-ziyaurrahman** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish, here is your [Magento instance](https://i-22004-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22004-2-3-develop.instances.magento-community.engineering/admin](https://i-22004-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mwr** [comment]
I can confirm the issue with an 2.3.1 Magento instance.

**Comment by tufahu** [comment]
@ansari-krish have you started to make PR?

**Comment by tufahu** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tufahu. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tufahu, here is your [Magento instance](https://i-22004-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22004-2-3-develop.instances.magento-community.engineering/admin](https://i-22004-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment]
I can confirm this problem exist in 2.3.1 vanila version
grid only pass all items of first page only not all item ids

**Comment by mrtuvn** [comment]
![Screenshot from 2019-04-20 19-07-58](https://user-images.githubusercontent.com/1908873/56457080-ec7bd880-639f-11e9-979b-f1ad5d0410d4.png)
the variable **selected** seem set wrong value because in this selection value should be max total records
Link reference
https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js#L437

**Comment by shikhamis11** [comment]
I am working on this at #dmcdindia1

**Comment by tufahu** [comment]
Ah, thank you @shikhamis11 !! I had no time for it :\

**Comment by Green2Matter** [comment]
I see very similar behavior in our instance.
We use Magento 2.4.6-p3, php8.2... I want to do mass edit of products attributes in backend grid.

After choosing select All - confirmation is visible saying for example: 7565 records found (7565 selected).
So, I select Update attribute, do editing and click Save.
Result says: "Task "Update attributes for 7565 selected products": 76 item(s) have been successfully updated." Every 100 item is updated? It seems like magento selects every 100 item. If I select 200 products, only 2 are updated. Selected 300, make 3 products updated and so on...
Or if I select only 2 products, result is: Task "Update attributes for 2 selected products": 1 item(s) have been successfully updated.

How to fix it?
