### ISSUE TITLE
2.3.0 Product attribute not saving if getCustomAttribute / getCustomAttributes is called

### ISSUE THREAD

**Issue by Swahjak** [magento/magento2#22007]
### Preconditions (*)

1. Magento 2.3
2. Make sure `getCustomAttribute` or `getCustomAttributes()` is called on the model *before* `Magento\Framework\EntityManager\Operation\Update` is executed (for example in a `catalog_product_save_before` observer)

### Steps to reproduce (*)

1. Save a product with a (changed) multi select attribute
2. 

### Expected result (*)

1. [Screenshots, logs or description]
2. Multiselect attribute is saved

### Actual result (*)

1. Mutliselect attribute is not saved
2.

https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Model/AbstractExtensibleModel.php#L257 this line overwrites the model data with custom attribute data. Everything works fine up until https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/EntityManager/Operation/Update/UpdateMain.php#L55.

**Comment by magento-engcom-team** [comment]
Hi @Swahjak. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Swahjak do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98964`, `MAGETWO-98965` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by irajneeshgupta** [comment]
I am working on this at #dmcdindia1

**Comment by Swahjak** [comment]
:clap: next level issue solving, just close the issue because it hasn't been fixed within a x period.

Since nobody has marked this as fixed I'm going to assume it hasn't been fixed.

**Comment by Swahjak** [comment]
Still not stale

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by Swahjak** [comment]
How is closing an issue 'as it did not get much attention' a way of creating quality. Maybe you should look at the validity of the issue instead of the attention.

**Comment by KyleGospo** [comment]
This ticket that got closed for unfathomable reasons cost us 100s of hours of debugging work.
