### ISSUE TITLE
Upgrading to 2.3.1

### ISSUE THREAD

**Issue by tkymuk** [magento/magento2#22017]
### Preconditions (*)

Magento 2.3 being run on siteground servers.

### Steps to reproduce (*)

I have setup a new instal of magento with no additional themes or extensions added, essentially fresh out of the box. I have gone to setup wizard to get the update to 2.3.1 going and i am still coming across the "Check Component Dependency. We found conflicting component dependencies." error. On a fresh instal. 

### Expected result (*)

I expected the upgrade to occur.

### Actual result (*)

"Check Component Dependency. We found conflicting component dependencies." error.

**Comment by magento-engcom-team** [comment]
Hi @tkymuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@tkymuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ghost** [comment]
HI @tkymuk thank you for you report, this issue is acknowledged,  please refer to -> https://github.com/magento/magento2/issues/20684 thanks for collaboration :+1:
