### ISSUE TITLE
Add a form option to agreement functionality

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#22018]
### Summary 
For now, we're able to only add checkout Terms and Conditions. It could be cool (and I can do that) if while adding new Agreement I can choose forms that are applied for that agreement. For now, it's impossible to separate agreement by forms, but if we add forms multi-select field then it could be much easier for administrators to work with that.

### Examples (*)
For now to add customer registration agreement that should not be applied for checkout you must override registration.phtml and hardcode them.

### Proposed solution
I can add multiple providers and begin just with adding registration and checkout forms as an option for each agreement.

**Comment by magento-engcom-team** [comment]
Hi @madonzy. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@madonzy do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by kisroman** [comment]
@madonzy I think this is good idea. Can I take it in work or you want to do this task?
