### ISSUE TITLE
2.2.6 - Email address is now required. Why?

### ISSUE THREAD

**Issue by trucatchtraps** [magento/magento2#22019]
Create New Order -> Create New Customer -> Email field is now required.

Why has this been implemented and why is it not noted on the Release Notes for 2.2.6? How do I make it a non-required field again.

Thanks!

**Comment by magento-engcom-team** [comment]
Hi @trucatchtraps. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@trucatchtraps do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ananth-iyer** [comment]
@trucatchtraps If Email Address field is not required in your case then I suggest you can add any dummy Email Address to place an admin order.

**Comment by ghost** [comment]
hi @trucatchtraps this is expected behavior,  Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by trucatchtraps** [comment]
It was not required in 2.2.5. I don't understand why the change has not been documented. Please point me to a commit or discussion that explains the reason for this change. Or why this is not a feature you can turn on/off. Not everyone in the world has email addresses or sometimes they prefer not to give it out. Now we have to try and makeup a different dummy address every time because if it matches another email the order will not be created.

**Comment by trucatchtraps** [comment]
![2 2 6](https://user-images.githubusercontent.com/16922585/55808594-a1112280-5aa1-11e9-90d6-2df6d1b950ad.png)
![2 2 4](https://user-images.githubusercontent.com/16922585/55808595-a1112280-5aa1-11e9-830a-b34701cf374b.png)

Please explain the email "required" field in the 2 screenshots. The one is 2.2.6 and the other is 2.2.4. The email address has never been required up until 2.2.6. Why did you add this and not document or allow a way to turn it off.
