### ISSUE TITLE
Products Enabled require a full reindex before they show up in appropriate categories.

### ISSUE THREAD

**Issue by ladle3000** [magento/magento2#22013]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. When releasing a new product I add the products way in advance of the product release time and set to disabled. When the release time is near, I enable the products 5 minutes in advance or so to give the indexes time to run with my 1 min cron runtime.

### Expected result (*)

1. The category that contains the products should then be refreshed when the products are set to enabled. It should display the new products

### Actual result (*)

1. It never does. I always have to go do a full reindex from cli and sometimes an additional cache flush, which is absolutely horrible for performance when releasing a new product.

And then I cuss and remind myself that magento is still not ready for primetime after all these years, but I'm too deeply integrated to escape the ecosystem. I then sometimes lash out at family and resort to Benzodiazepines to calm down.

**Comment by magento-engcom-team** [comment]
Hi @snoroozi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@snoroozi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by tomekjordan** [comment]
your cron is not set correctly. dont do this manually, create it according to Magento 2 docs

**Comment by ghost** [comment]
HI @snoroozi thank you for you report, i'm not able to reproduce following steps you described, please verify your cron settings.
![deepin-screen-recorder_Select area_20190401103623](https://user-images.githubusercontent.com/40756439/55310931-65a3a200-546a-11e9-95c4-ff366136c620.gif)

**Comment by ladle3000** [comment]
@engcom-backlog-nazar can you let me know the quickest way to test from cli, so I can test without cron running on my dev server and do on command.

My cron on production is completely fine, and 99% of other things work.

**Comment by ghost** [comment]
@snoroozi wait, test without cron ? and indexer set to schedule ?

**Comment by hostep** [comment]
@snoroozi: if you have [magerun2](https://magerun.net/) installed, you can execute a specific cron job with: `n98-magerun2.phar sys:cron:run indexer_update_all_views`. This should trigger partial reindexing on all indexers. Be sure to also use `bin/magento indexer:status` to see the status of the indexers.

And for a better understanding of how partial reindexing and materialised views work in Magento, there is this [excellent blog post](https://www.bigbridge.nl/blog/essential-magento-2-partial-reindexing/).

**Comment by sedax90** [comment]
We have the same problem with a simple programmatically price import. Normally we update 3000+ products, all indexes are setup up to run at schedule and most of products are indexed correcly but some products constantly disappear. We have to force a full reindex at the end of the import to correctly view all of them.
