### ISSUE TITLE
Unable to update products via csv file, when products ids from file are from wide id range

### ISSUE THREAD

**Issue by mtwegrzycki** [magento/magento2#22028]
### Preconditions (*)
1. Magento 2.3.0
2. PHP 7.1.20
3. Database with 6000 products

### Steps to reproduce (*)
1. Prepare csv file to update products (2 products or more). (This csv should contain products with the lowest and the highest id - 1 and 6000)
2. In Admin panel go to: System->Import and choose Product and Add/Update
3. Upload file
4. Check Data
5. Import csv file (error should be displayed now)

### Expected result (*)
1. I can update products via csv file import.

### Actual result (*)
1. General error: 1114 The table 'catalog_product_index_price_temp' is full occurs. (full error in attachment)

[tmp_table_import_products.txt](https://github.com/magento/magento2/files/3022216/tmp_table_import_products.txt)
![error screen](https://user-images.githubusercontent.com/48506469/55227613-372e8880-5218-11e9-9dce-076f256e78db.PNG)

**Comment by magento-engcom-team** [comment]
Hi @mtwegrzycki. Thank you for your report. 
The issue has been fixed in magento/magento2#22902 by @mtwegrzycki in 2.2-develop branch
Related commit(s):
 - [1f3f984aef9233c19a566513dcd6f39dfa49b18b](https://github.com/magento/magento2/commit/1f3f984aef9233c19a566513dcd6f39dfa49b18b)

The fix will be available with the upcoming 2.2.10 release.
