### ISSUE TITLE
Magento CRON Job Names are missing in NewRelic: "Transaction Names"

### ISSUE THREAD

**Issue by PiotrSiejczuk** [magento/magento2#22047]
### Preconditions (*)

1. Magento 2.1.x or 2.2.x or 2.3.x OpenSource / Commerce / Cloud
2. Correctly Configured Magento CRON Jobs
3. Issue Details: [Transactions named /index.php or /unknown](https://docs.newrelic.com/docs/agents/php-agent/troubleshooting/transactions-named-indexphp-or-unknown)

### Steps to reproduce (*)

1. Any Magento CRON Job Executed via Standard Scheduler
2. Any Magento CRON Job Executed via CLI Command
3. Check NewRelic APM Monitoring - Transactions. Check below Screenshot to see the unwanted situation:

![NewRelic-UnknownTraces-ActualResult](https://user-images.githubusercontent.com/19482748/55250672-074ea780-524f-11e9-8322-f88f0d89f17c.png) 

### Expected result (*)

1. NewRelic APM showing exact CRON Job Code as Names within Transaction Traces
2. Number of unknown transaction percentage should get reduced
3. Improved Trace-ability of Transactions for Performance Review Operations

![NewRelic-UnknownTraces-ExpectedResult](https://user-images.githubusercontent.com/19482748/55250673-07e73e00-524f-11e9-999c-d4ba04e6c505.png)

Above screen has 2 transactions "hidden" with white box and red border due to project specific names and data that cannot be desclousered

### Actual result (*)

1. NewRelic shows unknown transaction in Transaction Traces

![NewRelic-UnknownTraces-ActualResult](https://user-images.githubusercontent.com/19482748/55250672-074ea780-524f-11e9-8322-f88f0d89f17c.png)

**Comment by lbajsarowicz** [comment]
I think that's great issue for tomorrow Magento Contribution Day with @magento/strix 

Extra information:
https://docs.newrelic.com/docs/agents/php-agent/troubleshooting/transactions-named-indexphp-or-unknown

**Comment by PiotrSiejczuk** [comment]
@lbajsarowicz that is indeed the idea for this ticket :) Will pick it up and hopefully fix it in a few hours :)

**Comment by lbajsarowicz** [comment]
Question to @PiotrSiejczuk and @maghamed - what should be the depth of the NewRelic descriptions:

I've done some PoC
<img width="488" alt="Screenshot 2019-03-30 at 12 17 46" src="https://user-images.githubusercontent.com/1639941/55275410-dcfbf900-52e5-11e9-8d4d-178c15644df5.png">

**Comment by lbajsarowicz** [comment]
Created PR #22059 for CLI commands.

I'm not sure if we can achieve something that @PiotrSiejczuk asked, as usually Cron Jobs are ran in groups and I'm not sure if one PHP execution can contain multiple transactions. So that... I just added transaction name based on CLI command name.

<img width="1459" alt="Screenshot 2019-03-30 at 14 28 09" src="https://user-images.githubusercontent.com/1639941/55276798-1473a100-52f8-11e9-8a84-d4f8af8041a6.png">

I'm doing investigation if we can have multiple transactions in one runtime.

**Comment by PiotrSiejczuk** [comment]
I am an old school guy, so, there is a Patch for normal CRON Flows:

`patch -p0 < Magento2.3.x-NewRelicCRONTransactionTrackingPatch.patch`

[Magento2.3.x-NewRelicCRONTransactionTrackingPatch.zip](https://github.com/magento/magento2/files/3025488/Magento2.3.x-NewRelicCRONTransactionTrackingPatch.zip)

I am going to create a PR in a few moment too

**Comment by magento-engcom-team** [comment]
Hi @PiotrSiejczuk. Thank you for your report. 
The issue has been fixed in magento/magento2#22059 by @lbajsarowicz in 2.3-develop branch
Related commit(s):
 - [a1661a5effb01e5fcd3cdf846d3052d8ec8e642f](https://github.com/magento/magento2/commit/a1661a5effb01e5fcd3cdf846d3052d8ec8e642f)
 - [07f8a65073331732f511c61fb66954365e2ada11](https://github.com/magento/magento2/commit/07f8a65073331732f511c61fb66954365e2ada11)
 - [638b73a514788822c19d8506763f79c0ac5a70b8](https://github.com/magento/magento2/commit/638b73a514788822c19d8506763f79c0ac5a70b8)
 - [bb861cc66bb1850d88eb189a3ae4364a52075ba0](https://github.com/magento/magento2/commit/bb861cc66bb1850d88eb189a3ae4364a52075ba0)
 - [9cd00fa8d80e085719d5a23491d9235e21da327f](https://github.com/magento/magento2/commit/9cd00fa8d80e085719d5a23491d9235e21da327f)

The fix will be available with the upcoming 2.3.2 release.

**Comment by PiotrSiejczuk** [comment]
Hi @magento-engcom-team, thank you for your information. Although commits from @lbajsarowicz are not addressing the whole scope of the reported issue. It is perfect that CLI CRON commands are being correctly Tracked @ NewRelic now. Although it is not tracking correctly ATOMIC Transactions executed within standard CRON execution. That being said: this ticket should not be CLOSED as the FIX is not addressing the whole scope of the ISSUE described initially

**Comment by VladimirZaets** [comment]
Hi @PiotrSiejczuk. Thank you for your report. 
The issue has been fixed in magento/magento2#25957 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [5819ded0ed228e0de105000d92da26531c07785a](https://github.com/magento/magento2/commit/5819ded0ed228e0de105000d92da26531c07785a)
 - [906c5a0d88fc5bc868a894b6397d0d71824bf614](https://github.com/magento/magento2/commit/906c5a0d88fc5bc868a894b6397d0d71824bf614)

The fix will be available with the upcoming 2.4.0 release.
