### ISSUE TITLE
Will Magento2 Merchant be available in the fourth quarter of 2015?

### ISSUE THREAD

**Issue by cfcnn** [magento/magento2#2207]
@ilol  Hello, I got the news from here, http://magento.com/developers/magento2  .
Is it real that Magento2 Merchant will be available in the fourth quarter of 2015?
Is it the same as CE version? What are the difference between Magento2 Merchant and CE?
What versions will Magento2 have?
I'm using Magento 1.9.2.2 CE, what version shall I use when update to Magento2?

Will Magento2 still have configurable swatches? I didn't find the swatches / thumbnail swatches in Magento2 which Magento1.9.2 has.

**Comment by mazhalai** [comment]
@cfcnn swatches are here: https://github.com/magento/magento2/tree/develop/app/code/Magento/Swatches

**Comment by choukalos** [comment]
@cfcnn Yes - Q4 2015 we'll drop the Double Deuce ( to paraphrase our product Paul ) in both CE & EE variants to continue our march towards total world e-commerce platform domination (yeah baby :) 

Magento 2.0 CE is for hobbyist and smaller merchants with features such as improved admin UX, streamlined checkout flow, improved mysql search, improved import/export, swatches, full page caching and more for the incredibly low price of free?!

Magento 2.0 EE is geared towards established merchants or those looking to grow rapidly and sports the same features as 2.0 CE and adds in Visual Merchandizer, SOLR search, rewards, gift cards, scalability enhancements such as multiple database support ( supports almost double the sustained checkout rate of 2.0 CE ), Customer Segmentation and more all for a TBD price.

Since your on CE now the obvious answer would be upgrading to Magento 2.0 CE.  If your business has grown considerably in the last year you might want to consider upgrading to Magento 2.0 EE as there are a # of features that make life easier when managing a rapidly growing or larger business.  When you consider an upgrade to Magento 2.0 please keep in mind a few things.  The platforms changed quite a bit so ping the makers of your favorite extensions to find out when they'll have Magento 2.x versions available.  We've released a data migration tool (https://github.com/magento/data-migration-tool-ce) to help speed up the upgrade.  We've got a very exciting roadmap in store for 2016 - quarterly releases ( goes well with Magento 2.0 since upgrades are streamlined in the new platform ) and a very passionate community who are now enabled to contribute back into core.  

-Chuck

**Comment by cfcnn** [comment]
@choukalos  Thank you for response. Does that mean Magento2.0 is going to charge? If magento 2.0 is not free any more, will you keep updating Magento1.9.x? or 1.9.x will be eliminated? and Magento is not free in future?  
If it's not free any more, it may be good news for Ebay, but bad news for its loyal users.

**Comment by choukalos** [comment]
Magento 2.0 is free!   I was just being sarcastic but I guess it didn't come across.

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
