### ISSUE TITLE
Error reindexing Target Rules

### ISSUE THREAD

**Issue by emcrobert** [magento/magento2#22083]
### Preconditions (*)

1. Magento 2.2.8
2.

### Steps to reproduce (*)

1. run the ./bin/magento indexer:reindex targetrule_rule_product command
2.

### Expected result (*)

1. index to be reccreated
2.

### Actual result (*)

1. Rceived this error message: SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s), query was: SELECT `e`.`entity_id` FROM `catalog_product_entity` AS `e` WHERE ((( (SELECT COUNT(*) FROM `catalog_category_product` WHERE (product_id=e.entity_id) AND (`category_id`='325', '326', '329', '330', '331', '333', '334', '338', '339', '341', '353', '544', '553')) > 0))) AND (e.created_in <= '1542621840') AND (e.updated_in > '1542621840')

2.

**Comment by emcrobert** [comment]
Clearly SQL query should be in rather than equal e.g = '326','329','330' shoud be in ('326','329','330')

However, I'm still trying to trace where the query is created in the code

**Comment by ghost** [comment]
HI @emcrobert  thank you for you report,
![DeepinScreenshot_select-area_20190401135619](https://user-images.githubusercontent.com/40756439/55322805-03589a80-5486-11e9-84af-a9005076bbc9.png)

**Comment by emcrobert** [comment]
the index still exists in 2.2.8. If it's not in develop branch is it going to be removed in 2.2.9?

The sql that's causing the issue seems to be generated based on information in the conditions_serialized field of the magento_targetrule table.

Not sure what populates that table though.

**Comment by ghost** [comment]
@emcrobert You use CE or EE version ?

**Comment by emcrobert** [comment]
EE version

**Comment by ghost** [comment]
@emcrobert on clean 2.2-develop, seems like this related with one of your custom modules.
![DeepinScreenshot_select-area_20190401153208](https://user-images.githubusercontent.com/40756439/55327708-58e77400-5493-11e9-804f-b737f477a573.png)

**Comment by orlangur** [comment]
This functionality does not seem to be a part of Magento Open Source, isn't it?

In such case
> Please report Magento Commerce issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant.
GitHub is intended for Magento Open Source bug reports given no account management for Magento Open Source users. This will allow for proper tracking of issues at the account level.

**Comment by emcrobert** [comment]
If it helps anyone else I found the problem related to a rule a user had created in the Related Products page of the admin.

They had created a rule where they had select the "is" option then selected multiple categories, when they should have selected the "is one of" option from the dropdown.

Whilst this is obviously user error, I'd say it's also a bug, as the admin shouldn't let a user select options which will generate invalid sql and break indexing.

We never got these errors with previous version of Magento and same rule, so I'm not sure if the rule used to work, or if it failed silently in the past and now throws an exception.

**Comment by orlangur** [comment]
@emcrobert thanks for your finding! I'm kindly ask you to send such report the way I described so that they keep an eye on this issue.

**Comment by hamplr** [comment]
I have the same problem and I think I found the problem. In magento/module-target-rule/Model/Rule/Condition/Product/Attributes/SqlBuilder.php changed the functionality and the check, which operator is used is refactored in a separate method. 

In case of the operator "is" in the rule, the code checks, if the operator is '!{}'. In this case is '!()' the value that will be returned. In every other case the return value will be '()'. After the change the functionality is refactored in the method getCategoryIdsConditionOperator(). In this method the check, which operator is used, is more granular. Thereby will be returned in case of 'is' the operator '=='. 
After this, the operator will be parsed in the method generateWhereClause() and will be hand over to the method  getOperatorCondition(). In this method the case of '==' isn´t defined. Bevor the change in 2.2.8 the operator in this case was '()' and the $selectOperator of getOperatorCondition() was 'IN(?)'. After the change the $selectOperator is '=?' and thats the reason for the problem because the prepare of the statement filled the placeholder with the list of category id´s and so the statement isn´t valid.

Possible Solution is IMHO that the input in the backend is only possible to store single values, in case the operator is "is".
