### ISSUE TITLE
Assigning Catalog Image from Gallery, then Saving Twice, Clears Image

### ISSUE THREAD

**Issue by jasonkcarter** [magento/magento2#22092]
### Preconditions (*)
1. Magento 2.3.0
2. Web root directory pointing to the Magento pub/ subdir.

### Steps to reproduce (*)
1. Edit an existing category node in the admin screen
2. Expand the Content tab
3. Next to Catalog Image, click Select from Gallery
4. Double click an existing image from the gallery
5. Click Save
6. Expand the Content tab

### Expected result (*)
1. The image should still be in the Catalog Image section
2. Saving a second time should keep the Catalog Image the same in the database and on the frontend.

### Actual result (*)
1. The image is missing, despite the image file path still being assigned in the database.
2. Saving a second time clears the Catalog Image path from the database and frontend.

**Comment by jasonkcarter** [comment]
It seems to be a problem with app/code/Magento/Model/Category/FileInfo.php not accounting for the pub/ subdirectory.

**Comment by jasonkcarter** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jasonkcarter. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jasonkcarter, here is your [Magento instance](https://i-22092-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22092-2-3-develop.instances.magento-community.engineering/admin](https://i-22092-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jasonkcarter** [comment]
The Magento 2.3-develop instance doesn't appear to use pub/ as its web root, so the bug is not evident on that machine.

**Comment by Bartlomiejsz** [comment]
@jasonkcarter it is fixed in my PR: #21131

**Comment by ghost** [comment]
Hi @jasonkcarter thank you for you report, i'm closing this as duplicate to this -> https://github.com/magento/magento2/issues/19872 thanks for collaboration :+1:

**Comment by magento-engcom-team** [comment]
Hi @jasonkcarter. Thank you for your report. 
The issue has been fixed in magento/magento2#21131 by @Bartlomiejsz in 2.3-develop branch
Related commit(s):
 - [ed43407dde622f7b6047b99c65fa5bd71db6d986](https://github.com/magento/magento2/commit/ed43407dde622f7b6047b99c65fa5bd71db6d986)
 - [619475dd35eb101e526ec98c6580ff7cb205a7cb](https://github.com/magento/magento2/commit/619475dd35eb101e526ec98c6580ff7cb205a7cb)
 - [17ed8d47f722dea48ea6ddb80c16a08228205702](https://github.com/magento/magento2/commit/17ed8d47f722dea48ea6ddb80c16a08228205702)
 - [ae61b7093715964364327c4e3e617a10225b5750](https://github.com/magento/magento2/commit/ae61b7093715964364327c4e3e617a10225b5750)
 - [112476a20ce1e2685fc62f315372870cb0da3743](https://github.com/magento/magento2/commit/112476a20ce1e2685fc62f315372870cb0da3743)
 - [8522a14fefe581e64691bdaebf8f6589a927978b](https://github.com/magento/magento2/commit/8522a14fefe581e64691bdaebf8f6589a927978b)
 - [07a296a5abd558f543c6207c5746d03475ed9102](https://github.com/magento/magento2/commit/07a296a5abd558f543c6207c5746d03475ed9102)
 - [a142ef2f71eaa78e18829e9b6990bd523254e158](https://github.com/magento/magento2/commit/a142ef2f71eaa78e18829e9b6990bd523254e158)
 - [de8df60b1d5b38e1b9fa53850076078a4218c320](https://github.com/magento/magento2/commit/de8df60b1d5b38e1b9fa53850076078a4218c320)
 - [d06fb10173f5080090c9983ed6b9f3f106788313](https://github.com/magento/magento2/commit/d06fb10173f5080090c9983ed6b9f3f106788313)

The fix will be available with the upcoming 2.3.3 release.
