### ISSUE TITLE
Shipping Methods Don't Load In IE11

### ISSUE THREAD

**Issue by marshallthornton** [magento/magento2#22119]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2
3. IE11

### Steps to reproduce (*)

1. Add some items to the cart
2. Go to checkout
3. Enter in your address so that methods will load

### Expected result (*)

1. A list of shipping methods appear

### Actual result (*)

1. No methods load and the console shows the error: "SCRIPT438: Object doesn't support property or method 'entries'"

This error appears to have been introduced with the commit https://github.com/magento/magento2/commit/4811ede46c2446361c5bdcb9aeb879ed66ffebf0 which is using Object.entries to loop over the custom attributes of the address. However Object.entries is not supported in IE according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries which is causing the error to get thrown and none of the methods to load. Magento still lists IE11 in the supported browsers so this should be fixed so that IE11 users can proceed through checkout.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99043` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jayankaghosh** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayankaghosh, here is your [Magento instance](https://i-22119-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22119-2-3-develop.instances.magento-community.engineering/admin](https://i-22119-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by geet07** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @geet07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @geet07, here is your [Magento instance](https://i-22119-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22119-2-3-develop.instances.magento-community.engineering/admin](https://i-22119-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nithya-babu** [comment]
I am working on this at #dmcdindia19

**Comment by alinalexandru** [comment]
Apparently there exists a polyfill
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Polyfill

Can I create a pull request and add the polyfill into lib/web/mage/polyfill.js ?

**Comment by magento-engcom-team** [comment]
Hi @marshallthornton. 

Thank you for your report and collaboration!

The related internal Jira ticket `MAGETWO-99043` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by Styopchik** [comment]
I can confirm issue in IE11 on magento 2.3.2

**Comment by sdzhepa** [comment]
Hello @marshallthornton and @Styopchik 

Thank you for contribution and collaboration!

Magento team has reconsidered this issue and related internal Jira ticket `MAGETWO-99043` has been reopened.

Currently `MAGETWO-99043` in progress and should be fixed and delivered soon. I will add updates here

**Comment by magento-engcom-team** [comment]
Hi @marshallthornton, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.4` release.

**Comment by DeLuuk** [comment]
Hey @sdzhepa,

I'm having this problem as well.
Can you tell me what the fix was so I can insert it into my 2.3.2 shop?

**Comment by sdzhepa** [comment]
Hello @marshallthornton and @Styopchik

The issue was closed accidentally by mistake.
At this moment the internal Jira ticket `MAGETWO-99043` is completed(Fixed/QA Passed) and waiting in the delivery queue.
I will update this Issue with commits info as soon as it will be delivered into public `2.3-develop` branch

**Comment by magento-engcom-team** [comment]
Hi @marshallthornton, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.4` release.

**Comment by JoostWan** [comment]
@magento-engcom-team Can you share the commit where it's been fixed? Thanks!

**Comment by sdzhepa** [comment]
Hello @JoostWan 

As I can see the fix was delivered with the internal pull request in the scop of `MAGETWO-99043`
So, all related commits can be found using search and this number - [LINK](https://github.com/magento/magento2/search?q=MAGETWO-99043&unscoped_q=MAGETWO-99043&type=Commits)

Commit: https://github.com/magento/magento2/commit/c15e194a9c5395d6cc703813feea8ed6efc4f6d5
