### ISSUE TITLE
A bug with health_check.php

### ISSUE THREAD

**Issue by wexo-team** [magento/magento2#22199]
### Preconditions (*)
1. Magento 2.2.8
2. Varnish set up with a health_check.php script for the backend

### Steps to reproduce (*)
1. Flush or disable the cache on the installation.
2. Visit health_check.php script. It should respond with 500 since the shutdown handler gets called and get_last_error in it returns a deprecation warning from the mcrypt functions. 

### Expected result (*)

1. health_check.php should not return 500 when an mcrypt deprecation warning(or any other warning suppressed with @ in front) is triggered on the page.

### Actual result (*)

1. health_check.php returns 500

**Comment by magento-engcom-team** [comment]
Hi @wexo-team. Thank you for your report. 
The issue has been fixed in magento/magento2#22200 by @wexo-team in 2.3-develop branch
Related commit(s):
 - [9675984b0487996de1521e2ba70d35ad7f77a788](https://github.com/magento/magento2/commit/9675984b0487996de1521e2ba70d35ad7f77a788)

The fix will be available with the upcoming 2.3.2 release.
