### ISSUE TITLE
Missing/Wrong data display on downloadable report table reports>downloads in BO

### ISSUE THREAD

**Issue by seyuf** [magento/magento2#22223]
### Preconditions (*)

1. At least Magento 2.1.11 to 2.3.1  are concerned

### Steps to reproduce (*)

1.Create 22 downloadable products
2.Order the 22 downloadable products
3. Complete the order in BO
3.Visit the downloadable links to download bought products (from frontend customer account)
4 Go go downloads reports table in the backoffice at *reports>downloads*

### Expected result (*)

1. Should've found 22 records / products with their download count as well as a pagination  
2. 
![good_report_pagination_ok](https://user-images.githubusercontent.com/3765910/55741933-c44eba00-5a2e-11e9-8e2f-9530296861df.png)

### Actual result (*)

1. Only 1 records found also the table only show the first 20 products with no pagination
2.
![only_first_20_product](https://user-images.githubusercontent.com/3765910/55742033-fbbd6680-5a2e-11e9-889b-8b19d0d339c1.png)

**Comment by seyuf** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @seyuf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99098` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @seyuf. Thank you for your report. 
The issue has been fixed in magento/magento2#22291 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [b881a5d98db719eae436d80965ea41365b53295e](https://github.com/magento/magento2/commit/b881a5d98db719eae436d80965ea41365b53295e)
 - [bf8e919b4bf203cc6caa59ceee668ff7eddc8a58](https://github.com/magento/magento2/commit/bf8e919b4bf203cc6caa59ceee668ff7eddc8a58)
 - [0453184879c5957d7ec4c903b9148c8ea35e43c1](https://github.com/magento/magento2/commit/0453184879c5957d7ec4c903b9148c8ea35e43c1)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @seyuf. Thank you for your report. 
The issue has been fixed in magento/magento2#22523 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [0d936c89a5c14c9e0edf352f7d68988b26dbb9c7](https://github.com/magento/magento2/commit/0d936c89a5c14c9e0edf352f7d68988b26dbb9c7)
 - [35ca37ea9cb672ffb9c088e1a4de007b5e21ba7b](https://github.com/magento/magento2/commit/35ca37ea9cb672ffb9c088e1a4de007b5e21ba7b)
 - [a78bb8e24f7818460e45cbf367b98ded74e05fb0](https://github.com/magento/magento2/commit/a78bb8e24f7818460e45cbf367b98ded74e05fb0)

The fix will be available with the upcoming 2.2.9 release.
