### ISSUE TITLE
Magento 2.2.7 - Unable to add tier price with 0 value via API

### ISSUE THREAD

**Issue by andrewbgittus** [magento/magento2#22237]
### Preconditions (*)

1. Magento version 2.2.7

### Steps to reproduce (*)

1. Send an API request with a tier price value of 0.

POST http://xxx.xxxx.com/magentov2/index.php/rest/V1/products/TEST/group-prices/1/tiers/20/price/0 HTTP/1.1
Authorization: Bearer xx0xxx0x0xx0xx00xxx00xx0x0xxxx0x
Accept: application/json, text/json, text/x-json, text/javascript
User-Agent: RestSharp/100.0.0.0
Host: dev.zynk.com
Content-Length: 0
Accept-Encoding: gzip, deflate
Connection: Close

### Expected result (*)

1. Within the Magento UI it is possible to set a tier price value to 0 so I would have expected the API to allow the same and return a successful response.

### Actual result (*)

HTTP/1.1 400 Bad Request
Date: Tue, 09 Apr 2019 08:30:45 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 39
Connection: close
Cache-Control: public, max-age=31536000
Expires: Wed, 08 Apr 2020 08:30:45 GMT
Vary: User-Agent
X-UA-Compatible: IE=edge
X-Turbo-Charged-By: LiteSpeed
Server: cloudflare
CF-RAY: 4c4b1eec6d3a6aa9-LHR

{"message":"Please provide valid data"}

**Comment by ghost** [comment]
Hi @andrewbgittus . Thank you for your report. 
The issue has been fixed in magento/magento2#18604 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [8084aa985c10208c1ee5bfd14ab31014bd4edfd4](https://github.com/magento/magento2/commit/8084aa985c10208c1ee5bfd14ab31014bd4edfd4)
 - [8296637b258a9d03f81304bf00724cee553da029](https://github.com/magento/magento2/commit/8296637b258a9d03f81304bf00724cee553da029)
 - [42839360380bc3783e1840b0ff69eb922e97a99d](https://github.com/magento/magento2/commit/42839360380bc3783e1840b0ff69eb922e97a99d)
 - [899a8a30d14907f07887a814060712a4b163efdb](https://github.com/magento/magento2/commit/899a8a30d14907f07887a814060712a4b163efdb)

The fix will be available with the upcoming 2.2.8 release.
