### ISSUE TITLE
Running cron jobs fails if database name is too long

### ISSUE THREAD

**Issue by amenk** [magento/magento2#22240]
### Preconditions (*)

Database is called
 shop_test_com_testing_foo_de

You have crontab.xml

    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
        <group id="update_virtual_attributes">

### Steps to reproduce (*)
1. bin/magento cron:run -v

### Expected result (*)
works

### Actual result (*)
doesn't

		                                                                                   
	  [Magento\Framework\Exception\InputException]                                             
	  Lock name too long: shop_test_com_testing_foo_de|CRON_GROUP_update_virtual_attribute...  
		                                                                                   

	Exception trace:
	 () at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/framework/Lock/Backend/Database.php:156
	 Magento\Framework\Lock\Backend\Database->addPrefix() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/framework/Lock/Backend/Database.php:66
	 Magento\Framework\Lock\Backend\Database->lock() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:259
	 Magento\Cron\Observer\ProcessCronQueueObserver->lockGroup() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:241
	 Magento\Cron\Observer\ProcessCronQueueObserver->execute() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/framework/Event/Invoker/InvokerDefault.php:72
	 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/framework/Event/Invoker/InvokerDefault.php:60
	 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/framework/Event/Manager.php:66
	 Magento\Framework\Event\Manager->dispatch() at /var/www/html/shop.test.com.testing.foo.de/web/generated/code/Magento/Framework/Event/Manager/Proxy.php:95
	 Magento\Framework\Event\Manager\Proxy->dispatch() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/framework/App/Cron.php:86
	 Magento\Framework\App\Cron->launch() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/module-cron/Console/Command/CronCommand.php:117
	 Magento\Cron\Console\Command\CronCommand->execute() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/symfony/console/Command/Command.php:245
	 Symfony\Component\Console\Command\Command->run() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/symfony/console/Application.php:835
	 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/symfony/console/Application.php:185
	 Symfony\Component\Console\Application->doRun() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/magento/framework/Console/Cli.php:102
	 Magento\Framework\Console\Cli->doRun() at /var/www/html/shop.test.com.testing.foo.de/web/vendor/symfony/console/Application.php:117
	 Symfony\Component\Console\Application->run() at /var/www/html/shop.test.com.testing.foo.de/web/bin/magento:23

**Comment by ghost** [comment]
Hi @amenk thank you for you report, this is expected behavior, please refer to -> https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html

**Comment by ghost** [comment]
@amenk `MySQL 5.7 and later enforces a maximum length on lock names of 64 characters. Previously, no limit was enforced.`

**Comment by amenk** [comment]
Thanks for the info --- but can't we then just create the lock name in another way? For example by hashing it ? What is the maximum table name length? then we should enforce a shorter cron group name or so ...

**Comment by PascalBrouwers** [comment]
This is not expected behaviour. With constraints Magento creates a shorter name when they are too long. It should do the same here.

**Comment by PivitParkour94** [comment]
I am able to replicate this, but it is manifesting in a confusing admin panel with no menu items loading. The error was being thrown in the log and changing to developer mode threw the error and it would seem it is because my database schema name is 40 characters long, so when the Database lock is loaded, when the prefix is added, the length is greater than 64 and the error is being thrown.
see `\Magento\Framework\Lock\Backend\Database::addPrefix`

![image](https://user-images.githubusercontent.com/5085830/67738321-e440dc00-fa59-11e9-9b09-b602c69180b0.png)

Is there a way we can trim the lock name to keep it under 64 to avoid hours of confusion in the future? That would be great.

**Comment by PascalBrouwers** [comment]
@engcom-backlog-nazar can you reopen this issue?
This is not expected behaviour. With constraints Magento creates a shorter name when they are too long. It should do the same here.

**Comment by PascalBrouwers** [comment]
Also... see this example of a lock
`BLOCK_4d0fde89c53949f89f741386ae575b1d704f9a24-old-price-225261-widget-product-grid-final_price-EUR-20191104-1-0-`
Even a db name the size of 1 character would cause the lock to fail

**Comment by VladimirZaets** [comment]
Hi @amenk. Thank you for your report. 
The issue has been fixed in magento/magento2#25472 by @vpashovski in 2.3-develop branch
Related commit(s):
 - [08972b4ee14f37651dc000dbd03c2ad317ab0e66](https://github.com/magento/magento2/commit/08972b4ee14f37651dc000dbd03c2ad317ab0e66)
 - [4dce93e1d3439d23ac822274e20cffb94f85463d](https://github.com/magento/magento2/commit/4dce93e1d3439d23ac822274e20cffb94f85463d)
 - [34f870ea09108509cedc1d66f5910f8c232f7b24](https://github.com/magento/magento2/commit/34f870ea09108509cedc1d66f5910f8c232f7b24)

The fix will be available with the upcoming 2.3.5 release.
