### ISSUE TITLE
Admin Order - Email is Now Required - Magento 2.2.6

### ISSUE THREAD

**Issue by trucatchtraps** [magento/magento2#22251]
### Important information after discussion with Product Departmen

This issue has been discussed with Magento Product Manager(PO).

> Changes from b1eece2 were made by the  Core team intentionally.
> It was based on several reports and escalations/complaints from different clients through Magento Support channel.
> The main idea was that specific of their businesses did not allow to accept any auto-generated email addresses in the case when field is empty(previous behavior).

Please see for more details: https://github.com/magento/magento2/pull/22648#issuecomment-490253069

But after a couple of additional meetings with PO was found compromise and solution how it can be fixed/implemented to be approved. Details and requirements here: https://github.com/magento/magento2/pull/22648#issuecomment-490253069

### Preconditions (*)
1. Magento 2.2.6 and newer

### Steps to reproduce (*)
1. Sales -> Orders
2. Create New Order
3. Create New Customer
4. Select Store View or if Single-Store Mode it brings you to the Order Information Page
5. Email field is now required

### Expected result (*)
1. Email field is NOT required (like versions prior to 2.2.6)

### Actual result (*)
1. Email field is required

### Additional Information (*)
The email field has never been required prior to 2.2.6 even going back to Magento1. Now the email field is required when placing an order on the backend of Magento. There is absolutely no documentation about this change or at least I have not found any. I will revert it with a custom module myself if someone points me to the code that makes it a required field. This needs to be a Config option to have the email required or not required. This is causing us major issues because now we have to try and make up random email address for customers. Not all the people in this world have an email address and some just prefer not to give it out. This is a bug not a feature. Please do not tell me this is normal function of Magento when it hasn't been since the beginning of Magento. 

### Screenshots (*)
Magento 2.2.4
![IxikJ](https://user-images.githubusercontent.com/16922585/55833429-bbb0bf00-5ad4-11e9-80cd-807e641a4825.png)

Magento 2.2.6
![iWVci](https://user-images.githubusercontent.com/16922585/55833440-c3706380-5ad4-11e9-9955-14657997e2e4.png)

**Comment by ghost** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-22251-2-2-3.instances.magento-community.engineering).
Admin access: [https://i-22251-2-2-3.instances.magento-community.engineering/admin](https://i-22251-2-2-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
HI @trucatchtraps thank you for you report, this is the "big issue" to have a not required email, and this was included in CHANGELOG.md, so there is a issue in older version where this field was not required.
![DeepinScreenshot_select-area_20190410100110](https://user-images.githubusercontent.com/40756439/55858218-ca03e700-5b77-11e9-98d1-1155f5d099f8.png)

**Comment by trucatchtraps** [comment]
That field has never been required in all my time working with Magento. Why is there now an issue with the email not required? And this is for backend orders. I just don't understand why it needs to be required for backend orders. Do you have a commit for the changes? I would like to override them.

**Comment by driskell** [comment]
@engcom-backlog-nazar Please can we reopen.

The changelog appears to refer to frontend guest checkout and not backend MOTO orders which have never required email and instead generated a random example.com placeholder email.

The configuration for the default email domain actually still exists so this is a bug. Default should be not required for MOTO (they are taking telephone calls to place orders - most users here do not have email addresses)


![F5F02FDA-BF7B-4F14-BAC8-4B788E4DA7D5](https://user-images.githubusercontent.com/939815/56364749-3cfc0600-61e7-11e9-9f06-3ed05d58acce.jpeg)

**Comment by driskell** [comment]
The commit that rolled back this feature was here:

https://github.com/magento/magento2/commit/b1eece2f41e99329afd0bb682f2674c0680b258c#diff-b79fbcef70631d52e90840aaf9a0d94d

@joanhe do you know what the reason for removing this feature was? The commit has actually left the constant and the configuration itself dangling with no use. Would be great to see this restored for next version and if necessary made optional.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99353`, `MAGETWO-99354` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by trucatchtraps** [comment]
I tried reverting that commit with a custom module but received the same results of the email being required on admin order.

**Comment by driskell** [comment]
@trucatchtraps We reverted the commit mentioned above and it restored original functionality perfectly. No longer required, and when left blank, auto-generates using the Default Email Domain

**Comment by trucatchtraps** [comment]
I must have missed something then...will try again

**Comment by trucatchtraps** [comment]
@driskell - I have tried it a couple different ways but still not showing the override for Magento\Sales\Block\Adminhtml\Order\Create\Form\Account on the backend. Can you please take a look at the custom module I created? The attached files I try to override the whole file, I have also tried to extend the original file and only include the affected classes but neither seems to be working. 

[Trucatch.zip](https://github.com/magento/magento2/files/3139031/Trucatch.zip)

Thanks!

**Comment by solwininfotech** [comment]
I am working on this at #dmcdindia19

**Comment by jayachandraoggy** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @jayachandraoggy. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @jayachandraoggy, here is your [Magento instance](https://i-22251-2-2-6.instances.magento-community.engineering).
Admin access: [https://i-22251-2-2-6.instances.magento-community.engineering/admin](https://i-22251-2-2-6.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jayachandraoggy** [comment]
I am working on this #codilar

**Comment by trucatchtraps** [comment]
Any update to this? I am still not able to revert the commit using a custom module. I moved to 2.3.1 but the issue is still present. I reattached my custom module, if someone wouldn't mind taking a look quick

[Trucatch.zip](https://github.com/magento/magento2/files/3303908/Trucatch.zip)

**Comment by trucatchtraps** [comment]
I finally was able to remove the required * for the email address, but now when I try to place an order without an email address, I receive the following errors. 

The value of attribute "Email" must be set
Validation is failed.

**Comment by magento-engcom-team** [comment]
Hi @trucatchtraps. Thank you for your report. 
The issue has been fixed in magento/magento2#24479 by @solwininfotech in 2.4-develop branch
Related commit(s):
 - [2ac0fe3ac5c5accab736a3001c70817eaf785117](https://github.com/magento/magento2/commit/2ac0fe3ac5c5accab736a3001c70817eaf785117)
 - [d78361ee7b1ecfd207a0415f982055beceb9fa5e](https://github.com/magento/magento2/commit/d78361ee7b1ecfd207a0415f982055beceb9fa5e)
 - [078bd695742a96210b16a4e5bd45b98e8a9b0301](https://github.com/magento/magento2/commit/078bd695742a96210b16a4e5bd45b98e8a9b0301)
 - [7e5bb80c72c62eebd4599c8bce8c68d205ae21bd](https://github.com/magento/magento2/commit/7e5bb80c72c62eebd4599c8bce8c68d205ae21bd)
 - [b5265e8446441ebcb38981b69e3494653c106818](https://github.com/magento/magento2/commit/b5265e8446441ebcb38981b69e3494653c106818)
 - [3c1d73e26e4ff18da5bbc3b2eb3780fcea244dbf](https://github.com/magento/magento2/commit/3c1d73e26e4ff18da5bbc3b2eb3780fcea244dbf)
 - [339c4c2a507767e8cb3badaac5e278430cf63d23](https://github.com/magento/magento2/commit/339c4c2a507767e8cb3badaac5e278430cf63d23)
 - [49f92779bd3ceb21ad6b2160d848aefd925b0060](https://github.com/magento/magento2/commit/49f92779bd3ceb21ad6b2160d848aefd925b0060)
 - [0627db9895e20c2152efb4684dd60f625c42fcc9](https://github.com/magento/magento2/commit/0627db9895e20c2152efb4684dd60f625c42fcc9)
 - [1e9e9407dee36b5d6daf18c50bc96923f00928f3](https://github.com/magento/magento2/commit/1e9e9407dee36b5d6daf18c50bc96923f00928f3)
 - [6dcdd8af62b234b8c14cf221757b3489822188e2](https://github.com/magento/magento2/commit/6dcdd8af62b234b8c14cf221757b3489822188e2)
 - [0e392e7b161371176c348caac07619e24584ac36](https://github.com/magento/magento2/commit/0e392e7b161371176c348caac07619e24584ac36)
 - [d4bcc7f18efa9f3e9feb4d837872c2f0c9162431](https://github.com/magento/magento2/commit/d4bcc7f18efa9f3e9feb4d837872c2f0c9162431)
 - [4e4e6a296ab4176cdf1c525a0128a66137147451](https://github.com/magento/magento2/commit/4e4e6a296ab4176cdf1c525a0128a66137147451)
 - [7da3d539b7402f5561be8fd679d61a5334ec0067](https://github.com/magento/magento2/commit/7da3d539b7402f5561be8fd679d61a5334ec0067)
 - [82ed8761bb43124235700cc27d165e937c123f26](https://github.com/magento/magento2/commit/82ed8761bb43124235700cc27d165e937c123f26)
 - [58511261b6ed15192b4014adc96e8a418df41e16](https://github.com/magento/magento2/commit/58511261b6ed15192b4014adc96e8a418df41e16)
 - [7772d52ee9cbdd12346d8d2bc9583a4c05193884](https://github.com/magento/magento2/commit/7772d52ee9cbdd12346d8d2bc9583a4c05193884)
 - [6915dc8089a1403764e761c869a1e4130f636269](https://github.com/magento/magento2/commit/6915dc8089a1403764e761c869a1e4130f636269)
 - [65ae5b064415165f2df56435af392d4fa44d3339](https://github.com/magento/magento2/commit/65ae5b064415165f2df56435af392d4fa44d3339)
 - [93fc0eeea9618ed1008a661ff691a08b81abd91e](https://github.com/magento/magento2/commit/93fc0eeea9618ed1008a661ff691a08b81abd91e)
 - [225ba009595ba295eb0324b643074fa4d8d11eee](https://github.com/magento/magento2/commit/225ba009595ba295eb0324b643074fa4d8d11eee)
 - [d5997ce775ab5ae8d39ebadbce91fbc7f83c13d9](https://github.com/magento/magento2/commit/d5997ce775ab5ae8d39ebadbce91fbc7f83c13d9)
 - [781684ab90d077ae838a5b3c833e1760c408c30a](https://github.com/magento/magento2/commit/781684ab90d077ae838a5b3c833e1760c408c30a)
 - [fbe87ab80084aa4f1803377c6c69c1fdb0779467](https://github.com/magento/magento2/commit/fbe87ab80084aa4f1803377c6c69c1fdb0779467)
 - [93d698a4de0ba46094043cf895d87d271d67178e](https://github.com/magento/magento2/commit/93d698a4de0ba46094043cf895d87d271d67178e)
 - [f4692b2274d986489c8c096096957c28de65040a](https://github.com/magento/magento2/commit/f4692b2274d986489c8c096096957c28de65040a)
 - [3e8369ece31b9241c7b1ad6c3bf47f48ac7e5cfc](https://github.com/magento/magento2/commit/3e8369ece31b9241c7b1ad6c3bf47f48ac7e5cfc)
 - [183b3157bc8fa203b1350b7aae97b570d52b77b0](https://github.com/magento/magento2/commit/183b3157bc8fa203b1350b7aae97b570d52b77b0)
 - [6d906ab23dc292be91eab7847a621503127d0718](https://github.com/magento/magento2/commit/6d906ab23dc292be91eab7847a621503127d0718)
 - [6fe2ab2dbf043fad74c218cbd2a4d699843f573f](https://github.com/magento/magento2/commit/6fe2ab2dbf043fad74c218cbd2a4d699843f573f)
 - [dfe039293baaff4b80ffb4a9c317f9ff00207067](https://github.com/magento/magento2/commit/dfe039293baaff4b80ffb4a9c317f9ff00207067)
 - [ab86799ce12cc728a31f5425d4474d95dfb9fa4b](https://github.com/magento/magento2/commit/ab86799ce12cc728a31f5425d4474d95dfb9fa4b)
 - [74cfd180853f41d9b6634267c82b7e51cc99ff56](https://github.com/magento/magento2/commit/74cfd180853f41d9b6634267c82b7e51cc99ff56)
 - [505549b7fcc1558699cd695dfb05b8cd465229d1](https://github.com/magento/magento2/commit/505549b7fcc1558699cd695dfb05b8cd465229d1)
 - [168a006a3010f3c46e216410cdd7da815fc343cc](https://github.com/magento/magento2/commit/168a006a3010f3c46e216410cdd7da815fc343cc)
 - [b1b3e6ce6ddef57a8d6e59cc678160670f8b9e76](https://github.com/magento/magento2/commit/b1b3e6ce6ddef57a8d6e59cc678160670f8b9e76)
 - [ca32574a4ef828a567276cf586c3c0109d03431d](https://github.com/magento/magento2/commit/ca32574a4ef828a567276cf586c3c0109d03431d)
 - [531e1b596c00eddd4af774c8d3a5ea998f409600](https://github.com/magento/magento2/commit/531e1b596c00eddd4af774c8d3a5ea998f409600)
 - [864f396105002f43bddb0e86bf67b75955494b84](https://github.com/magento/magento2/commit/864f396105002f43bddb0e86bf67b75955494b84)

The fix will be available with the upcoming 2.4.0 release.
