### ISSUE TITLE
Invoice order with only 1 configurable product is not treated as last invoice [CE 2.2.3]

### ISSUE THREAD

**Issue by qlhu** [magento/magento2#22283]
### Preconditions (*)
1. Magento CE 2.2.3

### Steps to reproduce (*)
1. Add a configurable product to cart
2. Complete the order with any payment method allowed to invoice
3. Invoice the order from Admin and debug this action

### Expected result (*)
1. The invoice is treated as last invoice and Magento\Sales\Model\Order\Invoice\Total\Tax::collect() line 94 - 97 is executed.

### Actual result (*)
1. The invoice is not treated as last invoice and Magento\Sales\Model\Order\Invoice\Total\Tax::collect() line 99 - 105 is executed.

The child item of configurable order item is treated as dummy but it's involved in the test if the item is to be invoiced completely. This issue

**Comment by ghost** [comment]
hi @qlhu thank you for you report, this issue has already fixed in 2.3-develop branch, but i think this may be related to your custom modules.
![deepin-screen-recorder_Select area_20190411114642](https://user-images.githubusercontent.com/40756439/55943639-a01df380-5c4f-11e9-8343-90fb38d48f50.gif)
![DeepinScreenshot_select-area_20190411114926](https://user-images.githubusercontent.com/40756439/55943785-e3786200-5c4f-11e9-8d89-2f7ee00d8248.png)

**Comment by qlhu** [comment]
Hi @engcom-backlog-nazar,
Thanks for quick response. Could you confirm it executes line 102 - 105 of `Magento\Sales\Model\Order\Invoice\Total\Tax::collect() `instead the line 107 - 113 when you did debugging? By reviewing 2.3-develop branch, thought the line 107 - 113 would to be executed.
Please let me share what I figured out with Magento CE 2.2.3. The configurable child item is treated as dummy and the `Magento\Sales\Model\Order\Item::getQtyToInvoice()` returns 0. And the `Magento\Sales\Model\Order\Invoice\Item::getQty()` returns 1 or any digit > 0. That leads `Magento\Sales\Model\Order\Invoice\Item::isLast()` returns false and then the invoice is not treated as last invoice.

**Comment by mizzimizzi** [comment]
Hello!
I'm having the same problem, any suggestions on how to proceed?
