### ISSUE TITLE
Category Update without "name" cannot be saved in scope "all" with REST API

### ISSUE THREAD

**Issue by cmuench** [magento/magento2#22309]
### Preconditions

1. A category tree must be created.

### Steps to reproduce

1. Install demo data in Magento 2.3.x
2. Try to save an existing category without the name attribute via REST API in scope "all".

### Expected result

1. Category will be saved.
2. Sent attributes are saved in the database.

### Actual result
1.Exception "Could not save category" with message `The "Name" attribute value is empty. Set the attribute and try again.`

PUT **/rest/all/V1/categories/11**  (throws error)

![screenshot-2019-03-07-15-20-52-2019-03-22-18-05-38-2019-04-12-16-47-16](https://user-images.githubusercontent.com/211294/56046113-d7210180-5d42-11e9-995f-063f512e8a26.png)

PUT **/rest/default/V1/categories/11**  (no error)

![image](https://user-images.githubusercontent.com/211294/56046195-fe77ce80-5d42-11e9-9985-f7b38f894ac1.png)

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22309-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22309-2-3-develop.instances.magento-community.engineering/admin](https://i-22309-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99164`, `MAGETWO-99165` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @cmuench. Thank you for your report. 
The issue has been fixed in magento/magento2#22362 by @niravkrish in 2.3-develop branch
Related commit(s):
 - [d4972dcde417536ab676a5a26b2f507299aa289c](https://github.com/magento/magento2/commit/d4972dcde417536ab676a5a26b2f507299aa289c)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @cmuench. Thank you for your report. 
The issue has been fixed in magento/magento2#22440 by @saphaljha in 2.2-develop branch
Related commit(s):
 - [20efb0563782aacef6511cc9cd55f971f2e18657](https://github.com/magento/magento2/commit/20efb0563782aacef6511cc9cd55f971f2e18657)

The fix will be available with the upcoming 2.2.9 release.
