### ISSUE TITLE
CodeSniffer should not mark correctly aligned DocBlock elements as code style violation.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/magento2#22317]
### Summary (*)

Magento\Sniffs\Annotation\MethodArgumentsSniff is marking as incorrect any aligned argument parameters, while [Magento Devdocs](https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#format-consistency) is obviously declaring such format as valid.

### Examples (*)

`/**`
` * ...`
` *`
` * @param  string   $parentId`
` * @param  string   $childId`
` * @param  int|null $position`
` * @return int`
` * @see    _insertChild() for position explanation`
` */`

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your report. 
The issue has been fixed in magento/magento2#22321 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [bed152b45be8c1c227434e66017f2f51a845770f](https://github.com/magento/magento2/commit/bed152b45be8c1c227434e66017f2f51a845770f)
 - [92d0f9324b991f2fdd92692ed643f5be60211148](https://github.com/magento/magento2/commit/92d0f9324b991f2fdd92692ed643f5be60211148)

The fix will be available with the upcoming 2.3.2 release.
