### ISSUE TITLE
Import product quantity is empty after import

### ISSUE THREAD

**Issue by kevinvuillemin** [magento/magento2#22355]
### Preconditions (*)

1. Magento  2.3.1
2. Csv file to upload product, with column base_image and his value
3. This image have to be not exist in folder 

### Steps to reproduce (*)

1. Go to admin (System - Import - Products)
2. Upload csv 
3. Check data
4. Import

### Expected result (*)

1. Product imported with all informations :qty, price, image default (because this image not existed in folder), attributes etc.
2. 

### Actual result (*)

1.  Product imported with all informations but miss qty, it is empty (but it's working if the image exist in folder)
2. It worked in magento 2.7

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99222` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kevinvuillemin** [comment]
At the same time, error handling is less developed in 2.2.x

**Comment by magento-engcom-team** [comment]
Hi @kevinvuillemin. Thank you for your report. 
The issue has been fixed in magento/magento2#22382 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [e949e85159dd00640106be24ff72b79441cba121](https://github.com/magento/magento2/commit/e949e85159dd00640106be24ff72b79441cba121)
 - [bfc82b60a404757b8211cbae4067b9dcd7e52fd4](https://github.com/magento/magento2/commit/bfc82b60a404757b8211cbae4067b9dcd7e52fd4)
 - [b6784b5fab4d6d2b4fdf826b96b8a42b202dc631](https://github.com/magento/magento2/commit/b6784b5fab4d6d2b4fdf826b96b8a42b202dc631)

The fix will be available with the upcoming 2.3.2 release.
