### ISSUE TITLE
config:set -le and -lc short form options don't work

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#22395]
### Preconditions (*)

1. 2.3.1

### Steps to reproduce (*)

1. bin/magento config:set --scope default -lc <path> <value>

### Expected result (*)

1. -lc option is applied

### Actual result (*)

1. Error message appears:

`The "-c" option does not exist.`

The long form versions (--lock-env, --lock-config) of those options work fine

**Comment by magento-engcom-team** [comment]
@kalpmehta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by kalpmehta** [comment]
Reproduced on 2.3.1

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @kalpmehta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99254` were created

**Issue Available**: @kalpmehta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @MichaelThessel. Thank you for your report. 
The issue has been fixed in magento/magento2#22720 by @satyaprakashpatel in 2.3-develop branch
Related commit(s):
 - [fbcfd11559def0891e829746a75ff5df2db438ee](https://github.com/magento/magento2/commit/fbcfd11559def0891e829746a75ff5df2db438ee)
 - [62cbf5b9d9443cd4b2dbdbef18d188b58888124c](https://github.com/magento/magento2/commit/62cbf5b9d9443cd4b2dbdbef18d188b58888124c)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @MichaelThessel. Thank you for your report. 
The issue has been fixed in magento/magento2#22836 by @shikhamis11 in 2.2-develop branch
Related commit(s):
 - [df7fad827caa3ec4b5c25f582d6153f3f4016295](https://github.com/magento/magento2/commit/df7fad827caa3ec4b5c25f582d6153f3f4016295)
 - [2e7c766b07b933e5fbcf38efdd6326b922262b16](https://github.com/magento/magento2/commit/2e7c766b07b933e5fbcf38efdd6326b922262b16)

The fix will be available with the upcoming 2.2.10 release.
