### ISSUE TITLE
PUT /V1/products/:sku/media/:entryId does not change the file

### ISSUE THREAD

**Issue by philippsander** [magento/magento2#22402]
### Preconditions (*)

1. Magento Commerce Edition 2.2.8
2. Have a Product with an image uploaded (Luma sample data provides this)

### Steps to reproduce (*)

1. Send the following request to "/V1/products/24-WG080/media/52"
base64_encoded_data is empty as this would bloat the issue-text

`{"entry":{"media_type":"image","label":"Label for my Image":1,"disabled":false,"types":["image","small_image","thumbnail"],"content":{"base64_encoded_data":"...","type":"image/jpeg","name":"luma-yoga-kit-2"},"id":52}}`

### Expected result (*)

1. Everything provided by the request is updated for the media entity
2. The actual file-content is replaced with what is provided in the base64_encoded_data
3. The endpoint returns true

### Actual result (*)

1. label, types and disabled is updated for the media entity
2. The actual file-content is NOT replaced with what is provided in the base64_encoded_data
3. The endpoint returns true

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99257`, `MAGETWO-99258` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by philippsander** [comment]
@Nazar65 Thanks for looking into this issue. keep in mind that I did not verfify this with 2.2-develop and 2.3-develop yet!

**Comment by Nazar65** [comment]
@philippsander this issue present on 2.3-develop as well, i'm  working on this now :+1:

**Comment by Nazar65** [comment]
Hi @philippsander  I'm made a proper fix for this you can apply to your instance.

**Comment by magento-engcom-team** [comment]
Hi @philippsander. Thank you for your report. 
The issue has been fixed in magento/magento2#22424 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [9205c6fa88e3de4ac09e48a85cd193507d47e1f7](https://github.com/magento/magento2/commit/9205c6fa88e3de4ac09e48a85cd193507d47e1f7)
 - [986d3844227fa59d5e780bc4fc64c7401d65c661](https://github.com/magento/magento2/commit/986d3844227fa59d5e780bc4fc64c7401d65c661)
 - [24580ee3eb4c87cca94d73b9e377621750708234](https://github.com/magento/magento2/commit/24580ee3eb4c87cca94d73b9e377621750708234)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @philippsander. Thank you for your report. 
The issue has been fixed in magento/magento2#22533 by @niravkrish in 2.2-develop branch
Related commit(s):
 - [299563686badfd4bb542c9f143c94005e8420dd6](https://github.com/magento/magento2/commit/299563686badfd4bb542c9f143c94005e8420dd6)

The fix will be available with the upcoming 2.2.9 release.

**Comment by philippsander** [comment]
The fix does not work. Still an Issue in 2.2.9
