### ISSUE TITLE
url returned with getOrderPlaceRedirectUrl() in payment gateway is not used

### ISSUE THREAD

**Issue by JonkRuud** [magento/magento2#2241]
Hello All, 

At the moment I'm working on a new Magento 2 payment gateway that should redirect the consumer to an external payment page from a Payment Service Provider. 
With Magento 1 we used to use getOrderPlaceRedirectUrl() within the gateway. It looks like this still is the way to go in Magento 2. Magento 2 does call the function after placing the order, but it doesn't use the returned url from that function.

When using code like:

```php
    public function getOrderPlaceRedirectUrl() {
        return $this->_urlBuilder->getUrl('module/controller/method');
    }
```
The consumer should be redirected tot the the modules controller, but this doesn't seem to happen and the consumer is just redirect to the success page.

Is this a bug within Magento 2, or should this be done in another way now?

**Comment by dkvashninbay** [comment]
Hi,

Currently getOrderPlaceRedirectUrl is not supported any more due to changes in rendering responsibility on storefront. As Onepage checkout uses knockout.js, you'll need to implement redirection logic on a client.

For example please take a look how PayPal Express checkout is implemented.
1. Config Provider, providing Redirect url:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Paypal/Model/ExpressConfigProvider.php#L116

3. View:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Paypal/view/frontend/web/template/payment/paypal-express.html#L43

4. ContinueToPaypal click handler (View Model):
https://github.com/magento/magento2/blob/develop/app/code/Magento/Paypal/view/frontend/web/js/view/payment/method-renderer/paypal-express-abstract.js#L72

5. Redirect Action:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Paypal/view/frontend/web/js/action/set-payment-method.js#L47

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by esilvajr** [comment]
@dkvashninbay you said: "you'll need to implement redirection logic on a client." but i need data from php, how do i build this?

**Comment by sinamiandashti** [comment]
@davidalger is the payment operation gonna change in 2.2 completely ?

**Comment by sixg** [comment]
As Onepage checkout uses knockout.js, you'll need to implement redirection logic on a client.

For example please take a look how PayPal Express checkout is implemented.

Config Provider, providing Redirect url:
https://github.com/magento/magento2/blob/b2fd6f320dab2aeb903690ba7e4e43622f3bcc23/app/code/Magento/Paypal/Model/ExpressConfigProvider.php#L139
View:
https://github.com/magento/magento2/blob/b2fd6f320dab2aeb903690ba7e4e43622f3bcc23/app/code/Magento/Paypal/view/frontend/web/template/payment/paypal-express.html#L43
ContinueToPaypal click handler (View Model):
https://github.com/magento/magento2/blob/b2fd6f320dab2aeb903690ba7e4e43622f3bcc23/app/code/Magento/Paypal/view/frontend/web/js/view/payment/method-renderer/paypal-express-abstract.js#L86
Setting Payment method:
https://github.com/magento/magento2/blob/b2fd6f320dab2aeb903690ba7e4e43622f3bcc23/app/code/Magento/Paypal/view/frontend/web/js/action/set-payment-method.js#L46
Redirect Action:
https://github.com/magento/magento2/blob/b2fd6f320dab2aeb903690ba7e4e43622f3bcc23/app/code/Magento/Paypal/view/frontend/web/js/view/payment/method-renderer/paypal-express-abstract.js#L94

**Comment by Nicerova7** [comment]
Hello, 

Any update about this topic ?
