### ISSUE TITLE
Incomplete Dependency on Backup Settings Configuration

### ISSUE THREAD

**Issue by keyurk-emipro** [magento/magento2#22474]
### Preconditions (*)

1. Magento ver. 2.3.1
2.

### Steps to reproduce (*)

1. Go to Store > Configuration > System > Advanced > Backup Settings
2. Enable Backup => Yes
3. Enable Scheduled Backup => Yes
4. Enable Backup => No

### Expected result (*)

1. All fields Must be Hidden on Enable Backup => No
2. 

### Actual result (*)

1. Only Enable Scheduled Backup are dependable on Enable Backup Field.
2. And Other 4 fields depend on Enable Scheduled Backup.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99377` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro. Thank you for your report. 
The issue has been fixed in magento/magento2#22475 by @keyuremipro in 2.3-develop branch
Related commit(s):
 - [60e862f64975378c8c2d269fdde1d97d6621275c](https://github.com/magento/magento2/commit/60e862f64975378c8c2d269fdde1d97d6621275c)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro. Thank you for your report. 
The issue has been fixed in magento/magento2#22499 by @keyuremipro in 2.2-develop branch
Related commit(s):
 - [bd0613a10f5bdfc554361c39b7b43072f3395868](https://github.com/magento/magento2/commit/bd0613a10f5bdfc554361c39b7b43072f3395868)

The fix will be available with the upcoming 2.2.9 release.
