### ISSUE TITLE
Customer address States are duplicated in backend

### ISSUE THREAD

**Issue by cdiacon** [magento/magento2#22484]
### Preconditions (*)
Magento 2.3.1 

### Steps to reproduce (*)

1. Install fresh magento 2.3.1
2. create a customer 
3. go to backend and click new address 
4. select any country United States or Australia

### Expected result (*)

1. State province are not duplicated
### Actual result (*)

1. All the sates are duplicated with the same ID
![image](https://user-images.githubusercontent.com/728734/56680909-e1db7f00-66d0-11e9-8116-6f25671647a9.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22484-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22484-2-3-develop.instances.magento-community.engineering/admin](https://i-22484-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99389` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hiren0241** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [Magento instance](https://i-22484-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22484-2-3-develop.instances.magento-community.engineering/admin](https://i-22484-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
I am working on this at #dmcdindia1

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @cdiacon. Thank you for your report. 
The issue has been fixed in magento/magento2#22637 by @shikhamis11 in 2.3-develop branch
Related commit(s):
 - [4a3fb1f692880a4926c2651f6c898df56ad96ae9](https://github.com/magento/magento2/commit/4a3fb1f692880a4926c2651f6c898df56ad96ae9)
 - [690ca8ea5a0ced6d5d4751f198122768fc24f925](https://github.com/magento/magento2/commit/690ca8ea5a0ced6d5d4751f198122768fc24f925)
 - [d859c0adc1974c6a9079215fdaa486fb47d9d86a](https://github.com/magento/magento2/commit/d859c0adc1974c6a9079215fdaa486fb47d9d86a)
 - [f85e6644e28bb5db5391b0a51768ebd90b3f0f5f](https://github.com/magento/magento2/commit/f85e6644e28bb5db5391b0a51768ebd90b3f0f5f)

The fix will be available with the upcoming 2.3.3 release.

**Comment by DmitryPirvu** [comment]
Hey there!
Provided fix seems just hiding nature of issue. Duplicates will be in DB anyway.
Added own solution for this task 462f4f3bd9553714426ee23be140818e93e38f4c

**Comment by engcom-Charlie** [comment]
Hello @DmitryPirvu 
Please create a new issue for advice or general discussion about this issue.
This issue should be closed. 
Thanks for your report!
