### ISSUE TITLE
Need full version via HTTP request

### ISSUE THREAD

**Issue by rafaelespinoza** [magento/magento2#22498]
This check version guide mentions you can send GET to /magento_version. However, the response is limited to only the major and minor versions of Magento. We're in need of the patch version as well.

In other words, we need 1.2.3, not just 1.2.

This is especially important in light of [PRODSECBUG-2198](https://magento.com/security/patches/magento-2.3.1-2.2.8-and-2.1.17-security-update), which specifies patch versions:

Magento Commerce < 1.14.4.1
Magento Open Source < 1.9.4.1
Magento < 2.1.17
Magento < 2.2.8
Magento < 2.3.1

How are we supposed to act on our vendors behalf without this critical information?

### Preconditions (*)

1. Any magento version

### Steps to reproduce (*)

1. Pick any magento installation
2. Follow [steps to check version](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/check-version.html#http-get-request) (send `GET` request to `http://<magento2-store>/magento_version`)

### Expected result (*)

1. `Magento/2.3.x (Community)`. The value at `x` is not important. But it's important to have the patch version.

### Actual result (*)

1. `Magento/2.3 (Community)`

---

note: this issue was at [community-features](https://github.com/magento/community-features/issues/162), but I moved it here for more visibility. It is security-related after all!

**Comment by orlangur** [comment]
@rafaelespinoza,

> How are we supposed to act on our vendors behalf without this critical information?

What do you mean? You don't know which Magento version is installed for each vendor?

Patch version is not exposed intentionally exactly for described reason: to not allow determine outdated stores quickly.

**Comment by rafaelespinoza** [comment]
We don't know which version of Magento is installed because we do not maintain the store, the vendor does. We just provide an API service for the store to connect to.

**Comment by orlangur** [comment]
@rafaelespinoza why vendor cannot communicate exact version to you then? For what kind of scenario you need a patch-version-dependent behavior of your system?

**Comment by rafaelespinoza** [comment]
I'm working on an external API service. The vendor maintains their store installation on their own, so we have no access to a [version check](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/check-version.html) other than the HTTP GET method, which is incomplete.

The goal is to prevent usage of our API when the vendor is using a version of Magento affected by [PRODSECBUG-2198](https://magento.com/security/patches/magento-2.3.1-2.2.8-and-2.1.17-security-update).

**Comment by hostep** [comment]
@rafaelespinoza: what do you do with Magento shops where the [`magento/module-version` module](https://github.com/magento/magento2/tree/2.3.1/app/code/Magento/Version) isn't installed on?
We recently started removing this module by default on our new shops as we don't want to expose which Magento version is used to the outside. It's considered a security issue when exposing which exact version a shop is running on (although you can see this as security through obscurity).

If you really want to know the version of Magento through an API request, you could write your own Magento module with a new endpoint, this endpoint should be protected with an apikey preferably and not open to the general public. And then let your consumers install this module.

Also: you know that you can have protection against PRODSECBUG-2198 by running versions lower then 2.3.1 or 2.2.8 since there are [separate patches available](https://magento.com/tech-resources/download#download2288) to install on a lower version of Magento (btw: you do know that the fix for PRODSECBUG-2198 wasn't even included in 2.1.17?)
