### ISSUE TITLE
Added Wish-list product displaying with wrong configurations

### ISSUE THREAD

**Issue by GrishmaNayee** [magento/magento2#22503]
### Preconditions (*)

1.Magento2.3 with sample data

### Steps to reproduce (*)

1.Log into the customer account.
2. Navigate to product listing page.
3.choose the configurable product and select preferred color and size options.
4.click on the wishlist icon of another configurable product on the same page without selecting any color/size options.

### Expected result (*)

1. On the Wishlist page, the system should not assign different product options to the wishlist product.

### Actual result (*)

1. system assigning wrong/other product configurations to the wishlist product.

![qa-contribution](https://user-images.githubusercontent.com/47663332/56800997-09019000-683a-11e9-9c5c-322c0fefa6f0.png)

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22503-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22503-2-3-develop.instances.magento-community.engineering/admin](https://i-22503-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-22503-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22503-2-2-develop.instances.magento-community.engineering/admin](https://i-22503-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ktpl-rammohan** [comment]
Issue Reproduced on Magento 2.3 and 2.2 as well.
Steps to Reproduce:
**Step1:** In Admin panel, Add two configurable products, for example: **test1** and **test2** with same configurations colors/size and assign to the same category.
**Step2:** on Front end store login as a customer and navigate to product listing page.
**Step3:** select test1 product configurations and click on test2 product wishlist icon. observe added wish-list product in the wish-list page.
**Step4:** Now select **test2** product configurations and click on **test1** product wishlist icon. observe in wishlist page system displaying test2 configurations to **test1** product.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99431`, `MAGETWO-99432` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by LuciferStrome** [comment]
#dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @GrishmaNayee. Thank you for your report. 
The issue has been fixed in magento/magento2#28157 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [a128f392b45f559316460962444bd4b1834e8f14](https://github.com/magento/magento2/commit/a128f392b45f559316460962444bd4b1834e8f14)
 - [e3bad69dc0d66d0eeb34eb180a4f415c25c3261e](https://github.com/magento/magento2/commit/e3bad69dc0d66d0eeb34eb180a4f415c25c3261e)
 - [536a728213fd4a36634dd958bbde243fe9154734](https://github.com/magento/magento2/commit/536a728213fd4a36634dd958bbde243fe9154734)
 - [3d69b132c603dbb0d04f3e8911b0b2a1416aed0e](https://github.com/magento/magento2/commit/3d69b132c603dbb0d04f3e8911b0b2a1416aed0e)
 - [75a5f2523643e89aa9226d92551021924c75e44f](https://github.com/magento/magento2/commit/75a5f2523643e89aa9226d92551021924c75e44f)
 - [0471e4e9bd296d6b4872cb450b6e95795060e928](https://github.com/magento/magento2/commit/0471e4e9bd296d6b4872cb450b6e95795060e928)
 - [2c07389f7cb3104378d6b49d3c2303a2b95de08c](https://github.com/magento/magento2/commit/2c07389f7cb3104378d6b49d3c2303a2b95de08c)
 - [e3e5a9af7054280a0a3fe47659a9c2bb911692a0](https://github.com/magento/magento2/commit/e3e5a9af7054280a0a3fe47659a9c2bb911692a0)
 - [e378086d6f1c0728afb2e2efbae9676c3522b3f3](https://github.com/magento/magento2/commit/e378086d6f1c0728afb2e2efbae9676c3522b3f3)
 - [11abbf95034a4cbbb317b6faad5e107098cad63d](https://github.com/magento/magento2/commit/11abbf95034a4cbbb317b6faad5e107098cad63d)
 - [ac6be807033e638e3098e5e0350b2990ecc2b236](https://github.com/magento/magento2/commit/ac6be807033e638e3098e5e0350b2990ecc2b236)
 - [8eead95b5580e1983e39584d18de1f67c92a09b2](https://github.com/magento/magento2/commit/8eead95b5580e1983e39584d18de1f67c92a09b2)
 - [e3fd2463dba30032f6777c926bba96a40f53730c](https://github.com/magento/magento2/commit/e3fd2463dba30032f6777c926bba96a40f53730c)
 - [129f4519eff38fef9deae4fca8b260996253ccbe](https://github.com/magento/magento2/commit/129f4519eff38fef9deae4fca8b260996253ccbe)
 - [8d025339e6df3bce298c231e920ddb243d44c95b](https://github.com/magento/magento2/commit/8d025339e6df3bce298c231e920ddb243d44c95b)
 - [840c99cb6422b9b320b1263c833e47f90a2af36b](https://github.com/magento/magento2/commit/840c99cb6422b9b320b1263c833e47f90a2af36b)

The fix will be available with the upcoming 2.4.2 release.
