### ISSUE TITLE
[WIP]Duplicate Adress on Reorder In Admin

### ISSUE THREAD

**Issue by Nazar65** [magento/magento2#22596]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)
1. Create A customer set Default Address
2. Create an Order in admin
3. Select in Sales Order -> recently created order.
4. Select Reorder.
5 Make sure you have all address data. and checkbox is checked `Save in address book`
6 Do reorder multiple times.
7. Now go to Customers in adminhtml and select edit Recently created customer 
8. Select Tab Adresses
### Expected result (*)

No duplicated addresses

### Actual result (*)

Duplicated Addresses
![DeepinScreenshot_select-area_20190502160114](https://user-images.githubusercontent.com/2481206/57076985-883c0b80-6cf3-11e9-86e0-ae2fc0cafb0b.png)

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22596-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22596-2-3-develop.instances.magento-community.engineering/admin](https://i-22596-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99507` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gaurav-473** [comment]
I am working on this at #dmcdindia1

**Comment by Nazar65** [comment]
@gauravagarwal1001 as you can see status of this issue WIP! I'm already working on this!

**Comment by erikhansen** [comment]
@Nazar65 Can you provide a link to the commit(s) where this was fixed? I'm running into this on Magento OS 2.3.3 and would like to create a patch to fix it.

**Comment by Nazar65** [comment]
@erikhansen feel free to reopen this one, and create a PR for this ticket.

**Comment by erikhansen** [comment]
@Nazar65 Ah, I thought you had fixed it since it was closed. 

I worked around the issue by applying a Composer patch to the https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Sales/view/adminhtml/templates/order/create/form/address.phtml#L90 file to remove the `<?php if (!$block->getDontSaveInAddressBook()) : ?> checked="checked"<?php endif; ?>` code.

[Here's the patch](https://github.com/magento/magento2/files/4031693/module-sales-prevent-duplicating-addresses-in-admin-checkout.patch.txt), in case it's useful to anyone else (rename from `.patch.txt` to `.patch` after downloading). Info on [how to use Composer patches](https://www.classyllama.com/blog/create-apply-patches-magento-2).
