### ISSUE TITLE
Without select attribute click on add attribute it display all selected when add attribute again.

### ISSUE THREAD

**Issue by magesanjay** [magento/magento2#22639]
Without select attribute click on add attribute it display all selected when add attribute again.

### Preconditions (*)
magento 2.2
magento 2.3

### Steps to reproduce (*)
1. Go to Admin
2. Catalog >> Manage Products >> Add New Product
3. Click on Add Attribute button
4. Without select any attribute click on add selected
5. It will close the popup window
6. Now click Add Attribute again
7. Review all attributes are selected by default and display count as (83 selected)

### Expected result (*)
Validation alert message should display like "You haven't selected any items!

### Actual result (*)
![big_snap_2](https://user-images.githubusercontent.com/39721144/57174393-cce2b680-6e5b-11e9-84a5-09aad770c340.png)

**Comment by krishprakash** [comment]
#dmcdindia19

**Comment by mageprince** [comment]
I am working on this at #dmcdindia19

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99548`, `MAGETWO-99549` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sidolov** [comment]
Hi @magesanjay. Thank you for your report. 
The issue has been fixed in magento/magento2#22991 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [f6ea06e2b070148ec5764e6faca10227e26b8270](https://github.com/magento/magento2/commit/f6ea06e2b070148ec5764e6faca10227e26b8270)
 - [f71e8a6b9df57cad2c33613e49c53e636e9ff3a0](https://github.com/magento/magento2/commit/f71e8a6b9df57cad2c33613e49c53e636e9ff3a0)

The fix will be available with the upcoming 2.2.10 release.
