### ISSUE TITLE
arrow toggle not changing only showing to down It should be toggle as every where is working 

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#22636]
Toggle arrow not changing, It only showing to down  but It should be toggle as every where is working 

### Preconditions (*)
1. php 7.2
2. Magento 2.3

### Steps to reproduce (*)
1. Login to admin panel
2. Go to **store** link and click on **Tax Rules** Available on sub menu 
3. Click on **add new tax rule**  and see **Additional Settings** tab and click on same 

### Expected result (*)
Toggle arrow should be down direction if content not open and should be up direction if content open

### Actual result (*)
Toggle arrow not moving 
![index](https://user-images.githubusercontent.com/26018716/57173963-76be4500-6e54-11e9-9f2d-9d8a40f1f9b6.png)

**Comment by shikhamis11** [comment]
#dmcdindia1

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22636-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22636-2-3-develop.instances.magento-community.engineering/admin](https://i-22636-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-22636-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22636-2-2-develop.instances.magento-community.engineering/admin](https://i-22636-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99544`, `MAGETWO-99545` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cedarvinda** [comment]
I am working in this #dmcdindia1

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#22644 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [4927b5dc037ab34260c081ea97d2cb8b1557e96a](https://github.com/magento/magento2/commit/4927b5dc037ab34260c081ea97d2cb8b1557e96a)
 - [3555b2614b8db3124751007b473a4d46f7ea123a](https://github.com/magento/magento2/commit/3555b2614b8db3124751007b473a4d46f7ea123a)
 - [df69419c979109f6c99b3345d532b3ee95223653](https://github.com/magento/magento2/commit/df69419c979109f6c99b3345d532b3ee95223653)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#23150 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [f1e8d055cbe9b7890afa675d35d25f3c175672b5](https://github.com/magento/magento2/commit/f1e8d055cbe9b7890afa675d35d25f3c175672b5)
 - [f4653b1997ad523bd69046e5854477643b9f285a](https://github.com/magento/magento2/commit/f4653b1997ad523bd69046e5854477643b9f285a)
 - [eff816e8863a6a5330e0b863906aa18f18f95c7b](https://github.com/magento/magento2/commit/eff816e8863a6a5330e0b863906aa18f18f95c7b)

The fix will be available with the upcoming 2.2.10 release.
