### ISSUE TITLE
In customer account create page word not readable, should use '-' after break to new line In mobile view

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#22647]
In customer account create page word not readable shoul use '-' after break to new line
### Preconditions (*)

1. php 7.2
2. Magento 2.3

### Steps to reproduce (*)
1. Open customer account create page in mobile view 

### Expected result (*)
![index](https://user-images.githubusercontent.com/26018716/57174736-ef2b0300-6e60-11e9-982c-b5970841f8fd.png)
**Should use **`hyphens: auto;`****

### Actual result (*)
![index_1](https://user-images.githubusercontent.com/26018716/57174754-11bd1c00-6e61-11e9-9c68-67baa1b2a350.png)

**Should not use **`word-break: break-all;`****

**Comment by cedarvinda** [comment]
I am working on this at #dmcdindia1

**Comment by shikhamis11** [comment]
@cedarvinda I checked this issue is not reporoduceable at 2.2-develop instance but is reproducable at 2.3-develop instance 
I think the actual result must be like this 
check screenshot - 2.2-develop 
![Screenshot_2019-05-04_11-59-38](https://user-images.githubusercontent.com/25526037/57175014-952c3c80-6e64-11e9-8b39-762083b37b5d.png)

2.3-develop 
![Screenshot_2019-05-04_12-01-32](https://user-images.githubusercontent.com/25526037/57175019-9fe6d180-6e64-11e9-88ae-6586a6e1e689.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99552` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by cedarvinda** [comment]
@shikhamis11 Yes this is also a solution but if we are thinking for global solution and large length word, In this case we will get extra space at the end of line, So we should use  `hyphens: auto;`

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#22656 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [1ae8bf536dc6174e5d810ef7c82864b6134cf376](https://github.com/magento/magento2/commit/1ae8bf536dc6174e5d810ef7c82864b6134cf376)

The fix will be available with the upcoming 2.3.3 release.
