### ISSUE TITLE
Compare Products counter, and My Wish List counter vertical not aligned

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#22676]
Compare Products counter, and My Wish List counter vertical not aligned

### Preconditions (*)
1. php7.2
2. Magento2.3

### Steps to reproduce (*)
1. Open frontend 
2. Login as customer (From customer account login)
3. add any product in wishlist and compare any product as well 
4. Now open My account page you will see issue as ref in screenshot

### Expected result (*)
![sol](https://user-images.githubusercontent.com/26018716/57176717-e9d9b280-6e78-11e9-8d93-63aeae812796.png)

### Actual result (*)
![issues](https://user-images.githubusercontent.com/26018716/57176722-f52cde00-6e78-11e9-8c68-45f94b3cafb6.png)

**Comment by LuciferStrome** [comment]
#dmcdindia1

**Comment by cedarvinda** [comment]
I am working in this issue at #dmcdindia1

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99555`, `MAGETWO-99556` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#23573 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [5a1ca956d52a0103d9df965b51a2d90803692ca5](https://github.com/magento/magento2/commit/5a1ca956d52a0103d9df965b51a2d90803692ca5)
 - [2a052552d2c86d15742f776836283f09e511df61](https://github.com/magento/magento2/commit/2a052552d2c86d15742f776836283f09e511df61)

The fix will be available with the upcoming 2.2.10 release.
