### ISSUE TITLE
Toggle icon not working in create configuration Product creation Page

### ISSUE THREAD

**Issue by nehaguptacedcoss** [magento/magento2#22702]
### Preconditions (*)
1. Magento2.3.1

### Steps to reproduce (*)
1.Catalog > Products > New Product (Configurable) > Click Create Configuration.
2. Select Attributes > Attribute Values > Bulk Images & Price > Summary.
3. Associated Products's Toggle not working properly

### Expected result (*)
On click tab arrow should be up and down.

### Actual result (*)
On click tab arrow is not changing.
![22](https://user-images.githubusercontent.com/40159259/57177956-4217b100-6e87-11e9-8320-294438661a0e.png)
![23](https://user-images.githubusercontent.com/40159259/57177957-42b04780-6e87-11e9-8f88-cac67f220219.png)

**Comment by nehaguptacedcoss** [comment]
I am working on this issue at #dmcdindia1

**Comment by ghost** [comment]
I'm working on it. #cdwebkul

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99558`, `MAGETWO-99559` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @nehaguptacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#23803 by @edenduong in 2.3-develop branch
Related commit(s):
 - [d56257230757b56120ea07bfce51d0a4a94b3afb](https://github.com/magento/magento2/commit/d56257230757b56120ea07bfce51d0a4a94b3afb)

The fix will be available with the upcoming 2.3.3 release.

**Comment by slavvka** [comment]
Hi @nehaguptacedcoss. Thank you for your report. 
The issue has been fixed in magento/magento2#28032 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [d7cf1881141fd855ff79f611a31ea2570726bdc3](https://github.com/magento/magento2/commit/d7cf1881141fd855ff79f611a31ea2570726bdc3)
 - [77a4e8c44e1ee901d77aa8d6680fcd5365cd376d](https://github.com/magento/magento2/commit/77a4e8c44e1ee901d77aa8d6680fcd5365cd376d)
 - [6b8fc4c55272229164fde82ddbd631f771f302d7](https://github.com/magento/magento2/commit/6b8fc4c55272229164fde82ddbd631f771f302d7)
 - [facbe37f9f51eb315bc5da1fb3c5000d743057ff](https://github.com/magento/magento2/commit/facbe37f9f51eb315bc5da1fb3c5000d743057ff)
 - [1ef8a517089ff132a7bb526194999ae83247ce50](https://github.com/magento/magento2/commit/1ef8a517089ff132a7bb526194999ae83247ce50)
 - [6e8190662497a8e248c05d92b8763886637be5f3](https://github.com/magento/magento2/commit/6e8190662497a8e248c05d92b8763886637be5f3)
 - [03a2908769ad60c5cd5b1a5262aeab092417fe6a](https://github.com/magento/magento2/commit/03a2908769ad60c5cd5b1a5262aeab092417fe6a)
 - [8c0eff01d09dbea47a3af3afbd0f75bae2a89c82](https://github.com/magento/magento2/commit/8c0eff01d09dbea47a3af3afbd0f75bae2a89c82)
 - [0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41](https://github.com/magento/magento2/commit/0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41)
 - [63550be4ba9097cb1ceac4cc787632d330ec0ea1](https://github.com/magento/magento2/commit/63550be4ba9097cb1ceac4cc787632d330ec0ea1)
 - [321f5c1aed364f72eed6e5e08696f88f4ceabcac](https://github.com/magento/magento2/commit/321f5c1aed364f72eed6e5e08696f88f4ceabcac)
 - [13fe206df162eb2e9f807659899bbe2462142d51](https://github.com/magento/magento2/commit/13fe206df162eb2e9f807659899bbe2462142d51)
 - [aae2b7f2073dd171fa12388348bef1a37e389c46](https://github.com/magento/magento2/commit/aae2b7f2073dd171fa12388348bef1a37e389c46)
 - [2c8839699612fa67db10ba795f5357dbc42756f5](https://github.com/magento/magento2/commit/2c8839699612fa67db10ba795f5357dbc42756f5)
 - [cfec001044286e96650d4f50ce906fc95bfc5d57](https://github.com/magento/magento2/commit/cfec001044286e96650d4f50ce906fc95bfc5d57)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Based on the provided information internal tickets `MC-34534` for 2.4.x were created.
