### ISSUE TITLE
Cursor position not in right side of search keyword in search box when click on search again (Mobile issue)

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22736]
Cursor position not in right side of search keyword in search box when click on search again(Mobile issue)

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
Issue in mobile screen resolution
1. front end 
2. search any product
3. on search result page click on search icon again
4. review the cursor position in search box

### Expected result (*)
![search result expected result](https://user-images.githubusercontent.com/49804008/57188262-3ecd0580-6f19-11e9-9707-e260c7b66a51.png)

### Actual result (*)
![search field cursor issue](https://user-images.githubusercontent.com/49804008/57188256-34127080-6f19-11e9-8be3-adcbd8b8dc0c.png) 

### Additional Information (*)
It should consider as user experience issue.
As user should clear the older search keyword and type for new search.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22736-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22736-2-3-develop.instances.magento-community.engineering/admin](https://i-22736-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22736-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22736-2-2-develop.instances.magento-community.engineering/admin](https://i-22736-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99563`, `MAGETWO-99564` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sanjaychouhan-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sanjaychouhan-webkul, here is your [Magento instance](https://i-22736-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22736-2-3-develop.instances.magento-community.engineering/admin](https://i-22736-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am working on this issue.

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#22795 by @sanjaychouhan-webkul in 2.3-develop branch
Related commit(s):
 - [5621c4481748788d2ae3c6fbf116217c605e642c](https://github.com/magento/magento2/commit/5621c4481748788d2ae3c6fbf116217c605e642c)
 - [3ca7c02c826c61d87cfd39cee535eb382368bfb9](https://github.com/magento/magento2/commit/3ca7c02c826c61d87cfd39cee535eb382368bfb9)
 - [3c8dcead5bd0361fddcd15efa378e2b74201ed9f](https://github.com/magento/magento2/commit/3c8dcead5bd0361fddcd15efa378e2b74201ed9f)
 - [c79e1ff6f6402b85ee79a6e640856972ba758c93](https://github.com/magento/magento2/commit/c79e1ff6f6402b85ee79a6e640856972ba758c93)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#23352 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [c068886d876c2fc76f6600ba515bc2e125f58697](https://github.com/magento/magento2/commit/c068886d876c2fc76f6600ba515bc2e125f58697)
 - [525396ac328f058dcfd9ad740976ce1d8d8e2aa7](https://github.com/magento/magento2/commit/525396ac328f058dcfd9ad740976ce1d8d8e2aa7)
 - [e7c33f33eaf6033a715828bdb64acc2aba935963](https://github.com/magento/magento2/commit/e7c33f33eaf6033a715828bdb64acc2aba935963)
 - [2464b3169e4a8d1294d69bdc1a9b0009adb3d8e5](https://github.com/magento/magento2/commit/2464b3169e4a8d1294d69bdc1a9b0009adb3d8e5)

The fix will be available with the upcoming 2.2.10 release.
