### ISSUE TITLE
Footers do not snap to bottom of screen on internet Explorer 11

### ISSUE THREAD

**Issue by vini1996** [magento/magento2#22748]
### Preconditions (*)

1.  Magento 2.2.7
2. php 7.14
3. internet Explorer 11

### Steps to reproduce (*)

1. clicking any pages on the footer.
2. clicking on the any of the categories.

### Expected result (*)

1.footers must fit at the bottom of the page
![Screenshot_2](https://user-images.githubusercontent.com/39683802/57220428-ee3cd180-7018-11e9-9542-01c8f02b0b8b.png)
### Actual result (*)

1. footers are not fit at the bottom of the page, instead, it is overlapping.
![Screenshot_1](https://user-images.githubusercontent.com/39683802/57220349-9d2cdd80-7018-11e9-84d8-955a27a25402.png)

**Comment by AlexWorking** [comment]
Hello @vini1996. Thanks for reporting. Please specify the steps necessary to reproduce Your issue. Screenshot of the actual result will also be appreciated.

**Comment by vini1996** [comment]
@AlexWorking  sry, that's all information I have

**Comment by AlexWorking** [comment]
Thank You @vini1996. But we are not able to reproduce Your issue on a clear vanilla instance of Magento2. There is ether missing something in Your Steps to Reproduce or Your Magento instance is modified with some custom extensions that cause such a result. If it's been not for the second one please try to guide us in what else we are supposed to do in order to reproduce Your issue.
![Footers](https://user-images.githubusercontent.com/27814011/57224540-04ba3d00-6fc7-11e9-965a-7ea65b2a284d.gif)

**Comment by vini1996** [comment]
@AlexWorking please try in Internet Explorer 11, this issue is with Internet Explorer only.

**Comment by AlexWorking** [comment]
@vini1996 here is a test done on Internet Explorer version 11.437.17763.0 with the same result:
![IE11437177630](https://user-images.githubusercontent.com/27814011/57283299-1570be80-706c-11e9-9a8b-29fba6d1a876.gif)

**Comment by vini1996** [comment]
@AlexWorking  can you send theme.less file, because this issue is still present in our site.

**Comment by AlexWorking** [comment]
Hi @vini1996. The contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
