### ISSUE TITLE
Credit Memo with Zero Total: Order Status "Complete" and not "Closed"

### ISSUE THREAD

**Issue by simonmaass** [magento/magento2#22762]
### Preconditions (*)

1. Magento 2.3.1
2. PHP7.2

### Steps to reproduce (*)

1. Create order with zero Amount (all Grand Total, Total Paid, Total Refunded, Total Due, Subtotal, Shipping & Handling, Tax are zero ) in status = "Pending" and 1 SKU qty = 1.
2. Create Invoice and now Order is status = "Processing"
3. Ship Order -> now Orderstatus is = "Complete"
4. Now create Credit memo and refund and return product

### Expected result (*)

1. The order status should be "Closed"

### Actual result (*)

1. Order Status is "Complete"

### Additional information
- [Order Status Workflow](https://docs.magento.com/user-guide/sales/order-status-workflow.html)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99588` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by deepakk-webkul** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @webkul-deepakkumar, here is your [Magento instance](https://i-22762-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22762-2-2-develop.instances.magento-community.engineering/admin](https://i-22762-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by deepakk-webkul** [comment]
I have checked this issue is reproducible on 2.2-develop also.

**Comment by JithinJay** [comment]
Can someone please review the PR, We have faced the same issue on orders paid with Magento store credit.

**Comment by slavvka** [comment]
Hi @simonmaass. Thank you for your report. 
The issue has been fixed in magento/magento2#29023 by @engcom-Echo in 2.4-develop branch
Related commit(s):
 - [8ab5415e546e1affbe94d80f62a611745a978c9b](https://github.com/magento/magento2/commit/8ab5415e546e1affbe94d80f62a611745a978c9b)
 - [e2b578de08d4e9853be51c52cc9872f394e55079](https://github.com/magento/magento2/commit/e2b578de08d4e9853be51c52cc9872f394e55079)
 - [eff94882403b548c32ae3d83e1347cd8a7b066c3](https://github.com/magento/magento2/commit/eff94882403b548c32ae3d83e1347cd8a7b066c3)
 - [0d3cc83657a0353c4de2528c518af18fd759f38e](https://github.com/magento/magento2/commit/0d3cc83657a0353c4de2528c518af18fd759f38e)
 - [f33150df886f8cf5a243259620ad852edc70a070](https://github.com/magento/magento2/commit/f33150df886f8cf5a243259620ad852edc70a070)

The fix will be available with the upcoming 2.4.1 release.

**Comment by DiegoSana** [comment]
@magento-engcom-team give me 2.4 instance
