### ISSUE TITLE
Magento 2.3.0 can't change text area field height admin form using Ui component

### ISSUE THREAD

**Issue by Patelcc** [magento/magento2#22771]
### Preconditions (*)

1. Magento version CE 2.3.0
2. PHP version 7.1.
3. Admin area

### Steps to reproduce (*)

1. Create admin form usign Ui component.
2. Add text area field to form
3. Try to increase text-area field height using `<item name="rows" xsi:type="number">60</item>`
**Note:** It is not working because of CSS `admin__control-textarea` class given height `height: 8.48rem;` if you remove this CSS then it is working fine.
### Expected result (*)

![expected-result](https://user-images.githubusercontent.com/40203855/57303738-94f99e80-70fb-11e9-8ddc-6dd436454d9a.png)

### Actual result (*)

![Actual-result](https://user-images.githubusercontent.com/40203855/57303751-9e830680-70fb-11e9-8661-c66a26922265.png)

**Comment by arnoudhgz** [comment]
@magento-engcom-team give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz, here is your [Magento instance](https://i-22771-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-22771-2-3-1.instances.magento-community.engineering/admin](https://i-22771-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99595`, `MAGETWO-99596` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Patelcc. Thank you for your report. 
The issue has been fixed in magento/magento2#22783 by @serhiyzhovnir in 2.2-develop branch
Related commit(s):
 - [2b8e142ab6025627d20c5052b538d8e354c29e3c](https://github.com/magento/magento2/commit/2b8e142ab6025627d20c5052b538d8e354c29e3c)
 - [c4411b44f1997062da37c99cf205bbb89f713202](https://github.com/magento/magento2/commit/c4411b44f1997062da37c99cf205bbb89f713202)
 - [6e88af6fc291d3751a6cf38ad5e0be1664a5b3cf](https://github.com/magento/magento2/commit/6e88af6fc291d3751a6cf38ad5e0be1664a5b3cf)

The fix will be available with the upcoming 2.2.10 release.

**Comment by Patelcc** [comment]
@magento-engcom-team thanks for the update it will be available upcoming **2.2.10** but this issue is also reproduced in **2.3.X** and while report issue I was mentioned version **2.3.0** so i think it should be open. for Magento **2.3.X**
