### ISSUE TITLE
php bin/magento catalog:image:resize error if image is missing

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#22808]
### Preconditions (*)
1. Magento 2.3.1 

### Steps to reproduce (*)
1. Delete manually a product image from pub/media/catalog folder 
2. Execute catalog:image:resize 

### Expected result (*)
1. The system creates the resized images for all products that the images exist and lists the errors.

### Actual result (*)
1. The execution halts immediately at the first missing image. 

![image](https://user-images.githubusercontent.com/20220341/57453750-d7dc8300-726f-11e9-9a9b-f40b3784830c.png)

This doesn't affect on the fly generation of images when browsing the products but it's good to be able to execute and test.

**Comment by nikunjskd20** [comment]
Hi, I am facing the same issue in **Magento Commerce ver. 2.3.1**

**Comment by ioweb-gr** [comment]
I forgot to mention this can also happen after migrating from magento 1 because the data migration tool does not take into account a few things regarding media galleries like cleaning up catalog_entity_varchar table and magento 2 cannot handle product images where the path is not like /x/x/filename.ext but just /filename.ext. the latter can happen in older versions of m1 using csv import so this can be a problem for a lot of users who migrated

**Comment by gwharton** [comment]
How about database media storage mode, when it is valid for pub/media to be completely wiped. Make sure any solution works in this mode too.

**Comment by amitvishvakarma** [comment]
#imagine2019

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17217`, `MC-17218` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ioweb-gr, @k4emic, @tdgroot, @gulshanchitransh. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [6a694a9bab15ab20531ffb2f70a744127611a1e3](https://github.com/magento/magento2/commit/6a694a9bab15ab20531ffb2f70a744127611a1e3)
 - [6e350d1a703199ded6d872367a5668f57c9f92cb](https://github.com/magento/magento2/commit/6e350d1a703199ded6d872367a5668f57c9f92cb)
 - [3a818b218434eb8dd4961a0a8b8b20013c593c14](https://github.com/magento/magento2/commit/3a818b218434eb8dd4961a0a8b8b20013c593c14)
 - [9a44da1e9b910d8c1c06f4af9e02b8db91e9ea7a](https://github.com/magento/magento2/commit/9a44da1e9b910d8c1c06f4af9e02b8db91e9ea7a)

The fix will be available with the upcoming `2.3.3` release.

**Comment by gwharton** [comment]
Hmmm, those commits don't appear in 2.3-develop and they also conflict with changes that were merged into 2.3-develop in PR #23598 11 days ago. @ihor-sviziev can you take a quick look at this to make sure this is right. which commits will take precedence, the above commits, or those in #23598. 2.3-develop currently reflects the changes in #23598.

Update : OK, forget this comment. Perhaps things just hadnt updated when I viewed them. 2.3-develop now reflects both commits, with conflicts resolved.

**Comment by ihor-sviziev** [comment]
Hi,
Sorry, right now on vacation, could check it in a weak

**Comment by gwharton** [comment]
@ihor-sviziev . Don't worry. a check of 2.3-develop around 10 minutes later showed it had been merged and conflicts resolved so we're all good. Well, apart from the fact that the conflicts weren't resolved correctly and the bug that #23598 fixed is now broken again, but thats another issue, for another PR, for another day. :)
