### ISSUE TITLE
Shipping price is not applied properly while Check Out with Multiple Addresses

### ISSUE THREAD

**Issue by singhabhinay** [magento/magento2#22820]
Shipping price is not applied properly while Check Out with Multiple Addresses

### Preconditions (*)
1. php 7.2
2. Magento 2.3

### Steps to reproduce (*)
1. Login to customer account 
2. Add product to cart (minimum quantity 2)
3. View and Edit cart
4. Select Check Out with Multiple Addresses
5. Select two different Shipping Address
6. Select two different Shipping Method with different shipping price
7. Select any payment method for Billing Information
8. Now getting the error, same shipping price for both in Review Order (before it we have select two different shipping price for both but getting here same shipping price that's the issue )

### Expected result (*)
1. While checkout with multiple address and  select two different Shipping Method with different shipping price
2. At the time of order review different shipping price can be applied for multiple address 
(as we have selected different shipping method with different prices for respective address) 

### Actual result (*)
1. While checkout with multiple address and  select two different Shipping Method with different shipping price
2.At the time of order review same shipping price can be applied for all the shipping address 
(as we have selected different shipping method with different prices for respective address) 

![edit-cart](https://user-images.githubusercontent.com/32534204/57532738-d4bdc180-7359-11e9-8ff9-09bbcc7b5a39.png)

![git-address](https://user-images.githubusercontent.com/32534204/57532795-f0c16300-7359-11e9-913d-b29264f4e266.png)

![git-price](https://user-images.githubusercontent.com/32534204/57532816-fc148e80-7359-11e9-8012-2be6c6ef406e.png)

![git-payment](https://user-images.githubusercontent.com/32534204/57532826-00d94280-735a-11e9-8ef9-062f02a0414c.png)

![git-error-price](https://user-images.githubusercontent.com/32534204/57532834-06368d00-735a-11e9-9297-5529bb43a5ca.png)

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-22820-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22820-2-3-develop.instances.magento-community.engineering/admin](https://i-22820-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by GovindaSharma** [comment]
i am able to reproduce this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99632`, `MAGETWO-99633` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by GovindaSharma** [comment]
i am working on this

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-22820-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22820-2-3-develop.instances.magento-community.engineering/admin](https://i-22820-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Unable to regenerate the issue.

**Comment by AlexWorking** [comment]
@singhabhinay, I have rechecked the issue. It is easily reproduced on, for example, 2.3.2 (You reported it on 2.3) but in the latest develop version it is reproduced no more. You can check it Yourself. So most likely the issue has been fixed.

**Comment by zaximus84** [comment]
I'm running into this on 2.3.1. I haven't tested on 2.3.2 or develop. It looks to me like the issue is in \Magento\Tax\Model\Sales\Total\Quote\Shipping::collect. This calls setShippingAmount on $quote->getShippingAddress(). $quote->getShippingAddress() isn't the right way to get the address object because it won't necessarily return the same address that totals are being collected for.

It returns the first shipping address in the quote's address collection. The result is that the last address to run through the collect method will have its shipping price copied to the first shipping address in the quote. In the original example in steps to reproduce, the $0 from the second address is being set on the first address (which was previously $5). No matter how many addresses you have during checkout, in theory, only the first will have the wrong shipping price at the end (always the same price as the last address).

If $quote->getShippingAddress() is replaced with $shippingAssignment->getShipping()->getAddress(), it seems to fix the problem. Looking at \Magento\Tax\Model\Sales\Total\Quote\Shipping in the 2.3 develop branch, it doesn't look like the references to $quote->getShippingAddress() have changed. If the issue is indeed fixed in the latest develop, the change was made elsewhere in the application.
