### ISSUE TITLE
[Shipping] The contact us link isn't showing on order tracking page

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#22822]
### Preconditions (*)
1. Magento 2.3-develop
2.

### Steps to reproduce (*)
1. Make sure you have enabled the **Contact Us**
`Stores / Configuration / Contacts [General] / Contact Us`
2. Create a new order
3. Create a shipment for the order
3.1 Add the Tracking Number by using **USPS** carrier
4. Click on the _Track Order_ link (from Order page)

### Expected result (*)
1. Having the contact page enabled, we should see a different error message if the Shipping Carrier is not available. The text should include "_contact us for more information or_"
![Xnip2019-05-10_18-45-53](https://user-images.githubusercontent.com/15868188/57541813-907df180-7358-11e9-8506-10d3650410e6.jpg)

Check this code:
https://github.com/magento/magento2/blob/72aebb7051eb34058b9d25c18ab5fe836f8ae305/app/code/Magento/Shipping/view/frontend/templates/tracking/details.phtml#L43-L47

### Actual result (*)

1. The contact us link is not available
![Xnip2019-05-10_18-46-15](https://user-images.githubusercontent.com/15868188/57541844-a2f82b00-7358-11e9-9c15-f06b8ef6468f.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99650`, `MAGETWO-99651` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by aman3103** [comment]
@eduard13 are you working on this or I can start work on this?

**Comment by eduard13** [comment]
@aman3103 it has been already fixed. Check the above PR.

**Comment by aman3103** [comment]
> @aman3103 it has been already fixed. Check the above PR.

noted.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#22823 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [73869c30edd5ee50c2da8d0ef5ab08e8c770b55b](https://github.com/magento/magento2/commit/73869c30edd5ee50c2da8d0ef5ab08e8c770b55b)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#23019 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [857c305e5e895135fc68083a9907322e43f03ec2](https://github.com/magento/magento2/commit/857c305e5e895135fc68083a9907322e43f03ec2)

The fix will be available with the upcoming 2.2.10 release.
