### ISSUE TITLE
Updated new address not appear after add new at checkout payment method page

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22840]
Updated address not appear after add new at checkout payment method page.

### Preconditions (*)
Magento 2.3

### Steps to reproduce (*)
1. Login to account >> Add some addresses in address book
2. Add product to cart
3. Checkout >> Shipping >> Select any address
4. Go to review and payment page
5. Payment method >> Uncheck the "My billing and shipping address are the same" checkbox
6. Select New address(Add New Address) from drop-down
7. Update address and check the "My billing and shipping address are the same" check box
8. Now review the address

### Expected result (*)
Updated new address should display.

### Actual result (*)
![Test](https://user-images.githubusercontent.com/46617848/57579850-b4a81280-74bf-11e9-9a97-016753fa2e37.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22840-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22840-2-3-develop.instances.magento-community.engineering/admin](https://i-22840-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22840-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22840-2-2-develop.instances.magento-community.engineering/admin](https://i-22840-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99648`, `MAGETWO-99649` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by RonakParmar** [comment]
@bhavik43  As per my knowledge, this is not a bug, I have followed above steps and found that it is correct behavior of "Ship Here" address functionality. Let me explain you what I have understood,
-> On Checkout -> "Shipping" page, you have selected one address on click of "Ship Here" button, So this address will be your shipping address, correct.
-> Now, On "Review & Payments" page, you have un-checked the "My billing and shipping address are the same" checkbox to select different "Billing Address", and you have selected new address from the dropdown.
In this case you have different shipping and billing address, Till this point Magento is working as expected.

Now, You have again checked the "My billing and shipping address are the same" checkbox, and you found that you billing address has been changed to old one. The reason behind this is, the Shipping address which you have selected on "Shipping" page. Because you have checked the checkbox that says, your billing and shipping address will be same, the New billing address has been updated and you see the old shipping address as you billing address at "Review & Payments" page.

Hope this will help you to clear the concept of having same and different shipping/billing addresses. 
Please update me if I have understood anything wrong, let me know your thoughts about this concept.
Thank you.

**Comment by mahesh-rajawat** [comment]
This issue is duplicate of #22112

**Comment by lamasfoker** [comment]
I think this is the right way to fix the bug in shipping-rates-validator.js at line 148
`if (formPopUpState.isVisible()) {`
You have to rid of the esclamation mark, because is when the popup is displayed that must there be the validation

**Comment by LucasCalazans** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans, here is your [Magento instance](https://i-22840-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22840-2-3-develop.instances.magento-community.engineering/admin](https://i-22840-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lamasfoker** [comment]
So @LucasCalazans have you test it?

**Comment by krzksz** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [Magento instance](https://i-22840-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22840-2-3-develop.instances.magento-community.engineering/admin](https://i-22840-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
I am not able to reproduce this issue, so I assume it was fixed via https://github.com/magento/magento2/pull/23656, closing.
