### ISSUE TITLE
Can the GitHub Repository Default to the `master` Branch? 

### ISSUE THREAD

**Issue by astorm** [magento/magento2#2284]
This a request, not a demand, data point of me, etc. 

Now that Magento 2 is near release, and going through the final (standard) stabilizing development steps, would it be possible to have the **default** GitHub branch be `master` instead of `develop`?

That is, if a non-Magento-employee runs

    git clone git@github.com:magento/magento2.git

they should be grabbing a stable branch, and not the up-to-the-minutes-unavoidably-breaking release. 

I know I personally wasted a bit of time when I wanted to checkout the merchant beta when I didn't realize that I'd cloned the `develop` branch.  I've also run across a number of people at conferences  who've had similar problems, as well as folks online (including Rasmus Lerdorf, PHP's inventor)  

I can totally see how, for a Magento employee, starting out on `develop` is the right choice, and helps get that new team member familiar with the build steps and the latest goings on in the source repository.  

However -- for folks that aren't working for Magento, having the first run experience be an unstable `develop` branch can be a real turn off.  Most other open source PHP projects, and open source projects in general, will default to the stable branch for the general public.  i.e. "Here's `master`, the latest and greatest thing which will probably work".  By defaulting to `develop`, you're basically saying to the world 

> If you want to participate in this project or even see what it's about, you need to put in the same effort as a Magento core team member.

That's not a great way to build a new base of community development.  For those of already a part of the Magento ecosystem, we'll grumble, but deal with it to get our extensions and systems running.  However, for the new developer who's approaching Magento for the first time, starting off in `develop` is a real turn-off, especially if the systems in an unusable state because Magento's teams are still figuring something out.

**Comment by mrdevries** [comment]
During the very non-stable nobody should use this period of development, `develop` was the better choice. But now there will be a GA release this month, the expected default will indeed be `master`.

+1 :+1:

**Comment by daim2k5** [comment]
Yes i think there change this after GA release for sure.

**Comment by Flyingmana** [comment]
You have to question, why someone does a git clone. In my sight usually to contribute a PR.
For people who just want to try out, they should know enough to use composer or official downloads.
I mean, really, if you want to try something out you use use the most stable release available, thats nearly never a git branch. thats like, `require something dev-master`, so pure evil to find there.

But, noone can predict how people will use it, so maybe default du master and change back to develop, if it causes to much inconvenience. 
But never state somewhere, that git cloning the repository is the/a recommended way to get a stable release(besides cloning explicite tags)

**Comment by daim2k5** [comment]
At the end hopefully all devs use only https://github.com/magento/magento2-community-edition with composer and not this repository ;-)

**Comment by brendanfalkowski** [comment]
I couldn't install M2 for (at least) the last year because `develop` kept breaking the VMs that community members provided, and I'll never have/want SysAdmin Grade "Cobra Midnight" to resolve that on my own.

From a frontend-er perspective, if there's a chance your default branch will be broken out-of-box I'm probably going to (a) call this too hard (b) give up (c) choose another platform. Lower the barrier to entry at the expense of making a hardened developer switch their branch.

**Comment by erichileman** [comment]
@daim2k5 key steps in that readme have broken links all redirecting to the same page about admin troubles, including the link that shows how to clone the repo. And that readme also links to pages like this which show instructions for cloning with ssh, however that will result in permission denied http://devdocs.magento.com/guides/v2.0/install-gde/install/composer-clone.html  This page should be updated to note the latest stable branch to clone, since it's not master :)

For someone who wants to get started and try it, it's daunting, to say the least due to lack of working instructions.  There also needs to be a "famous 5 minute" magento 2 install guide :)

There's many technical problems with the install docs. That's why we've decided to hold off writing our own blogs/articles on how to do things and instead focus our energy on improving the official docs. I hope others will as well. Because making clear, and most importantly WORKING official install guides, is the key to navigating around issues like checking out the wrong branch.  It's also the key to widespread adoption of M2 and part of the long term success of Magento.

**Comment by fooman** [comment]
I think there are a couple of issues raised in here, mostly around the problem of installing a stable version of Magento which needs to be addressed in the documentation. To me this is not related to the issue raised by Alan of using a different default branch. According to [this](https://help.github.com/articles/setting-the-default-branch/):

> The default branch is considered the base branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch. 

which lets contributors know that you would like all pull requests to be against develop which I think is intentional.

**Comment by xcomSteveJohnson** [comment]
@daim2k5 That page will be updated with information to say how to clone the master branch.

**Comment by davidalger** [comment]
Looping in @alankent here… to the best of my recollection, all deployments and implementations are expected to normally be built using composer pulling packages from the official Magento package server, not cloning GitHub. With GitHub's primary function being development and community involvement, having the develop branch remain the default branch would (to me) make sense because this way community PRs will default to the develop branch, avoiding the hassles (common to other projects) of having to request individuals resubmit a PR simply because they PR'd against the wrong base branch.

**Comment by astorm** [comment]
@all Appreciate the feedback here, **but**, irrespective of what Magento 2's final delivery method is, and what the final documentation for that looks like —

1. People **are** trying to checkout this repository, and run a composer install/update to get Magento 2 up and running.  i.e. this isn't theoretical -- it's a real problem. 

2. When people do that and something doesn't work (due to the natural working in progress nature of the default branch) it creates a negative first impression of the platform, and that impression's hard to shake. 

It's a barrier to platform adoption.  If there's something you can do to make a platform simpler to get started with, **especially** at such an important inflection point in the platform's life, you should do it.  Not doing it sends the clear message that you're not interested in having those folks participate in the platform.

**Comment by erichileman** [comment]
Yeah Alan, that's a great point, and a valid concern.  People will instinctively do a git pull to try it out and that should be working. Which is especially critical at this juncture. :+1:

**Comment by fooman** [comment]
This is how other popular php projects do it:

laravel - master
symfony - 2.8
codeigniter - develop

more [projects here](https://github.com/search?l=PHP&q=stars%3A%3E1&s=stars&type=Repositories) and most of the following seem to have master as the default branch.

**Comment by alankent** [comment]
Yes, we are going to recommend production sites use Composer to create sites, to ensure they have a stable version that you can get extensions etc for. (We are going to actually have pre-built ZIP files which are the same as doing the first few steps with Composer, so you can take the ZIP and drop it straight onto a hosting site without need for command line commands - you can do composer updates via the web interface afterwards.)

Having said that, I am hoping develop will become more stable post GA, because we should not have the same sweeping changes going on as we have been doing pre-GA.

But ultimately this decision lies with @maksek and the engineering team who live and breath this stuff every day.

For further reading, see also http://alankent.me/2015/10/02/magento-2-version-numbering-update/

**Comment by vrann** [comment]
Here are official recommendations on how to install Magento according to your intent: contribute to core, develop custom module or install on production: http://devdocs.magento.com/guides/v2.0/install-gde/install/pre-install.html

As it was mentioned earlier, cloning from git is recommended for contributors only, and "develop" is the best branch to submit contributions to.

**Comment by daim2k5** [comment]
Hi @astorm can we close the issue or have you additional questions?
