### ISSUE TITLE
Not able to change theme from backend 2.3.1

### ISSUE THREAD

**Issue by ShaileshRawat** [magento/magento2#22911]
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by AlexWorking** [comment]
Hello @ShaileshRawat. Thanks for reporting. Though the steps needed to reproduce the issue may seem obvious judging just from the issue's title, we would ask you to provide some more information on how You reproduce it. Also please verify You can reproduce it on a clear Magento instance. For example, there are two available themes: Luma (set by default during installation) and Blank. Try to shift between them and see if You will be facing the same problem. Otherwise there is possibly a problem with the custom theme You are  trying to apply.

**Comment by hitesh-wagento** [comment]
I am working on it

**Comment by hitesh-wagento** [comment]
@magento-engcom-team give me 2.3-develop instance for version 2.3.1

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento, here is your [Magento instance](https://i-22911-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22911-2-3-develop.instances.magento-community.engineering/admin](https://i-22911-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hitesh-wagento** [comment]
Hi @ShaileshRawat 

I have tested in magento version 2.3.1 I can change theme.

Thanks
