### ISSUE TITLE
Reset feature does not clear the date

### ISSUE THREAD

**Issue by renard123** [magento/magento2#22940]
Reset feature does not clear the date

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
Admin > Marketing > Catalog/Cart price rule > Add New Rule > Fill all data with date > now click on reset > Review all the fields are cleared or not

### Expected result (*)
All fields should be blank.

### Actual result (*)
![date-reset-issue](https://user-images.githubusercontent.com/50658701/57979303-a450e400-7a39-11e9-871c-7db1e05958c4.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99760`, `MAGETWO-99761` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#23007 by @niravkrish in 2.3-develop branch
Related commit(s):
 - [c9f98fcebb40bbb9ee8fd7ca6f27e63c86ecc2ab](https://github.com/magento/magento2/commit/c9f98fcebb40bbb9ee8fd7ca6f27e63c86ecc2ab)
 - [40cc415a21ddc38dc5f410698c830c2918628891](https://github.com/magento/magento2/commit/40cc415a21ddc38dc5f410698c830c2918628891)

The fix will be available with the upcoming 2.3.3 release.

**Comment by sidolov** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#23658 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [68ba53d05b9777db4a7de7e60dabf29b2d02539a](https://github.com/magento/magento2/commit/68ba53d05b9777db4a7de7e60dabf29b2d02539a)
 - [e378c79beac850ecabc9f348654060a8caea8876](https://github.com/magento/magento2/commit/e378c79beac850ecabc9f348654060a8caea8876)

The fix will be available with the upcoming 2.2.10 release.
