### ISSUE TITLE
could you provide a conf file for the nginx

### ISSUE THREAD

**Issue by shyandsy** [magento/magento2#2294]
when I use the sample config for magento, there is an error 

"Stoping nginx... nginx: [emerg] "location" directive is not allowed here in /usr/local/nginx/conf/vhost/magento.shyandsy.com.conf:30
 t"

could you provide a new version of nginx conf which can be deployed
ref: https://github.com/magento/magento2/blob/develop/nginx.conf.sample#L12

then I tried the tutorial on below
ref：https://firebearstudio.com/blog/magento-2-nginx-configuration.html

due to "the 502 bad getway"

**Comment by dfediuk** [comment]
My working Nginx config: https://mage2.pro/t/24
It is for PHP-FPM and subdirectory (site.com/store) case.

**Comment by shyandsy** [comment]
still not work on my lnmp environment
when i open the debug mode on nginx conf, i got error message said that i cant run setup wizard, try console setup

**Comment by johnbendi** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: shyandsySent: Sunday, Nove mber 8, 2015 5:45 PMTo: magento/magen. o.    G2Reply To: magento/magento2Subject: Re: [magento2] could you provide a conf file for the nginx (#gg)still not work on my lnmp environment
when i open the debug mode on nginx conf, i got error message said that i cant run setup wizard, try console setup

—Reply to this email directly or view it on GitHub.

**Comment by Flyingmana** [comment]
You did probably just copy the config file into your nginx config directory instead of reading the first lines of comment.
I belive this, because the line number in your error message, matches exactly the one in the `nginx.conf.sample`.

as described in http://stackoverflow.com/a/31354359/716029 this error message happens, if you have the `location` directive not inside a `server` directive.

And if you follow the example inside the comment of `nginx.conf.sample` you dont copy the file, you use it via `include /vagrant/magento2/nginx.conf.sample;` inside your server directive.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [technical issues forum](https://community.magento.com/t5/Technical-Issues/bd-p/magento-2-technical-issues) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
