### ISSUE TITLE
Spacing issue for Gift message section in my account

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#22950]
Spacing issue for Gift message section in my account

### Preconditions (*)
Magento 2.3

### Steps to reproduce (*)
1. Admin: Add product with enable gift option
2. Front end: Add to cart product
3. Shopping cart: Add gift option data and place order
4. Review at my order gift option data

### Expected result (*)
Spacing should appropriate.

### Actual result (*)
![test](https://user-images.githubusercontent.com/49804008/58023441-69c87380-7b2d-11e9-916f-65e1eeac13e1.png)

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22950-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22950-2-3-develop.instances.magento-community.engineering/admin](https://i-22950-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-22950-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22950-2-2-develop.instances.magento-community.engineering/admin](https://i-22950-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99764`, `MAGETWO-99765` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amjadm61** [comment]
@magento-engcom-team I'm working on it.

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#23226 by @amjadm61 in 2.3-develop branch
Related commit(s):
 - [878ea22d4a39b6e9503c8fdbf84d6c57043e3b70](https://github.com/magento/magento2/commit/878ea22d4a39b6e9503c8fdbf84d6c57043e3b70)
 - [02ff91ba994dfc017145e48e5b6dcf75ffdb7b32](https://github.com/magento/magento2/commit/02ff91ba994dfc017145e48e5b6dcf75ffdb7b32)

The fix will be available with the upcoming 2.3.3 release.

**Comment by sidolov** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#23657 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [bd6d89f7c2c61c7e849135175bb3086711c916ee](https://github.com/magento/magento2/commit/bd6d89f7c2c61c7e849135175bb3086711c916ee)

The fix will be available with the upcoming 2.2.10 release.
