### ISSUE TITLE
Wrong behavior of grid row and checkbox click

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#22988]
Impossible check/uncheck checkbox if click on right bottom angle of checkbox
When you try to select value in input field checkbox unchecking automatically

### Preconditions (*)

1. magento 2.3-develop

### Steps to reproduce (*)

1. Go to Catalog->Categories page
2. Open Products in Category fieldset
3. Try to select value in position field with mousup not above input field

Same steps for admin order create page with Assign products

### Expected result (*)

![wuyhv_2019-05-23_15-45-35](https://user-images.githubusercontent.com/1129623/58254244-02036a00-7d73-11e9-874a-06d3ab822233.gif)

![834nj_2019-05-23_15-33-17](https://user-images.githubusercontent.com/1129623/58254246-029c0080-7d73-11e9-8b7d-4bc7510db87a.gif)

![slb3v_2019-05-23_15-31-27](https://user-images.githubusercontent.com/1129623/58254247-029c0080-7d73-11e9-9912-a716c1b5f6af.gif)

### Actual result (*)

![1hkmj_2019-05-23_15-59-02](https://user-images.githubusercontent.com/1129623/58254624-cf0da600-7d73-11e9-9a54-7647cea6cde9.gif)

![bh9mh_2019-05-23_15-55-05](https://user-images.githubusercontent.com/1129623/58254625-cfa63c80-7d73-11e9-91f4-1af3ffc8662f.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99812` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#22990 by @Den4ik in 2.4-develop branch
Related commit(s):
 - [0105e4c59d5606662a100580c4627e29f6f999cf](https://github.com/magento/magento2/commit/0105e4c59d5606662a100580c4627e29f6f999cf)
 - [22aa250d5897c1ea1a60d8d289aab98413d3860e](https://github.com/magento/magento2/commit/22aa250d5897c1ea1a60d8d289aab98413d3860e)
 - [2b19c93728fceca3439df2954bbcf924af5e8906](https://github.com/magento/magento2/commit/2b19c93728fceca3439df2954bbcf924af5e8906)
 - [0988b6e5baf61535495cbdb1eb64b59aa0818feb](https://github.com/magento/magento2/commit/0988b6e5baf61535495cbdb1eb64b59aa0818feb)
 - [69447cbbfa4e70b162b9d080bd25f0a377edd6db](https://github.com/magento/magento2/commit/69447cbbfa4e70b162b9d080bd25f0a377edd6db)
 - [021b5d858670d2f3c8eb2e82bc2454d825abe776](https://github.com/magento/magento2/commit/021b5d858670d2f3c8eb2e82bc2454d825abe776)
 - [27a57deb6a6e2f4746e3d0a83946b8234818eee3](https://github.com/magento/magento2/commit/27a57deb6a6e2f4746e3d0a83946b8234818eee3)
 - [d2af2867c5828c33bb6c41db09d169a42437cb4f](https://github.com/magento/magento2/commit/d2af2867c5828c33bb6c41db09d169a42437cb4f)
 - [8b7458e01f8c07a6f8de3718df318eb236366469](https://github.com/magento/magento2/commit/8b7458e01f8c07a6f8de3718df318eb236366469)

The fix will be available with the upcoming 2.4.0 release.
