### ISSUE TITLE
Default registration behavior for extensions without «registration.php» file

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2298]
I use the same `registration.php` file for all my [Magento 2 extensions](https://mage2.pro/c/extensions): 
```
<?php
use Magento\Framework\Component\ComponentRegistrar;
$name = implode('_', array_map(function($part) {
	return implode(array_map('ucfirst', explode('-', $part)));
}, array_slice(explode(DIRECTORY_SEPARATOR, __DIR__), -2, 2)));
ComponentRegistrar::register(ComponentRegistrar::MODULE, $name, __DIR__);
```
I do not like that I need to duplicate the same file for each extension.  
The core modules do even worse: they use the same `registration.php` file for each 100 modules, but with unique string (the module name) within, for example:
https://github.com/magento/magento2/blob/22629abe10f9c640fe47b6081d57fedccdea8e0f/app/code/Magento/AdminNotification/registration.php#L9

I propose to use some default registration behavior when an extension has no the `registration.php` file.
My code above can be used as the default registration behavior.

**Comment by davidalger** [comment]
@dfediuk declaring the identifier using a string constant is more performant than the use of multiple array functions. Since these registration.php files are all executed on every run, using the array functions for this purpose would very easily introduce a significant performance hit, and so the hard-coded string is far better.

Currently the registration.php file is what is used to locate the modules presence in the system if a module has not been installed via composer (in which case the registration file is loaded by composer). How do you propose the system locate modules, themes, language packs, etc without these files and still performantly recognize modules? The system needs to detect the presence of components in some fashion.

**Comment by Flyingmana** [comment]
It may not be beautiful or nice, but it works and solves a main problem in a easy way.

If you dont like it, feel free to implement an own module detector.

https://github.com/magento/magento2/blob/develop/app/etc/NonComposerComponentRegistration.php is added via a simple composer file autoload. You can build an own package, which adds itself via file autoload (means it gets always included) and then implement an own detection algorithm there.

The next step is, all of your modules requiring your module loader package, instead of adding a `registration.php`.


This should solve the Issue you have.

**Comment by vrann** [comment]
I want to highlight that the main reason of adding registration.php is to add possibility to load same module from *different* locations. 

Let's say you develop your own module in app/code/YourName/ModuleName. While you do so, location of the module stay the same and it seems like no registration.php is needed. 

Now, let's say development completed and you decided to package it as a composer package and release on Packagist or on Magento Marketplace (ex Connect). The user who installs it from the Packagist will get it in the vendor/your-name/module-name directory. If the package does not have registration.php, there will be no way for the framework to locate it in filesystem.

The reason why we made it required to have registration.php -- we want to encourage usage of composer infrastructure as much as possible and make any extension developed be compatible with the composer repository. It is not a huge overhead to add simple file as a part of development process, but you gain possibility to distribute the extension on git, Connect, Packagist, etc. Any of these sources can be used as a part of development lifecycle.

**Comment by kandy** [comment]
For me  better developer experience  is develop my custom module in vendor directory from start. 
I create github repo  (or my local privare repo) with composer.json file and require module with composer. As result I get git powered module inside vendor directory  that i can use for development. 

Also I believe that register.php is not need in vendor dir, because extension already registered in composer, so why we need one more registration in this case?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.
