### ISSUE TITLE
Cookies flag issue

### ISSUE THREAD

**Issue by ivanoanekcha** [magento/magento2#22993]
we have security issue report and one of the major issue is that the cookies flag.
attach below is the summary of the report and the steps to reproduce.

The environment is ubuntu
php7
nginx
mysql
magento 2
cache

The expected result is that the issue should be perfectly resolve.

[security  Detailed Scan Report (1) (1).pdf](https://github.com/magento/magento2/files/3212357/security.Detailed.Scan.Report.1.1.pdf)

Kindly help me fix this issues as soon as possible.

Thanks.

**Comment by hostep** [comment]
This might be related to https://github.com/magento/magento2/issues/22272

**Comment by DrewML** [comment]
Yep @hostep, good catch - dupe of #22272. Closing this, as there is more discussion over there + an open PR https://github.com/magento/magento2/pull/22793

**Comment by ivanoanekcha** [comment]
Hello,
How would you please help me to resolve this issue?
we have Magento 2 e Commerce system installed on ubunto servers and we have
security issue report and we need them to  fixed, One of the major issue is
the cookies flag.

The summary of the report is attached below
The environment is SSH
Steps to reproduce:
lease follow the below steps for the installation of VPN client:



You need to install the VPN client from the below link:



http://www.forticlient.com/downloads



after installation please follow the below:



1- Select remote access.

2- Click on settings.

3- Select add a new connection as below:

image.png

4- Select SSL VPN.

5- Add 212.35.66.34 to the remote gateway and check the boxes as below:





6- Apply, then test the connection.



user : optimal

pass: ****** (redacted)

---------------------------------------------------

ssh

ip : 192.168.130.82

user : umniah

pass: ****** (redacted)

port : 22



----------------------------------------

website

url : https://eshopstaging.umniah.com

url admin : ****** (redacted)

user : admin

pass: ****** (redacted)




Kindly help me out.

**Comment by hostep** [comment]
@ivanoanekcha: I've edited your post and stripped out all passwords you posted. Please don't do that, everybody can just use these if they were correct. Please also **immediately** change all passwords since they've been out in the open for a couple of hours. People might abuse these to hack your system.

As for your problem, it looks like you might need to contact some professional developer to help you out. Github isn't really meant for stuff like this. You might have better luck asking around on https://magento.stackexchange.com/ or on https://community.magento.com/, but please, do **not** post usernames or passwords with access to your system out in the open!

**Comment by ivanoanekcha** [comment]
alright. Thanks

**Comment by Sharmilasrini95** [comment]
@ivanoanekcha  Got a solution?
