### ISSUE TITLE
Grid Action Column Design Issues

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#23024]
### Preconditions (*)

1. Magento 2.3.x
2. Magento 2.2.x

### Steps to reproduce (*)

1. Open any Grid that action column have more than one action like CMS Block grid.
2. Programatically change the position of action column.
3. Comment updated_time column flush cache and reload grid.
4. Now remove comment and flush cache and reload the grid. now action column will at second last position.   https://prnt.sc/ntyan7 
5. Now select action, you will see the column popup always at last position.
https://prnt.sc/ntybge

### Expected result (*)

1. 
![Screenshot46](https://user-images.githubusercontent.com/32479280/58424233-9ee83f00-80b4-11e9-9b52-b88c7abf94bf.png)

2.

### Actual result (*)

1. https://prnt.sc/ntyd3p
2.

**Comment by Shubham0492** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-23024-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23024-2-3-develop.instances.magento-community.engineering/admin](https://i-23024-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@Den4ik Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23024-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23024-2-3-develop.instances.magento-community.engineering/admin](https://i-23024-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17270`, `MC-17271` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by prabhatrawat-webkul** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul, here is your [Magento instance](https://i-23024-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23024-2-3-develop.instances.magento-community.engineering/admin](https://i-23024-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
The related internal Jira ticket `MC-17270, MC-17271` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-17271` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by magento-engcom-team** [comment]
Hi @mahesh-rajawat. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23726` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
