### ISSUE TITLE
Wrong behaviour of validation scroll

### ISSUE THREAD

**Issue by Den4ik** [magento/magento2#23034]
### Preconditions (*)

1. 2.3-develop

### Steps to reproduce (*)

1. Open create order page in admin panel
2. Click Add Product button
3. Click Submit Order  button
Page scrolling down and up instead of focusing on non valid field

### Expected result (*)

![malu9_2019-05-28_15-38-05](https://user-images.githubusercontent.com/1129623/58478908-cba56080-815f-11e9-9a65-d1719ece79aa.gif)

### Actual result (*)

![qcj64_2019-05-28_15-42-50](https://user-images.githubusercontent.com/1129623/58478932-d95ae600-815f-11e9-9786-b91a311a76d9.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99852`, `MAGETWO-99853` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#23035 by @Den4ik in 2.3-develop branch
Related commit(s):
 - [5b0191348477cc72a7f575c0e8b46c3a74c1287f](https://github.com/magento/magento2/commit/5b0191348477cc72a7f575c0e8b46c3a74c1287f)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your report. 
The issue has been fixed in magento/magento2#23086 by @Den4ik in 2.2-develop branch
Related commit(s):
 - [0820cd71b3fdd8a1b66f101a256b5f9b5690ae01](https://github.com/magento/magento2/commit/0820cd71b3fdd8a1b66f101a256b5f9b5690ae01)

The fix will be available with the upcoming 2.2.10 release.
