### ISSUE TITLE
[Magento 2.3.x] Declarative Schema :: Data/Schema Patches getAliases() not working as expected

### ISSUE THREAD

**Issue by atishgoswami** [magento/magento2#23031]
# Preconditions
**Project Environment** 

Magento Version: 2.3.x CE
PHP: 7.2
Database: MySQL 5.7
OS: CentOS 7
Caching: Varnish Cache and OPcache

# Steps to reproduce
1. Create a schema patch with a class name e.g. ExampleSchemaPatch
2. Add a logger inside the apply method for the schema patch class to indicate that the apply method was executed
3. Run setup:upgrade
4. Check the `patch_list` table a fully qualified class name for the patch class would be present
5. Check the log file to confirm that the apply method for the patch was executed
6. Now change the class name of the applied patch to some something else e.g. ChangedExampleSchemaPatch
7. Added the old class name as an array item for the return array for the getAliases() method
```php
public function getAliases()
{
    return [
        ExampleSchemaPatch::class
    ];
}
``` 
8. Run setup upgrade one more time

# Actual Result

1. The patch gets reapplied. This can be verified by checking the log file
2. A new entry of the renamed patch is added to the patch_list table

# Expected Result

The patch should not be reapplied.

Note: This issue can be replicated for Data as well as schema patches

**Comment by magento-engcom-team** [comment]
@korostii Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by francescosalvi** [comment]
Maybe I am dumb or have missed the point of the issue, but how does the change in https://github.com/magento/magento2/pull/25265/files solve this issue exactly?

I see that the current patch is applied _first_ (line :162) and only _then_ `getAliases()` is invoked and its result iterated... shouldn't it be the other way around? (i.e.: get aliases, if some is already listed in history, skip apply of current patch)

In fact, by testing empirically, all I get from adding the old class/patch name among aliases, is that the migration breaks when it reaches the current patch.. but only _after_ having applied it!

Therefore I think documentation snippet at https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/data-patches.html
> This internal Magento method, that means that some patches with time can change their names,
> but changing name should not affect installation process, that's why if we will change name of the patch
> we will add alias here

is misleading

**Comment by dareenzo** [comment]
@francescosalvi I'm no expert either, but I'd say you're at least half-right.

The patch does not get applied twice only due to the rollback called within the catch clause. 

While the actual behavior does not match what is written on the docs, I think the intended behavior is the one described.

The incorrect behavior I see (in my case) is that the application of the new patch fails while referencing the first one (an alias). But according to that doc snippet there should be no exception thrown, but simple skipping of reapplying the patch.

![Screenshot from 2020-12-22 15-43-49](https://user-images.githubusercontent.com/6130991/102894943-872d9400-446c-11eb-9733-a56adb28dc2f.png)

@magento-engcom-team could you reopen and have a second look at this issue?

**Comment by dareenzo** [comment]
Opened a new issue https://github.com/magento/magento2/issues/31396
