### ISSUE TITLE
Entity Attributes not showing while export the Products

### ISSUE THREAD

**Issue by ghost** [magento/magento2#23049]
### Preconditions (*)

1. 2.2.6

### Steps to reproduce (*)

1. Admin -> System -> Data Transfer -> Export
2. Select product from Entity type  
3. It displays the entity attributes
4. Change the Entity type to -- Please Select --
5. It will hide the entity attributes
6. Now Again select the Products from Entity type

### Expected result (*)

1. Product should have exported buy it failed to export
All the Entity Attributes should display.

### Actual result (*)

1. .https://nimb.ws/sAe98t

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23049-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23049-2-2-develop.instances.magento-community.engineering/admin](https://i-23049-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23049-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23049-2-3-develop.instances.magento-community.engineering/admin](https://i-23049-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99863` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment]
Hello @wajeehmmc !

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
