### ISSUE TITLE
Sendfriend works for products with visibility not visible individually

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#23053]
### Preconditions (*)

1. A simple product is created

### Steps to reproduce (*)

1. Find the product on the storefront and click EMAIL icon.
2. Add this page to bookmarks.
3. Restrict visibility of the product
4. Go back to your page from the bookmarks bar. URL should look like
`http://graphql-ce.io/sendfriend/product/send/id/1/cat_id/3/`
5. Send email

### Expected result (*)

1. On step 4 I see that page not found. Proceeding to step 5 is imposible.

### Actual result (*)

1. Email sent.
![Screenshot_2019-05-27_16-23-42](https://user-images.githubusercontent.com/11827230/58564237-41c7c700-8235-11e9-82d1-1ab2cf9b844f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17108`, `MC-17109` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/magento2#23118 by @Wirson in 2.3-develop branch
Related commit(s):
 - [265e0d4e7ca2bc051652241020a1609e48523f72](https://github.com/magento/magento2/commit/265e0d4e7ca2bc051652241020a1609e48523f72)
 - [74373a005e6c018b691fcbf3191862d9960bc624](https://github.com/magento/magento2/commit/74373a005e6c018b691fcbf3191862d9960bc624)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/magento2#23121 by @Wirson in 2.2-develop branch
Related commit(s):
 - [8476c1ff550e0b0ff9213a11a84360559230f749](https://github.com/magento/magento2/commit/8476c1ff550e0b0ff9213a11a84360559230f749)

The fix will be available with the upcoming 2.2.10 release.
