### ISSUE TITLE
Magento 2.3.1 - URL rewrite rules are not creating for product after update url key

### ISSUE THREAD

**Issue by Vishrootways** [magento/magento2#23074]
### Summary (*)
We are facing an issue with URL rewrite rules in fresh Magento 2.3.1 version. Issue: URL of the product does not getting updated after change URL key of category in multi-website setup. (NOTE: This issue is not coming when only one website is set up)

### Preconditions (*)
Fresh Magento 2.3.1 One category which has one product. Multi website setup.

### Steps to reproduce (*)
1. Go to the category at admin side.
2. Update URL key of category.
3. Save category.

### Expected result (*)
Rules should be created/updated for the category and all products which are assigned to this category as well it should be created for all websites.

### Actual result (*)
New URL rules are created with updated the key for the category but not created for the product. NOTE: URL rules of the product are created for the second website which does not default website, rules only not created for the mail website product.

**Comment by AlexWorking** [comment]
As the reporter says "NOTE: URL rules of the product are created for the second website which does not default website, rules only not created for the mail website product." It's that for the 2.3 version. In 2.2-develop it's right the opposite -  rules not created for the second (non-default) website product meening /category-url-key/product-url-key.(html).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17160`, `MC-17161` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Vishrootways** [comment]
@AlexWorking Thank you for reviewing issue we are getting and confirm that it's an issue in Magento. Please let us know if you want any additional information from our side to find and solve this issue.
Thanks,
Vish

**Comment by sta1r** [comment]
#mmuk2019 assign to me

**Comment by magento-engcom-team** [comment]
@sta1r thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @Vishrootways. Thank you for your report. 
The issue has been fixed in magento/magento2#23309 by @sta1r in 2.3-develop branch
Related commit(s):
 - [8fe7c88bf68c7eec7eb761f7b7690d73a9bb2ec1](https://github.com/magento/magento2/commit/8fe7c88bf68c7eec7eb761f7b7690d73a9bb2ec1)
 - [60b577e3fa998ab9b4b85b0fb486cf542d626168](https://github.com/magento/magento2/commit/60b577e3fa998ab9b4b85b0fb486cf542d626168)
 - [32de2806b5ea38b8d0b424838a5424f8279a6276](https://github.com/magento/magento2/commit/32de2806b5ea38b8d0b424838a5424f8279a6276)
 - [0da86ab8610b690d7ac149059f9b7c36e136f914](https://github.com/magento/magento2/commit/0da86ab8610b690d7ac149059f9b7c36e136f914)
 - [2d0fb70cb99fe7866eee251376a2de08dd2eab0c](https://github.com/magento/magento2/commit/2d0fb70cb99fe7866eee251376a2de08dd2eab0c)

The fix will be available with the upcoming 2.3.3 release.
