### ISSUE TITLE
Chinese locale code mismatch with PayPal

### ISSUE THREAD

**Issue by ghost** [magento/magento2#23082]
### Steps to reproduce 
1.Magento Paypal Express is configured
2.Set Stores->Configuration->General->Locale Options->Locale=Chinese (China)
3.Add product to cart
4.Check mini cart and cart page

### Expected result
a PayPal buttons rendered

### Actual result
a PayPal buttons aren't rendered

### More info:
Magento offers locale codes for zh_Hans_CN (China), zh_Hant_HK (Hong Kong) and zh_Hant_TW (Taiwan).

However, PayPal uses the codes zh_CN, zh_HK and zh_TW with its validation JS library using a regex of `^[a-z]{2}[_][A-Z][A-Z0-9]$`

This means a store using a Chinese locale in Magento will fail the PayPal validation when trying to render a PayPal button, with the locale set by the one used by the store.

Which code is correct is up for debate, but one needs to be the standard.

**Comment by syed92hasan** [comment]
I am working on this at #MM19DE

**Comment by ghost** [comment]
@syed92hasan what is your proposed fix?

**Comment by magento-engcom-team** [comment]
@VasylShvorak Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @VasylShvorak 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17236` were created

**Issue Available**: @VasylShvorak, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@VasylShvorak what is going to be the proposed fix to this?

Is it Magento at fault, or PayPal?

**Comment by magento-engcom-team** [comment]
Hi @paul-gene. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-17977` was closed as `non-reproducible` in `2.2-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by ghost** [comment]
It's been confirmed in 2.3...

**Comment by viktym** [comment]
We are working on it

**Comment by ghost** [comment]
@viktym you might want to remove the "cannot reproduce" label then?

Not sure what's going on with what I presume is a bot?

**Comment by magento-engcom-team** [comment]
Hi @paul-gene. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [2001743fa8b058586aa208020907895f995683ea](https://github.com/magento/magento2/commit/2001743fa8b058586aa208020907895f995683ea)

The fix will be available with the upcoming `2.3.3` release.
