### ISSUE TITLE
Date format grid is not based on the locale defined in the back-office

### ISSUE THREAD

**Issue by MeCapron** [magento/magento2#23113]
### Preconditions (*)
Magento 2.3.1

### Steps to reproduce (*)

1. Change locale from Magento back-office (for example, French)
2. Go to Sales -> Orders 
3. Check the column "purchase date"
4. Date format is still the english one

### Expected result (*)
Having the format date in French (or whatever locale chosen) instead of the default one

### Actual result (*)
Date format should be the local one

Every column is traduced but the date format one is not
![zodio](https://user-images.githubusercontent.com/49562288/58812304-da898880-8621-11e9-95d6-7d30cd6ed2be.png)

**Comment by MeCapron** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MeCapron. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MeCapron, here is your [Magento instance](https://i-23113-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23113-2-3-develop.instances.magento-community.engineering/admin](https://i-23113-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23113-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23113-2-3-develop.instances.magento-community.engineering/admin](https://i-23113-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AlexWorking 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17268`, `MC-17269` were created

**Issue Available**: @AlexWorking, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @MeCapron. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [db905b8cb6edf9ee6bd933a6d7f718f3147b56d3](https://github.com/magento/magento2/commit/db905b8cb6edf9ee6bd933a6d7f718f3147b56d3)
 - [3a31197544e93a29d86e509eb3389813b99735bc](https://github.com/magento/magento2/commit/3a31197544e93a29d86e509eb3389813b99735bc)
 - [3e0e4e263d398a30f68689fc308114c881d4c19d](https://github.com/magento/magento2/commit/3e0e4e263d398a30f68689fc308114c881d4c19d)
 - [ddb015e156b01c2df179b42859986f9a46650dab](https://github.com/magento/magento2/commit/ddb015e156b01c2df179b42859986f9a46650dab)
 - [227475fc9326fcf70322b44cec35b2ed9df6cc55](https://github.com/magento/magento2/commit/227475fc9326fcf70322b44cec35b2ed9df6cc55)
 - [928ca8c2fd316c528f34d2c5ed9bfb3f837017cf](https://github.com/magento/magento2/commit/928ca8c2fd316c528f34d2c5ed9bfb3f837017cf)
 - [8ecec7ba720266bd2283acc69a3107a7ba64510b](https://github.com/magento/magento2/commit/8ecec7ba720266bd2283acc69a3107a7ba64510b)
 - [7a91e775e120415d0ae51a64d9e5fe635c3b7249](https://github.com/magento/magento2/commit/7a91e775e120415d0ae51a64d9e5fe635c3b7249)
 - [cd2d8e0a6de2781c335ec267b741440b0d83a2f1](https://github.com/magento/magento2/commit/cd2d8e0a6de2781c335ec267b741440b0d83a2f1)
 - [d0ba3b629eed6db7c0971b1f1a0f9c2e8e94b2c7](https://github.com/magento/magento2/commit/d0ba3b629eed6db7c0971b1f1a0f9c2e8e94b2c7)
 - [f35aaab34e06b5b96045198d850862982528c100](https://github.com/magento/magento2/commit/f35aaab34e06b5b96045198d850862982528c100)

The fix will be available with the upcoming `2.3.3` release.
