### ISSUE TITLE
Magento_Theme. Incorrect configuration file location 

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#23138]
### Summary (*)
File `system.xml` locates in the `app/code/Magento/Theme/etc/` instead of `app/code/Magento/Theme/etc/adminhtml`.

### Proposed solution

Move `system.xml` to `app/code/Magento/Theme/etc/adminhtml`.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17331` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @atwixfirster. Thank you for your report. 
The issue has been fixed in magento/magento2#23140 by @atwixfirster in 2.3-develop branch
Related commit(s):
 - [51e11c12bc8a9213d9e88af58a497b65116e3fcf](https://github.com/magento/magento2/commit/51e11c12bc8a9213d9e88af58a497b65116e3fcf)
 - [ef12f0006900d30ac48fb79ffeadaac3cb70b270](https://github.com/magento/magento2/commit/ef12f0006900d30ac48fb79ffeadaac3cb70b270)

The fix will be available with the upcoming 2.3.3 release.
