### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by tylers-username** [magento/magento2#23145]
In Magento 2.2 dashes are not allowed in store codes. If you attempted to update a store code with a dash an error is thrown:

```
The store code may contain only letters (a-z), numbers (0-9) or underscore (_), and the first character must be a letter.
```

Was this intentional? What negative impact could come from allowing dashes?

**Comment by davidverholen** [comment]
hey @tylerssn, thx for bringing this up, but unfortunately this is the wrong place for this discussion.
The issues here are intended for bug reports.

If you want to trigger a technical discussion with the magento architects team, feel free to create an issue in the architecture repository: https://github.com/magento/architecture/issues

Also, the title should be a bit more descriptive or it will probably be closed there, too ;P

**Comment by lano-vargas** [comment]
> Was this intentional? What negative impact could come from allowing dashes?

I would like to know this too. As for Google Hyphen is recommended REF: https://support.google.com/webmasters/answer/76329?hl=en

Anyone have any references?

**Comment by davidverholen** [comment]
@tylerssn @lano-vargas I totally agree with you (maybe I did not really communicate that in my earlier comment :P )

I commented on an architecture issue to try to get it reopened, because I agree this change would make sense and bring much value to the core without breaking anything:
https://github.com/magento/architecture/issues/184
