### ISSUE TITLE
The URL Key field would generate a URL that already exists

### ISSUE THREAD

**Issue by huyphan261** [magento/magento2#23169]
### Preconditions (*)

1. Magento CE 2.2.7 without sample data is installed.
2. Products import from old shop

### Steps to reproduce (*)

1. Go to backend
2. Go to manage products
3. Search any product
4. Try to add Parent category of sub-category

### Expected result (*)

1. [Screenshots, logs or description]
Can not save product with new category
![image](https://user-images.githubusercontent.com/28799537/59094613-b343fb80-8940-11e9-8c3a-941e91fc3d1d.png)
![image](https://user-images.githubusercontent.com/28799537/59094563-9c050e00-8940-11e9-88cf-a3839bb44daf.png)
### Actual result (*)

1. [Screenshots, logs or description]
Can not save product with new category
![image](https://user-images.githubusercontent.com/28799537/59094563-9c050e00-8940-11e9-88cf-a3839bb44daf.png)

**Comment by orlangur** [comment]
@huyphan261 did you set `Use Category URL` to `Yes`?

**Comment by ghost** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar, here is your [Magento instance](https://i-23169-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23169-2-2-develop.instances.magento-community.engineering/admin](https://i-23169-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
Hi @huyphan261  thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.2-develop , seems like this related  your configuration or custom modules, thanks for collaboration.

**Comment by huyphan261** [comment]
> @huyphan261 did you set `Use Category URL` to `Yes`?

where can I set it?

**Comment by huyphan261** [comment]
> Hi @huyphan261 thank you for you report, i'm not able to reproduce following steps you described on clean magento 2.2-develop , seems like this related your configuration or custom modules, thanks for collaboration.

Hi there, I imported product from magento 1

**Comment by hostep** [comment]
@huyphan261: if you've used Magento's official data migration tool, it transfers over the `url_path` attribute from Magento 1 to Magento 2, even though Magento 2 never populates this field and it should always be empty, but M2 still uses it for generating url rewrites if it is in fact filled in. This might cause the problem you are experiencing. This bug is being tracked in https://github.com/magento/data-migration-tool/issues/541 & https://github.com/magento/data-migration-tool/issues/462

You might try to remove all attribute values of the `url_path` **product** attribute in the database of your M2 shop and see if that resolves this problem. But please, test this first, don't immediately start doing this on a production environment :)

>> did you set `Use Category URL` to `Yes`?

> where can I set it?

It's in Stores > Configuration > Catalog > Catalog > Search Engine Optimization > Use Categories Path for Product URLs
But this setting shouldn't matter as Magento's url rewrite mechanism always generates url's with categories in them as well, even it that setting is disabled.
BTW: there will become a new configuration option available in Magento 2.3.2 or 2.3.3 (provided by [MC-4244](https://github.com/magento/magento2/commit/211dd25c73bb2539c3c064374d9d5649f253fd14)) where you can actually disable this behavior called: `Generate "category/product" URL Rewrites`.

**Comment by huyphan261** [comment]
> @huyphan261: if you've used Magento's official data migration tool, it transfers over the `url_path` attribute from Magento 1 to Magento 2, even though Magento 2 never populates this field and it should always be empty, but M2 still uses it for generating url rewrites if it is in fact filled in. This might cause the problem you are experiencing. This bug is being tracked in [magento/data-migration-tool#541](https://github.com/magento/data-migration-tool/issues/541) & [magento/data-migration-tool#462](https://github.com/magento/data-migration-tool/issues/462)
> 
> You might try to remove all attribute values of the `url_path` **product** attribute in the database of your M2 shop and see if that resolves this problem. But please, test this first, don't immediately start doing this on a production environment :)
> 
> > > did you set `Use Category URL` to `Yes`?
> 
> > where can I set it?
> 
> It's in Stores > Configuration > Catalog > Catalog > Search Engine Optimization > Use Categories Path for Product URLs
> But this setting shouldn't matter as Magento's url rewrite mechanism always generates url's with categories in them as well, even it that setting is disabled.
> BTW: there will become a new configuration option available in Magento 2.3.2 or 2.3.3 (provided by [MC-4244](https://github.com/magento/magento2/commit/211dd25c73bb2539c3c064374d9d5649f253fd14)) where you can actually disable this behavior called: `Generate "category/product" URL Rewrites`.

I tried but it's not working
