### ISSUE TITLE
Search result relevance Again

### ISSUE THREAD

**Issue by ivankakurov** [magento/magento2#23171]
### Summary (*)
I need to add search result relevance in my search. I don't care for marketing, i need just to return relevance result. 
### Examples (*)
Go to every clean magetno2 project whit sample data. Enter in search box `Yoga`. 
I expect  the first product to be `Yoga Adventure` not `Josie Yoga Jacket`. 
Also Searching by phrase is nightmare. When i search `Yoga Adventure` i expect to see result ordered:
 1. Product name is exact `Yoga Adventure`
 2. Product name start wit `Yoga Adventure`
 3. Product name contains `Yoga Adventure`
4. Product name contains `Yoga` and `Adventure`
5. Product name contains  `Yoga` or  `Adventure`

I do not expect the first result to be `Josie Yoga Jacket`. 
I will not open the 2nd page where the product `Yoga Adventure` is located. I just will not expect that there is such a product there.

In 95% of cases, users will not return to your store because they have failed to find what they are looking for. This is a huge problem for me.

**Comment by orlangur** [comment]
@ivankakurov this is not a valid bug report. You should understand current implementation first and then suggest concrete changes to it.

**Comment by ivankakurov** [comment]
@orlangur this is not a bug?
what then do you think is a bug -  syntax error or exception ?
i think is that is a bug, but is not related with concrete implementations. This a core bug. 
In my case i found solution and my store has the most accurate and fastest search, but I do not recommend it to anyone unless it is a very experienced programmer.

I reported this here because too many people need a normal search and magento2 does not support it, and there is no plugin to support it without sending the sensitive data to external server.

If you not believe me, just search on google.

**Comment by AlexWorking** [comment]
Hello, @ivankakurov. Thanks for applying. You see, the relevance here may mean much more than simply relevance by search phrase components order. Lets take for instance the following situation. One searches for a product that as far as one remembers contains a word of "Yoga". With that lets assume that "Josie Yoga Jacket" is sold approximately 10000 units per month while "Yoga Adventure" - only 100. So the demand for the first product significantly exceeds the demand for the second one. What would You suggest having the aforementioned information, which of the two products the consumer **_most likely_** is looking for? It's obviously "Josie Yoga Jacket". And so it looks more relevant to show him or her "Josie Yoga Jacket" first. It doesn't mean this algorithm is really used in Magento. It's just an example of how wide the concept of relevance may be. The consumer always can switch to Sort by Product Name to make everything being put out in a standard alphabetical order if the consumer is not satisfied with Sort by Relevance. And to be more concrete in our situation, You haven't, for example, mentioned the Search Weight of the Product Attribute. Did You consider its impact on the search results output? So indeed, You need first to fully understand the current implementation with all of its pluses and minuses in order to be able to propose something better. Until then You simply can not prove that Your suggestions will make the current implementation better. So we deem it proper to close this issue not. But if You find an unexpected behavior from the point of view of the current search implementation please feel free to reopen it.

**Comment by orlangur** [comment]
@ivankakurov if you are not familiar with quality assurance in software development please let me help you.

https://glossary.istqb.org/en/search/bug says 
> defect 
An imperfection or deficiency in a work product where it does not meet its requirements or specifications.
Synonyms: bug, fault

So, when you have no clue how functionality is supposed to work, you cannot determine whether particular observed system behavior is a bug or not. On the other hand, you have full control over requirements of your particular store and you can implement relevance function satisfying your requirements, however, it does not mean such search will be suitable for all.

I bolded words in your last message which are subjective:
> what then do you think is a bug - syntax error or exception ?
i think is that is a bug, but is not related with concrete implementations. This a core bug.
In my case i **found solution** and **my store has the most accurate and fastest search**, but I do not recommend it to anyone unless it is a very experienced programmer.

> I reported this here because too many people need a **normal search** and magento2 **does not support it**, and there is no plugin to support it without sending the sensitive data to external server.

> If you not believe me, just search on google.

I'm quite concerned about the "do not recommend it to anyone unless it is a very experienced programmer". It clearly indicates your solution is not universal enough.

Also, you can post your improvement as a pull request if you define a clear metric by which search relevance became better.

**Comment by Ctucker9233** [comment]
@orlangur software is designed with an end user in mind, is it not? If it does not work as the end user expects, it can be said that the software is poorly designed. The quality is determined by the end user not necessarily the developer. Perhaps this subject would be better suited for the improvements forum instead of simply being closed and ignored. This is a huge stumbling block for our  company as well and we are very close to abandoning magento all together.
