### ISSUE TITLE
NO sender in email header for magento 2 sales order and password change emails to customer

### ISSUE THREAD

**Issue by msawyers** [magento/magento2#23199]
**Preconditions**
Magento 2.3.1
PHP 7.2.7

**Steps to reproduce**
Production Mode
Single Store Mode
Add product to cart
Checkout
View email in Live/hotmail account

**Expected result**
Order confirmation email with FROM name and email address sent to the customer per settings from store email addresses in config

**Actual result**
Order confirmation email contains no FROM or FROM EMAIL address
On email app sender shown as **=?utf-8?QStorename?=**

**Comment by msawyers** [comment]
Yes, this is replicable in the vanilla instance. see attached.

![email issue](https://user-images.githubusercontent.com/8907629/59621840-ba63ca00-90f5-11e9-9f16-453e8bfc4de1.PNG)

**Comment by msawyers** [comment]
Yes, this is replicable on a vanilla instance

![email issue](https://user-images.githubusercontent.com/8907629/59621926-eb43ff00-90f5-11e9-9226-2b911f76b300.PNG)

**Comment by oviliz** [comment]
This is likely the result of a recent fix (?) as per https://github.com/magento/magento2/issues/14952 after a too long struggle...

**Comment by msawyers** [comment]
The issue only exist on 2.3.1 can be replicated on vanilla instance

**Comment by msawyers** [comment]
Any assistance with this?

**Comment by gwharton** [comment]
If the emails are plain text then there is another bug where plain text emails are no longer sent as valid MIME emails so email clients may refuse to handle utf-8 encoding as that is only valid in MIME emails. See #22103.

**Comment by msawyers** [comment]
Yes, thats whats happening, issue still exist on Magento 2.3.2

**Comment by gwharton** [comment]
Yes. Plain text emails are currently broken in 2.2 and 2.3. Since 2.2.8 and never worked in 2.3.

**Comment by magento-engcom-team** [comment]
Hi @msawyers. Thank you for your report. 
The issue has been fixed in magento/magento2#23537 by @gwharton in 2.2-develop branch
Related commit(s):
 - [dfdbe7cc4b94c103ab66383577e13b91de395dff](https://github.com/magento/magento2/commit/dfdbe7cc4b94c103ab66383577e13b91de395dff)
 - [e6fbf99d409eb77e86266e008ff23db9276f3fb2](https://github.com/magento/magento2/commit/e6fbf99d409eb77e86266e008ff23db9276f3fb2)
 - [235cabaa912aba3ba3b5f0b96ef6ab0105859c27](https://github.com/magento/magento2/commit/235cabaa912aba3ba3b5f0b96ef6ab0105859c27)

The fix will be available with the upcoming 2.2.10 release.

**Comment by msawyers** [comment]
Awesome, thanks @gwharton

**Comment by magento-engcom-team** [comment]
Hi @msawyers. Thank you for your report. 
The issue has been fixed in magento/magento2#23535 by @gwharton in 2.3-develop branch
Related commit(s):
 - [fa030f284662ea698ea149b1b5de50cc9ea10e68](https://github.com/magento/magento2/commit/fa030f284662ea698ea149b1b5de50cc9ea10e68)
 - [7e3bc7154913af3c53b955a14c1f8f7dc78e7cfd](https://github.com/magento/magento2/commit/7e3bc7154913af3c53b955a14c1f8f7dc78e7cfd)
 - [b3e1aedd6dc63141411e5cbc67fe6b8169aa98cb](https://github.com/magento/magento2/commit/b3e1aedd6dc63141411e5cbc67fe6b8169aa98cb)

The fix will be available with the upcoming 2.3.3 release.
