### ISSUE TITLE
Static content deploy showing percentage(%) two times in progress bar

### ISSUE THREAD

**Issue by amitvishvakarma** [magento/magento2#23213]
### Preconditions (*)

1. Magento version -> 2.2.x / 2.3.x

### Steps to reproduce (*)

1. Run static deploy command -> php bin/magento setup:static-content:deploy -f

### Expected result (*)

1. Only one percentage(%) sign must be shown in progress bar.

### Actual result (*)

1.See screenshot
 ![Screenshot](https://user-images.githubusercontent.com/25526499/59307152-7e76d200-8cbb-11e9-9dba-412044a7cecb.png)
2. Percentage(%) sign is showing two times in progress bar.

**Comment by magento-engcom-team** [comment]
Hi @amitvishvakarma. Thank you for your report. 
The issue has been fixed in magento/magento2#23216 by @amitvishvakarma in 2.3-develop branch
Related commit(s):
 - [559555c7d7d13fdbcf13738f522e9e72a4bc5e8f](https://github.com/magento/magento2/commit/559555c7d7d13fdbcf13738f522e9e72a4bc5e8f)

The fix will be available with the upcoming 2.3.3 release.
