### ISSUE TITLE
Alert widget doesn't trigger always method on showing the message

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#23233]
### Preconditions (*)
1. Magento 2.3-develop
2.

### Steps to reproduce (*)
1. Create a new `alert` widget on frontend. The following simple code can be used:
```js
require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($, alert) {
        'use strict';

        alert({
            title: 'Alert Title',
            content: 'content',
            modalClass: 'alert',
            actions: {
                always: function() {
                    console.log('always triggering');
                }
            }
        });
    });
```

2. Click **OK** button

### Expected result (*)

1. You should be seeing `always triggering` text logged on opening and right after clicking the **OK** button

### Actual result (*)

1. The `always triggering` text is logged twice right after clicking the **OK** button

### Additional information
The fix proposed in https://github.com/magento/magento2/pull/23234 was reverted.
The solution was created an additional critical issue with payments on checkout
Please see more details in this https://github.com/magento/security-package/issues/207#issuecomment-614720433

> ...
> ` this.options.actions.always();`  must be called after the user click on "Ok" button (not before)
> So this line should be inside Magento_Ui/js/modal/confirm::closeModal() like it is in parent JS component  https://github.com/magento/magento2ce/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/modal/confirm.js#L97

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17454`, `MC-17455` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
@magento give me instance 2.26

**Comment by sunilit42** [comment]
@magento give me instance 2.2.6

**Comment by amol2jcommerce** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [Magento instance](https://i-23233-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23233-2-3-develop.instances.magento-community.engineering/admin](https://i-23233-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#23234 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [0c402aedc254ca85864008f54d5d4b2545b605d0](https://github.com/magento/magento2/commit/0c402aedc254ca85864008f54d5d4b2545b605d0)
 - [10c89f7cab704d239ad666a01d0538bcfdfd812f](https://github.com/magento/magento2/commit/10c89f7cab704d239ad666a01d0538bcfdfd812f)
 - [07590d9ed581b4f760bdd66135d5ca2a93704cf4](https://github.com/magento/magento2/commit/07590d9ed581b4f760bdd66135d5ca2a93704cf4)
 - [92adfeb2ebf9e2d27dc715ef4dcad8deddd2a4ad](https://github.com/magento/magento2/commit/92adfeb2ebf9e2d27dc715ef4dcad8deddd2a4ad)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#23579 by @eduard13 in 2.2-develop branch
Related commit(s):
 - [ecfaea17beafdfbd77f831cee29a819cad6c98ef](https://github.com/magento/magento2/commit/ecfaea17beafdfbd77f831cee29a819cad6c98ef)
 - [371755171cde37b2ef96f3b24758e427c0b93893](https://github.com/magento/magento2/commit/371755171cde37b2ef96f3b24758e427c0b93893)
 - [18a3f7021c2a35cc353c5d2e142420fa6d57cc79](https://github.com/magento/magento2/commit/18a3f7021c2a35cc353c5d2e142420fa6d57cc79)
 - [fc35128073722d72670262ba7aeffb1e63d09704](https://github.com/magento/magento2/commit/fc35128073722d72670262ba7aeffb1e63d09704)

The fix will be available with the upcoming 2.2.10 release.

**Comment by slavvka** [comment]
https://github.com/magento/magento2/pull/23579 has been reverted

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @slavvka 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33532` were created

**Issue Available**: @slavvka, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
