### ISSUE TITLE
Apply coupon button act like remove coupon while create new order from admin

### ISSUE THREAD

**Issue by renard123** [magento/magento2#23238]
Apply button act like remove button while create new order from admin

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Go to Admin -> Create New Order 
3. Select customer and add product
4. Apply valid coupon
5. Now click apply button again

### Expected result (*)
Coupon should not be removed.

### Actual result (*)
![apply button issue](https://user-images.githubusercontent.com/50658701/59430556-301f1b80-8e00-11e9-9404-7db0df5d5116.jpg)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23238-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23238-2-3-develop.instances.magento-community.engineering/admin](https://i-23238-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23238-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23238-2-2-develop.instances.magento-community.engineering/admin](https://i-23238-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17467`, `MC-17468` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#23250 by @gauravagarwal1001 in 2.3-develop branch
Related commit(s):
 - [6f5fc6e747722d9549edc92da6e57c3301961af2](https://github.com/magento/magento2/commit/6f5fc6e747722d9549edc92da6e57c3301961af2)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#23332 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [a9406b5da9f0e9315b161be358205075a42a12bd](https://github.com/magento/magento2/commit/a9406b5da9f0e9315b161be358205075a42a12bd)
 - [aa497280c88608e5a969558db0ef4d421413f49c](https://github.com/magento/magento2/commit/aa497280c88608e5a969558db0ef4d421413f49c)
 - [2ca4dbe918edcb55020847086e29432b48f506b3](https://github.com/magento/magento2/commit/2ca4dbe918edcb55020847086e29432b48f506b3)

The fix will be available with the upcoming 2.2.10 release.
