### ISSUE TITLE
Integration test for unsubscribing from 'Back in stock notification'

### ISSUE THREAD

**Issue by yuriichayka** [magento/magento2#23279]
### Summary (*)

The functionality should be covered by tests so issues like #22814 won't occur in future.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18587` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @yuriichayka. Thank you for your report. 
The issue has been fixed in magento/magento2#24291 by @yuriichayka in 2.3-develop branch
Related commit(s):
 - [b089cc2088fc68a8424561b3585d5ff49d0d020b](https://github.com/magento/magento2/commit/b089cc2088fc68a8424561b3585d5ff49d0d020b)
 - [36c00d2d7f0b1992ab84ed7df961959dca76de8c](https://github.com/magento/magento2/commit/36c00d2d7f0b1992ab84ed7df961959dca76de8c)
 - [665aad5966ff70c0fdbda79786062a97128ff8d8](https://github.com/magento/magento2/commit/665aad5966ff70c0fdbda79786062a97128ff8d8)
 - [f59012798f60ac55079e2b86a55d416093bba1c9](https://github.com/magento/magento2/commit/f59012798f60ac55079e2b86a55d416093bba1c9)

The fix will be available with the upcoming 2.3.4 release.
