### ISSUE TITLE
Message isn't displayed on the error after connection reset and placing order

### ISSUE THREAD

**Issue by akovtun** [magento/magento2#23288]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2.18

### Steps to reproduce (*)

1. Open the checkout page and fill in the data
2. Turn off the Internet / Make site inaccessible.
3. Click Place Order.

### Expected result (*)

User gets the error 'Something went wrong with your request. Please try again later.'

### Actual result (*)

User gets an error without text.
![bug4](https://user-images.githubusercontent.com/2437431/59610569-560b2f80-9122-11e9-98f5-0c900aa41d26.png)

### Possible reason
File: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Checkout/view/frontend/web/js/model/error-processor.js
If there is no response from the server, then response.responseText contains an empty string.
The code from the catch section is executed and the error variable will contain a string.
![bug1](https://user-images.githubusercontent.com/2437431/59610784-c1550180-9122-11e9-8cf2-4ef4f3c05cec.png)

But the addErrorMessage function expects an object with the text in the field 'message'
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Ui/view/frontend/web/js/model/messages.js
![bug2](https://user-images.githubusercontent.com/2437431/59610919-0aa55100-9123-11e9-96d5-6230ae83bb68.png)
![bug3](https://user-images.githubusercontent.com/2437431/59610921-0c6f1480-9123-11e9-8e40-d9168a46045d.png)

To fix this error, you need to change the line 32 in the error-processor.js file
`error = $t('Something went wrong with your request. Please try again later.');`
on
`error = {message: $t('Something went wrong with your request. Please try again later.')};`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17754`, `MC-17755` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @akovtun, @gauravagarwal1001. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [1f86c1256e433c6f614f9444ec1cc29ea3a569d1](https://github.com/magento/magento2/commit/1f86c1256e433c6f614f9444ec1cc29ea3a569d1)
 - [d87af0cbf0c395e1df2acc2142176b4659ad3bc3](https://github.com/magento/magento2/commit/d87af0cbf0c395e1df2acc2142176b4659ad3bc3)
 - [61c4328df9b62a156dce88e90aa265e910f1f1f3](https://github.com/magento/magento2/commit/61c4328df9b62a156dce88e90aa265e910f1f1f3)

The fix will be available with the upcoming `2.3.3` release.
