### ISSUE TITLE
Credit memo submit button(refund) stays disable after validation fails & unable to enable button

### ISSUE THREAD

**Issue by nishantjariwala** [magento/magento2#23285]
Hi,
Here I've found an issue while creating a credit memo. In credit memo, If your entered wrong value and once submit button(refund) will become disabled then unable to enable it.
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. From the Sales order click on credit memo.
2. Credit memo window will be opened.
3. Go to **Refund Shipping** in **Refund Totals** section. Here, enter a negative value and click on refund button.
4. https://prnt.sc/o2vqsu

### Expected result (*)

1. Now, the refund button should be enabled if I correct the value like following screenshot.
2. https://prnt.sc/o2vuft

### Actual result (*)

1. But, the refund button stays disabled although I correct the value and I am unable to refund.
2. https://prnt.sc/o2vt2c

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23285-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23285-2-3-develop.instances.magento-community.engineering/admin](https://i-23285-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23285-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23285-2-2-develop.instances.magento-community.engineering/admin](https://i-23285-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17529`, `MC-17530` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @nishantjariwala. Thank you for your report. 
The issue has been fixed in magento/magento2#23286 by @nishantjariwala in 2.3-develop branch
Related commit(s):
 - [248594043e9e2ed2b72c3cb78a0cafc27dcc69c7](https://github.com/magento/magento2/commit/248594043e9e2ed2b72c3cb78a0cafc27dcc69c7)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @nishantjariwala. Thank you for your report. 
The issue has been fixed in magento/magento2#23566 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [e1d04914dd26b22040b7ee53ff5f16d950e0c7fe](https://github.com/magento/magento2/commit/e1d04914dd26b22040b7ee53ff5f16d950e0c7fe)

The fix will be available with the upcoming 2.2.10 release.
