### ISSUE TITLE
Advanced Pricing Issue

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#23299]
### Preconditions (*)
1. Magento 2.3.1
2. php 7.1
3- Varnish Cahce
4- Redis

### Steps to reproduce (*)
1. Create a Product with Special Price that has expiration date
2. After the Special Price Expiration date, the products still show discount price
3- when processed in cart and place order, the price changes to the original price
Screenshuts: https://drive.google.com/drive/u/0/folders/1T-yxrAJCHUOIYJaEphHV_jD3iJJeLdPR 

### Expected result (*)

1. price in front end ( site and mobile ) are different from calculated price in order details

### Actual result (*)
1. if special price is expired, the price should change to normal price immediately

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23299-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23299-2-3-develop.instances.magento-community.engineering/admin](https://i-23299-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-23299-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23299-2-2-develop.instances.magento-community.engineering/admin](https://i-23299-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@salehawal - I have verified this issue Magneto 2.2 and Magneto 2.3 Instance with your test scenario. In Magento Instance I can't find the pricing issue. it's working fine.
See attached the Magento 2.2 and Magento 2.3 Instance screenshot:

![2 2_Advance Price](https://user-images.githubusercontent.com/24711761/59680392-d6976200-91ee-11e9-8049-caba6a7f58ec.png)

![2 2_Checkout_Main Price](https://user-images.githubusercontent.com/24711761/59680393-d72ff880-91ee-11e9-9abd-6c9963986edd.png)

![2 2_Details_Main Price](https://user-images.githubusercontent.com/24711761/59680394-d72ff880-91ee-11e9-9e4d-c387c6a24227.png)

![2 2_Listing_Main Price](https://user-images.githubusercontent.com/24711761/59680396-d72ff880-91ee-11e9-92c1-52c70e087eac.png)

![2 2_Order detail](https://user-images.githubusercontent.com/24711761/59680397-d7c88f00-91ee-11e9-8c1e-94f1a5f6ecff.png)

![2 2_Order detail_DiscountPrice](https://user-images.githubusercontent.com/24711761/59680398-d7c88f00-91ee-11e9-987a-f509f81476c9.png)

![2 3 Details Page_Discount Price](https://user-images.githubusercontent.com/24711761/59680412-e151f700-91ee-11e9-9fb5-82619284af60.png)

![2 3 Details Page_Main Price](https://user-images.githubusercontent.com/24711761/59680413-e1ea8d80-91ee-11e9-87d7-d2f3874d15e4.png)

![2 3_Checkout_DiscountPrice](https://user-images.githubusercontent.com/24711761/59680414-e1ea8d80-91ee-11e9-8363-bdc781ac097d.png)

![2 3_Checkout_MainPrice](https://user-images.githubusercontent.com/24711761/59680415-e2832400-91ee-11e9-9327-16f9c386d6d1.png)

@salehawal - This issue is related to your custom module or varnish cache. Please check it in your end this issue and update me.

@salehawal  - This does not default Magento issue so now I am closing this issue. If you have detected the issue in Magento instance you can reopen the issue again.

**Comment by salehawal** [comment]
ok thanks .. then it must be Varnish Cache .. can you confirm that API is included in the caching system of magento

**Comment by ajijshekh123** [comment]
@salehawal - API is not included in the caching system of Magento.

**Comment by salehawal** [comment]
we are experiencing this issue also in our apps, so if API is not included in Cache then dose that confirm that it is no a Varnish issue? might be a module or miss-configuration issue ?

**Comment by ajijshekh123** [comment]
Yes @salehawal, Issue may be any custom module Or related to the configuration.
