### ISSUE TITLE
./bin/magento config:show returns "Configuration for path: '...' doesn't exist" if config value equals to 0 or empty string

### ISSUE THREAD

**Issue by OleksiiBulba** [magento/magento2#23290]
### Preconditions (*)
1. Magento 2.4-develop
2. Create module `Vendor_Module`
3. Create `etc/config.xml` in created module `Vendor_Module` with new config path `default/vendor_module/general/value` with value `0` or `''` (empty string)

### Steps to reproduce (*)
1. Open magento cli and run command `./bin/magento config:show vendor_module/general/value`

### Expected result (*)
1. Should return `0` or `''` (empty string)

### Actual result (*)
1. Command returns `Configuration for path: "vendor_module/general/value" doesn't exist`

I think it happens because there `<magento_root>/vendor/magento/module-config/Console/Command/ConfigShowCommand.php:153` magento checks if value is empty and if it actualy is the error message is shown. But empty value does not mean that path does not exist. So we should check if path exist in different method.

**Comment by milindsingh** [comment]
@OleksiiBulba 
Its correct that it renders **Configuration for path: "vendor_module/general/value" doesn't exist**
But what should it render on empty value? Maybe an empty value error?

**Comment by OleksiiBulba** [comment]
Hi @milindsingh
It is confusing when you try to get value from path but you got "path does not exist". I think at least the message should not say "does not exist" because it does exist but has empty value

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17959`, `MC-17960` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-23290-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23290-2-3-develop.instances.magento-community.engineering/admin](https://i-23290-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-23290-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-23290-2-3-1.instances.magento-community.engineering/admin](https://i-23290-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
#mleu2019

**Comment by shikhamis11** [comment]
@magento I am working on this issue

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35564` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @OleksiiBulba. Thank you for your report. 
The issue has been fixed in magento/magento2#28549 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [3bff44623ad2694a203a0ae11018680bd7598a1f](https://github.com/magento/magento2/commit/3bff44623ad2694a203a0ae11018680bd7598a1f)
 - [a6049d55f20ffa75f25312b4e07554d8dd9616b1](https://github.com/magento/magento2/commit/a6049d55f20ffa75f25312b4e07554d8dd9616b1)
 - [70809f9eaae4a0ad129cbdf929ee39039ee3e9bd](https://github.com/magento/magento2/commit/70809f9eaae4a0ad129cbdf929ee39039ee3e9bd)
 - [655f5aba0c76529f013cde6a839a50b3ac466cc7](https://github.com/magento/magento2/commit/655f5aba0c76529f013cde6a839a50b3ac466cc7)
 - [36ff6d71e0ccb383022e33d58989ee461ea563e9](https://github.com/magento/magento2/commit/36ff6d71e0ccb383022e33d58989ee461ea563e9)
 - [0ac7e12d66e89362aca0b030e613947f2c13085c](https://github.com/magento/magento2/commit/0ac7e12d66e89362aca0b030e613947f2c13085c)

The fix will be available with the upcoming 2.4.1 release.
