### ISSUE TITLE
MethodArgumentsSniff works incorrect with arguments passed by reference.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/magento2#23301]
### Preconditions (*)

1. Magento 2 code.

### Steps to reproduce (*)

1. Add any changes to \Magento\CatalogImportExport\Model\Import\Product\Option class.
2. Run \Magento\Test\Php\LiveCodeTest::testCodeStyle method.

### Expected result (*)

1. No errors related to _isReadyForSaving method annotations.

### Actual result (*)

1. "Method arguments visual alignment must be consistent" error occurred.

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23301-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23301-2-3-develop.instances.magento-community.engineering/admin](https://i-23301-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@p-bystritsky according to the https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types definition ampersand should be used for intersection type. For variables passed by reference, such docblock is invalid. DocBlock should be fixed instead of code sniff. I'm closing this bug as not relevant.
