### ISSUE TITLE
Incorrect payment method translation in order emails

### ISSUE THREAD

**Issue by arendarenko** [magento/magento2#23333]
### Preconditions (*)

1. Magento 2.2.8
2. Default sales email templates is used

### Steps to reproduce (*)

1. Create website with different locale than en_US (for example: fr_FR)
2. Enable "Check / Money" order payment method for French website and translate it in into "Chèque / Argent"
3. Flush cache
4. Create new order in French store view
5. Create shipment for it and set checkbox "Email Copy of Shipment" checked
6. Create credit memo for it and set checkbox "Email Copy of Credit Memo" checked

### Expected result (*)

1. Customer will receive shipment and credit memo emails where in Payment Method area will be "Chèque / Argent", like it was in New order email

### Actual result (*)

1. Customer receiving shipment and credit memo emails with "Check / Money" in Payment Method area

**Comment by engcom-Bravo** [comment]
Hello @alexeya-ven. Would You please tell us what exactly You did in order to get "Check / Money Order" translated to "Chèque / Argent". Thank You.

**Comment by engcom-Bravo** [comment]
@alexeya-ven You did it via Configuration right?

**Comment by engcom-Bravo** [comment]
Also @alexeya-ven, it is most likely You mean You were creating those shipments and credit memos wile the default site was not that one with fr_FR locale. Please tell us is it so or not, as in Your Steps to Reproduce all of these things are not reflected or are called somewhat incorrectly (for example to change the name of the payment method in the Configuration for a particular website or store view is usually referred to as set another name but not to as translate). If everything is just as we think we can confirm the issue, but if it's not, then we are not able to reproduce it and so will need Your help in order to obtain the reproduction and to be able to confirm the issue.

**Comment by arendarenko** [comment]
Hi @engcom-Bravo 
The issue is happens when you have two websites with different locales - en_US (which is default) and fr_FR, and creating credit memo / shipment / invoice in orders which is placed in fr_FR website. In this cases Magento didn't emulate order store view, but uses default. Thats why payment method block in order email didn't translates correctly.

**Comment by engcom-Bravo** [comment]
Thank You @alexeya-ven for Your reply. Then it seems everything is just as we think. But could You please confirm that You made the name of "Check / Money" look like "Chèque / Argent" in the following way:
![ChMO](https://user-images.githubusercontent.com/51680745/60017570-b570be80-9691-11e9-8629-e83bd2708ce0.png)
Thank You.

**Comment by arendarenko** [comment]
@engcom-Bravo yes, we're talking about exactly the same case.

**Comment by engcom-Bravo** [comment]
Making different locales for different sites are redundant.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17759`, `MC-17760` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @alexeya-ven. Thank you for your report. 
The issue has been fixed in magento/magento2#23338 by @alexeya-ven in 2.3-develop branch
Related commit(s):
 - [292fa21391f15055480542f22d3588641ba5f069](https://github.com/magento/magento2/commit/292fa21391f15055480542f22d3588641ba5f069)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @alexeya-ven. Thank you for your report. 
The issue has been fixed in magento/magento2#23438 by @ihor-sviziev in 2.2-develop branch
Related commit(s):
 - [171c9ce069904263803d5b60d68efa82d7269820](https://github.com/magento/magento2/commit/171c9ce069904263803d5b60d68efa82d7269820)

The fix will be available with the upcoming 2.2.10 release.
