### ISSUE TITLE
Creditmemo getOrder() method loads order incorrectly

### ISSUE THREAD

**Issue by pavdan** [magento/magento2#23345]
### Preconditions (*)

1. Magento 2.3.1
2. `\Magento\Sales\Model\Order\Creditmemo::getOrder` method uses deprecated functionality. It results in wrong order state. For example, $order->getExtensionAttributes() return incorrectly filled data (some attribute values are missing)
3. Need order with creditmemo to reproduce (create any)

### Steps to reproduce (*)

1. Load creditmemo by `Magento\Sales\Api\CreditmemoRepositoryInterface`
2. Get order: $order = $creditmemo->getOrder();
3. Get extension attributes: $extension = $order->getExtensionAttributes();

### Expected result (*)

1. $extension contains all extension attributes

### Actual result (*)

1. $extension contains no data

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17684` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @pavdan. Thank you for your report. 
The issue has been fixed in magento/magento2#23358 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [14212b18de12eed264a452da8907eb953474505e](https://github.com/magento/magento2/commit/14212b18de12eed264a452da8907eb953474505e)

The fix will be available with the upcoming 2.3.3 release.
