### ISSUE TITLE
Data saving problem error showing when leave blank qty and update it

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#23354]
Data saving problem error showing when leave blank qty and update it

### Preconditions (*)
Magento 2.3

### Steps to reproduce (*)
1) Front end -> Login into account
2) Add more than 2 products to the cart
3) From cart go to checkout with multiple addresses
4) Qty leave blank and click on Update Qty & Addresses

### Expected result (*)
Appropriate error message should display.

### Actual result (*)
![error data shaving](https://user-images.githubusercontent.com/49804008/59916174-1606be00-943c-11e9-84df-bc10a45346a6.jpg)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23354-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23354-2-3-develop.instances.magento-community.engineering/admin](https://i-23354-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-23354-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23354-2-2-develop.instances.magento-community.engineering/admin](https://i-23354-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17681`, `MC-17682` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#23360 by @konarshankar07 in 2.3-develop branch
Related commit(s):
 - [471fd852fe8ddbd489f9a77aecbbc37e8a15f1cd](https://github.com/magento/magento2/commit/471fd852fe8ddbd489f9a77aecbbc37e8a15f1cd)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#23612 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [90be3ce44c9b36add9da6adbffe59eeb8a3c6e17](https://github.com/magento/magento2/commit/90be3ce44c9b36add9da6adbffe59eeb8a3c6e17)

The fix will be available with the upcoming 2.2.10 release.
