### ISSUE TITLE
Paypal orders - billing address displaying incorrect format in admin side

### ISSUE THREAD

**Issue by hackronshins** [magento/magento2#23374]
Hi team, We upgraded from 2.3.0 to 2.3.1, when we placed an order using paypal payment method that particular orders billing address displaying incorrect format or template prefix variables and curly braces.

### Preconditions (*)
1. Magento CE 2.3.1
2. Simple product ordered
3. Using Paypal payment method (card payment)
4. Billing address in paypal orders (Note down the order id and check in admin end)

### Steps to reproduce (*)
1. Add product to the cart
2. Proceed to checkout
3. Using Paypal express payment method
4. Place the order
5. Lets check in backend in admin
6. Open Sales -> Orders
7. Note down the order id and open with order in admin end
8. See the billing address

### Expected result (*)

1. We should see the address as shipping address. No need to see prefix variables and curly braces etc...

### Actual result (*)
![14](https://user-images.githubusercontent.com/23425297/60014650-1e126800-969f-11e9-8ec7-24697be84a96.PNG)

Please help me on this, we are expecting a solution for this, If you already have any patch please let us know

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23374-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23374-2-3-develop.instances.magento-community.engineering/admin](https://i-23374-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Hello @hackronshins. We've been not able to reproduce Your issue on a clear Magento installation:
![BillingAddres](https://user-images.githubusercontent.com/51680745/60027759-b8c27500-96a6-11e9-8bdd-83d9915e016c.png)
Could You please try to do the same - to reproduce it on theMagento's  vanilla instance of the latest develop version and tell us wether You'll have a success. Thank You.

**Comment by hackronshins** [comment]
Okay sure, I will check and update you.

**Comment by hackronshins** [comment]
My environment is upgrade version from 2.3.0 to 2.3.1, Can you give a try on this upgrade from 2.3.0 to 2.3.1 and try to reproduce using paypal. and also try on virtual products. Please confirm me if anything required

**Comment by engcom-Bravo** [comment]
Hi again @hackronshins. We've done what You asked us to do and we have got no bug again. We installed a vanilla instance of 2.3.0
![230](https://user-images.githubusercontent.com/51680745/60216631-3804a400-9873-11e9-9907-d96a13dc79d0.png)
Created a Simple and a Virtual products there and upgraded it to 2.3.1
![upgraded](https://user-images.githubusercontent.com/51680745/60216676-5ff40780-9873-11e9-99ce-307d7691de5f.png)
Then we created two orders: one with the simple product and the other one with the virtual product. The addresses are Ok as You can see:
![Simp](https://user-images.githubusercontent.com/51680745/60216773-96318700-9873-11e9-9537-9befe9dfbf38.png)
![Virt](https://user-images.githubusercontent.com/51680745/60216780-9e89c200-9873-11e9-8637-d0349e8722e8.png)
It is most probably that Your issue is caused by some third party extentions or any kind of other not native code. Currently we are supposed to close Your issue. Please feel free to reopen it if You  find the way to reproduce it on a vanilla (clear of any non-native code) Magento instance. Thank Your for applying.
