### ISSUE TITLE
Category A image replaced by uploading to Category B

### ISSUE THREAD

**Issue by stephan-cream** [magento/magento2#23376]
### Preconditions (*)
1. Magento version: 2.3.*
2. PHP version: Any
3. SQL version: Any

### Steps to reproduce (*)
1. Add an image with the name 'test.jpg' to Category A
2. Check the image (should be uploaded properly).
3. Add a different image with the same name 'test.jpg' to Category B.
4. Check the image (should be uploaded properly).
5. Go back to check the image of Category A (image replaced by image uploaded to Category B).

### Expected result (*)
1. The image for Category A is what is uploaded for Category A.
2. The image for Category B is what is uploaded for Category B.

### Actual result (*)
1. The image for Category A is what is uploaded for Category B (basically it's replaced).
2. The image for Category B is what is uploaded for Category B.

This is caused because there is no category identifier differentiation.
Everything is saved directly under /media/catalog/category/.
In this example, when checking the URL of the image on both categories it was:
/media/catalog/category/test.jpg

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17764`, `MC-17765` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sanjay-github** [comment]
@engcom-Bravo : I am working on this issue.

**Comment by magento-engcom-team** [comment]
Hi @stephan-cream, @sanjay-github. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.2-develop` branch(es).
Related commit(s):
 - [0f44fbd5bb123c78d6b84355ace79ecf896ad212](https://github.com/magento/magento2/commit/0f44fbd5bb123c78d6b84355ace79ecf896ad212)
 - [706b8f8f980078c1d19592e3103e38eaefd6bafc](https://github.com/magento/magento2/commit/706b8f8f980078c1d19592e3103e38eaefd6bafc)
 - [0cc141c40a413d6daa34b8f2717464d75881ce7b](https://github.com/magento/magento2/commit/0cc141c40a413d6daa34b8f2717464d75881ce7b)
 - [e2db69de42d0e79ae832e2be994a1377c9ca682c](https://github.com/magento/magento2/commit/e2db69de42d0e79ae832e2be994a1377c9ca682c)

The fix will be available with the upcoming `2.2.10` release.

**Comment by magento-engcom-team** [comment]
Hi @stephan-cream, @sanjay-github. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [e83fc73cbff9ffb5ed5726632097fbacdc419b34](https://github.com/magento/magento2/commit/e83fc73cbff9ffb5ed5726632097fbacdc419b34)
 - [5a5a24667af26979eeaa273e2d3119355bc9cdce](https://github.com/magento/magento2/commit/5a5a24667af26979eeaa273e2d3119355bc9cdce)
 - [eefb665d53364d04f0c6ee46105bbb783f925231](https://github.com/magento/magento2/commit/eefb665d53364d04f0c6ee46105bbb783f925231)
 - [8cfdffdca145cb34db85045030e5a654a65dabc5](https://github.com/magento/magento2/commit/8cfdffdca145cb34db85045030e5a654a65dabc5)
 - [573798c6f0b5f1eb5cb9e3868cf05b25b639fbf7](https://github.com/magento/magento2/commit/573798c6f0b5f1eb5cb9e3868cf05b25b639fbf7)
 - [666e95bb2ebe18bec1fdf5ef3a89a3fb338ca008](https://github.com/magento/magento2/commit/666e95bb2ebe18bec1fdf5ef3a89a3fb338ca008)
 - [c5b32c8729ea2f6f355184e7a46ded6bc8cc570c](https://github.com/magento/magento2/commit/c5b32c8729ea2f6f355184e7a46ded6bc8cc570c)
 - [2f8764a0979c1b8f784e7373e9cdc4fefb2114f3](https://github.com/magento/magento2/commit/2f8764a0979c1b8f784e7373e9cdc4fefb2114f3)

The fix will be available with the upcoming `2.3.3` release.

**Comment by aarondurban** [comment]
we've updated to 2.3.3 and it now attempts to save the category image again after every save.  In doing so, if any information is changed (ie description) the image is removed as a new one is not added.

**Comment by marketing2** [comment]
> we've updated to 2.3.3 and it now attempts to save the category image again after every save. In doing so, if any information is changed (ie description) the image is removed as a new one is not added.

Yes, we are having the same!
