### ISSUE TITLE
Mini cart loader not working first time magento2

### ISSUE THREAD

**Issue by iamckdev** [magento/magento2#23377]
### Preconditions (*)

1. Magento Version 2.3.1

### Steps to reproduce (*)

1. Clear browser cache and open website when click on add to cart see on the mini cart.
2. First time mini cart loader not showing, click second time then loader will be visible.

### Expected result (*)

1. Should always will be visible when you add to cart product.

### Actual result (*)

1. Refer the video.

Video: https://drive.google.com/file/d/1AlfqCl64VmgoKaQISRAI1WWw-CmZbIPt/view

**Comment by engcom-Charlie** [comment]
Hello @iamckindia ! Thank you for your report !
Seems like i need special permission to check video you linked.

**Comment by iamck07** [comment]
Please find the updated link: https://drive.google.com/file/d/1AlfqCl64VmgoKaQISRAI1WWw-CmZbIPt/view?usp=sharing

**Comment by magento-engcom-team** [comment]
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17762`, `MC-17763` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @iamckindia. Thank you for your report. 
The issue has been fixed in magento/magento2#23394 by @geet07 in 2.3-develop branch
Related commit(s):
 - [3d6b783324abb7415206fe66402d0bdcb44f8fbd](https://github.com/magento/magento2/commit/3d6b783324abb7415206fe66402d0bdcb44f8fbd)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @iamckindia. Thank you for your report. 
The issue has been fixed in magento/magento2#23536 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [6874f6158e17902809b91659783c597864d2ec16](https://github.com/magento/magento2/commit/6874f6158e17902809b91659783c597864d2ec16)

The fix will be available with the upcoming 2.2.10 release.
