### ISSUE TITLE
Magento Calculate Handling Fee with Percent Value does not work.

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#23385]
### Preconditions (*)
1. Magento 2.3.1 with sample data

### Steps to reproduce (*)
1. Configure Flat Rate > Custom Handling Fee  with Percent Value
2. Enter percentage in Flat Rate > Handling Fee as instructed in the user guide

### Expected result (*)
1. A Custom Handling Fee as percentage of something (either the product price or the the shipping fee itself, the docs do not state a percentage of what, it just says a percentage) is applied.

### Actual result (*)

1. A fixed Custom Handing Fee amount is applied 

![FlatRateUserGuide](https://user-images.githubusercontent.com/25669334/60035815-66895000-96b6-11e9-9cf2-973b37e917be.png)
![FlateRateConfigAdmin](https://user-images.githubusercontent.com/25669334/60035824-69844080-96b6-11e9-9c33-0755b92bb250.png)
![FlateRateCheckout](https://user-images.githubusercontent.com/25669334/60035831-6be69a80-96b6-11e9-9e4e-2f4b4475adb9.png)

**Comment by victortodoran** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @victortodoran. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @victortodoran, here is your [Magento instance](https://i-23385-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23385-2-3-develop.instances.magento-community.engineering/admin](https://i-23385-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by victortodoran** [comment]
@magento yes

![DevelopAdmin](https://user-images.githubusercontent.com/25669334/60036418-dea44580-96b7-11e9-8256-415c5d7016e1.png)
![DevelopCart](https://user-images.githubusercontent.com/25669334/60036419-e06e0900-96b7-11e9-976c-2fd8ea3c29b6.png)
![DevelopCheckout](https://user-images.githubusercontent.com/25669334/60036429-e4019000-96b7-11e9-93e3-bcbb5b629296.png)

**Comment by engcom-Bravo** [comment]
Hello @victortodoran. Thanks for applying. The essence of this issue lies in the very [docs](https://docs.magento.com/m2/ce/user_guide/shipping/shipping-flat-rate.html) You most likely used. In fact this part
![Incorrect](https://user-images.githubusercontent.com/51680745/60094305-6049b100-9754-11e9-9a11-ecfedd433f13.png)
is incorrect and simply redundant. [Here](https://www.mageplaza.com/kb/how-to-configure-flat-rate-shipping-method-magento-2.html), for example the instruction on Handling Fee is correct. All You need is to write in a needed decimal number in Handling Fee field which due to the value set for Calculate Handling Fee option is interpreted ether as a fixed amount or as percentage from the shipping costs. You thing Percent Value does not work because of the numbers You has chosen for an example: Price is 100 and Handling Fee is 0.10. In this case 0.10% calculated on 100$ is equal to 0.10$. So it's no matter what You set for Calculate Handling Fee - Percent or Fixed - the output  for Handling Fee of 0.10 will be the same 100.10$.

**Comment by victortodoran** [comment]
Hi. Yes you are correct. 
Found it in Shipping/AbstractCarrier::_getPrepackagePrice(), forgot to update the issue.

**Comment by engcom-Bravo** [comment]
@victortodoran we are glad for the mutual understanding on this issue reached between us. So with that let us close the issue.
