### ISSUE TITLE
Copy Service does not works properly for Entities which extends Data Object and implements ExtensibleDataInterface

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#23386]
### Summary (*)
There is no way to use Extension Attributes in Copy Service if you are using entity class which extends DataObject

### Examples (*)
https://github.com/magento/magento2/blob/1e58f70fc0474d66e052c92f849baa9c390599e9/lib/internal/Magento/Framework/Model/AbstractModel.php#L18

1. Create Extension Attribute for Quote Address.
2. Create Extension Attribute for Order.
3. Try to copy Extension Attribute from Quote Address to Order Extension Attribute with \Magento\Framework\DataObject\Copy.

Detected in [magento/inventory#2309](https://github.com/magento/inventory/pull/2309)

### Proposed solution
Change fallback from:

Array -> DataObject -> ExtensibleDataInterface -> AbstractSimpleObject
to
Array -> ExtensibleDataInterface -> DataObject -> AbstractSimpleObject

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your report. 
The issue has been fixed in magento/magento2#23387 by @swnsma in 2.3-develop branch
Related commit(s):
 - [9852b08e18f1128a081fd2b366e75e15355988f8](https://github.com/magento/magento2/commit/9852b08e18f1128a081fd2b366e75e15355988f8)
 - [d70edfccdb5051e46e7b78d4e432a88b2f9eb694](https://github.com/magento/magento2/commit/d70edfccdb5051e46e7b78d4e432a88b2f9eb694)
 - [661874a7ddc9e8efda797bfc7419f5fa064ed869](https://github.com/magento/magento2/commit/661874a7ddc9e8efda797bfc7419f5fa064ed869)
 - [731a4fce46a9f33ea16af7404839740efdf23371](https://github.com/magento/magento2/commit/731a4fce46a9f33ea16af7404839740efdf23371)

The fix will be available with the upcoming 2.3.3 release.
