### ISSUE TITLE
M2.2.7 : REST API V1 - PUT /V1/guest-carts/{cartId} gives 401 authorization error.

### ISSUE THREAD

**Issue by LovelySetia** [magento/magento2#23392]
I try to assign a customer to a quote using the REST API. 
This is a guest-endpoint so it should not require authentication. However, when I try to use it, the API tells me I am not allowed to do so

### Preconditions (*)

1.Magento 2.2.7

### Steps to reproduce (*)

1.Setup a quote as a guest and get it's masked ID (in this example it's Ai6z71bxdK3igp04qLBujM7RErkrhem6
2.Create a customer and get it's ID (in this example it's 10)
3.Create the API call. For example:

curl -X PUT -H "Content-Type: application/json" \
    -d '{"customerId":10}' \
    "http://www.domain.com/rest/V1/guest-carts/Ai6z71bxdK3igp04qLBujM7RErkrhem6/"

### Expected result (*)

1.A logic response from the API and the customer saved to the quote (as documented)

### Actual result (*)

1. 401 response with the following message:

{
  "message": "Consumer is not authorized to access %resources",
  "parameters": {
    "resources": "self"
  }

**Comment by LovelySetia** [comment]
@magento give me 2.2.3 instance.

**Comment by magento-engcom-team** [comment]
Hi @LovelySetia. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @LovelySetia, here is your [Magento instance](https://i-23392-2-2-3.instances.magento-community.engineering).
Admin access: [https://i-23392-2-2-3.instances.magento-community.engineering/admin](https://i-23392-2-2-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by LovelySetia** [comment]
This issue is also in Magento-2.2.3.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17778`, `MC-17779` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
Hi @LovelySetia, I don't think this is an issue.
For example:
1. Create a Guest checkout : `http://magento2-dev4.com/rest/V1/guest-carts`
2. You will receive quoteId.
3. Now if you want to assign this guest checkout to customer then you need to get the customer token first, because we want to convert quest quote to customer quote.

4. get customer token: 
`curl -X POST \
  http://magento2-dev4.com/rest/V1/integration/customer/token \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 9bdc4459-a40e-4018-905d-62f436275249' \
  -H 'cache-control: no-cache' \
  -d '{
	"username":"roni_cost@example.com",
	"password":"roni_cost3@example.com"
}`
5. Now add this token to request header and now make the assign customer request.
`
curl -X PUT \
  http://magento2-dev4.com/rest/V1/guest-carts/aWrtyeXmzPEsX49rodsM0DJaz1f01gpb \
  -H 'Authorization: Bearer qpxn9v15els2k8mr478c7kfaj9id3n3n' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 206de76e-0611-4133-9121-450bfcc7fa73' \
  -H 'cache-control: no-cache' \
  -d '{
	"customerId":1,
	"storeId": 1
}'
`
Its done no error.


@magento-engcom-team , please check my steps if i am wrong.

**Comment by LovelySetia** [comment]
If we pass customer token as authorization, it give response 400 error:
 "{"message": "Cannot assign customer to the given cart. Customer already has active cart."}".
@magento-engcom-team

**Comment by LovelySetia** [comment]
If we pass customer token as authorization, it give response 400 error:
"{"message": "Cannot assign customer to the given cart. Customer already has active cart."}" . Please guide me asap @magento-engcom-team @maheshWebkul721

**Comment by LovelySetia** [comment]
> Hi @LovelySetia, I don't think this is an issue.
> For example:
> 
> 1. Create a Guest checkout : `http://magento2-dev4.com/rest/V1/guest-carts`
> 2. You will receive quoteId.
> 3. Now if you want to assign this guest checkout to customer then you need to get the customer token first, because we want to convert quest quote to customer quote.
> 4. get customer token:
>    `curl -X POST \   http://magento2-dev4.com/rest/V1/integration/customer/token \   -H 'Content-Type: application/json' \   -H 'Postman-Token: 9bdc4459-a40e-4018-905d-62f436275249' \   -H 'cache-control: no-cache' \   -d '{ "username":"roni_cost@example.com", "password":"roni_cost3@example.com" }`
> 5. Now add this token to request header and now make the assign customer request.
>    `curl -X PUT \   http://magento2-dev4.com/rest/V1/guest-carts/aWrtyeXmzPEsX49rodsM0DJaz1f01gpb \   -H 'Authorization: Bearer qpxn9v15els2k8mr478c7kfaj9id3n3n' \   -H 'Content-Type: application/json' \   -H 'Postman-Token: 206de76e-0611-4133-9121-450bfcc7fa73' \   -H 'cache-control: no-cache' \   -d '{ "customerId":1, "storeId": 1 }'`
>    Its done no error.
> 
> @magento-engcom-team , please check my steps if i am wrong.
If we pass customer token as authorization, it give response 400 error:
"{"message": "Cannot assign customer to the given cart. Customer already has active cart."}" .

**Comment by LovelySetia** [comment]
@magento-engcom-team  Please tell me what is issue asap.

**Comment by LovelySetia** [comment]
If we pass customer token as authorization, it give response 400 error:
"{"message": "Cannot assign customer to the given cart. Customer already has active cart."}" . Please guide me asap @magento-engcom-team @maheshWebkul721

**Comment by mack4hack** [comment]
@LovelySetia I am facing the same issue on Magento CE v2.3.1

**Comment by TomashKhamlai** [comment]
The issue from the description is not an issue - it is expected behavior. When `customer_token` is not sent in the headers, then an authorization error message should occur.

The issue from comments is also not an issue - it is expected behavior. Also, it has a test-coverage:
- \Magento\Quote\Api\CartManagementTest::testAssignCustomerThrowsExceptionIfCustomerAlreadyHasActiveCart
- \Magento\Quote\Api\GuestCartManagementTest::testAssignCustomerThrowsExceptionIfCustomerAlreadyHasActiveCart

@engcom-Bravo, please check. I suggest closing this issue.

**Comment by engcom-Bravo** [comment]
@LovelySetia, I agree with @TomashKhamlai. So we are closing the issue. The 400 error You get most likely because Your customer has an active cart. You see if the Customer has no active cart and he (she) adds something to it then the cart gets active. And even if after that the Customer empties the cart it will still remain active until the first order after those cart manipulations will have been placed.
