### ISSUE TITLE
Search by keyword didn't work properly with "0" value

### ISSUE THREAD

**Issue by engcom-Golf** [magento/magento2#23424]
### Preconditions
1. Magento 2.3
2. Add 4 simple products (simple 1, simple 2, simple 0 and simple 4)
![image](https://user-images.githubusercontent.com/51681547/60183578-3dd89600-982f-11e9-90f7-440ec3f3413e.png)

3. set 2 products per page

### Steps to reproduce (*)
1. In field "search by keyword" set 0 and click search

### Expected result (*)
1.  Product "simple 0" will be found

### Actual result (*)
1. Product "simple 0" didn't found
![image](https://user-images.githubusercontent.com/51681547/60183773-9871f200-982f-11e9-807c-da31236a939d.png)

### Additional info
If we search by "4" product "simple 4" will be found 
![image](https://user-images.githubusercontent.com/51681547/60184063-12a27680-9830-11e9-847b-f132a0dc5e13.png)

I think it is related to method `\Magento\Ui\Component\Filters\Type\Search::applyFilter()`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17811`, `MC-17812` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @engcom-Golf. Thank you for your report. 
The issue has been fixed in magento/magento2#23427 by @jeysmook in 2.3-develop branch
Related commit(s):
 - [36190fbbb77f1f3f22187f8b65905967b23b283e](https://github.com/magento/magento2/commit/36190fbbb77f1f3f22187f8b65905967b23b283e)
 - [a8f5c0d6c98a04ad88dc4f73580e08f1c572cefe](https://github.com/magento/magento2/commit/a8f5c0d6c98a04ad88dc4f73580e08f1c572cefe)
 - [dfd664e5d2cb14348b49984d3760c779e0dabe7c](https://github.com/magento/magento2/commit/dfd664e5d2cb14348b49984d3760c779e0dabe7c)

The fix will be available with the upcoming 2.3.3 release.
