### ISSUE TITLE
Ship is not working on Firefox

### ISSUE THREAD

**Issue by qb90** [magento/magento2#23421]
### Preconditions (*)
1. Magento 2.3.1
2. Firefox 67.0.4 ( 64bit on Windows10 )
3. Chrome 75.0.0

### Steps to reproduce (*)
1. Create order on store as user
2. Log in to magento panel as admin on Firefox
3. Select **Sales** -> **Orders** from main menu
4. Select order and go to details
5. Go to **Better Ship** tab - custom modification of Ship
DEV info : Print Shipping Label problem
Shipping without Shipping Label print
6. **Create Packages** popup is opened, just click **Save** button.
![ff1](https://user-images.githubusercontent.com/16085506/60176772-93a14400-9817-11e9-9c9f-b4d1c162f504.JPG)

### Expected result (*)
1. **Create Packages** popup is closed
2. Redirect is working, 
3. Success message "The shipment has been created. You created the shipping label." is visible.

### Actual result (*)
1. Feature works on Chrome
![chrome1](https://user-images.githubusercontent.com/16085506/60177609-98ff8e00-9819-11e9-9f01-181d06ce9453.JPG)
![chrome2](https://user-images.githubusercontent.com/16085506/60177626-a3ba2300-9819-11e9-88c1-89784f243381.JPG)
2. Feature don't works on Firefox, **Create Packages** popup is not closed, redirect not working, 
success message is not visible.

### Next Steps on Firefox (*)
1. Close **Create Packages** popup
2. **New Shipment** page is visible, click **Submit Shipment** button
![ff3](https://user-images.githubusercontent.com/16085506/60176786-9d2aac00-9817-11e9-899a-ea4cab051f32.JPG)
3. 404 Error is visible
![ff4](https://user-images.githubusercontent.com/16085506/60176801-a582e700-9817-11e9-9ee1-11bf5f305026.JPG)

**Comment by engcom-Charlie** [comment]
Hello @qb90 ! Thank you for your report ! 
Can you confirm that this issue is reproducible on Vanilla Magento 2.3.1 ? Because as i can see , you are using some custom extensions here .

**Comment by engcom-Charlie** [comment]
Feel free to reopen it in case you can confirm that you are able to reproduce this issue on Vanilla Magento instance.

**Comment by cieslix** [comment]
@engcom-Charlie it is related to Printing Shipping Label, it happens when you start Ship process and you are using shipping carrier which provides PDF Label service. On vanilla Magento this is impossible to check, because lack of credentials to any Shipping Label service. But anyway after you create shipment with PDF Label you should be redirected to Sales Order View. It is correctly handled on Chrome browser (there is response 200 with header Location to sales order view), but on Firefox browser header location is interpreted differently, response is 302, and AJAX call is transferred to header Location, administrator stays on Create Package page, when he tries to submit once again he is transferred to 404 page.

**Comment by qb90** [comment]
> 
> 
> Feel free to reopen it in case you can confirm that you are able to reproduce this issue on Vanilla Magento instance.

@engcom-Charlie please reopen this issue

**Comment by engcom-Charlie** [comment]
Hello @cieslix , @qb90 !
We`ve tested this issue and we are not able to reproduce it on our Magento instance . Probably you have that kind of Error because you are using Windows OS ( here is a link with requirements https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html) . Try to reproduce it using Linux, Ubuntu and similar OS .
