### ISSUE TITLE
Url Rewrites are lost if an exception thrown or deadlock during regeneration

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#23429]
Magento 2.3.x probably 2.2 and 2.1 as well
### Preconditions (*)
In some cases when the `url_rewrite` has a lock and e.g. after the product saving - M2 regenerates URL and leaves the product without readable urls and affected URL lead to 404 page since they had not been generated again.

1.
2.

### Steps to reproduce (*)

1. Save product to trigger url regenerate
2. Simulate lock on `url_rewrite` table
3. See an exception
4. Clean cache and go to product page by known URL
5. See 404 page

### Expected result (*)

1. URL leads to correct product page
2.

### Actual result (*)

1. URL leads to 404 page
2.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18687` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ilnytskyi. Thank you for your report. 
The issue has been fixed in magento/magento2#23430 by @ilnytskyi in 2.3-develop branch
Related commit(s):
 - [b8f6a3ad75dddabdcc3bd06bed4f87064032e202](https://github.com/magento/magento2/commit/b8f6a3ad75dddabdcc3bd06bed4f87064032e202)
 - [a5c4a91a72e1ce10f279fce3f9d0e8ce7b4e79b2](https://github.com/magento/magento2/commit/a5c4a91a72e1ce10f279fce3f9d0e8ce7b4e79b2)
 - [a562b151c4d4c4ffe35037cace2f89c687fc5fb1](https://github.com/magento/magento2/commit/a562b151c4d4c4ffe35037cace2f89c687fc5fb1)
 - [a22f78e509eb7394439e204dbf0391b3b26ed36f](https://github.com/magento/magento2/commit/a22f78e509eb7394439e204dbf0391b3b26ed36f)

The fix will be available with the upcoming 2.3.4 release.
