### ISSUE TITLE
allow implement wysiwyg for frontend ?

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#23441]
### Description (*)
From frontend user can interactive with wysiwyg editor with less action than admin

### Expected behavior (*)
No implements yet in frontend with wysiwyg

### Benefits
possible provide convention way for 3rd-party extension provider can intergrate wysiwyg in frontend

**Comment by shikhamis11** [comment]
hello @mrtuvn 
This repo is for magento core functionality bugs for new features you can create issue at [Feature Request](https://github.com/magento/community-features)

**Comment by hostep** [comment]
@mrtuvn: since you were also commenting in https://github.com/magento/magento2/issues/21766, does this mean that exposing that `wysiwygAdapter` thingy on the frontend isn't enough to get the wysiwyg working? And does that also mean that issue #21766 is actually valid and we can remove it from the frontend entirely then?

**Comment by mrtuvn** [comment]
@hostep magento plan to make wysiwyg for frontend ? or only make it work for backend
From backend wysiwyg working without problem. But from frontend i have tried to make wysiwyg work but it's very tricky and also not available docs related to make editor in frontend

**Comment by hostep** [comment]
Well, I don't know the plans of Magento to make it available on the frontend. That's why there is no progress in https://github.com/magento/magento2/issues/21766. I assumed it was a bug to make it available in the frontend and would like to see it being removed honestly.

But you want the exact opposite 🙂. What is your particular use case for wanting it to be available in the frontend?

**Comment by mrtuvn** [comment]
i have seen and also work with some extension in frontend use wysiwyg as content editor in modules. After 2.3 release with new implement editor. This is major changed also make some extension break .So  will be great if magento can bring wysiwyg to frontend allow convention official way to implement editor in frontend . This is my thought about this. Maybe this idea not neccessary for magento right now
