### ISSUE TITLE
Phone and Zip not update if customer have no saved address

### ISSUE THREAD

**Issue by vrajesh-patel1993** [magento/magento2#23467]
### Preconditions (*)

1. Magento 2.2.x
2. Magento 2.3.x

### Steps to reproduce (*)

1. Go to Admin
2. Customers >> All Customers 
3. From customer grid Add Phone number and zip code
4. Click on save
5. Display success message like "You have successfully saved your edits"but it does not saved.

### Expected result (*)

Text fields should not be display for Phone and zip code if customer not saved any address.

### Actual result (*)

https://www.screencast.com/t/g4B0hxx9

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17888`, `MC-17889` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @vrajesh-patel1993. Thank you for your report. 
The issue has been fixed in magento/magento2#23494 by @kazim-krish in 2.3-develop branch
Related commit(s):
 - [2d7d8a85d23f928b64e769038009b05fb6bcbf68](https://github.com/magento/magento2/commit/2d7d8a85d23f928b64e769038009b05fb6bcbf68)
 - [11b1c2bf64f4650add22371e39b5a7e510231e01](https://github.com/magento/magento2/commit/11b1c2bf64f4650add22371e39b5a7e510231e01)

The fix will be available with the upcoming 2.3.3 release.

**Comment by magento-engcom-team** [comment]
Hi @vrajesh-patel1993. Thank you for your report. 
The issue has been fixed in magento/magento2#23614 by @krishprakash in 2.2-develop branch
Related commit(s):
 - [c2c2fd57beb0d6a9cbc044f48b770f0f6d48e194](https://github.com/magento/magento2/commit/c2c2fd57beb0d6a9cbc044f48b770f0f6d48e194)
 - [e2e901061600c0fc46a1359dff4c801aa8d22f94](https://github.com/magento/magento2/commit/e2e901061600c0fc46a1359dff4c801aa8d22f94)

The fix will be available with the upcoming 2.2.10 release.
