### ISSUE TITLE
Cart empty after update qty with -1 and change address.

### ISSUE THREAD

**Issue by nirmalraval18** [magento/magento2#23466]
### Description (*)
Cart empty after update qty with -1 and change address.

### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Front end >> Login into account
2. Add 1 product with 4 qty to the cart
3. Cart >> Go to checkout with multiple addresses
4. Change address for 1st product and update qty with -1
5. Click on Update qty & addresses
6. It will clear the shopping cart

### Expected result (*)

1. -1 Qty should not allow while update qty.

### Actual result (*)

1. https://www.screencast.com/t/dsyR2fC4

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17886`, `MC-17887` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @nirmalraval18. Thank you for your report. 
The issue has been fixed in magento/magento2#23477 by @nirmalraval18 in 2.3-develop branch
Related commit(s):
 - [6735bc5d68117f139d4b7376fc8ffcf756df5211](https://github.com/magento/magento2/commit/6735bc5d68117f139d4b7376fc8ffcf756df5211)

The fix will be available with the upcoming 2.3.3 release.
