### ISSUE TITLE
Product Images are very small in RSS Product Feed

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#23516]
I have installed the Magento 2.3.1.

I hav enabled the RSS Feed for the category and Product.

### Preconditions
enabled the RSS Feed for the category and Product

Information on your environment
I have installed the Magento 2.3.1.

### Steps to reproduce 
Open the Rss feed Page : http://magento2jigar.com/rss/

Click on the Get Feed link and It will show the xml feed.
see attached screenshot

### Expected result (*)
It should show the large image then too small, because I am uploading RSS feed to facebook and the image is too small to display.

### Actual result (*)
Its very small image generating.

![rss1](https://user-images.githubusercontent.com/16815711/60413881-fd449800-9bf3-11e9-8eb0-b4892bfccf0f.png)
![rss2](https://user-images.githubusercontent.com/16815711/60413882-fd449800-9bf3-11e9-9046-93597d6989ab.png)
![rss3](https://user-images.githubusercontent.com/16815711/60413883-fddd2e80-9bf3-11e9-8e54-293de92a5ede.png)
![rss4](https://user-images.githubusercontent.com/16815711/60413885-fddd2e80-9bf3-11e9-8493-203feadf37df.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17907`, `MC-17908` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
Hello,

https://github.com/magento/magento2/blob/2.3-develop/app/design/frontend/Magento/luma/etc/view.xml

it is not issue, you can modify that size from theme xml file.

**Comment by sunilit42** [comment]
@magento-engcom-team  do you want to change size let me know so i can change it.

**Comment by jigar48** [comment]
@sunilit42 Thank you for checking,

Image size can be changed, but the height and width of that attribute is remain same, It does not changed.

![image](https://user-images.githubusercontent.com/16815711/60450797-432b4b80-9c48-11e9-9deb-acda2e39787c.png)

**Comment by magento-engcom-team** [comment]
Hi @jigar48. Thank you for your report. 
The issue has been fixed in magento/magento2#23533 by @sunilit42 in 2.3-develop branch
Related commit(s):
 - [5853484d582f230087e425df39a372135b6e9bf7](https://github.com/magento/magento2/commit/5853484d582f230087e425df39a372135b6e9bf7)
 - [5bb135860dec61fd4d19aa37729c44f71e0981df](https://github.com/magento/magento2/commit/5bb135860dec61fd4d19aa37729c44f71e0981df)
 - [3a2f5c412f16d50cb60dae44e4856aa29afb7baa](https://github.com/magento/magento2/commit/3a2f5c412f16d50cb60dae44e4856aa29afb7baa)
 - [521e950db5ef14c059c404531b3bff729af19c68](https://github.com/magento/magento2/commit/521e950db5ef14c059c404531b3bff729af19c68)
 - [06a91b87181a7889f7cc4c41177ff6b935787f5d](https://github.com/magento/magento2/commit/06a91b87181a7889f7cc4c41177ff6b935787f5d)
 - [9e497bf114b554c273ccedcb2726e74447c8ea3b](https://github.com/magento/magento2/commit/9e497bf114b554c273ccedcb2726e74447c8ea3b)
 - [3e655f7af0816ab7973bff92cdae8e966750804c](https://github.com/magento/magento2/commit/3e655f7af0816ab7973bff92cdae8e966750804c)
 - [475555238a403698c4c4dbda48ae53971a39069a](https://github.com/magento/magento2/commit/475555238a403698c4c4dbda48ae53971a39069a)
 - [13a7c758fbb32b7125b62473cb202f1777300092](https://github.com/magento/magento2/commit/13a7c758fbb32b7125b62473cb202f1777300092)
 - [f968f859d1b824a4e3edd40a7303413dd025cfbd](https://github.com/magento/magento2/commit/f968f859d1b824a4e3edd40a7303413dd025cfbd)
 - [2f9d572a26e381455ac18aec090331b3529a787c](https://github.com/magento/magento2/commit/2f9d572a26e381455ac18aec090331b3529a787c)
 - [e8ca4889d9dc9ecc610da8ae3c63da7ee8de44c4](https://github.com/magento/magento2/commit/e8ca4889d9dc9ecc610da8ae3c63da7ee8de44c4)
 - [9f088cf3bbb2dc2483aaa4f29fbb2ac19531939d](https://github.com/magento/magento2/commit/9f088cf3bbb2dc2483aaa4f29fbb2ac19531939d)
 - [af94999497d3478c45c841e7c0c5ebfb1705b623](https://github.com/magento/magento2/commit/af94999497d3478c45c841e7c0c5ebfb1705b623)
 - [1fa9615f1cfd01ce26e6c1ec2072191b3e0d3b5c](https://github.com/magento/magento2/commit/1fa9615f1cfd01ce26e6c1ec2072191b3e0d3b5c)
 - [70afacd4368eb3398756a2d424470346e3173d6d](https://github.com/magento/magento2/commit/70afacd4368eb3398756a2d424470346e3173d6d)
 - [d6bd1d63d2a9096bf203516be7e8cebe0ec7d655](https://github.com/magento/magento2/commit/d6bd1d63d2a9096bf203516be7e8cebe0ec7d655)
 - [041385424e04b3f89bdae29d69b6b7b37118a8a4](https://github.com/magento/magento2/commit/041385424e04b3f89bdae29d69b6b7b37118a8a4)
 - [f3ef0cea68e4b185a7fec669f2d39897bbad968f](https://github.com/magento/magento2/commit/f3ef0cea68e4b185a7fec669f2d39897bbad968f)
 - [977552842f585c5381493ee02ba6f7b4090ed5ba](https://github.com/magento/magento2/commit/977552842f585c5381493ee02ba6f7b4090ed5ba)
 - [c086ab22ea66787325a6029f4b93aed31168a92f](https://github.com/magento/magento2/commit/c086ab22ea66787325a6029f4b93aed31168a92f)
 - [c4906f1ab6dfa87817a9a24764777f645377c158](https://github.com/magento/magento2/commit/c4906f1ab6dfa87817a9a24764777f645377c158)
 - [04d34518675745afd6a4bf4d4c7aae5b7c56f3e2](https://github.com/magento/magento2/commit/04d34518675745afd6a4bf4d4c7aae5b7c56f3e2)
 - [9c0ca372d50eacf9432f9bcb8c873c6e4261683e](https://github.com/magento/magento2/commit/9c0ca372d50eacf9432f9bcb8c873c6e4261683e)
 - [52b9939576af0b0ddb5fe70692ae482cb4a59e30](https://github.com/magento/magento2/commit/52b9939576af0b0ddb5fe70692ae482cb4a59e30)
 - [f301d5fb3478788700e17a31245de60849dbbab3](https://github.com/magento/magento2/commit/f301d5fb3478788700e17a31245de60849dbbab3)

The fix will be available with the upcoming 2.3.4 release.
