### ISSUE TITLE
Varnish Validation incorrect - Subnets are allowed in varnish VCL

### ISSUE THREAD

**Issue by bytes-max** [magento/magento2#23512]
### Preconditions (*)
1. Install PHP 7.2, MariaDB 5.7, Varnish 5.2.1
2. Install Magento 2.3.2

### Steps to reproduce (*)
1. Modify configuration node `system/full_page_cache/varnish/access_list` in Backend manually
2. add a ip incl. subnet notation (x.x.x.x/16)
3. press "Generate Config for v5+"

### Expected result (*)
1. Magento should validate the string correctly as IP with subnet notation. 
2. this is allowed to the documentation: https://varnish-cache.org/docs/5.1/users-guide/vcl-example-acls.html
3. its also allwed in 4.1+ https://varnish-cache.org/docs/4.1/users-guide/vcl-example-acls.html?highlight=acl

### Actual result (*)

1. [Screenshots, logs or description]

![image](https://user-images.githubusercontent.com/6654389/60400844-16a8fe00-9b7a-11e9-9828-2e64df0ca679.png)

**Comment by danemacmillan** [comment]
I'd like to add the correct terminology for this, should people be searching. What OP and myself want, and what the Varnish documentation allows, is the ability to define CIDR notated IP addresses.

In other words, similar to OP, I want to allow an entire range in my local instance group to be able to purge Varnish. In order to do so, without having to define 255 IP addresses, I would be able to write a shorter version, using CIDR notation: `10.162.0.0/24`, which corresponds to all IP addresses between `10.162.0.1` and `10.162.0.255`.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19909` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nopenopenope** [comment]
Unless nothing has changed, this is still an open issue/feauture request.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
