### ISSUE TITLE
The display watermark size is incorrect compared to the original watermark images on list product,product page on magento2.3.2

### ISSUE THREAD

**Issue by jordantran93** [magento/magento2#23515]
### Preconditions (*)

1.Magento 2.3.2 community edition
2. Fresh installation, no third party modules
### Steps to reproduce (*)

1. Go to Content -> Design->Configuration -> Edit Theme Luma
https://prnt.sc/o8u05g 
2.set  watermark image opacity to 99, image size to 255x68, image position to Bottom/Left, and saved configuration. https://prnt.sc/o8u1py
3.set small watermark image opacity to 99, image size to 147x38, image position to Bottom/Left, and saved configuration. https://prnt.sc/o8u0fu

### Expected result (*)

1.   watermark images size same image size uploaded is 147x38 on list page, 255x68 size on product page.  https://prnt.sc/o8u3co  https://prnt.sc/o8u3hk

### Actual result (*)

1. On product page and list product page show watermark smaller than origin watermark uploaded  https://prnt.sc/o8u36k  https://prnt.sc/o8u3lx
2. with images have size different will show watermark have size different and position also different  https://prnt.sc/o8u2wa

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17914` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wbeltranc** [comment]
#cd19latam

**Comment by rschulerdh** [comment]
@magento I am working on it

**Comment by mattheo-geoffray** [comment]
@magento I am working on it

**Comment by VladimirZaets** [comment]
Hi @jordantran93. Thank you for your report. 
The issue has been fixed in magento/magento2#25528 by @Krielkip in 2.3-develop branch
Related commit(s):
 - [85415eff8ddd81c9b204ec6c093efe49d467ba9e](https://github.com/magento/magento2/commit/85415eff8ddd81c9b204ec6c093efe49d467ba9e)
 - [2263d2e9fe2359b86c26dc91597cf50b5a87def4](https://github.com/magento/magento2/commit/2263d2e9fe2359b86c26dc91597cf50b5a87def4)

The fix will be available with the upcoming 2.3.5 release.
