### ISSUE TITLE
update from 2.3.1 to 2.3.2

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#23548]
Hello,

i have a problem, to update to the new version 2.3.2,
i have at the moment the 2.3.1 version.

In Step 2 i get an error at the readiness check, that the php extension mcrypt isnt happening.
in the info.php on the site it still is on.

The System is an Debian 8, with Plesk, the Domainhost have the PHP Version 7.2.19.

What could it be?

Can Somebody help ?

![image](https://user-images.githubusercontent.com/31250340/60536900-96180800-9d07-11e9-9df0-af8ca6c8a705.png)

**Comment by Olek89** [comment]
How can i make a check on vanilla Magento?
I cant find a Solution for it.
I think it could also be an misconfiguration of the server, but i still dont see it on magento, why there should not work.

**Comment by engcom-Bravo** [comment]
Hello @Olek89. The GitHub issue tracker is intended for Magento Core technical issues only. Your issue is not of that kind as there are already many people who have successfully updated their instances from 2.3.1 to 2.3.2 without facing that problem. In Your case we would suggest You to refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. Also please make sure You have that mcrypt extension installed and enabled precisely for the PHP version You are using for Your instance. Thanks for applying.
