### ISSUE TITLE
Tear Price? Tier Price?

### ISSUE THREAD

**Issue by dyuk1987** [magento/magento2#23567]
### Summary (*)

_(Not sure where to put this "issue")_
I found the term "**Tear Price**" in some part of the core when I was digging around. I was wondering if this is a typo for "**Tier Price**" or actually a special term.

### Examples (*)

With a little grep, I was managed to find "**Tear Price**" in at least 8 files:

1. magento/module-advanced-pricing-import-export/Test/Unit/Model/Import/AdvancedPricingTest.php
2. magento/module-advanced-pricing-import-export/Model/Import/AdvancedPricing.php
3. magento/magento2-base/dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductTierPriceManagementTest.php
4. magento/magento2-base/dev/tests/integration/testsuite/Magento/GroupedProduct/Pricing/Price/FinalPriceTest.php
5. magento/module-catalog/Test/Unit/Pricing/Price/BasePriceTest.php
6. magento/module-catalog/Test/Unit/Model/Product/Attribute/Backend/GroupPrice/AbstractTest.php
7. magento/module-catalog-rule/Test/Unit/Model/Indexer/IndexBuilderTest.php
8. magento/module-catalog/Model/Product/Type/Price.php

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23567-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23567-2-3-develop.instances.magento-community.engineering/admin](https://i-23567-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-23567-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23567-2-2-develop.instances.magento-community.engineering/admin](https://i-23567-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17945`, `MC-17946` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-23567-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23567-2-3-develop.instances.magento-community.engineering/admin](https://i-23567-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sunilit42** [comment]
Hello @magento-engcom-team 

grep -ril "Tear Price" vendor/magento/

i did not find any thing.

**Comment by sunilit42** [comment]
@DanielRuf , why you removed, can not reproduce tag? 

are you able to genereate issue?

**Comment by sdzhepa** [comment]
Hello @sunilit42, @dyuk1987, @DanielRuf 

It can be found in Magento codebase on GitHub using search
- https://github.com/magento/magento2/search?q=%22Tear+Price%22&unscoped_q=%22Tear+Price%22

**Comment by DanielRuf** [comment]
It was already reproduced twice.

> [engcom-Charlie](/engcom-Charlie) (Robert Turchyn) added the [Reproduced on 2.3.x](/magento/magento2/labels/Reproduced%20on%202.3.x)  label [vor 4 Tagen](#event-2460356624)

> [engcom-Charlie](/engcom-Charlie) (Robert Turchyn) added [Reproduced on 2.2.x](/magento/magento2/labels/Reproduced%20on%202.2.x)  [Issue: Confirmed](/magento/magento2/labels/Issue%3A%20Confirmed)  labels [vor 4 Tagen](#event-2460396560)

**Comment by magento-engcom-team** [comment]
Hi @dyuk1987. Thank you for your report. 
The issue has been fixed in magento/magento2#24160 by @sunilit42 in 2.3-develop branch
Related commit(s):
 - [1666ce89abb376adf3fbc445d1ed2e868c34ad5c](https://github.com/magento/magento2/commit/1666ce89abb376adf3fbc445d1ed2e868c34ad5c)
 - [5ac00d12a04a07645d61836ec4a8e7a765c34b61](https://github.com/magento/magento2/commit/5ac00d12a04a07645d61836ec4a8e7a765c34b61)
 - [4ad28850d49555df4a6a55919a614a2bf2c2047c](https://github.com/magento/magento2/commit/4ad28850d49555df4a6a55919a614a2bf2c2047c)
 - [93265e6495bc881b32827c7da4b02a21a610163f](https://github.com/magento/magento2/commit/93265e6495bc881b32827c7da4b02a21a610163f)
 - [09b94a65e1877a5e18832c8a8c26bc79f144f479](https://github.com/magento/magento2/commit/09b94a65e1877a5e18832c8a8c26bc79f144f479)
 - [ca9de510637b0e5c1d2a9f9a0ebe882ec97af7a9](https://github.com/magento/magento2/commit/ca9de510637b0e5c1d2a9f9a0ebe882ec97af7a9)
 - [8d90e19f49d350a48eb14426a88e283438663e8c](https://github.com/magento/magento2/commit/8d90e19f49d350a48eb14426a88e283438663e8c)
 - [4ccf3068f612771dbc4c48969b37c7ac445b7159](https://github.com/magento/magento2/commit/4ccf3068f612771dbc4c48969b37c7ac445b7159)
 - [fb99abc8d2b1ede79095f4d9f136a982e865cb4a](https://github.com/magento/magento2/commit/fb99abc8d2b1ede79095f4d9f136a982e865cb4a)
 - [8c1ddd19e1a1608db33768cac93a13adb4ed81b4](https://github.com/magento/magento2/commit/8c1ddd19e1a1608db33768cac93a13adb4ed81b4)
 - [db48e4c5d3de68323c88f1d540570bb652ae7e20](https://github.com/magento/magento2/commit/db48e4c5d3de68323c88f1d540570bb652ae7e20)
 - [aa1f52f96df32b970747ac84406adb2bb01d0189](https://github.com/magento/magento2/commit/aa1f52f96df32b970747ac84406adb2bb01d0189)

The fix will be available with the upcoming 2.3.4 release.
