### ISSUE TITLE
Database Media Storage : Difficulty changing mode to database media storage due to poor "Use Default Value" checkbox behaviour

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#23597]
### Preconditions (*)
1. 2.3-develop

### Steps to reproduce (*)
1. Deploy 2.3-develop
2. Stores -> Configuration -> Advanced -> System
3. Storage Configuration for Media
4. Change File System to Database
5. Select Media database = "Default setup"
6. Notice that the Use Default Values checkboxes are still ticked!!!
7. Click Synchronize
8. Save Config
9. Media Storage Mode is greyed out, but set to Database.

### Expected result (*)
1. System is placed into Database Media Storage Mode

### Actual result (*)
1. Checking of core_config shows system not in database storage mode even though settings page states we are in Database Media Storage Mode (albeit greyed out with use default value checked)
2. Its not clear to the user what mode we are in.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17969` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#23710 by @gwharton in 2.3-develop branch
Related commit(s):
 - [85e5375ad2e45eebeb5667b3f5e9a91e16989213](https://github.com/magento/magento2/commit/85e5375ad2e45eebeb5667b3f5e9a91e16989213)
 - [a97426185620893353474b0586f499322a07ae29](https://github.com/magento/magento2/commit/a97426185620893353474b0586f499322a07ae29)

The fix will be available with the upcoming 2.3.3 release.
