### ISSUE TITLE
Mime parts of email are no more encoded with quoted printable

### ISSUE THREAD

**Issue by ffauvel** [magento/magento2#23643]
### Preconditions (*)
1. 2.2.8+

### Steps to reproduce (*)
1. Add a lot of css to the email template
2. Complete an order

### Expected result (*)
1. The email is sent to the customer

### Actual result (*)
1. The email is rejected by the mail server - Error message: Message too big

Before 2.2.8, Magento was using Zend_Mail and Zend_Mime_Part (from ZF1) to send email.
The default encoding of Zend_Mime_Part was QUOTED_PRINTABLE.
In Magento 2.2.8+, they switch to Zend\Mail (from ZF2). The default encoding is 8bit.

It should be change back to QUOTED_PRINTABLE to avoid overlong lines.

**Comment by ffauvel** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ffauvel. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ffauvel, here is your [Magento instance](https://i-23643-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23643-2-3-develop.instances.magento-community.engineering/admin](https://i-23643-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @ffauvel. Thank you for your report. 
The issue has been fixed in magento/magento2#23650 by @gwharton in 2.2-develop branch
Related commit(s):
 - [9f66582a354fc57e7931cd1fbdf73d874f25baf2](https://github.com/magento/magento2/commit/9f66582a354fc57e7931cd1fbdf73d874f25baf2)

The fix will be available with the upcoming 2.2.10 release.

**Comment by magento-engcom-team** [comment]
Hi @ffauvel. Thank you for your report. 
The issue has been fixed in magento/magento2#23649 by @gwharton in 2.3-develop branch
Related commit(s):
 - [226009e90bba3af2c1d2b0ddb3ad9fc5c2b8f362](https://github.com/magento/magento2/commit/226009e90bba3af2c1d2b0ddb3ad9fc5c2b8f362)

The fix will be available with the upcoming 2.3.3 release.

**Comment by avoelkl** [comment]
For anyone having troubles with e-mails in Magento 2.3.2 as well:
We had the problem that the merchants' firewall blocked all magento mails as "line too long".

I added commit 226009e90bba3af2c1d2b0ddb3ad9fc5c2b8f362 as hotfix to one of my projects but had to adjust the hotfix locally it as there were different changes to Message.php as well.

The issue was resolved applying the fix.
In fact, these 2 lines are important:
https://github.com/magento/magento2/commit/226009e90bba3af2c1d2b0ddb3ad9fc5c2b8f362#diff-134b78852b9ecf820540911b665d6566R170

lib/internal/Magento/Framework/Mail/Message.php:
$part->setEncoding(Mime::ENCODING_QUOTEDPRINTABLE);
$part->setDisposition(Mime::DISPOSITION_INLINE);

**Comment by a-dite** [comment]
After update to Magento 2.2.10 (from 2.2.9) in our customer project we faced the issue that diverse mails, also the order confirmation mail, on some Exchange servers, were displayed empty in Outlook and the content of the mail was in an attachment file like ATT00000011.htm. See description e.g. [here](https://exchange-server-guide.blogspot.com/2015/11/att00001.txt-file-fix-email-attachment-issue.html). We fixed the issue by reverting the functional (not tests) part of the PR [#23650](https://github.com/magento/magento2/pull/23650) via patch. Actually removing these lines in [lib/internal/Magento/Framework/Mail/Message.php  ](https://github.com/magento/magento2/pull/23650/files#diff-134b78852b9ecf820540911b665d6566)

`$part->setEncoding(Mime::ENCODING_QUOTEDPRINTABLE);
        $part->setDisposition(Mime::DISPOSITION_INLINE);`

Let me know if i should open a new issue.
