### ISSUE TITLE
Can't see "Zero Subtotal Checkout" payment method settings if "Offline Payments" module is disabled

### ISSUE THREAD

**Issue by textarea** [magento/magento2#23678]
### Preconditions (*)
1. Magento 2.3.2

### Steps to reproduce (*)
1. php bin/magento module:disable Magento_OfflinePayments

### Expected result (*)
1. Go to Stores -> Configuration -> Sales -> Payment Methods
2. Can see and change "Zero Subtotal Checkout" payment method settings

### Actual result (*)
1. "Zero Subtotal Checkout" payment method settings are disappeared even if Free payment method is still enabled and running

**Comment by magento-engcom-team** [comment]
Hi @textarea. Thank you for your report. 
The issue has been fixed in magento/magento2#23679 by @textarea in 2.3-develop branch
Related commit(s):
 - [089e24a10d2ee8d527e5e65308d384a095127461](https://github.com/magento/magento2/commit/089e24a10d2ee8d527e5e65308d384a095127461)
 - [fb7d3aeec66ef78767bd1faf48d57711f62ec593](https://github.com/magento/magento2/commit/fb7d3aeec66ef78767bd1faf48d57711f62ec593)

The fix will be available with the upcoming 2.3.3 release.
