### ISSUE TITLE
Magento2.2.2 sitemap.xml google link in urlset tag attribute returns 404

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#23706]
### Preconditions (*)
1.Magento2.2.2 install

### Steps to reproduce (*)
Go to:
1.Dashboard->Marketing->SEO & Search->sitemap
2.Click add new fill in required fields
3. hit save & generate
4.Open newly created xml and check urlset tag attr xmlns:content is: "http://www.google.com/schemas/sitemap-content/1.0"

### Expected result (*)
Should be one of returns 200 OK like: http://www.sitemaps.org/schemas/sitemap/0.9

### Actual result (*)
http://www.google.com/schemas/sitemap-content/1.0
ref:
<img width="1504" alt="Screenshot 2019-07-15 at 14 13 36" src="https://user-images.githubusercontent.com/3495481/61219213-a8347600-a70b-11e9-92f3-950ab18eeb22.png">

More Info: File https://github.com/magento/magento2/blob/2.2/app/code/Magento/Sitemap/Model/Sitemap.php#L324

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18166`, `MC-18167` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @lano-vargas. Thank you for your report. 
The issue has been fixed in magento/magento2#23716 by @sunilit42 in 2.3-develop branch
Related commit(s):
 - [505d285b633828c1101113d41ebb9c3db9ae0335](https://github.com/magento/magento2/commit/505d285b633828c1101113d41ebb9c3db9ae0335)
 - [a95b55aad2c788204344454a109760b872fbf0fc](https://github.com/magento/magento2/commit/a95b55aad2c788204344454a109760b872fbf0fc)

The fix will be available with the upcoming 2.3.4 release.
