### ISSUE TITLE
So many Fields in Store->Configuration->Catalog has no-validations (digit, greater than zero)

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23721]
### Preconditions (*)

1. 2.3-develop

### Steps to reproduce (*)

1. Go to **Store->Configuration->Catalog->catalog**
2. Fill the string value in the fields like **"ggggg"** in following fields:

- Swatches per Product
- Default Recently Viewed Products Count
- Default Recently Compared Products Count
- Lifetime of products in Recently Viewed Widget
- Lifetime of products in Recently Compared Widget
- Search Suggestions Count
- Maximal Depth
- Default Maximum Number of Downloads
- Year Range

3. Click **"Save"**

### Expected result (*)

1. Validate, prevent the admin user saves.

### Actual result (*)

1. Save with the wrong data
![image](https://user-images.githubusercontent.com/8234209/61282571-c2428700-a7e5-11e9-917a-4c20c47214a9.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18895` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sidolov** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23723 by @edenduong in 2.3-develop branch
Related commit(s):
 - [7f585fd162fbc1a83d6608f29d238efbadc09dd5](https://github.com/magento/magento2/commit/7f585fd162fbc1a83d6608f29d238efbadc09dd5)
 - [f30301da8348486a42ebeb42e19513a138201709](https://github.com/magento/magento2/commit/f30301da8348486a42ebeb42e19513a138201709)

The fix will be available with the upcoming 2.3.3 release.
