### ISSUE TITLE
Numerous \ slashes are being added to the extra field in admin_user

### ISSUE THREAD

**Issue by AdamEarney** [magento/magento2#23744]
### Description (*)

Too many \ slashes are being added to the extra field in the admin_user table. This is happening here in this file: /Volumes/Sites/FleurOfEngland/vendor/magento/module-user/Model/User.php on line 241. 

This code in particular.

```
$data = [
            'extra' => $this->serializer->serialize($this->getExtra()),
        ];
```

### Preconditions (*)
1. Have Magento 2.2.8 installed

### Steps to reproduce (*)
1. Navigate to the admin
2. Login multiple times
3. Check the contents of the extra field in admin_user
4. Keep logging in and out until you can no longer login

### Expected result (*)
1. I login and the field is serialised 

### Actual result (*)
1. The field continues to have multiple slashes added to the field
2. Eventually I login and a report ID is shown to me rather than the admin page

**Comment by engcom-Charlie** [comment]
Hello @AdamEarney ! I was trying to reproduce this issue on fresh vanilla 2.3-develop instance and seems like it`s not reproducible . I`m closing it for now but feel free in case you can confirm that issue is reproducible (in that case please add some extra steps/info).
Thank you for your contribution !

![Screenshot from 2019-07-18 11-51-27](https://user-images.githubusercontent.com/51680850/61444064-58e08680-a953-11e9-9d51-a2a2091a0a2b.png)
