### ISSUE TITLE
Store view switcher is wrong , when each store views have different url.

### ISSUE THREAD

**Issue by Taku-Yamashita** [magento/magento2#23755]
### Preconditions (*)

1.  Magento 2.3.1
2.  using 2 store views and those views have different url (en.magento.local & jp.magento.local) 

### Steps to reproduce (*)

1.  Click a target store view on  language switcher.
2.  successfully switch to target store view.
3.  but will be displayed below error.
The store that was requested wasn't found. Verify the store and try again.

### Expected result (*)

1.  Switch to target store view.
2.  no errors are displayed.

### Actual result (*)

1.  Switch to target store view.
2.  below error is displayed.
The store that was requested wasn't found. Verify the store and try again.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18256` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gtlt** [comment]
linking possible similar issue : https://github.com/magento/magento2/issues/22966

**Comment by magento-engcom-team** [comment]
Hi @Taku-Yamashita. Thank you for your report. 
The issue has been fixed in magento/magento2#26548 by @TobiasCodeNull in 2.4-develop branch
Related commit(s):
 - [346e544911827c379bdfed10f29ea40889d57078](https://github.com/magento/magento2/commit/346e544911827c379bdfed10f29ea40889d57078)
 - [392bd3b899cd26d5d329eaa0ab7e7a1b91125c4b](https://github.com/magento/magento2/commit/392bd3b899cd26d5d329eaa0ab7e7a1b91125c4b)
 - [0cbc5b641efdee01fa2bd4222c2cc313d3846198](https://github.com/magento/magento2/commit/0cbc5b641efdee01fa2bd4222c2cc313d3846198)
 - [420fa1c739a2b568a115defdc58509976241464d](https://github.com/magento/magento2/commit/420fa1c739a2b568a115defdc58509976241464d)
 - [1375b5356aae59924f0e8f70b1970e8b85877e19](https://github.com/magento/magento2/commit/1375b5356aae59924f0e8f70b1970e8b85877e19)
 - [9cad4dcf942f1be3f704a16293116458c7b837fe](https://github.com/magento/magento2/commit/9cad4dcf942f1be3f704a16293116458c7b837fe)
 - [602419572902c06ed81a58080391207304c32760](https://github.com/magento/magento2/commit/602419572902c06ed81a58080391207304c32760)
 - [ee97fb5c647ce047d98d2a5554c67540df3fd7cf](https://github.com/magento/magento2/commit/ee97fb5c647ce047d98d2a5554c67540df3fd7cf)
 - [689093a20a8d4226c2ca74c039a8136b7604887e](https://github.com/magento/magento2/commit/689093a20a8d4226c2ca74c039a8136b7604887e)
 - [4708394d867aa235d51489f0e12b9705f081b9db](https://github.com/magento/magento2/commit/4708394d867aa235d51489f0e12b9705f081b9db)
 - [597bb18bc0faba8b0e67a499749c15785a23da16](https://github.com/magento/magento2/commit/597bb18bc0faba8b0e67a499749c15785a23da16)
 - [0fcb6a0c06cbcbf733da284bb94b85a5e1ea1f16](https://github.com/magento/magento2/commit/0fcb6a0c06cbcbf733da284bb94b85a5e1ea1f16)

The fix will be available with the upcoming 2.4.0 release.

**Comment by viktym** [comment]
For Magento versions 2.3.0 - 2.3.5 patch is available in [Magento Quality Patches](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html#mqp) package (MQP)

**MQP Installation**
`$ composer require magento/quality-patches`

**Applying a Patch**
`$ ./vendor/bin/magento-patches apply MDVA-30107`

**Patch Details**
https://support.magento.com/hc/en-us/articles/360049869051
