### ISSUE TITLE
Non UTF-8 encoded URI component throws error in CatalogWidget module

### ISSUE THREAD

**Issue by FerihumF** [magento/magento2#23760]
### Preconditions (*)

1. Magento 2.2.7
2. Make sure (block) caching is enabled

### Steps to reproduce (*)

1. Add a "Catalog Product List" Widget to a CMS page.
2. Open the CMS page in your browser and add **?%E4** to the URL (which is "ä" in ISO-8859-1)

### Expected result (*)

1. Regardless the wrongly encoded URI component the page should render without issues.

### Actual result (*)

1. In live mode an error page appears. In developer mode the message is printed directly to the content: **Unable to serialize value.**

Here [https://github.com/magento/magento2/blob/0a1a283cd6a0cf4b98a051867f90150c9490fcec/app/code/Magento/CatalogWidget/Block/Product/ProductsList.php#L198](url) all parameters are trying to be serialized, but json_encode fails for non UTF-8 encoded strings.

My point is, that just by entering any url parameter the site should not throw an error. Or is this assumption wrong?

Real life scenario is, when e.g. advertising companies link to your site and pass along some utm parameters, but mess up the encoding. Customers clicking those links should not land on an error page.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18259` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @FerihumF. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-23846` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by edas11** [comment]
Looks like this issue is still on 2.4.7-p5 and 2.4.4-p13. If I go to a cms page which has product list widget and I add the query string `?dclid=%EDclid` to the url I get an error `Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded`.

I also get this serialization error when Magento tries to redirect to a url which has the query string `?dclid=%EDclid`. For example, redirect from `/some-page?dclid=%EDclid` to `/some-page/?dclid=%EDclid` causes an error.
