### ISSUE TITLE
CommentLevelsSniff works incorrect with @magento_import statement.

### ISSUE THREAD

**Issue by p-bystritsky** [magento/magento2#23789]
[DevDocs article about @magento_import](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css-preprocess.html#magento-import-usage)

### Preconditions (*)

1. Make some changes to any less file containing @magento_import statement.

### Steps to reproduce (*)

1. Run Magento\Test\Less\LiveCodeTest

### Expected result (*)

1. No error related to @magento_import statement.

### Actual result (*)

1. "Level's comment does not have 2 spaces after '//'" error raised on a line containing @magento_import statement

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your report. 
The issue has been fixed in magento/magento2#23790 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [a99014e3ef132ecf8f7949b6411760c07678f9cc](https://github.com/magento/magento2/commit/a99014e3ef132ecf8f7949b6411760c07678f9cc)

The fix will be available with the upcoming 2.3.3 release.
