### ISSUE TITLE
User data serialised multiple times on save when loaded via loadByUsername

### ISSUE THREAD

**Issue by mustdobetter** [magento/magento2#23824]
### Preconditions (*)

1. Magento 2.2.* or 2.3.*

### Steps to reproduce (*)

1. Load a user using the `loadByUsername` method of the model.
2. Set some data on the model.
3. Save the model.

### Expected result (*)

1. The model is saved with the `extra` field data properly serialised.

### Actual result (*)

1. The model is saved with the `extra` field data serialised twice, corrupting the data and preventing it from being properly unserialised. This can prevent login.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Den4ik 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18473` were created

**Issue Available**: @Den4ik, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @mustdobetter. Thank you for your report. 
The issue has been fixed in magento/magento2#23827 by @mustdobetter in 2.3-develop branch
Related commit(s):
 - [11f7f3954132512dd9d8fbc0a70e81e48de7a4ba](https://github.com/magento/magento2/commit/11f7f3954132512dd9d8fbc0a70e81e48de7a4ba)
 - [6501efae06f07c90df11cf933f5e71150283c0ce](https://github.com/magento/magento2/commit/6501efae06f07c90df11cf933f5e71150283c0ce)
 - [41e9fff03dfdb9e55faf3fe25541b81981cb7c5c](https://github.com/magento/magento2/commit/41e9fff03dfdb9e55faf3fe25541b81981cb7c5c)

The fix will be available with the upcoming 2.3.4 release.
