### ISSUE TITLE
Error messages on Checkout when 'Syncronize with Backend' option is turned ON

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#23833]
### Preconditions (*)
1. Magento 2.3
2. Catalog with at least 1 product
3. Enabled setting _Admin Panel -> Stores -> Configuration -> Catalog - > Recently Viewed/Compared Products -> Synchronize widget products with backend storage_ === **_Yes_**

### Steps to reproduce (*)
1. Go to store front
2. Add product to the cart
3. Go to checkout

### Expected result (*)
1. No errors in browser console

### Actual result (*)
1. Browser console contains logs about errors.
![image](https://user-images.githubusercontent.com/9420807/61701605-24037380-ad47-11e9-9635-75fb0ae6fc63.png)

### Notes:

- The problem that section 'product_data_storage' does not have **syncUrl**.
- In `app/code/Magento/Catalog/view/frontend/web/js/storage-manager.js::sendRequest` it uses syncUrl parameter to pass url for Ajax request and, in result, sent request to empty (in case of JS - current) url.
- The setting mentioned in Preconditions have place in:
`\Magento\Catalog\Block\FrontendStorageManager::getConfigurationJson` - passed to JSON response
- `if (this.requestSent || !~~this.storagesConfiguration[name].allowToSendRequest)` from `app/code/Magento/Catalog/view/frontend/web/js/storage-manager.js::sendRequest` - have impact on the flow.

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-23833-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23833-2-3-develop.instances.magento-community.engineering/admin](https://i-23833-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@swnsma ! I am not able to reproduced in vanilla Magento 2.3-develop instance

**Comment by engcom-Bravo** [comment]
Not reproduced on 2.2-develop.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18470` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by kirtinariya1** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kirtinariya1, here is your [Magento instance](https://i-23833-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23833-2-3-develop.instances.magento-community.engineering/admin](https://i-23833-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-23833-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23833-2-3-develop.instances.magento-community.engineering/admin](https://i-23833-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @Tripuresh-Kumar-Pandey. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Tripuresh-Kumar-Pandey, here is your [Magento instance](https://i-23833-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23833-2-3-develop.instances.magento-community.engineering/admin](https://i-23833-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @swnsma 

Internal Magento team is working on this issue right now in the scope of Jira ticket `MC-18470`.
AT this moment it in Code-review status.
When fix will be delivered this issue will be closed with comment and related commits.

**Comment by magento-engcom-team** [comment]
Hi @swnsma, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [cd4a3eb409238de01508fc3afe5adf283f30ce98](https://github.com/magento/magento2/commit/cd4a3eb409238de01508fc3afe5adf283f30ce98)
 - [0d4bcfabdb87853c70cff0c07f9bce82f6eb877b](https://github.com/magento/magento2/commit/0d4bcfabdb87853c70cff0c07f9bce82f6eb877b)
 - [461f38973a91a6a79924af082c43919ddd777042](https://github.com/magento/magento2/commit/461f38973a91a6a79924af082c43919ddd777042)
 - [e3f35b8e20960c6d9de1883ec31b01cd8add9bbf](https://github.com/magento/magento2/commit/e3f35b8e20960c6d9de1883ec31b01cd8add9bbf)
 - [62f94aad16b182eeaf4ddae5e48106340cc50dc4](https://github.com/magento/magento2/commit/62f94aad16b182eeaf4ddae5e48106340cc50dc4)

The fix will be available with the upcoming `2.3.5` release.

**Comment by magento-engcom-team** [comment]
Hi @swnsma, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [cd4a3eb409238de01508fc3afe5adf283f30ce98](https://github.com/magento/magento2/commit/cd4a3eb409238de01508fc3afe5adf283f30ce98)
 - [0d4bcfabdb87853c70cff0c07f9bce82f6eb877b](https://github.com/magento/magento2/commit/0d4bcfabdb87853c70cff0c07f9bce82f6eb877b)
 - [461f38973a91a6a79924af082c43919ddd777042](https://github.com/magento/magento2/commit/461f38973a91a6a79924af082c43919ddd777042)
 - [e3f35b8e20960c6d9de1883ec31b01cd8add9bbf](https://github.com/magento/magento2/commit/e3f35b8e20960c6d9de1883ec31b01cd8add9bbf)
 - [62f94aad16b182eeaf4ddae5e48106340cc50dc4](https://github.com/magento/magento2/commit/62f94aad16b182eeaf4ddae5e48106340cc50dc4)

The fix will be available with the upcoming `2.3.5` release.

**Comment by PhilipRowe** [comment]
Hi @magento-engcom-team the links to the related commits above go to a 404 page. Could I have a link to the code changes?

**Comment by magento-engcom-team** [comment]
Hi @swnsma, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [68170c1a4a7b8b849e3a19d40ffe37ae3ae06292](https://github.com/magento/magento2/commit/68170c1a4a7b8b849e3a19d40ffe37ae3ae06292)

The fix will be available with the upcoming `2.4.0` release.
