### ISSUE TITLE
Unable to set default layout

### ISSUE THREAD

**Issue by anujsingh1220** [magento/magento2#23841]
### Preconditions (*)

1. Magento version 2.3.x CE & EE
2. On product edit page we need to set "No Layout" as default. To do this we set the default option as "No layout" after edit that attribute. But the option is not set as default, once we create a product, it seems another option is selected rather than the default one.

### Steps to reproduce (*)

1. Choose another "Is default" value for "custom_layout" product attribute 
![image](https://user-images.githubusercontent.com/51680850/65854754-12050900-e366-11e9-8bfb-645e50cc1841.png)
2. Go to the "Create product" page and check value of "Layout" attribute 
### Expected result (*)

1. We was expecting that the "No Layout" should be the default layout.

### Actual result (*)

1. Finds "No layout" option by default rather than your chosen.
![image](https://user-images.githubusercontent.com/51680850/65854872-5db7b280-e366-11e9-83ee-4b6487e9c439.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20618` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento I am working on it.

**Comment by engcom-Echo** [comment]
@maheshWebkul721 , @anujsingh1220.

Unfortunately, this is not reproducible. That's why ...

![image](https://user-images.githubusercontent.com/51681435/83724786-886eaf00-a649-11ea-8c26-40f9694cd0d4.png)

We set the 'custom_layout' attribute, but check the value of the wrong attribute.
Attribute 'custom_layout', is used on 'Schedule Design Update' tab.

![Peek 2020-06-04 10-04](https://user-images.githubusercontent.com/51681435/83725816-3c246e80-a64b-11ea-8ed2-3980d9c23c41.gif)

**Comment by engcom-Echo** [comment]
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
