### ISSUE TITLE
Schedule currency_rates_update cron job not working

### ISSUE THREAD

**Issue by krzysztofkuzniar** [magento/magento2#23846]
### Preconditions (*)

1. Magento version 2.3.2
2. After configure currency schedule import settings cron job currency_rates_update not save in cron_schedule table.

### Steps to reproduce (*)

1. Go to admin panel
2. Stores > Configuration > General Tab > Currency Setup > Scheduled Import Setting section
3. Set values:
- Enable -> Set Yes
- Service -> Choose one of available services
- Start Time -> Fill 00 : 00 : 00
- Frequency -> Choose Daily
4. Run php bin/magento cron:run from command line and job currency_rates_update should be in cron_schedule table 

### Expected result (*)

1. Cron job currency_rates_update should be in cron_schedule table after run php bin/magento cron:run from command line

### Actual result (*)

1. Cron job currency_rates_update not exist in cron_schedule table after run php bin/magento cron:run from command line

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18543` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by brunoroeder** [comment]
#mm19br

**Comment by magento-engcom-team** [comment]
@brunoroeder thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @krzysztofkuzniar. Thank you for your report. 
The issue has been fixed in magento/magento2#24590 by @brunoroeder in 2.3-develop branch
Related commit(s):
 - [b63fd5e10d2f2dde7e73697c1d2247926a22d35e](https://github.com/magento/magento2/commit/b63fd5e10d2f2dde7e73697c1d2247926a22d35e)
 - [42b914147aef35512c3edc29dcc391dfb69b421f](https://github.com/magento/magento2/commit/42b914147aef35512c3edc29dcc391dfb69b421f)
 - [9fb9ce95d147162804cb5a383123d33b565be46a](https://github.com/magento/magento2/commit/9fb9ce95d147162804cb5a383123d33b565be46a)
 - [7f44d6d5e798b298363233140b1a32b171112c06](https://github.com/magento/magento2/commit/7f44d6d5e798b298363233140b1a32b171112c06)
 - [7dbd2cd38912811eeb1bd01c48a8f3dc625c789e](https://github.com/magento/magento2/commit/7dbd2cd38912811eeb1bd01c48a8f3dc625c789e)
 - [126a974d29846db430446878b03a4bac410f82fc](https://github.com/magento/magento2/commit/126a974d29846db430446878b03a4bac410f82fc)
 - [5494064565b27faff2fa975c3efd2c5df9ef3127](https://github.com/magento/magento2/commit/5494064565b27faff2fa975c3efd2c5df9ef3127)

The fix will be available with the upcoming 2.3.4 release.

**Comment by molotow11** [comment]
Hello,

We have Magento 2.3.5 and currency import suddenly stop working.
We have Scheduled Import Settings enabled with Fixer.io
It is nothing in logs, Error Email not sent.
We have nothing related with currency in mg_cron_schedule table.
