### ISSUE TITLE
catalog_product_entity_decimal table's  column name `entity_id` is changed to `row_id` in magento 2.3.2

### ISSUE THREAD

**Issue by 619frank** [magento/magento2#23849]
catalog_product_entity_decimal table's  column name `entity_id` is changed to `row_id` in magento 2.3.2
but its usage is not changed

example 
getAttributeValueCount() in Magento\Catalog\Model\ResourceModel\Product\Collection

**Comment by engcom-Charlie** [comment]
Hi, @619frank ! I can't confirm this issue because in my database catalog_product_entity_decimal table have entity_id and not row_id(screenshot attached). I tested it on fresh 2.3.2 magento. So i close it. 
Thank you for contributing!
![image](https://user-images.githubusercontent.com/51680850/61788559-09023380-ae1b-11e9-9841-fff4fbf112df.png)
