### ISSUE TITLE
system.xml file validation issue

### ISSUE THREAD

**Issue by Gurdit** [magento/magento2#23899]
### Preconditions (*)

1. Magento commerce 2.3.2
2. Nginx server
3. Php 7.2

### Steps to reproduce (*)

1. In system.xml if you forgot to add label tag in inside field tag, your config will be locked as cache and it will not save any value to the database. as shown below:
`<field id="example_id" translate="label" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="1">            <frontend_model>[vendor]\[module]\Block\Adminhtml\Form\Field\Ranges</frontend_model>
</field>`
2. devdocs refrence url : https://devdocs.magento.com/guides/v2.3/ext-best-practices/tutorials/dynamic-row-system-config.html

### Expected result (*)

1. It should show an error message or log an error that vendor/module/etc/system.xml file is invalid.

### Actual result (*)

1. Config will be locked as cache and it will not save any value to the database. And will show the success message your configuration is saved.

**Comment by Gurdit** [comment]
yes

**Comment by Gurdit** [comment]
@magento yes

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18668` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @Gurdit. Thank you for your report. 
The issue has been fixed in magento/magento2#25985 by @AndreyChorniy in 2.4-develop branch
Related commit(s):
 - [c273067b6a6236883ff623f40589b298c461692d](https://github.com/magento/magento2/commit/c273067b6a6236883ff623f40589b298c461692d)
 - [eb408932576b485b668d8c44b0e2bacdda764eff](https://github.com/magento/magento2/commit/eb408932576b485b668d8c44b0e2bacdda764eff)
 - [cfd7771232d328da6c5ed6903b53984e06b027e7](https://github.com/magento/magento2/commit/cfd7771232d328da6c5ed6903b53984e06b027e7)
 - [1308074fca71dcd246d30d1c945c599fbca0e525](https://github.com/magento/magento2/commit/1308074fca71dcd246d30d1c945c599fbca0e525)
 - [5e6c59522154c4c72db3d6f2472869bf33657cd8](https://github.com/magento/magento2/commit/5e6c59522154c4c72db3d6f2472869bf33657cd8)
 - [f30a06a6695f590f261953d2b576efcb1ce512a3](https://github.com/magento/magento2/commit/f30a06a6695f590f261953d2b576efcb1ce512a3)

The fix will be available with the upcoming 2.4.0 release.
