### ISSUE TITLE
No validation  "Minimum Qty" on "Minimum Qty Allowed in Shopping Cart" field

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23895]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to "Store->Configurations->Catalog->Inventory"
2. Uncheck "Use system value" on "Minimum Qty Allowed in Shopping Cart" (Product Stock Options)
3. "Add Minimum Qty", leave them empty
![image](https://user-images.githubusercontent.com/8234209/61917819-21886000-af79-11e9-8b17-d2c556c203eb.png)
4. Save configuration
5. Fill "Five" to field
6. Save configuration

### Expected result (*)

1. Can not save with empty and not number qty

### Actual result (*)

1. Leave min qty Empty => can save and BUT when page reloads-> **NO RECORD**
2. Not a number => can save

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18654`, `MC-18655` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sidolov** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23896 by @edenduong in 2.3-develop branch
Related commit(s):
 - [d718dc0044e829a0e2f44adae8af35537e1f5cd8](https://github.com/magento/magento2/commit/d718dc0044e829a0e2f44adae8af35537e1f5cd8)
 - [aa02d5c1d68d95b53e7824630a2cdb81cd884a7f](https://github.com/magento/magento2/commit/aa02d5c1d68d95b53e7824630a2cdb81cd884a7f)
 - [0c768f06f8959d3342e34362063a2e2d36e77c10](https://github.com/magento/magento2/commit/0c768f06f8959d3342e34362063a2e2d36e77c10)

The fix will be available with the upcoming 2.3.3 release.
