### ISSUE TITLE
Price attribute is enabled for dynamic price type on bundle product edit page in admin

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#23890]
### Preconditions (*)

1. Magento 2.3.1 CE

### Steps to reproduce (*)

1. go to admin panel Stores -> Configuration -> Catalog -> Catalog -> Product Alerts, enable either Allow Alert When Product Comes Back in Stock = Yes or Allow Alert When Product Price Changes
2. go to Catalog -> Products, edit bundle product with Dynamic price type

### Expected result (*)

1. Price attribute should be disabled, since Dynamic price is enabled
![image](https://user-images.githubusercontent.com/10142848/61887008-71c7d980-af09-11e9-9470-8a8052553e49.png)

### Actual result (*)

1. Price is enabled
![image](https://user-images.githubusercontent.com/10142848/61887112-a63b9580-af09-11e9-9b7a-39a00776b5f3.png)

### Reason
After some debugging I found that issue is in vendor/magento/module-bundle/Ui/DataProvider/Product/Form/Modifier/BundlePrice.php line 64 the code snippet 
`$this->arrayManager->findPath(
                ProductAttributeInterface::CODE_PRICE,
                $meta,
                null,
                'children'
            )`
returns `alerts/children/price/arguments/data/config` (because Alerts feature is enabled), instead of `product-details/children/container_price/children/price/arguments/data/config` that is the actual path of price attribute, as result the attribute field in not being disabled

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18660`, `MC-18661` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @katesuykovskaya. Thank you for your report. 
The issue has been fixed in magento/magento2#24077 by @arushibansal013 in 2.3-develop branch
Related commit(s):
 - [7170102b50c589b4bc92ca4125afd906dcf4e559](https://github.com/magento/magento2/commit/7170102b50c589b4bc92ca4125afd906dcf4e559)
 - [87732f34eb8ee030147c7f12d6ee66f3044493a1](https://github.com/magento/magento2/commit/87732f34eb8ee030147c7f12d6ee66f3044493a1)
 - [375efd1aeaa492639a7c6ba0efc64b750433fc70](https://github.com/magento/magento2/commit/375efd1aeaa492639a7c6ba0efc64b750433fc70)
 - [035800e69413d66df8ae901f3ab244c46ee51706](https://github.com/magento/magento2/commit/035800e69413d66df8ae901f3ab244c46ee51706)
 - [19515786a9296e697c789c0a06df8352dd79d12a](https://github.com/magento/magento2/commit/19515786a9296e697c789c0a06df8352dd79d12a)
 - [09cd623cc03f28b2fafdc9f497e8c606c45de23e](https://github.com/magento/magento2/commit/09cd623cc03f28b2fafdc9f497e8c606c45de23e)

The fix will be available with the upcoming 2.3.4 release.
