### ISSUE TITLE
Propose to rename the «frontend_model» backend configuration field tag to something like «renderer» because it is not a model at all

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2390]
I know that the [`frontend_model`](https://mage2.pro/t/219) is a legacy name from Magento 1.x and is used for 8 years but why to use it for another 8 years?
Actually it is not a model at all. It is a renderer, it should be an instance of `\Magento\Framework\View\Element\AbstractBlock` and should implement the `\Magento\Framework\Data\Form\Element\Renderer\RendererInterface`.

**Comment by shiftedreality** [comment]
Hi @dfediuk 

I created internal ticket MAGETWO-47914 for investigation this case

**Comment by orlangur** [comment]
Hi @dmitry-fedyuk,

I don't know what was the reason for such naming 8 years ago, now some models do appear on frontend in fact with KnockoutJS and such :)

Anyway this is something pretty hard to fix after 2.0 GA release due to backward compatibility constraints. Technically it is possible but the value of such renaming looks doubtful to me considering efforts needed to get this done.
