### ISSUE TITLE
No auto-focus after validation at "Create Configurations" button => User can not see the error message

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23904]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Catalog->Products
2. Add Products
3. Scroll to **Create Configurations**
![image](https://user-images.githubusercontent.com/8234209/61950937-a1dead80-afd9-11e9-96a9-6624f4f4036d.png)
4. Click the button **Create Configurations**

### Expected result (*)

1. Validate: Invalid, auto focus to the error fields

### Actual result (*)

1. Validate: Invalid, but **No Focus to the error => User can not see the error message**

![nofocus](https://user-images.githubusercontent.com/8234209/61951120-347f4c80-afda-11e9-8101-acca70a95b86.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18669`, `MC-18670` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23905 by @edenduong in 2.3-develop branch
Related commit(s):
 - [039ea7759d1c09990bd7a068e29840cf7ba5e124](https://github.com/magento/magento2/commit/039ea7759d1c09990bd7a068e29840cf7ba5e124)

The fix will be available with the upcoming 2.3.3 release.
