### ISSUE TITLE
escapeUrl - Magento XSS issue

### ISSUE THREAD

**Issue by nagrgk** [magento/magento2#23914]
### Preconditions (*)
please note that magento layered navigation has XSS issue because layer url has not been escaped with escapeUrl. Please help to add fix immediately in core product
1. this is escapeUrl issue
![escapeUrl](https://user-images.githubusercontent.com/2674815/61989506-098d0b00-b063-11e9-8055-ca6ec81ca7e3.PNG)

### Steps to reproduce (*)
left filter with swatches, link, label need to be escaped with escapeURL or escapeHTML

### Expected result (*)

1. having escapeUrl to escape url links and label
2. ![escapeUrl-after-fix](https://user-images.githubusercontent.com/2674815/61989512-1a3d8100-b063-11e9-94f4-1ba422aaa241.PNG)

### Actual result (*)

1. escapreUrl with html, produces QSS issue, with double quotes not escaped

file name: vendor/magento/module-swatches/view/frontend/templates/product/layered/renderer.phtml

**Comment by hostep** [comment]
Hi @nagrgk 

I've seen a bunch of commits landing on the `2.3-develop` branch in the last couple of weeks  fixing not escaping output all over the Magento codebase.
The problem you mentioned was fixed in: https://github.com/magento/magento2/commit/50329e21a45254eb210dc8293bbc5705fd866c19#diff-f4e3f76f4cf865522b96b664b0a390ac

My guess is that Magento 2.3.3 will contain these fixes (release date is supposed to be around the end of September 2019).

Let's close this issue, but thanks for reporting!
