### ISSUE TITLE
Authorize Net issue on the admin order creation page

### ISSUE THREAD

**Issue by eermolaev** [magento/magento2#23934]
### Preconditions (*)

1. Install Magento 2.3.2
2. Enable a few shipping methods, more than 1 method should be available in your store
3. Configure Authorize Net setting, only this payment should be available in your store

### Steps to reproduce (*)

1. Go to the admin area
2. Start the order creation process: choose customer and products
3. Choose one of the shipping methods (few methods must be available on this page)
4. Put credit card data information in the payment form (only the Authorize.Net method should be available on this page)
5. Click the "Create order" button

### Expected result (*)

1. Order created successfully

### Actual result (*)

1.  Order not created, I got the following error message: "Transaction has been declined. Please try again later."

Additionally, when I put cc info again here - order was created successfully (I copy-paste the same cc data).

![authorize net_issue](https://user-images.githubusercontent.com/1344077/62035656-51499900-b201-11e9-91fc-f965e367fe10.gif)

Log file:
[payment.log](https://github.com/magento/magento2/files/3441174/payment.log)

It looks like Magento refresh payment form when I choose shipping and miss some required payment data.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18714` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Hirenshah2011** [comment]
Hello,

Is there any update on this issue? we can't use authorize.net payment method in backend.
https://magento.stackexchange.com/questions/285823/magento-2-admin-create-order-authorize-net-not-working

Please update ASAP.

**Comment by magento-engcom-team** [comment]
Hi @eermolaev. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [78d225e5190e013550c33949655e955c0aa7634f](https://github.com/magento/magento2/commit/78d225e5190e013550c33949655e955c0aa7634f)

**Comment by magento-engcom-team** [comment]
Hi @eermolaev. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [f9a510a10ed9cf8a3c8a1f0f4ffd374b59333f82](https://github.com/magento/magento2/commit/f9a510a10ed9cf8a3c8a1f0f4ffd374b59333f82)

The fix will be available with the upcoming `2.4.0` release.

**Comment by bineet-kumar** [comment]
Hello,

Please provide any update on this issue? 
We can't use authorize.net payment method in backend. Please provide a solution for Magento 2.3.2.
https://user-images.githubusercontent.com/1344077/62035656-51499900-b201-11e9-91fc-f965e367fe10.gif
I'm facing the similar issue.

Please update ASAP.
