### ISSUE TITLE
Credit Memo - doesn't recalculate tax

### ISSUE THREAD

**Issue by asim-vax** [magento/magento2#23938]
If an order is placed for $65.00 (incl tax) and we want to refund the customer $5. We set adjustment fee to $60.00 ($5 refunded).

The totals appear correct, but the tax on the credit memo is the tax from original order, not the tax on the refund.

The tax needs to be recalculated for credit memo, as we must be able to refund tax properly.

related issue:
https://github.com/magento/magento2/issues/7937
(closed - even though this issue still exists)

### Preconditions (*)
1. magento 2.3.2, latest version 2.4
2. ubuntu 19.04
3. php 7.2

### Steps to reproduce (*)
1. place an order with tax
![Screenshot from 2019-07-29 13-41-14](https://user-images.githubusercontent.com/4798940/62049198-9d4b0c80-b206-11e9-8bcd-47ba417c9ec8.png)
($10 is relevant further down)
2. go into admin and credit memo the order
3. set adjustment fee to new total for the order (original total - refund amount)
4. view credit memo created
![Screenshot from 2019-07-29 13-38-30](https://user-images.githubusercontent.com/4798940/62049008-2f9ee080-b206-11e9-8640-47638f5da9f4.png)

How can the tax be $10 on a $5 refund? This needs to be fixed to recalculate tax on the refund.

### Expected result (*)

1. Tax is recalculated upon creating credit memo

### Actual result (*)

1.Tax is not recalculated upon creating credit memo

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18737`, `MC-18738` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ghost** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MrGangola-Webkul, here is your [Magento instance](https://i-23938-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23938-2-3-develop.instances.magento-community.engineering/admin](https://i-23938-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by luisgsoft** [comment]
Any news? This is a critical bug, We cannot make legal credit invoices with corrections

**Comment by webtekindo** [comment]
I totally agree, we works with Magento since it exists and there was never any solution for that problem. We cannot do legal accounting in current situation.

**Comment by luisgsoft** [comment]
I cannot understand how a bug of this importance can be on hold for a year.

**Comment by tropilex** [comment]
Why is this not fixed yet? It's quite important that we/everyone send the legal credit invoices.

**Comment by webtekindo** [comment]
Why it's closed? Already fix ?

**Comment by sprankhub** [comment]
@sdzhepa could you please shed some light on this? This is still an important issue!

**Comment by sdzhepa** [comment]
Hello @webtekindo @sprankhub 

The issue was closed by mistake. After closing the internal issue that was related for 2.2x version only.

Sorry for the confusion.

I reopen this issue. It should be reverified on the latest `2.4-develop` code.

@engcom-Oscar  Could you please recheck this issue on the latest `2.4-develop`
if its still actual please do
- Update description with latest version 2.4
- Update steps to be more clear(if applicable)
- set label "repro on: 2.4.x"
- set label "Issue: Confirmed"


But if this issue is not repro on the latest code(e.g. only on 2.3.x) - the issue should be closed. 
We are not able to process and deliver into 2.3.x through this public repository

**Comment by magento-engcom-team** [comment]
@engcom-Oscar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37422` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by webtekindo** [comment]
@engcom-Oscar I see you label this as a feature request. But this is not a feature, it's a big issue and requirement to make any legal accounting with Magento, and that since Magento exists. 

This situation put all users (at least European) in a situation where we do not not comply to the law with incorrect refund invoice sent to customer. 

So maybe a little more attention to that issue will be much appreciated by the community and our accountants.

**Comment by tropilex** [comment]
Agree to @webtekindo. Without being this solved there is no way Magento complies with the EU Law!

**Comment by webtekindo** [comment]
@asim-vax @luisgsoft @tropilex @sprankhub  did you somehow manage to find a trick, a patch, or an extension that solves that problem?

As it looks like it won't be solved any time soon by Magento.

**Comment by sprankhub** [comment]
For M1, we basically use https://magento.stackexchange.com/a/173992/142 / https://gist.github.com/Schrank/896561c841f564efb003c87441e90a4e for some clients. We did not implement it for M2 yet, but it may be pretty similar (not sure).

**Comment by asim-vax** [comment]
Unfortunately no, we still use credit memo functionality - but it is wrong. Thanks @sprankhub we will take a look at this.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37422` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
@asmin-vax @webtekindo
Unfortunately, I can't reproduce this behaviour. I got the next result:

![screenshot_5](https://user-images.githubusercontent.com/51681435/100714309-433ff580-33be-11eb-9487-1ddbabaa765e.png)
----------------------------
![screenshot_6](https://user-images.githubusercontent.com/51681435/100714317-46d37c80-33be-11eb-9067-ee7a4645c9ed.png)
----------------------------
![screenshot_7](https://user-images.githubusercontent.com/51681435/100714328-4935d680-33be-11eb-8cf3-630a58a88aec.png)
----------------------------
![Peek 2020-11-16 11-58](https://user-images.githubusercontent.com/51681435/100714248-2acfdb00-33be-11eb-9962-a6fdfd12cc47.gif)
----------------------------
This was expected - [User guide](https://docs.magento.com/user-guide/sales/credit-memo-create.html)
`For Adjustment Fee, enter a value to be subtracted from the total amount refunded.
This amount is not subtracted from a specific section of the order such as shipping, items, or tax.`

Please provide additional information(steps) to reproduce an issue.

**Comment by webtekindo** [comment]
@engcom-Echo 

Ok let's take an example, of legal accounting in Europe. 

**Sale Order**
1 x Product A (taxable at 20%) = 100 euros (incl.tax)
Tax = **16.67 euros**
Total = 100 euros

We want to refund that customer 50%.

**Credit memo**
1 x Product A = 50 euros
Tax = **8.33 euros (THIS IS CORRECT)**
Total = 50 euros

That's what any european accountant expect. Then my question will be how you do that in Magento ?

Let's try:

**Credit memo Test 1**
0 x Product A = 0 euros
Adjustment Refund = 50 euros
Tax = **0 euros (THIS IS WRONG)**
Total = 50 euros


**Credit memo Test 2**
1 x Product A = 100 euros
Adjustment Fee = 50 euros
Tax = **16.67 euros (THIS IS WRONG)**
Total = 50 euros

For business where transactions are without taxes Adjustment Refund/Fee works perfectly, and probably nothing to change here like you mention:

`For Adjustment Fee, enter a value to be subtracted from the total amount refunded. This amount is not subtracted from a specific section of the order such as shipping, items, or tax.`

The only possible correct solution to make legal accounting in Magento is to add the possibility to set custom price by credit memo line item. As different products can have different taxes, then the taxes can be calulcated correctly.

Please consult with an accountant if it's not clear. This is not a bug, this is a logic problem! 

Thank you.

**Comment by sreichel** [comment]
It is sad that Magento fails to fix this serious bug in many years ... it should be fixed ASAP.

**Comment by webtekindo** [comment]
Here we are again, why it's closed without any solution?

**Comment by Rickertje** [comment]
There a tens of issues describing this same problem dating back to the first release of M1 ten years ago. Now why is this issue closed (again) and what is the status of this problem ?? This is so tiring.

**Comment by toddliningerdesign** [comment]
It is absurd that this has not been fixed yet. This is a huge issue that goes back to the beginning of Magento! It should not be closed until it is fixed, and it should have been fixed years ago!

**Comment by webtekindo** [comment]
I have tried for years to open issues about it since Magento 1 and these always have been closed with no explanation. It makes no sense to me.

**Comment by tropilex** [comment]
Why is this closed? The issue is still there.

**Comment by hostep** [comment]
@sidolov: like discussed on Slack, could you talk to the product owner about this ticket again?

I believe the correct solution might be found in @webtekindo's answer:
> The only possible correct solution to make legal accounting in Magento is to add the possibility to set custom price by credit memo line item. As different products can have different taxes, then the taxes can be calulcated correctly.

The adjustment fee field currently doesn't know to which line(s) of a credit memo it should apply to (which one of the products, or shipping, ...) so it doesn't know which tax should be used for calculations. Therefore it makes sense that it doesn't calculate taxes.
But if we would have an extra field per line in the creditmemo for an additional fee/refund (or to enter a custom price), it would become do-able to figure out the correct taxes since it will be linked to a certain line of the creditmemo.

Thanks!

**Comment by twosg** [comment]
Please reopen this issue.

**Comment by Rickertje** [comment]
I noticed before that once an issue is closed the only way to get things restarted is to open a copy.

**Comment by hostep** [comment]
@Rickertje: I've talked to @sidolov on Slack some hours ago and he's getting a product owner involved here. So it might get re-opened soon-ish...

**Comment by toddliningerdesign** [comment]
Thanks, @hostep. Let's hope your efforts are not in vain.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and Tax is not recalculated for credit-memo:
![image](https://user-images.githubusercontent.com/60198231/155702463-a23cbebd-2007-4648-8967-1656a5ed34f8.png)

**Comment by Rickertje** [comment]
Any news anybody? The issue is still not reopend.

**Comment by Rickertje** [comment]
@hostep? @sidolov?

**Comment by engcom-November** [comment]
Reopening the ticket as Tax is not recalculated for credit-memo created with adjustment fee.

**Comment by vernard** [comment]
I made a quickfix for this. It's not a solution for everyone, but it's something that works for us. Hopefully it works for your case too.

What I did is create a plugin on Credit Memo's Grand Total Collector class, and if it detects that there's only a single tax rate used in that order (non-zero), it will use that tax rate on the adjustment amounts.

Here's the code for that plugin.

```
// Replace with your own module name
namespace Luz\AdminPanelOverrides\Model\Sales\Model\Order\Creditmemo\Total;

class Grand
{
    public function aroundCollect(
        $subject,
        \Closure $proceed,
        \Magento\Sales\Model\Order\Creditmemo $creditmemo
    ){
        $result = $proceed($creditmemo);

        $order = $creditmemo->getOrder();

        $tax_percent = null;
        foreach ($order->getAllItems() as $item) {
            if(is_null($tax_percent)) {
                $tax_percent =  $item->getTaxPercent();
                continue;
            }

            if($tax_percent != $item->getTaxPercent() && $item->getTaxPercent() != 0) {
                return $result; // If there are two items with different non-zero tax rates, exit. We can't identify the tax amount if there are multiple rates.
            }
        }

        $adjustment_tax = ((double)$tax_percent/100) * $creditmemo->getAdjustment();
        $creditmemo->setAdjustment($creditmemo->getAdjustment() - $adjustment_tax);

        $base_adjustment_tax = ((double)$tax_percent/100) * $creditmemo->getBaseAdjustment();
        $creditmemo->setBaseAdjustment($creditmemo->getBaseAdjustment() - $base_adjustment_tax);

        $creditmemo->setTaxAmount($creditmemo->getTaxAmount() + $adjustment_tax);
        $creditmemo->setBaseTaxAmount($creditmemo->getBaseTaxAmount() + $base_adjustment_tax);

        $creditmemo->setGrandTotal($creditmemo->getGrandTotal() - $adjustment_tax);
        $creditmemo->setBaseGrandTotal($creditmemo->getBaseGrandTotal() - $base_adjustment_tax);

        return $result;
    }
}
```

And just setup the plugin in di.xml:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Sales\Model\Order\Creditmemo\Total\Grand">
        <!-- Replace with your own module name -->
        <plugin name="luz_adminpaneloverrides_model_sales_model_order_creditmemo_total_grand" type="Luz\AdminPanelOverrides\Model\Sales\Model\Order\Creditmemo\Total\Grand"/>
    </type>
</config>
```

We only have different rates for each countries and all our products are taxed the same way.

There might be some edge cases like: 
- Calculated tax amount exceeding the tax charged to customer if you refunded more than what customer paid)
- This code only takes the adjustment refunds and calculates tax inclusively. 

So use this at your own risk.

Hope that helps.

**Comment by twosg** [comment]
> Tax is calculated and applied at order creation and does not change, even when a credit memo is created.

That is totally fine for the order. But a credit memo and a invoice are different documents and should have their own tax calculated according to the contents (items) of the invoice or credit memo.

**Comment by constancyGmbH** [comment]
I agree with @twosg 
Say we have an order of a total of 50$. If tax is 19%, ordertax should be 7,98$.
If I refund 10$ the tax on the creditmemo should state 1,60$, regardless of the tax that is calculated in the order.
Like @twosg said, it is not necessary to recalculate the ordertax, just the tax stated on the creditmemeo should be correct!

**Comment by pvalium** [comment]
Agree totally with @constancyGmbH

**Comment by tropilex** [comment]
@constancyGmbH is right. There should always be tax calculated on the adjustment fee. Or (as a suggestion) it must be possible to adjust the product price on the credit invoice. So Magento can use the tax setting for that product. And we do need to use the adjustment fee.

**Comment by constancyGmbH** [comment]
sorry @toddliningerdesign but this is not the correct way. Taxes should *never* be recalculated! The order itself is fixed at the time it is placed. The problem that we describe is, that on an refund the tax on the creditmemo is not only the tax calculated from the refund amound, but alway the tax from the original order.

But if this is solved, your problem is also solved. If your client refunds just the discount amount as adjustment refund than the tax should only be calculated for that refund amount.

**Comment by toddliningerdesign** [comment]
Yes, my wording was wrong. I didn't mean to indicate that anything should be changed on the original order. We're all after the same thing here: the ability to accurately calculate and log the amount of taxes being refunded when issuing a partial refund rather than the entire purchase price. Thanks, @constancyGmbH, for clarifying!

**Comment by Rickertje** [comment]
I dont want to be rude but this issue has been put under the attention of product dev I guess a 2-dozen times since the dawn of Magento 1.0. In the EU VAT should be calculated for a refund amount no matter what kind of refund. Period. Maybe a product owner with more understanding of how taxes work in EU can take a look at this? Pretty frustrating guys.

**Comment by webtekindo** [comment]
It would be great if we could find a copy of a partial credit memo from Adobe to a customer in the EU, then 2 outputs their credit memo is not EU compliant (which I doubt) or they will understand what we all mean since all these years.

**Comment by atIOCrON** [comment]
> We got confirmation from our Product Owner that this is an expected behavior but not a bug. Tax is calculated and applied at order creation and does not change, even when a credit memo is created. What will change is how much tax the merchant owes to the government, but it does not look like this is the scope of this issue. Hence we are closing this issue.

@engcom-November please reopen this issue. As countless others have told you, when you create a credit memo tax must be calculated, otherwise, the credit memo is not tax compliant.

You even said yourself, "what will change is how much tax the merchant owes to the government" proving that tax must be calculated on the credit memo so we can know how much tax we owe the government.

You also said "Tax is calculated and applied at order creation" which is correct. This is the order tax, however, it also needs to be calculated and applied at credit memo creation because the "Adjustment Fee" and "Adjustment Refund" fields are not available at order creation so no tax has been calculated on them yet.

When creating a credit memo, tax needs to be calculated for that refund. It can be pulled from the order for the items and delivery but for "Adjustment Fee" and "Adjustment Refund" it needs to be calculated since these are new fields.

If Magento has no intention of making these fields tax compliant they should be removed entirely.

**Comment by NicolasDoyer** [comment]
Same issue here.
I'm using @vernard solution but it would be great to have a prestashop like feature :

![image](https://user-images.githubusercontent.com/23630393/221804572-43f16dfe-59bf-4df4-a508-8ee08037634d.png)

As you can see, the partial refund can be adjust on each item which is more flexible and "EU VAT compliant".

**Comment by simonmaass** [comment]
has anyone found a solution for this in any way? this is a hugh problem for any merchant in the EU!
