### ISSUE TITLE
Card stored for customers despite Vault being disabled in Payment config

### ISSUE THREAD

**Issue by ghost** [magento/magento2#23949]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Ensure vault is disabled for Braintree
2. Create customer account and login
3. Order a product and use Credit Card via Braintree (note that no option to save card is present)
4. Goto account and click Store Payment Methods

### Expected result (*)

1. No stored payment methods should exist

### Actual result (*)

1. Previously used card is stored in customers account

**Comment by ghost** [comment]
Related to https://github.com/magento/magento2/issues/23946

**Comment by paul-gene** [comment]
Reproduced on 2.3.x

**Comment by engcom-Bravo** [comment]
Hello again @paul-gene. We followed the steps You provided in this issue and here is what we have after the the order has been placed:
![Screenshot from 2019-07-31 12-48-37](https://user-images.githubusercontent.com/51680745/62202430-f4311d00-b391-11e9-8be4-d8376d92d15f.png)

**Comment by ghost** [comment]
It's fixed in 2.3-develop by https://github.com/magento/magento2/pull/19767

It affects 2.3.1 and I imagine any 2.2.x version.

The reason is because the default value set for `is_visible` is set to 1 for some odd reason. The logic in the vault observer uses a check to see if the "save for later" value is set, which it isn't if you have the vault option turned off in the Braintree config. The above PR addresses this.

What can we do about 2.3.1 and 2.2x?

**Comment by engcom-Bravo** [comment]
Hello @paul-gene. `2.2-develop` branch was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details. As for 2.3.x versions - if the bug has been fixed in current develop version this fix becomes available only starting from the next release version. Thank You for applying.

**Comment by ghost** [comment]
@engcom-Bravo does that mean 2.2 will never get fixed?

**Comment by engcom-Bravo** [comment]
Yes @paul-gene, unfortunately it means exactly that. I'm not sure if it equally concerns Enterprise Edition as well, but as for Community Edition (this repository is intended for) everything is just like that.
