### ISSUE TITLE
Disable Guest Checkout if Cart Contains Downloadable Items doesn't work correctly

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#23971]
### Preconditions (*)

1. Magento version 2.3.2
2. Php version: 7.2.19

### Steps to reproduce (*)

1. navigate to backend->stores->configuration->catalog->Downloadable Product Options
2. Set Shareable -> No and Disable Guest Checkout if Cart Contains Downloadable Items -> No
![downloadable-product-issue](https://user-images.githubusercontent.com/44425160/62280272-37aa8a80-b469-11e9-9a6e-9fa6ac016e09.png)

### Expected result (*)

1. Guest checkout must be disabled if cart contains downloadable products.

### Actual result (*)

1. Guest checkout is enabled

**Comment by ktpl-rammohan** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rammohan-krish, here is your [Magento instance](https://i-23971-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23971-2-3-develop.instances.magento-community.engineering/admin](https://i-23971-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@rammohan-krish Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by ktpl-rammohan** [comment]
Issue Reproduced on develop 2.3 instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rammohan-krish 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19009` were created

**Issue Available**: @rammohan-krish, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#23972 by @rani-webkul in 2.4-develop branch
Related commit(s):
 - [548ea7b21c772587e8428d6f57dc506be64a78e7](https://github.com/magento/magento2/commit/548ea7b21c772587e8428d6f57dc506be64a78e7)
 - [1cf138978ca83bb9ba313ac0c4f59b5f132b2151](https://github.com/magento/magento2/commit/1cf138978ca83bb9ba313ac0c4f59b5f132b2151)
 - [65cf71b5bd3539ab9b7a89bc293d8da2042df091](https://github.com/magento/magento2/commit/65cf71b5bd3539ab9b7a89bc293d8da2042df091)
 - [a1dd986c3830ef082d84ef0b9ad75fb68c683022](https://github.com/magento/magento2/commit/a1dd986c3830ef082d84ef0b9ad75fb68c683022)
 - [c3e1ce024a233131764970d8ba31ca5b00fcce15](https://github.com/magento/magento2/commit/c3e1ce024a233131764970d8ba31ca5b00fcce15)
 - [caf9ef781155b4e26ab0d2ad7f7c21550376b35e](https://github.com/magento/magento2/commit/caf9ef781155b4e26ab0d2ad7f7c21550376b35e)
 - [98dd6c0298041f35831616f0252996e865d3643d](https://github.com/magento/magento2/commit/98dd6c0298041f35831616f0252996e865d3643d)
 - [9f37b2f3a283735257b8d3ff6df8132b1e7b68d8](https://github.com/magento/magento2/commit/9f37b2f3a283735257b8d3ff6df8132b1e7b68d8)
 - [993a1e5b31a939f21b7d9579dceb769eb7c33a58](https://github.com/magento/magento2/commit/993a1e5b31a939f21b7d9579dceb769eb7c33a58)
 - [575d9e5f1c4699d5aafe18d3b832a993bf4545e5](https://github.com/magento/magento2/commit/575d9e5f1c4699d5aafe18d3b832a993bf4545e5)
 - [c343492705059b0b97b89ff784ea8f07de5ff805](https://github.com/magento/magento2/commit/c343492705059b0b97b89ff784ea8f07de5ff805)
 - [4d045cd38b62f7882d6f77ff30f70de020d38754](https://github.com/magento/magento2/commit/4d045cd38b62f7882d6f77ff30f70de020d38754)
 - [05a33482da397f067b4b5166e47906b628bb74fc](https://github.com/magento/magento2/commit/05a33482da397f067b4b5166e47906b628bb74fc)
 - [9e9bc694ce17e354deebf92033d7681f16fad6c7](https://github.com/magento/magento2/commit/9e9bc694ce17e354deebf92033d7681f16fad6c7)
 - [4380ff6042714e74bc61d6549935543f225c1fb6](https://github.com/magento/magento2/commit/4380ff6042714e74bc61d6549935543f225c1fb6)
 - [f4eb33e7532e4c2e1050402efce6242f04dd5262](https://github.com/magento/magento2/commit/f4eb33e7532e4c2e1050402efce6242f04dd5262)
 - [11f21bf52d15d27972932f2f862c2d1d81f1ab4c](https://github.com/magento/magento2/commit/11f21bf52d15d27972932f2f862c2d1d81f1ab4c)
 - [59e7f33cfefabe48426acf88b567041340fd4a9c](https://github.com/magento/magento2/commit/59e7f33cfefabe48426acf88b567041340fd4a9c)
 - [49e2fa9d363f7b55d19c589c815eba1c3a2b3e78](https://github.com/magento/magento2/commit/49e2fa9d363f7b55d19c589c815eba1c3a2b3e78)
 - [5389a714ecf377f3598f08dcb97c3005b171462f](https://github.com/magento/magento2/commit/5389a714ecf377f3598f08dcb97c3005b171462f)
 - [938a68ccf07338227f3d11db228a355b8f9462aa](https://github.com/magento/magento2/commit/938a68ccf07338227f3d11db228a355b8f9462aa)
 - [08e3875f213e183b32b30744a52b948770ecfe35](https://github.com/magento/magento2/commit/08e3875f213e183b32b30744a52b948770ecfe35)
 - [4c50949baf6a9480e61ada602d142ff6c0b9109c](https://github.com/magento/magento2/commit/4c50949baf6a9480e61ada602d142ff6c0b9109c)
 - [af4b7406127dcb3dc7ec1430698b23b77c90dfec](https://github.com/magento/magento2/commit/af4b7406127dcb3dc7ec1430698b23b77c90dfec)
 - [592915dc507b8fa96e32bb6698ed9c182baf9932](https://github.com/magento/magento2/commit/592915dc507b8fa96e32bb6698ed9c182baf9932)
 - [4dac91ce16db0724201541e0ce19a3a452364c36](https://github.com/magento/magento2/commit/4dac91ce16db0724201541e0ce19a3a452364c36)
 - [4db017271f0c65f9f10f76a71ecfcc0c715f432c](https://github.com/magento/magento2/commit/4db017271f0c65f9f10f76a71ecfcc0c715f432c)
 - [f1e11eabd7bfd68e8a9bf0f8b5159ea0d706dbc4](https://github.com/magento/magento2/commit/f1e11eabd7bfd68e8a9bf0f8b5159ea0d706dbc4)
 - [88778bdaa8797e221490f360799760e872495f88](https://github.com/magento/magento2/commit/88778bdaa8797e221490f360799760e872495f88)
 - [63ad4a30723c6c7990731a725c5caaa049f1db7d](https://github.com/magento/magento2/commit/63ad4a30723c6c7990731a725c5caaa049f1db7d)
 - [88953acffdf5c0c270baa1b514c7bbbf4dce1e50](https://github.com/magento/magento2/commit/88953acffdf5c0c270baa1b514c7bbbf4dce1e50)
 - [11e34b33660f8c2ca1d399f1a0c538061090781d](https://github.com/magento/magento2/commit/11e34b33660f8c2ca1d399f1a0c538061090781d)

The fix will be available with the upcoming 2.4.1 release.
