### ISSUE TITLE
Reset not working properly in Add review from admin

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#23990]
### Preconditions (*)

1. magento 2.3

### Steps to reproduce (*)

1. Go to Admin
2. Marketing -> All Reviews -> New Review
3. Click any product
4. Fill all data
5. Click on Reset

### Expected result (*)

1. Review form should reset and stay on same page
2. 

### Actual result (*)

1. https://www.screencast.com/t/dT6oqMKkF

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18894` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by konarshankar07** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07, here is your [Magento instance](https://i-23990-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23990-2-3-develop.instances.magento-community.engineering/admin](https://i-23990-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your report. 
The issue has been fixed in magento/magento2#24318 by @konarshankar07 in 2.3-develop branch
Related commit(s):
 - [5f7029d71e06e96d8e5c8a6197ef9343c0151c17](https://github.com/magento/magento2/commit/5f7029d71e06e96d8e5c8a6197ef9343c0151c17)
 - [bd5a0122f9b7bc20f8e236f030b2ca2ced01adb2](https://github.com/magento/magento2/commit/bd5a0122f9b7bc20f8e236f030b2ca2ced01adb2)
 - [e115b067996b98e1412afe7129aa9933bda88711](https://github.com/magento/magento2/commit/e115b067996b98e1412afe7129aa9933bda88711)
 - [2f4f8e81a03a257c6d7a0e064e985775d391594e](https://github.com/magento/magento2/commit/2f4f8e81a03a257c6d7a0e064e985775d391594e)
 - [ea22c906a73d0482ae7c8e211c50036b77ddb187](https://github.com/magento/magento2/commit/ea22c906a73d0482ae7c8e211c50036b77ddb187)

The fix will be available with the upcoming 2.3.4 release.
