### ISSUE TITLE
Remove var Translator = new Translate... from every page

### ISSUE THREAD

**Issue by stalniy** [magento/magento2#24]
You must remove this JS because it's bad for SEO it's bad for mobile and it's bad for users that use 3G modems. I undestand that this code need for translations in JavaScript, but you can get it using AJAX! During page loading just send AJAX request to some controller that will return translations in JSON format. 
It will also decrease time of page loading.

And it's useful you may check this thread http://www.magentocommerce.com/boards/viewthread/9307/ .

**Comment by fredbrunken** [comment]
Guys, I am not even sure if this message will be seen, since this issue has been closed since 2012, but that is exactly the problem. We are coming to the end of 2015, 4 Years after the issue was considered as closed and I still have all this code on my 1.9.2.1 magento store. Any news on it? Will it be availbe on the new magento 2? thanks

**Comment by alankent** [comment]
Quite a lot has been done in the M2 code base since 2012! Have you had a look to see if your issue has been addressed?  Translations have been revamped in M2.

**Comment by fredbrunken** [comment]
Where can I get m2? thanks...

**Comment by xcomSteveJohnson** [comment]
Start here: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html
