### ISSUE TITLE
"Currency Converter API" notify "Notice: Undefined index" when import currency rate

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24007]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Store -> Currency Rate
3. "Import Service" choose "Currency Converter API"
4. Click "Import"

### Expected result (*)

1. Notify correct error message 

### Actual result (*)

1. "Notice: Undefined index"
![image](https://user-images.githubusercontent.com/8234209/62413653-a0e1f780-b63b-11e9-9a7f-bd1d0a8a4e08.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-24007-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24007-2-3-develop.instances.magento-community.engineering/admin](https://i-24007-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
I can reproduce the issue on vanilla Magento instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18928` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24008 by @edenduong in 2.3-develop branch
Related commit(s):
 - [e4f4701d360162f2d2aeffa1d252065857fd2573](https://github.com/magento/magento2/commit/e4f4701d360162f2d2aeffa1d252065857fd2573)
 - [405fbcbf49d0d380380246c4e0ebacb933cbdb54](https://github.com/magento/magento2/commit/405fbcbf49d0d380380246c4e0ebacb933cbdb54)
 - [90253073b0a1e5253eda0410f5f000c75351d752](https://github.com/magento/magento2/commit/90253073b0a1e5253eda0410f5f000c75351d752)
 - [23d566ba0357d8728d66847f4a9418bf258a6ad3](https://github.com/magento/magento2/commit/23d566ba0357d8728d66847f4a9418bf258a6ad3)
 - [3fbdb4d78b3b3c5270edd0b9b4b0fd909c41b254](https://github.com/magento/magento2/commit/3fbdb4d78b3b3c5270edd0b9b4b0fd909c41b254)
 - [a0113091c2f68ba357ec9366fbfc60509a51bb51](https://github.com/magento/magento2/commit/a0113091c2f68ba357ec9366fbfc60509a51bb51)

The fix will be available with the upcoming 2.3.4 release.
