### ISSUE TITLE
Customer email Address is not updated in quote and sales_order tables

### ISSUE THREAD

**Issue by dipak85shinde** [magento/magento2#24012]
Preconditions:
1)Magento version - 2.3.2
2)PHP version - 7.1.30
3)Customer should be registered. 

Steps to reproduce:
1.Login to customer account
2. Add some products to the cart
3)Now move to My Account page.
4)Go to Edit Account Information page & check Change Email checkbox
5)Now change your email address & save your account information
6)Now move to checkout & place Order
7)Repeat steps 2-6. (Do not simply change email to some third kind, but change it back to the first one. Thus the issue is reproduced anyway)

Expected result:
1. Once a customer changes the email address, It must be updated in the quote table.
2. If a customer place order in the same situation, the email address must be updated in sales_order table.

Actual result:
1. Email address is not updated in the quote table.
2. Also, email address not updated in sales_order table

**Comment by dipak85shinde** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dipak85shinde. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dipak85shinde, here is your [Magento instance](https://i-24012-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24012-2-3-develop.instances.magento-community.engineering/admin](https://i-24012-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nadroj467** [comment]
Issue relates to third party extension please close
Thanks

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18943` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @dipak85shinde. Thank you for your report. 
The issue has been fixed in magento/magento2#24049 by @UncleTioma in 2.3-develop branch
Related commit(s):
 - [917705090bea4930b987cc6ab3e1ef3e9a46b7fb](https://github.com/magento/magento2/commit/917705090bea4930b987cc6ab3e1ef3e9a46b7fb)
 - [a62f72b4a730d805d0dcaef40bdef1afa8f95f60](https://github.com/magento/magento2/commit/a62f72b4a730d805d0dcaef40bdef1afa8f95f60)
 - [7ef77d764545b55341a9f845ed9c928ecd3ba5ba](https://github.com/magento/magento2/commit/7ef77d764545b55341a9f845ed9c928ecd3ba5ba)
 - [766db37a12358315929dbe924e818436291bd1c1](https://github.com/magento/magento2/commit/766db37a12358315929dbe924e818436291bd1c1)
 - [b0ba2ac21446324072af6777c78126fd077c5eab](https://github.com/magento/magento2/commit/b0ba2ac21446324072af6777c78126fd077c5eab)
 - [e270394119c95f2d296830b6269f05f494291233](https://github.com/magento/magento2/commit/e270394119c95f2d296830b6269f05f494291233)
 - [cacbe13234626da990891694c521740750009b54](https://github.com/magento/magento2/commit/cacbe13234626da990891694c521740750009b54)

The fix will be available with the upcoming 2.3.4 release.
