### ISSUE TITLE
Better exception handling during cli commands

### ISSUE THREAD

**Issue by PascalBrouwers** [magento/magento2#24043]
### Preconditions (*)
1. Magento 2.3.x

### Steps to reproduce (*)

1. Have a module with a wrong path in registration.php. For example set the path in vendor/magento/module-catalog/registration.php to `__DIR__ . '/wrong_folder'`
2. Run `bin/magento setup:upgrade`

### Expected result (*)
1. A clear exception what actually goes wrong. Instead the general error `There are no commands defined in the "setup" namespace.` is displayed.

### Actual result (*)
1. The general error `There are no commands defined in the "setup" namespace.` is displayed.

Also see: https://github.com/magento/magento2/issues/4832

**Comment by PascalBrouwers** [comment]
Made a pull request to fix this issue

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. Thank you for your report. 
The issue has been fixed in magento/magento2#24044 by @PascalBrouwers in 2.3-develop branch
Related commit(s):
 - [9ffe7eb2d3e6fcbf18eb39b6b847e99b0550a028](https://github.com/magento/magento2/commit/9ffe7eb2d3e6fcbf18eb39b6b847e99b0550a028)
 - [2861ca40b7f550c9e8498603c9f3763b12350f90](https://github.com/magento/magento2/commit/2861ca40b7f550c9e8498603c9f3763b12350f90)
 - [cd9ff1e34d8b19094b056f9c5b35909a7633d739](https://github.com/magento/magento2/commit/cd9ff1e34d8b19094b056f9c5b35909a7633d739)

The fix will be available with the upcoming 2.3.4 release.

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. Thank you for your report. 
The issue has been fixed in magento/magento2#24734 by @p-bystritsky in 2.3-develop branch
Related commit(s):
 - [dfd481d22616708a7e55d7b8757581e90ba4f41c](https://github.com/magento/magento2/commit/dfd481d22616708a7e55d7b8757581e90ba4f41c)

The fix will be available with the upcoming 2.3.4 release.

**Comment by PascalBrouwers** [comment]
Actually @p-bystritsky is using my commit. Give credit where credit due.

**Comment by hostep** [comment]
Euhm https://github.com/magento/magento2/issues/24043#issuecomment-521728434 ? 😉
