### ISSUE TITLE
No asterisk symbol (required entry) when changing "Encryption Key"

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24098]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. System->Manage Encryption Key
3. "Auto-generate a Key" is No
4. Click "Change Encryption Key"

See:

![image](https://user-images.githubusercontent.com/8234209/62823316-1577e180-bbba-11e9-8b8e-38fefdd95d97.png)

### Expected result (*)

1. The field "New Key" should have the "asterisk symbol" as the required field

### Actual result (*)

1.  The field "New Key" doesn't have the "asterisk symbol". 
![image](https://user-images.githubusercontent.com/8234209/62823321-190b6880-bbba-11e9-84ab-77e68d24af3c.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19126` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24099 by @edenduong in 2.3-develop branch
Related commit(s):
 - [fa78bfaa752d6f2e970439f6826e6a66a869bc36](https://github.com/magento/magento2/commit/fa78bfaa752d6f2e970439f6826e6a66a869bc36)

The fix will be available with the upcoming 2.3.4 release.
