### ISSUE TITLE
Selected configurable product attribute options are not displaying in wishlist page.

### ISSUE THREAD

**Issue by venugopal-codilar** [magento/magento2#24091]
### Preconditions (*)

1. Magento 2.3.2 with sample data
2. Product listing page should have 2 or more configurable products with swatches.

### Steps to reproduce (*)

1. Log into the customer account.
2. Navigate to product listing page.
3. Choose the configurable product and select preferred color and size options of any product expect last product which is listed in Product listing page ( It is working fine for last product of the listing page).
4. Click on the wishlist icon of the product.

### Expected result (*)

1. On the Wishlist page, the selected configurable product options color and size should be visible. (See Details is available on the product, see this gif below
![SeeDetails](https://user-images.githubusercontent.com/51680745/62854791-0f3c4f00-bcf9-11e9-8664-ec1b08d91ff8.gif)
)

### Actual result (*)

1. The selected color and size is not visible in wishlist page.

![plp](https://user-images.githubusercontent.com/26595808/62786413-28b67e80-bae0-11e9-90f6-7b1f39c14bea.png)
![wishlist](https://user-images.githubusercontent.com/26595808/62786415-28b67e80-bae0-11e9-92ac-5a607eadd277.png)

**Comment by engcom-Bravo** [comment]
Hello @venugopal-codilar. Though the essence of the issue may seem obvious just from its title we would still ask You to fill in all the required items like Preconditions, etc. Thank You.

**Comment by venugopal-codilar** [comment]
@engcom-Bravo  Ticket updated

**Comment by venugopal-codilar** [comment]
@magento-engcom-team  give me 2.3-develop instance

**Comment by venugopal-codilar** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @venugopal-codilar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @venugopal-codilar, here is your [Magento instance](https://i-24091-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24091-2-3-develop.instances.magento-community.engineering/admin](https://i-24091-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jayankaghosh** [comment]
@magento-engcom-team Reproducible in Magento 2.3.2

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19139` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @venugopal-codilar. Thank you for your report. 
The issue has been fixed in magento/magento2#28157 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [a128f392b45f559316460962444bd4b1834e8f14](https://github.com/magento/magento2/commit/a128f392b45f559316460962444bd4b1834e8f14)
 - [e3bad69dc0d66d0eeb34eb180a4f415c25c3261e](https://github.com/magento/magento2/commit/e3bad69dc0d66d0eeb34eb180a4f415c25c3261e)
 - [536a728213fd4a36634dd958bbde243fe9154734](https://github.com/magento/magento2/commit/536a728213fd4a36634dd958bbde243fe9154734)
 - [3d69b132c603dbb0d04f3e8911b0b2a1416aed0e](https://github.com/magento/magento2/commit/3d69b132c603dbb0d04f3e8911b0b2a1416aed0e)
 - [75a5f2523643e89aa9226d92551021924c75e44f](https://github.com/magento/magento2/commit/75a5f2523643e89aa9226d92551021924c75e44f)
 - [0471e4e9bd296d6b4872cb450b6e95795060e928](https://github.com/magento/magento2/commit/0471e4e9bd296d6b4872cb450b6e95795060e928)
 - [2c07389f7cb3104378d6b49d3c2303a2b95de08c](https://github.com/magento/magento2/commit/2c07389f7cb3104378d6b49d3c2303a2b95de08c)
 - [e3e5a9af7054280a0a3fe47659a9c2bb911692a0](https://github.com/magento/magento2/commit/e3e5a9af7054280a0a3fe47659a9c2bb911692a0)
 - [e378086d6f1c0728afb2e2efbae9676c3522b3f3](https://github.com/magento/magento2/commit/e378086d6f1c0728afb2e2efbae9676c3522b3f3)
 - [11abbf95034a4cbbb317b6faad5e107098cad63d](https://github.com/magento/magento2/commit/11abbf95034a4cbbb317b6faad5e107098cad63d)
 - [ac6be807033e638e3098e5e0350b2990ecc2b236](https://github.com/magento/magento2/commit/ac6be807033e638e3098e5e0350b2990ecc2b236)
 - [8eead95b5580e1983e39584d18de1f67c92a09b2](https://github.com/magento/magento2/commit/8eead95b5580e1983e39584d18de1f67c92a09b2)
 - [e3fd2463dba30032f6777c926bba96a40f53730c](https://github.com/magento/magento2/commit/e3fd2463dba30032f6777c926bba96a40f53730c)
 - [129f4519eff38fef9deae4fca8b260996253ccbe](https://github.com/magento/magento2/commit/129f4519eff38fef9deae4fca8b260996253ccbe)
 - [8d025339e6df3bce298c231e920ddb243d44c95b](https://github.com/magento/magento2/commit/8d025339e6df3bce298c231e920ddb243d44c95b)
 - [840c99cb6422b9b320b1263c833e47f90a2af36b](https://github.com/magento/magento2/commit/840c99cb6422b9b320b1263c833e47f90a2af36b)

The fix will be available with the upcoming 2.4.2 release.
