### ISSUE TITLE
"Number of results" and "Number of Uses" in edit "Search Term" missing validate number 

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24100]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to frontend
2. At the right top, in "Search Entire Store Here", enter "gggg", and search
3. Go to Backend
4. Marketing->Search Terms
5. Choose record "gggg"
6. In "Number of results" and "Number of Uses", fill "one"
7. Click "Save Search"

![image](https://user-images.githubusercontent.com/8234209/62834954-29384c00-bc7d-11e9-9327-5cd0a5bb9887.png)

### Expected result (*)

1. Don't allow to save
### Actual result (*)

1. Can save normally

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @rogyar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19128` were created

**Issue Available**: @rogyar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24101 by @edenduong in 2.3-develop branch
Related commit(s):
 - [20f88ecc42140fe5ed504678ffa5de0e8a734cea](https://github.com/magento/magento2/commit/20f88ecc42140fe5ed504678ffa5de0e8a734cea)

The fix will be available with the upcoming 2.3.4 release.
