### ISSUE TITLE
Missing "expand/collapse" icon in paypal setting

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24118]
### Preconditions (*)

1. 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Stores->Configuration
3. Sales->Payment Methods
4. Check the screen. No "expand/collapse" icon

![image](https://user-images.githubusercontent.com/8234209/62930056-dcbc5000-bde5-11e9-842c-0f9f8b40b5a6.png)

### Expected result (*)

Have the icon:

![image](https://user-images.githubusercontent.com/8234209/62929885-8f3fe300-bde5-11e9-896c-c3461aaf8a6d.png)

### Actual result (*)

No icon:

![image](https://user-images.githubusercontent.com/8234209/62930004-c31b0880-bde5-11e9-8b9e-10197bdfb957.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19181` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by BharathN96** [comment]
give me magento 2.1 instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24119 by @edenduong in 2.3-develop branch
Related commit(s):
 - [2895106f48dcc6770ac9ec40c8069666a01d4b36](https://github.com/magento/magento2/commit/2895106f48dcc6770ac9ec40c8069666a01d4b36)

The fix will be available with the upcoming 2.3.4 release.
