### ISSUE TITLE
No validation Email in Store->Configurations->Sales->Sales Emails

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24137]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Stores->Configuration
3. Sales->Sales Emails
4. Fill: "testemail" in 
- Send Order Email Copy To
- Send Order Comment Email Copy To
- Send Invoice Email Copy To
- Send Invoice Comment Email Copy To
- Send Shipment Email Copy To
- Send Shipment Comment Email Copy To
5. Save config

### Expected result (*)

Validate:

![image](https://user-images.githubusercontent.com/8234209/63079104-b45c5f00-bf67-11e9-905b-52839a36ad24.png)

### Actual result (*)

No validation, still save no-email format

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19265` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24138 by @edenduong in 2.3-develop branch
Related commit(s):
 - [84bb72267bd9d8cd867a2f623b6b6a2df7924634](https://github.com/magento/magento2/commit/84bb72267bd9d8cd867a2f623b6b6a2df7924634)
 - [ebc508f6c20154fc74e0d36b84d188315b4e25be](https://github.com/magento/magento2/commit/ebc508f6c20154fc74e0d36b84d188315b4e25be)

The fix will be available with the upcoming 2.3.4 release.
