### ISSUE TITLE
"Action" column is not the last column in "Design Configuration"

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24139]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Content->Configuration
3. Check the grid

### Expected result (*)

![image](https://user-images.githubusercontent.com/8234209/63081023-c12f8180-bf6c-11e9-8324-c69f707c8d11.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/63080884-6ac24300-bf6c-11e9-84ed-fbba652c0d2b.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19266` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24140 by @edenduong in 2.3-develop branch
Related commit(s):
 - [4e1a8aa2c0c741fbbab886c658029a350c9c4c44](https://github.com/magento/magento2/commit/4e1a8aa2c0c741fbbab886c658029a350c9c4c44)

The fix will be available with the upcoming 2.3.4 release.
