### ISSUE TITLE
No validate "Sort Order" in Widget Form

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24154]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Content->Widget
3. Add Widget
4. Choose Type: CMS Static Block
5. Choose Theme: Magento Luma
6. Continue
7. Fill all required field: Widget Title, Assign to Store Views, Select Block
8. "Sort order" fill string "one"

### Expected result (*)

1. Can not save because it is not a number
### Actual result (*)

1. Save normally

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24154-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24154-2-3-develop.instances.magento-community.engineering/admin](https://i-24154-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19346` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24155 by @edenduong in 2.3-develop branch
Related commit(s):
 - [f5e7cfef21d59d142acf6c6b1a1fcaf97d7787ac](https://github.com/magento/magento2/commit/f5e7cfef21d59d142acf6c6b1a1fcaf97d7787ac)
 - [905ff56483111c471e92978d83d541c5fbc58542](https://github.com/magento/magento2/commit/905ff56483111c471e92978d83d541c5fbc58542)

The fix will be available with the upcoming 2.3.4 release.
