### ISSUE TITLE
"HTTP Strict Transport Security" has the Outdate Url

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24164]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend.
2. Store->Configuration
3. General->Web
4. in Base URLs (Secure), "Use Secure URLs on Storefront" and "Use Secure URLs in Admin" : Yes
5. Click the Url in "**See HTTP Strict Transport Security page for details"**

### Expected result (*)

1. Go to CHEATSHEETS:

![image](https://user-images.githubusercontent.com/8234209/63214057-d1e32180-c13d-11e9-8b7b-2d91ff10b060.png)

### Actual result (*)

Go to  outdated page:

![image](https://user-images.githubusercontent.com/8234209/63213947-a7449900-c13c-11e9-93f2-85d867a12053.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19409` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24165 by @edenduong in 2.3-develop branch
Related commit(s):
 - [274064c1900903fba7bfc9c1bc8c46372f645eae](https://github.com/magento/magento2/commit/274064c1900903fba7bfc9c1bc8c46372f645eae)

The fix will be available with the upcoming 2.3.4 release.
