### ISSUE TITLE
Comment "Warning!" in "Allow Symlinks" should have red color like other notices

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24162]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configuration
3. Advanced->Develop
4. Template Settings, "Allow Symlinks"

See the comment : **"Warning! Enabling this feature is not recommended on production environments because it represents a potential security risk."**

### Expected result (*)

Warning should have red color: similar like **(CSS Settings/Use CSS critical path)**

![image](https://user-images.githubusercontent.com/8234209/63213640-f5f03400-c138-11e9-9f70-32f711019712.png)

### Actual result (*)

No color in "Warning!"

![image](https://user-images.githubusercontent.com/8234209/63213675-58e1cb00-c139-11e9-83c2-7cd0d398de5e.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19408` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24163 by @edenduong in 2.3-develop branch
Related commit(s):
 - [95b877c866cef8e43a536b0756b13c605d946f4b](https://github.com/magento/magento2/commit/95b877c866cef8e43a536b0756b13c605d946f4b)
 - [e8e8882b665f0905cbdeed621bf06049436c9c9e](https://github.com/magento/magento2/commit/e8e8882b665f0905cbdeed621bf06049436c9c9e)
 - [3d1b0c1bba0c1054cadfa102583943a5e1823039](https://github.com/magento/magento2/commit/3d1b0c1bba0c1054cadfa102583943a5e1823039)

The fix will be available with the upcoming 2.3.4 release.
