### ISSUE TITLE
Upgrade from 2.3.1 to 2.3.2 - MySQL error

### ISSUE THREAD

**Issue by heyepic** [magento/magento2#24166]
### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2

### Steps to reproduce (*)

1. Follow upgrade steps via command line from this page: https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html
2. All commands go correctly. Time to run setup:upgrade.

### Expected result (*)

1. Upgrade goes as expected - except it fails.

### Actual result (*)

Setup:upgrade Command returns `Cache cleared successfully
File system cleanup:
/public_html/generated/code/Amazon
/public_html/generated/code/Composer
/public_html/generated/code/Dotdigitalgroup
/public_html/generated/code/MGS
/public_html/generated/code/MSP
/public_html/generated/code/Magento
/public_html/generated/code/Symfony
The directory '/public_html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
SQLSTATE[HY000]: General error: 1878 Temporary file write failure., query was: ALTER TABLE `m2quote_address` MODIFY COLUMN `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "Updated At", ADD COLUMN `validated_country_code` text NULL COMMENT "Validated Country Code", ADD COLUMN `validated_vat_number` text NULL COMMENT "Validated Vat Number"
`

**Comment by hostep** [comment]
Hi @heyepic 

From what I understand of the error message `Temporary file write failure`, it might be that you are running out of disk space, maybe [this helps](https://dba.stackexchange.com/a/142598)?

I'm closing this issue since it doesn't sound like it is caused by Magento code, but more by some environmental problem. If I'm mistaken, let me know.

I hope you'll find a solution!

**Comment by heyepic** [comment]
Just wanted to follow up in case someone experiences this and say thanks to @hostep - the server's /tmp folder was full. All good!
