### ISSUE TITLE
"Service->Oauth Settings" has no number validation 

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24172]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configuration
3. Service-> Oauth
4. Fill all the Field as text (like "test")
5. Save config 

### Expected result (*)

1. Can not save because they are not number

### Actual result (*)

1. Save the invalid data

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19406` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24173 by @edenduong in 2.3-develop branch
Related commit(s):
 - [0c0b470cbed033dc0fd5a27ff22561bbe04d87a6](https://github.com/magento/magento2/commit/0c0b470cbed033dc0fd5a27ff22561bbe04d87a6)

The fix will be available with the upcoming 2.3.4 release.
