### ISSUE TITLE
Advanced reporting not working 404 issue on Magento 2 

### ISSUE THREAD

**Issue by duydangnguyen231** [magento/magento2#24180]
**Preconditions (*)**
Magento CE/EE 2.3.2
5.7.23-24 - Percona Server (GPL), Release 24
nginx/1.12.2
PHP Version 7.1.24
Advanced Reporting setup

**Steps to reproduce (*)**
1. Go to Stores -> Configuration
2. In General -> Advanced Reporting -> Enabled (Default)
3. In General -> Web -> Set Use Secure URLs on Storefront and Use Secure URLs in Admin to Yes.
4. Go to Dashboard -> Go to advanced reporting.

**Expected result (*)**
Advanced reporting display in a new window and statistical graphs showed up. 

**Actual result (*)**
A new browser window displayed with 404 error.

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-24180-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24180-2-3-develop.instances.magento-community.engineering/admin](https://i-24180-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Charlie, here is your [Magento instance](https://i-24180-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24180-2-3-develop.instances.magento-community.engineering/admin](https://i-24180-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19625` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @duydangnguyen231 

After investigation of this issue, we found that it is not a bug.

The main reason is the first data transfer(Magento -> Adv.reporting) will be performed by CRON according to Sys.Conf settings
![SCREEN_sys_conf](https://user-images.githubusercontent.com/3409584/63791485-37af7600-c8c1-11e9-8fc9-e78d16f63131.png)


But before the data transfer will be completed will be shown this page
![advrepPage](https://user-images.githubusercontent.com/3409584/63791518-46962880-c8c1-11e9-99dc-b0a5c7c694b4.png)


In my case for all Magento instances `2.3.2(CE,EE)` `2.3-develop (CE,EE)` where I tested, Advanced Reports have appeared after ~24h.

In general, there are a couple of main rules:
1. Magento Store URL should be available from the internet(not only for localhost or some internal network)
2.  Magento crontab is created and cron jobs are running on the installed server.
3. Wait for the first Data Transfer to Adv.Report system according to Sys.Conf settings


I am closing this issue but agree it could confuse user because I also missed it in the documentation:
https://docs.magento.com/m2/ce/user_guide/reports/advanced-reporting.html

> 5. Wait overnight, or until after the time of your next scheduled update.
