### ISSUE TITLE
bin/magento cron:install adds extra cron job

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#24186]
### Summary (*)

`bin/magento cron:install` command adds the extra cron job - `update/cron.php`:

```
#~ MAGENTO START c5f9e5ed71cceaabc4d4fd9b3e827a2b
#* * * * * /usr/bin/php7.1 /home/dev/sites/pgs/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/dev/sites/pgs/var/log/magento.cron.log
#* * * * * /usr/bin/php7.1 /home/dev/sites/pgs/update/cron.php >> /home/dev/sites/pgs/var/log/update.cron.log
#* * * * * /usr/bin/php7.1 /home/dev/sites/pgs/bin/magento setup:cron:run >> /home/dev/sites/pgs/var/log/setup.cron.log
#~ MAGENTO END c5f9e5ed71cceaabc4d4fd9b3e827a2b
```

### Examples (*)

**Example #1**
1. Install Magento 2.3 via `bin/magento setup:install` command
2. Run `bin/magento cron:install`
3. Run `crontab -l`
4. Check `<magento root folder>/update` folder. 

**Actual result:**
1. `<magento root folder>/update` folder does not exist.
2. `<magento root folder>/update/cron.php` does not exist.

**Example #2**
1. Install Magento 2.3 via `Web Setup Wizard`
2. Run `bin/magento cron:install`
3. Run `crontab -l`
4. Check `<magento root folder>/update` folder. 

**Actual result:**
1. `<magento root folder>/update` folder does not exist.
2. `<magento root folder>/update/cron.php` does not exist.

### Proposed solution

Remove the extra cron job from `cron:install` command.

**Comment by magento-engcom-team** [comment]
Hi @atwixfirster. Thank you for your report. 
The issue has been fixed in magento/magento2#24187 by @atwixfirster in 2.3-develop branch
Related commit(s):
 - [6e16a8f97f0021d21f199c6ef9411ee1a05ba181](https://github.com/magento/magento2/commit/6e16a8f97f0021d21f199c6ef9411ee1a05ba181)
 - [64d4b3781ae5d77bb237148378b00d261da4a647](https://github.com/magento/magento2/commit/64d4b3781ae5d77bb237148378b00d261da4a647)

The fix will be available with the upcoming 2.3.4 release.
