### ISSUE TITLE
Issue of Drag & drop category in admin Magento EE 2.3.2 

### ISSUE THREAD

**Issue by Danatran** [magento/magento2#24181]
### Preconditions (*)

1. Magento EE 2.3.2
Environment
Magento EE 2.3.2
5.7.23-24 - Percona Server (GPL), Release 24
nginx/1.12.2
PHP Version 7.1.24

2. Multi website setup

### Steps to reproduce (*)

1. Setup website 1 with category tree 1
2. Setup website 2 with category tree 2
![tải xuống (1)](https://user-images.githubusercontent.com/43237158/63250293-82176e00-c295-11e9-90bd-738cd6d10b61.png)

3. Drag & drop a subcategory from website 1 to website 2

### Expected result (*)

Category hierarchy is updated on both frontend and backend

### Actual result (*)

1. Category hierarchy is updated on backend, but not correctly on frontend. it still display both website

![drag Category issue](https://user-images.githubusercontent.com/43237158/63250319-90fe2080-c295-11e9-9b9d-d74f451b943f.jpg)

**Comment by engcom-Bravo** [comment]
Hello @Danatran. Thanks for reporting. We've been not able to reproduce Your issue on a fresh vanilla installation of Magento as You can see it from the attached gifs. Probably the reason is in some tiny detail You missed considering it not essential or in the exact order of actions You took while reproducing the issue. Or probably we missed something.
![before](https://user-images.githubusercontent.com/51680745/63261308-d9184580-c28b-11e9-9fef-fa100cc48b20.gif)
![after](https://user-images.githubusercontent.com/51680745/63261381-0b29a780-c28c-11e9-825c-cbc7a4f5a1cb.gif)

**Comment by Danatran** [comment]
Thank you, I realize that this category change needs to reindex to run correctly.
