### ISSUE TITLE
Cart price rule based on payment methodis not aplied in checkout

### ISSUE THREAD

**Issue by Styopchik** [magento/magento2#24206]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.15

### Steps to reproduce (*)

1. Create cart price rule based on payment method (f.e. Bank transfer payment)
![screen1](https://user-images.githubusercontent.com/884525/63369329-617c1080-c388-11e9-8fda-5c902cd4324c.png)

2. Set discount in rule actions
3. Add product to cart
4. Go to checkout
5. Select Bank transfer payment method

### Expected result (*)

1. Totals should be updated, discount amount should appear in totals

### Actual result (*)

1. Totals are not updated, there is no discount in totals
![screen2](https://user-images.githubusercontent.com/884525/63369793-5ecdeb00-c389-11e9-8095-acecf939e3cf.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19515` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Styopchik. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [b6880b20e8cd7049d69f67cb5c8fb60e092384db](https://github.com/magento/magento2/commit/b6880b20e8cd7049d69f67cb5c8fb60e092384db)
 - [4c952ed9b65351358bba0884571316dfa135d240](https://github.com/magento/magento2/commit/4c952ed9b65351358bba0884571316dfa135d240)

The fix will be available with the upcoming `2.4.0` release.
