### ISSUE TITLE
Exception occurs when attempting to unset persistence cookie after visiting checkout

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#24218]
### Preconditions (*)

1. Magento v2.3.2
2. Enable Persistent Shopping Cart

### Steps to reproduce (*)
1. Enable Persistence in in Magento Admin
2. Sign-in as a customer and check the "Remember me" persistence checkbox on login.
3. Add product to cart
4. Trigger persistence by deleting phpsession cookie from browser
4. Navigate to checkout
5. Enter address information, select shipping option and press next
6. Don't select a payment method, instead return to the homepage by pressing logo
7. Press the "Not you?" link to clear persistence

### Expected result (*)

1. Persistence is cleared
2. User is redirected to sign-in page

### Actual result (*)

1. Exception occurs: "The shipping address is missing. Set the address and try again"
![image](https://user-images.githubusercontent.com/49071342/63441978-35b16700-c42a-11e9-89ad-1b3dd2ac94f5.png)

### Triggered by:
`        
if (!$shippingAddress->getCountryId()) {
            // Remove empty quote address
            $this->quoteAddressResource->delete($shippingAddress);
            throw new StateException(__('The shipping address is missing. Set the address and try again.'));
        }`
Line 206 in vendor\magento\module-quote\Model\ShippingMethodManagement.php

**Comment by itmsenior** [comment]
Confirmed issue on vanilla 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19560` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by itmsenior** [comment]
@magento give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-24218-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-24218-2-3-1.instances.magento-community.engineering/admin](https://i-24218-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-24218-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24218-2-3-develop.instances.magento-community.engineering/admin](https://i-24218-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-24218-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-24218-2-3-3.instances.magento-community.engineering/admin](https://i-24218-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [93484e3fbdb9f26d222d9f42b77ed5a4e712269f](https://github.com/magento/magento2/commit/93484e3fbdb9f26d222d9f42b77ed5a4e712269f)
 - [ac86d278a13bdeae7df3425d5c9a92426d9d3814](https://github.com/magento/magento2/commit/ac86d278a13bdeae7df3425d5c9a92426d9d3814)

The fix will be available with the upcoming `2.3.5` release.

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [93484e3fbdb9f26d222d9f42b77ed5a4e712269f](https://github.com/magento/magento2/commit/93484e3fbdb9f26d222d9f42b77ed5a4e712269f)
 - [ac86d278a13bdeae7df3425d5c9a92426d9d3814](https://github.com/magento/magento2/commit/ac86d278a13bdeae7df3425d5c9a92426d9d3814)

The fix will be available with the upcoming `2.3.5` release.

**Comment by itwebdev2** [comment]
@magento-engcom-team Commits are 404?

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [27a1299b501f6a15f9758148d17b53edfc51504d](https://github.com/magento/magento2/commit/27a1299b501f6a15f9758148d17b53edfc51504d)

The fix will be available with the upcoming `2.4.1` release.
