### ISSUE TITLE
Toggle functionality for admin menu

### ISSUE THREAD

**Issue by Nagamaiah007** [magento/magento2#24210]
### Description (*)
In Magento admin when the user clicks on the navigation side bar the sub menu will be displayed. To close that user has to click on the 'X' button or he needs to click out of the sub menu. which is not user friendly when the sub menu is very big. If you consider Reports menu item he needs to go all the way to right and click on the close symbol to close. **We are suggesting toggle functionality for the menu items.**
### Expected behavior (*)
The menu item should be a toggle on Click
### Benefits
This will be user friendly for accessing any menu whose sub menu is of any size.

### Additional information

![](https://content.screencast.com/users/Naga123456789/folders/Jing/media/87792eb3-5ae1-4452-9e23-1ef48a42dbcf/2019-08-21_1156_contribution.png)

**Comment by magento-engcom-team** [comment]
Hi @Nagamaiah333. Thank you for your report. 
The issue has been fixed in magento/magento2#24211 by @sudheer-gajjala in 2.3-develop branch
Related commit(s):
 - [fc87a57fffa759631f527be2831406779cc56f37](https://github.com/magento/magento2/commit/fc87a57fffa759631f527be2831406779cc56f37)

The fix will be available with the upcoming 2.3.4 release.
