### ISSUE TITLE
FPT / Tax Totals Sorting Not Correct

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#24225]
### Preconditions (*)
1. Magento 2.3.2

### Steps to reproduce (*)
1. Created a FPT attribute and enable FPT
2. Create an order in the backend
3. While creating the order the totals sorting is correct
4. After placing the order the totals sorting is wrong

### Expected result (*)
1. Sorting to stay the same after placing order.

### Actual result (*)
1. FPT moved below Grand Total Excl. while it should be above it.

Some screenshots..

**Correct sorting:**
<img width="554" alt="creating" src="https://user-images.githubusercontent.com/7294081/63463008-7d50e680-c45c-11e9-9663-9a91fbc6b429.png">

**Incorrect sorting:**
<img width="570" alt="created1" src="https://user-images.githubusercontent.com/7294081/63463015-80e46d80-c45c-11e9-9fc1-f1bc587d8f34.png">

(Don't look at the actual prices I accidentally mixed two orders while creating the screenshots) 

**Update 1**

After running a develop instance the FPT sorting seems to be correct, but now the Tax sorting isn't correct. It should be between Grand Total excl. and Grand Total incl.

![Schermafbeelding 2019-08-23 om 11 23 29](https://user-images.githubusercontent.com/7294081/63593824-1dba1e80-c5b5-11e9-8ebe-6eab75a444fb.png)

**Comment by engcom-Bravo** [comment]
Hello @jorgb90, thanks for reporting. Indeed on 2.3.2 this issue is reproduced but in 2.3-develop version that behavior has changed. Would You please try it with develop version as You are asked above:
![Advised](https://user-images.githubusercontent.com/51680745/63575904-d0798500-c593-11e9-8b91-a0d67f9f86a0.png)

**Comment by jorgb90** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jorgb90. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jorgb90, here is your [Magento instance](https://i-24225-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24225-2-3-develop.instances.magento-community.engineering/admin](https://i-24225-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jorgb90** [comment]
@engcom-Bravo There is indeed something changed, but not correctly! Now Tax is above Grand Total Excl., so FPT is fixed but Tax should be between Grand Total Excl. and Grand Total Incl.

![Schermafbeelding 2019-08-23 om 11 23 29](https://user-images.githubusercontent.com/7294081/63582054-9c549300-c598-11e9-988e-417ce4e64cb6.png)

**Comment by engcom-Bravo** [comment]
Thank You @jorgb90 for the work done. May we ask You to edit Your issue respectively to the new outcome. Thanks in advance.

**Comment by jorgb90** [comment]
@engcom-Bravo I need to change the text from FPT sorting wrong to Tax sorting wrong? The issue stays the same, the sorting isn't correct.

Edit: Changed title and updated the issue with my findings.

**Comment by engcom-Bravo** [comment]
Perfect, @jorgb90, that's it. Thank You.

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19613` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @jorgb90. Thank you for your report. 
The issue has been fixed in magento/magento2#24663 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [928e966f3d8f79a3bb5b22d60c63e6a31cda3e58](https://github.com/magento/magento2/commit/928e966f3d8f79a3bb5b22d60c63e6a31cda3e58)
 - [adcbfdd9b8c88e27465046e5111115e74c54e766](https://github.com/magento/magento2/commit/adcbfdd9b8c88e27465046e5111115e74c54e766)
 - [825fcb1fe5ae60cb03228884f4aa5e6f0dcbe810](https://github.com/magento/magento2/commit/825fcb1fe5ae60cb03228884f4aa5e6f0dcbe810)
 - [32a3c1846c6a48d553b6152e2c2baac488242388](https://github.com/magento/magento2/commit/32a3c1846c6a48d553b6152e2c2baac488242388)
 - [2eb25ea53c4be31e7e0366317654bc0a5789393c](https://github.com/magento/magento2/commit/2eb25ea53c4be31e7e0366317654bc0a5789393c)
 - [e80515c70ec72a9ca67b976ea0c219548c6a19e3](https://github.com/magento/magento2/commit/e80515c70ec72a9ca67b976ea0c219548c6a19e3)

The fix will be available with the upcoming 2.3.5 release.
