### ISSUE TITLE
On cart page not able to check uploaded file of file type custom option

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24239]
### Preconditions (*)

Magento 2.3.2
PHP 7.2.19

### Steps to reproduce (*)

1. create a simple product with file type custom option
2. add this product to cart along with file
3. go to cart page
### Expected result (*)

![cart-file](https://user-images.githubusercontent.com/44425160/63519723-12adb280-c511-11e9-89d6-e6723f467be6.png)

### Actual result (*)

![cart-file-original](https://user-images.githubusercontent.com/44425160/63519743-1b9e8400-c511-11e9-803c-415c3a88c759.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19576` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24240 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [281a6a41d42da2f9fb06243cd1e1e153e0c7f87b](https://github.com/magento/magento2/commit/281a6a41d42da2f9fb06243cd1e1e153e0c7f87b)
 - [fff3f5090ab3f5bb114597a4113f52d3fbf8de8b](https://github.com/magento/magento2/commit/fff3f5090ab3f5bb114597a4113f52d3fbf8de8b)

The fix will be available with the upcoming 2.3.4 release.
