### ISSUE TITLE
File type custom option value not showing properly in minicart

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24236]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.2.19

### Steps to reproduce (*)

1. create a simple product with file type custom option
2. add this product to cart along with file 

### Expected result (*)

1. Should show like 
![file](https://user-images.githubusercontent.com/44425160/63515307-2c96c780-c508-11e9-973a-cf15b8be1a3b.png)

### Actual result (*)

1. but it's showing anchor tag 
![file1](https://user-images.githubusercontent.com/44425160/63515419-75e71700-c508-11e9-8751-bc8464e7cf6a.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19575` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Closing this as issue is duplicate to #23955

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24237 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [ed1df5fb3610140f552e06ad43747dbbe3147bc7](https://github.com/magento/magento2/commit/ed1df5fb3610140f552e06ad43747dbbe3147bc7)

The fix will be available with the upcoming 2.3.4 release.
