### ISSUE TITLE
Module-Theme: TopMenu invalid type of value returned

### ISSUE THREAD

**Issue by Krielkip** [magento/magento2#24251]
#22849 # Preconditions (*)
1. master 2.3-dev

### Steps to reproduce (*)
1. Code Review, because of error in our stage.

### Expected result (*)
1. Continue with code

### Actual result (*)
1.  PHP Error
```
2019/08/23 06:55:05 [error] 13943#13943: *579 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Magento\Theme\Block\Html\Topmenu::_getHtml() must be of the type array, null given, called in vendor/magento/module-theme/Block/Html/Topmenu.php on line 186 and defined in vendor/magento/module-theme/Block/Html/Topmenu.php:204
Stack trace:
#0 vendor/magento/module-theme/Block/Html/Topmenu.php(186): Magento\Theme\Block\Html\Topmenu->_getHtml(Object(Magento\Framework\Data\Tree\Node), 'submenu', 6, NULL)
#1 vendor/magento/module-theme/Block/Html/Topmenu.php(258): Magento\Theme\Block\Html\Topmenu->_addSubMenu(Object(Magento\Framework\Data\Tree\Node), 0, 'submenu', 6)
#2 vendor/magento/module-theme/Bl" while reading response header from upstream, client: 172.28.128.1, server: *.hypernode.local, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "magento2.hypernode.local"
```

Also added an fix pull request; Which will be linked to this issue. 

The issue is that in the topmenu building a submenu, it goes to an function which builds an array of _columnBrake. 
Only if $total <= $limit then the return is void; aka null. The _getHtml needs an Array, but gets Null; This results in fatal error.

**Comment by magento-engcom-team** [comment]
Hi @Krielkip. Thank you for your report. 
The issue has been fixed in magento/magento2#24252 by @Krielkip in 2.3-develop branch
Related commit(s):
 - [60ea2be0db939d8b02f05a31fa833149097f0177](https://github.com/magento/magento2/commit/60ea2be0db939d8b02f05a31fa833149097f0177)
 - [e9dd493dbd16c0e432ab854ca5af69466a301777](https://github.com/magento/magento2/commit/e9dd493dbd16c0e432ab854ca5af69466a301777)

The fix will be available with the upcoming 2.3.4 release.
