### ISSUE TITLE
magento 2.3.1 price not showing when configurable product out of stock 

### ISSUE THREAD

**Issue by web-pro** [magento/magento2#24292]
magento: 2.3.1
I am using this code $block->getProductPrice($_product)  on list.phtml for price.
when configurable product in-stock then price is showing but not showing price for out-of-stock.

@magento-team

**Comment by sdzhepa** [comment]
Hello @web-pro and @engcom-Charlie 

It seems this behavior has been discussed multiple times on GitHub, forums etc
And additionally has been discussed with Magento Product Managers/Owners and was confirmed it is not a bug but expected behavior, this requirement covered by internal test case.

Please see for more details https://github.com/magento/magento2/issues/16069

**Comment by engcom-Charlie** [comment]
@sdzhepa thanks for contributing! 
So i close this issue.
