### ISSUE TITLE
All shipping method (Flat Rate, Table Rate,...) has No validate number (Sort Order)

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24295]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Login to backend
2. Store->Configuration
3. Sales-> Shipping method
4. Expand collapse and fill the "Sort Order" as string like "one"
5. Save

### Expected result (*)

1. Can not save because it is not number

### Actual result (*)

1. Save normally

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19663` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24296 by @edenduong in 2.3-develop branch
Related commit(s):
 - [4a3456e269feae952de09e8b4c031f07adf4fb1e](https://github.com/magento/magento2/commit/4a3456e269feae952de09e8b4c031f07adf4fb1e)

The fix will be available with the upcoming 2.3.4 release.
