### ISSUE TITLE
No validate number when create Website, Store View

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24293]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Stores->All Stores
3. Create Store View or Website
4. In form, fill "one" in sort order
5. Save

### Expected result (*)

1. Can not save because it is not a number

### Actual result (*)

1. Save normally

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19660` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24294 by @edenduong in 2.3-develop branch
Related commit(s):
 - [cd1a93cd021f0621276ab62c4df44968b50144d3](https://github.com/magento/magento2/commit/cd1a93cd021f0621276ab62c4df44968b50144d3)

The fix will be available with the upcoming 2.3.4 release.
