### ISSUE TITLE
No validate "Proxy Port" in Paypal Module (Paypal Express, Paypal Payflow -Link, Pro, Advanced)

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24304]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configurations
3. Sales-> Payment Methods
4. "API Uses Proxy" in Paypal Express, Paypal Payflow, Paypal Pro is "Yes"
5. "Proxy Port" fill "one"
6. Save

### Expected result (*)

1. Can not save because it is not number

### Actual result (*)

1. Save normally

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24304-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24304-2-3-develop.instances.magento-community.engineering/admin](https://i-24304-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Currently, It is saved alphabetically words Ex:- One on "Proxy Port" fields, It should not save. It should accept only digits.
See attached screenshot:

![Configuration _ Settings _ Stores _ Magento Admin](https://user-images.githubusercontent.com/24711761/63744361-bbb32f00-c8bc-11e9-86c4-dee2b280cff7.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19655` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24313 by @edenduong in 2.3-develop branch
Related commit(s):
 - [afc57f92bb4a2deb13dcf88907eb6686957d9e9e](https://github.com/magento/magento2/commit/afc57f92bb4a2deb13dcf88907eb6686957d9e9e)
 - [35befe1985f88d8832a1b3654329a288b29bc4ab](https://github.com/magento/magento2/commit/35befe1985f88d8832a1b3654329a288b29bc4ab)
 - [57db0ea78210d5d70ff844aad7ad5ee29ef67d9b](https://github.com/magento/magento2/commit/57db0ea78210d5d70ff844aad7ad5ee29ef67d9b)
 - [66f8376d8d40d43c54c2ae6becd721eb16b4f9de](https://github.com/magento/magento2/commit/66f8376d8d40d43c54c2ae6becd721eb16b4f9de)
 - [8cc0b25f98aad08fc00c40dc63dd1d983e068d7e](https://github.com/magento/magento2/commit/8cc0b25f98aad08fc00c40dc63dd1d983e068d7e)
 - [c68b2007c5e142103857b13568ddf2182132c797](https://github.com/magento/magento2/commit/c68b2007c5e142103857b13568ddf2182132c797)
 - [aca055b598a4c0ea307fc13eb01870767b9bbef9](https://github.com/magento/magento2/commit/aca055b598a4c0ea307fc13eb01870767b9bbef9)
 - [f48c62be3ec7362cf069c7621107d02018f4ad5f](https://github.com/magento/magento2/commit/f48c62be3ec7362cf069c7621107d02018f4ad5f)
 - [21b91d92bec2d2367c9c038b2ef676b04e1456b0](https://github.com/magento/magento2/commit/21b91d92bec2d2367c9c038b2ef676b04e1456b0)

The fix will be available with the upcoming 2.3.4 release.
