### ISSUE TITLE
File type custom option value not showing properly on wish list page

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24319]
### Preconditions (*)

1. Magento 2.3.2
2. php 7.2.19

### Steps to reproduce (*)

1. create a simple product with file type custom option
2. open product at frontend and then select a file
3. add it to wish list

### Expected result (*)

![expected](https://user-images.githubusercontent.com/44425160/63777080-25a0f800-c900-11e9-8140-dfc6f7955ff7.png)

### Actual result (*)

![wishlist-issue](https://user-images.githubusercontent.com/44425160/63777100-2d609c80-c900-11e9-9d70-48b575b8b78f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19670` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24320 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [62c216cc99c443fe0bd4f35a556cacc88f770a07](https://github.com/magento/magento2/commit/62c216cc99c443fe0bd4f35a556cacc88f770a07)

The fix will be available with the upcoming 2.3.4 release.
