### ISSUE TITLE
"CData section too big" on Export grid

### ISSUE THREAD

**Issue by gaurangpadhiyar007** [magento/magento2#24311]
### Preconditions (*)

1. Magento version 2.3.2
2. Too big files and number of files more (around > 10000 or 20000)

### Steps to reproduce (*)

1. Login Admin panel
2. Go to System -> Export

### Expected result (*)

1. 
![Export _ Import_Export _ Data Transfer _ System _ Magento Admin](https://user-images.githubusercontent.com/19263771/63744835-2a44bc80-c8be-11e9-950f-c5ccbc0727c9.png)

2. Exported files listing

### Actual result (*)

1. 
![62708071-3ac8ec00-ba10-11e9-9271-28c8a3031b4d](https://user-images.githubusercontent.com/19263771/63744729-d639d800-c8bd-11e9-9aa2-e1c7cd09b22d.png)

2. Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : CData section too big found in vendor/magento/framework/View/TemplateEngine/Xhtml/Template.php on line 60

**Comment by gaurangpadhiyar007** [comment]
@engcom-Charlie @magento-engcom-team 
Issue resolved check pull request.
https://github.com/magento/magento2/pull/24314

**Comment by engcom-Charlie** [comment]
Hello @gaurangpadhiyar007 
Could you provide more info please:
It should be 10 000 files on the grid?

**Comment by gaurangpadhiyar007** [comment]
@engcom-Charlie 
**Navigate to System-->Export**

![Export _ Import_Export _ Data Transfer _ System _ Magento Admin (2)](https://user-images.githubusercontent.com/19263771/63750772-bdd0ba00-c8cb-11e9-8893-acab21b7a6a3.png)

**Issue :** 

![Export _ Import_Export _ Data Transfer _ System _ Magento Admin (3)](https://user-images.githubusercontent.com/19263771/63750782-c1644100-c8cb-11e9-9857-83bbd35e9c70.png)

**No of Records at my system : (> 10000)**

![Export _ Import_Export _ Data Transfer _ System _ Magento Admin (4)](https://user-images.githubusercontent.com/19263771/63750791-c4f7c800-c8cb-11e9-8736-4c1919ec2cbd.png)

I have resolved this on my Magento instance.
This is the pull request https://github.com/magento/magento2/pull/24314
Commit: https://github.com/magento/magento2/pull/24314/commits/94e3994497585769b4702de5188e65be00923770

It should be more than 10,000 or more than 20,000.

Regards,
Gaurang Padhiyar.

**Comment by engcom-Charlie** [comment]
@gaurangpadhiyar007 thanks for contributing!
I reproduced it only with 20 000+ files.

**Comment by gaurangpadhiyar007** [comment]
@engcom-Charlie 
Yes, that what I have given in my last comment.

**It should be more than 10,000 or more than 20,000.**

I have resolved this on my Magento instance.
This is the pull request https://github.com/magento/magento2/pull/24314

Commit: https://github.com/magento/magento2/commit/94e3994497585769b4702de5188e65be00923770

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19671` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gaurangpadhiyar007** [comment]
@maheshWebkul721 

I have already solved it. You may check the commit and pull request.
Would you please solve what goes wrong with the pull request because I don't understand what is wrong?
commit: https://github.com/magento/magento2/pull/24314/commits

Thanks

**Comment by magento-engcom-team** [comment]
Hi @gaurangpadhiyar007. Thank you for your report. 
The issue has been fixed in magento/magento2#24954 by @eduard13 in 2.3-develop branch
Related commit(s):
 - [9d4530d89831be96b717509780baedad8be2d5bf](https://github.com/magento/magento2/commit/9d4530d89831be96b717509780baedad8be2d5bf)
 - [5078e7788945a3bdd5d1a70a59500d8380b988c9](https://github.com/magento/magento2/commit/5078e7788945a3bdd5d1a70a59500d8380b988c9)
 - [88a56b586d66ec1c13e40dd31ec1a19ef673df57](https://github.com/magento/magento2/commit/88a56b586d66ec1c13e40dd31ec1a19ef673df57)
 - [d32d5743ea0d205abea1c9398f4a265eb0ce09a3](https://github.com/magento/magento2/commit/d32d5743ea0d205abea1c9398f4a265eb0ce09a3)
 - [4ce7bf5233e32a126e21aeb6680ff8533926ed77](https://github.com/magento/magento2/commit/4ce7bf5233e32a126e21aeb6680ff8533926ed77)

The fix will be available with the upcoming 2.3.4 release.
