### ISSUE TITLE
UI Component grid indicates a wrong number of selections when removing keyword search

### ISSUE THREAD

**Issue by hostep** [magento/magento2#24348]
### Preconditions (*)
1. Seen on Magento 2.2.3, 2.3.2 and 2.3, 2.4-develop (7cf99d11e6a), so probably all M2 versions are affected

### Steps to reproduce (*)
1. Setup some vanilla Magento
1. Login to the backend
1. Create 3 customers: 'One One', 'Two Two' and 'Three Three':
 <img width="486" alt="Screenshot 2019-08-28 at 20 05 17" src="https://user-images.githubusercontent.com/85479/63881267-b98dc500-c9cf-11e9-8669-8dc78cfb98c7.png"]

1. In the 'Search by keyword' box, enter 'one' and search
1. In the first column, choose the 'Select All' option
1. Notice that one record is selected:
 [img width="421" alt="Screenshot 2019-08-28 at 20 06 11" src="https://user-images.githubusercontent.com/85479/63881435-21441000-c9d0-11e9-949c-d2a56c865649.png"]

1. Remove the 'one' keyword search by pressing the 'x' icon to the right of it.
1. Notice that it now says that one record is selected, but visually all records have a checkmark:
 [img width="424" alt="Screenshot 2019-08-28 at 20 06 24" src="https://user-images.githubusercontent.com/85479/63881521-518bae80-c9d0-11e9-819d-794096cd597a.png"]

=> **this is probably the main bug**, but it gets even worse
1. Select Actions => Delete
1. Notice that it says it will remove 1 record:
 [img width="692" alt="Screenshot 2019-08-28 at 20 06 36" src="https://user-images.githubusercontent.com/85479/63881616-87309780-c9d0-11e9-8a77-b37ebaea6768.png"]

1. Press OK
1. Notice that it now removed all records (3) instead of the 1 it claimed to delete before **yikes!**
 [img width="441" alt="Screenshot 2019-08-28 at 20 06 47" src="https://user-images.githubusercontent.com/85479/63881704-b6df9f80-c9d0-11e9-99d9-690560719c9e.png">

Note that the exact same thing can be reproduced with the product grid (and maybe other grids as well in Magento).
### Expected result (*)
1. After removing the keyword search, it should only keep 1 record selected, not all of them

### Actual result (*)
1. Shop owners calling in panic that they unintentionally removed all their customers/products somehow

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-24348-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24348-2-3-develop.instances.magento-community.engineering/admin](https://i-24348-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19708` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahesh-rajawat** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721, here is your [Magento instance](https://i-24348-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24348-2-3-develop.instances.magento-community.engineering/admin](https://i-24348-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prabhatrawat-webkul, here is your [Magento instance](https://i-24348-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24348-2-3-develop.instances.magento-community.engineering/admin](https://i-24348-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gabrieldagama** [comment]
Hi @hostep, We have got a PR that aims to fix this issue https://github.com/magento/magento2/pull/29968

But the expected behavior may not be the one described on the issue, here the contributor has applied the same behavior that the filters have on the search for the grid. So basically if you apply filters or search on the grid, the grid will deselect all records, which would prevent the problem that you described with the wrong deletion.

I personally think that is correct, we keep consistency and the same behavior across the grid. What do you think? If we want to change the behavior we may have to check in with PO and do it on both (filters and search) to be consistent.

Please let me know your thoughts. Thanks.

**Comment by hostep** [comment]
Hi @gabrieldagama 

Let me know when #29968 is more or less stable and I can test it (according to the comments, it's not stable yet)
I'll try to give some feedback when the PR is stable and I can test it in practice to see how it behaves.

Thanks!

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#29968 by @engcom-Hotel in 2.4-develop branch
Related commit(s):
 - [1f6e82fede343e6e239aaedc854ea6d63317272c](https://github.com/magento/magento2/commit/1f6e82fede343e6e239aaedc854ea6d63317272c)
 - [e837bdc66501762a46418e2fdfea3746295f690f](https://github.com/magento/magento2/commit/e837bdc66501762a46418e2fdfea3746295f690f)
 - [591e04e80f0727840ac9ec8035caa055e148a930](https://github.com/magento/magento2/commit/591e04e80f0727840ac9ec8035caa055e148a930)
 - [8a9546f7f0a938a9752508fe6ffa090cd4d76f00](https://github.com/magento/magento2/commit/8a9546f7f0a938a9752508fe6ffa090cd4d76f00)
 - [f019712ea87afd04e7f6ec521f40f28c0894a8a5](https://github.com/magento/magento2/commit/f019712ea87afd04e7f6ec521f40f28c0894a8a5)
 - [4a20d6efc56b97e3ea73886b4a9ce51eefc322e2](https://github.com/magento/magento2/commit/4a20d6efc56b97e3ea73886b4a9ce51eefc322e2)
 - [70df4f05f74ecbb87355ac7c60fce6407436406b](https://github.com/magento/magento2/commit/70df4f05f74ecbb87355ac7c60fce6407436406b)
 - [a85a63b7fb59ae7cf92c3c1a2dc65afe49fcba3d](https://github.com/magento/magento2/commit/a85a63b7fb59ae7cf92c3c1a2dc65afe49fcba3d)
 - [462f12379f7a03c3acac35ff23e4295848bb0f24](https://github.com/magento/magento2/commit/462f12379f7a03c3acac35ff23e4295848bb0f24)

The fix will be available with the upcoming 2.4.2 release.

**Comment by hostep** [comment]
@gabrieldagama: I've just re-tested this on `2.4-develop` and it looks like it now works as expected. Thank you @engcom-Hotel!
