### ISSUE TITLE
product detail page thumbnail are not show

### ISSUE THREAD

**Issue by Flyoyo** [magento/magento2#24356]
### Preconditions (*)

1.Magento 2.3.2, PHP 7.2, MySQL 5.6

### Steps to reproduce (*)

1.product detail page thumbnail are not show

### Expected result (*)

1. [Screenshots, logs or description]
2.image can be show
3.product description are not show

### Actual result (*)

1.are not show 
2.
![WX20190829-182735](https://user-images.githubusercontent.com/46588961/63932889-b73c7100-ca8a-11e9-81ca-bef9ccc440be.png)

**Comment by engcom-Bravo** [comment]
Hello @Flyoyo. We do not clearly understand what kind of thumbnails You expect to see and where. Here is an example from Magento instance with Sample Data installed:
![bag](https://user-images.githubusercontent.com/51680745/63949982-de437480-ca83-11e9-9a25-ae3808c0f756.png)
It looks pretty much the same as in Your Actual Result. Would You please be more specific. Probably You could make an image for Expected Result section  of the issue description so that we may see more clearly what You are expecting to see. Thank You.

**Comment by Flyoyo** [comment]
thanks for you.@engcom-Bravo 
Add a simple product, upload multiple pictures, only show a main map in the product details page, description is not displayed on the page, my code from GitHub pulled

**Comment by engcom-Bravo** [comment]
@Flyoyo, please tell me does my example below works correctly:
![images](https://user-images.githubusercontent.com/51680745/64257393-f442b080-cf2d-11e9-8c79-8eb44e097c9c.gif)
Thank You.

**Comment by engcom-Bravo** [comment]
@Flyoyo, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
