### ISSUE TITLE
Unable to change page_layout of product page in theme

### ISSUE THREAD

**Issue by ochnygosch** [magento/magento2#24362]
### Preconditions (*)

1. Magento Version 2.3
2. Custom Theme

### Steps to reproduce (*)

1. Copy file Magento/Catalog/view/frontend/layout/catalog_product_view.xml to <theme_dir>/Magento_Catalog/layout/override/base/catalog_product_view.xml
2. Change <page layout="1column"... to <page layout="2columns-left"...

### Expected result (*)

1. Product page should be displayed using the 2columns-left page layout

### Actual result (*)

1. Product page is displayed using the 1column page layout

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19756` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ochnygosch. Thank you for your report. 
The issue has been fixed in magento/magento2#24367 by @ochnygosch in 2.3-develop branch
Related commit(s):
 - [424cd1fead90e091addd1acfa14061aaa1d66e93](https://github.com/magento/magento2/commit/424cd1fead90e091addd1acfa14061aaa1d66e93)

The fix will be available with the upcoming 2.3.4 release.
