### ISSUE TITLE
Placing order in Admin for more stock than is available is allowed and does not show error

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#24365]
### Preconditions (*)
1. 2.3-develop
2. No MSI

### Steps to reproduce (*)
1. deploy 2.3-develop
2. Create Test Product, in stock, Qty 10
3. Create Test Customer
4. Create Test Order in Adminhtml. Assign Test Customer
5. Add Products -> Select Test Product -> Enter Qty X -> Add Selected Products to Order, where X is equal to more than a half of the stock, but not more then the whole stock, i.e for our case it is in range from 6 to 10.

### Expected result (*)
1. Product is added to order with no warnings or errors

### Actual result (*)
1. Qty 10 is added to cart but warning message appears stating "The requested qty is not available". Seems the situation happens not only when adding to cart the full stock amount (10) but also when adding any other quantity greater then it's half (i.e 6, 7, etc.).

### Steps to reproduce (*)
1. deploy 2.3-develop
2. Create Test Product, in stock, Qty 10
3. Create Test Customer
4. Create Test Order in Adminhtml. Assign Test Customer
5. Add Products -> Select Test Product -> Enter Qty 20 -> Add Selected Products to Order

### Expected result (*)
1. Product is not added to order. An error should be displayed stating "The requested qty is not available"

### Actual result (*)
1. Qty 20 is added and a warning message (not error) appears stating "The requested qty is not available"

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19751` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mahsn** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [Magento instance](https://i-24365-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24365-2-3-develop.instances.magento-community.engineering/admin](https://i-24365-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@magento i am working on it.

**Comment by drpayyne** [comment]
@engcom-Alfa Isn't this intended as the admin knows about his store and his stock?

**Comment by gwharton** [comment]
I am the admin of my store. I have no idea how much stock i have. I rely on magento to stop me from placing orders for stock i dont have or is not available to sell. In this case issue 1 is warning me i have insufficient stock when i actually have the stock and issue 2 is allowing me to add stock i dont have to an order when backorders are disabed. I think these are both valid. No?

**Comment by engcom-Bravo** [comment]
Hello @drpayyne. I dare suppose You mean me. i.e. engcom-Bravo, as it was me who worked with this issue. But even if I'm wrong let me give You my point of view concerning Your question. No, it isn't intended so, in my opinion. In order for the product to be sold in the quantities larger than its stock there are special settings that are supposed to be involved. For example You may set Manage Stock to No and then sell a product in quantities larger than its stock allows. With that the products quantity will remain unchanged, i.e will not be decreased. Also You may enable Backorders. Thus if You sell a product in quantity lets say `101` when its stock is equal `100` the order will be successfully created and the product's stock will become equal `-1`. Now assume two different products like `A` and `B` were successfully sold in the quantities exceeding their actual stocks. With that let product `A` had  Manage Stock set to Yes and Backorders - to Allow Qty Below Zero while product `B` had also Manage Stock set to Yes but its Backorders were set to No Backorders, and it was allowed to be sold in such a quantity just because it was sold from backend where admin was aware about its stock. If such cases were deemed normal it would mean that Backorders setting which is supposed to affect overstock sales affects it not always what is evidently incorrect. At least incorrect, unless there is something said about it in the official documentation or in the Backorders field's comment in configuration. Personally I haven't seen anything of the kind. So once more I don't think its an intended behavior.

**Comment by drpayyne** [comment]
@engcom-Bravo Sorry, I tagged the wrong ID. I agree with you, but I remember seeing some comment which said it's expected behavior. Let me try to find it. 

https://github.com/magento/magento2/issues/22443#issuecomment-485591078

Does this have any significance here?

**Comment by engcom-Bravo** [comment]
@drpayyne, As to the first scenario of this issue - there is everything clean by all means. I hope You agree with me. The question has arisen from the second scenario. So I  [asked](https://github.com/magento/magento2/issues/22443#issuecomment-538341045) on our discussion point the same person You refer to in Your comment above. Lets wait maybe he can give us some more relevant information on that point. But even if he is right the second scenario still remains correct, though it's Expected Result needs to be somewhat corrected. Besides it would be useful to explore what happens to the order status and shipment when it has been created with Backorders allowed vs it has been created with Backorders disallowed. (Of course I mean sales overstock). If there is some difference in behavior it would probably also give us some clue on whether admin's so to say permissiveness is intended by the architects.

**Comment by drpayyne** [comment]
Yes, I agree with you @engcom-Bravo

**Comment by mahesh-rajawat** [comment]
@magento i am working on it.

**Comment by rparsi-boxycharm** [comment]
@maheshWebkul721 @engcom-Bravo Any progress on this?
This is an issue for our store....there are several admins, our site has high volume of sales so manually tracking inventory is not feasible, so we need a way to prevent admin generated Orders that result in negative product stock quantity.
We do NOT use backorders (setting is disabled, `No Backorders` value in config).
What settings and/or magento code do I need to override/change to prevent admin generated Orders that result in negative product stock quantity?

**Comment by mahesh-rajawat** [comment]
@rparsi-boxycharm , you can go with [https://github.com/magento/magento2/pull/24945/commits/2f60bd15d65ff8fe961b9b6d844adcef2e2f00f2](https://github.com/magento/magento2/pull/24945/commits/2f60bd15d65ff8fe961b9b6d844adcef2e2f00f2) solution for your store. I suggest you to create a patch for this.

**Comment by magento-engcom-team** [comment]
Hi @gwharton, @maheshWebkul721. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [bf36d5be648d9e042f2ebc3f14e8eff9778098cf](https://github.com/magento/magento2/commit/bf36d5be648d9e042f2ebc3f14e8eff9778098cf)

The fix will be available with the upcoming `2.3.5` release.

**Comment by rparsi-boxycharm** [comment]
@magento-engcom-team that commit doesn't seem to exist...I get a 404 page when attempting to load it.  Can you provide the pr url instead?

**Comment by gwharton** [comment]
give it a day. Ive seen it take time for the commits to become visible. There wont be a PR as it was an internal commit.

**Comment by rparsi-boxycharm** [comment]
@magento-engcom-team It's been several days...please post a working (publicly accessible) url for the related commit(s)

**Comment by gwharton** [comment]
Ahhh. I wonder if it is because 2.3-develop is hidden from us users.

**Comment by magento-engcom-team** [comment]
Hi @gwharton, @maheshWebkul721. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [52604a6bc6cf79facaf1873ec6f45249ee3a0704](https://github.com/magento/magento2/commit/52604a6bc6cf79facaf1873ec6f45249ee3a0704)

The fix will be available with the upcoming `2.4.0` release.

**Comment by plastikschnitzer** [comment]
@magento give me 2.4-develop instance
