### ISSUE TITLE
"New Block" form still show "Store View" field in "Single Store Mode" 

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24387]
### Preconditions (*)

1. Magento 2.3-develop
2. Enable "Single Store Mode"

![image](https://user-images.githubusercontent.com/8234209/64060881-2fc33f00-cbfd-11e9-81ac-1c622f65ff1c.png)

### Steps to reproduce (*)

1. Go to backend
2. Content->Blocks
3. Add New Block
4. See:

![image](https://user-images.githubusercontent.com/8234209/64060895-5b462980-cbfd-11e9-97b5-13dd9cf9315d.png)

### Expected result (*)

1. No Store View field

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/64060897-639e6480-cbfd-11e9-8795-ce9acfd9d112.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-24387-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24387-2-3-develop.instances.magento-community.engineering/admin](https://i-24387-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19875` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24397 by @edenduong in 2.3-develop branch
Related commit(s):
 - [24c022ec67c70ea60dca7e8c9f0b2ed0eada27fd](https://github.com/magento/magento2/commit/24c022ec67c70ea60dca7e8c9f0b2ed0eada27fd)
 - [aaa737920ee5f0d7f2ae6b587d1321ebd2ffcb8f](https://github.com/magento/magento2/commit/aaa737920ee5f0d7f2ae6b587d1321ebd2ffcb8f)

The fix will be available with the upcoming 2.3.4 release.
