### ISSUE TITLE
Price Indexer Performance Issue With Out of Stock Products

### ISSUE THREAD

**Issue by brucemead** [magento/magento2#24414]
### Preconditions (*)
Magento 2.x

### Steps to reproduce (*)
1. Ensure that display out of stock products option is disabled
2. `php bin/magento indexer:reindex catalog_product_price`
3. `php bin/magento cron:run --group=index`

You'll see because of the lack of a where using `$entityIds` in https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/CatalogInventory/Model/Indexer/ProductPriceIndexFilter.php#L87 its executing a the delete for every product every time this method is called.

### Expected result (*)
To only delete products which are not in stock filtered by `$entityIds` supplied.

### Actual result (*)
Deletes every product which are not in stock as not where filter implimented.

**Comment by brucemead** [comment]
I've created a PR to resolve this issue https://github.com/magento/magento2/pull/24415

**Comment by magento-engcom-team** [comment]
Hi @brucemead. Thank you for your report. 
The issue has been fixed in magento/magento2#24415 by @brucemead in 2.3-develop branch
Related commit(s):
 - [7563129bcce08c1d99347eba76f1af9d564b7039](https://github.com/magento/magento2/commit/7563129bcce08c1d99347eba76f1af9d564b7039)
 - [4b1b1dc7dee1832ba2ff3598c6c0afb766941bda](https://github.com/magento/magento2/commit/4b1b1dc7dee1832ba2ff3598c6c0afb766941bda)
 - [6677a497fead97540d12befc39fa702b4f318631](https://github.com/magento/magento2/commit/6677a497fead97540d12befc39fa702b4f318631)
 - [eaa5f74a7cc4488450494ad5bb618913e13a08eb](https://github.com/magento/magento2/commit/eaa5f74a7cc4488450494ad5bb618913e13a08eb)
 - [9c9d286fbe936cac8f72bbe592dfdc54ca295772](https://github.com/magento/magento2/commit/9c9d286fbe936cac8f72bbe592dfdc54ca295772)
 - [127e8aca29874e08f96582a19e2c6dd83a4d9232](https://github.com/magento/magento2/commit/127e8aca29874e08f96582a19e2c6dd83a4d9232)
 - [a73b832be92f3628363d7a4e6db5d4dc6a36e8cf](https://github.com/magento/magento2/commit/a73b832be92f3628363d7a4e6db5d4dc6a36e8cf)

The fix will be available with the upcoming 2.3.4 release.
