### ISSUE TITLE
"setup:upgrade" disabled for  "Table 'mage_1.email_abandoned_cart' doesn't exist"

### ISSUE THREAD

**Issue by fanglexue** [magento/magento2#24428]
### Preconditions (*)
Magento version : 2.3.2
PHP version ：7.2.13
Mysql version : Ver 14.14 Distrib 5.7.22

### Steps to reproduce (*)

1. ./bin/magento setup:upgrade
2. report "Upgrading schema.. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage_1.email_abandoned_cart' doesn't exist, query was: DESCRIBE `email_abandoned_cart`"

### Expected result (*)

1. "Upgrading schema.. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mage_1.email_abandoned_cart' doesn't exist, query was: DESCRIBE `email_abandoned_cart`"

### Actual result (*)

1. Correct implementation

**Comment by engcom-Bravo** [comment]
Hello @fanglexue. Thanks for applying. Currently we've been not able to reproduce Your issue. Could You please confirm You are able to reproduce it on a fresh vanilla Magento installation of 2.3-develop version. Thank You.
P.S. We are taking into consideration that You messed up the contents of Your Expected and Actual results. If it's not so please let us know.

**Comment by fluential** [comment]
I am having similar issue when upgrading from 2.2.3 db to 2.3.2, the issue is that
vendor/dotmailer/dotmailer-magento2-extension/Setup/InstallSchema.php is not invoked during `setup:upgrade` related issue here 
- https://stackoverflow.com/questions/37745246/magento-2-installschema-not-being-executed 
- https://stackoverflow.com/questions/57792783/magento-2-3-setup-installschema-script-not-creating-table

@fanglexue the fix seems to be:
```
# Drop table
# > delete from setup_module WHERE module='Dotdigitalgroup_Email';
# re-run upgrade
# > setup:upgrade
```

**Comment by fanglexue** [comment]
@fluential  Thank you for your kind help !
