### ISSUE TITLE
Not able to update decimal quantity from cart details page.

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24509]
### Preconditions (*)

1. Magento 2.3.2
2. Php 7.2.12
3. Browser: Chrome

### Steps to reproduce (*)

1. create a product 
2. set "Qty uses decimal" to yes
3. add product to cart
4. navigate to cart page and try to update decimal qty

### Expected result (*)

1. quantity should be updated

### Actual result (*)

1. Qty not updating..
![decimalqty](https://user-images.githubusercontent.com/44425160/64476244-324c0880-d1aa-11e9-9500-fbf4c04dc173.png)

**Comment by krishprakash** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-24509-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24509-2-3-develop.instances.magento-community.engineering/admin](https://i-24509-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19936` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your report. 
The issue has been fixed in magento/magento2#24510 by @rani-webkul in 2.3-develop branch
Related commit(s):
 - [06a1aa1b1b5830ccc17c2ebb2fdc713892d22d59](https://github.com/magento/magento2/commit/06a1aa1b1b5830ccc17c2ebb2fdc713892d22d59)
 - [4bf8bfdb7e148847c4c74c90bc90c5407b3ab8ae](https://github.com/magento/magento2/commit/4bf8bfdb7e148847c4c74c90bc90c5407b3ab8ae)

The fix will be available with the upcoming 2.3.4 release.
