### ISSUE TITLE
Click "What 's this" link scroll to the top of page

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24511]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend, Store->Configuration, Customer, Persistent Shopping Cart, Enable Persistence to Yes.
2. Go to Frontend, Sign In
3. In Remember me, click "What's this?" link

### Expected result (*)

1. No scroll 

### Actual result (*)

1. Scroll to the top of the page

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19933` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24602 by @vinidziuba in 2.3-develop branch
Related commit(s):
 - [056b9ea0d5b808b51dd9f9dcf508dac25ae6b0e7](https://github.com/magento/magento2/commit/056b9ea0d5b808b51dd9f9dcf508dac25ae6b0e7)
 - [407649f82883b00e619b3c1dc81387328121c374](https://github.com/magento/magento2/commit/407649f82883b00e619b3c1dc81387328121c374)
 - [60d1ce2cea38f9c7327067b92a0af21739bdbd39](https://github.com/magento/magento2/commit/60d1ce2cea38f9c7327067b92a0af21739bdbd39)
 - [397ce47c8d62b24ac6bdb0e7a2438d363312462c](https://github.com/magento/magento2/commit/397ce47c8d62b24ac6bdb0e7a2438d363312462c)

The fix will be available with the upcoming 2.3.4 release.
