### ISSUE TITLE
quote_item.applied_rule_ids not updated after disabling cart price rule

### ISSUE THREAD

**Issue by ghost** [magento/magento2#24526]
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Create new rule
2. Add product to cart
3. Disable rule
4. Reload cart

### Expected result (*)

1. quote_item.applied_rule_ids should be NULL

### Actual result (*)

1. quote_item.applied_rule_ids contains disabled rule ID

**Comment by priti2jcommerce** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-24526-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24526-2-3-develop.instances.magento-community.engineering/admin](https://i-24526-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Sometimes applied_rule_ids are annulled but only after one has proceeded to payment method page. Though even in that case the annulment happens not always.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19941` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rasmuswikman. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. 

The fix will be available with the upcoming `2.3.4` release.

**Comment by sdzhepa** [comment]
Hello @rasmuswikman and @zhartaunik 

This issue was closed by mistake. I will reopen it and assign to @zhartaunik as the author of proposed PR with fix https://github.com/magento/magento2/pull/24921

Sorry for inconveniences

**Comment by sdzhepa** [comment]
Hello @rasmuswikman @zhartaunik

Thank you for contribution and collaboration!

A couple of minutes ago I received notification that the internal Magento team is working on a fix for this issue in the scop of the internal ticket. The fix should be completed and delivered into the `2.4-develop` branch soon with internal PR. After delivery, this issue will be closed and commented with details about commits.

**Comment by magento-engcom-team** [comment]
Hi @rasmuswikman, @sdzhepa, @zhartaunik. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [0a16a89677bdbf88447fbcf1ce4b2e8c626783dd](https://github.com/magento/magento2/commit/0a16a89677bdbf88447fbcf1ce4b2e8c626783dd)
 - [0d9ce1fcd368adef6ffd3dd07f6a641b882b5fcb](https://github.com/magento/magento2/commit/0d9ce1fcd368adef6ffd3dd07f6a641b882b5fcb)

The fix will be available with the upcoming `2.3.5` release.

**Comment by magento-engcom-team** [comment]
Hi @rasmuswikman, @sdzhepa, @zhartaunik. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [0a16a89677bdbf88447fbcf1ce4b2e8c626783dd](https://github.com/magento/magento2/commit/0a16a89677bdbf88447fbcf1ce4b2e8c626783dd)
 - [0d9ce1fcd368adef6ffd3dd07f6a641b882b5fcb](https://github.com/magento/magento2/commit/0d9ce1fcd368adef6ffd3dd07f6a641b882b5fcb)

The fix will be available with the upcoming `2.3.5` release.

**Comment by magento-engcom-team** [comment]
Hi @rasmuswikman, @sdzhepa, @zhartaunik. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.3-develop` branch(es).
Related commit(s):
 - [0a16a89677bdbf88447fbcf1ce4b2e8c626783dd](https://github.com/magento/magento2ce/commit/0a16a89677bdbf88447fbcf1ce4b2e8c626783dd)
 - [0d9ce1fcd368adef6ffd3dd07f6a641b882b5fcb](https://github.com/magento/magento2ce/commit/0d9ce1fcd368adef6ffd3dd07f6a641b882b5fcb)

The fix will be available with the upcoming `2.3.5` release.

**Comment by sdzhepa** [comment]
Hello @rasmuswikman, @ihor-sviziev , @zhartaunik.

Let me please clarify details about this issue and internal status for PR with fix.
- The internal Magento team has already fixed it. 
- Related internal Jira ticket `MC-19941` is closed as fixed
- PR has been delivered into internal `2.3-develop` branch (not visible on public)
- This fix should be available with next `2.3.4` or `2.3.5` release

Additional internal ticket `MC-30155` for port the fix into `2.4-develop` branch was created according to the internal workflow. Progress is not completed yet but should be done and delivered soon.
I will try to update this issue with commits when it will be delivered. If not required commits can be found by GitHub search where commit message text contains [MC-30155](https://github.com/magento/magento2/search?q=MC-30155&type=Commits)

**Comment by magento-engcom-team** [comment]
Hi @rasmuswikman, @sdzhepa. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [08608a611f21d763aa2ddd6b759ef9abd62f88b7](https://github.com/magento/magento2/commit/08608a611f21d763aa2ddd6b759ef9abd62f88b7)

The fix will be available with the upcoming `2.4.0` release.
