### ISSUE TITLE
Newline Missing from Reports in var/reports

### ISSUE THREAD

**Issue by aepod** [magento/magento2#24558]
### Preconditions (*)
1. Any Magento 2 version

### Steps to reproduce (*)
1. Create an exception
2. Notice the report generated lacks a newline at the end of the report. 

### Expected result (*)
1. var/report files should have newline at the end of the json output. 

### Actual result (*)
1. var/report files do not have a newline at the end of the json output

This newline seems like a cosmetic issue, but it also affects automatic parsing of the log files.
For instance filebeats: https://github.com/elastic/beats/issues/6132

**Comment by magento-engcom-team** [comment]
Hi @aepod. Thank you for your report. 
The issue has been fixed in magento/magento2#24559 by @aepod in 2.3-develop branch
Related commit(s):
 - [fec58c20635bb2abd753dd54d550504b42be0e60](https://github.com/magento/magento2/commit/fec58c20635bb2abd753dd54d550504b42be0e60)
 - [cbbdee7447e7f3b01312c2fb4b56b6076df900f4](https://github.com/magento/magento2/commit/cbbdee7447e7f3b01312c2fb4b56b6076df900f4)

The fix will be available with the upcoming 2.3.4 release.
