### ISSUE TITLE
Cannot cancel a CreditMemo

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#24573]
### Preconditions (*)
1. 2.3-develop

### Steps to reproduce (*)
\Magento\Sales\Model\Order has a canCancel() function, has a possible state of STATE_CANCELED and an implementation of the cancel() function
https://github.com/magento/magento2/blob/88d78b232184d329dd0af6b06e717a140422e744/app/code/Magento/Sales/Model/Order.php#L1224-L1234

\Magento\Sales\Model\Order\Invoice has a canCancel() function, has a possible state of STATE_CANCELED and an implementation of the cancel() function
https://github.com/magento/magento2/blob/88d78b232184d329dd0af6b06e717a140422e744/app/code/Magento/Sales/Model/Order/Invoice.php#L410-L455

\Magento\Sales\Model\Order\CreditMemo has a canCancel() function, has a possible state of STATE_CANCELED, but is missing the actual cancel() implementation

### Expected result (*)
1. You should be able to programatically cancel a creditmemo

### Actual result (*)
1. sadly, you cannot.

**Comment by gwharton** [comment]
Not runtime reproducable. Analysis of code only.

**Comment by engcom-Charlie** [comment]
Hello @gwharton !
Out of the box Magento don't let you cancel a Credit Memo, it's not Magento order flow.
If you refund online, cancel a Credit Memo would mean that you get the money back you refund minutes ago, right?
It would also mean that you have your customer Credit Card token and you are authorized to use it.

**Comment by gwharton** [comment]
Yes. I see the issues. It just struck me as odd that a call to cancancel returns true.

**Comment by gwharton** [comment]
perhaps cancancel() should return false for online creditmemos, and should return true to offline credit memos. And then the implementation to cancel an offline memo should be written. If I make a mistake producing an offline credit memo, which I have on several occasions, then the only way to correct it is to get dirty with mysql which shouldnt be the way. Magento allows me to cancel invoices that are linked to online payments, and then cancel the invoice, and recreate it as an offline invoice afterall.

**Comment by engcom-Charlie** [comment]
hello @gwharton 
I am waiting for response about this issue from my lead.

**Comment by YevSent** [comment]
Hi @gwharton. The possibility to cancel a credit memo was removed intentionally because of the impossibility to revert a refund payment transaction and requirement of a credit card or token for re-authorization.
There are still some service contracts like `\Magento\Sales\Api\CreditmemoManagementInterface::cancel` with cancel method but the implementation throws an exception.

The dependency to payment type for credit memo will make the flow inconsistent and there are multiple reasons:
- A credit memo doesn't have a dependency on payment and probably should not have it
- In comparison to invoices, which payment operations revertable via refunds, credit memos are not revertable
- If some of the refund amounts were returned to Customer Balance or Reward Points they should be redeemed after credit memo cancellation

To avoid such inconsistency the only way I see is just to allow canceling only credit memos in "Open" status but the default behavior via Admin Panel is the creation of a credit memo in the "Refunded" state for online and offline.

Could you provide some scenarios which require the cancellation of credit memos?

**Comment by gwharton** [comment]
To be perfectly honest, I raised this issue without much thought to the bigger picture and knock on effects of such an action. My use case for this request was to recover from the situation where I have issued an offline credit memo either by accident, or with some error. This only happened once where I intended on issuing an offline credit memo for the refund of postage only, but ended up creating an offline credit memo for the refund of the full order value instead. I was able to recover using SQL eventually and then correctly create and issue the proper credit memo to the customer with the appropriate offline refund. It was a painful process.

A very brief inspection of the code at the time I raised the issue, led me to believe that because the code stubs existed, and canCancel() was returning true, that the implementation had been missed, but in reality, as you say, it looks like the code stubs were there because at some point it was implemented, but removed. I'm ok with that. Perhaps canCancel() should return false to be consistent.

Like I said, It came about because of the difficulty I had in recovering from my own mistake, and I always like to have all avenues covered.

Seems that pursuing this further would result in the opening of a lively can of worms, so I'll close this one off here.

**Comment by kanduvisla** [comment]
And still there are scenario's where you would like to be able to cancel a refund. In my scenario for example, I am creating a queued refund mechanism, where you can create Credit Memo's in a "pending" state, which will be refunded on a later moment.

This gives the possibility to cancel a pending credit memo, but you would have to write your own implementation for this (which makes sence, since cancelling the credit memo in this case would also imply that I have to remove it from the queue). However, Magento does not offer me some kind of API to restore the items that are now marked as refunded.

The result is that I now have a cancelled credit memo, total refunded of my order is 0.00, but I can also no longer create a new credit memo, since the items are no longer elligible to create a new credit memo.

So yeah, I understand the logic why Magento doesn't think you should be able to cancel, but there are plenty of business cases where a merchant should be able to cancel and it would be nice if Magento would support this on a lower level.

**Comment by speedupmate** [comment]
Theres also a possibility that the online refund is on PENDING status when created and can be settled only after days or rejected. You would then need to remove the credit memo from Magento and make a new one if needed etc.
