### ISSUE TITLE
Shipping address and shipping method lost when refresh payment step 

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#24585]
### Preconditions (*)

1. Latest Magento 2.3 
2. Customer has login
2. Customer contain at least two address
 

### Steps to reproduce (*)

1.  login as customer
2. add two address
3.  add product into cart
4. configure one payment with wrong details e.g authorize.net Deprecated or braintree and use card details
5 select other than default address
6.  go to next step (payment page)
7.  select that payment method and do place order
8. after get error msg from payment & reload that page
9. in sidebar you can see default shipping address not that address that you selected on first step

### Expected result (*)

1. it should keep current address into sidebar

### Actual result (*)

1. default shipping address are set on sidebar

**Comment by engcom-Bravo** [comment]
Hi, @sunilit42, thanks for applying. Please specify what do You mean under: "in sidebar you can see default shipping address..."? You are supposed to stay on the Payment page "after get error msg from payment & reload that page". And if You are still on the Payment Page there is no shipping address on it but only the billing address - the address You haven't changed and therefore it remains the default one. As I understand You have changed only the shipping address when "select other than default address", because after that You say "go to next step (payment page)". So when You changed the the address from the default to non-default one You were on the Shipping page and that could be only the shipping address. The payment address still remained the default one.

**Comment by sunilit42** [comment]
Hello @engcom-Bravo 
Thanks for checking
1) go to the checkout
2) select other than the default shipping address
3) select any shipping method
4) click on next
5) select any payment method
6) https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L84
add
throw new CouldNotSaveException(
                __('A server error stopped your order from being placed. Please try to place your order again.'),
                $e
            );

so it will not placed order
7) check the sidebar of checkout summary ( shipping address + shipping method)
8) now refresh the page and check the sidebar of checkout summary ( shipping address + shipping method)
9) now compare 7 and 8 shipping address and shipping method

**Comment by engcom-Bravo** [comment]
Ok @sunilit42, I was cared only about the address displayed in the main page's content. This "...check the sidebar of checkout summary..." made everything clear. Thank You, I'm confirming the issue)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20171` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vivekkumar945744** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vivekkumar-webkul, here is your [Magento instance](https://i-24585-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24585-2-3-develop.instances.magento-community.engineering/admin](https://i-24585-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
We are not able to reproduce this issue on the latest `2.4-develop` code using the provided steps to reproduce from description
It seems it was already fixed in the scope of another task/pr/issue/etc.

But if this issue can be reproduced on the latest code with some different steps please create new issue
