### ISSUE TITLE
GD2 not working in WYSIWYG

### ISSUE THREAD

**Issue by barbazul** [magento/magento2#246]
I am getting hundreds of daily emails from different websites I manage with the error "
Unsupported image format."

The error is triggered every time a CMS page or block is edited in the admin

The root of the problem is the Gd2 adapter calling getimagesize() on an "http://" wrapper in an environment where allow_url_fopen is false (as it is for most shared hostings).

getimagesize() logs an error and returns false, then _fileType does not get set which leads to an exception in line 150 of Varien/Image/Adapter/Gd2.php

A possible solution mentioned in the forums is to download the image using cURL. But I don't think accessing the image via http:// makes sense for most cases, since the images are usually located in the media/wysiwyg/ directory within the server.

I tried changing  `Mage_Adminhtml_Cms_WysiwygController` to remove the URL part and it seems to work fine, but I'd have to make more tests.

<pre>

        $url = Mage::getModel('core/email_template_filter')->filter($directive);
        $url = str_replace(Mage::getBaseUrl('media'), '', $url);
        $url = Mage::getBaseDir('media') . DS . $url;

</pre>

**Comment by magento-engcom-team** [comment]
Hi @barbazul. Thank you for your report. 
The issue has been fixed in magento/magento2#28072 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [034af404deaa448c6ae660166912b0c40dfc7b12](https://github.com/magento/magento2/commit/034af404deaa448c6ae660166912b0c40dfc7b12)
 - [7e6e0239c9895982b4bb1577412b0018beef1361](https://github.com/magento/magento2/commit/7e6e0239c9895982b4bb1577412b0018beef1361)
 - [81737c084b0b80b48cf5b3359e3b145c64aa54f1](https://github.com/magento/magento2/commit/81737c084b0b80b48cf5b3359e3b145c64aa54f1)
 - [120a105b5adb6fbc4d35a0067d72aa1975acccc5](https://github.com/magento/magento2/commit/120a105b5adb6fbc4d35a0067d72aa1975acccc5)
 - [035c1577d0e5dee7c102375cd2bdba0f1542c85f](https://github.com/magento/magento2/commit/035c1577d0e5dee7c102375cd2bdba0f1542c85f)
 - [8ed5018fda262de3fb337fc886daaede98122f96](https://github.com/magento/magento2/commit/8ed5018fda262de3fb337fc886daaede98122f96)
 - [cea930b4d7549bcf476e621ad11ffbfa4847e0e6](https://github.com/magento/magento2/commit/cea930b4d7549bcf476e621ad11ffbfa4847e0e6)
 - [dabbd3c07dbc5ee4c09b785f3f315b4fd3c29fa1](https://github.com/magento/magento2/commit/dabbd3c07dbc5ee4c09b785f3f315b4fd3c29fa1)
 - [f6ce31d43aa8316ff59821c508d7b54c734bcee9](https://github.com/magento/magento2/commit/f6ce31d43aa8316ff59821c508d7b54c734bcee9)
 - [a2f28d83e8ceab42e60505af371d3e5905ee1d65](https://github.com/magento/magento2/commit/a2f28d83e8ceab42e60505af371d3e5905ee1d65)
 - [233b695c4f55b1a4c14009ecc13ced4658d5b868](https://github.com/magento/magento2/commit/233b695c4f55b1a4c14009ecc13ced4658d5b868)
 - [d127c98a404e3d5e393e14157cd71b41b0df8ae7](https://github.com/magento/magento2/commit/d127c98a404e3d5e393e14157cd71b41b0df8ae7)
 - [d9748d2d6eecb98b6eca36b5aa9b7602b6bf237f](https://github.com/magento/magento2/commit/d9748d2d6eecb98b6eca36b5aa9b7602b6bf237f)
 - [d994276cbab26239732d64b8c313a38eac13f01c](https://github.com/magento/magento2/commit/d994276cbab26239732d64b8c313a38eac13f01c)
 - [938e43bfae3774afde30523951aa9edd27778ec3](https://github.com/magento/magento2/commit/938e43bfae3774afde30523951aa9edd27778ec3)
 - [d339ae8ec16a96edcaf6927376a3a0c179826a76](https://github.com/magento/magento2/commit/d339ae8ec16a96edcaf6927376a3a0c179826a76)

The fix will be available with the upcoming 2.4.1 release.
