### ISSUE TITLE
No error message when click "Import Tax Rates" without select file

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24642]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. System->Import & Export Tax Rates
3. Click "Import Tax Rates" without select file

### Expected result (*)

1. The error message is alerted

### Actual result (*)

1. Nothing happens.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20227` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#24643 by @edenduong in 2.3-develop branch
Related commit(s):
 - [77562dabf929b7018682d0f5fa70adcf8a89af79](https://github.com/magento/magento2/commit/77562dabf929b7018682d0f5fa70adcf8a89af79)

The fix will be available with the upcoming 2.3.4 release.
