### ISSUE TITLE
Template Styles working on Preview Template but in actual email being sent

### ISSUE THREAD

**Issue by chaoticgood1** [magento/magento2#24647]
### Preconditions (*)

1. Ubuntu 18.04LTS
2. PHP 7.1

### Steps to reproduce (*)

1. Created new template with the following info:
![Screenshot from 2019-09-18 22-50-12](https://user-images.githubusercontent.com/3498992/65161005-6dcbba00-da69-11e9-89c9-ca34abe743b5.png)

### Expected result (*)

1. The invoice-1 should have been bold
2. The invoice-2 should have had 20px font-size

### Actual result (*)

1. It works in Preview Template:
![Screenshot from 2019-09-18 22-43-54](https://user-images.githubusercontent.com/3498992/65161228-c9964300-da69-11e9-9130-fba79c2c1850.png)

2. But not in email(gmail)
![Screenshot from 2019-09-18 22-44-19](https://user-images.githubusercontent.com/3498992/65161249-cef38d80-da69-11e9-94e8-4c04102ca7a7.png)

**Comment by Nickan** [comment]
@magento give me {2.2.9} instance

**Comment by chaoticgood1** [comment]
@magento give me 2.2.9 instance

**Comment by magento-engcom-team** [comment]
Hi @Nickan. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by engcom-Bravo** [comment]
Hello @Nickan. We are able not to reproduce Your issue - the preview shows the same as the email:
![template](https://user-images.githubusercontent.com/51680745/65241939-8978a400-daed-11e9-92c7-d9e5d7f61d01.png)
Probably the issue has already been fixed in later versions. Could You please confirm You can still reproduce the issue on the latest develop version. For that just ask the bot, as You already tried above,  but let Your comment contain 2.3-develop instance instead of 2.2.9. Thank You.

**Comment by engcom-Bravo** [comment]
@Nickan, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
