### ISSUE TITLE
Module Analytics ExportDataHandler.php

### ISSUE THREAD

**Issue by nemke82** [magento/magento2#24708]
Any reason why module-analytics/Model/ExportDataHandler.php line 92 is using

**$tmpDirectory = $this->filesystem->getDirectoryWrite(DirectoryList::SYS_TMP);**

instead:
**$tmpDirectory = $this->filesystem->getDirectoryWrite(DirectoryList::VAR_DIR);**

### Preconditions (*)
Current one is a wrapper to sys_get_tmp_dir() I think. Whoever wrote that extension violated the Magento spec for this stuff and we should use DirectoryList::VAR_DIR instead.

### Steps to reproduce (*)
Part of analytics_collect_data cron task Advanced Reporting module

### Expected result (*)
Data creation should be generated within Magento Docroot/var/ folder instead of/tmp/

### Actual result (*)
Data is being generated in /tmp/ filling up smaller partition and presenting a security risk.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20485` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @nemke82. Thank you for your report. 
The issue has been fixed in magento/magento2#24773 by @drpayyne in 2.3-develop branch
Related commit(s):
 - [ece34863580bd8ba09cf420759effe7a38c3f076](https://github.com/magento/magento2/commit/ece34863580bd8ba09cf420759effe7a38c3f076)
 - [9a9622247fcf4aa3e49c1857999693064b82b045](https://github.com/magento/magento2/commit/9a9622247fcf4aa3e49c1857999693064b82b045)

The fix will be available with the upcoming 2.3.4 release.

**Comment by fascinosum** [comment]
@nemke82 

- in most cases, the system **/tmp/** directory is better protected than any web instance directory
- the analytics system can collect a lot of data and this may be a problem if customer has limits on the **var/** directory
