### ISSUE TITLE
Error message "This element is not expected" with no element.

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#24731]
### Preconditions (*)

Magento 2.3.x

### Steps to reproduce (*)

Insert via database this code below in the **cms_page** table in the **custom_layout_update_xml** column.

```
    <reference name="content"></reference>
```

### Expected result (*)

It should be rendered in the CMS Page via admin panel to be removed or edited following the new syntax.

### Actual result (*)

Today, it's not rendered but when I try to save the page shows the syntax error message below.

![Screen Shot 2019-09-25 at 6 15 05 PM](https://user-images.githubusercontent.com/610598/65641689-d4019100-dfc3-11e9-8853-8515133c9df4.png)

![admin-cms-page-error-message](https://user-images.githubusercontent.com/610598/65641675-ce0bb000-dfc3-11e9-9144-758c3907b472.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21692` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
Hi @rafaelstz @shikhamis11,
I've just looked on instance from 2.4-develop - this field was fully removed due to security reasons.
![image](https://user-images.githubusercontent.com/1873745/74009374-b4c03a80-498b-11ea-9747-11251d49d065.png)


https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-4-open-source.html?itm_source=devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=2.3.
![image](https://user-images.githubusercontent.com/1873745/74009580-2d26fb80-498c-11ea-986a-406c84e753e1.png)

After removing this field this issue looks like not relevant anymore.
@rafaelstz @engcom-Charlie could you confirm that?

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by shikhamis11** [comment]
Hi @ihor-sviziev 
thanks for update .. yes based on recent changes of magento 2.3.4 it seems this is no longer an issue .
