### ISSUE TITLE
Invoice PDF on frontend does not use configured logo image

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#24730]
I have installed the Magento 2.3.2.

I have uploaded custom logo on Stores -> Configuration -> Sales -> Sales ->Invoice and Packaging Slip Design.
https://prnt.sc/pawmig

I have placed test order and created invoice for that order. 

I have print the invoice from the front end customer account page under the My orders and this is what I am getting.
https://prnt.sc/pawngp 

I have print the same invoice from the back end : sales -> order -> invoice -> print -> https://prnt.sc/pawnvs
This is what I am getting https://prnt.sc/pawo9h

Preconditions (*)
I have installed the Magento 2.3.2.

I have uploaded custom logo on Stores -> Configuration -> Sales -> Sales ->Invoice and Packaging Slip Design.
https://prnt.sc/pawmig

Information on your environment
I have installed the Magento 2.3.2.

Steps to reproduce (*)
I have installed the Magento 2.3.2.

I have uploaded custom logo on Stores -> Configuration -> Sales -> Sales ->Invoice and Packaging Slip Design.
https://prnt.sc/pawmig

I have placed test order and created invoice for that order. 

I have print the invoice from the front end customer account page under the My orders and this is what I am getting.
https://prnt.sc/pawngp 

I have print the same invoice from the back end : sales -> order -> invoice -> print -> https://prnt.sc/pawnvs
This is what I am getting https://prnt.sc/pawo9h

Expected result (*)
Invoice print should be contains the same logo in the header either It should be print from the front end or back end. **(Added:)** If it shouldn't that has to be mentioned somewhere in the comments or official User Guide documentation.

Actual result (*)
https://prnt.sc/pawngp - front end invoice print
https://prnt.sc/pawo9h - back end invoice print
**(Added:)** It is nowhere officially specified that the Logo for PDF print-outs is meant to be exclusively for Backend print-outs.

**Comment by engcom-Bravo** [comment]
Hello @jigar48. Thanks for reporting. Backend and Frontend invoice pdfs use quite different templates so they look quit differently as it is logically supposed to be. The invoice available on Frontend is shop styled and is just an acknowledgement for a customer that his or her order has been invoiced while the invoice printed out from backend is business styled and is designed  to be used in a company's account, bookkeeping and other official document flow. With that the Frontend invoice uses the logo of the store while the Backend logo is set separately. Probably there's a little bug in this comment "Your default logo will be used in PDF and HTML documents." saying nothing about the logo being used only for Backend printing. What do You think of it.

**Comment by jigar48** [comment]
There is no place where mentioned that Logo should be use for the back end purpose only. and one more thing that the logo which we upload in to sales -> invoice and packing slip design, there is 2 field Logo for Print and Logo for HTML Print layout. 

Now Logo For the HTML print layout should not be part of the Backend. because that is only possible in the Front end side under the customer account -> My orders page.

so Its typically bug because that logo should be display in the front end print side as well.

**Comment by magento-engcom-team** [comment]
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20527` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jigar48** [comment]
I want to work on this issue

**Comment by andrewbess** [comment]
Hello @jigar48 . Please use next comment: "@magento I'm working on it" to assign issue on self

**Comment by jigar48** [comment]
@magento I'm working on it

**Comment by jigar48** [comment]
@magento-engcom-team please give me 2.3-develop instance

**Comment by mozok** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Hi @jigar48. Thank you for your report. 
The issue has been fixed in magento/magento2#30632 by @mozok in 2.4-develop branch
Related commit(s):
 - [2389da7df17a410deefac9d1f609da78f57c95d8](https://github.com/magento/magento2/commit/2389da7df17a410deefac9d1f609da78f57c95d8)
 - [682750315c1760c9a028cb212d87d978b4002d12](https://github.com/magento/magento2/commit/682750315c1760c9a028cb212d87d978b4002d12)
 - [9181adcefb3ae641d95e0a28fd99179b17d75aec](https://github.com/magento/magento2/commit/9181adcefb3ae641d95e0a28fd99179b17d75aec)
 - [4d0debd9988053627fd8fabbc505e99f3b61f018](https://github.com/magento/magento2/commit/4d0debd9988053627fd8fabbc505e99f3b61f018)
 - [7b7b83aa4cf37bda03c7fb48b6a5184edd375564](https://github.com/magento/magento2/commit/7b7b83aa4cf37bda03c7fb48b6a5184edd375564)
 - [182a65c06b1d72a8f248b5787b6993f156d2fe00](https://github.com/magento/magento2/commit/182a65c06b1d72a8f248b5787b6993f156d2fe00)
 - [0287723fba515922ca4e6b6dcb28797a601b5da5](https://github.com/magento/magento2/commit/0287723fba515922ca4e6b6dcb28797a601b5da5)
 - [65bb09577438f4ed028e732e192ff911690c244f](https://github.com/magento/magento2/commit/65bb09577438f4ed028e732e192ff911690c244f)
 - [f229c75c85e0bd56e8edfadb3277bff7ff5b4793](https://github.com/magento/magento2/commit/f229c75c85e0bd56e8edfadb3277bff7ff5b4793)
 - [585583210cb796f71714368ec0146deb8743c87d](https://github.com/magento/magento2/commit/585583210cb796f71714368ec0146deb8743c87d)

The fix will be available with the upcoming 2.4.2 release.
