### ISSUE TITLE
Change text and check box not in same aligned

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#24740]
Change text and check box not in same aligned

### Preconditions (*)
magento 2.3

### Steps to reproduce (*)
1. Admin -> Catalog -> Products
2. Select any product and from Action drop-down choose Update Attributes
3. Review the Update Attributes page

### Expected result (*)
change text and check box should display in same line

### Actual result (*)
![image](https://user-images.githubusercontent.com/49804008/65745290-d6293400-e118-11e9-8c0c-483594cac872.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20526` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @bhavik43. Thank you for your report. 
The issue has been fixed in magento/magento2#24761 by @drpayyne in 2.3-develop branch
Related commit(s):
 - [be1194b19e62a8244a81a18df6e86516ed155e91](https://github.com/magento/magento2/commit/be1194b19e62a8244a81a18df6e86516ed155e91)

The fix will be available with the upcoming 2.3.4 release.
