### ISSUE TITLE
How to Merge guest quote items to customer quote(if customer log in) by magento 2 rest API

### ISSUE THREAD

**Issue by sangeetajain** [magento/magento2#24808]
### Preconditions (*)
Magento 2.3-develop
If any one is add products in cart by guest and after that login then how it will merge guest cart to customer login cart items by Rest API.

### Steps to reproduce (*)
1. Create a customer 
2. Log out from customer account 
3. Add any product to cart 
4. Try to merge quotes via API
```
Authorization -"Bearer {user-token}"
PUT {URL}/rest/V1/guest-carts/{guest-card-id}
Body: 
{
  "customerId": {customer id},
  "storeId": {store id}
}
```
### Expected result (*)
200 OK
`true`
### Actual result (*)
getting error : "The customer can't be assigned to the cart because the customer already has an active cart."
![Screenshot from 2019-10-02 13-18-36](https://user-images.githubusercontent.com/51680850/66039969-f6912e00-e51e-11e9-8c66-3f045c2544f8.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21009` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sangeetajain** [comment]
Hello Team,
Is there any update regarding this issue...?

**Comment by sangeetajain** [comment]
Hello Team,
Is there any update regarding this issue...?

**Comment by engcom-Charlie** [comment]
Hello @sangeetajain !
Fix in progress as you can see in #24862 .

**Comment by magento-engcom-team** [comment]
Hi @sangeetajain. Thank you for your report. 
The issue has been fixed in magento/magento2#24862 by @ivan-koliadynskyy in 2.3-develop branch
Related commit(s):
 - [2a6dc66bbeab6179a717f31c988ed0a4eee8ec4d](https://github.com/magento/magento2/commit/2a6dc66bbeab6179a717f31c988ed0a4eee8ec4d)
 - [dc460c817b810553c3a037f9ae65985a07efb975](https://github.com/magento/magento2/commit/dc460c817b810553c3a037f9ae65985a07efb975)
 - [9f77a81dc7921077a0edd600d18d51a95115d002](https://github.com/magento/magento2/commit/9f77a81dc7921077a0edd600d18d51a95115d002)
 - [6ff21a67ba555b2dc24b677a0368085e976a457f](https://github.com/magento/magento2/commit/6ff21a67ba555b2dc24b677a0368085e976a457f)
 - [d0e2ced7c02a04a32de03d6bad0cb06ff8fc431f](https://github.com/magento/magento2/commit/d0e2ced7c02a04a32de03d6bad0cb06ff8fc431f)
 - [b6f0bb33a648fd1e9014e6fcd93fe019e1e19003](https://github.com/magento/magento2/commit/b6f0bb33a648fd1e9014e6fcd93fe019e1e19003)
 - [fe12c41fb92d9ee24f7af529230919cbdb162ba2](https://github.com/magento/magento2/commit/fe12c41fb92d9ee24f7af529230919cbdb162ba2)
 - [e5095fbae95c4c40f10576da74d86e752fbe5362](https://github.com/magento/magento2/commit/e5095fbae95c4c40f10576da74d86e752fbe5362)
 - [daede858a4838d013c728f2e12d749a233f34b2a](https://github.com/magento/magento2/commit/daede858a4838d013c728f2e12d749a233f34b2a)
 - [08fb9aec1e152181b817a342c55ce6ff2644a55e](https://github.com/magento/magento2/commit/08fb9aec1e152181b817a342c55ce6ff2644a55e)
 - [8b08a513b8bdc65601d6e6556c786350218dc13b](https://github.com/magento/magento2/commit/8b08a513b8bdc65601d6e6556c786350218dc13b)

The fix will be available with the upcoming 2.3.4 release.

**Comment by dimaportenko** [comment]
I created a workaround from the above fix for versions < 2.3.4. https://github.com/troublediehard/plab-cartsmergefix

**Comment by anowarsadata** [comment]
What need to do for work with magento 2.3.3

**Comment by AnemosGroup** [comment]
The fix is working but the merge is not taking into consideration the available quantity of stock products.
At Model\Quote.php, lines 2392 and 2393:
...
$quoteItem->setQty($quoteItem->getQty() + $item->getQty());
$this->itemProcessor->merge($item, $quoteItem);
...

The setQty bypasses any check of availability / eligibility.
Let's say a product has only 1 items in stock, a logged in customer adds it to the cart, then logs out, adds it again as a guest and then logs back in. The merge will result in 2x items of a 1x stock available product, and the checkout will throw an error.
