### ISSUE TITLE
Remove image doesn't clear flat table image value's when having multiple stores

### ISSUE THREAD

**Issue by NickdeK** [magento/magento2#24825]
### Preconditions (*)

1. Magento 2.3.2
2. Multiple stores

### Steps to reproduce (*)

1. Have a product that has one or multiple images
2. Remove the images while in the "All Store Views" scope.

### Expected result (*)

1. Image is removed and cleared in all store specific flat tables
2. Doing `$product->getData('small_image')` results in null or `no_selection`

### Actual result (*)

1. Old image path is still saved in the flat table of every store specific flat table except for store 0 (the default store)
2. Doing `$product->getData('small_image')` results in the old image path of the removed image
3. There is no way to see this data in the admin panel because the images are removed from every storeview.

**Comment by engcom-Bravo** [comment]
Hello @NickdeK, thanks for reporting. We haven't managed to reproduce Your issue on the latest develop version by now. We used simple CLI command to run such a code like:
```
$product = $this->productRepository->getById($Id);
$output->writeln($product->getData('small_image'));
```
Here You may see the results:
![noselection](https://user-images.githubusercontent.com/51680745/66060689-c1003b00-e546-11e9-8459-c8f53d752472.gif)

Point us please at where we missed or misunderstood something while reproducing the issue. Otherwise/also please try to reproduce Your issue on 2.3-develop version as You are asked in the [comment](https://github.com/magento/magento2/issues/24825#issuecomment-537476315) above. Thank You.

**Comment by engcom-Bravo** [comment]
@NickdeK, the contributor guide suggests that tickets that have not been active for two weeks should be closed. Please reopen as needed.
