### ISSUE TITLE
EE: File resolving is broken

### ISSUE THREAD

**Issue by vzubovich** [magento/magento2#2485]
I got following error when I was trying to open Content -> Pages:
Cannot read contents from file "/var/www/magento2ee/magento2ce/var/www/magento2ee/magento2ee/app/code/Magento/VersionsCms/view/adminhtml/ui_component/cms_page_listing.xml" Warning!file_get_contents(/var/www/magento2ee/magento2ce/var/www/magento2ee/magento2ee/app/code/Magento/VersionsCms/view/adminhtml/ui_component/cms_page_listing.xml): failed to open stream: No such file or directory

**Comment by mazhalai** [comment]
@vzubovich Have you set file and folder permissions as recommended [here](http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html)?

**Comment by vzubovich** [comment]
@mazhalai :)
pls take a notice that requested file path is basically wrong - it has splitted path to CE and EE code pools
/var/www/magento2ee/magento2ce + /var/www/magento2ee/

**Comment by mazhalai** [comment]
@vzubovich please open an issue via the support portal.

**Comment by vzubovich** [comment]
What I have to do?

**Comment by vzubovich** [comment]
@mazhalai What I have to do?

**Comment by mazhalai** [comment]
@vzubovich if you have EE, you must have an account on the partner portal. Please login and create a support ticket.

**Comment by alankent** [comment]
The support portal has more dedicated staff etc.

But in general, please remember that EE is a set of additional packages you add to your project. There are no code pools in M2. The path you reported looks strange - like there are separate magento2ce and magento2ee directories. I am not sure where these came from. The overall directory structure for CE and EE are the same - if you use the EE product metapackage instead of the CE product metapackage, you end up with more packages in the 'vendor' directory. But there is no different subdirectory. The Support org can help you get this path problem sorted out - it sounds like confusion around how to get the directory tree right, rather than a bug (?).

**Comment by mazhalai** [comment]
Closing, since this will be handled via partner portal.

**Comment by vzubovich** [comment]
@mazhalai I did create any issue on other portals. You may handle this bug as you wish! :)

**Comment by vzubovich** [comment]
@mazhalai I didn't create any issue on other portals. You may handle this bug as you wish! :)
