### ISSUE TITLE
On Magento 2.3.2, setup:upgrade command removes tables of disabled modules

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#24926]
### Preconditions (*)

1. Magento 2.3.2 & 2.3-develop, 2.3.2-p1 (CE or EE- doesn't matter)
2. At least one installed module, which uses declarative schema

### Steps to reproduce (*)

1. Disable module, which uses declarative schema, using console command (module:disable). For example, native Magento_ReleaseNotification extension
2. Run setup:upgrade command
3. Check in the database, tables of the disabled module from the first step (for Magento_ReleaseNotification - that's the only table 'release_notification_viewer_log')

### Expected result (*)

1. Tables of the disabled module have been already removed

### Actual result (*)

1. The database still contains tables of the disabled module, with all data.
2. See https://github.com/magento/magento2/issues/24458#issuecomment-528324463

**Comment by staradzinau** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @avgust1111. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @avgust1111, here is your [Magento instance](https://i-24926-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24926-2-3-develop.instances.magento-community.engineering/admin](https://i-24926-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by staradzinau** [comment]
> do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

Yes, I've reproduced the bug on my local environment. Unfortunately, I can't reproduce the issue on the test Magento instance, specified above, because I need SSH credentials to run console commands, specified above

It would be very nice to sort that issue out as soon as possible

**Comment by ghost** [comment]
After disabling module, please enable safe mode, while executing "setup:upgrade" or "setup:install", as this will creates a data dump during the installation or upgrade process. After this please restore the database while enabling the module.

Please follow the commands for same :

"setup:upgrade --safe-mode=1" : run after disabling the mod, this will create database backup.

"setup:upgrade --data-restore=1" :  to restore database again after enabling the module.

Please refer Magento doc. https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.html

**Comment by staradzinau** [comment]
Hello, @webkul-deepak 
Is that a final solution, or just a temporary one, until the bug won't be fixed?
Anyway, is that solution suitable for the situation, when module is enabled again after some period of time? Will database restoring affect all changes in all tables (both data and schema), or only tables, related to the enabled module?

**Comment by ghost** [comment]
Hi @avgust1111  the provided solution is not the temporary, it's the final solution. As it's the feature of Declarative Schema.
Yes, it will work same for modules which you've enabled after a long time.
Also "--data-restore=1" restores both data and schema, after enabling the module again.

**Comment by staradzinau** [comment]
Hello, @webkul-deepak.
Thank you for the update.
One moment is still unclear enough. 
> Will database restoring affect all changes in all tables (both data and schema), or only tables, related to the enabled module?

> "--data-restore=1" restores both data and schema,

Will this action affect the whole database, or only tables, related to the module, which is enabled again?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22908` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by twosg** [comment]
Personally I would prefer letting the "disabled" table(s) and data untouched while running `setup:upgrade` after disabling modules. If you really would want to delete the table and its (possibly important) data, you could run `setup:upgrade --cleanup_mode=1` or something similar. Because then you know that you do not want the data.

**Comment by danemacmillan** [comment]
I get that this is the point behind [Declarative Schema](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/), but there should still be an option to prevent data from getting purged, like @twosg [commented](https://github.com/magento/magento2/issues/24926#issuecomment-574109433). This is a really nuclear default; it should require more deliberate input from users instead.

Removing and re-adding the data using the `--safe-mode` and `--data-restore` options just seem like a more error-prone, generally worse option than a simple `--leave-my-shit-in-place` option.

**Comment by kanevbg** [comment]
Maybe better solution is that module:uninstall Module_Name is to remove the data, and not setup:upgrade?

**Comment by gabrieldagama** [comment]
Disabling a module should not lead to the deletion of the database table or its contents, as described by some contributors above. 

Closing this issue since the current behavior is the expected one.

Thanks.

**Comment by avgust1111** [comment]
@gabrieldagama Please, note: earlier, documentation has been updated: [https://github.com/magento/devdocs/issues/5629](url). I suppose if the behaviour was changed, it's necessary to update the documentation, what do you think?

**Comment by gabrieldagama** [comment]
Hi @avgust1111, thanks for highlighting. Did some investigation on this and the current behavior is the expected behavior on this issue. I guess the documentation is still correct. I will check internally, but I still think that shouldn't be the behavior, maybe there is a reason for that.

Thanks again for your feedback.

**Comment by LiamKarlMitchell** [comment]
Can you not delete tables, its rather annoying.
Delete the table if the module is completely deleted or add a warning on every setup:upgrade that the tables still exist...

**Comment by barryvdh** [comment]
This is understandable from a technical point of view, but I would say this is wildly dangerous behaviour. I think you would usually almost never want to drop actual tables/columns on an upgrade, especially with automated deployments. Examples:

 - A module is conflicting, so you disable modules one by one to find a solution -> your settings and data will now be dropped after deploying
 - For some reason a module is missing temporarily to wait for compat with newer versions -> all old data is lost
 - Technical error that disables the wrong module on deploy on a different branch, etc etc

I understand that you want to keep your database clean, but then please create an uninstall command. Not sure of the technical possibilities, but perhaps it's possible to keep the declarative schemas in the `var` folder, so if a module is deleted, the already used schemas are still available and can be used to actually revert a module if required (eg. by deleting that file also).

(I just noticed this because I disabled 2FA to let someone debug an issue on a staging enviroment, but after re-enabling: all the 2fa tokens were reset)

**Comment by bmelman** [comment]
This is indeed very dangerous and unexpected behaviour.
Disabling a module is not the same as removing a module: for removal (using i.e. composer) the removing of related tables would be logical.
That said at least an option to prevent this table removal behaviour (from module source code/config instead of cli) would be enough to even consider this in production.

So for now regressing back to Install/Upgradeschema

**Comment by nordcomputer** [comment]
Ok, just a question.
So, I disable a module and run `setup:upgrade --safe-mode`
After some time, I want to disable another module. So, I disable the second module and run `setup:upgrade --safe-mode` again.

What happens, if I reactivate the first module and run `setup:upgrade --restore-data`? Will it restore the data from the first deactivated module or will it restore the data for both modules (even, if the second module is still deactivated)?

**Comment by webkul-deepak** [comment]
@nordcomputer regarding : What happens, if I reactivate the first module and run setup:upgrade --data-restore=1? Will it restore the data from the first deactivated module or will it restore the data for both modules (even, if the second module is still deactivated)?
==> It only restore data for enabled module. It didn't restore data of deactivated modules.

regarding : Bonus question: Once I have done setup:upgrade --safe-mode=1, would I have to do it everytime, when I run the command? In other words: will the backup get deleted, when I run the command later without the --safe-mode option?
==> Whenever you need to run setup:upgrade after deactivating any module, in that case you need to execute it with --safe-mode=1 (to create database backup of deactivated module). In case if you're not deactivating any module, in that case their is no need to use --safe-mode=1. Also you can use --safe-mode=1 --data-restore=1 together, to create database backup and restore on the same time.

**Comment by jlenzstaysafe** [comment]
This does not work correctly when adding a column to an existing core table.  For example, if you create a custom module and define your db_schema and whitelist which simply adds a column to an existing core table, then disable your module/run set:up - POOF, the entire core table is gone

**Comment by oleksandrpikalov** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by jkenneydaniel** [comment]
Just for others coming across this in their travels:

Disabling a module which employs declarative schema **_does in fact_** delete the data for that module - so be _very_ careful what you are disabling. If you plan to migrate data from one module to another (for instance, when taking over another module) - you will absolutely need to leave the original module enabled and only disable it once the data has been migrated to the new tables.
