### ISSUE TITLE
Special Price class not added in configurable product page

### ISSUE THREAD

**Issue by k-edasi** [magento/magento2#24972]
### Preconditions (*)
1.  Magento 2.3.1 & 2.3-develop
2. Configurable product page with discount prices (this is reproducible on a clean Magento 2 project as well)

### Steps to reproduce (*)
1. Go to a configurable product page that has at least one discount price
2. Select an option with discount price
3. `class="normal-price"`  remains and is not changed to special-price

### Expected result (*)
1. `class="normal-price"`  is changed to `class="special-price"`  when discounted option is chosen as in simple product
**e.g**(simple product with special price):
![image](https://user-images.githubusercontent.com/51680850/68289853-934f6a00-008f-11ea-98b0-b966e87b41b7.png)

### Actual result (*)
1.  `class="normal-price"` remains, which means different styling options can not be added
![image](https://user-images.githubusercontent.com/51680850/68289761-6ac77000-008f-11ea-8e81-0468b74b86a5.png)

2. no console errors

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22858` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @k-edasi. Thank you for your report. 
The issue has been fixed in magento/magento2#26170 by @ravi-chandra3197 in 2.4-develop branch
Related commit(s):
 - [666d4c0ff2b3a498d97acd101ae1ec86592bee70](https://github.com/magento/magento2/commit/666d4c0ff2b3a498d97acd101ae1ec86592bee70)
 - [e037d514215f9e662b5585a5ab967ca4edcde3af](https://github.com/magento/magento2/commit/e037d514215f9e662b5585a5ab967ca4edcde3af)

The fix will be available with the upcoming 2.4.0 release.
