### ISSUE TITLE
API returns created_at/updated_at in UTC regardless of timezone settings

### ISSUE THREAD

**Issue by itmsenior** [magento/magento2#24985]
### Preconditions (*)

1. Magento 2.3.3
2. Set TimeZone to something that isn't UTC (I.e. GMT Europe/London - currently UTC+1)

### Steps to reproduce (*)
1. Place test order
2. Send GET request for order details to SalesOrderRepository
3. created_at/updated_at will be in UTC

### Expected result (*)

1. created_at/updated_at will use timezone set in Magento admin

### Actual result (*)

1. created_at/updated_at uses UTC timezone

**Comment by webkul-ratnesh** [comment]
@magento I am working on it.

**Comment by novikor** [comment]
Hi, @itwebdev2. Thank you for your collaboration.

The issue is not relevant and should be closed.

The API you referenced is a part of Magento Service Layer and it is not responsible for formatting dates in its output, - it's relevant to the presentation layer logic.
Moreover, even if we assume it is acceptable, it is not really safe to do that because existing integrations do not expect such changes.

The date format and timezone should be handled on the side of a client that uses the API.

Please don't hesitate to contact me if you have any questions regarding the issue.
