### ISSUE TITLE
Admin Panel logo link is not directing to admin dashboard page

### ISSUE THREAD

**Issue by Nagamaiah007** [magento/magento2#24990]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Go to magento admin  -> System -> Web Setup Wizard page.
2. Click on magento admin logo

### Expected result (*)

1. On click magento admin panel logo, It should redirect to admin dashboard page

### Actual result (*)

1. 
![admin_panel_logo](https://user-images.githubusercontent.com/54108580/66655384-96566680-ec59-11e9-8ea9-5665c435e1db.png)

2. Logo link is not redirecting to magento admin dashboard page upon click

**Comment by sudheer-gajjala** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheer-gajjala. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheer-gajjala, here is your [Magento instance](https://i-24990-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24990-2-3-develop.instances.magento-community.engineering/admin](https://i-24990-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21725` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Nagamaiah007. Thank you for your report. 
The issue has been fixed in magento/magento2#26100 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [5a5091c906e27153ac9680e0db5d8261df3c024c](https://github.com/magento/magento2/commit/5a5091c906e27153ac9680e0db5d8261df3c024c)
 - [1818eaf28562c82de23a59b5b8ade0ec93dd538c](https://github.com/magento/magento2/commit/1818eaf28562c82de23a59b5b8ade0ec93dd538c)
 - [c98e03f46c6d6b1e00f738e22e0474113373500e](https://github.com/magento/magento2/commit/c98e03f46c6d6b1e00f738e22e0474113373500e)
 - [8c672ebfe92b13cdd8111777db227d6b05897def](https://github.com/magento/magento2/commit/8c672ebfe92b13cdd8111777db227d6b05897def)
 - [b90f20c157bed3580623caf479024cdb0ca18875](https://github.com/magento/magento2/commit/b90f20c157bed3580623caf479024cdb0ca18875)
 - [531a22f24b8726ab06ee68e6a11ae052eb5c2a56](https://github.com/magento/magento2/commit/531a22f24b8726ab06ee68e6a11ae052eb5c2a56)
 - [4336cf1528ab8cc217d5da2573c2a9a237a90542](https://github.com/magento/magento2/commit/4336cf1528ab8cc217d5da2573c2a9a237a90542)
 - [f39a494a55f5d1337bded02db1fa932b12f43ff6](https://github.com/magento/magento2/commit/f39a494a55f5d1337bded02db1fa932b12f43ff6)
 - [31bbf073f9b359eb610b74a0b62c8dc55e8a3b53](https://github.com/magento/magento2/commit/31bbf073f9b359eb610b74a0b62c8dc55e8a3b53)
 - [e1b0ff085333190d013abb4ce722f0cf2fae42d6](https://github.com/magento/magento2/commit/e1b0ff085333190d013abb4ce722f0cf2fae42d6)

The fix will be available with the upcoming 2.4.0 release.
