### ISSUE TITLE
No rest api available for updating the shipping and billing address for customer

### ISSUE THREAD

**Issue by arunkasyakar** [magento/magento2#2499]
there are no api available to add another address and update the address for customer

**Comment by vkorotun** [comment]
Yes, there is no separate REST resource for Customer address by design.
Customer Address is a part of aggregate root, in this particular case - Customer Entity is an aggregate root.
While in PHP code you may get access to Customer Address model and do some actions directly with address entity, we've decided to do not provide access to sub-entities via REST or SOAP.

There is a "primary" REST resource you may call to save customer address, and this resource is actual customer: "/V1/customers/:id"
You may pass "addresses" key with array of addresses and those will be processed and persisted properly.

Be careful, as for related entities, we consider data, that have been passed, represents the final state of relations. This being said, that if you have three addresses already linked to customer, and within REST call you pass only two of those, the third one will be deleted.

**Comment by choukalos** [comment]
This is a dup of #2398 ; Summary - we have address as an extensible data object ( actually an array of objects for both shipping and billing ).  see the answer there for details and how to manipulate those arrays.
