### ISSUE TITLE
Admin routing to 404 page after installation

### ISSUE THREAD

**Issue by tiagosampaio** [magento/magento2#250]
When I install Magento in localhost I can access only the frontend. When I go to admin I get the login page and when I put my credentials and submit I am redirected to 404 page.
Am I doing anything wrong or this issue is not solved yet?

Thanks

Sam

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your report. 
The issue has been fixed in magento/magento2#27882 by @eduard13 in 2.4-develop branch
Related commit(s):
 - [9365b57c0591e14f5945a856acfb740c1921f69f](https://github.com/magento/magento2/commit/9365b57c0591e14f5945a856acfb740c1921f69f)
 - [ddf7d53cad8adf7b3ea40edd2c44c6287f5619a6](https://github.com/magento/magento2/commit/ddf7d53cad8adf7b3ea40edd2c44c6287f5619a6)
 - [51e2fbc741d8f6892432f8e9b83eec2c1737874b](https://github.com/magento/magento2/commit/51e2fbc741d8f6892432f8e9b83eec2c1737874b)
 - [0564f7800a251b617f3ec5d993d4c48dbe972752](https://github.com/magento/magento2/commit/0564f7800a251b617f3ec5d993d4c48dbe972752)
 - [1d75c53591e415a36c30b7155eae61c9be2a5661](https://github.com/magento/magento2/commit/1d75c53591e415a36c30b7155eae61c9be2a5661)
 - [e21d3a837c9e05fcfc4b7359b500246afcdf2e5c](https://github.com/magento/magento2/commit/e21d3a837c9e05fcfc4b7359b500246afcdf2e5c)
 - [dd796f3a7c6079ec1e341b4d432498f7d737813f](https://github.com/magento/magento2/commit/dd796f3a7c6079ec1e341b4d432498f7d737813f)
 - [1b7badebcf23cf876978be97fb33a3b781f021ce](https://github.com/magento/magento2/commit/1b7badebcf23cf876978be97fb33a3b781f021ce)
 - [9b8912efae26457371a78275e3009db14baa305e](https://github.com/magento/magento2/commit/9b8912efae26457371a78275e3009db14baa305e)
 - [20dfcc65fbaa587766ade672d619e1cbde98dfa0](https://github.com/magento/magento2/commit/20dfcc65fbaa587766ade672d619e1cbde98dfa0)
 - [5809bee005e62527e935fecee1a68c26660f5ea0](https://github.com/magento/magento2/commit/5809bee005e62527e935fecee1a68c26660f5ea0)
 - [4fedd42fc4fd1fb4fd91ed501a6db01366af0e9a](https://github.com/magento/magento2/commit/4fedd42fc4fd1fb4fd91ed501a6db01366af0e9a)
 - [64f9f005b383d6f8e227ebdda0efe17bbfe7f934](https://github.com/magento/magento2/commit/64f9f005b383d6f8e227ebdda0efe17bbfe7f934)
 - [5a4b0077680e4b0e3e09322ed79f7f8f7990b6aa](https://github.com/magento/magento2/commit/5a4b0077680e4b0e3e09322ed79f7f8f7990b6aa)
 - [3592cf9f7d32ef22926e41e9de682b9b3657fa70](https://github.com/magento/magento2/commit/3592cf9f7d32ef22926e41e9de682b9b3657fa70)
 - [70897083ea25b71618278ffb66e225dcfda6ced7](https://github.com/magento/magento2/commit/70897083ea25b71618278ffb66e225dcfda6ced7)
 - [017da272abe3d461994c937f4c8196d50b8ef41c](https://github.com/magento/magento2/commit/017da272abe3d461994c937f4c8196d50b8ef41c)
 - [a020625517c036c3f671eccdb88b2ec772ce188c](https://github.com/magento/magento2/commit/a020625517c036c3f671eccdb88b2ec772ce188c)
 - [0111b2d5956a791ef1cc4a63a95299a8f98b7899](https://github.com/magento/magento2/commit/0111b2d5956a791ef1cc4a63a95299a8f98b7899)
 - [f168ca6067aee1caf741e9e124802a8d97e87205](https://github.com/magento/magento2/commit/f168ca6067aee1caf741e9e124802a8d97e87205)
 - [f4437415404d52eacfa18135b886d673b204b4f0](https://github.com/magento/magento2/commit/f4437415404d52eacfa18135b886d673b204b4f0)
 - [11c7fd4462c0c376ad3cbf9d7d107a870d914335](https://github.com/magento/magento2/commit/11c7fd4462c0c376ad3cbf9d7d107a870d914335)
 - [c9184f68ae5b066b4d166daf3ae9fd0639d4fdcd](https://github.com/magento/magento2/commit/c9184f68ae5b066b4d166daf3ae9fd0639d4fdcd)
 - [b974b487d21ed32795cb1d244ebf620f31663085](https://github.com/magento/magento2/commit/b974b487d21ed32795cb1d244ebf620f31663085)
 - [de8598c313b74b3f0bde8374a3d52d83022c2f2c](https://github.com/magento/magento2/commit/de8598c313b74b3f0bde8374a3d52d83022c2f2c)
 - [9230db6bdf4edf45e0ae8299c8c64a88d13aa9d4](https://github.com/magento/magento2/commit/9230db6bdf4edf45e0ae8299c8c64a88d13aa9d4)

The fix will be available with the upcoming 2.4.1 release.
