### ISSUE TITLE
Issue in compare page

### ISSUE THREAD

**Issue by deepaktiwariwebkul** [magento/magento2#25008]
### Preconditions (*)

1. Magento 2.3.2
2. CE

### Steps to reproduce (*)

1. Add products on the compare page.
2. View the comparison of the product attribute, in which some product attribute value is available and some product attribute values are not available. 

### Expected result (*)

1. The product attribute that has no value must show as N/A like in Magento's previous version.
https://prnt.sc/pia8i0

### Actual result (*)

1. No value is visible 
https://prnt.sc/pia9e7

**Comment by deepaktiwariwebkul** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @deepaktiwariwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @deepaktiwariwebkul, here is your [Magento instance](https://i-25008-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25008-2-3-develop.instances.magento-community.engineering/admin](https://i-25008-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21765` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @deepaktiwariwebkul. Thank you for your report. 
The issue has been fixed in magento/magento2#25585 by @ptylek in 2.3-develop branch
Related commit(s):
 - [9ea1d3fcce6043a660ffbb2157a0d8a137ed1965](https://github.com/magento/magento2/commit/9ea1d3fcce6043a660ffbb2157a0d8a137ed1965)
 - [1f010f148cdce4e17baaf02235b325b79b3bb8a1](https://github.com/magento/magento2/commit/1f010f148cdce4e17baaf02235b325b79b3bb8a1)

The fix will be available with the upcoming 2.3.5 release.
