### ISSUE TITLE
Error during image import if "no_selection" is set

### ISSUE THREAD

**Issue by mageonius** [magento/magento2#25026]
### Preconditions (*)

1. Magento 2.3.2 & 2.3-develop with multiple stores (2 example stores)

### Steps to reproduce (*)

1. Create new simple product
2. Upload image to product at Default scope, save product
3. Go to store 2 view scope and assign "Swatch" role to already uploaded image, save product
4. Go to global store view and ensude that "Swatch" label is not assigned on product, re-save product
5. Go to System -> Export and export already created product as CSV
6. Go to System -> Import and import CSV file with "Add/update" behavior

### Expected result (*)

1. Import will ends without any errors

### Actual result (*)

1. Import ended with error: 
`Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s): 1`

### Suggestions
This issue happens because in CSV file on one of store views key "swatch_image" is set as "no_selection". I think it's good idea to ignore this value during image import OR get rid of it during export.

**Comment by mageonius** [comment]
@shikhamis11 can you confirm this issue to make possible start working on it?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23088` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @mageonius. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [26d4b9299d8aefeb37c6cd9f3eb933b8ae23b1c9](https://github.com/magento/magento2/commit/26d4b9299d8aefeb37c6cd9f3eb933b8ae23b1c9)
 - [254a46c8a11683c3958b09b80e59343befa1e2b5](https://github.com/magento/magento2/commit/254a46c8a11683c3958b09b80e59343befa1e2b5)

The fix will be available with the upcoming `2.4.0` release.
