### ISSUE TITLE
Not clear code in product custom options import

### ISSUE THREAD

**Issue by pusachev** [magento/magento2#25069]
### Preconditions (*)

1. Magento 2.3.2
2. php7.2

### Steps to reproduce (*)

1. Create product with custom options in file without 'store_view_code' field
2. Start import product

### Expected result (*)

Notice: Undefined index: store_view_code in vendor/magento/module-catalog-import-export/Model/Import/Product/Option.php on line 2046 

### Actual result (*)

Throw exception if field 'store_view_code' is required or add checks on 'store_view_code' in vendor/magento/module-catalog-import-export/Model/Import/Product/Option.php

Why is unclear for me? 

Because we have this [code](https://github.com/magento/magento2/blob/d15db0ac45cdae53fb43802e358052c0b23b34f4/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L2089)  where expected 'store_view_code'  field and this [code](https://github.com/magento/magento2/blob/d15db0ac45cdae53fb43802e358052c0b23b34f4/app/code/Magento/CatalogImportExport/Model/Import/Product/Option.php#L1157) where '_custom_option_store' not required.

Best Regards,
Pavel

**Comment by mahesh-rajawat** [comment]
@shikhamis11 could you please check this issue?

**Comment by magento-engcom-team** [comment]
Hi @pusachev. Thank you for your report. 
The issue has been fixed in magento/magento2#25080 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [0f796ccced021764632aa031ed44ac8efddf66d4](https://github.com/magento/magento2/commit/0f796ccced021764632aa031ed44ac8efddf66d4)
 - [2138e68aeced33886a98406c5f26e1036385a495](https://github.com/magento/magento2/commit/2138e68aeced33886a98406c5f26e1036385a495)
 - [6ea86bbf765429d233bc9ab8515a9e3eae856af4](https://github.com/magento/magento2/commit/6ea86bbf765429d233bc9ab8515a9e3eae856af4)
 - [3e513d0fd839bb1d98f4ad991ba946c780310458](https://github.com/magento/magento2/commit/3e513d0fd839bb1d98f4ad991ba946c780310458)
 - [a7f7d0ae1660e13f08d9e5fc5246429f40299a92](https://github.com/magento/magento2/commit/a7f7d0ae1660e13f08d9e5fc5246429f40299a92)
 - [bf8b1e4e880d227c052641faec2973b853d8cb1a](https://github.com/magento/magento2/commit/bf8b1e4e880d227c052641faec2973b853d8cb1a)

The fix will be available with the upcoming 2.3.5 release.
