### ISSUE TITLE
Bulk update product attributes issue - Magento 2.3.3

### ISSUE THREAD

**Issue by Userr017** [magento/magento2#25097]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.2, 7.3

### Steps to reproduce (*)

1. Choose few products
2. Open page "Update Attributes"
3. Choose Attributes
4. Save

### Expected result (*)

1. Starts "Update attributes for selected products".

### Actual result (*)

1. Doesn't start "Update attributes for selected products".
2. Summary all the time "Pending, in queue..."
![task](https://user-images.githubusercontent.com/26794034/66936530-87e7c080-f046-11e9-8bc5-956409861c22.JPG)
![task1](https://user-images.githubusercontent.com/26794034/66936561-97ffa000-f046-11e9-955b-bd7c51a80cb0.png)

**Comment by hostep** [comment]
@Userr017: please make sure your cronjobs are running, here is [the documentation](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html) around that.

If your cronjobs aren't running, they won't spawn the queue consumers, and nothing will happen with the messages in the queue.
This seems to be what you are experiencing.

If cronjobs are running and it still doesn't work, please check if you do have queue consumers running:
```
$ ps aux | grep -i [c]onsumers
me      72903   0.2  0.7  5502880 125632 s001  S     7:54PM   0:02.35 php /path/to/magento/bin/magento queue:consumers:start exportProcessor --single-thread --max-messages=10000
me      72905   0.1  0.7  5502880 125724 s001  S     7:54PM   0:02.34 php /path/to/magento/bin/magento queue:consumers:start codegeneratorProcessor --single-thread --max-messages=10000
me      72901   0.1  0.8  5502880 126436 s001  S     7:54PM   0:02.38 php /path/to/magento/bin/magento queue:consumers:start product_action_attribute.website.update --single-thread --max-messages=10000
me      72899   0.0  0.9  5506016 142644 s001  S     7:54PM   0:02.68 php /path/to/magento/bin/magento queue:consumers:start product_action_attribute.update --single-thread --max-messages=10000
```

If you don't see these consumers, then you'll need to figure out why those aren't getting spawned.
If you have specified something like the following in your `app/etc/env.php` file, that will prevent consumers to start, but I doubt that will be the case here?
```
    'cron_consumers_runner' => [
        'cron_run' => false
    ],
```
Also see [docs](https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html#configuration).

If you still don't know why consumers aren't getting spawned, then try debugging in [`Magento\MessageQueue\Model\Cron\ConsumersRunner::run`](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/MessageQueue/Model/Cron/ConsumersRunner.php#L101) and see if you can figure out why they aren't getting spawned.

Hope this helps.

I'm closing this issue since everything seems to work fine on a vanilla 2.3.3 installation while the cronjobs are running.
