### ISSUE TITLE
Elasticsearch not able to search for term with a slash / in it

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#25110]
### Preconditions (*)
1. Magento 2.3.3
2. Elasticsearch 6+

### Steps to reproduce (*)
1. Enable Elasticsearch 6+
2. Add a product with a SKU with a slash / in it.
3. Search in the frontend for that exact SKU.

### Expected result (*)
1. Find that particular product without errors.

### Actual result (*)
1. Search results in an error.

### Note:
similar issue #20689

**Comment by krishprakash** [comment]
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-25110-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25110-2-3-3.instances.magento-community.engineering/admin](https://i-25110-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21895` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Also found similar issue #20689

**Comment by jorgb90** [comment]
Thanks for confirming @krishprakash

**Comment by jorgb90** [comment]
Is this going to be fixed?

**Comment by jorgb90** [comment]
Apparently not?

**Comment by addMitt** [comment]
Would also like some kind of solution to this. We have a rather extensive industrial catalog and many manufacturers make heavy use of forward slashes in their product names.

**Comment by magento-engcom-team** [comment]
Hi @jorgb90. Thank you for your report. 
The issue has been fixed in magento/magento2#30318 by @wojtekn in 2.4-develop branch
Related commit(s):
 - [ce1263da089d5b8ca28bc8689480092db0924d33](https://github.com/magento/magento2/commit/ce1263da089d5b8ca28bc8689480092db0924d33)
 - [ccec05add626879219b858485d8c06aeecc1a145](https://github.com/magento/magento2/commit/ccec05add626879219b858485d8c06aeecc1a145)
 - [970d1793bc408ad99cf959197c77dec424f4cefc](https://github.com/magento/magento2/commit/970d1793bc408ad99cf959197c77dec424f4cefc)
 - [38c4a3e01ebc3dd0d18286efba20d03373deb830](https://github.com/magento/magento2/commit/38c4a3e01ebc3dd0d18286efba20d03373deb830)
 - [88f6101fe15eda61471822169670b744914fdf40](https://github.com/magento/magento2/commit/88f6101fe15eda61471822169670b744914fdf40)

The fix will be available with the upcoming 2.4.2 release.
