### ISSUE TITLE
Elasticsearch 6.8: Search For Part Of Product Name Yields No Results

### ISSUE THREAD

**Issue by sprankhub** [magento/magento2#25115]
### Preconditions (*)
1. Magento 2.3.3 & 2.3-develop
2. Elasticsearch 6.8
3. Magento Sample Data

### Steps to reproduce (*)
1. Configure Elasticsearch 6.0+ in the configuration.
2. Search for "hoo".

### Expected result (*)
1. All products, whose name contain "hoo" should be shown as a search result. For instance, "Circe Hooded Ice Fleece".

### Actual result (*)
1. No products, whose name contain "hoo" are shown.

It seems that it is simply not possible to search for any substring of a word of a product name.

**Comment by sprankhub** [comment]
Unfortunately, I cannot easily reproduce the issue on a vanilla installation, because the contributor assistant does not support Elasticsearch yet (https://github.com/magento/community-features/issues/145).

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21947` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by adarshkhatri** [comment]
Any update on this?

**Comment by onepack** [comment]
Same for multiple shops here

**Comment by AleksLi** [comment]
@sprankhub Seems like the ElasticSearch is searching by the whole word not using the part of the word. I'm debugging this right now and trying different queries using PostMan.

I've created a couple products on my local instance and trying different things to make it work. Let's see.

I know for sure that the whole word matching is working perfectly.

**Comment by AleksLi** [comment]
@sprankhub I just found out how to make it work from the perspective of ElasticSearch.
I have no idea yet how to implement this inside the Magento and maybe someone will tell me or give me the idea.

_I have created several products with part of the name "Hoodie". For example "Cotton Hoodie", "black hoodie" and others. I took the part of request from the Magento workflow calling elasticsearch for response. I tried "ood"  - not response, then I tried "hoodie" and I've got the requested products._

So, my solution was to try wildcard from the elasticsearch docs. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html 
The example below is working fine.

```{
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "visibility": [
                            "3",
                            "4"
                        ]
                    }
                }
            ],
            "should": [
                {
                    "wildcard": {
                        "_search": {
                            "value": "*ood*",
                            "boost": 1
                        }
                    }
                }
            ],
            "minimum_should_match": 1
        }
    },
    "aggregations": {
        "price_bucket": {
            "extended_stats": {
                "field": "price_0_1"
            }
        },
        "category_bucket": {
            "terms": {
                "field": "category_ids",
                "size": 500
            }
        }
    }
}`

Notice: wildcard search text (part of the word) should be wrapped in "*" to be like "LIKE" query in MYSQL.

**Comment by AleksLi** [comment]
@magento I am working on it

**Comment by sprankhub** [comment]
Thanks @AleksLi!

**Comment by AleksLi** [comment]
### NEED HELP
I will need some help figuring out how to init Wildcard requests for the Catalogsearch Queries.

Here is what I have found. There is a type of query like "FilteredQuery" and there is a type called \Magento\Elasticsearch\SearchAdapter\Filter\Builder\Wildcard which is handling the filteredQuery. THere is the mapper to switch between the filters types \Magento\Framework\Search\Request\Mapper. But I haven't found any configuration how to set query type to Wildcard instead of the simple Match Query and I **need HELP** with this.

Another thing I have found is how the quick_search_container written. It is the configuration, I strongly believe, app/code/Magento/CatalogSearch/etc/search_request.xml.

**ANYONE who knows how to handle that please reach out to me or in this issue in COmment.**

**Comment by gabrieldagama** [comment]
As discussed with @AleksLi this issue seems to be fixed on 2.4. 

Internal QA will re-test it.

**Comment by engcom-Bravo** [comment]
The issue is not reproducible on the latest 2.4-develop and Elastic Search Version: 7.9.2
According to the [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html), Magento no longer supports Elasticsearch 2.x, 5.x, and 6.x 

### Manual testing scenario
1 . Configure Elasticsearch 7 in the configuration.
2 Go to Store -> Configuration -> Catalog -> Catalog Search and verify that Elasticsearch 7 is selected as Search Engine
3. Go to Storefront and Search for "hoo"

### Actual result 
All products, which name contains "hoo" shown as a search result. 
![Search result](https://user-images.githubusercontent.com/51680745/95563917-b49aa200-0a26-11eb-8f78-bf2a7f07f8f5.png)

Also tested Catalog - Products. All products, which name contains "hoo" shown as a search result. 
![AdminSearch](https://user-images.githubusercontent.com/51680745/95564014-d562f780-0a26-11eb-9621-358c883f6ca4.png)

**Comment by sprankhub** [comment]
Awesome!
