### ISSUE TITLE
Issue with reorder when disabled reorder setting from admin

### ISSUE THREAD

**Issue by ghost** [magento/magento2#25130]
There is no check in reorder controller to validate the reorder configuration.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Place order from frontend as a customer or guest
2. Open order view page from frontend
3. Login into admin panel
4. Disable reorder option from admin. Navigate to Store -> Configuration-> Sales -> Reorder -> Allow Order and set this to **NO**
5. Go to opened order view page and click on reorder.

![Selection_011](https://user-images.githubusercontent.com/15954089/67052107-cff80780-f15a-11e9-9725-9f963b70a014.png)
![Selection_009](https://user-images.githubusercontent.com/15954089/67052119-d5555200-f15a-11e9-9f73-ec241d4a1500.png)

### Expected result (*)

1. Reorder should be disabled and there should be some error message like Reorder is disabled

### Actual result (*)

1. Able to reorder. 
![Selection_010](https://user-images.githubusercontent.com/15954089/67052127-dbe3c980-f15a-11e9-864b-34c3e164588a.png)

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25130-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25130-2-3-develop.instances.magento-community.engineering/admin](https://i-25130-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
I am able to reproduce issue on vanilla instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21919` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @rahulwebkul. Thank you for your report. 
The issue has been fixed in magento/magento2#26051 by @edenduong in 2.4-develop branch
Related commit(s):
 - [689c1f62069f7cb4520820013cebcb3b8b906dc6](https://github.com/magento/magento2/commit/689c1f62069f7cb4520820013cebcb3b8b906dc6)
 - [3e456b29a421a03f635f0d22701bf378c935f9b0](https://github.com/magento/magento2/commit/3e456b29a421a03f635f0d22701bf378c935f9b0)
 - [8928539dea7d79501b888d2affdd00220952bb72](https://github.com/magento/magento2/commit/8928539dea7d79501b888d2affdd00220952bb72)
 - [74ffaf38a237204517d51e6cfd21421949335979](https://github.com/magento/magento2/commit/74ffaf38a237204517d51e6cfd21421949335979)
 - [c4baf83e4d811ba436b4fdb1205f9abdf4f655f9](https://github.com/magento/magento2/commit/c4baf83e4d811ba436b4fdb1205f9abdf4f655f9)

The fix will be available with the upcoming 2.4.0 release.
