### ISSUE TITLE
Magento 2.3: Import fails if configurable attribute has an equal sign in its value

### ISSUE THREAD

**Issue by viniciusfabri** [magento/magento2#25188]
### Preconditions (*)
1. Magento 2.3.2 (2.3-develop also works) - PHP 7.1.26
2. Sample data Installer

### Steps to reproduce (*)
1. Change one of the attributes used by the configurable products (Size for instance) to have an = sign in its value
2. Export a configurable product that uses this attribute
3. Try to import the CSV from the previous step

### Expected result (*)
1. Product should be imported correctly

### Actual result (*)
1. Product import fails

### Description
This happens because when Magento is creating the product variations, it uses the equal sign as a separator, but if the attribute value has an equal sign in it, it breaks. We fixed this by adding a limit of '2' to the explode calls in these lines:
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php#L576
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/ConfigurableImportExport/Model/Import/Product/Type/Configurable.php#L637

**Comment by dhoang89** [comment]
@magento I'm working on it

**Comment by VladimirZaets** [comment]
Hi @viniciusfabri. Thank you for your report. 
The issue has been fixed in magento/magento2#25194 by @dhoang89 in 2.4-develop branch
Related commit(s):
 - [cded4b1f2a72c9f6cf568d4c85ff31a16c0d61ac](https://github.com/magento/magento2/commit/cded4b1f2a72c9f6cf568d4c85ff31a16c0d61ac)
 - [904b2342c7f7ce391103091d1c9e0406af247aed](https://github.com/magento/magento2/commit/904b2342c7f7ce391103091d1c9e0406af247aed)
 - [c983d415d2592e93dcbc96abe1ad23ef45b2fda5](https://github.com/magento/magento2/commit/c983d415d2592e93dcbc96abe1ad23ef45b2fda5)
 - [c721ae4d574002a30cf8d98ff2c2ebfd59d7e91f](https://github.com/magento/magento2/commit/c721ae4d574002a30cf8d98ff2c2ebfd59d7e91f)
 - [e9226fe1d99c6e25378a5032d8f3b3007335ebc9](https://github.com/magento/magento2/commit/e9226fe1d99c6e25378a5032d8f3b3007335ebc9)
 - [2dc4f1e9adc7f6f943680ce8eba1d2f243263dba](https://github.com/magento/magento2/commit/2dc4f1e9adc7f6f943680ce8eba1d2f243263dba)
 - [2dd6b141ae43a6b9ce924909cddf535a0225c949](https://github.com/magento/magento2/commit/2dd6b141ae43a6b9ce924909cddf535a0225c949)

The fix will be available with the upcoming 2.4.0 release.
