### ISSUE TITLE
Google API - Analytics code not showing up in page source, thus no data

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#2518]
Inspite having set the UA code in the Google API config settings via the backend, no data is showing up in Analytics. When inspecting the page source there is no analytics script present.

![2015-11-25_13h47_26](https://cloud.githubusercontent.com/assets/13572447/11397648/4b356380-937b-11e5-806c-4ece94099dc5.png)

<script>
(function(i,s,o,g,r,a,m){i'GoogleAnalyticsObject'=r;ir=ir||function()
{ (i[r].q=i[r].q||[]).push(arguments)}

,ir.l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)0;a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-xxxxxxxx-x', 'auto');
ga('send', 'pageview');

</script>

**Comment by SidneyBilliet** [comment]
Anybody? This is urgent, please

**Comment by mazhalai** [comment]
@SidneyBilliet thank you for reporting, we have created MAGETWO-46264 to investigate.

**Comment by devhn** [comment]
Any news on this?

**Comment by vzabaznov** [comment]
Hi @SidneyBilliet , seems like issue cannot be reporoduced on fresh magento version, please check it, and if you think that not, feel free to write here or to open new one

**Comment by hostep** [comment]
We also run into this with Magento 2.1.0

This is caused by the setting: General => Web => Default Cookie Settings => Cookie Restriction Mode => Yes

While it's questionable if this setting should disable outputting the Google Analytics code, you would expect that when you accept the cookie message, the GA code appears on the page. But that isn't the case.

@vzabaznov: I think you should reopen this after you verified my above statement also triggers this bug on a clean Magento installation (which I haven't tested yet).

**Comment by gewaechshaus** [comment]
We can verify that it doesn't work in our case with a composer installed 2.1.0, but setting General => Web => Default Cookie Settings => Cookie Restriction Mode => No does not have any effect...

**Comment by JHoyosl** [comment]
Hi, I have a issue with analytics. When I checked the console, it shows a sintaxys error, becouse missing a " ' ", you can add in block on "code/Magento/GoogleAnalytics/Block/Ga.php" on line 83, there miss a single colon. Hope this help some one.
