### ISSUE TITLE
Issue with tier price 0 when saving product second time

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#25195]
### Preconditions (*)
1.Fresh Magento 2.3.3 or any Magento 2.3 setup

### Steps to reproduce (*)
1. Create a simple Test product
2. Set the normal price 100 or whatever you want
3. Set the tier price 0 for "All Groups" with "1" Qty. 
<img width="967" alt="Screenshot 2019-10-21 at 14 44 37" src="https://user-images.githubusercontent.com/17308601/67206134-59d0fa80-f411-11e9-858a-ffd17a0c4b2f.png">

4. Save the product 
5. You can see the product tier price is 0 saved and on the frontend, you can see 0 prices which is expected
<img width="1354" alt="Screenshot 2019-10-21 at 13 09 44" src="https://user-images.githubusercontent.com/17308601/67206237-8c7af300-f411-11e9-8fd9-3640ea655382.png">
6. Edit the same product again from the backend.

7. Open the Advance pricing section and set the Tier price "10" for "All Groups" and "1" Qty.

8. Save the product

9. You can see "10" price on frontend and backend which is expected.

10. Now edit the product again from backend and open Advance pricing section

11. Set the price "0" for "All Groups" with "1" Qty.

12. Save the product

### Expected result (*)

1. After saving the second time product price should be displayed which we are saving(In this case 0 should be display)

### Actual result (*)

1. Price is showing the Non-zero price during the second time.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21951` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Shubham0492** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul, here is your [Magento instance](https://i-25195-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25195-2-3-develop.instances.magento-community.engineering/admin](https://i-25195-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment]
Hi @keyurshah070. Thank you for your report. 
The issue has been fixed in magento/magento2#26162 by @ravi-chandra3197 in 2.4-develop branch
Related commit(s):
 - [ffab78e0cb1c2a73ffbded3cda0c75cd0ff9542d](https://github.com/magento/magento2/commit/ffab78e0cb1c2a73ffbded3cda0c75cd0ff9542d)
 - [ee152fcab0a5913d21d79ed4ced54a65c96f76bc](https://github.com/magento/magento2/commit/ee152fcab0a5913d21d79ed4ced54a65c96f76bc)
 - [918fd028fd9d768946e52a4edbcbd4dc0a77a434](https://github.com/magento/magento2/commit/918fd028fd9d768946e52a4edbcbd4dc0a77a434)
 - [f309ae042236736db0a964e533e33baa0a0e5142](https://github.com/magento/magento2/commit/f309ae042236736db0a964e533e33baa0a0e5142)

The fix will be available with the upcoming 2.4.0 release.
