### ISSUE TITLE
The requested package magento/module-bundle-sample-data could not be found in any version, there may be a typo in the package name

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#2520]
Following: http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data-composer.html

```
$ composer require magento/module-bundle-sample-data:2.0.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/module-bundle-sample-data could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by buskamuza** [comment]
Hi @jameswithers ,
does this command work for you `bin/magento sampledata:deploy`?

**Comment by jameswithers** [comment]
@buskamuza That worked.

Can the documentation at http://devdocs.magento.com/guides/v2.0/install-gde/install/web/install-web-sample-data-composer.html be updated to reference this command?

The version of the sample data appears as 100, not 2.*

**Comment by mazhalai** [comment]
Pinging @xcomSteveJohnson for doc update.

**Comment by buskamuza** [comment]
The documentation has been updated.

**Comment by jameswithers** [comment]
On a fresh install of Magento using composer (before the Magento setup wizard), you get:

```
[root@demo html]# bin/magento sampledata:deploy
./composer.json has been updated
Loading composer repositories with package information



  [Composer\Downloader\TransportException]
  The 'https://repo.magento.com/packages.json' URL required authentication.
  You must be using the interactive console to authenticate



require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]


There is an error during sample data deployment.
```

This is worked around by:

`[root@demo html]# composer update`

**Comment by markshust** [comment]
@jameswithers @davidalger is the last post (`composer update`) the appropriate fix for this? It seems like a hack. Why isn't the repository correctly loading auth credentials on the first run?

**Comment by davidalger** [comment]
@markoshust The original issue had nothing to do with the functionality of sampledata:deploy, and was fixed in a documentation update. As for the `composer update` being a valid fix? No, it's a workaround for a known bug in sampledata:deploy, which is fixed in develop last I checked. It was running `composer update` internally, which doesn't work exactly the same for authenticated repositories on a non-interactive console (which is what it has when run from sub-called inside the PHP based CLI tool).

**Comment by Greko2017** [comment]
These 2 things worked for me

I needed to add the repository reference to my composer.json because it wasn't there

"repositories": [
         {
             "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
I needed to rename my auth.json.sample to auth.json and add the public and private keys to the json.

{
    "http-basic": {
        "repo.magento.com": {
            "username": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        }
    }
 }
If you want to input your private and public keys manually then do not include the auth.json

 [https://prnt.sc/st4iga]
