### ISSUE TITLE
RSS Feed - first load not working

### ISSUE THREAD

**Issue by JuraseQ** [magento/magento2#25211]
### Preconditions (*)

1. Magento 2.3.x & 2.3-develop
2. PHP 7.2.21 (i believe any other version too).

### Steps to reproduce (*)

1. Enable standard RSS Feed module.
2. Enable RSS Feed for New Products and Special Products.
![2020-07-21_16-10-30](https://user-images.githubusercontent.com/3409584/88184380-3c2afe80-cbf8-11ea-9fa3-2975984ec2b1.jpg)

3. Proceed to domain.tld/rss
![image](https://user-images.githubusercontent.com/51680850/67367709-b4d43000-f57e-11e9-81b0-894e0722742a.png)
4. Choose any channel.(New product in my case)
5. We get an exception
![image](https://user-images.githubusercontent.com/51680850/67367899-16949a00-f57f-11e9-9c6a-7c3fa11a35f5.png)
6. Refresh of site will make RSS Feed work. The point is that it's not working every time after compile.
![image](https://user-images.githubusercontent.com/51680850/67367970-2c09c400-f57f-11e9-9451-ad38e2200260.png)

### Expected result (*)

1. Module should output XML file

### Actual result (*)

> 1 exception(s):
Exception #0 (Zend\Feed\Writer\Exception\InvalidArgumentException): Invalid parameter: parameter must be a non-empty string

### What i found (*)
I debugged it and in Zend\Feed\Writer\AbstractFeed in method setTitle there is condition:
`        if ((empty($title) && ! is_numeric($title)) || ! is_string($title)) {
            throw new Exception\InvalidArgumentException('Invalid parameter: parameter must be a non-empty string');
        }`

$title is an instance of 'Magento\Framework\Phrase' that is why it's throwing an exception.
When i changed the condition to:

`if ((empty($title) && ! is_numeric($title)) || (! is_string($title) && strpos(get_class($title), 'Magento\Framework\Phrase') === false)) {`

I tried this way just temporary for tests but it will require to modify data before it will reach Zend's library method.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22027` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36069` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @JuraseQ. Thank you for your report. 
The issue has been fixed in magento/magento2#29455 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [b2a8ff40814a7646d2f9f09eebd18bbe2d90d57a](https://github.com/magento/magento2/commit/b2a8ff40814a7646d2f9f09eebd18bbe2d90d57a)
 - [176ce4321019adb3ca3f4f9fd6851d2ad45e1cfc](https://github.com/magento/magento2/commit/176ce4321019adb3ca3f4f9fd6851d2ad45e1cfc)
 - [1786065cb94a40ed059228d89267912bb3d5b8f2](https://github.com/magento/magento2/commit/1786065cb94a40ed059228d89267912bb3d5b8f2)
 - [8fdaa15f3a3aa52d5adc434628d43c2841a3f21e](https://github.com/magento/magento2/commit/8fdaa15f3a3aa52d5adc434628d43c2841a3f21e)
 - [0fa559eddfa76160d164a97ff17b8ca244a89014](https://github.com/magento/magento2/commit/0fa559eddfa76160d164a97ff17b8ca244a89014)
 - [fb06211c46b735e148a460a6ba8f25f621f7b8ac](https://github.com/magento/magento2/commit/fb06211c46b735e148a460a6ba8f25f621f7b8ac)
 - [3f304d9b78024ac7761f1e8b4539ae804f6ebc64](https://github.com/magento/magento2/commit/3f304d9b78024ac7761f1e8b4539ae804f6ebc64)
 - [8896804fc8dc5f334d8f95fc268280857a74edff](https://github.com/magento/magento2/commit/8896804fc8dc5f334d8f95fc268280857a74edff)
 - [745a5a69c5185e844917333ffcc03002b89784c5](https://github.com/magento/magento2/commit/745a5a69c5185e844917333ffcc03002b89784c5)
 - [1ab0e35fc11608b62e2512f3887feee97ed5548d](https://github.com/magento/magento2/commit/1ab0e35fc11608b62e2512f3887feee97ed5548d)

The fix will be available with the upcoming 2.4.1 release.
