### ISSUE TITLE
Numerical placeholder count in Phrase starts with %1, however js code assumes 0%

### ISSUE THREAD

**Issue by vitcra** [magento/magento2#25243]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Check this code: https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/Phrase/Renderer/Placeholder.php#L43

2. Compare to: https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Ui/view/frontend/web/js/model/messages.js#L52

### Expected result (*)

Js version of __('Carrier with such method not found: %1, %2', 'one', 'two') should produce the message of 'Carrier with such method not found: **one, two**'.

See for example: https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Checkout/Model/ShippingInformationManagement.php#L198

### Actual result (*)

Js version of __('Carrier with such method not found: %1, %2', 'one', 'two') produces the message of 'Carrier with such method not found: **two, one**'.

**Comment by engcom-Delta** [comment]
Issue is reproducible on 2.3-develop.
Modify string to `__('Carrier with such method not found: %1, %2', "one test", "two test")` in https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Checkout/Model/ShippingInformationManagement.php#L198
![#25243issue_2](https://user-images.githubusercontent.com/51681379/67550546-6efaa180-f70f-11e9-8db5-b3acdc5d3c34.jpg)

**Result:**
![#25243issue](https://user-images.githubusercontent.com/51681379/67550579-7de15400-f70f-11e9-99fb-94919100c52e.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22126` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @vitcra. Thank you for your report. 
The issue has been fixed in magento/magento2#25359 by @korostii in 2.4-develop branch
Related commit(s):
 - [2596ca7de56a5175338230a7e54d4e8fda902851](https://github.com/magento/magento2/commit/2596ca7de56a5175338230a7e54d4e8fda902851)
 - [2f5909e408ae977435540b260fbabbfa4462a062](https://github.com/magento/magento2/commit/2f5909e408ae977435540b260fbabbfa4462a062)
 - [d1b63cbb6b682597b0a725e672f10c1305ac643f](https://github.com/magento/magento2/commit/d1b63cbb6b682597b0a725e672f10c1305ac643f)
 - [f08857bbb8950a154e67f71bb83f4a19dc341640](https://github.com/magento/magento2/commit/f08857bbb8950a154e67f71bb83f4a19dc341640)
 - [71ca4bb2bc4e490cc696849b5a943b186f5caa6b](https://github.com/magento/magento2/commit/71ca4bb2bc4e490cc696849b5a943b186f5caa6b)
 - [d79bf5e53a42020220abc586ef717a4b83470dcd](https://github.com/magento/magento2/commit/d79bf5e53a42020220abc586ef717a4b83470dcd)
 - [3d36928e0b5043b847c724b771bc863d58ddceef](https://github.com/magento/magento2/commit/3d36928e0b5043b847c724b771bc863d58ddceef)
 - [9db06e58b1b93c09c009884b1e2ed54a52fa3df1](https://github.com/magento/magento2/commit/9db06e58b1b93c09c009884b1e2ed54a52fa3df1)
 - [df48d3e69fc17c7b54ddf2e33840da3ca3af2460](https://github.com/magento/magento2/commit/df48d3e69fc17c7b54ddf2e33840da3ca3af2460)
 - [9ccac04ff5908efd749c42187bc2ab79798f0d6f](https://github.com/magento/magento2/commit/9ccac04ff5908efd749c42187bc2ab79798f0d6f)
 - [ce191710acfaaf8457d2bb66c192d8d3bb984844](https://github.com/magento/magento2/commit/ce191710acfaaf8457d2bb66c192d8d3bb984844)

The fix will be available with the upcoming 2.4.0 release.
