### ISSUE TITLE
setCustomDiscount on quote maxes out at single cost of each item

### ISSUE THREAD

**Issue by cralls** [magento/magento2#25293]
# Preconditions (*)
1. Magento version 2.2.6

### Steps to reproduce (*)
1. Add a product to the order with a quantity greater than 1
2. Add a shipping amount and a tax amount to the grand total
3. Use \Magento\Backend\Model\Session\Quote:setCustomDiscount method to create a discount that is greater than the price of the product but less than the grand total which includes shipping and tax

### Expected result (*)
1. The invoice charges the grand total minus the discount amount

### Actual result (*)
1.  The invoice only applies a discount equal to the amount of the product in the cart

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul, here is your [Magento instance](https://i-25293-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25293-2-3-develop.instances.magento-community.engineering/admin](https://i-25293-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment]
Hello @cralls 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!
