### ISSUE TITLE
PHP Extension 0 must be loaded - XML Parse mistake?

### ISSUE THREAD

**Issue by ScreamingDev** [magento/magento2#253]
The requiered extensions for install can be found in config/install/databases/mysql4/extensions

Somehow the given confg.xml for installation is not parsed correct. 
https://github.com/magento/magento2/blob/master/lib/Varien/Simplexml/Config.php#L153

$this->_xml has "config/install/databases/mysql4/extensions" but it is empty.

Running in Ubuntu 12.10, PHP 5.4.6-1ubuntu1.1 (cli), Zend Engine v2.4.0, Apache/2.2.22

**Comment by slavvka** [comment]
Hi @ScreamingDev. Thank you for your report. 
The issue has been fixed in magento/magento2#28105 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [dbaf8a55e740741043231ad7e06ea6950064126c](https://github.com/magento/magento2/commit/dbaf8a55e740741043231ad7e06ea6950064126c)
 - [9479c3ac03a5d2a152f788dd75fd7955eb646b12](https://github.com/magento/magento2/commit/9479c3ac03a5d2a152f788dd75fd7955eb646b12)
 - [9d4223894e8b32fa3b6f7e44e4349f247b358fab](https://github.com/magento/magento2/commit/9d4223894e8b32fa3b6f7e44e4349f247b358fab)
 - [003162a43254c9f7b5d7ef335384d8e6d444dedc](https://github.com/magento/magento2/commit/003162a43254c9f7b5d7ef335384d8e6d444dedc)
 - [689bbeaefa1d8d69448a020d893a12a14ce9bcc4](https://github.com/magento/magento2/commit/689bbeaefa1d8d69448a020d893a12a14ce9bcc4)
 - [74a95e1adb476c49e9c1f4b4a0bab27e9b02df16](https://github.com/magento/magento2/commit/74a95e1adb476c49e9c1f4b4a0bab27e9b02df16)
 - [e4d9a056c6ce665642c6475eb2833a6781a86442](https://github.com/magento/magento2/commit/e4d9a056c6ce665642c6475eb2833a6781a86442)
 - [b059e515fcce915799fdc47d4d74d4b0d1e45690](https://github.com/magento/magento2/commit/b059e515fcce915799fdc47d4d74d4b0d1e45690)
 - [56b5ab696d0b260be457d057c893c53970fe58a2](https://github.com/magento/magento2/commit/56b5ab696d0b260be457d057c893c53970fe58a2)
 - [6287c86d43acde34f0f410f61985b328df92c4d2](https://github.com/magento/magento2/commit/6287c86d43acde34f0f410f61985b328df92c4d2)
 - [b7897f19c759bd3f0f490a5aec8d56844799ba00](https://github.com/magento/magento2/commit/b7897f19c759bd3f0f490a5aec8d56844799ba00)
 - [ca9078c7928ee2129d9e8633907d02c675149eda](https://github.com/magento/magento2/commit/ca9078c7928ee2129d9e8633907d02c675149eda)
 - [e3555dcfc3327d65e99f0a64672dd70eb56f93e5](https://github.com/magento/magento2/commit/e3555dcfc3327d65e99f0a64672dd70eb56f93e5)
 - [709440b59cc25ff5bb69e1655e7ae1832252f0ea](https://github.com/magento/magento2/commit/709440b59cc25ff5bb69e1655e7ae1832252f0ea)
 - [60845021ee79c5b66ea89c34c29b59ccdbdf9807](https://github.com/magento/magento2/commit/60845021ee79c5b66ea89c34c29b59ccdbdf9807)

The fix will be available with the upcoming 2.4.1 release.

**Comment by slavvka** [comment]
Hi @ScreamingDev. Thank you for your report. 
The issue has been fixed in magento/magento2#27956 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [dbaf8a55e740741043231ad7e06ea6950064126c](https://github.com/magento/magento2/commit/dbaf8a55e740741043231ad7e06ea6950064126c)
 - [9479c3ac03a5d2a152f788dd75fd7955eb646b12](https://github.com/magento/magento2/commit/9479c3ac03a5d2a152f788dd75fd7955eb646b12)
 - [9d4223894e8b32fa3b6f7e44e4349f247b358fab](https://github.com/magento/magento2/commit/9d4223894e8b32fa3b6f7e44e4349f247b358fab)
 - [003162a43254c9f7b5d7ef335384d8e6d444dedc](https://github.com/magento/magento2/commit/003162a43254c9f7b5d7ef335384d8e6d444dedc)
 - [689bbeaefa1d8d69448a020d893a12a14ce9bcc4](https://github.com/magento/magento2/commit/689bbeaefa1d8d69448a020d893a12a14ce9bcc4)
 - [74a95e1adb476c49e9c1f4b4a0bab27e9b02df16](https://github.com/magento/magento2/commit/74a95e1adb476c49e9c1f4b4a0bab27e9b02df16)
 - [e4d9a056c6ce665642c6475eb2833a6781a86442](https://github.com/magento/magento2/commit/e4d9a056c6ce665642c6475eb2833a6781a86442)
 - [b059e515fcce915799fdc47d4d74d4b0d1e45690](https://github.com/magento/magento2/commit/b059e515fcce915799fdc47d4d74d4b0d1e45690)

The fix will be available with the upcoming 2.4.1 release.

**Comment by slavvka** [comment]
Hi @ScreamingDev. Thank you for your report. 
The issue has been fixed in magento/magento2#28105 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [dbaf8a55e740741043231ad7e06ea6950064126c](https://github.com/magento/magento2/commit/dbaf8a55e740741043231ad7e06ea6950064126c)
 - [9479c3ac03a5d2a152f788dd75fd7955eb646b12](https://github.com/magento/magento2/commit/9479c3ac03a5d2a152f788dd75fd7955eb646b12)
 - [9d4223894e8b32fa3b6f7e44e4349f247b358fab](https://github.com/magento/magento2/commit/9d4223894e8b32fa3b6f7e44e4349f247b358fab)
 - [003162a43254c9f7b5d7ef335384d8e6d444dedc](https://github.com/magento/magento2/commit/003162a43254c9f7b5d7ef335384d8e6d444dedc)
 - [689bbeaefa1d8d69448a020d893a12a14ce9bcc4](https://github.com/magento/magento2/commit/689bbeaefa1d8d69448a020d893a12a14ce9bcc4)
 - [74a95e1adb476c49e9c1f4b4a0bab27e9b02df16](https://github.com/magento/magento2/commit/74a95e1adb476c49e9c1f4b4a0bab27e9b02df16)
 - [e4d9a056c6ce665642c6475eb2833a6781a86442](https://github.com/magento/magento2/commit/e4d9a056c6ce665642c6475eb2833a6781a86442)
 - [b059e515fcce915799fdc47d4d74d4b0d1e45690](https://github.com/magento/magento2/commit/b059e515fcce915799fdc47d4d74d4b0d1e45690)
 - [56b5ab696d0b260be457d057c893c53970fe58a2](https://github.com/magento/magento2/commit/56b5ab696d0b260be457d057c893c53970fe58a2)
 - [6287c86d43acde34f0f410f61985b328df92c4d2](https://github.com/magento/magento2/commit/6287c86d43acde34f0f410f61985b328df92c4d2)
 - [b7897f19c759bd3f0f490a5aec8d56844799ba00](https://github.com/magento/magento2/commit/b7897f19c759bd3f0f490a5aec8d56844799ba00)
 - [ca9078c7928ee2129d9e8633907d02c675149eda](https://github.com/magento/magento2/commit/ca9078c7928ee2129d9e8633907d02c675149eda)
 - [e3555dcfc3327d65e99f0a64672dd70eb56f93e5](https://github.com/magento/magento2/commit/e3555dcfc3327d65e99f0a64672dd70eb56f93e5)
 - [709440b59cc25ff5bb69e1655e7ae1832252f0ea](https://github.com/magento/magento2/commit/709440b59cc25ff5bb69e1655e7ae1832252f0ea)
 - [60845021ee79c5b66ea89c34c29b59ccdbdf9807](https://github.com/magento/magento2/commit/60845021ee79c5b66ea89c34c29b59ccdbdf9807)

The fix will be available with the upcoming 2.4.1 release.

**Comment by slavvka** [comment]
Hi @ScreamingDev. Thank you for your report. 
The issue has been fixed in magento/magento2#27956 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [dbaf8a55e740741043231ad7e06ea6950064126c](https://github.com/magento/magento2/commit/dbaf8a55e740741043231ad7e06ea6950064126c)
 - [9479c3ac03a5d2a152f788dd75fd7955eb646b12](https://github.com/magento/magento2/commit/9479c3ac03a5d2a152f788dd75fd7955eb646b12)
 - [9d4223894e8b32fa3b6f7e44e4349f247b358fab](https://github.com/magento/magento2/commit/9d4223894e8b32fa3b6f7e44e4349f247b358fab)
 - [003162a43254c9f7b5d7ef335384d8e6d444dedc](https://github.com/magento/magento2/commit/003162a43254c9f7b5d7ef335384d8e6d444dedc)
 - [689bbeaefa1d8d69448a020d893a12a14ce9bcc4](https://github.com/magento/magento2/commit/689bbeaefa1d8d69448a020d893a12a14ce9bcc4)
 - [74a95e1adb476c49e9c1f4b4a0bab27e9b02df16](https://github.com/magento/magento2/commit/74a95e1adb476c49e9c1f4b4a0bab27e9b02df16)
 - [e4d9a056c6ce665642c6475eb2833a6781a86442](https://github.com/magento/magento2/commit/e4d9a056c6ce665642c6475eb2833a6781a86442)
 - [b059e515fcce915799fdc47d4d74d4b0d1e45690](https://github.com/magento/magento2/commit/b059e515fcce915799fdc47d4d74d4b0d1e45690)

The fix will be available with the upcoming 2.4.1 release.

**Comment by magento-engcom-team** [comment]
Hi @ScreamingDev. Thank you for your report. 
The issue has been fixed in magento/magento2#28072 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [034af404deaa448c6ae660166912b0c40dfc7b12](https://github.com/magento/magento2/commit/034af404deaa448c6ae660166912b0c40dfc7b12)
 - [7e6e0239c9895982b4bb1577412b0018beef1361](https://github.com/magento/magento2/commit/7e6e0239c9895982b4bb1577412b0018beef1361)
 - [81737c084b0b80b48cf5b3359e3b145c64aa54f1](https://github.com/magento/magento2/commit/81737c084b0b80b48cf5b3359e3b145c64aa54f1)
 - [120a105b5adb6fbc4d35a0067d72aa1975acccc5](https://github.com/magento/magento2/commit/120a105b5adb6fbc4d35a0067d72aa1975acccc5)
 - [035c1577d0e5dee7c102375cd2bdba0f1542c85f](https://github.com/magento/magento2/commit/035c1577d0e5dee7c102375cd2bdba0f1542c85f)
 - [8ed5018fda262de3fb337fc886daaede98122f96](https://github.com/magento/magento2/commit/8ed5018fda262de3fb337fc886daaede98122f96)
 - [cea930b4d7549bcf476e621ad11ffbfa4847e0e6](https://github.com/magento/magento2/commit/cea930b4d7549bcf476e621ad11ffbfa4847e0e6)
 - [dabbd3c07dbc5ee4c09b785f3f315b4fd3c29fa1](https://github.com/magento/magento2/commit/dabbd3c07dbc5ee4c09b785f3f315b4fd3c29fa1)
 - [f6ce31d43aa8316ff59821c508d7b54c734bcee9](https://github.com/magento/magento2/commit/f6ce31d43aa8316ff59821c508d7b54c734bcee9)
 - [a2f28d83e8ceab42e60505af371d3e5905ee1d65](https://github.com/magento/magento2/commit/a2f28d83e8ceab42e60505af371d3e5905ee1d65)
 - [233b695c4f55b1a4c14009ecc13ced4658d5b868](https://github.com/magento/magento2/commit/233b695c4f55b1a4c14009ecc13ced4658d5b868)
 - [d127c98a404e3d5e393e14157cd71b41b0df8ae7](https://github.com/magento/magento2/commit/d127c98a404e3d5e393e14157cd71b41b0df8ae7)
 - [d9748d2d6eecb98b6eca36b5aa9b7602b6bf237f](https://github.com/magento/magento2/commit/d9748d2d6eecb98b6eca36b5aa9b7602b6bf237f)
 - [d994276cbab26239732d64b8c313a38eac13f01c](https://github.com/magento/magento2/commit/d994276cbab26239732d64b8c313a38eac13f01c)
 - [938e43bfae3774afde30523951aa9edd27778ec3](https://github.com/magento/magento2/commit/938e43bfae3774afde30523951aa9edd27778ec3)
 - [d339ae8ec16a96edcaf6927376a3a0c179826a76](https://github.com/magento/magento2/commit/d339ae8ec16a96edcaf6927376a3a0c179826a76)

The fix will be available with the upcoming 2.4.1 release.
