### ISSUE TITLE
View details toggle arrow not in single line for config product checkout page > minicart

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#25366]
View details toggle arrow not in single line for config product checkout page > mini cart (Cart summary link)

### Preconditions (*)
1. Magento2.3.x
2. php 7.2

### Steps to reproduce (*)
1. Open Frontend
2. Add to cart any configurable product 
3. Go to mini cart and click in Proceed to Checkout button 
4. Now resize the page the window to 320 and click cart summary link 
and now refer screenshot 

### Expected result (*)
![sol](https://user-images.githubusercontent.com/26018716/67851167-d8bfe480-fb2f-11e9-9279-0f1ffbd09f23.png)

### Actual result (*)
![issue_1](https://user-images.githubusercontent.com/26018716/67851205-effed200-fb2f-11e9-8a20-d05da97a08e1.png)

**Comment by shikhamis11** [comment]
@magento give me 2.3-develop

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22568` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your report. 
The issue has been fixed in magento/magento2#25368 by @cedarvinda in 2.3-develop branch
Related commit(s):
 - [d9e525a5e33a771df6c4c835e518fa024f6b47d2](https://github.com/magento/magento2/commit/d9e525a5e33a771df6c4c835e518fa024f6b47d2)
 - [fddc005bbb2480caeb3f816fd9e04865e36d4dee](https://github.com/magento/magento2/commit/fddc005bbb2480caeb3f816fd9e04865e36d4dee)
 - [6f5387c8360d5c52842d7905caa29af99257f3e3](https://github.com/magento/magento2/commit/6f5387c8360d5c52842d7905caa29af99257f3e3)

The fix will be available with the upcoming 2.3.4 release.
