### ISSUE TITLE
Performance issue: Magento 2 generates unnecessary wrappers for all the pluggable methods even there are no plugins for a particular method

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2536]
https://mage2.pro/t/210

**Comment by adragus-inviqa** [comment]
I guess it's easier to create the full interceptor class the first time, than to add methods on a per-plugin basis.

Do you know this to be a performance problem?

**Comment by antonkril** [comment]
Wrapper methods are only generated in developer mode, and if you run multi-tenant compiler.

If you run recommended for production and for almost all merchants single-tenant compiler, wrapper methods are only generated for intercepted methods.

**Comment by dmitrii-fediuk** [comment]
Why does the multi-tenant compiler do it in the production mode?

**Comment by antonkril** [comment]
Because multi-tenant is built for deployment scenarios where one magento installation may serve requests for different merchants (tenants) with different sets of modules installed. It means that for every request, final merged configurations may look different with different plugins applied to different methods. So we can not use optimizations that we use for single-tenant deployments and have to expect that every method may be pluginized. 

Launch of multi-tenant compiler is more complicated and should be run on magento with all possible modules installed, so that all plugins from all possible modules can be taken into account. This scenario is not fully tested/supported for now.

**Comment by adragus-inviqa** [comment]
@antonkril - sorry to hijack this thread, but would you like to expand on that multi single tenant vendor M2 app a bit?
The [docs](http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-compiler.html#config-cli-subcommands-run) say

```
Use this command if you have multiple tenants, which means more than one independent Magento application. In other words:

    There is one Magento 2 code base instance
    There is one database instance per tenant
    Independent configurations in the Magneto Admin per tenant
    The storefronts are independent of each other
```
- What exactly do you mean by `one magento installation may serve requests for different merchants (tenants) with different sets of modules installed`?
- What are tenants/vendors in this case?
- How can you have different module sets?
- Does a single M2 app with multiple websites/stores contitutes a multi or single tenant?
- Can you provide a hypothetical example of a multi-tenant M2 setup?

**Comment by adragus-inviqa** [comment]
👍

**Comment by antonkril** [comment]
Multi-tenant setup is a SAAS solution based on magento (Magento GO), where one magento installation can serve requests for multiple not connected merchants. Magento stores/websites are not example of multi-tenancy.
