### ISSUE TITLE
Product Additional Options Tooltip not fully visible

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#25392]
### Preconditions (*)

1. Magento 2.3.3
2. Product with additionalOptions populated

### Steps to reproduce (*)

1. Create a product that includes an additionalOption value that is over 55 characters
2. Place order for product
3. View shipment for order in customer dashboard

### Expected result (*)

1. <img width="705" alt="Screenshot 2019-10-31 at 08 39 21" src="https://user-images.githubusercontent.com/1945725/67928073-7233d880-fbba-11e9-98b4-6a8b60034cb5.png">

### Actual result (*)

1. <img width="704" alt="Screenshot 2019-10-31 at 08 40 33" src="https://user-images.githubusercontent.com/1945725/67928093-79f37d00-fbba-11e9-8b66-8cd7fcf9e18a.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22612` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your report. 
The issue has been fixed in magento/magento2#25393 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [3b795b92ec816489cdb0d11a948ecbdfc1292738](https://github.com/magento/magento2/commit/3b795b92ec816489cdb0d11a948ecbdfc1292738)

The fix will be available with the upcoming 2.3.4 release.
