### ISSUE TITLE
Checkbox Customizable Options saved to database incorrectly when editing orders

### ISSUE THREAD

**Issue by CronoxAU** [magento/magento2#25395]
I apoligise if I get this wrong, I have not submitted an issue here before.

### Preconditions (*)

1. We have verified this behavior in Magento 2.3.3 and 2.3.2 
2. A product with at least one Customizable Option of the checkbox type. it does not matter if it is set to required or not.

### Steps to reproduce (*)

1. Create a new order via the admin interface with the product in question and at least one value selected in the checkbox Customizable Option
![image](https://user-images.githubusercontent.com/23115040/67932727-66b6d080-fbff-11e9-9a43-a0cb65713d4d.png)

Once the order is created the custom_options field in the sales_order_item table in the database will look like:
`{"info_buyRequest":{"qty":1,"options":{"1":["2","3"]}},"options":[{"label":"option 1","value":"cb 2, cb 3","print_value":"cb 2, cb 3","option_id":"1","option_type":"checkbox","option_value":"2,3","custom_view":false}]}`

2. Edit the order in the admin interface and submit the edited order. 
No changes are needed to the order during the edit, although if changes are made the issue still occurs.

Once the edit is submitted the new entry for the item in the sales_order_item table has the following in the custom_options field:
`{"info_buyRequest":{"qty":"1.0000","options":{"1":"2,3"}},"options":[{"label":"option 1","value":"cb 2, cb 3","print_value":"cb 2, cb 3","option_id":"1","option_type":"checkbox","option_value":"2,3","custom_view":false}]}`

Specifically the options field has been saved with a string "2,3" rather than as an array of separate values ["2","3"]

3. Attempt to edit the order again

### Expected result (*)

1. The admin should be taken to the edit order screen and edit the order again as needed.

### Actual result (*)

1. The user is presented with the error "The product's required option(s) weren't entered. Make sure the options are entered and try again."
![image](https://user-images.githubusercontent.com/23115040/67933593-12aceb80-fc01-11e9-8224-bff17747216b.png)

2. Manually editing the database table to convert the options value back into the array format resolves the error on required fields and allows the order to be edited again, but the issue will re-occur when that edit is saved, with the order being un-editable again.

3. Once the sales_order_item data is saved in the wrong format during the edit process the reorder function also stops working. As far as we have seen other functionality on the order continues working correctly.

**Comment by CronoxAU** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @CronoxAU. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @CronoxAU, here is your [Magento instance](https://i-25395-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25395-2-3-develop.instances.magento-community.engineering/admin](https://i-25395-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by CronoxAU** [comment]
On the 2.3-develop build the issue is slightly different but I believe the underlying problem is still occurring.

There is no longer any error when attempting the edit an order but the checkbox options don't load into the configure product section meaning the user can't see what options are selected on this item:
![image](https://user-images.githubusercontent.com/23115040/67995635-73323c00-fc86-11e9-84f2-588134edb672.png)

If the options are not edited they will be maintained but if any check boxes are ticked during the edit all existing selections will be lost.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22681` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
Hello @CronoxAU 

Thank you for your report

We confirm that we could reproduce the issue on Magento 2.3.3 composer version. 
We get the _The user is presented with the error "The product's required option(s) weren't entered. Make sure the options are entered and try again."_ error

This issue is already fixed in 2.4-develop. No error messages appear on **Edit** and the order is placed successfully with the selected options. (After Edit and **not** changing anything)  

Steps to reproduce

1. Create a new order via the admin interface with the product in question and at least one value selected in the checkbox Customizable Option
2. Edit the order in the admin interface and submit the edited order
3. Attempt to edit the order again

Actual Result: Edit order screen appears without any errors
![Edit order](https://user-images.githubusercontent.com/51680745/96442818-651d5880-1214-11eb-9014-7f0779dcd02e.png)

We are closing this issue. Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
