### ISSUE TITLE
Magento_Analytics wrong link

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#25411]
### Preconditions (*)
1. I'm using Magento 2.3.3

### Steps to reproduce (*)
1. Access the admin panel
2. Click in this link circled in the image below.

![Magento2 admin panel report link](https://user-images.githubusercontent.com/610598/67963840-082d2a80-fbde-11e9-8baa-f96efa53ba1e.png)

### Expected result (*)

1. In my opinion, it should go to the [login page](https://dashboard.rjmetrics.com/v2/session/create)
2. Or to the [Advanced Reporting page](https://docs.magento.com/m2/ce/user_guide/reports/advanced-reporting.html).

![Screen Shot 2019-10-31 at 12 53 40 PM](https://user-images.githubusercontent.com/610598/67964185-9acdc980-fbde-11e9-9215-02ad03a78a45.png)
![Screen Shot 2019-10-31 at 12 53 44 PM](https://user-images.githubusercontent.com/610598/67964194-9c978d00-fbde-11e9-8e32-ffd540c0ba30.png)

### Actual result (*)

1. The button is redirecting to this page below.

![Screen Shot 2019-10-31 at 12 53 36 PM](https://user-images.githubusercontent.com/610598/67965637-33654900-fbe1-11e9-862b-0c27d62e937a.png)

### Additional Information
https://github.com/magento/magento2/issues/25411#issuecomment-548493946

> I created this PR to check if the Magento BI token is configured, if it's configured and not synchronized, it will redirect to the same page, if it's not configured it will redirect to the doc page.

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25411-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25411-2-3-develop.instances.magento-community.engineering/admin](https://i-25411-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @rafaelstz  and @itsPranith 

It looks like very similar to this https://github.com/magento/magento2/issues/24180
Previously issue was closed as cannot reproduce because after enabling Adv. Reporting needs some time for initial synchronization. It mentioned in DevDoc, the last point of [Step 1: Enable Advanced Reporting](https://docs.magento.com/m2/ce/user_guide/reports/advanced-reporting.html#step-1-enable-advanced-reporting)

For more details please see this https://github.com/magento/magento2/issues/24180#issuecomment-525391650


Could you please confirm that you have the same issue and after synchronization, it works as expected?

**Comment by rafaelstz** [comment]
Hi @sdzhepa,

It's not the same issue because today it's not considering if the Magento BI token is configured, even if it's not synchronized yet.
I created this [PR](https://github.com/magento/magento2/pull/25412) to check if the Magento BI token is configured, if it's configured and not synchronized, it will redirect to the same page, if it's not configured it will redirect to the doc page.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22634` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rafaelstz. Thank you for your report. 
The issue has been fixed in magento/magento2#25412 by @rafaelstz in 2.4-develop branch
Related commit(s):
 - [9efef990accdc4b2fc094fe3bb68fde3cc178604](https://github.com/magento/magento2/commit/9efef990accdc4b2fc094fe3bb68fde3cc178604)
 - [c01dd2a41a4862366148f9a486e402ebed6b0b27](https://github.com/magento/magento2/commit/c01dd2a41a4862366148f9a486e402ebed6b0b27)
 - [6a0f133b6ba40a87321324151910bf44ba8e6811](https://github.com/magento/magento2/commit/6a0f133b6ba40a87321324151910bf44ba8e6811)
 - [d69bd9d9a916f9c3a13793fd1a01bbe77257c7e4](https://github.com/magento/magento2/commit/d69bd9d9a916f9c3a13793fd1a01bbe77257c7e4)
 - [42eb8a04a783bdebf692805836beb8db87667bfa](https://github.com/magento/magento2/commit/42eb8a04a783bdebf692805836beb8db87667bfa)
 - [1e8b12e4a3e1fe881a56108c97131b17a5c0d6be](https://github.com/magento/magento2/commit/1e8b12e4a3e1fe881a56108c97131b17a5c0d6be)
 - [08c9f33f0c56df5fb12634a2a452f94aeeee0187](https://github.com/magento/magento2/commit/08c9f33f0c56df5fb12634a2a452f94aeeee0187)

The fix will be available with the upcoming 2.4.2 release.
