### ISSUE TITLE
Inconsistency with full stops in admin configurations  

### ISSUE THREAD

**Issue by Ashna-Jahan** [magento/magento2#25455]
### Steps to reproduce (*)

1.  Go to Admin > Stores > Configuration > Catalog > Catalog  > Store Front. 
2.  You can observe that the comments under the fields are not consistent with respect to full stops after the Sentence. 

### Expected result (*)

1. Full stops should be present after each sentence. 
### Actual result (*)

1.  No consistency with full stops after the comments in admin configurations.
![2019-11-01_1653](https://user-images.githubusercontent.com/32352950/68022310-f88b1000-fcc9-11e9-84bd-be32485e1328.png)

**Comment by kanthy-magento** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itsPranith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itsPranith, here is your [Magento instance](https://i-25455-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25455-2-3-develop.instances.magento-community.engineering/admin](https://i-25455-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kanthy-magento** [comment]
This issue is replicating on Magento instance- @ https://i-25455-2-3-develop.instances.magento-community.engineering/admin/admin/system_config/edit/section/catalog/

Please find the screen images for your reference.
![Catalog-Store](https://user-images.githubusercontent.com/56586384/68106131-a420a400-ff06-11e9-8fa4-ca44fc776b5a.PNG)
![catalog-store-1](https://user-images.githubusercontent.com/56586384/68106135-a7b42b00-ff06-11e9-8129-33a7f3c14ce0.PNG)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @itsPranith 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22733` were created

**Issue Available**: @itsPranith, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by theCapypara** [comment]
Sorry! Dind't see, that this is already fixed in PR #25456. The issue can propably be closed @magento-engcom-team .

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Ashna-Jahan,

Thanks for your reporting and collaboration.

We have verified the issue and the issue is no more reproducible in Latest 2.4-develop instance.

<img width="932" alt="Screenshot 2024-04-25 at 11 19 15" src="https://github.com/magento/magento2/assets/51680745/d0a0411d-89fb-4fd9-8ae8-1bfec7f887ef">


Hence we are Closing this issue.

Thanks.
