### ISSUE TITLE
Theme configuration issues

### ISSUE THREAD

**Issue by MBK8303** [magento/magento2#25450]
When I upgrade setup by cmd 
learn from :
https://www.solwininfotech.com/documents/magento2/freego/

![Screenshot (80)](https://user-images.githubusercontent.com/36476456/68084060-ffd92780-fe49-11e9-85f7-068b9b14488c.png)

**Comment by engcom-Delta** [comment]
Hi @MBK8303 thank you for your report. Your issue is connected with environment configuration.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
