### ISSUE TITLE
[2.3-develop] Uploading category image puts it in a tmp directory

### ISSUE THREAD

**Issue by hostep** [magento/magento2#25480]
### Preconditions (*)
1. PHP 7.2.24
2. Magento 2.3-develop branch (I've used commit b3bd86ba8fabe0550d380279e2cb0a83e31cf75c)

### Steps to reproduce (*)
1. Setup Magento from 2.3-develop branch
2. Create a category in the backend
3. In the Content tab of the category, upload a Category Image with the 'Upload' button (let's assume the file is called `filename.jpg`)
4. Save the category

### Expected result (*)
These are based on the results of Magento 2.3.2:
1. File is uploaded to the directory `pub/media/catalog/category`
2. Value of the attribute `image` in the database in the `catalog_category_entity_varchar` table is just `filename.jpg`

### Actual result (*)
1. File gets uploaded to the directory `pub/media/catalog/tmp/category/`
2. Value of the attribute `image` in the database in the `catalog_category_entity_varchar` table is `/pub/media/catalog/tmp/category/filename.jpg`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22862` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by PieterCappelle** [comment]
Hi @hostep, any update/pull request about this issue? We have the same problems with one of our clients :-)

**Comment by hostep** [comment]
@PieterCappelle: are you using an unstable Magento version? This bug only occurs on 2.3-develop, not in version 2.3.3.
Magento 2.3.3 has [another problem with category images](https://github.com/magento/magento2/issues/25099) however, which was fixed in 2.3-develop, and might have caused this problem here, but I'm not sure...

**Comment by PieterCappelle** [comment]
@hostep We are using 2.3.3. Thanks for pointing out the other issue, we have the same issue.
https://github.com/magento/magento2/issues/25099
https://github.com/FutureActivities/Magento-Fix-Category-Images

Thanks!

**Comment by hostep** [comment]
Accidentally saw the following commit flying by on the `2.4-develop` branch, which might fix this problem: https://github.com/magento/magento2/commit/1c3ee947270eb0465aef2710f3c216795747bbaf (not verified myself yet).

**Comment by asim-vax** [comment]
We are using 2.3.3 EE, and have the same issue. We took https://github.com/magento/magento2/commit/1c3ee947270eb0465aef2710f3c216795747bbaf and turned it into a patch, this has fixed our problem of not moving from tmp directory

**Comment by ihor-sviziev** [comment]
**Tested on 2.3.4:**
❌Category Image contains "tmp" in the URL
https://i-27168-2-3-4.instances.magento-community.engineering/category-1.html
![image](https://user-images.githubusercontent.com/1873745/83876144-0661b180-a741-11ea-8dfc-4d987ddfe10c.png)

Image URL is following:
https://i-27168-2-3-4.instances.magento-community.engineering/pub/media/catalog/tmp/category/Tests.png

**Tested on 2.4-develop:**
✔Category Image do not contains "tmp" in the URL
https://i-27168-2-4-develop.instances.magento-community.engineering/category-1.html
![image](https://user-images.githubusercontent.com/1873745/83876618-d23ac080-a741-11ea-8ac5-7abe1233ba9b.png)

Image URL is following:
https://i-27168-2-4-develop.instances.magento-community.engineering/pub/media/catalog/category/Tests.png


This issue was fixed in 2.4-develop branch and not reproducing anymore.
I'm closing this issue.
