### ISSUE TITLE
Most Viewed Products's count is incorrect in admin Dashboard report tab when FPC is enabled

### ISSUE THREAD

**Issue by harrywutech** [magento/magento2#25499]
### Preconditions (*)

1.  Magento EE 2.3.3  with sample data is installed (new installation)
2.  Nginx 1.17 and PHP7.3

### Steps to reproduce (*)

1.  Enable Full Page Cache in Admin
2.  Go to any product detail page, for example http://m233.test/push-it-messenger-bag.html
3.  Refresh the product detail page 10 times

### Expected result (*)

1. The push it messenger bag's Views number should be 10

### Actual result (*)

1.  The push it messenger bag's views number is 1
https://i.imgur.com/jfsnXWk.png

**Comment by kanthy-magento** [comment]
@hanxiangwu - T His is an EE issue. Please contact Enterprise team to get this issue fixed.
This forum is used for CE or Community issues
Closing this ticket.

**Comment by GuillaumeBrook** [comment]
Hello

Tested in Magento CE 2.3.3
This is indeed not working.

When visiting a product which is not in FPC, a row is added in the table "report_event".
When visiting a product which is in FPC, no row is added in the table "report_event".

Expected behavior : a row should be added in "report_event" every time a product page is visited even if this product is in FPC.
