### ISSUE TITLE
Cant set HtmlTag to "nav"

### ISSUE THREAD

**Issue by refaelgold** [magento/magento2#2549]
Hey, 
i try to make a menu like in HTML5 and use the nav element

```
        <container name="header.container" as="header_container" label="Page Header Container"  htmlTag="nav" htmlClass="navbar navbar-default" before="main.content"/>
```

i get an error

```
a:4:{i:0;s:167:"Html tag "nav" is forbidden for usage in containers. Consider to use one of the allowed: dd, div, dl, fieldset, main, header, footer, ol, p, section, table, tfoot, ul."
```

you have an idea why nav is forbidden? it will be fixed soon?

**Comment by victorgugo** [comment]
@refaelgold , thank you for reporting the issue. We created internal one MAGETWO-46295 to fix the problem. 
As a temporary workaround you can use block Magento\Framework\View\Element\Template with custom template instead of container, for example:
`<block class="Magento\Framework\View\Element\Template" template="Magento_ModuleName::path/to/template.phtml"/>`

**Comment by shiftedreality** [comment]
Fix was merged to develop branch. Closed.
