### ISSUE TITLE
Category Page Configurable Product Filter Issue

### ISSUE THREAD

**Issue by iflairBhavin** [magento/magento2#25516]
### Preconditions (*) 

1. Magento 2.3.3

### Steps to reproduce (*)
1. Create configurable product with Color and Size attributes (ie. Red, Green, Blue options of Color and S, M, L options of Size) and assign to one of the test category.
2. Make one simple product out of stock for ex. Green color with M size simple product's qty set to Zero and mark as out of stock.
3. In the Magento 2 Admin > Stores >Configuration> Catalog > Inventory > Stock Options > Display Out of Stock Products is Set to No.
4. Do indexing and cache flush/clean

### Expected result (*)
1. If user search using Green color and M size that is out of stock then that configurable product not visible in search result.

### Actual result (*)
1. If user search using Green color and M size that is out of stock then that configurable product is still visible in search result even if that variation is not available for purchase in product detail page.

![Test Product](https://user-images.githubusercontent.com/16224364/68399648-bc115580-019c-11ea-8ca2-c4dcba9f5556.png)

![Test](https://user-images.githubusercontent.com/16224364/68399660-c2073680-019c-11ea-80f5-e0a576bb67d7.png)

![Configuration   Settings   Stores   Magento Admin](https://user-images.githubusercontent.com/16224364/68399671-c6335400-019c-11ea-851e-986e76f66224.png)

**Comment by iflairBhavin** [comment]
@magento give me 2.3-develop instance ( 2.3.3 version)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22986` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VadimLugovoy** [comment]
@magento I am working on it

**Comment by VadimLugovoy** [comment]
#cdkharkiv19nov

**Comment by engcom-Hotel** [comment]
Hello @iflairBhavin,
Checking the issue:
Magento version: 2.4-develop
PHP version: 7.4
ElasticSearch version: 7
MySQL version: 8.0
1. Configurable product with 2 attributes;
2. Stores >Configuration> Catalog > Inventory > Stock Options > Display Out of Stock Products is Set to No;
3. Set QTY equal 0 and out of stock for one of the created products;

Checking PDP and PLP and they have similar behaviour - out of stock options are crossed and you are not able to buy it.
![25516_not_able_to_rep](https://user-images.githubusercontent.com/51681618/106002373-b9f52880-60b9-11eb-988f-36a670d13853.gif)
On the one hand, when we selecting out of stock options on PLP with such configuration it should not show hole configurable product. But on the other hand, it should be implemented in the same way as it implemented on PDP (crossing out of stock options). That is why I am not sure that it is a bug.
@sdzhepa What do you think is it a bug and if yes how it should be implemented on PDP and PLP?

**Comment by iflairBhavin** [comment]
@engcom-Hotel ,
As per my thinking if searched product was out of stock then that product means it's parent configurable product no more available in the search result on PLP page because user need that specific product (ie. blue color and a size) and we show him product which was out of stock already. Please share your thoughts. Thanks!

**Comment by redingopl** [comment]
According to us, the problem is still not solved (M2.4.3-p3). Has anyone been able to fix it or get around it?

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @iflairBhavin @redingopl,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce** 


- Create configurable product with Color and Size attributes (ie. Red, Green, Blue options of Color and S, M, L options of Size) and assign to one of the test category.
- Make one simple product out of stock for ex. Green color with M size simple product's qty set to Zero and mark as out of stock.
- In the Magento 2 Admin > Stores >Configuration> Catalog > Inventory > Stock Options > Display Out of Stock Products is Set to No.
- Do indexing and cache flush/clean



<img width="1189" alt="Screenshot 2023-07-31 at 12 20 47 PM" src="https://github.com/magento/magento2/assets/51680745/12194360-0dc0-4c23-994e-572f868b6be5">



<img width="1417" alt="Screenshot 2023-07-31 at 12 16 38 PM" src="https://github.com/magento/magento2/assets/51680745/06e18df1-bf15-4663-ae11-b38e8873846e">



<img width="1293" alt="Screenshot 2023-07-31 at 12 17 45 PM" src="https://github.com/magento/magento2/assets/51680745/85cd96a6-fb0b-4680-b112-0e29c5520a9c">



When user is searching with color **Green** and size **M** it is showing M size is crossed out for only green color because only for green color it is in out of stock for other colors and sizes it is in still in stock hence while filtering it will show all variations if any particular product is in out os stock that size or color will be in crossed out state.


When we move all products related to Green color it will not show while filtering.


<img width="854" alt="Screenshot 2023-07-31 at 12 28 32 PM" src="https://github.com/magento/magento2/assets/51680745/96684a48-b729-4ca5-94fd-2d68b65df444">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible and please let us know if we are missing anything.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @iflairBhavin,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
