### ISSUE TITLE
Wrong program code in "Magento/Checkout/view/frontend/web/js/view/summary/shipping.js"

### ISSUE THREAD

**Issue by andrewbess** [magento/magento2#25529]
### Preconditions (*)

1. Seems there is wrong code in Magento_Checkout/js/view/summary/shipping

`return shippingMethod ?`
`            shippingMethod['carrier_title'] + shippingMethodTitle :`
`            shippingMethod['carrier_title'];`

What can happen if shippingMethod will not be an array?

### Steps to reproduce (*)

1. Set shipping method as type "string" in the quote like a quote.shippingMethod('test')
2. Check the sidebar on step 2

### Expected result (*)

1. Shipping shouldn't look javascript type "undefined"

### Actual result (*)

1. [Incorrect delivery display](https://monosnap.com/file/Z6ylOQWZVdWEkkkEm01qhZXbhHkyhq)

**Comment by magento-engcom-team** [comment]
Hi @andrewbess. Thank you for your report. 
The issue has been fixed in magento/magento2#25530 by @andrewbess in 2.3-develop branch
Related commit(s):
 - [0ffbe25590f893cea39c31a7521c2ca9c68fd324](https://github.com/magento/magento2/commit/0ffbe25590f893cea39c31a7521c2ca9c68fd324)
 - [d6c184d5239502a65c1350d26c505bdd3642b9e1](https://github.com/magento/magento2/commit/d6c184d5239502a65c1350d26c505bdd3642b9e1)

The fix will be available with the upcoming 2.3.5 release.
