### ISSUE TITLE
Magento 2.3.2 OS Elasticsearch 6.8 returning suggestions from MySQL search_query

### ISSUE THREAD

**Issue by rf-magma** [magento/magento2#25534]
### Preconditions (*)
1. installing and configuring Elasticsearch 6.8.2 in a Magento 2.3.2(or 2.3-develop) Open Source installation as per devdocs (reindexing and cache:clean ok) 
2. checking (with Kibana) that the query (GET _search) is sent to Elastic (activating slow log threshold to 0 and checking the queries get passed to Elastic)
3. entering word/s in Magento2 search bar and hitting enter generates logs in Elasticsearch and return expected results (same as firing the query "GET _search" in Kibana).

### Steps to reproduce (*)
1. In magento 2.3 search bar entering a word (**without** hitting enter) and waiting for autocomplete to return results (search suggestions) in a dropdown list

### Expected result (*)
1. Query sent to Elasticsearch in order to retrieve "search suggestions"
2. Query logged in Elasticsearch logs
3. Search suggestions retrieved from Elastic

### Actual result (*)
1. Magento 2.3 queries instead MySQL search_query table and returns those search suggestions (words not present in whole elasticsearch indexes)
2. Queries not logged in elastic logs proving query is made to mysql search_query table 

### Notes
mysql search_query table contains many words not present in whole Magento because registers search made by previous visitors 

thanks,
romeo

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-28940` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by usuyukiso** [comment]
For me was also reproduced with Magento 2.3.2 OS, 2.3.3 Commerce.

**Comment by espressobytes** [comment]
Anything new to this issue?

**Comment by cosmedd** [comment]
_The performance of catalog search has improved. Disabling Enable Search Suggestions (Stores > Configuration > Catalog > Catalog Search) works as expected. Previously, Magento queried the MySQL search_query table instead of Elasticsearch for autocomplete search suggestions. GitHub-25534_

From https://devdocs.magento.com/guides/v2.3/release-notes/open-source-2-3-6.html#search

I don't understand if we have to disable _"Enable search suggestions"_ to use Elasticsearch or the problem was that even disabling that option Magento was still using MySQL before 2.3.6?
