### ISSUE TITLE
Add all type of product into cart, start checkout with multiple address after giving multiple address, except download and virtual type product, remove all four type product from the cart then getting exception 

### ISSUE THREAD

**Issue by Khushbu-Webkul-QA** [magento/magento2#25595]
### Preconditions (*)

1.Test environment:

* Magento version:2.3.3 or latest `2.4-develop`
* PHP Version:7.2
* mode: production
* Varnish:enable
* Js, CSS, HTML merged and minified
* Flat catalog/category – Yes
* Instance-  http://192.168.15.166/m2307/admin/
* username/password-admin/admin123

### Steps to reproduce (*)

1. add all six type of product into cart
2. proceed for checkout with multiple address
3. after give multiple address, remove four type product except download and virtual
4. getting exception

### Expected result (*)

1. it should not give exception

### Actual result (*)

1. ![Screenshot (7)](https://user-images.githubusercontent.com/45037885/68832268-84dc0080-06d6-11ea-81d8-b85dd4355f2d.png)

**Comment by Khushbu-Webkul-QA** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Khushbu-Webkul-QA. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Khushbu-Webkul-QA, here is your [Magento instance](https://i-25595-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25595-2-3-develop.instances.magento-community.engineering/admin](https://i-25595-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Khushbu-Webkul-QA** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/45037885/68843611-6b46b300-06ee-11ea-90cf-75e0ac728fc2.png)

@magento issue replicate

**Comment by engcom-Charlie** [comment]
I can confirm this behavior on the Magento 2.4-develop:
![image](https://user-images.githubusercontent.com/51680850/70315953-50fe8180-1823-11ea-8426-7226c47591fe.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29496` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Still actual on latest `2.4-develop`

![issue_25595](https://user-images.githubusercontent.com/3409584/85798919-f74c9e80-b703-11ea-9d82-c7cf66346476.gif)

**Comment by ralbin** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @Khushbu-Webkul-QA. Thank you for your report. 
The issue has been fixed in magento/magento2#29269 by @ralbin in 2.4-develop branch
Related commit(s):
 - [67a4be3c2d31abb4b0198069e89589780c11fae6](https://github.com/magento/magento2/commit/67a4be3c2d31abb4b0198069e89589780c11fae6)
 - [3a1df1d28f8087ca12f3248c1fa359fc8a43272a](https://github.com/magento/magento2/commit/3a1df1d28f8087ca12f3248c1fa359fc8a43272a)
 - [603ef0565df194abab63b1c23b11d2ee0d11aa8d](https://github.com/magento/magento2/commit/603ef0565df194abab63b1c23b11d2ee0d11aa8d)
 - [78f0780e7d4eec7863fc6a94ab8ce1e16e42f8c3](https://github.com/magento/magento2/commit/78f0780e7d4eec7863fc6a94ab8ce1e16e42f8c3)
 - [b566b8000621ccfdf96c894d2f73968daed8926e](https://github.com/magento/magento2/commit/b566b8000621ccfdf96c894d2f73968daed8926e)
 - [e40b1ca58f17e2cd0f54995ad6b722165af3c78c](https://github.com/magento/magento2/commit/e40b1ca58f17e2cd0f54995ad6b722165af3c78c)
 - [090f06a0a832adb64c298f297e0bc2741cd92b9d](https://github.com/magento/magento2/commit/090f06a0a832adb64c298f297e0bc2741cd92b9d)
 - [54c8ebc95dd9391db5a983ff7d63dbb3f8489b35](https://github.com/magento/magento2/commit/54c8ebc95dd9391db5a983ff7d63dbb3f8489b35)

The fix will be available with the upcoming 2.4.2 release.
