### ISSUE TITLE
& character in SKUs is shown as &amp; in current variations list on configurable products 

### ISSUE THREAD

**Issue by m1k3lm** [magento/magento2#25591]
### Preconditions (*)

1. Magento 2.3.3 PHP 7.1.33
2. Vanilla install

### Steps to reproduce (*)

1. Create a simple product with a _&_ character in SKU.
2. Create configurable product and add previously created simple product as variation.
3. In configurable product's current variations table the _&_ in the SKU field is shown as &amp;amp;

### Expected result (*)

1. See unchange & character in SKU

### Actual result (*)

![Captura de pantalla 2019-11-14 a las 0 36 15](https://user-images.githubusercontent.com/1660934/68814125-49aae480-0678-11ea-8246-3a33f2658f37.png)

**Comment by m1k3lm** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @m1k3lm. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @m1k3lm, here is your [Magento instance](https://i-25591-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25591-2-3-develop.instances.magento-community.engineering/admin](https://i-25591-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by m1k3lm** [comment]
Yes, it can be reproduced.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23126` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @m1k3lm. Thank you for your report. 
The issue has been fixed in magento/magento2#26007 by @KaushikChavda in 2.4-develop branch
Related commit(s):
 - [b3e6049c96a607087ec1c9de14e0cc79b280ac71](https://github.com/magento/magento2/commit/b3e6049c96a607087ec1c9de14e0cc79b280ac71)
 - [29d6a0f1e77fd6861872aa70f5d016c7cac8f72d](https://github.com/magento/magento2/commit/29d6a0f1e77fd6861872aa70f5d016c7cac8f72d)
 - [6540136deb2b65aa478e3a1b215c4e2ca33bdcf7](https://github.com/magento/magento2/commit/6540136deb2b65aa478e3a1b215c4e2ca33bdcf7)
 - [198d216d2190b804dcec5dde1d22c29dc824efb4](https://github.com/magento/magento2/commit/198d216d2190b804dcec5dde1d22c29dc824efb4)
 - [9692771b33136240d5ddca2f772d8edb16510be5](https://github.com/magento/magento2/commit/9692771b33136240d5ddca2f772d8edb16510be5)
 - [d2c8006d935011a3d41cf86937967faca3f7e41f](https://github.com/magento/magento2/commit/d2c8006d935011a3d41cf86937967faca3f7e41f)
 - [861f4922e0a45d0ab4cf52895043a92019bc09b4](https://github.com/magento/magento2/commit/861f4922e0a45d0ab4cf52895043a92019bc09b4)

The fix will be available with the upcoming 2.4.0 release.
