### ISSUE TITLE
No margin between checkbox and icon when choose category in condition in Cart/Catalog Rule

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25596]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend.
2. Marketing-> Catalog Price Rule
3. Create New
4. Go to conditions, choose rule category

![image](https://user-images.githubusercontent.com/8234209/68844122-dfd41e80-06fb-11ea-9ca9-cd45ff060789.png)

### Expected result (*)

1. Have margin
![image](https://user-images.githubusercontent.com/8234209/68844237-0d20cc80-06fc-11ea-8f14-9d8e4c6837a0.png)

### Actual result (*)

1. No margin between checkbox and icon

![image](https://user-images.githubusercontent.com/8234209/68844160-ef536780-06fb-11ea-9bdd-771f62f92f31.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23132` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#25597 by @edenduong in 2.3-develop branch
Related commit(s):
 - [9f5fece4a8c330dd44e664eee8d137e162608945](https://github.com/magento/magento2/commit/9f5fece4a8c330dd44e664eee8d137e162608945)

The fix will be available with the upcoming 2.3.5 release.
