### ISSUE TITLE
Bug when create a new admin route with hyphen

### ISSUE THREAD

**Issue by diegocpires** [magento/magento2#25635]
### Preconditions (*)

1. Magento version 2.3-develop

### Steps to reproduce (*)

1. Create a new route, with hyphen in frontName. E.g.:

<router id="admin">

    <route id="adminmodule" frontName="-">

        <module name="Contribution_AdminModule" />

    </route>

</route>

2. Create a new menu for Admin. E.g.:

> 
> <menu>
>         <add
>             id="Contribution_AdminModule::admin_module"
>             title="Meu Menu"
>             translate="title"
>             module="Contribution_AdminModule"
>             sortOrder="100"
>             parent="Magento_Sales::sales"
>             resource="Contribution_AdminModule::new_page"
>           />
> 
>         <add
>             id="Contribution_AdminModule::new_page"
>             title="Treinamento Menu"
>             translate="title"
>             module="Contribution_AdminModule"
>             sortOrder="10"
>             parent="Contribution_AdminModule::admin_module"
>             action="-/index"
>             resource="Contribution_AdminModule::new_page"
>            />
> 

### Expected result (*)

1. A new and functional rote, with hyphen in url

### Actual result (*)

1. Got an exception

> 1 exception(s):
> Exception #0 (InvalidArgumentException): Param action doesn't pass validation: '-/index' does not match against pattern '/^[A-Za-z0-9\/_]+$/'
>

**Comment by VladimirZaets** [comment]
Hi @diegocpires. Thank you for your report. 
The issue has been fixed in magento/magento2#25612 by @diegocpires in 2.3-develop branch
Related commit(s):
 - [9898d5cc6e7dcec9eb3428d2e17a9fba014c6440](https://github.com/magento/magento2/commit/9898d5cc6e7dcec9eb3428d2e17a9fba014c6440)
 - [93dcd502a9b04c56fa46b5cc446915b4de5bf0c8](https://github.com/magento/magento2/commit/93dcd502a9b04c56fa46b5cc446915b4de5bf0c8)
 - [8327db6cb299ca3932b6e053dfb9c3da7f694170](https://github.com/magento/magento2/commit/8327db6cb299ca3932b6e053dfb9c3da7f694170)
 - [4fd4e60670df5bfe960ee7ad6f9ac96ac11fdcba](https://github.com/magento/magento2/commit/4fd4e60670df5bfe960ee7ad6f9ac96ac11fdcba)

The fix will be available with the upcoming 2.3.5 release.
