### ISSUE TITLE
Magento 2.3.3 Cronjob use too much CPU source

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#25634]
### Preconditions (*)

1.nginx, mysql5.6, php7.3, composer install magento 2.3.3
2.finish all the settings and set 3 cronjobs following the official document. 

### Steps to reproduce (*)

1.use top command to monitoring the task cpu usage.
2.run php bin/magento cron:run and check the cpu usage. 

### Expected result (*)

1. Smooth CPU usage, dose not cause the long time loading.

### Actual result (*)

1. long loading time because of the high CPU usage(Clean Magento 2.3.2: 1s
Clean Magento 2.3.3: 3.5s)
![20191118192805](https://user-images.githubusercontent.com/45879513/69048996-ce5f7f00-0a39-11ea-9718-49d6f20e1d4e.jpg)

 CPU usage record by panel
![微信截图_20191118191411](https://user-images.githubusercontent.com/45879513/69048818-627d1680-0a39-11ea-9df9-7240ab939ed1.png)
CPU usage

**Comment by Yuwei9291** [comment]
![微信截图_20191119133238](https://user-images.githubusercontent.com/45879513/69119305-1ed5eb80-0ad1-11ea-9d2a-05fe24445fa2.png)
CPU Monitoring info

**Comment by jorgb90** [comment]
Same issue here #25593

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-28949` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by interequipment** [comment]
Having same issue. (upgraded from 2.3.1  to 2.3.3)

**Comment by benyang2015** [comment]
someone can solve this problem?
now I'm disable the cronjob

**Comment by Jilco** [comment]
Is there a solution or work around? My CPU stays at 100%...

**Comment by atastycookie** [comment]
Hello,

Any updates or workarounds? Our "load average"  is ~40.6 on the clean installations

**Comment by Jilco** [comment]
Update, i was google "attacking" my site for some reason, they indexed 159.000 pages a day at once...

Adjusting robots.txt to index less was the sollution

**Comment by vincentteyssier** [comment]
Hi, when you run `di:compile` the cache gets disabled somehow.
Even if cache management shows green in the admin panel, it is set to 0 in the back end.
Run `php bin/magento cache:enable` and cron will run with same performances as 2.3.2

**Comment by jlfguthrie** [comment]
Had a similar issue and tracked it down to an AJAX Layered Navigation module. Disabling the module resolved the issue.

**Comment by roni-sooryen** [comment]
Seems like this issue is able to fix this problem #26507

**Comment by driskell** [comment]
#28007 can help with high CPU as it removes some deadlocks that prevent cron schedule table from being cleaned. It can also fix things stuck in running status.

**Comment by magento-engcom-team** [comment]
Hi @Yuwei9291. Thank you for your report. 
The issue has been fixed in magento/magento2#28007 by @driskell in 2.4-develop branch
Related commit(s):
 - [aa12503923ac994873724ecaa759e1eb14b318dc](https://github.com/magento/magento2/commit/aa12503923ac994873724ecaa759e1eb14b318dc)
 - [b0b72b0f8486ca119015e84b7786dfab13d2e475](https://github.com/magento/magento2/commit/b0b72b0f8486ca119015e84b7786dfab13d2e475)
 - [315bd3af8c5ed3dd711abd40db9a163b0c953855](https://github.com/magento/magento2/commit/315bd3af8c5ed3dd711abd40db9a163b0c953855)
 - [96029b55f7cd00b58967637aedac67ddd1767bad](https://github.com/magento/magento2/commit/96029b55f7cd00b58967637aedac67ddd1767bad)
 - [7df183b6c6bc3f57f0c3d29d279c3c6d631cf455](https://github.com/magento/magento2/commit/7df183b6c6bc3f57f0c3d29d279c3c6d631cf455)
 - [68d679b7bd7d371c5266d4803f03f204893f7af2](https://github.com/magento/magento2/commit/68d679b7bd7d371c5266d4803f03f204893f7af2)
 - [a90161907aedae371cb307759b685cc254efe2d8](https://github.com/magento/magento2/commit/a90161907aedae371cb307759b685cc254efe2d8)
 - [dda5c72c9303f9476ce7041743c87079cada87f6](https://github.com/magento/magento2/commit/dda5c72c9303f9476ce7041743c87079cada87f6)
 - [4d4fa685c0b507b510ad899f5afe94bd6c836115](https://github.com/magento/magento2/commit/4d4fa685c0b507b510ad899f5afe94bd6c836115)
 - [e95d2fefefb62150e566f000a4a17f58f6716af5](https://github.com/magento/magento2/commit/e95d2fefefb62150e566f000a4a17f58f6716af5)
 - [916bc93138f7a81f65c2e8b5069eeb0f35fceb43](https://github.com/magento/magento2/commit/916bc93138f7a81f65c2e8b5069eeb0f35fceb43)
 - [edd77531f8847f7b13dbaca9aefa315ba4aa5e57](https://github.com/magento/magento2/commit/edd77531f8847f7b13dbaca9aefa315ba4aa5e57)
 - [e70027f838f766b816bd1f7063514c1a9caf7a20](https://github.com/magento/magento2/commit/e70027f838f766b816bd1f7063514c1a9caf7a20)
 - [92dc76438063e68f7523d5ab036a57d7faf7bc03](https://github.com/magento/magento2/commit/92dc76438063e68f7523d5ab036a57d7faf7bc03)
 - [d1b22ff825052d836b56f8ce33760d42b2241980](https://github.com/magento/magento2/commit/d1b22ff825052d836b56f8ce33760d42b2241980)
 - [a76482c4614a7660ab2d324ca4c086f66906c701](https://github.com/magento/magento2/commit/a76482c4614a7660ab2d324ca4c086f66906c701)

The fix will be available with the upcoming 2.4.3 release.
