### ISSUE TITLE
Merge JavaScript Files does not work

### ISSUE THREAD

**Issue by andreaskoch** [magento/magento2#2563]
The configuration value for merging the JavaScript files has no effect.

**Environment**
- Magento Version: 2.0.0 CE
- Webserver: Nginx + PHP FPM

**Steps to reproduce**
1. Open the homepage of a Magento 2.0 CE Demo Store (e.g. [Magento 2 Developer Hub](http://magento.com/developers/magento2) > [MAGENTO 2.0 CE FRONTEND DEMO](http://magento2-demo.nexcess.net/))
2. Observe the number of JS requests in your browsers' network tab. About **120 JavaScript files** are being requested:
   ![Screenshot of the Magento 2.0 CE Frontend Demo Store JS Requests](https://cloud.githubusercontent.com/assets/247364/11474195/d610a9ca-9776-11e5-8b60-6cf60f65b651.png)
3. Goto `Backend > Stores > Configuration > Advanced > Developer > JavaScript Settings` and set `Merge JavaScript Files` to `Yes`
4. Click "Save Config"
5. Refresh all Caches
6. Goto the homepage and observe the number of JS requests in your browsers' network tab

**Observed Behavior**

All JavaScript files are still being loaded separately:

![Screenshot Number of JS Requests with JS Merge Enabled](https://cloud.githubusercontent.com/assets/247364/11476151/743c0d6a-9781-11e5-95c2-3a8c86040ad6.png)

**Comment by gordonknoppe** [comment]
You will see the number of requests reduced when Magento is in production mode.

**Comment by anton-huz** [comment]
`Merge JavaScript Files` to `Yes` currently merges only js files added to `<head>` explicitly.
You can open page source (`Ctrl+U`). And find that instead of several files (`../requirejs/require.js`, `../mage/requirejs/mixins.js`, `../requirejs-config.js`) you have something like `static/_cache/merged/26a...e.js`.

If you want to reduce number of request to different static files try to set
`Enable Javascript Bundling` to `Yes` and setup Magento mode to `production`.

**Comment by anton-huz** [comment]
It is not an issue.

**Comment by pynej** [comment]
How is this not an issue?  This setting both is misleading, isn't explained, and actually kills the site performance....
