### ISSUE TITLE
Wrong Css at "Minimum Qty Allowed in Shopping Cart" on Google Chrome

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25647]
### Preconditions (*)

1. 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configurations, Catalog->Inventory
3. Look at "Product Stock Options", "Minimum Qty Allowed in Shopping Cart"

![image](https://user-images.githubusercontent.com/8234209/69130401-0a025380-0ae3-11ea-9bc3-a7546b119fa2.png)

### Expected result (*)

1. Gray color as **Disabled**

![image](https://user-images.githubusercontent.com/8234209/69134099-944db600-0ae9-11ea-90dd-0eb5bb377026.png)

### Actual result (*)

1. No gray color

![image](https://user-images.githubusercontent.com/8234209/69130412-0f5f9e00-0ae3-11ea-821a-e4d24dabbcc8.png)

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-25647-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25647-2-3-develop.instances.magento-community.engineering/admin](https://i-25647-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-28938` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#25648 by @edenduong in 2.3-develop branch
Related commit(s):
 - [34998b6ee11084d047aeca7c137d4fd65818e821](https://github.com/magento/magento2/commit/34998b6ee11084d047aeca7c137d4fd65818e821)
 - [20fd591f056285e1d906fd64fe18919f83e5963e](https://github.com/magento/magento2/commit/20fd591f056285e1d906fd64fe18919f83e5963e)
 - [0a4393ccce5760c8551a315ac774b160c0b6e19a](https://github.com/magento/magento2/commit/0a4393ccce5760c8551a315ac774b160c0b6e19a)

The fix will be available with the upcoming 2.3.5 release.
