### ISSUE TITLE
Magento OpenGraph meta description / title content bleeding

### ISSUE THREAD

**Issue by NathMorgan** [magento/magento2#25654]
### Preconditions (*)
Magento Version: dev-2.3-develop

### Steps to reproduce (*)

1. Create a product in the admin
2. Within the product description / title create a sample description that contains double quotes `"`

### Expected result (*)
1. Content within the `<meta property="og:title"` and `<meta property="og:description"` to match what was entered in the admin

### Actual result (*)
1. Content bleeds out of the html attribute due to no escaping of the `"` character

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29000` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @NathMorgan. Thank you for your report. 
The issue has been fixed in magento/magento2#25655 by @NathMorgan in 2.4-develop branch
Related commit(s):
 - [cb1b7749c0520cb45cd47ec1560c62a06dbb172c](https://github.com/magento/magento2/commit/cb1b7749c0520cb45cd47ec1560c62a06dbb172c)

The fix will be available with the upcoming 2.4.0 release.
