### ISSUE TITLE
Wrong message in confirmation popup when delete customer group

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25661]
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Customer -> Customer Groups
3. Create customer group with name **test-test**
4. Back to grid, choose that customer, select and click delete
See:

![image](https://user-images.githubusercontent.com/8234209/69217923-3e891480-0ba2-11ea-8b2e-7657e44786f4.png)

### Expected result (*)

1. Correct message with **test-test**

### Actual result (*)

1. Wrong text: **test\u002Dtest**

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29003` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#25662 by @edenduong in 2.3-develop branch
Related commit(s):
 - [3020ac7ed08cdc07562fdede078e1ff27b779de0](https://github.com/magento/magento2/commit/3020ac7ed08cdc07562fdede078e1ff27b779de0)

The fix will be available with the upcoming 2.3.5 release.
