### ISSUE TITLE
Elasticsearch version selections in admin are overly broad

### ISSUE THREAD

**Issue by dobooth** [magento/magento2#25674]
### Preconditions (*)

1. 2.2.x
2. 2.3.x

### Steps to reproduce (*)

1. When choosing Elasticsearch versions in Stores > Settings > Configuration > Catalog > Catalog > Catalog Search

### Expected result (*)
- Elasticsearch
- Elasticsearch 5.x(not sure)
- Elasticsearch 6.x

### Actual result (*)
- Elasticsearch
- Elasticsearch 5+
- Elasticsearch 6+

**Issues:**
1) Elasticsearch 5 is EOL and should probably be removed for PCI.
2) The wording is overly broad. We say Elasticsearch 6+ but we really support 6.x. We do not yet support 7.
There is documentation if they want to use an older, out-of-date version.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29043` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @dobooth. Thank you for your report. 
The issue has been fixed in magento/magento2#25838 by @mautz-et-tong in 2.4-develop branch
Related commit(s):
 - [cf1b0845fd7d0c083b5f20ba2c0a495d0e9bf9ad](https://github.com/magento/magento2/commit/cf1b0845fd7d0c083b5f20ba2c0a495d0e9bf9ad)
 - [37cf56d23baf4d54fdfcd45b0c7570f2313c4813](https://github.com/magento/magento2/commit/37cf56d23baf4d54fdfcd45b0c7570f2313c4813)

The fix will be available with the upcoming 2.4.0 release.
