### ISSUE TITLE
Unable add product to cart in Magento 2.3.3 backend when stock quantity is 1 - "The requested qty is not available"

### ISSUE THREAD

**Issue by wibbel** [magento/magento2#25675]
The problem is only shown in the 2.3.3 backend when making orders from Magento Admin. Any product that is added to te order that only has available stock of 1 displays "The requested qty is not available". Quantities of greater than 1 are fine.

### Preconditions (*)
1. Magento 2.3.3
2. Standard luma system
3. From Admin backend, modify one of the products so that quantity in stock is 1 e.g. Joust Duffle Bag

![2019-11-20_18-51-16](https://user-images.githubusercontent.com/15927277/69268334-d698f500-0bc6-11ea-851c-17529bf27ecb.jpeg)

### Steps to reproduce (*)
1. Create a new customer order from backend, e.g select existing customer , roni_cost@example.com
2. Add the product to the cart that was changed to have stock of 1 e.g. Joust Duffle Bag

### Expected result (*)
1. product is added to cart without errors

### Actual result (*)
1. Error message is displayed  "The requested qty is not available"

![2019-11-20_18-50-35](https://user-images.githubusercontent.com/15927277/69268371-e7e20180-0bc6-11ea-94ac-a4b196d92737.jpeg)

**Comment by wibbel** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @wibbel. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @wibbel, here is your [Magento instance](https://i-25675-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25675-2-3-develop.instances.magento-community.engineering/admin](https://i-25675-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by wibbel** [comment]
Confirmed on test instance
![2019-11-20_18-59-26](https://user-images.githubusercontent.com/15927277/69269281-9470b300-0bc8-11ea-9f8c-3aea2da7de95.jpeg)

![2019-11-20_18-59-06](https://user-images.githubusercontent.com/15927277/69269292-99356700-0bc8-11ea-827a-1cc1abb7da93.jpeg)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25675-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25675-2-3-develop.instances.magento-community.engineering/admin](https://i-25675-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
I have verified this issue. I have reproduced this issue.
**Please see attached the video:**

![Qty_Issue](https://user-images.githubusercontent.com/24711761/69304936-6a5ed580-0c48-11ea-9a6d-bbae506addc9.gif)

@wibbel - When the user clicks on the "Update Items and Quantities' button, This error will be gone.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29034` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by not-art** [comment]
I'm unsure if this is related, but we're experiencing something similar:

If we have a configurable product with a simple child item that's at its last qty available of stock, we can add it to the cart, but if we update the cart programatically behind the scenes (post to our 3rd party payment provider and save a custom value on the quote, for example), Magento throws a, 

"Could not save custom_field_1 to quote: \nThe requested qty is not available"

This only happens for child items on configurables. This does NOT happen for simple items ordered by themselves.

I will file this as a separate bug, but it definitely feels related to this code execution path.

To reproduce:

1. Magento 2.3.3, with all 2.3.3 supplemental patches
2. MSI modules disabled
3. OOS Threshold set to 0 (so items go OOS after ordering 1 last qty), we also tested with OOS Threshold set to 3 (so items go OOS after ordering the 4th qty left)
4. Have a custom field on the quote table, lets call it "custom_field_1", make it a varchar(255)
5. Have an observer or plugin in your checkout progress (before converting your quote to an order / completing order), which updates quote.custom_field_1 to "test", preferably before payment step / after shipping step
6. Add a configurable item to your cart, selecting a child option whose stock is at 1, so this will be the last sellable unit
7. Proceed into checkout, proceed past shipping (to have your observer update the quote)
8. Rather than proceeding to your payment step of checkout, you'll return to cart, with a message of an unknown error occurring, and a log should be written saying "Could not save custom_field_1 to quote: \nThe requested qty is not available", if you have a try/catch around your  quote.setCustomField1("test") in your observer.

**Comment by magento-engcom-team** [comment]
Hi @wibbel. Thank you for your report. 
The issue has been fixed in magento/magento2#26650 by @molneek in 2.4-develop branch
Related commit(s):
 - [e088db1dcacf61f5861a8fffa607eabaef2ae66a](https://github.com/magento/magento2/commit/e088db1dcacf61f5861a8fffa607eabaef2ae66a)

The fix will be available with the upcoming 2.4.0 release.
