### ISSUE TITLE
 Address update at checkout shows some Weird thing

### ISSUE THREAD

**Issue by bst2002git** [magento/magento2#25684]
### Preconditions (*)
Magento 2.3.3

### Steps to reproduce (*)
Checkout change  Customer Address on payment

### Actual result (*)
I'v exactly this Result (with other Customer-Name)

https://magento.stackexchange.com/questions/293174/magento-2-3-3-address-update-at-checkout-shows-some-weird-thing
![wired_thing_1](https://user-images.githubusercontent.com/10232785/69343012-07336a00-0c6d-11ea-9b9e-15f9ed214ab1.png)
![wired_thing_2](https://user-images.githubusercontent.com/10232785/69343014-08649700-0c6d-11ea-9a64-491ddd13a3e9.png)

**Comment by bst2002git** [comment]
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment]
Hi @bst2002git. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bst2002git, here is your [Magento instance](https://i-25684-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25684-2-3-develop.instances.magento-community.engineering/admin](https://i-25684-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bst2002git** [comment]
Hmm, i'v imported some addresses into the develop instance to test (https://i-25684-2-3-develop.instances.magento-community.engineering/admin) and i can't see the file vendor/magento/magento2-base/lib/web/legacy-build.min.js being loaded. Which on my magento 2.3.3 installation is loaded and makes the wired thing...
When/Why is legacy-build.min.js be loaded?

**Comment by AnnaShepa** [comment]
Hi @bst2002git  I tried to reproduce the issue using the same address as on screenshot on test instance and on own environment (with the legacy-build.min.js file), but for me it still looks fine. Please check you js file and try to reproduce on clear magento. You can also check in dev tools some js erors

**Comment by achleitner** [comment]
Anyone got a solution for this`? Happening on Magento 2.3.4

**Comment by bst2002git** [comment]
Hello @achleitner ,
i've removed "prototype" from vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js
see issue #26378

**Comment by achleitner** [comment]
> Hello @achleitner ,
> i've removed "prototype" from vendor/magento/module-braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js
> see issue #26378

hey @bst2002git this works is just perfect! Many thanks! Should have checked github for a response 9 hours ago :)

**Comment by Eddcapone** [comment]
I have this issue in 2.4.2 Enterprise.

**Comment by cdcrothers** [comment]
Issue still exists in 2.4.2-p2 Enterprise.

Caused by lib/web/legacy-build.min.js
which maps to prototype
which is depended on by Magento_GoogleTagManager/js/google-analytics-universal
which is depended on by vendor/magento/module-google-tag-manager/view/frontend/web/js/google-tag-manager-cart.js
which is injected by vendor/magento/module-google-tag-manager/view/frontend/templates/js.phtml
referenced by vendor/magento/module-google-tag-manager/view/frontend/layout/default.xml
which only happens when google/analytics/active  is enabled

so enable it, and you'll reproduce the issue.

"prototype" is a lib that's been without support for 7+ years. This lib makes some seemingly very global changes to the array prototype. First glance, I'd bet the Enumerable object is being treated as an item in the street array for some reason. Seems like an underlying conflict with prototype.js, and another js library such as underscore or jquery.
