### ISSUE TITLE
Incorrect behaviour of export/import logic for product with datetime attribute

### ISSUE THREAD

**Issue by staradzinau** [magento/magento2#25700]
### Preconditions (*)

1. Magento 2.3.3 or 2.3-develop
2. Set Locale to "English (United Kingdom)"
3. Default County: United States
4. Product attribute with "Catalog Input Type for Store Owner" => 'Date' (for example - 'test_date_attribute')
5. Add this attribute to default attribute set
6. Simple product with date attribute 'test_date_attribute' is created. (SKU = 'test-product-sku')

**Scenario 1**
**Steps to reproduce**

1. Set some date for the 'test_date_attribute' attribute for product 'test-product-sku'. (Day of the month should be greater than 12)
![Screenshot from 2019-11-25 14-49-45](https://user-images.githubusercontent.com/51681435/69542453-28a99400-0f94-11ea-8901-f613db11c1fd.png)
2. Go to System -> Export, perform products export operation to create a CSV, which contains product 'test-product-sku' with the value of 'test_date_attribute' attribute
![Screenshot from 2019-11-25 15-22-43](https://user-images.githubusercontent.com/51681435/69544050-999e7b00-0f97-11ea-8c0a-bd90f2b2c58d.png)

### Expected result (*)
Value of 'test_date_attribute' attribute in the product creation page is formatted according to the current locale

### Actual result (*)
The format of the attribute value 'test_date_attribute' on the product creation page does not match the current locale

 
**Scenario 2**
**Steps to reproduce**

1. Go to System -> Import, choose 'Products' entity type, upload CSV form the previous scenario, and click on "Sheck Data" button

### Expected result (*)
Exported data is validated correctly, the "Import" button is shown

### Actual result (*)

Format of the value of 'test_date_attribute' attribute in the product creation page, do not correspond to the current locale. Exported data validation is failed
![Screenshot from 2019-11-25 14-33-30](https://user-images.githubusercontent.com/51681435/69544150-ca7eb000-0f97-11ea-8934-3b3d220eb181.png)

### Additional information
After manual modifying of the date format to the US one inside CSV file, validation works correctly, import operation works fine

**Comment by staradzinau** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @avgust1111. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @avgust1111, here is your [Magento instance](https://i-25700-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25700-2-3-develop.instances.magento-community.engineering/admin](https://i-25700-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by staradzinau** [comment]
It's impossible to reproduce the issue within the provided Magento instance: running cron job is required for fetching export results (CSV file). Seems like specified M2 instance doesn't have running cron job

**Comment by engcom-Echo** [comment]
Hello @avgust1111 

Thank you for your report and collaboration!
We are not able to reproduce this issue by provided steps.
Tested on 2.3-develop and 2.3.3 

**Testing scenario:**

**Preconditions:**

1. Default locale - United States
2. Product attribute with "Catalog Input Type for Store Owner" => 'Date' (for example - 'test_date_attribute')
3. Add this attribute to default attribute set
4. Simple product with date attribute 'test_date_attribute' is created. (SKU = 'test-product-sku')

**Scenario 1**
**Steps to reproduce** 
1. Set some date for the 'test_date_attribute' attribute for product 'test-product-sku'. (Day of the month should be greater than 12)
2. Go to System -> Export, perform products export operation to create a CSV, which contains product 'test-product-sku' with the value of 'test_date_attribute' attribute

**Result**
Value of 'test_date_attribute' attribute in the CSV is formatted according to the current locale
![Screenshot from 2019-11-22 16-24-45](https://user-images.githubusercontent.com/51681435/69438326-7e402f80-0d4d-11ea-8379-0443a30ad5eb.png)
![Screenshot from 2019-11-22 17-25-51](https://user-images.githubusercontent.com/51681435/69438281-6bc5f600-0d4d-11ea-93de-14eacbf06225.png)

**Scenario 2**

**Steps to reproduce** 

1. Go to System -> Import, choose 'Products' entity type, upload CSV form the previous scenario, and click on "Sheck Data" button

**Result**
Exported data is validated correctly, the "Import" button is shown
![Screenshot from 2019-11-22 17-32-47](https://user-images.githubusercontent.com/51681435/69438744-44bbf400-0d4e-11ea-96bf-c431ad829832.png)
Thank you!

**Comment by staradzinau** [comment]
Hello, @engcom-Echo !
Thank you for the quick feedback

Please, check, which county is used in the "Country options" section in the "General" tab?
Had your CSV export file been generated by cron, after some delay?

I've reproduced the same issue on the 2.3.3 installation with native sample data, all the dates in the CSV export file have the incorrect format, please, look:
![aw_651](https://user-images.githubusercontent.com/24728606/69440098-3aebbe00-0d59-11ea-8ab5-a400773436f7.png)
![aw_652](https://user-images.githubusercontent.com/24728606/69440121-4343f900-0d59-11ea-979c-12ed9f91cd71.png)
Month and day aren't compatible with US date format

**Comment by engcom-Echo** [comment]
Hello @avgust1111 

Here is my Settings (M 2.3.3)
![Screenshot from 2019-11-25 13-12-22](https://user-images.githubusercontent.com/51681435/69536747-44f30400-0f87-11ea-9f55-bd5d9c30ccf5.png)
![Screenshot from 2019-11-25 13-12-37](https://user-images.githubusercontent.com/51681435/69536763-4cb2a880-0f87-11ea-8ad0-e4c895300c69.png)

All my CSV export files has been generated by cron after some delay.
All files have the correct date format.

![Screenshot from 2019-11-25 13-30-30](https://user-images.githubusercontent.com/51681435/69537053-ef6b2700-0f87-11ea-8643-2cab70cef2cf.png)

Could you provide more details for reproduce this issue?
Please add screenshots of the attribute settings.

Thank you!

**Comment by staradzinau** [comment]
Hello, @engcom-Echo !

Thank you for the update.
I've checked settings again and found the option, which triggers misbehavior for import/export. In my test environment with native M2 sample data installed, 'Locale" has been set to "English (United Kingdom)". So, if you set in "Stores" -> "Configuration" -> "General" -> "General" -> Country Options -> Default County: United States, and in "Stores" -> "Configuration" -> "General" -> "General" -> Locale Options -> Locale: "English (United Kingdom)", your exported CSV file will contain dates in the wrong format
Sorry for incomplete steps to reproduce
Please, check this case

Thank you!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29131` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sanjay-wagento** [comment]
#MM20IN

**Comment by engcom-Delta** [comment]
Hi @staradzinau  ,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached screenshots.


Default County: United States

<img width="1428" alt="Screenshot 2024-05-22 at 10 10 13 PM" src="https://github.com/magento/magento2/assets/51681379/47123c3d-514b-45ac-b152-4ace1a170ca8">

Set Locale to "English (United Kingdom)"

<img width="1440" alt="Screenshot 2024-05-22 at 10 10 35 PM" src="https://github.com/magento/magento2/assets/51681379/0730d52d-5fe5-4104-b4ef-9245548b4e62">

Product attribute with "Catalog Input Type for Store Owner" => 'Date' (for example - 'test_date_attribute')

<img width="1437" alt="Screenshot 2024-05-22 at 10 18 15 PM" src="https://github.com/magento/magento2/assets/51681379/f62da920-0ba7-4190-91d1-fbe4658dca22">

Added attribute to default attribute set

<img width="1440" alt="Screenshot 2024-05-22 at 10 19 33 PM" src="https://github.com/magento/magento2/assets/51681379/6873993d-3ad4-4367-beb8-616a42f4f83a">

Simple product with date attribute 'test_date_attribute' is created. (SKU = 'test-product-sku')

<img width="1438" alt="Screenshot 2024-05-22 at 10 25 17 PM" src="https://github.com/magento/magento2/assets/51681379/2308fbad-9963-4026-baf4-6f3bfe9210eb">

Value of 'test_date_attribute' attribute in the product creation page is formatted according to the current locale

<img width="182" alt="Screenshot 2024-05-23 at 12 06 13 AM" src="https://github.com/magento/magento2/assets/51681379/dea00e97-da01-472a-b70d-d491e2d60ce9">


Click on Import and add data

<img width="1431" alt="Screenshot 2024-05-23 at 12 18 16 AM" src="https://github.com/magento/magento2/assets/51681379/4692b620-f641-4476-9b61-ed1b739d6b81">

Add CSV

<img width="1440" alt="Screenshot 2024-05-23 at 12 22 57 AM" src="https://github.com/magento/magento2/assets/51681379/201b4cf9-7c7c-4d34-bbf5-5726e2107d25">

Exported data is validated correctly, the "Import" button is shown

<img width="1440" alt="Screenshot 2024-05-23 at 12 23 16 AM" src="https://github.com/magento/magento2/assets/51681379/2cc160d8-712a-490c-9393-18d373d04b02">


Hence We are closing this issue.
