### ISSUE TITLE
Google ReCaptcha API keys issue

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#25735]
### Preconditions (*)

1. Magento 2.3.3 (only in composer version)
### Steps to reproduce (*)

1. Setup an invisible ReCaptcha on frontend admin panel -> Stores-> Settings -> Configuration -> Security -> Google Recaptcha 
2. Setup a backend ReCaptcha (this is fixed as visible type)

### Expected result (*)

1. Either both frontend and backend should use invisible captcha as the API key is valid for this only or the API keys should be unique fields to frontend and backend

### Actual result (*)

1. Because the API key is for an invisible type and the backend is fixed at visible type you will become locked out of the backend with an "Incorrect ReCaptcha" message.

**Comment by devchris79** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @devchris79. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @devchris79, here is your [Magento instance](https://i-25735-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25735-2-3-develop.instances.magento-community.engineering/admin](https://i-25735-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devchris79** [comment]
Is the security tab removed from the develop instance? I can't see it...

I set up on my site like below:
https://docs.magento.com/m2/ce/user_guide/stores/security-google-recaptcha.html

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29186` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by SuperDiglett** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kevinvhengst. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by devchris79** [comment]
@sdzhepa Sorry I don't know if the bot unassigned you as a result of my accidental closure of this issue. I have re-opened as the issue remains outstanding.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30407` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @devchris79 

This issue was completely fixed and will be available in the next 2.4.0 release

Google reCapctha functionality was moved into new [security-package ](https://github.com/magento/security-package)
And was significantly refactored and partially reworked.
Now we have separate input fields per each reCAPCTCHA types and a different set of settings for Admin and Storefront

![2020-06-25_16-28-05](https://user-images.githubusercontent.com/3409584/85797258-e51d3100-b700-11ea-8693-af36c5514c47.jpg)


So, I think this issue is not actual any more and can be closed.
But if you have any additional issues related to reCAPCTHA please report it to the [security-package issue backlog](https://github.com/magento/security-package/issues)
