### ISSUE TITLE
queue_consumer.xml doesn't allow numbers in handler class

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#25731]
### Preconditions (*)

1. Magento 2.3.3 & 2.3-develop

### Steps to reproduce (*)

1.  Create a `queue_consumer.xml`
2. Specify a *handler* with a number in the path

### Expected result (*)

1. XML validation passes

### Actual result (*)

1. XSD validation fails because handler contains invalid characters 

This problem was already reported and closed without a solution: https://github.com/magento/magento2/issues/16168
Similar problem: https://github.com/magento/magento2/issues/14882.

Solution should be simple, just add *0-9* to the pattern in [consumer.xsd](https://github.com/magento/magento2/blob/2.3.3/lib/internal/Magento/Framework/MessageQueue/etc/consumer.xsd#L35)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29185` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your report. 
The issue has been fixed in magento/magento2#25952 by @edenduong in 2.4-develop branch
Related commit(s):
 - [fe935a668044bf02852b5b2ddcb01834090132a7](https://github.com/magento/magento2/commit/fe935a668044bf02852b5b2ddcb01834090132a7)

The fix will be available with the upcoming 2.4.0 release.
