### ISSUE TITLE
Site map doesn't include home page

### ISSUE THREAD

**Issue by vseager** [magento/magento2#25761]
### Preconditions (*)
1. 2.3.3 or 2.3-develop

### Steps to reproduce (*)

1. Go to Stores > Settings > Configuration > Catalog > XML Sitemap > Generation Settings section
2. Change option Enabled to Yes
3. Go to `Marketing > Seo & Search > Site Map`
4. Create a new site map and generate
5. Open new site map in browser

### Expected result (*)
1. Sitemap should include the home page 
![Sitemap](https://user-images.githubusercontent.com/51681435/69860528-29496f80-129f-11ea-920b-b208941bf6f0.png)

### Actual result (*)
1. Sitemap does note include the home page
![Sitemap-1](https://user-images.githubusercontent.com/51681435/69861197-901b5880-12a0-11ea-8265-b1b22fcd4020.png)

**Comment by engcom-Echo** [comment]
Hello @vseager 

Thank you for your report and collaboration!

Could you provide a use case why Sitemap should include the home page?

Thank you!

**Comment by vseager** [comment]
@engcom-Echo the XML sitemap should include all (crawlable) pages within the site. It is through submitting the XML sitemap to Google Search Console that you can inform Google when the page was last updated and how regularly it should be crawled.

Is there a use case where it shouldn't include the home page?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29275` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @vseager. Thank you for your report. 
The issue has been fixed in magento/magento2#26445 by @deepaksnair in 2.4-develop branch
Related commit(s):
 - [3bffb4cc8d16dcb5a4fa5358accd3b3bcedfcd02](https://github.com/magento/magento2/commit/3bffb4cc8d16dcb5a4fa5358accd3b3bcedfcd02)
 - [57b8f53c447a8b07f521a677678921364891b3b6](https://github.com/magento/magento2/commit/57b8f53c447a8b07f521a677678921364891b3b6)
 - [f165a5375830077ebaed7d07f7d8c965332ffae9](https://github.com/magento/magento2/commit/f165a5375830077ebaed7d07f7d8c965332ffae9)
 - [8f5b2c7ff88d4771ad34bd0548185d3cc0c30643](https://github.com/magento/magento2/commit/8f5b2c7ff88d4771ad34bd0548185d3cc0c30643)
 - [d93fe31aa16a297c28dcba4c5f8ad906475e08f2](https://github.com/magento/magento2/commit/d93fe31aa16a297c28dcba4c5f8ad906475e08f2)
 - [dec897285bb89e971c9597746d501bf9e84515f6](https://github.com/magento/magento2/commit/dec897285bb89e971c9597746d501bf9e84515f6)

The fix will be available with the upcoming 2.4.0 release.
