### ISSUE TITLE
Ordered Products Report not grouping by configurable products variations

### ISSUE THREAD

**Issue by lgrassini** [magento/magento2#25856]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. In the Magento 2 admin go to Reports -> Products -> Ordered
2. Select a date range where you know you have sold products spanning across multiple orders
3. Select 'Show By' Month
4. Hit Refresh

### Expected result (*)

The list of products grouped by SKU instead of product_id. So we can have information about number of products ordered for each product variation (ie: color).

### Actual result (*)
Currently the report is grouping configurable porducts by product_id. Displaying the total of all of the variations (child products) into one product. The report, then, is not providing the total of each product variation like the example bellow:

![incorrect-report](https://user-images.githubusercontent.com/5750506/69886908-a9de8f00-12e4-11ea-8e9c-fb08dad2bfd7.png)

### Propposed Fix 
I fixed this in my local enviroment by replacing the GROUP BY clause from `GROUP BY order_items.product_id` to `GROUP BY order_items.sku`. on app/code/Magento/Reports/Model/ResourceModel/Product/Sold/Collection.php

![fix](https://user-images.githubusercontent.com/5750506/69888169-c8e01f80-12ea-11ea-945a-9d9975f7bd04.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29286` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @lgrassini. Thank you for your report. 
The issue has been fixed in magento/magento2#25858 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [840cec90c04a917530c3b9d652b4c39ba763e89d](https://github.com/magento/magento2/commit/840cec90c04a917530c3b9d652b4c39ba763e89d)
 - [5fb9d49ac15f785ccede9a7df5bc01161f3ee5f5](https://github.com/magento/magento2/commit/5fb9d49ac15f785ccede9a7df5bc01161f3ee5f5)
 - [ffa3d2e51af3e577db5d74d4dff37e67e22d0fc1](https://github.com/magento/magento2/commit/ffa3d2e51af3e577db5d74d4dff37e67e22d0fc1)
 - [40311e95917e0631ea43834866b969e290cf667e](https://github.com/magento/magento2/commit/40311e95917e0631ea43834866b969e290cf667e)
 - [db0201317dc2afa738eb2ba940e11e9eb5ff1fd5](https://github.com/magento/magento2/commit/db0201317dc2afa738eb2ba940e11e9eb5ff1fd5)

The fix will be available with the upcoming 2.4.0 release.
