### ISSUE TITLE
Attribute Type Multiple Select - Radio button and default value issue

### ISSUE THREAD

**Issue by duerstd** [magento/magento2#2587]
I created a new attribute with the type "Multiple select" and filled in some values. 
## First issue:

When creating the new attribute and add some managed options, these options have a radio button to select the default ones. There should be check boxes to select multiple default managed options.
Btw: After saving and reediting there are check boxes.

![radio_button_issue](https://cloud.githubusercontent.com/assets/15245162/11559360/722315d0-99b8-11e5-9ed7-f4fa41bbe143.PNG)
## Second issue:

The first managed option is always selected as default. Even if I select other default manage options and deselect the first one.

Base situation, 3 default manage options selected:
![capture](https://cloud.githubusercontent.com/assets/15245162/11559384/9a0fc7be-99b8-11e5-8c40-ac6500b28b37.PNG)

Step 1, remove the first manage option from the default:
![remove_first_default_value](https://cloud.githubusercontent.com/assets/15245162/11559394/aebe8042-99b8-11e5-8cfa-96234ab0264b.PNG)

Step 2, save the attribute

Step 3, edit the attribute for check -> still 3 selected
![capture](https://cloud.githubusercontent.com/assets/15245162/11559410/d317aba8-99b8-11e5-8303-248c0eb1aae3.PNG)

**Comment by kmlav** [comment]
We are having the same issue. I have raised a ticket with the Magento support team and will let you know the outcome

**Comment by vzabaznov** [comment]
@duerstd thank you for reporting, internal tickets MAGETWO-50276 was created

**Comment by kmlav** [comment]
here is the response from Magento enterprise support 
**
My developer replied that both issues will be fixed in an upcoming Core code release.
Therefore, merchant has to wait until it is released.

I do not have an ETA on when the core upgrade version will be released, nor what version will have this fix.

I apologize that I am unable to obtain a patch fix for your issues and that you will have to wait for the future release that will contain this fix.
**

**Comment by magento-engcom-team** [comment]
@duerstd thank you for your report.
The fix for this issue is already available in release 2.1
