### ISSUE TITLE
Composer Install on magento/composer (1.0.2) is a fail

### ISSUE THREAD

**Issue by pubkey** [magento/magento2#2589]
I'm trying to install the newest Magento2.

When running

``` r, engine='bash', count_lines
 #composer install
```

it asks me for credentials to repo.magento.com

This is realy annoing because of the following reasons:
1. I don't have an account at repo.magento.com, and I also don't want to have one for every developer on my projekt.
2. When installing Magento inside a DockerImage, I have no iTerminal to insert the credentials automatically.
3. I created an account at repo.magento.com and it also doesnt work, with the following output:
   
   [Composer\Downloader\TransportException]  
   Invalid credentials for 'https://repo.magento.com/archives/magento/composer/magento-composer-1.0.2.0.zip', aborting. 

And yes, the password is correct.

Why on earth does an open-source software need to have closed source from a magento-repo?

**Comment by daim2k5** [comment]
I can't answer your last question but please take a look at
http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

maybe you use the wrong credential

**Comment by alankent** [comment]
I wrote up a blog post describing why there is password protection on the composer repo. It is not to stop access to free stuff, but rather given a personalized view of the contents. (It does stop access to non-free stuff unless you have paid for it!) E.g. Enterprise customers get access to more modules that they have paid for. The same will be true for all paid extensions. http://alankent.me/2015/11/22/magento-2-and-composer-authentication/

Note that the repo does not use your normal username/password. You set up credentials (which you can also revoke). This would go in your project's auth.json file (supported by Composer). Then all the team members can share that file (don't make it public, but it is fine to put into a private GIT repo). If it is compromosed, you can invalidate the credentials and create new ones (which is why it is separate to the username/password of the account).

**Comment by pubkey** [comment]
Thanks to @alankent and @daim2k5 for the gread answer. I got it running now and saved the credentials into the auth.json.

Even if I still think thats it's impolite to require a repo.magento.com-account, my problem is solved.

**Comment by maggiefor** [comment]
thank you, @alankentx !! You solved my problem!!

**Comment by maggiefor** [comment]
thank you, @alankent !! You solved my problem!!
