### ISSUE TITLE
Cannot create folder using only letters

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25896]
### Preconditions (*)

1. M 2.3.3

### Steps to reproduce (*)

1. On CMS edit page open media gallery
2. Click "Create Folder"
3. Type in "папка"
4. Click "OK"

### Expected result (*)

1. Consistency between message and behavior. Example:
`Please rename the folder using only Latin letters, numbers, underscores and dashes.`
2. Optional: the folder was created

### Actual result (*)

1. Message:
`Please rename the folder using only letters, numbers, underscores and dashes.`
![image](https://user-images.githubusercontent.com/11827230/70133540-fe8c5c00-168e-11ea-9abd-5d5cdf759139.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29385` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/magento2#25904 by @edenduong in 2.4-develop branch
Related commit(s):
 - [a4d57b99f4163ca929433f20d56630e99f234a54](https://github.com/magento/magento2/commit/a4d57b99f4163ca929433f20d56630e99f234a54)
 - [721f8cedc063e405074c0ceaea200f0c44f905eb](https://github.com/magento/magento2/commit/721f8cedc063e405074c0ceaea200f0c44f905eb)
 - [17a575a1ed64b6c74d969051877f01e25621ef58](https://github.com/magento/magento2/commit/17a575a1ed64b6c74d969051877f01e25621ef58)

The fix will be available with the upcoming 2.4.0 release.
