### ISSUE TITLE
Choose drop down not close when open another for upload file for swatch

### ISSUE THREAD

**Issue by hasim32** [magento/magento2#25910]
Choose drop down not close when open another for upload file for swatch

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
1. Admin - Stores
2. Attributes - Product
3. Add New Attribute 
4. Properties - Select Visual swatch from Catalog Input Type for Store Owner drop down
5. Click on Add Swatch - Upload image/color
6. Add Swatch again - Click on choose file 
7. without close this click on 1st swatch choose drop down

### Expected result (*)
Other choose file drop down should close once open another

### Actual result (*)
![image](https://user-images.githubusercontent.com/56119534/70230210-df202c80-177d-11ea-8d49-d93d05e02eb0.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29441` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Usik2203** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [Magento instance](https://i-25910-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25910-2-4-develop.instances.magento-community.engineering/admin](https://i-25910-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @hasim32. Thank you for your report. 
The issue has been fixed in magento/magento2#26090 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [423a4da934215f9a58ef96d0c37aa7f099a8a2ef](https://github.com/magento/magento2/commit/423a4da934215f9a58ef96d0c37aa7f099a8a2ef)
 - [96a9f3a4f36f8700fc88b29a63ebb68ed3de9bf4](https://github.com/magento/magento2/commit/96a9f3a4f36f8700fc88b29a63ebb68ed3de9bf4)
 - [2527b04cbe29054e9740c5e9634bb9ab0769cadf](https://github.com/magento/magento2/commit/2527b04cbe29054e9740c5e9634bb9ab0769cadf)
 - [5f14e0e07234b798d776637884907327cc4453af](https://github.com/magento/magento2/commit/5f14e0e07234b798d776637884907327cc4453af)
 - [7cd12dd62b71f642ff07cdb2f5745953dd3a6f47](https://github.com/magento/magento2/commit/7cd12dd62b71f642ff07cdb2f5745953dd3a6f47)

The fix will be available with the upcoming 2.4.0 release.
