### ISSUE TITLE
Admin confirm password input doesn't inherit needed styles

### ISSUE THREAD

**Issue by eduard13** [magento/magento2#25917]
### Preconditions (*)
1. Magento 2.3.3
2.

### Steps to reproduce (*)
1. Navigate to `System / Integrations`
2. Click on `Add New Integration` button
3. Scroll down to `Current User Identity Verification` fieldset

### Expected result (*)

1. The `Your Password` field has the input style
![image](https://user-images.githubusercontent.com/15868188/70248651-dfbbc180-1783-11ea-82ad-ec1c0a96b587.png)

### Actual result (*)
1. The `Your Password` field doesn't inherit admin input style.
![image](https://user-images.githubusercontent.com/15868188/70248546-b7cc5e00-1783-11ea-9362-79c053219e11.png)

**Comment by eduard13** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-25917-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25917-2-3-develop.instances.magento-community.engineering/admin](https://i-25917-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29447` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your report. 
The issue has been fixed in magento/magento2#25918 by @eduard13 in 2.4-develop branch
Related commit(s):
 - [67c55ec5b8bd00ad78355df34362e1a754980bf7](https://github.com/magento/magento2/commit/67c55ec5b8bd00ad78355df34362e1a754980bf7)
 - [18281bbb12f323c20764a5128f962912782b852a](https://github.com/magento/magento2/commit/18281bbb12f323c20764a5128f962912782b852a)
 - [8ea3d264ae8be701faa30bc597fd046b697d1582](https://github.com/magento/magento2/commit/8ea3d264ae8be701faa30bc597fd046b697d1582)
 - [3e65b3732aeee0e87fc66b2b66eb06cfed2acd52](https://github.com/magento/magento2/commit/3e65b3732aeee0e87fc66b2b66eb06cfed2acd52)

The fix will be available with the upcoming 2.4.0 release.
