### ISSUE TITLE
Google Shopping Ads - Cannot use Merchant Account created by Magento

### ISSUE THREAD

**Issue by jsdupuis** [magento/magento2#25927]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.1

### Steps to reproduce (*)

1. Go in Marketing --> Google Shopping Ads menu
2. Go through the whole onboarding process (link to Google account, create Google Merchant Account, claim website, create Google ads account, etc.)

### Expected result (*)

1. Account status is Approved
2. I can run Google ads

### Actual result (*)

1. A few hours after completing the onboarding process, I lost ownership of the Google Merchant Center (GMC) account created by Magento. 
2. Claim status changed to "unclaimed" and account status changed to "disapproved".
3. I cannot access the GMC account through my own Google account (i was able to for a few hours)
4. I cannot re-claim my website because the URL field in the settings is disabled and my URL grayed out
5. I cannot create a new GMC account by clicking on the button in Magento
6. Google Support cannot help me because the account created by Magento doesn't belong to me directly. Google told me to contact the owners...
7. Nobody replies to emails sent to channels@adobe.com (developer of the original extension)
8. Nothing in the troubleshooting documentation of either Google or Magento covers this case

I'm guessing this issue with be closed (traditional "cannot reproduce"), but I'd like to know if there are some instructions to reset and restart the onboarding process from scratch.

**Comment by engcom-Echo** [comment]
Hello @jsdupuis 

Thank you for your report and collaboration!
Try to clear browser and magento cache. If it doesn't help try to open magento in Incognito Window. Then try to create a new GMC account.

**Comment by jsdupuis** [comment]
Hi @engcom-Echo 

Thank you for the suggestions. I tried clearing browser and magento cache and going Incognito, but problem is the same. As further details, if I go in Settings, i see my GMC id and I can choose "edit URL" in the drop down. Screenshot 1 shows that I cannot edit my URL (all is greyed out).

If I try to create a new GMC account (screenshot 2), I cannot select a URL. It says "no option" probable because the URL is already selected in current GMC account. :(

Screenshot 1
![screen1](https://user-images.githubusercontent.com/28755070/70317294-10692d00-1850-11ea-9223-d6215acb0208.jpg)

Screenshot 2
![screen2](https://user-images.githubusercontent.com/28755070/70317296-10692d00-1850-11ea-916f-b789477e4bb8.jpg)

**Comment by engcom-Echo** [comment]
@jsdupuis 

Can you delete an old account?
[Here](https://docs.magento.com/m2/2.2/ee/user_guide/sales-channels/google-ads/gmc-unlink-gmc.html) is more info.

**Comment by jsdupuis** [comment]
@engcom-Echo I used to be running Shopping Ads before 2.3.3, but I unclaimed/unlinked my website before going through the onboarding process. I even deleted my old GMC account today in hope that it would solve the problem.

Is there any Magento log I can check to help investigate?

**Comment by engcom-Echo** [comment]
@jsdupuis 

You can check system.log and exception.log.
Also files in the Report folder. (If it doesn't exist - that's ok)

**Comment by jsdupuis** [comment]
@engcom-Echo 

I cannot find anything related in the log files. system.log shows this every day but it doesn't look like an error.

> [2019-12-06 10:34:34] main.INFO: Add of item with id Magento_GoogleShoppingAds::scconnector was processed [] []
> [2019-12-06 10:34:34] main.INFO: Add of item with id Magento_GoogleShoppingAds::scconnector_google was processed [] []

It's really confusing that Magento says "Website URL not provided" when we can see in my first screenshot that it was provided. 

![screen3](https://user-images.githubusercontent.com/28755070/70369503-21b44700-18ed-11ea-8a1a-6ff5c22b627a.jpg)

**Comment by jsdupuis** [comment]
So what happens is that the Google account of Magento (magentosaleschannels@gmail.com) creates both the GMC account and the Google Ads account and gives permission to the Magento user (me) to use these accounts. Somehow after the onboarding process I lost permission to access/manage the GMC account. I still have access to the Google Ads account where I can see under Tools & Settings --> Account Access that magentosaleschannels@gmail.com is the "inviter user". See screenshot 4.

Now how can I gain permission to manage my GMC account again? I tried contacting that email as well, but no reply. Probably a bot account of the module.

![screen4](https://user-images.githubusercontent.com/28755070/70411122-ee57f080-1a83-11ea-99fb-bb4f51c4bafe.jpg)

**Comment by ABARAUJOMGA** [comment]
I had exactly the same problem. Im watching the conversation.

**Comment by yumicom** [comment]
I have the same problem on magento 2.3.2-p2. 
I have several times created a new google merchant account and every time I lost access to it after linking to the Google ads account. 
To be able to start all over again, clear the "Unique ID" field in Stores-Configuration-Services-Channels

**Comment by ABARAUJOMGA** [comment]
Tried deleting the UNIQUE ID and creating.

Same problem happened. New account was in Magento Panel, and all of a suden i was disconnected from my GMC account. When i reconnected, the new acount was missing. 

But i have new insights about this problem:

1. The new GMC account just vanish AFTER you create the google ads account.
2. I tried a smart strategy that didn't work out. After i create the new GMC account i registered another email as admin user. So, i thought if they delete my account, i will have another one that would be able to use it.

No. They locked me off from all accounts.

**3. A question:** Since there should be thousands of users of magento 2.3 in the world, and this is happening just with us, could it be something we've done to our magento?


Thanks
Lucas

**Comment by jsdupuis** [comment]
@ABARAUJOMGA @yumicom 
Maybe we can try to help the developer assigned to this task by finding a pattern within our 3 cases. I'm sure there's more people affected by this bug, but let's try answering these questions:

1. Did you have an existing GMC account before going through the onboarding process?
2. Did you have a Google Ads account before going through the onboarding process?
3. Was your website URL claimed by another GMC account before?
4. In Stores --> Configuration --> Sales --> Google API --> Google Adwords, were you already using Conversion ID feature?

My own answers are 'yes' to all 4. I did unclaim my website as recommended in the setup guide, but i have the feeling it's something about it.

**Comment by Marineimpulseo** [comment]
Hi @engcom-Echo , @m2-assistant,

I'm also in the same situation.

GMC account created on Magento 2.3.3 on Monday, 09th, then well connected to my Merchant Center and Google Adwords. But yesterday, so on the 12th, the account disappears from my Merchant Center.
The Google adwords account is still existing. 

Regarding your previous questions :
1/ Yes I already have a GMC account
2/ Yes as well
3/ Yes it was claimed by my previous GMC account. I have now removed my previous account for this URL.
4/ Yes.

Hope you can help on this matter soon.

**Comment by ABARAUJOMGA** [comment]
I personally have MAJOR interest in solving this question because google shopping ads is almost 70% of my sales. And not being able to use it is ruining my busines.

Answering your questions:


Did you have an existing GMC account before going through the onboarding process?
Did you have a Google Ads account before going through the onboarding process?
Was your website URL claimed by another GMC account before?
In Stores --> Configuration --> Sales --> Google API --> Google Adwords, were you already using Conversion ID feature?
My own answers are 'yes' to all 4. I did unclaim my website as recommended in the setup guide, but i have the feeling it's something about it.



Yes to 1. Yes to 2. Yes to 3. Yes

**Comment by maisonlam90** [comment]
same issue, GMA disappeared when create google ads account

**Comment by jsdupuis** [comment]
@sdzhepa what is the next step now? I'm not familiar with the github process.

**Comment by MagentoChannels** [comment]
Hello, we've found a bug in the Google Shopping ads extension that removes the user from the GMC account created during onboarding shortly after the onboard process is complete. This prevents the user from claiming & verifying their account, and running ad campaigns. We will be releasing a fix to address this issue as soon as we can, and I will update this thread once we have an ETA on the fix. We know this is inconvenient and we apologize for the difficulty.

**Comment by Marineimpulseo** [comment]
@MagentoChannels Sorry to disturb you. Could you tell me approximatively how long it could takes please ? Depending on the answer, I will find another solution to use shopping.
Many thanks

**Comment by javiersnipe** [comment]
Hello everybody, I had exactly the same problem. I contacted Google to recover access to my GMC account. (Contacted Google from contact form they offer in Google ads.) Then they asked some details about the account to be sure that it was mine. After that, once I replied Google email and gave them all the details they asked me they gave me access again to the account.

**Comment by jsdupuis** [comment]
> Hello everybody, I had exactly the same problem. I contacted Google to recover access to my GMC account. (Contacted Google from contact form they offer in Google ads.) Then they asked some details about the account to be sure that it was mine. After that, once I replied Google email and gave them all the details they asked me they gave me access again to the account.

Doesn't work for me. Tried twice. Conversation with Google goes in an endless circle. They keep telling me to create a GMC account outside Magento which I keep repeating them doesn't work with the plugin... :(

**Comment by jmelkun** [comment]
I'm also having the same issue. I just got off the phone with my Adwords rep; they weren't able to help but did provide some interesting nuggets. 

The account is created as a multi-user account by Magento with the user given administrative rights to the account. At any point prior to creating your first campaign, you have access to the Merchant account created by the plugin; you can log into the Merchant account and claim your URL.

Once you claim your URL, Google has a record of the site being registered. When you create the first campaign, the multi-user account drops the end-user as an authorized user on the account and removes the claim to the website. At this point in time, Google has no record of the account ever being affiliated with your URL. Notably, the AdWords account is still active -- the merchant account tied to the account, however, is inaccessible and the claim to the site becomes unverified. As a result, you are unable to advertise on the products loaded into the google ecosystem. Even more frustrating, you are unable to reclaim your merchant account 

I suspect the error is in the campaign payload as it's uploaded since the site is unlinked at that point.

**Comment by emilev79** [comment]
Same issue here. 

As concerned the questions.

    _Did you have an existing GMC account before going through the onboarding process?
    Did you have a Google Ads account before going through the onboarding process?
    Was your website URL claimed by another GMC account before?
    In Stores --> Configuration --> Sales --> Google API --> Google Adwords, were you already using Conversion ID feature?_

Her it is y,y,y and a no. So then also the issue.

**Comment by jsdupuis** [comment]
@sdzhepa @MagentoChannels Could you please give us the courtesy of an update on this issue?

**Comment by iamsteve** [comment]
I can report the same issue - it's not a great workaround but you can stop the onboarding process after the GMC account creation and simply log into the GMC account, manually link it to a new google ads account and set up your own shopping campaigns with the products imported. In an ideal world, you'd want to manage the ads via Magento but at this point in time having any product available to serve on shopping ads is better than running no ads at all if your businesses depend on paid advertising.

**Comment by pictona** [comment]
I can also report the same issue, been through 3 times at least with same result. Can create new GMC account but as soon as you create and link an adwords account, you lose the verified url in the GMC account, rendering the whole thing useless.

@MagentoChannels Could you please give us the courtesy of an update on this issue? 20th December you said would release a fix asap. It's now March :)

**Comment by swell-d** [comment]
Same issue. And one more point. I use multystore and I don't understand how can I use many GMC accounts with only one gmail account.

**Comment by jsdupuis** [comment]
Problem solved. They are discontinuing this extension...
https://docs.magento.com/m2/ee/user_guide/sales-channels/google-ads/google-eol.html

**Comment by sdzhepa** [comment]
Hello, this should probably be closed as we've deprecated the Google Shopping ads Channel, and the [service was shut down ](https://docs.magento.com/user-guide/sales-channels/google-eol.html)as of Apr 28th.
