### ISSUE TITLE
Dupplicate Records when sorting column in Content->Themes Grid

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25925]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. Content->Themes
3. Click Theme Title to sort
4. Click Theme title to sort again
![sort](https://user-images.githubusercontent.com/8234209/70302245-24e8fd80-182f-11ea-8ff3-6c7c231655cd.gif)
=> Dupplicate Records

### Expected result (*)

![image](https://user-images.githubusercontent.com/8234209/70302388-88732b00-182f-11ea-862e-2ab64b0a4eed.png)

### Actual result (*)

=> Dupplicate Records

![image](https://user-images.githubusercontent.com/8234209/70302279-3e8a4500-182f-11ea-940b-aed6efad3349.png)

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-25925-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25925-2-4-develop.instances.magento-community.engineering/admin](https://i-25925-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29490` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#25926 by @edenduong in 2.4-develop branch
Related commit(s):
 - [fa2ed5347963585c3f8c8f639511fdf25a28df24](https://github.com/magento/magento2/commit/fa2ed5347963585c3f8c8f639511fdf25a28df24)
 - [1a285eac193762b3c11123ac9600d22ec1ac300a](https://github.com/magento/magento2/commit/1a285eac193762b3c11123ac9600d22ec1ac300a)
 - [7cd10625d1208c4599e711bbbba4b50edca4f953](https://github.com/magento/magento2/commit/7cd10625d1208c4599e711bbbba4b50edca4f953)
 - [05c84c29df8a2054a7aa04471696a884861acc21](https://github.com/magento/magento2/commit/05c84c29df8a2054a7aa04471696a884861acc21)

The fix will be available with the upcoming 2.4.0 release.
