### ISSUE TITLE
Refresh Statistics: Updated At = Null should be display as "Never" instead of "undefined".

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25931]
Updated At if Null should be display as "Never" instead of "undefined".

Please see the index management:

![image](https://user-images.githubusercontent.com/8234209/70313555-6cc84e80-1848-11ea-833d-97f56c4b382a.png)

**But:**

In refresh statistics:

![image](https://user-images.githubusercontent.com/8234209/70313718-b2851700-1848-11ea-9669-76e7f7dcf23f.png)

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. Reports-> Refresh Statistics
3. Please see:

![image](https://user-images.githubusercontent.com/8234209/70313764-cd578b80-1848-11ea-880f-79f43d066566.png)

### Expected result (*)

![image](https://user-images.githubusercontent.com/8234209/70313949-1c9dbc00-1849-11ea-93f6-9e279c30ca63.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/70313786-d8aab700-1848-11ea-9db6-42696383066f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29494` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#25932 by @edenduong in 2.4-develop branch
Related commit(s):
 - [b92aef02958c7820d2d4e9456eb22f3cebba107d](https://github.com/magento/magento2/commit/b92aef02958c7820d2d4e9456eb22f3cebba107d)
 - [f33199f77fe16beb22478dd9773035185b576a0d](https://github.com/magento/magento2/commit/f33199f77fe16beb22478dd9773035185b576a0d)
 - [2d0c917f48e5aa0d4b9e461834f9d4d147e53000](https://github.com/magento/magento2/commit/2d0c917f48e5aa0d4b9e461834f9d4d147e53000)
 - [a0b7436f96ca25ab320c3ed7b664b0a24a96979c](https://github.com/magento/magento2/commit/a0b7436f96ca25ab320c3ed7b664b0a24a96979c)

The fix will be available with the upcoming 2.4.0 release.
