### ISSUE TITLE
Grid Export rendered data is not reflecting in the exported File, Displayed ID instead of Rendered Label

### ISSUE THREAD

**Issue by koushikch7** [magento/magento2#25963]
### Preconditions
[Verified](https://chkoushik.com/) in Magento 2.3.2 and 2.3.3 and found that the data displayed in the grid by rendering columns is not reflecting in the Exported file, Instead, we are getting Id of the data rather than grid value.
Verified in the environments,
1. Magento 2.3.2 and Magento 2.3.3 & 2.4-develop
2. Apache and Nginx
3. Mysql and MongoDB

### Steps to reproduce
1. Log in to the Magento Admin
2. Choose any grid having an export option. In my case, I choose for Sales Order Grid.
3. Click on Export using CSV/Excel.

### Expected result
CSV/Excel sheet that contains all the details with values as displayed in the grid
e.g.:
![image](https://user-images.githubusercontent.com/51680850/70727807-fb394600-1d08-11ea-8a48-57f0a4ee1f5d.png)

### Actual result
CSV/Excel sheet that contains Columns with ID rathe than values displayed as in the grid
![export](https://user-images.githubusercontent.com/35527481/70498751-70582000-1b3d-11ea-8f7d-4ea14561e5c3.jpg)

**Comment by tuyennn** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tuyennn, here is your [Magento instance](https://i-25963-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25963-2-4-develop.instances.magento-community.engineering/admin](https://i-25963-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29734` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by koushikch7** [comment]
@konarshankar07  This issue is not only for the Customer group grid, but also for the all grids (Default and Custom) which need fixed globally not like everywhere i think.

**Comment by koushikch7** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @koushikch7. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @koushikch7, here is your [Magento instance](https://i-25963-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25963-2-4-develop.instances.magento-community.engineering/admin](https://i-25963-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by koushikch7** [comment]
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment]
Hi @koushikch7. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment]
Hi @koushikch7, here is your [Magento instance](https://i-25963-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-25963-2-3-2.instances.magento-community.engineering/admin_cc6b](https://i-25963-2-3-2.instances.magento-community.engineering/admin_cc6b)
Login: `c3da96b8` Password: `34e7a9268dff`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @koushikch7. Thank you for your report. 
The issue has been fixed in magento/magento2#26523 by @novikor in 2.4-develop branch
Related commit(s):
 - [b43980b94cdd208ee80e0e2cc9fc302469d96439](https://github.com/magento/magento2/commit/b43980b94cdd208ee80e0e2cc9fc302469d96439)
 - [93793d8af1c0de796df340beb9f8707a941e28f1](https://github.com/magento/magento2/commit/93793d8af1c0de796df340beb9f8707a941e28f1)
 - [c517f5f75c64c89dd46d639980f94cfc3e3f158b](https://github.com/magento/magento2/commit/c517f5f75c64c89dd46d639980f94cfc3e3f158b)
 - [9bb416f4c625af4b9059d994fed3a74d1f6b9340](https://github.com/magento/magento2/commit/9bb416f4c625af4b9059d994fed3a74d1f6b9340)
 - [cd24e419741b7834d2012be7c039fd01e57e82e7](https://github.com/magento/magento2/commit/cd24e419741b7834d2012be7c039fd01e57e82e7)
 - [6b434ba7a4cc581cb2e83f183959a7c7e0a98430](https://github.com/magento/magento2/commit/6b434ba7a4cc581cb2e83f183959a7c7e0a98430)
 - [b117b0c9cba0e7664ce3961600acf992cb55a55a](https://github.com/magento/magento2/commit/b117b0c9cba0e7664ce3961600acf992cb55a55a)
 - [4a78ca5d3270009fe79e74431263e96acd7e8c83](https://github.com/magento/magento2/commit/4a78ca5d3270009fe79e74431263e96acd7e8c83)
 - [34d1876492ec4fd7eb509434e2eed15da26740dc](https://github.com/magento/magento2/commit/34d1876492ec4fd7eb509434e2eed15da26740dc)
 - [448391132c1dc050f335d4a445b52a92cf918c27](https://github.com/magento/magento2/commit/448391132c1dc050f335d4a445b52a92cf918c27)
 - [0d3e4783b4f4477dc323df770d22338c9525c4f1](https://github.com/magento/magento2/commit/0d3e4783b4f4477dc323df770d22338c9525c4f1)
 - [1a1ab4dea69380349335bc405adbd58838955a56](https://github.com/magento/magento2/commit/1a1ab4dea69380349335bc405adbd58838955a56)
 - [5849cb68b782481db0f3a14c400f53d10e2fde78](https://github.com/magento/magento2/commit/5849cb68b782481db0f3a14c400f53d10e2fde78)

The fix will be available with the upcoming 2.4.0 release.
