### ISSUE TITLE
Notice: Array to string conversion Magento/CatalogSearch/Model/Layer/Filter/Attribute.php in catalog by filter by boolean option

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#25967]
### Preconditions (*)

1. Magento 2.4-dev

### Steps to reproduce (*)

1. Go to frontend -> Men -> Tops -> Hoodies & Sweatshirts
2. Choose Sales from Nav filter -> Yes

### Expected result (*)

1. Will be found products that being in sale(attribute value = 1, sales)

### Actual result (*)

1. exception Notice: Array to string conversion in /app/code/Magento/CatalogSearch/Model/Layer/Filter/Attribute.php on line 72

**Comment by sdzhepa** [comment]
Hello @tuyennn 

I cannot reproduce this issue by provided steps on the lates `2.4-develop` branch with sample data
Probably the issue the bug is already fixed and we can close this issue
Or some steps/preconditions are missed

I followed steps from the description and after checked system.log and exception.log. - there is no any errors or notices or warnings


![issue_25967](https://user-images.githubusercontent.com/3409584/81208719-1d23b580-8f95-11ea-8ad7-f2b082ca2147.gif)

**Comment by tuyennn** [comment]
@sdzhepa looks good, seem it was fixed on latest version
