### ISSUE TITLE
Amount of characters on a 'Area' Customizable Option counted differently on backend/frontend

### ISSUE THREAD

**Issue by hans-vereyken** [magento/magento2#25974]
### Preconditions (*)

1. Vagrant box, Debian 9
2. Magento 2.2.9
3. Chrome 78
4. Create a virtual product with Customizable Options:
- Option Title: Message
- Option Type: Area
- Max Characters: 20
- Don't forget to add a price and stock

### Steps to reproduce (*)

1. Try to put this product in your basket with a message 'Is twenty characters' => OK on front and can add to cart.
2. Try to put this product in your basket with a message with a newline:
'Is
twenty
characters'
=> Ok on front, but error on adding to cart: 'The text is too long.'

### Expected result (*)

1. If the Javascript validator validates the input, it should be valid on server-side as well.

### Actual result (*)

1. Error shown although the Javascript validator passed.

### Summary
The Javascript validator counts newlines as a single character (\n).
On the server side (\Magento\Catalog\Model\Product\Option\Type\maxCharacters) newlines are counted as 2 characters (\r\n).

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-25974-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25974-2-4-develop.instances.magento-community.engineering/admin](https://i-25974-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
The issue verified after following the same steps.
See attached the video:

![1](https://user-images.githubusercontent.com/24711761/70593806-6816e800-1c04-11ea-8770-44d678a44c94.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29644` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @hans-vereyken. Thank you for your report. 
The issue has been fixed in magento/magento2#26033 by @Leone in 2.4-develop branch
Related commit(s):
 - [284e3edc3b97fb05c9f01b3e9932a542551fec87](https://github.com/magento/magento2/commit/284e3edc3b97fb05c9f01b3e9932a542551fec87)
 - [2ae68386fc04fda7bb6ca9748277e81983732610](https://github.com/magento/magento2/commit/2ae68386fc04fda7bb6ca9748277e81983732610)
 - [d2a4865fee168c7b0e143346609f729b13e1c8bc](https://github.com/magento/magento2/commit/d2a4865fee168c7b0e143346609f729b13e1c8bc)
 - [6e68a470c5ed94ba4f1cd9a031fc81e5b99907fd](https://github.com/magento/magento2/commit/6e68a470c5ed94ba4f1cd9a031fc81e5b99907fd)

The fix will be available with the upcoming 2.4.0 release.
