### ISSUE TITLE
Admin attributes Advanced Attribute Properties icon doesn't change while collapsing block

### ISSUE THREAD

**Issue by SyntaxKay** [magento/magento2#26022]
### Preconditions (*)

1.Magento 2.3.3

### Steps to reproduce (*)

1.Login to admin
2.Store -> Attributes -> products -> properties -> Advanced attribute properties
3.check the icon of  Advanced attribute properties block

### Expected result (*)

1. ![expected](https://user-images.githubusercontent.com/33230237/70788686-6b9ea080-1db7-11ea-98ef-ee33705c05f9.png)

### Actual result (*)

1. ![actual](https://user-images.githubusercontent.com/33230237/70788707-778a6280-1db7-11ea-8679-76a993a59eab.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29751` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @speedy008. Thank you for your report. 
The issue has been fixed in magento/magento2#28032 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [d7cf1881141fd855ff79f611a31ea2570726bdc3](https://github.com/magento/magento2/commit/d7cf1881141fd855ff79f611a31ea2570726bdc3)
 - [77a4e8c44e1ee901d77aa8d6680fcd5365cd376d](https://github.com/magento/magento2/commit/77a4e8c44e1ee901d77aa8d6680fcd5365cd376d)
 - [6b8fc4c55272229164fde82ddbd631f771f302d7](https://github.com/magento/magento2/commit/6b8fc4c55272229164fde82ddbd631f771f302d7)
 - [facbe37f9f51eb315bc5da1fb3c5000d743057ff](https://github.com/magento/magento2/commit/facbe37f9f51eb315bc5da1fb3c5000d743057ff)
 - [1ef8a517089ff132a7bb526194999ae83247ce50](https://github.com/magento/magento2/commit/1ef8a517089ff132a7bb526194999ae83247ce50)
 - [6e8190662497a8e248c05d92b8763886637be5f3](https://github.com/magento/magento2/commit/6e8190662497a8e248c05d92b8763886637be5f3)
 - [03a2908769ad60c5cd5b1a5262aeab092417fe6a](https://github.com/magento/magento2/commit/03a2908769ad60c5cd5b1a5262aeab092417fe6a)
 - [8c0eff01d09dbea47a3af3afbd0f75bae2a89c82](https://github.com/magento/magento2/commit/8c0eff01d09dbea47a3af3afbd0f75bae2a89c82)
 - [0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41](https://github.com/magento/magento2/commit/0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41)
 - [63550be4ba9097cb1ceac4cc787632d330ec0ea1](https://github.com/magento/magento2/commit/63550be4ba9097cb1ceac4cc787632d330ec0ea1)
 - [321f5c1aed364f72eed6e5e08696f88f4ceabcac](https://github.com/magento/magento2/commit/321f5c1aed364f72eed6e5e08696f88f4ceabcac)
 - [13fe206df162eb2e9f807659899bbe2462142d51](https://github.com/magento/magento2/commit/13fe206df162eb2e9f807659899bbe2462142d51)
 - [aae2b7f2073dd171fa12388348bef1a37e389c46](https://github.com/magento/magento2/commit/aae2b7f2073dd171fa12388348bef1a37e389c46)
 - [2c8839699612fa67db10ba795f5357dbc42756f5](https://github.com/magento/magento2/commit/2c8839699612fa67db10ba795f5357dbc42756f5)
 - [cfec001044286e96650d4f50ce906fc95bfc5d57](https://github.com/magento/magento2/commit/cfec001044286e96650d4f50ce906fc95bfc5d57)

The fix will be available with the upcoming 2.4.0 release.
