### ISSUE TITLE
JsFooterPlugin sets Http Response content empty if PCRE limit reached

### ISSUE THREAD

**Issue by cundd** [magento/magento2#26026]
### Preconditions (*)
1. Magento 2.3.2-p2
2. PHP 7.1
3. pcre.backtrack_limit = 1000000 (Default)
4. pcre.recursion_limit = 1000000 (Default)
5. dev/js/move_script_to_bottom=enabled

### Steps to reproduce (*)
1. Build a huge HTML output (e.g. shopping cart with a lot of complex products)

### Expected result (*)
1. Output should be turned or error should be thrown

### Actual result (*)
1. A HTTP status code 200 without a response body is returned

The call to `preg_replace_callback()` in [`JsFooterPlugin`](https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Theme/Controller/Result/JsFooterPlugin.php#L51) will fail silently, resulting in a blank page. The reason for this is, that `preg_replace_callback()` will return `NULL` if one of it's limits is reached. `NULL` will further be used to set the content of the HTTP response.

A first step would be to check if the result of `preg_replace_callback()` is `NULL` and throw an appropriate exception (generated from `preg_last_error()`).

**Comment by cundd** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @cundd. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cundd, here is your [Magento instance](https://i-26026-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26026-2-4-develop.instances.magento-community.engineering/admin](https://i-26026-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cundd** [comment]
I couldn't manage to reproduce it with the admin access only, but fixing this would more be a general improvement to the Magento framework, rather than an immediate fix for a bug.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29768` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @cundd. Thank you for your report. 
The issue has been fixed in magento/magento2#27270 by @krzksz in 2.4-develop branch
Related commit(s):
 - [31eeaa7b5b18d27fc786660d23faaba6ff0393d1](https://github.com/magento/magento2/commit/31eeaa7b5b18d27fc786660d23faaba6ff0393d1)
 - [4fa54472bab13709e6f320fea97bdc94f330bcfd](https://github.com/magento/magento2/commit/4fa54472bab13709e6f320fea97bdc94f330bcfd)
 - [08f2bd4b92603363d8cd5f2ca4ffbbbdd454b6e9](https://github.com/magento/magento2/commit/08f2bd4b92603363d8cd5f2ca4ffbbbdd454b6e9)
 - [2c5bc50da87ac7a6471dc36759f37bf817a39e06](https://github.com/magento/magento2/commit/2c5bc50da87ac7a6471dc36759f37bf817a39e06)
 - [27805df2d2d61bb2290123ad6bdf8e1b0939e42a](https://github.com/magento/magento2/commit/27805df2d2d61bb2290123ad6bdf8e1b0939e42a)
 - [693507fde3894bbe98b77b4b24740b9503244f9f](https://github.com/magento/magento2/commit/693507fde3894bbe98b77b4b24740b9503244f9f)
 - [31b045682218f127a6239de1ff8bafd9b4dde4df](https://github.com/magento/magento2/commit/31b045682218f127a6239de1ff8bafd9b4dde4df)
 - [b54ce80fa8845358d9f8c7ddc76a4f076e885e62](https://github.com/magento/magento2/commit/b54ce80fa8845358d9f8c7ddc76a4f076e885e62)
 - [036f99fd1e6996724d9d91af19e9ff2edb0bb9ca](https://github.com/magento/magento2/commit/036f99fd1e6996724d9d91af19e9ff2edb0bb9ca)
 - [9687370475af12abea586dd94bfb1ede3800acb2](https://github.com/magento/magento2/commit/9687370475af12abea586dd94bfb1ede3800acb2)
 - [e38b1a116daf637bb212e8c60603e940bac7a642](https://github.com/magento/magento2/commit/e38b1a116daf637bb212e8c60603e940bac7a642)
 - [1b780be6c1d75cce024446e33446ef4b29d3f827](https://github.com/magento/magento2/commit/1b780be6c1d75cce024446e33446ef4b29d3f827)
 - [b7ff624737a78f3a09a8b92ea7a691c621fb1153](https://github.com/magento/magento2/commit/b7ff624737a78f3a09a8b92ea7a691c621fb1153)
 - [ffd392cbf9d61815846f40dec9d5591f579883da](https://github.com/magento/magento2/commit/ffd392cbf9d61815846f40dec9d5591f579883da)
 - [d963abc3173d7425d71d03076f4a681fccf9fbad](https://github.com/magento/magento2/commit/d963abc3173d7425d71d03076f4a681fccf9fbad)
 - [44131f8bc2fed8534995da0e43bfd2310fe78ff8](https://github.com/magento/magento2/commit/44131f8bc2fed8534995da0e43bfd2310fe78ff8)

The fix will be available with the upcoming 2.4.0 release.
