### ISSUE TITLE
Do not duplicate SEO meta data when duplicating a product

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26054]
## Description (*)

When you duplicate a product in the database a new product is created with the SEO data being the same.

99.9999999999999999999999999999999% of the time when you duplicate a product you do it because you want to use the same attributes for the next product, since it is usually a similar product.

What you do **not want** (usually) when duplicating is the same product name, the same SKU, and possibility not the same description or the same URL key as the previous product.

What happens is after you duplicate the product the SEO data stays the same. And unless you click down the hidden header you may forget to update that information, and your new duplicated product will have the same SEO meta data as your old product.

This adds extra useless work to empty this data every time you duplicate a product.

### Expected behavior (*)

A better solution would be to empty that data on duplication and save the new information on save.

Fields to be emptied/not duplicated:

- URL key
- Meta title
- Meta keywords
- Meta description

### Benefits

1. Less work.
1. Less problems.
1. Less duplicate meta tags.
1. Better user experience.
1. Better SEO experience.
1. Better SEO rankings.

### Additional information
When you duplicate a product in the database a new product is created with the SEO data being the same.

If you disagree, please state in what use case you want duplicate SEO content.

**Comment by magento-engcom-team** [comment]
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29793` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#26659 by @dasharath-wagento in 2.4-develop branch
Related commit(s):
 - [1f96b873283229aa6892444244475d9992c0d8f2](https://github.com/magento/magento2/commit/1f96b873283229aa6892444244475d9992c0d8f2)
 - [89b0a9d4edd2380672ee813d812fe8fbf715eb61](https://github.com/magento/magento2/commit/89b0a9d4edd2380672ee813d812fe8fbf715eb61)
 - [99383fcdef11a034118bb44b7f6f35ec3a8ae546](https://github.com/magento/magento2/commit/99383fcdef11a034118bb44b7f6f35ec3a8ae546)
 - [2d19477ebf398f066930ac413e6e4ebec6ce1830](https://github.com/magento/magento2/commit/2d19477ebf398f066930ac413e6e4ebec6ce1830)
 - [5aea4acf70bbf52d5c6f4f2d76e5698f3d8b2fb8](https://github.com/magento/magento2/commit/5aea4acf70bbf52d5c6f4f2d76e5698f3d8b2fb8)
 - [dbf39249c537519dd3d97fd116110c454847e736](https://github.com/magento/magento2/commit/dbf39249c537519dd3d97fd116110c454847e736)

The fix will be available with the upcoming 2.4.0 release.
