### ISSUE TITLE
Get full product details from rest API

### ISSUE THREAD

**Issue by userException** [magento/magento2#2606]
Request : http://localhost/magento2/index.php/rest/V1/categories/24/products

Response : [{"sku":"WH01","position":1,"category_id":"24"},...]

Is there a way to get the full product detail form this API ? I don,t want to access  /V1/products/:sku, for every product.

**Comment by maghamed** [comment]
You can utilize ProductRepositoryInterface and its getList method.
It's accessible through Web API 

```
<route url="/V1/products" method="GET">
        <service class="Magento\Catalog\Api\ProductRepositoryInterface" method="getList"/>
        <resources>
            <resource ref="anonymous" />
        </resources>
    </route>
```

All that you need to do - get the list of product SKUs for which you want to get detailed data and apply them as a filter.

**Comment by choukalos** [comment]
Answered by @maghamed

**Comment by shaibar** [comment]
Hello @maghamed,
I have tried your suggestion but the /products?search does not return all the product info like the /products/:sku i am missing the options, media_gallery_entries, extension_attributes and more
I am using magento v 2.1.2

**Comment by maghamed** [comment]
Hi @shaibar 
You are right, search (and getList method) doesn't return all the set of Extension Attributes.
The same problem we have with Product Collection, which is not extended with all extension attributes for its elements.
So, the only option to load all extension attributes for products - is to retrieve a collection of products (with getList call or using product collection) and iterate over this set with foreach loop calling
$product = ProductRepositoryInterface::get($productId) // this way $product would be fully loaded
because just ProductRepositoryInterface::get guarantees that all ext. attributes would be loaded either one which introduced my Magento either by 3rd party developers

**Comment by Puru2016** [comment]
I also try to get full product information in products collection, currently it showing limited information. Like this: 

```
{
        "entity_id": "3",
        "attribute_set_id": "15",
        "type_id": "simple",
        "sku": "24-MB03",
        "has_options": "0",
        "required_options": "0",
        "created_at": "2019-04-24 08:32:28",
        "updated_at": "2019-04-24 08:55:46",
        "cat_index_position": "0",
        "price": "38.0000",
        "tax_class_id": "2",
        "final_price": "38.0000",
        "minimal_price": "38.0000",
        "min_price": "38.0000",
        "max_price": "38.0000",
        "tier_price": null,
        "news_from_date": "2019-04-23 08:55:00",
        "news_to_date": null
    }
```
there is no product name and product image etc....

If any one have any idea please share with us to get full information in product collection.
