### ISSUE TITLE
Performance of isSalable method check on configurable product

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#26065]
Magneto 2.3.x
### Preconditions (*)

1. Render product listing
2.
Proposal to optimize or replace `getUsedProductCollection` in call
`\Magento\ConfigurableProduct\Model\Product\Type\Configurable::isSalable` since it can affect performance
e.g. create alias for `getUsedProductCollection` -> `getLinkedProductCollection` and use this method in `isSalable` additionally store its result to prevent multiple DB calls.
### Steps to reproduce (*)

1. Render prices on product listing
2. Check if product is saleable

### Expected result (*)

1. plugin `\Magento\Swatches\Model\Plugin\Configurable::afterGetUsedProductCollection` is not called after `isSaleable` call
2. `\Magento\ConfigurableProduct\Model\Product\Type\Configurable::isSalable` stores result since it can be called twice 

### Actual result (*)

1. plugin `\Magento\Swatches\Model\Plugin\Configurable::afterGetUsedProductCollection` is called when **isSaleable** checks 
2. Multiple call of `\Magento\ConfigurableProduct\Model\Product\Type\Configurable::isSalable` affects performance since the result is not cached and `afterGetUsedProductCollection` called

**Comment by slavvka** [comment]
Hi @ilnytskyi. Thank you for your report. 
The issue has been fixed in magento/magento2#26071 by @ilnytskyi in 2.4-develop branch
Related commit(s):
 - [ad5c3e4c76f0bed775e614d38b2c3b3688918a9d](https://github.com/magento/magento2/commit/ad5c3e4c76f0bed775e614d38b2c3b3688918a9d)
 - [87842d3d34e74f6102ec5f39c62fe6e23aa5761e](https://github.com/magento/magento2/commit/87842d3d34e74f6102ec5f39c62fe6e23aa5761e)

The fix will be available with the upcoming 2.4.0 release.
