### ISSUE TITLE
Admin UI Not Working

### ISSUE THREAD

**Issue by MichelSchade** [magento/magento2#26072]
Hey Magento Community,

I have a fresh Install of Magento CE-2.3.3 on nginx Server hosted by Timme Hosting and the UI Elements in the backend are not showing. Themes, Products,

Has someone else had this issue?

### Preconditions (*)
PHP: laut Timme Hosting Server 7.3.1
MySQL: 
nginx/1.14.0
Datenbank-Client Version: libmysql - 10.2.17
PHP-Erweiterung: mysqliDokumentation curlDokumentation mbstringDokumentation
PHP-Version: 5.6.22-2

### Steps to reproduce (*)
Fresh Install of Magento CE-2.3.3

### Expected result (*)
This is how its supposed to be: https://prnt.sc/qa9ud4

### Actual result (*)
This is what is happening: https://prnt.sc/qa9tdz

**Comment by shikhamis11** [comment]
hi @MichelSchade 
This issue seems to be not exist in magento .. It is probably at your server only .. 
try running below commands 
`php bin/magento setup:static-content:deploy`
`php bin/magento setup:di:compile`
`php bin/magento cache:flush`

also Please check your php version [here](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html)
