### ISSUE TITLE
Problem when trying to unset additional data in payment method.

### ISSUE THREAD

**Issue by marcoaacoliveira** [magento/magento2#26083]
### Preconditions (*)
1. Magento 2.3.2 & PHP 7.2.21

### Steps to reproduce (*)
1. You must use \Magento\Payment\Model\Info::setAdditionalInformation to add an additional information to a payment method;
2. Try to use \Magento\Payment\Model\Info::unsAdditionalInformation to remove the inserted additional data.

### Expected result (*)
1. \Magento\Payment\Model\Info::unsAdditionalInformation should remove an additional information from table quote_payment column additional_information after save the quote.

### Actual result (*)
1. \Magento\Payment\Model\Info::unsAdditionalInformation didn't remove the data in additional_information (column)

**Comment by VladimirZaets** [comment]
Hi @marcoaacoliveira. Thank you for your report. 
The issue has been fixed in magento/magento2#26084 by @marcoaacoliveira in 2.4-develop branch
Related commit(s):
 - [13f34cd6e15c0e1ce1b1183761d3ca4bfc318c22](https://github.com/magento/magento2/commit/13f34cd6e15c0e1ce1b1183761d3ca4bfc318c22)
 - [32227d2773836da0574db70fac8aad46ac0dad83](https://github.com/magento/magento2/commit/32227d2773836da0574db70fac8aad46ac0dad83)
 - [77390c18c505f743367f2a8b1eec37514ba7bec3](https://github.com/magento/magento2/commit/77390c18c505f743367f2a8b1eec37514ba7bec3)
 - [ad1059fb9a0abb316a6cb92b62ef9fee546f1f77](https://github.com/magento/magento2/commit/ad1059fb9a0abb316a6cb92b62ef9fee546f1f77)
 - [408b725157f031a81119cb27816d204d48b45b97](https://github.com/magento/magento2/commit/408b725157f031a81119cb27816d204d48b45b97)

The fix will be available with the upcoming 2.4.0 release.
