### ISSUE TITLE
special price & tier price are coming in base currency

### ISSUE THREAD

**Issue by mkum73** [magento/magento2#26121]
In Graphql fetch data for special price & tier prices in products query. The values come always in base currency.
### Preconditions (*)
1. Magento based on '2.4-develop' branch
2. Have a product created with name "Beginner's Yoga" (or refer to the same named product that becomes available with sample data) and set the following prices
    a. price: 6 
    b. Advanced pricing > special price: 5 
    c. Advanced Pricing > Catalog and Tier Price, for all websites and all groups, fixed type price, 
        - for qty 2 price 4
        - for qty 3 price 3 

3. Add new store view with code "eur_view"
4. Navigate to Store -> Settings -> Configuration -> General -> Currency Setup and allow EURO in **Allowed Currencies** and Save Configuration
5.  Change the Scope to the second Eur View and set **Default Display Currency** to Euro
6. Ensure there are currency rates available (e.g. on frontend catalog if the store view is switched price would change from 6 to 4.24 -> indicating that the USD -> EUR rate is 1.415)

### Steps to reproduce (*)

1. Set header "Store = default" and execute this query
`query{
products(search: "Beginner's Yoga"){
  total_count
	items {    
		name
     price_range {
       minimum_price {
         regular_price {
          currency
          value
        }
        final_price {
          currency
          value
        }
      } 
     }
     special_price
     price_tiers {
     	final_price {
        currency
        value
      }
      quantity
     }
		sku
	}
    }
}`

2. Prices now are expected in Default Store view in USD, response should look like
`        {
          "name": "Beginner's Yoga",
          "price_range": {
            "minimum_price": {
              "regular_price": {
                "currency": "USD",
                "value": 6
              },
              "final_price": {
                "currency": "USD",
                "value": 5
              }
            }
          },
          "special_price": 5,
          "price_tiers": [
            {
              "final_price": {
                "currency": "USD",
                "value": 4
              },
              "quantity": 2
            },
            {
              "final_price": {
                "currency": "USD",
                "value": 3
              },
              "quantity": 3
            }
          ],
          "sku": "240-LV04"
        }`

3.  Set header "Store = eur_view" and execute the query again
4. Prices now are expected in Eur View in EUR currency, response should look like
`        {
          "name": "Beginner's Yoga",
          "price_range": {
            "minimum_price": {
              "regular_price": {
                "currency": "EUR",
                "value": 4.24
              },
              "final_price": {
                "currency": "EUR",
                "value": 3.53
              }
            }
          },
          "special_price": 5,
          "price_tiers": [
            {
              "final_price": {
                "currency": "EUR",
                "value": 4
              },
              "quantity": 2
            },
            {
              "final_price": {
                "currency": "EUR",
                "value": 3
              },
              "quantity": 3
            }
          ],
          "sku": "240-LV04"
        }`

Observe how the `regular_price.minimum_price` and `regular_price.final_price` have changed its value, but not the `special_price` or the values respectively for the `price_tiers`

### Expected result (*)
1. `special_price` should display values corrected by the USD->EUR rate (E.g. something like 3.53)
2. `price_tiers.final_price.value` should display values corrected by the USD->EUR rate

### Actual result (*)
1. `special_price` still displays 5
2. `price_tiers.final_price.value` is still displayed in USD and displays 4 for qty 2, and 3 for qty 3

**Comment by sdzhepa** [comment]
Hi @TomashKhamlai 

Could you please help us with additional details about this issue?
- Actual/Expected results
- Example of query

**Comment by magento-engcom-team** [comment]
Hi @mkum73. Thank you for your report. 
The issue has been fixed in magento/magento2#28890 by @pmarjan in 2.4-develop branch
Related commit(s):
 - [5c69aa1bf0fba6306d86f97a7f99b11ec79a269e](https://github.com/magento/magento2/commit/5c69aa1bf0fba6306d86f97a7f99b11ec79a269e)
 - [cce0a99547cb0e597f8e3325fd59574ddc7049f8](https://github.com/magento/magento2/commit/cce0a99547cb0e597f8e3325fd59574ddc7049f8)
 - [89b968ad23feaf0b572bb281ad34d915591c3a9d](https://github.com/magento/magento2/commit/89b968ad23feaf0b572bb281ad34d915591c3a9d)
 - [75f71a47c52272670832ac8d811e9e8d9ac641d7](https://github.com/magento/magento2/commit/75f71a47c52272670832ac8d811e9e8d9ac641d7)
 - [4c5086aeae6fe08f63302e9d004429c35d9e933e](https://github.com/magento/magento2/commit/4c5086aeae6fe08f63302e9d004429c35d9e933e)
 - [9bd5def614faaf40fd86e9064cbe0225b1576501](https://github.com/magento/magento2/commit/9bd5def614faaf40fd86e9064cbe0225b1576501)
 - [7a526e96cf2a506e9634ddad7856c972f605808b](https://github.com/magento/magento2/commit/7a526e96cf2a506e9634ddad7856c972f605808b)
 - [d99ff1b3920625ab155856463e261801c652fa48](https://github.com/magento/magento2/commit/d99ff1b3920625ab155856463e261801c652fa48)
 - [831fb5b47645dc91eaf940114a40c8ae2d19f0ae](https://github.com/magento/magento2/commit/831fb5b47645dc91eaf940114a40c8ae2d19f0ae)
 - [f83763ee3c8e93e1956590bdfc8bd41e6374e588](https://github.com/magento/magento2/commit/f83763ee3c8e93e1956590bdfc8bd41e6374e588)
 - [20cd3d0b64b8cb3ebc3468295109b72b43ed8202](https://github.com/magento/magento2/commit/20cd3d0b64b8cb3ebc3468295109b72b43ed8202)
 - [9d80fa3b65e2d2365522f376b6436bceebe4673c](https://github.com/magento/magento2/commit/9d80fa3b65e2d2365522f376b6436bceebe4673c)

The fix will be available with the upcoming 2.4.1 release.
