### ISSUE TITLE
Coupon code text field not display in proper width in  Internet Explorer/EDGE browser

### ISSUE THREAD

**Issue by hasim32** [magento/magento2#26133]
Coupon code text field not display in proper width in Internet Explorer/EDGE browser

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
Review the coupon code section in IE or Edge browser

### Expected result (*)
It should display same as per chrome/firefox browsers

![image](https://user-images.githubusercontent.com/56119534/71167502-cd10b480-227a-11ea-976b-4806e8c081d7.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/56119534/71167375-9470db00-227a-11ea-92e7-e21c2b52ead1.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29933` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
![2020-06-25_13-10-19](https://user-images.githubusercontent.com/3409584/85775730-ac239300-b6e5-11ea-8700-7f1a510ae61e.jpg)
---

![2020-06-25_13-10-59](https://user-images.githubusercontent.com/3409584/85775767-b47bce00-b6e5-11ea-8252-f4c1187e8dcf.jpg)

**Comment by solwininfotech** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @hasim32. Thank you for your report. 
The issue has been fixed in magento/magento2#30405 by @solwininfotech in 2.4-develop branch
Related commit(s):
 - [a535faa775d861570058fd80f9ff0f34bbd7515b](https://github.com/magento/magento2/commit/a535faa775d861570058fd80f9ff0f34bbd7515b)
 - [a37cf33bc2a02671302f66ededb5085f6e911ea4](https://github.com/magento/magento2/commit/a37cf33bc2a02671302f66ededb5085f6e911ea4)
 - [e8ad9aee3fe307fce2e0c4b0cdd0661567170ae7](https://github.com/magento/magento2/commit/e8ad9aee3fe307fce2e0c4b0cdd0661567170ae7)

The fix will be available with the upcoming 2.4.2 release.
