### ISSUE TITLE
Modal Popup and Custom subTitle erased

### ISSUE THREAD

**Issue by textarea** [magento/magento2#26141]
### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)
1. Create a popup or custom modal with a title and subtitle, then change title with setTitle() method.

### Expected result (*)
1. Subtitle still exists

### Actual result (*)
1. Subtitle get erased

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29962` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @textarea. Thank you for your report. 
The issue has been fixed in magento/magento2#26142 by @textarea in 2.4-develop branch
Related commit(s):
 - [81b580accc3e0c48fb96f668be63680d9f055acd](https://github.com/magento/magento2/commit/81b580accc3e0c48fb96f668be63680d9f055acd)
 - [75b6674a6dbaa6ddce5ca4d11e48e8f787210280](https://github.com/magento/magento2/commit/75b6674a6dbaa6ddce5ca4d11e48e8f787210280)
 - [86023f9deea5be2dc3e846b4a3046fdaf5b9715f](https://github.com/magento/magento2/commit/86023f9deea5be2dc3e846b4a3046fdaf5b9715f)
 - [a1212509c813239ef8ab0236d623414831bbac12](https://github.com/magento/magento2/commit/a1212509c813239ef8ab0236d623414831bbac12)
 - [fcce5b8592f884bec431767d903150137a1a6c6e](https://github.com/magento/magento2/commit/fcce5b8592f884bec431767d903150137a1a6c6e)
 - [c4db9415c1567d1be897662593157f51b8b5f03b](https://github.com/magento/magento2/commit/c4db9415c1567d1be897662593157f51b8b5f03b)
 - [435c3fe27964a15729ecbc2ebbafe04b34412faf](https://github.com/magento/magento2/commit/435c3fe27964a15729ecbc2ebbafe04b34412faf)

The fix will be available with the upcoming 2.4.0 release.
