### ISSUE TITLE
Underline should not display on hover for delete icon at shopping cart Internet explorer browser

### ISSUE THREAD

**Issue by hasim32** [magento/magento2#26164]
Underline should not display on hover for delete icon at shopping cart Internet explorer browser.

### Preconditions (*)
Magento: 2.3.3
Windows IE 11

### Steps to reproduce (*)
- Open site in Internet explorer 11
- Add product to cart
- hover on delete icon

### Expected result (*)
Underline should not display on hover for delete icon as pr Chrome and Firefox

### Actual result (*)
![image](https://user-images.githubusercontent.com/56119534/71357186-c8197100-25aa-11ea-898a-7020d283cf31.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30037` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @hasim32. Thank you for your report. 
The issue has been fixed in magento/magento2#26173 by @divyajyothi5321 in 2.4-develop branch
Related commit(s):
 - [216d2c127c311244f52b5530286b2679488ed033](https://github.com/magento/magento2/commit/216d2c127c311244f52b5530286b2679488ed033)

The fix will be available with the upcoming 2.4.0 release.
