### ISSUE TITLE
Input Checkbox Alignment Issue at checkout page in Safari Browser

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#26168]
### Preconditions (*)

1. Magento2.4

### Steps to reproduce (*)

1. Go to Front end, add any product to Cart.
2. Go to Checkout Page.
3. Fill all the shipping details
4. Then go to Review and payments
5. The checkbox is not aligned properly for the My billing and shipping address are the same.

### Expected result (*)

1. My billing and shipping address input checkbox Should be aligned properly.
2. 
![checkbox-expected](https://user-images.githubusercontent.com/54176640/71401726-b38fb400-2650-11ea-892c-9a8ee4108b1e.png)

### Actual result (*)

1. My billing and shipping address input checkbox is not aligned properly.
2. 
![checkbox_alignment](https://user-images.githubusercontent.com/54176640/71401766-da4dea80-2650-11ea-99a1-b17647d43fa6.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30053` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @divyajyothi5321. Thank you for your report. 
The issue has been fixed in magento/magento2#26169 by @divyajyothi5321 in 2.4-develop branch
Related commit(s):
 - [9882e96dab666d5609e47af52d7130e5c33a7a6c](https://github.com/magento/magento2/commit/9882e96dab666d5609e47af52d7130e5c33a7a6c)

The fix will be available with the upcoming 2.4.0 release.
