### ISSUE TITLE
Footer Newsletter input field width is not identical in Internet Explorer/EDGE browser compared with chrome

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#26176]
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Go to Frontend footer section 
2. The newsletter input field width is not identical in Internet Explorer/Edge Browser

### Expected result (*)

1. Newsletter input field width should identical in all broswers
2.
![search-expected](https://user-images.githubusercontent.com/54176640/71441536-d80a8f80-2727-11ea-8afa-05f0b9dcafd4.png)

### Actual result (*)

1. Newsletter input field is not identical in all broswers
2.
![search-actuval](https://user-images.githubusercontent.com/54176640/71441522-caeda080-2727-11ea-97c2-cd1ca4fc9571.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26176-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26176-2-4-develop.instances.magento-community.engineering/admin](https://i-26176-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30075` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @divyajyothi5321. Thank you for your report. 
The issue has been fixed in magento/magento2#26182 by @divyajyothi5321 in 2.4-develop branch
Related commit(s):
 - [63ec3e575ca3f9621867e891c102a4bd0f55ed5d](https://github.com/magento/magento2/commit/63ec3e575ca3f9621867e891c102a4bd0f55ed5d)
 - [adc7908db1db52171e4ec60ffe0eaad152535230](https://github.com/magento/magento2/commit/adc7908db1db52171e4ec60ffe0eaad152535230)

The fix will be available with the upcoming 2.4.0 release.
