### ISSUE TITLE
Newsletter subscription (opt-in) as guest not working correctly

### ISSUE THREAD

**Issue by Quinten** [magento/magento2#2617]
I have the following settings in my backend under Stores > Configuration > Customers > Newsletter > Subscription Options:
Need to Confirm: Yes
Allow Guest Subscription: Yes

When i subscribe as guest with the form in the footer 2 things go wrong:
1. There is no check wether the email address is already subscribed. Which means i can keep sending emails with confirmation links to the same address.
2 . When i click the confirmation link in the email: i return to the homepage and there is no feedback message. But then only when i fill out the form in the footer again, i'll get 2 messages: "Your subscription has been confirmed." and "Thank you for your subscription."

**Comment by whizkid79** [comment]
Same issue here, but I can't get anyone activated, even by filling out the form again, like described above it is still not working.
I wouldn't call that an improvement, that is a bug to be fixed!

**Comment by homecoded** [comment]
Here is the problem and the solution to this **bug**:

When we enter an new email address (one that is not connected to an extisting subscriber), the subscriber object (`$this`) has no id (`$this->getId(); // null`) yet in `Magento\Newsletter\Model\Subscriber::subscribe`. The verification email is sent out before the subscriber is saved, thus the subscriber id is missing from the verification link. The link does not do anything when you click on it because the verification method in `Magento\Newsletter\Controller\Subscriber\Confirm::execute` rejects the link because of the missing id. 

You can easily mend the problem by calling `$this->save()` before calling `$this->sendConfirmationRequestEmail();`

**Comment by mazhalai** [comment]
@homecoded would you like to submit a PR with this fix?

**Comment by homecoded** [comment]
Sure, will take a few days as i have a lot on my plate right now. Can take care of it maybe on Friday or early next week. I wouldn't mind If somebody else wants to jump in.

```
        try {
            $this->save();
            if ($isConfirmNeed === true
                && $isOwnSubscribes === false
            ) {
                $this->sendConfirmationRequestEmail();
            } else {
                $this->sendConfirmationSuccessEmail();
            }
            return $this->getStatus();
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage());
        }
```

This is the last part of my version of the `subscribe`method. I simply moved the ''save'''-call a few lines up. `sendConfirmationRequestEmail`and `sendConfirmationSuccessEmail` do not seem to alter the `$this`object, so this is a valid change that does not break anything else.

**Comment by whizkid79** [comment]
Hi @mazhalai,
I'm a collegue of @homecoded and took the freedom to create the PR. Home that helps.
Peter

**Comment by Quinten** [comment]
Super! I will try out the patch.

**Comment by homecoded** [comment]
Thanks for picking this up @whizkid79 !!

**Comment by whizkid79** [comment]
Hi @vzabaznov,
would be nice to know if and when this issue will be fixed.
Thanks,
Peter
