### ISSUE TITLE
Out of stock text is not aligned properly with add to cart button at list page in responsive  

### ISSUE THREAD

**Issue by divyajyothi5321** [magento/magento2#26181]
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Go to Frond end and product listing page
2. In mobile view the out of stock text and add links are misaligned compared with add to cart button

### Expected result (*)

1. The out of stock text and add links should be aligned with add to cart button in all screens
2.
![outofstok-expected](https://user-images.githubusercontent.com/54176640/71468721-01412380-27ed-11ea-9bac-639c41b0fa88.png)

### Actual result (*)

1. The out of stock text and add links are not aligned compared with add to cart button
2.
![outofstok-actuval](https://user-images.githubusercontent.com/54176640/71468727-0aca8b80-27ed-11ea-92e2-8cd276464077.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30078` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @divyajyothi5321. Thank you for your report. 
The issue has been fixed in magento/magento2#26183 by @divyajyothi5321 in 2.4-develop branch
Related commit(s):
 - [e520c8b45ee5aaea9d19e3e48bc85bf65a6b871d](https://github.com/magento/magento2/commit/e520c8b45ee5aaea9d19e3e48bc85bf65a6b871d)
 - [aaf147837c1da4fcd5229236387bc46d4c44319d](https://github.com/magento/magento2/commit/aaf147837c1da4fcd5229236387bc46d4c44319d)
 - [b87672a94535a9cb5c7cec3f6cc522aec9f5505b](https://github.com/magento/magento2/commit/b87672a94535a9cb5c7cec3f6cc522aec9f5505b)
 - [7117ac4e49df34d04a149d591c49f51d029beb1e](https://github.com/magento/magento2/commit/7117ac4e49df34d04a149d591c49f51d029beb1e)
 - [135df0bc846d06ae00758fb86fb36cf54c852820](https://github.com/magento/magento2/commit/135df0bc846d06ae00758fb86fb36cf54c852820)
 - [6a7179a7f7b1ec7d80dfe124477dc2c967d516ae](https://github.com/magento/magento2/commit/6a7179a7f7b1ec7d80dfe124477dc2c967d516ae)
 - [4c545f23dd44026a87ab001e8294075cc98b1fea](https://github.com/magento/magento2/commit/4c545f23dd44026a87ab001e8294075cc98b1fea)
 - [3a7ec0d71b080c221e9212863bf0efe407336465](https://github.com/magento/magento2/commit/3a7ec0d71b080c221e9212863bf0efe407336465)

The fix will be available with the upcoming 2.4.0 release.
