### ISSUE TITLE
Need To Change Label In Totals Block in Order View Page

### ISSUE THREAD

**Issue by nit-it** [magento/magento2#26191]
After Place, the order, Create an Invoice Of some items. After that Cancel, the order, Total of Cancel items display as Total Due. 

### Preconditions (*)

Magento 2.3.3

### Steps to reproduce (*)
1. Place Order with 5 Items.
2. Now Create Invoice For 1st 3 Items.
3. Cancel Order.

### Expected result (*)
1. If Order Cancel, then Change the label of Total Due.

### Actual result (*)
1. If Order Canceled, Then need to Change the label  "Total Cancel" instead of "Total Due".

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26191-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26191-2-4-develop.instances.magento-community.engineering/admin](https://i-26191-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@nit-it - Your point is good but this is an improvement, not an issue.
Now, this issue is confirmed.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30118` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @nit-it. Thank you for your report. 
The issue has been fixed in magento/magento2#27516 by @madhurajawat in 2.4-develop branch
Related commit(s):
 - [d3021f9c1ceeebc0c560598d0af10cf11567043c](https://github.com/magento/magento2/commit/d3021f9c1ceeebc0c560598d0af10cf11567043c)
 - [012821a975ff2b1ceafbb1c5aebd2d14449956ef](https://github.com/magento/magento2/commit/012821a975ff2b1ceafbb1c5aebd2d14449956ef)
 - [8c2159c13e6dbc6a91e3ccaffdab273b04de0876](https://github.com/magento/magento2/commit/8c2159c13e6dbc6a91e3ccaffdab273b04de0876)
 - [6eae7769566d9cb2b34bbe1d58b803d8d458db4e](https://github.com/magento/magento2/commit/6eae7769566d9cb2b34bbe1d58b803d8d458db4e)
 - [02acf226c490d564bb84ecbf739e680c326634ca](https://github.com/magento/magento2/commit/02acf226c490d564bb84ecbf739e680c326634ca)
 - [7986ed6d47106b3482f783a4ab3e6df3337c02a7](https://github.com/magento/magento2/commit/7986ed6d47106b3482f783a4ab3e6df3337c02a7)
 - [f9d9f8d55e4bb14ac3e2dcb9becf6330f9bcf7fd](https://github.com/magento/magento2/commit/f9d9f8d55e4bb14ac3e2dcb9becf6330f9bcf7fd)
 - [017102b127e7656b059580fcbaf349085e827d13](https://github.com/magento/magento2/commit/017102b127e7656b059580fcbaf349085e827d13)
 - [8d952c3c21ef10e6865b926fb01503584bcd4135](https://github.com/magento/magento2/commit/8d952c3c21ef10e6865b926fb01503584bcd4135)
 - [4e7d5306e759939e3ac817a7f4d5a71bc681490b](https://github.com/magento/magento2/commit/4e7d5306e759939e3ac817a7f4d5a71bc681490b)
 - [8f73ab2c1775f36f2aef92378c4dc2d98bb0c9ae](https://github.com/magento/magento2/commit/8f73ab2c1775f36f2aef92378c4dc2d98bb0c9ae)
 - [1619403ce4a5c88225cd4c56e2d5c7ddc6efa1ef](https://github.com/magento/magento2/commit/1619403ce4a5c88225cd4c56e2d5c7ddc6efa1ef)
 - [18cc4918636bdc5df8fb38822d3bb78a3e73c031](https://github.com/magento/magento2/commit/18cc4918636bdc5df8fb38822d3bb78a3e73c031)
 - [474232a8d7614bda86d0bf2f84f1a5c04cb41b80](https://github.com/magento/magento2/commit/474232a8d7614bda86d0bf2f84f1a5c04cb41b80)
 - [79e1eb042b7a98f286c7528bfe1f44f07df3ffea](https://github.com/magento/magento2/commit/79e1eb042b7a98f286c7528bfe1f44f07df3ffea)
 - [54356340998b355e0d3821a827ba81cd2df63e1f](https://github.com/magento/magento2/commit/54356340998b355e0d3821a827ba81cd2df63e1f)
 - [d3dfc52c5d01ac4c849b3a3a2ccda6bc0a9bdef2](https://github.com/magento/magento2/commit/d3dfc52c5d01ac4c849b3a3a2ccda6bc0a9bdef2)

The fix will be available with the upcoming 2.4.1 release.
