### ISSUE TITLE
Missing information about currently reindexed index on failure

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26206]
### Summary (*)
When reindex fails, you have no information which indexer failed.

### Examples (*)
![image](https://user-images.githubusercontent.com/1639941/71579245-06a7b200-2afc-11ea-9c50-56eef292e700.png)

### Proposed solution
Output the indexer name without a newline, then the time it took.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30192` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#26207 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [1ca03a336588fded3f516b8d7ffe57f8201f718a](https://github.com/magento/magento2/commit/1ca03a336588fded3f516b8d7ffe57f8201f718a)
 - [79fe786afcc193a6424e5d2d31e8120a06d8700b](https://github.com/magento/magento2/commit/79fe786afcc193a6424e5d2d31e8120a06d8700b)
 - [84b131070043a4ad47f8bfa7a4999c42ed9940ba](https://github.com/magento/magento2/commit/84b131070043a4ad47f8bfa7a4999c42ed9940ba)
 - [80684d725413f93744b37c33b02301506a394110](https://github.com/magento/magento2/commit/80684d725413f93744b37c33b02301506a394110)
 - [5bdadc0db8dbf3e7510d64f0a65f610ca3550f09](https://github.com/magento/magento2/commit/5bdadc0db8dbf3e7510d64f0a65f610ca3550f09)

The fix will be available with the upcoming 2.4.0 release.
