### ISSUE TITLE
If an exception is occured during a model saving then the model is questionable left in the serialized state (_serializeFields is called, but unserializeFields is not called)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2620]
https://mage2.pro/t/283

**Comment by shiftedreality** [comment]
Hi, @dfediuk 

Thanks you for reporting. Created internal ticket MAGETWO-47887 for investigating

**Comment by dsikkema-magento** [comment]
@dfediuk object in memory will be left in serialized state, exception will be caught and re-thrown, and persistent storage will not be corrupted. Is that correct? Can you elaborate on the harm from not calling unserializeFields?

**Comment by dsikkema-magento** [comment]
Closing for now, please re-open if you find any reasons why the current approach is unsafe.

**Comment by pixiejohn** [comment]
We appear to have found a real-world case showing why leaving the model in its serialized state after a failed save can cause persistent data corruption.

Environment:

- Magento 2.4.8
- Adyen module-payment 10.10.3

We have now seen this on two separate orders.

In both cases, the save of sales_order_payment failed with:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock

The failed query was an UPDATE against sales_order_payment, including the additional_information field.

We traced the Magento save path in Magento\Framework\Model\ResourceModel\Db\AbstractDb:

    _serializeFields($object)
    ...
    updateObject($object)
    ...
    unserializeFields($object)

If updateObject() throws the deadlock exception, execution goes directly to the catch block:

    rollBack()
    setHasDataChanges(true)
    throw $e

There is no call to unserializeFields($object) in the exception path.

This means the in-memory payment object remains with additional_information in its serialized JSON string form after the failed save.

In both affected cases we subsequently found sales_order_payment.additional_information stored as double-encoded JSON, for example:

    "{\"shopper_conversion_id\":...}"

rather than:

    {"shopper_conversion_id":...}

We also checked the data before this stage:

- quote_payment.additional_information was valid JSON with JSON_TYPE = OBJECT
- the Adyen stored payment response was valid JSON with JSON_TYPE = OBJECT
- the corruption only appeared in sales_order_payment
- manually applying JSON_UNQUOTE() to the affected additional_information value restored the order and allowed Magento to load it normally

So we have strong evidence that the failed save leaves the payment model in a state where a subsequent reuse/save can cause the already-serialized JSON string to be serialized again and persisted.

What we have NOT yet determined is what causes the MySQL deadlock itself, or exactly which code path subsequently retries/reuses the same payment object. There are third-party modules involved in the checkout/payment flow, so we are continuing to investigate that separately.

However, irrespective of the original cause of the deadlock, AbstractDb leaving the model serialized after an exception appears to make the subsequent persistent corruption possible.

This seems to demonstrate the practical risk originally raised in this issue.
