### ISSUE TITLE
Need some space between input and update button Minicart

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#26227]
### Summary

Need some space between input and update button in Minicart

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Add any product in cart
2. Click on input in Minicart
3. Add Qty you will see the update button

### Expected result

1. Need some space between input and update button in Minicart like in mobile view.
![expected](https://user-images.githubusercontent.com/23443991/71654279-e0318300-2d56-11ea-9852-245548a63b6f.png)

### Actual result

1. No space between input and update button in Minicart
![actual](https://user-images.githubusercontent.com/23443991/71654278-e0318300-2d56-11ea-97fa-7a96e4dd5e4e.png)

**Comment by hitesh-wagento** [comment]
I am working on this issue

**Comment by dmytro-ch** [comment]
Hello @hitesh-wagento, the minor improvements do not require a separate issue to be created.
Feel free to create a PR only.
Thank you!

**Comment by VladimirZaets** [comment]
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26234 by @hitesh-wagento in 2.4-develop branch
Related commit(s):
 - [69f6da07a6443eddd099f7f53ebc52bf3f7f2ba0](https://github.com/magento/magento2/commit/69f6da07a6443eddd099f7f53ebc52bf3f7f2ba0)
 - [7e5e6c773712359e303f4b4ee1ebc1b2fb8b85af](https://github.com/magento/magento2/commit/7e5e6c773712359e303f4b4ee1ebc1b2fb8b85af)

The fix will be available with the upcoming 2.4.0 release.
