### ISSUE TITLE
Active menu is not set when opening admin path Marketing > User Content > Pending Reviews

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#26229]
### Preconditions (*)

1. Magento version 2.3.3

### Steps to reproduce (*)

1. Go to admin path Marketing > User Content > Pending Reviews and you will notice that no menu item is activated in the admin primary menu

### Expected result (*)

1. Marketing/Pending Reviews menu item show be shown as active

![Pending Reviews-active](https://user-images.githubusercontent.com/5336201/71656951-8e432a00-2d63-11ea-903b-00d2cf6c6a01.png)

### Actual result (*)

1. No menu item is activated

![Pending Reviews-not-active](https://user-images.githubusercontent.com/5336201/71657041-0e698f80-2d64-11ea-804a-be2ca96f8408.png)

**Comment by rav-redchamps** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rav-redchamps. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rav-redchamps, here is your [Magento instance](https://i-26229-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26229-2-4-develop.instances.magento-community.engineering/admin](https://i-26229-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30159` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rav-redchamps** [comment]
The pull request https://github.com/magento/magento2/pull/26230 for the issue has been created. Hopefully, it will be processed soon.

**Comment by dmytro-ch** [comment]
Hi @rav-redchamps, thank for your report.
Feel free to create the pull requests for minor fixes and obvious improvements without opening the issues.

Thank you!

**Comment by rav-redchamps** [comment]
@dmytro-ch Sure will create pull request directly for further minor fixes and obvious improvements.

**Comment by magento-engcom-team** [comment]
Hi @rav-redchamps. Thank you for your report. 
The issue has been fixed in magento/magento2#26230 by @rav-redchamps in 2.4-develop branch
Related commit(s):
 - [dca6730db6836614aea42d945a025a3e3fec461b](https://github.com/magento/magento2/commit/dca6730db6836614aea42d945a025a3e3fec461b)
 - [d5cb185e61b3cc3c49ccbdab9c412c5fe43b5036](https://github.com/magento/magento2/commit/d5cb185e61b3cc3c49ccbdab9c412c5fe43b5036)
 - [c8b80d0ddf9ab92613e588b9a081383462635d6c](https://github.com/magento/magento2/commit/c8b80d0ddf9ab92613e588b9a081383462635d6c)
 - [5898776d62e5948bbfee00ce9e2850dec01e09a6](https://github.com/magento/magento2/commit/5898776d62e5948bbfee00ce9e2850dec01e09a6)

The fix will be available with the upcoming 2.4.0 release.
