### ISSUE TITLE
Both Menu spacing should be same

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#26235]
### Summary

Both Menu spacing should be the same in mobile view

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce
1. Go to the mobile view
2. Click on Humber menu

### Expected result

1. Both Menu spacing should be the same
![expected](https://user-images.githubusercontent.com/23443991/71662962-69f24800-2d79-11ea-95dd-8d0f380490d6.jpg)

### Actual result

1. Both Menu spacing different
![actual](https://user-images.githubusercontent.com/23443991/71662964-69f24800-2d79-11ea-8d48-323a46e30cea.jpg)

**Comment by hitesh-wagento** [comment]
I am working on this

**Comment by ajijshekh123** [comment]
Okay @hitendra-wagento , Can I confirm this issue or not?
Have you seen this issue in Latest Magento 2.4 Instance?

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30163` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hitesh-wagento** [comment]
Hi @ajijshekh123 

I have @hitesh-wagento  not @hitendra-wagento 

Thanks

**Comment by ajijshekh123** [comment]
Sorry for the inconvenience @hitesh-wagento

**Comment by VladimirZaets** [comment]
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26238 by @hitesh-wagento in 2.4-develop branch
Related commit(s):
 - [1fd25977b0c27b8aee5e765afdd46cee3cb69906](https://github.com/magento/magento2/commit/1fd25977b0c27b8aee5e765afdd46cee3cb69906)
 - [636f03a4431714f93fa3bb4b351c7189eb1496bc](https://github.com/magento/magento2/commit/636f03a4431714f93fa3bb4b351c7189eb1496bc)
 - [d3987e5b0c2d59e5a73e890215debe4a92ce4052](https://github.com/magento/magento2/commit/d3987e5b0c2d59e5a73e890215debe4a92ce4052)
 - [0d8699cf96118fb67e621a57ad62fb2b67e142c9](https://github.com/magento/magento2/commit/0d8699cf96118fb67e621a57ad62fb2b67e142c9)
 - [ad71c044d99536ff629337beffd779ae3e010d28](https://github.com/magento/magento2/commit/ad71c044d99536ff629337beffd779ae3e010d28)

The fix will be available with the upcoming 2.4.0 release.
