### ISSUE TITLE
Minimum Advertised Price doesn't change for selected swatch option for configurable product

### ISSUE THREAD

**Issue by sergiy-v** [magento/magento2#26240]
### Preconditions
1. Magento 2.4

### Steps to reproduce
1. Enable MAP (Store -> Configuration -> Sales -> Sales -> Minimum Advertised Price -> Enable MAP).

1. Create configurable product for attribute with 'swatch' (Visual Swatch, Text Swatch) type with associated products:
-  simple A: price 1, MAP 11. (ex: 'black' color)
-  simple B: price 1, MAP 12. (ex: 'white' color)

### Expected result
![Expected result](https://user-images.githubusercontent.com/1982263/71674510-0c172d80-2d84-11ea-8001-d6d5f014d4eb.png)

### Actual result
![Actual result](https://user-images.githubusercontent.com/1982263/71674594-47b1f780-2d84-11ea-9259-057758f9b792.png)

**Comment by Leandry** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leandry. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leandry, here is your [Magento instance](https://i-26240-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26240-2-4-develop.instances.magento-community.engineering/admin](https://i-26240-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@Leandry Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30173` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @sergiy-v. Thank you for your report. 
The issue has been fixed in magento/magento2#26241 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [2d2f1e05625ee4eb83dbabb78f09c667b863e554](https://github.com/magento/magento2/commit/2d2f1e05625ee4eb83dbabb78f09c667b863e554)
 - [2f04078af6761a8a54b9f7b007b6d611b44529f9](https://github.com/magento/magento2/commit/2f04078af6761a8a54b9f7b007b6d611b44529f9)
 - [c8c31bccd12a851901274093bc05968fc05df9e9](https://github.com/magento/magento2/commit/c8c31bccd12a851901274093bc05968fc05df9e9)
 - [324fa3f455ce959e95097061a3343700a22383f7](https://github.com/magento/magento2/commit/324fa3f455ce959e95097061a3343700a22383f7)
 - [03ef9334738b953d15139da483c3da82ec2770f1](https://github.com/magento/magento2/commit/03ef9334738b953d15139da483c3da82ec2770f1)
 - [4ace1e6658a80a9b017cd5803b30fb3ed6189dd0](https://github.com/magento/magento2/commit/4ace1e6658a80a9b017cd5803b30fb3ed6189dd0)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Hi @sergiy-v. Thank you for your report. 
The issue has been fixed in magento/magento2#26317 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [b3abb06344d88d366a23f32a144f3d70abe4fb3c](https://github.com/magento/magento2/commit/b3abb06344d88d366a23f32a144f3d70abe4fb3c)
 - [9d9086fd7aeb1574c14b4608daf393b6ac7080fc](https://github.com/magento/magento2/commit/9d9086fd7aeb1574c14b4608daf393b6ac7080fc)
 - [c12ca77ee9b888d14adf7554476914773f0fec6f](https://github.com/magento/magento2/commit/c12ca77ee9b888d14adf7554476914773f0fec6f)
 - [992e3d12afb3667a9cc972710bbf026c61354b4e](https://github.com/magento/magento2/commit/992e3d12afb3667a9cc972710bbf026c61354b4e)
 - [df37523bd44a63fe3c220677bf7a5d6ed310b268](https://github.com/magento/magento2/commit/df37523bd44a63fe3c220677bf7a5d6ed310b268)
 - [824ef9f444941ebc0de1181f1a246cc1e055d2b7](https://github.com/magento/magento2/commit/824ef9f444941ebc0de1181f1a246cc1e055d2b7)

The fix will be available with the upcoming 2.4.0 release.
