### ISSUE TITLE
Checkout. Quote Address Street cloning issue

### ISSUE THREAD

**Issue by yutv** [magento/magento2#26276]
### Preconditions (*)

1. Magento 2.3.3 or 2.4-develop
2. Logged in Customer with an Address marked both as Shipping and as Billing.

### Steps to reproduce (*)

1. Add a product to cart and go to the second step of checkout.
2. Open developer console and change billing address. e.g.

        require('Magento_Checkout/js/model/quote').billingAddress().street[0] = '123 Main Street'

### Expected result (*)

1. Shipping Address remains the same

### Actual result (*)

1. Shipping address street is changed to "123 Main Street"

![image](https://user-images.githubusercontent.com/1616522/71806438-7b856980-3071-11ea-9bab-4b8bce3dc712.png)

### Cloning Issue

The issue is here [app/code/Magento/Checkout/view/frontend/web/js/action/select-billing-address.js#L21](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/js/action/select-billing-address.js#L21)

and can be fixed by replacing:

    address = $.extend({}, billingAddress);

to

    address = $.extend(true, {}, billingAddress);

to clone address recursively including the street array.

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-26276-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26276-2-4-develop.instances.magento-community.engineering/admin](https://i-26276-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
Hello @yutv , This is not an issue. It is working as expected because you marked both Shipping and as Billing address same.

I am closing this issue. Feel free to reopen if you feel that this is Magento core issue.

**Comment by yutv** [comment]
@sudheers-kensium 

No, you are wrong. There is a bug. As you can see from the screenshot, changing the billing city doesn't lead to changing shipping city, but changing billing street does. An experienced front end developer may confirm that the issue exists.

**Comment by magento-engcom-team** [comment]
Hi @yutv. Thank you for your report. 
The issue has been fixed in magento/magento2#26279 by @yutv in 2.4-develop branch
Related commit(s):
 - [26872216194a2c534104573bb3e25075d933fc0c](https://github.com/magento/magento2/commit/26872216194a2c534104573bb3e25075d933fc0c)
 - [4e81fd8452469c6497bd3362fe80d4006b43151b](https://github.com/magento/magento2/commit/4e81fd8452469c6497bd3362fe80d4006b43151b)
 - [974f5e934f14c4dff32717e0ebab4e1ae10bd1c0](https://github.com/magento/magento2/commit/974f5e934f14c4dff32717e0ebab4e1ae10bd1c0)

The fix will be available with the upcoming 2.4.0 release.

**Comment by Ig0r-M-magic42** [comment]
@yutv @sudheers-kensium @magento-engcom-team commit https://github.com/magento/magento2/commit/26872216194a2c534104573bb3e25075d933fc0c#diff-e96dae14765cbb77c452167706254377f17c2c2821f689958e306c9c4f81169b
introduced following but for a problem (on 2.4.2)
![image](https://user-images.githubusercontent.com/22006850/117325408-998ef400-ae88-11eb-9f30-ac31b2f52462.png)


This is due to cloning that adds a bunch of function on top of data, see below:
One magento project
![image](https://user-images.githubusercontent.com/22006850/117325511-b1667800-ae88-11eb-84f2-b7f724ea397e.png)

Another magento project on 2.4.2
![image](https://user-images.githubusercontent.com/22006850/117325556-ba574980-ae88-11eb-978f-105ab68e3d8a.png)


Unfortunately i cannot confirm at this point steps to replicate as it's different from these 2 projects, but essentially reverting https://github.com/magento/magento2/commit/26872216194a2c534104573bb3e25075d933fc0c#diff-e96dae14765cbb77c452167706254377f17c2c2821f689958e306c9c4f81169b fixed it for me.

Any advice on this matter?

**Comment by yutv** [comment]
Hello @Ig0r-M-magic42,

Most probably you have Google Tag Manager (GTM) enabled on the website. I have noticed recently that the GTM script changes the `Array.prototype`, adds a lot of new methods there which are cloned and then displayed by knockout on checkout.

As a hotfix the following patch may be used.
```
diff '--exclude=.git' -ruN a/view/frontend/web/js/action/select-billing-address.js b/view/frontend/web/js/action/select-billing-address.js
--- a/view/frontend/web/js/action/select-billing-address.js	2020-11-18 16:06:30.577137247 +0200
+++ b/view/frontend/web/js/action/select-billing-address.js	2020-11-18 16:06:56.153010452 +0200
@@ -19,6 +19,7 @@
             quote.shippingAddress().getCacheKey()
         ) {
-            address = $.extend(true, {}, billingAddress);
+            address = $.extend({}, billingAddress);
+            address.street = (billingAddress.street || []).slice(0);
             address.saveInAddressBook = null;
         } else {
             address = billingAddress;
```

It resolves the issue on checkout but there are other occurrences of `$.extend(true, {},` in the native Magento code, so similar issue may appear in order places: https://github.com/magento/magento2/search?q=%24.extend%28true%2C+%7B%7D%2C&type=code.

**Comment by Ig0r-M-magic42** [comment]
@yutv thanks for the feedback, it's quite helpful
