### ISSUE TITLE
missing Throw in copy pasted code

### ISSUE THREAD

**Issue by angelomaragna** [magento/magento2#26288]
**Preconditions (*)**
magento 2.3.3

**Steps to reproduce (*)**
go to /Magento/Customer/Model/ForgotPasswordToken/GetCustomerByToken.php of magento installation

**Expected result (*)**
exception should be covered with throw

**Actual result (*)**
Hi, you've got a problem with file https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/ForgotPasswordToken/GetCustomerByToken.php

<img width="606" alt="image" src="https://user-images.githubusercontent.com/6837687/71880987-5c4a1300-3129-11ea-846f-4394a91baf32.png">

Check this pull request if you wish: https://github.com/magento/magento2/pull/26287

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30309` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by arjundedha** [comment]
https://minequotes.com/strong-women-quotes/

**Comment by magento-engcom-team** [comment]
Hi @angelomaragna. Thank you for your report. 
The issue has been fixed in magento/magento2#27269 by @Bal2018 in 2.4-develop branch
Related commit(s):
 - [de530f7be37c64617225ed428c269e34875bda23](https://github.com/magento/magento2/commit/de530f7be37c64617225ed428c269e34875bda23)
 - [f44add27fbdd5e41023dc7994d13962d84eba69b](https://github.com/magento/magento2/commit/f44add27fbdd5e41023dc7994d13962d84eba69b)
 - [1bd7d1e43bba6d278f56fe96c2381818aab21d4b](https://github.com/magento/magento2/commit/1bd7d1e43bba6d278f56fe96c2381818aab21d4b)
 - [5d11fdc55dd2d6563a97896042ebbaa459b9ffef](https://github.com/magento/magento2/commit/5d11fdc55dd2d6563a97896042ebbaa459b9ffef)
 - [459500929c367c76d7ed3d78a5c54b4e8d33d317](https://github.com/magento/magento2/commit/459500929c367c76d7ed3d78a5c54b4e8d33d317)
 - [d30e5e211962dd7b0d25bb6c289736ea128ecf0d](https://github.com/magento/magento2/commit/d30e5e211962dd7b0d25bb6c289736ea128ecf0d)
 - [000c822b5f027db3bb8ba83414b1f6ffd7664269](https://github.com/magento/magento2/commit/000c822b5f027db3bb8ba83414b1f6ffd7664269)
 - [239037a9a9c75a33ad93a184fbe969460112ad52](https://github.com/magento/magento2/commit/239037a9a9c75a33ad93a184fbe969460112ad52)
 - [baf892e87ea8fa728720700cc6e67e7fc4d38c7d](https://github.com/magento/magento2/commit/baf892e87ea8fa728720700cc6e67e7fc4d38c7d)
 - [c3855c831a9e401f9bc1fc1cd5722debb7281f83](https://github.com/magento/magento2/commit/c3855c831a9e401f9bc1fc1cd5722debb7281f83)
 - [bcc29ed38cc782d18aa338aedc684d2ca9dd7ac4](https://github.com/magento/magento2/commit/bcc29ed38cc782d18aa338aedc684d2ca9dd7ac4)

The fix will be available with the upcoming 2.4.2 release.
