### ISSUE TITLE
Minimum Advertised Prices duplicates for all configurable products with price from selected swatch

### ISSUE THREAD

**Issue by sergiy-v** [magento/magento2#26314]
Minimum Advertised Prices duplicates for all configurable products on product list with price from selected swatch.

### Preconditions
1. Magento 2.4

### Steps to reproduce
1. Enable MAP (Stores -> Configuration -> Sales -> Sales -> Minimum Advertised Price -> Enable MAP).
1. Enable 'Show Swatches in Product List', enabled by default (Stores -> Configuration -> Catalog -> Catalog -> Storefront -> Show Swatches in Product List).
1. The product attribute uses for configurable products should be visible on Product List (Stores -> Attributes -> Product -> select attribute -> Storefront Properties -> Used in Product Listing) in order to show attribute swatches for Product List.
1. Create few configurable products for the attribute with 'swatch' (Visual Swatch, Text Swatch) type with associated products:
   - Configurable A:
      - Black A: price 1, MAP 11. (ex: 'black' color)
      - White A: price 2, MAP 12. (ex: 'white' color)
   - Configurable B:
      - Black B: price 10, MAP 110. (ex: 'black' color)
      - White B: price 20, MAP 120. (ex: 'white' color)
1. Create category, assign created products.

### Expected result
![Expected result](https://user-images.githubusercontent.com/1982263/71999059-695e2380-3249-11ea-9139-ca980c5f6e10.png)

### Actual result
![Actual result](https://user-images.githubusercontent.com/1982263/71999086-7844d600-3249-11ea-824d-c3bfc1b0f041.png)

**Comment by Leandry** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Leandry. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Leandry, here is your [Magento instance](https://i-26314-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26314-2-4-develop.instances.magento-community.engineering/admin](https://i-26314-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30291` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Leandry** [comment]
@sergiy-v  thank you. I was able to reproduce an issue.
![2020-01-08_19-38-48 (1)](https://user-images.githubusercontent.com/9416636/72001748-bb557800-324e-11ea-8431-3bae2458aca7.gif)

**Comment by sergiy-v** [comment]
I'll working on the issue

**Comment by magento-engcom-team** [comment]
Hi @sergiy-v. Thank you for your report. 
The issue has been fixed in magento/magento2#26317 by @sergiy-v in 2.4-develop branch
Related commit(s):
 - [b3abb06344d88d366a23f32a144f3d70abe4fb3c](https://github.com/magento/magento2/commit/b3abb06344d88d366a23f32a144f3d70abe4fb3c)
 - [9d9086fd7aeb1574c14b4608daf393b6ac7080fc](https://github.com/magento/magento2/commit/9d9086fd7aeb1574c14b4608daf393b6ac7080fc)
 - [c12ca77ee9b888d14adf7554476914773f0fec6f](https://github.com/magento/magento2/commit/c12ca77ee9b888d14adf7554476914773f0fec6f)
 - [992e3d12afb3667a9cc972710bbf026c61354b4e](https://github.com/magento/magento2/commit/992e3d12afb3667a9cc972710bbf026c61354b4e)
 - [df37523bd44a63fe3c220677bf7a5d6ed310b268](https://github.com/magento/magento2/commit/df37523bd44a63fe3c220677bf7a5d6ed310b268)
 - [824ef9f444941ebc0de1181f1a246cc1e055d2b7](https://github.com/magento/magento2/commit/824ef9f444941ebc0de1181f1a246cc1e055d2b7)

The fix will be available with the upcoming 2.4.0 release.
