### ISSUE TITLE
Code cleanup for module xml extra end tag removed

### ISSUE THREAD

**Issue by tejash-wagento** [magento/magento2#26338]
### Description

Module xml extra end tag removed

### Fixed Issues (if relevant)

No issues

### Manual testing scenarios (*)

No special scenarios needed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

**Comment by dmytro-ch** [comment]
Hi @tejash-wagento,
please create the pull requests with minor improvements without opening the issues.
Thank you!

**Comment by slavvka** [comment]
Hi @tejash-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26339 by @tejash-wagento in 2.4-develop branch
Related commit(s):
 - [065353971c4dd2e835723d2702f391000cddb219](https://github.com/magento/magento2/commit/065353971c4dd2e835723d2702f391000cddb219)
 - [399fe8eb8f463bf85702e10e0c81c8cfe99a2abf](https://github.com/magento/magento2/commit/399fe8eb8f463bf85702e10e0c81c8cfe99a2abf)

The fix will be available with the upcoming 2.4.0 release.
