### ISSUE TITLE
Reorder in Admin panel leads to report page in case of changed product custom option max characters

### ISSUE THREAD

**Issue by oleksii-lisovyi** [magento/magento2#26345]
### Preconditions (*)

1. Magento ver. 2.3.2-p2.

### Steps to reproduce (*)

1. Configure a product with text (area) custom option, that has "Max Characters" value = 15.
2. Place an order with the configured product.
2.1. The text custom option value should be at least 11 symbols length.
3. Change the value of the product text custom option "Max Characters" to 10 (or less).
4. Go to the placed order in Admin panel.
5. Click on "Reorder" button.

### Expected result (*)

The Admin user see a clear error message, that explains, why the order couldn't reordered.
Probably it's enough to implement it in the same way as on frontend for registered customer:
![registered customer - reorder after changing max characters - error message](https://user-images.githubusercontent.com/3918875/72147579-7f81f600-33a7-11ea-89ea-5fa522e441be.png)

### Actual result (*)

The Admin user see a report page.

**Comment by oleksii-lisovyi** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @oleksii-lisovyi. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @oleksii-lisovyi, here is your [Magento instance](https://i-26345-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26345-2-4-develop.instances.magento-community.engineering/admin](https://i-26345-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by oleksii-lisovyi** [comment]
I was able to reproduce the issue on the provided vanilla Magento instance.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30362` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @oleksii-lisovyi. Thank you for your report. 
The issue has been fixed in magento/magento2#26348 by @cedmudit in 2.4-develop branch
Related commit(s):
 - [16079d95e30cc6be2aa6a35b79f80db9e90ac155](https://github.com/magento/magento2/commit/16079d95e30cc6be2aa6a35b79f80db9e90ac155)
 - [86dc12d370a0b23d9dc04e9e5a7b7b1be78ccaf4](https://github.com/magento/magento2/commit/86dc12d370a0b23d9dc04e9e5a7b7b1be78ccaf4)
 - [a21b2466f6d63e5b9d120ff0295f80f51c2ec7cc](https://github.com/magento/magento2/commit/a21b2466f6d63e5b9d120ff0295f80f51c2ec7cc)
 - [43f9e2b61dca391ca4c887f0c0c939dcbace34b7](https://github.com/magento/magento2/commit/43f9e2b61dca391ca4c887f0c0c939dcbace34b7)
 - [7ba11b83fdfdccb65fbe097f3c51a267f09a7f24](https://github.com/magento/magento2/commit/7ba11b83fdfdccb65fbe097f3c51a267f09a7f24)
 - [6c5fbcb16196a5e7757fe82c77f358da3aae1678](https://github.com/magento/magento2/commit/6c5fbcb16196a5e7757fe82c77f358da3aae1678)
 - [f7819a64af4ce9789fa86a71948870eaccbf8c95](https://github.com/magento/magento2/commit/f7819a64af4ce9789fa86a71948870eaccbf8c95)

The fix will be available with the upcoming 2.4.0 release.
