### ISSUE TITLE
Add to Compare link not showing in mobile view under 640px

### ISSUE THREAD

**Issue by tejash-wagento** [magento/magento2#26364]
### Summary
On Product detail page Add to Compare link is not showing in mobile view under 640px(@screen__s) resolution

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce

On the Product detail page

### Expected result

![image](https://user-images.githubusercontent.com/15318347/72235545-c9154f80-35f8-11ea-8481-fd324d430d8d.png)

### Actual result

![image](https://user-images.githubusercontent.com/15318347/72235527-abe08100-35f8-11ea-889b-5a202c1e4f17.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30366` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @tejash-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26424 by @ptylek in 2.4-develop branch
Related commit(s):
 - [9ec1d67e18d0b4fed5cc1ef3c8b9a8ad7327d41c](https://github.com/magento/magento2/commit/9ec1d67e18d0b4fed5cc1ef3c8b9a8ad7327d41c)

The fix will be available with the upcoming 2.4.0 release.

**Comment by VladimirZaets** [comment]
Hi @tejash-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26365 by @tejash-wagento in 2.4-develop branch
Related commit(s):
 - [f4f61f7265c16446ea2444bac6e867192580dce6](https://github.com/magento/magento2/commit/f4f61f7265c16446ea2444bac6e867192580dce6)

The fix will be available with the upcoming 2.4.0 release.
