### ISSUE TITLE
SameSite cookie, posible issues

### ISSUE THREAD

**Issue by diazwatson** [magento/magento2#26377]
| QPT Data Collection|borderStyle=dashed|borderColor=#cccccc|titleBGColor=#dddddd|bgColor=#e3ffea |
| --- |
| 
* **QPT release:**
 1.0.20
* **Patch ID**
MC-41359
* **Are there any additional actions required after the patch installation to make it work?**
 N/A
* **Compatible with Magento versions:**
[Check compatibility](https://web72.us-west-2.stg.sparta.ceng.magento.com/support/patchchk/?patch_id=MC-41359)
|

### Preconditions (*)
On February, 4, Google is set to roll out a new Chrome update that promises a bunch of new features designed to make the browser faster and more secure — including a new approach to cookies.

The SameSite update will require website owners to explicitly state label the third-party cookies that can be used on other sites. Cookies without the proper labelling won’t work in the Chrome browser, which has 63.62% of the overall browser market, according to [Statcounter](https://gs.statcounter.com/browser-market-share).

Right now, the Chrome SameSite cookie default is: “None,” which allows third-party cookies to track users across sites. But from February, cookies will default into “SameSite=Lax,” which means cookies are only set when the domain in the URL of the browser matches the domain of the cookie — a first-party cookie.

This will not probably affect Magento itself but what about it 3rd party integrations which comes pre installed by default such as NewRelic?

### Steps to reproduce (*)
1. Open Chrome and go to [chrome://flags/](chrome://flags/)
1. Enable `SameSite by default cookies` and `Cookies without SameSite must be secure`
1. Open the Chrome inspector. 

### Expected result (*)

1. No errors or warnings should show.

### Actual result (*)

Production site
![Screenshot 2020-01-13 at 20 21 44](https://user-images.githubusercontent.com/1080386/72289246-985a0800-3642-11ea-9b8d-bc3bf0d4918b.png)

Admin Panel of a Vanilla Magento 2.3-develop site
![Screenshot 2020-01-13 at 20 35 08](https://user-images.githubusercontent.com/1080386/72290086-5b8f1080-3644-11ea-8863-293c504f9745.png)

Paying with PayPal Express sandbox account
![Screenshot 2020-01-13 at 20 46 35](https://user-images.githubusercontent.com/1080386/72290815-f0463e00-3645-11ea-96e3-a9f570b9e05b.png)

### Related links
- https://www.chromestatus.com/feature/5088147346030592
- https://www.troyhunt.com/promiscuous-cookies-and-their-impending-death-via-the-samesite-policy/
- https://tools.ietf.org/html/draft-west-first-party-cookies-07
- https://www.troyhunt.com/promiscuous-cookies-and-their-impending-death-via-the-samesite-policy/
- https://medium.com/adobetech/adobe-experience-cloud-cookie-updates-for-google-chrome-19ad67cf1598
- https://www.netsparker.com/blog/web-security/same-site-cookie-attribute-prevent-cross-site-request-forgery/
- https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
- https://help.salesforce.com/articleView?id=000351874&language=en_US&type=1&mode=1

**Comment by okorshenko** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-26377-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26377-2-4-develop.instances.magento-community.engineering/admin](https://i-26377-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devchris79** [comment]
I think this is a possible duplicate of #26310

**Comment by diazwatson** [comment]
It is indeed @devchris79 thanks for linking both issues 👍

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30452` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by diazwatson** [comment]
@engcom-Charlie thanks for reviewing and testing this issue.
Can I request one of the architects from the security team to provide some guidance on what would be the best approach to fix this issue?

**Comment by DavaGordon** [comment]
Issues come across as a result of sameSite in the last 24 hours are if you do not have an active backend SSL certificate then both Chrome & Firefox will not allow you to log in to the backend admin panel rather it will simply refresh without any errors and warning. 

After looking further into it I think the cause of this is down to a commit made 22 days ago https://github.com/zendframework/zend-http/commit/84d4615bba86474dc5ee4014040a417fb91c3b3d

**Steps to Reproduce**

- Install Magento 2.3.3
- Navigate to Admin 
- Try and Login 

**Result** 
The page refreshes as the admin area is not set to secure and you are unable to login, 

**Temporary workaround until permanent fix found**
Once you enable secure in adminhtml in the either in the database core_config_data table or by running `bin/magento config:set web/secure/use_in_adminhtml 1` and cleaning the cache you will then gain admin access to the website again.

**Comment by diazwatson** [comment]
@okorshenko @magento-engcom-team guys do you see any potential issue in production sites with this change going live next week?

**Comment by dyushkin** [comment]
Hello @diazwatson!
I have created an internal Magento ticket `MC-31046`. The fix should be completed and delivered into the `2.4-develop` branch with internal PR.
Thank you for your collaboration.

**Comment by DavaGordon** [comment]
> Hello @diazwatson!
> I have created an internal Magento ticket `MC-31046`. The fix should be completed and delivered into the `2.4-develop` branch with internal PR.
> Thank you for your collaboration.

This comes in tomorrow so a fix is a pretty high priority as it will affect a lot of payment gateways thus making the checkout process impossible

**Comment by TonyMerlin** [comment]
Any news on this as yet as we've got cookies failing to load from multiple sources now on 2.3.4

**Comment by sjb9774** [comment]
It appears this new behavior breaks Payflow Pro credit card processing: https://github.com/magento/magento2/issues/26840

**Comment by sjb9774** [comment]
Also valuable to note per https://www.chromium.org/updates/same-site this SameSite functionality will not become the default behavior even on Chrome 80 until the 17th (and even then it seems it will be limited in scope).

**Comment by diazwatson** [comment]
I guess it is due to all the issue it cause. But it will be done sooner or later so better to be prepared.

**Comment by sjb9774** [comment]
@dyushkin Do you have any insight into the related task https://github.com/magento/magento2/issues/26840? It seems like a pretty serious issue

**Comment by HirokazuNishi** [comment]
Guys, I published quick & dirty fix module for this issue.

https://github.com/Veriteworks/CookieFix

We tested it against 3DS payment and worked fine.

**Comment by asim-vax** [comment]
Has there been any progress made? We are seeing this affect customers now

**Comment by sjb9774** [comment]
@asim-vax In what way?

**Comment by asim-vax** [comment]
@sjb9774 our 3DS payment gateways were redirecting to blank basket after inputting their bank details (session cookie not persisting). The fix from @HirokazuNishi worked great, and has fixed it for us(setting samesite to none, and secure to true)

**Comment by istoutjesdijk** [comment]
The Google API (analytics) also doesn't work anymore after the update to Chrome 80.

**Comment by devchris79** [comment]
The fix module from @HirokazuNishi doesn't appear to correct the cookies from the Google ReCaptcha functionality in the core:

![image](https://user-images.githubusercontent.com/43850303/75982266-1cf83280-5ede-11ea-9b9a-aa92415c6c09.png)

**Comment by HirokazuNishi** [comment]
@devchris79 seems these cookies are sent from google. Not from your M2 instance.
But... please submit such report to our repo. Not here.

**Comment by othuress** [comment]
Being an end-user of the system this is issue is a mega catastrophe I can not stress enough that this GAP needs to be fixed in Magento, we are loosing sales due to extent of void payments from Chrome browsers!

**Comment by OlegsJakovlevsJp** [comment]
“Same site cookie policy issue in Magento2 Since the SameSite Cookie Changes redirect payment method flows can break when the issuer is redirecting back to the Magento site with a POST request. When Magento processes the POST request it starts with loading the cart from the session. In order to do so it reaches to the SESSION cookie. Unfortunately, the SESSION cookie is not set as SameSite=None; Secure therefore the browser is going to decline using the cookie so the process fails and Magento redirects back to the empty cart page. Since the redirect is not handled by Magento the payment is not finalized and the order stays as new.

To solve this issue the SESSION cookie should be set as SameSite=None; Secure so POST requests from outside of the Magento website domain can also be processed.“

**Comment by adarshkhatri** [comment]
So what's the solution to this?

**Comment by theramppeople** [comment]
This is preventing 3d secure and causing us major issues!

**Comment by okorshenko** [comment]
Hi All! We are doing our best to have it fixed in 2.4.1. Internal Epic has several stories and these stories are In Dev right now.

**Comment by ldubreuil** [comment]
@okorshenko any update on this?

**Comment by kestraly** [comment]
Ebizmarts suggest setting cookie path: /;Secure;SameSite=None

**Comment by kzobov** [comment]
can this be pushed in 2.3.5-p3 or as a hotfix?

**Comment by manezaf8** [comment]
How far is Magento from fixing this issue ?

**Comment by smiverma** [comment]
Magento 2.3 still supports PHP 7.2  and PHP 7.2 doesn't support SameSite attribute for `secookies()` function so we cannot add explicit support for SameSite in Magento framework. we are investigating what could be done on our side to support 2.3 line however we have added support in our next release 2.4.1

**Comment by hardyjohnson** [comment]
There are multiple examples of setcookie polyfills for lower PHP versions, one of which is provided by GoogleChromeLabs (https://github.com/GoogleChromeLabs/samesite-examples/blob/master/php.md)  and a similar one from @HirokazuNishi (https://github.com/Veriteworks/CookieFix) mentioned above. While those solutions may not be elegant, they surely can be implemented in the framework to uphold any interface contracts expected in the Magento Framework.

We have production sites which are freezing during the payment redirect flow and upgrade to 2.4.x will not be in the cards prior to this holiday season. A fix in the next patch release for 2.3.x is critical for our clients.

Thank you for working on open source software. We will look and post any solutions we come up with in the meantime. We are running on 2.3.5-p1, but should be on p2 soon and PHP7.2 transitioning to 7.3 soon, so will need to support both sides of the application and platform fixes.

**Comment by ktsour** [comment]
> Guys, I published quick & dirty fix module for this issue.
> 
> https://github.com/Veriteworks/CookieFix
> 
> We tested it against 3DS payment and worked fine.

I have tried your plugin but it makes the add-to-cart to stop working. I will post an issue to your repo too.

My workaround was to add the following in the .htaccess file:
Header always edit Set-Cookie ^(PHPSESSID.*)$ $1;HttpOnly;Secure;SameSite=None

I hope it helps until a permanent solution is found.

**Comment by Blatant** [comment]
Another angle, I'm currently using this stanza in my .htaccess file. Prob best to fix within the framework tho.

	    <If "%{HTTP_USER_AGENT} !~ /(iPhone; CPU iPhone OS 1[0-2]|iPad; CPU OS 1[0-2]|iPod touch; CPU iPhone OS 1[0-2]|Macintosh; Intel Mac OS X.*Version\x2F1[0-2].*Safari|Macintosh;.*Mac OS X 10_14.* AppleWebKit.*Version\x2F1[0-3].*Safari)/i">
            Header always edit Set-Cookie (.*) "$1; SameSite=None; Secure"
        </If>

It excludes the browsers where the implementation is a  bit bawked ATM (Safari sic). But this might help someone panicking with a live site as a quick fix. Seems to be working out ok on our prod servers.

Its not my work, but based on one of a number of topics on webmaster.stackexchange.com

Source : https://webmasters.stackexchange.com/questions/128635/chrome-80-clears-session-cookies-for-users-returning-from-payment-gateway

**Comment by vpodorozh** [comment]
@okorshenko - so 2.4.1 is expected version with a fix?
thx!

**Comment by johnorourke** [comment]
@ktsour @Blatant if you're struggling because PHPSESSID gets set without it my PR might help: https://github.com/magento/magento2/issues/27531 - I haven't had time to make the unit tests they asked for so it got closed.

**Comment by Blatant** [comment]
Thanks @johnorourke I had seen this already, however I didn't want to add yet another module and overhead to the thing and (a true SysAdmin here) I preferred the elegance of a htaccess/vhost apache born solution. IMHO it just seems more elegant and concise to tackle it at the Apache level with a one shot stanza, and time was of the essence.

I do agree your module seems to sort it however I will wait for Adobe to tackle this in the core. Not to dissuade anyone from looking at your module of course!

**Comment by TonyMerlin** [comment]
> Another angle, I'm currently using this stanza in my .htaccess file. Prob best to fix within the framework tho.
> 
> ```
>     <If "%{HTTP_USER_AGENT} !~ /(iPhone; CPU iPhone OS 1[0-2]|iPad; CPU OS 1[0-2]|iPod touch; CPU iPhone OS 1[0-2]|Macintosh; Intel Mac OS X.*Version\x2F1[0-2].*Safari|Macintosh;.*Mac OS X 10_14.* AppleWebKit.*Version\x2F1[0-3].*Safari)/i">
>         Header always edit Set-Cookie (.*) "$1; SameSite=None; Secure"
>     </If>
> ```
> 
> It excludes the browsers where the implementation is a bit bawked ATM (Safari sic). But this might help someone panicking with a live site as a quick fix. Seems to be working out ok on our prod servers.
> 
> Its not my work, but based on one of a number of topics on webmaster.stackexchange.com
> 
> Source : https://webmasters.stackexchange.com/questions/128635/chrome-80-clears-session-cookies-for-users-returning-from-payment-gateway
> 
> Edit : Extends a bit on @ktsour response above 👍

How can this beimplementedd in Nginx?

**Comment by diazwatson** [comment]
Some very interesting & fun ways to debug and prove sameSite cookie issues (for chrome browsers).
https://www.chromium.org/updates/same-site/test-debug

**Comment by elvinristi** [comment]
Related Safari on MacOS 10.14, ipad/iphone bug when forcing SameSite=None
- https://bugs.webkit.org/show_bug.cgi?id=198181
- https://www.chromium.org/updates/same-site/incompatible-clients

I have done vice versa - patched on app level to send always SameSite=None and in Apache level removing for those specific OS/browsers

```
# https://bugs.webkit.org/show_bug.cgi?id=198181
<If "%{HTTP_USER_AGENT} =~ /(iPhone; CPU iPhone OS 1[0-3]|iPad; CPU OS 1[0-3]|iPod touch; CPU iPhone OS 1[0-3]|Macintosh; Intel Mac OS X.*Version\x2F1[0-3].*Safari|Macintosh;.*Mac OS X 10_14.* AppleWebKit.*Version\x2F1[0-3].*Safari|(Chrom[^ \x2F]+\x2F(([5][1-9])|([6][0-7]))[\.\d]*[ ]))/i">
  Header always edit Set-Cookie "^(.*)(;[ ]?SameSite=None|;[ ]?samesite=None)(.*)?$" "$1$3"
</If>
```

**Comment by tuyennn** [comment]
What is the current status of this major issue? The promise for the fix is about 9 months ago

**Comment by hostep** [comment]
@tuyennn: It looks like it's coming in Magento 2.4.1 (15 October) according to the [bèta release notes](https://devdocs-beta.magento.com/guides/v2.4/release-notes/open-source-2-4-1.html):
>  Magento Open Source 2.4.1 introduces enhancements to performance and security. Security enhancements include **support for the SameSite attribute for cookies** and the addition of CAPTCHA protection for payment-related and order-related API endpoints and the Place Order storefront page.

**Comment by tuyennn** [comment]
@hostep Thank you for your information, great to know that. Were those related commits appeared on the 2.4-develop branch?

**Comment by hostep** [comment]
@tuyenn: according the "hidden" information in the release notes, these are done under ticket MC-35389:
<img width="639" alt="Screenshot 2020-10-06 at 14 10 32" src="https://user-images.githubusercontent.com/85479/95199868-c9d0c000-07dd-11eb-91c2-b25f90500fb7.png">

But I can't find any commits yet on the 2.4-develop branch which mention that ticket. So I assume they'll only publish these when 2.4.1 is released, which is strange ...

**Comment by nathanjosiah** [comment]
Due to our release cycles and code freeze dates these changes had no choice but to go to 2.4.1. I just checked the mentioned internal ticket MC-35389 (and several other directly related tickets) and the commits were delivered to our internal private branches so unfortunately it looks like they will not be available until the public release.

As for 2.3.x I do not have an ETA right now but we are working on it.

**Comment by hardyjohnson** [comment]
@nathanjosiah thanks for the update, any chance this could be released through the Magento Quality patches channel for 2.3.x?

**Comment by JesKingDev** [comment]
> Related Safari on MacOS 10.14, ipad/iphone bug when forcing SameSite=None
> 
> * https://bugs.webkit.org/show_bug.cgi?id=198181
> * https://www.chromium.org/updates/same-site/incompatible-clients
> 
> I have done vice versa - patched on app level to send always SameSite=None and in Apache 2.4 level removing for those specific OS/browsers
> 

@elvinristi Does your solution resolve the issue for Safari browsers? If, so, would you mind sharing a Gist of how you've solved this with patching at the app level? This is an incredibly impactful issue for us and we don't currently have a workaround for Safari. FYI @gowthamleanswift.

**Comment by elvinristi** [comment]
@JesKingDev,

This is the patch I use currently on Magento 2.4.1-beta2
- https://gist.github.com/elvinristi/a3263ca92a62ff68a838650dd0e91667

And this is used on Apache 2.4 vhost conf
- https://gist.github.com/elvinristi/87674507e854524b12bf2fa286a98f2d

**Comment by yogeshkarodiya** [comment]
Is there any patch available for Magento2.3? or any hard fix for this issue because above solutions are not working

**Comment by james05** [comment]
Is the patch going to be released soon? I'm using 2.4.1 and still experiencing this issue.

**Comment by okorshenko** [comment]
Hi @james05 
We are planning to deliver the solution in the upcoming release. 
Please visit [upcoming release dates](https://devdocs.magento.com/release/?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=release%20schedule) documentation

**Comment by cstergianos** [comment]
@diazwatson @magento-engcom-team this issue breaks Magento 2.3.6-p1 upgrade on PHP 7.2 while it is supposed to be compatible. You cannot access the frontend at and I was able to confirm in two internal projects. The exception you get is:
`InvalidArgumentException: Failed to set ini option "session.cookie_samesite" to value "Lax".`

In order to resolve this, I switched to PHP 7.3 and used the veriteworks [extension mentioned above](https://github.com/Veriteworks/CookieFix). I have created a PR for the extension https://github.com/Veriteworks/CookieFix/pull/24 so feel free to create a patch from this if its not merged in time.

**Comment by sivamind** [comment]
on magento 2.4.2 upgrade Uncaught TypeError: Cannot create property 'cart' on string '{"messages":1613612384,"company":1613612384,"customer":1613612384,"compare-products":1613612384,"requisition":1613612384,"last-ordered-items":1613612384,"cart":1613612384,"directory-data":1613612384,"captcha":1613612384,"wishlist":1613612384,"company_authorization":1613612384,"negotiable_quote":1613612384,"instant-purchase":1613612384,"loggedAsCustomer":1613612384,"multiplewishlist":1613612384,"purchase_order":1613612384,"persistent":1613612384,"review":1613612384,"recently_viewed_product":1613612384,"recently_compared_product":1613612384,"product_data_storage":1613612384,"paypal-billing-agreement":1613612384}laxlaxlaxlaxlaxlax'

**Comment by kkhebbar89** [comment]
On Magento 2.4.2, I am getting similar error as below as @sivamind is getting. 
Uncaught TypeError: Cannot create property 'quickOrderPadLink' on string '{"choose-address-link":1614686904,"branchPickUpLink":1614686904,"quickOrderPadLink":1614686904,"messages":1614686904,"customer":1614686904,"compare-products":1614686904,"last-ordered-items":1614686904,"cart":1614686904,"directory-data":1614686904,"captcha":1614686904,"instant-purchase":1614686904,"loggedAsCustomer":1614686904,"persistent":1614686904,"review":1614686904,"wishlist":1614686904,"locationPicker":1614686904,"b2bmasquerade":1614686904,"accountSummary":1614686904,"companylink":1614686904,"delearShopperLink":1614686904,"recently_viewed_product":1614686904,"recently_compared_product":1614686904,"product_data_storage":1614686904,"paypal-billing-agreement":1614686904}lax'

I think the issue is because of "lax" getting concatenated at the end of "section_data_ids" cookie value.

**Comment by nathanjosiah** [comment]
@cstergianos We had a communication issue where it wasn't explicitly communicated that PHP 7.2 support was dropped for 2.3.6-p1 and this was further made confusing by the composer dependencies hasn't removed 7.2 either. However, speaking generally, Magento cannot release a version of software that isn't PCI compliant and [PHP 7.2 is EOL](https://www.php.net/supported-versions.php) and therefore not PCI compliant. We do apologize for this communication gap and any trouble that it may have caused you.

@sivamind  and @kkhebbar89, can you provide more information about these issues? We perform QA and regression testing and this issue didn't come up in our scenarios. Did you happen to perform a root cause analysis for how this string is being appended to your JSON payloads?

**Comment by behnamshayani** [comment]
@nathanjosiah  I might be mistaken, but Php7.2 is part of main repository for Ubuntu 18.04.1 and is supported by Ubuntu until 2023. So Php7.2 should be considered PCI compliant on Ubuntu 18.04.1 and is not EOL on those installations IMO.

**Comment by nathanjosiah** [comment]
@behnamshayani It may be true that there are places to get PHP 7.2 where it is supported for longer periods of time but unfortunately Magento isn't just for Ubuntu which means we can't rely solely on their support for our compatibility decisions.

**Comment by behnamshayani** [comment]
@nathanjosiah  Certainly not for your compatibility decisions but to me it sounds more like you are making decisions for merchant if their installation is PCI compliant or not.
You can say we do not support 7.2 and that is your decision, just don't put it on PCI compliance.

**Comment by nathanjosiah** [comment]
@behnamshayani I'm not sure this is any different than any other compatibility. We essentially support the industry standard of N-1 or N-2 software and browser versions and PHP is no exception. In this case the official software is end of life and we cannot remain PCI compliant while supporting this software that violates our compliance. By example, there are still ways of getting PHP 5.4 (which has the same official support as PHP 7.2) and many still use it but that doesn't mean we support it or are allowed to support it.

**Comment by hostep** [comment]
I'm pretty sure that PCI compliance doesn't say that you need to drop support for PHP versions which no longer receive security fixes. Magento just needs to ensure it works on PHP versions which do get security fixes (in case of the official PHP releases that would be PHP 7.3, 7.4 or 8.0 at the moment of writing). If it still supports older PHP versions that is very much appreciated for the merchants who use decent hosting which use decent PHP packages which get like 5 year of security fixes (like Ubuntu or Debian and probably the RedHat distro family as well).

(I just checked and we have a shop running on PHP 7.0 which still receives security fixes, last update to the PHP version was 2 weeks ago even though PHP dropped official support back in 2019 ...)

Also, Magento shouldn't assume every merchant needs to be PCI compliant, that only counts when you need to acquire credit card numbers directly on your webshop, right? If you put that responsibility in the hands of a Payment Service Provider, then you don't need to be PCI compliant as far as I'm aware (I'm pretty sure that most merchants on Magento don't need to be PCI compliant).
It's however best practice to try to stay as safe as possible by using the latest Magento version and PHP version that's compatible with it though.

Anyways, this doesn't really bring anything useful to the discussion here.

----

Summary:
Adobe simply forgot that Magento 2.3 was still compatible with PHP 7.1 and 7.2 before they merged their samesite cookie feature in that release. Then they forgot to communicate about it even after being alerted about this problem before the official release.

It's unfortunate that this has happened in a patch release because those are supposed to be "easy" to roll out, but it is what it is.

Not much to do about it I'm afraid, upgrading to PHP 7.3 should in theory still be possible on Ubuntu 18.04 if you use an alternative PHP package then the built-in one, like https://deb.sury.org/ I think (not sure about this, I'm not an expert in these things, you should double check with your hosting to see what they can do).

**Comment by sivamind** [comment]
@nathanjosiah from the admin side we are using login as customer functionality then some times we are getting those js lax issues

**Comment by kkhebbar89** [comment]
@sivamind @nathanjosiah 
I am facing the issue at (Magento 2.4.2) frontend on login, not able to understand how its happening. But on debugging found that the cause of the issue is lib/web/jquery/jquery.cookie.js line no. 50. The code is 

_options.samesite  ? '; samesite=' + options.samesite : 'lax'_

I think it should be as below 

_options.samesite  ? '; samesite=' + options.samesite : '; samesite=lax'_

**Comment by pemann** [comment]
@kkhebbar89 Is there the same problem in https://github.com/magento/magento2/blob/2.4.2/lib/web/mage/cookies.js Line 79?

**Comment by pemann** [comment]
Why there is no samesite setting in form_key cookie set in https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/PageCache/view/frontend/web/js/form-key-provider.js Line 27 ?

**Comment by hostep** [comment]
Nice find @kkhebbar89

This seems like a silly bug introduced in Magento 2.4.2 and I can't really believe that nobody properly tested [this syntax](https://github.com/magento/magento2/blob/2.4.2/lib/web/mage/cookies.js#L79)

Proof: https://jsfiddle.net/wzt746hm/

@nathanjosiah : I think this answers [your question](https://github.com/magento/magento2/issues/26377#issuecomment-789921430) from earlier

Another bug report around this came in yesterday: https://github.com/magento/magento2/issues/32440
An attempt is being made at getting this fixed: https://github.com/magento/magento2/pull/32266, but that's in another file

**Comment by ihor-sviziev** [comment]
FYI I created PR that should fix this issue in all places. https://github.com/magento/magento2/pull/32462

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41359` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @diazwatson. Thank you for your report. 
The issue has been fixed in magento/magento2#32462 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [bc5f97e65aadf8c8e5ee216100805874826198ca](https://github.com/magento/magento2/commit/bc5f97e65aadf8c8e5ee216100805874826198ca)
 - [41b935d9645f7108232cef2f39a521cd22d18623](https://github.com/magento/magento2/commit/41b935d9645f7108232cef2f39a521cd22d18623)
 - [35570b3b0a98b578f88bd6cb694b1c0f4fc2b7c8](https://github.com/magento/magento2/commit/35570b3b0a98b578f88bd6cb694b1c0f4fc2b7c8)
 - [753be2a3db726090a6f05b7801ed4047ee65f36d](https://github.com/magento/magento2/commit/753be2a3db726090a6f05b7801ed4047ee65f36d)

The fix will be available with the upcoming 2.4.3 release.

**Comment by sivamind** [comment]
I think there should be a patch for this. due to this we are not able to add to cart or wishlist ,also not able to go to checkout.

**Comment by pemann** [comment]
Can you include this fix in 2.4.2-p1?

**Comment by hostep** [comment]
Patch can just be created from the pull request: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/32462.diff

Note that this patch is only a solution for "lax" suffix that gets added in a wrong format. This general issue has been more or less fixed in Magento 2.3.6-p1 and 2.4.2 (and probably also 2.4.1-p1).

**Comment by ihor-sviziev** [comment]
I'm going to create a pull request to quality patches repo when will have some free time, so it will be released faster

**Comment by ihor-sviziev** [comment]
I just created a PR that ports my fix to quality patches for Magento 2.3.6-p1 and 2.4.2: https://github.com/magento/quality-patches/pull/47

**Comment by chickyd3v** [comment]
Hi guys, how to implement this samesite fix for 2.4.0?

**Comment by live4soccer7** [comment]
@salehawal Do you have cookie restriction mode enabled? I do not and I am wondering if maybe that needs to be enabled for the cookies to have the proper attributes assigned.

**Comment by wajihkm** [comment]
> We've found a workaround for the cookie issue, currently it works just fine in our 2 projects. Basically the issue is the session being cleared whenever the browser is processing a POST request from 3rd party system to Magento instance (like, when redirecting from Payment Gateway to Magento after payment succeed). So we created a plugin of the SessionStartChecker class and exclude the callback URL that the 3rd party system is using to POST back the data to Magento.
> 
> app/code/SB/Framework/etc/di.xml:
> 
> ```
> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>         xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
>     <type name="Magento\Framework\Session\SessionStartChecker">
>         <plugin name="CallbackSessionChecker"
>                 type="SB\Framework\Plugin\CallbackSessionChecker"/>
>     </type>
> </config>
> ```
> 
> app/code/SB/Framework/Plugin/CallbackSessionChecker.php:
> 
> ```
> 
> namespace SB\Framework\Plugin;
> 
> use Magento\Framework\App\Request\Http;
> use Magento\Framework\Session\SessionStartChecker;
> 
> class CallbackSessionChecker
> {
>     /**
>      * Array
>      */
>     private const PAYMENT_CALLBACK_PATHS = [
>         'payso/payment/response',
>         'KbankOnlinePayment/Callback/Card',
>         'KbankOnlinePayment/Callback/Qr',
>         'p2c2p/payment/response',
>         'P2c2p/payment/response',
>         'sociallogin/social/callback'
>     ];
> 
>     /**
>      * @var Http
>      */
>     private $request;
> 
>     /**
>      * @param Http $request
>      */
>     public function __construct(Http $request)
>     {
>         $this->request = $request;
>     }
>     /**
>      * Check if session can be started or not, taking payment extension's response action into consideration
>      * @param \Magento\Framework\Session\SessionStartChecker $subject
>      * @param bool $result
>      * @return bool
>      */
>     public function afterCheck(\Magento\Framework\Session\SessionStartChecker $subject, bool $result) : bool
>     {
>         if ($result === false) {
>             return false;
>         }
> 
>         $inArray = true;
>         foreach (self::PAYMENT_CALLBACK_PATHS as $path) {
>             if (strpos((string)$this->request->getPathInfo(), $path) !== false) {
>                 $inArray = false;
>                 break;
>             }
>         }
>         return $inArray;
>     }
> }
> ```
> 
> Hope this can help someone.

This solution has some issues with Guest customers.
