### ISSUE TITLE
Store switcher redirects to homepage for multistore setup with different domains

### ISSUE THREAD

**Issue by DanieliMi** [magento/magento2#26384]
### Preconditions (*)

1. 2.3.3
2. More than one store view
3. Separate domain for the store views (default -> mage.local, second store view -> test.mage.local)
Apache vhost:
```
<VirtualHost *:80>
   ServerName          mage.local
   DocumentRoot        /var/www/html/magento2/pub/
</VirtualHost>

<VirtualHost *:80>
   ServerName          test.mage.local
   DocumentRoot        /var/www/html/magento2/pub/
   SetEnv MAGE_RUN_CODE "test"
   SetEnv MAGE_RUN_TYPE "store"
</VirtualHost>
```
4. Setup base urls for both store views in Stores > Settings > Configuration > General > Web
5. Create a category (it can be reproduced with cms pages too)

### Steps to reproduce (*)

1. Go to mage.local
2. Go to category
3. Use store switch to switch to the other store

### Expected result (*)

1. Redirect to test.mage.local/category-name.html

### Actual result (*)

1. Redirect to test.mage.local/

### Additional Information
Probably related to #14674 and #19714

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30450` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by TobiasLufinity** [comment]
The problem seem to exist in the request between "stores/store/redirect" and "stores/store/switch".

I have a Magento 2.4-dev setup with two stores (sv and default). The requests for the two mentioned above when switching from sv to default is
"http://sv.magento-dev.dev.int/index.php/stores/store/redirect/___store/default/___from_store/se/uenc/{unec}/"
and
 "http://sv.magento-dev.dev.int/index.php/stores/store/switch/?___from_store=se&___store=default&uenc={uenc}".

The problem then appears in the \Magento\Store\Model\BaseUrlChecker::execute on line 42 which is called from \Magento\Store\App\FrontController\Plugin\RequestPreprocessor::aroundDispatch on line 81. It checks if the host in the $uri array matches the host in the request. The $uri array is parsed using the parse_url method with the base url of the current store. To get the current store Magento uses \Magento\Store\Model\StoreManager::getStore which in turn uses the \Magento\Store\Model\StoreResolver::getCurrentStoreId. This method will retrieve the store from the url parameter ___store which in this case is "default" and the base url for my default store is http://magento-dev.dev.int. So the check if the request host (http://sv.magento-dev.dev.int) matches the base url of the store (http://magento-dev.dev.int) fails and you will be redirected incorrectly.

The request to "stores/store/swtich" should be to the new stores url and not the current. We've fixed this by setting current store before the last redirect in \Magento\Store\Controller\Store\Redirect::execute so the redirect request is made to the base url of that store. 
It will need some more testing  but I will make a pull request to Magento with this fix.

**Comment by TobiasCodeNull** [comment]
The pull request has been accepted so you can use this patch to fix the issue in your Magento 2.3.3 instance: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/26548.patch

**Comment by magento-engcom-team** [comment]
Hi @DanieliMi. Thank you for your report. 
The issue has been fixed in magento/magento2#26548 by @TobiasCodeNull in 2.4-develop branch
Related commit(s):
 - [346e544911827c379bdfed10f29ea40889d57078](https://github.com/magento/magento2/commit/346e544911827c379bdfed10f29ea40889d57078)
 - [392bd3b899cd26d5d329eaa0ab7e7a1b91125c4b](https://github.com/magento/magento2/commit/392bd3b899cd26d5d329eaa0ab7e7a1b91125c4b)
 - [0cbc5b641efdee01fa2bd4222c2cc313d3846198](https://github.com/magento/magento2/commit/0cbc5b641efdee01fa2bd4222c2cc313d3846198)
 - [420fa1c739a2b568a115defdc58509976241464d](https://github.com/magento/magento2/commit/420fa1c739a2b568a115defdc58509976241464d)
 - [1375b5356aae59924f0e8f70b1970e8b85877e19](https://github.com/magento/magento2/commit/1375b5356aae59924f0e8f70b1970e8b85877e19)
 - [9cad4dcf942f1be3f704a16293116458c7b837fe](https://github.com/magento/magento2/commit/9cad4dcf942f1be3f704a16293116458c7b837fe)
 - [602419572902c06ed81a58080391207304c32760](https://github.com/magento/magento2/commit/602419572902c06ed81a58080391207304c32760)
 - [ee97fb5c647ce047d98d2a5554c67540df3fd7cf](https://github.com/magento/magento2/commit/ee97fb5c647ce047d98d2a5554c67540df3fd7cf)
 - [689093a20a8d4226c2ca74c039a8136b7604887e](https://github.com/magento/magento2/commit/689093a20a8d4226c2ca74c039a8136b7604887e)
 - [4708394d867aa235d51489f0e12b9705f081b9db](https://github.com/magento/magento2/commit/4708394d867aa235d51489f0e12b9705f081b9db)
 - [597bb18bc0faba8b0e67a499749c15785a23da16](https://github.com/magento/magento2/commit/597bb18bc0faba8b0e67a499749c15785a23da16)
 - [0fcb6a0c06cbcbf733da284bb94b85a5e1ea1f16](https://github.com/magento/magento2/commit/0fcb6a0c06cbcbf733da284bb94b85a5e1ea1f16)

The fix will be available with the upcoming 2.4.0 release.

**Comment by viktym** [comment]
You can install the patch for Magento 2.3.0 - 2.3.5 using Magento Quality Patches package ([MQP](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching.html#mqp))

**Installation**
`$ composer require magento/quality-patches`

**Applying a patch:**
`$ ./vendor/bin/magento-patches apply MDVA-30107`

**Patch details:**
https://support.magento.com/hc/en-us/articles/360049869051

**Comment by VZeroCool** [comment]
Not working on Magento CE 2.3.3 

Applied above patch, Preconditions, 2 store views, 1 website and 1 store.

One CMS page in both store view with same URL key, Switching store from CMS Page taking to home page. 
why ? @viktym  @tstoyanovski-bounteous

**Comment by VZeroCool** [comment]
@magento give me 2.3-develop instance
