### ISSUE TITLE
Compare Products section not showing in mobile view under 767px

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#26416]
### Summary
Compare Products section not showing in mobile view under 767px

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce

1. Go to the Category page
2. Add product to compare

### Expected result

![expected](https://user-images.githubusercontent.com/23443991/72518218-d9d4f800-387a-11ea-93ef-cfc6d85afd47.png)

### Actual result

![actual](https://user-images.githubusercontent.com/23443991/72518216-d93c6180-387a-11ea-868c-723683a534c8.png)

**Comment by hitesh-wagento** [comment]
I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30480` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26418 by @hitesh-wagento in 2.4-develop branch
Related commit(s):
 - [1aed73ef7b48ea17e9f5f52d949dba056b591cfd](https://github.com/magento/magento2/commit/1aed73ef7b48ea17e9f5f52d949dba056b591cfd)
 - [f88223a74a92cc8c3eafc7bf5aea6c6f8c88e83f](https://github.com/magento/magento2/commit/f88223a74a92cc8c3eafc7bf5aea6c6f8c88e83f)
 - [e90a4a12157002cd35110ae6aa38dda88f3b1c44](https://github.com/magento/magento2/commit/e90a4a12157002cd35110ae6aa38dda88f3b1c44)

The fix will be available with the upcoming 2.4.0 release.
