### ISSUE TITLE
Cron needs index.php to be writeable

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26410]
`update-cron.ERROR: Cron readiness check failure! Found non-writable paths:        /home/http/magento/index.php [] []`

What is the purpose of this?

Why would we want index.php to be writeable? So we can be hacked easier?

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Install Magento
2. Setup cronjob
3. $ chmod 444 index.php
4. $ cat var/log/update.log

### Expected result (*)

No error spam in update.log

### Actual result (*)

Error spam in update.log

**Comment by engcom-Hotel** [comment]
Hello @Zyles 
`index.php` file have 644 permissions in production mode, which means writable by the user, read-only by the group, and read-only for everyone else.
![image](https://user-images.githubusercontent.com/51681618/72518326-c10a1980-385d-11ea-998d-07fe47a700a1.png)
So that means this file cannot be easy hacked.
More about Magento 2 file system permissions you can read [here](https://devdocs.magento.com/guides/v2.3/config-guide/prod/prod_file-sys-perms.html).

So i have to close this issue as non-issue.
Thanks for your report!

**Comment by Zyles** [comment]
Again, terrible security.

For what reason do you need index.php to be writeable by anyone?

This makes Magento 2 unable to run in a read-only state.

**Comment by hostep** [comment]
@Zyles: The error seems to come from the `update/cron.php` command, correct?

I think that script is used for Magento to be able to update itself, which would need write permissions to all files.

If you don't need that feature, then don't run that specific cron command ;)
The one and only cron you need to setup for Magento is: `bin/magento cron:run`.
The other two which are mentioned on [the docs](https://devdocs.magento.com/guides/v2.3/install-gde/install/post-install-config.html#create-the-magento-crontab) are not strictly necessary to run.

(disclaimer: I've never used that `update/cron.php` or `setup:cron:run` script myself, so I might be wrong about this)
