### ISSUE TITLE
Adding new Deserializer to Rest API removes other Deserializers 

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#26433]
### Preconditions (*)

1. Magento 2.2.x / Magento 2.3.x both CE / EE & 2.4-develop

### Steps to reproduce (*)

1. Create a new module which will add new webapi route
2. Create a new deserializer using `di.xml` in your module

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    
    <preference for="Coinpayments\Withdrawals\Api\IpnInterface"
                type="Coinpayments\Withdrawals\Model\Ipn" />

    <type name="Magento\Framework\Webapi\Rest\Request\DeserializerFactory">
        <arguments>
            <argument name="deserializers" xsi:type="array">
                <item name="text_plain" xsi:type="array">
                    <item name="type" xsi:type="string">text/plain</item>
                    <item name="model" xsi:type="string">Custom\Module\Webapi\Rest\Request\Deserializer\Plain</item>
                </item>
            </argument>
        </arguments>
    </type>

### Expected result (*)

1. New content type accepted by REST API 

### Actual result (*)

1. All CORE defined content types for API are no longer working and return 400 error
![image](https://user-images.githubusercontent.com/51681618/72727558-dd76c080-3b93-11ea-8f70-efd16bb1c039.png)

2. Only new defined content type is accepted

It was my understanding that **DI.XML** is used to extend **CORE** features, not **OVERWRITE** them.

**Comment by jakwinkler** [comment]
After checking content of
`generated/metadata/global.php`
`DeserializerFactory` has only 1 argument, defined in my module, others are missing. 

`'Magento\\Framework\\Webapi\\Rest\\Request\\DeserializerFactory' => 
    array (
      'objectManager' => 
      array (
        '_i_' => 'Magento\\Framework\\ObjectManagerInterface',
      ),
      'deserializers' => 
      array (
        '_v_' => 
        array (
          'text_plain' => 
          array (
            'type' => 'text/plain',
            'model' => 'Custom\\Module\\Webapi\\Rest\\Request\\Deserializer\\Plain',
          ),
        ),
      ),
    ),
`

**Comment by jakwinkler** [comment]
Its the same with `etc/webapi_rest/di.xml`

**Comment by jakwinkler** [comment]
Just an update from my end:
It seems like this is a general `di.xml` bug / (feature??)
If you try to add a new argument to an existing `<type>` in your own module, it will overwrite all arguments defined in CORE or 3rd party modules.
Its the same for all areas where you can define `di.xml` file
In order for this to work, you have to copy+paste arguments section to your own module

**Comment by engcom-Hotel** [comment]
Hello @qsolutions-pl 
This issue is a bug. 

Thanks for collaboration!

**Comment by fooman** [comment]
Speculating here it could be related to 'vendor/magento/framework/Config/Dom/NodeMergingConfig.php'
```
    public function getIdAttribute($nodeXpath)
    {
        foreach ($this->idAttributes as $pathPattern => $idAttribute) {
            if ($this->nodePathMatcher->match($pathPattern, $nodeXpath)) {
                return $idAttribute;
            }
        }
        return null;
    }
```

which looks to be working in conjunction with
vendor/magento/framework/ObjectManager/Config/Reader/Dom.php

```
    protected $_idAttributes = [
        '/config/preference' => 'for',
        '/config/(type|virtualType)' => 'name',
        '/config/(type|virtualType)/plugin' => 'name',
        '/config/(type|virtualType)/arguments/argument' => 'name',
        '/config/(type|virtualType)/arguments/argument(/item)+' => 'name',
    ];
```

The order of the above idAttributes seems important here. It might get a result for `/config/(type|virtualType)/arguments/argument` before it gets to ` '/config/(type|virtualType)/arguments/argument(/item)+'`

or it might go too deep.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30627` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Neo-Creo** [comment]
@magento assign this issue to me.

**Comment by Neo-Creo** [comment]
@magento I am working on this

**Comment by Neo-Creo** [comment]
@magento add to contributors team

**Comment by Neo-Creo** [comment]
@magento I am working on this

**Comment by sidolov** [comment]
Hi @qsolutions-pl , it's a known behavior of the configuration merge process, arguments defined in the “initial” config file, app/etc/di.xml (see https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/di-xml-file.html ) are overridden by the arguments defined on the module level. The common solution in this case is to duplicate original arguments and add the new ones.

We had discussions on that several times and there is no simple solution to fix it. 
Right now we are investigating the mentioned case and possible options on how to resolve it, most of the cases when this issue appears are caused by the wrong config location (webapi configuration probably should be in webapi module instead of global config).

**Comment by qsolutions-pl** [comment]
@sidolov the same issue is when you add configuration in webapi, I've checked all scenarios

**Comment by gabrieldagama** [comment]
Hi @qsolutions-pl,

I believe the problem is related to the stages where the arguments are defined, as described on the DevDocs (https://devdocs.magento.com/guides/v2.4/extension-dev-guide/build/di-xml-file.html#areas-and-application-entry-points), we have three stages, if you define arguments on a higher stage (the stage that is loaded later), it will overwrite the stages defined on the lower stage.

I've created a pull request to add that information as a warning on the DevDocs, hopefully, that will make it a little bit more clear. https://github.com/magento/devdocs/pull/8180

Hope that makes sense.

**Comment by qsolutions-pl** [comment]
Hi @gabrieldagama it does make sense to warn developers but, in my opinion, this is not a solution. 
In my project I only had 1 module which adds a deserializer, what if there are 3 or 5 modules with different deserializers? It will be hard to maintain the code because developer or team od developers will have to remember to double or tripple check each module which adds a deserializer.
Imho this should be fixed to maintain Magento platform flexibility.
The easiest solution: It is worth considering adding new deserializers to the core.

**Comment by qsolutions-pl** [comment]
Its has been over a year without any solution and no possible fix from the CORE team.
Closing the issue.
