### ISSUE TITLE
Configurable product attribute issue

### ISSUE THREAD

**Issue by Puru2016** [magento/magento2#26449]
### Preconditions (*)

1. Magento 2.3.1 with sample data
2. Size attribute Use in Layered Navigation

### Steps to reproduce (*)

1. Log into the admin account.
2. Navigate to Catalog > Products.
3. In add new product dropdown choose configurable product and create a configurable product using “Size” attribute:-

<img width="870" alt="Screenshot_22" src="https://user-images.githubusercontent.com/20985181/72661534-4a0d8600-3a01-11ea-8002-c6a245a00787.png">

3. Size attribute available to choose in configurable, but leave it as it is.
Once you created the configurable product,  size attribute also assigned to main configurable product like this:
<img width="872" alt="Screenshot_23" src="https://user-images.githubusercontent.com/20985181/72661554-66112780-3a01-11ea-8373-097e06f179f3.png">

3. Once you filter the products on category page using 49 size, this product visible in filter result. As I am not using 49 size in configurable product. (49 size are not available in my store).

### Expected result (*)

1. Size attribute should not be assign to parent configurable product, so once user filter the product on category page using 49 size, this product not show in filter result.

### Actual result (*)

1.  49 Size assigned parent configurable product automatically and visible in filter result on category page when user select size 49. That is wrong functionality.

Let me now if you need more explanation to understand this issue.

**Comment by Puru2016** [comment]
I am only using Size 48.5 and 48.7 for create child products in configurable product. 

Here is the Size attribute details:-

<img width="860" alt="Screenshot_2" src="https://user-images.githubusercontent.com/20985181/72664243-789b5900-3a21-11ea-884f-700e676f0dda.png">

**Comment by Zyles** [comment]
@magento give me 2.4-develop instance

**Comment by Puru2016** [comment]
Any update on this or require more information to replicate this issue, Please let me know.

**Comment by ghost** [comment]
I am also facing the same issue.

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Zyles, here is your [Magento instance](https://i-26449-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26449-2-4-develop.instances.magento-community.engineering/admin_3ede](https://i-26449-2-4-develop.instances.magento-community.engineering/admin_3ede)
Login: `51d66acd` Password: `80ddfef013c1`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26449-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26449-2-4-develop.instances.magento-community.engineering/admin_34c2](https://i-26449-2-4-develop.instances.magento-community.engineering/admin_34c2)
Login: `c42e9552` Password: `e7b88a189aa3`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32089` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Puru2016. Thank you for your report. 
The issue has been fixed in magento/magento2#27339 by @tna274 in 2.4-develop branch
Related commit(s):
 - [e7ff694959704cc0c570d330b70ee8c79855ad43](https://github.com/magento/magento2/commit/e7ff694959704cc0c570d330b70ee8c79855ad43)
 - [1071acfcea57b050d8ba432371455e2de09d723f](https://github.com/magento/magento2/commit/1071acfcea57b050d8ba432371455e2de09d723f)
 - [3b6b038c329178ec08d4202967edf1f19ab461f5](https://github.com/magento/magento2/commit/3b6b038c329178ec08d4202967edf1f19ab461f5)
 - [19ceb3a596f773bca9de0bcff1f75cf58df22563](https://github.com/magento/magento2/commit/19ceb3a596f773bca9de0bcff1f75cf58df22563)
 - [1efecdfaaabeb6eaaef24e81bdb7c6579c589174](https://github.com/magento/magento2/commit/1efecdfaaabeb6eaaef24e81bdb7c6579c589174)
 - [1e9895dfc62f7a2b9f241a83e9a6be979b44fa13](https://github.com/magento/magento2/commit/1e9895dfc62f7a2b9f241a83e9a6be979b44fa13)
 - [d139cf93be642abb8a858af2cdd4bcb8fbf10cc0](https://github.com/magento/magento2/commit/d139cf93be642abb8a858af2cdd4bcb8fbf10cc0)
 - [ec6bb304c1e8832c3079f2b2a4628098df370696](https://github.com/magento/magento2/commit/ec6bb304c1e8832c3079f2b2a4628098df370696)
 - [7cad47619fc39218f3b0fa5f178c7e9dd8defbea](https://github.com/magento/magento2/commit/7cad47619fc39218f3b0fa5f178c7e9dd8defbea)
 - [d89625934957ad1d61f9634a01e14a3b40b0ca9c](https://github.com/magento/magento2/commit/d89625934957ad1d61f9634a01e14a3b40b0ca9c)
 - [7d886585b058dfd0279e08da59185a75e6703d8c](https://github.com/magento/magento2/commit/7d886585b058dfd0279e08da59185a75e6703d8c)
 - [43e7715093e5b59c026e99ed57fb22e85af6a712](https://github.com/magento/magento2/commit/43e7715093e5b59c026e99ed57fb22e85af6a712)
 - [784e73347f76d5d5e2984e4e81b3ee8f8ee29aeb](https://github.com/magento/magento2/commit/784e73347f76d5d5e2984e4e81b3ee8f8ee29aeb)
 - [962274a69c81a078399b3c3fc2aa027f34ccbcf2](https://github.com/magento/magento2/commit/962274a69c81a078399b3c3fc2aa027f34ccbcf2)
 - [ea414794ead14a83609cd19efcdaa4d6d9c14de2](https://github.com/magento/magento2/commit/ea414794ead14a83609cd19efcdaa4d6d9c14de2)
 - [14863006f3644fd892ed47fdbd1c310c3ea365c0](https://github.com/magento/magento2/commit/14863006f3644fd892ed47fdbd1c310c3ea365c0)
 - [deb55867d3faa7a7831cca7d9af77a6b8ffffa71](https://github.com/magento/magento2/commit/deb55867d3faa7a7831cca7d9af77a6b8ffffa71)
 - [dfb74d5287a6f39c4d3868635100c6df2622b23b](https://github.com/magento/magento2/commit/dfb74d5287a6f39c4d3868635100c6df2622b23b)

The fix will be available with the upcoming 2.4.1 release.
