### ISSUE TITLE
Bug: AutoloaderRegistry::getAutoloader returns array

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26479]
### Preconditions (*)
1. Cloned `magento/magento2` repository (without changes)
2. Installed Composer dependencies

### Steps to reproduce (*)
1. Configure and run Integration Tests
2. 

### Expected result (*)
1. Integration Tests should pass

### Actual result (*)
1. Randomly you get error `Error: Call to a member function findFile() on array` (`/var/www/html/lib/internal/Magento/Framework/Code/Generator/DefinedClasses.php:59`)

### Comments
Actual source of issue is in: `\Magento\Framework\Autoload\AutoloaderRegistry::getAutoloader`
https://github.com/magento/magento2/blob/a31f4a35c018ad09654e5bd5871086b73fbd3d2d/lib/internal/Magento/Framework/Autoload/AutoloaderRegistry.php#L37-L44
For some cases just `composer dump-autoload` helps, but it's not always the case.

**Comment by slavvka** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#26480 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [ab1b1de0294314503af16d5b346e5e2536542210](https://github.com/magento/magento2/commit/ab1b1de0294314503af16d5b346e5e2536542210)
 - [61bc535bc277a340fd43bf9722c331b2a08f5712](https://github.com/magento/magento2/commit/61bc535bc277a340fd43bf9722c331b2a08f5712)

The fix will be available with the upcoming 2.4.0 release.
