### ISSUE TITLE
Product url key is not transliterated anymore if already set

### ISSUE THREAD

**Issue by DanieliMi** [magento/magento2#26499]
### Preconditions (*)

1. Affected versions: 2.2.9, 2.3.3 (not verified by myself but responsible code is the same: 2.2.10, 2.4-develop)

### Steps to reproduce (*)

1. Edit a product and add "test url key" as url key
2. Save the product

This can be reproduced via rest API too by updating a product url key.

### Expected result (*)

1. Url key is transliterated to "test-url-key"

### Actual result (*)

1. Url key is still "test url key"

### Additional information

- This bug was introduced with this commit: 6f4f511822fbbcb743a7d4a8de6353d207d99429
- Responsible code in [\Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator::prepareProductUrlKey](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlPathGenerator.php#L101)
- I am not sure if reverting the line back to `return $product->formatUrlKey($urlKey === '' || $urlKey === null ? $product->getName() : $urlKey);` will break arabic urls again so we might have to find a different solution.

**Comment by christianbookpwood** [comment]
Just wanted to confirm that I manually added the fix provided by @DanieliMi and it has resolved the issue for our Magento 2.3.3 installation.

**Comment by christianbookpwood** [comment]
Is there any chance this will get fixed in Magneto 2.3.5? We just upgraded to 2.3.4 and noticed it's still a bug.

**Comment by magento-engcom-team** [comment]
Hi @DanieliMi. Thank you for your report. 
The issue has been fixed in magento/magento2#26506 by @DanieliMi in 2.4-develop branch
Related commit(s):
 - [e9300b790b9a21c3d217e56665ac1553d949adf6](https://github.com/magento/magento2/commit/e9300b790b9a21c3d217e56665ac1553d949adf6)
 - [b7dc0bec2e756534df23e216391232d45321c2fa](https://github.com/magento/magento2/commit/b7dc0bec2e756534df23e216391232d45321c2fa)
 - [4e540340bb74de1c40f3ad5c1196ffcc6057aff9](https://github.com/magento/magento2/commit/4e540340bb74de1c40f3ad5c1196ffcc6057aff9)
 - [1b3ac0661bce7cdac20343fd4a0d7b51341fbbca](https://github.com/magento/magento2/commit/1b3ac0661bce7cdac20343fd4a0d7b51341fbbca)
 - [55c226636e4f45f63cf9bdcd3b12b438bbd2f634](https://github.com/magento/magento2/commit/55c226636e4f45f63cf9bdcd3b12b438bbd2f634)
 - [27dd58a91fa285ecc846d5ec941fe573666cf6d2](https://github.com/magento/magento2/commit/27dd58a91fa285ecc846d5ec941fe573666cf6d2)

The fix will be available with the upcoming 2.4.0 release.

**Comment by alpenite-lsartor** [comment]
Hello,
are you planning to fix this is issue also in other magento2 versions prior to 2.4?
Thank you

Leonardo

**Comment by hostep** [comment]
Good point @alpenite-lsartor!
@slavvka: will https://github.com/magento/magento2/pull/26506 be backported to 2.3? It's pretty important that this happens.

**Comment by slavvka** [comment]
@alena-marchenko Could you please answer?

**Comment by hostep** [comment]
@slavvka & @alena-marchenko: it looks like this fix wasn't included in Magento 2.3.6 which is pretty bad new. Is there a chance it will get included in 2.3.7? 

I understand you don't want to backport the database migration script, but at least backport the fix to prevent new bad data to make it into the databases.
