### ISSUE TITLE
Overlay after click "OK" on alert

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#26514]
### Preconditions (*)

1. M 2.3.3

### Steps to reproduce (*)

1. On CMS edit page open media gallery
2. Click "Create Folder"
3. Type in "папка"
4. Click "OK"
5. When alert with a message "Please rename the folder using only letters, numbers, underscores and dashes." appears, click "OK"

### Expected result (*)

1. I can create another folder using only letters, numbers, underscores and dashes.

### Actual result (*)

1. The overlay
![image](https://user-images.githubusercontent.com/11827230/70134014-e406b280-168f-11ea-97ba-a5e0abf6d367.png)

**Comment by engcom-Bravo** [comment]
Hello @TomashKhamlai,

Thank you for your report. 

This issue is not reproducible on Magento 2.4-develop, so we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest 2.4-develop branch. 

Thank you for collaboration.
