### ISSUE TITLE
di:setup:compile fails with anonymous classes

### ISSUE THREAD

**Issue by YevSent** [magento/magento2#26532]
### Preconditions (*)

The current implementation of `\Magento\Setup\Module\Di\Code\Scanner\PhpScanner` does not support classes that contain anonymous classes. This leads to failures for `di:setup:compile` command. The problem that `PhpScanner` treats anonymous classes as classes that might require code generation for factories and extension attributes.

All Magento versions have this issue.

### Steps to reproduce (*)

1. Create a dummy class which contains an anonymous class, like `Magento\DummyModule\Dummy` (see a sample below)
2. Run `bin/magento setup:di:compile` CLI command

### Expected result (*)

1. Compilation is successful

### Actual result (*)

1. Compilation fails with an error `Class \Magento\DummyModule\$arg does not exist`

Sample class:
```php
namespace Magento\DummyModule;

class Dummy
{
    public function execute($arg)
    {
        return new class($arg) {
            private $arg;

            public function __construct($arg)
            {
                $this->arg = $arg;
            }

            public function serialize()
            {
                return (string) $this->arg;
            }
        };
    }
}
```

To achieve the same error as described in https://github.com/magento/magento2/issues/21555, the anonymous class should not provide a possibility to specify arguments for a constructor. In simple words, `return new class {`.

**Comment by slavvka** [comment]
Hi @joni-jones. Thank you for your report. 
The issue has been fixed in magento/magento2#26533 by @joni-jones in 2.4-develop branch
Related commit(s):
 - [fd3f2a22b8e5b2cffaf17daccc29f461c26c5f51](https://github.com/magento/magento2/commit/fd3f2a22b8e5b2cffaf17daccc29f461c26c5f51)
 - [136d5592244d05509ad0b3b9117505d8f833ddfa](https://github.com/magento/magento2/commit/136d5592244d05509ad0b3b9117505d8f833ddfa)
 - [25fd9259e72bc484f5899aa4edf3de120b66db0c](https://github.com/magento/magento2/commit/25fd9259e72bc484f5899aa4edf3de120b66db0c)
 - [e165d99f5994af39d49ed70155c003745158e5db](https://github.com/magento/magento2/commit/e165d99f5994af39d49ed70155c003745158e5db)

The fix will be available with the upcoming 2.4.0 release.
