### ISSUE TITLE
My Wish List Product not showing properly between >768px and <1023px

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/magento2#26543]
### Summary
My Wish List Product not showing properly between >768px and <1023px

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce

1. Login in frontend
2. Add 4-5 products in wishlist
3. Go to Wishlist page

### Expected result

Products should show 3 items
![expected](https://user-images.githubusercontent.com/23443991/73155872-00f4ba80-4102-11ea-8059-9700be4f2cbb.png)

### Actual result
Products show 2 products and space right side

![actual](https://user-images.githubusercontent.com/23443991/73155870-005c2400-4102-11ea-9fd0-714c0f88a6f7.png)

**Comment by hitesh-wagento** [comment]
I am working on this issue

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26543-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26543-2-4-develop.instances.magento-community.engineering/admin_6eb8](https://i-26543-2-4-develop.instances.magento-community.engineering/admin_6eb8)
Login: `f4babffa` Password: `454c09bc7e5c`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30802` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment]
Hi @hitesh-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26546 by @hitesh-wagento in 2.4-develop branch
Related commit(s):
 - [55e2e64e98583cab40b79f97e9c515c439efbe28](https://github.com/magento/magento2/commit/55e2e64e98583cab40b79f97e9c515c439efbe28)
 - [6fbdbbed12051bc306174e1f4f828c3e00ac2e05](https://github.com/magento/magento2/commit/6fbdbbed12051bc306174e1f4f828c3e00ac2e05)
 - [13b3ba7867b8c983065df4d1f19596db3e0f1015](https://github.com/magento/magento2/commit/13b3ba7867b8c983065df4d1f19596db3e0f1015)

The fix will be available with the upcoming 2.4.0 release.
