### ISSUE TITLE
Magento 2 using a jQuery version with known vulnerabilities

### ISSUE THREAD

**Issue by valugi** [magento/magento2#26547]
### Preconditions (*)

1. Magento EE ver. 2.2.8
2. I see that 2.3.x is using the same version of jQuery

### Steps to reproduce (*)
1. Install Magento
2. check jQuery version that is packed with it

### Expected result (*)
1. Have a newer version of jQuery, possibly the latest
2. Maybe having a mechanism of updating jQuery independently

### Actual result (*)
1. A security scan shows that the version of jQuery has known vulnerabilities:
- jQuery 1.12.4
- jQuery UI 1.10.4

**Comment by engcom-Bravo** [comment]
Hello @sdzhepa 

This issue looks like a feature request, can you please move this to a propper repository?

Thank you

**Comment by valugi** [comment]
hi @engcom-Bravo,
If you treat this as a feature request it will be implemented only for the future versions. But this is a bug - a security bug - for the existing versions and should be patched in 2.2 and 2.3, not in 2.4 or above.
Regards

**Comment by duffner** [comment]
@magento-engcom-team, this is a security issue.  While this ticket, could use some improved documentation, Google itself recognizes this as a security flaw. This blantent notice looks bad for Magento.  While I don’t agree it should be ported back to 2.2 versions, I do believe it should be in 2.3 as this issue presented itself in 2.3 and I’d like to see us move forward.

**Comment by onepack** [comment]
I cannot believe this is still open. Please update asap.

**Comment by DanielRuf** [comment]
>     1. A security scan shows that the version of jQuery has known vulnerabilities:
> 
> 
>     * jQuery 1.12.4

This was patched directly in the file.

I guess you mean this and a few others: https://github.com/magento/magento2/pull/22418

**Comment by DanielRuf** [comment]
>     1. Have a newer version of jQuery, possibly the latest

The newer releases break existing code.

**Comment by DanielRuf** [comment]
Also see https://github.com/magento/magento2/commit/86fdea32b19df148a4eeaad0f81bd0db68dc0cef#diff-13e016f05effe828e3d5ababa4a62a15

As no details were provided about the exact problem (which CVE IDs are not fixed in our version) I think we can close this for now.

Still, most of the code still relies on jQuery 1.x and I think there were some PRs to make code compatible with jQuery 3 but would be a breaking change then.

Additionally I host patched versions at https://github.com/DanielRuf/snyk-js-jquery-174006/ and https://github.com/DanielRuf/snyk-js-jquery-565129

**Comment by kishorkoshti** [comment]
Hi, any fix or updates available on this. Experiencing the same still.

**Comment by Eddcapone** [comment]
Q2 2021 and Magento 2.4.2 still uses jQuery 1

**Comment by onepack** [comment]
Magento 2.4.2-p1. Quick Lighthouse scan:


Library Version | Vulnerability Count | Highest Severity
-- | -- | --
jQuery@1.12.4 | 4 | Medium
jQuery UI@1.10.4 | 1 | High

**Comment by onepack** [comment]
Make it a core setting in the backend or env: 
Required jQuery version: 1/ 2/ 3
Required jQuery UI version: etc.
New stores can go for the newer versions of jquery.
Older shops with older themes and functionality that would break keep it v1.

**Comment by DanielRuf** [comment]
> Magento 2.4.2-p1. Quick Lighthouse scan:

Lighthouse outputs these depending on the detected version number. It does not detect the manual changes in the jQuery files. Please check the files in the repo, in your projekt and see my last comments regarding the fixed problems.

**Comment by onepack** [comment]
@DanielRuf Thanks. I will check. 
Do you think this would affect SEO results as Google sees it as a high risk.
Their system doesn't notice the patches.

**Comment by DanielRuf** [comment]
> Do you think this would affect SEO results as Google sees it as a high risk.

No, I don't think so. Security itself has nothing to do with offsite or onsite SEO and I am not aware of any penalties due to outdated and insecure libraries.

**Comment by DanielRuf** [comment]
> Their system doesn't notice the patches.

Correct, because Lighthouse just checks library name + library version and compares it with a table of known vulnerable versions (from Snyk).

See:
https://github.com/GoogleChrome/lighthouse/blob/2511725963e8695c302095f68cc5f6a1bc393bd2/package.json#L170
https://www.npmjs.com/package/js-library-detector
https://github.com/GoogleChrome/lighthouse/issues/10412
