### ISSUE TITLE
wrong currency exchange calculation on product page

### ISSUE THREAD

**Issue by rommelfreddy** [magento/magento2#26553]
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. create a website (DE) with the currency EUR and a tax rate so it got 19 % applied on products
2. create a website (CH) with the currency CHF and a tax rate so it got 7 % applied on products
4. Setup that all prices does already have tax included (while entered at admin)
3. Setup base currency to EUR
4. Setup price display on product pages to "incl. tax"
6. Create a product with a gross price of 35.30 EUR

### Expected result (*)

1. In the DE-Website the price will displayed on product page with 35.30 EUR (gross)
2. In the CH-Website the price will displayed on product page with 35.57 CHF (gross)
--> excepted calculation for CH:
DE-Gross / DE-Tax = DE-NET (35.30 / 1.19 = 29.66)
DE-NET * CHF-Exchangerate = CHF-Net (29.66  * 1.1133 = 33.03)
CHF-NET * CH-Tax = CHF-Gross (33.03 * 1.077 = 35.57 CHF)

### Actual result (*)

1. In the DE-Website the price will displayed on product page with 35.30 EUR (gross)
2. In the CH-Website the price will displayed on product page with 39.30 CHF (gross)
--> actual calculation for CH:
DE-Gross / CHF-Exchangerate = CH-Gross (35.30 / 1.077 = 39.30)

### Additional info
19% of 35.3 € are 6.707, thats correct. - but this is not the tax. it is only 19%
the tax will always added to the net amout. so the net amount are 100%. after you added 19% tax (of the 100% net) you have 119% (of net) --> the gross price

**Comment by rommelfreddy** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rommelfreddy. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rommelfreddy, here is your [Magento instance](https://i-26553-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26553-2-4-develop.instances.magento-community.engineering/admin_b7f0](https://i-26553-2-4-develop.instances.magento-community.engineering/admin_b7f0)
Login: `4f0c1aee` Password: `b2d61421b43e`
Instance will be terminated in up to 3 hours.

**Comment by rommelfreddy** [comment]
lets go a little bit freakier than it already is:

if you change the display of the price in the cart to "excl. and incl. tax", the price will displayed on the product page correctly.

**Comment by rommelfreddy** [comment]
@magento-engcom-team sorry, but i need to setup a second website in the instance. but i am not able to add and second base url to access the second instance. Could you help me please?

**Comment by engcom-Bravo** [comment]
Hello @romellfredy

Thank you for your report 

The tax calculation will work properly if the following is observed: 
If there is a Store, German for example, the locale should also be German

**Comment by engcom-Bravo** [comment]
Hello @rommelfreddy 

Thank you for your report

The tax calculation will work as expected if the following is observed:
If the Store is German for example
- the **Default** and **Locale** country is Germany (the same is for Switzerland)
![gefault country](https://user-images.githubusercontent.com/51680745/73451824-2cc9a780-4371-11ea-86be-1f01e06ea44b.png)

-  the created _"19% tax rule"_ is assigned to the the **Tax Rate** and the **Country** is Germany (the same is for Switzerland)
![tax_rate](https://user-images.githubusercontent.com/51680745/73452004-a497d200-4371-11ea-8dfb-1f815b6dbdd1.png)

- the ** Signed In** Customer address is Germany (the same is for Switzerland) 
![front_country](https://user-images.githubusercontent.com/51680745/73452348-651db580-4372-11ea-97c9-f04241a46b55.png)
 
If all this is observed, then the price of the Product is _35.3+19% = 41.007_ rounded to **42.01 €**
![42 007](https://user-images.githubusercontent.com/51680745/73452587-d6f5ff00-4372-11ea-8f81-2cd221e0ee88.png)

In the case of Switzerland, the price of the Product if _35.3*1.1133._
![currency_rate](https://user-images.githubusercontent.com/51680745/73452736-2fc59780-4373-11ea-842b-b3e383932ba3.png) 
and _+19%_ =**42.05** 

In your case, the tax is calculated properly. But not as you expect, probably because the Customer's address is not Switzerland. And the Tax was not applied on the product page.

Could you take a look at this on your site?

Thank you

**Comment by rommelfreddy** [comment]
Hey @engcom-Bravo
you misunderstood me.

You have to different (Magento-)Websites.
In the first website (DE) you have the following conditions:
- Tax 19 % (doesn't matter how it will achieve - easiest way is via the default shipping/invoice address)
- Currency EUR
In the second website (CH) you have the following conditions:
- Tax  7.7%  (doesn't matter how it will achieve - easiest way is via the default shipping/invoice address)
- Currency CHF

Please also compare the prices on the product detail page and the cart.

Maybe it would be also easier to understand your settings if you provide more informations about the prices (if you mean net or gross)

**Comment by engcom-Bravo** [comment]
Hello @rommelfreddy 

- Can you please clarify what Product price do you set on step 6?
![prod_price](https://user-images.githubusercontent.com/51680745/73642451-643e9980-467a-11ea-8fb8-14ba3720038e.png)
Because in expected result, you subtract 19% out of it:
_DE-Gross / DE-Tax = DE-NET (35.30 / 1.19 = 29.66)_
Does it mean that the original price of the product is 29.66 ?

- Why do you divide 35.3 by 1.19 ? 
Because: 
35.3 / 1.19 = 29.66 
but 35.3 -19% = 28.596

**Comment by rommelfreddy** [comment]
Hello @engcom-Bravo 
i inserted the gross price.

Your calculation is not correct.
19% of 35.3 € are 6.707, thats correct. - but this is not the tax. it is only 19%
the tax will always added to the net amout. so the net amount are 100%. after you added 19% tax (of the 100% net) you have 119% (of net) --> the gross price

do you understand? (but this is simple tax calculation - so you should get it ;-) )

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31177` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @rommelfreddy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-31177` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
