### ISSUE TITLE
Product Detail Page - Tier price (fixed & discount) save percentage displaying wrong calculation

### ISSUE THREAD

**Issue by srsathish92** [magento/magento2#26583]
Tier price (fixed & discount) save percentage displaying wrong calculation in product detail page. 

### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Create simple product with
	Price - $100.00
	Special price - $65.00
2. Add tier price rule
        For 2 (Qty) - Fixed $40.00
	For 3 (Qty) - Percentage 36%
3. Save the product.

### Expected result (*)
Both fixed and discount save percentage should be applied on final price
- Buy 2 for $40.00 each and save 38%
- Buy 3 for $64.00 each and save 2%

### Actual result (*)
Fixed price save percentage applied on final price (In our case special price) and Discount save percentage applied on base price.
- Buy 2 for $40.00 each and save 38%
- Buy 3 for $64.00 each and save 36%

![tier_price_rule](https://user-images.githubusercontent.com/18184256/73389491-42e85100-42fa-11ea-9d28-2082757f0632.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26583-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26583-2-4-develop.instances.magento-community.engineering/admin_9af1](https://i-26583-2-4-develop.instances.magento-community.engineering/admin_9af1)
Login: `02b8101b` Password: `b06c0c655279`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30912` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment]
@magento give me test instance

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-26583-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26583-2-4-develop.instances.magento-community.engineering/admin_2fac](https://i-26583-2-4-develop.instances.magento-community.engineering/admin_2fac)
Login: `26678bd9` Password: `08ff719378b5`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
We had discussion with @Nazar65 about fixing this issue.

There were two options:

1. Fix the calculated percentage on the product page on top of existing behavior in the admin + document it

2. Change calculation of tier prices to be working with special prices.

During discussion we found that 2nd option will affect too many magento installations that working with tier prices, so decided to go with 1st option.

What was done:
1. Created fix for calculated percentage on the product page - https://github.com/magento/magento2/pull/26584
2. Created adjustment for documentation that tier prices doesn't work with special prices - https://github.com/magento/merchdocs/pull/338

**Comment by magento-engcom-team** [comment]
Hi @srsathish92. Thank you for your report. 
The issue has been fixed in magento/magento2#26584 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [9c11369cea37527da27c63108b8e18fa3b56ee9d](https://github.com/magento/magento2/commit/9c11369cea37527da27c63108b8e18fa3b56ee9d)
 - [00317ef8f28a89c2ad7e5bf23d47beca8d9534ac](https://github.com/magento/magento2/commit/00317ef8f28a89c2ad7e5bf23d47beca8d9534ac)
 - [ecc4ef5c9f60c416ce45fc1ea10071fd30336fe8](https://github.com/magento/magento2/commit/ecc4ef5c9f60c416ce45fc1ea10071fd30336fe8)
 - [24b3fba8e2506f74cbd10bd8b9ae187c6ff8b062](https://github.com/magento/magento2/commit/24b3fba8e2506f74cbd10bd8b9ae187c6ff8b062)
 - [62f8c6c16fc116b1683ec14db311e2a9fdc0fa03](https://github.com/magento/magento2/commit/62f8c6c16fc116b1683ec14db311e2a9fdc0fa03)
 - [01104963df3d0eb91bac08194dded8070e564158](https://github.com/magento/magento2/commit/01104963df3d0eb91bac08194dded8070e564158)
 - [4680f700a448c9eb2bf2172b349c95b3b5c8a4ae](https://github.com/magento/magento2/commit/4680f700a448c9eb2bf2172b349c95b3b5c8a4ae)
 - [0216e5e80f0004f05db2a7f4ad39e86801cdf85b](https://github.com/magento/magento2/commit/0216e5e80f0004f05db2a7f4ad39e86801cdf85b)

The fix will be available with the upcoming 2.4.0 release.
