### ISSUE TITLE
MFTF: AdminReorderWithCatalogPriceTest is failing in CI process

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26607]
### Summary (*)
The error occurs on Magento GitHub repository CI validations.
![image](https://user-images.githubusercontent.com/1639941/73532313-baae9c80-441c-11ea-8fef-26d423b0a2d7.png)

### Examples (*)
* https://github.com/magento/magento2/pull/26594/checks?check_run_id=417846845

### Proposed solution
C'mon, fix it :-)

**Comment by slavvka** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#26608 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [e6a3bee7dfbf17456e768a77d78e8e9a1b5bf133](https://github.com/magento/magento2/commit/e6a3bee7dfbf17456e768a77d78e8e9a1b5bf133)
 - [e26a536d1960253dfa2242b5793a6c805413a9ca](https://github.com/magento/magento2/commit/e26a536d1960253dfa2242b5793a6c805413a9ca)
 - [075f9f4d16a723095e1a0e77599e5e56fb78796d](https://github.com/magento/magento2/commit/075f9f4d16a723095e1a0e77599e5e56fb78796d)
 - [dab9463a523d51648b36bab7bbc26364bf23f944](https://github.com/magento/magento2/commit/dab9463a523d51648b36bab7bbc26364bf23f944)
 - [fe153fbd5eccef22c562016c4cac1ba4194e8abd](https://github.com/magento/magento2/commit/fe153fbd5eccef22c562016c4cac1ba4194e8abd)
 - [c9d83d7f74c5e7472c261c7e4ec057af5989c372](https://github.com/magento/magento2/commit/c9d83d7f74c5e7472c261c7e4ec057af5989c372)
 - [148011a08aa169f11c9228797ecca6d048ae2aea](https://github.com/magento/magento2/commit/148011a08aa169f11c9228797ecca6d048ae2aea)
 - [2bdbf8b2c15873f8c0ff60bf7cfb279ce6f4039c](https://github.com/magento/magento2/commit/2bdbf8b2c15873f8c0ff60bf7cfb279ce6f4039c)
 - [8450dc970f11713342984102970ac75d7aac9fc1](https://github.com/magento/magento2/commit/8450dc970f11713342984102970ac75d7aac9fc1)
 - [a2e16f34fc028da456ab29409d686a7fbf2289da](https://github.com/magento/magento2/commit/a2e16f34fc028da456ab29409d686a7fbf2289da)
 - [e52bc2a701818967ea9a7bf79cc1b05513276178](https://github.com/magento/magento2/commit/e52bc2a701818967ea9a7bf79cc1b05513276178)
 - [548da895caa3393ce951ce0675fea398c5a1910b](https://github.com/magento/magento2/commit/548da895caa3393ce951ce0675fea398c5a1910b)
 - [ea4a31ee10de19ab2d1cddb164eac62504e2fd1c](https://github.com/magento/magento2/commit/ea4a31ee10de19ab2d1cddb164eac62504e2fd1c)
 - [b130bd0670b2190903f358ca036005020407cefb](https://github.com/magento/magento2/commit/b130bd0670b2190903f358ca036005020407cefb)
 - [fc6fd6274bbc522cde5fd577556ae98f04de3d98](https://github.com/magento/magento2/commit/fc6fd6274bbc522cde5fd577556ae98f04de3d98)
 - [a9fccdb8aa3f1a0bfd4346aad45f7f2242faee6c](https://github.com/magento/magento2/commit/a9fccdb8aa3f1a0bfd4346aad45f7f2242faee6c)
 - [ed51b40914b99562ed9125c225694b3bd48af418](https://github.com/magento/magento2/commit/ed51b40914b99562ed9125c225694b3bd48af418)
 - [8df79b03bbc58fddbf168fa27c596b89c17f0f88](https://github.com/magento/magento2/commit/8df79b03bbc58fddbf168fa27c596b89c17f0f88)
 - [322e9d81a2be741f1e27bc790e646138e655d33a](https://github.com/magento/magento2/commit/322e9d81a2be741f1e27bc790e646138e655d33a)
 - [f16c97e29628849a722649fba2381080a5e6994d](https://github.com/magento/magento2/commit/f16c97e29628849a722649fba2381080a5e6994d)
 - [5a202f8efce57abfb90c5c2eaa7da0d224a39aea](https://github.com/magento/magento2/commit/5a202f8efce57abfb90c5c2eaa7da0d224a39aea)
 - [3eb92f5e8346a9fdbc22ed8a87a404130858d16b](https://github.com/magento/magento2/commit/3eb92f5e8346a9fdbc22ed8a87a404130858d16b)
 - [81cbfa2f496848471522bab6516a513d54df755e](https://github.com/magento/magento2/commit/81cbfa2f496848471522bab6516a513d54df755e)
 - [b5141f47c4a271f8410cc540e6409a76c7f4559d](https://github.com/magento/magento2/commit/b5141f47c4a271f8410cc540e6409a76c7f4559d)
 - [d3eaa9e6cfeaa23a5d6d5a0de564056b886e32eb](https://github.com/magento/magento2/commit/d3eaa9e6cfeaa23a5d6d5a0de564056b886e32eb)
 - [3588ab3ce389eed7377b505ff7ce30a465a28e39](https://github.com/magento/magento2/commit/3588ab3ce389eed7377b505ff7ce30a465a28e39)

The fix will be available with the upcoming 2.4.0 release.
