### ISSUE TITLE
MFTF: StorefrontApplyPromoCodeDuringCheckoutTest is failing in CI process

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26612]
### Summary (*)
![image](https://user-images.githubusercontent.com/1639941/73539942-e5a1ec00-442e-11ea-8e5f-55348be1d605.png)

Issue occurs randomly, when Magento instance is running slower. It's related with the fact, that Assertion does not wait for Loading Mask to disappear.

### Examples (*)
- https://github.com/magento/magento2/pull/26611/checks?check_run_id=419074708

### Proposed solution
Extend ActionGroup with `<waitForLoadingMaskDisappear>`

**Comment by slavvka** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#26614 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [c13b83fd26c3368c8536995caf918f4372e56b52](https://github.com/magento/magento2/commit/c13b83fd26c3368c8536995caf918f4372e56b52)

The fix will be available with the upcoming 2.4.0 release.

**Comment by lbajsarowicz** [comment]
Thanks @slavvka for closing that :-)
