### ISSUE TITLE
Create/change one catalog price rule result in all catalog product price and catalog fulltext re-index

### ISSUE THREAD

**Issue by zkliouel** [magento/magento2#26616]
### **Preconditions**

1. Magento 2.3.3
2. Indexing mode set to Update by Schedule

### **Steps to reproduce**
Create/change one a single catalogRule
Run the index cron in order to generate Mviews (e.g. magento cron:run --group=index)

### **Expected result**
invalidate catalogRule  index
reindex catalog_product_price and catalogsearch_fulltext using  products that match the catalogRule

### **Actual result**
Invalidate catalogRule & catalog_product_price & catalogsearch_fulltext indexes due to depencencies

Why do not only reindex products that matching the catalogRule ?
I mean instead of invalidate catalog_product_price and catalogsearch_fulltext that trigger a full reindex of all products, whe we don't only launch reindex in afterSave method of https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/CatalogRule/Model/Rule.php#L589 for only matching products ids ?

**Comment by zkliouel** [comment]
HI @magento-engcom-team  and @m2-assistant
On a vanilla Magento instantce i can reproduce this issue

Best regard

**Comment by swathishs** [comment]
Hello @zkliouel,
Thank you for your report.
This issue is duplicate to #https://github.com/magento/magento2/issues/25687 and already discussed many times.
You can track the conversation from the above issue id.
The issue  will be transferred to the feature requests repository- [(Comment)](  https://github.com/magento/magento2/issues/25687#issuecomment-558106200)
