### ISSUE TITLE
Add/Edit Product | Duplicating ".00" zeros on saves

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#26676]
### Preconditions (*)
1. Magento 2.3.1
2. php 7.2

### Steps to reproduce (*)
1. Open Admin
2. Change to Arabic Store ( it only happens there )
from the top right click admin -Account settings
change the **Interface locale** to _Arabic (Egypt)_ for example 
3. Go to Catalog/Products
4. Edit a Product
5. Save Multiple Times and you will see the price added (.00) on each Save you make

### Expected result (*)
1. on Add/Edit it should not add (.00) more than once

### Actual result (*)
1. on Add/Edit it is Adding (.00) to price on each additional save action
![arabic_price](https://user-images.githubusercontent.com/51680745/73749343-e1920900-4763-11ea-947c-6e93c5b7b4b1.png)

![2020-06-22_11-49-18](https://user-images.githubusercontent.com/3409584/85314226-ca3b8a00-b47e-11ea-9c53-a598fd3d1e62.jpg)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31085` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by odubovyk** [comment]
Add comment "Internal Magento team is working on this issue right now.

**Comment by magento-engcom-team** [comment]
Hi @salehawal, @odubovyk. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [76e011a981d2ab38e6d23763e55dd53c2859fbcf](https://github.com/magento/magento2/commit/76e011a981d2ab38e6d23763e55dd53c2859fbcf)

The fix will be available with the upcoming `2.4.1` release.
