### ISSUE TITLE
ORDER BY has two similar conditions

### ISSUE THREAD

**Issue by Usik2203** [magento/magento2#26708]
### Preconditions (*)

Magento 2.4-develop

### Steps to reproduce (*)

1. We have products in category
2. Go to app/code/Magento/Catalog/Block/Product/ListProduct.php and add 
<img width="1045" alt="Screenshot 2020-02-05 at 11 20 52" src="https://user-images.githubusercontent.com/13517181/73828488-fcb75400-4809-11ea-9768-9498a9beff4e.png">
3. Go to page on category 

### Expected result (*)

1.   condition ``cat_index``.``position`` `asc` shouldn't be double in ORDER BY

### Actual result (*)

1. We can see  two similar conditions in ORDER BY 
<img width="1426" alt="Screenshot 2020-02-05 at 11 25 51" src="https://user-images.githubusercontent.com/13517181/73828767-89621200-480a-11ea-9d37-5c8c32df6c30.png">

This conditon to ORDER BY was added in app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php
<img width="1339" alt="Screenshot 2020-02-05 at 11 38 56" src="https://user-images.githubusercontent.com/13517181/73829774-325d3c80-480c-11ea-814f-726cadb4385c.png">

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31175` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your report. 
The issue has been fixed in magento/magento2#27263 by @vasilii-b in 2.4-develop branch
Related commit(s):
 - [1e1ebd3a9ee69038841f41ebe8771b6a1fa700d6](https://github.com/magento/magento2/commit/1e1ebd3a9ee69038841f41ebe8771b6a1fa700d6)
 - [df35ddac0dacf30be6547a7cbad113c3ed6ed3fc](https://github.com/magento/magento2/commit/df35ddac0dacf30be6547a7cbad113c3ed6ed3fc)
 - [b8163347447bc8ee6636440c1d4ab522cc950af2](https://github.com/magento/magento2/commit/b8163347447bc8ee6636440c1d4ab522cc950af2)
 - [a61d92ae503d098e461bc53a1e684df3c5fdef97](https://github.com/magento/magento2/commit/a61d92ae503d098e461bc53a1e684df3c5fdef97)

The fix will be available with the upcoming 2.4.0 release.
