### ISSUE TITLE
Installing magento from composer install all the whole github repository

### ISSUE THREAD

**Issue by ericmorand** [magento/magento2#26706]
Hi guys,

When using the recommended syntax to install magento, the whole github repository is downloaded and installed locally:

`composer create-project --repository=https://repo.magento.com/ magento/project-community-edition [...]`

This means that we get not needed and not requested files in our environments: dev, build and deploy scripts, less sources, documentations, github templates, README...

We don't want all of these on any of our servers - even on local environment, we don't need and don't want them.

Is the recommended way of installing Magento wrong? Or is it a bug with mangento installation itself?

**Comment by hostep** [comment]
It's expected because a lot of people like to have all those development requirements.

What is not expected is that a bunch of those development requirements are also getting installed when providing the `--no-dev` flag.
But we already have issues for that:
- https://github.com/magento/magento2/issues/5262
- https://github.com/magento/magento2/issues/8971
- https://github.com/magento/magento2/issues/22359

Feel free to create extra issues for anything you noticed which is not specified by the tickets above.
I'm going to close this issue however, since the question is too generic and not specific enough.

**Comment by ericmorand** [comment]
@hostep , thanks a lot for the heads-up. Good to see that the issue is known and considered. :)
