### ISSUE TITLE
Discount is not applying on Shipping Amount for the rule 'Buy X get Y free (discount amount is Y)'.

### ISSUE THREAD

**Issue by webkul-dhananjay** [magento/magento2#26723]
### Preconditions (*)
Magento version:2.3.4 
Php version 7.2.14

### Steps to reproduce (*)
1. Create a rule for  'Buy X get Y free (discount amount is Y)
2.  Apply to Shipping Amount set to yes.

### Expected result (*)
Shipping amount should be $10
as discount should apply on shipping amount of 1 qty of item.

### Actual result (*)
Discount is not applying on Shipping Amount of 1 qty of item.

--------------------------------------------------------------------
![Screenshot (1)](https://user-images.githubusercontent.com/50043146/73913836-04e0c380-48de-11ea-9a2c-a6c6b8964214.png)

-----------------------------------------------------------
![Screenshot (2)](https://user-images.githubusercontent.com/50043146/73913863-16c26680-48de-11ea-906b-b3bb2ffcb7b6.png)

**Comment by ajijshekh123** [comment]
Give me @magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-26723-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26723-2-4-develop.instances.magento-community.engineering/admin_662e](https://i-26723-2-4-develop.instances.magento-community.engineering/admin_662e)
Login: `13d5fb0a` Password: `9e1d0074f746`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @webkul-dhananjay,
The discount amount is not displayed when product qty is 1. 
Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31173` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-31173).

**Comment by magento-engcom-team** [comment]
Hi @webkul-dhananjay. Thank you for your report. 
The issue has been fixed in magento/magento2#28839 by @engcom-Echo in 2.4-develop branch
Related commit(s):
 - [6005a92fa59f40294cd0074cb586f99b06f6b54e](https://github.com/magento/magento2/commit/6005a92fa59f40294cd0074cb586f99b06f6b54e)
 - [ed1a21e3f9cf14b4c5cf805eeea90881fb1c559a](https://github.com/magento/magento2/commit/ed1a21e3f9cf14b4c5cf805eeea90881fb1c559a)
 - [3b33889c69b24a71f7d118c3c139902a34b9cb5b](https://github.com/magento/magento2/commit/3b33889c69b24a71f7d118c3c139902a34b9cb5b)

The fix will be available with the upcoming 2.4.1 release.
