### ISSUE TITLE
Cart Event Observers have no effect when item quantity is not changed.

### ISSUE THREAD

**Issue by ghost** [magento/magento2#26753]
A customer Observer for the event "checkout_cart_update_items_after" is having seemingly no affect when I click "Update Shopping Cart" on the main cart page, unless I change the item quantity.

I have exposed some new select inputs on the cart item rows, and this data is successfully passed via POST which I can pick up in the Observer without issue.

If I click the button after having only changed that custom option, and leave the quantity alone, after my Observer executes and the page reloads, no change is made to the custom option in the database.

As soon as this process is done but the quantity is also changed, after my Observer executes, the custom option data is updated correctly.

**Comment by mrtuvn** [comment]
@paul-gene may be this event will help you 'checkout_cart_save_before'

**Comment by engcom-Golf** [comment]
Hi @paul-gene thank you for you report, this is expected behavior as qty will not saved if they not greater then 0 , feel free to create a feature request https://github.com/magento/community-features/issues
![DeepinScreenshot_select-area_20200303152314](https://user-images.githubusercontent.com/51681547/75779638-a71b8c00-5d62-11ea-846e-5f4160df883b.png)
![DeepinScreenshot_select-area_20200303152351](https://user-images.githubusercontent.com/51681547/75779698-c1556a00-5d62-11ea-8142-e9890b0e4345.png)
![DeepinScreenshot_select-area_20200303152405](https://user-images.githubusercontent.com/51681547/75779699-c1ee0080-5d62-11ea-9167-9a6de8647401.png)

**Comment by paul-gene** [comment]
You have misunderstood the issue. The cart observer should be able to handle updating other quote item object properties, but can't unless you change the qty. You should be able to leave the qty as is but still change cart item data in the observer.

**Comment by engcom-Golf** [comment]
@paul-gene could you please describe exact steps to reproduce ? because when i leave the same qty, observert take this quantity and save to the quote

**Comment by paul-gene** [comment]
> @paul-gene could you please describe exact steps to reproduce ? because when i leave the same qty, observer take this quantity and save to the quote

Imagine you want to add some custom data to the cart item, from the main cart, but don't want to update the qty.

The data is exposed via an input box under each line item. You enter something for one of the items, and hit the big "update cart" button.

The observer will not react to the change, as the qty has not been changed.

**Comment by engcom-Golf** [comment]
@paul-gene, exactly, when i have the same  qty and not changed, observer fires every time when i press `update cart` button
![DeepinScreenshot_select-area_20200305122848](https://user-images.githubusercontent.com/51681547/75972783-ac044b00-5edc-11ea-97e1-8e6d501ecf9a.png)
![DeepinScreenshot_select-area_20200305122858](https://user-images.githubusercontent.com/51681547/75972784-ac9ce180-5edc-11ea-99c9-b749d65eb73f.png)
