### ISSUE TITLE
Undefined variable $type in Product-Link Management

### ISSUE THREAD

**Issue by angelobono** [magento/magento2#26800]
Undefined variable $type in Product-Link Management

### Preconditions (*)
1. Magento Community Version 2.3.2 and current branch 2.4-develop

### Steps to reproduce (*)
1. Create two products, for example with SKU 1234 and SKU 5678
2. Create a product link 1234 to 5678 with Magento\Catalog\Model\ProductLink\Management->setProductLinks
3. Create a product link 5678 to 1234 with Magento\Catalog\Model\ProductLink\Management->setProductLinks

### Expected result (*)
1. New product link 1234 to 5678
2. New product link 5678 to 1234

### Actual result (*)
1. New product link 1234 to 5678
2. Exception: Notice: Undefined variable: type in /.../vendor/magento/module-catalog/Model/ProductLink/Management.php on line 94

**Comment by magento-engcom-team** [comment]
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31437` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @angelobono. Thank you for your report. 
The issue has been fixed in magento/magento2#26979 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [84eb1fcb8b51763a3d65933a54440a05b1f17d37](https://github.com/magento/magento2/commit/84eb1fcb8b51763a3d65933a54440a05b1f17d37)
 - [55d1f18446affc4e4861ea9e5d85024e14f2c9e6](https://github.com/magento/magento2/commit/55d1f18446affc4e4861ea9e5d85024e14f2c9e6)
 - [bb150058b5cf74ccd9f9325a0e1aa18f96f2e46d](https://github.com/magento/magento2/commit/bb150058b5cf74ccd9f9325a0e1aa18f96f2e46d)

The fix will be available with the upcoming 2.4.0 release.
