### ISSUE TITLE
Position sort does not work in GraphQl.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#26817]
### Preconditions (*)

1. Magento 2.3.4 Open Source

### Steps to reproduce (*)

1. Install demo data
2. Assign positions to all products in the Watches category (id: 6)
![Screenshot from 2020-02-11 16-31-53](https://user-images.githubusercontent.com/22170051/74251394-5dec9500-4cec-11ea-9738-f5d9c0ad1fb7.png)
3. Run the following GraphQl Query. 
```
query category {
  categoryList(
    filters: {ids: {eq: "6"}}
  ) {
    products(
      sort: {
        position: ASC
      }
    ) {
      items {
        id
      }
      total_count
    }
  }
}
```

### Expected result (*)

```
{
    "data": {
        "categoryList": [
            {
                "products": {
                    "items": [
                        {
                            "id": 43
                        },
                        {
                            "id": 41
                        },
                        {
                            "id": 39
                        },
                        {
                            "id": 37
                        },
                        {
                            "id": 36
                        },
                        {
                            "id": 38
                        },
                        {
                            "id": 40
                        },
                        {
                            "id": 42
                        },
                        {
                            "id": 44
                        }
                    ],
                    "total_count": 9
                }
            }
        ]
    }
}
```

### Actual result (*)

```
{
    "data": {
        "categoryList": [
            {
                "products": {
                    "items": [
                        {
                            "id": 36
                        },
                        {
                            "id": 37
                        },
                        {
                            "id": 38
                        },
                        {
                            "id": 39
                        },
                        {
                            "id": 40
                        },
                        {
                            "id": 41
                        },
                        {
                            "id": 42
                        },
                        {
                            "id": 43
                        },
                        {
                            "id": 44
                        }
                    ],
                    "total_count": 9
                }
            }
        ]
    }
}
```

**Comment by Hexmage** [comment]
It looks like the issue is caused by the products collection not having been joined with the catalog_category_position table. Because it can't find the category position it falls back onto entity_id.

**Comment by Hexmage** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @Hexmage. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Hexmage, here is your [Magento instance](https://i-26817-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26817-2-4-develop.instances.magento-community.engineering/admin_fcea](https://i-26817-2-4-develop.instances.magento-community.engineering/admin_fcea)
Login: `138cdecc` Password: `3b27a7255b44`
Instance will be terminated in up to 3 hours.

**Comment by Hexmage** [comment]
Confirmed to not work on 2.4-develop

**Comment by Hexmage** [comment]
This used to work on 2.3.3, if you manually added position to the graphql.schema for ProductSortInput, but it looks like the new filter/ search system has broken this.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31477` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Hexmage** [comment]
Doing the following resolves the issue, but it isn't a nice/good solution. This adds the category filterGroup to the searchCriteria, because position sort requires a join on the category index.

\Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\ProductSearch::getList

```
/**
     * Get list of product data with full data set. Adds eav attributes to result set from passed in array
     *
     * @param SearchCriteriaInterface $searchCriteria
     * @param SearchResultInterface $searchResult
     * @param array $attributes
     * @return SearchResultsInterface
     */
    public function getList(
        SearchCriteriaInterface $searchCriteria,
        SearchResultInterface $searchResult,
        array $attributes = []
    ): SearchResultsInterface {

+       $filterGroup = $searchResult->getSearchCriteria()->getFilterGroups()[0];
+       $searchCriteria->setFilterGroups([$filterGroup]);

        /** @var Collection $collection */
        $collection = $this->collectionFactory->create();

        //Join search results
        $this->getSearchResultsApplier($searchResult, $collection, $this->getSortOrderArray($searchCriteria))->apply();

        $this->collectionPreProcessor->process($collection, $searchCriteria, $attributes);
        $collection->load();
        $this->collectionPostProcessor->process($collection, $attributes);

        $searchResults = $this->searchResultsFactory->create();
        $searchResults->setSearchCriteria($searchCriteria);
        $searchResults->setItems($collection->getItems());
        $searchResults->setTotalCount($searchResult->getTotalCount());
        return $searchResults;
    }
```

**Comment by nrkapoor** [comment]
Thank you for reporting this issue. I have created an internal JIRA item and will address this issue as part of the 2.4 release. I will update the issue once the fix is available in 2.4 development.

**Comment by danielrenaud** [comment]
Thanks for your contribution. We started working on this internally.

**Comment by magento-engcom-team** [comment]
Hi @Hexmage, @nrkapoor, @cpartica, @shikhamis11. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [6d814c3325d830ac8ebb0e1253718751d28f123a](https://github.com/magento/magento2/commit/6d814c3325d830ac8ebb0e1253718751d28f123a)
 - [ef13e6b341d837967ff6461ca8186e81417fcff0](https://github.com/magento/magento2/commit/ef13e6b341d837967ff6461ca8186e81417fcff0)
 - [fdbf8ad927543151f83ba39bcf66fe3de4df9c8c](https://github.com/magento/magento2/commit/fdbf8ad927543151f83ba39bcf66fe3de4df9c8c)
 - [ed76a247b3eab1c57cea1ad926df3c8a6c692ae9](https://github.com/magento/magento2/commit/ed76a247b3eab1c57cea1ad926df3c8a6c692ae9)
 - [ab2f9d2bb51765b4ff825cb5114cf14a6b128d85](https://github.com/magento/magento2/commit/ab2f9d2bb51765b4ff825cb5114cf14a6b128d85)
 - [dfcf474d83c05620e6fa3010ae25632cb820174e](https://github.com/magento/magento2/commit/dfcf474d83c05620e6fa3010ae25632cb820174e)
 - [aad59c10c0011f36815e541b1e9feb2ebbd6c582](https://github.com/magento/magento2/commit/aad59c10c0011f36815e541b1e9feb2ebbd6c582)
 - [190e0511a322cd5f260b6d11b1d4e2e679070eef](https://github.com/magento/magento2/commit/190e0511a322cd5f260b6d11b1d4e2e679070eef)
 - [b7dce0e92038ee8e895115c0a21f13cc6d2a49f7](https://github.com/magento/magento2/commit/b7dce0e92038ee8e895115c0a21f13cc6d2a49f7)
 - [7a742ff7d669559a5f430f3c50d839de4a3080e0](https://github.com/magento/magento2/commit/7a742ff7d669559a5f430f3c50d839de4a3080e0)
 - [5ef3a835682f6851f24fce488746128381f8fdac](https://github.com/magento/magento2/commit/5ef3a835682f6851f24fce488746128381f8fdac)
 - [94bb238f7e3ee2f0e1f9b06a34751068bc4eb396](https://github.com/magento/magento2/commit/94bb238f7e3ee2f0e1f9b06a34751068bc4eb396)
 - [55280a6d453f1565a8f8c65021a1535e4ab3a6b3](https://github.com/magento/magento2/commit/55280a6d453f1565a8f8c65021a1535e4ab3a6b3)
 - [e9756816e409b0fd6438a517972c43f7360b57c5](https://github.com/magento/magento2/commit/e9756816e409b0fd6438a517972c43f7360b57c5)
 - [61b8d6bde7b0a0ac8c97f192babd69f30abe2917](https://github.com/magento/magento2/commit/61b8d6bde7b0a0ac8c97f192babd69f30abe2917)
 - [5d73d1d69b51e3c556892fa654b6609255b793c2](https://github.com/magento/magento2/commit/5d73d1d69b51e3c556892fa654b6609255b793c2)
 - [52c56c0876b9a08b94a62c24acd93471eff94a60](https://github.com/magento/magento2/commit/52c56c0876b9a08b94a62c24acd93471eff94a60)

The fix will be available with the upcoming `2.4.0` release.

**Comment by radub** [comment]
@Hexmage the workaround (https://github.com/magento/magento2/issues/26817#issuecomment-591429899) worked on M2.3.4 but is no longer working on M2.3.5 - I'm looking into it as M2.4 is really far away.

**Comment by shivnibble** [comment]
@khaled-badenjki We've used the position sort solution for 2.3.4-p1 and have found that the value entered changes after saving - usually as if there's a multiplier being applied, but occasionally resulting in a negative value. Any insight?

I'm also curious if anyone has managed to apply the position sorting fix to the carousel product sliders as well?

**Comment by denissdubinin** [comment]
Solution provided by @khaled-badenjki works correctly only if you are not using anchor categories.
To fix the problem, change join type from `inner` to `left` in `CatalogCategoryProductJoinProcessor.php` class.
