### ISSUE TITLE
Low stock report showing disabled products

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26838]
The low stock report becomes pretty useless pretty fast unless you delete products. We store disabled product for history and the chance that they may come back in stock.

There is no way to do a report and filter out the disabled products.

This means you have to go through A LOT of non-active products in the low stock report which makes it completely unusable.

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Add products
2. Set product count to 0
3. Disable some of the products
4. Run low stock report

### Expected result (*)

Either remove the disabled products from the report or have the ability to filter them out.

### Actual result (*)

Unable to remove disabled products or filter them out. Making the report useless since there are a lot of old products that don't need to be reviewed for low stock.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31479` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#26862 by @Mohamed-Asar in 2.4-develop branch
Related commit(s):
 - [6c8aa11b9637c1ac717c64335c3c15b6a46187b1](https://github.com/magento/magento2/commit/6c8aa11b9637c1ac717c64335c3c15b6a46187b1)
 - [b6f49b9b7b511311ae6f9cbc33277dda96ddac25](https://github.com/magento/magento2/commit/b6f49b9b7b511311ae6f9cbc33277dda96ddac25)

The fix will be available with the upcoming 2.4.0 release.
