### ISSUE TITLE
es_US Spanish (United States ) Locale is not supported in Magento 2.3.4

### ISSUE THREAD

**Issue by karthi6116** [magento/magento2#26843]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1.Create a language pack for the spanish united states with locale as es_US
2. Now run Static-content deploy for the es_US localization with
 php bin/magento setup:static-content:deploy -f --theme="Magento/blank" es_US
3. We are getting an error 
es_US argument has invalid value, please run info:language:list for list of available locales

### Expected result (*)

1. Theme should be deployed for the es_US localization.

### Actual result (*)

1. es_US argument has invalid value, please run info:language:list for list of available locales

**Comment by vincent-le89** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vincent-le89. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vincent-le89, here is your [Magento instance](https://i-26843-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26843-2-4-develop.instances.magento-community.engineering/admin_f7f3](https://i-26843-2-4-develop.instances.magento-community.engineering/admin_f7f3)
Login: `1f44e808` Password: `8bcd94ad2674`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @karthi6116. Thank you for your report. 
The issue has been fixed in magento/magento2#26857 by @vincent-le89 in 2.4-develop branch
Related commit(s):
 - [bab4fb677ea110d614d434937264fc107ac75c1d](https://github.com/magento/magento2/commit/bab4fb677ea110d614d434937264fc107ac75c1d)
 - [fb71138cc42493df673d5b7440154db0021485e3](https://github.com/magento/magento2/commit/fb71138cc42493df673d5b7440154db0021485e3)
 - [2b1bce54aa452aea6ccc9580469e7e25017f0df7](https://github.com/magento/magento2/commit/2b1bce54aa452aea6ccc9580469e7e25017f0df7)

The fix will be available with the upcoming 2.4.0 release.
