### ISSUE TITLE
Configurable product displays a price of $0.00 when no options are selected

### ISSUE THREAD

**Issue by matthew-muscat** [magento/magento2#26854]
### Preconditions (*)

1. "Catalog -> Inventory -> Display Out of Stock Products" is set to "Yes"

### Steps to reproduce (*)

1. Ensure that the system configuration of "Catalog -> Inventory -> Display Out of Stock Products" is set to a value of "Yes"
2. Navigate to a configurable product page, and view the product page with no options selected
3. Observe the frontend displaying "As low as $0"

### Expected result (*)

1. The product price displayed by default on the configurable product should be that of the lowest associated item price

### Actual result (*)

1. A price of $0.00 appears on the Magento frontend

**Suspected Cause**
This appears to be due to a bug in the `\Magento\ConfigurableProduct\Model\ResourceModel\Product\StockStatusBaseSelectProcessor` — specifically, https://github.com/magento/magento2/blob/15269d971985685906f1494c3b476fbcb727fc2f/app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/StockStatusBaseSelectProcessor.php#L48

It appears that when this option is enabled, a join on the stock table is required, however the conditional appears to be the opposite of what is required.

The "CatalogInventory" module has a similar processor logic, but it's implementation is using the appropriate if statement condition — https://github.com/magento/magento2/blob/15269d971985685906f1494c3b476fbcb727fc2f/app/code/Magento/CatalogInventory/Model/ResourceModel/Product/StockStatusBaseSelectProcessor.php#L53

**Comment by matthew-muscat** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @matthew-muscat. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @matthew-muscat, here is your [Magento instance](https://i-26854-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26854-2-4-develop.instances.magento-community.engineering/admin_2915](https://i-26854-2-4-develop.instances.magento-community.engineering/admin_2915)
Login: `da2f163b` Password: `8fe10e518844`
Instance will be terminated in up to 3 hours.

**Comment by matthew-muscat** [comment]
This looks to be related to Multi Source Inventory — a similar issue is described over at https://community.magento.com/t5/Magento-2-x-Technical-Issues/Default-Configurable-Product-Pricing-states-0-00-after-setting/td-p/141223 and raised in https://github.com/magento/inventory/pull/2528

Upon further investigation, it would appear this issue was fixed in magento/inventory via https://github.com/magento/inventory/commit/1bcd2f6e09fc951865594425d736603dbf762add

**Comment by stephan-cream** [comment]
The question now however, is in which Magento release this fix will be applied.
Applying the changes through a patch is fine, but it would still be nice to know when this version of the MSI module is incorporated in Magento itself.

**Comment by Javiercc78** [comment]
It doesn't seem to be fixed. Magento 2.3.4.

Continue 0 without selecting an option

**Comment by titechnologies** [comment]
Is there any fix for this in Magento 2.3.5 ?

**Comment by michi-p** [comment]
I'm still facing this problem in Magento 2.4.2-p1.

**Comment by reinier-tula** [comment]
Hi everyone,
Hope the below can help you all (login first):

-Go to vendor/magento/module-catalog/Model/ResourceModel/Product/Website/SelectProcessor.php
Note that function is adding a join to include only products linked to an specific website.
-Add "echo $select->__toString();" just before the return line in that function.
-Open the product page of any of the products showing $0. You will see the query at the top of the page.
Note the last inner join in the query is like "INNER JOIN `catalog_product_website` AS `pw` ON pw.product_id = child.row_id AND pw.website_id = here your website-ID "

*That query is used to return all the child products of a configurable prod linked to an specific website. This is been called during the process of getting the final price of a configurable prod. So Magento basically needs to pull all child and keep the lowest price from them.

THE PROBLEM: The query is returning an empty array of child prods because is using in above join catalog_product_website.product_id AND child.row_id instead of "child.entity_id" (catalog_product_website->product_id is foreign key of  sequence_product->sequence_value AND sequence_product->sequence_value is the catalog_product_entity->entity_id)

THE FIX: In the same path/function I mentioned at the beginning replace "$linkField" in the query for "entity_id" and create a patch with that change. Also remember to remove the "echo" statement we added for testing.

Now reload the product page (if you have Full page cache enable then clean it) and you should see the product price.
This problem showing $0 also happens of course in the category page. To fix it in the category page just reindex.

Hope this helps you.
Hopefully the Magento team can review this fix and want to add it in an official PATCH.

**Comment by jpkileaf** [comment]
@reinier-tula If its happending for specific products, can we do any fix from database level ?

**Comment by dbashyal** [comment]
Issue still exists in Magento 2.4.6-P4 as well.

**Comment by panosdotk** [comment]
Issue still exists in version 2.4.6-P4. But happens only to specific products for some reason.

**Comment by uramos4me** [comment]
Same as @panosdotk and all the guys here. Still happens in AC-2.4.6-p3 for specific products.
