### ISSUE TITLE
Add grouped product with individual quantity to cart using rest api

### ISSUE THREAD

**Issue by manish-sirvi** [magento/magento2#26909]
### Summary (*)

Currently i'm using  **POST** **/V1/carts/mine/items** rest api endpoint to add products to carts.
So for grouped product if use the payload as mentioned in devdoc then this picks the default quantity which is used in adminhtml to add those products to cart.

So if i want to add custom quantity for each product to add to cart, i am unable to use "product_option" in payload for grouped product to specify individual quantity as i do for other product types.

### Examples (*)

This is the payload mentioned on swagger for above api to add products to cart.
<code>
{
  "cartItem": {
    "item_id": 0,
    "sku": "string",
    "qty": 0,
    "name": "string",
    "price": 0,
    "product_type": "string",
    "quote_id": "string",
    "product_option": {
      "extension_attributes": {
        "custom_options": [
          {
            "option_id": "string",
            "option_value": "string",
            "extension_attributes": {
              "file_info": {
                "base64_encoded_data": "string",
                "type": "string",
                "name": "string"
              }
            }
          }
        ],
        "bundle_options": [
          {
            "option_id": 0,
            "option_qty": 0,
            "option_selections": [
              0
            ],
            "extension_attributes": {}
          }
        ],
        "configurable_item_options": [
          {
            "option_id": "string",
            "option_value": 0,
            "extension_attributes": {}
          }
        ],
        "downloadable_option": {
          "downloadable_links": [
            0
          ]
        },
        "giftcard_item_option": {
          "giftcard_amount": "string",
          "custom_giftcard_amount": 0,
          "giftcard_sender_name": "string",
          "giftcard_recipient_name": "string",
          "giftcard_sender_email": "string",
          "giftcard_recipient_email": "string",
          "giftcard_message": "string",
          "extension_attributes": {}
        }
      }
    },
    "extension_attributes": {
      "negotiable_quote_item": {
        "item_id": 0,
        "original_price": 0,
        "original_tax_amount": 0,
        "original_discount_amount": 0,
        "extension_attributes": {}
      }
    }
  }
}
</code>

How am i supposed to add grouped product with individual quantity specified for the products in group product.
### Proposed solution

There should be another key in "product_option" for grouped products to specify quantity.
Well if i use **PUT** **/V1/carts/mine/items** endpoint to update the quantity for products using item id after adding them, then i get the desired result.
So this approach is difficult to follow on mobile end and is also very slow.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32042` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @manish-sirvi. Thank you for your report. 
The issue has been fixed in magento/magento2#27845 by @shawnabramson in 2.4-develop branch
Related commit(s):
 - [dcc6381a921ee5225e46ef05b6d9e2386e663a1c](https://github.com/magento/magento2/commit/dcc6381a921ee5225e46ef05b6d9e2386e663a1c)
 - [de1f6262870dd84dddac687377b8edca59f266a0](https://github.com/magento/magento2/commit/de1f6262870dd84dddac687377b8edca59f266a0)
 - [8d2c2804038efd2f6fdd5690d62a6f180440c71b](https://github.com/magento/magento2/commit/8d2c2804038efd2f6fdd5690d62a6f180440c71b)
 - [e9fa0a8baa9672796a7a99a51b3586f802dcded2](https://github.com/magento/magento2/commit/e9fa0a8baa9672796a7a99a51b3586f802dcded2)
 - [d5160db59db56b85bcfaf4938b035c94a574bb0d](https://github.com/magento/magento2/commit/d5160db59db56b85bcfaf4938b035c94a574bb0d)
 - [8b141e149719e417417e2db6363475f23a9958ed](https://github.com/magento/magento2/commit/8b141e149719e417417e2db6363475f23a9958ed)
 - [bb9c1e29d91d079f3fd5d0079da2289c0ed7ae16](https://github.com/magento/magento2/commit/bb9c1e29d91d079f3fd5d0079da2289c0ed7ae16)
 - [3bcdd48f050c21fb3a7650b7df00c6f09f9624bf](https://github.com/magento/magento2/commit/3bcdd48f050c21fb3a7650b7df00c6f09f9624bf)
 - [7f49335b686c892271ea4e0ad6d529357a1b847a](https://github.com/magento/magento2/commit/7f49335b686c892271ea4e0ad6d529357a1b847a)
 - [3626d9c91e33316ec0d69411c1bed87bf6a4fa9e](https://github.com/magento/magento2/commit/3626d9c91e33316ec0d69411c1bed87bf6a4fa9e)
 - [cc0c94263c7c73e8f84adaa5ea0045211f5e76b7](https://github.com/magento/magento2/commit/cc0c94263c7c73e8f84adaa5ea0045211f5e76b7)
 - [74709d2e4fcaec39fd1726c005e0efe69d0992a8](https://github.com/magento/magento2/commit/74709d2e4fcaec39fd1726c005e0efe69d0992a8)
 - [fa4c7b8daee4a500ccbaf637243c41a1112011ba](https://github.com/magento/magento2/commit/fa4c7b8daee4a500ccbaf637243c41a1112011ba)
 - [24c27a4042145dfdf0dd1645410dcac13462f99e](https://github.com/magento/magento2/commit/24c27a4042145dfdf0dd1645410dcac13462f99e)
 - [be84eb128f9fdd7caf3fdaee2d8d34a7f11c694d](https://github.com/magento/magento2/commit/be84eb128f9fdd7caf3fdaee2d8d34a7f11c694d)
 - [c93616132bc8c3e0d934e217ab98f83607cf04b2](https://github.com/magento/magento2/commit/c93616132bc8c3e0d934e217ab98f83607cf04b2)
 - [7af13d7a51a3e3314e1f0fb91252a182299b7b19](https://github.com/magento/magento2/commit/7af13d7a51a3e3314e1f0fb91252a182299b7b19)
 - [4240a6b0e1f92b6f3b90acfa4ccf684f13405430](https://github.com/magento/magento2/commit/4240a6b0e1f92b6f3b90acfa4ccf684f13405430)
 - [768b3051e6fadddc544edbac1e2877d3c165d0f6](https://github.com/magento/magento2/commit/768b3051e6fadddc544edbac1e2877d3c165d0f6)
 - [4aa5527722a89b03e746d854b1da4f2dedb08570](https://github.com/magento/magento2/commit/4aa5527722a89b03e746d854b1da4f2dedb08570)
 - [0ace0c314266ef112f8c0c860fb537a0ca64c8df](https://github.com/magento/magento2/commit/0ace0c314266ef112f8c0c860fb537a0ca64c8df)
 - [bdfe7ec4a63c88d271848b5c6963f71a7473b1ca](https://github.com/magento/magento2/commit/bdfe7ec4a63c88d271848b5c6963f71a7473b1ca)
 - [769653abe032196d84328bb79fa2e55128e342a4](https://github.com/magento/magento2/commit/769653abe032196d84328bb79fa2e55128e342a4)

The fix will be available with the upcoming 2.4.3 release.
