### ISSUE TITLE
Guest visitor e-mail in checkout kicks off password field visibility

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#26903]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. add items to cart and reach checkout , use a unregistered e-mail in e-mail field and fill address data
2. go back to cart page (or to any other page as long outside from checkout page)
3. then go back to checkout page and see that it presents password fields for authenticating for e-mail that is not registered

### Expected result (*)

1. add items to cart and reach checkout , use a unregistered e-mail in e-mail field and fill address data
2. go back to cart page (or to any other page as long outside from checkout page)
3. then go back to checkout page and see that password fields are not displayed since e-mail is not jet registered 

### Actual result (*)

1. when reaching checkout and adding a unregistered e-mail and then visiting other pages and going back to checkout it shows password fields for unregistered visitors 

2. this is happening cause of https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/js/view/form/element/email.js#L196 and was introduced with https://github.com/magento/magento2/commit/0861a3077135f40d9728dc1e6cfec3ab7387f3a3

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-26903-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26903-2-4-develop.instances.magento-community.engineering/admin_3b68](https://i-26903-2-4-develop.instances.magento-community.engineering/admin_3b68)
Login: `6cb9f73d` Password: `b0ea869be18f`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31655` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mrtuvn** [comment]
i'm working on this issue. Can you guys assign me on this

**Comment by ProkopovVitaliy** [comment]
i'm working on this issue.

**Comment by hannes011** [comment]
is there any solution for this issue yet?

**Comment by ProkopovVitaliy** [comment]
> is there any solution for this issue yet?

You can try https://github.com/magento/magento2/pull/27691.

**Comment by magento-engcom-team** [comment]
Hi @speedupmate. Thank you for your report. 
The issue has been fixed in magento/magento2#27691 by @ProkopovVitaliy in 2.4-develop branch
Related commit(s):
 - [a9ca0f632da13071b9f44f706fda8740809e29d9](https://github.com/magento/magento2/commit/a9ca0f632da13071b9f44f706fda8740809e29d9)
 - [fc1a6c5264353b9e5adc9fb84851ea2d1b4c063f](https://github.com/magento/magento2/commit/fc1a6c5264353b9e5adc9fb84851ea2d1b4c063f)
 - [c412681b7f9fac6e70120cf51ada319dabd510bd](https://github.com/magento/magento2/commit/c412681b7f9fac6e70120cf51ada319dabd510bd)
 - [42803c8591267991f0bb475d374560cbc1d7ec89](https://github.com/magento/magento2/commit/42803c8591267991f0bb475d374560cbc1d7ec89)

The fix will be available with the upcoming 2.4.2 release.
