### ISSUE TITLE
Tax rate Zip/Post range and check box alignment issue

### ISSUE THREAD

**Issue by renard123** [magento/magento2#26917]
### Preconditions (*)
Magento: 2.3.4

### Steps to reproduce (*)
Admin -> Store -> Taxes -> Tax Zones and Rates -> Add new -> Tax rate Zip/Post range

### Expected result (*)
Should be in same line

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/74803585-73bd1400-5303-11ea-83c9-700eeade9670.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31657` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#26932 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [08219e880c142e7bcbfbf6320d8422db5c6354de](https://github.com/magento/magento2/commit/08219e880c142e7bcbfbf6320d8422db5c6354de)
 - [82e4623dfdd5a2bdb99952d9a53a2b1981c1974c](https://github.com/magento/magento2/commit/82e4623dfdd5a2bdb99952d9a53a2b1981c1974c)
 - [ff45a23bcad5b7c9c17a4831bedf2c83bc0f58ba](https://github.com/magento/magento2/commit/ff45a23bcad5b7c9c17a4831bedf2c83bc0f58ba)

The fix will be available with the upcoming 2.4.0 release.
