### ISSUE TITLE
Fatal error on calling ImageFactory::create() for product_page_image_large

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26973]
### Preconditions (*)
1. Magento 2.3.2

### Steps to reproduce (*)
1. Create a product with no image
2. Use `product_page_image_large` in your layout

### Expected result (*)
1. Placeholder displayed

### Actual result (*)
1. Fatal error: `PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Block\Product\ImageFactory::getRatio() must be of the type integer, null given`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31806` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#26974 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [806b4f9dfa63b5319fa3891c9bab911516b21747](https://github.com/magento/magento2/commit/806b4f9dfa63b5319fa3891c9bab911516b21747)
 - [74a03861375b1b1e8fa974b2eceb7677c691fcb7](https://github.com/magento/magento2/commit/74a03861375b1b1e8fa974b2eceb7677c691fcb7)

The fix will be available with the upcoming 2.4.0 release.
