### ISSUE TITLE
MFTF: Use Magento Cron for reindexing after creating data

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#26989]
### Preconditions (*)
1. Magento 2.4
2. Magento Functional Testing Framework 2.6

Issue: `indexer:reindex` is used for reindexing or no reindexing happens.

### Steps to reproduce (*)
N/A

### Expected result (*)
1. Magento Cron is used for reindexing
2. Reindex happens after each `<createData` group

### Actual result (*)
1. `<magentoCli` with `indexer:reindex` and `cache:flush` is used

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#26990 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [3590b44be005762c32ebf3fb7e3e0f4e28055e58](https://github.com/magento/magento2/commit/3590b44be005762c32ebf3fb7e3e0f4e28055e58)
 - [48a297f579904d68f9965a88d4eb29c5ab1f5881](https://github.com/magento/magento2/commit/48a297f579904d68f9965a88d4eb29c5ab1f5881)

The fix will be available with the upcoming 2.4.0 release.
