### ISSUE TITLE
Add New ratings Is active and checkbox alignment issue

### ISSUE THREAD

**Issue by renard123** [magento/magento2#26992]
Add New ratings Is active and checkbox alignment issue

### Preconditions (*)
Magento: 2.3.4

### Steps to reproduce (*)
- Admin -> Stores -> Attributes -> Ratings -> Add new ratings

### Expected result (*)
It should display in same line

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/75133818-2b866300-5702-11ea-8379-34abfd595b75.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31802` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ravi-chandra3197** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197, here is your [Magento instance](https://i-26992-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26992-2-4-develop.instances.magento-community.engineering/admin_9463](https://i-26992-2-4-develop.instances.magento-community.engineering/admin_9463)
Login: `e71c3d5f` Password: `30e757358794`
Instance will be terminated in up to 3 hours.

**Comment by ansari-krish** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#27014 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [08319582702be82b594225db5b66b873a87d18e7](https://github.com/magento/magento2/commit/08319582702be82b594225db5b66b873a87d18e7)
 - [4ddae72b876595c768a991a76e6cf058dd87f1f6](https://github.com/magento/magento2/commit/4ddae72b876595c768a991a76e6cf058dd87f1f6)
 - [97642b5f28da27bec827c906dc2a096aa95fb502](https://github.com/magento/magento2/commit/97642b5f28da27bec827c906dc2a096aa95fb502)
 - [ee00b989feee1ecf0412abe9d860cb0320fb5f26](https://github.com/magento/magento2/commit/ee00b989feee1ecf0412abe9d860cb0320fb5f26)

The fix will be available with the upcoming 2.4.0 release.
