### ISSUE TITLE
Sitemap.xml refers only tot non existent sitemaps.

### ISSUE THREAD

**Issue by arnoldfiesta** [magento/magento2#27025]
Hello,

I noticed that our developer created and submitted our sitemap to search console but somehow search console didn't find any links.
So i checked it and this is the only thing that is in the sitemap.

"
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>
https://www.feestwinkelfiesta.nl/domains/feestwinkelfiesta.nl/public_html/sitemap-1-1.xml
</loc>
<lastmod>2020-02-26T09:03:27+00:00</lastmod>
</sitemap>
<sitemap>
<loc>
https://www.feestwinkelfiesta.nl/domains/feestwinkelfiesta.nl/public_html/sitemap-1-2.xml
</loc>
<lastmod>2020-02-26T09:03:27+00:00</lastmod>
</sitemap>
<sitemap>
<loc>
https://www.feestwinkelfiesta.nl/domains/feestwinkelfiesta.nl/public_html/sitemap-1-3.xml
</loc>
<lastmod>2020-02-26T09:03:27+00:00</lastmod>
</sitemap>
</sitemapindex> "

```
So it refers somehow to sitemaps that aren't generated and don't exist.
I tried generating another sitemap but it made the same setup.

What i would need is a sitemap that refers to the category pages, product pages and all other content. How should i go about handling this?

**Comment by mattijv** [comment]
@arnoldfiesta I believe you are facing [the same problem as we did](https://github.com/magento/magento2/issues/24946). The partial sitemaps generated by a cron run will include the folder path to the Magento root folder. The issue is fixed in a future version of Magento, but you can temporarily fix it by adding a command to `cd` into the Magento root before
running the cron:run command in crontab. E.g.
```
* * * * * cd /path/to/magento/root && (normal magento cron run command here)
