### ISSUE TITLE
Custom module not loadable

### ISSUE THREAD

**Issue by Pinimichu** [magento/magento2#2702]
Hi all,
I have installed Magento2 on my local VM, after a few problems successfully.
I tried to implement a custom module with help of some tutorials but the module was never available under Store->Configuration->Advanced->Advanced.
I did add my module to app/etc/config.xml manually (I know, not recommended) and with the php bin/magento setup:upgrade command as well but nothing happened. The module does not appear in the terminal output. (Tutorial from here: http://www.venustheme.com/how-to-create-magento-2-module/)
Even with the sample modules from here https://github.com/magento/magento2-samples I had the same problem so I think it makes no sense to post my config files.

Is this a known issue and is there a possible solution?

**Comment by mazhalai** [comment]
@Pinimichu did you create a `registration.php` file for your module? Like this https://github.com/magento/magento2/blob/develop/app/code/Magento/AdminNotification/registration.php

**Comment by Pinimichu** [comment]
@mazhalai Yes, I did. And in the example module which has the same problem on my system the registration.php file is also included.

**Comment by mazhalai** [comment]
I tried the code, not all of it, but for basic module recognition. You can try with only `etc/module.xml` and `registration.php` within `app/code/<vendorName>/<moduleName>` and then running `bin/magento setup:upgrade`. The module should then show up in `config.php` not `config.xml` as mentioned in the tutorial. 

Additionally, there is no `composer.json`, in `module.xml` and `routes.xml` the noNamespaceSchemaLocation needs to be in urn format and many other typos. I would suggest following this [sample module](https://github.com/magento/magento2-samples/tree/master/sample-module-webflow) (which is now up to date) 

Closing since this is not an issue.
