### ISSUE TITLE
Add image lazy loading

### ISSUE THREAD

**Issue by tdgroot** [magento/magento2#27032]
### Description (*)

In many situations, catalog lists can contain many images, while most of them remain under the first fold. 

When running an audit using Lighthouse, it tells us the following.
![image](https://user-images.githubusercontent.com/1165302/75351451-780ba300-58a8-11ea-8f4e-cc1481dd0787.png)

So we need to add the `loading="lazy"` attribute to the images on the catalog list. This attribute is supported on the following browsers ([source](https://caniuse.com/#feat=loading-lazy-attr)):
- [Chrome >= 76](https://blog.chromium.org/2019/10/automatically-lazy-loading-offscreen.html)
  - Edge >= 79
  - Opera >= 64
  - Android Browser >= 80
  - Chrome for Android >= 80
- [Firefox >= 75](https://www.ghacks.net/2020/02/15/firefox-75-gets-lazy-loading-support-for-images/) 

In Chromium's aforementioned blog post, it seems that lazy loading is enabled for all websites on Chrome Android browsers with Lite Mode enabled.

### Expected behavior (*)

Better performance for catalog pages. This is achieved by adding the `loading="lazy"` attribute to the `image_with_borders.phtml` template. 

### Benefits

Better performance for both users and Lighthouse reports.

### Additional information

Not for now

**Comment by magento-engcom-team** [comment]
Hi @tdgroot. Thank you for your report. 
The issue has been fixed in magento/magento2#27033 by @tdgroot in 2.4-develop branch
Related commit(s):
 - [c00cef40fffb3b60d13077ee3d40dbde38e3cc4c](https://github.com/magento/magento2/commit/c00cef40fffb3b60d13077ee3d40dbde38e3cc4c)
 - [1a7977570c2638a33c8cc90b253b061fc934fe2d](https://github.com/magento/magento2/commit/1a7977570c2638a33c8cc90b253b061fc934fe2d)
 - [182a47423a3f2a00daac739bb19072416fc75e89](https://github.com/magento/magento2/commit/182a47423a3f2a00daac739bb19072416fc75e89)
 - [0bd7a87110248a4efbc8cdb612e3c42ce9475942](https://github.com/magento/magento2/commit/0bd7a87110248a4efbc8cdb612e3c42ce9475942)
 - [56fde6c7a3e4d7a3e506e10b78523a8b988bf779](https://github.com/magento/magento2/commit/56fde6c7a3e4d7a3e506e10b78523a8b988bf779)
 - [463c46072512b41d71bc13192ffbb5640c5ea394](https://github.com/magento/magento2/commit/463c46072512b41d71bc13192ffbb5640c5ea394)

The fix will be available with the upcoming 2.4.0 release.
