### ISSUE TITLE
Images no longer responsive

### ISSUE THREAD

**Issue by GrimLink** [magento/magento2#27040]
### Preconditions (*)

Since Magento 2.3.4 (commit https://github.com/magento/magento2/commit/d0ad63cca0b8e29b86b29c72608d034658d244a5) the height auto has been removed.
this clearly was not tested as all images on on the Magento front-end break and are distorted thanks to the size.

### Steps to reproduce (*)

View any image in Magento 2.3.4.
for example the logo.

### Expected result (*)

Images should be responsive.

### Actual result (*)

_Same as Expected result_

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31988` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @GrimLink. Thank you for your report. 
The issue has been fixed in magento/magento2#27041 by @GrimLink in 2.4-develop branch
Related commit(s):
 - [691d7bb275846d028262f21775259186a3152357](https://github.com/magento/magento2/commit/691d7bb275846d028262f21775259186a3152357)
 - [6209f3515d7dac92d23ad528dd0afdf94901641c](https://github.com/magento/magento2/commit/6209f3515d7dac92d23ad528dd0afdf94901641c)
 - [bf78c2c811fad6cf39fd5ffe5c6f127a2265a716](https://github.com/magento/magento2/commit/bf78c2c811fad6cf39fd5ffe5c6f127a2265a716)
 - [7e096c26f8278994df520b102311e62582a668cc](https://github.com/magento/magento2/commit/7e096c26f8278994df520b102311e62582a668cc)

The fix will be available with the upcoming 2.4.0 release.
