### ISSUE TITLE
Reordering customizable items

### ISSUE THREAD

**Issue by andypieters** [magento/magento2#2704]
Reordering an order with the same product but with different size/color, results in the product being added once, with a quantity of 2.

For instance:
I ordered: 
1. Beaumont Summit Kit Color: Red, Size: M, Quantity: 1
2. Beaumont Summit Kit Color: Yellow, Size: M, Quantity: 1

Reordering results in:
1. Beaumont Summit Kit Color: Red, Size: M, Quantity: 2

**Comment by NadiyaS** [comment]
Hi @andypieters,
this bug is really reproducible on 2.0.7 version. 
It has been fixed already and develop branch does not have this issue.
You can upgrade your code from develop branch right now or wait until next release.
Feel free to reopen this issue if you have the same problem on next release version.
