### ISSUE TITLE
BUG: Category Repository get()'s argument `store_id` does not work

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27044]
### Description
The implementation of `$storeId` support was never finished.

### Preconditions (*)
1. Magento `2.4-develop`

### Steps to reproduce (*)
1. Create 2 stores
  1. `default` with ID `1`
  1. `extra` with ID `2`
1. Create Category with `url_key` value: `category-1` (let's assume it's ID is `333`)
1. Open Category edit and change scope to `extra` store
1. Change `url_key` to value `some-magic-key`
1. Create class that use `CategoryRepositoryInterface`
1. Execute `$categoryRepository->get(333, 2)`

Data is properly saved in the MySQL table:
![image](https://user-images.githubusercontent.com/1639941/75400597-03fce980-5900-11ea-8256-e8bf14f8b364.png)

### Expected result (*)
1. Category data with `url_key` = `some-magic-key` is returned

### Actual result (*)
1. Category data with `url_key` = `category-1` is returned

### Related issues
1. https://github.com/magento/magento2#12881

### Not related issues
1. Please **not** treat it as related to magento/magento2#8897: That one is related with EAV error on saving attributes when saved with API.

**Comment by vincent-le89** [comment]
Hi @lbajsarowicz 

I can't reproduce this issue on version 2.4-develop. Please take a look at my record: https://vimeo.com/394117462

**Comment by lbajsarowicz** [comment]
Let me verify that, as I also covered that with integration test and... Isolated, that problem does not occur.

**Comment by lbajsarowicz** [comment]
Problem is actually related to internal cache storage.
It's not related to Repository but to the fact, that it does not update cache after save.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27048 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [2d15e9107418f04626ef021451774cdc438f1b42](https://github.com/magento/magento2/commit/2d15e9107418f04626ef021451774cdc438f1b42)
 - [8ad33f504b11976a4faa53c9024767a740e6bc44](https://github.com/magento/magento2/commit/8ad33f504b11976a4faa53c9024767a740e6bc44)

The fix will be available with the upcoming 2.4.0 release.
