### ISSUE TITLE
Recently viewed products in Luma theme does not fit on screen

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#27058]
Using the "recently viewed products" widget on mobile will break the viewport and forcing sidescrolling.

The problem is even worse when using translated "add to cart" that make the button longer.

### Preconditions (*)

1. Magento 2.3.3
2. Luma theme
3. Mobile view

### Steps to reproduce (*)

1. Add a new widget for "Recently viewed products"
2 .Select Layout update "All pages" and container "Sidebar Main"
3. Visit some products in mobile view until the widget appears in mobile view

### Expected result (*)

Each product should wrap on a new line to fit the add to cart button, not be on a 2x grid.

### Actual result (*)

The add to cart goes outside the viewport, and the images overlap the previous product.

![image](https://user-images.githubusercontent.com/1741593/75476634-390a4a00-599b-11ea-8047-1032ec9c5b78.png)

If you have a language with longer text than "add to cart" the effect will be worse:

![image](https://user-images.githubusercontent.com/1741593/75476733-6820bb80-599b-11ea-83f8-bc98cf634933.png)

**Comment by akash2008** [comment]
I am working on this issue.

**Comment by anerishah1** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @anerishah1. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @anerishah1, here is your [Magento instance](https://i-27058-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27058-2-4-develop.instances.magento-community.engineering/admin_c1c4](https://i-27058-2-4-develop.instances.magento-community.engineering/admin_c1c4)
Login: `3ba68ba1` Password: `7960a0b63f0a`
Instance will be terminated in up to 3 hours.

**Comment by anerishah1** [comment]
Verified issue on latest instance 
![27058](https://user-images.githubusercontent.com/50940094/75604629-bc917b80-5b00-11ea-97a3-fe058d0f6171.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32029` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#27572 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [d7cf1881141fd855ff79f611a31ea2570726bdc3](https://github.com/magento/magento2/commit/d7cf1881141fd855ff79f611a31ea2570726bdc3)
 - [9c8143329ca5d22d7fc7b29f329f6f49467752ca](https://github.com/magento/magento2/commit/9c8143329ca5d22d7fc7b29f329f6f49467752ca)
 - [4b64f33e755ca94363f01528c7b6fe01e41b9d67](https://github.com/magento/magento2/commit/4b64f33e755ca94363f01528c7b6fe01e41b9d67)
 - [5f0c02b8294b4cc779edee8041b9e4ff841bdfca](https://github.com/magento/magento2/commit/5f0c02b8294b4cc779edee8041b9e4ff841bdfca)
 - [581ab1f9c6fc6d47985670c9da89a567d7fc01a7](https://github.com/magento/magento2/commit/581ab1f9c6fc6d47985670c9da89a567d7fc01a7)
 - [a4935e30f2b83aeb0abe20c666a879f86c7a3728](https://github.com/magento/magento2/commit/a4935e30f2b83aeb0abe20c666a879f86c7a3728)
 - [ce431d39136ecb01039ead268c255057a620c641](https://github.com/magento/magento2/commit/ce431d39136ecb01039ead268c255057a620c641)

The fix will be available with the upcoming 2.4.0 release.
