### ISSUE TITLE
BUG: `getDefaultLimitPerPageValue` returns value that is not available

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27089]
### Preconditions (*)
![image](https://user-images.githubusercontent.com/1639941/76430296-72d24c00-63b0-11ea-9b39-3b7d1b75bd62.png)

As a Store Administrator, you are able to provide the **Products per Page on Grid Allowed Values** and **Products per Page on Grid Default Value**. There is no verification, so you can accidentally set the default value to be one of the unavailable options.
 
### Steps to reproduce (*)
1. Change `catalog/frontend/grid_per_page_values` to `1,2,5` using CLI
1. Change `catalog/frontend/grid_per_page` to `12`
1. Get the value of `catalog/frontend/grid_per_page_values` in your Template

### Expected result (*)
1. Configuration should return only allowed values, so we expect to return one of the available values (`1`,`2` or `5`)

### Actual result (*)
1. Configuration returns value that is not allowed - value of `12`

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @okorshenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33644` were created

**Issue Available**: @okorshenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27093 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [17236cc014ab718161e0cf446ce40f4eb8d27d9e](https://github.com/magento/magento2/commit/17236cc014ab718161e0cf446ce40f4eb8d27d9e)
 - [381ab640c0039652e93c2be24f0a9bf6be9a883e](https://github.com/magento/magento2/commit/381ab640c0039652e93c2be24f0a9bf6be9a883e)
 - [778fbfbe8bd2740713762220f61eac07e34deedb](https://github.com/magento/magento2/commit/778fbfbe8bd2740713762220f61eac07e34deedb)
 - [d3962f2e82532829522e5cf68122b92c27932a02](https://github.com/magento/magento2/commit/d3962f2e82532829522e5cf68122b92c27932a02)
 - [aec01d871608abbd17167ee141a0be3e358de683](https://github.com/magento/magento2/commit/aec01d871608abbd17167ee141a0be3e358de683)

The fix will be available with the upcoming 2.4.0 release.
