### ISSUE TITLE
In Floating cart delete pop-up, When user click on out side of OK button than button color is changed.

### ISSUE THREAD

**Issue by dipeshrangani** [magento/magento2#27095]
### Preconditions (*)

1. Magento2.4-develop

### Steps to reproduce (*)

1. Add to cart product
2. Goto mini cart and click on remove product

### Expected result (*)

![button-solution](https://user-images.githubusercontent.com/20924623/75606190-4eed4b80-5b10-11ea-887d-b488f3adf85d.png)

### Actual result (*)

![button-issue](https://user-images.githubusercontent.com/20924623/75606198-5e6c9480-5b10-11ea-9d17-c6c74368d9b9.png)

**Comment by samikshakrish** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @samikshakrish, here is your [Magento instance](https://i-27095-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27095-2-4-develop.instances.magento-community.engineering/admin_fbc4](https://i-27095-2-4-develop.instances.magento-community.engineering/admin_fbc4)
Login: `47f2fa4f` Password: `801f48968dbe`
Instance will be terminated in up to 3 hours.

**Comment by samikshakrish** [comment]
This could be consider as an improvement.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32030` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hi @dipeshrangani. Thank you for your report.
This is not an issue, We can consider as improvement.

**Comment by slavvka** [comment]
Hi @dipeshrangani. Thank you for your report. 
The issue has been fixed in magento/magento2#28083 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [d7cf1881141fd855ff79f611a31ea2570726bdc3](https://github.com/magento/magento2/commit/d7cf1881141fd855ff79f611a31ea2570726bdc3)
 - [77a4e8c44e1ee901d77aa8d6680fcd5365cd376d](https://github.com/magento/magento2/commit/77a4e8c44e1ee901d77aa8d6680fcd5365cd376d)
 - [6b8fc4c55272229164fde82ddbd631f771f302d7](https://github.com/magento/magento2/commit/6b8fc4c55272229164fde82ddbd631f771f302d7)
 - [facbe37f9f51eb315bc5da1fb3c5000d743057ff](https://github.com/magento/magento2/commit/facbe37f9f51eb315bc5da1fb3c5000d743057ff)
 - [1ef8a517089ff132a7bb526194999ae83247ce50](https://github.com/magento/magento2/commit/1ef8a517089ff132a7bb526194999ae83247ce50)
 - [6e8190662497a8e248c05d92b8763886637be5f3](https://github.com/magento/magento2/commit/6e8190662497a8e248c05d92b8763886637be5f3)
 - [03a2908769ad60c5cd5b1a5262aeab092417fe6a](https://github.com/magento/magento2/commit/03a2908769ad60c5cd5b1a5262aeab092417fe6a)
 - [8c0eff01d09dbea47a3af3afbd0f75bae2a89c82](https://github.com/magento/magento2/commit/8c0eff01d09dbea47a3af3afbd0f75bae2a89c82)
 - [0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41](https://github.com/magento/magento2/commit/0e84ed4214d5a7bafdabf99dcaa45e2f54bdac41)
 - [63550be4ba9097cb1ceac4cc787632d330ec0ea1](https://github.com/magento/magento2/commit/63550be4ba9097cb1ceac4cc787632d330ec0ea1)
 - [e3975c6b6461c0b1e1bce318cae04f4622f17bd7](https://github.com/magento/magento2/commit/e3975c6b6461c0b1e1bce318cae04f4622f17bd7)
 - [b285342bbf4a0a23f962edc84db825a815fc55ff](https://github.com/magento/magento2/commit/b285342bbf4a0a23f962edc84db825a815fc55ff)
 - [1b8199afd1ec5efe782b06e29f9b3216e4589b7d](https://github.com/magento/magento2/commit/1b8199afd1ec5efe782b06e29f9b3216e4589b7d)
 - [b8e26ce83d737387a40715297e7ade605458266c](https://github.com/magento/magento2/commit/b8e26ce83d737387a40715297e7ade605458266c)
 - [cc3f6a08396a6ea56de5d0e46932d20f730ea69e](https://github.com/magento/magento2/commit/cc3f6a08396a6ea56de5d0e46932d20f730ea69e)
 - [628f7d5b6b9691c2fcbc17e1dbe1cca22fea9a1e](https://github.com/magento/magento2/commit/628f7d5b6b9691c2fcbc17e1dbe1cca22fea9a1e)

The fix will be available with the upcoming 2.4.0 release.
