### ISSUE TITLE
Newsletter Input width issue.

### ISSUE THREAD

**Issue by premprakashprajapati** [magento/magento2#27099]
Newsletter Input width issue.

### Preconditions (*)

Magento 2.3.4

1. When enter wrong email input width increased.

### Steps to reproduce (*)

1. Enter invalid email address in footer newletter.

### Expected result (*)

 ![image](https://user-images.githubusercontent.com/56711366/75606735-dab5a680-5b15-11ea-8c81-94007ca0f992.png)

### Actual result (*)

 ![image](https://user-images.githubusercontent.com/56711366/75606731-cb365d80-5b15-11ea-9893-27586db0c997.png)

![issues_27099](https://user-images.githubusercontent.com/3409584/80736109-48129300-8ad7-11ea-980b-767de26dc6a7.gif)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32031` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-27099-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27099-2-4-develop.instances.magento-community.engineering/admin_b61e](https://i-27099-2-4-develop.instances.magento-community.engineering/admin_b61e)
Login: `e417b1bf` Password: `498cd1875ac9`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @premprakashprajapati. Thank you for your report. 
The issue has been fixed in magento/magento2#27106 by @dipeshrangani in 2.4-develop branch
Related commit(s):
 - [706eee57d2fbd1d8105f09655d35a1e53c8c93bc](https://github.com/magento/magento2/commit/706eee57d2fbd1d8105f09655d35a1e53c8c93bc)
 - [017d9de10b507c7db9f4ca040d7b0ed85be32ac6](https://github.com/magento/magento2/commit/017d9de10b507c7db9f4ca040d7b0ed85be32ac6)
 - [723d310cfc6f9fe9b30912e30d11f7b67cd73142](https://github.com/magento/magento2/commit/723d310cfc6f9fe9b30912e30d11f7b67cd73142)

The fix will be available with the upcoming 2.4.1 release.
