### ISSUE TITLE
MFTF: Test names are not following Best Practices (`Test` suffix)

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27117]
### Preconditions (*)
Test names should follow `{Area}` + `{What test does}` + `Test` pattern.
There are tests in Magento 2 that does not follow that pattern.

### Steps to reproduce (*)
N/A

### Expected result (*)
N/A

### Actual result (*)
N/A

**Comment by lbajsarowicz** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, here is your [Magento instance](https://i-27117-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27117-2-4-develop.instances.magento-community.engineering/admin_c3b0](https://i-27117-2-4-develop.instances.magento-community.engineering/admin_c3b0)
Login: `5f3b575d` Password: `e5623bb9c2bb`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27118 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [b6b69a6af9347e2f18930a7edc6388513c17b1e6](https://github.com/magento/magento2/commit/b6b69a6af9347e2f18930a7edc6388513c17b1e6)
 - [da8dfc2697639ad170fced8fea2fe40ad2165edc](https://github.com/magento/magento2/commit/da8dfc2697639ad170fced8fea2fe40ad2165edc)
 - [4f2da6f6c526ba6ca0bb92a93e00e52678db5b07](https://github.com/magento/magento2/commit/4f2da6f6c526ba6ca0bb92a93e00e52678db5b07)
 - [1045eb8a0cad9fef1502bfdf2de818e77df1fbe4](https://github.com/magento/magento2/commit/1045eb8a0cad9fef1502bfdf2de818e77df1fbe4)
 - [db38991b7c8e1738021d435defbdc9214eff2d65](https://github.com/magento/magento2/commit/db38991b7c8e1738021d435defbdc9214eff2d65)

The fix will be available with the upcoming 2.4.0 release.
