### ISSUE TITLE
Share Wishlist Email: Image Logic Issue

### ISSUE THREAD

**Issue by mtbottens** [magento/magento2#27124]
### Preconditions (*)

1. 2.4-develop
2. Sample Data Installed
3. Configuration: Stores > Configuration > Sales > Checkout > Shopping Cart > Configurable Product Image = "Product Thumbnail Itself"

### Steps to reproduce (*)

1. Add Olivia 1/4 Zip Light Jacket (Size = Medium, Color = Black) to wishlist
2. Navigate to wishlist page, observe that the product thumbnail shows the simple product image (Black)
3. Click the "Share Wishlist" button
4. Fill out form on the Share Wishlist page to configure the emails to share to, and an optional message
5. View the email sent from Magento
6. Observe that the product thumbnail is not respecting the configuration, (showing configurable product image)

### Expected result (*)

1. The share wishlist email should display the same image as the wishlist page in magento

### Actual result (*)

1. The share wishlist email does not show the expected product image

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-27124-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27124-2-4-develop.instances.magento-community.engineering/admin_59ff](https://i-27124-2-4-develop.instances.magento-community.engineering/admin_59ff)
Login: `38031562` Password: `9cbcb15bd9cc`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32119` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @mtbottens. Thank you for your report. 
The issue has been fixed in magento/magento2#27125 by @mtbottens in 2.4-develop branch
Related commit(s):
 - [854761db86de5a2bb960fc66c0b9922dd792f423](https://github.com/magento/magento2/commit/854761db86de5a2bb960fc66c0b9922dd792f423)
 - [12ae6e594d260f39f316cf65d4de66516dbdb200](https://github.com/magento/magento2/commit/12ae6e594d260f39f316cf65d4de66516dbdb200)
 - [76e61aecca249855bf9f45c25672bd800121e58e](https://github.com/magento/magento2/commit/76e61aecca249855bf9f45c25672bd800121e58e)
 - [428605d04e815c782cfbe20922f244970d153006](https://github.com/magento/magento2/commit/428605d04e815c782cfbe20922f244970d153006)
 - [b2d07939fa03becf51151ebc49597614a71d3397](https://github.com/magento/magento2/commit/b2d07939fa03becf51151ebc49597614a71d3397)

The fix will be available with the upcoming 2.4.0 release.
