### ISSUE TITLE
Cannot create shipment for remaining items

### ISSUE THREAD

**Issue by MLucaciu** [magento/magento2#27141]
### Preconditions (*)

1. Magento Open Source 2.3.3

### Steps to reproduce (*)

1. Create an order, where at least one product has a Quantity of 2. 
    - Example of order items : - 3 x product_1
                                              - 1 x product_2
                                              - 1 x product_3

2. Create an invoice, shipment and creditmemo for:
                                             -  2 x product_1 
                                             - 1 x product_2 
                                             - 1 x product_3

Example screenshot:
![bug-m2](https://user-images.githubusercontent.com/26298317/75781648-42623080-5d66-11ea-993f-bf4f29a1a403.png)

### Expected result (*)

1. It is possible to create a shipment for the remaining item.

### Actual result (*)

1. The Ship button disappeared, making it impossible to create a shipment for the remaining item.
![bug-m](https://user-images.githubusercontent.com/26298317/75781873-aa187b80-5d66-11ea-8977-75b884fd3647.png)

**Comment by MLucaciu** [comment]
yes

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32179` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rdudhara** [comment]
@magento 

I am working on it

**Comment by magento-engcom-team** [comment]
Hi @MLucaciu. Thank you for your report. 
The issue has been fixed in magento/magento2#27414 by @niravkrish in 2.4.0-develop branch
Related commit(s):
 - [8e4c3bfa7fd638e679d9dec94912f9f5f2dcd35e](https://github.com/magento/magento2/commit/8e4c3bfa7fd638e679d9dec94912f9f5f2dcd35e)
 - [ec55a63792a3075bc7fa79abe3a064a0150aef7c](https://github.com/magento/magento2/commit/ec55a63792a3075bc7fa79abe3a064a0150aef7c)
 - [b7e99de8ae795a8c7eac936965016133bccc77f6](https://github.com/magento/magento2/commit/b7e99de8ae795a8c7eac936965016133bccc77f6)
 - [cbc352e0d0235f1e8e200eee1f6587d08b1ec7ca](https://github.com/magento/magento2/commit/cbc352e0d0235f1e8e200eee1f6587d08b1ec7ca)
 - [c85bcd0fb0e1b97df1d8b116ba3647c28f3f33f4](https://github.com/magento/magento2/commit/c85bcd0fb0e1b97df1d8b116ba3647c28f3f33f4)
 - [01aeae6258529efdc60813e283b8fd09443a565d](https://github.com/magento/magento2/commit/01aeae6258529efdc60813e283b8fd09443a565d)
 - [20e30c62bf04cb38a2a2a2650d7ae775559e759b](https://github.com/magento/magento2/commit/20e30c62bf04cb38a2a2a2650d7ae775559e759b)
 - [2d34f0567db56eca6626848009b7bf08ff4afd5e](https://github.com/magento/magento2/commit/2d34f0567db56eca6626848009b7bf08ff4afd5e)
 - [f6938af5dc634eb0b18b3b15464d152e68a36690](https://github.com/magento/magento2/commit/f6938af5dc634eb0b18b3b15464d152e68a36690)
 - [f5c4dc4bfe636587443ba299f2fabea5f290d430](https://github.com/magento/magento2/commit/f5c4dc4bfe636587443ba299f2fabea5f290d430)

The fix will be available with the upcoming 2.4.0 release.
