### ISSUE TITLE
HttpClientInterface Doesn't exists from Symfony vendor Package

### ISSUE THREAD

**Issue by fab-rkd** [magento/magento2#27150]
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.2.28-3+ubuntu18.04.1+deb.sury.org+1 

### Steps to reproduce (*)

1. Create any custom class (Model, Helper etc.)
2. Use `Symfony\Component\BrowserKit\HttpBrowser`
3. Try to create an object of `HttpBrowser ($client)` and call `$client->request('GET', "https://magento.com/")`
4. Run dependency injection by `bin/magento setup:di:compile`

### Expected result (*)

1. Retrun object of type
 `Symfony\Component\DomCrawler\Crawler`

### Actual result (*)

1. Class `Symfony\Contracts\HttpClient\HttpClientInterface` does not exist
![Screenshot from 2020-03-04 13-34-31](https://user-images.githubusercontent.com/20355726/75857862-ff16c900-5e1c-11ea-960c-bf68715189d1.png)

**Comment by hostep** [comment]
@fab-rkd: I believe this might be a bug in the `symfony/browser-kit` package, see: https://github.com/symfony/browser-kit/commit/504b1e4979c4ab1499d4eeb766a00b05beb39802#commitcomment-37640083

You can probably fix it by executing `composer require symfony/contracts`

But but but, you have to be vary careful here, because the `symfony/browser-kit` is a development dependency in Magento which means it won't be deployed to a production environment. So you'd be advised to not use this package in a custom module, unless you make it a non-development requirement, by running `composer require symfony/browser-kit`.

I'm going to close this as it doesn't seem to be a bug in the Magento code.
