### ISSUE TITLE
Not able to update value with "use default checkbox" for Downloadable Product's Sample and Links Title.

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#27169]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

ISSUE: 1

1. Create a downloadable Product Add Sample Title and Link Title https://prnt.sc/rbtrlf
2. Save the product.
3. Now switch store scope by store switcher : https://prnt.sc/rbts2p
4. Uncheck Checkbox and update the value and save again: https://prnt.sc/rbtsn4
5. This time Check the Checkboxes to use Default value, and save. https://prnt.sc/rbttbs

ISSUE: 2
1. Follow the steps from ISSUE:1 upto Step 3.
2. Now check the Checkboxes for the Link and Sample Root titles: https://prnt.sc/rbty23 
3. Value with default scope updated but Checkboxes remains unchecked.

### Expected result (*)

1. Value must be updated with the global scope value.
2.

### Actual result (*)

1. It keeps the current scope value and do not update with default scope.
2.

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27169-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27169-2-4-develop.instances.magento-community.engineering/admin_c9f1](https://i-27169-2-4-develop.instances.magento-community.engineering/admin_c9f1)
Login: `1243f69a` Password: `b97803dc72cf`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32203` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your report. 
The issue has been fixed in magento/magento2#27295 by @tna274 in 2.4-develop branch
Related commit(s):
 - [4c40dad1ca3582551a2830161e1a57fbd5c83df6](https://github.com/magento/magento2/commit/4c40dad1ca3582551a2830161e1a57fbd5c83df6)
 - [53136a261df08fbe9b1a263a6721c765014adb6c](https://github.com/magento/magento2/commit/53136a261df08fbe9b1a263a6721c765014adb6c)
 - [5a2c9b7a6d7a9326b07c154e719c021420a00921](https://github.com/magento/magento2/commit/5a2c9b7a6d7a9326b07c154e719c021420a00921)
 - [2a2b98a1a04141dad801b7491588b113bd11f7cf](https://github.com/magento/magento2/commit/2a2b98a1a04141dad801b7491588b113bd11f7cf)
 - [796255795513a80b6aa8d85b4bc7840185989100](https://github.com/magento/magento2/commit/796255795513a80b6aa8d85b4bc7840185989100)
 - [e918d3b7cc37132b2f020fc7643605a831391eae](https://github.com/magento/magento2/commit/e918d3b7cc37132b2f020fc7643605a831391eae)
 - [d421504658fd4cbb4e1919a92c77e5741cae8a50](https://github.com/magento/magento2/commit/d421504658fd4cbb4e1919a92c77e5741cae8a50)
 - [a242e3ad8939a3e095ef796c751e94422915cd52](https://github.com/magento/magento2/commit/a242e3ad8939a3e095ef796c751e94422915cd52)
 - [947eaedf2397701d43f6366dacc2bcb8b65df3b1](https://github.com/magento/magento2/commit/947eaedf2397701d43f6366dacc2bcb8b65df3b1)
 - [6cd3bf77dca3fd7c07fe0ebb77452f5b3999093d](https://github.com/magento/magento2/commit/6cd3bf77dca3fd7c07fe0ebb77452f5b3999093d)

The fix will be available with the upcoming 2.4.0 release.
