### ISSUE TITLE
getTracking() not found in 2.3.3

### ISSUE THREAD

**Issue by gazsmith10** [magento/magento2#27195]
I am getting the error :

Fatal error: Uncaught Error: Call to undefined method Magento\Framework\Phrase::getTracking() in /domains/XX/http/vendor/magento/module-shipping/view/frontend/templates/tracking/details.phtml:21 Stack trace: #0

On the customer "track order" (through the back end also) which is the popup.html in in module-shipping.

I have seen the magento github it was apperently fixed by 2.2 but i'm on 2.3.3 and i'm getting the issue.

**Comment by zaximus84** [comment]
The problem is in \Magento\Shipping\Model\Order\Track::getNumberDetail. If a carrier instance can be loaded, the logic assumes it will have a getTrackingInfo method that will return a data object. When it doesn't, a phrase object is returned instead. A phrase object is fundamentally incompatible with Magento_Shipping::tracking/details.phtml.

When a carrier instance doesn't return tracking info, it should fall back to the same behavior it uses when there is no carrier instance: return an array containing the title and tracking number.

I recommend getNumberDetail be updated to this:
`public function getNumberDetail()
{
    $carrierInstance = $this->_carrierFactory->create($this->getCarrierCode());
    if ($carrierInstance) {
        $carrierInstance->setStore($this->getStore());
        $carrierInfo = $carrierInstance->getTrackingInfo($this->getNumber());
        if ($carrierInfo) {
            return $carrierInfo;
        }
    }

    $trackingInfo = [];
    $trackingInfo['title'] = $this->getTitle();
    $trackingInfo['number'] = $this->getTrackNumber();
    return $trackingInfo;
}`

**Comment by evs-xsarus** [comment]
Seems like there are two variants:

vendor/magento/module-rma/Model/Shipping.php
```php
    /**
     * Retrieve detail for shipment track
     *
     * @return \Magento\Framework\Phrase|string|array
     */
    public function getNumberDetail()
    {
        $carrierInstance = $this->_carrierFactory->create($this->getCarrierCode());
        if (!$carrierInstance) {
            $custom = [];
            $custom['title'] = $this->getCarrierTitle();
            $custom['number'] = $this->getTrackNumber();
            return $custom;
        } else {
            $carrierInstance->setStore($this->getStore());
        }

        if (!($trackingInfo = $carrierInstance->getTrackingInfo($this->getTrackNumber()))) {
            return (string)__('No detail for number "%1"', $this->getTrackNumber());
        }

        return $trackingInfo;
    }
```
vendor/magento/module-shipping/Model/Order/Track.php
```php
    /**
     * Retrieve detail for shipment track
     *
     * @return \Magento\Framework\Phrase|string
     */
    public function getNumberDetail()
    {
        $carrierInstance = $this->_carrierFactory->create($this->getCarrierCode());
        if (!$carrierInstance) {
            $custom = [];
            $custom['title'] = $this->getTitle();
            $custom['number'] = $this->getTrackNumber();
            return $custom;
        } else {
            $carrierInstance->setStore($this->getStore());
        }

        $trackingInfo = $carrierInstance->getTrackingInfo($this->getNumber());
        if (!$trackingInfo) {
            return __('No detail for number "%1"', $this->getNumber());
        }

        return $trackingInfo;
    }
```

The first one returns a string instead of a phrase. This, in turn, prevents a broken detail.phtml. 

I would try patching the latter one and add the cast to string.

**Comment by skghorela** [comment]
Hello Team,
Please help on this error(Magento2.4.7)
{main} {"exception":"[object] (Error(code: 0): Call to undefined method Magento\Framework\Phrase::getTracking() at /var/www/php83/ERPm247/vendor/magento/module-shipping/view/frontend/templates/tracking/details.phtml:21)"} []
![Screenshot (40)](https://github.com/magento/magento2/assets/82929406/022945d8-89f9-49bd-a49f-7cffb47e5089)
![Screenshot (39)](https://github.com/magento/magento2/assets/82929406/8af4d68d-0828-43aa-996c-71a9cfd23e93)
