### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by rvitaliy** [magento/magento2#27227]
PHP 7.4 has been released in november 2019. It would be nice to see Magento 2 supported it.

**Comment by sdzhepa** [comment]
Hello @rvitaliy 

Sorry but I am closing this issue due to
- to we cannot proceed with such reports/request here 
- and based on [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

> 
> Before creating an issue, please do the following:
> ...
> * Make sure, that information you are about to report is a technical issue, please refer to the [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for technical questions, feature requests, etc. These reports are not guaranteed to be processed within GitHub issue tracker.
> ...

**Comment by rvitaliy** [comment]
Hello @sdzhepa

I apologize for the inconvenience, I believe there is nothing to add as technical information for this issue.
I would ask you to reopen it and remove the `done` tag as this feature has not yet been implemented.

**Comment by hostep** [comment]
I'm re-opening, because I agree that we need some sort of ticket to keep track of support for upcoming PHP versions. It's interesting to follow this, and that Magento developers can post updates in here to announce progress and when we can expect a Magento release compatible with PHP 7.4
In the thread for PHP 7.3, the same [thing](https://github.com/magento/magento2/issues/19604#issuecomment-459394788) [happened](https://github.com/magento/magento2/issues/19604#issuecomment-505107830).

@sdzhepa, if you don't agree, then at least keep it open and move it to https://github.com/magento/community-features/ repository.

**Comment by sdzhepa** [comment]
Hello @rvitaliy @hostep 

Wow, it seems I become dislike champion in this thread...
Sorry for my strict answer and manners and let me explain the decision to close the issue
- reported issue it's not kine of bug or task that can be fixed and delivered here with community PR
- it's very complex task that required changes(and full testing) not only in Magento code itself but for all staff around. Not all of them are public available

So, for my point of view, such task should be done by Magento internally.

But despite all my excuses, let me share an additional update about it. Not sure that I can share it publicly,  it is not any kind of official announcement but just only my personal thoughts.
At this moment in the internal backlog, there are a lot of tasks/stories/epics to upgrade the PHP version to 7.4. These tasks in progress now and internal teams are working hard to make it reals as soon as possible. I hope it will be done with one of the next 2.4.x releases.
Due to the huge amount of internal tasks/tickets related to this, I am not able to provide a regular status update as a comment for this issue(manually or automatically)
The final update for this issue will be in the release notes.

I still think that we can close this issue but if you want we can keep it open and close only based on release notes related to php7.4

 
Sorry again for any inconveniences

**Comment by hostep** [comment]
@sdzhepa: thanks for the update! You can close the issue from my part, but it's just nice to keep the community updated around what happens and once most work is done and there is a known date for when a version can be expected that is compatible with PHP 7.4, it would be nice that this can get announced somehow.

A lot of work Magento is doing internally is interesting to know but some stuff remains hidden, which is a bit unfortunate for an open source project. I'm just asking for a little bit of transparency. Opening up that branch to the public is a nice gesture!

If [magento/magento2](https://github.com/magento/magento2) is not the correct repo for keeping track of PHP 7.4 progress, then maybe [magento/community-features](https://github.com/magento/community-features/) or [magento/backlog](https://github.com/magento/backlog/issues) or [the devblog](https://community.magento.com/t5/Magento-DevBlog/bg-p/devblog) is?

**Comment by rvitaliy** [comment]
Hi @sdzhepa!
Thanks for update and sorry for this dislikes, is not my scope.

I think that this kind of work must be open and related to a card like this to keep community updated.

My suggestion is that Mangento must keep in mind that they have many external libs that must be updated for properly work with new release, if community doesn't know whats happen in next release it's hard to be ready for update...
So, please, take care about update of our comunity.

I think that this issue can't be closed before upgdare to php 7.4 is not completed. It's usefull for other people to see that Magento is working on this issue.

**Comment by hostep** [comment]
Yay, it looks like PHP 7.4 support got recently merged in the 2.4-develop branch: https://github.com/magento/magento2/commit/40a787632f36ca67f8fff8c451e1e8d1bdbaf9f6

So that will probably be included in Magento 2.4.0 or 2.4.1?

Not sure if there are plans for backporting it to 2.3.x ?

**Comment by rvitaliy** [comment]
latest magento version support php 7.4 :beers:
