### ISSUE TITLE
Redirect to cart page from checkout with varnish Enable

### ISSUE THREAD

**Issue by jaivikpatel** [magento/magento2#27235]
### Preconditions (*)

1.Magento 2.3.4
2.Must Varnish Enable

### Steps to reproduce (*)

1. Do not add any product to the cart.
2. Directly go to https://www.sample.domain/checkout/
3. Because No product in cart Redirect user to Cart page https://www.sample.domain/checkout/cart
4. Add any product in the cart.
5. Go to Checkout.
6. It will redirect you to the cart page because of the caching of step 3 in varnish.

### Expected result (*)

1. Do not add any product to the cart.
2. Directly go to https://www.sample.domain/checkout/
3. Because No product in cart Redirect user to Cart page https://www.sample.domain/checkout/cart
4. Add any product in the cart.
5. Go to Checkout.
6. It should allow the user to go to the cart when the product is available.

### Actual result (*)

1. Because of Varnish, It cache steps 2 and 3 redirection and next time when users come with the product at that time also it not allowing the user to go to checkout page. So it should stop track of that redirection by varnish.

**Comment by vovsky** [comment]
could not reproduce on 2.3.4+Varnish

**Comment by jaivikpatel** [comment]
> could not reproduce on 2.3.4+Varnish
First clear cache and directly go to the checkout page.
As display in my step.
 https://www.sample.domain/checkout/

I can reproduce it.

**Comment by vovsky** [comment]
@jaivikpatel Here is my steps https://monosnap.com/file/I9KkyyoSwElUZiym0QmqNfQey67TfB
Am I missing something?

**Comment by jaivikpatel** [comment]
> @jaivikpatel Here is my steps https://monosnap.com/file/I9KkyyoSwElUZiym0QmqNfQey67TfB
> Am I missing something?

Clear browser cookie cache everything.

Yes, you missed it.
->you enter webisite.com/checkout
->it should be website.com/checkout/
->you missed last slash (/)
Please add that and run in the URL.
The try to add products and go for checkout regularly it will redirect to cart page.

**Comment by jaivikpatel** [comment]
> @jaivikpatel Here is my steps https://monosnap.com/file/I9KkyyoSwElUZiym0QmqNfQey67TfB
> Am I missing something?

@vovsky Have you got the issue with my steps?

**Comment by brandon1310** [comment]
Hi Magento,

Is it possible to get an update on this? We've just had this issue on our 2.3.4 site coupled with Varnish and has caused major issues.

Thanks,
Brandon

**Comment by prasannachelladurai90** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90, here is your [Magento instance](https://i-27235-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27235-2-4-develop.instances.magento-community.engineering/admin_fd2a](https://i-27235-2-4-develop.instances.magento-community.engineering/admin_fd2a)
Login: `b1fedf68` Password: `2c8b8e509aef`
Instance will be terminated in up to 3 hours.

**Comment by prasannachelladurai90** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @prasannachelladurai90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by engcom-Delta** [comment]
Hi @jaivikpatel , thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**
- Configure varnish v.6.2.1
![image](https://user-images.githubusercontent.com/51681379/104321875-db1c1d80-54ec-11eb-90f0-8d4af14c119d.png)

- Set magento developer mode to [verify response headers](https://devdocs.magento.com/guides/v2.4/config-guide/varnish/config-varnish-final.html#config-varnish-final-verify-headers)
- Do not add any product to the cart.
- Directly go to http://www.example.com/checkout/
- Because No product in cart Redirect user to Cart page http://www.example.com/checkout/cart
- Add any product in the cart.
- Go to Checkout.

**Result:**
:heavy_check_mark: Checkout page is opened
:heavy_check_mark: `https://www.sample.domain/checkout/` is not cached
![Peek 2021-01-12 15-39](https://user-images.githubusercontent.com/51681379/104322650-dc017f00-54ed-11eb-866d-38022462af4c.gif)


**Note:** Same scenario was tested on production mode

If you'd like to update the issue, please reopen it.

**Comment by jaivikpatel** [comment]
@engcom-Delta Can you please try in Magento 2.3.6, please?
