### ISSUE TITLE
Integration Tests: Consecutive `dispatch($uri)` on Test AbstractController fails

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27299]
### Preconditions (*)
1. Integration Tests in Magento `2.4-develop`

### Steps to reproduce (*)
1. Create a test that uses `\Magento\TestFramework\TestCase\AbstractController::dispatch` for dispatching controller.
2. Add the second request to any other URI.

### Expected result (*)
1. Both requests are dispatched

### Actual result (*)
1. First request is dispatched
2. Second request throws `InvalidArgumentException: Invalid return type`

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27300 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [5d0c97255f83c6aead003a420a8db803a7085b2d](https://github.com/magento/magento2/commit/5d0c97255f83c6aead003a420a8db803a7085b2d)
 - [ba8d3669a7b498759023dc9518e5339764e0170b](https://github.com/magento/magento2/commit/ba8d3669a7b498759023dc9518e5339764e0170b)
 - [4286297f0f69dcf0524542afba11be5c3c7f6634](https://github.com/magento/magento2/commit/4286297f0f69dcf0524542afba11be5c3c7f6634)
 - [5a2673d2b5c0f976bee50ac87491babfed29ecb3](https://github.com/magento/magento2/commit/5a2673d2b5c0f976bee50ac87491babfed29ecb3)

The fix will be available with the upcoming 2.4.0 release.
