### ISSUE TITLE
Multiple Temando Shipping modules in 2.3.4

### ISSUE THREAD

**Issue by nbennett25** [magento/magento2#27316]
There seem to be multiple Temando_Shipping modules in code in 2.3.4, which causes integrity constraint violations when running bin/magento setup:upgrade, since both modules are adding the same content with data upgrades.

Related:
https://community.magento.com/t5/Magento-2-x-Technical-Issues/Integrity-constraint-violation-on-setup-upgrade-Magento-2-3-3/td-p/209198

composer show:
...
temando/module-shipping                      1.6.2  Temando multi-carrier shipping extension for Magento 2
temando/module-shipping-m2                    1.6.2  Temando multi-carrier shipping extension for Magento 2
...
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.3

### Steps to reproduce (*)

1. Run composer install

### Expected result (*)

1. `temando/module-shipping-m2` is installed

### Actual result (*)

1. Both `temando/module-shipping` and `temando/module-shipping-m2` are installed

**Comment by hostep** [comment]
It looks like one of both is a composer meta package, because only `temando/module-shipping-m2` exists in the `vendor` directory.

Other observations by looking at the `composer.lock` file:
- `magento/product-community-edition` requires `temando/module-shipping`
- `temando/module-shipping` requires `temando/module-shipping-m2`

Strictly speaking this shouldn't be a problem but it can be a bit confusing.

In my opinion, this shouldn't cause database migration problems, so do you have more info about those @nbennett25 ?

**Comment by nbennett25** [comment]
Thanks for the clarification on the meta module.

I’m just noticing that when running setup:upgrade with 2.3.4, I’m getting the constraint violation error listed in the link above. Commenting out line 73 in the Temando_Shipping/Setup/UpgradeData.php file ($this->installer->addMappedProductAttributes();) allows the setup:install command to work as expected. 

The addMappedProductAttributes() method tries to add values to the `temando_product_attribute_mapping` and for whatever reason, those values already exist in the table.

Thx

**Comment by engcom-Oscar** [comment]
The issue not reproducible on 2.4-develop
