### ISSUE TITLE
MFTF: Functional Tests failing due to missing data in indexes

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27320]
### Preconditions (*)
I'm addressing the issue that wasn't solved for more than 3 months already and is blocker for most of the contributions. In most of the cases the results of Functional Tests are ignored, but it wasn't the goal of running them (!)

1. Magento is running multiple instances of tests on a single instance of the Store.
2. There are multiple Test Suites - eg. `SearchEngineElasticsearchSuite` that expect indices to work `On schedule` mode.
3. Data is created using `<createData` via API
4. A tested instance of Magento **is not running Cronjobs** (!)

### Steps to reproduce (*)
1. Install Magento instance locally
2. Set indices to work `On schedule`
3. Execute any test that `<createData`

### Expected result (*)
1. We expect the test to pass, of course

### Actual result (*)
1. But the test will probably fail, as the Cronjob was not run so the partial reindex was not executed.

### Solution :tada: 

1. Add extra command after each block of `<createData`s like: `<magentoCron stepKey="runCronIndex" groups="index"/>` to make sure that Cronjobs ran the partial reindex on specific items (products, categories).

#### Controverses

There are people who deeply believe that running Magento cronjobs is "hiding the issue" and they prefer to run `index:reindex` and `cache:flush`. This is unresponsible behaviour and should not be applied! The same people believe that `cron:run` executed twice one after another makes a difference. (Try it yourself: First will be executed, second one skipped if it's run in less than 60 seconds)

#### Problems

I still haven't managed why running Cronjobs are not reindexing the links in Configurable / Grouped products, but even if those products will still cause an issue, most of the Test cases are going to pass.

### Modules affected

- [ ] Magento_Analytics (Tests)
- [x] Magento_Backend (Tests)
- [x] Magento_Braintree (Tests)
- [x] Magento_Bundle (ActionGroups)
- [x] Magento_Bundle (Tests)
- [x] Magento_Captcha (Tests)
- [ ] Magento_Catalog (Tests)
- [x] Magento_CatalogImportExport (Tests)
- [x] Magento_CatalogInventory (Tests)
- [x] Magento_CatalogRule (Tests)
- [ ] Magento_CatalogRuleConfigurable (Tests)
- [ ] Magento_CatalogSearch (Tests)
- [ ] Magento_CatalogUrlRewrite (Tests)
- [ ] Magento_CatalogWidget (Tests)
- [ ] Magento_Checkout (Tests)
- [ ] Magento_CheckoutAgreements (Tests)
- [ ] Magento_Cms (Tests)
- [ ] Magento_Config (ActionGroups)
- [ ] Magento_Config (Tests)
- [ ] Magento_ConfigurableProduct (ActionGroups)
- [ ] Magento_ConfigurableProduct (Tests)
- [ ] Magento_CurrencySymbol (Tests)
- [ ] Magento_Customer (Tests)
- [ ] Magento_Downloadable (Tests)
- [ ] Magento_Elasticsearch (Tests)
- [ ] Magento_Elasticsearch6 (Tests)
- [ ] Magento_Fedex (Tests)
- [ ] Magento_GroupedProduct (Tests)
- [ ] Magento_ImportExport (Tests)
- [ ] Magento_LayeredNavigation (Tests)
- [ ] Magento_Msrp (Tests)
- [ ] Magento_Multishipping (Tests)
- [ ] Magento_Newsletter (Tests)
- [ ] Magento_OfflineShipping (Tests)
- [ ] Magento_PageCache (Tests)
- [ ] Magento_Paypal (Tests)
- [ ] Magento_Persistent (Tests)
- [ ] Magento_ProductVideo (Tests)
- [ ] Magento_Quote (Tests)
- [ ] Magento_Reports (Tests)
- [ ] Magento_Review (Tests)
- [ ] Magento_Sales (Tests)
- [ ] Magento_SalesRule (Tests)
- [ ] Magento_Search (Tests)
- [ ] Magento_Security (Tests)
- [ ] Magento_Shipping (ActionGroups)
- [ ] Magento_Shipping (Tests)
- [ ] Magento_Store (Tests)
- [ ] Magento_Swatches (Tests)
- [ ] Magento_Tax (Tests)
- [ ] Magento_Translation (Tests)
- [ ] Magento_Ui (Tests)
- [ ] Magento_Ups (Tests)
- [ ] Magento_UrlRewrite (Tests)
- [ ] Magento_User (ActionGroups)
- [ ] Magento_User (Tests)
- [ ] Magento_Vault (Tests)
- [ ] Magento_Weee (Tests)
- [ ] Magento_Widget (Tests)
- [ ] Magento_Wishlist (Tests)

(This is my checklist to confirm that task was done - please don't touch!)

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27321 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [40155f6594c0c08b1cd0c02a820ee4203e7412d9](https://github.com/magento/magento2/commit/40155f6594c0c08b1cd0c02a820ee4203e7412d9)
 - [ace15cd3243a69d16b4cf8800da3ed59429a04c0](https://github.com/magento/magento2/commit/ace15cd3243a69d16b4cf8800da3ed59429a04c0)
 - [7ab256f3ac26f00d5cde7e1602c213c045c57eb4](https://github.com/magento/magento2/commit/7ab256f3ac26f00d5cde7e1602c213c045c57eb4)
 - [e79ee1eee7c2311f412849e906745c3973edbec1](https://github.com/magento/magento2/commit/e79ee1eee7c2311f412849e906745c3973edbec1)
 - [b8f7e900724917f86eef3aa745059da424a062c8](https://github.com/magento/magento2/commit/b8f7e900724917f86eef3aa745059da424a062c8)
 - [2ed8d255c4e317c63cabaef67890075ad9c647a3](https://github.com/magento/magento2/commit/2ed8d255c4e317c63cabaef67890075ad9c647a3)
 - [fc2f7f5ff504d0496a24ddc0e4d87b7936833596](https://github.com/magento/magento2/commit/fc2f7f5ff504d0496a24ddc0e4d87b7936833596)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27322 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [59987101ec2f06f71a319a65a5ea6cddc379cb44](https://github.com/magento/magento2/commit/59987101ec2f06f71a319a65a5ea6cddc379cb44)
 - [c050d91cd8db2d78a9fa6d31921e98dfe649e2bb](https://github.com/magento/magento2/commit/c050d91cd8db2d78a9fa6d31921e98dfe649e2bb)
 - [ae817bd23c61990c31ea705431058781be40ed7b](https://github.com/magento/magento2/commit/ae817bd23c61990c31ea705431058781be40ed7b)
 - [9025093054c4251266408f301670d07ec24fd40a](https://github.com/magento/magento2/commit/9025093054c4251266408f301670d07ec24fd40a)
 - [c4c1756c236b84a2dd43564926c4aede356966a8](https://github.com/magento/magento2/commit/c4c1756c236b84a2dd43564926c4aede356966a8)
 - [212182e4c2c838c2023a908bc2a2448f286b16cd](https://github.com/magento/magento2/commit/212182e4c2c838c2023a908bc2a2448f286b16cd)
 - [9d614e26e9d8a21b186ecb42d087d3c20f0c69eb](https://github.com/magento/magento2/commit/9d614e26e9d8a21b186ecb42d087d3c20f0c69eb)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27323 by @lbajsarowicz in 2.4-develop branch
Related commit(s):
 - [7b9232adc9a211134c347b506888579ec1889e59](https://github.com/magento/magento2/commit/7b9232adc9a211134c347b506888579ec1889e59)
 - [86b27a69e11aad171102543a3b7dc074eccf377a](https://github.com/magento/magento2/commit/86b27a69e11aad171102543a3b7dc074eccf377a)
 - [410cb170dd78cdefb1ece9c4f001b709db182b4d](https://github.com/magento/magento2/commit/410cb170dd78cdefb1ece9c4f001b709db182b4d)
 - [3d304382df7958fe215ece612ca2af6f67df6943](https://github.com/magento/magento2/commit/3d304382df7958fe215ece612ca2af6f67df6943)
 - [cb3ad7c77f7d41e084175de2afdd4d640a223e53](https://github.com/magento/magento2/commit/cb3ad7c77f7d41e084175de2afdd4d640a223e53)
 - [d71b638fefcb1e11950462419836442d7dcc7d6b](https://github.com/magento/magento2/commit/d71b638fefcb1e11950462419836442d7dcc7d6b)
 - [1bc8a311be62d94257bbc0df9a2cf04eac2ea37c](https://github.com/magento/magento2/commit/1bc8a311be62d94257bbc0df9a2cf04eac2ea37c)
 - [656ea480bf14d75454dde53fa4deb56a28fcf347](https://github.com/magento/magento2/commit/656ea480bf14d75454dde53fa4deb56a28fcf347)
 - [06914ef8e221c071d4c2f2496a24900f69c10467](https://github.com/magento/magento2/commit/06914ef8e221c071d4c2f2496a24900f69c10467)
 - [2c1b4fe6edaab0ddde7a869c659201bc8c2b97c6](https://github.com/magento/magento2/commit/2c1b4fe6edaab0ddde7a869c659201bc8c2b97c6)
 - [653ce0f83ffaf0bc06ae8e7b919527f1363dc836](https://github.com/magento/magento2/commit/653ce0f83ffaf0bc06ae8e7b919527f1363dc836)

The fix will be available with the upcoming 2.4.0 release.
