### ISSUE TITLE
My account Address Book Additional Address Entries table issue

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#27335]
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Login to Luma theme front end -> My account -> Address Book -> Address Entries table 
2. see the table head aliment issue in (Tablet, Desktop)

### Expected result (*)

1. https://prnt.sc/rig3rm
2. https://prnt.sc/rig551

### Actual result (*)

1. https://prnt.sc/rig4f6
2. https://prnt.sc/rig4oi

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32606` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
The issue has been fixed in https://github.com/magento/magento2/pull/27336

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#27336 by @abrarpathan19 in 2.4-develop branch
Related commit(s):
 - [5abd3665e5f93588670a81503e6823d11d2e0d55](https://github.com/magento/magento2/commit/5abd3665e5f93588670a81503e6823d11d2e0d55)

The fix will be available with the upcoming 2.4.0 release.
