### ISSUE TITLE
Creating custom widget instance validation is weird due to controller type mismatch

### ISSUE THREAD

**Issue by MellenIO** [magento/magento2#27397]
### Summary (*)
See this line of code:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Widget/Controller/Adminhtml/Widget/Instance/Validate.php#L22

The function `\Magento\Widget\Model\Widget\Instance::validate()` is type hinted to return either a `\Magento\Framework\Phrase` or a `bool`
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Widget/Model/Widget/Instance.php#L294

This means the `is_string` check is going to fail. This further means that, unless you type cast the phrase to a string, you will **not** ever get a constructive error message out of the widget validation controller.
This isn't a huge issue for the most part with Magento core because of the frontend validation but for those creating custom widget validation rules it will break.

### Examples (*)

```php
$firstResult = __('Test message');
if ($firstResult !== true && is_string($firstResult)) {
    echo 'We have an error!';
}
```
Does not output anything.

### Proposed solution

I think the easiest solution is just to change the validation controller line to the following:
```php
if ($result !== true && (is_string($result) || ($result instanceof \Magento\Framework\Phrase)) {
// ...
```

On Magento sites with custom validation rules we've gotten around this by adding an `afterValidate` plugin to `\Magento\Widget\Model\Widget\Instance` which type casts the result to string (and returns a string for subsequent errors, rather than a phrase).

**Comment by magento-engcom-team** [comment]
Hi @MellenIO. Thank you for your report. 
The issue has been fixed in magento/magento2#28379 by @zaximus84 in 2.4-develop branch
Related commit(s):
 - [f20b05b549bb0813ca21a0204588045fcb7e1c2a](https://github.com/magento/magento2/commit/f20b05b549bb0813ca21a0204588045fcb7e1c2a)
 - [1e4ef873f9639316617a33bdfb229a652d5d5ceb](https://github.com/magento/magento2/commit/1e4ef873f9639316617a33bdfb229a652d5d5ceb)
 - [3d82fe3a7bf0dc297d64a369cff03e246536e4a5](https://github.com/magento/magento2/commit/3d82fe3a7bf0dc297d64a369cff03e246536e4a5)
 - [0f1c4599134fa43d2589ed0d0367d1f91b29ee31](https://github.com/magento/magento2/commit/0f1c4599134fa43d2589ed0d0367d1f91b29ee31)
 - [d0e8bda1a3b689b77b220c011249ec42c536b99d](https://github.com/magento/magento2/commit/d0e8bda1a3b689b77b220c011249ec42c536b99d)

The fix will be available with the upcoming 2.4.2 release.
