### ISSUE TITLE
M2.3.4 : Updated the url_key of a parent category does not update the url's of the children

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#27432]
### Preconditions (*)

1. Magento 2.3.4, vanilla installation

### Steps to reproduce (*)

1. Programmatically create a parent and a child category
2. Update the `url_key` of the parent category

### Expected result (*)

1. The URL of the child category should be updated as well.

### Actual result (*)

1. The URL of the child category still has the old URL.

### Integration test

I've wrote this integration test to show the problem:

    /**
     * @magentoDbIsolation enabled
     * @magentoAppIsolation enabled
     * @magentoAppArea adminhtml
     */
    public function testChildUrl()
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

        /** @var \Magento\Catalog\Model\CategoryRepository $categoryRepository */
        $categoryRepository = $objectManager->get(\Magento\Catalog\Model\CategoryRepository::class);

        /** @var \Magento\Catalog\Model\Category $parentCategory */
        $parentCategory = $objectManager->create(\Magento\Catalog\Model\Category::class);
        $parentCategory->setName('Foo');
        $parentCategory->setUrlKey('foo');
        $parentCategory->setIsActive(true);
        $categoryRepository->save($parentCategory);

        /** @var \Magento\Catalog\Model\Category $subCategory */
        $subCategory = $objectManager->create(\Magento\Catalog\Model\Category::class);
        $subCategory->setName('Bar');
        $subCategory->setUrlKey('bar');
        $subCategory->setIsActive(true);
        $subCategory->setParentId($parentCategory->getId());
        $categoryRepository->save($subCategory);

        $this->assertEquals('http://localhost/index.php/foo/bar.html', $subCategory->getUrl());

        // Now we edit the URL key of the parent:
        $parentCategory->setUrlKey('foo-updated');
        $categoryRepository->save($parentCategory);

        // Create new instance of repository, so we don't have internal caching issues:
        $categoryRepository = $objectManager->create(\Magento\Catalog\Model\CategoryRepository::class);
        $subCategory = $categoryRepository->get($subCategory->getId());

        // This will fail, URL is still the old one:
        $this->assertEquals('http://localhost/index.php/foo-updated/bar.html', $subCategory->getUrl());
    }

**Comment by celorodovalho** [comment]
I'm facing the same error! Any solution?

**Comment by laura5101** [comment]
Is there any update on this? Or does anyone know of an alternative way to force Magento to create the correct URLs (even if it's a workaround?)
Laura

**Comment by JamesFX2** [comment]
Maybe be an issue still in 2.4.4 - not fully investigated yet.

**Comment by JamesFX2** [comment]
Issue was caused by the url_path attribute not updating, the storefront version was overriding it in spite of the fact that the url_key was inheriting from the default.

**Comment by JamesFX2** [comment]
The issue happened at the same time as another error - when the parent categories URL key was changed - it threw an error because of duplicate URL keys of products in the category. It's possible this was responsible for the URL path not being updated but the issue persisted after the duplicate URL keys were removed.

**Comment by hostep** [comment]
@JamesFX2: use https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/ in case you want to find problems in `url_key` or `url_path` attributes of products and categories.

I'm not sure if this issue here was actually fixed in 2.4.4 but there are definitely fixes in various versions of Magento that have to do with this. But if your database was used in earlier versions of Magento, you might still be dragging your incorrect data with you, upgrading magento won't automatically fix incorrect values, that's something that needs to be done manually or with some kind of script I'm afraid.

**Comment by harihhs** [comment]
This issue is still there in 2.4.6

**Comment by harihhs** [comment]
@magento Reopen this issue.
