### ISSUE TITLE
Reset orders gives fatal error

### ISSUE THREAD

**Issue by wkaminsk** [magento/magento2#2747]
Have a order model, did clone and then tried to reset cloned object. It gives fatal error : 
Fatal error: Call to a member function setOrder() on null in /vendor/magento/module-sales/Model/Order.php on line 1445

Regards,
Wojtek.

**Comment by NadiyaS** [comment]
Hi @wkaminsk ,
thanks for reporting this bug. Internal issue was created MAGETWO-47209

**Comment by schmengler** [comment]
Thank you for fixing this bug. It's been almost a year now. Any reason why this was not merged in one of the 2.1 patch releases?

**Comment by korostii** [comment]
_Disclaimer: I am not an employee of Magento, Inc._

It seems that patching 2.1 in general just isn't a priority for Magento, Inc.
They expect to get the [community contributors involved into backporting](https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630) while [their own priorities are elsewhere](https://community.magento.com/t5/Magento-DevBlog/GitHub-Issue-Priority/ba-p/60088#M15).

**Comment by ishakhsuvarov** [comment]
Hi @schmengler @korostii 
We are indeed accepting Pull Requests for the backports into `2.1-develop` branch. Patching is a priority, however it does not mean that we have capacity to include all of the fixes into the patch releases.

Please feel free to submit a Pull Request with the backport for the fix or upvote this ticket to speed up the process on Magento's side.
Thanks.

**Comment by korostii** [comment]
@ishakhsuvarov,
> upvote this ticket to speed up the process on Magento's side.

With all due respect, that doesn't seem to work neither. Unlike this very issue, most issues get *closed* when the fix is delivered to the `develop` branch. And as you can read in @maksek's response [here](https://community.magento.com/t5/Magento-DevBlog/GitHub-Issue-Priority/bc-p/61133/highlight/true#M15), and I quote: "In terms of upvoting on closed issues - at the moment we are not monitoring (or rarely monitoring such issues), due overload on opened issues."

In my humble opinion, the time workforce it takes to review a community pull request alone must be significantly more than it takes the developer who've just implemented that fix on `develop` to cherry-pick the very fix into the `2.1-develop` branch as well (in scope of the same MAGETWO task) where your developer fixes it. Don't you agree?

It's not like it's a controversial feature suggestion which can be dropped altogether: the bug, however rare, _will_ be experienced by more users again (and again) and _must_ be eventually fixed (the sooner, the better).

Why is there a need for a third-party developer to be involved in that, at all? Why not release all these small patches right away?
What's logic behind the urge to have people vote on those? 
Or, better yet, why force a user to fork the repository with the sole purpose of "speeding up" the release of the bugfix required? (which is especially absurd if you consider that a lot of people experiencing these issues are merchants, with potentially no programming skills whatsoever)

**Comment by YevSent** [comment]
Fixed on develop branch https://github.com/magento/magento2/commit/c387af827bca365c3b584511b404d7bda834d6f5#diff-6f2b3927e6511c70ebb080c37d84c2d3

**Comment by schmengler** [comment]
@joni-jones You added the `2.1-develop` label but I don't see the fix in that branch yet. Am I looking at the wrong place? https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/Sales/Model/Order.php

**Comment by YevSent** [comment]
@schmengler, the fix is present only on the develop branch, but the issue also affects 2.1-develop branch.

**Comment by duckchip** [comment]
@schmengler can this fix be included in the next 2.1.x version?

**Comment by schmengler** [comment]
@duckchip I don't know, but maybe someone from the team can answer it:

> @magento-engcom-team moved this from TODO to Done in branch [2.1-develop] on 20 Sep 2017
