### ISSUE TITLE
Viewport resizing on search input focus on iphone

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#27506]
When you click the search input box the viewport changes size and the layout breaks using iphone and luma theme.

### Preconditions (*)

1. Magento 2.3.3
2. Luma theme
3. Iphone / Safari

### Steps to reproduce (*)

1. Navigate to luma demo with iphone and safari
2. Click search icon
3. Click search input

### Expected result (*)

Should not resize the view and cause sidescrolling.

### Actual result (*)

Resizes view and causes sidescrolling.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33050` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
The Issue has been fixed and delivered with https://github.com/magento/magento2/pull/27603

**Comment by magento-engcom-team** [comment]
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#27603 by @ptylek in 2.4-develop branch
Related commit(s):
 - [0d1d42c362eafe7052e3863f1d5285dc1c6ca6e1](https://github.com/magento/magento2/commit/0d1d42c362eafe7052e3863f1d5285dc1c6ca6e1)

The fix will be available with the upcoming 2.4.0 release.
