### ISSUE TITLE
No header logo in transactional emails

### ISSUE THREAD

**Issue by aqdennis** [magento/magento2#27528]
### Preconditions (*)

1. Magento 2.3.2
2. PHP 7.1.33

### Steps to reproduce (*)

1. Upload e-mail for header of transactional email (Content -> Design Configuration -> <Store View> -> Transactional emails
2. Create transactional email, for instance for order update,  including  {{template config_path="design/email/header_template"}}
3. Check Preview Template :  logo is there
4. Make sure the e-mail is send, for instance by commenting on existing order so that e-mail is sent. Email does not contain logo, but the alternative text.
5. I can see that logo does exist in /pub/media/email/logo/stores/[store_id]  and in /pub/media/logo/stores/[store_id]

### Expected result (*)

1. Logo should be in email

### Actual result (*)

1.  No logo in e-mail, but alternative text. The hyperlink is there though, so only the image is missing

**Comment by shikhamis11** [comment]
hi @aqdennis 
thank you for reporting this issue 
I followed steps provided by you in description but not able to reproduce this issue. all transactional email logos are updating in new templates

**Comment by laurnts** [comment]
I am currently running magento 2.3.4 php 7.2 with nginx and just run into this issue. The logo is uploaded correctly to the pub directory, the preview works fine, but when previewed using mailhog, the logo is missing. The issue lies within {{var logo_url}} sometimes output /pub/media/email and sometimes output /media/email (without pub).
