### ISSUE TITLE
CLI Patch Generator: Lack of information what path cannot be created

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27523]
### Preconditions (*)
1. When running CLI `setup:db:generate-patch` I'd like to know details of failure

### Steps to reproduce (*)
1. `setup:db:generate-patch My_Module PatchName`

### Expected result (*)
1. Information what path was used to create patch.

### Actual result (*)
1. ![image](https://user-images.githubusercontent.com/1639941/78069491-7bf47e80-739a-11ea-8555-a6424e695b57.png)

### Additional Information
- Related DevDoc  [Convert install/upgrade data scripts to the data patch format](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.html#convert-installupgrade-data-scripts-to-the-data-patch-format)

**Comment by korostii** [comment]
On branch `2.4-develop` I got a slightly different error message, but it is still quite cryptic, for example if the module passed as command option _does not exist_ at all"
![Screenshot from 2020-04-04 17-09-33](https://user-images.githubusercontent.com/24894168/78452948-3df7a300-7697-11ea-864f-be84a781b0ee.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33895` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27579 by @korostii in 2.4-develop branch
Related commit(s):
 - [1e8e825abdc37dbd9ea196867552169a91cad082](https://github.com/magento/magento2/commit/1e8e825abdc37dbd9ea196867552169a91cad082)
 - [1dd5290fcb7b379a9fdad38136a7dd13ae907fa3](https://github.com/magento/magento2/commit/1dd5290fcb7b379a9fdad38136a7dd13ae907fa3)
 - [c1d8feffe1c547eacbfbfc031708be51e0787503](https://github.com/magento/magento2/commit/c1d8feffe1c547eacbfbfc031708be51e0787503)
 - [a74f8fe0130f9cca56f4371efd7a5dae890f0ec8](https://github.com/magento/magento2/commit/a74f8fe0130f9cca56f4371efd7a5dae890f0ec8)
 - [f48cd50d9ae608df559c6ab6cfd9f433b98563ea](https://github.com/magento/magento2/commit/f48cd50d9ae608df559c6ab6cfd9f433b98563ea)
 - [2bc691af85e7daaa82af2bf7ff0762cf59cc3555](https://github.com/magento/magento2/commit/2bc691af85e7daaa82af2bf7ff0762cf59cc3555)
 - [89917331fa15463e951a65aec57bee3431fc06f4](https://github.com/magento/magento2/commit/89917331fa15463e951a65aec57bee3431fc06f4)
 - [347602ff8f71bcdcb22dae2763f90e84012b7d52](https://github.com/magento/magento2/commit/347602ff8f71bcdcb22dae2763f90e84012b7d52)
 - [75bb2c3537b3a4c7ef719cca36d099bc6af9ef6c](https://github.com/magento/magento2/commit/75bb2c3537b3a4c7ef719cca36d099bc6af9ef6c)
 - [7d316d49f3f99cb3dbce3e775ea7c16ac8db2f86](https://github.com/magento/magento2/commit/7d316d49f3f99cb3dbce3e775ea7c16ac8db2f86)

The fix will be available with the upcoming 2.4.2 release.
