### ISSUE TITLE
Previewing email templates in admin loads admin area CSS

### ISSUE THREAD

**Issue by erfanimani** [magento/magento2#27543]
### Preconditions (*)

1. Magento 2.3.4, but this happens to other versions too

### Steps to reproduce (*)

1. In the admin, navigate to Marketing -> Email Templates
2. Load a template and hit Preview Template

### Expected result (*)

1. Email looks as "true" as possible, without any interference of CSS unrelated to the actual email

### Actual result (*)

1. Admin CSS interferes with how the email looks

The issue is simply that admin CSS is loaded when previewing email templates, which could interfere with how the emails show up as. With the Luma emails this difference is not much, some minor typography changes. However, when designing email templates from scratch, this could have a big effect — making the Preview Template functionality useless.

See screenshot below. Essentially there are two pages, one is the outer page (preview), and one is the inner page/iframe (popup). The iframe exists supposedly to isolate CSS changes. However, that's rendered moot as admin CSS is also loaded inside the iframe.

![image](https://user-images.githubusercontent.com/930470/78204019-1522b280-74cb-11ea-8574-b3f2ccdcfee5.png)

**Comment by slavvka** [comment]
Hi @erfanimani. Thank you for your report. 
The issue has been fixed in magento/magento2#27828 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [d7cf1881141fd855ff79f611a31ea2570726bdc3](https://github.com/magento/magento2/commit/d7cf1881141fd855ff79f611a31ea2570726bdc3)
 - [77a4e8c44e1ee901d77aa8d6680fcd5365cd376d](https://github.com/magento/magento2/commit/77a4e8c44e1ee901d77aa8d6680fcd5365cd376d)
 - [6b8fc4c55272229164fde82ddbd631f771f302d7](https://github.com/magento/magento2/commit/6b8fc4c55272229164fde82ddbd631f771f302d7)
 - [facbe37f9f51eb315bc5da1fb3c5000d743057ff](https://github.com/magento/magento2/commit/facbe37f9f51eb315bc5da1fb3c5000d743057ff)
 - [1ef8a517089ff132a7bb526194999ae83247ce50](https://github.com/magento/magento2/commit/1ef8a517089ff132a7bb526194999ae83247ce50)
 - [cd961c4444d60a4a2efdbd711485904d39d9a04d](https://github.com/magento/magento2/commit/cd961c4444d60a4a2efdbd711485904d39d9a04d)
 - [bcef3f5339b359e195d447f09ee14a2eea140f60](https://github.com/magento/magento2/commit/bcef3f5339b359e195d447f09ee14a2eea140f60)
 - [8aeffcc289e8bc62b4d97bb7ef816f0de876857b](https://github.com/magento/magento2/commit/8aeffcc289e8bc62b4d97bb7ef816f0de876857b)
 - [461eab38f0a2945bda7fcc232e632076b38f5a68](https://github.com/magento/magento2/commit/461eab38f0a2945bda7fcc232e632076b38f5a68)
 - [84f424c98d20d1263519f6e2948670368d807861](https://github.com/magento/magento2/commit/84f424c98d20d1263519f6e2948670368d807861)

The fix will be available with the upcoming 2.4.0 release.

**Comment by magento-engcom-team** [comment]
Based on the provided information internal tickets `MC-34531` were created.
