### ISSUE TITLE
Cash on delivery - store label is not being displayed on order/invoice/shipping/creditmemo details.

### ISSUE THREAD

**Issue by swnsma** [magento/magento2#27570]
### Preconditions (*)
1. Magento multi-store setup (Store A, store B)
2. 'Cache on delivery' payment method is enabled

### Steps to reproduce (*)
1. Change 'Cache on Delivery' method title in scope of store B configurations in Stores -> Config -> Sales Methods -> Payment Methods -> Cache On Delivery 
2. Place the Order with 'cache on delivery' in scope of Store B.
3. Open order details in Admin Panel

### Expected result (*)
1. The Payment Method name is being used from Order Store scope

### Actual result (*)
1. The Payment Method name is being used from Default Store scope

### Note
It is not looking wrong for me, because if you will try to print it - the correct label will be used (did not tried to send an email).
But, for example, **Check/Money Order** uses Store Label even in admin details which seems to be not consistent behaviour.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33090` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ledian-hymetllari** [comment]
@VladimirZaets @nuzil what is the status of this ticket? :-) Do I need to add anything please?

**Comment by slavvka** [comment]
Hi @swnsma. Thank you for your report. 
The issue has been fixed in magento/magento2#27582 by @ledian-hymetllari in 2.4-develop branch
Related commit(s):
 - [352a3d62bacff95cd896f1a289b3c15c1b707fa3](https://github.com/magento/magento2/commit/352a3d62bacff95cd896f1a289b3c15c1b707fa3)
 - [1bf3ef92fafa1c707c543627a7afe2d8b47b6698](https://github.com/magento/magento2/commit/1bf3ef92fafa1c707c543627a7afe2d8b47b6698)
 - [6f3d633594be54baaecd30aecc8210e4a4e9ed78](https://github.com/magento/magento2/commit/6f3d633594be54baaecd30aecc8210e4a4e9ed78)
 - [85fb9c8df8c254a6971a09e72a1c61a17e4e2132](https://github.com/magento/magento2/commit/85fb9c8df8c254a6971a09e72a1c61a17e4e2132)
 - [2368e8793d2cc737c0e175d9ffaf79d4e5a8a473](https://github.com/magento/magento2/commit/2368e8793d2cc737c0e175d9ffaf79d4e5a8a473)
 - [d8afb0e8b8721bdaa4e17238de1e8ff604c2cfe0](https://github.com/magento/magento2/commit/d8afb0e8b8721bdaa4e17238de1e8ff604c2cfe0)

The fix will be available with the upcoming 2.4.1 release.
