### ISSUE TITLE
Sales Order grid checkbox alignment issue in Admin

### ISSUE THREAD

**Issue by sudheers-kensium** [magento/magento2#27633]
Sales Order grid checkbox alignment issue

### Preconditions (*)

1. Magento: 2.3.4

### Steps to reproduce (*)

1. Admin -> Sales -> Orders
2.

### Expected result (*)

1. checkbox vertical-alignIt should be top 
![image](https://user-images.githubusercontent.com/50358141/78553458-e5571000-7826-11ea-8c10-11f5b91458f9.png)

### Actual result (*)

1. checkbox vertical-alignIt is middle
![image](https://user-images.githubusercontent.com/50358141/78553406-cfe1e600-7826-11ea-891d-587c20741f67.png)

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27633-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27633-2-4-develop.instances.magento-community.engineering/admin_3739](https://i-27633-2-4-develop.instances.magento-community.engineering/admin_3739)
Login: `8b0b862f` Password: `339333d5aac3`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hi @sudheers-kensium,
I have verified this issue in the Magento 2.4 instance. I think this is not an issue but the checkbox is displayed center of the box.

**See the screenshot:**
![Orders](https://user-images.githubusercontent.com/24711761/78557677-d70cf200-782e-11ea-86d8-0e6bc18d4202.png)

![Products](https://user-images.githubusercontent.com/24711761/78557682-d96f4c00-782e-11ea-9c88-1c079392c35a.png)

Thanks.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33106` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Hi @sudheers-kensium. Thank you for your report !!
I don't think this we should consider this as an issue.
It looks same for all the admin grids like customers,orders,invoices,products and for user perceptive alignment of checkbox is proper

**Comment by sudheers-kensium** [comment]
@krishprakash issue in all admin grids and issue is only latest versions, in older version alignment  top.

**Comment by slavvka** [comment]
Hi @sudheers-kensium. Thank you for your report. 
The issue has been fixed in magento/magento2#27642 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [d7cf1881141fd855ff79f611a31ea2570726bdc3](https://github.com/magento/magento2/commit/d7cf1881141fd855ff79f611a31ea2570726bdc3)
 - [77a4e8c44e1ee901d77aa8d6680fcd5365cd376d](https://github.com/magento/magento2/commit/77a4e8c44e1ee901d77aa8d6680fcd5365cd376d)
 - [6b8fc4c55272229164fde82ddbd631f771f302d7](https://github.com/magento/magento2/commit/6b8fc4c55272229164fde82ddbd631f771f302d7)
 - [8437ec57b5c13ac0753048d9cc1ff8530170ee94](https://github.com/magento/magento2/commit/8437ec57b5c13ac0753048d9cc1ff8530170ee94)
 - [7bf2131bd6303f4f59a20989440d9c25941ebb52](https://github.com/magento/magento2/commit/7bf2131bd6303f4f59a20989440d9c25941ebb52)
 - [c044b34e6cafd0cd005a2ee20caf2efa39693846](https://github.com/magento/magento2/commit/c044b34e6cafd0cd005a2ee20caf2efa39693846)

The fix will be available with the upcoming 2.4.0 release.
