### ISSUE TITLE
Unable to finish the purchase - Global Users - Multi-Website

### ISSUE THREAD

**Issue by TerreFra** [magento/magento2#27653]
### Preconditions (*)

1. Magento 2.3.4
2. Customer is logged in.
3. Multi country websites
   3.1 Main Website - For Europe
   3.2 USA Website - For USA (Allowed countries option - only USA selected)
4. Global accounts enabled.

### Steps to reproduce (*)

1. Log in.
2. Add a product to the cart and try to finish the purchase with the bank transfer.

### Expected result (*)

1. Order completed, redirect to the thank you page.

### Actual result (*)

1. Log an error message, preventing the purchase.  (This happens with all payment methods.)
![screenshot](https://user-images.githubusercontent.com/52470453/78775206-1efa5900-7996-11ea-929f-b67f23d247f8.png)

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-27653-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-27653-2-3-5-p1.instances.magento-community.engineering/admin_8a68](https://i-27653-2-3-5-p1.instances.magento-community.engineering/admin_8a68)
Login: `3056ad86` Password: `8b11b6680bc1`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@TerreFra: Tested the issue in both 2.3.5p1 and 2.4 develop instance the issue is not reproducible.
Please find the attachment below:
1. Two websites:
![image](https://user-images.githubusercontent.com/58288685/83431313-c6ef4880-a454-11ea-95e2-ab014bc9dbf9.png)
2.  USA Website - For USA (Allowed countries option - only USA selected)
![image](https://user-images.githubusercontent.com/58288685/83431365-db334580-a454-11ea-828c-9e886cbf6a78.png)
3. Able to place order 
**2.4devlop instance:**
![fvmDkrlkMF](https://user-images.githubusercontent.com/58288685/83432131-0b2f1880-a456-11ea-9e02-e1be303db3e5.gif)
 **2.3.5-p1 instance**
![j4NP7xDlqh](https://user-images.githubusercontent.com/58288685/83432179-1f731580-a456-11ea-9009-6ffc7d6115a2.gif)

**Comment by swathishs** [comment]
Hi @TerreFra, thank you for your report. According contributor's guide Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop| 2.3.5p1 branch.
If you'd like to update the issue, please reopen it.
