### ISSUE TITLE
What's the best Magento version for PHP Version 5.2.17

### ISSUE THREAD

**Issue by AYElsharif** [magento/magento2#2767]
My current hosting have PHP version 5.2.17 and MySQL version 5.6.26, It's shared hosting and I can not upgrade to the PHP 5.6, So .. What is the best "stable" version of Magento CE can I work on?

Thanks in advance

Abdulsalam.

**Comment by KAB8609** [comment]
PHP 5.2.17 was released in 2011. Magento 2.0 will not work for you, and anything above Magento 1.3 will not work for you. I would suggest finding a new host instead of using Magento 1.3 as there is just no support and so much has changed since 1.3. Even theme and extension companies don't support anything this old.

**Comment by davidalger** [comment]
@Elsharif GitHub issues are intended strictly for technical issues, not questions. Please take your questions to either the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/). That said, I agree with @KAB8609; if your host can't put on a box running a modern version of PHP you need to switch hosting providers.
