### ISSUE TITLE
Cookies Does not contain the secure flag on Fronted(checkout/cart)

### ISSUE THREAD

**Issue by Sharmilasrini95** [magento/magento2#27879]
Our site is SSL secured site, and Magento 'secure' and 'insecure' URL variables both point at https:// URL. However, the PCI audit indicated that cookies are insecure on the 'checkout/cart' page.

### Preconditions (*)

1.Magento 2.3.3
I have updated the  below patch https://github.com/magento/magento2/commit/2d1f8ca5d13c626000b34002704de9e0a99d3d99

but it seems not working

### Steps to reproduce (*)
**Frontend:**
1. Go to the shop front end
2. Add product to the cart
3. Go to the cart page
4. Go to developer mode
5. Click on application
6. Navigate to the left side and click on cookies
7. Check the secure column 

**Backend:**
1. Go to admin panel
2. Click on the store -configuration 
3. Click on the web in the left nav
4. Go to URL(secure) section
5. In "Secure base URL" check the URL is in https:
6. Check "user secure URLs on storefront" to be " yes"
7. Check "user secure URLs on admin" to be " yes"

### Expected result (*)

1. Secure cookies to show up in the Cookie panel

### Actual result (*)

1. Few cookies are set as secure. please find the attachment

![Screenshot (33)](https://user-images.githubusercontent.com/20103861/79557615-7d26ea80-80c0-11ea-9bb5-892834b09e28.png)

**Comment by Sharmilasrini95** [comment]
Can you check this, please? It is a very critical security issue to us.

**Comment by hostep** [comment]
I've just checked a couple of shops of ours and the ones running on 2.3.3-p1 have a lot fewer secure cookies then the ones running on 2.3.4-p1 or 2.3.5.
(the general availability of those versions will happen on 28 April, we already have pre-release access, that's why I can already test those)

The release notes of Magento 2.3.5 also say:
> Frontend cookies are now set as expected when you enable Use Secure URLs on Storefront and Secure Base URL is set to https.
Which links to this commit: https://github.com/magento/magento2/commit/a3ac3646a5fd63976d858821b7bea53d41e19f2d

So maybe it's best if you re-test after you upgraded to one of those newer versions after 28 April? Or after you tried to apply that other patch?

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-27879-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27879-2-4-develop.instances.magento-community.engineering/admin_5b6a](https://i-27879-2-4-develop.instances.magento-community.engineering/admin_5b6a)
Login: `a9d90124` Password: `ee8ea8266e21`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
The issue is been reproduced on the 2.4-develop branch

1. Only "private_content_version" is being checked as secure cookies

Attachments:
**Frontend:**
![image](https://user-images.githubusercontent.com/58288685/81042641-3281dc80-8ece-11ea-9e7c-ee54c0fed3ec.png)

**Admin :**
![image](https://user-images.githubusercontent.com/58288685/81042777-7b399580-8ece-11ea-83b7-a39db393a258.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34028` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @Sharmilasrini95. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-34028` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
