### ISSUE TITLE
Category filter not showing

### ISSUE THREAD

**Issue by jameswithers** [magento/magento2#2789]
On a default install (without the sample data), products are showing in categories, but category filters are not appearing in the left column as they do with sample data.

**Comment by davidalger** [comment]
@jameswithers This is typically because category filters are something which you must enable on a per-category basis for them to show up. Haven't checked M2 to make sure the label is the same, but in Magento 1 it was the "Is Anchor" setting on categories. I believe this operates the same way here. 

However, the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue (providing full steps to reproduce) if you have further reasons to consider this a bug. Thanks!
