### ISSUE TITLE
MFTF: Inconsistent case in Section name

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#27897]
`StorefrontMinicartSection` and `StorefrontMiniCartSection` are defined.
There should be consistency.

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33577` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your report. 
The issue has been fixed in magento/magento2#27955 by @engcom-Echo in 2.4-develop branch
Related commit(s):
 - [86ed309a4d29af95276fe309321ca1d4d6d5105f](https://github.com/magento/magento2/commit/86ed309a4d29af95276fe309321ca1d4d6d5105f)
 - [659e3bbfb8722ea2e9d3a96d0ce142492d587d91](https://github.com/magento/magento2/commit/659e3bbfb8722ea2e9d3a96d0ce142492d587d91)

The fix will be available with the upcoming 2.4.0 release.
