### ISSUE TITLE
Fixed Dollar Amount Cart Price Rule for Bundle Product shows discount on both items in order/invoice

### ISSUE THREAD

**Issue by mangamuri** [magento/magento2#27906]
### Preconditions (*)
1. Magento 2.3.4
2.

### Steps to reproduce (*)
1. Create 2 simple products
2. Create Bundle product and add above two simple products as options to customer choose one or two
3. Create Cart price rule to  apply fixed dollar amount discount  for simple product 1
4. Add both items in bundle to cart
5. Apply discount code
6. discount covers fixed price which is equal to product 1
7. create order

### Expected result (*)

1. [Screenshots, logs or description]
2. Order  and invoice shows the discount on two line items

### Actual result (*)

1. [Screenshots, logs or description]
2. Order and invoice only should show discount is applied to  only one product which was defined in cart price rule

**Comment by mangamuri** [comment]
@magento could you please give me 2.3.4-develop instance

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27906-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27906-2-4-develop.instances.magento-community.engineering/admin_35d2](https://i-27906-2-4-develop.instances.magento-community.engineering/admin_35d2)
Login: `8590ebbf` Password: `f5247ab1abc3`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
@mangamuri - can you please share the video about the cart price rule?

**Comment by mangamuri** [comment]
@ajijshekh123  Thanks for working on this issue

![image](https://user-images.githubusercontent.com/1827538/79992094-ac4eaa80-8478-11ea-9bec-9e9615127ffb.png)

![image](https://user-images.githubusercontent.com/1827538/79992127-b7a1d600-8478-11ea-8736-8c78cd25755c.png)

I have products configured as 

Bundle - Bundle product

Simple 1 - $150

Simple 2 - $100

Both simple products are part of bundle having option to select one or many. Hope this helps let me know if you need more details

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajijshekh123, here is your [Magento instance](https://i-27906-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27906-2-4-develop.instances.magento-community.engineering/admin_aa96](https://i-27906-2-4-develop.instances.magento-community.engineering/admin_aa96)
Login: `e62496ef` Password: `74608b5105e9`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment]
Hello @mangamuri,
First of all thanks for the given me valuable information.
I have verified this issue in 2 scenarios:
**Scenario 1:**
Cart rule create with added Bundle Product SKU - Coupon code successfully Applied
**Scenario 2:**
Cart rule creates with added Simple Product SKU - Coupon code not applied successfully. It is displayed as an error.
**See attached screenshot:**

![1](https://user-images.githubusercontent.com/24711761/80088750-8f9a9b80-857a-11ea-9f0d-3756365f1605.png)

![4](https://user-images.githubusercontent.com/24711761/80088766-92958c00-857a-11ea-9925-d2d417d7e406.png)

![2](https://user-images.githubusercontent.com/24711761/80088760-91645f00-857a-11ea-8fec-f3166906af1c.png)

![3](https://user-images.githubusercontent.com/24711761/80088765-91fcf580-857a-11ea-8e72-948b58dae1de.png)

**See the Order Success Page with Bundle Product SKU:**

![5](https://user-images.githubusercontent.com/24711761/80089016-ef914200-857a-11ea-8d58-5737111a21b9.png)


I think this issue is fixed on Magento 2.4 instance. Can I close this issue or not?

Thanks.

**Comment by mangamuri** [comment]
@magento please give me 2.4-develop instance to verify
