### ISSUE TITLE
Swiping through photorama pictures causes the page to move up/down

### ISSUE THREAD

**Issue by devranowski** [magento/magento2#27923]
### Preconditions (*)

1. A Magento 2.3.x instance.
2. At least one product with at least two images with certain dimensions (can be reproduced with 700x700 px).
3. iPhone + Safari Mobile.

### Steps to reproduce (*)

1. Go to mobile PDP.
2. Swipe through product images.

### Expected result (*)

1. When cycling through product images on mobile by swiping, the vertical movement of the page should be blocked. The page should not move up/down if the finger movement isn't 100% horizontal.

### Actual result (*)

1. When cycling through product images on mobile by swiping, if you don't swipe left/right 100% accurately (the finger movement is slightly diagonal), the entire page scrolls up/down.
2. https://drive.google.com/file/d/1UXTBR5i2SLDkPMqEv-l9N2Gilw73tz6w/view?usp=sharing

**Comment by jkbdbrnwsk** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jkbdbrnwsk. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jkbdbrnwsk, here is your [Magento instance](https://i-27923-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27923-2-4-develop.instances.magento-community.engineering/admin_4879](https://i-27923-2-4-develop.instances.magento-community.engineering/admin_4879)
Login: `b7d235bb` Password: `145998e99e3b`
Instance will be terminated in up to 3 hours.

**Comment by jkbdbrnwsk** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jkbdbrnwsk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by jkbdbrnwsk** [comment]
Valid on 2.3.x, cannot reproduce on the 2.4.x instance. Please be so kind to double check.

**Comment by Sutharsan27** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by Sutharsan27** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27, here is your [Magento instance](https://i-27923-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27923-2-3-4.instances.magento-community.engineering/admin_d11c](https://i-27923-2-3-4.instances.magento-community.engineering/admin_d11c)
Login: `5dae9e4f` Password: `d6c847312d00`
Instance will be terminated in up to 3 hours.

**Comment by Sutharsan27** [comment]
@jkbdbrnwsk not able to reproduce on 2.3.4 as well on 2.4. Please refer to the attached video recording. 

[https://drive.google.com/open?id=1KDsWFpBVKEXOqCVFVzK0MePfHNDrdeL4](https://drive.google.com/open?id=1KDsWFpBVKEXOqCVFVzK0MePfHNDrdeL4)

**Comment by jkbdbrnwsk** [comment]
Thank you for checking, @Sutharsan27! Would you be able to try to check this on an iPhone (Safari) as well? This is were I could reproduce it.

**Comment by Sutharsan27** [comment]
lol, don't have an Iphone @jkbdbrnwsk .

**Comment by Sutharsan27** [comment]
@jkbdbrnwsk got a device, will keep you posted

**Comment by Sutharsan27** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27, here is your [Magento instance](https://i-27923-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27923-2-3-4.instances.magento-community.engineering/admin_dcbe](https://i-27923-2-3-4.instances.magento-community.engineering/admin_dcbe)
Login: `e2ea229b` Password: `1e161ee8a011`
Instance will be terminated in up to 3 hours.

**Comment by Sutharsan27** [comment]
@jkbdbrnwsk not able to reproduce on iPhone, please refer below
https://drive.google.com/file/d/1KdsPsc4-U5b6fwx3XnWSdgmqARcULc4t/view?usp=sharing

**Comment by jkbdbrnwsk** [comment]
Can you please try one more time on a product with these two attached images added to the gallery? Perhaps the image size has to do with it. Thank you.

![ws12-orange_main_2](https://user-images.githubusercontent.com/7212882/80396877-9c3e2d00-88b5-11ea-9525-e3cd6dde1c31.jpg)
![ws12-orange_back_2](https://user-images.githubusercontent.com/7212882/80396881-9cd6c380-88b5-11ea-8dd1-5323d8ed94dc.jpg)

**Comment by Sutharsan27** [comment]
@jkbdbrnwsk , sure will try and let you know

**Comment by Sutharsan27** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27, here is your [Magento instance](https://i-27923-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27923-2-3-4.instances.magento-community.engineering/admin_5d06](https://i-27923-2-3-4.instances.magento-community.engineering/admin_5d06)
Login: `fa841e1e` Password: `86f12e9148e0`
Instance will be terminated in up to 3 hours.

**Comment by Sutharsan27** [comment]
Hi @jkbdbrnwsk , still not able to reproduce the issue. Uploaded with couple more 700 x 700 pixel images and works just fine. 
Please see the recordings [https://drive.google.com/file/d/1kOoI5im86WweFTRiIa1UYm82F6z519Xh/view?usp=sharing](url)
note: there will be a slight disturbance on the scroll and the page scrolls down, it was due to the finger position and not because of the scroll option.

**Comment by jkbdbrnwsk** [comment]
Thanks for checking, @Sutharsan27! What you are mentioning in your note is actually the kind of behavior I am reporting and one that my client would like to see blocked. On your screencast, the page is moving down a little bit probably because you are not swiping the images 100% horizontally (just a guess, though; that's how I was able to reproduce it). Is it possible to block the vertical scroll of the page whenever a user is interacting with fotorama?

**Comment by Sutharsan27** [comment]
@jkbdbrnwsk I will try to reproduce in 2.4.x and update this ticket.

**Comment by Sutharsan27** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27, here is your [Magento instance](https://i-27923-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27923-2-4-develop.instances.magento-community.engineering/admin_5fd2](https://i-27923-2-4-develop.instances.magento-community.engineering/admin_5fd2)
Login: `50b51af0` Password: `498a3069760c`
Instance will be terminated in up to 3 hours.

**Comment by Sutharsan27** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27, here is your [Magento instance](https://i-27923-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27923-2-3-4.instances.magento-community.engineering/admin_6909](https://i-27923-2-3-4.instances.magento-community.engineering/admin_6909)
Login: `3317d413` Password: `d9e1c2c639c8`
Instance will be terminated in up to 3 hours.

**Comment by Sutharsan27** [comment]
@jkbdbrnwsk Tried with multiple 700 X 700 pixel images on both 2.4-develop and 2.3.4 versions of Magento. As notified earlier, the issue is not reproducible in 2.4-develop but on 2.3.4 the issue is occuring onlyl on iOS + Safari Mobile browser. 

Please can you update the ticket under Pre Condition that the issue is with iOS + Safari Mobile browser. 

I have got some additional video for your reference, you can use them if you want. 

[2.3.4 Magento](https://drive.google.com/file/d/1LNBV8YhJNQmuZUV5fSdID3qcTq0NWjrW/view?usp=sharing)

[2.4-develop Magento](https://drive.google.com/file/d/1LFoc_dTEIodnDQQXJOft05XjGHNP01IL/view?usp=sharing)

Once you have the Pre Conditions updated, please let me know. Will have the respective label applied and move it for a fix. 

Thanks

**Comment by Sutharsan27** [comment]
@jkbdbrnwsk In addition to the update as per my comment above, please include the issue occurs when the images are at 700 x 700 pixel

**Comment by jkbdbrnwsk** [comment]
Thanks, @Sutharsan27! Done.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @devranowski,

Thank you for reporting and collaboration.

We have verified the issue in Latest Magento 2.4-develop instance and we are not able to reproduce the issue.when we are swiping the vertical movement is blocked if the finger movement isn't 100% horizontal.

Could you please try to reproduce the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @devranowski,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
