### ISSUE TITLE
Can't create/reset user password if user address is not valid

### ISSUE THREAD

**Issue by rafal-kos** [magento/magento2#27954]
### Preconditions (*)

1. Magento 2.4-develop
2. Open `Create New Account Options` and enable `Require Emails Confirmation`
3. Create user with address (no special validation) via admin

### Steps to reproduce (*)

1. Add some kind of validation to address fields (limit length for city name)

> UPDATE customer_eav_attribute SET validate_rules='{"input_validation":1,"min_text_length":0,"max_text_length":2}'
    WHERE attribute_id=(SELECT attribute_id FROM eav_attribute WHERE entity_type_id=2 AND attribute_code='city');

OR for example you could create a plugin `beforeSave` on `\Magento\Customer\Api\AddressRepositoryInterface` that will add custom validation of address data.
2. Go to frontend
3. Click `Sign In`
4. Click `Forgot Your Password?`
5. Fill fields and click `Reset My Password`
6. Open email and click `Set a New Password`

### Expected result (*)

1. Forgot password functionality should allow the user to reset password
2. Address data shouldn't be used in reset password process

### Actual result (*)

1. You will be redirected to `Forgot Your Password?` page

Problem is in class `Magento\Customer\Model\ForgotPasswordToken\ConfirmCustomerByToken` in method `execute` which runs save on customer object.

We should disable address validation in this process or make an error message more clear for user.

**Comment by sheepfy** [comment]
i can take this one :)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33734` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment]
Hello @rafal-kos  and @shikhamis11 

Could you please provide more details in the Description about
> Add some kind of validation to address fields (limit length for city name)

It is not clear how exactly it should be done

**Comment by rafal-kos** [comment]
@sdzhepa I've added case the case. The problem here is that Magento shouldn't load/save address data in this process

**Comment by sheepfy** [comment]
@rafal-kos  i have added this PR https://github.com/magento/magento2/pull/27972, if helps.
The customer repository also saves the address entity instead of saving only the confirmation column of customer entity.

**Comment by gabrieldagama** [comment]
Hi @rafal-kos. Thank you for your report. 
The issue has been fixed in magento/magento2#27972 by @sheepfy in 2.4-develop branch
Related commit(s):
 - [29621ba467e4c6e145558bba9b378e29b9192d56](https://github.com/magento/magento2/commit/29621ba467e4c6e145558bba9b378e29b9192d56)
 - [bc52285c77410de35d4ae5d9bcab06bea72977a0](https://github.com/magento/magento2/commit/bc52285c77410de35d4ae5d9bcab06bea72977a0)
 - [4f8f9f2ae93caadd2d63d587183d6ac78a3514c3](https://github.com/magento/magento2/commit/4f8f9f2ae93caadd2d63d587183d6ac78a3514c3)
 - [09964aef01166af84664b603c4d8fc1c84d0852f](https://github.com/magento/magento2/commit/09964aef01166af84664b603c4d8fc1c84d0852f)
 - [b7d5fa592063413e16251cc3743575d4baef5e5b](https://github.com/magento/magento2/commit/b7d5fa592063413e16251cc3743575d4baef5e5b)

The fix will be available with the upcoming 2.4.2 release.
