### ISSUE TITLE
Order information thorugh order repository

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#27982]
### Preconditions (*)

1. Magento 2.3.3 CE, Apache2
2. MySQL, AWS Ec2 instance, PHPstorm with magento extension

### Steps to reproduce (*)

1. Retrieve order information from order Id using repository (Magento\Sales\Api\OrderRepositoryInterface)
2.  Try to get shipping address like, `$this->orderRepository->get($orderId)->getShippingAddress()`
3. No suggestion as there's no shippingAddress method in repo

### Expected result (*)

1.  If method is not there it should not return shipping address from repo.

### Actual result (*)

1. Its returning shippingAdress without any error but PHPStorm (Magento plugin) not suggesting method. 

Solid confusion going on........

**Comment by VZeroCool** [comment]
As this is at code level I cant check in instance you are going to provide.

**Comment by engcom-Alfa** [comment]
Hi @VZeroCool . Thank you for your report.
It is expected behavior.
If you do the following:

`
$this->orderRepository->get($orderId)` - it returns order object
and order has this method:
`\Magento\Sales\Model\Order::getShippingAddress`

Also, you can following this scenario ( it is the same):

1) `$order = $this->orderRepository->get($orderId)`
2) `$address = $order->getShippingAddress()`

**Actual Result:** :heavy_check_mark: Its returns shipping Address

So, we have to close it.
Thanks!
