### ISSUE TITLE
Follow-up: #27631: inconsistency between catalog_product_index_eav and cataloginventory_stock_status

### ISSUE THREAD

**Issue by Notranslator** [magento/magento2#27993]
### Preconditions (*)
Magento 2.2.3 CE
This issue is a follow-up of issue #27631 and has the same preconditions.
In addition in Index management in Magento backend all indexes have "update on save".

### Steps to reproduce (*)
Place an order which has stock status "in stock" and quantity = 1 for a simple product.

### Expected result (*)
Stock status = "out of stock" and quantity = 0.
For both product table and index table.

SELECT * FROM mg_catalog_product_index_eav
Join mg_cataloginventory_stock_status on product_id = entity_id
where attribute_id= 115 and store_id =1
and value <> stock_status
-- Attribute_id 115 is the stock status variable.
-- store_id =1 is not relevant for this issue.
**Expected zero records.** 

### Actual result (*)
Stock status = "out of stock" and quantity = 0 for product table. OK!
Stock status = "in stock" in the index table. NOT OK!

SELECT * FROM mg_catalog_product_index_eav
Join mg_cataloginventory_stock_status on product_id = entity_id
where attribute_id= 115 and store_id =1
and value <> stock_status
**This yields one record (the record for the product I ordered)**

### Additional information:
When I reindex manually through Magento backend Index Management the index is still not updated.
When I reindex manually through SSH command:  php bin/magento indexer:reindex
I get everywhere "index has been rebuilt successfully" but the index is still not updated.

**Comment by Notranslator** [comment]
Problem is still there. I am now creating a new 2.4.1 site and then move all data to this shop. I have to find out if the problem is then still there.

**Comment by engcom-Bravo** [comment]
Hello @Notranslator 

Thank you for your report.

We have rechecked the reported issue on the latest 2.4-develop
The `catalog_inventory_stock_status` table contains 1 record with _Stock Status_ - 0 :heavy_check_mark: 
![stock status](https://user-images.githubusercontent.com/51680745/106595551-63c23280-655c-11eb-8af2-cb96538e598b.png)

The `catalog_product_index_eav` contains one record, no matter what is the Quantity and Stock Status of the product :heavy_check_mark: 
![eav](https://user-images.githubusercontent.com/51680745/106596043-27430680-655d-11eb-8e65-7c3ec00a07e7.png)

The query _SELECT * FROM catalog_product_index_eav Join cataloginventory_stock_status on product_id = entity_id where attribute_id= 99 and store_id =1 and value <> stock_status;_ returns one record with correct Quantity and Status :heavy_check_mark: 

when the product is Out of Stock, Qty 0
![stock status](https://user-images.githubusercontent.com/51680745/106596342-89037080-655d-11eb-8dd9-f32b609a41d7.png)

the same when the product is In Stock, Qty 1
![in](https://user-images.githubusercontent.com/51680745/106596525-cff16600-655d-11eb-8f94-884620051f55.png)

This is the expected behavior on 2.4-develop.
We have to close this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
