### ISSUE TITLE
Web Api to create customer don't validate payload data and create corrupted record

### ISSUE THREAD

**Issue by GDauer** [magento/magento2#28064]
### Preconditions (*)

1. Magento 2.3.3
2. PHP 7.2.22
3. nginx/1.10.3

### Steps to reproduce (*)

1. Send a post request to the endpoint **/rest/V1/customers**
2. In the payload send an invalid **group_id** (by default Magento has the ids: 0, 1, 2, 3)
3. **(optional)** Another strange thing is that we can send the request to create a customer without password and the api creates the register.
4. Example of Request:
![CreateCustomerBug](https://user-images.githubusercontent.com/48294687/80734243-418b1800-8ae5-11ea-8435-787f7db9b7bf.png)

### Expected result (*)

1. Should throws an Exception informing that the group_id are not found

### Actual result (*)

1. It's creates the client record successfully 
2. The client **can't** see products or add products to the quote
3. https://www.loom.com/share/bf9c71c78bd6427b9537285c6064eb80

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33923` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajithkumar-maragathavel** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-28064-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28064-2-4-develop.instances.magento-community.engineering/admin_0570](https://i-28064-2-4-develop.instances.magento-community.engineering/admin_0570)
Login: `c967ebf9` Password: `2ffe3e105b77`
Instance will be terminated in up to 3 hours.

**Comment by ajithkumar-maragathavel** [comment]
@magento I am working on this

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-28064-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28064-2-4-develop.instances.magento-community.engineering/admin_871e](https://i-28064-2-4-develop.instances.magento-community.engineering/admin_871e)
Login: `8101de4d` Password: `ff5ea4e48ac7`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @GDauer. Thank you for your report. 
The issue has been fixed in magento/magento2#28903 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [a16efb632ff2433a365e5126fbd0081e5882d70e](https://github.com/magento/magento2/commit/a16efb632ff2433a365e5126fbd0081e5882d70e)
 - [7f8dd4456dde2e6c435741905ac07ae36466243e](https://github.com/magento/magento2/commit/7f8dd4456dde2e6c435741905ac07ae36466243e)
 - [b0b6dc99dd05355b88d5a50eedb4ec90ae8be664](https://github.com/magento/magento2/commit/b0b6dc99dd05355b88d5a50eedb4ec90ae8be664)
 - [616f0827865ba282c1f9ea3ac33ec0a2c314a82a](https://github.com/magento/magento2/commit/616f0827865ba282c1f9ea3ac33ec0a2c314a82a)
 - [4ae198a6f6ce5a59abda1d0dd8b70f62baa19b42](https://github.com/magento/magento2/commit/4ae198a6f6ce5a59abda1d0dd8b70f62baa19b42)
 - [360173a2e8b11db2bbddd4a5922eff754e53df1d](https://github.com/magento/magento2/commit/360173a2e8b11db2bbddd4a5922eff754e53df1d)

The fix will be available with the upcoming 2.4.1 release.
