### ISSUE TITLE
Unexpected reference to \Zend\* namespace in 2.3.5-p1

### ISSUE THREAD

**Issue by rvitaliy** [magento/magento2#28061]
### Preconditions (*)
"magento/product-enterprise-edition": "2.3.5-p1"

### Steps to reproduce (*)
install project
find "Zend\" in path ./vendor/magento/*

### Expected result (*)
find nothing or only backward compatibility reference for \Zend\*

### Actual result (*)
find 1116 results with concrete reference for uninstalled vendros `\Zend\*`
example
`vendor/magento/framework/Console/GenerationDirectoryAccess.php` use `Zend\ServiceManager\ServiceManager;` but this class is does't exist.
![Screenshot from 2020-04-30 14-22-27](https://user-images.githubusercontent.com/1823711/80709751-2244b880-8aee-11ea-8582-9711d3dc0906.png)

**Comment by rvitaliy** [comment]
same for `./setup/*` folder

**Comment by ihor-sviziev** [comment]
Sorry, just closed by mistake

**Comment by ihor-sviziev** [comment]
Hi @rvitaliy,
This issue was already fixed in 2.4-develop branch. Related https://github.com/magento/magento2/pull/26436 and related commits https://github.com/magento/magento2/search?p=2&q=MC-13825&type=Commits

In 2.3.5-p1 there was installed laminas/laminas-zendframework-bridge, that loads Laminas classes instead of Zend, so everything looks good.

 Think we can close this issue
