### ISSUE TITLE
Magento 2.3.4 update product attributes in bulk is not working

### ISSUE THREAD

**Issue by mrixwan-407** [magento/magento2#28077]
### Preconditions (*)

1.magento 2.3.4
### Steps to reproduce (*)

1.Catalog->Products->Select All Products-> Update attributs ->Update Tax Class -> None to Tex-able

### Expected result (*)

1. Every Products Tax class should be updated

### Actual result (*)

1.Nothing Update Just show a message "Message is added to queue" 
2.

**Comment by mrixwan-407** [comment]
@magento give me Magento 2.3.4 instance

**Comment by mrixwan-407** [comment]
yes

**Comment by mrixwan-407** [comment]
@magento-engcom-team yes

**Comment by mrixwan-407** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @mrixwan-407. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @mrixwan-407, here is your [Magento instance](https://i-28077-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28077-2-4-develop.instances.magento-community.engineering/admin_6c40](https://i-28077-2-4-develop.instances.magento-community.engineering/admin_6c40)
Login: `ece7ba89` Password: `b2c9c850ac11`
Instance will be terminated in up to 3 hours.

**Comment by hostep** [comment]
@mrixwan-407: make sure queue consumer processes run, otherwise the messages in the queue won't be picked up.

The consumers are normally spawned by the cronjobs, so make sure those are running.
If they are running, then make sure your configuration in the `app/etc/env.php` file is correct and don't block the consumers from spawning, see the documentation: https://devdocs.magento.com/guides/v2.3/config-guide/mq/manage-message-queues.html#configuration

There are also a bunch of tips in the following issue: https://github.com/magento/magento2/issues/23450 which might help you figure out why in your instance it's not working.

Hope this helps!

**Comment by mrixwan-407** [comment]
@hostep  Thanks I fix it by your reference.
