### ISSUE TITLE
Virtual product order status set to closed not complete

### ISSUE THREAD

**Issue by j-robin-hunter** [magento/magento2#28175]
### Preconditions (*)

1. Version 2.3.4 OS (but affects earlier versions from 2.2)
2. Define a virtual product

### Steps to reproduce (*)

1. Create an order for a virtual product with no value (for example a demo software license)
2. Submit the order using with zero payment enabled

### Expected result (*)

1. The order should complete with the order status set to complete

### Actual result (*)

1. The order status is set to closed

This behaviour is cause by the code Magento\Sales\Model\ResourceModel\Order\Handler\State which includes a call to $order->canShip(). This calls always returns false if the product is virtual which in turn forces the order status to be set to closed. This cannot be avoided!

**Comment by j-robin-hunter** [comment]
Confirmed that the issue can be reproduced on a vanilla instance using version 2.3.4 - code not changed for 2.3.5 so this issue will remain

**Comment by j-robin-hunter** [comment]
This bug is a dupliacte of #25177

**Comment by eastern-raviraj** [comment]
Is it still exist in ersion 2.3.5 ? 

I am still facing this issue

**Comment by magento-quality-patches** [comment]
The patch solving a similar issue is available in [Magento Quality Patches](https://support.magento.com/hc/en-us/articles/360047139492) package (MQP)
 
**Patch**
MDVA-28656: Fixes the issue where if an order was placed with no payment information required (for example, with 100% discount) and an invoice was created for the order, the order status changes to Closed instead of Complete.
 
**Compatible versions**
Magento OpenSource/Commerce/Commerce Cloud 2.3.1 - 2.3.5, 2.4.0
 
:warning: We strongly recommend testing all patches in a staging or development environment before deploying to production.
 
**Applying a patch - Magento OpenSource/Commerce**
 
1. `$ composer require magento/quality-patches`
2. `$ ./vendor/bin/magento-patches apply MDVA-28656`
 
See [MQP Magento Commerce documentation](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/mqp.html)
 
**Applying a patch - Magento Commerce Cloud**
See [MQP Magento Commerce Cloud documentation](https://devdocs.magento.com/cloud/project/project-patch.html)
