### ISSUE TITLE
Inventory stock issue when creating a new disabled product

### ISSUE THREAD

**Issue by itwebdev2** [magento/magento2#28227]
### Steps to reproduce (*)

1. Magento 2.3.4-p2
2. Create a new product in the Magento admin ensuring that "Enable product" is set to "No", "Manage Stock" is set to yes and stock quantity is valid number (i.e. 100)
3. Wait for index to process new product via CRON
4. Update "Enable Product" to be "yes" and save the product
5. View product on frontend

### Expected result (*)

1. Product should appear on frontend (i.e. category pages, search, etc)
2. Product stock level should be 100

### Actual result (*)

1. Product does not show on frontend
2. Product shows as out of stock when viewed directly via URL

**Comment by itmsenior** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by itmsenior** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-28227-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28227-2-4-develop.instances.magento-community.engineering/admin_a36b](https://i-28227-2-4-develop.instances.magento-community.engineering/admin_a36b)
Login: `97121bce` Password: `061b1cee2f0a`
Instance will be terminated in up to 3 hours.

**Comment by Sutharsan27** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27, here is your [Magento instance](https://i-28227-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28227-2-4-develop.instances.magento-community.engineering/admin_f0c1](https://i-28227-2-4-develop.instances.magento-community.engineering/admin_f0c1)
Login: `34f08e67` Password: `9ed7851b7cc4`
Instance will be terminated in up to 3 hours.

**Comment by Sutharsan27** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by Sutharsan27** [comment]
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by Sutharsan27** [comment]
@magento give me 2.3.5 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by Sutharsan27** [comment]
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment]
Hi @Sutharsan27. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by itmsenior** [comment]
Hi @Sutharsan27 

Are you struggling to replicate the issue?

**Comment by Sutharsan27** [comment]
Hey @itwebdev2 , yea!! I tried with 2.4-develop and couldn't succeed. Wanted to check with the other versions before letting you know. 
Since you asked, Magento community are no longer accepting any pull requests to 2.3.x versions. So I got to have this recreated in 2.4-develop version.  I'm a bit lost in step 3 - Wait for index to process new product via CRON. Can you please be more specific on what to be done on Step 3?

I was able to add a new product with "Enable Product" toggle to "No" and no products were seen in front end. Also with "Enable Product" toggle set to "Yes"  and with "Cache" refreshed, the products are visible in Frontend

If you can help me with Step 3 in detail, I will have this recreaed in 2.4-develop, update the step(if needed) and have it moved for Dev Ready.

If you wish to have this closed, please let me know why. I will have the details recorded before me closing this one

**Comment by itmsenior** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by itmsenior** [comment]
@Sutharsan27 OK, thanks for looking into it.
I think this relates to MSI so I don't think I'll be able to replicate using the Magento instances.

**Comment by magento-engcom-team** [comment]
Hi @itwebdev2, here is your [Magento instance](https://i-28227-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28227-2-4-develop.instances.magento-community.engineering/admin_5933](https://i-28227-2-4-develop.instances.magento-community.engineering/admin_5933)
Login: `e0e0b22b` Password: `8cce7610d335`
Instance will be terminated in up to 3 hours.

**Comment by itmsenior** [comment]
@Sutharsan27 How do I confirm I can replicate the issue with instance if it requires Magento CRON & MSI?

**Comment by Sutharsan27** [comment]
@itwebdev2 Apologies for the delay, I will have to get in touch with the Magento team on how to get the MSI and Magento CRON enabled. I will keep you posted. 

Are these the only required setup to reproduce the issue, please confirm?

**Comment by Sutharsan27** [comment]
Hi @itwebdev,2 all issue specific for MSI should be reported in the MSI repo

fyi: @sidolov @smoskaluk @sdzhepa 

It seems this issue MSI specific and should be fixed in MSI repository.

EngCom team, please confirm and transfer this issue to the https://github.com/magento/inventory/issues

Closing this issue
