### ISSUE TITLE
Cart update qty performs two requests to controller

### ISSUE THREAD

**Issue by domeglic** [magento/magento2#28278]
### Preconditions (*)

1. Magento v2.3.5
2. 

### Steps to reproduce (*)

1. Put a product into cart and go to cart page
2. Update qty and press "Update Shopping Cart"

### Expected result (*)

1. One request to update qty

### Actual result (*)

1. Two requests are made, one has no effect

If you inspect requests that are made, the first one is to `checkout/cart/updateItemQty` and the second one to `checkout/cart/updatePost`

So already the qty is being updated twice. On top of that, the first controller doesn't save so it is essentially useless: https://github.com/magento/magento2/blob/2.3.5/app/code/Magento/Checkout/Controller/Cart/UpdateItemQty.php
There is nothing here that saves the quote after changing the qty, so nothing happens.

**Comment by domeglic** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @domeglic. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @domeglic, here is your [Magento instance](https://i-28278-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28278-2-4-develop.instances.magento-community.engineering/admin_b059](https://i-28278-2-4-develop.instances.magento-community.engineering/admin_b059)
Login: `cc0e5c64` Password: `c5dae475fc23`
Instance will be terminated in up to 3 hours.

**Comment by domeglic** [comment]
![image](https://user-images.githubusercontent.com/8225737/82311712-5f51eb80-99c6-11ea-8125-daa7158a34a7.png)

In 2.4-develop there are still two requests being made.

**Comment by posidonius** [comment]
I appear to also be experiencing this issue in 2.3.5 using Magento Blank theme. According to Nginx logs, the first request to `checkout/cart/updateItemQty/` results in 200 and the quantity is updated.

After that there is a request to `customer/section/load/?sections=messages&force_new_section_timestamp=true` with 200 result.

Then there is a request to `checkout/cart/updatePost/` which does a 302 redirect to the base url (homepage).

The cart quantity is updated but the visitor is redirected to the homepage instead of staying on the cart page.

**Comment by preeteshtavant** [comment]
Using Magento2.4.1, magento sending 2 request 1 for updateItemQty and another one is for updatePost.
why magento calling updateItemQty from cart. it seems it is not required
