### ISSUE TITLE
SearchCriteriaBuilder SortOrder missing random sort

### ISSUE THREAD

**Issue by DominicWatts** [magento/magento2#28315]
### Summary (*)

When using SearchCriteriaBuilder to be able to apply random sort

This is particularly useful when working with product collections

### Examples (*)

At the moment we're restricted to sort by ASC, DESC.

### Proposed solution

Introduce a mechanism which works the same as MySQL ORDER BY
 rand()

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DominicWatts** [comment]
Here is an example where I've used php to code a workaround but you can see how there is an issue when setting page size. Code becomes verbose.

```
            $this->searchCriteriaBuilder->addFilter(MessageInterface::STATUS, [Data::ENABLED], 'eq');

            if ($group->getSortby() == Data::ORDERLY) {
                $sortBySort = $this->sortOrderFactory
                    ->create()
                    ->setField(MessageInterface::SORT)
                    ->setDirection(SortOrder::SORT_ASC);
                $sortByName = $this->sortOrderFactory
                    ->create()
                    ->setField(MessageInterface::NAME)
                    ->setDirection(SortOrder::SORT_ASC);
                $this->searchCriteriaBuilder->setSortOrders([$sortBySort, $sortByName]);
                if ($limit = $group->getLimit()) {
                    $this->searchCriteriaBuilder->setCurrentPage(Data::FIRST_PAGE);
                    $this->searchCriteriaBuilder->setPageSize((int) $limit);
                }
            }

            $searchCriteria = $this->searchCriteriaBuilder->create();
            $result = $this->messageRepositoryInterface->getList($searchCriteria)->getItems();
            if ($group->getSortby() == Data::RANDOM) {
                shuffle($result);
                if ($limit = $group->getLimit()) {
                    return array_slice($result, 0, (int) $limit);
                }
                return $result;
            }
            return $result;
```

**Comment by Serializator** [comment]
At first I was hesitant to agree with this but I looked a bit into the possible implementation and saw that `Magento\Framework\DB\Select` does support random sorting but it gets abstracted away.

Aside from the seeming support for it, achieving truly random sorting but at the same time be able to use the API (use the repositories and search criteria instead of collections directly) doesn't seem possible right now.

What I mean with "truly random sorting" is random sorting based on all the rows present in MySQL instead of a subset which gets returned based on your search criteria and then gets randomly sorted. 

I might be missing something so if I'm wrong, please correct me ;-)

**Comment by DominicWatts** [comment]
You are correct 

Factory collections have methods to support this

https://github.com/magento/magento2/blob/2.3/app/code/Magento/Sales/Model/ResourceModel/Order/Item/Collection.php#L75-L79

But completely overlooked in sortorder

**Comment by Serializator** [comment]
If this were to be added it'd impact the following classes, at least, the ones I've found till now.

- `Magento\Framework\Data\Collection\AbstractDb`
- `Magento\Eav\Model\Entity\Collection\AbstractCollection`
- `Magento\Catalog\Model\ResourceModel\Product\Collection`
- `Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection`
- `Magento\Reports\Model\ResourceModel\Review\ProductCollection`

In `Magento\Eav\Model\Entity\Collection\AbstractCollection` there is a method (`addAttributeToSort`) which has a special case for attributes that have `validate-digits` as frontend model. I don't think `orderRand` can be used for this, as it uses a special expression.

It depends on what solution you'd choose but a new method or `orderRand` in `Magento\Framework\DB\Adapter\Pdo\Mysql` would have to be extended to allow for both a field and an expression.

I don't know what'd have to happen to add support for ElasticSearch. At least, I think support for ElasticSearch would have to be added looking at the differentiation `addAttributeToSort` in `Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection` makes based on the `DefaultFilterStrategyApplyCheckerInterface`. 

Just kinda spitballing right now because at first (obviously) it looked like something that'd be relatively easy to implement, up till now.
