### ISSUE TITLE
Interception doesn't Work with the `Magento\Framework\App\StaticResource` Application

### ISSUE THREAD

**Issue by astorm** [magento/magento2#2832]
The attached extension contains the following di.xml configuration.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\Filesystem\Driver\File">
        <plugin name="pulsestorm_fixstaticassetsymlinks_magento_framework_filesystem_driver_file" type="Pulsestorm\FixStaticAssetSymlinks\Plugin\MagentoFrameworkFilesystemDriverFile"/>
    </type>
</config>
```

When processing a request from the main Magento application (`index.php`/`pub/index.php`) this `di.xml` works.  An interceptor for `Magento\Framework\Filesystem\Driver\File` is created.

However, when processing a request for the static asset serving application `pub/static.php` this `di.xml` does NOT work.  

It's not clear if this is a bug or designed behavior.  However, allowing plugins in the static asset serving application would allow Magento developers to solve many of their own problem in a clean efficient way.  For example, I discovered this behavior while trying to [come up for a work around for the problems the the static asset generator has with symlinks](http://magento.stackexchange.com/a/93238/4).

Steps to Reproduce:
1. Install the attached module
2. Compile all classes (important!)
2. Use the object manager to instantiate a `Magento\Framework\Filesystem\Driver\File` object in the context of the main Magento application -- use `get_class` to inspect its actual class.
3. Use the object manager to instantiate a `Magento\Framework\Filesystem\Driver\File` object in the context of the static asset generator -- use `get_class` to inspect its actual class.

Expected Behavior: Both objects are `Magento\Framework\Filesystem\Driver\File\Interceptor` object

Actual Behavior: One object is a `Magento\Framework\Filesystem\Driver\File\Interceptor` object, the second is a `Magento\Framework\Filesystem\Driver\File` object.

[Pulsestorm_FixStaticAssetSymlinks.zip](https://github.com/UltimateModuleCreator/Umc_Base/files/73615/Pulsestorm_FixStaticAssetSymlinks.zip)

**Comment by dkvashninbay** [comment]
Hi,

This use case looks strange with this step "Compile all classes (important!)".
What kind of compilation is that? As there are two types of "compilation": 
- setup:di:compile 
- setup:di:compile-multi-tenant

Both of them are meant to be run to prepare for production mode (i.e static content is deployed already):
http://devdocs.magento.com/guides/v2.0/howdoi/deploy/deploy-to-prod.html#deploy-dev (p.4-5).

It means that there is no user case, required to access static.php in production mode (with compiled code).

**Comment by astorm** [comment]
@dkvashninbay That's just a quick way to get to a reproducible state. The core issue is the static file serving application uses object manager managed objects, but those objects don't obey the settings in `di.xml`

**Comment by dkvashninbay** [comment]
@astorm 
Ok, i've compiled the code (setup:di:compile command), and put a breakpoint at https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/App/StaticResource.php#L105 
and put some code there:

``` php
$f = $this->objectManager->create('Magento\Framework\Filesystem\Driver\File');
$f->getAbsolutePath('bla', 'bla');
```

which led me directly to 

``` php
var_dump("Called" . __FILE__);
```

  So this issue is not reproducible or it has some unmentioned steps.

But this is not the your case, as you want to intercept \Magento\Framework\Filesystem\Driver\File at the start of application, right?

Magento has several layers of configuration which are merged in that order:
- _primary_ - app/etc/di.xml
- _global_ - [module]/etc/di.xml
- _myarea_ - [module]/etc/myarea/di.xml

So if any application component requests an instance of \Magento\Framework\Filesystem\Driver\File (File next) in context of _primary_ area, it will receive an instance of File as it is configured in _primary_ area only.

Your case is that some application components, you want to intercept are configured and initiated in context of _primary_ area, so they receive File which in current context doesn't have any plugins, i.e is not intercepted.
So configuration of File in _global_ area is a bit _late_ for such purpose, as initiated shared instances at _primary_ area are not being initiated again on new configuration merge.
What you can do is to modify _primary_ configuration if it is applicable for you :)

**Comment by astorm** [comment]
@dkvashninbay I'm not sure I follow that -- Jumping up a few abstraction layers, would it be accurate to say the static file serving application  is deliberately designed to **not** allow module developers to use `di.xml` features?

**Comment by dkvashninbay** [comment]
I've done more debugging on this and it seems that this not only about static application, but interception of File Driver is impossible because of that particular class (and all clients which are using this shared instance/configured by default):
[\Magento\Framework\Filesystem\DriverPool](https://github.com/magento/magento2/blob/2.0/lib/internal/Magento/Framework/Filesystem/DriverPool.php#L81)

So during assets publication StaticApplication(or any application) is using shared instance of [\Magento\Framework\Filesystem\Directory\ReadFactory](https://github.com/magento/magento2/blob/2.0/lib/internal/Magento/Framework/Filesystem/Directory/ReadFactory.php#L26) which is configured by raw initiated DriverPool (which happened in process of OM initialisation):
[\Magento\Framework\App\ObjectManagerFactory](https://github.com/magento/magento2/blob/2.0/lib/internal/Magento/Framework/App/ObjectManagerFactory.php#L257)

I'll create a ticket which is describing this particular problem.
Thanks!

**Comment by shiftedreality** [comment]
Internal ticket MAGETWO-47697 was created

**Comment by astorm** [comment]
Any update on this issue?  As an outside developer, my main question here is still which Magento application entry points load which `di.xml` files.  My programmer side wants to be able to use modules to change/improve the behavior of he static asset serving application via a module's `di.xml` file, but I can see reasons for not implementing that.  I clear and well documented set of how and why `di.xml` files get loaded based on application entry point and application area may be the solution.

/cc @piotrekkaminski @alankent @antonkril, opened issue with dev docs to ping them as well https://github.com/magento/devdocs/issues/654

**Comment by astorm** [comment]
No update since January of this year.  Assuming it's a deliberate design decision to have the di system work different for different applications.  Closing out.
