### ISSUE TITLE
Incorrect CSS selector in shipment page

### ISSUE THREAD

**Issue by yavuz** [magento/magento2#28345]
https://github.com/magento/magento2/blob/c9a246a100a0208ea156a3596864d638a2a0cfa3/app/code/Magento/Sales/view/frontend/templates/order/print/shipment.phtml#L64

I think this line should be like this.

`<div class="box box-order-billing-address">`

Am I wrong?

**Comment by sdzhepa** [comment]
Hello @yavuz 
fyi: @mrtuvn 

Could you please provide more details about the issue?
- How it impacts product or functionality?
- What functional flows are broken due to this issue?

Or its just typo that does not affect any functionality?

**Comment by mrtuvn** [comment]
@sdzhepa for me just clean up code remove deprecated method call in previous. Validate code and correct class follow correct context inside

**Comment by slavvka** [comment]
Hi @yavuz. Thank you for your report. 
The issue has been fixed in magento/magento2#28639 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [f35fb2bbc50e7acb0a88706ccc5ea1cf2ddbdcae](https://github.com/magento/magento2/commit/f35fb2bbc50e7acb0a88706ccc5ea1cf2ddbdcae)
 - [add79e6c1ee00c29a45211f018a35161f4f6cf1d](https://github.com/magento/magento2/commit/add79e6c1ee00c29a45211f018a35161f4f6cf1d)

The fix will be available with the upcoming 2.4.1 release.
