### ISSUE TITLE
Magento 2 settings cannot be edited in admin when we have run magento app: config: dump in developer mode

### ISSUE THREAD

**Issue by Hanhan1989** [magento/magento2#28346]
### Preconditions (*)

1. Magento 2.3.5-p1
2.  php7.3.x
3. mysql 5.7
4. Linux Ubuntu 20.x

### Steps to reproduce (*)

1. Set the Magento in developer mode. 
2. Run the command `magento app: config: dump`
3. Go to admin, for example: Click Stores > Settings > Configuration > Advanced > System > Full Page Cache.
4. The options are desabled. 

### Expected result (*)

1. The options should be editable in the development stage. 

As it says in the magento 2 documentation. we must be able setting configurations in admin in development stage  

> - Set the configuration in the Magento Admin.
> - Use the magento app:config:dump command to write the configuration to the file system.
> - Add your modified code and the shared configuration to source control.

![image](https://user-images.githubusercontent.com/11807165/82740945-c4eb0280-9d4d-11ea-9633-5c187810f13c.png)

https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/technical-details.html

### Actual result (*)

1. The options are disabled

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Hanhan1989 thank you for your report. After run `app:config:dump` any configuration settings in `config.ph`p or `env.php` are [locked](https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/technical-details.html#configuration-settings-locked-in-the-magento-admin) in the Magento Admin - this is expected behavior. Here: [Recommended pipeline deployment workflow](https://devdocs.magento.com/guides/v2.3/config-guide/deployment/pipeline/technical-details.html#config-deploy-workflow)
To export specific configuration you could use [config types](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-export.html) for command `app:config:dump`
After export configuration to file you could use `config:set` to change configuration:
https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-config-mgmt-set.html

If you'd like to update the issue, please reopen it.

**Comment by Hanhan1989** [comment]
Can you create the functionality that all options are unlocked in a specific mode?
For example: all settings are unlocked when we run
` bin / magento deploy: mode: set developer`

Thanks

**Comment by engcom-Delta** [comment]
@Hanhan1989 feel free to create issue in [community-features](https://github.com/magento/community-features/issues) repo for further discussion
