### ISSUE TITLE
CSP customization through backend

### ISSUE THREAD

**Issue by vincent-jacq** [magento/magento2#28363]
### Description (*)

The CSP implementation of Magento is great, but not easily changed by the admin users. Everytime a new domain needs to be whitelisted, we need to update the code and redeploy.
What I propose is to add something in the store configuration (ex: "Store > Configuration > Security > CSP") to add custom domain / other to be added for different policies. I think for security reason this should maybe only be available for the frontend part of Magento so the admin CSP always stay the same, but I'm no security expert.

### Expected behavior (*)

One way to make this may be to add a DynamicRow configuration key with at least 3 columns : 
1) Policy : a select with the list of policies handled by the CSP
2) Value : a text input for the user to define the rule (ex: https://domain.com, data:, etc.)
3) Enabled : checkbox (default: checked) so we can disabled some rules without deleting it completely.

This dynamic row would have a "website" scope so we can define different CSP depending on the website.

### Benefits

This should prevent the need to re-deploy everytime we need a new domain authorized. In my case, the marketing team usually add JS plug-in through Google Tag Manager and do so on their own, but the scripts always get blocked by the CSP rules, so they need to synchronize with us to add it to the whitelist. In the current Magento CSP implemetation, we would need to redeploy the project everytime.

### Additional information

I'm not an expert on security, so there may be things that need to be blocked in the configuration key that could allow attackers to get through, but I don't think there is...?

**Comment by ihor-sviziev** [comment]
Hi @vincent-jacq,
I would say that it was done in purpose without any configuration on the backend in order due to security reasons. 
**Example:**
potential hacker get access to the admin with all permissions, he added some script to the head scripts.

In current implementation (no ability to add policies) that javascript will not be able to send any customer data to their server/domain.

In case if we'll implement such ability - the admin user will just create a new policy that will allow to send customer data to their server/domain.

Does it make sense?

**Comment by ihor-sviziev** [comment]
Hi @vincent-jacq,
Unfortunately, we didn't get any input from you. I'm closing this issue as not relevant, more details in https://github.com/magento/magento2/issues/28363#issuecomment-725939261.

If you still believe we need to have such ability and could some use case - please just drop the comment here.

Thank you so much for your contribution!
