### ISSUE TITLE
Downloadable product is available in My Download Products tab after it has been partially refunded 

### ISSUE THREAD

**Issue by YaninaPrudnikova** [magento/magento2#28388]
### Preconditions (*)

1. Magento CE 2.3.5 wih sample data is installed.
2. Order with a download product and a product, requiring shipping, (e.g. simple product) is created.
3. The downloadable product is available in My Downloadable Products tab.

### Steps to reproduce (*)

1. Open this order page in Admin.
2. Perform a partial refund for the downloadable product (the other product is not refunded).
3. Go to My Downloadable Products tab.

### Expected result (*)

1. Downloadable product cannot be downloaded.

### Actual result (*)

1. Downloadable product still can be downloaded.
![order page](https://user-images.githubusercontent.com/66016118/83023196-40da9880-a035-11ea-90ae-17d1e44204f5.png)
![My DP tab](https://user-images.githubusercontent.com/66016118/83023205-43d58900-a035-11ea-916c-589349799426.png)

### Additional information 
Issue also reproduce on the lates `2.4-develop` https://github.com/magento/magento2/issues/28388#issuecomment-635249996

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28388-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28388-2-4-develop.instances.magento-community.engineering/admin_2f57](https://i-28388-2-4-develop.instances.magento-community.engineering/admin_2f57)
Login: `834c9a5f` Password: `3933fe214544`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment]
@YaninaPrudnikova: Issue is reproducible in Magento 2.4-develop instance 

Please find the attachment below:

1. Shopping cart:
![image](https://user-images.githubusercontent.com/58288685/83128784-882a5d00-a0f9-11ea-8639-1da09133044c.png)

2. Downloaded product before invoice:
![image](https://user-images.githubusercontent.com/58288685/83128904-ad1ed000-a0f9-11ea-8022-a55523b16c3d.png)

3. Order invoiced:
![image](https://user-images.githubusercontent.com/58288685/83128958-c031a000-a0f9-11ea-8978-30e70cc4fdbc.png)

4. Partially refunded:
![image](https://user-images.githubusercontent.com/58288685/83129039-db041480-a0f9-11ea-9ca7-4d52a2ffbdc5.png)

5. Able to download downloaded product:
![image](https://user-images.githubusercontent.com/58288685/83129090-eeaf7b00-a0f9-11ea-9417-b87aea9478ee.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34710` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ProkopovVitaliy** [comment]
I will work on this issue.

**Comment by magento-engcom-team** [comment]
Hi @YaninaPrudnikova. Thank you for your report. 
The issue has been fixed in magento/magento2#28413 by @ProkopovVitaliy in 2.4-develop branch
Related commit(s):
 - [a6f460dbe499df42c69af40b0fd51e05d0d6aa39](https://github.com/magento/magento2/commit/a6f460dbe499df42c69af40b0fd51e05d0d6aa39)
 - [9a83830b52446566d64531b267e0132800ae1ac4](https://github.com/magento/magento2/commit/9a83830b52446566d64531b267e0132800ae1ac4)
 - [96c9d5408d887f44d6e7b62cedd3b1160cd2465e](https://github.com/magento/magento2/commit/96c9d5408d887f44d6e7b62cedd3b1160cd2465e)
 - [59cf9f7d321fdc4278478e9e656f64584e95b80c](https://github.com/magento/magento2/commit/59cf9f7d321fdc4278478e9e656f64584e95b80c)
 - [c6c32315d1a98f0faa4d7a5581dda48a4c2f84dd](https://github.com/magento/magento2/commit/c6c32315d1a98f0faa4d7a5581dda48a4c2f84dd)
 - [eafdb17d9775a3d77b3cb8a4ca548d3b79a4f918](https://github.com/magento/magento2/commit/eafdb17d9775a3d77b3cb8a4ca548d3b79a4f918)
 - [92fd06b2dab671d99363440f8cf935cb48c583a7](https://github.com/magento/magento2/commit/92fd06b2dab671d99363440f8cf935cb48c583a7)
 - [1f7eace566744d292a5430afc38ec833e6f06f79](https://github.com/magento/magento2/commit/1f7eace566744d292a5430afc38ec833e6f06f79)
 - [db84d3afad32c2e6a361a19ade83b86d8236469d](https://github.com/magento/magento2/commit/db84d3afad32c2e6a361a19ade83b86d8236469d)
 - [d0a0962663e6b49e1c2dbffb0967887002b06048](https://github.com/magento/magento2/commit/d0a0962663e6b49e1c2dbffb0967887002b06048)
 - [aea9276635ad3595b8890035e87dfd17e580bf98](https://github.com/magento/magento2/commit/aea9276635ad3595b8890035e87dfd17e580bf98)
 - [1be2cd7259752e77bb1e59adbdffbf8dd0ef109b](https://github.com/magento/magento2/commit/1be2cd7259752e77bb1e59adbdffbf8dd0ef109b)
 - [dee9b16ee2515bd90f01ce63939660fd6e4f69ac](https://github.com/magento/magento2/commit/dee9b16ee2515bd90f01ce63939660fd6e4f69ac)
 - [a49709f0ba48954ff21b16e0314f46be23b3ef3e](https://github.com/magento/magento2/commit/a49709f0ba48954ff21b16e0314f46be23b3ef3e)
 - [8023f42f3d6dea08249b200670e16d53de1a5037](https://github.com/magento/magento2/commit/8023f42f3d6dea08249b200670e16d53de1a5037)
 - [9e312469d8101f47c6221a387e1b8e77fabf0f58](https://github.com/magento/magento2/commit/9e312469d8101f47c6221a387e1b8e77fabf0f58)
 - [d91b3058b5429dbb4f1d0e0fbaaab3180dfbb2d0](https://github.com/magento/magento2/commit/d91b3058b5429dbb4f1d0e0fbaaab3180dfbb2d0)
 - [62e486679859540f0a64581cc39a79634e517eba](https://github.com/magento/magento2/commit/62e486679859540f0a64581cc39a79634e517eba)
 - [97df424e66104260e10970ee13d27d9b1e863f4b](https://github.com/magento/magento2/commit/97df424e66104260e10970ee13d27d9b1e863f4b)
 - [2d58988451bd736066e24c7be7f42508e753791f](https://github.com/magento/magento2/commit/2d58988451bd736066e24c7be7f42508e753791f)
 - [87d898405f0237c0b5fc445f82dfb81c9e7d1469](https://github.com/magento/magento2/commit/87d898405f0237c0b5fc445f82dfb81c9e7d1469)

The fix will be available with the upcoming 2.4.2 release.
