### ISSUE TITLE
Unable to export low stock report in 2.3.4 

### ISSUE THREAD

**Issue by thomas-harding** [magento/magento2#28471]
### Preconditions (*)

1. Magento CE 2.3.4
2. PHP 7.2

### Steps to reproduce (*)

1. Log in to admin panel. Go to Reports > Products >Low Stock
2. Locate "Export To" form, select CSV and click "Export"
3. An error message shows

### Expected result (*)

1. The browser serves me a downloadable CSV

### Actual result (*)

1. An error message shows

```
Fatal error: Uncaught Error: Call to a member function getCsvFile() on bool in /domains/magentosite.com/http/vendor/magento/module-inventory-low-quantity-notification-admin-ui/Controller/Adminhtml/Report/ExportLowstockCsv.php:41 Stack trace: 
#0 /domains/magentosite.com/http/vendor/magento/framework/App/Action/Action.php(108): Magento\InventoryLowQuantityNotificationAdminUi\Controller\Adminhtml\Report\ExportLowstockCsv->execute() 
#1 /domains/magentosite.com/http/vendor/magento/module-backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) 
#2 /domains/magentosite.com/http/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) 
#3 /domains/magentosite.com/http/vendor/magento/framework/Interception/Interceptor.php(138): Magento\InventoryLowQuantityNotificationAdminUi\Controller\Adminhtml\Report\ExportLowstockCsv\Interceptor->___callPare in /domains/magentosite.com/http/vendor/magento/module-inventory-low-quantity-notification-admin-ui/Controller/Adminhtml/Report/ExportLowstockCsv.php on line 41
```

**Comment by thomas-harding** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @thomas-harding. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @thomas-harding, here is your [Magento instance](https://i-28471-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28471-2-4-develop.instances.magento-community.engineering/admin_81f9](https://i-28471-2-4-develop.instances.magento-community.engineering/admin_81f9)
Login: `362898c6` Password: `aa8b39700bad`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@thomas-harding: The issue is not reproducible in magento2.4 develop instance. Able to download the low stock report.

Please find the attachments below:
1.Low stock grid:
![image](https://user-images.githubusercontent.com/58288685/83531369-86ea9d00-a50a-11ea-82d8-794e57137d66.png)
2. Download lock stock:
![as6t6FN0Nn](https://user-images.githubusercontent.com/58288685/83531596-d3ce7380-a50a-11ea-9c8c-00c6224d14a4.gif)

**Comment by swathishs** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by swathishs** [comment]
The issue is not reproducible in Magento 2.3.5-p1  instance. Able to download the low stock report.

Please find the attachment below:
1. Low stock grid:
![image](https://user-images.githubusercontent.com/58288685/83615293-fb254f00-a5a3-11ea-9914-dace448fb9ce.png)
2. Downloaded file:
![image](https://user-images.githubusercontent.com/58288685/83615342-0d06f200-a5a4-11ea-8652-490a737f2e21.png)

**Comment by swathishs** [comment]
Hi @thomas-harding, thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch and 2.3.5-p1 instance.
If you'd like to update the issue, please reopen it.

**Comment by zbigniewKurasLM** [comment]
The issue is reproducible in Magento 2.3.5-p1 instance. There is a missing update handle in 
`vendor/magento/module-inventory-low-quantity-notification-admin-ui/view/adminhtml/layout/inventorylowquantitynotification_report_exportlowstockcsv.xml`
To fix this issue you have to add:
`<update handle="inventorylowquantitynotification_lowstock_grid"/>`

**Comment by zbigniewKurasLM** [comment]
The issue is reproducible in Magento 2.3.5-p1 instance. There is a missing update handle in
`vendor/magento/module-inventory-low-quantity-notification-admin-ui/view/adminhtml/layout/inventorylowquantitynotification_lowstock_grid.xml`
To fix this issue you have to add:
`<update handle="reports_report_product_lowstock"/>`

**Comment by dverkade** [comment]
I can confirm we have this issue on Magento 2.3.5 and Magento 2.3.5-p1 as well.

**Comment by dverkade** [comment]
I've identified this is en issue with the Magento_InventoryLowQuantityNotificationAdminUi module from Magento MSI / Inventory. Will raise a ticket in that project.
