### ISSUE TITLE
Implement the schema for PayPal PayFloPro

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28520]
As a Magento End Customer,

I would like the ability to store my Paypal (PayFloPro) payment method details in myaccount

so that 

I can expedite the future checkout process by not having to reenter the payment details.

 

+*Acceptance Criteria*+
 * During checkout customers can specify if they want to store the payment details in myaccount for future purchases.
 * Payment details are not saved if the customer doesn't select the save payment details option.
 * Feature only available for logged-in customers (not available during guest checkout). 

**Approved Schema**
https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/payflowpro-vault.md

**Comment by magento-engcom-team** [comment]
Hi @nrkapoor. Thank you for your report. 
The issue has been fixed in magento/magento2#28821 by @Usik2203 in 2.4-develop branch
Related commit(s):
 - [d29468da99c7dae39be1dbef880edd867440891f](https://github.com/magento/magento2/commit/d29468da99c7dae39be1dbef880edd867440891f)
 - [e798f7553d6ab21132d476ef0d7f7ab7a99475ea](https://github.com/magento/magento2/commit/e798f7553d6ab21132d476ef0d7f7ab7a99475ea)
 - [934db87d56bad355d759925aff9fe837c61ef398](https://github.com/magento/magento2/commit/934db87d56bad355d759925aff9fe837c61ef398)
 - [aef0f96fdc93dbfe01817426178223b73aae5088](https://github.com/magento/magento2/commit/aef0f96fdc93dbfe01817426178223b73aae5088)
 - [dee50092ec72e5265ced5250aa8842c20fe7a0f6](https://github.com/magento/magento2/commit/dee50092ec72e5265ced5250aa8842c20fe7a0f6)
 - [2e6e63ecf38a1b6679cca324c278bf7d5cf692c6](https://github.com/magento/magento2/commit/2e6e63ecf38a1b6679cca324c278bf7d5cf692c6)
 - [f714e123857be2cc5fde9f43c16dd9fcdbdec3da](https://github.com/magento/magento2/commit/f714e123857be2cc5fde9f43c16dd9fcdbdec3da)
 - [009a3ba8514b975367f8b17fda0d5e5ffd01d587](https://github.com/magento/magento2/commit/009a3ba8514b975367f8b17fda0d5e5ffd01d587)
 - [c28747d0899432aa0978df50396c2795b6cacc44](https://github.com/magento/magento2/commit/c28747d0899432aa0978df50396c2795b6cacc44)
 - [6596e6542f2904510e4155be37660e8a0e79948a](https://github.com/magento/magento2/commit/6596e6542f2904510e4155be37660e8a0e79948a)
 - [d6a2fb7a979296406b39dbf09684f3b8844f0362](https://github.com/magento/magento2/commit/d6a2fb7a979296406b39dbf09684f3b8844f0362)
 - [57b733fdd4a59492b6b09842a287654f8044a759](https://github.com/magento/magento2/commit/57b733fdd4a59492b6b09842a287654f8044a759)
 - [1422df6a8dcdd8aa9cef74fc62c1ccf6fdbbea5a](https://github.com/magento/magento2/commit/1422df6a8dcdd8aa9cef74fc62c1ccf6fdbbea5a)
 - [dbb34278aa50eb4ed5e9c428820a059d7199a922](https://github.com/magento/magento2/commit/dbb34278aa50eb4ed5e9c428820a059d7199a922)
 - [6b3da47001d7ede2dcb7d6bf78a88140fe2b83b6](https://github.com/magento/magento2/commit/6b3da47001d7ede2dcb7d6bf78a88140fe2b83b6)
 - [1baeb2128a59b70defb78d483a6ba669fd294c08](https://github.com/magento/magento2/commit/1baeb2128a59b70defb78d483a6ba669fd294c08)
 - [7bd8e06a19e72f6f106ad0dc7135384d524087f1](https://github.com/magento/magento2/commit/7bd8e06a19e72f6f106ad0dc7135384d524087f1)
 - [afaede9ee5eaa54714f869baf348f6aca5ddb076](https://github.com/magento/magento2/commit/afaede9ee5eaa54714f869baf348f6aca5ddb076)
 - [986d5b19fc7edd126210fe5b4b6c6eab7532462a](https://github.com/magento/magento2/commit/986d5b19fc7edd126210fe5b4b6c6eab7532462a)
 - [6925546abeab5e75b0f9bf997db7f5062775e230](https://github.com/magento/magento2/commit/6925546abeab5e75b0f9bf997db7f5062775e230)
 - [d723f24aac761d6a88fb177b1013c1c9f49da7fe](https://github.com/magento/magento2/commit/d723f24aac761d6a88fb177b1013c1c9f49da7fe)
 - [065c78027a30f1ae4e65d6927c5535c4398e60cd](https://github.com/magento/magento2/commit/065c78027a30f1ae4e65d6927c5535c4398e60cd)
 - [d47baa8c9cb5be44fbd145b902d8456bde35c83b](https://github.com/magento/magento2/commit/d47baa8c9cb5be44fbd145b902d8456bde35c83b)
 - [a37e651ab51005f9fa4e3f1ad4fa222710494533](https://github.com/magento/magento2/commit/a37e651ab51005f9fa4e3f1ad4fa222710494533)
 - [fd8e270122df128ff7f2e46840bca31a91e7651e](https://github.com/magento/magento2/commit/fd8e270122df128ff7f2e46840bca31a91e7651e)
 - [af7ece4d0ce3fa0c7ca13b09a8e108aaf7634313](https://github.com/magento/magento2/commit/af7ece4d0ce3fa0c7ca13b09a8e108aaf7634313)
 - [47d7be26f44dcb4daa1283c8c563c281dc95d7f2](https://github.com/magento/magento2/commit/47d7be26f44dcb4daa1283c8c563c281dc95d7f2)
 - [3c9406da38d53cb0c1430aed258b0a3d29af2c79](https://github.com/magento/magento2/commit/3c9406da38d53cb0c1430aed258b0a3d29af2c79)
 - [e4d71d1b5696d0f9a3d3afea2bb4ee784a016cff](https://github.com/magento/magento2/commit/e4d71d1b5696d0f9a3d3afea2bb4ee784a016cff)
 - [05e9e4e584f055243f1f5aa1354ce7ddf21e9f4b](https://github.com/magento/magento2/commit/05e9e4e584f055243f1f5aa1354ce7ddf21e9f4b)
 - [db47d6c9ed867c9a5ec6ba705479a622346cc1f7](https://github.com/magento/magento2/commit/db47d6c9ed867c9a5ec6ba705479a622346cc1f7)

The fix will be available with the upcoming 2.4.1 release.
