### ISSUE TITLE
B2B shared catalog feature set

### ISSUE THREAD

**Issue by nrkapoor** [magento/magento2#28550]
As a Magento Developer,

I want to expose B2B shared catalog functionality via GraphQL

So that customers can use a more flexible and performant API technology.

### Connected tickets

- [GraphQL "categories" and "categoryList" do not consider Category Permissions configuration ](https://github.com/magento/magento2/issues/29880)
- [Prices should be hidden from products query results when the category permissions chooses to hide them](https://github.com/magento/magento2/issues/29926)
- [Search should be disabled from products query when general configuration chooses to disabled it](https://github.com/magento/magento2/issues/29927)
- ["Add to Cart" mutations in GraphQl should consider Catalog Permissions](https://github.com/magento/magento2/issues/29930)

**Acceptance Criteria**

GraphQL respects user permissions for all storefront operations.
WebAPI test coverage and indirectly covered by its sub-tickets
- Sub tickets should provide WebApi coverage on EE level - coming from the CatalogPermissions feature
- Specifically this ticket should provide such WebApi coverage that by fixture(s) creates a shared catalog - this would just verify the shared catalog as a concept that is build on top of the catalog permisssions
All builds are green

### Related Pull Requests
1. Api functional tests on Shared catalog PR is:
https://github.com/magento/partners-magento2b2b/pull/335
and is continuation from PR
https://github.com/magento/partners-magento2b2b/pull/96
2.  For [GraphQL "categories" and "categoryList" do not consider Category Permissions configuration ]  (https://github.com/magento/magento2/issues/29880) PRs are
https://github.com/magento/magento2/pull/29883
https://github.com/magento/partners-magento2ee/pull/319
3. For  [Prices should be hidden from products query results when the category permissions chooses to hide them](https://github.com/magento/magento2/issues/29926) PR is
https://github.com/magento/magento2/pull/29998
4. For [Search should be disabled from products query when general configuration chooses to disabled it](https://github.com/magento/magento2/issues/29927) PRs are
https://github.com/magento/magento2/pull/30118
https://github.com/magento/partners-magento2ee/pull/337
5. For ["Add to Cart" mutations in GraphQl should consider Catalog Permissions](https://github.com/magento/magento2/issues/29930) PRs are
https://github.com/magento/magento2/pull/30019
https://github.com/magento/partners-magento2ee/pull/328

Other relater PRs are
1. Extract getting customer group id from context into its own class
https://github.com/magento/partners-magento2ee/pull/326

2. Increase accuracy in the context isCustomer method
https://github.com/magento/magento2/pull/29894

**Comment by pmarjan** [comment]
Hello @nrkapoor, @cpartica  

upon closer inspection of the related PRs to this ticket, I noticed that there is NO new schema that is specific to the shared catalog.

For example the schema.graphqls that has been added to the CatalogPermissionsGraphQl module does only extend two queries

- categoryList
- categories

and they are both specific to the catalog.

Thus no wonder, most of the coding relates to Catalog Permissions and can be found here: 
https://github.com/magento/partners-magento2ee/pull/302

I will further say that the title of this PR is inaccurate: catalog permissions are a thing on its own - and NOT only for the shared catalog.

So, can you please confirm: we do not have shared catalog specific graphql schema?

If so, probably it will be more clear separation of concerns to have specified tickets like:  

a. GraphQL "categoryList" query does not consider Category Permissions configuration
b. GraphQL "categories" query does not consider Category Permissions configuration

Because, I think this is exactly what is missing and the PR tries to solve.

Also it will be consistent with an earlier work on the same topic
GraphQL product search does not consider Category Permissions configuration
https://github.com/magento/magento2/issues/28563

**Comment by nrkapoor** [comment]
> Hello @nrkapoor, @cpartica
> 
> upon closer inspection of the related PRs to this ticket, I noticed that there is NO new schema that is specific to the shared catalog.
> 
> For example the schema.graphqls that has been added to the CatalogPermissionsGraphQl module does only extend two queries
> 
> * categoryList
> * categories
> 
> and they are both specific to the catalog.
> 
> Thus no wonder, most of the coding relates to Catalog Permissions and can be found here:
> [magento/partners-magento2ee#302](https://github.com/magento/partners-magento2ee/pull/302)
> 
> In attempt to put focus on differences and scope, I will further say that the title of this PR is inaccurate: catalog permissions are a thing on its own - and NOT only for the shared catalog.
> 
> So, can you please confirm: we do not have shared catalog specific graphql schema?
> 
> If so, probably it will be more clear separation of concerns to have specified tickets like:
> 
> a. GraphQL "categoryList" query does not consider Category Permissions configuration
> b. GraphQL "categories" query does not consider Category Permissions configuration
> 
> Because, I think this is exactly what is missing and the PR tries to solve.
> 
> Also it will be consistent continuation of an earlier work on the same topic:
> 
> GraphQL product search does not consider Category Permissions configuration
> #28563

@pmarjan it has to also support products query.

**Comment by pmarjan** [comment]
@nrkapoor 

products query - done! :)

https://github.com/magento/magento2/issues/28563
