### ISSUE TITLE
Enabled Translation inline affect to result of REST APIs.

### ISSUE THREAD

**Issue by phongphanmage** [magento/magento2#28656]
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Go to admin
2. Stores > Settings > Configuration
3. In the left panel, expand Advanced and choose Developer
4. Expand selector the Translate Inline section
5. Set Enabled for Storefront to Yes
6. Click on save config
7. Try to login to admin as a user using API-
POST -  {Baseurl}/rest/V1/integration/admin/token
Body-{
"username": "",
"password": ""
}

### Expected result (*)

1. Translation inline should be effected to frontend side only.
2. Message from REST API should work well while translation inline is enabled.

### Actual result (*)

1.  Result from rest API:
`{
    "message": "<span data-translate=\"[&#x7B;&quot;shown&quot;&#x3A;&quot;Invalid&#x20;login&#x20;or&#x20;password.&quot;,&quot;translated&quot;&#x3A;&quot;Invalid&#x20;login&#x20;or&#x20;password.&quot;,&quot;original&quot;&#x3A;&quot;Invalid&#x20;login&#x20;or&#x20;password.&quot;,&quot;location&quot;&#x3A;&quot;Text&quot;,&quot;scope&quot;&#x3A;&quot;Invalid&#x20;login&#x20;or&#x20;password.&#x7D;&#x7D;&#x7B;&#x7B;theme&quot;&#x7D;]\">Invalid login or password.</span>"
}`

### Additional information
- more detailed steps to reproduce with screens https://github.com/magento/magento2/issues/28656#issuecomment-644551601

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swathishs, here is your [Magento instance](https://i-28656-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28656-2-4-develop.instances.magento-community.engineering/admin_eebe](https://i-28656-2-4-develop.instances.magento-community.engineering/admin_eebe)
Login: `8ec2452d` Password: `3491f0e425f7`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment]
@phongphanmage : Issue is reproducible in Magento 2.4 develop instance
Please find the attachment below:

1. **Admin:**
![inline](https://user-images.githubusercontent.com/58288685/84737440-92879a80-afc5-11ea-932b-f85fce0d40fd.png)

2. **Frontend:**
![inline2](https://user-images.githubusercontent.com/58288685/84737502-adf2a580-afc5-11ea-8fba-a3b30297d360.png)

3. API response:
![inline3](https://user-images.githubusercontent.com/58288685/84737527-b8ad3a80-afc5-11ea-92bf-f0f74e70ac78.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35193` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
:x: Something went wrong. Cannot update Jira issue (https://jira.corp.magento.com/browse/MC-35193).

**Comment by magento-engcom-team** [comment]
Hi @phongphanmage. Thank you for your report. 
The issue has been fixed in magento/magento2#28856 by @zaximus84 in 2.4-develop branch
Related commit(s):
 - [c1eeed2407b425cae955d3c06ab1efaf07a8e12b](https://github.com/magento/magento2/commit/c1eeed2407b425cae955d3c06ab1efaf07a8e12b)
 - [35f7e8d29a8f570c0eb02b80116618f9d09d5de1](https://github.com/magento/magento2/commit/35f7e8d29a8f570c0eb02b80116618f9d09d5de1)
 - [b444002620bc37a75ac4a521f84b76109b194dc0](https://github.com/magento/magento2/commit/b444002620bc37a75ac4a521f84b76109b194dc0)
 - [6fc459529ac0ed544a4e31818f35d49f8d2b2165](https://github.com/magento/magento2/commit/6fc459529ac0ed544a4e31818f35d49f8d2b2165)
 - [e3726fc663edafdbf96941a8f8ae7255334c86b2](https://github.com/magento/magento2/commit/e3726fc663edafdbf96941a8f8ae7255334c86b2)
 - [9fc982c6d24e047da11e54a18062df5c446ab08f](https://github.com/magento/magento2/commit/9fc982c6d24e047da11e54a18062df5c446ab08f)
 - [285635bfd5d213c2d7890ee29cca4799136a44d0](https://github.com/magento/magento2/commit/285635bfd5d213c2d7890ee29cca4799136a44d0)
 - [a925a0377651cbc73edf83665f4b5cd80ba16737](https://github.com/magento/magento2/commit/a925a0377651cbc73edf83665f4b5cd80ba16737)
 - [9204022c7c003183a75eceddb333eee93a4febbb](https://github.com/magento/magento2/commit/9204022c7c003183a75eceddb333eee93a4febbb)

The fix will be available with the upcoming 2.4.1 release.
