### ISSUE TITLE
IPv6 values of X_FORWARDED_FOR in sales orders are truncated to 32 characters.

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#28693]
### Preconditions (*)

1. Magento 2.4-develop
2. When customer is using IPV6 address, the x_forwarded_for IP might get saved only partially into sales_order and quote tables depending on the address str length.  Problem appears to be in the x_forwarded_for column length which currently is VARCHAR(32)
3. This seems to be a version of the error descripted in #10395 for REMOTE_IP
4. Known to exist in our version 2.3.5-p1 but I suspect it probably pre-exists all the way back to at least 2.1.x

### Steps to reproduce (*)

1.Customer creates order from an IPv6 address that is longer than 32 characters when 
IPv6 addresses can be up to 45 characters.

### Expected result (*)

1. Veiw order for Placed from IP	2600:1700:ec11:1a40:f829:8829:139c:d85f (2600:1700:ec11:1a40:f829:8829:139c:d85f)
2.

### Actual result (*)

1. Placed from IP	2600:1700:ec11:1a40:f829:8829:139c:d85f (2600:1700:ec11:1a40:f829:8829:13)
2. Note the truncated value in () is 32 characters long.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ S1] Severity: **S1** _- A recently installed fraud detection tool used for analyzing the order is detecting that the actual IP and the forwarded IP don't match, and further their API is throwing an error because the forwarded IPv6 value is malformed and thus invalid.  Since nearly a third of the traffic coming to our website is IPv6, this issue is hindering our ability to detect fraudulent orders.

**Comment by ihor-sviziev** [comment]
Should be fixed by https://github.com/magento/magento2/pull/27221

**Comment by n2diving-dgx** [comment]
#27221 fixes 2.4, but we are going to be on 2.3.x for a while, could we get a backport?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35787` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @n2diving-dgx. Thank you for your report. 
The issue has been fixed in magento/magento2#27221 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [8ec11ad2e5797eeeafce815d2fbbbd422277d9b1](https://github.com/magento/magento2/commit/8ec11ad2e5797eeeafce815d2fbbbd422277d9b1)
 - [7308ee2a7246d4ae11c140819a30b6bb8db06db0](https://github.com/magento/magento2/commit/7308ee2a7246d4ae11c140819a30b6bb8db06db0)
 - [4514e0cc201ac790303142859218d658d2fdd7fc](https://github.com/magento/magento2/commit/4514e0cc201ac790303142859218d658d2fdd7fc)
 - [aa59e482127642e83b1904e4dff5a29072710a58](https://github.com/magento/magento2/commit/aa59e482127642e83b1904e4dff5a29072710a58)

The fix will be available with the upcoming 2.4.1 release.
