### ISSUE TITLE
Duplicate a product then duplicate it again SKU is TST.PROD.2.SIMPLE-1-1 instead of TST.PROD.2.SIMPLE-2

### ISSUE THREAD

**Issue by seansan** [magento/magento2#28827]
### Preconditions (*)
1. Magento 2.3.5

### Steps to reproduce (*)
1. Create product with SKU 123
2. Duplicate it to 123-1 (dash 1 gets added)
3. Duplicate 123-1 again 

### Expected result (*)
1. 3rd created product has SKU 123-2

### Actual result (*)
1. 3rd created product has SKU 123-1-1

[ X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @seansan thank you for your report.Currently this is expected behavior
Feel free to provide your point of view why sku duplicated as `123-2` will be better than `123-1-1`

Please created issue in [community-features](https://github.com/magento/community-features/issues) repo for further discussion
Or if you'd like to update the issue, please reopen it.

**Comment by seansan** [comment]
is it expected?

I thought -increment was described

not -1-1-1-1
