### ISSUE TITLE
Scope not reset on New Synonym Group form

### ISSUE THREAD

**Issue by renard123** [magento/magento2#28947]
Scope not reset on New Synonym Group form

### Preconditions (*)
Magento 2.3.4

### Steps to reproduce (*)

1. Admin - Marketing - SEO & Search 
2. Click on New Synonym Group
3. Select scope different then default 
4. Enter other details 
5. Click on Reset 

### Expected result (*)
All values should be reset 

### Actual result (*)
![image](https://user-images.githubusercontent.com/50658701/86222577-12a42780-bba4-11ea-83b1-2e0badb15081.png)

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-28947-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28947-2-4-develop.instances.magento-community.engineering/admin_5c89](https://i-28947-2-4-develop.instances.magento-community.engineering/admin_5c89)
Login: `6a754886` Password: `dd7ec2158718`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35578` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bartlomiejsz** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @renard123. Thank you for your report. 
The issue has been fixed in magento/magento2#29206 by @srsathish92 in 2.4-develop branch
Related commit(s):
 - [87d109465d6ce8437286313f0a41a9e6d7843985](https://github.com/magento/magento2/commit/87d109465d6ce8437286313f0a41a9e6d7843985)
 - [39aff394256735c448dbee13d6da9849190f4110](https://github.com/magento/magento2/commit/39aff394256735c448dbee13d6da9849190f4110)
 - [4ff81d3fe6029497dd2c2e10783f9327c16f15f3](https://github.com/magento/magento2/commit/4ff81d3fe6029497dd2c2e10783f9327c16f15f3)
 - [535f219a19773016f9a710a80c598c95aab2ab58](https://github.com/magento/magento2/commit/535f219a19773016f9a710a80c598c95aab2ab58)
 - [f1509b111b965719c5e3e2fe44a88aabd39ba2ac](https://github.com/magento/magento2/commit/f1509b111b965719c5e3e2fe44a88aabd39ba2ac)

The fix will be available with the upcoming 2.4.1 release.
