### ISSUE TITLE
Billingaddress gets renewed on every set-payment-information call. Thus Vat Validation on Billing address gets called multiple times

### ISSUE THREAD

**Issue by stkrelax** [magento/magento2#28946]
### Summary (*)

- After Upgrade from 2.3.3 now using magento 2.3.5-p1
- Vat Validation based on billing
- viv valiate on each transaction off
- OnestepCheckout

I came accross this when i was searching why our VatValidation Service is blocking calls from our side.
i figured out that there is an explicit deleting of quote billing addresses at

https://github.com/magento/magento2/blob/ba25897c151b4f33505a8fe91aa1942bb6e71330/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L124

this method is called up to 4 times in our checkout (classic OneStepCheckout plus iways/magento2-paypal-plus module)
the Reasons therefor are
 - scriptLoaded
 - Agreements posted
 - PayPalPlusIframe initialized
 - PaymentMethod selected

Note that there was no change in billingAddress, but the billingaddress is still posted due to the ```false``` in

https://github.com/magento/magento2/blob/ba25897c151b4f33505a8fe91aa1942bb6e71330/app/code/Magento/Checkout/view/frontend/web/js/action/set-payment-information.js#L17

this ```false``` tells the script to **not** skip billing. Thus billing data is provided and in management a new billing address is created and the old one deleted.

All together almost okay, despite the fact that i sometimes had 2 billingaddresses and 1 shippingaddress set to my quote at one time...
This does not seem to affect checkout or order place in any kind, so it is working. 

But it affects the Vat Validation. 

You may know a certain amount of calls/same calls lead to a block (around 1 minute) on the VIES or the german https://evatr.bff-online.de/eVatR/xmlrpc/ which actually uses the same endpoints.

There were some tickets that tried to prevent this behaviour. One good approach was that not everytime there must be a validation when nothing has changed. In this Feature the request data for validation ist stored in the quote address. A check is only made, when a change in the request data appears. 

### Examples (*)

And there is the problem: 

Having set Vat Validation based on billing address and having a billingaddress that renews itself on every call causes multiple Validation call to VIES. Sometimes to much so that VIES or other will block your ip for a while.

### Proposed solution

1. Instead of deleting the billing_address you could clean(of course not the viv requested data) the data and add the new data to the quote address.  

OR

2. Store the validation result in the quote and not in the address or in a completely seperate space.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by johnyoy** [comment]
having same issue in my site[VAT CALCULATOR](https://techcal.net/)

**Comment by engcom-Hotel** [comment]
Hello @stkrelax,

Please confirm if you are still able to reproduce this issue in the latest stable version or in the latest development branch.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @stkrelax,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks

**Comment by lucafuser** [comment]
Hi @engcom-Hotel 
the issue is this riproducible in the latest 2.4-develop branch.

There are 2 different scenarios.
1. Billing address gets renewed on every billing address change
2. Billing address gets renewed on every set payment information call


## Scenario 1

Step to reproduce:
1. Add a product to cart
2. Go to checkout (guest)
3. Add shipping address, select shipping method and go next
  Now shipping address and billing are the same, in the  quote_address table there are 2 rows for the quote, for example billing with address_id  and shipping with address_id 11.
4. Uncheck "My billing and shipping address are the same" and click "Edit" billing address
5. Change billing address and save
  Billing address with address_id 10 is removed,  new row for billing is created with address_id 12.  
  
Every time the billing address is changed, a new row is insert into quote_address table, and the previous is removed.

## Scenario 2

Step to reproduce:
1. Add a product to cart
2. Go to checkout (guest)
3. Add shipping address, select shipping method and go next
  Now shipping address and billing are the same, in the  quote_address table there are 2 rows for the quote, for example billing with address_id  and shipping with address_id 11.
4. Select payment method and place order.
  Billing address with address_id 10 is removed,  new row for billing is created with address_id 12.  
  
When placing order, a new row for billing is insert into quote_address table, and the previous is removed.
