### ISSUE TITLE
Magento 2.3.4 - 404 error When click ''add to cart" from shared wishlist

### ISSUE THREAD

**Issue by Vanitha-bujjinga** [magento/magento2#28986]
Magento Version - 2.3.4

### Steps to reproduce (*)

1. Login to a customer account and Add a product to wishlist.
2. Go to "wishlist" and click "Share wishlist".
3. Enter email id, message and send.
4. Logout from customer account.
5. Open a shared wishlist email, Click on "View Product" from email.
6. It landed on the shared wishlist products, Click the "Add to Cart" button from any product.

### Expected result (*)
1. It should add a product to the cart and redirect it to the cart page.

### Actual result (*)
1. It didn't add a product to the cart and it shows "404 error". 
URL: http://{host-name}/wishlist/shared/cart
![wishlist_addtocart](https://user-images.githubusercontent.com/31979511/86485495-7716e080-bd76-11ea-9e56-5597d6a3017a.jpg)

I have executed this in plain vanilla Magento 2.3.4.

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by Vanitha-bujjinga** [comment]
Any updates on this ticket?

**Comment by sabamanz00r** [comment]
Hi @Vanitha-bujjinga the issue is due to the interface HttpGetActionInterface  implemented by vendor/magento/module-wishlist/Controller/Shared/Cart.php class.

class Cart extends \Magento\Framework\App\Action\Action implements HttpGetActionInterface
{
}

getSharedAddToCartUrl function in vendor/magento/module-wishlist/Helper/Data.php returns parameters with post but our Cart class is implementing HttpGetActionInterface interface. 

    public function getSharedAddToCartUrl($item)
    {
        return $this->_postDataHelper->getPostData(
            $this->_getUrlStore($item)->getUrl('wishlist/shared/cart'),
            $this->_getCartUrlParameters($item)
        );
    }


Solution : Remove HttpGetActionInterface interface or replace HttpGetActionInterface with HttpPostActionInterface  in vendor/magento/module-wishlist/Controller/Shared/Cart.php class.

Change in core file is discourage. Add preference instead of changing core file.

**Comment by engcom-Delta** [comment]
Hi @Vanitha-bujjinga  thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Result:**
![Peek 2020-08-14 09-29](https://user-images.githubusercontent.com/51681379/90220456-ea4d5100-de10-11ea-9ed6-db5b689d6055.gif)


If you'd like to update the issue, please reopen it.

**Comment by Coosos** [comment]
Hi,

I reproduce this problem in `2.3.x`, but is fixed with this commit (https://github.com/magento/magento2/commit/c3f9f3d733dc56624fb95e1b07f7916966b7f212) who apply in 2.4.x

**Comment by Vanitha-bujjinga** [comment]
> Hi @Vanitha-bujjinga the issue is due to the interface HttpGetActionInterface implemented by vendor/magento/module-wishlist/Controller/Shared/Cart.php class.
> 
> class Cart extends \Magento\Framework\App\Action\Action implements HttpGetActionInterface
> {
> }
> 
> getSharedAddToCartUrl function in vendor/magento/module-wishlist/Helper/Data.php returns parameters with post but our Cart class is implementing HttpGetActionInterface interface.
> 
> ```
> public function getSharedAddToCartUrl($item)
> {
>     return $this->_postDataHelper->getPostData(
>         $this->_getUrlStore($item)->getUrl('wishlist/shared/cart'),
>         $this->_getCartUrlParameters($item)
>     );
> }
> ```
> 
> Solution : Remove HttpGetActionInterface interface or replace HttpGetActionInterface with HttpPostActionInterface in vendor/magento/module-wishlist/Controller/Shared/Cart.php class.
> 
> Change in core file is discourage. Add preference instead of changing core file.

Appreciate for your help, @sabamanz00r. It is working fine. Kudos...

**Comment by akgola** [comment]
@Vanitha-bujjinga , I am also geting same issue in Magento 2.4.0 version. When applying your code in core files it is working fine.Could you lease let me know where patch is available for that issue.
Because we will require to with custom module and  require to override the class for that condition , we can't update implement class in custom module.

Could you please let me know what will be solution in that case.
