### ISSUE TITLE
Magento 2.3.5-p1 Stock import does not update stock status on frontend

### ISSUE THREAD

**Issue by nadroj467** [magento/magento2#29090]
A configurable product with all its associated simple products marked as out of stock with 0 quantity. If stock is imported with just fields 'sku & qty' to bring all associated simple products in stock. The configurable product still shows out of stock on frontend. 

### Preconditions (*)

1. Magento 2.3.5-p1
2. PHP 7.3.1
3. Varnish 6
4. Use Flat Catalog Category > No
5. Use Flat Catalog Product > Yes
--

### Steps to reproduce (*)

1. Create a configurable product with a few simple associated products showing all out of stock status with qty of 0
2. Confirm frontend configurable product is showing out of stock.
3. Import csv with fields 'Sku & and Qty' and bring all simple associated products into stock with qty of 10 each
4. Use add/update on import option

### Expected result (*)

1. Expected for configurable product to now show as in stock on front end after import

### Actual result (*)

1. The configurable product still showing as out of stock on front end after qty for all its associated products updated to 10
2. Correct qty is showing in admin for simple products but stock status still remains as 'out of stock'

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nadroj467** [comment]
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment]
Hi @nadroj467. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nadroj467, here is your [Magento instance](https://i-29090-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29090-2-3-5-p1.instances.magento-community.engineering/admin_b1ea](https://i-29090-2-3-5-p1.instances.magento-community.engineering/admin_b1ea)
Login: `e56803d5` Password: `3f5e48b423f3`
Instance will be terminated in up to 3 hours.

**Comment by nadroj467** [comment]
I am able to replicate the issue on provided Magento 2.3.5-p1 instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Lima. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Lima, here is your [Magento instance](https://i-29090-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29090-2-4-develop.instances.magento-community.engineering/admin_3852](https://i-29090-2-4-develop.instances.magento-community.engineering/admin_3852)
Login: `c02c8519` Password: `45e4c645508e`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Kilo** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Kilo. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Kilo, here is your [Magento instance](https://i-29090-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29090-2-4-develop.instances.magento-community.engineering/admin_aa99](https://i-29090-2-4-develop.instances.magento-community.engineering/admin_aa99)
Login: `e18060ef` Password: `8728620976b9`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Lima** [comment]
Hello @nadroj467 
According to the [documentation](https://docs.magento.com/user-guide/system/data-attributes-product.html):

> is_in_stock - Indicates if the product is in stock.

If stock is imported with fields `sku`, `qty` and `is_in_stock`' to bring all associated simple products in stock, this works. All associated simple products become in stock after running cron
![Screenshot_60](https://user-images.githubusercontent.com/60198022/88383964-3417be00-cdb4-11ea-9d92-4573d9657eef.png)

Here is an example imported file: [1catalog_product.zip](https://github.com/magento/magento2/files/4971498/1catalog_product.zip)

**Comment by pjean-gorillagroup** [comment]
Hi @engcom-Lima, the `is_in_stock` product attribute is optional. If we do not include it in our product import, it should automatically calculate it. Unfortunately, it doesn't do it right now because of a bug in the file https://github.com/magento/magento2/blob/b06b839934218db725140d74a4d053d423fa3ec9/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L3087

This line of code was meant to calculate it but doesn't do it reliably because of that bug. It should look like `$row['is_in_stock'] = $rowData['is_in_stock'] ?? $this->stockStateProvider->verifyStock($stockItemDo);` instead of what we currently have.

**Comment by michaellehmkuhl** [comment]
Following up on the bug @pjean-gorillagroup reported above, we've seen the same bug affect our imports in Open Source 2.3.6. In our case, though, the desired behavior was for `is_in_stock` to be set to 1 and `qty` to be set to 0. However, the current logic forces `is_in_stock` to be set to 0 if `qty` is set to 0, even if the import file contains `is_in_stock` with a value of 1.

**Comment by gmonseur** [comment]
Hi

I have the same problem in Open Source 2.4.3-p1. I would add that the problem is not solved by adding the column "is_in_stock" in csv file. The column seems to be simply ignored.

I think you need to change the following condition:

https://github.com/magento/magento2/blob/8afdb9858d238392ecb5dbfe556068ec1af137bc/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L3191

By this
`if (isset($rowData['qty']) && $rowData['qty'] == 0 && !isset($rowData['is_in_stock'])) {`

**Comment by james-noon** [comment]
@gmonseur thanks for posting this (and attempting a fix) but unfortunately this didn't work for me. Did it fix it for you? 

I'm running into the same bug I think. I'm on v2.4.3-p1 and I have tried the following columns in my CSV file but it just keeps my configurable products "out of stock" even know I put a 1 in the column for the configurable product SKU. Ugh

source_code | sku | status | quantity
source_code | sku | is_in_stock | quantity

Neither worked. It updates my simple products correctly, but the configurable ones just stay "out of stock". 

For anyone else that ends up in this mess after importing, here is a semi-quick way to recover.:

Go to: phpmyadmin > Magento DB > cataloginventory_stock_item > Find the product IDs to your configurable products and under column > is_in_stock > change to 1 (I got semi-lucky because all my configurable products had a "NULL" entry for the "low_stock_date" so I just entered 'null' into the filter row and it filtered only my configurable products - this helped saved time as well)

You'll have to reindex manually to get it to reupdate. But this does work and is a bit quicker than going through each product 1-by-1 and selecting "In Stock". But still a major pain :(

Damn magento....

**Comment by Beraa995** [comment]
Hi,

You can do the import like you did, but after that, as a workaround, you need to do a second import containing only "is_in_stock" column without "qty" column. With this approach you can achieve to have 0 quantity and in stock status.
