### ISSUE TITLE
Can't open admin panel (Class Magento\User\Model\Resource\User does not exist)

### ISSUE THREAD

**Issue by ragum** [magento/magento2#2911]
After I install magento 2, the admin panel can't be open, but in frontend store working 
"There has been an error processing your request

Exception printing is disabled by default for security reasons.

Error log record number: 846107250"

anyone can help? (please help me and sorry for the bad english)
here the 846107250 file
[846107250.txt](https://github.com/magento/magento2/files/80783/846107250.txt)

**Comment by GianniPDF** [comment]
I have a similar issue but with class Magento\Authorization\Model\RoleFactory, i posted it in stackexchange, http://magento.stackexchange.com/questions/96024/magento-2-admin-url-gives-error-class-magento-authorization-model-rolefactory/96075#96075 but error persist

**Comment by ragum** [comment]
in my case, it just happen when I clone from 2.0 branch, if I clone from develop, it working correctly

**Comment by adampmoss** [comment]
I have the exact same problem.

**Class Magento\User\Model\Resource\User does not exist** followed by a stack trace.

**Comment by chapagain** [comment]
I was having the issue as mentioned by @GianniPDF 

In my case, it was the issue with `var/generation` directory. Magento 2 creates Factory classes and stores in this directory. 

I cleared `var/generation` directory and set it's ownership as that of `var/cache` and `var/page_cache` directory. And, now the issue is solved. I am able to login to admin again.

**Comment by mazhalai** [comment]
@adampmoss @GianniPDF  @ragum did @chapagain's suggestion help?

**Comment by ragum** [comment]
its fine now, after update magento 2.0.2
and edit .htaccess on root folder unstag SetEnv MAGE_MODE developer
