### ISSUE TITLE
Show custom maintenance site instead of exception

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#29150]
### Description (*)

Enterprise 2.3.5-p1

If I change my store to maintenance mode, then this message is showing:

```
1 exception(s):
Exception #0 (Exception): Unable to proceed: the maintenance mode is enabled. 

Exception #0 (Exception): Unable to proceed: the maintenance mode is enabled. 
<pre>#1 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000001f0deaee00000000184ccfc2#) called at [pub/index.php:45]
</pre>
```

### Expected behavior (*)

Show custom Site instead which I can configure in the backend.

### Benefits

1. You won't expose to anyone that you are using magento = more security.

2. Adding a custom maintenance site will make your site look more professional.

### Additional information

This should be a must have for every online shop. You can't show such a exception to customers, this is extremly unprofessional.

**Comment by Serializator** [comment]
I definitely agree with _"Adding a custom maintenance site will make your site look more professional."_. At the moment this could be done through NGINX / Apache which would divert the request to a separate folder (possibly containing a simple HTML document) on a 5xx response, rather than the public folder in which Magento is located.

If this were to be implemented in Magento I'd expect it to be a "simple" layout handle which is used when the webshop is in maintenance mode. 

_"You won't expose to anyone that you are using magento = more security."_ is negligible because you could easily determine whether a webshop is using Magento by looking at the source (`view-source:`) and search for some kind of `data-mage-init`. In case (out of the scope, but still) of a headless solution you could still determine whether it's using Magento or not based on the GraphQL / REST API requests.

**Comment by Eddcapone** [comment]
I figured out how to create a custom maintenance site. You just have to add your maintenance site code to the file `pub/errors/default/503.phtml`. Sadly this is nowhere described in the documentation... You can also use php and include sites to make it more organized.

**Comment by sivaschenko** [comment]
@Eddcapone thanks for reaching out! Please see the following documentation on setting up the custom maintenance page: https://devdocs.magento.com/guides/v2.4/comp-mgr/trouble/cman/maint-mode.html

**Comment by Eddcapone** [comment]
> @Eddcapone thanks for reaching out! Please see the following documentation on setting up the custom maintenance page: https://devdocs.magento.com/guides/v2.4/comp-mgr/trouble/cman/maint-mode.html

This is much more complicated then it should be. IMO you should be able to have the choise to create a CMS site in the admin area which is then loaded instead of the custom code.
