### ISSUE TITLE
Category API should support save_rewrites_history for consistency reasons

### ISSUE THREAD

**Issue by amenk** [magento/magento2#29174]
# Description

When updating category URL keys via REST API there is no possibility to automatically create 301 redirects for the old URL key to the new one.

For products this is possible

### Expected behavior (*)

contents of category-rename.json

     {"category":{"name":"new name","is_active":1,"parentId":2366,"custom_attributes":[{"attribute_code":"url_key","value":"new name"},{"attribute_code":"save_rewrites_history","value":1}]}}

When making a API call like

     curl -k -X PUT $BASEURL/rest/V1/categories/1295  -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @category-rename.json

I expect that a new entry is created a the end of `url_rewrite` database table with the old url_key redirecting to the new category.
Instead, after the API call, I cannot find the URL key anywhere in the `url_rewrite` table.

### Benefits

There are shops which are managed by PIM systems via API. Here it is important for SEO reasons, to allow renaming the URL key without loosing old links.

### Additional information 

There was already a pull request implementing something similar, but without the option to *not* create rewrites.
https://github.com/magento/magento2/pull/18408

The `save_rewrites_history` *is* supported for products. So for consistency this should also be possible for categories.

Maybe I can be implemented similarly to `\Magento\CatalogUrlRewrite\Plugin\Webapi\Controller\Rest\InputParamsResolver::afterResolve`

**Comment by amenk** [comment]
This is WIP.
Problem is that it doesn't work the same as with products as the flag we set gets lost in

\Magento\Catalog\Model\CategoryRepository::save

**Comment by amenk** [comment]
I found a workaround but I am not happy about it https://github.com/iMi-digital/magento2/commit/00176f5a3a0c6671556ff28b66f437ffb1970060

Does anybody have a better idea?

**Comment by engcom-Bravo** [comment]
@magento create issue

**Comment by magento-engcom-team** [comment]
Hi @amenk. Thank you for your report. 
The issue has been fixed in magento/magento2#29205 by @amenk in 2.4-develop branch
Related commit(s):
 - [5307bad69e56266eedf6fe80cd9d6da4c7ec0344](https://github.com/magento/magento2/commit/5307bad69e56266eedf6fe80cd9d6da4c7ec0344)
 - [00176f5a3a0c6671556ff28b66f437ffb1970060](https://github.com/magento/magento2/commit/00176f5a3a0c6671556ff28b66f437ffb1970060)
 - [4c99f0d4dc714de6fc49e2b7d2b5f9a28a243ec1](https://github.com/magento/magento2/commit/4c99f0d4dc714de6fc49e2b7d2b5f9a28a243ec1)
 - [f0ba72a4ba585e0f53f7d4bbb9de35f1a2ed49e1](https://github.com/magento/magento2/commit/f0ba72a4ba585e0f53f7d4bbb9de35f1a2ed49e1)
 - [0f983b209a5df48040dd9aa744847b19ce091bd2](https://github.com/magento/magento2/commit/0f983b209a5df48040dd9aa744847b19ce091bd2)
 - [7f380b6bf878d7c3257ef9e92ff982851943418a](https://github.com/magento/magento2/commit/7f380b6bf878d7c3257ef9e92ff982851943418a)
 - [3361e72bd8c8cbed271ad7547c3e48dc1d334fb3](https://github.com/magento/magento2/commit/3361e72bd8c8cbed271ad7547c3e48dc1d334fb3)
 - [79c54aecb267aa5ce9dea5e6bb4e96e0dcc7f803](https://github.com/magento/magento2/commit/79c54aecb267aa5ce9dea5e6bb4e96e0dcc7f803)
 - [99da072f8cef3250be8c54f236306d6fbc51ae0f](https://github.com/magento/magento2/commit/99da072f8cef3250be8c54f236306d6fbc51ae0f)
 - [f61a27af1429effd65f3706663223e1e295d707c](https://github.com/magento/magento2/commit/f61a27af1429effd65f3706663223e1e295d707c)
 - [25111f0dcd1ecf050112647930accd057b2d901a](https://github.com/magento/magento2/commit/25111f0dcd1ecf050112647930accd057b2d901a)
 - [c7822ff08cd1e9ae844f5133f590e3eb677c8feb](https://github.com/magento/magento2/commit/c7822ff08cd1e9ae844f5133f590e3eb677c8feb)
 - [df69e820fac74bf257b7c6ce133ec402747a27ee](https://github.com/magento/magento2/commit/df69e820fac74bf257b7c6ce133ec402747a27ee)
 - [6fde4babdb7be4b72a8c1401232582d24efce545](https://github.com/magento/magento2/commit/6fde4babdb7be4b72a8c1401232582d24efce545)
 - [9f81b49ed1cc3ccf4c9abd437657bcfdacc5a8ab](https://github.com/magento/magento2/commit/9f81b49ed1cc3ccf4c9abd437657bcfdacc5a8ab)
 - [9583212943f2208922482e4f075b56727d905f23](https://github.com/magento/magento2/commit/9583212943f2208922482e4f075b56727d905f23)
 - [1ad44825f3ae89a97f9ca4957b519bf41e7b8f5b](https://github.com/magento/magento2/commit/1ad44825f3ae89a97f9ca4957b519bf41e7b8f5b)

The fix will be available with the upcoming 2.4.2 release.
