### ISSUE TITLE
\Magento\Framework\Filter\Template\Tokenizer\Parameter

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#29185]
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Create Custom Directive as described in [devdocs](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email-migration.html#create-a-custom-directive);
2. Add created before directive to any CMS page ( `{{lifetime should_bold="1"}}` in my case);
3. Open cms page with the custom directive;

**Actual Result:** :heavy_multiplication_x: $parameters of method "process($value, array $parameters, ?string $html): string" have a parameter "hould_bold"

![2020-09-16_13-22](https://user-images.githubusercontent.com/51679138/93326802-113cdf80-f822-11ea-942f-0e48ab5fbc15.png)

:heavy_multiplication_x: and the parameter was not applied

![2020-09-16_13-25](https://user-images.githubusercontent.com/51679138/93326886-3598bc00-f822-11ea-9ef6-8efc4aa438c2.png)

**Expected Result:** :heavy_check_mark: $parameters of method "process($value, array $parameters, ?string $html): string" should have a parameter "should_bold"

![2020-09-16_13-29](https://user-images.githubusercontent.com/51679138/93326953-519c5d80-f822-11ea-8d8e-1e3fbd7e0044.png)

:heavy_check_mark: and the parameter must be applied

![2020-09-16_13-30](https://user-images.githubusercontent.com/51679138/93326994-5f51e300-f822-11ea-9389-8c4ff08ea036.png)

### Sollution
\Magento\Framework\Filter\Template\Tokenizer\Parameter has to use a do-while-loop. not a while loop. Else the first char is ignored because $this->next() set the pointer to the second char before getting the first char.

See: \Magento\Framework\Filter\Template\Tokenizer\Variable. There is used a do-while-loop.

Best regards
Bernd

**Comment by marvinhinz** [comment]
I just encountered the same problem. The do-while fixes it.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37691` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @bernd-reindl. Thank you for your report. 
The issue has been fixed in magento/magento2#29542 by @marvinhinz in 2.4-develop branch
Related commit(s):
 - [4328a2d67191648c352b156f3a0aecc56870d1ad](https://github.com/magento/magento2/commit/4328a2d67191648c352b156f3a0aecc56870d1ad)
 - [55a15434c4208a631aef8d6a9f474987ed8a901e](https://github.com/magento/magento2/commit/55a15434c4208a631aef8d6a9f474987ed8a901e)
 - [1b322f4310292ab933f1e801b3281c1964effa64](https://github.com/magento/magento2/commit/1b322f4310292ab933f1e801b3281c1964effa64)

The fix will be available with the upcoming 2.4.2 release.
