### ISSUE TITLE
Price Filter Into Grid not working for specific data

### ISSUE THREAD

**Issue by sarron93** [magento/magento2#29213]
### Preconditions (*)
1. Magento versions: 2.3.4, 2.3.5, 2.4-develop

### Steps to reproduce (*)
1. Create Grid Block with deprecated functionality extended class Magento\Backend\Block\Widget\Grid\Extended
2. add column type price `
$this->addColumn(
            'total_price',
            [
                'header' => __('Total Price'),
                'index' => 'total_price',
                'type' => 'price',
                'currency_code' => (string)$this->_scopeConfig
                    ->getValue(Currency::XML_PATH_CURRENCY_BASE),
            ]
        );
`
3. apply a filter on this field. Example: '123a'

### Expected result (*)
1. apply filter price to 123 cost

### Actual result (*)
1. Throw exception `Notice: A non well formed numeric value encountered in vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Price.php on line 197` and redirect on some page

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36739` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sarron93. Thank you for your report. 
The issue has been fixed in magento/magento2#29214 by @sarron93 in 2.4-develop branch
Related commit(s):
 - [2af87179617897d39c97dcddbfa89576cf95578d](https://github.com/magento/magento2/commit/2af87179617897d39c97dcddbfa89576cf95578d)
 - [1be7e8ceeee68ee04f595055b2280195fd613eac](https://github.com/magento/magento2/commit/1be7e8ceeee68ee04f595055b2280195fd613eac)
 - [eb2a80597f4e4df176542a658fb730fdbc4338b1](https://github.com/magento/magento2/commit/eb2a80597f4e4df176542a658fb730fdbc4338b1)

The fix will be available with the upcoming 2.4.1 release.
