### ISSUE TITLE
Same store name overriding in the store view grid filter  

### ISSUE THREAD

**Issue by jigar48** [magento/magento2#29267]
### Preconditions (*)

1. install the magento 2.3.5-p1, 2.4-develop

### Steps to reproduce (*)

1. create the new store view with same name "Default Store View"
![issue1](https://user-images.githubusercontent.com/16815711/88420290-46214d00-ce04-11ea-8a1b-eaa65b350880.png)
2. now go to sales -> order grid or catalog -> product grid and open the filter and check the listed store view, It display only one store, which is not correct.

here is the screenshot

### Expected result (*)

1. It should display all the stores which is created, but currently it display only last store which is created. Its override the option with last option.
2. I have checked the code and its using the store name as the array key which should not be correct.

### Actual result (*)

1. It is displayed only last store which is created. Its override the option with last option. 
![issue2](https://user-images.githubusercontent.com/16815711/88420295-47eb1080-ce04-11ea-8555-19167cb4db03.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

1. https://prnt.sc/to0p41
2. https://prnt.sc/to0p7z

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36266` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @jigar48. Thank you for your report. 
The issue has been fixed in magento/magento2#29474 by @engcom-Charlie in 2.4-develop branch
Related commit(s):
 - [1b39196a80c9c4a3d229c121b647b82ae242193d](https://github.com/magento/magento2/commit/1b39196a80c9c4a3d229c121b647b82ae242193d)
 - [9a980484c23a78f888708223df55f56090b970c9](https://github.com/magento/magento2/commit/9a980484c23a78f888708223df55f56090b970c9)
 - [5fbb3cf710773491c3f366af98f21637dd84179c](https://github.com/magento/magento2/commit/5fbb3cf710773491c3f366af98f21637dd84179c)
 - [55653494828cc444d846f79838c72b568aee4484](https://github.com/magento/magento2/commit/55653494828cc444d846f79838c72b568aee4484)

The fix will be available with the upcoming 2.4.2 release.
