### ISSUE TITLE
I am frustrated when I read the release notes for 2.4.0

### ISSUE THREAD

**Issue by chequille** [magento/magento2#29279]
I know, this entry is not a report of a bug but I have to write that with the hope, that many other ppeople could read it.
Maybe you remove it, but since than a few people might have seen it.

I could not believe it when reading the release notes for 2.4.0. This is definentely the end of running Magento on a hosted server. I know, this is at the end not best practice, but for smaller business the only way.

If I understood correct, 2.4.0 needs PHP 7.4 and to work as well Eleastic Search. Both of this is not on my hosted server.
As a matter of facts, I do have to stay with 2.3.5p1 and all the bugs it has.

Guys, this cannot be true.
I believe, that I am not the only one getting a lot of trouble now. How can we convince our customers, that they have to live with the bugs or to invest in new hardware, own server, not using hosted servers anymore?

This is really not a good reputation for Magento. Do you want to throw us out of the game?
I can live with less functionality of the OpenSource Version compared to Commerce, but I cannot live with bugs and with enhancing requirements.

I am excited if some offical guy will read this and will give a reply.

Best regards,
Chequille

**Comment by edenduong** [comment]
@chequille  As I can see, 2.3 still support to the end of 2021

![image](https://user-images.githubusercontent.com/8234209/88496201-9fe16d00-cfe6-11ea-9ab3-763d7456a589.png)

But I think you can consider the VPS instead of hosting. Now it is not expensive . DigitalOcean has the package only $5-$10 per month

**Comment by chequille** [comment]
@edenduong 
Thanks for your reply. At the end it makes me a little bit less frustrated.
But rgearding VPS, I cannot use a server in the US, I am located in Germany and because of all privacy restrictions which are actually mandatory, there is no change to use  a server outside the EU.
I hopfe, that the outcoming 2.3.5-p2 does contain as well bug fixes.
We will see.
Regards
Chequille

**Comment by hostep** [comment]
@chequille: there are plenty of hosting companies in Europe (and I guess Germany as well), which can provide a server with the correct software dependencies for Magento 2.4.x

However, I agree that it was a mistake to make ElasticSearch required, because suddenly your server(s) need a lot more memory and costs can go up significantly. Also not all hosting companies are very familiar with ElasticSearch and might have some trouble tuning it properly.
Which will make Magento 2.4.x less attractive for smaller merchants who try to manage their Magento shop on their own and not being supported by a dedicated team with lots of experience and technical knowledge.

Maybe it's a plan from Adobe to focus more and more on the Enterprise world for Magento, and maybe they want to get rid of their smaller customers since they don't bring in any money for them, who knows, we can only guess here ...

For PHP, in theory Magento 2.4.x should work fine on PHP 7.3 as well for now.

Regarding the support period for Magento 2.3.x, [this document](https://magento.com/sites/default/files/magento-software-lifecycle-policy.pdf) claims support for 18 more months after 2.4.0 is being released (which should happen tomorrow).

Based on previous Magento releases in the past, if you want to keep a stable shop, I'd recommend you to wait until at least version 2.4.3 is released to make the switch to 2.4.x. None of the 2.x.0 releases we've seen so far were particularly stable and 2.x.1 and 2.x.2 releases tend to still come with major changes, which came to late for the 2.x.0 release, which can cause a lot of headaches if you upgrade too soon.

Just my 2 cents 🙂

**Comment by devchris79** [comment]
I raised the ElasticSearch issue just over a year ago #22209 and just checked with our host (Siteground) and there are still no support plans.
With all the junkware that Magento has in the releases its surprising that there is an effort to remove the SQL search.

**Comment by DevBodin** [comment]
Forgive my jumping on an "off-topic" thread, but I'd like to echo the sentiment. This feels like a step toward shoving passengers overboard. 

I recently convinced a client to give Magento a try, and I've been baffled by how much it's changed, and how much denser and more abstract it's become. And in reading through documentation, releases and discussions, it certainly sounds like the landmark in the distance is "Monetization."

And after reading up on Adobe's acquisition of Magento and the fate of its Open Source... well, let's just say I'm not prepared to call them wrong just yet. Especially since downloading it required declining the Enterprise version like three times.

**Comment by Genaker** [comment]
Guys, Magento Solution/Sales engineers wrote me in the comment to this issue repost on LinkedIn:

> Always so interesting to read the stuff that comes out here. So what is small business?  I have worked with Fortune 500 who have a single business channel that only does $500K a year....am I then working with a small business?  I have also worked with people who have a zero revenue stream looking to grow it to $50M in 3 years. More that 10 million sku's. Is that a small business? 
> 
> If you guys want to go bashing Magento and want to have that opinion respected by people other than your small group of disgruntled developers.....at least try not to be so obvious that you have a bone to pick with the brand for some reason and not because you are offering serious opinions that are thoughtful and address an issue from all sides like a true commerce professional. 
> 
> I will not follow this up and go down your another of your regular stream of Magento ratholes.....I just like to pop in once and a while to offer the opinion that I still work for, and believe strongly, in Magento after 20+ years of doing commerce for customers of all sizes and business objectives around the globe. And NOT as a sales person, but as an end to end Solution Consultant who has worked  SaaS and non SaaS vendors across all levels of revenue scale and business size.

It is what Magento thinking about your business. If merchants can't afford buggy half baked Magento solution they are losers or "small group of disgruntled developers."... Interesting thought.

**Comment by chequille** [comment]
Fine, so I am thinking of whether I am a looser or a disgruntled developer !?!?!?!?!?
Will see what I decide for!

**Comment by Ctucker9233** [comment]
@devchris79 I'm in the same boat here. Do you know of any hosting services that are affordable and have the full stack of requirements that 2.4 has?

**Comment by Genaker** [comment]
I think the best hosting is AWS I can help you setup environment for free.
T3.small instance 2 vCPUs and 2GB of RAM - 15$ months with performance
better than Magento Cloud. The next solution is MageMojo they have
Kubernetes with a lot of services including ElasticSearch. Or you can
simply install Amasty or any extension which removes ElasticSearch
Requirements from the magento.

**Comment by devchris79** [comment]
@Ctucker9233 Its something I am yet to look into, although I know there is a myriad of different providers out there that should be able to do the job.
 
I would also check what the support is like, that's the reason I chose Siteground when we started is they are so fast at responding to issues. Its really annoying that they don't support Elasticsearch as its built on Java.

**Comment by iphigenie** [comment]
> However, I agree that it was a mistake to make ElasticSearch required, because suddenly your server(s) need a lot more memory and costs can go up significantly. 
> Also not all hosting companies are very familiar with ElasticSearch and might have some trouble tuning it properly.

Not just that, it's a totally different tech stack, so you have to manage java stacks and keep up with java security holes on top of the PHP ones. 

And then you have the people who already invested in an external search options, say sphinx, and now have a nightmare on their hands because the core catalog navigation needs elastic search even if you have your own search

**Comment by maksek** [comment]
Closing the issue, as it is not bug report. 
Please use forum for the discussions - https://community.magento.com/.
