### ISSUE TITLE
Can not export Coupon Code to CSV,XML

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#29277]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend, Marketing->Cart Price Rules
2. Create new rule, select auto generate coupon , generate coupon
3. In the grid, choose some coupon (must select by checkbox)
4. Click Export CSV or xml

![image](https://user-images.githubusercontent.com/8234209/88482640-ce325e80-cf8c-11ea-94a5-30fe714d6af6.png)

### Expected result (*)

1. Export Successfully

### Actual result (*)

1. 404 not found
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-29277-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29277-2-4-develop.instances.magento-community.engineering/admin_d2e0](https://i-29277-2-4-develop.instances.magento-community.engineering/admin_d2e0)
Login: `3fe940fa` Password: `8794787b9608`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36210` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#29278 by @edenduong in 2.4-develop branch
Related commit(s):
 - [ca09097a7cfa6006fa420218265826f656744685](https://github.com/magento/magento2/commit/ca09097a7cfa6006fa420218265826f656744685)
 - [c82e68f85c97423a41d28fd6b2ca540c0f31fd0c](https://github.com/magento/magento2/commit/c82e68f85c97423a41d28fd6b2ca540c0f31fd0c)
 - [e04514e48d089a4383064aa04d97b9c69d3f5c26](https://github.com/magento/magento2/commit/e04514e48d089a4383064aa04d97b9c69d3f5c26)
 - [af02e482bf45c9982990b71738a3fb693f3bfba2](https://github.com/magento/magento2/commit/af02e482bf45c9982990b71738a3fb693f3bfba2)
 - [c379cea911ab649a4a7e4fde81dabbc310f7a0c9](https://github.com/magento/magento2/commit/c379cea911ab649a4a7e4fde81dabbc310f7a0c9)

The fix will be available with the upcoming 2.4.2 release.

**Comment by gabrieldagama** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#29278 by @edenduong in 2.4-develop branch
Related commit(s):
 - [ca09097a7cfa6006fa420218265826f656744685](https://github.com/magento/magento2/commit/ca09097a7cfa6006fa420218265826f656744685)
 - [c82e68f85c97423a41d28fd6b2ca540c0f31fd0c](https://github.com/magento/magento2/commit/c82e68f85c97423a41d28fd6b2ca540c0f31fd0c)
 - [e04514e48d089a4383064aa04d97b9c69d3f5c26](https://github.com/magento/magento2/commit/e04514e48d089a4383064aa04d97b9c69d3f5c26)
 - [af02e482bf45c9982990b71738a3fb693f3bfba2](https://github.com/magento/magento2/commit/af02e482bf45c9982990b71738a3fb693f3bfba2)
 - [c379cea911ab649a4a7e4fde81dabbc310f7a0c9](https://github.com/magento/magento2/commit/c379cea911ab649a4a7e4fde81dabbc310f7a0c9)

The fix will be available with the upcoming 2.4.2 release.

**Comment by gabrieldagama** [comment]
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#29278 by @edenduong in 2.4-develop branch
Related commit(s):
 - [ca09097a7cfa6006fa420218265826f656744685](https://github.com/magento/magento2/commit/ca09097a7cfa6006fa420218265826f656744685)
 - [c82e68f85c97423a41d28fd6b2ca540c0f31fd0c](https://github.com/magento/magento2/commit/c82e68f85c97423a41d28fd6b2ca540c0f31fd0c)
 - [e04514e48d089a4383064aa04d97b9c69d3f5c26](https://github.com/magento/magento2/commit/e04514e48d089a4383064aa04d97b9c69d3f5c26)
 - [af02e482bf45c9982990b71738a3fb693f3bfba2](https://github.com/magento/magento2/commit/af02e482bf45c9982990b71738a3fb693f3bfba2)
 - [c379cea911ab649a4a7e4fde81dabbc310f7a0c9](https://github.com/magento/magento2/commit/c379cea911ab649a4a7e4fde81dabbc310f7a0c9)

The fix will be available with the upcoming 2.4.2 release.
