### ISSUE TITLE
Add back extension point for adding some html to the category page

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#29286]
### Summary (*)
In PR https://github.com/magento/magento2/pull/24728 there was done one change that caused method `getProductDetailsHtml ` and all their methods stopped to be executed at all that prevents adding customizations here.

During investigation why it was done - it was done due to issue in Swatches module, but fix was done actually in catalog.

I described it in https://github.com/magento/magento2/pull/24728#issuecomment-664219144

### Examples (*)
We need to add some HTML to the product listing page (category page), for instance some product label.

### Proposed solution
Move additional check from catalog module to the Swatches module.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by iGerchak** [comment]
@magento I am working on this issue

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36740` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#29291 by @iGerchak in 2.4-develop branch
Related commit(s):
 - [08671ba3d1a80c805742219a01d2134787ac144b](https://github.com/magento/magento2/commit/08671ba3d1a80c805742219a01d2134787ac144b)
 - [aeccbe5ec1d4c5cee1ab7ee291efd9b25253ea8a](https://github.com/magento/magento2/commit/aeccbe5ec1d4c5cee1ab7ee291efd9b25253ea8a)
 - [47cef27b7633db2abe66c155952c51b85496ab3b](https://github.com/magento/magento2/commit/47cef27b7633db2abe66c155952c51b85496ab3b)
 - [3da492ba3249880803d657d4172b95d62af70980](https://github.com/magento/magento2/commit/3da492ba3249880803d657d4172b95d62af70980)

The fix will be available with the upcoming 2.4.1 release.
