### ISSUE TITLE
Refactor Magento_Indexer module so that the "indexer_reindex_all_invalid" cronjob and "bin/magento indexer:reindex" command use the same code

### ISSUE THREAD

**Issue by hostep** [magento/magento2#29297]
### Summary (*)
This was discovered while working on https://github.com/magento/magento2/pull/29196

The cronjob `indexer_reindex_all_invalid` ([Magento\Indexer\Model\Processor::reindexAllInvalid](https://github.com/magento/magento2/blob/3008324fc7e90b01fd2b25be789aacaf950f6cde/app/code/Magento/Indexer/Model/Processor.php#L61)) and manually executing `bin/magento indexer:reindex {all-invalid-indexers}` ([Magento\Indexer\Console\Command\IndexerReindexCommand::execute](https://github.com/magento/magento2/blob/3008324fc7e90b01fd2b25be789aacaf950f6cde/app/code/Magento/Indexer/Console/Command/IndexerReindexCommand.php#L75)) should execute the exact same thing.
Currently both those entry points have separate codebases for executing their logic which can lead to subtle inconsistencies if only one of both codebases are touched.

We should try to refactor the code into one shared codebase for both entry points.

### Examples

It looks like this (probably) accidentally happened at least once in [MAGETWO-51540](https://github.com/magento/magento2/commit/e8f2b0c385db4036d8953721046af7aabedd6b27)

### Proposed solution
@rogyar [proposed](https://github.com/magento/magento2/pull/29196#issuecomment-663983945) the following solution:
> Additionally, I would create a separate service i.e. `validateSharedIndex` and put the logic of `getIndexerIdsBySharedIndex` and `validateSharedIndex` there. So we can reuse the newly created class for the indexer processor and `IndexerReindexCommand`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#29196 by @hostep in 2.4-develop branch
Related commit(s):
 - [f0c645307e031f9c6b8beb31f18c801dc62c02e3](https://github.com/magento/magento2/commit/f0c645307e031f9c6b8beb31f18c801dc62c02e3)
 - [07d4ac67ce54e3b4be771f526975819d1d907d8b](https://github.com/magento/magento2/commit/07d4ac67ce54e3b4be771f526975819d1d907d8b)
 - [e9359f1ce92b61890df259114325e575c6dd02dd](https://github.com/magento/magento2/commit/e9359f1ce92b61890df259114325e575c6dd02dd)
 - [6a58f7ef0cf75b830f7a7c462d8fa7d010de317e](https://github.com/magento/magento2/commit/6a58f7ef0cf75b830f7a7c462d8fa7d010de317e)
 - [bc2aab7c2efec20cfdc83c62765da5c380dcb39e](https://github.com/magento/magento2/commit/bc2aab7c2efec20cfdc83c62765da5c380dcb39e)
 - [f9f3725e1326a375cecbd8fd1c70125d35adeaba](https://github.com/magento/magento2/commit/f9f3725e1326a375cecbd8fd1c70125d35adeaba)

The fix will be available with the upcoming 2.4.2 release.
