### ISSUE TITLE
Login as Customer storefront banner is not sticky

### ISSUE THREAD

**Issue by mbrinton01** [magento/magento2#29354]
### Preconditions (*)
Magento 2.4.0

### Steps to reproduce (*)
1. Enable Login as Customer
2. Login as Customer to the Storefront (view detail page for a customer in the admin panel, click "Login as Customer" in header)

### Expected result (*)
1. Persistent banner appears at top of screen
2. Per original UX design in https://xd.adobe.com/view/7c1347fc-d229-4afc-5ee7-1c53bdaec588-0a22/, banner is "sticky" and remains at top of screen when user scrolls down

### Actual result (*)
1. Persistent banner appears at top of screen
2. Banner is not "sticky." When user scrolls down on the page, banner scrolls out of view.

Actual result shown in video: 
[login as customer header.mov.zip](https://github.com/magento/magento2/files/5008483/login.as.customer.header.mov.zip)

---

- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

**Comment by mbrinton01** [comment]
FYI @sdzhepa

**Comment by mbrinton01** [comment]
FYI @smuletf

**Comment by konarshankar07** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36609` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @mbrinton01. Thank you for your report. 
The issue has been fixed in magento/magento2#29415 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [4f2d8de0f36132cab835e5af3bc88d461e87967f](https://github.com/magento/magento2/commit/4f2d8de0f36132cab835e5af3bc88d461e87967f)
 - [43cca51a6d361c73bfebcbeeebf2430e345b5157](https://github.com/magento/magento2/commit/43cca51a6d361c73bfebcbeeebf2430e345b5157)
 - [00b3ff2a037f03ce2a83b153c6476cf57ce6786e](https://github.com/magento/magento2/commit/00b3ff2a037f03ce2a83b153c6476cf57ce6786e)
 - [804ed717fbe4ece509cb7cac483ff0aa8945770f](https://github.com/magento/magento2/commit/804ed717fbe4ece509cb7cac483ff0aa8945770f)
 - [c0ca7cdf42a3f4425827fe61f4b7711ae0996e8b](https://github.com/magento/magento2/commit/c0ca7cdf42a3f4425827fe61f4b7711ae0996e8b)
 - [b35d9dcfa4e37b14be5bbb370b4d1258092494b6](https://github.com/magento/magento2/commit/b35d9dcfa4e37b14be5bbb370b4d1258092494b6)
 - [425113c355ca8cb880cfec8c2c362dbfd802795a](https://github.com/magento/magento2/commit/425113c355ca8cb880cfec8c2c362dbfd802795a)
 - [58b78f6d00d344563632822e9d90292cf7da31b1](https://github.com/magento/magento2/commit/58b78f6d00d344563632822e9d90292cf7da31b1)
 - [debeec23125bb76b9a65b4fb0613efddfecfc9cd](https://github.com/magento/magento2/commit/debeec23125bb76b9a65b4fb0613efddfecfc9cd)
 - [2aca78a139b29368f34f4c8d64c51763178856c8](https://github.com/magento/magento2/commit/2aca78a139b29368f34f4c8d64c51763178856c8)
 - [c3d57cd63cbc7b8c33adb0ad72489ef67477dd23](https://github.com/magento/magento2/commit/c3d57cd63cbc7b8c33adb0ad72489ef67477dd23)
 - [eca27c78db1621eac2ec16553f66d4519a00d56b](https://github.com/magento/magento2/commit/eca27c78db1621eac2ec16553f66d4519a00d56b)

The fix will be available with the upcoming 2.4.2 release.
