### ISSUE TITLE
[GraphQL] Wrong tags are set for CategoryList query

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#29372]
We have an integration test that verifies pretty strange behavior: "category tag is present in X-Magento-Tags for current Query if it was present in the previous query"

**Steps to reproduce**

1. Run only 1 test-case "testRequestCacheTagsForCategoryListOnMultipleIds": 
Magento\GraphQlCache\Controller\Catalog\CategoryListCacheTest::testRequestCacheTagsForCategoryListOnMultipleIds
```
Magento\GraphQlCache\Controller\Catalog\CategoryListCacheTest::testRequestCacheTagsForCategoryListOnMultipleIds
Failed asserting that two arrays are equal.
--- Expected
<ins></ins><ins> Actual
@@ @@
 Array (
     0 => ‘cat_c’
-    1 => ‘cat*c*333’
-    2 => ‘cat*c*400’
-    3 => ‘cat*c*401’
-    4 => ‘FPC’
</ins>    1 => ‘cat*c*400’
<ins>    2 => ‘cat*c*401’
</ins>    3 => ‘FPC’
 )
/magento/dev/tests/integration/testsuite/Magento/GraphQlCache/Controller/Catalog/CategoryListCacheTest.php:108
FAILURES!
Tests: 1, Assertions: 2, Failures: 1.
{code}

2. Run all tests-cases Magento\GraphQlCache\Controller\Catalog\CategoryListCacheTest:
{code}
testsuite/Magento/GraphQlCache/Controller/Catalog/CategoryListCacheTest.php
PHPUnit 9.1.5 by Sebastian Bergmann and contributors.
Warning:       Using a custom test suite loader is deprecated
....                                                                                                                           4 / 4 (100%)
Time: 01:02.900, Memory: 98.00 MB
OK (4 tests, 12 assertions)
```

Expected behaviour: tag "333" form First request should not be "remembered" from one request to another and present in response for Second request

Note: 
- possible this is issue in integration framework, so need to check this behavior without tests
- possible this issue is present in Luma as well (not only for GQL) and it should be escalated with their priority

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-35798

**Comment by pmarjan** [comment]
**From Description**
The way that this issue is described in the first place

- run only one test (testRequestCacheTagsForCategoryListOnMultipleIds) from the test class
- run the full class

 and the `$actualCacheTags` result are different for single test case run and the full class, suggests that the tests are NOT independent of each other.

**Production behavior**
I checked the behavior without tests, and on Luma too, and as far as I can tell there is no production code issue.
The problem is strictly in the tests.

**Independence Problem explanation**
The class that accumulates cache tags is `Magento\GraphQlCache\Model\CacheableQuery`.
This is instantiated in `Magento\GraphQlCache\Model\CacheableQueryHandler`, which on its own is instantiated in `Magento\GraphQlCache\Model\Plugin\Query\Resolver`.

These three objects are singletons, as the should be, as it is expected that tags are accumulated for different entities. 
New `Resolver` instance, and for that matter `CacheableQueryHandler` and `CacheableQuery` instanes, are created only and only for new payloads. 
_Therefore if two test functions, have the same payload, for the first, yes new `Resolver` will be constructed, but for the second no, the same `Resolver` instance is used._ And how `CacheableQuery::addCacheTags()` method is defined, it will combine tags from all previous test functions.

`CategoryListCacheTest` uses the same payload 4 times in a row - only once the `Resolver` is instantiated for the first test function `testRequestCacheTagsForCategoryList`.
For comparison, `ProductsCacheTest` uses the same payload in methods `testRequestCacheTagsForProducts` and `testConsecutiveRequestsAreServedFromThePageCache` which results in missed instantiation of the `Resolver` for `testConsecutiveRequestsAreServedFromThePageCache`.

**Take away**
Any test class in the GraphQlCache domain, that extends AbstractGraphqlCacheTest will have to be careful NOT to invoke same payload in different test functions as this will break test Independence principle. One phpunit call is one application request and the business implementation of singletons simply leads to this undesired consequence.
