### ISSUE TITLE
Hardcoded path causes collisions

### ISSUE THREAD

**Issue by miguelbalparda** [magento/magento2#29373]
https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Analytics/Model/ExportDataHandler.php#L25

This hardcoded path will cause issues when more than 1 Magento install is using the same server. It might be useful to make it unique per install, maybe using the domain URL or another unique value.

### Preconditions (*)

1. Magento Analytics installed
2. More than one Magento instance on the same server

### Steps to reproduce (*)

1. Found static path $subdirectoryPath = 'analytics/'; in dir magento2/app/code/Magento/Analytics/Model/ExportDataHandler.php
2. We used Magento 1st instance and made some minor code changes as per https://github.com/magento/magento2/issues/29373#issuecomment-885023346 in CollectData.php and ExportDataHandler.php respectively to print the dir /private/tmp/analytics/tmp/.
3. We used Magento 2nd instance and made same code changes in CollectData.php and ExportDataHandler.php respectively to print the dir /private/tmp/analytics/tmp/.

**Issue:** Both Magento instances are inserting the analytics data to the same path.

### Expected result (*)

1. Different Magento 2 installs will use different paths

### Actual result (*)

1. Different Magento 2 installs will use the same paths

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
Issue totally makes sense. So if I understand it correctly multiple Magento installations on the same (linux) server will all write to `/tmp/analytics/` which might mix up data for all these shops together and send them over to Magento Analytics service, which can lead to very incorrect data and can probably even be seen as a security issue...

@sidolov: can somebody verify and then assign priorities?

**Comment by sidolov** [comment]
@hostep yes, we will verify all the not confirmed tickets marked as stale before the due date. Thank you for the input!

**Comment by hostep** [comment]
This stalebot is getting a bit annoying...

**Comment by hostep** [comment]
This stalebot is getting a bit annoying...

**Comment by engcom-Delta** [comment]
Hi @miguelbalparda,

Tried reproducing the issue on Magento 2.4 Develop and Magento 2.4.2 but not clear  on which server you are trying to install @step no 2.Please provide server details.

Kindly specify what are the different paths you have found.so that we can reproduce this issue.

Hence added the label 'Needs Update'

Thanks

**Comment by hostep** [comment]
@engcom-Delta : you need to install 2 separate Magento instances on the same machine. No disrespect since you are new here, but it would be appreciated if somebody else with a bit more experience could have a look as well.

**Comment by engcom-Delta** [comment]
Hi @hostep,

It would be great if you can help with sample reports & screenshots. also lets know the specific module you have installed for Analytics purpose.

Thanks

**Comment by hostep** [comment]
@engcom-Delta. The Analytics module is the one from Magento itself: Magento_Analytics that gets installed by default.

On certain systems, the php function call `sys_get_temp_dir` can return something that is always the same for multiple Magento installations. Quoting from [the link](https://www.php.net/manual/en/function.sys-get-temp-dir.php#121073) I posted [above](https://github.com/magento/magento2/issues/29373#issuecomment-754786621):

> If running on a Linux system where systemd has PrivateTmp=true (which is the default on CentOS 7 and perhaps other newer distros), this function will simply return "/tmp", not the true, much longer, somewhat dynamic path.

In order to simulate this, please add the following changes in code to the Magento codebase:
```diff
diff --git a/app/code/Magento/Analytics/Cron/CollectData.php b/app/code/Magento/Analytics/Cron/CollectData.php
index ff0b3e4f676..428776e275e 100644
--- a/app/code/Magento/Analytics/Cron/CollectData.php
+++ b/app/code/Magento/Analytics/Cron/CollectData.php
@@ -44,9 +44,9 @@ class CollectData
      */
     public function execute()
     {
-        if ($this->subscriptionStatus->getStatus() === SubscriptionStatusProvider::ENABLED) {
+        // if ($this->subscriptionStatus->getStatus() === SubscriptionStatusProvider::ENABLED) {
             $this->exportDataHandler->prepareExportData();
-        }
+        // }

         return true;
     }
diff --git a/app/code/Magento/Analytics/Model/ExportDataHandler.php b/app/code/Magento/Analytics/Model/ExportDataHandler.php
index 4dbc316d090..6eebb022562 100644
--- a/app/code/Magento/Analytics/Model/ExportDataHandler.php
+++ b/app/code/Magento/Analytics/Model/ExportDataHandler.php
@@ -91,7 +91,10 @@ class ExportDataHandler implements ExportDataHandlerInterface
         try {
             $tmpDirectory = $this->filesystem->getDirectoryWrite(DirectoryList::SYS_TMP);

-            $this->prepareDirectory($tmpDirectory, $this->getTmpFilesDirRelativePath());
+            $absPath = $this->prepareDirectory($tmpDirectory, $this->getTmpFilesDirRelativePath());
+            echo ".\n" . $absPath . "\n";
+            die();
+
             $this->reportWriter->write($tmpDirectory, $this->getTmpFilesDirRelativePath());

             $tmpFilesDirectoryAbsolutePath = $this->validateSource($tmpDirectory, $this->getTmpFilesDirRelativePath());
```

Then download [magerun2](https://files.magerun.net/) and simulate running the cronjob and specifying the temp directory:
```
php -d upload_tmp_dir=/tmp n98-magerun2.phar sys:cron:run analytics_collect_data
```

You will see that this directory is `/tmp/analytics/tmp/` (on Linux, or `/private/tmp/analytics/tmp/` on macOS) and it will be the same for all Magento installations on the same machine.

The expectation is that something unique to the Magento installation gets inserted in that path to make it unique per Magento installation so that analytics data from different Magento installations aren't written to the same directory.

I hope it's clear enough now? 🙂

**Comment by engcom-Lima** [comment]
Hi,

Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
1. Found static path **$subdirectoryPath = 'analytics/';** in dir magento2/app/code/Magento/Analytics/Model/ExportDataHandler.php
2. We used Magento 1st instance and made some minor code changes in CollectData.php and ExportDataHandler.php respectively to print the dir /private/tmp/analytics/tmp/.
3. We used Magento 2nd instance and made some minor code changes in CollectData.php and ExportDataHandler.php respectively to print the dir /private/tmp/analytics/tmp/.
**Issue:** Both Magento instances are inserting the analytics data to the same path.
