### ISSUE TITLE
Free Shipping Method not showing in backend

### ISSUE THREAD

**Issue by tigerx7** [magento/magento2#2939]
When creating an order in the backend, the Free Shipping Method is not showing up as an available option.
## Steps to Reproduce

In the Default Config store view configuration, enable "Free Shipping" method, set minimum order amount to $79. For comparison purposes, enable "Flat Rate" shipping method with a per item $5 value. Refresh cache and then go to Sales -> Orders, select Customer (or new Customer). Select a product with a subtotal value of $100. Enter a valid address and then click on "Get shipping methods and rates". Only the fixed rate is returned, there's no "Free Shipping" option.

Now if we do the same thing through the frontend, add the $100 product to the cart and retrieve rates via "Estimate Shipping" or "Checkout", it will show both "Free Shipping" and "Flat Rate". 
## Troubleshooting

In the core_config_data, both freeshipping and flatrate have scope = default, scope_id = 0 for their values and both are active. Both also have sallowspecific set to 0 and specificcountry is NULL. I also attempted trying to set a specific country, and same result. I'm not exactly sure what's happening.

**Comment by tigerx7** [comment]
Just came by this today but may be related to this issue. Looks like promotional cart price rules are not being run for admin orders. 

Created a new cart price rule, "Free Shipping". For websites, selected the only one available "Main Website", and all customer groups. Coupon: "No Coupon". Conditions: "Subtotal equals or greater than 99"; Actions: "Free Shipping: For matching items only".

On the website, cart price rule is executing for orders $99+ and the free shipping option is shown. However, when creating the same order in admin, the free shipping option is not shown.

**Comment by Mulderua** [comment]
Hi @tigerx7 , thank you for the report!
Internal ticket MAGETWO-54640 was created.

**Comment by lfritsche** [comment]
Hi @NadiyaS,

is there any update about this?
I'm using M2.0.4 and 2.0.7 and facing the same issue.
Right now we're using discount coupons in the backend to provide free shipping through admin/backend orders.

Additionally I recognized, that "Subtotal" within a cart price rule (free shipping from 35€ an above) is calculated excluding tax. What about carts with mixed products (low- and high- taxed products).
In this case I'm not able to provide a subtotal value excl. tax. I tried to provide free shipping as rule to customers buying products for more than 35€ incl. tax (German Store)
I would need the subtotal value including tax as rule option to apply the rule for carts with mixed taxes.

Thank you!

**Comment by NadiyaS** [comment]
Hi @leanderfritsche ,
thank you for additional information.
This issue was estimates with not very high priority, so it is not in progress right now. 
When it is fixed and delivered to develop branch we will let you know.

Thanks for understanding.

**Comment by SerhiyShkolyarenko** [comment]
MAGETWO-54640 is delivered to the develop branch. We are closing the issue. 
Issues for backporting are MAGETWO-61090(ver. 2.1) and  MAGETWO-61091(ver. 2.0)

**Comment by umang-ranium** [comment]
I am using Magento ver. 2.1.2 facing the same issue, free shipping is not showing up for backend orders i have multiple stores.

**Comment by jameshalsall** [comment]
This is still a problem @SerhiyShkolyarenko, in `Magento\Quote\Model\Quote\Address::requestShippingRates()` the call to `$this->getBaseSubtotalTotalInclTax()` returns null when placing an order via the admin.

**Comment by martinhetschel** [comment]
https://github.com/magento/magento2/commit/c6615dd8f91c08d474bbfcfa6f1de1e577f2d87a

is working for me!

**Comment by WebMaster-Capillus** [comment]
We're having the same problem. Magent 2.1.6 Enterprise Cloud Edition.

**Comment by apasare** [comment]
the issue is still present in 2.1.x, there is no backport from 2.2 to 2.1

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-2939-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-2939-2-3-0.instances.magento-community.engineering/admin](https://i-2939-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@tigerx7 thank you for reporting the issue. We are closing because it is fixed at least in the latest release.

**Comment by broeder** [comment]
Exact same problem with Magento2.4.3-p1
