### ISSUE TITLE
Customer Token Life in system config

### ISSUE THREAD

**Issue by ejaz-alam** [magento/magento2#29487]
This field should be save empty, but incorrect validation was applied. Because of that, admin user couldn't save the empty value.

### Preconditions (*)

1. Magento 2.4 CE

### Steps to reproduce (*)

1. Go to Stores > Settings > Configuration > Services > OAuth
2. Save Customer Token Lifetime (hours) without any value, Should be empty as mentioned in comment note

### Expected result (*)

1. configuration should save with empty value.

### Actual result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/22393364/89993044-94a56700-dc9f-11ea-9500-4e764bb263b9.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aliejaz55** [comment]
@magento I am working on this

**Comment by aliejaz55** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @aliejaz55. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aliejaz55, here is your [Magento instance](https://i-29487-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29487-2-4-develop.instances.magento-community.engineering/admin_c662](https://i-29487-2-4-develop.instances.magento-community.engineering/admin_c662)
Login: `1e8f3a93` Password: `23acb281bacc`
Instance will be terminated in up to 3 hours.

**Comment by aliejaz55** [comment]
fixed in  https://github.com/magento/magento2/pull/29486

**Comment by aliejaz55** [comment]
@rogyar  Could you review this one please ?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37639` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @ejaz-alam. Thank you for your report. 
The issue has been fixed in magento/magento2#29486 by @ejaz-alam in 2.4-develop branch
Related commit(s):
 - [7341b4f3acb4fbca10b6b5dc76e560b8415e81d6](https://github.com/magento/magento2/commit/7341b4f3acb4fbca10b6b5dc76e560b8415e81d6)
 - [e0a99e180df36efee97e5c3c9515eb104e9cbf32](https://github.com/magento/magento2/commit/e0a99e180df36efee97e5c3c9515eb104e9cbf32)
 - [fdb4b7f5eba6441d453e26f41e36c0e1935bf865](https://github.com/magento/magento2/commit/fdb4b7f5eba6441d453e26f41e36c0e1935bf865)
 - [d4f14aef3fc49b57bdcfd3754a5290dafd2914f5](https://github.com/magento/magento2/commit/d4f14aef3fc49b57bdcfd3754a5290dafd2914f5)
 - [b78479e2ab6f5e71a6c13c5f966c8740f091e131](https://github.com/magento/magento2/commit/b78479e2ab6f5e71a6c13c5f966c8740f091e131)
 - [1f137fcb340fdba58cc85ab25a9100392e180c44](https://github.com/magento/magento2/commit/1f137fcb340fdba58cc85ab25a9100392e180c44)
 - [459fc2331762bdb7f5c9d84980d6980f712d5c99](https://github.com/magento/magento2/commit/459fc2331762bdb7f5c9d84980d6980f712d5c99)

The fix will be available with the upcoming 2.4.2 release.
