### ISSUE TITLE
Theme issue - wrong UX

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#2964]
Responsive design at default M2 theme has usability issue for tablets. 
It is not good idea to display filters AFTER products.
https://s.mail.ru/4EmNRvXS5DFz/img-2016-01-12-11-54-13.png
It's better to display some icon or button BEFORE products which will call filters block, just as on mobile view (https://s.mail.ru/2A9VJvvB1fLR/img-2016-01-12-11-56-29.png).

Please consider,
Stanislav Golodov, Product Manager at aheadWorks.

**Comment by vil11** [comment]
@stasleo, that's a good point indeed! I would really like to use the tablet with such long screen so that both Catalog & Layered Navigation become visible without swiping the view-port down =)

But it's not a UX issue, more looks like a functional one. I can observe the "2-columns" layout on iPad (just the same as on desktop), I suppose your tablet device is just a little bit more narrow & that's why you have "1-column" layout already applied... partly.
You've found some kind of a half-way state between the desktop design & the mobile one. That's the issue.

Internal ticket **MAGETWO-47996**.

Dmytro Vilchynskyi, M2 QA engineer.

**Comment by MomotenkoNatalia** [comment]
Internal ticket MAGETWO-47996 is closed and delivered to mainline. Please let us know if you still have an issue.
