### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#2965]
Hi,

Does Magento have a release schedule for further M2 versions?

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by alankent** [comment]
(The answer by the way is roughly quarterly, and would I surprise anyone to say you can expect 2.1 will be released to somehow line up with Imagine... because its nice to have something to announce at the conference.)

**Comment by cscd98** [comment]
@alankent Thanks Alan

**Comment by cscd98** [comment]
@alankent Any updates on 2.1?

**Comment by alankent** [comment]
I checked with the team - the current target is mid June. I had thought it would be made to align with Imagine, but it was decided "do it right, not do it just for a conference announcement." So sorry for misleading guess earlier, I know delays are always painful, but long term I think the principle being followed is the right thing to do. We are also working hard on getting the patch cadence better as a pressure release as well (that is, make it easier to get critical issues into patches).

I _suspect_ we will be moving to a more "release when ready" mentality rather than a "date is paramount". I think this is an example of it. It makes more sense since not all features are the same size. But this is _not_ an official announcement. If not clear, I own making sure all the products align technically (including with community), I don't live daily in the execution side of the world. So always happy to share, but it can be a little less accurate than official channels (ie. from people who own it).

**Comment by rudik99** [comment]
Hi Alan, 
Really appreciate your transparency, it's fantastic.
Do you know what is the strategy for minor releases, quite a lot of fixes in the develop branch, how often do you think that will get rolled up for wider release? 
Rudi

**Comment by alankent** [comment]
We are certainly trying to release patches more often. The team have been working on putting practices in place to avoid repeating previous mistakes. The issue of frequent patches is always a balancing act between risk of patch (any change can impact someone), effort/cost of patch (patches involve testing), impact of just deferring until next release (given releases are aimed to be more frequent).

For example, we have the new marketplace up. Now can we do a better job of prior to release making sure useful combinations of extensions work through an upgrade? Once we get moving from 2.0 to 2.1 to 2.2 etc smoother (for core Magento code + extensions), I think that can take some pressure off backporting as much code to previous releases.

M2 has more tools in the toolbox than M1 to avoid extension conflicts and upgrade pain, but I would rather demonstrate it working and then claim victory rather than the other way around. Vision is great, delivery is better!
