### ISSUE TITLE
Unable to override knockout template for form groups

### ISSUE THREAD

**Issue by chicgeek** [magento/magento2#2968]
I'm trying to override a knockout template for form groups. I've copied over the file to the module folder in my theme dir and regenerated the assets, with no luck.

An example of content that uses this template are the two address text inputs in the checkout. Here is the template file I'm trying to overwrite, and the override path. **This does not work**:

```
/app/code/Magento/Ui/view/frontend/web/templates/group/group.html
/app/design/frontend/MyPackage/MyTheme/Magento_Ui/web/templates/group/group.html
```

The same method works as expected for other form UI templates. For example, **this works**:

```
/app/code/Magento/Ui/view/frontend/web/templates/form/field.html
/app/design/frontend/MyPackage/MyTheme/Magento_Ui/web/templates/form/field.html
```

I am editing the correct template for what I want to change. I am able to make changes to the core file and regenerate - I see those changes. It does not pick up my theme version of this file.

**Comment by chicgeek** [comment]
After some more fiddling with caches, this works after all. Closing the issue.

**Comment by rixitpatel13** [comment]
Hi, I got the things but what I am not getting is that How can I apply any custom onchange function for the zip code field on onepage checkout !

because what HTML is displaying, its generating by Knockout JS !

so, please tell me how can I do that !

Thanks in advance !

**Comment by korostii** [comment]
@rixitpatel13, please stop flooding random closed issues. Since you're experiencing a similar yet different issue, please create a new issue. If you expect meaningful answers, please also provide the details including, but not limited to: your environment, steps to reproduce, expected and actual results. 
In your specific case, providing the custom code you're using is also a good idea.

Please also note that the GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here. 
If you are looking for some help or an advice regarding development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) instead.
