### ISSUE TITLE
Magento 2 product YouTube video is not playing for the simple products within a configurable product

### ISSUE THREAD

**Issue by MagDevX** [magento/magento2#29690]
This issue was reported here ( https://github.com/magento/magento2/issues/23107 ) but could not be reproduced. In my tests in clean installations of v2.3.5-p1 this problem consistently happened when a video is added to the simple products within a configurable product if those simple products already have a photo and the video is moved to the position before (to the left of) image.

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Create a configurable product containing 3 simple products that vary in color (make sure to upload an image for each simple product and for the configurable product, then save the configurable product).
2. Now that the listing is published, add a YouTube video to each simple product and move it to the first position (to the left of the image). Then save the changes.

### Expected result (*)

1. The video of any options (i.e. simple products) within the configurable product would be displayed.

### Actual result (*)

1. If you check the frontend and switch between the options (i.e. simple products), you will see that the video is just a thumbnail and will not play.
![Peek 2020-09-03 15-23](https://user-images.githubusercontent.com/51681379/92114529-a63ee200-edf9-11ea-8c5e-3f40f1e941d6.gif)

The problem seems to be that the order of adding videos and images matters. The videos should be uploaded first, then the images should be added. Otherwise the videos would not play.

Workaround:
1. Remove the images from the simple products, so that only the video remains, then save the simple products.
2. Now add the images back to the simple products.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37344` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by viniciusbordinhao-blueacorn** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @MagDevX. Thank you for your report. 
The issue has been fixed in magento/magento2#30938 by @viniciusbordinhao-blueacorn in 2.4-develop branch
Related commit(s):
 - [e3276fcf458ccc8d35248d2d83a68c73908afd63](https://github.com/magento/magento2/commit/e3276fcf458ccc8d35248d2d83a68c73908afd63)
 - [db17e70f8ec0b2da5f7e9dfe6434d5b37cfcdf21](https://github.com/magento/magento2/commit/db17e70f8ec0b2da5f7e9dfe6434d5b37cfcdf21)
 - [24adb1448ef850ba2127acb80ac5abfbf94f5d1c](https://github.com/magento/magento2/commit/24adb1448ef850ba2127acb80ac5abfbf94f5d1c)
 - [bd6411fc73ccc56f0695e351a1f27ec3c65970e4](https://github.com/magento/magento2/commit/bd6411fc73ccc56f0695e351a1f27ec3c65970e4)
 - [1b11a71ff1a141c1d58b651f2cdeefabffd4f6bd](https://github.com/magento/magento2/commit/1b11a71ff1a141c1d58b651f2cdeefabffd4f6bd)
 - [acf585f35cc35a28bfa159ae3badb366decf3892](https://github.com/magento/magento2/commit/acf585f35cc35a28bfa159ae3badb366decf3892)
 - [7871905ee2cc1ede33e76b02a603c4a2c0041995](https://github.com/magento/magento2/commit/7871905ee2cc1ede33e76b02a603c4a2c0041995)

The fix will be available with the upcoming 2.4.3 release.

**Comment by tuyennn** [comment]
@magento give me 2.4-develop instance
