### ISSUE TITLE
Magento 2 gets stuck at 59% with the installing the module Magento_GoogleShoppingAds

### ISSUE THREAD

**Issue by mozinomer** [magento/magento2#29723]
![Screenshot (203)](https://user-images.githubusercontent.com/28697746/91017398-9f4cee00-e607-11ea-9673-7a3edbca98dd.png)

Magento 2 gets stuck at 59% with the installing the module Magento_GoogleShoppingAds

Any possible solution for this?

**Comment by engcom-Delta** [comment]
Hello @mozinomer 
Could you provide more details for reproduce this issue?
Please add version of magento.
What value is in memory_limit (php.ini)?
Are there any errors in the logs?

Thank you!

**Comment by mozinomer** [comment]
Hy @engcom-Delta.

Magento Version is 2.3 and it gets stucks at 59% of installation on the windows but worked fine on the Linux and Mac 
the Value in the php.ini is more than 4GB
nope am afraid there isn't any error log it just get stucks

**Comment by engcom-Delta** [comment]
Hello @mozinomer 
According to the [documentation](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements_repo-tls1-2.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=2.4%20requirements):
 
> The Web Setup Wizard is being deprecated in Magento 2.3.6 and will be removed in Magento 2.4.0. After it is removed, you must use the command line to install or upgrade Magento.

Magento works well on the Linux [because](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html):

> Linux distributions, such as RedHat Enterprise Linux (RHEL), CentOS, Ubuntu, Debian, and similar. Magento is not supported on Microsoft Windows and macOS.

But it`s possible to use [Virtual machine or container (host)](https://devdocs.magento.com/cloud/before/before-workspace-magento-prereqs.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=VM) on the Windows
