### ISSUE TITLE
Unable to create shipping label after creating shipment.

### ISSUE THREAD

**Issue by dev-ajaysaini** [magento/magento2#29817]
Unable to create shipping label for already shipped order.

### Preconditions (*)

1. Magento 2.4.0
2. Choose shipping method which have feature to create shipment label.

### Steps to reproduce (*)

1. Place an order with simple product
2.Choose shipping method which have feature to create shipment label.
3. Do shipment without creating shipping label for the same order.
4. Go to Shipments and choose shipment and then try to click on create shipping label button after that there it shows already 2 packages fields which can't be remove or unable to add products in to packages. https://prnt.sc/u8y96r also found some issue in console https://nimb.ws/pucMnw

### Expected result (*)

1. Admin should be able to add delete package and order items and create shipment label.

### Actual result (*)

1. https://nimb.ws/pucMnw
2. https://prnt.sc/u8y96r

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [1] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [1] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vasilii-b** [comment]
@magento give me 2.3.5-p1 instance

**Comment by Vishrootways** [comment]
@webkul-ajaysaini This is knowing issue of Magento 2.4.0. Here is the patch to solve this issue https://support.magento.com/hc/en-us/articles/360046750171-Shipping-labels-creation-known-issue-in-Magento-2-4-0

**Comment by engcom-Bravo** [comment]
Hello @webkul-ajaysaini 

Thank you for your report. 

This issue is already fixed in 2.4.1 and 2.4-develop Magento versions
Admin is able to create Shipping label, add/delete packages

We are closing this issue. Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by miteshdhaduk** [comment]
Not working in CE Magento2.4.2.

**Comment by juharintanen** [comment]
> 

I found out, that in Magento_Shipping::order/packaging/grid.phtml there is a row for fetching **Order Item Id**.

$id = $item->getId() ?? $item->getOrderItemId();

If you are trying to create label to a order that already has shipment, it's fetching items in sales_shipment_item table, so that row should actually be other way around because now its getting the wrong id.

So:
$id = $item->getOrderItemId() ?? $item->getId();

**Comment by eerohakio** [comment]
> > @engcom-Bravo Not working in CE Magento2.4.2.
> > Grid is not open after click on **Add Products to Package** for already shipped order(UPS shipping method).
> > No error in console or in var/log folder.
> 
> I found out, that in Magento_Shipping::order/packaging/grid.phtml there is a row for fetching **Order Item Id**.
> 
> $id = $item->getId() ?? $item->getOrderItemId();
> 
> If you are trying to create label to a order that already has shipment, it's fetching items in sales_shipment_item table, so that row should actually be other way around because now its getting the wrong id.
> 
> So: $id = $item->getOrderItemId() ?? $item->getId();

As @juharintanen mentioned this is valid. Tested also in Magento 2.4.3-p1. With the fix mentioned got the thing working.
