### ISSUE TITLE
[Magento 2.3.5 p2] Upload fails in image uploader

### ISSUE THREAD

**Issue by raghav111jain** [magento/magento2#29852]
### Preconditions (*)

1.magento 2.3.5 p2
2.php 7.3

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**show this error please help ASAP**

**"Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/designoneonline/public_html/shop/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php:365 Stack trace: #0 /home/designoneonline/public_html/shop/generated/code/Magento/Cms/Model/Wysiwyg/Images/Storage/Interceptor.php(37): Magento\Cms\Model\Wysiwyg\Images\Storage->getFilesCollection('/home/designone...', NULL) #1 /home/designoneonline/public_html/shop/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(60): Magento\Cms\Model\Wysiwyg\Images\Storage\Interceptor->getFilesCollection('/home/designone...', NULL) #2 /home/designoneonline/public_html/shop/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(74): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFiles() #3 /home/designoneonline/public_html/shop/vendor/magento/module-cms/view/adminhtml/templates/browser/content/files.phtml(13): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFilesCount() #4 /home/designoneonl in /home/designoneonline/public_html/shop/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php on line 365"**

**Comment by ajijshekh123** [comment]
Hello @raghav111jain,
Please add proper Steps to be reproduced, Actual result and Expected result.
Thanks.

**Comment by ihor-sviziev** [comment]
@raghav111jain 
please check if you have installed `fileinfo` extension, usually it goes bundled with php

**Comment by raghav111jain** [comment]
> @raghav111jain
> please check if you have installed `fileinfo` extension, usually it goes bundled with php
Thanks @ihor-sviziev its working man (fileinfo extension not installed)

**Comment by ihor-sviziev** [comment]
I'd like to reopen this task and add ext-fileinfo to the composer.json.
Could you provide more info how we can get the same php configuration as you had?

**Comment by ihor-sviziev** [comment]
This issue duplicates https://github.com/magento/magento2/issues/24332.

@raghav111jain FYI we have a pull request that solves this issue: https://github.com/magento/magento2/pull/29671, so after accepting this PR it will work even w/o fileinfo php extension.

As for now we have a workaround to install fileinfo extension.

**Comment by magento-engcom-team** [comment]
Hi @raghav111jain. Thank you for your report. 
The issue has been fixed in magento/magento2#29671 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [8344b1193b33ec89457b3717362dd923f4a7c97d](https://github.com/magento/magento2/commit/8344b1193b33ec89457b3717362dd923f4a7c97d)
 - [8da5e70859784f0cf097fae1bcbaa240db55fb85](https://github.com/magento/magento2/commit/8da5e70859784f0cf097fae1bcbaa240db55fb85)
 - [d312ab5f63f22329c3dde98cbcebb2347c8f077c](https://github.com/magento/magento2/commit/d312ab5f63f22329c3dde98cbcebb2347c8f077c)
 - [f7503ea597d79ed29b544daf169c7ced14ba42f9](https://github.com/magento/magento2/commit/f7503ea597d79ed29b544daf169c7ced14ba42f9)
 - [c09a26144f24548271e908efb4232baec079b92a](https://github.com/magento/magento2/commit/c09a26144f24548271e908efb4232baec079b92a)
 - [12098680bbfa555b8aad268bf8156ada710d507b](https://github.com/magento/magento2/commit/12098680bbfa555b8aad268bf8156ada710d507b)
 - [60c01638fe0f00d92184308eba1599cd58a74f6f](https://github.com/magento/magento2/commit/60c01638fe0f00d92184308eba1599cd58a74f6f)
 - [21f1eb357ce85f236f9af06ba3e429643ad28e3c](https://github.com/magento/magento2/commit/21f1eb357ce85f236f9af06ba3e429643ad28e3c)
 - [0cf0e09cf5453c7fb4f8502722b1a0447c00b9db](https://github.com/magento/magento2/commit/0cf0e09cf5453c7fb4f8502722b1a0447c00b9db)
 - [09bd902440a57c2253f8f44abbbe1da8e98901fc](https://github.com/magento/magento2/commit/09bd902440a57c2253f8f44abbbe1da8e98901fc)

The fix will be available with the upcoming 2.4.2 release.
