### ISSUE TITLE
"Item in Cart" not pluralized correctly

### ISSUE THREAD

**Issue by joeshelton-wagento** [magento/magento2#29920]
### Preconditions (*)
Magento 2.3.5
Sample Data installed

### Steps to reproduce (*)
Add a single product to the cart in a quantity of 3. (Or, any quantity greater than one.)

### Expected result (*)
In the minicart the text "3 Items in Cart" appears.
In the checkout order summary the text "3 Items in Cart" appears.

### Actual result (*)
In the minicart the text "3 Item in Cart" appears.
In the checkout order summary the text "3 Item in Cart" appears.

### Additional Information (*)
Seem problem happen when use config Display Cart Summary: Display item quantities <=Default option
Admin > Configuration > Sales > Checkout > My Cart Link

Test case 1: Add only one product and update qty to above a least 2 => NOT WORK
Test case 2: Add 2 products and update qty (optional) => WORK

The other option "Display number of items in cart" seem work

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by joeshelton-wagento** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @joeshelton-wagento. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @joeshelton-wagento, here is your [Magento instance](https://i-29920-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29920-2-4-develop.instances.magento-community.engineering/admin_cc35](https://i-29920-2-4-develop.instances.magento-community.engineering/admin_cc35)
Login: `52555f15` Password: `bbfa52e2ae6a`
Instance will be terminated in up to 3 hours.

**Comment by joeshelton-wagento** [comment]
Confirmed in 2.4
![2020-09-05_08-30-33](https://user-images.githubusercontent.com/23382713/92306101-5162af00-ef52-11ea-9eb4-72cee5c05e97.png)
![2020-09-05_08-31-10](https://user-images.githubusercontent.com/23382713/92306123-68090600-ef52-11ea-8873-c7bada0c6395.png)

**Comment by mrtuvn** [comment]
Seem problem happen when use config Display Cart Summary: Display item quantities <=Default option
Admin > Configuration > Sales > Checkout > My Cart Link

The other option "Display number of items in cart" seem work

I can confirmed this issue in 2.4

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-29920-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29920-2-4-develop.instances.magento-community.engineering/admin_5e0f](https://i-29920-2-4-develop.instances.magento-community.engineering/admin_5e0f)
Login: `67d1539c` Password: `690d47eae017`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37416` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saphaljha** [comment]
@magento I am working on this.

**Comment by gabrieldagama** [comment]
Hi @joeshelton-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#29923 by @saphaljha in 2.4-develop branch
Related commit(s):
 - [1ea32084a4c1a9fabe6af0dd6a3b9e219caf6795](https://github.com/magento/magento2/commit/1ea32084a4c1a9fabe6af0dd6a3b9e219caf6795)
 - [f01de6cad7c45055aa0a4b7308fe435aaf50a1f7](https://github.com/magento/magento2/commit/f01de6cad7c45055aa0a4b7308fe435aaf50a1f7)
 - [81866220d2c5e8a907e5c766c9fde7ac5773f6d6](https://github.com/magento/magento2/commit/81866220d2c5e8a907e5c766c9fde7ac5773f6d6)
 - [992de7a2ba61c32cb561616bbcf64a2dd5168372](https://github.com/magento/magento2/commit/992de7a2ba61c32cb561616bbcf64a2dd5168372)
 - [6489f079970c7ce03f72fed50ea742ddf063296d](https://github.com/magento/magento2/commit/6489f079970c7ce03f72fed50ea742ddf063296d)
 - [a883b69d42a683b80a94cc5cb3545db844f63ab9](https://github.com/magento/magento2/commit/a883b69d42a683b80a94cc5cb3545db844f63ab9)
 - [ce262002b56ff25401eee6ca0995a4213069faeb](https://github.com/magento/magento2/commit/ce262002b56ff25401eee6ca0995a4213069faeb)
 - [ee321602f3b256bf7af840ac961df320b0e67219](https://github.com/magento/magento2/commit/ee321602f3b256bf7af840ac961df320b0e67219)
 - [e677767fb391f7bb1b13f954eaeeca9b4633e47b](https://github.com/magento/magento2/commit/e677767fb391f7bb1b13f954eaeeca9b4633e47b)
 - [4c36fad625e6f87477286ecaa6ae0ef57205507a](https://github.com/magento/magento2/commit/4c36fad625e6f87477286ecaa6ae0ef57205507a)
 - [558b7d59571443e8ec1849ac1fc66ef8d62b8ea8](https://github.com/magento/magento2/commit/558b7d59571443e8ec1849ac1fc66ef8d62b8ea8)
 - [b034b4bb7dc391d0b4627a72ac1ef9d7a90f2a6b](https://github.com/magento/magento2/commit/b034b4bb7dc391d0b4627a72ac1ef9d7a90f2a6b)
 - [49573eb1e4768b845ba9e407361246f8d37bf4f7](https://github.com/magento/magento2/commit/49573eb1e4768b845ba9e407361246f8d37bf4f7)
 - [15c6380b5525df675574c5b95807d9f43f0b77bb](https://github.com/magento/magento2/commit/15c6380b5525df675574c5b95807d9f43f0b77bb)

The fix will be available with the upcoming 2.4.2 release.
