### ISSUE TITLE
item layout updates can't remove after add when create new widget

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#29936]
### Preconditions (*)

1. Magento 2.4-develop
2.

### Steps to reproduce (*)

1. Go to admin
2. Content > Widgets
3. Add new widget
4. In section "Layout Updates" Add Layout Update
5. Try to click on icon basket to remove item

### Expected result (*)

1. Item should be remove
2.

### Actual result (*)

1. Item cannot remove
2. Only first item could be removed
<img width="1481" alt="Screen Shot 2020-09-08 at 12 58 03" src="https://user-images.githubusercontent.com/1908873/92438642-61d58c80-f1d3-11ea-8201-94cb8688476b.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
@engcom-Delta Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37441` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saphaljha** [comment]
@magento I am working on this issue.

**Comment by bhaveshpp** [comment]
## Magento 2.4
I am facing the same issue in my project.
The console is clear there is no error in the console
https://drive.google.com/file/d/1EEhxFnAlPUu_-4srQGkQOP_iVtlLxIm6/view

Did anyone found any solution to this issue?

Thank you.

**Comment by mrtuvn** [comment]
You can see pull request links above

**Comment by bhaveshpp** [comment]
Hello,
It solved my issue.
https://github.com/magento/magento2/pull/29991/files
Thank you.

**Comment by bhaveshpp** [comment]
Hello,
After applying these file changes my issue with the widget is resolve but this change affects on system config field **use system value** checkbox
> https://github.com/magento/magento2/pull/29991/files

I am facing a new issue in store > Settings > Configuration
> https://drive.google.com/file/d/1idssPw1prXYuuIEe7-iKEgSqoA_CSz9S/view

Thank you.

**Comment by mrtuvn** [comment]
@bhaveshpp this is open PR and not accept yet by magento. You should use patch with caution and maybe this patch fix your problem but will possible break another function in other place

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn. Thank you for your report. 
The issue has been fixed in magento/magento2#29991 by @saphaljha in 2.4-develop branch
Related commit(s):
 - [7d6f8bb0846b863d8a2aa78b8ce1e480a7cf7413](https://github.com/magento/magento2/commit/7d6f8bb0846b863d8a2aa78b8ce1e480a7cf7413)
 - [1f0fe69c7965997b43995848119a3b5ec004de27](https://github.com/magento/magento2/commit/1f0fe69c7965997b43995848119a3b5ec004de27)
 - [87be948915016ff3398a3eec9af903cfd4dbc844](https://github.com/magento/magento2/commit/87be948915016ff3398a3eec9af903cfd4dbc844)
 - [9f9d2cbf492634a89cb97326fba68a02d9e7c175](https://github.com/magento/magento2/commit/9f9d2cbf492634a89cb97326fba68a02d9e7c175)
 - [89d3814530f20248a32b678fd9636bd990a5f9fb](https://github.com/magento/magento2/commit/89d3814530f20248a32b678fd9636bd990a5f9fb)
 - [08ca835531a52d74649e1dd01bccd3b1c9f1cf8f](https://github.com/magento/magento2/commit/08ca835531a52d74649e1dd01bccd3b1c9f1cf8f)
 - [788c26c8ed32630e8ab352c3f48d0764708cc0c6](https://github.com/magento/magento2/commit/788c26c8ed32630e8ab352c3f48d0764708cc0c6)
 - [357896acdaec16f9884f15cdd5170e5c76551fde](https://github.com/magento/magento2/commit/357896acdaec16f9884f15cdd5170e5c76551fde)
 - [04eaa23cf6409e23ea8de6c2dbc1b1cd4f156e85](https://github.com/magento/magento2/commit/04eaa23cf6409e23ea8de6c2dbc1b1cd4f156e85)
 - [dc957fb58307cc6f5ec62bc93140d9036790ce18](https://github.com/magento/magento2/commit/dc957fb58307cc6f5ec62bc93140d9036790ce18)
 - [28d724da89cf761ed0c81ad6c1cb17fbac8e8f76](https://github.com/magento/magento2/commit/28d724da89cf761ed0c81ad6c1cb17fbac8e8f76)
 - [2baf801a9e34f1be2aee737663ad6d5a1f47574c](https://github.com/magento/magento2/commit/2baf801a9e34f1be2aee737663ad6d5a1f47574c)
 - [bedee3d6471396b4a04e27d53d42568ee796714f](https://github.com/magento/magento2/commit/bedee3d6471396b4a04e27d53d42568ee796714f)
 - [e03e17ea488b91388f296ffef7978f12bb33f3d9](https://github.com/magento/magento2/commit/e03e17ea488b91388f296ffef7978f12bb33f3d9)
 - [0fee9a1ab949b29ae86fd4eca4150d4f6a10c895](https://github.com/magento/magento2/commit/0fee9a1ab949b29ae86fd4eca4150d4f6a10c895)
 - [20275ce6331957c854162c71742f7c9c7da25a50](https://github.com/magento/magento2/commit/20275ce6331957c854162c71742f7c9c7da25a50)
 - [a1f731f86f6fd3a5257ab042d952e48f5ace0440](https://github.com/magento/magento2/commit/a1f731f86f6fd3a5257ab042d952e48f5ace0440)
 - [7b37def433cbfa19f3176df3ce705442bb783407](https://github.com/magento/magento2/commit/7b37def433cbfa19f3176df3ce705442bb783407)
 - [e11e0a76a5ddb8cab7dbaf86fdaab5cde13c26ce](https://github.com/magento/magento2/commit/e11e0a76a5ddb8cab7dbaf86fdaab5cde13c26ce)
 - [901daf6771ca2179c886f25c80604f4105da0f83](https://github.com/magento/magento2/commit/901daf6771ca2179c886f25c80604f4105da0f83)

The fix will be available with the upcoming 2.4.3 release.
