### ISSUE TITLE
Users can not assign widgets to individual categories/products

### ISSUE THREAD

**Issue by mtbottens** [magento/magento2#30009]
### Preconditions (*)

1. Magento 2.4.0
2.

### Steps to reproduce (*)

1. Login to admin
2. Create Widget
3. Assign widget to anchor categories
4. Select "Specific Categories"

### Expected result (*)

1. Chooser appears
2. ![image](https://user-images.githubusercontent.com/3620915/92969299-ae76cd00-f44a-11ea-82e3-cc0d33d535de.png)

### Actual result (*)

1. Chooser does not appear 
2. ![image](https://user-images.githubusercontent.com/3620915/92969322-bafb2580-f44a-11ea-940c-92a32b34421e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37631` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Here is the issue screenshot for magento 2.4-develop:
![image](https://user-images.githubusercontent.com/46617848/93045085-ec0a6e80-f673-11ea-8ede-809174488c62.png)

**Comment by gabrieldagama** [comment]
Hi @mtbottens. Thank you for your report. 
The issue has been fixed in magento/magento2#30010 by @mtbottens in 2.4-develop branch
Related commit(s):
 - [51096cb8446ad542b76f127ca53ac48e9a39c944](https://github.com/magento/magento2/commit/51096cb8446ad542b76f127ca53ac48e9a39c944)
 - [fc741968d3c8a4d01d75be7d437bcf5a59f108c1](https://github.com/magento/magento2/commit/fc741968d3c8a4d01d75be7d437bcf5a59f108c1)
 - [f66bb6627d3eb50f319ac92a1cefddf06092268d](https://github.com/magento/magento2/commit/f66bb6627d3eb50f319ac92a1cefddf06092268d)
 - [d4c8d7098611daac7fb4169984dc2b56d5726d0d](https://github.com/magento/magento2/commit/d4c8d7098611daac7fb4169984dc2b56d5726d0d)
 - [bd97b9d7235ef130ccd2713986d076bfa87bd2a0](https://github.com/magento/magento2/commit/bd97b9d7235ef130ccd2713986d076bfa87bd2a0)
 - [90e7c77c3b315ba8167341b981f14cc56769de8b](https://github.com/magento/magento2/commit/90e7c77c3b315ba8167341b981f14cc56769de8b)
 - [e2512fd7e0c0d6d68f7d4954e658b836a80b6011](https://github.com/magento/magento2/commit/e2512fd7e0c0d6d68f7d4954e658b836a80b6011)

The fix will be available with the upcoming 2.4.2 release.
