### ISSUE TITLE
Input type datetime is used in lib styles

### ISSUE THREAD

**Issue by GrimLink** [magento/magento2#30064]
The `input[type=datetime]` has been depricated for some time -> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime
But is still used in the `lib/web/css/source/lib/_forms.less`

### Preconditions (*)

1. This issue is found in all magento 2 versions

### Steps to reproduce (*)
None, this styling issue, that has no major impact.

### Expected result (*)
The styling is applied for any input type date.
And not only for the datetime.

### Actual result (*)
Only the `input[type=datetime]` styled.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38233` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @GrimLink. Thank you for your report. 
The issue has been fixed in magento/magento2#30065 by @GrimLink in 2.4-develop branch
Related commit(s):
 - [d15f34dc6fdda1653e854b36f39f9549f8a70f72](https://github.com/magento/magento2/commit/d15f34dc6fdda1653e854b36f39f9549f8a70f72)
 - [beb817f0e243154c395585c995530ab96016fe7c](https://github.com/magento/magento2/commit/beb817f0e243154c395585c995530ab96016fe7c)

The fix will be available with the upcoming 2.4.2 release.
