### ISSUE TITLE
editorconfig: use an indentation of 2 for json and yaml files

### ISSUE THREAD

**Issue by GrimLink** [magento/magento2#30063]
### Summary (*)
Consider using a indentation of 2 for json and yaml files.
The recommended default for the package.json and yaml files is 2.

The only exception is composer that uses 4.

### Examples (*)
_None, this just a formatting suggestion_

### Proposed solution
See my Pr #30062 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Priority and Severity labels were copied from https://github.com/magento/magento2/issues/30066 that duplicates this issue

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38311` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @GrimLink. Thank you for your report. 
The issue has been fixed in magento/magento2#30062 by @GrimLink in 2.4-develop branch
Related commit(s):
 - [b70851de42e1430dc09f0ac88b4ecc8f82abc4fd](https://github.com/magento/magento2/commit/b70851de42e1430dc09f0ac88b4ecc8f82abc4fd)
 - [f7f5dce0d1415661441e9c8f5ccf0b24bea30f28](https://github.com/magento/magento2/commit/f7f5dce0d1415661441e9c8f5ccf0b24bea30f28)
 - [9ef8d9ddb9dbdc185489f0fe3475aade28da167a](https://github.com/magento/magento2/commit/9ef8d9ddb9dbdc185489f0fe3475aade28da167a)
 - [93d79b8d638568ac5a529b833cbb043333d3be0d](https://github.com/magento/magento2/commit/93d79b8d638568ac5a529b833cbb043333d3be0d)
 - [0533f2e35f4779d8b6fc14ed316c3c0e483698cb](https://github.com/magento/magento2/commit/0533f2e35f4779d8b6fc14ed316c3c0e483698cb)
 - [5b476475ad8eb2a99db7543f2881978b9b7fbe53](https://github.com/magento/magento2/commit/5b476475ad8eb2a99db7543f2881978b9b7fbe53)
 - [9d8a772c4f0efeb15f4fac12e294123f27e9f81b](https://github.com/magento/magento2/commit/9d8a772c4f0efeb15f4fac12e294123f27e9f81b)
 - [5f704dbd65b4f1cb8ca93a80d70cdbe466cf765c](https://github.com/magento/magento2/commit/5f704dbd65b4f1cb8ca93a80d70cdbe466cf765c)
 - [c722790487631c0ce78d753d2dfe9d97c7606a18](https://github.com/magento/magento2/commit/c722790487631c0ce78d753d2dfe9d97c7606a18)

The fix will be available with the upcoming 2.4.2 release.
