### ISSUE TITLE
BC in Magento\Sales\Model\Order\Pdf

### ISSUE THREAD

**Issue by fooman** [magento/magento2#30071]
### Preconditions (*)

1. current 2.4-develop and/or 2.4.1-beta1

### Steps to reproduce (*)

1. check https://github.com/magento/magento2/commit/66d259ed37ac8d7170012e14efb5df12c562cf13

### Expected result (*)

1. removal of parameter should trigger version bump for module-sales or new param should be added at the end see https://devdocs.magento.com/contributor-guide/backward-compatible-development/#:~:text=Backward%20Compatibility%20Policy&text=v2.,the%20'marketing%20version'%20number.&text=Necessary%20MAJOR%20and%20MINOR%20changes,ultimately%20decides%20what%20is%20allowed. "Adding a constructor parameter"

### Actual result (*)

1. $appEmulation replaces $_localeResolver

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @fooman ,
This class isn't marked as API, so it's fine to replace some arguments in minor versions

**Comment by fooman** [comment]
Thanks @ihor-sviziev from the outside I see a lot of PRs being requested to change something like the above constructor argument change (including for non-api). 

From my perspective such changes should be reserved for 2.x releases to increase stability in 2.x.y releases.

**Comment by ihor-sviziev** [comment]
@fooman yeah, as a maintainer sometimes I'm asking to make backward compatible changes if that's possible in order to have easier upgrades for everyone, but it's not really required by now - as of today from the automated Semantic Version Checker complains about classes marked with `@api` tag only. The same rule applies for internal teams.

Actually maintaining backward compatibility also have downside - we're getting more and more  not used dependencies that obviously not a good thing and slows down application, so there should be some balance.
