### ISSUE TITLE
Store specific text swatch attribute option label with value 0 (zero) can't be saved and automatically replaced with Admin Label value of option

### ISSUE THREAD

**Issue by Stepa4man** [magento/magento2#30073]
Store-specific text swatch attribute option label with value 0 (zero) can't be saved and automatically replaced with Admin Label value of the option

### Preconditions
* Magento 2.3.5-p2, 2.4-develop

### Steps to reproduce
1. Create multistore Magento instance
2. Create text swatch attribute
3. Insert in non-default store label input field **0** (like at the screenshot)
![image](https://user-images.githubusercontent.com/15912461/93345741-75b46a80-f833-11ea-9f31-5b461e41ebbc.png)
4. Save attribute

### Expected result
1. Store-specific option label saved as inserted

### Actual result
1. Instead of **0** option store specific label is replaced with Admin label value
![image](https://user-images.githubusercontent.com/15912461/93345778-81a02c80-f833-11ea-868a-674f6454a45a.png)

**Comment by Stepa4man** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
@engcom-Oscar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37713` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bartlomiejsz** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Hi @Stepa4man. Thank you for your report. 
The issue has been fixed in magento/magento2#30114 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [080a349d99b9d3190448a67a269242c575b255b3](https://github.com/magento/magento2/commit/080a349d99b9d3190448a67a269242c575b255b3)
 - [aaab946db220cb64f4e3d2d59bc39925b217b27f](https://github.com/magento/magento2/commit/aaab946db220cb64f4e3d2d59bc39925b217b27f)
 - [d552d80db1780ade14adc3422e0d0d2a3512f52a](https://github.com/magento/magento2/commit/d552d80db1780ade14adc3422e0d0d2a3512f52a)
 - [7bdac1be14c04853e0a7aeb647a7326239287add](https://github.com/magento/magento2/commit/7bdac1be14c04853e0a7aeb647a7326239287add)
 - [57ba467ded70e808c3d4ef0f878c646fa30c010f](https://github.com/magento/magento2/commit/57ba467ded70e808c3d4ef0f878c646fa30c010f)
 - [6bc7a61088132e7b6e36e2001c24b1e989e0caed](https://github.com/magento/magento2/commit/6bc7a61088132e7b6e36e2001c24b1e989e0caed)
 - [3b249553cb84eee58b92dd4521a9ef2d71daa07b](https://github.com/magento/magento2/commit/3b249553cb84eee58b92dd4521a9ef2d71daa07b)
 - [4fccb0c0d79166847ada42258c2122f7a36cf596](https://github.com/magento/magento2/commit/4fccb0c0d79166847ada42258c2122f7a36cf596)

The fix will be available with the upcoming 2.4.2 release.
