### ISSUE TITLE
Stabilize CMS Page asset links tests

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#30164]
### Preconditions (*)
Setup MFTF

### Steps to reproduce (*)
1. Create a PR removing skip from the following tests:
 - app/code/Magento/MediaGalleryCmsUi/Test/Mftf/Test/AdminMediaGalleryAssertUsedInLinkPagesGridTest.xml
 - app/code/Magento/MediaGalleryCmsUi/Test/Mftf/Test/AdminMediaGalleryCmsUiUsedInPagesFilterTest.xml
 - app/code/Magento/MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDisabledContentFilterTest.xml
2. Run Functional tests on the PR

### Expected result (*)
Test are passing locally and on PR builds

### Actual result (*)
Test are passing locally but failing on PR builds

Test reports:
http://10.234.147.14:8080/job/Functional-Tests-CE/3798/allure/#categories/92da55730d483ee0e1571a7fbbddf813/82f603f4a894fd19/
http://10.234.146.97:8080/job/Functional-Tests-CE/1183/allure/#categories/3d887810c4ddf7e837db7e3319f2ce90/798f573f1b84439b/

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37868` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your report. 
The issue has been fixed in magento/magento2#30069 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [a93e2e8dcee30fe7638728f9f1720619fc9c57d4](https://github.com/magento/magento2/commit/a93e2e8dcee30fe7638728f9f1720619fc9c57d4)
 - [3835116604b47ea851a5d6e2dd722085d5fe33f1](https://github.com/magento/magento2/commit/3835116604b47ea851a5d6e2dd722085d5fe33f1)
 - [89b550a1122d56e590ae2db575554aceed7fc7d6](https://github.com/magento/magento2/commit/89b550a1122d56e590ae2db575554aceed7fc7d6)
 - [34e32f0cdd0e210c7869702605d780e125f7e9c4](https://github.com/magento/magento2/commit/34e32f0cdd0e210c7869702605d780e125f7e9c4)
 - [0ba658f9d740abeccacca277fa4d47f19e907410](https://github.com/magento/magento2/commit/0ba658f9d740abeccacca277fa4d47f19e907410)
 - [1eaa4e25f35d52bd775db1180eb3a823f2f575f9](https://github.com/magento/magento2/commit/1eaa4e25f35d52bd775db1180eb3a823f2f575f9)
 - [5df1b7ed5f04dba49ca7bd53b252e8198f56ffa6](https://github.com/magento/magento2/commit/5df1b7ed5f04dba49ca7bd53b252e8198f56ffa6)
 - [64a2a38f9a7ddecb146265322c341a2c57c45e84](https://github.com/magento/magento2/commit/64a2a38f9a7ddecb146265322c341a2c57c45e84)
 - [69b43d7788940511838ffd366341af29c386993e](https://github.com/magento/magento2/commit/69b43d7788940511838ffd366341af29c386993e)
 - [2ce4e1e49ef49f8de0137faa9446b395a9026d13](https://github.com/magento/magento2/commit/2ce4e1e49ef49f8de0137faa9446b395a9026d13)
 - [9630367d68f42b599307bad37312c6e0519b49c0](https://github.com/magento/magento2/commit/9630367d68f42b599307bad37312c6e0519b49c0)
 - [f80005a95be0e746f89532ec0519f35a8fad2fe8](https://github.com/magento/magento2/commit/f80005a95be0e746f89532ec0519f35a8fad2fe8)
 - [915c776e02eba04c1505ce086702df45f0d6eb50](https://github.com/magento/magento2/commit/915c776e02eba04c1505ce086702df45f0d6eb50)
 - [999b239d4b4437ec639cbe7437b576dee4eec1a4](https://github.com/magento/magento2/commit/999b239d4b4437ec639cbe7437b576dee4eec1a4)

The fix will be available with the upcoming 2.4.2 release.
