### ISSUE TITLE
"The coupon code has been accepted." message remains after a Coupon Code was removed

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30255]
Preconditions
1. Create simple product  

2. Create Customer with address
* First Name: John
* Last Name: Doe
* Email Address: john.doe@example.com(use real mail)
* Company: Magento
* Address: 6161 West Centinela Avenue
* City: Culver City
* State/Province: California (CA)
* Zip/Postal Code: 90230
* Country: United States
* Telephone: 555-55-555-55
 
3. Go to Admin -> Marketing -> Cart Price Rules: click "Add New Rule"
* Fill all required fields 
  * "Coupon" select Specific Coupon
  * "Coupon Code" =  1111 
* In "Action" section 
  * "Apply" select "Percent of product price discount"
  * "Discount Amount" =  50
* click "Save" button 

Steps:
 1. Go to admin -> sales -order -> create new order -> select customer
 2. Add Products => simple product
 3. Apply Coupon Code => 1111
 4. remove Coupon Code
 
(/) Expected result
"The coupon code has been accepted." message should disappear

(x) Actual result
"The coupon code has been accepted." message is still  present

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37386

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37386` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment]
@magento I am working on this

**Comment by shikhamis11** [comment]
#dmcdindia2020

**Comment by gabrieldagama** [comment]
Hi @magento-engcom-team. Thank you for your report. 
The issue has been fixed in magento/magento2#30391 by @shikhamis11 in 2.4-develop branch
Related commit(s):
 - [f54561ea2ac52623695a91ea54bbd71b8f1fa101](https://github.com/magento/magento2/commit/f54561ea2ac52623695a91ea54bbd71b8f1fa101)
 - [16e962d30934ea24c653aff9e2407ebf01494085](https://github.com/magento/magento2/commit/16e962d30934ea24c653aff9e2407ebf01494085)
 - [9c09485387bc735f6f5efbddfd587de7759319cf](https://github.com/magento/magento2/commit/9c09485387bc735f6f5efbddfd587de7759319cf)
 - [1ee91ca2d9c6650c83f4b5f6abc1983fa1fef629](https://github.com/magento/magento2/commit/1ee91ca2d9c6650c83f4b5f6abc1983fa1fef629)
 - [15fdf8da649ec743c1bfc701f69ab73e113a5847](https://github.com/magento/magento2/commit/15fdf8da649ec743c1bfc701f69ab73e113a5847)
 - [2362ad9105f34e57f71e39072040e85a7620abfb](https://github.com/magento/magento2/commit/2362ad9105f34e57f71e39072040e85a7620abfb)
 - [28376be2f58bab6223629ab035defa9d7796ebe9](https://github.com/magento/magento2/commit/28376be2f58bab6223629ab035defa9d7796ebe9)
 - [d01145605e025745ba114b6cbc26d217d9988157](https://github.com/magento/magento2/commit/d01145605e025745ba114b6cbc26d217d9988157)

The fix will be available with the upcoming 2.4.2 release.
