### ISSUE TITLE
[Clone MC-35417]Radio buttons are not displayed in the “Payment & Shipping Information” section in the case of reorder by Admin

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30257]
**Preconditions:**
* Magento EE 2.3.6, EE 2.3.7-alpha2
* A Customer account with shipping address and a billing address is created
* A Simple Product is created
* Several delivery methods are configured
* At least one order is created

**Steps to Reproduce:**
* Go to Magento Admin panel > Sales > Orders
* Select the created order
* Click the “View” link
* Click the “Reorder” button
* Scroll down the page to the “Payment & Shipping Information” section
* Click the “Click to change shipping method”

**(/) Expected results:**

The list of delivery methods with radio buttons should appear
 ![image](https://user-images.githubusercontent.com/3409584/94735365-46702400-0330-11eb-85e9-ebfc71585ad0.png)

*(see the attached EE 2.4.1-alpha4. ADMIN REORDER RADIO BUTTONS EXPECTED.png)*

**(x) Actual results:**

The list of delivery methods without radio buttons appears
 ![image](https://user-images.githubusercontent.com/3409584/94735343-3c4e2580-0330-11eb-9104-bc3867459bc1.png)

*(see the attached  EE 2.4.1-alpha4. ADMIN REORDER RADIO BUTTONS ACTUAL.png*
                                   *EE 2.4.1-alpha4. ADMIN REORDER RADIO BUTTONS.mp4)*

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-37373

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37373` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AndreyChorniy** [comment]
@magento give me 2.4-develop instance

**Comment by AndreyChorniy** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Hi @magento-engcom-team. Thank you for your report. 
The issue has been fixed in magento/magento2#32393 by @gixid192 in 2.4-develop branch
Related commit(s):
 - [1be4239ba7f5fd512e6a51f386404883022ad513](https://github.com/magento/magento2/commit/1be4239ba7f5fd512e6a51f386404883022ad513)
 - [e40e45796a54e04ccf381d72a4d255bed98887e4](https://github.com/magento/magento2/commit/e40e45796a54e04ccf381d72a4d255bed98887e4)
 - [b54b8524d662f746453a406aecc9ad83ac79b711](https://github.com/magento/magento2/commit/b54b8524d662f746453a406aecc9ad83ac79b711)
 - [7dee9d8f64e3d05b0dee60dd7e7cad4620f5f2e6](https://github.com/magento/magento2/commit/7dee9d8f64e3d05b0dee60dd7e7cad4620f5f2e6)
 - [2821bc189bd7aefc877d25180bcc870044aa60fe](https://github.com/magento/magento2/commit/2821bc189bd7aefc877d25180bcc870044aa60fe)
 - [a57b22b86f51cf460030169c89fc592462dab89b](https://github.com/magento/magento2/commit/a57b22b86f51cf460030169c89fc592462dab89b)

The fix will be available with the upcoming 2.4.3 release.

**Comment by jellesiderius** [comment]
Patch fix can be done like this: https://magento.stackexchange.com/a/347147/7855
