### ISSUE TITLE
Unexpected loading of a Related Products grid

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30267]
**Preconditions:**
* Magento EE 2.3.5-p2, EE 2.4.0, EE 2.4.0-p1 is installed should be actule for CE
* At least 100 Simple products are created

**Steps to Reproduce:**
* Go to Magento Admin panel > Catalog > Products
* Select any of created Products
* Click “Edit” link
* Open “Related Products, Up-Sells, and Cross-Sells” section
* Click the “Add Related Products” button
* Select at least 100 products
* Click “Add Selected Products”
* Click “Save” button
* Open “Related Products, Up-Sells, and Cross-Sells” section
* Try to reach any page of the added Related Products, except the first and the last one, for example, page#2 (20 products/page)

**(/) Expected results:**

The page should be loaded

**(x) Actual results:**

The page is constantly loading

**(i) NOTE:** It seems, that the first and the last page are loading as expected. Only pages in-between that range are constantly loading

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36465

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36465` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by santhoshp** [comment]
@magento I am working on it

**Comment by santhoshp** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-36465` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
