### ISSUE TITLE
Placeholder for password on checkout is different for simple and other products

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30266]
**Preconditions:**
1. Magento EE 2.3.5-p2 or  EE 2.4.0-p1 is installed
1. There is registered Test Customer 
1. Test Simple Product is created
1. Other Test Product is created (Virtual for example)

**Steps to Reproduce:**
1. Go to Storefront as Guest user
1. Add 'test Simple Product' to Shopping Cart
1. Click 'Proceed to Checkout' button from mini-cart
1. On 'Shipping Address' Checkout step, fill 'Email Address' with address of existing Test Customer
1. Observe "Password" field placeholder
1. Repeat steps 1-5 but on step 2 add Virtual Product

**(/) Expected results:** Placeholders should be identical 

**(x) Actual results:** Placeholders are different.

![image](https://user-images.githubusercontent.com/3409584/94739576-cf8a5980-0336-11eb-9053-fdffd4f96e50.png)
![image](https://user-images.githubusercontent.com/3409584/94739584-d1ecb380-0336-11eb-90c4-ba5adab352c7.png)

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-36512

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36512` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vikalps4** [comment]
@magento I am working on this.

**Comment by vikalps4** [comment]
dmcdindia2020

**Comment by vikalps4** [comment]
#dmcdindia2020

**Comment by vikalps4** [comment]
@magento give me 2.4-develop instance

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-36512` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
