### ISSUE TITLE
2.4.0 Class Temando\Shipping\Model\Source\PackagingType does not exist

### ISSUE THREAD

**Issue by haxor211** [magento/magento2#30278]
I have ran the query in my database and removed 3 rows.. the problem still persists, what do I do?? I dont want to enable this useless module.

I also used the new module in 2.4.0 "Temando_ShippingRemover" and ran setup:upgrade, still doesnt work!!

I also tried deleting the attributes starting with "ts_%" in datatbase, this doesnt help either!!!!

The error "Exception #0 (ReflectionException): Class Temando\Shipping\Model\Source\PackagingType does not exist" is still here. Help me out please its driving me insane

_Originally posted by @haxor211 in https://github.com/magento/magento2/issues/25430#issuecomment-702097056_

**Comment by haxor211** [comment]
I have searched my whole database for entries like "*temando*" or "ts_*" nothing to be found... the biggest shock to me is that I have attributes such as "ts_dimensions_height" in my backend in attributes section, yet I cant find it anywhere in the database!!! 

Can someoone help me and tell me whats going on here with this shitty module?

**Comment by Genaker** [comment]
Magento 2 Core has a core issue. When the source model of the EAV class from the Database does not exist magento throws 

ReflectionException

Exception #0 (ReflectionException): Class "****\****\Model\Config\Source\***\Options" does not exist

```
/var/www/html/magento/vendor/magento/framework/Code/Reader/ClassReader.php

 public function getConstructor($className)
    {
        $class = new ReflectionClass($className); <-- Exception happens here 
```

however, it has logic to tell you exactly what attribute Model is missing

```
/var/www/html/magento/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php

public function getSource()
    {
        if (empty($this->_source)) {
            if (!$this->getSourceModel()) {
                $this->_source = $this->_getDefaultSourceModel();
            } else {
                $this->_source = $this->getSourceModel();
            }
        
            if (!$source) {
                throw new LocalizedException(
                    __(
                        'Source model "%1" not found for attribute "%2"',
                        $this->getSourceModel(),
                        $this->getAttributeCode()
                    )
                );
            }

```
 but this logic never happens because it is an Exception(ReflectionException) not a bool value 

you need to add this code and check exception

public function getSource()
    {
        if (empty($this->_source)) {
            if (!$this->getSourceModel()) {
                $this->_source = $this->_getDefaultSourceModel();
            } else {
                $this->_source = $this->getSourceModel();
            }
            try {
                $source = $this->_universalFactory->create($this->_source);
            } catch (\ReflectionException $e) {
                $source = false; 
            }
            if (!$source) {
                throw new LocalizedException(
                    __(
                        'Source model "%1" not found for attribute "%2"',
                        $this->getSourceModel(),
                        $this->getAttributeCode()
                    )
                );
            }

then an exception will be self-explained:

Exception #0 (Magento\Framework\Exception\LocalizedException): Source model "****\***\Model\Config\Source\***\Options" not found for attribute "some_attribute"

Please fix it ASAP.
