### ISSUE TITLE
Magento V2 Timezone Issue

### ISSUE THREAD

**Issue by forgeonline** [magento/magento2#3028]
While I was working on our current Magento 2 project I've found 
date_default_timezone_get()
is set to UTC. On my Model file
This gives me wrong Time ( 13 Hours late time )

date_default_timezone_get() value should be same as my time zone Pacific/Auckland

in public/app/bootstrap.php it is set to UTC
date_default_timezone_set('UTC'); 

This is causing different value in time. Can you please check this. Should I remove this timezone set in bootstrap.php

**Comment by forgeonline** [comment]
since value is set by date_default_timezone_set('UTC');

Any value set by ini_set('date.timezone', 'Pacific/Auckland');
is ignored

http://php.net/manual/en/function.date-default-timezone-get.php

Once I've removed  date_default_timezone_set('UTC'); from bootstrap.php it's working fine

**Comment by devdesco-ceo** [comment]
+1

**Comment by mazhalai** [comment]
@forgeonline @devdesco-ceo Can you please confirm this is on version 2.0?

**Comment by melnikovi** [comment]
It is best practice to operate on dates in application in UTC timezone and format in specific timezone when display. There are use cases when you need to represent the same date in different timezones. For instance, in multi-store setup Magento displays order creation date in timezone configured for a particular store on the frontend and in timezone from global config (admin timezone) in admin. There are also dates for which we don't do any conversion, for instance dates when the product is visible.

Magento\Framework\View\Element\AbstractBlock has formatDate and formatTime methods that you can use to format date according to the timezone of the store. Also take a look at Magento\Framework\Stdlib\DateTime\Timezone.

If you need to save date in database you can use TIMESTAMP type in database, see example in Magento\Customer\Setup\InstallSchema.

I hope this helps.

**Comment by forgeonline** [comment]
Yes this is version  2.0

**Comment by forgeonline** [comment]
Yes melnikovi I Agree, It's Ok to use UTC in General .

however UTC is overriding my Pacific/Auckland when I use date function in My Models, Themes etc. which is not acceptable on a software that have Timezone configuration in System Configuration.

Thanks

**Comment by melnikovi** [comment]
@forgeonline it actually gives more flexibility, because you don't rely on the timezone of your environment. Framework provides API to format date according to the timezone set in configuration. If you provide more details about your issue I can give you better example of how to use framework API to format date.

**Comment by forgeonline** [comment]
Yes it gives more flexibility if you are a programmer. 

Food for thoughts, What is the point of having a configuration in backend for Timezone configuration if it's not working correctly :)

**Comment by sIiiS** [comment]
+1 for remove it from bootstrap.php

**Comment by melnikovi** [comment]
In the backend you configure application, not infrastructure. Have you tried to use API provided by framework to format date?

Please explain reasons to make such change. Existing implementation provide easy way to achieve what you need and more flexible.

**Comment by forgeonline** [comment]
Yes existing implement is good for programmers.

I thinks it's best to change to so it's tide it to backend configruation.
For example: If I don't have any programming Knowlege I should be able to use correct timezone after I've Set my Timezone from backend.

Thanks
Nuwinda

**Comment by forgeonline** [comment]
Please add
date_default_timezone_set( ini_get('date.timezone') ); 
to bootstrap instead of UTC since most servers are Sync with there timezones. 

I'm working on a Booking system, I'm having difficulty of making a timezone changes. Since time is always calculate as UTC (Unless I change it in the Models, Helpers or controllers)

Thanks

**Comment by devdesco-ceo** [comment]
+1

```
date_default_timezone_set( ini_get('date.timezone') );
```

this worked perfectly!

**Comment by forgeonline** [comment]
No need to remove 

date_default_timezone_set('UTC');

All the Magento Date/Time functions based on UTC so Module developer has to Load Timezone functions and do the programming (Though it's time consuming )

Thanks

**Comment by ameliemelo1** [comment]
date_default_timezone_set( ini_get('date.timezone') );
can seriously damage cron jobs that are currently working fine. I don't think this is a viable solution.

**Comment by syed786hasan** [comment]
I am getting following error regarding time zone

Notice: date_default_timezone_set(): Timezone ID 'Pakistan Standard Time' is invalid in /home/storevb/public_html/app/code/DHL/DhlToolkit/Ui/Component/Listing/Column/Status.php on line 935

Please provide solution to get rid of this error

**Comment by netzwelt-nishu** [comment]
Hi, 
I am opening this issue, because i am still facing this problem in Magento 2.3.0. Can you guys please mention which workaround for you.                                                                   
              date_default_timezone_set( ini_get('date.timezone') );                                                                                 This above workaround doesn't work for me.  Please suggest me how can i solve my issue.

**Comment by jove4015** [comment]
I realize I'm commenting on an old issue but - the main reason I want to properly set the time zone is so that promotions set via special_price_from_date and to_date actually end at the correct time and not on UTC schedule.  We don't all live in England.

**Comment by MilenV** [comment]
Hello @jove4015 @mazhalai @viktor-zhuromskyy @melnikovi @forgeonline @FabianLauer @ameliemelo1 

We are experiencing strange issue on Production LIVE environment with Adobe Commerce ver. 2.4.5-p2
If you Go to Stores -> Configuration.
Make sure the Store View is set to: Default Config.
Go to General -> General.
Scroll down to Locale Options you will notice the timezone is GMT(Greenwich Mean Time Europe/London) which is identical on Staging and Production when compared manually.
![GMT](https://github.com/magento/magento2/assets/41599684/be6531ff-94a5-42d0-be95-caaa70ec9f47)
and  as per wiki https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/cart-rules/price-rule-cart-scheduled-changes.html?lang=en this below is how price rule cart scheduled changes were set.
![Content Magento Active Promo](https://github.com/magento/magento2/assets/41599684/530044fd-2db6-433a-9cb1-b4f452c16622)
Friday morning the UK better than black friday the Homepage was supposed to go live however it did not go live at the time it was scheduled to go live (10:00am). This was then manually updated. An hour later the homepage updated to to the template that was originally supposed to go live at 10:00 because of this I tested on the UK dummy page for the page to go live at 12:30 and found that the homepage updated an hour later at 1:30 meaning that the scheduling times were out by an hour. This issue is also not happening on staging. Other scheduling live banners and promo codes worked correctly. It seams to only be on happening on the live pages

This is how the Homepage scheduling was set up, this is how all homepages have been set up - I think that there could possibly be an issue regarding the timing of Magento in the back end. This is the only thing that i could possibly think could have caused this issue.

Regards,
Milen Velinov
