### ISSUE TITLE
Dynamic Block is present on Storefront even if Catalog/Cart Price rule is not active

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30308]
1. Go to Content > Dynamic Blocks
1. Fill out required field but Catalog/ Cart Price rule
1. Assign Dynamic Block to a widget to make it show up on Storefront (In widget option, select Specified Dynamic Block for field "Dynamic Blocks to Display")
1. Go to Storefront where created Dynamic Block suppose to display

(x) Actual result: Created Dynamic Block display on Storefront
 (/) Expected result: Dynamic Block only displays on Storefront when a catalog/cart price rule is active

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-5583

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-5583` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Surabhi-Cedcoss** [comment]
@magento give me 2.4-develop instance

**Comment by sdzhepa** [comment]
The related internal Jira ticket `MC-5583` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
