### ISSUE TITLE
3D secure Error with BrainTree CreditCard payment method

### ISSUE THREAD

**Issue by ajayceymox** [magento/magento2#30339]
In  Magento 2.3.4, enabled and configured the payment method BrainTree Credit Card with 3D secure and it shows the error "Please try other form of Payment ". It is working sandbox (with 3D secure) and production mode (without 3D secure). Any idea to solve the issue?

**Comment by Scarraban** [comment]
Identified a similar issue in 2.4.x - 3DS was failing on production but not sandbox.

We've isolated the issue to the AVS settings being a little too strict on production:
![image](https://user-images.githubusercontent.com/3777938/102078043-2c5bc300-3e02-11eb-8cd9-f229bf97ac64.png)

If set so that the address and postcode are required fields, the request returns with a "Postal code is required, Billing address is required" error from Braintree, but only with 3DS enabled.

A workaround for now is to turn off the above AVS checks, which resolves the error, but ideally these fields should be sent as part of a 3DS request.

**Comment by nicholasscottfish** [comment]
@ajayceymox Did you find a solution to this?

@Scarraban We were seeing the issue occur on our sandbox environment with all of the above settings disabled. When we looked at the console we could see it was failing on "Billing state format is invalid".

`
{name: "BraintreeError", code: "THREEDS_LOOKUP_VALIDATION_ERROR", message: "The data passed in `verifyCard` did not pass validation checks. See details for more info", type: "CUSTOMER", details: {…}}
code: "THREEDS_LOOKUP_VALIDATION_ERROR"
details:
originalError: i
code: "CLIENT_REQUEST_ERROR"
details:
httpStatus: 422
originalError:
error: {message: "Billing state format is invalid."}
threeDSecureInfo: {liabilityShifted: false, liabilityShiftPossible: false}
__proto__: Object
__proto__: Object
message: "There was a problem with your request."
name: "BraintreeError"
type: "NETWORK"
__proto__: Error
__proto__: Object
message: "The data passed in `verifyCard` did not pass validation checks. See details for more info"
name: "BraintreeError"
type: "CUSTOMER"
`

Apologies for the format of the above console log.

Strangely, if we were to leave the state field blank then the 3D Secure validation passes and we receive no error.

Has anybody else come across this issue?

**Comment by tarunpg** [comment]
@nicholasscottfish We are also seeing this issue on our Sandbox "Billing state format is invalid". I contacted Braintree and they informed that " in production a 2 or 3 digit billing state is required for 3DS 2. Otherwise, if a longer billing state is passed, the authentication will be downgraded to 3DS 1. Therefore, the validation error in Sandbox is intended to encourage merchants to pass a 2-3 digit  billing state in line with the 3DS 2 requirements." Based on this I think we need to find out if this change is being worked on by Paypal. 

Writing on Github for this first time - so apologize if any issues in the format.

**Comment by nicholasscottfish** [comment]
Thanks @tarunpg, this does appear to the issue. We had actually removed the state field via the Magento admin but are using the Fetchify extension for address lookup and this was filling in the hidden state field without us knowing; this then leads on to the issue you described above.

**Comment by chalov-anton** [comment]
Can we please reopen this issue?
