### ISSUE TITLE
[NOT READY] Missing "search" feature in Magento to support Omnisearch for Staging/Preview in AEM

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30470]
### Description

Omnisearch in AEM for staging/preview will not work because "search" for this purpose is not supported in Magento.
### Reference:

This is a snippet of the pending documentation from <https://devdocs.magedevteam.com/1532/guides/v2.3/graphql/queries/index.html#staging> (only reachable from inside Adobe Corp Net, and only for 14 days).
```java
The products query does not support full text search in the context of staging, because staged content is not indexed. Therefore, omit the search input attribute in your staging products queries.
```

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-38406

**Comment by gabrieldagama** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by herzog31** [comment]
As documented in [0], when sending a GraphQL request in staging mode via the `Preview-Version` header, the full-text search via the `search` parameter in the `products` GraphQL query does not work and returns an error. This is because staged product data is not indexed.

Goal of this issue is to enable full-text search for the `products` query, when querying staged product data.

[0] https://devdocs.magento.com/guides/v2.4/graphql/queries/index.html#staging
