### ISSUE TITLE
Magento2 import stock sources successful but no changes made and not showing in import history

### ISSUE THREAD

**Issue by cliddell97** [magento/magento2#30494]
### Preconditions (*)

1. Magento ver. 2.3.4

### Steps to reproduce (*)
1. Updating stock sources with csv columns and values:  

source_code,sku,status,quantity
default,144646,1,10.000

2. csv is in utf-8 encoding with no unusual characters.

### Expected result (*)
1. The import is done succesfully and 1 product stock has been updated
2. Import is registered in import_history table

### Actual result (*)
1. The import is done succesfully but update message is empty
2. No registry in import_history table
3. Product stock remains unchanged
![image](https://user-images.githubusercontent.com/62906960/96045245-efd61000-0e2e-11eb-9ce1-bdef24ccc122.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Bravo** [comment]
Hello @cliddell97 

Thank you for your report.

We have rechecked the reported issue on the latest 2.4-develop.
Exported a .csv file, edited the SKU, Quantity, Stock Status, and Imported the .csv file
The import success message is displayed with content, not empty, and there is a record in the `import_history` table in the database.
![msi](https://user-images.githubusercontent.com/51680745/106745452-cb927f00-6629-11eb-8cb4-4542a20abe20.png)

However, if you are updating the _source_code_, this might mean that the issue is related to the Inventory functionality.
Please, open the same issue in the appropriate https://github.com/magento/inventory/issues repository.
Thank you.
