### ISSUE TITLE
Magento shows message telling that article is not in storage for configurable product

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30512]
### Preconditions (*)

1. 2.4

### Steps to reproduce (*)

1. Create configurable product
2. Set Quantity to 0
2. add simple products
3. set Quantity of simple products to 1000
4. Try to configure the product in the frontend and buy it.

### Expected result (*)

1. Magento should let us buy the article, because the loaded simple article is in stock.

It should not make any diverence if the configurable products Quantity is 0 or >0. The configurable products task is to select a simple product by the configuration, so magento should only look at the Quantity of the simple product.

### Actual result (*)

1. Magento does not let us buy the article, even though the choosen simple product is in stock, but the
configurable product is not in stock (which should be completly ignored).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment]
Hi, @Eddcapone,
This issue is not reproduced in the Latest Magento 2.4 Instance.
As per your steps, actual result and the expected result I have verified this issue but Not able to verify it.
** Front End Attached screenshot **
![image](https://user-images.githubusercontent.com/24711761/96413138-d3f4b480-1208-11eb-8ef3-f17f0fcbe17b.png)

** Admin Section attached screenshot **
![image](https://user-images.githubusercontent.com/24711761/96413182-ecfd6580-1208-11eb-9d41-d6c855355e18.png)

![image](https://user-images.githubusercontent.com/24711761/96413196-f4247380-1208-11eb-95f1-eeadf499bb0e.png)

Thanks.

**Comment by Eddcapone** [comment]
I imported the products from Magento 1. I think the import messed with the data. I also can't fix it. When I try to change the QTY of the configurable product and save, then the value is not getting saved.

**Comment by ajijshekh123** [comment]
Right @Eddcapone, I think this is a Data Migration Issue. Please review it and update me if this issue Is fixed from your end so I will close the issue.

**Comment by ajijshekh123** [comment]
@Eddcapone - If you found this issue again you can reopen.
