### ISSUE TITLE
String as a key used, might be damaged accidentally. 

### ISSUE THREAD

**Issue by iaroslavglodov** [magento/magento2#30545]
https://github.com/magento/magento2/blob/32ed03cad4f2b2abc6ca6e5dc14885cd822c4508/app/code/Magento/Quote/Model/Quote/Address.php#L679

### Summary (*)
String key `'cached_items_all'` MUST be changed to `$key`, or even better with the predefined class constant `CACHE_KEY_ITEMS_ALL`.

**Comment by ejaz-alam** [comment]
@magento I am working on this

**Comment by magento-engcom-team** [comment]
Hi @iaroslavglodov. Thank you for your report. 
The issue has been fixed in magento/magento2#30579 by @ejaz-alam in 2.4-develop branch
Related commit(s):
 - [6970b19c234d752d2f4137580c877b37d96f77d5](https://github.com/magento/magento2/commit/6970b19c234d752d2f4137580c877b37d96f77d5)
 - [fd4a5a7cb63e2c712e03de61b820f92a47a33a2e](https://github.com/magento/magento2/commit/fd4a5a7cb63e2c712e03de61b820f92a47a33a2e)

The fix will be available with the upcoming 2.4.2 release.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39035` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
