### ISSUE TITLE
Can't place order on admin: "regionId" is required

### ISSUE THREAD

**Issue by kassner** [magento/magento2#30577]
### Preconditions

Magento 2.4-develop;
Magento 2.3.6;

2. Two websites;
3. Disable all countries for the default scope (General > Countries > Allow);
4. Enable `United States` on one website (General > Countries > Allow);

### Steps to reproduce

1. Go to Admin > Sales > Orders > Create order;
2. Select the website used on Preconditions step 4;
3. Add a product, fill the addresses using `United States` as country;
    Note that the region field is a text field instead of a dropdown with the states
4. Fill the payment method and shipping method and place the order;

### Expected result

1. Order is placed successfully;

### Actual result

1. Error `Please check the shipping address information. "regionId" is required. Enter and try again.` is shown and the order is not placed.

![Screenshot from 2020-10-21 15-11-51](https://user-images.githubusercontent.com/51679138/96719370-f8d85b80-13b1-11eb-9964-c43b6a063f8c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kassner** [comment]
@magento give me 2.4-develop instance

**Comment by kassner** [comment]
Reproducible on 2.4-develop:

![Screenshot from 2020-10-21 11-06-05](https://user-images.githubusercontent.com/301255/96698593-98372780-138d-11eb-9c66-df3772a492e3.png)

> Note the state is not a dropdown, but a text field.

![Screenshot from 2020-10-21 11-06-27](https://user-images.githubusercontent.com/301255/96698617-a08f6280-138d-11eb-9f35-10483df6dc34.png)

**Comment by kassner** [comment]
From my quick investigation, the `regionUpdater` within the page doesn't have any regions populated. The commit 2b4cfab52c7305521447c07e104afa4cec730a19 made some changes that makes it not render the countries when it's in the admin order create page. Likely the fix lies around `\Magento\Directory\Helper\Data::getRegionData` method being aware that it is in the admin order create oage and display the websites based on the selected website, instead of the one in the request object, as the `getCurrentScope` does.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38592` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bogutskyy** [comment]
@magento I am working on this

**Comment by bogutskyy** [comment]
@magento add to contributors team

**Comment by bogutskyy** [comment]
@magento I am working on this

**Comment by gabrieldagama** [comment]
Hi @kassner. Thank you for your report. 
The issue has been fixed in magento/magento2#30755 by @bogutskyy in 2.4-develop branch
Related commit(s):
 - [e8507dbb9ee99d419ff46e8fff99ab27bec9af2b](https://github.com/magento/magento2/commit/e8507dbb9ee99d419ff46e8fff99ab27bec9af2b)
 - [228cb684d982af6970c2248902a6a4c466eb01c7](https://github.com/magento/magento2/commit/228cb684d982af6970c2248902a6a4c466eb01c7)
 - [4e48a7abfa1c8f4dc711414992a06dcd7bef58d8](https://github.com/magento/magento2/commit/4e48a7abfa1c8f4dc711414992a06dcd7bef58d8)
 - [165a1c1ca943017ef0645a296f2339d39a62a7ac](https://github.com/magento/magento2/commit/165a1c1ca943017ef0645a296f2339d39a62a7ac)
 - [3bfc316509b59e863ab29eef578b4cf2f9d9f445](https://github.com/magento/magento2/commit/3bfc316509b59e863ab29eef578b4cf2f9d9f445)
 - [b611bae3532c7a16255f13f7ad5eabfb518eb838](https://github.com/magento/magento2/commit/b611bae3532c7a16255f13f7ad5eabfb518eb838)
 - [cbe1cd939ab81f17054974380f83989f44311db8](https://github.com/magento/magento2/commit/cbe1cd939ab81f17054974380f83989f44311db8)
 - [ef066add3c90f842ca7dd3e3c8e1c75cfc46d1e1](https://github.com/magento/magento2/commit/ef066add3c90f842ca7dd3e3c8e1c75cfc46d1e1)
 - [95bf7dce3f392d8ea40c96451af22f3789e2449e](https://github.com/magento/magento2/commit/95bf7dce3f392d8ea40c96451af22f3789e2449e)
 - [ee503112e228fd641ca5224bce4781c38bb0e2b3](https://github.com/magento/magento2/commit/ee503112e228fd641ca5224bce4781c38bb0e2b3)
 - [9e061d1edbcc79bcae814b2176117006fc0da46a](https://github.com/magento/magento2/commit/9e061d1edbcc79bcae814b2176117006fc0da46a)

The fix will be available with the upcoming 2.4.3 release.

**Comment by hussainbaig34** [comment]
Hi,

I just finished implementing Magento 2.4.2 on my website and I have migrated my website. During staging everything was great but in production things are not looking very good after cutover. In the last 2 days I have 71 orders declined do to this issue. For our website  which is located in Canada, this drop down issue is intermittent. I have been on a call with a customer trying to checkout and the Text Field changes back between being a drop down and a text field intermittently.

Even looking at the PayPal payflow gateway, it shows all the transactions that are being declined have a missing postal code.

I need urgent help with this. Is this something you guys can help me with?

Regards,
Hussain Baig

**Comment by ProxiBlue** [comment]
@hussainbaig34 

From the supplied link to the fix, you can create a diff, by adding .diff to the PR URL.

```
https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/30755.diff
```

You can apply the patch.

Most of that involves tests, so in a pinch, if you are using composer patching, below is the part that makes teh site work again:

```
diff --git a/Helper/Data.php b/Helper/Data.php
index 3133e3d4c195..b359989fe981 100644
--- aHelper/Data.php
+++ b/Helper/Data.php
@@ -13,6 +13,7 @@
 use Magento\Directory\Model\ResourceModel\Region\CollectionFactory;
 use Magento\Framework\App\Cache\Type\Config;
 use Magento\Framework\App\Config\ScopeConfigInterface;
+use Magento\Framework\App\Helper\AbstractHelper;
 use Magento\Framework\App\Helper\Context;
 use Magento\Framework\Json\Helper\Data as JsonData;
 use Magento\Store\Model\ScopeInterface;
@@ -25,8 +26,10 @@
  * @since 100.0.2
  * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
  */
-class Data extends \Magento\Framework\App\Helper\AbstractHelper
+class Data extends AbstractHelper
 {
+    private const STORE_ID = 'store_id';
+
     /**
      * Config value that lists ISO2 country codes which have optional Zip/Postal pre-configured
      */
@@ -424,6 +427,11 @@ private function getCurrentScope(): array
                 'type' => ScopeInterface::SCOPE_STORE,
                 'value' => $request->getParam(ScopeInterface::SCOPE_STORE),
             ];
+        } elseif ($request->getParam(self::STORE_ID)) {
+            $scope = [
+                'type' => ScopeInterface::SCOPE_STORE,
+                'value' => $request->getParam(self::STORE_ID),
+            ];
         }

         return $scope;
```

applied via composer patch :

```
"patches": {
            "magento/module-directory": {
                "Fix Region Issue": "patches/composer/region-id-directory-fix.diff"
            }
        }
```

**Comment by mokanfar** [comment]
Hello I would like to share my experience with this and a possible quirky solution that worked for me without patching code. 

This issue was reproducible on production but not on staging leading us to believe it was a data issue. **A simple opening and manual page save of the _Admin Stores->Configuration->General->General tab_ solved the issue for us.**
