### ISSUE TITLE
Frontend cookies HttpOnly flag is not set. PCI Compliance checking failed

### ISSUE THREAD

**Issue by tope316** [magento/magento2#30583]
### Preconditions (*)

1. Magento 2.3.5-p1
2. Use HTTP Only is set to Yes in Default Cookie Settings

### Steps to reproduce (*)

1. Open a page on a Magento 2 shop
2.

### Expected result (*)

1. Cookies should have HttpOnly set to true
2.

### Actual result (*)

1. Cookies HttpOnly are not set.
![image](https://user-images.githubusercontent.com/17076407/96723757-8ed7aa80-13e1-11eb-84d6-03fc3e3e973c.png)

### Additional information
from comment https://github.com/magento/magento2/issues/30583#issuecomment-715393691
> Attached is the detailed report for reference.
> [ASV_Report_2020-10-11 - PCI Compliance scan 10-12-20.pdf](https://github.com/magento/magento2/files/5430208/ASV_Report_2020-10-11.-.PCI.Compliance.scan.10-12-20.pdf)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @tope316,
The listed above cookies are used by JS, so they can't be https only.
I'm closing this issue as not relevant

**Comment by tope316** [comment]
Hi @ihor-sviziev, thanks for your reply. I reported this since our PCI Compliance checking detected these issues. So does this mean that the PCI Compliance checking report is not accurate?

**Comment by tope316** [comment]
Attached is the detailed report for reference.
[ASV_Report_2020-10-11 - PCI Compliance scan 10-12-20.pdf](https://github.com/magento/magento2/files/5430208/ASV_Report_2020-10-11.-.PCI.Compliance.scan.10-12-20.pdf)

**Comment by tope316** [comment]
Any progress on this issue?

**Comment by ihor-sviziev** [comment]
@engcom-Alfa @engcom-Bravo could you check this issue? Seems to me as really critical

**Comment by tope316** [comment]
Any news on this? I am getting concerned as we need to be compliant.

**Comment by gabrieldagama** [comment]
Hi @tope316 @ihor-sviziev 

I've done some investigation on this, and will share my thoughts, feel free to correct me. I believe this is not an issue, the HttpOnly flag is set for specific cookies, like your PHP session and other cookies that are relevant just for the server and for security reasons cannot be accessed by JS running on your browser.

I believe the goal with that configuration is not to have all the cookies with HttpOnly flag set, otherwise, our UiComponents that require access to some of those cookies won't work. 

Looking at your report, there are a couple of cookies that are not Magento related and few more that are, when this test was ran did you have https enable on all site? Because as for now I can see that the cookies mentioned as failed that are Magento related on your website now have the "Secure" flag set. 

And looking at the "Remediation" section, we have:

```
Secure flag must be set for Session Cookies for Application served over SSL.
For all Session cookies, HTTPOnly flag would limit session access in
cases of Cross-Site Scripting issues. Proper Caching headers should be
set for responses carrying the cookie.
```

You do seem to have the Secure flag on those cookies now, and, as for the Session cookies, the Magento related ones also seem to have the HttpOnly flag set.

Hope this helps. Please let me know your thoughts.

**Comment by tope316** [comment]
hi @gabrieldagama, thanks for your reply. If the setting of the HttpOnly flag is not an issue, does it mean the scan report is inaccurate?

**Comment by gabrieldagama** [comment]
@tope316 I can't say if it is accurate or not, but my thoughts are described above, that is why I asked if you had https enabled on the whole website when the tests were run, because one of the solutions for the problem is to have the security flag on those cookies.

**Comment by tope316** [comment]
@gabrieldagama - yes the entire site is using https.

**Comment by tope316** [comment]
So are you guys saying that the scan report should just ignore these cookies?

**Comment by leeclemens** [comment]
@tope316 I came across this after a similar result regarding the httpOnly flag on an XSRF cookie. Did you ever resolve this?

I submitted an Exception to my PCI ASV with similar reasoning as @gabrieldagama provided (e.g. not session/security, breaks JS functionality by design). I just wanted to leave this note and plan to follow up once my vendor responds for any future Internet travelers.

**Comment by leeclemens** [comment]
The ASV put my response as an Exception/False Positive and marked it Passed.

**Comment by gabrieldagama** [comment]
Hi @tope316 I will be closing this issue for now as it seems to not be a problem. Please feel free to reopen it and add more information. Thanks!

**Comment by hcsarah** [comment]
hello, can you please let me know how you managed to set secure flag for mage-messages cookie ?
