### ISSUE TITLE
Deploy stuck on compilation

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#30611]
### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. `rm -rf generated/*`
1. `bin/magento setup:di:compile`

### Expected result (*)

Finished compilation.

### Actual result (*)

Stuck compilation.

```
Compilation was started.
Interceptors generation... 4/7 [================>-----------]  57% 20 secs 267.0 MiB
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @Zyles,
Do you have this issue on the clean magento installation, without any custom modules installed? I believe some custom module might cause this issue.

**Comment by hostep** [comment]
If the issue is caused by a custom module, then there is potentially still a bug in Magento itself. I'm suspecting that some kind of endless loop is being triggered somehow, and the source of that could still lie in Magento's code being triggered by a specific way a custom module has been programmed.

So @Zyles: if you have found out more information and can boil the issue down to a specific module, it might still be interesting to figure out how this problem is being triggered.

**Comment by Zyles** [comment]
Solved it with using `bin/magento -vvvv setup:di:compile` in developer mode.
