### ISSUE TITLE
Blank theme partly not translateable on mobile

### ISSUE THREAD

**Issue by argovaerts** [magento/magento2#30707]
### Preconditions (*)

1. 2.4.0
2. 2.4-develop

### Steps to reproduce (*)

1. Clean install of Magento
2. Activate multiple storefront with another language than English
3. Category structure: Category -> Subcategory(1) -> Subcategory(2)

### Expected result (*)

1. On mobile, have (1) translated (including "All") or have it removed.

### Actual result (*)

1. Word 'All' is not translated
2. [Imgur](https://imgur.com/UZLpjdp)
![30707](https://user-images.githubusercontent.com/51681379/98035528-52fd0600-1e21-11eb-91ad-f768017f4c27.gif)

**Note:** Phrase `All,All,module,Magento_Catalog` or `All,All,module,Magento_CatalogSearch` are not translatable 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Rohaty** [comment]
Hi,
I have the same problem.

Magento 2.4.1

I can't translate the string 'All' from the subcategory on mobile menu. The file where the string appears is menu.js located on /lib /web/mage/

line 465:

.text ($. mage .__ ('All% 1'). replace ('% 1', category));

Even though I translate this string into German in the csv language (i18n directory):

All % 1, "Alle % 1", lib, lib/web/mage/menu.js

I still only get All instead of Alle.

But when I add this string in the js-translation.json file:
"All % 1": "Alle % 1",

so then the translation in the mobile menu is correct.

Where is the problem? Can this string get to js-translation.json directly at compile time?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38884` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
