### ISSUE TITLE
Strange block appearing at the top of page

### ISSUE THREAD

**Issue by redinn** [magento/magento2#3090]
Hi, I'm getting а weird issue when try to open one product ( Karissa V-Neck Tee ).
In order to reproduce this issue please do the following:
1. Navigate to Women-->Tops
2. Select any Size in layered navigation (XS or XL)
3. Open "Karissa V-Neck Tee" product

After that, I'm able to see additional block at the top:
![image](https://cloud.githubusercontent.com/assets/8018308/12531702/84334376-c212-11e5-8afc-abe140cd860c.png)

Could you please check it from yor side.

Thanks.

**Comment by tigerx7** [comment]
I ran into this same issue. It's happening because html tags are getting included in the META description. Whenever META description is empty, at some point in saving the product, the description automatically gets copied into META description but the html tags are not cleaned out thus creating the issue you see.

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2295
https://mage2.pro/t/161
https://github.com/magento/magento2/issues/1514

**Comment by vzabaznov** [comment]
@redinn bug was fixed and delivered to develop branch

**Comment by digitalredefined** [comment]
When will this be in release?  I d/led 2.0.9 and code was showing as pre-commit on MAGETWO-48511
