### ISSUE TITLE
Redundant header generated while add a product to grouped product

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#30911]
### Preconditions (*)
1. M2.3.x
2. M2.4.0

### Steps to reproduce (*)
1. Go Admin > Catalog > Products
2. Select Grouped Product from drop down of Add Product button
3. In new product page, at Attribute Set select, choose Top
4. Scroll down to tab Grouped Products and try add new product.
5. Got an issue [https://imgur.com/porq478](https://imgur.com/porq478)
6. Loom: https://www.loom.com/share/b28e534af9254eec99bf5fc4e77a0376

### Expected result (*)
1. [https://imgur.com/iIjvWuq](https://imgur.com/iIjvWuq)

### Actual result (*)
1. [https://imgur.com/porq478](https://imgur.com/porq478)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”.

**Comment by krishprakash** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39180` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment]
Verified:

![image](https://user-images.githubusercontent.com/46617848/99622346-ee13f380-2a4f-11eb-944a-6d9a6d51089c.png)

**Comment by saphaljha** [comment]
@magento I am working on this.

**Comment by magento-engcom-team** [comment]
Hi @kamui23. Thank you for your report. 
The issue has been fixed in magento/magento2#31142 by @saphaljha in 2.4-develop branch
Related commit(s):
 - [04eaa23cf6409e23ea8de6c2dbc1b1cd4f156e85](https://github.com/magento/magento2/commit/04eaa23cf6409e23ea8de6c2dbc1b1cd4f156e85)
 - [dc957fb58307cc6f5ec62bc93140d9036790ce18](https://github.com/magento/magento2/commit/dc957fb58307cc6f5ec62bc93140d9036790ce18)
 - [28d724da89cf761ed0c81ad6c1cb17fbac8e8f76](https://github.com/magento/magento2/commit/28d724da89cf761ed0c81ad6c1cb17fbac8e8f76)
 - [fac9b1f02909be994207946ab127ad0375750929](https://github.com/magento/magento2/commit/fac9b1f02909be994207946ab127ad0375750929)
 - [19c7e10ccb0b6b6f43dd7931394ca0156c756c8b](https://github.com/magento/magento2/commit/19c7e10ccb0b6b6f43dd7931394ca0156c756c8b)
 - [e8709e2c289bf38ea8eaa08e0a98c51501b99855](https://github.com/magento/magento2/commit/e8709e2c289bf38ea8eaa08e0a98c51501b99855)
 - [0fd760a44e1b75920691e2e4a4d3d714d353e977](https://github.com/magento/magento2/commit/0fd760a44e1b75920691e2e4a4d3d714d353e977)
 - [958582ee34a6734f101074d64680ad57f9f70f50](https://github.com/magento/magento2/commit/958582ee34a6734f101074d64680ad57f9f70f50)
 - [4bdc98ef49516d2a89dc7ff61df4bcee200007a5](https://github.com/magento/magento2/commit/4bdc98ef49516d2a89dc7ff61df4bcee200007a5)
 - [b4a14812aff90e5658a9cd6570ba0c2b66d29260](https://github.com/magento/magento2/commit/b4a14812aff90e5658a9cd6570ba0c2b66d29260)
 - [44ad22abca518cd6cc56f3b59b569aa88c1de882](https://github.com/magento/magento2/commit/44ad22abca518cd6cc56f3b59b569aa88c1de882)

The fix will be available with the upcoming 2.4.3 release.
