### ISSUE TITLE
[Cart Rule] Incorrect discount amount applied for bundle products containing more than one option

### ISSUE THREAD

**Issue by sky-hub** [magento/magento2#30952]
### Preconditions (*)

1. Magento 2.4 (probably older versions too)
2. Affects bundle products fixed cart discounts

Note: Because the `$availableDiscountAmount` is set to zero after processing the first item the other items will not have any discount applied.

### Steps to reproduce (*)

1. Install Magento 2.4 with sample data
2. Create cart rule with fixed discount amount for whole cart (Ex: 50$)
3. Add a bundle product to cart (Example: http://local.magento2.com/sprite-yoga-companion-kit.html)
4. Navigate to checkout/cart page and check discount. 

### Expected result (*)

1. Cart discount should be 50$
![image](https://user-images.githubusercontent.com/3511966/99402835-75e3eb80-28f2-11eb-980b-eb02ea78fa51.png)

### Actual result (*)

1. Cart discount is 18.85$
![image](https://user-images.githubusercontent.com/3511966/99402746-5a78e080-28f2-11eb-8161-6eb565df58dc.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Fixed in: #30953

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @eduard13 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39158` were created

**Issue Available**: @eduard13, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment]
Hi @sky-hub. Thank you for your report. 
The issue has been fixed in magento/magento2#30953 by @sky-hub in 2.4-develop branch
Related commit(s):
 - [d56db5bed6424e94fb70ae116eb89360465d1762](https://github.com/magento/magento2/commit/d56db5bed6424e94fb70ae116eb89360465d1762)
 - [4d1e4eafc8a5554d4114e2d892b0ecd99402a5b3](https://github.com/magento/magento2/commit/4d1e4eafc8a5554d4114e2d892b0ecd99402a5b3)
 - [12806e0f33d748247436320a74ee6e9e1f6ac1d0](https://github.com/magento/magento2/commit/12806e0f33d748247436320a74ee6e9e1f6ac1d0)
 - [b4275c9bc6a9852186205814417730182abf6f27](https://github.com/magento/magento2/commit/b4275c9bc6a9852186205814417730182abf6f27)
 - [aa7e7cd0aa8dd4ecd0d551c38d610cde38d9733c](https://github.com/magento/magento2/commit/aa7e7cd0aa8dd4ecd0d551c38d610cde38d9733c)
 - [a24dc14ee22db5b8c3877679b45f02ebf7306ba6](https://github.com/magento/magento2/commit/a24dc14ee22db5b8c3877679b45f02ebf7306ba6)
 - [963b28f999b0b9e822ae89fa39dec664d8b3cada](https://github.com/magento/magento2/commit/963b28f999b0b9e822ae89fa39dec664d8b3cada)
 - [cfb8f02d82a150c9c17314f99408e987dcee028d](https://github.com/magento/magento2/commit/cfb8f02d82a150c9c17314f99408e987dcee028d)
 - [6015adaf1aa278f71fa190abd902ec1f7f85aa21](https://github.com/magento/magento2/commit/6015adaf1aa278f71fa190abd902ec1f7f85aa21)
 - [eeda660e3453709af3631b71935fcf7753afc260](https://github.com/magento/magento2/commit/eeda660e3453709af3631b71935fcf7753afc260)
 - [47149bf7cc434576f38bf0d4f5edb4baa9026578](https://github.com/magento/magento2/commit/47149bf7cc434576f38bf0d4f5edb4baa9026578)
 - [15bc12cfcd2b9888d036ef0c16744753e6a23b46](https://github.com/magento/magento2/commit/15bc12cfcd2b9888d036ef0c16744753e6a23b46)

The fix will be available with the upcoming 2.4.3 release.

**Comment by skeutmeier** [comment]
I still experience this in 2.4.6-p1
