### ISSUE TITLE
Please enter a valid URL. Protocol (http://, https://) is required.

### ISSUE THREAD

**Issue by diegoyane** [magento/magento2#31044]
I have an issue on my custom module in Magento ver. 2.3.2-p2. 

This issue appears when I put the url api on the box "API Endpoint". 

Things to know:

- The API works well I already tested on Postman

- The API user and the API toker also are correct. 

Im adding the configuration on the custome module. 

![Issue report](https://user-images.githubusercontent.com/74992149/100156949-6a06a500-2e6f-11eb-96db-0638ac9ab53b.png)

**Comment by engcom-Alfa** [comment]
Hi @diegoyane . Thank you for your report. Your issue is connected with your custom module.

The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.
