### ISSUE TITLE
Issue with Zero Checkout Subtotal Magento2.4 

### ISSUE THREAD

**Issue by ajaysingh-webkul** [magento/magento2#31046]
**Magento version**
Magento2.4.1

**Step To Reproduce**

1 Please Set Zero Subtotal checkout new order status to Processing ( https://imgur.com/a/mrJQyTN )
2.create a virtual Product with Price 0
3.then add to cart that product and place an order with a total of 0
4. then check order status in admin orders grid ( https://imgur.com/a/syfqkkX )

**Actual Result:-**
Order Status is closed
**Expected Result:-**
Order Status Should be Processing

**Comment by ajijshekh123** [comment]
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment]
Hi @ajaysingh-webkul,
I have verified this issue as per your steps to be reproduced, actual result and expected result.
Currently, After placing the order with Zero Subtotal amount, It is showing "Complete" order status instead of "Processing" order status.

**Admin Configuration screenshot:**

![image](https://user-images.githubusercontent.com/24711761/100193622-29b03100-2f1a-11eb-8bc9-fab4e33744a0.png)

**Order List status:**

![image](https://user-images.githubusercontent.com/24711761/100193644-346ac600-2f1a-11eb-9355-13e243a85548.png)

**Expected result:**

Order status should be "**Processing**" instead of "**Complete**".

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39355` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by RakeshJesadiya** [comment]
@magento I am working on this.

**Comment by sdzhepa** [comment]
@RakeshJesadiya  
At first glance, it looks like the expected result in the case with "virtual product"
I assume that for simple product(any product that can be shipped) it will work as described

i will investigate and provide more details

**Comment by RakeshJesadiya** [comment]
@sdzhepa Yes, I have modified the logic for the Virtual product with Zero subtotal checkout.
For the Physical products, It will be worked as expected.
Only issue with Virtual product is that, once you place an order with zero subtotal, and you have made setting `**New Order Status**` as **Processing** that time, after place an order, order status will be closed instead of complete.

But If you go with default setting of Zero Checkout method with **New Order Status** as **Pending**, Add products and try to place an order, after successfully placed an order, Order status will be Complete. This is the right scenario.

**Issue exists for the Virtual product only if you have made New Order Status as Processing from the Stores -> Configuration**

I have create a PR to resolved the issue.

**Comment by magento-engcom-team** [comment]
Hi @ajaysingh-webkul, @sdzhepa, @RakeshJesadiya. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39355` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
