### ISSUE TITLE
Multiple Security Vulnerabilities reported by Lighthouse in 2.4.1 JQuery and JQuery-Ui

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#31146]
### Preconditions (*)

1. Deploy 2.4.1

### Steps to reproduce (*)

1. Using Google Chrome as Browser
2. Launch Dev tools and go to Lighthouse Tab
3. Analyse the 2.4.1 homepage
4. View the "Trust and Safety" section in "Best Practices"

### Expected result (*)

1. There should be no security Vulnerabilities found

### Actual result (*)

1. Lighthouse reports several, including one high security vulnerability.

![image](https://user-images.githubusercontent.com/30697781/100995114-3ef71200-354f-11eb-8319-562e633ec908.png)

Search of source code and google didn't bring up much for the following in relation to Magento

CVE-2020-11022
CVE-2020-11023
CVE-2019-11358
CVE-2019-5428
CVE-2015-9251
CVE-2017-16012
CVE-2016-7103

I see @DanielRuf has produced some patches for a subset of these. Have these made it into core?????

Attached another screenshot that shows the issue is reproducible.
![image](https://user-images.githubusercontent.com/51679138/121352437-7d301c80-c94a-11eb-9b66-b51bff78d579.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DanielRuf** [comment]
> I see @DanielRuf has produced some patches for a subset of these. Have these made it into core?????

Yes, afaik.
Lighthouse does only a simple version check and does not check the code of the jQuery files. So basically this is a false positive.

**Comment by DanielRuf** [comment]
These are covered by https://github.com/DanielRuf/snyk-js-jquery-565129:

CVE-2020-11022
CVE-2020-11023
CVE-2019-11358
CVE-2019-5428

https://github.com/DanielRuf/snyk-js-jquery-565129/blob/master/jquery-1.12.4.patch

As you can see at https://github.com/magento/magento2/pull/22418/files my PR only covered the prototype pollution part. Not sure fi the others landed there too. Changing the already modified minified file is not that easy.

Afaik I did not add it there because it's mostly a breaking change as you can read here regarding the html filter: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251 is basically a breaking change as you can not set/change the dataType without further side-effects.

See also https://github.com/jquery/jquery/pull/2588#issuecomment-146855997 and especially https://github.com/jquery/jquery/issues/2432#issuecomment-403761229

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16012 was rejected as this is a duplicate of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-7103 affects only jQuery before 1.12.0. My own patches address only the last versions of each major jQuery version.

Magento uses jQuery 1.12.4 as you can see in your screenshot and in the code at https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery/jquery.min.js#L1 and https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery.js#L2

**Comment by DanielRuf** [comment]
These are covered by https://github.com/DanielRuf/snyk-js-jquery-565129:

CVE-2020-11022
CVE-2020-11023
CVE-2019-11358
CVE-2019-5428

https://github.com/DanielRuf/snyk-js-jquery-565129/blob/master/jquery-1.12.4.patch

As you can see at https://github.com/magento/magento2/pull/22418/files my PR only covered the prototype pollution part. Not sure if the others landed there too, this is probably not the case. Changing the already modified minified file is not that easy.

Afaik I did not add it there because it's mostly a breaking change as you can read here regarding the html filter: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251 is basically a breaking change as you can not set/change the dataType without further side-effects.

See also https://github.com/jquery/jquery/pull/2588#issuecomment-146855997 and especially https://github.com/jquery/jquery/issues/2432#issuecomment-403761229

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16012 was rejected as this is a duplicate of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-7103 affects only jQuery before 1.12.0. My own patches address only the last versions of each major jQuery version.

Magento uses jQuery 1.12.4 as you can see in your screenshot and in the code at https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery/jquery.min.js#L1 and https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery.js#L2

**Comment by DanielRuf** [comment]
These are covered by https://github.com/DanielRuf/snyk-js-jquery-565129:

CVE-2020-11022
CVE-2020-11023
CVE-2019-11358
(CVE-2019-5428 - rejected as duplicate)

These are covered by https://github.com/DanielRuf/snyk-js-jquery-174006:

CVE-2019-11358
(CVE-2019-5428 - rejected as duplicate)

https://github.com/DanielRuf/snyk-js-jquery-565129/blob/master/jquery-1.12.4.patch

As you can see at https://github.com/magento/magento2/pull/22418/files my PR only covered the prototype pollution part. Not sure if the others landed there too, this is probably not the case. Changing the already modified minified file is not that easy.

Afaik I did not add it there because it's mostly a breaking change as you can read here regarding the html filter: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251 is basically a breaking change as you can not set/change the dataType without further side-effects.

See also https://github.com/jquery/jquery/pull/2588#issuecomment-146855997 and especially https://github.com/jquery/jquery/issues/2432#issuecomment-403761229

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16012 was rejected as this is a duplicate of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-7103 affects only jQuery before 1.12.0. My own patches address only the last versions of each major jQuery version.

Magento uses jQuery 1.12.4 as you can see in your screenshot and in the code at https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery/jquery.min.js#L1 and https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery.js#L2

**Comment by DanielRuf** [comment]
These are covered by https://github.com/DanielRuf/snyk-js-jquery-565129:

CVE-2020-11022
CVE-2020-11023
CVE-2019-11358
(CVE-2019-5428 - rejected as duplicate)

These are covered by https://github.com/DanielRuf/snyk-js-jquery-174006:

CVE-2019-11358
(CVE-2019-5428 - rejected as duplicate)

https://github.com/DanielRuf/snyk-js-jquery-565129/blob/master/jquery-1.12.4.patch

As you can see at https://github.com/magento/magento2/pull/22418/files my PR only covered the prototype pollution part. Not sure if the others landed there too, this is probably not the case. Changing the already modified minified file is not that easy.

Afaik I did not add it there because it's mostly a breaking change as you can read here regarding the html filter: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251 is basically a breaking change as you can not set/change the dataType without further side-effects.

See also https://github.com/jquery/jquery/pull/2588#issuecomment-146855997 and especially https://github.com/jquery/jquery/issues/2432#issuecomment-403761229

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16012 was rejected as this is a duplicate of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-7103 affects only jQuery before 1.12.0. My own patches address only the latest releases of each major jQuery version.

Magento uses jQuery 1.12.4 as you can see in your screenshot and in the code at https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery/jquery.min.js#L1 and https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery.js#L2

**Comment by DanielRuf** [comment]
These are covered by https://github.com/DanielRuf/snyk-js-jquery-565129:

CVE-2020-11022
CVE-2020-11023
CVE-2019-11358
(CVE-2019-5428 - rejected as duplicate)

These are covered by https://github.com/DanielRuf/snyk-js-jquery-174006:

CVE-2019-11358
(CVE-2019-5428 - rejected as duplicate)

https://github.com/DanielRuf/snyk-js-jquery-565129/blob/master/jquery-1.12.4.patch

As you can see at https://github.com/magento/magento2/pull/22418/files my PR only covered the Prototype Pollution vulnerability. Not sure if the others landed there too, this is probably not the case. Changing the already modified minified file is not that easy.

Afaik I did not add it there because it's mostly a breaking change as you can read here regarding the html filter: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251 is basically a breaking change as you can not set/change the dataType without further side-effects.

See also https://github.com/jquery/jquery/pull/2588#issuecomment-146855997 and especially https://github.com/jquery/jquery/issues/2432#issuecomment-403761229

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16012 was rejected as this is a duplicate of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-7103 affects only jQuery before 1.12.0. My own patches address only the latest releases of each major jQuery version.

Magento uses jQuery 1.12.4 as you can see in your screenshot and in the code at https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery/jquery.min.js#L1 and https://github.com/magento/magento2/blob/2.4.1/lib/web/jquery.js#L2

**Comment by jinnko** [comment]
I'm trying to determine whether the patches introduced in https://github.com/DanielRuf/snyk-js-jquery-565129 and https://github.com/DanielRuf/snyk-js-jquery-174006 have made it into Magento 2.3.6.  How can this be confirmed?

**Comment by gwharton** [comment]
In the absence of anyone else piping up, you could do a code analysis comparing the patches to the Magento code, and post the results here. 😁

**Comment by DanielRuf** [comment]
> As you can see at [#22418 (files)](https://github.com/magento/magento2/pull/22418/files) my PR only covered the Prototype Pollution vulnerability. Not sure if the others landed there too, this is probably not the case.

@jinnko

**Comment by gwharton** [comment]
Someone should target a breaking requirejs/knockout/jQuery update for 2.5-develop and get it over and done with.

**Comment by DanielRuf** [comment]
> Someone should target a breaking requirejs/knockout/jQuery update for 2.5-develop and get it over and done with.

Afaik there are PRs to migrate to jQuery 3 and remove jQuery migrate. So they are already working on this and this is planned for the near future. Makes not much sense to introduce breaking changes now with the patches. As mentioned most of these patches will produce more problems than they solve and the risk is relatively low for the unpatched issues (at least so far).

**Comment by ankurAuriga** [comment]
@DanielRuf - After applying patch 1.12.4 from https://github.com/DanielRuf/snyk-js-jquery-565129 in Magento 2.2.11, mini cart is stopped working. It does not show any content.

**Comment by DanielRuf** [comment]
@Anahitmartirosyan please do not simply apply the patch. The supplied jQuery version is already patched.

Also please see the previous comments about the exact parts, which are applied. Not all parts of the patches are applied in Magento.

**Comment by DanielRuf** [comment]
@Anahitmartirosyan please do not simply apply the patch. The supplied jQuery version is already patched.

Also please see the previous comments about the exact parts, which are applied. Not all parts of the patches are applied in Magento.

Check your browser console for any errors.

**Comment by DanielRuf** [comment]
> As you can see at [#22418 (files)](https://github.com/magento/magento2/pull/22418/files) my PR only covered the Prototype Pollution vulnerability. Not sure if the others landed there too, this is probably not the case. Changing the already modified minified file is not that easy.
> 
> Afaik I did not add it there because it's mostly a breaking change as you can read here regarding the html filter: [blog.jquery.com/2020/04/10/jquery-3-5-0-released](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/)

**Comment by DanielRuf** [comment]
@Anahitmartirosyan please do not simply apply the patch. The supplied jQuery version is already patched.

Also please see the previous comments about the exact parts, which are applied. Not all parts of the patches are applied in Magento.

Check your browser console for any errors.

Please carefully read https://github.com/magento/magento2/issues/31146#issuecomment-738112151.

> As you can see at [#22418 (files)](https://github.com/magento/magento2/pull/22418/files) my PR only covered the Prototype Pollution vulnerability. Not sure if the others landed there too, this is probably not the case. Changing the already modified minified file is not that easy.
> 
> Afaik I did not add it there because it's mostly a breaking change as you can read here regarding the html filter: [blog.jquery.com/2020/04/10/jquery-3-5-0-released](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/)

**Comment by keyurshah070** [comment]
@DanielRuf all are false positive? or any specific one?

**Comment by keyur-shah-accenture** [comment]
@DanielRuf  as from your [PR](https://github.com/magento/magento2/pull/22418) it looks like it is covered CVE-2019-11358 but not all of them,

**Comment by keyurshah070** [comment]
@DanielRuf as from your PR it looks like it is covered CVE-2019-11358 but not all of them,

**Comment by keyurshah070** [comment]
thanks for the response @DanielRuf , as you mention Magento is planning to move in jQuery 3 , so do you know any plans for when it can happen? or any time-line?

**Comment by DanielRuf** [comment]
No, I do not how the current plans are. I'm not that involved (anymore). Please ask the Magento product team regarding the plans to upgrade jQuery.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42607` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jefduarte** [comment]
Good afternoon, 
We are currently experiencing this issue as well with our report provided by Qualys that the Magento JQuery UI is outdated and has vulnerabilities.  Looking at comments, want to know the status of this internal ticket: MC-42607 or if this is going to be solved in a near future release.
Thanks

**Comment by ashumisra** [comment]
Hi, 
We are facing same issue, can you please share release version for internal ticket: MC-42607
Thanks

**Comment by iiagolima** [comment]
Hello!

Is there any updates here? Could not find the PR for it.

**Comment by ksenia-zlotin** [comment]
I have applied the CVE-2020-11022 patch provided in https://github.com/DanielRuf/snyk-js-jquery-565129/blob/master/jquery-1.12.4.patch onto a clean Magento 2.4.3-p1 install and experienced errors within the admin:
For example, the price input does not render in the add / edit product form within the admin, making it not possible to save a product properly.
<img width="1601" alt="Screen Shot 2022-05-25 at 12 32 43 PM" src="https://user-images.githubusercontent.com/62074773/170315403-8532ac3f-9678-47b4-8ce6-a18e6c1117d3.png">

Is there any way to implement the security patch for this vulnerability without experiencing such breakage?

**Comment by DanielRuf** [comment]
@ksenia-zlotin you don't need this patch. I had already patched the relevant parts in the provided jQuery version. Please see https://github.com/magento/magento2/issues/31146#issuecomment-776013505 and https://github.com/magento/magento2/issues/31146#issuecomment-738112151 including previous comments by me.

The security scanners report false positives since they only look at the (unchanged) version number. They can not know what is patched.
