### ISSUE TITLE
General error: 1836 Running in read-only mode, query was: SELECT GET_LOCK(?, ?)

### ISSUE THREAD

**Issue by rvitaliy** [magento/magento2#31145]
### Preconditions (*)

1. PHP v7.4.13
2. magento EE 2.4.1
3. aws aurora cluster  Engine version 5.7.mysql_aurora.2.08.21 Writer & Reader

### Steps to reproduce (*)
configure app/etc/env.php
```
'db' => [
        'connection' => [
            'default' => [
                'host' => DATABASE_HOST,
                'dbname' => DATABASE_NAME,
                'username' => DATABASE_USERNAME,
                'password' => DATABASE_PASSWORD,
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8;',
                'active' => '1',
            ],
        ],
        'slave_connection' => [
            'default' => [
                'host' => DATABASE_READ_ONLY_HOST,
                'dbname' => DATABASE_READ_ONLY_NAME,
                'username' => DATABASE_READ_ONLY_USERNAME
                'password' => DATABASE_READ_ONLY_PASSWORD,
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8;',
                'active' => '1',
            ],
        ],
        'table_prefix' => '',
    ],
```
open admin pannel, so magento.local/admin > login > pannel page

### Expected result (*)
No errors!

### Actual result (*)
`General error: 1836 Running in read-only mode, query was: SELECT GET_LOCK(?, ?)`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

This bug does not allow us to exploit read-only instance of aws aurora cluster.
Most likely it can also be reproduced on other types of clusters.

Can you help me solve this problem?
Thanks!

**Comment by sven-codeculture** [comment]
I can confirm this as we have the same problem.

**Comment by anoop-corra** [comment]
We are also facing the same issue with identical configuration  , Is there any work around for this issue apart from disabling the reader configuration in env.php ?

php 7.4.13
magento EE 2.4.1
Aws aurora cluster5.7.mysql_aurora.2.09.1

**Comment by ikevinsolomon** [comment]
I too can confirm that we are facing this issue on Aurora can someone please provide inputs :)

**Comment by sodhancha** [comment]
@rvitaliy any resolution from your side which you've figured out ?

**Comment by rvitaliy** [comment]
@sodhancha rollback configuration. :cry: 
I hope Magento's developers solve this problem. :rocket:

**Comment by sodhancha** [comment]
@rvitaliy **Master->Slave** concept is fundamentally different to **Writer->Reader** Configuration.
I dont think @magento-devops has any support for **Writer->Reader** type of Configuration.

**Comment by rvitaliy** [comment]
@sodhancha yes, without results.

**Comment by sodhancha** [comment]
@rvitaliy i've opened this issue on my ticket list with Magento Commerce Support as well.

**Comment by sodhancha** [comment]
Magneto Support Reply:
_This issue will not be fixed as it is reproduced with AWS aurora replicas only.

It is not reproducible with 2.4-develop/mysql 8.0 and replica with innodb_read_only or super_read_only ON.
With this being the case, it is recommended to switch lock provider from db to zookeeper, or file._

**Comment by gianstraf** [comment]
Hi all, 
we have the same problem of @rvitaliy and @sodhancha on AWS aurora replicas with:

- php 7.4.6
- Magento CE ver. 2.4.2

I report our analisys if can be useful to the problem fix.

It seems that the problem is caused by two wrong injected dependencies, for the class `Magento\Framework\Cache\LockGuardedCacheLoader` and member `locker`.

The member locker is of declared as **LockManagerInterface** and resolved with the proxy class `Magento\Framework\Lock\Proxy`. 
This proxy istances the right lock strategy using `Magento\Framework\Lock\LockBackendFactory`, which reads the configuration and should instances in our case a Magento\Framework\Lock\Backend\FileLock.

But, the lock `Magento\Framework\Lock\Backend\Database` is used anyway:
- on the frontend
- into Magento admin panel.

We found (seems) two possible wrong concrete implementations for the member `Magento\Framework\Cache\LockGuardedCacheLoader::locker`, in these files:

app/etc/di.xml
  ```
<type name="Magento\Framework\Cache\LockGuardedCacheLoader">
        <arguments>
            <argument name="locker" xsi:type="object">Magento\Framework\Lock\Backend\Database</argument>
        </arguments>
    </type>

```

vendor/magento/module-config/etc/di.xml
```
<virtualType name="systemConfigQueryLocker" type="Magento\Framework\Cache\LockGuardedCacheLoader">
        <arguments>
            <argument name="locker" xsi:type="object">Magento\Framework\Lock\Backend\Database</argument>
        </arguments>
    </virtualType>
```

These declarations force the use of `Magento\Framework\Lock\Backend\Database` bypassing the `LockManagerInterface` instanciation based on proxy.
The down side is that the database lock, has done on slave connection causing the error _General error: 1836 Running in read-only mode, query was: SELECT GET_LOCK(?, ?)_

If we change `Magento\Framework\Lock\Backend\Database` with `Magento\Framework\Lock\LockManagerInterface`, all come back to work properly.

**Comment by marshallthornton** [comment]
For anyone looking to still use DB locks while using Aurora DB replicas, we made a quick fix on our side to make sure all lock related queries get directed to the master DB. In `Magento\ResourceConnections\DB\Adapter\Pdo\MysqlProxy::isReadOnlyQuery` we adjusted the return condition to the following:
```
return 
!in_array($startSql, $this->writeQueryPrefixes) &&
!in_array($startSql, $this->_ddlRoutines) &&
strpos(strtolower($sqlMessage[1]), '_lock(') === false;
```
Adding that 3rd condition catches all lock related queries (GET_LOCK, RELEASE_LOCK, and IS_USED_LOCK) that we found being called in the Magento code and causes the `Magento\ResourceConnections\DB\Adapter\Pdo\MysqlProxy::selectConnection` function to avoid using the slave connection for these queries.

Once we applied this everything started working normally again and we weren't getting any errors about these lock related functions hitting the reader database(s) anymore.

**Comment by sodhancha** [comment]
@amansrivastava @rvitaliy @sven-codeculture @ikevinsolomon did you guys try out  @marshallthornton 's solution ?
Did it work for you guys ?

**Comment by salman231** [comment]
I've tried @marshallthornton solution on 2.4 EE and still getting these errors!! , Anyone fixed it yet ?

**Comment by francescosalvi** [comment]
gotta love the bot noise in this thread

**Comment by engcom-Hotel** [comment]
Hello @rvitaliy,

Thanks for posting the issue!

Please tell us if this issue occurs while using aurora or it can be reproducible by using any master-slave replica.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @rvitaliy,

We have tried to reproduce the issue in Magento 2.4-develop branch with the EE module installed on Aurora cluster DB. But for us, the issue is not reproducible. 

We have followed the exact same steps as mentioned in the main description. There might a case that the issue is already been addressed and fixed in the current development branch. We request you to please try to reproduce the issue in the latest development branch i.e. 2.4-develop branch.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @rvitaliy,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
