### ISSUE TITLE
Update Magento Coding Standard to version 6

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31152]
A new version 6 of Magento Coding Standard is available: https://github.com/magento/magento-coding-standard/releases/tag/v6

The composer.lock file should be updated to switch to the new version

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your report. 
The issue has been fixed in magento/magento2#31151 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [55926f83b5517b4acf989b20029830187e4df8ca](https://github.com/magento/magento2/commit/55926f83b5517b4acf989b20029830187e4df8ca)

The fix will be available with the upcoming 2.4.3 release.
