### ISSUE TITLE
MSI - Source Notify Qty and Notify Qty Below not working as expected

### ISSUE THREAD

**Issue by DiegoSana** [magento/magento2#31329]
### Preconditions (*)

Im trying to configure **Notify Qty Below** by source on product edit page.
Theres no problem, but the salable qty at stock level, is not the expected one.

1. Magento 2.4.1
2. MSI enabled
3. Sample data

### Steps to reproduce (*)

1. Create a **test_source**
2. Simple product with **manage_stock**=yes 
3. Global **Out-of-Stock Threshold**=10
4. Define a **qty**=100 for the product source
5. Backorders not allowed
6. Define a **notify qty**=5 with **use default** = no
![Screenshot - 2020-12-17T151852 265](https://user-images.githubusercontent.com/4226282/102526979-39cfb200-407b-11eb-8e67-d7b49aed4909.png)

### Expected result (*)

1. **Salable qty** at stock level => 100 - 5 - 10 = 85
![Screenshot (99)](https://user-images.githubusercontent.com/4226282/102527082-6388d900-407b-11eb-9c47-4726a8c3db41.png)

### Actual result (*)

1. **Salable qty** at stock level => 100 - 10 = 90

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DiegoSana** [comment]
@magento give me 2.4.1 instance

**Comment by DiegoSana** [comment]
Here is the evidence taken from the provided magento instance...

![Screenshot - 2020-12-17T161719 470](https://user-images.githubusercontent.com/4226282/102532857-5e2f8c80-4083-11eb-8145-ecf573fe3ada.png)
![Screenshot - 2020-12-17T161707 397](https://user-images.githubusercontent.com/4226282/102532873-64256d80-4083-11eb-8706-fb44eb25e23b.png)
![Screenshot - 2020-12-17T161648 951](https://user-images.githubusercontent.com/4226282/102532874-64be0400-4083-11eb-9223-1a6444723d86.png)

**Comment by DiegoSana** [comment]
@magento give me 2.4-develop instance

**Comment by DiegoSana** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hello @DiegoSana 

Thank you for your report.

The formula for the Salable Quantity is (Quantity - (Out-of-Stock Threshold)). :point_right: https://docs.magento.com/user-guide/catalog/inventory-backorders.html#out-of-stock-threshold
The **Notify for Quantity Below** is a setting that sends an email notification when a product’s quantity reaches a low quantity and is not deducted from the Salable Quantity. :point_right: https://docs.magento.com/user-guide/catalog/inventory-backorders.html#notify-for-quantity-below

This is the expected behavior. 

We are closing this issue. Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by DiegoSana** [comment]
@engcom-Bravo i understud. Thanks for your reply!
But, what about with this part of the documentation?
https://devdocs.magento.com/guides/v2.4/inventory/#a-simple-scenario

It's a little bit confusing...
