### ISSUE TITLE
Visual Swatch not showing on product page when once set as Text Swatch

### ISSUE THREAD

**Issue by Pakkapao** [magento/magento2#3139]
Hi,
It happended when changing Swatch type between Text Swatch and Visual Swatch back and forth.

`Text Swatch -> Visual Swatch` OR `Visual Swatch -> Text Swatch -> Visual Swatch`

`Magento 2.0.1 / PHP 7.0.2`
1. Create product attribute and product template as usual.
   ![1](https://cloud.githubusercontent.com/assets/11070293/12576991/2d388a38-c44a-11e5-887f-db40b9a01cff.png)
   ![2](https://cloud.githubusercontent.com/assets/11070293/12576996/336188ec-c44a-11e5-964f-7edd1c175ee5.png)
2. Create Configurable product
   ![3](https://cloud.githubusercontent.com/assets/11070293/12577001/41469434-c44a-11e5-9b05-346a5bae6ad9.png)
3. Visual Swatch is displaying on product page.
   ![4](https://cloud.githubusercontent.com/assets/11070293/12577023/645c2d62-c44a-11e5-9f2f-86d193517f37.png)
4. Now changing from Visual Swatch to Text Swatch
   ![9](https://cloud.githubusercontent.com/assets/11070293/12577229/a4506b58-c44b-11e5-9ce1-9721bada87ce.png)
5. Now Text Swatch is displaying on product page
   ![6](https://cloud.githubusercontent.com/assets/11070293/12577094/ca4e023a-c44a-11e5-9517-c9580a90ae78.png)
6. Change Swatch type back to Visual Swatch
   ![7](https://cloud.githubusercontent.com/assets/11070293/12577112/ed4cc154-c44a-11e5-9c2a-14a8a00023cc.png)
7. Text Swatch is showing instead of Visual Swatch!
   ![6](https://cloud.githubusercontent.com/assets/11070293/12577134/1152d46c-c44b-11e5-87a9-cafa78c670c5.png)

Thanks,

**Comment by AVoskoboinikov** [comment]
Hi, @Pakkapao 

Thanks for reporting this issue, I have created ticket in our internal JIRA to fix it (MAGETWO-57766). This issue will be closed after fix.

**Comment by soncp** [comment]
Hello, did you fixed this issue?

**Comment by soncp** [comment]
hello, 
Is there any update on this one?

**Comment by joshdoehla** [comment]
+1
I've had to recreate configurable products multiple times because of this issue. 
(Currently running multiple instances of 2.1.2)

**Comment by phucdh57** [comment]
Hi, I've not fixed in logic code of Magento Swatches, but I found in eav_attribute_option_swatch table
which like as below
+-----------+-----------+----------+------+---------+
| swatch_id | option_id | store_id | type | value   |
+-----------+-----------+----------+------+---------+
|        11 |         9 |        0 |    1 | #000000 |
|        12 |        10 |        0 |    1 | #ff05ff |
|        13 |        11 |        0 |    1 | #33ff24 |
|        14 |        12 |        0 |    1 | #ff6600 |
|        15 |        13 |        0 |    1 | #ffffff |
|        16 |        14 |        0 |    1 | #fbff00 |
|        17 |        15 |        0 |    1 | #f20000 |
|        18 |        16 |        0 |    1 | #ababab |
|        19 |         9 |        1 |    0 | Black    |
|        20 |        10 |        1 |    0 | Purple  |
|        21 |        11 |        1 |    0 | Green   |
|        22 |        12 |        1 |    0 | Orange  |
|        23 |        13 |        1 |    0 | White   |
|        24 |        14 |        1 |    0 | Yellow  |
|        25 |        15 |        1 |    0 | Red     |
|        26 |        16 |        1 |    0 | Gray    |
+-----------+-----------+----------+------+---------+
I changed field "value" from Black, Purple ... Gray to NULL and the issue seems to be solved.
Note: option_id is same to the option_id in eav_attribute_option  so, you can check which is in a same pair. Before we have a patch for this issue I hope that my tip can be helpful for others.
(My current magento version is 2.1.2)

**Comment by ghost** [comment]
This is still an issue in 2.1.7.

**Comment by magento-engcom-team** [comment]
@Pakkapao, thank you for your report.
We've created internal ticket(s) MAGETWO-57766 to track progress on the issue.

**Comment by basselalaraaj** [comment]
I found out that the issue is caused because only store_id '0' is getting the right type '1', the rest of the store_id's are still on type '0', if u adjusted that to '1', it works again.

From
<img width="967" alt="schermafbeelding 2018-02-06 om 08 17 09" src="https://user-images.githubusercontent.com/5745279/35846294-61066ec4-0b16-11e8-9144-0c868ef1e062.png">

To:
<img width="847" alt="schermafbeelding 2018-02-06 om 08 16 42" src="https://user-images.githubusercontent.com/5745279/35846302-68a8f91c-0b16-11e8-9f89-8580a7c128d4.png">

**Comment by mmularski** [comment]
#WroCD :)

**Comment by mmularski** [comment]
#WroCD :)

**Comment by magento-engcom-team** [comment]
@mmularski thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by udayankoliya** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@udayankoliya thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by dasharath-wagento** [comment]
I am working on this at #dmcdindia

**Comment by udayankoliya** [comment]
me and @dasharath-wagento  both are checked as per given step by @Pakkapao to produce this issue but we can't  reproduce it in Magento 2.2

**Comment by magento-engcom-team** [comment]
@Pakkapao we are closing this now due to inactivity. Additionally, @udayankoliya reported that issue is no more reproducible.

Thanks
