### ISSUE TITLE
Saving Products in a Category doesnt work if bulk is selected

### ISSUE THREAD

**Issue by samc2810** [magento/magento2#31486]
### Preconditions (*)

1. Magento 2.4.1 Commerce (dont know about the previous versions)
2. Cloud installation with B2B-Module installed
3. Smile_ElasticSuite is also installed

### Steps to reproduce (*)

1. Go to the category management in the admin panel and select a category
2. Filter the desired products and select all
![image](https://user-images.githubusercontent.com/1092318/103310933-3217f200-4a19-11eb-8c56-ef6dd12eace7.png)

### Expected result (*)

1. all the products are saved in the category

### Actual result (*)

1. Error in Backend
![image](https://user-images.githubusercontent.com/1092318/103311001-6e4b5280-4a19-11eb-9231-8245e77c0b94.png)
2. Error-Log 
![image](https://user-images.githubusercontent.com/1092318/103311175-ef0a4e80-4a19-11eb-80e9-c3a73c1d513f.png)
3. Because the JSON sent via POST contains an ID "on" 
![image](https://user-images.githubusercontent.com/1092318/103311265-2547ce00-4a1a-11eb-8ebc-66a46aad9162.png)

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Bravo** [comment]
Hello @samc2810 

Thank you for your report.

We have rechecked the reported issue on 2.4-develop CE and 2.4-develop EE versions.
Our steps:
1. Go to _Catalog - Category_, select any Category containing products
2. Click **Products in Category**
3. Select **Any**. Also tested with **Yes** and **No** values
4. Type a SKU name into SKU_ field and hit the Enter key to use the search
5. Click **Select All** checkbox
6. Click **Save** category

Actual Result:
:heavy_check_mark: Category is successfully saved
Please see the attachment
![Peek 2020-12-30 14-23](https://user-images.githubusercontent.com/51680745/103351341-9f746300-4aab-11eb-9de1-3d47349c5cad.gif)

Please, correct our steps or add some additional details in order to help us to reproduce the issue and provide a solution for it.

Thank you

**Comment by sedax90** [comment]
I've the same problem, log say: 

`"caused_by":{"type":"number_format_exception","reason":"For input string: \"on\""}}}]},"status":400} []
`
The problem is in the passed products:
```

{
                  \"terms\" : {
                    \"entity_id\" : [
                      \"187663\",
                      \"187664\",
                      \"187665\",
                      \"187666\",
                      \"187668\",
                      \"187669\",
                      \"187670\",
                      \"187671\",
                      \"187672\",
                      \"187673\",
                      \"187674\",
                      \"187675\",
                      \"187676\",
                      \"187677\",
                      \"187678\",
                      \"187679\",
                      \"187680\",
                      \"187681\",
                      \"187682\",
                      \"187683\",
                      \"on\"
                    ],
                    \"boost\" : 1.0
                  }
                }
```

**Comment by engcom-Bravo** [comment]
Hello @sedax90, are you also experiencing this issue on Magento 2.4.1 ?
Thank you
