### ISSUE TITLE
Magento 2.4.1 In-Store Delivery causes checkout to permanent hang with Error is email.js:165 Uncaught TypeError: Cannot read property 'check' of undefined at UiClass.validateEmail (email.js:165)

### ISSUE THREAD

**Issue by InternetAdvertisingSolutions** [magento/magento2#31576]
Summary of the issue,

Magento 2.4.1 In-Store Delivery causes checkout to permanent hang when an existing customer enters their password.
Checkout Page hangs with loading circle
Error is email.js:165 Uncaught TypeError: **Cannot read property 'check' of undefined**
    at UiClass.validateEmail **(email.js:165)**

### Preconditions (*)
1. Magento CE 2.4.1
2. Ubuntu 20.04
3. MySQL8
4. Apache2
5. php7.4
6. ElasticSearch 7.6
7. Setup up Click-and-Collect as per Magento Instructions (Add source, assign stock, In-Store Pickup Delivery = enabled

### Steps to reproduce (*)
1. Do not log in as a customer
2. Add an item to basket
3. Go to checkout page
4. Enter email address for existing customer
5. Password field appears
6. Enter password is entered
7. Click Login

### Expected result (*)

1. Customers saved Delivery Address is shown and options of Delivery Methods including In-Stock Pickup should display underneath.

![GitHub-ClickandCollect1](https://user-images.githubusercontent.com/40262043/103817033-db846680-505d-11eb-9f0e-0cbf8cc9d27c.png)

### Actual result (*)

1. Screen goes white with Loading circle and hangs permanently
2. email.js:165 Uncaught TypeError: **Cannot read property 'check' of undefined**
    at UiClass.validateEmail **(email.js:165)**
    at UiClass.emailHasChanged (email.js:90)
    at setNested (objects.js:43)
    at Object.nested (objects.js:117)
    at UiClass.set (element.js:305)
    at updateValue (links.js:80)
    at Function.notifySubscribers (knockout.js:1320)
    at Function.valueHasMutated (knockout.js:1538)
    at UiClass.observable [as email] (knockout.js:1504)
    at setNested (objects.js:43)
3. I know nothing about js but if it helps, /vendor/magento/module-checkout/view/frontend/web/js/view/form/elementEmail.js:165 line is 
            **return validator.check(usernameSelector);**

![GitHub-ClickandCollect2](https://user-images.githubusercontent.com/40262043/103817051-e3dca180-505d-11eb-89eb-9f759fcd5ac7.png)

Thank You.

**Comment by mrtuvn** [comment]
@magento give me  2.4.1 instance

**Comment by mrtuvn** [comment]
lol

**Comment by engcom-Bravo** [comment]
Hello @InternetAdvertisingSolutions 

Thank you for your report.

MSI related issues should be reported into a separate [Inventory](https://github.com/magento/inventory/issues) repository.
Can you please open a separate issue in https://github.com/magento/inventory/issues ?

Thank you in advance

**Comment by InternetAdvertisingSolutions** [comment]
Thanks.  Have done as requested and opened it here... https://github.com/magento/inventory/issues/3260

**Comment by torhoehn** [comment]
@magento give me 2.4-develop instance

**Comment by SmokinX** [comment]
Well, starting to really dislike everything about Magento... after a day of troubleshooting and searching for answers.
What most strikes me is threads like this: you have an issue and you'd like to report it. But then then 'the internet cops' show up and demand you do this and that and such and so. Terrible. Instead of pissing people of, make yourself usefull and try it yourself.

Now, to business: above is correct, though, not hanging indefinitely, but for a very long period.
So glad I got to this point... because I ran into another bug... which cost me several hours. I'm just gonna tell it here, to get it of my chest.

When you turn on In-Store Delivery and leave the title blank in the same options, the checkout page hangs indefinitely.
It's a bug. It's terrible. And it makes me wonder if things ever got tested.

So tell me. How should I know? Where to find out? Which logs?
Everything in this system is made to NOT WORK for dummies. Even the documentation (just referring to Pickup in store for now) is not complete. Not telling that you need to setup a source and stock location. Now wonder what a simple store-owner would know about store-locations and sources? Nothing. So those were not configured. Think about it: I want to give my customers an options to pick up in store without hassle, with no costs. How simple could/should that be? But you made a system that is impossible to setup so people like me just can't figure it out!

Pfew, I'm just glad I got this typed down. See you all on the flip-side.
