### ISSUE TITLE
The included sample file fails the import test??

### ISSUE THREAD

**Issue by lukas-jifu** [magento/magento2#31587]
### Preconditions (*)

1. Magento ver. 2.3.5-p1
2. Chrome / Windows 10

### Steps to reproduce (*)

1. Logged into magento as Admin.
2. Menu click to System > Import
3. Click "Download Sample File" and download
4. Open, make NO changes, and save Sample File as UTF-8 CSV
5. Set "Entity Type > Products"
6. Set "Import Behavior > Add/Update"
7. Use defaults for the rest.
8. Click "Choose File" and select the Sample File from above
9. Click on "Check Data"
10. Check fails, due to product type > simple
11. WHAT? Your own sample file fails the import check?

### Expected result (*)

1. Expected the sample file to correctly import so we can verify it's working

### Actual result (*)

1. Error message below:
Checked rows: 6, checked entities: 6, invalid rows: 3, total errors: 3
Following Error(s) has been occurred during importing process:
Only the first 100 errors are shown. Download full report
Value for 'product_type' attribute contains incorrect value, see acceptable values on settings specified for Admin in row(s): 1, 2, 3

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Pavel-Fekete** [comment]
Not reproducible on the latest 2.4-develop, sample file is proceed validation without errors.
![Import](https://user-images.githubusercontent.com/67371013/104003322-ea2c6400-51aa-11eb-8c34-6bb849e9eea6.png)

**Comment by engcom-Bravo** [comment]
Hello @lukas-jifu 

Thank you for your report.

We have rechecked the reported issue on the latest 2.4-develop and we do not have enough information to reproduce it.
Can you please share more details?
- What settings are set in your text editor on step _Open, make NO changes, and save Sample File as UTF-8 CSV_ ?
![Selection_030](https://user-images.githubusercontent.com/51680745/104013471-261af580-51ba-11eb-843c-c58a57f594d3.png)
- If possible, please share the exported .csv file

Thank you in Advance

**Comment by lukas-jifu** [comment]
Our platform is Magento ver. 2.3.5-p1

UTF CSV Catalog file attached. Importing products, "Check Data" fails.

**Comment by engcom-Bravo** [comment]
@lukas-jifu We have tried to import the provided .csv into our 2.4-develop instance and did not face any errors
The validation passed successfully :heavy_check_mark: 
![validation_result](https://user-images.githubusercontent.com/51680745/105034184-d366f680-5a61-11eb-8555-f73fae6aeec9.png)

And the products are imported
![success_import](https://user-images.githubusercontent.com/51680745/105034298-f09bc500-5a61-11eb-8c21-21f7d5078ccd.png)

Seems like the issue has already been fixed in 2.4-develop. 

In your case, I can offer you a temporary solution. Please try to empty the `product_type` column and try to Import
![product_type](https://user-images.githubusercontent.com/51680745/105034534-47090380-5a62-11eb-934d-07784fa26bb9.png)

We have to close this issue as it is not reproducible on 2.4-develop.Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
