### ISSUE TITLE
Image details cannot be updated in new media gallery when JS Minificaiton is enabled

### ISSUE THREAD

**Issue by thomas-kl1** [magento/magento2#31633]
### Preconditions (*)
1. Magento 2.4-develop
2. M2.4.*
3. Enable built-in JS Minification (production mode) ( `bin/magento config:set dev/js/minify_files 1` )
4. DIsable old media gallery ( Stores -> Configuration -> System -> Media Gallery and set **Enable Old Media Gallery** to **No**)

### Steps to reproduce (*)
1. Go to Admin -> Catalog -> Categories -> Content -> Select from Gallery
2. Open the context menu for any image (3 dots) and select "Edit"
3. Enter image title, description, add keywords
4. Click "Save"

### Expected result (*)
Image details are saved

### Actual result (*)
Image details are not saved. `Uncaught TypeError: Cannot read property 'call' of undefined` in jquery.validate

There are JS console errors when media gallery is opened:
`Uncaught SyntaxError: Invalid regular expression: missing /` validate-image-title.min.js:1 
`Uncaught SyntaxError: Invalid regular expression: missing /` validate-image-description.min.js:1 

![Screenshot from 2021-01-13 12-53-12](https://user-images.githubusercontent.com/51679138/104447625-b7b4a980-55a4-11eb-9f59-2911bb8864b0.png)

Before/After Minification of the regex:

`/^[a-zA-Z0-9\-\_\.\,\n\ ]+$|^$/i.test(value);`
`/^[a-zA-Z0-9\-\_\.\,\]+$/i.test(value);`

Space and new line are escaped and not recognized as part of the regex. Also regarding the JSShrink issues, it looks like there plenty of issues with regex, isn't any other working library? https://github.com/tedious/JShrink/issues

---

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40400` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by webkul-ajaysaini** [comment]
@magento give me 2.4-develop instance

**Comment by sivaschenko** [comment]
Updated description with the actual functional issue description. Increased priority to P2.

**Comment by gabrieldagama** [comment]
Hi @thomas-kl1. Thank you for your report. 
The issue has been fixed in magento/magento2#32398 by @gixid192 in 2.4-develop branch
Related commit(s):
 - [1be4239ba7f5fd512e6a51f386404883022ad513](https://github.com/magento/magento2/commit/1be4239ba7f5fd512e6a51f386404883022ad513)
 - [e40e45796a54e04ccf381d72a4d255bed98887e4](https://github.com/magento/magento2/commit/e40e45796a54e04ccf381d72a4d255bed98887e4)
 - [b54b8524d662f746453a406aecc9ad83ac79b711](https://github.com/magento/magento2/commit/b54b8524d662f746453a406aecc9ad83ac79b711)
 - [7dee9d8f64e3d05b0dee60dd7e7cad4620f5f2e6](https://github.com/magento/magento2/commit/7dee9d8f64e3d05b0dee60dd7e7cad4620f5f2e6)
 - [2821bc189bd7aefc877d25180bcc870044aa60fe](https://github.com/magento/magento2/commit/2821bc189bd7aefc877d25180bcc870044aa60fe)
 - [2f7b55d5769d48957369d9f2643319bb698f18dc](https://github.com/magento/magento2/commit/2f7b55d5769d48957369d9f2643319bb698f18dc)
 - [bff0f37834f5ff091d891d467d6a573532d769b5](https://github.com/magento/magento2/commit/bff0f37834f5ff091d891d467d6a573532d769b5)

The fix will be available with the upcoming 2.4.3 release.

**Comment by ia-gaurav** [comment]
can it be pulled via some patch
