### ISSUE TITLE
Update ramsey/uuid dependency to PHP 8 compatible version

### ISSUE THREAD

**Issue by sivaschenko** [magento/magento2#31777]
In scope of the user story MC-41383 we need to 

Update ramsey/uuid dependency to PHP 8 compatible version (Branch dev-master is compatible with PHP 8 but not released yet)

In scope of this spice we need to estimate the effort required to do this upgrade.

**Comment by sergeynezbritskiy** [comment]
@magento I am working on this

**Comment by sergeynezbritskiy** [comment]
Currently updating this dependency is impossible due to magento2-functional-testing-framework which locks some dependencies.
Actually it locks ": "allure-framework/allure-php-api" at version "1.1.8", and this version of allure-php-api requires  "ramsey/uuid": "^3.0".
We need to update magento2-functional-testing-framework composer.lock file first. Here is the PR to mftf repo https://github.com/magento/magento2-functional-testing-framework/pull/814
Waiting for this PR to be merged and released
cc: @sivaschenko

**Comment by sivaschenko** [comment]
@sergeynezbritskiy MFTF PR was merged, this task in now unblocked

**Comment by ihor-sviziev** [comment]
I added WIP PR with a description of all dependencies.
So far we have 2 dependencies that block updating this package:
- allure-framework/allure-phpunit 
- magento/magento2-functional-testing-framework

**Comment by ihor-sviziev** [comment]
@sivaschenko why it was closed?

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @ihor-sviziev, @sergeynezbritskiy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41383` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @ihor-sviziev, @sergeynezbritskiy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41383` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by sivaschenko** [comment]
It looks like an incorrect synchronization with the internal jira. We'll take a look at it.

Anyway, the changes are merged to 2.4-develop. Thank you @ihor-sviziev !

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, @ihor-sviziev, @sergeynezbritskiy. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39648` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.
