### ISSUE TITLE
Category filter IN doesn't work in graphQL.

### ISSUE THREAD

**Issue by PedroChagasGuerra** [magento/magento2#31812]
Steps to reproduce:
Create 2 categories, and add some products into.
Try to search with graphql for products filtering by category and put 2 categorys.

### Preconditions (*)
1. Sample data installed
2. Graphql

### Steps to reproduce (*)
1. Using this query try to search for your products:
`query {
  products(filter: { category_id: { in: ["ID", "ID"] } }) {
    total_count
    items {
      sku
      name
    }
  }
}
`
*Change "ID" by your category id.

### Expected result (*)
1. All available products should return.

### Actual result (*)
1- It returns just the products from the last category in filter array.

**Comment by engcom-Bravo** [comment]
Hello @PedroChagasGuerra 

Thank you for your report

We have rechecked the reported issue on the latest 2.4-develop.
We have created two Categories and added two products to each
![4products](https://user-images.githubusercontent.com/51680745/105697608-6e058080-5f0d-11eb-8e2e-a05da258d629.png)
![4products](https://user-images.githubusercontent.com/51680745/105697622-72ca3480-5f0d-11eb-9ecb-17ec8e09ec6f.png)

The GraphQL query
```graphql
query {
  products(filter: { category_id: { in: ["3", "4"] } }) {
    total_count
    items {
      sku
      name
    }
  }
}
```
returned all 4 products
```graphql
{
  "data": {
    "products": {
      "total_count": 4,
      "items": [
        {
          "sku": "Product 2 from Category 2",
          "name": "Product 2 from Category 2"
        },
        {
          "sku": "Product 1 from Category 2",
          "name": "Product 1 from Category 2"
        },
        {
          "sku": "Product 2 from Category 1",
          "name": "Product 2 from Category 1"
        },
        {
          "sku": "Product1 from Category1",
          "name": "Product1 from Category1"
        }
      ]
    }
  }
}
```
![gql_query](https://user-images.githubusercontent.com/51680745/105697834-bb81ed80-5f0d-11eb-93cb-4b2b716ee6f3.png)

The reported issue has already been fixed in this PR https://github.com/magento/magento2/pull/30375

We are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
