### ISSUE TITLE
Authorize Net issue on the admin order creation page

### ISSUE THREAD

**Issue by bineet-kumar** [magento/magento2#31834]
**Preconditions (*)**

1. Install Magento 2.3.2
2. Enable a few shipping methods, more than 1 method should be available in your store
3. Configure Authorize Net setting, only this payment should be available in your store

**Steps to reproduce (*)**

1. Go to the admin area
2. Start the order creation process: choose customer and products
3. Choose one of the shipping methods (few methods must be available on this page)
4. Put credit card data information in the payment form (only the Authorize.Net method should be available on this page)
5. Click the "Create order" button

**Expected result (*)**

1. Order created successfully

**Actual result (*)**

1. Order not created, I got the following error message: "Transaction has been declined. Please try again later."

Additionally, when I put cc info again here - order was created successfully (I copy-paste the same cc data).

https://user-images.githubusercontent.com/1344077/62035656-51499900-b201-11e9-91fc-f965e367fe10.gif

**Comment by engcom-Alfa** [comment]
Hello @bineet-kumar 

Thank you for your report and collaboration!

Unfortunately, we are closing this Issue report because we are not able to process contribution to the `2.3.x` release line through this public repository. See details [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)

And starting from `2.4.0` release, code related to this payment was removed/deprecated from Magento code-base:
[Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.

[Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445)

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
