### ISSUE TITLE
ProductRepository $saveOptions

### ISSUE THREAD

**Issue by Quazz** [magento/magento2#31870]
### Preconditions (*)

1. 2.4.1 (possibly earlier versions too)

### Steps to reproduce (*)

1. [ProductRepositoryInterface](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Api/ProductRepositoryInterface.php#L26) defines $saveOptions as a bool which mandates [ProductRepository](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ProductRepository.php#L516) to use it. 
2. [ConfigurableProduct ProductRepositorySave Plugin](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php#L58) does not return $saveOptions back to ProductRepository. 

### Expected result (*)

1. The plugin returns the same arguments back to the function it plugs in to regardless of whether those arguments get used. 

### Actual result (*)

1. The plugin returns only the product object in an array, the $saveOptions get ommitted. 

### Additional Information (*)
As per the [documentation](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html), If there are any arguments, the method should return an array of those arguments. But here it is not returning the `$saveOptions` variable.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ * ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Since $saveOptions are not used by the save function, this does not cause any issue in the functionality of the function itself, though I have found that this function will break when using the following module https://github.com/creatuity/magento2-interceptors , which forms the basis for the following PR that may or may not get merged down the line: https://github.com/magento/magento2/pull/22826

An example of a correct implementation already exists in Magento 2 core: [Product Authorization](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Plugin/ProductAuthorization.php#L44)

**Comment by engcom-Delta** [comment]
Hi @Quazz  thank you for your report. Could you provide case with this issue to clarify what negative impact it has?

**Comment by Quazz** [comment]
> Hi @Quazz thank you for your report. Could you provide case with this issue to clarify what negative impact it has?

Well, for the most part it simply doesn't follow Magento's guidelines on what an Interceptor (plugin) should return. 

If you were to create another plugin that comes after this plugin, it would not have access to the $saveOptions data, even though under normal circumstances it should.

In core Magento it doesn't cause any issues since $saveOptions is currently unused (though it conflicts with the expected parameters of its API).

**Comment by Quazz** [comment]
The plugin still does not follow Magento 2 guidelines as of yet.

**Comment by engcom-Hotel** [comment]
Hello @Quazz,

Thanks for reporting this issue!

As per the [documentation](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html), If there are any arguments, the method should return an array of those arguments. But here it is not returning the `$saveOptions` variable.

So I am confirming this issue.

Thanks

**Comment by rmsundar1** [comment]
@magento I am working on this

**Comment by engcom-Alfa** [comment]
As I have re-verified again, the $saveoptions is not getting omitted!
Please refer below steps that I have followed, and kindly let me know if anything needs to be added/changed.

**Using existing model:**

1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40 as shown in below screenshot
<img width="1440" alt="Screenshot 2021-12-16 at 2 35 39 PM" src="https://user-images.githubusercontent.com/51679138/146342268-de8f4333-ed36-466e-b754-c4d59da8b067.png">

2. Placed the var_dump line of code in the configurableProduct>Model>Plugin>ProductRepositorySave.php file as shown in below screenshot.
<img width="1440" alt="Screenshot 2021-12-16 at 2 35 52 PM" src="https://user-images.githubusercontent.com/51679138/146342552-a8d2576b-9f26-43b8-aa13-4157d481ce4e.png">

3. Placed the var_dump line of code in Catalog>Model>ProductRepository.php file as shown in below screenshot.
<img width="1440" alt="Screenshot 2021-12-16 at 2 36 05 PM" src="https://user-images.githubusercontent.com/51679138/146342881-38addc56-b503-4012-b68c-63a80396f7d8.png">

4. Tried to add the configurable product through API request and found the $saveoptions has a value
 set to bool(false) as shown in the below screenshot.
<img width="1440" alt="Screenshot 2021-12-16 at 2 35 17 PM" src="https://user-images.githubusercontent.com/51679138/146343086-df019070-df81-42ef-8cd2-bba065de42d8.png">



**Using new custom plugin:**
5. Instead of that, created new plugin as shown in below 2 screenshots.
<img width="1440" alt="Screenshot 2021-12-16 at 2 37 00 PM" src="https://user-images.githubusercontent.com/51679138/146343810-483fb1d5-9986-4113-bd67-8d7ede705149.png">

<img width="1440" alt="Screenshot 2021-12-16 at 2 38 30 PM" src="https://user-images.githubusercontent.com/51679138/146343859-810f6d08-9932-4c87-888a-c13fc08ae96a.png">

Still I am getting the same output as mentioned in the step 4 screenshot.

**Comment by Quazz** [comment]
Of course the functions technically have access to $saveOptions since it has a default value set by the function itself.

The issue is that $saveOptions variable is not being passed by the plugin. Try setting the value of $saveOptions to true in the plugin and then check the result in API call and you will see it has not changed.

**Comment by engcom-Hotel** [comment]
Hello @Quazz,

The issue is still relevant. Hence confirming the issue. The below method does not return the `$saveOptions` as per the Magento standard:

https://github.com/magento/magento2/blob/39f0be8226abd6036afccfc012a6a14dcb828b20/app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php#L58-L90

Thanks
