### ISSUE TITLE
Backend Search not working properly

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#31964]
### Preconditions (*)

1. 2.4.1

### Steps to reproduce (*)

1. Create a new CMS block named `Schiebetür einflüglig mit Rundumgriff`
2. Search for `Schiebetür`

### Expected result (*)

It should find the CMS block

### Actual result (*)

![image](https://user-images.githubusercontent.com/16349349/106776170-1caf6c80-6644-11eb-9331-c56cf2cce9bf.png)
-----------------
If you enter `Schiebet` then it gets found. 

![image](https://user-images.githubusercontent.com/16349349/106776489-64ce8f00-6644-11eb-9a9c-9afa6ec33209.png)

-----------------
If you enter `Schiebetür` then it does not find the block.

![image](https://user-images.githubusercontent.com/16349349/106776567-7c0d7c80-6644-11eb-8089-16f75db76617.png)

The problem seems to be the `ü`.

Tested on a fresh magento 2 with sample data (Enterprise)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hello @Eddcapone 

Thank you for your report. 

This is the expected behavior for the English Locale. If you'll change the Admin Locale to German, the search will find the _Schiebetür_ block 
![shube](https://user-images.githubusercontent.com/51680745/106914303-8e072200-670d-11eb-8279-ee11827c022a.png)

We are closing this issue. Please feel free to comment, reopen or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by Eddcapone** [comment]
Ok, but this is not clear and not a good solution. I am german and I rather work in a english UI, because instructions and the documentation are also written in english and it is much easier to follow them with an english UI.
