### ISSUE TITLE
Clarify error message in system upgrade tool when no updates are available

### ISSUE THREAD

**Issue by malaiselvan** [magento/magento2#3216]
I understand 2.0.2 is the latest.  I am very much frustrated with the error `Sorry, we can't take that action right now.` and I spent a hell amount of hours in 2.0.0 and 2.0.1.  Finally decided to install a fresh 2.0.2 and remigrate the data from 1.9.1.0.

I got my beta website running on 2.0.2.  Just for curiosity I tried the System Upgrade and I was expecting the system will say that 'No updates available' or similar kind of message.

But I got the same error message :-( frustrated again...

![image](https://cloud.githubusercontent.com/assets/5956639/12696231/9f8af254-c78a-11e5-8847-c1357a051a87.png)

This is my composer.json on Magento root directory

```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool-ce"
        }
    },
    "require": {
        "magento/product-community-edition": "2.0.2",
        "composer/composer": "@alpha",
        "magento/data-migration-tool": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}
```

This is the composer.json in update directory

```
{
    "name": "magento/updater",
    "description": "Magento Updater",
    "type": "project",
    "version": "2.0.0",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "php": "~5.5.0|~5.6.0|~7.0.0",
        "composer/composer": "1.0.0-alpha10",
        "magento/composer": "~1.0.0",
        "symfony/console": "~2.3 <2.7"
    },
    "autoload": {
        "psr-4": {
            "Magento\\": "app/code/Magento/"
        }
    }
}
```

Cron is running every minute

![image](https://cloud.githubusercontent.com/assets/5956639/12696248/61fccede-c78b-11e5-9bbf-28923e129898.png)

Below is the installation steps.

1  Downloaded the 2.0.2 tar.gz file from magento website
2. FTP to my hosting server
3. Unzip and install it via the setup wizard
4. Installed the magento migration tool ce-to-ce
5. Migrated the data from 1.9.1.0 to 2.0.2

**Comment by jsakars** [comment]
I noticed it as well after fresh 2.0.2 install. It seems that Magento2 in core is not quite stable yet.

**Comment by hiepnt93** [comment]
i having the same issue.

**Comment by mazhalai** [comment]
@malaiselvan @werdlv @vnecoms1 Well this is very much expected since there is no 2.0.3 version of Magento 2 available yet. Please try again when a newer version is available.

**Comment by davidalger** [comment]
> I was expecting the system will say that 'No updates available' or similar kind of message.

This is a bug report due to unclear messaging, not that the update system is not allowing them to update. Sounds legit to me, and it could stand to have copy that's a bit more clear.

**Comment by mazhalai** [comment]
Thank you for clarifying @davidalger! We have created MAGETWO-48650 to track changes.

**Comment by Quotacious** [comment]
Is the original poster sure that they have entered their Public and Private access key into System config when they freshly installed Magento 2.0.2?

I ask for two reasons... one, that is the error you get when the keys haven't been entered (obviously it should tell you about the missing keys, but it does not yet).

Two, I have a fresh 2.0.2 install, with properly configured keys, and have no problem continuing with the system upgrade.  It will take me through the Readiness check without issue.  When I get to the backup step, even though the backup indicates it has finished successfully, the system upgrade thinks otherwise, and stops the process - see my detailed post at [Magento Forums](https://community.magento.com/t5/Version-Upgrades-for-2-x/2-0-2-System-Upgrade-says-successful-backup-has-failed/td-p/28996). 

I'm wondering if this is a similar issue; that the System upgrade process should be saying there is no upgrade, but instead, the upgrade process fails on the backup step.

**Comment by malaiselvan** [comment]
Hi, I am sure I have keyed in the correct credentials. I double checked now too.

Note : It's a fresh install with default luma template with 0 code changes. The only additional thing I have is the core data migration tool installed and the data migrated from 1.9.1.0

Your response is completely contradict with mazhalai. You mentioned that the 2.0.2 system has taken you till the backup stage..... But as per mazhalai it should stop you because there is not higher version released yet...

**Comment by Quotacious** [comment]
Re: contradictory, yes, that was another reason wny I posted, as I knew I was able to get farther along than had been suggested earlier.

Last week I had an install on CentOS and PHP7 and the Magento System update there, as well, was more than willing to continue through to the backup stage, but it too, failed after the backup was completed, so I reverted back to Ubuntu.

I decided to comment on your issue rather than creating a new one, as it seemed possibly related and, well, there are already almost a 1,000 open issues so I wanted to wait a bit in case it was something that could be figured out.

**Comment by mazhalai** [comment]
@LongDono ~~what version did you install initially?~~ just read your previous comment that you had 2.0.2. So, in system upgrade page, what version did you select from the dropdown?  I think, since you had a previous installation, it is possible browser cache was not properly cleaned, you were able to get ahead to backup pages. There was a [similar issue](https://github.com/magento/magento2/issues/2891#issuecomment-173349882) during installation a couple of days ago.

**Comment by Quotacious** [comment]
@mazhalai Interesting idea!  I always use Google Chrome so I opened Internet Explorer 11 (eww) and went to my admin panel to check.  It still allowed me to continue and I note it indicates that it knows I'm using the current version:

![alt text](http://snag.gy/1kn5J.jpg)

I did not mean to crop the **Try Again** and **Next** buttons above but can confirm that **Next** lights up in orange and I can click it to continue to the Readiness Check.

**Comment by Quotacious** [comment]
Okay, I actually had a reply to my post on the Magento forums, where they suggested I'd perhaps not changed the default max_execution_time.  I had on php5 but not the new php7 install.

I changed it from 30 seconds to 1800 (overkill) and now the backup completes successfully, or more importantly, the webpage/php script doesn't time out before it is done.

The system upgrade then allowed me to proceed with my component upgrade from Magento 2.0.2 to presumably the same version, which goes as well as you'd probably expect...

![alt text](http://snag.gy/yrpsF.jpg)

I'll let it go for a while but it's already had 5 minutes so I think that's the end of that.

**Comment by mazhalai** [comment]
This issue has been fixed in the develop branch. Closing ticket. Please open a new one if issues persist.
