### ISSUE TITLE
Magento 2.4.x Elasticsearch issue with hyphen returning too many results?

### ISSUE THREAD

**Issue by amitvkhajanchi** [magento/magento2#32207]
Magento CE 2.4.1 (Production) and 2.4.2 (Staging)
Ubuntu 20.04 LTS
PHP 7.4.3
MySQL 8.022 (Amazon RDS)
Elasticsearch 7.6.2
Redis 5.2.1
Varnish 6.2.1
Nginx 1.8

PS. I have over 5000+ products in 2 websites (EU/US) EU site has 5 Store views (EN,FR,IT,DE,ES). US site has 1 Store view (US). Total of 6 Store view for my site.

I have multiple products with attribute of product model, which has "-" in its name.   For example APCRBC132-V7-1E.  I get proper result when I put in "APCRBC132-V7-1E" with quotes or APCRBC132 with 1 result, but if not it shows 1700+ results and then ultimately search will crash and I get varnish error.  This seems to be same issue documented on

[https://support.magento.com/hc/en-us/articles/360050671611-MDVA-28993-Magento-patch-Elasticsearch-partial-search-minimum-should-match-and-fix-for-searches-with-hyphen-issue](url)

![search_result_many](https://user-images.githubusercontent.com/5608603/108260174-d9123380-7116-11eb-91be-a48b91c2140f.jpg)

![search_result_many_doesnt_render](https://user-images.githubusercontent.com/5608603/108260263-f8a95c00-7116-11eb-82f3-d2a8e0c71f37.jpg)

![search_result_partial](https://user-images.githubusercontent.com/5608603/108260275-fc3ce300-7116-11eb-9842-c8a04ae1608d.jpg)
![search_result_enclosed_in_quotes](https://user-images.githubusercontent.com/5608603/108260280-fe9f3d00-7116-11eb-8169-de1603af6fce.jpg)

How can I have it just return 1 result as expected?  Seems "hyphen" means something else in Elasticsearch???

**Comment by mbautista** [comment]
Hello,
This issue still exists in Magento 2.4.3 with Elastic Search 7.x

There was a similar issue with mysql search (with a total different fix) and people posted there instead of here :
https://github.com/magento/magento2/issues/9988

I'm quite sure this affects lots of websites because most of magento shops use elastic search and hyphens in their SKUs.

Could you please have a look at my comment there ?
https://github.com/magento/magento2/issues/9988#issuecomment-1600390806

I've tried many things but nothing works.

Thank you for your help :)
Mathieu.

**Comment by tthierryEra** [comment]
I'm having this issue on 2.4.6-p3 too. Did anybody found a work around?
