### ISSUE TITLE
A PHPDoc result type of the \Magento\Ui\Component\AbstractComponent::render() method is wrong

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3221]
https://mage2.pro/t/395

**Comment by vrann** [comment]
@dfediuk Thanks for reporting! Can you please create a pull request to fix it?

**Comment by Mulderua** [comment]
Internal issue MAGETWO-54594 was created.

**Comment by magento-engcom-team** [comment]
@dmitry-fedyuk, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
