### ISSUE TITLE
Magento 2.4.2 is not showing agreements and setup page

### ISSUE THREAD

**Issue by Div123chauhan** [magento/magento2#32235]
I have downloaded the versions:
magento 2.4.2
Elasticsearch 7.11.1
PHP 7.4.15
Composer 2.0.9
MySQL 5.6.44
but, Magento 2.4.2 is not showing agreements and setup page. I share the Screenshot for the refrence.
![Screenshot_magento](https://user-images.githubusercontent.com/67589375/108617470-a92b9e80-743c-11eb-8ddb-6b2eb8b4bf55.JPG)

**Comment by zapotocnylubos** [comment]
Since Magento 2.4.* there is no web-based setup/installation, it only suppoorts command line setup (`bin/magento setup:install ...`).

**Comment by mrtuvn** [comment]
you have to install magento via command line instead. You no longer able install magento via web UI

**Comment by Div123chauhan** [comment]
by the CLI, I have following error in the snapshot.
How i solve this?

![Capture1](https://user-images.githubusercontent.com/67589375/108678465-1e68a380-7511-11eb-8dc7-5f4df6b4b7ad.JPG)

**Comment by mrtuvn** [comment]
Default magento not support windows os. Second if you have to try on windows make sure setup properly write files/folders. My suggest you should 
use sub system Linux on windows instead

**Comment by ihor-sviziev** [comment]
Hi @Div123chauhan,
Thank you for your report!

As @mrtuvn mentioned earlier, Magento 2.4.2 doesn't have a web-based installer anymore. That's why you have just links to documentation.
Also, Windows OS isn't supported by Magento. You can find the requirements here: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html.

As both points are not an issue - I'm closing this issue.
