### ISSUE TITLE
GET orders API using search criteria sometimes returns "same id" error

### ISSUE THREAD

**Issue by jglassmaker** [magento/magento2#32306]
### Preconditions (*)
Magento 2.4.2

### Steps to reproduce (*)
1. Populate an instance with many orders
2. Using the /orders/?searchCriteria API call fetch those orders

### Expected result (*)
A collection of orders is returned

### Actual result (*)
A fatal error is returned
`Item (Magento\Sales\Model\Order\Interceptor) with the same ID "93310" already exists.`

This issue is difficult to produce as it does not happen with every order. The order conditions are not yet known however within a 7 day period of about 59 orders, 2 orders cause this issue. Fetching the order directly using /orders/93310 does not produce a fatal error. It seems that while the orders with search criteria are being collected, an order can be collected twice. 

---
- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by clusain** [comment]
I am also seeing this issue and would like to know how to fix.

**Comment by jorjdaniel** [comment]
I got the same issue when tried to call the /orders API.

**Comment by rahimimo** [comment]
I observed the same thing

**Comment by gilbert-temgoua** [comment]
I'm facing the same issue too.

**Comment by groomershop-mt** [comment]
We also noticed this issue after updating Magento from 2.4.6 to 2.4.7. We found that the problem is caused by more than one record in sales_order_payment for the same order (having the same parent_id) - in our case faulty module for PayU payment processor was creating new payment (instead of new transaction). Such record were not a problem before upgrading Magento to 2.4.7-p3.

This SQL query show rows with duplicated parent_id:
SELECT p1.* FROM sales_order_payment p1, sales_order_payment p2 WHERE p1.entity_id > p2.entity_id AND p1.parent_id = p2.parent_id

This query remove duplicated rows, leaving the newest one:
DELETE p1 FROM sales_order_payment p1, sales_order_payment p2 WHERE p1.entity_id > p2.entity_id AND p1.parent_id = p2.parent_id
