### ISSUE TITLE
Installation Error Magento at 65%

### ISSUE THREAD

**Issue by alihashir** [magento/magento2#3241]
@mazhalai  Thanks for your response dear... but i do not know how to create /tmp/ folder and give permissions ... can you please explain it step by step...  Please mam... guide me by steps to make folder and giving permissions....
and also guide me if it need to disable " xdebug " or not...if yes then how to disable it...
Thanks.
![megento](https://cloud.githubusercontent.com/assets/15688053/12727036/b714b816-c93c-11e5-8b3f-ec2046a0b6dc.PNG)
![path](https://cloud.githubusercontent.com/assets/15688053/12727040/bae2b484-c93c-11e5-857f-b1c4674f7647.PNG)
![session](https://cloud.githubusercontent.com/assets/15688053/12727045/be7046e8-c93c-11e5-8f50-1685308dbb1b.PNG)
![xdebug](https://cloud.githubusercontent.com/assets/15688053/12727046/c0af26f4-c93c-11e5-9cca-6e787009465a.PNG)

**Thanks Again** !!!

**Comment by ghost** [comment]
How to [disable xdebug](http://stackoverflow.com/questions/8754826/how-to-disable-xdebug)

The context for the other information you requested isn't clear.

**Comment by alihashir** [comment]
@xcomSteveJohnson  thanks for being here... Sir actully when i install magento it Fails on 65% as shown in 1st screenshot... you can see in consol log... "Installing User Configuration" 

Please help me in fixing it

Thanks...

**Comment by ghost** [comment]
#2942 where the suggestion was "This issue is caused by you php `session.save_path setting` in your `php.ini` file. It is not readable by the apache user. Please create tmp/ folder and give required permissions, or change the setting to point to another writable folder."

You wanted to know how to do this:
1.  Open your `php.ini` file in a text editor to find the value of `session.save_path` .
2.  Set the value to `/tmp/magento`
3.  Save your changes to `php.ini` and exit the text editor.
4.  Find the name of your Apache web server user:
   -   CentOS: `egrep -i '^user|^group' /etc/httpd/conf/httpd.conf`
   -  Ubuntu: `ps aux | grep apache` 
5.  Enter the following command:

```
sudo chown /tmp/magento <apache user name>
```
1. Restart Apache and try to install again.

**Comment by alihashir** [comment]
@xcomSteveJohnson sir check the screen... i have done setting value to \tem\magento as you said... but i did not get the point number 4. "Find the name of apache server user" ... can you tell me more that where to type those commands and where to find the name... i am using Window 7 and Wamp server....

![done](https://cloud.githubusercontent.com/assets/15688053/12728658/aeba9caa-c944-11e5-9fe8-48ba3bf7640c.PNG)

**Comment by ghost** [comment]
I don't use WAMP so I cannot tell you the exact command. Try googling it.

**Comment by alihashir** [comment]
@xcomSteveJohnson  thanks for helping me :)

**Comment by alihashir** [comment]
@magento-team  @mazhalai  can you help me in it please... ??

**Comment by ghost** [comment]
Try this: http://stackoverflow.com/questions/10289133/finding-out-what-user-apache-is-running-as-in-windows

**Comment by maksek** [comment]
please use forums for questions, GitHub only for bugs and PR.
