### ISSUE TITLE
cookie lax append issue magento 2.4.2 upgrade enterprise b2b

### ISSUE THREAD

**Issue by sivamind** [magento/magento2#32440]
on magento 2.4.2 upgrade Uncaught TypeError: Cannot create property 'cart' on string '{"messages":1613612384,"company":1613612384,"customer":1613612384,"compare-products":1613612384,"requisition":1613612384,"last-ordered-items":1613612384,"cart":1613612384,"directory-data":1613612384,"captcha":1613612384,"wishlist":1613612384,"company_authorization":1613612384,"negotiable_quote":1613612384,"instant-purchase":1613612384,"loggedAsCustomer":1613612384,"multiplewishlist":1613612384,"purchase_order":1613612384,"persistent":1613612384,"review":1613612384,"recently_viewed_product":1613612384,"recently_compared_product":1613612384,"product_data_storage":1613612384,"paypal-billing-agreement":1613612384}laxlaxlaxlaxlaxlax'

**Comment by gabrieldagama** [comment]
Hi @sivamind. Thank you for your report. 
The issue has been fixed in magento/magento2#32462 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [bc5f97e65aadf8c8e5ee216100805874826198ca](https://github.com/magento/magento2/commit/bc5f97e65aadf8c8e5ee216100805874826198ca)
 - [41b935d9645f7108232cef2f39a521cd22d18623](https://github.com/magento/magento2/commit/41b935d9645f7108232cef2f39a521cd22d18623)
 - [35570b3b0a98b578f88bd6cb694b1c0f4fc2b7c8](https://github.com/magento/magento2/commit/35570b3b0a98b578f88bd6cb694b1c0f4fc2b7c8)
 - [753be2a3db726090a6f05b7801ed4047ee65f36d](https://github.com/magento/magento2/commit/753be2a3db726090a6f05b7801ed4047ee65f36d)

The fix will be available with the upcoming 2.4.3 release.

**Comment by pemann** [comment]
So it will be 5 months and we'll get our shops to work!
Any chance to get this fix on M2.4.2-p1?

**Comment by IbrahimS2** [comment]
I applied the patch, but the problem never went away!?

**Comment by ihor-sviziev** [comment]
Just note the fix also available in the quality patches tool as MC-41359.
