### ISSUE TITLE
Paying with Paypal changes guest users email

### ISSUE THREAD

**Issue by teuma86** [magento/magento2#3253]
If you checkout as a guest, using a@example.com 
Select PayPal as your payment method, then sign into paypal with b@example.com
The Success page shows you an option to create the account for b@example.com
Also the order is against email b@example.com.

**Comment by alena-marchenko** [comment]
Hi,

We created internal ticket MAGETWO-49101 regarding this issue

**Comment by alena-marchenko** [comment]
We have resolved the issue and delivered the fix to develop branch.

**Comment by komsitr** [comment]
Hi @alena-marchenko 

Do you know which release version this fix is included? I updated to 2.0.5 but the issue still persist.

**Comment by tigerx7** [comment]
What is the associated commit for this fix? We're experiencing an issue on 2.1.6 where email is not being associated with the quote when guest uses paypal thus a critical error is thrown when trying to save customer since email is empty. We have a feeling changes made for this commit may be conflicting with some of the other fixes we've had to do.
