### ISSUE TITLE
Magento2: Unable to redirect to new page from capture method of custom payment module

### ISSUE THREAD

**Issue by mohinik-chetu** [magento/magento2#3257]
Hi,

I am unable to redirect to new page (where i want form submit feature) on based of some condition from capture method of model. Similar to http://stackoverflow.com/questions/21753859/implementing-3d-secure-verification-in-custom-api-based-payment-method-in-magent.
Please provide a solution.

**Comment by alena-marchenko** [comment]
Hi @mohinik-chetu ,

It's hard to suggest something since we don't know you flow details.
But if you want to make some validation before order processing you should extend Magento_Payment/js/view/payment/cc-form component and override placeOrder method.
Take a look at Braintree payment implementation https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/view/frontend/web/js/view/payment/method-renderer/cc-form.js#L299
A sample of magento payment module you can find here https://github.com/magento/magento2-samples/tree/master/sample-module-payment-gateway
we suggest to make your payment integration according to this sample.
Closing this issue, please feel free using [Community Forums](https://community.magento.com/) or [Magento Stack Exchange](http://magento.stackexchange.com/) for further technical questions.
