### ISSUE TITLE
WYSIWYG Editor in IE

### ISSUE THREAD

**Issue by Kastnerd** [magento/magento2#3259]
When editing a product page any maybe other places.  The WYSIWYG editor does not work in IE. Works fine in Chrome.  Using IE 11.0.9  Below you can see the IE view first. and then the Chrome view.  Using Magento 2.0.2

![iewysiwyg](https://cloud.githubusercontent.com/assets/17027563/12752853/5debce72-c992-11e5-9f54-28b1d740ad2e.JPG)
![chromewysiwyg](https://cloud.githubusercontent.com/assets/17027563/12752859/633345fe-c992-11e5-894f-86c919f65d61.JPG)

**Comment by Khaleel** [comment]
There are many known bugs with the WYSIWYG editor already reported.

I think the best thing would be to make a new File Media Manager in Magento 2 that links in the WYSIWYG - we have a lot of feedback from Content and Marketing that there is no history tool either thus having to trawl through many folders. And no search features.

It is a poor Gallery and upload tool. It often fails in Firefox, Chrome and IE. I also receive many errors when using it in Arabic.

I think TinyMCE has issues with Arabic due to UTF and charset
<img width="1434" alt="screen shot 2016-02-03 at 12 36 44 pm" src="https://cloud.githubusercontent.com/assets/355336/12776912/e18849be-ca72-11e5-8e58-5e3e1e1fa7aa.png">
<img width="1437" alt="screen shot 2016-02-03 at 12 36 50 pm" src="https://cloud.githubusercontent.com/assets/355336/12776913/e1b159b2-ca72-11e5-9a0e-2e8e89350e3f.png">

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
