### ISSUE TITLE
Underscores not allowed in module names in \Magento\Framework\App\Utility\Files::accumulateThemeStaticFiles 

### ISSUE THREAD

**Issue by bentideswell** [magento/magento2#32619]
PSR-4 dictates that underscores have no special meaning and can be used in module names. There have been  [multiple](https://github.com/magento/magento2/pull/11765) [PRs](https://github.com/magento/magento2/pull/14397) accepted for this bug in other areas of Magento but this one has been missed.

This is in \Magento\Framework\App\Utility\Files::accumulateThemeStaticFiles. This method collates static files from your theme. The bug means that it's not possible to extend a static file from a module that has an underscore in the module name (eg. FishPig_WordPress_IntegratedSearch).

### Preconditions (*)
1. Magento 2.4.2 - but this is probably present in all versions from 2.0.0

### Steps to reproduce (*)
1. Install Magento 2.4.2
2. Extend a CSS file from a module with an underscore in the module name (app/design/frontend/YourVendor/YourTheme/ThirdParty_Module_Test/web/css/source/_module.less)
3. Compile the static assets

### Expected result (*)

The _module.less is processed correctly

### Actual result (*)
Error happened during deploy process: Could not parse theme static file '/var/www/test-siteapp/design/frontend/YourVendor/YourTheme/ThirdParty_Module_Test/web/css/source/_module.less'

---
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by bentideswell** [comment]
I have created a [PR](https://github.com/magento/magento2/pull/32620) for this.

**Comment by gabrieldagama** [comment]
Hi @bentideswell. Thank you for your report. 
The issue has been fixed in magento/magento2#32620 by @bentideswell in 2.4-develop branch
Related commit(s):
 - [a3b124a773061d59fbce5a4efb5cd7b3479f6db0](https://github.com/magento/magento2/commit/a3b124a773061d59fbce5a4efb5cd7b3479f6db0)
 - [e17a3e7fb9b26510a6102a654253bab0c0d0d072](https://github.com/magento/magento2/commit/e17a3e7fb9b26510a6102a654253bab0c0d0d072)
 - [df94b8aef4a8c59a04dc432d286cec172e99500b](https://github.com/magento/magento2/commit/df94b8aef4a8c59a04dc432d286cec172e99500b)
 - [696f7ee63784e6d549d5d2b2ad39b649b1812cc5](https://github.com/magento/magento2/commit/696f7ee63784e6d549d5d2b2ad39b649b1812cc5)
 - [96f58e78e750452475dcae0f1f8d2a86fc78de41](https://github.com/magento/magento2/commit/96f58e78e750452475dcae0f1f8d2a86fc78de41)
 - [87c4a75b98d3e7e6d98885f231fef3d035b76587](https://github.com/magento/magento2/commit/87c4a75b98d3e7e6d98885f231fef3d035b76587)

The fix will be available with the upcoming 2.4.3 release.
