### ISSUE TITLE
Added compare_item does not get returned in response

### ISSUE THREAD

**Issue by jurvi** [magento/magento2#32692]
*As a customer who wants to compare products I want to add configurable product variants in compare_list so that I can compare their content.*

### AC
* Add a configurable product variant to compareList using addProductsToCompareList mutation
* Observe the response that has item_count 0 and empty items array.
* Fetch the list using compareList query
* Observe again the item_count 0 and empty items array

### Approved Schema
* Schema is fine, variants are just not getting returned in the response

Additional information: 
Also checked from database and variant gets added to compare_items table properly. Looks like the issue is that the variant does not exist in catalog_category_product_index_storeX table thus not getting returned due to failing INNER JOIN clause in SQL.

**Comment by engcom-Golf** [comment]
@jurvi This issue is not reproducible. May be Configurable Product is not created in a correct way. I have created one Configurable Product having Color Attribute  with multiple Variants. Let me explain you with Example.

Step 1: **Added a [configurable product variant to compareList using addProductsToCompareList mutation](url)**
Step 2: **Fetch the list using compareList query**

Please note that **item_count** 2 and items array is not empty. Output is shown as expected.
specific portion of Snapshots are attached for your reference. 
![image](https://user-images.githubusercontent.com/51681547/122383928-dde1d980-cf88-11eb-9924-b29ffc3ad30d.png)
![image](https://user-images.githubusercontent.com/51681547/122384086-fe119880-cf88-11eb-9b47-ad904d61bb3c.png)
![image](https://user-images.githubusercontent.com/51681547/122384143-09fd5a80-cf89-11eb-9334-4fabbde5fbf7.png)

**Comment by engcom-November** [comment]
Based on the labels added, we are closing this issue.
Thank you
