### ISSUE TITLE
Incorrect URL path 

### ISSUE THREAD

**Issue by swap-994** [magento/magento2#32704]
Hi there,

I've a website which is developed in Magento 2. I'm having some issues with URLs. I'm not getting the proper path of URL for category and product pages. 

I'm an SEO executive and abides by the SEO guidelines that the website should follow. 

I'm attaching the screenshot for the same. 
![svaraa pdp url](https://user-images.githubusercontent.com/82205999/114191697-54030800-996a-11eb-9298-289e349db16b.PNG)

Also, currently I have the following filter URL, which is not as per the Google's guidelines and does not impact on SEO.

1) Filter by Price -
Current URL: - https://www.svaraa.in/rings.html?price=10000-20000

2) Filter by Product -
Current URL: - https://www.svaraa.in/rings.html?prod_type=7393

3) Filter by Weight Range -
Current URL: - https://www.svaraa.in/rings.html?weight_range=7394

4) Filter by Material - 
Current URL: - https://www.svaraa.in/rings.html?material=7750 

Kindly, let me know how to improve the formatting of URL in magento 2.

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Oscar** [comment]
Hello @swap-994 !
Please check if you have enabled the url rewrite in your store configuration: Admin->Configuration->General->Web-> Search Engine Optimization-> "Use Web Server Rewrites". Then you need to do full reindex and flush cache.

**Comment by swap-994** [comment]
Hi Slava,

Sorry, for the late revert. Yes, I've checked the backend and the "Website
Server Rewrites" is enabled already.

Please let me know what should be done next in order to get the proper URL
format. Also, I don't know how to do a full reindex and flush cache, please
advise me step by step.

Thanks & Regards,
Swapnil Sharma

**Comment by engcom-Oscar** [comment]
@swap-994  
https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-index.html
https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cache.html

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible:
@swap-994 Catalog and Products URL configuration can be done in Admin - Stores - Configuration - Catalog - Catalog - Search Engine Optimization followed by reindexing (reindex from Terminal/CLI: >php bin/magento indexer:reindex) and clearing cache (> php bin/magento cache:flush)
Kindly refer the [docs](https://docs.magento.com/user-guide/catalog/catalog-urls.html) if you need further details of configuration.
Kindly recheck the issue on latest Magento version and elaborate steps to reproduce if you are still facing the issue.
Thank you.
