### ISSUE TITLE
«Yes/No» attributes should be allowed in the Layered Navigation

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3283]
https://mage2.pro/t/462

**Comment by kandy** [comment]
@dfediuk,  Thanks for reporting. Can I ask you describe in more details steps to reproduce and expected behavior.

**Comment by dmitrii-fediuk** [comment]
![](https://mage2.pro/uploads/default/original/1X/d86c437f3f44903e28c1726540905de96eff8635.png)
![](https://mage2.pro/uploads/default/original/1X/83e83a57f303f26845313e651af49c920c8ac480.png)

**Comment by AddoSolutions** [comment]
+1 on this

**Comment by choukalos** [comment]
Adding to epic - MAGETWO-39787 for consideration (improved layered navigation)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Yes-No-attributes-should-be-allowed-in-the-Layered-Navigation/idi-p/46090).

**Comment by sebfie** [comment]
Do you have pr or code change related to this on 2.3 branch?

**Comment by sebfie** [comment]
I tried on 2.3-develop branch, it does not work

**Comment by lewisvoncken** [comment]
@sebfie  I will make a PR for this

#workingonit

**Comment by magento-engcom-team** [comment]
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#17823 by @lewisvoncken in 2.2-develop branch
Related commit(s):
 - [952b333b9908121f17e966078737c21b8620cce6](https://github.com/magento/magento2/commit/952b333b9908121f17e966078737c21b8620cce6)
 - [a2d9a6a5f84d680c23d4f269596baf40ac709395](https://github.com/magento/magento2/commit/a2d9a6a5f84d680c23d4f269596baf40ac709395)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#18434 by @lewisvoncken in 2.3-develop branch
Related commit(s):
 - [e6833c8af293def8774eebc90c7cd994a08f50ba](https://github.com/magento/magento2/commit/e6833c8af293def8774eebc90c7cd994a08f50ba)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#21772 by @stkec in 2.3-develop branch
Related commit(s):
 - [dc3bdb8e2e3dc2b111c4174da2f523e3764f9b71](https://github.com/magento/magento2/commit/dc3bdb8e2e3dc2b111c4174da2f523e3764f9b71)
 - [b34eb7a41477af9223241d7bc24f609093e179fb](https://github.com/magento/magento2/commit/b34eb7a41477af9223241d7bc24f609093e179fb)
 - [3c50c7ceed1728d3886131b29ea2e0d937a68b97](https://github.com/magento/magento2/commit/3c50c7ceed1728d3886131b29ea2e0d937a68b97)

The fix will be available with the upcoming 2.3.2 release.
