### ISSUE TITLE
GraphQL : Cannot update Bundle Product selected options quantity in cart

### ISSUE THREAD

**Issue by theshreyas** [magento/magento2#32834]
Cannot update Bundle Product selected options quantity in cart
### **Preconditions**
1. Magento 2.4.1 / 2.4.2
1. GraphQl API
1. Bundle product with at least one option exists
  * The option must allow for "User Defined" quantities. This is only possible for options with input type "Drop-down" or "Radio Buttons".

### **Steps to reproduce**
1. Add the product with its required options to the cart using "addProductsToCart" mutation
```json
mutation {
  addProductsToCart(
    cartId: "WPHOcFMyngPmdwLfsegKBfpIFbGoLXa8", 
    cartItems: <{
      quantity: 1, 
      sku: "Bundle", 
      selected_options: ["YnVuZGxlLzEvMi8x">, 
      entered_options: <{
        uid: "YnVuZGxlLzEvMi8x", 
        value: "1"
      }>
    }]
  ){
    cart {
      id
      items {
        quantity
        ... on BundleCartItem {
          bundle_options {
            label
            type
            uid
            values {
              id
              label
              price
              quantity
            }
          }
        }
      }
    }
  }
}
```
1. Now try to update the bundle product quantity (parent product) and the bundle option quantity (child product) using the "updateCartItems" mutation
```json
mutation {
  updateCartItems(
    input: {
      cart_id: "WPHOcFMyngPmdwLfsegKBfpIFbGoLXa8",
      cart_items: <{
        cart*item*uid: "MTAw" 
        quantity: 3 
      }>
    }
  ){
    cart {
      items {
        uid
        product{ 
          name 
        }
        quantity
      }
      prices {
        grand_total{ 
          value
          currency 
        }
      }
    }
  }
}
```

### **Expected result**
1. Both the bundle product quantity (parent product) and the bundle option quantity (child product) get updated

### **Actual result**
1. Only the bundle product quantity (parent product) is updated. The bundle option quantity (child product) is unchanged.

### ** Additional Information **
UID of the options can be retrieved using below mutation:
`
{
  products(filter: { sku: { eq: "bundle1" } }) {
    total_count
    items {
      id
      name
      uid
      sku
      url_key
      stock_status
      new_from_date
      new_to_date
      special_price
      special_from_date
      special_to_date
      __typename
      short_description {
        html
      }
      description {
        html
      }
      image {
        url
        label
      }
      small_image {
        url
        label
      }
      thumbnail {
        url
        label
      }
      swatch_image
      media_gallery {
        url
        label
      }
      ... on BundleProduct {
        dynamic_sku
        dynamic_price
        dynamic_weight
        price_view
        ship_bundle_items
        items {
          option_id
          title
          sku
          uid
          type
          required
          position
          options {
            id
            label
            uid
            quantity
            can_change_quantity
            price
            price_type
            is_default
            position
            product {
              id
              name
              sku
              uid
              stock_status
              __typename
            }
          }
        }
      }
    }
  }
}
`

### **Proposed Solution**

We have selected*options & entered*options in the addProductsToCart mutation, but not in the updateCartItems mutation. The updateCartItems mutation should be updated to include these fields and function similarly to the addProductsToCart mutation.

**Comment by cpartica** [comment]
@magento export issue to Jira project PWA as Bug

**Comment by cpartica** [comment]
@magento export issue to Jira project MC as Bug

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Steps performed:
1. Generate Customer token using graphql
2. Get Cart ID of the logged in customer using GraphQL query
3. Add Bundle Product to Cart using below addProductsToCart mutation:
`
mutation {
  addProductsToCart(
    cartId: "yAuBMIIb6VTBt3pXbpCL7ZwpgbSvlSG0"
    cartItems: [
      {
        quantity: 1
        sku: "bundle1"
        entered_options: [
          {
            uid: "YnVuZGxlLzIvMy81"
            value: 1
          }
        ]
        selected_options: [
          "YnVuZGxlLzIvMy81"
        ]
      }
    ]
  ) {
    cart {
      items {
        uid
        product {
          name
          sku
        }
        quantity
        ... on BundleCartItem {
          bundle_options {
            uid
            label
            type
            values {
              id
              label
              price
              quantity
            }
          }
        }
      }
    }
  }
}
`
4. Now run below updateCartItems" mutation 
`
mutation {
  updateCartItems(
    input: {
      cart_id: "yAuBMIIb6VTBt3pXbpCL7ZwpgbSvlSG0",
      cart_items: [
        {
          cart_item_uid: "MTc="
          quantity: 2
        }
      ]
    }
  ){
    cart {
      items {
        uid
        product {
          name
        }
        quantity
      }
      prices {
        grand_total{
          value
          currency
        }
      }
    }
  }
}
`
Issue: Unable to update the quantity
![image](https://user-images.githubusercontent.com/60198231/143895256-8dcb3f12-29c2-400f-b5f6-58e04b00521d.png)

**Comment by engcom-Hotel** [comment]
Hello @theshreyas,

We have analysed this issue on a clean instance of 2.4-develop, please find my observations below.

The **updateCartItems** mutation takes **cart_id** & **cart_items** as input attributes, from which it uses the **cart_item_uid** to identify and update the details of the respective cart item, the concerned mutation is appended for reference.
```
mutation {
  updateCartItems(
    input: {
      cart_id: "2m3Wpue1L3bNARhErAKbZ8Lb7czvgq6R",
      cart_items: [
        {
          cart_item_uid: "MjQ="
          quantity: 3
        }
      ]
    }
  ){
    cart {
      items {
        uid
        product {
          name
        }
        quantity
      }
    }
  }
}
```
When the **cart_item_uid** of the selected option of the bundled product in the cart is provided as the value to input attribute, an error is thrown with the message **Child items may not be updated.** from `app/code/Magento/QuoteGraphQl/Model/CartItem/DataProvider/UpdateCartItems.php` 
![image](https://user-images.githubusercontent.com/51681618/145036294-ca43c6b0-7275-4267-9e96-46c8939a6517.png)

This scenario was also verified from the frontend, wherein there is no provision to edit the quantity of the selected option from the cart page, in-turn the user has to click on the edit icon which will redirect to the product page, from where he/she can update the selected option quantity.
![image](https://user-images.githubusercontent.com/51681618/145036411-5f227a8f-c9a0-42cf-bdf1-4fe6e681a63c.png)

Hence taking cues from the above code snippet & frontend cart behavior, this seems like an **expected behavior** of Magento to disallow update of selected options from the cart. If this feature needs to be implemented, we will require a confirmation from the concerned PO.

Thanks
