### ISSUE TITLE
Investigate upgrade to the latest ChartJS

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32842]
### Overview

For the ChartJS library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC
- Create PoC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration.

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by karyna-tsymbal-atwix** [comment]
Investigation Outcome

**If this library is used on Admin UI or Storefront Luma or both**
Admin UI only.


**What exact functionality is using this particular library**
The only place where this library is used - Admin Dashboard Page, a section with Charts.
Entry point: _app/code/Magento/Backend/view/adminhtml/web/js/dashboard/chart.js_

**Is it possible to migrate without introducing BIC into Luma**
This library is not used in Luma theme and it’s excluded from frontend bundling.

**Level of the impact of updating dependency in terms of BIC**
As it’s used only in one place in Admin area, I’d say that this level is low.

**What is a preliminary scope of work to migrate to the new version.**
The 3.x version contains major changes.
The time scale requires both a date library and a corresponding adapter to be present. Time scale is used in Dashboard charts, so adapter is required now.
(details: https://www.chartjs.org/docs/latest/axes/cartesian/time.html#date-adapters)

Right now a moment.js library is in use, so chartjs-adapter-moment.js should be used.
(https://github.com/chartjs/chartjs-adapter-moment, https://www.jsdelivr.com/package/npm/chartjs-adapter-moment)

Also, I checked the 3.x Migration Guide and made changes into dashboard/chart.js, as there are changes in the configuration options.
(details: https://www.chartjs.org/docs/latest/getting-started/v3-migration.html#scales)

**Library was updated to 3.3.2** 
https://github.com/magento/magento2/pull/33463
___________
The last version of ChartJS library (at the time of this investigation) is **3.4.1**, which was released on 04 Jul 2021.
3.4.x release introduces a new error in dashboard/chart.js:

_Uncaught TypeError: Cannot read property 'getBasePixel' of undefined_
This error has to be fixed in order to use the very last version.

As was found during the investigation, the reason for this issue is prototype.js overrides native _Array.from_ function.
A workaround should be found to continue with the upgrade.
