### ISSUE TITLE
Investigate upgrade to the latest ExtJS

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32843]
### Overview

For the ExtJS library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC
- Create PoC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration. 

### Conclusion

It was agreed to not upgrade the current version of ExtJS, which is in the code, and don’t replace it with JSTree. The main reason being that the latest versions of ExtJS are not open source.

**Comment by karyna-tsymbal-atwix** [comment]
@magento I am working on this

**Comment by eduard13** [comment]
### Update

We couldn't find the library within the [open sources](https://github.com/search?o=desc&q=extjs&s=&type=Repositories). However, the vendor now offers some paid solutions. There is a possibility to use a Community edition ([Ext JS Community Edition](https://www.sencha.com/products/extjs/communityedition/)) but it has some legal restrictions. 

As discussed internally, since there is already implemented [JsTree](https://www.jstree.com/) library in core and Adobe Stock Integration project, we have to estimate how much effort is required to replace ExtJs in all the places where is being used.

**Comment by eduard13** [comment]
### Update

After discussing it with Adobe team, it was agreed to not upgrade the current version of ExtJS, which is in the code, and don’t replace it with JSTree. 

The latest versions of ExtJS are not open source.

### Overview

- The Admin area is the only affected area
- Most of the usages are in the templates, which means a BIC, however, the probability is quite low. Moreover, removing this library means breaking some 3rd party implementations that rely on ExtJs Tree library.
