### ISSUE TITLE
Investigate upgrade to the latest legacy-build.min.js

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32853]
### Overview

For the legacy-build.min.js library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration.

**Comment by anzin** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
seem this package related with prototype

**Comment by anzin** [comment]
**Review Results**:

1.  **If this library is used on Admin UI or Storefront Luma or both**
     _The library is used in Admin UI_
2. **What exact functionality is using this particular library**

The legacy-build.min library includes the following files:

- lib/web/prototype/prototype.js
- lib/web/prototype/window.js
- lib/web/scriptaculous/builder.js
- lib/web/scriptaculous/effects.js
- lib/web/lib/ccard.js
- lib/web/prototype/validation.js
- lib/web/varien/js.js
- lib/web/mage/adminhtml/varienLoader.js
- lib/web/mage/adminhtml/tools.js
- dev/tools/grunt/assets/legacy-build/shim.js

3. **What is a preliminary scope of work to migrate to the new version.**

Needed updated next js library:

- **lib/web/prototype/prototype.js** from **1.7** to **1.7.3**
- **lib/web/prototype/window.js** from from **1.3** to **1.4b**
- **lib/web/prototype/validation.js** does not have a new version latest version **1.5.41**
- **lib/web/scriptaculous/builder.js** from **1.8.2** to **1.9.0**
- **lib/web/scriptaculous/effects.js** from **1.8.2** to **1.9.0**
- **lib/web/lib/ccard.js** does not have a new version 
- **lib/web/varien/js.js** custom library don't need update
- **lib/web/mage/adminhtml/varienLoader.js** custom library don't need update
- **lib/web/mage/adminhtml/tools.js** custom library don't need updat
- **dev/tools/grunt/assets/legacy-build/shim.js**  don't need update

The changes are not significant and must be compatible with the current Magento. The amount of work will only consist of replacing the .js files.

4. **Is it possible to migrate without introducing BIC into Luma**

It is possible to update libraries without introducing BIC into Luma because changes are minor.

5. **Level of the impact of updating dependency in terms of BIC**

The level should be low because there are no significant changes in the updated libraries.
