### ISSUE TITLE
Update guzzlehttp/guzzle to the latest version

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/magento2#32869]
Update guzzlehttp/guzzle from 6.5.5 to 7.3.0

### What needs to be done:
 - Review and list the usages of the library in the codebase
 - Review and list the backwards-incompatible changes of the new version of the library (link the migration guide if available)
 - Update the dependency via composer
 - Perform the testing of affected areas after update (use automated tests if available)
 - Open the pull request (and pull requests to related repositories if available)
t

**Comment by drpayyne** [comment]
- checks the packages in CE repo which requires `guzzlehttp/guzzle`
```
$ composer why guzzlehttp/guzzle
  
magento/magento2ce                    dev-2.4-develop  requires  guzzlehttp/guzzle (^7.3)                
aws/aws-sdk-php                       3.183.10         requires  guzzlehttp/guzzle (^5.3.3|^6.2.1|^7.0)  
csharpru/vault-php-guzzle6-transport  2.0.4            requires  guzzlehttp/guzzle (~6.2)
```
- checks the packages in EE repo which requires `guzzlehttp/guzzle`
```
$ composer why guzzlehttp/guzzle

magento/magento2ee                    dev-2.4-develop  requires  guzzlehttp/guzzle (^7.3.0)              
aws/aws-sdk-php                       3.183.11         requires  guzzlehttp/guzzle (^5.3.3|^6.2.1|^7.0)  
csharpru/vault-php-guzzle6-transport  2.0.4            requires  guzzlehttp/guzzle (~6.2)
```
- checks which packages require `csharpru/vault-php-guzzle6-transport`, since this is the package which is blocking the upgrade of `guzzlehttp/guzzle` to `7.x`
```
$ composer why csharpru/vault-php-guzzle6-transport 

magento/magento2-functional-testing-framework  3.5.1  requires  csharpru/vault-php-guzzle6-transport (^2.0)

```

CE, EE -> MFTF -> `csharpru/vault-php-guzzle6-transport:^2.0`. But, the latest version of this dependency is `2.0.4` which is already what we're using. (https://packagist.org/packages/csharpru/vault-php-guzzle6-transport). This package hasn't hasn't been updated in over two years...

**Comment by drpayyne** [comment]
@magento I'm working on this

**Comment by drpayyne** [comment]
Created a PR in the blocking repository - https://github.com/CSharpRU/vault-php-guzzle6-transport/pull/3.

**Comment by drpayyne** [comment]
Dependent PR has been closed saying repository isn't active anymore - https://github.com/CSharpRU/vault-php-guzzle6-transport/pull/3. Will check codebase for this package's usage.

**Comment by sivaschenko** [comment]
@drpayyne @andrewbess @jilu1 can csharpru/vault-php-guzzle6-transport be eliminated from MFTF (or replaced with active alternative)?

cc @fascinosum
