### ISSUE TITLE
Quote Lifetime works not like documented

### ISSUE THREAD

**Issue by TimQSO** [magento/magento2#32880]
The documentation found here:
https://docs.magento.com/user-guide/sales/cart-quote-lifetime.html

Says that with the quote lifetime you are able to set an amount of days to protect the price of the products that are put in a cart.

So, if you set it to 3 days, the customer will be protected against price changes for the products that are in the cart. After those 3 days, the price of the items in the cart is allowed to change.

I quote the docs:

"You can determine how long a price is valid by setting the cart quote lifetime in the configuration. For example, if a shopper leaves a cart unattended after several days, the quotes price for some items might no longer be the same. By default, the quote lifetime is set to thirty days." and "For Quote Lifetime (days), enter the number of days that a quoted price remains valid."

However this feature works completely different. If you set Quote Lifetime to 3 days, the complete cart will be removed after those 3 days. The cart is erased and gone for the customer.

### Preconditions (*)

1. Magento 2.4.2 
2. PHP 7.4
3. Nginx

### Steps to reproduce (*)

1.  Set Quote Lifetime to 1 day
2.  Put something in your cart
3. Change the price of the product in the backend
4. Check the cart, the price should not be changed, because you are still within the Quote Lifetime, but the cart price has been changed too
5. Close your browser
3.  Come back not sooner than 24 hours ( 1 day)
4. See that the cart is removed

### Expected result (*)

1. After changing a product price while the cart is still within the quote lifetime, the price of the product in the cart should not change
2. After 24 hours the cart should be still there. 
### Actual result (*)

1. Prices are effectuated immediately after changing a price in the backend
2. When the Quote Lifetime has passed, the cart is gone

You can do two things: 

1. Change the documentation, that says that the Quote Lifetime is in fact the Cart Lifetime, after the Lifetime has passed, the cart will be removed
2. Change the behaviour of the Quote in the cart, like documented and add a second feature 'Cart Lifetime'. But we would need to be able to disable 'Quote Lifetime' most shop owners want a price to change immediately in the carts when changed in the backend.

At this moment there is no such thing as 'Quote Lifetime' only 'Cart Lifetime'

**Comment by magento-engcom-team** [comment]
@engcom-Oscar Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
@m2-community-project[bot] Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42146` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Delta** [comment]
Hi @TimQSO ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and it is an improvement so we will mark ticket as feature request. Product price updates as soon as cron runs instead of quote lifetime set.

**Steps to reproduce**
1. Set Quote Lifetime to 1 day
![image](https://github.com/user-attachments/assets/1333d08e-d409-4781-a74f-578bb323d606)
2. Put something in your cart
![image](https://github.com/user-attachments/assets/df56675a-2f04-4f37-989e-e85fa1d3ed9b)
3. Change the price of the product in the backend
![image](https://github.com/user-attachments/assets/ceab6828-e094-4f55-b7b7-ab7b31de81ae)
4. Check the cart, the price should not be changed, because you are still within the Quote Lifetime, but the cart price has been changed too
![image](https://github.com/user-attachments/assets/bde02e3e-c289-4460-8735-09cf61342c24)
5. Close your browser
6. Come back not sooner than 24 hours ( 1 day)
7. Observe product stays in the cart with Updated price
![image](https://github.com/user-attachments/assets/97f0bf30-1339-4b78-938e-414b17768219)

Thanks.

**Comment by TimQSO** [comment]
Good luck with it. Solving bugs is taking so long in Magento. We've decided to migrate to Shopware 6 some time ago. Good luck!

**Comment by gorbunovav** [comment]
@engcom-Delta the documentation is misleading - this is a bug. It describes things completely unrelated to what this config option actually does:
https://experienceleague.adobe.com/en/docs/commerce-admin/stores-sales/point-of-purchase/cart/cart-configuration#quote-lifetime
