### ISSUE TITLE
Import core less files in extension

### ISSUE THREAD

**Issue by ksz2013** [magento/magento2#3288]
Hi,

Is it possible to include core standard less files into our custom module. I would like to use in my extension some predefined less variables, but i get the following message:

> File path '../../source/lib/_responsive.less' is forbidden for security reasons.

The path although is specified correctly:

> @import '../../../source/lib/_responsive.less';

Is this somehow possible, to use lib less files in the custom modules?

Thanks

**Comment by alankent** [comment]
Hi, This is an area for reporting bugs/issues with the product. The forums etc are the best place to ask such questions.

Having said that ;-), my suggestion to investigate is if you are in developer mode you might want to enable your web server to follow symlinks. I am guessing that is the security message. Not good in production, but it actually works well in dev.

**Comment by ksz2013** [comment]
HI,

Understood, and it won't happen again ;).

My only question is that if it is possible to inherit somehow less files in custom modules, because from what I see currently the framework is not allowing us to do that. 

The path is specified correctly although:

> Magento\Framework\View\Design\FileResolution\Fallback\Resolver\Simple is not allowing this
> File path '../../source/lib/_responsive.less' is forbidden for security reasons.

I know that web/css/source/_extend.less files from each module are parsed, but i would like to include a separate module and configuration specific less file.

Thanks

**Comment by alankent** [comment]
Yes. You can write your own Less files in your own module and import files from our library.  Reference a CSS file from the layout (using the <css> element in <head> of layout files). When you reference a .css file that does not exist and Magento finds a .less file with that name, we will compile the Less file for you. (You can use Grunt or Gulp as well.)

Yes, you have to get the relative path correct, as you say as well. It is relative to the directory you put your file in. I suggest putting your file somewhere, running `magento dev:source-theme:deploy', and exploring the directory structure created under pub/static/frontend/... to work out the right relative path for the directory you have put the file in. This directory structure has all the "fall back" mechanisms resolved, so you don't have to work out the rules in your head.

There is another way supported by Magento which is to add extra CSS rules to _extend.less in modules, but that is not as Grunt/Gulp friendly. (I have been blogging in this area recently on http://alankent.wordpress.com/ if you were unaware. Exploring "what really works well for developers" rather than "what Magento makes possible".)

Please note, this is really an area for reporting problems not asking support questions. The forums etc are for that. But will sneak in quick answers where possible! ;-)

**Comment by alankent** [comment]
Sorry, I think I had an old window open and may have responded twice without remembering whole thread!

I grepped the code and found the "security reasons" message in our code. I need to work out what the security issue is. (You might be able to try Grunt or Gulp in the mean time to bypass our engine - but I have not tried that.)

**Comment by dmitrii-fediuk** [comment]
https://github.com/magento/magento2/issues/2264

**Comment by alankent** [comment]
Ah, thank you. Yes there are a few occurrences of the same problem I see. Let me dig a little - I want to know the answer myself.

**Comment by alankent** [comment]
Well, I might have found a workaround until we resolve the issue correctly.

The reason for the error message is the current code does not like the "../" in the imported path. There is a way around this problem which is to declare a variable to hold the "../" and reference that variable in the import command. If you grep through our less files you will see a few occurrences using @{baseDir} in import paths.

So instead of

```
@import '../../../source/lib/_responsive.less';
```

Try something like

```
@baseDir: '../../../';
@import '@{baseDir}source/lib/_responsive.less';
```

We do still need to review this area, but in my testing this will get around the problem in the short term.

**Comment by eug123** [comment]
Internal ticket MAGETWO-48840 created

Thank you

**Comment by ksz2013** [comment]
Hi

Thanks Alan, i will give it try.

**Comment by giacmir** [comment]
Hi Alan,
your workaround works fine for me in _developer mode_, but if I go in _production mode_ and compile assets with `setup:static-content:deploy` it fails with:

`File ../../css/source/lib/_lib.less not found.`

**Comment by imisnik** [comment]
I managed import less file in my extension styles like:
`@import '../../../../../../../../lib/web/css/source/lib/_variables.less';`
`@import '../../../../../../../../lib/web/css/source/lib/_responsive.less';`

But, I have another problem with importing less files from custom theme directory `/app/code/design/frontend/MyVendorName/theme`

I tried something like:
`@import '../../../../../../../design/frontend/MyVendorName/theme/web/css/source/_extend.less';`
but I got error: 
`File path '/var/www/magento2/app/code/MyVendorName/ExtensionName/view/frontend/web/../../../../../../design/frontend/MyVendorName/theme/web/css/source/_extend.less' is forbidden for security reasons. [] []`

**Comment by magento-engcom-team** [comment]
@ksz2013, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
