### ISSUE TITLE
CMS menu issue - Luma Theme

### ISSUE THREAD

**Issue by addison74** [magento/magento2#32926]
Luma Theme needs a check for different sizes of the screen.  In order to reproduce this issue click in the footer the linked named **Privacy and Cookie Policy** then resize the browser window. Bellow you may find how is looking the CMS menu when the size of the screen is a small one.

![Screenshot 2021-05-02 152055](https://user-images.githubusercontent.com/8360474/116813052-8b746700-ab5a-11eb-905d-98028d742659.jpg)

This is happening when the menu is visible.

![Screenshot 2021-05-02 152034](https://user-images.githubusercontent.com/8360474/116813055-90d1b180-ab5a-11eb-824a-c6fc918b74df.jpg)

A change in the padding value at the bottom will fix this.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42155` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by gabrieldagama** [comment]
Hi @ADDISON74. Thank you for your report. 
The issue has been fixed in magento/magento2#32927 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [7f1092ec7352065439463fd997ea60347e42ae79](https://github.com/magento/magento2/commit/7f1092ec7352065439463fd997ea60347e42ae79)

The fix will be available with the upcoming 2.4.3 release.
