### ISSUE TITLE
moved element after before not working

### ISSUE THREAD

**Issue by shinethazhava** [magento/magento2#3296]
`
<referenceContainer name="header.panel">
            <block class="Magento\Framework\View\Element\Template" name="theme.nav.toggle" template="Magento_Theme::html/header/navtoggle.phtml" before="minicart" />
        </referenceContainer>
<move element="minicart" destination="header.panel" before="-" />`
Not render block content before minicart

**Comment by andimov** [comment]
@shinethazhava 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ser14joker** [comment]
you need to override 'default.xml' file which is located in module-theme folder. and past the code below into your file .
`<?xml version="1.0"?>
     <page>
    <referenceContainer name="header.panel">
    <block class="Magento\Framework\View\Element\Template" name="theme.nav.toggle" template="Magento_Theme::html/header/navtoggle.phtml" before="minicart" />
    </referenceContainer>
    <move element="minicart" destination="header.panel" before="-"/>
   </page>`
it works for me .

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
