### ISSUE TITLE
Wrong discount calculation when using multiple fixed discount cart rules

### ISSUE THREAD

**Issue by tiagosampaio** [magento/magento2#32964]
### Preconditions (*)

1. I believe that this happens to any Magento version but I'm using 2.3.7 Commerce Edition currently
2. Create two products with the base price of $19.00 each. Both products must be available to be purchased in the front store.
3. Create two cart discount rules
4. The first cart rule will apply a fixed discount amount of $10.00 to the whole cart. Define a specific coupon code to activate this rule in the shopping cart
5. The second cart rule will apply a fixed discount amount of $18.00 to only one of the products in the cart. This cart rule must be applied automatically to the customer's cart
6. Both cart rules must be active

### Steps to reproduce (*)

1. Go to the front store and add the two products in the cart, each one with the price of $19.00 (total $38.00)
2. Go to the cart
3. You should be able to see the second rule already applied and a discount of $18.00 must be visible.
4. In the shopping cart, apply the coupon code to activate the fixed $10.00 discount rule in the cart.
5. You'll be able to see the total discount applied is $24.00 while it should be $28.00
6. The cart total is shown as $14.00 but the correct value should be $10.00

### Expected result (*)

1. The discount amount should be $28.00 in total.

### Actual result (*)

1. Only a $24.00 discount is applied.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment]
Hi @tiagosampaio  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue. Looks like we miss some important preconditions, so may you please recheck and update description?
After following steps from the ticket, result is:

![Screenshot from 2021-05-07 10-51-25](https://user-images.githubusercontent.com/60198413/117416607-35207300-af22-11eb-87de-4ea27bf6d6fe.png)

**Comment by tiagosampaio** [comment]
@engcom-Oscar any update on this?

**Comment by engcom-Oscar** [comment]
@tiagosampaio Thank you for your reply, with more detailed steps I was able to reproduce this issue and confirmed it.

**Comment by engcom-Foxtrot** [comment]
The issue is caused by calculation in \Magento\SalesRule\Helper\CartFixedDiscount::getDiscountAmount, where the whole cart price discount is divided between all cart items.

**Comment by engcom-Oscar** [comment]
### Preconditions (*)

1. Magento version 2.4-develop 
2. Create two products with the base price of $19.00 each. Both products must be available to be purchased in the front store.
3. Create first cart rule will apply a fixed discount amount of $10.00 to the whole cart. Define a specific coupon code to activate this rule in the shopping cart
4. Create second cart rule will apply a fixed discount amount of $18.00 to only one of the products in the cart. This cart rule must be applied automatically to the customer's cart


### Steps to reproduce (*)

1. Go to the front store and add two created products to the cart, each one with the price of $19.00 (total $38.00)
2. Go to the cart page 
3. Apply the coupon code to activate the fixed $10.00 discount rule in the cart.

### Actual result (*)

Primarily discount calculating by second rule ($10 for whole cart by coupon) and it using formula summ of discount divided on qty of order items - $10 \ 2 = $5 on each product. This make price of both product $19 - $5 = $14, and subtotal of the cart = $28. After this first cart rule applying (minus $18 for one of the product), but because our product price only $14, so discount is only $14, so the product price became 0. Terefore only $24 discount is applied, and the cart total is shown as $14.00.

### Expected result (*)

1. The discount amount should be $28.00, so cart total should be $10.00.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @tiagosampaio ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce -**
1. Create two products with $19 as price
2. Create two Cart Price Rules:
The first rule is applied only to the product product2 (filtered in the actions section)
Applies a fixed discount of $18 on the product's price.
![image](https://github.com/user-attachments/assets/300fca75-3b9b-4b1b-a994-1549f47a5b1d)
3. The second one applies a fixed discount of $10 to the whole cart.
4.  With all set then go to the storefront and add product1 and product2 to the cart.
5. Go to the shopping cart page and you'll be able to see the discount of -$18.00 already applied because product2 is in the cart.
6. Apply the coupon code to the cart
7.  Check the discount amount now
8. Discount is displaying expected as $28
![image](https://github.com/user-attachments/assets/fcc3d24c-0e26-49b2-9352-ba622398b242)
Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.
Thanks.

**Comment by tiagosampaio** [comment]
@engcom-Delta, this still happens in version `2.4.7-p1`.

I have the following cart rules created:

![image](https://github.com/user-attachments/assets/75bda8ec-2d10-4c81-a0fc-f86ec3ec6566)

### Fixed $10.00 to the whole cart

![image](https://github.com/user-attachments/assets/9d8ce373-6c28-4d29-9fd1-980d3cdc5d41)

### Fixed $18.00 to a particular category

![image](https://github.com/user-attachments/assets/9b0d9b24-0fcc-4e66-8f2a-1cc2e9191932)

When I go to the cart page and add the products to my cart I have the following result:

![image](https://github.com/user-attachments/assets/8930c356-bbce-40b4-a2f4-30a467816b53)

The total discount applied to my cart should be `$28.00`, not `$23.19`.

The `Testing Product #2` should receive a fixed $18.00 discount amount, because it belongs to category #4, and the $10.00 should be applied to the whole cart after adding the `MY10` discount coupon, according to my rule.

![image](https://github.com/user-attachments/assets/60284696-3ccd-4d6c-a860-601a6985e27c)

Thanks.
