### ISSUE TITLE
Order moves to complete state if items are refunded but shipping is not.

### ISSUE THREAD

**Issue by jasonrgd** [magento/magento2#33012]
If an order is refunded but the shipping of the order is not. then the order moves to a complete state. 
Is this by design? Only shipped orders should move to complete state right ?

**Comment by engcom-Oscar** [comment]
Hi @jasonrgd! According to https://docs.magento.com/user-guide/sales/credit-memo-create.html, after creating Credit Memo and refunding, order should get "Complete" status. As you may see, it not possible to do shipping with such order as well, because order is "finalized". 
So, I have to close this ticket as non-issue.

**Comment by simonrl** [comment]
@engcom-Oscar sorry but I have to add another question here.

An order which has been refunded should move to "closed" state, not "complete".
"complete" should be for orders which are completed.
"closed" should be for orders with an invoice which was refunded.
"canceled" should be for orders without and invoice which were cancelled (no refund necessary without an invoice).
