### ISSUE TITLE
Allow Dynamic Media URL in Products and Categories setting gone?

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#33089]
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)
1. Create category.
2. Add content to the category with an image.

### Expected result (*)
1. At the frontend image is visible for that category page.

### Actual result (*)
1. Dynamic media url is not generated, so image is broken.

There should be a setting in Stores -> Configuration -> Catalog which is called "Allow Dynamic Media URL in Products and Categories" but this seems to be removed? Or at least this option does not exist for me. How could we use dynamic media in category and product pages?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jorgb90** [comment]
@magento give me 2.4-develop instance

**Comment by jorgb90** [comment]
Option is indeed missing in newer versions:

![Schermafbeelding 2021-05-28 om 09 33 33](https://user-images.githubusercontent.com/7294081/119949221-f2d6d880-bf99-11eb-9b39-414356f4e8ad.png)

But media urls in category pages are working:

![Schermafbeelding 2021-05-28 om 09 35 52](https://user-images.githubusercontent.com/7294081/119949257-fec29a80-bf99-11eb-852b-90cd55bd7363.png)

![Schermafbeelding 2021-05-28 om 09 49 46](https://user-images.githubusercontent.com/7294081/119949308-0b46f300-bf9a-11eb-9bb1-3b291b48c31d.png)

Does anyone know of a recent change? How can I make this also work for our theme?

**Comment by jorgb90** [comment]
@magento give me 2.4.2 instance

**Comment by jorgb90** [comment]
Doesn't seem to be a Magento issue. Now lets find out why it isn't working for me..

**Comment by engcom-Alfa** [comment]
Hi @jorgb90 
Since it is not reproducible in our system, kindly give me more information- how you are getting it reproducible.
Your custom configurations and step by step procedure.
Else you may reset all your configurations to default and give a try once, it may help you solving your problem.
You may please refer below links as well:
https://docs.magento.com/user-guide/configuration/catalog/catalog.html

**Comment by jorgb90** [comment]
@engcom-Alfa Can you maybe help me get in the right direction by pointing what piece of code should be responsible to make this work at the frontend?

**Comment by engcom-Alfa** [comment]
As mentioned in the [AboveComment](https://github.com/magento/magento2/issues/33089#issuecomment-850258902) it is not actually a Magento issue. I tried reproducing and it is not reproducible as well in the 2.4-develop version.
You may please upgrade to current 4.2-develop version to come out of this issue.
Due to your custom theme, you might even required to re look into the configurations as well, you may also refer https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/theme-create.html
For any Magento relevant issue, kindly report a ticket with detailed steps to reproduce.
Thanks
