### ISSUE TITLE
Rss Category not working

### ISSUE THREAD

**Issue by hryvinskyi** [magento/magento2#33116]
### Preconditions (*)

1. Magento 2.4.2-p1
2. PHP 7.4.15

### Steps to reproduce (*)

1. Enable standard Rss Feed module.
2. Enable Rss Feed for Top Level Category
![image](https://user-images.githubusercontent.com/9294098/120318384-753c0100-c2e8-11eb-8e5d-7cd2459d71b7.png)
3. Go to category page -> click on Subscribe to RSS Feed link
![image](https://user-images.githubusercontent.com/9294098/120318735-debc0f80-c2e8-11eb-8a60-93b6238ae98d.png)

### Expected result (*)

1. List of products:
![image](https://user-images.githubusercontent.com/9294098/120319176-66098300-c2e9-11eb-964b-34444673710b.png)

### Actual result (*)

1. Empty product list:
![image](https://user-images.githubusercontent.com/9294098/120319286-85a0ab80-c2e9-11eb-9efd-53e8ef009c8e.png)

### What i found (*)
If i comment line `->addAttributeToSort('updated_at', 'desc')` in file `vendor/magento/module-catalog/Model/Rss/Category.php`

![image](https://user-images.githubusercontent.com/9294098/120319517-c4cefc80-c2e9-11eb-88e3-e4e6743569cc.png)

list of products will appear

**Comment by engcom-Echo** [comment]
Hi @hryvinskyi 

We are not able to re-produce the issue with the given steps. In our case Rss feeds is showing the products without commenting the code.

<img width="1364" alt="Screenshot 2021-06-02 at 5 23 23 PM" src="https://user-images.githubusercontent.com/51681435/120475853-8576dd80-c3c7-11eb-957b-bed8bee32c1c.png">

<img width="629" alt="Screenshot 2021-06-02 at 5 23 36 PM" src="https://user-images.githubusercontent.com/51681435/120475884-8f98dc00-c3c7-11eb-9840-a98829b6c71f.png">

Request you to kindly test this issue on lates branch i.e. 2.4-develop or provide us more input so that we can reproduce the same on our system.

Thanks

**Comment by engcom-Echo** [comment]
Hi @hryvinskyi ,

We are closing this issue , as there has been not much update on it. 
If you are still getting this issue please comment.

Thanks

**Comment by Djohn12** [comment]
If anyone is looking for a fix, there is an official adobe quality patch on the subject available at https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-28/acsd-48866-error-when-requesting-rss-feed-for-categories.html
