### ISSUE TITLE
Category with url_key "publication" getting 404

### ISSUE THREAD

**Issue by gexxx05** [magento/magento2#33215]
### Preconditions (*)
Vanilla Magento 2.4.2

### Steps to reproduce (*)
1. Go to Catalog > Categories > Add new subcategory > Name it "Publication" > Save
2. Go to frontend and open newly created category "Publication"

### Expected result (*)
You can see the newly created category and get a 200 OK.

### Actual result (*)
You will get a 404 Not found. 
![screen01](https://user-images.githubusercontent.com/16879037/121658419-9d262400-caa1-11eb-9c24-a6fa994b936c.jpg)

If i rename it to "Bublication" it is working.
![screen02](https://user-images.githubusercontent.com/16879037/121658515-b0d18a80-caa1-11eb-844a-ed1c2040ae4e.jpg)

I think the problem is because of the root folder "pub". The function which is causing this is located in \vendor\magento\framework\HTTP\PhpEnvironment\Request.php getBaseUrl() on line 795.
![screen03](https://user-images.githubusercontent.com/16879037/121658724-e6767380-caa1-11eb-8368-ac287786ad3a.jpg)

**Comment by engcom-Echo** [comment]
Hi @gexxx05 ,

I have followed the steps provided but was not able to reproduce the issue. Please find the attached screenshot
<img width="1305" alt="Screenshot 2021-06-11 at 2 38 43 PM" src="https://user-images.githubusercontent.com/51681435/121662268-c1dec380-cac2-11eb-8c8e-9936edb16f7c.png">

<img width="1014" alt="Screenshot 2021-06-11 at 2 37 39 PM" src="https://user-images.githubusercontent.com/51681435/121662280-c60ae100-cac2-11eb-90f2-fe0a9c7e37f1.png">

Request you to kindly test the issue on latest magento version 2.4-develop or kindly provide more details so that we can reproduce the same.

Thanks

**Comment by gexxx05** [comment]
Hi @engcom-Echo,

I have installed M2.4.2 with composer.
Here are some screenshots of debugging the function getBaseUrl() in \vendor\magento\framework\HTTP\PhpEnvironment\Request.php.

![screen01](https://user-images.githubusercontent.com/16879037/121667484-9d76ed00-caaa-11eb-9e40-aadd3debeeeb.jpg)

With category url_key "publication":
 `$this->getRequestUri()` is `/publication`
`$url` is `/pub`
![screen02](https://user-images.githubusercontent.com/16879037/121667710-db741100-caaa-11eb-9b48-a95bff45b73d.jpg)

With category url_key "bublication":
 `$this->getRequestUri()` is `/bublication`
`$url` is empty
![screen03](https://user-images.githubusercontent.com/16879037/121667969-1aa26200-caab-11eb-9721-f49a0199696d.jpg)

I don't know why it is not reproduceable on your side. We have it on all our M2.4.2 instances. It started when the main htaccess was moved to /pub folder in M2.4.1 i think.

**Comment by mrtuvn** [comment]
what server that you used ? nginx, apache
Check .htaccess in magento root (It's should point to pub folder)
since magento updated root to pub. So i think lot of server infra not update it's follow magento approach
Some links for your reference
https://devdocs.magento.com/guides/v2.4/install-gde/tutorials/change-docroot-to-pub.html
https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-2.html#known-issues

**Comment by gexxx05** [comment]
Yes, we have a nginx, apache server.
We changed the document root in virutal host to /pub and now it is working.

Thanks a lot.
