### ISSUE TITLE
unsubscribe link doesn't work anymore

### ISSUE THREAD

**Issue by LeoNun** [magento/magento2#33310]
Hello, I´m having an issue since I installed magento 2.4, and now still have the problem in magento 2.4.2-p1. The unsubscribe link doesn't work in the newsletter since magento 2.3.5.

The unsubscribe link for both is the same, {{var subscriber.getUnsubscriptionLink()}}

When I check over the unsubscribe link in a newsletter sent with magento 2.4.2 I get a blank page, as it fallows:

![1](https://user-images.githubusercontent.com/56118723/122756151-f0605980-d28d-11eb-874b-ad98c7d8d698.jpg)

Before in magento 2.3.5, a link was generated to unsubscribe, as:

![2](https://user-images.githubusercontent.com/56118723/122756168-f6563a80-d28d-11eb-8673-7266029d162b.jpg)

I've found some people with the same issue but nothing in concret to solve the problem.

Is this a bug already reported? Any solution?

Please find more details about the issue below:
https://github.com/magento/magento2/issues/33310#issuecomment-865098873

Best Regards,
Leonel Nunes

**Comment by LeoNun** [comment]
Hello,
I also noticed that cheking the client page in the admininistartion shows that a user who is registered in magento is not.
Althow the page is not messed anymore (like prvious version 2.4.1), there is still this problem.

Best regards,
Leonel Nunes

**Comment by LeoNun** [comment]
Hello,
I can confirm that the problem of the customer edit page is fixed, so it displays as it showld but the unsubscription doesn't work.

Best regards,
Leonel Nunes

**Comment by engcom-November** [comment]
Verified the issue on latest Magento version 2.4.2 and the issue is reproducible.
Blank page is displayed in the news Letter. Unsubscribe link is not getting displayed.
**Preconditions:**
Email configuration is setup on Magento (Ex: SMTP Gmail configuration)
**Steps to reproduce:**
1. Magento Admin -> Customers -> All Customers -> Edit the Customer -> News Letter -> Subscribe to NewsLetter and save
2. Marketing -> News Letter Template -> Add new template
3. Marketing -> News Letter Template -> Actions -> Queue News Letter - edit and Save News Letter
4. News Letter should be triggered to the Customer email ID. If not triggered, run magento cron job: sudo php bin/magento cron:run, emails would be triggered automatically after running cron.
**Issue:** Blank page is displayed in News Letter email. Unsubscribe link is not displayed for any of the below configurations:
![image](https://user-images.githubusercontent.com/60198231/122782521-6a183780-d2ce-11eb-8f28-bcdd74a4c8fc.png)
Also tried with below configurations in Queue information page but still blank page is getting displayed in email.
<a href="var subscriber.getUnsubscriptionLink()">
var subscriber.getUnsubscriptionLink()
</a>

Or
a href="{{var subscriber.getUnsubscriptionLink()}}">Unsubscribe</a>

![image](https://user-images.githubusercontent.com/60198231/122782957-c4b19380-d2ce-11eb-95d4-063aaba61017.png)

**Comment by LeoNun** [comment]
Hello,
thank for the onfirmation, I will wait for an hot fix for this issue.

Best regards,
Leonel Nunes

**Comment by SilinMykola** [comment]
@magento I am working on this

**Comment by LeoNun** [comment]
Hello,
is this solved in magento 2.4.3 ?

Best regards,
Leonel Nunes

**Comment by shane-clickingmad** [comment]
> Hello,
> is this solved in magento 2.4.3 ?
> 
> Best regards,
> Leonel Nunes

Doesn't appear so no

**Comment by MakoWish** [comment]
I see this is closed, but I am running into the same issue with 8.4.4. The unsubscribe link is not being generated on Newsletter emails. I have not yet tried other emails.

**Comment by norgeindian** [comment]
@MakoWish , it is now generated using another syntax:

`<a href="{{var subscriber_data.unsubscription_link}}">{{var subscriber_data.unsubscription_link}} </a>` works for me.
