### ISSUE TITLE
no more "Add Block Names to Hints"?

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#33323]
It seems "Add Block Names to Hints" was removed and now only the class types are shown which is not that helpful in many cases.

Was this changed in the past? If so, why? And how can we reintroduce the display of the block names to reference them in layouts?

### Preconditions (*)

1. Magento 2.4.2
2.

### Steps to reproduce (*)

1. go to developer settings in the backend
2. search for "Add Block Names to Hints" in the debug section (there is only "Add Block Class Type to Hints")

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)
![grafik](https://user-images.githubusercontent.com/827205/123072447-d6ea1980-d415-11eb-8094-8f78df889fa8.png)

It seems the old option is still in the translation files but not used (probably not cleanly removed).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DanielRuf** [comment]
Block names are still mentioned at https://docs.magento.com/user-guide/configuration/advanced/developer.html and https://docs.magento.com/user-guide/system/template-path-hints.html, but the screenshots clearly don't show such option.

**Comment by rimmeh** [comment]
that confused me too many times, finding block names in m2 is a pain

**Comment by mrtuvn** [comment]
https://github.com/vpietri/magento2-developer-quickdevbar
Used this one for quick check. Default feature from magento seem not enough for developer

**Comment by rimmeh** [comment]
thanks mrtuvn, its a nice plugin, but it does not show xml block names too

**Comment by engcom-November** [comment]
@DanielRuf 

I tried verifying when the system.xml was last modified and who the author of the modifications was and found the Github commit with changes: Removed "Add Block Names to Hints" and added  "Add Block Class Type to Hints" with reason: Renamed config setting to represent what it actually does:
"This config name is notoriously misleading as it does not show the block name at all, instead it shows the block class type. Worse still there is a question about this in the Magento2 certification exam which is utterly confusing due to the poor naming of the config setting."
[Github commit](https://github.com/magento/magento2/commit/7238228429b1)
Please find the screenshot of the same below:
![image](https://user-images.githubusercontent.com/60198231/124452594-26303280-dda4-11eb-88c1-2cdff13995e9.png)

**Comment by DanielRuf** [comment]
Ok, thanks for the information and the link to the commit with the changes. So it seems the docs are outdated and have to be accordingly updated.

I was pretty sure that in 2017 or earlier we had the option to show the block names and there were also block names shown. The logic was maybe changed and the option not renamed.

**Comment by engcom-November** [comment]
Hi @DanielRuf,
Thanks for your update. I have created this [Github issue](https://github.com/magento/devdocs/issues/9047) to correct/update the user docs wrt this feature. Hence we are closing this issue.

Thank you.
