### ISSUE TITLE
Inheriting from a class that doesn't exist

### ISSUE THREAD

**Issue by Qikerz** [magento/magento2#33334]
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php#L151

Preconditions:
Install Magento 2.4-develop

Steps to reproduce :
1. Open file magento2/app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php
2. Check line number 151
3. It has a function call getPrice(BundleDiscountPrice::PRICE_CODE), with reference of BundleDiscountPrice class

Expected Result;
The class BundleDiscountPrice must be declare.

Actual Result:
This class is not defined

**Comment by engcom-Hotel** [comment]
Hi @Qikerz ,

We have checked this issue in Magento 2.4-develop branch. As per the stated file i.e.[https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php#L151](url), has a function call of getPrice which requires a string type of argument and it is passing **BundleDiscountPrice::PRICE_CODE** as an arguement.

It seems that, the class **BundleDiscountPrice** is not defined. Are you talking about the same issue?

**Comment by Qikerz** [comment]
Hi @engcom-Hotel,

Yes that's right.

Also, there is no **calculateDiscount** function that takes a float argument **$configuredOptionsAmount**.

**Comment by engcom-Hotel** [comment]
Hi @Qikerz ,

Based on the comments, I am confirming this issue.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42711` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by monteshot** [comment]
@magento I’m working on it

**Comment by monteshot** [comment]
@magento I am working on this

**Comment by monteshot** [comment]
@magento add to contributors team

**Comment by monteshot** [comment]
@magento I am working on this

**Comment by sidolov** [comment]
Hi @Qikerz. Thank you for your report. 
The issue has been fixed in magento/magento2#33449 by @monteshot in 2.4-develop branch
Related commit(s):
 - [f649582fcefe166fc20d365a017d3cb7edc22aa9](https://github.com/magento/magento2/commit/f649582fcefe166fc20d365a017d3cb7edc22aa9)
 - [a1575f70569a14012c1146aa832f3572963e3497](https://github.com/magento/magento2/commit/a1575f70569a14012c1146aa832f3572963e3497)
 - [3a92f3e78b15b54268b1ed8ac7eb33758a4e2843](https://github.com/magento/magento2/commit/3a92f3e78b15b54268b1ed8ac7eb33758a4e2843)
 - [c717b3466b3bf2fc2adaf7335186602f840defcf](https://github.com/magento/magento2/commit/c717b3466b3bf2fc2adaf7335186602f840defcf)
 - [995cb2a8687948e805e28344977d698854c7a3ff](https://github.com/magento/magento2/commit/995cb2a8687948e805e28344977d698854c7a3ff)
 - [b0c21333b445699de8468940a3535c4d98c39fe8](https://github.com/magento/magento2/commit/b0c21333b445699de8468940a3535c4d98c39fe8)
 - [1aa93e06373dc6aafe299d37c4e76aa5fbbc868b](https://github.com/magento/magento2/commit/1aa93e06373dc6aafe299d37c4e76aa5fbbc868b)
 - [33914c154dd2f04ff29d9a547c81b02e0dcd428f](https://github.com/magento/magento2/commit/33914c154dd2f04ff29d9a547c81b02e0dcd428f)
 - [0f32c4d1f2dd3177bf0eef2dc7f7f27921c9d9e1](https://github.com/magento/magento2/commit/0f32c4d1f2dd3177bf0eef2dc7f7f27921c9d9e1)
 - [72facef7b43d5999d9848f5aa428cbf6559fc0b0](https://github.com/magento/magento2/commit/72facef7b43d5999d9848f5aa428cbf6559fc0b0)
 - [e1b094b29f5ce0874df95a132bd9614c62d19eac](https://github.com/magento/magento2/commit/e1b094b29f5ce0874df95a132bd9614c62d19eac)
 - [962543624be48b904af16ca2495eab12fff44a31](https://github.com/magento/magento2/commit/962543624be48b904af16ca2495eab12fff44a31)
 - [f34f5c8acfc60daeff03a419c1e1d291fdf3e0f9](https://github.com/magento/magento2/commit/f34f5c8acfc60daeff03a419c1e1d291fdf3e0f9)
 - [2ec38bc83d89542435ce024de2b209dd1c999052](https://github.com/magento/magento2/commit/2ec38bc83d89542435ce024de2b209dd1c999052)
 - [0669115786d5819b235f975cd932a44f748600dd](https://github.com/magento/magento2/commit/0669115786d5819b235f975cd932a44f748600dd)

The fix will be available with the upcoming 2.4.3 release.
