### ISSUE TITLE
Magento 2 Integration Resources Aren't Respected

### ISSUE THREAD

**Issue by AngelsDustz** [magento/magento2#33347]
### Preconditions (*)

1. Magento 2.4.2-p1

### Steps to reproduce (*)

1. Create a new integration
2. Give it limited right (catalog -> inventory -> products)
    
![Screenshot from 2021-06-25 08-18-24](https://user-images.githubusercontent.com/4640484/123379154-02900f80-d58e-11eb-88e9-b58daef7cbac.png) 

3. Do *not* give it access to "Update Attributes"

### Expected result (*)

1. The API is not allowed to update product attributes.
2. Some 403/401 error is returned by the API.

### Actual result (*)

1. The API updates product attributes.

What I believe is happening is that it is getting recursive rights, so if you select products it gets all of it under it too. But I need a read-only integration so it seems natural that if the "Update Attributes" is not checked it can not do that.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
@nathanjosiah

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project AC as Bug

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:

**Steps to reproduce:**
Admin - System - Extensions - Integrations - Add new Integration/edit existing integration
API - Resource Access - custom and Give it limited right (catalog -> inventory -> products)
Do not give it access to "Update Attributes" and Save
Reindex and clear cache
Generate Admin access token  using POST /rest/default/V1/integration/admin/token
Send PUT request to update exising product attributes using: /rest/default/V1/products/attributes/{attribute-code}
**Issue: Response retrieved with 200 status code**
However, the updated changes are not reflected in UI
![image](https://user-images.githubusercontent.com/60198231/134335030-8a1a1461-0e81-4420-88fd-61b1973bebcb.png)
![image](https://user-images.githubusercontent.com/60198231/134335082-2d2b551e-6464-449b-b6e0-bab4cfe957a1.png)

**Comment by hostep** [comment]
It looks like this is the merge commit with a fix for this: https://github.com/magento/magento2/commit/c7e5002e587dd908643de491850c673701758564 (all commits: https://github.com/magento/magento2/search?q=AC-1316&type=commits)
