### ISSUE TITLE
Magento Media Query Function ".media-width" not working

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#33441]
### Preconditions (*)

1. 2.4.2

### Steps to reproduce (*)

1. Create a module
2. Add this file to it:

## MODULE/view/frontend/web/source/_module.less

```
.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__l) {
	body.checkout-index-index {

	    #foobar {
		background: #bbb;
	    }
	}
}
```
3. Compile 
4. Load website
5. View source
6. inspect styles-l.css and styles-m.css and search for "foobar"

### Expected result (*)

1. Code should be in the files

### Actual result (*)

1. Code is no where

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
have you try .media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {}

**Comment by mrtuvn** [comment]
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/responsive-web-design/rwd_css.html

**Comment by Eddcapone** [comment]
@mrtuvn I need `screen__l` not `screen__m`

**Comment by mrtuvn** [comment]
if you go for that approach you will have overlap styles of mobile too
.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
<= 768
} and here
 & when (@media-common) {both mobile/desktop}
In case you want to try you can use

**Comment by mrtuvn** [comment]
you may also want to try this 
& when (@media-target = 'mobile'), (@media-target = 'all') {
    @media only screen and (max-width: (@screen__l)){ }
}
I think it may work too. This will use native media query

**Comment by engcom-Lima** [comment]
Hi @Eddcapone,

Please place your _module.less file in below dir:
**<your_theme_dir>/Magento_Review/web/css/source/_module.less**

And your code for screen_l will work on 1024px screen.

I was able to get foobar inside screen_m.css on 2.4-develop branch with your code due to my screen size. Please find attached screenshot of the same:

<img width="1172" alt="Screenshot 2021-09-06 at 5 13 38 PM" src="https://user-images.githubusercontent.com/60198022/132214366-dd73bc54-2083-42aa-8b81-36da8b7166c5.png">

Please find more info for your reference on https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-guide/css_quick_guide_approach.html

This does not look like Magento Dev issue to me. If you still think this is Magento Dev issue, please update description with more details or otherwise we'll have to close this issue.

**Comment by engcom-Lima** [comment]
Hi @Eddcapone,

We have noticed that this issue has not been updated for some time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
