### ISSUE TITLE
Multiselect attribute, not all options are saved in database. 

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#33486]
### Preconditions (*)

1. Magento 2.4.2, 
2. Magento 2.4.1, 
3. Magento 2.4.2-p1, 
4. Magento 2.3.x

### Steps to reproduce (*)

1. Create a new `multiselect` attribute
2. Add at least **150** options to an attribute
3. Add an attribute to main attribute set
4. create a product and assign ALL options to the product 

### Expected result (*)

1. All options are selected (as they are not saved) in `catalog_product_entity_text` table as in Magento 1 (or propose a different solution)

### Actual result (*)

1. Attribute options are saved in `catalog_produdct_entity_varchar` table 
2. not all options are saved when you reopen the product in Admin

This is basically a copy of this issue:
https://github.com/magento/magento2/issues/24199

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by qsolutions-pl** [comment]
You can cleary see the issue if you look in the database, `value` limit is 255 characters in `catalog_product_entity_varchar`
![image](https://user-images.githubusercontent.com/4256191/125753118-3475beba-6338-4bd4-8975-3e9c3865436d.png)

**Comment by qsolutions-pl** [comment]
Since this is a critical issue, it affects the entire framework functionality for products with multi select attributes and it got NONE attention from M2 CORE TEAM, I'm closing this issue and related Pull Request.

**Comment by sidolov** [comment]
Hi @qsolutions-pl. Thank you for your report. 
The issue has been fixed in magento/magento2#33487 by @qsolutions-pl in 2.4-develop branch
Related commit(s):
 - [16ef8b1e28bd92f3ee086d8181c398cc47a45207](https://github.com/magento/magento2/commit/16ef8b1e28bd92f3ee086d8181c398cc47a45207)
 - [2be10b7f4aeb1779356fafbd65ad1c8d2d95dd58](https://github.com/magento/magento2/commit/2be10b7f4aeb1779356fafbd65ad1c8d2d95dd58)
 - [82f040f3f17da08d6af0d51c0f5ed33abd94d040](https://github.com/magento/magento2/commit/82f040f3f17da08d6af0d51c0f5ed33abd94d040)
 - [c78a5a6b02631736b6ef655d0c0c585292adc170](https://github.com/magento/magento2/commit/c78a5a6b02631736b6ef655d0c0c585292adc170)
 - [b638595533ab01757d407da1716098f12a4e51cf](https://github.com/magento/magento2/commit/b638595533ab01757d407da1716098f12a4e51cf)
 - [36c2c8a5a7bc2fc029dc82bcc0fc771a0b7c0dd9](https://github.com/magento/magento2/commit/36c2c8a5a7bc2fc029dc82bcc0fc771a0b7c0dd9)
 - [ddc95cc7aa0a691225c8eb8f905f735a0ee971e4](https://github.com/magento/magento2/commit/ddc95cc7aa0a691225c8eb8f905f735a0ee971e4)
 - [ddab158144b1e4cc6971bea51beb8c25cc2ebc07](https://github.com/magento/magento2/commit/ddab158144b1e4cc6971bea51beb8c25cc2ebc07)
 - [0661722901f8b6e29a207ff350297b04514cc391](https://github.com/magento/magento2/commit/0661722901f8b6e29a207ff350297b04514cc391)

The fix will be available with the upcoming release.

**Comment by atty31** [comment]
On magento 2.4.6 , I m still facing this issue

**Comment by justinaht** [comment]
Any update on EE 2.4.5-p7
