### ISSUE TITLE
An error occurred during backup

### ISSUE THREAD

**Issue by mcera** [magento/magento2#3349]
An error happened during backup of file system and data base.
SHELL: magento setup:backup --code --db

PHP Fatal error:  Call to undefined function Magento\Framework\Archive\Helper\File\gzopen() in /var/www/dev.magento/public_html/vendor/magento/framework/Archive/Helper/File/Gz.php on line 25

**Comment by hydra** [comment]
me too.

```
[Thu Mar 31 19:36:10.580727 2016] [:error] [pid 3818] [client 109.233.115.223:39392] PHP Fatal error:  Call to undefined function Magento\\Framework\\Archive\\Helper\\File\\gzopen() in /var/www/vhosts/.../shop/magento/vendor/magento/framework/Archive/Helper/File/Gz.php on line 25, referer: http://.../setup/
```

**Comment by hydra** [comment]
seems to be related to this.

https://bugs.php.net/bug.php?id=53829

IMHO the readyness check should be updated OR a workaround should be put in place.

**Comment by hydra** [comment]
this can be worked around by changing to call to `gzopen()` to `gzopen64()` in `/vendor/magento/framework/Archive/Helper/File/Gz.php`

**Comment by andimov** [comment]
@cerovicmarko 
Thank you for reporting!
Please provide more detailed info about your environment to reproduce it.

**Comment by hydra** [comment]
I was running php 5. something at the time if that helps, sorry I can't be more specific as the system has been upgraded to php7 now.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
Please also provide information about environment: versions of PHP, web-server and MySQL.

**Comment by hydra** [comment]
@veloraven great. thanks.  we both take time out to report the issue and you just close it without doing anything.  there's clearly a bug in the code.  If the code is run using the oldest supported php version you will find it will fail because php changed the gzopen() to gzopen64().

The code should be updated to check to see what php version is running and call the appropriate method.

It's a simple fix for a php dev, I know, i was one once.

**Comment by andimov** [comment]
@hydra it looks like a bug that we can fix. But, please, create the new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) with steps to reproduce and specific preconditions.

**Comment by hydra** [comment]
just reopen this one, any developer looking at this will easily be able to find the code and fix it.
- i found it from the original poster's error message and changed it temporarily myself in order to work around the issue.
- for me it occured when upgrading magento 2.01 to the latest version that was available at the time of my first comment.  probably 2.03 or something.
