### ISSUE TITLE
How to set up development environment in Mac OS X?

### ISSUE THREAD

**Issue by janghwan** [magento/magento2#3358]
I'm trying to develop Magento 2 website with my Macbook. I tried to set up local development environment using Vagrant which i used to use for other projects. 
But the problem is, shared folder performs really bad for M2 project since there are so many files that Magento reads/writes to shared source folder (which has `pub` and `var` etc. in it)
So it seems impossible to use Vagrant and shared folder for development environment.
I checked some docker approaches, but they have the same issue with source sharing.
I think this is inherent problem of magento 2 that source directory has every dynamic, static and library dependencies. (This is obvious if you see how complicate initial `.gitignore` is.)
The only option i can try is running magento natively having PHP installed on OS X, which i don't want to do because of inconsistency between production and development environment.

What am I missing here?
I would like to know how people set up development environment in Mac OS X.

**Comment by cchamikara** [comment]
try http://www.magestead.com/

**Comment by jsakars** [comment]
@janghwan I am using Mac OS X and Vagrant for Magento2 + PHP7 development with NFS shared folder(which obviously holds the source code) - works fine

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

That said :) Everyone at my company uses a vagrant based setup I created and published on my GitHub:  http://github.com/davidalger/devenv — It's using NFS to mount the source code into the VMs, which works (at least the way I've set it up) because the exports (see below) for the NFS mounts are mapping the uid/gid of all operations in the guest machine to a particular uid/gid on the host, avoiding any permissions issues you might run into if you simply deployed the files directly in the VM.

```
/Volumes/Server/sites/ -alldirs -network 10.19.89.0 -mask 255.255.255.0 -mapall=501:80
/Volumes/Server/mysql/ -alldirs -network 10.19.89.0 -mask 255.255.255.0 -mapall=501:80
```

**Comment by janghwan** [comment]
Thank you all!

**Comment by alankent** [comment]
Now that Igloczek has his new Gulp tool going, I am going to release a Docker container and suggested development approach shortly. Its designed more for learning M2 (and to help me work out problems with the approach), there may be better approaches around, but watch out for akent99 on twitter for when it is ready. Just got to find a free evening to get it done with a supporting blog post. A week at most, hopefully end of this coming weekend.
