### ISSUE TITLE
Unnecessary SQL requests during visitors log clean

### ISSUE THREAD

**Issue by ihorvansach** [magento/magento2#33613]
### Summary (*)
Cron job "visitor_clean" run the method Magento\Customer\Model\Visitor::clean() that call the next one
Magento\Customer\Model\ResourceModel::clean()

In the resource model there is a "while" loop with multiple requests that can be replaced with the single one delete SQL request

### Examples (*)
that will work faster, as will not need to run SELECT for the same "WERE" and then run additional DELETE request with condition ['visitor_id IN (?)' => $visitorIds]

### Proposed solution
I have prepared a merge request for this https://github.com/magento/magento2/pull/33614
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [+] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
Hi @ihorvansach,

I have gone through the proposed solution and comments from other members on the fix #33614 and I also think the current one will work better since deleting directly from a hugh table could take a lot more time than deleting by parts.

So for further analysis, please provide the below details:
1. Have you checked how much time existing solution is taking for cron execution ?
2. How much data are you checking the current solution on ?
3. If you have problem with any specific issue, can you please elaborate ?

**Comment by engcom-Delta** [comment]
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
