### ISSUE TITLE
the shipping information was unable to be saved. verify the input data and try again

### ISSUE THREAD

**Issue by syba786** [magento/magento2#33765]
Preconditions (*)
Magento 2.3.4 

Steps to reproduce (*)
Create a customer account
Go to my account, and add a shipping address

Add any product and go to the checkout 

Select a shipping method and click next button

Expected result (*)
Payment page should show up

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
Steps performed:
1. Created a customer account from fron-end
2. Go to my account, and added a shipping address
3. Add any product and go to the checkout
4. Select a shipping method and click next button - No issue: Payment methods displayed as expected. Also able to place Order
Note: This issue is not reproduced when new shipping Address is added during checkout - No issue
![image](https://user-images.githubusercontent.com/60198231/129192054-23ae291e-ec32-4b78-b04d-f1f9f130c22d.png)

![image](https://user-images.githubusercontent.com/60198231/129192031-67fd2d86-d821-4f7e-8114-6e72ed62f576.png)

![image](https://user-images.githubusercontent.com/60198231/129192011-d25edfe9-c7a3-4ea6-af35-0a0771788248.png)

@syba786 kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if the issue is still reproducible.
Thank you.

**Comment by lbajsarowicz** [comment]
I encountered such an issue in our Staging environment:
![image](https://user-images.githubusercontent.com/1639941/139494267-3d8fcffc-ff02-43ab-9c68-519a8dbcf36d.png)

Not sure what are the steps to reproduce the issue, however:
1. The Customer Address entity exists and it's correctly assigned to the Customer
2. Customer account exists and is active.
