### ISSUE TITLE
Custom Option selection regular price should remain same only special price should change accordingly Magento 2

### ISSUE THREAD

**Issue by vk44295** [magento/magento2#33840]
### Summary (*)
I want to change the special price only when custom option select by any customer currently both regular price and special price changed on selection. I am using Magento 2.4.2

### Examples (*)
https://myimaginecom.hyperx.cloud/mac/macbook-air/13-inch-macbook-air-512gb-space-grey-m1-2020

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @vk44295 
Thanks for reporting the issue.
However the information provided is not enough for us to check the issue.
In order to check this issue, please update below information:
Detailed Steps that you have taken to reproduce the issue.
Expected and actual results
Is issue reproducible on **2.4-develop** instance ?

Thank you.

**Comment by vk44295** [comment]
@engcom-Echo  Thanks for the support.

My issue is suppose we have a product with custom options like Mobile with some earphones or laptop with some accessories. 

Issue : 
Laptop Product
Price 5000
Selling Price: 3000

Custom Option:
1. Mouse - +300
2. Keyboard- +200

When i select currently from custom options like mouse or keyboard then custom price added to both price like below:
if select mouse
price - 5300
selling price - 3300

Expected Result: 
if select mouse:
MRP Price should be not change: 5000
Selling Price : 3300

This is my product link:
https://myimaginecom.hyperx.cloud/mac/macbook-air/13-inch-macbook-air-512gb-space-grey-m1-2020

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by vk44295** [comment]
Ok Thank you @engcom-Echo , Please let me know when you find any solutions for me.

**Comment by engcom-Echo** [comment]
The issue is confirmed on **2.4-develop** branch.
Here are the steps to reproduce the issue.
1. On a clean instance of Magento 2.4-develop branch , add few products if there aren't any present.
2. Choose a product , say **Product A of regular price $1000** Add Advancing Pricing for the Product, so as to set up a **selling price of $500**.
3. Configure custom options to the product , say for eg: **Product X @ +$100 , Product Y @ +$200**.
4. If we choose the **Product A** from front end & choose one of the custom options say Product X , then the **selling price** should be **$600** and **regular price** displayed for **Product A** should be unchanged at **$1000**. However currently the regular price of Product A is changing to **$1100**, which shouldn't happen.

**Comment by vk44295** [comment]
Dear Team,
Can you please tell me the status is it possible to do?

**Comment by vk44295** [comment]
Dear Team,
Please confirm if you can do? in last 10 days i didn't get any reply form your side.

**Comment by chernenm** [comment]
hello @vk44295,

Thank you for reporting this issue to us. But it is actually expected out of the box behavior of Magento 2, whenever custom option is selected its price is being added to the base product price.
