### ISSUE TITLE
when old media gallery is hidden and there are more than 11 items in the content menu, the submenu title doesn't show.

### ISSUE THREAD

**Issue by paresh6002** [magento/magento2#33889]
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)
1.Create any 3 submenus with titles under the content menu. Like below screenshot

![screenshort-magento-1](https://user-images.githubusercontent.com/59193951/130437923-86881a84-0f90-440b-a3d0-0721c881c2d6.png)

2. Open admin panel

3. Open configuration and navigate to this setting system→media gallery and set to “yes ” on this setting

![screenshort-magento-2](https://user-images.githubusercontent.com/59193951/130438035-aeaba2da-b40f-48dd-9220-2928387923ec.png)

4. Refresh cache after enable above setting. 

5. check submenus of the content menu. We can’t see the title of the submenus. These are hidden.

![screenshort-magento-3](https://user-images.githubusercontent.com/59193951/130438116-a2213e0f-6252-4525-a641-5f3a783723db.png)

### Expected result (*)
1. If we create new 3 submenus with title under the content menu then, the title of the submenu should be visible. Like the below screenshot.

![screenshort-magento-4](https://user-images.githubusercontent.com/59193951/130438200-32b5503b-888f-4671-910b-afef5186e135.png)

### Actual result (*)
1. content’s submenus title are hidden/missing when we add 3 submenus with title.

![screenshort-magento-3](https://user-images.githubusercontent.com/59193951/130438465-aa51fda4-38d1-4296-bf24-381974d8c80e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @paresh6002 
Thanks for reporting this issue. I was able to reproduce this issue on **2.4-develop** branch with the given steps to reproduce in the issue description.
Would like to highlight few points w.r.t issue.
1. When  **Stores -> Settings -> Configuration -> Advanced -> System -> Media Gallery -> Enable Old Media Gallery** -> set to **NO** - Then the newly added custom menu items are visible on content menu along with their title.
<img width="1351" alt="Screenshot 2021-08-25 at 11 31 51" src="https://user-images.githubusercontent.com/51681435/130746103-afa6b46d-f62f-4ba5-bf4f-4298cda8f760.png">

<img width="1351" alt="Screenshot 2021-08-25 at 11 31 31" src="https://user-images.githubusercontent.com/51681435/130745564-3001d2dc-5451-4d3e-a6cf-7dd63262d9f4.png">

2. When  **Stores -> Settings -> Configuration -> Advanced -> System -> Media Gallery -> Enable Old Media Gallery** -> set to **YES** - Then the newly added custom menu items are visible on content menu, but the submenu titles are missing
<img width="1129" alt="Screenshot 2021-08-25 at 11 35 34" src="https://user-images.githubusercontent.com/51681435/130746642-debc34fe-3865-4d33-bd99-67aa955543b1.png">

3. When  **Stores -> Settings -> Configuration -> Advanced -> System -> Media Gallery -> Enable Old Media Gallery** -> set to **YES**  & **3 new submenu item**s are added under **Design** submenu title, then also submenu titles turns out to be missing
<img width="1129" alt="Screenshot 2021-08-25 at 12 44 49" src="https://user-images.githubusercontent.com/51681435/130747130-a76fb18f-6436-4598-8689-f2ba9d3256d6.png">

4. When  **Stores -> Settings -> Configuration -> Advanced -> System -> Media Gallery -> Enable Old Media Gallery** -> set to **YES**  & **2 new submenu item**s are added under **Design** submenu title, then submenu titles are present & inference being count of item also plays importance in this issue.
<img width="1129" alt="Screenshot 2021-08-25 at 12 46 24" src="https://user-images.githubusercontent.com/51681435/130747370-ad28908e-3a19-4a5c-9345-ceaf4f6089b9.png">

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @<reporter>,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-1000 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-1000&type=commits

Based on the Jira ticket, the target version is 2.4.4.

Thanks
