### ISSUE TITLE
Magento 2.4.3 Page Builder 404 JS files

### ISSUE THREAD

**Issue by SkullXA** [magento/magento2#33881]
Magento 2.4.3 Page Builder is not working, it just shows a blank page, when I go to the console it shows this shows a bunch of 404 errors to all the .JS files

**Comment by mrtuvn** [comment]
better report issue in [https://github.com/magento/magento2-page-builder/issues](pagebuilder repo)

**Comment by engcom-Lima** [comment]
Hi @SkullXA,

The information you provided is not enough to reproduce this issue on Magento.

In order to reproduce this, please provide below information:
1. Steps to reproduce on Magento 2.4-develop instance.
2. Expected and Actual results.

Please provide necessary screenshots. And if the issue is of Magento Page Builder, please report it on repo https://github.com/magento/magento2-page-builder/issues

**Comment by engcom-Lima** [comment]
Closing this issue as there has been no update from the reporter on the same.
