### ISSUE TITLE
upgrade magento 2.4.3 allure-framework/allure-phpunit 1.4.0 requires phpunit/phpunit ^7.2

### ISSUE THREAD

**Issue by Skyfly2021** [magento/magento2#33880]
### Preconditions (*)

1.Magento 2.4.2-p1
2.php 7.4.22
3.composer 1.22

### Steps to reproduce (*)

1.composer remove magento/product-community-edition --no-update
2.composer require magento/product-community-edition=2.4.3 --no-update
3.composer update

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.
![image](https://user-images.githubusercontent.com/53896477/130339247-3690e698-8854-47c2-afa1-dc6f1cd910c3.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Skyfly2021,

Verified this while upgrading from Magento 2.4.2 to 2.4.3 and the issue is not reproducible with Composer 2.x version.
As per the devdocs, compatible/supported Composer version for Magento 2.4.2 or later versions is "Composer 2.x version". Kindly refer this [link](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) of system requirements and try upgrading your composer version to 2.x and verify this issue.

Steps performed:
On Magento 2.4.2- P1 instance - run :
>composer remove magento/product-community-edition --no-update
>composer require magento/product-community-edition=2.4.3 --no-update
>composer update - No issue
![image](https://user-images.githubusercontent.com/60198231/130610461-a238fdf4-b6a2-422a-af5a-e1c1721810df.png)

**Comment by Skyfly2021** [comment]
![image](https://user-images.githubusercontent.com/53896477/130796261-5064481e-907c-4861-a5a9-896ffdff63bf.png)
Composer 2 is not compatible with magento 2.4.2-p1, please see the attached picture.
