### ISSUE TITLE
Widget New Products showing ADD to cart even if salable QTY is 0

### ISSUE THREAD

**Issue by chequille** [magento/magento2#33911]
### Preconditions (*)

1. Magento 2.4.3
2. Using LUMA theme

### Steps to reproduce (*)

1. Insert the following widget on a CMS page: {{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="new_products" show_pager="0" products_count="4" template="product/widget/new/content/new_grid.phtml"}}
2. Set a few products as new
3. Set "Display produts out of stock" to YES
2. Make an order for one of the new products that it is going to saleable qty 0

### Expected result (*)

1. Widget should show the product which is now salabe qty 0 without the add to cart button
2.

### Actual result (*)

1. ADD to Cart button is still shown
2.

Sorry, guys, but it really seems that there is a huge problem with getting inventory information. The method $product->isSaleable() (used in a lot of templates) is returning the stock quantity and not the salable quantity.

Are you aware of this?
Are you going to fix this?
When?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by abhattGlo** [comment]
@magento give me 2.4-develop instance

**Comment by abhattGlo** [comment]
@magento give me 2.4-develop instance

**Comment by abhattGlo** [comment]
@magento give me 2.4-develop instance

**Comment by kemexyz** [comment]
What would be the pull request for this issue ? whats the solution?

**Comment by hostep** [comment]
@sdzhepa: can you help out here? See comment above. Issues should never get closed without an extra comment specifying why it got closed.

**Comment by chequille** [comment]
Hi Guys,
it is strange as always here !!!

The major problem is, that the method IsSaleable() is not returning false if salable quantity is 0

In pull request #33799 there is a change in Module/InventoryIndexer/IsSalable.php
With this, the IsSalabe method is returning false if salable quantity is 0 but not before cache is cleaned and only on catalog pages and product pages -> not here in the New Products widget.
It seems, that in this widget, another isSaleable() method is called as it is still looking for the stock quantity and not salable quntity.

As a matter of facts, handling of salable quantity is really a big bug in 2.4.3 (or let's say since 2.4.x)

I am frustrated because nobody really take this serious as I think.

I am paying since 9 months now for a VServer to be able to switch to 2.4.x but must still run my shop on a hosting server and version 2.3.x.

Very very bad.

Have a nice weekend
Chequille

**Comment by chequille** [comment]
What are you talking about?
What is a queue?
What is Rabbit MQ?

How should I do this?
I am not working on a cloud.
Explain what to do please

**Comment by hostep** [comment]
@chequille:
- Nobody mentioned Rabbit MQ, right?
- Magento Cloud has nothing to do with this
- Magento 2.3.0 introduced message queues, in the open source product the queues started being used since version 2.3.2 for various things like exporting products or generating coupon codes and stuff like that (so these can be long processes which can take a few minutes to run, those are now handled asynchronously using a queue instead of synchronously in a webserver request which can timeout if it takes too long to process).
- The consumers of the queue normally get started up by the cronjob as long as you've not overwritten the [default configuration](https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html#configuration)
- Magento comes with support for 2 kind of message queue storages, Mysql and RabbitMQ (as far as I know, only the async bulk api import uses RabbitMQ and all the other messages from queues are being stored in Mysql)
- The consumer `inventory.reservations.updateSalabilityStatus` that is mentioned above (which I have no idea of if it's related to your bug report) is using the [Mysql database (db) as queue storage, not RabbitMQ](https://github.com/magento/inventory/blob/7151b60f860a6e8c3789742ab5dd5d71268cbba6/InventoryIndexer/etc/queue_consumer.xml#L9). This consumer is part of the [MSI project](https://github.com/magento/inventory) BTW.

These are the things I can explain, not sure if this helps you further though.

**Comment by chequille** [comment]
@hostep 
Thanks for this info.
But it does only help to understand about the entries above.
At the end, Magento does have a problem with all parts using the methods IsSaleable() or IsSalable() as these methods do not look at salable quantity, they return true if stock is >0
All this is related as you mentioned to MSI.

Many users would be happy if there would finally be a solution for these bugs, but as it looks, this is far away.
For us it looks nobody really cares.
