### ISSUE TITLE
Catalog price rule promotion information is not recorded against sales order item

### ISSUE THREAD

**Issue by valdemaras-zilys-cg** [magento/magento2#33917]
### Preconditions (*)

1. 2.2.* 
2. 2.3.* 
3. 2.4.2-p1

### Steps to reproduce (*)

1. Create Catalog Rule promotion
2. Place order with the product on promotion
3. Check sales_order_item DB table for the discount information recorded

### Expected result (*)

1. Columns applied_rule_ids, discount_percent, base_discount_amount, discount_amount and other discount related fields are populated with correct information

### Actual result (*)

1. When Catalog Rule promotion is applied, the discount related fields like applied_rule_ids, discount_percent, base_discount_amount, discount_amount are not populated with values

Severity: S0 - there is no way to accurately report on sales. Currently this issue is having negative impact on finance and client relationship. No workaround that we could find.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-November** [comment]
Hi @valdemaras-zilys-cg ,
Thanks for your confirmation. Verified the issue again on Magento 2.4-develop branch and the issue is reproducible.
**Steps to reproduce:**
Create Catalog Price Rule and apply the rule (Admin - Marketing - Catalog Price Rule - Add New Rule and apply)
Reindex and clear cache
Create a simple Product and save
Front-end - Add the product to Cart - Checkout and place order. **No issue**: Catalog Price Rule is applied to the product. User is able to purchase product with discounted price.
Verify DB table: sales_order_item
**Issue**: When Catalog Rule promotion is applied, the discount related fields like applied_rule_ids, discount_percent, base_discount_amount, discount_amount are not populated with values
![image](https://user-images.githubusercontent.com/60198231/131329666-291f31c6-ed3d-42f9-81ff-1adf392559ad.png)

**Comment by chernenm** [comment]
Hello @valdemaras-zilys-cg,

Thank you for reporting this issue, but we have to close it as not a bug, since Magento Catalog Price rules are designed to be used as catalog base pricing method the same as special or tier/group price options, which means they are intended to be applied adding adding products to cart, that is why catalog rule prices are not shown in a cart as a separate discount or promotion. And changing this core behavior would be changing the catalog pricing initial concept.

**Comment by valdemaras-zilys-cg** [comment]
Hi, 

Thanks for this explanation, but could you also help me with how to identify which promotion has been applied, what was the discount and the percentage of it if there is no information in the sales table? 
There can be several promotions that apply to the same product, how to know which one has been applied?

I understand why tier pricing and special pricing might not have discount information. But struggling to understand why promotion rules are treated same way. What is the logic behind it? 

Could you please provide more information why it has been decided to not record promotion information in order item table? Was there any technical issue?

Thanks,
Valdemaras
