### ISSUE TITLE
Magento 2.4.3 Bundle Product not working with "Use Flat Catalog Product"=Yes

### ISSUE THREAD

**Issue by davidandersson1** [magento/magento2#33935]
**Preconditions (*)**
Magento Versions: 2.4.2

**Steps to reproduce (*)**
1. Admin - Stores - Configuration - Catalog - Catalog - Set "Use Flat Catalog Product" to Yes and Save
2. Reindex and Clear cache
3. Front-end - Open any Bundle Product - Issue: Below error message is displayed on UI

**Expected result (*)**
No Exception on UI

**Actual result (*)**
[2021-08-27 12:17:35] main.CRITICAL: Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Flat::getLinkField() in /var/www/html/magento2/magento243/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:1066

SKU:  24-WG080, this is the sku of sample data and throw above error on product page with flat product enabled.

![Screenshot from 2021-08-27 18-32-26](https://user-images.githubusercontent.com/49389320/131131738-61bb7027-d557-406c-9fbd-ec9a9d25e097.png)
![Screenshot from 2021-08-27 18-32-38](https://user-images.githubusercontent.com/49389320/131131746-6e169129-a585-4d77-8cb2-a8cf68301dbb.png)

Attached here some screenshots of error & how looks bundle product page.

Please note: except default magento modules, there is no any single 3rd party modules has been installed. 

It would be great if you could provide solution for this issue. looking forward to your reply!

Thanks,
David Andersson

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
**Steps to reproduce:**
Admin - Stores - Configuration - Catalog - Catalog - Set "Use Flat Catalog Product" to Yes and Save
Reindex and Clear cache
Front-end - Open any Bundle Product - Issue: Below error message is displayed on UI
![image](https://user-images.githubusercontent.com/60198231/131324627-a8b13418-156b-4d7c-ac68-9999abc3bfa0.png)

Front-end - There is no issue with Simple Products - User is able to view Simple Product Details page
Front-end - Home - Default Category view having sub root category (Ex: default) - Issue: Exception
![image](https://user-images.githubusercontent.com/60198231/131324863-df1889cf-2342-4741-ab1e-bc66cd3548cd.png)
![image](https://user-images.githubusercontent.com/60198231/131324952-0fb25a86-9919-4ba8-b3cf-3232a6dcaa6a.png)

/var/log/system.log:

![image](https://user-images.githubusercontent.com/60198231/131324743-ba37fcbb-bfda-4369-b80e-135950fa98f4.png)

**Comment by engcom-Alfa** [comment]
Lowered the priority to P3 because the feature _"Use Flat Catalog Product"=Yes_ can be used but still it is not recommended by Magento. Here is the [RefLink](https://docs.magento.com/user-guide/catalog/catalog-flat.html) .

**Comment by Kishorchhugani** [comment]
Still having this issue on Magento 2.4.6-p3
