### ISSUE TITLE
I can't login into admin after update Magento to 2.4.3: Invalid security or form key. Please refresh the page.

### ISSUE THREAD

**Issue by mahmoudbeikhit** [magento/magento2#33941]
After updating Magento from the version. 2.4.1 to 2.4.3  i can't login to Admin Page I see below error:
Invalid security or form key. Please refresh the page.

### Preconditions (*)

1.Update Magento from version 2.4.1 to version 2.4.3
2.Error appears when login to Admin Panel.

### Steps to reproduce (*)

1.Error appears when login to admin panel After i put Login information and press sign in, and i should type 2FA - Google Auth Authenticator code but it redirect with same error 

### Expected result (*)

1. Upgrade Magento to version 2.4.3 and login to Admin Panel 

### Actual result (*)

1. Invalid security or form key. Please refresh the page.

**Comment by mahmoudbeikhit** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by mahmoudbeikhit** [comment]
@magento how i can try to update magento from 2.4.1 to 2.4.3 in develop instance? and how i can enable 2FA - Google Auth on it ?

**Comment by mahmoudbeikhit** [comment]
I have disabled 2FA and the same error appear in admin page

**Comment by engcom-November** [comment]
Hi @mahmoudbeikhit ,
This issue is the duplicate of https://github.com/magento/magento2/issues/33749. Please track this ticket for all the latest updates on the same.
FYI.. Temporary workaround: Refresh the page and login again using valid credentials.
Closing this issue. Please move into https://github.com/magento/magento2/issues/33749
Thank you.
