### ISSUE TITLE
"Minimum Qty Allowed in Shopping Cart" for simple product bug when adding product more than once

### ISSUE THREAD

**Issue by Commercers** [magento/magento2#33955]
### Preconditions (*)

1. Magento CE 2.4.2-p2

### Steps to reproduce (*)

1. Set simple product to have a "Minimum Qty Allowed in Shopping Cart" >1 for example 5 
![grafik](https://user-images.githubusercontent.com/5063768/131488595-c8f88d13-2a26-49ca-865d-c4603d17a9c1.png)
2. Go to frontend to this product and add 5 pcs of this item to the cart 
![grafik](https://user-images.githubusercontent.com/5063768/131488662-6347f595-8c53-44be-b4d1-4d717ea85500.png)
3. Stay on product page and add 1 more pc to the cart 
![grafik](https://user-images.githubusercontent.com/5063768/131488707-3d86a7b3-f925-4265-9812-e0458929f7d9.png)

### Expected result (*)

1. Because the minimum qty of the item is already in the cart I expect any other qty (in this example additional 1) to be addable to the cart

### Actual result (*)

1. It is not possible to add any qty < than the minimum cart qty to the cart.
2. The error message is "The fewest you may purchase is 5."
3. When you go to cart and change the number of the qty to 6 for example it works as expected
![grafik](https://user-images.githubusercontent.com/5063768/131489455-3ae7a479-c451-4d0e-baf5-b196b84be018.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Commercers** [comment]
Issue: Clear Description

**Comment by Commercers** [comment]
#Issue: Clear Description

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:

**Steps to reproduce:**
Set simple product to have a "Minimum Qty Allowed in Shopping Cart" >1 for example 5
Go to frontend to this product and add 5 pcs of this item to the cart
Stay on same product page and add 1 more pc to the cart
Issue: Unable to add the product to cart . "The fewest you may purchase is 5" error message is displayed.
Expected behavior: Since the product with minimum quantity 5 is already in Cart, user should able to add 1 more product to Cart from Product Details page.
**Note:** On clicking cart icon and Edit Item - user is navigated to checkout/cart page having Update Cart button instead of Add to Cart button.
![image](https://user-images.githubusercontent.com/60198231/131619910-e42f50e9-e34d-49d5-9a78-ac33f0dffb70.png)

![image](https://user-images.githubusercontent.com/60198231/131620118-ebe12e6b-8e26-45fa-9be4-6cf83bfcdc14.png)
As per official user [docs](https://docs.magento.com/user-guide/catalog/inventory-product-stock-options.html), "Minimum Qty Allowed in Shopping Cart" - Determines the minimum number of the product that can be purchased in a single order.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by Bashev** [comment]
@magento I am working on this

**Comment by glo05363** [comment]
@Commercers thanks for working on the same, This reported issue is no more reproducible on 2.4-develop. Please check below screens as well:

![image](https://user-images.githubusercontent.com/87003041/226535229-a50832b2-8e98-42c3-bacf-a3dd36430152.png)
![image](https://user-images.githubusercontent.com/87003041/226535256-30320004-daeb-4d12-8afd-7250b8371df8.png)

Hence we have closed this issue.
