### ISSUE TITLE
_prepareLayout() is not able to read _data that you pass onto the block in a controller

### ISSUE THREAD

**Issue by bytes-max** [magento/magento2#33986]
### Preconditions (*)

1. Use Magento 2.4.3
2. Create a controller 
2. create your PageResult, create a blog of your choice and add data via `->setData('my_key', 'my_value');
3. in your block, create `_prepareLayout()` 
4. inside the method, do this: `$this->pageConfig->getTitle()->set(__('%1 - Test Title', $this->getData('my_key'));

### Steps to reproduce (*)

1. see preconditions

### Expected result (*)

1. The Title resolves to `my_value - Test Title`
2. `$this->getData('my_key')` returns `my_value`

### Actual result (*)

1. The title resolves to `- Test Title`
2. `$this->getData('my_key')` returns null in `_prepareLayout()` 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
First there are many way to do that
Option 1 you don't need set title from block. You can do it right in controller file
$this->_view->getPage()->getConfig()->getTitle()->prepend(__('Your Title'));
$resultPage->getConfig()->getTitle()->set('Something');
Option 2 if you want use setData from Block Class ??
Have you try use coreRegistry for set data ?
Just curious why not choose first option  or pass data from Block Class instead of Controller

**Comment by nopenopenope** [comment]
Of course I can set a static title in many different ways, but thats not the scope of this bug report. I don't want to set a static title, I want to set a dynamic title based on what the Controller is loading. 

So, in context of your questions: 
Option 1 - not applicable because of the the use case I have 
Option 2 - not applicable because of the the use case I have
Option 3 - Registry is already marked as deprecated and I am not going to develop something that will break in the future eventually 

A Block should not be responsible to check the Request parameters and do the work there, but instead, the Controller should be responsible for reading request data and just pass plain - maybe escaped - data to the Block. 

Since the data is available for the Block later on it makes no sense not to have it in the moment where we call `_prepareLayout()`.

**Comment by mrtuvn** [comment]
Hmm the fast way you still able set title dynamic from controller. Each page only have 1 title and multiple block childs. Not sure why you have extra step to set title in child block of page when result page rendered

**Comment by engcom-Lima** [comment]
Hi @nopenopenope,

I have followed the thread and I think @mrtuvn has a point. 

Why not pass data from Block Class instead of passing data from controller to block class ? 

I think there will be too many dependencies if you follow this approach. It's not the responsibility of the controller to set variables for the view. Controller set values for Models and block retrieves values from that model.

Also, you have explained that Option 1 and 2 are applicable for your use case. Can you please update the use case also in description so that we can do further analysis ?

**Comment by nopenopenope** [comment]
Hi @engcom-Lima 
I think you have misread my previous statements. They are simply not applicable because setup in XML is a static definition of a Views Title, and I have the need to have dynamic Titles, depending on the entity loaded. 
Also, you cannot set title in view itself, only when `_prepareLayout()` is called. After that, Title is *not* changed anymore. 

I have also explained why Controller is responsible for handling request and not block. Examples on this usage is commonly used inside Magento 2 Core Modules (Controller handles request, Blocks handle Block-related tasks).

**Comment by mrtuvn** [comment]
Cc: @kandy @ihor-sviziev maybe have more experiences than me at this areas. Can you guys follow up and share some thoughts

**Comment by nopenopenope** [comment]
HI @engcom-Lima,

thanks for your effort! I've tried to solve my problem via the _prepareLayout() logic in the block itself, however, if the solution you provided is working as well we can also go with that. However, the main question is still open: why can the Block in _prepareLayout() not access the proper data, passed to the Block via setData() for example. But maybe I am lacking understanding of the Framework here.

**Comment by mrtuvn** [comment]
Short Answer: limitation . I'm not sure why layout not able to access data. Maybe it's doesnt have to be able access to such data

**Comment by engcom-Lima** [comment]
Hi @nopenopenope, 

Based on your comment, looks like your issue is resolved. You can also try with my code as a workaround. So we are closing it since there is no action required from our side. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
