### ISSUE TITLE
Magento 2.4.2-p2 USPS shipping method issue SimpleXMLElement::addAttribute(): string is not in UTF-8

### ISSUE THREAD

**Issue by baljinderimpinge** [magento/magento2#33988]
Hello Team,

I hope you are doing fine.
I have upgraded Magento 2.2.11 to 2.4.2-p2 and now I am getting error on cart & checkout page. Error I am getting is below
Warning: SimpleXMLElement::addAttribute(): string is not in UTF-8 in /vendor/magento/module-shipping/Model/Simplexml/Element.php on line 27

Php version: 7.4
Composer: 2
Website: ﻿https://23050a41a7.nxcli.net/

Front End - password protected:
michael@nexusbox.io
RevsPagersHungShaves

Please check once and let me know if you need anything from my side. Please help me to solve this issue asap.

Thanks
@victor-v-rad @victor-ruiz

**Comment by baljinderimpinge** [comment]
Please add any product to cart and then go to cart page or checkout page, in the browser console you will see error like this
https://prnt.sc/1r4ba06

**Comment by engcom-Delta** [comment]
Hi @baljinderimpinge ,
We tried to reproduce the issue on provided website, found that issue is reproducible and getting same error while checkout .
Kindly find the attached screenshot for reference. Hence added the label 'Needs Update
Website URL: https://23050a41a7.nxcli.net/checkout/#shipping

<img width="960" alt="checkout_issue" src="https://user-images.githubusercontent.com/51681379/132010463-cff17bd1-81ff-4032-8ec8-ab5a60c61b49.png">

Please confirm whether it has to be validated on Magento 2.4.Develop or not ?

Thanks

**Comment by baljinderimpinge** [comment]
@engcom-Delta 
Sorry, I am not clear with "whether it has to be validated on Magento 2.4.Develop or not ?"
Please explain it so that I can understand and reply accordingly.
Thanks

**Comment by engcom-Delta** [comment]
Hi @baljinderimpinge ,

Thanks for reverting back , I mean I should install magento 2.2.11 and upgrade to magento 2.4.2-p2.then do checkout process.
Regards.

**Comment by baljinderimpinge** [comment]
Yes please. Also I have details entered there in the old version so do I
need to re-enter new credentials there after upgradation?

**Comment by baljinderimpinge** [comment]
Any update please?

**Comment by baljinderimpinge** [comment]
@engcom-Delta Please reply, looking for your response.

**Comment by themew** [comment]
@baljinderimpinge Did you solve this?  I don't see the error in your demo anymore.  We haven't seen it on our M2 install but are concerned if it exists in 2.4.2-p2.
