### ISSUE TITLE
Missing classes required by DI in commands are not reported & logs are misleading

### ISSUE THREAD

**Issue by marvinhinz** [magento/magento2#34028]
### Summary (*)
When a class requested in the constructor of a Command does not exist, a misleading error is shown instead of the actual source of the problem. When running bin/magento the output is just "Class Vendor\SomeModule\Console\Command\SomeCommand\Interceptor does not exist". 
To fix the problem the developer is forced to open the logfiles.

### Examples (*)
Create a new module with a command that injects a class that cannot be autoloaded (Class XYZ). Try to run the command or just bin/magento. Instead of printing "Class XYZ does not exist" it prints "The Interceptor does not exist. "

### Proposed solution
It seems to be enough to add a "throw $exception;" after [line 55 in framework/Code/Generator/Autoloader.php](https://github.com/magento/magento2/blob/f0f779a07596da9be8845050815f83dd907f3844/lib/internal/Magento/Framework/Code/Generator/Autoloader.php#L55)
The message should be changed, too as the possible reason is described as a permission issue only.
But i dont about other possible consequences/side effects of this change.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment]
Hi @marvinhinz,
Good catch! Could you create a pull request with a suggested solution? It would be easier to review it with test results ;)

**Comment by marvinhinz** [comment]
Sure, can do. But i just realized the comment of the method says: "According to PSR-4 section 2.4 an autoloader MUST NOT throw an exception and SHOULD NOT return a value.". I guess thats the reason why there is no throw. Then i'm not sure how to fix this. 🤔

**Comment by engcom-Lima** [comment]
Magento bot moved it to **High Priority Backlog** hence moved it back to **Issue Confirmation and Triage Board**

**Comment by engcom-Lima** [comment]
Hi @marvinhinz,
Thank you for reporting the issue.

I was able to reproduce this issue on 2.4-develop instance.
Steps followed to reproduce the issue :-

1. Install fresh Magento 2.4-develop instance
2. Create a custom command and inject a non existing class through the constructor
<img width="956" alt="Screenshot 2022-02-01 at 5 21 31 PM" src="https://user-images.githubusercontent.com/60198022/151963674-356cc0d8-a87e-40f4-b72c-de7f467ea423.png">

3. On CLI Instead of printing **"Class XYZ does not exist"** it prints **"The Interceptor does not exist."**

<img width="956" alt="Screenshot 2022-02-01 at 5 23 16 PM" src="https://user-images.githubusercontent.com/60198022/151963898-bf02811f-0330-4db9-94fa-1ed207802ec1.png">

Based on this confirming the issue.

Thanks!

**Comment by engcom-Hotel** [comment]
Hello @marvinhinz,

As per the comment on its related PR https://github.com/magento/magento2/pull/34326#issuecomment-1076004841, we are closing this issue.

Thanks
