### ISSUE TITLE
[GraphQl 2.4.2] All active payment methods are returned for "free" orders

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#34036]
### Preconditions (*)

1. Magento 2.4.2
2. Enable zero subtotal checkout
3. Enable Check / Money order

### Steps to reproduce (*)

1. Create a product with price 0
2. Add free product to cart
3. Set a shipping and billing address
4. Set freeshipping_freeshipping shipping method.
5. Run graphql query:
```
query getCartDetails($cartId: String!) {
	cart(cart_id: $cartId) {
	    available_payment_methods {
                code
                title
            }
    }
}
```
### Expected result (*)

1. 
```
{
    "data": {
        "getCartDetails": {
            "cart": {
                "available_payment_methods": [
                    {
                        "code": "free",
                        "title": "No Payment Information Required"
                    }
                ],
            }
        }
    }
}
```

### Actual result (*)

1.  
```
{
    "data": {
        "getCartDetails": {
            "cart": {
                "available_payment_methods": [
                    {
                        "code": "free",
                        "title": "No Payment Information Required"
                    },
                   {
                        "code": "checkmo",
                        "title": "Check / Money order"
                    },
                ]
            }
        }
    }
}
```

### The Issue
If the order is free most other payment methods will break when trying to place the order. In the normal magento frontend this is handle by hiding all the other payment methods with javascript. Imo the other payment methods shouldn't be returned in the first place if they aren't going to work. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
**Steps to reproduce:**
Stores - Configuration - Sales - Payment Methods - Enable zero subtotal checkout 
Enable Check / Money order
Create a product with price 0
Enable Free Shipping from Stores - Configuration - Sales - Delivery Methods
Reindex and clear cache
Generate Customer token using GraphQL request
Get Cart ID of the logged in Customer using GraphQL request
`
{
  customerCart {
    id
    items {
      id
      product {
        name
        sku
      }
      quantity
    }
  }
}
`
Add Free Product to Cart using GraphQL or from front-end using above customer
`
mutation {
  addProductsToCart(
    cartId: "V08ldamy2bjY7FQH1vCnQfZ3wOaXO2to"
    cartItems: [
      {
        quantity: 1
        sku: "Test Productsssss"
      }
    ]
  ) {
    cart {
      items {
        product {
          name
          sku
        }
        quantity
      }
    }
  }
}
`
Set Shipping Address and Billing address
Set Free-shipping Method using GraphQL:
`
mutation {
  setShippingMethodsOnCart(
    input: {
      cart_id: "V08ldamy2bjY7FQH1vCnQfZ3wOaXO2to",
      shipping_methods: [
        {
          carrier_code: "freeshipping"
          method_code: "freeshipping"
        }
      ]
    }
  ) {
    cart {
      shipping_addresses {
        selected_shipping_method {
          carrier_code
          carrier_title
          method_code
          method_title
          amount {
            value
            currency
          }
        }
      }
    }
  }
}
`

Run the GraphQL query
`
{
	cart(cart_id: "V08ldamy2bjY7FQH1vCnQfZ3wOaXO2to") {
	    available_payment_methods {
                code
                title
            }
    }
}
`
**Issue**: All payment methods are getting displayed in GraphQL response
![image](https://user-images.githubusercontent.com/60198231/132839251-4917b404-71bf-4d64-9127-a10fac68a721.png)

**Expected behavior:** All other payment methods should not be displayed. There is no issue on front end - Only one payment method is displayed to the user:
![image](https://user-images.githubusercontent.com/60198231/132839201-08533b10-b5e2-4d0e-b31c-0565e1f5c259.png)

**Comment by Hexmage** [comment]
In the frontend the hiding of the other payment methods is done by javascript in the checkout. I assume it's done because the other payment methods do not know if the free payment method is available. In my opinion the best solution would be to move this logic from the javascript to the php code. Because the free payment method is only available when all the other payment methods should be hidden.

**Comment by cpartica** [comment]
this issue is being worked on internally for 2.4.5
