### ISSUE TITLE
Shipping price including/excluding tax not working

### ISSUE THREAD

**Issue by wstnbrg** [magento/magento2#34033]
### Preconditions (*)

1. Magento Version 2.4.3
2. Setup shipping method (e.g. flat rate with 5$ price) 
3. Set tax/calculation/shipping_includes_tax to "Including Tax"
4. Set tax/cart/display_shipping to "Including and Excluding Tax"
5. Set tax/classes_shipping/tax_class to your configured tax rate (in my case Germany - 19%)

### Steps to reproduce (*)

1. add product to cart
2. estimate shipping cost in cart

### Expected result (*)

1. calculated shipping price including tax should be $5
2. calculated shipping price excluding tax should be $4.20

### Actual result (*)

1. calculated shipping price excluding tax is $5
2. calculated shipping price including tax is $5.95 (tax of 19% got reapplied).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wstnbrg** [comment]
This topic might be related to: https://github.com/magento/magento2/issues/33947

**Comment by wstnbrg** [comment]
This one might also be related: https://github.com/magento/magento2/issues/31206

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
**Steps to reproduce:**

 1. Stores - Configuration > Sales > Tax > Calculation Settings > Shipping Prices set to 'Including Tax'
 2. Stores - Configuration > Sales > Tax > Price Display Settings > Display Shipping Prices set to 'Including Tax and Excluding Tax'
 3.  Stores - Configuration > Sales > Tax > Shopping Cart Display Settings > Display Shipping Amount set to 'Including and Excluding Tax'
 4.  Default Tax Destination Calculation - Country - Set Germany / US Country. (Issue Observed for both countries)
 5. Stores - Taxes - Create Tax Zone and Rate with Country "Germany". Tax rate is 19%
 6. Apply Tax rate to Tax Rule
 7. Setup shipping method (e.g. flatrate with 5$ price)
 8. Reindex and clear cache
 9. Front-end - Sign in as customer - default Shipping Address - Germany Address
 10. Add the product to Cart
Issue: calculated shipping price including tax is $5.95 
![image](https://user-images.githubusercontent.com/60198231/132688024-916a4e71-7f60-4bf1-8a52-154c365ee9f2.png)

**Comment by evktalo** [comment]
Is there a fix on 2.4-develop branch?

**Comment by evktalo** [comment]
Since this was closed in Nov 2021, I assume the fix should be in 2.4.4, but I'm still encountering this issue in that version.

**Comment by engcom-November** [comment]
Hi @wstnbrg 
It has been decided that this is expected behavior of Magento and no need to change the current tax calculation logic.
Thank you.

**Comment by evktalo** [comment]
Correct me if I'm wrong, but if this is expected behaviour, isn't having a setting tax/calculation/shipping_includes_tax unnecessary and misleading, if Magento's shipping tax calculation will only work correctly when set to "excluding tax"?
