### ISSUE TITLE
There's no Submit Button for Reindexing data Manually

### ISSUE THREAD

**Issue by xrobix** [magento/magento2#3403]
Receive notification when finish the installation for reindexing and doing a cron job, 
but both of them have not submit button for doing manually.

Kindly advise for magento 2.0
telkoantenna.com - just startup for doing in ecommerce

**Comment by webtekindo** [comment]
+1

**Comment by davidalger** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

That said :) The notification in the admin is informing you that the cron task is not configured on the server. The cron will run the indexes automatically. Since these are not administrative functions, they are not operations which can be done from the admin panel in Magento 2, only from the CLI interface or via the built-in mechanisms in a properly configured environment. On top of them being automatically rebuilt via the cron task, they can also be rebuilt from scratch using the bin/magento tool on the CLI. If you need assistance doing that, head over to the forums at one of the above links
