### ISSUE TITLE
Magento Graph QL : Unable to Apply Coupon as its marked as applied even before placing an order

### ISSUE THREAD

**Issue by venkivenkatesh** [magento/magento2#34058]
We are using Magento ver. 2.4.2-p1 as backend admin while frontend is running on PWA which uses graphql mutations.
I am facing the below problem. Please find the below steps

**Steps to Reproduce:**

1. I have a Welcome coupon configuration where a customer can use the coupon only once
2. Apply that coupon in the cart
3. Navigate to the last step of checkout page
4. Then make any of the product in cart to outofstock
5. Click on Place order,it will redirect to cart page showing "Some of the products are out of stock" which is valid one
6. Click again on Place Order - "The Coupon code is not valid" error message is displayed.
6. Run consumer command: bin/magento queue:consumers:start sales.rule.update.coupon.usage
7. But now i can no longer use that coupon on any of the products. When i check the DB tables,an entry is created like the coupon is already used. Please refer below screenshots
![image](https://user-images.githubusercontent.com/25029807/132946291-9e749420-8860-494a-b5fb-5b0e03599e62.png)

**Expected result (*) :**

I should be able to apply the coupon again as order is still not yet placed

**Actual result (*) :** 
I am not able to apply the coupon in the cart page
DB tables - salesrule_coupon, salesrule_coupon_usage - Entries are created even if the coupon is not used. "times_used" column is updated to 1 even if order is not created.

Any suggestions on how we can fix this. Thanks in advance

**Note:** It is reproducible using front end UI as well

**Comment by engcom-November** [comment]
We are blocked to test this issue on Magento 2.4-develop branch due to https://github.com/magento/magento2/issues/34065.
(Note: Issue also exists on 2.4.3 Composer version)

This ticket needs to be verified once the above issue is resolved as this is reproducible on 2.4.2-p1 version.

**Steps to reproduce:**
1. Admin - Marketing - Cart Price Rules - Add New Rule - Create Specific Coupon , Customer Groups - All except "Not Logged In" (exclude "Not Logged In")
Set Uses per Coupon , Uses per Customer to 1
Actions - Enter discount amount and Save
2. Reindex and clear cache
3. Front-end - Login using Customer which belong to any of the above configured Customer Group
4. Add product to Cart
5. Enter Discount code and proceed to checkout (final step)
6. Do not place Order. Set the product to Out of Stock from Admin and Save
7. Place Order - Error message displayed. **No issue.** User is not able to place Order
**Issue**: User cannot able to use the coupon anymore.
DB tables - sales_coupon, sales_coupon_usage - Entries are created even if the coupon is not used. 
Expected behavior: Since the order payment failed, User should able to re-use the coupon.
![image](https://user-images.githubusercontent.com/60198231/133080944-4c9271b2-afd9-40e3-8702-0f7aeea3c8cd.png)
![image](https://user-images.githubusercontent.com/60198231/133081281-29ec4582-c632-4e58-b254-2c574ef4b859.png)

**Comment by engcom-November** [comment]
Verified the issue again on Magento 2.4-develop branch and the issue is reproducible:
**Steps to reproduce:**
1. Admin - Marketing - Cart Price Rules - Add New Rule - Create Specific Coupon , Customer Groups - All except "Not Logged In" (exclude "Not Logged In")
2. Set Uses per Coupon , Uses per Customer to 1
3. Actions - Enter discount amount and Save
4. Reindex and clear cache
5. Front-end - Login using Customer which belong to any of the above configured Customer Group
6. Add product to Cart
7. Enter Discount code and proceed to checkout (final step)
8. Do not place Order. Set the product to Out of Stock from Admin and Save
9. Place Order - Error message displayed. **No issue. User is not able to place Order**
10. Run consumer command: bin/magento queue:consumers:start sales.rule.update.coupon.usage
11. Add any other product to cart and apply same coupon - **Issue**: Error message displayed.
User cannot able to use the coupon anymore.**
DB tables - salesrule_coupon, salesrule_coupon_usage - Entries are created even if the coupon is not used. "times_used" column is updated to 1 even if order is not created.
**Expected behavior**: Since the order is not placed, user should able to use the coupon.
![image](https://user-images.githubusercontent.com/60198231/133991469-f55b3b66-70f5-4e42-bd0d-88dca65608de.png)

![image](https://user-images.githubusercontent.com/60198231/133991238-f36635b9-92de-44f5-b8be-2026146f1a47.png)
![image](https://user-images.githubusercontent.com/60198231/133991568-36f2dd83-d442-4bbc-9dfa-0e760a75ceea.png)

**Comment by engcom-Hotel** [comment]
Hello,

We have tried to reproduce the aforementioned issue on the latest 2.4-develop code base & were unable to do so.

Please find the steps followed to reproduce & associated screenshots below for reference.

1. Admin - Marketing - Cart Price Rules - Add New Rule - Create Specific Coupon , Customer Groups - All except "Not Logged In" (exclude "Not Logged In")

Set Uses per Coupon, Uses per Customer to 1

Actions - Enter the discount amount and Save
![image](https://user-images.githubusercontent.com/51681618/189928238-46d28a39-b237-46fa-86a6-ad065babfab5.png)

2. Front-end - Login using Customer which belongs to any of the above configured Customer Group

Add product to Cart

Enter the Discount code and proceed to checkout (final step)
![image](https://user-images.githubusercontent.com/51681618/189928339-9a695755-04c4-4e98-a4f6-40c454843db5.png)


3. Do not place an Order. Set the product to Out of Stock from Admin and Save

4. Place Order - Error message displayed as expected. The user is not able to place an Order
![image](https://user-images.githubusercontent.com/51681618/189928417-3f51a4a2-c1c9-4d83-8906-bfb230f1f36d.png)


5. Run consumer command: bin/magento queue:consumers:start sales.rule.update.coupon.usage
Observed DB tables - salesrule_coupon, salesrule_coupon_usage times_used is still 0.
![image](https://user-images.githubusercontent.com/51681618/189928454-c7529004-73db-41bd-8124-579d841cd68b.png)

6. Add product to cart and apply same coupon
![image](https://user-images.githubusercontent.com/51681618/189928506-e5474cbc-7a61-4d47-9a20-67d0613c0950.png)

We were able to successfully place the order with the one-time use coupon.

Thanks
