### ISSUE TITLE
Related Products Block Breaks Rich Snippets Price on Product View

### ISSUE THREAD

**Issue by hewgim** [magento/magento2#34063]
### Preconditions (*)
We are running on Magento 2.3.5-p1

When the product view related products block is generated after a cache clean, it appears that it generates cached price blocks for each of the related products (without any schema.org offer price rich snippets). If you then click on one of these products and go to the product view for that product, the main price field is loaded from cache, and therefore the schema.org offer price rich snippets are missing. We noticed this because Google was showing incorrect prices for our products as a result of the missing rich snippets.

### Steps to reproduce (*)

Set up a simple product A with one related simple product B
Go to product A's product view
Clear the cache
Refresh product A's product view
Look in your web inspector tools at the main price field for product A and you will see the offers rich snippet
From product A's related products block go to product B
Look in your web inspector tools at the main price field for product B and the offers rich snippet is missing. I believe this is because the price block for product B was cached without the offers rich snippet when product A's product view was created.

### Expected result (*)
The offers rich snippet should always be present on the main price field on the product view
![image](https://user-images.githubusercontent.com/60198231/134140343-89f3d6c9-9d7e-45fe-84bc-d3f2b1fb75d3.png)

### Actual result (*)
The offers rich snippet is sometimes missing from the main price field on the product view which means that Google often displays incorrect prices on its search results.
![image](https://user-images.githubusercontent.com/60198231/134140367-6adc093f-6e6b-41ee-98c8-8a9b7ae61200.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hewgim** [comment]
@magento give me 2.4-develop instance

**Comment by hewgim** [comment]
I can confirm that this issue exists on the 2.4-develop instance. Not quite sure how this process works. I see that @engcom-November has self assigned this, so I'm not sure if there is anything else I need to do. I did run the 2.3.5-p1 code through a debugger and it looks to me like getCacheKeyInfo() in Magento/Catalog/Pricing/Render/FinalPriceBox.php needs to include a flag that indicates whether the price block includes the offers rich snippet or not.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:

**Steps to reproduce:**
Create a Simple Product A from admin and Save
Create another simple product B and add Simple A as Related Product to it and Save
Front-end - Open Simple Product B
Clear the cache - > bin/magento cache:flush
Refresh product B's product view
Inspect Element - Look in your web inspector tools at the main price field for product B and you will see the offers snippet
From product B's related products block go to product A
Look in your web inspector tools at the main price field for product A and the offers rich snippet is missing. 
Note: This issue is happening after clearing Cache for existing Related products as well when viewed related product from main product.
**Expected Results**
The offers rich snippet should always be present on the main price field on the product view
![image](https://user-images.githubusercontent.com/60198231/133264228-384234e2-c4c6-40c1-8208-c164382a90c0.png)

**Actual Results**
The offers rich snippet is sometimes missing from the main price field on the product view which means that Google often displays incorrect prices on its search results.
![image](https://user-images.githubusercontent.com/60198231/133264322-8538a4fb-5d78-499f-89f0-93c3735732d9.png)

**Comment by vovsky** [comment]
@magento I am working on this
