### ISSUE TITLE
Updated Magento to the 2.4.3 version. Error on begin process checkout of goods.

### ISSUE THREAD

**Issue by sgeleon** [magento/magento2#34125]
Hi.

======== Preconditions =========
1) Magento 2.4.3
2) Onestepcheckout/iosc 1.2.051

======== Steps to reproduce =====
1) Add goods in cart by click on 'Add to cart'
2) Come in into checkout

======== Expected result ========
Begin checkout and see list of goods

======== Actual result ==========
Get error: Type error occurred when creating object: Magento\ReCaptchaUi\Model\CaptchaTypeResolver.

================================ my searching the cause this bug ====================================

I update Magento to the 2.4.3 version. When I begin process checkout of goods I got the error:
![image](https://user-images.githubusercontent.com/18437080/133981594-46662cf5-c797-4933-b465-9fa6a6bfefef.png)

I found out why arrived this error when initialing the class IsCaptchaEnabledInterface by ObjectManager, it got an empty array in this file:
![checkout_3](https://user-images.githubusercontent.com/18437080/133981818-e9b0d3fe-ec54-4c99-a563-7d09761865f0.png)

but this class requires the necessary initializes of classes.
![checkout_4](https://user-images.githubusercontent.com/18437080/133981843-905bc010-6b5e-44a3-aabe-dee024caa3b4.png)

This class is defined in di.xml:
![checkout_5](https://user-images.githubusercontent.com/18437080/133981890-73eaddbe-ce86-4e56-baf7-5b2e36d18ba9.png)

This class used in the checkout config provider:
![checkout_2](https://user-images.githubusercontent.com/18437080/133981927-d6707253-97a8-4f16-8f06-76598452b0cc.png)

Which is called in this pthml:
![checkout_1](https://user-images.githubusercontent.com/18437080/133981950-5a48ef63-7a01-486e-a196-86ab3a260b14.png)

**Comment by engcom-Delta** [comment]
Hi @sgeleon ,
Kindly provide the steps to reproduce, issue description, actual results and expected results.

Thanks

**Comment by atIOCrON** [comment]
Hi @engcom-Delta ,
You clearly didn't read the description that @sgeleon wrote because the steps to reproduce, actual results and expected results are all there. I'll copy and paste them for you:

======== Preconditions =========

Magento 2.4.3
Onestepcheckout/iosc 1.2.051
======== Steps to reproduce =====

Add goods in cart by click on 'Add to cart'
Come in into checkout
======== Expected result ========
Begin checkout and see list of goods

======== Actual result ==========
Get error: Type error occurred when creating object: Magento\ReCaptchaUi\Model\CaptchaTypeResolver.

**Comment by speedupmate** [comment]
@sgeleon since OneStepCheckout  is a 3rd party extension  try to report such issues to support@onestepcheckout.com directly
