### ISSUE TITLE
Slow loading/Exception and incorrect permission in var/cache/mage-tags 

### ISSUE THREAD

**Issue by memen45** [magento/magento2#34120]
### Preconditions (*)
Magento 2.4.3

### Steps to reproduce (*)
Enabling the following developer options
- Minify HTML
- Minify JavaScript 
- Merge CSS
- Minify CSS
- Use CSS critical path

crontab is setup for user `deploy`

### Expected result (*)
Faster page loads.
In case cache is created from the cron (not sure why cron would create this btw), the files should have `deploy:www-data` ideally, as deploy is in the www-data group and the cache should be readable by www-data as well.

### Actual result (*)
I observe same behaviour as #10700 and #11930, slowing the site and taking 10-20+ seconds to load any page every time, or even exceptions due to Permission denied errors from mage-tags directory.
The slow loading can be fixed by using `bin/magento cache:flush` and disabling cron. This reduced the response time significantly to below 100ms.

Observing the `var/cache/mage-tags` folder with cron enabled: some files have `deploy:deploy` owner, which cannot be accessed by www-data user. 
Observing with cron disabled and after the cache flush and a page access: all files have `www-data:www-data`  owner, which can be accessed by www-data user obviously.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @memen45,

We have tried to reproduce this issue in Magento 2.4-develop branch, but this is not reproducible for us. We have followed the steps mentioned in the main description as well as below one:
1. Install Magento 2.4-develop branch with sample data.
2. Setup cron by running command `bin/magento cron:install`.
3. Run command `bin/magento c:f` to flush the cache.
4. Wait until the cache has been built by cron and then check the user for the folders in `var/cache/`. For us it is visible for `abhinav` user.
5. And then again run `bin/magento c:f` to flush the cache and then refresh the homepage so that this time cache will build by request
6. We can see the same user i.e. `abhinav` for the folders in `var/cache/`.

Please let us know if we did anything wrong in order to reproduce the issue.

Thanks

**Comment by memen45** [comment]
Thanks for your reply. Did you check the group owner? The issue is not with the user, it is correct and expected to be the deploy user, as deploy creates the cache files during cron. However, the apache2 user requires access to those cache files. Therefore, the owner group should be www-data and the full owner of the cache files should thus be 
`deploy:www-data`, or in your case `abhinav:www-data` (or replace www-data with the user group of the web server user). 

Hope this clarifies the issue!

**Comment by engcom-Hotel** [comment]
Hello @memen45,

For me in both cases group is coming as `admin`.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @memen45,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
