### ISSUE TITLE
Price and special price are not syncing

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#34147]
### Preconditions (*)

1. Magento version 2.3.1
2.

### Steps to reproduce (*)

1. Call the API url for sync price and special price  http://php72.webgility.com/magento231_ext3/rest/V1/products/base-prices, http://php72.webgility.com/magento231_ext3/rest/V1/products/special-price respectively
2. API does not sync price and special price.
3.  But when in same request we pass "storeid=0", the price and special spice both gets synced.
4.  Request for both APIs with storeiid >0 and storeid=0 
[priceandspecialprice_storeid.txt](https://github.com/magento/magento2/files/7215836/priceandspecialprice_storeid.txt)

### Expected result (*)

1. price and special price should get synced irrespective of stores value. It was working fine previously.
2.

### Actual result (*)

1. price and special price are not getting synced
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:

**Steps performed:**
Admin - Stores - Configuration - Catalog - Catalog - Price Scope is set to Global
Reindex and clear cache
Generate Admin access token using POST: /rest/default/V1/integration/admin/token
Send POST request to /rest/V1/products/base-prices to update Base Price of other store
In my case: Store id of france is 3
**No issue: Error message is displayed as price scope is set to "Global"**
![image](https://user-images.githubusercontent.com/60198231/134499442-40928237-00c8-4990-9d30-9e3b9d4a9bea.png)

Chance Catalog Price scope to "Website" from Admin
Reindex and clear cache
Send POST request to /rest/V1/products/base-prices to update Base Price of other store
**No issue:** Base Price is updated as expected for france store
Send POST request to /rest/V1/products/special-price to update Special Price of other store
**No issue**: Special Price is updated as expected for france store
![image](https://user-images.githubusercontent.com/60198231/134499339-4ab051a7-8fdc-40b3-8cd4-8ed2392627eb.png)

![image](https://user-images.githubusercontent.com/60198231/134499286-72820093-c2dc-47d8-aa84-baa51f734ec9.png)

![image](https://user-images.githubusercontent.com/60198231/134499193-8d1a8588-632b-4011-91a2-29a7df885cd0.png)

![image](https://user-images.githubusercontent.com/60198231/134499143-271c32ae-6bd7-444a-9779-037838ae2cfd.png)
