### ISSUE TITLE
Capture amount is invalid when discount is higher than subtotal without tax 

### ISSUE THREAD

**Issue by MeCapron** [magento/magento2#34181]
### Preconditions (*)

1. 2.4.2-p2

### Steps to reproduce (*)

1. Add to your cart a product with a tax class
2. Add a discount that is for example 95% of the order
3. Try to capture it

### Expected result (*)

1. Order should be capturable

### Actual result (*)

1. Order is not capturable

### Example

- As far as I know, this issue was introduced by the commit [2dbab41631cce46be4a27dcbf10a7b172be61f63](https://github.com/magento/magento2/commit/2dbab41631cce46be4a27dcbf10a7b172be61f63) from Magento 2.4.1.

Before this commit, the calculation would be the following : 

- Ordering for a total amount of 45€, with 20% tax resulting to a subtotal of 37.5€
- Adding a discount for 40€
- During the calculation, Magento would do *subtotal - discount = result* -> 37.5 - 40 = -2.5
- Before 2.4.1, Magento will set to the Invoice grand total
- After 2.4.1, Magento sets 0 to the Invoice grand total
- During discount tax compensation of 40€, Magento will do **grand_total** + tax + discount_tax
- Before 2.4.1, Magento would calculate `(-2.5) + 0.83 + 6.67 = 5.00`
- After 2.4.1, Magento calculate `0 + 0.83 + 6.67 = 7.5`
- Result : bad amount for the capture

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MeCapron** [comment]
@magento give me 2.4-develop instance

**Comment by hostep** [comment]
This sounds similar to https://github.com/magento/magento2/issues/32270 & https://github.com/magento/magento2/issues/30853. Does [MC-41438: 100% Discount cart rule results in Tax invoiced](https://github.com/magento/magento2/commit/533ec2eb46c91b79b7a99ba4a6a164e2f6e3d7f1) fix your issue? This fix is included in Magento 2.4.3 btw.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible. Capture online and Capture Offline both are working fine with above Tax and discount configuration.
**Steps performed:**
Created Tax rate of 20%
Created Cart Price Rule of $40 - Fixed amount for whole cart
Tax calculation as per below screenshot:
![image](https://user-images.githubusercontent.com/60198231/135222605-cfa10682-aa86-4168-b1c6-bf23af4382cb.png)

Created Product with price including tax - $45
Front-end - Add Product to cart - Apply discount - Grand Total = 5 - **No issue**
Placed Order using Paypal Express Checkout
Admin - Sales - Orders - View Order - Invoice - Capture Online - **No issue** - Captured successfully.
![image](https://user-images.githubusercontent.com/60198231/135222493-1a57c57c-7400-44cf-8e00-2d3c4479b718.png)

![image](https://user-images.githubusercontent.com/60198231/135222432-fce82ad8-92d1-42f2-ad47-adec241c27ab.png)

@MeCapron, kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps if any if the issue is still reproducible:

**Comment by MeCapron** [comment]
> This sounds similar to #32270 & #30853. Does [MC-41438: 100% Discount cart rule results in Tax invoiced](https://github.com/magento/magento2/commit/533ec2eb46c91b79b7a99ba4a6a164e2f6e3d7f1) fix your issue? This fix is included in Magento 2.4.3 btw.

Thanks. I just tried this patch and it fixed my issue. No more problem here, thanks.

**Comment by MeCapron** [comment]
@engcom-November Thank you for working on this issue, as @hostep said this issue is resolved in 2.4.3 through  https://github.com/magento/magento2/commit/533ec2eb46c91b79b7a99ba4a6a164e2f6e3d7f1
