### ISSUE TITLE
Magento/QuoteGraphQl/Model/Cart/GetCartForUser function updateCartCurrency

### ISSUE THREAD

**Issue by carloricci84** [magento/magento2#34199]
In https://github.com/magento/magento2/blob/2.4.3-release/app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php

The function updateCartCurrency set an object instead of a string inside the cart object. On line 130, 131 and 133. The argument passed should be

`$newStore->getCurrentCurrency()->getCode()`

instead of

`$newStore->getCurrentCurrency()`

### Preconditions (*)
1. Magento 2.4.3

### Steps to reproduce (*)

1. Add an item to cart trough graphql with a logged in user
2. Change your store view
3. Try to load a quote with \Magento\Checkout\Model\Session ->getQuote in a checkout_cart_save_after events 

### Expected result (*)

1. Quote is loaded correctly observer can process by doing what it needs to do

### Actual result (*)

1. Quote is not loaded because it try to compare an object with a string on line 267 of https://github.com/magento/magento2/blob/2.4.3-release/app/code/Magento/Checkout/Model/Session.php. Then when trying to save the quote on line 269  it goes on an infinite loop with the observer .

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Hotel** [comment]
Hello @carloricci84,

Thanks for posting this issue!

The issue is reproducible in the Magento 2.4-develop branch by looking into codebase only. I am attaching a screenshot of the file `app/code/Magento/QuoteGraphQl/Model/Cart/GetCartForUser.php` below for reference:

![image](https://user-images.githubusercontent.com/51681618/141272908-b5cb1972-938f-48a1-a3f1-27da1e2d73f2.png)

`setStoreCurrencyCode` function requires parameter as string but object passed of type `Currency`. 

Thanks

**Comment by engcom-Lima** [comment]
Hi @carloricci84, I tried to reproduce the issue on 2.4-develop, however the issue is not reproducible.

Steps followed to reproduce the issue:-

1. Created 2 store views
2. Added simple product from **one** store view in GraphQl
3. Changed the header to set the **second** store view
4. Proceeded with Checkout

I was able to complete the checkout without any error

Please let me know if this issue is still reproducible.
If it is still reproducible then please let me know the exact steps along with code modifications (if any) I need to do.
I will reverify it.

Thanks

**Comment by engcom-Alfa** [comment]
As there is no response to my last comment in last ~14 days, closing this current issue.

Kindly upgrade to the latest version to re test. In case of any Magento related issues, you may please report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).
