### ISSUE TITLE
Error while saving home page

### ISSUE THREAD

**Issue by krishnaragu** [magento/magento2#34216]
![magento1](https://user-images.githubusercontent.com/38458706/135575066-914019d1-a823-4a48-8c69-2d41e22884b1.png)

### Preconditions (*)

1. I use magento version 2.4.3
2.

### Steps to reproduce (*)

1. Login to admin panel.
2. Try to save the "home Page"
3. You will get below error:
"Temporarily allowed to save HTML value that contains restricted elements. Allowed HTML tags are: div, a, p, span, em, strong, ul, li, ol, h5, h4, h3, h2, h1, table, tbody, tr, td, th, tfoot, img, hr, figure, button, i, u, br, b, iframe, style, pre"

Screenshot of the same in the attached file "magento1.png".

After saving I can see blank slider as shown in the screenshot "magento
![magento_home](https://user-images.githubusercontent.com/38458706/135575034-56dd02c3-f7bf-4aa4-8a6d-83fcf2daadce.png)
_home.png". Please help to fix the issue.

**Comment by engcom-Lima** [comment]
Hi @krishnaragu,

Thank you for reporting the issue.

However with the steps provided, I was not able to reproduce it. I am able to save page without any issues, attached screenshot of the same.

<img width="1323" alt="Screenshot 2021-10-08 at 5 19 17 PM" src="https://user-images.githubusercontent.com/60198022/136554935-a9fc7573-ab45-4e99-ad83-8bcc71d163c4.png">

Maybe the tags that you are using in your home page content are restricted. Please check below link and see if it helps:
https://magento.stackexchange.com/questions/331918/cms-and-block-content-warning-magento-2-4-2

Please provide more detailed 'steps to reproduce' or the content from which you think this error might have occurred, then only I'll be able to reproduce it.

Thanks

**Comment by KrishnaPB** [comment]
Hi, I have still experiencing the same issue. Please look into this.

**Comment by baseplayer** [comment]
Hi,

I use 2.3.7-p2 and the same problem is there?

I am realy sorry too say but Magento 2 has so many bugs, i use magento for 11 years
but since magento 2 i find bugs over and over again. in frontpage(customer account) and backend.

Every time i ask my dev to fix it cost me more than 1000,- euro and this is the truth?
How can this be?

What is strange that the problems sometimes where solved years  ago, but pop up in new distro's

If you want i send you a list

It is realy frustrating! Magento 1 was much faster and better.

So i hope you can discuss this.

**Comment by baseplayer** [comment]
It seems like old files with old bugs are used for new patches>?
