### ISSUE TITLE
Theme CSS is not including to head on front-end PHP 7.4.24

### ISSUE THREAD

**Issue by nirajbsa** [magento/magento2#34239]
### Preconditions (*)
1.  Magento 2.4.3
2.  PHP 7.4.24

### Steps to reproduce (*)

1. Fresh Magento installation on nginx and php 7.4.23 and after that upgraded php to latest sub release 7.4.24 and head doesn't have any included css expect calender.css

![image](https://user-images.githubusercontent.com/88161122/135894484-2bb16585-6d84-47b9-9978-4170b2c24bb0.png)

2. As per release note php7 - they have php7.4-xml has update and think it has something that is generating this issue.
https://www.php.net/ChangeLog-7.php 

### Expected result (*)

Should show atleast styles-m.css in source

![image](https://user-images.githubusercontent.com/88161122/135894793-c74997fb-53bd-49ae-bc0f-13ba91b08a9d.png)

### Actual result (*)
Not including any css expect calendar.css

![image](https://user-images.githubusercontent.com/88161122/135894484-2bb16585-6d84-47b9-9978-4170b2c24bb0.png)

**Comment by mrtuvn** [comment]
I think issue may related with theme named "Magento/builtcon" ? Is this custom not from magento

**Comment by nirajbsa** [comment]
Nope I tried with fresh Magento. That snapshot was sample from another site
to show it needs to add styles-m.css. or any other css

**Comment by jl-tric** [comment]
Can confirm that php 7.4.24 breaks CSS on magento 2.4.3.

**Comment by nirajbsa** [comment]
Yes it happened only after upgrading php from 7.4.23 to 7.4.24
https://www.php.net/ChangeLog-7.php

Above you can see release note.

I couldn't figure out solution. It needs to be resolved ASAP because all **new server setups** if we install php 7.4 it will be latest version  7.4.24 and no one will be able make their website live nor can do development on website.

**Comment by jl-tric** [comment]
To citate @hostep : 

> We were able to solve it by setting pcre.jit to 0 in our php.ini file

@nirajbsa maybee this will solve your issue aswell? 
I have testet it, and it works perfectly for my installation :-) :+1:

**Comment by densen45** [comment]
This issues also occurs on Magento 2.4.2-p2.

I can confirm that setting `pcre.jit=0` in the php.ini file and restarting the php7.4-fpm.service solves this issue. Thank you @jl-tric for sharing this.

**Comment by nirajbsa** [comment]
@jl-tric  it worked :)  Thank you

**Comment by mrtuvn** [comment]
never got this issue. I don't change any specific in php instance. So i can't reproduce from my end
Just curiously is this config pcre.jit always enable (equal 1) ?

**Comment by hostep** [comment]
So to give a bit more context.
The [bug](https://bugs.exim.org/show_bug.cgi?id=2763) was introduced in the PCRE2 library version 1.0.37 and has been [fixed](https://vcs.pcre.org/pcre2?view=revision&revision=1302) since then but that hasn't been released yet in a newer version.
PHP then as a quick fix added [a workaround](https://bugs.php.net/bug.php?id=81101) in version 7.4.22 and 8.0.9 to circumvent the bug in the PCRE2 library.
To prevent the bug in older versions of PHP, changing the setting `pcre.jit=0` in your `php.ini` file should work as well.

But from the reports here, it sounds like PHP's workaround is not working properly if people are able to reproduce the bug on 7.4.24?
