### ISSUE TITLE
Advanced Reporting not working

### ISSUE THREAD

**Issue by margauxdalimier** [magento/magento2#34255]
Good morning,

We are struggling to have Advanced Reporting in our Magento instance.

This is what we have done so far :

- The website must run on a public web server.
- The domain must have a valid security (SSL) certificate.
- Commerce must have been installed or upgraded successfully without error.
- In the Commerce configuration for  store URLs , the Base URL (Secure) setting for the store view must point to the secure URL. For example https://yourdomain.com.
- In the Commerce configuration for  store URLs , Use Secure URLs on Storefront and Use Secure URLs in Admin must be set to ### Yes
- Make sure that  Commerce crontab  is created and cron jobs are running on the installed server.
- We authorize the Webanalytics user API many times
- Our subscription status is set to «Enable » in Magento backend
- We also ran the query « select distinct base_currency_code from sales_order; » in production which returns one currency (USD)

Could you please look at your end if there is something special to do / to fix? @magento-admin @magento

Many thanks for your support.
Kind Regards,

**Comment by engcom-Lima** [comment]
Hi @margauxdalimier,

Thank you for reporting the issue. However your issue does not look like Magento Dev related.

So, what I suggest is you check with Magento Support relating to same or you can also post on various Magento Forums for a possible solution. As per documentation `It can take up to a day for data to be available in Advanced Reporting.` so please make sure of it.

You can find more details on https://devdocs.magento.com/guides/v2.4/advanced-reporting/overview.html

If you still think this issue is related to Magento Dev, please update your description with proper 'Steps to reproduce' and 'Expected & Actual Results' or otherwise we'll have to close this one.
