### ISSUE TITLE
Vault/Stored Payment Methods are not saved per store

### ISSUE THREAD

**Issue by lilbumblebear** [magento/magento2#34253]
### Preconditions (*)
1. Magento 2.4.3
2. Braintree Payment Method (with Stored Cards)

### Steps to reproduce (*)
1. Create 2 websites (ex: A and B)
2. Stores - Configuration - Customers - Customer Configuration - Share customer accounts --> global
3. Reindex and cache clear
4. Admin - Stores - Configuration - Sales - Payment Methods - Scope - Default Scope - Configure Braintree with Sandbox account credentials and Save  
5. Change scope to other Store view - Configure Braintree with different Sandbox account credentials and save   (Different payment credentials for each website (testing with braintree, with 2 different sandbox accounts)
6. Reindex and clear cache
4. Create 1 customer 
5. (on Admin) Create an order on website A for customer 1 and store card info
6. (on Admin) Start creating an order on website B for customer 1 and the stored card from website A appears
7. Front end - Login to Website B using same customer - Checkout page - Stored card payment method is displayed however payment is not working.
### Expected result (*)
1. Card information should be saved per store, not globally for the customer
2. I should not be able to see stored cards unless I am checking out in the same store in which they were saved.

### Actual result (*)
1. I am able to see the stored card from website A when I choose payment information for website B
2. If I try to process the order, there is an error (expected, because the processor credentials are different)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Admin:
![image](https://user-images.githubusercontent.com/60198231/146777736-4e9bd258-1b0c-4be5-b6b0-28647983e3c2.png)

Front end - 
Stored card info is displayed however payment is not working. Page not loading.
![image](https://user-images.githubusercontent.com/60198231/146777826-a3d0f08b-27f5-4dd2-8a76-2d6e82e06214.png)

**Comment by fredden** [comment]
@nathanjosiah I think there is a security issue here.

Consider a case where the payment gateway gives weak / colliding tokens. This is fine, because the token means nothing to us, and the association with actual payment happens at the payment gateway side. Let's say (for ease of discussion here) that the payment gateway gives sequential numeric identifiers per account as its tokens.

With the above, let's follow the flow of two users in Magento using the Vault.

1. Alice creates an account in Store1 (configured with Sandbox1 payment gateway account).
1. Alice goes through checkout in Store1 and saves their card, getting a token of `Vault1` from the payment gateway.
1. Bob creates an account in Store2 (configured with Sandbox2 payment gateway account).
1. Bob goes through checkout in Store2 and saves their card, getting a token of `Vault1` from the payment gateway.
1. Alice goes through checkout in Store1 using their saved card. The payment gateway sees `Vault1` for Sandbox1 and takes payment. All is well.
1. Bob goes through checkout in Store2 using their saved card. The payment gateway sees `Vault1` for Sandbox2 and takes payment. All is well.
1. Alice goes through checkout in **Store2** using their saved card. The payment gateway sees `Vault1` for Sandbox2 and takes payment **from the wrong person**. Magento thinks all is well, as the payment gateway reports that it has successfully transferred funds.

Another similar problem could exist if the website administrator changes the payment gateway account credentials. For example (following on from above):

1. The website administrator changes the payment details for Store1 to use payment gateway account Production1.
1. Charlie goes through checkout and saves their card, getting a token of `Vault1` from the payment gateway.
1. Alice goes through checkout in Store1 using their saved card. The payment gateway sees `Vault1` for Production1 and takes payment **from the wrong person**. Magento thinks all is well, as the payment gateway reports that it has successfully transferred funds.

From what's being described here, no collisions have been detected so far. (This is most likely because payment gateways are likely producing globally unique tokens.) When there's no collision, the payment gateway is rejecting the token and the user gets an error.

Yes, the token belongs to the user, but also to the payment method / gateway account. When these match what's on the store being visited, the Vault payment methods / options should show. When either is not applicable, the Vault payment methods should not be displayed.

**Comment by fredden** [comment]
@sidolov why was this closed? The labels suggest that this has been 'done', but I don't see any details here about what has been changed in order to fix this.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2901 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-2901&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta2.

Thanks
