### ISSUE TITLE
Page Builder in Custom Admin Form

### ISSUE THREAD

**Issue by Priyanka-J-94** [magento/magento2#34259]
### Summary (*)

Current Magento Version - 2.4.3 is possible to implement default page builder editor for custom admin form

**Note :** Here form created using php (without using ui_component)

### Examples (*)

Implemented for CMS Page's Content like the same way need to implement for custom form's content

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Priyanka-J-94** [comment]
thank you

**Comment by Priyanka-J-94** [comment]
**Summary :**

Page Builder for Custom Admin Form

**PreConditions :** 

Magento 2.4.3 Open Source

**Steps to Reproduce :** 

1. Need to Implement Page Builder instead of Editor in Blogs Extension for content description
2. Here Blog form is implemented without using ui component in admin

**Expected Result :** 

Page Builder should be implemented in custom form like CMS Page edit form having Edit wth Page Builder Option

**Actual Result :** 

Unable to implement Page Builder for custom forms in admin

**Comment by engcom-Lima** [comment]
Hi @Priyanka-J-94,

This does not seems to be Magento core dev issue. Looks like you are facing problem in implementing Page Builder in Third Part Extension on Admin Panel. For that, you can raise same query on various Magento Forums like [Magento Community](https://community.magento.com/) and [Magento Extension](https://magento.stackexchange.com/). You'll probably get help there.

Since this issue is not related to Magento Dev, we'll have to close this issue. If you still think, it is related to core Magento please update description with proper error information.
