### ISSUE TITLE
PRODUCT CATEGORY URL NOT UPDATING (REWRITING)

### ISSUE THREAD

**Issue by wiwuae** [magento/magento2#34291]
Hi, i am having this issue where once a product category is created, it generates a url but afterwards, it will not update (REWRITE) when i try to change it later on. This happens mostly with the main product categories and not the sub categories. 

For example, if i create main category, lets say SHOES, a url will be generated automatically such as "shoes" [www.example.com/shoes] BUT if later i decide to rename the main category to WORK SHOES, and i want to also update the url to "work-shoes" [www.example.com/work-shoes], it will not rewrite. It will stick to "shoes" [www.example.com/shoes] even though main category name has been updated to WORK SHOES. I am using Magento 2.3.6

Any ideas why this is happening and how to update such urls please?

**Comment by wiwuae** [comment]
For example, if i create main category, lets say SHOES, a url will be generated automatically such as "shoes" [www.example.com/shoes] BUT if later i decide to rename the main category to WORK SHOES, and i want to also update the url to "work-shoes" [www.example.com/work-shoes], it will not rewrite. It will stick to "shoes" [www.example.com/shoes] even though main category name has been updated to WORK SHOES.

**Comment by engcom-Lima** [comment]
Hi @wiwuae,

Thank you for reporting the issue.

However, the issue description is not enough for us to reproduce this. Please provide more detailed 'Steps to reproduce' and your environment related details in order to reproduce it.

From current descrption, it does not seem to be issue related Magento Dev, so you can raise similar queries on various Magento Forums for help. You can also refer to related [Docs](https://docs.magento.com/user-guide/marketing/url-rewrite-category.html) and check if it helps.

**Comment by krishprakash** [comment]
Hi @wiwuae,

Feel free to reopen the ticket once you confirm that issue reproduce on latest magento instance.

Thanks!!
