### ISSUE TITLE
Some job fields are getting same sort order.

### ISSUE THREAD

**Issue by shubham5022** [magento/magento2#34308]
##Environment
- Magento Version : 2.3.2
- Php -v : 7.2.34
- Commit ID : 
- Mode : Tester
##Description
- Some jobs fields are getting same sort order, in reality fields should differ in sort order.
##Steps to Reproduce
1. Open job portal.
2. Click on manage jobs.
3. Click on create jobs.
4. Enter all data with sort order same as of any previously defined field.
5. save the job.
## Expected Result
- Jobs should have different sort types.
##Actual Result 
- Jobs have same sort type.
##Link- https://magento-auction-demo1714892251.webkul.com/admin/jobboard/job/index/key/b03269c7af3381be72cd9cf3a8540cf04afaabf6aaf74deed43291f94040f453/
![Screenshot 2021-10-11 at 22-40-06 View Jobs JobBoard Magento Admin](https://user-images.githubusercontent.com/92208084/136829862-305c0340-2592-46a2-81dd-28f6da623f6f.png)

**Comment by engcom-Lima** [comment]
Hi @shubham5022,

Thank you for reporting the issue.

However, this does not looks like Magento Dev related issue. You are adding some third party module to Magento and it's code might be causing the issue which you are facing. You can write about same issue on various Magento forums like [Magento Community](https://community.magento.com/) or [Magento Stack Exchange](https://magento.stackexchange.com/) and you'll probably get required help. 

I am closing this issue for now as there is no action required from our side. If you feel that your issue is related to Magento Dev and it should be addressed, please re-open this ticket with updated issue description or create a fresh ticket.
