### ISSUE TITLE
Magento 2 cart price rule discard subsequent rules not working

### ISSUE THREAD

**Issue by nafees1988** [magento/magento2#34320]
I added 2 new rules to magento 2.3.4 and these aren't working as they should. 
These rules are for Guest Users <br/>

**Rule 1: DIS100 $100 off $699**
Coupon : No Coupon (auto apply) 
Priority: 2 
Condition: If subtotal greater than 699 and less than 1399 
Action: Fixed Amount Discount for Whole Cart 
Discount Amount : $100 

**Rule 2: 10OFF 10% off** 
Coupon : Specific Coupon (10OFF) 
Priority: 1 
Condition: If category is 50 (50 is category id) 
Action: Percent of Product Price Discount 
Discount Amount : 10%  
Discard Subsequent Rules: Yes 

**Expected Result** 
When customer use coupon code 10OFF then it should discard the first rule and only discount should be given to products assigned to category id 50. 

**Actual Result:** 
It works fine if only category 50 products are added to cart, but when I add any other category products then first rule also applies

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible:
Steps performed:
Created Cart Price Rule for Guest User - No Coupon , Priority: 2
Condition: If subtotal greater than 699 and less than 1399
Action: Fixed Amount Discount for Whole Cart
Discount Amount : $100
Created another Cart Price Rule for Guest User - Specific Coupon - 10OFF , Priority 1, Condition: If category is 3 (3 is category id)
Action: Percent of Product Price Discount
Discount Amount : 10%
Discard Subsequent Rules: Yes
Create Product with Subtotal = $800
Navigate to Store front - Add a Product to Cart. - **No issue**
If no coupon is applied - $100 is applied
Apply coupon code - 10OFF - **No issue: Old discount is removed and only new coupon is applied** 
**Before Specific Coupon applied:**
![image](https://user-images.githubusercontent.com/60198231/137900818-7560ec0a-5921-461e-9492-447926ba562e.png)
**After Specific Coupon applied**
![image](https://user-images.githubusercontent.com/60198231/137900220-a4712797-66c8-4f43-98c0-e943193dfadc.png)
@nafees1988 kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by krishprakash** [comment]
Hi @nafees1988. Feel free to reopen once you confirm that issue reproduce on latest 2.4 develop instance with all reproducible steps.
Thanks.

**Comment by iahmed25** [comment]
Hi All,

Can someone please confirm is this the expected functionality in magento 2.4.2
@nafees1988 @krishprakash
