### ISSUE TITLE
Variant tax on bundle product

### ISSUE THREAD

**Issue by kasperth** [magento/magento2#34364]
### Preconditions (*)
1. Tested on Magento 2.4.2 and 2.4.3
2. Sample data installed

### Steps to reproduce (*)
1. Create Tax Zone - Identifier: DK-25, Zip/Post Code:*, Country: Denmark, Rate Perfect: 25
2. Create Tax Rule - Name: DK25, Tax Rate: DK
3. Adjust Tax settings as attached image backend-tax.jpeg
![backend-tax](https://user-images.githubusercontent.com/5848718/137717311-e075a2b7-08dc-4147-bf8f-eeb347ee44ac.jpeg)
3. Create (A) Simple product to be buyable with price "100" and tax class: None
4. Create (B) Simple product to be buyable with price "0" and tax class: None
5. Create a Bundle product to be buyable with price "1000", Tax Class: Taxable Goods, Price view: As low as, and assign the two created simple products as product options. Give the first product price "100" and the second product price "0".
6. Go to bundle product on frontend, choose variant A and add to basket.

### Expected result (*)
1. I expected the combined product price would be the same on the product page, minicart, basket, checkout.
I am uncertain which price is the correct to show.

### Actual result (*)
1. The product price in the product page is visually not shown correctly. 
The product variant price and combined product price shows including tax from simple product A (which have zero vat) This doesn't match the correctly calculated price in the minicart, basket and checkout.
![frontend-tax](https://user-images.githubusercontent.com/5848718/137717317-c083a180-ec2b-4da1-a661-af2a8adee907.jpeg)

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @kasperth ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots

**Steps to reproduce**
1. Create Tax Zone - Identifier: DK-25, Zip/Post Code:*, Country: Denmark, Rate Perfect: 25
2. Create Tax Rule - Name: DK25, Tax Rate: DK
3. Adjust Tax settings as per the description
4. Create (A) Simple product to be buyable with price "100" and tax class: None
5. Create (B) Simple product to be buyable with price "0" and tax class: None
6. Create a Bundle product to be buyable with price "1000", Tax Class: Taxable Goods, Price view: As low as, and assign the two created simple products as product options. Give the first product price "100" and the second product price "0".
7. Go to bundle product on frontend, choose variant A and add to basket.
8. Observe combined product price is same on the product page, minicart, basket, checkout.
PDP
![image](https://github.com/user-attachments/assets/913ab53d-aef1-455e-a757-9000d61dedf0)
Select the product A
![image](https://github.com/user-attachments/assets/5e7f6bc8-2cac-444a-9ffb-e740f871b330)
Mini Cart
![image](https://github.com/user-attachments/assets/a901a113-f0b5-4f7a-af4a-15327be178a6)
Shopping Cart
![image](https://github.com/user-attachments/assets/b26bedc9-bb3c-4cfc-9e2c-a7efdff7ea97)
Checkout
![image](https://github.com/user-attachments/assets/f383c426-438e-4c94-aaa1-1e956eccfe72)

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.
Thanks.
