### ISSUE TITLE
Some categories and products urls giving 404 error

### ISSUE THREAD

**Issue by baljinderimpinge** [magento/magento2#34395]
1. Magento CE 2.4.0  and has 372 categories and 13k products
2) Staging site url: https://stage.mcfeelys.com/
3) Frontend Access details: 
tgrote@mcfeelys.com
CarafeWandTiarasBetted

Steps to reproduce
Please open this url and then click on first subcategory (CABINET SCREWS)
https://stage.mcfeelys.com/screw-fastener-web-store/shop-screws-by-application.html

Expected result:
Category page should be open with all subcategories & products
Actual result:
Page shows 404 error

@victor-ruiz @victor-v-rad @engcom-Alfa 
Please let me know how to fix such issues

**Comment by engcom-Echo** [comment]
Hi @baljinderimpinge,

The current description is not enough for me to reproduce this as the link is also not working now. In order to try again, can you please update the description with more detailed **'Steps to reproduce'** so that I can reproduce on 2.4-develop instance ?

Thanks

**Comment by engcom-Echo** [comment]
Dear @baljinderimpinge,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks
