### ISSUE TITLE
tailwindui css layout support - colon is not accepted by the pattern

### ISSUE THREAD

**Issue by in-session** [magento/magento2#34430]
I would like to use tailwindui for a project, but unfortunately it is currently not possible because no colon is allowed within the htmlClass. 

```
<!-- Width of 16 by default, 32 on medium screens, and 48 on large screens -->
<div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl"></div>
```

`
<referenceContainer name="header-wrapper" htmlClass="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl" htmlId="header" />
`

`Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value 'page-wrapper flex relative md:p-0' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 1306`

Is there a way to make this compatible?

**Comment by Nurgiel** [comment]
It's really annoying that you can't use some tailwind classes in .xml files.

Is there a way to add a plugin/preference to override this regex from elements.xsd file? Otherwise when is this going to be released as a patch?

Issue was opened for the first time over two years ago and no solution has been given since then:
https://community.magento.com/t5/Can-Magento-do/XSD-regex-override/td-p/312167

<xs:include schemaLocation="urn:magento:framework:View/Layout/etc/elements.xsd"/>
is hardcoded all over the place in vendor/magento/framework/View/Layout/etc/ body.xsd, layout_generic.xsd, layout_merged.xsd, page_layout.xsd, ui_settings.xsd...

**Comment by in-session** [comment]
@Nurgiel 
https://github.com/magento/magento2/pull/34559
