### ISSUE TITLE
grunt exec:[mytheme] fails after @import 'filename' in .less

### ISSUE THREAD

**Issue by dav1dian** [magento/magento2#3447]
Hi.
I've installed magento 2, created my custom theme and now trying to work with .less files using grunt watch task.
sctucture - web/css/
_styles.less
styles-new.less
custom.less
in styles.less i have @import '_styles';
so at first i did grunt exec:[mytheme]

Now, the problem is, that in pu/static i got symlink(i guess) to custom.less, but styles-new.less became not symlink, but copy of my file.. and i don't know the reason, but grunt watch is watching this file instead of original one from app/design

http://prntscr.com/a4hmyh
http://prntscr.com/a4hn7b

I'm running magento 2 on Win7. I can't find way to fight this issue :(

**Comment by alankent** [comment]
Hi. It always watches pub/static is my understanding as that is what Less will read from - but if its a symlink, then this is fine. If a file copy, then watching does not work.

Could you supply a copy of styles-new.less?  What happens is the `magento dev:source-theme:deploy` script uses a symlink if it can, but if the source file includes any "Magento magic", it has to copy the file to replace the magic with standard Less files. So for example, any file with `//@magento_import` is copied (with that instruction expanded to be a series of `@import` statements).  Another one I would look for is using a `Magento_Theme::` style prefix. Those paths I suspect are patched as well, so again a copy is required rather than a symlink.

To detect this sort of change, could you diff the original file to what is in pub/static - I think some differences will be reported which is triggering the copy instead of symlink that you would prefer. If so, could you tell me at least the diff? I am curious to know what the problem is.

**Comment by dav1dian** [comment]
Hello @alankent !
yes, you are right, it always watches pub/static, but this structure only works, if .less files are symlinked from app/design.. otherwise it's watching a copy of a file and not going to change css, after changing that file in app/design.

Here is file - https://drive.google.com/open?id=0ByIwa4gTTVWaMHljMHM4S3hURW8
and i really can't see any differences between files in pub and app.. it's just simpy making copy of a file, which has `@import`

**Comment by eug123** [comment]
Hi @dav1dian ,

Seems it is about `.less` file extension in `@import` directive. You can omit extension -  sources will be found and CSS will be compiled, but magento [will add this extension](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Css/PreProcessor/Instruction/Import.php#L141-L156) to the processed file, so published file content will be different from original source.

Please change your import to `@import '_styles.less';` and check if symlink or copy will be published.

**Comment by MomotenkoNatalia** [comment]
@dav1dian Please let us know if this helps.

**Comment by dav1dian** [comment]
@MomotenkoNatalia @eug123 
`@import '_styles.less';` - works!
Thank you very much, guys :)

**Comment by MomotenkoNatalia** [comment]
@dav1dian  We will be glad to help you solve any problem that may occur ;)

Issue can be closed.
