### ISSUE TITLE
Class Magento\Customer\Block\Address\Renderer\AbstractAddress does not exist

### ISSUE THREAD

**Issue by moleman** [magento/magento2#3448]
When calling "bin/magento setup:di:compile-multi-tenant", it will fail with the error message:

[Magento\Framework\Exception\LocalizedException]
  Class Magento\Customer\Block\Address\Renderer\AbstractAddress does not exist

This only happens when we are using a certain third-party module and not in a vanilla Magento2 installation.

After some investigation, the error occurs because the argument type expected in getFormat(...) in https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Block/Address/Renderer/DefaultRenderer.php#L98 is of the type AbstractAddress and it's undefined in that class. Looking at the history it seems that this commit, https://github.com/magento/magento2/commit/99acfee1f5d0379a636ecf85eba74a892b12dd3e, where "use ...\AbstractAddress" was changed to "use ...\AddressModelInterface", caused the error because the argument type in getFormat(...) should also have been changed to AddressModelInterface.

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-49425

**Comment by pivulic** [comment]
Including patch in .txt format (even though the original comment is clear enough)
[Patch-Magento_Customer-AbstractAddress-DoesNotExist.txt](https://github.com/magento/magento2/files/136225/Patch-Magento_Customer-AbstractAddress-DoesNotExist.txt)

**Comment by azambon** [comment]
I just made a pull request for this fix.
As an additional note, the problem shows up only when there's a plugin for the Magento\Customer\Block\Address\Renderer\DefaultRenderer block or one of its parents. When Magento tries to instantiate this class, the interceptor generation process tries to read each method's signature in order to generate the interceptor code. When the getFormat method is found, the code tries to load the Magento\Customer\Block\Address\Renderer\AbstractAddress class. This class doesn't exist, so an exception is thrown.

So, to reproduce the bug:
- declare a plugin for the Magento\Customer\Block\Address\Renderer\DefaultRenderer block or one of its parents;
- go to the order detail page in the admin, or do as moleman said and run "bin/magento setup:di:compile-multi-tenant".

**Comment by pivulic** [comment]
:+1:

**Comment by slavvka** [comment]
@moleman, the fix has been merged. See 472ff521 and a4b4f2a. Thank you for your contribution to Magento 2!
