### ISSUE TITLE
Page Cache is not cleared for the parent product on the child product save

### ISSUE THREAD

**Issue by stupachenko** [magento/magento2#34508]
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Admin Panel > System > Index Management and set Index Mode = Update By Schedule for all indexes.
2. In the Admin Panel create a new configurable product with one simple product.
3. Open this product on the frontend and select options.
4. In the Admin Panel update the price for the simple product.
5. Return to the frontend, refresh the configurable product page and select options.

### Expected result (*)

1. The price of the configurable product must be updated on the frontend.

### Actual result (*)

1. The price is not updated.

**Comment by stupachenko** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @stupachenko,
We have observed that Sku price is not reflecting on frontend with updated price in Admin portal(Backend) .
Scenario 1:
1. Create a configurable product with different prices for color sku's
2. Observe that price is not reflecting on frontend as we configured in backend.


Hence marking that issue is reproducible on Magento 2.4 Develop.
Please find the attached video for reference.
https://user-images.githubusercontent.com/51681379/140276889-7dc6ab14-f4df-4a20-a6cc-21385b333a59.mp4

**Comment by engcom-Alfa** [comment]
We have re-test the same scenario in the cloud env.

**Comment by engcom-Alfa** [comment]
> Hi @stupachenko, We have observed that Sku price is not reflecting on frontend with updated price in Admin portal(Backend) . Scenario 1:
> 
> 1. Create a configurable product with different prices for color sku's
> 2. Observe that price is not reflecting on frontend as we configured in backend.
> 
> Scenario 2: sometimes on selection of color sku , price reflects in front end.
> 
> Hence marking the issue is reproducible on Magento 2.4 Develop. Please find the attached video for reference. https://user-images.githubusercontent.com/51681379/140276889-7dc6ab14-f4df-4a20-a6cc-21385b333a59.mp4

As per the scenario 2 here, what does _sometimes_ means here. Is it _after sometime of the price update_?

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @stupachenko,

We have rechecked the issue in Magento 2.4-develop cloud instance and the issue is reproducible for us. We have followed the exact same steps mentioned in the main description. The latest price is not reflected for us as well.

But after clearing cache, and refreshing the frontend, the latest price is reflected. So confirming the issue.

Thanks

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Hi @stupachenko ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/search?q=AC-1705&type=commits).
Thanks!
