### ISSUE TITLE
Magento session ends after making a GraphQL request

### ISSUE THREAD

**Issue by malero** [magento/magento2#34550]
### Preconditions (*)
1. New issue when upgrading one of our sites from 2.3 to 2.4
2. The following commit has caused the issue
[937a3e2d16183c3e9dd9220ce383e578a2dff50e](https://github.com/magento/magento2/commit/937a3e2d16183c3e9dd9220ce383e578a2dff50e)

### Steps to reproduce (*)
1. Login to a Magento store and start a session
2. Make a GraphQL request. I'm not sure if all queries are affected or just the one we are using, which is the categories query
3. Refresh the page and see that you're logged out

### Expected result (*)
1. The user remains logged in

### Actual result (*)
1. The ClearCustomerSessionAfterRequest plugin logs the customer out

### Note
I believe this to be a bug with Magento 2.4 OR a documentation issue. If you look at the [generateCustomerToken mutation](https://devdocs.magento.com/guides/v2.4/graphql/mutations/generate-customer-token.html), it mentions session-based authentication as an alternative to making requests with a bearer token.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @malero,

Thanks for posting this issue!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. Please let us know the specific version you upgraded. It helps us in the reproduction of the issue.

Thanks

**Comment by peacefultruth** [comment]
I ran into this issue after recently upgrading, the cause of it seems to be [vendor/magento/module-customer-graph-ql/Plugin/ClearCustomerSessionAfterRequest.php].

Is there a particular reason this was introduced?

**Comment by malero** [comment]
@peacefultruth It is most likely a bug. It sounds like they're working on it.

**Comment by peacefultruth** [comment]
@malero Well there are two parts to the changes which are causing this issue:

1. the population of customer data into the session (which I assume is about making any dependency of the graphql resolver execution be able to operate without requiring refactoring of nested dependencies which assume the customer data is in the session, this is just speculation).
2. The clearing of the customer session after any graphql call, note the customer session is a separate thing from the customer data on the session.


The thing is, you’re just speculating that it’s a bug, and to let them work on it (why exactly you’re fighting for the maintainers _not_ to communicate about a pretty severe issue is just mindboggling to me), but it could turn out to be intended behavior, if the maintainers have an idea as to exactly what they’re trying to do and can talk with us about it, it would help with making a customization to deal with the issue as we wait for an official patch, if a change gets accepted at all (again, it could be what they’re wanting to do).

There are some serious businesses that depend on Magento and need more than just speculation that it’s “likely a bug and being worked on”, the businesses won’t have patience for me to tell them to wait for another update for the update.

So moving forward, there are two potential customizations I can think of to mitigate this issue for an existing project which uses Magento that doesn’t want to completely refactor to token auth currently (if this issue is not a problem for token auth that is):

1. Remove the introduced changes in your own app customization, pretend they never existed in the first place, but then who knows what will happen with the next upgrade.
2. In your own app customizations, before they set things on the session, store previous values, and set them back on the sessions afterwards instead of just resetting the customer session to zero.

Or is there something more going on where these options aren’t viable?

**Comment by engcom-Hotel** [comment]
The issue has been fixed and merged with mainline 2.4-develop. The commit id for the same is `d117a194e43dc8f9a2663c4a8c58597fbc9f0d92`

**Comment by mcfedr** [comment]
I understand this fix has not made it into a release of magento?
