### ISSUE TITLE
VAT ID won't appear in checkout shipping address unless the customer/create_account/vat_frontend_visibility is Yes

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#34683]
As the title says, currently users cannot enable address vat_id only on the checkout page because it won't show unless the option `customer/create_account/vat_frontend_visibility` is enabled.  This option clearly refers to the account creation.

There's no apparent reason why that is, other than that the system is configured to check this configuration option instead of the `customer/address/taxvat_show` option. This option clearly refers to the customer's address settings. 

This is a bug because currently if we want to show vat_id in the addresses we also have to show it in the registration page. This doesn't make sense when there are two configuration options for each one.

### Preconditions (*)
1. Magento 2.4.1 - 2.4.3

### Steps to reproduce (*)
1. set `customer/create_account/vat_frontend_visibility` to No
2. set `customer/address/taxvat_show` to optional or required
3.  visit the checkout page

### Expected result (*)
1. the vat_id field should show in the address because of the setting `customer/address/taxvat_show` being optional or required

### Actual result (*)
1. VAT ID doesn't show up

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ioweb-gr** [comment]
@magento give me 2.4-develop instance

**Comment by ioweb-gr** [comment]
From the demo instance 

Config

![image](https://user-images.githubusercontent.com/20220341/142687331-11c87f93-85e3-4273-b03d-eeb0868354db.png)


Checkout

![image](https://user-images.githubusercontent.com/20220341/142687501-ae2b5dd1-c504-4ef2-a743-8443a6ffaf1d.png)


If I enable the first option for customer registration, then it shows. 

![image](https://user-images.githubusercontent.com/20220341/142687609-794def44-a7e9-4c9d-b1bf-bf6ae0234de6.png)

But registration is weird then as we don't need the VAT ID there

![image](https://user-images.githubusercontent.com/20220341/142687680-a8f29f5d-b5f3-481e-9200-65f15c3312dd.png)

**Comment by engcom-Hotel** [comment]
Hi @ioweb-gr,

Thank you for reporting the issue.

We are able to reproduce it on Magento 2.4-develop/2.4.3/2.4.3-p1

Steps followed to reproduce this issue.

1. Enable Show Tax/VAT Number from Stores->Configuration->Customer->Customer Configuration->Name and Address Option
2. VAT field not visible on Magento Checkout Address Form until
3. Enable Show VAT Number on Storefront from Customer New Account Options Group.
4. But if we enable it, the VAT field will also be available on Create New Customer Page.

Hence confirming the issue.

Thanks

**Comment by glo80326** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,

Based on the comments from JIRA, The Product owner has confirmed this as an expected Magento behavior & the concerned functionality is working as expected. The gaps in the documentation on our devedocs will be addressed in our further development guild meetings

Hence closing this issue.

Thanks

**Comment by ioweb-gr** [comment]
Hi @engcom-Hotel, could you write a quick word to us about the reasoning behind this design choice so we can understand why that is set like this as we don't have access to Jira?

**Comment by engcom-Hotel** [comment]
Hello @ioweb-gr,


1. Stores-> Configurations->Customer->Customer Configuration->Create New Account Options -> Show VAT Number on Storefront ->yes
2. Stores-> Configurations->Customer->Customer Configuration->Name & Address Options -> Show Tax/VAT Number ->required/optional

The customer will have the option to input his/her VAT number during registration & also during checkout. But both of them are treated differently.
The VAT Number entered during registration would be associated with the customer_entity table -  taxvat column & would be part of the customer profile. It can be verified from the Customers Grid Listing on the admin panel under the Tax Vat Number column. This data can be modified by the customer via storefront -
My Account -> Account Information -> Edit.

Whereas the VAT number entered by the customer during checkout along with the Address section is tied together as a part of his/her Billing/Shipping Address. This can be verified from admin panel at Customers -> Customer Information -> Addresses -> Default Billing Address/ Default Shipping Address. The customer can modify this data via storefront - My Account -> Address Book -> Default Billing Address/ Default Shipping Address.
PO has confirmed this as the expected behavior.

That's why we have closed this issue.

Thanks

**Comment by ioweb-gr** [comment]
Hi thanks, perhaps I didn't phrase it correctly, my question is why do we have to enable it on registration if we only need it on checkout?

We want to use only the one tied to the billing / shipping address but forced to use both and it would be nice to know the reasoning behind a forced choice

**Comment by ErikDW1** [comment]
I'm on a 2.4 dev instance and have enabled both options:

- Stores-> Configurations->Customer->Customer Configuration->Create New Account Options -> Show VAT Number on Storefront ->yes
- Stores-> Configurations->Customer->Customer Configuration->Name & Address Options -> Show Tax/VAT Number ->required

The VAT number input shows on Account creation page but not in checkout page in Shipping Address. Can anyone help me?
Thanks
