### ISSUE TITLE
Specified rule does not allow auto generated coupons

### ISSUE THREAD

**Issue by ed007m** [magento/magento2#34749]
### Preconditions (*)

1. Magento 2.4.3
2. Any product available for purchase.

### Steps to reproduce (*)

1. Create SalesRule
2. Under Rule Information section:
    2.1. Enter Rule Name
    2.2. Activate rule
    2.3. Set  Coupon setting to "Auto"
    2.4. Select appropriate website and customer group.
3. Under Action section:
    3.1. Set Action to -> Percent of product price discount
    3.2. Put Discount amount greater than 0.
4. Save the rule by Clicking "Save and Continue editing".
5. Go to "Manage Coupon Codes" section
    5.1. Fill Coupon Qty greater than 0.
    5.2. Fill Coupon Length greater than 0.
    5.8. Press "generate" button.
6. Choose any coupon code and try to apply it on the cart page.    

### Expected result (*)

1. Coupon code is applied

### Actual result (*)

1. Coupon code is not valid
Backend error message: "Specified rule does not allow auto generated coupons"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [*] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Error message is generated on the next code line:
[vendor/magento/module-sales-rule/Model/CouponRepository.php:116](https://github.com/magento/magento2/blob/2.4.3/app/code/Magento/SalesRule/Model/CouponRepository.php#L118)

Perhaps condition should be like:
`$coupon->getType() == $coupon::TYPE_GENERATED && (!$rule->getUseAutoGeneration() || $rule->getCouponType() !== $rule::COUPON_TYPE_AUTO`

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Steps performed:
Created Cart Price Rule (Admin - Marketing - Cart Price Rules - Add New Rule - Specific Coupon - Auto Generation enabled
Actions - Percent of Product Price Discount - Save
Manage Coupon Codes - Generated coupon codes)
Front-end - Add Product to Cart - Apply the generated coupon - No issue.
User able to apply coupon and place order.
![image](https://user-images.githubusercontent.com/60198231/144440450-7b414405-89f0-411b-9ce5-3cf1c616f255.png)

![image](https://user-images.githubusercontent.com/60198231/144440399-8c74b6d8-bf8d-4819-bef2-1ac08bff1429.png)

@ed007m kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by ed007m** [comment]
Ah, common guys
In the steps to reproduce there were nothing about "Specific coupon" type. I've mentioned "Auto".
<img width="839" alt="Screenshot 2021-12-02 at 16 34 36" src="https://user-images.githubusercontent.com/6236299/144442429-7c450612-362c-4593-a292-0114e6028a2f.png">

**Comment by engcom-November** [comment]
Hi @ed007m ,
2.4-develop version of Magento doesn't have "Auto" option in drop down. Instead checkbox "Use Auto Generation" will be present and the behavior is same as 2.4.3. Multiple Coupon codes can be generated using this feature. Kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/145022458-20aa33b5-f821-4e4c-abe7-0671c668890d.png)

Thank you.

**Comment by ravi0403** [comment]
auto generate code quantity not save
