### ISSUE TITLE
Grouped product invokes protected function of other class instance

### ISSUE THREAD

**Issue by mischabraam** [magento/magento2#34746]
https://github.com/magento/magento2/blob/203a44f9e755fa6d2e057f1b99efbaff17546a80/app/code/Magento/GroupedProduct/Model/Product/Type/Grouped.php#L397

```
$_result = $subProduct->getTypeInstance()->_prepareProduct($buyRequest, $subProduct, $processMode);
```

In above highlighted line you can see that a class is being fetched to invoke a function on it. The class is an instance of `AbstractType` and the function is `_prepareProduct`. However, the function is `protected`. This should be a `public` function?

**Comment by mischabraam** [comment]
I think this is an OOP violation. It works because of https://bugs.php.net/bug.php?id=81369.

**Comment by engcom-Delta** [comment]
Hi @mischabraam   ,

Thank you for raising an issue , we are happy to work on this issue . Kindly provide steps to reproduce , expected results, actual results with screenshots.

Regards,

**Comment by engcom-Echo** [comment]
Hi @mischabraam, 

Thank you for reporting the issue.

I have gone through the code and found that the function “_prepareProduct” is working because of the parent class extension and is working as per the scope of the protected function. It's not violating any OOPS rules. 

Have a look at the following code sample and observe the behaviour of function “call_user_func_array” with the class extends and without extends keyword. The issue seems to be mentioned in this php [ticket](https://bugs.php.net/bug.php?id=81369) with the function “call_user_func_array”.
```
<?php 
class One {
	protected function cat() { return 'this is cat'; }
}

class MyClass
{
    public $public = 'Public';
    protected $protected = 'Protected';
    private $private = 'Private';

    function printHello()
    {
        echo $this->public;
        echo $this->protected;
        echo $this->private;
        echo $this->cat();

        echo call_user_func_array([new MyClass, 'cat'], []) . PHP_EOL; // Works
    }
    protected function cat() { return 'this is cat'; }
}

$obj = new MyClass();
echo $obj->public; // Works
echo $obj->protected; // Fatal Error
$obj->cat(); // fatal error
$obj->printHello(); // Shows Public, Protected and Private

echo call_user_func_array([new MyClass, 'cat'], []); // Fatal error
echo call_user_func_array([new One, 'cat'], []); // Fatal error 
class MyClass2 extends One
{
    public $public = 'Public';
    protected $protected = 'Protected';
    private $private = 'Private';

    function printHello()
    {
        echo $this->public;
        echo $this->protected;
        echo $this->private;
        echo call_user_func_array([new One, 'cat'], []) . PHP_EOL; // Works only when "One" class is extended
    }
}

$obj = new MyClass2();
echo $obj->public; // Works

$obj->printHello(); // Shows Public, Protected and Private
```
Please check and update. If you still think it is an issue then please provide some more details, accordingly I’ll proceed on this.

Thanks

**Comment by mischabraam** [comment]
Because it can (and works) it doesn't mean it's correct. With PHP you can write very very ugly code that works even though it shouldn't. It's up to us as developers not to abuse it, but write good code that follows the principles described.

Scoping of `private` should only be invoked by the class itself.
Scoping of `protected` should only be invoked by the class itself and inheriting classes.
Scoping of `public` can be invoked by anyone.

Using the magic `__call` makes it possible to call any scoped function and thus break above stated principles. Very dangerous, as developer I choose which functions I expose publicly or not for a reason. Just because you can invoke them through the nasty `__call` exposure doesn't mean that you should actively use it.
I understand using this for the EAV classes and such, where we can dynamically call functions to get or set data of attributes. But in this case we know exactly which function we want to call (`_prepareProduct`), which is not dynamic at all. And thus should not be depending on the `__call` exploit.

Honestly, above is probably just an opinion.

**Comment by engcom-Hotel** [comment]
Hello @mischabraam,

We have checked this issue in Magento 2.4-develop branch in debug mode. We have added the breakpoint on the line you mentioned in the main description and below are our findings:

- `$subProduct->getTypeInstance()` method is returning the object of type `app/code/Magento/Catalog/Model/Product/Type/Simple.php`
- Class `app/code/Magento/Catalog/Model/Product/Type/Simple.php` extends `\Magento\Catalog\Model\Product\Type\AbstractType` in which we have `_prepareProduct` method with protected access modifier.
- As per the visibility definition, members declared protected can be accessed only within the class itself and by inheriting and parent classes.

As per our findings, the behavior is as expected. Please guide us if we missed anything in order to analyze this issue.

Thanks

**Comment by mischabraam** [comment]
To be more specific `$subProduct->getTypeInstance()` returns an instance of `\Magento\Catalog\Model\Product\Type\AbstractType`. In this case you call a protected function directly on the returned instance. This would be equivalent to first assign the returned instance to a variable and then call the function, like per example:

```php
$instance = $subProduct->getTypeInstance();
$_result = $instance->_prepareProduct(...);
```

For this to work without the spoken "bug", the function `_prepareProduct` needs to be public.

If you would call the function only inside the instance itself, it would be enough to have it protected, like per example:

```php
class Example 
{
    public function doStuffPublicly()
    {
        return $this->doPrivateOrProtectedStuff();
    }

    protected function doPrivateOrProtectedStuff()
    {
        return 'stuff';
    }
}
```

```php
$instance = new Example();
$instance->doStuffPublicly(); // correct
$instance->doPrivateOrProtectedStuff(); // incorrect and won't work in this example

$someFactoryInstance->getInstanceOfExample()->doPrivateOrProtectedStuff(); // incorrect either
```


It works in Magento because, like you imply, both the calling class instance and the returned class instance are of type `\Magento\Catalog\Model\Product\Type\AbstractType`. Which is at least weird. I debugged it also and yes it works. 
Does it work when the calling class instance is **not** of `...AbstractType`? Like the issue in PHP says, it's a bug and you shouldn't rely on it, it might fixed in the future.

Maybe I'm comparing too much to other languages where this won't work (and it shouldn't). If you think otherwise, fine by me and you could close this issue.

**Comment by engcom-Hotel** [comment]
Hello @mischabraam,

Thanks for the reply!

I agree with your point, even I have also tried the same change in order to get the type of the instance.

> This would be equivalent to first assign the returned instance to a variable and then call the function, like per example:
> 
> ```
> $instance = $subProduct->getTypeInstance();
> $_result = $instance->_prepareProduct(...);
> ```

But as I mentioned in comment [here](https://github.com/magento/magento2/issues/34746#issuecomment-1033693838). the protected function can be accessed only within the class itself, by inheriting and parent classes. 

I am not closing this issue for now. Let's wait for more contributions to this.

CC: @ihor-sviziev @mrtuvn 

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mischabraam,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
