### ISSUE TITLE
Very slow `catalogrule_product` index even when no catalog rule exists

### ISSUE THREAD

**Issue by dudzio12** [magento/magento2#34784]
On a Magento 2.4.3 instance:
- I don't have any catalog rule
- I have ~100k products, mostly configurable
- I have 4 websites
- Have almost all my indexes setup on scheduled mode

### Steps to reproduce (*)

1. Add some ids (or update some product attributes) into `catalogrule_product_cl` table.
2. Run `indexer_update_all_views` CRON job.

### Expected result (*)

1. Product ids quantity should not have that big impact in index processing time.
2. The index process should end in a reasonable time.

### Actual result (*)

1. Product ids quantity is brutally impacting execution time.
2. Index process should end in a moment, when no catalog rule is set.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dudzio12** [comment]
```php
protected function doReindexByIds($ids)
    {
        $start = round(microtime(true) * 1000);
        $this->cleanProductIndex($ids);

        /** @var Rule[] $activeRules */
        $activeRules = $this->getActiveRules()->getItems();

        foreach ($activeRules as $rule) {
            $rule->setProductsFilter($ids);
            $this->reindexRuleProduct->execute($rule, $this->batchCount);
        }

        foreach ($ids as $productId) {
            $this->cleanProductPriceIndex([$productId]);
            
            ## I've added `if` statement as seen below and there is no need to reindex prices
            ## if only  above cleaning cleans it correctly and no activeRule exists.
            ## That only sppeds up indexation process more that 10 times
            if (count($activeRules) > 0) {
                $this->reindexRuleProductPrice->execute($this->batchCount, $productId);
            }

        }

        $this->reindexRuleGroupWebsite->execute();

        $end = round(microtime(true) * 1000);

        echo "End indexing in " . ($end-$start) . "ms for " . count($ids) . " products. \n\n";
    }
```

**Comment by dudzio12** [comment]
I'll prepare PR and run some tests with that change implemented. It won't fix non optimal index, but will lock some unnecessary code execution.

**Comment by dudzio12** [comment]
Fixed by https://github.com/magento/magento2/pull/34785

**Comment by aligent-lturner** [comment]
The performance of this indexer appears to be incredibly slow, as it reindexes products one by one, instead of in batches.
I've taken a quick look at the code involved, and I can't really see a good reason why this has been done.

The select builder used is here - https://github.com/magento/magento2/blob/0a834cce01c3d924d450c9a71123d9ac6de68b62/app/code/Magento/CatalogRule/Model/Indexer/RuleProductsSelectBuilder.php#L81-L109

A single product id is passed in, and used to restrict the query to that product, but the query would still work if multiple products were passed in and an `IN` clause was used instead.

Similarly, the place that calls and then uses the query built by `RuleProductsSelectBuilder` is here - https://github.com/magento/magento2/blob/0a834cce01c3d924d450c9a71123d9ac6de68b62/app/code/Magento/CatalogRule/Model/Indexer/ReindexRuleProductPrice.php#L88-L112

This creates a key value using the product id coming from the data the query returns, so it too would still work with multiple products.

Maybe I'm missing something here, but I think that changing these functions to take in an array of product ids instead of a single one (and then batching appropriately in `IndexBuilder`) would dramatically reduce the amount of time required.

**Comment by leonhelmus** [comment]
@hostep have you seen this fix already. This should improve speed for catalog product rule.
