### ISSUE TITLE
Default country selection issue while creating new customer from backend

### ISSUE THREAD

**Issue by keyurshah070** [magento/magento2#3483]
Hello,

While creating a new customer from back-end default country selection doesn't display on adding a new address.

![new customer customers customers magento admin](https://cloud.githubusercontent.com/assets/17308601/13176846/1b521470-d73b-11e5-8cc1-8c87ec2055f2.png)

To reproduct this step
- Login into magento admin panel
- Go to Customers > All Customers > Add New Customer > Click on left tab [Addresses]
- Click on Add New Addresses [ On country dropdown it display blank] 

**I think this is the bug because it should display a default country selection on dropdown [As per system configuration selection]**

Thanks.

**Comment by sevos1984** [comment]
Internal ticket MAGETWO-49792

**Comment by haocongnghe** [comment]
Any update on this issues ? I see it's still on 2.1.3 but it's fixed on 2.1.5. Can you give me git commit to fix it ?

**Comment by magento-engcom-team** [comment]
@keyurshah070, thank you for your report.
We've created internal ticket(s) MAGETWO-49792 to track progress on the issue.

**Comment by pradeep-wagento** [comment]
Hi @magento-engcom-team, @okorshenko 
I investigated this issue and working on fix for it.  
Please assign to me.
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @keyurshah070. Thank you for your report. 
The issue has been fixed in magento/magento2#13024 by @pradeep-wagento in 2.2-develop branch
Related commit(s):
 - [2fb34ef4d42552ccbf0e1b7138630f05f0f1bb5f](https://github.com/magento/magento2/commit/2fb34ef4d42552ccbf0e1b7138630f05f0f1bb5f)
 - [c0ef7803a7b2fdd62dbb59b1199333d3f473203d](https://github.com/magento/magento2/commit/c0ef7803a7b2fdd62dbb59b1199333d3f473203d)
 - [8266e0304d6ccbe705fb33bfe895e759c28a537f](https://github.com/magento/magento2/commit/8266e0304d6ccbe705fb33bfe895e759c28a537f)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @keyurshah070. Thank you for your report. 
The issue has been fixed in magento/magento2#14204 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [255b682ef61ca83e896ec562c1c9914c0e875571](https://github.com/magento/magento2/commit/255b682ef61ca83e896ec562c1c9914c0e875571)
 - [e37ae24b9a7df0c66139e7f3d0929c96ee3f2116](https://github.com/magento/magento2/commit/e37ae24b9a7df0c66139e7f3d0929c96ee3f2116)

The fix will be available with the upcoming 2.3.0 release.
