### ISSUE TITLE
Element 'route': Missing child element(s). Expected is ( resources ).

### ISSUE THREAD

**Issue by usman-xs4arabia-dev** [magento/magento2#34843]
I'm using magento 2.4.3-p1 and while running setup:upgrade commend I'm getting this error.

**Comment by andrewbess** [comment]
Hello @usman-xs4arabia-dev 
Could you please provide screenshot and stack trace of your error?
Thank you in advance.

**Comment by usman-xs4arabia-dev** [comment]
![image](https://user-images.githubusercontent.com/96001451/146675939-0cb1a12c-3d02-4740-8ba8-54e0665258d0.png)


> Hello @usman-xs4arabia-dev Could you please provide screenshot and stack trace of your error? Thank you in advance.

**Comment by usman-xs4arabia-dev** [comment]
> Hello @usman-xs4arabia-dev Could you please provide screenshot and stack trace of your error? Thank you in advance.



> Hello @usman-xs4arabia-dev Could you please provide screenshot and stack trace of your error? Thank you in advance.

Moreover there is another module Magento_MysqlMq in which I'm also getting the same error. So two module Magento_Ampq and Magento_MysqlMq.

**Comment by usman-xs4arabia-dev** [comment]
![image](https://user-images.githubusercontent.com/96001451/146677009-ee2eb92a-58c7-46f7-b5ea-336563523848.png)


> Hello @usman-xs4arabia-dev Could you please provide screenshot and stack trace of your error? Thank you in advance.

**Comment by engcom-Echo** [comment]
Hi @usman-xs4arabia-dev,

Thank you for reporting the issue.

Have you run setup:di:compile after adding API routes ? You can find similar issue with its solution [here](https://stackoverflow.com/questions/66122868/error-on-magento-setupupgrade-element-route-missing-child-elements-expe). Hope it helps.

You can also raise similar queries on various Magento forums like [Magento Stack Exchange](https://magento.stackexchange.com/) or [Magento Community](https://community.magento.com/) platform and there you may get some help. Can you please update if your issue is anyway related to Magento core development ? If yes, please update relevant details in Issue description or otherwise we'll have to close this issue.

Thanks

**Comment by engcom-Echo** [comment]
Dear @usman-xs4arabia-dev,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks
