### ISSUE TITLE
Cart Rule product subselect condition is missing total including tax option

### ISSUE THREAD

**Issue by johnulecan** [magento/magento2#34871]
### Preconditions (*)

1. 2.4.3-p1

### Steps to reproduce (*)

1. Create a Cart price rule and add a products subselection condition. There is only a total amount option limiting the condition to be set only for a value excluding tax.

### Expected result (*)

1. Have the option to add the the total excluding tax as a condition option in products subselection

### Actual result (*)

1. There is only one option to select total amount excluding tax in the product subselection condition

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by johnulecan** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hi @johnulecan,

Thank you for reporting the issue.

Although I think it is more of a feature that you are requesting. Since you are asking for an additional option apart from the existing ones in the ‘Cart Price Rule’.

So for now, I am moving this issue to the ‘feature request’ board where it’ll be further analyzed and proper action can be taken accordingly. If you think, it is an issue/bug related to existing functionality, please update the description with the issue details.

Thanks
