### ISSUE TITLE
Magento page is not loading properly after migration

### ISSUE THREAD

**Issue by ghost** [magento/magento2#34888]
Hi github folks ,
I migrated my magento 2.3.7 from cloud hosting to VPS Ubuntu 18.04 Server , after the successful migration of the website the magento website is not loading properly . I can tell the whole website is messed up (All the pages layout are not proper)
I dont know that is because of css ,js issue or migration issue .
I am attaching my website screenshot please anyone suggest a solution ..it will be great !![
![image_2021_12_27T16_43_44_076Z](https://user-images.githubusercontent.com/92668606/147491475-74a85d25-9958-418c-967c-d637212dc87a.png
![image_2021_12_27T16_43_14_421Z](https://user-images.githubusercontent.com/92668606/147491527-041ffa14-6ca7-4aec-95cd-b4fb04b53d5a.png)
)

**Comment by engcom-Echo** [comment]
Hi @homedirect76,

Thank you for reporting the issue.

I think that your Magento is not properly installed to your new server after migration. Looks like resources are not getting pointed to correct location. 

You can also raise similar queries on various Magento forums like [Magento Stack Exchange](https://magento.stackexchange.com/) or [Magento Community](https://community.magento.com/) platform and there you may get some help. Can you please update if your issue is anyway related to Magento core development ? Otherwise we'll have to close this issue. 

Thanks

**Comment by engcom-Echo** [comment]
Dear @homedirect76,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks
