### ISSUE TITLE
Can magento2-functional-testing-framework be removed? Getting in the way of an upgrade.

### ISSUE THREAD

**Issue by pmatra** [magento/magento2#34885]
I'm trying to upgrade 2.3.1 to 2.3.7 using Composer V2 up to date using php 7.4 and I get an error message that

```
Problem 1
    - magento/magento2-functional-testing-framework is locked to version 2.3.9 and an update of this package was not requested.
    - magento/magento2-functional-testing-framework 2.3.9 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0|~7.2.0 -> your php version (7.4.26) does not satisfy that requirement.
```

When I use PhP 7.1 I get this error

```
[InvalidArgumentException]
  Package magento/product-community-edition at version 2.3.7-p1 has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - magento/product-community-edition 2.3.7-p1 requires php ~7.3.0||~7.4.0 which does not match your installed version 7.1.33.

```

I cannot get around this update because magento2-functional-testing-framework is getting in the way. Can it be updated separately? Or be removed since it is not being used?

**Comment by engcom-Echo** [comment]
Hi @pmatra,

Thank you for reporting the issue.

I think you are getting requirement compatibility related errors which you'll have to met in order to install new version of Magento. You can check [this](https://magento.stackexchange.com/questions/322661/magento-2-4-composer-php-7-4-error-magento-magento2-functional-testing-framewo) query and see if it helps.

You can also raise similar queries on various Magento forums like [Magento Stack Exchange](https://magento.stackexchange.com/) or [Magento Community](https://community.magento.com/) platform and there you may get some help. Can you please update if your issue is anyway related to Magento core development ? Otherwise we'll have to close this issue. 

Thanks

**Comment by pmatra** [comment]
Thank you very much for your help! It helped. The Community could not solve my problem. I appreciate your advice. I will try Stack Exchange.
