### ISSUE TITLE
CURL Json POST

### ISSUE THREAD

**Issue by Grohotun** [magento/magento2#3489]
Using  \Magento\Framework\HTTP\Client\Curl doesn't support json posts, because it used only

$this->curlOption(CURLOPT_POSTFIELDS, http_build_query($params));

But need: 

CURLOPT_POSTFIELDS, json_encode($params))

**Comment by veloraven** [comment]
@Grohotun thank you for reporting.
Is this issue still actual?
Please close it if it is not.
Please specified Magento version if it is.

**Comment by voleye** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by okorshenko** [comment]
@Grohotun this issue is resolved now by your PR: https://github.com/magento/magento2/pull/8373 Thank you!

**Comment by magento-engcom-team** [comment]
Hi @Grohotun. Thank you for your report. 
The issue has been fixed in magento/magento2#14151 by @simpleadm in 2.1-develop branch
Related commit(s):
 - [a676af86fe11a6bc1ecf4e46fe413afeef4ac14f](https://github.com/magento/magento2/commit/a676af86fe11a6bc1ecf4e46fe413afeef4ac14f)

The fix will be available with the upcoming 2.1.14 release.

**Comment by Grohotun** [comment]
@magento-engcom-team will be this issue also updated on 2.1+ versions?

**Comment by magento-engcom-team** [comment]
Hi @Grohotun. Thank you for your report. 
The issue has been fixed in magento/magento2#14481 by @simpleadm in 2.3-develop branch
Related commit(s):
 - [1f3cc4da0e479252f46d402b8b3dcdff125f662a](https://github.com/magento/magento2/commit/1f3cc4da0e479252f46d402b8b3dcdff125f662a)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment]
Hi @Grohotun. Thank you for your report. 
The issue has been fixed in magento/magento2#14169 by @simpleadm in 2.3-develop branch
Related commit(s):
 - [03bbca68e9b6822f06a34bb1d60b9785b0e45b56](https://github.com/magento/magento2/commit/03bbca68e9b6822f06a34bb1d60b9785b0e45b56)

The fix will be available with the upcoming 2.3.0 release.
