### ISSUE TITLE
Latest data doesn't show at front end after addding data in my custom module

### ISSUE THREAD

**Issue by MIANZAHOOR** [magento/magento2#34906]
### Summary (*)

Latest data does not show at front-end after submitting form in my custom module. when I clear cache then latest data show at front end.

### Expectation (*)
Help me! how to fix that problem.

when I disable cache my module work correctly but I want to displaying latest data at front side without disable cache.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment]
Hi @MIANZAHOOR,

Thank you for reporting the issue.

However, the issue description is not enough for us to reproduce it. By the looks of it, issue seems to be with your custom code. You can also raise similar queries on various Magento forums like [Magento Stack Exchange](https://magento.stackexchange.com/) or [Magento Community](https://community.magento.com/) platform and there you may get some help. 

If you think the issue is anyway related to Magento core development, please update below details in Issue description:

1. Summary of the issue
2. Information on your environment
3. Steps to reproduce
4. Expected and actual results

Thanks

**Comment by thecoachsmb** [comment]
There are 3 ways to achieve this.

1. Disable cache from layout xml for block
2. Disable cache for block programatically
3. Using Varnish Cache

All these 3 methods, [I have explainded in this article](https://www.thecoachsmb.com/how-to-disable-the-cache-for-the-block-in-magento-2/).

**Comment by krishprakash** [comment]
Hi @MIANZAHOOR, Feel free to reopen once you update all necessary details to reproduce this issue.
Thanks
