### ISSUE TITLE
Listings being deleted from magento 2.2.6 please help

### ISSUE THREAD

**Issue by ghost** [magento/magento2#34901]
### Preconditions (*)

1.  magento 2.2.6

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*) stop listings from being deleted

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-Echo** [comment]
Hi @chris197645,

Issue description is empty. Can you please update issue description with below details of the issue so that we can check further:

1. Summary of the issue
2. Information on your environment
3. Steps to reproduce
4. Expected and actual results

Thanks

**Comment by engcom-Echo** [comment]
Dear @chris197645,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks
