### ISSUE TITLE
price and base_price with same value even though order is with non base currency

### ISSUE THREAD

**Issue by nunogato** [magento/magento2#34902]
When creating an order with a configurable product (not tested with others) and setting up a custom price, magento saves on the database the price and base_price as the same value as base_price.

When printing invoices it gets the 'price' but as it's wrong the invoice is with wrong data.

### Preconditions (*)
1. Magento 2.3.7-p2

### Steps to reproduce (*)
1. create order for existing customer through backend
2. Change the order currency to other than the base currency 
3. add a product to the order, tested with a configurable one
3. change the price to a custom price
4. Fill all other fields and submit the order

### Expected result (*)

1. Product price should show a different value for original currency and order currency

### Actual result (*)
1. Product price shows the same value for both currencies but subtotal and row total are correct

![image](https://user-images.githubusercontent.com/32461691/147684490-4237244e-dc27-464d-a64a-5a01c32ec693.png)

This issue then propagates everywhere where you call getPrice() on a order item as it's actually wrong on the database
![image](https://user-images.githubusercontent.com/32461691/147684620-f9941087-2e8c-47a1-a7bb-ea4426c6461e.png)
![image](https://user-images.githubusercontent.com/32461691/147684711-44e5840f-dd10-401c-b6de-e9af85fd9d8c.png)

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by nunogato** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @nunogato,

Thank you for reporting the issue.

I tried to reproduce this issue with your provided steps but this issue is not occurring in Magento 2.4-develop version. Attached screenshots of the same:

<img width="1440" alt="Screenshot 2021-12-30 at 12 20 22 PM" src="https://user-images.githubusercontent.com/51681435/147728714-96380b5c-9020-4106-8357-5ccb014ef528.png">

<img width="772" alt="Screenshot 2021-12-30 at 12 23 56 PM" src="https://user-images.githubusercontent.com/51681435/147728725-a0c8a590-9a7c-46f8-abf6-bd3a984c64b6.png">

Based on above analysis, can you please check and verify if this issue is happening for you on Magento 2.4-develop as well ? That way we can verify if this issue is 2.3.7-p2 specific or happening across all Magento versions. Any other info would also be helpful.

Thanks

**Comment by nunogato** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Dear @nunogato,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
