### ISSUE TITLE
The default luma logo is shown on frontend order print page

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#34942]
During migration from Magento 2.3.x to 2.4.3-p1 we noticed an issue - the print order/invoice/credit memo pages (on frontend) started showing a default luma logo instead of the logo that is shown on the entire website.

### Preconditions (*)

1. Magento 2.4.3
2. Luma theme
3. Set custom logo in the header on the frontend

### Steps to reproduce (*)
1. Go to the frontend
2. Place some order
3. On the frontend go to My Account > My Orders > View Order > Print Order

### Expected result (*)
1. If you explicitly defined a custom logo for emails - that logo should be shown (the highest priority) - Config path `sales/identity/logo_html`
2. If you specified a custom frontend logo - that logo should be shown (medium priority) - Config path `design/header/logo_src`
2. If you didn't specify both custom logo for emails and frontend logo - the default luma should be shown (the lowest priority)
**The same flow should be for invoices and credit memos.**

### Actual result (*)
1. If you explicitly defined a custom logo for emails - that logo should be shown (the highest priority) - ✔ works fine
2. If you specified a custom frontend logo  - that logo should be shown (medium priority) - ❌ doesn't work, but worked on Magento 2.3.7-p2.
3. If you explicitly defined a custom logo for emails - that logo should be shown (✔ works fine)

### Additional info
The issue appeared after the following commit: https://github.com/magento/magento2/commit/4531c763b5afad4af054bf5dce14669dce0c49ee
It had to fix the case when the first option didn't work fine.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @ihor-sviziev,

Thanks for posting the issue!

We have tried to reproduce the issue by upgrading Magento from 2.3.7 to 2.4.3-p1 and the issue is reproducible for us. We have followed the exact same steps mentioned in the main description. Please have a look at below screenshots for reference:

- Before Upgrade:
**_Admin Dashboard_**
![mag_v_237](https://user-images.githubusercontent.com/51681618/148740398-9ca242e3-a7da-473f-9caf-0e13ef61d28a.png)

**_Order Frontend_**
![mag_v_237_order_logo](https://user-images.githubusercontent.com/51681618/148740458-b8e491d8-99bd-4a45-85c5-35278e2710ff.png)

- After Upgrade
_**Admin Dashboard**_
![mag_v_243p1](https://user-images.githubusercontent.com/51681618/148740519-5f241e32-5ec1-4c15-a2f7-c86ebff5ccce.png)

**_Order Frontend_**
![image](https://user-images.githubusercontent.com/51681618/148740133-7ac00a20-2dd1-4e48-89f5-ae62230b42d1.png)

Hence confirming the issue.

Thanks

**Comment by ihor-sviziev** [comment]
Hi @engcom-Hotel, while you confirmed the issue, could you please test the linked PR to make sure it's actually fixes the issue?
Thank you!
