### ISSUE TITLE
[Issue] Weight 0 for bundle products

### ISSUE THREAD

**Issue by manuelcanepa** [magento/magento2#34952]
### Preconditions (*)
1. Magento 2.4.3-p1
2. Bundle product with Configurable child
3. Ship Bundle Items: Together
4. All simple products, childs of configurable must have weight > 0
5. Configurable weight: 0

### Steps to reproduce (*)
1. Choose bundle product on frontend
2. Go to cart
3. Estimate shipping rates

### Expected result (*)
1. On a shipping carrier, the method `collectRates(RateRequest $request)`, calling `$request->getPackageWeight()` will return > 0

### Actual result (*)
1. `$request->getPackageWeight()` return 0
2. This method does not include bundles logic:

https://github.com/magento/magento2/blob/302f6c52138221d511b0e1742f94cd43f68aa6f3/app/code/Magento/Quote/Model/Quote/Address/Total/Shipping.php#L152-L231

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by manuelcanepa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment]
Hi @manuelcanepa,
 
Thank you for reporting the issue. 
However, we tried to reproduce it on Magento 2.4.3-p1/2.4-dev but the issue is not reproducible. 
Steps followed to reproduce issue:
1. Installed the fresh Magento 2.4-dev/2.4.3-p1 instance.
2. Created bundle product with the configurable product as child product.
3. Setup weight for child configurable product. 
4. Added product to the cart and created order.
5. Able to place the order successfully. (attached screenshots). 

<img width="1428" alt="1 - Screenshot 2022-01-11 at 1 54 49 PM" src="https://user-images.githubusercontent.com/51681435/149075238-b61f82c6-8e69-4d8b-9158-ecf32f76bf97.png">

<img width="1428" alt="2 - Screenshot 2022-01-11 at 1 55 09 PM" src="https://user-images.githubusercontent.com/51681435/149075243-13ef44e9-f1ff-49ed-a637-998f07589d24.png">

<img width="1428" alt="3 - Screenshot 2022-01-11 at 1 57 38 PM" src="https://user-images.githubusercontent.com/51681435/149075253-b7e21a25-b7c4-401c-b093-7a9dcab0f66b.png">

6. Observed the function $request->getPackageWeight() output on the “fedex/Model/Carrier.php” and it shows the correct weight, see the below screenshot ( attach screenshot). 

<img width="1428" alt="4 - Screenshot 2022-01-11 at 7 35 16 PM" src="https://user-images.githubusercontent.com/51681435/149075279-11cdf1b3-1970-48c8-8d7f-8b5a29fc5462.png">

7. Also observed the function output “getAssignmentWeightData()”, it has the weight value as well (attached screenshot)

<img width="1428" alt="5 - Screenshot 2022-01-11 at 1 53 56 PM" src="https://user-images.githubusercontent.com/51681435/149075391-6346ac05-6d11-4da9-99a1-ec73380076e5.png">

If the issue still persists at your end then please provide some more details or provide the exact steps, accordingly, I’ll try to reproduce it again.

Thanks

**Comment by manuelcanepa** [comment]
The issue occur when you set `Ship Bundle Items` as `Together` on the bundle config:
![image](https://user-images.githubusercontent.com/10290593/149146788-10c8f657-ec60-4792-957d-bec01f5cdac2.png)

vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php
![image](https://user-images.githubusercontent.com/10290593/149146546-02463ec0-de9b-412d-a5b4-6cdd71451c90.png)

In order to workaround this issue, i just set  `Ship Bundle Items` as `Separately` and works fine:
![image](https://user-images.githubusercontent.com/10290593/149147437-3b117d3f-a626-4248-a4b8-8efd6f4b7c97.png)

I'm not sure if it's the desired functionality or a bug, but I don't think it's correct. Is this work as intended?

**Comment by engcom-Echo** [comment]
Hi @manuelcanepa,

I have tried the way you said. Updated bundle product configuration “Ship Bundle Items” as “Together” on the bundle config, and tested the scenario again and I still get the package weight in shipping and shipping carrier file ($request->getPackageWeight()). See the attached screenshot. It seems the shipping and carrier working as expected. 

<img width="1440" alt="Screenshot 2022-01-17 at 7 11 32 PM" src="https://user-images.githubusercontent.com/51681435/149782234-442eee2f-e54d-441a-ae10-b700bdd52aa0.png">

Hope it helps. Let me know if you are still facing this issue or provide more relevant details if you think it is a Magento core issue.

Thank You

**Comment by manuelcanepa** [comment]
I will keep with the premise: I dont know if this is a issue. I find how to reproduce. The weight is set on simple products. If i set weight on configurable, is working fine (Together or Separately). The way to reproduce this issue is setting weight ONLY on simple product. I suppose that is an issue because in some cases the simples may have differents weights based on his attributes. Think on flavor as a configurable and simples selled by weight, if i setup configurable with 1kg and select option with 0.5kg i will have a difference between selection and weight calculated.

**Comment by manuelcanepa** [comment]
btw, i need to metion @engcom-Echo ?

**Comment by engcom-Hotel** [comment]
Hi @manuelcanepa,
We are not able to reproduce this issue, it would be good if you provide the exact steps and the issue so that I can reverify and confirm it.

Thanks

**Comment by manuelcanepa** [comment]
Im sorry, i just realize that you need to install this extension: https://marketplace.magento.com/ewave-extendedbundleproduct.html So, no, is not a bug of magento vanilla.
