### ISSUE TITLE
secureRenderer attributes are convertet in unicode

### ISSUE THREAD

**Issue by in-session** [magento/magento2#34977]
Insert a script into a phtml file, for example:

```
<?php
$scriptTagManager = <<<SCRIPT
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-XXXXXXX');
SCRIPT;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type'=>'text/plain','data-usercentrics'=>'Google Tag Manager'], $scriptTagManager, false) ?>
```

Script tag output:
```
<script data-cfasync="false" type="text&#x2F;plain" data-usercentrics="Google&#x20;Tag&#x20;Manager">
```

**Comment by engcom-Hotel** [comment]
Hello @in-session,

We have tried to reproduce the issue in Magento 2.4-develop branch but for us, it is not reproducible. We are able to get the proper `script` tag.

We have tried it in `Checkout/view/frontend/templates/onepage.phtml` file:
![image](https://user-images.githubusercontent.com/51681618/149965489-5e92b65d-273d-4ac3-8e00-5085107d657f.png)

Please let us know if we have missed anything in order to reproduce the issue.

Thanks

**Comment by in-session** [comment]
@engcom-Hotel 

I cross-checked your info again, the problem is not visible in the console as the Unicode characters are converted here. 
Can you look into the source code directly: view-source:https://....

![Screenshot 2022-01-18 164540](https://user-images.githubusercontent.com/16542619/149970175-36d0e8c9-1ecd-4071-9585-01820fe8d8a7.png)

**Comment by in-session** [comment]
@engcom-Hotel 

I have once made a test PR:
https://github.com/magento/magento2/pull/34996

**Comment by in-session** [comment]
https://github.com/magento/magento2/issues/30524
