### ISSUE TITLE
Error: Call to a member function getCustomerName() on null

### ISSUE THREAD

**Issue by Green2Matter** [magento/magento2#34998]
### Preconditions (*)

1. Magento CE 2.4.3-p1
2. Ubuntu 20.04.3, PHP7.4, Percona MySQL8.0, Varnish 6.5, Elasticsearch 7

### Steps to reproduce (*)

Go to admin panel - Stores - Settings - Configuration -> Catalog -> RSS Feeds - Enable RSS Config, Wishlist -> Save Config
Clear Cache
Front-end - Login as Customer - Add Products to Wish list
My Wish list -> Share Wish List -> Enter email id , message
Select "Check here to link an RSS feed to your Wish List" Checkbox and click on Share Wish list

### Expected result (*)

1. To have a message sent as same as without RSS link

### Actual result (*)

1. [<p id="wishlist-rss-email-link">
    Error: Call to a member function getCustomerName() on null in <magento_root>/vendor/magento/module-wishlist/view/frontend/templates/rss/email.phtml:15
Stack trace:
#0 <magento_root>/vendor/magento/framework/View/TemplateEngine/Php.php(71): include()
#1 <magento_root>/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#2 <magento_root>/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#3 <magento_root>/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#4 <magento_root>/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#5 <magento_root>/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#6 <magento_root>/vendor/magento/module-wishlist/Controller/Index/Send.php(328): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 <magento_root>/vendor/magento/module-wishlist/Controller/Index/Send.php(237): Magento\Wishlist\Controller\Index\Send->getRssLink()
#8 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Wishlist\Controller\Index\Send->execute()
#9 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Wishlist\Controller\Index\Send\Interceptor->___callParent()
#10 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Wishlist\Controller\Index\Send\Interceptor->Magento\Framework\Interception\{closure}()
#11 <magento_root>/generated/code/Magento/Wishlist/Controller/Index/Send/Interceptor.php(23): Magento\Wishlist\Controller\Index\Send\Interceptor->___callPlugins()
#12 <magento_root>/vendor/magento/framework/App/Action/Action.php(111): Magento\Wishlist\Controller\Index\Send\Interceptor->execute()
#13 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#14 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Wishlist\Controller\Index\Send\Interceptor->___callParent()
#15 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Wishlist\Controller\Index\Send\Interceptor->Magento\Framework\Interception\{closure}()
#16 <magento_root>/generated/code/Magento/Wishlist/Controller/Index/Send/Interceptor.php(32): Magento\Wishlist\Controller\Index\Send\Interceptor->___callPlugins()
#17 <magento_root>/vendor/magento/framework/App/FrontController.php(245): Magento\Wishlist\Controller\Index\Send\Interceptor->dispatch()
#18 <magento_root>/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#19 <magento_root>/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#20 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#21 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#22 <magento_root>/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#23 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#24 <magento_root>/vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php(140): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch()
#26 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}()
#27 <magento_root>/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins()
#28 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch()
#29 <magento_root>/vendor/swissup/module-amp/Plugin/Framework/FrontController.php(48): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#30 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(135): Swissup\Amp\Plugin\Framework\FrontController->aroundDispatch()
#31 <magento_root>/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#32 <magento_root>/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#33 <magento_root>/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#34 <magento_root>/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#35 <magento_root>/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#36 <magento_root>/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#37 {main}]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [S3 ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by makzef** [comment]
@Green2Matter Hello.
I cannot reproduce issue that you describe. I tried it on magento 2.4-develop.

### Steps that were made to reproduce the issue:

1. Go to admin panel and enable **rss** config for wish list by this path  _**Configuration -> Catalog -> RSS Feeds -> Wish List -> Enable RSS -> Enabled**_.
2. Log in as user, add some product to user's wish list.
3. Go to user's wish list and select `Share Wish List`.
4.  In the `Share Wish List` page form, specify necessary data and check `Check here to link an RSS feed to your Wish List` and submit the form. 

### Actual result: 
Message about successful sharing - `Your wish list has been shared.` There was no any error.

@Green2Matter if my steps were correct, can you specify is it still an issue? If it so, please provide more details about how to reproduce this bug?

Thank you.

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Steps performed:
Go to admin panel - Stores - Settings -  Configuration -> Catalog -> RSS Feeds - Enable RSS Config, Wishlist -> Save Config
Clear Cache
Front-end - Login as Customer - Add Products to Wish list
My Wish list -> Share Wish List -> Enter email id , message
Select "Check here to link an RSS feed to your Wish List" Checkbox and click on Share Wish list
Issue:
![image](https://user-images.githubusercontent.com/60198231/155068979-bc1d85b7-3f12-41eb-a24d-1c75589ff44a.png)

Exception:
`
[2022-02-22T05:28:29.167811+00:00] main.CRITICAL: Error: Call to a member function getCustomerName() on null in /var/www/html/mg24/magento2/app/code/Magento/Wishlist/view/frontend/templates/rss/email.phtml:15
Stack trace:
#0 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(71): include()
#1 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#2 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#3 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#4 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#5 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#6 /var/www/html/mg24/magento2/app/code/Magento/Wishlist/Controller/Index/Send.php(328): Magento\Framework\View\Element\AbstractBlock->toHtml()
#7 /var/www/html/mg24/magento2/app/code/Magento/Wishlist/Controller/Index/Send.php(237): Magento\Wishlist\Controller\Index\Send->getRssLink()
#8 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Wishlist\Controller\Index\Send->execute()
#9 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Wishlist\Controller\Index\Send\Interceptor->___callParent()
#10 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Wishlist\Controller\Index\Send\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/html/mg24/magento2/generated/code/Magento/Wishlist/Controller/Index/Send/Interceptor.php(23): Magento\Wishlist\Controller\Index\Send\Interceptor->___callPlugins()
#12 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\Wishlist\Controller\Index\Send\Interceptor->execute()
#13 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#14 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Wishlist\Controller\Index\Send\Interceptor->___callParent()
#15 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Wishlist\Controller\Index\Send\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/html/mg24/magento2/generated/code/Magento/Wishlist/Controller/Index/Send/Interceptor.php(32): Magento\Wishlist\Controller\Index\Send\Interceptor->___callPlugins()
#17 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\Wishlist\Controller\Index\Send\Interceptor->dispatch()
#18 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#19 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#20 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#21 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#22 /var/www/html/mg24/magento2/app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#24 /var/www/html/mg24/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#25 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#26 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#27 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#28 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#29 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#30 /var/www/html/mg24/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#31 {main} [] []
`

**Comment by engcom-Alfa** [comment]
Hi @Green2Matter,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/search?q=AC-2445&type=commits).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
