### ISSUE TITLE
Setting an invalid Cookie domain crash the website

### ISSUE THREAD

**Issue by wajihkm** [magento/magento2#35048]
### Preconditions (*)

2.4.3 p1

### Steps to reproduce (*)

1. Store >> Configurations >> Web >> Default Cookie Settings Cookie Domain
2. Enter invalid value: eg: magento.localhost,staging.com

### Expected result (*)

1. Show warning
2.

### Actual result (*)

1. The website crashs
2. {"0":"Warning: Cookie domains cannot contain any of the following ',; \\t\\r\\n\\013\\014' in \/magento243p1\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php on line 152"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by wajihkm** [comment]
@magento give me 2.4-develop instance

**Comment by wajihkm** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
![image](https://user-images.githubusercontent.com/60198231/154926510-9dee0087-caec-422f-8b4a-0a7b684b7eaf.png)

`
[2022-02-21T09:26:07.258206+00:00] main.CRITICAL: Exception: Warning: Cookie domains cannot contain any of the following ',; \t\r\n\013\014' in /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php on line 152 in /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php(152): setcookie()
#2 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Stdlib/Cookie/PhpCookieManager.php(123): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie()
#3 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Session/SessionManager.php(251): Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie()
#4 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Session/SessionManager.php(212): Magento\Framework\Session\SessionManager->renewCookie()
#5 /var/www/html/mg24/magento2/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(122): Magento\Framework\Session\SessionManager->start()
#6 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Session/SessionManager.php(141): Magento\Backend\Model\Auth\Session\Interceptor->start()
#7 /var/www/html/mg24/magento2/app/code/Magento/Backend/Model/Auth/Session.php(102): Magento\Framework\Session\SessionManager->__construct()
#8 /var/www/html/mg24/magento2/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(14): Magento\Backend\Model\Auth\Session->__construct()
#9 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Backend\Model\Auth\Session\Interceptor->__construct()
#10 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#11 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#12 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#13 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#14 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#15 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#16 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#17 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#18 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#19 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#20 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#21 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#22 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#23 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#24 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(206): Magento\Framework\ObjectManager\ObjectManager->get()
#25 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(182): Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray()
#26 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#27 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument()
#28 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime()
#29 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments()
#30 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#31 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(109): Magento\Framework\ObjectManager\ObjectManager->get()
#32 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(14): Magento\Framework\App\FrontController->__construct()
#33 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\FrontController\Interceptor->__construct()
#34 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#35 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#36 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\ObjectManager\ObjectManager->get()
#37 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#38 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#39 /var/www/html/mg24/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#40 {main} {"report_id":"16e60a7180acf4ae5267f09a403abc4c0291b78e728a23600eb227261d317226"} []
`

**Comment by engcom-Alfa** [comment]
Hi @Reporter ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/search?q=AC-2441&type=commits).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
