### ISSUE TITLE
Purchase of product with all/last pcs leave product available in catalog (until manual cache flush)

### ISSUE THREAD

**Issue by nkajic** [magento/magento2#35105]
### Preconditions (*)

1. development branch

### Steps to reproduce (*)

1. Add product in cart with max quantity available (usually 100 pcs in sample data)
2. Finish checkout
3. Go to category where that product was available
4. Add to cart

### Expected result (*)

1. Product IS NOT shown in category
2. Product does not have Add to cart button available

### Actual result (*)

1. Product is shown in category
2. Product Add to cart button is available
3. Clicking Add to cart leads to Product page showing error "The requested qty is not available"

Recording from testing
https://youtu.be/ZrknzyYy2EI

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @nkajic,

We have tried to reproduce the issue in Magento 2.4-develop branch, the issue is reproducible for us. Please have a look into the below screenshots for reference:

- In the admin panel, the catalog list page shows 0 default stock:
![image](https://user-images.githubusercontent.com/51681618/154248238-6eddc177-7900-4c7c-b8f8-b17328200d17.png)

- Product Shown in the category:
![image](https://user-images.githubusercontent.com/51681618/154247974-e8a99612-2c94-401a-9dce-03198e025705.png)

- Error on `Add to cart`:
![image](https://user-images.githubusercontent.com/51681618/154247845-6718252c-e96a-4f57-a849-4251fda9310d.png)

- After clearing the cache, the product is not visible in the category page:
![image](https://user-images.githubusercontent.com/51681618/154248565-32e578f6-ad8e-488b-9ec0-baace1a3fb03.png)

Note: I have waited for some time like 5 mins if the cache will clear automatically. But that does not happen.

Hence confirming the issue.

Thanks

**Comment by sdzhepa** [comment]
@engcom-Hotel  @nkajic 

This issue could occur on instances where consumers are not runing(configured)
https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-queue.html


Could you please confirm is it issue happened with enabled/configured consumers on an instance with MSI

**Comment by nkajic** [comment]
Hi all,

I have managed to get it working by properly configuring consumers.

Are't consumers configured to run on test instances by magento-deployment-service? Maybe tried before consumers were ready to accept jobs?

I will close this issue. Thanks all.
