### ISSUE TITLE
Email Template Css Styles breaking

### ISSUE THREAD

**Issue by thinksys-dev** [magento/magento2#35130]
### Preconditions (*)

1. We installed the Patches MDVA-43395,MDVA-43443 but after installing the Email templates styles are breaking.
2. The styles which are set on Template styles box is not working on templates.

### Steps to reproduce (*)

1. Install the Patches MDVA-43395,MDVA-43443  on magento2 and set CSS under Template Styles text box on any email template in Admin then the CSS will not work for the email template.
2.

### Expected result (*)

1. The email template should pick the defined styles in Template style text box
### Actual result (*)

1. When email is sending to customer the email design is distorted due to not picking the CSS from defined CSS

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ S4] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @thinksys-dev,

Thanks for posting the issue!

Please let us know the below points in order to further analysis of the ticket:

- Summary of your environment
- CSS changes made
- If possible, please provide some screeshots

Thanks

**Comment by mrtuvn** [comment]
i don't have much information but i think email styles need to rework after fix/patch
Current you have to migrate styles in admin to theme (less/css ) because styles email include admin not able to work after fix/apply patch
Maybe a lot of stores may be affected this.

**Comment by mrtuvn** [comment]
SQL command may help you to know how many templates broke. Bracket in css after patch will broke
```sql
SELECT COUNT(*) FROM `email_template` WHERE template_styles like '%{%';
```

**Comment by thinksys-dev** [comment]
> i don't have much information but i think email styles need to rework after fix/patch Current you have to migrate styles in admin to theme (less/css ) because styles email include admin not able to work after fix/apply patch Maybe a lot of stores may be affected this.

How we can fix the issue, how the CSS will work on email templates. could you please provide the suggestion/steps or any link to fix this.

**Comment by thinksys-dev** [comment]
@mrtuvn 
Gentle Reminder: Could you please suggest the solution, and also tell will Magento will provide any patch in the future for this to fix and how much should be waited so that CSS can pick from admin templates.

**Comment by kerlama** [comment]
Hi,
I can confirm the issue too.

**Comment by MatthijsvanNoort** [comment]
Confirming this issue. Brackets {} in CSS missing

**Comment by hostep** [comment]
@nathanjosiah: just wanting to confirm if you guys are aware of this issue? It was posted in the security Slack channel a week or 2 ago, but I didn't saw a confirmation from you guys so we aren't sure if you are aware of this problem and if work on it has started to fix it or not?

There is some little info about here:
- https://gist.github.com/wigman/171f9314d692d23330591d20cec3a9fd#css-in-email-template-break-after-applying-the-patch
- https://twitter.com/fschmengler/status/1494604466837934082?s=21

**Comment by nathanjosiah** [comment]
We are aware of several negative side-effects of the security hotfix. At this time we do not have plans to issue a third patch however this (and others) will be resolved in the upcoming April releases 2.4.4/2.3.7-p3/2.4.3-p2. As always the recommendation is to upgrade to the latest available Magento versions in order to have the latest quality and security fixes. Please keep in mind this is a sensitive security-related fix and as such we cannot openly discuss the context or reasoning for everything. We understand this can be frustrating especially when it has a negative impact. But please trust that we are doing our best to balance security, flexibility, and negative impact to customers.

**Comment by hostep** [comment]
Thanks for this info, that's very much appreciated!

----

Just wanted to bring up that a solution for this issue is floating around (on at least 2 different slack workspaces than the official one from Magento) without a guarantee that it doesn't re-introduce the security issue. So maybe reconsider the third patch solution as it seems like some people can't wait yet another month.

**Comment by engcom-Hotel** [comment]
Hello @thinksys-dev,

We have tried to reproduce the issue in Magento 2.4-develop branch, but for us, the issue is not reproducible for us. We have followed the below steps in order to reproduce the issue:
1. Trying to send a "Forgot Password" email before applying patch:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/51681618/157029336-e40880d6-b03a-4827-90c5-0a0108175527.png">
2. Apply patches mentioned in this [link](https://support.magento.com/hc/en-us/articles/4426353041293-Security-updates-available-for-Adobe-Commerce-APSB22-12)
3. Then again send a "Forgot Password" email after applying the patch:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/51681618/157029965-1894adc5-5163-4cae-a266-171880b95a4c.png">

No issues were found in emails. Maybe we have missed anything in order to reproduce the issue. Please let us know in case we have missed anything.

Thanks

**Comment by hostep** [comment]
@engcom-Hotel: please stop wasting time on this, it's already confirmed internally and a fix is already being worked on or is already finished and will be delivered in Magento 2.4.4 an other versions as you can see from [this comment](https://github.com/magento/magento2/issues/35130#issuecomment-1058249592).

**Comment by engcom-Hotel** [comment]
Hello @hostep,

Thanks for the confirmation.

Hello @thinksys-dev,

As this issue is already fixed and lined up for the next Magento release shall we close this issue?

Thanks

**Comment by engcom-Hotel** [comment]
Dear @thinksys-dev,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by mrtuvn** [comment]
why this ticket closed ? I think it's should valid till we got information of fix

**Comment by LeoNun** [comment]
Hello,
applied the patchs last month for CVE-2022-24086 and CVE-2022-24087 and have the same problem, no styles in the newsletter template.

Best Regards,
Leonel Nunes
