### ISSUE TITLE
Different products randomly drop Catalog Price Rule

### ISSUE THREAD

**Issue by paul-uz** [magento/magento2#35143]
We are experiencing a strange issue in Magento 2.3.7-p2 where different products assigned to a catalog price rule are dropping the discount at random times.

A manual reindex seems to fix it temporarily, which is unusual, as the cron is running every minute.

I'm not seeing any obvious errors in the logs either.

The affected products are not appearing in the `catalogrule_product` table, but are in the `catalogrule_product__tempXXXXXX` table, despite resaving and applying the catalog price rule.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
**Steps performed:**
Admin - System - Index Management - Indexers are set to "Update By Schedule"
Stores - Attributes - Product - Search for SKU - Storefront Properties - Use for Promo Rule Conditions - Set to Yes and Save
re-index and clear cache
Marketing - Catalog Price Rule - Create New Rule
Edit the rule - Conditions - add SKU - assign different Products - Save and Apply
Wait for Indexers to be updated and clear cache
Front -end - Catalog Price Rule is applied on selected products as expected - **No issue.**
@paul-uz kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/155966744-1bef9fa8-eb46-428e-93a2-d62edd37bdeb.png)
![image](https://user-images.githubusercontent.com/60198231/155966843-c4f94e95-0d45-4afe-850f-87de630d102a.png)

Thank you.

**Comment by paul-uz** [comment]
@engcom-November unfortunately, this is on 2.3.x and we are not in a position to move to 2.4

**Comment by engcom-November** [comment]
Hi @paul-uz ,
Its recommended to verify issues on Magento 2.4-develop branch only as it is the upcoming 2.4.x release. Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible. You can get the cloud 2.4-develop instance by commenting on this issue with "@magento give me 2.4-develop instance"

Thank you.

**Comment by paul-uz** [comment]
I appreciate what you are syaing @engcom-November but I doubt I would be able to replicate it on 2.4, especially as we do have additional 3rd party plugins installed etc.

I ended up backing up and deleting some old temp table that were floating about, and ran `bin/magento index:reset` and after a re-index, it seems to have resolved the issue.
