### ISSUE TITLE
Applied Coupon Message missing

### ISSUE THREAD

**Issue by sagarppanchal** [magento/magento2#35152]
In the Core Magento 2.4.3-p1 cart page, when we apply coupon there is no any message is appearing, its simply applies coupon if its correct and refreshing the page.

### Preconditions (*)

1. Magento 2.4.3-p1
2. Tested with sampledata and its coupon : H20

### Steps to reproduce (*)

1. Add Product to cart ex. SKU : 24-UG06
2. Proceed to Cart Page
3. Apply coupon ex. H20

### Expected result (*)

1. Error / Success message should be displayed just like its displaying on the /checkout page

### Actual result (*)

1. No any message is displaying, its simply refreshing the page and applies coupon directly without message

https://www.loom.com/share/b2d8a89e36e34e9a8e04e91b243e732b

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Coupon applied successfully and message is displayed as expected in Shopping Cart page - No issue
![image](https://user-images.githubusercontent.com/60198231/156126053-1896f394-e79f-4f97-8fdd-f81f53fc5ded.png)
@sagarppanchal kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment]
Verified the issue again on Magento 2.4-develop branch with sample data and coupon H20 but the issue is still not reproducible on Ubuntu 20.04.3 LTS - 64bit and Chrome browser
![image](https://user-images.githubusercontent.com/60198231/156339227-1203876f-342f-41d6-a743-d1c4626415eb.png)
@sagarppanchal kindly recheck the issue on Magento 2.4-develop branch as it is having latest code base and upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by sagarppanchal** [comment]
@engcom-November Thanks for the confirmation, on the instance its working fine for me as well.
