### ISSUE TITLE
Product Recommendations - Adobe Sensei  CSP - Refused to load the script https://web-sdk.aptrinsic.com/api/aptrinsic.js

### ISSUE THREAD

**Issue by apomili** [magento/magento2#35163]
### Preconditions (*)

1. Magento Commerce 2.4.3 
2. Adobe Sensei Integration

### Steps to reproduce (*)

1. Go in the backoffice:  Marketing > Product Recommendations
2. Open the browser's console

### Expected result (*)

1. No JS error

### Actual result (*)

1. launch-177bc126c8e6.min.js:4 Refused to load the script 'https://web-sdk.aptrinsic.com/api/aptrinsic.js?a=AP-XD7ZED5OKDHG-2-1' because it violates the following Content Security Policy directive: "default-src 'self' data: 'unsafe-inline' 'unsafe-eval' assets.adobedtm.com use.typekit.net performance.typekit.net p.typekit.net commerce.adobe.net amcglobal.sc.omtrdc.net fonts.googleapis.com fonts.gstatic.com *.adobe.io". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

![Schermata da 2022-03-04 12-08-44](https://user-images.githubusercontent.com/7668956/156752921-698d1eb9-8483-4d6a-b2bc-788ede994cbb.png)

*I'm unable to fix it via CSP whitelist and cannot find why.*

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Install Product Recommendations Module
Go in the admin panel : Marketing > Product Recommendations
Open the browser's console > refresh the page and java script error is thrown.
![image](https://user-images.githubusercontent.com/60198231/160403299-0bce37cf-c9b8-4301-bd2b-779be1ffa9d2.png)

**Comment by nataliefox-288** [comment]
The Product Recommendations module blocks override the admin template. I experienced a similar issue and contacted Product Recommendations's support who supplied me with an xml file which removed 2 offending blocks in their template. The error has disappeared since adding the file.

**Comment by engcom-Alfa** [comment]
Hi @apomili and @nataliefox-288 
Thanks for your contribution and collaboration here.

We again tried to reproduce the same issue in `2.4-develop` in order to fix the same! But noticed that it is not reproducible anymore might be due to the above-comment.

Kindly pull the latest Magento code 2.4-develop and try to reproduce the same issue. If at all the issue is reproducible anymore, kindly update me back here with all the details like steps to execute and if there is any specific configurations required.
Thanks

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by hostep** [comment]
@engcom-Alfa: why did this issue get closed without any feedback explaining why it got closed?

**Comment by engcom-Alfa** [comment]
> @engcom-Alfa: why did this issue get closed without any feedback explaining why it got closed?

Hi @hostep thanks for asking this!
Apologies;
Our internal PM has closed the linked internal githhub issue, hence this github has got auto closed.
But, missed to mention the reason here.

FYI:
We have a below message in the internal ticket:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/51679138/187857059-066e00f6-5e2b-4ca2-9f0a-5a2e2830999f.png">
  The link is clickable [HERE](https://experienceleague.adobe.com/docs/commerce-merchant-services/product-recommendations/getting-started/install-configure.html?lang=en#update).

Thanks
