### ISSUE TITLE
Order Total is becoming negative value during checkout if discount is greater than Cart value

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#35162]
### Preconditions (*)

1. Magento 2.4-develop
2. 

### Steps to reproduce (*)

1. Create Cart Price Rule with Action "Fixed amount discount for Whole Cart" and amount $100
2. Stores - Settings - Configuration - Sales - Tax - Calculation Settings - 'Apply Customer Tax' Set to "After Discount", Apply 'Discount On Prices' - "Including Tax" - Save Config
3. Default Tax Destination Calculation - Germany
4. Stores - Settings - Configuration - Sales - Shipping Methods - Enable Free Shipping
5. Create 3 Tax Rules (Ex: US ex: 8.25% tax rate and Germany 2 rules : 19% and 7%)
![image](https://user-images.githubusercontent.com/60198231/156752579-a8d0bef2-f1af-4d1a-b9a2-4ffb867cbdca.png)
6. Reindex and clear cache
7. Create a Product so that whole cart value is < 100 . (Ex: Created product with amount $40)
8. Front-end Login as Customer - Add Product to Cart
9. Ship to US/Germany Address, Apply Discount - Payment Step

### Expected result (*)

Order Total should become 0

### Actual result (*)

Order Total is becoming negative value.
On submitting the order, below error message is displayed.
![image](https://user-images.githubusercontent.com/60198231/156753309-a545e69d-561c-4755-a371-ab04449b5707.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @engcom-November ,
We tried to reproduce the issue on Magento 2.4.Develop latest branch , 
issue is reproducible for Germany Country Whereas for US shipping address it did not show negative value during checkout. Hence confirming the issue .

**Steps followed:**
1. Create Cart Price Rule with Action "Fixed amount discount for Whole Cart" and amount $100
<img width="1440" alt="Screenshot 2022-03-07 at 8 10 11 PM" src="https://user-images.githubusercontent.com/51681379/157059146-0fe1df88-3712-48bd-9de3-d27e54b9dab0.png">
2. Stores - Settings - Configuration - Sales - Tax - Calculation Settings - 'Apply Customer Tax' Set to "After Discount", Apply 'Discount On Prices' - "Including Tax" - Save Config
<img width="1440" alt="Screenshot 2022-03-07 at 8 43 51 PM" src="https://user-images.githubusercontent.com/51681379/157061901-dc32aacd-86fe-4bd0-b502-67dae82cd217.png">
3. Default Tax Destination Calculation - Germany
<img width="1440" alt="Screenshot 2022-03-07 at 8 49 36 PM" src="https://user-images.githubusercontent.com/51681379/157062742-e2011d85-619b-47c4-b9f1-06725a8501ee.png">
4. Stores - Settings - Configuration - Sales - Shipping Methods - Enable Free Shipping
<img width="1440" alt="Screenshot 2022-03-07 at 7 50 03 PM" src="https://user-images.githubusercontent.com/51681379/157062854-16466c7b-2485-4625-b6b0-b2889779052e.png">
5. Create more than one Tax Rule (Ex: US and Germany - 19% and 7%)
<img width="1440" alt="Screenshot 2022-03-07 at 8 32 12 PM" src="https://user-images.githubusercontent.com/51681379/157063005-237f1b16-ff99-4e43-b67e-4587bb2cfdca.png">
6. Reindex and clear cache
7. Create a Product so that whole cart value is < 100 . (Ex: Created product with amount $40)
<img width="1440" alt="Screenshot 2022-03-07 at 7 58 23 PM" src="https://user-images.githubusercontent.com/51681379/157063266-a03b71c3-75a3-496e-8cdc-e1587916a6c3.png">
8. Front-end Login as Customer - Add Product to Cart
9. Ship to US/Germany Address, Apply Discount - Payment Step
<img width="1440" alt="Screenshot 2022-03-07 at 8 24 55 PM" src="https://user-images.githubusercontent.com/51681379/157063506-594d4e10-227b-4f8a-9b5a-98183ba58829.png">
<img width="1440" alt="Screenshot 2022-03-07 at 8 10 46 PM" src="https://user-images.githubusercontent.com/51681379/157063691-d8089690-5b17-4a5f-b706-d154f3c52ace.png">
<img width="1440" alt="Screenshot 2022-03-07 at 8 23 54 PM" src="https://user-images.githubusercontent.com/51681379/157063724-709c399f-2a10-4349-930a-846c86847623.png">











Create more than one Tax Rule (Ex: US and Germany - 19% and 7%)

**Comment by engcom-November** [comment]
Issue will not be fixed and is cancelled with below reasons:
1. During configuring, there is sufficient warning to the merchant that they are performing some configurations that could lead to problems. Being even more stringent and stopping the merchant from proceeding with their configuration would require substantial effort on definition and also implementation. We would probably have to check all prices in the catalogue to check if the minimum price was less than the total cart discount and also the combinations of the discount calculations including or not tax, as well as the tax calculations taking place after discount applied. Altogether, quite a complex scenario for what appears to be somewhat of an edge case caused by trying to configure the store incorrectly.
2. During checkout: the value shown is < 0 and this does indeed look silly. But what could be a solution? Making the order amount to be zero when the order value total is <0? That could be a solution but it could imply that shoppers start to see zero value orders and order many items rapidly, thereby cleaning out the merchant for what is probably an error. So in this case, I would also err on the side of caution and keep the order from being completed. At least this way, the merchant does not run the risk of having unexpected zero-value orders and they should relook at their configuration and configure their store correctly, creating cart discounts which correspond with the minimum prices of their products.

**Comment by judin** [comment]
I was wanting to give 100% discount coupons (in the UK) and I've got the same issue as @engcom-November - I'm surprised this hasn't been fixed.
