### ISSUE TITLE
Wrong parameter are passed to setFreeShipping method

### ISSUE THREAD

**Issue by baatractive** [magento/magento2#35164]
### Preconditions (*)
1. 2.4.3, master branch

### Steps to reproduce (*)
1. The `setFreeShipping` requires an integer parameter while `isFreeShipping` method interface returns a boolean. 

### Expected result (*)
The following call to `setFreeShipping` passes a boolean value while it should pass an integer: https://github.com/magento/magento2/blob/81340cb1b7231e875ceb92c333f371fd3a2309b8/app/code/Magento/Quote/Model/Quote/Address/Total/Shipping.php#L76

### Actual result (*)

![image](https://user-images.githubusercontent.com/88047235/156774944-d55cb067-d56d-42cf-b041-d43620c5f674.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @baatractive,

Thanks for posting this issue!

We have checked the codebase in Magento 2.4-develop branch and we are able to reproduce the issue. This functionality may impact the `shipping` cost.

We have checked the below files in order to reproduce the issue:

1. Calling from `collect` function from the below line:
https://github.com/magento/magento2/blob/81340cb1b7231e875ceb92c333f371fd3a2309b8/app/code/Magento/Quote/Model/Quote/Address/Total/Shipping.php#L76
2. `$isFreeShipping` variable is type of `bool`:
https://github.com/magento/magento2/blob/81340cb1b7231e875ceb92c333f371fd3a2309b8/app/code/Magento/Quote/Model/Quote/Address/FreeShippingInterface.php#L19
3. `setFreeShipping` method requires `int` type value:
https://github.com/magento/magento2/blob/81340cb1b7231e875ceb92c333f371fd3a2309b8/app/code/Magento/Quote/Model/Quote/Address.php#L62

Hence confirming this issue.

Thanks

**Comment by engcom-Alfa** [comment]
Hi @Reporter ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/search?q=AC-2583&type=commits).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
