### ISSUE TITLE
Duplicate SKUs When Using Leading 0 Causes Errors - Bulk Unassign Inventory Source

### ISSUE THREAD

**Issue by uandiweb** [magento/magento2#35171]
### Preconditions (*)

1. Magento 2.4.3-p1
2. Inventory/ MSI enabled

### Steps to reproduce (*)

1. Create a simple product with SKU 01234
3. Create another simple product with SKU 1234
4. Ensure both products don't have inventory source assigned
5. Use the product bulk action tool to assign inventory source (i.e. default) to both products at once (Catalog - Products - Select Products - Actions - Assign Inventory Source)

### Expected result (*)

1. Both products should now have inventory source assigned

### Actual result (*)

1. Only one product will have the inventory source assigned.
2. Error log shows: "main.CRITICAL: TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in /home/test/public_html/vendor/magento/module-inventory-catalog/Model/ResourceModel/BulkSourceAssign.php on line 71 and defined in /home/test/public_html/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:"

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
![image](https://user-images.githubusercontent.com/60198231/157189709-ffed43be-a725-4964-9b03-11e8f2c24336.png)

[2022-03-08T07:40:00.078262+00:00] main.CRITICAL: TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in /var/www/html/mg24/magento2/ext/magento/inventory/InventoryCatalog/Model/ResourceModel/BulkSourceAssign.php on line 71 and defined in /var/www/html/mg24/magento2/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:
#0 /var/www/html/mg24/magento2/ext/magento/inventory/InventoryCatalog/Model/ResourceModel/BulkSourceAssign.php(71): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor->execute()
#1 /var/www/html/mg24/magento2/ext/magento/inventory/InventoryCatalog/Model/BulkSourceAssign.php(63): Magento\InventoryCatalog\Model\ResourceModel\BulkSourceAssign->execute()
#2 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\InventoryCatalog\Model\BulkSourceAssign->execute()
#3 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\InventoryCatalog\Model\BulkSourceAssign\Interceptor->___callParent()
#4 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\InventoryCatalog\Model\BulkSourceAssign\Interceptor->Magento\Framework\Interception\{closure}()
#5 /var/www/html/mg24/magento2/generated/code/Magento/InventoryCatalog/Model/BulkSourceAssign/Interceptor.php(23): Magento\InventoryCatalog\Model\BulkSourceAssign\Interceptor->___callPlugins()
#6 /var/www/html/mg24/magento2/ext/magento/inventory/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssignPost.php(94): Magento\InventoryCatalog\Model\BulkSourceAssign\Interceptor->execute()
#7 /var/www/html/mg24/magento2/ext/magento/inventory/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssignPost.php(145): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost->runSynchronousOperation()
#8 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost->execute()
#9 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->___callParent()
#10 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->Magento\Framework\Interception\{closure}()
#11 /var/www/html/mg24/magento2/generated/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssignPost/Interceptor.php(23): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->___callPlugins()
#12 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->execute()
#13 /var/www/html/mg24/magento2/app/code/Magento/Backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#14 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#15 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->___callParent()
#16 /var/www/html/mg24/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(145): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#18 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/html/mg24/magento2/generated/code/Magento/InventoryCatalogAdminUi/Controller/Adminhtml/Source/BulkAssignPost/Interceptor.php(32): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->___callPlugins()
#20 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\InventoryCatalogAdminUi\Controller\Adminhtml\Source\BulkAssignPost\Interceptor->dispatch()
#21 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#22 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#23 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#24 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#25 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#27 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#28 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#29 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#30 /var/www/html/mg24/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#31 {main} [] []

**Comment by engcom-Alfa** [comment]
Hi @uandiweb,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento-commerce/magento2ce/commit/e71f1543555d7740b5132f18c192f61c02857551).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!
