### ISSUE TITLE
Product customizable options incorrect after "import options"

### ISSUE THREAD

**Issue by anvanza** [magento/magento2#35200]
### Preconditions (*)
1. Have an instance with Magento 2.4.3-p1
2. Create 2 storeviews with 2 languages

### Steps to reproduce (*)
1. Create a product A with 25 customizable options and manage their order.
2. Translate the title for each option for both storeviews.
3. Make sure that each option has a different sku
4. Save product A
5. Create a product B, import options and select product A
6. Save product B

### Expected result (*)
1. Product B has an exact copy of the customizable options of product A
2. The titles are translated per storeview, the order is the exact same.

### Actual result (*)
1. The sortorder of the last 5 options is wrong, (also 0 in database) making them appear first.
2. The titles are not translated and are a copy of the option sku
3. I'm unable to sort options between pages

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by anvanza** [comment]
@magento give me 2.4-develop instance

**Comment by anvanza** [comment]
Reproduced this on the magento instance.
Created Product A with 25 options.
<img width="1371" alt="Screenshot 2022-03-16 at 11 18 31" src="https://user-images.githubusercontent.com/2848347/158569165-72ef10b8-bfd2-47bb-a4a6-32baba19cc3e.png">
Changed the titles on storeview 1
<img width="1367" alt="Screenshot 2022-03-16 at 11 19 14" src="https://user-images.githubusercontent.com/2848347/158569243-fe58fae8-c3d4-4615-bef2-c4e86c554e28.png">
Changed the titles on storeview 2
Created Product B and selected import from product A
<img width="1460" alt="Screenshot 2022-03-16 at 11 20 59" src="https://user-images.githubusercontent.com/2848347/158569345-fa0e041b-a820-4983-8a90-dc7c41e1d2a6.png">
At first it seems imported correctly
<img width="1462" alt="Screenshot 2022-03-16 at 11 21 09" src="https://user-images.githubusercontent.com/2848347/158569422-4f27021d-11e3-4007-8052-e2ca3412c38a.png">
After clicking save
<img width="1461" alt="Screenshot 2022-03-16 at 11 21 38" src="https://user-images.githubusercontent.com/2848347/158569448-0c8cdcfc-017b-441e-b549-f2ff2085d64c.png">
The order has changed
<img width="1454" alt="Screenshot 2022-03-16 at 11 22 07" src="https://user-images.githubusercontent.com/2848347/158569504-b48b179b-8f20-4ddc-8d87-71f2526b94ba.png">
In other storeviews the titles dissappeared

**Comment by engcom-November** [comment]
Hi @anvanza ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop above instance but cannot able to reproduce the issue.
1. Created prodx with 25 options.
![image](https://user-images.githubusercontent.com/60198231/158581557-2a2682c5-b77b-4d7c-8c86-65f949075bfc.png)

2. Changed all titles of options in both store views (Default and other store)
3. Created prody by importing prodx options and Save
No issue: Order of the options is same as created after saving and refresh
![image](https://user-images.githubusercontent.com/60198231/158581499-d55c5585-8f2d-402a-987c-a4c885dba94d.png)

All other store views - options are not disappeared.
![image](https://user-images.githubusercontent.com/60198231/158581426-f9ced294-6c59-4a4e-97d7-8ddf1287469c.png)
@anvanza I see your Product B order has changed but the options are present in all store views.
Kindly recheck and elaborate the missing steps if any if the issue is still reproducible.
Thank you.

**Comment by anvanza** [comment]
Hi @engcom-November ,

Thank you for the collaboration. Verified the issue on Magento 2.4-develop above instance and **I am able** to reproduce the issue. See screenshots created in my last comment. Both products are on that same instance.

Option titles are dropped like shown on your screenshot.
The option order is screwed, look at product with SKU product_b.
I verified this on a local instance where I could also see that the database values for sort_order = 0 for the last 5 products.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch again and the issue is reproducible.
Hence confirming the issue.
New Product B created by importing Product A options - Sorting order is changed before save and after save
Updated description of steps to reproduce. 
![image](https://user-images.githubusercontent.com/60198231/159416086-f848d441-e576-42f0-9835-b64e0f352422.png)

![image](https://user-images.githubusercontent.com/60198231/159416046-d776c097-77ca-4ba9-8703-3e635d33a96e.png)

**Comment by yvaliya** [comment]
No problem, thanks anyway.

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by anvanza** [comment]
@engcom-Hotel , Where can I find the PR ?

**Comment by engcom-Hotel** [comment]
Hello @anvanza,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2678 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2678&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks
