### ISSUE TITLE
Adding tier_price to product comparison will crash the page

### ISSUE THREAD

**Issue by Tjitse-E** [magento/magento2#35244]
### Preconditions (*)

1. Magento 2.4.2-p1
2. PHP 7.4

### Steps to reproduce (*)

1. Go to the Magento 2 admin panel
2. Go to stores > attributes > product
3. Search for 'tier_price'
4. Open the tier price attribute and go to the 'Storefront properties' tab.
5. Set 'Comparable on storefront' on 'yes'
6. Go to the frontend
7. Add two products to the products comparison
8. View the product comparison

### Expected result (*)

1. See the product comparison, no errors

### Actual result (*)

1. The page will crash:
> 1 exception(s):
> Exception #0 (Exception): Notice: Array to string conversion in vendor/magento/module-catalog/Block/Product/Compare> > /ListCompare.php on line 208

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Issue: Compare Products page is empty.
User have to click again on Compare Products link to display the products.
![image](https://user-images.githubusercontent.com/60198231/160590636-302339de-1217-4133-89e3-e9f7e2b3ff53.png)

Exeption stacktrace:
`
[2022-03-29T10:19:03.325092+00:00] main.CRITICAL: Exception: Notice: Array to string conversion in /var/www/html/mg24/magento2/app/code/Magento/Catalog/Block/Product/Compare/ListCompare.php on line 208 in /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 /var/www/html/mg24/magento2/app/code/Magento/Catalog/Block/Product/Compare/ListCompare.php(208): Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/html/mg24/magento2/app/code/Magento/Catalog/view/frontend/templates/product/compare/list.phtml(131): Magento\Catalog\Block\Product\Compare\ListCompare->getProductAttributeValue()
#2 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#3 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#4 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#5 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#6 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#7 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#8 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#9 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#10 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#11 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#12 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#13 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#14 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#15 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#16 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#17 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#18 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#19 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#20 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#21 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#22 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#23 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#24 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#25 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#26 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#27 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#28 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#29 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#30 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#31 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#32 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#33 /var/www/html/mg24/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#34 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#35 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#36 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#37 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#38 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#39 /var/www/html/mg24/magento2/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#40 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#41 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#42 /var/www/html/mg24/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#43 {main} [] []
`

**Comment by engcom-Hotel** [comment]
The issue has been fixed and merged. Please find the related commits on this link https://github.com/magento/magento2/search?q=AC-2719&type=commits. It will reflect in the 2.4.5 version.

Thanks
