### ISSUE TITLE
Translated catalog names from second store view appear in category dropdown list when creating/editing new products in All Store Views

### ISSUE THREAD

**Issue by jxn0326** [magento/magento2#35259]
**Preconditions (*)**

1. Magento 2.2.5
2. Multiple store views

**Steps to reproduce (*)**

1. Create a second Website
2. Go to catalog category edit screen & translate the attribute "Category Name" to a different language in the store view of the second website
3. Create a new product that is only in the second store & assign a category
4. Create a new product that is only in the first website & assign a category
6. Check the name of the categories in the dropdown list and compare them with the Catalog Names under "All store views" in the catalog category edit screen.

**Expected result (*)**

1. When creating a new product, the language of the category names in the category dropdown list (in the catalog product edit screen) should always be the same as set for "All store views" in the catalog category edit screen.

**Actual result (*)**

1. After the product is published in the second store view, the translated category names of the second store view will appear in the category drop down when creating a new product, even if the Category Name set for "All store views" is different.
2. This causes confusion for admins who do not speak the language of the second store view.
3. A workaround is to go to catalog category edit screen and save the categorys in "All store views" or to manually reindex Category data.

![category name change after save](https://user-images.githubusercontent.com/89451807/161249339-4cebf43e-da00-4e5c-9fc5-09c7ce827c87.png)
![category norway store view](https://user-images.githubusercontent.com/89451807/161249346-d14c9b9c-d689-4c32-be4b-d6c345499538.png)
![category all store views](https://user-images.githubusercontent.com/89451807/161249347-cc7432c5-0502-4466-a714-69cbd2dac755.png)
![category name change before save](https://user-images.githubusercontent.com/89451807/161249850-30a4b2bd-977b-44bf-8567-08d839c5fe17.png)

**Comment by engcom-Delta** [comment]
Hi @jxn0326 ,
Thank you for raising an issue . We tried to reproduce the issue on Magento 2.4 Develop but confused with Step# 2 .
Could you please elaborate on "translate the attribute "Category Name" to a different language "?. I could not find out different language option in the application.Hence request to help in this step.

Please find below screenshot for reference.
<img width="1440" alt="Screenshot 2022-04-05 at 8 24 54 AM" src="https://user-images.githubusercontent.com/51681379/161670375-b87b47b9-97bf-41ee-92ea-99e431362409.png">
Thanks

**Comment by jxn0326** [comment]
What I really meant with step 2 was that in the store view that you're currently viewing, simply overwrite "What's New" with a different text & make sure that the "Use default value" box is blank when you save.

My recreation instructions are a bit biased because we use different languages in every store view. So from one store view to another, the category name is different.

**Comment by engcom-Delta** [comment]
Hi @jxn0326 ,

Thank your quick turn around, we tried to reproduce the issue as per provided steps , we found that issue is reproducible on magento 2.4 Develop with latest branch. Hence confirming it.

Steps followed:

1. Create a second Website
<img width="1440" alt="Screenshot 2022-04-07 at 1 06 20 PM" src="https://user-images.githubusercontent.com/51681379/162146139-32a3e2be-4d9b-40e4-a6bc-0c88ea22e504.png">

2. Go to catalog category edit screen & translate the attribute "Category Name" to a different language in the store view of the second website
<img width="1440" alt="Screenshot 2022-04-07 at 12 58 28 PM" src="https://user-images.githubusercontent.com/51681379/162146433-a7bf7c17-aab8-4e7f-83e0-4abf2cc22ef5.png">
<img width="1440" alt="Screenshot 2022-04-07 at 12 47 50 PM" src="https://user-images.githubusercontent.com/51681379/162146578-0a4123b0-8e47-43b5-877c-8852a54906f5.png">

3. Create a new product that is only in the second store & assign a category
<img width="1440" alt="Screenshot 2022-04-07 at 12 57 12 PM" src="https://user-images.githubusercontent.com/51681379/162146709-48d613e6-cc7d-422f-9a33-67a8db5aea0b.png">

4. Create a new product that is only in the first website & assign a category
<img width="1440" alt="Screenshot 2022-04-07 at 12 59 37 PM" src="https://user-images.githubusercontent.com/51681379/162146829-9fe055ee-574e-4316-9e73-330d529fa76d.png">

5. Check the name of the categories in the dropdown list and compare them with the Catalog Names under "All store views" in the catalog category edit screen.
<img width="1440" alt="Screenshot 2022-04-07 at 1 02 41 PM" src="https://user-images.githubusercontent.com/51681379/162147028-16a85cc2-58de-465b-83c5-dea922d68886.png">

Result: 
in the category dropdown list (in the catalog product edit screen) is not  the same as set for "All store views" in the catalog category edit screen.

<img width="1440" alt="Screenshot 2022-04-07 at 1 03 37 PM" src="https://user-images.githubusercontent.com/51681379/162147078-111c2c02-a2a5-471c-b1fd-a95a8c16e50f.png">

**Comment by gaganmagento** [comment]
@magento I am working on this

**Comment by gaganmagento** [comment]
@magento  give me 2.2.5 instance

**Comment by engcom-Delta** [comment]
Hi @jxn0326 ,

Thanks for your reporting and collaboration.
We have re-verified the issue in 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Create a second Website
![image](https://github.com/user-attachments/assets/bc778aac-99ef-472c-b287-69fbf8c2ea84)
2. Go to catalog category edit screen & translate the attribute "Category Name" to a different language in the store view of the second website
![image](https://github.com/user-attachments/assets/10a89e6a-db51-412a-8255-8e2da13b2e11)
3. Create a new product that is only in the second store & assign a category
4. Create a new product that is only in the first website & assign a category
5. Check the name of the categories in the dropdown list and compare them with the Catalog Names under "All store views" in the catalog category edit screen. Observe , in the category dropdown list (in the catalog product edit screen) is same as set for "All store views" in the catalog category edit screen.
![image](https://github.com/user-attachments/assets/12b8608d-02ab-4047-848f-7d28d4bdd129)
![image](https://github.com/user-attachments/assets/36c3bf94-ae15-4416-b2c6-f34b6d130b0e)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by engcom-Delta** [comment]
Hi @jxn0326 ,

This issue is being closed since it has not been updated in a long time.
Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
