### ISSUE TITLE
Unable to change Magento Favicon for add product & edit product pages

### ISSUE THREAD

**Issue by Surya2211** [magento/magento2#35266]
Preconditions (*)
1. Open magento admin panel
1. Login with valid credentials
1. Dashboard page will be opened

### Steps to reproduce (*)
1. Navigate to Catalog - Products -> Add product/Edit product
1. verify whether user is unable to change magento favicon for add product & edit product pages

Expected result (*)
1. Application owner should able to change the favicon for add product & Edit product like other pages

Actual result (*)
Unable to change Magento Favicon for add product & edit product pages

![](https://user-images.githubusercontent.com/103035998/161732849-c0eb62aa-d0c3-4db6-8be9-4ba6a5335980.png)

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible on existing product edit page:
![image](https://user-images.githubusercontent.com/60198231/161744628-012acd29-c836-40d9-8c93-8bf5c19ca4ed.png)
There is no issue on add new product page:
![image](https://user-images.githubusercontent.com/60198231/161744734-bb8ee6d0-58f4-441e-8860-c770929e8c5f.png)

**Comment by nisha-vaghela** [comment]
@magento i am working on this.

**Comment by nisha-vaghela** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch again and the issue is not reproducible anymore. @Surya2211  Kindly reopen/ create new issue if you are still facing any issues.
Thank you.
