### ISSUE TITLE
Stopped loading on Edge

### ISSUE THREAD

**Issue by OlorinBW** [magento/magento2#35264]
### Preconditions (*)

1. Magneto ver 2.3.7-p2
2. 

### Steps to reproduce (*)

1. Log into using MS Edge, select customer, watch the wheel spin forever 
2. Log into using Chrome, select customer, it works
![Magneto Edge Issues](https://user-images.githubusercontent.com/102988794/161599467-a6833313-7a2b-49a6-ba00-1ba312a1278c.jpg)

### Expected result (*)

1. [Screenshots, logs or description] I attached a screenshot
2. Used to work using edge, which is our companies preferred browser. About 1-2 weeks ago it stopped working on edge. 

### Actual result (*)

1. [Screenshots, logs or description]
2. Edge simply almost never loads. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Microsoft edge browser version used: 100.0.1185.29
Ubuntu: 20.04.4 LTS
![image](https://user-images.githubusercontent.com/60198231/161727273-118edf4e-e1a4-4480-8b19-01865516e3dc.png)
@OlorinBW , FYI.. please check below workaround that may help to resolve your issue 
Inspect the page and check whether any js is loading properly if not loading properly then delete the pub folders and run the below code from the root folder
rm -rf var/* generated/* pub/static/*
chmod -R 777 var/ generated/ pub/static/
php bin/magento setup:upgrade
php bin/magento setup:di:compile
sudo php bin/magento cache:flush
chmod -R 777 var/ generated/ pub/static/
php bin/magento setup:static-content:deploy -f
php bin/magento indexer:reindex
sudo php bin/magento cache:flush
Kindly check on Magento 2.4-develop branch as it the upcoming 2.4.x release and have latest code base and elaborate the steps / configuration details if the issue is still reproducible
Thank you.

**Comment by hostep** [comment]
@engcom-November: you have given extremely bad advise:

- `rm -rf var/*` => this is very dangerous, the `var` directory contains many different things, so you should defintely not delete everything inside it as it might break your shop
- `chmod -R 777` => this might introduce security vulnerabilities by allowing the webserver to write inside these directories, you really don't want this
- `sudo php` => don't advise to use `sudo`, this is really not appropriate

@OlorinBW: please don't follow this advise, it's going to get you into more trouble than you are already in so far.

@sdzhepa, @sidolov: could one of you talk to the engcom squad guys and make sure they no longer provide "advise" in such a manner, I really wouldn't expect this sort of thing from an Adobe employee!

**Comment by sdzhepa** [comment]
hello @hostep 

Thank you for raising this.

@engcom-Hotel pls address additional investigation for this issue and provide sufficient communication.

The recommendation provided by @engcom-November could be some kind OK for local debugging during development or testing. But it is absolutely not OK for any kind of production env, it contradicts best practices and official recommendation

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance
