### ISSUE TITLE
Unable to get filters using REST API which are showing on category pages on left side

### ISSUE THREAD

**Issue by hemendraajmera** [magento/magento2#35326]
### Summary (*)

I am using rest API to develop frontend, i am using products API to get category products, now I want to show filter as similar which are showing category page for magento2 store.
I want rest API which get this filter based on category products 
### Proposed solution

Is there any module or API, please share that so I can implement to get that same user experience for customer to filter products
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment]
> 

HI @hemendraajmera 
Thanks for reporting here with your thoughts. We want to understand bit more about the requirement.

You are using _products API_ to get category products, I understood this point.
Next is, you want to filter categories for a specific store, I am correct here?
If that is the thing, we have the request `/rest/default/V1/categories` to get the categories with their children data.

**Is there anything else you are looking for? If so, Can you please help us to understand with your more detailed description about it?**

Thanks in advance!

**Comment by engcom-Alfa** [comment]
HI @hemendraajmera 
For time being, since there is no response to my last comment in last ~14 days, closing this issue currently.

Kindly upgrade to the latest version `2.4-develop` to re test this issue to re-verify.
Please provide me all the required details in the comment section here, so that I will cross check and re-open the ticket again.
Else, better you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings possibly.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks
