### ISSUE TITLE
Setup Promotion specific to In Store pick up shipping method

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#35334]
### Preconditions (*)

Magento 2.4.2 or 2.4.3-P1
1. Inventory enabled
2. Create new Source and Stock (non default) with Pickup location enabled (Stores - Inventory - Sources and Create new Stock and assign source)
3. Enable In store Pickup delivery (Stores - Configuration - Sales - Shipping Methods)
4. Create Product and assign Stock
5. Create [Cart Price Rule](https://user-images.githubusercontent.com/60198231/164417233-f59d6028-b6f3-404c-9bd6-e85f0f9d41e4.png)
   - Specific Coupon = "DISCOUNT20" 
   - Conditions: Shipping Method is In store Pickup and Actions - 20% discount 

### Steps to reproduce (*)

1. Go to Storefront 
2. Add product to cart 
3. Start checkout
4. Select In Store Pickup delivery and apply discount in checkout page

### Expected result (*)

It should give 20% discount to customer

### Actual result (*)

Coupon is not getting applied
![image](https://user-images.githubusercontent.com/60198231/164417158-a177c8f9-e245-40ca-9aa7-54b6f242e0f3.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by VZeroCool** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Steps performed:
Inventory enabled
Create new Source and Stock (non default) with Pickup location enabled (Stores - Inventory - Sources and Create new Stock and assign source)
Enable In store Pickup delivery (Stores - Configuration - Sales - Shipping Methods)
Create Product and assign Stock
Create Cart Price Rule - Specific Coupon, Conditions - Shipping Method is In store Pickup and Actions - 20% discount
Front -end - Add product to cart - Select In Store Pickup and apply discount in checkout
Issue: Coupon is not getting applied
![image](https://user-images.githubusercontent.com/60198231/164417158-a177c8f9-e245-40ca-9aa7-54b6f242e0f3.png)

Cart Price Rule:
![image](https://user-images.githubusercontent.com/60198231/164417233-f59d6028-b6f3-404c-9bd6-e85f0f9d41e4.png)

**Comment by malafalx91** [comment]
I have magento 2.4.2 and I have this issue. How can I fix this?
