### ISSUE TITLE
Print pdf don't delete file in var folder

### ISSUE THREAD

**Issue by quienti** [magento/magento2#3535]
Magento 2.0.2

If we print a pdf in `Shipment` :
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/13292499/41a99fdc-db1c-11e5-9e38-1ac0a7bc23db.jpg)

We generate the file in folder `var` :
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/13292498/41a663b2-db1c-11e5-804e-761a78179a4a.jpg)

But, this file is never delete !

If we look in this file :
`https://github.com/magento/magento2/blob/2.0/lib/internal/Magento/Framework/App/Response/Http/FileFactory.php#L99-L101`

This code doesn't work for pdf files, but this code work fine for csv files like `export customer`

**Comment by NadiyaS** [comment]
Hi @quienti ,
thank you for reporting this issue. Internal ticket MAGETWO-54083 was created.

**Comment by AntonEvers** [comment]
Isn't it strange that the PDF's are dropped in the var root? I'd rather see them end up in a semantically named subdir or in the var/tmp dir.

**Comment by southerncomputer** [comment]
Just going to put this here for search engine semantics. If you ever try to print pdf's from the frontend and get no such template {} error. It is because magento forgot to place two files in the frontend for the methods to access their templates..

copy the files from adminhtml/templates/info/pdf* to frontend/templates/info/pdf/*

`mkdir vendor/magento/module-payment/view/frontend/templates/info/pdf`
`mkdir vendor/magento/module-offline-payments/view/frontend/templates/info/pdf`

`cp vendor/magento/module-payment/view/adminhtml/templates/info/pdf/* vendor/magento/module-payment/view/frontend/templates/info/pdf/`
`cp vendor/magento/module-offline-payments/view/adminhtml/templates/info/pdf  vendor/magento/module-offline-payments/view/frontend/templates/info/pdf/`

Hope this saves you hours of frustration from seemingly useless error message when trying to print pdf's from the frontend (or email their attachments!)

**Comment by magento-engcom-team** [comment]
@quienti, thank you for your report.
We've created internal ticket(s) MAGETWO-82033 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@quienti, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @quienti. Thank you for your report. 
The issue has been fixed in magento/magento2#16401 by @rogyar in 2.2-develop branch
Related commit(s):
 - [4989d8b358bcaccac21ee5aa985e2359d8abb9ca](https://github.com/magento/magento2/commit/4989d8b358bcaccac21ee5aa985e2359d8abb9ca)
 - [9366da978649cd3549f1732521d45f4963f74d5e](https://github.com/magento/magento2/commit/9366da978649cd3549f1732521d45f4963f74d5e)
 - [70fed741d14a72c11ae7f62c7164b9fd066c532e](https://github.com/magento/magento2/commit/70fed741d14a72c11ae7f62c7164b9fd066c532e)
 - [31df140d545a5a4cecf3b7c410069d0ae169a328](https://github.com/magento/magento2/commit/31df140d545a5a4cecf3b7c410069d0ae169a328)
 - [25d49eb011d2aa7cd232b0139f05ad09cc1fb731](https://github.com/magento/magento2/commit/25d49eb011d2aa7cd232b0139f05ad09cc1fb731)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @quienti. Thank you for your report. 
The issue has been fixed in magento/magento2#17280 by @tiagosampaio in 2.3-develop branch
Related commit(s):
 - [b358932812325776ca46824aaf15f8795d990984](https://github.com/magento/magento2/commit/b358932812325776ca46824aaf15f8795d990984)
 - [d3a7b9729405842e680fd5fafb09285de09ce30b](https://github.com/magento/magento2/commit/d3a7b9729405842e680fd5fafb09285de09ce30b)
 - [5f1e0bf52be0c106de165f304f9d6a582903e0ae](https://github.com/magento/magento2/commit/5f1e0bf52be0c106de165f304f9d6a582903e0ae)
 - [99c5631783417a829523f647d00ed2a5838fad6e](https://github.com/magento/magento2/commit/99c5631783417a829523f647d00ed2a5838fad6e)
 - [ec713fcbb0f33f668540e2c9c625097679b68b2e](https://github.com/magento/magento2/commit/ec713fcbb0f33f668540e2c9c625097679b68b2e)

The fix will be available with the upcoming 2.3.0 release.
