### ISSUE TITLE
Related Products on multiple website not saved when user has limited access 

### ISSUE THREAD

**Issue by salvadorcanillas** [magento/magento2#35351]
### Preconditions (*)

1. Magento 2.4.2 Cloud

### Steps to reproduce (*)

1. Create new website, store and store view
2. Create new User Role, set Role Scopes to Custom and check new website.
3.  Create new user and assign to the new User Role
4.  Login as new user, edit any product. Add a related product

### Expected result (*)

1. Related Products are saved
2. 

### Actual result (*)

1. Related products are NOT saved. If there are existing related products, all are removed.
2. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by salvadorcanillas** [comment]
@magento give me 2.4-develop instance

**Comment by salvadorcanillas** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
Hi @salvadorcanillas ,
Thank you for logging an issue. We tried to reproduce the issue on magento 2.4 develop , unfortunately issue is not reproducible.

Followed below steps:
1. Create new website, store and store view
<img width="1430" alt="Screenshot 2022-04-25 at 8 28 30 PM" src="https://user-images.githubusercontent.com/51681379/165116196-812345ea-95b2-4307-a8e0-b2adb35f4cac.png">
2.Create new User Role, set Role Scopes to Custom and check new website.
<img width="1322" alt="Screenshot 2022-04-25 at 8 29 44 PM" src="https://user-images.githubusercontent.com/51681379/165116447-bf40b059-855a-4045-8fe8-b8d697f65a31.png">
3. Create new user and assign to the new User Role
<img width="1426" alt="Screenshot 2022-04-25 at 8 31 06 PM" src="https://user-images.githubusercontent.com/51681379/165116864-10e2fd0d-411a-4750-b080-703537cdc22f.png">
4. Login as new user, edit any product. Add a related product
<img width="1318" alt="Screenshot 2022-04-25 at 8 35 13 PM" src="https://user-images.githubusercontent.com/51681379/165117768-23edc1cd-015a-445b-937e-ef39bb965cd7.png">


<img width="1440" alt="Screenshot 2022-04-25 at 8 36 28 PM" src="https://user-images.githubusercontent.com/51681379/165117787-75e29f19-14ff-4b63-8bfc-e930848cbfdb.png">

Actual result:
Related products saved successfully without any error.

Hence, request to review the provided steps or pre-condition.

**Comment by salvadorcanillas** [comment]
Updated steps:
2.Create new User Role, set Role Scopes to Custom and check new website. - Make sure that the role has limited scope to the newwebsite.
![roles](https://user-images.githubusercontent.com/40746365/165215368-be312278-70cc-4640-990b-57ce4e386fa6.PNG)


4. Login as new user, edit any product. Add a related product - User should have limited access and can only edit products on the newwebsite level. 
![products](https://user-images.githubusercontent.com/40746365/165215576-1681d37b-0a4d-4eda-9580-b6b1ac22fca8.PNG)

Edit any of the product and add Related Products
![related](https://user-images.githubusercontent.com/40746365/165216057-a0586b60-036b-48fd-9928-833280a6f661.PNG)

**Comment by engcom-Delta** [comment]
Hi @salvadorcanillas ,
Thank you for confirming the scope and issues . We reverified the issue and found that issue is not reproducible in Magento 2.4 Develop. Kindly correct me if my steps are wrong.

Steps followed:
1. Create new website, store and store view [ From Magento Enterprise Edition ]

<img width="1440" alt="Screenshot 2022-04-29 at 8 35 58 PM" src="https://user-images.githubusercontent.com/51681379/165981651-8b4f627b-fb8a-4896-9f92-5fd983b5e1e9.png">

2. Create new User Role, set Role Scopes to Custom and check new website

<img width="1440" alt="Screenshot 2022-04-29 at 9 24 39 PM" src="https://user-images.githubusercontent.com/51681379/165983132-286f11b4-9eb2-4da4-968b-36599f132570.png">

<img width="1440" alt="Screenshot 2022-04-29 at 8 37 20 PM" src="https://user-images.githubusercontent.com/51681379/165982646-adc54f38-d401-4f78-8edc-71ba07b461d5.png">

3. Create new user and assign to the new User Role
<img width="1440" alt="Screenshot 2022-04-29 at 9 48 51 PM" src="https://user-images.githubusercontent.com/51681379/165984775-489cbaa8-1161-4e24-8767-cc81b89f056f.png">

<img width="1440" alt="Screenshot 2022-04-29 at 8 06 40 PM" src="https://user-images.githubusercontent.com/51681379/165982560-7dfaac9b-1ba3-4bb3-a4a8-892b58a3cfcf.png">

4. Login as new user, edit any product. Add a related product

<img width="1440" alt="Screenshot 2022-04-29 at 9 56 39 PM" src="https://user-images.githubusercontent.com/51681379/165985242-b871a354-f3a4-4b02-a108-a7065dc9f8a8.png">

Added 1 related product and saved: 

<img width="1440" alt="Screenshot 2022-04-29 at 9 16 40 PM" src="https://user-images.githubusercontent.com/51681379/165985333-056cc95b-e2ef-4497-a805-981cc86bde38.png">

Again edited the product and added one more related product : 

<img width="1440" alt="Screenshot 2022-04-29 at 9 20 47 PM" src="https://user-images.githubusercontent.com/51681379/165985782-44229803-6b43-47b1-8a3a-4d35ce172837.png">

5. Save 

Actual Results:

Previously added related products are there and newly added one saved successfully. 
<img width="1440" alt="Screenshot 2022-04-29 at 10 03 08 PM" src="https://user-images.githubusercontent.com/51681379/165986450-9d8c21a5-998f-4da2-ac66-a452c722bc25.png">

**Comment by salvadorcanillas** [comment]
Hi,

For step 2, the scope should only be on the newwebsite, please uncheck Main Website.

**Comment by engcom-Delta** [comment]
Hi @salvadorcanillas ,

Thank you for providing more inputs. We tried to replicate it again with updated steps unfortunately issue is not reproducible.


1. Unchecked the Main Website

<img width="1440" alt="Screenshot 2022-05-04 at 12 32 27 PM" src="https://user-images.githubusercontent.com/51681379/166637184-295424b3-f568-4257-84e7-a729caa97a89.png">

2. Role updated

<img width="1440" alt="Screenshot 2022-05-04 at 12 39 58 PM" src="https://user-images.githubusercontent.com/51681379/166637631-4178d7da-f8ec-4c90-b756-64c464a4d859.png">

3. Added related products and saved
<img width="1440" alt="Screenshot 2022-05-04 at 12 53 25 PM" src="https://user-images.githubusercontent.com/51681379/166638384-11bb2ad1-cd67-41e7-8314-2db7d563aa8f.png">


<img width="1440" alt="Screenshot 2022-05-04 at 12 43 07 PM" src="https://user-images.githubusercontent.com/51681379/166637788-f6b1f6e7-2d69-4f46-92ff-cbe3c3a24dc5.png">

5. No error displayed and existed products are remain same.

<img width="1440" alt="Screenshot 2022-05-04 at 12 43 07 PM" src="https://user-images.githubusercontent.com/51681379/166637925-c954c455-fad2-4777-be33-52b60cfab047.png">

Hence , request to review the steps provided and correct me if i am wrong.

**Comment by salvadorcanillas** [comment]
Hi,

We have already purchased an extension to allow saving related products on different store view and access level. You may now close this if you can't  replicate. 

Thanks

**Comment by engcom-Delta** [comment]
As per confirmation from @salvadorcanillas  , We have noticed that purchasing of extension helped them to resolve this issue . so we are closing it.Please raise a fresh  ticket or reopen this ticket if you need more assistance on this.
