### ISSUE TITLE
You can change the e-mail address to current e-mail address

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#35363]
Our marketing criticised that you can use the current e-mail 

### Preconditions (*)

1. Fresh Magento 2.4.4

### Steps to reproduce (*)

1. Login to your account.
2. Go to "My Account"
3. Click on **Edit** under Account Information -> Contact Information.
4. Click on the Checkbox "Change Email"
5. Enter your current E-Mail address.
6. Enter your current Password.
7. Click on "Save".

![demo](https://user-images.githubusercontent.com/16349349/165060017-b225c1b7-22a5-4be0-84fa-3faf8791bfae.gif)

### Expected result (*)

1. There should be an error, because you actually did not changed the e-mail, it is still the same.

### Actual result (*)

1. No error

![demo](https://user-images.githubusercontent.com/16349349/165060017-b225c1b7-22a5-4be0-84fa-3faf8791bfae.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Eddcapone ,
Thanks you for raising an issue . We tried to reproduce the issue on Magento 2.4.4 ,issue is reproducible . Hence issue is confirming.
**Steps followed:** 

1. Login to your account From Frontend
2. Go to "My Account"
3. Click on Edit under Account Information -> Contact Information.
4. Click on the Checkbox "Change Email"
<img width="1440" alt="Screenshot 2022-04-25 at 9 48 43 PM" src="https://user-images.githubusercontent.com/51681379/165131052-91530044-ad07-4f75-acd5-5a7605d0e3f6.png">

5. Enter your current E-Mail address.
6. Enter your current Password.
7. Click on "Save".
Actual Result:
Current email id is updated successfully without any error ( It happens on FrontEnd only ).
<img width="1440" alt="Screenshot 2022-04-25 at 9 48 48 PM" src="https://user-images.githubusercontent.com/51681379/165131294-52f9feeb-2763-4ba5-ab63-9993f3414654.png">

**Comment by engcom-Delta** [comment]
Hi @Eddcapone ,
We have moved this issue to On Hold status due to retesting is in progress . We will revert back as soon as we get our findings.
Thanks

**Comment by engcom-Delta** [comment]
Hi @Eddcapone,

We have received comments from Security team Product Owner Nathan Smith on this issue  as follows:
"As far as what is required, the only standard that we follow that would be relevant here is PCI compliance. Technically 8.2.5 says
8.2.5 Do not allow an individual to submit a new password/passphrase that is the same as any of the last four passwords/passphrases he or she has used.
But PCI doesn’t apply to storefront customers, only to admin users because customers cannot access any PCI/PII data. So really, we do not have any compliance or security requirements that mandate this behavior to change. If the merchant would like to customize this behavior they are welcome to add additional validations but we do not have anything on our roadmap to address this. ".

Hence closing the issue.
