### ISSUE TITLE
You can change the password to the current password

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#35364]
Our marketing criticised that you can use the current e-mail 

### Preconditions (*)

1. Fresh Magento 2.4.4

### Steps to reproduce (*)

1. Login to your account.
2. Go to "My Account"
3. Click on **Edit** under Account Information -> Contact Information.
4. Click on the Checkbox "Change Password"
5. Enter your current Password in each field.
6. Click on "Save".

### Expected result (*)

1. There should be an error, because you actually did not changed the password, but used the current one.

### Actual result (*)

1. No error showing.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Eddcapone ,
Thank you for raising an issue .We tried to reproduce it on Magento 2.4.4 .Issue is reproducible.
Steps followed:
1. Login to your account.
2. Go to "My Account"
3. Click on Edit under Account Information -> Contact Information.
<img width="1440" alt="Screenshot 2022-04-25 at 8 58 36 PM" src="https://user-images.githubusercontent.com/51681379/165122550-078b7339-d657-4b44-b622-13eed0fad997.png">
4. Click on the Checkbox "Change Password"
5. Enter your current Password in each field.
6. Click on "Save".
<img width="1440" alt="Screenshot 2022-04-25 at 9 05 23 PM" src="https://user-images.githubusercontent.com/51681379/165123258-6e16f477-b87d-4c14-8875-92d49b72c4f4.png">

Actual Results: there is no error displayed on changing the password and able to login successfully with new password.
Hence issue is confirmed.

**Comment by engcom-Delta** [comment]
Hi @Eddcapone ,
We have moved this issue to On Hold status due to retesting is in progress . We will revert back as soon as we get our findings.
Thanks

**Comment by engcom-Delta** [comment]
Hi @Eddcapone ,

We received comments from Security team PO @Nathan Smith as below.

"As far as what is required, the only standard that we follow that would be relevant here is PCI compliance. Technically 8.2.5 says
8.2.5 Do not allow an individual to submit a new password/passphrase that is the same as any of the last four passwords/passphrases he or she has used.
But PCI doesn’t apply to storefront customers, only to admin users because customers cannot access any PCI/PII data. So really, we do not have any compliance or security requirements that mandate this behavior to change. If the merchant would like to customize this behavior they are welcome to add additional validations but we do not have anything on our roadmap to address this."

Hence , we are closing the issue.
Thanks
