### ISSUE TITLE
Long foreign key names and db_schema.xml

### ISSUE THREAD

**Issue by bonner-earle** [magento/magento2#35394]
### Preconditions (*)

1. Magento 2.4.3-p1
2. Running in docker https://github.com/magento/magento-cloud-docker version 1.2.4

### Steps to reproduce (*)

1. Create a FK in db_schema.xml such that a computed name of `FK_<table>_<column>_<referencedTable>_<referencedColumn>` is longer than 63 characters, set the referenceId to be a string less than 63 characters, and set onDelete="RESTRICT".
2. Deploy 
```docker-compose run --rm deploy cloud-deploy```
3. It will create the FK in the db with a shortened name starting FK_ then a series of letters and numbers.
4. Generate the whitelist file
```docker-compose run --rm deploy magento-command setup:db-declaration:generate-whitelist --module-<MyModule>```
5. It will put the shortened generated name of the FK into the whitelist file  
6. Dropping the constraint by hand in the db and rerunning the deploy adds it back with the same shortened name
7. On a second box, that we think is identical (if it isn't we can't figure out what the different is) get the code and run a deploy
Initially it errored with 
RESTRICT isn't a valid value, switching this to NO ACTION got past that error

8. It then errored with
```
Element 'constraint', attribute 'referenceId': 'FK_<table>_<column>_<referencedTable>_<referencedColumn>' is not a valid value of the union type 'referenceIdType'.
Line: 35

Element 'constraint', attribute 'referenceId': Warning: No precomputed value available, the value was either invalid or something strange happened.
Line: 35
```

Changing the referenceId in the schema file and in the whitelist file to refer to `FK_<table>_<column>_<referencedTable>_<referencedColumn>` doesn't error on deploy
it creates a FK with the shortened name in the db
9. Put the updated db_schema and whilelist back on the first box and deploy, it deployed and the FK still has the generated shortener name in the db.

I realise these steps don't exactly specify how to reproduce the issue but that is because I don't know exactly how to reproduce the issue.

### Expected result (*)

1. Somewhat ignoring that fact that running the same code on what we believe are identical boxes produced different answers my issues are.
I don't get why the valid reference for the foreign key name that was shorter than 63 characters defined in the db_schema wasn't used as the FK name in the db and instead a generated shorten name was created.
Why on the first box is it valid to have both references of `FK_<table>_<column>_<referencedTable>_<referencedColumn>` and the generated shortened name as acceptable?
So I believe the handling of this scenario could be improved if for example the whitelist generating tool create output with using the fk name `FK_<table>_<column>_<referencedTable>_<referencedColumn>`
3. RESTRICT is a valid option in mariadb https://mariadb.com/kb/en/constraint/, I've included this because this is what happened to us, I realise this is could be caused by a change to a db setting that I haven't found googling the problem. My main problem is the first point, this is here more in case .

### Actual result (*)

1. See above
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ yes ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nishant04412** [comment]
@magento give me 2.4-develop instance

**Comment by bonner-earle** [comment]
FYI, edited the description so `FK_<table>_<column>_<referencedTable>_<referencedColumn>` is displayed correctly

**Comment by ChameleonDevil** [comment]
@bonner-earle At original poster, did you ever manage to figure out how this works?

It feels like the very first time you **install your module**, _that is the db_schema.xml is being used_.

I have created a similar question : `indexes (instead of FK) entities` but I am getting similar behaviour.  I would appreciate any information on **how to completely remove and clear any cached information; because even now since last week I still the same behaviour**, it just ignores my _NEW names (which are shorter)_.

Any assistance here or on SO would be appreciated:
[[db_schema.xml setup:db-declaration:generate-whitelist: Constraints/index changes are not applied/refreshed - (Is there cached db_schema.xml?)](https://magento.stackexchange.com/questions/360898/db-schema-xml-setupdb-declarationgenerate-whitelist-constraints-index-changes)](https://magento.stackexchange.com/questions/360898/db-schema-xml-setupdb-declarationgenerate-whitelist-constraints-index-changes)

**Comment by bonner-earle** [comment]
@ChameleonDevil Hello, I didn't try to figure out how it works, I expected it would be complicated, we have only run into the issue once so far, so has not bee a pressing issue for us. We ended up with names in the schema which are longer than 63 characters, and with generated short names in the actual database.

**Comment by ChameleonDevil** [comment]
Ok, thank you for the prompt reply!

I was hoping for better news, because those auto-generated names mean nothing and read badly when quickly trying to determine content of constraints and indexes using `information_schema.STATISTICS` table.

I have deleted everything and even uninstalled the module twice, restarting server and still as soon as I reinstall the module the old names (auto-generated) names are used.  

At this point I believe there is some kind of bug where Magento just ignores new indexed names; but why and how I don't understand.

**Comment by ChameleonDevil** [comment]
@engcom-Hotel This issue relates to older versions as well, I am running a 2.3.7 version; so would be great if you can let us know about patched files with improvements on this feature.

At the moment I assume I would need to use `Data patches` using `implement \Magento\Framework\Setup\Patch\DataPatchInterface` and try to see if I am able to `ALTER TABLE ... RENAME INDEX` from these horrible auto-generated index names to the *actual names I am specifying inside the db_schema.xml*.  It's clearly a feature that is not working; or names ignored for some obscure reasons.

**Comment by ChameleonDevil** [comment]
For reference to anyone that might find this useful:

An update on the index name issue:

- This commit claims to be named : [Index names are ignored by declarative schema](https://github.com/magento/magento2/commit/d6b614fc94c1f738700e76830f6bfde774582f08), *however my files locally are exactly the same as this commit*.

- *`referenceId` appears to _only be used by whitelist as a reference for the index_, but does not *apply this name*, even though it appeared from the documentation to do that. 
 I do not know if the documentation I read from Adobe is accurate or not, but it always hinted that `referenceId` can be used as the index name in database table as well.*

- Looking at the code while debugging I found the relevant files:

*All of these are in `vendor/magento/framework/Setup`:

````
./Setup/Declaration/Schema/Declaration/SchemaBuilder.php 

SchemaBuilder::build() -> SchemaBuilder::processTable() -> $table->addIndexes($this->processIndexes($tableData, $resource, $table))

````

Relevant code for `processIndexes`:

````
    private function processIndexes(array $tableData, string $resource, Table $table): array
    {
...... trimmed
            $indexData['name'] = $this->elementNameResolver->getFullIndexName(
                $table,
                $indexData['column'],
                $indexData['indexType'] ?? null
            );
... trimmed
    }
````

`./Setup/Declaration/Schema/Declaration/TableElement/ElementNameResolver.php`:
`````
    public function getFullIndexName(
        Table $table,
        array $columns,
        ?string $type = AdapterInterface::INDEX_TYPE_INDEX
    ): string {
        if (AdapterInterface::INDEX_TYPE_PRIMARY === $type) {
            return strtoupper(AdapterInterface::INDEX_TYPE_PRIMARY);
        }

        /**
         * Temporary solution.
         * @see MAGETWO-91365
         */
        $isIndexTypeOutOfList = false === array_search(
            $type,
            [AdapterInterface::INDEX_TYPE_FULLTEXT, AdapterInterface::INDEX_TYPE_UNIQUE]
        );
        if ($type && $isIndexTypeOutOfList) {
            $type = AdapterInterface::INDEX_TYPE_INDEX;
        }

        $tableName = $this->tableNameResolver->getNameOfOriginTable($table->getName());

        return $this->resourceConnection
            ->getIdxName(
                $tableName,
                $columns,
                $type
            );
    }
````

The definition appears to be the same of the commit mentioned, and there appears to be nothing here defined that uses the indexed (`referenceId`) name.

### Summary (Solution)

I have two options:

The first option seems to be easier to implement:

- I guess creating a Plugin for `ElementNameResolver::getFullIndexName()` would be what I need to do (and then make sure I *only change the new custom module/s I want to update, keeping everything else intact*.

- Or alternatively fiddle with the DB table creation and creating a `function renameIndex()` that handles existing index renames, at first I thought there is a function that does this, but it appears only to have `./Setup/Declaration/Schema/Dto/Table::addIndexes` (no rename index / update index)

````
    /**
     * Add indexes
     *
     * This is workaround, as any DTO object couldnt be changed after instantiation.
     * However there is case, when we depends on column definition we need modify our indexes
     *
     * @param array $indexes
     */
    public function addIndexes(array $indexes)
    {
        $this->indexes = array_replace($this->indexes, $indexes);
    }
````

**Comment by engcom-Hotel** [comment]
Hello @bonner-earle,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but it seems it is working as mentioned in the [documentation](https://developer.adobe.com/commerce/php/development/components/declarative-schema/configuration/#db_schema-structure).

<img width="783" alt="image" src="https://user-images.githubusercontent.com/51681618/198532242-ab6c33c7-6855-4f2f-8633-dd098564be8d.png">

Actually, we have made a module in order to reproduce it, which is attached for reference here:

[Magz.zip](https://github.com/magento/magento2/files/9886334/Magz.zip)

The foreign is created as follows:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/51681618/198532786-28fecfb3-e669-4bae-83ea-e6014d7b83f4.png">

Let me know in case we have missed anything here.

Thanks
