### ISSUE TITLE
 Error: Undefined constant Braintree\PaymentInstrumentType::ANDROID_PAY_CARD

### ISSUE THREAD

**Issue by mrrobotisback** [magento/magento2#35434]
### Preconditions (*)

1. Magento community 2.4.4
2. Php 8.1.5

### Steps to reproduce (*)

1. New magento 2.4.4 install
2. Go to Reports -> Braintree Settlement

### Expected result (*)

1. Show grid

### Actual result (*)

1. Error: Undefined constant Braintree\PaymentInstrumentType::ANDROID_PAY_CARD in /var/www/html/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php:49
Stack trace:
#0 /var/www/html/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php(29): PayPal\Braintree\Ui\Component\Report\Listing\Column\PaymentType->getAvailablePaymentTypes()
#1 /var/www/html/vendor/magento/module-ui/Component/Form/Element/AbstractOptionsField.php(67): PayPal\Braintree\Ui\Component\Report\Listing\Column\PaymentType->toOptionArray()

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by mrrobotisback** [comment]
@magento give me 2.4.4-develop instance

**Comment by shubham-cedcoss** [comment]
@magento I am working on this

**Comment by engcom-Delta** [comment]
Hi @mrrobotisback ,
Thank you for raising an issue , we tried to reproduce it on Magento 2.4.4 instance and found that issue is reproducible.
Hence issue has been confirming .

Steps followed:
1. Log into Backend(Admin portal)

<img width="1440" alt="Screenshot 2022-05-09 at 3 05 21 PM" src="https://user-images.githubusercontent.com/51681379/167383393-9ce25a2f-8760-4629-a775-6099cd88516b.png">


2. Click on Reports--> Sales--> Braintree settlements

<img width="1440" alt="Screenshot 2022-05-09 at 3 08 15 PM" src="https://user-images.githubusercontent.com/51681379/167383562-a93b4617-9c29-440e-ab72-b74c166b2c4b.png">


3. Observe the error from Admin portal dashboard 

<img width="1440" alt="Screenshot 2022-05-09 at 2 59 09 PM" src="https://user-images.githubusercontent.com/51681379/167382787-be1ad5ae-11d7-49a1-aae3-5aa2df54a5e7.png">

4. Verify the debugging logs.
<img width="1440" alt="Screenshot 2022-05-09 at 2 58 28 PM" src="https://user-images.githubusercontent.com/51681379/167382907-04316778-0ffe-468f-a398-abd502188ac6.png">

**Actual results** 

Error: Undefined constant Braintree\PaymentInstrumentType::ANDROID_PAY_CARD in /opt/homebrew/var/www/magento244/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php:49

**Comment by Pranav-242** [comment]
@magento i'm working on this.

**Comment by Pranav-242** [comment]
@magento add to contributors team

**Comment by Pranav-242** [comment]
@magento i'm working on this

**Comment by cctorres** [comment]
@engcom-Delta Please fix this problem.

/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php on line 49
PaymentInstrumentType::ANDROID_PAY_CARD => __(PaymentInstrumentType::ANDROID_PAY_CARD) 

change it to
PaymentInstrumentType::GOOGLE_PAY_CARD => __(PaymentInstrumentType::GOOGLE_PAY_CARD)

That is the variable defined by 
/vendor/braintree/braintree_php/lib/Braintree/PaymentInstrumentType.php

**Comment by cctorres** [comment]
@magento i'm working on this

**Comment by cctorres** [comment]
@magento add to contributors team

**Comment by cctorres** [comment]
@magento i'm working on this

**Comment by engcom-Hotel** [comment]
Hello,

The issue has been fixed by the ext-Braintree developers and as per the developers, this has been provided with Magento 2.4.6 release. Meanwhile, if someone faced this issue can use the below patch provided by them:

```
diff --git a/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php b/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php
index 211ae14f..0cf553aa 100644
--- a/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php
+++ b/vendor/paypal/module-braintree-core/Ui/Component/Report/Listing/Column/PaymentType.php
@@ -46,7 +46,7 @@ private function getAvailablePaymentTypes(): array
             PaymentInstrumentType::PAYPAL_ACCOUNT => __(PaymentInstrumentType::PAYPAL_ACCOUNT),
             PaymentInstrumentType::CREDIT_CARD => __(PaymentInstrumentType::CREDIT_CARD),
             PaymentInstrumentType::APPLE_PAY_CARD => __(PaymentInstrumentType::APPLE_PAY_CARD),
-            PaymentInstrumentType::ANDROID_PAY_CARD => __(PaymentInstrumentType::ANDROID_PAY_CARD)
+            PaymentInstrumentType::GOOGLE_PAY_CARD => __(PaymentInstrumentType::GOOGLE_PAY_CARD)
         ];
         // @codingStandardsIgnoreEnd
     }
```

Hence closing this issue. As nothing to be fixed at the Magento end.

Thanks
