### ISSUE TITLE
Issue with Ordering from Gift Registry Magento 2.4.4 Enterprise/Commerce

### ISSUE THREAD

**Issue by shawkatalam-dev** [magento/magento2#35432]
### Preconditions (*)

1. We are using Magento 2.4.4 Enterprise/Commerce Edition with PHP 8.1
2. MySQL 8.0
3. Ubuntu 20.04 LTS
4. nginx 1.18
5. Trying to place order from registrants gift registry item

### Steps to reproduce (*)

1. Add a product to gift registry
6. share the gift registry link
7. open the gift registry link in another browser/incognito window
8. Add qty and add to cart the item
9. Go to Checkout Page, select shipping method(As shipping address is already selected, provided by the registrant)
10. Select the payment Method
11. Click on Place Order Button

### Expected result (*)

1. The order should get placed and the registrant should get gift registry update email
2. 

### Actual result (*)

1. Something went wrong with your request. Please try again later.
2. In log we can see the error Call to a member function getUpdatedQty() on null in /var/www/html/local.magento244.com/vendor/magento/module-gift-registry/Block/Email/Items.php:61
3. 
![Screenshot from 2022-05-06 00-33-19](https://user-images.githubusercontent.com/55043505/167009806-37ac2ddf-05f4-4324-b9ef-e87e5e708a34.png)
4. The order is not placed

**Comment by engcom-Delta** [comment]
Hi @shawkatalam-dev ,

Thank you for logging an issue . We tried to reproduce the issue on 2.4 develop ( Enterprise Edition) Frontend , but need more clarity on step 3 & step 4. 

Followed steps:

1. Add a product to gift registry

<img width="1440" alt="Screenshot 2022-05-06 at 7 38 36 PM" src="https://user-images.githubusercontent.com/51681379/167153674-ba1165c9-8f60-4c01-9401-1b66b7696047.png">

2. share the gift registry link

<img width="1440" alt="Screenshot 2022-05-06 at 7 42 21 PM" src="https://user-images.githubusercontent.com/51681379/167153789-410a3b9a-0a23-4eab-ab4d-723faa5c3add.png">

3. open the gift registry link in another browser/incognito window

Query : Which link we suppose to use at this movement ? the link that we got in the email ? or the link that present on the frontend?

4. Add qty and add to cart the item
Query: May i have screenshots please? 

Hence, request to help me to reproduce the issue.

**Comment by shawkatalam-dev** [comment]
Hello ,

We are using vanilla Magento instance. Below is the more detailed steps to reproduce the issue.

1. First add a product to gift registry from cart page

![image](https://user-images.githubusercontent.com/55043505/168572754-462de90e-9466-4aca-8931-483c50f765d4.png)

2. Go to your gift registry and click on the share button/link

![image](https://user-images.githubusercontent.com/55043505/168573227-03859968-6127-4b11-a695-e6b05ef9034a.png)

3. Now add Message , Invitee Details and share the Gift Registry

![image](https://user-images.githubusercontent.com/55043505/168574175-98383a9c-300f-4829-9ec2-a53c383768ba.png)

4. Open the email id and click on the registry location link (Suggest to use another browser or try incognito mode, so that it does not use the current user session)

![image](https://user-images.githubusercontent.com/55043505/168574729-515b887c-7ee0-46b0-b44c-0a0a25f8b376.png)

5. Now add qty and click on Add To Cart

![image](https://user-images.githubusercontent.com/55043505/168575251-da9f89fd-4a1d-4013-9bef-3f26b3822595.png)

6. After that do the usual checkout process and go to the payment page , select any payment method and click on place order.

expected is the order should be placed, but we are getting error

![image](https://user-images.githubusercontent.com/55043505/168580656-216adf4a-ba33-4d2f-9e8a-9844df9646e4.png)

When we checked log we can see the below message 

![image](https://user-images.githubusercontent.com/55043505/168581016-6e548ec9-bf6b-4b1a-a876-e4d459eb9e43.png)


Hope this information is useful.

**Comment by shawkatalam-dev** [comment]
@magento give me 2.4-develop instance. I want to check in vanilla instance as well

**Comment by engcom-Delta** [comment]
Hi @shawkatalam-dev ,

Thanks for sharing the details and we have retested it again on Magento Enterprise Edition 2.4 Develop. Issue is reproducible. Hence issue is confirmed.
1. First add a product to gift registry from cart page
<img width="1440" alt="Screenshot 2022-05-19 at 8 52 29 PM" src="https://user-images.githubusercontent.com/51681379/169334751-609edb87-f65f-424e-a1c8-bd352d07c160.png">

2. Go to your gift registry and click on the share button/link

<img width="1440" alt="Screenshot 2022-05-19 at 9 01 05 PM" src="https://user-images.githubusercontent.com/51681379/169337295-562ee0c4-3bb4-4dfc-bde9-30f0e8ec0558.png">

3. Now add Message , Invitee Details and share the Gift Registry

<img width="1440" alt="Screenshot 2022-05-19 at 7 46 53 PM" src="https://user-images.githubusercontent.com/51681379/169337441-4e523dbc-19ac-4b49-8e4d-369e178b5cdf.png">

4. Open the email id and click on the registry location link (Suggest to use another browser or try incognito mode, so that it does not use the current user session)

<img width="693" alt="Screenshot 2022-05-19 at 8 16 10 PM" src="https://user-images.githubusercontent.com/51681379/169335685-24c3f2b0-3f97-40d9-ad0f-433c9469be68.png">

5. Now add qty and click on Add To Cart

<img width="1440" alt="Screenshot 2022-05-19 at 8 22 42 PM" src="https://user-images.githubusercontent.com/51681379/169335914-de7d0976-7d7c-4e71-8dbe-b9201bb7c77a.png">

6. After that do the usual checkout process and go to the payment page , select any payment method and click on place order.
7. Getting the below error .

<img width="1440" alt="Screenshot 2022-05-19 at 8 42 16 PM" src="https://user-images.githubusercontent.com/51681379/169336067-055fa534-02a9-47d1-a7c4-f7235fa3421a.png">

**Comment by Pranav-242** [comment]
@magento i'm working on this.

**Comment by veloraven** [comment]
Internal Team started working on this issue
