### ISSUE TITLE
Create Product Configurations - Step 3: "drag image here" adds to all attribute variations

### ISSUE THREAD

**Issue by RebeccaBrocton** [magento/magento2#3548]
Configurable Product Information Admin Page > Create Configurations > Step 3: Bulk Images, Price, and Quantity > Images > Apply unique images by attribute to each SKU >  Select attribute >  "...drag image here" adds the image to all attribute variations, not just the one it was dragged on to. 

Watch issue here: http://rebeccatroth.co.uk/wp-content/uploads/2016/02/configurationsbug2.gif

**Comment by antboiko** [comment]
Hi @RebeccaLTroth , the image link doesn't work.

Could you please reattach it?

Thanks,
Anton.

**Comment by RebeccaBrocton** [comment]
Hi @antboiko, fixed :) 

http://rebeccatroth.co.uk/wp-content/uploads/2016/02/configurationsbug2.gif

**Comment by antboiko** [comment]
@RebeccaLTroth 
Hi Rebecca, thanks for reporting this issue. We've created internal ticket MAGETWO-50270.

Best,
Anton.

**Comment by veloraven** [comment]
This issue was already fixed for ver 2.1.
Internal ticket for ver. 2.0 - MAGETWO-57137
But as it's unlikely that it will be fixed I'm closing this issue

**Comment by korostii** [comment]
hi @veloraven,
> But as it's unlikely that it will be fixed I'm closing this issue

What's that supposed to mean? Are you able to see the future?
Or are you saying that even a community pull request backporting this fix won't be accepted? In that case, would you mind adding it as a "known issue" to the 2.0.x's release notes?

If you meant to say "Magento, Inc. decided no to put any effort into backporting this issue", why not mark it as "up for grabs" so that someone from community might notice it and put some effort into the backport? 
To me, "closed" means there is nothing to be done here as the bug either cannot be reproduced OR is fixed already. This issue is neither of those.
