### ISSUE TITLE
A is NULL, and B is NULL, then A equals with B? No!

### ISSUE THREAD

**Issue by SunshineTech** [magento/magento2#3551]
https://github.com/magento/magento2/pull/3365

**Comment by dsikkema-magento** [comment]
In the PHP level, after entities have been loaded from MySQL, if we had two unique keys that were both equal to null, it could create problems (because in php, null == null). If you can find an example of faulty behavior or design that is related to the null check, please feel free to describe the error in a new issue and we'll look into it.
