### ISSUE TITLE
Where is MAGETWO-36632 , i was not found , everyone , help  me !!!!!

### ISSUE THREAD

**Issue by zhaoxiong123** [magento/magento2#3553]
Where is MAGETWO-36632 , i was not found , everyone , help  me !!!!!

**Comment by mazhalai** [comment]
MAGETWO-36632 is an internal ticket, what exactly are you looking for?

**Comment by davidalger** [comment]
@zhaoxiong123 Anything starting with MAGETWO- is an internal ticket reference number. They are used internally to track tickets. If you search for these here on GitHub, you'll find the issues relevant to the noted internal number. That said, I'm closing, as this is not a technical issue. If you have a bug to report, please open an issue with steps to reproduce and env details, otherwise you may head over to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
