### ISSUE TITLE
Redis 6.2.7 compatibility 

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#35570]
### Preconditions and environment

- Magento 2.4.4
- Redis 6.2.7 (image bitnami/redis:6.2.7-debian-10-r23)

### Steps to reproduce

Run bin/magento c:f

### Expected result

Cache flushed

### Actual result

```
In Cache.php line 209:
                                                                                              
  Error cleaning cache by mode all: ERR unknown command `flushdb`, with args beginning with:  
                                                                                              

In Client.php line 1306:
                                                            
  ERR unknown command `flushdb`, with args beginning with:  
                                                            

cache:flush [--bootstrap BOOTSTRAP] [--] [<types>...]
```

### Additional information

Works fine if we rollback to redis 6.0

Redis 6.2 should be compatible : https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Nuranto ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch with redis-6.2.7 installed and configured but could not able to reproduce the issue.
bin/magento c:f - cleans cache without any errors.
![image](https://user-images.githubusercontent.com/60198231/171856464-c68e8d3a-c3a0-46fa-abe9-8cf536888559.png)
![image](https://user-images.githubusercontent.com/60198231/171856520-85bd133a-0f7f-49a1-b4ef-434aae137d3b.png)
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by Nuranto** [comment]
Seems it was a redis conf issue after all.
Sorry for the noise.
