### ISSUE TITLE
Broken Authentication & Session Management

### ISSUE THREAD

**Issue by newz12** [magento/magento2#35581]
Vulnerability: Broken Authentication & Session Management
I have observed that when we change "password" from one browser in place of session expiration from another browser it just updates the password from another browser and the old session gets updated without being logged out.
The flows goes like this:
Broken Authentication and Session Management > Failure to Invalidate Session > On Password Change

Steps:
1- Login from two browsers at a time [From Chrome browser and from Mozilla Firefox].
2- Change password in settings from chrome browser.
3- Now Check Mozilla Firefox.
4- Your Session got "updated" in place of expiration.

Same goes with when using two different computer systems.
1- Login from two computers at a time
2- Change password in settings from computer A.
3- Now Check computer B.
4- Your Session got "updated" in place of expiration.

Recommendations: If Session is Updating from one Browser/Computer so other should expire first to renew session after login.

**Comment by newz12** [comment]
I will not be able to help you any further, this problem was reported to me by an anonymous source. I'm adding it here so you can investigate this in the Magento core files, as I don't have the technical knowledge to reply back to you. Thanks

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @newz12 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
**Steps performed:**
1. Created account from Magento front-end and signout
2. Login to front-end on chrome and Firefox browsers at same time
3. Chrome browser - My Account - Change password
4. Refresh Firefox browser - User is logged out - No issue.
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by JelleGe** [comment]
Same issue over here, please reopen this issue

**Comment by engcom-November** [comment]
Hi @JelleGe ,
Can you please provide missing steps / configuration details as we are unable to reproduce on 2.4-develop branch with provided steps/ description.
Thank you.

**Comment by JelleGe** [comment]
Hi @engcom-November,

The steps are the same to reproduce on a Magento 2.4.3-p1 install

**Comment by engcom-November** [comment]
@JelleGe ,
Its recommended to verify issues on Magento 2.4-develop branch only as its the upcoming 2.4.x release and have latest code base. Can you please check on 2.4-develop branch whether you are still able to reproduce the issue.
Thank you.

**Comment by JelleGe** [comment]
@engcom-November I will try, can you give me a Magento 2.4-develop branch

**Comment by engcom-November** [comment]
Hi @JelleGe ,
Please comment on this issue as "@magento give me 2.4-develop instance" to get vanilla Magento 2.4-develop instance.
Thank you.

**Comment by engcom-November** [comment]
Hi @JelleGe ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Comment by Keivanph** [comment]
I have a similar case related to using two separate browsers (our test was in Firefox and Chrome) and sessions.
1- user tries to reset the password in browser Firefox
2- user gets the password reset link and set a new password on Firefox
3- use goes to chrome and tries to login with the new password that he/she set in previous step

expected behaviour: User is logged in and is navigated to /customer/account/ 
current behaviour: User is navigated to home page and when she/he clicks on customer icon in navbar, it seems the user is not logged in. The login button is being displayed. If user refreshes the page, she/he is logged in. This seems to be an issue with sessions on different browsers.

This is bit of edge case issue as customers normally do not reset their password on one device/browser and tries to login in another device/browser, but still we faced it sometimes.
