### ISSUE TITLE
Consistant Location for index.php File

### ISSUE THREAD

**Issue by astorm** [magento/magento2#356]
As it stands, Magento 2 currently ships with **two** index.php bootstrap files. One in the root folder

    index.php

and one in the `pub` folder

    pub/index.php

This situation creates some uncertainty for end users of the system as to which folder should be exposed to their web-server.  The includes of a `pub` folder will indicated to some developers that **this** should be the public webroot.  However, developers not familiar with the concept will see `index.php` in the root folder and assume this file should be exposed. 

With commenting on which approach is better, a single approach should be chosen for the file to reduce confusion in the system.  A single location for the "index bootstrap" files should be chosen, and stuck to.  (assuming, of course, there's is not an opaque-but-important reason for the current state of affairs)

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-32660

**Comment by amenk** [comment]
What is the status of the internal ticket?

**Comment by amenk** [comment]
See also https://github.com/magento/magento2/issues/1874

**Comment by astorm** [comment]
No update since September of last year -- assuming this isn't a priority for the engineering team and closing out.

**Comment by piotrekkaminski** [comment]
Hey @astorm. I do understand the confusion it introduces and while we have plans to have single entry point, it is not a priority due to low impact and possibility of affecting many merchants using lower end hosting providers, who still (s)FTP the files and cannot change the webroot. Ideally everyone that can should be using pub as the entry point and I will ask to clarify this in the guides.
