### ISSUE TITLE
Deprecated Functionality: strtoupper(): Currency.php

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#35668]
### Preconditions and environment

- Magento 2.4.4
- PHP 8.1

### Steps to reproduce

Deprecated functionality

### Expected result

PHP 8.1 support.

### Actual result

Not supported.

### Additional information

1 exception(s):
Exception #0 (Exception): Deprecated Functionality: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxx/public_html/vendor/magento/module-directory/Model/ResourceModel/Currency.php on line 65

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jorgb90** [comment]
@engcom-November Its a core php script? The line is not PHP 8.1 compatible right?

**Comment by engcom-Hotel** [comment]
Hello @jorgb90,

Thanks for the reply!

As we can see here https://github.com/magento/magento2/blob/cd826aa2215e19d543a3a606aebde18fa3e40d4e/app/code/Magento/Directory/Model/ResourceModel/Currency.php#L65

and checked the usages of `getRate($currencyFrom, $currencyTo)` method, we haven't found from where `null` value has been passed to this method. We request you to please suggest a way in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @jorgb90,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
