### ISSUE TITLE
Erratic Admin URI's

### ISSUE THREAD

**Issue by devdesco-ceo** [magento/magento2#3570]
Erratic Admin URI's when Multi Site is enabled.
When loading admin from admindomain.zzz, some times Magento admin starts behaving weirdly, it generates admin panel links and form post links to other domains in multisite setup.

**Comment by andimov** [comment]
@devdesco-ceo
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
