### ISSUE TITLE
Incorrect selection price of option for bundle product on product view page when the price type is fixed and not dynamic if option product has customer group prices assigned

### ISSUE THREAD

**Issue by jay-pipaliya** [magento/magento2#35734]
### Preconditions and environment

- Magento version 2.4.x

### Steps to reproduce

- set option price type fixed and value >0  for e.g 6.5 and qty >1 for e.g 12
- open the assigned option product :
1. and in advance pricing set price for customer group for e.g price 1 and qty 12
2. In main price add price greater than 1 for e.g 10

Issue occurs on product view page and works fine on cart and checkout.

### Expected result

It schuld refer to fixed price assigned to option and not tier price to option product.

### Actual result

The price of selection option in product view page refers to tier price of customer group assigned on option product.

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @jay-pipaliya ,

Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
Price displayed is the same (fixed option price but not the ) in all pages: Product details/view, shopping cart page and checkout page
![image](https://user-images.githubusercontent.com/60198231/177983873-245b49a9-aefb-4ed8-a5b0-bd09da0f86cf.png)
![image](https://user-images.githubusercontent.com/60198231/177983925-f1cad8f4-e7f1-486e-9333-e1e6483c93a7.png)
Kindly recheck the issue on Magento 2.4-develop branch as its the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.
