### ISSUE TITLE
Widget multi fields depend

### ISSUE THREAD

**Issue by giangitman** [magento/magento2#3574]
I can not declare multi fields depends like that
`<parameter name="widget_tab" xsi:type="select" required="true" visible="true"
                       source_model="MT\Widget\Model\Widget\Source\Tab">
                <label translate="true">Enable Tabs</label>
                <description translate="true">Enable tab on widget</description>
                <depends>
                    <parameter name="widget_type" value="product" />
                    <parameter name="mode" value="none" />
                </depends>
            </parameter>`

**Comment by andimov** [comment]
@giangitman 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
