### ISSUE TITLE
Can't decrease qty in cart The requested qty is not available

### ISSUE THREAD

**Issue by Harpreet-StreamMarket** [magento/magento2#35780]
### Preconditions and environment

Magento version => 2.4.4

### Steps to reproduce

<ol dir="auto">
<li>Admin - Create a product with Quantity more than 1. ex: 20  (Catalog - Products - Add New Product)</li>
<li>Front-end - Login as Customer - Add the Product to Cart with Quantity say ex: 12</li>
<li>Admin - Edit the Product - Update the Quantity  say ex: 10 and save. Or purchase the Product using other customer Id's so that the stock Quantity available is less than 10</li>
<li>Reindex and clear cache</li>
<li>Front-end - Login using Customer Reload the Shopping Cart page<br>
error messages: "The requested qty is not available" are getting displayed to the user. That is fine and correct.</li>
<li>Now Customer decrease the qty at the cart by setting the qty to 5 and press update button. The update does not work and it throws this dialog: Attention The requested qty is not available. So it seems impossible to change the qty smaller in cart.</li>
<li>Currently only solution is to remove product from cart and re-add it with qty 5 to cart at the product page.</li>
</ol>

### Expected result

Customer update cart with smaller qty successfully

### Actual result

The error messages: "The requested qty is not available" are getting displayed to the user when he tries to decrease the qty.

### Additional information

PHP version => 8.1.7
Disable Magento MSI

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Not able to decrease the qty in cart getting "The requested qty is not available".

**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Admin - Create a product with Quantity more than 1. ex: 20 (Catalog - Products - Add New Product)
2. Front-end - Login as Customer - Add the Product to Cart with Quantity say ex: 12
3. Admin - Edit the Product - Update the Quantity say ex: 10 and save. Or purchase the Product using other customer Id's so that the stock Quantity available is less than 10
4. Reindex and clear cache
5. Front-end - Login using Customer Reload the Shopping Cart page
6. error messages: "The requested qty is not available" are getting displayed to the user. That is fine and correct.
7. Now Customer decrease the qty at the cart by setting the qty to 5 and press update button. The update does not work and it throws this dialog: Attention The requested qty is not available. So it seems impossible to change the qty smaller in cart.
8. Currently only solution is to remove product from cart and re-add it with qty 5 to cart at the product page.

**Expected result:** Quantity should be updated successfully.
**Actual result:** The error messages: "The requested qty is not available" are getting displayed to the user when he tries to decrease the qty.
**Screenshot:**
![image](https://user-images.githubusercontent.com/60198022/179715386-67bc4f46-d415-4c41-b9f7-f8feaccf5469.png)
Hence,confirming the issue.

**Comment by ITCot** [comment]
@magento add to contributors team

**Comment by shmVan** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @Harpreet-StreamMarket,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5987 by the internal team
Related commits: https://github.com/magento/magento2/commit/fd7e45e945796afcb39ef96c57121f494d651754

Based on the Jira ticket, the target version is 2.4.6.

Thanks
