### ISSUE TITLE
magento 2.4 Home page search cannot search products whose names are numbers

### ISSUE THREAD

**Issue by ldc321** [magento/magento2#35793]
### Preconditions and environment

- Magento   2.4.4

### Steps to reproduce

1.The latest Magento2.4 is installed
2.create new product name is 'test-STX-1217-300-DCX'
3.Frontend search this product such as  search "217"

The search for "1217" has results  But Search "217" has no result  !!!

![image](https://user-images.githubusercontent.com/57743360/180374645-1ac43cb5-914b-4d56-8e32-2b69f8464d8d.png)
![image](https://user-images.githubusercontent.com/57743360/180374966-44470802-1d83-4751-bf17-2e95d1123489.png)

### Expected result

The search for "217" has results  

### Actual result
Search "217" has no result  !!!

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @ldc321 ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop branch and is reproducible. But however this an expected behavior of Magento.
217 is not a valid search criteria to be used when searching for the products. If min search length required set is 3, then searching using 121 will give search results.
This behavior is present not only for numbers, but also same behavior exists for alphabets.
![image](https://user-images.githubusercontent.com/60198231/180434862-ab8db2f5-427b-4eac-8ae5-2994c41ecd86.png)
![image](https://user-images.githubusercontent.com/60198231/180435019-8f8053d2-8d6e-4a92-ad60-3f8573c50cb4.png)
![image](https://user-images.githubusercontent.com/60198231/180435062-7d5efc9e-8f3d-4201-9c9b-f0c3cd26a88b.png)

Please check the catalog search configuration. Ref [guide](https://docs.magento.com/user-guide/catalog/search-configuration.html) and provide supporting documents/proofs to consider this as a valid issue.
Thank you.
