### ISSUE TITLE
Admin It's time to change your password Link Is Not Working and Admin login page url key is not added - Magento 2.4.3-p1

### ISSUE THREAD

**Issue by pankajchhatwani** [magento/magento2#35832]
### Preconditions and environment

- admin login page in link not added secure key
![link-not-proper](https://user-images.githubusercontent.com/76781896/181436501-443f90e5-6a7e-4dd9-b778-998a0ec3fc31.png)

- change password link is always redirect starting admin page with 'You entered an invalid Secret Key. Please refresh the page.'
![change-password](https://user-images.githubusercontent.com/76781896/181436653-c01bf03f-b3fc-46b6-83a2-f1fdfc59648b.png)

### Steps to reproduce

- Go to Stores --> Configurations --> Settings --> Advanced --> Admin --> Security --> Password Change
- set Recommended
-  Go to Stores --> Configurations --> Settings --> Advanced --> Admin --> Security --> Password Lifetime (days)
- set 1

### Expected result

redirect  Account Information page 

### Actual result

link is always redirect starting admin page.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by pankajchhatwani** [comment]
> Hi @engcom-Lima, here is your Magento Instance: https://e286f36e860b0ec10533a14ce6dcc27f.instances.magento-community.engineering Admin access: https://e286f36e860b0ec10533a14ce6dcc27f.instances.magento-community.engineering/admin_a497 Login: a9454c8c Password: faedab7f6a4d


Thanks for quick reply

i have changed the configuration for replicated issue : https://prnt.sc/zZUHVmEV6nDS

can you please check link https://prnt.sc/zpAtg35fhu5v

admin url issue image : 
![url-issue](https://user-images.githubusercontent.com/76781896/181450481-264a0dc7-a8fa-4bc7-b55f-50b7c6f6d91e.png)

Thanks!

**Comment by engcom-Lima** [comment]
@magento give me 2.4.1 instance

**Comment by engcom-Lima** [comment]
https://github.com/magento give me 2.4.2 instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** "_Change your password_" link redirecting to dashboard instead of password reset page.

**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Login as admin.
2. Go to Stores --> Configurations --> Settings --> Advanced --> Admin --> Security --> Password Change-> set Recommended
4. Go to Stores --> Configurations --> Settings --> Advanced --> Admin --> Security --> Password Lifetime (days)->set 1.
5. Clear cache.
6. Wait for some time or logout.
7. Login again and click on "Change your password" link on anypage. For ex- from product creation page etc.

**Expected result:**  On clicking it should redirect to password reset page.
**Actual result:**  It is redirecting to Dashboard of the admin page.

Hence, confirming this issue.

Thanks

**Comment by pankajchhatwani** [comment]
@sdzhepa  @engcom-Lima  Team,
Found a solution for it ?

Thanks!

**Comment by MaksSum41** [comment]
@magento I am working on this

**Comment by pankajchhatwani** [comment]
@MaksSum41  Thanks for solution, but actually 

Go to Stores --> Configurations --> Settings --> Advanced --> Admin --> Security --> Password Change
set Recommended

So I think the password page should not be forcefully redirected to update.

@sdzhepa @engcom-Lima 
Thanks!

**Comment by pankajchhatwani** [comment]
The issue is fixed in Magento 2.4.6.
Thanks
