### ISSUE TITLE
Admin product grid gets wrong amount of visible columns if custom view is created

### ISSUE THREAD

**Issue by nukka** [magento/magento2#35897]
### Preconditions and environment

- Magento version 2.4.3

### Steps to reproduce

1. Create one product attribute with default properties from the admin panel. No matter what the input type is. 
2. Open product grid from admin panel.
3. Choose columns you want to be visible in the grid and save the custom view.
4. Change to view back to “Default View”

### Expected result

The default view should have 14 out of 37 visible options
![expected](https://user-images.githubusercontent.com/25184364/183655831-201bd558-f10c-4ca1-b247-023e061badb6.png)

### Actual result

The default view has the wrong amount of visible columns. It has 13 out of 37 visible options. The right result appears when page is refreshed (14 out of 37 visible options)
![result](https://user-images.githubusercontent.com/25184364/183656072-64bb6b4e-01f2-4092-b366-d1a9f754e443.png)

### Additional information

Issue is reproducable on different Magento 2.4 instances. Used Firefox (v. 103.0)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @nukka ,

We have tried to reproduce the issue in Magento 2.4-develop branch the issue is not reproducible.

Please refer the below screenshot for the reference; 
![Screenshot from 2022-08-09 19-38-01](https://user-images.githubusercontent.com/60198592/183670495-142bde23-fd5a-4d73-86a0-3d2cdbd4035f.png)

We have followed the below steps in order to reproduce the issue:

1. Create one product attribute with default properties from the admin panel. 
2.Open product grid from admin panel.
3.Choose columns you want to be visible in the grid and save the custom view.
4.Change to view back to “Default View”

 We are getting expected results.... we are not able to reproduce the issue.

Let us know in case we have missed anything. 

Thanks
