### ISSUE TITLE
Discount Description does not get displayed on cart page

### ISSUE THREAD

**Issue by parekhreena** [magento/magento2#3594]
**Preconditions (*)**

magento 2.3

**Steps to reproduce (*)**

On Cart Page only Coupon codes get displayed. There is no provision to display discount description on Cart Page ? Whereas on Order View Page, checkout page summary everywhere the discount description gets displayed. 

For Cart page In file: /vendor/magento/module-quote/Model/ResourceModel/Quote/Address/Attribute/Frontend/Discount.php - following coding is there:

```
$title = __('Discount');
            $couponCode = $address->getQuote()->getCouponCode();
            if (strlen($couponCode)) {
                $title .= sprintf(' (%s)', $couponCode);
            }
```

Hence, only coupon code gets displayed. 

Whereas, For Order view page in file: /vendor/magento/module-sales/Block/Order/Totals.php - following coding is there.

_initTotals() 

```
 if ($this->getSource()->getDiscountDescription()) {
                $discountLabel = __('Discount (%1)', $source->getDiscountDescription());
            } else {
                $discountLabel = __('Discount');
            }
```

**Actual result (*)**
I am not sure if this is a feature or a bug, but currently discount is displayed differently on cart page as compared to other pages. Which i think is not correct. This is especially highlighted when a coupon code is added to cart and a custom discount with discount description is added to cart. 

**Expected result (*)**

Discount Description should display on cart page

**Comment by sdzhepa** [comment]
@parekhreena  Thank you for reporting this issue. We have created an internal ticket `MAGETWO-50296` to fix the problem.

**Comment by parekhreena** [comment]
@sdzhepa  - Thank you

**Comment by ishakhsuvarov** [comment]
@parekhreena Closing, as the fix for the issue seems to be delivered to the `develop` branch with the commit [`a610b45`](https://github.com/magento/magento2/commit/a610b45e4777b561c95a26d91ad776792a9121f0).
Please feel free to reopen if you have any additional questions.

**Comment by josefbehr** [comment]
On Magento 2.1.3 still only the coupon code gets displayed regarding discounts. Fixed discount starting at specific cart amount (eg over 75€ -> get 2%) is applied, but no label is displayed, even though one can set it for the cart rule.

**Comment by medinadato** [comment]
It's still an issue in Magento 2.1.4. =/

**Comment by josefbehr** [comment]
@ishakhsuvarov This is still an issue in 2.1.7, the supposed fix doesn't work. Please re-open and fix this issue for real.

**Comment by frostbitten** [comment]
Can confirm 2.3.1 still has this issue.

**Comment by magento-engcom-team** [comment]
@shikhamis11 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18899`, `MC-18900` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MaxSouza** [comment]
#mm19br

**Comment by magento-engcom-team** [comment]
@MaxSouza thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by kalpmehta** [comment]
I don't think this is a valid issue. We don't have enough real estate in cart totals box to show full description, and I have seen merchants use Shopping Cart rule's Description field for internal comments as well. Though this could be a nice feature for some of the merchants, I am not sure if this should be rolled out to everyone.

**Comment by josefbehr** [comment]
@kalpmehta I have had many merchants who desperately needed to show their customers which specific discount was applied, instead of just showing the percentage. We definitely need to show the description there, real estate or not. Using the description for internal comments is not a good practice, as the description is displayed in the frontend further down the checkout anyways (unless you remove them). So in my opinion (and as you can see above, many others) this is most definitely a feature that is needed.

**Comment by ghost** [comment]
@magento i'm working on it

**Comment by kalpmehta** [comment]
Thanks @josefbehr for your feedback.

@maxtrezo We already have an open PR on this. https://github.com/magento/magento2/pull/24595

**Comment by magento-engcom-team** [comment]
Hi @parekhreena. Thank you for your report. 
The issue has been fixed in magento/magento2#24595 by @MaxSouza in 2.3-develop branch
Related commit(s):
 - [23382ed8053e515a57561e5cb78173a52320b4cb](https://github.com/magento/magento2/commit/23382ed8053e515a57561e5cb78173a52320b4cb)
 - [217ab79e66e240f06d49dc1cc9413f4aea46a4ce](https://github.com/magento/magento2/commit/217ab79e66e240f06d49dc1cc9413f4aea46a4ce)
 - [83a84a31930d3a609f8c2c515fc2357a2c6197b0](https://github.com/magento/magento2/commit/83a84a31930d3a609f8c2c515fc2357a2c6197b0)
 - [7ec7d6526bda78791301f16ff6cb6a215dbfff77](https://github.com/magento/magento2/commit/7ec7d6526bda78791301f16ff6cb6a215dbfff77)
 - [42edfafe9f3dc32d65a201a39c8df96d1e6db23e](https://github.com/magento/magento2/commit/42edfafe9f3dc32d65a201a39c8df96d1e6db23e)
 - [fb5c663bcf3e1564da47e05294d540df17943b7a](https://github.com/magento/magento2/commit/fb5c663bcf3e1564da47e05294d540df17943b7a)
 - [7eed1166d1885eb0c66d584f37d4cacc9ec3c732](https://github.com/magento/magento2/commit/7eed1166d1885eb0c66d584f37d4cacc9ec3c732)
 - [afd489b26691e063069a845d41af6c5e38f4aa2f](https://github.com/magento/magento2/commit/afd489b26691e063069a845d41af6c5e38f4aa2f)
 - [c1d4190391111f9576dc6cfb18caf7a34d678d68](https://github.com/magento/magento2/commit/c1d4190391111f9576dc6cfb18caf7a34d678d68)
 - [57247f81702f5c5657deb23d9aa5d19ce5acafc1](https://github.com/magento/magento2/commit/57247f81702f5c5657deb23d9aa5d19ce5acafc1)

The fix will be available with the upcoming 2.3.4 release.

**Comment by goutam1github** [comment]
I have managed to fix it creating a plugin to update the description. It separates description by label

public function aroundAddDiscountDescription(
        \Magento\SalesRule\Model\RulesApplier $subject,
        \Closure $proceed,
        $address,
        $rule
    ) {       

        $return = $proceed($address, $rule);

        $description = $address->getDiscountDescriptionArray();
        $ruleLabel = $rule->getStoreLabel($address->getQuote()->getStore());
        $label = '';
        if ($ruleLabel) {
            $label = $ruleLabel;
        } 

        if (strlen($address->getCouponCode())) {
            $label = $address->getCouponCode();

            if ($rule->getDescription()) {
                $label = $rule->getDescription();
            }
        }

        if (strlen($label)) {
            $description[$rule->getId()] = $label;
        }

        $address->setDiscountDescriptionArray($description);  
		
        return $return;
    }

**Comment by kassner** [comment]
Why not displaying the frontend labels instead?

![Screenshot from 2020-04-22 12-01-55](https://user-images.githubusercontent.com/301255/79969335-a6b18e80-8491-11ea-9b91-98c4924910a4.png)
