### ISSUE TITLE
Grave accent character [`] cannot be used for customer's name

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#35951]
### Preconditions and environment

- Magento version 2.4.3-p1 with the [MDVA-44660](https://support.magento.com/hc/en-us/articles/7147867650445-MDVA-44660-Grave-accent-character-cannot-be-used-for-customer-s-name) patch applied

### Steps to reproduce

POST:/V1/customers
{
"customer": {
"email": "[OToole@joeperkins.com](mailto:OToole@joeperkins.com)",
"firstname": "O`Toole",
"lastname": "perkins",
"website_id": 1
}
}

### Expected result

200, Success

### Actual result

Status: 400, Response: {"message":"First Name is not valid!"}'

### Additional information

The [MDVA-44660](https://support.magento.com/hc/en-us/articles/7147867650445-MDVA-44660-Grave-accent-character-cannot-be-used-for-customer-s-name) patch claims in the title and description to allow the grave accent character [`] (&#96;) in the customer's name, however, it only fixes the right single quotation mark (&#8217;).

The original [issue](https://github.com/magento/magento2/issues/35469) related to the right single quotation mark (&#8217;) has been fixed in [MDVA-44660](https://support.magento.com/hc/en-us/articles/7147867650445-MDVA-44660-Grave-accent-character-cannot-be-used-for-customer-s-name), however, a new patch is needed to allow the grave accent character [`] (&#96;) in the customer's name.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @atIOCrON ,

I have tried to reproduce the issue in 2.4.3-p1 with MDVA-44660 patch but issue is not reproducible to me.
Please find screenshot for your reference:
**Created from API:**
![Screenshot from 2022-08-18 14-58-46](https://user-images.githubusercontent.com/60198022/185362894-62541afd-5899-4b86-a58f-0560b59322ad.png)
**Created from UI:**
![Screenshot from 2022-08-18 14-49-22](https://user-images.githubusercontent.com/60198022/185363101-0d82f225-4cc2-4369-bea7-c221f403d798.png)
**Verified in admin panel:**
![image](https://user-images.githubusercontent.com/60198022/185363674-d2e31133-047d-4fcd-8f63-c60c74d6e3b0.png)

KIndly provide more information so that issue can be reproducible to us.

Thanks

**Comment by engcom-Lima** [comment]
Hi @atIOCrON ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks
