### ISSUE TITLE
Bundle options decimal qty is rendered as an integer part only

### ISSUE THREAD

**Issue by say-my-name-user** [magento/magento2#35964]
### Preconditions and environment

- Magento version: CE 2.4.4

### Steps to reproduce

1. Create a bundle product
2. Allow "Qty Uses Decimals" in Advanced Inventory **for bundle options**
3. Buy this bundle product with decimal options Qty like 1.5
4. Check option Qty in the email / customer account / admin panel order details / invoice details / shipment details

### Expected result

Bundle options Qty must be rendered everywhere according to amount you bought, in our case **qty = 1.5**

### Actual result

Bundle options Qty is rendered only **as an integer part, qty = 1**

### Additional information

This happens due to using `sprintf('%d', $attributes['qty'])`, this `'%d'` makes it using only integer part.

Needs to be fixed at least in `\Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer`, `\Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer` and `\Magento\Bundle\Block\Sales\Order\Items\Renderer`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @say-my-name-user ,
Thank you for raising an issue , we tried to reproduce the issue on magento 2.4.4 instance , unfortunately we could not find step# 2 from Advanced inventory section. Kindly review the provided steps.

<img width="1339" alt="Screenshot 2022-08-22 at 5 23 54 PM" src="https://user-images.githubusercontent.com/51681379/185915601-c3f3922b-05b7-470d-ae05-b899191019f1.png">

<img width="1294" alt="Screenshot 2022-08-22 at 5 23 25 PM" src="https://user-images.githubusercontent.com/51681379/185915649-e4a88469-6e6d-4bd6-b876-c32e954e1a0a.png">

**Comment by say-my-name-user** [comment]
Hi @engcom-Delta,

you should check Advanced Inventory **in the bundle options product**, the simple product that is attached to the bundle, not bundle itself.

**Comment by engcom-Delta** [comment]
Hi @say-my-name-user ,
Sorry to come back to you again , unfortunately we could not find out such options on magento 2.4 develop instance.
Please find the attached video for reference  and correct me if i am wrong.

https://www.loom.com/share/e2d6ecbd46fa4ef48b07e9e2c4d5251c

**Comment by say-my-name-user** [comment]
Hi, you've got me wrong @engcom-Delta,

again, this option is NOT in the bundle product itself but in the SIMPLE product that bundle is consists of.

![Products - Inventory - Catalog - Magento Admin 2022-08-25 15-25-39](https://user-images.githubusercontent.com/17194260/186664221-0887c4ce-bb5b-4629-94f6-33365e35403a.png)
![Products - Inventory - Catalog - Magento Admin 2022-08-25 15-26-57](https://user-images.githubusercontent.com/17194260/186664241-3c25e33a-d63a-4e37-931e-9fe6488b49ae.png)

**Comment by engcom-Delta** [comment]
Hi @say-my-name-user ,
Thank you for providing more clear snapshots to understand the steps. We tried to reproduce the issue on Magento 2.4 develop instance , found that on Admin panel after placing an order quantity has been displayed as 1.5 only for order details section,invoiced section but after receiving an email , on order confirmation email it(quantity) has been showing as 1 instead of 1.5 . Hence issue has been confirmed.

Please find the attached video for reference and screenshots.

<img width="1440" alt="Screenshot 2022-08-25 at 8 05 52 PM" src="https://user-images.githubusercontent.com/51681379/186697069-314ce22c-c86d-42a2-a1c1-202a6ed30029.png">

<img width="1440" alt="Screenshot 2022-08-25 at 8 08 02 PM" src="https://user-images.githubusercontent.com/51681379/186697207-9edec2a9-076c-4d37-b47c-14ec2c05660f.png">
<img width="1093" alt="Screenshot 2022-08-25 at 8 08 38 PM" src="https://user-images.githubusercontent.com/51681379/186697261-922de68d-3967-4ed4-ac02-431234156e42.png">

https://www.loom.com/share/af78008d78ae46a5b453cda2f59c161a

**Comment by say-my-name-user** [comment]
Thank you @engcom-Delta ,

but you mentioned only "Qty" column where the number is correct but pay attention to the "Product" column on the order/invoice detailed page.

This columns has a bundle option title in the format like "qty x product_name" and qty is also incorrect there, "1 x Joust Duffle Bag" instead of "1.5 x Joust Duffle Bag".

The same issue is in the email option title.
