### ISSUE TITLE
Save cms block or page not possible

### ISSUE THREAD

**Issue by ghost** [magento/magento2#35975]
### Preconditions and environment

- Magento version 2.4.5
- Anything else that would help a developer reproduce the bug
Php 7.4

### Steps to reproduce

Edit cms page/block
Click on save button

### Expected result

Cms page/block saved

### Actual result

Cms page/block dont save and no error in logs

![image](https://user-images.githubusercontent.com/17496183/185434851-43d641c4-a729-4cdb-ac0c-1f46ca902214.png)

### Additional information

This issue begin after magento 2.4.4 to 2.4.5 upgrade.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by OleksandrZheleznyi** [comment]
@magento add to contributors team

**Comment by devchris79** [comment]
Magento 2.4.5 requires PHP 8.1 [see here](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html)

**Comment by engcom-Echo** [comment]
Hello @achatpc,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4.5 branch with Php 8.1, but for us, the issue is not reproducible.
followed [steps](https://github.com/magento/magento2/issues/35975#issue-1343279115).

Please find the attached screen for your reference.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/185616733-ac6199e4-3f0f-4ae1-b71f-5cdfb3d3f827.png">

Please check if i missed anything and kindly check on Magento 2.4.5 branch and provide more information with exact steps and screenshot so that we can reproduce this issue.

Thanks

**Comment by achatpc** [comment]
I have more information about issue.

When i disable PageBuilder, issue is solved.

But i need PageBuilder

**Comment by engcom-Echo** [comment]
Hello @achatpc,
Thanks for your quick response.

We have tried to reproduce the issue in Magento 2.4.5 branch with Php 8.1, but for us, the issue is not reproducible.
Note :- We have checked with PageBuilder Enable and we are able to save it successfully.

Please find the attached screen for your reference.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/185916963-65ff41f5-b2fb-4b7f-8e98-09ecb9bd7eed.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/185917265-34cf7ec1-2403-4332-9aca-b966242ad038.png">

Please check on Magento 2.4.5 branch and provide more information with exact steps and screenshot so that we can reproduce this issue.

Thanks

**Comment by achatpc** [comment]
Fixed, was related to conflict with header in pub/.htaccess:

Was "Header set X-Frame-Options CROSS-ORIGIN"
After change to
Header set X-Frame-Options SAMEORIGIN
Save block work again.
