### ISSUE TITLE
webapi salesOrderRepositoryV1 /V1/orders only returns a single order

### ISSUE THREAD

**Issue by DonatelloNguyen** [magento/magento2#3600]
GET /V1/orders api with the searchCriteria returns only a single order than a list of orders.

**Release:** 2.0.2 Community Version.  Installed from composer

**reproduction:**
1.) POST /magento/index.php/rest/V1/integration/admin/token. 
_Get the bearer token_

2.) GET /magento/index.php/rest/V1/orders?searchCriteria[filterGroups][0][filters][0][field]=status&searchCriteria[filterGroups][0][filters][0][value]=processing
_Use the bearer token from step 1 in this call_

**expect:** 
Multiple orders returned

**actual:** 
A single order is returned

**Comment by choukalos** [comment]
Hi @DonatelloNguyen how many orders did you have in the system with status = processing?  For the single order returned was that in the expected return set?  Was it either the first or the last order of status processing?  Creating internal issue (MAGETWO-50029) to address.

**Comment by DonatelloNguyen** [comment]
Hey @choukalos, I do not have that data anymore since I wipe it out to update w/ the new magento update.

This was set up on my dev box.  At the time it has ~6+ with status=processing.  The single order returned was from the expected set since I tested with other statuses as well.  As for the question whether it was the first or last order, I do not know; I'll update once I find out.

**Comment by DonatelloNguyen** [comment]
@choukalos , it grabs the first order.  I am basing this off from the order_id

**Comment by cpartica** [comment]
Cannot reproduce this, I created 3 orders: 2 processing one pending, each filter grabs it's corespondent number of items, see attached screenshots
Maybe we need some additional info to reproduce this since it might be a particular case when this happens. 
Maybe the installation had multiple views, or other cases

<img width="100%" alt="screen shot 2016-03-17 at 2 28 30 pm" src="https://cloud.githubusercontent.com/assets/11950741/13859633/69c343a0-ec52-11e5-814b-de55ee98995f.png">

Processing filter:
<img width="271" alt="screen shot 2016-03-17 at 2 33 53 pm" src="https://cloud.githubusercontent.com/assets/11950741/13859647/7a2c7892-ec52-11e5-9537-09f8d5159985.png">

Pending filter:
<img width="276" alt="screen shot 2016-03-17 at 2 34 17 pm" src="https://cloud.githubusercontent.com/assets/11950741/13859653/8003db52-ec52-11e5-891f-46a523c500e0.png">

The only problem found here is that search_criteria is null, so created internal bug MAGETWO-50606 for this

**Comment by DonatelloNguyen** [comment]
There must be some mistake on my end, it seems to work now, I'll reopen if I'm able to reproduce it.

**Comment by adnan-jamil** [comment]
I'm getting response

**Comment by adnan-jamil** [comment]
I'm getting below response{
  "message": "Consumer is not authorized to access %resources",
  "parameters": {
    "resources": "Magento_Sales::sales"
  }
}

**Comment by adnan-jamil** [comment]
@DonatelloNguyen, i'm getting this below response when try to get index.php/rest/V1/orders after getting token from this API index.php/rest/V1/integration/admin/token.

{
  "message": "Consumer is not authorized to access %resources",
  "parameters": {
    "resources": "Magento_Sales::sales"
  }
}

**Comment by zeeshan2523806** [comment]
@adnan-jamil you need to pass the authorization token in header form instead of a query parameters
![image](https://cloud.githubusercontent.com/assets/12829227/22174601/19a81bf6-e004-11e6-8484-a6816c465f7e.png)
