### ISSUE TITLE
Fixer IO API Endpoint changed

### ISSUE THREAD

**Issue by IbrahimS2** [magento/magento2#36010]
### Preconditions and environment

- Magento version: 2.4.5
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

> Simply if you now go to configure currency exchange using Fixer IO they will direct you to a new platform with a new API Endpoint https://apilayer.com/marketplace/fixer-api
> Admin - Stores - Currency Rates - Select - Fixex.io as Import service and click on Import

### Expected result

It imports currency rates successfully

### Actual result

The import is failing due to the new API keys only compatible with the new API Endpoint which must be updated/corrected from within M2

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence updating the description and confirming this issue.
![image](https://user-images.githubusercontent.com/60198231/198178550-428d833f-8cb9-4330-b782-d2d884f23f22.png)

**Comment by hostep** [comment]
Closed without any comments explaining why? Possibly fixed by [ACP2E-1044: Fixer.IO API doesn't work](https://github.com/magento/magento2/commit/dea1326481e1005e40b0ddf7d7e9db7fb3de0ff7)? Which seems to have introduced a new config field for a new API key.

**Comment by hostep** [comment]
If somebody's interested in the fix I mentioned above, here is a patch file that can be applied to the `magento/module-directory` composer package.

[ACP2E-1044-Directory.txt](https://github.com/magento/magento2/files/10342931/ACP2E-1044-Directory.txt)

I had to rework the code a bit and switch from `LaminasClient` to `ZendClient` because those `LaminasClient` classes haven't been released yet (they will probably be released in Magento 2.4.6 I'm guessing)

Patch was tested on Magento 2.4.3-p3 and should in theory also work on 2.4.4 and 2.4.5 (and maybe even on older versions).

After applying the patch, you'll find a new configuration section called "Fixer Api (APILayer)" in the Currency Setup that you'll need to configure:
<img width="1273" alt="Screenshot 2023-01-04 at 09 23 50" src="https://user-images.githubusercontent.com/85479/210526924-6b865a1c-f2ed-4f76-8a53-6fdc26536d7f.png">

**Comment by Viper9x** [comment]
The modified patch from @hostep worked as expected. Thanks @hostep :)
