### ISSUE TITLE
Magento 2 - Content > Page & Content > Block grids do not load on Chrome

### ISSUE THREAD

**Issue by loneregister** [magento/magento2#3601]
I am running chrome, and the magento content > page and content > block grids do not load in Chrome.  They do however, load on Firefox.  Screenshot attached of chrome page.
![missing-grid-chrome](https://cloud.githubusercontent.com/assets/6249947/13451953/607ac9fa-dff8-11e5-8a1f-400f7616a07b.png)

And - here is the very same site loaded in firefox.
![grid-ok-firefox](https://cloud.githubusercontent.com/assets/6249947/13451979/8e4aa120-dff8-11e5-90ff-4fec3ab017f3.jpg)

I inspected the page in chrome - and it does report an error stating:
Uncaught Error: You cannot apply bindings multiple times to the same element.
It states its in file: knockout.js line 2908

**Comment by anton-huz** [comment]
Hi Kevin,
On current moment I can suggest you to flush caches in your Chrome browser or open Private tab (`Ctrl+Shift+N`) and check again. We look closer on Chrome in Windows 10 in scope of regression testing.

Internally developers use Chrome on Win7/OS X without side issues.

**Comment by loneregister** [comment]
Thanks guz-anton - I did do the mentioned cache flushes etc..  And was able to prove that it worked on other browsers and not on chrome.  (per pictures).

However, now - many days later - when I access the magento 2 content sections via chrome it functions properly.

**Comment by loneregister** [comment]
Keep in mind, that I did wait several hours for the chrome "blank" page to refresh and it failed to do so.  All the while the other browsers worked with no problem.

**Comment by anton-huz** [comment]
@ LoneRegister thanks for patience.

**Comment by alextotal** [comment]
HI Kevin and Guz, I'm facing the same issue but it happens in chrome, firefox and edge. I can't see any CMS content nor products, on backend and the console is giving me this error: http://i.imgur.com/F8hYii6.png
Any ideas how can I find those files it says I'm missing or how can I solve it?

**Comment by loneregister** [comment]
At this point,I am not sure what the solution is/was.  Are you running the current version alextotal?

**Comment by romeof1980** [comment]
hi there,
the issue is present in Magento 2.1.2 too, across all major browsers.
Clearing Magento cache, CDN cache and redeploying static content don't solve the issue.
No errors appearing in the console by the way...

**Comment by alanmasic** [comment]
I am having the same issue with content>pages only its stuck in a loading loop. 
any fix for this?
![screen shot 2017-01-29 at 2 35 07 pm](https://cloud.githubusercontent.com/assets/17924022/22613879/4de2f5d6-ead0-11e6-9a3c-f6e22ed129d4.png)

**Comment by romeof1980** [comment]
Hi @strangerida,
for us it turned out to be a server issue. Are you using a shared-server?

romeo

---- On Sat, 04 Feb 2017 01:52:06 +0100 notifications@github.com wrote ----

I am having the same issue with content>pages only its stuck in a loading loop.
any fix for this?

**Comment by alanmasic** [comment]
@romeo1980 yes I am on a shared server. Is there anything I can do to fix this issue thru cpanel or FTP?

**Comment by romeof1980** [comment]
I will advise to change hosting company.
I've got no more issue since I switched to Nexcess SIP100. Very affordable, great assistance.
It was confirmed the problem was due to the shared solution hitting resources.

Cheers,
romeo

---- On Sat, 04 Feb 2017 12:40:59 +0100 notifications@github.com wrote ----

@romeo1980 yes I am on a shared server. Is there anything I can do to fix this issue thru cpanel or FTP?

**Comment by romeof1980** [comment]
hi @Strangerida ,
I just recall that before fixing the problem definitively (changing hosting solution as said in the previous comment) we had got to flush constantly also the CDN cache in order to get the page loading correctly. We did that many times per day.
Though, since we've switched to the new hosting solution (it's 1 month) we've not experienced that issue anymore. We've not changed any settings in the CDN (only the IP in the CNAME), so if there was a problem, was definitely hosting-related.
cheers!
