### ISSUE TITLE
Category Sort (position, name, price) behavior has changed in M2.4.5

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#36045]
### Preconditions and environment

Category Sort (position, name, price) behavior has changed in M2.4.5

The sorted order of products appearing in catalog category pages is controlled by the Sort By setting selected by the user from a drop down appearing in the upper right corner of the category page.

Previously the out-of-stock status of a product had no effect on the sort order, but as of update to M2.4.5 this appears to be working differently, out-of-stock items are not sorting in to the correct order regardless of setting.  Instead, starting with M2.4.5 the out-of-stock items are always listed at the end. 

### Steps to reproduce

This can be reproduced in a clean installition of M2.4.5 with the Luma data as follows...

(1) perform clean installtion of M2.4.5 with the Luma store data
(2) In frontend website navigate to Home > Gear > Watches, and observe that the position of Luma Analog Watch is appropriate and correct in the order of  products displayed for all Sort By selections.
(3) In admin backend Catalog > Product > Luma Analog Watch > Advanced Inventory, uncheck Use Config Settings and change Out-of-Stock Threshold value to be greater than current Qty, in this case value = 101, alternately change the current QTY value to zero (either method will cause same results) then Done and Save.
(4) in admin backend Stores > Configuration > Catalog > Inventory, uncheck Use System Value and change Display Out Of Stock Products value to Yes, then Save Config
(5) in admin backend Cache Management, Flush Magento Cache
(6) In frontend Home > Gear > Watches observe that the position of Luma Analog Watch is ALWAYS at the end of products displayed regardless of Sort By selection

### Expected result

Sort order of products displayed in catalog pages is not affected by their stock status.

### Actual result

Instead, starting with M2.4.5 the out-of-stock items are always listed at the end.    Previously the out-of-stock status of a product had no effect on the sort order, but as of update to M2.4.5 this is working differently, out-of-stock items are not sorting in to the correct order regardless of setting. 

### Additional information

There are plenty of 3rd party trivial extensions and patches that do this, but the M.2.4.5 Release Notes do not document this significant change in the sort behavior that greatly impacts the presentation order of products in categories on our website and our customers ability to find them.  There does not appear to be an admin method or setting to change this new behavior, at least not one I can find or that is documented in the M2.4.5 Release Notes. 

### Additional Information

In frontend website navigate to Home > Gear > Watches, and observe that the position of Luma Analog Watch is appropriate and correct in the order of products displayed for all Sort By selections.

<img width="755" alt="dj" src="https://user-images.githubusercontent.com/51680745/187387755-964bcbf0-2d21-4d5b-91b3-1585c1159cf4.png">

<img width="763" alt="dj 2" src="https://user-images.githubusercontent.com/51680745/187387817-9ab79e4d-7dc7-4365-b55a-b4a1ce2d4659.png">

<img width="739" alt="dj 3" src="https://user-images.githubusercontent.com/51680745/187387909-6513c47e-6b8c-4d6a-bfee-75ecf8f8fa98.png">

in admin backend Stores > Configuration > Catalog > Inventory, uncheck Use System Value and change Display Out Of Stock Products value to Yes, then Save Config.

<img width="925" alt="29" src="https://user-images.githubusercontent.com/51680745/187388470-fdfa8458-5d8f-4ab2-88d5-0f6a298c30ce.png">

In frontend Home > Gear > Watches observe that the position of Luma Analog Watch is ALWAYS at the end of products displayed regardless of Sort By selection

<img width="828" alt="30" src="https://user-images.githubusercontent.com/51680745/187388091-5252ea3a-b5e3-44fa-b666-79ba4ddc7d9d.png">

<img width="789" alt="31" src="https://user-images.githubusercontent.com/51680745/187388141-7add8bd9-fdfb-4ac8-a926-12a5142e7992.png">

<img width="764" alt="32" src="https://user-images.githubusercontent.com/51680745/187388193-7b044ec4-0c63-4058-83c7-3223590f74fd.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4.5 instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @n2diving-dgx,


Precondition:
• Magento 2.4-develop && 2.4.5
• PHP 8.1


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 project-community-edition as well but the issue is reproducible.

Kindly refer the screenshots.


1.In frontend website navigate to Home > Gear > Watches, and observe that the position of Luma Analog Watch is appropriate and correct in the order of products displayed for all Sort By selections.

<img width="755" alt="dj" src="https://user-images.githubusercontent.com/51680745/187197807-1132c038-c955-40da-bbdd-9c99d6d14a70.png">

<img width="763" alt="dj 2" src="https://user-images.githubusercontent.com/51680745/187197888-cf324660-9b69-4311-8cd7-e445d9140e3b.png">

<img width="739" alt="dj 3" src="https://user-images.githubusercontent.com/51680745/187197936-27f21eb9-94f1-4a33-a210-573438336202.png">


2. In admin backend Catalog > Product > Luma Analog Watch > Advanced Inventory, uncheck Use Config Settings and change Out-of-Stock Threshold value to be greater than current Qty, in this case value = 101, alternately change the current QTY value to zero (either method will cause same results) then Done and Save.


<img width="925" alt="28" src="https://user-images.githubusercontent.com/51680745/187198181-1ae64b5d-6c65-4404-b5fd-72e3675b3142.png">


3.in admin backend Stores > Configuration > Catalog > Inventory, uncheck Use System Value and change Display Out Of Stock Products value to Yes, then Save Config.

<img width="925" alt="29" src="https://user-images.githubusercontent.com/51680745/187198411-7197abdd-5f7b-4ad3-b699-4f757b840de8.png">


4.In frontend Home > Gear > Watches observe that the position of Luma Analog Watch is ALWAYS at the end of products displayed regardless of Sort By selection


<img width="828" alt="30" src="https://user-images.githubusercontent.com/51680745/187198549-20962ae1-e6eb-45af-af7d-f52396a68efd.png">










<img width="789" alt="31" src="https://user-images.githubusercontent.com/51680745/187198589-660b917e-916a-4c46-bf92-f9ebf732beb2.png">










<img width="764" alt="32" src="https://user-images.githubusercontent.com/51680745/187199596-72424829-050a-4a65-a221-3ad10b3b4b3a.png">




Products (out-of-stock items) are always listed at the end.


Hence Confirming this issue.


Thanks.

**Comment by Bashev** [comment]
Probably is a good idea to make a settings "Move out of stock products at the end" or something similar, to achieve both goals.

**Comment by pmonosolo** [comment]
Try this fix:
https://github.com/magento/inventory/issues/3360

**Comment by codebase-md** [comment]
Hi there,

this is happening due to a change in function `\Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::apply()`. In line 108 the function `getProductIdsBySaleability()` checks setting `cataloginventory/options/show_out_of_stock` and if enabled **and** you are on a category id is given(in other words you are on a category page) it calls the function `categoryProductByCustomSortOrder($categoryId)`(line 190) which resets the entire collections select statement and adds on line 213 a sort order for `is_salable` with hardcoded direction **DESC**. Additionally we found out that this function introduces another issue. It prevents custom sort orders to be applied due to the reset of the select statement. I created a patch which fixes this behavior(allows custom sorting an removes sorting by stock status):

```
Index: vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
--- a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php	
+++ b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php	(date 1662619604901)
@@ -210,20 +210,14 @@
         $storeId = $this->collection->getStoreId();
         $searchCriteria = $this->searchResult->getSearchCriteria();
         $sortOrders = $searchCriteria->getSortOrders() ?? [];
-        $sortOrders = array_merge(['is_salable' => \Magento\Framework\DB\Select::SQL_DESC], $sortOrders);
 
         $connection = $this->collection->getConnection();
-        $query = clone $connection->select()
+        $query = clone $this->collection->getSelect()
             ->reset(\Magento\Framework\DB\Select::ORDER)
             ->reset(\Magento\Framework\DB\Select::LIMIT_COUNT)
-            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET)
-            ->reset(\Magento\Framework\DB\Select::COLUMNS);
-        $query->from(
-            ['e' => $this->collection->getTable('catalog_product_entity')],
-            ['e.entity_id']
-        );
+            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET);
+
         $this->stockStatusApplier->setSearchResultApplier(true);
-        $query = $this->stockStatusFilter->execute($query, 'e', 'stockItem');
         $query->join(
             ['cat_index' => $this->collection->getTable('catalog_category_product_index_store' . $storeId)],
             'cat_index.product_id = e.entity_id'

```
I can't promise that it's the best solution but it solved the problem for now. Feedback welcome.

**Comment by pmonosolo** [comment]
> $storeId = $this->collection->getStoreId();
>          $searchCriteria = $this->searchResult->getSearchCriteria();
>          $sortOrders = $searchCriteria->getSortOrders() ?? [];
> -        $sortOrders = array_merge(['is_salable' => \Magento\Framework\DB\Select::SQL_DESC], $sortOrders);
>  
>          $connection = $this->collection->getConnection();
> -        $query = clone $connection->select()
> +        $query = clone $this->collection->getSelect()
>              ->reset(\Magento\Framework\DB\Select::ORDER)
>              ->reset(\Magento\Framework\DB\Select::LIMIT_COUNT)
> -            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET)
> -            ->reset(\Magento\Framework\DB\Select::COLUMNS);
> -        $query->from(
> -            ['e' => $this->collection->getTable('catalog_product_entity')],
> -            ['e.entity_id']
> -        );
> +            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET);
> +
>          $this->stockStatusApplier->setSearchResultApplier(true);
> -        $query = $this->stockStatusFilter->execute($query, 'e', 'stockItem');
>          $query->join(
>              ['cat_index' => $this->collection->getTable('catalog_category_product_index_store' . $storeId)],
>              'cat_index.product_id = e.entity_id'

This does not work for me unfortunately - the toolbar still shows the full catalog:

![image](https://user-images.githubusercontent.com/66754347/189217587-ea345d58-bccf-4cd0-b092-88435fddda5e.png)

It means that the whole catalog is being outputted regardless of the search query.

**Comment by codebase-md** [comment]
@pmonosolo
> > $storeId = $this->collection->getStoreId();
> > $searchCriteria = $this->searchResult->getSearchCriteria();
> > $sortOrders = $searchCriteria->getSortOrders() ?? [];
> > 
> > * ```
> >      $sortOrders = array_merge(['is_salable' => \Magento\Framework\DB\Select::SQL_DESC], $sortOrders);
> >   
> >      $connection = $this->collection->getConnection();
> >   ```
> > * ```
> >      $query = clone $connection->select()
> >   ```
> > 
> > 
> > * ```
> >      $query = clone $this->collection->getSelect()
> >          ->reset(\Magento\Framework\DB\Select::ORDER)
> >          ->reset(\Magento\Framework\DB\Select::LIMIT_COUNT)
> >   ```
> > 
> > 
> > * ```
> >          ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET)
> >   ```
> > * ```
> >          ->reset(\Magento\Framework\DB\Select::COLUMNS);
> >   ```
> > * ```
> >      $query->from(
> >   ```
> > * ```
> >          ['e' => $this->collection->getTable('catalog_product_entity')],
> >   ```
> > * ```
> >          ['e.entity_id']
> >   ```
> > * ```
> >      );
> >   ```
> > 
> > 
> > * ```
> >          ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET);
> >   ```
> > * ```
> >      $this->stockStatusApplier->setSearchResultApplier(true);
> >   ```
> > 
> > 
> > * ```
> >      $query = $this->stockStatusFilter->execute($query, 'e', 'stockItem');
> >      $query->join(
> >          ['cat_index' => $this->collection->getTable('catalog_category_product_index_store' . $storeId)],
> >          'cat_index.product_id = e.entity_id'
> >   ```
> 
> This does not work for me unfortunately - the toolbar still shows the full catalog:
> 
> ![image](https://user-images.githubusercontent.com/66754347/189217587-ea345d58-bccf-4cd0-b092-88435fddda5e.png)
> 
> It means that the whole catalog is being outputted regardless of the search query.

I'm sorry to hear that. But this patch is not intended to fix problems with the amount of products shown in your catalog. It is intended to fix the issue in regards to sort orders and position at which out of stock products are shown.

You might have a different issue here since I'm not able to reproduce the behavior described by you.
