### ISSUE TITLE
Can't place order for ordered qty less than 1 with guest checkout

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#36060]
### Preconditions and environment

- Magento Open Source Ver. 2.4.5

### Steps to reproduce

1. In admin backend Catalog > Product > Joust Duffle Bag > Advanced Inventory, change qty to 96.75,  Minimum Qty Allowed in Shopping Cart  to 0.5,  Qty Uses Decimals  to Yes
2. In frontend add  Joust Duffle Bag to cart with qty 0.5
3. Go to checkout and place order 

### Expected result

Place order success

### Actual result

Show error message "Some of the products are disabled."

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4.3 instance

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 project-community-edition as well but the issue is reproducible. Kindly refer the screenshots.


1.In admin backend Catalog > Product > Joust Duffle Bag > Advanced Inventory, change qty to 96.75, Minimum Qty Allowed in Shopping Cart to 0.5, Qty Uses Decimals to Yes



<img width="936" alt="150" src="https://user-images.githubusercontent.com/51680745/188806819-38c761c3-0457-4c3e-8b98-0608e2b175a5.png">







2.As a guest customer we are not able to place the order for a product.




<img width="926" alt="151" src="https://user-images.githubusercontent.com/51680745/188807113-4854a386-9492-46b8-af9e-c92b21679bf0.png">




Hence Confirming the issue.


Thanks.
