### ISSUE TITLE
Magento 2.4.5: CVE-2022-24086 and CVE-2022-24087 included?

### ISSUE THREAD

**Issue by kassner** [magento/magento2#36078]
### Preconditions and environment

- Magento 2.4.4
- Patch for CVE-2022-24086
- Patch for CVE-2022-24087

### Steps to reproduce

- Upgrade to Magento 2.4.5;
- Apply the CVE-2022-24086 and CVE-2022-24087 patches;

The patches conflict with newer changes in the Magento codebase.

### Expected result

Either:

1. Patches are applied successfully;

or

2. Patches are not needed, and the release notes have that information;

### Actual result

Unclear if patches are needed on 2.4.5, and if they do, patches should be compatible with the release.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @kassner ,
Thank you for reporting and collaboration.  CVE-2022-24086 and  CVE-2022-24087 are not included in Magento 2.4.5
Magento 2.4.5 release [notes](https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-5.html) does not contain any information about the mentioned patches as they are not included.  Please refer the [security updates](https://support.magento.com/hc/en-us/articles/4426353041293-Security-updates-available-for-Adobe-Commerce-APSB22-12) where the affected products and versions are mentioned here and find the solution [here](https://helpx.adobe.com/security/products/magento/apsb22-12.html)

**Comment by ihor-sviziev** [comment]
@sidolov @sdzhepa this looks like p0

**Comment by sdzhepa** [comment]
Hello @kassner and @ihor-sviziev 

I have discussed this issue with our Security Team.

**Short answer:**
1. Mentioned patches are not applicable for the 2.4.5. (_applicable only <= 2.4.3-p1 and <= 2.3.7-p2_)
2. Users do not need to apply these patches to fix security issues. Because these vulnerabilities were already fixed and included into 2.4.5

**Detailed answer**(quotes)

> 2.4.4, 2.4.3-p2, and 2.3.7-p3 were the first releases after that hotfix was released, not 2.4.5. Those release notes do mention that it was addressed in those releases https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-4.html#hotfixes-included-in-this-release: 
>  
>> •	The vulnerability addressed by MDVA-43395_EE_2.4.3-p1_COMPOSER_v1.patch and MDVA-43443_EE_2.4.3-p1_COMPOSER_v1.patch has been resolved in this release.
>
> We don’t include information about all hotfixes from previous releases, only the ones that affect the immediate release.
> So maybe the confusion was that 2.4.5 isn’t the first release since those listed hotfixes.
>  
> To summarize, the issue was addressed in 2.4.4, 2.4.3-p2, and 2.3.7-p3 and was available as hotfix patches before that. Important to note that the patches are not the same fix as what we released in the full releases. We opted for a more comprehensive solution than what the hotfix provided.


I hope this information will clarify the situation and we can close this issue but would like to receive your confirmation before.

cc: @engcom-Hotel @engcom-November

**Comment by peterjaap** [comment]
@sdzhepa still curious to know how it is fixed in 2.4.4 then. Since the patch _can_ still be applied on 2.4.4, even though it is not meant for that version. That would mean the code hasn't changed, otherwise the patch application would fail. So how is it fixed?

**Comment by hostep** [comment]
@nathanjosiah: can adobe publish some kind of post-mortem about this, too many people are confused about this.

**Comment by nathanjosiah** [comment]
We cannot discuss the details of vulnerability fixes. The patch may be able to be applied to version it is not meant for but that doesn't mean it isn't fixed. 

As an abstract example:

```
function process() {
  //some broken method
  $foo = $thing->getResult();

  //hack fix
  return preg_replace(...,...,$foo);
}
```

In this example, the temporary fix was in the "hack fix" but the bug was in the `getResult`. Which means a proper fix wouldn't have the hack fix and not affect that line.

If you think that you have found a vulnerability in one of our current versions, please report it through HackerOne.

**Comment by peterjaap** [comment]
@nathanjosiah ok thanks for clearing that up. Just wanted to be sure the vuln was fixed in 2.4.4.

**Comment by engcom-November** [comment]
Hi @pemann  ,
As mentioned by @sdzhepa , mentioned patches are applicable only for Magento instances <= 2.4.3-p1 and <= 2.3.7-p2. The issue was addressed in 2.4.4, 2.4.3-p2, and 2.3.7-p3 and was available as hotfix patches before that. Kindly confirm if you have found a vulnerability in latest magento instance with steps to confirm or we can close the issue.
Thank you.

**Comment by nathanjosiah** [comment]
@engcom-November Please do not direct the community to post vulnerability steps in public github. @pemann if you have a vulnerability please submit it through our HackerOne program or message me directly in the community slack.

**Comment by engcom-November** [comment]
Thank you for the update @nathanjosiah. We are closing this issue as the mentioned patches are not applicable for Magento 2.4.5
Thank you.
