### ISSUE TITLE
It's time to change your password.

### ISSUE THREAD

**Issue by sandip9909** [magento/magento2#36087]
![Screenshot (48)](https://user-images.githubusercontent.com/106960671/188564178-a0bc9385-ad61-4688-8b31-4e75a0385bb8.png)

### Proposed solution

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
You will need to share your Magento version and PHP version.
Also the screenshot displays your custom admin path, so you may want to change that.

**Comment by sandip9909** [comment]
Magento ver. 2.3.4

**Comment by devchris79** [comment]
I would check your error logs.
The password change also sends an email within the try function, so it may be a problem with emails.

**Comment by engcom-Hotel** [comment]
Hello @sandip9909,

Thanks for posting the issue!

We request you to please go through with the guidelines [here](https://developer.adobe.com/commerce/contributor/guides/code-contributions/#report-an-issue) in order to report an issue. This will help us move forward with this ticket. Also, you need to provide us with the following information:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by engcom-Hotel** [comment]
Dear @sandip9909,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by sandip9909** [comment]
close
