### ISSUE TITLE
Newrelic GraphQl transaction names not working

### ISSUE THREAD

**Issue by carolien-betersport** [magento/magento2#36112]
### Preconditions and environment

- Magento version: 2.4.4, 2.4.4-p1 and 2.4.5
- Original issue: #30915

### Steps to reproduce

1. Sign up and setup New Relic account 
2. Enable cron
3. Disable New Relic reporting from Magento Admin. (Stores - Configuration - General - New Relic reporting)
5. Make some GraphQl request while connected to NewRelic
6. Reindex and clear cache
7. Navigate to New Relic Account - APM & Services - PHP Application - Verify Transaction Names

### Expected result

Queries are shown as `/GraphQL-queryname`

### Actual result

Transaction name is still `/FrontController/Magento\GraphQl\Controller\GraphQl\Interceptor`
Transaction name is displayed as unknown
There is no issue with CLI and Cron jobs. Transaction names are displayed as expected for reindexing and cron job operations.
But for graphql operations / requests made, Transaction names are not getting displayed.

### Additional information

I looked at the commits done for the original issue and it was fixed there, but during a merge some of the work got lost.
As far as I can see the commit that was lost is: https://github.com/magento/magento2/commit/b0131a276cb34bd928da996658b4110ec1188863 which contains the naming of the transactions.

When I add the changes from this commit to my installation the names are working as expected.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by convenient** [comment]
Thanks for getting here @arko-betersport 

This is the EXACT same issue as i described on https://github.com/magento/magento2/issues/30915

The magento solution to that issue was to set the new relic transaction name only when `newrelicreporting/general/enable` is configured in the database.

https://github.com/magento/magento2/blob/28c7f79f4d74564ba880e35e59ea45b896437ca7/app/code/Magento/GraphQl/Model/Query/Logger/NewRelic.php#L42-L55

This is madness because so many other transactions are properly named without integrating with this module
- `Cron Job` entries are named
- Rest API controllers
- Standard frontend controllers

Having to enable the magento module to get visibility on the transaction when all I care about is the APM for these requests is less than ideal.

I am composer patching this in https://github.com/magento/magento2/pull/36436

**Comment by convenient** [comment]
Hey @engcom-November I've added some detailed notes to reproduce the issue on https://github.com/magento/magento2/pull/36436

**Comment by engcom-November** [comment]
Hi @arko-betersport ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with below steps performed:
**Steps performed:**
1. Setup new [Relic account](https://newrelic.com/)
2. Enabled Cron for Magento 2.4-develop instance
3. Configured New Relic with Magento. (Stores - Configuration - General - New Relic Reporting)
4. Reindex and clear cache
5. Made few GraphQL requests using Altair GraphQl client
6. Verified New relic account - Apm and services - PHP Application_graphql - Transactions - **No issue. Transaction names are displayed as expected** Kindly refer the screenshots for the same.
![image](https://user-images.githubusercontent.com/60198231/204735086-723cf98e-1b45-4af5-81b8-2f9097a812e4.png)
![image](https://user-images.githubusercontent.com/60198231/204735140-35862c12-8edd-4e64-9b67-7d43b185e7b3.png)
Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by convenient** [comment]
@engcom-November can you confirm that the Magento store configuration for new relic is disabled?

**Comment by convenient** [comment]
If you look at the breakdown of transaction names  on my pull request here #36436 you will see that graphql is the only one that requires you to have enabled the Magento module in store configuration.

Everything else only requires the PHP.ini configured

**Comment by convenient** [comment]
> If I disable New Relic reporting from Magento Admin configuration, no data is no data is displayed for Graphql operations performed.

I don't understand. That is the issue as I report it.  When new relic is enabled at the php level, but the Magento module is disabled, we do not get new relic transaction names (but we get all other transaction names)

See my description above where I detail where each type of transaction is configured. Graphql is the only one requiring the magento module to he enabled.

**Comment by engcom-November** [comment]
Thank you for the response @arko-betersport . Verified the behavior again on PHP Application APM & Services by disabling New Relic reporting from Magento admin and the issue is reproducible for Graphql requests.
For CLI operations (Ex: reindex) - Transaction names are displayed as expected.
Cron job transaction names displayed as expected.
For the Graphql operations / requests made, Transaction name is displayed as Unknown. Hence updating the description and confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/206391693-7f23bb36-8f36-487b-9aa6-3fb5ba4575a1.png)
![image](https://user-images.githubusercontent.com/60198231/206391743-57bc50d2-e47c-44d2-b3b8-d5a6308c65bd.png)
![image](https://user-images.githubusercontent.com/60198231/206391860-8e4ec2e6-114c-402a-b00e-be430f8ed3f4.png)
