### ISSUE TITLE
typo error on a js file.

### ISSUE THREAD

**Issue by Oscarvaz96** [magento/magento2#36163]
### Summary (*)

On Magento 2.3.5 there is a typo error right here:
vendor/magento/module-catalog/view/frontend/web/js/product/storage/storage-service.js
line 120:
 /**
             * Subscribers list
             */
            subsctibers = {};
this object  subsctibers = {}; is used in further parts of this js with that same name, which is a typo.

### Examples (*)

line 191
processSubscribers: function (initialized, config) {
                if (subsctibers[config.namespace]) {
                    _.each(subsctibers[config.namespace], function (callback) {
                        callback(initialized);
                    });

                    delete subsctibers[config.namespace];
                }
            },

### Proposed solution

It should be replaced by subscribers
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sandy6666** [comment]
@magento i am working on this

**Comment by engcom-Delta** [comment]
Hi @Oscarvaz96 

Thanks for the contribution!

we have tried to reproduce the issue in Magento 2.4-develop branch. And the issue is reproducible for us.
we haved checked the storage-service.js file as mentioned above lines and in other places. we found the typo error. 

<img width="454" alt="Screenshot 2022-09-26 at 6 24 15 PM" src="https://user-images.githubusercontent.com/51681379/192281856-dd248c40-3ae5-4db7-8359-6c88b97b05e1.png">

<img width="1005" alt="Screenshot 2022-09-26 at 6 24 32 PM" src="https://user-images.githubusercontent.com/51681379/192281885-c1717eb8-efac-427d-b467-0bdfdbfba5fb.png">

<img width="673" alt="Screenshot 2022-09-26 at 6 27 36 PM" src="https://user-images.githubusercontent.com/51681379/192282423-c857c57b-c44e-47ac-81a8-060e00c7aa8b.png">

Hence confirming the issue.

Thanks.
