### ISSUE TITLE
Mage error component is duplicating error warnings on form inputs

### ISSUE THREAD

**Issue by Rueff19** [magento/magento2#36201]
### Preconditions and environment

- Magento 2.4.5
- The error can be reproduced in any form (ex: login form)

### Steps to reproduce

1. Submit blank login form;
2. Fill the email input and submit again;
3. Remove the email and submit blank form again;
4. Click one more time on submit button.

### Expected result

There should only be one error warning.

### Actual result

Two error warnings appear.

![image](https://user-images.githubusercontent.com/19212914/192284155-c62d53d8-ff60-4f44-a5ac-f3997635a3ec.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Rueff19,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances
Kindly refer screenshot.


<img width="635" alt="Screenshot 2022-09-27 at 6 19 32 PM" src="https://user-images.githubusercontent.com/51680745/192530833-f62ffcba-463a-4640-9a93-49fc56d88eea.png">


Steps to reproduce
1.Submit blank login form;
2.Fill the email input and submit again;
3.Remove the email and submit blank form again;
4.Click one more time on submit button.



Hence confirming the issue.


Thanks.

**Comment by kedangghet** [comment]
@engcom-Bravo Seem this fixed not correct, it will create a duplicate error element every validate

The problem occurs when we remove `aria-describedby` when input validate, it breaks the logic of **jQuery Validation Plugin**.
we should remove `removeAttr('aria-describedby')` on this code block

https://github.com/magento/magento2/blob/0fe805f90119dbef44156e7641eb903ce9e837d9/lib/web/mage/validation.js#L1981C12-L1987C14
![image](https://github.com/magento/magento2/assets/4742613/f40f6687-847a-4d4c-b919-542586303751)
