### ISSUE TITLE
Stale links to topics migrated to Adobe domains

### ISSUE THREAD

**Issue by Tomasito665** [magento/magento2#36230]
### Summary (*)
Adobe migrated Magento documentation to Adobe domains.
https://devdocs.magento.com/migrated.html

### Examples (*)
The pull request description template itself is a clear example:

```
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
```

The link points to https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog, which was moved to https://developer.adobe.com/commerce/contributor/guides/code-contributions/#community-backlog-priority.

### Proposed solution
The solution is simple enough: update the links :-)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sdzhepa** [comment]
Hello @Tomasito665 

Could you please be more specific or provide more details about where exact wrong links?
In the description, you provided an example for the pull request but PR template does not have a section for Severity

Template in use: https://github.com/magento/magento2/blob/2.4-develop/.github/PULL_REQUEST_TEMPLATE.md

For issues, all templates can be found https://github.com/magento/magento2/tree/2.4-develop/.github/ISSUE_TEMPLATE

1. [bug_report.yaml](https://github.com/magento/magento2/blob/2.4-develop/.github/ISSUE_TEMPLATE/bug_report.yaml) - has correct(updated) link for severity  [bug_report.yaml#L65](https://github.com/magento/magento2/blame/2.4-develop/.github/ISSUE_TEMPLATE/bug_report.yaml#L65)
2. [developer-experience-issue.md](https://github.com/magento/magento2/blob/2.4-develop/.github/ISSUE_TEMPLATE/developer-experience-issue.md) has wrong link [developer-experience-issue.md#L23](https://github.com/magento/magento2/blame/2.4-develop/.github/ISSUE_TEMPLATE/developer-experience-issue.md#L23) **BUT it is fixed in** this PR https://github.com/magento/magento2/pull/35990
3. [feature_request.md](https://github.com/magento/magento2/blob/2.4-develop/.github/ISSUE_TEMPLATE/feature_request.md) - does not have this section for Severity
4. [story.md](https://github.com/magento/magento2/blob/2.4-develop/.github/ISSUE_TEMPLATE/story.md) - does not have this section for Severity


Noteі: 
- old links could be only in the old issues(that were created/reported before changes). I think(imho) the effort and time required to update all old issues does not worth the result
- all newly reported issues should have correct links

**Comment by Tomasito665** [comment]
Hello @sdzhepa,

Thanks for coming back to me. If you click [New issue](https://github.com/magento/magento2/issues/new/choose) → [Developer experience issue](https://github.com/magento/magento2/issues/new?assignees=&labels=Triage%3A+Dev.Experience&template=developer-experience-issue.md), the template still contains the old links. Many links on other documentation are also old, including some links on the main README. A few examples:

- https://github.com/magento/magento2/blob/2.4-develop/.github/ISSUE_TEMPLATE/developer-experience-issue.md?plain=1#L23
- https://github.com/magento/magento2/blob/2.4-develop/README.md?plain=1#L18-L21
- https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/README.md?plain=1#L28
- https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Email/README.md?plain=1#L37-L40

For more examples, search for `https://docs.magento.com` in this repository:
https://github.com/magento/magento2/search?q=https%3A%2F%2Fdocs.magento.com

> old links could be only in the old issues(that were created/reported before changes). I think(imho) the effort and time required to update all old issues does not worth the result

I agree.

**Comment by engcom-November** [comment]
Hi @Tomasito665 ,
Thank you for reporting and collaboration. I believe updates/modifications to devdocs should be reported in this [repository](https://github.com/magento/devdocs/). Hence raised new issue report for the same: https://github.com/magento/devdocs/issues/9523 . Kindly check and move on this issue for latest updates / solutions on the same.
Thank you.

**Comment by Tomasito665** [comment]
Hi @engcom-November,

I filed a pull request to update all links to migrated documentation to their updated URLs. It has been two days since I filed the PR and yet CI checks appear in progress still. How long do they normally take? Am I missing something?

Thanks

**Comment by engcom-November** [comment]
Hi @Tomasito665 ,
Thank you for the response. The [issue](https://github.com/magento/devdocs/issues/9523) raised by me in [devdocs]([repository](https://github.com/magento/devdocs/)) repository has been closed.
Reason: They are currently working on updating the navigation on the devdocs home page to point to new locations and will not implement redirects on devdocs until they finish migrating all content. Kindly check this  https://community.magento.com/t5/News-Announcements/Community-Monthly-Update-February-2022/td-p/492851#toc-hId-828475519 for more information.
Thank you.

**Comment by Tomasito665** [comment]
Hi @engcom-November,

Thanks for your response. The issue you describe is about building in redirects from the old to the new URLs, which is related but different than the issue described in this issue. In this issue, I refer to the URLs in this repository, magento2, which point to the old URLs. The pull request I opened updates all links to their new locations, removing the need to redirect at all. Because of that, I would like to reopen the issue until the pull request is closed. Could you do that?

Thank you!
