### ISSUE TITLE
npm audit critical vulnerabilities

### ISSUE THREAD

**Issue by bramvanderholst** [magento/magento2#36254]
### Preconditions and environment

Magento version 2.4.x (and, as the relevant package is unchanged in 2.5 dev, probably also in 2.5)

### Steps to reproduce

1. Make sure the package.json is up to date with https://github.com/magento/magento2/blob/2.4-develop/package.json.sample
2. run `npm i`

### Expected result

No (critical) vulnerabilities in npm dependencies

### Actual result

2 critical vulnerabilities, both coming from grunt-styledocco@0.3.0

minimist < 1.2.6: https://github.com/advisories/GHSA-xvch-5gv4-984h
```
├─┬ grunt-styledocco@0.3.0
│ └─┬ styledocco@0.6.6
│   └─┬ optimist@0.6.1
│     └── minimist@0.0.10
```

uglify-js < 2.4.24: https://github.com/advisories/GHSA-34r7-q49f-h37c
```
├─┬ grunt-styledocco@0.3.0
│ └─┬ styledocco@0.6.6
│   └── uglify-js@1.2.6
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @bramvanderholst,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

package.json is up to date


<img width="502" alt="Screenshot 2022-12-19 at 4 54 26 PM" src="https://user-images.githubusercontent.com/51680745/208430406-9f49770a-3a4f-4ca6-92e9-2ad2543da025.png">




After running `npm i` we got below Warnings.

<img width="1461" alt="Screenshot 2022-12-19 at 4 42 13 PM" src="https://user-images.githubusercontent.com/51680745/208430610-a56d9f8f-ec51-4b5f-9f3e-c52a4015ee8b.png">


Please let us know if we are missing any thing.


Thanks.

**Comment by bramvanderholst** [comment]
At the end of the `npm i` output, it shows the following. (Not sure where the third critical is suddenly coming from..)
![Screenshot 2022-12-19 at 15 36 59](https://user-images.githubusercontent.com/7457340/208450195-3b317461-ec58-4bb9-a3bc-46083b1b1bca.png)
As the output suggests, run `npm audit` for more details. 
I can also recommend the following package for a more detailed overview: https://www.npmjs.com/package/better-npm-audit

**Comment by engcom-Bravo** [comment]
Hi @bramvanderholst,

Thanks for your Update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Make sure the package.json is up to date with https://github.com/magento/magento2/blob/2.4-develop/package.json.sample
2.run npm i


<img width="502" alt="Screenshot 2022-12-19 at 4 54 26 PM" src="https://user-images.githubusercontent.com/51680745/208622811-d6ef5fba-cf47-45fb-8b31-851e59b7fe24.png">


3 critical vulnerabilities

<img width="666" alt="Screenshot 2022-12-20 at 11 07 31 AM" src="https://user-images.githubusercontent.com/51680745/208622856-8bbf24ff-fadf-4ad8-98a4-29beeeae1280.png">



Hence confirming this issue.

Thanks.

**Comment by rostilos** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7499 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-7499&type=commits

Thanks.
