### ISSUE TITLE
Undefined value sets in the variant's sku

### ISSUE THREAD

**Issue by Dhaval410** [magento/magento2#36309]
### Preconditions and environment

- Magento version: 2.4.5
- Add sample data by using this command _bin/magento sampledata:deploy_

### Steps to reproduce

1. Go to the Stores menu -> select 'Attribute set' under the Attributes section.
2. Select any one attribute set from the list and it will open.
3. Move any group to the top above the 'Product Details' group in the group section like in the below image.
![Bag-Attribute-Sets-Attributes-Stores-Magento-Admin](https://user-images.githubusercontent.com/59201168/195338817-23ce8814-1420-4d4c-8934-2cb08965775d.png)

4. Open any product from that attribute set in which you move the group (In my case I have taken one product as marked in the below image where the attribute set is 'Bag').
![Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/59201168/195339648-dd2ab618-a432-4809-92ba-1c1d78fe4460.png)

5. Now go to the 'Configurations' tab and create a simple product by clicking the 'Create Configurations' as in the below image.
![Joust-Duffle-Bag-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/59201168/195341024-9c12b5b1-039e-4015-ad13-b2574180a121.png)

6. Now follow the steps mentioned below:
- **Step 1:** Select Attributes - select any attribute from the list and click next.
- **Step 2:** Attribute Values - Select options and click on the next.
- **Step 3:** Bulk Images, Price, and Quantity - Don't do anything and click on the next.
- **Step 4:** Summary - you can see the grid of the products you are about to create. But in the 'SKU' column, you can see it sets the undefined text instead of the parent SKU's text as in the below image.

![Variant-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/59201168/195344784-fb2b05b8-78ee-4e46-8096-e075e4d743ae.png)

### Expected result

when we create variants of the product while the other tab is on the top above the 'Product Details', it should create variants with the proper SKU names like in the image.
![Correct-Variant-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/59201168/195345763-3b597bad-29cb-49b9-bf4c-a22d0a8417cd.png)

### Actual result

It sets the undefined value to the SKU as shown in step 6 of Steps to reproduce.

### Additional information

As I checked the file -
> _**/vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/steps/summary.js**_

in this file, there is a function name '**calculate()**' at line 93 as in image.

![summary-file-calculate](https://user-images.githubusercontent.com/59201168/195579068-62ae3c55-ea99-4d7b-a850-945970b49f1f.png)

In this function getting productSku by calling function **getProductValue()** with passing argument 'sku'. This function is defined in the file -

> _**/vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/variations.js**_

at line 132 as in the image.

![variation-file-getProductValue](https://user-images.githubusercontent.com/59201168/195580462-7adca7f1-4678-4b98-b4ca-313ce04a6be1.png)

in the getProductValue() function, there is a code to get the value of the SKU at line 135. Here, if the 'Product Details' tab is not open by default in the product edit page in the admin then it can't able to get the value for the SKU. Because if the 'Product Details' tab is not opened then their elements don't load.

By default, the first tab will be open. So, if we add another tab to the top above the 'Product Details' tab then this tab will collapse (not open) by default. And the elements of this tab will not load. And we will get the undefined text instead of the proper SKU name for the variants. The same thing happens with the product name also.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Dhaval410,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances.We are getting Undefined value sets in the variant's sku. Kindly refer the screenshots.


Steps to reproduce:

1.Go to the Stores menu -> select 'Attribute set' under the Attributes section.

2.Select any one attribute set from the list and it will open.

3.Move any group to the top above the 'Product Details' group in the group section like in the below image.

4.Open any product from that attribute set in which you move the group

5.Now go to the 'Configurations' tab and create a simple product by clicking the 'Create Configurations' as in the below image.

6.Now follow the steps mentioned below:

Step 1: Select Attributes - select any attribute from the list and click next.
Step 2: Attribute Values - Select options and click on the next.
Step 3: Bulk Images, Price, and Quantity - Don't do anything and click on the next.
Step 4: Summary - you can see the grid of the products you are about to create. But in the 'SKU' column, you can see it sets the undefined text instead of the parent SKU's text as in the below image.



<img width="1331" alt="Screenshot 2022-10-17 at 3 49 08 PM" src="https://user-images.githubusercontent.com/51680745/196161234-79bc50eb-6525-453a-b362-cd6d34f77088.png">




<img width="1369" alt="Screenshot 2022-10-17 at 3 50 48 PM" src="https://user-images.githubusercontent.com/51680745/196161302-438651e6-2138-48ee-a5ad-abf19f9f7c8e.png">




<img width="1373" alt="Screenshot 2022-10-17 at 3 52 02 PM" src="https://user-images.githubusercontent.com/51680745/196161797-8440a49e-5ba4-4ad9-a7ba-f0647cb544b6.png">




<img width="1299" alt="Screenshot 2022-10-17 at 3 53 01 PM" src="https://user-images.githubusercontent.com/51680745/196161829-3d4b8987-bb3c-4772-9841-6042e53b775d.png">




Hence Confirming the issue.


Thanks.
