### ISSUE TITLE
bin/magento setup:upgrade error when use composer install --no-dev

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#36351]
### Preconditions and environment

- 2.4-develop with sample data.

### Steps to reproduce

1.  Disable Sample data using command : `bin/magento module:disable Magento_SampleData`
2. Run `composer install --no-dev`
3. Run `bin/magento indexer:reindex`
4. Check the debug log.

### Expected result

No error

### Actual result

Error: There is an error in /var/www/html/magento2/lib/internal/Magento/Framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php at line: 143
Call to undefined function Magento\Framework\Api\SearchCriteria\CollectionProcessor\array_first()

### Additional information

- Function array_first is declared in composer dev package weew/helpers-array.
- In production environment, I think no need install composer dev packages, so the code should not depend on these packages.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nadroj467** [comment]
@magento give me 2.4.5 instance

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop and the issue is not reproducible.Kindly refer screenshots.



<img width="871" alt="Screenshot 2022-10-25 at 4 08 38 PM" src="https://user-images.githubusercontent.com/51680745/197777488-ffad3f3b-cd6b-4725-8e69-e92624920d27.png">



<img width="780" alt="Screenshot 2022-10-25 at 4 10 04 PM" src="https://user-images.githubusercontent.com/51680745/197777622-9847173a-2f03-4b75-ad52-c823fea5589f.png">





<img width="749" alt="Screenshot 2022-10-25 at 4 10 17 PM" src="https://user-images.githubusercontent.com/51680745/197777672-96c4c0b4-227b-4c3a-a37a-f888a59f21f0.png">



Kindly recheck the issue on Magento 2.4-develop instance and Please let us know we miss anything.


Thanks.

**Comment by rogerdz** [comment]
Hi @engcom-Bravo, issue still reproducible with lastest code in 2.4-develop.
Please check video https://www.loom.com/share/39b34193380e44c3a8f42641df527feb

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,


Thanks for update.

Verified the issue on Magento 2.4-develop and the issue is not reproducible.Kindly refer screenshots.


<img width="871" alt="Screenshot 2022-10-25 at 4 08 38 PM" src="https://user-images.githubusercontent.com/51680745/198028784-93387cb2-f4ca-4245-ba35-23709e08e6f6.png">




<img width="1190" alt="Screenshot 2022-10-26 at 2 45 22 PM" src="https://user-images.githubusercontent.com/51680745/198028847-d363b867-669c-40c5-8868-b6f9600b0282.png">




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by rogerdz** [comment]
Hi @engcom-Bravo, thank you for your response.
I checked again and found that the cause is Magento_ConfigurableSampleData module.
So I disabled all sample data module and found to be able to reproduce the error by running the command php bin/magento indexer:reindex.
![2022-10-27_22-18](https://user-images.githubusercontent.com/78783748/198330376-58ce7e51-6e28-480e-b30b-1a555b12685b.png)

**Comment by Den4ik** [comment]
@engcom-Bravo I'm agree that use of native php functions in core code is more correct

**Comment by monteshot** [comment]
@magento I am working on this
