### ISSUE TITLE
Layered Navigation with configurable product (maybe stock problem)

### ISSUE THREAD

**Issue by mbattistini** [magento/magento2#36364]
1. Magento 2.4.5-p1,Magento 2.4 develop
2. PHP 8.1
3. Create Configurable with Length and Width Product Attributes.

### Steps to reproduce

1. Insert this products:

![products](https://user-images.githubusercontent.com/29307582/27280140-2dc3d60e-54e7-11e7-8212-f626fdab0097.png)

### Expected result (*)

1. Only configurable product A is visible

### Actual result (*)

1. Both configurable product A and B are visible. So if the customer clicks on the product B does not find the desired combination.

---

**I keep having the same problem, maybe it has to do with stock.
After selection, products displayed with selected attributes are displayed even if "out of stock".**

_Originally posted by @mbattistini in https://github.com/magento/magento2/issues/9980#issuecomment-1289274266_

**Comment by mbattistini** [comment]
I edited the first post by adding the details!

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @mbattistini,


Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances.Kindly refer the screenshots.


<img width="1367" alt="Screenshot 2022-10-27 at 1 57 48 PM" src="https://user-images.githubusercontent.com/51680745/198284664-e226db1a-bcd1-4a77-bb8d-1e0132365361.png">



<img width="1394" alt="Screenshot 2022-10-27 at 1 57 57 PM" src="https://user-images.githubusercontent.com/51680745/198284715-4b9632f8-5d0a-4af1-9178-4b7466b9c5c6.png">




<img width="1400" alt="Screenshot 2022-10-27 at 1 58 05 PM" src="https://user-images.githubusercontent.com/51680745/198284753-cccff5b2-4653-4127-9ab1-220e7f306289.png">



When we applying Filters with Length 5 and Width 6 only Product A should be visible.Both Product A and Product are visible here.

<img width="1323" alt="Screenshot 2022-10-27 at 2 10 24 PM" src="https://user-images.githubusercontent.com/51680745/198284789-4ff93b56-df20-439b-b281-c549102a3a22.png">



Hence confirming the issue.


Thanks.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by abukatar** [comment]
@magento I am working on this

**Comment by abukatar** [comment]
The requested functionality is not supported by the current Adobe Commerce architecture. Due to the complexity of the implementation, this won't be in the scope of a quick fix. Instead, this has been converted into a story and will be worked out accordingly. Unfortunately, we are unable to provide an ETA on when a solution would be available. Once this is implemented, the corresponding details will be communicated in the release notes.

**Comment by abukatar** [comment]
Hi @cedric-jeeper, currently, the search engine stores data for all types of composite products in a way that the information about the variations is flattened, and the links to available combinations are lost.

For example, Product B is indexed with the

`"length_value": ["5","6"]`

and

` "width_value": ["6","7"]`

without any links to available combinations which are [L:5,W:7] and [L:6,W:6]

Hence, when we search for the combination L:5,W:6, the engine simply retrieves documents that have a match in the indexed attribute values.

I hope this helps.

**Comment by abukatar** [comment]
It's about how to create the OpenSearch index in a way that this case will be supported
