### ISSUE TITLE
Error when trying to subscribe email to newsletter on integration

### ISSUE THREAD

**Issue by Beagon** [magento/magento2#36366]
### Preconditions and environment

- 2.4.5-p1 (And lower)
- Set an integration token in your GraphQL request

### Steps to reproduce

1. Create an integration token
2. Send integration token as bearer with GraphQL request to subscribe an email to the newsletter `mutation ($email: String!) {
    subscribeEmailToNewsletter(email: $email) {
        status
    }
}
`
4. Get error: "Cannot create a newsletter subscription"

### Expected result

{
	"data": {
		"subscribeEmailToNewsletter": {
			"status": "SUBSCRIBED"
		}
	}
}

### Actual result

main.ERROR: No such entity with customerId = 36 [] []
main.ERROR: Cannot create a newsletter subscription.

### Additional information

This issue is because the GraphQL resolver uses the context user ID without checking the type.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by aliraza512** [comment]
Need a instance of fresh Magento2 latest version.

**Comment by aliraza512** [comment]
@magento give me magento2.4.5-p1 instant please

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Beagon,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.Kindly refer screemshots.


<img width="1350" alt="Screenshot 2022-10-26 at 4 16 17 PM" src="https://user-images.githubusercontent.com/51680745/198028272-5e248560-358f-403a-bc7b-d4c6b9c5176d.png">


<img width="636" alt="Screenshot 2022-10-26 at 4 16 28 PM" src="https://user-images.githubusercontent.com/51680745/198028325-ef4a9a23-40c8-4820-a38d-6dcc32f3f109.png">



<img width="1330" alt="Screenshot 2022-10-26 at 4 15 51 PM" src="https://user-images.githubusercontent.com/51680745/198028381-3a920d69-a604-494c-85e6-50141cb3b314.png">


Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by sdzhepa** [comment]
Closed due https://github.com/magento/magento2/pull/36367#issuecomment-1293767499
