### ISSUE TITLE
Admin Stores->Configuration->Sales->Payment methods unable to save - internal server error

### ISSUE THREAD

**Issue by potocky** [magento/magento2#36372]
### Preconditions and environment

- Magento version 2.4.5-p1
- Stores->Configuration->Sales->Payment methods unable to save - internal server error

### Steps to reproduce

Navigate in admin to Stores->Configuration->Sales->Payment methods
Try to save form - top right save button
 unable to save - internal server error

### Expected result

Normal page with saved form.

### Actual result

Internal server error

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @potocky,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.Kindly refer the screenshots.


<img width="1438" alt="Screenshot 2022-10-26 at 5 43 17 PM" src="https://user-images.githubusercontent.com/51680745/198027600-a53586ae-fc0b-4635-8366-a3682ac19584.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.



Thanks.
