### ISSUE TITLE
[UCT]Using class or Extending from class that is non API on version 2.4.5

### ISSUE THREAD

**Issue by athreyag** [magento/magento2#36380]
### Preconditions and environment

I have generated Upgrade Compatibility Tool Report after upgrading from 2.4.2 to 2.4.5 and getting lots of errors in core files. Please find some of the errors reported for reference.

Extending from class 'Magento\Framework\App\Helper\AbstractHelper' that is non API on version '2.4.5'
Extending from class 'Magento\ProductAlert\Model\Observer' that is non API on version '2.4.5'
Using class 'Magento\Catalog\Model\ProductRepository' that is non API on version '2.4.5'
Using class 'Magento\Framework\Model\ResourceModel\Db\Context' that is non API on version '2.4.5'

### Steps to reproduce

1. Upgrade to magento latest version.
2. Install and run UCT tool to see the list of errors.

### Expected result

UCT to list out critical issues, errors, and warnings in customized modules.

### Actual result

Getting Errors in magento core files

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @athreyag ,
Thank you for reporting and collaboration. This issue related to Upgrade Compatibility tool should be reported here in this [repository](https://github.com/magento/magento2-phpstorm-plugin/projects/3) We are closing this issue. Kindly report [here](https://github.com/magento/magento2-phpstorm-plugin/projects/3) if you are facing any issues.
Thank you.

**Comment by sprajapat770** [comment]
@engcom-November  you closed this issue do you have any solution for this problem. 
let me explain similar bug

i am creating custom ResourceModel class so i need to extend \Magento\Framework\Model\ResourceModel\Db\AbstractDb.
i need to define 1 dependency in my constructor so i have to call \Magento\Framework\Model\ResourceModel\Db\Context in my constructor but in uct report i am getting error due to this class -> Using class 'Magento\Framework\Model\ResourceModel\Db\Context' that is non API on version '2.4.7-p1'

in magento core its implemented & no issue found -> vendor\magento\module-tax\Model\ResourceModel\Calculation.php

please resolve this issue.
