### ISSUE TITLE
Customer data in localstorage not reset when session file lost

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#36391]
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

1. Login customer in frontend
2. Add product to cart
3. Remove magento session files with command: rm -rf var/session/*
4. Flush cache

### Expected result

- Header not show customer name
- Mini cart not show any item

### Actual result

- Header still show old customer name
- Mini cart still show old item

![fVbvsUP](https://user-images.githubusercontent.com/78783748/198695728-f1c4534f-b3bf-4345-bc86-dd70c1b0c936.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,


Thank you for reporting and collaboration.

Verified the issue on Magento` 2.4-develop` instance and the issue is reproducible.Customer data in localstorage not reset when session file lost.Kindly refer the screenshots.

Steps Followed:

1.Login customer in frontend
2.Add product to cart
3.Remove magento session files with command: rm -rf var/session/*
4.Flush cache


<img width="1359" alt="Screenshot 2022-11-04 at 1 03 19 PM" src="https://user-images.githubusercontent.com/51680745/199962937-344e575c-85f3-4898-b620-d68c156a490e.png">



Hence confirming the issue.


Thanks.

**Comment by o-iegorov** [comment]
The fix from the internal issue was reverted from the 2.4.7-beta1, issue so issue is still reproducible

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,

@adarshkhatri,

Thanks for your update.


Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Kindly refer the screenshots.

Steps Followed:

- Login customer in frontend
- Add product to cart
- Remove magento session files with command:  `rm -rf var/session/*`
- Flush cache


<img width="930" alt="Screenshot 2023-06-21 at 11 53 28 AM" src="https://github.com/magento/magento2/assets/51680745/ba645795-f523-482d-9983-5c8e79adac50">


After removing the session file Header still showing the old customer name and products in the cart.

Hence Confirming the issue.

Thanks.

**Comment by Poovarasan-06** [comment]
@magento i am working on this
