### ISSUE TITLE
"Integration not secure" warning showing in list of integration, if field values of "Callback URL" and "Identity link URL" are empty.

### ISSUE THREAD

**Issue by Shaikh-Samir** [magento/magento2#36407]
### Preconditions and environment

    Magento version 2.4.5
    PHP 8.1 (FPM)
    Apache2.4
    Ubuntu 20.04.5 LTS

### Steps to reproduce

1. Login to admin panel
2. Go to "System >> Extensions >> Integrations"
3. Add New Integration.
4. Fill up require fields but **fields "Callback URL" and "Identity link URL" leave empty** and Save.
5. Now error displaying as mentioned in below  attachment:
![screenshot](https://user-images.githubusercontent.com/117074683/199439946-33975e27-1023-42e5-b8d6-29024f0efbf4.png)

### Expected result

No error on integration list page as both fields are empty and optional.

### Actual result

Error found on integration list page.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Shaikh-Samir ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance and is reproducible. But however this warning message is an expected behavior but not a bug as Magento strongly recommends using https:// in integration urls for security reasons.
[Ref docs](https://docs.magento.com/user-guide/system/integrations.html)
Kindly recheck and let us know if you are still facing any issues.
Thank you.

**Comment by Shaikh-Samir** [comment]
Hi @engcom-November 

Thanks for the response.

We are agreed on recommendation of "https://" for Call back URL and Identity Link URL. But both fields are optional in API integration Form. Now if we do not pass Call back URL or Identity URL and save the API Integration Form. In the Grid it is showing warning (Integration is not secure), So client will be worried about security of APIs we are going to use. 

If we have Optional fields on any Form then Validation must be applied when we have Field Data for validation.

Let me know if need more details for this issue. 

Please review attachment we have not entered field values for both URls.

![screenshot2](https://user-images.githubusercontent.com/117074683/199654534-56adf379-2ef3-426f-9be9-080c3bd89d0a.png)


Thanks again.

**Comment by engcom-November** [comment]
Hi @Shaikh-Samir ,
Thank you for the response. Reverified the issue again on Magento 2.4-develop instance and agreed that warning message should not be displayed if we do not pass Call back URL and Identity Link URL optional fields. Temporary workaround to resolve this issue is to updated in DB by running below SQL queries:
UPDATE `integration` set `endpoint` = '' where `endpoint` IS NULL;
UPDATE `integration` set `identity_link_url` = '' where `identity_link_url` IS NULL;
Hence confirming this issue.

**Comment by Shaikh-Samir** [comment]
@magento add to contributors team

**Comment by Shaikh-Samir** [comment]
@magento i am working on the issue

**Comment by Shaikh-Samir** [comment]
@magento give me 2.4-develop instance

**Comment by adamphh** [comment]
@magento add to contributors team

**Comment by adamphh** [comment]
@magento I am working on this

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance
