### ISSUE TITLE
Updating a product through the API unchecks "Use Default Value" on a bunch of attributes

### ISSUE THREAD

**Issue by ssstankiewicz** [magento/magento2#36429]
### Preconditions and environment

- Magento 2.4.5
- 2 store views

### Steps to reproduce

1. Create 2 store views
2. Add a new product with a price
3. Change store view on the product. You can see "Use Default Value" for price is checked.
4. Update the product using the API, for example uploading an image
5. View the product again
6. Notice the "Use Default Value" on Name or Description is now unchecked (other attributes as well)

### Expected result

Checkbox "Use Default Value" should remain checked until a user actually unchecks it/add value per store view via API.

### Actual result

Checkbox "Use Default Value" unchecks itself when you update the product using the API.

### Additional information

In theory this issue was fixed in https://github.com/magento/magento2/issues/26484 but it occurs again.

Product before request:
![24-MB01_before_request](https://user-images.githubusercontent.com/25231802/200251022-3d9ae995-f34d-49fc-975f-978a3b43b1c4.png)

Product after request:
![24-MB01_after_request](https://user-images.githubusercontent.com/25231802/200251059-a8b26d37-5b8f-43be-89c4-04d5b70a25ab.png)

Request endpoint: /rest/en/V1/products/24-MB01/media
Request body:
[24-MB01_request.odt](https://github.com/magento/magento2/files/9949089/24-MB01_request.odt)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @ssstankiewicz ,

Thanks for your contribution and collaboration.

i have tried to reproduce the issue on `2.4-develop` but issue is not reproducible to me. Below are the steps which I have followed:

1. Created two views.
2. Created a product.
3. Changed the Store view and verified "Use Default" checkbox.
4. Uploaded image from rest api.
5. Again verified the Use Default checkbox.

**Screenshots for your reference:
Before and After update of image:**

**Before image update:**
![image](https://user-images.githubusercontent.com/60198022/200304495-d4cbcbd8-3299-4145-a3de-24c79f3659a9.png)


![before_update](https://user-images.githubusercontent.com/60198022/200303748-933b0e33-c2a1-4525-aa8e-087f0ee9296d.png)



**After Update:**
![image](https://user-images.githubusercontent.com/60198022/200303554-611dab2f-b020-4aca-96b9-46b590b4a3ad.png)

**Checked for existing product as well:**
![image](https://user-images.githubusercontent.com/60198022/200303494-23b785c9-c297-4d66-adef-6b40a946bffd.png)

Kindly provide more information in order to reproduce the issue. Kindly test it in latest `2.4-develop` and let us know if you are facing any issue.

Thanks

**Comment by ssstankiewicz** [comment]
@magento give me 2.4-develop instance

**Comment by ssstankiewicz** [comment]
https://github.com/magento give me 2.4.5 instance

**Comment by ssstankiewicz** [comment]
@magento give me 2.4.5 instance

**Comment by ssstankiewicz** [comment]
@engcom-Lima I can confirm that issue is not reproducible on 2.4-develop. But on 2.4.5 is. Do you have any idea how to fix it temporarily?

**Comment by ssstankiewicz** [comment]
@magento give me 2.4.4 instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @ssstankiewicz ,

Thanks for your confirmation in above [comment](https://github.com/magento/magento2/issues/36429#issuecomment-1305752753).
As this issue is not reproducible in latest Magento `2.4-develop`. Hence, closing the issue.

Thanks

**Comment by bartbollen93** [comment]
Hi @ssstankiewicz , I'm facing the same issue in 2.4.5-p5, did you find a solution for this problem?

**Comment by ssstankiewicz** [comment]
Hi @bartbollen93, yes. I attach patch for this issue.

[ACSD-48133_2.4.4.zip](https://github.com/magento/magento2/files/13189431/ACSD-48133_2.4.4.zip)
