### ISSUE TITLE
Hidden custom Shipping Policy in Admin Store View scope

### ISSUE THREAD

**Issue by angelo983** [magento/magento2#36425]
### Preconditions and environment

- Magento version 2.4-develop
- PHP 8.1
- Apply Shipping Policy.

### Steps to reproduce

1. Go to Stores => Settings => Configuration => Sales => Shipping Settings => Shipping Policy Parameters
2. Set 'Apply custom Shipping Policy' to Yes
3. Fill Shipping Policy field with text
4. Switch in Store View scope in admin.

### Expected result

Shipping Policy field visible in Store View scope

### Actual result

Shipping Policy field is not visible in Store View scope

### Additional information

1.Set 'Apply custom Shipping Policy' to No
2. Switch in Store View scope in admin.

Shipping Policy field visible in Store View scope

<img width="1371" alt="Screenshot 2022-11-10 at 4 57 02 PM" src="https://user-images.githubusercontent.com/51680745/201080177-4154d2d7-e39c-46ca-905d-4b178e6952e3.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @angelo983,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Shipping Policy field visible in Store View scope.Kindly refer the screenshots.

Steps to reproduce :

1.Go to Stores => Settings => Configuration => Sales => Shipping Settings => Shipping Policy Parameters
2.Set 'Apply custom Shipping Policy' to Yes
3.Fill Shipping Policy field with text
4.Switch in Store View scope


<img width="1494" alt="Screenshot 2022-11-07 at 1 54 16 PM" src="https://user-images.githubusercontent.com/51680745/200305215-7e9384cc-d071-44f9-b4a5-f11b590a98ed.png">



<img width="1281" alt="Screenshot 2022-11-07 at 1 54 21 PM" src="https://user-images.githubusercontent.com/51680745/200305242-a2cc63a6-5f3b-4eb1-b9c9-9f37ed5e61a4.png">



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by angelo983** [comment]
@engcom-Bravo read better steps and follow them to the letter, according also to issue title.

Switch ADMIN setup in store view scope 
![image](https://user-images.githubusercontent.com/24254454/200315501-8ed9133a-c3a5-4c34-907b-c25c78fabbb6.png)

Thanks.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @angelo983,

Thanks for quick Update.

Store Views are mostly used to handle different languages on your website as per magento [devdocs](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/site-store/store-views.html?lang=en).We Cannot configure Shipping Policy.When we Configure Shipping Policy initially from Default store view it will not reflected in the Frontend.


Kindly let us know if you are still facing any issue.


Thanks.

**Comment by angelo983** [comment]
Sorry but I cannot understand what you wrote. The issue is still present, example try to write a shipping policy for a specific language different from the default one.

**Comment by engcom-Bravo** [comment]
Hi @angelo983,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to Reproduce** :

1.Go to Stores => Settings => Configuration => Sales => Shipping Settings => Shipping Policy Parameters
2.Set 'Apply custom Shipping Policy' to Yes.
3.Fill Shipping Policy field with text.
4.Switch in Store View scope in admin.


Shipping Policy field is not visible in Store View scope.



<img width="1422" alt="Screenshot 2022-11-10 at 1 03 15 PM" src="https://user-images.githubusercontent.com/51680745/201078803-6da2ce2d-4472-408a-80eb-cd650e7970f0.png">




When 'Apply custom Shipping Policy' to No.
Switch in Store View scope in admin.


Shipping Policy field visible in Store View scope


<img width="1371" alt="Screenshot 2022-11-10 at 4 57 02 PM" src="https://user-images.githubusercontent.com/51680745/201079599-297df807-9108-4d12-b146-0b8b52eb5125.png">.




Hence confirming the issue.


Thanks.
