### ISSUE TITLE
Password reset - The session has expired, please login again

### ISSUE THREAD

**Issue by pbritka** [magento/magento2#36447]
### Preconditions and environment

- Magento version 2.4.5
- Clean installation with Luma theme
- developer environment

### Steps to reproduce

Have 2 browsers open. One with the magento shop, second one with your gmail account.

Register a new customer.

In the first browser, click on the "forgotten password" link and enter your email address. You'll be redirected to a customer login page. Don't close the tab.

In the second browser, click on the "reset password" link in your gmail account. A new browser tab will open. Set a new password.

Go back to the first browser, enter your new login information and click on the "login" button. 

You'll get this errror: The session has expired, please login again

### Expected result

The customer is logged in and redirected to the dashboard.

### Actual result

Redirected to https://m2livetest.isotoxin.com/customer/account/index/ with this error message: The session has expired, please login again

When the user logs in the second time, everything works. But it's still not very good to have this screen. It was reported by our QA on our solution which was in production mode and the user was redirected to the homepage. I could replicate this behavior on the clean Luma installation. In previous verision 2.4.3 that we were using, it didn't happen.

### Additional information

<img width="1354" alt="Screenshot 2022-11-09 at 12 12 14" src="https://user-images.githubusercontent.com/28778956/200827425-a44d586a-0105-4292-802a-97e6b79385c2.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @pbritka,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances.

We are not getting any exception.But the session has expired, and again we need to Login.

**Steps to reproduce** :

1.Have 2 browsers open. One with the magento shop, second one with your gmail account.

2.Register a new customer.

3.In the first browser, click on the "forgotten password" link and enter your email address. You'll be redirected to a customer login page. Don't close the tab.

4.In the second browser, click on the "reset password" link in your gmail account. A new browser tab will open. Set a new password.

5.Go back to the first browser, enter your new login information and click on the "login" button.


<img width="930" alt="Screenshot 2022-11-10 at 3 35 39 PM" src="https://user-images.githubusercontent.com/51680745/201070313-fe54c4ea-274c-4e91-b14a-e3f809d1292e.png">



Hence confirming this issue.


Thanks.

**Comment by chittima** [comment]
Internal Team fixed this issue and waiting for the deployment

**Comment by royalkaroma** [comment]
hi i have the same issu link password reset expired i tray all the possiblity i find in internet nothing to do

**Comment by royalkaroma** [comment]
Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances.

We are not getting any exception.But the session has expired, and again we need to Login.

Steps to reproduce :

1.Have 2 browsers open. One with the magento shop, second one with your gmail account.

2.Register a new customer.

3.In the first browser, click on the "forgotten password" link and enter your email address. You'll be redirected to a customer login page. Don't close the tab.

4.In the second browser, click on the "reset password" link in your gmail account. A new browser tab will open. Set a new password.

5.Go back to the first browser, enter your new login information and click on the "login" button.

and i got 
![Capture](https://user-images.githubusercontent.com/36032214/215318130-27a908ee-55ef-465d-8f36-15de3442c504.PNG)

**Comment by hostep** [comment]
@chittima: can you provide some more info as to why this ticket got closed? And if it got fixed, please provide the commit(s) that fixed it. Thanks!

/cc @sdzhepa

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1345 by the internal team.

Related commits: https://github.com/magento/magento2/search?q=ACP2E-1345&type=commits

Based on the Jira ticket, the target version is 2.4.7.

Thanks

**Comment by chittima** [comment]
@hostep  Please find the commit id : https://github.com/magento/magento2/commit/90a2a7464a2ce5815665884a410182428de883f0

**Comment by royalkaroma** [comment]
hi sorry for late am still getting the problem

**Comment by royalkaroma** [comment]
> Hello,
> 
> As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1345 by the internal team.
> 
> Related commits: https://github.com/magento/magento2/search?q=ACP2E-1345&type=commits
> 
> Based on the Jira ticket, the target version is 2.4.7.
> 
> Thanks
hi sorry but am still getting the problem with link expired

**Comment by hostep** [comment]
Thanks @chittima !

@engcom-Hotel: I think you linked the wrong ticket, the one from @chittima looks like the correct one.

**Comment by sadlyblue** [comment]
I have a v2.4.5-p1, and applying the commit id https://github.com/magento/magento2/commit/90a2a7464a2ce5815665884a410182428de883f0 didn't worked for me. Still get the same error after.

**Comment by chittima** [comment]
Hi @sadlyblue Issue is no more reproducible with commit id https://github.com/magento/magento2/commit/90a2a7464a2ce5815665884a410182428de883f0. Can you please share more details?

**Comment by sadlyblue** [comment]
Hi @chittima. Maybe there is something else interfering, i still have the 2.4.5-p1.
I applied the changes as mentioned in the commit (adding the $this->session->destroy(['send_expire_cookie']);). An account that tried to recover the password, still got the "The session has expired, please login again." error. Trying to debug, the $cutoff is greater than $sessionCreationTime in the CutoffValidator.
Tried to recover the password again, and still the same error.
