### ISSUE TITLE
Jquery vulnerability for 3.4.0

### ISSUE THREAD

**Issue by ninjacoder30** [magento/magento2#36484]
### Preconditions and environment

- Magento version - 2.4.4-p1
- PHP 8.1

We have upgraded the Magento version and Jquery Version is upgraded to 3.4.0 with the same.

But getting Below error in our scans. Please check

![image](https://user-images.githubusercontent.com/12250864/202366230-f2010407-47ab-40dc-a146-82ffbb2f684b.png)

### Steps to reproduce

Upgrade Magento version - 2.4.4-p1

### Expected result

No errors should be reported.  because of this, we are getting a bad grade for 'security score' when running webpagetest

### Actual result

Errors in Scans 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me 2.4.5-p2 instance

**Comment by hostep** [comment]
@ninjacoder30: Magento 2.4.4-p1 ships with jQuery 3.6.0:
- https://github.com/magento/magento2/blob/2.4.4-p1/lib/web/jquery/jquery.min.js
- https://github.com/magento/magento2/blob/2.4.4-p1/lib/web/jquery.js

Are you sure you are looking at the jquery library from core Magento? Because it could be a 3rd party module or some custom code that pulls in an earlier version?

**Comment by WebHostingAce** [comment]
@ninjacoder30 upgraded to 2.4.4-p1 from 2.4.3-p1.

I can confirm the jQuery has been upgraded to jQuery 3.6.0

As @hostep mentioned, It could be a 3rd party module or custom theme customization.

**Comment by engcom-Hotel** [comment]
Hello @ninjacoder30,

Thanks for the report and collaboration!

We have tried to upgrade Magento from 2.3.x to 2.4.4-p1 and 2.4.5-p1, but in both cases, we have jQuery 3.6.0 instead of 3.4.0. 

I request you to please check this on the fresh installation of the Magento and then upgrade it. Let us know in case if you still face any issues.

Thanks
