### ISSUE TITLE
mini cart is  not working magento 2

### ISSUE THREAD

**Issue by ravimule** [magento/magento2#3649]
When I add new product to cart. It is adding that products to cart but mini cart doesn't shows anything.
and my console has following error.
TypeError: this.itemRenderer is undefined
can anyone tell what is because of this.
[http://umbrosashop.wrc-test2.be/infina-square-2.html](http://umbrosashop.wrc-test2.be/infina-square-2.html)

**Comment by ishakhsuvarov** [comment]
@ravimule Thank you for reporting. The issue seems to come from one of the customisations or extensions applied to your site. 
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by ravimule** [comment]
@ishakhsuvarov Thanks for your replay. I again encounter another issue

If I used color and text swatch in magento 2, sequence/order of option isn't changing. I mean I want to show
1. size
2. color

but it always show
1. color
2. size

if I used dropdown instead of color and text swatch. it is working fine. Can anyone tell me, is that isssue comes with magento 2.0?
I have open ticket for this, please check following url
http://magento.stackexchange.com/questions/104705/color-swatch-and-text-swatch-issue-in-magento-2

**Comment by iprabhakar** [comment]
@ishakhsuvarov , I am facing the same issue. When I add product to cart is not showing in mini cart and when I check "checkout/cart" then product are showing on this page only.
I have tried many options like enabled FPC and all but still facing the same issue. Please give some solutions

**Comment by mrkhoa99** [comment]
@iprabhakar which is your Magento version?

**Comment by iprabhakar** [comment]
@mrkhoa99  I am working on M 2.1.3
