### ISSUE TITLE
JS Code is rendered as text for the billing address's street

### ISSUE THREAD

**Issue by cdcrothers** [magento/magento2#36503]
### Preconditions and environment

- Magento version 2.4.2-p2 Enterprise and Community
- Enable google/analytics/active

https://github.com/magento/magento2/issues/25684#issuecomment-1322712773
https://github.com/magento/magento2/issues/26276#issuecomment-833671346
^ relevant issues that reported and caused the bug.

### Steps to reproduce

Reach billing step.
See billing address's street render JS code on the frontend.

![image](https://user-images.githubusercontent.com/16570564/203173763-34bda90e-055a-4ad0-b708-432d80cae608.png)

### Expected result

Billing address renders normally.

### Actual result

Billing address renders JS code on frontent

### Additional information

Short term patch/solution is the apply the patch seen in the other issue's comment linked in the description.

Root cause boils down to some namespacing issues and very poor practices within Array prototype modifications made by prototype.js. The prototype lib has been unsupported for 7+ years. The long term solution would be to remove frontend/luma dependencies on prototype.js.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @cdcrothers ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop with enterprise edition modules enabled but the issue is not reproducible with below steps performed:
**Steps performed:**
1. Configured Google [Analytics](https://analytics.google.com/) Account by creating account with property
2. Copy Measurement ID - Login to Magento admin - Stores - Configuration - Sales - Google API - Enabled and selected Account Type - Google Analytics4, add measurement id and save
3. Cache clean
4. Front end - Place Order - **No issue: No errors observed in console and order placed successfully.**
5. Created [Google tag Manager account](https://tagmanager.google.com/) and noted container id
6. Import container (Admin - Container - import container)
7. Login to Magento admin - Stores - Configuration - Sales - Google API - Select Account Type Google GTag , enter container add and save
8. Navigate to Content - Design - Configuration - HTML Head section - added the GTM script setup
9. In the footer section also added the GTM code and save configuration
10. Clear cache
11. Front end - Place Order - **No issue. Order placed successfully with no errors.**
Kindly recheck the issue on Magento 2.4-develop with enterprise edition and provide missing steps if any if the issue is still reproducible.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/203760049-40350c2c-d913-4085-960f-260d36edbd99.png)
![image](https://user-images.githubusercontent.com/60198231/203760256-dea57ad8-0cca-450b-9ddd-53f51d7ab546.png)
