### ISSUE TITLE
Unable to redirect success page after paypal payflow link payment. 

### ISSUE THREAD

**Issue by jayantakr1** [magento/magento2#36520]
**Pre-conditions (*)**

We are using Magento 2.4.3 version . We have configure paypal payflow link payment method
Issue reproducible on 2.4-develop as well.

**Steps to reproduce (*)**
1. Configure Payflow link payment from Magento Admin - Stores - Configuration - Sales - Payment Methods - Payflow link with sandbox mode.
2. Place and order from front end using payflow link payment

**Actual result (*)**
After place order it's not redirecting success page from iframe. 

**Expected result (*)**
Payflow link payment should be working with valid test data used.

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance and payflow link payment is not working in test mode using any valid test payment details used. Payment is getting declined. No errors/exceptions are observed in log files. Hence confirming this issue.
payment.log file response:
[payment log](https://github.com/magento/magento2/files/10084884/payment.log)

**Comment by engcom-Hotel** [comment]
Hello @jayantakr1,

We have an update from the internal team on this issue as follows:

This issue is reproducible on Magento 2.4-develop Local setup, but not on [Magento Cloud Instance](https://master-7rqtwti-gkp7mcrolecs2.us-4.magentosite.cloud/) while placing an order via PayPal PayFlow Link using [Test Cards](https://www.paypalobjects.com/en_AU/vhelp/paypalmanager_help/credit_card_numbers.htm)

On Local setup, getting the below error via https://github.com/magento-commerce/magento2ce/blob/2.4-develop/app/code/Magento/Paypal/Controller/Payflow/ReturnUrl.php#L78 

`Your payment has been declined. Please try again.`

Note: Even tried with HTTPS too on Local Setup, but it didn't work. Moreover, In case of placing the order via Local Magento setup, Order is placed in Admin Panel with the status as Pending Payment => Canceled.

![image](https://user-images.githubusercontent.com/51681618/228213456-9d8b0875-700a-4ddf-a3b5-57f1778087b0.png)

**Comment by engcom-Hotel** [comment]
Dear @jayantakr1,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards
