### ISSUE TITLE
Product with any custom option causes an error when deleting product images

### ISSUE THREAD

**Issue by ksenia-zlotin** [magento/magento2#36566]
### Preconditions and environment

- Magento 2.4.4

### Steps to reproduce

1. create any product with any custom option and save.
2. add a product image with any role or no roles at all and save.
3. delete the product image and save

### Expected result

Product is saved, image is deleted and no error or warning messages are shown

### Actual result

Product is saved, image is deleted but an error/warning message is shown, stating:
"The image cannot be removed as it has been assigned to the other image role"

### Additional information

This seems to solely happen to products with custom options.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @ksenia-zlotin,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.create any product with any custom option and save.
2.add a product image with any role or no roles at all and save.
3.delete the product image and save.


![yguiegfuh-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/205915444-019f3c30-1884-45a4-a49b-6088527b911b.png)


![yguiegfuh-Products-Inventory-Catalog-Magento-Admin (1)](https://user-images.githubusercontent.com/51680745/205915542-1431b097-b0be-481c-a102-2c4ca0adf949.png)


Could you please try with these steps.

Go to Stores > Attributes > Product Change Scope to "Global" for the following attributes:
* image
* small_image
* swatch_image
* thumbnail

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by ksenia-zlotin** [comment]
@engcom-Bravo It does not look like you actually added a custom option based on the screenshots provided. For me - it also works when no custom option is added. Please retest with a custom option added, as seen in this attached screenshot:
<img width="1788" alt="Screen Shot 2022-12-05 at 12 42 16 PM" src="https://user-images.githubusercontent.com/62074773/205916816-f73d6ab6-1bf6-4136-b8ec-d686d90c2458.png">

**Comment by adamphh** [comment]
@magento I am working on this

**Comment by adamphh** [comment]
@magento run all tests

**Comment by CGLOB** [comment]
Internal team is working on it.

**Comment by chittima** [comment]
commit id : https://github.com/magento/magento2/commit/423cd2a2466167e929efa1cfbf8eb4821489a714

**Comment by hostep** [comment]
Commit mentioned above seems to be too broad, it contains many other tickets as well. I think the following commits are the correct ones: https://github.com/magento/magento2/search?q=ACP2E-1479&type=commits, but no clean merge commit unfortunately :(

**Comment by INPVLSA** [comment]
Still actual on 2.4.6-p3

> Commit mentioned above seems to be too broad, it contains many other tickets as well. I think the following commits are the correct ones: https://github.com/magento/magento2/search?q=ACP2E-1479&type=commits, but no clean merge commit unfortunately :(

Unfortunately, there are only error messages snoozing on product saving here:
- https://github.com/magento/magento2/commit/58d133817c3df821d2ec5ecfbe7d9178ec1ecdd8 
- https://github.com/magento/magento2/commit/ae0678ea17b5ce2511ee7fd9c1ff7746ffdd0285

As a result - no message "The image cannot be removed as it has been assigned to the other image role" after saving the product, but the image still exists for the product
