### ISSUE TITLE
Package symfony/debug is abandoned > 2.4.5-p1 requires web-token/jwt-framework (^v2.2.7)

### ISSUE THREAD

**Issue by in-session** [magento/magento2#36574]
### Preconditions and environment

- Magento version 2.4.5-p1
- PHP 8.1

### Steps to reproduce

SSH Console "composer update -W"

### Expected result

Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.

The problem comes from the fixed web-token/jwt-framework:
magento/product-community-edition    2.4.5-p1 requires web-token/jwt-framework (^v2.2.7)
https://github.com/magento/magento2/blob/2.4-develop/composer.json#L85

Current Version is 3.1.2
https://github.com/web-token/jwt-framework 

### Actual result

-

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @in-session ,
Thank you for reporting and collaboration. Verified the behavior on both Magento 2.4.5-p1 Project-community-edition and 2.4-develop instance and is reproducible on 2.4.5-p1 but not reproducible on 2.4-develop instance. Issue might have got fixed in 2.4-develop instance. Can you please check the behavior on 2.4-develop instance and let us know if you are still facing any issues.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/206176175-d00849e9-cf67-4814-9d36-2da79ea4eb92.png)
![image](https://user-images.githubusercontent.com/60198231/206176234-c5abba62-60f0-4862-93a8-3e4e13db6b69.png)

**Comment by in-session** [comment]
@engcom-November
ok thanks for the info then it is possibly already fixed, I am working on a livesite so I can't go to 2.4-develop.

**Comment by engcom-November** [comment]
Thank you for the response @in-session . We are closing this issue as its no more reproducible on 2.4-develop instance. Kindly reopen / create new issue if you face any issues on 2.4-develop instance.
Thank you.
