### ISSUE TITLE
Greet welcome is not displayed on mobile devices after Advanced JS Bundling

### ISSUE THREAD

**Issue by arhmart** [magento/magento2#36664]
### Preconditions and environment

- M2.4.5-p1
- I will provide build.js below

### Steps to reproduce

1. Follow the steps shown here for advanced JS bundling:
https://experienceleague.adobe.com/docs/commerce-operations/performance-best-practices/performance-best-practices/advanced-js-bundling.html

It work fine on both PC and mobile device on M2.4.4.

On M2.4.5-p1, the greet welcome and customer name cannot be displayed on the mobile device after Advanced JS Bundling, but it can be displayed on PC.

It also work fine without Advanced JS Bundling.

### Expected result

Make the greet welcome and customer name can be displayed on mobile devices.

### Actual result

It cannot be displayed on mobile device.

### Additional information

![8(TW_@ K(B2HA6O~GWC2Q)9](https://user-images.githubusercontent.com/84454905/209139018-d92358fb-51a4-4f4b-bbcc-64930d4f673f.png)
It work fine on PC

![6@P5P}~6_~2IP1_5V7Z$(2I](https://user-images.githubusercontent.com/84454905/209140307-ed09abcf-6c2e-43d2-abda-e46e5d5be43f.png)
It cannot be displayed on mobile device.

So, what went wrong?
Can anyone help? Thanks a lot.

build.js is below:

[build.txt](https://github.com/magento/magento2/files/10287161/build.txt)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @arhmart,

Thanks for the report and collaboration!

We have tried to reproduce this issue in the latest Magento development branch i.e 2.4-develop but the issue is not reproducible for us. Please have a look into the below screenshots for reference:

### Admin Panel JS Bundle Configuration
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/51681618/210398827-872029d1-b451-45ef-b425-76de16b3f0cb.png">

### Storefront After Login Welcome message shown

<img width="295" alt="image" src="https://user-images.githubusercontent.com/51681618/210398965-d0cedd08-2f96-4641-a541-8947be534e87.png">

Please let us know if we missed anything.

Thanks

**Comment by arhmart** [comment]
@engcom-Hotel 

Hi, you are referring to magento built-in js bundles.
But I'm talking about advanced js bundles with build.js

**Comment by engcom-Hotel** [comment]
Thanks @arhmart,

We are working on it. Will update you soon on this.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @arhmart,

We have tried it with the advanced js bundles with build.js also but still, the issue is not reproducible for us. Please refer to the screenshot below for reference:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/51681618/214591919-70ee9409-e9f8-4b07-b54e-bea85ef9afbe.png">

We are using the Magento 2.4-develop branch with sample data installed. Nothing has been customized in this instance.

Thanks
