### ISSUE TITLE
addFilterToMap function is not working for certain columns

### ISSUE THREAD

**Issue by dzhuser** [magento/magento2#36719]
### Preconditions and environment

Magento 2.4.5-p1

There an issue related with addFilterToMap function on custom grid collection used in custom admin grid. If you map column with name `created_at` it will conflicts with same column in joined table in `where` condition.  It seems that new plugin `Magento\Sales\Plugin\Model\ResourceModel\Order\OrderGridCollectionFilter` in `aroundAddFieldToFilter` function ignores AbstractDb's mapper   `_getMappedField` that called inside `_translateCondition`. In this case you get error "SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous".

### Steps to reproduce

1. Create custom grid in admin based on table that has  `created_at` column
2. Rewrite `_initSelect` to add join with another table that also has `created_at` column and after that apply filter map `$this->addFilterToMap('created_at', 'main_table.created_at'); `
3. Apply filter on the grid by 'created_at'  field or you can just apply `addFieldToFilter` by `created_at` column programmatically on you collection

### Expected result

filtering of a collection by mapped  column `created_at` works without errors and uses applied filter mapping

### Actual result

applied filter mapping for `created_at` column not working. Getting error`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous`.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ananth-iyer** [comment]
@dzhuser @engcom-Dash I have replicated the issue and a single line fix.

Find line:

```php
$fieldName = $subject->getConnection()->quoteIdentifier($field);
```

Replace with:

```php
$fieldName = $subject->getConnection()->quoteIdentifier($subject->getMainTable() . '.' . $field);
```

I will create a PR soon. I need to sync my forked repository before that.

**Comment by engcom-Hotel** [comment]
Hello @dzhuser,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in the 2.4-develop branch and the issue is reproducible for us. The issue can be reproducible with the exact description mentioned in the main window. 

Please refer to the screenshot below for reference:

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/51681618/213705945-3061092c-e7ee-4678-a33f-088324795768.png">

Hence confirming the issue.

Thanks

**Comment by ljr95** [comment]
@ananth-iyer 
Thank you very much for solution, it works for me.
What would be the best solution to apply this fix, I think applying the change directly in vendor/magento/module-sales/Plugin/Model/ResourceModel/Order/OrderGridCollectionFilter.php would fiendly
Thank you for your reply

**Comment by ananth-iyer** [comment]
@ljr95 I am happy to know that my solution worked for you. You could create a patch file, then add an entry in composer.json for future deployments.

**Comment by ljr95** [comment]
@ananth-iyer 
Thank you for your answer, can you give me the outline so that I can realize it?

**Comment by ananth-iyer** [comment]
@magento I am working on this

**Comment by SerhiiMandrykin** [comment]
@ananth-iyer the thing is that `\Magento\Sales\Plugin\Model\ResourceModel\Order\OrderGridCollectionFilter::aroundAddFieldToFilter` is affecting filter `created_at` of any table. So your solution fixes only the consequences but not the cause.

I think this plugin should only affect the very specific place that is needed but not every call of `addFieldToFilter`

**Comment by SerhiiMandrykin** [comment]
I mean, this solution will add `main_table.` to every `created_at` field when filtering

**Comment by ananth-iyer** [comment]
@SerhiiMandrykin This error occurs only in this Plugin class and not in other places.

**Comment by SerhiiMandrykin** [comment]
@ananth-iyer well this plugin affects all other grids
If you have the created_at column on **your custom grid** and have`addFilterToMap` for the column - it won't work because of the plugin

Here's the flow:
1. You filter by `created_at`
2. The method `addFieldToFilter` is going to be called
3. Here's where the plugin `\Magento\Sales\Plugin\Model\ResourceModel\Order\OrderGridCollectionFilter::aroundAddFieldToFilter` comes up
4. The plugin prevents `addFieldToFilter` for **your custom grid**.
![image](https://user-images.githubusercontent.com/25152924/222070927-8d14f76d-bd7b-4471-ae59-dbef680791c7.png)

I'm trying to say that it is better to not set plugin on `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult` because it is **too common**

**Comment by ananth-iyer** [comment]
@SerhiiMandrykin As per plugin name suggests: `orderGridCollectionFilterPlugin` it should be for `Magento\Sales\Model\ResourceModel\Order\Grid\Collection`, but previous developer add it for `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult` and will cause issues in other places.

Should this be changed in `adminhtml/di.xml` of Magento_Sales from `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult` to `Magento\Sales\Model\ResourceModel\Order\Grid\Collection`?

I will test it locally and if it works then push in the PR.

**Comment by SerhiiMandrykin** [comment]
@ananth-iyer yes, i guess changing it to `Magento\Sales\Model\ResourceModel\Order\Grid\Collection` would be great. thank you

**Comment by ananth-iyer** [comment]
@SerhiiMandrykin I changed it to `Magento\Sales\Model\ResourceModel\Order\Grid\Collection` in latest commit.

**Comment by SerhiiMandrykin** [comment]
@ananth-iyer thank you!

**Comment by fgerodez** [comment]
@ananth-iyer The problem with changing the plugin target to `Magento\Sales\Model\ResourceModel\Order\Grid\Collection` is that both the CreditMemo and Invoice grids only extend `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult`.

With your new target the plugin code for the `created_at` and `order_created_at` fields won't be executed for the CreditMemo and Invoice grids which can potentially cause unwanted results.

**Comment by SerhiiMandrykin** [comment]
So in this case we can create a class that extends `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult` and then do all the staff in there instead of the plugin

**Comment by fgerodez** [comment]
Quite a few other grids depend on `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult` and I think we could tweak the plugin to have it call `$proceed($field, $condition)` all the time. I have to do further tests but I don't see the point of manually adding the sql clause there instead of letting the parent (and its custom logic potentially) do the work in addFieldToFilter.

That would give us something like: 

![image](https://user-images.githubusercontent.com/876544/227936308-e718e273-8c4a-4d80-8655-164917959911.png)

I've looked at most of the inherited classes of `Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult` and the only problematic code I found is this one in `Magento\Customer\Model\ResourceModel\Grid\Collection`:

![image](https://user-images.githubusercontent.com/876544/227937302-2e660e83-7d48-4997-b9d3-d6741b9b4e67.png)

It duplicates the logic of the plugin. At the moment the code `if ($field === 'created_at')` is never called because the plugin doesn't call `$proceed($field, $condition)` for created_at.

So by always calling `$proceed($field, $condition)` in the filter and removing this if block in `Magento\Customer\Model\ResourceModel\Grid\Collection` we can make sure that each concrete Grid Class has the ability to add fields to the query any way it wants without impacting the others.

**Comment by ananth-iyer** [comment]
@fgerodez We should follow SOLID DESIGN PRINCIPALS over there: https://stackify.com/solid-design-principles/

Please feel free to edit in my PR.

**Comment by mdesplenter** [comment]
I was hitting this problem last week. For now I removed the plugin in my modules etc/adminhtml/di.xml with this code:

`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
	

	
	
	<type name="Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult">
        <plugin name="orderGridCollectionFilterPlugin" 
			type="Magento\Sales\Plugin\Model\ResourceModel\Order\OrderGridCollectionFilter"
			disabled="true"/>
    </type>
</config>`

Also informed by client he should use the Datepicker when filtering because the check is now gone.

I won't/can't fix it myself, but; this plugin should look if there is a mapping set and add it before the fieldname, I don't think hardcoding main_table like suggested is the correct way to do this.

**Comment by pradeepkanaka** [comment]
The issue still exists in 2.4.6-p3, is there any patch available to fix this issue?

**Comment by rishibankaradicle** [comment]
@pradeepkanaka By any chance, did you got the working patch from adobe that fix the issue if we are on Magento version < 2.4.8?
