### ISSUE TITLE
Catalog price rule condition get the wrong attribute value (wrong scope).

### ISSUE THREAD

**Issue by dekzer007** [magento/magento2#36752]
### Preconditions and environment

- Magento version ver. 2.4.5-p1 
- The problem is we have catalog price rule which have a condition. If "test_dropdown_website_scope is B" then discount "10".
![mg2_01](https://user-images.githubusercontent.com/8735334/213107084-0b76e77b-8a92-45cb-b86f-e2d310205c0d.jpg)

We have 2 websites and each website has 1 store.
![mg2_02](https://user-images.githubusercontent.com/8735334/213107775-16328747-cd90-4517-a4a2-5fdc4daf4a45.jpg)

USD store set the value to empty.
![mg2_03](https://user-images.githubusercontent.com/8735334/213108522-ffccc3fb-8e4d-4985-8927-19d5b83d95eb.jpg)

DKK store set the value to "B".
![mg2_04](https://user-images.githubusercontent.com/8735334/213108585-04a8c862-51b1-480f-a902-1af14a719b9b.jpg)

In database look like this.
![mg2_05](https://user-images.githubusercontent.com/8735334/213108735-decbd588-2954-4305-a1a2-dc3d96e0351f.jpg)

USD store frontend reult.
![mg2_06](https://user-images.githubusercontent.com/8735334/213110998-0bfe6116-5848-4bcb-bda4-93061177cb9c.jpg)

DKK store frontend reult.
![mg2_07](https://user-images.githubusercontent.com/8735334/213111069-733775a8-8963-476a-ba18-eee41554dacc.jpg)

DKK store should show the discount price.

### Steps to reproduce

1. Create 2 websites, 1 store for each website.
2. Create dropdown product attribute (scope : website), Add to an attribute set.
3. Create a simple product
- first store : set the attribute value to empty 
- second store : set the attribute value to some value that match the product price rule condition.
4. Create a catalog price rule. Set condition where the dropdown attribute in step 2 match some option value. (in my case is "B")
5. Apply catalog price rules, re-index and flush cache.

### Expected result

Frontend price:
- The first store show the full price.
- The second store show discount price.

### Actual result

Frontend price:
- The first store show the full price.
- The second store show the full price.

### Additional information

From many test cases we have done. We think catalog price rule get the first atribute value record without store/website filter.

For example, we try to set the match value on the first store and set value to empty for the second store.
![mg2_08](https://user-images.githubusercontent.com/8735334/213112366-e6f68317-37d6-4749-b6c0-2fadf3299f85.jpg)

Then frontend show discount for both stores which also unexpected.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @dekzer007,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Create 2 websites, 1 store for each website.
2.Create dropdown product attribute (scope : website), Add to an attribute set.
3.Create a simple product
  a.first store : set the attribute value to empty
  b.second store : set the attribute value to some value that match the product price rule condition.
4.Create a catalog price rule. Set condition where the dropdown attribute in step 2 match some option value. (in my case is "B")
5.Apply catalog price rules, re-index and flush cache.



<img width="1432" alt="Screenshot 2023-01-19 at 2 20 37 PM" src="https://user-images.githubusercontent.com/51680745/213428650-f659a44f-5251-4578-9764-1ed9cc8593c9.png">


<img width="1319" alt="Screenshot 2023-01-19 at 2 20 18 PM" src="https://user-images.githubusercontent.com/51680745/213428796-b6ab4c10-05f4-4ea4-870c-cc7b7418264f.png">



<img width="1237" alt="Screenshot 2023-01-19 at 2 20 04 PM" src="https://user-images.githubusercontent.com/51680745/213428861-fbc51916-263d-4bc1-adb8-97cd4405196b.png">



<img width="1486" alt="Screenshot 2023-01-19 at 2 26 19 PM" src="https://user-images.githubusercontent.com/51680745/213428912-e11cbaa2-ffa5-4fff-a590-84e2a21243bc.png">


As per catalog price rule Discount should be applied for this store, because attribute matching the catalog rule.


<img width="1414" alt="Screenshot 2023-01-19 at 2 26 28 PM" src="https://user-images.githubusercontent.com/51680745/213428936-322b4d11-2d29-4fce-bfb2-bc70faea902f.png">


Discount is not applying.


Hence Confirming this issue.


Thanks.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by Vasudev-22** [comment]
@magento I am working on this

**Comment by engcom-Hotel** [comment]
Hello @dekzer007.

We had a discussion on this flow internally and with PO as well, as per the outcome of the discussion, this is expected behavior and if customers want to cart price rule to be applied only for a specific website, they should set only this specific website as the rule scope.

Thanks

**Comment by dekzer007** [comment]
> Hello @dekzer007.
> 
> We had a discussion on this flow internally and with PO as well, as per the outcome of the discussion, this is expected behavior and if customers want to cart price rule to be applied only for a specific website, they should set only this specific website as the rule scope.
> 
> Thanks

Hi @engcom-Hotel 

I wanted to follow up on the issue. We have tried your suggestion, but it does not seem to be working correctly 100%.

When we set the USD store to empty (which does not have the discount)
![image](https://user-images.githubusercontent.com/8735334/234550626-7b1007f5-0fc4-46c5-8da5-3a1349063566.png)
and the DKK store to "B" (which should have the discount)
![image](https://user-images.githubusercontent.com/8735334/234551970-cade44c7-15eb-4ffb-bc18-7ad8cc4d4a38.png)
In database look like this.
![image](https://user-images.githubusercontent.com/8735334/234550929-d8e7e6f3-184b-4729-8584-f1683e7ec92b.png)
the frontend does not show the discount for either store, even though it should show for the DKK store.

------------
We have also tested another scenario, where we set "C" for the USD store (which should not have the discount)
![image](https://user-images.githubusercontent.com/8735334/234552189-d61683d3-47c6-4fd7-b5bb-9204e02407f2.png)
and "B" for the DKK store (which should have the discount)
![image](https://user-images.githubusercontent.com/8735334/234551970-cade44c7-15eb-4ffb-bc18-7ad8cc4d4a38.png)
In database look like this.
![image](https://user-images.githubusercontent.com/8735334/234552426-33bc4289-78d3-4228-93aa-c9ea6dfc9dbc.png)
In this case, the frontend shows the correct results. 


It seems that the issue might be related to the "null" value. Could you please investigate this further? 
We have suggested to our client to set the default value for the dropdown attribute, which the default value should not have the discount. 
However, we want to make sure that this issue does not occur again, in case the admin sets the empty value (null) on the dropdown attribute.

Best regards,

**Comment by nige-one** [comment]
The issue lies in

https://github.com/magento/magento2/blob/d196d504d8b387454a123033ec2a74d7fd3d5430/app/code/Magento/CatalogRule/Model/Rule.php#L355

The resulting select for for the `$productCollection` in

https://github.com/magento/magento2/blob/d196d504d8b387454a123033ec2a74d7fd3d5430/app/code/Magento/CatalogRule/Model/Rule.php#L363-L364

will always check for the _global scope_ (`0`) and the configured default _StoreView_. So it looks some like this:

```
SELECT `e`.*,
       IF(at_{ATTRIBUTE_CODE}.value_id > 0, at_{ATTRIBUTE_CODE}.value,
          at_{ATTRIBUTE_CODE}_default.value) AS `product_of_the_month`
FROM `catalog_product_entity` AS `e`
         INNER JOIN `catalog_product_website` AS `product_website`
                    ON product_website.product_id = e.entity_id AND product_website.website_id IN (8)
         LEFT JOIN `catalog_product_entity_int` AS `at_{ATTRIBUTE_CODE}_default`
                   ON (`at_{ATTRIBUTE_CODE}_default`.`entity_id` = `e`.`entity_id`) AND
                      (`at_{ATTRIBUTE_CODE}_default`.`attribute_id` = '493') AND
                      `at_{ATTRIBUTE_CODE}_default`.`store_id` = 0
         LEFT JOIN `catalog_product_entity_int` AS `at_{ATTRIBUTE_CODE}`
                   ON (`at_{ATTRIBUTE_CODE}`.`entity_id` = `e`.`entity_id`) AND
                      (`at_{ATTRIBUTE_CODE}`.`attribute_id` = '493') AND (`at_{ATTRIBUTE_CODE}`.`store_id` = 1)
WHERE ((e.entity_id IN ((SELECT `ca_product_of_the_month`.`entity_id`
                         FROM `catalog_product_entity_int` AS `ca_product_of_the_month`
                         WHERE (ca_product_of_the_month.attribute_id = '493')
                           AND (ca_product_of_the_month.value IN ('195'))))))
```

The value of the _StoreView_ specific value is not loaded if it is not coming from 
```
AND (`at_{ATTRIBUTE_CODE}`.`store_id` = 1)
```

If you save the product itself in the BE it will work, but the indexer will overwrite it based on aforementioned mechanism.

**Comment by bricht** [comment]
Issue still there

**Comment by bricht** [comment]
Issue still persists

**Comment by mironsoft75** [comment]
issue still exists
