### ISSUE TITLE
"Subtotal (Excl. Tax)" condition for Cart rule is not working for FREE Shipping

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#36760]
### Preconditions and environment
 - Magento version `2.4.3-p2`
 - Enable Tablerate shipping

### Steps to reproduce

**Backend**
1. Create a cart rule with following

 - {{{}Conditions{}}}: `Subtotal (Excl. Tax)` is equals or greater than `100`
 - {{{}Actions{}}}: `Free Shipping` = `For matching items only`

1. Create another cart rule with coupon `XYZ` to give a `Fixed amount discount for whole cart` of `10`

**Storefront**
1. Add items to the cart to make a subtotal of 105
1. Apply the coupon `XYZ` to get 10$ OFF

### Expected result

The shipping fee should not be 0 (i.e. FREE shipping cart rule should not be applied)
### Actual result

The shipping fee is showing 0 (i.e. FREE shipping cart rule is applied)
### Additional information

!https://user-images.githubusercontent.com/1205071/213676297-f3145d58-e179-47fb-aebc-19d5edb4e47a.png|width=593,height=348!

**Quick n Dirty Solution**

Step debugging showed that the value provided by the `$address->getData('base*subtotal_with*discount')` is not correct:
!https://user-images.githubusercontent.com/1205071/213677260-afb0ac81-6fd1-450a-a945-3212f479f63c.png|width=509,height=152!

So ended up tweaking as below:

`\Magento\OfflineShipping\Model\SalesRule\Calculator::processFreeShipping()`
``{{
public function processFreeShipping(\Magento\Quote\Model\Quote\Item\AbstractItem $item)
{
$address = $item->getAddress();

$item->setFreeShipping(false);

foreach ($this->_getRules($address) as $rule) {

/* Quick Fix - Start */
$address->setBaseSubtotalWithDiscount($address->getBaseSubtotal() + $address->getBaseDiscountAmount());
/* Quick Fix - End */

/* @var $rule \Magento\SalesRule\Model\Rule */
if (!$this->validatorUtility->canProcessRule($rule, $address))

{ continue; }

}}``
### Release note

*No response*
### Triage and priority
 - < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @MagePsycho,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


Steps to reproduce

1.Create a cart rule with following
a.Conditions: Subtotal (Excl. Tax) is equals or greater than 100
b.Actions: Free Shipping = For matching items only
2.Create another cart rule with coupon XYZ to give a Fixed amount discount for whole cart of 10


<img width="1484" alt="Screenshot 2023-01-27 at 3 17 53 PM" src="https://user-images.githubusercontent.com/51680745/215066255-8c5e6ba4-89c4-4c8b-842b-e626ea129e2b.png">



<img width="1453" alt="Screenshot 2023-01-27 at 3 14 11 PM" src="https://user-images.githubusercontent.com/51680745/215066346-ebd2f7a0-9a4a-4c45-9a2e-fbc94e61ce8f.png">


As per first cart price subtotal is greater than 100 hence in that case we are getting free shipping.

We are not able to apply coupon(2 cart price rule) .Please let us know if you are facing issue to apply coupon.


![Shopping-Cart (2)](https://user-images.githubusercontent.com/51680745/215067540-e241624d-4a77-40d6-8532-a61531049cb1.png)


Thanks.

Thanks.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @MagePsycho,

Thanks for your update.

![sahch-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/51680745/215470626-ab8f928d-6f18-4ff7-be1d-bad1cf9273f6.png)


![rgss-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/51680745/215470695-cfa0db40-5ea8-40f0-8212-3447565f6c0d.png)



![Shopping-Cart (3)](https://user-images.githubusercontent.com/51680745/215470736-8789d4ef-10f1-423a-a49f-0e7443e9a828.png)



We have created 2 cart price rules.1 for condition and 1 for coupon code.


We are not able to apply coupon code for a product please let us know you are facing issue to apply coupon.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @MagePsycho,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


Created a cart rule with following

Conditions: Subtotal (Excl. Tax) is equals or greater than 100
Actions: Free Shipping = For matching items only


![Add-Promotions-Marketing-Magento-Admin (1)](https://user-images.githubusercontent.com/51680745/216985252-1da9a02e-778a-4c52-a4a3-890027fdb724.png)



Created another cart rule with coupon XYZ to give a Fixed amount discount for whole cart of 10


![Test-Promotions-Marketing-Magento-Admin (1)](https://user-images.githubusercontent.com/51680745/216985342-b1aa7023-789f-4460-a616-9f5708ee9641.png)



Storefront

1.Add items to the cart to make a subtotal of 105
2.Apply the coupon XYZ to get 10$ OFF

As per 1 cart price rule we added a product with a price of 105, hence we are getting free shipping.

![Shopping-Cart (4)](https://user-images.githubusercontent.com/51680745/216985435-5059e6fd-5a1e-46da-b8a9-a42fdbdb72ea.png)


Here we are applying coupon code with a discount of 10 hence the subtotal is reduced to 95 so in that case free shipping should not be applied as per 1 cart price rule. Free shipping should be applied when subtotal is 105.


![Shopping-Cart (5)](https://user-images.githubusercontent.com/51680745/216985480-2f44edf9-e6d1-49ce-af53-2cc87418d2e2.png)



Hence confirming the issue.

Thanks.

**Comment by Vasudev-22** [comment]
@magento I am working on this

**Comment by Vasudev-22** [comment]
Hi @engcom-Bravo , @MagePsycho ,

In Adobe Magento, we can add multiple cart rules at a time without coupon code

So, Here the scenario is 

**Rule 1 :-** Without COUPON 
		a. Subtotal will be equal or greater than 100 .
		b. Free Shipping for item matching only.
	
**Rule 2 :-** With COUPON, Apply discount for the whole cart amount is 10%.


In Cart, 
	we have product subtotal above 100, 
	
_Scenario 1:-_ let assume as 105

	so Rule 1 will apply without coupon , so Table Rate shipping come to zero 
	next Rule 2 with coupon can apply along with this Rule 1 , because  we made Discard Subsequent Rules = No in both cart rules.

_Scenario 2:-_ let assume as 90

        Rule 1 will not apply without coupon , because  its not upto the condition, so we have table rate shipping value.
	next Rule 2 with coupon can apply .

Scenario 1 is expected , Please let me know if i was understanding in different way.
So, this is not a valid issue.

**Comment by engcom-Hotel** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7886 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-7886&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks
