### ISSUE TITLE
Layered navigation not working properly

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#36795]
### Preconditions and environment

- Magento version 2.4.5-p1
- Hyva theme

### Steps to reproduce

1. Do a clean magento 2.4.5-p1
2. install hyva theme
3. use migration tool to import data from magento1 shop
4. reindex and clean cache
5. use layered navigation

### Expected result

Products should match filter.

### Actual result

Products doesn't match filter: http://biljartwinkel.wemessage.it/outlet?price=100-200

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @Naberdz,

Thanks for the reporting and collaboration!

Here on this platform, we are accepting the issues related to Magento 2. But it seems this issue is related to data migration from Magento 1 to Magento 2. To report these kinds of issues, I would like to request to create an issue [here](https://github.com/magento/data-migration-tool/issues). 

Also, you can go through [this link](https://experienceleague.adobe.com/docs/commerce-operations/tools/data-migration/how-migration-works.html) for more details on the data migration tool.

We are closing this issue from here.

Thanks
