### ISSUE TITLE
SetEnv MAGE_PROFILER firebug in .htaccess is not working correctly.

### ISSUE THREAD

**Issue by tronghuan** [magento/magento2#3683]
## Steps to reproduce
1. SetEnv MAGE_PROFILER firebug in .htaccess file.
2. Go to [Example]http://magento.dev
## Expected result
1. Don't know.
## Actual result
1. Error message appears: "
   Fatal error: 
   Uncaught exception 'Exception' with message 'Recoverable Error: 
   Argument 1 passed to Zend_Controller_Plugin_Abstract::setResponse() must be an instance of Zend_Controller_Response_Abstract,
   instance of Magento\Framework\HTTP\PhpEnvironment\Response given, 
   called in /var/www/html/dev/lib/internal/Magento/Framework/Profiler/Driver/Standard/Output/Firebug.php on line 53 and
   defined in /var/www/html/dev/vendor/magento/zendframework1/library/Zend/Controller/Plugin/Abstract.php on line 70' in /var/www/html/dev/lib/internal/Magento/Framework/App/ErrorHandler.php:61 
   Stack trace: 
   #0 /var/www/html/dev/vendor/magento/zendframework1/library/Zend/Controller/Plugin/Abstract.php(70): Magento\Framework\App\ErrorHandler->handler(4096, 'Argument 1 pass...', '/var/www/html/d...', 70, Array) 
   #1 /var/www/html/dev/lib/internal/Magento/Framework/Profiler/Driver/Standard/Output/Firebug.php(53): Zend_Controller_Plugin_Abstract->setResponse(Object(Magento\Framework\HTTP\PhpEnvironment\Response))
   #2 /var/www/html/dev/lib/internal/Magen in /var/www/html/dev/lib/internal/Magento/Framework/App/ErrorHandler.php on line 61".
2. 
   ![loi](https://cloud.githubusercontent.com/assets/7024076/13590292/237eeda6-e511-11e5-9eaa-ff2e82c2446a.png)

**Comment by dvasconcelos** [comment]
Hello,

It is the same thing with MAGE_PROFILER html. But only on some Ajax request :
System > Export > Select an Entity Type > Once the page is loaded, just before the HTML profiler, There is exactly the same error with Firebug.php class.

The problem is that the class Magento\Framework\Profiler\Driver\Standard\Output\Firebug.php uses the class Zend_Wildfire_Channel_HttpHeaders  which is part of **ZF1**. This class expects a Zend_Controller_Response_Abstract object (ZF1) in setResponse but a Magento\Framework\HTTP\PhpEnvironment\Response object is given extending Zend\Http\PhpEnvironment\Response which is **ZF2**.

Regards.

**Comment by piotrekkaminski** [comment]
Cannot reproduce on 2.1. The output is properly shown for html output, not error for firebug.
