### ISSUE TITLE
Vulnerability when any user can execute ESI scripts and replace cached version of the page in Varnish

### ISSUE THREAD

**Issue by Sorbog** [magento/magento2#36910]
### Preconditions (*)
1. Magento 2.4.5-p1
2. Varnish 7.0

### Steps to reproduce (*)
1. ```curl -s 'https://example.com?x=<!--esi\"put-exploit-here-->' | grep "exploit"```
2. Request goes to varnish -> varnish passes it to Magento -> magento includes it on the frontend page, without escaping -> it goes back to varnish -> varnish notices ESI tag and processes it

### Expected result (*)
```
--- a/magento/module-page-cache/Block/Javascript.php
+++ b/magento/module-page-cache/Block/Javascript.php
@@ -33,7 +33,7 @@ class Javascript extends \Magento\Framework\View\Element\Template
                 'route'      => $this->getRequest()->getRouteName(),
                 'controller' => $this->getRequest()->getControllerName(),
                 'action'     => $this->getRequest()->getActionName(),
-                'uri'        => $this->getRequest()->getRequestUri(),
+                'uri'        => $this->_escaper->escapeUrl($this->getRequest()->getRequestUri()),
             ],
             'versionCookieName' => \Magento\Framework\App\PageCache\Version::COOKIE_NAME
         ];
```
### Actual result (*)
```
                'uri'        => $this->getRequest()->getRequestUri(),
```

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @Sorbog,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- `curl -s 'https://example.com?front<!--esi-->put-exploit-here<!--esx-->end' | grep "exploit"`
- Request goes to varnish -> varnish passes it to Magento -> magento includes it on the frontend page, without escaping -> it goes back to varnish -> varnish notices ESI tag and processes it.



After hitting above command we got below response.Kindly let us know if we are missing anything.

```

"pageCache": {
    "url": "http:\/\/magento22.local\/default\/page_cache\/block\/render\/?front%3C%21--esi--%3Eput-exploit-here%3C%21--esx--%3Eend=",
    "handles": [
        "default",
        "cms_index_index",
        "cms_page_view",
        "cms_index_index_id_home"
    ],
    "originalRequest": {
        "route": "cms",
        "controller": "index",
        "action": "index",
        "uri": "\/?front<!--esi-->put-exploit-here<!--esx-->end"
    },
    "versionCookieName": "private_content_version"
}
```

<img width="1510" alt="Screenshot 2023-02-28 at 12 31 43 PM" src="https://user-images.githubusercontent.com/51680745/221778465-3894eef5-4f43-4a2f-989e-ec705f06de5f.png">



Thanks.

**Comment by Sorbog** [comment]
I have investigated this vulnerability deeper and the patch is not needed because of `json_encode`.
<img width="768" alt="Screenshot 2023-02-28 at 20 16 28" src="https://user-images.githubusercontent.com/5592126/222076630-422912a2-ea8a-4616-bcec-9435b468d92a.png">
The only ESI tag you can use is `<!--esi text -->`, but this can be done only from a terminal or Postman with disabled encoding config.
Even in this situation, esi tag will still add encoded text
<img width="1723" alt="Screenshot 2023-02-28 at 20 25 51" src="https://user-images.githubusercontent.com/5592126/222077186-cb424b35-4890-467b-9db9-c4b3a1963625.png">
