### ISSUE TITLE
Export file list - file missing

### ISSUE THREAD

**Issue by ClemenF** [magento/magento2#36951]
### Preconditions and environment

- Magento version : 2.4.5-p1
- Multiple export files created

### Steps to reproduce

1. Go to System > Data Transfer > Export
2. Display a list of available file

### Expected result

I have around 2400 files exported in folder var/export/xml/Archives/order_export/.
Need to see all those file

### Actual result

I have only 19 files listed.

### Additional information

I investigate in code and found out in the file :
src/vendor/magento/module-import-export/Ui/DataProvider/ExportFileDataProvider.php:174
that it creates a variable $sortedFiles and uses the file's mtime stat as a key (last modification time) and as a sort.

In my case, multiple files are created and it seems that it's modified at the same time sometimes. This results in not displaying all my available exported files.

To have files with a "last modify" time set to the same, you can rsync or scp from a distant server and some of them will have the same information.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @ClemenF ,

Thanks for raising this issue,

Could you please provide More Information about this issue and Provide exact use case test steps for this issue as well as if you any screenshots for this issue Kindly share here,Because its very easy to proceed further and helpful to reproduce the issue quickly.

Regards,

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by ClemenF** [comment]
I think the issue is not reproducible with manual action because it's not possible to create files at the exact same time. 

To reproduce you should connect to the server with the command line and copy multiple files (with "cp" command) in the folder var/export. As the cp command is fast, they will all have the same "last_modify" stat

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by ClemenF** [comment]
Hello 

If I understand well, the issue is confirmed ? Do I have to do something now?

Regards

**Comment by engcom-Dash** [comment]
Hi @ClemenF ,

As per Main Description,this issue is not producible,Because when we creating more number of exported  files at the same time as per the actual result 19 files listed,But we got only one file is listed.its closely to the actual result,But exact actual result.

Regards,

**Comment by ClemenF** [comment]
Hi @engcom-Dash 

I don't understand your response. The issue is not that there are one or 19 files listed. It's that not all the files from the export folder are listed in the 

Regards,

**Comment by engcom-Dash** [comment]
Hi @ClemenF ,

**_Issue confirmed,_**

Verified the issue in 2.4-Develop instance and the issue is reproducible,Hence we are confirming the issue.

**_Preconditions:_**

Magento Version 2.4-Develop
PHP Version 8.1

**_Steps to reproduce:_**

1.Install Fresh Magento instance
2.Create Multiple Export file
3.Go to Stores >> System
4.Click on Export and Check Exported files is listed or not

**_Kindly Refer the below Screenshots:_**

![image](https://user-images.githubusercontent.com/60198592/225802875-a0e2d749-bac9-44ec-b73a-339fcae5a337.png)
<img width="1512" alt="ex1" src="https://user-images.githubusercontent.com/60198592/225802827-610bbf02-23da-4736-a3ac-8bd3f83f798f.png">

We created more then thousand csv files but it not  reflected in backend,only few files only showing in,we are getting actual behaviour as per the description,Hence we are confirming the issue.

Regards,

**Comment by ducquywp92** [comment]
Hello,
Is there a patch to fix this bug? What version of magento do you plan to fix this on?
Thank you.

**Comment by dhorytskyi** [comment]
The internal team is working on a solution for this issue.

**Comment by chittima** [comment]
Commit Id: https://github.com/magento/magento2/commit/1bde57e917bf42ba4f322f5887e575f7379b9b3b
