### ISSUE TITLE
[Sales] Missing relation data when reorder

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#37028]
### Preconditions and environment

- Magento version 2.4.5-p1
- PHP 8.1

### Steps to reproduce

1. Place an order
2. Reorder that order

### Expected result

- `relation_child_id` and `relation_child_real_id` are set in parent order row. A link is diplayed on parent order view to new order.
![Capture d’écran 2023-03-08 à 10 07 31](https://user-images.githubusercontent.com/1633463/223670573-a869fc2a-f9e3-4ea1-b7a2-f5f2ea8ee1b5.png)
- `relation_parent_id` and `relation_parent_real_id` are set in child order row. A link is diplayed on child order view to parent order.

![Capture d’écran 2023-03-08 à 10 06 53](https://user-images.githubusercontent.com/1633463/223670449-9116e3cc-f8ed-43cd-9daa-a39395ca0792.png)

### Actual result

- `relation_child_id` and `relation_child_real_id` are not set in parent order row. No link is diplayed on parent order view to new order.
- `relation_parent_id` and `relation_parent_real_id` are not set in child order row. No link is diplayed on child order view to parent order.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hi @Nuranto ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance and is reproducible. But however, as per Magento [docs](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/shopper-tools/reorders-allow.html?lang=en) this seems to be expected behavior. As per Magento documentation, no link to view parent order / child order from View Order page is displayed. Kindly recheck the docs and provide supporting docs/ proofs to consider this as valid bug.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/223930830-150e7fa5-0f2f-4908-8aec-8ebb0d291530.png)

**Comment by Nuranto** [comment]
Hi @engcom-November,

Ok I'm sorry, the links to previous/new on order page view I was talking about, are on backend order view. I should have been more specific.

Updated steps : 
1. Place an order
2. Reorder that order from backend
3. Check on backend order page view

However, there is no documentation about that neither: There's no screenshot on the doc of that page after reorder. 

However, the fields `relation_*` do exists in `sales_order` table, the setters and getters on `OrderInterface` do exist too, and the admin template does exist and work well when these fields are set (You can try by set those fields manually in database). 

https://github.com/magento/magento2/blob/4a41ec4822424ccc579206ed2739527ccc9f49b7/app/code/Magento/Sales/view/adminhtml/templates/order/view/info.phtml#L75-L94

**Comment by engcom-November** [comment]
Thank you for the response @Nuranto ,
Verified the issue again on Magento 2.4-develop instance with updated steps and the issue is reproducible on Admin Backend.
"Link to the Previous Order" is initially not displayed by default after reorder (relation_parent_id, relation_parent_real_id values in sales_order DB table are NULL) in Admin - Order details page but by manually updating relation_parent_id, relation_parent_real_id values in sales_order DB table, "Link to the previous order" is getting displayed on UI
However, as per Magento [docs](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/order-management/orders/order-processing.html?lang=en) no such link is mentioned as expected behavior in Admin Order details page.
![image](https://user-images.githubusercontent.com/60198231/224906513-e12f298e-5505-45d9-8f21-b99e8f87c98b.png)
![image](https://user-images.githubusercontent.com/60198231/224906561-0c41575e-6484-4ccc-907e-832e04421b67.png)

**Comment by Nuranto** [comment]
Hi @engcom-November,

My point of view is that if the code exists, the schema exists and the template exists... then it should be considered as an issue. 
The docs cannot be exhaustive, I mean, if I follow your link, I can't see "Unhold" button either. Does it means it would be a feature request if that button doesn't show up after holding an oder ?

**Comment by engcom-November** [comment]
Thank you for the response @Nuranto . Agree with you and considering this as an issue. Updating the description as per ref [comment](https://github.com/magento/magento2/issues/37028#issuecomment-1467401527) and confirming the issue.

**Comment by KrasnoshchokBohdan** [comment]
@magento I am working on this

**Comment by atIOCrON** [comment]
We updated to v2.4.7-p1 where this fix was pushed and it has caused problems because the "Reorder" button should not cause the new order to link to the previous one as suggested here.

We've been using Magento since 2009 and this was never the behaviour of the reorder button.

The link on the admin order page to a new order is only when you "Edit" an order. In that case, there should be a link because the orders are the same, you are editing one which cancels the first and makes the second, however, the reorder button is just a shortcut to place a brand new order for a client, it has nothing to do with the previous order.

This "fix" should be removed, it makes no sense at all.
