### ISSUE TITLE
Swatch options are not disabled when configuration is out of stock while "Display Out of Stock Products" is true

### ISSUE THREAD

**Issue by apomili** [magento/magento2#37035]
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

1) Install Sample Data on Magento 2.4.5
2) Set  "Display Out of Stock Products" on true in Configuration Catalog Inventory
3) Create a new swatch attribute and assign to the relative attribute set.
3) Set "out of stock" some simple product of a configurable prod, like xs blu.
4) Go on the Detail Page (a product with 3 configurable option like this https://github.com/magento/magento2/issues/37035#issuecomment-1461675400) of the product.

### Expected result
All options should always visible but striked when the product go to out of stock status.

### Actual result
All configurations are allowed and I only get an error about the quantity when the server has processed the request.

### Additional information

The product should have 3 configurable swatch attributes
![image](https://user-images.githubusercontent.com/7668956/226856073-7c6469a8-dac0-4e71-ba90-db2f59b4dbd2.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
**Hi @apomili ,**

**Thanks for contribution and collaboration,**

**Preconditions:**

- Magento Version 2.4-develop instance
- PHP Version 8.1

Verified the issue in 2.4-develop instance and the issue is not reproducible,we are getting expected result as per the description.
**Kindly refer the below screenshots:**
<img width="1497" alt="png2" src="https://user-images.githubusercontent.com/60198592/223913289-19ad1291-940e-46ee-9dce-c27eba4bf49d.png">
<img width="1497" alt="png3" src="https://user-images.githubusercontent.com/60198592/223913298-cbba7372-7ae0-408a-80bd-f1769360e873.png">
<img width="1512" alt="png5" src="https://user-images.githubusercontent.com/60198592/223913303-af27523c-3c3c-4070-aa0c-e69a6175900e.png">
<img width="1512" alt="png6" src="https://user-images.githubusercontent.com/60198592/223913306-de69bb9c-55a3-436f-8fae-76ea1d489562.png">

**Steps to reproduce:**

- install magento instance

- Set "Display Out of Stock Products" on true in Configuration Catalog Invetory

- Set "out of stock" some simple product of a configurable prod, like xs blu.

- Go on the Product Page of the product.

We are not able to reproduce the in 2.4-develop instance,We are getting expected result as per the description and kindly provide more information if the issue still reproducible.

Let us know if we missing anything

Regards,

**Comment by apomili** [comment]
Ok guys, the problem returns when the product as up to three swatches attributes.

With "Display Out of Stock Products" at false
![magento_display_false](https://user-images.githubusercontent.com/7668956/223982967-4713516b-73eb-408e-92ce-1e34692843db.png)

With "Display Out of Stock Products" at true
![magento_display_true](https://user-images.githubusercontent.com/7668956/223983003-01a1998e-64d9-4d8b-bf05-19a9ea88ca56.png)

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @apomili ,

Thanks for collaboration and contribution,

As per your last command we got also same result, With "Display Out of Stock Products" at false the Third attribute is disabled as well as With "Display Out of Stock Products" at true the third attribute is enabled.Could you please give Actual result and expected result as per you last [comment](https://github.com/magento/magento2/issues/37035#issuecomment-1461675400),Which is Easy to proceed further to reproduce the issue.

Regards,

**Comment by apomili** [comment]
I expect that the third option is disabled also when "Display Out of Stock Products" is true, as happens with two attributes.

I think that all the options should be always visible but striked when out of stock.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @apomili ,

All options should always visible but its striked when  the product go to out of stock status.Kindly update the main description as per except result,Its very useful to proceed further in this case.

Thanks!

**Comment by engcom-Dash** [comment]
Hi @apomili ,

Verified the issue in 2.4-develop instance and the issue is not reproducible.
We are getting expected result,which is All options should always visible but its striked when the product go to out of stock status.
**_Kindly refer the below screenshots:_**
<img width="1512" alt="ww1" src="https://user-images.githubusercontent.com/60198592/226847277-c5aa8767-17bb-42f3-8375-aa612fa481cb.png">
<img width="1512" alt="ww2" src="https://user-images.githubusercontent.com/60198592/226847342-09355342-09e2-4d67-9788-2961e013fdcd.png">

Regards,

**Comment by apomili** [comment]
We said in the comments that the bug appears with at least three swatch attributes. Now I update the first post

**Comment by apomili** [comment]
I can confirm the error on mage 2.4.5

![Screenshot Capture - 2023-04-04 - 09-22-35](https://user-images.githubusercontent.com/7668956/229718225-3c4f96a6-d1c6-444b-b8dc-e65f583beabd.png)
![screencapture-app-mage245-test-backend-catalog-product-index-key-a256651318eb33aaaeaea7690516bca8d096e8d9db098e7a26e063e166fd8672-2023-04-04-09_17_21](https://user-images.githubusercontent.com/7668956/229718245-a23f07f4-40be-479b-a247-92fafd972876.png)
![Screenshot Capture - 2023-04-04 - 09-23-20](https://user-images.githubusercontent.com/7668956/229718499-ba955f93-7f2b-48df-aaea-296e0e2cdd0f.png)


While if turn off the "Display Out of Stock Products"
![Screenshot Capture - 2023-04-04 - 09-25-08](https://user-images.githubusercontent.com/7668956/229718774-a5ad3ff1-f57a-484c-9106-75ab653a6ef5.png)

**Comment by engcom-Dash** [comment]
@magento give me 2.4.5-magento instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4.5 instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4.5 instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @apomili ,

Verified the issue in 2.4-develop, the issue is not reproducible,Kindly recheck the behaviour of 2.4-develop instance.
<img width="1511" alt="Screenshot 2023-05-19 at 7 11 16 AM" src="https://github.com/magento/magento2/assets/60198592/ad1c6aa0-4b60-457f-b8a7-347d8f635f78">
<img width="1511" alt="Screenshot 2023-05-19 at 7 12 02 AM" src="https://github.com/magento/magento2/assets/60198592/b337e041-3ed7-4930-ab48-12e778482f58">

**Comment by apomili** [comment]
Please, try to flush the cache after changed the param. I can confirm the problem even in 2.4.6

**Comment by engcom-Dash** [comment]
@magento give me 2.4.6 instance

**Comment by engcom-Dash** [comment]
Hi @apomili 

Verified the issue in 2.4.6 also and we got expected behaviour,Kindly refer the screenshots

<img width="1505" alt="Screenshot 2023-06-13 at 7 38 51 PM" src="https://github.com/magento/magento2/assets/60198592/22ce1802-6db8-463e-9bab-ab37d6dc98f5">
<img width="1505" alt="Screenshot 2023-06-13 at 7 38 33 PM" src="https://github.com/magento/magento2/assets/60198592/8b07475c-98cb-44f2-ba21-dd9bdac1fbc9">
<img width="1505" alt="Screenshot 2023-06-13 at 7 40 17 PM" src="https://github.com/magento/magento2/assets/60198592/9f9088e8-910c-4f18-a7fe-cabcc475d727">
<img width="1505" alt="Screenshot 2023-06-13 at 7 39 45 PM" src="https://github.com/magento/magento2/assets/60198592/78fa2655-ce77-48ae-92a9-8ff5a3f51ad1">

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @apomili ,

Thanks for contribution and collaboration !

We worked with two attributes in 2.4-develop,Kindly check below video reference,


https://github.com/magento/magento2/assets/60198592/78c97704-2f7c-4659-aece-ca22a0e44097

Let us know if we are missing anything!

**Comment by apomili** [comment]
Hi, thanks for your patience.
Seems correct to me.
Maybe it was fixed in the development branch or I was cursed by the Magento god.

**Comment by engcom-Dash** [comment]
Hi @apomili ,

Thanks for the contribution !

have you need any further investigation regarding this issue ??? or Can we close the issue ???

Thanks !

**Comment by apomili** [comment]
Hi, I just read the 2.4.7 release notes

Out-of-stock simple products that are options for a configurable product are now displayed as disabled on the storefront when Display Out of Stock Products is set to Yes. Previously, all options were displayed as available, despite their status and real availability.
