### ISSUE TITLE
[Performance] [RemoteStorage/Swatches] Useless image copy when loading category page

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#37031]
### Preconditions and environment

- Magento version 2.4.5-p1
- PHP 8.1

### Steps to reproduce

1. Enable remote storage, create category and products with images
2. Add a breakpoint on `Magento\RemoteStorage\Plugin\Image::beforeOpen()`
3. Load a frontend category page

### Expected result

We never pass through `Magento\RemoteStorage\Plugin\Image::beforeOpen()`

### Actual result

We pass through `Magento\RemoteStorage\Plugin\Image::beforeOpen()`, which copy image from remote to tmp.

On our categories, that represent almost 600ms wasted

![Capture d’écran 2023-03-08 à 11 47 49](https://user-images.githubusercontent.com/1633463/223693273-97052b41-fa1f-4ad2-b074-361c3f085d08.png)

### Additional information

After some investigation, it seems the image get opened by Swatches module, through `getSwatchPath` => `getSwatchAttributeImage` => `generateSwatchVariations`.

I guess the solution is to **not** generate thoses images on the fly.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment]
Another example where you can see that this perf issue takes almost half the time of a front category page load time : 

![Capture d’écran 2023-03-20 à 11 41 14](https://user-images.githubusercontent.com/1633463/226316677-baa8bf07-5b92-426d-90c9-570d7ef2d76b.png)

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in the 2.4-develop instance but the issue is not reproducible for us. We have followed the below steps:

1. Configure AWS S3 via following the below documentation:
https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/storage/remote-storage/remote-storage-aws-s3.html?lang=en
2. Sync all media/images with S3 via the following command:
`bin/magento remote-storage:sync`
3. Add a breakpoint in the `app/code/Magento/RemoteStorage/Plugin/Image:beforeOpen` function but the application does not reach to the breakpoint.

Please refer to the below screencast for reference:

https://user-images.githubusercontent.com/51681618/227612561-7cb75371-a686-4273-97fd-9a45abc6e234.mp4

Please let us know if we have missed anything.

Thanks

**Comment by Nuranto** [comment]
Hello @engcom-Hotel ,

Sorry, I update the steps : 
1. Configure the color attribute with mutilple values, and set frontend_input = swatch_visual. Add colors to options. Set that attribute filterable.
2. Enable remote storage, create category and products with colors
3. Add a breakpoint on Magento\RemoteStorage\Plugin\Image::beforeOpen()
4. Load a frontend category page with products having colors.

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

Thanks for the reply!

We have tried the updated steps also but still, we are unable to reproduce the issue. We have followed the below steps:

1. Edit the `Color` attribute, and add swatches:
![image](https://user-images.githubusercontent.com/51681618/228224500-d2411a41-ca9c-49a3-be87-3a5c0f55b600.png)

2. Create new `Category` and `Product`:
![image](https://user-images.githubusercontent.com/51681618/228225891-3bc58736-f31f-4078-ab11-9f91bf0c7c62.png)

3. Enable S3 and sync images on S3
4. Add the breakpoint on Magento\RemoteStorage\Plugin\Image::beforeOpen()
5. Load a frontend category page with products having colors.

[Home-page-1.webm](https://user-images.githubusercontent.com/51681618/228226826-e596ab2e-5705-4bb9-a967-77c7a23f7d76.webm)


Still, the breakpoint is not hit.

Thanks

**Comment by Nuranto** [comment]
Actually, we will still have the issue if we set an image instead of a color in swatches.

**Comment by engcom-Hotel** [comment]
Ok @Nuranto, let me check this with images instead of a color in swatches.

**Comment by engcom-Hotel** [comment]
@Nuranto,

We have tried with the image swatches as well but the issue is still not reproducible for us. Please have a look at the below screenshot:

![image](https://user-images.githubusercontent.com/51681618/228859029-b85deedb-afee-4ce6-b422-1ece64f49d9d.png)

[Home-page-2.webm](https://user-images.githubusercontent.com/51681618/228860543-fb15439d-4b83-494d-ba20-0c6e873eb594.webm)

Please let us know if we have missed anything.

Thanks

Thanks

**Comment by Nuranto** [comment]
Hi @engcom-Hotel ,

I'm not sure we're talking about the same things. It seems you still have color as swatch visual, not image : 
![Capture d’écran 2023-03-30 à 16 08 06](https://user-images.githubusercontent.com/1633463/228863113-cd5d1348-498e-4c08-a0b2-4a888226a3ad.png)

(second option : Upload file)

**Comment by engcom-Hotel** [comment]
@Nuranto, We have also uploaded images only, no colors have been used.

**Comment by Nuranto** [comment]
Ok, I'm confused. I don't know which step is wrong or missing. Maybe there's another third part extension involved. Or it has been fixed in 2.4.6.
Hence closing this issue.
