### ISSUE TITLE
Flooded with spam customers

### ISSUE THREAD

**Issue by rt-renjithThomas** [magento/magento2#37155]
### Preconditions and environment

- Magento version 2.3.4
- Flooded with random spam customers
![FloodedCustomers](https://user-images.githubusercontent.com/127417250/224056091-0c8f0017-b8d3-4bc2-9d5a-79d18648d11a.png)

### Steps to reproduce

1.Login to Admin portal
2.Select customers
3.List list of customers with actual and spam customers.

### Expected result

![FloodedCustomers](https://user-images.githubusercontent.com/127417250/224056736-8b3cbf3c-1c26-464f-88d3-571680b130b0.png)

### Actual result

1.Should list only actual customers.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
[Add Google ReCaptcha to the customer registration pages](https://experienceleague.adobe.com/docs/commerce-admin/systems/security/captcha/security-google-recaptcha.html) (and other things like newsletter subscription).
We had phantom accounts until we added it.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
@devchris79 Thanks for your contribution & collaboration over here.

Hi @rt-renjithThomas,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Login to Admin portal
- Select customers

<img width="1009" alt="Screenshot 2023-03-10 at 1 59 54 PM" src="https://user-images.githubusercontent.com/51680745/224329427-006a00f4-635c-4984-ac1d-508b1cc4dbcd.png">





Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by rt-renjithThomas** [comment]
@devchris79 
Thank You for the help.
Google ReCaptcha added to the customer registration pages and page looks fine.
