### ISSUE TITLE
[Issue] File doesn't exist error when trying to upload using /product/{sku}/media endpoint

### ISSUE THREAD

**Issue by redsquirrelstudio** [magento/magento2#37186]
### Preconditions and environment

- Magento version: 2.4.5-p1

I am currently unable to create media against a product using the /product/{sku}/media api. 
I have remote storage with S3 enabled.
Endpoint returns error when core file is modified to return an actual exception:
File '<S3 ENDPOINT>/media/tmp/catalog/product/0/e/0e122e0136b51a9b8ed525284aed2b12.jpg' doesn't exist"

It looks like magento is not creating the temporary file in S3 resulting in this error.

Many thanks for any help.

### Steps to reproduce

Enable remote storage using the following commands with credentials.
```
php bin/magento system/media_storage_configuration/media_database 0

php bin/magento setup:config:set \
    --remote-storage-driver="aws-s3" \
    --remote-storage-bucket="UNIQUE-BUCKET-NAME" \
    --remote-storage-prefix="myPREFIX" \
    --remote-storage-region="me-south-X" \
    --remote-storage-key="REMOTE_STORAGE_KEY" \
    --remote-storage-secret="REMOTE_STORAGE_SECRET"
```

Create a product with all required fields filled out in magento admin.
Send request to api route /rest/all/V1/products/{sku}/media/
Content type: application/json

Body:
"entry" => (object)[
            "content" => (object)[
                'base64_encoded_data' => $content,
                'name' => $filename,
                'type' => $mime
            ],
            'media_type' => 'image',
            'disabled' => 0,
            'label' => $label,
            'position' => $order,
            'types' => $types,
]

Usually will return "Product could not be saved"
Upon modifying Magento\Catalog\Model\Product\Gallery\GalleryManagement Line 82 to return the exception
returns:  "File '<S3 Endpoint>/media/tmp/catalog/product/0/e/0e122e0136b51a9b8ed525284aed2b12.jpg' doesn't exist"

### Expected result

Image is uploaded to s3 and is assigned to the product with the specified sku.

### Actual result

API returns an error 500

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by redsquirrelstudio** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Hi @redsquirrelstudio ,
Verified the issue on Magento 2.4-develop instance with below steps performed but the issue is not reproducible.
Steps performed:
1. Enabled remote Storage with S3 from terminal. [Ref docs](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/storage/remote-storage/remote-storage.html?lang=en)
2. Disabled database storage: `bin/magento config:set system/media_storage_configuration/media_database 0`
3. Created a product from Magento admin
4. Postman - Created admin integration token using POST: rest/default/V1/integration/admin/token
5. Sent POST request to /rest/all/V1/products/{sku}/media/
No issue: Response retrieved as expected. Image uploaded successfully in UI as well
![image](https://user-images.githubusercontent.com/60198231/225219685-6ba400f6-54f8-4c6a-9ee0-98204795528f.png)
![image](https://user-images.githubusercontent.com/60198231/225219814-2c35136b-60d8-4a61-bb0b-e081b19fd454.png)
Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by redsquirrelstudio** [comment]
Hi @engcom-November,

Thank you for your quick response. I have updated my application to v2.4.6 today and it has fixed the issue I was having in
2.4.5-p1.

I'll close down this issue, thanks again.
