### ISSUE TITLE
Cannot slide images in product page in mobile in 2.4.6 only!

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37232]
### Preconditions and environment

- Magento version 2.4.6 (in 2.4.5 was working!!)
Luma Theme

### Steps to reproduce

Create a product with more than one image, 3 or 4 would be perfect!
In the product page, using a mobile or mobile view try to slide images to the left (or to the right) with your finger!
Images are not sliding and not changing at all, the slider is not responding. Only way to see the next image is to click on the tiny dot under the image.
I consider this major bug (as usual unexplained regression once again...)

### Expected result

The images should slide following the finger of the user!

### Actual result

Only the first image of the product is displayed and user is completely unable to view the rest images! This is major bug!!!
Why magento is doing so often such basic regressions? Why simple things that used to work correctly are breaking down the road in every release??

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
Can you record video mobile show your web ? android or ios firms
So this issue happen on real mobile devices only

**Comment by engcom-Dash** [comment]
@magento give me 2.4.6 instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by cptX** [comment]
@mrtuvn hi, I don't have another camera available to record a video on the physical phone but anyway there is no point to show a video. If you just visit the product page in a mobile phone you cannot slide right or left the images of the product. The first image stays frozen on the screen and this is MAJOR BUG.
Also this is a Luma theme. No custom modules installed. I have the exact same copy of the site with 2.4.5 and it works there. This functionality clearly broke in 2.4.6 without changing anything else!
Really disappointed. In every update fundamental functionality breaks every time. Magento was proud of anouncing 300 bug fixes, but they didn't report that 300 new bugs were introduced. I already discovered 2 new bugs the very first day of it's release!
Is anybody doing any fundamental testing in the dev team? How is this even possible to break?

**Comment by mrtuvn** [comment]
so can you share you website link ? It's will easy and faster way to figure problem.

**Comment by mrtuvn** [comment]
https://developer.adobe.com/open/magento/slack

**Comment by cptX** [comment]
@mrtuvn I don't understand your request. As you see above a new magento instance has been created. You just have to visit it. For your convenience check this product in mobile view with touch enabled or just from your mobile phone
https://cfe24c18561a2f21c44d921f8db2c17e.instances-prod.magento-community.engineering/radiant-tee.html
The two images cannot be slided sideways!

**Comment by cptX** [comment]
> https://developer.adobe.com/open/magento/slack

I was not aware of this group. Tried to register but it says the invitation sent to me was expired. How can I join this group?

**Comment by mrtuvn** [comment]
yes i see your point here 
Seem in real device (mine used ios 16.3.1) the icon next not visible anymore. The only way to navigate is use orange dot

**Comment by cptX** [comment]
This is major bug and I'm glad that you verified this!
I'm new to magento and I'm shocked of how easy and often standard functionality breaks on every update!! How in the world did this break??

**Comment by cptX** [comment]
Please provide a patch asap, I need to publish my site next week and this is a major blocking issue!!!

**Comment by roma84** [comment]
As a fast fix, you can revert the following commit: https://github.com/magento/magento2/commit/d1c5ccfdadbc5667e71770c68e617b2e3ad48b12
Tested, and it works fine for me after reverting the code at line 1143.

**Comment by engcom-Dash** [comment]
@magento give me 2.4.6 instance

**Comment by thomas-weaverpsp** [comment]
Can report this is also happening to me after I upgrade my site yesterday from 2.4.5 to 2.4.6.

**Comment by thomas-weaverpsp** [comment]
@roma84 I tried to implement this fix suggested but still not working on my site.

**Comment by roma84** [comment]
> @roma84 I tried to implement this fix suggested but still not working on my site.

It worked for me on 2.4.6. You need to clear and re-generate static content after the change. 

Maybe the following fix is correct for line 1143 in file fotorama.js:

```js
el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);
```

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/pull/37234
i have added quick patch here

**Comment by cptX** [comment]
I can verify that https://github.com/magento/magento2/pull/37234 works! 
Thanks guys for the quick response! @mrtuvn can you please expain your modification? What 'wheel' means for example?

Can you please expain why it broke in this version? I just need to understand the reason why things break so often. Is it because this code comes from external source and not Magento? And nobody run a single browsing before releasing 2.4.6?

**Comment by mrtuvn** [comment]
Previously i see the code changed in this commit (released to 2.4.6)
Seem author accidently remove curly brackets. But its should be object param
https://github.com/magento/magento2/commit/d1c5ccfdadbc5667e71770c68e617b2e3ad48b12
CC: @glo05363 Can you share reason or any ticket issue related with this update

And the fix/patch explain here
when wheel -> desktop options {passive: false} will pass to event
no wheel -> mobile options {passive: true} will pass to event allow touch event trigger

**Comment by mrtuvn** [comment]
@cptX have you notice any changes ? at mobile after apply patch ? Scroll janky or slow response

**Comment by engcom-Dash** [comment]
@magento give me 2.4.6 instance

**Comment by engcom-Dash** [comment]
Hi @cptX ,

**_Issue Confirmed !_**

Verified the issue in 2.4-develop instance and 2.4.6 magento instance and the issue is reproducible,Hence we are confirming the issue.

**_Preconditions:_**
Magento Version 2.4-develop and 2.4.6
PHP version 8.1

**_Steps to reproduce:_**

- Create a product with more than one image, 3 or 4 would be perfect!
- In the product page, using a mobile or mobile view try to slide images to the left (or to the right) with your finger!
- Images are not sliding and not changing at all, the slider is not responding. Only way to see the next image is to click on the tiny dot under the image.

**_Kindly refer the below screenshots:_**
<img width="1512" alt="sl2" src="https://user-images.githubusercontent.com/60198592/226200772-599eac81-7bb6-4a5a-96b6-60191caf8ad6.png">

<img width="1512" alt="sl1" src="https://user-images.githubusercontent.com/60198592/226200348-7c325166-4bc0-4f81-9ef2-b85cc883fbd5.png">

As per the description we are getting actual result,which is Images are not sliding and not changing at all, the slider is not responding. Only way to see the next image is to click on the tiny dot under the image.

Regards,

**Comment by cptX** [comment]
@glo05363 just out of curiosity, how come nobody didn't try a single slide to check the correctness of the code before the official release? As I'm new to Magento I'm really curious to understand how these basic bugs are not detected before the official releases... I mean I found the bug the very first day of the 2.4.6 release...

**Comment by chernenm** [comment]
@magento give me 2.4.0 instance

**Comment by cptX** [comment]
I'm confused, which patch should we apply https://github.com/magento/magento2/pull/37234 or https://github.com/magento/magento2/pull/37355?

**Comment by glo17680** [comment]
Internal team has started working on the issue.

**Comment by cptX** [comment]
I cannot make it work any more. Initially I had done the following modifications in file lib/web/fotorama/fotorama.js @1143

```
	-    el.addEventListener ? el.addEventListener(e, fn, !!bool) : el.attachEvent('on' + e, fn);
    +    const options = {
    +        get passive() {
    +            return e === 'wheel';
    +        }
    +    }
    +    el.addEventListener ? el.addEventListener(e, fn, options) : el.attachEvent('on' + e, fn);

```
but this now doesn't work!

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by cptX** [comment]
Why are you closing this? From my tests, as I reported in a previous post here, only a part of the patches worked. Have you tested it for all possible options: images, videos etc? Have you tested it in both pc and mobile? All these tests have to be completed successfully before closing. Shouldn't we wait for more users to test and give feedback? And as @drinkingsouls suggests a quality patch should be prepared and prioritized for this major bug.

**Comment by tsharp42** [comment]
> Images seem to scroll now but YouTube & Vimeo videos do not play on mobile.

We are facing this issue too, after implementing the fotorama.js change outlined above. The JS error as noted in #36456 is also present.

Implementing the changes in #36578 fixes the video playback when zoomed in but playback issues from the sliding gallery remain.

**Comment by JosephGourvenec** [comment]
Hi All, 

Was this solved and is there a patch or solution that works? 

I did

Error in fotorama.js, line 1143
el.addEventListener ? el.addEventListener(e, fn, !!bool) : el.attachEvent('on' + e, fn);
Needs to be changed to:
el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);

And updated, but still isn't working

**Comment by drinkingsouls** [comment]
There has definitely been changes made since. I now have fotorama.js line 1143 as:
`el.addEventListener ? el.addEventListener(e, fn, !!bool) : el.attachEvent('on' + e, fn);`
Which now works for me.

**Comment by aryanbond1983** [comment]
yes, this works for me correctly.

**Comment by JosephGourvenec** [comment]
Thanks, Here is my issue:

"There is a bug / conflict with M2.4.6-p1 once the Porto theme is installed the product carousel stops working.

My support has expired but this is a pretty big issue, when will this be fixed?

Or do you have patch for it already?

I have tested on multiple installs from fresh M2.4.6-p1 install with sample data. 1. Without Porto Theme installed product carousel works 2. Once files are uploaded to M2.4.6-p1 doesn’t work

Even without enabling Porto theme, the Luma theme itself using a Product Carousel stops working. This can only be caused by a conflict somewhere in code base, like finding a needle in a haystack.

Please advise if there is a fix for this issue and how to resolve it, or update the theme files so i can update theme again.

There are no 3rd party extensions installed at all.

1. I installed a complete fresh M2.4.6-p1 with sample data 1.a. setup both a Product Grid and Product Carousel via WYSIWYG editor - Everything worked as expected

2. Installed Porto theme and product carousel no longer works

I have done nothing else other than work with the theme, happy to give you access. I’ll even buy another license if needs be but only use mine for testing and base development until client buys themselves a the porto theme.

Cheers, Joe"

I have tried both those fixes but still doesn't work

**Comment by drinkingsouls** [comment]
> 

Same issues here still. Implemented Fotorama change for images to slide and fix [36578](https://github.com/magento/magento2/pull/36578) to get videos to play. Videos play when full screen gallery is launched but do not otherwise

**Comment by Tomasz-Silpion** [comment]
Still not fixed in both 2.4.6-p1 and 2.4.6-p2 although issue was reported in March and closed in May. We've promised fixes, we've got regression again. A halfyear has passed since @vseager provided the fix and still we have to apply it manually cause it was not yet officially released to the public and is available under 2.4.7-beta1 tag only. Shame.

**Comment by sfritzsche** [comment]
@drinkingsouls,
@tsharp42,
@cptX,
@vseager

At this point, I would like to highlight a few points that perhaps not everyone is aware of:

#### 1. the history of "addEventListener" and its parameters.
    
If you look at the history of the native javascript method "addEventListener", you will notice that until 2016 the 3rd parameter was "useCapture" (boolean only). From 2016 on you could pass either the boolean value ("useCapture") or an option object. In this option object you can now pass multiple options, like "capture", "passive" or "once".
Before it was common to pass "true" as 3rd parameter, if you wanted to override the default value "false".

#### 2. the same state as in 2017 (addEvent).

If you look at the history of the "fotorama.js" file and jump back to [year 2017](https://github.com/magento/magento2/blob/a232e0753026b081a83f1aa6fd47800da125a8c6/lib/web/fotorama/fotorama.js#L1135), for example, you can see that the call "el.addEventListener(e, fn, !!bool)" there is exactly the same as the call today (from version 2.4.6-p2).
In this context, if you look at, for example, [a call from 2017] (https://github.com/magento/magento2/blob/a232e0753026b081a83f1aa6fd47800da125a8c6/lib/web/fotorama/fotorama.js#L1209) that uses the 3rd parameter, you can see that the "bool" parameter was directly passed to the "addEventListener" function as "useCapture".

#### 3. the new "passive" parameter and the ignored "bool" parameter

[On April 09, 2021](https://github.com/magento/magento2/commit/2f5b57a0c0e20e47068e6e9552a85b4e6c28f0a2), the addEvent method was revised so that instead of the "bool" parameter, the static object "{passive: true}" is now passed to the "addEventListener" method.

However, this seems to have already been implemented incorrectly, since the original "bool" parameter no longer receives any attention. And since the "addFocus" method calls the "addEvent" method with the 3rd parameter "true" and originally wanted to set the "useCapture" option, we should have reverted to the following object:

```{passive: true, capture: !!bool}```

#### 4. the rediscovery of "useCapture"

[On 02/03/2023](https://github.com/magento/magento2/commit/d1c5ccfdadbc5667e71770c68e617b2e3ad48b12), the "addEvent" method was reverted to the 2017 state.

A strange commit.
Firstly because all events added via the "addEvent" method are now executed with "passive: false" again by default. And explicitly for the "touchstart" event (on the document) the option "useCapture" is now set to true.
At this point it should be mentioned that the specification of "addEventListener" or [its documentation](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) of the option "passive" says: "except that in browsers other than Safari, it defaults to true for wheel, mousewheel, touchstart and touchmove events".
Whether this commit was really necessary, I can't judge without the corresponding error messages.

#### Summary

To get the swipe back, the 2 lines from the [last commit](https://github.com/magento/magento2/commit/d1c5ccfdadbc5667e71770c68e617b2e3ad48b12) should look like

* 1143: ```el.addEventListener ? el.addEventListener(e, fn, {passive: true, capture: !!bool}) : el.attachEvent('on' + e, fn);```
* 1522: ```addEvent(document, 'touchstart', onOtherStart);```

I love the idea of setting the "passive" option based on the event as noted by @cptX in [comment](https://github.com/magento/magento2/pull/37234#issuecomment-1517495473).

However, the approach only queries "wheel" at the moment. This would need to be extended to include "touch" events. See [here](https://caniuse.com/passive-event-listener).
Furthermore the parameter "bool" is not used in the [code example](https://github.com/magento/magento2/pull/37234#issuecomment-1517495473), so that "addFocus" would not work as intended.

#### Regarding the [current patch](https://github.com/magento/magento2/commit/3598333616d066c4ce4ea2fb8daed53d35f680b6) by @vseager

The core problem why swiping did not work was that the option "useCapture" was explicitly used for the outer "touchstart".
The current fix prevents the setting of "useCapture" and makes the swiping work again, but

* The "bool" parameter, as explained, is probably meant for the "capture" option, not the "passive" option. See method "addFocus". The "focus" event is also executed with the "passive: true" option with this fix
* Furthermore, for all other events that are noted in the fotorama.js and do not pass a third parameter, the value of "passive" changes from "true" to "false"

#### Big solution

To really resolve any issues, it would be interesting to know what the original error messages were underlying the [last commit](https://github.com/magento/magento2/commit/d1c5ccfdadbc5667e71770c68e617b2e3ad48b12).

**Comment by Nurgiel** [comment]
Still not fixed in 2.4.6-p2 over half a year later after the issue was reported and fixed in March.

**Comment by hostep** [comment]
It will be fixed in 2.4.7 which is [to be released on the 9th of April 2024](https://experienceleague.adobe.com/docs/commerce-operations/release/planning/schedule.html). The `-pXXX` releases only contain security fixes and critical bug fixes. They don't consider this as a critical bug, I'm sorry.

Get into the habbit of using patches if you need bugs fixed in your shop, it's the easiest/fastest way to accomplish this. We have tons of patches for various Magento versions to have them working in a way we (and our clients) want them to.

**Comment by Erchiragdodia** [comment]
> @tsharp42
> 
> Same issues here still. Implemented Fotorama change for images to slide and fix [36578](https://github.com/magento/magento2/pull/36578) to get videos to play. Videos play when full screen gallery is launched but do not otherwise

You can resolve it by doing below changes in fotorama.js

Replace the line no 1222 with below code

if (!Modernizr.touch) {
            e.preventDefault ? e.preventDefault() : (e.returnValue = false);
        }

**Comment by RajasekarPanneerselvam** [comment]
@magento give me 2.4.6 magento instance

**Comment by drinkingsouls** [comment]
Did anyone have a temp fix that worked? 
Past solutions seem to only partially work or cause the video issue where they no longe play unless in full screen.
Very surprised there is no official fix for this until 2024? This is a major issue that should have had a quality patch issued.

**Comment by nicholasfishjgm** [comment]
Has anyone managed to find a fix for this please?

**Comment by drinkingsouls** [comment]
It seems this has been closed as there is a fix coming in 2.4.7. However, this is still in beta.
What is the confirmed fix for Magento 2.4.6x.
We've updated to 2.4.6-p4 and this issue is still present.

Changing fotorama.js line 1143 to
`el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);`
Works correctly for us to for image scrolling on mobile but then causes the issue that videos are not played unless opened in full screen.

I keep finding scattered solutions on Github but there seems to be no fix that solves both issues.

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by Skyfly2021** [comment]
Thanks, in magento 2.4.6-p6 also solved the sliding problem in mobile!

**Comment by sfritzsche** [comment]
Due to the latest update (Magento 2.4.7-p1), we have taken another look at the corrections. The adjustments fix the problem with swiping. However, the addEvent method was not adapted correctly. 


The current structure of the method (in Magento 2.4.7-p1) looks like this:

```javascript
function addEvent(el, e, fn, bool) {
    if (!e) return;
    el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);
}
```
The 4th parameter ("bool") is currently forwarded to the "passive" option. This was not originally intended. See the "addFocus" method (in Magento 2.4.7-p1): 

```javascript
function addFocus(el, fn) {
    addEvent(el, 'focus', el.onfocusin = function (e) {
        fn.call(el, e);
    }, true);
}
```

As already described in the [previous comment](https://github.com/magento/magento2/issues/37232#issuecomment-1743240592), the "addFocus" method already existed before the "passive" option was introduced. 

The intention of addFocus or the call to addEvent was therefore to use the "capture" option with the 4th parameter.

It was also an excellent suggestion to set the "passive" option based on the EventType ("wheel").

The addEvent method should therefore be structured as follows:

```javascript
function addEvent(el, e, fn, bool) {
    if (!e) return;
    const options = {
        get passive() {
            return e === 'wheel';
        }
        get capture() {
            return !!bool;
        }
    }
    el.addEventListener ? el.addEventListener(e, fn, options) : el.attachEvent('on' + e, fn);
}
```

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by Skyfly2021** [comment]
hi:
     Tested without problems in this version, is there a difference between this version and Magento 2.4.7-p1?


[cid:bcbf369e-7908-4482-82b2-4cac3690f18f]
________________________________
发件人: magento-deployment-service[bot] ***@***.***>
发送时间: 2024年7月3日 12:08
收件人: magento/magento2 ***@***.***>
抄送: Skyfly ***@***.***>; Comment ***@***.***>
主题: Re: [magento/magento2] Cannot slide images in product page in mobile in 2.4.6 only! (Issue #37232)


Hi @engcom-Dash<https://github.com/engcom-Dash>, here is your Magento Instance: https://cfe24c18561a2f21c44d921f8db2c17e.instances-prod.magento-community.engineering
Admin access: https://cfe24c18561a2f21c44d921f8db2c17e.instances-prod.magento-community.engineering/admin_eaca
Login: 3b9a1c9f
Password: c6b56cac73a1

―

**Comment by engcom-Dash** [comment]
Hi @cptX 

Thanks for reporting and collaboration.

I verified the issue on both Magento 2.4 dev instance and Magento 2.4.7-p1.

The issue is not reproducible.

Able to slide images on product page on mobile

Please refer to the attached screen recording


https://github.com/magento/magento2/assets/60198592/64eb1334-6bec-40e2-9f97-4bb8e8fe5af2

**Comment by DannyDaemonic** [comment]
For me it *does* work in Chrome "mobile" mode as displayed in the above video, but it doesn't work in on real mobile devices running Chrome.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @DannyDaemonic,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance using real mobile device using chrome and the issue is no more reproducible.Kindly refer the attached video.


https://github.com/magento/magento2/assets/51680745/b212f429-7010-4227-9d90-4c5c8cc83f8e



We are able to slide the images in a mobile device.

Hence we are closing this issue.

Thanks.

**Comment by DannyDaemonic** [comment]
@engcom-Bravo Thanks for taking a look. Not to be pedantic, but were you sliding the image with your finger or were you tapping on the dots at the bottom?

The feature that was lost wasn't the use of the dots below the image, but the actual dragging of the image with your finger.

**Comment by engcom-Bravo** [comment]
Hi @DannyDaemonic,

Thanks for your update.

We have tried with the fingers for sliding the images in a mobile device.Kindly let us know if we are missing anything.

Thanks.

**Comment by Flipmediaco** [comment]
Found the mobile interaction with fotorama gallery to be an issue Magento ver. 2.4.6-p6

Following the threads on this issue created the following patch which resolves the issue from https://github.com/magento/magento2/commit/9d751c5a826cab16e55043435406bdb559cc4cdd#diff-fb7ac60e407ee78fc8e5ff56eef13de3f3bbe8a8ce52c14d674f0015f502e7c7

`diff --git a/lib/web/fotorama/fotorama.js b/lib/web/fotorama/fotorama.js
index a60999e..17736fe 100644
--- a/lib/web/fotorama/fotorama.js
+++ b/lib/web/fotorama/fotorama.js
@@ -1140,7 +1140,7 @@ fotoramaVersion = '4.6.4';
 
     function addEvent(el, e, fn, bool) {
         if (!e) return;
-        el.addEventListener ? el.addEventListener(e, fn, !!bool) : el.attachEvent('on' + e, fn);
+        el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);
     }
 
     /**`

**Comment by Flipmediaco** [comment]
> I have the same issue in AC open source 2.4.7-p4. In production mode only was reproducible.

We are running the following composer patch (deployed via: cweagans/composer-patches - patching on: magento/magento2-base), this addresses the issue you are having.

```
---
 lib/web/fotorama/fotorama.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lib/web/fotorama/fotorama.js b/lib/web/fotorama/fotorama.js
index a60999e..17736fe 100644
--- a/lib/web/fotorama/fotorama.js
+++ b/lib/web/fotorama/fotorama.js
@@ -1140,7 +1140,7 @@ fotoramaVersion = '4.6.4';
 
     function addEvent(el, e, fn, bool) {
         if (!e) return;
-        el.addEventListener ? el.addEventListener(e, fn, !!bool) : el.attachEvent('on' + e, fn);
+        el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);
     }
 
     /**
--

**Comment by vaibhavmagneto** [comment]
I'm able to have it work this solution when its having the images only.
https://github.com/magento/magento2/issues/37232#issuecomment-2757976284

But what about when we are playing youtube video with the images and video is playing and we want to swipe

**Comment by engcom-Hotel** [comment]
Hello @vaibhavmagneto,

Thanks for raising the concern!

We request you to please create a new issue with the detailed information as below:

- Summary of the issue
- Information on your environment
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by Rorke-Melville** [comment]
I enabled swipe functionality for images and restored YouTube video playback on mobile devices in Magento 2.4.6-p5. This addresses the swipe issue (related to #37355 and #37232) and the video playback conflict (#38137). Here are the steps:

Go to /pub/static/frontend/Codazon/unlimited_child/en_US/fotorama/fotorama.js

Go to line 1143 
- "el.addEventListener ? el.addEventListener(e, fn, !!bool) : el.attachEvent('on' + e, fn);"

Replace it with:
+ "el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);"

then go to line 1222 
- "e.preventDefault ? e.preventDefault() : (e.returnValue = false);"

Replace it with:
+ "if (!Modernizr.touch) {
            e.preventDefault ? e.preventDefault() : (e.returnValue = false);
  }"


This file path is unique to my theme so you will need to look in your theme path "pub/static/frontend/<Vendor>/<Theme>/en_US/fotorama/fotorama.js"

Then you will just need to run the commands 

php bin/magento s:s:d 
php bin/magento c:c
php bin/magento c:f


This should allow users to swipe left or right to change images on mobile and allow them to play videos

**Comment by engcom-November** [comment]
Hello @vaibhavmagneto 

Thank you for your report and collaboration.

We were unable to reproduce the image sliding issue on our end. To assist further, please refer to the video recording attached below for clarification.

https://github.com/user-attachments/assets/1ef6f63b-6784-48e0-95f0-3bc395a8bc33

Regarding the Auto-Play functionality, kindly review the official documentation for more details:
Product Video Documentation

Let us know if you have any further questions or observations.
