### ISSUE TITLE
Google Recaptcha and Admin > Stores > Settings > Config > Security is missing

### ISSUE THREAD

**Issue by rb-ec** [magento/magento2#37279]
### Preconditions and environment

- Magento version 2.4.6 or 2.4.5-p1 or 2.4.5-p2

### Steps to reproduce

Install fresh copy of Magento and notice its missing

### Expected result

The security tab in Admin > Stores > Settings > Config should be there
![Screenshot 2023-03-21 at 14 31 26](https://user-images.githubusercontent.com/46932580/226638706-7141a7e8-7e8e-45cc-8fb7-d0fc65613038.png)

### Actual result

no errors, just the security tab in Admin > Stores > Settings > Config should be there

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rb-ec** [comment]
Ok, so the security tab is there but how does that help anyone who is running a frtesh install of 2.4.5 or 2.4.6? It makes no sense. 

How can I add it back into my production environment?

**Comment by engcom-Bravo** [comment]
Hi @rb-ec,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and 2.4.6 instance and the issue is not reproducible. kindly refer the screenshots.


We are able to see the security tab in admin configuration.


![Configuration-Settings-Stores-Magento-Admin (4)](https://user-images.githubusercontent.com/51680745/226646701-7a3df62a-289e-4ca6-9b9b-9f4308d56248.png)



Kindly recheck the issue on Magento 2.4-develop instance and 2.4.6 instance and check if any 3rd party extensions / modules enabled is causing this issue.



Thanks.

**Comment by rb-ec** [comment]
I've checked the composer.json and compared it with 2.4-dev branch and its the same. There are no missing modules. 

I've checked the server requirements in the docs and compared with what the server is running, no issues either. It should work but its just not.  Any help or recommendations would be greatly appreciated.

**Comment by hostep** [comment]
@rb-ec: it's not recommended to install Magento using the tar.gz file from github, because it does not contain all modules. Not everything from a vanilla Magento installation is coming from this repository. For example, you are missing modules from https://github.com/magento/security-package and https://github.com/magento/inventory and possibly some others as well.

It's strongly recommended to install Magento using composer as explained in [the documentation](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/overview.html), that way you'll get all necessary modules.

**Comment by rb-ec** [comment]
So what is this then? Clone the repo! I think you are wrong. 

![Screenshot 2023-03-22 at 08 12 24](https://user-images.githubusercontent.com/46932580/226839670-5e6eb5ba-bae0-4442-8c1d-50c3adc14a60.png)

**Comment by rb-ec** [comment]
thanks @hostep , appreciate the help.

**Comment by hostep** [comment]
Cloning the git repo is meant for contributing fixes to Magento core. Not for running it in production.

I would still recommend you follow the correct steps by using the composer metapackage, because it might be hard to maintain the project if you set it up like you set it up right now.

**Comment by rb-ec** [comment]
I will do that @hostep . Appreciate the help.
