### ISSUE TITLE
Cannot extract data

### ISSUE THREAD

**Issue by SPietschJLR** [magento/magento2#37273]
### Preconditions and environment

- Magento version 2.3.1
- Google Chrome "Version 110.0.5481.178 (64-Bit)"
-  Microsoft Windows 10 Enterprise: Version	10.0.19044 Build 19044

 

### Steps to reproduce

1) Navigate to Connected Cars tab
2) add filter expiry data from 01/09/2022  to 30/06/2023
3) add filter Market DE
4) apply filters
5) Expand Export drop-down (top right corner) and select CSV
6) Click export button

### Expected result

Download is started

### Actual result

Error message: "stream timeout" or "upstream request timeout"

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @SPietschJLR ,

Thank you for reporting and collaboration. However, this issue is a 3rd party extension and code of this extension is not part of https://github.com/magento/magento2 git repository. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.
