### ISSUE TITLE
Sample data deploy in magento 2.4.6 is not possible

### ISSUE THREAD

**Issue by Daniel-Zadora** [magento/magento2#37303]
### Preconditions and environment

- Magento 2.4.6
- magento clean install, set to developer mode

ERROR while setup:upgrade : **Unable to apply data patch Magento\BundleSampleData\Setup\Patch\Data\InstallBundleSampleData for module Magento_BundleSampleData. Original exception message: Rolled back transaction has not been completed correctly.**

### Steps to reproduce

1. php bin/magento deploy:mode:set developer
2. php bin/magento sampledata:deploy
3. php bin/magento setup:upgrade

### Expected result

Deploy sample data.

### Actual result

No sample data deployed.

Error while setup:upgrade
Unable to apply data patch Magento\BundleSampleData\Setup\Patch\Data\InstallBundleSampleData for module Magento_BundleSampleData. Original exception message: Rolled back transaction has not been completed correctly.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Daniel-Zadora** [comment]
I tried to delete generated data before setup:upgrade - no success
rm -rf generated/code/* generated/metadata/*

**Comment by Daniel-Zadora** [comment]
I solve the problem by changing the search engine 7 to opensearch. However I am using elasticsearch 8.4.
There is no option to select elasticsearch 8 from the admin panel or during installation.
During installation i had to use --search-engine=elasticsearch7, with the --search-engine=opensearch option I was getting an error.

**Comment by engcom-Dash** [comment]
Hi @Daniel-Zadora ,

Thanks for raising this issue,

Verified the issue in 2.4.6 magento instance,the issue is not reproducible.

**Kindly refer the below Screenshots:**
<img width="1512" alt="2463" src="https://user-images.githubusercontent.com/60198592/228094689-2b7f304a-b01a-4725-b4e0-1aa8d00c66cb.png">
<img width="1512" alt="2464" src="https://user-images.githubusercontent.com/60198592/228094693-39b6c00d-8f03-4b10-81b7-79d50f46dda6.png">
<img width="1512" alt="2462" src="https://user-images.githubusercontent.com/60198592/228094683-40095b7f-cacd-4666-9067-96438a142543.png">
<img width="1512" alt="246" src="https://user-images.githubusercontent.com/60198592/228094679-2e84108d-45e3-484c-84d4-7cdd869fbe12.png">

**Steps to reproduce:**
1.Install 2.4.6 Magento instance
2.Set a developer mode
3.php bin/magento deploy:mode:set developer
4.php bin/magento sampledata:deploy
5.php bin/magento setup:upgrade

Sample data deployed successfully.

Let us know if we are missing anything

Regards,

**Comment by hostep** [comment]
@Daniel-Zadora:
> I solve the problem by changing the search engine 7 to opensearch. However I am using elasticsearch 8.4.
There is no option to select elasticsearch 8 from the admin panel or during installation.

ES 8 support doesn't exists out of the box in Magento 2.4.6, you'll need to perform some extra steps: https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html#upgrade-elasticsearch

**Comment by shakil-codilar** [comment]
@magento give me 2.4.6-develop instance

**Comment by SolsWebdesign** [comment]
I think this should be addressed, though, it doesn't only happen in 2.4.6 but almost in any version and I am specifically saying version here because I have seen this error in 2.4.7-px, 2.4.4-py and in 2.4.6-pz ... and I finally found out why because it happened again today (just after the release of another security package).
So I installed 2.4.4-p10  a few weeks ago for a quick test, quickly added sample data and no problem. 
I needed a new clean test environment so I installed another 2.4.4-p10 and installed the sample data and I got the error

Unable to apply data patch Magento\BundleSampleData\Setup\Patch\Data\InstallBundleSampleData for ...

This really triggered me, could it seriously be that the command bin/magento sampledata:deploy actually installs the wrong sampledata.. security package??????? No, it could not be that, right? Yes, that is right, that is exactly what happens :-(

To test this I tried the following: remove the sample data that the bin/magento sampledata:deploy does and download the right package from magento's sample-data github (so that would be magento2-sample-data-2.4.4-p10.tar.gz), put it in the root, unpacked it and ran setup:upgrade. No errors.

I had another go, I installed a specific instance of 2.4.6 and I choose p2. So I installed a clean 2.4.6-2 through composer and everything. And then I did bin/magento sampledata: deploy and setup:upgrade. Error! 
I proceeded to uninstall using sampledata:remove and downloaded the magento2-sample-data-2.4.6-p2.tar.gz and put it in the root of magento. Unpacked it and setup:upgrade and... it worked!

So... if "magento-deployment-service" will test this, they will simply get the right version with the right version of the sample data and ... so it is possible they will say "issue is not reproducible"...

**Comment by rbncha** [comment]
Hello. It is my fresh installed Magento 2.4.6. While I try to install sample data, the bin/magento setup:upgrade process I get this error..... 

> Warning: Trying to access array offset on value of type bool in vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 93
