### ISSUE TITLE
The dates at Magento are 3 hours ahead, at the excel csv, then the correct date at the Magento system 

### ISSUE THREAD

**Issue by guineedhelp** [magento/magento2#37306]
### Preconditions and environment

- Magento versão 2.4.2-p1

### Steps to reproduce

1. Download data as csv, works great but it export all the date 3 hours ahead of the system data which is not correct

### Expected result

1. Download data as csv, and the data exported have the same day and hour of the system

### Actual result

1. Download data as csv, works great but it exports all the data 3 hours ahead of the system data which is not correct

### Additional information

1. Download data as csv, works great but it exports all the data 3 hours ahead of the system data which is not correct

### Release note

1. Download data as csv, works great but it exports all the data 3 hours ahead of the system data which is not correct

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @guineedhelp,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We have exported a file at `01:38` indian standard time the data is not ahead of the magento system.

Please Make sure your cron job is running.

<img width="1510" alt="Screenshot 2023-03-29 at 1 47 47 PM" src="https://user-images.githubusercontent.com/51680745/228471387-18915fdc-2b0d-4677-90d3-6e6432042363.png">


<img width="416" alt="Screenshot 2023-03-29 at 1 47 13 PM" src="https://user-images.githubusercontent.com/51680745/228471439-74365e34-7cd6-4609-99f0-4feafb18d446.png">



<img width="711" alt="Screenshot 2023-03-29 at 1 47 18 PM" src="https://user-images.githubusercontent.com/51680745/228471476-9d5c5967-ccf8-4e5f-acad-22fa59fea5c2.png">


<img width="1310" alt="Screenshot 2023-03-29 at 1 56 10 PM" src="https://user-images.githubusercontent.com/51680745/228473515-e58d13d2-2001-4176-abc7-9256a6786f00.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.
