### ISSUE TITLE
Layered Navigation Price Step on category ignored for graphQL

### ISSUE THREAD

**Issue by dwsmart** [magento/magento2#37311]
### Preconditions and environment

- version 2.4.6

 

### Steps to reproduce

- set Stores > Catalog > Catalog > Layered navigation  as `Price Navigation Step Calculation` as `Manual`
 Set `Default Price Navigation Step` as `100`, `Maximum Number of Price Intervals` as `25` _(actual numbers don't matter, just for illustration)_
![image](https://user-images.githubusercontent.com/11179452/228550049-a6a44775-cf08-4fce-be1c-c44006bb9905.png)

Save, clear caches and reindex

- on a category, set Display Settings >  Layered Navigation Price Step to 1000, save, clear caches and reindex
![image](https://user-images.githubusercontent.com/11179452/228551092-a936cc22-7399-4d80-945c-a2c8213244b9.png)

### Expected result

the Following Query:

```
{
  products(filter: {category_id: {eq: "108094"}}) {
    aggregations {
      attribute_code
      count
      label
      options {
        label
        value
        count
        __typename
      }
      __typename
    }
    __typename
  }
}

```

Returns price broken down into buckets of 1000

### Actual result

Returns in buckets of `100` _(or whatever you set on the Stores > Catalog > Catalog > Layered navigation level)_

![image](https://user-images.githubusercontent.com/11179452/228552308-33072ea5-a1a2-4134-9a9c-a8ef377cc8c3.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @dwsmart,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce**

<img width="1388" alt="Screenshot 2023-03-30 at 4 41 52 PM" src="https://user-images.githubusercontent.com/51680745/228818505-ee84fd09-45ca-4621-a225-c1cdcfe4fb35.png">



<img width="1384" alt="Screenshot 2023-03-30 at 2 51 33 PM" src="https://user-images.githubusercontent.com/51680745/228818580-7cfb7e91-deea-495e-b247-f795866090cf.png">




<img width="1458" alt="Screenshot 2023-03-30 at 2 51 11 PM" src="https://user-images.githubusercontent.com/51680745/228818618-dc5ea8fd-e06f-4e12-b92b-10fa193524f4.png">


<img width="1367" alt="Screenshot 2023-03-30 at 2 51 23 PM" src="https://user-images.githubusercontent.com/51680745/228818701-ccd6687b-d45b-4ef5-b11e-a3949b36e252.png">



We are getting response and returns in the buckets of `1000`.Kindly let us know if we missing anything.


Thanks.
