### ISSUE TITLE
Category's url key not getting updated if it has subcategory

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37324]
### Preconditions and environment

- Magento version 2.4.6
- Luma theme
- 2 store views 1 greek, 1 english

### Steps to reproduce

1. Create a new sub-category with url key a1
2. Create a new sub-sub-category under a1 with url key b1
3. Url for b1 should now be a1/b1
4. Change url key for a1 to a2 and save
5. Run bin/magento indexer:reindex; bin/magento c:c
6. Check path for sub-category, it's still a1
7. Check path for sub-sub-category, it's still a1/b1
8. Repeat as many times the attempt to change a1 to anything else and you will see it's impossible to change

In the other hand if you try to update the url key for b1 to anything else it's actually updated correctly. So the issue is only if a subcategory has a child sub-category.

For your information my settings in Configuration > Catalog > Catalog > Search Engine Optimization:

Use Categories Path for Product URLs -> No
Create Permanent Redirect for URLs if URL Key Changed -> Yes
Generate "category/product" URL Rewrites -> No

### Expected result

Changing the url key of a subcategory which has children subcategories, should get updated and reflected in frontend.
Also all paths for the children subcategories should get updated too!

### Actual result

Changing the url key of a subcategory which has children subcategories, is not getting updated and stays the same with the first url key ever saved.
Also all paths of the children subcategories stay the same and don't get updated !

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by cptX** [comment]
Something is very fucked up (at least in my system)!
I'm trying to manually correct the urls now but even manually they don't work!!!
For example: I have a page for electric-vehicles. In the english view I created a url rewrite as following:

Request Path: electric-vehicles Target Path: catalog/category/view/id/9

When I request page mysite/en/electric-vehicles page is not loading, firefox says "The page isn’t redirecting properly"
When I request page mysite/en/catalog/category/view/id/9 page is loading fine!
I have checked all the existing url rewrites and no other is conficting with the above!
So i'm clueless and desparate!
Please help, this is critical functionality!

**Comment by cptX** [comment]
Also, is this url rewrites normal for a product?
![image](https://user-images.githubusercontent.com/9040042/229620363-873ef106-e42e-4416-9fdc-7d39b4cd431d.png)
Isn't only the last one necessary? Do I need to have links for all the categories this product belongs to?

**Comment by cptX** [comment]
I'm trying to track down the issue. I now have realized that all the rewrites created for my 2nd store view are not working. Even if I create them manually in the url rewrite table it's impossible to access any english menu (2nd store view): I receive the error "The page isn’t redirecting properly" in my browser.
I have also created a new category which with greek in the first store view works fine, but in the 2nd store view with a different url is not accessible. Note that this category doesn't have any children. I cannot access any page of the second storeview even if I create manually the url rewrite. I'm missing something crucial here... I have checked the database and I cannot find any issue... I really don't understand what is happening and it's really critical as now my second store view is completely inaccessible...

**Comment by cptX** [comment]
It's possible that the cause is the module https://github.com/alex-79/magento2-hide-default-store-code-from-url that I had installed. We need to verify this though because I think this was not affecting the issue mentioned here.

**Comment by engcom-Bravo** [comment]
Hi @cptX,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- 2 store views 1 greek, 1 english
- Create a new sub-category with url key a1
- Create a new sub-sub-category under a1 with url key b1
- Url for b1 should now be a1/b1
- Change url key for a1 to a2 and save
- Run bin/magento indexer:reindex; bin/magento c:c
- Check path for sub-category, it's still a1
- Check path for sub-sub-category, it's still a1/b1
- Repeat as many times the attempt to change a1 to anything else and you will see it's impossible to change

**Magento 2.4.6 Instance**

<img width="1387" alt="Screenshot 2023-04-04 at 3 33 02 PM" src="https://user-images.githubusercontent.com/51680745/229779517-0cee29ca-16db-4917-87a4-1d3cf96eceb8.png">

<img width="1338" alt="Screenshot 2023-04-04 at 3 56 50 PM" src="https://user-images.githubusercontent.com/51680745/229779602-b7c9e420-a992-4aa5-8009-5c6a92420eb0.png">


<img width="1327" alt="Screenshot 2023-04-04 at 3 33 23 PM" src="https://user-images.githubusercontent.com/51680745/229779540-b9adc4e1-50e8-4ea0-a487-f85481e3dc55.png">






**Magento 2.4 develop Instance**


<img width="1331" alt="Screenshot 2023-04-04 at 3 34 47 PM" src="https://user-images.githubusercontent.com/51680745/229779569-1b44e1c0-f87a-4373-877f-5788a1878025.png">




After changing the URL of subcategory which has children subcategories, URL's are updated and it is reflected on frontend.


Kindly let us know if we are missing anything.

Thanks.

**Comment by cptX** [comment]
I'm very sorry if you couldn't reproduce this. Everything looks like the problem was this module  https://github.com/alex-79/magento2-hide-default-store-code-from-url . I have reported the issue to the developer and hope it will be solved. I was not suspecting it as I had it installed in my dev environment several months already but I haven't played much with categories and different url paths. This module breaks the generation of url rewrites for the second store view, thus was impossible to modify them. After unistalling it the functionality is as expected.
Thank you all for checking this. I'm closing the issue now.
