### ISSUE TITLE
The customer group is not changed automatically when VAT is removed from the address

### ISSUE THREAD

**Issue by sevka** [magento/magento2#37360]
### Preconditions and environment

- Magento version 2.4.2, but I believe the bug is relevant for all the versions from 2.4.2 because it was introduced here: https://github.com/magento/magento2/commit/f6bb0228a30f9c12059cce724a522257d6f50d14

- Configure Magento in order to assign the group automatically based on billing address:
  - Customers > Customer Configuration > Create New Account Options:
    - Enable Automatic Assignment to Customer Group = YES
    - Tax Calculation Based On = Billing address
    - Default Group = Ganeral
    - Group for Valid VAT ID - Domestic = B2B (please create this group first)
    - Group for Valid VAT ID - Intra-Union = B2B
    - Validate on Each Transaction = YES

### Steps to reproduce

1. Create a customer
2. Create a default billing address with valid VAT, as a result the customer group is changed to b2b automatically
3. Remove the VAT from the address

### Expected result

The customer group is changed to General.

### Actual result

The customer group is not changed. It still B2B, no matter customer doesn't have the VAT anymore.
As a result, the customer does not pay tax, but he should actually because the customer doesn't have a VAT and should be treated as a private customer.is 

### Additional information

As I said, the bug was introduced here:
https://github.com/magento/magento2/commit/f6bb0228a30f9c12059cce724a522257d6f50d14

If I roll back the change in the app/code/Magento/Customer/Observer/AfterAddressSaveObserver.php it works fine for me.

I implemented a patch which works fine for me:
```
--- ./Observer/AfterAddressSaveObserver.php.org 2023-04-04 18:00:58.000000000 +0200
+++ ./Observer/AfterAddressSaveObserver.php     2023-04-04 18:02:52.000000000 +0200
@@ -141,8 +141,7 @@
             if ($customerAddress->getVatId() == ''
                 || !$this->_customerVat->isCountryInEU($customerAddress->getCountry())
             ) {
-                $defaultGroupId = $customer->getGroupId() ? $customer->getGroupId() :
-                    $this->_groupManagement->getDefaultGroup($customer->getStore())->getId();
+                $defaultGroupId = $this->_groupManagement->getDefaultGroup($customer->getStore())->getId();
                 if (!$customer->getDisableAutoGroupChange() && $customer->getGroupId() != $defaultGroupId) {
                     $customer->setGroupId($defaultGroupId);
                     $customer->save();
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sevka** [comment]
@magento give me 2.4-develop instance

**Comment by sevka** [comment]
Hi @engcom-Dash 
The links provided by magento-deployment-service do not work:

> here is your Magento Instance: https://e219d599b92fc5e05c5cf42d4e7c3b3b.instances-prod.magento-community.engineering/
> Admin access: https://e219d599b92fc5e05c5cf42d4e7c3b3b.instances-prod.magento-community.engineering/admin_5082

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @sevka ,

Verified the issue in 2.4-develop instance,The issue is not reproducible

Preconditions:
Magento version 2.4-develop
PHP 8.1

Steps to reproduce:
1.Install Magento instance
2.Go to stores >Configuration>Customers>Customer configuration
3.Set the below configuration
Enable Automatic Assignment to Customer Group = YES
Tax Calculation Based On = Billing address
Default Group = Ganeral
Group for Valid VAT ID - Domestic = B2B (please create this group first)
Group for Valid VAT ID - Intra-Union = B2B
Validate on Each Transaction = YES
4.Create customer in Customer Option admin panel
5.Enter the VAT Address with default billing address
6.Remove the VAT Address in Billing Address

Kindly refer the below screenshots:
<img width="1511" alt="Screenshot 2023-05-02 at 9 24 43 AM" src="https://user-images.githubusercontent.com/60198592/235934138-1829ef11-0b3a-462b-a47b-da6ec7d54698.png">
<img width="1511" alt="Screenshot 2023-05-02 at 9 27 45 AM" src="https://user-images.githubusercontent.com/60198592/235934166-4f96eda3-3223-46be-92fe-216c29cc278d.png">

The Customers group changed to General when we removing the VAT Address
This is Expected result as per description,Hence the issue is not reproducible,Kindly provide more information if the issue still reproducible.

**Comment by nicolaspernot** [comment]
@magento give me 2.4-develop instance

**Comment by nicolaspernot** [comment]
Looks like this bug is indeed not reproducible on newest Magento 2 versions.
This bug was fixed here : https://github.com/magento/magento2/commit/f231a8d1c633a11e9cc010c1ada0d12c1d613d69

Unfortunately, this fix is only available from M2.4.6.
