### ISSUE TITLE
Content changed by page builder isn't saved

### ISSUE THREAD

**Issue by mnowakCode** [magento/magento2#37428]
### Preconditions and environment

- Magento version: 2.4.4 CE

### Steps to reproduce

1. Set production mode
2. Go to Content -> CMS Blocks/Pages -> choose one -> edit it in page builder
3. Save

### Expected result

Data are save

### Actual result

Data aren't saved, but sometimes are saved. I know it's weird, but it's true. So during the test, please check this a few times.

### Additional information

Earlier we didn't have this issue. But during a lot of changes in our content, this error was shown, and now it's almost all the time

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @mnowakCode,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Set production mode
- Go to Content -> CMS Blocks/Pages -> choose one -> edit it in page builder
- Save


<img width="1457" alt="Screenshot 2023-04-25 at 5 00 12 PM" src="https://user-images.githubusercontent.com/51680745/234282502-53fb7eb7-fe77-4f7f-ab03-a61ac2bfea6a.png">



We are able to save the Data using page builder.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by mnowakCode** [comment]
I forgot to add that we have a multistore webshop. Maybe this is the reason why you can't reproduce this issue.
I'm hoping someone has had a similar problem.

**Comment by mnowakCode** [comment]
I recorded a film with change and save moment, please check that
[page_builder.webm](https://user-images.githubusercontent.com/78545108/234494279-468c6e8a-fb6c-44a5-b485-98e2c81ccc6b.webm)

**Comment by tec655** [comment]
Page builder changes can be difficult to save, especially when there are multiple users working on the same document. In issue #37428, the issue is that the changes made to the page using the page builder are not being saved. This could be due to a number of factors such as a technical glitch, an incorrect setting in the page builder, or incompatibility between the page builder and the platform the page is hosted on. To resolve this issue, it is important to first identify the cause of the problem and then take the necessary steps to rectify it. This could involve consulting a technical specialist in [technical-branch](https://www.pakshaheens.com/navy-technical-branch/), checking the page builder settings, or updating the platform the page is hosted on. Once the problem is identified and fixed, the page builder changes should be saved correctly.

**Comment by mnowakCode** [comment]
I'm closing the issue. The problem is generated by the latest update of the Chrome browser.

**Comment by pknap** [comment]
Hi @mnowakCode,

could you please provide a bit more detail about the Chrome issue? Is there any specific bug reported in their tracker which causes it? Is there any workaround other than using older / different browser?

**Comment by anton-vidext** [comment]
I have been trying to solve the problem for 2 days. In fact, I still haven't succeeded. In production mode the changes are not saved. They are saved about one in ten times. I attach a video with the evidence. Also tried with Firefox and I had the same problem.

[Vídeo Page Builder Problem](https://www.youtube.com/watch?v=r45aaz0PrRw)

**Comment by dcwnaveen** [comment]
any solution for this issue?
Am also facing same issue

**Comment by alicedfisheye** [comment]
@dcwnaveen Try - magento/module-page-builder

```
diff --git a/view/adminhtml/requirejs-config.js b/view/adminhtml/requirejs-config.js
index f7a5d86..e234b84 100644
--- a/view/adminhtml/requirejs-config.js
+++ b/view/adminhtml/requirejs-config.js
@@ -22,6 +22,9 @@ var config = {
         },
         'Magento_PageBuilder/js/resource/jquery/ui/jquery.ui.touch-punch': {
             deps: ['jquery/ui']
+        },
+        'Magento_PageBuilder/js/form/element/wysiwyg': {
+            deps: ['Magento_Ui/js/form/form']
         }
     },
     config: {
```

**Comment by sbailey88** [comment]
Hi @aamoronatti did you manage to fix this? The fix provided by @alicedfisheye was implemented but did not solve our problem.

**Comment by yarshevcgi** [comment]
@engcom-Bravo Why this issue is Closed? Adobe Commerce ver. 2.4.5-p1 having same problems with updating content using page builder, saves successfully only 1 of 10 times, can we have some hotfix for this?
