### ISSUE TITLE
Add to Wishlist with product custom option file upload not working Magento 2.4.6

### ISSUE THREAD

**Issue by sagarmagex** [magento/magento2#37437]
### Summary

**Preconditions and environment**
- Magento: 2.4.6

**Step to reproduce**

- Create a simple product
- Add a custom option file and text
- Options should be required.
![test product _ Products _ Inventory _ Catalog _ Magento Admin](https://user-images.githubusercontent.com/130215107/234768126-aedf846c-916e-4ef7-912b-19825ddb1d54.png)
- Now go to the front end, log in customer, and open the product page.
- Upload file and add text value
- Now click on add to wishlist

### Examples

**Expected result**

- Only a single product should add to the wishlist with selected product custom options.

**Actual result**

- When add to wishlist 2 products will add to the wishlist.
![My Wish List](https://user-images.githubusercontent.com/130215107/234772382-e95a0bf1-10cf-44c2-9156-af623c9f2e1c.gif)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sagarmagex** [comment]
@magento give me 2.4-develop instance

**Comment by sagarmagex** [comment]
@engcom-Bravo I can reproduce an issue in a given instance. Kindly check this product.
https://c66c1d897a7c2bbb7704f6d2c3316b0f.instances-prod.magento-community.engineering/joust-duffle-bag.html

![My Wish List](https://user-images.githubusercontent.com/130215107/234778655-4b9aa0b1-0bf6-47a4-8fad-864e3605f7de.gif)

**Comment by engcom-Bravo** [comment]
HI @sagarmagex,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and Magento 2.4.6 instance and the issue is reproducible.Kindly refer the attached video.

**Step to reproduce**

- Create a simple product
- Add a custom option file and text
- Options should be required.
- Now go to the front end, log in customer, and open the product page.
- Upload file and add text value
- Now click on add to wishlist





https://user-images.githubusercontent.com/51680745/234832727-e41f7b94-f17a-440f-95e8-cbba4576706b.mov





Single Product should be add but Multiple products are adding to wishlist after clicking the add to wishlist.


Hence confirming the issue.


Thanks.

**Comment by rostilos** [comment]
@magento I am working on this
