### ISSUE TITLE
Magento 2.4.6 using a JQueryUI with security vulnerabilities

### ISSUE THREAD

**Issue by Hurrpadurr** [magento/magento2#37488]
### Preconditions and environment

Magento 2.4.6 Community Edition

### Steps to reproduce

1. Install Magento
2. check jQueryUI version that is packed with it

### Expected result

JQueryUI Version 1.13.2 is the latest version without any known security issues.

### Actual result

JQueryUI Version 1.13.1 is installed.

### Additional information

The Security issue I am refering to is CVE-2022-31160.
Apologies if this vulnerability was fixed in the code instead of upgrading the JQueryUI version. I couldn't find any more info on this.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment]
latest code base already upgrade jquery ui to 1.13.2
https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/jquery-ui.js
But i'm not sure it delivery to 2.4.7 or not

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @Hurrpadurr ,

Thanks for contribution and collaboration !

Verified the issue in 2.4-develop instance and 2.4.6 Magento instance and the issue is reproducible, Hence we are confirming the issue.

**Preconditions:**
Magento version 2.4-develop and 2.4.6
PHP version 8.1

**Steps to reproduce:**
1.Install magento instance
2.Go to front end and open developer console toolbar
3.Check jQuery Version using "jQuery.ui.version"

**Kindly refer the Below screenshot:**
<img width="1511" alt="Screenshot 2023-05-12 at 7 21 11 PM" src="https://github.com/magento/magento2/assets/60198592/f7e2232a-ea0a-49e9-836c-05698a72b55c">
<img width="1511" alt="Screenshot 2023-05-12 at 7 22 55 PM" src="https://github.com/magento/magento2/assets/60198592/4d6c7738-2d2c-45b9-91e3-7c090fb22b2d">

jQueryUI version 1.13.1 installed.Hence we are confirming the issue.


Regards,

**Comment by engcom-Dash** [comment]
Hi @Hurrpadurr ,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7775 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-7775&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks
