### ISSUE TITLE
Cart Price Rule is applied while it should not be applied when using the condition 'If an item is NOT FOUND  in the cart with ALL  of these conditions true'

### ISSUE THREAD

**Issue by tools-utrecht-hh** [magento/magento2#37487]
### Preconditions and environment

Magento version 2.4.5-p1

### Steps to reproduce

1. Create a Cart Price Rule with any discount and with the condition 'If an item is NOT FOUND  in the cart with ALL  of these conditions true':
![image](https://github.com/magento/magento2/assets/5173161/f345e4fd-0ccd-40ae-ad49-b307a7403886)
2. Go to the storefront and add sku aaa111bbb222 to the shopping cart
3. Go to the shopping cart and notice that the discount is **not applied**. So far, so good (conditions were not met)
4. Add any other sku to the cart and notice that the discount is **applied**. 

### Expected result

The discount should **not be applied**, since the conditions are not met. sku aaa111bbb222 is still in the cart and the rule should only be applied if this product is not found.

### Actual result

The discount is **applied**.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by experius-nl** [comment]
Please give me the environment.

**Comment by experius-nl** [comment]
Hi @magento, I hereby confirm that this issues is reproducable on the provided Magento instance.

**Comment by engcom-Bravo** [comment]
Hi @experius-nl,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Test-Promotions-Marketing-Magento-Admin (2)](https://github.com/magento/magento2/assets/51680745/c077a29e-a657-4496-b2cb-796f2b9b37c6)


<img width="1432" alt="Screenshot 2023-05-12 at 4 41 35 PM" src="https://github.com/magento/magento2/assets/51680745/c8847cbf-6e01-4843-a491-c65bc84ffc49">


Product with Sku Joust Duffle Bag is excluded and discount is applying for other product.

"Conditions section serves to specify conditions that will be applied to whole cart.
If you want to apply conditions for a certain products you need to set them in Actions tab under "Apply the rule only to cart items matching the following conditions (leave blank for all items)"


Kindly refer this document https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/cart-rules/price-rules-cart-create.html?lang=en#step-2%3A-describe-the-conditions.



<img width="1059" alt="Screenshot 2023-05-12 at 4 45 42 PM" src="https://github.com/magento/magento2/assets/51680745/6c5e7028-e57c-4ff2-954c-3fe1afd86a76">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.



Thanks.

**Comment by dennisvandaalen** [comment]
Hi @magento,
Please use the conditions I have screenshotted in the CONDITIONS tab instead of the ACTIONS tab.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by experius-nl** [comment]
Hi @magento,

Please add the label: Reproduced on 2.4.x

Gr. Dennis (Experius)

**Comment by engcom-November** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment]
Thank you for the response @experius-nl . Verified the behavior again on Magento 2.4-develop instance and 2.4.3-p2 instance and the issue is reproducible on 2.4-develop but not on 2.4.3-p2 instance.
Coupon code is getting applied on both the products from Shopping cart page in Magento 2.4-develop instance
Expected behavior; Coupon code should not be applied which is working fine in 2.4.3-p2 instance.
Hence confirming the issue.
![image](https://github.com/magento/magento2/assets/60198231/a9fcff67-5ac5-42ef-96c6-80c90939c603)
![image](https://github.com/magento/magento2/assets/60198231/4dc410a0-bf4e-4b21-ad02-dbda646900a8)

**Comment by mad-develop** [comment]
Hello fellow investigators,

i could be wrong but i think this commit is propably what caused the issue. [#acaac444c6aa](https://github.com/magento/magento2/commit/acaac444c6aa1d1948356deb555e1d7c8dff0849)

**Comment by Vasudev-22** [comment]
@magento I am working on this

**Comment by hostep** [comment]
Issue got closed without an explanation why?
Possibly fixed by https://github.com/magento/magento2/commit/abf434f3f84bd14bc3c0011949aa0c80b16fb620 (which is related to https://github.com/magento/magento2/issues/37660), but not sure ...

@engcom-November: maybe you can provide more info why this issue got closed?
