### ISSUE TITLE
custom pageSize for admin grid is not used for AJAX request URL after page idling 10 minutes

### ISSUE THREAD

**Issue by yavery** [magento/magento2#37513]
### Preconditions and environment

- M242, Commerce

### Steps to reproduce

1. go to an admin grid with a lot of data, for example: products, customers
2. change the pageSize to 200 or 250, in devtool you can see the AJAX URL is using the custom value
3. load page immediately, you can see the page remembers the custom pageSize and AJAX URL is working as expected
4. let the page idle for 10 minutes
5. reload the page, you can see the page display the custom value in "fitler", BUT in devtool you can see the AJAX URL is using default 20   ~ listing is obviously shorter
6. reload the page again, you can see the page is longer and AJAX is requesting with the correct pageSize

---

Attachment is the element affected:
<img width="451" alt="image" src="https://github.com/magento/magento2/assets/130590250/50cade95-0e83-465b-91bc-834e2f054359">

### Expected result

expect Ajax URL to use the correct pageSize on the first refresh after idling for more than 10 minutes

### Actual result

no error message

### Additional information

This is confusing for the staff, they are now forced to reload the listing page twice

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @yavery,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- go to an admin grid with a lot of data, for example: products, customers
- change the pageSize to 200 or 250, in devtool you can see the AJAX URL is using the custom value
- load page immediately, you can see the page remembers the custom pageSize and AJAX URL is working as expected
- let the page idle for 10 minutes
- reload the page, you can see the page display the custom value in "fitler", BUT in devtool you can see the AJAX URL is using default 20 ~ listing is obviously shorter
- reload the page again, you can see the page is longer and AJAX is requesting with the correct pageSize

AJAX URL using correct page size on the first refresh after idling for more than 10 minutes

<img width="917" alt="Screenshot 2023-05-18 at 12 07 37 PM" src="https://github.com/magento/magento2/assets/51680745/b81aad4c-9e3e-4731-847b-6a2c13b5a2d2">


<img width="663" alt="Screenshot 2023-05-18 at 12 29 40 PM" src="https://github.com/magento/magento2/assets/51680745/eaf5fc6b-c7ea-4327-a5b6-ab9b88cb3706">


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible and provide screenshots it will help us to reproduce.


Thanks.

**Comment by yavery** [comment]
@engcom-Bravo 

Thank you for checking with the develop branch! I can also confirm this is fixed on 2.4.5, however, the bug is occurring on 2.4.2, would it be more reasonable for Magento team to test and fix this for 2.4.2 ?

Develop branch represent the latest development, however most companies using Magento would be on an older specific versions. As you are aware, certain upgrading for larger installation with customization takes major efforts. What if users for some reasons can not immediately upgrade to 2.4.5 or deploy develop branch to their production. They may be forced to live with the issue(s).

May I suggest Adobe release more "patches" for specific versions ?

Regards

**Comment by engcom-Bravo** [comment]
Hi @yavery,

Thanks for your update.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Kindly upgrade to Magento Latest Version.

Thanks.

**Comment by yavery** [comment]
Hi @engcom-Bravo 

You don't need dev branch instance, that's not relevant to this issue

Please see my previous comment:
- this issue seems not present in 245, therefore I speculate it is also fixed for any version afterward including dev branch
- we already upgraded the version to 245 for our own use, this issue is created to report this problem existing for m242

If there is no plan to fix this in 242, we can close this ticket.
