### ISSUE TITLE
PageBuilder rendering slowly after Chrome version 112

### ISSUE THREAD

**Issue by paturiku-p** [magento/magento2#37516]
### Preconditions and environment

- Magento version: 2.4.2-p2, also tested on 2.4.5-p2 and 2.4.6
- PageBuilder is enabled
- Chrome 112 and newer
- CMS page with pagebuilder content

### Steps to reproduce

1. Use Chrome version 112 or above
2. Edit CMS Page, Product or anything that has PageBuilder.
3. Try saving. It takes a long time 20+ seconds (a lot longer than on older versions or in other browsers)

### Expected result

Content is saved as quickly as in other browsers, or older versions of Chrome.

### Actual result

PageBuilder takes a long time to render. PageBuilder is rendering slowly to master template (when content is saved), only on Chrome version 112 and newer.

### Additional information

Also there is an error in console: [ERROR] Page Builder was rendering for 5 seconds without releasing locks.
![image](https://github.com/magento/magento2/assets/29523337/242e0072-cba9-4120-822a-fc8ef475c194)

I have a suspicion that the _applyBindings_ function in _magento/module-page-builder/view/adminhtml/web/js/master-format/render.js_ takes too long to complete.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by paturiku-p** [comment]
Issue confirmed on develop instance: 
![image](https://github.com/magento/magento2/assets/29523337/b9d7252b-2a92-465f-800d-a4037f7eb11a)

On firefox I can save page instantly, but on Chrome it takes a long time.

Chrome version 112.0.5615.165: 
![image](https://github.com/magento/magento2/assets/29523337/de463202-5111-4bc3-a5fa-1997d45fc647)

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @paturiku-p ,

Verified the issue in 2.4-develop instance and the issue is not reproducible.Kindly refer the below screenshots.

<img width="1005" alt="Screenshot 2023-05-19 at 5 42 48 PM" src="https://github.com/magento/magento2/assets/60198592/a0bfb626-d19a-4509-b56f-2589bce4ea00">
<img width="1512" alt="Screenshot 2023-05-19 at 5 47 54 PM" src="https://github.com/magento/magento2/assets/60198592/f0850c85-f07d-4b04-b19f-6b3819ff5076">
<img width="1512" alt="Screenshot 2023-05-19 at 5 49 23 PM" src="https://github.com/magento/magento2/assets/60198592/c26184f8-8dd6-491a-abcc-7ad166796ddb">

Steps to reproduce:
1.Install magento instance
2.Go to CMS page or product and edit with page builder
3.Save

We got error in console even-though Pages or product saved successfully both chrome and Firefox browsers and we are using latest version.

Let us know if we are missing anything!

**Comment by paturiku-p** [comment]
Hi @engcom-Dash 

thank you for checking the issue, the issue is that it takes considerably longer time to save any PageBuilder content on 112+ version of chrome than on other browsers, or older versions of chrome. On firefox I don't get the error that "PageBuilder was rendering for 5 seconds without releasing locks.", the problem isn't that it is impossible to save entities, but the slowdown after updating Chrome. I believe it is caused by some 'optimization' in Chrome and it makes the work of content creators a lot more tedious.

**Comment by paturiku-p** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @paturiku-p ,

Thanks for contribution and collaboration!
verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly recheck the behaviour in 2.4-develop instance.

Kindly refer the below video reference:

https://github.com/magento/magento2/assets/60198592/b1d2675f-4716-46b9-90a7-255d570d12e4

We are trying to save the page-builder with some modifications with latest chrome version of 114 and its saved successfully.
<img width="668" alt="Screenshot 2023-06-08 at 9 41 56 AM" src="https://github.com/magento/magento2/assets/60198592/cdb36041-9888-4962-b44f-1ba36220a19c">

Kindly recheck the behaviour in 2.4-develop instance and let me know if we are missing anything!

Thanks.

**Comment by 0franco** [comment]
Same issue here, just adding more info

- Randomly save fast but most of the time is so slow ~10/20 seconds
- Chrome version: Version 114.0.5735.106 (Official Build) (arm64)
- If you can't reproduce it try saving several times same block/page or edit the content adding random widgets
- No reproducible on my end on Safari v16.5

**Comment by engcom-Dash** [comment]
Hi @paturiku-p ,

We are trying to reproduce the issue in 2.4-develop instance and we are not able to reproduce.Are you still want more investigation kindly let us know.

Thanks.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by chittima** [comment]
I was able to reproduce the issue. Click on Edit with Page Builder and save, try couple of times, issue is reproducible.
Internal team is working on this issue.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @paturiku-p 

Verified the issue in 2.4-develop instance and the issue is reproducible.

Kindly refer the screenshots:
<img width="1512" alt="Screenshot 2023-05-19 at 5 49 23 PM" src="https://github.com/magento/magento2/assets/60198592/3c867c0e-f7d6-4d33-b5f0-d6ae725eacc0">

We are getting Actual result which page builder taking time to render on first time and we got console error as per the description.

Note: This is not happening frequently, it may occurs some time only.

**Comment by hostep** [comment]
@chittima: can you please post the associated commits, so people who want the fix can try to patch it themselves? Thanks! (please never close issues without leaving feedback and links to the commits that fixed it, I've been complaining for the last 3 years about this and it still happens, is quite annoying ...)

**Comment by chittima** [comment]
Hi @hostep here is the commit id https://github.com/magento/magento2-page-builder/commit/69953bcb7f1ac3a793ec7e0b09fc07e680a80856
