### ISSUE TITLE
Admin grid saved filter does not working as expected

### ISSUE THREAD

**Issue by ronak-vaimo** [magento/magento2#37529]
### Preconditions and environment

- Magento version 2.4.5 and 2.4.6
- It's work in older version
- Something went wrong in last 3 commits of bookmarks.js - https://github.com/magento/magento2/commits/2.4-develop/app/code/Magento/Ui/view/base/web/js/grid/controls/bookmarks/bookmarks.js

### Steps to reproduce

Here is video link for reproduce issue.
https://www.loom.com/share/6aa5e2ac56ad40b2b6f07239c8356455

### Expected result

Grid in saved filter work as expected

### Actual result

Actual result you can see in video: https://www.loom.com/share/6aa5e2ac56ad40b2b6f07239c8356455

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @ronak-vaimo,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

Admin Grid filter is working as expected.


https://github.com/magento/magento2/assets/51680745/27f25105-a194-452f-bbd5-efcdbec0b9f2



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by ronak-vaimo** [comment]
Hi @engcom-Bravo 
Can you please check in this magento instance.
Admin access: https://015aa8cea73427ca6d575a1047b07557.instances-prod.magento-community.engineering/admin_3895
Login: 468c953a
Password: 07b278699251

Here you can see some weird.
<img width="1706" alt="image" src="https://github.com/magento/magento2/assets/104133729/54faeb83-7d06-402a-b86c-f5826892c674">

**Comment by engcom-Bravo** [comment]
Hi @ronak-vaimo,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.

In admin grid saved filters are not working as expected.


<img width="1245" alt="Screenshot 2023-05-26 at 12 27 34 PM" src="https://github.com/magento/magento2/assets/51680745/5b2729b5-a8d8-4f89-803d-4f3b39996d0d">




https://github.com/magento/magento2/assets/51680745/37821ec6-4dcd-48d5-bfee-16f2b96ecfaf


Hence Confirming the issue.


Thanks.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by ronak-vaimo** [comment]
If we revert [this](https://github.com/magento/magento2/commit/d2abc271b9e9a0620ebcaa29603f9ae12c796a1a) commit then work but still there is an old issue ACP2E-546

https://github.com/magento/magento2/commits/2.4-develop/app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php

**Comment by chittima** [comment]
Here is the commit id: https://github.com/magento/magento2/commit/debc9fd748485048db2a147719b085a4b2c24672
