### ISSUE TITLE
The Store View selected for sending Welcome email from is not related to the customer's associated website.

### ISSUE THREAD

**Issue by WebHostingAce** [magento/magento2#37540]
### Preconditions and environment

- 2.4.3-p1
- Muti-Store Setup
- Customer "Share Customer Accounts" option selected "Global".

### Steps to reproduce

1. Try to add a Customer to a "Associate to Website" other than the "Default Store".

### Expected result

1. Able to select the "Send Welcome Email From" when add the customer.

### Actual result

1. Unable to select the "Send Welcome Email From" when add the customer.
2. Error - "The Store View selected for sending Welcome email from is not related to the customer's associated website."

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @WebHostingAce,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**


- Try to add a Customer to a "Associate to Website" other than the "Default Store".


We are able to select the **Send Welcome Email From** when we are adding the customer other the default store view and we are get the Emails.



https://github.com/magento/magento2/assets/51680745/92bc8c44-e8b3-41c2-a71d-988247acda13



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by WebHostingAce** [comment]
Hi @engcom-Bravo,

Thank you for looking into this.

Please select "Associate to Website" other than the "Main Website". You will notice the issue.

Sorry for mentioning as the "Default Store".

Thank you!

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @WebHostingAce,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Try to add a Customer to a "Associate to Website" other than the "Default Store".

We are able to select the **Send Welcome Email From** when we are adding the customer other the **MAIN WEBSITE** and we are get the Emails.

<img width="1415" alt="Screenshot 2023-05-26 at 12 18 01 PM" src="https://github.com/magento/magento2/assets/51680745/ab6332ed-e7f7-4edb-857f-36575778ffcf">


https://github.com/magento/magento2/assets/51680745/06e6d732-fbc4-4dc3-b1fb-6fb3188346e3


 Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks

**Comment by WebHostingAce** [comment]
Hi @engcom-Bravo ,

Thank you very much for looking into this.

This issue only reproducible on 2.4.3-p1 not the development branch.

Also I tried this on 2.4.5 and I can confirm this issue no longer exists.

I will check the latest commits and what have been chanced since 2.4.3-p1

Thank you again.

**Comment by perryholden** [comment]
For those who come across this later, this issue is fixed by this commit: https://github.com/magento/magento2/commit/5881e2b36380db438e647b315b2ef80cdd2a23fa
