### ISSUE TITLE
UPS United Parcel Service  issue

### ISSUE THREAD

**Issue by eladius1129** [magento/magento2#37541]
### Preconditions and environment

- Magento 2.4.5 p1

Magento UPS is not working for United Parcel Service type, the API response is getting 302 found error

### Steps to reproduce

1.add product to cart
2.go to checkout 
3.select a shipping address
4. shipping method list are empty and show message  "This shipping method is currently unavailable. If you would like to ship using this shipping method, please contact us".

### Expected result

show shipping method after collect shipping rates

### Actual result

is showing  show message  "This shipping method is currently unavailable. If you would like to ship using this shipping method, please contact us". message error

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jlboban** [comment]
The default UPS CGI gateway [https://www.ups.com/using/services/rave/qcostcgi.cgi](https://www.ups.com/using/services/rave/qcostcgi.cgi) is apparently being shut down.

**Comment by eladius1129** [comment]
@themew , We had to switch to XML using credentials and we're back up and running now.

**Comment by themew** [comment]
Thanks @eladius1129 appreciate it.

Unfortunately, those of us that use UPS.com, Stamps.com, and other discounted shipping methods, since we don't have a shipper number, it seems we can't use XML to retrieve shipping quotes.

This has turned into a much bigger issue than expected, especially if your M2 store only ships UPS and uses a discounter for shipping.   No warning from UPS?!?

**Comment by themew** [comment]
Agree with @engcom-Bravo that this is clearly a UPS issue due to the deprecation of their CGI rate link.  UPS is forcing sites requiring UPS rates to switch to XML and register a UPS and payment method.

I suggest closing this thread as solved since it's not an issue with M2 and UPS customers can implement changes to their UPS accounts and their M2 setting to retrieve UPS rates.
