### ISSUE TITLE
Search suggesions not working on mini search form

### ISSUE THREAD

**Issue by tharindueh** [magento/magento2#37557]
h3. Short issue description

The auto-complete search suggestions on the header's mini search frontend are not functioning properly. They do not populate the suggestions initially. However, after typing in the keyword and then clicking the search icon or pressing "Enter," if we type again in the search bar, it populates a single suggestion. I believe this suggestion is being retrieved from a cache.

Attached for reference screen share video.

Reference screenshot admin panel search suggestions configurations : 

!image-2023-08-23-14-52-40-903.png|width=525,height=658!
### Steps to reproduce
1. Go to the header mini-search form
1. Type the available product name (eg: Jacket) without clicking the search icon.

### Actual results
No search suggestions shown

### Expected results
Show search suggestions with available products when typing product names

### Additional information

I have found the same for git hub issue: 

<https://github.com/magento/magento2/issues/37557>

Also AC ticket: 

https://jira.corp.adobe.com/browse/AC-9145

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
HI @tharindueh,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Go to the header mini-search form
- Type the available product name without clicking the search icon.

In frontend also it is showing suggestions while searching without clicking on search icon.

https://github.com/magento/magento2/assets/51680745/067dc6eb-e478-428d-acc2-a2f733f8b83a



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by tharindueh** [comment]
Hi @engcom-Bravo 

Thank you for the update. I checked again with a different instance. the same issue was there. 
In your instance, it might be a cached result. 

When we type one product in the mini search form and then click the search icon or press enter, the product name will be cached. Then it appears as a suggestion when typing. 
Please check below video

https://github.com/magento/magento2/assets/44543372/014bb841-4a3f-4885-a4d3-2038ae6d08a7

Any comment, please?

**Comment by indunie** [comment]
Hi @engcom-Bravo @tharindueh,

Any solution for this? 
I am having the same issue in multiple instances in 2.4.5 / 2.4.6 community edition.

Thanks

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @tharindueh,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Go to the header mini-search form
- Type the available product name without clicking the search icon





https://github.com/magento/magento2/assets/51680745/5ab0d046-30dc-4952-adca-3486aff3da57



No search suggestions are showing for the product.but it is showing for when the product is cached.

Hence confirming the issue.


Thanks.

**Comment by o-iegorov** [comment]
Internal Adobe team start working on the issue

**Comment by chittima** [comment]
Here is the commit id: https://github.com/magento/magento2/commit/4ebff941b139c4fa64813f6f58ef40224535a115

**Comment by Kishorchhugani** [comment]
I am facing same issue on my Magento 2.4.7 version.
any updates?

**Comment by bhushanmeetanshi** [comment]
look product search result count is not showing 
[screen-capture.webm](https://github.com/magento/magento2/assets/109195906/00593e00-7418-4546-bc11-602fd4ae26c5)

Why are you all closing the issue without any confirmation from the user side....

**Comment by bhushanmeetanshi** [comment]
Look i am also facing the issue. search product count not visible in magento 247

[screen-capture.webm](https://github.com/magento/magento2/assets/109195906/844fe43c-d609-4b23-bf95-765fc1eefc06)

Why are you closing the issue without Issue reporter confirmation???. Thats not helping to anyone... doesn't it???

**Comment by bhushanmeetanshi** [comment]
@engcom-Bravo Please look into this matter. The product count in the mini search form has mysteriously vanished from the old version to the new one. It's as if the functionality decided to play hide-and-seek without leaving a forwarding address!

**Comment by bhushanmeetanshi** [comment]
It seems that reopening the issue while commenting is like trying to high-five yourself—not gonna happen!

Am I Correct @engcom-Bravo ???

**Comment by indunie** [comment]
hello @engcom-Bravo,  @o-iegorov , @chittima 
Any update on this issue?
Was this been fixed?

**Comment by engcom-Bravo** [comment]
Hi @tharindueh,

We have reverified the issue in Latest 2.4-develop instance and we are not able to reproduce the issue.Kindly refer the screenshots.


<img width="1411" alt="Screenshot 2024-12-20 at 4 15 30 pm" src="https://github.com/user-attachments/assets/3e47d677-ab82-4efc-968e-bacd04775177" />



Search Suggestions are working fine via mini search form with product count as well.

Thanks.
