### ISSUE TITLE
Images Not Showing in Insert Image Section

### ISSUE THREAD

**Issue by intheshallow** [magento/magento2#37565]
### Preconditions and environment

- Magento version: 2.4.6

If you go into a Static Block and click on Insert Image... the entire section is blank. No images populate.

### Steps to reproduce

1. Click into Content - Elements - Blocks
2. Choose any block to edit.
3. Click Insert Image...

### Expected result

You should see all images previously uploaded into folders. I have hundreds from previous Magento versions.

### Actual result

You do not see any previous images at all. It's completely blank.

![magento-issue](https://github.com/magento/magento2/assets/4449132/ce74da9a-5e0b-4785-9a73-13f15c9214e1)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment]
My 2.4.6 works fine, however I notice you have an active filter, do the images display when you clear the filter?

**Comment by engcom-Bravo** [comment]
Hi @intheshallow,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshot.


**Steps to reproduce**

- Click into Content - Elements - Blocks
- Choose any block to edit.
- Click Insert Image...

We are able to see the images which was previously uploaded.


![Home-Page-Block-Blocks-Elements-Content-Magento-Admin](https://github.com/magento/magento2/assets/51680745/ee95f1a0-6bad-48ff-acdc-0d8bddfdaf7d)



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by intheshallow** [comment]
I cleared out my filter. I also made sure to disable all third party extensions and use Magento Luma. Still the same result. Now I can see any image I uploaded AFTER switching to Magento 2.4.6. But any image from 2.4.5-p1 and back, I cannot see any image at all. I have 10 other sites and they are all having the same exact problem. Most of them are from a migration, and I have 2 that were fresh installs. Yet all of them do not show any preview of images uploaded from previous Magento versions.

![magento-issue-3](https://github.com/magento/magento2/assets/4449132/eefa3dd4-11d8-4803-9241-77c1c076c07e)

You can see I have no filter chosen and that the images are in the correct folder within my SFTP.

**Comment by devchris79** [comment]
May be related to [this](https://magento.stackexchange.com/questions/330864/magento-2-media-gallery-doesnt-show-any-images-in-2-4-1) and the gallery needs a sync command.

**Comment by intheshallow** [comment]
Ah that did it! I had to run that sync command in SSH. I'm closing this.
