### ISSUE TITLE
Impossible to edit a Widget with PageBuilder after it is saved once

### ISSUE THREAD

**Issue by vbidou** [magento/magento2#37564]
### Preconditions and environment

- Magento version: 2.4.6
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Navigate to Content on Back-End (for example Home page)
2. Open Page Builder
3. Create a ProductsList widget.
4. Save it and exit.
5. Re-enter the PageBuilder.
6. Try to edit the Widget.

### Expected result

When mouseover the widget section the menu to Edit should appear.

### Actual result

No Edit menu appears on mousover the widget section.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by vbidou** [comment]
I tested on your Magento instance server and the widget seems to work...
![image](https://github.com/magento/magento2/assets/44623543/d0dc0452-ceea-4c08-9d69-5cfa6c4b3cc4)

On my Magneto 2.4.6, here is what I see...
![image](https://github.com/magento/magento2/assets/44623543/906966ad-c28d-4ddd-bee5-c4b7a74f5a35)

**Comment by vbidou** [comment]
For information, the widgets which doesn't show are from this section of PageBuilder:
![image](https://github.com/magento/magento2/assets/44623543/daf64bd8-665e-49ee-a8ed-a536f8bb2b6a)

**Comment by engcom-Bravo** [comment]
Hi @vbidou,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Navigate to Content on Back-End (for example Home page)
- Open Page Builder
- Create a ProductsList widget.
- Save it and exit.
- Re-enter the PageBuilder.
- Try to edit the Widget.

When mouseover the widget section the menu to Edit section is appeared successfully.



https://github.com/magento/magento2/assets/51680745/4e6282d3-4c69-46fc-a826-20e5ddf943a0



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.
Thanks.

**Comment by vbidou** [comment]
Update: The issue happened after switching Magento from Production mode to developper mode. As we can't replicate the issue, we are recovering backup to better understand the root cause.

**Comment by jerry32410** [comment]
Widget Locking: Some PageBuilders have a feature that locks widgets once they have been saved to prevent accidental modifications. This can be done to maintain consistency and prevent unintended changes to the layout. Check if there is an option to unlock or edit the widget within the PageBuilder's settings or toolbar.

Widget Versioning: PageBuilders sometimes create different versions of the widget when saved. Ensure that you are attempting to edit the latest version of the widget. Look for options to switch between different versions or check if there is a version history feature within the PageBuilder.

Cache and Browser Issues: Clear your browser cache and refresh the page of[ how-to-play-mini-militia](https://minimilitiapk.com/how-to-play-mini-militia/). Cached files can sometimes interfere with the editing functionality of the PageBuilder. Additionally, try accessing the PageBuilder in a different browser or incognito mode to rule out any browser-related issues.

Plugin or Theme Conflicts: In some cases, conflicts between the PageBuilder, plugins, or themes can cause editing issues. Disable any recently installed plugins or switch to a default theme temporarily to see if the problem persists. If the issue is resolved, you can narrow down the conflicting plugin or theme by reactivating them one by one.

**Comment by engcom-Bravo** [comment]
Thanks for your contribution & collaboration over here @jerry32410 

Hi @vbidou,

Thanks for your update.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We have checked after switching Magento from Production mode to developper mode.


<img width="1450" alt="Screenshot 2023-06-05 at 3 08 23 PM" src="https://github.com/magento/magento2/assets/51680745/e9915901-31bf-401e-bff2-e79ce1f9a5a2">



<img width="1436" alt="Screenshot 2023-06-05 at 3 06 21 PM" src="https://github.com/magento/magento2/assets/51680745/173c1994-faef-428e-aa60-c6c7179be98d">


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by vbidou** [comment]
Dear Team, 
After long and deep investigations, we have identified that the issue was due to 2 aheadworks extensions which affected the pagebuilder javascript. The issue was pushed to their dev department for a fix. This iussue can be marked as resolved for now.
Thanks for your support in determining that it is not a core Magento script issue.
Best regards
