### ISSUE TITLE
Authentication does not work with Elasticsearch8

### ISSUE THREAD

**Issue by fnievesf** [magento/magento2#37602]
### Preconditions and environment

- 2.4.6 CE
- Elasticsearch server 8.4.3

Elasticsearch configuration:
xpack.security.enabled: true

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.client_authentication: required
xpack.security.transport.ssl.keystore.path: *****

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: *****

### Steps to reproduce

1. Deploy elasticsearch v8.4.3
2. Configure Magento to use elasticsearch8 in `Catalog > Catalog > Catalog Search`
<img width="570" alt="image" src="https://github.com/magento/magento2/assets/136321064/bae59da8-9e76-4c33-97b8-1c3319188dca">

3. Run `bin/magento setup:upgrade`
4. Run `bin/magento indexer:reindex`

### Expected result

bin/magento setup:upgrade and bin/magento indexer:reindex ends without errors

### Actual result

`Could not validate a connection to Elasticsearch. Verify that the Elasticsearch host and port are configured correctly` when we run bin/magento setup:upgrade.

`Indexer handler is not available: elasticsearch8` when we run bin/magento indexer:reindex.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @fnievesf,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.

Please try to install elasticsearch with setup : install command.Kindly check this document https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/advanced.html

`bin/magento setup:install --base-url=[http://magento246.local](http://magento2.local/) --db-host=localhost --db-name=magento246 --db-user=global --db-password=Global@123 --admin-firstname="admin" --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=admin123 --language=en_US --currency="USD" --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin --search-engine=elasticsearch8 --elasticsearch-host=localhost --elasticsearch-port=9200 --elasticsearch-username=magento --elasticsearch-password=guest`

We have configured Magento instance with Elasticsearch8 using this document https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch


<img width="1250" alt="Screenshot 2023-05-02 at 1 36 53 PM" src="https://user-images.githubusercontent.com/51680745/235613925-245ec214-4523-47cd-901d-ace093077262.png">



<img width="784" alt="Screenshot 2023-05-02 at 1 46 48 PM" src="https://user-images.githubusercontent.com/51680745/235615096-665e1dc8-56df-42c8-a1ec-a84fa22484c8.png">


<img width="1047" alt="Screenshot 2023-06-12 at 4 15 37 PM" src="https://github.com/magento/magento2/assets/51680745/0445f1e8-a546-4d1e-afa4-4af0f22e78bb">



Both the `bin/magento setup:upgrade` and `bin/magento indexer:reindex` ends without errors.

Kindly recheck the behavior on Magento 2.4.6 instance and elaborate steps to reproduce if the issue is still reproducible.


Please let us know if you are still facing any issue.

Thanks.

**Comment by fnievesf** [comment]
Could you provide me with your Elasticsearch configuration?

I'm trying to install Elasticsearch and vanilla on Docker. Specifically, I want Elasticsearch to run in a separate container, but I'm having trouble getting it to work.

<img width="719" alt="image" src="https://github.com/magento/magento2/assets/136321064/0339cfeb-e6bc-4eb2-a3cb-9889f2d51680">

**Comment by engcom-Bravo** [comment]
Hi @fnievesf,

Thanks for your update.


Below is the our Elastic search Configuration :

<img width="1368" alt="Screenshot 2023-06-15 at 12 17 59 PM" src="https://github.com/magento/magento2/assets/51680745/e7e955c2-e336-4537-9a09-d4dafdc48d2f">



<img width="602" alt="Screenshot 2023-06-15 at 12 19 07 PM" src="https://github.com/magento/magento2/assets/51680745/149b4473-71c0-482a-bea2-75eb7e0cdbe8">



Kindly refer this document https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html for configuring elastic search and please let us know if you are still facing any issue.


Thanks.

**Comment by fnievesf** [comment]
Hi, I noticed that you have 'xpack.security.enabled' set to 'false'. Could you test setting this to 'true'?

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @fnievesf,

Thanks for your update.

we have tried with 'xpack.security.enabled' set to 'true' still we are not able to reproduce the issue.We have upgraded the elastic search to latest version.


<img width="681" alt="Screenshot 2023-06-19 at 6 42 06 PM" src="https://github.com/magento/magento2/assets/51680745/bfb05135-05f7-486a-a80d-a853120d9d63">



<img width="657" alt="Screenshot 2023-06-19 at 6 43 55 PM" src="https://github.com/magento/magento2/assets/51680745/cff11108-8175-40b1-99cd-e9fc93c9bd07">



<img width="733" alt="Screenshot 2023-06-19 at 6 44 51 PM" src="https://github.com/magento/magento2/assets/51680745/14098ffa-a69a-4fa2-a26e-c4e3e744810a">


Both the bin/magento setup:upgrade and bin/magento indexer:reindex ends without errors.


Kindly let us still if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @fnievesf,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
