### ISSUE TITLE
Synonyms don't work correctly when using "Minimum Terms to Match" using Elasticsearch

### ISSUE THREAD

**Issue by rvm-pmis** [magento/magento2#37647]
### Preconditions and environment

- Magento version 2.3.7-p4
- Elasticsearch 7.17.5

Also reported in https://github.com/magento/magento2/issues/35141 with magento 2.4.3, but closed there due to lack of response from the bug reporter and inability to reproduce, because of a testcase that didn't trigger the issue..

### Steps to reproduce

1. Define synonym group (eg laptop,notebook,macbook)
2. Have product with name "New notebook" and another product with name "New notebook macbook"
3. Use Elastichsearch 7 as search engine
4. Set "Minimum Terms to Match" to a value (eg 2 or 75% or 2<75%)
5. Search in frontend on "notebook" or "laptop" or "macbook"

### Expected result

Both products show up in search results

### Actual result

Only the product "New notebook macbook" is found.

What appears to happen is that if you search for "laptop" it sends search terms "laptop", "notebook" and "macbook" (laptop + synonyms) to elasticsearch. Due to the Minimum terms to match that resolves to 2, it requires at least two of out of three to match, so the product that contains only one of the synonyms doesn't match the criteria.

We've currently had to stop using synonyms to avoid this issue.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rvm-pmis** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by rvm-pmis** [comment]
@engcom-Dash I seem to have lost my develop instance. Here's what I tried to do:

Without any changes, if I search for these three key words, these are the products that are found:

Rival:

- Rival Field Messenger

Wayfarer:

- Wayfarer Messenger Bag

Messenger:

- Rival Field Messenger
- Wayfarer Messenger Bag
- Push It Messenger Bag
- Strive Shoulder Pack

Stores => configuration => catalog => catalog search:
- search engine: elasticsearch 7
- minimum terms to match: 2<75%
Marketing => search synonyms => new synonymgroup: rival,wayfarer,messenger
System => cache management => flush magento cache.

At this point I would like to reindex the indexes... but can't find how to do this. Perhaps it is reproducible with opensearch as well, but I lost the development instance at this point

My guess is that after these changes, searching for "rival" would only give "Wayfarer Messenger Bag" as a result.

**Comment by rvm-pmis** [comment]
@engcom-Dash I borrowed your development instance. Tested with opensearch (assuming it's similar enough to elasticsearch to test this)... got an unexpected result. Searching for 'rival' gives 3 results, but I would expect 4 results, because 'messenger' is among the synonyms of 'rival' and searching for 'messenger' gives 4 results. The fourth result (that doesn't show when searching for 'rival' with synonym 'messenger') is the product named "Strive Shoulder Pack" (it has the word "messenger" in the "more information" tab, under "style").

**Comment by engcom-Dash** [comment]
@magento give me 2.3.7-p4 instance

**Comment by engcom-Dash** [comment]
Hi @rvm-pmis ,

Verified the issue in 2.4-develop instance and the issue is not reproducible.

Kindly refer the below screenshots:
<img width="1509" alt="Screenshot 2023-06-22 at 4 25 49 PM" src="https://github.com/magento/magento2/assets/60198592/ac85f8a5-c4f1-4dae-9f12-675b201055cf">
<img width="1509" alt="Screenshot 2023-06-22 at 4 26 01 PM" src="https://github.com/magento/magento2/assets/60198592/e772a4f6-04eb-4de0-a8f6-0e6f84e9bfa0">
<img width="1509" alt="Screenshot 2023-06-22 at 4 26 21 PM" src="https://github.com/magento/magento2/assets/60198592/ad6064cb-4e3a-42fe-a35e-4e93580821b5">

steps to reproduce:
Go to stores>Configuration>Catalog>Catalog serach
Set serach engine As Elasticsearch7
Set "Minimum Terms to Match" to a value (eg 2 or 75% or 2<75%)
Create product with name "New notebook" and another product with name "New notebook macbook"
Search in frontend on "notebook" or "laptop" or "macbook"

while we are searching the products in front end both the products available.Kindly recheck the behaviour in 2.4-develop instance.

Kindly let us know if we are missing anything!

Thanks

**Comment by rvm-pmis** [comment]
@magento give me 2.3.7-p4 instance

**Comment by rvm-pmis** [comment]
@magento give me 2.3.7-p4 instance

**Comment by rvm-pmis** [comment]
@magento give me 2.3.7-p4 instance
... pretty please with a cherry on top ;)

**Comment by rvm-pmis** [comment]
Would've like to double check in vanilla 2.3.7-p4, but can't seem to get a development instance.
Anyway, seems to work in the most recent 2.4 branch, so that's fine. Closing the ticket. Thanks for testing.
