### ISSUE TITLE
REST api: Product updated_at doesn't change when product's stock is updated via api

### ISSUE THREAD

**Issue by cykolln** [magento/magento2#37670]
### Preconditions and environment

- Magento version: 2.4.3
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Using a test store with a product, make the following requests in Postman: 

1. Acquire access token for auth
2. Update the inventory for the product to 500 using the following request: 
PUT `https://store-example/rest/default/V1/products/{SKU}/stockItems/{ITEM ID}`

where the request body is: 
```
{
    "stockItem":{
    "item_id": {ID}
    "product_id": {ID},
    "stock_id": 1,
    "qty": 500,
    "is_in_stock": true,
    "is_qty_decimal": false,
    "show_default_notification_message": false,
    "use_config_min_qty": true,
    "min_qty": 0,
    "use_config_min_sale_qty": 1,
    "min_sale_qty": 1,
    "use_config_max_sale_qty": true,
    "max_sale_qty": 10000,
    "use_config_backorders": true,
    "backorders": 0,
    "use_config_notify_stock_qty": true,
    "notify_stock_qty": 1,
    "use_config_qty_increments": true,
    "qty_increments": 0,
    "use_config_enable_qty_inc": true,
    "enable_qty_increments": false,
    "use_config_manage_stock": true,
    "manage_stock": true,
    "low_stock_date": null,
    "is_decimal_divided": false,
    "stock_status_changed_auto": 0
}}
```
3.  Make the following request to retrieve products updated within the last day:
GET https://store-example/rest/default/V1/products?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]=2023-06-26T00%3A00%3A00&searchCriteria[filter_groups][0][filters][0][condition_type]=gteq&searchCriteria[filter_groups][1][filters][0][field]=updated_at&searchCriteria[filter_groups][1][filters][0][value]=2023-06-26T23%3A59%3A59&searchCriteria[filter_groups][1][filters][0][condition_type]=lt&searchCriteria[sortOrders][0][field]=updated_at&searchCriteria[sortOrders][0][direction]=DESC&searchCriteria[currentPage]=1&searchCriteria[pageSize]=50

### Expected result

I expect that if a product's stock is updated, the product's updated_at value will be as well. When I update a product's stock using the admin UI, the product will successfully be returned in the filtered /search request. 

### Actual result

The product updated in the first request is not returned from the /search request. 

### Additional information

This is vital for integrations that sync magento 2 catalog items and are reliant on filtered `/products/search` endpoint request to correctly return products that have been updated within a sync window. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @cykolln,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Using a test store with a product, make the following requests in Postman:

- Acquire access token for auth
- Update the inventory for the product to 500 using the following request:
- PUT https://store-example/rest/default/V1/products/{SKU}/stockItems/{ITEM ID}
- Make the following request to retrieve products updated within the last day:




<img width="1336" alt="Screenshot 2023-06-27 at 12 58 59 PM" src="https://github.com/magento/magento2/assets/51680745/8df8d2e3-7b5b-4b36-9a10-7eaf07b4ccb0">


Product is not getting when we are updating API request.We are not getting response for that particular product.

<img width="1423" alt="Screenshot 2023-06-27 at 1 00 38 PM" src="https://github.com/magento/magento2/assets/51680745/35c5af27-e9d4-42bb-ab10-4ae1f742e6b2">


When we update same product in the admin we are getting response as below.

<img width="1192" alt="Screenshot 2023-06-27 at 1 03 42 PM" src="https://github.com/magento/magento2/assets/51680745/e6e51ddd-2968-4040-8f78-6b3c9856fd2d">




Hence Confirming the issue.


Thanks.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by thiagosn** [comment]
Hi, is there any resolution? I have the same problem

**Comment by cykolln** [comment]
@Kannakiraj123 is there an update here? 🙏
