### ISSUE TITLE
Product Media Gallery GQL response is not sorted by image position

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#37671]
### Preconditions and environment

- Magento version: 2.4-develop

### Steps to reproduce

1. Edit the prdouct
2. Add images
3. Save it
4. edit the same product and this time drag the last image to the very first
5. save the productproduct

### Expected result

GraphQl response should return the gallery sorted by their position.

### Actual result

Gallery images are sorted by their IDs.

### Additional information

Use this Query:

````
{
  products(filter: { sku: { eq: "24-MB01" } }) {
    items {
      name
      sku
      url_key
      stock_status
      media_gallery {
              __typename
              ... on ProductVideo {
                video_content {
                  video_url
                  video_title
                  __typename
                }
                __typename
              }
              ... on ProductImage {
                url
                __typename
              }
            }
    }
    total_count
    page_info {
      page_size
    }
  }
}

````

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @adarshkhatri,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Edit the prdouct
- Add images
- Save it
- edit the same product and this time drag the last image to the very first
- save the productproduct


<img width="1321" alt="Screenshot 2023-06-28 at 2 43 47 PM" src="https://github.com/magento/magento2/assets/51680745/9be783fb-105b-4010-839b-5b5f0efc759b">



<img width="1485" alt="Screenshot 2023-06-28 at 2 40 00 PM" src="https://github.com/magento/magento2/assets/51680745/54b1542a-8489-477a-9971-6d99eb24d635">


We are not getting response as per the position of the images.we are getting as per their ID's.


In frontend it is working fine as per sorting of the images.


<img width="1427" alt="Screenshot 2023-06-28 at 3 43 05 PM" src="https://github.com/magento/magento2/assets/51680745/bc5d6635-455b-4177-a9db-d9baee6b5fe5">


Hence Confirming this issue.

Thanks.

**Comment by Kannakiraj123** [comment]
@magento I am working on this

**Comment by thiaramus** [comment]
This issue is under development by an internal team. The fix will be delivered to the mainline according to our processes once done, and the status of this issue will be updated. If there are any incomplete Pull Requests to this issue and the community code will be re-used, all original commits will be preserved.
