### ISSUE TITLE
EAV attribute backend model 'ArrayBackend' filters non numeric values

### ISSUE THREAD

**Issue by DiskoPete** [magento/magento2#37675]
### Preconditions and environment

- Magento ^2.4.6

### Steps to reproduce

1. Create a new product attribute eg 'foobar' with
 - a `\Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend` backend model
 - a custom source model which has non numeric option values
2. Save the product with changed attribute 'foobar' values (eg through a REST API call)

### Expected result

Changed/new attribute values are saved to the product.

### Actual result

Attribute values are not saved

### Additional information

The non numeric values are filtered here and won't be saved:
https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Eav/Model/Entity/Attribute/Backend/ArrayBackend.php#L67

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by DiskoPete** [comment]
@magento I am working on this

**Comment by DiskoPete** [comment]
@magento add to contributors team

**Comment by DiskoPete** [comment]
@magento I am working on this

**Comment by engcom-November** [comment]
Hello @DiskoPete,

Thank you for reporting and collaboration!

We have tried to reproduce the issue on 2.4-develop, We found that the custom attribute value is not being saved and is being deleted when we try to change the value from REST API call, There is already an issue on Custom attribute being deleted.
The issue is open, Please refer to https://github.com/magento/magento2/issues/37426 for more information.

You can refer the below screenshots
![image](https://github.com/magento/magento2/assets/60198231/30e82594-908b-4ba6-9d95-273f6291d3f6)
![image](https://github.com/magento/magento2/assets/60198231/75f7df54-5f0f-4997-94f6-7778731265f9)


After using PUT to change custom attribute value, The custom attribute is being deleted.
<img width="1402" alt="image" src="https://github.com/magento/magento2/assets/60198231/2438ea56-f6dc-42b5-8436-76f9142391fa">
<img width="1396" alt="image" src="https://github.com/magento/magento2/assets/60198231/e287dea8-abe2-4037-91cc-b647cd9981ee">


Hence putting the Issue on hold.
Please let us know if we are missing something.

Thanks.

**Comment by DiskoPete** [comment]
Hi @engcom-November 

Thanks for your feedback.
I agree that the mentioned [issue](https://github.com/magento/magento2/issues/37426) is connected.

The fix I prepared will probably also solve the other issue.
https://github.com/magento/magento2/pull/37677

**Comment by abukatar** [comment]
Hello @DiskoPete 
 
Thank you for your contribution and collaboration!
 
An internal Magento team is working on this issue right now (as Jira ticket `ACP2E-2647`).

**Comment by abukatar** [comment]
@magento I'm working on it

**Comment by asim-blueprintprep** [comment]
This ticket is closed, but the linked MR is still open...does anyone have a link the the MR that fixed this issue?
