### ISSUE TITLE
Preview email template image not respect correct theme store image

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#37775]
### Preconditions and environment

- Magento version 2.4.5+
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1.  Create theme (extend blank) + create image inside web/images
2.  Setup theme in admin
3.  Create template email for theme (any email such as order/invoice)
4. Add image with url directive view
```html
<img src='{{view url="images/abc.png"}}' alt="" />
```
5. Click preview template

### Expected result

Image load ok. Image path correct with theme path

### Actual result

Image broken. Image path load incorrect theme path
<img src="https://i.imgur.com/0uE8Fg5.png"/>

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment]
Hello @mrtuvn,

Thank you for report and collaboration!

We have tried to reproduce the issue on 2.4-develop.
The issue is not reproducible for us.
Please look at the screenshot for reference:
![image](https://github.com/magento/magento2/assets/60198231/5de1d8c0-7983-494d-9208-b5b438469f08)
![image](https://github.com/magento/magento2/assets/60198231/27e5dcb7-24a8-40c0-8bf1-56e9140efdcf)

Please let us know if we are missing something.

Please find below the Custom theme for reference: 
[CustomTheme.zip](https://github.com/magento/magento2/files/12169352/CustomTheme.zip)

Thanks.

**Comment by mrtuvn** [comment]
you need add custom theme extend luma theme
Step 2 create theme/store for that theme
Step 3 create email template for use only theme previous created
Step 4 In template call to image store in theme luma

**Comment by magenizr** [comment]
How about adding this snippet to the header template and using `src="{{var logo_url}}"` just like in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Email/view/frontend/email/header.html

This should work as expected because `logo_url` is defined per store.

`$variables['logo_url'] = $this->getLogoUrl($storeId);`

**Comment by mrtuvn** [comment]
header totally same as default core. I dont' change to that area. The scenario only for import image. Logo case works fine with me

**Comment by engcom-November** [comment]
Hello @mrtuvn,
Thank you for quick response!

We have followed the same steps as you mentioned in :

> you need add custom theme extend luma theme (You zip theme correct) Step 2 create theme/store for that theme Step 3 create email template for use only theme previous created Step 4 In template call to image store in theme luma Note in your file theme zip contain image but it's difference with my test case. Image must stay in theme luma (parent) not place theme child. The important thing image must stay in parent theme.
> 
> CC: @engcom-November can you recheck my scenario

Changed the image path from the custom theme to parent theme(luma), still we are getting the expected result.
Please refer the screenshot below:
Here the image is in parent theme
![image](https://github.com/magento/magento2/assets/60198231/ed239bf8-01db-4e65-8057-696184426e9f)
Still we are able to get the image in preview template.

Please let us know if we are missing something.
Thank you.
