### ISSUE TITLE
[M2.4.6-p1] Can't create an order in admin. I'm getting redirect to the store selection randomly

### ISSUE THREAD

**Issue by gmachure** [magento/magento2#37773]
### Preconditions and environment

When you have multiples stores, you have the store selection when you create an order in admin, just after customer selection. Randomly, after you've selected a store, the page reload and instead of getting the product selection step, you get redirected to the store selection again.

<img width="619" alt="image" src="https://github.com/magento/magento2/assets/25632159/4f6ed4bd-3063-4beb-834e-34766ebbdf9c">

Reproduced on M2.4.6-p1.

### Steps to reproduce

On magento 2.4.6-p1 vanilla : 
1. Go to admin
2. Create a new store view and add it to the default website
3. Create a random customer
Create an order : 
5. Once you have selected the customer for the order, you are on the store selection. Select a random store.
6. If you are on the product selection, click "Cancel button" to go back to the store selection 
7. Repeat step 5 and 6.

### Expected result

After selecting a store, I should always go to the product selection.

### Actual result

Randomly, I stay on store selection after I selected a store.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @gmachure,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**



- Go to admin
- Create a new store view and add it to the default website
- Create a random customer
- Create an order :
- Once you have selected the customer for the order, you are on the store selection. Select a random store.
- If you are on the product selection, click "Cancel button" to go back to the store selection
- Repeat step 5 and 6.



https://github.com/magento/magento2/assets/51680745/1f1020b5-f333-4cca-aa08-c29bc086fce1



After selecting the store we are able to go the product selection page.

This issue is fixed under in this commit d617644 Target version 2.4.7-beta1.

Please let us now if you are still facing any issue.

Thanks.

**Comment by usuyukiso** [comment]
The same was reproduced for me, although I cannot proceed to the product selection, I am returned to the store selection 90% of the cases (sometimes randomly I still can proceed to the product selection)
Noticed the following error in the system and debug.log:
`report.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'm246ee.catalog_category_product_index_store0' doesn't exist, query was: SELECT `main_table`.*, IFNULL(wishlist.name, 'Wish List') AS `wishlist_name` FROM `wishlist_item` AS `main_table`
 INNER JOIN `wishlist` ON main_table.wishlist_id = wishlist.wishlist_id
 INNER JOIN `catalog_category_product_index_store0` AS `cat_index` ON cat_index.product_id = main_table.product_id AND cat_index.category_id = '0' AND cat_index.visibility IN (3, 2, 4) WHERE (wishlist.customer_id = 1) AND (`main_table`.`store_id` IN('0')) [] []`

**Comment by gmachure** [comment]
Hi @engcom-Bravo

I patched my magento 2.4.6-P1 with this commit [d617644](https://github.com/magento/magento2/commit/d6176449f759a8bd535693cdf2971aed5a14e4c3) and i don't reproduce anymore. I'll remove the patch once the 2.4.7 releases officially 

Thanks!
