### ISSUE TITLE
HTML characters not rendered in thumbnail popup

### ISSUE THREAD

**Issue by drinkingsouls** [magento/magento2#37781]
### Preconditions and environment

- 2.4.6-p1

### Steps to reproduce

1. Go to Catalog > Products (Product Grid)
2. Find a product with a html character such as quotes " for this example.
3. Click on the image thumbnail

**Product Grid**
Product name contains quotes and displays correctly here
![prod-grid](https://github.com/magento/magento2/assets/45666862/82b411b1-2dcf-491d-ba45-c29c12da56f9)

When Product thumbnail is clicked the lightbox does not render the quote characters. Shows `&quot;` instead of the character.
![popup](https://github.com/magento/magento2/assets/45666862/a2318e13-0f96-4c95-b5d1-2575d2b47038)

Same thing happens with other characters such as & (ampersand)

### Expected result

Product name is displayed above image with html character codes rendered

### Actual result

Product name is displayed above image with html character code not rendered

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by drinkingsouls** [comment]
@magento give me 2.4-develop instance

**Comment by drinkingsouls** [comment]
Reproduced.
![rep](https://github.com/magento/magento2/assets/45666862/31718be7-8bd4-43ca-a451-492bb08652ee)

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @drinkingsouls,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Go to Catalog > Products (Product Grid)
- Find a product with a html character such as quotes " for this example.
- Click on the image thumbnail


In Product grid it is working fine and showing with a html character such as quotes " .


<img width="1426" alt="Screenshot 2023-07-31 at 3 44 22 PM" src="https://github.com/magento/magento2/assets/51680745/535c74f7-552f-4e3f-a5a3-219ba24230ab">


In frontend also it is working fine.


<img width="1302" alt="Screenshot 2023-07-31 at 3 44 39 PM" src="https://github.com/magento/magento2/assets/51680745/6b59c5d1-9a3c-4bc5-bdfb-4f40c17549e0">



In Product grid when we click the image the html characters are not rendering.


<img width="759" alt="Screenshot 2023-07-31 at 3 45 02 PM" src="https://github.com/magento/magento2/assets/51680745/9ba80bf8-5d5d-4ea6-ab8c-a8c6db2bb1b6">



Hence Confirming the issue.


Thanks.

**Comment by JettyRohanAditya** [comment]
@magento I am working on this

**Comment by drinkingsouls** [comment]
I've just upgraded Magento 2 to 2.4.6-p4 and this issue has returned.
@magento give me 2.4-develop instance

**Comment by drinkingsouls** [comment]
Not reproducible for development site. Unsure why my local install has reverted back to this issue.
