### ISSUE TITLE
Update simple product custom option in cart adds QTY together

### ISSUE THREAD

**Issue by bentideswell** [magento/magento2#37839]
### Preconditions and environment

- 2.4.6-p1

### Steps to reproduce

1. Create a simple product and set the quantity to 1.
2. Add a new custom option dropdown. Call it 'Size' and create 2 options: small and medium
3. Navigate to the frontend and add the item to the cart and select the 'small' option.
4. Edit the item in the cart. When the product page loads, change the option from 'small' to 'medium' and click Update Cart

### Expected result

The item in the cart should be updated to use the 'medium' option.

### Actual result

The item stays in the cart with the original option (small) and the error message 'The requested qty is not available' is displayed.

This issue occurs if the quantity in the basket multipled by 2 is more than the quantity in stock. The easiest way to test this is with a QTY of 1.

The issue happens because when updating the item in the cart, Magento adds the requested quantity to the existing quantity. If we have 1 in stock and the QTY in the basket is 1, Magento adds the updated QTY of 1 to the existing QTY of 1 and tries to validate it for qty=2. This fails as only 1 is in stock.

The addition occurs here:

\Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList::getQty

This would happen with any QTY where the QTY in the basket multipled by 2 is more than the QTY in stock, so if there were 3 in stock and the basket QTY was 2, the system would validate a QTY of 4 which would fail.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @bentideswell ,

Thanks for reporting this issue,

Verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly recheck the behaviour in 2.4-develop instance.
Kindly refer the below screenshots:
<img width="1504" alt="Screenshot 2023-08-14 at 12 03 21 PM" src="https://github.com/magento/magento2/assets/60198592/a07bad10-9490-48ce-b9ac-eea3901f7813">
<img width="1504" alt="Screenshot 2023-08-14 at 12 04 05 PM" src="https://github.com/magento/magento2/assets/60198592/ff5188fc-dbe0-488e-b4d8-05f5242106cb">
<img width="1504" alt="Screenshot 2023-08-14 at 12 05 03 PM" src="https://github.com/magento/magento2/assets/60198592/49fb24c6-f232-4f32-945c-9eac7756dfc6">
<img width="1504" alt="Screenshot 2023-08-14 at 12 05 51 PM" src="https://github.com/magento/magento2/assets/60198592/53d29b0d-dff7-4b51-843c-3a480699b123">

**Comment by bentideswell** [comment]
Thanks for reviewing. I can see the issue is NOT reproducible on the 2.4-develop instance, but it still is on my 2.4.6-p1 installation. Could this have been fixed since 2.4.6-p1?

**Comment by bentideswell** [comment]
I've installed 2.4-develop locally and tested and can confirm that the issue is not reproducible suggesting that a recent fix has resolved the issue.

Are there any recent merges that you can think of that could be responsible for fixing this? It would be great to generate a patch for my client until this issue is released in 2.4.7 or 2.4.6-p2.
