### ISSUE TITLE
Email broken when use raw header instead

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#37840]
### Preconditions and environment

- Any version 2.4.5+

### Steps to reproduce

1. Create template order for example (add template in admin)
2. Remove default header {{template config_path="design/email/header_template"}}
3. Copy/Place raw html email header code to top content email instead default (Raw content you can find here https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Email/view/frontend/email/header.html)
4. Save email.
5. Can preview or send directly email for review

### Expected result

Html render fine without broken layout

### Actual result

Email broken, css can't fill inline to email

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create template order for example (add template in admin)
- Remove default header {{template config_path="design/email/header_template"}}
- Copy/Place raw html email header code to top content email instead default (Raw content you can find here https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Email/view/frontend/email/header.html)
- Save email.
- Can preview or send directly email for review



<img width="1403" alt="Screenshot 2023-08-04 at 11 46 55 AM" src="https://github.com/magento/magento2/assets/51680745/e678aceb-0d44-426d-8580-24d1bac07282">



<img width="1392" alt="Screenshot 2023-08-04 at 11 46 26 AM" src="https://github.com/magento/magento2/assets/51680745/42454f52-584a-4074-84da-5b9292984271">




<img width="1047" alt="Screenshot 2023-08-04 at 11 46 35 AM" src="https://github.com/magento/magento2/assets/51680745/44d2257a-b4e7-4915-8e58-e4c711e02e04">


Html is rendering fine without broken layout.Please let us know if we are missing anything.


Thanks.

**Comment by mrtuvn** [comment]
the last one in bottom seem missing. Can you share final output email with place test order and capture entire sample order test email

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create template order for example (add template in admin)
- Remove default header {{template config_path="design/email/header_template"}}
- Copy/Place raw html email header code to top content email instead default (Raw content you can find here https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Email/view/frontend/email/header.html)
- Save email.
- Can preview or send directly email for review


<img width="1439" alt="Screenshot 2023-08-07 at 12 58 19 PM" src="https://github.com/magento/magento2/assets/51680745/a915fa7d-cdf9-49ab-8b35-a08506a002e7">



<img width="1150" alt="Screenshot 2023-08-07 at 12 58 28 PM" src="https://github.com/magento/magento2/assets/51680745/f7dfb382-c128-487c-95a6-a82f05a0bc74">



<img width="1113" alt="Screenshot 2023-08-07 at 1 02 52 PM" src="https://github.com/magento/magento2/assets/51680745/57a2594e-ab3b-459a-b508-43987a109d91">


<img width="1107" alt="Screenshot 2023-08-07 at 1 03 01 PM" src="https://github.com/magento/magento2/assets/51680745/88f41c6d-3e45-4adf-b69c-f087cd72a702">


Html is rendering fine without broken layout.Please let us know if we are missing anything.

Thanks.

**Comment by mrtuvn** [comment]
looks like problem from my own email. I will check from my side. Closed this one now
