### ISSUE TITLE
Maximum Qty allowed in shopping cart Issue

### ISSUE THREAD

**Issue by EzzatLaw** [magento/magento2#37875]
### Preconditions and environment

- 2.4.6-p2
- When you set maximum Qty allowed in shopping cart to any value like "2" 
- the page reloads and your cart is completely emptied when you try to add more 2 items from the product.

### Steps to reproduce

1. Navigate to backend
2. Catalog -> products
3. Press "Add Product" button
4. Fill the Required product fields and Quantity.
5. Press "Advanced Inventory" bellow Quantity field.
6. Uncheck box "Use Config Settings" under "Maximum Qty Allowed in Shopping Cart" line.
7. Set Value to "2"
8. Press "Done" button
9. Save product

### Expected result

On the frontend
the customer can't add more 2 items from this product to cart.
and get message "max allowed Qty is 2 from this product"

### Actual result

You can add first item successfully 
also the Second.
The page reloads and your cart is completely emptied when you try to add the third.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @EzzatLaw,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Navigate to backend
- Catalog -> products
- Press "Add Product" button
- Fill the Required product fields and Quantity.
- Press "Advanced Inventory" bellow Quantity field.
- Uncheck box "Use Config Settings" under "Maximum Qty Allowed in Shopping Cart" line.
- Set Value to "2"
- Press "Done" button
- Save product

When we are trying to add more than QTY 2 we are not able to cart.getting message as **The requested qty exceeds the maximum qty allowed in shopping cart**


<img width="1359" alt="Screenshot 2023-08-14 at 12 00 18 PM" src="https://github.com/magento/magento2/assets/51680745/3a9e8750-a3ff-47e2-ad7f-557d4f4686e9">





<img width="1457" alt="Screenshot 2023-08-14 at 12 05 01 PM" src="https://github.com/magento/magento2/assets/51680745/8d7f9ee4-e988-4818-b9fd-f3ae6b264bbe">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by devchris79** [comment]
@magento give me 2.4-develop instance

**Comment by drinkingsouls** [comment]
@magento give me 2.4-develop instance

**Comment by EzzatLaw** [comment]
@magento give me 2.4-develop instance

**Comment by nicolasbachmaier** [comment]
@magento give me 2.4-develop instance

**Comment by nicolasbachmaier** [comment]
Issue is not reproducible, but I noticed something else.

If you set the Order Maximum of a Configurable, this will be ignored. For example set the max order quantity to 2 and then you can add 3 different color variations or size variations to your cart which of course in my opinion should not be allowed.

**Comment by devchris79** [comment]
I called a test instance after seeing @engcom-Bravo test screenshots. They show the maximum quantity set to 2 in the setup, but the error occuring with 1 item in the basket and adding a second (as the max is set to 2 it should be fine). I couldn't reproduce that behaviour though, so I think the screenshots are incorrect.

**Comment by engcom-Bravo** [comment]
@devchris79 @nicolasbachmaier Thanks for your contribution & collaboration over here.

@devchris79,

We have already added same product to the cart with quantity 2 and again we are adding the same product with the quantity as 1 then we are getting message as a **The requested qty exceeds the maximum qty allowed in shopping cart**.


<img width="1442" alt="Screenshot 2023-08-21 at 12 59 09 PM" src="https://github.com/magento/magento2/assets/51680745/21a11009-3c1c-441a-ba7f-84aa48ec2c90">


<img width="1397" alt="Screenshot 2023-08-21 at 12 59 38 PM" src="https://github.com/magento/magento2/assets/51680745/65bca323-9f0b-4dce-a669-aced38358f6d">





@nicolasbachmaier,


For Configurable products please change the settings for child products under Advanced inventory.we have changed for XS-Black and we are getting **The requested qty exceeds the maximum qty allowed in shopping cart**.



<img width="1396" alt="Screenshot 2023-08-21 at 1 26 48 PM" src="https://github.com/magento/magento2/assets/51680745/68c0d442-99e1-44cf-9ece-91a11a95c095">




Please let us know still you are facing any issue.


Thanks.

**Comment by EzzatLaw** [comment]
Thank you for help @engcom-Bravo  
it's already work fine on Magento Instance site,
So I have installed new one without any extensions but the problem still persists.
this my test site if you need to check
[mag.ezzat.eu.org](https://mag.ezzat.eu.org/)
Thanks in advance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by nicolasbachmaier** [comment]
@engcom-Bravo 
> @nicolasbachmaier,
> 
> For Configurable products please change the settings for child products under Advanced inventory.we have changed for XS-Black and we are getting **The requested qty exceeds the maximum qty allowed in shopping cart**.
> <img alt="Screenshot 2023-08-21 at 1 26 48 PM" width="1396" src="https://user-images.githubusercontent.com/51680745/261958699-68c0d442-99e1-44cf-9ece-91a11a95c095.png">

it works when setting the maximum qty for the simple products,

**but** shouldn't it as well work on the configurable level? For example: If I drop a limited edition sneaker (that sells out within a couple of minutes) and I don't want that people buy it in multiple sizes at once, but only one size a time.
In this case I should be able to go to the Configurable and set the max qty to 1.

(so in theory magento should not only check the Simple you are actually buying for max qty when putting it into the cart but also the associated configurable product)

Please correct me if I am wrong or missing something.

**Comment by EzzatLaw** [comment]
Thank you @engcom-Bravo 
I'm using Magento ver. 2.4.6-p2 community-edition
Centos 7 
Apache/2.4.52
PHP: 8.1.18
MySQL: 10.4.28-MariaDB
Elastic search 7.10.2

**Comment by engcom-Bravo** [comment]
Hi @EzzatLaw,

Thanks for your update.

We have also tried to reproduce the issue in Magento 2.4.6-p2 version still we are not able to reproduce the issue.Kindly refer the attached video.



https://github.com/magento/magento2/assets/51680745/5517a8ca-d54c-4bb4-ada3-49a51ac6f800




Could you please check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by EzzatLaw** [comment]
Thank you all
I have installed it on another sub domain and it working correctly, thanks
Specially engcom-Bravo

**Comment by maaarghk** [comment]
@engcom-Bravo This bug is reproducible for me on 2.4-develop, please re-open it. If you retry using the correct reproduction steps as provided by @EzzatLaw you will see it - in your own comment you list reproduction steps which are different (You add 3 at one time whereas in the original post you were instructed to add one at a time).

It is possible to see that this bug exists just by reading the code, which deletes the item if it has an error, even if the item already exists.

https://github.com/magento/magento2/blob/968fb3e1031b04bce2202aa8031cb3a862ff88e0/app/code/Magento/Quote/Model/Quote.php#L1701-L1702

The expected behaviour is that the add to cart fails, but the item remains in the cart with qty = 2.  The observed behaviour is the item is removed from the cart.

**Comment by nicolasbachmaier** [comment]
@magento give me 2.4-develop instance

**Comment by nicolasbachmaier** [comment]
> @engcom-Bravo This bug is reproducible for me on 2.4-develop, please re-open it. If you retry using the correct reproduction steps as provided by @EzzatLaw you will see it - in your own comment you list reproduction steps which are different (You add 3 at one time whereas in the original post you were instructed to add one at a time).
> 
> It is possible to see that this bug exists just by reading the code, which deletes the item if it has an error - but does not check if this is the appropriate behaviour.
> 
> https://github.com/magento/magento2/blob/968fb3e1031b04bce2202aa8031cb3a862ff88e0/app/code/Magento/Quote/Model/Quote.php#L1701-L1702
> 
> The expected behaviour is that the add to cart fails, but the item remains in the cart with qty = 2. The observed behaviour is the item is removed from the cart.




I tried to reproduce it again, but I can only observe the expected behavior. Adding an Item to the Cart uses this Code

> https://github.com/magento/magento2/blob/968fb3e1031b04bce2202aa8031cb3a862ff88e0/app/code/Magento/Quote/Model/Cart/AddProductsToCart.php#L78-L118

and it does have ErrorHandling to ensure "Full Success" instead of only "Partial Success" while Adding to Cart. 


My steps and what I observed (Max Qty. set to 2):

1. Add Item one time to the Cart -> Success
2. Add Item another time to Cart -> Success
3. Add Item another (a third) time to Cart -> Error -> Page reloads because the POST Request returns the BackURL e.g. {"backUrl":"https:\/\/0229a02fdbd4382d710f8a2d87f7e60f.instances-prod.magento-community.engineering\/joust-duffle-bag.html"}
4. The two items previously added are as expected still in the cart. (It took some time to display the two items in the shopping cart because the DEV Server I got was rather slow)

Am I missing anything? @maaarghk

**Comment by maaarghk** [comment]
It occurs to me this same error text is thrown by MSI and classic inventory; this error may only occur when MSI is disabled (this is the case on the site I tested with). Is it considered a valid bug in that case? I would think a backwards compatibility error.  Not sure how to disable MSI on the test instances or if it is even possible.

**Comment by maaarghk** [comment]
I didn't ask whether you think it is an MSI issue, I asked whether it is possible to create a test instance which has MSI disabled, and whether the bug is still considered valid if it only happens when MSI is disabled.

**Comment by devchris79** [comment]
Disabling the MSI is no longer recommended, the alternative CatalogInventory module has been deprecated and the documentation now says it can cause issues:
https://experienceleague.adobe.com/en/docs/commerce-admin/inventory/get-started/install-update

We had this disabled, but after reading the above I decided we had better enable the MSI modules.
