### ISSUE TITLE
REST API /V1/orders does not handle out-of-bound currentPage correctly

### ISSUE THREAD

**Issue by vanderlee** [magento/magento2#3787]
## Steps to reproduce
1. Install Magento2 with sample data (has 2 orders).
2. Call `/V1/orders` API with a `pageSize` and `currentPage` in `searchCriteria` that is beyond the number of orders. (tested path: `/V1/orders?searchCriteria%5BcurrentPage%5D=100&searchCriteria%5BpageSize%5D=100`)
## Expected result
1. Empty page
## Actual result
1. Last page of orders

**Comment by mbrinton01** [comment]
Internal Issue MAGETWO-52813

**Comment by chrisconlon-klaviyo** [comment]
Also seeing this for:

> /V1/customers/search
> /V1/carts/search

Works as expected for `/V1/products` though.

As a workaround for others that are blocked by this, I'm going to just use the response's `page_size` \* `current_page` > `total_count` to know when I'm past the last page.

**Comment by mbrinton01** [comment]
Thank you @chrisconlon-klaviyo for the additional feedback. I have added your comments about /V1/customers/search and /V1/carts/search to the internal ticket.

**Comment by slavvka** [comment]
Hi all. This is not a bug since such a behavior is standard for all Magento collection.

**Comment by vrann** [comment]
@vanderlee There are couple of options on what to do if page is larger than number of pages available -- Magento just selected default one used in Collections assuming this would be the most familiar way for developers. Are there any situations where this causes problems? Client can always decide to ignore the response. Also it doesn't look to make sense to iterate through search results "while not empty", because count is available.
