### ISSUE TITLE
feat(directory): rename Swaziland -> Eswatini in the codebase

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#37873]
### Preconditions and environment

v2.4.7-beta1

### Steps to reproduce

Review the codebase for references to Swaziland

### Expected result

See `Eswatini` instead of `Swaziland`

### Actual result

I see various files which reference `Swaziland` instead of `Eswatini` 

 - [ ] https://github.com/magento/magento2/blob/0a834cce01c3d924d450c9a71123d9ac6de68b62/app/code/Magento/CustomerGraphQl/etc/schema.graphqls#L396

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @damienwebdev,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Review the codebase for references to Swaziland

<img width="526" alt="Screenshot 2023-08-16 at 11 46 21 AM" src="https://github.com/magento/magento2/assets/51680745/2cc2f582-91e8-4056-960d-7fab78101f25">



We have referred this page https://en.wikipedia.org/wiki/Eswatini. It should be **Eswatini** instead of **Swaziland**.


Hence Confirming the issue.

Thanks.

**Comment by yegxr** [comment]
@magento I am working on this
