### ISSUE TITLE
GraphQL addProductsToCart mutation reports unrelated errors in user_errors

### ISSUE THREAD

**Issue by paales** [magento/magento2#37908]
### Preconditions and environment

- 2.4.6-p2
- Demo products available
- MSI configured (although not known if it is a specific MSI issue)

### Steps to reproduce

1. Create a product "PRODUCT-1" with inventory of 100
2. Create a product "PRODUCT-2" with inventory of 100 (make sure indexers etc. have ran)

3. Create an empty cart:

```graphql
mutation {
  createEmptyCart(input: {cart_id: "CART_ID_CART_ID_CART_ID_CART_ID_"})
}
```

4. Add a product with for quantity of 100 to the cart.

```graphql
mutation AddProductOne {
  addProductsToCart(cartId: "CART_ID_CART_ID_CART_ID_CART_ID_", cartItems: [{
    sku: "PRODUCT-1",
    quantity: 100
  }]) {
    cart {
      items {
        ... on SimpleCartItem {
          quantity
        }
        errors {
          code
          message
        }
      }
    }
    user_errors {
      code
      message
    }
  }
}
```

5. Run this mutation again, you will see an error on `user_errors`, this is correct.
6. Change the quantity of PRODUCT-1 to 50 in the backend
7. Validate that the items[0].errors has entries:

```graphql
query GetCart {
  cart(cart_id: "CART_ID_CART_ID_CART_ID_CART_ID_") {
    items {
      ... on SimpleCartItem {
        quantity
      }
      product {
        sku
      }
      errors {
        code
        message
      }
    }
  }
}
```
8. Add the second product to the cart with quantity of 1

```graphql
mutation {
  addProductsToCart(cartId: "CART_ID_CART_ID_CART_ID_CART_ID_", cartItems: [{
    sku: "PRODUCT-2",
    quantity: 1
  }]) {
    cart {
      items {
        ... on SimpleCartItem {
          quantity
        }
        product {
          sku
        }
        errors {
          code
          message
        }
      }
    }
    user_errors {
      code
      message
    }
  }
}
```

### Expected result

I would expect the user_errors to be empty because there was no error with the operation, only an error with the cart it's self.

### Actual result

user_errors contains the error of the other item..

### Additional information

We currently have to do some very dirty checking to see on which item this error occurs and do a string match on the message to filter any cart item errors. This is not foolproof and is slow when there are many items in the cart. This issue arises because add to cart actions become very slow when there are many items in the cart because we fetch those items on each action.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @paales,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create a product "PRODUCT-1" with inventory of 100
- Create a product "PRODUCT-2" with inventory of 100 (make sure indexers etc. have ran)
- Create an empty cart:

```
mutation {
  createEmptyCart(input: {cart_id: "CART_ID_CART_ID_CART_ID_CART_ID_"})
}
```

- Add a product with for quantity of 100 to the cart.

```
mutation AddProductOne {
  addProductsToCart(cartId: "CART_ID_CART_ID_CART_ID_CART_ID_", cartItems: [{
    sku: "PRODUCT-1",
    quantity: 100
  }]) {
    cart {
      items {
        ... on SimpleCartItem {
          quantity
        }
        errors {
          code
          message
        }
      }
    }
    user_errors {
      code
      message
    }
  }
}
```

- Run this mutation again, you will see an error on user_errors, this is correct.
- Change the quantity of PRODUCT-1 to 50 in the backend
- Validate that the items[0].errors has entries:

```
query GetCart {
  cart(cart_id: "CART_ID_CART_ID_CART_ID_CART_ID_") {
    items {
      ... on SimpleCartItem {
        quantity
      }
      product {
        sku
      }
      errors {
        code
        message
      }
    }
  }
}

```

- Add the second product to the cart with quantity of 1

```
mutation {
  addProductsToCart(cartId: "CART_ID_CART_ID_CART_ID_CART_ID_", cartItems: [{
    sku: "PRODUCT-2",
    quantity: 1
  }]) {
    cart {
      items {
        ... on SimpleCartItem {
          quantity
        }
        product {
          sku
        }
        errors {
          code
          message
        }
      }
    }
    user_errors {
      code
      message
    }
  }
}

```

We have added a PRODUCT-1 with qty 100.

<img width="1414" alt="Screenshot 2023-08-23 at 7 34 28 PM" src="https://github.com/magento/magento2/assets/51680745/15371a15-1206-4bf4-9d85-3b74aa1cf436">







Here We are getting errors it is expected.

<img width="1436" alt="Screenshot 2023-08-23 at 7 34 43 PM" src="https://github.com/magento/magento2/assets/51680745/42338bcf-7e85-4c93-8538-dd0bf204504b">


<img width="1422" alt="Screenshot 2023-08-23 at 6 02 34 PM" src="https://github.com/magento/magento2/assets/51680745/3d78840c-dd27-457f-8746-8f72efff7f66">



<img width="1471" alt="Screenshot 2023-08-23 at 7 40 21 PM" src="https://github.com/magento/magento2/assets/51680745/96b3a326-dffd-4bd4-8d33-f9a6c1f68f5e">


We are getting user errors while adding **PRODUCT-2** it is having sufficient stock and quantity there is no issue with this product.There should be no errors still we are getting errors.

Hence Confirming the issue.

Thanks.

**Comment by Vasudev-22** [comment]
@magento I am working on this
