### ISSUE TITLE
It's time to change your password link not working.

### ISSUE THREAD

**Issue by parbat-evrig** [magento/magento2#37902]
### Preconditions and environment

- Magento 2.4.6

### Steps to reproduce

1. Login to admin panel
2. If your password expired and **Password Change** setting set to **Recommended** you will a message "It's time to change your password." with link.
3. When you click on this link then simply same page will be refreshed.
4. No way to reset password.

### Expected result

It should redirect to reset/change admin password page.

### Actual result

It is not redirecting to reset/change admin password page.Simply refresh admin dashboard page.

### Additional information

In same admin dashboard page if click on user icon then on Account Setting, it directs to reset/change admin password page.
I think issue is in key that is added to link url.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by parbat-evrig** [comment]
> Are you using Porto theme?

@devchris79 No, I am using luma theme.

**Comment by devchris79** [comment]
May be related to #35667

**Comment by parbat-evrig** [comment]
Dashboard message:-
  vendor/magento/module-user/Observer/Backend/AuthObserver.php
  Line no- 203
  `$myAccountUrl = $this->url->getUrl('adminhtml/system_account/');`
  Above url not Working.


Admin user nav:-
vendor/magento/module-backend/view/adminhtml/templates/page/header.phtml
Line No:- 23
`<?= /* @noEscape */ $block->getUrl('adminhtml/system_account/index') ?>`
Above url is working.


After debugging it more found out that key value in url is diff-diff for both.

**Comment by engcom-Bravo** [comment]
Hi @parbat-evrig,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Login to admin panel
- If your password expired and Password Change setting set to Recommended you will a message "It's time to change your password." with link.
- When you click on this link then simply same page will be refreshed.
- No way to reset password.


We have changed Password change setting as Recommended.

<img width="1019" alt="Screenshot 2023-08-22 at 1 31 08 PM" src="https://github.com/magento/magento2/assets/51680745/4b395873-3d76-448a-bc11-a137ba4bd582">


https://github.com/magento/magento2/assets/51680745/7009466f-0c2b-4b7e-8ee7-2eb06b940e87



After login to Admin dashboard when we click on **It's time to change your password** it is not redirecting to password change page it is just refreshing the admin page.


Hence Confirming the issue.

Thanks.

**Comment by BeggiNN** [comment]
@magento I am working on this

**Comment by BeggiNN** [comment]
@magento give me 2.4-develop instance

**Comment by BeggiNN** [comment]
@magento give me 2.4-develop instance

**Comment by BeggiNN** [comment]
Unable to replicate on Dev instance because password cannot expire in time

**Comment by BeggiNN** [comment]
@magento 
Unable to replicate on Dev instance because password cannot expire in time

**Comment by parbat-evrig** [comment]
Hi @BeggiNN , any update here ?

**Comment by BeggiNN** [comment]
@parbat-evrig I'm in the process

**Comment by BeggiNN** [comment]
@magento I am working on this

**Comment by Kristhian92** [comment]
Hello everyone, at the moment I am trying to find a solution but I haven't found it, could you help me, thank you

**Comment by parbat-evrig** [comment]
Hello Kristhian,

Did you apply this patch
https://github.com/magento/magento2/pull/37978/commits/a40555914794446146c004e3ebf973f6802902d5
?

**Comment by cristhianlizcanov** [comment]
Hello, I am trying to customize the message its time change the password so that when I click on it, it redirects me to Account Settings to renew the password and it does not take me to the Dashboard again. I don't know what file to change in my vendor.
