### ISSUE TITLE
Moment.min.js.map file is not generating

### ISSUE THREAD

**Issue by bartoszjuszczyk** [magento/magento2#37925]
### Preconditions and environment

- Magento 2.4.6-p2

### Steps to reproduce

1. Navigate to backend panel

### Expected result

Moment.min.js.map file is generated

### Actual result

Moment.min.js.map file is not generated

<img width="865" alt="image" src="https://github.com/magento/magento2/assets/128232518/1618d5c0-a34d-4530-a88c-81d75f4ad7db">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bartoszjuszczyk** [comment]
@magento give me 2.4.6-p2 instance

**Comment by bartoszjuszczyk** [comment]
@magento reproduced on 2.4.6-p2 instance

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @bartoszjuszczyk,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Navigate to backend panel

<img width="1512" alt="Screenshot 2023-08-29 at 3 09 55 PM" src="https://github.com/magento/magento2/assets/51680745/4000cd33-f7c2-4573-8b74-055597f27276">



<img width="1499" alt="Screenshot 2023-08-29 at 3 17 12 PM" src="https://github.com/magento/magento2/assets/51680745/fd4b538b-13eb-4221-a61a-b59c937b6379">




There is no error in console and also Moment.min.js.map file is generating.

Could you please refer this document https://experienceleague.adobe.com/docs/commerce-operations/performance-best-practices/performance-best-practices/advanced-js-bundling.html regarding enabling javascript Bundling.

Thanks.

**Comment by hostep** [comment]
I've seen this as well on many shops. It should definitely still be reproducible on 2.4-develop I think. But I don't have time to find exact steps.
It's quite annoying, the JS console should ideally be empty, no warnings or errors, but this warning is added there.

Issue was introduced by updating the moment.js library from version 2.29.1 to 2.29.4 [over here](https://github.com/magento/magento2/commit/e7775d63f7cf714c2d2b751a4f3f9dfd96679dfc). You'll see that the last line added introduces that link to `moment.min.js.map`
This change got added in:
- 2.4.4-p4
- 2.4.5-p3
- 2.4.6-p1
- 2.4.7-beta1

So I think the solution is simple, that extra line at the bottom of that file should be removed again, just like it was before the upgrade.

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your contribution & collaboration over here.

Hi @bartoszjuszczyk,

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to Reproduce**

- Install Magento 2.4-develop 
- Go to the backoffice (no need to login) (or use the frontend)
- Look into your console in your browser


<img width="1489" alt="Screenshot 2023-09-01 at 12 11 21 PM" src="https://github.com/magento/magento2/assets/51680745/af648186-0b31-42a8-b79c-0c606018d50e">



<img width="1506" alt="Screenshot 2023-09-01 at 12 12 54 PM" src="https://github.com/magento/magento2/assets/51680745/dea630a1-d02f-4c99-82e5-74525846eb92">


<img width="1507" alt="Screenshot 2023-09-01 at 12 24 38 PM" src="https://github.com/magento/magento2/assets/51680745/85cb3a71-7369-4fa3-9fec-ebfefa0cf64d">



We are getting error failure to load zxcvbn.js.map and Moment.min.js.map.

Hence Confirming the issue.

Thanks.

**Comment by LucScu** [comment]
@engcom-Bravo do you know which is the PR created related to this issue?

**Comment by engcom-Bravo** [comment]
Hi @bartoszjuszczyk,

Internal team has started working on this issue.

Thanks,

**Comment by hostep** [comment]
Closed without any comment telling why?

But appears to be fixed by removing the sourceMappingURL: https://github.com/magento/magento2/commit/11add87193d7ba5fd822631df8e329998f841026

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1358 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-9452&type=commits

Thanks.

**Comment by YiffyToys** [comment]
> But appears to be fixed by removing the sourceMappingURL: [11add87](https://github.com/magento/magento2/commit/11add87193d7ba5fd822631df8e329998f841026)

So no issues with "main.CRITICAL: Unable to resolve the source file" for any .js.map files once all plugins are updated and we can upgrade to **2.4.7** ?

**Comment by chrom** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by chrom** [comment]
@magento give me develop instance

**Comment by mooseducks** [comment]
I ended up completely reinstalling. I had a Magento developer take a look, they think one of the extensions I added via command line was logged in as root user instead of owner.

Don't know if that helps, after a few hours of them trying to troubleshoot it, I just decided to go with a new instance since products hadn't been added yet, we are migrating from another platform.
