### ISSUE TITLE
Random showing JSON strings instead of category page

### ISSUE THREAD

**Issue by Claudiusdev** [magento/magento2#37936]
### Preconditions and environment

- Magento version 2.4.3
- varnish-6.5.2

### Steps to reproduce

Browse any category page

### Expected result

Show a normal category page

### Actual result

Reach a cached page with JSON strings occasionally

### Additional information

#28237 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Claudiusdev,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Browse any category page

It is showing normal category page.

<img width="1129" alt="Screenshot 2023-08-31 at 12 51 36 PM" src="https://github.com/magento/magento2/assets/51680745/babc86f9-9013-4516-a561-d8ee62459c61">


<img width="1454" alt="Screenshot 2023-08-31 at 12 49 29 PM" src="https://github.com/magento/magento2/assets/51680745/d9ecf22d-5d70-4a19-983a-cfbb8354a250">



Could you please try to reproduce the issue Latest Magento 2.4-develop instance it may issue got fixed.

Thanks.

**Comment by Claudiusdev** [comment]
Hi @engcom-Bravo,
We will test everything after magento upgrade to last version.

Thank you for the information
