### ISSUE TITLE
Failed to process PxPay 2.0 response error message

### ISSUE THREAD

**Issue by AWAlex01** [magento/magento2#37961]
### Preconditions and environment

- Magento version 2.4.6
- Can't reproduce purposely, happens randomly on different customer orders.
Some customers place orders and it goes through fine. Others place orders and I get a random 'Failed to process PxPay 2.0 response.' error message on the back of the web. This causes the email not to send as well.
![pxpay2 0](https://github.com/magento/magento2/assets/144139287/96147e18-c72d-4a53-a35b-5e89a57299fd)

### Steps to reproduce

Can't reproduce purposely, happens randomly on different customer orders.

Some customers place orders and it goes through fine. Others place orders and I get a random 'Failed to process PxPay 2.0 response.' error message on the back of the web. This causes the email not to send as well.

### Expected result

We expect the customers' order to go through like normal and properly. With them also getting their order confirmation.

### Actual result

Random orders get this error message causing an error on their end too which says 'Failed To Load Basket' after pressing place order. The order comes through our end and all looks okay but the error causes errors on the customer end and also doesn't send their order email. It can cause duplicate orders as customers don't think they have ordered the first time. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @AWAlex01,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are able to place the order successfully without any issue.

<img width="1043" alt="Screenshot 2023-09-06 at 1 04 33 PM" src="https://github.com/magento/magento2/assets/51680745/51c0dece-d28d-4d27-a0f5-2ec93e0b583d">



<img width="1360" alt="Screenshot 2023-09-06 at 1 04 42 PM" src="https://github.com/magento/magento2/assets/51680745/bfb3dc77-2bb9-4b0a-b543-0465639cea93">


It looks like third party extension causing the issue.please if you are using any third party extension All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page.

Please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @AWAlex01,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37961#issuecomment-1708243035 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by AWAlex01** [comment]
This issue is still happening frequently. We are trying to get the people that built our checkout to help fix it but they're not being cooperative. 

Thanks,

**Comment by engcom-Bravo** [comment]
Hi @AWAlex01,

“WindCave” Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of https://github.com/magento/magento2 git repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.
