### ISSUE TITLE
Template Issue: Displaying special price with and without tax

### ISSUE THREAD

**Issue by kestraly** [magento/magento2#37989]
### Preconditions and environment

- Magento version 2.4.x - Affects all versions

### Steps to reproduce

1. Store > Configuration >Tax  > Price Display Settings > Display Prices Including and Excluding Prices
2. Store > Configuration >Tax  > Calculationg Settings > Catalog Prices > Excluding Tax
3. Save
4. Set special price on a simple product
5. View product on frontend of the website

### Expected result

You would expect to see the price of the product display on the old price including and excluding tax and the final price including and excluding tax

### Actual result

Actual result is the final price including and excluding tax and the old price including tax only. 

Old price does not display excluding tax.

### Additional information

File causing the issue is vendor/magento/module-catalog/view/base/templates/product/price/final_price.phtml

**Code in question**
```
 <span class="old-price">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
```

Work around is to copy the file to your theme and remove skip_adjustments
```
 <span class="old-price">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true
        ]); ?>
    </span>
```

Removing skip_adjustments means that the special price will display correctly for the following display settings

including and excluding tax
excluding tax
including tax

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @kestraly,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Store > Configuration >Tax > Price Display Settings > Display Prices Including and Excluding Prices
- Store > Configuration >Tax > Calculationg Settings > Catalog Prices > Excluding Tax
- Save
- Set special price on a simple product
- View product on frontend of the website


**Before Special Price**

<img width="1258" alt="Screenshot 2023-09-14 at 12 01 43 PM" src="https://github.com/magento/magento2/assets/51680745/b5040ed3-4710-4969-82e6-e715d7bd22ca">



**After Special Price**


<img width="1410" alt="Screenshot 2023-09-14 at 12 06 48 PM" src="https://github.com/magento/magento2/assets/51680745/9da04549-b2a7-46dc-a724-4d1df16d3ce0">



Both the old price and special price disaplaying with including and excluding tax.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by kestraly** [comment]
Ah, I can see this has recently been changed on 2.4.7-beta1 in [ACP2E-1634](https://github.com/magento/magento2/commit/a670c855722d11488192df14cbf47afb761a24de)

Which has been adusted to 

`'skip_adjustments'  => false`

Although it could be removed entirely.

Appreciate you looking into this.
