### ISSUE TITLE
Invalid security or form key. Please refresh the page.

### ISSUE THREAD

**Issue by rciopluma** [magento/magento2#37993]
### Preconditions and environment

- Magento version 2.4.2
- PHP 7.4.33
- MySql 8.0.26
- Elastic 7.9.3
- Redis Server 6.0.16

### Steps to reproduce

1. Navigate to Store -> Attributes -> Product.
2. Select a dropdown attribute.
3. Add a new option.
4. Save.
![Schermata da 2023-09-15 10-57-57](https://github.com/magento/magento2/assets/132480337/613349b4-25ec-457e-a766-acbe4fabe7cf)
![Schermata da 2023-09-15 10-58-25](https://github.com/magento/magento2/assets/132480337/aba2b9d3-3968-4a86-b509-7529e275e770)

### Expected result

A new option is added.

### Actual result

Invalid security or form key. Please refresh the page.
![Schermata da 2023-09-15 10-56-50](https://github.com/magento/magento2/assets/132480337/299abb1a-2c29-4e0a-8d2a-a262362bb7e8)

### Additional information

I also applied [this](https://github.com/magento/magento2/issues/33749) without success
![Schermata da 2023-09-15 11-02-20](https://github.com/magento/magento2/assets/132480337/1bee7a8d-7221-4e58-a1c5-7c74b93e2ad7)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @rciopluma,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Navigate to Store -> Attributes -> Product.
- Select a dropdown attribute.
- Add a new option.
- Save.


We are able to add the new option and save.


<img width="1460" alt="Screenshot 2023-09-15 at 3 52 29 PM" src="https://github.com/magento/magento2/assets/51680745/8af15b94-fcf0-4555-add4-7f54f706c23e">



Could you please refer this comment https://github.com/magento/magento2/issues/33749#issuecomment-1028410426 and try to use that commit and please let us know if you are still facing any issue.


Thanks.

**Comment by rciopluma** [comment]
Hi @engcom-Bravo 
I have also added the code snippet of this [comment #33749](https://github.com/magento/magento2/issues/33749#issuecomment-1028410426), but I got the same error.
I'll do some debugging in a development environment and let you know

Thanks.

**Comment by rciopluma** [comment]
HI @engcom-Bravo 
I fixed it by removing the vendor folder and reinstalling all dependencies with composer.
Thanks

**Comment by rciopluma** [comment]
The issue can be closed
