### ISSUE TITLE
Add product to website and URL key error

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38004]
### Preconditions and environment

- Magento version 2.4.6-p2

### Steps to reproduce

1. Create a product with url key `toto`, add it into main website (A), and website B
2. Set url key = `tata` into website B
3. Create a second product in main website (A), with url key = `tata` (save)
4. Add this second product into website B, save

### Expected result

The product is added to website B, with url key `tata-1`

### Actual result

Error : `The value specified in the URL Key field would generate a URL that already exists.`

### Additional information

I think a common solution should be found for this issue and this one : https://github.com/magento/magento2/issues/12412

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Nuranto,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance.Kindly refer the screenshots.


**Steps to reproduce**

- Create a product with url key toto, add it into main website (A), and website B
- Set url key = tata into website B
- Create a second product in main website (A), with url key = tata (save)
- Add this second product into website B, save


<img width="1467" alt="Screenshot 2023-09-21 at 1 47 48 PM" src="https://github.com/magento/magento2/assets/51680745/932e4a6e-408b-49ea-8830-9fa275cc37e2">


We are able to reproduce the issue but it looks like expected behaviour because already we have same url key for the second product could you please let us know if we are missing anything.




Thanks.

**Comment by Nuranto** [comment]
Ok, I thought the expected behaviour was to add a number at the of the url key automatically to prevent duplicates. 
But that's a design choice indeed. I have those issue while importing products in mass, so this is really annoying and not easy to fix. But, I understand the choice.
