### ISSUE TITLE
Unclickable filters

### ISSUE THREAD

**Issue by yrp06** [magento/magento2#38013]
### Preconditions and environment

- Magento version : 2.3.7-p4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

An error message "Something went wrong with processing the default view and we have restored the filter to its original state." continuously pop up when I open Sales > Orders view.
I think the issue started since I have changed the filter to '999 per page'.
I'd like to reset the filter as the default one but I cannot because the page gets blocked whenever I enter.
Can you please help me to resolve the problem?

### Expected result

Would like to open and see the orders list.

### Actual result

Error message :  "Something went wrong with processing the default view and we have restored the filter to its original state." 
Issue : Cannot click anything in the page. (Sales > Orders)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @yrp06,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1468" alt="Screenshot 2023-09-28 at 11 23 41 AM" src="https://github.com/magento/magento2/assets/51680745/3b48b65c-1096-4314-808a-4d4660987fd9">


We are able to change the filter 999 per page and we are able to view the orders list.

Please refer this solution :


* Please check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
* UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
* Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.
* Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @yrp06,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38013#issuecomment-1738981427 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

It seems to be issue is caused by third party modules Please check the issue if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by yrp06** [comment]
Dear engcom-Bravo,

Thanks for your help.
All the issues have been resolved!

Best,

**Comment by yrp06** [comment]
Dear engcom-Bravo,

Thanks for your help.
All the issues have been resolved!

Best,
