### ISSUE TITLE
Magento Community Edition: Version 2.4.7-beta1 - Create Partial Shipment with default magento MSI feature

### ISSUE THREAD

**Issue by RocktechnolabsDev** [magento/magento2#38063]
### Preconditions and environment

- Magento Community Edition '2.4.7-beta1' without sample data is installed.
- Website have products
- Wants to create partial shipment for the order

### Steps to reproduce

1. Login into admin > Sales > Orders > Open order which have multiple products(items)
2. Create shipment for product1 (let's assume i have added Test simple, Test simple 2, Test simple 3 into cart, place an order, Login into admin > Sales > Orders > Open order, shipment created for product1 - http://i.imgur.com/q0Kg9L4.png 
3. Once shipment created for Test simple, again create new shipment for rest of two products.
4. what i am doing, if you will create another(2nd) shipment, you can see Test simple product into **Items Ordered** grid - http://i.imgur.com/a4PUxeO.png
5. when you select source, qty for ship is 0 for Test simple product, But i am able to add Qty to deduct value, while i add 1 into qty to deduct field for Test simple product, add 0 value for rest of 2 product, click on create shipment button, items to ship section not have information about the product, new shipment page looks like as per image - http://i.imgur.com/8i8bKxN.png
6. Rest of fields leave as it is.

### Expected result

New shipment creation page: 'items to ship' section doesn't have product information, also if we already created shipment for that product1, then it's doesn't move into next step which is new shipment page.

### Actual result

New shipment creation page: 'items to ship' section doesn't have product information - http://i.imgur.com/8i8bKxN.png

### Additional information

https://www.awesomescreenshot.com/video/21491584?key=165c1950b5dd5cba072517ca3650fc78

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @RocktechnolabsDev,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Login into admin > Sales > Orders > Open order which have multiple products(items)
- Create shipment for product1 (let's assume i have added Test simple, Test simple 2, Test simple 3 into cart, place an order, Login into admin > Sales > Orders > Open order, shipment created for product1 - http://i.imgur.com/q0Kg9L4.png
- Once shipment created for Test simple, again create new shipment for rest of two products.
- what i am doing, if you will create another(2nd) shipment, you can see Test simple product into Items Ordered grid - http://i.imgur.com/a4PUxeO.png
- when you select source, qty for ship is 0 for Test simple product, But i am able to add Qty to deduct value, while i add 1 into qty to deduct field for Test simple product, add 0 value for rest of 2 product, click on create shipment button, items to ship section not have information about the product, new shipment page looks like as per image - http://i.imgur.com/8i8bKxN.png
- Rest of fields leave as it is.


https://github.com/magento/magento2/assets/51680745/b30cc666-95e5-47a0-afdd-4adc3ecf77c8







After doing partial shipment for next shipment for product 1 then it's doesn't move into next step which is new shipment page. and for new shipment we are making other 2 products as 0 but still it is creating shipment for that products while creating it is not showing any products.


Hence Confirming the issue.


Thanks.

**Comment by ejaz-alam** [comment]
@magento I am working on this
