### ISSUE TITLE
backend and frontend not loading on fresh magento 2.3.3 

### ISSUE THREAD

**Issue by walsoulconsut** [magento/magento2#38066]
### Preconditions and environment

- Magento version 2.3.3 PHP 7.3
- Anything else that would help a developer reproduce the bug
- 

### Steps to reproduce

1. Magento was working well on my  could server
2. But on the same server, I have removed Python 3.6 and conda, then installed Anaconda version: 23.7.2 for Python's higher version
3. httpd server was also removed again and reinstalled.
4. after installation looks like the server configuration got changed or something happened to Magento
5. Since then Admin of Magento is broken and on the front end, images are not coming as the image URL is blocked.

### Expected result

Login In page

### Actual result

<img width="947" alt="magento 2 3 3" src="https://github.com/magento/magento2/assets/92803266/65db2c54-cd90-4d95-96f5-2b7fc1a58b71">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
It's not really a good idea to post environmental problems you have here on github. Since this isn't a core bug in Magento.
It's probably better to search for solutions on https://magento.stackexchange.com/ or https://community.magento.com/

But that aside, I seem to remember a wierd issue we ran into as well with PHP 7.3 and Magento 2.3.x shops that lead to no longer being able to generate static assets. And it was something due to an updated PCRE library.
Our workaround back then was to set `pcre.jit` to `0` in the `php.ini` file(s).
Maybe you're experience the same bug...

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your contribution & collaboration over here.

Hi @walsoulconsut,

Thank you for reporting and collaboration.

Looks like your issue is resolved with the workaround in php.ini file. Since this issue is not related to Magento Dev specifically and there is no action required from our side so we are closing this issue. If you still think there is an issue related to Magento Dev, please re-open this ticket or raise a fresh one with more related details.


Thanks.
