### ISSUE TITLE
Wrong bundle product price when used with tier prices

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#38091]
### Preconditions and environment

- 2.4.1 

### Steps to reproduce

Create the following products

1. Product with tier prices (P1)

- Price = 7
- Special price = 5.9
- Tier price -> QTY = 6 -> Price = 5.5
![image](https://github.com/magento/magento2/assets/20220341/ac96f82f-b88c-4350-9284-cba0fe6af77d)

2. A bundle product (P2) which 
- consists of 6 x P1 products and has 99% special price 
![image](https://github.com/magento/magento2/assets/20220341/736058c8-3910-41ce-8266-46ad556f3bf2)

The price of this product is and should be 32.67 which is 6 X 5.5 = 33 * 0.99 = 32.67

However on the site it appears as 35.04 which is 6 X 5.9  = 35.40 * 0.99 = 35.04 

The tier price is not working as expected in the product display on categories and product page. 

However the total configured price is correct at 32.67 when adding the product to the cart. 

The database indexer calculates the price as 35.046 which is also not rounded correctly as 35.05

![image](https://github.com/magento/magento2/assets/20220341/895aef84-24b2-445c-b618-684ffa241c90)

### Expected result

The tier prices are taken into account properly

### Actual result

The tier prices are not taken into account properly 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ioweb-gr** [comment]
@magento give me 2.4-develop instance

**Comment by ioweb-gr** [comment]
Actually I just spotted this one too #30610 looks like it's the same issue that's still not properly fixed. If there's a fix in newest version could you point us to the relevant commits @engcom-Bravo ?

**Comment by engcom-Bravo** [comment]
Hi @ioweb-gr,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

Create the following products

- Product with tier prices (P1)
- Price = 7
- Special price = 5.9
- Tier price -> QTY = 6 -> Price = 5.5



- A bundle product (P2) which
- consists of 6 x P1 products and has 99% special price


<img width="1056" alt="Screenshot 2023-10-18 at 1 08 18 PM" src="https://github.com/magento/magento2/assets/51680745/68994d1c-de6d-44e2-b044-f2773d939287">




<img width="987" alt="Screenshot 2023-10-18 at 1 08 11 PM" src="https://github.com/magento/magento2/assets/51680745/1862f515-573d-4485-9b9a-808958c0d685">




<img width="1413" alt="Screenshot 2023-10-18 at 1 08 03 PM" src="https://github.com/magento/magento2/assets/51680745/0ad3c0b5-c838-4d0c-b1a4-90d5702a3ab6">




<img width="1104" alt="Screenshot 2023-10-18 at 1 09 50 PM" src="https://github.com/magento/magento2/assets/51680745/686629ac-26d9-42f8-b272-584304022935">




In frontend it should show as follows :

6 X 5.5 = 33 * 0.99 = 32.67 


But it is showing as 32.70 there is rounding errors in the price.


The database indexer calculating the price as 35.04600 which is not correct.


Hence Confirming the issue.


Thanks.

**Comment by ioweb-gr** [comment]
The most important part is the indexer because for everything that uses the indexed price like feeds, elastic, layered navigation the calculation is happening with the wrong price leading to false information

**Comment by Swahjak** [comment]
Was anything ever fixed? Or was this just another one of those 'if we close it nobody might notice'?

**Comment by ioweb-gr** [comment]
Probably the latter @Swahjak
