### ISSUE TITLE
Price Mistmatch Error for configurable product

### ISSUE THREAD

**Issue by hariwebdeveloper1989** [magento/magento2#38110]
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Seems to be with all versions. We have recently tested on 2.4.6-p2
-The issue is the price is changing on client side with url like 
https://stage.epoxywinkel.be/flow-resin-epoxy-giethars-voor-grote-gietingen#162=220
https://stage.epoxywinkel.be/flow-resin-epoxy-giethars-voor-grote-gietingen#162=496

As you see the price change with options is create a problem in Google Merchant Center and shows price mismatch error. As google says it crawl page source rather than data which is dynamically updated after page load.

### Steps to reproduce

1. Create a configurable product with different prices for the option selected such size x color red $30, size x color blue 40$.

If you now visit the page with the #based url such #100=1 or #100=2 where 100 is the attribute id for size x and 1  & 2 are attribute id for color red and blue respectively. You will see the price changes with a delay.

### Expected result

Expected behavior is the price are updated from server side rather than client side.

### Actual result

Price is update on client side using jquery or javascript which update the price dynamically base on hash value which cause price mismatch errors.

### Additional information

Let me know if additional information required.

### Release note

NA

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @hariwebdeveloper1989,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create a configurable product with different prices for the option selected such size x color red 


Prices are updating when we are updating from the admin side.

<img width="1410" alt="Screenshot 2023-10-26 at 12 36 45 PM" src="https://github.com/magento/magento2/assets/51680745/0b8c300b-e2d7-4a64-b9a2-1a5f760b455b">



<img width="1426" alt="Screenshot 2023-10-26 at 12 36 51 PM" src="https://github.com/magento/magento2/assets/51680745/2284f2e6-2bc6-42a6-9ebb-e92c5c7517f3">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by hariwebdeveloper1989** [comment]
Hi Venkata,

Thank you for jumping on this. Will it be possible to demonstrate the
issue on the call. I can be available at any time of your preference
and we can jump on either a zoom or hangout call to do a screen share.

The issue exist on configurable products with different price and
while accessing the product using hash value.

Regards,
Hari

**Comment by engcom-Bravo** [comment]
Hi @hariwebdeveloper1989,

Thanks for your update.

Could you please record a video if possible please share with us with that one we will proceed further.Please provide us Slack ID so that we can connect via Slack.

If possible please check the issue in Magento 2.4-develop instance and also provide us that particular Hash value to access the Product.

Thanks.

**Comment by hariwebdeveloper1989** [comment]
Hi

Below is my slack id.
U05FKMW87EZ

Please let discuss the issue in realtime as it is difficult for me to capture a video and share here.

Regards,
Hari

**Comment by hariwebdeveloper1989** [comment]
Here is the video recording from two different magento 2 site. So its issue for the URL is there a method
https://www.awesomescreenshot.com/video/22353365

https://www.awesomescreenshot.com/video/22353603

Regards,
Hari

**Comment by engcom-Bravo** [comment]
Hi @hariwebdeveloper1989,

Thanks for your update.

We are not able to access to your provided video.Could you please reshare the video again if possible provide screenshots also.

<img width="979" alt="Screenshot 2023-11-14 at 11 40 02 AM" src="https://github.com/magento/magento2/assets/51680745/d5417c8c-c0b7-404a-8f8d-585cf120a9d2">



Thanks.

**Comment by hariwebdeveloper1989** [comment]
Hi,

Updated link
https://www.awesomescreenshot.com/video/22353365?key=b9f7b17c2668365d31f004146712ce14

https://www.awesomescreenshot.com/video/22353603?key=0e53c8836ff08bf2a3c05470641f0cb4

Regards

**Comment by hariwebdeveloper1989** [comment]
Hello,

Also as issue is happening for fraction of second in Google Shopping feed causes price mismatch error.

Regards

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by hariwebdeveloper1989** [comment]
Any Update here @engcom-Bravo

**Comment by hariwebdeveloper1989** [comment]
This is very long ongoing issue from Adobe Forums
https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Magento-2-Configurable-Simple-Products-to-Google-Shopping/td-p/485490

**Comment by hariwebdeveloper1989** [comment]
still waiting

Issues in all magento version. You can try with ant magento version. Can we have a resolution on this

**Comment by Karhal** [comment]
UP
This is unsuitable for any solution connected to Google Merchant center, this issue should be a top priority

**Comment by engcom-Bravo** [comment]
Hi @hariwebdeveloper1989,

Thanks for your update.

We have verified the issue in Magento 2.4 develop instance without Google shopping Feed and the issue is not reproducible.

“Google Shopping Feed” Extension that doesn't come along with latest / default Magento installation. Code of this package is not part of [https://github.com/magento/magento2 git](https://github.com/magento/magento2%C2%A0git) repository. We are not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) or the [Magento Market place](https://marketplace.magento.com/extensions.html) page

Thank you.

**Comment by hariwebdeveloper1989** [comment]
Hi @engcom-Bravo ,

Thanks for  responding. I am not referring to any "Google Shopping Feed" Extension here. I mean by in errors logs of Google Merchant Shopping feed it shows "price mismatch error" for configurable products while reaching to those product through hash url. As the price are modified with help of either javascript or some other script causing price mismatch error. 

Rather than asking for more information and it is global problem accross any version of Magento. I can demonstrate the error.

Please we can reopen this ticket it would be great and it will be good for our community if we can resolve this error.

I can be available at any time / timezone to demonstrate the issue.

Regards,
Hari

**Comment by hariwebdeveloper1989** [comment]
@engcom-Bravo, @magento-admin, @magento-dev27  Can we reopen this as it is valid issue and It is hampering most of clients using different prices for different simple products for a configurable product. We need to resolve this issue as some already move to shopify due to this issue.

**Comment by manish85sixty** [comment]
Did anyone find a solution for this issue?

**Comment by hariwebdeveloper1989** [comment]
@engcom-Bravo, @magento-admin  This issue still exist and it has never resolve. It is issue in default magento code without any third party extension configure and install in a single installation.

**Comment by SloppySyntax** [comment]
Running into the same problem. In 2 years this apparently is still an issue. Did aybody find a workaround for this? Or should we conclude magento is not compatible with probably the most important tool for online marketing?
