### ISSUE TITLE
Unable to Play Videos on Mobile Devices

### ISSUE THREAD

**Issue by Kashyap1999** [magento/magento2#38137]
### Preconditions

- Magento 2.4-develop

### Description

When attempting to play product videos on various mobile devices, such as  Android and iPhone, as well as in the mobile view mode of the Chrome browser on a desktop, the videos are not played and not showing any errors in the console. The video is working properly in desktop view.

Screenshot-1
![image (18)](https://github.com/magento/magento2/assets/124759297/d81de75b-71f4-4bbe-9e86-f611c406145f)

### Steps to reproduce

1. Create a product with Images and video.
2. Visit the product in store front using mobile device or mobile view mode of the Chrome browser on desktop.
3. Play video.

### Expected result
Video will be play on any mobile devices or view mode of the Chrome browser. 

### Actual result
Video is not played on mobile device.

### Additional information

This issue arise after merge [Fix broken fotorama image slider on mobile Fixes #37232 #37355](https://github.com/magento/magento2/pull/37355) PR. 
In this PR solved issue with fotorama Image slider on mobile. 
In Magento 2.4.6-p2 there are not having issue with the video on mobile devices.

File name: [Fotorama.js](https://github.com/vseager/magento2/blob/3598333616d066c4ce4ea2fb8daed53d35f680b6/lib/web/fotorama/fotorama.js#L1143) 
 
Line 1143: `el.addEventListener ? el.addEventListener(e, fn, {passive: !!bool}) : el.attachEvent('on' + e, fn);`

In this line, added {passive: !!bool} for sloving slider issue but it affected on video played in mobile. due to this it started causing an issue with the video played on moble. If we  revert the {passive: !!bool}  to !!bool as per magento 2.4.6-p2 video is played on mobiles but slider issue will cause a problem.

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @Kashyap1999 

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is confirmed as the product videos are not played and not showing any errors in the console on mobile devices.

Please refer the attached video evidences.


https://github.com/magento/magento2/assets/60198592/630b9b10-bff0-43d0-9529-8e5b6a47d760


Thanks

**Comment by stephensfisheye** [comment]
I've had the same issue and through investigation I've created the following patch. This resolves the issue for the 2.4.6-p3 site I'm working on, with the other Fotorama fixes (#37355 and #36578) also applied as patches.

[38137-fotorama-mobile-videos-slider.patch](https://github.com/magento/magento2/files/13283762/38137-fotorama-mobile-videos-slider.patch)

Essentially the fix is to remove the following line: https://github.com/magento/magento2/blob/c333d3253d220834148d1b4a36ff6fe56cea57e2/lib/web/fotorama/fotorama.js#L1484

This seems to have stemmed from the change in the `addEvent` function applying the `bool` argument to the `passive` option for [`addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#usecapture), instead of the `useCapture` argument as it previously did. Referencing: 3598333616d066c4ce4ea2fb8daed53d35f680b6

This feels like more of a 'workaround' than a full solution and therefore may require a more robust/better approach. However, I haven't experienced any problems/different behaviour when testing the patch in Chrome, Firefox or Safari.

**Comment by oa-netigo** [comment]
@stephensfisheye 

Thank you! I tested your fix. It's working, but we have another issue that related to this: 
(The click/tap goes through)
https://github.com/magento/magento2/issues/34886

If I use [this fix](https://github.com/magento/magento2/pull/35017) **and** your fix. The issue of "Close button" returns again.

Perhaps the whole thing really should be looked at more closely and fixed. This is just for information, so that other problems can be looked at in context.

**Comment by buderus199** [comment]
I have applied fix for [Close button not working in a mobile device on product image zoom popup](https://github.com/magento/magento2/issues/34886), but then i get [Unable to Play Videos on Mobile Devices](https://github.com/magento/magento2/issues/38137#top). Is there a way for both patches to coexist?

**Comment by Kashyap1999** [comment]
This issue has been solved in the Magento 2.4-developer branch. I have found the commit [Product pages Vimeo videos not working for mobile devices](https://github.com/magento/magento2/commit/fb12f6e89b6f235e719e97ec5fb9363319083e22) which is merged on 21-Nov-23.

**Comment by FlyingMonkey82** [comment]
After reading through both threads mentioned (https://github.com/magento/magento2/issues/34886 andhttps://github.com/magento/magento2/issues/38137) am I right that our current option is to either be able to play videos or be able to close the pop-up without pressing what is below?

**Comment by buderus199** [comment]
> After reading through both threads mentioned (#34886 and #38137) am I right that our current option is to either be able to play videos or be able to close the pop-up without pressing what is below?

Unfortunately, you're right.
