### ISSUE TITLE
Price indexer running for multiple hours with 2.1 million products

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#38147]
### Preconditions and environment

- 2.4.5-p2

### Steps to reproduce

We have created a website with 45974  configurable products and a total of 2.1 million products with their variations + simple products

Reindexing process crashed  in scheduled mode and for some reasons and we need to reindex them fully. 

Unexpectedly though the reindex process runs for too many hours for the price indexer and this leads to products not displaying in the frontend as in order to reindex the catalog search index and the category products index, the price index must run as well but it takes too long.

Now our frontend is missing products 

Is magento even able to handle the 2.1m products? What can I do to make it run faster? Changing the batch size has no effect whatsoever, the speed is horribly slow. 

### Expected result

All indexers run fast. 

### Actual result

Reindexing is slow. 

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Adel-Magebinary** [comment]
Try this patch

https://github.com/magento/magento2/pull/38050#issuecomment-1782398047

**Comment by hostep** [comment]
Not sure if it is the same issue, but there is a bug in Magento 2.4.x (not in 2.3.x) with the indexers where the partial indexer could loop unnecessarily many times over the same entities to index and sometimes even skip indexing entities it should reindex.
That was fixed in https://github.com/magento/magento2/pull/36155 (which is supposed to be included in Magento 2.4.7)

**Comment by amouri82** [comment]
Hello,
@hostep there is a patch to fix this issue or not yet ? We are facing the same problem and can't wait next release to fix it. Thanks

**Comment by amouri82** [comment]
@hostep Thanks you for your replay and the diff of the PR. I will try to create owr own patch and share it if works.
Thanks.

**Comment by engcom-Dash** [comment]
Hi @ioweb-gr 

Thanks for reporting and collaboration.

As per the above comments the issue is fixed in https://github.com/magento/magento2/pull/36155 in Magento 2.4.7

Please try to reproduce the issue in magneto 2.4.7 and let us know if you still face the issue.

Thanks

**Comment by engcom-Bravo** [comment]
Hi @ioweb-gr,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance with 1M products and the issue is not reproducible.Kindly refer the screenshots.

<img width="1391" alt="Screenshot 2024-11-12 at 13 54 58" src="https://github.com/user-attachments/assets/2569fe3c-0a88-4552-bd89-557eed651764">



<img width="1434" alt="Screenshot 2024-11-12 at 16 11 31" src="https://github.com/user-attachments/assets/54d65ec2-42d4-4ff0-9078-fb01d9f5aafc">



Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by ioweb-gr** [comment]
Actually I lost track of htis issue. It's indeed resolved in 2.4.7-p2 as far as I can see. I never experienced again such long running times for price indexer so we can close it for now. I'll reopen a new issue if I bump into it again.
