### ISSUE TITLE
Special characters in configurable associate product name are  being Converted to HTML Entities.

### ISSUE THREAD

**Issue by imran9935** [magento/magento2#38146]
### Preconditions (*)
I have tested it only below mentioned magento versions,and issue is reproducible.
1. Magento – 2.4.6-p1
2. Magento – 2.4.6-p2

### Description (*)
 When we are using special character " " in configurable product name (screenshot-1) and create configuriotion and save the product then associated varient name is showing perfectly  but second time when we edit that associate product then special character is being change into '&quot'; in associate Product name (screenshot-2).

**Screenshot-1**
![image](https://github.com/magento/magento2/assets/113010604/839f3272-00b3-4a69-8142-dc642e349609)

**Screenshot-2**
![image](https://github.com/magento/magento2/assets/113010604/cfcc6b0e-0882-4664-881f-d62fafc66854)

![image](https://github.com/magento/magento2/assets/113010604/0305645c-188a-4413-a45f-a7a05a24e04c)

### Steps to reproduce (*)
1. Create Configurable Product.
2. Add product name Like Test "config"
3. Create Configuration and Add attribute (color/size) Attributue then select any attribute (color/size) and save the configurable product.
4. Edit the associte product and then observe.

### Expected result (*)
 Special character in Product Name should be not change to html entities when we edit the associate product.

### Actual result (*)
 Special characters in configurable associate product names are  being Converted to html entities.

### Additional Information (*)
As I have checked When Saving a Configurable Product for the First Time then this file is being called Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix.php as on line no 377 (Screenshot-3) where escapeHtml is not implemented for name and when second time while editing associated for the same configurable product then this file  Magento\ConfigurableProduct\Ui\DataProvider\Product\Form\Modifier\Data\AssociatedProducts.php (Screenshot-4) is being called where on line 308 the escapeHtml method is implemented for the product name.

**Screenshot-3**
![image](https://github.com/magento/magento2/assets/113010604/338283b4-f90a-40e3-86c8-f80a59970c54)

**Screenshot-4**
![image](https://github.com/magento/magento2/assets/113010604/e2d403f2-8d56-4a6f-ba2f-de0cf34ee198)

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @imran9935,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Create Configurable Product.
- Add product name Like Test "config"
- Create Configuration and Add attribute (color/size) Attributue then select any attribute (color/size) and save the configurable product.
- Edit the associte product and then observe.


![Test-config-Products-Inventory-Catalog-Magento-Admin](https://github.com/magento/magento2/assets/51680745/182f8617-e650-4382-b6b5-04ce0e0d9626)




<img width="1078" alt="Screenshot 2023-11-08 at 12 15 21 PM" src="https://github.com/magento/magento2/assets/51680745/08797c0d-d84b-4d53-b3ce-ac21523b3337">


Special character in Product Name not changing to html entities when we editing the associate product.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by imran9935** [comment]
Hi @engcom-Bravo ,
I think you are are editing the associate product by opening that product , could you please try to edit the associate product by using Edit configuration, please  Check out the below video.

https://www.awesomescreenshot.com/video/22315119?key=bdd194d510619bc4be31899d222e0d7f

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @imran9935,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Create Configurable Product.
- Add product name Like Test "config"
- Create Configuration and Add attribute (color/size) Attributue then select any attribute (color/size) and save the configurable product.
- Edit the associte product and then observe.


<img width="1220" alt="Screenshot 2023-11-09 at 1 24 59 PM" src="https://github.com/magento/magento2/assets/51680745/27fc84e4-1aa6-4176-a2ed-efcaf09a7def">



<img width="1434" alt="Screenshot 2023-11-09 at 1 24 41 PM" src="https://github.com/magento/magento2/assets/51680745/315d55f8-ec2b-4ead-a40c-f6e7565cd49f">



While editing the Configurations Special characters in configurable associate product names are being Converted to html entities.

Hence Confirming the issue.

Thanks.
