### ISSUE TITLE
No timezone offsets for catalog events

### ISSUE THREAD

**Issue by samtay** [magento/magento2#3815]
## Steps to reproduce
1. Install Magento from `develop` branch using timezone EST with server time UTC.
2. Create a "Test" category
3. Create a new Catalog Event in the admin panel from different timezones. I had people connect to my local site from different timezones.
## Expected result
1. GMT offset occurs properly
## Actual result
1. GMT offset does not occur properly. For instance if I navigate to the admin panel on my local machine running UTC, and set the event expiration to `2016-03-16 15:18:00` (2 minutes greater than what my computer is currently displaying), I would expect the frontend to show that there are 2 minutes left on the sale. Instead, it does not offset that saved datetime, and interprets it as EST on the frontend so that the event expires in 4 hours and 2 minutes.
## 

If no one can get around to a fix, please at least respond with a way to do this or some other example in core code where this is done correctly. I am creating a scheduler for CMS content and need examples on how to do this in Magento 2.

**Comment by antboiko** [comment]
Hello @SamTay , sorry for the late reply. We've created internal ticket MAGETWO-52986 to investigate this issue.

Best,
Anton.

**Comment by katmoon** [comment]
Hi @SamTay 

Magento Admin expects date/time to be set in Magento timezone, EST in your case.
So if your local machine is in UTC, you should set `2016-03-16 11:18:00` in Admin. This applies to any functionality in Admin, not only CatalogEvents.

@antboiko This is indeed not obvious and we raised this question several times. There was a proposition to add a time clock in Admin so that it's clear what is 'current time' for Admin at least.

@SamTay I'm closing the issue for now as this is the expected behavior. Feel free to reopen it if you have any questions left.

Thanks,
Kateryna.
