### ISSUE TITLE
Error when apply gift cards with discount (coupon) 100%

### ISSUE THREAD

**Issue by Mr8Duck** [magento/magento2#38157]
### Preconditions and environment

- Magento version: 2.4.5
- Install sample data

### Steps to reproduce

1. Tax configuration
On Stores -> Configuration -> Sales -> Tax
![tax-config](https://github.com/magento/magento2/assets/48816311/6efb8472-229a-4e09-aa37-2c5a0eecadb4)
2. Create gift cards
![2023-11-08_13-47](https://github.com/magento/magento2/assets/48816311/c867c9cb-a3d6-49e5-bbaf-cdc96ffcacff)
3. Create coupon 
![coupon](https://github.com/magento/magento2/assets/48816311/10d31639-415c-465b-b3e8-0f0f19bca66d)
4. Add to cart
5. Go to Shopping cart
6. Apply coupon code
7. Apply gift carts

### Expected result

**The sumary is shown as well.**

### Actual result

**The sumary is not shown as well.**
Shopping cart.
![cart](https://github.com/magento/magento2/assets/48816311/489a9ff8-f80e-4d93-8dab-8358741237e6)

Checkout page.
![payment](https://github.com/magento/magento2/assets/48816311/235dd971-c6c6-4372-9aeb-83ac4f4a983b)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Mr8Duck,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Tax configuration
On Stores -> Configuration -> Sales -> Tax
- Create gift cards
- Create coupon
- Add to cart
- Go to Shopping cart
- Apply coupon code
- Apply gift carts

Discount is applying 100% as per the cart price rule and Gift card account.

<img width="1397" alt="Screenshot 2023-11-13 at 2 20 02 PM" src="https://github.com/magento/magento2/assets/51680745/ec62488e-c36c-44b7-8f8b-7a0e719ae50e">


Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by Mr8Duck** [comment]
Hi @engcom-Bravo,
Thanks for checking it.
I check config and I mising something:

![2023-11-15_10-10](https://github.com/magento/magento2/assets/48816311/ed14b742-840a-4863-bfb7-637824d5e0e2)

I updated it and everything was ok.


Thanks.
