### ISSUE TITLE
Jquery widget Icons doesn't work

### ISSUE THREAD

**Issue by quienti** [magento/magento2#3816]
## Steps to reproduce
1. Magento 2.0.2
2. Use doc at http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/jquery-widgets-about.html
3. Use this code : `$("#accordion").accordion({ multipleCollapsible: false, icons: {header: "icon-triangle-1-e", activeHeader: "icon-triangle-1-s"}, heightStyle: "content" });`
## Expected result
1. Accordion with icons
## Actual result
1. Accordion without icons
2. I tested with other 'Jquery Widget' and it doesn't work too.

**Comment by MomotenkoNatalia** [comment]
Hi @quienti ! Thanks for reporting this issue! Internal ticket MAGETWO-50974

**Comment by almarchenko** [comment]
Hi @quienti, thank you for reaching us. I've updated the docs, having added a note about using jQuery UI style, and corrected the names of the styles in code sample.
http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/jquery-widgets-about.html

**Comment by quienti** [comment]
Thank you for your reply.

I thought that was directly integrated into Magento
But, I will try that

Thank you

**Comment by quienti** [comment]
@almarchenko, import juery-ui.css work fine ^^
But, import can break magento design

I use this in a custom module
`<css src="css/jquery-ui.min.css"/>`

And Magento menu are complety break ^^

**Comment by almarchenko** [comment]
@quienti i'm sorry to hear this. Developers will take a look and we will get back to you!

**Comment by quienti** [comment]
Thank you, i'm waiting !

**Comment by zanilee** [comment]
Hi, @quienti!

Unfortunately, at the moment you can't use jQuery UI styles "as is", because they can affect both storefront and admin themes (in fact, you've already seen that :) )

To add accordion icons, you should write your own styles or use just the part of jQuery UI styles, which are adding icons to accordions where you need them.

[The documentation is updated](http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/jquery-widgets-about.html#info)

Thank you

**Comment by quienti** [comment]
Okay, Thank for your answer
I will do my own styles so

But, I hope you can find a best solution for this !

**Comment by piotrekkaminski** [comment]
Documentation was updated
