### ISSUE TITLE
translation in emails does not work, email templates broken

### ISSUE THREAD

**Issue by tobiasolge** [magento/magento2#38237]
Hi, 
sometimes email templates do not use translations.
in our case this is regarding Shipment emails at the moment. The problem also occured on others. I was unable to find the string "Ihre Bestellung" anywhere in my magento2 installation. We translated to "Deine Bestellung". I have no clue, where that translation comes from.

What I can see is, that when the translation is not working, the entire template is broken. First letter from Links is removed. (ttp:// instead of http://)
![image](https://github.com/magento/magento2/assets/13048553/25c7557f-daab-447b-bf9b-94ae6c940505)

This happens randomly. One was broken and 20 were broken.

Magento ver. 2.4.6-p1

_Originally posted by @tobiasolge in https://github.com/magento/magento2/issues/37507#issuecomment-1831739287_

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @tobiasolge 

Thanks for reporting and collaboration.

Verified the issue on magneto developer instance and the issue is reproducible. Email templates are broken, the translations in the email is different from the template. Please refer the attached screenshots

<img width="1440" alt="passwordresettemplate" src="https://github.com/magento/magento2/assets/60198592/c38cdc5a-f7bf-4942-aa2e-b54528b6894b">
<img width="1440" alt="Resetpasswordemail" src="https://github.com/magento/magento2/assets/60198592/63e00eae-2346-4ff4-ab2c-2ce59483f454">

**Comment by engcom-Dash** [comment]
Hi @tobiasolge 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4-develop instance and not able to reproduce the issue. 
Translations in the emails are working fine and the links are not broken.
Please let us know if you are using any third party tools. Thanks.
