### ISSUE TITLE
Backend order overview screen: Backordered quantity not visible on order item level

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#38252]
### Preconditions and environment

- 2.4.6-p3

### Steps to reproduce

- Have a product which allows backorders
- Create an order with a product that allows backorders and make sure there's no current inventory for that item
- When the order has an invoice the item status is "invoiced" and doesn't show that the order has been backordered
- The quantity column shows that the number of items that is ordered, invoiced & shipped, but doesn't show the number of backordered items

### Expected result

Show the number of items that are in backorder based on the data in the sales_order_item table.

### Actual result

The quantity column shows that the number of items that is ordered, invoiced & shipped, but doesn't show the number of backordered items

![image](https://github.com/magento/magento2/assets/1058480/f9eddd41-7fc9-47ec-94fa-5a6a640611db)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @dverkade,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance.Kindly refer the screenshots.


- Steps to reproduce
- Have a product which allows backorders
- Create an order with a product that allows backorders and make sure there's no current inventory for that item
- When the order has an invoice the item status is "invoiced" and doesn't show that the order has been backordered
- The quantity column shows that the number of items that is ordered, invoiced & shipped, but doesn't show the number of backordered items

We have ordered with product backorders allowed and there is no current inventory for it.
![-000000006-Orders-Operations-Sales-Magento-Admin](https://github.com/magento/magento2/assets/51680745/189e6a84-869b-41b1-81f0-6dd66779fd29)


![New-Shipment-Shipments-Operations-Sales-Magento-Admin](https://github.com/magento/magento2/assets/51680745/2a12050b-93bb-4d9a-b82d-343021626c9d)


After invoicing there is no information regarding backorders information in qty column.

Here we are not able to proceed with the shipments could you please let us know if we are missing anything here.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @dverkade,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38252#issuecomment-1849860049 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by dverkade** [comment]
The screenshot exactly shows the problem. It only shows "Ordered" and "Invoiced" quantity. Backordered is not being shown. However that data is present in the sales_order_item table and should be presented to the user.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @dverkade,

Thanks for your update.

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Have a product which allows backorders
- Create an order with a product that allows backorders and make sure there's no current inventory for that item
- When the order has an invoice the item status is "invoiced" and doesn't show that the order has been backordered
- The quantity column shows that the number of items that is ordered, invoiced & shipped, but doesn't show the number of backordered items

Before Invoicing and shipment it is showing as backordered.

![Screenshot from 2024-01-11 12-23-43](https://github.com/magento/magento2/assets/51680745/074905fb-3b2e-438c-8d06-af01a6c04dd3)


![Screenshot from 2024-01-11 12-24-47](https://github.com/magento/magento2/assets/51680745/9ccd2389-6bb4-41b0-90d7-b434139aae6d)


After invoicing and product shipment it is not showing status as backordered.

Hence Confirming the issue.

Thanks.
