### ISSUE TITLE
Tier Price is not being deleted from Configurable Product

### ISSUE THREAD

**Issue by bhoopatparmar** [magento/magento2#38390]
### Preconditions (*)

1. Magento 2.4.6-p2
2. Magento 2.4-develop

### Description (*)
The tier price for the configurable product isn’t deleted when a simple product is converted into a configurable product. The Actual price of a product is removed from the database but the tier price  remains there in `catalog_product_entity_tier_price`. It will show the minimum price for the product at the front end even if any child variant of the product isn’t having any tier price. This can lead to a mismatch in the price. See the attached screenshots below.

Screenshot 1:
Here you can see in the screenshot that the simple product has the tier price in the table `catalog_product_entity_tier_price`.
![image](https://github.com/magento/magento2/assets/106948523/995c00bd-9a54-4655-bde8-71673bd24624)

Screenshot 2:
After Converting the simple product into the configurable product by creating the variants, you can see in the below screenshot that the tier price remains there. Even after removing the tier price from all its variants, it remains there in the table `catalog_product_entity_tier_price`.

These things lead in a way to mismatch of the price on a product page.
If you check the product on a category-page/listing-page, you will find the minimum price coming from the tier price available for a  product. But when you visit the product page for the same and check all the variants, you will come to know that there is no minimum price available in any of the child variants of the product.
![image](https://github.com/magento/magento2/assets/106948523/ca0d9675-088f-4978-b9ff-d0028e87ea30)
![image](https://github.com/magento/magento2/assets/106948523/d93389d3-270e-49a8-921f-6e908f3af402)

### Steps to reproduce (*)

1. Create a simple product with a tier price.
2. Edit that simple product and convert it into a configurable product by creating some variants with a price greater than the tier price and make sure that any variant should not have any tier price.
3. Observe in the database that table `catalog_product_entity_tier_price` still has the entry for the particular product with the tier price.
4. Visit the particular product on a listing page and product page and observe the price.

### Expected result (*)

The tier price of the configurable product should also get deleted when a product is converted from a simple product to a configurable product. It should show the minimum price of the variants instead of a tier price of the parent configurable product at the frontend.
### Actual result (*)

The tier price of the configurable product is not deleted when a product is converted from a simple product to a configurable product. It is showing the tier price of a configurable product as a minimum price.

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @bhoopatparmar,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Screenshot from 2024-01-30 12-08-29](https://github.com/magento/magento2/assets/51680745/261cef3b-79aa-49c2-bf9b-2d17ba39df7d)



![Screenshot from 2024-01-30 12-14-42](https://github.com/magento/magento2/assets/51680745/d7fac76d-a1d3-46de-9787-1a0eca0501df)




![Screenshot from 2024-01-30 12-14-17](https://github.com/magento/magento2/assets/51680745/865250ea-9fa3-42a4-ae97-645ee1a8c426)


In Product listing page tier price is showing as expected but in Product detail page tier is not showing but when we select the Configurable product variants it is showing tier price as expected because the configurable product depends on their childs product so it looks like an expected behaviour.

Thanks.

**Comment by bhoopatparmar** [comment]
Hi @engcom-Bravo 
Make sure that the Configurable product variants don't have any tier price. Once the simple product is converted into a configurable product with some variants and the variants are having the same price as the parent product, it will add the same tier price as the parent product to all the variants. So kindly remove the tier price from Configurable product variants. and then if you check tier price will not get deleted for the parent configurable product.

**Comment by engcom-Bravo** [comment]
Hi @bhoopatparmar,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce (*)**

- Create a simple product with a tier price.
- Edit that simple product and convert it into a configurable product by creating some variants with a price greater than the tier price and make sure that any variant should not have any tier price.
- Observe in the database that table catalog_product_entity_tier_price still has the entry for the particular product with the tier price.
- Visit the particular product on a listing page and product page and observe the price.


![Screenshot from 2024-01-31 12-31-34](https://github.com/magento/magento2/assets/51680745/1316d249-68b8-4eb0-816d-0dae8e7a8260)


![Screenshot from 2024-01-31 12-31-52](https://github.com/magento/magento2/assets/51680745/11d99ecd-3460-49ca-a131-9758a8f30d68)


The tier price of the configurable product is not deleted when a product is converted from a simple product to a configurable product. It is showing the tier price of a configurable product as a minimum price.

The issue is in Product Listing Page.

Hence Confirming the issue.

Thanks.
