### ISSUE TITLE
my account add address crash on save

### ISSUE THREAD

**Issue by sheepfy** [magento/magento2#38406]
### Preconditions and environment

On latest magento version

### Steps to reproduce

Go to admin -> Customer Address attributes -> pick one, add some random validation (for example, length validation)
Go to admin -> general -> state -> Set "Allow to Choose State if It is Optional for Country" to NO
Go to my account, try to add/edit an address (i did with edit) that don't have the region field displayed. For example: Finland
Inspect element and remove validation classes for the length validated attribute.
Click save

Expected result: address to be saved
Actual result: Exception #0 (Exception): Warning: Undefined array key "region" in ~/git/magento/vendor/magento/module-customer/Block/Address/Edit.php on line 128

![image](https://github.com/magento/magento2/assets/17467949/f246c17b-d415-4d08-adb0-d0e893276b76)

### Expected result

address to be saved

### Actual result

Exception #0 (Exception): Warning: Undefined array key "region" in ~/git/magento/vendor/magento/module-customer/Block/Address/Edit.php on line 128

### Additional information

![image](https://github.com/magento/magento2/assets/17467949/f246c17b-d415-4d08-adb0-d0e893276b76)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @sheepfy,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video,

**Steps to reproduce**

- Go to admin -> Customer Address attributes -> pick one, add some random validation (for example, length validation)
- Go to admin -> general -> state -> Set "Allow to Choose State if It is Optional for Country" to NO
- Go to my account, try to add/edit an address (i did with edit) that don't have the region field displayed. For example: Finland
- Inspect element and remove validation classes for the length validated attribute.
- Click save

[Screencast from 02-02-24 01:14:32 PM IST.webm](https://github.com/magento/magento2/assets/51680745/5a44328a-332a-4041-80bd-54dc25107bbe)



We are able to save the address.

Could you please let us know if we are missing anything.

Thanks.

**Comment by sheepfy** [comment]
@engcom-Bravo 
Are there any input validation set for the firstname attribute of customer address entity?

**Comment by sheepfy** [comment]
@engcom-Bravo 
You have a validation of length min 1 and max 255 chars.

Before submitting the form, you have to enter an invalid value for firstname. For example, something longer than 255. (but try to add the length input validation of 25 for example, to be shorter)..

If you trigger the validation, it will redirect to edit page with the post form data. And that $_POST it will have region field missing, but the array it will try to access it.

**Comment by sheepfy** [comment]
@engcom-Bravo 
the point of removing the css classes was to bypass the JS validation

**Comment by engcom-Bravo** [comment]
Hi @sheepfy,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video,

**Steps to reproduce**

Go to admin -> Customer Address attributes -> pick one, add some random validation (for example, length validation)
Go to admin -> general -> state -> Set "Allow to Choose State if It is Optional for Country" to NO
Go to my account, try to add/edit an address (i did with edit) that don't have the region field displayed. For example: Finland
Inspect element and remove validation classes for the length validated attribute.
Click save


[Screencast from 05-02-24 01:28:47 PM IST.webm](https://github.com/magento/magento2/assets/51680745/fd57c32f-56a0-4457-a0db-ad62cc3e9e9e)



We have tried with input validation with 25 .Kindly let us know still if we are missing anything.

Thanks.

**Comment by sheepfy** [comment]
@engcom-Bravo 
My attribute settings: (legnth validation, max 25)
![image](https://github.com/magento/magento2/assets/17467949/ec4d3826-9786-4b75-ad39-7f6111b33108)

Allow to Choose State if It is Optional for Country -> set to NO
![image](https://github.com/magento/magento2/assets/17467949/b8dc391b-c2b4-4351-822c-eab8991e4bae)

See video:


https://github.com/magento/magento2/assets/17467949/69e53272-b99c-4edf-9aee-37908f3da76c

**Comment by sheepfy** [comment]
@engcom-Bravo 
I think you need to have an address saved already and it works only on "edit address" and not on "create new address"

**Comment by engcom-Bravo** [comment]
Hi @sheepfy,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video,

**Steps to reproduce**

- Go to admin -> Customer Address attributes -> pick one, add some random validation (for example, length validation)
- Go to admin -> general -> state -> Set "Allow to Choose State if It is Optional for Country" to NO
- Go to my account, try to add/edit an address (i did with edit) that don't have the region field displayed. For example: Finland
- Inspect element and remove validation classes for the length validated attribute.
- Click save

[Screencast from 06-02-24 02:18:11 PM IST.webm](https://github.com/magento/magento2/assets/51680745/9ba708bb-5df6-462b-b8ff-30d0f045c020)



We are not getting any exception but still the address is not saved. we are getting blank address book page.Could you please let us know if we are missing anything.

Thanks.

**Comment by sheepfy** [comment]
@engcom-Bravo 
For the "we are having an whitepage" version of this issue, you can see the error in var/log/*.log files. 
In order to see the error log on the webpage, you have to enable developer mode with:

~ php bin/magento deploy:mode:set developer


![image](https://github.com/magento/magento2/assets/17467949/98758472-2570-4d7f-aad1-29fa1982a726)

**Comment by engcom-Bravo** [comment]
Hi @sheepfy,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.While saving the address we are getting exception.

Hence Confirming the issue.

Thanks.

**Comment by sheepfy** [comment]
@engcom-Bravo here is also the fix

https://github.com/magento/magento2/pull/38407
