### ISSUE TITLE
Opening the review grid in backoffice can cause session storage to explode if you have a huge amount of reviews

### ISSUE THREAD

**Issue by hostep** [magento/magento2#38402]
### Preconditions and environment

I haven't verified on a vanilla installation of Magento, but we've seen this on a big shop we maintain

- Magento version 2.4.6-p3
- Have a huge amount of product reviews in the database (we have 29.011 at the moment)

### Steps to reproduce

- In the backoffice, go to Marketing > User Content > All Reviews
- you should see a huge amount of reviews (if not, then you haven't checked the preconditions)
- now reload the grid, or apply a filter in one of the columns (like nickname), or go to any other page in the backoffice

### Expected result

You are not being logged out of the backoffice.

### Actual result

You are being logged out of the backoffice. And you'll see a warning like this in the `var/log/system.log` file:
```
[2024-02-01T09:26:36.192399+00:00] main.WARNING: Session size of xxxxxx exceeded allowed session max size of 256000. [] []
```
Where xxxxxx is bigger than 256000 (in our case it's 622643)

### Additional information

This happens because all the items are being stored in the session over here: https://github.com/magento/magento2/blob/984630670aa9ffb711b3169f1c1a15ea5cc4f052/app/code/Magento/Review/Helper/Action/Pager.php#L74

No idea why this is done this way, it doesn't sound like the best idea to do it like this.
This should be rewritten to avoid storing all the items in the session.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @hostep 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance with atleast 30000 reviews and the issue is reproducable.

When we login into mangeto backend which has huge number of reviews in database , navigate to marketing->reviews and do some action the user is logged out automatically.

Please refer the screen recording attached.

https://github.com/magento/magento2/assets/60198592/06c324c4-e5da-47fa-8046-f2970c9b822b

<img width="1440" alt="Screenshot 2024-02-07 at 11 55 15 AM" src="https://github.com/magento/magento2/assets/60198592/fff79e6c-e812-4086-9b82-c8b633299403">

hence, confirming this issue.

**Comment by rogerdz** [comment]
same https://github.com/magento/magento2/issues/38198

**Comment by engcom-Dash** [comment]
Hi @hostep 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance but the issue is no longer reproducible.

We are not being logged out of the back office.

Steps to reproduce
In the backoffice, go to Marketing > User Content > All Reviews
you should see a huge amount of reviews (if not, then you haven't checked the preconditions)
now reload the grid, or apply a filter in one of the columns (like nickname), or go to any other page in the backoffice

Please take a look at the screenshots I've attached.

<img width="1403" alt="Screenshot 1946-03-21 at 11 38 50 PM" src="https://github.com/magento/magento2/assets/60198592/c891e481-1dfb-4feb-a5d2-a1a5619fac91">
<img width="1258" alt="Screenshot 1946-03-21 at 11 39 47 PM" src="https://github.com/magento/magento2/assets/60198592/9ce5f3fc-afc7-41e7-a0ff-f40449fe13b1">
<img width="1433" alt="Screenshot 1946-03-21 at 11 40 12 PM" src="https://github.com/magento/magento2/assets/60198592/f641b7c1-3a50-4c1b-9649-d78010f23588">

**Comment by hostep** [comment]
@engcom-Dash: if I understand your script correctly, it means you created only 10 reviews? `10 !== huge amount`, right?
Try creating 30.000 reviews, and then retry it?

But maybe hold of, the problem was indeed already confirmed by your colleague @engcom-November in https://github.com/magento/magento2/issues/38198
Do we know the progress on that one? You guys created an internal ticket (AC-10627) over 6 months ago, has work on it already started to get it fixed?

Anyway, let's close this issue as it duplicates the other one.
