### ISSUE TITLE
Created_at are 0000-00-00 00:00:00 

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#38419]
### Preconditions and environment

- Magento 2.4.6-p3
- System locale Dutch (nl_NL)

### Steps to reproduce

Create product in backend.
Set created at to any value
Save product

### Expected result

Created at should be saved properly.

### Actual result

Created at that visible in admin backend is always today.
Database value is 0000-00-00 00:00:00

field updated_at is correct.
See attached video:
https://www.awesomescreenshot.com/video/24664538?key=27ef5d47a651e75131df30d53d2ac3dd

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @Naberdz,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Screenshot from 2024-02-06 11-02-13](https://github.com/magento/magento2/assets/51680745/633517ee-d77c-43e5-8e30-9a7850fb905a)


![Screenshot from 2024-02-06 11-08-04](https://github.com/magento/magento2/assets/51680745/dc71b379-7800-4c74-9827-3c48bc33ac2b)

Created at is saved properly.

Kindly recheck the issue in Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Naberdz** [comment]
i see what is wrong in this case. if you set created at field in database **catalog_eav_attribute** table as visible, it will cause such problem.
