### ISSUE TITLE
245-p6 - unable to view media folders and files when a file is present in any subdirectory of pub/media with a space in the filename

### ISSUE THREAD

**Issue by pixiemediaweb** [magento/magento2#38463]
### Preconditions and environment

- Magento 2.4.5-p6
- Upgrade to p6.  Go to the admin panel, open a CMS page or block, click Insert Image.

### Steps to reproduce

Login to Admin
Go to a CMS page or block
Click 'insert image'
If you have any file in the pub/media/* location (even nested folders) that contains a space in the filename, you will not be able to see folder and files in the insert image popup.

### Expected result

Should be able to see media folders and image assets

### Actual result

No folders or image assets

### Additional information

The issue is due to having any file in the /pub/media/ location (and below) that contains a space in the filename.   You can make it reveal problematic files by running;

bin/magento media-gallery:sync

Though this will only tell you one file issue at a time.  Once you find and update the reported filenames, the gallery works again as expected, though in most cases this is unrealistic for a merchant to do themselves.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @pixiemediaweb,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Login to Admin
- Go to a CMS page or block
- Click 'insert image'
- If you have any file in the pub/media/* location (even nested folders) that contains a space in the filename, you will not be able to see folder and files in the insert image popup.



![Screenshot from 2024-02-23 12-48-38](https://github.com/magento/magento2/assets/51680745/5b3fd3aa-5232-4fbb-a367-121ccb22d681)



![Screenshot from 2024-02-23 12-49-20](https://github.com/magento/magento2/assets/51680745/4a61015c-336f-4003-a1a7-9485ad269485)



We are able to get the folders from pub/media/* location.

Kindly check the issue in Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by pixiemediaweb** [comment]
Hi @engcom-Bravo - you need to upload a file in the /pub/media/ directory that has a space in the filename.  This needs to a manual upload as the wywisyg will automatically rename it if you upload from there.

Here is an example of the output you get from bin/magento media-gallery:sync when there is a file with a space in it;

`Path "/var/www/dev/pub/media/my image name.jpg" cannot be used with directory "/var/www/dev/pub/media/"`

Thanks

**Comment by engcom-Bravo** [comment]
Hi @pixiemediaweb,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Screenshot from 2024-02-26 12-50-45](https://github.com/magento/magento2/assets/51680745/33ebf376-1c20-41f9-ab70-ac1ff7d521c5)



![Screenshot from 2024-02-26 12-51-02](https://github.com/magento/magento2/assets/51680745/60a5b1c7-4ed3-476c-9454-fdf91b59b711)


We have uploaded a file in the /pub/media/ directory that has a space in the filename and the command bin/magento media-gallery:sync completed successfully.

Kindly check the issue in Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by jaminion** [comment]
Hello @engcom-Bravo and @pixiemediaweb ,

I'm having a similar problem with a file that our custom code generates under var/export for some of our custom reports, as we have the file set up to be named like "<site name> - <report name> - <date>.xlsx", the spaces around hyphens are triggering it. It's coming from the following `preg_match()` call which was added to the frontend of an if check in the `validate()` method in the magento/framework's `Filesystem/Directory/PathValidator.php`:

```php
        if (preg_match('/(?:^-|\s-)/', $path)
            || (
                mb_strpos($actualPath, $realDirectoryPath) !== 0
                && rtrim($path, DIRECTORY_SEPARATOR) !== $realDirectoryPath
            )
        ) {
```

It's the `\s-` portion of the preg_match check that is triggering it. This also prevents filenames which start with a hyphen.

Note that the current version of this magento/framework:Filesystem/Directory/PathValidator.php file in the available source code for the 2.4-develop branch does not have this preg_match() function in it. This preg_match() check was not included in the previous release, 2.4.5-p5, but it is showing in the 2.4.5-p6 tagged version: https://github.com/magento/magento2/blob/2.4.5-p6/lib/internal/Magento/Framework/Filesystem/Directory/PathValidator.php. The 2.4.7-beta2 version of the file also does not have it included: https://github.com/magento/magento2/blob/2.4.7-beta2/lib/internal/Magento/Framework/Filesystem/Directory/PathValidator.php, but I guess that's from back in October and we can probably expect the 2.4.7-beta3 coming in a couple of weeks to include it.

It feels like this code is intended as helping to fix CVE-2024-20720 (Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')), and they are not otherwise referenced in the source, I've been spinning wheels trying to figure out how it got injected into my composer-based sites and it turns out it was packaged that way by Magento.

**Comment by maderlock** [comment]
I think that 2.4-develop does have this in? https://github.com/magento/magento2/blob/a9f88e2428b72e930865eaf57b58b62b3c2379c7/lib/internal/Magento/Framework/Filesystem/Directory/PathValidator.php#L57

I'm seeing the same issue that has appeared on upgrading 2.4.5-p5 to 2.4.5-p6.

The effect we're seeing is that file upload does not even show directories:
![image (27)](https://github.com/magento/magento2/assets/630320/98e74837-8d36-4b86-ae7c-29064fa28474)
I can understand that import fails. That seems to be what this validation should be doing:
![image (28)](https://github.com/magento/magento2/assets/630320/bee9b392-1489-4f62-a965-bf81078d73a1)

**Comment by jaminion** [comment]
It looks like it was added in a PR yesterday: https://github.com/magento/magento2/commit/a9f88e2428b72e930865eaf57b58b62b3c2379c7#diff-0a86f23a4c8b01db4b820276a15815173b4aa97e8a2f272b9522015150b32551

Prepping for the 2.4.7-beta3 release in a couple weeks, I expect - "Sync 2.4 develop with 2.4.7 beta3 develop".

I have been back and forth on how to handle this but have ended up just changing file names. I'm not in a position where I can argue with an auditor over the exploitability of a CVE if I was to try and adjust that back through a composer patch, and I'm not certain it's tied to that CVE - just my best guess. Would probably be best if this new restriction of file names was mentioned as known issues in the release notes.

I have been using `find pub/media -name '* \-*' -print` to look for files which would trigger it and working through adjustments to those.

**Comment by nathanjosiah** [comment]
I am aware of this issue and having my team take a look.

**Comment by nathanjosiah** [comment]
It is intended that files with certain combinations of dashes and or spaces is not allowed. The case that we are trying to understand is from @pixiemediaweb above which shows the error 

> `Path "/var/www/dev/pub/media/my image name.jpg" cannot be used with directory "/var/www/dev/pub/media/"`

We are unable to reproduce a case where only spaces is triggering the error. Can anybody else provide reproduction steps for this specific issue where there are no dashes but you are still getting an error?

**Comment by nathanjosiah** [comment]
Given the lack of response and proof of the use case explained above I'm going to close this ticket. We are going to fix the use case where dashes are not allowed when on their own. For example `My File - Version 1.jpg` will be allowed with our fix. 

Other combinations are not allowed by design. If anybody is seeing the issue that @pixiemediaweb reported where spaces by themselves are not allowed (e.g. `My File.jpg`) please let me know and we can investigate further.

**Comment by ashraf-ktpl** [comment]
@nathanjosiah  @pixiemediaweb  @engcom-Bravo 

I have encountered this same issue.
after Magento Upgrade from  2.4.6-p3 to 2.4.6-p5

Error : Path "amasty/amfile/attach/custom/upload/Installation Instructions - Rintal Zink Exterior Spiral Stairs.pdf" cannot be used with directory "/home/magento/pub/media/"
Exception in /home/magento/vendor/magento/framework/Filesystem/Directory/PathValidator.php:63

Change in PathValidator.php
 --   if (mb_strpos($actualPath, $realDirectoryPath) !== 0
--          && rtrim($path, DIRECTORY_SEPARATOR) !== $realDirectoryPath

++           if (preg_match('/(?:^-|\s-)/', $path)
++              || (
++                  mb_strpos($actualPath, $realDirectoryPath) !== 0
++                  && rtrim($path, DIRECTORY_SEPARATOR) !== $realDirectoryPath

Please check

**Comment by PieterCappelle** [comment]
I'm having the same issue with the import of a Product with an image at the following path `var/import/images/MSII/MS II -B96+.png`. This is a valid filename, but I'm having the same error.

**Comment by PieterCappelle** [comment]
I have created a patch:

```
diff --git a/Filesystem/Directory/PathValidator.php b/Filesystem/Directory/PathValidator.php
index 342f399..2e76c27 100644
--- a/Filesystem/Directory/PathValidator.php
+++ b/Filesystem/Directory/PathValidator.php
@@ -54,11 +54,9 @@ class PathValidator implements PathValidatorInterface
             $actualPath = $this->driver->getRealPathSafety($path);
         }

-        if (preg_match('/(?:^-|\s-)/', $path)
-            || (
-                mb_strpos($actualPath, $realDirectoryPath) !== 0
-                && rtrim($path, DIRECTORY_SEPARATOR) !== $realDirectoryPath
-            )
+        if (
+            mb_strpos($actualPath, $realDirectoryPath) !== 0
+            && rtrim($path, DIRECTORY_SEPARATOR) !== $realDirectoryPath
         ) {
             throw new ValidatorException(
                 new Phrase(
```

Add it to composer.json

```
    "extra": {
        "magento-force": "override",
        "composer-exit-on-patch-failure": true,
        "patches": {
            "magento/framework": {
                "Fix PathValidator, ignore regex": "patches/composer/github-issue-38463.diff"
            }
        }
    }
    ```

**Comment by hnsr** [comment]
@PieterCappelle Your patch is much appreciated. Seems this issue is still present in 2.4.6-p10

**Comment by hnsr** [comment]
This one applies to 2.4.6-p10:

```patch
Fix issue with media gallery directories not showing in backend, see https://github.com/magento/magento2/issues/38463#issuecomment-2234393043

@package magento/framework

diff -Nru magento/framework-orig/Filesystem/Directory/PathValidator.php magento/framework/Filesystem/Directory/PathValidator.php
--- magento/framework-orig/Filesystem/Directory/PathValidator.php	2025-03-28 18:37:22
+++ magento/framework/Filesystem/Directory/PathValidator.php	2025-04-18 12:26:11
@@ -54,11 +54,9 @@
             $actualPath = $this->driver->getRealPathSafety($path);
         }

-        if (preg_match('/(?:^-|\s-\S)/', $path)
-            || (
-                mb_strpos($actualPath, $realDirectoryPath) !== 0
-                && rtrim($path, DIRECTORY_SEPARATOR) !== $realDirectoryPath
-            )
+        if (
+            mb_strpos($actualPath, $realDirectoryPath) !== 0
+            && rtrim($path, DIRECTORY_SEPARATOR) !== $realDirectoryPath
         ) {
             throw new ValidatorException(
                 new Phrase(

```

**Comment by hnsr** [comment]
Note that our case, the file pattern that broke things was `-foo-bar_baz.jpg`

I have a small suspicion that the most recent security update (2.4.6-p10) tweaked this regex, since the patch previously provided did not apply cleanly, and our media gallery broke and became unusable after the security update, while the  `-foo-bar_baz.jpg` was uploaded long ago.

**Comment by thomas-kl1** [comment]
We do have the same issue @hnsr after the latest security patch, we also had a file starting with an hyphen (and one before the extension).
