### ISSUE TITLE
Sales order report not being displayed, error with date formatting in UI

### ISSUE THREAD

**Issue by jmonrove** [magento/magento2#38589]
### Preconditions and environment

- Magento ver. 2.4.6-p4
- PHP 8.1.2
- Linux hosted apache2.4

### Steps to reproduce

Log into admin
Go to Reports -> Sales -> Orders
Select date range from 4/1/24 thru 4/8/24 using the date selector.
Click on show report

Observe logs while doing this, you should see an error as below
main.CRITICAL: PDOException: SQLSTATE[HY000]: General error: 1525 Incorrect DATE value: '04/01/2024' in /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:90

Now do the same thing again, but this time type manually in MySQL format the date so 20240401 and 20240408, watch it work.... 

### Expected result

A report is pulled for the dates reported

### Actual result

Nothing happens, says the report is generated but no information is shown, there is an error in the logs with a stacktrace referencing an invalid date

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by davirs** [comment]
exactly the same error here.
Magento 2.4.6-p3 with php 8.2
I've already checked the server and bank schedules, they are aligned.

The report I receive is this:

`#121 {main} {"exception":"[object] (Zend_Db_Statement_Exception(code: 0): SQLSTATE[HY000]: General error: 1525 Incorrect DATE value: '3/31/24', query was: SELECT sum(orders_count) AS `orders_count`, sum(orders_invoiced) AS `orders_invoiced`, sum(invoiced) AS `invoiced`, sum(invoiced_captured) AS `invoiced_captured`, sum(invoiced_not_captured) AS `invoiced_not_captured` FROM `sales_invoiced_aggregated_order` WHERE (period >= '3/1/24') AND (period <= '3/31/24') AND (store_id IN(1)) at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109)
[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1525 Incorrect DATE value: '3/31/24' at /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:90)"} []`

I use UTC-3 here.
it seems that this would be correct: the dates '3/1/24' and '3/31/24' to the format YYYY-MM-DD.

Literally no reports of any kind are generated. It's a general bug.

**Comment by davirs** [comment]
@andrei-lisovski Thanks for sharing! This problem was actually very difficult, if you hadn't helped I would never have found out.
I'm really very disappointed with Magento because every time I face a different bug and most of the time there is no solution, only alternative solutions.

So I would like to thank you again for your help! I know a lot of people will use this fix.

I'll leave the patch here ready for anyone who wants it:
1 - create this file called: reverter-laminas-filter.patch
```
--- a/laminas-filter/src/FilterChain.php
+++ b/laminas-filter/src/FilterChain.php
@@ -87,7 +87,7 @@
                     foreach ($value as $spec) {
                         $callback = $spec['callback'] ?? false;
                         $priority = $spec['priority'] ?? static::DEFAULT_PRIORITY;
-                        if (is_callable($callback)) {
+                        if ($callback) {
                             $this->attach($callback, $priority);
                         }
                     }
```

2 - put it into your patches folder, in this case /patches/ at the root directory
3 - Make sure you have cweagans installed to apply the patch.
(these are SSH commands)

Check package: `composer show cweagans/*`

Install the package: `composer require cweagans/composer-patches`

4 - Make a copy of your composer.json and save it, just in case.
5 - At the end of your composer.json add the following code for the patch to be applied. Note that you need to specify the correct patch file path:

`        "extra": {
            "magento-force": "override",
            "patches": {
                "laminas/laminas-filter": {
                    "Resolve o erro 1525 Incorrect DATE value nos relatórios": "patches/reverter-laminas-filter.patch"
                }
            }
        }`

5 - Apply Patches: With the patches properly defined in your composer.json, you will need to update your dependencies for Composer to apply the patches. This can be done with the following command:

`composer install`

Or, if you already installed your dependencies and just added new patches:
`composer update`


If everything goes well, the patch will be applied and you will follow it on the console. If necessary, review the procedures above.
Remembering that you must run the basic Magento commands of upgrade, cleaning and deploy.

I hope I contributed.

**Comment by Bashev** [comment]
Simple workaround was mentioned here https://github.com/magento/magento2/issues/38596#issuecomment-2047786135: 
```compose require laminas/laminas-filter:2.34.0```

**Comment by Bashev** [comment]
Issue was fixed in [laminas-filter](https://github.com/laminas/laminas-filter/releases/tag/2.35.2):2.35.2 and this PR is not required anymore. 

To fix it in current magento installations, just run `composer update laminas/laminas-filter`

**Comment by jmonrove** [comment]
> Issue was fixed in [laminas-filter](https://github.com/laminas/laminas-filter/releases/tag/2.35.2):2.35.2 and this PR is not required anymore.
> 
> To fix it in current magento installations, just run `composer update laminas/laminas-filter`

Confirmed, updating laminas/laminas-filter fixed the issue
