### ISSUE TITLE
[B2B] assignTierPrices endpoint does not takes website_id into account

### ISSUE THREAD

**Issue by zhovnirigor** [magento/magento2#38584]
### Preconditions and environment

- Magento version 2.4.6, 2.4.7
- One or more shared catalogs setup
- Two or more websites exist
- One or more products exist

### Steps to reproduce

1. Make a request to /rest/all/async/bulk/V1/sharedCatalog/bySharedCatalogId/assignTierPrices, payload
`[
  {
    "sharedCatalogId": [your shared catalog ID],
    "prices": [
      {
        "price": 1.12,
        "price_type": "fixed",
        "sku": "[your SKU]",
        "website_id": [your Website ID]
      }
    ]
  }
]`
2. Check the product's identified by [your SKU] tier prices.

### Expected result

Tier prices are assigned as per the website ID specified in the request

### Actual result

Tier prices are assigned to all websites (website_id = 0)

### Additional information

In \Magento\SharedCatalog\Model\AssignTierPrice::execute 
`$rawPriceData['website_id'] = self::DEFAULT_WEBSITE_ID;
`
must be replaced by
`$rawPriceData['website_id'] = $price->getWebsiteId() ?? self::DEFAULT_WEBSITE_ID;
`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by engcom-Delta** [comment]
Hi @zhovnirigor ,

Thanks for reporting and collaboration.

Verified the issue in Magento 2.4 dev commerce instance and the issue is not reproducible.

Preconditions and Environment:

   1.Install commerce edition
   2.Setup one or more shared catalogs 
   3.Create two or more websites 
   4.Create multiple products

Steps to reproduce:

    1.Make a request to /rest/all/async/bulk/V1/sharedCatalog/bySharedCatalogId/assignTierPrices, payload
      [   { "sharedCatalogId": [your shared catalog ID], "prices": [ { "price": price, "price_type": "fixed", "sku": "[your SKU]", 
      "website_id": [your Website ID] } ]   } ]
   2.Check the product's identified by [your SKU] tier prices.
   3.Check the tier prices assigned as per website mentioned.


  Please refer the attached screenshots and let us know if we missed anything.


<img width="1439" alt="Screenshot 2024-04-18 at 10 40 15 PM" src="https://github.com/magento/magento2/assets/51681379/1c99f52b-bd78-4fda-9247-baa3855453e2">


<img width="1421" alt="Screenshot 2024-04-18 at 10 40 55 PM" src="https://github.com/magento/magento2/assets/51681379/1e912f75-8943-43cd-a555-18c393b96db4">


<img width="1027" alt="Screenshot 2024-04-18 at 10 42 15 PM" src="https://github.com/magento/magento2/assets/51681379/7c01ed4f-2bdc-4e87-9f88-0b2b9cee7dce">


<img width="1430" alt="Screenshot 2024-04-18 at 10 43 50 PM" src="https://github.com/magento/magento2/assets/51681379/ec59a982-8e45-404f-aad8-ab8802917ed7">


<img width="1434" alt="Screenshot 2024-04-18 at 10 43 57 PM" src="https://github.com/magento/magento2/assets/51681379/12260f7a-0322-4ab5-8191-d4bdbe9bf490">

**Comment by zhovnirigor** [comment]
I can confirm the result on the screenshots meets the expected results. However, this is not in 2.4.7 version yet, which means will be released later.
