### ISSUE TITLE
Built-in FPC cache is broken in 2.4.7 for some configurations

### ISSUE THREAD

**Issue by thlassche** [magento/magento2#38626]
### Preconditions and environment

- Magento version: 2.4.7
- Use built in FPC
- Have a`MAGE_RUN_CODE` parameter set

### Steps to reproduce

1. Enable built-in FPC
2. Have a **MAGE_RUN_CODE** parameter in your **$_SERVER** array
3. Load a frontend page
4. Load the same page again

### Expected result

Page is cached, and in developer mode a header `X-Magento-Cache-Debug: HIT` is set

### Actual result

Page is  uncached, and in developer mode a header `X-Magento-Cache-Debug: MISS` is set

### Additional information

In 2.4.7 the identifier for saving a page to cache was decoupled from the fetching identifier:

https://github.com/magento/magento2/blob/725b6483932b4bbbbd9f463de80c82914346643d/app/code/Magento/PageCache/Model/App/Request/Http/IdentifierForSave.php#L18

However the fetching identifier has plugins on it that prepend the cache key with some parameters:

https://github.com/magento/magento2/blob/725b6483932b4bbbbd9f463de80c82914346643d/app/code/Magento/PageCache/Model/App/CacheIdentifierPlugin.php#L67

That plugin is not added to the saving part, hence the key will always mismatch if there are additional parameters 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thlassche** [comment]
Workaround, add this in a module:

```
<namespace>\<module>\Plugin\CacheIdentifierPlugin.php
```

```php
<?php
namespace <namespace>\<module>\Plugin;
use Magento\PageCache\Model\App\Request\Http\IdentifierForSave;
use Magento\Store\Model\StoreManager;

class CacheIdentifierPlugin
{
    /**
     * @var \Magento\Framework\View\DesignExceptions
     */
    private $designExceptions;

    /**
     * @var \Magento\Framework\App\RequestInterface
     */
    private $request;

    /**
     * @var \Magento\PageCache\Model\Config
     */
    private $config;

    /**
     * @param \Magento\Framework\View\DesignExceptions $designExceptions
     * @param \Magento\Framework\App\RequestInterface $request
     * @param \Magento\PageCache\Model\Config $config
     */
    public function __construct(
        \Magento\Framework\View\DesignExceptions $designExceptions,
        \Magento\Framework\App\RequestInterface $request,
        \Magento\PageCache\Model\Config $config
    ) {
        $this->designExceptions = $designExceptions;
        $this->request = $request;
        $this->config = $config;
    }
    
    public function afterGetValue(IdentifierForSave $identifier, $result)
    {
        if ($this->config->getType() === \Magento\PageCache\Model\Config::BUILT_IN && $this->config->isEnabled()) {
            $identifierPrefix = '';
            /* @phpstan-ignore-next-line */
            $ruleDesignException = $this->designExceptions->getThemeByRequest($this->request);
            if ($ruleDesignException !== false) {
                $identifierPrefix .= 'DESIGN' . '=' . $ruleDesignException . '|';
            }

            /* @phpstan-ignore-next-line */
            if ($runType = $this->request->getServerValue(StoreManager::PARAM_RUN_TYPE)) {
                $identifierPrefix .= StoreManager::PARAM_RUN_TYPE . '=' .  $runType . '|';
            }

            /* @phpstan-ignore-next-line */
            if ($runCode = $this->request->getServerValue(StoreManager::PARAM_RUN_CODE)) {
                $identifierPrefix .= StoreManager::PARAM_RUN_CODE . '=' . $runCode . '|';
            }

            return $identifierPrefix . $result;

        }
        return $result;
    }
}
```

```
<namespace>\<module>\etc\frontend\di.xml
```


```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">

    <type name="Magento\PageCache\Model\App\Request\Http\IdentifierForSave">
        <plugin name="core-app-area-design-exception-plugin"
                type="<namespace>\<module>\Plugin\CacheIdentifierPlugin" sortOrder="10"/>
    </type>
</config>


```

**Comment by engcom-Hotel** [comment]
Hello @thlassche,

Thanks for the report and collaboration!

We have tried to reproduce the issue in both 2.4.7 and 2.4-develop and the issue is reproducible in both instances. 

But if we remove `MAGE_RUN_CODE`, the `X-Magento-Cache-Debug` is showing as `HIT`. Please refer to the below screenshot for reference:

_**With MAGE_RUN_CODE**_
![247](https://github.com/magento/magento2/assets/51681618/641dde0c-9a13-4b3d-8880-5a5896a59339)

_**Without MAGE_RUN_CODE**_
![247_wo_mageruncode](https://github.com/magento/magento2/assets/51681618/dea15db7-c470-4805-9e45-e05f5d217745)

Hence confirming the issue.

Thanks

**Comment by digitalrisedorset** [comment]
I added a fix with the PR [38646](https://github.com/magento/magento2/pull/38646). There is no automated tests at this time but the fix was added in the 2.4-develop branch and I verified both 2.4.7 and 2.4-develop had this issue

**Comment by ThisIsRuddy** [comment]
Cheers @digitalrisedorset 

[magento-module-page-cache-fpc-identifier.patch](https://github.com/magento/magento2/files/15146945/magento-module-page-cache-fpc-identifier.patch)

**Comment by engcom-Bravo** [comment]
Hi,

Internal team has started to work on it

Thanks.

**Comment by sanmic** [comment]
> Cheers @digitalrisedorset
> 
> [magento-module-page-cache-fpc-identifier.patch](https://github.com/magento/magento2/files/15146945/magento-module-page-cache-fpc-identifier.patch)

I the the file Identifier.php is missing in the patch file.
Also the line "<preference for="Magento\Framework\App\PageCache\IdentifierInterface" type="Magento\PageCache\Model\App\Request\Http\Identifier"/>" is missing in the di.xml file.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11819 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11819&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Comment by vandijkstef** [comment]
@engcom-Bravo Question for some clarity; Can we expect this to land in 2.4.7-p3 as well? If not; can there be an official patch made? The 'related commits' link includes some 20k+ line changes...

**Comment by digitalrisedorset** [comment]
Looking at the commits, 2 of them seem to be where most of the PR size comes from. I'd be happy to compile a patch for 2.4.7-p3 that would only include the files that make the fix working. 
However, we have 2 caveats with this idea:
1. I am no official and I can only offer a fix that I can suggest to the team but cannot assure it will be approved. This patch would only include the first and last commits since I see them as needed and don't see the rest as related
2. I believe the PR I made had some side-effects with functional tests. If this is the case, that would explain the 2 other commits. For this second point, the patch would fix the problem but we could have to live with some functional tests failing 

If you wanted to try this path, I'd be happy to test a possible patch. It would be ideal to be able to liaise with your team when the patch is on the test environment to consolidate the patch integration and possibly help for the official approval to take place.

**Comment by engcom-Hotel** [comment]
Hello @vandijkstef,

Can you please confirm if this issue can be reproducible for you with Redis in the cloud or Varnish configured in your instance?

Thanks

**Comment by vandijkstef** [comment]
@engcom-Hotel I can confirm this issue is existing in mage-2.4.7 and did not magically disappear.

Can you confirm if the resolution of this issue will be (or has been) included in any of the releases in the 2.4.7 line?

**Comment by engcom-Hotel** [comment]
Hello @vandijkstef,

Actually, we are in discussion with PO for this. But is it reproducible for you Redis in the cloud or Varnish configured in your instance? Can you please confirm the same?

Thanks

**Comment by Crashead** [comment]
I can confirm that on my multiwebsite/multistore Magento 2.4.7-p3 with Redis and Varnish, even with applied patch I still have the issue. 
On the Redis service restart the system works normally for about 5 minutes, and they you notice significant perormance drop, especially on Add To Cart CTA. 
I do hope that official patch will come out sooner than later because we cannot wait for official patch to come out in April with Magento 2.4.8

**Comment by dandrikop** [comment]
@engcom-Hotel

I can confirm that the specific issue appears on Magento 2.4.7 with FPC implemented on both Files and Redis. I have not tested Magento 2.4.7 with Varnish. We always talk about multi-store implementations where the routing to the appropriate store view is regulated by the .htaccess file with directives such as the following ones:

SetEnvIf Host fr.dlastore.com MAGE_RUN_CODE=french_dla
SetEnvIf Host fr.dlastore.com MAGE_RUN_TYPE=store

I believe that an official patch should be issued for this problem. There must be many store owners with multi-store implementations who may have upgraded to Magento 2.4.7 and they have not noticed that their store actually works without FPC.

There is only one 3rd party FPC module which works with Magento 2.4.7, but it has other problems, and for this reason I would not like to mention which is that very module.

**Comment by agendartobias** [comment]
any update for this? We have the same problem on 2.4.7-p4

**Comment by sanmic** [comment]
> any update for this? We have the same problem on 2.4.7-p4

2.4.8 release notes:
AC-11819: Built-in FPC cache is broken in 2.4.7 for some configurations

Fix note: The system now correctly caches pages when the MAGE_RUN_CODE parameter is set, ensuring optimal performance. Previously, pages were not being cached under these conditions, leading to potential performance issues.
GitHub issue: https://github.com/magento/magento2/issues/38626
GitHub code contribution: https://github.com/magento/magento2/pull/38646, https://github.com/magento/magento2/commit/0c53bbf7

**Comment by agendartobias** [comment]
Hey, thank you, but is there Quality patch for 2.4.7?

**Comment by dandrikop** [comment]
Hello @digitalrisedorset,

I have not understood the roadmap of this Github issue. Is there any official patch for Magneto 2.4.7 regarding the FPC problem reported herein?

**Comment by dandrikop** [comment]
@digitalrisedorset, @agendartobias, @sanmic, @thlassche, @engcom-Hotel, I tried the patch [315dd68](https://github.com/magento/magento2/commit/315dd68) with Magento 2.4.7-p5 that is supposed to fix the problem on Magneto 2.4.8. Although this patch was successfully installed, the problem persisted on Magento 2.4.7-p5 multi-store implementation. Indeed, if the quality patch ACSD-62591 for Magento 2.4.7 has been installed, it should be reverted; otherwise the [315dd68](https://github.com/magento/magento2/commit/315dd68) cannot be installed.

In any case, things became worse with [315dd68](https://github.com/magento/magento2/commit/315dd68) on Magento 2.4.7 comparing with ACSD-62591. Namely, the pages were not cached in FPC at all with [315dd68](https://github.com/magento/magento2/commit/315dd68).

**Comment by agendartobias** [comment]
@dandrikop so if i revert ACSD-62591 for Magento 2.4.7 and patch it with #315dd68 FPC works for multistore?

**Comment by dandrikop** [comment]
@agendartobias, the situation is as follows with Magento 2.4.7-p5:

1. If no patch is installed, the FPC does not work at all; i.e. the pages are actually cached by FPC but when revisited, Magento cannot locate them in FPC so as to bring them from there. Indeed, if you're on development mode, the HTTP header X-Magento-Cache-Debug is always MISS.
2. If you install the quality patch ACSD-62591, the problem with the HTTP header X-Magento-Cache-Debug is resolved. However, given that the cache keys do not include the environmental variables MAGE_RUN_CODE and MAGE_RUN_TYPE, as it happened till Magento 2.4.6, some Full Page Cache Warmers don't work.
3. If you revert the quality patch ACSD-62591, so as to install the patch [315dd68](https://github.com/magento/magento2/commit/315dd68), then you actually return to point #1 above.

Given that the commit the patch [315dd68](https://github.com/magento/magento2/commit/315dd68) is supposed to resolve the problem on Magento 2.4.8, but it didn't work on Magento 2.4.7, this situation makes me think that the problem may also persist on Magento 2.4.8; i.e. FPC somehow works, but not 3rd party modules related with Full Page Cache Warming.

**Comment by qlhu** [comment]
My sites are multiple stores and FPC doesn't work either after upgrading to 2.4.7-p6. After doing deep investigation, figured FPC broken when there's any AJAX call to an action implementing `\Magento\Framework\App\Action\HttpGetActionInterface`. The \Magento\Framework\App\Response\Http::sendVary() removes X-Magento-Vary cookie to any AJAX call to the acton implementing `\Magento\Framework\App\Action\HttpGetActionInterface`. The commit [4f23095](https://github.com/magento/magento2/commit/4f230951730f785ce3a999afee35d34717ffd795) flags the response as unreachable. I have to revert the commit [4f23095] from my Varnish server.

**Comment by digitalrisedorset** [comment]
Thanks for your comment. From what you’ve described, it sounds like the fix in the PR aligns well with your environment. My advice would be not to modify your Varnish setup, but instead to integrate the change directly from the PR into your codebase.

The core purpose of this change is to ensure the store data is passed correctly, so that the Varnish cache key can reliably identify your site’s pages — and, in turn, make caching behave as expected.
Let me know if you need help applying it.

**Comment by amenk** [comment]
We have a multi store installation which did not cache anymore after the upgrade. We discovered that we had an `MAGE_RUN_TYPE=default` on the main store view. As this is redundant, we removed that line from the VHost and the main store view was cached again, but no the additional store views, which need a MAGE_RUN_CODE to work properly.

Then we we applied https://github.com/magento/magento2/commit/315dd68 on Magento 2.4.7-p8 which fixes the problem, just to notice that the private content is no longer be properly hole-punched (logged in users do not see the customer menu). We use the Hvyä theme and the problem disappears after reverting that patch.

Wondering if anyone else saw this symptoms, too?
