### ISSUE TITLE
Klarna Issue

### ISSUE THREAD

**Issue by dvakerlis** [magento/magento2#38675]
### Preconditions and environment

Version 2.4.5

### Steps to reproduce

After comple the payment in klarna website when its returns to our site we get error 500 in this url /checkout/klarna/updateSession/

### Expected result

Order placed successfully 

### Actual result

No redirect to the success page. It's returns to checkout page and the order not placed

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dvakerlis** [comment]
Reproduced on 2.4.5

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by alicedfisheye** [comment]
**Issue:**
vendor/klarna/module-payments/Controller/Klarna/QuoteStatus.php
Local and CI work as expected as is_active is always true due to the fact it technically errors which allows orders to go through. On live checkout/klarna/authorize callback happens which means that the klarnaQuote is set and does not error.

It then moves out of the try/catch and goes to set is_active again.
$result['is_active'] = $magentoQuote->getIsActive() && $klarnaQuote->isAuthCallbackFailedOrNotStarted();
It sets this to true.

However, the JS vendor/klarna/module-payments/view/frontend/web/js/view/payments/kp.js check to decide if it should call checkout/klarna/authorizationTokenUpdate and then call context.placeOrder(); checks - if (result['is_active'] === '1') {
but since the above has set it to true this will not run and a order will never be placed.

Therefore, the stack trace below will happen.

Magento\Framework\Exception\InputException: An ID is needed. Set the ID and try again. in /var/www/website/releases/20240509084859/vendor/magento/module-sales/Model/OrderRepository.php:133
Stack trace:
#0 /var/www/website/releases/20240509084859/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->get()
#1 /var/www/website/releases/20240509084859/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent()
#2 /var/www/website/releases/20240509084859/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception{closure}()
#3 /var/www/website/releases/20240509084859/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(23): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins()
#4 /var/www/website/releases/20240509084859/vendor/klarna/module-payments/Controller/Klarna/UpdateSession.php(103): Magento\Sales\Model\OrderRepository\Interceptor->get()
#5 /var/www/website/releases/20240509084859/vendor/magento/framework/Interception/Interceptor.php(58): Klarna\Kp\Controller\Klarna\UpdateSession->execute()
#6 /var/www/website/releases/20240509084859/vendor/magento/framework/Interception/Interceptor.php(138): Klarna\Kp\Controller\Klarna\UpdateSession\Interceptor->___callParent()
#7 /var/www/website/releases/20240509084859/vendor/magento/framework/Interception/Interceptor.php(153): Klarna\Kp\Controller\Klarna\UpdateSession\Interceptor->Magento\Framework\Interception{closure}()
#8 /var/www/website/releases/20240509084859/generated/code/Klarna/Kp/Controller/Klarna/UpdateSession/Interceptor.php(23): Klarna\Kp\Controller\Klarna\UpdateSession\Interceptor->___callPlugins()

Apply this patch :)

`diff --git a/Controller/Klarna/QuoteStatus.php b/Controller/Klarna/QuoteStatus.php
index 34a6f20..c6349bb 100644
--- a/Controller/Klarna/QuoteStatus.php
+++ b/Controller/Klarna/QuoteStatus.php
@@ -114,7 +114,7 @@ class QuoteStatus extends CsrfAbstract implements HttpPostActionInterface
         }
 
         $magentoQuote = $this->magentoQuoteRepository->get($klarnaQuote->getQuoteId());
-        $result['is_active'] = $magentoQuote->getIsActive() && $klarnaQuote->isAuthCallbackFailedOrNotStarted();
+        $result['is_active'] = $magentoQuote->getIsActive() && $klarnaQuote->isAuthCallbackFailedOrNotStarted() ? '1' : '0';
 
         return $this->result->getJsonResult(200, $result);
     }
`

This caused me great pain.

**Comment by engcom-Dash** [comment]
Hi @dvakerlis 

Thanks for reporting and collaboration.

The team is working on this issue. We are keeping the issue in On Hold status for now.

Thanks.

**Comment by engcom-Dash** [comment]
Hi @fredden 

We are getting issues while configuring Klarna. we are waiting to fix the related configuration issue.

We will work on the ticket once we fix the configuration issue with Klarna.

Thanks.

**Comment by kristibarbosky** [comment]
FYI: this issue was fixed in the m2-klarna extension per PPP-1266 in v2.2.2

**Comment by engcom-Delta** [comment]
Hi @dvakerlis ,

Thanks for your reporting and collaboration.
As per https://github.com/magento/magento2/issues/38675#issuecomment-2315183359 issue is fixed in m2-klarna extension per PPP-1266 in v2.2.2
Hence closing the ticket. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.
