### ISSUE TITLE
Bundled Product Discount is Applied on Bundled Product Items with already Special Price

### ISSUE THREAD

**Issue by anasshl** [magento/magento2#38674]
### Preconditions and environment

- 2.4.6 -p2

### Steps to reproduce

1. Go to admin panel. 
2. Create New bundle product 
3. Add Bundle Items  Chose some product which has already some special price
4. Add discount to the bundle product for example 20%
6. Check  store front

### Expected result

Only bundle product discount should be applied and shown.

### Actual result

Simple product discount is applied plus bundle product discount.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @anasshl,

Thanks for your reporting and collaboration.

We have verified the issue in Magento 2.4-develop instance and it looks like expected behaviour of magento.

<img width="351" alt="Screenshot 2024-04-29 at 16 58 24" src="https://github.com/magento/magento2/assets/51680745/5257a84e-e07a-4e17-93a0-46b06abb0a96">


Simple product already having discount and again we are adding discount for bundle product so in that case discount will apply for both.Bundle product prices depends on the products which we are adding.it is an expected behaviour.

Thanks.

**Comment by anasshl** [comment]
Hi, thank you for your reply.
I'm wondering if there's a way to apply only the discount of the bundle product and override the previous discount.

**Comment by engcom-Bravo** [comment]
Hi @anasshl,

Thanks for your update.

We are considering this as a improvement to proceed further we are marking this as a feature request.

Thanks.

**Comment by anasshl** [comment]
Thank you so much for your feedback :)
