### ISSUE TITLE
[Issue] Sales Rules regression in 2.4.7

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38671]
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create a sales rule with : 
   - Coupon code = test
   - No limitation
   - No conditions
   - Action = Fixed amount for whole cart, 1€ discount
   - Apply to Shipping Amount = yes
   - Product condition = name equals to "any_text_that_is_not_a_product_name"
 2. Apply 'test' coupon to a frontend cart with a shipping amount. 

### Expected result

Rule is applied. Discount of 1€ is applied on shipping amount

### Actual result

Cannot add coupon to cart (invalid coupon)

### Additional information

We had rules like this to add discount on shipping amount (and shipping amount only). It worked perfectly in previous versions, but does not work anymore in 2.4.7.

Regression happened in this commit : https://github.com/magento/magento2/commit/79d57b4eb7696bb0fc2ce3aad03f5d6bec1ae275 where line `$this->rulesApplier->maintainAddressCouponCode($address, $rule, $this->getCouponCode());` has been removed. @sivaschenko / @bl4de  : was there a reason ?

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @Nuranto 

Thanks for reproting and collaboration.

Verified the issue on both 2.4 dev and 2.4.7 instances but the issue is not reproducable.

Steps to reproduce

1. Create a sales rule with :

Coupon code = test
No limitation
No conditions
Action = Fixed amount for whole cart, 1€ discount
Apply to Shipping Amount = yes
Product condition = name equals to "any_text_that_is_not_a_product_name"

2. Apply 'test' coupon to a frontend cart with a shipping amount.

We are able to apply the coupon code successfully.

Please refer the attached screenshots. Let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-04-29 at 12 46 17 PM" src="https://github.com/magento/magento2/assets/60198592/95aef135-a3fa-4ab0-addf-1a3c458e26ce">

**Comment by Nuranto** [comment]
Hello @engcom-Dash 
On your Magento Instance, there's not product condition : 
![Capture d’écran 2024-04-29 à 10 20 34](https://github.com/magento/magento2/assets/1633463/f3543817-02d7-4493-8252-fa175c176c14)

I added one : 
![Capture d’écran 2024-04-29 à 10 23 24](https://github.com/magento/magento2/assets/1633463/b40b11db-42f3-4eec-8b25-e8ccd73dbe05)


And now : 
![Capture d’écran 2024-04-29 à 10 22 56](https://github.com/magento/magento2/assets/1633463/032a2373-2b8b-4236-92e5-d8c1dcf2c9d8)

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11876 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11876&type=commits


Thanks
