### ISSUE TITLE
Upgrading from 2.4.6-p5 to 2.4.7 not compiling

### ISSUE THREAD

**Issue by will-wright1** [magento/magento2#38689]
### Preconditions and environment

Upgrading from 2.4.6-p5 to 2.4.7

Blank environment, no modules, new database etc

### Steps to reproduce

When running setup:di:compile it gets to 11% and stops. I've tried with a blank copy of 2.4.6-p5 and on a different server and still get the same issue.

php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 115.0 MiB

### Expected result

Compilation should complete to 100%

### Actual result

Stops at 11% with no error.

Only error I can find is in var/log/debug.log

main.DEBUG: Source class "\Magento\ServiceProxy\Model" for "Magento\ServiceProxy\Model\Logger" generation does not exist. {"exception":"[object] (RuntimeException(code: 0): Source class \"\\Magento\\ServiceProxy\\Model\" for \"Magento\\ServiceProxy\\Model\\Logger\" generation does not exist.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by will-wright1** [comment]
This issue can probably be closed, it turns out it was because composer wasn't on the latest version. I'm not sure why it only fails at the compile stage but ensuring composer was on version 2.7.0 fixed it

**Comment by marwan-corals** [comment]
I updated composer to the latest version : Composer version 2.7.6 2024-05-04 23:03:15 
and the issue is still there

**Comment by raviverma18th** [comment]
I am getting the same issue in debug.log file, 
Composer version 2.7.2 2024-03-11 17:12:18

[2024-05-16T13:41:45.437723+00:00] report.DEBUG: Source class "\Magento\ServiceProxy\Model" for "Magento\ServiceProxy\Model\Logger" generation does not exist. {"exception":"[object] (RuntimeException(code: 0): Source class \"\\Magento\\ServiceProxy\\Model\" for \"Magento\\ServiceProxy\\Model\\Logger\" generation does not exist. at /vendor/magento/framework/Code/Generator.php:223)"} []

**Comment by LotsofPixels** [comment]
After doing composer update in Magento 2.4.7 with PHP 8.3 I have the same issue
[2024-05-16T17:13:10.241272+00:00] main.DEBUG: Source class "\Magento\ServiceProxy\Model" for "Magento\ServiceProxy\Model\Logger" generation does not exist. {"exception":"[object] (RuntimeException(code: 0): Source class \"\\Magento\\ServiceProxy\\Model\" for \"Magento\\ServiceProxy\\Model\\Logger\" generation does not exist. at /data/web/magento2/vendor/magento/framework/Code/Generator.php:223)"} []

**Comment by FadedOut** [comment]
@raviverma18th  @LotsofPixels 

You're both saying you've done composer update and have this error in the log file? I'm on 2.4.6-p5 and have ran composer update just a little while ago and found the same error in my debug.log file. 

I am having a 500 error on my front page now. Trying to revert to backups. No idea if this error is in relation to the site not working. But it was working before I did this composer update and it updated (also added) a few dependencies. I also can't get past 3/9 on di:compile. It just stops the process with no errors.

Did either of you see these when it updated (hopefully you keep a log of every update?):
Upgrading paragonie/constant_time_encoding (v2.6.3 => v2.7.0)
  - Upgrading composer/xdebug-handler (3.0.4 => 3.0.5)
  - Upgrading laminas/laminas-validator (2.53.0 => 2.54.0)
  - Upgrading psr/http-factory (1.0.2 => 1.1.0)
  - Upgrading colinmollenhour/php-redis-session-abstract (v1.5.5 => v1.6.0)
  - Installing react/event-loop (v1.5.0)
  - Installing evenement/evenement (v3.0.2)
  - Installing react/stream (v1.3.0)
  - Installing react/cache (v1.2.0)
  - Installing react/dns (v1.12.0)
  - Installing react/socket (v1.15.0)
  - Installing react/child-process (v0.6.5)
  - Installing fidry/cpu-core-counter (1.1.0)
  - Installing clue/ndjson-react (v1.3.0)
  - Upgrading friendsofphp/php-cs-fixer (v3.54.0 => v3.57.1)
  - Upgrading phpstan/phpstan (1.10.67 => 1.11.1)
  - Upgrading aws/aws-sdk-php (3.305.9 => 3.306.7)

I think the culprit is in here somewhere...arg!!

**Comment by hostep** [comment]
@FadedOut: in your case it's most likely related to: `Upgrading colinmollenhour/php-redis-session-abstract (v1.5.5 => v1.6.0)`, see https://github.com/magento/magento2/issues/38728

But it's definitely not related to the issue here.

**Comment by LotsofPixels** [comment]
@hostep @FadedOut @raviverma18th
After downgrading colinmollenhour/php-redis-session-abstract, everything is working again.

composer require colinmollenhour/php-redis-session-abstract:1.5.5

**Comment by FadedOut** [comment]
> @FadedOut: in your case it's most likely related to: `Upgrading colinmollenhour/php-redis-session-abstract (v1.5.5 => v1.6.0)`, see #38728 (and see [#38728 (comment)](https://github.com/magento/magento2/issues/38728#issuecomment-2114806169) for a workaround)
> 
> But it's definitely not related to the issue here.

You are a lifesaver! This was exactly my problem. So glad you were able to respond quickly like that, that's much appreciated 👍😀.

**Comment by marcinkaczmarekmkmk** [comment]
hi

magento 2.4.7-p1
composer 2.7.0 and 2.7.6
colinmollenhour/php-redis-session-abstract 1.5.5
issue still present

changing the name of virtualType for Magento\Framework\Logger\Monolog in Magento\ServiceProxy\etc\adminhtml\di.xml to WhateverNameWithoutSlashes helps. can be done with custom composer patch.

**Comment by AndresInSpace** [comment]
Moving
`Magento\ServiceProxy\etc\adminhtml\di.xml`
to
`Magento\ServiceProxy\etc\di.xml`

fixed this for me
It appears that `vendor/magento/module-service-proxy/Controller/Adminhtml/Service/Proxy.php`
is accessed/instantiated via CLI `bin/magento` during operations like `setup:upgrade` `cache:flush` etc

If I follow this correctly,  because we're using cli commands it triggers actions that would of assumed to be coming from an admin route  (but is from CLI)?

**Comment by MeCapron** [comment]
Hello there,

it seems to be bound to the enterprise version only. Within the modules `Magento\PaymentServices\*`

@engcom-Dash where to report this properly?

**Comment by tuyennn** [comment]
+1 why it was closed by a composer update version?
