### ISSUE TITLE
[Issue] Static content deploy - Type error

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#38682]
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create an empty less file in your theme
2. Launch `setup:static-content:deploy --force`

### Expected result

The error "LESS file is empty" is displayed correctly

### Actual result

```
 Magento\Framework\Exception\LocalizedException::__construct(): Argument #1 ($phrase) must be of type Magento\Framework\Phrase, string given, called in /var/www/html/vendor/magento/module-deploy/Service/DeployPackage.php on line 142
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @Nuranto , 

Thanks for reporting and collaboration.

Verified the issue in Magento 2.4 dev instance and 2.4.7 and the issue is not reproducible.

Steps to reproduce:

1.Create an empty less file in your theme
2.Launch setup:static-content:deploy --force


Please refer the attached screenshots, data and let us know if we missed anything.


Created an empty less file in luma theme abc.less

<img width="710" alt="Screenshot 2024-05-02 at 8 03 43 PM" src="https://github.com/magento/magento2/assets/51681379/13aaa1a7-0b53-42c9-987b-22c8218bb35b">


bin/magento setup:static-content:deploy --force , it's ran successfully

<img width="978" alt="Screenshot 2024-05-02 at 8 04 46 PM" src="https://github.com/magento/magento2/assets/51681379/362ac077-c91a-4691-a010-0edbdbc8b199">

**Comment by Nuranto** [comment]
Rename `_abc.less` to `abc.less`, and you should be able to reproduce the issue. (The goal here is just to generate an error during compilation. The issue is about an error that happens when an error is displayed)

**Comment by engcom-Delta** [comment]
Hi @Nuranto,

Verified the issue on 2.4-develop, 2.4.7 and it is reproducible.

Hence, Confirming the issue.

Steps to reproduce:-

1.Create an empty less file in your theme
2.Launch setup:static-content:deploy --force



<img width="1233" alt="Screenshot 2024-05-02 at 9 53 54 PM" src="https://github.com/magento/magento2/assets/51681379/604835e7-269b-4ee7-a6b9-4a285a878e3b">



<img width="1440" alt="Screenshot 2024-05-02 at 10 08 20 PM" src="https://github.com/magento/magento2/assets/51681379/fafc70cc-4e05-46dd-a442-b2636a803c01">


Please refer the attached screenshot.

**Comment by mrtuvn** [comment]
seem you need use file less with underscore for solve problem. Magento not allow you import styles without underscore

**Comment by Kishorchhugani** [comment]
my less file not empty still giving me same error after upgrading to 2.4.7 in deploy command !!!

any Updates ?

**Comment by pyyick** [comment]
I also face this issue too. I filled something in that empty css file as a workaround.

**Comment by amaldethan** [comment]
Error disappears after changing $errorMessage type to Phrase
```
use Magento\Framework\Phrase;

`throw new LocalizedException(new Phrase($errorMessage));`
```
