### ISSUE TITLE
Export Report Generator

### ISSUE THREAD

**Issue by sottilejillian** [magento/magento2#38690]
### Preconditions and environment

- Magento version 2.3.3

### Steps to reproduce

1. Log into Magento as vendor to update website information
2. Click on System
3. Click on Export
4. Entity type: Products
5. Scroll down
6. Click continue

### Expected result

Report in created and I am able to download and open on desktop.

### Actual result

The report never appears

### Additional information

As a wholesaler we use Magento to show our products to our customers not to sell to the general public. In the past we have been able to use the export function to export a csv report with product information. We have been trying to export a report all day and nothing has generated. Has this happened to anyone?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @sottilejillian 

Thanks for reporting and collaboration.

Verified the issue in magento 2.4 dev instance but the issue is not reproducible.

Steps to reproduce
Log into Magento as vendor to update website information
Click on System
Click on Export
Entity type: Products
Scroll down
Click continue

The report is generated successfully.

Please refer the attached screenshots.

<img width="1440" alt="38690" src="https://github.com/magento/magento2/assets/60198592/2fa90835-167d-4fff-8da9-6d6fa6f7b817">
