### ISSUE TITLE
Admin: Page Actions Buttons floating left instead of right

### ISSUE THREAD

**Issue by pawan** [magento/magento2#38701]
### Preconditions and environment

- Magento version: 2.4.7
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

- Login to Admin
- Go to Stores >> Settings >> Configuration **OR** Customers >> All Customers >> Add New Customer
- Now scroll page
- On sticky header, Page Actions Buttons floating left instead of right

### Expected result

- On sticky header, Page Actions Buttons should float to right

<img width="1345" alt="Screenshot 2024-05-07 at 11 58 03 AM" src="https://github.com/magento/magento2/assets/22196227/e2df443d-9748-4b3d-b984-43da8c749246"]

### Actual result

- On sticky header, Page Actions Buttons floating to left

[img width="979" alt="Screenshot 2024-05-07 at 11 56 13 AM" src="https://github.com/magento/magento2/assets/22196227/8a21d9a4-8960-4352-a394-c1b322a7a0d9"]

### Additional information

*No response*

### Release note

*No response*

### Triage and priority

- [ ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [X> Severity: **S4** *- Affects aesthetics, professional look and feel, "quality" or "usability".*

**Comment by pawan** [comment]
@magento I am working on this

**Comment by engcom-Dash** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @pawan 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance and 2.4.7 instance and the issue is reproducable.

On sticky header, Page Actions Buttons floating to left. Hence, we are confirming this issue.

Steps to reproduce

1. Login to Admin
2. Go to Stores >> Settings >> Configuration OR Customers >> All Customers >> Add New Customer
3. Now scroll page
4. On sticky header, Page Actions Buttons floating left instead of right

<img width="1440" alt="Screenshot 2024-05-07 at 4 44 55 PM" src="https://github.com/magento/magento2/assets/60198592/76d635e1-1b85-4882-b72c-72be9a7f12a6">

**Comment by engcom-Bravo** [comment]
Hi @pawan,

Internal team has started to work on it

Thanks.

**Comment by pawan** [comment]
@engcom-Bravo i already created PR https://github.com/magento/magento2/pull/38713.  Can we review and merge it ?

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11919 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11919&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks
