### ISSUE TITLE
Vault/Stored Payment Methods not selected value when changing the uncheck/check my billing address and shipping address are the same 

### ISSUE THREAD

**Issue by vbuiendertech** [magento/magento2#38718]
### Preconditions and environment

- Magento version 2.4.6-p5
- Braintree Payment Method (with Stored Cards)

### Steps to reproduce

1. Add a product to the cart and redirect to the checkout/#payment page. (Step 2 on the checkout page.)
2. Selected any payment method on the Stored Payment method
3. Uncheck the option My billing and shipping address are the same. => Click the update with the new address.

### Expected result

After unchecking/checking the checkbox, my billing and shipping address are the same, and click on the Update button. Selecting "My billing and shipping address are the same" should not de-select the selected stored credit card.

### Actual result

Selecting “My billing and shipping address are the same” under the stored credit card would de-select the selected stored credit card.

![Screenshot 2024-05-14 at 10 40 44](https://github.com/magento/magento2/assets/39359387/5dd1b461-c342-40a3-b07e-e8d47d863cb5)
![Screenshot 2024-05-14 at 10 40 54](https://github.com/magento/magento2/assets/39359387/f3ff712d-09f2-45ea-8d21-d26c3835e830)

This is my video test:

https://drive.google.com/file/d/1nq3MZpX5GKbtVaz_5g1WdyAYF0RcUL2A/view

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4.7 instance

**Comment by engcom-Delta** [comment]
Hi @vbuiendertech ,

Thanks for reporting and collaboration.

Verified the issue in magento 2.4-develop instance and the issue is not reproducible.

Preconditions:-

Braintree Payment Method (with Stored Cards)

Steps to reproduce:-

1.Add a product to the cart and redirect to the checkout/#payment page. (Step 2 on the checkout page.)
2.Selected any payment method on the Stored Payment method
3.Uncheck the option My billing and shipping address are the same. => Click the update with the new address.


After unchecking/checking the checkbox, my billing and shipping address are the same, and click on the Update button. Selecting "My billing and shipping address are the same" doesn't de-select the selected stored credit card.



https://github.com/magento/magento2/assets/51681379/f1cdcc9c-1aad-4006-a1cd-7165222e8348

**Comment by vbuiendertech** [comment]
Hi @engcom-Delta 

Thank you for response.

But you tested on the Magento 2.4.7 and Braintree Payment v4.6.1.

My issue existed on Magento 2.4.6-p5 ( this Magento version uses Braintree Payment v4.5.0-p1)

Can you please test this issue on Magento 2.4.6-p5 and Braintree Payment v4.5.0-p1? and provide patches to resolve this issue before we upgrade to Magento 2.4.7?

Thank you in advance!

VietBui

**Comment by vbuiendertech** [comment]
Hi @engcom-Delta

I will reopen this ticket.

Please confirm with me.

My issue existed on Magento 2.4.6-p5 ( this Magento version uses Braintree Payment v4.5.0-p1)

Thank you so much.

**Comment by engcom-Delta** [comment]
Hi @vbuiendertech ,

Thanks for reporting and collaboration.

Verified the issue in latest magento 2.4.7 instance and the issue is not reproducible.

Preconditions:-

Braintree Payment Method (with Stored Cards)

Steps to reproduce:-

1.Add a product to the cart and redirect to the checkout/#payment page. (Step 2 on the checkout page.)
2.Selected any payment method on the Stored Payment method
3.Uncheck the option My billing and shipping address are the same. => Click the update with the new address.

After unchecking/checking the checkbox, my billing and shipping address are the same, and click on the Update button. Selecting "My billing and shipping address are the same" doesn't de-select the selected stored credit card.


https://github.com/magento/magento2/assets/51681379/79af7807-0075-40e5-9f71-7fd0d0367ba0

**Comment by vbuiendertech** [comment]
Hi @engcom-Delta,

Thanks for reporting and collaboration.

**Comment by vbuiendertech** [comment]
Hi @engcom-Delta,

Thanks for reporting and collaboration.

I know this issue can't be reproduced on Magento 2.4.7

But you can reproduce this issue on Magento 2.4.6-p5.

Currently, my site uses Magento 2.4.6 -p5 and  still hasn't plan upgrade to Magento 2.4.7

Can you provide patches to fix this issue on the Magento 2.4.6-p5?

Thank you in advance!

**Comment by engcom-Delta** [comment]
Hi @vbuiendertech ,

Thanks for reporting and collaboration.

Verified the issue in magento 2.4.6-p5 instance and the issue is reproducible.

Preconditions:-

Braintree Payment Method (with Stored Cards)

Steps to reproduce:-

1.Add a product to the cart and redirect to the checkout/#payment page. (Step 2 on the checkout page.)
2.Selected any payment method on the Stored Payment method
3.Uncheck the option My billing and shipping address are the same. => Click the update with the new address.

Selecting “My billing and shipping address are the same” under the stored credit card would de-select the selected stored credit card.


https://github.com/magento/magento2/assets/51681379/006c832a-472e-408e-a13f-3df2bdd9bf7b


We will get back to you soon for the patch required by you, meanwhile we are putting this issue on hold.

**Comment by engcom-Delta** [comment]
Hi @vbuiendertech ,

Thanks for reporting and collaboration.
Verified the issue in magento 2.4.6-p5 instance and the issue is reproducible.

Preconditions:-
Braintree Payment Method (with Stored Cards)

Steps to reproduce:-
1.Add a product to the cart and redirect to the checkout/#payment page. (Step 2 on the checkout page.)
2.Selected any payment method on the Stored Payment method
3.Uncheck the option My billing and shipping address are the same. => Click the update with the new address.
Selecting “My billing and shipping address are the same” under the stored credit card would de-select the selected stored credit card.

https://github.com/user-attachments/assets/e2f9ba6f-087c-4aff-b5a6-87b885b1503b

Thanks.

**Comment by randix0** [comment]
FYI
The issue was fixed in the commit https://github.com/magento/magento2/commit/cfac1ff2d3ab10f083ff976c7b9f1bafb9d0cd83
