### ISSUE TITLE
Credis update to 1.6 breaks Magento 2.4.7

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#38728]
### Preconditions and environment

- Magento 2.4.7
- colinmollenhour/php-redis-session-abstract 1.6

### Steps to reproduce

2 hours ago the framework package colinmollenhour/php-redis-session-abstract is updated to v1.6 and by this change it breaks Magento, so just run composer update and get the latest version.

### Expected result

No errors

### Actual result

`[15-May-2024 21:18:24 UTC] PHP Fatal error:  Class Magento\Framework\Session\SaveHandler\Redis\Config contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Cm\RedisSession\Handler\ConfigInterface::getRetries) in /home/xxx/public_html/vendor/magento/framework/Session/SaveHandler/Redis/Config.php on line 16`

### Additional information

https://github.com/colinmollenhour/php-redis-session-abstract/releases

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by viniciusgborges** [comment]
To solve this run composer require colinmollenhour/php-redis-session-abstract:1.5.5

**Comment by contardi** [comment]
There's also an issue opened to revert the breaking changes on php-redis-session package.

https://github.com/colinmollenhour/php-redis-session-abstract/issues/58

**Comment by laasso** [comment]
> A possible workaround is to fix the version to 1.5.5 `composer require colinmollenhour/php-redis-session-abstract:1.5.5`

Fixed with this

`composer require colinmollenhour/php-redis-session-abstract:1.5.5

./composer.json has been updated
Running composer update colinmollenhour/php-redis-session-abstract
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Downgrading colinmollenhour/php-redis-session-abstract (v1.6.0 => v1.5.5)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading colinmollenhour/php-redis-session-abstract (v1.5.5)
  - Downgrading colinmollenhour/php-redis-session-abstract (v1.6.0 => v1.5.5): Extracting archive
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
143 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.`

**Comment by hostep** [comment]
Might be better to define a conflict with this specific version, so you don't pin the version in your `composer.json` file and forget about removing it again in the future.
Something like this is probably better:
```diff
diff --git a/composer.json b/composer.json
index 8621702..6d43808 100644
--- a/composer.json
+++ b/composer.json
@@ -152,6 +152,7 @@
         "magento/module-wishlist-analytics": "*"
     },
     "conflict": {
+        "colinmollenhour/php-redis-session-abstract": "1.6.0",
         "gene/bluefoot": "*"
     },
     "autoload-dev": {
```

**Comment by andrea-glam** [comment]
same issue here, could be a possibile fix apply a patch or a complete rewrite to: 
`vendor/magento/framework/Session/SaveHandler/Redis/Config.php`
and implement an empty method getRetries()?

Thank you, 
Andrea.

**Comment by TuVanDev** [comment]
@andrea-glam I have submitted a pull request to address this issue and provided composer patches for a more immediate solution. You can check it out at https://github.com/magento/magento2/pull/38729

You can also utilize the `conflict` configuration, as @hostep suggested, to prevent the installation of version 1.6.0 in your project.

**Comment by PaulWatt** [comment]
same issue here on 2.4.6p5.
Could we have a patch please?

**Comment by colinmollenhour** [comment]
I released the latest master as v2.0.0 and the previous v1.5.5 as v1.7 so I believe that should effectively "roll back" the v1.6.0 release. My apologies for this debacle, I should have read more carefully how the "^" operator works for Composer.

**Comment by hostep** [comment]
@chernenm, @jorgb90: I believe we can close htis issue now that version 1.7.0 was released which fixes this, right?

**Comment by jorgb90** [comment]
@hostep Yes correct. Confirmed.
