### ISSUE TITLE
A lot of Store Switcher errors in exeption.log

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#38782]
### Preconditions and environment

- Magento version 2.6.5-p5
- PHP 8.1.24
Since I upgradede to 2.4.6-p5 I get a lot of errors in exception.log. It also looks like the performance of the webshop is affected. I regularly get a Gateway Timeout. Checkout does not always proceed to step 2.

The error is:
main.ERROR: InvalidArgumentException: Couldn't retrieve data from cache. in /vendor/magento/module-store/Model/StoreSwitcher/RedirectDataCacheSerializer.php:85

### Steps to reproduce

1. Navigate around the website 
2. Check exception.log

### Expected result

No error in exception.log

### Actual result

The following error is repeated a lot in exception.log:
main.ERROR: InvalidArgumentException: Couldn't retrieve data from cache. in /vendor/magento/module-store/Model/StoreSwitcher/RedirectDataCacheSerializer.php:85

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment]
Hi @mtjweb 

Thanks for reporting and collaboration.

Please let us know which Magento version you upgraded to 2.4.6-p5.

Thanks.

**Comment by mtjweb** [comment]
> Hi @mtjweb
> 
> Thanks for reporting and collaboration.
> 
> Please let us know which Magento version you upgraded to 2.4.6-p5.
> 
> Thanks.

I upgraded from version 2.4.5-p1.

**Comment by engcom-Dash** [comment]
Hi @mtjweb 

I verified the issue on Magento 2.4.7 after upgrading the instance from 2.4.5-p1 but the issue is not reproducible.

We can create a product and place an order successfully without errors.

Please refer to the attached screen-recording.
Let us know if we missed anything.


https://github.com/magento/magento2/assets/60198592/9313f103-aef8-4d4a-b956-c7fa7575af88

**Comment by mtjweb** [comment]
My webshop is a multistore. The error refers to the store switcher module.

The problems are also worse when an EU VAT-number is entered in the checkout.

**Comment by engcom-Dash** [comment]
Hi @mtjweb 

Can you please provide the detailed steps to reproduce the issue with screenshots

Thanks.

**Comment by mtjweb** [comment]
Sorry, but I'm not here to give a beginners tutorial.

**Comment by engcom-Dash** [comment]
Hi @mtjweb 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance but the issue is not reproducible.

We are not seeing store switched errors in execption.log

Please refer to the attached screen recording and let us know if we missed anything.


https://github.com/magento/magento2/assets/60198592/997f6c6f-8d92-4fda-9ad9-31b2f2dc90ec

**Comment by mtjweb** [comment]
I have the  storecode-in-url feature also enabled, using Redis but no Varnish.

**Comment by musicworld** [comment]
same issue here with varnish and redis magento 2.4.7-p2 and php 8.2

**Comment by musicworld** [comment]
@engcom-Dash please reopen issue still here.

**Comment by Migno** [comment]
Can confirm, we are also getting this issue in Magento 2.4.7

**Comment by musicworld** [comment]
Issue ist still there with magento 2.4.8
