### ISSUE TITLE
Issue at product import when provided with custom options-type: file (Created Product does not contain price for custom-option and show only the first file type extension provided)

### ISSUE THREAD

**Issue by ATIFYAQOOB869** [magento/magento2#38805]
### Preconditions and environment

- Magento version: 2.4.7
- PHP-8.3

Attached the CSV used during the testing.
[export_catalog_product_20240606_161012.csv](https://github.com/user-attachments/files/15613984/export_catalog_product_20240606_161012.csv)

### Steps to reproduce

1. Create a CSV file for product import.
2. Add the necessary data for the product along with custom_options.
3. Add the type: file and other data for the custom_options column. Make sure to add more than one file_extension attribute.
4. Navigate to System>Import.
5. Choose Entity type: Products and Import behaviors: Add/Update. Leave the remaining settings as default. (separators: ",")
6. Validate and Import the Product.
7. Check the created product customization options section on the edit product page. The price is missing and file extension show only the first extension provided in the CSV.

### Expected result

![Screenshot from 2024-06-06 16-01-46](https://github.com/magento/magento2/assets/171928821/14caa7f9-1f08-4a31-b20f-34b431f00056)

### Actual result

![Screenshot from 2024-06-06 16-33-41](https://github.com/magento/magento2/assets/171928821/7ebdf0a5-bbd9-4142-93cc-cd521aaf2630)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @ATIFYAQOOB869,

Thanks for your reporting and collaboration,

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create a CSV file for product import.
- Add the necessary data for the product along with custom_options.
- Add the type: file and other data for the custom_options column. Make sure to add more than one file_extension attribute.
- Navigate to System>Import.
- Choose Entity type: Products and Import behaviors: Add/Update. Leave the remaining settings as default. (separators: ",")
- Validate and Import the Product.
- Check the created product customization options section on the edit product page. The price is missing and file extension show only the first extension provided in the CSV.



<img width="1308" alt="Screenshot 2024-06-18 at 10 07 53" src="https://github.com/magento/magento2/assets/51680745/f33a1936-fd5d-4bbf-a5d2-15e89b9c6a59">



The price is missing and file extension show only the first extension provided in the CSV.


Hence Confirming the issue.


Thanks.

**Comment by Yaroslav1301** [comment]
@magento I am working on this
