### ISSUE TITLE
Checkout CSP mode changed from report_only to strict in security release 2.4.5-p8

### ISSUE THREAD

**Issue by dphilipps** [magento/magento2#38823]
### Preconditions and environment

Security release 2.4.5-p8

### Steps to reproduce

1. Open file vendor/magento/module-checkout/etc/config.xml
2. See new section at the end as follows including the following line which disables report_only and enables strict mode:_<report_only>0</report_only>_:

        <csp>
            <mode>
                <storefront_checkout_index_index>
                    **<report_only>0</report_only>**
                </storefront_checkout_index_index>
            </mode>
            <policies>
                <storefront_checkout_index_index>
                    <scripts>
                        **<inline>0</inline>**
                        <event_handlers>1</event_handlers>
                    </scripts>
                </storefront_checkout_index_index>
            </policies>
        </csp>

Additionally, 

1. Browse to checkout on storefront with developer tools open.
2. Check for CSP error entries not prefixed with [Report Only]
3. Potentially broken checkout (rendering or functionality)

### Expected result

CSP mode should remain in 'Report Only' after upgrade.  It should not be enabled in a patch release as it is a significant unexpected configuration and behaviour change that is likely to break many checkout implementations.  **There is no warning of this change in the release notes that I have seen**.  AFAIK according to documenation this change was only meant to be brought about from 2.4.7 onwards.

### Actual result

1. CSP Strict mode is enabled in module-checkout.
2. Inline scripts are blocked.

### Additional information

There is also a NEW module dependency in module-checkout for module-csp (requiring it be enabled).  I previously had module-cps disabled in 2.4.5-p7 however the storefront breaks after upgrade without the module being enabled.  This is also an unexpected and significant change.

Workaround to enable 'Report Only' for checkout:
insert into core_config_data (scope, scope_id, path, value) values ('default', 0, 'csp/mode/storefront_checkout_index_index/report_only', 1) on duplicate key update value = VALUES(value);

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
I'm planning of investigating these changes and will hopefully release a new version of https://github.com/baldwin-agency/magento2-module-csp-shim/ that supports these newly released patch versions later today (🤞), so you can remove the CSP module if you don't want to deal with it in these security patch releases

**Comment by dphilipps** [comment]
This change should be documented in the release notes for 2.4.5-p8 and is not.  The patch releases are intended to reduce barriers to upgrading to a more secure codebase, however this change potentially requires significant testing, development and time to deploy - it breaks our entire store.  Previous patch releases have been low friction and seemless to deploy in our case into a production environment. 

https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/2-4-5-patches

According to [the ](https://experienceleague.adobe.com/en/docs/commerce-operations/release/planning/versioning-policy#patch-release)
The following guidelines apply to patch releases:

1. The latest-supported minor release receives full functional quality fixes and enhancements.
**2. Changes that could break extensions or code compatibility are avoided.** For example, code written for version 2.2.0 should still work on version 2.2.7.
3. On an exceptional basis, breaking changes or additional patches or hotfixes may be released to address security or compliance issues and high-impact quality issues. On the module level, these are mostly PATCH-level changes; sometimes MINOR-level changes.

So looks like this change falls under point 3.  I suggest documenting this change in known issues and release notes please.

**Comment by willbrammer** [comment]
This should **100%** be in the release notes and is going to trip up a lot of merchants.

https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/2-4-7-patches
https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/2-4-6-patches
https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/2-4-5-patches
https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/2-4-4-patches

**Comment by hostep** [comment]
The release notes for 2.4.7-p1 shouldn't be updated, nothing changed in the CSP module in that release, it's just the same code that was already included in 2.4.7

**Comment by nathanjosiah** [comment]
We will not accept this change as it is not a change coming from within Adobe. This is driven by PCI compliance and is required to be on. Be aware that your auditors will be closely looking for this as it goes into effect March of 2025. 

Having said that, any merchant can easily customize their instance to non-compliant and take your own risks with your auditor. But as for the official settings and feature, it does have to be enabled by default for payment pages.

**Comment by adamrevsonline** [comment]
> ### Preconditions and environment
> Security release 2.4.5-p8
> 
> ### Steps to reproduce
> 1. Open file vendor/magento/module-checkout/etc/config.xml
> 2. See new section at the end as follows including the following line which disables report_only and enables strict mode:_<report_only>0</report_only>_:
>    ```
>     <csp>
>         <mode>
>             <storefront_checkout_index_index>
>                 **<report_only>0</report_only>**
>             </storefront_checkout_index_index>
>         </mode>
>         <policies>
>             <storefront_checkout_index_index>
>                 <scripts>
>                     **<inline>0</inline>**
>                     <event_handlers>1</event_handlers>
>                 </scripts>
>             </storefront_checkout_index_index>
>         </policies>
>     </csp>
>    ```
> 
> Additionally,
> 
> 1. Browse to checkout on storefront with developer tools open.
> 2. Check for CSP error entries not prefixed with [Report Only]
> 3. Potentially broken checkout (rendering or functionality)
> 
> ### Expected result
> CSP mode should remain in 'Report Only' after upgrade. It should not be enabled in a patch release as it is a significant unexpected configuration and behaviour change that is likely to break many checkout implementations. **There is no warning of this change in the release notes that I have seen**. AFAIK according to documenation this change was only meant to be brought about from 2.4.7 onwards.
> 
> ### Actual result
> 1. CSP Strict mode is enabled in module-checkout.
> 2. Inline scripts are blocked.
> 
> ### Additional information
> There is also a NEW module dependency in module-checkout for module-csp (requiring it be enabled). I previously had module-cps disabled in 2.4.5-p7 however the storefront breaks after upgrade without the module being enabled. This is also an unexpected and significant change.
> 
> Workaround to enable 'Report Only' for checkout: insert into core_config_data (scope, scope_id, path, value) values ('default', 0, 'csp/mode/storefront_checkout_index_index/report_only', 1) on duplicate key update value = VALUES(value);
> 
> ### Release note
> _No response_
> 
> ### Triage and priority
> * [ ]  Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
> * [x]  Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
> * [ ]  Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
> * [ ]  Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
> * [ ]  Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

We have ran the query detailed in this workaround but we are still experiencing issues when attempting to place orders in the admin. Is there a similar query that can be ran to resolve that?

**Comment by dphilipps** [comment]
@adamrevsonline 
Here is a suggestion, please test it first though. There may be other paths which need adding for admin as well as **csp/mode/admin_sales_order_create_index/report_only**

insert into core_config_data (scope, scope_id, path, value) values ('default', 0, 'csp/mode/admin_sales_order_create_index/report_only', 1) on duplicate key update value = VALUES(value);

**Comment by sdouma** [comment]
> Thank you for the report and we understand this change has been hard and will have a negative impact to merchants. Unfortunately we can not change the default to be disabled because the CSP requirements are not coming from within Adobe. This is driven by PCI compliance and is required to be on. Be aware that your auditors will be closely looking for this as it goes into effect March of 2025.
> 
> Having said that, any merchant can easily customize their instance to non-compliant and take your own risks with your auditor. But as for the official settings and feature, it does have to be enabled by default for payment pages.
> 
> As for the docs missing this change, it was supposed to be in there. I am working on getting this in and there is already a PR in progress to get all of them updated.

It seems like bad practice to add security enhancements for 2025 on a vulnerability patch. The need to not have a critical  vulnerability on my site is urgent, yet I have to waste time on csp for something that is almost a year out. It completely changes the nature of the patch and that reflects on the merchant end when we need to have additional discussions before deploying. Even modules from Adobe approved third party partners weren't updated.
It is a separate issue and needs to be resolved in a separate patch.

**Comment by nathanjosiah** [comment]
@sdouma while I understand what you're saying, you are mislabeling what these patches are. These are fully supported release lines that just happen to focus on security vulnerabilities. However, they are fully supported which means they also have to stay compliant. You should not be able to run ANY officially supported version of our product and not be compliant. We also add hotfixes and security enhancements to these releases in additional to vulnerability fixes.

* https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/overview#about-adobe-commerce-security-patch-releases
* https://experienceleague.adobe.com/en/docs/commerce-operations/release/planning/versioning-policy
* https://experienceleague.adobe.com/en/docs/commerce-operations/security-and-compliance/shared-responsibility

By contrast, we have had many merchants asking for this to be implemented in preparation for the new rules. For the security-focused release lines we must either be compliant or drop support for them completely. It's not an option for them to be supported but not compliant.

**Comment by nathanjosiah** [comment]
@sdouma One thing for you and anybody else watching this thread, you are able to disable the CSP and apply the security patch as normal. When you are ready to prepare for the PCI 4 audit and the associated new required CSP changes, you can enable it again. 

Simply add this to a `config.xml` file:
``` <csp>
     <mode>
         <storefront_checkout_index_index>
             <report_only>1</report_only>
         </storefront_checkout_index_index>
     </mode>
     <policies>
         <storefront_checkout_index_index>
             <scripts>
                 <inline>1</inline>
                 <event_handlers>1</event_handlers>
             </scripts>
         </storefront_checkout_index_index>
     </policies>
 </csp>
```

But again, be warned, this is going to be a high visibility item for your auditor because it's new so you are taking your own risk by doing this.

**Comment by sdouma** [comment]
> @sdouma while I understand what you're saying, you are mislabeling what these patches are. These are fully supported release lines that just happen to focus on security vulnerabilities. However, they are fully supported which means they also have to stay compliant. You should not be able to run ANY officially supported version of our product and not be compliant. We also add hotfixes and security enhancements to these releases in additional to vulnerability fixes.
> 
> * https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/security-patches/overview#about-adobe-commerce-security-patch-releases
> * https://experienceleague.adobe.com/en/docs/commerce-operations/release/planning/versioning-policy
> * https://experienceleague.adobe.com/en/docs/commerce-operations/security-and-compliance/shared-responsibility
> 
> By contrast, we have had many merchants asking for this to be implemented in preparation for the new rules. For the security-focused release lines we must either be compliant or drop support for them completely. It's not an option for them to be supported but not compliant.

I think you are reading a lot more into what I said then what I said. I am not sure why you suggesting that I am posing the people shouldn't be in compliance when you are in compliance until April 2025 or that security patches do not contain security enhancements, so I don't think I am mislabeling them. I am simply putting consideration on not separating enhancement and critical vulnerabilities. The "security patch" definition even includes "hotfixes required to address critical issues that affect the Adobe Commerce application."
Having something like that will impede any merchant from quickly resolving the CV. Separating out the fixes for the CVs seems like best practice.

**Comment by nathanjosiah** [comment]
You're not the only one on this thread or the many places that are linking to it so I am adding some general guidances for those people. You are also welcome to follow it if needed. 

As for the suggestion, It's a great idea but it comes down to time and money. We only have so many people and resources that we can use for this work. With what we have allocated today, many alternate strategies are not feasible. 

It's hard to quickly explain how much work goes into the quality and regression process for our releases outside of the development itself. Especially with how many use cases and combinations of packages and versions we support. I have proposed and discussed many alternative workflows and release strategies but as I said, they are not possible with what we have available to Commerce today. So for now we all have to make the best of what we have.

We really appreciate the feedback from everyone and we do incorporate as much of the feedback as we are able to. Before my time here I was a long time consumer of Magento 1 and 2 and I understand the impact these changes bring to the community.

**Comment by hostep** [comment]
Just my 2 cents, but maybe we can learn from this for the future.

In my opinion, this should have been announced beforehand. Say that at the beginning of 2024, Adobe would have announced that in June of 2024 the more stricter CSP feature would land in versions xxx, yyy, zzz, with an article explaining the deal and some tips and tricks of how to prepare for it.
That in my opinion would have avoided a lot of frustration that is happening right now.

Anyway, maybe something to think about for the future when you guys consider introducing another big change in a minor patch release...

**Comment by sdouma** [comment]
@nathanjosiah you "@" me and then said I was mislabeling. I am not sure why I would then assume you were responding to the entire thread instead of me. There is a lot of miscommunication going on.  Just please communicate with your gold and silver partners. As far as I know, no one was prepared.

**Comment by nathanjosiah** [comment]
@sdouma let me clear it up
> mislabeling
Yes, this was directed at you. You said 

> It seems like bad practice to add security enhancements for 2025 on a vulnerability patch. <snip> yet I have to waste time on csp for something that is almost a year out. It completely changes the nature of the patch 

This is not the correct way to label these patches. As I saiefored, these patches are not strictly "vulnerability patches" and having compliance changes does not "completely change the nature of the patch" just because it's not expected in every patch. Every patch has vulnerability fixes and it really shouldn't be up to merchants to decide what is important enough to upgrade. CVSS scores are not a great way to qualify or quantify vulnerabilities and merchants often go unprotected from important things and get hacked because of bad interpretation of our bulletins. I say that because it means upgrading is a given and it takes however long it takes. 

The goal of these patches is to offer the bare minimum path to stay secure and compliant and sometimes that means bigger changes than everyone has become accustomed to (thanks to me and my teams by the way. I fight for all of you). 

As for it being a year out, it's not a year out for us. 2.4.7 GA (released in April) is the last major version before March of 2025 and also the last version before our next audit. We will be going through the audit in July/August and it will include the CSP scope.

We are discussing the possibility of posting something other than all of the resources I already shared above (and the KB articles that went live months ago) specifically talking about the security release lines. The mitigating factor is that it's extremely easy to disable if needed for any length of time and merchants have no problem doing this for anything else they don't like (like 2fa) so we're a little confused about why there is such negative pushback about it. CSP has been a best practice for many years now, required and implemented by many of our merchants already, and we began rolling it out back in 2020 so it's not a huge leap even in precedent.

Out of curiosity, where would you have expected to see such a technical announcement such as the one being described?We are always aiming to increase our awareness as much as we can so if we can publish things where people will actually see it then we can improve.

**Comment by hostep** [comment]
> Out of curiosity, where would you have expected to see such a technical announcement such as the one being described?

On your devblog for instance: https://community.magento.com/t5/Magento-DevBlog/bg-p/devblog? It has some great resources of good articles from years ago, but the rate at which good articles are posted there now, has declined since Adobe has taken over control of Magento unfortunately :(
But announce things on as many places as you want, the more the better, to be able to reach the most amount of people...

Also, the fact that the release notes didn't mention anything about the CSP changes from day 1 has something to do with this discussion here. Devs tend to check out these release notes the moment they get published, but if they don't contain all the necessary info yet, then yes, people get surprised when a release contains more than what was said it would contain. So for the future, try to make sure the release notes are always 100% ready the moment you publish them please.

**Comment by nathanjosiah** [comment]
> announce things on as many places as you want, the more the better,

The problem is (and why I'm asking) nearly all communication channels are very non-technical so it's hard to get approval to publish but it's also hard to get the content crafted for the main audiences of those channels. Like sales and business people don't care about CSP or jquery upgrades or anything else that developers care about. They care about features and business cases and time/revenue saving techniques, etc. 

> the release notes didn't mention anything about the CSP changes from day 1

Yes, this was a mistake on our end. The changes were originally going out alongside the 2.4.7 GA (which also has the changes) and the notes were all in sync. We had to defer the security patch changes to the June release and the notes didn't get propagated along with them. It's not an excuse but it should give you some sort of solace that they were supposed to be there.

**Comment by hryvinskyi** [comment]
Each Magento instance is unique, this is for information only
