### ISSUE TITLE
[Bug] Magento 2.4.7 doesn't allow product photo's with capital letter file extension.

### ISSUE THREAD

**Issue by pieterhollander** [magento/magento2#38831]
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create a new product
2. Try to upload a picture with e.g. filename `DSCN0018.JPG`. The upload will fail.
3. Change the filename to `DSCN0018.jpg`. The upload succeeds.

<img width="778" alt="Screenshot 2024-06-14 at 18 47 20" src="https://github.com/magento/magento2/assets/1392118/f63e59a0-0475-47be-af2d-2daacb8aa1f6">

### Expected result

Image uploads with capital letter file extensions don't cause an error.

### Actual result

After upgrading to 2.4.7, Image uploads with capital letter file extensions are refused.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by phol** [comment]
@magento give me 2.4-develop instance

**Comment by phol** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment]
Hi @phol 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance and the issue is reproducable.

Getting "Disallowed file type: when we try to upload product photo with capital letter file extension.

Steps to reproduce

1. Create a new product
2. Try to upload a picture with e.g. filename DSCN0018.JPG. The upload will fail.
3. Change the filename to DSCN0018.jpg. The upload succeeds.

Please take a look at the screenshots I've attached.

<img width="1440" alt="Screenshot 2024-06-17 at 1 24 56 PM" src="https://github.com/magento/magento2/assets/60198592/9d9e0aa3-35ea-4727-a6a3-cc41a9bbfbf9">
<img width="1440" alt="Screenshot 2024-06-17 at 1 23 31 PM" src="https://github.com/magento/magento2/assets/60198592/7115f005-7cb8-484e-9328-eeb141409d22">

**Comment by monteshot** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it.

Thanks.

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12167 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12167&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks
