### ISSUE TITLE
CSP report_only field is missing in backend configuration

### ISSUE THREAD

**Issue by ajung-dev** [magento/magento2#38850]
### Preconditions and environment

- 2.4.6-p6
- Set: Production Mode

### Steps to reproduce

1.) Login backend
2.) Menu > Stores >  Configuration > Security > Content Security Policy (CSP) > Mode
3.) No setting for report_only found
4.) Go in project files: vendor/magento/module-csp/Model/Mode/ConfigManager.php line 83 report_only function exists but go in fallback line 93
5.) Checking vendor/magento/module-csp/etc/adminhtml/system.xml no report_only <field/> found.

### Expected result

Menu > Stores >  Configuration > Security > Content Security Policy (CSP) > Mode > Report Only (checkbox).

### Actual result

Backend: Menu > Stores >  Configuration > Security > Content Security Policy (CSP) > Mode > Report Only (checkbox) missing.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment]
I think it's intentionally not added to the backoffice configuration settings in case your backoffice gets compromised that bad actors can disable it. Maybe @nathanjosiah can confirm?

The following instructions can maybe help you further: https://sansec.io/guides/magento-csp#disable-strict-csp-on-checkout?

**Comment by ajung2** [comment]
I am not an expert in security. If that's the case, then documentation or a hint would be very helpful for me. It looks like a bug.

@hostep I tested your link with the env.php settings for CSP. Yes, it sets the important areas to "report-only", but there is no official documentation at that point.

Due to the settings in the env.php, I can no longer capture the Report URI; it constantly returns null.

**Comment by hostep** [comment]
Official documentation is here: https://developer.adobe.com/commerce/php/development/security/content-security-policies

You may be looking for these things more specifically:
- https://developer.adobe.com/commerce/php/development/security/content-security-policies/#configure-a-modules-csp-mode
- https://developer.adobe.com/commerce/php/development/security/content-security-policies/#page-specific-content-security-policies

Or if you want to disable CSP all together, there are a bunch of 3rd party modules that came to exist in the last couple of days/weeks:
- https://github.com/yireo/Yireo_DisableCsp
- https://github.com/weiweiouyang/magento2-module-disable-csp
- https://github.com/outeredge/magento-disable-csp
- https://github.com/baldwin-agency/magento2-module-csp-shim
- ...
But try to use those only as a temporary solution, eventually it's best to enable CSP and setup correct whitelists.

**Comment by engcom-November** [comment]
Hello @ajung2,

Thank you for the report and collaboration!

Moving this to on hold for PO confirmation.

**Comment by engcom-November** [comment]
@ajung2,

As per the PO, this is the intended behaviour, in order to change the CSP mode you can do it in config.xml by following the guide here: https://developer.adobe.com/commerce/php/development/security/content-security-policies/#configure-a-modules-csp-mode

Hence closing this issue, if you need more assistance on this feel free to raise a new ticket or reopen this.

Thank you.
