### ISSUE TITLE
CSP Issue with DOB field

### ISSUE THREAD

**Issue by mahesh-singh-pinja** [magento/magento2#38894]
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

1. Enable strict CSP mode.
2. Enable show DOB field from admin on customer registration.

 This will add dob field with this script 
 https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Element/Html/Date.php#L31
 
 It should add nonce on this script 

### Expected result

No CSP warning in console.

### Actual result

CSP warning in console.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mahesh-singh-pinja** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @mahesh-singh-pinja,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the latest development branch of Magento ie 2.4-develop but it seems the issue is not reproducible for us. To enable the strict CSP mode. We have created a custom module with the following `config.xml`:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/config.xsd">
    <default>
        <csp>
            <mode>
                <storefront>
                    <report_only>0</report_only>
                </storefront>
                <admin>
                    <report_only>0</report_only>
                </admin>
            </mode>
        </csp>
    </default>
</config>
```

And then enable the module. However, we are not seeing any CSP warning in the console. Please have a look at the below screenshot for reference:
![image](https://github.com/magento/magento2/assets/51681618/f377874d-0ae7-4f46-8847-eacf8aae66c2)

But let us know if we have missed anything here.

Thanks

**Comment by engcom-Hotel** [comment]
Dear @mahesh-singh-pinja ,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards
