### ISSUE TITLE
GraphQL addProductsToCart mutation return duplicate errors

### ISSUE THREAD

**Issue by trungpq2711** [magento/magento2#38979]
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

- Add a simple product with qty is 1 to cart (use graphql)
- Go to BE change min qty to 4
- Add simple product to cart with qty is 1(use graphql)

### Expected result

Return only one error message 

### Actual result

Return duplicate error message
![Screenshot 2024-07-29 at 10 48 23](https://github.com/user-attachments/assets/686ca4d2-79bb-4e3b-994f-915689967792)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment]
Hi @trungpq2711,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Add a simple product with qty is 1 to cart (use graphql)
- Go to BE change min qty to 4
- Add simple product to cart with qty is 1(use graphql)


<img width="1434" alt="Screenshot 2024-07-29 at 12 37 56" src="https://github.com/user-attachments/assets/59bf0646-6eb1-4a66-a90c-1543e491d7a1">



It is returning only single error message.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by trungpq2711** [comment]
Hi @engcom-Bravo 
I have checked Latest 2.4-develop and it work well.
I see we are removed function to get error message from cart.
The issue only present in Magento 2.4.6-p3
