### ISSUE TITLE
Images Not Displaying for Configurable Products on Fresh Magento 2.4.4-p6-9 Installs

### ISSUE THREAD

**Issue by JonathanHelvey** [magento/magento2#39108]
### Preconditions and environment

1. **Magento Version**: Magento 2.4.4-p6-9
2. **Sample Data**: Installed using `php bin/magento sampledata:deploy`
3. **Installation Type**: Fresh installation
4. **Operating System**: macOS
5. **Web Server**: Apache (installed via MAMP)
6. **PHP Version**: PHP 8.1
7. **Database**: MySQL
8. **Environment**: Development environment using MAMP
9. **Browser**: Tested on Google Chrome
10. **Additional Modules Installed**: No additional modules apart from sample data.

### Steps to reproduce

1. Set up a fresh instance of Magento 2.4.4-p8 using MAMP on a local environment.
2. Install sample data using the command: `php bin/magento sampledata:deploy`.
3. Run `php bin/magento set up:upgrade` and `php bin/magento setup:static-content:deploy`.
4. Verify that product images are stored in the wrong path `pub/media/catalog/catalog/product`.
5. Move the images to the correct folder path from `pub/media/catalog/catalog/product` to `pub/media/catalog/product`.
6. `php bin/magento catalog:images:resize` `php bin/magento indexer:reindex` `cache:clean` Check the Magento Admin and Frontend for product images.
7. Notice that images for simple products appear correctly, but images for configurable products do not.

### Expected result

- images should be stored in the correct folder path `pub/media/catalog/product`.
- All product images, including those for configurable products, should display correctly in both the admin and frontend after deploying sample data.

### Actual result

-  After `php bin/magento sampledata:deploy` images populate to the wrong folder path, to `pub/media/catalog/catalog/product`.
- Images for simple products display correctly after resizing.
- Images for configurable products do not display in either the admin or frontend after deploying sample data and resizing.

### Additional information

- This issue was observed immediately following a fresh installation of Magento 2.4.4-p8 and installing sample data. It appears that the sample data deployment process might be creating incorrect paths or failing to map images correctly to configurable products.
- A workaround involves manually associating the missing images via CSV import or manually adding images from the pub media, which is impractical for a large catalog.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @JonathanHelvey,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4.8-beta1 instance and the issue is not reproducible.Kindly refer the screenshots.


https://github.com/user-attachments/assets/2ebd83f2-0ac8-4a75-b8e2-01c5c5171ad4



images should be stored in the correct folder path pub/media/catalog/product.All product images, including those for configurable products, should display correctly in both the admin and frontend after deploying sample data.

Kindly recheck the issue in Latest Magento instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @JonathanHelvey,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Comment by gitrequests** [comment]
**Same issue on 2.4.7-p3** (fresh installation by `composer create-project...`, and then `bin/magento sampledata:deploy`).

It seems that all the sample data folders are copied to the wrong directories:
- For `products`, they are copied to `/pub/media/catalog/catalog/product/*` instead of `/pub/media/catalog/product/*`
- For `wysivyg`, they are copied to `/pub/media/wysiwyg/wysiwyg/*` instead of `/pub/media/wysiwyg/*`
- For `downloadable`, they are copied to `/pub/media/downloadable/downloadable/*` instead of `/pub/media/downloadable/*`

If they are moved manually to their proper destinations, everything starts working

**Comment by rbouma** [comment]
@gitrequests I can confirm I had this today as well. It copied to `catalog/catalog/product` instead of `catalog/product`.
