### ISSUE TITLE
Customer address is not saved after setBillingAddressOnCart GraphQL mutation

### ISSUE THREAD

**Issue by kdivan** [magento/magento2#39130]
### Preconditions and environment

Magento 2.4.7

### Steps to reproduce

Do all steps via GQL:

1. Authorize ( generateCustomerToken mutation)
2. Create cart (customerCart query)
3. Add product to cart (addSimpleProductsToCart mutation)
4. Set billing address (setBillingAddressOnCart mutation).
5. Important: save_in_address_book: true

### Expected result

Address from step 4 should appear in customer_address_entity table

### Actual result

Address is not created

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @kdivan,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

Do all steps via GQL:

- Authorize ( generateCustomerToken mutation)
- Create cart (customerCart query)
- Add product to cart (addSimpleProductsToCart mutation)
- Set billing address (setBillingAddressOnCart mutation).
- Important: save_in_address_book: true

<img width="1437" alt="Screenshot 2024-09-02 at 11 25 57" src="https://github.com/user-attachments/assets/d9485007-5d0a-4742-9427-9662a8080f99">



Address was created in customer_address_entity table.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by kdivan** [comment]
Hi @engcom-Bravo ,

Sorry, I was a bit quick by creating this issue. It is OK. We can close this one.

Thanks for your help
