### ISSUE TITLE
Braintree plugin breaks when JS minify is turned on

### ISSUE THREAD

**Issue by middlegrey** [magento/magento2#3916]
In the Braintree module's requirejs-config.js, the external resource https://js.braintreegateway.com/v2/braintree.js is specified.

When JS minify is turned on, the system tries to load https://js.braintreegateway.com/v2/braintree.min.js which doesn't exist, breaking the page.

**Comment by YevSent** [comment]
The Braintree module on the current develop branch require only minified version of sdk https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/view/frontend/requirejs-config.js#L9 and https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/etc/config.xml#L34

**Comment by alena-marchenko** [comment]
Hi @middlegrey,

If the issue still persist, please provide us with exact steps to reproduce and specify magento version that you are using.

**Comment by middlegrey** [comment]
Hi Alena,

To get around the problem, I changed the external resource string in requirejs-config.js to https://js.braintreegateway.com/v2/braintree.js?nomin

And am currently using 2.0.2

**Comment by alena-marchenko** [comment]
Hi @middlegrey 

This issue is already solved in develop  branchby using minified version of sdk only https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/view/frontend/requirejs-config.js#L9 and https://github.com/magento/magento2/blob/develop/app/code/Magento/Braintree/etc/config.xml#L34
Closing this issue, please feel free contacting us if you have any further issues.
