### ISSUE TITLE
GraphQl Products result is not cached 

### ISSUE THREAD

**Issue by m08110071** [magento/magento2#39173]
### Preconditions and environment

- Magento 2.4.7-p2
- Enable full cache type

### Steps to reproduce

- Call any graphQl products

### Expected result

At the second time, cache data should be return

### Actual result

products query result was not cached

### Additional information

Missing define `\Magento\GraphQlResolverCache\Model\Resolver\Result\ResolverIdentityClassProvider::$cacheableResolverClassNameIdentityMap` for products

It is same issue for many queries: categories, ...

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment]
Hello @m08110071,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the latest released version i.e. 2.4.7-p2 and for us the issue is not reproducible. Please have a look at the below screenshots for reference:

The first request took around 496ms:
![image](https://github.com/user-attachments/assets/bf37d00e-4e6d-4739-a78e-74c5c5c10418)

The second request took around 238ms:
![image](https://github.com/user-attachments/assets/65e19af6-b83c-403b-9465-deee010c2cb1)

The second request was served from the cache. Please let us know if we missed anything.

Thanks
