### ISSUE TITLE
GraphQl get configurable variant error

### ISSUE THREAD

**Issue by m08110071** [magento/magento2#39180]
### Preconditions and environment

- Magento 2.4.7-p2

### Steps to reproduce

- Create a simple product S1
- Create a configurable product C1 and assign S1 as child product
- Create a configurable product C2 and assign S1 as child product
- Call GraphQl products with variants for two configurable products

### Expected result

Response status is success

### Actual result

Get error with log:
`{"exception":"[object] (GraphQL\\Error\\Error(code: 0): Item (Magento\\Catalog\\Model\\Product\\Interceptor) with the same ID \"1276\" already exists. at vendor/webonyx/graphql-php/src/Error/Error.php:170)`

### Additional information

This issue happen when there are multi configurable products use same child product

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @m08110071,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create a simple product S1
- Create a configurable product C1 and assign S1 as child product
- Create a configurable product C2 and assign S1 as child product
- Call GraphQl products with variants for two configurable products


<img width="1315" alt="Screenshot 2024-11-11 at 11 19 23" src="https://github.com/user-attachments/assets/0f59ee82-2a13-4c58-a6fd-9ab9f6e27631">



Response status was success.

Kindly recheck the issue in Latest 2.4-develop instance and let us know still if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @m08110071,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Comment by bckpff** [comment]
@magento give me 2.4-develop instance

**Comment by m08110071** [comment]
This issue has not fixed in source code yet but there is quality patch to resolve it

[ACSD-60631_2.4.7-p1.patch](https://github.com/user-attachments/files/19335038/ACSD-60631_2.4.7-p1.patch)
