### ISSUE TITLE
Backend: Customer grid not filtered accordingly to admin scope 

### ISSUE THREAD

**Issue by FloForMagento** [magento/magento2#39190]
### Preconditions and environment

- Adobe Commerce ver. 2.4.5-p8

### Steps to reproduce

1. In customer grid, with no filter set, have at least two customers on different websites in results. 
2. In System, User Roles, create a new role. In Role ressources, change Role Scopes from All to custom, select only one website. 
3. Affect this role to an admin user, log in with that admin user. 
4. Go in Customers, all customers

### Expected result

Grid should show customers accordingly to admin user scope. 

### Actual result

Magento throw an exception: "More permissions are needed to view this item." 

### Additional information

The problem is that Magento don't use admin user scope to filter request on customer_grid_flat. It does control scope after that, in Magento\AdminGws\Model\Model::customerLoadAfter, call to hasStoreAccess return false and lead to the exception. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @FloForMagento,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.


<img width="1331" alt="Screenshot 2024-10-03 at 09 28 18" src="https://github.com/user-attachments/assets/dfd995aa-6fca-42d7-a428-007675a19352">



<img width="1331" alt="Screenshot 2024-10-03 at 09 27 38" src="https://github.com/user-attachments/assets/649cd2b9-3cd6-41e9-b46e-2fe477ba6f42">



Grid showing customers accordingly to admin user scope.

Kindly recheck the issue in Latest 2.4-develop instance with EE edition and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by FloForMagento** [comment]
@magento give me 2.4-develop instance
