### ISSUE TITLE
(Suggestion) Provide method to translate only the storefront

### ISSUE THREAD

**Issue by dgunwin** [magento/magento2#3920]
I am translating my Magento 2 website. I would like to keep English for the admin pages, but use another language for the storefront (i.e. the pages customers see). This should mean there will be far fewer phrases to translate, as the admin pages will remain in English.

I am using the Magento command-line tool to generate the translation dictionary:

`magento i18n:collect-phrases -o "/var/www/html/magento2/tr_TR.csv" -m`

This outputs phrases used on the entire site - i.e. storefront AND admin pages.

I think it would useful if there was a 'flag' that instructed the 'collect-phrases' command to only collect phrases that are used on the storefront (and ignore the phrases that are used on the admin pages).

I think this would be a useful feature, because if the store administrator(s) can speak reasonably good English, they’ll only need to spend time / money translating the content customers will see, rather than having to translate all of the admin pages too.

**Comment by jigneshthummar** [comment]
i think good idea to gather strings of particular module as well so we can generate tranlsation file per module

**Comment by piotrekkaminski** [comment]
Due to the structure of translations it would be really hard to distinguish admin from front-end strings. All the popular languages should be translated using https://crowdin.com/project/magento-2, which should not require you to spend time or money translating the core strings yourself. The only thing left to translate is the custom content, which does not really differ between admin and front-end. 

Translations can already be generated with column indicating which module they come from, which allows to translate only single module.

As such, this feature request is not in our backlog.
