### ISSUE TITLE
need an API to get parent product SKU using child SKU

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#3921]
Here our scenario is : 
We are updating any value of child product then on third party we need updated products so, there we need to find the configurable product sku of updated child product.

We are using /V1/products/:sku but it is not returning the sku of parent product.

Please let me know any way or suggestion, how we can get this without changing anything in magento2 and using standard rest apis

Thanks!

**Comment by choukalos** [comment]
Hi @ankursachdeva11 I'm not sure I understand the use case.  Who/What is driving the update of a child product ( is that merchandizing... aka changing description?  ).  Why is the parent config product SKU needed.  Can you provide more background?  Could a SKU naming convention for configurable products address this (aka shirt_bob is parent sku, then shirt_bob_small_red or shirt_bob_small_blue ... ) or is that not viable due to mapping to 3rd party suppliers and other integrations?

Use case:  updating a child product, need to find parent configuration product ( to get that SKU ), (?for what reason? ... ?infer need parent config sku to talk to 3rd party system ?infer)

Thanks!

**Comment by choukalos** [comment]
Re-assigning to Mark

**Comment by mbrinton01** [comment]
Internal issue MAGETWO-52809

**Comment by mbrinton01** [comment]
@ankursachdeva11 do you have any update?  Please provide more detail on the use case for this request.

**Comment by mbrinton01** [comment]
Closing this issue as no feedback has been provided.
