### ISSUE TITLE
Salable quantity constantly growing

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [magento/magento2#39211]
### Preconditions and environment

- Magento version: 2.4.7-p2
- FedEx shipping

### Steps to reproduce

1. Navigate to backend
2. Create shipping for ordered product
3. Navigate to products
4. Add one item in product stock

### Expected result

Salable quantity should be consistent with quantity in stock.

### Actual result

Slaable quantity keeps growing.

### Additional information

Before shipping, stock of product shows 1 item and salable quantity shows 3 items.

<img width="534" alt="Capture d’écran 2024-09-25 à 11 17 59" src="https://github.com/user-attachments/assets/6ca55b87-eaf2-4674-971d-ef8b77760ad2">

After shipping created with FedEx module, stock of product shows 0 item, product is out of stock and salable items show 0 also.

<img width="536" alt="Capture d’écran 2024-09-25 à 11 18 28" src="https://github.com/user-attachments/assets/3db38ad4-d304-41ca-b47a-df8cd0c028e4">

When I put one item back in stock, quantity shows 1 and salable shows 4.

<img width="535" alt="Capture d’écran 2024-09-25 à 11 23 45" src="https://github.com/user-attachments/assets/57362ec6-74a9-4fe2-bdd9-43c17ca63b1c">

If I repeat this operation, quantity shows 1 and salable shows 5 and so on.

This only occurs when shipping has changed the stock.

**If I change manually the product back to 0 / out of stock, then 1 / back in stock, salable keeps showing 4 items.**

This is very important as we always have very low stock of products (1 or 2) and we produce daily on demand. Having too many items in salable quantity could lead us to not be able to delivery.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by fabiopelloso** [comment]
@magento-engcom-team give me 2.4.7 instance

**Comment by fabiopelloso** [comment]
@magento give me 2.4.7 instance

**Comment by engcom-Bravo** [comment]
Hi @ShapesGraphicStudio,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Before Shipping** :

<img width="1327" alt="Screenshot 2024-10-01 at 16 11 10" src="https://github.com/user-attachments/assets/109222b8-6ecc-4704-b66b-2466aac8a172">


**After Shipping with fedex** :

<img width="1327" alt="Screenshot 2024-10-01 at 16 14 40" src="https://github.com/user-attachments/assets/20590805-125a-4004-a28a-9afb81acbdfd">


When we put item in stock Salable quantity is consistent.


<img width="1327" alt="Screenshot 2024-10-01 at 16 15 32" src="https://github.com/user-attachments/assets/228f92bd-bd44-4513-92b4-ab7aa2a4a9d3">



Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by ShapesGraphicStudio** [comment]
We do not have simple products, only configurable.
And we also have multiple stores.
Could it explain the issue and wht you can't reproduce it?

**Comment by engcom-Bravo** [comment]
Hi @ShapesGraphicStudio,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Before Shipping** :


<img width="1366" alt="Screenshot 2024-11-12 at 09 51 50" src="https://github.com/user-attachments/assets/9229beb6-a410-4755-aed4-a4b6499416b9">


**After Shipping with fedex**

<img width="1366" alt="Screenshot 2024-11-12 at 10 02 21" src="https://github.com/user-attachments/assets/4637fc21-1a79-4b60-a957-257b19a7077b">



<img width="1366" alt="Screenshot 2024-11-12 at 10 02 46" src="https://github.com/user-attachments/assets/a7ada562-b159-4801-9262-60f33b8aca2f">


Salable quantity was consistent for the configurable products when quantity was back in stock.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @ShapesGraphicStudio,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
