### ISSUE TITLE
ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range

### ISSUE THREAD

**Issue by GNUXDAR** [magento/magento2#39313]
### Preconditions and environment

- Magento version: Adobe Commerce ver. 2.4.6-p6
- Anything else that would help a developer reproduce the bug:

### Steps to reproduce

- Upload a .gif image in any product  and make it base, small, thumb all
- Save the product
- Go to PDP 
GIF image
![SMX110NZA](https://github.com/user-attachments/assets/1bdd0b9f-3b9c-420f-a802-9b19037972ab)

### Expected result

image .gif animated

### Actual result

![local-gif-base](https://github.com/user-attachments/assets/af68caba-e164-4da9-91e5-583473b7c34f)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by GNUXDAR** [comment]
@magento I am working on this

**Comment by GNUXDAR** [comment]
@magento add to contributors team

**Comment by engcom-Bravo** [comment]
Hi @GNUXDAR,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1317" alt="Screenshot 2024-11-04 at 10 36 47" src="https://github.com/user-attachments/assets/92a3cb15-6ac8-4f9d-b429-bb85093b402a">


image .gif animated.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @GNUXDAR,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
