### ISSUE TITLE
Error saving new address in address book for customer with Share Customer Accounts enabled

### ISSUE THREAD

**Issue by alessandrogrisafi** [magento/magento2#39348]
### Preconditions and environment

- Magento version 2.4.5-p10

### Steps to reproduce

- Install a clean version of Magento
- Create at least two stores, for example IT and UK
- Inside the section `Stores -> Configuration -> General -> General -> Allow Countries` set **only** Italy for the IT store and **only** United Kingdom for the UK store
- Enable `Stores -> Configuration -> General -> Web -> Add Store Code to Urls`
- Set `Stores -> Configuration -> Customers -> Customer configuration -> Account Sharing Options -> Share Customer Accounts` to "Global"
- Create a customer account in the IT store (`<base-url>/it`)
- Go to the UK store (`<base-url>/uk`) and log in with the customer created in the IT store
- Add a product to the cart and in the checkout specify a new shipping address in the UK
- Complete the order 

### Expected result

Order is placed

### Actual result

Placing the order appears the errore `Invalid value of "GB" provided for the countryId field.`

### Additional information

The issue arises because, when saving a new address in `\Magento\Customer\Model\ResourceModel\AddressRepository::save`, the store ID of the address is set to match the customer’s store ID:
>         $addressModel->setStoreId($customerModel->getStoreId());
During validation in `\Magento\Customer\Model\Address\Validator\Country::validateCountry`, an address in the UK (with country code GB) fails validation. This happens because `validateCountry` checks the list of allowed countries based on the store ID associated with the address, which is inherited from the customer.
In this example the customer is associated with the Italian store (IT) so the address will also use this store ID, resulting in a list of allowed countries that does not include the UK (GB). Consequently, the UK address is invalid and the order cannot be placed

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @alessandrogrisafi,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Install a clean version of Magento
- Create at least two stores, for example IT and UK
- Inside the section Stores -> Configuration -> General -> General -> Allow Countries set only Italy for the IT store and only United Kingdom for the UK store
- Enable Stores -> Configuration -> General -> Web -> Add Store Code to Urls
- Set Stores -> Configuration -> Customers -> Customer configuration -> Account Sharing Options -> Share Customer Accounts to "Global"
- Create a customer account in the IT store (<base-url>/it)
- Go to the UK store (<base-url>/uk) and log in with the customer created in the IT store
- Add a product to the cart and in the checkout specify a new shipping address in the UK
- Complete the order


![Order-5000000001-11-13-2024_10_26_AM](https://github.com/user-attachments/assets/fa3f0e9e-9f22-4b46-8450-f380040d6874)



We are able to place the order in the UK Store.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by alessandrogrisafi** [comment]
Hi,

We're currently using Magento version 2.4.5, as specified in the first comment, rather than the latest 2.4-develop instance (which I assume is version 2.4.7). I've replicated the issue on a vanilla Magento 2.4.5 setup.

Could you please attempt to replicate the issue on Magento 2.4.5 following the same steps?

Additionally, I originally overlooked a minor configuration detail: the IT and UK stores have their Default Country settings set to Italy and the United Kingdom, respectively.

![image](https://github.com/user-attachments/assets/a0231b04-880c-4c06-9121-41539e5d4370)
![image](https://github.com/user-attachments/assets/2bda6d93-7e2d-4df5-b360-c7361cbb3a04)

Thank you!

**Comment by engcom-Bravo** [comment]
Hi @alessandrogrisafi,

Thanks for your update.

It is recommended to verify the issue in Latest 2.4-develop instance as it is having latest codebase.Could you please verify the issue in Latest Magento instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by alessandrogrisafi** [comment]
Hi,

We had a similar discussion with the Adobe Enterprise Support Team, and after several iterations, we identified that the key factor in reproducing the bug is not just creating two different stores, but ensuring that the stores are under different websites as well.

Using this setup, they were able to reproduce the issue in Magento 2.4.5-p10. The bug appears to be resolved in Magento 2.4.7-p3, and they are now working on creating a patch for Magento 2.4.5-p10 to address the issue in the same way it was fixed in Magento 2.4.7-p3.

Thank you for your support. This issue can now be closed.
