### ISSUE TITLE
Magento_Sales released with wrong version number

### ISSUE THREAD

**Issue by fooman** [magento/magento2#3936]
Magento 2.0.3 includes `magento/module-sales": "100.0.4",`

However the following functionality was added as part of this release

```
+    <preference for="Magento\Sales\Api\Data\ShippingInterface" type="Magento\Sales\Model\Order\Shipping"/>
+    <preference for="Magento\Sales\Api\Data\ShippingAssignmentInterface" type="Magento\Sales\Model\Order\ShippingAssignment"/>
     <preference for="Magento\Sales\Api\Data\TransactionInterface" type="Magento\Sales\Model\Order\Payment\Transaction"/>
     <preference for="Magento\Sales\Api\Data\TransactionSearchResultInterface" type="Magento\Sales\Model\ResourceModel\Order\Payment\Transaction\Collection"/>
+    <preference for="Magento\Sales\Api\Data\TotalInterface" type="Magento\Sales\Model\Order\ShippingTotal"/>
```

to follow semantic versioning I would expect the version number to be 100.1.0.

> MINOR version when you add functionality in a backwards-compatible manner, and

### Preconditions

1. Magento 2 code.

### Steps to reproduce

1. Observe /[Magento root]/app/code/Magento/Sales/etc/di.xml source code.
2. At least one of next dependencies is present: 
`<preference for="Magento\Sales\Api\Data\ShippingInterface" type="Magento\Sales\Model\Order\Shipping"/>`
`<preference for="Magento\Sales\Api\Data\ShippingInterface" type="Magento\Sales\Model\Order\Shipping"/>`
`<preference for="Magento\Sales\Api\Data\TotalInterface" type="Magento\Sales\Model\Order\ShippingTotal"/>`
3. Observe  /[Magento root]/app/code/Magento/Sales/etc/module.xml source code.

### Expected result
`<module name="Magento_Sales" setup_version="2.1.*">`

### Actual result
`<module name="Magento_Sales" setup_version="2.0.*">`

**Comment by tobi-pb** [comment]
+1

**Comment by alankent** [comment]
Just noting this is being investigated internally. There are no existing interfaces modified. No client of the module is impacted. E.g. if you have an interface, and add a method, then if you call the interface you don't care about the extra method. If you implement the interface, you do care because your code would break. In this case neither situation has arisen (from what I can see). A new separate interface was added without breaking existing code - should that trigger a minor number increment? Adding a new function somewhere in the code base does not automatically trigger a MINOR number increment.

The question in this case I think is because new preferences were added - does that represent a MINOR SemVer change. More pondering required. (We have had lengthy internal discussions on PHP interfaces and SemVer with API and SPI relationships. You cannot really capture both in the one version number.)

**Comment by davidverholen** [comment]
adding a new Interface adds new functionality and should trigger a minor version update.
Changing Interfaces would be breaking compatibility with external code using these Interfaces and should trigger a major version update

**Comment by fooman** [comment]
> A new separate interface was added without breaking existing code - should that trigger a minor number increment? 

Yes

> Adding a new function somewhere in the code base does not automatically trigger a MINOR number increment.

Maybe I read semantic versioning differently - one could of course argue that @api annotated methods/classes are really only the public api as per [item 1](http://semver.org/#spec-item-1) but in my view that contradicts one of the stated goals of M2 of better maintainability and stability. 

For every code change I would go through the following questions:

Is it a breaking change (doesn't matter feature or fix)? Yes -> increase Major Version
Is it a new feature? Yes -> increase Minor Version
Is it a fix? Yes -> increase Patch Version

The added code adds new functionality around shipping assignments (because it was implemented to not break existing interfaces) only a minor version bump is needed in my view.

**Comment by Vinai** [comment]
I can see how it makes sense to "educate" or "encourage" third party developers to stick to `@api` interfaces by using only `@api` changes for determining required version updates.  

On the other side, for third party developers more frequent version updates reflecting changes to the implementations also would be more convenient.

This is true especially since the `@api` coverage isn't where it needs to be yet. This also applies to the internal usage of service contracts between modules (so core functionality can cleanly be replaced with custom implementations by extensions).

So in an ideal world binding version updates to `@api` changes only would be the right thing to do, but since we don't live in an ideal `@api` world (yet), I think the pragmatic thing to do would be to favor more frequent version updates whenever implementations change, rather then breaking third party code.  

I think more cleanup and continued refactoring of the M2 code is required for it to become a long term success. So I for one would welcome more b/c breaks (more frequent major version increments) until the platform reaches a state, where the service contracts can really be used for the majority of customizations.  
At that point in time it would make sense to introduce a policy change and bind version `SemVer` updates to `@api` changes only.

I realize this is a hugely political topic with no clearly right or wrong answer and it's up to Magento to decide. Just thought I'd give my $.02 on it since @fooman kindly opened this issue.

**Comment by davidverholen** [comment]
maybe I got this wrong but I thought the Interfaces under Api directory are api by convention and the @api annotation is an addition for classes outside of the api directory

**Comment by fooman** [comment]
I have added a proposal to make semantic versioning policy comprehensive here #4228

**Comment by maksek** [comment]
@fooman, it makes complete sense to bump minor version for the module with the changes, after adding the interfaces. we have tool which scan modules for changes and identify type of change and do proposal which version must be bumped for next release. Also we simplified logic for patches, and do bump of all modules in 2.0.5, to resolve issues in our repo. We will continue work on our tool improvements. 
Also we did not identified major issues with existing extensions, with changing fix version versus minor for incremental interface additional.

**Comment by cspruiell** [comment]
An internal ticket (MAGETWO-52703) has been created to track this issue.

**Comment by magento-engcom-team** [comment]
@fooman, thank you for your report.
We've created internal ticket(s) MAGETWO-84518, MAGETWO-52703 to track progress on the issue.

**Comment by fooman** [comment]
Closing this as subsequent progress has been made in communication and procedures around versioning.
