### ISSUE TITLE
Can't export "Products Ordered" report to CSV or Excel

### ISSUE THREAD

**Issue by granthony** [magento/magento2#39407]
### Preconditions and environment

- Magento version: 2.4.6-p8, 2.4.5-p10

### Steps to reproduce

In the Magento Admin, navigate to Reports > Products > Ordered
Select "Export to CSV" and click "Export"
Select "Export to Excel XML" and click "Export"

### Expected result

A download should be initiated of a CSV (or Excel XML) showing ordered products in the chosen timeframe

### Actual result

Magento Admin displays a 404 Error "Page not found"

![Screenshot_20241127_153400](https://github.com/user-attachments/assets/c7a06cf8-7d6a-4c56-8997-5ba1a4b2f0f1)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment]
Hi @granthony ,

Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4-develop instance and the issue is reproducible. Kindly refer the screenshots.

**Steps to reproduce**
1. In the Magento Admin, navigate to Reports > Products > Ordered
2. Select "Export to CSV" and click "Export"
![image](https://github.com/user-attachments/assets/c86d3b00-c67b-4af1-bfa0-5d16cc1ff8ee)
3. Select "Export to Excel XML" and click "Export"
![image](https://github.com/user-attachments/assets/d94bd80f-69cf-4241-ab98-aa195129bf21)

Thanks.

**Comment by magentoabu** [comment]
@magento I'm working on this

**Comment by magentoabu** [comment]
Hi @engcom-Delta This issue is already fixed by team, please check this [issue](https://github.com/magento/magento2/issues/39261) for more details

**Comment by engcom-Bravo** [comment]
@magentoabu Thanks for your Contribution!!.

Hi @granthony,

The issue has been already fixed by this commit https://github.com/magento/magento2/commit/7677eb61f8c672cfc0e8984d36e90ca5580e3a4f

Hence we are closing this issue.

Thanks.
