### ISSUE TITLE
Product image name end with dot not displaying on front end

### ISSUE THREAD

**Issue by sunit9** [magento/magento2#39435]
### Preconditions and environment

Magento version CE 2.4.7-p3
It may be in older version also.

### Steps to reproduce

1) Open magento admin
2) Add/edit product
3) Upload product image having name like 1...jpg ( image name ended with . (dot) Eg. abcd...jpg, product1...jpg etc)
4) Save product. You can that image in admin
5) Open that product on front end. 

### Expected result

Image should be display on product page front end

### Actual result

Magento placeholder image display instead of upload image.
![2024-12-04_17-43](https://github.com/user-attachments/assets/92a16def-bb6f-49fb-96ba-732ecfa556b1)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @sunit9,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="1439" alt="Screenshot 2024-12-05 at 11 40 46 am" src="https://github.com/user-attachments/assets/a9f60879-dcdd-49a7-859a-48397559df8b">



Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by sunit9** [comment]
Thank you,
I run image resize command and it works from me also.
