### ISSUE TITLE
Printed invoice shows the wrong tax name

### ISSUE THREAD

**Issue by segway-github** [magento/magento2#39445]
### Preconditions and environment

- Magento version 2.4.6-p3
- Anything else that would help a developer reproduce the bug
When print the invoice, the California state tax shows as 'Duty'. 

### Steps to reproduce

1. Login the customer account or admin portal
2.  Find  the order and go to invoice 
3. Click 'Print' to generate the invoice

### Expected result

Printed invoice shows the same invoice as invoice preview in the webpage

### Actual result

 California state tax in Printed invoice shows as 'Duty'. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @segway-github,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Shopping-Cart-12-06-2024_09_46_AM](https://github.com/user-attachments/assets/b2042df5-6e87-4a89-ac0a-cbe26a3e2177)



<img width="1352" alt="Screenshot 2024-12-06 at 9 46 05 am" src="https://github.com/user-attachments/assets/a8a30b38-590d-4757-a6be-e90501702a0b">



<img width="794" alt="Screenshot 2024-12-06 at 9 45 52 am" src="https://github.com/user-attachments/assets/6499a170-96e6-4ff2-9ffd-ba45ee5ebcef">



Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is reproducible and let us know if we are missing anything.


Thanks.

**Comment by segway-github** [comment]
Here is the printed invoice
***@***.***

Order Page
***@***.***

Invoice Preview Page
***@***.***

From: Venkata Kumar Kuntumalla ***@***.***>
Date: Friday, December 6, 2024 at 03:51
To: magento/magento2 ***@***.***>
Cc: IT ***@***.***>, Mention ***@***.***>
Subject: Re: [magento/magento2] Printed invoice shows the wrong tax name (Issue #39445)

Hi @segway-github<https://github.com/segway-github>,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

Shopping-Cart-12-06-2024_09_46_AM.png (view on web)<https://github.com/user-attachments/assets/b2042df5-6e87-4a89-ac0a-cbe26a3e2177>
Screenshot.2024-12-06.at.9.46.05.am.png (view on web)<https://github.com/user-attachments/assets/a8a30b38-590d-4757-a6be-e90501702a0b> Screenshot.2024-12-06.at.9.45.52.am.png (view on web)<https://github.com/user-attachments/assets/6499a170-96e6-4ff2-9ffd-ba45ee5ebcef>

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is reproducible and let us know if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @segway-github,

Thanks for your update.

The attached screenshots we are not able to view or access them.Could you please provide again if possible to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @segway-github,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
