### ISSUE TITLE
Discount Amount Wrong When Apply Multi Cart Rules

### ISSUE THREAD

**Issue by m08110071** [magento/magento2#39448]
### Preconditions and environment

- Magento 2.4.7-p2

### Steps to reproduce

- Add new simple product with price 1000$, no tax
- Add new cart price rule 1 to apply for all cart: No coupon, Discount 100$ for whole cart, Priority: 1
![image](https://github.com/user-attachments/assets/3b442c72-9654-4645-bbb2-0d477fe8f315)

- Add new cart price rule 2 to apply for all cart: No coupon, Discount 10% of product price, Priority: 10
![image](https://github.com/user-attachments/assets/55f4ebce-428b-483a-ad1d-266fe2d18a27)

- Add new product to cart and go to cart page
- Check discount amount, total discount is 190$. It should be 200$
![image](https://github.com/user-attachments/assets/ac886304-4ab4-4f17-9df6-c4f79d04d72f)

- Change priority of cart price rules: rule 1 => 10, rule 2 => 1
- Check discount amount, total discount is 200$
![image](https://github.com/user-attachments/assets/138dbca6-ab2b-4fc8-9f8f-89de53b91631)

### Expected result

- Total discount amount should not depend on priority of cart price rules and should be 200$ for all cases

### Actual result

- Total discount amount is changed when cart price rules priority are changed

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment]
Hi @m08110071,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.As Per Magento devdocs https://experienceleague.adobe.com/en/docs/commerce-admin/marketing/promotions/cart-rules/price-rules-cart-create#step-3-define-the-actions it is an expected behaviour of magento.

<img width="1352" alt="Screenshot 2024-12-06 at 10 02 32 am" src="https://github.com/user-attachments/assets/7a2ab4d1-dc41-45a3-aacd-877b293af3b7">


The rule having highest priority(i.e 1) it will controls the cart first.

As per the steps to reproduce we have set priortity 1 to cart price rule 1 and priority 10 to cart price rule 2.

It will apply like this :

1000-100=900>>cart price rule 1

900-90(10%discount)=810>>cart price rule 2


<img width="456" alt="Screenshot 2024-12-06 at 10 06 51 am" src="https://github.com/user-attachments/assets/fc4a811c-9476-4e1d-b687-2a894ab73c6f">



If we change priorities of cart price rule 

It will apply like this :


1000-100(10%discount)=900>>cart price rule 1

900-100=800>>cart price rule 2

<img width="456" alt="Screenshot 2024-12-06 at 10 10 04 am" src="https://github.com/user-attachments/assets/4a1074ce-0bbb-4209-a8af-5c5f91ac921d">


Here cart price rule will control the cart first as per the priority.Could you please let us know if you are still facing any issue.

Thanks.

**Comment by GangolaManish** [comment]
@magento give me a instance

**Comment by engcom-Bravo** [comment]
Hi @m08110071,

Thanks for your update.

Since we have defined priorities for the cart price rules after applying highest priority cart price rule the price of the product will be decreased and after second rule will apply and it is an expected behaviour of magento.

Even though if we enable Discard Subsequent Rules the highest priority will control the action.

<img width="1426" alt="Screenshot 2024-12-11 at 10 08 47 am" src="https://github.com/user-attachments/assets/fef0526c-a9f7-4a2e-a6ef-25ac2e5fc9c1">


https://experienceleague.adobe.com/en/docs/commerce-admin/marketing/promotions/cart-rules/price-rules-cart-create#step-3-define-the-actions as per the document and based on the priorities it is an expected behaviour of Magento.


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @m08110071,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.
