### ISSUE TITLE
(Slightly Selfish) Request: Uninstall and downgrade scripts.

### ISSUE THREAD

**Issue by clockworkgeek** [magento/magento2#395]
As a third party dev I sometimes make changes to the database which I should like to reverse were my extension ever be uninstalled.  This feature has been [requested for several years](http://www.magentocommerce.com/boards/viewthread/22033/) but now with version 2.0 there is an opportunity.  Any previous concerns you may have had with backward compatibility don't apply now.

For example I recently added an attribute with a custom backend model.  When the extension is removed so is the backend model but the attribute remains and causes an error on every page request.

As well as an uninstall script to reverse the action of an install script I would also like to use a sequence of downgrades to complement each upgrade step.  That way I don't have to write a monolithic uninstall script for every version.

**Comment by buskamuza** [comment]
> When a you deliver a new version of your modules, you need to be able to rollback in case something goes not as expected

I'd not recommend to rely on uninstall/rollback in this case because, if something went not as expected, it means that the DB may be in an unexpected state, so uninstall/rollback may work in unexpected way too.

> it's easy with Doctrine Migrations.

Doctrine Migrations can be used for schema only. The bigger problem is to rollback data. And still, I'm not sure that it's so easy to migrate schema - as I remember, Doctrine doesn't distinguish "removing of a column + adding new column" and "renaming a column", so most likely, if you want to rename a column, all the data in it will be lost.

Question to @all: how do you imagine workflow of uninstallation a module(s)?
1. **Data Uninstall Tool**. Uninstall tool that uninstalls DB schema, DB data, media + manual removal of the code. It's up to developer how to remove the code (`composer remove`, `rm -rf module`, custom script)
2. **All-in-one Uninstall Tool**. Uninstall tool that uninstalls DB schema, DB data, media, removes the code, modifies `composer.json` (if necessary), etc.
3. Your option

**Comment by Vinai** [comment]
My preference would be your option 1, the **Data Uninstall Tool**.

I think it would work great if Magento would provide uninstall hooks to modules. These hooks would be triggered by the uninstall tool and leave the precise actions that are applied to the modules developer.

Once the triggerd actions complete, the module should be left in a deactivated state, so the files can be removed later.

Re-enabling the module at this stage would be like a fresh install.

**Comment by choukalos** [comment]
Assigned to Tanya; Note that we have an epic slated for 2.0 covering the uninstall of modules ( #MAGETWO-30245 )

**Comment by verklov** [comment]
Hi all, for feature requests, we will now be closing GitHub requests providing the ticket is created in the backlog.
We have created a ticket in our internal tracker for this improvement. We will review and handle it according to the priorities. Thank you for this request!
ID: MAGETWO-30245

**Comment by ilol** [comment]
@clockworkgeek Planned for Merchant Beta release (summer 2015)

**Comment by clockworkgeek** [comment]
Thank you @ilol. I look forward to it.

**Comment by davidalger** [comment]
@tanya-soroka or @ilol Can you confirm that this made it into the merchant beta release?

**Comment by mazhalai** [comment]
@davidalger is this what you are referring to?  http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall-mods.html

**Comment by davidalger** [comment]
@mazhalai Yes, that is exactly what I was looking for. Thanks!

This was implemented via `Magento\Framework\Setup\UninstallInterface` and is available in the latest develop branch. Closing.
