### ISSUE TITLE
Upgrading from 2.0.2 to 2.0.4 readiness check fails.

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#3959]
## Steps to reproduce

I am using XAMPP 5.6.15 under Windows (Both Windows 2012 R2 Server and Windows 10) and have the problem when trying to upgrade Magento CE from 2.0.2 to 2.0.4

I installed magento using command line:
- call composer create-project
- php bin\magento setup:install
- php bin\magento deploy:mode:set developer

Composer update and php bin\magento setup:upgrade worked without errors (I properly set write permissions to var and pub folders).

Also both frontend and backend work without problems.
## Expected result

No errors in the readiness check.
## Actual result

The following checks passed successfully:
- Check Updater Application Availability
- Check Component Dependency

But on the other hand, I get the following readiness check fails when upgrading in the backend:
- Check Cron Scripts,
- PHP Version Check (Your PHP version is . The required PHP version is .),
- PHP Settings Check
- PHP Extensions Check (missing PHP extensions.)

Setting always_populate_raw_post_data to -1 in php.ini did not resolve my problem.

I also wonder how to override Check Cron Scripts fail, since there are no cron scripts available in Windows?

**Comment by mazhalai** [comment]
1. Officially, Magento only supports [Ubuntu and Centos](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html).
2. However, since many developers use Windows, we provide limited support, but it is no way intended to be run on production in Windows.
3. Since there is no ability of cron in windows, you could try something like [windows scheduler](http://stackoverflow.com/questions/132971/what-is-the-windows-version-of-cron) 

_OR_ 

Just run the following commands manually in the following order:
`/bin/magento setup:cron:run`
`php /update/cron.php`
Once before you start upgrade, and once when updater shows as "pending"

Closing since this is not really a bug.
