### ISSUE TITLE
Need product list using store in search filter

### ISSUE THREAD

**Issue by kuldeeps3** [magento/magento2#4030]
We need to get product list using store ID by Rest WebAPI.
We have a API : http://[domain]/rest/V1/store/storeConfigs here we got stores which we use in website.

Just like we can pass status or any other field in "http://[domain]/rest/V1/products" API search filters part to get products according to status.

here we need to get product list for multi stores using different store id.

Our question is that how can we get the list of product using store id by using rest WebAPI.

Thanks, 
Kuldeep

**Comment by maghamed** [comment]
All that you need to do is to specify store code in your URL
So, instead of "http://[domain]/rest/V1/products"
you need to use
"http://[domain]/rest/<store_code>/V1/products"
Documentation could be found here http://devdocs.magento.com/guides/v2.0/rest/rest_endpoints.html
If store code is skipped (as in your case), Default store code is used.

**Comment by maksek** [comment]
Please use forum for questions.

**Comment by RUjmiak** [comment]
@maksek filter by store_code not working with V1/products on Magento 2.1.0. It is working perfectly with V1/categories.

With V1/products you will receive always the same products...
