### ISSUE TITLE
Malware found

### ISSUE THREAD

**Issue by cytracon** [magento/magento2#4042]
Malware found?

/XXX/pub/static/adminhtml/Magento/backend/de_DE/js/bundle/bundle0.js: Html.Exploit.CVE_2015_6073-1 FOUND

**Comment by piotrekkaminski** [comment]
Hey @cytracon can you give us more info? can you paste the contents of this file here or send to security@magento.com?

**Comment by cytracon** [comment]
Hi, file is too big. I just sent it to security@magento.com. Cheers, Bernard

**Comment by safwkhan** [comment]
@cytracon we have yet not received any email from you. From high level, it doesn't look like vulnerability in Magento application, please see this https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-6073. Looks like it a Microsoft Broswer issue, using which this malware was deployed in your system. Please see the work around here: https://technet.microsoft.com/library/security/ms15-113

If you still want some help from use to investigate it, we need the malware file and your server log files to see when and how it was deployed in your system (or may be you can search for that). For now, please remove the malware and see the workaround link provided.

**Comment by soydemadrid** [comment]
Hi I can also confirm that ClamAv reports this file as infected, this time in the en_US backend folder.. I don't have Windows or Edge etc. I installed Magento 2 on a LAMP web hosting server which runs ClamAv each night to check for malware. Yesterday I got this back on an email after a scan completed:

/public_html/pub/static/adminhtml/Magento/backend/en_US/js/bundle/bundle0.js: Html.Exploit.CVE_2015_6073-1 FOUND

I've disabled the file but wanted to check if this file is legit and is giving a false positive? Should I renable the file? It is 9.5mb in size...

**Comment by safwkhan** [comment]
It's a malicious file. Please see my above comment to fix it. Also, please check setting of your filesystem's ownership and permission.

**Comment by jonahnaylor** [comment]
Hi thanks but I'm not sure what the fix is in the previous comment, as I don't use any Microsoft products or software... Could you please advise what the fix is with Magento and the correct file permissions on the folders/files to prevent this for this particular file? Thanks very much for any help.

**Comment by safwkhan** [comment]
If you are not using Microsoft Browser/products (that was a method of injecting this bundle0.js file, reported so far), then you need to find out the attack vector of how it got into your filesystem. For now, please remove the file. For proper filesystem permission, you can follow this: http://devdocs.magento.com/guides/m1x/install/installer-privileges_after.html

**Comment by niclashoyer** [comment]
ClamAV still reports this vuln on any backend `bundle0.js` file. It _seems_ to be a false positive, but I'm not sure about that. It is definitely _not_ injected from the outside. Just checked on a fresh Magento 2 installation, that was never online.

**Comment by ghost** [comment]
Hi, I've recently encountered the same issue with `bundle0.js` and took some time to review the code. After reading all the relevant parts of the js, I can confirm that (atleast in my case) it's a false-positive caused by ClamAV.

Here's a VT scan: https://virustotal.com/de/file/8100e4677a65ae5bd6ea68f683de65c4d07f1006b8c017e6cddc9d762037c0f4/analysis/1485635048/

And here is the according ClamAV sig taken from `daily.cld`:

	# Name:Type:Offset:malware hex output
	Html.Exploit.CVE_2015_6073-1;Engine:51-255,Target:3;0&1;696e7365727461646a6163656e7468746d6c;6164646576656e746c697374656e6572{-30}646f6d6e6f646572656d6f766564*737761706e6f6465


Cheers
