### ISSUE TITLE
Fatal error when reorder order with 2 bundle products

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#4049]
## Steps to reproduce

1.magento 2.0.2
2. create bundle product with 2 or more options and 1 non-required custom option
![bundle product without designer 2 details fixed price products inventory products magento admin](https://cloud.githubusercontent.com/assets/10142848/14354280/5f28b47c-fce5-11e5-95e3-e22e1b6031ce.png)
1. add this bundle product to cart twice. First time without checking custom option, 2nd - with it. Custom option here is added to create separate quote and order items using one product
2. place order
3. in admin panel invoice and ship this order.
4. go to customer account dashboard
5. go to order, click Reorder
   ![order 000000027](https://cloud.githubusercontent.com/assets/10142848/14354112/b67bb108-fce4-11e5-863c-7058bba213b3.png)
## Actual result

Fatal error: Call to a member function getPosition() on a non-object in /var/www/graffiticaps-m2.iwdfun.com/vendor/magento/module-bundle/Model/Product/Type.php on line 1019
## Note

if this bundle product has 1 item in order, or if bundle product has 1 option, everything is OK.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-53560

**Comment by NadiyaS** [comment]
Hi @Katerina1993,
this bug is really reproducible on 2.0.2 Magento version.. On the latest Magento version (2.0.7) this bug was fixed but there is another problem with reorder which was already fixed in develop branch. Please upgrade your Magento to 2.0.7 where no such fatal error. And be sure to upgrade Magento when next release will be added to make reorder possible.
Thanks.

**Comment by katesuykovskaya** [comment]
@NadiyaS thank you!
