### ISSUE TITLE
Only Primary Image Updates on Swatch/Option change

### ISSUE THREAD

**Issue by magnetic5355** [magento/magento2#4101]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add configurable product and options with multiple images per option
3. View product page and select option.
## Expected result
1. All images swap to images of option selected
2. Thumbnails swap to images of option selected
## Actual result
1. Only primary (first) image swaps
2. Only first thumbnail swaps

**Comment by joebusby** [comment]
I am not sure from your description, but it appears our problem is the same as yours where the image will update on the product listing page, but when you click on the "Add to Cart" button and go to the "You need to choose options for your item." page the product image will not update when selecting a swatch.  When I change the base unsecure url to "https" instead of "http" the process works correctly,  the product image is updated on both pages when you select a swatch.  I can't find any configuration that affects this, so it must be a bug right?  Let me know if you solve it.  If I set "Use Secure URLs on Storefront" to "No" under Configuration/General/Web the image updates on both pages, but I get un-secure pages on checkout.

**Comment by piotrekkaminski** [comment]
@caesarcxiv i'm not sure if i understood it correctly. Would you be able to record you screen with this issue?

**Comment by joebusby** [comment]
My earlier comment was for an earlier version, and this behavior seems to be fixed for us now.

**Comment by magnetic5355** [comment]
@piotrekkaminski  --- I attached an image. Initial product loaded was silver. Clicking the gold option only swapped the primary image, not subsequent images as seen in screenshot. 
![capture](https://cloud.githubusercontent.com/assets/13050060/15750105/1fa87414-28b3-11e6-902d-f871441bac2e.PNG)

**Comment by ps202** [comment]
Any update on this?

**Comment by ps202** [comment]
I am also having this issue.
Magento 2.1, configurable product (color, size).
Configurable product has more simple products in it with at least 2 images each. 
Color swatch changes on product page only the first image. The second stays as it was before...

**Comment by hemendraajmera** [comment]
solution
https://magento.stackexchange.com/questions/131308/image-not-change-on-change-swatch-option
