### ISSUE TITLE
PayPal doesn't clear Minicart but cart

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4114]
We have found a weird bug. If a customer is paying with PayPal the Minicart doesn't get cleared. However, the cart is empty, so if you click "go to cart" you see "there are no products in your cart".

Bug only occours when using PayPal out of sandbox mode.

How can we fix this? I was thinking about a session destroyer on the success.phtml but wasn't lucky to find a solution for this.

Any ideas? Its kinda important for us.

**Comment by grasdaggel** [comment]
We are using:
PHP7
Magento 2.0.4

**Comment by orlangur** [comment]
Since such blocks like Minicart are rendered on client side based on data stored in local storage, the fix is basically to specify actions which must invalidate particular sections of customer data: https://github.com/magento/magento2/blob/develop/app/code/Magento/Paypal/etc/frontend/sections.xml

So, probably some other actions than "paypal/express/placeOrder" and "paypal/payflowexpress/placeOrder" are involved when you are out of sandbox? I'm not sure such scenarios are frequently tested by the way.

**Comment by grasdaggel** [comment]
Can you elaborate how to apply a fix here? Not sure if I want to change PayPal-core-files. :/

**Comment by orlangur** [comment]
Look into Network tab of Developer Tools during your scenario and note actions involved in the process.

If there are some missing in section invalidation config, add them similar to:

```
<action name="paypal/express/placeOrder">
        <section name="cart"/>
        <section name="checkout-data"/>
    </action>
```

**Comment by alena-marchenko** [comment]
This issue is already fixed in develop branch, closing the issue.

**Comment by lgt** [comment]
can you please paste a link to the fix. I have this bug on 2.0.7

**Comment by commcad** [comment]
I have the same bug using 2.0.7 - 2.1.0rc1 - 2.1.0rc2
