### ISSUE TITLE
Error 1001 on PayPal checkout using PHP 7 in Magento 2.0.4

### ISSUE THREAD

**Issue by esiemens** [magento/magento2#4130]
Magento version 2.0.4 with latest patches PHP 7

on paypal checkout i receive error 1001

if i downgrade to PHP 5.6 checkout works just fine

**Comment by nobuttsalex** [comment]
I had the same problem so switched to the develop branch, I'm guessing the fix will be in 2.0.5 or soon after

**Comment by plentyhappy** [comment]
Same with me except I had trouble with braintree - paypal and authorize.net - spent 4 days or so down with several developers not being able to fix.  On my own, I finally decided to install fresh magento 2.0 and if that did not fix the problem downgrade to 1.9 magento.

Luckily the fresh install did "not" work.  When my most excellent hosting company heard the fresh install did not work they downgraded php 7 to php 5.5 and my life changed for the better.  Looking forward to this being fixed in 2.0.5

**Comment by YevSent** [comment]
@esiemens, thanks for your report. This issue already fixed on the develop branch, but not included to 2.0.4. You can try to use develop branch if possible.

**Comment by alena-marchenko** [comment]
Hi @esiemens 

The fix can be found at please see https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6 commit. Closing the issue, please feel free to open it if you still able to reproduce it on the develop branch.
