### ISSUE TITLE
Widget condition with unexpected character not preventing from saving

### ISSUE THREAD

**Issue by devhn** [magento/magento2#4136]
## Preconditions
1. Magento 2.1

## Steps to reproduce
1. Install Magento from `community` branch.
2. Create a new widget via admin (Content -->Widgets)
3. Widget type: Catalog Products List
4. Layout update: Specific category
5. Widget options (conditions): Set product as new from date. Entered value: {TODAY}
## Expected result
1. It should display an error about unexpected character and not allow to save the widget
## Actual result
1. Upon saving the widget it display and error on frontend (attached)
2. When trying to edit the widget it displays an error on backend (attached)

This happens when using {TODAY} as a time value and not actual formatted date.
Is the {TODAY} parameter obsolete? And will there be an option to delete the widget from the administration in the future as currently there is no selection options with actions within the Widgets section?

[errors.zip](https://github.com/magento/magento2/files/216853/errors.zip)

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-53440

**Comment by magento-engcom-team** [comment]
@devhn, thank you for your report.
We've created internal ticket(s) MAGETWO-53440 to track progress on the issue.

**Comment by vasilii-b** [comment]
I'm gonna have a look on this.

**Comment by magento-engcom-team** [comment]
Hi @devhn. Thank you for your report. 
The issue has been fixed in magento/magento2#14485 by @vasilii-b in 2.2-develop branch
Related commit(s):
 - [cc1e013ff822aacccf9c8bf9c6c320f5a9f1f606](https://github.com/magento/magento2/commit/cc1e013ff822aacccf9c8bf9c6c320f5a9f1f606)
 - [ff4b005c34c541951d31691515f1e5c33c75798e](https://github.com/magento/magento2/commit/ff4b005c34c541951d31691515f1e5c33c75798e)
 - [6c87bb36a666e17ba7f993b436cea1763699be02](https://github.com/magento/magento2/commit/6c87bb36a666e17ba7f993b436cea1763699be02)
 - [1d1d061ad4eb8c664d9abf9aaa84e7b620a8dd9a](https://github.com/magento/magento2/commit/1d1d061ad4eb8c664d9abf9aaa84e7b620a8dd9a)

The fix will be available with the upcoming 2.2.8 release.

**Comment by vasilii-b** [comment]
@gelanivishal skip forward port for this one

**Comment by magento-engcom-team** [comment]
Hi @devhn. Thank you for your report. 
The issue has been fixed in magento/magento2#19390 by @vasilii-b in 2.3-develop branch
Related commit(s):
 - [00f4f7dcbc1a9e236eb6c9c84001efcd49c92df1](https://github.com/magento/magento2/commit/00f4f7dcbc1a9e236eb6c9c84001efcd49c92df1)
 - [40086305aef6638d1004e8b4b0f86bc051732714](https://github.com/magento/magento2/commit/40086305aef6638d1004e8b4b0f86bc051732714)
 - [e6323fb113d97e6e03bfec9eb2760e584cc8f8a4](https://github.com/magento/magento2/commit/e6323fb113d97e6e03bfec9eb2760e584cc8f8a4)
 - [80fed1b5348ee1f5038700ad4e7966c45ae805f4](https://github.com/magento/magento2/commit/80fed1b5348ee1f5038700ad4e7966c45ae805f4)
 - [747f33d99ad5d62cb3862eb7738c729fb1f0feb5](https://github.com/magento/magento2/commit/747f33d99ad5d62cb3862eb7738c729fb1f0feb5)
 - [740fbd09d12a6d9175d45b88ec35e4bc1e8c1c77](https://github.com/magento/magento2/commit/740fbd09d12a6d9175d45b88ec35e4bc1e8c1c77)

The fix will be available with the upcoming 2.3.1 release.
