### ISSUE TITLE
Attribute Indexing ignores custom source model options

### ISSUE THREAD

**Issue by simonspoerri** [magento/magento2#417]
Currently The indexing of Attribute Values used for the product filters in the category overview only index multiselect attributes that use attribute options. If a custom source model is specified the values are not indexed and thus are not taken into account when filtering products.

To fix the issue in my case I created an interface which all Source Models that should be taken into account while indexing should implement. For Attributes implementing this interface not only attribute options from the DB are indexed but also all options provided by the source model.

the class in question is Mage_Catalog_Model_Resource_Product_Indexer_Eav_Source . I've overridden the _prepareMultiselectIndex Method and added the following snippet after the attribute options are loaded from 'eav/attribute_option'

```
		foreach($attrIds as $attributeId) {
			$attributeModel = Mage::getModel(Mage_Eav_Model_Entity::DEFAULT_ATTRIBUTE_MODEL)->load($attributeId);
			if($attributeModel->getSource() instanceof MyNS_MyModule_Model_Product_Attribute_Source_Interface) {
				$sourceModelOptions = $attributeModel->getSource()->getAllOptions();
				foreach($sourceModelOptions as $o) {
					$options[$attributeId][$o["value"]] = true;			
				}
			}
		}


```

Maybe I'm misusing some principles here but I really think custom source model based multiselect attributes should be filterable as well, thus they need to be indexed...

**Comment by kokoc** [comment]
@simonspoerri Thank you for reporting the issue and sorry for so biiiiig delay.

Internal reference: MAGETWO-33570
We will fix the problem and get back to you once we have the working code.

**Comment by LittleBigDev** [comment]
Hello @kokoc, did you plan a similar fix for Magento 1 ? I'm currently on EE 1.14 and iI have this bug too (class Mage_Catalog_Model_Resource_Product_Indexer_Eav_Source).
If my question should be asked somewhere else, please tell me :)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Attribute-Indexing-ignores-custom-source-model-options/idi-p/46851).

**Comment by maderlock** [comment]
This is a bug, not a feature request - one documented feature does not work with another documented feature. Please could we have an update on MAGETWO-33570?

**Comment by maderlock** [comment]
Update to the previously suggested code - this works if added at around line 246 of magento/module-catalog/Model/ResourceModel/Product/Indexer/Eav/Source.php

````
// Add options from custom source models
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$select = $this->getConnection()->select()->from(
    ['ea' => $this->getTable('eav_attribute')],
    ['attribute_id','source_model']
)->where('attribute_id IN(?)', $attrIds)
 ->where('source_model is not null');
$query = $select->query();
while ($row = $query->fetch()) {
    try {
        // Load custom source class and its options
        $source = $objectManager->create($row['source_model']);
        $sourceModelOptions = $source->getAllOptions();
        // Add options to list used below
        foreach ($sourceModelOptions as $o) {
            $options[$row['attribute_id']][$o["value"]] = true;
        }
    } catch (\BadMethodCallException $e) {
        // Skip
    }
}
````

I'm not sure if there is a better method for creating instances of the source class without the overhead of loading all the attributes, but this does fix the issue.

**Comment by maderlock** [comment]
If you are using the above for a temp fix, obviously use DI to create a preference for \Magento\Catalog\Model\ResourceModel\Product\Indexer\Eav\Source and override just the _prepareMultiselectIndex method.

**Comment by pravalitera** [comment]
@maderlock This fix does not work with custom source that has varchar values. it causes an integrity constraint on reindex. With integer values, it's ok. 
I know  it's "normal" that it does not work with varchar, but it should not provoke an error on reindex.

**Comment by JosephMaxwell** [comment]
@maderlock: thanks for that fix. I packaged it up, here: https://github.com/SwiftOtter/AttributeIndexFix

**Comment by maderlock** [comment]
Any update on this? I note that 2.1.8 has no fix for this.

**Comment by magento-engcom-team** [comment]
Hi @simonspoerri. Thank you for your report. 
The issue has been fixed in magento/magento2#19176 by @rain2o in 2.3-develop branch
Related commit(s):
 - [3de065bfeefbe324d1db903800efb6a95824e076](https://github.com/magento/magento2/commit/3de065bfeefbe324d1db903800efb6a95824e076)
 - [c6352c6c9166eba48d86852774b876ecaf34ebd8](https://github.com/magento/magento2/commit/c6352c6c9166eba48d86852774b876ecaf34ebd8)
 - [7284a78db7141db996282814ec1d7830bdeeb386](https://github.com/magento/magento2/commit/7284a78db7141db996282814ec1d7830bdeeb386)
 - [f506bf3af7b51402faea3a86d8f885bce7206982](https://github.com/magento/magento2/commit/f506bf3af7b51402faea3a86d8f885bce7206982)
 - [028a15ced987666269cf9cdb269b5002cfa5b11d](https://github.com/magento/magento2/commit/028a15ced987666269cf9cdb269b5002cfa5b11d)
 - [f38283304a86c7d720e74daed60420a9064e1e6e](https://github.com/magento/magento2/commit/f38283304a86c7d720e74daed60420a9064e1e6e)
 - [355b4c95d9513dabd5f46cc66603370bae711fd8](https://github.com/magento/magento2/commit/355b4c95d9513dabd5f46cc66603370bae711fd8)
 - [b9c4e77bc0cca1f87efa569c2804e7bfe6723025](https://github.com/magento/magento2/commit/b9c4e77bc0cca1f87efa569c2804e7bfe6723025)
 - [5142ee77533bc5f399270018affde33307f87f31](https://github.com/magento/magento2/commit/5142ee77533bc5f399270018affde33307f87f31)
 - [e940298f04b0dfbef5bb9efa1123ece974c32248](https://github.com/magento/magento2/commit/e940298f04b0dfbef5bb9efa1123ece974c32248)
 - [e12ebf1ddcb0c568986d1dff881ce50e13995068](https://github.com/magento/magento2/commit/e12ebf1ddcb0c568986d1dff881ce50e13995068)
 - [8daff66d9c4f750bd31ee7d0cc7570699ad9aeab](https://github.com/magento/magento2/commit/8daff66d9c4f750bd31ee7d0cc7570699ad9aeab)

The fix will be available with the upcoming 2.3.1 release.

**Comment by leoquijano** [comment]
Hi @magento-engcom-team,

Is this one going to be applied to the 2.2-develop line? I see PR #16727 but it doesn't seem to have commits. 2.2.7 doesn't seem to have any changes to ```Magento\Catalog\Model\ResourceModel\Product\Indexer\Eav\Source``` either.

**Comment by dattruongthe** [comment]
Hi @magento-engcom-team 

Seem this works for multi-select attribute only, Does this work for select attribute also?
