### ISSUE TITLE
getProductUrl does not allow to override the scope in backend context

### ISSUE THREAD

**Issue by fetzi** [magento/magento2#4247]
### Preconditions:

1. Magento instance with several websites
2. Each website has a specific domain (base url)

### Steps to reproduce:

1. Open a product page for a specific website in the admin area
2. Use the $product->getProductUrl() method to retrieve product url

### Expected result:

Returned product url relates to specified website

### Actual result:

Magento always uses the 'admin' scope (and the default base url) to retrieve product url and returns incorrect url.

I'm trying to implement a custom indexer in Magento 2.0.4. The indexer should send product data to an external service. It is possible to get all store specific values of the product except the product url.

By calling the method `$product->getProductUrl()` I'm always retreiving the product's url with the admin storekey in it. (for example `http://HOST/admin/catalog/product/view/...`)

I've looked into the problem and the method `getBaseUrl` in `Magento\Framework\Url` offers the possiblity to override the url scope with the parameter `_scope`. 

In backend context the subclass `Magento\Backend\Model\Url` is used and the call to [_getScope()](https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/Model/Url.php#L410) which is executed within the getBaseUrl() method always returns the admin store. `Magento\Framework\Url::_getScope()` uses the data value of `scope` instead.

I think that it should be possible to also override the scope in backend context.

**Comment by daim2k5** [comment]
The GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. In your case, the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) is likely the most appropriate. Feel free to reopen this issue if you think you have encountered a bug in Magento 2.

**Comment by fetzi** [comment]
This is a technical issue. The method override `_getScope()` in `Magento\Backend\Model\Url` breaks the functionality of `Magento\Framework\Url::getBaseUrl` (which allows to set the scope of the url). Please reopen the ticket!

**Comment by alexpoletaev** [comment]
I have the same issue. There is no ability to retrieve product url for a specific website in the admin area.
**Preconditions:**
- Magento instance (v2.1) with several websites
- Each website has a specific domain (base url)

**Steps to reproduce:**
- open a product page for a specific website in the admin area
- use the `$product->getProductUrl()` method to retrieve product url

**Result:**
Magento always uses the 'admin' scope (and the default base url) to retrieve product url and returns incorrect url.

**Stack trace:**
- `Magento\Catalog\Model\Product\Url::getUrl()` method, check out the code `$this->getUrlInstance()->setScope($storeId)->getUrl($routePath, $routeParams)`
- `Magento\Framework\Url::setScope()` - here Magento sets a 'scope' variable in Data Object
- `Magento\Framework\Url::getBaseUrl()` - for the product url Magento executes this method without any params
- `Magento\Backend\Model\Url::_getScope()` - here Magento checks for the local '_scope' variable which always is null (while the 'scope' is located in the Data Object, `Magento\Framework\Url::getData('scope')`) and returns the 'admin' scope

Please reopen this ticket and fix this issue. Thanks.

**Comment by sshymko** [comment]
Same issue here. Please reopen the ticket. @piotrekkaminski, please help.

**Comment by silverman63** [comment]
Same issue as well.

**Comment by sshymko** [comment]
@daim2k5, @piotrekkaminski,
Could you kindly reopen the ticket, it's a technical bug not a discussion topic for the forum.

**Comment by pboisvert** [comment]
reopening the ticket

**Comment by sshymko** [comment]
Thanks @pboisvert!

**Comment by nickgundry** [comment]
@pboisvert Any update on the status of this issue? Thanks

**Comment by magento-engcom-team** [comment]
@fetzi, thank you for your report.
We've created internal ticket(s) MAGETWO-84492 to track progress on the issue.

**Comment by sebastian-enz** [comment]
@magento-engcom-team Any update on this issue? :) It is a critical issue that should be fixed in 2.3 in my opinion. Lots of people affected by this.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by irajneeshgupta** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by fetzi** [comment]
![](https://botlab.io/wp-content/uploads/2017/07/1-BBT_ZPaQIuw5YUqiQ1FXew-1080x588.png)

**Comment by sebastian-enz** [comment]
@fetzi Please don't close this issue just because of frustration. 👎 This is a valid issue, and MUST be fixed. @magento-engcom-team *Please* take a closer look, it's a real issue that affects merchants.

**Comment by fetzi** [comment]
Sorry, but after almost 3 years since ticket creation, I think this step is legit. The way the magento core team handles community issues forced me to stop working with magento. 

You are free to open your own issue but I have absolutely no interest in this one any more.

**Comment by sebastian-enz** [comment]
@shikhamis11 Please re-open, or create a new ticket, or remove fetzi from this ticket. Also, as you've assigned this to yourself, would you please talk to your point of contact with Magento so this issue is finally taken care of?

**Comment by shikhamis11** [comment]
@fetzi yes I know It's annoying to wait so long for any issue to be fixed but still I would suggest you to let this issue remain open this will be surely taken care of.

**Comment by shikhamis11** [comment]
@ikk0 sure

**Comment by orlangur** [comment]
Valid issues must not be closed even if author stopped working with Magento.

**Comment by magento-engcom-team** [comment]
Hi @fetzi. Thank you for your report. 
The issue has been fixed in magento/magento2#21876 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [c50975a7b3dd61cbc0d030cb56b4f0099a61921d](https://github.com/magento/magento2/commit/c50975a7b3dd61cbc0d030cb56b4f0099a61921d)

The fix will be available with the upcoming 2.3.3 release.
