### ISSUE TITLE
Validations not working on customer registration on DOB field. 

### ISSUE THREAD

**Issue by sourabh-ranosys** [magento/magento2#4248]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. From Magento backend using store configuration set DOB in customer form as required.
3. Go to frontend on registration page and hit submit without filling any entry.
4. DOB field has an star mentioned as required but no validation messages is populating for this but working fine for other fields.
## Expected result
1. Error should show when someone submits the form without filling the DOB.

**Comment by mazhalai** [comment]
@skmomemo thank you for reporting, we have created MAGETWO-52244 to investigate and fix.

**Comment by kumbas1** [comment]
Fixed in scope of 35732a1

**Comment by anton-huz** [comment]
Hi @skmomemo 
You can retest issue on current develop branch.
Fill free continue discussion if it still reproducible for you.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80096

**Comment by digvijay2017** [comment]
Fixed in 2.2.1. Thanks

**Comment by okorshenko** [comment]
Hi @skmomemo. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1353 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 299109f1265fa15eeb3067e22c2638ff5907205e
 - 57318bf03bf6fe7f84b2956ffb5ecc1332bf41b3
 - 41cd961a217d30c4b7b051a775902c4fb40b84ea
 - 076b90398852478d93d1444f936ac483b4640a82
 - 435a6c200cd548b8765e5bc73b0458039a58645d
 - 5d174b873f8ba369d6504fb9d7ef30296816e2b1
 - a47b10dce854a2d21ead6b362b86ca3ddf595386
 - ab48cb176830ddab69fd1617cae96d76094ab167
 - 46be4c7ea59f6cfb9884f2bc5875245b1960edc6
 - eafc6f0a473547542c3ef80352dcd2be7128da87
 - 63b9e909f1173a51374d4cdfc68249baa66f0007
 - 2edfe9a30bb64f0a7e102bb335a89658b627bfad
 - ef5ddffb43a735627d09535b62fac2a41804a96a
 - 4ada797ece84c2f5eb55499e8bc3f75e0c7ef245
 - c5d9a019b0d51a51b452fd99b527e3b894874be2
 - 72e9e0732b98ea5b8f47bddc781dc47c688c3c58
 - 215180de0a3f6c4a16e02205732bfe8670293ad2
 - 685d50625b68dbb960988a6bfbbfc14455a6cb9e

The fix will be available with the upcoming 2.3.0 release.
