### ISSUE TITLE
Hit fast twice F5 on checout page, customer loggs out automatically

### ISSUE THREAD

**Issue by daniel-ifrim** [magento/magento2#4301]
Steps to reproduce
1. http://magento2-demo.nexcess.net or Magento 2.0.4 with cache enabled (page cache too).
2. Have products in cart as logged in customer
3. Go to checkout page.
4. Hit fast twice F5 key in browser
5. Customer is not logged in anymore.

Expected result
1. Customer should stay as logged in

Actual result
1. Customer is not logged in anymore

It may be related to module-customer/view/frontend/web/js/customer-data.js

Thank you

**Comment by piotrekkaminski** [comment]
internal issues (related) MAGETWO-32380

**Comment by Zaylril** [comment]
Yes you also have this issue if you stop the page load mid-way through on the checkout. Cart is emptied and customer logged out

**Comment by tkotosz** [comment]
and the minicart still shows the items after this logout happens

**Comment by daniel-ifrim** [comment]
Actually the 2 times hit happens on every button or link that points to cart or checkout. Hit twice checkout button on cart page. Why would I hit twice: high traffic, server isn't serving pages fast enough or I just don't see in browser that the next page is loading - sent request. The following statement isn't related to the current issue: hit checkout button on cart page while cart page sections are still loading.

**Comment by SerhiyShkolyarenko** [comment]
@daniel-ifrim @Zaylril is it still reproducible for you on 2.0.9 or 2.1.11? if so, please clarify if you use secure catalog and secure checkout.

**Comment by SerhiyShkolyarenko** [comment]
Tried double hitting F5 on checkout and didn't reproduce the issue. Version 2.1.1.

**Comment by tkotosz** [comment]
I can reproduce this issue in 2.0.6, but it seems it is fixed in 2.1.1

**Comment by daniel-ifrim** [comment]
@SerhiyShkolyarenko I don't have 2.1.1 anywhere. If it works for you it works for any than. Thank you!

**Comment by SerhiyShkolyarenko** [comment]
Reproduced the issue on 2.0.9. Ticket for backporting fix is MAGETWO-57341. Thanks everybody for taking part!

**Comment by magento-engcom-team** [comment]
@daniel-ifrim, thank you for your report.
We've created internal ticket(s) MAGETWO-80855 to track progress on the issue.

**Comment by erikhansen** [comment]
I'm experiencing this behavior on two 2.1.9 sites. Another way to reproduce the issue is:

1. Add a product to cart.
2. From the mini-cart, click the "Go To Checkout" button and then immediately click the "View and edit cart" link.
3. The cart will be empty with this error message: "You have no items in your shopping cart."

**Comment by missoxd** [comment]
I'm experiencing this behavior on Magento 2.2 too.

Doing some research i found in method `Magento\Checkout\Controller\Index\Index::execute()`, around line 35, a call to `$this->_customerSession->regenerateId()`.

When we fire two (or more) subsequent requests, they come to the server with the same session id. But the first request regenerates the session id, getting a new one (and destroying the last one), so the latter requests are getting an empty session.

Maybe there is some magento store/webserver configuration that i am forgetting about, sorry if that's the case.

Using Apache/2.4.18 (Ubuntu) with PHP 7.0.27.

**Comment by erikhansen** [comment]
This appears to be related to #12362. I've experienced this issue recently on a Magento 2.2.2 installation.

**Comment by elioermini** [comment]
Replicating on M2.1.10 Commerce

**Comment by aeu** [comment]
Subscribing.  We are also seeing this as well as the related issues mentioned in this thread and other threads that mention this one.

**Comment by obatkova** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@obatkova thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by obatkova** [comment]
cannot reproduce the issue on the M2.1.14 and M2.2

**Comment by elioermini** [comment]
Have you tried @obatkova with PHP 7.x and Redis for session cache storage?

**Comment by ishakhsuvarov** [comment]
Closing this issue in favor of the more popular duplicate ticket.
Please continue tracking and discussion under https://github.com/magento/magento2/issues/12362
Thank you

**Comment by magento-engcom-team** [comment]
Hi @daniel-ifrim. Thank you for your report. 
The issue has been fixed in magento/magento2#14428 by @adrian-martinez-interactiv4 in 2.2-develop branch
Related commit(s):
 - [dc687c6730ad87189e86867a30e5349388a10777](https://github.com/magento/magento2/commit/dc687c6730ad87189e86867a30e5349388a10777)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @daniel-ifrim. Thank you for your report. 
The issue has been fixed in magento/magento2#14429 by @adrian-martinez-interactiv4 in 2.3-develop branch
Related commit(s):
 - [f82a17507acfa821e2bea543a99f072e1de1252f](https://github.com/magento/magento2/commit/f82a17507acfa821e2bea543a99f072e1de1252f)
 - [4d23b8b3c64e4e0276c0f562ceba36f2c5688e4d](https://github.com/magento/magento2/commit/4d23b8b3c64e4e0276c0f562ceba36f2c5688e4d)

The fix will be available with the upcoming 2.3.0 release.

**Comment by nmallepally** [comment]
@magento-engcom-team 
Any fix available for 2.1.x v ?
have the same issue with 
php 7 
magento 2.1.12
Debian
Maria DB

**Comment by aeu** [comment]
@nmallepally I applied this patch https://github.com/magento/magento2/commit/a6f146cd9302fbbb6305df9613c7ce3eea7a05ae and it is fixed for me, Magento 2.1.12 PHP7.
