### ISSUE TITLE
Deploy mode assertion inconsistent

### ISSUE THREAD

**Issue by danny-balance** [magento/magento2#4304]
Manually setting app to run in production mode does not seem to be consistent across all areas of the app. Should we not be setting the deploy mode in server config?
## Steps to reproduce

Using Magento 2.0.4 EE:
1. Include `set $MAGE_MODE developer;` in nginx config (or server equivalent)
2. Run `bin/magento deploy:mode:set production` to swap to production mode
3. Run `bin/magento deploy:mode:show`, shows output is `production`
## Expected result

 `$bootstrap->isDeveloperMode()` returns `false`
## Actual result

 `$bootstrap->isDeveloperMode()` returns `true`

**Comment by mazhalai** [comment]
@danny-balance thank you for reporting, we have created MAGETWO-52318 to investigate and fix.

**Comment by rganin** [comment]
Environment variable has higher priority than `deploy:mode:set` and is designed for development purposes. This is an expected behavior.

**Comment by rganin** [comment]
@danny-balance the environment variable has higher priority than config setting, it is designed for development or debug purposes. So the Actual result is an expected behavior.
The output for `bin/magento deploy:mode:show` is a bit confusive, but also valid as server config is not loaded for console app.

**Comment by danny-balance** [comment]
Thanks for clarifying the expected behaviour @rganin
