### ISSUE TITLE
Configurable Products special Price appear for all options

### ISSUE THREAD

**Issue by gayankt** [magento/magento2#4442]
I have added special price only for one simple product of the configurable product.
Other simple products associated with it do not have special prices.
But on fronted special price appears for all options
![specialprice](https://cloud.githubusercontent.com/assets/654973/15135114/5db41892-1690-11e6-9482-f2cdbcd6cf5b.png)
## Steps to reproduce
1. Create a configurable product with different (size) options 
2. assign special price for only one size option (simple product)
3. View on front end
## Expected result

Special Price should appear only for selected (size) option

**Comment by antboiko** [comment]
Hi @gayankt , what Magento version do you use?

Could you please clarify if you have the price A$18 appearing along with "was A$22.00" for all possible configurations (i.e. Blue/L, Pink/L, Orange/S, Orange/M, etc.)?

Thanks,
Anton.

**Comment by gayankt** [comment]
Special price is added only to one simple product (SKU - WS12-S-Blue)
but it appearing on all other configurations as well

**Comment by antboiko** [comment]
Hi @gayankt , I couldn't reproduce this issue on current mainline. 

What version do you use?
Let me clarify one more time. do you see A$18 price appearing for any specified pair Color/Size of values? Could you please attach screenshots with few other combinations of values?

Thanks,
Anton.

**Comment by christianlakits** [comment]
i have the same problem.

the first product has a special price.
![bildschirmfoto vom 2016-06-20 09 27 20](https://cloud.githubusercontent.com/assets/16207574/16186156/41e0e952-36c9-11e6-8667-7a0ac3d52faa.png)

the second one has no a special price
![bildschirmfoto vom 2016-06-20 09 27 04](https://cloud.githubusercontent.com/assets/16207574/16186155/41e07eea-36c9-11e6-991d-7b6b7fe122b3.png)

i use version 2.0.7

**Comment by antboiko** [comment]
@gayankt @christianlakits thanks for reporting. Internal ticket MAGETWO-52925 was created.

**Comment by micheese** [comment]
Same problem here.

Will there be a patch soon?

Thank you very much.

**Comment by heldchen** [comment]
seeing this as well in 2.1.1

**Comment by ktruehl** [comment]
Here's a patch that might at least serve temporarily. I tried to figure out how to do this properly, but seriously, can you make these things even more (unnecessarily) complicated? So I put together a hacky patch until Magento gets its act together.

[fix-switching-of-old-prices-for-configurable-products-vendor_magento_module-catalog_view_base_web_js_price-box.diff.zip](https://github.com/magento/magento2/files/449837/fix-switching-of-old-prices-for-configurable-products-vendor_magento_module-catalog_view_base_web_js_price-box.diff.zip)

Note: You will probably have to remove the `/www` directory prefixes from the paths of the files in the patch.

**Comment by slavvka** [comment]
The issue has been fixed and delivered to the mainline. It is also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

**Comment by ktruehl** [comment]
I wish it were so.

However, if the product, which determines the initial price shown on the detail page of a configurable product, does not have a special price itself, then my previous patch is still needed. Tested it and it makes logical sense, since the provided commits don't touch the problem handled by my patch.

In addition, the above commits do not completely fix the issue when swatches are used. The file `vendor/magento/module-configurable-product/view/frontend/web/js/configurable.js` is not loaded then and the method `_displayRegularPriceBlock()` is therefore of no use. So I ported the method to the `Magento_Swatches` module:
[port_patch_magetwo-52925_to_also_work_for_configurable_swatches-vendor_magento_module-swatches_view_frontend_web_js_swatch-renderer.diff.zip](https://github.com/magento/magento2/files/470228/port_patch_magetwo-52925_to_also_work_for_configurable_swatches-vendor_magento_module-swatches_view_frontend_web_js_swatch-renderer.diff.zip)

Furthermore, the `old-price` container should not have `display: none;` if the cheapest associated product of the configurable product actually has a special price. So here's another patch taking care of that:
[show_old_price_if_different_from_special_price-vendor_magento_module-configurable-product_view_base_templates_product_price_final_price.diff.zip](https://github.com/magento/magento2/files/470232/show_old_price_if_different_from_special_price-vendor_magento_module-configurable-product_view_base_templates_product_price_final_price.diff.zip)

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 today.

**Comment by ktruehl** [comment]
So. Most of it is fixed in 2.1.4. Except for a teensy little bit:

Select a configuration via the swatches, so that a specific simple product has been uniquely determined, i.e. so that for each attribute a swatch has been selected. Then deselect one of the selected swatches, so that a simple child product is no longer uniquely determined. Et voilà. Javascript error: `TypeError: result is undefined` (Firefox).

The problem lies in `vendor/magento/module-swatches/view/frontend/web/js/swatch-renderer.js` on line 714 in the check `if (result.oldPrice.amount !== result.finalPrice.amount)`. If no simple product is uniquely determined `result` will be undefined. Find attached a patch that solves this problem.

[configurable_swatches-dont_explode_on_deselect.diff.zip](https://github.com/magento/magento2/files/793612/configurable_swatches-dont_explode_on_deselect.diff.zip)

**Comment by NerminPh** [comment]
Still my configurable products read special price and main price(with the same amount hover I didn't add special price in some of the Childs) when another child products has special price, please advice

**Comment by potticus** [comment]
> I wish it were so.
> 
> However, if the product, which determines the initial price shown on the detail page of a configurable product, does not have a special price itself, then my previous patch is still needed. Tested it and it makes logical sense, since the provided commits don't touch the problem handled by my patch.
> 
> In addition, the above commits do not completely fix the issue when swatches are used. The file `vendor/magento/module-configurable-product/view/frontend/web/js/configurable.js` is not loaded then and the method `_displayRegularPriceBlock()` is therefore of no use. So I ported the method to the `Magento_Swatches` module:
> [port_patch_magetwo-52925_to_also_work_for_configurable_swatches-vendor_magento_module-swatches_view_frontend_web_js_swatch-renderer.diff.zip](https://github.com/magento/magento2/files/470228/port_patch_magetwo-52925_to_also_work_for_configurable_swatches-vendor_magento_module-swatches_view_frontend_web_js_swatch-renderer.diff.zip)
> 
> Furthermore, the `old-price` container should not have `display: none;` if the cheapest associated product of the configurable product actually has a special price. So here's another patch taking care of that:
> [show_old_price_if_different_from_special_price-vendor_magento_module-configurable-product_view_base_templates_product_price_final_price.diff.zip](https://github.com/magento/magento2/files/470232/show_old_price_if_different_from_special_price-vendor_magento_module-configurable-product_view_base_templates_product_price_final_price.diff.zip)

These changes, particularly the swatch renderer js code change, stopped all payment gateways from completing the purchase of configurable items that used swatches. It was hard to spot this error until it was reported to us by a customer weeks later. The customer gets sent back to the site with a 'cant place the order' error.
