### ISSUE TITLE
Unable to insert multiple catalog product list widgets in CMS page

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#4468]
## Preconditions
1. Magento 2.1

## Steps to reproduce
1. Insert at least two widgets with type Catalog Product List in CMS page, in my case I want to output 16 products from one category and 16 from another one in homepage (4 products in row with pager and page size- 4)

## Actual result
error in CMS page output:
> Error filtering template: Element with ID 'widget.products.list.pager' already exists.
and no content at all.

## Expected result
Content is displayed properly, error message is absent.

**Comment by pboisvert** [comment]
@tkacheva can you review if this is a bug or an improvement?

**Comment by palamar** [comment]
@kandrejevs 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by tkacheva** [comment]
@palamar I had the same issue - MAGETWO-54911 please check

**Comment by Thuan1234** [comment]
Yes, The problem is still there. We have same issue now (version 2.1.1). I have also checked the problem on Magento Sample Data package (V2.1.1) . But we can solve this problem by disabling all cache types from Cache Management. However, the site could take 15- 20 second to load. 
Anyway, its big bug. Please fix it soon
Thanks

**Comment by phuongnd** [comment]
@tkacheva do you know when this is fixed?

**Comment by ooples** [comment]
I'm getting this error as well

**Comment by ksilliman-pipeline** [comment]
I'm getting this error too. (version 2.1.1)

**Comment by ghost** [comment]
Issue is still on 2.1.3 also. But just setting the option to remove pagination seems to work until you have the issue resolved.

**Comment by KingKarrow** [comment]
Issue still in 2.1.3. Does anyone have a workaround?

**Comment by caliboy007** [comment]
Issue is still in 2.1.5, possible due to pager (pagination) and page_var_name which seems to be generated unique to each category product list widget generated. 

What worked for me was under 'Category Products List' select Display Page Control to 'No'.

Hope this helps! Permanent solution still needed.

**Comment by phuongnd** [comment]
Yep this issue is still in Magento 2.1.5. You can temporary solve it by [**Disable Blocks HTML output cache**](http://doc.zooextension.com/magento/novetty/#disable-block-html-output-cache)

**Comment by smokygeek17** [comment]
Bug is still present in 2.1.6

**Comment by smokygeek17** [comment]
@phuongnd disabling the block output doesn't help :(

**Comment by johnsonmasih** [comment]
There error in 2.1.7 too, couldn't find the solution on whole internet...

**Comment by phuongnd** [comment]
@smokygeek17  do you refresh the cache? 

@johnsonmasih just disable blocks HTML output cache, it will be sorted out.

**Comment by johnsonmasih** [comment]
@phuongnd Refreshing cache  or disabling blocks HTML output cache didn't work

**Comment by phuongnd** [comment]
@johnsonmasih  we're using multi widget here http://novetty.zooextension.com/stores/store/switch/?___store=home9_en and it's working very well.

**Comment by smokygeek17** [comment]
@phuongnd Yes it did. And your next advise to disable the HTML output cache didn't work. 

We just used the "SKU is one of" option and listed all SKUs that are needed. 

But it's obviously a bug.

**Comment by phuongnd** [comment]
@smokygeek17 yes, it's exactly a bug. **Disable block html cache** is just a temporary solution.

**Comment by atsareva** [comment]
Hi guys! Any updates here? Thanks

**Comment by magento-engcom-team** [comment]
@kandrejevs, thank you for your report.
We've created internal ticket(s) MAGETWO-54911 to track progress on the issue.

**Comment by old-code-archive** [comment]
Bug present in 2.1.9

**Comment by olekluk** [comment]
Hi any update on this issue?
I have the same error on Magento 2.1.10
When add show_pager="1" attribute.

**Comment by mfsi-subhras** [comment]
Hey, I faced the issue in Magento 2.2 as well. Can you please let know the solution of the same.

**Comment by pixiemediaweb** [comment]
we had this issue too.  Quick solution is duplicate the widget phtml file, so you never have the same template loaded twice on the same page.

**Comment by anilspurtree** [comment]
This issue is still present in 2.2.6 version any updates ??

**Comment by anilspurtree** [comment]
The only solution seems to be disable pagination "Display Page Control" to NO

**Comment by vasilii-b** [comment]
@magento-engcom-team give me 2.3 instance

**Comment by vasilii-b** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-4468-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-4468-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-4468-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vasilii-b** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-4468-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-4468-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-4468-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
Hi @kandrejevs. Thank you for your report. 
The issue has been fixed in magento/magento2#18714 by @vasilii-b in 2.3-develop branch
Related commit(s):
 - [0a253644a43f39d8ab40701011512534f4fc34bb](https://github.com/magento/magento2/commit/0a253644a43f39d8ab40701011512534f4fc34bb)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @kandrejevs. Thank you for your report. 
The issue has been fixed in magento/magento2#18874 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [3f17772611af437165443aa2d4ac9c3a27945225](https://github.com/magento/magento2/commit/3f17772611af437165443aa2d4ac9c3a27945225)

The fix will be available with the upcoming 2.2.8 release.

**Comment by phumlaninyati** [comment]
I am on magento 2.3.0 this issue is still not fixed.
