### ISSUE TITLE
Local customer data doesn't get invalidated after account confirmation

### ISSUE THREAD

**Issue by marius-bica** [magento/magento2#4475]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Set the "Require Emails Confirmation" option in the admin to "Yes" (Stores -> Configuration -> Customers -> Customer Configuration -> Create New Account Options).
3. Make sure that at least the `config` and the `block_html` caches are cleared. Also clear the browser cookies
4. Create an account in the frontend and wait for the confirmation email
5. Click on the account confirmation link in the email
## Expected result
1. The account gets confirmed and the user is automatically logged in. The site header displays the user's name on top of the account options dropdown, besides the welcome message
2. The user is able to reach the checkout after adding products in the basket.
## Actual result
1. The user's name is missing from the site header.
   ![header-customer-data-missing](https://cloud.githubusercontent.com/assets/783672/15211537/60ef5084-1844-11e6-92a2-375d159e482b.png)
2. After adding a product to the cart in the product page and then clicking on the cart icon and on the "Go to Checkout" button, the "Create Account or Sign In" dialog pops up instead of redirecting to the checkout page.
   ![checkout-after-confirmation](https://cloud.githubusercontent.com/assets/783672/15211633/0f07b44a-1845-11e6-97b7-2c7f293948ec.png)
### Notes:
1. I have also set the "Allow Guest Checkout" option to "No" in the backend;
2. It is possible to open the account options drop down and go the the dashboard for instance, which indicates that the user is logged in. The checkout is not allowed though;
3. I've managed to replicate the problem in both Google Chrome and Firefox;
4. I've investigated the issue and it seems to be caused by the local storage customer data, which gets invalidated at login for example, but not after the account confirmation. I wouldn't bet on it though

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-54121, thanks for posting

**Comment by MomotenkoNatalia** [comment]
Hi @marius-bica , Internal ticket MAGETWO-54121 is closed and delivered to mainline. Please let us know if you still have an issue

**Comment by LucianMihalache** [comment]
How comes this is not solved in 2.3.1?
I am having similar issues...
I am on a fresh install of 2.3.1, I registered, logged, added products to the cart, logged out, cleared all cache (server-side pub, generated, var, client-side, everything), going incognito, missing lots of data. Browsing the site in hoping the data will be added, some (rare) times the data is added, logging out, browser storage is deleted, logging back, data again missing.
![cache bug](https://user-images.githubusercontent.com/48981554/55379736-a103a680-5526-11e9-8584-4e229db47280.png)


When I log out, the storage is filled up... I don't have any more ideas of what to do...
![bug logged out](https://user-images.githubusercontent.com/48981554/55380176-11f78e00-5528-11e9-9078-c14b8502654f.png)


Solved:

The problem was on me.
I was adding a custom section to the customer data.
The problem was in my custom section on method: getSectionData()
I was trying to get the customer session, and it was throwing error.
The error was not logged anywhere.
It just broke the code without any trace...
As I saw in the code, there is no catch anywhere in the section pools, but there might be some catch deep in the code that is not logged.
