### ISSUE TITLE
Updating to 2.0.5 deletes translations

### ISSUE THREAD

**Issue by teokolo** [magento/magento2#4562]
## Steps to reproduce
1. Install Magento 2.0.4.
2. Create and install a language pack as explained in the official documentation.
3. Update to 2.0.5 using web setup wizard
## Expected result
1. Module language files xx_XX.csv kept as in previous version
## Actual result
1. Module language files xx_XX.csv have been deleted
2. My list of missing csv files (italian translation, language package built from crowdin):

vendor/magento/module-widget/i18n/it_IT.csv

vendor/magento/module-checkout/i18n/it_IT.csv

vendor/magento/module-captcha/i18n/it_IT.csv

vendor/magento/module-catalog-import-export/i18n/it_IT.csv

vendor/magento/module-catalog/i18n/it_IT.csv

vendor/magento/module-swatches/i18n/it_IT.csv

vendor/magento/module-advanced-pricing-import-export/i18n/it_IT.csv

vendor/magento/module-newsletter/i18n/it_IT.csv

vendor/magento/module-customer/i18n/it_IT.csv

vendor/magento/module-sales/i18n/it_IT.csv

vendor/magento/module-backend/i18n/it_IT.csv

vendor/magento/module-store/i18n/it_IT.csv

I hope that isn't the expected behaviour.

**Comment by davidalger** [comment]
That would indeed be the expected behavior, but let me explain :) The files you created were not setup in a language pack, but added to _dependencies_ required by composer. When a new version of a dependency (in this case, core modules) are updated, the entire dependency directory is blown away and the new version installed. This is nothing special about Magento, it's how composer works.

What I would suggest is reading the following two pages in detail, and creating your translations in the format of a language pack component which can be installed in the system vs placing the translation files in the individual module dependencies:

http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/xlate.html#m2devgde-xlate-languagepack
http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.html#config-cli-subcommands-xlate-pack

If that doesn't get you to where you need to go, please head over to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) sites for further help.
