### ISSUE TITLE
Wrong backend CSS showing white headlines (browser safari/mac)

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#4593]
There is a wrong css formatting in the backend --> product --> crossellproducts / updsell etc.

The headline is shown white in safari/mac because of the css background: transparent

![2](https://cloud.githubusercontent.com/assets/16196483/15421687/f5a9203e-1e74-11e6-9667-25c8e3cdcb2e.png)
![1](https://cloud.githubusercontent.com/assets/16196483/15421688/f5ccb6e8-1e74-11e6-882a-5dad2de585a4.png)

**Comment by MomotenkoNatalia** [comment]
Hi @andidhouse Which Magento version do you use?

**Comment by MomotenkoNatalia** [comment]
@andidhouse Closing the issue as it cannot be reproduced on current develop branch and there is no response has been received from the reporter.
Please feel free to create new ticket if you feel that issue could be reproduced.

**Comment by andidhouse** [comment]
@MomotenkoNatalia sry for the delay.
Did you really check the issue on Mac/safari with all magento versions including 2.0.7?
The bug definitely exists!

**Comment by vil11** [comment]
I do check this on the latest **develop** branch on Mas OS Safari 9: all the grid headers are displayed correctly. The issue isn't reproducible neither on described page (this page had been already refactored) nor on similar pages like "update Customer" or "update Order".
Please upgrade your Magento version so that the fix is applied.

## 

:sunny: dvilchynskyi, M2 QA

**Comment by andidhouse** [comment]
This can be closed - it has no meaning as you refacturated the complete backend product page as you said. 

By the way: Having no navigation bar (former left side) the product page is very hard to edit as there is no navigation at all 👎
