### ISSUE TITLE
Configurable options are not reflecting at order view page.

### ISSUE THREAD

**Issue by Doability** [magento/magento2#4618]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add Configurable Product to the cart.
3. When you purchase the item either from the backend or frontend at the order view page the  configurable items appears in two lines without any option (which was set during Add to cart.)
## Expected result

1.Configurable product added to the shopping cart should show options which was set during add to cart. 
## Actual result
1. When you purchase the item either from the backend or frontend at the order view page the  configurable items appears in two lines without any option (which was set during Add to cart.)
   ![image](https://cloud.githubusercontent.com/assets/16632176/15454071/ee95565a-204a-11e6-9800-8a299e1980f8.png)

Any help would be appreciated.

Thanks in Advance.

**Comment by Pakkapao** [comment]
This affects the **pdf invoice** as well. If customer purchases the same product with different option/price, it will definitely confuse customer.  I'm currently using Magento 2.0.6.

**Comment by NadiyaS** [comment]
Hi @Doability ,
thank you for reporting this issue. It really exists on 2.0.7 version. But develop branch does not have this bug.
You can upgrade your code from develop branch or wait until next release.
This issue is closed as resolved.
Feel free to reopen it if you have encountered this bug on upgraded version.
