### ISSUE TITLE
Logic failure in module-catalog/Model/Layer/Filter/AbstractFilter.php 

### ISSUE THREAD

**Issue by bgkavinga** [magento/magento2#4639]
In module-catalog/Model/Layer/Filter/AbstractFilter.php::isOptionReducesResults() checks whether the resulting option count is greater than products count. There could be an option that applies to all the products. Since this logic does not check equality, the option that applies to all the products in that category will not be shown.

**Comment by maghamed** [comment]
That's true, for now Magento doesn't show possible attribute values in LN if all the products in the result set have this option(-s). So, Magento shows LN options just in case they lead to narrowing down result set. This is done to prevent possibility of infinite LN clicking.
For example, you have a search request "polo t-shirt" and get 10 t-shirts in the result set.
5 out of 10 shirts have "S" size
10 out of 10 shirts have "M" size
7 out of 10 shirts have "L" size
3 out of 10 shirts have "XL" size

So, Magento generates next LN section for "Size" attribute:
"S" - 5
"L" - 7
"XL" - 3

"M" size not rendered because all the products in result set have one.

Probably it could confuse customer as he/she could think that NON of the products obtain "M" size.
Probably from Usability point of view it's better to generate not clickable "M" size option.

Adding Product Owner of Search Track for resolution @choukalos

**Comment by choukalos** [comment]
@bgkavinga thank you for the input; I'm tracking this improvement as MAGETWO-54219 internally.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Logic-failure-in-module-catalog-Model-Layer-Filter/idi-p/46348).
