### ISSUE TITLE
Broken help links?

### ISSUE THREAD

**Issue by qmarlats** [magento/magento2#4797]
Hey,
At least one help link is broken: in the configuration page (and on some other pages), next to the scope on the top of the page, there is a help link with this link: http://www.magentocommerce.com/knowledge-base/entry/understanding-store-scopes. But the page doesn't exists. I don't know if some others are broken.

**Comment by ghost** [comment]
Thanks for letting us know. This link is supposed to redirect but it obviously is not. We'll get back to you with an update ASAP.

**Comment by ghost** [comment]
Response I received today from the merchant documentation team:

It looks like these are fixed in the RC-1 release. I wasn't able to check CE, but EE is fixed. All of the scope links should go to the following pages:

M2 EE:

http://docs.magento.com/m2/ee/user_guide/configuration/scope.html

M2 CE:

http://docs.magento.com/m2/ce/user_guide/configuration/scope.html

**Comment by qmarlats** [comment]
I think it's fixed now then I close this issue.
