### ISSUE TITLE
Updating Magento 2 wipes grunt configuration

### ISSUE THREAD

**Issue by crantron** [magento/magento2#4823]
Updating Magento 2 wipes grunt configuration

**Comment by pboisvert** [comment]
@crantron can you provide more details in terms of steps to reproduce, which version you were trying to upgrade from and to?

**Comment by hostep** [comment]
@crantron: this will be fixed in Magento 2.1.

They renamed `Gruntfile.js` to `Gruntfile.js.sample` so a Magento upgrade won't overwrite your own `Gruntfile.js` in the future. See this commit: https://github.com/magento/magento2/commit/9ba77d903d173a134ef4c5b1f9de0d3f4d73d47d

Slightly related ticket: https://github.com/magento/magento2/issues/4697

**Comment by crantron** [comment]
@hostep thanks so much. God speed!

**Comment by anton-huz** [comment]
@crantron for list of the themes from now you can use separate file:  
`dev/tools/grunt/configs/themes.loc.js` config file.

See [implementation](https://github.com/magento/magento2/blob/develop/dev/tools/grunt/tools/files-router.js#L64-L71) for more details.

Thanks for report, ideas and insights.
