### ISSUE TITLE
Meta Description automatically filled with HTML

### ISSUE THREAD

**Issue by jsakars** [magento/magento2#4861]
## Steps to reproduce
1. Install Magento from `2.0` branch.
2. Edit product that has description with HTML content in it (e.g. `<ul>`)
## Expected result
1. Product is shown on front-end as is
## Actual result
1. Product is show on front-end
2. Meta description is breaking the page as it outputs HTML and breaks the tag.

It seems that meta description is automatically filled with product title + plain product description if it's empty when editing product.

**Comment by pboisvert** [comment]
@antboiko think this may be yours (or possibly Olena). Does M1 have the same behavior of grabbing description for meta description and if so does it strip HTML out of description on use? If so then not parity. If not, then this would be improvement and should be documented.

**Comment by antboiko** [comment]
Hello @werdlv , thanks for your inquiry.

Here you can find all information about [Default Field Values](http://docs.magento.com/m2/ce/user_guide/catalog/product-fields-autogenerated.html) including Mask for Meta Description.

Regarding Meta Description doesn't strip HTML tags and breaks layout, the fix for this issue is already in develop branch and will be also available in one of future patches.

I'm closing the ticket. Please feel free to reopen if you have additional questions.

Best,
Anton.
