### ISSUE TITLE
catalog_product_index_price after migration is not populated

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#4898]
## Steps to reproduce
1. Migrate data from magento 1
## Expected result
1. All products from magento 1 should be visible in magento 2 FE
## Actual result
1. catalog_product_index_price table is not populated even after reindex. This causes a bug where none of the products are viewable in frontend, but categories and category filter in search are present.
2. After opening product in BE and saving it without changes it stores values in catalog_product_index_price table and product becomes visible in frontend.

The only way to populate table is to open each product individually and save it without changes.

**Comment by kandrejevs** [comment]
After manually deleting all entries in `indexer_state` table, Indexer finally performed full reindex and populated `catalog_product_index_price` table.

**Comment by victor-v-rad** [comment]
Hi @kandrejevs 
It is good you have managed to find the solution. But anyway we will investigate the cause of the issue withing internal ticket MAGETWO-54114
Thanks

**Comment by southerncomputer** [comment]
If you log sql queries you will randomly (2.10-rc3) see that "The table is full" mysql error on the _temp table being made. 

I moved mysql /tmp from /tmp to /var/lib/mysql/tmp to avoid memory starvation but i'm not sure if it fixed it or if the restart of mysqld free'd up ram resources!

The only way to log this error due to the indexer running under cron.php is to enable full sql logging from Quiet in di.xml ! It doesn't seem the indexer logs mysql errors anywhere useful!

**Comment by larsroettig** [comment]
Hi, 
i can reproduce this issue.  The main problem is if the temp table size too small than will

**$productResource->commit();** throw an exception temp table is full. But this error is not in log because from **$productResource->rollBack()** will over writen with an
 **Asymmetric transaction rollback**  beause **commit** set the transactionLevel  to  **0**.

Plugin with the Problem:
https://github.com/magento/magento2/blob/53072e0f34af7025950d88c2659e6837b938dbf2/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext/Plugin/Product.php#L55

##Soltions

Create  custom.cnf follwing configs:
[mysqld]
tmp_table_size=512M
max_heap_table_size=512M

**Comment by magento-engcom-team** [comment]
Hi @kandrejevs
Please consider creating migration related issues for https://github.com/magento/data-migration-tool project.
Thank you
