### ISSUE TITLE
Admin permissions error when trying to save WYSIWYG content

### ISSUE THREAD

**Issue by mstumpf818** [magento/magento2#4920]
## Steps to reproduce
1. Install Magento 2.0.6
2. Sign into the admin panel as a user with full permissions
3. Go to Content > Pages and select "edit" for a page
4. Go to the "Content" tab and enter this text in the editor: `from time-to-time (collectively, "Conditions")`
## Expected result
1. The WYSIWYG properly encodes/converts any special characters so that content is able to be saved
## Actual result
1. When you hit "Save" you get the following error at this url: /staginga_admin/cms/page/save/active_tab/content_section/

`Forbidden  You don't have permission to access /staginga_admin/cms/page/save/active_tab/content_section/ on this server.`

<img width="1278" alt="screen shot 2016-06-07 at 16 48 28" src="https://cloud.githubusercontent.com/assets/11161484/15874202/120b342e-2cd0-11e6-990f-23bc6830f57e.png">
<img width="737" alt="screen shot 2016-06-07 at 16 49 24" src="https://cloud.githubusercontent.com/assets/11161484/15874201/12095cee-2cd0-11e6-8b74-e12fbf7addcd.png">

**Comment by mstumpf818** [comment]
@mslabko UPDATE: I've found that certain characters are not being properly html encoded and are setting off the alert.  If I disable the WYSIWYG editor and manually replace the characters with the HTML equivalent, then I am able to save successfully

( === &#40;
) === &#41;
+ === &#43;

**Comment by shiftedreality** [comment]
Hi @mstumpf818 

I've created internal ticket MAGETWO-54356 to investigate this issue.
Please also provide your system configuration such us PHP version, OS version, etc.

**Comment by adifucan** [comment]
Hi @mstumpf818 I double checked your issue on our end I could not reproduce it. I checked it on Magento 2.0.6 CE & also on Magento 2.0.6. EE

Page is saved correctly with following content `from time-to-time (collectively, "Conditions")` as you can see on screen shot attached below.

Issue was test on following environment:
PHP 5.6.15
Apache 2.4.10
MySQL 5.6.25
Firefox 46.0.1 & Chrome Version 51.0.2704.84 m
Linux 3.2.0-4-amd64 x86_64

More likely this issue is connected with wrong host or permission settings but not with WYSIWYG. Please refer to Magento 2 Developer Documentation: 
- http://devdocs.magento.com/guides/v2.0/install-gde/install-quick-ref.html
- http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-sys-perms-over.html

Please, let me know if you still have this issue on your end. If so, please provide more details including your environment versions, /var/log files, console errors etc.

![admin_permissions_error_when_trying_to_save_wysiwyg_content](https://cloud.githubusercontent.com/assets/6827593/16126587/77ad126a-3401-11e6-9bc5-21d0213d4aeb.jpg)

**Comment by shiftedreality** [comment]
No answer from the author was received for 8 days.
Closed.

**Comment by sma09sjb** [comment]
Was this ever resolved, i am experiencing this issue on our independent server environment? When i setup the site locally i can't replicate the issue.

Can you be more specific about the permissions i need to set to ensure this doesn't happen? I have a site running CE 2.1 in production mode.

Thanks,

Sophie

**Comment by mstumpf818** [comment]
@shiftedreality @sma09sjb no this issue was never resolved but funding for the project ran out and so development efforts stopped

**Comment by sma09sjb** [comment]
So is this an acknowledged Magento bug?

I'm not aware of how your processes work internally as far as bug fixing and funding goes, but i would expect a bug like this to be high up in terms of priority. It's directly impacting on the usability of the site, and has far reaching implications in terms of data population. Currently we're not able to complete product data entry because of this bug, and that could set back our launch date.

Do you have any suggestions that may help me investigate the root cause of this myself? Can you confirm if it's to do with server permissions? 

It's imperative for our client that this is resolved as soon as possible.

**Comment by pboisvert** [comment]
@sma09sjb Pulling acknowledged label as the internal ticket shows this is as closed can't reproduce. When we reproduce issues they get the label "acknowledged" to indicate we are aware and have the issue in our backlog.

If you are encountering you can reopen the issue but we will need complete info to be able to reproduce the issue.

**Comment by sma09sjb** [comment]
https://github.com/magento/magento2/issues/6067 -- i've created a new ticket for this issue.

I'm running Magento 2.1 CE, on a Nexus server environment. We're not experiencing this issue locally, only on the server, which indicated to me there must be an issue with either server permissions or Magento configuration. 

We've been having a number of issues switching the mode successfully to production mode on the server (https://github.com/magento/magento2/issues/6185), so the site is currently running in development mode. 

I've given full 777 recursive permissions to the pub and var folders, are you able to confirm this is correct?

Thanks.

Sophie

**Comment by tanghia** [comment]
Me too! 

I have one production website and two demo websites. All of them got this issue when save a complex HTML content from editor. (it works well for simple content )
![image](https://cloud.githubusercontent.com/assets/7329746/18167077/d353d8de-7078-11e6-9e5c-609e9fbda0b8.png)

**Comment by tanghia** [comment]
Oh, i detected that if your html content contains special characters like: %20 (space), You can't save...This issue must be fixed.
