### ISSUE TITLE
No way to add Group Prices?

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#4934]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add product
3. Try adding a group price ....
## Expected result
1. on the tab advanced pricing a Group price section should be present
## Actual result
1. There is no groupo price section on the advanced pricing tab
2. Screenshot of user guide: 

![2016-06-09_09h38_10](https://cloud.githubusercontent.com/assets/13572447/15922137/7f1e0dd2-2e26-11e6-9d58-49f53ec15494.png)

**Comment by SidneyBilliet** [comment]
2.0.7 backend screenshot:
![2016-06-09_09h40_31](https://cloud.githubusercontent.com/assets/13572447/15922194/d34da9d0-2e26-11e6-9e32-363272c0a86a.png)

**Comment by orlangur** [comment]
There is no Group Price attribute [since version 2.0.1](https://github.com/magento/magento2/blame/2.0/app/code/Magento/Catalog/Setup/UpgradeData.php#L73), it was an excessive concept.

You can use tier price with Qty = 1 instead.

This fact does not seem to be reflected in Admin UI and/or user guide though.

**Comment by bijalbhavsar** [comment]
I also having same issue, we have verified this feature in Magento CE 2.0.7 but it is specified in Magento user guide for Magento Community Edition, 2.1 - http://docs.magento.com/m2/ce/user_guide/catalog/settings-advanced-advanced-pricing.html.

It is not showing in Magento CE 2.1 version also.

**Comment by ArthurTransoftgroup** [comment]
Hello @SidneyBilliet , thank you for being Attentive! In new versions, there is a little bit different look for the buttons and some texts, please look at my screenshot for more details: 
![untitled](https://user-images.githubusercontent.com/27813956/27542102-e1c67056-5a8e-11e7-9db5-ddb69f617346.png)

**Comment by orlangur** [comment]
@ArthurTransoftgroup, `Customer Group Price` field on your screenshot seems to be tier price in fact due to Quantity column. In my 2.1.x instance there are only Special Price, Cost and Tier Price fields in this form.

@veloraven this is not a bug by the way as I explained in earlier comment. The only thing which needs to be fixed is documentation.

**Comment by tkacheva** [comment]
Please refer to the user guide http://docs.magento.com/m2/ee/user_guide/catalog/product-price-group.html
