### ISSUE TITLE
On editing a Bundle product from shopping cart the user defined quantities of the options are overwritten

### ISSUE THREAD

**Issue by densen45** [magento/magento2#4942]
## Steps to reproduce
1. Install Magento CE 2.0.6
2. Create a Bundle product with at least one option of type radio and enable user defined quantity
3. Add more then one product to the option and enable user defined quantity
4. Open the Bundle product on frontend
5. Change the quantity of an option
6. Add the Bundle product to the shopping cart
7. Go to the shopping cart
8. Press the "Edit" button in order to edit the Bundle product
## Expected result
1. The quantity of the option should be the user defined one
## Actual result
1. The quantity of the option is not the user defined one. It is the selections' default quantity.
## Debugging until now
1. On page load the quantity is the user defined one (see variable `$_defaultQty` in `radio.phtml`).
2. Then the `value` (property, not the attribute) of the input field is changed through Javascript
3. Don't know were this happens exactly but for sure the `_onBundleOptionChanged(event)` of the `price-bundle.js` is involved.

**Comment by RomanKrut** [comment]
Internal ticket was created for this issue - MAGETWO-69959

**Comment by magento-engcom-team** [comment]
@densen45, thank you for your report.
We've created internal ticket(s) MAGETWO-69959 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@densen45, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @densen45. Thank you for your report. 
The issue has been fixed in magento/magento2#15905 by @JosephMaxwell in 2.2-develop branch
Related commit(s):
 - [c05ac4c243810a7d94517a82680e29cc6371c33b](https://github.com/magento/magento2/commit/c05ac4c243810a7d94517a82680e29cc6371c33b)
 - [076bb60450be1aab2f89b379c68bd7f311819a50](https://github.com/magento/magento2/commit/076bb60450be1aab2f89b379c68bd7f311819a50)
 - [e35a9b1de6bbc961d3bc3acbbd31ca288c893ee5](https://github.com/magento/magento2/commit/e35a9b1de6bbc961d3bc3acbbd31ca288c893ee5)

The fix will be available with the upcoming 2.2.8 release.

**Comment by sidolov** [comment]
Hi @densen45. Thank you for your report. 
The issue has been fixed in magento/magento2#18520 by @gelanivishal in 2.3-develop branch
Related commit(s):
 - [e210b7044a7bfd503082249a72a95a6c0ae03eb5](https://github.com/magento/magento2/commit/e210b7044a7bfd503082249a72a95a6c0ae03eb5)
 - [53f59424c0b049e2f275c50bbced1fc9b42a6916](https://github.com/magento/magento2/commit/53f59424c0b049e2f275c50bbced1fc9b42a6916)
 - [8050d5014037c9ae845be1fd1338b4f4ce7b8d19](https://github.com/magento/magento2/commit/8050d5014037c9ae845be1fd1338b4f4ce7b8d19)
 - [0bd75c823e506e8099cfa4dbb5877be5662bcebb](https://github.com/magento/magento2/commit/0bd75c823e506e8099cfa4dbb5877be5662bcebb)

The fix will be available with the upcoming 2.3.1 release.
