### ISSUE TITLE
Filter country drop down for estimate shipping on cart page

### ISSUE THREAD

**Issue by exnite** [magento/magento2#4973]
## Steps to reproduce
1. Log into Admin, go to Store > Configurations > Sales > Shipping Methods
2. In UPS, Select "Specific Countries" under Ship to Applicable Countries
3. Pick United States and Canada under Ship to Specific Countries
4. Clear cache
5. Add a product to cart
6. Go to Shopping Cart, 
7. Under Estimate Shipping and Tax, the Country drop down lists all countries
## Expected result
1. Estimate Shipping and Tax to filter Country drop down.
   (This list shows United States and Canada in the country drop down on Checkout page)
## Actual result
1. the Country drop down lists all countries

**Comment by exnite** [comment]
The code is in Magento\Checkout\Block\Cart\LayoutProcessor line 88 and 95.

``` php
public function process($jsLayout)
    {
        $elements = [
            'city' => [
                'visible' => $this->isCityActive(),
                'formElement' => 'input',
                'label' => __('City'),
                'value' =>  null
            ],
            'country_id' => [
                'visible' => true,
                'formElement' => 'select',
                'label' => __('Country'),
                'options' => $this->countryCollection->load()->toOptionArray(),
                'value' => null
            ],
            'region_id' => [
                'visible' => true,
                'formElement' => 'select',
                'label' => __('State/Province'),
                'options' => $this->regionCollection->load()->toOptionArray(),
                'value' => null
            ],
            'postcode' => [
                'visible' => true,
                'formElement' => 'input',
                'label' => __('Zip/Postal Code'),
                'value' => null
            ]
        ];

        if (isset($jsLayout['components']['block-summary']['children']['block-shipping']['children']
            ['address-fieldsets']['children'])
        ) {
            $fieldSetPointer = &$jsLayout['components']['block-summary']['children']['block-shipping']
            ['children']['address-fieldsets']['children'];
            $fieldSetPointer = $this->merger->merge($elements, 'checkoutProvider', 'shippingAddress', $fieldSetPointer);
        }
        return $jsLayout;
    }
```

**Comment by YevSent** [comment]
@exnite current behaviour is correct. The `Ship to Applicable Countries` option allows to specify the list of countries where this shipping method will be available, but it doesn't filter countries in the dropdown because you can configure more than one shipping method.
If your change shipping country different to Canada or USA in your case UPS should not be available.

**Comment by U12358** [comment]
Problem in 
'options' => $this->countryCollection->load()->toOptionArray(),

must be
'options' => $this->countryCollection->loadByStore()->toOptionArray(),

![t297](https://cloud.githubusercontent.com/assets/813985/15988284/1dc78854-3053-11e6-9f9f-412e056d68f9.png)

**Comment by asemenenko** [comment]
Hi @exnite described behavior is correct, example will be say having UPS configured for US and Canada and Australia Post for AU and NZ only. During checkout you will have to see all the countries that you want to ship items to since country needs to be selected before getting shipping rates. What you are referring to is a need to limit a list of countries available to be selected, one of the options is to merge an array with both UPS [US, CA] and Australia Post [AU, NZ] to [US, CA, AU, NZ] which is questionable solution since it is not quit obvious to the merchant due to lack single list. That is why we have a setting that controls available countries under General, General, Countries Options, Allow Countries

**Comment by exnite** [comment]
Thank you for all your answers, I understand that if there are two carriers, you would have to merge the two, but it should only list US, Canada, AU and NZ, instead of all countries.
if I select UPS and with "Specific Countries", which means I'm only shipping to US and Canada, therefore, listing all countries seems unnecessary.  It's also inconsistent with the checkout, which only lists US and Canada, so it would appear that checkout is using the correct behavior while the cart is not.  

![image](https://cloud.githubusercontent.com/assets/19860626/16013567/cbc3f88a-3142-11e6-8483-48223cc20b13.png)

Correctly filtered at checkout:
![image](https://cloud.githubusercontent.com/assets/19860626/16013530/a6fd010e-3142-11e6-84bc-49dcc805aef0.png)

**Comment by exnite** [comment]
@SKovbel suggestion seems to solve the issue.  It does let me pick which country to display once I select the countries under General, General, Countries Options, Allow Countries.  :) Please sneak this tiny change into your next patch.
