### ISSUE TITLE
Customer Updated Time not changing when updating address data from front end using REST Api

### ISSUE THREAD

**Issue by arijit-de93** [magento/magento2#5013]
## Steps to reproduce
1. Install Magento.
2. Login to Magento frontend.
3. Go to My Account and in the Address section update your address.
4. Pull that customer using REST Api.
## Expected result
1. updated_at time should change.
## Actual result
1. updated_at time not changing.

**Comment by mbrinton01** [comment]
@arijit-insync what do you expect to see the updatedAt time reflect? The time the address was changed in the front end, or the time the API call is made? Are you using GET /V1/customers/{customerId}?

**Comment by arijit-de93** [comment]
The time the address was changed in the frontend. Yes, I am using your API call

**Comment by mbrinton01** [comment]
Address is stored separately from the customer record, so a change to the address only will not modify `updatedAt` for the customer record. To do this we would have to modify the API to update the customer record in the database when the address is changed.  Please confirm this is your intention.  If so, I will record this as a feature request for APIs.

**Comment by arijit-de93** [comment]
Thanks for understanding the issue. I personally feel it is not a concern of a consumer on how data is stored in backend. An API should be full proof to handle any customer scenario for a website.

Lets take a scenario 
1. Customer 1  is updated in server. 
2. I am calling **/V1/customers/search** with a search criteria based on the update time. 
3. The data returned does not contain the customer which is updated to the server. 

[Provided : You are sending address data with the customer] 

I don't see this as a feature, if customer does not contain address related information, then it would have been, but in our case the API is sending some wrong data and there is no alternative way to search through address field.

If you think this as a feature, can you please provide me an alternative solution to this ? 

My intention is to get all customer data that has been updated in server after a particular time. 
Thanks

**Comment by srinivasanithin** [comment]
@mbrinton01 I agree with @arijit-insync . I too didn't find a way to pull customers address which updated after a particular time nor I think we can run joins in API searches. There needs a way to pull that customer any particular updated happen on them.

Addresses records are linked to particular customer record and there are not part of any other records. Hence, I think any update happening on them should be reflected on customer record Hence, updatedAt field value needs to be updated with any update any customer address field or customer fields.

**Comment by mbrinton01** [comment]
@misha-kotov please capture this request in MAGETWO

**Comment by magento-engcom-team** [comment]
@arijit-insync, thank you for your report.
We've created internal ticket(s) MAGETWO-82433 to track progress on the issue.

**Comment by arijit-de93** [comment]
Hi Team,

What is the status of this issue?

**Comment by marcejohnson** [comment]
+1  Any update?  We are also encountering this issue, which impacts accurate syncs and integrations.  Very important to resolve.  In summary, upon edit of existing `address`, associated `customer` should be "touched" (`last_updated` updated on `customer`).  Also, is there a workaround?  We are using REST API for all interactions, as described above.  Thanks!

**Comment by arijit-de93** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@arijit-de thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by rddwh** [comment]
Any update on this issue?

**Comment by manishmittalm** [comment]
I would be willing to take on this issue! #SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
@manishmittalm thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @manishmittalm. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by dmitrijivanenko** [comment]
#mageconf

**Comment by magento-engcom-team** [comment]
@dmitrijivanenko thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @dmitrijivanenko. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
