### ISSUE TITLE
Report error csv doesn't work when trying to import a csv file with semicolon delimiter

### ISSUE THREAD

**Issue by agoeurysky** [magento/magento2#5015]
## Steps to reproduce (Magento 2.1-rc3)
1. Try to import a catalog_product.csv file in admin interface which contains an error.
2. Configure the semicolon `;` for row delimiter.
3. Click `Check data` button, the file is valid for import.
4. Click `Import` button.
## Expected result
1. Import is stopped and all errors are printed.
2. We can download the report error csv file.
## Actual result
1. Import is stopped but only `General system exception happened` is printed.
2. We cannot download the report error csv file because the link doesn't appear.
## Note

The same workflow works with a catalog_product.csv file with the `,` row delimiter, because this is the default Magento delimiter for a csv source.
See `\Magento\ImportExport\Model\Report\Csv::createSourceCsvModel`.

**Comment by veloraven** [comment]
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by agoeurysky** [comment]
@veloraven The problem still appears with the latest version 2.1-rc3.

**Comment by BaDos** [comment]
Hi @agoeurysky 

Thank you for reporting.
The internal ticket MAGETWO-58382 was created to resolve this issue.

**Comment by magento-engcom-team** [comment]
@agoeurysky, thank you for your report.
We've created internal ticket(s) MAGETWO-58382 to track progress on the issue.

**Comment by okorshenko** [comment]
The issue has been fixed and delivered to 2.2-develop branch. Will be available with 2.2.2 release

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-82956

**Comment by magento-engcom-team** [comment]
Hi @agoeurysky. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1285 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - ad6c0af7dddbe2855a336acd3fd55994851e6d26
 - 6d3d70a72f08cba36c3aef6b59eea8db40eb4071
 - 6b0c02c5fd00d7a4237c4e1fae40dc265e3e43c3
 - c8abb139f8006826989fe4231dabc21fd4a02fd0
 - c6a9b5f7b13554958b547f387637c4288eb60b0b
 - c867b81af936e01a3d8ba8baa7128de06a5b7cd5
 - 88a3ad00d3ca97da847531c86bf64055dc1d790b
 - d87e316a2d6ee55debe2e712359adba8cb70fdb2
 - c76b04c9acde117c1021270500c8ded6954f6f05
 - 5ae21099aaa19699525c798f9ac0ef10db47b311
 - 931133abf574f1db96450f11f5980ef359d32967
 - 4c927a0585f11921c5e422b7e4a15b787e6338bd
 - 060a8f9f2b08ed97b31667eb76cace1dc0e642be
 - 4da2a7d2657b0da67f8be43bffc85f04b5b7144e
 - 008ef5583892d73c04628f003a2ce3d97fe0ed72
 - d3642e88d26a9240a1a4d648d37d984a785672a9
 - d37ce089d56c230f5896d5d7e922bd928b3726e6
 - b22b232563359f9cbcbf09709e63a87be7e81446
 - 6c02a2d3a272e872d549881d91ed6d5235a33f77
 - f2ec2ea175469636acec0bf9f65f0601854f89a2

The fix will be available with the upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @agoeurysky. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1203 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [7c03614c09fe85893e5ab8f4d78bd9bb5880af56](https://github.com/magento/magento2/commit/7c03614c09fe85893e5ab8f4d78bd9bb5880af56)

The fix will be available with the upcoming 2.3.0 release.
