### ISSUE TITLE
Structured Data - Price  property not recognized

### ISSUE THREAD

**Issue by devhn** [magento/magento2#5022]
## Steps to reproduce
1. Install Magento 2.0.7 from `community` branch.
2. Open any product page and copy it's URL to [Google Structured Data testing tool](https://goo.gl/pYUUjG)
## Expected result
1. Price property should be recognized.
## Actual result
1. Price property is not valid (the property XXX € is not a valid price specification).

[Screenshoot for reference](http://i.imgur.com/hxuobq2.png)

**Comment by antboiko** [comment]
Hi @devhn , thanks for pointing on this. 

I checked guidelines on https://schema.org/price and there were some changes:
Use the priceCurrency property (with ISO 4217 codes e.g. "USD") instead of including ambiguous symbols such as '$' in the value. 

I've created internal ticket MAGETWO-54430 for this improvement and added it to the product backlog.

Thanks,
Anton.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Structured-Data-Price-property-not-recognized/idi-p/46878).
