### ISSUE TITLE
Datetime Error on Newsletter Template

### ISSUE THREAD

**Issue by davideperrotta** [magento/magento2#5037]
## Steps to reproduce
1. Go to Admin->Marketing->Newsletter Template
2. Select "Queue Newsletter" from right dropdown
3. Select a "Queue Date Start" and try to save it
## Expected result
1. Saved
## Actual result
1. DateTime::__construct(): Failed to parse time string (29/giu/2016 01:22:19) at position 0 (2): Unexpected character
## Temporary Solution

Insert data manually before hour in this way:
2016/06/29

this problem maybe doesn't affect who uses this data format yet

**Comment by PierAlex** [comment]
Same problem on Magento 2.1.0.

**Comment by antboiko** [comment]
Hi @davideperrotta , thanks for reporting this issue. Internal ticket MAGETWO-57643 was created.

Best,
Anton.

**Comment by LuisChaves** [comment]
Already have a definitive solution on this issue? I'm using Magento 2.1.7 and the error continues.

**Comment by magento-engcom-team** [comment]
@davideperrotta, thank you for your report.
We've created internal ticket(s) MAGETWO-57643 to track progress on the issue.

**Comment by RomanMichak** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@RomanMichak thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by RomanMichak** [comment]
Issue detected in DateTime construct when input date on it_CH localization include "giu" month name. A good solution would be to change the used date format from IntlDateFormatter::MEDIUM to IntlDateFormatter::SHORT, as in other forms in admin it used SHORT format anyway.
But that solution caused another issue, which connected to different datetime format set in /Magento/Newsletter/Block/Adminhtml/Queue/Edit/Form.php and datepicker from a template.
So I decide to rewrite that Edit/Form block to ui component as it is for other admin edit forms.
It is in progress now, and PR will be created later.

**Comment by marco7319** [comment]
same problem with magento 223

**Comment by mrkhoa99** [comment]
@RomanMichak can I work on this issue or you are still working on it?

**Comment by RomanMichak** [comment]
@mrkhoa99 yes, sure, you can assign ticket to yourself and work on it

**Comment by patelnimesh1988** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@patelnimesh1988 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by patelnimesh1988** [comment]
I am working on this issue

**Comment by patelnimesh1988** [comment]
Fixed issue. Please check it out here: https://github.com/magento/magento2/pull/15783

**Comment by patelnimesh1988** [comment]
I am working on this issue

**Comment by rodrigowebjump** [comment]
@patelnimesh1988 How is the progress on this issue?

**Comment by sidolov** [comment]
Hi @davideperrotta. Thank you for your report. 
The issue has been fixed in magento/magento2#18083 by @bnymn in 2.3-develop branch
Related commit(s):
 - [ae42612217947d75aa09b300a34e23487b8954c3](https://github.com/magento/magento2/commit/ae42612217947d75aa09b300a34e23487b8954c3)
 - [c4fa85bb59e9006f12fa79854da78af4e3fd601e](https://github.com/magento/magento2/commit/c4fa85bb59e9006f12fa79854da78af4e3fd601e)
 - [6bda779e40699ae1e4b16920374cfd398dea28a8](https://github.com/magento/magento2/commit/6bda779e40699ae1e4b16920374cfd398dea28a8)
 - [a4f80a9d93c455328a08718b1c7319fde0dfc32f](https://github.com/magento/magento2/commit/a4f80a9d93c455328a08718b1c7319fde0dfc32f)
 - [14d9528852bd30b6f7545b3a22ac2d555a196543](https://github.com/magento/magento2/commit/14d9528852bd30b6f7545b3a22ac2d555a196543)
 - [da580fc75a0dd854ca60b4c7278c54e7c98cf935](https://github.com/magento/magento2/commit/da580fc75a0dd854ca60b4c7278c54e7c98cf935)
 - [16a7f0babc8cfd4420dfea32c35449745449791b](https://github.com/magento/magento2/commit/16a7f0babc8cfd4420dfea32c35449745449791b)
 - [9315dd6963834ec6299eed8395add8bdb7bb7895](https://github.com/magento/magento2/commit/9315dd6963834ec6299eed8395add8bdb7bb7895)
 - [42cd2282007b0fc191413f8d483c58c6729823fc](https://github.com/magento/magento2/commit/42cd2282007b0fc191413f8d483c58c6729823fc)
 - [ddeaf36c942f17f720cc720c840aeb844e93efbf](https://github.com/magento/magento2/commit/ddeaf36c942f17f720cc720c840aeb844e93efbf)
 - [6cc903442a668370898ee352871510f48a72bc21](https://github.com/magento/magento2/commit/6cc903442a668370898ee352871510f48a72bc21)
 - [28617c01e62941eaa68df8b6ea72a958c6f5367c](https://github.com/magento/magento2/commit/28617c01e62941eaa68df8b6ea72a958c6f5367c)
 - [fd0ab037a74cc5d78d02c603adbd5cf10cb92c88](https://github.com/magento/magento2/commit/fd0ab037a74cc5d78d02c603adbd5cf10cb92c88)
 - [1b03c19021957d85e625eeb5bb61cd3921b31937](https://github.com/magento/magento2/commit/1b03c19021957d85e625eeb5bb61cd3921b31937)
 - [c6c2ffe214f45366e81e3644b7ddadb2b2fce383](https://github.com/magento/magento2/commit/c6c2ffe214f45366e81e3644b7ddadb2b2fce383)
 - [502e5ac6941a10e39ef1e559c91565bdb07a4d14](https://github.com/magento/magento2/commit/502e5ac6941a10e39ef1e559c91565bdb07a4d14)
 - [51e8fe7118e6734e3ee250483d9877eda2d1388a](https://github.com/magento/magento2/commit/51e8fe7118e6734e3ee250483d9877eda2d1388a)
 - [a8c77686312a61ab151eb4c9a7a79a5f8127b3dd](https://github.com/magento/magento2/commit/a8c77686312a61ab151eb4c9a7a79a5f8127b3dd)
 - [127b1b8029a52fca7ad9726380f55c99c9db4c8a](https://github.com/magento/magento2/commit/127b1b8029a52fca7ad9726380f55c99c9db4c8a)
 - [526bfc9267c837ef8b9bf7234869cf16d4327a26](https://github.com/magento/magento2/commit/526bfc9267c837ef8b9bf7234869cf16d4327a26)
 - [edc962dbf324a3866f9ac78537ce23abfc1316e4](https://github.com/magento/magento2/commit/edc962dbf324a3866f9ac78537ce23abfc1316e4)
 - [4fe8c7a3ccc100d23f170dcef994477227aed35e](https://github.com/magento/magento2/commit/4fe8c7a3ccc100d23f170dcef994477227aed35e)
 - [e27de555edbbc24ff8a7037ee57de4deea306472](https://github.com/magento/magento2/commit/e27de555edbbc24ff8a7037ee57de4deea306472)
 - [0d0c210a7e081086a8235f9777a219601bd7e8c4](https://github.com/magento/magento2/commit/0d0c210a7e081086a8235f9777a219601bd7e8c4)

The fix will be available with the upcoming 2.3.1 release.
