### ISSUE TITLE
Export --> Import products proces

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#5047]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add attribute "alcohol percentage" (dropdowns with value's LIKE 70%, 40% etc)
3. Add attribute "content" (dropdowns with value's LIKE 70cl, 40cl, 35cl/50cl/100cl, 25cl etc)
4. Add products and set the attrubtes to any value
5. Export products
6. do not open the file but save it
7. try re-importing the file
## Expected result
1. A file exported should be able to be imported "as is". 
2. If I can add any type values to dropdown attributes, how come this cannot be re-imported as is??
## Actual result
1. Error message appears: "Value for alcohol percentage attribute contains incorrect value, see acceptable values ...."
2. Error message appears: "Value for content attribute contains incorrect value, see acceptable values ...."
3. I keep getting errors because of the content of the "additional_attributes" column in the file
4. screenshot

![2016-06-15_17h12_16](https://cloud.githubusercontent.com/assets/13572447/16085932/11b3afca-331e-11e6-954c-db9aa2d94bac.png)
1. export/import file

[catalog_product_20160615_144636.zip](https://github.com/magento/magento2/files/316463/catalog_product_20160615_144636.zip)

**Comment by duhon** [comment]
Hello @SidneyBilliet 

Can't reproduce on the latest version, please clarify your version

**Comment by SidneyBilliet** [comment]
@duhon Hello, we are running 2.0.7

**Comment by duhon** [comment]
In version 2.1 the problem is already fixed, please wait for a stable version. If you have more questions re-open this issue

**Comment by loomdecor** [comment]
I couldn't agree more.  It's ridiculous.  The data exported does not match how you are supposed to import it.  So if you are trying to manage a large catalog it is virtually impossible to use your import / export functionality.  In addition, I found that some columns do not even export the right data.  For example, Categories column exported that my products were ONLY in the highest level parent category and NONE of the child categories.  If I want to update this data and add products to new categories, I can't do that as I don't have an export that reflects all the categories a product is ALREADY in.  So I would have to manage this Categories field perfectly in Excel and NEVER change the backend through the admin.  So that if I want to change it, I know what categories the product is already in.
