### ISSUE TITLE
Issue with setting fields in payload for POST "/v1/invoices" api

### ISSUE THREAD

**Issue by ruby10** [magento/magento2#5065]
Hi there, 
I have a query regarding following Magento2 API 
POST "V1/invoices" 
with payload 
{
        "entity": {
            "base_discount_tax_compensation_amount": null,
            "base_shipping_discount_tax_compensation_amnt": null,
            "discount_tax_compensation_amount": null,
            "order_id": 58,
            "shipping_discount_tax_compensation_amount": 0,
            "total_qty": 2,
            "grand_total": 155,
            "subtotal": 150,
            "items": [
            {
                "base_discount_tax_compensation_amount": null,
                "discount_tax_compensation_amount": null,
                "order_item_id": 74,
                "sku": null,
                "qty": 56,
                "row_total": 150,
                "tax_amount": 152,
                "discount_amount": 23,
                "price": 154
    }
  ]
}
}

Please clarify following points
a)  Am I supposed to set fields "grand_total", "subtotal" on body level?
b)  Fields "qty", "row_total", "tax_amount", "discount_amount" inside items array?
These fields are visible on invoice created on Magento2.
Attaching screenshot on created invoice below:
![ab](https://cloud.githubusercontent.com/assets/12557241/16132067/4c23fc98-342f-11e6-946a-ee9b4d5dce0f.PNG)

OR mentioning "order_id" and "order_item_id" should be enough??
OR there is some other way , Please do provide info .

**Comment by pboisvert** [comment]
@ruby10 this is a question best direct to the Magento stack exchange account or the Community forums.  Github is intended solely for reporting issues.

**Comment by srinivasanithin** [comment]
@pboisvert It should be Magento responsibility to bring the rate and amount based on the qty and item_id field passed in the API while creating the invoice. It should not be expecting these field values from the API user to give it. These can lead to many critical issue like variances in amount capture/invoiced and this can mess up many financial details. Can you review once again it as issue rather than question. 

As a API user, I am expected to pass Magento API with orderId, Items object array with order_item_id and qty, shipping cost ( again validation where this cost should be less then order shipping cost )

Thanks,
