### ISSUE TITLE
Custom option values do not save correctly

### ISSUE THREAD

**Issue by samtay** [magento/magento2#5067]
Certain permutations of product custom options are impossible to save. For example, 
1. First save a product with a custom option dropdown of two values with differing fields:
   ![2016-06-16-191853_1331x521_scrot](https://cloud.githubusercontent.com/assets/7246591/16136423/3f48cd00-33f8-11e6-9c17-1d03f569e40c.png)
2. Now try to save the second value to be identical to the first, like so: 
   ![2016-06-16-193922_1344x530_scrot](https://cloud.githubusercontent.com/assets/7246591/16136611/14bda05e-33fa-11e6-8d3f-c1830be55bb2.png)
3. Notice that many of the values are not saved correctly. For me, this time around only the SKU was problematic, but you will have problems saving any number of these fields.

This is because
- the abstract resource model generates the `UPDATE` query based on differences between the new data array being saved and the preexisting `$object->storedData` array. [code reference](https://github.com/magento/magento2/blob/3561b6614eeafb70cbcbf0dc0254359b857af3d4/lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php#L718-L733)
- the OptionValue model loops through `setData` commands to save multiple OptionValue instances, hence `storedData` property refers to the **previously saved** Value instance, which is set during the previous `setData()->..->save() iteration`. [code reference](https://github.com/magento/magento2/blob/3561b6614eeafb70cbcbf0dc0254359b857af3d4/app/code/Magento/Catalog/Model/Product/Option/Value.php#L191-L215)

So, those two reasons result in any identical OptionValue fields _not_ able to be saved consecutively, causing the bug shown in steps 1-3.

I think it is rather odd/lazy that the option value model does not have its own resource model.. it seems like a poor idea to just loop through `$this->setData()->save()` calls. But, if you want to fix this quickly, just issue a `$this->load($this->getOptionTypeId())` before the `save`. This will set the proper `storedData` property onto the model.

**Comment by antboiko** [comment]
Hello @SamTay , could you please advise me if you have any errors upon saving the product with identical values in custom option? What Magento version are you using?

Thanks,
Anton.

**Comment by samtay** [comment]
No, see the above code references, this fails silently. Occurs on latest version.

**Comment by antboiko** [comment]
@SamTay thanks for the details, I've created internal ticket MAGETWO-54516 to investigate this issue.

Best,
Anton.

**Comment by ttribeiro** [comment]
I have a similar problem. I edit the price of the option and do not save the price correctly.

Before Save

<img width="1547" alt="screen shot 2016-11-18 at 2 14 14 am" src="https://cloud.githubusercontent.com/assets/1144965/20423364/731d72b4-ad35-11e6-893b-c16f9e7e96d8.png">

After Save

<img width="1556" alt="screen shot 2016-11-18 at 2 15 34 am" src="https://cloud.githubusercontent.com/assets/1144965/20423376/7be05cb8-ad35-11e6-80bf-128b1dd65a93.png">

**Comment by yutv** [comment]
Can anyone from magento tell when this bug will be fixed? Really guys, you have had 1+ year to fix it but this bug still exists in your recent 2.2 release.

Here is hotfix - just modify [Magento\Catalog\Model\Product\Option\Value::saveValues](https://github.com/magento/magento2/blob/3561b6614eeafb70cbcbf0dc0254359b857af3d4/app/code/Magento/Catalog/Model/Product/Option/Value.php#L191-L215) method: 
1. add `$clone = clone $this;` after foreach
2. use `$clone` instead of `$this` in the foreach body.

**Comment by magento-engcom-team** [comment]
@samtay, thank you for your report.
We've created internal ticket(s) MAGETWO-54516 to track progress on the issue.

**Comment by yutv** [comment]
Here is a module with [clone based workaround](https://github.com/orange35/magento2-custom-option-value-save-handler/blob/master/CatalogModelProductOptionValue.php) mentioned in my previous comment:
`    composer require orange35/magento2-custom-option-value-save-handler`

**Comment by VladimirZaets** [comment]
Hi @samtay. Thank you for your report. 
The issue has been fixed in magento/magento2#13569 by @JeroenVanLeusden in 2.2-develop branch
Related commit(s):
 - [d7f6baa1f20492a43ef76d32cb32be8b5f4b903d](https://github.com/magento/magento2/commit/d7f6baa1f20492a43ef76d32cb32be8b5f4b903d)
 - [cb304dbdc9520528cacc77e214901a5ddb7a25fa](https://github.com/magento/magento2/commit/cb304dbdc9520528cacc77e214901a5ddb7a25fa)
 - [0b3fd22abb39e1f3aa802204e4c17df4c268a090](https://github.com/magento/magento2/commit/0b3fd22abb39e1f3aa802204e4c17df4c268a090)

The fix will be available with the upcoming 2.2.6 release.

**Comment by magento-engcom-team** [comment]
Hi @samtay. Thank you for your report. 
The issue has been fixed in magento/magento2#16838 by @JeroenVanLeusden in 2.3-develop branch
Related commit(s):
 - [955fbf2b92cee5336489c0fdede4d862dee275fd](https://github.com/magento/magento2/commit/955fbf2b92cee5336489c0fdede4d862dee275fd)
 - [db95d8ab1dee5030a3d592f9ecdea117b6b34a1f](https://github.com/magento/magento2/commit/db95d8ab1dee5030a3d592f9ecdea117b6b34a1f)

The fix will be available with the upcoming 2.3.0 release.
