### ISSUE TITLE
Exception during invoice order that contains Physical and Virtual Gift Cards

### ISSUE THREAD

**Issue by virtual97** [magento/magento2#5072]
## Steps to reproduce
1. Install 2.0.6 Magento version.
2. Add Physical Gift Card to the cart (sku=243-MB04).
3. Add Virtual Gift Card to the cart (sku=243-MB09).
4. Place order using "Check / Money Order" (or using "PayPal Express Checkout").
5. Go to Admin panel and create an invoice for this order.
## Expected result
1. The invoice was created successfully for the order with an appropriate successfully message.
## Actual result
1. The Invoice was created, but exception message appeared:
   [exception.txt](https://github.com/magento/magento2/files/320048/exception.txt).

**Comment by orlangur** [comment]
GiftCard module does not seem to be a part of Community Edition. Please report this issue in partner portal.

**Comment by magento-engcom-team** [comment]
@virtual97 thank you for your report. 
Because Gift Cards module is not functionality of Magento CE, please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways: 
You can use the Support portal associated with your account or If you are a Partner reporting on behalf of a merchant, use the Partner portal. 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
