### ISSUE TITLE
REST payment-information for guest require cartId field (which is not needed)

### ISSUE THREAD

**Issue by patricklwy** [magento/magento2#5075]
## Steps to reproduce (referring to http://devdocs.magento.com/swagger/index.html)
1. Using Magento Community Luma. Configured with Braintree sandbox credit card payment method.
2. Using curl command to run this API = quoteCartManagementV1, "POST /V1/carts" to generate empty cart.
3. Using curl command to add product into shopping cart.
4. Using curl command to run this API = checkoutGuestTotalsInformationManagementV1, data return successfully.
5. Using curl command to run this API = checkoutGuestPaymentInformationManagementV1, "POST /V1/guest-carts/{cartId}/payment-information" to check out and place order with credit card information.
- This is how the whole curl command with parameters looks like (assuming 16 is my quoteId) = 
  curl -X POST -k -H "Authorization: Bearer 5aihu2h6infacnx3xum6jcqm5bdjjo7w" -H "Accept: application/json" -H "Content-type: application/json" -d '{"email":"abc@gmail.com", "paymentMethod":{ "method":"braintree", "additional_data":{ "cc_last4":"1111", "store_in_vault":true, "payment_method_nonce":"", "cc_token":"", "device_data":"", "cc_type":"VI", "cc_exp_year":"2017", "cc_exp_month":"7" } }, "billingAddress":{ "id":0, "region":"string", "regionId":0, "regionCode":"string", "countryId":"string", "street":[ "string" ], "company":"string", "telephone":"string", "fax":"string", "postcode":"string", "city":"string", "firstname":"string", "lastname":"string", "middlename":"string", "prefix":"string", "suffix":"string", "vatId":"string", "customerId":0, "email":"string", "sameAsBilling":0, "customerAddressId":0, "saveInAddressBook":0, "extensionAttributes":{ }, "customAttributes":[ { "attributeCode":"string", "value":"string" } ] }}' https://magento.mirum-apac.com/rest/V1/guest-carts/16/payment-information
## Expected result
1. Should be able to place the order successfully. Tested with the UI by clicking through.
## Actual result
1. Step five above with curl command response with an error message indicating = {"message":"No such entity with %fieldName = %fieldValue","parameters":{"fieldName":"cartId","fieldValue":null}}

According to the API documentation for checkoutGuestPaymentInformationManagementV1, it doesnt require any cartId as part of the JSON parameter. Any idea?

**Comment by YevSent** [comment]
Hi @patricklwy, this error says what active quote for this id is not found.
In your case the `cartId` is  **16** and this is incorrect, because for guests users it should be a hash string instead integer value.
If you open a `quote_id_mask` table, you will see `masked_id` field related to your `quote_id`, this `masked_id` should be presented in url request.

Related to API docs a `POST /V1/guest-carts/{cartId}/payment-information` contains `cartId` field in the request and it's required field.

**Comment by patricklwy** [comment]
That's the thing. My step to reproduce, step 4; using API checkoutGuestTotalsInformationManagementV1 (POST /V1/guest-carts/{cartId}/totals-information), I mange to get quotes total by doing a POST by replacing the "cartId" with **16**. 

Anyway, do you have any idea how can I generate the said hash string using JScript or is there any API I can call to retrieve it? I creating a client app using Java.

Thanks for the prompt respond.

**Comment by YevSent** [comment]
The `quoteGuestCartManagementV1` has `POST /V1/guest-carts`, which you should run instead `POST /V1/carts`, because it should create a quote for guests users and this request will return hashed quote id.

I'm close this ticket, because any issues in the exists logic or code. Please, if you will have some errors,  be free to reopen it.
