### ISSUE TITLE
Add to cart transalation and on Swatch not working

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#5087]
Hi,

I have two issues here..
first one is, I have installed the language pack (http://imaginaerum.github.io/magento2-language-fr-fr/en.html)
It works fine, but it does not work on Add to cart button ( when i click on it, it shows Adding and Addedd in english).. I was reading one of the issues, but could not get it. What would be the fix for this?. I attaching the image for this.

Second is for configurable product.. When i choose swatch as a option for color and weight as drop down.. the Add to Cart does not work.. But if i change the swatch to drop down it works.. its tricky, I am attaching image for ref(working and not working).
![adding n added](https://cloud.githubusercontent.com/assets/19605497/16152319/3ad431e6-3499-11e6-9d5e-e5cf6221df10.png)
![working](https://cloud.githubusercontent.com/assets/19605497/16152324/403a145c-3499-11e6-8af4-b76050526429.png)
![not working](https://cloud.githubusercontent.com/assets/19605497/16152331/45f7ec34-3499-11e6-8778-28fb835ba853.png)

 the image for ref.

**Comment by pboisvert** [comment]
@antboiko can you check if this string is not able to be translated?

**Comment by nmallepally** [comment]
@pboisvert how can I fix it?

**Comment by nmallepally** [comment]
Any update on the above issue, please ?? @antboiko

**Comment by antboiko** [comment]
Hi @nmallepally , the Add to Cart translation was already fixed in https://github.com/magento/magento2/issues/4181. The fix will be available in 2.1 release and also in one of the future patches.

Regarding the second issue, I will update you on this under another ticket that you created https://github.com/magento/magento2/issues/5135.

I'm closing this issue. Please feel free to reopen if it's needed.

Best,
Anton.
