### ISSUE TITLE
Configurable Products shows same regular and Special price 

### ISSUE THREAD

**Issue by christianlakits** [magento/magento2#5097]
Hi,

we setup a configurable product. Now we changed at one product to special price. Now every product  is shown with a regular and special price, even if they are equal.

regards Christian 

please close double post

**Comment by antboiko** [comment]
https://github.com/magento/magento2/issues/4442

**Comment by slavvka** [comment]
The issue has been fixed and delivered to the mainline. It is also ported for 2.0 and 2.1 and will be delivered as a part of nearest patch releases.

**Comment by elenleonova** [comment]
This issue has been delivered to 2.1.3 and 2.0.11 today.

**Comment by programmer2-techybirds** [comment]
How to show exclusive price instead of inclusive price in configurable product with tier price. 
See below example for more clarification.

![image](https://user-images.githubusercontent.com/32291934/32657424-b085ed1e-c63b-11e7-8ee5-66f5663705ad.png)

Here exclusive price is: 5.04
inclusive price is: 6.10

Now when select any single product from dropdown then calculation is upon inclusive price.
Need instead of that exclusive price instead of inclusive price.

Anyone have solution on this?

**Comment by Voblerbg** [comment]
Hi,
I have a problem with visualization of Promo Price in Configurable products. The old price is struck through and the new price is visible, but it is not shown as a promo price.

![screenshot_9](https://user-images.githubusercontent.com/35472165/35068450-c362457a-fbdf-11e7-978c-da5c954643ba.jpg)


My simple product is OK and I want the Configurable product to look the same.
Magento ver. 2.2.1

![screenshot_10](https://user-images.githubusercontent.com/35472165/35068455-c8216ec4-fbdf-11e7-9db6-ded96ce04443.jpg)
