### ISSUE TITLE
[2.0.7] JS minification causes image on product to not show in production

### ISSUE THREAD

**Issue by peec** [magento/magento2#5123]
## Steps to reproduce
1. Install Magento from `2.0.7` branch.
2. Put magento2 in production mode
3. Go into magento admin / settings / advanced / developer. Enable "Javascript merge", "Javascript bundling" and "Javascript minification". 
4. After minification settings is updated in admin. Generate static content with static:content:deploy.
5. Open up a product's full page and see that the product-image is missing.
## Expected result
1. Image on product should show.
## Actual result
1. Javascript exception ( Fotorama )
2. See screenshot of JS exception below

![image](https://cloud.githubusercontent.com/assets/131546/16222687/b9a00588-3799-11e6-99dc-c48daccbb7d5.png)

**Comment by southerncomputer** [comment]
This is fixed in 2.10-rc3 - but you know you should service restart php-fpm and varnish and httpd/nginx and blow your browser cache and magento-cache refresh to get rid of this.

It has to do with the fact that php and php-fpm caches files that are being dynamically generated and race condition - you could refresh your "network" developer tab and see the .js files change file size periodically.

rm -rf var/di var/generation var/page_cache var/cache var/view_preprocessed
rm -rf pub/static/\* (if using apache do not rm -rf .htaccess in pub/static/.htaccess!)

Also make sure your /etc/php.d/10-opcache.ini is not cli enabled, and disable filestamp validation because that is the reason you are picking up garbage into the .min.js ! 
^^ this requires service php-fpm restart upon any changes to php/js/css !

Try to go through what I said and clean upgrade to 2.10-rc3 you should be much better off!

It is a pita to clean up this type of corruption/race condition due to levels of caching positively, and negatively without using locking/snapshots!

**Comment by southerncomputer** [comment]
p.s. use php bin/magento deploy:mode:set production rather than static:content:deploy

**Comment by peec** [comment]
Fixed in rc3 confirmed.

**Comment by franckgarnier21** [comment]
Do you have the commit reference of this fix ? I have a similar problem with my custom javascript file.
