### ISSUE TITLE
Umlaut not corretly saved in Widgets

### ISSUE THREAD

**Issue by rugbymauri** [magento/magento2#5132]
## Steps to reproduce
1. Insert a Widget in a Static Block or CMS Page, ex. Category-Link
2. Insert some umlaut character in the text fields, ex. öäü
3. Insert the Widget
4. Reopen the Widget-Dialog, double-click on the insered Widget

![auswahl_001](https://cloud.githubusercontent.com/assets/5549264/16233028/30d9b3e6-37cd-11e6-8691-4b85651e777b.png)

![auswahl_002](https://cloud.githubusercontent.com/assets/5549264/16233032/341a243c-37cd-11e6-9cb3-7f85a83cb7f4.png)

**Comment by palamar** [comment]
Please, provide the used version. 
If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by palamar** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by biolauri** [comment]
I've got the same problem with Magento 2.1.2. All umlauts are getting displayed wrong as can be seen in the screenshots.

If any developer has any question, I'll do my best to help solving this issue. So I would be very happy to reopen it.

# Workaround

For those of you stumbling upon the same error: Just **utf8_decode** your variables before echoing them. For example:

``` php
$text_w_correct_umlauts = utf8_decode($this->getData('text_w_incorrect_umlauts'));
```

**Comment by biolauri** [comment]
After some more testing, I have to admit, the workaround isn't quite acceptable. If you insert the widget and then save the page instantly, it works well (at least it works).
But every time you edit the widget, the already (wrong) converted umlauts get converted again while clicking *Insert widget*. 
Conclusion: **utf8_decode** can't help, because you don't know how often the widget was edited. If you manually replace the wrong characters with the original umlauts each time editing the widget, my workaround will be fine, otherwise not and the umlauts are displayed wrong.

@palamar (or @rugbymauri), please reopen this. Again, I'll be happy to provide any information helpful to get this done! :-)
By the way, this is an issue with the Magento backend, but its effect is on the frontend as well. The umlauts are not only displayed incorrect in the widgets editing form, but also for customers viewing pages displaying widgets with umlauts.

**Comment by biolauri** [comment]
Aaaahhh, so embarrassing…
Another ticket is already opened: #7249. I searched twice for already existing issues, but used only the string *umlaut* and variations/compunds. Really sorry for pinging you both!
