### ISSUE TITLE
URL key for specified store already exists. While Importing products in bluk

### ISSUE THREAD

**Issue by Rajesh-Rathod** [magento/magento2#5162]
## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...
## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...
## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by vzabaznov** [comment]
Hi @Rajesh-Rathod.
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.
And please provide more proper steps, adding configurable product to cart is working fine on latest mainline, i don't understand how the title bound with the ticket body
