### ISSUE TITLE
Frontend Product Details -  Warning: Magento\Framework\Locale\Format::getPriceFormat(): Cannot load resource element 'default'

### ISSUE THREAD

**Issue by bhaveshsurani** [magento/magento2#5183]
Magento Version: 2.1.0-rc3
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Go to Product details page from home page or any product listing page
## Expected result
1. It would require to show product details with add to cart options.
## Actual result
1.  Warning: Magento\Framework\Locale\Format::getPriceFormat(): Cannot load resource element 'default' in lib\internal\Magento\Framework\Locale\Format.php on line 112
   ![magento2_dev_breathe-easy-tank_html](https://cloud.githubusercontent.com/assets/1414787/16301495/4a92909a-3963-11e6-9765-64bcd506e304.jpg)

**Comment by veloraven** [comment]
Hi @bhaveshsurani !
Thank you for your report.
Unfortunately I was not able to reproduce this issue.
Could you please:
1. Provide us with detailed information about your environment: PHP version, MySQL version and web server version.
2. Tell us if it was clear Magento installation or upgrade from some other version?
3. Provide us with full steps how to reproduce this issue including type of the product and all product's properties.
4. Also please confirm that issue reproduces on ver. 2.1.0 as  you mentioned two branches in description: 2.1.0-rc3 and develop branch.

**Comment by bhaveshsurani** [comment]
1. Provide us with detailed information about your environment: PHP version, MySQL version and   web server version.
   - here is version of php/mysql/web
     mysqlnd 5.0.11-dev
     Apache/2.4.17 
     PHP/5.6.21
2. Tell us if it was clear Magento installation or upgrade from some other version?
   - i have installed 2.1.0 then upgrade to 2.1.0-rc3 and then do upgrade to 2.2.0-dev.
3. Provide us with full steps how to reproduce this issue including type of the product and all product's properties.
   - Just have installed sample data. Nothing any kind of changes done. Then navigating to product listing page and from there to details page. Error get reprodce on details page only. Here is video for the same.
     http://www.screencast.com/t/fiGPAzrcND
4. Also please confirm that issue reproduces on ver. 2.1.0 as you mentioned two branches in description: 2.1.0-rc3 and develop branch.
   - yes i have installed 2.1.0 then upgraded to 2.1.0-rc3 and then finally 2.2.0-dev but still issue there.

Hope it will help. do let me know if require more details.

**Comment by lhsatch** [comment]
Hi,
I have a similar problem. I installed Magento 2 (2.0.1)via composer using the repo.magento.com on a WAMP using php 5.6.16. When going to the cart I get the following error
`1 exception(s):
Exception #0 (Exception): Warning: Magento\Framework\Locale\Format::getPriceFormat(): Cannot load resource element 'default' in C:\wamp64\www\magento2\vendor\magento\framework\Locale\Format.php on line 112

Exception #0 (Exception): Warning: Magento\Framework\Locale\Format::getPriceFormat(): Cannot load resource element 'default' in C:\wamp64\www\magento2\vendor\magento\framework\Locale\Format.php on line 112
#0 C:\wamp64\www\magento2\vendor\magento\framework\Locale\Format.php(112): Magento\Framework\App\ErrorHandler->handler(2, 'Magento\Framewo...', 'C:\wamp64\www\m...', 112, Array)
#1 C:\wamp64\www\magento2\vendor\magento\module-checkout\Model\DefaultConfigProvider.php(275): Magento\Framework\Locale\Format->getPriceFormat(NULL, 'GBP')
#2 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Interceptor.php(146): Magento\Checkout\Model\DefaultConfigProvider->getConfig()
#3 C:\wamp64\www\magento2\var\generation\Magento\Checkout\Model\DefaultConfigProvider\Interceptor.php(26): Magento\Checkout\Model\DefaultConfigProvider\Interceptor->___callPlugins('getConfig', Array, Array)
#4 C:\wamp64\www\magento2\vendor\magento\module-checkout\Model\CompositeConfigProvider.php(32): Magento\Checkout\Model\DefaultConfigProvider\Interceptor->getConfig()
#5 C:\wamp64\www\magento2\vendor\magento\module-checkout\Block\Cart\Shipping.php(54): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#6 C:\wamp64\www\magento2\vendor\magento\module-checkout\view\frontend\templates\cart\shipping.phtml(28): Magento\Checkout\Block\Cart\Shipping->getCheckoutConfig()
#7 C:\wamp64\www\magento2\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\wamp64\www\m...')
#8 C:\wamp64\www\magento2\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart\Shipping), 'C:/wamp64/www/m...', Array)
#9 C:\wamp64\www\magento2\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/wamp64/www/m...')
#10 C:\wamp64\www\magento2\vendor\magento\framework\View\Element\AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#11 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#12 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('checkout.cart.s...')
#13 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.s...')
#14 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.cart.s...')
#15 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.cart.s...', true)
#16 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.cart.s...')
#17 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('cart.summary')
#18 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cart.summary')
#19 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cart.summary')
#20 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cart.summary', true)
#21 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('cart.summary')
#22 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('checkout.cart.c...')
#23 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.c...')
#24 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.cart.c...')
#25 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.cart.c...', true)
#26 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.cart.c...')
#27 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('checkout.cart.i...')
#28 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.i...')
#29 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.cart.i...')
#30 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.cart.i...', true)
#31 C:\wamp64\www\magento2\vendor\magento\framework\View\Element\AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.cart.i...', true)
#32 C:\wamp64\www\magento2\vendor\magento\module-checkout\view\frontend\templates\cart.phtml(15): Magento\Framework\View\Element\AbstractBlock->getChildHtml('with-items')
#33 C:\wamp64\www\magento2\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('C:\wamp64\www\m...')
#34 C:\wamp64\www\magento2\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart), 'C:/wamp64/www/m...', Array)
#35 C:\wamp64\www\magento2\vendor\magento\framework\View\Element\Template.php(279): Magento\Framework\View\Element\Template->fetchView('C:/wamp64/www/m...')
#36 C:\wamp64\www\magento2\vendor\magento\framework\View\Element\AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#37 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#38 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('checkout.cart')
#39 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart')
#40 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.cart')
#41 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.cart', true)
#42 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.cart')
#43 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#44 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#45 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#46 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#47 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#48 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#49 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#50 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#51 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#52 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#53 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#54 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#55 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#56 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#57 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#58 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#59 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#60 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#61 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#62 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#63 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#64 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#65 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#66 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#67 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#68 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#69 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#70 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#71 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#72 C:\wamp64\www\magento2\vendor\magento\framework\View\Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#73 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#74 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Layout\Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#75 C:\wamp64\www\magento2\vendor\magento\framework\View\Result\Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#76 C:\wamp64\www\magento2\vendor\magento\framework\View\Result\Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#77 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#78 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#79 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#80 C:\wamp64\www\magento2\vendor\magento\module-page-cache\Model\Controller\Result\VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#81 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#82 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#83 C:\wamp64\www\magento2\vendor\magento\module-page-cache\Model\Controller\Result\BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#84 C:\wamp64\www\magento2\vendor\magento\framework\Interception\Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#85 C:\wamp64\www\magento2\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#86 C:\wamp64\www\magento2\vendor\magento\framework\App\Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#87 C:\wamp64\www\magento2\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#88 C:\wamp64\www\magento2\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#89 {main}`
The system log also generates:
`[2016-07-22 10:18:16] main.CRITICAL: Broken reference: the 'catalog.compare.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-22 10:18:16] main.CRITICAL: Broken reference: the 'sale.reorder.sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-22 10:18:16] main.CRITICAL: Broken reference: the 'wishlist_sidebar' element cannot be added as child to 'sidebar.additional', because the latter doesn't exist [] []
[2016-07-22 10:18:16] main.CRITICAL: Broken reference: the 'checkout.cart.item.renderers.gift-card.actions.gift_options' element cannot be added as child to 'checkout.cart.item.renderers.gift-card.actions', because the latter doesn't exist [] []
[2016-07-22 10:18:16] main.CRITICAL: Broken reference: the 'checkout.cart.item.renderers.gift-card.actions.gift_options' tries to reorder itself towards '', but their parents are different: 'checkout.cart.item.renderers.gift-card.actions' and '' respectively. [] []`.
I have magento in developer mode. I have tried refreshing cache and indexes but still no luck.

**Comment by lhsatch** [comment]
I have just changed to production mode and although it doesn't generate an error I only see the luma logo and the footer. In the system.log I get the below error:
`[2016-07-22 11:57:14] main.CRITICAL: Warning: Magento\Framework\Locale\Format::getPriceFormat(): Cannot load resource element 'default' in C:\wamp64\www\magento2\vendor\magento\framework\Locale\Format.php on line 112 [] []`

**Comment by lhsatch** [comment]
I have inspected the Code in the Format.php file and the $localeData isn't returning anything/
$localeData = (new DataBundle())->get($localeCode); //$localeData is empty

**Comment by lhsatch** [comment]
If I set $defaultset to self::$defaultNumberSet; then it works.

**Comment by ozmuhsin** [comment]
This error happens if you have intl.error_level set to other values than 0 i.e if you have changed it from its default value 0.Comment it out to fall back to default and it worked.

**Comment by ndungujackson** [comment]
I have resolved this by setting  intl.error_level  to 0.

**Comment by vc7deo** [comment]
I have resolved this by setting intl.error_level to 0.

**Comment by titechnologies** [comment]
We got the same issue in 2.1.7
Fixed by intl.error_level to 0.

**Comment by chetansanghani** [comment]
I have resolved this by setting intl.error_level to 0.

**Comment by magento-engcom-team** [comment]
@bhaveshsurani, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.2.0, 2.1.9
