### ISSUE TITLE
Error generating URN-catalog when blank one exists

### ISSUE THREAD

**Issue by JamesonNetworks** [magento/magento2#5188]
### Preconditions
 Install Magento from `develop` branch.

## Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a blank misc.xml file inside of the .idea folder (if using php storm)
3. Run 'bin/magento dev:urn-catalog:generate --ide="phpstorm" ./.idea/misc.xml'
## Expected result
1. A new URN catalog for the project should get generated
## Actual result
1. User receives the error "Warning: DOMDocument::loadXML(): Empty string supplied as input in /Sites/magento2ce/app/code/Magento/Developer/Model/XmlCatalog/Format/PhpStorm.php on line 61"

I admit that it is an esoteric case, however, the routine generating the xml file is only creating a new fresh file in the instance that the file doesn't exist. If a blank file exists, it attempts to read the existing XML out of the file and throws the error. I had a problem where I created the .idea/misc.xml file but an exception was thrown during the creation process. The invalid misc.xml would generate this error until I removed the file entirely and ran the command again. Pretty low priority, but just thought I'd report it.

**Comment by magento-engcom-team** [comment]
@JamesonNetworks, thank you for your report.
We've created internal ticket(s) MAGETWO-80579 to track progress on the issue.

**Comment by tdgroot** [comment]
I would like to pickup this issue!

**Comment by tdgroot** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by andkirby** [comment]
**2.2.0** - the same.
I was just generating the file several times and after some step it just get broken.
I don't understand why it's become empty. I can assume it tries to read the file at first. I think that's wrong due to reason an exist file could have wrong content.
In a nutshell, it's a strange behavior.

**Comment by okorshenko** [comment]
Hi @JamesonNetworks. Thank you for your report. 
The issue has been fixed in magento/magento2#11686 by @tdgroot in 2.2-develop branch
Related commit(s):
 - 177e540938631fbb749dcc028d4f8f864e290b4e
 - 0d652139889d882dd6646741070e12d04ebd8a5b
 - a781bf6f75c74a6e871f1640ae679b18967ac000
 - dcc480d15c9f0c1aca77974d5cd89a972f1d32dd
 - 5d4e1c29ca7d0a62a3465dd7b98a5c30d1410845
 - b552dd1be35436e05065d8269dabe6cebfaaafcd
 - b85b91e4fa5c41fe337accd4709b184d7811cd65

The fix will be available with the upcoming patch release.

**Comment by okorshenko** [comment]
Hi @JamesonNetworks. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1298 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 54301a8ea63134b961d6b7b9891c31bc2798f8dc
 - 402b719168fc8b17ebc099c12b85f629cf90303b
 - 3837f2780b32112b7f70a9d3074158ee2336b1b7
 - 031e23e93ffaa258a39dfed5c5edb0e873ab0aa8
 - aa267f462f7eb964226a9c89d20c04b718406337
 - 934818dbee0bd36ec5eae7b3b7230c4d8a70b481
 - 6bed7d475bff5e98e27b8fdcaa998438bc31ed05
 - 72b2794043afd0012f9a8d5f6fc04df07acad3af
 - 4e64c415e26845826b527c17008eda00d3808591
 - d3feb280ed621c5ffe2dc3a2b7ac30abb25d9c22
 - 7aeccea46d2336a1322811a9d60d52432108c8e3
 - b857c022ae1cdb7975cf5c3d79cd679843c72a3b
 - a75bf2391dfc6e7c8a1283490f5de7551de42bbe
 - ab2e5798e529633f770c3970a0df999c11764e06
 - d904690443d43322c5dd2c58d075944eae867316
 - a821c7a3c17eb06983f421c47a7cc0fe99983a38
 - 68ac4c0bd6cae6b5b62e683c23f49293ee41d797
 - 93fe4d14faba635cc7c668b2d931e7595567cda9
 - f43fd4b98c55e1f498d060aeb245e4c969bdcb13
 - 2c52a8fd15cff7af7245573e2f26be6d601acb08

The fix will be available with the upcoming 2.3.0 release.
