### ISSUE TITLE
[ CE 2.1.0-rc3] - Cancel an order of bundle product

### ISSUE THREAD

**Issue by mhabou** [magento/magento2#5194]
## Steps to reproduce
1. Install Magento ver 2.1.0-rc3
2. Add Bundle Product to the cart.
3. Place the order
4. invoice partially the order
5. Cancel

[See The video](https://youtu.be/z9Yjt3kRh8M)
## Expected result

Order status is procerssing
## Actual result

Order status is complete

**Comment by mhabou** [comment]
@andimov :

The problem is in the qty_canceled which still 0 and the order status must be "processing" because there is no shipment

![bundle_product_9](https://cloud.githubusercontent.com/assets/13301885/16334613/7c10f736-39f1-11e6-9f7c-6109461f6ed3.png)

**Comment by AVoskoboinikov** [comment]
Hi @Dayssam,

Thank you for your report. I have created ticket (#MAGETWO-57880) in our internal jira to fix this. This issue will be closed after fix.

**Comment by veloraven** [comment]
This issue was already fixed for develop branch.
Closed.

**Comment by korostii** [comment]
The issue was reported on 2.1.x branch.
Could you please explain the reasoning behind fixing it on `develop`? (and not `2.1-develop` or both)
That is about as useful for a user of a composer-installed version of Magento CE 2.1.x as fixing it for EE only: there is no safe and straightforward way to take advantage of the fix.

Is there some kind of guide regarding patching such an instance using the code from `develop` branch you could reference? It might become really useful now that a lot of issues hang in this state indefinitely.
