### ISSUE TITLE
Web setup wizard not working in production mode 2.0.7

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#5255]
## Steps to reproduce
1. Access web setup wizard
2. https://mysite.com/setup/ loads black error page and states:

The mysite.com page isn’t working

mysite.com didn’t send any data.
ERR_EMPTY_RESPONSE
## Expected result
1. Web setup wizard loads
## Actual result
1. https://mysite.com/setup/ loads black error page and states:

The mysite.com page isn’t working

mysite.com didn’t send any data.
ERR_EMPTY_RESPONSE
2. 
![2016-06-25_152913](https://cloud.githubusercontent.com/assets/17181901/16357277/ea0bd906-3ae9-11e6-87f1-d5373a7bc31a.png)
1. Cleaned var/session folder but no luck
2. no errors in log

Please help

**Comment by palamar** [comment]
Could you please provide additional information:
- PHP version
- web server name and version
- check web server logs for possible errors
- check PHP logs for possible errors

As I can see you are using HTTPS, do you have valid certificate for your domain?
Do you have security exception for your domain if you are using self-signed certificate?
Also you can try to use http://mysite.com/setup/  instead of https://mysite.com/setup/ or use Firefox that has interface that allow add self-signed certificate to exception.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one.
