### ISSUE TITLE
'Flush Static Files Cache' wipes out theme

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#5272]
## Steps to reproduce
1. Install Magento CE 2.0.7.
2. Load Luma theme, e.g.:
   ![2016-06-27_111135](https://cloud.githubusercontent.com/assets/4110567/16367685/a7f864ce-3c58-11e6-9c12-0feee8d5f07d.png)
3. Go to Admin / System / Cache Management and click 'Flush Static Files Cache':
   ![2016-06-27_111148](https://cloud.githubusercontent.com/assets/4110567/16367704/ba26238e-3c58-11e6-8268-767d6dc17252.png)
## Expected result
1. The site should not break after static files are flushed.
## Actual result
1. After flushing static files, the site breaks (it appears the static files are not redeployed automatically):
   ![2016-06-27_111248](https://cloud.githubusercontent.com/assets/4110567/16367716/de1f99be-3c58-11e6-977a-22cd63bba3f4.png)

**Comment by Ctucker9233** [comment]
Is this a custom theme or the default luma theme?

**Comment by thdoan** [comment]
Default Luma theme, developer mode, all caches disabled.

**Comment by ghost** [comment]
same thing just happened to me using default blank theme, developer mode 2.1.2
![screen-shot-2016-11-07-at-1 20 31-am](https://cloud.githubusercontent.com/assets/21045500/20052405/c014bc18-a488-11e6-84ce-c7c0b4e63fb4.jpg)

**Comment by ghost** [comment]
running php bin/magento setup:static-content:deploy it_IT but that is generating errors on the files that are missing and causing a 404

**Comment by progcode** [comment]
use `php bin/magento setup:static-content:deploy` it is regenerate all files

**Comment by ghost** [comment]
as stated above @progcode it is not regenerating the files and it gets errors on the files that are missing causing 404s.

**Comment by progcode** [comment]
@rosandrest I think this is a custom issue, what's the error message?

**Comment by Ctucker9233** [comment]
Had exact same issue. I replaced the entire /lib folder and redeployed static content. My website works again but still experience some js errors.

Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
reports.js:1 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.d @ reports.js:1
jquery-migrate.js:21 JQMIGRATE: Logging is active
jquery.js:2998 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://tuckersfurniture.biz" from accessing a cross-origin frame.(…)
authentication-popup.js:26 Uncaught TypeError: Cannot read property 'autocomplete' of undefined(…)

**Comment by stevematthewroberts** [comment]
The issue is normally when you have a theme over written. That theme I guess has no styles.
You are flushing the cache which then reverts to the theme which the styles arent there or connected.

**Comment by magento-engcom-team** [comment]
@thdoan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by storepeinture** [comment]
I am experiencing the same issue after upgrading to Magento 2.2.3. After pressing "flush static files cache" even the admin backend styles are completely wiped out.

**Comment by DePalmo** [comment]
Can confirm for v 2.2.3. After "Flush static files cache", those files are not regenerated on next load, but the entire website breaks. Frontend loads only partial content while backend is missing all the styles and JS.

This is not expected behavior. Expected is that when CACHE is cleared, it should re-cache the content on next load or right after the cache was cleared.

Solution in our case was:
- reupload app/design/*
- reupload /pub/static/*
- run through SSH: bin/magento setup:static-content:deploy
