### ISSUE TITLE
Please add coupon in last step of checkout

### ISSUE THREAD

**Issue by seansan** [magento/magento2#528]
Please add coupon in last step of checkout

Example: http://www.magentocommerce.com/magento-connect/media/catalog/product/cache/9/image/9df78eab33525d08d6e5fb8d27136e95/l/o/logo11_1.png

Like this: http://www.magentocommerce.com/magento-connect/add-discount-coupon-with-checkout-process-1.html

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-23163

**Comment by asemenenko** [comment]
Hi @seansan , @beckindesigns , @brendanfalkowski , @philwinkle 

Now we allow to apply discount on the Payment & Review step. Discount field is collapsed by default. It can be easily removed from this step if needed by theme developer. There are a number of ways to deal with discount flow, say: 
1. Have a Proceed to Checkout button go to the shopping cart and having discount field removed from Payment & Review step. (for the case when cross sells are heavily used)
2. Keep discount field everywhere.

Normally it is not Ok to completely remove a possibility to add a coupon during checkout process since it may result in abandonment if customer have a discount but can not find a way to use it. 

Having discount displayed as a primary filed with a huge Apply button on the last step of checkout is not good too since makes customer wonder if there is a way to search for the discount (thus resulting in abandonment if start googling)

Thanks for a valuable input!

**Comment by seansan** [comment]
Collapsed is great (and exactly as we use it now)
Also I would add a config setting: enable coupon in checkout yes/no
