### ISSUE TITLE
Where is or how can I generate the app/etc/config.php file?

### ISSUE THREAD

**Issue by guilhermehbueno** [magento/magento2#5290]
Hi people,

I'm starting my first steps in Magento 2. I read in a lot of tutorials and official documentation references to file **app/etc/config.php**. But I didn't found it. Where is this file?

I'm simply trying to create a custom module and enable this in Magento 2.

**Comment by toddwolaver** [comment]
Since this is not a bug, you would probably be better served by posting a question on https://community.magento.com/ or http://magento.stackexchange.com/

Ensure you have completed the installation: http://devdocs.magento.com/guides/v2.0/install-gde/bk-install-guide.html

Once you have a functional install, you may enable / disable modules via the command line utility (magento module:enable):
http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-enable.html
