### ISSUE TITLE
2.1: Can't save a new product with a new product image

### ISSUE THREAD

**Issue by sheldonli999** [magento/magento2#5294]
## Steps to reproduce
1. Install Magento 2.1
2. Click catalog
3. add a new product
4. fill in the fields for product
5. add an image
## Expected result
1. The product is saved
2. ...
## Actual result
1. An error occurred: Required parameter 'theme_dir' was not passed
2. Adding a new product without the image is ok
3. ...

**Comment by sheldonli999** [comment]
![screen shot 2016-06-27 at 7 30 23 pm](https://cloud.githubusercontent.com/assets/18491705/16401927/55c42130-3c9d-11e6-89a4-184460fe17b0.png)

**Comment by afavata** [comment]
same behaviour....

Note also if a product is updated, having deleted its image, a second error is shown:
Cannot gather stats! Warning!stat(): stat failed for /var/www/xxxxxxxx/pub/media/catalog/product/w/o/productimmage1.jpg

Please give max priority as this does not allow to add or update products at all

Thanks indeed

**Comment by didineedthis** [comment]
Same error here unable to upload an image to my product or change the configuration. even tried by ticking the box and selectin update attributes NEW THEME that doesn't
 work either.
Required parameter 'theme_dir' was not passed
![screenshot 24](https://cloud.githubusercontent.com/assets/10882960/16575127/7c6558be-427d-11e6-8cfc-b0e4660bd038.png)

I tried deleting the product and adding a new and got this error. i tried FTP the images to that directory and still got the same error

![screenshot 26](https://cloud.githubusercontent.com/assets/10882960/16575682/1400f1a2-4282-11e6-894e-a9d901c210a1.png)

**Comment by joates-ldg** [comment]
I'm seeing this error regardless of weather I have an image or not. I also get "Update with id "0" does not exist." whenever I try and save a product.

**Comment by afavata** [comment]
I resolved the issue. In my case the problem was not Magento but a wrong operation I did time ago as follow:
I created a theme creating the relative path in app/design/frontend/**MyFolder/MyTheme** and registered it as explained in Magento 2 online documentation.
Then I decided to cancel the theme and instead to use the appropriate command:
bin/magento theme:uninstall frontend/MyFolder/MyTheme 
I deleted the folders directly. This is not a good operation as the database is not updated with the due information. 
Solution: with an editor of database as phpmyadmin, delete the record in the table "Theme" corrisponding to the deleted folders
![2016-07-05](https://cloud.githubusercontent.com/assets/15713756/16587559/8481ed3e-42cb-11e6-84e5-90af47700f34.png)

**Now I can update products without any issue**

 I hope this will help!

@sheldonli999 please look whether these tips help you and in case close the ticket. Thank you!

**Comment by didineedthis** [comment]
You my friend are a star i deleted a theme and forgot about it. all good now i just added and deleted a product :)

**Comment by afavata** [comment]
@didineedthis Happy you definitely resolved the issue and you can now proceed working again with Magento 2

**Comment by didineedthis** [comment]
Thanks again, Appreciated.

**Comment by Krapulat** [comment]
Thanks @afavata. I had the same problem.

**Comment by afavata** [comment]
Noted your comment @krapulat.Thanks

**Comment by refaelgold** [comment]
@afavata  thank you so much!  this issue need to be close and be alerted to magento 2 team

**Comment by joaotnlima** [comment]
Thank you. ;)

**Comment by veloraven** [comment]
Closed as seems to be not Magento issue.
@sheldonli999 if you still experience this problem please reopen the ticket with corresponding comment.

**Comment by SVUskov** [comment]
Thank you. Problem was solved.

**Comment by vtransy** [comment]
thannks @afavata (y)
