### ISSUE TITLE
[2.1] Unable to get store URL from admin

### ISSUE THREAD

**Issue by acharrex** [magento/magento2#5322]
### Preconditions (*)
Magento 2.4-develop
### Steps to reproduce (*)
1. Install Magento  from `develop` branch.
2. Run the following code from the admin area (by example from a controller):

``` php
$url = $this->_objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore(1) // 1 = default store id
    ->getUrl('myroute')

echo $url;
```

### Expected result (*)

```
http://mymagentoshop.local/myroute
```

### Actual result (*)

Magento returns an URL prefixed with the admin path:

```
http://mymagentoshop.local/admin_XXXX/myroute
```
## Note

The following code:

``` php
$url = $this->_objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore($customer->getStoreId())
    ->getBaseUrl();
```

Works correctly:

```
http://mymagentoshop.local/
```

This problem seems to be limited to the "getUrl" method.

This issue was not present with Magento 2.0.7.

**Comment by sfedosimov** [comment]
I have the same issue on Magento 2.1.3

**Comment by Rabot18** [comment]
Same problem here, up

**Comment by sfedosimov** [comment]
Solution (in controller):
`$this->url->setScope($this->storeManager->getWebsite($customer->getWebsiteId())->getDefaultStore());`

**Comment by Rabot18** [comment]
I use it in a class who extends AbstractHelper so i used _urlBuilder like this instead of StoreManagerInterface : 
```
$this->_urlBuilder->setScope($storeId);
return $this->_urlBuilder->getUrl('myurl/action', $defaultParams);
```
thx @sfedosimov

**Comment by perryholden** [comment]
Still an issue as of 2.1.4. In the backend, I get the store from a particular order, and then try to generate a URL for that store:

`/** @var \Magento\Store\Model\Store $orderStore */`
`    $orderStore = $this->storeManager->getStore($order->getStore()->getId());`
`    $storeUrl = $orderStore->getUrl('controlleraction');`

Expected: `https://store.domain.com/controlleraction/...`
Result: `https://www.domain.com/backend/controlleraction/...`

I find that sometimes if I flush the cache, I get the correct URL, but after a while, it returns to the incorrect backend URL.

**Comment by perryholden** [comment]
A workaround to get a frontend URL for a store in the backend:

See how Magento is generating the "View" link in the CMS page admin grid via its page actions: `Magento\Cms\Ui\Component\Listing\Column\PageActions`. It injects the following class in order to build the URL: `Magento\Cms\Block\Adminhtml\Page\Grid\Renderer\Action\UrlBuilder`, which uses `\Magento\Framework\UrlInterface`. Well, that `UrlInterface` has a frontend model and a backend model.

In the CMS module's `etc/adminhtml/di.xml`, it injects the **frontend** URL model for that interface:

```
<type name="Magento\Cms\Block\Adminhtml\Page\Grid\Renderer\Action\UrlBuilder">
    <arguments>
        <argument name="frontendUrlBuilder" xsi:type="object">Magento\Framework\Url</argument>
    </arguments>
</type>
```

If you don't do this, no matter how you pass it the proper scope, it always resets that scope after getting the base URL. Not good.

Anyhow, I was able to get it working then by doing what `Magento\Cms\Block\Adminhtml\Page\Grid\Renderer\Action\UrlBuilder` is doing, and using `di.xml` to pass it the proper URL model. *Nevertheless, this should be fixed*. There is no reason why I shouldn't be able to just call getUrl() from a store model in the backend.

**Comment by magento-engcom-team** [comment]
@acharrex, thank you for your report.
We've created internal ticket(s) MAGETWO-84693 to track progress on the issue.

**Comment by ashokbhati180** [comment]
I found an issue in magento 2 that it does not load get store URL  when cache is enabled . that I am working on magento 2 and my cache is disabled and its working properly but if i enable cache then It redirect to store id 1 always and i did not found my store URL

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shelkeakshay96** [comment]
I am working on this issue at #dcmdindia19

**Comment by shelkeakshay96** [comment]
I am working on this issue at #dmcdindia19

**Comment by magento-engcom-team** [comment]
@shelkeakshay96 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by shelkeakshay96** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shelkeakshay96. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shelkeakshay96, here is your [Magento instance](https://i-5322-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-5322-2-3-develop.instances.magento-community.engineering/admin](https://i-5322-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shelkeakshay96** [comment]
Try following code in admin controller : 


```
namespace vendor_name\module_name\Controller\Adminhtml\Test;
class Index extends \Magento\Backend\App\Action {
	public function __construct(
		\Magento\Backend\App\Action\Context $context,
		\Magento\Framework\Url $url
	) {
		parent::__construct($context);
		$this->url = $url;
	}
	public function execute() {
		$frontendUrlFromAdmin = $this->url->getUrl('your_route/index/index');
                echo $frontendUrlFromAdmin; die;
	}
}
```

**Comment by marciomaciel** [comment]
I am working on this issue at #mm19br

**Comment by magento-engcom-team** [comment]
@marciomaciel thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by marciomaciel** [comment]
@magento I am working on it

**Comment by drpayyne** [comment]
I analyzed the flow a little and this is what I observe
- Run `bin/magento cache:flush`
- Use this in an `adminhtml` controller
```
return $this->_objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore(1)->getUrl('hello');
```
### Expected
- `$this->_url` in `\Magento\Store\Model\Store` is `\Magento\Framework\Url` (**frontend** URL handler)
- http://magento2.site/hello
### Actual
- `$this->_url` in `\Magento\Store\Model\Store` is `\Magento\Framework\Url` (**frontend** URL handler)
- http://magento2.site/hello
- Refresh page (Magento now uses cache)
- `$this->_url` in `\Magento\Store\Model\Store` is `\Magento\Backend\Model\Url` (**backend** URL handler)
- http://magento2.site/admin/hello

Only backend URL handler is initialized for any more calls to `\Magento\Framework\UrlInterface`

@engcom-Alfa any idea why Magento could possibly use different interface implementations for different calls?

**Comment by Serializator** [comment]
@drpayyne, `Magento\Framework\UrlInterface` has two preferences, one in `/vendor/magento/magento2-base/app/etc/di.xml` and the other in `/vendor/magento/module-backend/etc/adminhtml/di.xml`

When you're in the `adminhtml` area, it uses the preference from `magento/module-backend`, causing it to become a `Magento\Backend\Model\UrlInterface` and giving you an unexpected result.

**Product URL**
I had the same problem with a colleague of mine today when we tried to get the URL of a product. 

`Magento\Catalog\Model\Product` uses the `Magento\Catalog\Model\Product\Url` class which in turns uses the `Magento\Framework\UrlFactory` which uses the `Magento\Framework\UrlInterface`, causing the same exact problem as in the `Magento\Store\Model\Store` class.

We eventually solved our problem with two virtual types and a type.

```xml
<type name="ourClass">
    <arguments>
        <argument name="urlBuilder" xsi:type="object">virtualProductUrl</argument>
    </arguments>
</type>

<virtualType name="virtualProductUrl" type="Magento\Catalog\Product\Url">
    <arguments>
        <argument name="urlFactory" xsi:type="object">virtualUrlFactory</argument>
    </arguments>
</virtualType>

<virtualType name="virtualUrlFactory" type="Magento\Framework\UrlFactory">
    <arguments>
        <argument name="instanceName" xsi:type="string">Magento\Framework\Url</argument>
    </arguments>
</virtualType>
```

In my opinion this is really dirty, but at the same time, we tried a bunch of stuff such as emulate the area before creating the `Magento\Catalog\Model\Product` using the `Magento\Catalog\Model\ProductFactory`, e.t.c, but nothing really seemed to work.

**Comment by ivankristic** [comment]
Same problem on 2.3.1

Trying to fetch frontend route depending on the store scope from admin
`$storeManager->getStore($storeCode)->getUrl($route, $params)` also returns route from admin scope, even if `$params['_scope']` is set to specific store, resulting in even base url being admin one, and not website in which store is defined.

One viable way for fetching frontend route is to set scope directly on instance of `Magento\Framework\Url::class` and using its class method `getUrl($path, $params)`, because we used it in Helper class and could retrieve it from `Magento\Framework\App\Helper\Context::class`, which seems not too volatile (as opposed to directly injecting it in our class)

**Comment by magento-engcom-team** [comment]
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30039` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ivankristic** [comment]
Is your bot ok, or buggy as well? Spamming me after 2mo of silence

**Comment by lfluvisotto** [comment]
@magento I am working on it
