### ISSUE TITLE
Magento 2.0.7 "Urlkey for the store already exists" error while importing products

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#5334]
I am trying to import simple products, But it fails due to some validation error.
The error message i get is "Additional data: URL key for specified store already exists.".

I have checked the URL keys generated from the product names are all unique. but still i am having this annoying issue.

I am importing >10000 products.

**Comment by dthampy** [comment]
Internal Jira ticket MAGETWO-56315 has been created.

**Comment by jeremib** [comment]
Looks like this bug is done, what's the target release version?

**Comment by magento-engcom-team** [comment]
@Taral-Patoliya @jeremib 
This issue is marked as duplicate and has multiple related tickets in internal bug tracker, which are all related to import and url rewrites mechanisms.
Unfortunately, since the issue report is not clear enough, we can not determine which specific fix you are looking for.
Please verify your case with the latest `2.2.0` and file a new issue report following the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
Thank you
