### ISSUE TITLE
SHow/Hide editor button won't load editor in Chrome Version 51.0.2704.103 m

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#5337]
see video please
[2016-06-29 11h16_44.zip](https://github.com/magento/magento2/files/338934/2016-06-29.11h16_44.zip)

**Comment by veloraven** [comment]
@SidneyBilliet thank you for your report.
Please, provide the used version of Magento. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please provide description according to the template: with steps, actual result and expected result.  It will help other users to find this issue in case when they have the same one.

**Comment by SidneyBilliet** [comment]
@veloraven, @stevenvdp  The used version of Magento is 2.0.7 as vissible in the video ;)
The issue occurs when "minify css" is active. 
This issue is probably related to or the same as https://github.com/magento/magento2/issues/3170 

Kind regards,

**Comment by andimov** [comment]
@SidneyBilliet
Thank you for reporting!
Is this a duplicate for  #3170?
Could you provide description according to the template: with steps, actual and expected result?

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
