### ISSUE TITLE
magento/module-swatches v100.1.0

### ISSUE THREAD

**Issue by ppisarek** [magento/magento2#5361]
## Steps to reproduce
1. $this->helper('Magento\Swatches\Helper\Data');
## Expected result
1. Magento\Swatches\Helper\Data object
## Actual result
1. \LogicException
## Proposed solution
1. Declare class as:

```
class Data extends \Magento\Framework\App\Helper\AbstractHelper
```
## Temporary solution
1. Clone helper in custom module

**Comment by phuc128t** [comment]
I think with new update, we can't call swatch helper in template file. You have to include it in block constructor and use it in a custom function.

**Comment by andimov** [comment]
@ppisarek 
Unfortunately, now it's not easy to understand what is it about, and what is your actual problem is so I have to ask you once more to format your issue according to templates: specifying exact steps to reproduce, actual result, and expected result. 
Additional please specify exact versions or tags you used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
