### ISSUE TITLE
Mixed images order [Magento 2.1.0]

### ISSUE THREAD

**Issue by RG-1** [magento/magento2#5422]
## Steps to reproduce
1. I am using Magento 2.1.0 (updated form Magento 2.0.7).
2. Before the update I imported products from csv file.
3. After the update base image position in a gallery of thumbnails is mixed.
4. Base images are also marked as "thumbnail" and "small".
5. Images order on the backend is set up right.
## Expected result
1. Base image should be first one in a gallery of thumbnails.

![2](https://cloud.githubusercontent.com/assets/17853402/16541919/b373de66-4093-11e6-982e-529aa2619c42.png)
## Actual result
1. The base image is displayed correctly as the main image, but position in a gallery of thumbnails is swapped with first additional image. 
2. Other additional images are on right positions.

![1](https://cloud.githubusercontent.com/assets/17853402/16541917/aa97d978-4093-11e6-8800-29f26584adb6.png)

**Comment by antboiko** [comment]
Hello @RG-1 , please provide more details basing on any of imported products. What was the order of images before the update and how were labels assigned?

Thanks,
Anton.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by AlexKru** [comment]
I have same issue.

Magento\Catalog\Block\Product\View\Gallery::getGalleryImagesJson() returns images list with empty labels and positions = 0 for all.

Magento EE 2.1.0

Data was migrated from Magento EE  1.14.2

**Comment by tvainisi** [comment]
I have this issue on Magento 2.1 also.  When I use the product import spreadsheet, sometimes the base image is somehow the second image in a configurable product gallery (frontend).  When a configuration is chosen from dropdown, the image in the first position (which should be the second image) is then swapped out for a duplicate base image, leaving the gallery with two of the same images.  In the table catalog_product_entity_media_gallery_value I can change the appropriate position for the secondary image and fix this (have to do it on many rows - 1 row for each configuration combination).  Also, all of the rows in this table start out with the same position (1).  I'd guess that's where the problem originates.

One other thing.  Even though I delete all my products (using backend) before importing, it seems that the table I mentioned (along with the associated catalog_product_entity_media_gallery) receives additional rows each time I import.  So that i have 11000 lines in these tables even though I import the same 200 or so products each time.

**Comment by Tristan-N** [comment]
@RG-1 I noticed that this happens on global scope. When switch to website scope the positions match as shown on the frontend of the website. When I switch positions the images switchs on the frontend too. 

@andimov Why isn't there an option to "use default" on this particular setting?

**Comment by hostep** [comment]
I'm pretty sure this was fixed in [Magento 2.1.6](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.6CE.html):

> Magento now displays imported product images in this order: first, the base image, then the additional images in the order in which they were listed in the CSV file. Previously, Magento displayed images in this unexpected order: first, an additional image, then the base image, and finally, all remaining additional images.

**Comment by Tristan-N** [comment]
@hostep It applies on the import. If I want to change the order of the images, does that mean I have to re-import the images? Changing the order in the backend doesn't affect the frontend when applied on global scope.

**Comment by hostep** [comment]
I have no idea, sorry! Please test it out yourself.
My comment was more directed to the original post, I assumed you were running into the exact same problem.

**Comment by Tristan-N** [comment]
@hostep No problem! I'll test it to see if it solved my (much related) issue as well. Thank you for you comment.
