### ISSUE TITLE
Paypal order confermation email not sent by customer associated with website but sent to paypal account holder (Paye).

### ISSUE THREAD

**Issue by kapilsinghathia** [magento/magento2#5435]
1. Add a product to cart and place order with paypal.
2. It will redirect you to paypal website, login with paypal and click pay now.
3. It will redirect you to order success screen and new order email is sent to paypal paye not to the customer email filled in checkout shipping step...
4. I have enabled cron jobs but still not working.

**Comment by YevSent** [comment]
Hi @kapilsinghathia, to help us investigate your issue, please, follow to [the reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) , it will significantly decrease our time for investigation.

**Comment by YevSent** [comment]
Closing this issue due to no response, please reopen when you have an update.

**Comment by luxwan13** [comment]
I just get the same problem. Order confirmation email should be sent to the email address used at checkout but it get sent to the Paypal account email address.

**Comment by dongnguyen-bi** [comment]
Got the same issue for Magento 2.1.2
At Checkout, the customer email entered was test-paypal-test@domain.com.
Then, on PayPal screen, it prompts for email address in Contact Details section. This was entered as customer@gmail.com

But then when this PayPal form is submitted and redirects to Success, the PayPal email gets assigned to the order and overrides the Magento customer email entered by the customer:

The PayPal email should never override the Magento email. The Paypal email is just a separate contact information field as part of their form.
Otherwise, why even ask for a Magento customer email? If it's just going to be overriden by PayPal. Customers are not going to expect that the email entered on PayPal form will actually override their Magento email address for their Magento account (it's not clear on PayPal that this is anything but a 'contact information field').

Please reopen this ticket as it's definitely sthing to be looked at. thanks

**Comment by panagiotis223** [comment]
Solution for version 2.3.4:
go to PayPal Express Checkout Settings

Advanced settings:
Require Customer's Billing Address: No
Billing Agreement Signup: Never
