### ISSUE TITLE
Magento2 REST API not adding new products

### ISSUE THREAD

**Issue by TanguyBusschaert** [magento/magento2#5448]
I try to add a new product trough the M2 REST API, but I somehow can't seem to get it to work.

Here are SS from my code and from the error:

CODE:

![ps1](https://cloud.githubusercontent.com/assets/18099315/16563334/b50d191c-4201-11e6-9a49-99ad6e823fc4.PNG)

ERROR: 

![ps2](https://cloud.githubusercontent.com/assets/18099315/16563338/b92aff14-4201-11e6-97d1-047f05969871.PNG)

Thanks !

**Comment by wozniakm** [comment]
You should check logs, exceptions in Magento contains lack of informations. I bet that you are trying to insert product with SKU or URL_KEY which already exists. Try with different data and let's see what happens.

**Comment by andimov** [comment]
@TanguyBusschaert 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
