### ISSUE TITLE
[CE 2.1.0] Security Issue in some blocks that use an on_click action.

### ISSUE THREAD

**Issue by spipu** [magento/magento2#5458]
example here : 

https://github.com/magento/magento2/blob/2.1/app/code/Magento/Cms/Block/Adminhtml/Block/Edit/DeleteButton.php#L26

The message given to the deleteConfirm function is not protected with a method like escapeHtml

lots of blocks have this issue, this is not the only one.

Laurent

**Comment by safwkhan** [comment]
This is a known issue on which we are working on. For internal reference: MAGETWO-46314.

**Comment by spipu** [comment]
The pb is stil there...

**Comment by magento-engcom-team** [comment]
@spipu, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment]
Hi @spipu

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@spipu thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
