### ISSUE TITLE
Place Order leads to 'Unable to place Order, Please Try Again'

### ISSUE THREAD

**Issue by darragh1001** [magento/magento2#5479]
## Steps to reproduce
1. Installed Magento 2.1
   Expected result
   --
   Add product to cart then checkout
## Actual result

I get the error: "'Unable to place Order, Please Try Again

No error shown in log, however using browser bugging I get this error:

'https://www.mywebsite.com/rest/dreamstream/V1/guest-carts/c558626bd1545832dd378f9b8f92f445/payment-information Failed to load resource: the server responded with a status of 400 (Bad Request)'

**Comment by sdzhepa** [comment]
Hello, @darragh1001 !

We tried to reproduce it with steps:

Preconditions:
- Magento2 CE is cloned "git clone https://github.com/magento/magento2"
- Then switch branch to 2.1, "git checkout -f 2.1"
- Install with all default settings(changes only in DB user name, DB name, Admin user name and password)
  Steps:
- Login as Admin user and create simple product
  (!) All magento settings in default state as after install:
- Only one shipping method is enabled by default: Flat Rate
- Only one payment solution is enabled by default: Check / Money order
- Go to Storefront as guest
- Add simple product to cart
- Go to Shopping Cart page
- Click "Proceed to Checkout" button
- Fill form for "Shipping Address" step with any valid data and select shipping solution in my case it's Flat Rate
- Click "Next" button
- On "Payment" i use "Check / Money order" and "My billing and shipping address are the same"
- Click "Place Order"

Result: Order is successfully placed

# 

It seems there is(are) other preconditions/steps/settings in Your case

Could You pls provide more detailed information?
- What additional settings do You change in Store>Configuration section(additional means in comparison with default as after install)
- What payment solution do You use(Stores>Configuration>Sales>Payment Method) it will be really helpful if You provide all settings for selected payment method.Probably screen shoot can make it in easy way
- Do You use some extensions?
- Also this error can appears if You use wrong credentials for payment solution(e.g. typo or wrong URLs)
- Also this error can appears if payment solution is not available at the moment(e.g. network configuration or firewall)
- Also some payment solution is not available for some addresses data(e.g. zip, state/province)

# 

quote: "No error shown in log"
Yes, there is issue with logging. This bug is in progress now and we provide fix for it ASAP

#

**Comment by Nerogee** [comment]
@sdzhepa Hi, I have the same problem. Fresh installed magento2.1, manual order is working fine. when checkout using Paypal, i found the invoice ID sent through paypal API is always 000000001. Do you think this is the cause? Thanks. This issue baffle me a week now.

**Comment by liquidia** [comment]
Same issue with stripe extension http://store.cryozonic.com/magento-2/stripe-payments.html(only tested in tested mode) 

Though stripe account shows successful transaction
**Firebug errors:**
`failed to load resource: the server responded with a status of 400 ()`
`rest/default/V1/guest-carts/85347343e5e98bfd2b34353439f01/payment-information 400 ()`
`.../rest/default/V1/guest-carts/854453794533s061de5e98bfd2b515449f01/payment-information 400 ()`

**Comment by Nerogee** [comment]
@sdzhepa please try to place a few of orders. I mixed actions of **paypal** checkout and **cash on delivery**. Doing this is because it's failed under some conditions. and I don't know what actually cause this.

**Comment by gabriel-sf** [comment]
Just to add a note (since I just fixed it after 3 full days), renaming the tables and removing the table prefix solved the 400 error for me using PayFlow Pro. --> Same thing as other posts using BrainTree

**Comment by sma09sjb** [comment]
Hi,

i have the same problem, when you say renaming the tables, which tables are you referring to? I'm experiencing this problem with both paypal express and the the stripe extension above. Nothing in the logs but i was initially getting an error as follows

https://github.com/magento/magento2/issues/5843
Exception: Wrong order ID: "000000005".

I changed the order increment because there was already an order in paypal with the same id 000000005,

On the frontend i get a number of different error messages, 

"Cannot initialize paypal express"

"Unable to place order. Please try again later"

"We can't create the order"

Any help on this would be greatly appreciated.

Kind regards,

Sophie

**Comment by gabriel-sf** [comment]
Hi @sma09sjb  this is what I did for removing the prefix on the tables.

http://magento.stackexchange.com/questions/103597/how-to-properly-remove-db-table-prefix-in-magento2/103599

**Comment by sma09sjb** [comment]
Hi, 

I don't have any table prefixes, so i'm not sure this will help me. Any other suggestions? I've updated this thread also 
https://github.com/magento/magento2/issues/5843#issuecomment-240076932

**Comment by quan-ntekka** [comment]
Maybe my little insight can help resolve this issue.  

I've created a custom braintree module that failed validation and Braintree returned the validation message, but it's not passed up the chain for Magento to parse, so you just get a generic "Unable to place order. Please try again later."

\Magento\Braintree\Gateway\Validator\GeneralResponseValidator line 36

To sum it all up, it was an incorrect configuration that failed validation.  Although, viewing the original validation message would have been less frustrating.

**Comment by alena-marchenko** [comment]
Hi @darragh1001 

According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
Issues described in comments are duplicate to #4580, #5714

**Comment by goeword** [comment]
Hi,

I am experiencing same issue on my checkout page here, it shows: An error occurred on the server. Please try to place the order again.

Google chrome browser is showing following message: 

/rest/english/V1/guest-carts/d78c1ba71d139a97e903304366505e3a/payment-information Failed to load resource: the server responded with a status of 400 (Bad Request)
VM5311:2 POST https://brands-hub.com/rest/english/V1/guest-carts/d78c1ba71d139a97e903304366505e3a/payment-information 400 (Bad Request)

Is there any solution for this? it has been bugging me for days now.

**Comment by goeword** [comment]
Hi,

I am experiencing same issue on my checkout page here, it shows: An error occurred on the server. Please try to place the order again.

Google chrome browser is showing following message:

/rest/english/V1/guest-carts/d78c1ba71d139a97e903304366505e3a/payment-information Failed to load resource: the server responded with a status of 400 (Bad Request)
VM5311:2 POST https://mydomain.com/rest/english/V1/guest-carts/d78c1ba71d139a97e903304366505e3a/payment-information 400 (Bad Request)

Is there any solution for this? it has been bugging me for days now.
