### ISSUE TITLE
Magento 2.0 - Credit Memo functionality not working

### ISSUE THREAD

**Issue by geeta-randev** [magento/magento2#5491]
Required info listed below... would be great to get some support. :)
## Steps to reproduce
1. Go to Sales > Orders > Select an Order > Select 'Invoice' > View Invoice > Select Credit Memo
2. Update qty to 0
3. Add amount in 'Adjustment Refund'
4. Click on 'Refund online' button
## Expected result
1. Credit memo is created & Customer is credited back the amount in the Adjustment Refund field
## Actual result
1. Error message appears - "Total must be a positive number'.
2. A new message also occurred today saying 'Quantities cannot be updated right now'

**Comment by geeta-randev** [comment]
Hi there - just wondered if there was any update to this bug? Are you able to replicate it?

Many thanks,
Geet

**Comment by mombrea** [comment]
I'd add to this report that it appears the amount to refund is not updated when you edit the 'Adjustment Refund' or 'Adjustment Fee' or 'Refund shipping' fields if you're not refunding an entire item from the order.

This issue persists in Magento CE 2.1.5

The workaround for now is to submit an offline refund and manually refund the proper amount in your payment processor.

**Comment by lfritsche** [comment]
@mombrea : I'm facing the same issue in 2.0.12.
Would be great to hear if there is any update on this topic. @veloraven 
We have multiple refunds per day which would be automatically processed, if there wouldn't be this bug.

**Comment by mombrea** [comment]
Bump to this issue, it turns out we're unable to process an Online Refund for any amount, including a full refund. It always results in an error "Invalid refund amount"

**Comment by oleg-onufer** [comment]
Hi @geeta-randev.
Thanks for reporting this issue.
Internal ticket MAGETWO-70353 was created.

**Comment by magento-engcom-team** [comment]
@geeta-randev, thank you for your report.
We've created internal ticket(s) MAGETWO-70353 to track progress on the issue.

**Comment by MikeParkin** [comment]
I'm working on it #distributed-cd

**Comment by MikeParkin** [comment]
I have tested this with the core PayPal Express implementation on 2.3-develop.

There are a few different issues raised in this ticket, so will try to address each of them separately:

1. Refunding an order with qty 0 and a adjustment refund

- Only positive numbers can be put into Adjustment Fee/refund (expected)
- Putting a value in Adjustment fee larger than the refund amount results in error "The credit memo's total must be positive." (expected)
- Putting a value in Adjustment refund too high errors "The most money available to refund is $xx.xx"

Apart from the above examples, I've not been able to replicate any other error. 

2. amount to refund is not updated when you edit the 'Adjustment Refund' or 'Adjustment Fee' or 'Refund shipping' fields

It's definitely correct that the GUI does not update dynamically (with Javascript) when the values are updated. I'm not sure why this is but this but it's not a bug, but definitely a cool feature - perhaps a separate issue would be good for that. 

Regarding actually behaviour of using the different values and them being pushed into the payment gateway, this is working fine for me. Again used PayPal Express on 2.3-develop. Tested multiple options with adjustment fees, adjustment amounts etc and everything worked as expected.

Perhaps this is being caused by a 3rd party extension? It would be worth testing the behaviour on a vanilla version of Magento to ensure this is not in user-land somewhere.

3. it turns out we're unable to process an Online Refund for any amount, including a full refund

I have been able to place multiple test orders and refunds, I don't think this is related to core.

**Comment by mombrea** [comment]
I can confirm that as of CE 2.2 we no longer experience this issue.

**Comment by jc-hurricane** [comment]
We are having the issues mentioned above -- in Magento CE 2.2.4 and Magento CE 2.2.5 - I am installing a vanilla copy and I will test and do a data dump. This is happening on multiple servers - dev, stage and production. Ugg 
 Using gene/Braintree 3.0.3

1.Refunding an order with qty 0 and a adjustment refund
•Only positive numbers can be put into Adjustment Fee/refund (expected)
•Putting a value in Adjustment fee larger than the refund amount results in error "The credit memo's total must be positive." (expected)
•Putting a value in Adjustment refund too high errors "The most money available to refund is $xx.xx"

Hopeful....

**Comment by chattertech** [comment]
Same issue here. CE 2.2.3. It happens with an Adjustment Refund when issuing either an Online Refund or Offline Refund. Also for the Refund button to be available a quantity of zero must be added to the items to refund (although it does not work in the end). 

I think it would be better to have zero items selected by default and then have to choose which items to refund. Less chance of refunding the whole order by mistake. 

Item or shipping refunds work as expected.

**Comment by paul-uz** [comment]
This is happening in Magento 2.3.5-p2

Order total was £46, (£36 for prodcuts, £10 for shipping)

Qtys to Return set to 0
Adjustment Refund set to £24.10
Adjustment Fee set to 0

Error states "The most money available to refund is £46.00."

Also, if Item qtys are changed first, updating totals for adjustment refund amount reset the qtys to return.
