### ISSUE TITLE
"Request does not match any route error" at Shipping method selection

### ISSUE THREAD

**Issue by vipin-eglobeits** [magento/magento2#5542]
##  **Steps to reproduce:**

Please note: This issue is not there always, it happens frequently but in most of the cases I wasn't able to recreate that twice in a row.
1. Install Magento 2.1.
2. Enable Shipping methods UPS, USPS and Fedex with live mode.
3. Go to shipping method selection area in checkout page.
4. Add address information
5. Choose any shipping method
6. Press "Next"
7. If you don't see any error message, repeat steps 3 through 6
## **Expected Result**

On clicking the "Next" button, it should initiate an ajax call to the rest api url **_rest/default/V1/guest-carts/:cartId/shipping-information_** and return a json object.
## **Actual result**

The rest api request **_rest/default/V1/guest-carts/:cartId/shipping-information_** is returning a 404 error with message "Request does not match any route".
## **Cause**

In vendor/magento/module-checkout/etc/webapi.xml

``` xml
<route url="/V1/guest-carts/:cartId/shipping-information" method="POST">
    <service class="Magento\Checkout\Api\GuestShippingInformationManagementInterface" method="saveAddressInformation"/>
    <resources>
    <resource ref="anonymous" />
    </resources>
</route>
```

As per the above route, the method saveShippingInformation will only called if the http request method is POST.

But here in my case, the http request getting in magento is "GET" and it is returning a 404 because there is no router to handle the request via GET.

I checked both browser console and the server access log and found a strange this that both recorded the request as a POST and not GET. So I suspect somewhere in magento, the method type is getting manipulated to GET even if the actual request type is POST.

I have confirmed this in my case by adding some logging to Magento\Webapi\Model\Rest\Config::getRestRoutes() method.
on line 131: 

``` php
if (strtoupper($httpMethod) == strtoupper($requestHttpMethod)) {
......
}
```

magento comparing the httpMethod defined in the route(webapi.xml) and the actual requestHttpMethod. The value of the variable `$requestHttpMethod` is "GET" in some cases, even if the actual method is POST.

Any help would be appreciated. 

Please feel free to ask if any questions.

**Comment by alwin-eglobeits** [comment]
Finding the same issue.Anyone please help

**Comment by vipin-eglobeits** [comment]
We checked with a custom URL in our website and post it with the same JSON array, then we can't able to trigger the problem at all. Based on this, it seems that something internal to Magento is terminating unexpectedly before any output is issued (thus causing the fcgi errors in the log). There aren't any errors in the log indicating PHP syntax errors or other consistent fatal errors that would indicate configuration problems.

**Comment by ghost** [comment]
Experiencing the same issue in version 2.0.7.
See http://magento.stackexchange.com/questions/136139/shipping-failure-404-or-400-on-magento-2 for full details.

**Comment by aaronsturm** [comment]
I had the same issue and it turned out that I was missing the SOAP PHP extension. Hopefully that helps someone else who comes across this issue.

**Comment by maheshwestagile** [comment]
Facing same issue 

rest/default/V1/carts/mine/shipping-information going to 500, Due to this i can't able to place order.

Anybody help.

**Comment by magento-engcom-team** [comment]
@vipin-eglobeits, thank you for your report.
We've created internal ticket(s) MAGETWO-83335 to track progress on the issue.

**Comment by TechnoBuddhist** [comment]
Can I just add a bit more info that might be helpful because it seems closely related if not part of the same issue. I'm on M2.2.3, no shipping extensions installed and I have a couple of stores on the same site. I only have Flat rate and Free shipping methods enabled. I have tested using both 1 page checkout and not.

I get the same "no route" error BUT only on the stores that aren't the 'Default Config' url store. For the stores that error they use "Request Method: OPTIONS", the working store has "Request Method: POST".

In my root .htaccess file I have "Access-Control-Allow-Methods: OPTIONS" but it doesn't help.

Error is "Status Code: 400 Bad Request" instead of 404 of OP and the console shows :- 
`Failed to load https://[store2_url]/rest/[store2_view_id]/V1/guest-carts/b8f4abe51125c17751b69c56455c663f/estimate-shipping-methods: Response for preflight has invalid HTTP status code 400.
`
If this isn't related please excuse me, but I'd like to know so I can raise the issue(I've searched extensively and can't find any help!). This is stopping us going live using Magento 2.

Many Thanks

**Comment by LewisSellers** [comment]
We had exactly the same issue on one of our stores. We traced the issue to a server rewrite which forced a trailing slash to URLs.

This rule was redirecting traffic to the http version of the end point and once removed, the checkout worked successfully.

**Comment by magento-engcom-team** [comment]
Hi @vipin-eglobeits

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@vipin-eglobeits, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by gustavoulyssea** [comment]
> We had exactly the same issue on one of our stores. We traced the issue to a server rewrite which forced a trailing slash to URLs.
> 
> This rule was redirecting traffic to the http version of the end point and once removed, the checkout worked successfully.

Hello,

I am facing the same issue on 2.3.2. Can you show me the changes you made to test on my installation ?

Thanks !

**Comment by adarshkhatri** [comment]
I am facing this error as well. In magneto 2.3.3 EE

**Comment by jproffer** [comment]
I am also experiencing this issue.  Magento 2.3.3 CE
