### ISSUE TITLE
Magento 2 Attribute set return empty array

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5556]
In [magento.stackexchange.com/ ](http://magento.stackexchange.com/questions/124781/magento-2-attribute-set-return-empty-array)is an a issue where DB query of attribute set attributes gets back only attribute_id and empty array what might be causing it in Magento 2.0.7 and 2.1.0?

**Comment by grasdaggel** [comment]
Maybe you link the thread here?

**Comment by andimov** [comment]
@Pistrik 
Link not works (404).
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by andimov** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
