### ISSUE TITLE
Why is assignData(..) in Adapter only accessible through observer ?

### ISSUE THREAD

**Issue by rikterbeek** [magento/magento2#5587]
The new way of using a payment methods is using the Adapter Facade class. Why do you need to add an observer to assignData instead of using Dependency Injection to do this like all other calls in this class ?

**Comment by YevSent** [comment]
Hi, @rikterbeek, can you clarify your question? All payment methods, which extends payment Adapter can replace or extend the `assignData` method. The order management system "directly" calls this method to set payment data.
How do you want to use DI to call this `assignData` method?

**Comment by rikterbeek** [comment]
@joni-jones,

In the new way you define the payment methods in the di.xml file. I would expect that I can define my assignData logic class in this di.xml file instead of creating a events.xml file. In this file I need to define an observer to set my variables in the additionalData of the payment method received from the front-end. It is much easier to keep the flow that is used for all other methods of the adapter class so you can just define it in one place.

Regards,
Rik
Adyen

**Comment by YevSent** [comment]
The current behaviour for `assignData` method is based on Magento events, as you can see this method uses event manager and that's why you need to describe observers in `events.xml` file. This allows extending payments methods by some specific data and base payment module doesn't know about any specific implementations.
As I understand, your purpose to move `assignData` method into separated class or service, which can be configured via `di.xml` for each payment implementation.
Actually, now I can't imagine any use cases, which will get some benefits, but if your integration extends payment method adapter, you can change `assignData` method to your custom usage.

**Comment by rikterbeek** [comment]
@joni-jones,

Observers have a downside that you don't have a clear view who is observing this call. I don't understand why assignData() is using observers and all other methods in this class are using dependency injection to declare the behaviour. I found it much more logical if it uses the executeCommand instead. I can extend the Adapter class and change this function but rather be consistent with the core code.

Regards,
Rik
Adyen

**Comment by dkvashninbay** [comment]
@rikterbeek Hi,

### Introduction

When we were implementing current behaviour for _assignData()_ method, the main idea was to move away from assignData at all, as method implementation depends on a concrete client(_Checkout/Quote_) implementation and data structure used to perform a transaction.

So the easiest way to substitute _assignData()_ call (which actually means _assignDataFromWebCheckoutQuote()_) with an event which gets triggered in a concrete client, and has event handlers (if applicable) in payment method implementation.

### Why is this needed right now?

_MethodInterface_ (and so _Adapter_ implementation) contains a huge amount of helper methods, which are not required for most of the payments or do no not cover the integration abilities.

**Example:**
- _sale()_ method is a required operation in most of the integrations but is not present in _MethodInterface_ which leads to implementation of two operations in _capture()_ method. 
  That's why we have _CommandManagerInterface_ which allows client to run any _Command_ by its type.

### The next step

Define _Payment Usage Context_ infrastructure which will be used by clients to run operations on Payment Methods.

**Example:**
- _Checkout_ has _Web Checkout_ context, which means that a specific flow/data structure should be processed by Payment implementation. This approach may be implemented in _CommandManager_  (and similar payment infrastructure interfaces, like _Configuration_) to load and execute _Command_ which is configured for input _Context_.
- The one would like to use Magento to capture transaction by its ID, received from third-party ERP system. This means that _Raw Transaction_ context (or similar) should be used to execute _capture_, which will not affect Magento Order management system and will perform a simple transaction operation.

### Summary
- assignData() depends on Checkout/Quote clients
- _assign_data_ event is the first step to make Payment integration independent from its client
- _assign_data-*_ event dispatch call will most likely be moved to client (Quote)
- Configuration via DI will be most likely possible in the future, but requires more time to think on extension points and usability.

**Comment by rikterbeek** [comment]
Hi @dkvashninbay,

Thanks for this detailed information. I hope it can be moved soon to the DI file so you have a clear overview what files the payment method is using during the checkout process.

Regards,
Rik
Adyen

**Comment by YevSent** [comment]
@rikterbeek, I'm thinking Dmitry posted an exhaustive answer to your question, so I'm close this issue. If you have, any questions, please, fill free to reopen it.
_UPD_ you can use [Magento2 PHPStorm](https://plugins.jetbrains.com/plugin/8024?pr=phpStorm) plugin, which allows navigating for all event observers.
