### ISSUE TITLE
Magento 2.0.7 Authorize.net Direct Post not redirecting to success page Multistore. For one store working fine other store its not. Just the loader icon is loading.

### ISSUE THREAD

**Issue by arunkrsigmainfo** [magento/magento2#5638]
## Steps to reproduce
1. Go to http://electricyogawholesale.sigmainfo.in
2. login in with "arun.kr@sigmainfo.net / arun@1234"
3. Add Any Product to cart
4. Proceed to checkout
5. Select Credit Card Authorize.net Direct Post
6. Enter the below details
   Card No : 4111111111111111
   Any Expiry Date 
   Any CVV
## Expected result
1. Redirect to Success Page
## Actual result
1. Loading Icon stays there.

[debug.txt](https://github.com/magento/magento2/files/363828/debug.txt)

**Comment by YevSent** [comment]
@arunkrsigmainfo, seems, your problem related to mixed content. If you open browser console on payment step and will try to place an order, you will see a list of js errors related to mixed content. The `https://test.authorize.net/gateway/transact.dll` works with `https`, but your site uses `http`.
Try to configure `https` on your site.

**Comment by arunkrsigmainfo** [comment]
@joni-jones : Thanks a lot for your prompt reply appreciate it.

I tried enabling the https but I am getting timeout error. Its a multistore and for one store http://electricyogaretail.sigmainfo.in with out https also its working fine but for the other store its not working. As per the console under network I see the system is not redirecting to "/authorizenet/directpost_payment/redirect/x_invoice_num....". Can you please let me know how to fix it.

**Comment by YevSent** [comment]
I've tried both your sites and js errors appear only on the first of them. As I see in the browser, the problems on the first site start after `transact.dll` request. I see a lot of js errors related to mixed content and nothing else, I suppose that's a main reason of problem and that's why you aren't redirected to `directpost_payment`.

Try to use xdebug to find the reason of errors causing.

**Comment by arunkrsigmainfo** [comment]
@joni-jones : I tried xdebug with phpstrom. I cant find any issues I am not even going into redirect.php everything is proper and as per the admin settings I have not all set any page to use secure ULR's always is_secure is null in both the cases. Then i thought its can be bacuse any conflict with theme or modules so I disabled everything and also I have installed fresh magento 2.0.7 and tried with multi store same issue. Also I have tried 2 different accounts of authorize.net for 2 stores I have and it shows the same issue.

Can someone help me in resolving the issue.

**Comment by YevSent** [comment]
I think, at first, you need to solve problem with js errors in browser console, because now, redirect can't be processed.

**Comment by gamort** [comment]
@arunkrsigmainfo do not use http, use https - directPost means precisely that, the payment is posted directly to https://test.authorize.net/gateway/transact.dll - your browser is not going to support mixing http and https on the same page.  Whether or not you get lucky with one site working and another site failing is irrelevant.   The configuration is not supported and against Authorize.net policies.

"Mixed Content: The page at 'https://test.authorize.net/gateway/transact.dll' was loaded over HTTPS, but requested an insecure stylesheet 'http://electricyogawholesale.sigmainfo.in/pub/static/frontend/Mgs/luxury/en_US/mage/calendar.css'. This request has been blocked; the content must be served over HTTPS."

Beyond that, once you actually are using https you can then review the actual errors if any.

**Comment by gamort** [comment]
See https://github.com/magento/magento2/issues/5642 for a detailed debugging steps.
In this case you have submitted the form to authorize.net and authorize.net was even able to get a response from your server.  It therefore returned something almost usable to the client.  However since this "almost usable" response contains a bunch of http links, and it is being loaded by an iframe that is posting to an https endpoint[transact.dll] your browser will quite rightly refuse to load any of the http links - again failing.

Always use https for submitting payments.  LetsEncrypt will provide you with a valid short term ssl certificate at no cost: https://letsencrypt.org/

**Comment by alena-marchenko** [comment]
Closing as duplicate to #5642
