### ISSUE TITLE
Magento 2.1 fresh Install Missing "MSRP" from Advanced Pricing

### ISSUE THREAD

**Issue by acidreian666** [magento/magento2#5662]
## Steps to reproduce
1. Install Magento 2.1.zip from magento.com
2. Add Click Add Simple Product.
3. Click Advanced Pricing.
## Expected result
1. Display a Textbox for MSRP.
2. Special Price 
3. Special Price From
4. Cost
5. Tier Price
## 
## Actual result
1. Special Price 
2. Special Price From
3. Cost
4. Tier Price

Missing MSRP input Textbox.
changing location of MSRP under Default Attribute set from Advanced Pricing to something else End result nothing still not showing up under any Group within "Add New Product"

Sorry if this is a duplicate I searched but i feel I'm the only person experiencing this.

**Comment by rganin** [comment]
To make it visible please enable MAP feature  in System -> Configuration -> Sales -> Minimum Advertised Price

**Comment by acidreian666** [comment]
So I enabled MAP feature in System -> Configuration -> Sales -> Minimum Advertised Price.
After reviewing how they have implemented this feature it seems cool but to my knowledge its an incorrect.

I have a Massive database list of products with this prices.
1. MSRP = manufacturer's suggested retail price (Also known as Retail price.)
2. Cost = My Cost Of Product
3. MAP= Minimum Advertised Price
4. Price = The Price I'm Selling the product for.

As you see there is a difference between MSRP & MAP. Sites like Amazon or Ebay sell products for MAP or below MAP pricing. Sites like Bestbuy or NewEgg sell products for MSRP & MAP.

MSRP should be where you enter full retail price and with frontend displaying a MSRP price with a line through it and a % showing 10% or 30% off retail. AKA 30% off retail (MSRP) usually is the MAP price.

The use of this MSRP function to my knowledge is incorrect. For people like me whom have products that sell for Full Retail (MSRP) and products that only sell for minimum advertised price (MAP) also know as what is the min price you can sell for without breaking the sale policy for most vendors.

Correct me if I'm wrong but I cannot be the only person with the point of view of how things work.

**Comment by asemenenko** [comment]
@acidreian666 i agree that we need to have an ability to specify both MSRP price and MAP price on the admin product edit page. For now if there is a need to show MAP lightbox with crossed MSRP price - merchant needs to specify MSRP price for the product. 
I added this to the backlog.

**Comment by nikoelgatito** [comment]
# MSRP VS MAP

As we are also experiencing issues related to the new "MSRP/MAP" in Magento 2, I would like to add some facts.

First of all, this was a huge mistake - MSRP and MAP are very different. The only part they have in common is that they are both provided by the manufacturer.

These are both descriptions following my personal knowledge, which is how it actually is.

**MSRP (Manufacturer's Suggested Retail Price)**
A _suggested_ price that has been set by the manufacturer to identify the resale value of its product in a specific market. This usually indicates the highest price (value) at which a product can be sold and most retailers will sell below that price. Most regular prices or any defined pricing subcategories in different markets will base their calculation on this price. These rarely change, mostly only when there is market/dollar fluctuations or when a specific product depreciates.
-Suggested
-Highest selling price
-Helps retailer determining the selling price

**MAP (Minimum Advertised Price)**
An _imposed_ lower price limit which depending on the manufacturer's policy will prevent the retailer to advertise or even sell a product below the set MAP. These are more often changed by the manufacturer to control the saleability/profitability balance of their products while preventing a loss of value due to unfair, overly aggressive and destructive pricing/advertising strategies. This allows to stabilize the market for their products and it also prevents ruining the brand image. These policies can be specific and can apply to one or both online and brick and mortar commerce.
-Imposed
-Lowest selling price
-Prevents retailer pricing abuse

**For more details, both are described in Wikipedia**
[https://en.wikipedia.org/wiki/List_price](https://en.wikipedia.org/wiki/List_price)

As many other retailers and suppliers, we do rely on these distinct functionnalities to operate our businesses and I'm affraid that this huge mistake will prevent us from switching to the new Magento 2 platform. I think that in 2016 both MSRP and MAP should be well understood by and completely integrated into any reliable shopping cart.

We hope that this will soon get resolved.

**Comment by acidreian666** [comment]
@nikoelgatito +1 thanks for support.

**Comment by iknowtech** [comment]
I just setup Magento for the first time, to offer it as an option to client for store they want developed.    This is a Distributor who would be selling at wholesale, and they need to be able to show the MAP pricing and MSRP pricing separately, as they need this information to visible to the buyers who will be reselling the product.    

This definitely seems like a major oversight, and a clear misunderstanding of what MAP and MSRP are?   Seems hard to imagine that would even be issue with a Cart Development company?   

My first time integrating Magento and presenting it as an option, and this is a non starter for me right out of the box.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-2-1-fresh-Install-Missing-quot-MSRP-quot-from-Advanced/idi-p/45205).

**Comment by krejcif** [comment]
Hi, why this has been closed, please? 

It seems like bug, not improvement.

MSRP should be visible without enabled MAP. 

Thanks for explanation.

**Comment by maderlock** [comment]
I think their thought is that although this is incorrect business logic, the functionality works correctly - only under their faulty assumptions, but in that sense not a code bug.

**Comment by iknowtech** [comment]
No it does not work correctly.   For businesses that need to list an actual Sale price, a MAP price that that a reseller buyer must adhere to, as well as an MSRP price that the reseller buyer can have for reference to post on their own site and price lists.     Many people needing a MAP pricing field will likely be selling to other resellers.

**Comment by maderlock** [comment]
I agree about the need for the functionality. Would you agree that the current functionality is misnamed, and there is a need for a separate MSRP price?

**Comment by spyrule** [comment]
MSRP should be completely separated from MAP pricing. Many people display MSRP without the need to hide actual product prices.

**Comment by nikoelgatito** [comment]
For our part if Magento does not decide to do it, that was our first idea. Simply modifying the Msrp module renaming everything so that the module is called Map and is using an attribute with "map" as code instead of "msrp". It shouldn't be that hard to implement, and if Magento is finally willing to make things right then they may include an update script for those already using the "msrp" attribute as "map" to update the database switching everything to "map".

We still do not understand how this misconception happened at the first place and howcome this isn't fixed yet.

Community members might have to fix it directly or release a custom patch as unfortunately things are not moving forward quickly on the matter.

**IMPORTANT NOTE:** 
Magento transfered this tread in the Magento Forum, section: Magento 2 Feature Requests and Improvements a while ago. Everything will be followed up regarding this issue on the following page:

[Magento 2.1 fresh Install Missing "MSRP" from Advanced Pricing](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-2-1-fresh-Install-Missing-quot-MSRP-quot-from-Advanced/idi-p/45205)

**Give Kudos, rate the request and comment, the more attention is given the sooner they may react!**

**Comment by hamdrew** [comment]
@magexo This issue was closed because it was moved to their feature request forum: 
 [Magento 2.1 fresh Install Missing "MSRP" from Advanced Pricing](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Magento-2-1-fresh-Install-Missing-quot-MSRP-quot-from-Advanced/idi-p/45205)

I encourage you to vote on the issue and provide any feedback in the forum!

**Comment by rob-gonz** [comment]
@hamdrew , @piotrekkaminski,  can we get this ticket re-opened?  Please review @nikoelgatito post.  He explained it very well.  The current functionality does not meet industry standards for the terms MAP and MSRP.    This directly affects how we market to consumers on product pages and listings.  We are having to create our own custom functionality as a workaround.

Since the post was copied the forums it has lost all visibility.  Those forums are not traversed nearly as much like Github.     Thank you.

**Comment by techzilla** [comment]
Can we at least get the current functionality properly renamed?  That definitely is wrong, and then only the MSRP would be a new feature. As it stands now, having a feature using another feature's name constitutes a barrier.   Rename everything msrp to map, and then this bug would be resolved, and the msrp can be a new feature request.

**Comment by rob-gonz** [comment]
Bump @hamdrew, @piotrekkaminski , @rganin This is not fixed. The logic is still flawed in 2.2.3.
