### ISSUE TITLE
In Magento 2.1 sitemap, product's URL does not include its category!

### ISSUE THREAD

**Issue by Whaaaaat** [magento/magento2#5674]
Although configured in Stores -> Configuration -> Catalog -> XML Sitemap and Stores -> Configuration -> Catalog -> catalog, product's URL does not include its category in Magento 2.1 sitemap!

For example if the product URL is http://www.niceexample.com/category/product1.html
you will find it in sitemap as: http://www.niceexample.com/product1.html

**I think functions generating sitemaps needs more improvement and development!**

**Comment by HRR1337** [comment]
Its linking to canonical url as it should. Not a bug, its a feature!

**Comment by Whaaaaat** [comment]
What is the benifet of this feature?
Can I disable it?

**Comment by andimov** [comment]
@Whaaaaat 

Thanks for reporting!
To allow us to research the issue, please, format description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by AirmanAJK** [comment]
The sitemap code now ads the query filter of "AND url_rewrite.metadata IS NULL" in the class \Magento\Sitemap\Model\ResourceModel\Catalog\Product inside the function getCollection()

Previous versions of Magento did not do this, which is why it randomly ended up with a url_rewrite record, typically one for a category.

The previous commenter is correct in that you DEFINITELY want the canonical version of the url in your sitemap. An individual product can have multiple categories associated with it, and Magento has no way of determining which one to consistently use since one is just as valid as the other.

Before I upgraded to 2.1.0, I had a custom module which added the filter to use canonical only. I was happy to see that they corrected it in the newer release.

The feature you're asking for would be equivalent to asking for the sitemap to randomly use different urls for the same product each time it's generated. Google would not be happy.

If you want to convey category information to Google or any other crawler, use proper meta data around your breadcrumbs on each page. You don't need the category urls in the sitemap.

**Comment by wert2all** [comment]
@Whaaaaat  Thanks for reporting. Internal issue MAGETWO-56474 was created.

**Comment by magento-engcom-team** [comment]
@Whaaaaat, thank you for your report.
We've created internal ticket(s) MAGETWO-56474 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @Whaaaaat 
This is not a bug.
If we do this, that the sitemap may contain several urls for one product: for each linked categories.
And this mean that several urls will download same content. 
The reason why this settings is ignored is exactly to avoid duplication or ambiguity.
And this is the way it was in M1.
