### ISSUE TITLE
Product attribute accepted via admin interface but cannot relate via import csv

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#5690]
Steps to reproduce
1. Install Magento from `develop` branch.
2. Create a dropdown attribute with values: '5µ, 10µ, 15µ...'
3. Attempt to add those accepted attribute values with attribute to a product via csv.

Expected result
1. Product given attribute and attribute value correctly recognised as it is accepted in interface.

Actual result
1. Value not recognised.

I believe this is due to HTML encoding or URL encoding, or whatever encoding is used to process the spreadsheet, though I may be mistaken.

**Comment by veloraven** [comment]
@LiamFielding thank you for your report.
Please provide more detailed steps. 
As I was not able to reproduce this issue on the develop branch. I successfully imported the product with custom attribute with specified value.

**Comment by LiamFielding** [comment]
It is a problem with the micron/other symbols. They have to match but the importer parses the value so it no longer matches the attribute label.

**Comment by veloraven** [comment]
@LiamFielding I used exactly the same symbol you provided. And I had no problems during import.
Could you please update your develop branch and confirm that the issue is still there?
And if it is, I still need more detailed steps including information, how did you create a file for import? 
Maybe list of some other symbols you have problems with.
Please also provide information about your environment: OS, PHP, MySQL, web browser versions.
And specify if it was clear install or upgrade from some previous version.

**Comment by LiamFielding** [comment]
Your attribute say "Measurement X" has a value in the attribute dropdown (admin) of 5µ what value did you use in your spreadsheet to give the product this attribute value option?

**Comment by magento-engcom-team** [comment]
@LiamFielding, thank you for your report.
We've created internal ticket(s) MAGETWO-82088 to track progress on the issue.

**Comment by piotrekkaminski** [comment]
This issue was moved to magento-engcom/import-export-improvements#56
