### ISSUE TITLE
How do I: Bug tracking for Magento 1 + ideas for Magento 2

### ISSUE THREAD

**Issue by seansan** [magento/magento2#572]
Hi, probably this is not the place. But - this is my/our best hint of getting an answer

_*\* Where do I log bugs or ideas for Magento 1?_
It seems the list http://www.magentocommerce.com/bug-tracking/list is dead. And nobody responds,  .... so, where can we really contribute bugs or ideas for Magento 1?

_*\* Then, many bugs or ideas also affect Magento 2 - where do I log those?_
Many small configuration or operational issues that we see in Magento 1 we log at the above URL. But if nobody is watching this -> it will also never reach Magento 2 .... so, do I then log these more configuration settings/operational problems we see also _here_ in github or where?

ps. If http://www.magentocommerce.com/bug-tracking/list is nog longer used. can someone then please just close it. I tink this is even better than creating an expectation

(sorry for those who are aggitated for me logging it here - but we love Magento and want to contribute)

**Comment by seansan** [comment]
@verklov @piotrekkaminski May I respond to your comment in May 2014 

"Our team is currently finalizing their efforts in the field and they promised to introduce the new system. I believe there will be a blog post or other announcement when the system will finally go live. "

When  I look @ http://www.magentocommerce.com/bug-tracking/list/index/page/10 => even months back all bugs have the status open. 

Why not move Magento 1.9.x to a public github repository too? I don't understand why one would have a github repo and the other not ... 

I think my question remains open: how and where can we log issues and suggest pull requests to the code directly to help fix issues? Where one can comment and collaborate?

I hope it helps

thanks guys!

**Comment by magento-engcom-team** [comment]
Hi @seansan. Thank you for your report. 
The issue has been fixed in magento/magento2#25349 by @konarshankar07 in 2.4-develop branch
Related commit(s):
 - [a4a2ff7d2444fe24bf13f022b9748ddb961a095c](https://github.com/magento/magento2/commit/a4a2ff7d2444fe24bf13f022b9748ddb961a095c)
 - [c42d48a44829ad91024e2c61f14fa9d5e9fe9731](https://github.com/magento/magento2/commit/c42d48a44829ad91024e2c61f14fa9d5e9fe9731)
 - [b8e0c42cba3db9a4b5005fe7e0d078891ad5b0ce](https://github.com/magento/magento2/commit/b8e0c42cba3db9a4b5005fe7e0d078891ad5b0ce)
 - [d6995f7595363e896415f06c1228ffc2f2f719ff](https://github.com/magento/magento2/commit/d6995f7595363e896415f06c1228ffc2f2f719ff)
 - [c9f9757fe815ac1e390b9943df5c5a046eb62491](https://github.com/magento/magento2/commit/c9f9757fe815ac1e390b9943df5c5a046eb62491)
 - [240fc19617589cecc528799824ad1b8378558dd4](https://github.com/magento/magento2/commit/240fc19617589cecc528799824ad1b8378558dd4)
 - [da6b3612ff51e52caf4bcf7dccf7690cd79d9cd4](https://github.com/magento/magento2/commit/da6b3612ff51e52caf4bcf7dccf7690cd79d9cd4)
 - [db51191275245123b84d772a80820454a2cb5631](https://github.com/magento/magento2/commit/db51191275245123b84d772a80820454a2cb5631)
 - [3e25bd1385e9287f0ba5d5c6579a2f65ade3d2b4](https://github.com/magento/magento2/commit/3e25bd1385e9287f0ba5d5c6579a2f65ade3d2b4)
 - [633ea172803d6d81b823f8791226bf1d0e516957](https://github.com/magento/magento2/commit/633ea172803d6d81b823f8791226bf1d0e516957)
 - [5d676b60bbcc8a03fe50bc417c5f17b7e62a99d3](https://github.com/magento/magento2/commit/5d676b60bbcc8a03fe50bc417c5f17b7e62a99d3)
 - [997959f2f081f844b798ccae31cc54fa0833ca60](https://github.com/magento/magento2/commit/997959f2f081f844b798ccae31cc54fa0833ca60)
 - [d3aa9320e82eb9f1f6ee903c1bef0dd4e2983b3e](https://github.com/magento/magento2/commit/d3aa9320e82eb9f1f6ee903c1bef0dd4e2983b3e)
 - [65b2afeeea0801291a924eb64618650faa8d2e93](https://github.com/magento/magento2/commit/65b2afeeea0801291a924eb64618650faa8d2e93)
 - [727679d3c9ee2540cb707fe1431d25b7fbae7a34](https://github.com/magento/magento2/commit/727679d3c9ee2540cb707fe1431d25b7fbae7a34)
 - [b41ea13a925eda843277dc9960071f00207b329e](https://github.com/magento/magento2/commit/b41ea13a925eda843277dc9960071f00207b329e)
 - [552eaafd5029a982c5243670e71d618467602319](https://github.com/magento/magento2/commit/552eaafd5029a982c5243670e71d618467602319)
 - [ce6614ef0e813e2d2ae8226c715d8d0a5cfb4d1a](https://github.com/magento/magento2/commit/ce6614ef0e813e2d2ae8226c715d8d0a5cfb4d1a)
 - [c14fbedfac2559ae05767e98afcd7d274ec5da48](https://github.com/magento/magento2/commit/c14fbedfac2559ae05767e98afcd7d274ec5da48)
 - [257eb00a4400dbddf7e0a6774fc927eb198d8381](https://github.com/magento/magento2/commit/257eb00a4400dbddf7e0a6774fc927eb198d8381)
 - [b1ab6a97c8354b3ef1c80aac379140fe356898e4](https://github.com/magento/magento2/commit/b1ab6a97c8354b3ef1c80aac379140fe356898e4)
 - [53fe8eecbd87c7a0e3924e81cd9d77e9300eb9d4](https://github.com/magento/magento2/commit/53fe8eecbd87c7a0e3924e81cd9d77e9300eb9d4)
 - [437fab3b783eb68460d283214f41f6b9d9fcb49f](https://github.com/magento/magento2/commit/437fab3b783eb68460d283214f41f6b9d9fcb49f)

The fix will be available with the upcoming 2.4.0 release.
