### ISSUE TITLE
Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by steadweb** [magento/magento2#574]
Installed a clean version on our local server, both frontend and backend produce this error:

Maximum function nesting level of '100' reached, aborting! in /mnt/pdrive/Clients/magento2/site/lib/Zend/Code/Generator/DocBlock/Tag.php on line 96

Currently checkout out to `f78121f (HEAD, origin/master, origin/HEAD, master) 2.0.0.0-dev78`

Running:

PHP 5.4.25
MySQL 5.0.77
Apache/2.2.3

**Comment by magento-engcom-team** [comment]
Hi @steadweb. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#694 by @osrecio in 2.3-develop branch
Related commit(s):
 - [55ad3d0a55492871cedb0858288b97a93eb05158](https://github.com/magento/magento2/commit/55ad3d0a55492871cedb0858288b97a93eb05158)

The fix will be available with the upcoming 2.3.3 release.
