### ISSUE TITLE
Magento 2 has been stuck when create sub category

### ISSUE THREAD

**Issue by love1106** [magento/magento2#5772]
![image](https://cloud.githubusercontent.com/assets/7650991/17074702/e2e7ba08-50a8-11e6-9cb3-37e322c845fa.png)

**Comment by andimov** [comment]
@love1106 
Thanks for reporting!

Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
