### ISSUE TITLE
Tier price and custom options give bad results

### ISSUE THREAD

**Issue by yangsystem** [magento/magento2#5774]
### Steps to reproduce
1. Create a product with base price
   ![image](https://cloud.githubusercontent.com/assets/6049104/17077997/9538bcac-50ef-11e6-85bc-23a366bf4ae4.png)
2. Create a tier price
   ![image](https://cloud.githubusercontent.com/assets/6049104/17078048/cf652b58-50f0-11e6-994a-c939a8162c6f.png)
3. Create 2 custom options
   ![image](https://cloud.githubusercontent.com/assets/6049104/17078003/d00b405c-50ef-11e6-8ce1-daa565cbd24d.png)
   and
   ![image](https://cloud.githubusercontent.com/assets/6049104/17078004/d88e9198-50ef-11e6-9fbb-2624a90e3187.png)

The logic is that the client should send me a design file and I will engrave a pen with his design.
![image](https://cloud.githubusercontent.com/assets/6049104/17078104/e1bced62-50f1-11e6-9c36-0687a58713e6.png)

I have special prices for re-sellers.
### Expected result

If I am logged as a re-seller I have the right price for the product but the wrong price for the special option (the option specify that if you want also engrave on the back of the pen you should pay for an extra engrave). In this case the price for "Personalizare pe ambele fete + **12,00 RON**" should be "Personalizare pe ambele fete + **0,30 RON**"
![image](https://cloud.githubusercontent.com/assets/6049104/17078088/8693beac-50f1-11e6-80fe-9249f3beff7d.png)

The price is OK in shopping cart with the +100% if you want both sides engraved in both cases "general" and "re-seller" tier price
![image](https://cloud.githubusercontent.com/assets/6049104/17078129/ef74c5be-50f2-11e6-8203-afc3f386ceed.png)

**Comment by oserediuk** [comment]
Hello! Please, provide your code base version

**Comment by yangsystem** [comment]
2.1.0

![image](https://cloud.githubusercontent.com/assets/6049104/17179820/352532e6-5423-11e6-8c71-78b348510b73.png)

**Comment by SilvanLaroo** [comment]
I also face this issue, is there already a fix?

**Comment by yangsystem** [comment]
I don't know. I have purchased 2 extensions one for formula calculation and one for advanced product options and I do my work with them.

**Comment by SilvanLaroo** [comment]
I see. I think the problem is here: https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product/Option/Value.php#L227

This function uses the function getFinalPrice() that does not use the tier prices.

**Comment by IlnitskiyArtem** [comment]
@yangsystem Thanks for reporting this issue. 
I've linked this GitHub issue to internal ticket MAGETWO-70082

**Comment by magento-engcom-team** [comment]
@yangsystem, thank you for your report.
We've created internal ticket(s) MAGETWO-70082 to track progress on the issue.

**Comment by marinagociu** [comment]
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment]
Hi @yangsystem 
The issue has been fixed and delivered in 2.2-develop branch. Will be available with upcoming patch release.

**Comment by magento-engcom-team** [comment]
Hi @yangsystem. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1359 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 1db3f8f6a336026d4a4493c8ba8d3e165ade66d8
 - 412d2287ee5a1a9620fb2a256bab562bdd10fe49
 - 02620b09456d77408ccbbd6a6b61a7b7ebcf73fa
 - 57c5d8a819e403905bd4d5419564d184712bc142
 - 94a3f0346ea086626d8b11c08fd397b11a570caa
 - 0d557dc99c15c6638e1c894ce46cb681a74b8912
 - 48baf590f86590c44bba81a9d5303902aed9d8d7
 - dc3bb78962c4522eb5df8a1a8f40c3bbe2b623fc
 - 0ab45334ef4d44e55c9f84f9c6e4b6a9e08e9237
 - 00f64b077ce00e55216e6ea9fb39071dc74b51a1
 - 440a1b5f9e6309fa87790a5f5b7d1b8fd7ffa53d
 - 4ed8f5b65d5d1779522653102120917c5f9578be
 - 656eeb5587eb1baebaffdc8ba68f1028afda8910
 - fd2f731f7efc4a2cec9e03f8de88bf39c0988829
 - 2c1a23faa60805bd63ff62216309d57a052612d1
 - f7ff71a92bcf56679b82c22549244e1adb9f4ed2
 - ac9bcfa15b1b0b98f9cb3851f4d9b56e18ede89b
 - 55debe0c2b514e37271ed6edf20b95fec6cc41c9
 - 349508628dc1c4334e13b3541227505e26c93c64
 - d678f1568b6e2d30c6d651dd3da02e0f3512353e
 - bf8ee3089f005e267f0b14cf81b14e9a3ee26986
 - 335c91c07dde6f90309f11cf0efcbd9127630955
 - c5a823f95161f7c13fb0947abb445fdc9e9a620a
 - 696a5a575513bb87c47ffc15a571034b0b91d7ae

The fix will be available with the upcoming 2.3.0 release.
