### ISSUE TITLE
Quick Search feature in Admin is not working properly when choosing in Products

### ISSUE THREAD

**Issue by addison74** [magento/magento2#5785]
Please see the image bellow:

![quick_search](https://cloud.githubusercontent.com/assets/8360474/17086197/b9ce1fca-51f4-11e6-8ec8-efaf89bb4b22.jpg)

Search in Admin for emma leggings then choose in Products, in Orders, in Customers, in Pages. All are providing results correctly, except in Products. If you choose "emma leggings" in Products you will get all products listed. This option has an issue providing correct results.

**Comment by choukalos** [comment]
Tracked as (MAGETWO-36855) internally when we apply the new enhanced data grid to products.  Sales, Customer and CMS are the new enhanced data grids.

**Comment by magento-engcom-team** [comment]
Hi @ADDISON74 
Issue seems to be already fixed in the `2.3.0-dev` with the PR magento/magento2#10089.
We will consider backporting it into previous versions.

**Comment by magento-engcom-team** [comment]
@ADDISON74, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @ADDISON74, The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
