### ISSUE TITLE
Categories Moving Error, Magento 2

### ISSUE THREAD

**Issue by nomuprive** [magento/magento2#5792]
We been having issue moving and re-arranging Magento 2 categories. Each time we try to move a category we get the error, "There was a category move error. URL key for specified store already exists." Please check error screenshot here... http://prntscr.com/bx8zir

Thanks!

**Comment by oserediuk** [comment]
Hello! Please, add code base version which you use

**Comment by nomuprive** [comment]
Hello @oserediuk is Magento 2, Version 2.1

**Comment by nomuprive** [comment]
@oserediuk is that a fix? Couldn't find it? A little explanation would help. Thanks!

**Comment by oserediuk** [comment]
@williambize What do you mean?

**Comment by nomuprive** [comment]
@oserediuk I meant did you find a fix for the issue?

**Comment by oserediuk** [comment]
@williambize This issue reproduce on CE or EE version?

**Comment by nomuprive** [comment]
@oserediuk CE version (2.1) Error Screenshot here http://prnt.sc/bx8zir

**Comment by nomuprive** [comment]
@oserediuk I have tried using the fix here but not working. :) https://github.com/magento/magento2/commit/8b2eb5e387d2272cf25baeb7647f88f5fadc10c5

**Comment by nmallepally** [comment]
I have the same error as well, When i just change the url of the category. It says URL key already exists.

**Comment by nmallepally** [comment]
@oserediuk Which version are you using?, im using 2.1 updated from 2.0.7, I dont see the same code to fix from 8b2eb5e

**Comment by TClilMouse** [comment]
I have the same error as well - 2.1

**Comment by nmallepally** [comment]
Any update on the issue?? @oserediuk

**Comment by AVoskoboinikov** [comment]
Hi guys,

Thanks for reporting but could you please provide detailed steps to reproduce this issue? I've tried to reproduce it in clean 2.1.1 magento installation with sample data, but without any success. So, could you help me with that?

Thanks!

**Comment by andimov** [comment]
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Comment by jimul** [comment]
Facing same issue in EE 2.1.5

**Comment by smoliakoff** [comment]
I confirm, is still present in CE 2.1.5. Let's create the module itself correct? Magento Developers apparently do not want to fix it ever. ))

I do not know exactly how to reproduce it, but the fact is that the renamed categories in the urlrewrite table still have old records. As it turned out that the two categories had the same urlkey and when I move one category I  goted error.

**Comment by jimul** [comment]
I have dirty workaround to fix this issue. 

Under classs Magento\UrlRewrite\Model\Storage\DbStorage function doReplace, filtered duplicate urls for stores., Replace function doReplace with below code. 

```
protected function doReplace($urls)
    {
        foreach ($this->createFilterDataBasedOnUrls($urls) as $type => $urlData) {
            $urlData[UrlRewrite::ENTITY_TYPE] = $type;
            $this->deleteByData($urlData);
        }
        $data = [];
        $stores=[];
        foreach ($urls as $url) {
            $urlData=$url->toArray();
            if(!isset($stores['store_id'])){
                $stores['store_id']=[];
            }
            if(!in_array($urlData['request_path'], $stores['store_id'])){
                $stores['store_id'][]=$urlData['request_path'];
                $data[] = $urlData;
            }
           
        }
        $this->insertMultiple($data);
    }
```

I am not sure above code may impact any other area.

**Comment by orlangur** [comment]
@jimul,
> filtered duplicate urls for stores

It will make some products/categories inaccessible in some stores (having URLs like `/category/view/123` instead of SEO-friendly ones).

**Comment by jimul** [comment]
@orlangur,

Request path should be unique per store so I think it will also work in case of non SEO friendly URL's as well, but not sure, need to try once.

**Comment by orlangur** [comment]
Yes it should, but if you have a collision for some store with such patch you will just ignore one of the products.

Let's say we have Product1 with ID=1, URL Key="test" and merchant changes Product2 with ID=2 so that URL Key = "test".

**Before patch**
Merchant observes error, fixes URL Key and have both products properly accessible.

**After patch**
No error occurs, Product1 is properly accessible while Product2 URL looks like `/product/view/2/` which is not SEO-friendly.

**Comment by jimul** [comment]
What I observed is $data contains request_path(without category url) multiple times for same product, same store, because products was assigned under multiple categories. I had total 48 products under the category for which this issue was occurring. After applied this change and saved category, I have confirmed all 48 products have a proper urls in url_rewrite table.

**Comment by onepack** [comment]
Same here on a 2.3 shop. It has migrated data from M1.
