### ISSUE TITLE
[2.1.0-ce] Role Resources not selectable 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5803]
### Preconditions
1. CE 2.1.0, php 7.07, ubuntu 14.04, either Firefox or Safari latest stable version.
### Steps to reproduce

1. Login to Admin
2. Create and save a new user role.
3. Attempt to select appropriate resources for that role
### Expected result
1. Role resources should be displayed and selectable and savable.
### Actual result
1. No role resources are shown, selectable, or savable.

![clip_3](https://cloud.githubusercontent.com/assets/5779763/17121423/48c04f9c-5299-11e6-9874-00c3a53b8c81.png)

**Comment by luantmindarc** [comment]
You can check file acl.xml in your module

**Comment by robkor** [comment]
Exact the same issue in our Magento 2.1.0-CE. Upgraded from 2.0.7-CE.

I need to create a new role for a api-user to be used for a shipment interface. But first I have to correct an xml file? Where is that file to be found? In which module? What is the path?

Please enlighten me.

**Comment by TommyKolkman** [comment]
I need this too. Occurs in 2.1.1 as well.

**Comment by robkor** [comment]
Hi @TommyKolkman 

On a fresh install of 2.1.0-CE the role resources are correctly shown. The problem may be caused by a theme or module that is installed. 

I used [article #132329](http://magento.stackexchange.com/questions/132329/magento-2-1-0-roles-resource-tree-not-showing) on stackexchange to solve the issue for now.

In the file **module_user/Block/Role/Tab/Edit.php**, in the function `getTree()` I changed:
`isset($resources[1]['children']) ? $resources[1]['children']`
into:
`isset($resources[2]['children']) ? $resources[2]['children']`
and the resource tree is shown again.

**Comment by niclashoyer** [comment]
Can confirm this issue on an installation of 2.1.2-CE after Upgrade from 2.0.7 and 2.1.1. The temporary workaround from @robkor works.

**Comment by pguedesbr** [comment]
I had the same issue with the resources tree rendering blank, and I've found out that the issue was with the acl.xml file of one of the installed modules (it can also be from a theme).

In my case, the module's resources were not inside the Magento_Backend::admin resource tag:

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
<acl>
    <resources>
        <resource id="UOL_PagSeguro::Conciliation" title="Conciliation" sortOrder="10" />
        <resource id="UOL_PagSeguro::Abandoned" title="Abandoned" sortOrder="20" />
        <resource id="UOL_PagSeguro::Cancellation" title="Cancellation" sortOrder="30" />
        <resource id="UOL_PagSeguro::Refund" title="Refund" sortOrder="40" />
        <resource id="UOL_PagSeguro::Credentials" title="Credentials" sortOrder="50" />
    </resources>
</acl>
</config>
```
After making the changes such as placing the resources inside a group resource tag (one for all the module related resources), and also placing it inside the Magento_Backend::admin tag, fixed the problem.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Acl/etc/acl.xsd">
<acl>
    <resources>
        <resource id="Magento_Backend::admin">
            <resource id="UOL_PagSeguro::admin" title="PagSeguro">
                <resource id="UOL_PagSeguro::Conciliation" title="Conciliation" sortOrder="10" />
                <resource id="UOL_PagSeguro::Abandoned" title="Abandoned" sortOrder="20" />
                <resource id="UOL_PagSeguro::Cancellation" title="Cancellation" sortOrder="30" />
                <resource id="UOL_PagSeguro::Refund" title="Refund" sortOrder="40" />
                <resource id="UOL_PagSeguro::Credentials" title="Credentials" sortOrder="50" />
            </resource>
        </resource>
    </resources>
</acl>
</config>
```

Finally, to find out the module/theme thats causing this issue, check their acl.xml files or try to disable one by one and check the roles & permissions page to see if the tree is visible again.

Remember to clear cache if you're not running in developer mode!

**Comment by fideliocc** [comment]
I understand these are the custom modules located in `app/code` directory (?). There are also directories that don't contain the acl.xml file in `custom-module-name/etc` directory. It's necesary to add this file, or just to modify these lines where the file exists?

Thanks for your help.

**Comment by pguedesbr** [comment]
You dont need to create acl.xml files for modules that do not require one.
In those modules that do have acl.xml file, check their sintax as per my previous post and fix them accordingly.

**Comment by ThakurPradeep** [comment]
Thanks <b>@Robkor</b> Working fine.

Magento ver 2.1.5

<b> Problem: </b> No role resources are shown, selectable, or savable.

1) Admin -> System -> User Roles -> Add New Role -> Roles Resources
   
Solution : Open file and edit Edit.php
path : /vendor/magento/module-user/Block/Role/Tab/Edit.php

in the function getTree() I changed:
isset($resources[1]['children']) ? $resources[1]['children'] : []
into:
isset($resources[2]['children']) ? $resources[2]['children'] : []
and the resource tree is shown again.

2) Admin -> System -> Extensions -> Integration  -> Add New Integration ->  API -> Resources

Solution : Open file and edit Webapi.php
path :/vendor/magento/module-integration/Block/Adminhtml/Integration/Edit/Tab/Webapi.php

in the function getTree() I changed:
isset($resources[1]['children']) ? $resources[1]['children'] : []
into:
isset($resources[2]['children']) ? $resources[2]['children'] : []
and the resource tree is shown again.

Thanks

**Comment by BlackIkeEagle** [comment]
this is not a proper fix, but the develop branch has this issue fixed

66d19602e9627b2c446dd5445ff62bfbc2eea2b6 and 6b512596988f5f2d9f3102a56fbea17bff88ef13 are related to this

**Comment by oleg-onufer** [comment]
Hi @dgarbe.
Unfortunately I could not reproduce this issue. May you please advise if this problem is still relevant for latest release Magento 2

**Comment by magento-engcom-team** [comment]
@dgarbe, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by Brendonwbrown** [comment]
I have this issue after upgrade to 2.1.9.

**Comment by KowsiganAtsayam** [comment]
i am also having this issue in magento 2.3.3
