### ISSUE TITLE
403 forbidden error while try to access homepage.

### ISSUE THREAD

**Issue by senthilengg** [magento/magento2#5912]
### Preconditions

1. Cent 0s, PHP-Fpm & nginx
2. Mysql 5.6 (Percona)
### Steps to reproduce

1. Not able to access the home page after install via cli. Its throwing 403 Forbidden error.
2. Its happening with the mode developer as well as production.
3. Using the nginx.conf.sample as virtual host conf.
### Expected result

1. Home page should have displayed without any error.
### Actual result

1.pub/index.php" is forbidden (13: Permission denied)

**Comment by acidreian666** [comment]
Hopefully you attempted to `Sudo php -f bin/magento setup:static-content:deploy`
then 
`cd /var/www/html/magento2 && find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; && find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \; && chmod u+x bin/magento`

This was taken directly from [Official dev Doc's](http://devdocs.magento.com/guides/v2.0/install-gde/prereq/file-system-perms.html)

I have installed magento2 with your Preconditions multiple times on way to reproduce this issue is to ignore the permissions step.

**Comment by andimov** [comment]
@senthilengg
Do you have any updates?

**Comment by ghost** [comment]
@acidreian666 thanks. I was able to fix the issue using.
restorecon -r <path-to-www-folder/>

**Comment by ghost** [comment]
Sorry it's weird the command I ran is
restorecon -r /path/to/www

**Comment by andimov** [comment]
@senthilengg
Thank you! It's look like a permission issue. So I close it. Please feel free to reopen if you need.
