### ISSUE TITLE
tab contents showing as dashboard in new magento 2 version

### ISSUE THREAD

**Issue by shyam100379** [magento/magento2#5950]
In admin, the tab contents are showing dashboard itself. This is new version of Magento 2.
See: http://prntscr.com/c0z07k
I think its a bug in new version. Hope the fix for this will be included in next version.

**Comment by veloraven** [comment]
@shyam100379 thank you for your report.
Please provide description according to the template: with steps, actual result and expected result.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used. 
Also please specify if it was clean installation or upgrade from previous version.

**Comment by andimov** [comment]
@shyam100379 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
