### ISSUE TITLE
Checkout address formating

### ISSUE THREAD

**Issue by Corefix** [magento/magento2#6012]
### Preconditions

1. Any setup, that can run a Magento 2 install
### Steps to reproduce

1. Add product to cart
2. Go to checkout
3. Complete shipping step
4. View address formating in summary / Payment method (if use same address is checked)
### Expected result

1. Address formating should be used from administration. 
### Actual result

1. The checkout uses knockout templating to do this

So Magento have for a long time had this feature where you can select address formating via System > Configuration. This is great, it provides one place where the administrator can go and decide how addresses should behave and it allows merchans to internationalize their store so it fits the address formating of their choice. And have it be reflected across all places on the store where addresses occur. 

However since checkout now is using Knockout for most of its rendering this doesn't apply here. This is confusing for merchants, and also for developers. Especially because formating of the addresses are rendered indenpendely.

So the way I see it currently workflow if you wan't to change address formating is:
1. Go to admin and edit the formating for the stores you want to, if you have two different formats you need to edit the default and then the one specific store.
2. Go the the code and edit the formating in two different template files to the formating affecting the most stores.
3. Make a new template, set it up so it extends from the previous default stores one. (Which will increase static file deployment time). 
4. Edit the formating for the two knockout files again so they reflect this stores formating.

I'm not sure how to resolve this in the most elegant way, but can we agree that this is not an optimal flow for changing something that in older versions of Magento was just step 1. ?

**Comment by magento-engcom-team** [comment]
@Corefix We need more information about this issue in order to successfully investigate potential fixes.

**Comment by Corefix** [comment]
Hi @magento-engcom-team what information do you need?

**Comment by magento-engcom-team** [comment]
Hello @Corefix ,

Thank you for your report and interest in Magento system.
The behavior that you have described in expected in Magento 2. Address template settings do not have any impact on checkout process anymore (address tiles on shipping step and address information in the sidebar on the billing step). This was a requirement and was done on purpose. However we do have plans to improve address information rendering on checkout in future in order to make it more flexible (internal ticket MAGETWO-63402).

Thank you once again for the report. This ticket will be closed. Thank you for understanding.
Regards,
