### ISSUE TITLE
logging-in in order to checkout when guest checkout is disabled

### ISSUE THREAD

**Issue by SidneyBilliet** [magento/magento2#6015]
### Preconditions

1. Magento version v2.1
2. 
### Steps to reproduce

1. set-up magento with these options:
2. Allow Guest Checkout = NO
3. Require Customer To Be Logged In To Checkout = YES
4. Add a product to the cart
5. click the "Go To Checkout" button in the header cart
6. when the pop-up appears, sign in 
### Expected result

1. One would expect that you are automatically redirected to the checkout after logging in (you did choose to "go to checkout"...). Even when you go to the cart via "view cart" first and then click "proceed to checkout", the behavior is the same... It doesn't seem logical to have to click the button a second time after signing in because you stay on the same page after sign-in...
### Actual result

1.  After signing in the pop-up disappears but you stay on the page you where on before signing in.

**Comment by SerhiyShkolyarenko** [comment]
Thank you for the report. Our internal issue is MAGETWO-58082.

**Comment by magento-engcom-team** [comment]
internal issue MAGETWO-58082.

**Comment by jissereitsma** [comment]
I'm unable to locate the configuration option "Require Customer To Be Logged In To Checkout" which is mentioned here above. However, regardless of this setting, this issue is still there. I'm going to pick this up (MM17BE)

**Comment by quienti** [comment]
https://github.com/magento/magento2/issues/7848

**Comment by jissereitsma** [comment]
Fix is on the way with changes in 2 files: `Magento_Customer/js/view/authentication-popup.js` and `vendor/magento/module-customer/Block/Account/AuthenticationPopup.php`. Prepping PR.

**Comment by VincentMarmiesse** [comment]
Hi,
Any news on this?

**Comment by ivanko-dev** [comment]
Issue was reproducible only in case of login with dialog from cart page by clicking "Proceed to Checkout" button. Cause of issue is missing "login_redirect" with checkout page url value in cookie. In all other cases login_redirect added before login and as result redirect work well.

**Comment by engcom-Bravo** [comment]
Hi @SidneyBilliet,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



**Steps to reproduce**

- set-up magento with these options:
- Allow Guest Checkout = NO
- Require Customer To Be Logged In To Checkout = YES
- Add a product to the cart
- click the "Go To Checkout" button in the header cart
- when the pop-up appears, sign in



https://github.com/magento/magento2/assets/51680745/fada5ced-a6be-4e7e-9802-119a8545d9c7



After signin we are redirecting to checkout page.As the issue is no more reproducible in latest 2.4-develop instance we are closing this issue.

Thanks.
