### ISSUE TITLE
related product

### ISSUE THREAD

**Issue by chiragayartops** [magento/magento2#6019]
How to stop to change related product price after change attribute value into configurable product product page in magento2

**Comment by andimov** [comment]
@chiragayartops 
Thank you for reporting!
To allow us to research the issue, please, provide description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
Please, provide the used version also. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by chiragayartops** [comment]
Hi,
When i change color swatch product images does not change into configurable in magento2.
Thanks.

**Comment by oserediuk** [comment]
@chiragayartops , is this same issue https://github.com/magento/magento2/issues/6041 ?

**Comment by andimov** [comment]
@chiragayartops 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
