### ISSUE TITLE
making Schedule new update Start/End store wise in product edit page

### ISSUE THREAD

**Issue by rramiii** [magento/magento2#6060]
**Preconditions**
Magento 2.1 ee
PHP 7 & MySQL

**steps:**
1- from admin view, open product edit page.
2- switch to desired store view.
3- added a new Scheduled Change by clicking on "Schedule new update"(actually updated product price only).
**Expected**
have Scheduled Change in selected store view only.
**Actual**
any Scheduled Change is available for all stores no matter in which store view it was set and both start/end date for the Scheduled Change are not a store level values.

**Aim** 
have Scheduled Change in product price as per store (some stores might be not involved).

**Comment by veloraven** [comment]
@rramiii is this issue still actual?
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
