### ISSUE TITLE
inserted image in product description got broken on front end 

### ISSUE THREAD

**Issue by forvin** [magento/magento2#6088]
My site is built by Magento 2.1.
I inserted image in product description area, but image is broken after I save it. 
How to fix it?  Thanks

**Comment by allanpaiste** [comment]
I tried to repeat the problem by:
1. have 2.1 stable release installed (with demo data)
2. log into admin
3. edit any product (I chose "Hyperion Elements Jacket-XS-Green")
4. open the "Content" accordion
5. Insert an image via media manager to the description wysiwyg area
6. save the product

**EXPECTED**: image is correctly rendered in the description area
**ACTUAL**: image is correctly rendered in the description area

... so basically I failed to repeat

QUESTIONS: what image type did you use, what was the image filename? what product type? do you have any extra modules installed?

**Comment by forvin** [comment]
Hi allanpaiste, Thanks for your reply. 

I just tested a product of demo data , it works .

**Comment by oserediuk** [comment]
Hello @forvin ! Did you resolve you issue?

**Comment by forvin** [comment]
Hi @oserediuk ! No, I didn't.   Inserted image will be fine at first,  but it will break after you re-index your magento.  And newly added products will not appear until you manually re-index via ssh.  @allanpaiste

**Comment by andimov** [comment]
@forvin
Unfortunately, now it's not easy to understand what is your actual problem is. So I have to ask you format your issue according to templates: specifying preconditions, exact steps to reproduce, actual result, and expected result.

**Comment by dthampy** [comment]
@forvin , is this the same as https://github.com/magento/magento2/issues/6138 ?

**Comment by andimov** [comment]
@forvin 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-70435

**Comment by erikkubica** [comment]
@magento-team I am running CE 2.2.3  and this issue still persists. My client just reported that he inserted image into the product description and that the image does not load if user is not logged in as admin.

I have tried to use blank and luma themes so I can ensure that issue is not caused by my custom theme. Output from any theme I tried:

```
<img src="https://blahblahblahblah.com/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvbGlwb2VsYXN0aWNfc3Rhcm9zdGxpdm9zdF8yLnBuZyJ9fQ/" width="600" height="346">
```

Funny thing is that it works for CMS Page, but not for product description.

I have tried to wrap my block where I echo my product description using:
```
$this->_filterProvider->getPageFilter()->filter(...)
```
But it did not work. When I tried to:
```
$this->_filterProvider->getPageFilter()->filter('{{media url="wysiwyg/lipoelastic_starostlivost_2.png"}}'); 
```

Then it returned URL. So it seems like the problem is that the filter cannot proccess the directive, while it can process the widget code.

--- Edit ----
If I insert image without wysiwyg editor, then it works since instead of that weird directive it generates widget code.
