### ISSUE TITLE
Unable to get correct placeholder image URL on backend

### ISSUE THREAD

**Issue by JanPetr** [magento/magento2#6119]
Hello, I got weird behaviour when I try to get product's image URL. I have set placeholder images in store configuration, I have product with no images and when I try to get imageUrl() from ImageHelper I always get URL `[domain]/pub/static/adminhtml/_view/en_US/Magento_Catalog/images/product/placeholder/.jpg`

### Preconditions

1. Magento 2.1
2. PHP 7.0.7
3. MySQL 5.7.13
### Steps to reproduce

1. Set placeholder images in configuration
2. Have some products with no images
3. Get instance of `Magento\Catalog\Helper\Image`
4. Iterate over collenction of products
5. Get product's image URL by `$imageHelper->init($product, 'product_base_image')->getUrl();`
6. See that products without images does not get right placeholder URL
### Expected result

1. Right placeholder URL, something like: `[domain]/pub/media/catalog/product/cache/1/image/265x265/beff4985b56e3afdbeabfc89641a4582/placeholder/default/spaca_k.jpg`
### Actual result

1. `[domain]/pub/static/adminhtml/_view/en_US/Magento_Catalog/images/product/placeholder/.jpg`

**Comment by sammarcus** [comment]
Can someone from Magento kindly provide an update on this? I am able to reproduce in 2.1.2.

**Comment by springimport** [comment]
I had the same problem with my theme after including a block.

``` xml
<block class="Magento\Reports\Block\Product\Widget\Viewed" page_size="4" name="recently_viewed" template="Magento_Reports::widget/viewed/content/viewed_grid.phtml" cacheable="false" />
```

I solved it by adding `etc/view.xml` from luma.

**Comment by shazadmaved** [comment]
@springimport could you please explain it of how to add it to our custom module and the file path of etc/view.xml from luma ?

**Comment by ousmanedev** [comment]
Any update on this, please ?

**Comment by springimport** [comment]
@shazadmaved Yes.

Example from luma placed here: `/vendor/magento/theme-frontend-luma/etc/view.xml`.

You need to put this file in `/app/code/YouVendor/YouModule/etc/view.xml`.

**Comment by magento-engcom-team** [comment]
@JanPetr, thank you for your report.
We've created internal ticket(s) MAGETWO-81625 to track progress on the issue.

**Comment by JanPetr** [comment]
Thanks for the update @magento-engcom-team! How / where can I track progress / fix of this issue now?

**Comment by breg-13** [comment]
Found some solution, it fixed displaying of product placeholder image for me, when product don't have an image. But not sure.
It's needed to add:
```
<view xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/view.xsd">

    <media>

        <images module="Magento_Catalog">

            <image id="image" type="image"/>

            <image id="small_image" type="image"/>

            <image id="thumbnail" type="image"/>

```
 in /etc/view.xml (theme folder)

**Comment by danemacmillan** [comment]
Any news on this?

**Comment by vananin** [comment]
This issue can be fixed by overriding of `Algolia\AlgoliaSearch\Helper\Entity\ProductHelper` class.
There are two changes required:

1. Load design area in `__constructor()` method
`public function __construct(
        Config $eavConfig,
        ConfigHelper $configHelper,
        AlgoliaHelper $algoliaHelper,
        Logger $logger,
        StoreManagerInterface $storeManager,
        ManagerInterface $eventManager,
        Visibility $visibility,
        Stock $stockHelper,
        Data $taxHelper,
        StockRegistryInterface $stockRegistry,
        ObjectManagerInterface $objectManager,
        CatalogHelper $catalogHelper,
        CurrencyHelper $currencyManager,
        PriceCurrencyInterface $priceCurrency,
        Rule $rule,
        CategoryHelper $categoryHelper,
        AreaList $areaList
    ) {
        parent::__construct(
            $eavConfig,
            $configHelper,
            $algoliaHelper,
            $logger,
            $storeManager,
            $eventManager,
            $visibility,
            $stockHelper,
            $taxHelper,
            $stockRegistry,
            $objectManager,
            $catalogHelper,
            $currencyManager,
            $priceCurrency,
            $rule,
            $categoryHelper
        );

        $this->configHelper = $configHelper;
        $this->objectManager = $objectManager;
        $this->imageHelper = $this->objectManager->create(
            'Algolia\AlgoliaSearch\Helper\Image',
            [
                'options' =>[
                    'shouldRemovePubDir' => $this->configHelper->shouldRemovePubDirectory(),
                ]
            ]);

        // BlueAcorn's changes start
        $area = $areaList->getArea(\Magento\Framework\App\Area::AREA_FRONTEND);
        $area->load(\Magento\Framework\App\Area::PART_DESIGN);
        // BlueAcorn's changes end
    }`

Note: `configHelper`, `objectManager` and `imageHelper ` properties have private access so shoud be overridden as well. Otherwise they are not available in overridden class.

2. Override `addImageData()` method
`
$customData['thumbnail_url'] = $this->imageHelper
                //BlueAcorn's changes start
                ->init($product, 'product_page_image_small')
                //BlueAcorn's changes end
                ->resize(90, 90)
                ->getUrl();
`
where `product_page_image_small` is a config from _vendor\magento\theme-frontend-blank\etc\view.xml_ file.

**Comment by vananin** [comment]
I faced with such issue using Algolia search module for Magento2 - incorrect placeholders were added to index. In scope of that module this issue was resolved by overriding of `Algolia\AlgoliaSearch\Helper\Entity\ProductHelper` class.
There were two changes required:

1. Load design area in `__constructor()` method
```public function __construct(
        Config $eavConfig,
        ConfigHelper $configHelper,
        AlgoliaHelper $algoliaHelper,
        Logger $logger,
        StoreManagerInterface $storeManager,
        ManagerInterface $eventManager,
        Visibility $visibility,
        Stock $stockHelper,
        Data $taxHelper,
        StockRegistryInterface $stockRegistry,
        ObjectManagerInterface $objectManager,
        CatalogHelper $catalogHelper,
        CurrencyHelper $currencyManager,
        PriceCurrencyInterface $priceCurrency,
        Rule $rule,
        CategoryHelper $categoryHelper,
        AreaList $areaList
    ) {
        parent::__construct(
            $eavConfig,
            $configHelper,
            $algoliaHelper,
            $logger,
            $storeManager,
            $eventManager,
            $visibility,
            $stockHelper,
            $taxHelper,
            $stockRegistry,
            $objectManager,
            $catalogHelper,
            $currencyManager,
            $priceCurrency,
            $rule,
            $categoryHelper
        );

        $this->configHelper = $configHelper;
        $this->objectManager = $objectManager;
        $this->imageHelper = $this->objectManager->create(
            'Algolia\AlgoliaSearch\Helper\Image',
            [
                'options' =>[
                    'shouldRemovePubDir' => $this->configHelper->shouldRemovePubDirectory(),
                ]
            ]);

        // BlueAcorn's changes start
        $area = $areaList->getArea('frontend');
        $area->load(\Magento\Framework\App\Area::PART_DESIGN);
        // BlueAcorn's changes end
    }
```

Note: `configHelper`, `objectManager` and `imageHelper ` properties have private access so shoud be overridden as well. Otherwise they are not available in overridden class.

2. Override `addImageData()` method
```
if (false === isset($customData['thumbnail_url'])) {
    $customData['thumbnail_url'] = $this->imageHelper
        //BlueAcorn's changes start
        ->init($product, 'product_page_image_small')
        //BlueAcorn's changes end
        ->resize(90, 90)
        ->getUrl();
}
```
where `product_page_image_small` is a config from _vendor\magento\theme-frontend-blank\etc\view.xml_ file.

So the main goal was to load correct area `$area->load(\Magento\Framework\App\Area::PART_DESIGN);` and pass proper image type to `init()` method

**Comment by vananin** [comment]
I faced with such issue using Algolia search module for Magento2 - incorrect placeholders were added to index. In scope of that module this issue was resolved by overriding of `Algolia\AlgoliaSearch\Helper\Entity\ProductHelper::addImageData()` method.

```
protected function addImageData(array $customData, Product $product, $additionalAttributes)
{
    // BlueAcorn's changes start
    $area = $this->areaList->getArea(\Magento\Framework\App\Area::AREA_FRONTEND);
    $area->load(\Magento\Framework\App\Area::PART_DESIGN);
    // BlueAcorn's changes end
    
    if (false === isset($customData['thumbnail_url'])) {
        $customData['thumbnail_url'] = $this->imageHelper
            //BlueAcorn's changes start
            ->init($product, 'product_page_image_small') // was `thumbnail`
            //BlueAcorn's changes end
            ->resize(90, 90)
            ->getUrl();
    }	
    ...
```
where `product_page_image_small` was a config from _vendor\magento\theme-frontend-blank\etc\view.xml_ file, _$this->areaList_ was a `Magento\Framework\App\AreaList` class.

So there was necessary to load correct area `$area->load(\Magento\Framework\App\Area::PART_DESIGN);` and pass proper image type to `init()` method.

**Comment by ilnytskyi** [comment]
Can not reproduce on 2.3-develop
