### ISSUE TITLE
Custom option image upload v2.1

### ISSUE THREAD

**Issue by pieal86** [magento/magento2#6143]
### Preconditions

1. Magento v2.1 CE
2. PHP 7.0
### Steps to reproduce

1. Create simple product with custom option of image upload. supported file (jpg, png).
2. Order uploading a .jpg image
### Expected result

1. In order mail there should be link of the image.
2. In backend sales>orders> should have the image link inside.
### Actual result

1. In the order email there is only name of the file with a wrong link like: site.com/sales/download/downloadCustomOption/id/19/key/e45e0dc5bb08417063e6/?SID=a7erbtefl3p3iga4iknenptcl1
2. same for the backend sales>order>
3. File names shows correct but not the file.

**Comment by slopukhov** [comment]
@pieal86 thank you for your feedback,
Please, recheck it on the latest 2.1 version of Magento.

Just to clarify, сan you open the image to these links?  
Since I have links: 
in the email like site.com/sales/download/downloadCustomOption/id/3/key/74e0e2326f17da27aa32/, 
in the backend like site.com/sales/download/downloadCustomOption/id/3/key/74e0e2326f17da27aa32/?SID=pmjci4l0t9hiph86ndig83q244
and by clicking on the links image downloaded correctly.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
