### ISSUE TITLE
Updating product images across multiple products, incorrect/previous thumb shown

### ISSUE THREAD

**Issue by blizam** [magento/magento2#6161]
2.1.0

I had need to go through all my products today and delete the Base image and add a new image to which I then set as the base image. My image file names are identical for certain images of a certain type across multiple categories... perhaps that makes a difference in the behavior I'm about to describe.

I cycled through 12 products like this with no issue.

When I started the next batch of 12 products, all using new unique image files with the same filename as their "mirror" product in the other category the Image preview of the file I uploaded was that of the 1st category's products.

eg:

Category 1
Edit Product, delete Base image, upload new product1.jpg
Edit Next Product, delete base image, upload new product2.jpg
Edit Next Product, delete base image, upload new product3.jpg

etc.

Category 2
Edit Product, delete Base image, upload new product1.jpg -- the image thumb preview shows Category 1's product1.jpg... even if I click the image to edit it's properties I still still Category 1's product.jpg.

rinse and repeat for the next 2 products...

I then flushed my image cache and ran indexer:reindex... it didn't effect it... I still saw the same behavior.

Furthermore, it did seem like Magento was actually persisting the wrong image as well... like, it didn't appear to just be a "preview" issue... I decided to just go ahead and delete the image a 2nd time and re-upload, doing this showed the correct thumb (so for every product I had to delete, upload, delete, upload to get the correct image/image preview) so I decided to do that for all the products.

**Comment by blizam** [comment]
pretty sure it's related to me having the same file names... I had some variations that I typo'ed or otherwise had a different file name and this issue did not occur

**Comment by blizam** [comment]
possibly related:

https://github.com/magento/magento2/issues/3484

any probably definitely related seeing as I reported this one a while back and had forgotten:

https://github.com/magento/magento2/issues/4988

:)

**Comment by blizam** [comment]
unlike 4988 though saving the product did NOT show the correct thumb... which is why I believed it was actually persisting the incorrect image file... on the first couple where I didn't notice right away when I went back into the product it was still showing the incorrect thumb/preview image

**Comment by wert2all** [comment]
Thanks for a response. As I see this is a copy of #3484.

**Comment by blizam** [comment]
I don't think it is necessarily... related maybe... my issue is very specific to using product images with the same file name when updating/creating multiple products... the other post doesn't mention the filenames being identical

**Comment by wert2all** [comment]
@blizam I will create an internal ticket for #3484 and will add your case to the issue description.

**Comment by wert2all** [comment]
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. This will help to reproduce the issue for me.

**Comment by blizam** [comment]
Create 2 images that look different but have the same filename

Create a new product. Add the first image to it. Save it. Create a new product, add the 2nd image to it... you'll see the thumbnail/preview of the first image.

The same thing will happen if you have 2 products already created and you try to update their images

**Comment by veloraven** [comment]
Internal ticket was created - MAGETWO-70028

**Comment by 1408sheva** [comment]
Thank you, Internal ticket was created for this issue - MAGETWO-70028

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @blizam The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
