### ISSUE TITLE
Can't set customer group when creating a new order in the admin.

### ISSUE THREAD

**Issue by otg-chris** [magento/magento2#6162]
When ordering in the admin, we can't change the customer group when creating a new customer while creating an order. It worked before we updated the site from 2.0.2 to 2.1. The same problem happens when creating an order with an existing customer, except the group select goes back to what the customer was set to when the page was loaded.
### Preconditions
1.  Magento 2.1
2.  Apache/2.4.6 (Red Hat Enterprise Linux), PHP/5.6.24, MySQL 5.6.25
3.  Several Customer Groups created
### Steps to reproduce
1.  In admin select Sales->Orders.
2.  Select Create New Order
3.  Select Create New Customer
4.  Under Account Information, change the group.
### Expected result
1.  Selected customer group stays selected in select box.
2.  Product prices are updated for the group.
### Actual result
1.  Wait overlay comes up, twice.
2.  Customer group goes back to the default.
3.  Email input box to the right is cleared.
4.  Product prices stay the same.

**Comment by picamator** [comment]
@otg-chris  thanks for reporting.
We created internal ticket MAGETWO-57077 to fix it.

**Comment by SerhiyShkolyarenko** [comment]
Fix of MAGETWO-57078 is delivered to develop branch. Closing the issue.

**Comment by flnative** [comment]
If I have 2.1.2 was this supposed to be fixed?  I cannot edit customer group per customer.. Says it saves upon clicking the save button, though it reverts back to default setting.

**Comment by magento-engcom-team** [comment]
Hi @otg-chris. Thank you for your report. 
The issue has been fixed in magento/magento2#21145 by @gauravagarwal1001 in 2.3-develop branch
Related commit(s):
 - [76468502c720ae637c3c61382dfd57a40c071ad1](https://github.com/magento/magento2/commit/76468502c720ae637c3c61382dfd57a40c071ad1)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @otg-chris. Thank you for your report. 
The issue has been fixed in magento/magento2#21239 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [d77bc6acaccaecddc4bda3415d268ed21ef94981](https://github.com/magento/magento2/commit/d77bc6acaccaecddc4bda3415d268ed21ef94981)

The fix will be available with the upcoming 2.2.9 release.
