### ISSUE TITLE
Magento asked for account password reset in loops

### ISSUE THREAD

**Issue by robilomas** [magento/magento2#6170]
### Preconditions

1.  Dell Latitude E5440, Windows 7, Google Chrome
2.  Magento 2.0.5
### Steps to reproduce

1. Access Magento with password.
2. New scree prompts me with It's tim to change my password.
3. Once password is changed, I cannot access any other page and I am stuck in a loop. 
### Expected result

1. I should be able to change my password and access Magento in it entirety. 
### Actual result

1. It loops on the Reset password screen.
   ![password](https://cloud.githubusercontent.com/assets/21038281/17665572/d1954a12-62c9-11e6-8d79-5a7658f9ff01.jpg)

**Comment by stamster** [comment]
You're using outdated Magento version. Try to upgrade to the latest stable.
Additionally, Windows is NOT supported platform for M2: http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html

**Comment by katmoon** [comment]
Hi @robilomas 
1. Which [Magento mode](http://devdocs.magento.com/guides/v2.0/config-guide/bootstrap/magento-modes.html) do you use? You can see more errors on browser page in `developer` mode. Are there any errors in magento/apache/php logs?
2. What happens if you clear cookies and cache and try to login to Admin with the password you entered on the Reset password screen?

Thanks,
Kateryna.

**Comment by andimov** [comment]
@robilomas 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
