### ISSUE TITLE
i am installed magento 2 successfully but i cant see even subcategories in admin panel i installed it many times but same problem

### ISSUE THREAD

**Issue by jaimin1671992** [magento/magento2#6225]
This is the Actual error and i unable to solve this i think i am unable to install backend inshort how to solve this all?

![1](https://cloud.githubusercontent.com/assets/21102494/17773210/de08726c-656a-11e6-910a-9c98e354b80e.png)
![2](https://cloud.githubusercontent.com/assets/21102494/17773211/de54eec6-656a-11e6-9c82-17a6d1fb8900.png)

**Comment by allanpaiste** [comment]
Looks like static files are missing, are you running Magento in dev mode? In development mode, those files will be generated on the fly when a request is sent against Magento. In production mode they have to be there beforehand (generated with bin/magento setup:static-content:deploy).

Another thing that I've seen (but it's not your case atm, because you get 404's) is that when you have totally cleaned your browser cache, the inital load might take a while to finish and you may get strange page on the first visit. Reloading the page usually fixes this for me. But - again - in those cases it's just slow to load the resources and does not result in bunch of 404's.

**Comment by jaimin1671992** [comment]
i just install and see the link i dont know which mode i am running my magento @allanpaiste

**Comment by jaimin1671992** [comment]
how to solve this first i want to solve my admin panel error @allanpaiste

**Comment by jaimin1671992** [comment]
can i install magento without sample data if it will run?

if you free than i am ready to my pc access threw ammyadmin

**Comment by veloraven** [comment]
@jaimin1671992 thank you for your feedback.
Please, provide the used Magento version.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. In your case please describe by steps how do you install Magento.
Please try to clear browsers cache if you have installed Magento before.
And, yes, you can install and run Magento without any sample data.

**Comment by jaimin1671992** [comment]
i am solve this at my self actually i want to set just this ->php bin/magento setup:static-content:deploy
and all my problem is solved

**Comment by jaimin1671992** [comment]
Thank you @veloraven
