### ISSUE TITLE
Why no updated_at on cataloginventory_stock_item table?

### ISSUE THREAD

**Issue by centerax** [magento/magento2#6234]
Is there a reason for not having the updated_at attribute on the cataloginventory_stock_item table?

Thanks.

**Comment by yaronish** [comment]
Hi, @centerax 

Can you specify case for updated_at you are interested in?

Table has 25+ fields and having such field we must update it with every single change.
So as I understand such field just tell us that something has been changed.
Taking into account that `qty` field will be changed with every order placed in your system updated_at field most probably will contains last order creation time and I'm not sure this is you expect to have.

Thanks.

**Comment by centerax** [comment]
Hi @yaronish
Thanks for your reply.

I think Magento should keep this attribute to keep track of inventory changes. Almost every entity inside Magento has it except this one. 
`created_at` and `updated_at` should be part of the schema in my opinion.

**Comment by yaronish** [comment]
Hi, @centerax 

Agree with you, fields `created_at` and `updated_at` exist for all entities. 
Catalog Inventory Item does not have such field because it always was part of product entity not standalone one. 
But things are changing and now we can treat it as separate entity especially taking into account in Magento 2 it has dedicated repository.

This inconsistency will be fixed in one of the future releases.

Thanks.

**Comment by centerax** [comment]
Thanks again @yaronish I appreciate your quick reply.

Looking forward to have this merged in core.

**Comment by yaronish** [comment]
Mentioned changes will be implemented in MAGETWO-61014.
Closed.
