### ISSUE TITLE
[Magento_Version] Do not publicly disclose store version

### ISSUE THREAD

**Issue by kassner** [magento/magento2#6239]
Hi,

Looks like we have this particular [Magento_Version](https://github.com/magento/magento2/blob/develop/app/code/Magento/Version/Controller/Index/Index.php) module, that the unique purpose is to disclose publicly which Magento version and edition the store is running. Although is a good idea to allow other systems that integrate to Magento retrieve the current version to do proper API calls, I strongly believe this should not be available wide open, but rather inside secure/authenticated endpoint.

Can we make this call authenticated? Or maybe remove the module at all? Why outsiders need to know which minor version a particular store is running?

Thanks!

**Comment by avoelkl** [comment]
I agree, I would not show this as a public available information per default.

**Comment by veloraven** [comment]
@kassner your proposition looks like an improvement.
Could you please transfer it to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96))?

**Comment by kassner** [comment]
@veloraven no, I think it is a security issue, not a feature request.

**Comment by veloraven** [comment]
@kassner than please format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by kassner** [comment]
@benmarks @sherrierohde What is the point of having community moderators if the only thing they do is poking about a damn ticket structure?

**Comment by miguelbalparda** [comment]
You were told to go to the forums or reformat the issue according to the guidelines and you failed to do it. These rules are probably here to keep things in order and have a clear workflow (and make things reproducible for others FWIW). 
If everybody thinks the issue they are reporting is more important than others and that they don't need to follow the guidelines because "the only thing they (community moderators) do is poking about a damn ticket structure" this would be a total chaos.
Guidelines are clear and moderators are just following them. Go ahead and restructure this or go to the forums, there is no need to be rude with the moderators because you don't like the way they manage things around here.

**Comment by kassner** [comment]
I won't comment in this issue anymore, it was my mistake to bring up on
GitHub. Please lock it.
