### ISSUE TITLE
Order getitemscollection Missing items when loading

### ISSUE THREAD

**Issue by basselalaraaj** [magento/magento2#6267]
### Preconditions
1. Magento 2 develop branch (update to last commit 5a615bb9d369ca8ead2929dd469d12d55532c8f8)
2. PHP 7 and mysql 5.6
### Steps to reproduce
1. First setItems() on a order through code.
   \Magento\Sales\Model\Order::setItems()
2. Then call the item collection of an order
   \Magento\Sales\Model\Order::getItemsCollection()
### Expected result

![screen shot 2016-08-22 at 11 40 55](https://cloud.githubusercontent.com/assets/5745279/17850451/9578d910-685d-11e6-97b7-a2ff24f10e17.png)
### Actual result

![actual](https://cloud.githubusercontent.com/assets/5745279/17850427/6c4503ca-685d-11e6-9381-c536f8185a8d.jpg)

**Comment by basselalaraaj** [comment]
provided also the fix
https://github.com/magento/magento2/pull/6268/commits/329158428843772ee6f930d4f2cd2fff8117e34b

**Comment by magento-engcom-team** [comment]
@basselalaraaj, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
