### ISSUE TITLE
Changing sample for downloadable product failure

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#6272]
### Preconditions

1. I use Magento 2.1, PHP 7.0. 
### Steps to reproduce

1. On clean Magento install I have created new downloadable product with link, link sample and sample and saved it.
2. Afterwards, when I wanted to change sample I used button browse and uploaded new file. It has been uploaded, but after saving I have noticed that It hasn't been bind with product - instead of it there was previous file still present.
3. The same problem does not occure for link and link samples.
### Expected result

1. Of course, changing the file for sample without any problem.
### Actual result

1. It does not change. There is no error messages or signs in logs. Product has just been saved, but with previous file.

**Comment by bartoszkubicki** [comment]
If I want to change sample i have to use this icon of bin and remove it completly and add new instance of sample with required file.

**Comment by victor-v-rad** [comment]
Internal ticket MAGETWO-57817 to fix this issue

**Comment by magento-engcom-team** [comment]
@bartek9007, thank you for your report.
We've created internal ticket(s) MAGETWO-57817 to track progress on the issue.

**Comment by sichensol** [comment]
#Kharkiv-CD

**Comment by magento-engcom-team** [comment]
@molneek thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment]
Hi @bartoszkubicki. Thank you for your report. 
The issue has been fixed in magento/magento2#19806 by @ravi-chandra3197 in 2.3-develop branch
Related commit(s):
 - [7cd48fc3b92c67d3d99257e3d302a931acd966a1](https://github.com/magento/magento2/commit/7cd48fc3b92c67d3d99257e3d302a931acd966a1)
 - [b39550ae4e947da335cea2e836005fc000b0082a](https://github.com/magento/magento2/commit/b39550ae4e947da335cea2e836005fc000b0082a)
 - [d598262302bc6852cd05020c5013dd38281bfc03](https://github.com/magento/magento2/commit/d598262302bc6852cd05020c5013dd38281bfc03)

The fix will be available with the upcoming 2.3.2 release.

**Comment by magento-engcom-team** [comment]
Hi @bartoszkubicki. Thank you for your report. 
The issue has been fixed in magento/magento2#22471 by @ravi-chandra3197 in 2.2-develop branch
Related commit(s):
 - [9aff2a9aafea39288564699e38e1715029342f28](https://github.com/magento/magento2/commit/9aff2a9aafea39288564699e38e1715029342f28)
 - [03db5583c67ea4f7fc685dd4dd48672fb326c65c](https://github.com/magento/magento2/commit/03db5583c67ea4f7fc685dd4dd48672fb326c65c)

The fix will be available with the upcoming 2.2.9 release.
