### ISSUE TITLE
Development mode loads +450 files

### ISSUE THREAD

**Issue by thagxt** [magento/magento2#6276]
### Preconditions

1. Magento CE: 2.1.0, PHP: 5.6.15
### Steps to reproduce

1. Set Developer mode on 
2. Load a page of your choice
3. Open FireBug (or similar) 
4. Watch Magento request +450 files. 
   An infinite number of _module.less, _widget.less and others.
5. My iMac panics/restarts at least 2 times a day because of all of these.
### Actual result

1. [Screenshot](https://i.imgur.com/C44Rduy.gif)

**Comment by TiEul** [comment]
If your Mac has Kernel Panics, it likely has some kind of hardware defect. Loading a large amount of files through HTTP requests does not cause unrecoverable kernel states, that's ridiculous.

That said, did you enable "Frontend Development Workflow" in the back-end? Because that will cause Less files to be compiled during runtime.

**Comment by thagxt** [comment]
Setting "Frontend Development Workflow" to "Server-side compilation" did the trick. Files went from 455 to 130.

[Devdocs guide](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css-preprocess.html)
