### ISSUE TITLE
Customer Admin Shopping Cart View Missing

### ISSUE THREAD

**Issue by alexgoodey** [magento/magento2#6287]
It is not possible to view what a registered customer has in their shopping cart in Magento CE 2.1.0.

This functionality was available in the Magento 1.\* and it does look like some provision has been made for it in version 2 as these files exist:

./vendor/magento/module-customer/Block/Adminhtml/Edit/Tab/Carts.php
./vendor/magento/module-customer/Block/Adminhtml/Edit/Tab/Cart.php
./vendor/magento/module-customer/Controller/Adminhtml/Index/Carts.php

However there is no corresponding "CartsTab" file to actually add it to the admin screen.
### Preconditions
1. Magento 2.1 install
2. Registered Customer
### Steps to reproduce
1. Install a standard Magento 2.1 setup
2. Register a customer 
3. Add a product to customers basket
4. Login to the admin area and navigate to customer
5. See no-existence of Shopping Cart tab
### Expected result
1. At Step 5 above I would expect to a tab labelled Shopping Cart where I can view the products that are in the customers cart
### Actual result
1. As step 5 above there is no tab for Shopping Carts

**Comment by pboisvert** [comment]
You should be able to see this functionality by clicking on the Manage Shopping Cart page (2nd link from the right)

<img width="1409" alt="screen shot 2016-08-23 at 7 37 45 am" src="https://cloud.githubusercontent.com/assets/5807369/17895903/74053ea8-6903-11e6-9ee4-d3a6068a2fd5.png">

Manage Shopping Cart
<img width="1331" alt="screen shot 2016-08-23 at 7 39 28 am" src="https://cloud.githubusercontent.com/assets/5807369/17896019/eeb74042-6903-11e6-8882-1281b16a3778.png">

**Comment by alexgoodey** [comment]
Can you confirm what version that is? I don't have that link on my CE 2.1.0 install.

**Comment by alexgoodey** [comment]
Hi,

Any update on this?

Alex

**Comment by sja87** [comment]
same problem here. No cart link in admin.

![bildschirmfoto 2016-08-24 um 15 20 44](https://cloud.githubusercontent.com/assets/4973582/17932035/721f5572-6a0e-11e6-9122-61de10c9b3ca.png)

**Comment by sevos1984** [comment]
Hi, Manage Shopping Cart button is available in EE version only both in 1.x and 2.x

**Comment by alexgoodey** [comment]
That is not true. In Magento CE 1.x you can view the customers shopping cart in the admin area.

![screenshot from 2016-08-25 10-36-16](https://cloud.githubusercontent.com/assets/2563109/17963981/c946afb6-6aaf-11e6-8186-06786e7282c2.png)

**Comment by sevos1984** [comment]
I meant Manage Shopping Cart functionality. View cart is not available in M2 CE

**Comment by alexgoodey** [comment]
So my original report still stands: "Customer Admin Shopping Cart View Missing"

**Comment by sevos1984** [comment]
This functionality is not available anymore in M2

**Comment by alexgoodey** [comment]
Why not? I now have to explain to a client why Magento 2 has less features than Magento 1. Also why has it been partly implemented as my original post describes?

**Comment by alexgoodey** [comment]
In addition to the above, which also suggests that this functionality is intended to be in Magento CE 2.x is the fact that if you go to the "Abandoned Carts" report, and then click on one of the rows for a registered customer it tries to redirect you to a link like:

admin_xxx/customer/index/edit/id/159/**active_tab/cart**/key/xxxxxxxxxxxxxxxxxxxxxx

Where you actually end up is at the "Customer View" tab because the "Cart" is only partially implemented.

Will this now be flagged as a bug as it is fairly obvious as this functionality was intended to be part of Magento CE 2.x?

**Comment by alexgoodey** [comment]
Any update on this?

**Comment by sja87** [comment]
also I need update

**Comment by alexgoodey** [comment]
Any update on this?

**Comment by ilol** [comment]
Hi, we are in progress.

**Comment by apurv-anand** [comment]
This is much needed functionality. If we want to send out a mail to the customer on the cart items he/she has, it becomes difficult since this information is not available. Please let us know the plan for bringing this back. We are on M2.1.1

**Comment by willfrombrazil** [comment]
@ilol any updates on this fix?

**Comment by wclsandipan** [comment]
@ilol .. Hi .. is there any update on this issue? Our client is not able to view the Abandoned cart items after it redirects to the customer view page.

**Comment by lfolco** [comment]
Any updates on this?

**Comment by sackling** [comment]
checking in for updates :)

**Comment by sja87** [comment]
Update?

**Comment by legweilo** [comment]
Hi guys,

A small module to fix it : https://github.com/pfortin-expertime/MageFix-Customer#magefix-customer
Feel free to enhance it ;)

**Comment by erfanimani** [comment]
Thanks @pfortin-expertime ! Will try it out soon.

**Comment by mthsialkot** [comment]
You can check customer's cart when you will click create order during customer view  it will show under customer's Activities in M2 CE

**Comment by vasanth833** [comment]
+1 any update?

**Comment by amansrivastava** [comment]
I'm also having same issue. Code is having reference to show cart in customer tabs.
Why is it not visible in admin panel.

**Comment by magento-engcom-team** [comment]
@alexgoodey, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by lfolco** [comment]
Does this mean that if we create the functionality you will merge it into the open source/community edition? Or is it only going to be for EE?

**Comment by Aresinho** [comment]
Not really a fix or anything, but if you press the "Create Order" button it will show the items on the cart on that page.

**Comment by praveen-chelumalla** [comment]
Thanx @Aresinho

**Comment by okorshenko** [comment]
Please refer to the [Community Forums](https://community.magento.com/) for discussion about this feature. The GitHub issue tracker is intended for Magento Core technical issues only.

**Comment by rav-redchamps** [comment]
Hi @alexgoodey 

A pull request https://github.com/magento/magento2/pull/20918 has been made to enable the 'Shopping Cart' tab for customers. 

This should be soon processed and possibly the change should be available in any version of 2.3.x series. 

The possibility starts with 2.3.1 :wink:

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99119` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rav-redchamps** [comment]
Hi Guys

The pull request https://github.com/magento/magento2/pull/20918 from us to fix this problem is taking time to get processed. 

So we have extracted changes from the pull request and packaged them in an extension. It is available here https://github.com/redchamps/customer-shopping-carts-tab . Please feel free to use it till the time change is available in Magento 2 core.

**Comment by magento-engcom-team** [comment]
Hi @alexgoodey. Thank you for your report. 
The issue has been fixed in magento/magento2#20918 by @rav-redchamps in 2.3-develop branch
Related commit(s):
 - [e062906ed76ffbc3e2226d42c43c9be023391f8d](https://github.com/magento/magento2/commit/e062906ed76ffbc3e2226d42c43c9be023391f8d)
 - [ae5b032443f68742bab92b71753c697a4f66cd9b](https://github.com/magento/magento2/commit/ae5b032443f68742bab92b71753c697a4f66cd9b)
 - [1a73182ab6010d6ed6dc2b0583dc0dbce2119562](https://github.com/magento/magento2/commit/1a73182ab6010d6ed6dc2b0583dc0dbce2119562)
 - [33e702e93558c437aa5386e8e36077b36e19dcea](https://github.com/magento/magento2/commit/33e702e93558c437aa5386e8e36077b36e19dcea)
 - [1c3d10e05a3264c6f08575822d466e96e0d06a52](https://github.com/magento/magento2/commit/1c3d10e05a3264c6f08575822d466e96e0d06a52)
 - [e3e65a43c721767993cd5214445150badef57a9f](https://github.com/magento/magento2/commit/e3e65a43c721767993cd5214445150badef57a9f)
 - [6d9d7f0e2fc984e555f156c17f259eccc252e749](https://github.com/magento/magento2/commit/6d9d7f0e2fc984e555f156c17f259eccc252e749)
 - [9e07d6e1e8118baa9638f6c3525806d0b1da3dd7](https://github.com/magento/magento2/commit/9e07d6e1e8118baa9638f6c3525806d0b1da3dd7)
 - [bca244cbcf2365f0dafa02617117147e3b363ccf](https://github.com/magento/magento2/commit/bca244cbcf2365f0dafa02617117147e3b363ccf)

The fix will be available with the upcoming 2.3.3 release.

**Comment by rhoerr** [comment]
Note https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Customer/Block/Adminhtml/Edit/Tab/Cart.php#L248 is currently bugged -- if the customer being viewed has no active quote, the collection will only be filtered by `parent_item_id is null`, and you'll get all parent items for all customers and quotes. Which is not right.

        $quote = $this->getQuote();
        if ($quote) {
            $collection = $quote->getItemsCollection(false);
        } else {
            $collection = $this->_dataCollectionFactory->create();
        }
        $collection->addFieldToFilter('parent_item_id', ['null' => true]);
        $this->setCollection($collection);

**Comment by engcom-Charlie** [comment]
Hello @rhoerr 
This issue has been fixed in #20918 by @rav-redchamps in 2.3-develop branch.I have to close this issue.
Your comment looks like as a separate issue. Can you create a new issue? 
Thanks for contributing!
