### ISSUE TITLE
test idea

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2#6295]
Just testing - do not delete

### Preconditions

1. 
2. 
### Steps to reproduce

1. 
2. 
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by piotrekkaminski** [comment]
test comment1

**Comment by piotrekkaminski** [comment]
test comment 2

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/boards/id/feature-requests/messages/id/9)

**Comment by piotrekkaminski** [comment]
Thank you for your submission.
The Magento 2 GitHub repository is used to capture code and documentation issues.
New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.
This discussion is now available at [Magento Forums](https://community.magento.com/t5https://community.magento.com/t5/Magento-2-Feature-Requests-and/test-idea/idi-p/44551).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/test-idea/idi-p/44555).

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

The Magento 2 GitHub repository is used to capture code and documentation issues.

New feature requests and existing feature improvements should be submitted to the Magento 2 Feature Requests and Improvements forum.

This discussion is now available at [Magento Forums](https://community.magento.com/t5/Magento-2-Feature-Requests-and/test-idea/idi-p/44560).

**Comment by piotrekkaminski** [comment]
Just testing (a [link](http://www.google.com))

**Comment by hostep** [comment]
@piotrekkaminski: since you start closing feature requests on Github and moving them to the forums.
Do you know a way of subscribing to those new topics on the forums without leaving a comment and checking 'Email me when someone replies', because now I have to add these silly dummy comments to subscribe to threads I was subscribed to on Github and I don't find another way to do this.

Also: please make the forums perform at least twice as fast as they are now, because they are slow as hell.

Thanks!

**Comment by hostep** [comment]
@piotrekkaminski: can you please reconsider this idea you have (which you made without consulting with the community beforehand :s)? The forums have a horrible UX. It's really hard to work with them, Github is much easier to use.

Instead of moving everything from Github to the forums, is it an idea to create a new Github repo and move the issues over to the new repo?
There seems to be a utility which can automate this: https://github.com/google/github-issue-mover

Thanks for considering this!

If others have interest in this, please chime in, maybe I'm the only one who hates the forums?

**Comment by Ctucker9233** [comment]
@hostep I wholeheartedly agree. The forums have a terrible response rate (as in none) and no one that works for magento seems to frequent it. Same thing goes for stackexchange.
