### ISSUE TITLE
Can't save Customizable options

### ISSUE THREAD

**Issue by bachlee89** [magento/magento2#6305]
Can't save customizable options Magento 2.1.0

Steps to reproduce
1. Go to Catalog/Product then edit a product
2. In Customizable Options tab, add option:
-  Option Title: Test
-  Option Type: Dropdown
- Options: 
  ![image](https://cloud.githubusercontent.com/assets/5562316/17924116/7d92a654-6a11-11e6-83c1-54498383e9d8.png)

Expected result
- Option should be saved

Actual result
- Can't save option with Title: 0

**Comment by yaroslavGoncharuk** [comment]
@bachlee89 thank you for your report, we created internal ticket MAGETWO-57705.

**Comment by magento-engcom-team** [comment]
@bachlee89, thank you for your report.
We've created internal ticket(s) MAGETWO-57705 to track progress on the issue.

**Comment by luismiguelyangehuaman** [comment]
I'm working on this issue for #MM17ES

**Comment by angelEbizmarts** [comment]
I’m working on it #distributed-cd

**Comment by Madhumalak** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@Madhumalak thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment]
Hi @bachlee89. Thank you for your report. 
The issue has been fixed in magento/magento2#15357 by @Madhumalak in 2.2-develop branch
Related commit(s):
 - [474946c0b8997aa6636ad19a06729339c668948c](https://github.com/magento/magento2/commit/474946c0b8997aa6636ad19a06729339c668948c)
 - [9dd89455549fc6bcf4d10af9dd874d1610dc525b](https://github.com/magento/magento2/commit/9dd89455549fc6bcf4d10af9dd874d1610dc525b)
 - [641c5565421c53a48158d8eef804d6652c327a51](https://github.com/magento/magento2/commit/641c5565421c53a48158d8eef804d6652c327a51)
 - [3c444ce889b1a2dd6fc03d5222122d94a67f09d0](https://github.com/magento/magento2/commit/3c444ce889b1a2dd6fc03d5222122d94a67f09d0)

The fix will be available with the upcoming 2.2.7 release.

**Comment by sidolov** [comment]
Hi @bachlee89. Thank you for your report. 
The issue has been fixed in magento/magento2#17609 by @jignesh-baldha in 2.1-develop branch
Related commit(s):
 - [cd9ba043a806f857790e1a68972634fa9dca6eb3](https://github.com/magento/magento2/commit/cd9ba043a806f857790e1a68972634fa9dca6eb3)
 - [1bcd7dc8802c88c060b90d517803547b3a1019e1](https://github.com/magento/magento2/commit/1bcd7dc8802c88c060b90d517803547b3a1019e1)
 - [0a168488a8578bd4475c63c0eb9a8b12b75cde9f](https://github.com/magento/magento2/commit/0a168488a8578bd4475c63c0eb9a8b12b75cde9f)
 - [470320e7ca5222e72d194d44545b929f929f4d63](https://github.com/magento/magento2/commit/470320e7ca5222e72d194d44545b929f929f4d63)

The fix will be available with the upcoming 2.1.16 release.

**Comment by magento-engcom-team** [comment]
Hi @bachlee89. Thank you for your report. 
The issue has been fixed in magento/magento2#17607 by @jignesh-baldha in 2.3-develop branch
Related commit(s):
 - [d60b3cfbd8172afcccadcdef5da1774bf8628d36](https://github.com/magento/magento2/commit/d60b3cfbd8172afcccadcdef5da1774bf8628d36)
 - [71ce3fa2ee3487c6845286340c35937ec5083b47](https://github.com/magento/magento2/commit/71ce3fa2ee3487c6845286340c35937ec5083b47)
 - [170d02962d126e314980bd2382efee3c5ffa653b](https://github.com/magento/magento2/commit/170d02962d126e314980bd2382efee3c5ffa653b)
 - [6aebfe8c6007a71a5b2601e8050c1405b2685231](https://github.com/magento/magento2/commit/6aebfe8c6007a71a5b2601e8050c1405b2685231)

The fix will be available with the upcoming 2.3.0 release.
