### ISSUE TITLE
Paypal Duplicate invoice error on magento 2.1.1 ce

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#6417]
Magento 2.1.1 fresh install
Changed to Dev Mode
Add a new product
Enabled paypal Sandbox
Payment action:order
tested payment : duplicate invoice error
php 5.6.23
Maria DB
![paypal error](https://cloud.githubusercontent.com/assets/19605497/18133182/6d3f4bce-6f91-11e6-98b1-ae4623beebe6.png)

**Comment by asemenenko** [comment]
Hi @nmallepally such error appears if the PayPal account already has a transaction registered with the same Order Number (for the PayPal it is Invoice ID). This happens when you have to stores that use the same number sequence for the sales documents. In order to fix that you will need to go to your PayPal account, My Account > Profile > My Selling Tools > Credit Card Statement Name > "Allow multiple payments per invoice ID"

**Comment by krnareshkumar23** [comment]
Below is the Direct link that might be helpful

https://www.paypal.com/cgi-bin/webscr?cmd=_profile-pref
