### ISSUE TITLE
Magento 2.1 to 2.1.1 upgrade .htaccess overwrite

### ISSUE THREAD

**Issue by dapdx** [magento/magento2#6419]
Just wanted to point out that when using the admin to upgrade to 2.1.1 from 2.1 your .htaccess file gets overwritten. Since we use multiple store fronts our domain magrun commands were deleted so our storefronts weren't working. Not sure what other stuff people might have in their .htaccess, but just a warning.
### Preconditions

Magento 2.1 upgraeing to 2.1.1 via admin panel
PHP 7
**Updated(09/27/2019):** Still actual in further upgrading from 2.1.1 directly to 2.3.2.
### Steps to reproduce

Used admin panel to upgrade to new version
### Expected result

Upgrade to new version correctly (which so far all other elements do)
### Actual result

 .htaccess file was overwritten causing domains for multistores to not link correctly.

**Comment by hostep** [comment]
Related/duplicates:
- https://github.com/magento/magento2/issues/6285
- https://github.com/magento/magento2/issues/4930
- https://github.com/magento/magento2/issues/6221
- https://github.com/magento/magento2/issues/4697

**Comment by veloraven** [comment]
Closed as duplicate.

Additionally Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

One of corresponding issues was already moved to forum. You can find it [here](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Unable-to-modify-htaccess-in-static-directory/idi-p/45735).

**Comment by udovicic** [comment]
Since this task is the only one in series that I have found to be still open, I would like to point out that this does not only affect .htaccess. It affects all files that are placed there by magento-base module when doing composer install. So anything outlined there will be overridden in your code. And in any future case where new thing is added to that module and has the same naming as my code can potentially remove if from my site.

**Comment by magento-engcom-team** [comment]
@dapdx, thank you for your report.
We've created internal ticket(s) MAGETWO-82686 to track progress on the issue.

**Comment by czettnersandor** [comment]
I found this ticket because I was looking for why `composer install` is overwriting my changes during deployment. It's not only updating the .htaccess file but `dev/tools/grunt/configs/themes.js`.

Since it's essential to add themes to this file to compile .less files and there's no other way to achieve the same, I think this "feature" needs rethinking.

Maybe don't do this overwrite on `composer update` as these files are not part of the /vendor folder, but do this outside of update, you can create a grunt task or composer script the developers can run, inspect changes in diff, then commit to their project repository.

**Comment by wpalmer** [comment]
In either case, surely any file which is managed via `composer install` should be added to `.gitignore`?

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment]
Keeping in mind that the script https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html#upgrade-cli-script is for upgrading to 2.3.0, I will add reproduced on 2.3-develop, because release line 2.3.x is the reason for creating this script

**Comment by magento-engcom-team** [comment]
@TomashKhamlai Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97063`, `MAGETWO-97064` were created

**Comment by ihor-sviziev** [comment]
Seems like the only one possible solution will be switching to nginx + php-fpm, that's basically fixes all the issues as all configuration is NOT in the magento2 directory.

**Comment by hostep** [comment]
I actually think it's a great feature and this probably isn't a bug.
If you put your `.htaccess` file in git (which you probably should), you should notice it when a magento upgrade overwrites it on your local machine. When that happens, you can decide how to merge your own custom changes with the new changes from Magento. I'm considering this a good thing, because the changes from Magento in that file can be important.
Whereas if you use nginx, you probably won't notice the change in the `nginx.conf.sample` file and might run into issues if you aren't paying close attention when that file changes...

Anyway, in our deploy flow, we do something like the following, this way the `.htaccess` file on the server is always in the state as it is in git:
```
composer install ...
git checkout pub/.htaccess
```

**Comment by ihor-sviziev** [comment]
Hi,

I re-analyzed this issue again and saw that fixing this issue will not be easy, while it is too low a priority. 
It's better to close this issue and for those who are getting it - use one of the options listed below.

**Workarounds:**
1. add one more command after the `composer install` to your deployment process, like this:
```bash
composer install ...
git checkout pub/.htaccess
```
2. switch from apache to Nginx + php-fpm (to be honest, this is a way better option as, in general, Magento will work a bit faster).
