### ISSUE TITLE
Can´t finish upgrading to M2.1.1 with SSH CLI  [InvalidArgumentException]  

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#6429]
- I can´t finish upgrading M2.1 to M2.1.1 due to cli command: php bin/magento setup:upgrade not works afther: composer update.
  ![cli](https://cloud.githubusercontent.com/assets/16081377/18157819/e819ea3c-701f-11e6-9f84-ec7172cc068c.jpg)

Best Regards
Toni

**Comment by paales** [comment]
Run `php bin/magento` to see what error you are running into

**Comment by salelsol** [comment]
Afther rename var/generation folder  I´m running bin/magento setup:upgrade previously removed vendor folder but now I´m this issue when go to backend:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Sales data: current version - 2.0.2, required version - 2.0.3

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Magento_Sales data: current version - 2.0.2, required version - 2.0.3
#0 /home/39552-42818.cloudwaysapps.com/ybwnkuzght/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#1 /home/39552-42818.cloudwaysapps.com/ybwnkuzght/public_html/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#2 /home/39552-42818.cloudwaysapps.com/ybwnkuzght/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /home/39552-42818.cloudwaysapps.com/ybwnkuzght/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#4 /home/39552-42818.cloudwaysapps.com/ybwnkuzght/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#5 {main}

Best Regards
Toni

**Comment by paales** [comment]
In general, before upgrading run: `rm -rf var/di var/generation var/cache var/page_cache`

The Exception says you should run:
`bin/magento setup:upgrade`

**Comment by salelsol** [comment]
- At end just upgraded to M2.1.1 ( I´m thinking the best issue was with var/generation folder I don´t removed it completly all files inside before running bin/magento setup:upgrade command line).

Best regards
Toni

**Comment by paales** [comment]
@salelsol If your problem is solved, could you close the ticket?

**Comment by paales** [comment]
:)

**Comment by shanevbg** [comment]
I think that sometimes people miss a step when upgrading Magento from the command line
Here are the commands I run (after doing a backup of the server)
[First command is because Magento overwrites my .htaccess and I have to make sure the settings are correct after]
'cp .htaccess htaccess.sav` 
`sudo -H -u www-data bin/magento maintenance:enable`
`sudo -H -u www-data composer require magento/product-community-edition 2.1.2 --no-update`
`sudo -H -u www-data composer update`
`chmod +x /bin/magento`
`rm -rf var/cache/* var/page_cache/* var/generation/*`
`sudo -H -u www-data bin/magento setup:upgrade`
`sudo -H -u www-data bin/magento setup:di:compile`
`sudo -H -u www-data bin/magento setup:cron:run`
`sudo -H -u www-data bin/magento setup:cron:run`
'cp .htaccess htaccess.mag` 
'cp htaccess.sav .htaccess` 
`sudo -H -u www-data bin/magento maintenance:disable`
