### ISSUE TITLE
Template path hints behavior

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#647]
I've enabled the template path hints for a website but they show up on the admin also.  
I don't know if this is a bug or a feature.  
I know that a lot of developers asked for template path hints in the admin on magento 1.x but my money is on a bug. If this is a feature I'm almost sure that this is not the way it should work.  

**Pre conditions**:
 - Installed Magento 2. alpha93. 
 - Used [sample data from here](https://github.com/tzyganu/m2-sample-data). I don't think the sample data is the issue. Sample data has 1 website and 3 store views.  

**Steps to reproduce**
- Go to the backend: Stores->Configuration->Developer. 
- Change the scope to `Main website` (The `Debug` fieldset did not appear in the `Default config` scope)
- In the `Debug` fieldset changed the values for `Template Path Hints` and `Add Block Names to Hints` to `Yes`. 
- Saved the config.

**Expected Result**  
 In the frontend I should see the template path hints for all the blocks and template in any page.

**Actual result**  
Beside the expected result I also see in the backend the template path hints.  

**Additional info**  
All caches are off.  
I ran this query on the database   
`select * from core_config_data where path = 'dev/debug/template_hints'`.
I got only one result:  

|config_id|scope|scope_id|path|value|
|----|---|---|----|---|
|78|websites|1|dev/debug/template_hints|1|

Changing the `Template Path Hints` back to `No` made the template hints disappear from the backend also.  

I really hope this is a bug related to template path hints and not with the config loader.

**Comment by ctubio** [comment]
Sorry for that recent duplicate.

Please, do not mix the feature of allowing template hints in the adminhtml pages with the bug of the template hints showing in adminhtml pages even if the template hints are just enabled for a single store view.

If template hints should be allowed in adminhtml pages, a new configuration option should be added rather than force it implicit together with whatever similar option already exists.

thank you''

**Comment by erikhansen** [comment]
Just recently encountered this issue. I enabled Template Path Hints for a specific website and hints were displaying in the admin. 

I definitely appreciate the ability to enable Template Path Hints in the admin, but there should be an explicit way to do that, rather than admin hints being enabled any time hints on the frontend are enabled.

**Comment by tkacheva** [comment]
Thank you all for your input. I will update you once we fix the issue

**Comment by tkacheva** [comment]
MAGETWO-42869

**Comment by piotrekkaminski** [comment]
This should be fixed now and soon be available on github.

**Comment by jigs-bc** [comment]
can you please give us pull request ?
