### ISSUE TITLE
PayPal PayFlow Pro in Multiple Addresses Checkout

### ISSUE THREAD

**Issue by manishclarion** [magento/magento2#6506]
In Magento 2.1 there is a bug when using Multiple Addresses in Checkout.
When users selects multiple addresses in checkout the "PayPal PayFlow Pro Credit Card" payment method does not work. Tested it with "check/Money order" and it works fine but with Payflow pro it does not work.
### Preconditions

Magento 2.1.1 CE
PHP Version 5.6.3
### Steps to reproduce
1. Disable OnePage checkout
2. Enable Multiple Address option from the Configuration --> Sales --> Multi shipping Settings
3. Enable "paypal payflow pro" from the payment methods. (Specially the credit card option)
4. Add product to cart from frontend and proceed to checkout.
5. Select Multiple addresses from on the checkout page.
6. Select Shipping methods and proceed.
7. You will see payment method is not loaded on the review order page.
### Expected result
1. Payment Method must be visible on the Billing Information page.
### Actual result
1. Payment method section is blank.
2. See attached screen
   ![billing information magento commerce](https://cloud.githubusercontent.com/assets/16595781/18271230/ac66d378-744e-11e6-8b03-22bd4c595dc7.png)
   shot.

**Comment by andimov** [comment]
@manishclarion
Thanks for reporting.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by manishclarion** [comment]
@andimov  Updated the issues as per "issue reporting guidelines"

**Comment by manishclarion** [comment]
@andimov  Is there any estimation/timeline when you would be able to fix this as we are implementing this functionality in one of our Application?

**Comment by asemenenko** [comment]
Hi @manishclarion  current implementation is build using transparent redirect approach. That means we send credit card information directly from a browser to a payment gateway. Existing multi address checkout creates multiple sales orders and requires multiple transactions to be created which can not be integrated seamlessly to Payflow since we need to deal with a total amount for all orders to the client. We have item in the backlog to improve this part of the multiaddress checkout that will allow us to properly integrate OOTB Payflow by having a single payment transaction only.

**Comment by manishclarion** [comment]
@asemenenko  Thank you for the information. That really helped us.

**Comment by dyushkin** [comment]
@manishclarion, thank you for reporting. We are closing this issue, feel free to reopen it if you have more questions.

**Comment by dmitrii-fediuk** [comment]
My [**Stripe** extension](https://mage2.pro/c/stripe) does support multishipping: [an example of a multishipping checkout with Stripe payment](https://mage2.pro/t/4411).
