### ISSUE TITLE
Changing shipping fields does not get updated on checkout last step

### ISSUE THREAD

**Issue by devhn** [magento/magento2#6537]
### Preconditions

1. Magento CE 2.0.7.
### Steps to reproduce

1. Add a product to cart and go to checkout
2. Fill out the shipping fields on checkout step 1
3. Go to checkout step 2 and then return back to step 1
4. Change any shipping field (for example: change name from John to Bill)
5. Go back to step 2
### Expected result

1. When changing the shipping fields on step 1, they should get updated on step 2
### Actual result

1. Shipping fileds do not get updated, they stay the same as the first/initial submit upon the first entry

**Comment by SerhiyShkolyarenko** [comment]
@devhn thank you for reporting!
do you perform those steps as guest or as a registered user?
Is it reproducible for you on 2.1.1?

**Comment by devhn** [comment]
@SerhiyShkolyarenko as guest. Yes, also reproducable in 2.1.1.

`shipping-information` gets updated ([screenshoot](http://imgur.com/a/Hu8zU) - "new name" and "new address" is the newly updated data when going back to Shipping step) but fields don't get populated within `billing-address-details` on step 2.

**Comment by SerhiyShkolyarenko** [comment]
@devhn checkout worked for me exactly like you described. It's **expected behavior**. Please pay attention that the checkbox "My billing and shipping address are the same" is unchecked after step 5.
This is how it works internally.
0. On checkout start both billing and shipping address are empty
1. When you fill shipping address and click "Next", the server(Magento) saves it. Then Magento checks that billing address is empty and fills it with the same data. It's a reasonable assumption for most cases. Since it happen billing and shipping address are considered as set.
2. When you go back, edit shipping address and save it on "Next" button, shipping address is saved, but billing addresss is considered as set and is not updated. We uncheck the "My billing and shipping address are the same" checkbox only. So, everything you described is corresponding to internal logic.
Thank you for your attention. Please, feel free to leave comments here event the issue is closed.
