### ISSUE TITLE
Feature Request:Payflow Pro card authorizations costing hundreds per month

### ISSUE THREAD

**Issue by tstamplis** [magento/magento2#6542]
Because Mangento (2.1.0 in this case) does $0 card authorizations on payflow pro now for credit card transactions, it is costing merchants .30 cents PER card authorization, on top of the .30 cent authorization attached to the actual sale.  This adds up to hundreds of dollars per month in additional fees just because of this new way Magento handles payflo pro integration.

I would request the ability to disable this "feature" so merchants that do not want to increase their processing fees for the sake of this method of authorization have the option to opt out.

**Comment by andimov** [comment]
@tstamplis 
Thanks for reporting this issue.
Please use our issue reporting template to describe this issue. The template specifies the version and configuration information we need to assess your issue. See the Issue reporting guidelines for more information.

**Comment by tstamplis** [comment]
I hope this is correct?!?

# Preconditions

Magento CE 2.1.0
PHP 7.0.10
MySQL 5.6.31

# Steps to reproduce

Setup Paypal Payflow Pro payments method
Add product to cart and complete checkout using credit card (Payflow Pro)

# Expected result

Dollar amount of transaction is sent to paypal as authorize and capture,
Paypal assess a .30 cent authorization fee and a % of the sale in merchant processing fees.

# Actual result

Magento sends a $0 "Card Authorization" to paypal first to verify the card is valid.
Paypal assesses a .30 cent "Card Authorization" fee to the monthly processing fee
Magento receives "Approved" status, and no fraud filters are triggered.
Magento sends another authorization and sale for the actual dollar amount of the order.
Paypal assesses a .30 cent authorization fee and a % of the sale in merchant processing fees.

# Important

This way of sending a $0 card authorization first, followed by an authorization and sale second, causes an additional .30 processing fee for each credit card transaction.  Because the card authorization is for $0, paypal assesses the fee to the monthly processing fee which is normally $30.  Paypal then assesses another .30 cent fee and % of the sale amount which is deducted from the gross amount captured when the second transaction for the actual dollar amount is processed.  Confirmed by Paypal Payflo Pro Merchant Services representative.

# Request

Allow merchants the ability to disable the $0 "Card Authorization" step and simply send the sale amount as authorization AND capture.

**Comment by tstamplis** [comment]
Apologies, didn't mean to close it!

**Comment by asemenenko** [comment]
Hi @tstamplis 
Payflow implementation is build using recommended implementation option via Transparent Redirect. 
Authorization transaction created via Transparent Redirect will always be accepted by Payflow since TR requires AVS and CVV settings to be turned off (see [documentation](https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/paypal_transparent_redirect.pdf)) to have transaction accepted by gateway. In this case every transaction will be accepted no matter what happens with AVS/CVV results. Also even if we will try to void such transaction and notify a customer on the storefront - we will have to deal with multiple asynchronous calls (remember we need to Void auth with negative CVV results, plus Auth transaction happens asynchronously if TR is used) that per our experience will results in periodic issues with either a) having garbage "cancelled" and "pending" sales orders without transactions or authorizations without sales orders in the system, resulting into stock being updated wrong b) non voided transactions and customer calls

Account Verification allows to get rid of all the problems mentioned above giving us a reliable server-to-server implementation.

**Comment by tstamplis** [comment]
Thanks for the explanation.  The feature request would then be to offer a standard integration option alongside the transparent redirect method.  Regardless of requirements to properly integrate transparent redirect, the unintended (I assume unintended, ebay companies wouldn't be collaborating to increase merchant fees on unsuspecting merchants!) result is merchants having to pay double authorization fees per credit card transaction.  In my case, this will average $300 per month.  I'm sure there are other Magento merchants who will pay much more.  Perhaps this is something we will have to look to the community to provide.

**Comment by asemenenko** [comment]
@tstamplis Possible option i see here is to add this with a notice that explains to merchant all the issues that will appear if it is disabled. It will be up to the merchant how to balance reliability (results in sales loss, support costs) vs transaction fees increase.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Feature-Request-Payflow-Pro-card-authorizations-costing-hundreds/idi-p/48314).

**Comment by rav-redchamps** [comment]
@tstamplis We have developed a tiny extension to solve this problem. You can find the extension [Payflow Pro Disable Authorization](https://redchamps.com/payflow-pro-disable-authorization-magento2-extension.html)  [here](https://redchamps.com/payflow-pro-disable-authorization-magento2-extension.html)
