### ISSUE TITLE
Delete address api is not working

### ISSUE THREAD

**Issue by impekablenarender** [magento/magento2#6552]
### Preconditions

1. Magento Rest Api 2.0
### Steps to reproduce

1. unable to delete address
2. DELETE http://{base url}/rest/V1/addresses/{18}     with auth token
### Expected result

1. Selected address should be deleted from list
### Actual result

1. 401 Unauthorized http://{base url}/rest/V1/addresses/18 
   {"message":"Consumer is not authorized to access %resources","parameters":{"resources":"Magento_Customer::manage"}}

**Comment by mbrinton01** [comment]
Hello @impekablenarender, I was not able to replicate your issue.  The error message you are getting seems to indicate it's a problem with authentication instead of the specific API route.

Here are the steps that I took:
1. Get admin token
   `POST http://<hostname>/index.php/rest/V1/integration/admin/token`
   with body of `{"username":"admin", "password":"<password>"}`
   Result should be admin token
2. Check address
   `GET http://<hostname>/index.php/rest/V1/addresses/<id>`
   with header of `Authorization = bearer <token from step 1>`
   Result should be the address with that id
3. Delete address
   `DELETE http://<hostname>/index.php/rest/V1/addresses/<id from step 2>`
   with header of `Authorization = bearer <token from step 1>`
   Result is `"true"`

Please try these steps and reply back.

More info on Authentication here: http://devdocs.magento.com/guides/v2.0/get-started/authentication/gs-authentication-token.html

**Comment by mbrinton01** [comment]
Hello @impekablenarender, I am closing this issue since there has been no response. If you are still having trouble with this please open a new issue. You may add me to any new related issue.
