### ISSUE TITLE
Product dissapear from cart when "out of stock"

### ISSUE THREAD

**Issue by maqlec** [magento/magento2#6583]
### Preconditions

1. Magento 2.1.1 with sample data
2. PHP 7.0.10
### Steps to reproduce

1. Add product to cart.
2. Go to cart
3. Change stock to 0 in admin panel
4. Refresh cart
### Expected result

1. Error message "Some of the products are out of stock."
2. Error message "This product is out of stock." on the product which stock we changed
### Actual result

1. Error message "Some of the products are out of stock."
2. The out of stock product has dissapeared from cart!! There is no possibility to remove this product from cart. Only by minicart

**Comment by maqlec** [comment]
It works correct in Magento 2.0.9

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-58345. Thanks for reporting

**Comment by heldchen** [comment]
seems related to #6388

**Comment by alena-marchenko** [comment]
Hi @maqlec 

Fix for MAGETWO-58345 is merged to develop branch, closing the issue.
Thank you!

**Comment by korostii** [comment]
Hi @alena-marchenko,

Could you please provide an answer to the following questions:
1. Is there any official timeline for the 2.2 release which you could announce publicly?
2. Could you please briefly explain, what's the recommended way of using the fixes provided for the develop branch if you're a merchant or an integrator currently running 2.1.x CE in production? A link to documentation would be perfect (if available).

**Background for my questions:** 
I've seen numerous issues closed with the reason "merged to develop branch" and as I understand, develop branch corresponds to the future 2.2 version and there seems to be no publicly available date for its release. Many of those bugfixes don't reach 2.1.x releases for months straight.

To be honest, I don't see how is "merged to develop branch" an acceptable resolution to an acknowledged bug. Until the fix is officially released, a lot of the users are still struggling with it.
In my opinion, having these patches added into the nearest 2.1.x (or 2.1.x.x) releases right away would be perfect, but that doesn't seem to be happening for quite a lot of similar issues out here in on Magento2's GitHub. 

Considering that the switch to 2.2 will probably be somewhat resource-heavy and very delayed, it would make sense to have an alternative suggested officially to users of 2.1.x which would help use these numerous fixes in a safe and robust way (of which there seems to be none, to the best of my knowledge).

**Comment by PiskaManojkumar** [comment]
hi guys,
where can i get that module @maqlec mentioned above.
