### ISSUE TITLE
How I can change PO number in order?

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6600]
### Steps to reproduce
1. Send `[POST] /V1/orders`

``` json
{
  "entity": {
      "entity_id": 103,
      "payment": {
          "po_number":"si-103",
          "method":"purchaseorder",
          "entity_id":104
      }
  }
}
```

And if you send

``` json
{
  "entity": {
      "payment": {
          "po_number":"si-103",
          "method":"purchaseorder",
          "entity_id":104
      }
  }
}
```

You have

``` html
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getMethodInstance() on null in \vendor\magento\module-payment\Observer\SalesOrderBeforeSaveObserver.php:24
Stack trace:
...
```

This is bad.
### Expected result

PO number is `si-103`.
### Actual result

PO number is `NULL`.
### Additional info

[API documentation](http://devdocs.magento.com/swagger/index.html) salesOrderRepositoryV1

| Q | A |
| --- | --- |
| Magento version | 2.1.0 with sample data |
| PHP version | 7 x64 |
| Operating system | Windows 10 x64 |

**Comment by olysenko** [comment]
Hi, thank you for your report. Magento doesn't have business rules to edit  initial order information(except addresses). POST could be used only for new order creation, but not for update existing one. Your issue is more appropriate for the [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) than this forum. Closed
