### ISSUE TITLE
Magento caches broken pages if MySQL server dies in the middle of the connection

### ISSUE THREAD

**Issue by lahdekorpi** [magento/magento2#6639]
Usually when the configured MySQL server isn't responding or it's giving an error, Magento throws an exception as it should.
However, while our server was running low on RAM and MySQL got killed, I've noticed that at times if the request to the MySQL server dies while receiving data, Magento keeps on going and produces a broken page that then gets cached to the page cache (tested both the built-in cache and Varnish).
In both cases the output was the same. The page has the correct `<head>` with resources etc but the `<title>` and `<body>` have no content. Also, a 200 response is given out.
Testing this is a bit tricky, but I've managed to reproduce by loading a bunch of dummy traffic to / while forcefully killing MySQL.
### Preconditions

php: 7.0.10-2+deb.sury.org~xenial+1
"magento/product-community-edition": "2.1.1"
varnish-4.1.1 revision 66bb824
mysqld  Ver 5.7.13-0ubuntu0.16.04.2
### Steps to reproduce
1. Default install
2. Use page cache (built-in or Varnish)
3. Generate dummy traffic to /
4. Simulate killing the MySQL server due to memory running out
5. Load /
### Expected result
1. If the connection dies while receiving data, throw an exception and a non 200 HTTP code
2. Contents not getting cached due to an exception / non 200 HTTP code
### Actual result
1. 200 HTTP code
2. Existing but empty `<title>` and `<body>` tags
3. Empty page with just some resources in `<head>` gets cached into built-in cache or Varnish
4. Error is logged (sometimes): `main.CRITICAL: Warning: PDOStatement::execute(): MySQL server has gone away in vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228`

**Comment by KSaho** [comment]
I've just had an interesting issue with the Magento 2 Web API that has the same result, but with a twist.

**Preconditions:**
PHP 7.0.22-0ubuntu0.16.04.1
Magento CE 2.2.2
redis-cli 4.0.2
mysql 5.7.20

**Steps to reproduce:**
Default install
Set Mage environment to production
Use page cache (Redis) - Not sure if this has anything to do with it.
Call the Web API from a local machine to the server and saturate the number of connections with 160 pages + 10 items per page (1600 items total). Each page is a connection. I used my own Python (3.5) scripts with grequests.

**Expected result:**
If the issue is that the query is too large, the connection should break from MySQL's end and Magento should return a JSON message with the issue.

**Actual result:**
MySQL will crash, and in one instance it leaked the query. This could be an attack vector for leaking information from the server.

**Additional information:**
I have been trying all morning to reproduce the SQL leak, but I could not. I do not know what specific circumstances caused the SQL leak.

**Comment by magento-engcom-team** [comment]
@lahdekorpi, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by lahdekorpi** [comment]
This bug still exists and should be fixed.
