### ISSUE TITLE
Change locale settings to Spanish (Colombia) affect the behaviour of the shopping cart, It only accepts 1 item per product

### ISSUE THREAD

**Issue by javiermartinezruiz** [magento/magento2#6656]
### Preconditions

1. Magento ver. 2.1.1 and Magento ver. 2.0.9
2. PHP 5.6.25-2+deb.sury.org~trusty+1
3. MySQL 5.6.31
4. Ubuntu 14.04
### Steps to reproduce

1. Access to magento admin page and go Stores->Configuration->Local options -> Locale 
2. Change your locale settings to Spanish (Colombia)
3. Save the new locale
4. Update cache
5. Go to the store and add more than 1 item from a product to your cart.
### Expected result

1. I should be able to add any quantity of items from a product to my cart 
### Actual result

1. For some reason the cart only accept 1 item per product at time, even if you update directly the cart, it only accepts 1 item.
   This is a video when I reproduced the case
   https://youtu.be/4wIDyo6Flbk

**Comment by gerosalesc** [comment]
+1

**Comment by yaxa** [comment]
+1

**Comment by veloraven** [comment]
@javiermartinezruiz thank you for report.
We have created internal issue MAGETWO-59973

**Comment by AlexandreKhayrullin** [comment]
There is a workaround described in #7502 that we are using, but it involves editing a file in the Zend library (the file to edit might be different though between the Colombian and the Chilean Spanish locales).

**Comment by janmech** [comment]
Here is another option/workaround if you don't need multiple Spanish translations.

We are using this language pack: https://www.mageplaza.com/magento-2-spanish-language-pack.html

Instead of changing core files we installed the pack manually and changed the locale from es_AR to es_ES. 

To do so change the following files/lines to:

registarion.php:

```
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::LANGUAGE,
    'mageplaza_es_es',
    __DIR__
);
```

language.xml:

```
<?xml version="1.0"?>
<language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/Language/package.xsd">
    <code>es_ES</code>
    <vendor>mageplaza</vendor>
    <package>es_es</package>
</language>
```
php bin/magento cache:clean
php bin/magento setup:static-content:deploy es_ES

and select Spanish (Spain) as you store locale.

**Comment by slimzc** [comment]
Hi! if you see when send a decimal in qty field (like 3.0) the add to cart work normally. I created a "Before plugin" for Magento\Checkout\Controller\Cart\Add and Magento\Checkout\Controller\Cart\UpdatePost intercepting the request and transforming the qty params to decimal.

Was the way I found to doesn`t change the Core. Maybe override the Controllers with Preferences is another quick solution.

:)

**Comment by hoodpablo** [comment]
hey @slimzc dont you mind sharing your code, cannot make it work, Thks!

**Comment by jahicDario** [comment]
+1 Same problem, when locale is Bosnia and Herzegovina.

**Comment by barbanet** [comment]
The problem is on ZF definition. This affect M1 & M2 because both use the same libraries ZF1.
I've made a blog post (in spanish) with the explanation and the solution: http://www.damianculotta.com.ar/magento/bug-en-los-locales-es-en-magento-1-y-2

Also I made a PR to the Magento's ZF repository with the fix for es_* locales: https://github.com/magento/zf1/pull/9

@jahicDario can you check if the problem with your locale is similar to the es_AR (or es_CL, es_CO, es_UY, etc, etc)

**Comment by magento-engcom-team** [comment]
The issued has been fixed in https://github.com/magento/zf1/pull/9
@javiermartinezruiz thank you for report

**Comment by mateo2181** [comment]
I can't resolve this problem, I have the site configurated with spanish language. Someone continue with this problem? Thanks!

**Comment by kkTeam** [comment]
any solution?

**Comment by barbanet** [comment]
Hi @mateo2181 and @kkTeam !
Can you check, just for I+D purpouse, to apply the modification from https://github.com/magento/zf1/pull/9 on your local environment and validate the fix?
Which version of Magento are you using?
