### ISSUE TITLE
I really recommend magento to setup a testing environment for every version where user can test the bugs

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#6689]
Sry this is not a bug report but a recommendation.
We are following magento development from releasing on - and struggle hard with all the bugs.
What i realize is that lots of bugs are reported back meaning the magento team answers like "what version of xyz do you use" or "we cannot replicate this issue here" etc.

This is very time consuming for us users and also for the magento team i guess so i would really strongly recommend magento to set up demo stores ov each version and each upgrade so we users can test the bugs on official installed versions.

Also a recommendation for the server systems (Ubuntu/Debian), PHP, Nginx etc.) would be great so we users can use the same stable systems for our clients.

Me and my company are a bit tired of all the major bugs at the moment with magento 2 because some bugs seem to here for over half a year and are still there. Pls magento take this not as an attack but just a try to speed up bug fixing as a bug reported on your systems need no further pingpong in a bug ticket regarding versions, installed os etc. etc.

**Comment by piotrekkaminski** [comment]
We are working towards something that can help standarize the environment. Hope to be able to share more details in near future. Regardless of that, screenshots/videos + version info help a lot to avoid back and forth.

**Comment by benmarks** [comment]
**_NB: this is an important topic, but I'm not sure we will leave it open; as OP notes, it is not an issue. If closed, I'm sure we'll post a public location for discussion & follow up.**_

@andidhouse Thanks for taking the time to bring this up. It's important. @fooman has [commented about this online](https://twitter.com/foomanNZ/status/778792731267047424) as well.

Regarding part of your statement:

> Also a recommendation for the server systems (Ubuntu/Debian), PHP, Nginx etc.) would be great so we users can use the same stable systems for our clients.

...I'd be very curious to know the following: **have you seen our [DevDocs topic related to system requirements](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html)?**

If so: what does that document lack in order to accomplish what you describe?

If not: where did you look for setup info, and - now that you have seen it - does it work for you?

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/I-really-recommend-magento-to-setup-a-testing-environment-for/idi-p/49591).
