### ISSUE TITLE
Footer Links Widget CSS Issue

### ISSUE THREAD

**Issue by ghost** [magento/magento2#6712]
### Preconditions

1. Magento 2.1.1 CE
2. Luma Theme
### Steps to reproduce

1. Install Magento with sample content

OR
1. Add a block/widget for additional footer links
### Expected result

1. Additional footer links block should line up with default footer links
   ![footer_mage2 0 7](https://cloud.githubusercontent.com/assets/19348887/18757359/fff574f4-80c9-11e6-84cf-5c1d18aec261.PNG)
### Actual result

1. Additional footer links block do not line up with default footer links. There is a 20px margin.
   ![footer_mage2 1wrongcss](https://cloud.githubusercontent.com/assets/19348887/18757432/4cd1c606-80ca-11e6-874a-c2b2399a66a8.PNG)

Removing the margin CSS property makes the block display lined up correctly.
![footer_mage2 1propercss](https://cloud.githubusercontent.com/assets/19348887/18757462/6cc92cec-80ca-11e6-82db-529f5d6a54d7.PNG)

**Comment by vil11** [comment]
Hi
Thanks for reporting this. Internal ticket MAGETWO-58224.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-80112

**Comment by magento-engcom-team** [comment]
@crtsl, thank you for your report.
We've created internal ticket(s) MAGETWO-58224 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @crtsl the issue has been fixed in https://github.com/magento/magento2/pull/11063 by @fragdochkarl . The fix will be available in 2.2.1

**Comment by okorshenko** [comment]
Hi @crtsl. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1353 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 299109f1265fa15eeb3067e22c2638ff5907205e
 - 57318bf03bf6fe7f84b2956ffb5ecc1332bf41b3
 - 41cd961a217d30c4b7b051a775902c4fb40b84ea
 - 076b90398852478d93d1444f936ac483b4640a82
 - 435a6c200cd548b8765e5bc73b0458039a58645d
 - 5d174b873f8ba369d6504fb9d7ef30296816e2b1
 - a47b10dce854a2d21ead6b362b86ca3ddf595386
 - ab48cb176830ddab69fd1617cae96d76094ab167
 - 46be4c7ea59f6cfb9884f2bc5875245b1960edc6
 - eafc6f0a473547542c3ef80352dcd2be7128da87
 - 63b9e909f1173a51374d4cdfc68249baa66f0007
 - 2edfe9a30bb64f0a7e102bb335a89658b627bfad
 - ef5ddffb43a735627d09535b62fac2a41804a96a
 - 4ada797ece84c2f5eb55499e8bc3f75e0c7ef245
 - c5d9a019b0d51a51b452fd99b527e3b894874be2
 - 72e9e0732b98ea5b8f47bddc781dc47c688c3c58
 - 215180de0a3f6c4a16e02205732bfe8670293ad2
 - 685d50625b68dbb960988a6bfbbfc14455a6cb9e

The fix will be available with the upcoming 2.3.0 release.
