### ISSUE TITLE
Error with a nonexistent theme

### ISSUE THREAD

**Issue by springimport** [magento/magento2#6732]
### Steps to reproduce

Add theme folder with `registration.php`.

``` php
<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::THEME,
    'frontend/Magento/Simplicity',
    __DIR__
);
```

![example_1](https://cloud.githubusercontent.com/assets/18581994/18787565/6a048bb2-8171-11e6-82d2-2a0c766640ff.PNG)

Fix mistake: 'frontend/Magento/Simplicity'`=>`'frontend/Vendor/Simplicity',`

![example_2](https://cloud.githubusercontent.com/assets/18581994/18787601/7fa9ddf0-8171-11e6-81a1-04d342fa908e.PNG)

Go to `Magento/sample`.
### Expected result

Something like 404 not found or delete theme if theme folder is not found (and remove from table).
### Actual result

**Fatal error**: `Uncaught Error: Call to a member function getId() on null in /vendor\magento\framework\View\Model\Layout\Merge.php:751`

![example_3](https://cloud.githubusercontent.com/assets/18581994/18787776/470acfee-8172-11e6-9183-7c76fa6c3c53.PNG)
### Additional info

| Q | A |
| --- | --- |
| Magento version | 2.1.0 with sample data |
| PHP version | 7 |
| Operating system | Windows 10 x64 |

**Comment by veloraven** [comment]
@springimport thank you for your feedback.
Magento does not support Windows. You can fond Magento technology stack requirements [here](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html).
Can you confirm that issue is present as well when Linux is used as operating system?

**Comment by springimport** [comment]
@veloraven Currently no.

I think this error is not related with operating system.

**Comment by sevos1984** [comment]
That is an improvement and in backlog already, tiket MAGETWO-46425. At the moment magento can't remove themes from db if it was removed/moved from file system.

**Comment by springimport** [comment]
I understood, thanks for reply.

**Comment by piotrekkaminski** [comment]
It is critical theme removal leaves system in a state that does not results in exceptions. marking as a bug

**Comment by piotrekkaminski** [comment]
adding report MAGETWO-46231 to make sure uninstall command removes the theme from DB

**Comment by tkacheva** [comment]
Relates to #1596

**Comment by magento-engcom-team** [comment]
@springimport, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by korostii** [comment]
Hi @magento-engcom-team,

With all due respect, a comment from your colleague @piotrekkaminski (which can be seen above) makes it pretty clear that this is, in fact, a _bug_. 
Could you please kindly explain\elaborate, what's changed since then and why? Thanks in advance.
