### ISSUE TITLE
Bad ukrainian character encoding in minicart when Enabled JavaScript Bundling in production mode

### ISSUE THREAD

**Issue by yumicom** [magento/magento2#6733]
### Preconditions

1. Magento ver. 2.1.1
2. php version 7.0, MariaDB 10.1
### Steps to reproduce

1.  I manually translated into Ukrainian some phrases in minicart in file: /app/design/frontend/My/Met1/Magento_Checkout/web/template/minicart/content.html , utf-8 without boom.
### Actual result

 In developer mode good, but in production mode when Enabled JavaScript Bundling I see bad characters in minicart, other characters on all pages are good. 
Cache cleaned, magento setup:static-content:deploy command run.

**Comment by veloraven** [comment]
@yumicom thank you for your feedback.
Could you please provide exact phrases you translated?

**Comment by yumicom** [comment]
I translated several phrases in different files, for example "Go to Checkout" > "Оформити замовлення" in Magento_Checkout/web/template/minicart/content.html
I found a temporary solution to encode Ukrainian phrases for JavaScript: "Оформити замовлення" > "\u041E\u0444\u043E\u0440\u043C\u0438\u0442\u0438 \u0437\u0430\u043C\u043E\u0432\u043B\u0435\u043D\u043D\u044F"

**Comment by sevos1984** [comment]
Hi! Why don't you use csv files for translation or inline translates? I was able to translate mentioned phrase  and deployed bundled js without errors if translate using csv.

**Comment by yumicom** [comment]
I use csv file )), but not all phrases can be translated in such a way, it is a known Magento bug, maybe it will be fix in version 2.2

**Comment by sevos1984** [comment]
I know problem about cache and local storage that need to be cleared after deployment. If you mean these problems I will link this ticket to internal.

**Comment by yumicom** [comment]
Problem in bad characters encoding, in production mode when Enabled JavaScript Bundling. I must to use code converter.

**Comment by sevos1984** [comment]
Do you use any other options for js files like minify or merge? As with only bundling enabled everything is fine.

**Comment by yumicom** [comment]
I try to use other options for js files: minify and merge - no problems with encoding. Bad character encoding only in bundling enabled

**Comment by tkacheva** [comment]
@yumicom, please provide exact setting of your configuration as we can't reproduce the issue with only js bundling on

**Comment by yumicom** [comment]
My core_config_data.sql
[core_config_data.zip](https://github.com/magento/magento2/files/533464/core_config_data.zip)

**Comment by mvmenno** [comment]
Is there already a fix for this issue? I have exactly the same issue as Yumicom is having. 
I use 2.0.11 and i am deploying to the french language. 
This isue seems to be only happening if phrases are translated in the js-translation.json file.
In developer mode it works just fine but deploying using production mode breaks the encoding.

For example : 
"Extraatje voor de \u00e9chte klusser":"Un petit plus pour nos bricoleur"

**Comment by maqlec** [comment]
Polish language has the same issue.

**Comment by magento-team** [comment]
Internal ticket to track issue progress: MAGETWO-71647

**Comment by magento-engcom-team** [comment]
@yumicom, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by luckyduck** [comment]
Any update on this? Or maybe a reference to the commit for an extension? Would help me a great deal!

**Comment by vil11** [comment]
@luckyduck 
Initial issue is fixed (MAGETWO-71647) & delivered in https://github.com/magento/magento2/pull/10563 for 2.3.0.

**Comment by luckyduck** [comment]
Awesome, thank you so much @vil11 !

**Comment by grazianodimaio** [comment]
Is this fix available for 2.1.8 ?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
Hi @yumicom The issue was re-tested and we can confirm that it was fixed on the 2.3 release branch. We closing this issue as fixed due to upcoming 2.3 release that will be available soon.
