### ISSUE TITLE
Magento 2.1.1 saving product breaks image assingments (base, thumbnail etc..)

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#6743]
### Preconditions

1. Magento 2.1.1
### Steps to reproduce

1. Open a product in backend
2. Click 'Save' option
### Expected result

1. Saved product
### Actual result

1. Product saved successfully but image assingments gone. You should re-save product after selecting images.

**Comment by Ctucker9233** [comment]
I have this problem too. Same preconditions as OP. When I get the error, I try to re-assign images and save again. Even then sometimes it won't let me save. I have to go out of the catalog and back in and I usually have to recreate the product.

**Comment by miakusha** [comment]
Hi @rbostan , @Ctucker9233 
I cannot reproduce issue, please provide more information:
- its clear magento instance or upgrade from previously versions
- do you have any custom attribute

**Comment by cizgidekiadam** [comment]
Hi @miakusha 
There is not any installed extension.
Upgraded from 2.1 to 2.1.1 via composer (Previous 2.1 was a clear install)

**Comment by Ctucker9233** [comment]
@miakusha I use an extension called Ves Testimonial. However, with the extension turned off, the issue still occurs. I also upgraded from 2.1 to 2.1.1 via compressed .zip archive. I have some custom attributes, but the issue also occurs on products that don't use those attributes. It's a little hard to pin down because the error does not occur every time. If the issue occurs again, I'll be sure to document the steps and include some screenshots.

**Comment by Sergeacc** [comment]
Unfortunately, I could not reproduce the issue as you described it.
Please, upgrade Magento and check this issue on the latest Magento 2.1.x version.
