### ISSUE TITLE
Price sorting order should use indexed minimal price not the price attribute

### ISSUE THREAD

**Issue by paales** [magento/magento2#6751]
### Preconditions

1. 2.1.0
### Steps to reproduce

1. (1) Create a product with price 11 and with tier price 9.
2. (2) Create a product with price 10.
### Expected result

1. Sort order should be (1) and then (2).
### Actual result

1. Sort order is (2) and then (1)

**Comment by sevos1984** [comment]
To sort by tier price you should set tier_price attribute for sorting but there is an issue on that. Internal ticket MAGETWO-59234. Thanks for reporting.

**Comment by paales** [comment]
@sevos1984 I think it should just sort by minimal price, what if there is a special price, the same issue applies, right?

**Comment by IvanRybakov** [comment]
Any update?

**Comment by veloraven** [comment]
This issue has already been fixed in develop branch.
Closed.

**Comment by korostii** [comment]
I am very glad that the people who happen to be using the `develop` branch in production will have this issue resolved for them.
However, in which version will the fix be released for the rest of the users? 
You know, all the other mere mortals who use either composer-installed version or the package downloaded from the official website.
Could you please provide a link to the downloadable version/patch or a composer tag to upgrade to?

Otherwise I don't see how this issue is anywhere near being resolved and closed for the ordinary users (which is what you seem to imply).
IMHO it is misleading and confusing to see such an issue in "closed" state, not knowing the internals which can keep the issue on `develop` branch for months straight without ever appearing on any of the multiple upcoming releases. I've seen dozens of people upgrading to latest released version in order to get the fix... only to discover that it wasn't included into that release neither.

**Comment by epson121** [comment]
Are there any news on release date for this fix? Can you point to a patch we could apply to have this fixed on the stores in the meantime?

**Comment by tmrage** [comment]
Is not fixed in develop branch (tested 2.2.0-rc22)

**Comment by staniag** [comment]
Has not been fixed in develop branch (testen on 2.2.0-rc22)

**Comment by afoucret** [comment]
@veloraven : I suppose you refer to bab4284310b0e73b0ddd3d521ba07a81b30303f1 when you say the bug is fixed. Am I right ?

If so, I do not think allowing sort on tier_price solve the problem issued by @paales.
He want regular price sort by take care of tier_price.

The main problem is tier_price is not considered when indexing min_price and final_price.

Price are rendered using price modifier but sort (and filters) are done using the price index. So there is an inconsistency that can only be resolved by fixing price indexing to include tier_price in the the final_price (or min_price) computation.

IMHO the problem is :

1. `Magento\Catalog\Model\Indexer\Product\Price\AbstractAction:_prepareTierPriceIndex` implementation is very weak :
   * Website management when selecting all website
   * Confusion with the customer_group_id 0 (all_groups or not_logged_in)

2. tier_price column is often NULL in the price index as a result of this poor implementation (especially if you choose a tier_price that apply to all websites or to all customer groups)

3. Even if not null, the tier_price is not used in the computation of the final_price (or min_price)

IMHO, this issue should be reopen.

**Comment by afoucret** [comment]
This is a big issue when using Magento B2B which rely on tier_price to achieve the shared catalog custom pricing.

**Comment by magento-engcom-team** [comment]
@paales, thank you for your report.
We've created internal ticket(s) MAGETWO-59234 to track progress on the issue.

**Comment by gianiaco** [comment]
@afoucret i'm trying to understand if we are talking about the same issue [#13335](https://github.com/magento/magento2/issues/13335) , are we?

**Comment by okorshenko** [comment]
@mbrinton01 could you please look at this issue.

**Comment by okorshenko** [comment]
Confirmed from the PO side. Request is valid

**Comment by dhorytskyi** [comment]
Was fixed in
#https://github.com/magento/magento2/commit/56859b0c84cc41d03617800c930b937a12711e2f

**Comment by ishakhsuvarov** [comment]
@paales Closing this now, as fix is already available in `2.2-develop`. 
See comment above for commit reference.

Thanks!

**Comment by nkarthickannan** [comment]
@ishakhsuvarov 

Is this fix available in 2.2.4 release? If not, when can we expect this fix to be available for the production website?

**Comment by ishakhsuvarov** [comment]
Hi @karthickannan 
I do not have exact ETA for the fix but I assume it may be available with 2.2.6

**Comment by aaugusto-efi** [comment]
Will this also fix the issue of sorting by customer group price or does this only affect tier pricing?
