### ISSUE TITLE
Impossible to Create/Edit "CMS Block" for Super-Admin users in Magento Enterprise Edition

### ISSUE THREAD

**Issue by nuzil** [magento/magento2#6790]
### Preconditions
1. Magento EE - 2.1.1 - Clean Installation
2. System has 2 Websites
3. Was created separate Admin user/role and gave him an access just to 1 website (Magento EE Feature under System -> User Roles -> Role Resources)

<img width="1430" alt="screen shot 2016-09-29 at 13 12 20" src="https://cloud.githubusercontent.com/assets/1667889/18951627/74a6c542-8646-11e6-98e1-fa4325f763a4.png">
### Steps to reproduce
1. Logout and Login as this new Creates user
2. Go To: Content -> Blocks
3. Create New Block -> click Save
### Expected result
1. CMS Block Saved 
### Actual result
1. Error Message: Something went wrong while saving the block.
2. If try to debug an error message found a Warning:
   "Warning: array_intersect(): Argument #1 is not an array in /Users/alexlyzun/Projects/code/aboshop3/www/vendor/magento/module-admin-gws/Model/Models.php on line 1079"

**Comment by nuzil** [comment]
Also a question: Is it possible to make a Pull Request for Magento EE?

**Comment by veloraven** [comment]
@nuzil the GitHub issue tracker is intended for CE issues only, if your issue affects only Magento Enterprise Edition, you should contact Magento support instead of posting your issue here. 
There is no way to make a pull request for EE as only CE code is accessible in this repository. However if you have some solution you can propose it to the support team.
Please address this issue to Magento support as module you mentioned is present in EE only.
