### ISSUE TITLE
More settings for image storage

### ISSUE THREAD

**Issue by bubach** [magento/magento2#680]
Hi, I'd like to request just generally more settings for how and where images are stored. Possibly even fallback functionality for where to fetch images if not found in main path.  One issue I have in particular with the current code base is on this line:

https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product/Image.php#L501

Where store ID is set as part of the cache path.  In some webshops where you have 10+ stores and literally _all_ the images are identical, it's a huge waste to keep duplicates of every thinkable image size. Not to mention the server strain when clearing the image buffer.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-29125

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/More-settings-for-image-storage/idi-p/47146).

**Comment by VladimirZaets** [comment]
Hi @bubach. Thank you for your report. 
The issue has been fixed in magento/magento2#16006 by @nmalevanec in 2.3-develop branch
Related commit(s):
 - [0501e1794641116c99c2e69d6adf383ce26d9adb](https://github.com/magento/magento2/commit/0501e1794641116c99c2e69d6adf383ce26d9adb)
 - [731b58f10925f9fa88e9541db91d8706f8ddcb63](https://github.com/magento/magento2/commit/731b58f10925f9fa88e9541db91d8706f8ddcb63)
 - [7c3d53f4ee819958292d08ddc64ecbcd97353634](https://github.com/magento/magento2/commit/7c3d53f4ee819958292d08ddc64ecbcd97353634)
 - [0d06ad882506150ed5bb39386a2ff0805c0d07b6](https://github.com/magento/magento2/commit/0d06ad882506150ed5bb39386a2ff0805c0d07b6)

The fix will be available with the upcoming 2.3.0 release.
