### ISSUE TITLE
Store Default Currency still have old currencies

### ISSUE THREAD

**Issue by milinka** [magento/magento2#6832]
### Preconditions

1.  Store Default Currency still have old currencies: FIM (Markka). 
2.  Magento version 2
### Steps to reproduce

1. Start magento installation
2. Process to step: Step 4: Customize Your Store
3. Click to drop down for default currency: FIM (Markka).
### Expected result

1. FIM (Markka) Should be removed. Finland has moved to EUR in 2001
### Actual result

1. [Screenshot, logs]

**Comment by dthampy** [comment]
Internal jira -MAGETWO-60033 has been created for this issue.

**Comment by magento-engcom-team** [comment]
@milinka, thank you for your report.
We've created internal ticket(s) MAGETWO-60033 to track progress on the issue.

**Comment by ArjenMiedema** [comment]
The currencies are loaded from Zend Framework 1, which is not supported anymore by Zend and is currently maintained by Mgento. With the move to PHP 7.2, ZF1 will be removed completely (at least that's what I heard), so it won't be an issue anymore from that moment on.

If this should be solved in older versions of Magento as well, we should go through all files in vendor/magento/zendframework1/library/Zend/Locale/Data/ and remove the old currencies in all these files. It would be a good idea to have a full list of all deprecated currencies then, so we only have to do this once.

However, I'm not sure if this is an issue that requires to be solved. The list of old currencies is not that nice, but it doesn't actually break anything in a webshop. As long as you don't select these currencies, you'd be fine.

**Comment by larsroettig** [comment]
I think we should close this issue because of it doesn't actually break anything.

**Comment by MarekBo** [comment]
#WroCD

**Comment by SubrataBauri** [comment]
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment]
@SubrataBauri thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by ArjenMiedema** [comment]
@SubrataBauri I think that if we remove the deprecated Finnish currency, we should also remove all other deprecated currencies. For example all other European currencies that were used before the Euro are still in this list. Talking about the German Mark, French Franc, Spanish Peseta, etc. These currencies are deprecated since 2002.

I think other currencies have been deprecated in the past decades as well, but I'm not aware which currencies those are. But I think cleaning up this list with more then just one currency is useful. Not sure if you have the time, but it would be great if you can do this.

**Comment by brunoroeder** [comment]
This doesn't actually break anything and the old currencies are loaded from Zend Framework 1, which is not supported anymore.
