### ISSUE TITLE
Indian Currency Symbol is not shown up correctly

### ISSUE THREAD

**Issue by kapeel45** [magento/magento2#6846]
### Steps to reproduce

1. Go to Currency
2. Indian Standard Currency will be decoded one 
3. For now i m using RS.
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment]
@kapeel45 thank you for your feedback,
Please provide expected and actual result.
Please also provide exact and detailed steps you do including path to the section in Admin area, e.g. 'Open Stores -> Configuration -> ...' . As now it is hard to understand what is your exact problem is.

**Comment by hkbittla** [comment]
Me also facing the same issue with Indian Currency, its not showing,

steps to produce ->

in admin Go to Stores ->Currency Symbols

![image](https://cloud.githubusercontent.com/assets/22587341/19031226/819d6daa-8970-11e6-9c2f-cf1689b3bbf1.png)

**Comment by slopukhov** [comment]
@kapeel45 thank you for your feedback,
Please provide detailed information about version of Magento and information about your environment: operating system, versions of PHP, MySQL and web server.

Since on my environment, this problem can not be reproduced.
![result](https://cloud.githubusercontent.com/assets/8982177/19934655/1ce86bf4-a120-11e6-992c-31a7cce9fefb.png)

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
