### ISSUE TITLE
Product save validation errors in the admin don't hide the overlay

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#686]
If there is an error in the validation done before the product save in the backend, the overlay shown by the ajax call does not disappear. 
Steps to reproduce.  

 1.Create a product attribute and set the flag `Unique Value` to `Yes`. 
 2.Assign the attribute to an attribute set.  
 3.Create/Edit a product from the attribute set and add a value to the attribute created at step 1.
1. Create/Edit an other product from the same attribute set and fill in the same value from step 3 for the attribute created in step 1.
2. Save.

Expected result:
There should be an error message under the field for the attribute that should be unique. 
The user should be able to edit the product attribute values again.  
Actual result:
There is an error message under the field that should be unique but I cannot edit the product attribute values because the overlay does not disappear.

![Error](http://i.imgur.com/UKImkuW.png)

I'm sure the error can be reproduced just by returning an error message from the validate product method but I described a real life scenario.

**Comment by magento-engcom-team** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#695 by @osrecio in 2.3-develop branch
Related commit(s):
 - [898d0325e73c77db6b0d043825b510db713b4638](https://github.com/magento/magento2/commit/898d0325e73c77db6b0d043825b510db713b4638)

The fix will be available with the upcoming 2.3.3 release.
