### ISSUE TITLE
Unable to change country of manufacture default label value

### ISSUE THREAD

**Issue by wujashek** [magento/magento2#6879]
### Preconditions
1. Magento 2.1.1 fresh install.
### Steps to reproduce
1. Navigate to product attributes in admin panel
2. Edit country of manufacture attribute
3. Try to change default label
4. Hit save
### Expected result

Attribute is saved
### Actual result

![attribute rename error](https://cloud.githubusercontent.com/assets/677017/19105031/29271556-8ae0-11e6-9cb8-b36212a87150.png)

**Comment by praful-rajput** [comment]
Same problem.

Even no such option value saved in table 'eav_attribute_option' for attribute 'country_of_manufacture'. and Manage Options grid showing the options as disabled.  Really this renders magical. Can anybody tell how such attribute value is saving in product save ?

I created same king of attribute. Added Source module (Country), option are showing up in product form. but not saving value anywhere.  Please keep hope for help from you...

**Comment by dthampy** [comment]
Created an internal jira ticket for this issue ->MAGETWO-59882

**Comment by hansvanl** [comment]
Would love an update

**Comment by netzweltvimal** [comment]
Same problem with Magento ver. 2.1.3. 
I can't save labels for county_of_manufacture, status, tax_class_id, and so on..
For new custom created attributes , It is working fine.

**Comment by alexsergin** [comment]
Hello. What about this issue? Was it fixed already? Have the same problem.
Maybe someone know where to find values of this attribute in DB? I suppose this error is displaying because the first value is empty. Maybe try to set it's value to one of the folloving "No", "Empty".

**Comment by afavata** [comment]
Issue still present in 2.1.7... Please provide urgent update or work around
thanks

**Comment by magento-engcom-team** [comment]
@wujashek, thank you for your report.
We've created internal ticket(s) MAGETWO-59882 to track progress on the issue.

**Comment by afavata** [comment]
Same situation with Magento 2.2.0

**Comment by enriquei4** [comment]
I'm working on it for #SQUASHTOBERFEST 2017, I'll make the PR in a few minutes.

**Comment by MateuszChrapek** [comment]
#distributed-cd

**Comment by magento-engcom-team** [comment]
@MateuszChrapek thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by MateuszChrapek** [comment]
I've made pull request #14319 fixing this issue.

**Comment by magento-engcom-team** [comment]
Hi @wujashek. Thank you for your report. 
The issue has been fixed in magento/magento2#14319 by @MateuszChrapek in 2.2-develop branch
Related commit(s):
 - [6627eeec690162b71dde50a605aa2603220024d4](https://github.com/magento/magento2/commit/6627eeec690162b71dde50a605aa2603220024d4)
 - [58dc25b387303240f43ac6d8f64fa9dcfd0a1685](https://github.com/magento/magento2/commit/58dc25b387303240f43ac6d8f64fa9dcfd0a1685)

The fix will be available with the upcoming 2.2.5 release.

**Comment by magento-engcom-team** [comment]
Hi @wujashek. Thank you for your report. 
The issue has been fixed in magento/magento2#14714 by @rostyslav-hymon in 2.3-develop branch
Related commit(s):
 - [5a2e819da59e616a4026f8e05bb8dc15d6468d33](https://github.com/magento/magento2/commit/5a2e819da59e616a4026f8e05bb8dc15d6468d33)
 - [156dcc06b1e1b3c8e5c1c14af21fd0f206f0c8fd](https://github.com/magento/magento2/commit/156dcc06b1e1b3c8e5c1c14af21fd0f206f0c8fd)

The fix will be available with the upcoming 2.3.0 release.
