### ISSUE TITLE
Import validation leaking through to other accounts.

### ISSUE THREAD

**Issue by LiamFielding** [magento/magento2#6880]
Magento 2.2.0-dev

Steps to reproduce
1. Import for a while with multiple accounts. 

Expected result
1. Validation is contained for each user and only relates to their actions.

Actual result
1. Validation may state that validation has passed with no errors but this result is for another user - not the data you just tried to check.

I noticed when Magento said 9 of 9 entities were valid but my sheet only contained three. This is not a EOL problem the data was perfect (or at least I would know it is if I received my own results).

We have repeated this multiple times and it is not a coincidence or error on our part, unless this is a setting somewhere (why would it be?)

**Comment by AlexWorking** [comment]
Hello, @LiamFielding. We couldn't reproduce this issue. Probably it has been already fixed. If You are still able to reproduce it please confirm it and give us more detailed picture of how You do that. Thanks for applying.

**Comment by ghost** [comment]
Yes, haven't had the problem for many months, thank you very much.

**Comment by veloraven** [comment]
@xAvarice thank you for your answer.
As there was not any answer from the reporter for more than two weeks and the issue seems to be fixed i'm closing this issue.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by ghost** [comment]
Sorry, I am the reporter. I have a business and personal git account.
