### ISSUE TITLE
Problem programatically updating tier pricing for configurable products using SOAP API

### ISSUE THREAD

**Issue by maurizio-pbh** [magento/magento2#6884]
### Issue

I am trying to create a script which will update product tier prices for all Magento product types using the Magento SOAP API. Using the add method on the catalogProductTierPriceManagementV1 endpoint I am able to update tiered pricing for simple products, so for example I can set different prices for 20-40, 40-60 products etc. However, when I update simple products associated with a configurable product, the simple products lose their relationship with the configurable product which of course breaks the product on the site. It could be that I am going about this in the wrong way or that there is a bug. I've not been able to find much in the way of examples. 
### Development environment

My development environment is set up as detailed here:
https://github.com/paliarush/magento2-vagrant-for-developers#what-you-get
### Steps to reproduce

In my script, to update the main price for each simple product I am calling:

`$soapClient->catalogProductRepositoryV1Save(['product' => ['sku' => 'EPFG', 'price' => 7.00]]);`

To update the simple product tiered pricing, I am using this script:

```
$row = 1;
$handle = fopen('tier-prices-configurable.csv', 'r');
while (($data = fgetcsv($handle, ',')) !== false) {
    if ($row != 1) {
        $requestData = '';
        $sku = $data[0];
        $customerGroupId = $data[1];
        $qty = $data[2];
        $price = $data[3];

        $requestData = [
            'sku' => $sku,
            'customerGroupId' => $customerGroupId,
            'qty' => $qty,
            'price' => $price,
        ];

        try {
            // Update tiered prices
            if (!empty($sku)) {
                $soapClient->catalogProductTierPriceManagementV1Add($requestData);
            }

        } catch (Exception $e) {
            $errors .= 'Error for SKU ' . $sku . ': ' . $e->getMessage() . "\n";
        }
    }

    $row++;
}
```
### Expected result

1. The main price and tiered pricing for each of the simple products to be updated.
2. When the simple products associated with a configurable product are updated they maintain their relation as child products to the configurable product.
### Actual result
1. The simple products are updated, but those associated with a configurable product are no longer associated with that configurable product as child products.

**Comment by veloraven** [comment]
@maurizio-pbh thank you for your feedback.
Please identify which version of Magento you are running.

**Comment by nobuttsalex** [comment]
@veloraven maurizio is out of the office, he is running 2.1.1

**Comment by tmotyl** [comment]
other related issues: #8371 #7599 #7909 #9789

**Comment by Mobecls** [comment]
#mageconf

**Comment by electricalsupplies** [comment]
I was updating Tier Pricing via a CSV import using these columns:

sku | tier_price_website | tier_price_customer_group | tier_price_qty | tier_price

Upgraded Magento 2 to the latest version then it stopped working with the error described above, after a bit of testing I added the column "tier_price_value_type" with a value of Fixed and the import started working again.

Checked rows: 556, checked entities: 0, invalid rows: 0, total errors: 0

Hopefully this will help someone else

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by TomashKhamlai** [comment]
I was not able to reproduce on the latest 2.3-develop. So it looks like it is fixed now
