### ISSUE TITLE
Product attribute input renderer not working?

### ISSUE THREAD

**Issue by hectornguyen** [magento/magento2#6895]
### Preconditions

1. Ubuntu 14.04.5 LTS
2. Magento 2.1.1
3. PHP 7.0.10 (or PHP 5.6.25)
4. Percona 5.7 (`5.7.14-7-log Percona Server (GPL), Release '7', Revision '083e298'`)

Magento 2 is running on `default` mode.
### Steps to reproduce

- Remove or change the value of `frontend_input_render` column to something doesn't exist from `catalog_eav_attribute` table. My SQL statement (example)

``` sql
UPDATE `catalog_eav_attribute` SET `frontend_input_renderer` = 'Magento\Hello\World\Something\Does\Not\Exists' WHERE `attribute_id` = 105;
```
- Run `bin/magento cache:flush` and cleanup `var/generation`, `var/view_preprocessed`, `pub/static/*` directories
- Go to Products > Catalog > Edit any product
### Expected result

Error should appears because of that input renderer does not exist or if it is NULL?
### Actual result

Magento still working without any trouble, in my example I changed the class name of `category_ids`, but the category tree in product edit form still being rendered

I tried to add `input_renderer` to my custom product attribute, but it is not working.
Below is what I tried,

> Setup\MySetup.php

```
public function getDefaultEntities()
{
    return [
        'catalog_product' => [
            'entity_model' => 'Magento\Catalog\Model\ResourceModel\Product',
            'attribute_model' => 'Magento\Catalog\Model\ResourceModel\Eav\Attribute',
            'table' => 'catalog_product_entity',
            'additional_attribute_table' => 'catalog_eav_attribute',
            'entity_attribute_collection' => 'Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection',
            'attributes' => [
                'custom_ids' => [
                    'type' => 'static',
                    'input' => 'select',
                    'label' => 'Custom Attribute',
                    'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
                    'backend' => 'Vendor\Module\Model\Product\Attribute\Backend\CustomAttr',
                    'source' => 'Vendor\Module\Model\Product\Attribute\Source\CustomAttr',
                    'input_renderer' => 'Vendor\Module\Block\Adminhtml\Product\Helper\Form\CustomAttr',
                    'required' => false,
                    'sort_order' => 9,
                    'visible' => true,
                    'group' => 'General',
                    'is_used_in_grid' => false,
                    'is_visible_in_grid' => false,
                    'is_filterable_in_grid' => false,
                ],
    ];
}
```

> Block\Adminhtml\Product\Helper\Form\CustomAttr.php

```
class CustomAttr extends \Magento\Framework\Data\Form\Element\Select
{
    public function getAfterElementHtml()
    {
        if (!$this->isAllowed()) {
            return '';
        }

        $htmlId = $this->getHtmlId();
        $suggestPlaceholder = __('start typing to search custom attribute');
        $selectorOptions = $this->jsonEncoder->encode($this->getSelectorOptions());
        $backendUrl = $this->backendData->getUrl('vendor_module/customattr_index/index/suggestCustomAttr');

        $return
            = <<<HTML
   /** Some HTML and JavaScript here **/
HTML;

        return $return;
    }
}
```

Could anyone here please help me know what is the right way to customise product attribute input renderer? And the top most question is why when I change value of `frontend_input_renderer`, Magento 2 still able to working without any error?

**Comment by hectornguyen** [comment]
Any updates on this @veloraven ?

**Comment by klakekent** [comment]
same issue met. any update on this @veloraven

**Comment by vbuck** [comment]
Same issue here, please investigate.

~~Something to try as an alternative could be observing the event dispatched in `Magento\Catalog\Block\Adminhtml\Product\Edit\Tab::_getAdditionalElementTypes`:~~

    /**
     * Retrieve additional element types
     *
     * @return array
     */
    protected function _getAdditionalElementTypes()
    {
        $result = [
            'price' => 'Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Price',
            'weight' => 'Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Weight',
            'gallery' => 'Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery',
            'image' => 'Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Image',
            'boolean' => 'Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Boolean',
            'textarea' => 'Magento\Catalog\Block\Adminhtml\Helper\Form\Wysiwyg',
        ];

        $response = new \Magento\Framework\DataObject();
        $response->setTypes([]);
        $this->_eventManager->dispatch('adminhtml_catalog_product_edit_element_types', ['response' => $response]);

        foreach ($response->getTypes() as $typeName => $typeClass) {
            $result[$typeName] = $typeClass;
        }

        return $result;
    }

~~I haven't yet test this, but as I read this method, it would require you to register a new `type` property on the attribute definition. As long as your context is confined to admin forms, you should get away with it.~~

**Tested above, doesn't work; see my followup reply**

**Comment by igotgroove** [comment]
Following up on this one. After some research, I believe it comes down to admin UI components having moved away from input renderers. Seems that I was seeking this out based on M1 knowledge, but M2 has moved on for its UI components.

Reference:
> http://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.html

Still, I think this is a legitimate issue to address, either by way of better documentation or else some consideration for backwards compatibility.

**Comment by vbuck** [comment]
Following up on this one. After some research, I believe it comes down to admin UI components having moved away from input renderers. Seems that I was seeking this out based on M1 knowledge, but M2 has moved on for its UI components.

Reference:
> http://devdocs.magento.com/guides/v2.1/ui_comp_guide/concepts/ui_comp_modifier_concept.html

Still, I think this is a legitimate issue to address, either by way of better documentation or else some consideration for backwards compatibility.

**Comment by hectornguyen** [comment]
@vbuck I found my answer here for a long time ago: https://magento.stackexchange.com/questions/139480/customise-a-custom-product-attribute-input-renderer-in-magento-2-the-right-way/

Thanks for your help anyway.

**Comment by AlexWorking** [comment]
Hello @hectornguyen. Based on Your issue an internal ticket was created - MAGETWO-71001. You'll be informed as the issue is fixed. Thanks for applying.

**Comment by magento-engcom-team** [comment]
@hectornguyen, thank you for your report.
We've created internal ticket(s) MAGETWO-71001 to track progress on the issue.

**Comment by ghost** [comment]
Why is it not fixed yet?

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ghost** [comment]
@hectornguyen, thank you for reporting this issue.

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.
