### ISSUE TITLE
Media image attribute in product listing

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#690]
Is there any reason why I cannot set a product attribute with type 'Media Image' to be used in product listing?  
When I create an attribute from Stores->Attribute->Products and select the `Catalog Input Type for Store Owner` to be `Media Image` the `Frontend Properties` tab disappears completely.  
If I create the attribute like that and then change the value for the field `used_in_product_listing` in the `catalog_eav_attribute` table for the attribute I just created to 1 it works just fine. I have my attribute loaded in the product listing page.  
Sometimes I may need an additional image attribute in the product listing. I cannot do that from the UI and I see no reason for it. A real use case: I want to have a rollover image. When hovering the product image I want to see a different image (with the backside of my product for example).

This problem exists in Magento 1 also. I hope it will be tackled at least in M2.

And while on this...please change the label of the attribute type field. `Catalog Input Type for Store Owner` sounds scary. `Attribute type` sounds more friendly.

**Comment by vpelipenko** [comment]
Internal ticket: MAGETWO-30483

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Media-image-attribute-in-product-listing/idi-p/47131).

**Comment by Yonn-Trimoreau** [comment]
Still an issue....

**Comment by aeu** [comment]
Hi.  Came across this one will searching for a solution.  Apparently not being able to add a new image attribute to a product is a feature.

https://github.com/magento/magento2/issues/7601

**Comment by fritzmg** [comment]
This is still an issue in Magento 2.3.2. As a workaround you can set the `used_in_product_listing` option directly in the database for the new attribute.

**Comment by VladimirZaets** [comment]
Hi @tzyganu. Thank you for your report. 
The issue has been fixed in magento/magento2#25566 by @engcom-Golf in 2.3-develop branch
Related commit(s):
 - [f070206da28f41814f6677ecee9ef4d84105338d](https://github.com/magento/magento2/commit/f070206da28f41814f6677ecee9ef4d84105338d)
 - [c23393d20e9e3e6493f6326a2cc80c4e36cdf86d](https://github.com/magento/magento2/commit/c23393d20e9e3e6493f6326a2cc80c4e36cdf86d)
 - [aa7195afb7fcab4a4984d9eb703643cc9d5a6be2](https://github.com/magento/magento2/commit/aa7195afb7fcab4a4984d9eb703643cc9d5a6be2)
 - [e29914e4581d5f14c6a4dcd5fdf4f4799c8df64c](https://github.com/magento/magento2/commit/e29914e4581d5f14c6a4dcd5fdf4f4799c8df64c)
 - [a565ee001e76ed3b5d53b7b21ed8dd637c1fb71b](https://github.com/magento/magento2/commit/a565ee001e76ed3b5d53b7b21ed8dd637c1fb71b)
 - [b30b855668313aa55c00156927e9392723795195](https://github.com/magento/magento2/commit/b30b855668313aa55c00156927e9392723795195)
 - [a7ffbd6842a0e4e243a014b8ceb8d197fca83f2e](https://github.com/magento/magento2/commit/a7ffbd6842a0e4e243a014b8ceb8d197fca83f2e)
 - [e5d143d8d968bf5a71429677015be4ae36196a74](https://github.com/magento/magento2/commit/e5d143d8d968bf5a71429677015be4ae36196a74)

The fix will be available with the upcoming 2.3.5 release.
