### ISSUE TITLE
Connecting Component Manager Magento 2.1.1 EE with Marketplace Account brings error

### ISSUE THREAD

**Issue by Daou** [magento/magento2#6908]
While trying to sign in to sync my Magento Marketplace purchases in the component Manager I get a RuntimeException.
### Preconditions
1. Magento 2.1.1 EE
2. Fresh Install, no other configuration were made
### Actual result
1. An error appears interrupting the login process "Couldn't get available versions for package magento/framework-foreign-key"
2. Please see the screenshot attached
   <img width="800" alt="screen shot 2016-10-06 at 19 02 31" src="https://cloud.githubusercontent.com/assets/1880056/19162319/a97f107e-8bf7-11e6-938f-5d0f43f31e36.png">

**Comment by veloraven** [comment]
@Daou thank you for your feedback.
Given this issue is reported against Enterprise edition, please report via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level
