### ISSUE TITLE
Downloadable product and a tracking number for shipping

### ISSUE THREAD

**Issue by tanghia** [magento/magento2#6937]
A customer purchased our downloadable product. After 12h an email send to customer about tracking number for shipping.
I don't think the downloadble product need a tracking number.
![image](https://cloud.githubusercontent.com/assets/7329746/19222589/4c7552b2-8e86-11e6-8ae7-569da7a42400.png)
![image](https://cloud.githubusercontent.com/assets/7329746/19222597/83c7f562-8e86-11e6-9f95-c4a3c6b3e0aa.png)
Magento v2.1.0
Steps to reproduce:
1. Customer purchase downloadable products
2. Customer complete payment process.

Expected result:
1. An email to notify customer and include link to download products.

Actual result:
1. An email for order confirmation sent, this email contains the information about shipping and tracking number for downloadable products.

In my opinion, we should use a particular email template for product which is digital content.

**Comment by veloraven** [comment]
@tanghia thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by tanghia** [comment]
I updated this issue. 
Magento 2 has many features which are compatible with a "digital download" store. I think that we need to improve to become the best. Following below are some suggest features:
- Change sales/order confirmation email template for downloadable products.
- Download counter
- Email notification when update new version for a particular product

Thanks

**Comment by dthampy** [comment]
internal ticket -MAGETWO-60779 created

**Comment by jurpro** [comment]
Hello. May I comment here? I have the same problem, not the same but I think it is on the same situation.

When customers buy a downloadable product or Virtual Product, on the checkout, customer cannot complete the checkout step because there is an error message says "No Payment Method available".
But when this product change to simple product, the checkout is success with shipping cost 0. 

I think the downloadable product and virtual product is not the product need the shipping cost even it 0, it should be "by pass" for shipping cost and directly pay a payment method.

Sorry I comment here, because I completely frustated no answer anywhere even in the forum Magento Community.

Thank you so much for allowing me writing here.

**Comment by magento-engcom-team** [comment]
@tanghia, thank you for your report.
We've created internal ticket(s) MAGETWO-60779 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
@tanghia, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.
