### ISSUE TITLE
Greek vat numbers cannot be validated

### ISSUE THREAD

**Issue by schnappenberger** [magento/magento2#6960]
Validation of vat numbers use country code to build a vat number for vat validation. But greek vat numbers start with EL instead of GR.
### Preconditions
1. Magento 2.1.1
2. PHP7
3. Mysql 5
4. Apache 2
### Steps to reproduce
1. login in frontend
2. enter a valif greek vat id
3. let magento validate the vat number
### Expected result
1. correct vat numbers should be validated
### Actual result
1. vat number validation fails

**Comment by sevos1984** [comment]
Internal ticket created MAGETWO-59636. Thanks for posting

**Comment by cmuench** [comment]
Any updates here? We have the same problem with a valid the german VAT.
If i remove the "DE" prefix it passes the validation. After the validation the "DE" prefix is automatically prepended. If i save my billing address again in the customer area the validation fails again.

**Comment by magento-engcom-team** [comment]
@schnappenberger, thank you for your report.
We've created internal ticket(s) MAGETWO-59636 to track progress on the issue.

**Comment by magento-engcom-team** [comment]
Hi @schnappenberger

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@schnappenberger thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Comment by hostep** [comment]
Re-opening, because a customer of ours runs against this problem with the incorrect Greek prefix.
I'm currently preparing a PR to fix this.

@cmuench: I think the issue you are experiencing is not the same, but might have been fixed by: https://github.com/magento/magento2/pull/17385

**Comment by magento-engcom-team** [comment]
Hi @schnappenberger. Thank you for your report. 
The issue has been fixed in magento/magento2#20548 by @hostep in 2.3-develop branch
Related commit(s):
 - [3ed5efb6d43067132dd10dd01579461513e3e7ef](https://github.com/magento/magento2/commit/3ed5efb6d43067132dd10dd01579461513e3e7ef)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment]
Hi @schnappenberger. Thank you for your report. 
The issue has been fixed in magento/magento2#21169 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [bfa4e1ff8f4173e75cb0c45fc7cbb0f644f6c96f](https://github.com/magento/magento2/commit/bfa4e1ff8f4173e75cb0c45fc7cbb0f644f6c96f)

The fix will be available with the upcoming 2.2.9 release.
