### ISSUE TITLE
Unable to refresh cache during developement until deploy static content

### ISSUE THREAD

**Issue by sunilgith** [magento/magento2#6966]
### Preconditions

1. Version : Community 2.1.0, Cache disabled, developer mode on
### Steps to reproduce

1. We are developing a theme using luma theme, so we have overrided the luma css and place them at app/design/frontend/Magento/<Theme Name>/web/css/source/
2. Now when we change anything on the for ex : _theme.less and run deploy static content comment it works fine, but we cannot run the command 100 times a day.
### Expected result

1. I think either we are missing any setting or this is a bug so until we complete the development we can easily view the css changes without deploying static content.
### Actual result

1. currently the css is refreshed only when we deploy the staTic content after deleting it.

**Comment by eug123** [comment]
Hi @sunilgith,

Yes you need to clean contents of the `pub/static` and `var/view_preprocessed` folders in order to recompile css from .less sources (in the admin - System/Cache Management "Flush Static Files Cache" button). You are running magento in developer mode so you don't need to run static content deploy command - static resources are published automatically, in case they are not published yet.

Please try [client-side LESS compilation mode](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css-preprocess.html#client-side) or setup [Grunt task runner](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css_debug.html) to speed up development of your theme.

Please let us know if it helped.

Thank you!

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
