### ISSUE TITLE
Bundle product order - create invoice via REST API

### ISSUE THREAD

**Issue by ankursachdeva11** [magento/magento2#6988]
We are trying to create invoice for bundle product used in order by using 
/V1/order/:orderId/invoice : POST method API.
### Preconditions
1. Magento Development ver. 2.2.0-dev 
2. Magento Released ver. 2.1.2 CE
### Steps to reproduce
1. Create an Order using Bundle item
2. try to create invoice using /V1/order/:orderId/invoice : POST method API with bundle product order item id.
3. try to create invoice using /V1/order/:orderId/invoice : POST method API with child simple product order item id.
### Expected result
1. It should be able to create invoice either using parent order item id or child product order item id.
### Actual result
1. In Magento Development latest ver. 2.2.0-dev instance : Invoice created properly if we use child product order item id. If we use parent product order item id then empty invoice will be created.
2. In Magento Released ver. 2.1.2 CE instance : Invoice created properly if we use parent product order item id. If we use child product order item id then empty invoice will be created.

Both development and released version magento2 are working opposite for creation of invoice.

**Comment by SerhiyShkolyarenko** [comment]
@ankursachdeva11 thank you for reporting the issue. Our internal one is MAGETWO-60692(for develop branch).

**Comment by olysenko** [comment]
Basically Magento has two different types of bundle products: dynamic and fixed. That's why I need to add clarification for Expected Result:
I) Bundle dynamic product:
1) request: 
{ "items": [ {"order_item_id": (parent bundle order_item_id), "qty": 1} ]  }
response:
 {"message":"InvoiceDocument Validation Error(s):\nYou can't create an invoice without products."}
2) request: 
{ "items": [ {"order_item_id": (child bundle order_item_id), "qty": 1} ]  }
response:
 partial id of created invoice

II) Bundle fixed product:
1) request: 
{ "items": [ {"order_item_id": (child bundle order_item_id), "qty": 1} ]  }
response:
 {"message":"InvoiceDocument Validation Error(s):\nYou can't create an invoice without products."}
2) request: 
{ "items": [ {"order_item_id": (parent bundle order_item_id), "qty": 1} ]  }
response:
 id of created invoice

**Comment by veloraven** [comment]
This issue was fixed in develop branch.
Closed.

**Comment by korostii** [comment]
Hi @veloraven,
Are there any plans to backport this fix?
