### ISSUE TITLE
Dashboard "Last 5 Orders" Customer show guest instead of name of guest customer

### ISSUE THREAD

**Issue by salelsol** [magento/magento2#6995]
Under "Last 5 Orders" Customer column there is many order by guest it doesn´t show the name of guest customer. 
![last_orders_dashboard](https://cloud.githubusercontent.com/assets/16081377/19353634/48a550ca-9164-11e6-9f7c-cfe12c85d52f.jpg)

**Comment by veloraven** [comment]
@salelsol thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Comment by blizzardengle** [comment]
**This is still an issue please re-open:** The dashboard on Magento 2.0+ chooses to display **Guest** in place of the customers actual name on the **Last Orders** grid when the customer checkouts without being logged-in. 

### Preconditions
1. Using Magento 2.0+ (I am using 2.1.2)

### Steps to reproduce
1. Using Magento 2.0+ (I am using 2.1.2) login to a store that has had customers check out as guests.
2. Look at the **Last Orders** grid on the left and it will say **Guest** and not the customers actual name; the original poster (OP) attached an image into their post.
3. This seems to be the offending file but I could be wrong: vendor/magento/module-backend/view/adminhtml/templates/dashboard/grid.phtml

### Expected result
The **Last Orders** grid should show who actually placed the order (Billing Name) instead of guest regardless of the fact that they were logged in or not.

### Actual result
Look at the OP's screenshot. Look at the **Last Orders** grid on the left and it will say **Guest** and not the customers actual name

**Comment by jimul** [comment]
I faced same issue in magento EE 2.1.5. When debug issue in detail, found that sales_order table field customer_firstname is null. Might be issue in converting quote to order.
