### ISSUE TITLE
M2.1.2 : Cron throws error that Schedule cannot be converted to int

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#7005]
I have a custom cron which tries to run a method on a Helper class every 5 minutes, but it doesn't run. When I look in the database I see there is an error with the following message:

> Notice: Object of class Magento\Cron\Model\Schedule could not be converted to int in /var/www/public/vendor/magento/zendframework1/library/Zend/Db/Select.php on line 640
### Preconditions
- Magento 2.1.2

`crontab.xml`:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
    <group id="default">
        <!--
            Process the queue every minute:
        -->
        <job name="run_the_queue" instance="Vendor\Module\Helper\Queue" method="processQueue">
            <schedule>*/5 * * * *</schedule>
        </job>
    </group>
</config>
```

The class in question exists and the method `processQueue` exists and looks something like this:

```
/**
 * @param int $amount
 */
public function processQueue($amount = 25)
{
    // ...
}
```
### Expected result

That the cron runs every 5 minutes and doesn't throw an error.
### Actual result

The cron runs every 15 minutes (I believe this is another bug that has been filed earlier), and it throws an error like described above.

I cannot find anything in the log files regarding the cron.

**Comment by DaimPiek** [comment]
The job is only executed every 15 minutes because the "default" crontab group is used. Use "index" or define another cron_group. 

Documentation: http://devdocs.magento.com/guides/v2.1/config-guide/cron/custom-cron-ref.html

## Solution: 
Do not have any arguments in the function that is mentioned in crontab.xml

As you can see in the following file: vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:247. 

```
try {
    call_user_func_array($callback, [$schedule]);
} catch (\Exception $e) {
    $schedule->setStatus(Schedule::STATUS_ERROR);
    throw $e;
}
```

The function is called with the Schedule object as the first argument and will override your function's default argument value.

Why is the Schedule object passed to the job's function ?

**Comment by kanduvisla** [comment]
Thanks for your reply to this older ticket. Meanwhile I already learned so much more about Magento 2 and I now see that it's not a bug.
