### ISSUE TITLE
Unable to update Magento from version 2.1.1 to 2.1.2 due to "We cannot retrieve information on magento/product-community-edition."

### ISSUE THREAD

**Issue by frostshoxx** [magento/magento2#7024]
### Preconditions

1. Magento version 2.1.1 
2. PHP 7.0.11
3. MySQL 5.6
### Steps to reproduce

1. Login as an admin
2. Go to Web install
3. Go to Update
### Expected result

1. I expect to see the page that will do the check before update
### Actual result

1. On the first page of system upgrade, it just showed me this text in red "We cannot retrieve information on magento/product-community-edition."

**Comment by shanevbg** [comment]
Don't know if you can use the command line, but these are the steps I take for a upgrade (other guides seem to miss some points). Maybe if you can do try this, you might get a more coherent error message.
Good Luck!

[First command is because Magento overwrites my .htaccess and I have to make sure the settings are correct after]

### DO A BACKUP!!!

`cp .htaccess htaccess.sav`
`sudo -H -u www-data bin/magento maintenance:enable`
`sudo -H -u www-data composer require magento/product-community-edition 2.1.2 --no-update`
`sudo -H -u www-data composer update`
`chmod +x /bin/magento`
`rm -rf var/cache/* var/page_cache/* var/generation/*`
`sudo -H -u www-data bin/magento setup:upgrade`
`sudo -H -u www-data bin/magento setup:di:compile`
`sudo -H -u www-data bin/magento setup:cron:run`
`sudo -H -u www-data bin/magento setup:cron:run`
`cp .htaccess htaccess.mag`
`cp htaccess.sav .htaccess`
`sudo -H -u www-data bin/magento maintenance:disable`

**Comment by thanasisgalanis** [comment]
I had the same issue, for me the problem was in php.ini and especially in parameter
`allow_url_fopen=Off` magento 2 require it to be ΟΝ.

You will be able to check if this solution is for you, if you try to update magento via composer.

**Comment by frostshoxx** [comment]
I ended up doing something similar to @shanevbg suggestion. However, the root cause of the issue turned out to be allow_url_fopen is disabled. After enable it, the issue went away. However, the host provider I'm using is strongly against having this parameter enabled. Do we have a workaround or alternative to having to keep allow_url_fopen enabled?

**Comment by veloraven** [comment]
@frostshoxx thank you for your feedback.
I'm going to close this issue as there is no Magento issue and the GitHub issue tracker is intended for technical issues only. Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.

**Comment by frostshoxx** [comment]
Thank you, I'll try that. Appreciate the heads up.
