### ISSUE TITLE
FilterList:getFilters() called three times for one category page refresh

### ISSUE THREAD

**Issue by bartoszkubicki** [magento/magento2#7034]
### Preconditions

1. Magento 2.1.1., PHP 7.0
### Steps to reproduce

1. While building plugin (after) on ´Magento\Catalog\Model\Layer\Filterlist´ ->´getFilters() I cleares cache.
2. The I refreshed a category page.
3. Example string in that method was logged three times, so for one refresh of page method is fired three times. After that results are propably cached (no logs while refresh)
### Expected result

1. Method called once.
### Actual result

1. Called three times.

**Comment by magento-engcom-team** [comment]
@bartek9007, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
