### ISSUE TITLE
Backend Issue - $this->scopeConfig->getValue() not reflecting the admin values

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#7036]
### Preconditions

1. Magento 2.1.0 EE
2. PHP 7.0.10
3. MySQL 5.6
### Steps to reproduce

1. Create multi-stores
2. Configure different 'Allow Countries' settings for different stores (Configuration > General > Country Options)
3. Go to Admin > Customers > All Customers > Go to any customer edit page
4. In the Addresses section: You will see the different values for Country dropdown
### Expected result

1. Address Country drop-down in Admin should take values from 'Allow Countries' setting configured for the Default Store View(Admin)
### Actual result

1. But it's picking the 'Allow Countries' from other store (the one from `select * from store_website where is_default = 1;`)

**Comment by veloraven** [comment]
@MagePsycho thank you for your feedback.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level

**Comment by robert-lero9** [comment]
@veloraven This is actually an issue in Magento 2 CE 2.1.1 also so this should be analyzed and considered for a bugfix.

Indeed the behaviour is as @MagePsycho has described. The country selection for the backend customer admin address page comes from the countries configured for the store that is set as default in the "All Stores" management instead of the configuration for the Allow Countries option (Under Stores > Configuration > General > Country Options) for the "Default Config" Scope.

**Comment by robert-lero9** [comment]
Just following up on this issue, @veloraven, as it is actually a pretty bad problem as store administrators cannot correctly manage customer information in a multistore setup where the default store has country limitations.

**Comment by robert-lero9** [comment]
Come one guys!! Is this dead here??? This is a major issue for merchants managing multistore setups - at least an acknowledgement can be posted!?

**Comment by sevos1984** [comment]
This is fixed in develop https://github.com/magento/magento2/commit/863c05a9b2bf6f98934e66aebb81ebd3bf1cca05, and will be delivered in nearest patch release.
