### ISSUE TITLE
Installation -> Magento Setup Tool display blank page - setup/controls not found.

### ISSUE THREAD

**Issue by price2b** [magento/magento2#706]
1- step 1-> magento2 download from https://github.com/magento/magento2 version 0.1.0-alpha101all
step 2-> install composer globally using composer windows installer.
step 3-> run composer install in magento2/setup directory using CMD and everything is installed perfect.
then, I went to localhost/magento2/ .. the browser is redirected to a new url localhost/magento2/setup/ with title "Magento Setup Tool" but a blank page is displayed. No install steps are displayed in my browser. I tried that with firefox and chrome with same results.

its a common situation?, anyone knows if we have to erase some file after we run composer install into setup directory?

server error.log: [Sat Oct 25 16:19:07 2014] [error] [client 127.0.0.1] File does not exist: C:/Zend/Apache2/htdocs/magento2/setup/controls, referer: localhost/magento2/setup/

any help appreciated.

**Comment by mengbo123456** [comment]
**# now i know why can't linking style ,but i don't know why this?**
because install path no version1499055289 folder ,and i add it  style work 
![image](https://user-images.githubusercontent.com/29748690/27776219-46d059a2-5fdb-11e7-9598-ea4100385f21.png)


![Uploading image.png…]()







install successful but no style damin button can't click?

**Comment by mengbo123456** [comment]
**# now i know why can't linking style ,but i don't know why this?**
because install path no version1499055289 folder ,and i add it  style work 
![qq 20170703141604](https://user-images.githubusercontent.com/29748690/27780458-9e8f6dfc-5ffb-11e7-9cf7-eaeb3d60d6c7.png)
![qq 20170703141841](https://user-images.githubusercontent.com/29748690/27780461-9f0b7dd4-5ffb-11e7-9a49-e3596576bcd9.png)
![qq 20170703142510](https://user-images.githubusercontent.com/29748690/27780459-9e9a501e-5ffb-11e7-96d0-4aa4b1650e53.png)
but i don't know why it can't add  version1499055289 folder itself in  During the installation process
