### ISSUE TITLE
When tier price qty above 1000 adds a thousand separator in the Advanced Pricing panel

### ISSUE THREAD

**Issue by mortenbm** [magento/magento2#7060]
### Preconditions

1.  Magento 2.1.2
2. Set `Base Currency` to `Danish Krone`
3. Set `Default Display Currency` to `Danish Krone`
4. Set `Allowed Currencies` to `Danish Krone`
5. PHP Version 7.0.11-1~dotdeb+8.1
6. MySQL Version: mysqlnd 5.0.12-dev - 20150407
7. intl php extension version:
   - version  1.1.0
   - ICU version  52.1
   - ICU Data version 52.1
### Steps to reproduce

1. Create product with a tier pricing of at least `1000`
2. Save product
3. Reopen product and save again.
### Expected result

1. The tier qty field should be `1000`
### Actual result

1. The tier qty field is `1`

This error is already adressed and closed in [#5745](https://github.com/magento/magento2/issues/5745) but I still experience the error.
I have patched with [MAGETWO-55847](https://github.com/magento/magento2/commit/3e070060cfe99fea8d824aff65fad7d59d33a2a7) but with no change to functionality.

**Comment by olysenko** [comment]
Hi, thanks for your report. This issue was fixed in develop branch and will be delivered with version 2.1.3 soon. 
For patch try to use changes from such commits mentioned in  #[5745](https://github.com/magento/magento2/issues/5745) 
[21c8a66](https://github.com/magento/magento2/commit/21c8a66997d73783bb4f6c1ed227c873578ec1d6)
[310808f](https://github.com/magento/magento2/commit/310808f4cba92da528f646acf85be576934b1eed)
[9d33182](https://github.com/magento/magento2/commit/9d33182bbab1f70e304611575082fe241643a4d8). I verified on 2.1.2 with apllying above changes and it works. Please check fix yourself  and if it helps close issue

**Comment by mortenbm** [comment]
I was unaware that the links to commits were not all linking to the same commit and therefore only applied part of the patch! I will give it a go and close if it fixes.

Thanks!

**Comment by mortenbm** [comment]
Issue was fixed after applying all commits. Thank you for your time!
