### ISSUE TITLE
Catalog Inventory using 0 as website ID

### ISSUE THREAD

**Issue by lhsatch** [magento/magento2#7090]
### Preconditions
1. Magento version - 2.1.0
### Steps to reproduce
1. I was attempting to get the stock status of a product using \Magento\Store\Model\StoreManagerInterface getProductsStockStatuses(). This function requires you to pass productIds and the website id.
2. The returned array for all items was coming back empty.
### Expected result
1. The returned array should contain the stock status (instock 1 out of stock 0) of the product.
### Actual result
1. An empty array is being returned. I have looked in the cataloginventory_stock_status table and can see that the website id is set to 0. See image.
   ![stockstatuswebsite](https://cloud.githubusercontent.com/assets/6516012/19516083/4b96f544-95f2-11e6-8359-b61c3377243d.jpg)
   If I look into the catalog_product_website table the website id used is 1.

![catalog_product_website](https://cloud.githubusercontent.com/assets/6516012/19516129/791d934c-95f2-11e6-9aba-575493772f3e.jpg)

Should the website_id  be set to 1 for the first website in the cataloginventory_stock_status?

**Comment by odubovyk** [comment]
Thank you for the report. Internal ticket MAGETWO-60146

**Comment by maghamed** [comment]
Hi @lhsatch 

Looks like you use 
\Magento\CatalogInventory\Model\ResourceModel\Stock\Status::getProductsStockStatuses($productIds, $websiteId, $stockId = Stock::DEFAULT_STOCK_ID)

method passing $websiteId = 1 (your current website) and get an empty result, because ResurceModel Stock Status uses it as a filter for cataloginventory_stock_status table.

Correct way to achieve desirable behavior is to use API interface 
\Magento\CatalogInventory\Api\StockStatusRepositoryInterface::getList(StockStatusCriteriaInterface $searchCriteria);
and pass needed product ids as search criteria filter there.

For now Magento supports single stock without linkage to websites

**Comment by miakusha** [comment]
It's duplicate #5222.  Issue was fixed in [2.1.3](https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogInventory/Setup/UpgradeData.php#L90-L98)
