### ISSUE TITLE
Hebrew words in PDF invoice are reversed

### ISSUE THREAD

**Issue by hezide** [magento/magento2#7095]
### Preconditions

1. Magento 2 CE 2.1.2
### Steps to reproduce

1. Enter Sales>>invoice.
2. Enter to an invoice.
3. Press "Print".
### Expected result

1. Hebrew words should appear correctly.
### Actual result

1. Hebrew word are reversed, for Example instead of: "חזי" its "יזח".

screenshot:
![default](https://cloud.githubusercontent.com/assets/22726977/19527269/0c8920aa-9630-11e6-86af-73ce0e172829.PNG)

**Comment by veloraven** [comment]
@hezide thank you for your report.
We've created internal ticket MAGETWO-59977

**Comment by hezide** [comment]
any idea about this? it's very important...

**Comment by hezide** [comment]
in addition, my currency symbol is not showing (NIS ₪) and it looks like this:
![default](https://cloud.githubusercontent.com/assets/22726977/21292517/d7ad8898-c510-11e6-834e-0dcb64cd24a4.PNG)

I have seen this issue in several places:
http://stackoverflow.com/questions/25911650/rupee-symbol-not-rendering-properly-on-invoice-pdf-in-magento

http://magento.stackexchange.com/questions/87934/how-can-i-display-%E2%82%B9-properly-in-invoice-pdf-without-changing-core-files

but these solutions doesn't work on magento 2.
The closest thing I have found to change the font in the PDF is this:
http://magento.stackexchange.com/questions/117659/adding-new-fonts-to-pdf-invoice-magento-2/117668
but I couldn't understand completely what I should place in the AddFontToPdf.php file...

I'll be glad for some help here..

Thanks.

**Comment by mrkhoa99** [comment]
@hezide You should open new question on http://magento.stackexchange.com/. I have already one solution for this.

**Comment by hezide** [comment]
Hi, the solutions can fix the symbol issue but not the reverted words..
It's really important to me...
Thanks

**Comment by hezide** [comment]
Anyone?

**Comment by codekipple** [comment]
I've fixed this issue for my site but it involved overriding the Invoice, Shipment and Creditmemo PDF classes.
I've tracked down the problem with the reversed Hebrew to be an issue with Zend Pdf. My fix currently is to try and detect Hebrew words and to preemptively reverse the words so that when Zend Pdf does reverse them it is actually correcting them. It's pretty hacky.

**Comment by hezide** [comment]
Whatever solution you have is blessed, could you share it please?

**Comment by codekipple** [comment]
@hezide ok, I'll update this question https://magento.stackexchange.com/questions/150820/hebrew-words-in-pdf-invoice-are-reversed-and-currency-symbol-not-showing with my solution. Check back in a couple hours as I'm going to lunch first.

**Comment by magento-engcom-team** [comment]
@hezide, thank you for your report.
We've created internal ticket(s) MAGETWO-59977 to track progress on the issue.

**Comment by gaganrana-pl** [comment]
@codekipple  The solution worked, but now the pdf size is too large. One invoice pdf is around 5 MB, so I am getting pdf file corrupted. Not sure if this issue is related to this but it has happened since I have applied this plugin. Please help if anyone facing the same issue(It is that the pdf id getting corrupted when trying to open. This is not happening on every system, so I am not sure if it will be related)

**Comment by codekipple** [comment]
@leosingh44 5MB is probably due to the added size of the custom fonts. I never checked the size of my PDF's.

My hebrew reversing solution was very hacky and only covers a few of the sections. Interestingly I did have an issue with corrupted invoices. I can't remember if it happened on the Hebrew site I was working on only. I'm managing 10 different sites all in different countries. I remember getting the invoice file corrupted error on one of the sites and again finding a hacky solution which I applied to all 10 sites.

My hacky solution was to put the admin into developer mode and it seemed to then download the invoices correctly. The only reason I could get away with this is because my sites have a server dedicated to running just the admin separate from the frontend. The frontend is served via multiple separate instances behind a load balancer.

I assumed the corrupted invoice was a Magento bug and I was hoping it would be fixed in a future update. I will have to look into this and get back to you. Maybe my code to fix the hebrew PDF is calling something which fails when the magento site is in 'production' mode.

**Comment by gaganrana-pl** [comment]
Thanks for the reply.  I had tried to repair the pdf and when it was repaired, I was getting this error as an exception. 

**The font LinLibertineB contains a bad/BBox** 

However, the pdf was getting displayed. But not sure why this issue is not coming for other windows/mac systems. One more thing is it was working previously, so not sure if its anything related to magento, or server or my system.

**Comment by magento-engcom-team** [comment]
@hezide, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
