### ISSUE TITLE
Magento 2.2.0-dev selected backend language not applied

### ISSUE THREAD

**Issue by hocomadvies** [magento/magento2#7157]
when selecting a different language for he backend user it is not applied. Although I can see in the database that the selected language is saved for the user. 
### Steps to reproduce
1.  Go into user config and select interface local
2. Save it and empty the cache files
3. refresh the backend
### Expected result
1.  the new language should appear in this case nl_NL
### Actual result
1. Nothing is changed still the default language? 

There is only  /app/code/Magento/backend/i18n/en_US.csv should there also be a nl_NL.csv ?

**Comment by hocomadvies** [comment]
Could this be caused using an existing database? So there might still be something in the database referring to the (old)default language. So it does not matter whatever is selected on the user config-page?

**Comment by veloraven** [comment]
@hocomadvies you need to have installed translation for desired language in order to use it. Magento itself contains en_US language only.
You can find information in the [User Guide](http://docs.magento.com/m2/ce/user_guide/stores/store-language-add.html?Highlight=localization) .
I'm closing this issue as it is not a Magento issue.
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want to report some other technical issue  please create a new GitHub issue report.
