### ISSUE TITLE
Numeric-ish values not properly evaluated on varchar attributes

### ISSUE THREAD

**Issue by Morgon** [magento/magento2#7170]
I had a varchar attribute that I needed to change from `7` to `07`. No matter how many times I tried, I could not get it to save `07`. Wholly different values worked, and I was then able to save it back to `07` afterwards. It wasn't until I tried saving `07` back to `7`, and failing, that I realized what is probably happening.

With PHP being a loosely-typed language, my guess is that the ORM/Model is not explicitly comparing varchar attributes: `7` == `07`, but !== `07`.
### Preconditions

1. Magento 2.1.2 (also occurs on 2.1.0, possibly other versions)
2. PHP 7.0.12, Percona MySQL 5.6.32-78
### Steps to reproduce

1. Create an attribute with the varchar datatype
2. Save a number into this field, e.g. `100` or `00100`
3. Try to save the same number with a differing amount of leading zeroes (or remove them if present).
### Expected result

1. Values should change to reflect exactly what I entered
### Actual result

1. The previous value is retained, likely due to PHP loosely comparing this text as equal.

**Comment by veloraven** [comment]
@Morgon thank you for your your report.
Please report EE issues via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. 
Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
Custom customer's attributes is Enterprise functionality.

**Comment by Morgon** [comment]
This is not limited to Customer Attributes, that was just where I noticed it first.
I have also verified this issue exists with Product Attributes, even on a fresh install of CE 2.1.2 - setting one of the demo products' name to "0001" and then to "1" results in the original value being kept.

Updated the original report to remove the specific distinction.

**Comment by veloraven** [comment]
@Morgon thank you for update and for additional information.

**Comment by endergreen** [comment]
Seeing this issue as well with version 2.1.4 and PHP version 7.0.16

**Comment by endergreen** [comment]
It looks like you can get around it by adding in an alphabetical character as well to change the value with the zeros and then remove the alphabetical character on next save.  In other words change 0001 to 1X first then change 1X to just 1 to get the desired result.  However, depending on how many potential products would be affected by something like this, it could be very time consuming to correct.

**Comment by sedax90** [comment]
Same problem in 2.1.7, no patch yet?

**Comment by cproach** [comment]
Was there ever a fix for this?

**Comment by magento-engcom-team** [comment]
@Morgon, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by creative-git** [comment]
same issue here ..

**Comment by viralvasara** [comment]
I am facing the same issue in 2.1.7

- created attribute with type = 'textfield', attribute name p_code
- assigned it to Default Attribute Set

- I have prepared a csv with sku and p_code
for e.g. sku = A111 and p_code = 123456

- imported csv and product data is saved. p_code = 123456 is saved for sku = A111

- now I want to update p_code = 00123456 but it is not being saved.

- It only returns with value p_code = 123456

Can anyone please check/advise on this?

---------------------------------------------------------------------------
Though I got the tweak to make it happend.
- I made field p_code blank and saved the product. (or you can add whatever value other than previous value (123456) )
- Then i add value p_code = 00123456 and again saved it.
- it is working proper. 

but this is not a good way to handle this.



@magento-engcom-team - can you please look into this?

**Comment by srepn** [comment]
@magento-engcom-team same issue in 2.2.5

**Comment by srepn** [comment]
@magento-engcom-team  [source](http://bit.ly/2NJTPhB) - can we skip `is_numeric` in line 1359 ?

**Comment by srepn** [comment]
Temporary solution:
replace line 1359 in `module-eav/Model/Entity/AbstractEntity.php` 
from:
`} elseif (!is_numeric($v) && $v !== $origData[$k] || is_numeric($v) && $v != $origData[$k]) {`
to:
`} elseif ($v !== $origData[$k]) {`

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ghost** [comment]
@magento-engcom-team give me 2.3.0 instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii. Thank you for your request. I'm working on Magento 2.3.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-andrii, here is your [Magento instance](https://i-7170-2-3-0.instances.magento-community.engineering).
Admin access: [https://i-7170-2-3-0.instances.magento-community.engineering/admin](https://i-7170-2-3-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
It looks like it was fixed in the latest release. Closing for this.

**Comment by seegrand** [comment]
If you experience this issue in Magento 2.1.1 - 2.1.7 you can use this patch to fix the issue:

```
Index: vendor/magento/module-eav/Model/ResourceModel/UpdateHandler.php
GitHub issue: https://github.com/magento/magento2/issues/7170
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- /vendor/magento/module-eav/Model/ResourceModel/UpdateHandler.php
+++ /vendor/magento/module-eav/Model/ResourceModel/UpdateHandler.php
@@ -161,7 +161,7 @@
                 if (array_key_exists($attribute->getAttributeCode(), $snapshot)
                     && $snapshot[$attribute->getAttributeCode()] !== false
                     && array_key_exists($attribute->getAttributeCode(), $entityData)
-                    && $snapshot[$attribute->getAttributeCode()] != $entityData[$attribute->getAttributeCode()]
+                    && $snapshot[$attribute->getAttributeCode()] !== $entityData[$attribute->getAttributeCode()]
                     && !$attribute->isValueEmpty($entityData[$attribute->getAttributeCode()])
                 ) {
                     $this->attributePersistor->registerUpdate(

```
