### ISSUE TITLE
Price filter showing prices excluding taxes

### ISSUE THREAD

**Issue by pitangaweb** [magento/magento2#7199]
### Preconditions

1. Magento 2.1.2 installed using composer
### Steps to reproduce

1. Set catalog settings to show prices _including taxes_ on front-end
2. Enable layered navigation by setting "is anchor" to yes on every categories
### Expected result

1. Price filter on catalog pages should display price ranges _including_ taxes.
### Actual result

1. Price filter displays price ranges _excluding_ taxes. Example: A product priced at 19€ excluding taxes and displayed at 24€ including taxes does show when the "10€ to 20€" price range is selected. It should show when the "20€ to 30€" price range is selected.

**Comment by davidnguyen2205** [comment]
Same as my problem...

**Comment by choukalos** [comment]
Did you set the default or the website's shipping origin and tax default calculation to the same country?  Did you also setup a tax rule that has an appropriate rate to it?  It sounds like Magento thinks you uploaded the prices with tax (but found a 0% tax rate) and then is now dynamically adjusting the price based on the customer's tax rate (> 0% tax rate).

**Comment by davidnguyen2205** [comment]
I checked that my config is right as you said. Can you reproduce it or not? :)

**Comment by odubovyk** [comment]
@pitangaweb, thank you for report. Internal ticket MAGETWO-60411

**Comment by koenner01** [comment]
We have this problem too in 2.1.2 and I can confirm that this is still an issue after correcting the shipping origin & tax default calculation by setting them to the same country

**Comment by developerscb** [comment]
I can also confirm the same problem is happening in 2.1.3 and the things said by @choukalos are reviewed and not applying.

**Comment by tal-girit** [comment]
some problem with products with discount magento 2.1.2 and 2.1.3

**Comment by hostep** [comment]
We also saw this, but over here, the problem was caused by a free 3rd party extension which manipulates the filter functionality (Manadev).
Digging through their code, they use prices excl tax for the price filtering.
Disabling this 3rd party module seems to display the correct results over here.

**Comment by ThisIsRuddy** [comment]
Any news on this?
We went live with M2 in December and had to disable our price filters due to it using the excluding tax price, causing major confusion for our customers. 2.1.6 and this is still the case, going to spin up a 2.1.7 and see if it is fixed there but I can only hope as this ticket is still open.

Image attached demonstrating behavior

![price-filter-using-excluding-tax-value](https://cloud.githubusercontent.com/assets/1761171/26835865/275c4852-4ad1-11e7-8f26-c106de41a99c.png)

**EDIT:** Just tried 2.1.7.... same problem
![price-filter-using-excluding-tax-value](https://user-images.githubusercontent.com/1761171/26838641-98a02cb6-4ad8-11e7-8e60-efa4d8fdaf9f.png)

**Comment by RixXuan** [comment]
@ThisIsRuddy your problem came from visualizing after taxed final price, here is quick solution, you can override method **_getProductCollection** from Magento\Catalog\Block\Product\ListProduct class by using your own ListProduct class, before return productCollection object, you can apply your own filter logic to filter again whole collection.

For instance, mention that price_filter in Magento using GET, you should see some param in URI like '?price=(min_price)-(max_price)' on category page, if things goes like this way, then you gen extract max price and iterate through product collection compare each of them with max price, remove product items has (price+tax) above filter range, like:
foreach ($this->_productCollection as $key => $item) {
// YOUR FILTER LOGIC
// blah blah blah...

if(!$in_condition){
$this->_productCollection->removeItemByKey($key);
}
}

This solution works fine on my case, but still, it's a temporal solution, hope Magento team will make filter module more customizable.

Good luck!

**Comment by veloraven** [comment]
I'm closing this issue as internal ticket was closes as not a bug: layered navigation with prices including tax will multiply index size, also that will break manual Layered Navigation with fixed intervals if it's configured (i.e. 100-200, 200-300, 300-400).
However you can submit this issue to [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) as improvement if you think it will have significant value (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)). However I can not promise that it will be implemented even in this case.

**Comment by pitangaweb** [comment]
Well I can understand the implications, but I find it really weird that such an essential feature for the European market (and lots of countries) might never be implemented.

**Comment by ThisIsRuddy** [comment]
I too share this opinion 😐

**Comment by GuidoHub** [comment]
You are kidding me right? So the products are shown with tax and you are going to filter on excluding, how can you even think this is feature and not a bug. Have you ever looked at this on perspective of a customer? Oh I filter on price 20 but I never see products in that price range. What a disappointment.

**Comment by ThisIsRuddy** [comment]
@GuidoHub you tried 2.2 RC yet? I've not had a chance to

**Comment by GuidoHub** [comment]
@ThisIsRuddy No, still fighting with Magento 2.1.18, there are so many bugs and features that don't work for european market. Like when you use special price, the old price in catelog is shown without tax, how can you even think this is right. Magento is really working towards B2B instead of B2C

**Comment by pitangaweb** [comment]
Well it's crystal clear that Magento is ignoring the European market. Customers have a hard time understanding why basic features included in entry-level cart systems are not even in Magento 2's roadmap.  I mean, we have to make a feature request to have a bug fixed, because the bug is actually a feature. How crazy is that ?

**Comment by farhadfrz** [comment]
Almost one year no fix?

**Comment by ThisIsRuddy** [comment]
Ridiculous 😭😂

**Comment by orlangur** [comment]
> internal ticket was closes as not a bug: layered navigation with prices including tax will multiply index size, also that will break manual Layered Navigation with fixed intervals if it's configured (i.e. 100-200, 200-300, 300-400).

Anybody understand this? Isn't all we need is just having a BIG GLOBAL SWITCH saying whether layered navigation includes tax or not? Or the problem is that tax may vary from region to region and thus we would have to keep NxX compared to X size of original index?

**Comment by ThisIsRuddy** [comment]
Only time it can identify region is when the user is logged in with saved
address anyway so the hooks are there either way...

**Comment by korostii** [comment]
> also that will break manual Layered Navigation with fixed intervals if it's configured (i.e. 100-200, 200-300, 300-400)

Well, from the screenshots above it seems to me that it's broken already. Please note that "it seems complicated, we're worried we might break something else while fixing this bug" is not the same as "not a bug".

**Comment by sebfie** [comment]
Any update on this?

**Comment by sandip5678** [comment]
> Any news on this?
> We went live with M2 in December and had to disable our price filters due to it using the excluding tax price, causing major confusion for our customers. 2.1.6 and this is still the case, going to spin up a 2.1.7 and see if it is fixed there but I can only hope as this ticket is still open.
> 
> Image attached demonstrating behavior
> 
> ![price-filter-using-excluding-tax-value](https://cloud.githubusercontent.com/assets/1761171/26835865/275c4852-4ad1-11e7-8f26-c106de41a99c.png)
> 
> **EDIT:** Just tried 2.1.7.... same problem
> ![price-filter-using-excluding-tax-value](https://user-images.githubusercontent.com/1761171/26838641-98a02cb6-4ad8-11e7-8e60-efa4d8fdaf9f.png)

this issue still there in Magento latest version 2.2.5 and 2.2.6. 
Hope they will resolve in 2.3.0 release

**Comment by Panda-Mathieu** [comment]
Any news on this ?

**Comment by orlangur** [comment]
I would like to get some kind of an answer as well.

@veloraven could you please add some more details?

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99245` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by darshan-khatri-16** [comment]
Its fixed in 2.3.1

**Comment by orlangur** [comment]
@darshan-khatri-16 good to know, please add appropriate label then.

**Comment by ghost** [comment]
Hi @darshan-khatri-16 Unfortunately we also have this problem, but we use magento 2.3.1 .. Do you have any idea or tipp for what we should to do or try ? Maybe can you send a link where we can see the commit about this?
Thank you!

**Comment by darshan-khatri-16** [comment]
Hi @matekovacs-srg 
You just need to do a proper configuration in Magento admin. Also, set proper tax class while creating Product. I didn't find any particular commit for this issue fix.

**Comment by jcodo** [comment]
Is this actually fixed?

**Comment by pitangaweb** [comment]
I opened this issue almost 3 years ago. It's good to know that something has finally happened. I know it won't help anybody but I have to say that, after 10 years (!) on Magento, we have finally switched to another e-commerce platform that is actually opened to the possibility that there is life outside North America.

**Comment by orlangur** [comment]
@pitangaweb I bet such platform does not have even 50% of Magento abilities and has it's own pitfalls 😉

**Comment by pitangaweb** [comment]
@orlangur
Every platform has its pitfalls for sure.

"I bet such platform does not have even 50% of Magento abilities"

Well, almost 3 years to finally have a basic feature like price filtering fixed does not inspire me to explore the other 50%.

**Comment by orlangur** [comment]
@pitangaweb it could be fixed by proper third-party developers if needed pretty quickly, probably not fixed by core developers because it is not a really frequent use case.

Anyway, good luck with a new platform of your choice and thanks for a bug report, such tiny steps help to improve Magento platform for sure.

**Comment by jcodo** [comment]
Can anyone here suggest how this new functionality might be switched on or configured? Can't work it out.

**Comment by chickenland** [comment]
Seeing this issue in 2.3.1 too - would be useful to know the correct setup suggested for this if it's config.

**Comment by kevinvuillemin** [comment]
Hello did you found a solution ?

**Comment by bernd-reindl** [comment]
Still in 2.3.5-p1

**Comment by kevinvuillemin** [comment]
Up please ?

**Comment by bernd-reindl** [comment]
@magento-engcom-team this bug is still in 2.3.5-p1.

**Comment by pitangaweb** [comment]
> @pitangaweb [...] it is not a really frequent use case.
Yes, you're right, it only concerns the 750 million people of Europe. it is not a really frequent use case, right ?

**Comment by victortodoran** [comment]
See Igors answer here https://magento.stackexchange.com/questions/176341/magento-2-layered-navigation-price-without-tax

**Comment by pitangaweb** [comment]
@victortodoran And that's a terrible answer. If "the current behavior is by design", then it was poorly designed.

**Comment by zigojacko** [comment]
2.4 user here and we've just noticed this problem - I find it absolutely ridiculous that Magento don't deem this a bug. It renders the price filter completely inaccurate - abysmal...!

Anyone know of a fix we can apply to put this right?

**Comment by Rickertje** [comment]
@magento-engcom-team Reopen this issue please

**Comment by DaWheelz** [comment]
This is still happening in 2.3.6... Can we please get a fix for this soon?

**Comment by matiasgaletto** [comment]
Still happening in 2.4.7-p1, eight years later.
The solution suggested by Igor in his post 7 years ago is no longer possible because the referenced methods and files are no longer in use.
As suggested, I was able to add a new column to **catalog_product_price_index**, which is the table used to filter the collection.
This new column gets the min_price excluding taxes and adds the tax_class_id value, also present in that index table.
Then you have min_price_incl_tax.
The only remaining thing to do is to filter the collection using this new field. I thought I had found where the query was constructed and replaced the field min_price with the new one, but didn't work. So, basically, I don't know where is the place where I have to put my new field on so the collection is proeprly filtered.
Seems amazing to me that no one has fixed this for over 8 years.
And yes, this is a BUG. Please reopen. @magento-engcom-team
It is not reasonable to allow something to work wrong. There should be at least a failsafe that if the price filter is not going to work properly due to other configurations combinations, it shouldn't even render.
Showing prices out of range absolutely destroys a brand/store reputation, and if I may remind you, Magento is a system for brands and stores, not for developers. So a little respect should be shown. And if showing prices out of range is by design, that is possibly the worst design I have ever seen. @veloraven
The configuration that doesn't work is when you introduce your prices excluding taxes and show them in the frontend including taxes. Prices saved in the price_index table are without them, so you need to add an extra column for every combination. Then filter with it. Can someone tell me where to replace min_price with min_price_incl_tax? Thanks
