### ISSUE TITLE
Configurable Products dropdown not showing pricing

### ISSUE THREAD

**Issue by titus213** [magento/magento2#7200]
I have a configurable product and the configurations all have different prices.  The dropdown on my configurable product does not show pricing information (like it did in Magento 1.9).
### Preconditions

Magento ver 2.1.2 up to 2.3.1
### Steps to reproduce

1. Create a configurable product with two attributes and that the second attribute (second in the list, never the first one - it's essential for reproduction) has pricing differences.
2. Go to the Frontend and watch the second attribute dropdown.

### Expected result

1. Second attribute drop-down reflects pricing differences like on the screenshot below
![image](https://user-images.githubusercontent.com/46617848/58231370-7549b380-7d54-11e9-9c9f-926188568a88.png)

### Actual result

1. No pricing information is shown in the second drop-down.
![backend](https://cloud.githubusercontent.com/assets/22941717/19741357/f8bbf7d6-9b85-11e6-8c65-a115aa8859d1.png)
![frontend](https://cloud.githubusercontent.com/assets/22941717/19741356/f8b288fe-9b85-11e6-80dc-dd8c83deb10a.png)

 The pricing differences would be shown only in the first attribute dropdown if they were set for it.

**Comment by olysenko** [comment]
Hi, thank you for your report. Internal issue is created MAGETWO-60362

**Comment by siddharth-vaghasia** [comment]
Hello any update on this ? when will be this issue fixed ?

**Comment by magento-engcom-team** [comment]
@titus213, thank you for your report.
We've created internal ticket(s) MAGETWO-60362 to track progress on the issue.

**Comment by rachana229** [comment]
Hi any update on this?

**Comment by aashworth-ldg** [comment]
I would also be interested in any update to this?

**Comment by arnoudhgz** [comment]
@magento-engcom-team  any news on this issue?

**Comment by malikt** [comment]
Hi,
@magento-engcom-team  seems this issue never considered?

**Comment by supportnubix** [comment]
@magento-engcom-team Is this issue still on the radar? Is this fixed in upcoming updates (2.2.6+)?

**Comment by 1stKarkan** [comment]
Hello @magento-engcom-team is there any chance this will be fixed in 2.3.1?

**Comment by vikalps4** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vikalps4. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vikalps4, here is your [Magento instance](https://i-7200-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-7200-2-3-develop.instances.magento-community.engineering/admin](https://i-7200-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 1stKarkan** [comment]
I tried it on that Demo Shop but apparently the feature only works for the first dropdown:
https://i-7200-2-3-develop.instances.magento-community.engineering/test.html

After selecting the first attribute, there are no prices visible on the options of the second.

This is really disappointing and makes it even worse for products with more than one configurable attribute as it is definitly more confusing for a buyer than not showing a price difference at all.
For my customer i added a working version of this feature via a lot of ugly javascript on the product page. But it would be great if this becomes a built in Feature of Magento 2. Actually i would appreciate it even more when the real difference is shown. So that if Option A is +5$ and you select it, the +5$ gets removed and Option B gets labeled -5$.

How come M1 has this Feature and M2 doesn't?

**Comment by sdzhepa** [comment]
Hello @magento/quality-maintainers team,

May I ask you to review this Issue and Confirm is it still reproducible on the latest vanilla Magento?
Probably need to update Steps to Reproduce or Issue is not actual any more(was fixed with another pull request)

Thank you in advance!

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [Magento instance](https://i-7200-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-7200-2-3-develop.instances.magento-community.engineering/admin](https://i-7200-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment]
I have tested with same scenario as mentioned in issue description.
Also tried with some other scenarios.
But could not reproduce this issue on latest magento 2.3 instance.
Prices are displaying.
PFA
Admin:
![image](https://user-images.githubusercontent.com/46617848/58231364-7084ff80-7d54-11e9-8a5d-ab9127817aa1.png)

Front end:
![image](https://user-images.githubusercontent.com/46617848/58231370-7549b380-7d54-11e9-9c9f-926188568a88.png)

Thanks.

**Comment by 1stKarkan** [comment]
Hello,
This issue is still not resolved. Yes, the prices are shown, but only for the first dropdown. Any other attribute will not show the prices on the dropdown. I made a second product with two configurable attributes and it breaks.
![admin](https://user-images.githubusercontent.com/8205102/58233269-e29d1a80-7d3b-11e9-9175-08d86a0df1b2.png)
![front](https://user-images.githubusercontent.com/8205102/58233272-e5980b00-7d3b-11e9-88a4-7121fdb1afe9.png)

**Comment by mhenkel1** [comment]
Is there any way to remove these prices? Any option for it?
One of my customers does not want to show the pricing difference on every option.

**Comment by rani-priya** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul, here is your [Magento instance](https://i-7200-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-7200-2-3-develop.instances.magento-community.engineering/admin](https://i-7200-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
