### ISSUE TITLE
Magento 2.1 Assign Simple/Virtual Products to a configurable Product

### ISSUE THREAD

**Issue by abubner** [magento/magento2#7212]
I have a problem with my custom product importer.

As HowTo i used this article:
https://firebearstudio.com/blog/how-to-programmatically-create-a-configurable-magento-2-product.html

I have 2 super attributes: foo_color and foo_size

After adding new simple products and save them, i create a config product and assign
the new simple ids to the config. product. But this do not work!! - After save the simples are not
associated to the config product! Is this a bug? I tried sev. things but nothing work. Now i read
that this is a known issue? - If not ... where can i found a working example ( and i do not want to use the REST API ).
### Preconditions
1. Magento 2.1
### Steps to reproduce
1. Creating Simple Products ( also tried virtual )
2. Creating Config Product
3. Try to associate the simples by using this example: https://firebearstudio.com/blog/how-to-programmatically-create-a-configurable-magento-2-product.htm
### Expected result
1. After adding the associate simple ids they should appear in the conf. product
### Actual result

![s1](https://cloud.githubusercontent.com/assets/4447556/19764686/9e31d9ba-9c44-11e6-99ba-c01d58c9090d.PNG)
![s2](https://cloud.githubusercontent.com/assets/4447556/19764687/9e375fca-9c44-11e6-92e5-168417adbc12.PNG)

**Comment by abubner** [comment]
Update: I can associate the variants now to the config product by a custom code.
It seems very complex, so i hope you will develop a better way for the flow:
1. Have simples already which have his own attributset and with this you know the super attributes and knows the super values
2. Have config product already
3. you can add the associated variant ids and the super attribute codes at the config product
4. Save

Hope you understand the request. - Please let me know if i should describe more the details.
Thanks
Andre

**Comment by veloraven** [comment]
@abubner thank you for your feedback.
Please describe exact steps you do instead of link to the external resource.
Please also provide expected and actual results if you think it to be an issue.
If it is rather a question how to do it and get desired result please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
Please also note that we have separate forum for improvements and feature requests, you can use it in case when there are no issues in functionality itself but there is a lack of functionality:  [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Comment by samgranger** [comment]
I have encountered the same issue. Try cleaning your browser cache (worked here).

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
