### ISSUE TITLE
Categories column in products grid stays empty

### ISSUE THREAD

**Issue by JerVoo** [magento/magento2#7248]
### Preconditions

Magento v2.1.0

### Steps to reproduce
1. Add a product
2. Add the product to a category
3. Add the categories column in to the product grid
4. Find the added products in the grid and take a look at the categories column

### Expected result
1. The categories column should display the category or categories the product has been added to

### Actual result
1.  The column stays empty for products added to categories.
![image](https://cloud.githubusercontent.com/assets/4249421/19854218/2866431a-9f6e-11e6-867d-8792a5d5fe3c.png)

![image](https://cloud.githubusercontent.com/assets/4249421/19854233/3e8c33f2-9f6e-11e6-9292-c9f2307138cf.png)

**Comment by slopukhov** [comment]
@JerVoo thank you for your feedback,
Please, recheck it on the latest 2.1 version of Magento.
And if this bug is still there, please, describe how you add a column with the categories, since I do not have it in the list.

![result](https://cloud.githubusercontent.com/assets/8982177/20384990/5dd98d7e-acbe-11e6-89ec-e2b4ef6bf543.png)

**Comment by vzabaznov** [comment]
Hi @JerVoo , closed as we don't receive update more than 2 week, feel free to write here/reopen or to open new issue
