### ISSUE TITLE
Product regular price on category page is using Default Store regular product price instead of Current Active Store product price

### ISSUE THREAD

**Issue by lid3rs** [magento/magento2#7251]
### Preconditions
If we have multiple web stores (one website) and product is active on store A and on Store B (Store A and Store B are instances of one website; store A and Store B are NOT Store Views), but with different prices, then on category page, in Store A and in Store B, the product regular price is the same for store A and for Store B. Mismatch here is that in Admin panel in Store A regular price is different that in Store B. In Product Page, the regular price is different and is O.K.  If we make Advanced Pricing, then the Special Price differs on Category View page, and is O.K.

The prices are configured to be different per Website.

Magento ver. 2.1.2

### Steps to reproduce
1. Create 2 Stores, which are placed in one website
2. Configure to show different prices per website
3. Create two root categories for Site A, Site B
4. Place on product in Site A and Site B
5. Define different regular prices for this product for Site A and Site B
6. Go to category view and see the mismatch.

### Expected result
**In admin panel**
Product A has A regular price for Store A, website A
_Product A has **B** regular_ price for Store B, website A

**In category page**
Product A has A regular price for Store A, website A
_Product A has **B** regular_ price for Store B, website A

**In product page**
Product A has A regular price for Store A, website A
_Product A has **B** regular_ price for Store B, website A

### Actual result

**In admin panel**
Product A has A regular price for Store A, website A
_Product A has **B** regular_ price for Store B, website A

**In category page**
Product A has A regular price for Store A, website A
--> error -- > _Product A has **A** regular_ price for Store B, website A

**In product page**
Product A has A regular price for Store A, website A
_Product A has **B** regular_ price for Store B, website A

**Comment by rganin** [comment]
Thank you for reporting, the issue is actually in broken price scoping: price can have only global or website scope depending on configuration setting in Stores -> Configuration -> Catalog -> Price -> Catalog Price Scope field, and should not be scoped per store view.
Issue is already aknowledged in https://github.com/magento/magento2/issues/5133.
Internal ticket created MAGETWO-54704.

**Comment by lid3rs** [comment]
U'r welcome. I was expecting the price change not per store view, but per **Store** if we speak Website -> Store -> Store View.

_A little offtopic:_
What i'm trying to achieve, is that there are different Websites (businessess with different products), Stores (only different countries and prices), Store Views (Different Langs). So I used the Store to setup different prices. It worked as i expected in product page, but not in category page.

**Is my approach wrong? If so, what could be teh best solution for such business organisation?**

**Comment by ritschi72** [comment]
Is there any update on that issue? I am also facing that problem in Magento version 2.1.2

**Comment by yaronish** [comment]
Fixed

**Comment by brekz** [comment]
I got another interesting error related this issue:

We have 5 different stores. 
Creating product. After created product we're correcting product name for each store. After that, I'm coming back to "Store View: All Store Views" & want to change price for entire product.

Changing, seems OK, but now I'm going to each store to check if price is changed - NO.
Interesting situation that price changing in that store where we didn't correct product name.

Interesting situation, that if I didn't change product name is store, price input following "Store View: All Store Views" changes. But if I correcting something in multi store, price is didn't changing.

We have "Catalog Price Scope: Website"

**Comment by brekz** [comment]
Any answer?

**Comment by orca931** [comment]
I don't think this issue is fixed.
I am encountering exactly the same problem in Magento 2.2.3 

 I read that the prices in the category pages are coming from the price index (table catalog_product_index_price) which is not the case for the product details page.

In that table, there is a column **website_id**, but there is no column **store_id**. This means that a product which has different price in each store cannot have different **indexed** prices, it can have just one indexed price per website and therefore you will get only one price in the category page regardless which store are you browsing.

For me that is very strange and an obvious problem with the design of the index price table. I cannot understand why there is no store_id column in the price index table, and how people are dealing with this issue.

**Comment by syedsaleem086** [comment]
Same issue on Magento2.2.7
@mmansoor-magento
