### ISSUE TITLE
Insignificant stores sorting issue 

### ISSUE THREAD

**Issue by miller-nicholas** [magento/magento2#7283]
### Preconditions
1. Magento 2.1.2 Release Archive 
2. Magento 2.4-develop

### Steps to reproduce
1. Login to Admin
2. go to Stores -> All Stores.
3. Sort by any column

### Expected result
Sorting should work or disable the  sorting option

### Actual result
sorting doesn't work

**Comment by VasylShvorak** [comment]
Thanks for reporting this issue. Created internal issue MAGETWO-69970 to investigate and track this issue.

**Comment by magento-engcom-team** [comment]
@magecodenet, thank you for your report.
We've created internal ticket(s) MAGETWO-69970 to track progress on the issue.

**Comment by afirlejczyk** [comment]
Hello  @magento-engcom-team 

I have an idea how to fix, but this view is using deprecated block 
```
Magento\Backend\Block\Widget\Grid
```
I would like to fix this issue, but I am wondering - should I rebuild this view and use UI component to render store listing ?

**Comment by ishakhsuvarov** [comment]
Hi @afirlejczyk 
Yes, you may do both ways, however migrating to use UI component is definitely a better approach.

**Comment by ishakhsuvarov** [comment]
Hi @afirlejczyk 
Are you still interested in working on this?

**Comment by afirlejczyk** [comment]
Hi @ishakhsuvarov 
Yes, I am. I will make a pull request within two weeks.

**Comment by magento-engcom-team** [comment]
Hi @magecodenet. Thank you for your report. 
The issue has been fixed in magento/magento2#17371 by @afirlejczyk in 2.2-develop branch
Related commit(s):
 - [f16859318ee6f57f629b78a99717ad732e41c675](https://github.com/magento/magento2/commit/f16859318ee6f57f629b78a99717ad732e41c675)
 - [81fc5aa1135e094fb6a3c8f762e8123918c635e6](https://github.com/magento/magento2/commit/81fc5aa1135e094fb6a3c8f762e8123918c635e6)
 - [c4fbe49677aac50c3fabffc7d8e67e060bccf581](https://github.com/magento/magento2/commit/c4fbe49677aac50c3fabffc7d8e67e060bccf581)
 - [8910b68ccf8b33863ff23da35ef941d9eeb153fd](https://github.com/magento/magento2/commit/8910b68ccf8b33863ff23da35ef941d9eeb153fd)
 - [7bc52b96586af3edc74174a477fe0689ee366ab1](https://github.com/magento/magento2/commit/7bc52b96586af3edc74174a477fe0689ee366ab1)
 - [c0e78e0645382bee9e7739966ccb4c5dfd05f67b](https://github.com/magento/magento2/commit/c0e78e0645382bee9e7739966ccb4c5dfd05f67b)
 - [471de671f98b8094e5e8fafc5bfaacfa8b213c46](https://github.com/magento/magento2/commit/471de671f98b8094e5e8fafc5bfaacfa8b213c46)
 - [c60df27b883fcb082b8bb9239532667ad635a583](https://github.com/magento/magento2/commit/c60df27b883fcb082b8bb9239532667ad635a583)
 - [448a333e3bcd31c392625dabdf060a5363f383cc](https://github.com/magento/magento2/commit/448a333e3bcd31c392625dabdf060a5363f383cc)
 - [e6b17ad869da220c265b2ae2e227c67e85d1d193](https://github.com/magento/magento2/commit/e6b17ad869da220c265b2ae2e227c67e85d1d193)

The fix will be available with the upcoming 2.2.9 release.

**Comment by Vigneshmuthusamy** [comment]
The issue still persists in Magento version 2.3.4.

**Comment by Vigneshmuthusamy** [comment]
Ideally, we could remove the sorting option here. There won't be a scenario for a user to sort here. They will search if they want to which is already there.

**Comment by srsathish92** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @srsathish92. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @srsathish92, here is your [Magento instance](https://i-7283-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-7283-2-4-develop.instances.magento-community.engineering/admin_4c42](https://i-7283-2-4-develop.instances.magento-community.engineering/admin_4c42)
Login: `b77b42f3` Password: `4b89a2fedd9b`
Instance will be terminated in up to 3 hours.

**Comment by srsathish92** [comment]
@magento-engcom-team I can able to reproduce in given instance.

here is the proof:
![screen1](https://user-images.githubusercontent.com/18184256/74050164-85e1ad00-49fb-11ea-9a32-d9d1df10fb6b.png)

====================================

![screen2](https://user-images.githubusercontent.com/18184256/74050168-88dc9d80-49fb-11ea-81b0-a52a8bf209dc.png)

**Comment by magento-engcom-team** [comment]
@srsathish92 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31309` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by afirlejczyk** [comment]
Is anybody is working to port changes for Magento 2.3.4? If not I will try to port changes from Magento 2.2 https://github.com/magento/magento2/pull/17371

**Comment by nitish-ranjan05** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nitish-ranjan05, here is your [Magento instance](https://i-7283-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-7283-2-4-develop.instances.magento-community.engineering/admin_0ae7](https://i-7283-2-4-develop.instances.magento-community.engineering/admin_0ae7)
Login: `9734a2b3` Password: `cbc5bcb13da2`
Instance will be terminated in up to 3 hours.

**Comment by Bartlomiejsz** [comment]
@nitish-ranjan05 are you working on porting https://github.com/magento/magento2/pull/17371 to 2.4-develop? I started to migrate Stores listing to ui components when I wasn't aware that this was done in 2.2, so I could pick this up in case it would be free

**Comment by afirlejczyk** [comment]
@nitish-ranjan05 please let us know if you plan to port changes, thank you.

**Comment by nitish-ranjan05** [comment]
@Bartlomiejsz @afirlejczyk It is available for work. you could pick it.

**Comment by magento-engcom-team** [comment]
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
